### PR TITLE
CI: use dockercmd when possible

### PR DESCRIPTION
**Pull request by HuKeping**
Part of #14603

Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@HuKeping many fails on jenkins

**Comment by HuKeping** [comment]
@LK4D4 how to replace with `dockercmd` when get something like
``` 
out, _, _, err := runCommandWithStdoutStderr(runCmd)
if err != nil {
		c.Fatalf("failed to run container: %v, output: %q", err, out)
}

if out != "test123\n" {
		c.Fatalf("container should've printed 'test123'")
}
```

If use `dockercmd`, the out will contain some message about "Warning" and that will fail the `if` line.

**Comment by coolljt0725** [comment]
@HuKeping  I have add a function ` dockerCmdWithStdoutStderr`  https://github.com/coolljt0725/docker/commit/c6cde91b7d2cb3671dc55cafc5ab693f9cb17cc8

**Comment by HuKeping** [comment]
@coolljt0725 so great!

**Comment by LK4D4** [comment]
Nice, LGTM

**Comment by calavera** [comment]
I'm going to say that LGTM, but github did not show the diff so I had to generate it manually :pensive:

**Pull request merged**
