### PR TITLE
Fixed #14036 - add two new options to the `exec` command

### LINKED ISSUE #14036: Proposal: --env for docker exec
Setting environment variables with docker exec currently requires a shell and a bit of extra code:
`docker exec 123abc /bin/sh -c 'export ONE=1; echo $ONE'`

Wouldn't it be nice if could just do this?
`docker exec -e ONE=1 123abc  echo $ONE`

Happy to contribute this and it looks quite straightforward to implement. Asked about this on IRC, too. What do you think?

### PR DESCRIPTION
**Pull request by henrysher**
```
-e, --env=[]               Set environment variables
--env-file=[]              Read in a file of environment variables
```

Fixed #14036
Signed-off-by: Henry Huang henry.s.huang@gmail.com

### CODE REVIEW

**Comment by henrysher** [comment]
Add two new options in `exec` command, similar usage to `run` command, also with some integration-cli tests.
```
-e, --env=[]               Set environment variables
--env-file=[]              Read in a file of environment variables
```
The environment variables provided in `exec` command will not clear the variables directly in the container, but replace the existing one or append for new one, as the func "**ReplaceOrAppendEnvValues**" re-used here (same to `run`, in *docker/utils*). For example, 
```
# docker exec CONTAINER1  env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=bdc64e485829
HOME=/root
```
```
# cat env.file
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

# docker exec --env-file env.file nginx env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
HOSTNAME=bdc64e485829
HOME=/root
```
```
# docker exec -e "TEST=H" -e "HOSTNAME=xxx" CONTAINER1  env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
HOSTNAME=xxx
TEST=H
HOME=/root
```
Please help review it.

**Comment by duglin** [comment]
ping @crosbymichael - any reason not to do this?

**Comment by henrysher** [comment]
I saw the comments from @cpuguy83 
> hmm... Not sure I see the technical reason to actually include this.

> docker exec is a hack to break into a container.
> It's purposefully designed to put you in the exact env as the container was started with.

**--env** will help the troubleshoot on the container more flexible and easier.
If you have concern about changing the environment variables for the runtime application, I could update my code to support the inpersistent way:
* env changed only for **exec** command execution, and will keep the runtime app in the same env.

what about yours: @duglin @crosbymichael @LK4D4 ?

**Comment by duglin** [comment]
If we can make it so that the envs specified on the exec commands are local to just that one exec (which is what I think people would expect) then the design SGTM.  I can see this being useful if your debug tooling needs certain env vars set in order to run properly.

**Comment by jhowardmsft** [comment]
Tagging this. I need to add to the Windows exec driver too

**Comment by tiborvass** [comment]
@henrysher sorry about late notice, we decided to not accept more flags on `exec`: https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec

Also, the corresponding issue was already closed.

**Pull request closed without merging**
