### PR TITLE
Skip some root tests

### PR DESCRIPTION
**Pull request by elboulangero**
Hello, here are two patches to conditionally skip tests that require root, for you to consider.

**More context**

In Debian we have a patch that skips privileged tests, under one big, ugly patch: https://salsa.debian.org/docker-team/docker/-/blob/master/debian/patches/test--skip-privileged-unit-tests.patch

I'm working on splitting this patch into smaller patches, so that I can submit what's relevant here in this PR.

Thanks !

### CODE REVIEW

**Comment by thaJeztah** [comment]
you're planning to add more commits to this PR, or in follow ups?

**Comment by elboulangero** [comment]
@thaJeztah As far as I can tell, no, no more commits planned for this PR.

**Review by AkihiroSuda — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by elboulangero** [comment]
Hi again, seeing that there was no update, I took this chance to sneak in an additional patch (and also rebase my branch on master)

**Review by thaJeztah — APPROVED** [review]
still LGTM

**Comment by thaJeztah** [comment]
I tried getting CI to pass; the s390x builds are flaky, but on this PR they continuously failed for some reason; wondering if skipping some tests revealed an issue that some state is not reset somewhere, causing tests to fail 🤔

**Comment by elboulangero** [comment]
I looked at the logs, however it seems (correct me if I'm mistaken) that the CI run as root, right? In such case this PR should not have any effect.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
