### PR TITLE
Update go-winio to v0.4.0 (go 1.8.x works on Windows)

### PR DESCRIPTION
**Pull request by darstahl**
Needed for https://github.com/moby/moby/pull/29030

**- What I did**

In order to support the upgrade to go1.8.x, go-winio needs to be updated to v0.4.0

**- How I did it**

Revendor go-winio

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by cpuguy83** [comment]
Looks like an issue with the vendor.
Can you make sure your version of vndr is up to date and re-run?

**Comment by darrenstahlmsft** [comment]
vndr doesn't seem to work (correctly) on Windows 😢 I'm attempting to get it to work on an Ubuntu VM, but it is deleting too many dependencies currently

**Comment by darrenstahlmsft** [comment]
Got it to work 😄

**Comment by cpuguy83** [comment]
Guessing the extra deps being removed is due to the docker/cli move since everything is compiling nicely.

**Comment by darrenstahlmsft** [comment]
CI is 💚

**Comment by cpuguy83** [comment]
Let's wait for #33111 if you don't mind.

**Comment by cpuguy83** [comment]
Ok merged the other and rebased this.

**Comment by darrenstahlmsft** [comment]
> Guessing the extra deps being removed is due to the docker/cli move since everything is compiling nicely.

In my initial runs it was due to an incorrect gopath. Was deleting actually used dependencies (like go-winio, which is what this was supposed to be updating)

**Review by cpuguy83 — COMMENTED** [review]
LGTM

**Review by mlaventure — APPROVED** [review]
LGTM (assuming :green_heart:)

**Comment by thaJeztah** [comment]
CI failed https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/13704/console not sure if there's anything related

**Comment by darrenstahlmsft** [comment]
>18:43:53 INFO: Downloading git...
18:43:54 Exception calling "DownloadFile" with "2" argument(s): "The remote name could 
18:43:54 not be resolved: 'www.nuget.org'"

Looks like a network hiccup. Can someone restart?

**Comment by darrenstahlmsft** [comment]
Rebased again due to conflicts. Windows CI was 💚

**Comment by mavenugo** [comment]
powerpc failure is a known issue : https://github.com/moby/moby/issues/33041.

LGTM.

**Pull request merged**
