### PR TITLE
Make the root fs private when the host root is not shared.

### PR DESCRIPTION
**Pull request by calavera**
This turns container creation to the default behavior that we had in Docker <= 1.6 when the root is not shared.

See https://github.com/docker/libcontainer/commit/907c7c17f04f140ded24fdbdd5b79ce6f3e8ab2a for the change between 1.6 and 1.7.

As discussed in https://github.com/docker/docker/issues/13775#issuecomment-110549123

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by vbatts** [comment]
also, there is `github.com/docker/docker/pkg/mount` with [GetMounts()](http://godoc.org/github.com/docker/docker/pkg/mount#GetMounts) and the [MountInfo](http://godoc.org/github.com/docker/docker/pkg/mount#MountInfo) struct.
Rather than just doing a `string.Contains()`

**Comment by calavera** [comment]
@vbatts what do you mean? That's what I'm using, `Mountinfo.Ops` is a string with the options. I haven't seen any way to get the different options from the info.

**Comment by vbatts** [comment]
oh shit. I looked too fast.

<3

**Comment by crosbymichael** [comment]
We are going to revert this change for now.

**Pull request closed without merging**
