### PR TITLE
Updating with man pages for distribution

### PR DESCRIPTION
**Pull request by moxiegirl**
Went through the man pages to update for the
v2 instance. Checked against the commands.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @dmp42 @stevvooe fyi I'm updating all existing docs as well

**Comment by stevvooe** [comment]
LGTM!

**Comment by moxiegirl** [comment]
@SvenDowideit @fredlf @jamtur01

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
