### PR TITLE
Update dockerd default network mtu

### PR DESCRIPTION
**Pull request by chaosmatrix**
**- What I did**

Set default network mtu as the minimum of
system's available interfaces's network mtu,
not always 1500

**- How I did it**
When docker start, if "mtu" didn't config,
get system's all avaliable interfaces's mtu,
find the minimum value.

**- How to verify it**
Consider this system interface information output

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c3:0b:39:56:2c:d1 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.3/24 brd 10.0.2.3.255 scope global dynamic ens33
       valid_lft 1285sec preferred_lft 1285sec
    inet6 fe80::88a6:b4e3:8129:5223/64 scope link
       valid_lft forever preferred_lft forever
3: ens34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c3:0c:29:81:af:de brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.3/24 brd 10.0.0.255 scope global dynamic ens34
       valid_lft 979sec preferred_lft 979sec
    inet6 fe80::33cd:677e:6255:22e3/64 scope link
       valid_lft forever preferred_lft forever
```

When "dockerd" start and didn't config "mtu",
the default network mtu will be **1400** (min(1400, 1500, 65536)),
instead of **1500**, and this will affect all container run under this "dockerd".

This can prevent some network problem cause by Incorrect network mtu,
especially when interface configured network mtu less than **1500**
and user didn't config "mtu" when start dockerd.

**- Description for the changelog**

Set default network mtu as the minimum of
system's available interfaces's network mtu,
not always 1500

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Older versions of Docker used to attempt to detect the MTU to use, but that feature was removed in https://github.com/moby/moby/pull/18108 (some explanation is included there), so not sure if automatic detection of these values should be added back, but let me ask some people;

ping @fcrisciani @mavenugo PTAL

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by olljanat** [comment]
Derek remove label: status/failing-ci

**Comment by olljanat** [comment]
Derek add label: area/networking

**Pull request closed without merging**
