### PR TITLE
[WIP] Builder long running session - easier publishing and consuming

### PR DESCRIPTION
**Pull request by simonferquel**
**- What I did**

Based on @tonistiigi work on context streaming (#32677), I iterated to try to find an easier way to publish and consume RPC components.
So what I did, is
- Fully embrace gRPC (removing the rpc protocol abstraction)
- Enabled publishing and consuming gRPC services declared in .proto file in a very easy way
- Enabled an more straightforward way to publish and consume stream based functions (like @tonistiigi diffcopy implementation)

One thing that we wanted is to have as much flexibility as possible about versioning, and having the possibility to publish multiple instances of the same component on the same grpc server.

This has been done for low level streaming functions, but not yet for `protoc` based services (on the server side, it is quite easy to do, but on the client side, this would require a customized version of https://github.com/gogo/protobuf to be able to inject an instance ID in the method url).

**- How I did it**

- For .proto declared services, I simply added a way to publish a `grpc.ServiceDesc` to a server session, and I exposed the grpc client connection on the client side `session.Caller` interface so that client proxy factories generated by protoc can work.
- For low level stream based function, I enabled a kind of "record & replay" API that allows stream handler publishers to register their handlers in much simpler way. The very good side effect of that, is that there is a very nice symmetry between the server side publishing API and the client side consuming API.

**- How to verify it**

The last 3 commits in the PR add a sample high level `protoc` based grpc service to pull credentials on demand (instead of pushing the whole list of available credentials upfront), and a low level `echo` stream handler.

@tonistiigi @dnephin @cpuguy83 @dmcgowan, please give feedback

### CODE REVIEW

**Comment by simonferquel** [comment]
The 3 last commits add garbage to the builder, but they are very usefull to demonstrate api usage. If the design get validated eventually, I'll remove them

**Comment by simonferquel** [comment]
@stevvooe @thaJeztah you might also be interested

**Comment by tonistiigi** [comment]
So this comes in 2 implementations, one is limited to service name based discovery and a single instance of the service. The other(`AllowStream`) is very similar to the current implementation. I'd say it is quite more complicated actually as introduces concepts as services, instances, and methods to the hijack layer while the current one only cares about the method url. `AllowStream` generates one specific type of stream method like the current implementation.

Also, in the current "echo" example, low-level concepts like streams and methods leaks to the cli/daemon implementation. I very much like the "feature/attachable" abstraction that should expose a clean Go API to accomplish a specific feature.

I think it only makes sense to limit this to grpc if we can get benefits from reusing the generated proto code for services. With the current example, it is not actually reusing any generated grpc proto. Proto is only for types same way as with current generic transport logic.

Looking at the caller code, it is also much more complicated now. Instead of previous `supports()` and `call()` we now have `supports()`, `grpcconn()`, `liststreams()`, `supportstream()`, `connecttostream()`.

---

Let's use the fssession as an example of how it could look like as that is the more complicated and requires instances for source locations and method discovery for protocols. The goal is to define something that would work if this case and wouldn't require modifications for the simpler auth case.

The proto would look:

```
service FSSession {
    rpc DiffCopy(stream DiffCopyReq) returns (stream DiffCopyResp)
    rpc Tar(stream TarReq) returns (stream TarResp)
}
```

The go API for fssession feature could be:

```
client:
fssession.NewFSSendProvider(name, root string, excludes []string) session.Attachment
session.Allow(session.Attachment)

server:
fssession.TryFSSend(session, name) (fssession.FSSender, error)
sender.Send(FSSendRequestOpt) error 
```

Now the problem is how to cleanly implement these methods in `fssession` package so that they use the generated proto definition.

In the handler side, `NewFSSendProvider` implementation needs to create an instance of the handler that satisfies the rpc interface. After that is needs to register this service while it is scoped to the instance name. This could be done by adding a prefix to the service name in `ServiceDesc` before registering it or using an interceptor to catch the instance name from method url. Another method would be to generate this code for each service.

In both cases this could be a helper session method `expose(name, serviceDesc, impl)` that does this so fssession itself doesn't need to do anything special with the proto. After this method is called session would already be exposed in pre-hijack headers as well, either by storing them or using `ServiceInfo()`. I think it is better to use the previous implementation of exposing only method urls instead on different types as these are part of wire definition and not allowed to change if any grpc concepts change in the future.

The daemon-side `TryFSSend` is a bit more complicated. The session should expose helper method that allows discovery and returns a grpcClient that is already mapped to a specific instance. `session.supports(methodurl) bool` should be enough for discovery. To get the client we would need a function like `NewFSSessionClientWithName(session.grpcconn(), name)` as the current generated client code doesn't allow changing method URL. In the long run we could generate this code per service but in the beginning, when we have less than 5 methods these one liners can be just written by hand. Maybe, client-interceptor could be used but I think we still need an object that adds something to the request that interceptor can detect.

**Comment by tonistiigi** [comment]
For the auth feature, it is ok expose the grpc client to daemon directly. There is no need to wrap that but getting access to that client should be through a (Try*) method defined in auth pkg and the client returned would be mapped to an instance(or maybe instances are optional as that should also work well if we only expose method urls).

**Comment by simonferquel** [comment]
I really like the named service instance approach. To resolve that, I ll make a fork of gogo protobuf adding an option to support custom service names when generating proxy code. That would certainly help us experiment and see if we can have a good story about other requirements (I am thinking mainly about versioning of grpc services)

**Comment by tonistiigi** [comment]
@simonferquel I think the naming can be optional as we currently only need it for fssession and it is easy to wrap these 2 fssession client methods without a custom proto plugin. We don't need to expose a concept of instance or name, just reuse the service definition with a custom name if it is needed. In that case, this would just mean removing the current `allowstream/connecttostream` parts and changing the exposed headers to method URLs.

**Comment by simonferquel** [comment]
Still, having tooling support for avoiding mistyping client proxy code (especially regarding API evolutions etc) seem better. I looked at gogo protobuf and the code base seem quite simple.

**Comment by simonferquel** [comment]
I removed the low level streaming functions, and with a slightly modified version of gogo/protobuf (see https://github.com/gogo/protobuf/pull/291), I now support named instances for grpc services based on .proto files.

This way I was able to recreate an echo package that supports multiple instances, and whose underlying communication interface is fully generated from .proto files.

Btw, I really like the approach of generating all protobuff / grpc stuff in an internal package and provide a clean API fitting well with moby's type system (for ex, auth rely on a provider of AuthConfig whose type is the same as everywhere else in moby's codebase and not a protobuf message), as well as with common go constructs (echo API using simple string channels instead of the underlying object stream). I think this pattern should be generalized.

**Comment by tonistiigi** [comment]
That patch will probably not be accepted as this is usually done with a custom plugin. They probably want to keep consistency with `golang/protobuf` . Anyway, the proto generation part doesn't worry me much as even if there is a clean solution it can be a follow-up optimization. I still noticed though that discovery is based on service names instead of method urls that are not safe and doesn't allow adding methods.

**Comment by stevvooe** [comment]
We need to be careful with going down this path. The fact that package/service name set the URL is kind of a core part of GRPC. If we go down another path, it is going to make using GRPC very challenging. Allowing any kind of parameterization basically removes the whole point of grpc.

It sounds like we should push this variation into a proper discovering mechanism.

I would recommend explaining this problem on the grpc project mailing list and see if they have a solution.

**Comment by tonistiigi** [comment]
closing this based on comments in #32677

**Pull request closed without merging**
