### PR TITLE
Make /etc/hosts, /etc/resolv.conf, /etc/hostname read only if --read-only enabled

### LINKED ISSUE #11577: Files like hosts, resolve.conf, and hostname are read-write if --read-only is enabled.
**Problem**
 
Files like hosts, resolve.conf, and hostname are read-write if --read-only is enabled.
 
**Solution**
 
When running read-only containers, docker mounted files such as `/etc/hosts`, `/etc/resolv.conf`, and `/etc/hostname` should also be changed from their default read-write permissions to read-only.

### PR DESCRIPTION
**Pull request by runcom**
Carry and fixes #11577 
/cc @LK4D4 you weren't sure about this I've read in the issue

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by tiborvass** [comment]
@runcom if you're carrying someone else's PR it's nice to keep their commit :) I suggest you just amend his commit.

**Comment by runcom** [comment]
@tiborvass he hasn't any commit for this I have looked at his github repo and docker repo to see if I could keep his commit of course. But seems he isn't active since April 2 (maybe "carry" was misleading) sorry for this

**Comment by tiborvass** [comment]
@runcom I believe it's this https://github.com/mauriyouth/docker/commit/8243d9a5fc10a4ac68d3604a9a9f21de7fb94cff

**Comment by runcom** [comment]
@tiborvass aww ok really sorry for that

**Comment by tiborvass** [comment]
@runcom absolutely no problem :)

**Comment by runcom** [comment]
@tiborvass so should I take it even if I'm not using that? Or just commit with --author and use his name/email?

**Comment by tiborvass** [comment]
@runcom author is fine now.

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
