### PR TITLE
Apparmor engine

### PR DESCRIPTION
**Pull request by stefanberger**
The following two patches fix ptrace and /bin/ps related apparmor denials. Presumably none of the performed actions are malicious and therefore can be allowed by the profile.

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @ewindisch

**Comment by ewindisch** [comment]
I've taken a look at this and have found that our usage of 'ps' does not depend on the ptrace functionality and ps itself does not fail should it be unable to ptrace. As a result, I propose instead specifying a 'deny ptrace' which will squash the audit messages without granting this privilege.

**Comment by stefanberger** [comment]
@ewindisch I updated the 2nd patch; yes, the ps tool does not depend on ptrace for correct functioning as it seems, so I modified the patch to deny it now following your suggestion; I needed to deny it in both places, the /usr/bin/docker as well as the subprofile /bin/ps to have the log silenced.

**Comment by ewindisch** [comment]
The 'file' permission is a bit too broad for 'ps'. Perhaps you could test my branch and make PRs there?

https://github.com/ewindisch/docker/tree/apparmor-engine-policy-nofile

**Pull request closed without merging**
