### PR TITLE
Pass excludes/options to tar unarchiver via environment versus cmd line

### LINKED ISSUE #10426: Load fails w/ FATA[0000] Error: Untar fork/exec /usr/bin/docker: argument list too long
```
$ cat /tmp/image.tar | docker load
FATA[0000] Error: Untar fork/exec /usr/bin/docker: argument list too long 
```

You can get this error if you have a several hundred images on your host.  I had ~450 images (as reported by `docker images | wc -l`) and when loading a saved image it would fail consistently w/ this error.  

This looks like it might be related to https://github.com/docker/docker/blob/092d52281d20e3456677ac11d781abf1cd0bdd8f/graph/load.go#L41 which constructs a list of all image IDs on the host which is then serialized to JSON and passed as an argument to a subsequent exec call.

After deleting my images down to ~250, `docker load` started working again.

```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```
```
$ docker info
Containers: 194
Images: 1526
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 1921
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 8
Total Memory: 15.36 GiB
Name: laptop
ID: PIYC:2PIA:5YSP:XY2N:YE2Z:KO5T:YCEJ:VWQJ:MUUO:KC54:GKES:CKFT
Debug mode (server): true
Debug mode (client): false
Fds: 10
Goroutines: 10
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Registry: [https://index.docker.io/v1/]
```

```
$ uname -a
Linux laptop 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by estesp**
Fixes #10426

Because of the ability to easily overload the shell max argument list
length once the image count is several hundred, `docker load` will
start to fail because of this as it passes an excludes list of all
images in the graph.  This patch uses a tmp file written and passed to
the unarchiver to get around the argument length limitation.

Docker-DCO-1.1-Signed-off-by: Phil Estes estesp@linux.vnet.ibm.com (github: estesp)

### CODE REVIEW

**Comment by unclejack** [comment]
@estep I think this should be done over stdio, instead of writing to a temporary file. Once we're done reading the json, we can start reading the actual layer data.

**Comment by estesp** [comment]
@unclejack keep forgetting to get back to this--I'm willing to go that route, but it seems a bit more involved than having a temp file.  @crosbymichael your comment in the original issue made me think you already had an implementation in mind--any thoughts here?

**Comment by estesp** [comment]
@unclejack we tried working it within the same stream, but ran into problems with the buffers. @crosbymichael and I decided that given the environment size max is extremely large it was a much simpler solution rather than figuring out why the tar header and rest of stdin can't be read properly after decoding the JSON.

**Comment by LK4D4** [comment]
@estesp Whoa! nice hack. But I still prefer pipes, you can use `stderr` or add new pipe to `ExtraFiles` like in `daemon/networkdriver/portmapper/proxy.go`

**Comment by crosbymichael** [comment]
@LK4D4 This seems like the simplest way and env vars have a large size maximum so we won't run into issues.  We were dealing with pipes for a while and this was simple and straight forward, what do you think?

**Comment by LK4D4** [comment]
@crosbymichael I'm okay with env if you okay. Though it is produce much more allocations then encoding to pipe, but this might be not an issue for us.

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
