### PR TITLE
Vendoring libnetwork 2c8b683

### PR DESCRIPTION
**Pull request by mavenugo**
Pulling in https://github.com/docker/libnetwork/pull/1623 to address #30295

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

would be nice to have a "type" for name servers, so that we don't pass them along as strings

**Comment by thaJeztah** [comment]
ping @vieux FYI, I agree we should have this in 1.13.1

**Comment by mavenugo** [comment]
ping @aboch fyi.

@thaJeztah @vieux as you can see, am vendoring this only in 1.13.x branch.
@sanimej has an open item to vendor libnetwork master into docker master and that vendoring will pull in this patch into docker master.

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
