### PR TITLE
Bump SwarmKit to 8d8689d5a94ac42406883a4cef89b3a5eaec3d11

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/docker/swarmkit/compare/a84c01f49091167dd086c26b45dc18b38d52e4d9...8d8689d5a94ac42406883a4cef89b3a5eaec3d11

Changes included;

- https://github.com/docker/swarmkit/pull/2735 Assign secrets individually to each task
- https://github.com/docker/swarmkit/pull/2759 Adding a new `Deallocator` component
- https://github.com/docker/swarmkit/pull/2738 Add additional info for secret drivers
- https://github.com/docker/swarmkit/pull/2775 Increase grpc max recv message size
  - addresses https://github.com/moby/moby/issues/37941
  - addresses https://github.com/moby/moby/issues/37997
  - follow-up to https://github.com/moby/moby/pull/38103

### CODE REVIEW

**Comment by tiborvass** [comment]
Following failures on janky:

```
02:00:32 FAIL: docker_api_swarm_node_test.go:75: DockerSwarmSuite.TestAPISwarmNodeDrainPause
02:00:32 
02:00:32 [dc14bd3a2292b] waiting for daemon to start
02:00:32 [dc14bd3a2292b] daemon started
02:00:32 
02:00:32 [d19712fc63806] waiting for daemon to start
02:00:32 [d19712fc63806] daemon started
02:00:32 
02:00:32 waited for 1.47956855s (out of 30s)
02:00:32 waited for 42.945818ms (out of 30s)
02:00:32 waited for 217.871823ms (out of 30s)
02:00:32 waited for 2.461052573s (out of 30s)
02:00:32 waited for 10.754297ms (out of 30s)
02:00:32 docker_api_swarm_node_test.go:104:
02:00:32     waitAndAssert(c, defaultReconciliationTimeout*2, reducedCheck(sumAsIntegers, d1.CheckActiveContainerCount, d2.CheckActiveContainerCount), checker.Equals, instances)
02:00:32 docker_utils_test.go:441:
02:00:32     c.Assert(v, checker, args...)
02:00:32 ... obtained int = 3
02:00:32 ... expected int = 1
02:00:32 ... output: "1f0d412d405f\ne2ccd0f2873d\n80e426fa8841\n"
02:00:32 
02:00:32 waited for 1m0.055336515s (out of 1m0s)
02:00:32 [dc14bd3a2292b] exiting daemon
02:00:32 [d19712fc63806] exiting daemon
02:01:07 
02:01:07 ----------------------------------------------------------------------
...
02:00:32 FAIL: docker_api_swarm_node_test.go:75: DockerSwarmSuite.TestAPISwarmNodeDrainPause
02:00:32 
02:00:32 [dc14bd3a2292b] waiting for daemon to start
02:00:32 [dc14bd3a2292b] daemon started
02:00:32 
02:00:32 [d19712fc63806] waiting for daemon to start
02:00:32 [d19712fc63806] daemon started
02:00:32 
02:00:32 waited for 1.47956855s (out of 30s)
02:00:32 waited for 42.945818ms (out of 30s)
02:00:32 waited for 217.871823ms (out of 30s)
02:00:32 waited for 2.461052573s (out of 30s)
02:00:32 waited for 10.754297ms (out of 30s)
02:00:32 docker_api_swarm_node_test.go:104:
02:00:32     waitAndAssert(c, defaultReconciliationTimeout*2, reducedCheck(sumAsIntegers, d1.CheckActiveContainerCount, d2.CheckActiveContainerCount), checker.Equals, instances)
02:00:32 docker_utils_test.go:441:
02:00:32     c.Assert(v, checker, args...)
02:00:32 ... obtained int = 3
02:00:32 ... expected int = 1
02:00:32 ... output: "1f0d412d405f\ne2ccd0f2873d\n80e426fa8841\n"
02:00:32 
02:00:32 waited for 1m0.055336515s (out of 1m0s)
02:00:32 [dc14bd3a2292b] exiting daemon
02:00:32 [d19712fc63806] exiting daemon
02:01:07 
02:01:07 ----------------------------------------------------------------------
...
02:14:30 FAIL: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
02:14:30 
02:14:30 [d8ccf6bfdbe20] waiting for daemon to start
02:14:30 [d8ccf6bfdbe20] daemon started
02:14:30 
02:14:30 [d63bfdc5da340] waiting for daemon to start
02:14:30 [d63bfdc5da340] daemon started
02:14:30 
02:14:30 [d6291a6c678f7] waiting for daemon to start
02:14:30 [d6291a6c678f7] daemon started
02:14:30 
02:14:30 [d63bfdc5da340] exiting daemon
02:14:30 [d63bfdc5da340] waiting for daemon to start
02:14:30 [d63bfdc5da340] daemon started
02:14:30 
02:14:30 [d6291a6c678f7] exiting daemon
02:14:30 [d6291a6c678f7] waiting for daemon to start
02:14:30 [d6291a6c678f7] daemon started
02:14:30 
02:14:30 [d63bfdc5da340] exiting daemon
02:14:30 [d63bfdc5da340] waiting for daemon to start
02:14:30 [d63bfdc5da340] daemon started
02:14:30 
02:14:30 [d6291a6c678f7] exiting daemon
02:14:30 [d6291a6c678f7] waiting for daemon to start
02:14:30 [d6291a6c678f7] daemon started
02:14:30 
02:14:30 docker_cli_swarm_test.go:1379:
02:14:30     c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
02:14:30 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000966ae0), Stderr:[]uint8(nil)} ("exit status 1")
02:14:30 ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
02:14:30 
02:14:30 
02:14:30 [d8ccf6bfdbe20] exiting daemon
02:14:30 [d63bfdc5da340] exiting daemon
02:14:30 [d6291a6c678f7] exiting daemon
02:14:33 
02:14:33 ----------------------------------------------------------------------
```

Kicking janky again to see if it's flakiness.

**Comment by thaJeztah** [comment]
Only one failure this time, which is a known flaky test https://github.com/moby/moby/issues/32673, and being worked on in https://github.com/moby/moby/pull/37833

```
19:34:45 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
19:34:45 
19:34:45 [d49a8a2493588] waiting for daemon to start
19:34:45 [d49a8a2493588] daemon started
19:34:45 
19:34:45 [dcb19b9338720] waiting for daemon to start
19:34:45 [dcb19b9338720] daemon started
19:34:45 
19:34:45 [d26d3b54b3a05] waiting for daemon to start
19:34:45 [d26d3b54b3a05] daemon started
19:34:45 
19:34:45 [d49a8a2493588] exiting daemon
19:34:45 Waiting for election to occur...
19:34:45 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded: [dcb19b9338720] (*Daemon).GetNode: NodeInspectWithRaw("v6imthrkueel4q4jb05g5eoet") failed
19:34:45 waited for 20.001386562s (out of 30s)
19:34:45 [dcb19b9338720] exiting daemon
19:34:45 [d26d3b54b3a05] exiting daemon
```

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
