### PR TITLE
Annotate some swagger documented types as int64

### LINKED ISSUE #39131: Swagger spec for HealthConfig type's time.Duration fields does not annotate them as 64-bit ints
**Description**

The swagger spec defines [`HealthConfig`'s `Interval`, `Timeout` and `StartPeriod` fields](https://github.com/moby/moby/blob/2bfa24b39393f3e6e1ec38e1d76004e5a50d109f/api/swagger.yaml#L597) to have `type: "integer"`, which means a Swagger generator defaults to emitting them as 32-bit integer fields. However [the corresponding golang type](https://github.com/moby/moby/blob/2bfa24b39393f3e6e1ec38e1d76004e5a50d109f/api/types/container/config.go#L17) for these fields is `time.Duration`, so these fields should be annotated with `format: "int64"` (like [this other nanoseconds field](https://github.com/moby/moby/blob/2bfa24b39393f3e6e1ec38e1d76004e5a50d109f/api/swagger.yaml#L3207)).

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
```

**Output of `docker info`:**

```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by gesellix**
Using the swagger.yaml to generate api models will create incompatible field types. Some inconsistencies had already been mentioned at #39131. I've added more fixes from real life experience, some only occurring on Windows.

Closes #39131

Signed-off-by: Tobias Gesellchen <tobias@gesellix.de>

**- What I did**

The following types documented in api/swagger.yaml and docs/api/v1.41.yaml have been adjusted to match the types in the Golang model:

- [container.HealthConfig.Interval](https://github.com/moby/moby/blob/8abb84c7342a19009d777ef3d871c0b2a5c032a5/api/types/container/config.go#L46-L48
)
- [container.HealthConfig.Timeout](https://github.com/moby/moby/blob/8abb84c7342a19009d777ef3d871c0b2a5c032a5/api/types/container/config.go#L46-L48
)
- [container.HealthConfig.StartPeriod](https://github.com/moby/moby/blob/8abb84c7342a19009d777ef3d871c0b2a5c032a5/api/types/container/config.go#L46-L48
)
- [container.WaitResponse.StatusCode](https://github.com/gesellix/moby/blob/8abb84c7342a19009d777ef3d871c0b2a5c032a5/api/types/container/wait_response.go#L18)
- [types.ImageSummary.SharedSize](https://github.com/moby/moby/blob/8abb84c7342a19009d777ef3d871c0b2a5c032a5/api/types/image_summary.go#L78)
- [volume.UsageData.Size](https://github.com/moby/moby/blob/8abb84c7342a19009d777ef3d871c0b2a5c032a5/api/types/volume/volume.go#L62-L74)
- [volume.UsageData.RefCount](https://github.com/moby/moby/blob/8abb84c7342a19009d777ef3d871c0b2a5c032a5/api/types/volume/volume.go#L62-L74)

**- How I did it**

Changed the swagger.yaml and v1.41.yaml, compared with moby's Golang types (didn't check any older api versions).

**- How to verify it**

See the list above, with each entry linking to the Golang source for easier comparison.

**- Description for the changelog**

Annotate some Swagger documented types as int64, matching the Golang types.

**- A picture of a cute animal (not mandatory but encouraged)**

ladybug

### CODE REVIEW

**Comment by gesellix** [comment]
Looks like I forgot to update the `types/image_summary.go` for the fixed typo (`s/imagem/image,/`), I'm going to fix that soon.

**Comment by thaJeztah** [comment]
Thanks!

Hmm.. validate is failing 🤔 ;


```
The result of hack/generate-swagger-api.sh differs
 
diff --git a/api/types/image_summary.go b/api/types/image_summary.go
index 53c2885758..90b983a25c 100644
--- a/api/types/image_summary.go
+++ b/api/types/image_summary.go
@@ -61,7 +61,7 @@ type ImageSummary struct {
 	// List of image names/tags in the local image cache that reference this
 	// image.
 	//
-	// Multiple image tags can refer to the same imagem and this list may be
+	// Multiple image tags can refer to the same image, and this list may be
 	// empty if no tags reference the image, in which case the image is
 	// "untagged", in which case it can still be referenced by its ID.
 	//

Please update api/swagger.yaml with any API changes, then 
run hack/generate-swagger-api.sh.
```

Ah! I think that's because that bit is related to the Go types;
https://github.com/moby/moby/blob/235f86270d4976e7d17c11eccdb65f81d76f5c40/api/types/image_summary.go#L64

and

https://github.com/moby/moby/blob/235f86270d4976e7d17c11eccdb65f81d76f5c40/api/types/types.go#L51

So those will have to be updated as well 😅

**Comment by gesellix** [comment]
@thaJeztah thanks for pointing me to the second occurrence at https://github.com/moby/moby/commit/235f86270d4976e7d17c11eccdb65f81d76f5c40 :)

**Comment by gesellix** [comment]
Wow... "Upstream fix" somewhere far away closed this pull request. TIL.

**Comment by gesellix** [comment]
The failing test case doesn't seem to be related to my changes 🤔 

```
[2022-05-23T20:28:57.914Z] === Failed
[2022-05-23T20:28:57.914Z] === FAIL: amd64.integration-cli TestDockerSuite/TestExecWithPrivileged (0.83s)
[2022-05-23T20:28:57.914Z]     docker_cli_exec_test.go:463: assertion failed: 
[2022-05-23T20:28:57.914Z]         Command:  /usr/local/cli/docker logs parent
[2022-05-23T20:28:57.914Z]         ExitCode: 1
[2022-05-23T20:28:57.914Z]         Error:    exit status 1
[2022-05-23T20:28:57.914Z]         Stdout:   Privileged exec has not run yet
[2022-05-23T20:28:57.914Z]         Privileged exec has not run yet
[2022-05-23T20:28:57.914Z]         Privileged exec has not run yet
[2022-05-23T20:28:57.914Z]         
[2022-05-23T20:28:57.914Z]         Stderr:   error from daemon in stream: Error grabbing logs: invalid character 'l' after object key:value pair
[2022-05-23T20:28:57.914Z]         
[2022-05-23T20:28:57.914Z]         
[2022-05-23T20:28:57.914Z]         
[2022-05-23T20:28:57.914Z]         Failures:
[2022-05-23T20:28:57.914Z]         ExitCode was 1 expected 0
[2022-05-23T20:28:57.914Z]         Expected no error
[2022-05-23T20:28:57.914Z]     --- FAIL: TestDockerSuite/TestExecWithPrivileged (0.83s)
[2022-05-23T20:28:57.914Z] 
[2022-05-23T20:28:57.914Z] === FAIL: amd64.integration-cli TestDockerSuite (1370.50s)
[2022-05-23T20:28:57.914Z] 
```

**Comment by thaJeztah** [comment]
> Wow... "Upstream fix" somewhere far away closed this pull request. TIL.

Ah, yes, those can be fun; even more so if the `fix #xyz` is in the commit message (can't edit those after the fact)

> The failing test case doesn't seem to be related to my changes 

Probably some flakiness; let me kick CI again

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by gesellix** [comment]
This one also doesn't seem to be related:

```
2022-05-24T12:59:49.289Z] === FAIL: github.com/docker/docker/integration-cli TestDockerSuite/TestRunContainerWithRmFlagCannotStartContainer (2.20s)
[2022-05-24T12:59:49.289Z]     docker_cli_run_test.go:2770: Expected not to have containers f11f42a8a90e
[2022-05-24T12:59:49.289Z]         
[2022-05-24T12:59:49.289Z]     --- FAIL: TestDockerSuite/TestRunContainerWithRmFlagCannotStartContainer (2.20s)
[2022-05-24T12:59:49.289Z] 
[2022-05-24T12:59:49.289Z] === FAIL: github.com/docker/docker/integration-cli TestDockerSuite (2660.72s)
[2022-05-24T12:59:49.289Z] 
```

If I can do anything to make it work, please leave a note here :)

**Comment by thaJeztah** [comment]
Looks like that test was flaky before; https://github.com/moby/moby/issues/11966 (and I saw a couple of other mentions). Should not be related, but let me kick it once more just to see if we can make it nice and green 😅

**Review by tianon — APPROVED** [review]

**Pull request merged**
