### PR TITLE
Add warning log when high priority graphdriver used before

### PR DESCRIPTION
**Pull request by daehyeok**
added warnning log when high priority graphdrvier used before for feature request #8270

Signed-off-by: daehyeok.Mun daehyeok@gmail.com

### CODE REVIEW

**Comment by daehyeok** [comment]
I modified code to change log message.
my directory list and warning message are like below.
happy new year
```
root@ubuntu:/var/lib/docker# ls -al /var/lib/docker
lrwxrwxrwx 1 root root 19 12월 29 02:00 /var/lib/docker -> /root/docker_mount/
root@ubuntu:/var/lib/docker# ls /var/lib/docker
aufs  btrfs  containers  execdriver  graph  init  linkgraph.db  repositories-aufs  tmp  trust  vfs  volumes
```

```WARN[0000] graphdriver aufs selected. Warning: your graphdriver directory /root/docker_mount already contains data managed by other graphdrivers: btrfs,vfs```

**Comment by LK4D4** [comment]
@daehyeok I'll retry tomorrow, thank you.

**Comment by SvenDowideit** [comment]
awesome, @daehyeok thank you for your patience - figuring out good error messages is hard for all of us :) much LGTM!

**Comment by LK4D4** [comment]
@daehyeok 
```
ls /var/lib/docker
btrfs  containers  execdriver  graph  init  tmp  trust  vfs  volumes  linkgraph.db  repositories-btrfs
```
```
docker -d -s overlay
```
no warning, but
```
ls /var/lib/docker
btrfs  containers  execdriver  graph  init  overlay  tmp  trust  vfs  volumes  linkgraph.db  repositories-btrfs  repositories-overlay
```

**Comment by daehyeok** [comment]
@LK4D4 
it will not print warning when user use -s option. if you start docker with ```docker -d``` command, it will show warning message. It's for situation like #8270 issue. 
I think it don't need to print when user selected graph driver.

**Comment by LK4D4** [comment]
@dahyeok hmm, ok, then I'll recheck logic, because now I'm not fully follow it :)

**Comment by SvenDowideit** [comment]
@jfrazelle @tiborvass @crosbymichael would it be possible to add to `docker info` `/var/lib/docker also contains data from other graphdrivers: devicemapper` ? (in a separate PR?)

**Comment by tiborvass** [comment]
@SvenDowideit sure

**Comment by tiborvass** [comment]
LGTM

Ping @crosbymichael

**Comment by crosbymichael** [comment]
I'll carry this one with a change I want to make and merge.

@daehyeok Thanks for the PR!

**Pull request closed without merging**
