### PR TITLE
Fix (*Ulimit).String() function. Closes #11769.

### LINKED ISSUE #11769: Fix (*Ulimit).String() function
in `pkg/ulimit/ulimit.go`.
For `u.Soft` and `u.Hard` should be `%d` printf verb.

### PR DESCRIPTION
**Pull request by blatyo**
Closes #11769.

Signed-off-by: Allen Madsen blatyo@gmail.com

### CODE REVIEW

**Comment by icecrime** [comment]
Waiting for CI, but LGTM, thanks!

**Comment by blatyo** [comment]
I don't believe this failure is due to my changes.

**Comment by jfrazelle** [comment]
ya dont worry about the windows failure

**Comment by duglin** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
