### PR TITLE
More docs 1.12.1 cherry picks

### PR DESCRIPTION
**Pull request by SvenDowideit**
@thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
*don't merge yet*, @tiborvass is working on a cherry-pick for code

**Comment by SvenDowideit** [comment]
don't merge yet, @tiborvass is working on a cherry-pick for code

**Comment by tiborvass** [comment]
@SvenDowideit @thaJeztah  can i merge ?

**Comment by thaJeztah** [comment]
yes, thanks!

**Pull request merged**
