### PR TITLE
Fix deadlock on plugin shutdown.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by tonistiigi** [comment]
@anusha-ragunathan Failures in experimental do not look like the already reported flaky ones.

**Comment by anusha-ragunathan** [comment]
https://github.com/docker/docker/pull/25553/files changed how "Active" state was interpreted. It's the desired state and not the actual state. As a result, we dont need to update any state of plugin shutdown.

**Pull request merged**
