### PR TITLE
correct integration error for issue 32069

### LINKED ISSUE #32069: make test-integration-cli fails in docker/master
**Description**

I failed to run integration test in docker/master

Here is the error log:
```
---> Making bundle: build-integration-test-binary (in bundles/17.05.0-dev/build-integration-test-binary)
Building test dir: integration-cli
++ cd integration-cli
++ go test -c -o /go/src/github.com/docker/docker/bundles/17.05.0-dev/build-integration-test-binary/../test-integration-cli/test.main -ldflags -w -tags 'autogen netgo static_build apparmor pkcs11 seccomp selinux daemon journald libdm_no_deferred_remove' -installsuffix netgo -i
# github.com/docker/docker/integration-cli
./docker_cli_build_test.go:4786: undefined: withDockerfile
./docker_cli_build_test.go:4817: undefined: withDockerfile
./docker_cli_build_test.go:4817: undefined: withBuildFlags
./docker_cli_build_test.go:5648: undefined: withBuildFlags
make: *** [test-integration-cli] Error 1
```

Here is the git message:
```
root@ip-172-31-23-42:~/gocode/src/github.com/allencloud/docker# git log
commit 8008f6529394d8c458ccf58f4763754681568b57
Merge: 2fa8fe4 50c4475
Author: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
Date:   Fri Mar 24 13:04:47 2017 +0900

    Merge pull request #31608 from vdemeester/integration-cli-package

    [test-integration] Introduce a `cli` package for test-integration
```

`Git status`:
```
root@ip-172-31-23-42:~/gocode/src/github.com/allencloud/docker# git status
HEAD detached at origin/master
nothing to commit, working directory clean
```

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

fixes #32069 and remove redundant comment and fix typo.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tonistiigi** [comment]
@allencloud Didn't see this before #32071 . I think the correct way is to use `cli.WithFlags`. We can close mine if you make that change.

**Comment by allencloud** [comment]
Oh, Thanks @tonistiigi. I updated this one. PTAL

**Comment by vdemeester** [comment]
ah I didn't see that one before merging @tonistiigi's PR 😓 
@allencloud should we close this one ?

**Comment by allencloud** [comment]
That is all right. I am closing this. @vdemeester  😃

**Comment by vdemeester** [comment]
Thanks @allencloud 🤗

**Pull request closed without merging**
