### PR TITLE
refactor attach to not use internal data structures

### PR DESCRIPTION
**Pull request by MHBauer**
- refactor to make it easier to split the api in the future

I found a currently existing function that makes it much easier than I expected to make this change. There are other branches in my fork with similar work in different ways.

The tests seem pretty comprehensive.

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by MHBauer** [comment]
grabbing @calavera @icecrime  @duglin  because I forgot.

**Comment by LK4D4** [comment]
@MHBauer Seems like now gofmt is angry.

**Comment by MHBauer** [comment]
misconfigured editor. my bad. both should be fixed now.

**Comment by duglin** [comment]
LGTM
I don't think the janky failures are related, but I've been out of the loop for a few days, so I'll let someone else confirm and merge.

**Pull request merged**
