### PR TITLE
Vendoring boltb/bolt v1.2.0

### PR DESCRIPTION
**Pull request by aboch**
This may help on the CI issue tracked by  #21453

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by icecrime** [comment]
Thanks! A few questions:

- Should we take this for 1.11?
- How confident are we that it will improve the situation? Are there any risks associated with it?

**Comment by aboch** [comment]
The original issue was consistently seen on the sync in the open file path. That sync has been removed and the only one left is in the commit path. In 15 CI run I have run with the v1.2.0 changes, slowness is sporadically seen, but never to 15 secs level. In fact none of the CI has failed because of the sync slowness. From what I understand, there should not be risks with the update. I have not encountered issues during the CI runs and my local testing.

**Comment by tonistiigi** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
