### PR TITLE
Update Networking changelog for 1.11

### PR DESCRIPTION
**Pull request by sanimej**
Signed-off-by: Santhosh Manohar santhosh@docker.com

### CODE REVIEW

**Comment by tiborvass** [comment]
@sanimej can you please reference the vendoring PRs that fixed each of those issues? It's fine to reference multiple times the same pr.

**Comment by thaJeztah** [comment]
@sanimej can you add links to the PR(s), to be consistent?

**Comment by thaJeztah** [comment]
Oh, sorry for the double post - GitHub didn't show tibors comment

**Comment by sanimej** [comment]
@tiborvass I didn't include the PR because it will be repetitive. If its ok I will update it. thanks.

**Comment by tiborvass** [comment]
@sanimej it is okay.

**Comment by sanimej** [comment]
@tiborvass @thaJeztah Updated with the PR references.

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
