### PR TITLE
Remove hard coded 'docker' string from package

### LINKED ISSUE #19546: "docker" string appeared when I use mflag package.
```
fmt.Fprintf(fs.Out(), "docker: %s.\n", str)
```
-- [mflag/flag.go](https://github.com/docker/docker/blob/757d686700b02fa79f7c59edee656b7c35f956f3/pkg/mflag/flag.go#L1166)

I am using the [mflag](https://github.com/docker/docker/tree/master/pkg/mflag) package in my personal project. It's pretty nice, but when I make an argument error, "docker" string will comes out because it is hard coded. Do you have a plan to change this?

Thanks.

### PR DESCRIPTION
**Pull request by WeiZhang555**
Closes #19546

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐨

**Comment by runcom** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
