### PR TITLE
Promote volume drivers from experimental to master.

### PR DESCRIPTION
**Pull request by calavera**
Remove volume stubs and use the experimental path as the only path.

Part of #14214.

/cc @cpuguy83, @icecrime

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM pending janky.

**Comment by calavera** [comment]
@cpuguy83 I think we can do it after. It will be easier for everyone if we land this first, so we don't have to think about experimental/non-experimental.

**Comment by icecrime** [comment]
Two questions:
- I'm assuming we chose not to make #14242 a prerequisite, but are we still considering it for the near future?
- Why are we mentioned passing the container ID down to the plugin? I don't see what additional use it would make of it as long as we guarantee a unique (user-provided) name for the volume.

**Comment by calavera** [comment]
> I'm assuming we chose not to make #14242 a prerequisite, but are we still considering it for the near future?

@icecrime at the end, moving this out of experimental is a pre-requisite of #14242. Otherwise @cpuguy83 needs to put the api/cli in experimental and then move them out.

> Why are we mentioned passing the container ID down to the plugin? I don't see what additional use it would make of it as long as we guarantee a unique (user-provided) name for the volume.

It's a different topic, we've talked about sending some extra information to the plugins, like the container id. I don't think it's related to this PR.

**Comment by icecrime** [comment]
Sounds good, thanks.

**Comment by icecrime** [comment]
Code LGTM.

Ping @lukemarsden FYI. 
Spoiler alert: we're gonna need to promote the docs too.

**Comment by calavera** [comment]
> Spoiler alert: we're gonna need to promote the docs too.

moving the docs too.

**Comment by calavera** [comment]
ouch, I might wait to move the docs until #1395 is merged, which should happen soon-ish.

**Comment by calavera** [comment]
@thaJeztah I moved the volume and plugin documents from experimental to docs in this PR. Let me know what you think.

**Comment by icecrime** [comment]
One issue with docs here is that I believe they aren't linked to anywhere? (cc @moxiegirl)

**Comment by calavera** [comment]
yeah, I'm wondering if we should have a `Extend docker` section:

image

**Comment by thaJeztah** [comment]
@calavera IIUC, only the *volume* plugins will be promoted from experimental, but the network plugins still are (experimental)? In that case, shouldn't the docs in the experimental directory stay intact for the network plugins?


And, yes, we need to find a good location inside the navigation :-)

**Comment by thaJeztah** [comment]
I personally like "extend docker" as a title

**Comment by calavera** [comment]
@thaJeztah the networking docs are still in the experimental folder.

**Comment by thaJeztah** [comment]
@calavera yes, but the `plugins.md` file contained the description for both the network and volume plugins, not sure if that's still needed in the "experimental" directory?

**Comment by calavera** [comment]
@thaJeztah not anymore. I changed the plugins document to reflect what we have that's not experimental.

**Comment by moxiegirl** [comment]
@calavera Since `Extend Docker` seems like a good title to me too. The position is important --- I think it should come after **Manage Image Repositories** at the very least. Since it contains API information it really belongs under **Command and API References**  --- WDYT?

**Comment by calavera** [comment]
sounds great, I'll make the change.

**Comment by calavera** [comment]
I moved the docs to `docs/plugins` and they should show up under the `Extend Docker` menu when docker/docs-base#114 is merged.

**Comment by moxiegirl** [comment]
um. don't kill me but I renamed plugins to extend to fit the menu.  After all, plugin isn't the only way a product could be extended.

**Comment by moxiegirl** [comment]
image

**Comment by SvenDowideit** [comment]
I'm pretty much LGTM on the docs, and while I'd love to have ID and userid passed to the plugin, I can do quite a bit without :)

**Comment by calavera** [comment]
@moxiegirl I've applied your patch and moved the docs to `extend`, thank you!
@SvenDowideit I'm confident we can iterate on that in future releases.

**Comment by moxiegirl** [comment]
Thanks @calavera LGTM

**Comment by thaJeztah** [comment]
docs LGTM, thanks @calavera

Just to confirm; @cpuguy83 your LGTM is for design *and* code review?

if it is: press da button!

**Comment by lukemarsden** [comment]
@icecrime thanks for the heads up!

I have tested flocker and the flocker docker plugin with docker master from today (4ed3e3a5b26a365e9b270011b0ba2b772fb98ab9) and, after changing the plugins path, it appears to be working in basic manual testing.

Thanks!

**Pull request merged**
