### PR TITLE
1.13.1 rc2 cherrypicks 2

### PR DESCRIPTION
**Pull request by vieux**
Update systemd drop-in link #30603
Revendor Microsoft/go-winio v0.3.8 #30614
plugin: use pkg/errors in more places #30615 
Add bash completion for `docker checkpoint` #30444
install dirmngr if needed #30616

### CODE REVIEW

**Comment by LK4D4** [comment]
Looks like windows failed. Not sure if flaky or what. ping @jhowardmsft

**Comment by vieux** [comment]
ping @LK4D4 @tiborvass

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Pull request merged**
