### PR TITLE
Ensure that the node status is no longer pending when checking lock/unlock.

### PR DESCRIPTION
**Pull request by cyli**
This is an addendum to https://github.com/docker/docker/pull/28997.  cc @aaronlehmann

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Earlier I suggested doing this, but now I'm not sure.

Won't `Restart` block until the node leaves the pending state, unless something is really wrong and the node doesn't come up by the deadline?

ping @tonistiigi

**Comment by cyli** [comment]
@aaronlehmann I'm not sure if something went very wrong, but I saw a test run where it ended up in pending state.  Looking at the logs, it seems like it couldn't connect to the other 2 nodes immediately (I see some health check failure errors), and it took it about 50 seconds to acknowledge a leader - it looks like the query to the `/info` endpoint happened before that happened?  Not sure I'm interpreting this right:

https://gist.github.com/cyli/9bc0ced5fc582b47d80a787441a2c106

**Comment by tonistiigi** [comment]
@aaronlehmann Yes, restart waits for 20 seconds for the node to become active. In https://gist.github.com/cyli/9bc0ced5fc582b47d80a787441a2c106#file-docker-log-L826 it shows that it didn't finish in time for that. I'm not sure if it not finishing in time shows a bug or wrong timeouts. Previously we have discussed about these timeouts being in swarmkit side where it could make a more precise decision to give up or wait more if the election has not finished.

**Comment by aaronlehmann** [comment]
@cyli: Do you have the Git revision corresponding to that log? The problem is supposed to be fixed by https://github.com/docker/swarmkit/pull/1779, which was vendored on master yesterday.

**Comment by cyli** [comment]
@aaronlehmann https://github.com/cyli/docker/commit/083511414d339d6621ea7ef2d1422f62919b4c5d - I basically copied and pasted swarmkit master with some log stuff into the docker repo, since I was actually trying to reproduce a different error (in the gist I stripped out my debugging messages, since they didn't seem relevant).

https://github.com/cyli/docker/commit/083511414d339d6621ea7ef2d1422f62919b4c5d#diff-5bdd3b513fc40e864b6b1974f1e8328c seems to have your changes from https://github.com/docker/swarmkit/pull/1779.

**Comment by cyli** [comment]
Should https://github.com/docker/swarmkit/pull/1797 supersede this PR?  This would make it less likely the tests would fail, but perhaps we want the tests to be flakey if leader election takes too long?

**Comment by aaronlehmann** [comment]
👍, I think there is an SwarmKit bug delaying convergence that hopefully docker/swarmkit#1797 will fix. I agree it's better to address the root cause than change the tests to tolerate the issue.

**Pull request closed without merging**
