### PR TITLE
disable-ipv4 support

### PR DESCRIPTION
**Pull request by daaku**
This is an initial rev and needs some cleanup, but wanted to get some feedback early.

We want to run in an ipv6 only environment, and want to entirely disable ipv4.

### CODE REVIEW

**Comment by jfrazelle** [comment]
don't we need to add iptables6 implementations for this?

**Comment by MalteJ** [comment]
What are we using iptables for? I just remember ICC and NAT. Is there something else? Host port mapping?

I'd like to realize a "disable-ipv4 support" via `docker -d --ipv4=false --ipv6=true`. This way it would be consistent with the IPv6 approach.

**Comment by jfrazelle** [comment]
ooo i like that ux @MalteJ

**Comment by icecrime** [comment]
Agree with @MalteJ: @daaku would you mind updating your contribution to follow the proposed UX? Thanks!

**Comment by icecrime** [comment]
Ping @daaku!

**Comment by daaku** [comment]
Sorry, I'll come back to this later.

**Pull request closed without merging**
