### PR TITLE
Remove drone.

### PR DESCRIPTION
**Pull request by jessfraz**
We have janky now and it is amazing

### CODE REVIEW

**Comment by thaJeztah** [comment]
Funny to read "waiting to hear about ... " from Jenkins for this PR. My guess is, he will agree :D

**Comment by crosbymichael** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by crosbymichael** [comment]
just work jenkins, just work!!!!!

**Comment by jfrazelle** [comment]
it passed it passed

**Comment by tianon** [comment]
LGTM

**Pull request merged**
