### PR TITLE
note regarding explicit non-support of systemd below v7 of RHEL & CentOS

### PR DESCRIPTION
**Pull request by mikebrow**
User complaint that it is not possible to use systemd on RHEL/CentOS prior to RHEL7/CentOS7.  User asks for instructions or an explicit declaration that it won't work so as to save others time in trying to make it work.

Adding a note in the systemd portion of the installation documentation for these now unsupported repos to caution users from trying to use systemd in said unsupported repos.

Signed-off-by: Mike Brown brownwm@us.ibm.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @mikebrow, I'm not sure though if we still need to include this, given that, with Docker 1.8, Docker dropped support for RHEL/CentOS 6.x

ping @moxiegirl wdyt?

**Comment by SvenDowideit** [comment]
we really should consider ramping up the use of https://forums.docker.com for information about things like Centos 6 etc.

i do think that giving some pointers as to why we're not supporting older releases like this is useful, as it gives people that like to tinker a heads up.

**Comment by moxiegirl** [comment]
@thaJeztah I agree with you that having the note there is confusing if we don't support versions that lack `systemd` --- why mention this if you don't support that version of the OS.

@mikebrow @SvenDowideit are acknowledging a fact, people don't do what we say all the time. They tinker.  Maybe what we need is a page devoted to folks that like to tinker.   *Running Docker in an unsupported operating system"  On that page we could put key tips like the one @mikebrow  is providing and also links to articles and blogs that are particularly helpful.

WDYT folks?

**Comment by thaJeztah** [comment]
Yes, I think that makes sense; we could also link to that page if the https://get.docker.com install script fails to detect the operating system / distribution.

**Comment by mikebrow** [comment]
Ok so maybe we have at least two issues to think about... 1) using down level versions of docker that do support down level versions of centos/rhel where we need this warning to not use systemd.  and 2) links on the platform install pages to a new page to discuss known issues with unsupported platforms.. 

Minor note:  Finding the link to docker archives for the prior releases to find out how to install prior releases is not obvious.  Maybe a paragraph on the install page for each platform that says something about these instructions are for the current 1.8 release See Docker Archives.. for prior releases?

**Comment by moxiegirl** [comment]
@mikebrow Since we are public, we rely on the issues in the repo for "known issues" rather than maintaining a list. Doing that has the added benefit of allowing users to follow issues they care about.
Similarly, old releases https://github.com/docker/docker/releases are also here. So, we really need information on how to use those two areas.

Maybe a single page with this:

```
# Manage your Docker Engine software

yada, yada

## Reporting issues or tracking known issues

yada, yada

## Finding older releases

yada, yada

## Going unsupported

yada, yada
```

We can link to this from each installation page.  WDYT?

**Comment by mikebrow** [comment]
a) Note for the #13297 issue:  should we change the Docker Use page: https://docs.docker.com/misc/   "Develop, Ship and Run Any Application, Anywhere" to :"Develop, Ship and Run Any Application, on Any Supported Platform" ?

b1) #manage is a large topic already covered by other sections... I think that would get confusing as you'd be covering more details in summary that are already covered well elsewhere.  I like it the way it is now with the install instructions just covering a very basic getting started by running hello-world thing. Then they move to the using / managing sections of the docs.  Maybe just add a next steps section on the install page?
b2) ## going unsupported on particular platforms is a topic that would probably go well with the https://docs.docker.com/installation/binaries/ page.
b3) ## finding older releases... I was thinking you need a paragraph at the top of the install pages that says these instructions install the latest version of the docker engine on version # of ___. to see information about prior releases go ___.
b4) ## Reporting issues or tracking known issues... that's a tough topic as you already have lots of links to that stuff.. not to mention github.  I think the user that opened the issue just wanted to make sure no one was surprised again.  Thus if we just be more explicit about what release of each platform is supported vs. saying everywhere... we should be able to avoid the issue of surprise.

**Comment by moxiegirl** [comment]
@mikebrow a) That is a marketing slogan so we can't do that.

b1) I'm not a fan of manage in the title.  Sounds like you are suggesting expanding the `installation/index.md` page.  I'd go for that.
b2) Good point and taken.
b3) `installation/index.md` page?  I'd go for that.
b4) OK.  

Thanks for such a thoughtful approach and patience with discussion. Do you want to tackle this on this PR? Or would you like us to close, carry, and ping you for review?

**Comment by mikebrow** [comment]
@moxiegirl Thanks for the discussion on irc.  Per our discussion I'll add some additional content to expand on installation/index.md.  

Cheers...

**Pull request closed without merging**
