### PR TITLE
Fix flaky TestEventsContainerFilterBeforeCreate

### LINKED ISSUE #20529: Flaky test: TestEventsContainerFilterBeforeCreate
From #20526 https://jenkins.dockerproject.org/job/Docker-PRs-experimental/15218/console

```
01:40:53 ----------------------------------------------------------------------
01:40:53 FAIL: docker_cli_events_unix_test.go:125: DockerSuite.TestEventsContainerFilterBeforeCreate
01:40:53 
01:40:53 docker_cli_events_unix_test.go:152:
01:40:53     c.Assert(out, checker.Contains, cID, check.Commentf("Missing event of container (foo)"))
01:40:53 ... obtained string = "" +
01:40:53 ...     "2016-02-20T01:40:29.587977244Z container create a9af1eda63b3b20240c46ccb4760454189f0c9e53b8e797209b42fd4580da20d (image=busybox, name=foo)\n" +
01:40:53 ...     "2016-02-20T01:40:29.633116042Z container start a9af1eda63b3b20240c46ccb4760454189f0c9e53b8e797209b42fd4580da20d (image=busybox, name=foo)\n" +
01:40:53 ...     "2016-02-20T01:40:29.926971940Z container kill a9af1eda63b3b20240c46ccb4760454189f0c9e53b8e797209b42fd4580da20d (image=busybox, name=foo)\n" +
01:40:53 ...     "2016-02-20T01:40:29.954202675Z container die a9af1eda63b3b20240c46ccb4760454189f0c9e53b8e797209b42fd4580da20d (image=busybox, name=foo)\n" +
01:40:53 ...     "2016-02-20T01:40:30.064539462Z container destroy a9af1eda63b3b20240c46ccb4760454189f0c9e53b8e797209b42fd4580da20d (image=busybox, name=foo)\n"
01:40:53 ... substring string = "af77ab8d69cd5267b64aac268c332c50c6bb0ef30ba3602410384e237379685f"
01:40:53 ... Missing event of container (foo)
01:40:53 
01:40:55 
01:40:55 ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes #20529

Most recently failed in https://jenkins.dockerproject.org/job/Docker%20Master/label=fedora%20&&%20devicemapper/6601/console . From the logs the failure is because of a random slow container startup. Test expects the container to be started in 2 seconds. This changes the test to repeatedly try for 15 sec with 500ms intervals. It also makes the test 5x faster for the common case.

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
The old test was using `waitRun` which has a 5s timeout and 2s to wait for whatever between call to events and run.

**Comment by cpuguy83** [comment]
It might be helpful to use the `eventObserver`

**Comment by tonistiigi** [comment]
> The old test was using waitRun which has a 5s timeout and 2s to wait for whatever between call to events and run.

Not enough https://gist.github.com/tonistiigi/4aedb9078540308edb21c0c3eab5ea61#file-docker-log-L23-L40

**Comment by tonistiigi** [comment]
@cpuguy83 If I understand correctly then `eventObserver` swallows errors on `eventObserver.Match` and retries the request on `CheckEventError` what makes it not ideal for this because this test is for specifically testing the stream that was started before the container.

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
