### PR TITLE
Remove case sensitive duplicate dir in vendor

### PR DESCRIPTION
**Pull request by tonistiigi**
After #19902 we vendor both `src/github.com/Microsoft` and `src/github.com/microsoft`. That means bad stuff starts to happen if git checkout is made on filesystems that don't support it. Files end up in same directory and imports will fail.

@jhowardmsft

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
wow nice

**Pull request merged**
