### PR TITLE
Add command "docker volume rename"  to rename a volume

### PR DESCRIPTION
**Pull request by haoshuwei**
I' working to add a client command which is "docker volume rename" to rename a volume.
details:
# volume rename

```
Usage: docker volume rename [OPTIONS] OLD_NAME NEW_NAME

Rename a volume
  --help=false    Print usage
```

The `docker rename` command allows the container to be renamed to a different name.

```
  --help=false    Print usage
```

The `docker volume rename` command allows the volume to be renamed to a different name.

So far, i have completed dev code part to use this command "docker volume rename OLD_NAME NEW_NAME".At later,i will update  test code part.

### CODE REVIEW

**Comment by duglin** [comment]
Please squash your commits.
Overall, I agree with this added feature.

**Comment by cpuguy83** [comment]
I like the idea, but this can be super dangerous.
Even `docker rename` which is modifying only locally controlled state has tons of issues, and is constantly a problem when adding/changing other functionality.

With `docker volume rename` we are modifying state that we don't own, which is very likely being used on multiple hosts which makes it more tricky.

As it is, this is already broken even for a single host because it's not modifying any of the containers which are referencing the volume name.

**Comment by cpuguy83** [comment]
Given that, NOTLGTM

**Comment by duglin** [comment]
@cpuguy83 do volumes have IDs and names or just names?  When I do inspect I only see a name.  It would be nice if internally all of the linking/processing was based on static IDs and then the name is just an alias which could be changed (and referenced by the user).

**Comment by haoshuwei** [comment]
@cpuguy83 the command "docker volume rename " only modify a volume's name when it's not in used,or it will give err "volume is in use"

**Comment by duglin** [comment]
just noticed that the name (not an ID) appears under `/var/lib/docker/volumes`. If IDs were used there too then we'd be in a lot better shape when (if?) we ever get to a multi-tenant environment.

**Comment by haoshuwei** [comment]
@duglin  as i know,volumes only have names without IDs,this may be different from container's rename operation.

**Comment by cpuguy83** [comment]
@haoshuwei This still ends up being a problem for multi-host drivers.
I am not comfortable adding this functionality at the moment.

**Comment by haoshuwei** [comment]
Ok,i should commit a proposal first before i start to code.Anyway ,thanks a lot for all of your reviews.

**Comment by calavera** [comment]
I agree with @cpuguy83. This will only introduce unnecessary complexity and more issues than it solves. I don't think we should implement it in any form.

Thanks a lot for putting this together, but I think we should close it and not move it forward.

**Comment by crosbymichael** [comment]
with the end goal of cluster wide volumes we should probably wait on a rename for now and look into some of the issues with using just names and no ids instead of a model with ids and a name layer linking to them.

@haoshuwei thanks for the PR though!

**Pull request closed without merging**
