### PR TITLE
Limit conccurent container creates in TestEventsLimit to 8

### LINKED ISSUE #22601: Flaky test: TestEventsLimit failing on WindowsTP5
TestEventsLimit seen failing on this PR; https://github.com/docker/docker/pull/22588 (https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP5/1500/console)

```
2:52:07 ----------------------------------------------------------------------
12:52:07 FAIL: docker_cli_events_test.go:108: DockerSuite.TestEventsLimit
12:52:07 
12:52:07 docker_cli_events_test.go:129:
12:52:07     c.Assert(err, checker.IsNil, check.Commentf("%q failed with error", strings.Join(args, " ")))
12:52:07 ... value *errors.errorString = &errors.errorString{s:"exit status 127: D:\\CI\\CI-858ae79\\binary\\docker.exe: Error response from daemon: Container command 'C:/busybox/busybox.exe' not found or does not exist.\n"} ("exit status 127: D:\\CI\\CI-858ae79\\binary\\docker.exe: Error response from daemon: Container command 'C:/busybox/busybox.exe' not found or does not exist.\n")
12:52:07 ... "run --rm busybox true" failed with error
12:52:07 
```

### PR DESCRIPTION
**Pull request by darstahl**
fixes #22601 

This limits the number of concurrent runs in TestEventsLimit in order to prevent hitting a platform timeout on Windows. I am unable to repro this failure locally, so this needs a few windowsRS1 CI runs to confirm the fix, but I strongly suspect this will fix the issue.

Assuming the platform timeout is the issue, the other option is to limit concurrency in the daemon, which might be the more correct solution here, since this solution (not changing anything) would require clients to limit their concurrent calls to creating containers on Windows until the platform timeout is changed. We could also temporarily disable the test until a platform fix is available, since I wouldn't really consider this a Docker bug, nor a test bug.

/cc @jhowardmsft @jstarks @jterry75 FYI

### CODE REVIEW

**Comment by jhowardmsft** [comment]
I'm ok with this as an interim solution. Assuming it works :smile:  Can you add a comment for why. Obviously we still need to track down the bug in Windows for servicing independently. IOW LGTM if CI passes a few runs.

**Comment by darrenstahlmsft** [comment]
This has passed CI without TestEventsLimit failures 5 times. Comment is updated, and ready for review 👍

**Comment by vieux** [comment]
same as @jhowardmsft, "I'm ok with this as an interim solution" LGTM

**Review by vieux — APPROVED** [review]

**Comment by crosbymichael** [comment]
What was wrong with the waitgroup?

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
