### PR TITLE
Windows CI: Fixup docker_api_containers_test.go

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This enables a bunch more WIndows to Windows CI tests present in docker_api_containers_test.go. Where tests are problematic, or further work to continue porting the tests is needed, these have been annotated.

```
E:\go\src\github.com\docker\docker>runtest wl TestContainerApi
Running test TestContainerApi
DOCKER_TEST_HOST=tcp://127.0.0.1:2375
DOCKER_HOST=tcp://127.0.0.1:2375
=== RUN   Test
INFO: Testing against a local daemon
SKIP: docker_api_containers_test.go:574: DockerSuite.TestContainerApiBadPort (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1167: DockerSuite.TestContainerApiChunkedEncoding (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:515: DockerSuite.TestContainerApiCommit     16.727s
PASS: docker_api_containers_test.go:538: DockerSuite.TestContainerApiCommitWithLabelInConfig    18.794s
SKIP: docker_api_containers_test.go:1001: DockerSuite.TestContainerApiCopy (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:1064: DockerSuite.TestContainerApiCopyContainerNotFound     0.015s
SKIP: docker_api_containers_test.go:1032: DockerSuite.TestContainerApiCopyResourcePathEmpty (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1048: DockerSuite.TestContainerApiCopyResourcePathNotFound (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:599: DockerSuite.TestContainerApiCreate     5.504s
SKIP: docker_api_containers_test.go:680: DockerSuite.TestContainerApiCreateBridgeNetworkMode (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:619: DockerSuite.TestContainerApiCreateEmptyConfig  0.014s
SKIP: docker_api_containers_test.go:686: DockerSuite.TestContainerApiCreateOtherNetworkModes (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:715: DockerSuite.TestContainerApiCreateWithCpuSharesCpuset (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:655: DockerSuite.TestContainerApiCreateWithDomainName (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:630: DockerSuite.TestContainerApiCreateWithHostName (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:1074: DockerSuite.TestContainerApiDelete    5.684s
PASS: docker_api_containers_test.go:1131: DockerSuite.TestContainerApiDeleteConflict    5.259s
PASS: docker_api_containers_test.go:1094: DockerSuite.TestContainerApiDeleteForce       5.532s
PASS: docker_api_containers_test.go:1087: DockerSuite.TestContainerApiDeleteNotExist    0.011s
SKIP: docker_api_containers_test.go:1105: DockerSuite.TestContainerApiDeleteRemoveLinks (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:1142: DockerSuite.TestContainerApiDeleteRemoveVolume        5.814s
PASS: docker_api_containers_test.go:34: DockerSuite.TestContainerApiGetAll      5.730s
SKIP: docker_api_containers_test.go:152: DockerSuite.TestContainerApiGetChanges (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:128: DockerSuite.TestContainerApiGetExport (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:58: DockerSuite.TestContainerApiGetJSONNoFieldsOmitted      5.808s
PASS: docker_api_containers_test.go:779: DockerSuite.TestContainerApiInvalidPortSyntax  0.027s
PASS: docker_api_containers_test.go:908: DockerSuite.TestContainerApiKill       5.761s
SKIP: docker_api_containers_test.go:462: DockerSuite.TestContainerApiPause (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:1203: DockerSuite.TestContainerApiPostContainerStop 5.530s
SKIP: docker_api_containers_test.go:803: DockerSuite.TestContainerApiPostCreateNull (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:893: DockerSuite.TestContainerApiRename     4.561s
SKIP: docker_api_containers_test.go:921: DockerSuite.TestContainerApiRestart (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:933: DockerSuite.TestContainerApiRestartNotimeoutParam (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:947: DockerSuite.TestContainerApiStart      4.380s
SKIP: docker_api_containers_test.go:209: DockerSuite.TestContainerApiStartDupVolumeBinds (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:178: DockerSuite.TestContainerApiStartVolumeBinds (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:234: DockerSuite.TestContainerApiStartVolumesFrom (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:971: DockerSuite.TestContainerApiStop       5.688s
SKIP: docker_api_containers_test.go:489: DockerSuite.TestContainerApiTop (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:748: DockerSuite.TestContainerApiVerifyHeader       0.749s
PASS: docker_api_containers_test.go:986: DockerSuite.TestContainerApiWait       10.858s
OK: 20 passed, 21 skipped
--- PASS: Test (130.92s)
PASS
ok      _/E_/go/src/github.com/docker/docker/integration-cli    131.192s

E:\go\src\github.com\docker\docker>runtest wl TestPostContainer
Running test TestPostContainer
DOCKER_TEST_HOST=tcp://127.0.0.1:2375
DOCKER_HOST=tcp://127.0.0.1:2375
=== RUN   Test
INFO: Testing against a local daemon
PASS: docker_api_containers_test.go:1213: DockerSuite.TestPostContainerApiCreateWithStringOrSliceEntrypoint     11.358s
SKIP: docker_api_containers_test.go:442: DockerSuite.TestPostContainerBindNormalVolume (Test requires a Linux daemon)
SKIP: docker_api_attach_test.go:85: DockerSuite.TestPostContainersAttach (Test requires a Linux daemon)
PASS: docker_api_attach_test.go:69: DockerSuite.TestPostContainersAttachContainerNotFound       0.015s
SKIP: docker_api_containers_test.go:1543: DockerSuite.TestPostContainersCreateMemorySwappinessHostConfigOmitted (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1447: DockerSuite.TestPostContainersCreateShmSizeHostConfigOmitted (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1433: DockerSuite.TestPostContainersCreateShmSizeNegative (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1479: DockerSuite.TestPostContainersCreateShmSizeOmitted (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1568: DockerSuite.TestPostContainersCreateWithOomScoreAdjInvalidRange (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1511: DockerSuite.TestPostContainersCreateWithShmSize (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1258: DockerSuite.TestPostContainersCreateWithStringOrSliceCapAddDrop (Test requires a Linux daemon)
PASS: docker_api_containers_test.go:1236: DockerSuite.TestPostContainersCreateWithStringOrSliceCmd      11.758s
SKIP: docker_api_containers_test.go:1388: DockerSuite.TestPostContainersCreateWithWrongCpusetValues (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1299: DockerSuite.TestPostContainersStartWithLinksInHostConfig (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1318: DockerSuite.TestPostContainersStartWithLinksInHostConfigIdLinked (Test requires a Linux daemon)
SKIP: docker_api_containers_test.go:1281: DockerSuite.TestPostContainersStartWithoutLinksInHostConfig (Test requires a Linux daemon)
OK: 3 passed, 13 skipped
--- PASS: Test (28.97s)
PASS
ok      _/E_/go/src/github.com/docker/docker/integration-cli    29.145s

E:\go\src\github.com\docker\docker>

```

### CODE REVIEW

**Comment by thaJeztah** [comment]
Same question here w.r.t. sleep/top https://github.com/docker/docker/pull/19604#discussion_r50629385 (happy to change it, just making sure :heart:

**Comment by jhowardmsft** [comment]
Same answer :)

**Comment by icecrime** [comment]
I'll replace the `"sleep 60"` overall after we merge those. LGTM for the time being.

**Comment by thaJeztah** [comment]
alright, LGTM let's merge this

**Pull request merged**
