### PR TITLE
Add Trisquel 7 (Belenos) support to install.sh

### PR DESCRIPTION
**Pull request by boite**
Install as Ubuntu Trusty.

### CODE REVIEW

**Comment by jfrazelle** [comment]
we added the `check_forked` function for this, does it not work for your distro

**Comment by thaJeztah** [comment]
@boite could you help out and provide the information for your system (as described in https://github.com/docker/docker/pull/15001#issuecomment-125721830);

Run the following commands and post their respective outputs here:

```Bash
$ lsb_release -a
$ lsb_release -a -u
$ ls /etc/upstream-release/
$ cat /etc/upstream-release/*
```

/cc @fmoliveira

**Comment by fmoliveira** [comment]
I've created a VM with *Belenos Trisquel Sugar 7.0* and I've found out the `-u` option isn't supported by the `lsb_release` command.

Before we consider hard coding distro names, I've opened a [discussion/proposal here](https://github.com/docker/docker/issues/15765), please check that @boite @jfrazelle @thaJeztah .

**Comment by fmoliveira** [comment]
Or should we ask for Trisquel developers to add support for the `-u` option?

[Here's how](https://github.com/jolicloud/lsb/commit/fde07bfec0935784e5caa6cd6a2ff5f81c3d0ad4) JoliOS have done that, and according to [this topic](https://code.launchpad.net/~elementary-os/ubuntu/utopic/lsb/upstream-information/+merge/231704), it's exactly how elementary OS guys have done it too.

**Comment by boite** [comment]
I realise @fmoliveira has already determined that `lsb_release -u` isn't available on Trisquel, but here's the info requested from me anyway:-

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Trisquel
    Description:    Trisquel GNU/Linux 7.0, Belenos
    Release:        7.0
    Codename:       belenos

    $ lsb_release -a -u
    Usage: lsb_release [options]
    
    lsb_release: error: no such option: -u

    $ ls /etc/upstream-release/
    ls: cannot access /etc/upstream-release/: No such file or directory

**Comment by jfrazelle** [comment]
I am going to close this for the time being re the discussion going on in #15765, thanks!

**Pull request closed without merging**
