### PR TITLE
[Carry 18549] Lazy initialize Volume on container Mount object.

### PR DESCRIPTION
**Pull request by calavera**
Carry #18549.

/cc @ibuildthecloud, @cpuguy83

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by tiborvass** [comment]
@calavera some volume tests are failing

**Comment by calavera** [comment]
:goberserk:

**Comment by calavera** [comment]
@cpuguy83 I think at the end your PR was more correct. We should still try to mount the volumes when the daemon restart, to avoid issues with volume removal, but we should still double check that the volumes are okay before starting the container, like @ibuildthecloud suggested in his PR.

**Comment by cpuguy83** [comment]
` daemon/volumes_windows.go:21: undefined: m`

**Comment by calavera** [comment]
fixed, thanks!

**Comment by cpuguy83** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by calavera** [comment]
all :green_heart:

**Pull request merged**
