### PR TITLE
Fix unpause defer before deleteAllContainers

### PR DESCRIPTION
**Pull request by cpuguy83**
Signed-off-by: Brian Goff cpuguy83@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
Would you also mind making sure all pause tests have unpauseAllContainers I've been meaning too but haven't gotten around to it, and while you are here..... :D

**Comment by cpuguy83** [comment]
Updated, a few more where unapuse was being called after removeAllContainers.
Couldn't find anything missing unpause.

**Comment by duglin** [comment]
http://blog.golang.org/defer-panic-and-recover
>  Deferred function calls are executed in Last In First Out order after_the surrounding function returns.

So doesn't this mean that it needs to be:
```
defer deleteAllContainers()
defer unpauseAllContainers()
```
you have it swapped.

**Comment by cpuguy83** [comment]
Oh dang, I didn't even know... Closing.

**Pull request closed without merging**
