### PR TITLE
Fix curl progress flags

### PR DESCRIPTION
**Pull request by cristianrz**
**- What I did**

Fix wrong curl progress flags

**- How I did it**

Change `--progress` to `--progress-bar` on calls to `curl` and `fetch-blob` (which in turn calls `curl`)

**- How to verify it**

```
./contrib/download-frozen-image-v2.sh dummy ubuntu:latest
```

will run successfully

**- Description for the changelog**

Change `--progress` to `--progress-bar` on calls to `curl` and `fetch-blob` (which in turn calls `curl`)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Changes look good; 

Two minor nits;

- although it's recommended in various places, we try to keep `fixes XXX` comments out of our commit messages, because they generate a lot of noise on github if those commits get cherry-picked (or merged in forks). Instead, it's often better to just reference it in the PR description on GitHub, but not in the commit message itself
- could you amend your commit and change your DCO sign-off to use your real name (Cristian Ariza) instead of your github handle (`cristianrz`)? https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

You can use a force-push to update the PR; Something along these lines;

```
git commit --amend
# edit the commit message; remove the "fixes" line, and update the sign off line

git push -f origin
```

Let me know if you need a hand 👍

**Comment by cristianrz** [comment]
Fixed as requested, but now the checks say

> Commit sha: 7608e42, Author: cristianrz, Committer: cristianrz; Expected "cristianrz dev@cristianrz.com", but got "Cristian Ariza dev@cristianrz.com".

Is that okay?

**Comment by thaJeztah** [comment]
Ah, yes, looks like the DCO bot was updated recently to enforce the sign-off to match the "committer". I _think_ it should be possible to fix that if you `git config --global user.name "Cristian Ariza"`, and amend your commit again `git commit --amend --no-edit`)

Could you give that a try? Otherwise I can probably override the check to make it pass

**Comment by cristianrz** [comment]
Doing that does not really fix it, i.e. after doing the commit amend it still show the author being "cristianrz" but "Signed-off by: Cristian Ariza"

**Comment by thaJeztah** [comment]
Let me manually mark it as "passing"; thanks for trying!

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
@tianon PTAL

**Review by tianon — APPROVED** [review]
LGTM, thanks! :+1:

**Comment by rrebollo** [comment]
hit me today, regression???

**Comment by thaJeztah** [comment]
@rrebollo can you be more specific? The script still uses `--progress-bar`. Are you perhaps running on an old distro / curl version that doesn't support this option?

Also, if you suspect there's a bug, and have details / ways to reproduce please open a ticket instead of commenting on a 2 year old pull request 😅

**Pull request merged**
