### PR TITLE
Add Madhu Venugopal to maintainers

### PR DESCRIPTION
**Pull request by thaJeztah**
Adding @mavenugo to maintainers :tada:

ping @docker/core-engine-maintainers

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by coolljt0725** [comment]
LGTM :congratulations:

**Comment by jfrazelle** [comment]
LGTM

On Wednesday, April 20, 2016, Lei Jitang <notifications@github.com> wrote:

> LGTM [image: :congratulations:]
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/22187#issuecomment-212360921>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
:tada: 💃

**Pull request merged**
