### PR TITLE
Change all docker -d to docker daemon

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

/cc @tiborvass

**Comment by tiborvass** [comment]
LGTM

I guess I missed some, thanks @hqhq !

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
@calavera think this needs cherry-pick?

**Comment by calavera** [comment]
we're not cherry picking any code that's not critical in the release at this point, sorry :sweat_smile:

**Comment by thaJeztah** [comment]
@calavera yeah, not really *code* changes mainly comments. But fair :smile:

Thinking if there's a way to get just the docs-changes in...

**Pull request merged**
