### PR TITLE
do not trim one char from {{.Names}} each time it is used in --format

### LINKED ISSUE #21772: --format trims one char from {{.Names}} each time it is used
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Mon, 04 Apr 2016 16:27:28 +1200
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Mon, 04 Apr 2016 16:27:28 +1200
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 91
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 88
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-16-generic
Operating System: Ubuntu 16.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65 GiB
Name: plata
ID: OERF:H3PM:YRZA:W34S:LM4N:QN2S:AYF4:QYYG:DFZV:JPKW:WROU:6LBO
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine, but this issue has happened on several other machines I have tested on running on different OSes and different Docker versions.

**Steps to reproduce the issue:**
1.  Run this script:
```
docker ps --format="
1  Names:  {{.Names}}
2  Names:  {{.Names}}
3  Names:  {{.Names}}
4  Names:  {{.Names}}
5  Names:  {{.Names}}
6  Names:  {{.Names}}
7  Names:  {{.Names}}
8  Names:  {{.Names}}
"
```

**Describe the results you received:**
Output of the above script on a machine with one container:
```
1  Names:  bitlbee
2  Names:  itlbee
3  Names:  tlbee
4  Names:  lbee
5  Names:  bee
6  Names:  ee
7  Names:  e
8  Names:
```

This behavior does not occur with the other available format vars.

### PR DESCRIPTION
**Pull request by vieux**
fix #21772

ping @danielhoherd  @thaJeztah @calavera

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by duglin** [comment]
LGTM windows failures look unrelated

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Actually, the Windows failure is genuine;

```
17:23:22 ----------------------------------------------------------------------
17:23:22 FAIL: docker_cli_ps_test.go:659: DockerSuite.TestPsNamesMultipleTime
17:23:22 
17:23:22 docker_cli_ps_test.go:660:
17:23:22     dockerCmd(c, "run", "--name=test1", "-d", "busybox", "top")
17:23:22 github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:630:
17:23:22     ...open github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go: The system cannot find the path specified.
17:23:22 ... Error: Cannot use 'busybox top' in tests on Windows. Use runSleepingContainer()
17:23:22 
```

it should use `runSleepingContainer` to start the container

**Comment by vieux** [comment]
@thaJeztah I'll update asap

**Comment by vieux** [comment]
@thaJeztah updated

**Comment by thaJeztah** [comment]
thanks

**Comment by thaJeztah** [comment]
Al green! Merging :)

**Pull request merged**
