### PR TITLE
Remove some unused contrib items

### PR DESCRIPTION
**Pull request by cpuguy83**
- contrib/builder is not used and not tested, and only updated for go versions, see github.com/docker/docker-ce-packaging for actual maintained package builders
- custom selinux policies don't work at all due to changes to bsae policies and should not be used in any case as there are now packages providing the necessary types on various distros (see the `container-selinux`)
- `project-stats.sh` is very old using an old tool called "gordon" that doesn't even really work anymore and is unmaintained. 

Closes ##36118

### CODE REVIEW

**Comment by thaJeztah** [comment]
replaces https://github.com/moby/moby/pull/36118 ? 

Also could you check https://github.com/moby/moby/pull/36118#issuecomment-366269259 (https://github.com/thaJeztah/docker/commit/017bef15ca9515f0fb327edc1dcdbd4697bd8afa) if the Makefile needs to be cleaned up, and possibly some files in `hack/.rpm`, `hack/.deb` (reading from my phone, so perhaps that was done already)

**Comment by cpuguy83** [comment]
I forgot about that one... yeah.

**Comment by cpuguy83** [comment]
Cleaned up Makefile. Looks like rpm/deb stuff was already removed from hack.

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @tianon

**Review by tianon — APPROVED** [review]

**Pull request merged**
