### PR TITLE
Event tests need retry logic

### LINKED ISSUE #33285: DockerSwarmSuite.TestSwarmClusterEventsSecret is failing
Seen failing on  https://github.com/moby/moby/pull/33280 (https://jenkins.dockerproject.org/job/Docker-PRs/42925/console) and https://github.com/moby/moby/pull/33261 (https://jenkins.dockerproject.org/job/Docker-PRs-s390x/2994/console)

```
23:59:44 ----------------------------------------------------------------------
23:59:44 FAIL: docker_cli_swarm_test.go:2197: DockerSwarmSuite.TestSwarmClusterEventsSecret
23:59:44 
23:59:44 [d5ecaf060bb69] waiting for daemon to start
23:59:44 [d5ecaf060bb69] daemon started
23:59:44 
23:59:44 docker_cli_swarm_test.go:2219:
23:59:44     c.Assert(out, checker.Contains, "secret remove "+id)
23:59:44 ... obtained string = ""
23:59:44 ... substring string = "secret remove ofztf6uqeeepgtsnyntmz6ebt"
23:59:44 
23:59:44 [d5ecaf060bb69] exiting daemon
23:59:58 
23:59:58 ----------------------------------------------------------------------
```

ping @dongluochen

### PR DESCRIPTION
**Pull request by dongluochen**
Fixes #33285. 

Swarm events are generated by processing raft store changes thru Watch API. The might be delay when the event processing goroutine is running slow. The tests should have retry logic to deal with random delay. 

cc @aaronlehmann @thaJeztah. 

Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
I suspect 600 ms may not always be enough on platforms like ARM. Can we increase the retry count to be sure?

**Comment by dongluochen** [comment]
Add a default retry count of 10. It'd wait for 1.8 seconds.

**Comment by aaronlehmann** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
All green

**Comment by aaronlehmann** [comment]
We will want to cherry-pick this one.

**Pull request merged**
