### PR TITLE
Fix race condition on daemon shutdown (#20543)

### LINKED ISSUE #20543: Terminated/Killed integration-cli tests
On latest master code, as already outlined here https://github.com/docker/docker/pull/20509#issuecomment-186560841, integration-cli tests are Killed/Terminated. I cannot see anything weird in test.log nor any other log files. I'm experiencing this on my own laptop but PRs are also affected (see linked PR before). The tests usually fails at `TestDaemonLoggingDriverNone` but sometimes also on `Volumes*` tests.

```
PASS: docker_cli_daemon_test.go:575: DockerDaemonSuite.TestDaemonKeyGeneration	0.528s
PASS: docker_cli_daemon_test.go:594: DockerDaemonSuite.TestDaemonKeyMigration	0.524s
PASS: docker_cli_daemon_test.go:1045: DockerDaemonSuite.TestDaemonLinksIpTablesRulesWhenLinkAndUnlink	2.156s
PASS: docker_cli_daemon_test.go:498: DockerDaemonSuite.TestDaemonLogLevelDebug	0.518s
PASS: docker_cli_daemon_test.go:508: DockerDaemonSuite.TestDaemonLogLevelFatal	0.516s
PASS: docker_cli_daemon_test.go:431: DockerDaemonSuite.TestDaemonLogLevelWrong	5.501s
PASS: docker_cli_daemon_test.go:1154: DockerDaemonSuite.TestDaemonLoggingDriverDefault	1.066s
PASS: docker_cli_daemon_test.go:1196: DockerDaemonSuite.TestDaemonLoggingDriverDefaultOverride	1.063s
PASS: docker_cli_daemon_test.go:1217: DockerDaemonSuite.TestDaemonLoggingDriverNone	1.042s
/go/src/github.com/docker/docker/hack/make/test-integration-cli: line 18:  2829 Terminated              ( bundle .integration-daemon-start; bundle .integration-daemon-setup; bundle_test_integration_cli; bundle .integration-daemon-stop ) 2>&1
      2830                       | tee -a "$DEST/test.log"
```

### PR DESCRIPTION
**Pull request by icecrime**
Last investigations on #20543 show that the integration-test daemon receives a SIGTERM which was apparently sent to all running processes.

Suspicious lines:
- [opencontainers/runc/libcontainer/container_linux.go:1038](https://github.com/docker/docker/blob/ea5acb08fa429b1d1833aa855793e8cbfabe25d8/vendor/src/github.com/opencontainers/runc/libcontainer/container_linux.go#L1038): pid initialized to `-1`
- [opencontainers/runc/libcontainer/container_linux.go:177-200](https://github.com/docker/docker/blob/ea5acb08fa429b1d1833aa855793e8cbfabe25d8/vendor/src/github.com/opencontainers/runc/libcontainer/container_linux.go#L177-L200): there is a delay during which `initProcess` is not set in the `linuxContainer` (done by [`linuxContainer.updateState`](opencontainers/runc/libcontainer/container_linux.go#L959))
- [native/driver.go:305](https://github.com/docker/docker/blob/master/daemon/execdriver/native/driver.go#L305): send a signal to `state.InitProcessId` (which is `-1` during a time window described above)

Sequence is the following:
- `daemon/execdriver/native/driver.go` calls `d.factory.Create()`: the resullt is a `linuxContainer` where `initProcess` is `nil`
- `daemon/execdriver/native/driver.go` calls `cont.Start()`
- `libcontainer/container_linux.go` only sets the `initProcess` when it reaches `c.UpdateState`
- until it reaches that point of the code, the container is already registered in `activeContainers` so if we attempt to kill, we signal `-1`

Hopefully fixes #20543.

### CODE REVIEW

**Comment by icecrime** [comment]
If the theory is right, [this code](https://github.com/docker/docker/blob/master/daemon/kill.go#L59-L61) should have protected us, so I may be missing something here.

**Comment by icecrime** [comment]
Also: ping @runcom @crosbymichael @tonistiigi.

**Comment by icecrime** [comment]
Credits go to @mlaventure for doing the hard work on figuring out that -1 was signaled ;-)

**Comment by thaJeztah** [comment]
WindowsTP4 is https://github.com/docker/docker/issues/20942

**Comment by thaJeztah** [comment]
Arm having connection issues;

```
04:31:17  > git -c core.askpass=true fetch --tags --progress https://github.com/docker/docker.git +refs/heads/*:refs/remotes/origin/*
04:35:41 ERROR: Error cloning remote repo 'origin'
04:35:41 hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/docker/docker.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
04:35:41 stdout: 
04:35:41 stderr: fatal: unable to access 'https://github.com/docker/docker.git/': GnuTLS recv error (-54): Error in the pull function.
04:35:41 
```

**Comment by icecrime** [comment]
CI is green, but let's try an ARM rebuild as it often fails.

**Comment by mlaventure** [comment]
I was afraid we would be depending on `d.activeContainers` if `cont.Start(p)` was to fail, but that doesn't seem to be the case :).

:+1:

**Comment by tophj-ibm** [comment]
It's looking green so far on power as well. Nice job @mlaventure this has been a tricky one! :tada:

**Comment by runcom** [comment]
my host seems not to suffer tests termination anymore, thanks @mlaventure !

LGTM after arm builds successfully (cause it will right?)

**Comment by calavera** [comment]
LGTM. Go ARM go!

**Comment by calavera** [comment]
:green_heart:

**Comment by icecrime** [comment]
:tada:

**Pull request merged**
