### PR TITLE
Bump v1.6.1

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @crosbymichael @LK4D4 @tiborvass @docker/security-team

**Comment by diogomonica** [comment]
LGTM

**Comment by NathanMcCauley** [comment]
LGTM

**Comment by ewindisch** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by crosbymichael** [comment]
janky!!! quit taking your time

**Comment by calavera** [comment]
LGTM :tada:

**Pull request merged**
