### PR TITLE
added contrib/Dokerfile.armv7 to build docker on ARMv7 with the original...

### PR DESCRIPTION
**Pull request by umiddelb**
.../unpatched sources

Hi,

I've modified the existing Dockerfile in order to build docker successfully for ARMv7 on ARMv7 (since this [commit](https://github.com/docker/docker/commit/7d7a002e51a1a1172f09741896f0a6c001438a49) with the original sources :). If you find it useful you may add this to the contrib directory (other docker users would appreciate this [as well](https://github.com/docker/docker/issues/4556#issuecomment-72374663). I'll try to keep at least the release versions in sync.   

Regards
Uli Middelberg uli@middelberg.de

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by tiborvass** [comment]
@umiddelb Thanks very much for your contribution, however we wouldn't like to duplicate Dockerfiles just to add a few arch specific variations.

I believe @duglin has some ideas on how to parameterize Dockerfiles in a way that could be used for having docker build on ARMv7.

I'm gonna close this PR for now, if anyone finds a better way please comment below and we could reopen it. Again, we DO WANT this!

**Comment by umiddelb** [comment]
@duglin
Fine, let's discuss. I see tree different kinds of changes:
- Changes related to the ARMv7 platform, e.g. `FROM ...`
- Changes related to vanilla ubuntu_core taken as baseimage, e.g. `RUN apt-get update ...`
- Changes making the build process run in a smarter way, e.g. `RUN dpkg-divert --local --rename ...`

**Comment by duglin** [comment]
ping @brahmaroutu

**Comment by duglin** [comment]
@umiddelb as mentioned, there is work going on to add more flexibility to Dockerfile processing. @brahmaroutu is working on adding if-statement support - a first pass can be seen here: https://github.com/brahmaroutu/docker/tree/ifdef_commands   hopefully a PR will be created for soon, but some other pieces of work need to come first - like: https://github.com/docker/docker/pull/9176 .

**Comment by umiddelb** [comment]
@brahmaroutu
Do you have written down your ideas in a 'design document' explaining how the if-statement support will look like?
Will you equip the docker binary with some predefined primitives?
How can I interact inside the Dockerfile with the operation system and the environment variables?

**Comment by brahmaroutu** [comment]
@umiddelb As pointed out by @duglin once the build supports environment variables and the ifdef capability in the docker file we can pretty much have good control on Dockerfile. Please checkout also 
https://github.com/brahmaroutu/docker/compare/gccgo_x86 where the Dockerfile and the Makefile would demo how we have gc or gccgo builds. We can invoke the build using a command like "make binary gccgo=true" for example. Please review and let me know. Also please follow #9207

**Pull request closed without merging**
