### PR TITLE
 Shell scripts: remove bashisms and fix bare variables

### PR DESCRIPTION
**Pull request by thaJeztah**
Reverts https://github.com/moby/moby/pull/38424, and re-applies the non-double-bracket-changes-etcetera

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon 👍 ❤️

**Review by tianon — APPROVED** [review]
:heart_eyes: thank you!

**Review by tao12345666333 — APPROVED** [review]

**Comment by olljanat** [comment]
Derek add label: rebuild/janky

**Review by vdemeester — APPROVED** [review]
LGTM :dancer: 
@tianon :hugs:

**Comment by thaJeztah** [comment]
💚

**Pull request merged**
