### PR TITLE
Don't pass check.C to dockerCmdWithError

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by LK4D4** [comment]
@cpuguy83 Compile error

**Comment by cpuguy83** [comment]
Fixed, it's building fine now.
Did a rebase right before push and 2 more slipped in there.

**Comment by runcom** [comment]
LGTM if janky's happy!

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
I think the windows failures are unrelated.

**Pull request merged**
