### PR TITLE
add configs tag in swagger.yml

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: Allen Sun <allensun.shl@alibaba-inc.com>

**- What I did**
1. add configs tag in swagger.yml

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
thanks! LGTM

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by thaJeztah** [comment]
failures are not related. merging

**Pull request merged**
