### PR TITLE
Fix a typo: change "such Bash" to "such as Bash" in dockerfile_best-practices.md

### PR DESCRIPTION
**Pull request by anatolyborodin**

### CODE REVIEW

**Comment by anatolyborodin** [comment]
PS There is "BASH" in docs/project/set-up-dev-env.md, there are also "Bash" and "bash" in other doc files. Which should be the consistent way?

**Comment by albers** [comment]
According to [Bash Reference Manual](http://www.gnu.org/software/bash/manual/bashref.html), and [Wikipedia](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) the name is _Bash_.
when referred to as a command, it is _bash_.

**Comment by cpuguy83** [comment]
LGTM

**Comment by anatolyborodin** [comment]
Thanks, that was really fast!

One more question: when should be documentation fixes like this one be based on origin/master, and when on origin/docs? I've tried to find it in the docs, and I thought origin/docs is being merged to origin/master from time to time, but `git log origin/master..origin/docs` says there are unmerged commits 6 months old.

**Pull request merged**
