### PR TITLE
backport 17.03.1 CHANGELOG

### PR DESCRIPTION
**Pull request by vieux**

### CODE REVIEW

**Comment by tiborvass** [comment]
To compare: https://github.com/docker/docker/blob/v17.03.1-ce/CHANGELOG.md

**Comment by tiborvass** [comment]
LGTM

**Review by tiborvass — APPROVED** [review]

**Comment by aaronlehmann** [comment]
pedantry: It's not really a backport if the changes are being brought to master.

**Comment by tiborvass** [comment]
@aaronlehmann fair point. Is it a foreport? frontport? According to http://softwareengineering.stackexchange.com/questions/170393/is-there-an-opposite-for-the-term-backporting it's just `port`. So `Port 17.03.1 Changelog to master` ?

**Comment by aaronlehmann** [comment]
I've heard the term "forward-port" before.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
I usually just say "cherry-pick to master" :smile:

**Pull request merged**
