### PR TITLE
[Carry #11827] Add a new event for process exiting

### PR DESCRIPTION
**Pull request by calavera**
Carry #11827.

I've swapped the `exit` and `die` events. I cannot find any documentation about events, do we have any?

/cc @mgood, @jfrazelle, @duglin

### CODE REVIEW

**Comment by cpuguy83** [comment]
A little trouble understanding the progression of `exit->die` and `die->exit` (from the context in the previous PR), and the code seems to be inconsistent with one way or the other as well:

- In container.go#269 it is die->exit
- In monitor.go#166 it is die->exit
- Inmonitor.go#185 it is exit->die

**Comment by calavera** [comment]
@cpuguy83 I've fixed those inconsistencies, for the context in the previous PR, it's aways `exit->die`.

**Comment by tonistiigi** [comment]
This event has the same issues #11065 . If you do a kill with a signal that doesn't stop the container you don't get `exit` event if it crashes later.

**Comment by calavera** [comment]
@tonistiigi I believe the problem is not about this new event, but about the signal management issue described in your issue, in general. We agreed that we want to have this event, we need to solve the re-starting logic separately.

**Comment by tonistiigi** [comment]
@calavera Yes, nothing we can do with this event to fix this. Just pointing out that 1) this doesn't always work 2) I think we should solve issues with the kill signals before we release this.

**Comment by calavera** [comment]
> I think we should solve issues with the kill signals before we release this.

I kinda disagree, I don't think one should block the other, and as you can see in the original PR, several maintainers already are okay with getting this in.

**Comment by mountkin** [comment]
Hello maintainers. IMHO we don't need this event anymore because since 1.8.0 there is always a "kill" event before the "die" event if the container is stopped by a administrator via "docker stop".
But if the container stops on its own there is no "kill" event before the "die". See my previous report here https://github.com/docker/docker/issues/15438

I think we should add a new field to the event message to indicate how the event is triggered rather than a new "exit" event. For example, we want  to distinguish the events that emitted from "docker build " command from the normal events.

**Comment by calavera** [comment]
Okay, closing this. I'm not really sure we need it either. Will reopen if it's needed.

**Pull request closed without merging**
