### PR TITLE
[project] bump go to go 1.7.4

### PR DESCRIPTION
**Pull request by tophj-ibm**
Bumps go version to 1.7.4

go 1.7.4 patch notes here https://groups.google.com/forum/#!topic/golang-announce/2lP5z9i9ySY

### CODE REVIEW

**Comment by tophj-ibm** [comment]
@jhowardmsft FYI I upped the go version on Dockerfile.simple and Dockerfile.windows here.

**Review by justincormack — APPROVED** [review]

**Comment by justincormack** [comment]
@tophj-ibm needs a rebase alas.

**Comment by justincormack** [comment]
This needs cherry picking for 1.12 as well.

**Comment by tophj-ibm** [comment]
rebased

**Comment by justincormack** [comment]
1.12 equivalent is here https://github.com/docker/docker/pull/29220 (different Go version...)

**Comment by tonistiigi** [comment]
@tophj-ibm no `Dockerfile.s390x` ?

**Comment by tophj-ibm** [comment]
thanks @tonistiigi, added s390x

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
This did not end into 1.13.0 (only in 1.12.6), moving the milestone so that it can get into 1.13.1

**Pull request merged**
