### PR TITLE
Extract $HOME usages into utils.GetHomeDir() for windows

### PR DESCRIPTION
**Pull request by ahmetb**
Refactored getHomeDir in docker/docker to GetHomeDir in utils. Currently covers all use cases on the client-side.

@icecrime can we please tag with `windows`?
cc: maintainers @vieux @jfrazelle

### CODE REVIEW

**Comment by jfrazelle** [comment]
awesome!!!

**Comment by ahmetalpbalkan** [comment]
yeah, realized this broke the deamon.go code, will move this to utils package.

**Comment by ahmetalpbalkan** [comment]
CI is green now. cc: @icecrime

**Comment by tiborvass** [comment]
@ahmetalpbalkan ?

**Comment by ahmetalpbalkan** [comment]
@tiborvass oh I didn't realize it was an open PR and I was doing some home cleaning and I am just re-forking the project. Will try to reopen.

**Comment by jfrazelle** [comment]
he must be planning something bigger

**Comment by ahmetalpbalkan** [comment]
was it actually going to be merged? should I re-send?

**Comment by jfrazelle** [comment]
no rush :) but I know we needed something like this (but it's not essential for 1.5 or anything) it can wait til windows client is supported :)

**Comment by tiborvass** [comment]
@ahmetalpbalkan i was looking in the code if we could find a better place to the code instead of `utils`.
I feel bad after having read https://blog.golang.org/package-names :D

**Comment by ahmetalpbalkan** [comment]
@tiborvass yah, I didn't create that pkg :D

**Comment by ahmetalpbalkan** [comment]
@tiborvass that reminds me of this slide in particular https://talks.golang.org/2014/organizeio.slide#6

**Comment by tianon** [comment]
Since it's generic and not specific to Docker, why not "pkg/home" ?

"home.Get()" sounds pretty hawt to me :smile:

**Comment by ahmetalpbalkan** [comment]
@tianon well we'd use https://github.com/mitchellh/go-homedir if we're gonna go that way.

I guess I can't restore the PR at this point, I'll just re-send PR.

**Pull request closed without merging**
