### PR TITLE
Pass "meta" headers in API calls to the registry

### PR DESCRIPTION
**Pull request by shin-**
This will allow us to implement registry storages that use external authentication. The first use case for this is to allow upen-stack support (by allowing keystone tokens to be passed through to the registry, then to glance)

cc @samalba

### CODE REVIEW

**Comment by iamolegga** [comment]
I'm so sorry for bothering after all these years, but could anyone tell if we really need that `X-Meta-` limitation for headers?

Asking because there is the [open issue for 5 years without any response from owners](https://github.com/docker/docs/issues/11456) regarding this undocumented restriction for headers.

Thank you in advance 🙏

**Comment by thaJeztah** [comment]
Looks like that constraint is there indeed, e.g.; https://github.com/moby/moby/blob/578ce11a56f566c607b56f1e10ebeeb400024f98/daemon/server/router/image/image_routes.go#L159-L165

**Comment by iamolegga** [comment]
Thank you @thaJeztah for the fast reaction 🙏 So, my question is is this limitation for headers really needed or we can drop it from the code and pass all the headers specified in the docker config or via `DOCKER_CUSTOM_HEADERS`?

Real life example: we have a registry behind some authorization layer which requires some headers, so when we push images we cannot set those headers simply via docker config due to this `X-Meta-` limitation.

**Comment by thaJeztah** [comment]
Probably better to open a new ticket for that with more details; we'd probably need to look if there's potential risks in unconditionally forwarding all headers and if there's constraint that should be kept. If you can provide a more detailed use-case that would be good; also because there's various parts of the codebase being transitioned.

**Comment by iamolegga** [comment]
@thaJeztah will do. I've decided to ask it first here as this is the PR which introduces this feature.

**Comment by iamolegga** [comment]
Just opened [here](https://github.com/moby/moby/issues/50859)

**Pull request merged**
