### PR TITLE
quick doc fix for windows versions

### PR DESCRIPTION
**Pull request by BenSeverson**
Windows 7.1 doesn't exist but 8.1 does. Fixing typo

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hehe, yup.

Can you sign-off your commit using the instructions above?

LGTM (after signing)

**Comment by BenSeverson** [comment]
will do, gimme a sec since I did the edit thru github's web interface

**Comment by thaJeztah** [comment]
I saw :)

No stress, take your time!

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by jamtur01** [comment]
LGTM assuming signed.

**Comment by fredlf** [comment]
LGTM too

**Comment by thaJeztah** [comment]
Thanks @BenSeverson!

**Comment by moxiegirl** [comment]
@jfrazelle cherry-pick on this one please  (We to do this many as prep for the retooling)

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
