### PR TITLE
Add logpath to inspect container

### PR DESCRIPTION
**Pull request by bcicen**

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM
Also inspect is pretty bad tested.

**Comment by tiborvass** [comment]
This needs an API bump, and some additional documentation to the API docs. /cc @jfrazelle @vieux @SvenDowideit

**Comment by vieux** [comment]
yes, if it doesn't make it inside docker 1.5 it'll require an API bump.

alors as @tiborvass said, it need documentation.

**Comment by tiborvass** [comment]
It won't make it into 1.5, this is technically a new feature.

**Comment by bcicen** [comment]
I'm not sure how best to supplement the documentation; so I added it everywhere hostspath or hostnamepath were referenced in the API docs in https://github.com/bcicen/docker/commit/54c2e6197c3bdf1b690a433c8ac76dfbf3a4a7b9 . I'm open to suggestions.

**Comment by SvenDowideit** [comment]
if its in the output of `docker inspect` then the example in `cli.md` should be updated - otherwise LGTM - @fredlf @jamtur01

**Comment by jamtur01** [comment]
Needs rebase.

**Comment by bcicen** [comment]
@jamtur01 rebased.

**Comment by fredlf** [comment]
What Sven said, if this changes the output of `inspect`, we need to update the example at http://docs.docker.com/reference/commandline/cli/#inspect

**Comment by bcicen** [comment]
added example to cli docs.

**Comment by tiborvass** [comment]
Code LGTM Ping @jfrazelle @crosbymichael @LK4D4 

@SvenDowideit @fredlf @jamtur01 Friendly reminder that this PR is under code review.

**Comment by jfrazelle** [comment]
the docs need to be moved to 1.18 right also I think 3 commits is a bit much for adding a line to inspect, other than that LGTM

**Comment by jamtur01** [comment]
Docs LGTM

**Comment by bcicen** [comment]
Bumped to 1.18 docs, squashed commits.

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
