### PR TITLE
Fix integration test case for `docker service`

### PR DESCRIPTION
**Pull request by WeiZhang555**
Test `docker service` command with more suitable func, and make some
cleaning after test.

I had once pushed this PR but closed due to change of `service` UX, and I notice that `docker service` command has finished refactoring, so I wonder if this test case is acceptable now. :)

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by calavera** [comment]
I think the service command is going away for now https://github.com/docker/docker/pull/16645

/cc @mavenugo

**Comment by mavenugo** [comment]
@calavera thats correct. 
@WeiZhang555 pls take a look at #16645 and it simplifies the network UX significantly and the new networking features will be exiting experimental once #16645  PR is merged.

**Comment by calavera** [comment]
Thanks @mavenugo.

Sorry @WeiZhang555, I'm going to close this pull request. Please, feel free to check #16645 out, help there is very welcome, specially with testing.

**Comment by WeiZhang555** [comment]
@calavera @mavenugo 
Oops, didn't noticed that. Fine, it seems is a better UX, looking forward to it. :smile:

**Pull request closed without merging**
