### PR TITLE
Added c.Assert statements to docker_api_create_test.go

### PR DESCRIPTION
**Pull request by zelahi**
Summary: Modified tests to remove if .. else blocks and add c.Assert statements.

Referenced Issue #16756

Signed-off-by: Zuhayr Elahi elahi.zuhayr@gmail.com

### CODE REVIEW

**Comment by MHBauer** [comment]
Please clean up the squashed commit message.

**Comment by zelahi** [comment]
Done.  I cleaned up the commit message :smiley:

**Comment by vdemeester** [comment]
@zelahi no need for the `check.Commentf` in both assertion. Otherwise, looks good :-)

**Comment by zelahi** [comment]
Just squashed the both commits into one =)

**Comment by calavera** [comment]
LGTM. Merging

**Pull request merged**
