### PR TITLE
ci: set codecov token

### PR DESCRIPTION
**Pull request by crazy-max**
follow-up:
* https://github.com/moby/buildkit/pull/4660
* https://github.com/moby/buildkit/pull/4672

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Interesting why did this start failing on this PR as well?

```
=== CONT  TestDaemonProxy/command-line_options
    daemon_test.go:280: assertion failed: 172.17.0.1:4318 (received string) != example.org:5001 (string): should not have used proxy
--- FAIL: TestDaemonProxy (0.50s)
    --- PASS: TestDaemonProxy/conflicting_options (0.50s)
    --- PASS: TestDaemonProxy/reload_sanitized (1.02s)
    --- PASS: TestDaemonProxy/configuration_file (1.25s)
    --- PASS: TestDaemonProxy/environment_variables (1.31s)
    --- FAIL: TestDaemonProxy/command-line_options (6.15s)
```

**Comment by crazy-max** [comment]
> Interesting why did this start failing on this PR as well?
> 
> ```
> === CONT  TestDaemonProxy/command-line_options
>     daemon_test.go:280: assertion failed: 172.17.0.1:4318 (received string) != example.org:5001 (string): should not have used proxy
> --- FAIL: TestDaemonProxy (0.50s)
>     --- PASS: TestDaemonProxy/conflicting_options (0.50s)
>     --- PASS: TestDaemonProxy/reload_sanitized (1.02s)
>     --- PASS: TestDaemonProxy/configuration_file (1.25s)
>     --- PASS: TestDaemonProxy/environment_variables (1.31s)
>     --- FAIL: TestDaemonProxy/command-line_options (6.15s)
> ```

I don't know but this looks similar to https://github.com/moby/moby/pull/47364#issuecomment-1946208521

**Comment by vvoland** [comment]
Extracted https://github.com/moby/moby/pull/47410 from the Buildkit PR, it should help against these random failures.
Weird that these didn't start showing up immediately after we implemented OTEL..

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
Ah! Yes, I recalled the failures on the BuildKit update PR, but assumed it was related to changes in that area (guess it was flaky all along, but we were just lucky to don't hit it often?)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vvoland** [comment]
Can we merge this or do we still need to set the `CODECOV_TOKEN` secret in settings?

**Pull request merged**
