### PR TITLE
Add John Stephens to maintainers

### PR DESCRIPTION
**Pull request by thaJeztah**
Add @johnstep as a maintainer 😄 

ping @docker/core-engine-maintainers

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
self-five :) Jenkins is not testing this file 

congrats @johnstep!

**Comment by jhowardmsft** [comment]
LGTM

**Comment by vdemeester** [comment]
🎉

**Pull request merged**
