### PR TITLE
Fixes to bash completion for docker daemon

### PR DESCRIPTION
**Pull request by albers**
This is a follow-up of #15166 and #13771.

See individual commit messages.

ping @jfrazelle @tianon for review
ping @tiborvass @calavera for including in RC2.

### CODE REVIEW

**Comment by tiborvass** [comment]
Looks good, but IANTM

**Comment by tianon** [comment]
Nice, LGTM

**Comment by tiborvass** [comment]
@tianon feel free to merge

**Comment by albers** [comment]
Thanks for the ultra quick review and merge.

**Comment by tianon** [comment]
:heart:

**Comment by calavera** [comment]
cherry picked into #15091

**Comment by thaJeztah** [comment]
Awesome! :+1:

**Pull request merged**
