### PR TITLE
Fix ARG scoping for Dockerfiles with multiple FROM

### LINKED ISSUE #31892: `ARG` should be scoped to `FROM`
Currently, when using multiple `FROM` statements in the `Dockerfile` all the previous commands are reset after a `FROM` statement. But `ARG` statement behaves like a global and leaks to the next `FROM`. Only the values passed by the user should be global, the `ARG` definitions should be local to the `FROM` statement.

The leaking arg means that change in arguments in one block also invalidates all the commands in another block.

```
FROM busybox
ARG foo=bar
RUN env
FROM busybox
ARG baz=bar
RUN env
```

Currently, last command will print both `foo` and `baz` while it should only show `baz`.

When https://github.com/docker/docker/pull/31352 gets merged that means that `ARG` defined before first `FROM` should only be used for replacing a `FROM` value itself. If the same arg is needed in one of subblocks it just needs to be redefined. There is no change for user as they still need to only pass the value once.

This may seem like an obscure thing nobody will encounter in practice atm but it will become much more relevant after https://github.com/docker/docker/issues/31067#issuecomment-287126021

@dnephin

### PR DESCRIPTION
**Pull request by tonistiigi**
depends on #31352 (could rewrite it without it but there seems to be a consensus that #31352 will be merged)

fixes #31892

@dnephin

### CODE REVIEW

**Comment by thaJeztah** [comment]
left some thoughts on the issue https://github.com/docker/docker/issues/31892#issuecomment-287475769

**Comment by tonistiigi** [comment]
@thaJeztah Do you think I should rebase it without #31352 if you want to discuss that one more

**Comment by thaJeztah** [comment]
@tonistiigi hm, perhaps it's best to keep the discussion separate (but let me know if it's troublesome to do 😅)

**Comment by tonistiigi** [comment]
superseded by #31257

**Pull request closed without merging**
