### PR TITLE
builder: synchronize stderr and stdout

### LINKED ISSUE #20441: build fails randomly
**Reproduce**

- `rm -rf /var/lib/docker`
- compile and install latest **master** docker (I'm on latest fedora 23)
- from inside the repo: `docker build -t dry-run-test .`
- watch it fails at lvm2 compile step or also at update (it's random...)

When docker build with docker 1.10.1 everything runs fine. I narrowed down the issue, it seems to fail trying to compilie lvm2 (there's also a data race in daemon logs).

**Info**
```

[...truncated build output...]

checking whether to enable readline... maybe
checking whether to enable realtime support... 
checking whether to enable OCF resource agents... no
checking whether to build cluster LVM daemon... none
checking whether to build cluster mirror log daemon... no
checking whether to enable debugging... no
checking for C optimisation flag... -O2
checking whether to gather gcov profiling data... no
checking whether to enable unit testing... no
checking whether to enable valgrind awareness of pools... no
checking whether to use device-mapper... yes
checking whether to build LVMetaD... no
checking whether to enable synchronisation with udev processing... no
checking whether to enable installation of udev rules required for synchronisation... no
checking whether to enable executable path detection in udev rules... no
checking whether udev supports built-in blkid... checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PKGCONFIGINIT... no
pkg-config initialized
no
checking whether to enable O_DIRECT... yes
checking whether to build liblvm2app.so application library... no
checking whether to compile liblvm2cmd.so... no
checking whether to build Python wrapper for liblvm2app.so... no
checking whether to install fsadm... yes
checking whether to install blkdeactivate... yes
checking whether to use dmeventd... 
checking for getline in -lc... yes
checking for canonicalize_file_name in -lc... yes
checking for dlopen in -ldl... yes
checking whether to enable selinux support... yes
checking for sepol_check_context in -lsepol... no
checking for is_selinux_enabled in -lselinux... no
checking for getopt.h... (cached) yes
configure: WARNING: Disabling selinux
docker run --rm -i --privileged -e BUILDFLAGS -e KEEPBUNDLE -e DOCKER_BUILD_GOGC -e DOCKER_BUILD_PKGS -e DOCKER_CLIENTONLY -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKERFILE -e DOCKER_GRAPHDRIVER -e DOCKER_INCREMENTAL_BINARY -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TESTDIRS -e TESTFLAGS -e TIMEOUT -v "/home/runcom/koding/docker/bundles:/go/src/github.com/docker/docker/bundles" -t "docker-dev:master" hack/make.sh dynbinary test-integration-cli
Unable to find image 'docker-dev:master' locally
Pulling repository docker.io/library/docker-dev
docker: Tag master not found in repository docker.io/library/docker-dev.
See 'docker run --help'.
Makefile:123: recipe for target 'test-integration-cli' failed
make: *** [test-integration-cli] Error 125
```
*daemon logs*
```
Feb 19 11:35:11 fedora docker[14686]: checking for getline in -lc... yes
Feb 19 11:35:11 fedora docker[14686]: checking for canonicalize_file_name in -lc... yes
Feb 19 11:35:11 fedora docker[14686]: checking for dlopen in -ldl... yes
Feb 19 11:35:11 fedora docker[14686]: checking whether to enable selinux support... yes
Feb 19 11:35:11 fedora docker[14686]: checking for sepol_check_context in -lsepol... no
Feb 19 11:35:11 fedora docker[14686]: configure: WARNING: Disabling selinux
Feb 19 11:35:11 fedora docker[14686]: checking for is_selinux_enabled in -lselinux... no
Feb 19 11:35:11 fedora docker[14686]: checking for getopt.h... (cached) yes
Feb 19 11:35:11 fedora docker[14686]: ==================
Feb 19 11:35:11 fedora docker[14686]: WARNING: DATA RACE
Feb 19 11:35:11 fedora docker[14686]: Read by goroutine 84:
Feb 19 11:35:11 fedora docker[14686]: bufio.(*Writer).Write()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/bufio/bufio.go:589 +0x9b
Feb 19 11:35:11 fedora docker[14686]: bufio.(*ReadWriter).Write()
Feb 19 11:35:11 fedora docker[14686]: <autogenerated>:20 +0x8e
Feb 19 11:35:11 fedora docker[14686]: fmt.Fprintf()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/fmt/print.go:189 +0xd2
Feb 19 11:35:11 fedora docker[14686]: net/http.(*chunkWriter).Write()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/net/http/server.go:268 +0x345
Feb 19 11:35:11 fedora docker[14686]: bufio.(*Writer).flush()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/bufio/bufio.go:562 +0x1a7
Feb 19 11:35:11 fedora docker[14686]: bufio.(*Writer).Flush()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/bufio/bufio.go:551 +0x3a
Feb 19 11:35:11 fedora docker[14686]: net/http.(*response).Flush()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/net/http/server.go:1204 +0x7c
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/pkg/ioutils.(*WriteFlusher).Flush()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/writeflusher.go:49 +0x104
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/pkg/ioutils.(*WriteFlusher).Write()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/writeflusher.go:34 +0x151
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/pkg/streamformatter.(*StderrFormatter).Write()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/pkg/streamformatter/streamformatter.go:167 +0x17e
Feb 19 11:35:11 fedora docker[14686]: io.copyBuffer()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/io/io.go:383 +0x303
Feb 19 11:35:11 fedora docker[14686]: io.Copy()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/io/io.go:351 +0x78
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/container.AttachStreams.func2()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/container/container.go:444 +0x26d
Feb 19 11:35:11 fedora docker[14686]: Previous write by goroutine 65:
Feb 19 11:35:11 fedora docker[14686]: bufio.(*Writer).Write()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/bufio/bufio.go:607 +0x4ce
Feb 19 11:35:11 fedora docker[14686]: bufio.(*ReadWriter).Write()
Feb 19 11:35:11 fedora docker[14686]: <autogenerated>:20 +0x8e
Feb 19 11:35:11 fedora docker[14686]: fmt.Fprintf()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/fmt/print.go:189 +0xd2
Feb 19 11:35:11 fedora docker[14686]: net/http.(*chunkWriter).Write()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/net/http/server.go:268 +0x345
Feb 19 11:35:11 fedora docker[14686]: bufio.(*Writer).flush()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/bufio/bufio.go:562 +0x1a7
Feb 19 11:35:11 fedora docker[14686]: bufio.(*Writer).Flush()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/bufio/bufio.go:551 +0x3a
Feb 19 11:35:11 fedora docker[14686]: net/http.(*response).Flush()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/net/http/server.go:1204 +0x7c
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/pkg/ioutils.(*WriteFlusher).Flush()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/writeflusher.go:49 +0x104
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/pkg/ioutils.(*WriteFlusher).Write()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/writeflusher.go:34 +0x151
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/pkg/streamformatter.(*StdoutFormatter).Write()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/pkg/streamformatter/streamformatter.go:152 +0x127
Feb 19 11:35:11 fedora docker[14686]: io.copyBuffer()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/io/io.go:383 +0x303
Feb 19 11:35:11 fedora docker[14686]: io.Copy()
Feb 19 11:35:11 fedora docker[14686]: /usr/lib/golang/src/io/io.go:351 +0x78
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/container.AttachStreams.func2()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/container/container.go:444 +0x26d
Feb 19 11:35:11 fedora docker[14686]: Goroutine 84 (running) created at:
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/container.AttachStreams()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/container/container.go:455 +0x4aa
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/container.(*Container).Attach()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/container/container.go:362 +0x172
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/daemon.(*Daemon).containerAttach()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/daemon/attach.go:111 +0x5f8
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/daemon.(*Daemon).ContainerAttachRaw()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/daemon/attach.go:62 +0x12e
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/builder/dockerfile.(*Builder).run.func1()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/builder/dockerfile/internals.go:543 +0xf3
Feb 19 11:35:11 fedora docker[14686]: Goroutine 65 (running) created at:
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/container.AttachStreams()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/container/container.go:454 +0x448
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/container.(*Container).Attach()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/container/container.go:362 +0x172
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/daemon.(*Daemon).containerAttach()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/daemon/attach.go:111 +0x5f8
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/daemon.(*Daemon).ContainerAttachRaw()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/daemon/attach.go:62 +0x12e
Feb 19 11:35:11 fedora docker[14686]: github.com/docker/docker/builder/dockerfile.(*Builder).run.func1()
Feb 19 11:35:11 fedora docker[14686]: /home/runcom/koding/docker/.gopath/src/github.com/docker/docker/builder/dockerfile/internals.go:543 +0xf3
Feb 19 11:35:11 fedora docker[14686]: ==================
Feb 19 11:35:11 fedora docker[14686]: time="2016-02-19T11:35:11.615221595+01:00" level=debug msg="Build cancelled, killing and removing container: 9fa0323fa1c59d06afd7118b90e33e49f9a06e233772620333175fede3353969"
Feb 19 11:35:11 fedora docker[14686]: time="2016-02-19T11:35:11.615478096+01:00" level=debug msg="Sending 9 to 9fa0323fa1c59d06afd7118b90e33e49f9a06e233772620333175fede3353969"
Feb 19 11:35:11 fedora docker[14686]: checking for library containing tgetent... 
Feb 19 11:35:11 fedora docker[14686]: time="2016-02-19T11:35:11.648425438+01:00" level=debug msg="attach: stderr: end"
Feb 19 11:35:11 fedora docker[14686]: time="2016-02-19T11:35:11.648524391+01:00" level=debug msg="attach: stdout: end"
Feb 19 11:35:11 fedora docker[14686]: time="2016-02-19T11:35:11.717904775+01:00" level=debug msg="Releasing addresses for endpoint insane_davinci's interface on network bridge"
Feb 19 11:35:11 fedora docker[14686]: time="2016-02-19T11:35:11.718030376+01:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
Feb 19 11:35:11 fedora docker[14686]: time="2016-02-19T11:35:11.771204653+01:00" level=warning msg="could not write error response: write unix /var/run/docker.sock->@: write: broken pipe"
```

### PR DESCRIPTION
**Pull request by LK4D4**
it's concurrent streams and should be synchronized before writing to response.
Otherwise there will be race in writing to *bufio.Writer in
net/http.response.

Fixes  #20441

Signed-off-by: Alexander Morozov lk4d4@docker.com

### CODE REVIEW

**Comment by runcom** [comment]
Does this fix the race here? https://github.com/docker/docker/issues/20441#issue-134605645

**Comment by LK4D4** [comment]
@runcom yes, it fix that race indeed.

**Comment by runcom** [comment]
Awesome, though I don't think that the race is the cause of that issue :(

**Comment by runcom** [comment]
LGTM if tests pass

**Comment by calavera** [comment]
LGTM

**Pull request merged**
