### PR TITLE
Ensure image for all arch in the same file

### PR DESCRIPTION
**Pull request by hqhq**
They are doing this for the same purpose, should in the
same file.

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by DieterReuter** [comment]
ping @Govinda-Fichtner, @StefanScherer.
Please check where is the best place to handle the Docker images for the integration tests. I'd like to have it only within a single file, if this is possible. Then it's easier to maintain.
Even with this PR, the logic is split into two files, `.ensure-frozen-images` and `.ensure-images`.

**Comment by Govinda-Fichtner** [comment]
@hqhq Could you explain why it is necessary to have a separate `.ensure-images`? 

@hqhq @LK4D4 @DieterReuter @StefanScherer I personally feel it would reduce the level of indirection if we just kept everything in one place. In my opinion this should be the existing `.ensure-frozen-images`.

I think there is room for improvement when it comes to fetching and tagging the architecture specific images. Here it should be possible to come up with a generic approach that gets its input from variables defined in the architecture specific Dockerfile.

As a first step I would like to keep everything in `.ensure-frozen-images`. Afterwards I would love to create a PR that comes up with a generic solution for fetching and tagging the architecture specific images in `.ensure-frozen-images`.

What do you think?

**Comment by hqhq** [comment]
@Govinda-Fichtner Agreed, I don't see the necessity to have a separate `.ensure-images`, I've changed the PR, PTAL.

**Comment by calavera** [comment]
LGTM, but it looks like it needs a rebase.

**Comment by StefanScherer** [comment]
LGTM.

**Comment by hqhq** [comment]
Close in favor of https://github.com/docker/docker/pull/18506

**Pull request closed without merging**
