### PR TITLE
Removing Hub v1 documentation, Hub v2 documentation will come from th…

### PR DESCRIPTION
**Pull request by SvenDowideit**
…at repository

Signed-off-by: Sven Dowideit SvenDowideit@home.org.au

### CODE REVIEW

**Comment by moxiegirl** [comment]
@SvenDowideit If you want to make a Makefile change, please do that on another PR.  I can't let this Makefile change through without testing.

**Comment by SvenDowideit** [comment]
yeah, sorry, its a change i needed to make to get the docs to build in my env - peasy to remove :)

**Comment by thaJeztah** [comment]
@SvenDowideit I see two images referenced in userguide as well; can you check if those are still used anywhere. If not, remove those as well?

**Comment by SvenDowideit** [comment]
@thaJeztah done.

**Comment by thaJeztah** [comment]
Thanks! LGTM

**Pull request merged**
