### PR TITLE
Add useful info to builder cache logrus.Debug

### PR DESCRIPTION
**Pull request by duglin**
Closes: #16790

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by LK4D4** [comment]
I don't like output:
```
Use cached version: &{[/bin/sh -c #(nop) MAINTAINER Tianon Gravi <admwiggin@gmail.com> (@tianon)]}
```
I think we can remove it or we should use logic from `dispatch` where it construct line from `Dockerfile` from `*parser.Node`

**Comment by duglin** [comment]
@LK4D4 I'm pretty sure we can find the original Dockerfile command, but I didn't think that was very useful. Since this is only shown in the daemon debug logs I was assuming people are looking at that closely because things are not acting the way they think it should. Since the end-user will be notified during the build at to whether each step is using the cache or not, I assumed we'd want more info here than just what the Dockerfile shows.

So, for example, a COPY might show:
```
Use cached version: &{[/bin/sh -c #(nop) COPY file:ae22447707e6ff17dfa463b38a49c7c7d8540b8a4ee5cc881f241e1e396b9ba7 in /tmp/]}
```
which shows the hash for the file being copied and allows an admin to then look at the history of sibling images to see if that hash is/isn't there - and that should give them a clue as to why the cache was, or was not, used.  Granted there are other reasons (like env vars) but this seems like a small/safe thing to show.

Let me know what you think.

**Comment by LK4D4** [comment]
@duglin Yeah, maybe you're right, but logs became extremely noisy(try build docker image).
Now I think that maybe it's better to remove those logs, they're noisy and show too much internal info.
However maybe other decide to keep it, ping @docker/core-maintainers

**Comment by duglin** [comment]
I agree it comes down to whether we want to say anything at all.

**Comment by duglin** [comment]
one question for folks.... do we expect deployments to run with debug on normally or just when they want to investigate something?  I've been assuming its only when things are funky.

Would be nice if we could turn on debug for just certain components (e.g. `--debug=builder/*` ) which I think is technically possible if logrus wanted to support it.

**Comment by icecrime** [comment]
> one question for folks.... do we expect deployments to run with debug on normally or just when they want to investigate something? I've been assuming its only when things are funky.

Agree, which is why I wouldn't care too much about the aesthetics of a debug log. So +1 on this

**Comment by jfrazelle** [comment]
I run in debug mode all the time but ya i expect stuff like this

**Comment by icecrime** [comment]
LGTM (needs rebase though)

**Comment by thaJeztah** [comment]
Agreed, debug logs *should be noisy*, LGTM (fwiw) :-)

(we could add `--log-level=whatsapp`)

**Comment by vdemeester** [comment]
@duglin needs a rebase :sweat_smile:

**Comment by duglin** [comment]
rebased

**Comment by vdemeester** [comment]
LGTM 🐰

**Pull request merged**
