### PR TITLE
Add filter to /images/json docs

### LINKED ISSUE #14894: Is the query parameter 'filter' for '/images' officially supported ?
The query parameter [filter](https://github.com/docker/docker/blob/7e4db0a3704b3f156e6a67ce32a7fcada61fdef1/api/server/server.go#L358) can be used in `GET /images/json?filter=myname` to match on image name. This is not documented so I wonder whether this is an official feature on can rely on ?

BTW, `filter` doesn't work well with default registries `index.docker.io` and `docker.io`. I.e. if you create an  image `docker.io/myimage` and try to get it back with `GET /images/json?filter=docker.io/myimage` you get an empty list.

### PR DESCRIPTION
**Pull request by duglin**
Closes #14894

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks

I think it would make sense to deprecate this filter, and move it to the regular "filters" parameter, wdyt?

**Comment by duglin** [comment]
I dunno.  Is "filter" deprecated?

**Comment by thaJeztah** [comment]
@duglin not afaik, but having both `filters=` and `filter=` is a bit weird from a UX perspective, so adding a "name" filter option to `filters` would make that cleaner (and mark the `filter` deprecated)

Anyway, not something for this PR of course, just got "triggered" by this change :-)

**Comment by thaJeztah** [comment]
let me ping some people so that this can be merged :-)

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by jamtur01** [comment]
LGTM

**Comment by moxiegirl** [comment]
LGTM @duglin thank you!

**Pull request merged**
