### PR TITLE
Update go-winio to v0.4.2

### PR DESCRIPTION
**Pull request by darstahl**
Signed-off-by: Darren Stahl <darst@microsoft.com>

**- What I did**

This fixes a bug causing the daemon on Windows Nanoserver to fail to start. Validated locally.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM

**Comment by thaJeztah** [comment]
@jhowardmsft I assume we need this for 17.06?

ping @johnstep PTAL

**Comment by jhowardmsft** [comment]
Yes if gowinio 0.4.1 made it in 17.06

**Comment by thaJeztah** [comment]
I don't think it made it yet, but I guess we can do them both

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
all green

**Comment by darrenstahlmsft** [comment]
Just to clarify, this is needed for 17.06

**Pull request merged**
