### PR TITLE
Remove unnecessary function parameter, add mirror endpoint test

### PR DESCRIPTION
**Pull request by aidanhs**
I wasn't such a fan of the approach in #15378 which added a boolean function parameter, so I made a new PR to remove it. Then I included a regression test for the issue fixed by the previous PR to make this more attractive to merge :D

### CODE REVIEW

**Comment by dmp42** [comment]
cc @docker/distribution-maintainers

**Comment by tiborvass** [comment]
@aidanhs thanks for the test, I was trying to get an integration-cli test or a test in distribution but I guess your solution is better than nothing so thanks again.

As for the *boolean* issue, I seriously don't see it as an issue since it's pretty readable and clear what it is and it is not exported. If it were exported I would probably just pass in some enum instead of rebuilding another slice. Also, the standard library has a whole bunch of examples that use a boolean the way I did.

But if it really bothers you, I don't mind. LGTM

**Comment by aidanhs** [comment]
There's such locality it's not a big issue if you prefer avoiding pointless churn in version control history - I freely admit it's a personal preference, I'll revert that change at make it just about the test if you prefer.

**Comment by tiborvass** [comment]
Lol I prefer with Boolean in this particular case (would agree otherwise)
but others are likely to disagree /cc @stevvooe @RichardScothern

**Comment by icecrime** [comment]
*Whatever you decide, we can still keep the test :wink:*

**Comment by stevvooe** [comment]
:-1: for boolean function parameters. They tend affect code clarity over time.

This structure is logically more coherent. We have a dataset, _endpoints_, which is clearly filtered by whether or not they are a mirror.

**Comment by aaronlehmann** [comment]
Personally, the boolean argument doesn't bother me. I find it slightly clearer for the endpoint generation to be centralized in `lookupEndpoints` instead of going through an extra filtering step in some cases (one could miss the fact that the list returned by `lookupEndpoints` is not actually the list of endpoints used for pushes). But the patch looks fine to me if people prefer this style.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
