### PR TITLE
Modified `docker export` to allow an --output flag

### PR DESCRIPTION
**Pull request by jessfraz**
Carry of #9761, just rebased

### CODE REVIEW

**Comment by jfrazelle** [comment]
it had docs approval iirc, just needed rebase, ping @tiborvass @crosbymichael

**Comment by jamtur01** [comment]
Docs LGTM

**Comment by jfrazelle** [comment]
this one should be good to go @icecrime @crosbymichael or @LK4D4

**Comment by tiborvass** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
ping @fredlf @SvenDowideit @moxiegirl

**Comment by SvenDowideit** [comment]
yes, Docker LGTM :)

**Pull request merged**
