### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by liubin**
**\- What I did**

Fix some typo's in sources and documents.

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

Fix some typo's in sources and documents.

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: bin liu liubin0329@gmail.com

### CODE REVIEW

**Comment by liubin** [comment]
I saw that this PR has modified some files that #23797 did

If #23797 be merged, i need do a rebase.

**Comment by LK4D4** [comment]
ping @thaJeztah

**Comment by SvenDowideit** [comment]
LGTM

**Comment by SvenDowideit** [comment]
@liubin thank you :) turns out GH worked out what to do

**Pull request merged**
