### PR TITLE
Update libcontainer to 1597c68f7b941fd97881155d7f077852e2914e7b

### PR DESCRIPTION
**Pull request by LK4D4**
This commit contains changes for docker:
- user.GetGroupFile to user.GetGroupPath docker/libcontainer#301
- Add systemd support for OOM docker/libcontainer#307
- Support for custom namespaces docker/libcontainer#279, docker/libcontainer#312
- Fixes #9699 docker/libcontainer#308

I put all in one commit, because don't want to have broken commits in master for better git-bisect experience.

ping @icecrime @erikh @jfrazelle @unclejack @crosbymichael @tiborvass

### CODE REVIEW

**Comment by unclejack** [comment]
Do we need this for 1.4.2?

**Comment by LK4D4** [comment]
@unclejack I don't know, this fixing bad bug with `exec`, but `exec` is not critical part of docker.

**Comment by ggrandes** [comment]
+1 for 1.4.2 :-)

**Comment by fcamblor** [comment]
Is there any workaround to be able to stop the running instance ? (specifying a timeout to `docker stop` doesn't help)

**Comment by LK4D4** [comment]
@fcamblor You need to find cgroups for this container and remove them.
I think something like:
```
find /sys/fs/cgroup *<container-id>
```
should help find them, but I don't tried.

**Comment by fcamblor** [comment]
Thanks, in fact, I were using `boot2docker` (mac install) and stopping/restarting boot2docker removed the running instance.

**Pull request merged**
