### PR TITLE
Add apparmor dependency to debian package

### LINKED ISSUE #9745: [docs]: add note about installing apparmor to ubuntu installation docs
Description of problem:

After installing the lxc-docker package from the repositories
provided by Docker on Ubuntu 14.04.1 the Docker daemon fails to
start because of the missing executable `/sbin/apparmor_parser`.

`docker version`:

    Client version: 1.4.1
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 5bc2ff8
    OS/Arch (client): linux/amd64
    FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 

`docker info`:

    FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 

`uname -a`:

    Linux srv28 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

A new physical server with a fresh minimal install of Ubuntu 14.04.1.

How reproducible:

On a custom minimal Ubuntu install without apparmor this is always reproducable. The standard Ubuntu install seems to include apparmor and therefore the problem is not apparent. 

Steps to Reproduce:
1. Follow install instructions: http://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation
2. `service docker start`
2. `docker info`

Actual Results:

The Docker daemon fails to start.  `docker info` outputs

    FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 

and `/var/log/upstart/docker.log` contains

    INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    INFO[0000] +job init_networkdriver()                    
    INFO[0000] -job init_networkdriver() = OK (0)           
    INFO[0000] WARNING: Your kernel does not support cgroup swap limit. 
    FATA[0000] Error loading docker apparmor profile: fork/exec /sbin/apparmor_parser: no such file or directory () 

Expected Results:

The Docker daemon should be up and running.  `docker info`
should output something like

    Containers: 0
    Images: 0
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Dirs: 0
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-43-generic
    Operating System: Ubuntu 14.04.1 LTS
    CPUs: 12
    Total Memory: 62.89 GiB
    Name: srv28
    ID: SDXF:XYT2:PAMA:OSYS:2QJD:VIZN:MDUU:PYJK:YJXY:2RCA:4A6F:ZCDL
    WARNING: No swap limit support

and `/var/log/upstart/docker.log` should contains something like

    INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    INFO[0000] +job init_networkdriver()                    
    INFO[0000] -job init_networkdriver() = OK (0)           
    INFO[0000] WARNING: Your kernel does not support cgroup swap limit. 
    INFO[0000] Loading containers: start.                   
    INFO[0000] Loading containers: done.                    
    INFO[0000] docker daemon: 1.4.1 5bc2ff8; execdriver: native-0.2; graphdriver: aufs 

Additional info:

Running the following command allows the Docker daemon to start
properly:

    apt-get install apparmor

Thus the lxc-docker package should depend on apparmor which contains the missing executable `/sbin/apparmor_parser`.

### PR DESCRIPTION
**Pull request by andreas-h**
fixes #9745

### CODE REVIEW

**Comment by jfrazelle** [comment]
should this be recommends, ping @tianon ?

**Comment by andreas-h** [comment]
not sure.  without the *apparmor* package, the docker daemon doesn't
start, the error is "Error loading docker apparmor profile: fork/exec
/sbin/apparmor_parser: no such file or directory ()", as given in the
issue.  so it seems that the package does indeed *depend* on apparmor.

Unless, of course, there is a valid reason to install the lxc-docker
package when the docker daemon cannot be used ...

**Comment by tianon** [comment]
I don't think even `Recommends` is necessarily right, but it's definitely closer than `Depends`:

https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps
> `Recommends`
> This declares a strong, but not absolute, dependency.
> 
> The Recommends field should list packages that would be found together with this one in all but unusual installations.

In this case, it's only a `Recommends` level dependency on Ubuntu platforms (and other platforms where AppArmor is standard).  On Debian, for example, we don't need `apparmor` at all unless we've explicitly App-Armor-enabled our system (at which point we get to keep the pieces).

The way this discrepancy is _usually_ solved is with a bit of packaging that only happens when you're building for that particular platform (see http://sources.debian.net/src/docker.io/1.3.3~dfsg1-2/debian/rules/#L27-L30 for an example of how this is done for `src:docker.io` downstream).  In our case, we use the same deb for both platforms (which is also a problem we're brainstorming potential fixes for), so we don't have the luxury of conditional dependencies like that. :confused:

**Comment by gdm85** [comment]
@tianon but if the package for Ubuntu doesn't work out-of-the-box on Ubuntu, it's a dependency not a recommended package.

What am I missing here?

**Comment by tianon** [comment]
That "the package for Ubuntu" isn't _just_ for Ubuntu.  It's for Debian,
etc too.

**Comment by seschwar** [comment]
apparmor should be a dependency for the Ubuntu package. If you don't want to add additional dependencies to the Debian package (apprarmor, libapparmor-perl and libapparmor1 are 1.4M) you should consider making separate repositories for Ubuntu and Debian. Otherwise the user experience for installing lxc-docker on Ubuntu is simply and unnecessarily broken.

**Comment by jfrazelle** [comment]
wdyt @tianon should we close for your build scripts patch

**Comment by tianon** [comment]
Regardless, we have to close, since this is an Ubuntu-specific dependency and the package in question is generic. :cry:

**Comment by andreas-h** [comment]
Then, at the very least, document this in the description of the Ubuntu
install.  Otherwise, you risk losing Ubuntu users as your software
(docker) is not working as you're advertising it (in the install
instructions for Ubuntu).

**Comment by tianon** [comment]
I agree 100%!  Also, if there's an easy way to detect AppArmor from a shell
script, I think we should add installing this package to
"project/install.sh" appropriately, especially since that would also work
for Debian systems that happen to be manually configured for AppArmor.

**Pull request closed without merging**
