### PR TITLE
Fix documentation typo in articles/basics.md

### PR DESCRIPTION
**Pull request by sergey-alekseev**
[ci skip]
Signed-off-by: Sergey Alekseev sergey.alekseev.minsk@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
You do not need to close and open a new PR when there is an error, even Gordon who threw the error said that, please keep this one open

**Comment by sergey-alekseev** [comment]
@jfrazelle I know, my bad. Intended to be a quick fix and I didn't want to clone the repo locally, so couldn't do amending and force pushing.

**Comment by moxiegirl** [comment]
LGTM.  Thank you for the contribution.

ping @docker/docs-owners

**Comment by tiborvass** [comment]
NOT LGTM

**Comment by calavera** [comment]
Thanks for your contribution @sergey-alekseev. Please, make the commit message as much explanatory as possible, we like to keep the repo history as much self explanatory as possible. The new PR title is a good candidate as commit message.

**Comment by fredlf** [comment]
LGTM

**Comment by sergey-alekseev** [comment]
So much hassle because of a small change...
Thanks for your time, guys.

**Comment by calavera** [comment]
Thanks for the change @sergey-alekseev. Merging!

**Pull request merged**
