### PR TITLE
Move 1.10 to API version 1.110

### PR DESCRIPTION
**Pull request by ibuildthecloud**
https://github.com/docker/docker/issues/17521

Signed-off-by: Darren Shepherd darren@rancher.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
:-1: I do not think we should not tie these two versions together, and changing the scheme will just make things more confusing.

**Comment by thaJeztah** [comment]
Hm, yes, I feel your pain, but I'm not sure this is the solution. Although *currently* the versions are bumped in sync, this is not set in stone, so could change at some point

**Comment by duglin** [comment]
I think this is where "theory" and "reality" bump heads :-)

In theory it sounds nice to have separate version numbers but in reality we end up changing the API version number every release and for those times when people need to do the mapping its kind of annoying. Unless we actually change our current process and freeze the APIs for a while, I'm inclined to agree with some kind of harmonization between the two version numbers.

**Comment by ibuildthecloud** [comment]
I think @duglin has the right idea :smile:   I don't care what the solution is really, it's just that for somebody like me that has to support a lot of different people running different random Docker versions, it's just annoying and hard.  Even when I work with other engineers it's terrible to say "no, I mean *API VERSION* 1.18 not Docker version."

It seems there has been a lot of effort lately to add a framework to handle API version maintenance efficiently.  Users already expect the API version to bump with each release so for the sanity of users like me, lets just lock it to something sane.

**Comment by calavera** [comment]
I really really hear you. I don't know in which api version I live anymore. I don't know if this is the best solution, but I'm looking forward to have a fix for this.

**Comment by thaJeztah** [comment]
Hm, looks like we don't really reach consensus on this, perhaps we should close this one and rethink the versioning if we reach docker 2.0?

**Comment by calavera** [comment]
I agree with @thaJeztah. I don't think we should do this now, but it's worth having it in mind for a new major version.

I'm going to close this PR.

**Pull request closed without merging**
