### PR TITLE
Add extra permission check in removal test

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

@kolyshkin ptal

**Comment by crosbymichael** [comment]
ping

**Comment by thaJeztah** [comment]
we might want to disable this docker-py test; looks flaky https://jenkins.dockerproject.org/job/Docker-PRs/54995/console

```
14:03:14 _______________ ExecDemuxTest.test_exec_command_tty_stream_demux _______________

14:03:14 tests/integration/api_exec_test.py:324: in test_exec_command_tty_stream_demux

14:03:14     assert (b'hello out\r\n', None) in exec_log

14:03:14 E   AssertionError: assert (b'hello out\r\n', None) in [(b'hello out\r\nhello err\r\n', None)]

**Comment by thaJeztah** [comment]
@cpuguy83 @kolyshkin PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
all green now; merging

**Comment by thaJeztah** [comment]
relates to https://github.com/moby/moby/pull/39193, which added this code

**Pull request merged**
