### PR TITLE
Welcome the captains :-)

### PR DESCRIPTION
**Pull request by thaJeztah**
The Docker Captains are going to assist in our triage process! \o/ \o/

ping @docker/core-engine-maintainers 

/cc @alexellis @anonymuse @chanwit @fntlnz @gianarb @rheinwein 

**- A picture of a cute animal (not mandatory but encouraged)**

xp9ptw

### CODE REVIEW

**Comment by justincormack** [comment]
Hey, the image caption has a mis-spelling...

**Comment by thaJeztah** [comment]
@justincormack it wasn't me! blame Gooogle image search, but feel free to open a pull request :D

**Review by vdemeester — APPROVED** [review]
LGTM 🦁 👍

**Comment by fntlnz** [comment]
yay!

**Comment by gianarb** [comment]
👍

**Comment by alexellis** [comment]
Captains be like:

**Review by estesp — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
LGTM. And welcome! :cat:

**Review by justincormack — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]
LGTM and welcome

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by mlaventure** [comment]
6 LGTM ought to be more than enough.

Welcome!

**Comment by anonymuse** [comment]
Late LGTM but still excited to be part of the party!

**Pull request merged**
