### PR TITLE
Windows: Remove servicing mode

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Removes servicing mode for Windows containers. In RS1-RS3, this actually never worked and was never triggered by the platform. In RS4, cupdate was removed from the image so is never triggered. Hence removing redundant code.

@darrenstahlmsft @johnstep PTAL.  (Note once merged, I'll remove the remaining pieces from HCSShim and revendor it. Just some sequencing needed).  

@swernli FYI :)

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Rebased

**Review by thaJeztah — APPROVED** [review]
SGTM

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
ping @darrenstahlmsft now you're back :)

**Review by darstahl — APPROVED** [review]
LGTM

**Pull request merged**
