### PR TITLE
#6141 Allowing configfile to be overwritten with an environment variable...

### PR DESCRIPTION
**Pull request by brimstone**
This allows the .dockercfg location to be overwritten with an environment variable, DOCKER_CFG.

### CODE REVIEW

**Comment by duglin** [comment]
Actually, I'd prefer to hold off on this one as this is a UX change and there's already work going on to revamp how the config file processing is done.

**Comment by brimstone** [comment]
whomp whomp :(

**Comment by duglin** [comment]
If you're curious you can look at this branch: https://github.com/duglin/docker/tree/Config  at the current incantation

**Comment by ehazlett** [comment]
@brimstone have you had a chance to look at @duglin branch?

**Comment by brimstone** [comment]
@ehazlett yes, but I don't plan on doing anything about this PR until after @duglin's branch has been merged in.

**Comment by ehazlett** [comment]
@brimstone thanks for the update!

**Comment by duglin** [comment]
@brimstone Now that #12009 is merged - would you be interested in morphing this PR so that people could specify a different dir (other than ~/.docker) via both env var (DOCKER_CFG) and cmd line option (--config) ?

Personally, I think this will be important when more than one CLI needs to be run at the same time and each needs its own config file.

**Comment by icecrime** [comment]
Ping @brimstone!

**Comment by brimstone** [comment]
@duglin @icecrime I'm sorry, but apparently it's been a week and I haven't found the time. I don't want to be a blocker on this. This pull request can probably be closed.

**Comment by duglin** [comment]
@brimstone if you think you'll have time to get to it over the next week then you can reopen it, but if not I'd be more than happy to carry it. Just let me know.

**Comment by duglin** [comment]
PR #12856 created to carry this.

**Pull request closed without merging**
