### PR TITLE
Fix unmount redeclaration on darwin in github.com/docker/docker/pkg/m…

### PR DESCRIPTION
**Pull request by FabianKramm**
Signed-off-by: Fabian Kramm kramm@covexo.com 

We use the moby project as a dependency in our project and unfortunately it does not compile under darwin (without cgo) on the current master version anymore. The compile error we get is:

```
# github.com/docker/docker/pkg/mount
pkg/mount/unmount_unix.go:7:6: unmount redeclared in this block
        previous declaration at pkg/mount/mounter_unsupported.go:9:39
```

**- How to reproduce**
Clone the moby project into `$GOPATH/src/github.com/docker/docker` and run `GOOS=darwin go install "github.com/docker/docker/pkg/mount"` and you will see the above error.

**- What I did**
Fixed the compile error in darwin

**- How I did it**
Moved the unmount function declaration away from "github.com/docker/docker/pkg/mount/mounter_unsupported.go" to a new file "github.com/docker/docker/pkg/mount/unmount_unsupported.go" that is only included in windows, where the unmount function is not declared.

**- How to verify it**
1. Clone the fork into `$GOPATH/src/github.com/docker/docker`
2. Checkout master branch
3. Run `GOOS=darwin go install "github.com/docker/docker/pkg/mount"`
4. Switch branch to fix-darwin-compile
5. Run `GOOS=darwin go install "github.com/docker/docker/pkg/mount"` again and you shouldn't see the error message anymore

**- A picture of a cute animal (not mandatory but encouraged)**
Cute dog

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @kolyshkin

**Comment by kensaggy** [comment]
Also ran into this issue, thanks for fixing @FabianKramm!
Looking forward to seeing this merged soon

**Comment by kolyshkin** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by kensaggy** [comment]
Thanks for the quick turnaround everyone!

**Pull request merged**
