### PR TITLE
Add @calavera to maintainers

### PR DESCRIPTION
**Pull request by icecrime**
Also removed a few unnecessary trailing whitespace in the process.

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
closes https://github.com/docker/docker/issues/12938 ;-)

**Comment by estesp** [comment]
@icecrime apparently broke something with this patch according to janky :P

**Comment by tianon** [comment]
:+1:

**Comment by calavera** [comment]
LGTM :trollface:

**Comment by runcom** [comment]
LGTM :tada:

**Comment by thaJeztah** [comment]
The builds have spoken; Janky and Experimental failed, Windows passed, so looks that @calavera will be Windows maintainer :)

LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
