### PR TITLE
Refactor seccomp types to reuse runtime-spec, and add support for "ErrnoRet"

### PR DESCRIPTION
**Pull request by thaJeztah**
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice! https://github.com/opencontainers/runtime-spec/pull/1087 was just opened, and has a change I was also considering for a follow-up; with that, it's possible to create a profile that uses `ENOSYS` as a default (which could be our default profile, or could be used by a user in a custom profile)

**Comment by thaJeztah** [comment]
@justincormack @tonistiigi @AkihiroSuda ptal

**Comment by thaJeztah** [comment]
Arm64 failure is tracked through https://github.com/moby/moby/issues/42357

```
--- FAIL: TestDaemonHostGatewayIP (5.37s)
    daemon_linux_test.go:161: [ddd4a2c7b3721] failed to start daemon with arguments [--data-root /go/src/github.com/docker/docker/bundles/test-integration/TestDaemonHostGatewayIP/ddd4a2c7b3721/root --exec-root /tmp/dxr/ddd4a2c7b3721 --pidfile /go/src/github.com/docker/docker/bundles/test-integration/TestDaemonHostGatewayIP/ddd4a2c7b3721/docker.pid --userland-proxy=true --containerd-namespace ddd4a2c7b3721 --containerd-plugins-namespace ddd4a2c7b3721p --containerd /var/run/docker/containerd/containerd.sock --host unix:///tmp/docker-integration/ddd4a2c7b3721.sock --debug --storage-driver overlay2 --host-gateway-ip=6.7.8.9] : [ddd4a2c7b3721] daemon exited during startup: exit status 1
```

kicking CI again

**Comment by thaJeztah** [comment]
Lots of whitespace changes, so diff is best viewed with `?w=1`; https://github.com/moby/moby/pull/42005/files?w=1

**Comment by thaJeztah** [comment]
Failures:

`TestRunPIDsLimit`: tracked through https://github.com/moby/moby/issues/42416

```
=== RUN   TestDockerSuite/TestRunPIDsLimit
    --- FAIL: TestDockerSuite/TestRunPIDsLimit (0.93s)
        docker_cli_run_unix_test.go:1395: assertion failed:
            Command:  /usr/local/cli/docker run --name skittles --pids-limit 4 busybox cat /sys/fs/cgroup/pids/pids.max
            ExitCode: 125
            Error:    exit status 125
            Stdout:
            Stderr:   runtime/cgo: pthread_create failed: Resource temporarily unavailable
            SIGABRT: abort
            PC=0x91ce6b m=2 sigcode=18446744073709551610
```

Failures on arm64:

`TestConcurrencyNoWait` tracked through https://github.com/moby/moby/issues/42458

```
=== RUN   TestConcurrencyNoWait
--- FAIL: TestConcurrencyNoWait (0.12s)
    iptables_test.go:217:  (iptables failed: iptables -t nat -A DOCKEREST -p tcp -d 192.168.1.1 --dport 1234 -j DNAT --to-destination 172.17.0.1:4321 ! -i lo: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
         (exit status 4))
```

`TestExistsRaw` : https://github.com/moby/moby/issues/42469

```
=== RUN   TestExistsRaw
--- FAIL: TestExistsRaw (0.03s)
    iptables_test.go:288: Failed to detect rule. i=0
```

**Comment by thaJeztah** [comment]
Aaaand... another flaky libnetwork test on Windows RS5 https://ci-next.docker.com/public/job/moby/job/PR-42005/6/execution/node/270/log/?consoleFull

Opened https://github.com/moby/moby/issues/42484

```
=== RUN   TestNetworkDBCRUDMediumCluster
2021/06/07 07:36:57 Closing DB instances...
time="2021-06-07T07:36:57Z" level=error msg="node: c784143724ad is unknown to memberlist"
time="2021-06-07T07:36:58Z" level=error msg="node: c0a70b8886f7 is unknown to memberlist"
--- FAIL: TestNetworkDBCRUDMediumCluster (9.68s)
    networkdb_test.go:117: Network existence verification failed
```

**Comment by thaJeztah** [comment]
@justincormack @tonistiigi @AkihiroSuda ptal

**Review by tonistiigi — APPROVED** [review]

**Comment by thaJeztah** [comment]
@AkihiroSuda @tianon PTAL 🤗 (justin told me he currently doesn't have time to review)

**Review by tianon — APPROVED** [review]
> Lots of whitespace changes, so diff is best viewed with `?w=1`; https://github.com/moby/moby/pull/42005/files?w=1

I am Very Smart, so I rediscovered this the hard way :+1:

**Comment by thaJeztah** [comment]
> I am Very Smart, so I rediscovered this the hard way 👍

Aw, man, sorry! I should've mentioned it in the top comment instead 😞 


2 LGTM's now, so let me bring this one in.


I'll have a look at the follow-up as well; see https://github.com/moby/moby/pull/42005#issuecomment-782264599

> Nice! [opencontainers/runtime-spec#1087](https://github.com/opencontainers/runtime-spec/pull/1087) was just opened, and has a change I was also considering for a follow-up; with that, it's possible to create a profile that uses `ENOSYS` as a default (which could be our default profile, or could be used by a user in a custom profile)

With that change we will have the _option_ (at least) to switch the profile to use `ENOSYS` (or allow users to modify the default profile to use that); see https://github.com/opencontainers/runc/issues/2151

**Pull request merged**
