### PR TITLE
Make docker stack deploy a little bit more indempotent

### PR DESCRIPTION
**Pull request by vdemeester**
Version of #29732 for master.

---

Make sure running multiple times `docker stack deploy --compose-file docker-compose.yml foo` on the same unchanged file doesn't update the services each times. This is mainly due to the use of `map` .

This is related to #29676

This is sorting `environment`, `extraHost` and `port` too. <del>There is some weirdiness with ports but a PR might follow for that.</del> You can reproduce and validate this using the following compose file.

```yaml
version: "3.0"

services:
  test:
    image: busybox
    command: top
    extra_hosts:
      - foo:1.1.1.1
      - bar:2.2.2.2
    environment:
      - FOO=BAR
      - FAR=BOO
    ports:
      - "5000:80"
      - "5001:81"
    networks: [front-tier, back-tier]

networks:
  front-tier:
  back-tier:
```

This also helps with `Error response from daemon: rpc error: code = 2 desc = changing network in service is not supported` when you didn't change the networks.

/cc @thaJeztah @dnephin @icecrime @cpuguy83 @aaronlehmann @aanand 

If it gets in, I'll do a PR against master.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by LK4D4 — APPROVED** [review]
LGTM

**Comment by LK4D4** [comment]
ping @docker/core-engine-maintainers

**Comment by estesp** [comment]
LGTM

**Review by estesp — APPROVED** [review]

**Comment by drsolaris** [comment]
I'm seeing the same problem caused by secrets not being sorted. From nosing at the code, I don't think that was fixed in here, though it looks like secrets are handled slightly differently, so please let me know if I'm wrong. I'll happily open a separate ticket for secrets if that's the best way forward.

**Comment by thaJeztah** [comment]
@drsolaris thanks for reporting; can you open a new issue for that for tracking? (you can include a link to this issue in the description)

**Pull request merged**
