### PR TITLE
[17.03] Fix log readers can block writes indefinitely

### PR DESCRIPTION
**Pull request by cpuguy83**
In case we want to pull this into 17.03-ce

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @andrewhsu

**Comment by thaJeztah** [comment]
Build is failing @cpuguy83 

```
21:58:59 # github.com/docker/docker/daemon/logger/jsonfilelog
21:58:59 daemon/logger/jsonfilelog/jsonfilelog.go:101: undefined: logger.PutMessage
21:58:59 daemon/logger/jsonfilelog/jsonfilelog.go:104: undefined: logger.PutMessage
21:58:59 daemon/logger/jsonfilelog/read.go:114: no new variables on left side of :=
21:59:29 Build step 'Execute shell' marked build as failure
```

**Comment by cpuguy83** [comment]
Fixed

**Comment by thaJeztah** [comment]
for reference; PR for master is https://github.com/moby/moby/pull/33897

**Comment by vieux** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by andrewhsu** [comment]
LGTM

desirable

**Pull request merged**
