### PR TITLE
Add bash completion for `update --cpus`

### PR DESCRIPTION
**Pull request by albers**
Bash completion for #31148.
Ping @sdurrheimer for zsh completion

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM when #31148 gets merged

**Comment by thaJeztah** [comment]
@yongtang perhaps you can pull @albers commit into your pull request?

**Comment by albers** [comment]
Temporarily closed until #31148 gets merged.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by yongtang** [comment]
Thanks @albers!

**Pull request merged**
