### PR TITLE
update changelog 1.13.0-rc4

### PR DESCRIPTION
**Pull request by vieux**
ping @jhowardmsft @thaJeztah @aluzzardi

### CODE REVIEW

**Review by lowenna — COMMENTED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
CI failure is unrelated

(cc @tiborvass @anusha-ragunathan )
```
00:37:51.139 ----------------------------------------------------------------------
00:37:51.139 FAIL: docker_cli_events_test.go:278: DockerSuite.TestEventsPluginOps
00:37:51.140 
00:37:51.140 docker_cli_events_test.go:283:
00:37:51.140     dockerCmd(c, "plugin", "install", pNameWithTag, "--grant-all-permissions")
00:37:51.140 docker_utils.go:505:
00:37:51.141     c.Assert(result, icmd.Matches, icmd.Success)
00:37:51.141 ... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc42390c000), ExitCode:1, Error:(*exec.ExitError)(0xc420987880), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc4200785a0), errBuffer:(*cmd.lockedBuffer)(0xc420078630)} ("\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-rc3/binary-client/docker plugin install tiborvass/no-remove:latest --grant-all-permissions\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: content is not a plugin\n\n")
00:37:51.144 ... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
00:37:51.145 ... 
00:37:51.145 Command: /go/src/github.com/docker/docker/bundles/1.13.0-rc3/binary-client/docker plugin install tiborvass/no-remove:latest --grant-all-permissions
00:37:51.146 ExitCode: 1, Error: exit status 1
00:37:51.146 Stdout: 
00:37:51.146 Stderr: Error response from daemon: content is not a plugin
00:37:51.147 
00:37:51.147 
00:37:51.147 Failures:
00:37:51.147 ExitCode was 1 expected 0
00:37:51.147 Expected no error
00:37:51.147 
00:37:51.147 
00:37:51.684 
00:37:51.685 ----------------------------------------------------------------------
```

**Comment by vieux** [comment]
@AkihiroSuda it's expected, the errors are fixed in https://github.com/docker/docker/pull/29229

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
