### PR TITLE
swagger.yaml: Remove extra 'the' wrapped by newline

### PR DESCRIPTION
**Pull request by FreddieOliveira**
Just a typo fix. This PR was originally proposed by @phillc here: https://github.com/docker/engine/pull/456

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
LGTM

**Comment by tianon** [comment]
CI failure seems related, but I'm not sure how/why?

```diff
+ docker run --rm -t --privileged -v /home/ubuntu/workspace/moby_PR-41924/bundles:/go/src/github.com/docker/docker/bundles -v /home/ubuntu/workspace/moby_PR-41924/.git:/go/src/github.com/docker/docker/.git --name docker-pr3 -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT=2db5676c6e827ce311a87224cf5f2e3ae8b68afd -e DOCKER_GRAPHDRIVER -e TEST_FORCE_VALIDATE -e VALIDATE_REPO=https://github.com/moby/moby.git -e VALIDATE_BRANCH=master docker:2db5676c6e827ce311a87224cf5f2e3ae8b68afd hack/validate/default
Congratulations!  All commits are properly signed with the DCO!
Congratulations!  Packages in "./pkg/..." are safely isolated from internal code.
Congratulations!  The swagger spec at "api/swagger.yaml" is valid against swagger specification 2.0
The result of hack/generate-swagger-api.sh differs

diff --git a/api/types/container/container_wait.go b/api/types/container/container_wait.go
index 49e05ae669..c2e69b5b25 100644
--- a/api/types/container/container_wait.go
+++ b/api/types/container/container_wait.go
@@ -6,14 +6,6 @@ package container // import "github.com/docker/docker/api/types/container"
 // See hack/generate-swagger-api.sh
 // ----------------------------------------------------------------------------
 
-// ContainerWaitOKBodyError container waiting error, if any
-// swagger:model ContainerWaitOKBodyError
-type ContainerWaitOKBodyError struct {
-
-	// Details of an error
-	Message string `json:"Message,omitempty"`
-}
-
 // ContainerWaitOKBody OK response to ContainerWait operation
 // swagger:model ContainerWaitOKBody
 type ContainerWaitOKBody struct {
@@ -26,3 +18,11 @@ type ContainerWaitOKBody struct {
 	// Required: true
 	StatusCode int64 `json:"StatusCode"`
 }
+
+// ContainerWaitOKBodyError container waiting error, if any
+// swagger:model ContainerWaitOKBodyError
+type ContainerWaitOKBodyError struct {
+
+	// Details of an error
+	Message string `json:"Message,omitempty"`
+}

Please update api/swagger.yaml with any API changes, then 
run hack/generate-swagger-api.sh.
script returned exit code 1
```

**Comment by thaJeztah** [comment]
> CI failure seems related, but I'm not sure how/why?

Yeah, `go-swagger` uses a `map[string]` internally, and maps are randomised by Golang when iterating over them (by design: )

Unfortunately, we can't update to a more recent version of go-swagger, as it removes some functionality we need (there's a (now bit-rotten) PR to replace it with something else; https://github.com/moby/moby/pull/36714

**Comment by thaJeztah** [comment]
Kicked CI again (just to be sure), will merge once it passes

**Pull request merged**
