### PR TITLE
Reimplement integration test for symlink Dockerfile as a unit test

### PR DESCRIPTION
**Pull request by tkopczynski**
Test for symlink Dockerfile as a unit test with some refactoring.

Part of resolving #20784

Signed-off-by: Tomasz Kopczynski tomek@kopczynski.net.pl

### CODE REVIEW

**Comment by LK4D4** [comment]
@tkopczynski failure on tp5 :/

**Comment by LK4D4** [comment]
LGTM

**Comment by tkopczynski** [comment]
I didn't leave a comment because I wanted to check CI over the night (Europe timezone) but it seems to be ok now
thanks @LK4D4

**Comment by vdemeester** [comment]
experimental timed out after tests (which is weird but not related..)
LGTM 🐯

**Pull request merged**
