### PR TITLE
Remove docs for cfengine

### LINKED ISSUE #11560: Test the "Process Management with CFEngine" article
Test the article and ensure the process works as documented. File any issues a `writing` issues.

https://docs.docker.com/engine/articles/cfengine_process_management/

### LINKED ISSUE #11703: Update "Process Management with CFEngine"  Article to run Under Docker 1.50
Dockerfile appears broken and outdated. Running "wget -qO- http://cfengine.com/pub/gpg.key | apt-key add - " returns a 403. 

https://github.com/docker/docker/blob/b64558907139911b86d846de70ab859504cc45a2/docs/sources/articles/cfengine_process_management.md

Link to article with error: https://docs.docker.com/engine/articles/cfengine_process_management/

### PR DESCRIPTION
**Pull request by senk**
Removed cfengine docs page for several reasons:
Doc is outdated
Included Dockerfile is not working, referenced repo estenberg/cfe-docker seems inactive
Dockerfile violates best practices
Running multiple processes inside one container is against best practices.
Issues #11703 and #11560 seem inactive.

So my suggestion is to remove the docs page for cfengine

closes #11703 closes #11560
Signed-off-by: Robin Naundorf r.naundorf@fh-muenster.de

### CODE REVIEW

**Comment by senk** [comment]
ping @thaJeztah @moxiegirl

**Comment by thaJeztah** [comment]
Well, we have examples for running, e.g. supervisord in a container (to control multiple processes), but I agree that this doc is very outdated (it didn't change much since it was added in https://github.com/docker/docker/pull/2853), and I don't see many people using CFEngine for this purpose

LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by moxiegirl** [comment]
@joaofernandez you might want to pick this up in your cfengine docs

**Pull request merged**
