### PR TITLE
Carry 13934: Add `docker daemon` to bash completion

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Harald Albers github@albersweb.de
Signed-off-by: Tibor Vass tibor@docker.com

Closes #13934 

Ping @tianon I have no idea if this is good or lacking.

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
cherry picked into #15091

**Comment by albers** [comment]
Back from holiday, so here is my review:

There is a group of options that is both contained in the output of `docker --help` and `docker daemon help`:

    -D, --debug=false                    Enable debug mode
    -H, --host=[]                        Daemon socket(s) to connect to
    -l, --log-level=info                 Set the logging level
    --tls=false                          Use TLS; implied by --tlsverify
    --tlscacert=~/.docker/ca.pem         Trust certs signed only by this CA
    --tlscert=~/.docker/cert.pem         Path to TLS certificate file
    --tlskey=~/.docker/key.pem           Path to TLS key file
    --tlsverify=false                    Use TLS and verify the remote

**Are these options really supported in both positions**? That means they could be legally specified twice, e.g.

    docker -l info daemon -l debug

Completion only supports these options for `docker`, not `docker daemon`.
If the options are legal in both positions, I will add them.

cc @thaJeztah

**Comment by tiborvass** [comment]
@albers they are not legal, it will error out.

**Comment by tiborvass** [comment]
@albers as in, `docker --tls run ...` is legal, `docker daemon --tls` is legal, but `docker --tls daemon --tls` is not. I just don't know how to describe that.

**Comment by albers** [comment]
@tiborvass I see. So the new syntax would be `docker daemon --tls` and `docker --tls` is just for compatibility. As far as there is no conflict, the latter syntax works.

**Comment by tiborvass** [comment]
@albers Well, `docker --tls` is not for backwards compat (we don't want backwards compat in a bash completion script), it's for docker client commands (all except `daemon`).

**Comment by albers** [comment]
@tiborvass I thing I got it: The above mentioned options are valid for all _client commands_ as _global options_, i.e. they must be given right behind `docker`, e.g. `docker --log-level debug run`.

For `docker daemon`, these options are _command options_, i.e. they have to follow the command, e.g. `docker daemon --log-level debug`. For this one command, the _global_ syntax is invalid and errors out. Example: `docker --log-level debug daemon` is invalid.

**Comment by tiborvass** [comment]
@albers correct

**Comment by albers** [comment]
@tiborvass Thanks for your patience. I'm a bit in a hurry to finish up the completion.

So I will add support for the _global options_ to `docker daemon` as _command options_ as they are currently missing there.

**Comment by tiborvass** [comment]
@albers okay sorry about that, I'm really not good at these completion scripts. Thanks for your help!

**Comment by albers** [comment]
@tiborvass Well, I'm sorry that completion bounced back to you because I was on holiday. Thanks for taking care of it!

**Comment by albers** [comment]
@tiborvass By the way, I found that `docker --log-level debug daemon` errors out with

    invalid flag '-l'.

Is this framework related or can this be fixed?

**Comment by thaJeztah** [comment]
> I'm sorry that completion bounced back to you because I was on holiday. Thanks for taking care of it!

@albers please *don't* feel sorry. We were aware you didn't have time, and you're always helping out in fantastic ways. There's more in life than Docker and you deserve your Holidays, no stress (really!) :heart:

**Pull request merged**
