### PR TITLE
Fix TestRunCreateVolumesInSymlinkDir

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

@cpuguy83 @calavera @mikedougherty 

This test is wrong :) Looks like it might have been modified in the past, but modified incorrectly. It used to create a directory on the host, then a file in it, then all it does is create the same directory name in the container, and ignores the file created on the host. In fact, it ignores the directory on the host too. So why even create it? Instead, just used a hard-coded directory inside the container (based on the test name) to use as the base of the symbolic link to (c:)\test, which is what is really being tested here.

This is a problem on Windows CI, or at least will be as soon as we switch to a fast SSD on the D: drive, as the D: drive doesn't exist inside the container. Hence needs to be merged before I can switch the CI servers to dramatically improve the performance of the windowsTP4 runs.

### CODE REVIEW

**Comment by mikedougherty** [comment]
:+1:

**Comment by thaJeztah** [comment]
Previous changes look to be made in https://github.com/Microsoft/docker/commit/63708dca8a633d68f9342eebd4f7a616e8c48234

**Comment by jhowardmsft** [comment]
Way before that change ;)

**Comment by cpuguy83** [comment]
Ok, this check is for an old bug where if there existed a path on the host that was the same path as a volume path (e.g. `/test` on the host and `/test` in a container), and the container path was a symlink it was causing issues.

**Comment by jhowardmsft** [comment]
@cpuguy83 So would you rather me put it back to how it was, and just don't run it on Windows to Windows CI? I think the updated version of the test still has merit as a test in its own right though.

**Comment by cpuguy83** [comment]
We should not change the purpose of the test, which is to ensure there's no issues as described above.

**Comment by jhowardmsft** [comment]
@cpuguy83 OK, put test back in with a safety check to skip when running on Windows if the TEMP directory is not on the C: drive. And what was the modification is added as a new test. PTAL

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
