### PR TITLE
Add support for --cgroup:container:<id>

### PR DESCRIPTION
**Pull request by mrunalp**
Implements #18654 

I am working on creating PRs for runc but have all the code in here right now to make it easier to test.

### CODE REVIEW

**Comment by jfrazelle** [comment]
ooo cool feature :)

**Comment by mrunalp** [comment]
@jfrazelle Thanks for the +1 :) I am working on rebasing this and the simple runc PR.

**Comment by icecrime** [comment]
Ping @mrunalp! Should we close for now?

**Comment by mrunalp** [comment]
@icecrime I am waiting for a libcontaner bump. I will rebase the other changes and keep them ready.

**Comment by thaJeztah** [comment]
ping @mrunalp https://github.com/docker/docker/pull/20187 was just merged and bumps runc

**Comment by icecrime** [comment]
Ping @mrunalp! Thanks :-)

**Comment by mrunalp** [comment]
I will update the PR this week.

**Comment by thaJeztah** [comment]
Thanks @mrunalp!

**Comment by mrunalp** [comment]
I have created docker-engine PR that is required for this https://github.com/docker/engine-api/pull/119

**Comment by calavera** [comment]
I think we should NOT move this forward until after 1.11. That would mean that it needs to be handled when containerd integration is ready. Should we close it, since it will require to be rewritten? @tonistiigi ?

**Comment by thaJeztah** [comment]
ping @mrunalp containerd is now integrated; were you planning on updating this PR, or do you want me to close this one and you opening a new one?

**Comment by mrunalp** [comment]
I can open a new PR. Thanks!

**Comment by thaJeztah** [comment]
thanks, let me close this one then

**Pull request closed without merging**
