### PR TITLE
Refactor setting graph driver name

### PR DESCRIPTION
**Pull request by nakabonne**
Signed-off-by: Ryo Nakao <nakabonne@gmail.com>

**- What I did**

This is a small fix to merge parts that looped too much, I think no problem even if setting of layer store and resetting of graph driver are included in the same loop.

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by nakabonne** [comment]
@AkihiroSuda Thanks.
Should I deal with something to pass the codecov check?

**Comment by AkihiroSuda** [comment]
No, we don't need to add a new test for a small fix like this.

**Comment by nakabonne** [comment]
Thanks for letting me know.

**Comment by cpuguy83** [comment]
I think this is used for LCOW+WCOW?
If so maybe a comment would help.

ping @jhowardmsft

**Comment by jhowardmsft** [comment]
Yeah, this is indeed in the case of LCOW+WCOW. I believe it's safe though, but haven't verified

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Thanks for contributing!

**Pull request merged**
