### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by veggiemonk**
Add Awesome-docker list to docker resources. https://github.com/veggiemonk/awesome-docker

Signed-off-by: Julien Bisconti julien.bisconti@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks for suggesting this!

@moxiegirl wdyt? I like that listing, but don't know if there are "competing" lists that also want to be added here when this is added

**Comment by moxiegirl** [comment]
@veggiemonk Good idea!  @thaJeztah I think it would be great to have a our own database that people can add to and vote up of these things.  (Another thing on my long  "when I have time"  lists.)  Seeing as how that ambition is currently thwarted, let's do this. If it gets out of hand or something we can back it down.

Tho feel free to ping maintainers of course TMMV.

**Comment by veggiemonk** [comment]
Hi everybody,

It would be amazing to have a place to post docker related projects. That's
the only reason I made this pr. Since that's what people are already doing
qith this listing anyway. Maybe you could fork this list into docker
organization. I could manage it for you if you want. It would be nice. What
do you think?

---
Julien Bisconti

**Comment by moxiegirl** [comment]
LGTM to add this in the mean time.  @veggiemonk We can review additions changes to this area as they occur

**Comment by thaJeztah** [comment]
Sorry for the late response, I meant to write a response yesterday at work, but we had some major issues on a project :blush:

I think linking is good; I checked your project and it already has quite a number of stars (I'm not sure those are preserved if the project is moved?)

Also, if other similar lists want a mention, we would still be able to do so, probably changing the header of this section.

So, LGTM. Thanks for contributing and for maintaining this list, it's a really nice resource!

**Pull request merged**
