### PR TITLE
Update to hide the 1.10 material

### PR DESCRIPTION
**Pull request by moxiegirl**
@thaJeztah 
Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
This change is to temporarily hide the 1.10 / v1.22 API docs, so that https://github.com/docker/docker/pull/17583 can be cherry picked into the release branch, without making it show up API docs for 1.10

**Comment by thaJeztah** [comment]
LGTM

**Comment by tiborvass** [comment]
I didn't need this commit, since I had to resolve conflicts manually and had already removed `1.10`

**Comment by thaJeztah** [comment]
@tiborvass cool! I wanted to prevent accidental slip ups, hence this PR.

Will create a revert PR, so that master includes 1.10 again

**Pull request merged**
