### PR TITLE
zsh: enable option stacking

### PR DESCRIPTION
**Pull request by vincentbernat**
The first commit is about enabling short options with arguments to specify their arguments with `=` instead of just space. This is also a prerequisite for the second commit.

The second commit is about stacking short options: `docker run -it ubuntu bash` now works correctly. There is a minor drawback is that Zsh will allow completion of arguments for short options without a space nor an equal: `docker run -uapp<tab>` will complete to `-uapprox`. Therefore, I keep this commit separate in case it needs to be discarded/reverted but I think that its usefulness outweights this flaw.

I have asked for guidance on Zsh mailing list but got no answer yet.

I am adding `-s` even when there is no short option or only one for consistency. When a short option is added to an existing command, the `-s` is already here.

cc @sdurrheimer

### CODE REVIEW

**Comment by sdurrheimer** [comment]
:+1: for short option with `=`

:-1: for the stacking. Not that I'm not interested in stacking short options, but the drawback about the argument in the same word is annoying. I have tried to do it too, but encountered the same issue.

**Comment by vincentbernat** [comment]
I modified the last commit to make option stacking optional. It is still enabled by default as I believe this is an improvement. This is just a matter of changing `-T` to `-t` to change that and I am fine to change that if most people think this is better.

To give an example, currently, `docker run -it ubu<tab>` doesn't complete as expected (image name). With this commit, it does but `docker run -u<tab>` will complete with user names instead of `=` or space.

**Comment by jfrazelle** [comment]
ping @sdurrheimer

**Comment by vincentbernat** [comment]
It's more a mini poll. For example, @jfrazelle, if you use Zsh, what would you prefer?

**Comment by jfrazelle** [comment]
I don't sorrry but i think @bfirsh does

**Comment by sdurrheimer** [comment]
Same for @calavera if I'm not mistaken.

**Comment by vincentbernat** [comment]
So, without any further input, I amended the last commit to disable the stacking behavior by default. People can still enable it if they want it.

**Comment by sdurrheimer** [comment]
Ok LGTM

**Comment by cpuguy83** [comment]
Needs a rebase

**Comment by vincentbernat** [comment]
Rebased.

**Comment by calavera** [comment]
LGTM but needs another rebase :crying_cat_face: :sob:

**Comment by vincentbernat** [comment]
Rebased.

**Comment by thaJeztah** [comment]
Merging, taking @sdurrheimer's review as the second LGTM (thanks for reviewing!) I don't think this needs squashing, so all good thanks @vincentbernat !

**Comment by ratijas** [comment]
I've discovered this PR from links on related thread, and I should say it is very confusing. The title spells "enable option stacking", but in the end they were [not enabled](https://github.com/moby/moby/pull/17124#issuecomment-150518700). As far as I can tell, this PR enhances some short options with arguments, but doesn't enable stacking.

**Pull request merged**
