### PR TITLE
Update Derek behaviour

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

**- What I did**

Update Derek behaviour

**- How I did it**

Adds new opt-in feature "pr_description_required" see docs for more:
https://github.com/alexellis/derek/blob/master/USER_GUIDE.md

**- How to verify it**

Once merged, raise a PR with a completely blank description and Derek will inform the user
of this being a requirement and add a label to the issue.

**- Description for the changelog**

Enable Derek (automation) PR linting feature

**- A picture of a cute animal (not mandatory but encouraged)**

FYI this version of Derek also enables the short command:

```
Derek add label: janky/rebuild

# also available as:

/add label: janky/rebuild
```

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
SGTM let's see how it works 👍

**Comment by alexellis** [comment]
cc @rgee0

**Comment by alexellis** [comment]
Derek add label: rebuild/experimental

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
Thank you 👍

**Comment by alexellis** [comment]
Derek add label: area/project

**Comment by alexellis** [comment]
Derek add label: area/project

**Pull request merged**
