### PR TITLE
[WIP] Service Security Config

### PR DESCRIPTION
**Pull request by ehazlett**
Continuing on https://github.com/docker/docker/issues/25303 this attempts to group some of the flags (in this case security related) into a more portable format to be used with Services.

This takes the security options from `docker run` and places them in a "Security Config" for the service.  This is then used when running a container to apply the configuration.  An example are the flags `--userns` and `--credentialspec`.  These options get passed when creating a service:

`$> docker service create --name test -t --security userns=host --security credentialspec=foo alpine ash`

(forgive my ignorance I'm not exactly sure what credentialspec should be).

This is then stored as part of the Service spec:

```
$> docker service inspect test
...
"ContainerSpec": {
                    "Image": "alpine:latest@sha256:dfbd4a3a8ebca874ebd2474f044a0b33600d4523d03b0df76e5c5986cb02d7e8",
                    "Args": [
                        "ash"
                    ],
                    "TTY": true,
                    "DNSConfig": {},
                    "SecurityConfig": {
                        "Userns": "host",
                        "CredentialSpec": "foo"
                    }
                },
...
```
If the platform is supported, the option is applied.  Here is an example of setting `--userns=host`:

```
$> docker inspect d0
...
            "UTSMode": "",
            "UsernsMode": "host",
            "ShmSize": 67108864,
...
```

This is just a start and is a request for comments.  If agreed upon, I would like to move some other options into this as well:
- `--capabilities` (replacing `--cap-add` and `--cap-drop`)
- `--cgroup-parent` ?
- `--security-opt` (we might want to rename this)

Questions:

- Should the above be in the "Security Config"?
- Is anything missing that should be included?

Swarmkit PR: https://github.com/docker/swarmkit/pull/1944

### CODE REVIEW

**Comment by mostolog** [comment]
does ulimit fit under --security-opt?

**Comment by justincormack** [comment]
I think it is maybe best to try to structure the config around how it is in the OCI spec, not in groupings like "security" , even though it does not always have things in the most logical structure (can still be fixed!). It comes with data types for everything too. Otherwise it will be painful to switch from the Docker API to the Containerd API. Also one day I would love for `docker inspect` to just show me the OCI config for my containers...

There is a further can of worms around this - as swarmkit currently uses docker to run the containers and docker does not have a generic interface for some options, it has a more usable one, some options just won't do the right thing.

For example the `--pid=...` option for setting `pid` namespace. The OCI interface takes a filesystem path to the namespace to use, which is fully general. `--pid=host` means use `/proc/1/ns/pid` as the path, but `--pid=container:name` looks up the container name, finds its pid and uses that path.  But local container names don't mean anything for swarmkit. You can just not implement all this functionality for now, but it should be on the roadmap - this for example is part of the implementation needed for pod-like setups. Other similar things would be having per service per host resource limits, where swarmkit would need to start managing cgroups.

I would take a serious look at refactoring around the OCI structures (cc @ijc25) and then cherry picking a few of the fields to add that don't have issues - capabilities would be good for example, but `--pid=host` and the other unconfinement options are huge security holes. The Windows options would not be available of course, until Windows moves to OCI, although perhaps there is a draft OCI Windows spec you could base something off?

**Comment by aluzzardi** [comment]
@stevvooe ^^

We had that same conversation a long time ago. Everything about OCI is non-portable across machines AFAIK, therefore is too low level for orchestration

**Comment by diogomonica** [comment]
I really don't think this is the right path forward.

I think that before we allow `docker service` to have any of these abilities, we need to group the low level permissions into bundles, like we've talked about in the past.

Then we could have a `grant` mechanism that allows the service creation to tell swarm what the service needs.

```bash
$> docker service create --name test -t alpine ash
This service requires the following permissions:
- network-listen
- bind-mount /etc/hostname
Accept these permissions? (y/n):
```

or the one-liner equivalent 
`$> docker service create --name test -t --grant network-listen --grant bind-mount:/etc/hostname alpine ash`

Overall no user should ever see capabilities/other low level implementation details.

**Comment by cyli** [comment]
@diogomonica Just checking, by:

> Overall no user should ever see capabilities/other low level implementation details.

You mean in the CLI, correct?  Possibly someone could use them if making the raw API request if they wanted to do something specific?

**Comment by diogomonica** [comment]
@cyli correct. Just making sure everyone is clear on that. We should have the ability of sending to the API arch-specific security properties, but not expose them as `--capabilities` or `--cap-add` or what-have-you on the cli.

Also: privileged is as of now deprecated and shouldn't make it to the API *at all*.

**Comment by ehazlett** [comment]
Closing in favor of "security profiles".  Will work with security team to get that moving.

**Comment by aluzzardi** [comment]
Folks, we really do need to make progress on converging this.

I do understand the push backs but I don't see a reasonable path forward being proposed either or efforts being invested to fix this.

This is a pretty high priority since it's a convergence blocker.

/cc @diogomonica @cyli @justincormack

**Pull request closed without merging**
