### PR TITLE
remove oracle linux 6 for time being

### PR DESCRIPTION
**Pull request by jessfraz**
see https://github.com/docker/docker/issues/18688#issuecomment-164917055

ping @Djelibeybi @tianon

### CODE REVIEW

**Comment by tianon** [comment]
LGTM until/if we can find a fix

**Comment by Djelibeybi** [comment]
:+1: this is OK with me. We're working on UEK4 and have an internal bug open to update the headers so that Docker 1.10+ builds successfully on OL6.

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @Djelibeybi!

**Pull request merged**
