### PR TITLE
fix version struct on old versions

### LINKED ISSUE #13730: 1.7: /version is not map[string]string anymore
For 1.6 and earlier /version would return `map[string]string`.  In 1.7 it now has a `experimental` flag in it which is a boolean.  So the type now is essentially `map[string]interface{}`.  I don't know if this is considered a bug but basically github.com/fsouza/go-dockerclient fails to work now because of this.

### PR DESCRIPTION
**Pull request by jessfraz**
closes #13730

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @ibuildthecloud

**Comment by icecrime** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by ibuildthecloud** [comment]
Thanks

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
