### PR TITLE
Nat was moved to pkg/nat

### PR DESCRIPTION
**Pull request by cpuguy83**
Somehow this import was missed

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @calavera @LK4D4

**Comment by calavera** [comment]
LGTM.

**Comment by LK4D4** [comment]
LGTM

**Comment by pwaller** [comment]
To answer the "somehow", it's because the import was added after the rename was created, and then the rename branch was merged shortly after the commit introducing the import was merged. An amusing case that traditional CI struggles to catch!

https://github.com/docker/docker/pull/14231 (Made on the 28th, merged 19:54)
https://github.com/docker/docker/pull/14297 (Made 19:27, merged 20:22).

**Pull request merged**
