### PR TITLE
Proposing Chandrasekhar, Khorana, Saha for name-generator

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by vbatts** [comment]
@LalatenduMohanty cool. Can you `gofmt -s -w .` please?

**Comment by LalatenduMohanty** [comment]
@vbatts , fixed. Sorry for the typo.

**Comment by vbatts** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
