### PR TITLE
FAQ: add docker daemon unavailable note

### LINKED ISSUE #18884: UX: Attempt to start boot2docker automatically
```bash
❯ docker pull gliderlabs/alpine
Using default tag: latest
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

It would be nice to 
- have the docker cli check for the existence of  `boot2docker`, 
    - **true**: attempt to run `boot2docker up` automatically 
    - **false**: a link to this error in a Docker FAQ (can't seem to find one [here](https://docs.docker.com/engine/misc/faq/), surprisingly)

### PR DESCRIPTION
**Pull request by tkopczynski**
Adding a note about the error:
_Cannot connect to the Docker daemon. Is the docker daemon running on this host?_

Fixes #18884 

Signed-off-by: Tomasz Kopczynski tomek@kopczynski.net.pl

### CODE REVIEW

**Comment by MHBauer** [comment]
in the case of docker-machine, it could also be that you haven't run the eval of the environment variables. Looks like `eval "$(docker-machine env dev)"`, and it does show up on the linked page. 

I'm not sure we should be advocating changes how the system starts up.

The second paragraph is kind of weird to me. I'm not sure this is the place for such a warning.

**Comment by thaJeztah** [comment]
Agreed with @MHBauer; not having the env-vars setup is a frequent issue.

The second paragraph is not needed, so I suggest to remove it, also, since boot2docker-cli is deprecated, not sure we should mention it separately

**Comment by vdemeester** [comment]
Agreed with @MHBauer and @thaJeztah too. A proposition

```markdown
This error points out that the docker client cannot connect to the virtual machine. 
This means that either the virtual machine that works underneath `docker-machine` 
is not running or that the client doesn't correctly point at it.

To verify that the docker machine is running you can use the `ls` command and start it with `start` if needed.

    $ docker-machine ls
    NAME          ACTIVE   URL          STATE     URL   SWARM   DOCKER    ERRORS
    default       -        virtualbox   Stopped                 Unknown  

    $ docker-machine start default

We have to tell Docker to talk to that machine. You can do this with the `docker-machine env` command. For example,

    $ eval "$(docker-machine env default)"
    $ docker ps

```

**Comment by tkopczynski** [comment]
I've changed the pull request in line with @vdemeester proposition since it addressed all issues mentioned in the discussion and I don't see any clearer way of describing the problem.

**Comment by vdemeester** [comment]
LGTM 🐙

**Comment by thaJeztah** [comment]
LGTM, thanks @tkopczynski!

**Comment by MHBauer** [comment]
I like it. LGTM.

**Comment by thaJeztah** [comment]
Adding "cherry pick" so that we can include it in the next docs release

**Pull request merged**
