### PR TITLE
Bump notary version up to 0.3.0 and re-vendor.

### PR DESCRIPTION
**Pull request by cyli**
This updates the vendored notary version from v0.3.0-RC1 to v0.3.0.  The changes between the two versions involve:
- code cleanup and refactoring
- obsoleting the `trusted_certificates` directory in `"~/.docker/trust"` - we just look at the previously downloaded root now, if we're doing TOFU
- fixing a bug where docker 1.10 can't read newer repository formats (which never made it into any released docker version)

caracal

### CODE REVIEW

**Comment by thaJeztah** [comment]
> obsoleting the trusted_certificates directory in "~/.docker/trust" - we just look at the previously downloaded root now, if we're doing TOFU

Was this ever documented? I.e., does it need to be mentioned in the "deprecated features" or changelog?

LGTM otherwise

**Comment by cyli** [comment]
Hi Sven!  The trust certificates were an implementation detail of doing TOFU.  I can't seem to find it anywhere in the content trust docs, except maybe here:  https://github.com/docker/docker/blob/master/docs/security/trust/trust_key_mng.md#lost-keys where the words "trusted certificates" is used as part of the error message (I think the error message has changed now).  I'll update that error message.

**Comment by thaJeztah** [comment]
Thanks! LGTM (if CI is green)

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
Ok, let's merge it

**Pull request merged**
