### PR TITLE
dockerd-rootless-setuptool.sh: create CLI context "rootless"

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**
dockerd-rootless-setuptool.sh: create CLI context "rootless"

**- How to verify it**

```console
$ dockerd-rootless-setuptool.sh install
...
[INFO] Creating CLI context "rootless"
Successfully created context "rootless"

[INFO] Make sure the following environment variables are set (or add them to ~/.bashrc):

export PATH=/usr/local/bin:$PATH
export DOCKER_HOST=unix:///run/user/1001/docker.sock
```

```console
$ docker context ls
NAME        DESCRIPTION                               DOCKER ENDPOINT                     KUBERNETES ENDPOINT   ORCHESTRATOR
default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                               swarm
rootless    Rootless mode                             unix:///run/user/1001/docker.sock 
```

**- Description for the changelog**

dockerd-rootless-setuptool.sh: create CLI context "rootless"

**- A picture of a cute animal (not mandatory but encouraged)**

:penguin:

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
SGTM

@tianon ptal 🤗

**Review by tianon — APPROVED** [review]
Seems fine :+1:

At some point we should probably add `local` to all these function variables (since their names are really generic and thus likely to collide), but this is consistent with the rest of the file.

**Comment by AkihiroSuda** [comment]
> add local to all these function variables

This requires bash, right?

**Comment by tianon** [comment]
Doh, right -- forgot this was POSIX, sorry.

**Pull request merged**
