### PR TITLE
api: swagger: add missing "platform" query-arg on create

### PR DESCRIPTION
**Pull request by thaJeztah**
internal ticket [ENGDOCS-874](https://docker.atlassian.net/browse/ENGDOCS-874)

Commit 7a9cb29fb980c0ab3928272cdc24c7089b2fcf64 (https://github.com/moby/moby/pull/40725) added a new "platform" query-parameter to the `POST /containers/create` endpoint, but did not update the swagger file and documentation.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @tianon @milas PTAL

Also prepared backports; https://github.com/moby/moby/pull/43889 and https://github.com/moby/moby/pull/43890

**Review by milas — APPROVED** [review]
😊

**Review by cpuguy83 — APPROVED** [review]

**Comment by thaJeztah** [comment]
Ah, dang; need to fix trailing spaces

```

[2022-07-29T20:26:39.889Z] api/swagger.yaml
[2022-07-29T20:26:39.889Z]   6217:1    error    trailing spaces  (trailing-spaces)
[2022-07-29T20:26:39.889Z]   6221:1    error    trailing spaces  (trailing-spaces)
[2022-07-29T20:26:39.889Z]   6228:1    error    trailing spaces  (trailing-spaces)
```

**Comment by thaJeztah** [comment]
^ fixed 👍

**Comment by thaJeztah** [comment]
Let me get this one in and move the backports out of draft

**Pull request merged**
