### PR TITLE
DO NOT MERGE: test libcontainer updates

### PR DESCRIPTION
**Pull request by thaJeztah**
testing changes from, https://github.com/opencontainers/runc/pull/2695, which removes various Windows stubs/placeholders

### CODE REVIEW

**Comment by kolyshkin** [comment]
```
[2020-12-03T15:44:48.298Z] Building: bundles/cross/windows/amd64/dockerd-dev.exe
[2020-12-03T15:44:48.298Z] GOOS="windows" GOARCH="amd64" GOARM=""
[2020-12-03T15:45:26.959Z] # github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/user
[2020-12-03T15:45:26.959Z] vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go:19:9: undefined: lookupUser
[2020-12-03T15:45:26.959Z] vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go:26:9: undefined: lookupUid
[2020-12-03T15:45:26.959Z] vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go:33:9: undefined: lookupGroup
[2020-12-03T15:45:26.959Z] vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go:40:9: undefined: lookupGid
[2020-12-03T15:45:41.887Z] # github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/devices
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:19:18: undefined: unix.Lstat
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:26:11: undefined: unix.Stat_t
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:36:15: undefined: unix.Major
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:37:15: undefined: unix.Minor
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:39:16: undefined: unix.S_IFMT
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:40:7: undefined: unix.S_IFBLK
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:42:7: undefined: unix.S_IFCHR
[2020-12-03T15:45:41.887Z] vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go:44:7: undefined: unix.S_IFIFO
script returned exit code 2
```

I guess the fix is to NOT import those packages in case of WIndows.

Or revert the changes I made in runc :-\

**Comment by kolyshkin** [comment]
> I guess the fix is to NOT import those packages in case of WIndows.

... which moby/moby does not do, but these two do:

vendor/github.com/containerd/containerd/oci/spec_opts.go:       "github.com/opencontainers/runc/libcontainer/user"
vendor/github.com/moby/buildkit/executor/oci/user.go:   "github.com/opencontainers/runc/libcontainer/user"

**Comment by thaJeztah** [comment]
Ha @kolyshkin 👋 yes, I thought to have a quick look what it would work like (thanks for looking)

> Or revert the changes I made in runc :-\

I think it would perhaps be good to move it to a separate PR if possible (also for visibility); _possibly_ have temporary stubs to ease the migration. Meanwhile I can look at refactoring consumers.

**Comment by thaJeztah** [comment]
replaced by https://github.com/moby/moby/pull/42143

**Pull request closed without merging**
