### PR TITLE
Fix docker run -it on windows

### LINKED ISSUE #32799: Windows: docker run -it is broken on master
Looks like it was regressed by https://github.com/moby/moby/pull/32248, b2551c619d30f163c3ab8c9ee53cdb09bfbeaa55

@icapurro FYI. 

You now get "The Parameter is incorrect" when trying `docker run -it --rm microsoft/nanoserver cmd`

### PR DESCRIPTION
**Pull request by vdemeester**
I think it should fix #32799

Signed-off-by: Vincent Demeester <vincent@demeester.fr>

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM (when build is green)

**Comment by jhowardmsft** [comment]
LGTM. Verified locally. Thanks!!!

```
PS C:\> docker version
Client:
 Version:      17.06.0-dev
 API version:  1.30
 Go version:   go1.7.5
 Git commit:   8c014db30
 Built:        04/25/2017 16:47:46
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   8c014db30
 Built:        04/25/2017 16:46:54
 OS/Arch:      windows/amd64
 Experimental: false
```

**Review by lowenna — APPROVED** [review]

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
PPC CI failures were unrelated, but restarted. Again...

**Pull request merged**
