### PR TITLE
api/server: don't print warning if serving on localhost

### PR DESCRIPTION
**Pull request by mattyw**
Fixes bug #10728

Docker-DCO-1.1-Signed-off-by: Matt Williams lp@mattyw.net (github: mattyw)

### CODE REVIEW

**Comment by cpuguy83** [comment]
Quote from my comment mentioned issue:
> It needs to be warning no matter what it's binding to if --tlsverify isn't set.

Binding to any interface is a major security risk if not using `--tlsverify`, so I would prefer to make it always warn if not using `--tlsverify`.

**Comment by jfrazelle** [comment]
yes can we remove `!strings.HasPrefix(addr, "127.0.0.1") && !strings.HasPrefix(addr, "localhost") &&` so it always prints

**Comment by mattyw** [comment]
PTAL

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
