### PR TITLE
[20.10 backport] overlay2: support "userxattr" option (kernel 5.11)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Cherry-pick https://github.com/moby/moby/pull/42068

### CODE REVIEW

**Comment by thaJeztah** [comment]
looks like its failing; could it be it needs https://github.com/moby/moby/pull/42147 ?

**Comment by thaJeztah** [comment]
Can you try rebasing?

**Comment by thaJeztah** [comment]
Looks like this test is sometimes flaky; this is on arm64; https://ci-next.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-42168/runs/2/nodes/273/log/?start=0

```
 === FAIL: daemon/logger TestCopierWithSized/With_RingLogger (0.00s)
     --- FAIL: TestCopierWithSized/With_RingLogger (0.00s)
         copier_test.go:271: Line was not of expected max length 32768, was 34304
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
