### PR TITLE
Remove PortMapping from container NetworkSettings

### PR DESCRIPTION
**Pull request by runcom**
It's marked as deprecated and explicitly set to nil
I'm not sure this needs some notes on deprecated.md since it's set to nil since April but I could miss something
~~Tests are fine locally, dunno what's wrong here~~

Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by duglin** [comment]
Looks like a real test failure

**Comment by runcom** [comment]
@duglin you're right found (I may have run make test-unit on master instead of on this branch, my bad)

**Comment by duglin** [comment]
LGTM once janky is happy.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
