### PR TITLE
vendor: github.com/containerd/containerd v1.6.24

### PR DESCRIPTION
**Pull request by thaJeztah**
### vendor: github.com/Microsoft/hcsshim v0.9.10

Add support for platform compatibility check for windows + add windows builds

full diff: https://github.com/Microsoft/hcsshim/compare/v0.9.8...v0.9.10

### vendor: github.com/containerd/containerd v1.6.24

full diff: https://github.com/containerd/containerd/compare/v1.6.22...v1.6.24

v1.6.24 release notes:

full diff: https://github.com/containerd/containerd/compare/v1.6.23...v1.6.24

The twenty-fourth patch release for containerd 1.6 contains various fixes
and updates.

Notable Updates

- CRI: fix leaked shim caused by high IO pressure
- Update to go1.20.8
- Update runc to v1.1.9
- Backport: add configurable mount options to overlay snapshotter
- log: cleanups and improvements to decouple more from logrus

v1.6.23 release notes:

full diff: https://github.com/containerd/containerd/compare/v1.6.22...v1.6.23

The twenty-third patch release for containerd 1.6 contains various fixes
and updates.

Notable Updates

- Add stable ABI support in windows platform matcher + update hcsshim tag
- cri: Don't use rel path for image volumes
- Upgrade GitHub actions packages in release workflow
- update to go1.19.12
- backport: ro option for userxattr mount check + cherry-pick: Fix ro mount option being passed

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ah, dang, I messed up the links in the commit message (CI is green though!)

**Comment by thaJeztah** [comment]
Fixed the commit message; no changes in code

**Review by neersighted — APPROVED** [review]

**Comment by neersighted** [comment]
You have the casts set up differently from my BuildKit PR (https://github.com/moby/moby/pull/45966/commits/a5255a7df0bb9f7c41b03fc8fc8114ff32ca72ad), but your version also looks fine to me.

**Comment by thaJeztah** [comment]
From our slack conversation;

> I used the reverse for the type, with backport’ability in mind (also wasn’t sure if daemon/config was imported anywhere where we didn’t want containerd to become part of it)
>
> For v25.0 I’m more comfortable making that change though, so perhaps in your rebase, you can still keep your variant

**Pull request merged**
