### PR TITLE
gitutils: fix checking out submodules

### PR DESCRIPTION
**Pull request by tonistiigi**
Fix issue reported in https://github.com/moby/moby/pull/32502#issuecomment-349873402

In addition to adding new command, this also separates the internal clone function so that the test actually tests the commands instead of just validating the commands strings.

@ijc @dnephin @lgarithm

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Review by ijc — APPROVED** [review]
LGTM

**Review by dnephin — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
All tests pass except `z`, which is a known issue these days. Merging now...

**Comment by ryansanford** [comment]
Any chance this fix will be a new release in the stable channel before March?

**Pull request merged**
