### PR TITLE
docs: optimize and consolidate images, remove duplicates

### PR DESCRIPTION
**Pull request by thaJeztah**
This optimizes a number of images and removes a duplicate image. Also consolidated images in the 'docker-hub' section.

<strike>NOTE: This PR does _not_ include SEO (301)-redirects for the (re)moved images.</strike>

imageoptim-1
imageoptim-2

### CODE REVIEW

**Comment by jfrazelle** [comment]
Cool!!!

**Comment by thaJeztah** [comment]
Perhaps Gordon should detect images that can be optimized? All the tools in "ImageOptim" are basically command-line tools as well, just in a fancy package.

**Comment by thaJeztah** [comment]
Build completed succesfully, but noticed an error 500 in the logs. copied it here, in case it's useful ;

    time="2015-02-21T23:42:26Z" level="error" msg="Error parsing media type:  error: mime: no media type" 
    time="2015-02-21T23:42:26Z" level="error" msg="Handler for POST /containers/create returned error: Content-Type specified () must be 'application/json'" 
    time="2015-02-21T23:42:26Z" level="error" msg="HTTP Error: statusCode=500 Content-Type specified () must be 'application/json'"

**Comment by SvenDowideit** [comment]
@thaJeztah `docs/s3_website.json` contains the redirects if you're interested in adding them :)

LGTM - @fredlf @jamtur01 @spf13 @moxiegirl

**Comment by jamtur01** [comment]
LGTM

**Comment by thaJeztah** [comment]
@SvenDowideit thanks for the tip. I added the redirects, but please check if I did them correctly.

**Comment by fredlf** [comment]
LGTM Thanks for doing this, @thaJeztah ! @SvenDowideit can you please validate the redirects are formed correctly?

**Comment by SvenDowideit** [comment]
redirects LGTM, mergening

**Pull request merged**
