### PR TITLE
Add Lei Jitang to MAINTAINERS.

### PR DESCRIPTION
**Pull request by calavera**
Per vote on maintainers mailing list.

Welcome @coolljt0725!

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM! welcome @coolljt0725!!

**Comment by HuKeping** [comment]
so cool!

**Comment by coolljt0725** [comment]
Thank you guys for your trust. I'm appreciated for this. LGTM

**Comment by chenchun** [comment]
Congrats ! @coolljt0725

**Comment by mountkin** [comment]
:+1: Congratulations! @coolljt0725

**Comment by thaJeztah** [comment]
Ah, we don't need CI on this one, merging :)

**Comment by thaJeztah** [comment]
congrats @coolljt0725!

**Comment by coolljt0725** [comment]
Thank you  -:)

**Comment by hqhq** [comment]
:congratulations: :clap:

**Comment by runcom** [comment]
:tada: congrats!

**Comment by vdemeester** [comment]
:tada: :clap:

**Pull request merged**
