### PR TITLE
migrate pkg/pubsub to github.com/moby/pubsub

### LINKED ISSUE #44057: [DISCUSS] move pkg/pubsub to a standalone repository
### Description

Background: We are planning to implement a new architecture in the [Kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) project, and we found that pkg/pubsub works well for our needs. But we don't want to vendor the full docker repository. Start this discussion to move it to a standalone repository. Thanks!

The pkg/pubsub package is a small package and, looking at git history, has low maintenance (last changes were made 2 years ago). Similar to (e.g.) the https://github.com/moby/sys and https://github.com/moby/term packages, we can consider moving the package to its own repository, to allow easier consumption of the package without having to pull in the whole docker repository

/cc @thaJeztah @rikatz @strongjz

### PR DESCRIPTION
**Pull request by thaJeztah**
- closes https://github.com/moby/moby/issues/44057

This package was moved to a separate repository, using the steps below:

    # install filter-repo (https://github.com/newren/git-filter-repo/blob/main/INSTALL.md)
    brew install git-filter-repo

    cd ~/projects

    # create a temporary clone of docker
    git clone https://github.com/docker/docker.git moby_pubsub_temp
    cd moby_pubsub_temp

    # for reference
    git rev-parse HEAD
    # --> 572ca799db4b67b7be35904e487f0cc51c3f9f06

    # remove all code, except for pkg/pubsub, license, and notice, and rename pkg/pubsub to /
    git filter-repo --path pkg/pubsub/ --path LICENSE --path NOTICE --path-rename pkg/pubsub/:

    # remove canonical imports
    git revert -s -S 585ff0ebbe6bc25b801a0e0087dd5353099cb72e

    # initialize module
    go mod init github.com/moby/pubsub
    go mod tidy

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @corhere @tao12345666333 PTAL

**Review by corhere — APPROVED** [review]
Since it's already in production use, the github.com/moby/pubsub module should [have a v1.0.0 release.](https://0ver.org/)

**Review by tao12345666333 — APPROVED** [review]
LGTM

Thanks 🙏

**Comment by thaJeztah** [comment]
Yes, a v1.0.0 is probably ok; I guess just some minor touching up to do in the repository (add a minimal github actions to run tests), and we should be fine I think

**Review by cpuguy83 — APPROVED** [review]

**Comment by thaJeztah** [comment]
I opened https://github.com/moby/pubsub/pull/1 to add github actions to the repository

**Comment by thaJeztah** [comment]
Go Actions were added and happy. Let me tag a v1.0.0 and update this PR, then we should be all set (and we don't need to do a follow-up to update the version)

**Comment by thaJeztah** [comment]
Updated to v1.0.0 👍

**Pull request merged**
