### PR TITLE
Vendoring libnetwork @e8431956

### PR DESCRIPTION
**Pull request by sanimej**
- Fixes an issue with starting containers after upgrade from 1.12.x to 1.14-dev
- Fixes [docker 30295](https://github.com/docker/docker/issues/30295)

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
LGTM

@sanimej since this changes the ExtDNS type from extDNSEntry back to string, can you pls confirm how this will impact existing developer environment that runs previous versions of 1.14.0-dev and upgrading to a version after this PR is merged. am more curious if this will impact just the existing containers or will it impact also the daemon restartability if there are restartable containers ?

**Comment by thaJeztah** [comment]
This is the counterpart on master for https://github.com/docker/docker/issues/30467, correct?

**Comment by mavenugo** [comment]
@thaJeztah yes and more fixes that are specific to master

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by sanimej** [comment]
@mavenugo daemon will come up ok. But you have to delete the existing networks and recreate it. This is only if you are moving from a older 1.14-dev to the latest.

**Pull request merged**
