### PR TITLE
Remove pkg testutil cmd

### PR DESCRIPTION
**Pull request by dnephin**
Part of #32989 
Follow up to #34600

Replace `pkg/testutil/cmd` with the extracted package

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by vieux — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
@johnstep can you take a look into the test failure ?

```
22:13:05 ----------------------------------------------------------------------
22:13:05 FAIL: docker_cli_start_test.go:189: DockerSuite.TestStartReturnCorrectExitCode
22:13:05 
22:13:05 docker_cli_start_test.go:198:
22:13:05     c.Assert(exitCode, checker.Equals, 12)
22:13:05 ... obtained int = 1
22:13:05 ... expected int = 12
22:13:05 
22:13:05 
22:13:05 ----------------------------------------------------------------------
```

**Comment by vdemeester** [comment]
@dnephin needs a rebase too 👼

**Pull request merged**
