### PR TITLE
[DNM] ci: test buildkit features compat

### PR DESCRIPTION
**Pull request by crazy-max**
follow-up https://github.com/moby/buildkit/pull/3713#issuecomment-1468233465

disable azblob and s3 cache backend tests

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think we had to test this one in combination with https://github.com/moby/moby/pull/45153

**Comment by crazy-max** [comment]
@thaJeztah This PR was just to test for the s3 case: https://github.com/moby/buildkit/pull/3713#issuecomment-1468255866 but I can open another one with #45153

**Comment by thaJeztah** [comment]
@crazy-max yeah, so on that PR we saw a failure, so I thought (assumed) we wanted to test the new changes in BuildKit to work with that PR (to exclude the things that need to be excluded with the new env-vars)?

Looks like this PR is green, so I guess we can re-use this PR to include the other PR to test if it also works with those changes.

**Comment by thaJeztah** [comment]
🤦 OH! I see you already opened another PR; https://github.com/moby/moby/pull/45165 ?

**Comment by crazy-max** [comment]
> 🤦 OH! I see you already opened another PR; #45165 ?

Yes that's the one for merge diff, and looks good: https://github.com/moby/moby/actions/runs/4425205314

**Pull request closed without merging**
