### PR TITLE
Unmount Container rootfs after successful start

### PR DESCRIPTION
**Pull request by rhvgoyal**
This patch series fixes issue #11113

### CODE REVIEW

**Comment by rhvgoyal** [comment]
Re-pushed the branch after taking care of some of the comments of @rhatdan

**Comment by rhvgoyal** [comment]
Hmm.., something is wrong with jenkins? It has been saying "Jenkins build is being scheduled" for last 10 minutes now.

**Comment by jfrazelle** [comment]
theres a large build queue at the moment and your PR has 9 commits, it tests each individually

**Comment by rhvgoyal** [comment]
Hmmm..., tests failed.

---> Making bundle: test-integration (in bundles/1.5.0-dev/test-integration)

+ go test -test.timeout=45m github.com/docker/docker/integration

# github.com/docker/docker/integration
./utils_test.go:77: not enough arguments in call to c.Unmount

FAIL	github.com/docker/docker/integration [build failed]

There is one more call to UnMount(). This needs to be modifed to pass in "false" as parameter. Will fix it.

**Comment by rhvgoyal** [comment]
Pushed the patches again with the fix for last build failure.

**Comment by ahmetalpbalkan** [comment]
@rhvgoyal it might be better to squash some commits since reducing the commit count may help reducing the stress on CI machines. @jfrazelle what do you think?

**Comment by jfrazelle** [comment]
yes but since these are already in the queue squshing and force pushing again will just add to the queue more

**Comment by rhvgoyal** [comment]
@ahmetalpbalkan 

Personally I like to keep commits small and logically contained unit. Even if take more time to build. that way it helps review patches and in long term one can go back to commits and figure out more easily what went in and why.

But every project is different. So if docker project prefers to combine commits and keep number of commits small, I can do that.

**Comment by icecrime** [comment]
Thank you @rhvgoyal. I understand your taste for separated commit, but that's not what [the Docker project encourages](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#conventions). Please squash in 1 if you don't mind!

**Comment by rhvgoyal** [comment]
@icecrime 

Ok, I will put all this into one patch and push again.

But I seriously disagree with this methodology. I just can't review a single big patch and not sure how other people can review such changes.  Logically broken down commits with proper commit messages are so much easier to review. People can easily get to the core changes without having to worry about not so much important details.

And I was reading the link you pointed me to. I could not find out where does it say that put everything into a single commit. I could find following though.

" Before you make a pull request, squash your commits into logical units of work using git rebase -i and git push -f. After every commit, make sure the test suite passes. Include documentation changes in the same pull request so that a revert would remove all traces of the feature or fix".

So as per above, you do expect multiple commits in a pull request. Only question is what is considered a "logical unit of work" and I could not find guidelines for what is a logical unit of work. I think I did break down patches into multiple logical unit of work. That's a different thing that somebody might disagree with my organization and say hey i only see 3 logical units and not more.

**Comment by icecrime** [comment]
I'll update the `CONTRIBUTING.md` to define a "logical unit of work".

**Comment by rhvgoyal** [comment]
Ok, pushed one more time. This time merged all the patches into single patch as asked by @icecrime

**Comment by rhvgoyal** [comment]
@jfrazelle 

This "make test-docker-py" failure is happening even without my patches on my local machine. So doe not look like anything related to my patches.

**Comment by jfrazelle** [comment]
I think it should be fixed now

**Comment by rhvgoyal** [comment]
@jfrazelle 

How do I restart my failed job?

**Comment by jfrazelle** [comment]
restarted the builds

**Comment by rhvgoyal** [comment]
@jfrazelle  @vbatts @cpuguy83 

I am wondering how can I make some progress on this pull request. Any thoughts?

**Comment by aluzzardi** [comment]
@rhvgoyal I believe the Windows failure is genuine - could you have a look please?

**Comment by rhvgoyal** [comment]
This is also the solution for following issue.

https://github.com/docker/docker/issues/10991

But now I prefer the alternate solution of deferring device removal posted here.

https://github.com/docker/docker/pull/12190

**Comment by jfrazelle** [comment]
closing in favor of #12190

**Pull request closed without merging**
