### PR TITLE
Use spf13/cobra for docker history

### PR DESCRIPTION
**Pull request by yongtang**
This fix is part of the effort to convert commands to spf13/cobra #23211.

Thif fix coverted command `docker history` to use spf13/cobra

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Ok, learned two things from testing this;

1. Looks like `docker history` does not support immutable identifiers (also true for docker 1.11);

  docker history nginx@sha256:e2d7332b6da6dba653c81c1596a0aa1142e5a28fc99a153ec06520285d420924
  Error response from daemon: no such id: nginx@sha256:e2d7332b6da6dba653c81c1596a0aa1142e5a28fc99a153ec06520285d420924


2. The output format of the "non human" version of the date is dependent on the host (settings), it seems:

on my host

```
docker history --human=false nginx:alpine
IMAGE               CREATED                     CREATED BY                                      SIZE                COMMENT
a32fd277704c        2016-06-01T20:06:21+02:00   /bin/sh -c #(nop) CMD ["nginx" "-g" "daemon o   0
<missing>           2016-06-01T20:06:20+02:00   /bin/sh -c #(nop) EXPOSE 443/tcp 80/tcp         0
...
```


in container

```
docker history --human=false nginx:alpine
IMAGE               CREATED                CREATED BY                                      SIZE                COMMENT
a32fd277704c        2016-06-01T18:06:21Z   /bin/sh -c #(nop) CMD ["nginx" "-g" "daemon o   0
<missing>           2016-06-01T18:06:20Z   /bin/sh -c #(nop) EXPOSE 443/tcp 80/tcp         0
...
```

**Comment by thaJeztah** [comment]
but, LGTM, thanks @yongtang!

**Pull request merged**
