### PR TITLE
Use the official mime type that exists instead of an imaginary one that does not.

### LINKED ISSUE #9954: Invalid MIME type used in several places
Several codepaths set the Content-Type of a request to an invalid value - "plain/text".

These pieces of code probably intend to set the value to "text/plain".

### PR DESCRIPTION
**Pull request by exarkun**
Fixes #9954 

I didn't add any unit tests for this change because I couldn't find any existing unit tests for either of the modified files and my understanding of the code being modified is not sufficiently great that I feel comfortable starting these test suites from scratch.

I did modify part of the API docs to apply this fix - but only in the two cases where it seemed likely relevant.  I left one other occurrence alone where the correct fix would **seem** to be a change to application/json or something similar.

### CODE REVIEW

**Comment by crosbymichael** [comment]
Can you please `go fmt` your files?  `go fmt -s`

**Comment by SvenDowideit** [comment]
wow - oops 

Can you do a `git grep 'plain/text'` and fix the third 1.17 API doc one too? 

and yup, can't change the older released API's __unless__ this gets merged into a patch release of 1.4 - @crosbymichael ?

**Comment by exarkun** [comment]
> I guess someone needs to verify the other plain/text case in the 1.17 API doc?

Yes.  I don't know offhand what content-type is actually used by that endpoint - but I suspect it's not text/plain.

**Comment by jfrazelle** [comment]
@exarkun can you please gofmt you files and force push this branch:
`go fmt -s`

**Comment by exarkun** [comment]
Unfortunately the version of `go fmt` packaged for my OS doesn't support the `-s` option.  I haven't had a chance to figure out what's involved in getting a newer version yet.

**Comment by jfrazelle** [comment]
I can do it for you:)

**Comment by jfrazelle** [comment]
I took your commits and `gofmt`'d them in #10019 so I am going to close this. Thanks!

**Pull request closed without merging**
