### PR TITLE
integration-cli: remove not necessary -d

### PR DESCRIPTION
**Pull request by runcom**
/cc @icecrime 

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
Slightly related to #20543 because -d and the later rm of the container seems to cause that issue

**Comment by runcom** [comment]
@icecrime this is at least letting me run the full tests w/o crashing (not fixing the linked issue)

**Comment by icecrime** [comment]
LGTM until we can find the root cause

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
