### PR TITLE
Increase raft ElectionTick to 10xHeartbeatTick

### PR DESCRIPTION
**Pull request by anshulpundir**
Related change in swarmkit https://github.com/docker/swarmkit/pull/2564

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
Makes sense, LGTM.

**Comment by thaJeztah** [comment]
Is a revendor of SwarmKit also needed, or is the code that changed there not used here?

**Comment by anshulpundir** [comment]
>Is a revendor of SwarmKit also needed, or is the code that changed there not used here?
We can revendor it, but its strictly not needed. @thaJeztah

**Comment by anshulpundir** [comment]
BTW, can we merge it or is codecov/patch — 0% of diff hit (target 50%) a concern ? @cpuguy83 @thaJeztah

**Review by thaJeztah — APPROVED** [review]
LGTM

not sure if a test case is possible for this

**Comment by cpuguy83** [comment]
It would be really nice to come up with a way to test network instability somewhere.

**Comment by anshulpundir** [comment]
agreed. we're figuring out the approach to test this @cpuguy83

**Pull request merged**
