### PR TITLE
builder: remove unused netnsRoot field in builder-next

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <tibor@docker.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
@tiborvass Doesn't build

**Comment by tiborvass** [comment]
🤦‍♂️ I thought I pushed the fix in time, oops. Fixed now

**Review by tonistiigi — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
experimental failure is being worked on in https://github.com/moby/moby/pull/37773

**Pull request merged**
