### PR TITLE
Use temp dir for integration daemon sockets

### PR DESCRIPTION
**Pull request by cpuguy83**
Instead of using the bundles dir, which may be mounted in and ultimately
break if using b2d/d4mac/d4win. This makes it much easier to collect
test daemon logs and more natural for use d4mac/d4win users to run tests.

Addresses one aspect of #23545

### CODE REVIEW

**Comment by stevvooe** [comment]
I have a similar patch locally, but it fails with the following during the integration tests:

```
check_test.go:229:
    c.Assert(d.Init(swarm.InitRequest{}), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"initializing swarm: invalid statuscode 500, \"{\\\"message\\\":\\\"listen unix /go/src/github.com/docker/docker/bundles/1.12.0-rc5/test-integration-cli/d21403372/root/swarm/control.sock: bind: file name too long\\\"}\\n\""} ("initializing swarm: invalid statuscode 500, \"{\\\"message\\\":\\\"listen unix /go/src/github.com/docker/docker/bundles/1.12.0-rc5/test-integration-cli/d21403372/root/swarm/control.sock: bind: file name too long\\\"}\\n\"")
```

We need to be able to move the swarm socket, as well.

**Comment by LK4D4** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by thaJeztah** [comment]
all green; merging

**Comment by jhowardmsft** [comment]
@cpuguy83 This change (or at least something which is now firing this code) is breaking windowsRS1 CI now. Which isn't surprising as this code won't work on Windows. For example, https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/1592/console:

```
...
11:47:46 SKIP: docker_cli_proxy_test.go:26: DockerDaemonSuite.TestCliProxyProxyTCPSock
11:47:46 SKIP: docker_cli_exec_test.go:82: DockerDaemonSuite.TestExecAfterDaemonRestart
11:47:46 
11:47:46 ----------------------------------------------------------------------
11:47:46 FAIL: check_test.go:191: DockerDaemonSuite.TearDownSuite
11:47:46 
11:47:46 check_test.go:201:
11:47:46     c.Assert(err, checker.IsNil, check.Commentf("error while cleaning up daemon sockets"))
11:47:46 ... value *os.PathError = &os.PathError{Op:"GetFileAttributesEx", Path:"D:\\CI\\CI-bc228eb\\docker-integration", Err:0x2} ("GetFileAttributesEx D:\\CI\\CI-bc228eb\\docker-integration: The system cannot find the file specified.")
11:47:46 ... error while cleaning up daemon sockets
11:47:46 
11:47:46 SKIP: docker_cli_build_test.go:5518: DockerTrustSuite.TestBuildContextDirIsSymlink
11:47:46 SKIP: docker_cli_create_test.go:359: DockerTrustSuite.TestCreateWhenCertExpired
11:47:46 SKIP: docker_cli_pull_trusted_test.go:65: DockerTrustSuite.TestPullWhenCertExpired
11:47:46 SKIP
...
```

Could you PTAL. Thanks :smile:

**Comment by jhowardmsft** [comment]
Actually - it failed on this run, just the error didn't get propagated back (but does in the latest version of the CI scripts which I haven't yet put into production). So it is this change which is the issue.

**Comment by thaJeztah** [comment]
oh wow, CI failed, but reported success;


```
18:47:46 OOPS: 414 passed, 668 skipped, 1 FAILED
18:47:46 --- FAIL: Test (1180.06s)
18:47:46 FAIL
18:47:46 coverage: 30.4% of statements

...

18:48:13 INFO: End of cleanup
18:48:13 Notifying endpoint 'HTTP:https://leeroy.dockerproject.org/notification/jenkins'
18:48:13 Finished: SUCCESS
```

**Pull request merged**
