### PR TITLE
Clean up authz integration-cli test

### PR DESCRIPTION
**Pull request by estesp**
- Order the flow of the handlers more cleanly--read req, do actions,
  write response.
- Add "always allowed" endpoints to handle `/_ping` and `/info` usage
  from the test framework/daemon start/restart management

Docker-DCO-1.1-Signed-off-by: Phil Estes estesp@linux.vnet.ibm.com (github: estesp)

### CODE REVIEW

**Comment by estesp** [comment]
For those trying to keep score at home, this is "step 2" in my attack on the authz CI flakiness issues. To do "step 3" (get rid of the daemon restarts in the actual tests), need to vendor in **docker/engine-api** now that the content-type fix is in.

**Comment by calavera** [comment]
LGTM

**Comment by estesp** [comment]
Now that #20521 is merged, I added the "step 3" commit to this PR rather than create a new one.

@calavera you are free to reconsider your LGTM-ness on this PR :)

**Comment by icecrime** [comment]
Thanks! LGTM if green

**Comment by runcom** [comment]
I'm getting https://github.com/docker/docker/pull/20509#issuecomment-186474202 which clearly show the tests process has been **Terminated** even on my laptop when running make test-integration-cli (sometimes I also get **Killed**). Has anybody any clue about what's happening?

I'll relaunch tests and merge if it's green tho

**Comment by runcom** [comment]
userns flacky test - merging - and I'll open another issue about my problem above

**Pull request merged**
