### PR TITLE
Add bash completion to the development container

### PR DESCRIPTION
**Pull request by albers**
For developing bash completion, I need an environment with
- Docker daemon
- Docker cli
- the bash completion script

Bash completion was removed from this repository in #33665 and is now located in `docker/cli`.
#32694 added a way to mount a development version of the `docker` binary into the development container.
This PR adds a way to also include the bash completion script.

It does so by adding an environment variable `DOCKER_BASH_COMPLETION_PATH` to the Makefile.
The variable works like `DOCKER_CLI_PATH`: The directory hosting the specified file is mounted into the container. A symbolic link in `/etc/bash_completion.d/` activates the completion script on container startup.

The command to start a container for developing bash completion would be
```bash
DOCKER_CLI_PATH=~/go/src/github.com/docker/cli/build/docker DOCKER_BASH_COMPLETION_PATH=~/go/src/github.com/docker/cli/contrib/completion/bash/docker make shell
```

To verify: start the container with the given command and try bash completion of any Docker command.

Please merge quickly. Because I had no working dev environment for several weeks, some missing features queued up.

### CODE REVIEW

**Comment by albers** [comment]
@tiborvass, @thaJeztah, @mlaventure Would you like to take a look at this?

**Review by mlaventure — APPROVED** [review]
LGTM

I had to do `source /etc/bash_completion` first though, but that was already the case before.

**Comment by albers** [comment]
Oh yes, I forgot that I use a custom .bashrc that initializes bash completion.

**Comment by thaJeztah** [comment]
> I had to do source /etc/bash_completion first though, but that was already the case before.

Should we do that as part of `make shell`?

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by albers** [comment]
> Should we do that as part of make shell?

@thaJeztah Created #33816

**Pull request merged**
