### PR TITLE
[25.0 backport] vendor: github.com/opencontainers/runc v1.1.12

### PR DESCRIPTION
**Pull request by thaJeztah**
- backport https://github.com/moby/moby/pull/47272
- release notes: https://github.com/opencontainers/runc/releases/tag/v1.1.12
- full diff: https://github.com/opencontainers/runc/compare/v1.1.11...v1.1.12

(cherry picked from commit b20dccba5ee345bdd6dcd5c79b598b6c041c749f)

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by laurazard — APPROVED** [review]
LGTM

**Review by vvoland — APPROVED** [review]

**Comment by vvoland** [comment]
Weird failure:

```
=== FAIL: amd64.integration-cli TestDockerCLIPluginsSuite/TestPluginMetricsCollector (12.15s)
    docker_cli_plugins_test.go:469: assertion failed: r.Error is not nil: latest: Pulling from cpuguy83/docker-metrics-plugin-test
        Digest: sha256:6d4eea181eda6ff933093ec04d1b26a4c26b3a620263140a986158be8192a882
        a67d4c51c505: Waiting
        a67d4c51c505: Pulling fs layer
        a67d4c51c505: Complete
        a67d4c51c505: Download complete
        incorrect privileges
```

probably just flaky though

**Comment by thaJeztah** [comment]
Failure looks unrelated;

```
=== Failed
=== FAIL: amd64.integration-cli TestDockerCLIPluginsSuite/TestPluginMetricsCollector (12.15s)
    docker_cli_plugins_test.go:469: assertion failed: r.Error is not nil: latest: Pulling from cpuguy83/docker-metrics-plugin-test
        Digest: sha256:6d4eea181eda6ff933093ec04d1b26a4c26b3a620263140a986158be8192a882
        a67d4c51c505: Waiting
        a67d4c51c505: Pulling fs layer
        a67d4c51c505: Complete
        a67d4c51c505: Download complete
        incorrect privileges
        
    --- FAIL: TestDockerCLIPluginsSuite/TestPluginMetricsCollector (12.15s)
```

**Comment by thaJeztah** [comment]
Oh! LOL sorry for the double post; blame browser cache.

Everything else is green; bringing this one in

**Pull request merged**
