### PR TITLE
Remove duplicate TestServiceUpdatePort

### PR DESCRIPTION
**Pull request by thaJeztah**
The `TestAPIServiceUpdatePort` test performs exactly the same steps.

Here's one; https://github.com/moby/moby/blob/5a4841079bc247937e6ed1042ab24ffd01a8547c/integration-cli/docker_cli_service_update_test.go#L14-L47

And the other;

https://github.com/moby/moby/blob/5a4841079bc247937e6ed1042ab24ffd01a8547c/integration-cli/docker_api_swarm_service_test.go#L32-L51

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
hm... https://jenkins.dockerproject.org/job/Docker-PRs-experimental/39654/console

```
15:31:45 === RUN   TestServiceWithPredefinedNetwork
15:31:56 --- FAIL: TestServiceWithPredefinedNetwork (11.33s)
15:31:56 	daemon.go:283: [d016408df2853] waiting for daemon to start
15:31:56 	daemon.go:315: [d016408df2853] daemon started
15:31:56 	service_test.go:52: timeout hit after 10s: task count at 1 waiting for 0
15:31:56 	daemon.go:273: [d016408df2853] exiting daemon
15:31:56 FAIL
```

Odd, that test was added in https://github.com/moby/moby/pull/36316, but trying to understand how `waiting for 0` can occur

**Comment by thaJeztah** [comment]
oh! misreading, was looking at service count, not task-count (thanks @vdemeester), so that test is failing at https://github.com/moby/moby/blob/0b0af855ae28698f8e3dc97cdc2a46e714ce6b6a/integration/network/service_test.go#L52

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
