### PR TITLE
Bump go 1.5

### PR DESCRIPTION
**Pull request by diogomonica**
Bumping Docker to use Go 1.5
- uses binaries for go compiling, speeding up cache busts
- fixes statically compiling windows
- fixes IPv6 URL parsing
- closes #15703

### CODE REVIEW

**Comment by tianon** [comment]
LGTM :+1:

**Comment by jfrazelle** [comment]
LGTM, working on fixing `test-unit` too to see if we can speed up the unit tests

**Comment by jfrazelle** [comment]
btw windows is failing because we are running 1.4 on there still and it doesnt have the concept of -linkmode, but I am fixing

**Comment by jfrazelle** [comment]
nm we good

**Comment by tianon** [comment]
We should hit the generate scripts for the deb and rpm builder scripts now
too. :+1:

**Comment by LK4D4** [comment]
What about unit-tests? It mentioned in commit message.

**Comment by jfrazelle** [comment]
Ya I have a follow up pr sorry was seeing weird stuff wanted to make sure it was consistent over speed

**Comment by jfrazelle** [comment]
Ya I really don't see a difference in the time without the parallel

**Comment by jfrazelle** [comment]
I cant tell if its different per graphdriver either :/

**Comment by unclejack** [comment]
It's very sad to see that we've switched from building everything from source to using binaries for Go.

**Pull request merged**
