### PR TITLE
Enable HotAdd for Windows

### PR DESCRIPTION
**Pull request by madhanrm**
Signed-off-by: Madhan Raj Mookkandy <madhanm@microsoft.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by madhanrm** [comment]
There is a bug in libnetwork - PR https://github.com/docker/libnetwork/pull/2010 is required to be vendored into docker for hotadd to work properly

**Comment by madhanrm** [comment]
Ping @mavenugo @dineshgovindasamy @pradipd @msabansal

**Review by dineshgovindasamy — APPROVED** [review]
@mavenugo Could you please approve this PR?

**Comment by madhanrm** [comment]
ping @jhowardmsft

**Comment by cpuguy83** [comment]
Ping @johnstep

**Comment by jhowardmsft** [comment]
@madhanrm Does this need a system version check (as we need to support RS1+)

**Comment by madhanrm** [comment]
The platform would throw not supported, if the request is not supported.

This PR depends on  docker/libnetwork#2010  to be merged first

**Comment by madhanrm** [comment]
Can someone vendor in docker/libnetwork#2010, before this can be merged?

**Review by johnstep — APPROVED** [review]
LGTM and docker/libnetwork#2010 is merged as of https://github.com/moby/moby/commit/e37374c0673bf56890e33afed112ad9e3a682203.

**Review by lowenna — APPROVED** [review]
LGTM

**Pull request merged**
