### PR TITLE
Remove container if --rm flag is passed and container cannot be started

### LINKED ISSUE #9658: Docker doesn't remove the container if it exit with non-zero exit code when auto remove enabled
We are running dockers on a large cluster for a time and found lots of machines with many finished containers with non-zero exit code that have not been removed. We run docker container always with --rm option specified.
I think docker daemon should remove containers even if exit with a non-zero exit code when specified --run option, is it reasonable?

### PR DESCRIPTION
**Pull request by runcom**
Partially fixes #9658

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by jfrazelle** [comment]
I think we decided we want this to be done fully on the daemon side so we can sure cc @duglin

**Comment by duglin** [comment]
@jfrazelle true that is the preferred solution.

But, I also have no problem with this client-side solution in the meantime since, if nothing else, it will prepare people for the idea that no matter what happens the container will be removed (instead of just on a successful `run`), when the `rm` flag is used.

However, this fix isn't quite right. It only deleted the container when the start command fails.  There are several other `return` statements after the container `create` that need to be taken into account too.  Would it be bad to do the check and container `delete` via a defer ? If that's too much then we should resigned it so that there's only one return (at the end) and we can do the check just one down there.

**Comment by chenchun** [comment]
I agree with @duglin. It's better to use `defer` instead of only adding a delete request after failing to start container.

**Comment by runcom** [comment]
Something like the following before starting the container could work but I'll move the container deletion to another funciton so it can also be called after running a container with `--rm` (here: https://github.com/runcom/docker/blob/master/api/client/commands.go#L2539):
```golang
	defer func() {
		if *flAutoRemove {
			if _, _, err := readBody(cli.call("DELETE", "/containers/"+createResponse.ID+"?v=1", nil, false)); err != nil {
				return err
			}
		}
	}()

```

**Comment by duglin** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
