### PR TITLE
Return error if basename is expanded to blank

### PR DESCRIPTION
**Pull request by yui-knk**
Fix: https://github.com/moby/moby/issues/37325

Signed-off-by: Yuichiro Kaneko <spiketeika@gmail.com>

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM :+1:

**Comment by thaJeztah** [comment]
Looking good; testing with empty values; both with a `:tag` and _without_;

```bash
docker build --no-cache -<<'EOF'
ARG SOMETHING
ARG ALPINE

FROM ${SOMETHING} as builder
# No actual build steps, just copying

FROM ${ALPINE}

EXPOSE 8080
EOF
```

```
Sending build context to Docker daemon  2.048kB
Step 1/5 : ARG SOMETHING
Step 2/5 : ARG ALPINE
Step 3/5 : FROM ${SOMETHING} as builder
base name (${SOMETHING}) should not be blank
```

With `:tag`:

```bash
docker build --no-cache -<<'EOF'
ARG SOMETHING
ARG ALPINE

FROM ${SOMETHING}:latest as builder
# No actual build steps, just copying

FROM ${ALPINE}:latest

EXPOSE 8080
EOF
```

```
Sending build context to Docker daemon  2.048kB
Step 1/5 : ARG SOMETHING
Step 2/5 : ARG ALPINE
Step 3/5 : FROM ${SOMETHING}:latest as builder
invalid reference format
```

**Comment by thaJeztah** [comment]
Wondering if we already have a test covering the "with `:tag`" option somewhere

**Comment by thaJeztah** [comment]
Also; janky failure is not related; tracked through https://github.com/moby/moby/issues/32673

```
10:46:48 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
10:46:48 
10:46:48 [dd124c5850d58] waiting for daemon to start
10:46:48 [dd124c5850d58] daemon started
10:46:48 
10:46:48 [df0c66ae7bfc0] waiting for daemon to start
10:46:48 [df0c66ae7bfc0] daemon started
10:46:48 
10:46:48 [d107b37dcc526] waiting for daemon to start
10:46:48 [d107b37dcc526] daemon started
10:46:48 
10:46:48 [dd124c5850d58] exiting daemon
10:46:48 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
10:46:48 [df0c66ae7bfc0] exiting daemon
10:46:48 [d107b37dcc526] exiting daemon
```

restarting, but all other tests were green

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
I think @tonistiigi had some questions about this; @tonistiigi PTAL

**Comment by tonistiigi** [comment]
The real reason why the error didn't appear seems to be that empty string is reused to mean `FROM scratch` in https://github.com/moby/moby/blob/328c089b5bca66594c4937e88cf9879879c4eed7/daemon/images/image_builder.go#L171 . So unless we want to refactor this to be safer the current solution LGTM but should have a comment about why this extra validation is needed.

**Comment by yui-knk** [comment]
I added comment. Can you review again when you have a chance.

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
