### PR TITLE
add a more accurate error description for invalid tag name

### PR DESCRIPTION
**Pull request by yuchangchun1**
please let me know if you have a better description or idea

### CODE REVIEW

**Comment by yuchangchun1** [comment]
thanks，i will try it again

**Comment by yuchangchun1** [comment]
hi,i want to discuss something about tag name with you . 
docker client allow '_' as a initial of tag name,but docker-registry v1 got a bug ,as follows:
#docker tag 127.0.0.1:80/official/busybox:latest 127.0.0.1:80/official/busybox:_testtag
#docker push 127.0.0.1:80/official/busybox:_testtag
#curl -X GET 127.0.0.1:80/v1/repositories/official/busybox/tags
{"_testtag": "4986bf8c15363d1c5d15512d5266f8777bfba4974ac56e3270e7760f6f0a8125", "latest": "4986bf8c15363d1c5d15512d5266f8777bfba4974ac56e3270e7760f6f0a8125", "testtag_json": "{\"kernel\": \"3.13.0-53-generic\", \"arch\": \"amd64\", \"docker_go_version\": \"go1.4.2\", \"last_update\": 1433297452, \"docker_version\": \"1.6.0-rc1\", \"os\": \"linux\"}"}

the remote api (getting tags) returns unnecessary json information . because registry v1 places 'tag_' as a separator when processing this request.that is why i got a json key 'testtag_json' . 

in fact this is a bug of registry v1;registry v2 handles it properly.

so do you think whether it is necessary to disallow '_' as a initial of tag name?

**Comment by yuchangchun1** [comment]
sorry,TestCliStatsNoStreamGetCpu failed . i don't know why.

**Comment by coolljt0725** [comment]
`TestCliStatsNoStreamGetCpu` failed is unrelated, #13645 are going fix this.

**Comment by jfrazelle** [comment]
LGTM

**Comment by calavera** [comment]
LGMT

**Pull request merged**
