### PR TITLE
Continuation of the `docker secret` storage feature

### PR DESCRIPTION
**Pull request by vbatts**
Closes https://github.com/dotcloud/docker/pull/6075

Starting on a new PR to accommodate alex being on holiday

### CODE REVIEW

**Comment by razic** [comment]
@shykes Before I go and create a proposal for the "dev ssh key for builds" use case, I just want to make sure there aren't any currently open.

This one is closed and #10310 doesn't address an individual use case like you asked for on Nov 4th.

I couldn't find any other related proposals but just wanted to make sure. Can you confirm?

**Comment by NitroBAY** [comment]
Damn we're in 2017 and after reading tons of PR and articles the only thing I learned is that Docker has this problem for a long time even tough a lot of PR has been proposed. Weirdo.

**Comment by timthelion** [comment]
The trouble that happened was that during one of the regular IRC 
meetings a design was proposed by three people and agreed upon by 
@shykes (I don't even recal the exact design) a seccond design was 
proposed by like two people and implemented by Alex Larson. And the two 
designs were very different and @shykes explicitly said during the 
meeting that he didn't like the one that Alex proposed. And so it lead 
to this weird situation of having an implemented PR that was against the 
wishes of the BDFL and no PR that was according to his wishes. Now I 
think that shykes is quite busy right now, and so maybe his oppinion 
matters less and this PR can go through. Or someone can go look up those 
old IRC conversations and try to implement the "correct" design.

**Comment by thaJeztah** [comment]
@NitroBAY @timthelion have a look at https://github.com/docker/docker/pull/27794 (which will be in docker 1.13), and https://github.com/docker/docker/pull/28079 (which probably will be continued on for docker 1.14)

**Comment by NitroBAY** [comment]
Okay thanks, I may be suprised because I'm used to such huge projects, it's maybe normal that implement a feature is that complex in that kind of projects.

**Pull request closed without merging**
