### PR TITLE
Remove grpc logging to stderr

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by icecrime** [comment]
Is that still logging _some_ of gRPC output?

**Comment by crosbymichael** [comment]
@icecrime no

**Comment by mlaventure** [comment]
Don't we want to keep the other errors though?

**Comment by crosbymichael** [comment]
yes, errors not debugging output are returned to the consumer

**Comment by thaJeztah** [comment]
@crosbymichael should this have been opened against the bump branch? :innocent:

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
I'll bite

**Pull request merged**
