### PR TITLE
Extract event processing to a common function for testing.

### PR DESCRIPTION
**Pull request by calavera**
We keep only one logic to test event related behavior that will help us
diagnose flacky event errors.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

My only nit is that I would prefer if `eventObserver.Match` did not wrap its contents in a new goroutine. Writing `go observer.Match(matcher)` in calling code would make it more obvious that the matching happens asynchronously. That would also give calling code more control over the goroutine lifecycle, in case it needed to prevent the callback from being called after the test completes.

**Comment by calavera** [comment]
@aaronlehmann I agree with you. The problem is that the even delivery is not synchronous and we don't completely control when the event is delivered, that's why I left the goroutine.

**Comment by calavera** [comment]
gosh, sorry @aaronlehmann, I didn't understand your comment correctly the first time I read it. I've change the match calls, I like it better too.

**Comment by vdemeester** [comment]
LGTM 🐸 assuming it's green :smile_cat:

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
