### PR TITLE
[DO NOT MERGE][RFD] Merge back old release branches to master (to assist go mod?)

### PR DESCRIPTION
**Pull request by thaJeztah**
This came up in a maintainers meeting, and something to explore / discuss.

Although this definitely doesn't fix everything (we'd need to bring back the release-branches from docker/engine to this repository), perhaps it helps a bit with `go mod`.

Go mod expects the commits related to all tags to be found on master. Given that we've used long-lived release branches to cherry-pick fixes into releases (while master still got changes merged for the "next" release), commits in release branches (and thus the commit associated with tags) cannot be found on master.

For example, running `git describe --tags` on master currently shows;

```bash
git describe --tags
docs-v1.12.0-rc4-2016-07-15-11992-g9adc7bb379
```

This PR merges back all release branches to master (note: perhaps we should use the tags instead of release branches, but we can discuss that). The branches are merged with `--strategy=ours` (in other words: don't pick up actual changes, just unify the branches (for better words);

Screenshot 2019-10-02 at 13 57 20

I used the following to create this PR:

```bash
for branch in 1.12.x 1.13.x 17.03.x 17.04.x 17.05.x; do git merge --no-ff --signoff -S --strategy=ours upstream/${branch} -m "Merge branch '${branch}' into master"; done
```

#### Before this change;

```bash
git describe --tags
docs-v1.12.0-rc4-2016-07-15-11992-g9adc7bb379
```

#### After this change;

```bash
git describe --tags
v17.05.0-ce-7761-g47e625fdfe
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tianon @SamWhited @tonistiigi @tiborvass @cpuguy83 @kolyshkin @andrewhsu @AkihiroSuda  ptal. Interested to hear if this is worth doing (and perhaps works as a strategy for other repos (such as buildkit) as well.

**Comment by thaJeztah** [comment]
Note that (locally), I also tried to merge back the release branches from https://github.com/docker/engine;

```bash
for branch in 18.06 18.09 19.03; do git merge --no-ff --signoff -S --strategy=ours ce-engine/${branch} -m "Merge branch '${branch}' into master"; done
```

After which `git describe --tags` shows;

```bash
git describe --tags
v19.03.3-beta2-3799-g5eb3ab51a4
```

**Comment by SamWhited** [comment]
I hate that we'd have to pollute our history this way, but I don't see a tenable alternative right now. 

As a temporary workaround: maybe we could start using the `/major-version` prefix and then we'd still have the odd version numbers based around `v1.4.2` or whatever the last tag on master is, but at least you'd be able to see from the import path that it was wrong (it's not great, but I'm just spitballing). It would also make maintenance a pain with our release versioning, but that's something I think we'll have to change eventually anyways as Go is making more and more assumptions that we're using semver.

It may be worth submitting a [proposal](https://go.googlesource.com/proposal/) first if we can come up with a different way of searching for commits, but I wouldn't hold my breath since anything we do is likely to break MVS or cause existing go.mod files to change if it were in a new version of Go (and I think they've said they're stabilizing the selection, but don't quote me on that).

**Comment by AkihiroSuda** [comment]
Can we just push branches ans tags from docker/engine?

**Comment by thaJeztah** [comment]
> I hate that we'd have to pollute our history this way

I'm not sure if it's too bad; I actually think this is a common approach (i.e., merge release branches back to master), although I'm not sure if `--strategy ours` is best practice there. 

> Can we just push branches ans tags from docker/engine?

I think that discussion is still ongoing, but I'm personally +1 on bringing back the release branches from docker/engine in this repository, do cherry-picking here as well (and we could keep docker/engine as a mirror)


Unfortunately, that still won't fix all `go mod` issues (as those tags aren't SemVer), but it would be a first step.

> As a temporary workaround: maybe we could start using the /major-version prefix

Yeah, it's still tricky; in that case, I guess `v19.09` would become `v1909.0.0` to be SemVer(ish), and given that we have no stability guarantee on our go API (so each release would be a new major bump.

IIUC, that would require people to update their import paths with _each release_, correct? Thus;

```go
import "github.com/docker/docker/v1909/pkg/foo"
```

**Comment by SamWhited** [comment]
> Yeah, it's still tricky; in that case, I guess v19.09 would become v1909.0.0

I was thinking it would still be `v19.09.0` or similar, but the tag would effectively be ignored. This way if you imported docker and depended on the 19.09 branch you'd get something like this (this is actually the `17.05.x` branch with the version/import path changed for the example):

```
$ go get github.com/docker/docker@19.09.x
$ grep docker/docker go.mod
require github.com/docker/docker/19 v1.4.2-0.20170504205632-89658bed64c2
```

This way we can at least see the major version, even though it (annoyingly) doesn't show up in the actual version. It's not great, but it means that if something uses `/v19` and something else uses `/v20` they don't resolve to one path and confuse the selection. They end up being two distinct packages (which may or may not be what we want but is probably good since we break the API frequently and if they're using two versions it's better to be able to see it than to wonder why an old version is being selected with an API we can' tuse).

**Comment by tonistiigi** [comment]
This PR completely messes up `git log --graph --oneline` (or other `git log` variant you might like) that I would argue is the most important command in git.

**Comment by tianon** [comment]
IMO merging the branches/tags all back into master is overkill -- if we just copy the tags over as-is with no other changes, this is what I get on current master:

```console
$ git describe --tags
v19.03.0-beta3-1024-ga4a82bb0ee
```

Here's a fuller shell history for folks that want to reproduce what I did:

```console
$ git clone https://github.com/moby/moby.git
$ cd moby
$ git describe --tags
docs-v1.12.0-rc4-2016-07-15-11994-ga4a82bb0ee
$ git fetch --tags https://github.com/docker/engine.git
$ git describe --tags
v19.03.0-beta3-1024-ga4a82bb0ee
```

Which IMO makes perfect sense -- typically, the `.0` release will be a direct commit off master (that's kind of the point of master, after all), and the `.1`, `.2`, etc releases are divergent branches from master.

**Comment by tianon** [comment]
(for `go.mod` purposes, these will likely all be marked with `+incompatible` anyways since they won't be using the versioned import paths)

**Comment by thaJeztah** [comment]
> Which IMO makes perfect sense -- typically, the .0 release will be a direct commit off master (that's kind of the point of master, after all), and the .1, .2, etc releases are divergent branches from master.

Yes, but (IIUC) currently also the problem with `go mod`, as it doesn't like tags only being on release branches

**Pull request closed without merging**
