### PR TITLE
logger: remove logentries driver

### PR DESCRIPTION
**Pull request by neersighted**
**- What I did**
Remove the Logentries (SaaS) log driver from the project, as the service will be discontinued on November 15, 2022:

> Dear Logentries user,
>
> We have identified you as the owner of, or collaborator of, a Logentries account.
>
> The Logentries service will be discontinued on November 15th, 2022. This means that your Logentries account access will be removed and all your log data will be permanently deleted on this date.
>
> Next Steps
> If you are interested in an alternative Rapid7 log management solution, InsightOps will be available for purchase through December 16th, 2022. Please note, there is no support to migrate your existing Logentries account to InsightOps.
>
> Thank you for being a valued user of Logentries.
>
> Thank you,
> Rapid7 Customer Success

**- How I did it**
:fire:

**- How to verify it**
CI :green_circle:

**- Description for the changelog**
Remove the Logentries logdriver as the service has been shut down.

**- A picture of a cute animal (not mandatory but encouraged)**
Fat Rat

### CODE REVIEW

**Comment by neersighted** [comment]
:+1:, a graceful migration seems at least worth exploring; I'll do so in this PR.

**Comment by AkihiroSuda** [comment]
Needs rebase

> Remove the Logentries (SaaS) log driver from the project, as the service will be discontinued on November 15, 2022.

Is there a source about this?
Can't find the information on https://logentries.com/ .
(Most links there are already 404 though)

**Comment by neersighted** [comment]
I need to rebase this yes, but I also need to see about adding some graceful migration code to move restored containers to the current default driver (discussed in a past maintainer's call).

As to Rapid7 discontinuing the Logentries SaaS product, see the commit message for the email I was sent, as a user.

**Comment by thaJeztah** [comment]
carried in;

- https://github.com/moby/moby/pull/46926
- https://github.com/moby/moby/pull/46925

**Pull request closed without merging**
