### PR TITLE
daemon: update ImageGetCached to use Graph().ByParent()

### PR DESCRIPTION
**Pull request by proppy**
Also adding tests, let me know if there is a better way than mocking out the graphdriver like I do here.

### CODE REVIEW

**Comment by tiborvass** [comment]
@proppy you have many failures :S

**Comment by proppy** [comment]
@tiborvass yes, I'll gave it a look next time I get a chance.

Feel free to close it if that's in the way.

**Comment by tiborvass** [comment]
@proppy feel free to close it that way you can reopen it when you're ready!

**Comment by proppy** [comment]
closing will re-open when ready :)

**Pull request closed without merging**
