### PR TITLE
Bump spf13/cobra to v0.0.3, pflag to v1.0.1

### PR DESCRIPTION
**Pull request by thaJeztah**
Use a tagged release of Cobra. All relevant PR's were merged, so the fork is
no longer needed.

https://github.com/spf13/cobra/compare/7b2c5ac9fc04fc5efafb60700713d4fa609b777b...v0.0.3

Relevant changes:

- spf13/cobra#552 Add a field to disable [flags] in UseLine()
- spf13/cobra#567 Add `CalledAs` method to cobra.Command
- spf13/cobra#580 Update error message for missing required flags
- spf13/cobra#584 Add support for --version flag
- spf13/cobra#614 If user has a project in symlink, just use its destination folder and work there
- spf13/cobra#649 terminates the flags when -- is found in commandline
- spf13/cobra#662 Add support for ignoring parse errors
- spf13/cobra#686 doc: hide hidden parent flags

Also various improvements were added for generating Bash
completion scripts (currently not used by us)

Fixes usage output for dockerd;

Before this update:

    dockerd --help

    Usage:	dockerd COMMAND

    A self-sufficient runtime for containers.

After this update:

    dockerd --help

    Usage:	dockerd [OPTIONS] [flags]

    A self-sufficient runtime for containers.

### Bump spf13/pflag to v1.0.1

https://github.com/spf13/pflag/compare/97afa5e7ca8a08a383cb259e06636b5e2cc7897f...v1.0.1

Relevant changes:

- spf13/pflag#106 allow lookup by shorthand
- spf13/pflag#113 Add SortFlags option
- spf13/pflag#138 Generate flag error output for errors returned from the parseFunc
- spf13/pflag#141 Fixing Count flag usage string
- spf13/pflag#143 add int16 flag
- spf13/pflag#122 DurationSlice: implementation and tests
- spf13/pflag#115 Implement BytesHex type of argument
- spf13/pflag#150 Add uintSlice and boolSlice to name prettifier
- spf13/pflag#155 Add multiline wrapping support
- spf13/pflag#158 doc: clarify difference between string slice vs. array
- spf13/pflag#160 add ability to ignore unknown flags
- spf13/pflag#163 Allow Users To Show Deprecated Flags

### Hide [flags] in usage output

Hides the [flags] in the usage output of commands (present in newer
versions of Cobra), using the `.DisableFlagsInUseLine` option.

Before this change:

    dockerd --help

    Usage:	dockerd [OPTIONS] [flags]

    A self-sufficient runtime for containers.

After this change:

    dockerd --help

    Usage:	dockerd [OPTIONS]

    A self-sufficient runtime for containers.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Janky https://jenkins.dockerproject.org/job/Docker-PRs/49493/console is failing on a flaky test (https://github.com/moby/moby/issues/32673)

```
02:47:16 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
02:47:16 
02:47:16 [d6f467bb9f2d8] waiting for daemon to start
02:47:16 [d6f467bb9f2d8] daemon started
02:47:16 
02:47:16 [da904da1ba566] waiting for daemon to start
02:47:16 [da904da1ba566] daemon started
02:47:16 
02:47:16 [d99314c8d1b6d] waiting for daemon to start
02:47:16 [d99314c8d1b6d] daemon started
02:47:16 
02:47:16 [d6f467bb9f2d8] exiting daemon
02:47:16 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
02:47:16 [da904da1ba566] exiting daemon
02:47:16 [d99314c8d1b6d] exiting daemon
```

PowerPC https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/9920/console as well, but different test (https://github.com/moby/moby/issues/33041)

```
03:08:15 FAIL: docker_cli_swarm_test.go:1372: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
03:08:15 
03:08:15 [dfead4008b72e] waiting for daemon to start
03:08:15 [dfead4008b72e] daemon started
03:08:15 
03:08:15 [de4c4ad13eeaf] waiting for daemon to start
03:08:15 [de4c4ad13eeaf] daemon started
03:08:15 
03:08:15 [d30249e346d26] waiting for daemon to start
03:08:15 [d30249e346d26] daemon started
03:08:15 
03:08:15 [de4c4ad13eeaf] exiting daemon
03:08:15 [de4c4ad13eeaf] waiting for daemon to start
03:08:15 [de4c4ad13eeaf] daemon started
03:08:15 
03:08:15 [d30249e346d26] exiting daemon
03:08:15 [d30249e346d26] waiting for daemon to start
03:08:15 [d30249e346d26] daemon started
03:08:15 
03:08:15 docker_cli_swarm_test.go:1449:
03:08:15     c.Assert(err, checker.IsNil)
03:08:15 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc423fc6260), Stderr:[]uint8(nil)} ("exit status 1")
03:08:15 
03:08:15 [dfead4008b72e] exiting daemon
03:08:15 [de4c4ad13eeaf] exiting daemon
03:08:15 [d30249e346d26] exiting daemon
```

**Comment by thaJeztah** [comment]
Hm...failure on PowerPC; https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/9921/console

I see this failed on some other runs, e.g. https://github.com/moby/moby/pull/36511#issuecomment-382216564 - looks like flaky

```
11:31:27 FAIL: docker_api_containers_test.go:435: DockerSuite.TestContainerAPITop
11:31:27 
11:31:27 docker_api_containers_test.go:453:
11:31:27     c.Assert(top.Processes[0][10], checker.Equals, "/bin/sh -c top")
11:31:27 ... obtained string = "top"
11:31:27 ... expected string = "/bin/sh -c top"
11:31:27 
```

**Comment by thaJeztah** [comment]
this is green now; @dnephin @vdemeester

**Review by boaz0 — APPROVED** [review]
LGTM :+1:

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
