### PR TITLE
Improve deprecation messages and message for "commit --run"

### PR DESCRIPTION
**Pull request by thaJeztah**
This implements "see other" flags for deprecation messages, which allows a "replacement" flag to refer to another flag that is defined separately.

Before this change, the "replacement" flag could only be part of the same flag definitions, which made it impossible to output a deprecation message for flags that were replaced with another flag.

The "see other" replacement flags can be set by prefixing the flag-name with '@' and are ignored as an actual
flag.

In addition the deprecation warning for `docker commit --run` was improved (using the feature above) to give a hint for the new `--change` flag.

Before this change;

```
Warning: '--run' is deprecated, it will be removed soon. See usage.
```

After:

```
Warning: '--run' is deprecated, it will be replaced by '--change' soon. See usage.
```

relates to: https://github.com/docker/docker/issues/9525#issuecomment-77700372

**notes**
- I wasn't sure if these changes should be created as two separate pull-requests, I kept them as two commits, but let me know if you want them to be split to two pull-requests.
- It's my first "playing around" with the code. Probably lots of improvements to be made; hit me!
- Attempted to add some tests, but open to suggestions :)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh, shucks. Looks like I messed up something (tests ran on my machine), will keep open, but check tomorrow.

**Comment by crosbymichael** [comment]
ping @vieux for mflag change

**Comment by icecrime** [comment]
Ping @thaJeztah: any news on this? Thanks!

**Comment by thaJeztah** [comment]
@icecrime hm, good one, I actually haven't looked into this, will need to make some time.

Do you want me to close it for now to keep the PRs down?

(Some feedback from @vieux would still be nice, this was my first fiddling with Go, it feels a bit hacky, but if it's an acceptable approach, I'll pick it up again)

**Comment by icecrime** [comment]
Truth is, it's gonna be a pain to rebase anyway (because `api/client/commands.go` was split in many little files), so yes I'd rather close this so we can start fresh :-)

**Comment by thaJeztah** [comment]
Yep, I noticed, and didn't have much "computer time" recently to work on decent PRs

Will close and see if I can come up with something decent! Thx!

**Pull request closed without merging**
