### PR TITLE
added re-directs for cloud install docs as clean-up for  #18282

### PR DESCRIPTION
**Pull request by londoncalling**
Signed-off-by: Victoria Bialas victoria.bialas@docker.com

### CODE REVIEW

**Comment by londoncalling** [comment]
Added redirects for docs on cloud installs of Docker Engine that were removed per issue #18282. Cloud-specific install instructions for amazon, google, ibm softlayer, azure, rackspace, and joyent now redirect to cloud.md "Understand cloud install options and choose one". I'll add a link here to draft Docs on Digital Ocean to for you to test the re-directs. Please review, and let me know if I can merge this.

**Comment by londoncalling** [comment]
merging this, will provide link to drafts for your review

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by thaJeztah** [comment]
ping @moxiegirl for review/merge

**Comment by moxiegirl** [comment]
LGTM Thanks V!

**Comment by londoncalling** [comment]
Yay! Thanks!

**Pull request merged**
