### PR TITLE
Windows: reexec during layer import

### LINKED ISSUE #22404: Unable to pull images on Windows Server 2016 TP5
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1010.amd64fre.rs1_release_svc.160415-2143)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 4 GiB
Name: WIN-LLLQ675JB3A
ID: VSVH:X5U3:FUA4:6BJ5:3OK2:FTCV:QZVB:GXCW:4CBQ:FEGG:VDDI:KMPS
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows Server 2016 TP5 running in VMWare Workstation 9 

**Steps to reproduce the issue:**
1. Follow [instructions](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment) for installation
2. docker pull microsoft/dotnet35:latest

**Describe the results you received:**
latest: Pulling from microsoft/dotnet35

1cf51c47c298: Extracting [==================================================>] 72.03 MB/72.03 MB
849b9bdf7071: Download complete
failed to register layer: convert O:BAG:DUD:(A;OICI;0x1200a9;;;S-1-5-83-0)(A;OICI;FA;;;BA)(A;OICI;FA;;;SY)(A;;FA;;;BA)(A;OICIIO;GA;;;CO)(A;OICI;0x1200a9;;;BU)(A;CI;LC;;;BU)(A;CI;DC;;;BU): The security ID structure is invalid.

**Describe the results you expected:**
docker image to be pulled down

**Additional information you deem important (e.g. issue happens only occasionally):**
cant seem to pull any docker image from docker hub. also cant build any image using docker build on windows

### PR DESCRIPTION
**Pull request by jstarks**
This improves reliability by doing parsing of potentially untrusted data
in a separate process. It opens the door for further security improvements
if we can lock down the reexec-ed process. It also improves import
performance by only taking the backup and restore privileges once, for the
whole process.

This requires a revendor of go-winio, which also fixes #22404 for new images,
without requiring the workaround of producing images only on non-domain joined
machines.

cc @swernli, @jhowardmsft

### CODE REVIEW

**Comment by swernli** [comment]
LGTM.

**Comment by LK4D4** [comment]
@jstarks some wild test failures on CI :/

**Comment by jstarks** [comment]
Whoa. Looks like I managed to trigger a latent bug in Diff() with my changes. I pushed a fix, hopefully it goes better this time.

**Comment by jstarks** [comment]
Could someone restart win2lin? Looks unrelated to my changes.

**Comment by thaJeztah** [comment]
restarted

**Comment by tonistiigi** [comment]
LGTM

**Comment by jhowardmsft** [comment]
LGTM. Merging.

**Pull request merged**
