### PR TITLE
fix for issue #6809

### PR DESCRIPTION
**Pull request by justyntemme**
Fix was suggested in the issue ticket

Signed-off-by: Justyn Temme Justyntemme@gmail.com

Fixes ##6809.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon PTAL, I see you had some concerns on the original issue; https://github.com/docker/docker/issues/6809#issuecomment-49204165

**Comment by tianon** [comment]
@thaJeztah I think time has shown that "cross-yumming" isn't really a goal that's a high-priority for anyone (and we don't currently support it so this can't really be a regression either) :cry:

thus, this LGTM

**Comment by thaJeztah** [comment]
ping @kencochrane @mlaventure ptal

**Comment by mlaventure** [comment]
Unfortunately I don't know much about how the rpm platform works, so I'll abstain :)

**Comment by kencochrane** [comment]
Is there a simple manual test case I can run, to make sure it works? I read the linked comment and it didn't really help.

**Comment by LK4D4** [comment]
ping @justyntemme

**Comment by justyntemme** [comment]
Not knowledgeable on the subject enough to make a educated comment. Was simply issuing a pr based on the comment in the issue. 

However i would think a simple test would be to create both a x32 and x64 Fedora docker container. I could probably do this today or tomorrow depending on free time.

**Comment by kencochrane** [comment]
@justyntemme thank you, let us know what you find out.

**Comment by justyntemme** [comment]
Sorry for the delay, time has been something i don't have a lot of recently. Eating my dogfood and learning docker to put in production. I will report back this will NOT be abandoned.

**Comment by cpuguy83** [comment]
Any news?

**Comment by justyntemme** [comment]
So There was some issues when researching for a test case i could use, i have gained a small grasp of docker and actually started using it with website deployment, however i can not find an already build 32 bit fedora/centos docker image or build script to use to test. I have everything ready to make sure it's working just don't know how to build that image. If someone can point me in the right direction i would love to continue work on this.

**Comment by thaJeztah** [comment]
@tianon do you have any ideas up your magic sleeve? ^^

**Comment by tianon** [comment]
I don't know of anything official for Fedora/CentOS -- Fedora publishes official tarballs (https://getfedora.org/en/cloud/download/docker.html), but http://fedora.mirror.lstn.net/releases/24/Docker/ doesn't have 32bit (only `x86_64` and `armhfp`). :disappointed:

**Comment by andrewhsu** [comment]
The `/etc/rpm/platform` file really ought not to be assumed to be in the host operating system.

```
$ sudo ./mkimage-yum.sh test
...
+ cp /etc/rpm/platform /tmp/mkimage-yum.sh.2HtGA3/etc/rpm/platform
cp: cannot stat ‘/etc/rpm/platform’: No such file or directory
```

A clean install of CentOS 7 does not have that file.

I have put a comment in #6809 to get an understanding on the original desire for the change.

**Comment by thaJeztah** [comment]
per the discussion on https://github.com/docker/docker/issues/6809#issuecomment-257385733, I think it's best to close this PR. There's too many uncertainties here for a very narrow use case.

Thanks so much for doing the work on this @justyntemme! I'm sorry we're closing your PR, but that doesn't mean it's not appreciated! :heart:

**Pull request closed without merging**
