### PR TITLE
Windows: Refactor pkg\plugins

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

I was going through still trying to get test-unit running on Windows when I stumbled across the plugins package which was erroring out. This is very Unix specific in implementation, so I ended up refactoring it to have the minimal pieces needed to compile docker on Windows. It was slightly complicated by the fact that libnetwork relies on certain structures, functions and variables exported by this package. I have put some TODO Windows where with some libnetwork refactoring and revendor, these can also be moved to _unix files.

### CODE REVIEW

**Comment by LK4D4** [comment]
@jhowardmsft experimental fail is related

**Comment by jhowardmsft** [comment]
@LK4D4 Huh! Thanks. Investigating...

**Comment by jhowardmsft** [comment]
@LK4D4 Yeah, was an easy fix. A couple of no-op methods were missing for graphdriver plugins present in experimental. Added "build Windows experimental" to my list of checks before PR submission! And hopefully I'll remember to run it!

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
@jhowardmsft is this for TP4?

**Comment by jhowardmsft** [comment]
Just a general change

**Comment by LK4D4** [comment]
I'm not sure, plugins should work on windows as well(it's just HTTP). @jhowardmsft Could you point me to unix-specific details there?

**Comment by calavera** [comment]
Plugins work over http. This is not a unix only feature. This does not LGTM.

**Comment by jhowardmsft** [comment]
Hmmm. Closing and will revisit.

**Pull request closed without merging**
