### PR TITLE
added albatros library

### PR DESCRIPTION
**Pull request by dcylabs**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@dcylabs Can you sign off your commit, using the instructions that @GordonTheTurtle gave above?

**Comment by dcylabs** [comment]
@thaJeztah Sure, just signed off

**Comment by thaJeztah** [comment]
Thanks!

LGTM

ping @moxiegirl @SvenDowideit @jamtur01

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
