### PR TITLE
Removing TODO in pkg/term/windows

### PR DESCRIPTION
**Pull request by mqliang**
Removing TODO in pkg/term/windows

Signed-off-by: mqliang mqliang.zju@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
Hi @mqliang,

Thanks for the PR. Could you rename it (and probably the comment message) to something more meaninful, like "Removing TODO in pkg/term/windows" or something like that.

**Comment by runcom** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
Not tested but looks OK. Think this is Ahmets code though, so ping @ahmetalpbalkan

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM

**Comment by thaJeztah** [comment]
moved to "merge", but let me know if you think @ahmetalpbalkan should still have a look

**Comment by jhowardmsft** [comment]
I think we're good. LGTM

**Comment by ahmetalpbalkan** [comment]
heh not my code but @jstarks would know

**Comment by vdemeester** [comment]
Windows is green, pretty sure we're ok then, merging :sweat_smile:

**Pull request merged**
