### PR TITLE
add status code 400 for update endpoints in swagger.yml

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

I think in docker/master we should add status code 400 for endpoint node update and secret update.

First pic is for node update.
wechatimg1
I test docker 1.12.x, 

Second pic is for secret update:
wechatimg2

**- What I did**
1. add status code 400 for endpoint `POST /node/{id}/update`;
2. add status code 400 for endpoint `POST /secret/{id}/update`;

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by allencloud** [comment]
ping @vdemeester @thaJeztah

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by thaJeztah** [comment]
oh, ugh, I was about to comment but was in the airplane already; discussing with @justincormack, but this 400 should probably be a 404 given that the requested resource doesn't exist?

**Pull request merged**
