### PR TITLE
fix a few golint errors

### PR DESCRIPTION
**Pull request by vieux**
ping @tonistiigi @aluzzardi

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by tonistiigi** [comment]
@vieux That dot removal broke a test

**Comment by aluzzardi** [comment]
LGTM

**Comment by aluzzardi** [comment]
```
00:52:55 FAIL: docker_cli_help_test.go:145: DockerSuite.TestHelpExitCodesHelpOutput
00:52:55 
00:52:55 docker_cli_help_test.go:199:
00:52:55     c.Assert(stderr, checker.Equals, "docker: 'BadCmd' is not a docker command.\nSee 'docker --help'.\n", check.Commentf("Unexcepted output for 'docker badCmd'\n"))
00:52:55 ... obtained string = "" +
00:52:55 ...     "docker: 'BadCmd' is not a docker command.\n" +
00:52:55 ...     "See 'docker --help'\n"
00:52:55 ... expected string = "" +
00:52:55 ...     "docker: 'BadCmd' is not a docker command.\n" +
00:52:55 ...     "See 'docker --help'.\n"
00:52:55 ... Unexcepted output for 'docker badCmd'
```

**Comment by vieux** [comment]
@aluzzardi PTAL

**Comment by aluzzardi** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
