### PR TITLE
Add exec event log

### PR DESCRIPTION
**Pull request by daehyeok**
added exec event log follwing issue #8662 proposal

Signed-off-by: Daehyeok.Mun daehyeok@gmail.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@daehyeok could you rebase pls? then we'll merge

**Comment by daehyeok** [comment]
rebase completed.

**Comment by LK4D4** [comment]
LGTM

**Comment by vieux** [comment]
I forgot, we probably want an `exec_die`

**Pull request merged**
