### PR TITLE
Fixes Issue # 23589: enable dm.use_deferred_removal and dm.use_deferred_deletion by default.

### LINKED ISSUE #23589: [RFE] Enable devicemapper storage options (dm.use_deferred_removal and dm.use_deferred_deletion) by default.
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.5.1
 Git commit:   5955835-unsupported
 Built:        Wed Jun 15 15:49:47 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.5.1
 Git commit:   5955835-unsupported
 Built:        Wed Jun 15 15:49:47 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121929-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 265.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 696.3 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: default
Default Runtime: default
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
[RFE]
Since docker has done changes in their systemd unit file to run docker daemon in host namespace by default. That means lot of leaking of mounts across namespaces and that also means lot more need to enable deferred deletion and deferred removal by default.

With these options (dm.use_deferred_removal and dm.use_deferred_deletion) enabled by default, users will not see any errors in operations like exiting the container shell, rm, rmi etc. since thin devices removal and deletion would automatically be deferred, in case of conflicts.

**Describe the results you received:**

N/A

**Describe the results you expected:**

Starting docker daemon (dockerd) would automatically enable these options.

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes #23589 

Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
What this patch does is:

1) If the user start `dockerd` without passing these options, `dm.use_deferred_removal` and `dm.use_deferred_deletion` would be enabled by default.
    ---> If these options are not supported by kernel or libdm, we will only log a warning message to daemon and not blow up. i.e we ll start the daemon, since user did not pass these options. We don't want daemon to blow up on different linux distros, just because these options are not supported, and user did not explicitly passed these options.

2) If the user start dockerd by explicitly passing these options: 
```
dockerd --storage-opt dm.use_deferred_removal=true dm.use_deferred_deletion=true
```. 
It will enable these options just the way it does today.
    ----> if these options are not supported by kernel or libdm, we will throw an error and stop the daemon     start, Just the way it does today. The user will  assume responsibility for passing these options.

Shishir

**Comment by shishir-a412ed** [comment]
ping @thaJeztah @rhvgoyal

**Comment by rhvgoyal** [comment]
If somebody is running docker daemon in host mount namespace they need to enable deferred removal and deferred deletion otherwise expect lot of errors of device being busy.

Now even docker upstream has changed their systemd unit file to run daemon in host mount namespace. So it makes sense to enable this feature by default.

When daemon is running in host namespace, it is really easy to lean container mount points into other namespaces. Run a container and just do "unshare -m bash" and now tried to exit that container and it will fail. Enable deferred device removal and container exit will succeed. Mount point still has leaked but once the original bash shell exits, device will be cleaned up.

**Comment by shishir-a412ed** [comment]
@thaJeztah any updates on this one ?

**Comment by cpuguy83** [comment]
What's the side-effects of making this the default? Why did we provide the option to begin with rather than just turning it on?

**Comment by shishir-a412ed** [comment]
@cpuguy83 
The side effects of making this the default is less errors :)
Everytime user tries to exit a container, when the mount point is leaked. `dm.use_deferred_removal` and `dm.use_deferred_deletion` will defer the device removal and deletion, and the user will be able to exit the container without any errors.

I am not 100% sure why we @rhvgoyal made this an option to begin with. But my best guess would be there were not too many errors related to this initially. Now that docker daemon is running in host mount namespace, you will see a lot of mount points leaked and hence a lot of errors on container exit. I guess enabling these options by default will provide a better user experience, rather than user getting an error everytime he/she exits the container.

**Comment by cpuguy83** [comment]
But there must be negative trade-offs otherwise it should not have been optional.

**Comment by shishir-a412ed** [comment]
@cpuguy83 
ping @rhvgoyal he would be the best person to answer this.

**Comment by rhvgoyal** [comment]
@cpuguy83 It was just defensive programming. This was so new feature, I kept it off by default. Wanted to first see if it works reasonably well or not. 

Having said that, we have figured out a kernel issue with older kernels and that breaks deferred deletion. Upstream and newer kernels don't have that issue.

So deferred removal we can enable by default and I think we might have to put some smart checks to figure out if deferred deletion works well on this kernel or not and if it does, then enable it.

**Comment by rhvgoyal** [comment]
Here is the issue I am talking about.
Do following.
- mkdir foo
- mount --bind foo foo
- In separate terminal window do "unshare -m bash"
- In original terminal window "umount foo"
- rmdir foo

This last step succeeds with upstream and fedora kernels but fails on centos kernel with message device is busy.

What this means is that when container deletion happens, it will try to remove container rootfs dir and if that directory is still mounted on in another namespace then container deletion will fail. 

Shishir, is it possible to put a check during initialization to test this and enable deferred deletion accordingly?

**Comment by thaJeztah** [comment]
ping @shishir-a412ed @rhvgoyal what's the status on this one?

**Comment by shishir-a412ed** [comment]
@thaJeztah 

What @rhvgoyal mentioned in the above comment (https://github.com/docker/docker/pull/23590#issuecomment-228814790), the problem here is `deferred deletion` is only supported on upstream and fedora kernels, but fails on some kernels like centos. 

I discussed this with him, and we feel it would be a bit hard to check at runtime if `deferred deletion` is supported by the underlying kernel. If YES, then only we enable `dm.use_deferred_deletion` option in docker daemon. 

Open to suggestions on how to fix this.

Shishir

**Comment by thaJeztah** [comment]
@shishir-a412ed would it produce an error that we can detect, and would be able to fall back if it's not supported?

**Comment by rhvgoyal** [comment]
@thaJeztah We can fall back to deferred deletion being off by default if we have the capability to determine what's the kernel behavior. I think we will have to write some dynamic check in docker daemon to determine following.

- Create a dir
- Bind mount that dir onto itself
- Create another mount namespace so that this mount point leaks into that mount namespace.
- Unmount dir from oringal mount namespace
- Try to delete dir in original mount namespace.

If that dir removal succeeds, that means kernel is new enough to support dir removal even if dir is a mount point in some other namespace. Otherwise not. And that will determine whether deferred deletion should be enabled by default or not.

**Comment by thaJeztah** [comment]
@rhvgoyal that sounds like adding a lot of complexity :cry:

**Comment by rhvgoyal** [comment]
@thaJeztah yep, it is not very simple and right now I can't think what's the other possible method.

**Comment by thaJeztah** [comment]
Was thinking if it's a packaging issue (i.e., set those defaults in a systemd-drop-in file), but not sure we want to go that path 😞

**Comment by shishir-a412ed** [comment]
I have implemented a C program 
https://github.com/shishir-a412ed/Algorithms/blob/master/src/deferredDeletion.c
that checks if deferred deletion is supported by the underlying kernel or not. 

We can call this in Cgo or exec the binary. and based on the response if deferred deletion is supported by the underlying kernel, we can enable it by default. 

@thaJeztah @cpuguy83 WDYT ?

Shishir

**Comment by estesp** [comment]
During the maintainers review meeting we discussed this issue of devicemapper config/setup. It seems that already there are a significant number of setup steps that are going to remain manual for a truly proper devicemapper setup.  The only out of the box capability the daemon has is to use loopback which we all know is strongly discouraged except for simple local test/dev where data loss/performance are not a consideration.

Given all that, and adding the apparent complexity of trying to "query" the system's capabilities (e.g. requiring another binary that has to be maintained), it's hard to see a strong need to add this complexity given a real use of devicemapper will already require understanding the docs, creating the right disk configuration, and selecting the startup parameters appropriate for the system being configured.

Is it possible this test tool could be made available and added to the docs for easy configuration for an admin who doesn't want to go understand the kernel and libdm versioning manually as an alternative?

I know in IBM where we have some heavy use of devicemapper this would not have solved our DM configuration issues as testing showed that we actually had backlevel versions of libdm that didn't support deferred removal, so auto-setting the capability would not have helped.

**Comment by rhatdan** [comment]
Can we test this outside of docker and setup the systemd unit file to do it properly, or use docker-storage-setup to figure out whether the flag should be set?

**Comment by shishir-a412ed** [comment]
@estesp 
I agree, the devicemapper setup is quite complex and would always require the admin to do manual steps and go through the docs. So that he can not only just get the right configuration, but also the configuration that is right for him/her.

The main idea to enable `dm.use_deferred_removal` and `dm.use_deferred_deletion` be default was to minimize errors users were facing. But we later realized that `deferred deletion` is not supported by all the kernels, hence a way to detect whether it is supported or not came out as a natural requirement.

Let me know what do you think of this (This is somewhat similar to what you are suggesting)

1) Host the test tool (https://github.com/shishir-a412ed/Algorithms/blob/master/src/deferredDeletion.c) in a separate github repository.
2) Update the docker docs to point to that repository link. What the docs would say:
    a) Docs should explain the problem Statement: 
        If a user is running docker daemon in host mount namespace, there is a high probability that container rootfs mount points can get leaked into another mount namespace. Which means if he tries to do `docker rm $ContainerID` he might get an error device busy.

   b) Docs should propose a solution:
       To avoid this error the user can enable these options (dm.use_deferred_removal and dm.use_deferred_deletion) at daemon start time. However deferred_deletion is not supported by all kernels so he can use this tool to first detect whether his kernel support this functionality or not.

  c) If this tool returns TRUE (0 error code) then docs should tell how to enable these options.

WDYT ?
Shishir

**Comment by shishir-a412ed** [comment]
Closing this PR, as we have handled this in docker-storage-setup (d-s-s).

Shishir

**Pull request closed without merging**
