### PR TITLE
update containerd binary to v1.4.0

### PR DESCRIPTION
**Pull request by AkihiroSuda**
release note: https://github.com/containerd/containerd/releases/tag/v1.4.0

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
```
[2020-05-17T10:31:49.109Z] #43 [gotestsum 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     ...

[2020-05-17T10:31:49.109Z] #43 25.96 + cd /tmp/tmp.ho6yonV5RT/src/gotest.tools/gotestsum

[2020-05-17T10:31:49.109Z] #43 25.96 + git checkout -q v0.3.5

[2020-05-17T10:31:49.109Z] #43 25.98 + go build -buildmode=pie -o /build/gotestsum gotest.tools/gotestsum

[2020-05-17T10:31:49.109Z] #43 26.22 handler.go:8:2: cannot find package "github.com/sirupsen/logrus" in any of:

[2020-05-17T10:31:49.109Z] #43 26.22 	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)

[2020-05-17T10:31:49.109Z] #43 26.22 	/tmp/tmp.ho6yonV5RT/src/github.com/sirupsen/logrus (from $GOPATH)

[2020-05-17T10:31:49.685Z] #43 ERROR: executor failed running [/bin/sh -c PREFIX=/build /tmp/install/install.sh gotestsum]: runc did not terminate sucessfully
```

https://github.com/moby/moby/pull/40979 should fix CI failure

**Comment by tianon** [comment]
Do you think we should leave this as a draft until 1.4.0 GA? (not sure we want master depending on a pre-release, especially while prepping for a release :sweat_smile:)

**Comment by AkihiroSuda** [comment]
If 20.0X GA is planned to be released after containerd 1.4 GA, we should merge this, otherwise we should not.
My understanding is the former one.
cc @cpuguy83 @thaJeztah

**Comment by AkihiroSuda** [comment]
@cpuguy83 @thaJeztah PTAL

**Comment by thaJeztah** [comment]
Discussing in the maintainers meeting, and we're leaning towards (at least initially) shipping 20.0x with containerd 1.3.x, with the option to later go to 1.4.x. Given that 1.3.x has had some time to mature (less risky)

**Comment by AkihiroSuda** [comment]
@thaJeztah When is the ETA of 20.03? 
Given than 19.03 required more than 3 months since beta1 to GA and we haven't reached 20.03 beta1 yet, I predict ETA of 20.03 GA to be around September or maybe October. containerd 1.4 is highly likely to be matured enough at that time.

Also, supporting cgroup2 (i.e. containerd 1.4) from the beginning of 20.03.0 would be good to shut up "Docker/Moby will never support cgroup2" hoax.

**Comment by AkihiroSuda** [comment]
@thaJeztah @tianon @cpuguy83 

We are still not ready to release v20.0x soon: https://github.com/moby/moby/issues/40838
Any chance to get this PR reconsidered to be included for v20.0X?

**Comment by AkihiroSuda** [comment]
updated to beta2

**Comment by AkihiroSuda** [comment]
updated to rc.0

**Comment by AkihiroSuda** [comment]
updated to rc.1

**Comment by AkihiroSuda** [comment]
Updated to v1.4.0 GA.

I still think Docker 20.XX should skip containerd 1.3 and use 1.4  from the beginning.

containerd 1.3 is likely to reach [EOL (February 17, 2021)](https://github.com/containerd/containerd/blob/v1.4.0/RELEASES.md#support-horizon) right after (or before, in the worst case) the release of Docker 20.XX .

@thaJeztah @cpuguy83 @tianon PTAL

**Comment by cpuguy83** [comment]
I agree.

The main concern is that docker-ce 19.03 will be required to update to containerd 1.4 (for new installs) unless people manually specify the containerd version when installing docker.
Having release specific channels for this would help.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Discussing in the maintainers meeting with @cpuguy83 @tonistiigi, and we think we can start updating docker 19.03 to containerd 1.3, then start alphas/betas for docker 20.0x with containerd 1.4 on the test channels.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Note that `io.containerd.runtime.v1.linux` has issues on 1.4.0, specifically with `exec` requests filling up log pipes from the shim which are never consumed, and thus eventually block the shim: https://github.com/containerd/containerd/pull/4546

**Pull request merged**
