### PR TITLE
Fix the unnecessary parameter

### PR DESCRIPTION
**Pull request by HackToday**
Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
Nice catch! Can you also update the v1.22 docs? I see the same mistake is in that one; https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md

**Comment by HackToday** [comment]
ping @thaJeztah  PTAL Thanks

**Comment by thaJeztah** [comment]
Awesome, thanks!

LGTM

**Pull request merged**
