### PR TITLE
service ps: Revert output to 1.12 behavior.

### PR DESCRIPTION
**Pull request by aluzzardi**
- Display the ID column
- Do not append the task ID in the name column
- (NEW): Truncate task IDs, unless --no-trunc is specified

Example:
```
root@5db063ff62a2:/go/src/github.com/docker/docker# docker service ps redis
ID            NAME          IMAGE         NODE          DESIRED STATE  CURRENT STATE            ERROR  PORTS
b2xvb8bkbfaj  redis.1       redis:latest  5db063ff62a2  Running        Running 40 seconds ago
3rxx3lrjuz6o   \_ redis.1   redis:latest  5db063ff62a2  Shutdown       Complete 50 seconds ago

root@5db063ff62a2:/go/src/github.com/docker/docker# docker service ps --no-trunc redis
ID                         NAME          IMAGE                                                                                 NODE          DESIRED STATE  CURRENT STATE           ERROR  PORTS
b2xvb8bkbfaje3h6viln9y9hw  redis.1       redis:latest@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673  5db063ff62a2  Running        Running 3 minutes ago
3rxx3lrjuz6ovmq7e6wcvxvyj   \_ redis.1   redis:latest@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673  5db063ff62a2  Shutdown       Complete 3 minutes ago
```

/cc @vieux @aaronlehmann @thaJeztah @icecrime

### CODE REVIEW

**Comment by aaronlehmann** [comment]
ping @yongtang

**Comment by allencloud** [comment]
I like this PR's concept. Mixed several things in the `NAME` column will confuse users:
```
root@ubuntu:~# docker service ps zf
NAME                            IMAGE   NODE    DESIRED STATE  CURRENT STATE          ERROR  PORTS
hungry_sinoussi.1.hsphe3flrrbj  alpine  ubuntu  Running        Running 6 seconds ago
```

I hope to use `docker inspect task_id` to get task details, I have no idea to get the task ID at the first time, since output gave a Name which seems not a true name.

**Comment by thaJeztah** [comment]
I think this addresses https://github.com/docker/docker/issues/28430, correct @mstanleyjones ?

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by yongtang** [comment]
The task name was assigned as `<e.ServiceAnnotations.Name>.<Slot>.<TaskID>` in https://github.com/docker/swarmkit/pull/1193
and assigned as `<e.ServiceAnnotations.Name>.<NodeID>.<TaskID>` for global mode in https://github.com/docker/swarmkit/pull/1476
Related changes also includes: https://github.com/docker/docker/pull/27751

I am wondering if we display task name as `<e.ServiceAnnotations.Name>.<Slot>` in replicated mode and `<e.ServiceAnnotations.Name>.<NodeID>`, maybe some additional changes are needed in swarmkit and docker as well?

Or we consider the `NAME` in the output of `service ps` to be for "display only" then I think additional changes will not be needed.

/cc @stevvooe

**Comment by stevvooe** [comment]
I still think we need to implement what I said in https://github.com/docker/docker/issues/28430#issuecomment-264039772 to make this useful.

**Comment by thaJeztah** [comment]
@stevvooe @aluzzardi I compared this with 1.12, and docker 1.12 did not truncate the ID. Although I verified that `docker inspect <truncated-id>` works; do we want to fully revert to 1.12 output and never truncate the ID, or is the current implementation sufficient? (I don't think we use `task ID` anywhere else in the CLI?)

**Comment by stevvooe** [comment]
@thaJeztah If we can make `docker inspect <trunacated name>` also work, we don't need to roll back this change.

**Comment by thaJeztah** [comment]
> If we can make docker inspect <trunacated name> also work, we don't need to roll back this change.

@stevvooe we don't support matching on partial names on any command currently, so I'm not sure we should do that this late in the release. If we want to support that, it'll have to be a change for all commands

**Comment by aluzzardi** [comment]
@thaJeztah @stevvooe: Truncated task IDs do work, truncated names are not supported by Docker, tasks don't have names

**Review by thaJeztah — APPROVED** [review]
LGTM

we can further improve in future, but this restores the basic behavior that was there in 1.12

**Pull request merged**
