### PR TITLE
2016.09.08 cherry picks

### PR DESCRIPTION
**Pull request by mdlinville**
@sfsmithcha @SvenDowideit @thaJeztah @vdemeester PTAL. cc @riyazdf

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like https://github.com/docker/docker/pull/26016 (https://github.com/docker/docker/pull/26572/commits/fbf0dd03d27b3f14b5382b5ddae5bd676a1b39b0) shouldn't be in there

**Comment by mstanleyjones** [comment]
@thaJeztah I took it out. Thanks!

**Comment by thaJeztah** [comment]
changes LGTM, *but*, I notice that the API 1.25 docs have found their way into this branch (and because of that are currently published on docs.docker.com). Probably happened in an earlier cherry-pick.

Think we have two option to fix that;
- remove the document from this branch
- add a change that puts the document in "draft" so that it's not visible

let me know if you what you prefer and/or you want to do that in this PR or a separate one :smile:

**Comment by mstanleyjones** [comment]
Can you try to do a git blame and let me know which commit I should pull out? Then I can do it and re-push on this PR. I'm in a meeting or I would try to figure it out myself.

**Comment by mstanleyjones** [comment]
Hmm.... I found the bad commit (88bd4cb0ea26da05bc9507d785b08b4e3162980c) and rebased on its parent, edited the commit and removed the file `docs/reference/api/docker_remote_api_v1.25.md`. I had a conflict to resolve so I did it, then the rebase went cleanly, but now it is saying that I have conflicts to resolve. Do you want to investigate, @thaJeztah ? or shall I?

**Comment by thaJeztah** [comment]
@mstanleyjones if you have time later today (I'm about to head off), that'd be great.

w.r.t. https://github.com/docker/docker/commit/88bd4cb0ea26da05bc9507d785b08b4e3162980c, I think what's usually done is that the file is just manually removed as part of the cherry-pick PR (because the changes in the 1.24 doc can be still relevant).

Perhaps it's easier that we do a separate PR that simply puts the 1.25 doc in "draft" mode, that way we can cherry-pick without having to worry about the 1.25 doc becoming visible online

**Comment by mstanleyjones** [comment]
Wait this commit ended up in the wrong branch. What did I do? Let me see if I can fix this.

**Comment by mstanleyjones** [comment]
Closed in favor of #26603

**Pull request closed without merging**
