### PR TITLE
Deprecate daemon cli and build tag

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This is potentially a scary, hairy, don't-touch-with-a-10-foot-pole type of PR.... I was looking at removing the daemon build tag as it's strictly not necessary to build the daemon anymore being a separate binary. However, the client uses it to still support `docker daemon` to invoke `dockerd` in a hidden CLI option, as per pre 1.11. I believe in 1.13 we can now deprecate that, so the build tag can be completely removed.

I think :scream_cat: I've got everything, but this is going to need a few eyes to be sure. I haven't tested locally either, so CI will be the acid test.  @tianon as this touches files under hack\make. And @icecrime for the deprecation.

Fingers crossed for CI :innocent:

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@thaJeztah Thoughts on deprecation? Thanks.

**Comment by thaJeztah** [comment]
Hm, we extended the default deprecation cycle to _three_ releases, so possibly we need to wait until after 1.13

/cc @dnephin

**Comment by tianon** [comment]
I'm +1, and the changes LGTM too

**Comment by dnephin** [comment]
The problem is that we never deprecated `docker daemon` (it doesn't appear in https://docs.docker.com/engine/deprecated/ and there is no warning on the command). I would have liked to, but there was no support for deprecating it at the time.

We would have to official deprecated it in 1.13, which would allow us to remove it in 1.16.

**Comment by thaJeztah** [comment]
Ow, that's unfortunate :cry:. I think we should indeed mark it deprecated now then (and probably issue a deprecation message if someone uses `docker daemon`?

**Comment by dnephin** [comment]
Yes, I think we should add a warning to say "please use `dockerd` instead of `docker daemon`"

**Comment by jhowardmsft** [comment]
Ok, I'll put together a PR for that and close this one. Perhaps we should have a 1.16 tag already :smile:

**Comment by thaJeztah** [comment]
Yeah, sorry for this @jhowardmsft! I think we all agree that the PR is good, and we'd like to cleanup this stuff as well 👍

**Comment by thaJeztah** [comment]
let me close this PR for now

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker/pull/26834 for deprecating the subcommand

**Pull request closed without merging**
