### PR TITLE
Remove registry redirect

### PR DESCRIPTION
**Pull request by moxiegirl**
... it was causing an infinite redirect.

Signed-off-by: Ben Firshman ben@firshman.co.uk
(cherry picked from commit 4c6d5e3a25557b2a053e8f8e5aafc84f5f6aada8)

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM (if builds go green)

**Comment by moxiegirl** [comment]
@jfrazelle I have no ability to rekick builds --- even so there seems to be an across the board issue with that one hello-world test.  (I'm more concerned about seeing the consistent test failure on multiple prs than this particular pr)  What say you?

**Comment by jfrazelle** [comment]
Seems fine

**Comment by moxiegirl** [comment]
Wah but I want my builds to be green before I merge!

**Comment by jfrazelle** [comment]
I think there's a pr to fix that test

**Comment by thaJeztah** [comment]
The PR was merged, but you'll have to rebase to get it. Forgot about that when I triggered a rebuild this morning :smile:

**Comment by moxiegirl** [comment]
nooooooooooo!

**Comment by thaJeztah** [comment]
:'(

**Pull request closed without merging**
