### PR TITLE
add new kernel flag check

### PR DESCRIPTION
**Pull request by alexchenfeng**
add kernel flag check:   CONFIG_IP_VS_NFCT, CONFIG_NETFILTER_XT_MATCH_IPVS    #26930

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @alexchenfeng. Looks like you forgot to sign off your commit; can you squash your commits, and make sure the sign-off is there? You can find some instructions for squashing in our contributors guide; https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently

**Comment by alexchenfeng** [comment]
@thaJeztah You are welcome, I will add Sign-Off later.

**Comment by cpuguy83** [comment]
Thanks @alexchenfeng. Just FYI we can't review until it's signed off.

**Comment by mrjana** [comment]
@alexchenfeng Please include `CONFIG_IP_VS_RR` as well.

**Comment by alexchenfeng** [comment]
@mrjana IP_VS_RR added

**Comment by alexchenfeng** [comment]
You are welcome, I will fix it later.

**Comment by mavenugo** [comment]
@mrjana @thaJeztah should this be considered for 1.12.2 ?
Also @alexchenfeng pls squash the commits.

**Comment by mrjana** [comment]
Yeah it can be useful and not all that of a risk.

**Comment by justincormack** [comment]
@mavenugo we don't ship this with releases I don't think we normally just point people at the github raw link from master.

**Comment by mrjana** [comment]
@justincormack I thought it is added to deb https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/hack/make/.build-deb/docker-engine.install

**Comment by mrjana** [comment]
it is present in my installation in Ubuntu:
```
mrjana@dev-1:~/docker/docker$ ls /usr/share/docker-engine/contrib/check-config.sh
/usr/share/docker-engine/contrib/check-config.sh
```

**Comment by thaJeztah** [comment]
> it is present in my installation in Ubuntu

Yes, t.b.h. I only noticed that recently. Overall we point people to the version on GitHub (so that they use the latest version), but I don't have objections against cherry-picking it.

_However_ @alexchenfeng first needs to squash and sign off (officially we aren't even allowed to review, but "lawyers" :joy:)

**Comment by justincormack** [comment]
Oh is it? Hmm, never noticed! Should add to tgz too then.

**Comment by alexchenfeng** [comment]
@thaJeztah I'm so sorry, I rebased  the git repo and added signed-off, please check if has any incorrect.

**Comment by thaJeztah** [comment]
@alexchenfeng no worries! Can you squash your commits so that there's a single commit in this PR? See my earlier comment for some instructions https://github.com/docker/docker/pull/26940#issuecomment-249808967, but let us know if you need assistance

**Comment by alexchenfeng** [comment]
@thaJeztah Oh, no, something is wrong, I think I may be to reopen a new pull request!

**Comment by thaJeztah** [comment]
Continued in https://github.com/docker/docker/pull/26940

**Pull request closed without merging**
