### PR TITLE
Update aws-sdk-go to v1.1.30

### LINKED ISSUE #22961: Please update for AWS-SDK-GO v1.1.*
It would be nice to update Docker for [latest release of aws-sdk-go](https://github.com/aws/aws-sdk-go/releases) v1.1.* as Docker still uses [v0.9.9](https://github.com/docker/docker/blob/master/hack/vendor.sh#L126).

Thanks.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to update aws-sdk-go to v1.1.30.

The following dependencies have been added:
github.com/go-ini/ini 060d7da055ba6ec5ea7a31f116332fe5efa04ce0
github.com/jmespath/go-jmespath 0b12d6b521d83fc7f755e7cfc1b1fbdd35a01a74
Note: the commits matches v1.1.30 of aws-sdk-go.

The following dependency has been removed
github.com/vaughan0/go-ini a98ad7ee00ec53921f08832bc06ecf7fd600e6a1

This pull request consists of two commits. The first commits update `hack/vendor.sh` and `vendor`. The second commit fixes build errors caused by update.

This fix fixes #22961.

### CODE REVIEW

**Comment by yongtang** [comment]
cc @onlyjob @thaJeztah @samuelkarp

**Comment by cpuguy83** [comment]
This is absolutely crazy.
Adding the SDK already added 10k+ LOC, now we are netting +8k more...
We need to look at the cloudwatch driver...

**Comment by samuelkarp** [comment]
I tried this on an Amazon EC2 instance running Ubuntu 14.04.  Trying to run without specifying a region causes a panic:

```
INFO[0040] Trying to get region from EC2 Metadata       
2016/05/27 20:04:15 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 153 [running]:
net/http.(*conn).serve.func1(0xc820ca0c80)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x15097e0, 0xc82000a100)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/aws/aws-sdk-go/aws/ec2metadata.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x1)
        /go/src/github.com/docker/docker/vendor/src/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go:38 +0x72
github.com/docker/docker/daemon/logger/awslogs.glob.func1(0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/logger/awslogs/cloudwatchlogs.go:113 +0x44
github.com/docker/docker/daemon/logger/awslogs.newAWSLogsClient(0xc820de1380, 0xc820d6ba00, 0x40, 0xc820afc440, 0xe, 0xc820b015c8, 0x4, 0xc820d6ac50, 0x3, 0x3, ...)
        /go/src/github.com/docker/docker/daemon/logger/awslogs/cloudwatchlogs.go:130 +0x8bc
github.com/docker/docker/daemon/logger/awslogs.New(0xc820de1380, 0xc820d6ba00, 0x40, 0xc820afc440, 0xe, 0xc820b015c8, 0x4, 0xc820d6ac50, 0x3, 0x3, ...)
        /go/src/github.com/docker/docker/daemon/logger/awslogs/cloudwatchlogs.go:91 +0x1b8
github.com/docker/docker/container.(*Container).StartLogger(0xc820db41c0, 0xc820b01d80, 0x7, 0xc820de1380, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/container/container.go:327 +0x568
github.com/docker/docker/daemon.(*Daemon).StartLogging(0xc8203fca80, 0xc820db41c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/logs.go:122 +0xf4
github.com/docker/docker/daemon.(*Daemon).AttachStreams(0xc8203fca80, 0xc820762e5e, 0x40, 0x7f344e0f85d8, 0xc820dd9620, 0x7f344e0f8680, 0xc82010f7b8, 0x7f344e0f8680, 0xc82010f7c8, 0x0, ...)
        /go/src/github.com/docker/docker/daemon/monitor.go:107 +0x532
github.com/docker/docker/libcontainerd.(*container).start(0xc8204dd950, 0x0, 0x0)
        /go/src/github.com/docker/docker/libcontainerd/container_linux.go:96 +0x51a
github.com/docker/docker/libcontainerd.(*client).Create(0xc820793aa0, 0xc820d6ba00, 0x40, 0xc82038ca80, 0x9, 0x17434c0, 0x5, 0x173f908, 0x5, 0x0, ...)
        /go/src/github.com/docker/docker/libcontainerd/client_linux.go:179 +0x734
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc8203fca80, 0xc820db41c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/start.go:133 +0x67a
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc8203fca80, 0xc8208aa167, 0x40, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/start.go:78 +0x5dd
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc8203d97c0, 0x7f3450aa02a8, 0xc820d9b3e0, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0, 0xc820d9b260, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:148 +0x117
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x7f3450aa02a8, 0xc820d9b3e0, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0, 0xc820d9b260, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/container/container.go:52 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f3450aa02a8, 0xc820d9b3e0, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0, 0xc820d9b260, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f3450aa02a8, 0xc820d9b350, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0, 0xc820d9b260, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0)
        /go/src/github.com/docker/docker/api/server/server.go:137 +0x138
net/http.HandlerFunc.ServeHTTP(0xc82047ab40, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8204da280, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0)
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8208fc200, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0)
        /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8202cd500, 0x7f344e0ee3d8, 0xc820414a90, 0xc820dd55e0)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820ca0c80)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
```

On line 113, it looks like `ec2metadata.New` needs a `session`.

**Comment by yongtang** [comment]
@cpuguy83 I did a `wc` on aws-sdk-go, go-ini, and go-jmespath. go-ini and go-jmespath each has about ~3K lines. aws-sdk-go has about 10K lines (55 files) with service/cloudwatchlogs/api.go about 3K lines.

I noticed that hack/vendor.sh has already removed unreferenced files. Not sure if we could reduce the size further.

**Comment by yongtang** [comment]
Thanks @samuelkarp I updated the pull request to have the issue fixed. Let me know if there are other issues.

**Comment by yongtang** [comment]
@samuelkarp On a separate note, it seems that I am not able to pass AWS credentials to docker through `docker run`. In certain situations we would like to run docker remotely (through tcp on another host) and pass the credentials in runtime (not by re-configuring the daemon host).

Do you think it makes sense to pass aws credentials through `docker run`, e.g., adding
```
--log-opt awslogs-access-key-id=...
```
and
```
--log-opt awslogs-secret-access-key=...
```
?

**Comment by thaJeztah** [comment]
@yongtang yes, it's not your fault; point is that (on the PR that added support for AWS logging) we were unsure if we should include it, due to it bringing in a massive amount of code (just for a logging driver), and now, just updating it to the latest brings in another 8k lines of code.

**Comment by samuelkarp** [comment]
Code LGTM

@yongtang My biggest concern about that is how easy it makes it to accidentally expose your AWS credentials in bash history, `ps`, or in an unencrypted TCP stream.

**Comment by yongtang** [comment]
@samuelkarp Thanks for the review and explanation.

**Comment by thaJeztah** [comment]
OK we're moving this to code review; we really don't like  this bringing in so many code, but want to keep it up to date so...

**Comment by thaJeztah** [comment]
LGTM


ping @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
