### PR TITLE
Update Dockerfile.windows usage

### PR DESCRIPTION
**Pull request by andyleejordan**
The build must be run with process (not hyperv) isolation.

Signed-off-by: Andrew Schwartzmeyer <andschwa@microsoft.com>

/cc @jhowardmsft

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Unfortunately not. Windows server containers are not supported on client. Hence I'm closing this. I just need to find the bug. Will follow up internally.

**Comment by andschwa** [comment]
@jhowardmsft 

> Windows server containers are not supported on client.

What does this have to do with the process isolation bug?

This is a current problem with the Windows build instructions and wasted multiple hours of my time to find, these docs need to be updated until the bug is fixed.

**Comment by jhowardmsft** [comment]
Then the dockerfile.Windows file should be updated so say that this only works on Windows server, at currently does not work on Windows client. It is wrong to say use --isolation=process here.

**Comment by jhowardmsft** [comment]
https://github.com/docker/docker/issues/28263
https://github.com/docker/docker/pull/28261

**Pull request closed without merging**
