### PR TITLE
builder: fix duplicate mount release

### PR DESCRIPTION
**Pull request by tonistiigi**
A possible fix for https://github.com/moby/buildkit/issues/691
Follow up to the previous fix https://github.com/moby/moby/pull/37431

There is a condition (from the readonly mount sharing) where multiple calls can be made against `Mountable` so that the first one calls `Release()` after the second one has returned mounts but has not used them yet. I never managed to reproduce it myself but when I add a sleep to a specific line this becomes 100% reproducible. The error matches the https://github.com/moby/buildkit/issues/691 report.

@tiborvass @AkihiroSuda 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]
LGTM but let's see if @brad-jones can confirm the fix.

**Comment by tonistiigi** [comment]
@tiborvass We need this fix anyway, as there is definitely a possibility to hit this race. But there might be another one as well of course because we never managed to reproduce the original report.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
No idea what the failure is on RS5

```
12:32:02 INFO: Base image for tests is microsoft/windowsservercore
12:32:02 INFO: Loading windowsservercore .tar from disk into the daemon under test. This may take some time...
12:32:45 
12:32:45 
12:32:45 ERROR: Failed 'ERROR: Failed to load c:\baseimages\windowsservercore.tar into daemon under test' at 10/24/2018 12:32:45
12:32:45 At C:\gopath\src\github.com\docker\docker\hack\ci\windows.ps1:705 char:21
12:32:45 + ...             Throw $("ERROR: Failed to load $readBaseFrom`:\baseimages ...
12:32:45 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:32:45 
```

**Comment by tonistiigi** [comment]
@thaJeztah Same error on other PRs. The code changed here should not run at all in windows. @jhowardmsft

**Comment by thaJeztah** [comment]
Yes, let's merge. Was wondering if it was intermittent or a permanent issue

**Pull request merged**
