### PR TITLE
Updated message severity in graphdriver

### LINKED ISSUE #12491: Change severity of message in graphdriver
`daemon/graphdriver/driver.go`:
```
logrus.Infof("[graphdriver] trying provided driver %q", name)
```
Should be debugf.

### PR DESCRIPTION
**Pull request by kostickm**
Changed the message severity from Infof to Debugf. Fixes #12491 

Signed-off-by: Megan Kostick mkostick@us.ibm.com

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by icecrime** [comment]
Pending CI for merge.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
