### PR TITLE
Added information about mailing lists

### PR DESCRIPTION
**Pull request by psankar**

### CODE REVIEW

**Comment by calavera** [comment]
This LGTM, but I'm going to leave the merge for someone use because this information might be duplicated in the docs.

/cc @docker/docs-maintainers

**Comment by psankar** [comment]
Surely it should be there in the docs too, if already not present. But I (assuming a few others too) tend to view the github page more often than the docs page. Also it is easier to post a query to the mailing list from my terminal, without having to google for it, if I have the mailing lists in the git repo itself. Having said all that, I am fine if this cannot be merged :) Thanks for the review.

**Comment by thaJeztah** [comment]
It's actually in the CONTRIBUTING.MD file; https://github.com/docker/docker/blob/master/CONTRIBUTING.md#talking-to-other-docker-users-and-contributors

But I agree that most people will look in the README first (only?), especially if they're not planning to contribute, but simply are looking for help/support.

Perhaps the block should be moved or copied to the README?

@moxiegirl thoughts?

**Comment by SvenDowideit** [comment]
when it comes to finding how to communicate documentation, I'd rather there was duplication - forcing new people to search to find out simple stuff like this is not good UX.

LGTM

**Comment by thaJeztah** [comment]
If we're going to repeat, I'd prefer to actually copy the section from the contributing section, as it also mentions the IRC channels etc. Perhaps as a follow up PR?

I don't see *harm* in adding these in the meantime, so from that perspective;

lgtm

**Comment by psankar** [comment]
I will do the follow up PR as suggested by @thaJeztah by copying the section from the contributing section. I will if possible, try to make it an individual .md file and link to that from both the README.md and the other contributor.md file. But I would be able to do this only by the weekend and I hope it is fine. Thanks for merging.

**Comment by thaJeztah** [comment]
@psankar thanks! I think it would be best to just *copy* the section and not putting it in a separate .md file. The information in that section won't change often and having it in two locations won't hurt.

Also, it's better that people don't have to navigate to another document, because that interrupts them when reading the rest of the content.

**Pull request merged**
