### PR TITLE
Fix typo dont->don't

### PR DESCRIPTION
**Pull request by nashasha1**
Signed-off-by: nashasha1 <a4012017@sina.com>

**- What I did**
Fixed typo in ./api/types/stats.go (dont->don't)

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by kolyshkin** [comment]
PR 37783 already fixed one of these typos (the other one remains though).

LGTM

**Comment by nashasha1** [comment]
@kolyshkin Thanks for reminding. Rebased master.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
