### PR TITLE
Vendor swarmkit 7e096ced

### PR DESCRIPTION
**Pull request by aaronlehmann**
This updates moby to compile against the latest swarmkit, which got slightly out of sync due to protobuf updates.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@aaronlehmann per the discussion I saw on Slack; should we try to get this into 17.06, or no big deal?

**Comment by aaronlehmann** [comment]
It shouldn't be a big deal.

**Comment by thaJeztah** [comment]
ping @cyli @vdemeester PTAL

**Review by vdemeester — APPROVED** [review]
LGTM 👼

**Pull request merged**
