### PR TITLE
Update syntax/vim README with Vundle instructions

### PR DESCRIPTION
**Pull request by carmi**
Wasn't sure how to add a specific subdirectory with Vundle. Figured it out, thought it'd be best to add to the README for others.

### CODE REVIEW

**Comment by LK4D4** [comment]
@carmi You should sign your commit with `git commit --amend -s`

**Comment by carmi** [comment]
On Mon, Jan 5, 2015 at 11:07 AM, Alexander Morozov <notifications@github.com
> wrote:

> git commit --amend -s


Yeah, sorry, saw I broke the build. Just a sec and I'll do that.


-- 
Evan H. Carmi
http://ecarmi.org/

**Comment by carmi** [comment]
Ok, I think I got it signed. @LK4D4

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
