### PR TITLE
Run s390x tests on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by thaJeztah**
carry https://github.com/moby/moby/pull/42577
closes https://github.com/moby/moby/pull/42577

### CODE REVIEW

**Comment by StefanScherer** [comment]
Thanks!
Error during s390x unit tests:
```
[2021-06-29T16:02:11.027Z] + sudo modprobe ip6table_filter
[2021-06-29T16:02:11.027Z] sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
script returned exit code 1
```
We probably have to load that module in advance.

**Comment by thaJeztah** [comment]
Ah, yes, I recall that message showing after libnetwork (and related tests) were moved to this repository. Probably would be good to install it by default yes.

**Comment by thaJeztah** [comment]
Failures:

`TestSCTP4Proxy` tracked in https://github.com/moby/moby/issues/42495

```
 === FAIL: cmd/docker-proxy TestSCTP4Proxy (0.00s)
 panic: interface conversion: net.Addr is nil, not *sctp.SCTPAddr [recovered]
 	panic: interface conversion: net.Addr is nil, not *sctp.SCTPAddr

 goroutine 38 [running]:
 testing.tRunner.func1.2(0x1e4cc0, 0xc00009aab0)
 	/usr/local/go/src/testing/testing.go:1143 +0x2e6
 testing.tRunner.func1(0xc000083200)
 	/usr/local/go/src/testing/testing.go:1146 +0x458
 panic(0x1e4cc0, 0xc00009aab0)
 	/usr/local/go/src/runtime/panic.go:965 +0x16e
 github.com/docker/docker/cmd/docker-proxy.NewProxy(0x257138, 0xc0000ba180, 0x0, 0x0, 0xc0000944e0, 0x1, 0x259088, 0xc0000ba160)
 	/go/src/github.com/docker/docker/cmd/docker-proxy/proxy.go:46 +0x1e2
 github.com/docker/docker/cmd/docker-proxy.TestSCTP4Proxy(0xc000083200)
 	/go/src/github.com/docker/docker/cmd/docker-proxy/network_proxy_test.go:294 +0x21e
 testing.tRunner(0xc000083200, 0x2283f8)
 	/usr/local/go/src/testing/testing.go:1193 +0xd8
 created by testing.(*T).Run
 	/usr/local/go/src/testing/testing.go:1238 +0x296
```

`TestCleanupServiceDiscovery` tracked in https://github.com/moby/moby/issues/42494

```
 === FAIL: libnetwork TestCleanupServiceDiscovery (0.74s)
 time="2021-06-29T15:43:09Z" level=info msg="Removing stale sandbox d029a34093cc03749af640d66b0a2491047eb9960f193788b097df90eeffbc9d (abcdefghi)"
 time="2021-06-29T15:43:09Z" level=warning msg="Failed to delete sandbox d029a34093cc03749af640d66b0a2491047eb9960f193788b097df90eeffbc9d from store: Key not found in store"
 time="2021-06-29T15:43:09Z" level=info msg="Removing stale endpoint endpoint (2b9f95c4c4c5512167980128b47bad351dce5405892eaa6c4c8dc1836811c9ef)"
 time="2021-06-29T15:43:09Z" level=warning msg="Could not delete local endpoint endpoint during endpoint cleanup: Key not found in store"
 time="2021-06-29T15:43:09Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/536205bf922ff27b12135cc9c273139c330f1d4f72a3211d4b9d1e7f261b8573/ is not added to the store"
 time="2021-06-29T15:43:09Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/e7950e76ca0663b23c628f1f6c0e571bd2ffed958034cdeb82c44f034ed866d4/ is not added to the store"
 time="2021-06-29T15:43:09Z" level=warning msg="Failed to update store after ipam release for network net1 (536205bf922ff27b12135cc9c273139c330f1d4f72a3211d4b9d1e7f261b8573): failed to update store for object type *libnetwork.network: Key not found in store"
     service_common_test.go:23: error deleting network endpoint count from store: Key not found in store
```

`TestJoinLeave` tracked in https://github.com/moby/moby/issues/42496

```
 === FAIL: libnetwork/api TestJoinLeave (0.61s)
 time="2021-06-29T15:43:08Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/0d2e913c391bb510d14428ebbfea05f0e717e453ebc5092b2bbe6fe221b7af2b/ is not added to the store"
 time="2021-06-29T15:43:08Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/2b9f95c4c4c5512167980128b47bad351dce5405892eaa6c4c8dc1836811c9ef/ is not added to the store"
     api_linux_test.go:1337: Unexpected failure, got: &{failed to add interface veth20e44d1 to sandbox: failed to set namespace on link "veth20e44d1": invalid argument 500}
 time="2021-06-29T15:43:09Z" level=warning msg="error destroying network sandbox" error="invalid argument"
```

`TestPortMappingV6Config` tracked in https://github.com/moby/moby/issues/42468
```
 === FAIL: libnetwork/drivers/bridge TestPortMappingV6Config (1.98s)
 time="2021-06-29T15:43:22Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/dummy/ is not added to the store"
 time="2021-06-29T15:43:22Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/ep1/ is not added to the store"
 time="2021-06-29T15:43:22Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/ep1/ is not added to the store"
     port_mapping_test.go:157: Failed to store the port bindings into the sandbox info. Found: [{udp 172.19.0.11 400 0.0.0.0 54000 54000} {tcp 172.19.0.11 500 0.0.0.0 65000 65000} {sctp 172.19.0.11 500 0.0.0.0 65000 65000}]
```

**Comment by StefanScherer** [comment]
Small update: We've update a bunch of s390x agents to Ubuntu 20.04 (and Docker 20.10.7), so technically we're ready to use the new Jenkins label.

**Comment by thaJeztah** [comment]
Yes, I think this one should be OK to merge (failing tests aren't new).

I opened a backport for the 20.10 branch in https://github.com/moby/moby/pull/42591, and kicked a build with s390x enabled to verify it works in that branch as well

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/42591 is green 👍

**Review by thaJeztah — COMMENTED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tianon @cpuguy83 PTAL (see above discussion w.r.t. it not being "green" on master - something to be addressed separately, this makes sure we at least have a machine that we can run on 😅)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]

**Pull request merged**
