### PR TITLE
Fix combined image events filters

### LINKED ISSUE #14316: Filter on push events for a specific image
I am trying to use `docker events` to list push events for a specific image(as a part of my CI/CD pipeline - the push event would be a trigger to pull the image and create a new container). Running `docker events --filter 'event=push' --filter 'image=<name>'` does not give me any event when a new image is pushed to the repo.
`docker events --filter 'event=push'` does work for but all image push events. `docker events --filter 'image=<name>'` works but lists create/destroy events as well.
Is there no way to filter specific image's push events?

### PR DESCRIPTION
**Pull request by runcom**
fixes #14316

Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@runcom test fail

**Comment by runcom** [comment]
@LK4D4 fixing

**Comment by runcom** [comment]
Ping @LK4D4 (not sure if this should go in 1.7.1 also)

**Comment by LK4D4** [comment]
I think ok for 1.8
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
