### PR TITLE
Fix openrc script

### PR DESCRIPTION
**Pull request by williamh**
This does a couple of things.

First, it turns off the execute bit on the openrc  script in the repository since this isn't needed; the execute bit should be turned on when the file is installed in the service directory.

It also updates the shebang line to openrc-run which is what modern versions of openrc use and reworks the init script to take advantage of OpenRC's default start/stop functions.

### CODE REVIEW

**Comment by calavera** [comment]
@williamh how are we going to support old versions if we do this?

/cc @tianon, @jfrazelle

**Comment by williamh** [comment]
The reason this was done is for bug https://bugs.gentoo.org/show_bug.cgi?id=494220, and it first took affect in OpenRC-0.13, which was released about a year ago, so people should be transitioning away from #!/sbin/runscript.
Do you have an interest in supporting pre-0.13 OpenRC?

**Comment by tianon** [comment]
@calavera I'm running "stable" Gentoo, and I've got the necessary bits in my OpenRC for this, so I think we're good :+1:

Did some testing here, and everything appears to work great!  LGTM

**Comment by calavera** [comment]
Okaaay, LGTM then

**Pull request merged**
