### PR TITLE
Add api to manage docker daemon labels

### PR DESCRIPTION
**Pull request by hacpai**
Managing docker daemon labels is good for doing some specific scheduling with Swarm.

I am interesting in posting a PR to add api to manage docker daemon labels with @feiyang21687 help.

Docker was able to modify daemon label with `docker label` command, like this:

Signed-off-by: hacpai balckwing@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
I think this lands more in the daemon configuration conversations that we've had with other maintainers, like @duglin. He was proposing to allow changing certain configuration options with a command like `docker config` and labels seem like a good candidate to be included in that set.

I'd like to see something in a more general idea of configuration than adding specific commands for specific options, like this one.

So, I'm going to say that we shouldn't do this. But, maybe other maintainers think otherwise.

**Comment by vdemeester** [comment]
I do agree with @calavera that it would make more sense to have a more *general* commands if any.

I'm still having hard time to see use cases to change dynamically the daemon options (but I might be blind :sweat:). I would think it is more the job of a configuration management system to add / maintain this daemon options / labels.

**Comment by vdemeester** [comment]
I'm gonna close this for now, but feel free to discuss on it and argue for it :wink:.

**Comment by abronan** [comment]
Changing daemon labels is really something that is needed for swarm or you have to restart the docker daemons that have attributes and characteristics changing dynamically (changing a node that was handling `dev` workloads to now handle `prod` workloads for example), as the scheduling policies rely heavily on those labels.

Now I totally agree with the comments above, we need a more general command to deal with the daemon configuration and allow to dynamically change attributes at runtime.

**Comment by hacpai** [comment]
@calavera @vdemeester @abronan Thank you for your suggestion. I think `docker config` is a good design. But maybe it is implemented in a time. I want to perfect `docker label` to make it more general. So I plan to add the feature of managing container label to help more people use docker easily to do something. Referencing https://github.com/docker/docker/issues/15496

Is it a good idea?

**Comment by hongqn** [comment]
@vdemeester Does docker team have any progress on this issue now?  We are using swarm and facing the exact same problem.  It's too heavyweight to restart daemon just to set a label on it.

At which version would we see the label api?  If it is still not in the plan, we'd have to use other workaround, e.g. powerstrip to hijack the api, sadly.

**Comment by thaJeztah** [comment]
@hongqn see my other answer; https://github.com/docker/docker/pull/16978#issuecomment-175983014 this will be possible in docker 1.10; you can try the release candidates now

**Pull request closed without merging**
