### PR TITLE
Bump api version to 1.18

### PR DESCRIPTION
**Pull request by LK4D4**
Signed-off-by: Alexander Morozov lk4d4@docker.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
wow that was fast, LGTM after @icecrime makes the patch to bump the docker version

**Comment by LK4D4** [comment]
Actually we should do this right after "code freeze", because now many people will be forced to move their changes to new file.

**Comment by SvenDowideit** [comment]
Docs LGTM - @fredlf @jamtur01

**Comment by tiborvass** [comment]
LGTM

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
