### PR TITLE
Capitalized Docker and Swarm for consistency

### PR DESCRIPTION
**Pull request by tiffanyfay**
Update of #23395 

turtlekitty
@thaJeztah @justincormack

### CODE REVIEW

**Comment by icecrime** [comment]
Ha, thanks! Cc @dnephin.

**Comment by icecrime** [comment]
LGTM

**Comment by dnephin** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
🎉

**Comment by tiborvass** [comment]
I didn't need to cherrypick this because for some reason 71104bb592dc98467d3828394eabcbe50ca22ae4 had it already and was part of 1.12.0-rc1 already.

**Pull request merged**
