### PR TITLE
Remove job viz

### PR DESCRIPTION
**Pull request by runcom**
pretty sure is not used anywhere

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like a duplicate of https://github.com/docker/docker/pull/12333 which also removes code in other places

**Comment by runcom** [comment]
I'll close it then @thaJeztah, ok?

**Comment by thaJeztah** [comment]
@runcom yes, I think that's best, given that the discussion is mostly taken place there.

Thanks for the compliment; everybody has his specialties :)

I'll let you close it yourself, so that you're still able to re-open, just in case :)

**Comment by runcom** [comment]
thx @thaJeztah

**Pull request closed without merging**
