### PR TITLE
Allow bridge net driver to skip IPv4 configuration of bridge interface

### PR DESCRIPTION
**Pull request by gsomlo**
Introduce "com.docker.network.bridge.inhibit_ipv4" option to the bridge
network driver. If set, this option will prevent docker from setting or
modifying Layer-3 (IP) configuration on the bridge interface in any way.

This option should allow connecting containers to pre-existing network
segments (with e.g., pre-existing default gateways) while simultaneously
preserving our ability to communicate with the host and/or configure the
properties of the host-side container virtual network interface (e.g.,
delay/loss/jitter via netem), which can not be done using macvlan.

Fixes issue #37430.

Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>

### CODE REVIEW

**Comment by gsomlo** [comment]
ping

**Comment by Jabbo16** [comment]
ping

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Derek add label: status/needs-vendoring

**Comment by olljanat** [comment]
@gsomlo plz remove libnetwork changes from this and do them on libnetwork project (if not done yet)

**Comment by gsomlo** [comment]
@olljanat please see https://github.com/docker/libnetwork/pull/2317
For the remaining changes against moby, please see https://github.com/gsomlo/moby/tree/gls-bridge-inhibit-ipv4 (new branch, not sure what would happen if I started modifying a commit I've already pushed)

**Comment by olljanat** [comment]
> For the remaining changes against moby, please see https://github.com/gsomlo/moby/tree/gls-bridge-inhibit-ipv4 (new branch, not sure what would happen if I started modifying a commit I've already pushed)

This PR is created from branch **37430-gls-bridge_inhibit_ipv4** so try to switch, make reset to last commit before your change and then cherry-pick that *2d1dcdd9ae5b021a50bc256611891578db438a42* commit to it.

**Comment by gsomlo** [comment]
Thanks for the hint -- I modified the original pull request (ammend + push --force) to reflect only the remaining (non-libnetwork) changes.

**Comment by cpuguy83** [comment]
ping @arkodg

**Comment by arkodg** [comment]
do we need this @cpuguy83 , shouldn't https://github.com/docker/libnetwork/commit/062641d19a0c55958ac138c7fa9c4cc621609072 be enough to use this feature (by default the value will be 0 / disabled) ?

**Comment by cpuguy83** [comment]
Sounds like we don't need it then.
Thanks!

**Pull request closed without merging**
