### PR TITLE
Don't env-var evaluate labels from docker build cmd line

### LINKED ISSUE #26027: --label inconsistent between build and run
TLDR: `docker build --label` sends its string to be interpolated (after bash processes it) and so it  replaces bash style variables (ie `$foo`) with their value from the env/build-args, while labels passed via `docker run` are not interpreted.

**Output of `docker version`:**

```
# also tested in 1.12.1
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.7
 Git commit:   b9f10c9
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.7
 Git commit:   b9f10c9
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 6651
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.5-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.88 GiB
Name: isengard
ID: UOCM:3F65:5FZC:6H5L:W3HY:34G4:A5XZ:SUOV:S2D4:XQTO:4KGA:6XSE
Docker Root Dir: /mnt/spare/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine. 

**Steps to reproduce the issue:**
 1. Build a Dockerfile with `--label`

  ```console
$ docker build --label 'cli_label$foo=$bar' -t test-labels - <<'EOF'
FROM alpine
EOF
  ```

 1. Try running an image with some labels

  ```console
$ docker run --label foo='$bar' --label 'foo$two'='more $bar' --name labels -it --rm test-labels sh
/ #
  ```

 1. Check `docker inspect` output (see next section)

**Describe the results you received:**
First, look at the output of the above `docker build`.

```console
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine
 ---> 45a09e37e616
Step 2 : LABEL "cli_label$foo" "$bar"
 ---> Running in 89af0220fbc7
 ---> 97b8ad7418da
Removing intermediate container 89af0220fbc7
Successfully built 97b8ad7418da
```

Ok, lets check the image and container with inspect:

```console
$ # image
$ docker inspect --format "{{ json .Config.Labels }}" test-labels | jq
{
  "cli_label": ""
}
$ # container
$ docker inspect --format "{{ json .Config.Labels }}" labels | jq
{
  "cli_label": "",
  "foo": "$bar",
  "foo$two": "more $bar"
}
```

**Describe the results you expected:**

I would expect build to not interpret variables in strings just like `docker run`. So the build above would've resulted in a config like this:
```json
{
  "cli_label$foo": "$bar"
}
```

I know it is possible to do via Dockerfile with with single quotes: `LABEL 'cli_label$foo'='$bar'`.

This is an inconsistent interface for `--label` between `build` and `run`.

### PR DESCRIPTION
**Pull request by duglin**
Fixes #26027

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
@duglin This broke win2lin https://jenkins.dockerproject.org/job/Docker%20Master%20(win2lin)/189/console

**Comment by thaJeztah** [comment]
@tonistiigi @duglin fixed already through https://github.com/docker/docker/pull/27416; looks like two PR's succeeded individually, but resulted in CI to fail when combined

**Comment by tonistiigi** [comment]
@thaJeztah That link is for revision e5d293375d6f9e4213ba7df68036b1ab082040f1 so after #27416

**Comment by dnephin** [comment]
It looks like this broke some people: #31697

**Pull request merged**
