### PR TITLE
Reformat vendor.conf and pin all deps by git-sha

### PR DESCRIPTION
**Pull request by thaJeztah**
to make it better readable, and to encourage pinning by sha, but "align" to a tagged release.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @vdemeester ptal 🤗

**Comment by thaJeztah** [comment]
I also want to sort imports (or better grouping); I see that the current grouping doesn't really make sense anymore, given that packages are used by various dependencies, so there's no single "owner" of a dependency.

**Review by AkihiroSuda — APPROVED** [review]

**Comment by tao12345666333** [comment]
it better readable now. :+1:

**Review by vdemeester — APPROVED** [review]
LGTM :dancer:

**Pull request merged**
