### PR TITLE
Add bash completion for new devicemapper storage options

### PR DESCRIPTION
**Pull request by albers**
Bash completion for #31104.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@albers with the CLI moving to https://github.com/docker/cli (but the `dockerd` command staying in this repository for now), should the completion scripts be split in two separate files? One here for `dockerd` and one in `docker/cli` for the others?

**Comment by albers** [comment]
@thaJeztah
> should the completion scripts be split in two separate files? One here for dockerd and one in docker/cli for the others?

Sounds logical, yes. But there is a lot of shared logic and shared options between both parts, so the split would cause a lot of ongoing maintenance work. We already have a similar situation with duplicated code in `docker-compose` and `docker-machine` where some functions went out of sync.

**Comment by albers** [comment]
@thaJeztah Things were definitely better if `docker`, `dockerd`, `docker-compose` and `docker-machine` all had installer packages. Then we could create a versioned shared lib for the completions (haven't tried but should work).

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by albers** [comment]
Just for the records: I no longer think that a shared lib would reduce maintenance efforts. There would be some problems with versioning and probably issues due to different locations on different OSses.

**Pull request merged**
