### PR TITLE
Fix wrong CPU count after CPU hot-plugging

### LINKED ISSUE #23768: wrong CPU count after cpu hot-plugging
**Applies…**

… to all Docker versions including `1.12.0-rc2`.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

metal

**Steps to reproduce the issue:**
1. Start Docker. (Call `docker info` yourself or by *Docker Swarm*.)
2. Insert or remove CPUs from the system, …
3. … then observe `docker info` not displaying any changed values.

Without a hot-plugging–capable system you could (mask or) offline CPUs to reproduce this:
```bash
printf 0 >/sys/devices/system/cpu/cpu3/online
```

**Describe the results you received:**
Go's `runtime.NumCPU` is used, which gets its data from an initializer at the beginning of process lifetime. Any changes to CPU count do not get reflected by subsequent calls and return values of aforementioned function.

**Describe the results you expected:**
Docker should query the system itself. On Linux and using C you would utilize `sysconf(_SC_NPROCESSORS_ONLN)`.

**Additional information you deem important (e.g. issue happens only occasionally):**
See also docker/swarm#1949 and docker/swarm#1992.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address issues raised in #23768 where the CPU count is not updated after cpu ho-plugging.

**\- How I did it**

This fix follows the suggestion from #23768 and replace go's `runtime.NumCPU()` so that correct CPU count could be obtained even after CPU hot-plugging.

**\- How to verify it**

This fix is tested manually, as is suggested in #23768.

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #23768.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by wmark** [comment]
Replace the `+build` by:

```go
// +build !android,linux
// +build cgo
```

… because Android uses *bionic* and not the *glibc*.

**Comment by wmark** [comment]
A version without CGO:

```bash
import (
        "syscall"
        "unsafe"

        "golang.org/x/sys/unix"
)

func popcnt(x uint64) (n byte) {
        x -= (x >> 1) & 0x5555555555555555
        x = (x>>2)&0x3333333333333333 + x&0x3333333333333333
        x += x >> 4
        x &= 0x0f0f0f0f0f0f0f0f
        x *= 0x0101010101010101
        return byte(x >> 56)
}

// AvailableCPU queries the system for the count of threads available
// for use to this process.
//
// Issues two syscalls.
// Returns 0 on errors. Use |runtime.NumCPU| in that case.
func AvailableCPU() uint {
        // Gets the affinity mask for a process. The very one invoking this function.
        pid, _, _ := syscall.RawSyscall(unix.SYS_GETPID, 0, 0, 0)

        var mask [1024 / 64]uintptr
        _, _, err := syscall.RawSyscall(unix.SYS_SCHED_GETAFFINITY, pid, uintptr(len(mask)*8), uintptr(unsafe.Pointer(&mask[0])))
        if err != 0 {
                return 0
        }

        // For every available thread a bit is set in the mask.
        var ncpu uint = 0
        for _, e := range mask {
                if e == 0 {
                        continue
                }
                ncpu += uint(popcnt(uint64(e)))
        }
        return ncpu
}
```

**Comment by yongtang** [comment]
Thanks @wmark I tried the implementation locally and it works as expected. The PR has been updated.

I also realized that on Windows the same issue may apply as well. I will spend sometime to see if I could get Windows implementation with `GetProcessAffinityMask`.

**Comment by yongtang** [comment]
@wmark The NumCPU on Windows has been implemented and the PR has been updated. Please let me know if there are any issues.

**Comment by wmark** [comment]
Thanks, @yongtang! In a nutshell: LGTM

You've vendored-in `x/sys/unix`, hence the many changed lines. I've only glanced over the first four changed files.

The syscalls work for all `posix`, not only `linux`. That is, I cannot test it but expect that it will work on some *BSD variants and Solaris. But yes, this time Android is covered. Other than that I am no neutral reviewer of the code anymore.

There's a subtle difference between your old approach (which has been fine!) and the new one, querying affinity masks:

- An operator might have pinned Docker to a disjunct set of CPUs than for the containers.
- So the affinity mask does not reflect the count of available »CPUs«.
- An affinity mask that had been reduced (does not span all CPUs anymore) does not get expanded after plugging in more CPUs. The count of online CPUs on the other hand will be increased. (Someone messing with the mask will already be aware of that limitation, though.)

Neither of the approaches reliably tells how many »CPUs« we can expect (affinity mask could reduce online ones). But both approaches are more accurate and suitable than just `runtime.NumCPU`.

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @jhowardmsft PTAL for the windows part

**Comment by jhowardmsft** [comment]
LGTM for the Windows change

**Comment by thaJeztah** [comment]
all green, so merging, thanks all!

**Pull request merged**
