### PR TITLE
extend mirror for supporting private registry

### PR DESCRIPTION
**Pull request by TrumanLing**
extend mirror for supporting private registry

Signed-off-by: Ling FaKe lingfake@huawei.com

### CODE REVIEW

**Comment by hqhq** [comment]
You don't need to open a new PR for rebase, just `git push -f xxx` in https://github.com/docker/docker/pull/18915

**Comment by thaJeztah** [comment]
I'd really like to have input of @dmp42 @stevvooe, @RichardScothern for "registry" and @tonistiigi for the engine side on this

**Comment by stevvooe** [comment]
To add support for this, we need to make it so that image names are scoped by their registry if they are not from the official registry. We also need content trust to be enabled by default, since this defers naming to a possibly untrusted registry. Such a PR really needs a proper proposal outlining the approach to these concerns before proceeding.

I believe my most recent description of this issue is in [this post](https://groups.google.com/forum/#!topic/docker-user/-odvHhqisLg).

**Comment by TrumanLing** [comment]
@stevvooe I know your concers, but I don't understand completely, the image names, images trust and provenance you mentioned [docker/docker#16974](https://github.com/docker/docker/issues/16974)

**Comment by TrumanLing** [comment]
@thaJeztah @stevvooe though there is naming scope issue, but I think this PR has no direct relationship with your concerns, and there is strong and much desire for mirroring private registry, how about your opinion?

**Comment by stevvooe** [comment]
@TrumanLing If registry A and registry B disagree on what the value of image `foo` is, how should docker behave? Should docker just take the new value? Should it reject the differing value? Without assigning a single source of naming, these problems become endless. They need to be clearly understood before proceeding.

Also, this needs a description of the actual proposal. This PR changes the format and behavior of an existing option and doesn't even demonstrate why or how. Let's see a design and proposal covering these concerns and move from there.

**Comment by TrumanLing** [comment]
@stevvooe thanks for your reponse. If you do desgin, proposal and discussion, would you please involve me if convinient, I am very interesting these conerns.

**Comment by thaJeztah** [comment]
@TrumanLing I think @stevvooe meant to say; if you want this feature, please create a design and proposal

**Comment by hqhq** [comment]
We already have a proposal: https://github.com/docker/docker/issues/18818
@TrumanLing Maybe you can ping related maintainers in that issue.

**Comment by stevvooe** [comment]
@hqhq Could you expand the proposal to cover the concerns above? Specifically, what is the planned behavior in the daemon upon disagreement in naming. These questions need to be answered before we can proceed.

**Comment by TrumanLing** [comment]
@thaJeztah @stevvooe you mentioned " If registry A and registry B disagree on what the value of image ```foo``` is, how should docker behave? ", in fact there is no disagreement even if registry A and registry B have the same value of image ```foo```, because there are two different images ```registry A/foo``` and ```registry B/foo```.

**Comment by stevvooe** [comment]
@TrumanLing The proposal is insufficient. Please expand it to cover these cases and analyze other cases that may arise. We cannot accept a change here without proper due diligence.

**Comment by icecrime** [comment]
Let's continue discussion on the related issue #18818: I'm closing this for now as it doesn't seem ready to be merged.

Thanks

**Pull request closed without merging**
