### PR TITLE
Add missing fields for list container

### PR DESCRIPTION
**Pull request by KostyaSha**
Dump from 1.10.1 has this fields.

### CODE REVIEW

**Comment by KostyaSha** [comment]
And `SizeRw` is missing even with `size=true`

**Comment by thaJeztah** [comment]
Thanks! Can you also update the v1.23 version, because that should also match this?

> And SizeRw is missing even with size=true

I could not reproduce that, adding `?size=true`, I got;

```json
[
  {
    "Id": "4ecb9ba7e02162519836b525ab0e0f902b8a5d361d987ca0ed18ff1aa7191452",
    "Names": [
      "\/loving_ptolemy"
    ],
    "Image": "ubuntu",
    "ImageID": "sha256:14b59d36bae04ba5e4c2bb3ff2906c16d6beac3b6c3ea15273f7458bb5687a3d",
    "Command": "\/bin\/bash",
    "Created": 1455807318,
    "Ports": [
      
    ],
    "SizeRw": 11574761,
    "SizeRootFs": 199524984,
    "Labels": {
      
    },
    "Status": "Up 5 minutes",
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "",
          "EndpointID": "dcce2d44d394a05e1ce666a6c6eb317e25c8e4075fe67f043eafb77bd9151115",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.2",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:02"
        }
      }
    }
  }
]
```

**Comment by KostyaSha** [comment]
Last time when i contributed docs updates @moxiegirl said that something changed vs `docs` branch so i'm not sure where is right target branches.

@thaJeztah maybe it depends on storage driver, i used latest docker toolbox (1.10.1)

**Comment by thaJeztah** [comment]
@KostyaSha I think it's fine to merge to master; we can cherry-pick into the docs branch (we're currently discussing if we want to change that, but for now that's fine)

I just tried it on boot2docker 1.10.1 as well, so not sure what can cause it to not appear; good question

**Comment by calavera** [comment]
> Can you also update the v1.23 version

@KostyaSha can you do this for _1_23 too? Master branch, please :pray:

**Comment by KostyaSha** [comment]
I found more issues in docs, i'm in process of syncing docker-java, so will update with all issues that i will find.

**Comment by moxiegirl** [comment]
@KostyaSha are you able to complete this or do you need a carry?

**Comment by KostyaSha** [comment]
@moxiegirl slowly switching to network API sync in docker-java. Feel free to merge if you need faster :)

**Comment by KostyaSha** [comment]
Seems "aux" example in Pull response item is also missing, would be good to document it.

**Comment by thaJeztah** [comment]
oh, just see the "carry" PR was merged, so this can be closed

**Pull request closed without merging**
