### PR TITLE
add test for pulling "mcr.microsoft.com/windows/servercore" image

### PR DESCRIPTION
**Pull request by andrey-ko**
add regression test for https://github.com/docker/escalation/issues/1098
this is just basic test to pull "mcr.microsoft.com/windows/servercore" image

### CODE REVIEW

**Comment by jhowardmsft** [comment]
This is a prohibitively expensive test to run on the servers and prone to timeout (as it did on RS5). Do you REALLY need to do this? (Also, I don't think adding anything under integration-cli is permitted any more. I can't see the docker/escalation repo, so can't really tell why you're adding this.

**Comment by thaJeztah** [comment]
@jhowardmsft this relates to https://github.com/moby/moby/issues/38582 (  https://github.com/Microsoft/hcsshim/pull/147 and https://github.com/Microsoft/hcsshim/pull/144)

Pulling a large image is definitely a concern; do you know if an alternative can be found to check for that situation?

@andrey-ko might want to mention those instead

**Comment by jhowardmsft** [comment]
The hcsshim links don’t relate to large images. The latest instance
of reexec failing is due to a bad image on mcr which is being looked at internally (not sure if resolved yet). But not due to the image size

**Comment by thaJeztah** [comment]
> The hcsshim links don’t relate to large images

IIUC, it was related to "junctions", so perhaps we can have a small image that can be used to reproduce the original issue?

**Comment by jhowardmsft** [comment]
Would’t that be better handled as a unit test in hcsshim?

**Comment by ddebroy** [comment]
@jhowardmsft I agree that this test will require a while to complete - the test run did trip the 10m timeout. However it seems we do not perform a regular Windows pull test anywhere in `docker_cli_pull_test.go`. Isn't that a rather big hole in `docker_cli_pull_test.go` in the context of Windows engine?

**Comment by jhowardmsft** [comment]
If you are going to pull an image, why does it need to be so big? The root cause of the failure alluded to had nothing directly to do with size itself. At least something based on nanoserver would be significantly cheaper. Pulling and expanding windowsservercore is HUGELY expensive to run on these servers in terms of IO and storage costs, and add a lot of time to the overall run. I honestly cannot be supportive of it as it stands. Would it not be better to come up with a way to pull from a local registry if you feel it necessary to have such a test? And it still is the case that this would have to be done through integration, not integration-cli regardless (and integration enabled for Windows).

**Comment by cpuguy83** [comment]
I tend to agree with @jhowardmsft , I don't think it's worth it and in general we should be eliminating pulls from remote registries as a whole from the test suite as this introduces flakiness in the tests way more often than most people realize.

I'm sure if we want to test the pull functionality itself, we can come up with some contrived image with a split base, but keep it in a registry that is local to the test run (not that this is testing the bug in question, just commenting on what's being discussed as testing holes).

**Comment by thaJeztah** [comment]
closing for now, but we'll discuss other approaches

**Comment by andrewhsu** [comment]
@andrey-ko there is a better way to have a test internally at docker for verifying the docker-ee 17.06 engine which i'll contact you directly about. i agree with @cpuguy83 and @jhowardmsft about having this tested elsewhere.

**Pull request closed without merging**
