### PR TITLE
Updates man page generation to use go-md2man v1.0.2

### LINKED ISSUE #12866: docs/man completely messed up
Some of docker man pages are completely messed up (e.g. docker-cp and docker-run)
`Docker version 1.6.0, build 3eac457/1.6.0`

For example `man docker cp` results in
```
NAME
       docker-cp - Copy files or folders from a container's PATH to a HOSTDIR or to STDOUT.

SYNOPSIS
       docker cp [--help] CONTAINER:PATH HOSTDIR|-

DESCRIPTION
       Copy files or folders from a CONTAINER:PATH to the HOSTDIR or to STDOUT.  The CONTAINER:PATH is relative to the root of the container's filesystem. You can copy from either a running or stopped container.

       The  PATH  can  be  a  file  or  directory.  The  docker  cp  command  assumes  all  PATH values start at the / (root) directory. This means supplying the initial forward slash is optional; The command sees compassionate_dar‐
       win:/tmp/foo/myfile.txt and compassionate_darwin:tmp/foo/myfile.txt as identical.

       The HOSTDIR refers to a directory on the host. If you do not specify an absolute path for your HOSTDIR value, Docker creates the directory relative to where you run the docker cp command. For example, suppose you want to copy
       the /tmp/foo directory from a container to the /tmp directory on your host. If you run docker cp in your   (home) directory on the host:

                  docker cp compassionate_darwin:tmp/foo /tmp

              Docker creates a /tmp/foo directory on your host. Alternatively, you can omit the leading slash in the command. If you execute this command from your home directory:

                         docker cp compassionate_darwin:tmp/foo tmp

                     Docker creates a  /tmp/foo subdirectory.

                     When copying files to an existing HOSTDIR, the cp command adds the new files to the directory. For example, this command:

                                docker cp sharp_ptolemy:/tmp/foo/myfile.txt /tmp

                            Creates a /tmp/foo directory on the host containing the myfile.txt file. If you repeat the command but change the filename:

                                       docker cp sharp_ptolemy:/tmp/foo/secondfile.txt /tmp

                                   Your host's /tmp/foo directory will contain both files:

                                              ls /tmp/foo
                                              myfile.txt secondfile.txt

                                          Finally, use '-' to write the data as a tar file to STDOUT.

```
and should be
```
NAME
       docker-cp - Copy files or folders from a container's PATH to a HOSTDIR or to STDOUT.

SYNOPSIS
       docker cp [--help] CONTAINER:PATH HOSTDIR|-

DESCRIPTION
       Copy files or folders from a CONTAINER:PATH to the HOSTDIR or to STDOUT.  The CONTAINER:PATH is relative to the root of the container's filesystem. You can copy from either a running or stopped container.

       The  PATH  can  be  a  file  or  directory.  The  docker  cp  command  assumes  all  PATH values start at the / (root) directory. This means supplying the initial forward slash is optional; The command sees compassionate_dar‐
       win:/tmp/foo/myfile.txt and compassionate_darwin:tmp/foo/myfile.txt as identical.

       The HOSTDIR refers to a directory on the host. If you do not specify an absolute path for your HOSTDIR value, Docker creates the directory relative to where you run the docker cp command. For example, suppose you want to copy
       the /tmp/foo directory from a container to the /tmp directory on your host. If you run docker cp in your   (home) directory on the host:

                  docker cp compassionate_darwin:tmp/foo /tmp

       Docker creates a /tmp/foo directory on your host. Alternatively, you can omit the leading slash in the command. If you execute this command from your home directory:

                  docker cp compassionate_darwin:tmp/foo tmp

       Docker creates a  /tmp/foo subdirectory.

       When copying files to an existing HOSTDIR, the cp command adds the new files to the directory. For example, this command:

                  docker cp sharp_ptolemy:/tmp/foo/myfile.txt /tmp

       Creates a /tmp/foo directory on the host containing the myfile.txt file. If you repeat the command but change the filename:

                  docker cp sharp_ptolemy:/tmp/foo/secondfile.txt /tmp

       Your host's /tmp/foo directory will contain both files:

                  ls /tmp/foo
                  myfile.txt secondfile.txt

       Finally, use '-' to write the data as a tar file to STDOUT.
```

### PR DESCRIPTION
**Pull request by bexelbie**
This update includes a patch that fixes the indention issue where
codeblocks cause all further text to be indented.

Fixes #12866

Signed-off-by: Brian Exelbierd bex@pobox.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Sorry, this isn't right.
The v1.0.1 version should be working just fine.
Do you have a specific doc that isn't rendering properly?

**Comment by thaJeztah** [comment]
@cpuguy83 does this LGTY? Should this be cherry-picked for 1.7? (typing on my phone right now)

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
@bexelbie sorry for this, but https://github.com/docker/docker/pull/13804 was just merged, and the location of this file was changed as a result of this, so this PR needs a rebase

**Comment by bexelbie** [comment]
@thaJeztah rebased.

**Comment by thaJeztah** [comment]
Awesome, @bexelbie!

It's very busy at the moment because of the pending 1.7 release, but I'll try and get another maintainer to review this.

ping @jfrazelle @moxiegirl this should fix formatting issues for users building the man-pages (https://github.com/docker/docker/issues/12866)

**Comment by bexelbie** [comment]
TY @thaJeztah

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
And... It's merged! Thanks for your contribution @bexelbie !

**Comment by moxiegirl** [comment]
Late to the party! I did test it the whole thing soup to nuts this morning to verify.  Thanks @bexelbie for the timely contribution!

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
