### PR TITLE
avoid copying dir when creating 'id-init' .

### PR DESCRIPTION
**Pull request by xuxinkun**
graphdriver-vfs will copy all the files when create 'id-init'. But actually,when Create(), just record the parent dir. And when Get() happens, return the parent dir will resolve this problem.

Signed-off-by: xuxinkun xuxinkun@gmail.com

### CODE REVIEW

**Comment by xuxinkun** [comment]
To solve the issue https://github.com/docker/docker/issues/11366

**Comment by icecrime** [comment]
Thanks @xuxinkun! Apparently CI is failing:

```
---> Making bundle: validate-gofmt (in bundles/1.5.0-dev/validate-gofmt)
These files are not properly gofmt'd:
 - daemon/graphdriver/vfs/driver.go

Please reformat the above files using "gofmt -s -w" and commit the result.
```

Can you please take a look?

**Comment by LK4D4** [comment]
@xuxinkun Seems like something not working.

**Comment by xuxinkun** [comment]
Test online cannot pass maybe because each case is tested sperately. I test it on my own machine. The intergration-cli tests can be passed.

**Comment by unclejack** [comment]
This PR is breaking the code. vfs is broken with these changes. `make test` fails.

**Comment by LK4D4** [comment]
I'm closing this due inactivity.
@xuxinkun Feel free to open new when you find problem.

**Comment by xuxinkun** [comment]
@LK4D4 I open a new one and fix the error. Please check #12806 .

**Pull request closed without merging**
