### PR TITLE
[27.x backport] vendor: vendor: github.com/vishvananda/netlink v1.3.x (084abd93d) and fix compatibility

### PR DESCRIPTION
**Pull request by thaJeztah**
Backport:

- https://github.com/moby/moby/pull/48368
- https://github.com/moby/moby/pull/48407
    - minor conflict because https://github.com/moby/moby/commit/185b1e3d6995f6c2126641edc91248008ac1da28 is not in this branch
    - https://github.com/moby/moby/pull/48515
- https://github.com/moby/moby/pull/48598

### CODE REVIEW

**Comment by thaJeztah** [comment]
Needed for updating buildkit v0.18

**Comment by thaJeztah** [comment]
Missed an import somewhere;

```
#23 38.05 libnetwork/drivers/bridge/setup_ip_tables_linux.go:572:15: undefined: netlink
#23 38.05 libnetwork/drivers/bridge/setup_ip_tables_linux.go:573:23: undefined: netlink
```

**Comment by thaJeztah** [comment]
Failures are unrelated, but are more flaky since recently; likely related to the runc 1.2 update

```
=== FAIL: amd64.integration.build TestBuildUserNamespaceValidateCapabilitiesAreV2 (17.08s)
Loaded image: busybox:latest
Loaded image: busybox:glibc
Loaded image: debian:bookworm-slim
Loaded image: hello-world:latest
Loaded image: arm32v7/hello-world:latest
    build_userns_linux_test.go:131: run produced invalid output: "", expected "/bin/sleep cap_net_bind_service=eip"
    
    
=== RUN   TestDiff
    diff_test.go:28: assertion failed: 
        --- expected
        +++ items
          []container.FilesystemChange(
        - 	{{Kind: s"A", Path: "/foo"}, {Kind: s"A", Path: "/foo/bar"}},
        + 	nil,
          )
        
--- FAIL: TestDiff (0.57s)    
```

**Comment by thaJeztah** [comment]
Rebased; minor conflicts in imports due to the modprobe PR already being merged in this branch;

- https://github.com/moby/moby/pull/49043

**Review by akerouanton — APPROVED** [review]

**Pull request merged**
