### PR TITLE
daemon: execdriver: lxc: fix wrong template value passed to lxc conf

### LINKED ISSUE #15876: lxc fix kernel memory limit test
```
----------------------------------------------------------------------
FAIL: docker_cli_run_unix_test.go:284: DockerSuite.TestRunWithKernelMemory

docker_cli_run_unix_test.go:287:
    dockerCmd(c, "run", "--kernel-memory", "50M", "--name", "test", "busybox", "true")
github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:839:
    ...open github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go: no such file or directory
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc20826db60)} ("exit status 255")
... "run --kernel-memory 50M --name test busybox true" failed with errors: WARNING: You specified a kernel memory limit on a kernel older than 4.0. Kernel memory limits are experimental on older kernels, it won't work as expected and can cause your system to be unstable.
, exit status 255


----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by runcom**
@jfrazelle but this fixes #15876 :p

Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by runcom** [comment]
```
+ go test -check.f DockerSuite.TestRunWithKernelMemory* -test.timeout=60m -check.v github.com/docker/docker/integration-cli
INFO: Testing against a local daemon
PASS: docker_cli_run_unix_test.go:205: DockerSuite.TestRunWithKernelMemory	0.276s
OK: 1 passed
PASS
coverage: 11.2% of statements
ok  	github.com/docker/docker/integration-cli	0.368s
---> Making bundle: .integration-daemon-stop (in bundles/1.9.0-dev/test-integration-cli)
++++ cat bundles/1.9.0-dev/test-integration-cli/docker.pid
+++ kill 898
```

**Comment by jfrazelle** [comment]
LGTM

**Comment by ehazlett** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM, only one test failed in LXC, and it's a known issue

**Pull request merged**
