### PR TITLE
Proposal: Add Logging driver for fluentd

### PR DESCRIPTION
**Pull request by tagomoris**
I think that some more Logging driver make users happy!
This is the first for more logging drivers for [Fluentd](http://www.fluentd.org).

See the files for more details.

### CODE REVIEW

**Comment by tagomoris** [comment]
I'm sorry to miss it. I added.

**Comment by kysnm** [comment]
:+1:

**Comment by ijin** [comment]
:+1:

**Comment by katutoshi** [comment]
:+1:

**Comment by zchee** [comment]
:+1:

**Comment by kazegusuri** [comment]
:+1:

**Comment by ixixi** [comment]
:+1:

**Comment by Saisse** [comment]
:+1:

**Comment by otaki-ryuta** [comment]
:+1:

**Comment by tmtk75** [comment]
:+1:

**Comment by jfrazelle** [comment]
hey all we get it you want this, but can you not +1, because it makes feedback hard to read :), we promise we will do our best to review this as soon as possible

**Comment by jfrazelle** [comment]
adding this seems fine to me

**Comment by kzk** [comment]
@jfrazelle Just a background. @tagomoris is a maintainer of Fluentd (http://www.fluentd.org/), and I'm from Treasure Data sponsoring Fluentd project.

We recently started seeing more people adopting Docker + Fluentd. For example. Google's Kubernetes adopted Fluentd as a default log collector. But this uses Fluentd's 'tail' input plugin for log files, so it's not something performant and config files become messy...

- https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

Digital ocean wrote a documentation about how to centralize Docker logs into one place, using Fluentd. But as I mentioned above, it tails log files.

- https://www.digitalocean.com/community/tutorials/how-to-centralize-your-docker-logs-with-fluentd-and-elasticsearch-on-ubuntu-14-04

We'd like to have a way to directly push the logs from Docker to Fluentd, which is more performant and reliable. Just in case, @tagomoris already wrote a code so that you can review.

- https://github.com/tagomoris/docker/tree/logger-driver-fluentd

Logging is the essential part of the immutable infrastructure, so hope Docker has a flexible way to centralized logs using the solution like Fluentd.

**Comment by Zaki-XL** [comment]
:+1:

**Comment by cpuguy83** [comment]
Definitely +1 as long as we can ping for issues. @tagomoris @kzk do you plan to contribute code for this?
Also, proposal doc is probably longer than the actual implementation will be :)

**Comment by tagomoris** [comment]
I already have a complete code for this feature.
So I've just created a pull request #12876.

**Comment by jfrazelle** [comment]
can you then combine this with that one so there are not two threads for the same feature and close this one

**Comment by kzk** [comment]
@cpuguy83 I can give you our point of contacts for you guys. Please reach out to me at k@treasure-data.com.

**Comment by LK4D4** [comment]
I think we can close this, because now it is real PR #12876

**Pull request closed without merging**
