### PR TITLE
Fix devmapper backend in docker info

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
gofmt errors.

**Comment by LK4D4** [comment]
@anusha-ragunathan that's weird :) I suggest to fix it anyway.

**Comment by calavera** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
