### PR TITLE
Renaming a container with an invalid name should fail

### LINKED ISSUE #10081: rename to invalid name is losing its old name
docker rename to an invalid name is losing its old name, I think the backend should check new name's validity before making any changes

```
$ docker ps
CONTAINER ID        IMAGE           COMMAND     CREATED  STATUS   PORTS    NAMES
3df7e2d463f9        debian   "/bin/bash"  15 minutes ago  Up 15 minutes     myname
$ docker rename myname new:invalid
Error response from daemon: Error when allocating new name: Invalid container
  name (new:invalid), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
FATA[0000] Error: failed to rename container named myname 
$ docker rename myname newok
Error response from daemon: No such container: myname
FATA[0000] Error: failed to rename container named myname 
$ docker ps
CONTAINER ID        IMAGE           COMMAND     CREATED  STATUS   PORTS    NAMES
3df7e2d463f9        debian   "/bin/bash"  15 minutes ago  Up 15 minutes
$ docker rename 3df7e2d463f9 newokname
$ docker ps
CONTAINER ID        IMAGE           COMMAND     CREATED  STATUS   PORTS    NAMES
3df7e2d463f9        debian   "/bin/bash"  15 minutes ago  Up 15 minutes     newokname
```

### PR DESCRIPTION
**Pull request by jessfraz**
Fixes #10081

### CODE REVIEW

**Comment by icecrime** [comment]
Sorry to come in late, but I didn't get the chance to test the original PR after my review comments were applied, and I'm afraid it has other flaws... This is what I just tried:

```
$ docker run -dti --name root busybox
77a2727a3d81d523ca8f3b26744bfb24b6600f9f6fbb4f24026265cb3b704b90
$ docker run --link root:root --name child1 busybox true
$ sqlite3 /var/lib/docker/linkgraph.db .dump
[...]
INSERT INTO "edge" VALUES('0',NULL,'/');
INSERT INTO "edge" VALUES('77a2727a3d81d523ca8f3b26744bfb24b6600f9f6fbb4f24026265cb3b704b90','0','root');
INSERT INTO "edge" VALUES('a9f63cf8de7d92efefb388cbe5b8abd169b0bccaf5ea9b0f3db3b1cb2ccb95d2','0','child1');
INSERT INTO "edge" VALUES('77a2727a3d81d523ca8f3b26744bfb24b6600f9f6fbb4f24026265cb3b704b90','a9f63cf8de7d92efefb388cbe5b8abd169b0bccaf5ea9b0f3db3b1cb2ccb95d2','root');
[...]
$ docker rename root parent
$ sqlite3 /var/lib/docker/linkgraph.db .dump
[...]
INSERT INTO "edge" VALUES('a9f63cf8de7d92efefb388cbe5b8abd169b0bccaf5ea9b0f3db3b1cb2ccb95d2','0','child1');
INSERT INTO "edge" VALUES('77a2727a3d81d523ca8f3b26744bfb24b6600f9f6fbb4f24026265cb3b704b90','a9f63cf8de7d92efefb388cbe5b8abd169b0bccaf5ea9b0f3db3b1cb2ccb95d2','root');
INSERT INTO "edge" VALUES('77a2727a3d81d523ca8f3b26744bfb24b6600f9f6fbb4f24026265cb3b704b90','0','parent');
[...]
```

The important information here is that in this last dump, we still have a relationship named as the original name. Does it break link functionality, I don't know, but it looks weird to me.

**Comment by tiborvass** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
Actually can you change the var names to not be snake case and shame the person that put this into the code base?

**Comment by jfrazelle** [comment]
nice catch

**Comment by jfrazelle** [comment]
done

**Comment by jfrazelle** [comment]
@crosbymichael drone passed give me back your LGTM, or don't, whatever ;)

**Comment by vieux** [comment]
LGTM

**Pull request merged**
