### PR TITLE
Embedded DNS problem after renaming container. Step2:change in docker…

### PR DESCRIPTION
**Pull request by jmzwcn**
Embedded DNS problem after renaming container. Step2:change in docker daemon side
#22466

Signed-off-by: Daniel Zhang jmzwcn@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Would you be able to add an integration test for this? something like;

- create a network
- start an anonymous container
- rename the container
- start another container on the same network and ping to the renamed container

**Comment by jmzwcn** [comment]
Sure, I will try adding an integration for this issue.

**Comment by jmzwcn** [comment]
@thaJeztah , I have appended the integration test, but having two uncertain:
1.not sure whether it works on Windows platform;
2.why it fails on win2lin/windowsTP5.

Could you please give me more advice? Thanks!

**Comment by thaJeztah** [comment]
Looks like both failures are a networking issue in CI, and unrelated. Let me restart them

**Comment by thaJeztah** [comment]
Looks like you need to rebase, because there's a merge commit in your PR now; see https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently

**Comment by jmzwcn** [comment]
@thaJeztah 
have rebase, but the both failures arise again.

**Comment by LK4D4** [comment]
ping @mavenugo @mrjana

**Comment by jmzwcn** [comment]
@LK4D4 
Yes, the checking are passed finally, please help to review.

**Comment by mavenugo** [comment]
LGTM. ping @sanimej

**Comment by icecrime** [comment]
Thanks! LGTM.

Waiting for @sanimej to give it a final look before merging.

**Comment by sanimej** [comment]
LGTM. Thanks @jmzwcn

**Comment by jmzwcn** [comment]
@sanimej 
For renaming the running anonymous container, the RR locates in #https://github.com/docker/libnetwork/pull/1164. Could you please review?

**Pull request merged**
