### PR TITLE
hack/dockerfile/binaries-commits: use full commit hash for docker info

### PR DESCRIPTION
**Pull request by runcom**
Before:
```sh
$ docker info
[...]
Init Binary: docker-init
containerd version:  (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: 51371867a01c467f08af739783b8beafc154c4d7 (expected: 51371867a01c467f08af739783b8beafc15)
init version: 949e6fa
[...]
```
After:
```sh
$ docker info
[...]
Init Binary: docker-init
containerd version:  (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
[...]
``` 
You can see `runc` version is now ok. The problem is that we have to use exactly the same commit id from the output of `runc --version` (in this case it's longer).
```sh
8:58:35 [~] /usr/local/bin/docker-runc --version
runc version 1.0.0-rc2
commit: 51371867a01c467f08af739783b8beafc154c4d7
spec: 1.0.0-rc2-dev
```

### CODE REVIEW

**Comment by mlaventure** [comment]
LGTM, not sure how I ended up cutting the hash :sweat_smile: 

Thanks for spotting it!

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
All 💚

**Pull request merged**
