### PR TITLE
Optimize `TestEventsContainerFailStartDie`

### PR DESCRIPTION
**Pull request by WeiZhang555**
Part of #19425 

Optimize performance of `TestEventsContainerFailStartDie`

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by WeiZhang555** [comment]
After fix:
```
INFO: Testing against a local daemon
PASS: docker_cli_events_test.go:68: DockerSuite.TestEventsContainerFailStartDie 1.063s
OK: 1 passed
PASS
```

Execution time is reduced from 40s to 1s

**Comment by coolljt0725** [comment]
LGTM 
confirm this can fix this, the previous test use the image 
`out, _ := dockerCmd(c, "images", "-q")
image := strings.Split(out, "\n")[0]` 
after debugging, I found this image is 
`syscall-test` which size is `609.1 MB`.
below is the some printf from test.
<pre><code>REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
syscall-test        latest              f3c415b8ca88        8 hours ago         609.1 MB
httpserver          latest              d84c92bd6b04        8 hours ago         7.792 MB
buildpack-deps      jessie              fbcf1a53307b        13 hours ago        606.5 MB
busybox             latest              aa5d5f5a81c9        12 weeks ago        1.109 MB
hello-world         frozen              690ed74de00f        3 months ago        960 B
jess/unshare        latest              d733ebae1254        8 months ago        4.8 MB
emptyfs             latest              11f64303f0f7        2 years ago         0 B</code></pre>
and `image := strings.Split(out, "\n")[0]` is `f3c415b8ca88`

The image is too large and we use `vfs` storage driver for test, so it will take a long time to
prepare the container root filesystem. I think it make sense to use `busybox` at the test.

**Comment by vdemeester** [comment]
Oh :sweat_smile: 40s :astonished:
LGTM 🐵

**Comment by vdemeester** [comment]
```
12:49:18 FAIL: docker_cli_network_unix_test.go:995: TestDockerNetworkHostModeUngracefulDaemonRestart.pN59_github_com_docker_docker_integration_cli.DockerNetworkSuite
12:49:18 
12:49:18 [d47566000] waiting for daemon to start
12:49:18 [d47566000] daemon started
12:49:18 [d47566000] exiting daemon
12:49:18 [d47566000] waiting for daemon to start
12:49:18 [d47566000] daemon started
12:49:18 docker_cli_network_unix_test.go:1016:
12:49:18     c.Assert(err, checker.IsNil)
12:49:18 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc208a760a0)} ("exit status 1")
12:49:18 
12:49:18 [d47566000] exiting daemon
12:49:20 
```

**Comment by duglin** [comment]
@coolljt0725 thanks for the details - I was going to ask why that image was so slow!

**Comment by duglin** [comment]
LGTM if **all** of the tests are ok

**Comment by WeiZhang555** [comment]
Thank you all! @coolljt0725 @vdemeester @duglin

**Pull request merged**
