### PR TITLE
Replace pkg/units with docker/go-units.

### PR DESCRIPTION
**Pull request by calavera**
Add minor dependency update from libcontainer to remove circular dependencies. It won't be the last time we update libcontainer before the next major release, I think we should be okay bumping the dependency to a commit SHA here. There has only been a refactoring change between our tag and the the new SHA that doesn't modify, add or remove functionality.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by calavera** [comment]
I was wrong, and libcontainer introduced a breaking change :pensive:

**Comment by calavera** [comment]
I opened a PR in runc: https://github.com/opencontainers/runc/pull/436

**Comment by vdemeester** [comment]
:sweat:

**Comment by calavera** [comment]
libcontainer is fixed already. I pulled the changes with the new SHA here.

**Comment by tiborvass** [comment]
@calavera please separate vendoring commit

**Comment by calavera** [comment]
@tiborvass done.

**Comment by cpuguy83** [comment]
I noticed go-units has the ulimit stuff too.
Did you want to convert that over as well?

**Comment by calavera** [comment]
@cpuguy83 yes.

**Comment by calavera** [comment]
the ulimits change is going to be a separated PR because it affects runconfig, which I'm working on right now.

**Comment by cpuguy83** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
