### PR TITLE
Updated proposal for additional registries

### PR DESCRIPTION
**Pull request by miminar**
This PR updates and obsoletes #10411. It reflects current patch set for additional registries for Docker shipped by Red Hat. It's not supposed to be merged and in fact it shouldn't be. It's purpose is to keep upstream community in sync with RH's work. However, Red Hat would like ideas implemented here be considered during the definition of future interfacing with v2+ registries and discovery
endpoints.

### CODE REVIEW

**Comment by icecrime** [comment]
Removing the `status/` labels on this as it's out of the regular workflow.

Ping @crosbymichael @dmp42 FYI.

**Comment by dmp42** [comment]
Hi @miminar 

Can you join irc?

**Comment by ewindisch** [comment]
I confirm that this patch behaves as described.

**Comment by jfrazelle** [comment]
Hey! ya this is cool and I think we can discuss still but to quote the original comment:

> It's not supposed to be merged and in fact it shouldn't be.

I'm going to close because why keep open a patch that is not meant to be merged. But of course continue the discussion.

**Comment by miminar** [comment]
@ewindisch Thanks for the confirmation! And sorry for all the trouble.

**Pull request closed without merging**
