### PR TITLE
[20.10 backport] Merge fixes to pkg/system to support FreeBSD's mknod

### PR DESCRIPTION
**Pull request by dfr**
backports:

- https://github.com/moby/moby/pull/42866
- https://github.com/moby/moby/pull/43087

This allows projects that depend on pkg/system's implementation of mknod such as github.com/openshift/imagebuilder and github.com/containers/buildah to build on FreeBSD.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Overall this looks harmless to backport, so I'm ok with this; could you perhaps amend the commits, and sign-off the commits with your own DCO sign-off as well? i.e.,

```
Signed-off-by: Original Author <email>
(cherry picked from commit XXX)
Signed-off-by: Your Name <your e-mail>
```

**Comment by dfr** [comment]
I've added my own sign-off - I wasn't sure about that part since I'm not really adding much value here :). Thanks for the feedback.

**Comment by thaJeztah** [comment]
Thanks! Yes, it's a bit of a "grey" area. I know a previous check we had would fail if the sign-off wasn't the last line in the commit message, and IANAL, so just in case ❤️

**Review by thaJeztah — APPROVED** [review]
LGTM

@samuelkarp ptal

**Comment by dfr** [comment]
The test failure looks like this:

```
[2022-06-03T11:32:37.098Z] === FAIL: amd64.integration-cli TestDockerSwarmSuite/TestSwarmContainerEndpointOptions (2.17s)
[2022-06-03T11:32:37.098Z]     docker_cli_swarm_test.go:351: assertion failed: error is not nil: exit status 125: Unable to find image 'busybox:glibc' locally
[2022-06-03T11:32:37.098Z]         /usr/local/cli/docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
[2022-06-03T11:32:37.098Z]         See '/usr/local/cli/docker run --help'.
[2022-06-03T11:32:37.098Z]         
[2022-06-03T11:32:37.098Z]     --- FAIL: TestDockerSwarmSuite/TestSwarmContainerEndpointOptions (2.17s)
```
which seems unrelated to the changes in this PR

**Comment by thaJeztah** [comment]
Ah! I'll kick CI again; have been spamming the machines a bit with rebuild requests, and we don't set authentication on them, so at times we hit the rate limits on those machines

**Comment by dfr** [comment]
Looks to be the same overload issue:
```

[2022-06-03T13:06:40.172Z] === Failed
[2022-06-03T13:06:40.172Z] === FAIL: amd64.integration-cli TestDockerSwarmSuite/TestSwarmContainerEndpointOptions (2.20s)
[2022-06-03T13:06:40.172Z]     docker_cli_swarm_test.go:351: assertion failed: error is not nil: exit status 125: Unable to find image 'busybox:glibc' locally
[2022-06-03T13:06:40.172Z]         /usr/local/cli/docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
[2022-06-03T13:06:40.172Z]         See '/usr/local/cli/docker run --help'.
[2022-06-03T13:06:40.172Z]         
[2022-06-03T13:06:40.172Z]     --- FAIL: TestDockerSwarmSuite/TestSwarmContainerEndpointOptions (2.20s)
```

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
Looks like you hit the jackpot; now a flaky test 😂 (I kicked it once more)

**Comment by dfr** [comment]
Thanks for the quick turnaround!

**Pull request merged**
