### PR TITLE
docs: update apparmor to reflect recent changes

### PR DESCRIPTION
**Pull request by tophj-ibm**
updates the apparmor docs to reflect recent changes, specifically that we are no
longer saving to `/etc/apparmor.d/`. Also updates the example profiles with the current
implementation. 

@justincormack 

Signed-off-by: Christopher Jones tophj@linux.vnet.ibm.com

owl

### CODE REVIEW

**Comment by tophj-ibm** [comment]
@thaJeztah should I be opening this against https://github.com/docker/docker.github.io instead?

**Comment by thaJeztah** [comment]
@tophj-ibm oh, yes, sorry about that; depending on which version this relates to, it should go into "master" or "vnext-engine" https://github.com/docker/docker.github.io/tree/vnext-engine (if it's for 1.13)

**Comment by tophj-ibm** [comment]
np, thanks for the info!

**Comment by thaJeztah** [comment]
Thanks! The whole workflow is still WIP, so bear with us :smile:

**Pull request closed without merging**
