### PR TITLE
WiP Support for specifying .dockerignore file with --ignore-file

### PR DESCRIPTION
**Pull request by mishak87**
Client: Parsed `.dockerignore` is passed in build options field `IgnoreRules []string`.
Server: If field `IgnoreRules` is empty contents of `.dockerignore` are used (old behaviour) preserving backwards compatibility with older clients.

NOTE: I was not able to build docker locally using `make`.

```
rm: cannot remove 'autogen/winresources': Directory not empty
```

### CODE REVIEW

**Comment by mishak87** [comment]
While analyzing the code I realised that instead of adding support for different `.dockerignore` file it might be more useful to leave old code as it is and add new behavior.

Client would make list of ignore rules from `--ignore-file` contents and `--ignore` arguments and pass it to server as *ignoreList*. If *ignoreList* is specified, even if it is empty, server would use that list. If *ignoreList* is not specified it would use contents of `.dockerignore`.

What do you think @tiborvass @thaJeztah?

**Comment by mishak87** [comment]
This is probably the best I could come up with while preserving BC and introducing minimum of changes.

**Comment by thaJeztah** [comment]
Oh, thanks @mishak87, and apologies for the delay, due to holidays and the upcoming 1.10 release.

Perhaps @duglin is interested in looking at this as well, as he's done quite some things for the dockerignore parts of docker.

**Comment by mishak87** [comment]
There is backwards compatibility issue if new client uses IgnoreRules but server doesn't know about them (is older then client). I don't know if it is an issue and/or could it be handled with server version detection.

**Comment by thaJeztah** [comment]
@mishak87 Newer clients on an older server are not supported, and should be handled by [this error message](https://github.com/docker/docker/blob/baee7ae045019d33e6833043bbf86bd76e1b9d41/errors/server.go#L12-L17), so I think we should be good there :-)

**Comment by duglin** [comment]
I'd prefer if we didn't complicate thing by creating multiple ways of specifying the ignore file/list. If we were to allow for something other than .dockerignore I'd prefer to just add a

**Comment by duglin** [comment]
I'd prefer if we didn't complicate thing by creating multiple ways of specifying the ignore file/list. If we were to allow for something other than .dockerignore I'd prefer to just add a `-i .dockerignore` type of flag as they would then be consistent with the `-f Dockerfile` flag.  This would also then require a change to the API not just the CLI.

**Comment by mishak87** [comment]
@duglin For me is limiting that Dockerfile or dockerignore has to be a file (other one can be `/dev/stdin`).  Being able to specify dockerignore via arguments is more flexible because tools don't have to use temporary **file in build context** just to pass instructions.

OT: For example being able add more Dockerfile lines as and argument would be helpful for adding CI labels as a last step.

**Comment by mishak87** [comment]
Removing Dockerfile from contexts is subject of #14298 so I think my approach fits into the roadmap.

**Comment by calavera** [comment]
I feel like we should not move forward with this issue. We're very close to have the builder in its own repo and this would only complicate its extraction further. I vote to close this issue and move the discussion to the standalone builder when we have it :soon: 

/cc @tiborvass

**Comment by icecrime** [comment]
I agree with @duglin and @calavera here :-( Sorry, so many things are moving right now, but builder will be split out in just under 2 weeks.

**Comment by dominics** [comment]
@icecrime Given the builder movements have died down ("We won't go further on this effort ourselves, as backward compatibility constraint forces us to preserve a daemon-side implementation of the Builder anyway") can you please circle back around on this one?

Is the "this would only complicate [builder] extraction further" argument still valid?

**Comment by mrluc** [comment]
It seems so strange that this ability is still not present! But it may have its own logic that I don't understand.

I can specify different Dockerfiles, for use in different situations (fat builder images vs lean runner images, for instance) ... but not .dockerignore files, which determine what files are available?

**Comment by nalipaz** [comment]
Should we assume that builder has now been "split out" as per @icecrime's [comment](/docker/docker/pull/18754#issuecomment-174836620)? If so, would it make sense to reopen this for further review? I think it is still a feature that many might see as useful.

**Comment by timaschew** [comment]
Please either comment on @nalipaz or refer to some other issue (and maybe deeplink to a comment) where this discussion was or is continued.

**Pull request closed without merging**
