### PR TITLE
hack/ci/windows.ps1: stop tailing logs after stopping the daemon

### PR DESCRIPTION
**Pull request by thaJeztah**
(taken from https://github.com/moby/moby/pull/38410)

There's already a step in  "Nuke Everything", but lets' stop it after stopping the daemon as well

### CODE REVIEW

**Comment by thaJeztah** [comment]
@StefanScherer @vikramhh ptal

**Comment by vikramhh** [comment]
LGTM

**Review by StefanScherer — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Windows RS1 failure is a known flaky issue https://github.com/moby/moby/issues/38521, and for which there's a WIP PR (that stalled unfortunately); https://github.com/moby/moby/pull/38595

https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39878/runs/2/nodes/33/log/?start=0

```
[2019-09-10T22:11:10.185Z] 
[2019-09-10T22:11:10.185Z] ----------------------------------------------------------------------
[2019-09-10T22:11:10.185Z] FAIL: docker_cli_start_test.go:190: DockerSuite.TestStartReturnCorrectExitCode
[2019-09-10T22:11:10.185Z] 
[2019-09-10T22:11:10.185Z] docker_cli_start_test.go:200:
[2019-09-10T22:11:10.185Z]     c.Assert(exitCode, checker.Equals, 12, check.Commentf("out: %s", out))
[2019-09-10T22:11:10.185Z] ... obtained int = 125
[2019-09-10T22:11:10.185Z] ... expected int = 12
[2019-09-10T22:11:10.185Z] ... out: time="2019-09-10T22:11:09Z" level=error msg="error waiting for container: EOF" 
[2019-09-10T22:11:10.185Z] 
```

**Comment by thaJeztah** [comment]
Everything else is nice and green, so I think this should be good to go

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
