### PR TITLE
Only relabel /var/lib/docker on initial install

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces https://github.com/docker/docker/pull/20332

**Comment by thaJeztah** [comment]
ping @jfrazelle @ewindisch ptal, this replaces the previous PR

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
