### PR TITLE
Remove port mapper/allocator global state 

### LINKED ISSUE #11941: docker run busybox ls outputs logs client side
With current master, when I run 

`$ docker run busybox ls`

Here is the output I get:
```
time="2015-03-30T23:19:07Z" level=warning msg="port allocator - using fallback port range 49153-65535 due to error: open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory"
bin
dev
etc
home
lib
lib64
linuxrc
media
mnt
opt
proc
root
run
sbin
sys
tmp
usr
var
```

```
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 69b84c5
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 69b84c5
OS/Arch (server): linux/amd64
```

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #11941

The bug stems from the package level init reading filesystem state.  Lets not do that anymore.  Don't do package level init() that reads from disk or other out of process resources.

### CODE REVIEW

**Comment by jfrazelle** [comment]
holy crap this changes a lot, just want to make sure this is _not_ needed in 1.6.0 right

**Comment by jfrazelle** [comment]
small bug, big fix = :(

**Comment by crosbymichael** [comment]
It's needed

**Comment by jfrazelle** [comment]
dammit

**Comment by jfrazelle** [comment]
after merge I will need you to review when I cherry pick because there will def be conflicts ugh

**Comment by jfrazelle** [comment]
also fixed #11849

**Comment by crosbymichael** [comment]
Unless this isn't in 1.6 in the first place then it's not needed

**Comment by jfrazelle** [comment]
it is

**Comment by jfrazelle** [comment]
https://github.com/jfrazelle/docker/blob/bump_v1.6.0/daemon/networkdriver/portallocator/portallocator.go#L72 :cry:

**Comment by jfrazelle** [comment]
omg works on rhel MERGE IT

**Comment by jfrazelle** [comment]
after unit tests are fixed :angel:

**Comment by jfrazelle** [comment]
just to prove it, this is on RHEL LGTM https://paste.fedoraproject.org/205077/42776563/

**Comment by crosbymichael** [comment]
yah, i fix bug that I don't even know about

**Comment by vbatts** [comment]
nice work @crosbymichael 
LGTM, with a question. Is there no longer a need for OnShutdown cleanup?

**Comment by duglin** [comment]
LGTM

**Comment by estesp** [comment]
@vbatts it did nothing interesting..I'm glad to see it go :+1:  :) [meant to clean that up soon, after working in the shutdown handler code and walking through all the registered items]

**Pull request merged**
