### PR TITLE
Add a flag to enable cpu and go-routine-blocking profiling on the integration test suite

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@tianon :smile:

**Comment by dnephin** [comment]
So this still isn't giving me the profiles I expect to see. I've attached some output from the test run.

[profile1.zip](https://github.com/docker/docker/files/450711/profile1.zip)

**Comment by tonistiigi** [comment]
Afaik when the cpu sample is taken and all goroutines are unscheduled waiting on syscalls/channels nothing is recorded. So it makes sense that only some specific tasks like parsing JSON show up. Increasing the rate will get more records but I don't think that will be useful as the test runner just isn't running cpu intensive go code. For the blocking profiler it only shows the time of blocking while waiting on channel to return, `TestLogsFollowSlowStdoutConsumer` is artificially blocking by design.

**Comment by dnephin** [comment]
[According to the docs](https://golang.org/pkg/runtime/#SetBlockProfileRate) the blocking profiler should record every blocking event by default. Every http call to the daemon should be a blocking event, right? So we should still see at least one frame from almost every test.

The cpu profiler claims it only took 142 samples! The default rate is 100/second, so that matches the reported 1.4s. Even if it didn't capture everything, I would still expect 100 * 50 * 60 samples for a 50 minute runtime.

> So it makes sense that only some specific tasks like parsing JSON show up.

I agree if a few things were missing we could definitely blame it on the sampling, but there is just way too much missing for me to believe that is the case.

**Comment by tianon** [comment]
When we run the integration tests, we run the daemon as an external (and thus opaque to `go test`) binary/process, so that's probably why you're not seeing any of the daemon's usage (and most of the test runtime is spent waiting for it to do things or respond).

**Comment by dnephin** [comment]
>  so that's probably why you're not seeing any of the daemon's usage

Right, I am not expecting to see any of the daemon functions, just test functions.

> most of the test runtime is spent waiting for it to do things or respond

Yes, that's probably true, which is why I enabled the blocking profiler.

**Comment by dnephin** [comment]
I haven't been able to get any meaningful results from this yet, so I'm going to close this PR for now.

**Pull request closed without merging**
