### PR TITLE
Don't lookup container 4 times for stats

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by duglin** [comment]
@cpuguy83 I'm a bit worried about this change from a consistency perspective.  I didn't check all of them, but I think the pattern I'm seeing is that the functions on `Daemon` take generic args like the name of the container instead of the container itself (for better or worse).  So changing this for just some of the Daemon funcs will make for an inconsistent API.

My understanding is that the Daemon is meant to be pretty generic and something that is called from the HTTP/REST layer, and that we didn't want to require those higher-level layers to get the underlying model before they call the Daemon - we'd let the Daemon code do it for them.

However, having said that, I do agree with your overall concern and what I'd prefer is for the Daemon layer to be a thin shim over the real model code. IOW, a function on Daemon would immediatly do things like convert the container name into a container resource and then call the appropriate low-level function on the container resource to get its job done.  Meaning, once the conversion from "name" to "container" was done, we'd enter code that never needed the "name" again - which means we wouldn't call a Daemon func.  I know this isn't possible today for all Daemon funcs because its a mixture of "utility" funcs and "real work" funcs, but perhaps we could look at a design path to clean this up rather than introduce an inconsistency?

For example, can we take `daemon.getNetworkStats(container)` and convert it to `container.getNetworkStats()` ?

**Comment by runcom** [comment]
LGTM

**Comment by cpuguy83** [comment]
@duglin Most of the daemon functions take a container as an arg and not a name/id.
And even the functions on a container end up calling `container.daemon.foo(container)`

**Comment by duglin** [comment]
@cpuguy83 try:
`grep "func.*\*Daemon).*name string" daemon/*.go`
and I see a lot of hits.  This part of the lack of consistency I'd like to address first.  IMO, if we're taking an action on a container it should be `container.foo()` and never `daemon.foo(container)`

**Comment by duglin** [comment]
We could also force the http layer to deal with the name->container version too  :-)  I'm ok with that as long as we have a consistent model.

**Comment by cpuguy83** [comment]
@duglin We aren't telling the container to do something here, we are telling the daemon "give me information about this container".

This PR consolidates 4 name lookups, 4 potential chances of an error return.
This is also consistent with other streamed response API's (attach, logs).

**Comment by duglin** [comment]
I'll explain my bigger picture goals in a different PR later.... in the meantime, LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
