### PR TITLE
Fix apparmor version checks

### PR DESCRIPTION
**Pull request by cyphar**
The method used for checking the version of apparmor_parser
isn't actually correct (a version of 3.0 would cause the checks for
`>2.9` to break). In addition, one of the version checks (for suppressing
ptrace denials) was not correct due to the Ubuntu package having
a misleading version number (2.8.95 which is actually 2.9).

This includes a carry of #20270, as well as fixing how versions are checked.

Signed-off-by: Aleksa Sarai asarai@suse.com

### CODE REVIEW

**Comment by cyphar** [comment]
Ignore the failing documentation check -- there aren't any documentation changes in this PR.

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
