### PR TITLE
add ehazlett and johnstep to random_assign

### PR DESCRIPTION
**Pull request by vieux**
congratulations @ehazlett and @johnstep \o/

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 😈

**Review by thaJeztah — APPROVED** [review]
LGTM 🎉

**Comment by thaJeztah** [comment]
hmf accidentally hit the "update branch" button, I'll fix when I'm at my computer. Hate that button

**Comment by thaJeztah** [comment]
there. fixed it :smile:

**Pull request merged**
