### PR TITLE
Add bash completion for `docker service logs`

### PR DESCRIPTION
**Pull request by albers**
Sorry, missed this one: #28089.
Please schedule for 1.13.1.
Ping @sdurrheimer for zsh completion

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
This is not `docker swarm logs` :smile: 
Please modify the commit of the title?

**Comment by albers** [comment]
@AkihiroSuda :flushed:. Thanks for catching this.
Title and commit message are correct now.

**Comment by LK4D4** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
