### PR TITLE
expected new_container_id while testing ContainerCommit

### PR DESCRIPTION
**Pull request by lixiaobing1**
it is not "container_id " but "new_container_id"

### CODE REVIEW

**Review by vdemeester — DISMISSED** [review]
LGTM 🐸
@lixiaobing10051267 you can group multiple typo fix in `_test.go` files, it will be less PR to reviews 👼
It would also spare some CI lifecycle so that would be greatly appreciated :angel:

**Review by vdemeester — CHANGES_REQUESTED** [review]
@lixiaobing10051267 actually you should group multiple typo fix in _test.go files, it will be less PR to reviews :angel:
It would also spare some CI lifecycle so that would be greatly appreciated :angel:

I'll close the other ones.

**Review by AkihiroSuda — APPROVED** [review]
LGTM (if other typo-fix PRs are grouped together👍)

**Comment by lixiaobing10051267** [comment]
ok， has been grouped together.

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
