### PR TITLE
comment out the docker and curl lines we'll run later

### PR DESCRIPTION
**Pull request by SvenDowideit**
Docker-DCO-1.1-Signed-off-by: Sven Dowideit SvenDowideit@docker.com (github: SvenDowideit)

a follow on for #9952 

to test the examples in the `https.md` documentation, I run

`make certs ; make run` in one terminal, and then `make client` in another.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@fredlf @jamtur01 

this is an attempt to work out how to make the docs examples testable - and its not going to be trivial.

**Comment by fredlf** [comment]
Cool. What are you using as test criteria? That a command is run-able? That it runs AND does what we say it will? Just curious...

Do you need this merged or is it still WIP?

**Comment by SvenDowideit** [comment]
success atm is that `make certs; make run` and then `make client` in another terminal succeeds - and gives output that does not make me worried.

painfully, `make certs` requires interactive data entry, and you need to get the answers just right.

yes, I'd like it merged so that I don't lose it :)

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
