### PR TITLE
Remove seccomp from DOCKER_BUILDTAGS for ppc64le 

### PR DESCRIPTION
**Pull request by mlaventure**

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by runcom** [comment]
I may have missed the conversation, but why this?

**Comment by thaJeztah** [comment]
It was not enabled in 1.11.x so far, and enabling it would be adding a new feature in a patch release

**Comment by thaJeztah** [comment]
And having it work / build would require more changes

**Comment by tonistiigi** [comment]
LGTM

**Comment by justincormack** [comment]
LGTM

**Comment by thaJeztah** [comment]
@runcom no worries!

**Comment by mlaventure** [comment]
@runcom edited the commit message to specify it's for ppc :)

**Comment by tophj-ibm** [comment]
woot, thank you guys!

**Comment by thaJeztah** [comment]
Ignoring Windows TP5 failure, as it's expected on the 1.11.x branch

**Pull request merged**
