### PR TITLE
Typo fix wiildcard -> wildcard

### PR DESCRIPTION
**Pull request by alexellis**
First commit, please be understanding. The PR was raised after being encouraged to do so by @thaJeztah 

**\- What I did**

Fixed a typo in PR20784

https://github.com/docker/docker/commit/cf2611f3239d18919e437e82554cec178028612e#commitcomment-17572123

**\- How I did it**

Cloned Docker, built, ran unit + int tests, fixed typo and ran unit tests again.

**\- How to verify it**

Tests still passing.

**\- Description for the changelog**

Fixes typo in unit test to improve readability.

**\- A picture of a cute animal (not mandatory but encouraged)**

Doge

Signed-off-by: Alex Ellis alexellis2@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
No need to be scared, you did great! 

LGTM :tada: 

ping @vdemeester for review/merge

**Comment by alexellis** [comment]
@thaJeztah Thanks, and I've found a different *doge*.

**Comment by vdemeester** [comment]
LGTM 😇

**Comment by thaJeztah** [comment]
Haha! Great

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
