### PR TITLE
Update docker-py to 3.7.0

### PR DESCRIPTION
**Pull request by thaJeztah**
Full diff: https://github.com/docker/docker-py/compare/8b246db271a85d6541dc458838627e89c683e42f...ac922192959870774ad8428344d9faa0555f7ba6 / https://github.com/docker/docker-py/compare/8b246db271a85d6541dc458838627e89c683e42f..ac922192959870774ad8428344d9faa0555f7ba6

Includes https://github.com/docker/docker-py/pull/2216, which fixes a test checking for an incorrect status code (found through https://github.com/moby/moby/pull/38487 - https://github.com/moby/moby/pull/38487#issuecomment-452484199)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@shin- @LinuxMercedes

**Review by shin- — APPROVED** [review]

**Comment by LinuxMercedes** [comment]
Thanks! This patch has really come full-circle--I originally found the bug via a project I have which uses docker-py :smile:

**Comment by thaJeztah** [comment]
Looks like `python-setuptools` was needed for installing `yamllint`

**Comment by thaJeztah** [comment]
removed the changes to use `pip`; moving that to a separate PR (https://github.com/moby/moby/pull/38526), because s390x and PowerPC look to have issues with that

**Comment by thaJeztah** [comment]
ok; think I have it going now.

it just occurred to me that we don't even run the docker-py tests on s390x, powerpc or arm, so I actually want to do a follow-up to see if I can rewrite the Dockerfile to skip installation on those platforms.

CI does not (yet) use BuildKit, so skipping build-stages is not really possible yet, but perhaps with some script hacks for the time being.

**Review by yongtang — APPROVED** [review]
LGTM once janky is 🍏

**Comment by olljanat** [comment]
Ready for merge?

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
