### PR TITLE
redoing #10990 to generate Docker file for building Docker with or wi…

### PR DESCRIPTION
**Pull request by brahmaroutu**
…thout gccgo in x86, IBM Power and Z

The PR is reopen of #10990 (https://github.com/docker/docker/pull/10990)
This PR will help run docker builds with gccgo enabled for various platforms, including IBM Power, Z and x86.

Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by brahmaroutu** [comment]
ping @tianon @icecrime @jfrazelle  This PR is reintroduced to support non-x86 platforms with gccgo compiler to build Docker.

**Comment by LK4D4** [comment]
ping @tianon @jfrazelle

**Comment by duglin** [comment]
@tianon if you get a chance, could you look this one over?

**Comment by thaJeztah** [comment]
ping @tianon :heart: thanks!

**Comment by tianon** [comment]
@duglin as we discussed offline, I think this is still premature, isn't it?

**Comment by cpuguy83** [comment]
Closing per @tianon's comments.
We can re-open when we're ready for this.

**Pull request closed without merging**
