### PR TITLE
Vendoring libnetwork v0.7.0-dev.8

### LINKED ISSUE #17217: Unable to remove network "has active endpoints"
Not to sure if this belongs in this repo or libnetwork.

docker version: ```Docker version 1.9.0-rc1, build 9291a0e```
docker info:

```
Containers: 0
Images: 5
Engine Version: 1.9.0-rc1
Storage Driver: devicemapper
 Pool Name: docker-253:0-390879-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.023 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.62 GB
 Metadata Space Used: 1.7 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.797 GiB
Name: carbon1.rmb938.com
ID: IAQS:6E74:7NGG:5JOG:JXFM:26VD:IAQV:FZNU:E23J:QUAA:NI4O:DI3S
```

uname -a: ```Linux carbon1.rmb938.com 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

List the steps to reproduce the issue:
1. Create a network with a remote driver
2. Run a container connected to the network
3. Kill and Remove the container
4. Remove the network

Describe the results you received:

If the remote network driver gives an error when processing /NetworkDriver.Leave docker still kills and removes the container but does not remove the endpoint. This allows docker's internal db to think that the endpoint still exists even though the container is removed.

When you try and remove the network this error is returned

```
docker network rm net1      
Error response from daemon: network net1 has active endpoints
```

Describe the results you expected:

Docker should not be allowed to kill or remove the container if /NetworkDriver.Leave returned an error.

### LINKED ISSUE #20312: Docker 1.10.1 fails to create network bridge on start up
I seem to have the #18113 issue with Docker 1.10.1!

But it also occurs mostly when using a virtual machine (virtual box) with more than 3G of memory. Then startup of Dockers fails the most time and leaves a ```/var/lib/docker/network/files/local-kv.db```. As long as the file exists, I can not start docker. As soon as I remove it, everything is fine. I have some more hints to reproduce the problem below.

I have the following setup:
- Host: 
  - Ubuntu: 15.10
  - 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
  - Vagrant: 1.7.4 (Default on Ubuntu 15.10)
  - VirtualBox: 5.0.14 (Default on Ubuntu 15.10)
- Create a Vagrant virtual machine with VirtualBox:
  - Ubuntu 14.04 (LTS)
  - 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Inside of the VM
  - Install Puppet (3.4.3) with some modules (apt, docker, epel, etckeeper, stdlib)
  - Start Docker via Puppet manifest: latest Puppet-Docker (garether-docker) sets up ```Docker version 1.10.1, build 9e83765```

I have a Jenkins starting some of those virtual machines. Most of them require only 2048 MB of assigned RAM. But since yesterday I needed some larger instances and set the memory size for one of them to 4096 MB. This one almost always fails to start Docker and leaves the mentioned local-kv.db. Why only "almost", why not always?

I was trying around with some ideas: 
* At first I was running the puppet based setup with strace, something like ```strace -f -o /tmp/docker-problem -ttt puppet apply docker-setup.pp```. When run with strace the problem never occured, though I was also never able to see access to the local-kv.db (I guess this happens in the container?).
* Then I was trying with different memory sizes:
  * 3072 MB (always works)
  * 3584 MB: Worked some times (1 out of 3)
  * 3800 MB: Failed (only one try)
  * 4095 MB (trying to be slightly below the 4GB): Worked (only one try)
  * 4096 MB: Always fails

Maybe it's something completely different and has nothing todo with memory sizes? 

I attach one of the local-kv.db (a bzip2 in a zip) for further investigation: 
[local-kv.db.zip](https://github.com/docker/docker/files/129706/local-kv.db.zip)

### LINKED ISSUE #21240: daemon crashes when running a container in overlay network
**Output of `docker version`:**

```
Client:                                                                                                                                                                                                                                                       
 Version:      1.11.0-dev                                                                                                                                                                                                                                     
 API version:  1.23                                                                                                                                                                                                                                           
 Go version:   go1.6                                                                                                                                                                                                                                          
 Git commit:   aa76ddd                                                                                                                                                                                                                                        
 Built:        Wed Mar 16 06:10:13 2016                                                                                                                                                                                                                       
 OS/Arch:      linux/amd64                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                              
Server:                                                                                                                                                                                                                                                       
 Version:      1.11.0-dev                                                                                                                                                                                                                                     
 API version:  1.23                                                                                                                                                                                                                                           
 Go version:   go1.6                                                                                                                                                                                                                                          
 Git commit:   aa76ddd                                                                                                                                                                                                                                        
 Built:        Wed Mar 16 06:10:13 2016                                                                                                                                                                                                                       
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0                                                                                                                                                                                                                                                 
 Running: 0                                                                                                                                                                                                                                                   
 Paused: 0                                                                                                                                                                                                                                                    
 Stopped: 0                                                                                                                                                                                                                                                   
Images: 0                                                                                                                                                                                                                                                     
Server Version: 1.11.0-dev                                                                                                                                                                                                                                    
Storage Driver: overlay                                                                                                                                                                                                                                       
 Backing Filesystem: extfs                                                                                                                                                                                                                                    
Execution Driver: native-0.2                                                                                                                                                                                                                                  
Logging Driver: json-file                                                                                                                                                                                                                                     
Cgroup Driver: cgroupfs                                                                                                                                                                                                                                       
Plugins:                                                                                                                                                                                                                                                      
 Volume: local                                                                                                                                                                                                                                                
 Network: overlay null host bridge                                                                                                                                                                                                                            
Kernel Version: 4.4.5-1-ARCH                                                                                                                                                                                                                                  
Operating System: Debian GNU/Linux 8 (jessie) (containerized)                                                                                                                                                                                                 
OSType: linux                                                                                                                                                                                                                                                 
Architecture: x86_64                                                                                                                                                                                                                                          
CPUs: 4                                                                                                                                                                                                                                                       
Total Memory: 7.493 GiB                                                                                                                                                                                                                                       
Name: 967a4b9efb0c                                                                                                                                                                                                                                            
ID: XBVP:6QQV:Q6JJ:SEU7:ED43:G2IF:K3NB:YMOW:ALLT:AKZN:CAHK:F3F2                                                                                                                                                                                               
Docker Root Dir: /var/lib/docker                                                                                                                                                                                                                              
Debug mode (client): false                                                                                                                                                                                                                                    
Debug mode (server): true                                                                                                                                                                                                                                     
 File Descriptors: 13                                                                                                                                                                                                                                         
 Goroutines: 28                                                                                                                                                                                                                                               
 System Time: 2016-03-16T07:09:47.230398367Z                                                                                                                                                                                                                  
 EventsListeners: 0                                                                                                                                                                                                                                           
Registry: https://index.docker.io/v1/                                                                                                                                                                                                                         
WARNING: bridge-nf-call-iptables is disabled                                                                                                                                                                                                                  
WARNING: bridge-nf-call-ip6tables is disabled                                                                                                                                                                                                                 
Cluster store: consul://consul:8500                                                                                                                                                                                                                           
Cluster advertise: 172.18.0.4:2375
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**


**Steps to reproduce the issue:**
1. Build a swarm cluster which has the only node whose daemon is docker 1.11.0-dev.
2. Create an overlay network whose name is 'hello' in the cluster.
3. Run `docker -H :4000 run --net=hello hello-world`.


**Describe the results you received:**

hello-world container runs successfully.

**Describe the results you expected:**

Docker daemon of the swarm node crashes with the following error:

    panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                                   
    [signal 0xb code=0x1 addr=0x40 pc=0x8ab50f]                                                                                                                                                                                                               
                                                                                                                                                                                                                                                              
    goroutine 1399 [running]:                                                                                                                                                                                                                                 
    panic(0x15d4ea0, 0xc8200100b0)                                                                                                                                                                                                                            
            /usr/local/go/src/runtime/panic.go:464 +0x3e6                                                                                                                                                                                                     
    github.com/docker/libnetwork.(*resolver).ServeDNS(0xc82135e680, 0x7f21ae135f68, 0xc820d75ab0, 0xc820d58bd0)                                                                                                                                               
            /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/resolver.go:324 +0xc6f                                                                                                                                                   
    github.com/miekg/dns.(*Server).serve(0xc82135e820, 0x7f21abf1d0c8, 0xc8207587e0, 0x7f21a9ebeca8, 0xc82135e680, 0xc8213a0000, 0x2a, 0x200, 0xc8204c3080, 0xc820c5c240, ...)                                                                                
            /go/src/github.com/docker/docker/vendor/src/github.com/miekg/dns/server.go:535 +0x7c8                                                                                                                                                             
    created by github.com/miekg/dns.(*Server).serveUDP                                                                                                                                                                                                        
            /go/src/github.com/docker/docker/vendor/src/github.com/miekg/dns/server.go:489 +0x3d5   

**Additional information you deem important (e.g. issue happens only occasionally):**

Here is the debug log of docker daemon of the swarm node.

```
	DEBU[0144] Calling POST /v1.15/containers/create
	DEBU[0144] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"CpuShares":0,"Cpuset":"","Domainname":"","Entrypoint":null,"Env":null,"ExposedPorts":null,"HostConfig":{"Binds":null,"BlkioWeight":0,"CapAdd":null,"CapDrop":null,"CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","DNSOptions":[],"Devices":[],"Dns":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","KernelMemory":0,"Links":null,"LogConfig":{"config":{},"type":""},"LxcConf":null,"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"hello","OomKillDisable":false,"PidMode":"","PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"UTSMode":"","Ulimits":null,"VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{"com.docker.swarm.id":"34bf9dc5054978bc44d12d479b53f8157bde7d0971207fd34879bd93cb1ea3d9"},"MacAddress":"","Memory":0,"MemorySwap":0,"NetworkDisabled":false,"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"PortSpecs":null,"StdinOnce":false,"StopSignal":"SIGTERM","Tty":false,"User":"","VolumeDriver":"","Volumes":{},"WorkingDir":""}
	ERRO[0144] Handler for POST /v1.15/containers/create returned error: No such image: hello-world:latest
	DEBU[0144] Calling POST /v1.15/images/create?fromImage=hello-world%3Alatest
	DEBU[0144] Trying to pull hello-world from https://registry-1.docker.io v2
	DEBU[0146] Calling GET /v1.15/containers/json?all=1&size=0
	DEBU[0146] Calling GET /v1.15/volumes
	DEBU[0146] Calling GET /v1.15/networks
	DEBU[0146] Calling GET /v1.15/images/json?all=1
	DEBU[0146] Increasing token expiration to: 60 seconds
	DEBU[0148] Pulling ref from V2 registry: hello-world:latest
	DEBU[0148] pulling blob "sha256:03f4658f8b782e12230c1783426bd3bacce651ce582a4ffb6fbbfa2079428ecb"
	DEBU[0148] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
	DEBU[0149] Downloaded a3ed95caeb02 to tempfile /var/lib/docker/tmp/GetImageBlob839087981
	DEBU[0149] Downloaded 03f4658f8b78 to tempfile /var/lib/docker/tmp/GetImageBlob537481926
	DEBU[0149] Start untar layer
	DEBU[0149] Untar time: 0.031192797s
	DEBU[0149] Applied tar sha256:b652ec3a27e758f30de4742156b5d096bb19c82f2dc836e96e430323ba166ffe to ed619100298e0ecd2e8ae8f82e65f0aabdbd2190e256d157056811721d7ec5d6, size: 960
	DEBU[0149] Applied tar sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef to a2bd67d8c118b22ffb92c010846b85bcb2205ec33b2797a16e801217c8f2d64c, size: 0
	DEBU[0149] Calling GET /v1.15/images/json?all=1
	DEBU[0149] Calling GET /v1.15/images/json?all=1
	DEBU[0149] Calling POST /v1.15/containers/create
	DEBU[0149] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"CpuShares":0,"Cpuset":"","Domainname":"","Entrypoint":null,"Env":null,"ExposedPorts":null,"HostConfig":{"Binds":null,"BlkioWeight":0,"CapAdd":null,"CapDrop":null,"CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","DNSOptions":[],"Devices":[],"Dns":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","KernelMemory":0,"Links":null,"LogConfig":{"config":{},"type":""},"LxcConf":null,"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"hello","OomKillDisable":false,"PidMode":"","PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"UTSMode":"","Ulimits":null,"VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{"com.docker.swarm.id":"34bf9dc5054978bc44d12d479b53f8157bde7d0971207fd34879bd93cb1ea3d9"},"MacAddress":"","Memory":0,"MemorySwap":0,"NetworkDisabled":false,"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"PortSpecs":null,"StdinOnce":false,"StopSignal":"SIGTERM","Tty":false,"User":"","VolumeDriver":"","Volumes":{},"WorkingDir":""}
	DEBU[0149] container mounted via layerStore: /var/lib/docker/overlay/07c45e8c4ea9a25fff165477a06ab803b1dff9c7c6191b8581314e35d71c8f8b/merged
	DEBU[0149] Calling GET /v1.15/containers/json?all=1&size=0&filters={"id":["5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445"]}
	DEBU[0149] Calling GET /v1.15/containers/json?all=1&size=0&filters={"id":["5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445"]}
	DEBU[0149] Calling GET /v1.15/containers/5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445/json
	DEBU[0149] Calling GET /v1.15/containers/5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445/json
	DEBU[0149] Calling GET /v1.15/volumes
	DEBU[0149] Calling GET /v1.15/networks
	DEBU[0149] Calling POST /v1.22/containers/5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445/attach?stderr=1&stdout=1&stream=1
	DEBU[0149] Client and server don't have the same version (client: 1.10.3, server: 1.11.0-dev)
	DEBU[0149] attach: stderr: begin
	DEBU[0149] attach: stdout: begin
	DEBU[0149] Calling GET /v1.15/containers/json?all=1&size=0&filters={"id":["5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445"]}
	DEBU[0149] Calling POST /v1.15/containers/5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445/start
	DEBU[0149] form data: null
	DEBU[0149] container mounted via layerStore: /var/lib/docker/overlay/07c45e8c4ea9a25fff165477a06ab803b1dff9c7c6191b8581314e35d71c8f8b/merged
	DEBU[0149] Assigning addresses for endpoint desperate_boyd's interface on network hello
	DEBU[0149] RequestAddress(GlobalDefault/10.0.0.0/24, <nil>, map[])
	DEBU[0149] Assigning addresses for endpoint desperate_boyd's interface on network hello
	INFO[0149] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]
	INFO[0149] IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]
	DEBU[0149] Allocating IPv4 pools for network docker_gwbridge (b7da6ba2b7c2dd531b2007502fdf8cde787ea6247799f3b44023a5bbade26b53)
	DEBU[0149] RequestPool(LocalDefault, , , map[], false)
	DEBU[0149] RequestAddress(LocalDefault/172.19.0.0/16, <nil>, map[RequestAddressType:com.docker.network.gateway])
	DEBU[0149] Setting bridge mac address to 02:42:5c:a5:1d:e7
	DEBU[0149] Assigning address to bridge interface docker_gwbridge: 172.19.0.1/16
	DEBU[0149] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.19.0.0/16 ! -o docker_gwbridge -j MASQUERADE]
	DEBU[0149] /sbin/iptables, [--wait -t nat -I POSTROUTING -s 172.19.0.0/16 ! -o docker_gwbridge -j MASQUERADE]
	DEBU[0149] /sbin/iptables, [--wait -t nat -C DOCKER -i docker_gwbridge -j RETURN]
	DEBU[0149] /sbin/iptables, [--wait -t nat -I DOCKER -i docker_gwbridge -j RETURN]
	DEBU[0149] /sbin/iptables, [--wait -D FORWARD -i docker_gwbridge -o docker_gwbridge -j ACCEPT]
	DEBU[0149] /sbin/iptables, [--wait -t filter -C FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP]
	DEBU[0149] /sbin/iptables, [--wait -A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP]
	DEBU[0149] /sbin/iptables, [--wait -t filter -C FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT]
	DEBU[0149] /sbin/iptables, [--wait -I FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT]
	DEBU[0149] /sbin/iptables, [--wait -t filter -C FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
	DEBU[0149] /sbin/iptables, [--wait -I FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
	DEBU[0149] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
	DEBU[0149] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
	DEBU[0149] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
	DEBU[0149] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
	DEBU[0149] /sbin/iptables, [--wait -t filter -C FORWARD -o docker_gwbridge -j DOCKER]
	DEBU[0149] /sbin/iptables, [--wait -I FORWARD -o docker_gwbridge -j DOCKER]
	DEBU[0149] /sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION]
	DEBU[0149] /sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION]
	DEBU[0149] /sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION]
	DEBU[0149] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP]
	DEBU[0149] /sbin/iptables, [--wait -I DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP]
	DEBU[0149] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP]
	DEBU[0149] /sbin/iptables, [--wait -I DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP]
	WARN[0149] running inside docker container, ignoring missing kernel params: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
	DEBU[0150] Assigning addresses for endpoint gateway_5986976e2635's interface on network docker_gwbridge
	DEBU[0150] RequestAddress(LocalDefault/172.19.0.0/16, <nil>, map[])
	DEBU[0150] Assigning addresses for endpoint gateway_5986976e2635's interface on network docker_gwbridge
	DEBU[0150] Programming external connectivity on endpoint gateway_5986976e2635 (2ff801bb3a7b1b3e49ab413f5742457c38754dfc4b497bfd8115aac458aabe64)
	DEBU[0150] Calling GET /v1.15/networks
	DEBU[0150] Calling GET /v1.15/containers/json?all=1&size=0&filters={"id":["5986976e2635862bc1b17208243626787702bf180baedb11f1368024f7f9c445"]}
	DEBU[0150] /sbin/iptables, [--wait -t nat -A OUTPUT -d 127.0.0.11 -p udp --dport 53 -j DNAT --to-destination 127.0.0.11:39356]
	DEBU[0150] /sbin/iptables, [--wait -t nat -A POSTROUTING -s 127.0.0.11 -p udp --sport 39356 -j SNAT --to-source :53]
	DEBU[0150] /sbin/iptables, [--wait -t nat -A OUTPUT -d 127.0.0.11 -p tcp --dport 53 -j DNAT --to-destination 127.0.0.11:38896]
	DEBU[0150] /sbin/iptables, [--wait -t nat -A POSTROUTING -s 127.0.0.11 -p tcp --sport 38896 -j SNAT --to-source :53]
	DEBU[0150] To resolve: metadata.google.internal in
	DEBU[0150] To resolve: metadata.google in internal
	DEBU[0150] To resolve: metadata in google.internal
	DEBU[0150] Querying ext dns udp:8.8.8.8 for metadata.google.internal.[1]
	DEBU[0150] Connect failed, dial udp 8.8.8.8:53: connect: network is unreachable
	DEBU[0150] Querying ext dns udp:8.8.4.4 for metadata.google.internal.[1]
	DEBU[0150] Connect failed, dial udp 8.8.4.4:53: connect: network is unreachable
	DEBU[0150] Querying ext dns udp:8.8.8.8 for metadata.google.internal.[28]
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x40 pc=0x8acc0f]

	goroutine 423 [running]:
	panic(0x15df1c0, 0xc8200100b0)
			/usr/local/go/src/runtime/panic.go:464 +0x3e6
	github.com/docker/libnetwork.(*resolver).ServeDNS(0xc82131f860, 0x7f49acef58c0, 0xc8201540e0, 0xc820e41e60)
			/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/resolver.go:324 +0xc6f
	github.com/miekg/dns.(*Server).serve(0xc82131fa00, 0x7f49ac50c460, 0xc8207ac2d0, 0x7f49ac517fd8, 0xc82131f860, 0xc8212f0a00, 0x2a, 0x200, 0xc820029c30, 0xc820d280c0, ...)
			/go/src/github.com/docker/docker/vendor/src/github.com/miekg/dns/server.go:535 +0x7c8
	created by github.com/miekg/dns.(*Server).serveUDP
			/go/src/github.com/docker/docker/vendor/src/github.com/miekg/dns/server.go:489 +0x3d5
```

### PR DESCRIPTION
**Pull request by aboch**
- Fixes https://github.com/docker/docker/issues/21240
- Fix netns path setting from hook (for containerd integration)
- Fixes https://github.com/docker/docker/issues/17217 (may also fix https://github.com/docker/docker/issues/20312)
- Windows net driver fixes
- Ipvlan/Macvlan driver fixes

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
@aboch I see there is an issue with the `Vagrantfile` because of our recent gitignore changes. Do you want me to make a fix for that so you don't have to include zfs files here?

**Comment by aboch** [comment]
Thanks @tonistiigi, realized that the vendor script is no longer skipping the Vagrant files, and updated the PR.

**Comment by tonistiigi** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Pull request merged**
