### PR TITLE
Re-vendor Notary and docker/go

### PR DESCRIPTION
**Pull request by cyli**
This updates Notary and updates `github.com/jfrazelle/go` to be `github.com/docker/go`.

This also includes @thaJeztah's changes in #19739 which update the notary versions in all the Dockerfiles for different architectures to use the notary tag.  This PR bumps the version to `docker-1.10-4` instead of `docker-1.10-3`.

Repeating his comment re: the versions here:
- Dockerfile.aarch64 uses Golang 1.5.3, so guess we should be safe there
- Dockerfile.armhf uses Golang 1.4.3, but already used Notary 1.10-2 (not sure which version of notary added the Yubico things)
- Dockerfile.ppc64le has notary disabled; do we need it enabled in there?
- Dockerfile.s390x mentions "after we upgrade to Go 1.5+". I don't see a Go version in there, only `GO_TOOLS_COMMIT`; is that what determins the Go version in that file? If so, we should probably should not change it

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cyli what changes does it bring in Notary? Is this for the 1.10 release?

**Comment by cyli** [comment]
@thaJeztah Oh oops, sorry, forgot to include that.  :)  This is mostly code cleanup, some new features and lots of better error reporting/help messages for the notary CLI, and more tests.

The things that affect behavior with the docker client are:
1.  Changed some error messages if we cannot reach the notary server or if there's no trust data.
2.  Always fall back on the cached metadata now if we can't get a new timestamp from the server (previously sometimes it would fall back, sometimes it wouldn't) and log a warning to the user.
3.  Changing the dependency `jfrazelle/go` to `docker/go`

I don't think this is necessarily for the 1.10 release - the notary tag was docker-1.10-4 because I had misunderstood where it needed to go.  There is some discussion as to whether it'd be nice to change some log levels for the 1.10 release, though, so as to be less confusing (we log some messages as errors right now that can be recovered from)

**Comment by thaJeztah** [comment]
@cyli cool, thanks; I'll keep it off the milestone for now then

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
