### PR TITLE
Fix go vet errors

### PR DESCRIPTION
**Pull request by chrisseto**
Fix https://github.com/docker/docker/issues/14993

### CODE REVIEW

**Comment by runcom** [comment]
LGTM, thanks @chrisseto 

windows janky won't turn green tho :(

**Comment by chrisseto** [comment]
@runcom Any chance its probabilistic? 
screen shot 2015-07-25 at 18 22 35
Could be a networking error? But those addresses look like test fixtures.
Thoughts? ¯\_(ツ)_/¯

**Comment by runcom** [comment]
Yes don't worry about it :) there are some issues with the ci servers today

**Comment by chrisseto** [comment]
:+1: Cool, so rerun the tests tomorrow or something?

**Comment by icecrime** [comment]
No need ;-) LGTM thank!

**Pull request merged**
