### PR TITLE
Fix docs for #14047

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This updates the docker version docs for #14047

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Can you update the man page as well? https://github.com/docker/docker/blob/master/man/docker-info.1.md and check if there's other examples as well (just to be sure)

**Comment by jhowardmsft** [comment]
@thaJeztah  I grepped the docs/ directory and could find any. Didn't think to check man/ but that's updated now too.

**Comment by SvenDowideit** [comment]
LGTM - @moxiegirl

**Comment by thaJeztah** [comment]
LGTM can't check on my mobile right now, but the CLI docs were just split into separate files (one per command), so I think this needs a rebase

**Comment by moxiegirl** [comment]
@jhowardmsft @thaJeztah It might be easier to just back out your changes to `cli.md` and instead add them to the new, specific command file.

**Comment by jhowardmsft** [comment]
@moxiegirl Sure - no problem

**Comment by jhowardmsft** [comment]
Reworked after the split.

**Comment by moxiegirl** [comment]
Thank you @jhowardmsft for the quick turn around.  LGTM for the merge.

**Pull request merged**
