### PR TITLE
Integration: remove redundant kernel version check for MACVlan

### PR DESCRIPTION
**Pull request by thaJeztah**
The daemon requires kernel 3.10 or up to start, so there's no need to check if the daemon is kernel 3.8 or up.

https://github.com/moby/moby/blob/3d21b86e0a44932bfb4a3f882d8a7c9065432d40/daemon/daemon_unix.go#L319-L324

### CODE REVIEW

**Comment by thaJeztah** [comment]
Pushed an extra commit to don't build the package on Windows, and adding a missing "import" comment

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
(rebased to get the latest fixes in)

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
