### PR TITLE
docs: fix incorrect package name on Oracle Linux

### PR DESCRIPTION
**Pull request by thaJeztah**
Replaces https://github.com/docker/docker/pull/18345

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @Djelibeybi :)

**Comment by Djelibeybi** [comment]
:+1: LGTM. Nice catch.

**Comment by estesp** [comment]
LGTM

**Comment by thaJeztah** [comment]
Author LGTM, thanks for checking both!

**Pull request merged**
