### PR TITLE
remove unused headers in secret_create.go

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

**- What I did**
1. remove unused headers in secret_create.go

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Comment by YuPengZTE** [comment]
LGTM

**Comment by cpuguy83** [comment]
ping @ehazlett

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
