### PR TITLE
devmapper: some explination of `docker info`

### PR DESCRIPTION
**Pull request by vbatts**
for @SvenDowideit :-)

Signed-off-by: Vincent Batts vbatts@hashbangbash.com

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM - yay :) @vbatts

**Comment by jfrazelle** [comment]
prettyyyyyyy

**Comment by vbatts** [comment]
... Is that jess-speak for LGTM? ;-)

**Comment by jfrazelle** [comment]
well it's docs so I was trying to persuade hahah, but LGTM

**Pull request merged**
