### PR TITLE
Integration: fix various issues in "config" and "secret" tests

### PR DESCRIPTION
**Pull request by thaJeztah**
See individual commits for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
marked as "WIP", because some more changes are coming

**Comment by thaJeztah** [comment]
rebased to get rid of the test results of the old Jenkins

**Comment by thaJeztah** [comment]
ping @kolyshkin @vdemeester PTAL

**Review by vdemeester — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Failure is unrelated; https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39771/runs/6/nodes/202/log/?start=0

```
     --- FAIL: Test/DockerSuite/TestRunInteractiveWithRestartPolicy (11.50s)
         docker_cli_run_test.go:1802: assertion failed: 
             Command:  /usr/local/cli/docker run -i --name test-inter-restart --restart=always busybox sh
             ExitCode: 0
             Stdout:   
             Stderr:   
            
            Failures:
            ExitCode was 0 expected 11
```

**Comment by tao12345666333** [comment]
Flaky test https://github.com/moby/moby/issues/38521

```
[2019-09-13T01:39:32.734Z]     --- FAIL: Test/DockerSuite/TestStartReturnCorrectExitCode (9.30s)
[2019-09-13T01:39:32.734Z]         docker_cli_start_test.go:198: assertion failed: 125 (exitCode int) != 12 (int): out: time="2019-09-13T01:38:16Z" level=error msg="error waiting for container: EOF" 
[2019-09-13T01:39:32.734Z]             
[2019-09-13T01:39:32.734Z]         check_test.go:123: assertion failed: error is not nil: Error response from daemon: container 0107f1043a6c2e16c241e47b5fdd3a0005b22588603b8ddd2f8da76eb004e6ee: driver "windowsfilter" failed to remove root filesystem: hcsshim::GetComputeSystems: Access is denied.: failed to remove 0107f1043a6c2e16c241e47b5fdd3a0005b22588603b8ddd2f8da76eb004e6ee
```
https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39771/runs/8/nodes/50/steps/173/log/?start=0

**Comment by thaJeztah** [comment]
ping @tiborvass @kolyshkin PTAL

**Comment by thaJeztah** [comment]
rebased. ping @tiborvass @kolyshkin @cpuguy83 @AkihiroSuda PTAL

**Review by vdemeester — APPROVED** [review]
still LGTM :stuck_out_tongue:

**Comment by thaJeztah** [comment]
rebased because the `gotest.tools` import path changed to `v3`

ping @cpuguy83 @tiborvass @AkihiroSuda PTAL

**Comment by thaJeztah** [comment]
rebased again to get a fresh run of CI

**Comment by thaJeztah** [comment]
ping @kolyshkin @cpuguy83 @AkihiroSuda ptal 🤗

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
