### PR TITLE
Do not use keyservers to fetch GPG keys for apt

### LINKED ISSUE #13555: Key server down for get.docker.com
Description of problem:
Key server down for get.docker.com

`docker version`:
Docker version 1.6.2, build 7c8fca2

`docker info`:
Containers: 2
Images: 47
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 6
Total Memory: 2.939 GiB
Name: vagrant-ubuntu-trusty-64.localdomain
ID: DID2:SFJ6:6GK2:3AUD:TIM2:4LCH:MWRL:JHCA:6ZMJ:ANUD:6Y3M:SP5R
WARNING: No swap limit support

`uname -a`:
Linux vagrant-ubuntu-trusty-64.localdomain 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox

How reproducible:
wget -qO- https://get.docker.com/ | sh

Steps to Reproduce:
1. Try to install docker with wget script

Actual Results:

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.xIf9seuuMo --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7:
```

Expected Results:

```
Install successful
```

Additional info:

Instead a workaround was found by changing the key server to be 

```
hkp://keyserver.ubuntu.com:80
```

There should likely be a fallback option so that the script doesn't fail on the off chance the primary key server is down.

### LINKED ISSUE #28510: RFE: Please fix the Flakey GPG Key Import Fails
# Description
Occasionally, the GPG keys fail to be imported. 

The Docker GPG keys fail to import during an Packer build. With a little Googling this problem seems widespread.  I've seen mention of this with variant conditions all with the same result. I don't believe this is a Packer problem as much as that Packer exposes the issue early in the OS install process and therefore seems to be related. 

This behavior seems random but I've isolated at least 1 aspect of the error, [dash][2]. Since Packer executes all scripts defined in `"provisioners"` with `sudo` root is the user executing them. On inspection, the root user - by default - uses `sh` to execute; `/bin/sh` is a softlink `dash`. It's worth mentioning:
  * dash is only invoked at this early stage because it is the result of a process, not initiated by a user after login. 
  * **_after login_** users have a proper bash shell
  * dash is a POSIX-compliant shell so this should not happen.

However, there may be other causes for the same/similar failures.

## TEST Steps: a failed run
1. [Download][3] Packer and install it
2. [Download][4] VirtualBox and install it
3. git clone git@github.com:chef/bento.git
4. Edit: debian-8.6-amd64.json; search for  "scripts":
5. Add [scripts/common/autoprep.sh][5] after `"scripts/common/metadata.sh",`
6. Add [scripts/debian/inst-docker.sh][6] after `"scripts/debian/update.sh",`
7. Run the automation: `packer build --only=virtualbox-iso debian-8.6-amd64.json`
8. The build will fail while attempting to pull the docker GPG key:

## Actual Results
```bash
    virtualbox-iso: + apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.tCXkthl6S4 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
    virtualbox-iso: ?: [fd 4]: read error: Connection reset by peer
    virtualbox-iso: gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D partially retrieved (probably corrupt)
    virtualbox-iso: gpg: no valid OpenPGP data found.
    virtualbox-iso: gpg: key 2C52609D: no valid user IDs
    virtualbox-iso: gpg: this may be caused by a missing self-signature
    virtualbox-iso: gpg: Total number processed: 1
    virtualbox-iso: gpg:           w/o user IDs: 1
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2
```

## TEST Steps: a successful run
1. Edit `scripts/common/autoprep.sh`; uncomment Lines 16-19.
2. Tell the Debian installer to set the dash boolean to false in `http/debian-8/preseed.cfg`; e.g.:
```bash
...
  /usr/lib/pre-pkgsel.d/20install-hwpackages                                       
d-i dash dash/sh boolean false    # just add this line between these existing ones, without this comment
d-i time/zone string UTC                                                           
...
```
3. Re-run the automation. 

## Expected Results

```bash
...
    virtualbox-iso: + apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.RgYU2mnHa6 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
    virtualbox-iso: ?: [fd 4]: read error: Connection reset by peer
    virtualbox-iso: gpg: key 2C52609D: public key "Docker Release Tool (releasedocker) <docker@docker.com>" imported
    virtualbox-iso: gpg: Total number processed: 1
    virtualbox-iso: gpg:               imported: 1  (RSA: 1)
    virtualbox-iso: + apt-get update
    virtualbox-iso: Hit http://security.debian.org jessie/updates InRelease
    virtualbox-iso: Hit http://security.debian.org jessie/updates/main Sources
...
```

### Additional Info
I have not had the time for root-cause analysis and likely won't. My feeling is that the key is not being presented/distributed in a way that a purely POSIX-compliant interpreter (dash) can properly process it. These findings will be left to your engineers to decide their value and take the required action.

Being adherent to the POSIX requirements _is_ the method of guaranteeing proper transaction results.  I'm quite certain the Debian engineers examine and select packages meticulously and that baking-in something like dash was very attractive because of its POSIX conformity. FWIW, those guys are hardened psychos that only see the world in this pure form; and I'm happy they do it. 

This is why it's my _"feeling"_. 

**Output of `docker version`:**

```bash
$ docker --version
Docker version 1.12.3, build 6b644ec
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 494.4 MiB
Name: debian-8
ID: RWJ4:ETMG:XCFD:RDIC:7IXA:5UTJ:GF67:SHRU:3F6H:GTW5:CVWD:YUYW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Based on the nature of the issue the results should be consistent regardless of the environment.

[1]: https://www.packer.io/
[2]: https://wiki.ubuntu.com/DashAsBinSh/Spec
[3]: https://www.packer.io/downloads.html
[4]: https://www.virtualbox.org/wiki/Downloads
[5]: https://gist.github.com/todd-dsm/f9f542e8878cb4574fad3db026c16e7d
[6]: https://gist.github.com/todd-dsm/81346267264c9b221186946ba12dd5d7

### PR DESCRIPTION
**Pull request by justincormack**
The keyserver infrastructure is unreliable, and just adds another point
of failure without adding any security. Instead, commit the key used at
build time for ZFS to the repo, and inline our signing key into the
install script rather than just its fingerprint.

fix #28510
fix #13555

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Note I removed the `rpm_import_repository_key` function as it was unused, for RPM the keys are fetched from the repo.

Please can reviewers verify the keys!

cc @andrewhsu @tiborvass @vieux 

cute-owl

### CODE REVIEW

**Comment by justincormack** [comment]
Using a static `rpm_import_repository_key` seems kind of better than checking from the repo, but I haven't looked at the rpm security mechanism in detail recently. This is not currently being used so I removed the dead code, but maybe it should be, seems a good time to review.

**Comment by aaronlehmann** [comment]
Big +1 - I've been arguing for this for awhile.

**Comment by diogomonica** [comment]
I think the major disadvantage is losing the ability of revoking the key.

/cc @cyli thoughts?

**Comment by justincormack** [comment]
@diogomonica hmm, this does not really affect revocation (for `apt`), or indeed key rollover, as either way we add the key to your installation at the point where you run the `get.docker.com` install script. The only difference would be if we revoke from the keyserver before changing the script/docs. It means we are currently unable to do key rotation as everyone has the key hard installed. I think for rotation the best practise for `apt` may be to add the key into a package that we can then update (signed with old key).

**Comment by cyli** [comment]
Once the key is installed, apt doesn't seem to automatically update it from the gpg servers?  I added a key, then revoked it, and running `apt-get update` and `apt-get key-update` don't seem to actually update them - it only gets the revocation if I do `apt-key adv --recv-key <key>` or `apt-key adv --refresh-keys` (or possibly some other gpg options).  So I think @justincormack is correct in that this wouldn't affect existing revocation behavior for:

1.  Folks who have already run the install script some time in the past, and are updating docker by doing `apt-get update` - for these folks, we can still publish a revocation to public key servers, and then if they do an `apt-key adv --refresh-keys` they would also get the revocation.
1.  Folks who are installing docker for the first time on a system by using the latest install script from `get.docker.com` - they'd get the latest key.

If someone had cached older (pre-revocation) install script, though, they would not be able to tell that the key on this older script had been revoked.  In a sense, the key servers serve as a (admittedly not very good) sort of freshness check on install script itself.  I'm not sure how common this use case is, or if we care to support it (they should probably handle cache invalidation on their own anyway) but if so, perhaps we can provide that check a different way.

**Comment by justincormack** [comment]
@cyli I don't think we expect people to cache the install script, so I think that use case is fairly rare. It does sound like we should work out how to do revocation/key rollover. cc @andrewhsu

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
