### PR TITLE
cleaning up more stuff in vendor

### PR DESCRIPTION
**Pull request by caarlos0**
**\- What I did**

There are still a lot of files in vendor that are not actually used. In this PR I'm removing the ones related to CIs like travis and others.

**\- How I did it**

Added a `for` loop for known files and `exec` `rm`ing them. 

**\- How to verify it**

ran `hack/vendor.sh`

**\- Description for the changelog**

Cleaning up CI files from vendor

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
/cc @thaJeztah @justincormack @tiborvass

**Comment by LK4D4** [comment]
LGTM

**Comment by caarlos0** [comment]
Thanks 👍

**Comment by thaJeztah** [comment]
nice! thanks!

**Pull request merged**
