### PR TITLE
consistent variable names in api/server/router

### PR DESCRIPTION
**Pull request by MHBauer**
- banish 'daemon'

purely cosmetic, but in theory it's not necessarily a daemon anymore.

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by duglin** [comment]
LGTM if janky is happy

**Comment by icecrime** [comment]
@MHBauer Any chance you could please investigate that flaky test above? :-( Thanks

**Comment by MHBauer** [comment]
@icecrime sure, looking

**Comment by vdemeester** [comment]
Oh `TestUpdateRestartPolicy` is pretty new.. ping @WeiZhang555 :stuck_out_tongue_closed_eyes:

**Comment by MHBauer** [comment]
Yea, test comes from ff3ea4c90f2ede5cccc6b49c4d2aad7201c91a4c, so that's who I would ping. 

We're not even getting into the test body here. Looking at the logs, the daemon appears to die after finishing docker_cli_run_test.go. Not sure if the test is related.

**Comment by vdemeester** [comment]
@MHBauer ah was on the phone, didn't check the Jenkins output. The janky error is strange too.

**Comment by calavera** [comment]
LGTM those failures are **NOT** related to this change.

**Comment by WeiZhang555** [comment]
I'll have a look into the flaky test. But it's very strange that it failed on a very simple docker run command.

**Comment by WeiZhang555** [comment]
Ah, I think it's not a big problem, it's caused by broken HTTP connection.
```
19:48:01 ----------------------------------------------------------------------
19:48:01 FAIL: docker_cli_update_test.go:11: DockerSuite.TestUpdateRestartPolicy
19:48:01 
19:48:01 docker_cli_update_test.go:12:
19:48:01     out, _ := dockerCmd(c, "run", "-d", "--restart=on-failure:3", "busybox", "sh", "-c", "sleep 1 && false")
19:48:01 C:/Jenkins/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
19:48:01     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
19:48:01 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0820ef740)} ("exit status 125")
19:48:01 ... "run -d --restart=on-failure:3 busybox sh -c sleep 1 && false" failed with errors: C:\CI\CI-a376186\docker.exe: An error occurred trying to connect: Post http://10.0.0.20:2375/v1.23/containers/create: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it..
19:48:01 See 'C:\CI\CI-a376186\docker.exe run --help'.
19:48:01 , exit status 125
19:48:01 
19:48:03 An error occurred trying to connect: Get http://10.0.0.20:2375/v1.23/containers/json?all=1&filters=%7B%22status%22%3A%7B%22paused%22%3Atrue%7D%7D: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:03 
19:48:04 An error occurred trying to connect: Get http://10.0.0.20:2375/v1.23/containers/json?all=1: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:04 
19:48:07 
19:48:07 ----------------------------------------------------------------------
19:48:07 FAIL: docker_cli_run_test.go:275: DockerSuite.TestUserDefinedNetworkAlias
19:48:07 
19:48:07 docker_cli_run_test.go:277:
19:48:07     dockerCmd(c, "network", "create", "-d", "bridge", "net1")
19:48:07 C:/Jenkins/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
19:48:07     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
19:48:07 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0824612c0)} ("exit status 1")
19:48:07 ... "network create -d bridge net1" failed with errors: An error occurred trying to connect: Post http://10.0.0.20:2375/v1.23/networks/create: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:07 , exit status 1
19:48:07 
19:48:09 An error occurred trying to connect: Get http://10.0.0.20:2375/v1.23/containers/json?all=1&filters=%7B%22status%22%3A%7B%22paused%22%3Atrue%7D%7D: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:09 
19:48:10 An error occurred trying to connect: Get http://10.0.0.20:2375/v1.23/containers/json?all=1: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:10 
19:48:13 
19:48:13 ----------------------------------------------------------------------
19:48:13 FAIL: docker_cli_run_test.go:201: DockerSuite.TestUserDefinedNetworkLinks
19:48:13 
19:48:13 docker_cli_run_test.go:203:
19:48:13     dockerCmd(c, "network", "create", "-d", "bridge", "udlinkNet")
19:48:13 C:/Jenkins/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
19:48:13     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
19:48:13 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc082428840)} ("exit status 1")
19:48:13 ... "network create -d bridge udlinkNet" failed with errors: An error occurred trying to connect: Post http://10.0.0.20:2375/v1.23/networks/create: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:13 , exit status 1
19:48:13 
19:48:15 An error occurred trying to connect: Get http://10.0.0.20:2375/v1.23/containers/json?all=1&filters=%7B%22status%22%3A%7B%22paused%22%3Atrue%7D%7D: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:15 
19:48:16 An error occurred trying to connect: Get http://10.0.0.20:2375/v1.23/containers/json?all=1: dial tcp 10.0.0.20:2375: connectex: No connection could be made because the target machine actively refused it.
19:48:16 
19:48:19 
19:48:19 ----------------------------------------------------------------------
```

We can handle this if it happens often.

**Pull request merged**
