### PR TITLE
Update Microsoft/go-winio to version 0.4.19

### PR DESCRIPTION
**Pull request by awmirantis**
Signed-off-by: Adam Williams <awilliams@mirantis.com>

Update Microsoft/go-winio to 0.4.19. A change in this version is needed for a future fix to using docker data root on a VHDX.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like this replaces https://github.com/moby/moby/pull/42307

**Review by thaJeztah — APPROVED** [review]
LGTM (assuming CI goes green 😅)

**Review by tianon — APPROVED** [review]
Windows CI passed :joy: :see_no_evil:

LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by awmirantis** [comment]
Looks like this has passed all checks, could someone please merge this?

**Pull request merged**
