### PR TITLE
Update engine api to use net/context.Context all accross the client API

### PR DESCRIPTION
**Pull request by vdemeester**
Updating `engine-api` vendor to make `docker/docker` up-to-date with docker/engine-api#140 (@stevvooe). I felt this change should be vendored quick and on its own to ease the review (and the next PR that needs to vendor `engine-api`) 🐙.

Hopefully, all is green 🐸.

/cc @calavera @cpuguy83 @stevvooe @runcom @LK4D4 @tiborvass 

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by LK4D4** [comment]
That's really cool.

**Comment by calavera** [comment]
@vdemeester you need to rebase master, but otherwise LGTM

**Comment by stevvooe** [comment]
@vdemeester Thanks for taking this on. I wasn't going to have time until the end of this week.

Looks like we can start using context to control command-level timeouts! :chart_with_upwards_trend: 

LGTM

**Comment by cpuguy83** [comment]
Looks like we have a test timeout.

**Comment by vdemeester** [comment]
@calavera hum, I'm rebased against master (the Cgroups PR has not been merged yet).
@cpuguy83 yep, investigating why.

**Comment by vdemeester** [comment]
Okay, I found the culprit in `ImageImport`, see docker/engine-api#152 for the fix.
I'll update the PR once merged.

**Comment by vdemeester** [comment]
Updated the vendoring of engine-api and added a commit to remove `Vagrantfile` from vendoring (it's causing `vendor` build check to fail otherwise, see https://github.com/docker/docker/pull/21217/files#diff-a084b794bc0759e7a6b77810e01874f2L17).

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
