### PR TITLE
[WIP] docs: add storage-driver compatibility matrix

### PR DESCRIPTION
**Pull request by thaJeztah**
This is a quick PR to see if we're interested in adding this information (and if this is the right place to add it).

This table is a direct copy (slightly formatted) of the table @unclejack provided in https://github.com/docker/docker/issues/4036#issuecomment-76723060 (hope that's ok - I can add your name to the commit message), but obviously outdated by now.

TODO's
- Add newer versions of existing distributions
- Add other distro's (all?)
- Add bfs-compatibility (placeholders are added)

To be discussed:
- Are we interested in adding this?
- Are there concerns on keeping this list up-to-date?

### CODE REVIEW

**Comment by thaJeztah** [comment]
Some extra info; @moxiegirl is currently working on documentation for storage drivers. This table could be useful information, but it obviously needs an update, and there are concerns if this information is changing much and wether or not we would be able to maintain it.

Possibly more generic distro information could help (e.g. Ubuntu 15.04 and above.., Kernel x.x.x and above)

**Comment by unclejack** [comment]
@thaJeztah This is a good idea, but we need to think about a way to update this for older versions as well. Things change over time when it comes to support. This support includes various types of support: support from the community, support from the maintainers, support from Docker Inc, support from the main kernel of that distribution, support from that distribution's vendor and support from that distribution's community.

Perhaps we should have some documentation that exists outside of the versioned documentation. For example, devicemapper should be marked as unsupported for static binaries on all Docker versions, but this is a change which affects all versions. There will be changes similar to this one in the future and that's why I think we need to think about having this outside of the version specific documentation.

**Comment by thaJeztah** [comment]
Thanks @unclejack, yes preserving docs for older versions would be helpful here (although, of course, we recommend our users to keep up to date). I saw it's being worked on here; https://github.com/docker/docs.docker.com/issues/35

**Comment by moxiegirl** [comment]
Just in general relying on documentation let alone `old documentation` to get information to people is not the best approach.  Always best to put something automated in the code *before* using the doc to *fix* or *fill* a feature gap.

The ideal situation to me would be if I am issuing the `docker daemon   --storage-driver="foo"` command and the driver I'm setting doesn't work on the backing filesystem, the command should report an error. The error should provide some information about the conditions under which that driver **is** supported.    

Most likely y'all are thinking this way. As I told Seb if maintaining this table is largely dependent on manual interviews with the community --- we have to balance our short staffed writing team with the return from the table.   Right now, maintaining this sounds entirely manual.

**Comment by thaJeztah** [comment]
closing this for now, because we have improved the documentation around storage drivers, but happy to reopen if people think this is still useful (and easy to maintain)

**Pull request closed without merging**
