### PR TITLE
Added support for build event

### LINKED ISSUE #15211: Docker Build event
It doesn't seem that `docker build` triggers any event - Could we get a `build` event triggered when it completes?
Maybe something like:
`daemon.eventsService.Log("build", logName, "")`

The doc doesn't seem to hint at the above being triggered:
https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.21.md#monitor-dockers-events

### PR DESCRIPTION
**Pull request by FrenchBen**
**\- What I did**
It's an attempt at porting PR #15216 over which will finally close #15211

**\- How I did it**
I copied what I could, then compiled it with tests.

**\- How to verify it**
`make test`

**\- Description for the changelog**
Triggers an event log when a build is made, allowing for listeners to know a build was started

**\- A picture of a cute animal (not mandatory but encouraged)**
doggie

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @FrenchBen tests are failing;

```
21:14:29 ----------------------------------------------------------------------
21:14:29 FAIL: docker_cli_events_test.go:304: DockerSuite.TestEventsBuild
21:14:29 
21:14:29 docker_cli_events_test.go:325:
21:14:29     c.Fatalf("build should be build, not %#v", buildEvent)
21:14:29 ... Error: build should be build, not []string{"2016-09-13T21:14:28.861798526Z", "container", "kill", "fe3587a0763e017bd9114f004d9192763222a1cd1f66d7689be00ff964edc622", "(image=busybox,", "name=foo,", "signal=9)"}
21:14:29 
21:14:30 
21:14:30 ----------------------------------------------------------------------
```

**Comment by FrenchBen** [comment]
@thaJeztah I'll check to see where I failed 🍂

**Comment by justincormack** [comment]
Needs a rebase now.

**Comment by thaJeztah** [comment]
```
03:06:19 
03:06:19 ----------------------------------------------------------------------
03:06:19 FAIL: docker_cli_events_test.go:273: DockerSuite.TestEventsBuild
03:06:19 
03:06:19 docker_cli_events_test.go:287:
03:06:19     c.Assert(parseEventAction(c, events[nEvents-5]), checker.Equals, "build")
03:06:19 ... obtained string = ""
03:06:19 ... expected string = "build"
03:06:19 
```

**Comment by thaJeztah** [comment]
ping @FrenchBen I'll close this for now, but let us know when you're ready to work on this again

**Comment by FrenchBen** [comment]
thanks @thaJeztah I'll make sure to follow up when bandwidth permits!

**Pull request closed without merging**
