### PR TITLE
Add built-in support for aliases

### LINKED ISSUE #16702: Add built-in support for aliases in docker CLI
It will be nice to have a built-in system of aliases in the docker CLI. 

This could help users to define complex "one-liner" they use to join a running container, clean up, start a new ubuntu or playing a nice hello world instead of using bash aliases. Built-in aliases can reuse your bash completion and are well integrated with your environment

Check out this video : https://youtu.be/ZfP-K2AYtbI

@agouriou @ggerbaud and my self have already implemented this feature during the docker global hackday, PR to follow

### PR DESCRIPTION
**Pull request by mathieu-pousse**
Implementation of issue #16702 done during the global hack day

@agouriou @ggerbaud @mathieu-pousse

### CODE REVIEW

**Comment by thaJeztah** [comment]
@mathieu-pousse looks like you forgot to sign-off the second commit (https://github.com/ZenikaOuest/docker/commit/fbb9ffddaa6e59e003fb7c4ceed565a6b5f6da47)

**Comment by cpuguy83** [comment]
I would much rather follow the git model and exec some other binary rather than handling these aliases within cli.

**Comment by mathieu-pousse** [comment]
Hum... Not sure to have it. I think we did exactly as git (https://git-scm.com/book/tr/v2/Git-Basics-Git-Aliases) 

Create basic alias that contains a docker command or a complex alias, starting with `!` that executes the command from another shell (https://github.com/git/git/blob/33f2c4ff7b9ac02cd9010d504e847b912b35baf6/run-command.c#L154)

BTW, we fixed the go lint issues, could you please retrigger a build ? thx

**Comment by cpuguy83** [comment]
I'm thinking more along the lines of: https://www.kernel.org/pub/software/scm/git/docs/howto/new-command.html

**Comment by mathieu-pousse** [comment]
Ok I see but it looks overkill to me. The idea was just to create aliases,
not to create sub commands. And with the binaries, you loose the bash
auto-completion.

With the built-in system you inherit the existing features in your shell.

I don't think users will create a man page for an alias, nor write test
cases for aliases.

**Comment by vdemeester** [comment]
@mathieu-pousse I think what @cpuguy83 mean is that it probably would preferable to add to docker support for an *exec model* as git does. This would make any `docker-sthg` command to be used as `docker sthg` (`docker machine ls`, `docker compose up -d`, etc..).

And thus, a `docker-alias` command could even be an external project to docker itself (project that could be written in any language, have bash/zsh auto-completion, man, etc.. :wink:).

**Comment by calavera** [comment]
I'm very :-1: on adding this to the cli, we should not reimplement bash features.

I'm going to close this PR, it looks like other maintainers don't like it either. Please, feel free to reopen it if there are compelling reasons to incorporate this into docker.

**Pull request closed without merging**
