### PR TITLE
Clear Containers for Docker Engine (v1.9.0)

### PR DESCRIPTION
**Pull request by jamesodhunt**
This PR supersedes #17244 (and #16163).

### CODE REVIEW

**Comment by xnox** [comment]
Something is odd, in terms of the amount of merge commits outstanding. Possibly the target branch has moved, in a criss-cross way since clr-1.9.0-submit merge was done. Possibly the results of the merge need to be stashed away, and remerged to get a cleaner diff/history graph.

**Comment by ppadala** [comment]
Great to see this getting merged. Is there some documentation on how to enable and use clr backend for runc?

**Comment by calavera** [comment]
This is not going to be merged, as we've pointed out in several occasions already, can you please stop? Even if Docker is not using Runc yet, adding more execution drivers only takes us further away from using it. A better alternative to have this support is to make Runc work with ClearContainers and help with the migration to Runc.

Opening these PRs only generates confusion for users, like @ppadala

**Comment by jamesodhunt** [comment]
@calavera - This PR was raised after discussion with @runcom on the Clear Linux mailing list [1].

We are aware that docker plans to move to OCI, but have not seen a schedule for this move. Are you or anyone else able to answer the following?

 1. When docker will support OCI (approximate timeline / docker version)?
 2. Do any test/beta docker OCI branches exist that we can test our OCI runtime with?

We already have a draft OCI runtime for Clear Linux [2]. However, until docker migrates to OCI, we would very much like to have it support Clear Linux, hence these PRs.

Kind regards,

James.
---
[1] - https://lists.clearlinux.org/pipermail/dev/2015-October/thread.html#56 
[2] - https://github.com/clearlinux/kvmtool/tree/oci

**Comment by runcom** [comment]
I'm not really aware of the plan to fully move to OCI but of course the previous PR was still outdated so I suggested to move everything to master. Though I'm well aware of the current Roadmap (and the state of not adding more execdriver), I think moving toward OCI is the right thing to do here and with other new execdriver

**Comment by calavera** [comment]
@jamesodhunt you can modify docker to support OCI in the same way you modified docker to support this driver. You could also start a conversation on the OCI list to gather requirements to migrate docker to OCI, if there is any.

> we would very much like to have it support Clear Linux, hence these PRs.

We would like very much to migrate to OCI, adding a new driver takes us further away, as I said before. Help us migrate to OCI rather than keeping us away from it.

**Comment by WeiZhang555** [comment]
Hi everyone, I'm a developer who is also very interested in `Clear Container`, and we are still investigating possibility to support other runtimes in docker. 

I see that you are deciding to NOT add more execdrivers to docker, what I'm suggesting is that docker provide a plugin mechanism(we already have a nice plugin design) to call out to other OCI-compatible runtimes such as `Clear Container`, since @jamesodhunt says they already have a draft OCI runtime for Clear Linux, with this standard plugin interface, Docker will never need to embed more exec drivers directly, they can simply call out to other runtimes remotely. And also other runtimes don't need to modify docker source code, what they only need to do is following OCI standard and expose standard interfaces needed.

The proposal is listed here #17477, I think this is good for Docker and Clear Linux, WDYT of this? 
ping @jamesodhunt @xnox @calavera @runcom

**Comment by xnox** [comment]
@calavera we also have lkvm which is OCI compatible, that is takes same configs as runc does to execute workloads. But there is deadlock now - there is no docker that uses OCI, and there is no OCI tooling that works with docker hub. We have done two implementations now, and it seems that neither can be merged and tested now. So which one is it? Should we write an execdriver that calls out to an OCI compatible binary, or would that be also rejected from being merged?

**Comment by calavera** [comment]
> Should we write an execdriver that calls out to an OCI compatible binary, or would that be also rejected from being merged?

As far as I know, that has always been the goal, I don't see why it should be rejected.

/cc @crosbymichael

**Comment by xnox** [comment]
@calavera right, but the Highland team have requested a stable execution driver from us the other day. Which we are providing here. Our understanding was, that due to Highland team requests this execution driver (rather than an OCI executor) is required by Docker. Is there some communication that developers on our end have missed?

**Comment by thaJeztah** [comment]
I've had a quick chat with @calavera, and we'll close this PR for now. I've understood that he talked with you during DockerCon about possible ways to get support for clear containers in the future.

Thanks!

**Pull request closed without merging**
