### PR TITLE
Don't disable restart policy with non-fatal signal

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by cpuguy83** [comment]
Note, this isn't fully functional right now due to #16887, but check it out!

**Comment by icecrime** [comment]
I don't think I agree with this one, as I believe the default action for `SIGUSR1` is indeed to terminate the process.

See `signal(7)`:

```
       Signal     Value     Action   Comment
       ──────────────────────────────────────────────────────────────────────
       SIGUSR1   30,10,16    Term    User-defined signal 1
       SIGUSR2   31,12,17    Term    User-defined signal 2
```

**Comment by icecrime** [comment]
I don't think we can make this for 1.9.0 in time, removing milestone.

**Comment by LK4D4** [comment]
@cpuguy83 Where we here? I sorta agree that `SIGUSR1` default action is reload and not kill process.

**Comment by cpuguy83** [comment]
Well, it's currently in design review.
And yes, +1 on SIGUSR1+2 being user defined signals, not typically used for program termination.

**Comment by vdemeester** [comment]
Desgin LGTM for me :wink:

**Comment by icecrime** [comment]
I won't go against, but I insist that SIGUSR1 _are_ fatal signals by default...

```
$ top &
[1] 3600
$ kill -SIGUSR1 3600
[1]+  Stopped                 top
```

**Comment by cpuguy83** [comment]
I concede that termination is the default action for SIGUSR1/2.
However, the GNU docs say this:
```
The SIGUSR1 and SIGUSR2 signals are set aside for you to use any way you want. They're useful for simple interprocess communication, if you write a signal handler for them in the program that receives the signal.
```

I'm good with whatever, however I know many apps uses SIGUSR1 to prompt reloading of some configuration.
Maybe at least we can say, if a stop signal is defined, then SIGUSR1 and SIGUSR2 are considered non-fatal?

**Comment by crosbymichael** [comment]
Lets not do this.  There is only one fatal signal and that is SIGKILL.  Anything else can be handled by the application and ignored so its not fair to pick ones that we think will be fatal but will not do anything.

I think we need to find a better way to handle this.  Maybe not do this if `docker stop` is called but if `docker kill -s` is called then ignore it but I think this PR will cause more weird issues.

**Pull request closed without merging**
