### PR TITLE
Vendor Libnetwork v0.7.0-rc.1

### PR DESCRIPTION
**Pull request by mavenugo**
- Fixes https://github.com/docker/libnetwork/issues/1051
- Fixes https://github.com/docker/libnetwork/issues/985
- Fixes https://github.com/docker/libnetwork/issues/945
- Log time taken to set sandbox key (to assist with debugging #21453)
- Limit number of concurrent DNS queries

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think this is for 1.11?

**Comment by tiborvass** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
Weird failures on WindowsTP4 https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/3946/console

```
05:28:39 --- FAIL: TestGetContextFromLocalDirWithNoDirectory (0.00s)
05:28:39 	context_test.go:173: Error when getting context from local dir: unable to get absolute context directory: The filename, directory name, or volume label syntax is incorrect.
05:28:39 --- FAIL: TestGetContextFromLocalDirWithDockerfile (0.00s)
05:28:39 	context_test.go:208: Absolute directory path should be equal to C:\Windows\TEMP\builder-context-test716901139, got: C:\Windows\Temp\builder-context-test716901139
05:28:39 --- FAIL: TestGetContextFromLocalDirWithCustomDockerfile (0.00s)
05:28:39 	context_test.go:292: Absolute directory path should be equal to C:\Windows\TEMP\builder-context-test695992509, got: C:\Windows\Temp\builder-context-test695992509
05:28:39 --- FAIL: TestValidateContextDirectoryEmptyContext (0.00s)
05:28:39 	context_test.go:60: Error should be nil, got: The filename, directory name, or volume label syntax is incorrect.
05:28:39 FAIL
```
```
06:01:54 ----------------------------------------------------------------------
06:01:54 FAIL: docker_cli_ps_test.go:341: DockerSuite.TestPsListContainersFilterAncestorImage
06:01:54 
06:01:54 docker_cli_ps_test.go:377:
06:01:54     // start fourth container
06:01:54     dockerCmd(c, "run", "--name=fourth", imageName1Tagged, "echo", "hello")
06:01:54 C:/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
06:01:54     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
06:01:54 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc08227b8c0), Stderr:[]uint8(nil)} ("exit status 125")
06:01:54 ... "run --name=fourth images_ps_filter_test1:tag echo hello" failed with errors: D:\CI\CI-eea63c5\binary\docker.exe: Error response from daemon: HCSShim::CreateProcessInComputeSystem failed in Win32: The specified path is invalid. (0xa1) id=333bcd4e718bf1659262a38d7f500512b6d9d0a290c3607c50ac69f147ddb70b params={ C:/busybox/busybox.exe echo hello  map[] false [0 0]}.
06:01:54 , exit status 125
06:01:54 
06:01:55 
06:01:55 ----------------------------------------------------------------------
```

**Comment by runcom** [comment]
LGTM

**Pull request merged**
