### PR TITLE
docs: speed up build by reducing build steps

### PR DESCRIPTION
**Pull request by Mic92**
should be also easier to maintain

### CODE REVIEW

**Comment by xiaods** [comment]
missing a sign off, please 
```
git commit -s
```

**Comment by Mic92** [comment]
@xiaods it is signed

**Comment by icecrime** [comment]
Ping @moxiegirl!

**Comment by moxiegirl** [comment]
Clever! I'm new to working with Dockerfiles and have been learning by osmosis -- so thanks for the education. And the contribution! 

LGTM

ping @docker/docs-owners

**Comment by fredlf** [comment]
LGTM, but I have to assume someone has tested it since I can't do that myself atm.

**Comment by moxiegirl** [comment]
@fredlf Yes, I tested it.  Thanks for the quick response.

**Pull request merged**
