### PR TITLE
1.13.0 rc2 cherrypicks

### PR DESCRIPTION
**Pull request by vieux**
- [#28341](https://github.com/docker/docker/pull/28341)
  - d67aa065ef9f295949ed507fc3d67f29fd56fcdb Show experimental flags and subcommands if enabled
- [#28397](https://github.com/docker/docker/pull/28397)
  - d2bb29f87e326034e4329e31f3208d8f610ccef7 Add docs for plugin push
- [#28306](https://github.com/docker/docker/pull/28306)
  - 8dfdecbd2bf1c13e664a03b0c7c61ff391fb4fe1 only check secrets for service create if requested
- [#28317](https://github.com/docker/docker/pull/28317)
  - e23e36f25cc55fd273fa04f2dd9d3772683ee381 Skip plugin tests if not in amd64
- [#28310](https://github.com/docker/docker/pull/28310)
  - 17df5593ebcd471b0bbf0ea9d6e060ee3447850a 69f0402585579ced62bca22551a6ef45672bb4fd Docker info binaries version update
- [#28350](https://github.com/docker/docker/pull/28350)
  - 1addb4817bca8daeb3a3bca207705ad72f5c7a16 judge manager before getting secret
- [#28203](https://github.com/docker/docker/pull/28203)
  - 63904eb6745d553573ffe8b7cef43dfc0b8a07cf docker logs --tails returns less lines than expected
- [#28309](https://github.com/docker/docker/pull/28309)
  - e60e54c12aa65c3c11c27bda3002b361f2c1e90f dockerversion: add other binaries to _lib.go
- [#28323](https://github.com/docker/docker/pull/28323)
  - beccd3663f3e377249fa5c07f62cbdbe5f3be14a dockerversion: Extra v1.25 in API docs
- [#28280](https://github.com/docker/docker/pull/28280)
  - 5527202e41dfa48b8635dd6f274acb7f19ee3302 Remove duplicated document
- [#28359](https://github.com/docker/docker/pull/28359)
  - 7bbbc8c7f16869dbb43e4e218ac280d5d1c0944a fix typo in node update docs
- [#28410](https://github.com/docker/docker/pull/28410)
  - 5ea75bb6bf41aeaeaa15d8bcceea5be87c211ffc Move `StreamConfig` out of `runconfig`
- [#28342](https://github.com/docker/docker/pull/28342)
  - c6357f04b5f30ac4d0e6712a05375013a8f7327e Add bash completion for `docker build --cache-from`
- [#28344](https://github.com/docker/docker/pull/28344)
  - 279bd827fe3393b1790ef26e36a3a7f4260c0441 Add bash completion for managing ports in services
- [#28355](https://github.com/docker/docker/pull/28355)
  - ac50074258c0fef31ddc5c062ac5c07379b7cf78 Add zsh completion for 'docker image build --cache-from'
- [#28356](https://github.com/docker/docker/pull/28356)
  - 7b6a38e1b1e146e4350db0e38d3d7a9313232ece Fix bash completion for `docker ps --filter is-task`
- [#28357](https://github.com/docker/docker/pull/28357)
  - 36916ae2ad3709ec254d6c013fb5712820a898a7 Add zsh completion for 'docker service {create --port, update --port-{add, rm}}
- [#28360](https://github.com/docker/docker/pull/28360)
  - 188d2fac57d63888f08531adc46aa3349e3b4f3a Add bash completion for `docker service ps --all`
- [#28362](https://github.com/docker/docker/pull/28362)
  - 28dc8c863a810a5fce078319fb422caced67b725 Add bash completion for DNS settings in services
- [#28369](https://github.com/docker/docker/pull/28369)
  - fb8404a3488bccfb4b318d279332946f370d1452 Update bash completion `dns-options-add/rm` -> `dns-option-add/rm`
- [#28370](https://github.com/docker/docker/pull/28370)
  - 45e5b2552ab1ca685e88e0feeedc92fb817d8567 Fix a small typo in `docs/deprecated.md`
- [#28378](https://github.com/docker/docker/pull/28378)
  - 54ebf4f74a5e8f6598849da4a9052743ada8e83f Add zsh completion for 'docker service' DNS settings
- [#28381](https://github.com/docker/docker/pull/28381)
  - b184bdabf7a01c4b802304ac64ac133743c484be Add zsh completion for the new 'docker secret' command
- [#28386](https://github.com/docker/docker/pull/28386)
  - 0bc07d29577bf163eb88c4047e52382218dd4026 Add zsh completion for 'docker service {create,update} --secret'
- [#27985](https://github.com/docker/docker/pull/27985)
  - a8180eeaedfb5161a0e8db8ddd464ac3f1eb5cfb 2d3df91436a096e17214fc56aee4968c3fe598de  clear message for host volumes not starting with /
- [#28340](https://github.com/docker/docker/pull/28340)
  - b4ab4530841417305bcaa0b0d25d172bfbf3956a Fix issue with missing fields for `ps` template
- [#28292](https://github.com/docker/docker/pull/28292)
  - f469021f88ef4765f9871c36b61e4f0138528a7b fix the wrong title with docker swarm
- [#28380](https://github.com/docker/docker/pull/28380)
  - 11bfa638fe5b5fecf16341d4d7154c233862d946 Add zsh completion for 'docker image build --network'
- [#28418](https://github.com/docker/docker/pull/28418)
  - 766cc9b46753106c6880ccdea0a4dcb2bc734c2a Perform graceful shutdown during plugin disable
- [#28417](https://github.com/docker/docker/pull/28417)
  - e2adb5560b6ef666beb69de53028925098a952c9 Gitignore dockerversion\version_autogen_unix.go
- [#28384](https://github.com/docker/docker/pull/28384)
  - 45bccaeacbc80f28861bd7fe9cb73007b493b11f Updated daemon documentation to clarify that live-restore is not supported on Windows
- [#28419](https://github.com/docker/docker/pull/28419)
  - 985cc9fb053e82967a4469cd5f278271b914480c Remove inexistent link and add related links
- [#28424](https://github.com/docker/docker/pull/28424)
  - 8eeaa2556399f90ad637f74401a6f11c01b7544c man page: consistent indents for flag descriptions
- [#28435](https://github.com/docker/docker/pull/28435)
  - ba408fbc9a3131d03bb5389e73cb9eec49e071be man/docker: wrap lines consistently
- [#28453](https://github.com/docker/docker/pull/28453)
  - d341bb1b6eac3f40eb4cd5798784635e0183809b Revert reference docs for ambient capabilities

### CODE REVIEW

**Comment by justincormack** [comment]
@vieux https://github.com/docker/docker/pull/28410 is merged now

**Comment by vieux** [comment]
@docker/core-maintainers let's merge those, no need to wait, I'm going to do another PR for the rest.

**Comment by cpuguy83** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
