### PR TITLE
Bump containerd to v0.2.1

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by mlaventure** [comment]
missing the update to `hack/vendor.sh`

**Comment by crosbymichael** [comment]
@mlaventure fixed

**Comment by mlaventure** [comment]
LGTM, IANAM.

**Comment by tonistiigi** [comment]
https://github.com/docker/containerd/compare/07c95162cdcead88dfe4ca0ffb3cea02375ec54d...v0.2.1

https://github.com/docker/containerd/compare/d2f03861c91edaafdcb3961461bf82ae83785ed7...v0.2.1 is the more important part of the changeset because we forgot to update master to the same sha that is used in 1.11.

**Comment by tonistiigi** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by mlaventure** [comment]
Fixes #22167

**Pull request merged**
