### PR TITLE
Do not show tasks from down nodes as active in ls

### LINKED ISSUE #23806: Docker service scale bug when remove swarm node
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 28
 Running: 7
 Paused: 0
 Stopped: 21
Images: 140
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 446
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 9b4wspjwk5m6nhwnmn2n4wsrv
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:ea57da3379505e56c244c135de662752e64eacd61651e3b24ece8b318fe8e7e0
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-boot2docker
Operating System: Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.097 GiB
Name: default
ID: 2JXI:2JZN:E6HT:TBX2:IJBZ:3AQF:LFQH:PYR7:PZ7A:OK5N:LBO6:SKPD
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 86
 Goroutines: 185
 System Time: 2016-06-21T09:24:52.418449567Z
 EventsListeners: 0
Username: jorge07
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Host OSX 10.11.4
Virtual Box

**Steps to reproduce the issue:**
1.Having a `default` boot2docker machine as swarm master (*docker swarm init*)
2.docker-machine create --driver virtualbox minion1
3.docker-machine create --driver virtualbox minion2
3.eval $(docker-machine env minion1)
4.docker swarm join 192.168.99.100:2377
5.eval $(docker-machine env minion2)
6.docker swarm join 192.168.99.100:2377
7.eval $(docker-machine env default)
8.docker service create --name=nginx --replicas=3 nginx:1.9
9.docker service scale nginx=8
10.docker-machine stop minion2
11.docker service tasks nginx

Result:

result

**Describe the results you received:**
ESP0047:~ jorge.arco$ docker service ls
ID            NAME   REPLICAS  IMAGE      COMMAND
4kj9dx2nvl4i  nginx  11/8      nginx:1.9
screenshot

**Describe the results you expected:**
ESP0047:~ jorge.arco$ docker service ls
ID            NAME   REPLICAS  IMAGE      COMMAND
4kj9dx2nvl4i  nginx  8/8      nginx:1.9

**Additional information you deem important (e.g. issue happens only occasionally):**
I also run `docker service scale nginx=3`
Result image

The containers are well relocated, but the counter is displaying the wrong number of replicas.

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #23806

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

ping @stevvooe

**Comment by abronan** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by stevvooe** [comment]
LGTM

**Comment by dnephin** [comment]
Do we really want to iterate over every node on the client?

Shouldn't this filtering be done on the engine side?

**Comment by thaJeztah** [comment]
ping @tonistiigi @stevvooe ^^

**Comment by tonistiigi** [comment]
@dnephin Status doesn't seem to be a valid filter atm. https://github.com/docker/docker/blob/master/daemon/cluster/filters.go#L13 https://github.com/docker/swarmkit/blob/master/api/control.proto#L85

**Comment by dnephin** [comment]
Should we add it?

**Comment by aaronlehmann** [comment]
Doesn't seem like a priority to me. This is the kind of optimization we can always do later.

**Pull request merged**
