### PR TITLE
Migrate stats and events command to cobra

### PR DESCRIPTION
**Pull request by WeiZhang555**
part of #23211

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by vdemeester** [comment]
@WeiZhang555 I wondet about the move of `events` in the `container` package as events are not only for containers so the command is not only for containers 😇

**Comment by WeiZhang555** [comment]
@vdemeester Oh no, you're definitely right. 

How about moving `events` to a new package named "system", this will make it consistent with `api/server/router/system` where `events` API inhabits in.

`stats` can still keep in  package `container`. WDYT?

**Comment by vdemeester** [comment]
@WeiZhang555 yeah make sense I think :wink: 
`stats` is a container thing so yeah, `container` package is about right :angel:

**Comment by WeiZhang555** [comment]
@vdemeester Updated. PTAL.

**Comment by thaJeztah** [comment]
@WeiZhang555 CI failures look related;

```
5:15:59 ---> Making bundle: validate-vet (in bundles/1.12.0-dev/validate-vet)
15:15:59 api/client/system/events_utils.go:29: Handle passes lock by value: system.eventHandler contains sync.Mutex
15:15:59 api/client/system/events_utils.go:38: Watch passes lock by value: system.eventHandler contains sync.Mutex
15:15:59 exit status 1
15:16:00 Unable to find image 'busybox:latest' locally
```

**Comment by WeiZhang555** [comment]
@thaJeztah It passed now :-)

**Comment by WeiZhang555** [comment]
ping @vdemeester @thaJeztah @cpuguy83 @runcom

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐮

**Pull request merged**
