### PR TITLE
Add zsh completion for gelf-compression log driver options

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref #19831

@albers Thx for the ping

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM thanks @sdurrheimer :+1:

**Comment by thaJeztah** [comment]
Oh! I think one of your other PRs conflicted with this one, needs a rebase @sdurrheimer :cry:

**Comment by vdemeester** [comment]
LGTM 🐵

**Comment by sdurrheimer** [comment]
@thaJeztah Rebased

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
