### PR TITLE
Use `cli` for trusted related command

### PR DESCRIPTION
**Pull request by vdemeester**
This also removed some skipped test (that are skipped for a long while).

🦁

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

**Review by boaz0 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
other than that LGTM, just wondering about those tests that were removed

**Comment by cyli** [comment]
@thaJeztah Looks like they've been skipped for a while.  We do have explicit tests for expired metadata and expired root certificates in notary itself, and those tests would be slightly harder to replicate in Docker.  cc @endophage @riyazdf for visibility

**Comment by thaJeztah** [comment]
ok let me go ahead and merge then; thanks for looking @cyli

**Pull request merged**
