### PR TITLE
use `proto` and `addr` replace `protoAddrParts[0]` and `protoAddrPart…

### PR DESCRIPTION
**Pull request by gorilla001**
**\- updated variables name**

**\- use `proto` and `addr` replace `protoAddrParts[0]` and `protoAddrParts[1]`**

### CODE REVIEW

**Comment by vdemeester** [comment]
I'm not sure I like this change too much as it doesn't make it more readable (even less)

**Comment by thaJeztah** [comment]
hm, it seems consistent with the code above this (which also uses `addr` and `proto`, so a "mild" +1  from me, so I think the next reviewer should make the decision :smile:

**Comment by vdemeester** [comment]
oh wait what ? :sweat: I don't know why but I did read the invert change, so in fact I'm +1 for this change (I think I was tired when first reviewing this one).

**Comment by thaJeztah** [comment]
LGTM then :smile:

**Comment by vdemeester** [comment]
@pwzgorilla you need to sign your commit though

```
15:39:52 ---> Making bundle: validate-dco (in bundles/1.13.0-dev/validate-dco)
15:39:53 These commits do not have a proper 'Signed-off-by:' marker:
15:39:53  - 2d3f4475d44643c7cebc8128a7b3a8dafa190440
```

As @GordonTheTurtle would say :

Please sign your commits following these rules:
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-5" git@github.com:friism/docker-1.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Ammending updates the existing PR. You **DO NOT** need to open a new one.

**Comment by pwzgorilla** [comment]
what happened to jenkins check?

**Comment by thaJeztah** [comment]
Don't think CI failures are related. This one is scary though; not sure what happened there;

https://jenkins.dockerproject.org/job/Docker-PRs/30811/console

```
02:20:37 ----------------------------------------------------------------------
02:20:37 FAIL: docker_cli_build_test.go:5864: DockerSuite.TestBuildBuildTimeArgOverrideEnvDefinedBeforeArg
02:20:37 
02:20:37 docker_cli_build_test.go:5888:
02:20:37     if out, _ := dockerCmd(c, "run", "--name", containerName, imgName); !strings.Contains(out, envValOveride) {
02:20:37         ...
02:20:37     }
02:20:37 /go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
02:20:37     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
02:20:37 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc82049d340), Stderr:[]uint8(nil)} ("exit status 2")
02:20:37 ... "run --name bldargCont bldargtest" failed with errors: barOverride
02:20:37 panic: close of closed channel
02:20:37 
02:20:37 goroutine 1 [running]:
02:20:37 panic(0xaff640, 0xc8203653f0)
02:20:37 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
02:20:37 github.com/docker/engine-api/client/transport/cancellable.(*notifyingReader).Close(0xc820366e20, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:109 +0x7a
02:20:37 github.com/docker/docker/api/client/container.waitExitOrRemoved(0xc82007c510, 0x7f7e915b87c8, 0xc82032a380, 0xc820386180, 0x40, 0x0, 0xecf3b34f4, 0x202ffd6a, 0x139ab20, 0x0, ...)
02:20:37 	/go/src/github.com/docker/docker/api/client/container/utils.go:91 +0xc8f
02:20:37 github.com/docker/docker/api/client/container.runRun(0xc82007c510, 0xc82007d4d0, 0xc8202f97d0, 0xc820314500, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/api/client/container/run.go:266 +0x168b
02:20:37 github.com/docker/docker/api/client/container.NewRunCommand.func1(0xc82031b680, 0xc820332f00, 0x1, 0x3, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/api/client/container/run.go:49 +0x141
02:20:37 github.com/spf13/cobra.(*Command).execute(0xc82031b680, 0xc820332e70, 0x3, 0x3, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:593 +0x6fe
02:20:37 github.com/spf13/cobra.(*Command).ExecuteC(0xc82007fb00, 0xc82031b680, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:683 +0x55c
02:20:37 github.com/spf13/cobra.(*Command).Execute(0xc82007fb00, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:642 +0x2d
02:20:37 github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.run(0xc82007fb00, 0xc82007c510, 0x7ffd28d64aff, 0x3, 0xc82000a0c0, 0x3, 0x3, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:122 +0x25f
02:20:37 github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.Command.func1(0xc82000a0c0, 0x3, 0x3, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:130 +0x8c
02:20:37 github.com/docker/docker/cli.(*Cli).Run(0xc8203325a0, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/cli/cli.go:81 +0x34b
02:20:37 main.main()
02:20:37 	/go/src/github.com/docker/docker/cmd/docker/docker.go:72 +0x599
02:20:37 
02:20:37 goroutine 17 [syscall, locked to thread]:
02:20:37 runtime.goexit()
02:20:37 	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
02:20:37 
02:20:37 goroutine 5 [syscall]:
02:20:37 os/signal.signal_recv(0x0)
02:20:37 	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
02:20:37 os/signal.loop()
02:20:37 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
02:20:37 created by os/signal.init.1
02:20:37 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
02:20:37 
02:20:37 goroutine 24 [runnable]:
02:20:37 github.com/docker/docker/api/client/system.(*eventHandler).Watch(0xc820384420, 0xc82038c840)
02:20:37 	/go/src/github.com/docker/docker/api/client/system/events_utils.go:39 +0x7f
02:20:37 created by github.com/docker/docker/api/client/container.waitExitOrRemoved
02:20:37 	/go/src/github.com/docker/docker/api/client/container/utils.go:56 +0x417
02:20:37 
02:20:37 goroutine 10 [runnable]:
02:20:37 github.com/docker/docker/api/client.(*DockerCli).ForwardAllSignals.func1(0xc82038c060, 0xc82007c510, 0x7f7e915b87c8, 0xc82032a380, 0xc820386180, 0x40)
02:20:37 	/go/src/github.com/docker/docker/api/client/utils.go:144 +0x83
02:20:37 created by github.com/docker/docker/api/client.(*DockerCli).ForwardAllSignals
02:20:37 	/go/src/github.com/docker/docker/api/client/utils.go:164 +0x97
02:20:37 
02:20:37 goroutine 8 [runnable]:
02:20:37 net/http.(*persistConn).readLoop(0xc820368680)
02:20:37 	/usr/local/go/src/net/http/transport.go:1185 +0xd52
02:20:37 created by net/http.(*Transport).dialConn
02:20:37 	/usr/local/go/src/net/http/transport.go:860 +0x10a6
02:20:37 
02:20:37 goroutine 9 [select]:
02:20:37 net/http.(*persistConn).writeLoop(0xc820368680)
02:20:37 	/usr/local/go/src/net/http/transport.go:1280 +0x472
02:20:37 created by net/http.(*Transport).dialConn
02:20:37 	/usr/local/go/src/net/http/transport.go:861 +0x10cb
02:20:37 
02:20:37 goroutine 19 [select, locked to thread]:
02:20:37 runtime.gopark(0xec1d50, 0xc82001ef28, 0xd49050, 0x6, 0x18, 0x2)
02:20:37 	/usr/local/go/src/runtime/proc.go:262 +0x163
02:20:37 runtime.selectgoImpl(0xc82001ef28, 0x0, 0x18)
02:20:37 	/usr/local/go/src/runtime/select.go:392 +0xa67
02:20:37 runtime.selectgo(0xc82001ef28)
02:20:37 	/usr/local/go/src/runtime/select.go:215 +0x12
02:20:37 runtime.ensureSigM.func1()
02:20:37 	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
02:20:37 runtime.goexit()
02:20:37 	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
02:20:37 
02:20:37 goroutine 13 [runnable]:
02:20:37 encoding/json.(*Decoder).Decode(0xc820307ba0, 0xac2280, 0xc82041a480, 0x0, 0x0)
02:20:37 	/usr/local/go/src/encoding/json/stream.go:43
02:20:37 github.com/docker/docker/api/client/system.DecodeEvents(0x7f7e8fd68090, 0xc820366e20, 0xc820365040, 0x0, 0x0)
02:20:37 	/go/src/github.com/docker/docker/api/client/system/events_utils.go:56 +0x102
02:20:37 created by github.com/docker/docker/api/client/container.waitExitOrRemoved
02:20:37 	/go/src/github.com/docker/docker/api/client/container/utils.go:79 +0xaea
02:20:37 
02:20:37 goroutine 12 [runnable]:
02:20:37 github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f7e915b87c8, 0xc82032a380, 0xc8203845b0, 0xc820331440)
02:20:37 	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:78 +0xef
02:20:37 created by github.com/docker/engine-api/client/transport/cancellable.Do
02:20:37 	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x336
02:20:37 , exit status 2
02:20:37 
02:20:41 
```

**Comment by pwzgorilla** [comment]
need re-check

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL (everything is signed, squashed, rebased 👍)

**Comment by vdemeester** [comment]
LGTM :tiger:

**Pull request merged**
