### PR TITLE
Move Michael Crosby to alumni

### PR DESCRIPTION
**Pull request by thaJeztah**
Michael informed me that he wants to step down as a maintainer for the project, so I tried to write up something nice 😅

Thank you Michael!!

@AkihiroSuda @Anusha @coolljt0725 @cpuguy83 @crosbymichael @estesp @johnstep @justincormack @kolyshkin @MHBauer @runcom @stevvooe @tianon @tibor @tonistiigi @unclejack @vdemeester @vieux @yongtang ptal

**- A picture of a cute animal (not mandatory but encouraged)**

thankyou

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 😻 😭

**Comment by coolljt0725** [comment]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Review by estesp — APPROVED** [review]
LGTM! Thanks @crosbymichael for all your work but more personally for helping me grow in my own open source & development skills in the early days of this project!

**Review by tianon — APPROVED** [review]
A neverending stream of love for Mr. Crosby ❤️

LGTM

**Review by AkihiroSuda — APPROVED** [review]
Thank you Michael!

**Comment by thaJeztah** [comment]
Bringing this one in; chatted with Michael and he said; thanks!

**Comment by tiborvass** [comment]
Thank you, Michael!

**Pull request merged**
