### PR TITLE
add Images testcase

### PR DESCRIPTION
**Pull request by chchliang**
Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>

Add  testcases with ` Image` , covering all methods.

### CODE REVIEW

**Comment by chchliang** [comment]
03:28:46 image/image_test.go:1::warning: file is not goimported (goimports)
03:28:46 Unable to find image 'busybox:latest' locally
03:28:47 latest: Pulling from library/busybox
03:28:48 03b1be98f3f9: Pulling fs layer
03:28:48 03b1be98f3f9: Download complete
03:28:48 03b1be98f3f9: Pull complete
03:28:48 Digest: sha256:99ccecf3da28a93c063d5dddcdf69aeed44826d0db219aabc3d5178d47649dfa
03:28:48 Status: Downloaded newer image for busybox:latest
03:28:49 Build step 'Execute shell' marked build as failure
03:28:49 Set build name.
03:28:49 New build name is '#34876'
03:28:49 Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '#34876', new value: '#34876'
03:28:49 [PostBuildScript] - Execution post build scripts.
03:28:49 [Docker-PRs] $ /bin/sh -xe /tmp/hudson859299392853152556.sh
03:28:49 + docker stop docker-pr45531
**03:28:49 Error response from daemon: No such container: docker-pr45531**
03:28:49 + true
03:28:49 + id -u
03:28:49 + id -g
03:28:49 + docker run --rm -v /home/ubuntu/workspace/Docker-PRs:/workspace busybox chown -R 1000:1000 /workspace
03:28:49 [Docker-PRs] $ /bin/sh -xe /tmp/hudson739707961498073262.sh
03:28:49 + xargs tar -czf bundles.tar.gz+ find bundles -name *.log -o -name *.prof -o -name integration.test
03:28:49 
03:28:49 tar: Cowardly refusing to create an empty archive
03:28:49 Try 'tar --help' or 'tar --usage' for more information.
03:28:49 + true
03:28:49 [Docker-PRs] $ /bin/sh -xe /tmp/hudson3115015410293497088.sh
03:28:49 + set +x
03:28:49 
03:28:49 
03:28:49 ---
03:28:49 Now starting POST-BUILD steps
03:28:49 ---
03:28:49 
03:28:50 Error response from daemon: No such container: docker-pr45531
03:28:50 Archiving artifacts
03:28:50 Notifying endpoint with url 'https://leeroy.dockerproject.org/notification/jenkins'
03:28:51 [WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
03:28:51 Finished: FAILURE

**Comment by thaJeztah** [comment]
Did you close this on purpose?

**Comment by chchliang** [comment]
@thaJeztah 
I was accidentally closed, but I have submitted another one  #34878.

**Comment by thaJeztah** [comment]
Great, thanks!

**Pull request closed without merging**
