### PR TITLE
Make errdefs helpers idempotent

### PR DESCRIPTION
**Pull request by thaJeztah**
Don't convert errors if they already have the right type

~Builds on top of https://github.com/moby/moby/pull/38455, so I can rebase once that one is merged~

rebased

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @vdemeester

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
rebased, to get rid of the extra commit

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by olljanat** [comment]
CI OK except codecov/patch failure. This one is ready for merge.

**Comment by thaJeztah** [comment]
yup; let's merge, thanks!

**Pull request merged**
