### PR TITLE
Add examples for stack ps

### PR DESCRIPTION
**Pull request by bhavin192**
**- What I did**
Added example outputs and commands for the filters. Added `node` filter as it is supported (I have tried it) 

This fixes https://github.com/docker/docker.github.io/issues/2955

### CODE REVIEW

**Comment by vieux** [comment]
@bhavin192 can you please open your branch against master ?

**Review by cten — APPROVED** [review]
Well done.

**Comment by bhavin192** [comment]
@vieux [docs/reference/commandline/stack_ps.md ](https://github.com/moby/moby/blob/master/docs/reference/commandline/stack_ps.md) already have better explanation and examples, I think this PR should be closed then.

**Comment by thaJeztah** [comment]
Yes, looks like these examples are already in the master branch, so I go ahead and close this PR, but thanks so much for contributing @bhavin192 :heart:

**Pull request closed without merging**
