### PR TITLE
Update authors and mailmap

### PR DESCRIPTION
**Pull request by thaJeztah**
Updated and sorted .mailmap and re-generated authors

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
@tianon PTAL 🤗

**Comment by AkihiroSuda** [comment]
(Curious, can we releax the current 2-LGTM rule for this kind of PRs?)

**Review by tianon — APPROVED** [review]
LGTM :+1:

**Comment by thaJeztah** [comment]
> Curious, can we releax the current 2-LGTM rule for this kind of PRs?

Ideally, still 2 LGTM's on PR's, but (my 0.02c) maintaining the project is about trust, so I'm comfortable with maintainers doing what they consider "right" and responsible.

**Pull request merged**
