### PR TITLE
typo fix retreived

### PR DESCRIPTION
**Pull request by liyongxin**
typo fix for volume/service/opts/opts.go

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! The change itself looks good, but looking at the commit message;

```
Signed-off-by: liyongxin <yxli@alauda.io>
```


@liyongxin could you use your [real / full name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work) in the sign-off?  😅

**Comment by liyongxin** [comment]
> typo fix for volume/service/opts/opts.go

@thaJeztah sorry, already recommited

**Review by yongtang — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
