### PR TITLE
Proposal: Container device add/remove CLI/API documentation

### PR DESCRIPTION
**Pull request by imain**
Device add/remove CLI and API documentation.  This is being proposed as
the new API and CLI to see how people like it.

Co-Authored-By: Chris Alfonso calfonso@redhat.com (github: calfonso)
Docker-DCO-1.1-Signed-off-by: Ian Main imain@redhat.com (github: imain)

### CODE REVIEW

**Comment by coolljt0725** [comment]
+1 for this

**Comment by tiborvass** [comment]
I'm +1 for the proposal, but I don't see us merging this anytime soon until we agreed on #8829.

I'm going to close this for now, which does NOT mean we don't want this feature. We can always reopen it later.

We know we've been slow on design discussions, and we are working on improving that bottleneck. Thanks for your contribution.

**Comment by jacknlliu** [comment]
+1 for this proposal

**Comment by kstromeiraos** [comment]
+1 for this

**Comment by leo-orellana** [comment]
+1 for this

**Pull request closed without merging**
