### PR TITLE
fix broken link to wiki

### PR DESCRIPTION
**Pull request by liubin**
Signed-off-by: bin liu liubin0329@gmail.com

The link is broken, changed it to wiki page like https://docs.docker.com/docker/introduction/understanding-docker/ .

### CODE REVIEW

**Comment by thaJeztah** [comment]
@moxiegirl I noticed the linked file is actually there, but marked "draft"; could that cause the link to be broken? https://github.com/docker/docker/blob/master/docs/terms/layer.md

**Comment by liubin** [comment]
HI @thaJeztah 

Very long ago, docs.docker.com has some pages that you mentioned.

But now I cant found the entry to view the old pages, so is not it to be discarded?

**Comment by thaJeztah** [comment]
@liubin possibly; I wasn't sure what the plans were for these pages, so hoping @moxiegirl could tell. If they're really deprecated, those files should be deleted, but wanted to check :smile:

**Comment by moxiegirl** [comment]
@liubin The correct link is: https://docs.docker.com/introduction/understanding-docker/

Your link had an extra `/docker/` in the path.  We had old pages hanging around in our site.  I apologize that you encountered one of those links.

**Comment by moxiegirl** [comment]
@thaJeztah  just read your comment. @liubin the terms are replaced in favor of the single glossary file. https://github.com/docker/docker/blob/master/docs/reference/glossary.md

I'll remove the terms as they aren't in use any more.

**Comment by liubin** [comment]
Hi , @moxiegirl I had updated the url to glossary page.

**Comment by moxiegirl** [comment]
Thanks @liubin LGTM  @thaJeztah I created an issue for the glossary and a contributor is working the issue. See #15530

**Comment by thaJeztah** [comment]
Thanks @liubin LGTM

@moxiegirl I saw the issue and PR, thanks!

**Pull request merged**
