### PR TITLE
Enhance 'network inspect' to show IpamInfo

### LINKED ISSUE #23025: PoolID missing in libnetwork api, /NetworkDriver.CreateNetwork call to remote driver
Please consider a scenario where two docker networks are created with subnets having same cidr.
The problem is we dont have any ways of associating an ip pool with a subnet. The calls to IPAM driver have no info on the network. the calls to the remote driver have no info on IP pools.

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
These changes will enable showing 'PoolID' provided by ipam driver in 'network inspect' output

Closes #23025
Signed-off-by: vikaschoudhary16 choudharyvikas16@gmail.com

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
Hi Folks, Would really appreciate any feedback on these changes.

Thanks.

**Comment by icecrime** [comment]
Thanks for the contribution. I think the change makes sense, but discussion should happen over the [`docker/engine-api` repository](https://github.com/docker/engine-api).

**Comment by icecrime** [comment]
Cc @mavenugo.

**Comment by vikaschoudhary16** [comment]
@icecrime ,
Thanks a lot for your response. 
I am new to docker contribution/development workflow. I can see some checks are failing and some are pending. Not sure if I should be worried about these or how to fix them. Any help or support will be much appreciated.

**Pull request closed without merging**
