### PR TITLE
enable installation on Cumulus Linux

### PR DESCRIPTION
**Pull request by gospo**
Signed-off-by: Andy Gospodarek gospo@cumulusnetworks.com

### CODE REVIEW

**Comment by gospo** [comment]
New pull request as we cleaned up output from lsb_release.

**Comment by gospo** [comment]
It seems unlikely that I need to be concerned with the experimental build failure, but what about the 'janky' build failure?  It seems more random than actually related to my change.

**Comment by jfrazelle** [comment]
this is going to need to be rebased on the new install script changes and i would look at https://github.com/docker/docker/pull/15001 for an example of how to do it

**Comment by fmoliveira** [comment]
Hi @gospo ,

Please check [PR 15001 at the testing instructions](https://github.com/docker/docker/pull/15001#issuecomment-125721830) and run the requested commands in your Cumulus Linux setup, then post your commands output to that PR.

This will help us determine whether Cumulus will benefit from that fix.

Thanks.

**Comment by thaJeztah** [comment]
ping @gospo would you be able to provide the output as @fmoliveira requested above? https://github.com/docker/docker/pull/14680#issuecomment-125782561, thanks so much in advance!

**Comment by gospo** [comment]
I'll check it out.  I was AFK last week, so I didn't have a chance until
now.

**Comment by jfrazelle** [comment]
closing in favor of #15001

**Comment by fmoliveira** [comment]
@gospo please ping me when you open a new issue to discuss this. :)

**Comment by fmoliveira** [comment]
@gospo please check [this proposal](https://github.com/docker/docker/issues/15765) .

**Pull request closed without merging**
