### PR TITLE
Carry 21716: When container had no layer data, cleanupContainer crashed

### PR DESCRIPTION
**Pull request by tiborvass**
Carry of #21716
Closes #21716

### CODE REVIEW

**Comment by thaJeztah** [comment]
This is only a rebase, and was already reviewed, so moving to "merge"

**Comment by thaJeztah** [comment]
Flaky test on WindowsTP5 ? https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP5/111/console

```
17:02:57 ----------------------------------------------------------------------
17:02:57 FAIL: docker_cli_ps_test.go:303: DockerSuite.TestPsListContainersFilterID
17:02:57 
17:02:57 docker_cli_ps_test.go:309:
17:02:57     // start another container
17:02:57     runSleepingContainer(c)
17:02:57 C:/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
17:02:57     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
17:02:57 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc08252c020)} ("exit status 127")
17:02:57 ... "run -d busybox sleep 240" failed with errors: 0cfcaef96d9f60450ba1bc264fac37094e858898907c381f6a6c05fe2866ab68
17:02:57 D:\CI\CI-0bfc9c8\binary\docker.exe: Error response from daemon: Container command 'C:/busybox/busybox.exe' not found or does not exist.
17:02:57 , exit status 127
17:02:57 
```

**Comment by jhowardmsft** [comment]
Known TP5 bug. Not a flaky test. We're investigating the cause of those class of errors.

**Comment by thaJeztah** [comment]
@jhowardmsft alright, let's ignore that one for now then

**Pull request merged**
