### PR TITLE
Skip deprecated storage-drivers in auto-selection

### PR DESCRIPTION
**Pull request by thaJeztah**
This PR is built on top of https://github.com/moby/moby/pull/38018; I can rebase once that's merged

Related PRs:

- https://github.com/moby/moby/pull/38017 Deprecate "devicemapper" storage driver, and add warning 
- https://github.com/moby/moby/pull/38018 Deprecate legacy overlay storage driver, and add warning 
- https://github.com/docker/cli/pull/1424 Deprecate "devicemapper" storage driver. 
- https://github.com/docker/cli/pull/1425 Deprecate legacy overlay storage driver 

Discourage users from using deprecated storage-drivers
by skipping them when automatically selecting a storage-
driver.

This change does not affect existing installations, because
existing state will take precedence.

Users can still use deprecated drivers by manually configuring
the daemon to use a specific driver.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @AkihiroSuda @andrewhsu @dmcgowan

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by cpuguy83** [comment]
Maybe we can also add a 10s sleep on initializing deprecated drivers? This sleep can be increased over time.

**Review by fntlnz — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
