### PR TITLE
Jenkinsfile: modprobe br_netfilter

### PR DESCRIPTION
**Pull request by thaJeztah**
**- What I did**

Make sure the module is loaded, as we're not able to load it from within
the dev-container;

    time="2024-11-29T20:40:42Z" level=error msg="Running modprobe br_netfilter failed with message: modprobe: WARNING: Module br_netfilter>

Also moving these steps _before_ the "print info" step, so that docker info
doesn't show warnings that bridge-nf-call-iptables and bridge-nf-call-ip6tables
are not loaded.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```markdown changelog

```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Whoop; this at least fixes the Jenkins situation

**Comment by thaJeztah** [comment]
I'll make one small change and move the mod probes _before_ "print info" so that the `docker info` output should hopefully no longer show the warnings;

```
[2024-11-29T21:20:50.870Z] WARNING: bridge-nf-call-iptables is disabled
[2024-11-29T21:20:50.870Z] WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by thaJeztah** [comment]
Scratch that; moving to before `docker info` doesn't help; perhaps because it's already running;


```
[2024-11-29T21:52:25.614Z] WARNING: bridge-nf-call-iptables is disabled
[2024-11-29T21:52:25.614Z] WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by thaJeztah** [comment]
OK; restarting the docker service does the trick for that 👍

**Review by austinvazquez — APPROVED** [review]

**Comment by austinvazquez** [comment]
Pulling this in to unblock others. Thanks for the deep dive.

**Pull request merged**
