### PR TITLE
[carry 19752] vendor: update runc/libcontainer to v0.0.8

### PR DESCRIPTION
**Pull request by cyphar**
For a list of changes, see https://github.com/opencontainers/runc/releases/tag/v0.0.8

Closes #19752

Signed-off-by: Aleksa Sarai asarai@suse.com

~~This depends on opencontainers/runc#552.~~ Everything this depends on has been merged.

/cc @jfrazelle @crosbymichael @icecrime

### CODE REVIEW

**Comment by cyphar** [comment]
The windows failures aren't caused by this PR.

**Comment by thaJeztah** [comment]
LGTM, thanks for carrying @cyphar

**Comment by LK4D4** [comment]
@cyphar btw there is 0.0.8 :/

**Comment by cyphar** [comment]
@LK4D4 I've bumped it to `v0.0.8`.

**Comment by cyphar** [comment]
Looks like the network tests are timing out. This doesn't happen on `v0.0.7`...

**Comment by cyphar** [comment]
Thank goodness I added a regression test for invalid cgroup paths. This could've ended badly. runC also broke that. o.O

**Comment by LK4D4** [comment]
@cyphar Seems like something with vendor.

**Comment by cyphar** [comment]
@LK4D4 Yeah, I've added some fixes that haven't yet been merged into runC (so I haven't updated `hack/vendor.sh` or someone might merge it).

**Comment by cyphar** [comment]
For some reason, `vendor` seems keen to drop the entirety of `gopkg.in/fsnotify.v1` ... I'll look into this later.

**Comment by LK4D4** [comment]
@cyphar yes, it's weird, it used in pkg/filenotify. ping @cpuguy83

**Comment by cpuguy83** [comment]
Yeah, this is because vebdor.sh will drop anything not used by the core. We don't use the file notify package anymore, so it's deps are being dropped.
Can make a or to remove it.

**Comment by thaJeztah** [comment]
@cpuguy83 that'd be great, I think this PR is currently blocking https://github.com/docker/docker/pull/19244 and https://github.com/docker/docker/pull/18697

**Comment by cyphar** [comment]
@cpuguy83 @LK4D4 @thaJeztah  Alright, I've opened a new PR to remove fsnotify: #20396.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
