### PR TITLE
skip api/types/container/ (like golint) and fix one pkg

### PR DESCRIPTION
**Pull request by vieux**
ping @tonistiigi

### CODE REVIEW

**Comment by vieux** [comment]
depends on #28611

**Comment by aaronlehmann** [comment]
build failing

**Comment by tonistiigi** [comment]
I also have 
```
pkg/system/filesys_windows.go:101: os.PathError composite literal uses unkeyed fields
pkg/system/filesys_windows.go:109: os.PathError composite literal uses unkeyed fields
pkg/system/filesys_windows.go:114: os.PathError composite literal uses unkeyed fields
pkg/system/filesys_windows.go:165: os.PathError composite literal uses unkeyed fields
pkg/system/filesys_windows.go:171: os.PathError composite literal uses unkeyed fields
```

**Comment by vieux** [comment]
@tonistiigi thanks, added.

**Comment by tonistiigi** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
