### PR TITLE
Fix & improve bash completion for swarm mode commands

### PR DESCRIPTION
**Pull request by albers**
Ref: #23363, #23476
## fixes
- `docker service {ls,tasks} --filter` was treated as a boolean option
- `docker node demote` would also complete files in the current directory
## new completions
- add completions for various filters in `docker {service,node} {ls,tasks}`
- complete the default port after `docker swarm init hostname:` and `--listen-addr hostname:`
## cleanup

There was duplicated logic in quite a bunch of helper funcions for service and node lookups.
This was refactored into two parameterized functions that now also deal with customization, see next item.
## configurable completions

For images and networks we already have environment variables that configure whether or not IDs should be used in completions. Now, you can configure this for services and nodes as well.

Please schedule for 1.12.0

ping @jfrazelle @tianon for review
ping @sdurrheimer Hi, maybe you can use this in zsh completion

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @mgoelzer @tianon PTAL

**Comment by albers** [comment]
Updated for the renamed filter `desired_state` => `desired-state`, see #24128

**Comment by icecrime** [comment]
Woohoo, thank you! :+1: LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
