### PR TITLE
Changed package name to docker.io in Debian install docs

### PR DESCRIPTION
**Pull request by mijndert**
In the Debian installation docs there was mention of a docker-io package
upon 'apt-get purge'. This should, imo, be docker.io.

Signed-off-by: Mijndert Stuij mijndert@mijndertstuij.nl

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Can you sign-off your commit? Also, there looks to be a merge-commit in the PR, so, perhaps you should rebase your changes; see https://docs.docker.com/project/work-issue/#pull-and-rebase-frequently

**Comment by crosbymichael** [comment]
ping @jfrazelle i have no clue what it's called today

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
can you squash your commits please

**Comment by SvenDowideit** [comment]
LGTM, assuming that there's squashage, signage and stuff :)

**Comment by thaJeztah** [comment]
@mijndert why did you close this? Were you running into problems squashing/signing? Are you going to update this PR or open a replacement?

**Comment by mijndert** [comment]
@thaJeztah sorry, going to open a replacement with more fixes. Couldn't get it to squash properly. First time I'm PRing on such a big project.

**Comment by thaJeztah** [comment]
No problem; feel free to ask for assistance in the #docker-dev IRC channel. But make sure you re-open this PR before pushing, otherwise it won't update

**Pull request closed without merging**
