### PR TITLE
[master] Re-vendor SwarmKit to af3f0e1e5eceef93191f77b6ed2be7959549464e

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by LK4D4** [comment]
@aluzzardi looks like compilation failed :scream:

**Comment by aaronlehmann** [comment]
BTW, running `vndr github.com/gogo/protobuf` will work around the build problems, but I don't think this is the right fix. `github.com/docker/swarmkit/protobuf/plugin` added a few extra dependencies that shouldn't be needed by downstreams. I've opened https://github.com/docker/swarmkit/pull/1923 to correct this.

**Comment by aaronlehmann** [comment]
docker/swarmkit#1923 was merged, so updating the version of swarmkit being vendored should solve the problem.

**Comment by ehazlett** [comment]
ping @aluzzardi

**Comment by aaronlehmann** [comment]
Closing this in favor of #30457, which revendors swarmkit

**Pull request closed without merging**
