### PR TITLE
update runc to v1.1.0

### PR DESCRIPTION
**Pull request by AkihiroSuda**
https://github.com/opencontainers/runc/releases/tag/v1.1.0-rc.1
https://github.com/opencontainers/runc/releases/tag/v1.1.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like something is failing in vendoring;

```

[2022-01-18T04:51:00.491Z] Building test suite binary /go/src/github.com/docker/docker/integration/build/test.main
[2022-01-18T04:51:26.997Z] # github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/configs
[2022-01-18T04:51:26.997Z] vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go:130:18: undefined: LinuxRdma
[2022-01-18T04:51:26.997Z] vendor/github.com/opencontainers/runc/libcontainer/configs/mount.go:34:11: undefined: unix.MountAttr
[2022-01-18T04:51:26.997Z] # github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/configs
[2022-01-18T04:51:26.997Z] vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go:130:18: undefined: LinuxRdma
[2022-01-18T04:51:26.997Z] vendor/github.com/opencontainers/runc/libcontainer/configs/mount.go:34:11: undefined: unix.MountAttr
[2022-01-18T04:51:36.948Z] Building test suite binary /go/src/github.com/docker/docker/integration/config/test.main
[2022-01-18T04:51:37.880Z] Building test suite binary /go/src/github.com/docker/docker/integration/container/test.main
[2022-01-18T04:51:44.423Z] # github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/configs
[2022-01-18T04:51:44.423Z] vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go:130:18: undefined: LinuxRdma
[2022-01-18T04:51:44.423Z] vendor/github.com/opencontainers/runc/libcontainer/configs/mount.go:34:11: undefined: unix.MountAttr
```

**Comment by thaJeztah** [comment]
@AkihiroSuda https://github.com/moby/moby/pull/43101 was merged; can you rebase and fix the vendoring?

**Comment by AkihiroSuda** [comment]
Rebased

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
Arf, looks like the vendor check failed (for some reason it didn't fail Jenkins though, but just timed out)

I guess it needs a `go mod tidy` (we really should move that bit to `vendor.sh`, not just in the check)

```
[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-180)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-181)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-182)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-183)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-184)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-185)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-186)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-187)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-188)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-189)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-190)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-191)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-192)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-193)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-194)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-195)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-196)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-197)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-198)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-199)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-200)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-201)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-202)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-203)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-204)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-205)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-206)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-207)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-208)[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43083/7/#step-409-log-209)[2022-02-04T13:07:01.915Z] The result of go mod vendor differs
[2022-02-04T13:07:01.915Z] 
[2022-02-04T13:07:01.915Z]  M vendor.sum
[2022-02-04T13:07:01.915Z] 
[2022-02-04T13:07:01.915Z] Please vendor your package with hack/vendor.sh.
[2022-02-04T13:07:01.915Z] 
[2022-02-04T13:07:01.915Z] diff --git a/vendor.sum b/vendor.sum
[2022-02-04T13:07:01.915Z] index 65bc5f7174..f9395ee958 100644
[2022-02-04T13:07:01.915Z] --- a/vendor.sum
[2022-02-04T13:07:01.915Z] +++ b/vendor.sum
[2022-02-04T13:07:01.915Z] @@ -81,7 +81,6 @@ github.com/chzyer/readline v0.0.0-20180603132655-2972b
[2022-02-04T13:07:01.915Z] e24d48e/go.mod h1:nSuG5e5P
[2022-02-04T13:07:01.915Z]  github.com/chzyer/test v0.0.0-20180213035817-a1ea475d72b1/go.mod h1:Q3SI9o4m/ZM
[2022-02-04T13:07:01.915Z] nBNeIyt5eFwwo7qiLfzFZmjNmxjkiQlU=
[2022-02-04T13:07:01.915Z]  github.com/cilium/ebpf v0.2.0/go.mod h1:To2CFviqOWL/M0gIMsvSMlqe7em/l1ALkX1Pyjr
[2022-02-04T13:07:01.915Z] X2Qs=
[2022-02-04T13:07:01.915Z]  github.com/cilium/ebpf v0.4.0/go.mod h1:4tRaxcgiL706VnOzHOdBlY8IEAIdxINsQBcU4xJ
[2022-02-04T13:07:01.915Z] JXRs=
[2022-02-04T13:07:01.915Z] -github.com/cilium/ebpf v0.6.2 h1:iHsfF/t4aW4heW2YKfeHrVPGdtYTL4C4KocpM8KTSn
[2022-02-04T13:07:01.915Z] I=
[2022-02-04T13:07:01.915Z]  github.com/cilium/ebpf v0.6.2/go.mod h1:4tRaxcgiL706VnOzHOdBlY8IEAIdxINsQBcU4xJ
[2022-02-04T13:07:01.915Z] JXRs=
[2022-02-04T13:07:01.915Z]  github.com/cilium/ebpf v0.7.0 h1:1k/q3ATgxSXRdrmPfH8d7YK0GfqVsEKZAX9dQZvs56k=
[2022-02-04T13:07:01.915Z]  github.com/cilium/ebpf v0.7.0/go.mod h1:/oI2+1shJiTGAMgl6/RgJr36Eo1jzrRcAWbcXO2
[2022-02-04T13:07:01.915Z] usCA=
[2022-02-04T13:07:01.915Z] @@ -95,7 +94,6 @@ github.com/containerd/cgroups v0.0.0-20210114181951-8a
[2022-02-04T13:07:01.915Z] 68de567b68/go.mod h1:ZJeTF
[2022-02-04T13:07:01.915Z]  github.com/containerd/cgroups v1.0.1 h1:iJnMvco9XGvKUvNQkv88bE4uJXxRQH18efbKo9w
[2022-02-04T13:07:01.915Z] 5vHQ=
[2022-02-04T14:32:05.263Z] --More--Sending interrupt signal to process
[2022-02-04T14:32:25.264Z] After 20s process did not stop
```

**Comment by thaJeztah** [comment]
I opened https://github.com/moby/moby/pull/43212 to update the `hack/vendor.sh` scripts to run `go mod tidy`

**Comment by thaJeztah** [comment]
Can you rebase and run the vendor script again to fix ci? 🤗

**Pull request merged**
