### PR TITLE
Fix a typo and a minor formatting issue in the docs.

### PR DESCRIPTION
**Pull request by ghost**
Two very minor changes: removed a typo in `test-and-docs.md` and fixed a formatting issue in `create-pr.md` and `work-issue.md` (the same issue as the text is identical).

I think the HTML-style link was causing a parsing issue so I replaced it with Markdown syntax.

### CODE REVIEW

**Comment by thaJeztah** [comment]
> I think the HTML-style link was causing a parsing issue so I replaced it with Markdown syntax.

What issue did you encounter with the link? IIRC, the reason for adding those links as HTML was to be able to add a `target=_blank`. While I'm not really happy with mixed HTML/Markdown, it'd be good to keep that.

Keep in mind that the docs use a different Markdown renderer than GitHub, so make sure to test the changes using [the instructions here](https://docs.docker.com/project/test-and-docs/#build-and-test-the-documentation) to see if if works correctly.

**Comment by eolamey** [comment]
You are right about the `target` stuff, sorry, I totally overlooked that. I did test my changes using `make docs` (awesome feature, btw): once I fixed the quotes around `git commit -s`, the remaining text didn't render properly, that's why I had to switch from HTML to Markdown. Actually, the whole `Make sure you...` line disappears when using the HTML link.
I'm guessing it's because the text is indented and part of a list of items, but I'm note sure.

**Comment by thaJeztah** [comment]
Looking at the docs that are currently build from master; http://docs.master.dockerproject.org/project/create-pr/#rebase-your-branch they are indeed broken.

*And I just spotted why!* Look at this;

    <a href="./set-up-git" target="_blank>your signature</a>.

The `target="_blank` is missing a closing quote (`"`). This must have gone unnoticed somewhere during an update.

So, I think this can be fixed by adding back the HTML links and adding the closing quote for those links (perhaps check if there are others in that document)

If you can make those changes, that would be awesome. Thanks for bringing this to our attention, because it was clearly overlooked. :+1:

**Comment by eolamey** [comment]
D'oh! I'm such a doofus, sorry for wasting your time. I reverted my change, added the `"` and a missing dot as well, as the link should be for `../set-up-git`, like other similar links in the docs.

Grep didn't find any other occurence of a missing quote in the docs.

**Comment by thaJeztah** [comment]
> D'oh! I'm such a doofus, sorry for wasting your time.

No! You're not, and you didn't waste my/our time! You brought our attention to a bug in the docs that we failed to notice. It's the tiny things that count and this is really appreciated :heart:, So if this is your definition of "wasting time", feel free to waste more!

LGTM (but I'm on the road, and didn't build the docs on the PR to do a final check)

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by jamtur01** [comment]
Nice catch!

**Comment by eolamey** [comment]
Thanks @thaJeztah!

The docker docs are pretty good in general but the ones for contributing are just awesome, I'm really thankful that you all put so much thoughts into this.

**Comment by thaJeztah** [comment]
I think @moxiegirl will be very happy to hear that, she wrote those docs and I agree, did a very good job on that.

**Comment by moxiegirl** [comment]
@eolamey Thanks for the catch and the contribution.  Glad you found the documentation useful --- always good to hear!

**Comment by moxiegirl** [comment]
@jfrazelle cherry pick on this one please

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
