### PR TITLE
Update the link for understand data volumes

### PR DESCRIPTION
**Pull request by yuexiao-wang**
**\- What I did**
Update the link for understand data volumes

**\- How I did it**
Update the link for understand data volumes in docker/docker.github.io

**\- How to verify it**
Access to the page

**\- Description for the changelog**
The new link is https://docs.docker.com/engine/tutorials/dockervolumes/.

Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

### CODE REVIEW

**Comment by vdemeester** [comment]
/cc @thaJeztah 
This is tricky… I think we should link to `docs.docker.com` instead of the github source file.

**Comment by thaJeztah** [comment]
ah, yes, similar to the other PR

technically, the current links are OK, because these files are synced with the docker.github.io repository, where all the other pages still live

perhaps we should add a big banner to say that navigation / links are broken when viewed here, and link to the same file in the docker.github.io repository (if people view them on GitHub)

/cc @mstanleyjones do we have a list of things that we need to sort out?

**Review by mdlinville — CHANGES_REQUESTED** [review]
Yes, please use https://docs.docker.com/engine/tutorials/dockervolumes/ for this link. We should use the docs.docker.com URLs where possible because they are much less likely to break.

**Comment by yuexiao-wang** [comment]
@mstanleyjones @thaJeztah @vdemeester PTAL
Got it and I have updated this PR. 
Thanks so much for your suggestion!

**Comment by thaJeztah** [comment]
Thanks @yuexiao-wang - we're still working out the best way to do this, so bear with us :smile:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by mdlinville — CHANGES_REQUESTED** [review]
LGTM but please resolve the conflicts.

**Comment by thaJeztah** [comment]
@yuexiao-wang can you rebase? Then we can go ahead and merge

**Comment by yuexiao-wang** [comment]
@thaJeztah @mstanleyjones PTAL
Thanks!

**Comment by thaJeztah** [comment]
did you stage and push your changes? It still says there's conflicts

**Comment by yuexiao-wang** [comment]
Sorry, I found it and I'm resolving it now.

**Comment by yuexiao-wang** [comment]
@thaJeztah PTAL
There are some other commits updated to this PR.
Can I solve it?

**Comment by thaJeztah** [comment]
Assuming your "upstream" (docker) is called "upstream"; `git fetch upstream` then `git rebase upstream/master`

**Comment by yuexiao-wang** [comment]
@thaJeztah @mstanleyjones PTAL
It is done to resolve the conflicts.
Thanks very much for @thaJeztah's help!

**Review by mdlinville — APPROVED** [review]
LGTM

**Pull request merged**
