### PR TITLE
Move VolumeDriver to HostConfig to make containers portable.

### LINKED ISSUE #15342: VolumeDriver currently in Config, not HostConfig
I wanted to raise this because I feel like it's wrong.
Currently `VolumeDriver` is specified in `Config` instead of `HostConfig`, even though this is a host-specific configuration. And, for instance, I wouldn't want someone to commit a container to an image where it's specifying some plugin as a driver.

### PR DESCRIPTION
**Pull request by calavera**
Fixes #15342

/cc @cpuguy83 

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
lint errors on missing comments for new exported types.

**Comment by cpuguy83** [comment]
Definitely a +1 from me since I created the issue :)

**Comment by thaJeztah** [comment]
Yup, +1 from me for changing this. Don't forget to update the docs and man-pages if this moves further.

**Comment by cpuguy83** [comment]
Should this require backwards compat or should this part of 1.8.2 and thus modify the current API?

**Comment by cpuguy83** [comment]
My thought is make it part of 1.8.x.

**Comment by thaJeztah** [comment]
I'm +1 to making it part of 1.8.x, regarding it a "fix" and to reduce the exposure (yes, it's awkward doing an API change in a dot-release, but we should try to avoid people starting to rely on this)

**Comment by calavera** [comment]
@cpuguy83, @thaJeztah I'm neutral, but this change is completely backwards compatible. Containers started `VolumeDriver` in the config still work as expected if stopped and started with this new code.

**Comment by cpuguy83** [comment]
@calavera Oh yes, makes sense. We have to support already created containers here.

**Comment by cpuguy83** [comment]
I still see `VolumeDriver` showing up in the inspect output and not in HostConfig.
It does work, though, as `VolumeDriver` which was committed to the image is not used by a container created from that image.

**Comment by calavera** [comment]
@cpuguy83 version numbers are hard! I'm going to add some tests for the inspect output.

**Comment by calavera** [comment]
I've added a couple of integration tests to prevent regressions. It turned out that I left the field in the config inspect for the next version of docker :pensive:

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
I've rebased this. Please, take a look.

**Comment by bboreham** [comment]
If I understand correctly, this design still only allows one VolumeDriver per container.  What happens if you want to mount one volume using Flocker and one using Convoy?

**Comment by cpuguy83** [comment]
@bboreham Need to use `docker volume create`, then bind that volume in using the name.

**Comment by cpuguy83** [comment]
@calavera external volume tests are failing.

**Comment by thaJeztah** [comment]
@bboreham using the new volume API, this should work;

```Bash
docker run -d \
   -v $(docker volume create --driver=foo):/volume-a/ \
   -v $(docker volume create --driver=bar):/volume-b/ \
   my-image
```

**Comment by bboreham** [comment]
Ah, right, thanks.  Wasn't clear from https://docs.docker.com/extend/plugins_volume/

**Comment by thaJeztah** [comment]
@bboreham it's not released yet; the `volume create` command will be in the next release (docker 1.9), but you can experiment with it, by downloading a binary from https://master.dockerproject.org (there are still some bugs, so tread carefully)

**Comment by crosbymichael** [comment]
@calavera volume test are failing after rerunning the tests.

**Comment by calavera** [comment]
@crosbymichael I don't know what happened with those tests, but it looks like it's passing now.

**Comment by crosbymichael** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
