### PR TITLE
Bump plugin API version

### PR DESCRIPTION
**Pull request by cpuguy83**
This should have been updated with the changes to volume drivers (#16534).

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐭

**Comment by ibuildthecloud** [comment]
@cpuguy83 Whoa!?  What is the impact of this? By bumping the version does this mean Docker 1.10 will reject drivers of version v1.1?

**Comment by ibuildthecloud** [comment]
Sorry guys, I'm confused on the what this version is used for?  It seems to be a global "plugins" version so I don't see why the version should change if the volume API changed.  The is version seems to indicate the version of the plugin handshake.

**Comment by cpuguy83** [comment]
This should be handled by the plugin...
But pinging @calavera
This is how I was told we handle these sorts of changes -- may not be ideal especially with networking in stable and using plugins.
At the time it was just volumes.

**Comment by mavenugo** [comment]
there has been some extra fields added to the network plugin protocol as well.
They are just additions and it will NOT affect the backward compatibility.
Just making sure if this will impact existing plugins in anyway.

**Comment by ibuildthecloud** [comment]
Not-LGTM? I don't think this version needs to be bumped as the handshake because daemon/plugin has not changed.

**Comment by calavera** [comment]
I'm pretty sure we don't validate this field at the moment in any ways, but I might be mistaken.

We introduced changes in the volume plugins that are not (completely) backwards compatible afaik, so we should probably bump this version.

**Comment by calavera** [comment]
This change LGTM.

We use this header to advertise that the docker daemon "Accepts" plugins with that version, but we don't reject responses from other versions.

**Comment by thaJeztah** [comment]
Added impact labels

**Pull request merged**
