### PR TITLE
partial image export

### PR DESCRIPTION
**Pull request by a-ba**
close #3870

This PR introduces the `--exclude` option in  `docker save` (and in the underlying API) to exclude the given layers from the created archive.

 Note : I used --exclude instead of --have (as I suggested in #3870) because it is clearer in the documentation and consistent with the meaning of --exclude in archiving utilities like `tar`

### CODE REVIEW

**Comment by zoltrain** [comment]
I've been having a discussion around adding individual layer export to the daemon, not just the registry.

https://github.com/docker/docker/issues/8039

It seems this offers "a" way to do this, though in my use case I only ever want 1 image, so I'd need to construct a list of all images and exclude all bar one. 

Another option would be adding the inverse of this flag, --include?

Seems like it wouldn't be terribly difficult to add, and if your exclusion list is large it would save people some typing.

**Comment by icecrime** [comment]
Thanks for the contribution, however we are working on phasing out the concept of layers from the UX and provide higher abstractions for our image definition format. This feature you add is very dependent on the notion of layer, so we're -1 on its design, sorry.

**Comment by zoltrain** [comment]
Where can we find details on this "image definition format"?

Just so we know what's happening in regards to phasing out layers.

**Comment by sahus5** [comment]
@icecrime 
Where can we find more information on image format? Is there any design, doc we can refer to?

**Comment by sahus5** [comment]
@icecrime 
Where can we find more information on image format? Is there any design, doc we can refer to?

**Comment by sahus5** [comment]
@icecrime 
Where can we find more information on image format? Is there any design, doc we can refer to?

**Comment by runcom** [comment]
@zoltrain @sahus5  https://github.com/docker/docker/blob/master/image/spec/v1.md

**Comment by sheerun** [comment]
@icecrime @runcom I see v1 spec of image format still uses notion of "Layer". Do you still plan to phase it out? If not, would you reconsider re-opening this PR?

**Comment by 1ubuntuuser** [comment]
@icecrime Could this be reconsidered? Layers still seem at large. This would be very handy for a use case of mine.

**Pull request closed without merging**
