### PR TITLE
Provide correct superlink for installing docker compose

### PR DESCRIPTION
**Pull request by lixiaobing1**
Previous superlink "/compose/installed.md" cann't be found, should be modified to another one.

### CODE REVIEW

**Comment by justincormack** [comment]
Are you sure? I think the docs build fixes up the link, as the live link seems fine.

**Comment by lixiaobing10051267** [comment]
@justincormack but there is no file "/compose/install.md" in the docker source code, and superlink for installing composer at other places such as trust_sandbox.md is just like this:

    To install Docker Compose, see the [detailed instructions here]  (https://docs.docker.com/compose/install/).

**Comment by justincormack** [comment]
cc @londoncalling

**Comment by londoncalling** [comment]
@lixiaobing10051267 @justincormack we can't approve this change because the link is already properly formatted. The target of the link is https://github.com/docker/compose/blob/master/docs/install.md. The build system converts markdown to HTML, and renders the link properly; i.e., if you take the [here](https://docs.docker.com/engine/security/trust/deploying_notary/#deploying-notary-server-with-compose) to "installed Docker Compose", it works.

 As a general policy and to fit with our docs build tooling and link checkers, we keep the `.md` file extensions.

**Comment by lixiaobing10051267** [comment]
ok.

**Pull request closed without merging**
