### PR TITLE
Update docker.fish

### PR DESCRIPTION
**Pull request by jessfraz**
Docker-DCO-1.1-Signed-off-by: Jessie Frazelle jess@docker.com (github: jfrazelle)

### CODE REVIEW

**Comment by jfrazelle** [comment]
resplaces #10253

**Comment by tianon** [comment]
Shouldn't your commit include his sign-off from https://github.com/docker/docker/pull/10253#issuecomment-70937531 too?

**Comment by jfrazelle** [comment]
I don't know if thats cheating?

**Comment by jfrazelle** [comment]
ping @crosbymichael

**Comment by tianon** [comment]
Didn't we hash all this out before?  I thought what we'd worked out was that a carry could copy the sign-off into the commit from a comment, since how you've done it here feels like cheating even more to me (so I'd personally rather see both if we do this), but I defer to @crosbymichael :heart:.

**Comment by crosbymichael** [comment]
Should include both but since he does not have one...

**Comment by tianon** [comment]
He added one in a comment -- this is what @SvenDowideit was trying to clarify if it was legit before.

**Comment by jfrazelle** [comment]
ok added

**Comment by crosbymichael** [comment]
ok
LGTM

**Comment by thaJeztah** [comment]
Some repos even add [`Reviewed-by`](https://git.eclipse.org/r/Documentation/user-signedoffby.html). OT for this discussion, but I think it *does* add value, because the review process is embedded in source control, and not relying on GitHub.

**Comment by jfrazelle** [comment]
@tianon for the merge wooo

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
