### PR TITLE
Docs update 1.6 # 1

### PR DESCRIPTION
**Pull request by moxiegirl**
Fix for machine docs
https://github.com/docker/docker/pull/13003
8c9d67921a44e4f189373d8dc10fc8946039918d

Fix for support on Official Repo wording
https://github.com/docker/docker/pull/12993 
3efc083d4a785b2c7b1c1f862133167d5618d216

Jess Debian
https://github.com/docker/docker/pull/12801
b6cfe7ca07722cee22345602595fc8fb928dbe79

https://github.com/docker/docker/pull/12484
37b9ce61ac5aa762cf0ad34d84bc1924807a7617

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @jfrazelle Make sure I have this right for you Jess.

ping @docker/docs-owners

**Comment by jfrazelle** [comment]
perfect yayyy! thanks!!! LGTM

**Comment by thaJeztah** [comment]
Checked that the machine/docs branch was present (better be sure), other changes look okay as well, so LGTM

@moxiegirl Waiting for lights to go green for good measure, but feel free to merge if you're in a hurry

**Comment by thaJeztah** [comment]
For future reference, this is not the *first* docs update after the 1.6 release, but using the "docs update #xxx" wasn't used in prior merges :smile_cat:

**Comment by thaJeztah** [comment]
Windows build failed. Windows users will need to get a proper computer to read the docs. 

I'm brave; merging :smile:

**Comment by moxiegirl** [comment]
Thanks @thaJeztah I really hate to merge on a broken build. It is bad practice...but right now bigger fish to fry.

**Comment by thaJeztah** [comment]
@moxiegirl the broken build seemed really unrelated (iptables running out of memory) and I thought I'd save you the stress. Just blame me in this case!

**Comment by jfrazelle** [comment]
yeah we should try to get in some docs tests with the apis like we talked about then the broken build would mean something :)

**Comment by moxiegirl** [comment]
Lordy @thaJeztah did it sound like I was blaming anyone? I'm just bemoaning the bad practice --- mostly cause I'm always willing to slide down a slipper slope to hell.  @jfrazelle I have plans...schemes...and plans. 

witchy

**Comment by thaJeztah** [comment]
no worries; I'd like to merge on green lights only as well, but for the docs branch I know that the code will never be used, so....

Some tests for the docs would be great, also; skipping other tests for a docs-only PR would be a big time-saver :)

**Pull request merged**
