### PR TITLE
Removed unused compression arg in Graph.TempLayerArchive()

### PR DESCRIPTION
**Pull request by bobrik**
It was confusing so I deleted it.

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by bobrik** [comment]
Oh, I copy-pasted that from my previous PR, looks like things changed a bit. I updated comment.

**Comment by unclejack** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
