### PR TITLE
Add wildcard support for rmi command

### PR DESCRIPTION
**Pull request by gzoller**
Automated CI/CD processes can spew a lot of Docker images, for example one for each commit on different branches.  We like to stamp images with a chunk of the git commit hash so we can always tie an image back to the code that built it.  Fantastic idea but it does create a LOT of images!

The current 'docker rmi' command is a one-per operation, so to help make this less tedious this PR seeks to add simple wildcarding to the process, so you can do this:

docker rmi foo/bar:stage_*
docker rmi foo/bar:*
docker rmi foo/bar:*RC

This simple implementation is purely on the client-side so the server-side behavior is unmolested.

### CODE REVIEW

**Comment by duglin** [comment]
Couple of things:
1 - if we do this, it might be better to do it on the daemon side rather than the cli. In cases where the list of images is really large I don't think we'd want the overhead of moving the data between the two. 
2 - we'd need docs and testcases.
3 - clearly it needs to be signed too :-)

**Comment by jfrazelle** [comment]
why not grep tho?

**Comment by jfrazelle** [comment]
and a pipe?

**Comment by runcom** [comment]
+1 for grep&pipe from docker images

**Comment by gzoller** [comment]
I'm not sure what grep+pipe means.  I get the concept of not festooning the cli with a lot of ugly barnacles  but my thought here is that wildcard support is a fairly basic capability.  As for client vs server, I don't disagree it would be more efficient on the server fpr the reasons stated, but 1) that exceeds my current understanding and 2) at least as a first cut, this was the least surgery to the system.

I guess what gave me a little pause, beyond my own newbie-ness to the Docker code, was that the entire server infrastructure seemed set up to handle one DELETE command call at a time.  (correct?)  If true then adding the ability to handle more than one deletion would involve some careful thought--that architecturally may extend beyond just removing images.  Another reason I shied away from such a big lift on my first venture out. :-)

**Comment by cpuguy83** [comment]
I think this is dangerous to support on the client, and I don't think it belongs in the daemon.
`*` will be interpreted by the shell first unless you explicitly escape it or quote it.
It would be better to make sure the filtering API on the image list can filter the list of images that you then  pipe into `docker rmi`

**Comment by jfrazelle** [comment]
yes I am -1, I think you can do this in bash

**Comment by cpuguy83** [comment]
@gzoller Thanks for submitting but I don't think this one is going to work out.
Admittedly when I first saw the syntax I was thinking "oh cool!", but unfortunately the semantics of the shell just don't work out for something like this.

Thanks again!

**Pull request closed without merging**
