### PR TITLE
Add bash completion for `docker inspect --type plugin`

### PR DESCRIPTION
**Pull request by albers**
Ref: #28967
Please schedule for 1.13.0 as the corresponding functionality is present in that release,
ping @sdurrheimer for zsh completion

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐻

**Comment by sdurrheimer** [comment]
Just saw there is no `docker inspect --type=volume`, @vdemeester ?

**Comment by vdemeester** [comment]
@sdurrheimer in the code there is 👼 (https://github.com/docker/docker/blob/master/cli/command/system/inspect.go#L48)

**Comment by thaJeztah** [comment]
@sdurrheimer there should be; see [cli/command/system/inspect.go#L113](https://github.com/docker/docker/blob/90bb2cdb9f15a9b1b9a4e2ea4242882665daac4e/cli/command/system/inspect.go#L113)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
