### PR TITLE
Vendoring in libnetwork and libkv

### PR DESCRIPTION
**Pull request by mavenugo**
- libkv upgrade is required for https://github.com/docker/docker/pull/16229
  it has a bunch of good fixes for etcd and zookeeper backends.
- vendor-in libnetwork contains an update to network plugin api
  Thanks @WeiZhang555 : https://github.com/docker/libnetwork/pull/516

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @icecrime libkv upgrade that is required for https://github.com/docker/docker/pull/16229

**Comment by icecrime** [comment]
:+1:

**Comment by mavenugo** [comment]
@icecrime I will do another update to this vendor in to pick up another minor change that resolves a bug in overlay. It will be useful for the hackathon today.

**Comment by icecrime** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
