### PR TITLE
add fileutils_darwin.go in pkg/fileutils to support darwin platform

### PR DESCRIPTION
**Pull request by allencloud**
add fileutils_darwin.go in pkg/fileutils to support darwin platform

This PR can finish a part of work described in #22470

### CODE REVIEW

**Comment by justincormack** [comment]
This does not seem very useful as it just returns an error. This information is available from osx.

**Comment by allencloud** [comment]
how about using `lsof -p PID | wc -l` ?
@justincormack

**Comment by allencloud** [comment]
Actually. I am very concerned about this design.
Any better guidance about get fds of process in osx?
@justincormack @LK4D4

**Comment by justincormack** [comment]
I believe this may be the underlying interface, although I don't know the XNU internals very well https://github.com/aosm/xnu/blob/master/bsd/kern/proc_info.c#L372

**Comment by allencloud** [comment]
ping @justincormack 
Sorry for that I am not so familiar with the OSX underlying interface with golang.
Now still with `lsof`,  PTAL.

**Comment by allencloud** [comment]
any update?  @justincormack @thaJeztah PTAL

**Comment by LK4D4** [comment]
LGTM
ping @justincormack

**Comment by LK4D4** [comment]
@allencloud I found some example of usage in C
https://github.com/palominolabs/get_process_handles/blob/master/main.c

I wonder if you wanna write some cgo. It's ok for me as it is, though.

**Comment by allencloud** [comment]
Something strange happens. While I run the c code and `lsof -p PID`, the result differs a lot.

```
Desktop $  ./a.out 1698
Open file: /dev/null
Open file: /dev/null
Open file: /dev/null
Open file: /dev/random
Desktop $  lsof -p 88
Desktop $  lsof -p 1698
COMMAND    PID     USER   FD     TYPE             DEVICE  SIZE/OFF     NODE NAME
com.apple 1698 AllenSun  cwd      DIR                1,4      1122        2 /
com.apple 1698 AllenSun  txt      REG                1,4    132240 37249034 /System/Library/PrivateFrameworks/CloudServices.framework/Versions/A/XPCServices/com.apple.lakitu.xpc/Contents/MacOS/com.apple.lakitu
com.apple 1698 AllenSun  txt      REG                1,4     21920 37234982 /System/Library/PrivateFrameworks/AOSAccountsLite.framework/Versions/A/AOSAccountsLite
com.apple 1698 AllenSun  txt      REG                1,4    158592 37246478 /System/Library/CoreServices/Encodings/libSimplifiedChineseConverter.dylib
com.apple 1698 AllenSun  txt      REG                1,4     50744 60657886 /private/var/db/mds/system/mdsDirectory.db
com.apple 1698 AllenSun  txt      REG                1,4     32768 60657888 /private/var/db/mds/messages/se_SecurityMessages
com.apple 1698 AllenSun  txt      REG                1,4  24438480 37260699 /usr/share/icu/icudt53l.dat
com.apple 1698 AllenSun  txt      REG                1,4    506080 60663534 /Users/AllenSun/Library/Keychains/login.keychain
com.apple 1698 AllenSun  txt      REG                1,4    219052 60569885 /Library/Keychains/System.keychain
com.apple 1698 AllenSun  txt      REG                1,4    469704 37352767 /System/Library/Keychains/SystemRootCertificates.keychain
com.apple 1698 AllenSun  txt      REG                1,4    622896 37335050 /usr/lib/dyld
com.apple 1698 AllenSun  txt      REG                1,4 383907859 37708031 /private/var/db/dyld/dyld_shared_cache_x86_64h
com.apple 1698 AllenSun    0r     CHR                3,2       0t0      303 /dev/null
com.apple 1698 AllenSun    1u     CHR                3,2       0t0      303 /dev/null
com.apple 1698 AllenSun    2u     CHR                3,2       0t0      303 /dev/null
com.apple 1698 AllenSun    3u  KQUEUE                                       count=2, state=0x2
com.apple 1698 AllenSun    4r     CHR               11,0    0t1728      576 /dev/random
com.apple 1698 AllenSun    5u    unix 0xdee6987938fb3bb7       0t0          ->0xdee698793ad82327
com.apple 1698 AllenSun    8u    unix 0xdee698793ad82327       0t0          ->0xdee6987938fb3bb7
```

**Comment by allencloud** [comment]
Since different output happens. I am agree with `lsof` as it is more general.
WDYT?
@LK4D4 @justincormack

**Comment by LK4D4** [comment]
LGTM
ping @docker/core-engine-maintainers

**Comment by thaJeztah** [comment]
LGTM,  thanks!

**Pull request merged**
