### PR TITLE
fixing consistent aliases for OCI spec imports

### LINKED ISSUE #45194: [chore] use more consistent aliases for OCI spec imports
### Description

I noticed that we started to use more different aliases for this import, which can be confusing, make it more difficult to find uses, and (baring linters catching them) could lead to duplicate imports.

Here's a quick check of aliases that we currently use;

```bash
git grep '"github.com/opencontainers/image-spec/specs-go/v1"'
api/server/router/container/container_routes.go:                specs "github.com/opencontainers/image-spec/specs-go/v1"
api/server/router/distribution/distribution_routes.go:          v1 "github.com/opencontainers/image-spec/specs-go/v1"
api/server/router/image/backend.go:                             specs "github.com/opencontainers/image-spec/specs-go/v1"
api/server/router/image/image_routes.go:                        specs "github.com/opencontainers/image-spec/specs-go/v1"
api/types/backend/build.go:                                     specs "github.com/opencontainers/image-spec/specs-go/v1"
api/types/configs.go:                                           specs "github.com/opencontainers/image-spec/specs-go/v1"
api/types/image/opts.go:import                                  specs "github.com/opencontainers/image-spec/specs-go/v1"
api/types/registry/registry.go:                                 v1 "github.com/opencontainers/image-spec/specs-go/v1"
builder/builder-next/adapters/containerimage/pull.go:           ocispec "github.com/opencontainers/image-spec/specs-go/v1"
builder/builder-next/adapters/localinlinecache/inlinecache.go:  specs "github.com/opencontainers/image-spec/specs-go/v1"
builder/builder-next/exporter/mobyexporter/writer.go:           ocispec "github.com/opencontainers/image-spec/specs-go/v1"
builder/builder-next/worker/worker.go:                          ocispec "github.com/opencontainers/image-spec/specs-go/v1"
builder/dockerfile/builder.go:                                  specs "github.com/opencontainers/image-spec/specs-go/v1"
builder/dockerfile/copy.go:                                     specs "github.com/opencontainers/image-spec/specs-go/v1"
builder/dockerfile/dispatchers.go:                              specs "github.com/opencontainers/image-spec/specs-go/v1"
builder/dockerfile/imagecontext.go:                             specs "github.com/opencontainers/image-spec/specs-go/v1"
builder/dockerfile/imagecontext_test.go:                        ocispec "github.com/opencontainers/image-spec/specs-go/v1"
builder/dockerfile/internals.go:                                specs "github.com/opencontainers/image-spec/specs-go/v1"
client/container_create.go:                                     specs "github.com/opencontainers/image-spec/specs-go/v1"
client/interface.go:                                            specs "github.com/opencontainers/image-spec/specs-go/v1"
client/service_create_test.go:                                  v1 "github.com/opencontainers/image-spec/specs-go/v1"
container/container.go:                                         ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/cluster/executor/backend.go:                             specs "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image.go:                                     ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image_commit.go:                              ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image_exporter.go:                            ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image_history.go:                             ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image_import.go:                              ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image_list.go:                                v1 "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image_pull.go:                                specs "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/image_snapshot.go:                            v1 "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/progress.go:                                  ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/containerd/service.go:                                   ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/content.go:                                              ocispec "github.com/opencontainers/image-spec/specs-go/v1"
daemon/create.go:                                               v1 "github.com/opencontainers/image-spec/specs-go/v1"
daemon/image_service.go:                                        v1 "github.com/opencontainers/image-spec/specs-go/v1"
daemon/images/image.go:                                         specs "github.com/opencontainers/image-spec/specs-go/v1"
daemon/images/image.go:                                         v1 "github.com/opencontainers/image-spec/specs-go/v1"
daemon/images/image_builder.go:                                 specs "github.com/opencontainers/image-spec/specs-go/v1"
daemon/images/image_import.go:                                  specs "github.com/opencontainers/image-spec/specs-go/v1"
daemon/images/image_pull.go:                                    specs "github.com/opencontainers/image-spec/specs-go/v1"
daemon/images/images_test.go:                                   specs "github.com/opencontainers/image-spec/specs-go/v1"
daemon/images/store_test.go:                                    v1 "github.com/opencontainers/image-spec/specs-go/v1"
distribution/config.go:                                         specs "github.com/opencontainers/image-spec/specs-go/v1"
distribution/manifest.go:                                       specs "github.com/opencontainers/image-spec/specs-go/v1"
distribution/manifest_test.go:                                  specs "github.com/opencontainers/image-spec/specs-go/v1"
distribution/pull_v2.go:                                        specs "github.com/opencontainers/image-spec/specs-go/v1"
distribution/pull_v2_test.go:                                   specs "github.com/opencontainers/image-spec/specs-go/v1"
distribution/pull_v2_unix.go:                                   specs "github.com/opencontainers/image-spec/specs-go/v1"
distribution/pull_v2_windows.go:                                specs "github.com/opencontainers/image-spec/specs-go/v1"
distribution/registry.go:                                       ocispec "github.com/opencontainers/image-spec/specs-go/v1"
integration/container/create_test.go:                           specs "github.com/opencontainers/image-spec/specs-go/v1"
integration/image/pull_test.go:                                 imagespec "github.com/opencontainers/image-spec/specs-go/v1"
integration/internal/container/container.go:                    specs "github.com/opencontainers/image-spec/specs-go/v1"
integration/internal/container/ops.go:                          specs "github.com/opencontainers/image-spec/specs-go/v1"
integration/plugin/common/plugin_test.go:                       v1 "github.com/opencontainers/image-spec/specs-go/v1"
libcontainerd/remote/client.go:                                 v1 "github.com/opencontainers/image-spec/specs-go/v1"
pkg/platforms/platforms.go:                                     ocispec "github.com/opencontainers/image-spec/specs-go/v1"
plugin/backend_linux.go:                                        specs "github.com/opencontainers/image-spec/specs-go/v1"
```

### PR DESCRIPTION
**Pull request by Jeyanthinath**
fix : #45194 

**- What I did**

 changed the aliases to a common alias `ocispec`

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! We can probably also update the linter to validate this; similar to https://github.com/moby/moby/commit/f66374f6a87f8c2d67932d6b0249bae358b70f93

**Review by thaJeztah — APPROVED** [review]
LGTM (assuming CI is green)

left one suggestion above (but I'm fine with doing so in a follow-up) 👍

**Review by thaJeztah — APPROVED** [review]
still LGTM, thanks for updating!

**Review by neersighted — APPROVED** [review]

**Review by cpuguy83 — COMMENTED** [review]
Since we're making the change here, would it make sense to call this `imagespec` instead of `ocispec` given there is also runtime-spec?

**Comment by Jeyanthinath** [comment]
@cpuguy83, in the issue `ocispec` was suggested, so I made that change. I also feel `ocispec` appropriate, but open to suggestions.

**Comment by thaJeztah** [comment]
No (very) strong opinion on the name; I think I picked this one as it was closest to what was used (including in vendored repositories). My main goal with that ticket was to make sure we at least use the same name everywhere, to reduce cognitive load, and to prevent accidentally use the wrong import (which in some cases can happen if types with the same name are in other "similar" packages).

For runtime-spec, it looks like we converged to just `specs`;

Screenshot 2023-05-10 at 01 20 45

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
