### PR TITLE
Add testRequires NotSystemdCgroups

### PR DESCRIPTION
**Pull request by jessfraz**
skip the stats dind test for now, not closing the issue because its still an issue we should fix but this will allow @vbatts to help us with an rpm :angel:

### CODE REVIEW

**Comment by jfrazelle** [comment]
but for reference its https://github.com/docker/docker/issues/10690 ping @tiborvass @LK4D4

**Comment by LK4D4** [comment]
Can I try to fix it today? I'll tell you if I fail tomorrow.

**Comment by jfrazelle** [comment]
yes! im +1 for fixing first :D

On Mon, Mar 30, 2015 at 1:32 PM, Alexander Morozov <notifications@github.com

**Comment by vbatts** [comment]
+1 for fixing first. I've got patch to skip this test, so i can still function normal locally. But have not sent a PR for it. and every time i began to investigate a fix, i get pre-occupied :-\

**Comment by jfrazelle** [comment]
closing again lol

**Comment by tiborvass** [comment]
@jfrazelle please add more info on why you're closing it :P I want you to reopen! :)

**Comment by jfrazelle** [comment]
no but we fixed the real bug :) master works on my systemd host now :D

**Pull request closed without merging**
