### PR TITLE
Bugfix: the actions when pull from notary should not contains `push`

### PR DESCRIPTION
**Pull request by HuKeping**
Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by endophage** [comment]
LGTM!

I thought this had been done quite a long time ago, but it's possible the change was made on the notary CLI side.

@thaJeztah This is just good solid cleanup. We should only be requesting the permissions actually required for the operation.

**Comment by HuKeping** [comment]
```
02:59:31 PASS: docker_cli_daemon_test.go:434: DockerSuite.TestDaemonStartWithDaemonCommand	25.712s
04:16:59 Build timed out (after 90 minutes). Marking the build as failed.
04:16:59 Build timed out (after 90 minutes). Marking the build as aborted.
```

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, thanks @HuKeping!

**Pull request merged**
