### PR TITLE
Remove Mount/Unmount from Builder interface.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by calavera** [comment]
Nice, good to know that we didn't really need those calls :grin: 

LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
Unfortunately none of the Windows tests ran because of an unrelated "No connection could be made because the target machine actively refused it." issue.

**Comment by calavera** [comment]
Windows is just being silly. Merging.

**Pull request merged**
