### PR TITLE
Makes Debian/Ubuntu package scripts use invoke-rc.d/service as appropriate

### PR DESCRIPTION
**Pull request by ncraike**
I'm not sure how to test this.

This is my first contribution to Docker, and I'm not sure how to run the full docker package build scripts to build a new .deb package and test if this works.

I'm pretty sure this completes #3924, but please test and code review!

Refs #3924

Signed-off-by: Nathan Craike ncraike@gmail.com

### CODE REVIEW

**Comment by ncraike** [comment]
(Written at the Brisbane docker.party!)

**Comment by icecrime** [comment]
Thanks @ncraike! Ping @jfrazelle and @tianon that can help you with that :-)

**Comment by tianon** [comment]
The "easiest" way to build this would be something like this:
```console
$ make shell
# ./hack/make.sh binary ubuntu
```
This will put the `.deb` in `bundles/VERSION/ubuntu/` for consumption and testing.

As to the fix, all the platforms I've tested on actually have the `service` command, so I'm not sure whether this will actually fix anything.

It's probably worth noting #12111 here, which is something I've been working on to build our `.deb` files properly with `debhelper` so that this logic is baked in correctly by `debhelper` itself instead of us trying to do ad-hoc platform detection right in our `.deb` scripts.

**Comment by jfrazelle** [comment]
closing as we have to maintian this working across distros and the fix is purely cosmetic sorry but we can redo the cosmetic bits when we fully implement #12111

**Comment by ncraike** [comment]
Fair enough, @jfrazelle. There were some bugs in my fix anyway which I didn't get on top of. Thanks for the advice @tianon and @jfrazelle both.

**Pull request closed without merging**
