### PR TITLE
Improve concurrency for func lookupDevice in devmapper

### PR DESCRIPTION
**Pull request by ghost**
The sync.Mutex in struct DeviceSet is too coarse-grained to protect DeviceSet.metaData.Devices, especially  for lookupDevice/lookupDeviceWithLock. A finer-grained RWMutex is added in struct metaData, only protect metaData.Devices, mainly optimizing lookup(reading) DeviceSet.metaData.Devices.

Signed-off-by: Peng Shen <shenpeng11@huawei.com>

### CODE REVIEW

**Comment by s0-huawei** [comment]
@GordonTheTurtle
As a new comer, sorry for the mistakes, I'll update it later. Thank you.

**Comment by rhvgoyal** [comment]
Adding another lock brings in lot of headache and defining proper lock ordering between locks. We already have two locks right now. Global devices lock and per device lock. So before you jump into adding more locks, let us first quantify what are the gains. Which operations are gaining and does it really matter.

**Comment by cpuguy83** [comment]
I agree with @rhvgoyal 
If we're at the point of adding another lock, we should consider refactoring instead.

**Comment by s0-huawei** [comment]
@rhvgoyal @cpuguy83 I agree with you too, lookupDevice optimization helps more or less to solve the problem I met, indeed it's not good from the whole point of view, but maybe a step forward to push the community to get rid of the bottlenecks caused by the coarse-grained locks.  
    The original problem is k8s creates containers concurrently, and some cost too long (more than 2 minutes). First, I found the bottleneck is ls.mountL.Lock() in func (ls *layerStore) CreateRWLayer, to a specific layerStore, there are 19 create-container queries to obtain ls.mountL in the duration. The time holding for ls.mountL for each container will add to another. Next, I found ls.initMount  in CreateRWLayer costs too much time. Ultimately, identifying  lookupDeviceWithLock in func (devices *DeviceSet) AddDevice, func (devices *DeviceSet) MountDevice and func (devices *DeviceSet) UnmountDevice wait too long, those functions are invoked by func (ls *layerStore) initMount.
    At first, I would like to change ls.mountL to only protect accessing ls.mounts, don't lock the subsequent actions for ls.driver, but will suffer inconsistency. So I choose to modify lookupDevice.

**Comment by cpuguy83** [comment]
We can't make the code worse so that someone else will step in and clean it up.
If you'd like to make this change then we need to do it cleanly.

**Comment by thaJeztah** [comment]
Based on the discussion here, I think we should close this PR, as it's not the right approach. But let us know if you want to work on a new PR to do a refactor.

**Comment by s0-huawei** [comment]
@thaJeztah Thank you. If there is a chance to take part in refactoring,  why not?

**Pull request closed without merging**
