### PR TITLE
Remove myself from codeowners 😅

### PR DESCRIPTION
**Pull request by vdemeester**
Still maintaining but most likely shouldn't be see as code owner :sweat_smile: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by olljanat** [comment]
Interesting. Two new failing issues which cannot caused by this.

Janky:
```
10:02:33 FAIL: docker_cli_plugins_test.go:474: DockerSuite.TestPluginMetricsCollector
10:02:33 
10:02:33 [d2b8817f52f54] waiting for daemon to start
10:02:33 [d2b8817f52f54] daemon started
10:02:33 
10:02:33 docker_cli_plugins_test.go:482:
10:02:33     c.Assert(r.Error, checker.IsNil, check.Commentf(r.Combined()))
10:02:33 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0009e73e0), Stderr:[]uint8(nil)} ("exit status 1")
10:02:33 ... Error response from daemon: error pulling image configuration: unknown blob
10:02:33 
10:02:33 
10:02:33 [d2b8817f52f54] exiting daemon
```

Experimental:
```
10:05:38 FAIL: docker_cli_daemon_test.go:3006: DockerDaemonSuite.TestFailedPluginRemove
10:05:38 
10:05:38 [de502d7f8cafd] waiting for daemon to start
10:05:38 [de502d7f8cafd] daemon started
10:05:38 
10:05:38 docker_cli_daemon_test.go:3022:
10:05:38     c.Assert(err, checker.IsNil)
10:05:38 ... value *errors.withStack = Error response from daemon: unauthorized: authentication required ("Error response from daemon: unauthorized: authentication required")
```

Let's try again...

**Comment by olljanat** [comment]
Derek add label: rebuild/experimental

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
let me move this to "merge" so that CI can complete (as @olljanat was debugging 🤗)

**Pull request merged**
