### PR TITLE
Cleanup: change test func name

### LINKED ISSUE #13413: nit: capitalization of test
this drives me nuts some are ADD and some are Add, choose one and make consistent through test names

```
DockerSuite.TestBuildADDCurrentDirWithCache                 3.02
DockerSuite.TestBuildADDCurrentDirWithoutCache              1.12
DockerSuite.TestBuildADDFileNotFound                        0.23
DockerSuite.TestBuildADDLocalAndRemoteFilesWithCache        1.13
DockerSuite.TestBuildADDLocalAndRemoteFilesWithoutCache     1.57
DockerSuite.TestBuildADDLocalFileWithCache                  1.58
DockerSuite.TestBuildADDLocalFileWithoutCache               3.26
DockerSuite.TestBuildADDMultipleLocalFileWithCache          1.85
DockerSuite.TestBuildADDRemoteFileMTime                     3.33
DockerSuite.TestBuildADDRemoteFileWithCache                 0.55
DockerSuite.TestBuildADDRemoteFileWithoutCache              1.06
DockerSuite.TestBuildAddBadLinks                            0.68
DockerSuite.TestBuildAddBadLinksVolume                      1.58
DockerSuite.TestBuildAddDirContentToExistingDir             5.30
DockerSuite.TestBuildAddDirContentToRoot                    4.58
DockerSuite.TestBuildAddEtcToRoot                           0.49
DockerSuite.TestBuildAddFileWithWhitespace                  7.76
DockerSuite.TestBuildAddMultipleFilesToFile                 0.17
DockerSuite.TestBuildAddMultipleFilesToFileWild             0.18
DockerSuite.TestBuildAddMultipleFilesToFileWithWhitespace   0.18
DockerSuite.TestBuildAddPreservesFilesSpecialBits           2.55
DockerSuite.TestBuildAddScript                              2.42
DockerSuite.TestBuildAddSingleFileToExistDir                5.82
DockerSuite.TestBuildAddSingleFileToNonExistingDir          4.93
DockerSuite.TestBuildAddSingleFileToRoot                    4.48
DockerSuite.TestBuildAddSingleFileToWorkdir                 0.79
DockerSuite.TestBuildAddTar                                 6.29
DockerSuite.TestBuildAddTarXz                               1.10
DockerSuite.TestBuildAddTarXzGz                             1.18
DockerSuite.TestBuildAddToSymlinkDest                       2.74
DockerSuite.TestBuildAddWholeDirToRoot                      5.66
```

### PR DESCRIPTION
**Pull request by WeiZhang555**
resolve  #13413

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM and thanks a lot :)

**Comment by WeiZhang555** [comment]
@runcom Glad to help :)

**Comment by runcom** [comment]
I've updated your first comment to use a correct form to autoclose the related issue, see more here for the next time https://help.github.com/articles/closing-issues-via-commit-messages/ :)

**Comment by thaJeztah** [comment]
Thanks, LGTM! Think this should be safe for me to merge ;)

And a screenshot to see the nice improvement here;


image

**Comment by WeiZhang555** [comment]
@thaJeztah Thank you!
@runcom got a new technique now, I will add "resolve" keyword next time, thank you! ;)

**Comment by runcom** [comment]
@WeiZhang555 you're welcome and thx for this!

**Pull request merged**
