### PR TITLE
updated fedora yum to dnf package manager

### PR DESCRIPTION
**Pull request by tbonza**
Fedora has a new package manager (dnf instead of yum). "The DNF package and its dependencies are in f18 repositories now, in a testable state."; see [fedora wiki on dnf](https://fedoraproject.org/wiki/Features/DNF). A more complete overview of dnf is available at [readthedocs](http://dnf.readthedocs.org/en/latest/index.html). 

This pull request is a proposal to upgrade the Fedora documentation to reflect the new package manager.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tbonza can you squash your commits, and sign-off, otherwise we won't be able to review or accept your changes

**Comment by phemmer** [comment]
`dnf` is not installed by default in Fedora 21 (which Docker supports. see line 14 of the file).
`yum` works in both. Thus the instructions either need to mention this, or they should stay referencing `yum` (as it is present in both) until docker drops support for Fedora 21.

**Comment by runcom** [comment]
I'd stick with `yum` and mention `dnf` can be used on fedora 22+ in a note at the start

**Comment by tbonza** [comment]
@thaJeztah  my commit should now be consistent with the contributions policy

**Comment by thaJeztah** [comment]
@tbonza thank you. I agree with the other comments; dnf is not installed by default on Fedora 21, so we should be careful here.

However, [Fedora 21 is EOL'd on December 1st](https://fedoraproject.org/wiki/End_of_life?rd=LifeCycle/EOL) so I just created a PR to drop support for it in Docker 1.10: https://github.com/docker/docker/pull/18794

I'll await if that is accepted, and if so, we can merge this PR for inclusion in the Docker 1.10 docs.

LGTM (pending approval of https://github.com/docker/docker/pull/18794)

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/pull/18794 was just merged

ping @moxiegirl for the merge :+1:

**Comment by moxiegirl** [comment]
@tbonza Very nice! Thank you. LGTM

**Pull request merged**
