### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by innovimax**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by olljanat** [comment]
@innovimax plz check message above

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Z failed to #38460

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
z failure is unrelated. Let's merge...

**Comment by yongtang** [comment]
@innovimax Congratulations to your first PR 🎉 !

**Pull request merged**
