### PR TITLE
add google group subscribtion method using only emails

### PR DESCRIPTION
**Pull request by ghost**
- users don't have to create an google account for using the google groups. They
  can simply email to e.g. "docker-user+subscribe@googlegroups.com" to
  subscribe.
- since this behavior is not mentioned on the google group website, i think its
  a good idea to explain this method here.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice! Didn't know that actually :relaxed: 

LGTM

**Comment by toogley** [comment]
:) regarding the failed tests: can i make them pass somehow? at least the first two seem to fail because my commits had missed the sign. Therefore maybe a rerun of the tests could partly solve them.

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by thaJeztah** [comment]
Oh, I just noticed you opened this PR against the docs branch; can you open this against master? The docs branch is only used for publishing docs, and we only cherry-pick changes into that for updating the online documentation (docs.docker.com), which these documents aren't part of.

Unfortunately, GitHub won't let you change an existing PR to a different branch, so you'll need to open a new one :cry:

**Pull request closed without merging**
