### PR TITLE
Fix a bit typos

### PR DESCRIPTION
**Pull request by yuexiao-wang**
**- What I did**
Fix a bit typos

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Please do no touch files under the vendor directory.

Also, I think "eg" is widely accepted
http://dict.cn/eg

**Comment by yuexiao-wang** [comment]
@AkihiroSuda
Thanks for review.
I agree that "eg" or "EG" is widely accepted,  However,  there are many "e.g." used in document and comment which is popular. So I suggest that use "e.g." instead of "eg"

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Pull request merged**
