### PR TITLE
Added two new adjectives and four new names to names-generator.go

### PR DESCRIPTION
**Pull request by Yadnyawalkya**
Signed-off-by: Yadnyawalkya Tale <yadnyawalkyatale@gmail.com>

**- What I did**
- Added cool, crazy, charming, magical and sweet as a adjectives (Aug 18)
- Added four men scientists to the list - faraday, maxwell, sutherland, and moore (Aug 21)
- Added four women scientists to the list - cannon, moser and rhodes (Aug 28)

**- A picture of a cute animal (not mandatory but encouraged)**
Bonus++

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
"Please, for any amazing man that you add to the list, consider adding an equally amazing woman to it, and vice versa."

**Comment by Yadnyawalkya** [comment]
Agreed! sure @anusha-ragunathan. Will search and add interesting names.

**Review by boaz0 — APPROVED** [review]
LGTM :+1:

**Comment by anusha-ragunathan** [comment]
Thanks for the update. The idea is to have equal participation of both genders. So for the 4 men that have been added, please add 4 women engineers/scientists/physicists/etc (not 2).

**Comment by Yadnyawalkya** [comment]
@anusha-ragunathan, I thought earlier you just said it for fun :grinning:  
Updated this time, 4 Men and 4 Women !

**Comment by anusha-ragunathan** [comment]
LGTM (if CI is green)

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
