### PR TITLE
Fix duplicated ports allocation with restarted swarm

### LINKED ISSUE #29247: Swarm service auto allocate ports maybe will duplicate with others
Hi there,

I found that swarm service auto allocate ports maybe will duplicate with others.

How to reproduce:

```
root@dce2-dev-5:~# docker swarm init --advertise-addr 192.168.2.143 --force-new-cluster
Swarm initialized: current node (92n09si1jwqbhbb88zcodk7iv) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-5efgz6ef993x3leyxl8fv44kfm8otp95am7y61qzuywsjn18rs-87mxbncuc953poema8fnxcf88 \
    192.168.2.143:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

root@dce2-dev-5:~# docker service create -p 80 -p 443 daocloud.io/nginx && systemctl restart docker # Restart Docker Daemon immediately
e3o7ywttd1q1qtp63apeiufvf
root@dce2-dev-5:~# docker service inspect e3o7ywttd1q1qtp63apeiufvf | grep Port
                "Ports": [
                        "TargetPort": 80
                        "TargetPort": 443
                "Ports": [
                        "TargetPort": 80
                        "TargetPort": 443
            "Ports": [
                    "TargetPort": 80,
                    "PublishedPort": 30000
                    "TargetPort": 443,
                    "PublishedPort": 30001
# So service `e3o7ywttd1q1qtp63apeiufvf` has published 30000 and 30001
root@dce2-dev-5:~# docker service create -p 80 -p 443 daocloud.io/nginx 
1pzk991znh6buecgu7jf16dh8
root@dce2-dev-5:~# docker service inspect 1pzk991znh6buecgu7jf16dh8 | grep Port
                "Ports": [
                        "TargetPort": 80
                        "TargetPort": 443
                "Ports": [
                        "TargetPort": 80
                        "TargetPort": 443
            "Ports": [
                    "TargetPort": 80,
                    "PublishedPort": 30000
                    "TargetPort": 443,
                    "PublishedPort": 30001
# Service `1pzk991znh6buecgu7jf16dh8` still published 30000 and 30001
```

Docker Info

```
root@dce2-dev-5:~# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: active
 NodeID: 92n09si1jwqbhbb88zcodk7iv
 Is Manager: true
 ClusterID: 6iqzr3ueonc09aoi3hlbin51a
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.143
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.4 MiB
Name: dce2-dev-5
ID: QVXX:LATH:VRMQ:4CG2:EHPW:5TPJ:56EG:SBZB:6MCJ:4C2A:D2EV:6HUE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
```

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**
This fix fixes the issue raised in #29247 where duplicated ports (`PublishedPort`) is being allocated with restarted swarm nodes.

The reason for the issue was that `isPortsAllocated` relies on portSpace which does not capture the ports in restored services when swarm is restarted.

**- How I did it**

See SwarmKit PR: https://github.com/docker/swarmkit/pull/1802

Most of the fix is done in SwarmKit PR which adds a flag in `isPortsAllocated`. In case the allocator is still in initialization stage, dynamically allocated ports (`PublishedPort`) will always be reallocated.

This fix (docker PR) adds an integration test to prevent regression in the future.

**- How to verify it**

An integration test has been added.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

christmas-animals-004

This fix fixes #29247.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by allencloud** [comment]
Need a rebase @yongtang 
Hope this PR could move on soon.

**Comment by yongtang** [comment]
Thanks @allencloud. PR has been rebased.

**Comment by yongtang** [comment]
Also /cc @aboch. Please take a look.

**Comment by cpuguy83** [comment]
@yongtang Looks like this can be taking care of purely in swarmkit?

**Comment by yongtang** [comment]
@cpuguy83 Yes if docker/swarmkit#1802 is merged I think we are good. Let me close this PR.

**Pull request closed without merging**
