### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by schmunk42**
**\- What I did**

fixed grammar

**\- How I did it**

**\- How to verify it**

Please let it be reviewed by a native English speaker :)

**\- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
@schmunk42 it looks good but please sign your commit.
`git commit -s --amend --no-edit`
and then repush.

**Comment by schmunk42** [comment]
Is there no way to do this via the GitHub web-interface? It's a bit annoying that I need to clone 100s of MBs for changing 2 characters - and even writing this here. But hey :)

Clone is downloading at 100 KB/sec :( ..... stay tuned.

**Comment by duglin** [comment]
@schmunk42 I'm confused - how did you push your change w/o cloning in the first place?

**Comment by schmunk42** [comment]
@duglin I just clicked the edit button in GitHub's Web-UI, this forks the repo in the background and let's you instantly create a PR from your changes.

You don't need to work locally, that is nice workflow for a little typos in docs like above.

**Comment by schmunk42** [comment]
bildschirmfoto 2016-09-14 um 12 44 41

**Comment by thaJeztah** [comment]
> Is there no way to do this via the GitHub web-interface? It's a bit annoying that I need to clone 100s of MBs for changing 2 characters - and even writing this here. But hey :)

Unfortunately, no, I think there's a feature request somewhere, and a "rant" from Linus Torvalds on this subject https://github.com/torvalds/linux/pull/17#issuecomment-5654674

We know it's a PITA, so **thanks** for fixing it 👍 

LGTM

**Pull request merged**
