### PR TITLE
kr/pty: vendor upstream 5cf931ef8f

### PR DESCRIPTION
**Pull request by hqhq**
Don't know if it's proper to send this PR by me, just this vendor hasn't been updated for half a year, and it has ARM64 support now, hope we can have this in 1.7.0. @unclejack 

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by unclejack** [comment]
@hqhq Thanks for the ping and for the PR.

ping @tianon

LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@tianon can you take a look plz

**Comment by tianon** [comment]
LGTM

**Pull request merged**
