### PR TITLE
Add Neil Armstrong to names generator

### PR DESCRIPTION
**Pull request by jfleach**
**- What I did**

Added Neil Armstrong to the names generator

**- How I did it**

Created pull request

**- How to verify it**

View source code

**- Description for the changelog**

Added Neil Armstrong to the names generator

### CODE REVIEW

**Comment by jfleach** [comment]
@thaJeztah : Can I get this one merged?  Thanks

**Comment by thaJeztah** [comment]
Sorry, look like this one dropped off  my list;

I see that the commit message is missing a DCO sign-off, which makes CI fail; https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

Could you also add a non-male person to the list? https://github.com/moby/moby/blob/06ca1606e1a09c36bd12ed503b4c99d8a17ca230/pkg/namesgenerator/names-generator.go#L120-L122

When updating, please amend the existing commit (single commit for the pull request should be ok); let me know if you need help making those changes

**Review by thaJeztah — CHANGES_REQUESTED** [review]
(see my comment above)

**Comment by tianon** [comment]
Thank you so much for taking the time to make this contribution!  We're very sorry for how long it has taken us to come to a decision on it, but as of https://github.com/moby/moby/pull/43210 the `namesgenerator` package is now officially "frozen" against new additions.  There is some explanation there as to why it is frozen (and why it has taken us so long to come to a decision on PRs like yours 🙈), but https://github.com/moby/moby/pull/43210#issuecomment-1029934277 is especially good for a longer explanation. :heart:

**Pull request closed without merging**
