### PR TITLE
Update bash completion for 1.7.0

### PR DESCRIPTION
**Pull request by albers**
Added the new features mentioned in the 1.7.0 release notes from #13528:
- `docker`: `--userland-proxy`, `--default-gateway`, `--default-gateway-v6`
- `docker run`: `--uts`, `--blkio-weight`
- `docker build`: `--cgroup-parent`, `--cpu-period`, `--cpuset-mems`

Also fixed some options that were erroneously implemented as boolean flags and applied some minor tweaks.

ping @jfrazelle @tianon 
Please add this to the upcoming release.

### CODE REVIEW

**Comment by jfrazelle** [comment]
awesome thanks assigned myself so I remeber to cherry pick, lGTM

**Comment by tianon** [comment]
Nice, LGTM! :+1:

**Comment by albers** [comment]
Thanks!

**Comment by jfrazelle** [comment]
no, thank you!

**Comment by thaJeztah** [comment]
@albers fully agree with Jess here, thank you so much for keeping these up-to-date!

**Pull request merged**
