### PR TITLE
Add Kuryr Network Plugin to the docs

### PR DESCRIPTION
**Pull request by mbanikazemi**
Signed-off-by: Mohammad Banikazemi mb@us.ibm.com

### CODE REVIEW

**Comment by MHBauer** [comment]
Looks good to me.

I'm wondering if we ought to separate the plugins into subsections (i.e. networking, volume driver, etc.)

**Comment by estesp** [comment]
nice, thanks @mbanikazemi

**Comment by calavera** [comment]
LGTM

**Comment by mavenugo** [comment]
LGTM. thanks @mbanikazemi

**Comment by vdemeester** [comment]
LGTM 🐱
@MHBauer I agree, at some point we might want to separate plugins by types but that's not the scope of this PR :wink:

**Pull request merged**
