### PR TITLE
Create system  subcommand

### PR DESCRIPTION
**Pull request by dnephin**
Adds a new `docker system` for `events`, and `info`.

`df`and `purge` will be added in #26108

### CODE REVIEW

**Comment by dnephin** [comment]
cc @mlaventure

**Comment by mlaventure** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM :+1:

**Comment by mlaventure** [comment]
`TestHealth` is a known failure atm.

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by vdemeester** [comment]
The documentation will be updated in a follow-up PR (just like the cli restructuring 👼)

**Pull request merged**
