### PR TITLE
Revert "Jenkinsfile: temporarily pin windows image to 10.0.17763.973"

### PR DESCRIPTION
**Pull request by thaJeztah**
This reverts commit fa2417984be775b4076db681d233f565539207db https://github.com/moby/moby/pull/40506

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by StefanScherer** [comment]
Hm, building the Windows container image now works, but the build fails later on. 🤔

**Comment by thaJeztah** [comment]
Interesting, haven't seen that error before. Let me kick it again, to see if it was indeed just a flake

**Comment by thaJeztah** [comment]
Failing again with `Failed to compile event message resources`, so looks like it's an actual issue / regression in Windows 😞

**Comment by StefanScherer** [comment]
Weird, do you encounter that problem in other PR's today? 
I ask because the Azure agents are now updated to 10.0.17763.1039, but our temporary fix still uses the older 10.0.17763.973 base image.
If it also fails in other PR's using the older image I would rollback to the previous VM image.

**Comment by thaJeztah** [comment]
Good one; yes, looks like this PR also fails; https://github.com/moby/moby/pull/40510 https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-40510/3/pipeline

**Comment by StefanScherer** [comment]
Alright, I've rolled back to the previous VM images.

**Comment by thaJeztah** [comment]
Added "cherry-pick" label, because I'm backporting the temporary fix in https://github.com/moby/moby/pull/40551

**Comment by StefanScherer** [comment]
@thaJeztah I've triggered another RS5 build, now with the latest VM image (10.0.17763.1039) again and it uses also the latest patched base image (10.0.17763.1040). This build is 💚 again.
So, it's time to remove the workaround.

**Comment by thaJeztah** [comment]
Thanks! I'll merge this one (ugh; forgot that updating a PR title triggers CI)

Build was green, so I don't think we'll have to wait for CI to do another run 😅

**Pull request merged**
