### PR TITLE
Do not probe plugins for graph init unless `-s`

### PR DESCRIPTION
**Pull request by cpuguy83**
When `-s` is not specified, there is no need to ask if there is a plugin
with the specified name.

This speeds up unit tests dramatically since they don't need to wait the
timeout period for each call to `graphdriver.New`.

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐢

**Comment by estesp** [comment]
makes a lot of sense, but any reason we should just boolean `GetDriver` with a "`builtinOnly`"-like flag rather than copy most of the same function?

**Comment by cpuguy83** [comment]
Because booleans are horrid.

**Comment by estesp** [comment]
ha, ok :) well, then maybe to not have confusing debug sessions in the future at least the log message on failure can be "true" to the name of the function at least?

**Comment by cpuguy83** [comment]
As in `failed to get built-in GraphDriver`?

**Comment by estesp** [comment]
@cpuguy83 correct--right now both functions have the same exact failure log, which would make it potentially hard to determine the codepath by inspection.

**Comment by cpuguy83** [comment]
@estesp Makes sense. Updated.

**Comment by estesp** [comment]
LGTM

**Pull request merged**
