### PR TITLE
Split docker_cli_build_test.go into several pieces

### PR DESCRIPTION
**Pull request by vdemeester**
This feels silly to make this PR. **Feel free to close this one as it does nothing more than splitting a big file into several** 🐙. 

6000 lines of code for a file (`docker_cli_build_test.go`) feels a little bit too much (and my editor is not that happy about it but _meh_). So I tried to split them a little between smart and naive :sweat_smile:. This does not change any piece of test (just moving them around and updating the imports).

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by thaJeztah** [comment]
I don't think it's silly. Smaller files, less rebases, so :+1:

**Comment by tiborvass** [comment]
I do wonder though if there are tests that could go in multiple categories... if so, shouldn't those stay in some generic build_test.go ?

**Comment by vdemeester** [comment]
@tiborvass There is still a `docker_cli_build_test.go` with *alone* tests and tests I didn't really know where to put. It's just that github doesn't show it because of the size of the diff on this file.

**Comment by jfrazelle** [comment]
if you rebase we can get this in fast to avoid another, just ping me :)

**Comment by vdemeester** [comment]
@jfrazelle discussed with @tiborvass on IRC, maybe it would be better / simpler to have folders instead (and why not even removing the `docker_…` prefix :stuck_out_tongue_closed_eyes:).

I'll re-start to work seriously on #17129 so I might do this in the PR(s) that will follow.. 
@tiborvass @jfrazelle I probably should close this one for now, wdyt ? :wink:

**Comment by jfrazelle** [comment]
sounds good to me!

**Pull request closed without merging**
