### PR TITLE
Remove myself (lowenna aka jhowardmsft) from maintainers

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <github@lowenna.com>

I think it's very doubtful at this point that I'm going to be able to positively contribute anything to the project now that I'm semi-retired, no longer working at Microsoft, have the tech to be able to run this stuff on Windows, nor have any "inside" knowledge some 18-months on. So time to bow out gracefully and watch from afar. I still use it daily, just on Linux 😂. So I'm giving up my maintainer role. 

Just hope I got my PR correct with the CR/LF vs LF. It's been waaaaay too long since I did anything cross-platform. It will make me laugh at least if I got it wrong, my machine is just defaults 🤣

@akihirosuda @anusha @coolljt0725 @cpuguy83 @crosbymichael @estesp @johnstep @justincormack @kolyshkin @mhbauer @runcom @stevvooe @thajeztah @tianon @tibor @tonistiigi @unclejack @vdemeester @vieux @yongtang

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by lowenna** [comment]
@thecloudtaylor @jstarks FYI 😎

**Review by estesp — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
:cry: LGTM

image

There's an `Org.Alumni` section further down that IMO we should write up something nice for. :smile:

> John Howard was instrumental in successfully bringing Docker to the Microsoft Windows platform.  His experience (and patience with all us cheeky Linux folk) cannot be overstated, and his impact will continue to be enjoyed by many Windows users for years to come.

**Comment by thaJeztah** [comment]
@lowenna would you like to be included in the "alumni" list? (I can write up something nice) https://github.com/moby/moby/blob/02bc2769fb12b617e572b166b4851fa3f908580c/MAINTAINERS#L74-L80

**Comment by lowenna** [comment]
> would you like to be included in the "alumni" list? (I can write up something nice)

@thaJeztah Please do 😊 It was/is truly a difficult realisation (yes, s, not z!), but realistic to remove myself. I genuinely thoroughly enjoyed getting this project running on Windows. There were so many challenges in getting there, both internally and externally!!! Hope you are well 😁

**Comment by thaJeztah** [comment]
> Please do 😊 

More than happy to write up something! I'll spend some time this week to open a PR 🤗 

>  (yes, s, not z!)

Hehe, my machine is on "true" English 🇬🇧 and I have to "correct" those all the time 😉

> but realistic to remove myself. I genuinely thoroughly enjoyed getting this project running on Windows. There were so many challenges in getting there, both internally and externally!!!

And thank you _soo_ much for every bit of that! I enjoyed every moment of the road to getting there (including the sometimes heated discussion on "Windows is not Linux!")

> Hope you are well 😁

I am! And if I find myself in your neck of the woods once this pandemic is behind us, I'll let you know! ☕ 🍻 🍷

**Review by vieux — APPROVED** [review]
LGTM

**Comment by thecloudtaylor** [comment]
image

**Review by kolyshkin — APPROVED** [review]
LGTM, and thanks for all the fish!

**Review by vdemeester — APPROVED** [review]
LGTM
@thaJeztah we need something in alumni though 👼🏼

**Review by AkihiroSuda — APPROVED** [review]
Thank you for your all work!

**Comment by coolljt0725** [comment]
LGTM

**Comment by thaJeztah** [comment]
Let's get this one in 🤗 

Follow-up is in https://github.com/moby/moby/pull/42326

**Pull request merged**
