### PR TITLE
[1.11.2] Use clang 3.5 over 3.8

### PR DESCRIPTION
**Pull request by thaJeztah**
Cherry-pick of f8dacaf0ab7ca533cc3a33c6d06f7dca3e347955 (https://github.com/docker/docker/pull/23145) for 1.11.2

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @mlaventure @justincormack

**Comment by justincormack** [comment]
LGTM

**Comment by mlaventure** [comment]
LGTM (IANAM)

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
