### PR TITLE
Add zsh completion for new 'docker system' subcommands

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #26025

Same logic as @albers #27814 PR, splitting commits for better review session.

New df and prune subcommands will be added in a different PR.

@vincentbernat

### CODE REVIEW

**Comment by vincentbernat** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by thaJeztah — APPROVED** [review]
LGTM

@sdurrheimer would you be okay with squashing these, now that it's reviewed?

**Comment by vdemeester** [comment]
@sdurrheimer needs a rebase too 👼

**Comment by sdurrheimer** [comment]
Rebased, should I still squash those commits even if we didn't do it for `docker container` and `docker image` commands ?

**Comment by thaJeztah** [comment]
@sdurrheimer yes, I think it's ok to squash (@cpuguy83 DM'd me that he overlooked the squashing when he merged - we sometimes forget)

**Comment by sdurrheimer** [comment]
Squashed

**Comment by vdemeester** [comment]
Thanks @sdurrheimer 👼

**Pull request merged**
