### PR TITLE
fix build on OpenBSD by defining Self()

### PR DESCRIPTION
**Pull request by Mischi**
**- What I did**
While building all tools from https://github.com/ethereum/go-ethereum on OpenBSD, I got an error because Self was not defined in `reexec/command_unsupported.go`.

**- How I did it**
This PR defines the method.

**- How to verify it**
It builds now under OpenBSD. I did not do any runtime testing though.

**- Description for the changelog**

fix the build on OpenBSD.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for contributing! Can you sign off your commit (you can use the instructions that @gordontheturtle provided above) otherwise CI won't pass :sweat_smile:

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by Mischi** [comment]
Thanks!

**Pull request merged**
