### PR TITLE
validate heartbeat in discovery cluster opts

### PR DESCRIPTION
**Pull request by allencloud**
This PR did:
1. validate heartbeat and ttl in discovery cluster opts, and make sure that both two are positive;
2. add related test case in discovery_test.go

**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: allencloud allen.sun@daocloud.io

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM
ping @vdemeester

**Comment by vdemeester** [comment]
LGTM 🐸
This will need an entry in the API changes file (to say it's now validated) 👼

**Comment by cpuguy83** [comment]
Not an API field, though, is it?

**Comment by vdemeester** [comment]
@cpuguy83 my bad :sweat_smile: I didn't drink enough coffee today :joy:

**Pull request merged**
