### PR TITLE
buildkit: normalize build target and local platform

### LINKED ISSUE #795: Docker build "FROM" Fails to search local images
When building containers FROM another container image I've built locally, Docker build is failing to find the image and searching externally. A couple weeks ago, I saw this issue and found the problem was mitigated by disabling build kit (`DOCKER_BUILDKIT=0`) However, this no longer works. 

Notably, this is a paradigm I've been following for years- I've searched all over dockers documentation and can not find any relevant changes documented.

This is what I'm seeing, The `amd64/wtfbbqhax_runtime` is just an alpine image that I have locally.

```Dockerfile
bash$ cat Dockerfile
FROM amd64/wtfbbqhax_runtime:7b2d02df45e4 as runtime
RUN apk add gdb
COPY cores/ /storage/cores
ENTRYPOINT []
```


```bash
bash$ docker images | grep amd64
amd64/wtfbbqhax_runtime          latest             7b2d02df45e4   3 hours ago   89.1MB
```


```bash
bash$ docker build -t wtfbbqhax-debug .
[+] Building 1.8s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                      0.0s
 => => transferring dockerfile: 196B                                                                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                                                                           0.0s
 => ERROR [internal] load metadata for docker.io/amd64/wtfbbqhax_runtime:7b2d02df45e4                                                                                                                                                                             1.6s
------
 > [internal] load metadata for docker.io/amd64/wtfbbqhax_runtime:7b2d02df45e4:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, 
repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

### LINKED ISSUE #6009: Some images on Apple Silicon without --platform results in "failed to solve" error
When building some images based on an image that was not build with `--platform linux/arm64` results in Docker a "failed to solve" error:

```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: eu.gcr.io/gby-rapideye/golang:latest: not found
```

The issue seems to be that "Variant: v8" is added to the build that does not use the `--platform` flag. The strange thing is that printing `TARGETPLATFORM` in the Dockerfile gives the exact same output independent on setting the `--platform` flag.

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I expect images (which have linux/arm64 support) to be usable as base images on Apple M1 without setting `--platform linux/arm64`.

### Actual behavior

What actually happens is that without `--platform` the variant is set to v8 which makes builds based on the image impossible, even when setting `--platform` on the downstream builds based on the "broken" base image.

### Information

  - macOS Version:
  - Intel chip or Apple chip:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. Base an image on `golang:1.17-alpine`.
  2. Build the image (on a Apple M1) with and without `--platform linux/arm64`.
  3. Diff the result of `docker inspect <image>`.
  4. The only difference is `"Variant": "v8"` is NOT added when building with `--platform`.

### LINKED ISSUE #42893: Not finding local images that do exist, trying to pull instead
**Description**

When BuildKit is enabled, if you tag an image with `--tag` and then refer to it when building another image, Docker will not find it and instead tries to pull it from Docker Hub.

Disabling BuildKit makes the problem go away.

**Steps to reproduce the issue:**

Make these files:

Dockerfile.parent:
```
FROM rockylinux/rockylinux:8.4@sha256:8122f31fbdd5c1368c6b7d5b9ae99fec2eb5966a5c967339d71e95c4a3ab7846

RUN echo "Installing common stuff"

CMD echo "Everything is good"
```

Dockerfile.child:

```
FROM local/foo-parent

RUN echo "Installing special stuff"
```

The run these commands:

```
docker build -f Dockerfile.parent -t local/foo-parent .
docker build -f Dockerfile.child -t local/foo-child .
```

**Describe the results you received:**

On building the parent image, the last line says:
```
 => => naming to docker.io/local/foo-parent                                                     0.0s
```

On building the child image, it fails to find the local image and instead tries to pull from Docker Hub:

```
 => ERROR [internal] load metadata for docker.io/local/foo-parent:latest                        2.9s
```

**Describe the results you expected:**

The tag I specified already had a `/` in it, so Docker shouldn't have automatically prefixed it with `docker.io/`. I guess that's at least part of the problem?

However, `docker inspect` still finds the image just fine by either name, so I'm not sure why building the child image fails to find it.

```
jeff@tank docker-local-image-woes % docker inspect docker.io/local/foo-parent:latest
[
    {
        "Id": "sha256:358eed8be7a681d6b130631dab99dfe0b46635116be03d1691dfc8a04c0301a3",
        "RepoTags": [
            "local/foo-parent:latest"
        ],
```

```
jeff@tank docker-local-image-woes % docker inspect local/foo-parent                 
[
    {
        "Id": "sha256:358eed8be7a681d6b130631dab99dfe0b46635116be03d1691dfc8a04c0301a3",
        "RepoTags": [
            "local/foo-parent:latest"
        ],
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm running Docker Desktop on an M1 MacBook.

**Output of `docker version`:**

```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 2.922GiB
 Name: docker-desktop
 ID: GJTR:EIL2:CYN3:JRV6:5JXM:VS3U:HRAU:2VA6:WUBG:MDN7:VXF6:24AO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical MacBook with Apple Silicon (M1), default settings, relatively fresh install of everything including Docker. (This is my first time trying to get an existing project working on the new Macs.)

This is all pure ARM -- no x86_64 virtualisation or anything complicating it as far as I can tell:

```
jeff@tank docker-local-image-woes % docker inspect rockylinux/rockylinux:8.4@sha256:8122f31fbdd5c1368c6b7d5b9ae99fec2eb5966a5c967339d71e95c4a3ab7846 | grep Architecture
        "Architecture": "arm64",
jeff@tank docker-local-image-woes % docker inspect local/foo-parent | grep Architecture
        "Architecture": "arm64",
```

### PR DESCRIPTION
**Pull request by crazy-max**
Fixes #42893
Fixes docker/buildx#795
Fixes docker/for-mac#6009

**- What I did**
When resolving a local reference to build an image with BuildKit, we need to normalize the two platforms (reference and target platform) before matching them otherwise it would fallback to remote and fail with:

```
[+] Building 1.9s (3/3) FINISHED                                                                                                                                                                      
 => [internal] load build definition from Dockerfile.child                                                                                                                                       0.1s
 => => transferring dockerfile: 102B                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                0.1s
 => => transferring context: 2B                                                                                                                                                                  0.0s
 => ERROR [internal] load metadata for docker.io/local/foo-parent:latest                                                                                                                         1.3s
------
 > [internal] load metadata for docker.io/local/foo-parent:latest:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

If we check daemon logs we have:

```
Requested build platform linux/arm64 does not match local image platform linux/arm64/v8, checking remote
```

**- How I did it**
Normalize local and target platform before matching them.

**- How to verify it**

On M1 host:

```dockerfile
# ./Dockerfile.foo
FROM alpine
RUN echo "Hello foo!"
```

```dockerfile
# ./Dockerfile.bar
FROM local/foo-parent
RUN echo "Hello bar!"
```

```shell
DOCKER_BUILDKIT=1 docker build -f Dockerfile.foo -t local/foo-parent .
DOCKER_BUILDKIT=1 docker build -f Dockerfile.bar -t local/foo-child .
```

**- A picture of a cute animal (not mandatory but encouraged)**

cc @thaJeztah @tonistiigi

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by jrajahalme** [comment]
@crazy-max This still fails if using "docker buildx build --load" on both build commands. Is that by design? If so, is there a way to use local images with buildx?
```
$ DOCKER_BUILDKIT=1 docker buildx build --load -f Dockerfile.foo -t local/foo-parent .
[+] Building 0.4s (7/7) FINISHED                                                                                                  
 => [internal] load build definition from Dockerfile.foo                                                                     0.0s
 => => transferring dockerfile: 76B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                             0.2s
 => [1/2] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300              0.0s
 => => resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300              0.0s
 => CACHED [2/2] RUN echo "Hello foo!"                                                                                       0.0s
 => exporting to oci image format                                                                                            0.1s
 => => exporting layers                                                                                                      0.0s
 => => exporting manifest sha256:415006142ad68915792e13feb34a71379d880a946666fab8f578bedd8922135e                            0.0s
 => => exporting config sha256:08a75c04c63fa34b43445d21ae662336e88d9e0c4f77907959d3e82a3738b5a5                              0.0s
 => => sending tarball                                                                                                       0.1s
 => importing to docker
$ DOCKER_BUILDKIT=1 docker buildx build --load -f Dockerfile.bar -t local/foo-child .[+] Building 1.4s (3/3) FINISHED                                                                                                  
 => [internal] load build definition from Dockerfile.bar                                                                     0.0s
 => => transferring dockerfile: 86B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s
 => ERROR [internal] load metadata for docker.io/local/foo-parent:latest                                                     1.3s
------
 > [internal] load metadata for docker.io/local/foo-parent:latest:
------
Dockerfile.bar:1
--------------------
   1 | >>> FROM local/foo-parent
   2 |     RUN echo "Hello bar!"
   3 |     
--------------------
error: failed to solve: local/foo-parent: pull access denied, repository does not exist or may require authorization: authorization status: 401: authorization failed
```

**Comment by nikophil** [comment]
Hello I still got this bug as well @crazy-max @thaJeztah 

```
$ docker --version
Docker version 20.10.14, build a224086
$ docker buildx version
github.com/docker/buildx v0.8.1-docker 5fac64c2c49dae1320f2b51f1a899ca451935554
```

```
# Dockerfile.foo
FROM alpine
RUN echo "Hello foo!"
```

```
# Dockerfile.bar
FROM foo:local
RUN echo "Hello bar!"
```

```
docker buildx build \
     --load \
     --tag foo:local \
     --file ./Dockerfile.foo \
     .

docker buildx build \
     --load \
     --file ./Dockerfile.bar \
     .
```

```
=> ERROR [internal] load metadata for docker.io/library/foo:local                                                                                                                                                                       1.1s
------
 > [internal] load metadata for docker.io/library/foo:local:
------
Dockerfile.bar:1
--------------------
   1 | >>> FROM foo:local
   2 |     RUN echo "Hello bar!"
   3 |     
--------------------
error: failed to solve: foo:local: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

```
$ docker images | grep foo
foo                                         local                                      2f58ace52d56   About a minute ago   5.57MB
```

**Comment by thaJeztah** [comment]
Note that `docker --version` shows the version information of the CLI only, not the daemon; what does `docker version` show?

Also, from your command (`docker buildx build --load`) are you using a custom builder (using the container driver, not the BuildKit embedded in the docker daemon)? What does `docker buildx ls` show?

**Comment by thaJeztah** [comment]
From the `docker buildx ls` output, it looks like you're using a container builder as the current builder. Container builders are designed to be stateless; they only preserve build-cache, but not images (i.e., they are designed to not depend on any previous state), so the second build fails, because the `foo:local` image is only available in the Docker daemon image store, and not known to the builder instance. See https://github.com/moby/buildkit/issues/2343 for a longer discussion about the design.

**Review by MoodsTop — COMMENTED** [review]
+24

**Review by MoodsTop — COMMENTED** [review]
+24

**Comment by contentfree** [comment]
This still fails with `docker build` in v24.0.6 on Mac M1. Workaround is to use `DOCKER_BUILDKIT=0` (which is deprecated, I believe) or to ensure that your parent image is built supporting the required platform.

**Pull request merged**
