### PR TITLE
rfc: move client/types from api/types…

### PR DESCRIPTION
**Pull request by vdemeester**
… and reorganize `api/types`. `api/types` will now only hold aliases
to types that comes from elsewhere (for compatibility purpose).

This uses Go type aliases (introduced in Go 1.9) to make sure we don't
break users of these packages.

This is a take at https://github.com/moby/moby/issues/36337 "Move api/types/client.go and api/types/backend to a more appropriate package" — only the `client` part.

- Moves any "options" types that are only used by the client (e.g. `ContainerLogsOptions`) to `client` package directly.
- Moves almost all types from `api/types` to their own packages (`container`, `image`, …)

This is a wip for several reasons :
- [ ] validate it makes sense
- [ ] I may have missed some and probably some naming need to be changed too
- [ ] need to figure out how to fix validation, mainly because of `swagger` cc @dnephin 
- [ ] tests need to be changed too — I didn't change them now because it might represent a big change and if we think it doesn't make sense, didn't want to do this work for nothing
- [ ] This also shows some internal usage of client types in *internal* packages (like `daemon` or `plugin`), those could be refactored too.

It is supposed to be `red` for now :sweat: (because of tests :stuck_out_tongue:), but it compiles !

:lion: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Discussing in the maintainers session; one concern is raised  by @tonistiigi - he's not against this change, but was wondering how we would prevent some code using the alias, and other code using the full path/type. Should we have some validation for that to prevent it becoming a mix/mash?

**Comment by vdemeester** [comment]
> Discussing in the maintainers session; one concern is raised by @tonistiigi - he's not against this change, but was wondering how we would prevent some code using the alias, and other code using the full path/type. Should we have some validation for that to prevent it becoming a mix/mash?

Right, so… on the project we could set-up some CI validation check (i.e. `warn` or `error` if an import is done on `"github.com/docker/docker/api/types"`), similar to the checks we do on `github.com/docker/docker/pkg` :angel:.

From outside the project there is no way to do that. The one thing we can do is to mark the aliased type in `api/types` as deprecated (a `// Deprecated` comment), that tends to get a *strikeout* font face in most editors.

**Comment by vdemeester** [comment]
@tonistiigi @cpuguy83 @thaJeztah @tiborvass @AkihiroSuda @dnephin with a validation in the CI that won't do use aliased types and a green CI (i.e. tests and internal code updated), does this PR seems ok ? :angel: :pray:

**Comment by thaJeztah** [comment]
SGTM

**Comment by tiborvass** [comment]
@vdemeester I like the idea, but can you just reexplain the desired benefit it brings?

**Comment by vdemeester** [comment]
@tiborvass From https://github.com/moby/moby/issues/36337

> The `api/types` package should only contain the types used to serialize/deserialize requests and responses for the HTTP API. This is the case for most of the types in this package and sub packages.
>
> There are two exceptions:
> * `api/types/client.go` contains types that are used by `APIClient` interface in the `client` package
> * `api/types/backend` contains types that are used by the backend interfaces between the API routers and the server implementation
>
> These two categories of types are never used for serialization/deserialization.

This is my take at the first item of this list, i.e. moving the `client` only types (options, etc..) directly into the `client` package, while not pushing a breaking change (using aliased types). The "good" side-effect of this is that it force `api/types` struct to be put in their respective packages (`container`, …) — to not get import cycle errors.

**Comment by tiborvass** [comment]
@vdemeester Thanks! Please rebase :)

**Comment by vdemeester** [comment]
@tiborvass I'll wait a bit to rebase, as I feel https://github.com/moby/moby/pull/37151 or https://github.com/moby/moby/pull/37149 and some more important PRs might conflicts with this refactoring :angel:

**Pull request closed without merging**
