### PR TITLE
Merge 1.12.1 CHANGELOG to master

### PR DESCRIPTION
**Pull request by tiborvass**
Ping @thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM!

**Comment by thaJeztah** [comment]
It's just a cherry-pick, and already reviewed on the bump branch, so merging this

**Comment by tiborvass** [comment]
@thaJeztah not really a cherrypick, more of a copy.

**Comment by thaJeztah** [comment]
@tiborvass let's call it a  🍒 🐷

**Pull request merged**
