### PR TITLE
update docs about installer

### PR DESCRIPTION
**Pull request by longliqiang88**
related issue #19235 
 The shell `apt-get install docker` can not install the latest version docker,so we can run `wget -qO- https://get.docker.com/ | sh` to install the latest version.Thanks .
@HackToday

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh, sorry @longliqiang88, but it looks like this is already being worked on in https://github.com/docker/docker/pull/20046.

**Comment by longliqiang88** [comment]
Add annotation to the file docker/docker.go
Thanks for looking.

**Comment by longliqiang88** [comment]
Sorry,you said that "it looks like this is already being worked on in #20046.",but what I edited is different from his.  Thanks @HackToday

**Comment by thaJeztah** [comment]
> but what I edited is different from his

Yes, but I don't think this PR improves things much, because all the steps before this line explain the steps that are done automatically by the get.docker.com script.

I'm sorry, but I'm closing this PR, because I don't think this is the right change

**Pull request closed without merging**
