### PR TITLE
Remove fedora-23 because eol

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Remove fedora-23 because it will be [EOL 2016-12-20](https://fedoramagazine.org/fedora-23-end-of-life/):

> With the recent release of Fedora 25, Fedora 23 will officially enter End Of Life (EOL) status on December 20th, 2016. After December 20th, all packages in the Fedora 23 repositories will no longer receive security, bugfix, or enhancement updates, and no new packages will be added to the Fedora 23 collection.
> 
> Upgrading to Fedora 24 or Fedora 25 before December 20th 2016 is highly recommended for all users still running Fedora 23.

**- How I did it**

Removing the `contrib/builder` dir for `fedora-23`. This is similar to PR #27432 for EoL of fedora-22.

**- How to verify it**

```
$ make DOCKER_BUILD_PKGS=fedora-23 rpm # no more fedora-23
```

**- Description for the changelog**

Remove Fedora 23 as supported platform. Fedora 23 is EOL, and no longer receives updates

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

### CODE REVIEW

**Review by justincormack — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM, don't forget to update the docs as well https://github.com/docker/docker.github.io/blob/vnext-engine/engine/installation/linux/fedora.md

hm, looks like I forget to add 25 there as well

**Comment by vieux** [comment]
LGTM, ping @andrewhsu for the doc changes

**Comment by thaJeztah** [comment]
docs are in a separate repository, so we can merge this, but I added the "docs/revisit" label so that we don't forget

**Pull request merged**
