### PR TITLE
Upgrade containerd to latest version.

### PR DESCRIPTION
**Pull request by boucher**
Necessary for merging in #22049.

### CODE REVIEW

**Comment by tophj-ibm** [comment]
can you update the hashes in the other Dockerfiles (aarch64, armhf, ppc64le, s390x and simple) as well so they are all in sync?

**Comment by boucher** [comment]
@tophj-ibm Sure, done.

**Comment by tonistiigi** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
