### PR TITLE
Add a Dockerfile for generating manpages on s390x

### PR DESCRIPTION
**Pull request by justincormack**
Untested.

Hoping CI and @michael-holzheu can test...

Signed-off-by: Justin Cormack justin.cormack@docker.com

deer

### CODE REVIEW

**Comment by justincormack** [comment]
cc @dnephin

**Comment by dnephin** [comment]
LGTM

**Comment by justincormack** [comment]
Z test passed, but I don't think they actually build the man pages anywhere....

**Comment by justincormack** [comment]
@michael-holzheu ping.

**Comment by michael-holzheu** [comment]
@justincormack I tested your `man/Dockerfile.s390x` together with the following patch:

- michael-holzheu/docker@e86144b3c70f4ee1a6eacc22a133dd792c7c7d0b

Looks like the man pages have been built correctly:

```bash
# make deb
...
Step 12/13 : WORKDIR /go/src/github.com/docker/docker/
 ---> Running in ca0d038fa576
 ---> 7f305c4a3bc1
Removing intermediate container ca0d038fa576
 ---> Running in cedb13ecd869
 ---> 7908eec7b1f9
Removing intermediate container cedb13ecd869
Successfully built 7908eec7b1f9
...
```

Here the complete log for "make deb": [make-rpm.log.txt](https://github.com/docker/docker/files/435325/make-rpm.log.txt)

Currently we don't have any s390x support for `contrib/builder`.
What about starting with michael-holzheu/docker@e86144b3c70f4ee1a6eacc22a133dd792c7c7d0b?

> Z test passed, but I don't think they actually build the man pages anywhere....

Can you point me to a CI Jenkins job that builds the man pages?

**Comment by michael-holzheu** [comment]
> @michael-holzheu ping.

pong :-)

**Comment by michael-holzheu** [comment]
So regarding 1091dfb60f2326b05f0a3c77ae2b82ee8df370b0: LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by justincormack** [comment]
@michael-holzheu not entirely sure there is a test target that tests the man pages. We need to install the debs and rpms too really as part of testing... more work to do.

**Comment by michael-holzheu** [comment]
@justincormack What do you think? Should I create a PR for: michael-holzheu/docker@e86144b3c70f4ee1a6eacc22a133dd792c7c7d0b?

**Comment by michael-holzheu** [comment]
> @justincormack What do you think? 

@justincormack : I now created PR #26104

**Pull request merged**
