### PR TITLE
Bump v1.9.1

### PR DESCRIPTION
**Pull request by tiborvass**

### CODE REVIEW

**Comment by tiborvass** [comment]
```
----------------------------------------------------------------------
FAIL: docker_cli_pull_test.go:106: DockerHubPullSuite.TestPullAllTagsFromCentralRegistry

docker_cli_pull_test.go:130:
    c.Assert(splitLatest, checker.DeepEquals, splitCurrent, check.Commentf("busybox:latest was changed after pulling all tags"))
... obtained []string = []string{"busybox", "latest", "17583c7dd0da", "9", "days", "ago", "1.109", "MB"}
... expected []string = []string{"busybox", "latest", "c51f86c28340", "9", "days", "ago", "1.109", "MB"}
... busybox:latest was changed after pulling all tags
```

Will see if it's a one off or something actually wrong with the code.

**Comment by tiborvass** [comment]
1.9.1-rc1 is up

Ubuntu/Debian: `curl -sSL https://test.docker.com/ | sh`
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.9.1-rc1
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.9.1-rc1
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.9.1-rc1
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.9.1-rc1.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.9.1-rc1.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.9.1-rc1.exe

**Comment by LK4D4** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
