### PR TITLE
Update bash completion for `docker network create`

### PR DESCRIPTION
**Pull request by albers**
This adds support for `docker network create --internal` (#19276) and `docker network create --ipam-opt` (#17316)

ping @jfrazelle @tianon for review
Thanks @sdurrheimer for the ping.

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐺

**Comment by tianon** [comment]
Nice, LGTM :+1:

**Comment by vdemeester** [comment]
ping @thaJeztah for cherry pick (I guess :angel:)

**Comment by thaJeztah** [comment]
@vdemeester you can apply the "cherry-pick" label to make sure we don't miss them :)

Thanks @albers!

**Pull request merged**
