### PR TITLE
Change the wording of image verification warning.

### PR DESCRIPTION
**Pull request by jessfraz**
Updated the wording per @fredlf's recommendation.

### CODE REVIEW

**Comment by tianon** [comment]
Bahahaha I literally thought about pasting the old message to him for revising. :+1:

LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by SvenDowideit** [comment]
LGTM :)

**Comment by fredlf** [comment]
LGTM, but I would say that, wouldn't I? :-)

**Pull request merged**
