### PR TITLE
Add link to user guide to end of 14.04 section

### PR DESCRIPTION
**Pull request by stevekochscience**
Adding instructions to exit the test shell and a link to the user guide (as is done in the following sections for 12.04 and 13.04/10.

PS: I'm pretty sure the docker contributions encouraged pull requests like these for small changes to documentation. I hope it's not annoying!

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

~~~console
$ git clone -b "master" git@github.com:stevekochscience/docker.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

**Comment by stevekochscience** [comment]
Sorry, let me try to ammend the commit

**Comment by stevekochscience** [comment]
Apologies for forgetting the signoff. I've followed your instructions and it looks like my commit now includes the sign-off.

**Comment by jfrazelle** [comment]
perfect thanks so much.

**Comment by jfrazelle** [comment]
LGTM ping @SvenDowideit

**Comment by stevekochscience** [comment]
You're welcome and thank you! This whole system (Jenkins etc.) is amazing. And just started learning Docker which is also amazing. :)

**Comment by jamtur01** [comment]
LGTM

**Comment by jamtur01** [comment]
Ping @fredlf

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
