### PR TITLE
Added missing word.

### PR DESCRIPTION
**Pull request by mikecasas**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by duglin** [comment]
should this not going into 'master' too?

**Comment by mikecasas** [comment]
@duglin This was the branch I was taken to from the 'Edit this Page' button.

**Comment by thaJeztah** [comment]
Hm, yes, I've been mentioning that to the docs team 😞 

The usual flow in this repository is that we merge to master, then cherry-pick to the branches where the change is needed; I can cherry-pick this back into master if needed, or could you change it to be against "master"?

**Comment by mikecasas** [comment]
Do you want a new commit to master, or the current PR changed to master? Whichever is cleaner for you.

**Comment by thaJeztah** [comment]
Having it in "master" first would be perfect

**Comment by AkihiroSuda** [comment]
Closing this PR in favor of https://github.com/docker/docker/pull/32475

**Comment by mikecasas** [comment]
I created a new PR against master #32475.

You can close this.

**Pull request closed without merging**
