### PR TITLE
Remove "OMG IPV6" log message

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
Awww, I came here hoping it was literally putting `OMG IPV6` in `docker.log`. :+1:

**Comment by jfrazelle** [comment]
I was told there would be cake.

**Comment by MalteJ** [comment]
@tianon yeah, I was curious, too.
Now I am thinking about creating a PR "Adding 'OMG IPV6' log message"

**Pull request merged**
