### PR TITLE
remove "RC" warning from Markdown files

### PR DESCRIPTION
**Pull request by thaJeztah**
A site-wide banner is going to be used, so we don't need this warning

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @SvenDowideit PTAL let me know if this is correct, otherwise feel free to close

**Comment by SvenDowideit** [comment]
thank you for the list, I'll update after kids are in bed.

**Comment by SvenDowideit** [comment]
I'm making a followon PR

**Comment by thaJeztah** [comment]
thanks!

**Pull request closed without merging**
