### PR TITLE
Fix removing plugins and Implement plugin restore after daemon restart

### PR DESCRIPTION
**Pull request by cpuguy83**
Implement plugin restore after daemon restart

This ensures that:
- The in-memory plugin store is populated with all the plugins
- Plugins which were active before daemon restart are active after.
  This utilizes the liverestore feature when available, otherwise it manually starts the plugin.

Closes #23575

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @tiborvass @anusha-ragunathan

**Comment by cpuguy83** [comment]
Sorry, I've got this commit sitting on top of #23575

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Pull request merged**
