### PR TITLE
Change buildEndpointResource params avoid repeat visits resource

### LINKED ISSUE #24364: Docker network list very slow in overlay network through etcd
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   075161d-unsupported
 Built:        Wed Jul  6 07:06:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   075161d-unsupported
 Built:        Wed Jul  6 07:06:58 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 108
 Running: 106
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 272
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: cdd788f672ab24e33b17099680bede766-node1
ID: FBX3:ADNW:VU72:COWH:BJ5T:Y4BK:23TH:7J2O:YP5Y:4USL:SESZ:42AA
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 562
 Goroutines: 945
 System Time: 2016-07-06T17:59:59.362611803+08:00
 EventsListeners: 4
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://200.198.0.108:2379/cdd788f672ab24e33b17099680bede766
Cluster advertise: 10.25.214.121:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Create 100+ containers on this node in overlay network through etcd
2.Run `docker network ls` command

**Describe the results you received:**
```
NETWORK ID          NAME                 DRIVER
5ddc59fb2b4b        bridge               bridge
f7a17aea4419        docker_gwbridge      bridge
e2728c36d613        host                 host
f9e09ab1c9d8        multi-host-network   overlay
33fa521086df        none                 null
```

* This command will hanging about 7-8s

**Describe the results you expected:**
1. This command should return very quickly
2. Swarm and swarmkit rely this command, and in overlay network through etcd, 100+ containers will hang about 7-8s. If I have more containers in one node, maybe it will not return anymore.
3. This will delay swarm and swarmkit speed of creating container in overylay network.

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by xianlubird**
**\- What I did**
Fix #24364

**\- How I did it**
Change params to avoid repeat visit etcd 
**\- How to verify it**

```
docker network ls
```

See it's response time, maybe cost half of past
**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Xianlu xianlu.cxl@alibaba-inc.com

### CODE REVIEW

**Comment by xianlubird** [comment]
Ping @mavenugo @aboch WDYT ?

**Comment by xianlubird** [comment]
Ping @mavenugo @aboch @thaJeztah   @tiborvass  @dongluochen @coolljt0725  WDYT ?

@sfsmithcha

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
