### PR TITLE
#16498 - Linux mint LMDE (Debian Edition) support added to install script

### PR DESCRIPTION
**Pull request by justsml**
Fixes issue #16498 

Please let me know if/how to write tests for the install script.

### CODE REVIEW

**Comment by tiborvass** [comment]
weak LGTM

Ping @tianon @jfrazelle

**Comment by justsml** [comment]
@tiborvass thx... How's it looking now?

**Comment by justsml** [comment]
... i thought I was missing some commits before the automatic tests would pass...

**Comment by tiborvass** [comment]
@justsml argh, my bad sorry! Apparently it was good but was confused by the automatic labeling. It's now worse because there are 3 commits :(

Try this:
```
git checkout linuxmint
# beware: next command will make all uncommitted changes and commits in linuxmint branch go away
git reset --hard upstream/master   # assuming upstream is the docker/docker repo, otherwise replace it
git cherry-pick b012a8df34e354e73d72a4f0c70048cf020cda3b
git push -f origin         # assuming origin is your fork
```

**Comment by justsml** [comment]
@tiborvass thanks for the git commands

**Comment by jfrazelle** [comment]
We should not have to add this, the other platform support function 'check forks' should cover this NOT LGTM

**Comment by justsml** [comment]
Hey @jfrazelle currently the check_forked() function hopes `lsb_release -u` is supported (it errors on my fresh LMDE install), 

What are your thoughts on my updating `check_forked()` w/ code to handle when `$lsb_release == 'linuxmint' && $lsb_release_exit_code != "0"` ?

Thanks for the quick responses!!!

**Comment by jfrazelle** [comment]
hmmm idk i wonder if we can push upstream to them? or how have we handled others @tianon I have forgotten?

**Comment by jfrazelle** [comment]
cc @fmoliveira

**Comment by justsml** [comment]
Here's a basic implementation:
https://github.com/docker/docker/pull/16533

**Comment by fmoliveira** [comment]
#16533 looks more interesting as it looks more generic, I'll join the discussion there first.

**Comment by jcbrinfo** [comment]
Linux Mint has many editions. Some are based on Ubuntu, others on Debian. So, #16533 is more reliable.

**Comment by jfrazelle** [comment]
I'm going to close this in favor of https://github.com/docker/docker/pull/16533, thanks so much!

**Pull request closed without merging**
