### PR TITLE
[1.13.x] Publish long short syntax 1 13

### PR DESCRIPTION
**Pull request by vdemeester**
This is cherry-picking #28943 for 1.13.x 👼 

/cc @vieux @thaJeztah @mavenugo 

🐸

### CODE REVIEW

**Comment by mavenugo** [comment]
Thanks @vdemeester . LGTM

**Comment by vieux** [comment]
@vdemeester can you please rebase ? <3

**Comment by mavenugo** [comment]
@vieux the windowsRS1 failure doesnt seem related. It didnt even start the tests. :(

**Comment by mavenugo** [comment]
@vieux its 💚

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
added "merged-to-master" so that we know we don't have to merge it back

**Pull request merged**
