### PR TITLE
Bump Golang 1.12.2

### PR DESCRIPTION
**Pull request by thaJeztah**
go1.12.2 (released 2019/04/05) includes fixes to the compiler, the go
command, the runtime, and the doc, net, net/http/httputil, and os packages.
See the Go 1.12.2 milestone on our issue tracker for details:

https://github.com/golang/go/issues?q=milestone%3AGo1.12.2

Full diff: https://github.com/golang/go/compare/go1.12.1...go1.12.2

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tao12345666333** [comment]
after this has been merged, should we upgrade to golang 1.12.3?

**Comment by tao12345666333** [comment]
xref: https://github.com/golang/go/issues/31293

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
