### PR TITLE
Propagate context to exec delete

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
I'm not sure this is a correct solution. Start can return an error from grpc when context gets canceled even if the server side completed. Then if this context is reused it would now turn this deletion into no-op.  And if start failed with a proper error, context cancel can still happen after that and cancel the deletion. I guess this was also the thinking why background was used here at all.

I'm ok with switching background to a new timeouted context though.

Just as a note, that this is related to the deadlocks we are seeing and isn't solving the actual problem but just avoids one codepath that would trigger a deadlock in a different layer. Just putting this here to make sure we are still tracking the issues with client canceling fifos propagating to the containerd shim even when this PR is merged.

**Comment by thaJeztah** [comment]
> I guess this was also the thinking why background was used here at all.

We may want to add a comment to that part of the code to explain that reasoning

**Comment by andrewhsu** [comment]
This PR should not be merged when https://github.com/moby/moby/pull/38383 is merged because 38383 is the more desirable alternative.

**Pull request closed without merging**
