### PR TITLE
Fix warning

### LINKED ISSUE #19614: hack/make.sh always warns when running in container
hack/make.sh will always warn when running in container even when `inContainer` is set.

```
+ inContainer=AssumeSoInitially
++ go env GOHOSTOS
+ '[' linux = windows ']'
+ '[' /go/src/github.com/docker/docker '!=' /go/src/github.com/docker/docker ']'
+ '[' -z darwin/amd64 ']'
+ '[' -n AssumeSoInitially ']'
+ echo '# WARNING! I don'\''t seem to be running in a Docker container.'
# WARNING! I don't seem to be running in a Docker container.
+ echo '# The result of this command might be an incorrect build, and will not be'
# The result of this command might be an incorrect build, and will not be
+ echo '# officially supported.'
# officially supported.
+ echo '#'
```

if [ -n "$inContainer" ] should be if [ -z "$inContainer" ] so its true if its unset

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 3
Images: 65
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 71
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 2
Total Memory: 1.956 GiB
Name: d
ID: O63J:2JYF:767U:YN7D:YPLV:ZOQH:NZOR:PO5C:PYG3:4F2S:MHVW:6GXB
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 38
 System Time: 2016-01-23T20:42:49.387754644Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarevsphere

`uname -a`:
Darwin mbp 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by pr0xr**
Fixes #19614

Signed-off-by: Paul Liljenberg liljenberg.paul@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! LGTM 

ping @tianon for review

**Comment by runcom** [comment]
LGTM hit this and opened a PR as well :smile:

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by vdemeester** [comment]
`windowsTP4` are forever *queued* :sweat_smile:. Merging though.

**Pull request merged**
