### PR TITLE
rewrite inspectAll function to make code more readable

### PR DESCRIPTION
**Pull request by allencloud**
I found that function InspectAll in api/client is somewhat terrible.

What I did:
1. rewrite function inspectAll;
2. fix a typo 

Signed-off-by: allencloud allen.sun@daocloud.io

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! I think similar improvements are made as part of https://github.com/docker/docker/pull/24710, so I'm not sure we need to keep this open

/cc @dnephin

**Comment by dnephin** [comment]
@thaJeztah is referring to #23902 I think. It does look very similar to the changes I made in that PR.

**Comment by thaJeztah** [comment]
Oh, lol, doing it again, yup, I wanted to copy that URL :blush:

**Comment by thaJeztah** [comment]
@allencloud are you okay with closing this PR? Perhaps you can help review https://github.com/docker/docker/pull/23902

**Comment by allencloud** [comment]
Great. Sorry for my missing that PR. Thanks a lot @thaJeztah @dnephin 
I will close this pr and help to review that one.

**Comment by thaJeztah** [comment]
Awesome, thanks!

**Pull request closed without merging**
