### PR TITLE
Add counts of container operations

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

@thaJeztah As mentioned the other day...

Note this PR needs an update to engine-api to complete, but opening as a discussion PR to determine whether this is useful generically. I've had so many folks now ask me internally "so many containers were started during a CI/Performance/Validation suite run", and my answer as always been to count externally as the daemon doesn't expose this information. With this PR, the daemon tracks the number of containers which have been created/started/paused/... since the daemon was started, and returns that in docker info such as shown below

```
PS E:\> docker -H=tcp://127.0.0.1:2357 info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Containers since daemon start:
 Created: 122
 Exited: 42
 Paused: 0
 Restored: 0
 Started: 42
 Unpaused: 0
Images: 6
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat overlay null
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.0.amd64fre.rs1_release.160715-1616)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 1023 MiB
Name: WIN-U4T09JVQG98
ID: 7Y7S:TQL5:BZJC:474E:EBIL:JKGT:E3TO:4UJE:A3NR:7WRJ:TDTE:QPSY
Docker Root Dir: C:\CI\CI-1ed85d3\daemon
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

### CODE REVIEW

**Comment by crosbymichael** [comment]
@jhowardmsft 

I'm actually working on this for 1.13.  Here is a sample of what things looks like in the raw format:

```
# HELP docker_daemon_container_changes_ms The number of milliseconds it takes to list fs changes in a container.
# TYPE docker_daemon_container_changes_ms summary
docker_daemon_container_changes_ms{quantile="0.5"} NaN
docker_daemon_container_changes_ms{quantile="0.9"} NaN
docker_daemon_container_changes_ms{quantile="0.99"} NaN
docker_daemon_container_changes_ms_sum 0
docker_daemon_container_changes_ms_count 0
# HELP docker_daemon_container_commit_ms The number of milliseconds it takes to commit a container.
# TYPE docker_daemon_container_commit_ms summary
docker_daemon_container_commit_ms{quantile="0.5"} NaN
docker_daemon_container_commit_ms{quantile="0.9"} NaN
docker_daemon_container_commit_ms{quantile="0.99"} NaN
docker_daemon_container_commit_ms_sum 0
docker_daemon_container_commit_ms_count 0
# HELP docker_daemon_container_create_ms The number of milliseconds it takes to create a container.
# TYPE docker_daemon_container_create_ms summary
docker_daemon_container_create_ms{quantile="0.5"} 88
docker_daemon_container_create_ms{quantile="0.9"} 102
docker_daemon_container_create_ms{quantile="0.99"} 132
docker_daemon_container_create_ms_sum 73654
docker_daemon_container_create_ms_count 826
# HELP docker_daemon_container_delete_ms The number of milliseconds it takes to delete a container.
# TYPE docker_daemon_container_delete_ms summary
docker_daemon_container_delete_ms{quantile="0.5"} 9
docker_daemon_container_delete_ms{quantile="0.9"} 11
docker_daemon_container_delete_ms{quantile="0.99"} 15
docker_daemon_container_delete_ms_sum 6792
docker_daemon_container_delete_ms_count 827
# HELP docker_daemon_container_mount_ms The number of milliseconds it takes to mount a container's rootfs.
# TYPE docker_daemon_container_mount_ms summary
docker_daemon_container_mount_ms{quantile="0.5"} 15
docker_daemon_container_mount_ms{quantile="0.9"} 18
docker_daemon_container_mount_ms{quantile="0.99"} 26
docker_daemon_container_mount_ms_sum 25817
docker_daemon_container_mount_ms_count 1653
# HELP docker_daemon_container_start_ms The number of milliseconds it takes to start a container.
# TYPE docker_daemon_container_start_ms summary
docker_daemon_container_start_ms{quantile="0.5"} 208
docker_daemon_container_start_ms{quantile="0.9"} 233
docker_daemon_container_start_ms{quantile="0.99"} 267
docker_daemon_container_start_ms_sum 175893
docker_daemon_container_start_ms_count 825
# HELP docker_daemon_container_stats_ms The number of milliseconds it takes to collect stats for a container.
# TYPE docker_daemon_container_stats_ms summary
docker_daemon_container_stats_ms{quantile="0.5"} NaN
docker_daemon_container_stats_ms{quantile="0.9"} NaN
docker_daemon_container_stats_ms{quantile="0.99"} NaN
docker_daemon_container_stats_ms_sum 0
docker_daemon_container_stats_ms_count 0
# HELP docker_daemon_containers_list_ms The number of milliseconds it takes to list all containers.
# TYPE docker_daemon_containers_list_ms summary
docker_daemon_containers_list_ms{quantile="0.5"} NaN
docker_daemon_containers_list_ms{quantile="0.9"} NaN
docker_daemon_containers_list_ms{quantile="0.99"} NaN
docker_daemon_containers_list_ms_sum 0
docker_daemon_containers_list_ms_count 5
# HELP docker_daemon_containers_running_count The number of running containers.
# TYPE docker_daemon_containers_running_count gauge
docker_daemon_containers_running_count 0
# HELP docker_daemon_image_delete_ms The number of milliseconds it takes to delete an image.
# TYPE docker_daemon_image_delete_ms summary
docker_daemon_image_delete_ms{quantile="0.5"} NaN
docker_daemon_image_delete_ms{quantile="0.9"} NaN
docker_daemon_image_delete_ms{quantile="0.99"} NaN
docker_daemon_image_delete_ms_sum 0
docker_daemon_image_delete_ms_count 0
# HELP docker_daemon_image_history_ms The number of milliseconds it takes to get the history of an image.
# TYPE docker_daemon_image_history_ms summary
docker_daemon_image_history_ms{quantile="0.5"} NaN
docker_daemon_image_history_ms{quantile="0.9"} NaN
docker_daemon_image_history_ms{quantile="0.99"} NaN
docker_daemon_image_history_ms_sum 0
docker_daemon_image_history_ms_count 0
# HELP docker_daemon_image_inspect_ms The number of milliseconds it takes to inspect an image.
# TYPE docker_daemon_image_inspect_ms summary
docker_daemon_image_inspect_ms{quantile="0.5"} NaN
docker_daemon_image_inspect_ms{quantile="0.9"} NaN
docker_daemon_image_inspect_ms{quantile="0.99"} NaN
docker_daemon_image_inspect_ms_sum 0
docker_daemon_image_inspect_ms_count 0
# HELP docker_daemon_images_list_ms The number of milliseconds it takes to list all images.
# TYPE docker_daemon_images_list_ms summary
docker_daemon_images_list_ms{quantile="0.5"} NaN
docker_daemon_images_list_ms{quantile="0.9"} NaN
docker_daemon_images_list_ms{quantile="0.99"} NaN
docker_daemon_images_list_ms_sum 0
docker_daemon_images_list_ms_count 0
# HELP docker_daemon_network_create_ms The number of milliseconds it takes to create a network.
# TYPE docker_daemon_network_create_ms summary
docker_daemon_network_create_ms{quantile="0.5"} NaN
docker_daemon_network_create_ms{quantile="0.9"} NaN
docker_daemon_network_create_ms{quantile="0.99"} NaN
docker_daemon_network_create_ms_sum 0
docker_daemon_network_create_ms_count 0
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000135164
go_gc_duration_seconds{quantile="0.25"} 0.00045902400000000004
go_gc_duration_seconds{quantile="0.5"} 0.0006505150000000001
go_gc_duration_seconds{quantile="0.75"} 0.051544091
go_gc_duration_seconds{quantile="1"} 0.059713218000000005
go_gc_duration_seconds_sum 7.455886533
go_gc_duration_seconds_count 387
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 34
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.4146776e+07
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 4.166391168e+09
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.816542e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 1.0442009e+07
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 1.517568e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.4146776e+07
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 1.1280384e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 1.8374656e+07
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 138451
# HELP go_memstats_heap_released_bytes_total Total number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes_total counter
go_memstats_heap_released_bytes_total 0
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 2.965504e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.4694886768660781e+19
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 217321
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 1.058046e+07
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 4800
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 243120
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 294912
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 2.5254996e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 940314
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 753664
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 753664
# HELP go_memstats_sys_bytes Number of bytes obtained by system. Sum of all system allocations.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 3.4994424e+07
# HELP http_request_duration_microseconds The HTTP request latencies in microseconds.
# TYPE http_request_duration_microseconds summary
http_request_duration_microseconds{handler="prometheus",quantile="0.5"} 1879.211
http_request_duration_microseconds{handler="prometheus",quantile="0.9"} 3447.618
http_request_duration_microseconds{handler="prometheus",quantile="0.99"} 9695.142
http_request_duration_microseconds_sum{handler="prometheus"} 1.2770453339000003e+07
http_request_duration_microseconds_count{handler="prometheus"} 1540
# HELP http_request_size_bytes The HTTP request sizes in bytes.
# TYPE http_request_size_bytes summary
http_request_size_bytes{handler="prometheus",quantile="0.5"} 305
http_request_size_bytes{handler="prometheus",quantile="0.9"} 305
http_request_size_bytes{handler="prometheus",quantile="0.99"} 305
http_request_size_bytes_sum{handler="prometheus"} 469216
http_request_size_bytes_count{handler="prometheus"} 1540
# HELP http_requests_total Total number of HTTP requests made.
# TYPE http_requests_total counter
http_requests_total{code="200",handler="prometheus",method="get"} 1540
# HELP http_response_size_bytes The HTTP response sizes in bytes.
# TYPE http_response_size_bytes summary
http_response_size_bytes{handler="prometheus",quantile="0.5"} 2065
http_response_size_bytes{handler="prometheus",quantile="0.9"} 2070
http_response_size_bytes{handler="prometheus",quantile="0.99"} 2071
http_response_size_bytes_sum{handler="prometheus"} 3.115557e+06
http_response_size_bytes_count{handler="prometheus"} 1540
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 44.39
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 19
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 6.406144e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.46946559774e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 5.11172608e+08
```

When ingested via something like prometheus you get simple charting like this for the various metrics:

prom-test

**Comment by jhowardmsft** [comment]
@crosbymichael Very cool :sunglasses: Will be interesting to see if what you come up with can be hooked into something like OMS on Windows, and what stats are relevant on Linux vs Windows. 

However, just my $.02, we're trying to solve slightly different problems here - one is the sledgehammer approach which gives you the fine-grained granular approach and really needs some analytics system to interpret the data. The other is extremely self contained and extends an existing semantic in the engine and client. I think there's probably room for both :smile_cat:

**Comment by jhowardmsft** [comment]
@crosbymichael / maintainers - do you see any value in this at all? Or should I close it and not bother putting together an engine-api PR to support this?

**Comment by vdemeester** [comment]
@jhowardmsft @crosbymichael hum I would think #25820 would cover these better. WDYT ?

**Comment by crosbymichael** [comment]
Since we are reworking the metrics collection and we will be collecting all this information in another pr we can take another look at this method of output after we have the collection finished

**Pull request closed without merging**
