### PR TITLE
`docker cp`++

### PR DESCRIPTION
**Pull request by jlhawn**
This pull request builds on top of #13171 by adding support for container paths which contain shell globs, and general support for multiple source arguments when copying.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Added this to the 1.8 milestone (see the [roadmap wiki](https://github.com/docker/docker/wiki/Engine-1.8.0/9576fc453a8e8880446f1e3c70b422c6ea08257d))

**Comment by icecrime** [comment]
Removing from 1.8 milestone: let's focus on #13171.

**Comment by jlhawn** [comment]
:+1:

**Comment by jlhawn** [comment]
Since `filepath.Glob` will follow symlinks, the best way to do this will probably be to do a re-exec with a `chroot`, resolve the patters from there, then return those.

**Comment by icecrime** [comment]
I'm happy with the new `cp`: do we *really* need this?

**Comment by cpuguy83** [comment]
As much as `docker cp` can behave like `cp`/`scp` it would be great.

**Comment by rgarbin** [comment]
The new docker cp has documentation?
https://docs.docker.com/reference/api/docker_remote_api_v1.18/

**Comment by thaJeztah** [comment]
@rgarbin you probably have to look in API v1.20 for the new cp functionality

**Comment by calavera** [comment]
@jlhawn I think this needs additional tests for the functionality that's adding and documentation. I just moved it to code-review.

**Comment by jlhawn** [comment]
I'm closing for now as I haven't maintained this feature in a while and there's also a potential security issue with the glob matching (might be best to do it in a chroot).

**Comment by jlhawn** [comment]
I'll reopen again soon when I have a chance to update it.

**Pull request closed without merging**
