### PR TITLE
builder: fix pull synchronization regression

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes https://github.com/moby/buildkit/issues/1939 ("Failed to compute cache key in newer version")

regression from dbffbe8f9bbeb784a5ebbd8979e548370548b6e8 and 8f464ae2ab8275a1c29984b501cc083a5973efe0 (https://github.com/moby/moby/pull/41601) (v20.10 only). Buildkit standalone/buildx is not affected.

Config resolution was synchronized based on wrong key as ref
variable is initialized only after in the same function. This means that
on parallel config pulls keys can collide and one side is ignored. Using
right key isn't fully correct either as the syncronized method
changes properties of the puller instance and can't be just skipped.
Added better error handling for the same case as well.

@DRoet @summera

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
SGTM

**Comment by thaJeztah** [comment]
@tiborvass @AkihiroSuda PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by BretFisher** [comment]
Thanks a lot ya'll. Quick turnaround on this one!

**Pull request merged**
