### PR TITLE
Move the monolith

### PR DESCRIPTION
**Pull request by cpuguy83**
This moves the old engine code into /monolith.
Part of #32871

api, pkg, and client remain at the top level since these are packages that are used by external consumers.

Have not touched `cli` yet since this is changing significantly with #32694

This does move the Makefile into monolith/, which will most certainly break existing workflows, and most likely CI, however tests and everything can be run from `monolith/`

TODO:
- [x] Fix moby logo in README.md
- [x] Remove CLI components (dependent on #32694)
- [ ] Fix Windows CI

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Maybe `engine` would be a more descriptive directory name.

**Comment by cpuguy83** [comment]
I don't think engine is very descriptive at all, it has very little meaning.
In addition some new component could potentially be called "engine" thus making it confusing.
"monolith" is very much not confusing, we know what it is and that is going away.

If the goal of moby is to split up the monolith, and we have a dir called "monolith", it's pretty simple to tell where the work lies.

To all, let's please not bike-shed on the naming here. Ultimately this is going away.

**Comment by AkihiroSuda** [comment]
README.md needs to be on the root

**Comment by AkihiroSuda** [comment]
daemon/graphdriver/devmapper can be moved to the monolith directory

**Comment by cpuguy83** [comment]
@AkihiroSuda Thanks!

I've added symlinks to the real Dockerfiles under `monolith/` at the root of the repo. This is so CI can continue to work as apparently CI does not use `Makefile` to build.
I also added a dummy `Makefile` at the root which just passes everything through to `monolith/`
Once this is merged we can update the CI to use the new paths and then remove them from the project root.

**Comment by AkihiroSuda** [comment]
Moby logo in README broken 😅

**Comment by cpuguy83** [comment]
Added a checklist of things to fix, which is currently quite small, feel free to update as you notice issues.

**Comment by cpuguy83** [comment]
Fixed logo, updated with docker/cli changes.

**Comment by cpuguy83** [comment]
ping @jhowardmsft Could use some help with the Windows CI.
Assuming the Windows CI doesn't like the symlink I put in for Dockerfile.windows.

**Comment by cpuguy83** [comment]
powerpc and z are failing for the same reason.
Sadly we don't get any archives of the daemon logs on these.

```
09:29:13 FAIL: docker_cli_daemon_test.go:2831: DockerDaemonSuite.TestRemoveContainerAfterLiveRestore
09:29:13 
09:29:13 [de8ef8ec90e68] waiting for daemon to start
09:29:13 [de8ef8ec90e68] exiting daemon
09:29:13 docker_cli_daemon_test.go:2833:
09:29:13     s.d.StartWithBusybox(c, "--live-restore", "--storage-driver", "overlay")
09:29:13 daemon/daemon.go:198:
09:29:13     t.Fatalf("Error starting daemon with arguments: %v", args)
09:29:13 ... Error: Error starting daemon with arguments: [--live-restore --storage-driver overlay]
```

**Comment by jhowardmsft** [comment]
@cpuguy83 I'm slammed between the Linux containers on Windows bring-up and containerd. Perhaps @johnstep has time to look. However, if the symlink is in the source tree itself, that won't work at all on Windows - git won't clone them.

**Comment by cpuguy83** [comment]
We discussed just keeping two copies of `Dockerfile.windows` for a (very) short period... long enough to change CI over to use the new Dockerfile path.

WDYT?

**Comment by jhowardmsft** [comment]
To be clear, the use of ANY symlinks in a git repo mean that the clone won't work correctly on Windows. This needs to be solved without any symlinks in the repo.

**Comment by cpuguy83** [comment]
Running into some issues with Windows CI expecting paths to be under the root  (like docker.exe, dockerd.exe) instead of monolith/.
These two in particular are fairly easy to work-around by copying the binaries from monolith/bundles to bundles/.

dockerversion/version_autogen.go is slightly more complicated.

**Comment by alexellis** [comment]
Trying to catch up on the naming of everything. What does a folder called Monolith actually mean?

**Comment by cpuguy83** [comment]
Closing based on discussions on the forums it seems like we will just move the engine out of the repo.

**Pull request closed without merging**
