### PR TITLE
Update fsutil to latest master and remove deprecated fileutil.Matches

### LINKED ISSUE #42788: .dockerignore: !**/file doesn't work for selected inclusion
I followed the [docs](https://docs.docker.com/engine/reference/builder/#dockerignore-file) and setup my .dockerignore like this:
```
# ignore everything
*
# but include all package.xml in any folder
!**/package.xml
```
However, these files are *not* added to the context as expected. Seems like `**` doesn't work for inclusion?
Explicitly adding those files works as expected.

Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.1

### PR DESCRIPTION
**Pull request by aaronlehmann**
fixes https://github.com/moby/moby/issues/42788

Now that fsutil is being updated to a new version, the original `Matches`
function and method are no longer needed. Remove them in favor of the
versions that have been fixed to handle `**/foo` patterns.

See #42676 for context.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
This will need an update to buildkit too; I'll open a PR over there.

**Comment by aaronlehmann** [comment]
Buildkit PR here: https://github.com/moby/buildkit/pull/2319

Once it gets merged, I can update this PR to revendor buildkit as well.

**Comment by thaJeztah** [comment]
Ah, yes, looks like it's currently failing;

```

[2021-08-18T20:24:33.242Z] Building test suite binary /go/src/github.com/docker/docker/integration/container/test.main
[2021-08-18T20:25:29.555Z] # github.com/docker/docker/vendor/github.com/moby/buildkit/cache/contenthash
[2021-08-18T20:25:29.555Z] vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:621:34: includePatternMatcher.Matches undefined (type *fileutils.PatternMatcher has no field or method Matches)
[2021-08-18T20:25:29.555Z] vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:631:34: excludePatternMatcher.Matches undefined (type *fileutils.PatternMatcher has no field or method Matches)
[2021-08-18T20:25:29.555Z] # github.com/docker/docker/vendor/github.com/moby/buildkit/cache/contenthash
[2021-08-18T20:25:29.555Z] vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:621:34: includePatternMatcher.Matches undefined (type *fileutils.PatternMatcher has no field or method Matches)
[2021-08-18T20:25:29.555Z] vendor/github.com/moby/buildkit/cache/contenthash/checksum.go:631:34: excludePatternMatcher.Matches undefined (type *fileutils.PatternMatcher has no field or method Matches)
```


Let me warn up-front that updating buildkit may involve some niggles; I was working on that for the docker/cli (and did it in a couple of steps to bring other dependencies up to date); https://github.com/docker/cli/pull/3237.

If I'm able to find some time, I may give it a try to update it (if it can work without this update), then leave the final update to this PR.

**Comment by thaJeztah** [comment]
The circular dependency is a bit of a pain; I recall doing https://github.com/tonistiigi/fsutil/pull/105 to move this all to fsutil, but I think Tonis didn't want to have to maintain it 😂

**Comment by aaronlehmann** [comment]
@thaJeztah: The buildkit PR got merged. I tried updating buildkit and I've run into some issues with other dependencies. Would you be interested in taking it from here?

**Comment by aaronlehmann** [comment]
I won't be completing this; therefore closing the PR.

**Pull request closed without merging**
