### PR TITLE
added -extfile to server certificate documentation

### PR DESCRIPTION
**Pull request by lgfausak**
I spent many hours trying to get this to work, in the end it is
fairly simple.
subjectAltName=IP:x.x.x.x
this allows for connecting to the docker server from docker client
using the dns name OR using the IP address (lots of docker stuff
prefers IP addresses)

### CODE REVIEW

**Comment by lgfausak** [comment]
ok, i signed my work.


On Wed, Feb 11, 2015 at 10:10 AM, Gordon <notifications@github.com> wrote:

> Can you please sign your commits following these rules:
>
> https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work
>
> The easiest way to do this is to amend the last commit:
>
> $ git clone -b "master" git@github.com:tacodata/docker.git somewhere
> $ cd somewhere
> $ git commit --amend -s --no-edit
> $ git push -f
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/10710#issuecomment-73907980>.
>



-- 
Greg Fausak
lgfausak@gmail.com

**Comment by SvenDowideit** [comment]
argh. this extension is not in tinycore, ie boot2docker, so my test fails there.

@lgfausak what distro did you test this on?

**Comment by SvenDowideit** [comment]
heya @lgfausak I've tweaked your text a little at #10722 and added changes to allow my test harness to use it too

**Comment by lgfausak** [comment]
@SvenDowideit I think you already got it to work, but, I was using ubuntu:14.04 testing the openssl -extfile stuff.

**Pull request closed without merging**
