### PR TITLE
Use sudo when running the experimental installer

### LINKED ISSUE #14590: Docker Experimental Script Installs Docker 1.6.2 Stable on CentOS
When running `wget -qO- https://experimental.docker.com | sh ` on CentOS 7, this installs `Docker version 1.6.2, build ba1f6c3/1.6.2`. Is there something I'm missing for experimental release installation?

### PR DESCRIPTION
**Pull request by kkirsche**
Fixes #14590

### CODE REVIEW

**Comment by kkirsche** [comment]
If you can't sign via github's site that really isn't a great requirement....

**Comment by jfrazelle** [comment]
false, sorry. What error are you getting because this is not the correct fix ;)

**Comment by jfrazelle** [comment]
sorry closing, I fixed here https://github.com/docker/docker/pull/15064

**Comment by kkirsche** [comment]
@jfrazelle what are you talking about....?

**Comment by jfrazelle** [comment]
i found the fix for your problem, you should not need to | sudo sh

**Comment by thaJeztah** [comment]
> If you can't sign via github's site that really isn't a great requirement...

Sorry for that @kkirsche we really can't accept PRs that aren't signed off (legal stuff..), and trust me: there's been a **lot** of cursing around the limitations of the GitHub web interface in this area.

**Comment by kkirsche** [comment]
A.) signed it
B.) your the only company that needs this? Bullshit.

**Pull request closed without merging**
