### PR TITLE
Windows: [TP3] Fix certificate directory for registry

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

@swernli

This PR is part of the proposal described in docker/docker issue 10662 to port the docker daemon to Windows. Windows doesn't have an /etc directory :) @calavera I had to undo some of your const*.go changes as the _windows and _unix files now have more than just const in them.

### CODE REVIEW

**Comment by calavera** [comment]
sounds good.

`munge`? what about something more descriptive, like `cleanPath`? :smile:

**Comment by jhowardmsft** [comment]
Yeah :) Updated.

**Comment by jhowardmsft** [comment]
Crazy Windows CI results - seen this on two PRs this afternoon. Not sure if some bad merge has gone in, or CI strangeness again. Experimental has been having catastrophic errors since mid afternoon. Restarted 3 times, same result.

**Comment by jhowardmsft** [comment]
Windows CI will be fixed by GH15336

**Comment by jhowardmsft** [comment]
And it is fixed. Yay green CI

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
