### PR TITLE
Consider making the main installation URI for all products be <product>/install/...

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit SvenDowideit@home.org.au

ok, so @thaJeztah and I wondered what it would take to make the `install` URI more obvious - and this is what we need to do for this project...

I'm guessing this is not something we want to merge for 1.10 :)

### CODE REVIEW

**Comment by thaJeztah** [comment]
> Consider making the main URI ...

Well, this still allows us to have `/some-product/` as a landing page for each product

But, I like it, so LGTM (but possibly not for 1.10, we can discuss however) :smile:


ping @moxiegirl wdyt?

**Comment by moxiegirl** [comment]
Let's not touch this until after 1.10 is out. I

**Comment by thaJeztah** [comment]
> Let's not touch this until after 1.10 is out. I'll look at it next week.

SGTM, we already came to the conclusion that changing it in all repositories would not be wise, so close to the release

**Comment by tiborvass** [comment]
Whatever we do with this, can we make sure we 301 on old URLs when we change them?

**Comment by thaJeztah** [comment]
ping @moxiegirl did you have time to look at / think about this?

**Comment by moxiegirl** [comment]
You'll have to explain the value of this to me. It isn't leaping off the page.  How does renaming the path make it more obvious?

**Comment by thaJeztah** [comment]
@moxiegirl point is that the "url" of a website is also (kind of) an API, being
consistent, and having predictable URLs helps here. Currently it's really a mix
of approaches, and I'd like to have it consistent.

Currently, we have (just a quick check):

- Engine https://docs.docker.com/engine/installation/
- Compose https://docs.docker.com/compose/install/
- DTR https://docs.docker.com/docker-trusted-registry/install/

Docker machine includes "machine" in the URL, possibly from old time, when page names couldn't overlap

- https://docs.docker.com/machine/install-machine/


UCP keeps separate pages for "production" / "evaluation", which could be grouped under an "install" section;

- https://docs.docker.com/ucp/evaluation-install/
- https://docs.docker.com/ucp/plan-production-install/
- https://docs.docker.com/ucp/production-install/


Having a consistent URL scheme enables me to go to;

- https://docs.docker.com/ to get an overview of all products
- https://docs.docker.com/PRODUCT/ to get an overview of a product
- https://docs.docker.com/PRODUCT/INSTALL/ to view how to install the product
- etc.

In addition, properly designed URL structures can help improve SEO. Some random
articles;

- https://www.nngroup.com/articles/url-as-ui/
- http://warpspire.com/posts/url-design/
- https://moz.com/blog/11-best-practices-for-urls
- http://www.creativebloq.com/design/design-perfect-url-1126509

**Comment by calavera** [comment]
@thaJeztah, @SvenDowideit what should we do with this?

**Comment by thaJeztah** [comment]
I'll close this for now; we can continue the discussion though

**Pull request closed without merging**
