### PR TITLE
Use waitAndAssert to test node state changes

### PR DESCRIPTION
**Pull request by tonistiigi**
wip: depending on #24459 

cc @cpuguy83

### CODE REVIEW

**Comment by thaJeztah** [comment]
Is there an issue related to this?

**Comment by tonistiigi** [comment]
@thaJeztah https://github.com/docker/docker/pull/24459#discussion_r70139887

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐭

**Pull request merged**
