### PR TITLE
Windows: Revendor github.com/Microsoft/go-winio

### PR DESCRIPTION
**Pull request by jstarks**
This fixes docker save when the daemon was launched from a remote PowerShell session. This is currently failing for obscure reasons having to do with the Windows privilege model.

Signed-off-by: John Starks jostarks@microsoft.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐰 but needs a rebase.

**Comment by jstarks** [comment]
@jhowardmsft Hitting test timeouts in TP4 after the rebase. I suspect this is just a flaky test environment.

**Comment by jhowardmsft** [comment]
Restarted.

**Comment by calavera** [comment]
LGTM

**Pull request merged**
