### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by x1957**
**- What I did**
fix typo in daemon/graphdriver/lcow/lcow.go

**- How I did it**

**- How to verify it**
see changes

**- Description for the changelog**

Fixed typos

**- A picture of a cute animal (not mandatory but encouraged)**
img

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by AkihiroSuda — APPROVED** [review]

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by duglin** [comment]
LGTM

**Review by lowenna — COMMENTED** [review]
LGTM

**Pull request merged**
