### PR TITLE
Add missing nil-check on errdefs.Unavailable()

### PR DESCRIPTION
**Pull request by thaJeztah**
This was done on all the other ones, so let's add it here as well

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @vdemeester

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
