### PR TITLE
awslogs: fix flaky TestLogBlocking unit test

### LINKED ISSUE #39857: Flaky test: awslogs tests failing with ResourceAlreadyExistsException
Not sure if related to similar errors, but there were some fixes for race-conditions in the past (see https://github.com/moby/moby/issues/22963, and https://github.com/moby/moby/pull/22985)

Seen this failing a couple of times: 

Failure on RS1 (but I may have seen this on other platforms); https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39855/runs/1/nodes/39/log/?start=0

```
time="2019-09-03T10:15:19Z" level=info msg="Trying to get region from EC2 Metadata"
time="2019-09-03T10:15:19Z" level=info msg="Log stream already exists" errorCode=ResourceAlreadyExistsException logGroupName= logStreamName= message= origError="<nil>"
--- FAIL: TestLogBlocking (0.02s)
    cloudwatchlogs_test.go:313: Expected to be able to read from stream.messages but was unable to
time="2019-09-03T10:15:19Z" level=error msg=Error
time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=InvalidSequenceTokenException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
time="2019-09-03T10:15:19Z" level=info msg="Data already accepted, ignoring error" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token"
FAIL
coverage: 78.2% of statements
FAIL	github.com/docker/docker/daemon/logger/awslogs	0.631s
```

Interesting bit in that case is that the test that was marked failing looks to be using a `mockClient` (so should not even be connecting to AWS?) https://github.com/moby/moby/blob/e78a3dca21ea9ceb8d7a5e0252e94ee7ad05eadd/daemon/logger/awslogs/cloudwatchlogs_test.go#L288-L322

For other tests, we seem to be reusing the same `groupName` and `logStreamName`, so I suspect this is just a race condition (and AWS doesn't like attempting to create duplicates); https://github.com/moby/moby/blob/e78a3dca21ea9ceb8d7a5e0252e94ee7ad05eadd/daemon/logger/awslogs/cloudwatchlogs_test.go#L29-L36

Should we add a unique suffix to the `groupName` and `logStreamName` in the tests? (e.g., use the test name as suffix? `groupName+t.Name()`)

### PR DESCRIPTION
**Pull request by samuelkarp**
**- What I did**
Fix https://github.com/moby/moby/issues/39857

**- How I did it**
TestLogBlocking is intended to test that the Log method blocks by default.  It does this by mocking out the internals of the awslogs.logStream and replacing one of its internal channels with one that is controlled by the test.  The call to Log occurs inside a goroutine.  Go may or may not schedule the goroutine immediately and the blocking may or may not be observed outside the goroutine immediately due to decisions made by the Go runtime.  This change adds a small timeout for test failure so that the Go runtime has the opportunity to run the goroutine before the test fails.

**- How to verify it**
`TestLogBlocking` doesn't fail anymore.

```
$ go test -run TestLogBlocking  -count 10000 ./daemon/logger/awslogs/
ok  	github.com/docker/docker/daemon/logger/awslogs	0.476s
```

**- Description for the changelog**
N/A

### CODE REVIEW

**Comment by samuelkarp** [comment]
I'm not sure what failed, but in the failed run I still see this:

```
[2019-09-20T23:29:14.035Z] ok  	github.com/docker/docker/daemon/logger/awslogs	0.635s	coverage: 77.8% of statements
```

**Comment by thaJeztah** [comment]
thank you! I kicked CI to run again

**Comment by thaJeztah** [comment]
@ddebroy @vikramhh @kolyshkin PTAL

**Comment by vikramhh** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
