### PR TITLE
Updates libcontainer to v2.2.1

### PR DESCRIPTION
**Pull request by mrunalp**
@LK4D4 PTAL.
Signed-off-by: Mrunal Patel mrunalp@gmail.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@mrunalp Uh-oh, some failures around groups :/

**Comment by mrunalp** [comment]
@LK4D4 hmm, looks like related to not finding /etc/group in that particular image.

**Comment by mrunalp** [comment]
@LK4D4 I am working on a fix.

**Comment by mrunalp** [comment]
Pushed the update with fix; will wait for builds now.

**Comment by mrunalp** [comment]
TestLogsFollowSlowStdoutConsumer failed in janky but it passed for me locally. The failure seems unrelated to this PR.

**Comment by mrunalp** [comment]
Also, looks like none of the tests failed on experimental but failure during teardown.

**Comment by LK4D4** [comment]
LGTM
It's impossible  to get all CI steps green today :D

**Comment by mrunalp** [comment]
@LK4D4 Yes, sometimes it is better to move on :)

**Comment by mrunalp** [comment]
@crosbymichael PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
Thanks!

**Pull request merged**
