### PR TITLE
Revendor Microsoft/hcsshim @v0.7.3

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Bumps hcsshim to a released tag rather than a commit hash (https://github.com/Microsoft/hcsshim/releases/tag/v0.7.3)

[Note while this is marked as pre-release, hcsshim strictly has always been pre-release as we haven't got to a v1.0 yet. Current hcsshim is in progress while we are working on v2 schema work to support various RS5/containerd/runhcs(runc) scenarios, although the v1 code which is the only code docker currently uses is unchanged apart from some internal re-org within the repo]

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Closing temporarily - need to bump to v0.7.3 once @jterry75 implements a small regression in the guid code (doesn't look like it affect docker directly, but does runhcs/containerd).

**Comment by jhowardmsft** [comment]
Re-opened and bumped to v0.7.3

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
That's figured now. vendor is passing.

**Review by yongtang — APPROVED** [review]
LGTM if CI is green.

**Comment by Adawntoremember** [comment]
Copy

**Pull request merged**
