### PR TITLE
docs/api: add documentation for API v1.47

### PR DESCRIPTION
**Pull request by vvoland**
API version used by the v27.2.0 release.

### CODE REVIEW

**Review by robmry — APPROVED** [review]

**Review by thaJeztah — CHANGES_REQUESTED** [review]
I think we only need a copy of the Swagger file here, not a markdown file?

**Comment by thaJeztah** [comment]
Oh! It is the swagger file, but wrong file extension 😅

**Comment by vvoland** [comment]
Yep, thanks for spotting! 😅

**Comment by thaJeztah** [comment]
Do we want https://github.com/moby/moby/pull/48357 to be included before we create the copy?

**Comment by vvoland** [comment]
I can rebase that PR after this one is merged too, I'm fine anyway.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by laurazard — APPROVED** [review]

**Pull request merged**
