### PR TITLE
hack: make.sh: remove not used function

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by vdemeester** [comment]
Oh I was pretty sure it was used somewhere but.. `janky` and friends are telling me that's not the case.

ping @jfrazelle @tianon

**Comment by runcom** [comment]
`ag` isn't returning usage anywhere :)

**Comment by MHBauer** [comment]
use removed in 
1c23de0e64887f6c36b2156dd65717f723493775 & f7e417ea5e26f11ec43dba64ee153765d2276f40 

Concur no current usage.

**Comment by runcom** [comment]
thanks @MHBauer for confirming!

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by calavera** [comment]
LGTM

**Pull request merged**
