### PR TITLE
Vendor change jhowardmsft/opengcs to Microsoft/opengcs

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Moves from the repo I started developing the opengcs client code from (jhowardmsft/opengcs/gogcs/client) into an official Microsoft repo (Microsoft/opengcs/client).

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
@thaJeztah Just a sec - I got something wrong with vendoring

**Comment by thaJeztah** [comment]
Oh, actually, looks like there's an issue with the README and LICENSE

```
21:46:41 The result of vndr differs
21:46:41 
21:46:41  M vendor/github.com/Microsoft/opengcs/LICENSE
21:46:41  M vendor/github.com/Microsoft/opengcs/README.md
21:46:41 
21:46:41 Please vendor your package with github.com/LK4D4/vndr.
21:46:41

**Comment by thaJeztah** [comment]
LOL beat me to it

**Comment by jhowardmsft** [comment]
Dang, looks like it was CF/LF line endings :( Hopefully fixed now.

**Comment by thaJeztah** [comment]
thanks! Still LGTM

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
Restarted powerpc

**Review by justincormack — APPROVED** [review]

**Pull request merged**
