### PR TITLE
Preserve /etc/sysconfig/docker across rpm update

### PR DESCRIPTION
**Pull request by wcwxyz**
Otherwise we have to reconfigure every time docker rpm got update.

Signed-off-by: WANG Chao wcwxyz@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
thanks let me try this out

**Comment by jfrazelle** [comment]
ping @Djelibeybi  since this really only effects oracle 6

**Comment by jfrazelle** [comment]
LGTM

**Comment by Djelibeybi** [comment]
:+1: I actually had exactly the same patch queued to push, so LGTM too.

**Comment by jfrazelle** [comment]
thanks!!

**Pull request merged**
