### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by pcgeek86**
**\- What I did**

Updated the GitHub issue template, adding general support details.

**\- How I did it**

Edited Markdown

**\- How to verify it**

Visually examine `ISSUE_TEMPLATE.md`

Added general support information to the issue template.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice!

Can you sign off your commit, using the instructions @GordonTheTurtle gave above?

**Comment by pcgeek86** [comment]
Sure, FYI the example seems to assume the use of Git with SSH. I had to change it to work with HTTPS.

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
@pcgeek86 oh! I had a PR for that, but see it wasn't merged yet; https://github.com/docker/leeroy/pull/63

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
