### PR TITLE
Format colors

### PR DESCRIPTION
**Pull request by samoht**
Example:

```
docker ps --format '{{ .Blue (.Underline .ID) }}'
```

### CODE REVIEW

**Comment by samoht** [comment]
Any idea what this means?

```
17:20:48 ---> Making bundle: validate-vendor (in bundles/1.12.0-dev/validate-vendor)
19:05:26 Username for 'https://github.com': Build timed out (after 120 minutes). Marking the build as failed.
19:05:26 Build timed out (after 120 minutes). Marking the build as aborted.
```

(in https://jenkins.dockerproject.org/job/Docker-PRs-vendor/683/console)

**Comment by thaJeztah** [comment]
I'll restart the vendor CI, it happens sometimes, although it looks a bit like a configuration issue in Jenkins.

This may be a flaky test, noting here, I may make a separate issue for tracking;
https://jenkins.dockerproject.org/job/Docker-PRs/26588/console
```
17:35:40 ----------------------------------------------------------------------
17:35:40 FAIL: docker_cli_run_unix_test.go:783: DockerSuite.TestRunSeccompProfileDenyUnshare
17:35:40 
17:35:40 docker_cli_run_unix_test.go:806:
17:35:40     c.Fatalf("expected unshare with seccomp profile denied to fail, got %s", out)
17:35:40 ... Error: expected unshare with seccomp profile denied to fail, got /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary/docker: Error response from daemon: Untar re-exec error: exit status 1: output: no such file or directory.
17:35:40 See '/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary/docker run --help'.
17:35:40 
```

**Comment by samoht** [comment]
I've fixed the `validate-vendor` error.

**Comment by icecrime** [comment]
Works for me, moving to code review!

**Comment by icecrime** [comment]
Ping @calavera @jfrazelle: thoughts?

**Comment by jfrazelle** [comment]
SGTM:)






On Wed, May 11, 2016 at 3:30 PM -0700, "Arnaud Porterie" <notifications@github.com> wrote:












Ping @calavera @jfrazelle: thoughts?

**Comment by calavera** [comment]
Nice. I see a `_test.go` in the colors library, I'm almost sure the vendoring should have removed it, can you double check?

vendor/src/github.com/fatih/color/color_test.go

Otherwise code LGTM

**Comment by vdemeester** [comment]
Hum indeed seems weird that `vendor` did not remove a `_test.go`...
Otherwise code LGTM too, just wonder if we can/could add some tests ? :angel:

**Comment by thaJeztah** [comment]
I'm a bit "-1" on this feature; it feels a bit "because we can" without a clear use case, but perhaps it's just me (sorry!)

This PR will need changes to the documentation though, so if you can update https://github.com/docker/docker/blob/master/docs/admin/formatting.md to include the new coloring options (and some examples).

**Comment by jfrazelle** [comment]
Ok I'm glad you said it because I was trying to point out its a lot more to maintain for what? Colors? Sure it's pretty and I'm a huge TUI fan but is it worth it. Just didn't want to be Debbie downer.

**Comment by thaJeztah** [comment]
Let's move this back to design review for now

**Comment by thaJeztah** [comment]
Sorry @samoht, we discussed this, and we don't think we really need this, so closing, thanks!!

**Comment by samoht** [comment]
No pb, thanks for having looked at it!

**Pull request closed without merging**
