### PR TITLE
Cleanup handleLegacy logic.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
handleLegacy is a flag to indicate whether daemon is supporting legacy
plugins. When the time comes to remove support for legacy plugins,
flipping this bool is all that will be needed to remove legacy plugin
support. This can be a global variable rather than be embedded in the
manager, thereby cleaning up code.

Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
cc @tiborvass

**Comment by cpuguy83** [comment]
Instead of `legacy` can we use something like `pluginsV1`

**Comment by anusha-ragunathan** [comment]
@cpuguy83 : Renamed to `allowV1PluginsFallback`

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
