### PR TITLE
Vendor strslice change from engine-api

### PR DESCRIPTION
**Pull request by dmcgowan**
Update usage of strslice to use pure slice operations to match type update in engine-api

### CODE REVIEW

**Comment by cpuguy83** [comment]
See failures.

**Comment by dmcgowan** [comment]
Needed for #20565

ping @kencochrane @stevvooe

**Comment by dmcgowan** [comment]
There are some rather obnoxious integration test failures I am looking into. It appears this change may have an effect on the output of `docker inspect` and the tests are very rigid on the output.

**Comment by runcom** [comment]
Yup  (I originally wrote them iirc), what was the issue with the old implementation?

**Comment by kencochrane** [comment]
Thank you @dmcgowan

**Comment by dmcgowan** [comment]
@runcom this PR is only attempting to vendor the change from engine-api. The goal of the original change was to avoid using an unnecessary pointer, see https://github.com/docker/engine-api/pull/97. To me the expected output of the tests don't seem to make much sense, if you can shed any light on why certain values would be expected, for example
```
20:53:24 docker_api_containers_test.go:535:
20:53:24     c.Assert(cmd, checker.Equals, "{[/bin/sh -c touch /test]}", check.Commentf("got wrong Cmd from commit: %q", cmd))
20:53:24 ... obtained string = "/bin/sh -c touch /test"
20:53:24 ... expected string = "{[/bin/sh -c touch /test]}"
```

**Comment by stevvooe** [comment]
> c.Assert(cmd, checker.Equals, "{[/bin/sh -c touch /test]}", ...)

Looks like we are testing the output of `GoString() string`. This is string output for `struct { []string } { []string{"/bin/sh", "-c", "touch", "/test"} }`.

> Yup (I originally wrote them iirc), what was the issue with the old implementation?

The old implementation had a number of consistency and style issues:

1. No need to have a struct pointer to a slice type. A slice header is a pointer.
2. No need to have `Slice()` and `Len()` when the type itself is just a slice.
3. Bazaar `ToString()` function with unclear use case.
4. There was some bazaar behavior in the unit tests. [This case](https://github.com/docker/engine-api/pull/97/files#diff-e03b19ce66bf945ac0fd5bda0891ed90L12) is particularly problematic in that nil would return `""`, breaking the json output and empty returns `null`, which is unexpected.
5. With the rest of the fixes, `MarshalJSON` was completely unnecessary.

All in all, it simply wasn't a well-behaved type. While I attempted to root these problems out in unit testing, it is clear from the integration tests that some of this odd behavior may have propagated to the API. Hopefully, we can clear this up.

IMHO, this should have been addressed during review, but we can't catch 'em all. :hamster:

**Comment by dmcgowan** [comment]
Opened up https://github.com/docker/engine-api/pull/110 to address the poor output. The default output for `Config.Cmd` should be in slice format, which the previously code was not doing (was outputting a structure like `{[/bin/sh -c touch /test]}`), and the updated code was not doing correctly since it implemented `String()` when it should not have.

**Comment by runcom** [comment]
@stevvooe no, nothing has propagated to the api, that output was the original, old, output of the api, and we tried to keep as much as possible backward compatibility.

**Comment by cpuguy83** [comment]
Yes, this was due to how engine (the old api-layer package) was serializing the fields currently utilizing this type.

**Comment by calavera** [comment]
@dmcgowan can you take care of the failing tests?

**Comment by dmcgowan** [comment]
@calavera fixing the tests are not straightforward in this PR since it involves a recently merged change to `engine-api`. I am working with Ken to get the fixed version into #20565. If that PR gets merged with these changes I will just close this PR. I will likely update this PR with the change hacked in to validate the tests but should not merge it. Without a specific branch in `engine-api` with just my change cherry-picked I would need to pull in the no email update to get something merged with a correct vendor hash.

**Comment by calavera** [comment]
@dmcgowan let's centralize in one single PR then. We're not going to merge this anyways with a bunch of tests failing. Do you mind closing this?

**Pull request closed without merging**
