### PR TITLE
Splitting the cli command in to individual files.

### PR DESCRIPTION
**Pull request by moxiegirl**
Splitting the cli command into individual files  -- one for each command.  The current file is close to 3000 lines long.  It is hard to read. Also, hard to manage as nearly every significant change hits some portion of the file. 

image

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by vdemeester** [comment]
Yes ! :heart_eyes:

**Comment by moxiegirl** [comment]
@vdemeester I know! Right? :-D

**Comment by moxiegirl** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
💗 will have a proper look later, but YES!

**Comment by moxiegirl** [comment]
@docker/docs-owners Can I get some eyes on this.  The sooner the better to prevent hideous merge issues.

**Comment by fredlf** [comment]
LGTM, but I think a ToC page might help too. That menu is pretty unwieldy.

**Comment by moxiegirl** [comment]
@fredlf We will be adding the TOC into when we update the documentation layout.  See docker/docs-base project for the list things to be addressed.

**Pull request closed without merging**
