### PR TITLE
Update sfp13/pflag

### LINKED ISSUE #27461: Windows: dockerd --help prints escaped filepaths
On docker/docker master as of today 678ff27f0fd108b1760b3b0b4939d62b7d5eb6be, run dockerd --help on Windows.

Note that all the filepaths are `\\` rather than `\`. Not sure if this is spf13/cobra or docker code doing this - haven't had time to look in more details.

```
Usage:  dockerd [OPTIONS]

A self-sufficient runtime for containers.

Options:
      --api-cors-header string                Set CORS headers in the remote API
      --authorization-plugin value            Authorization plugins to load (default [])
  -b, --bridge string                         Attach containers to a virtual switch
      --cluster-advertise string              Address or interface name to advertise
      --cluster-store string                  URL of the distributed storage backend
      --cluster-store-opt value               Set cluster store options (default map[])
      --config-file string                    Daemon configuration file (default "C:\\ProgramData\\docker\\config\\daemon.json")
  -D, --debug                                 Enable debug mode
      --dns value                             DNS server to use (default [])
      --dns-opt value                         DNS options to use (default [])
      --dns-search value                      DNS search domains to use (default [])
      --exec-opt value                        Runtime execution options (default [])
      --fixed-cidr string                     IPv4 subnet for fixed IPs
  -g, --graph string                          Root of the Docker runtime (default "C:\\ProgramData\\docker")
  -G, --group string                          Users or groups that can access the named pipe
      --help                                  Print usage
  -H, --host value                            Daemon socket(s) to connect to (default [])
      --insecure-registry value               Enable insecure registry communication (default [])
      --label value                           Set key=value labels to the daemon (default [])
      --log-driver string                     Default driver for container logs (default "json-file")
  -l, --log-level string                      Set the logging level (debug, info, warn, error, fatal) (default "info")
      --log-opt value                         Default log driver options for containers (default map[])
      --max-concurrent-downloads int          Set the max concurrent downloads for each pull (default 3)
      --max-concurrent-uploads int            Set the max concurrent uploads for each push (default 5)
      --mtu int                               Set the containers network MTU
  -p, --pidfile string                        Path to use for daemon PID file (default "C:\\ProgramData\\docker.pid")
      --raw-logs                              Full timestamps without ANSI coloring
      --register-service                      Register the service and exit
      --registry-mirror value                 Preferred Docker registry mirror (default [])
      --run-service
      --service-name string                   Set the Windows service name (default "docker")
  -s, --storage-driver string                 Storage driver to use
      --storage-opt value                     Storage driver options (default [])
      --swarm-default-advertise-addr string   Set default address or interface for swarm advertised address
      --tls                                   Use TLS; implied by --tlsverify
      --tlscacert string                      Trust certs signed only by this CA (default "C:\\Users\\Administrator\\.docker\\ca.pem")
      --tlscert string                        Path to TLS certificate file (default "C:\\Users\\Administrator\\.docker\\cert.pem")
      --tlskey string                         Path to TLS key file (default "C:\\Users\\Administrator\\.docker\\key.pem")
      --tlsverify                             Use TLS and verify the remote
      --unregister-service                    Unregister the service and exit
  -v, --version                               Print version information and quit
```

@thaJeztah I'm pretty sure this was OK before the cobra changes, but can't be 100% certain.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #27461  (I think, I don't have a windows host to test it)

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Something still not quite right:

```
PS E:\go\src\github.com\docker\docker> git log -1
commit 2082ef6979122fdee306ec78b17a14e0ae11631e
Author: Daniel Nephin <dnephin@docker.com>
Date:   Tue Oct 18 12:06:55 2016 -0700

    Update sfp13/pflag

    Signed-off-by: Daniel Nephin <dnephin@docker.com>
PS E:\go\src\github.com\docker\docker> dockerd --version
Docker version 1.13.0-dev, build 2082ef6-jhoward-JHOWARD-Z420-Dynamic
PS E:\go\src\github.com\docker\docker> dockerd --help

Usage:  dockerd [OPTIONS]

A self-sufficient runtime for containers.

Options:
      --api-cors-header string                Set CORS headers in the remote API
      --authorization-plugin list             Authorization plugins to load (default [])
  -b, --bridge string                         Attach containers to a virtual switch
      --cluster-advertise string              Address or interface name to advertise
      --cluster-store string                  URL of the distributed storage backend
      --cluster-store-opt map                 Set cluster store options (default map[])
      --config-file string                    Daemon configuration file (default "C:\\ProgramData\\docker\\config\\daemon.json")
  -D, --debug                                 Enable debug mode
      --dns list                              DNS server to use (default [])
      --dns-opt list                          DNS options to use (default [])
      --dns-search list                       DNS search domains to use (default [])
      --exec-opt list                         Runtime execution options (default [])
      --fixed-cidr string                     IPv4 subnet for fixed IPs
  -g, --graph string                          Root of the Docker runtime (default "C:\\ProgramData\\docker")
  -G, --group string                          Users or groups that can access the named pipe
      --help                                  Print usage
  -H, --host list                             Daemon socket(s) to connect to (default [])
      --insecure-registry list                Enable insecure registry communication (default [])
      --label list                            Set key=value labels to the daemon (default [])
      --log-driver string                     Default driver for container logs (default "json-file")
  -l, --log-level string                      Set the logging level (debug, info, warn, error, fatal) (default "info")
      --log-opt map                           Default log driver options for containers (default map[])
      --max-concurrent-downloads int          Set the max concurrent downloads for each pull (default 3)
      --max-concurrent-uploads int            Set the max concurrent uploads for each push (default 5)
      --mtu int                               Set the containers network MTU
  -p, --pidfile string                        Path to use for daemon PID file (default "C:\\ProgramData\\docker.pid")
      --raw-logs                              Full timestamps without ANSI coloring
      --register-service                      Register the service and exit
      --registry-mirror list                  Preferred Docker registry mirror (default [])
      --service-name string                   Set the Windows service name (default "docker")
  -s, --storage-driver string                 Storage driver to use
      --storage-opt list                      Storage driver options (default [])
      --swarm-default-advertise-addr string   Set default address or interface for swarm advertised address
      --tls                                   Use TLS; implied by --tlsverify
      --tlscacert string                      Trust certs signed only by this CA (default "C:\\Users\\Administrator\\.docker\\ca.pem")
      --tlscert string                        Path to TLS certificate file (default "C:\\Users\\Administrator\\.docker\\cert.pem")
      --tlskey string                         Path to TLS key file (default "C:\\Users\\Administrator\\.docker\\key.pem")
      --tlsverify                             Use TLS and verify the remote
      --unregister-service                    Unregister the service and exit
  -v, --version                               Print version information and quit
PS E:\go\src\github.com\docker\docker>
```

**Comment by dnephin** [comment]
Ok, i'll keep looking

**Comment by dnephin** [comment]
@jhowardmsft ok, I fixed the second instance and vendored again. I thinks it's actually fixed this time.

**Comment by tonistiigi** [comment]
LGTM

**Comment by jhowardmsft** [comment]
Ok. Will check in the morning.

**Comment by johnstep** [comment]
I tested this commit, and it looks good:

```
> dockerd --help | findstr :\
      --config-file string                    Daemon configuration file (default "C:\ProgramData\docker\config\daemon.json")
  -g, --graph string                          Root of the Docker runtime (default "C:\ProgramData\docker")
  -p, --pidfile string                        Path to use for daemon PID file (default "C:\ProgramData\docker.pid")
      --tlscacert string                      Trust certs signed only by this CA (default "C:\Users\Administrator\.docker\ca.pem")
      --tlscert string                        Path to TLS certificate file (default "C:\Users\Administrator\.docker\cert.pem")
      --tlskey string                         Path to TLS key file (default "C:\Users\Administrator\.docker\key.pem")
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
