### PR TITLE
Update libcontainer and make it the source of truth on logrus version

### PR DESCRIPTION
**Pull request by tianon**
To help avoid version mismatches between libcontainer and Docker, this updates libcontainer to be the source of truth for which version of logrus the project is using.  This should help avoid potential incompatibilities in the future, too. :+1:

### CODE REVIEW

**Comment by tiborvass** [comment]
@tianon what happens when we merge something else like libcontainer, that also uses logrus?

Also, why doesnt' the PR remove the vendored logrus and use the libcontainer-vendored-logrus?

**Comment by tianon** [comment]
That first question is the million-dollar one, and I don't know that anyone has a good answer to that just yet.  Right now, it's easy to say that libcontainer and Docker must use the same versions of all their dependencies, but if we look to bring in more projects that might get harder to say unilaterally.  The reason we let libcontainer be the source of truth initially for the deps it uses is because it was a simple solution to making sure the two projects stay in sync, and we only excluded `codegangsta/cli` since it was the one dep of libcontainer's that Docker doesn't use.

For your second question, the answer's in the script: (https://github.com/docker/docker/blob/4895a887e2e88699a07ab6fea9113a5ff13d2450/hack/vendor.sh#L73-L76)
```bash
# see src/github.com/docker/libcontainer/update-vendor.sh which is the "source of truth" for libcontainer deps (just like this file)
rm -rf src/github.com/docker/libcontainer/vendor
eval "$(grep '^clone ' src/github.com/docker/libcontainer/update-vendor.sh | grep -v 'github.com/codegangsta/cli')"
```

We _could_ just use `src/github.com/docker/libcontainer/vendor` directly, but then we'd have to tell people not only that they need to add our `vendor` to their `GOPATH`, but also `vendor/src/github.com/docker/libcontainer/vendor`, which is much less discoverable.

**Comment by tiborvass** [comment]
@tianon awesome explanations, thank you very much! Now let's hope janky passes ;)

LGTM

**Comment by calavera** [comment]
LGTM. We'll need to update libcontainer again at some point, but it's not related to this PR, so I'm merging this and we'll deal with that in the future.

**Pull request merged**
