### PR TITLE
Fixes #29901 digest output when using filter

### LINKED ISSUE #29901: Digest not shown when image tag specified
Digests are shown for pushed images with `docker images --digests ...`

```
$ docker push example.com/foo/bar:master
The push refers to a repository [example.com/foo/bar]
9ce98538809e: Layer already exists 
91a8f3990fa4: Layer already exists 
837094365fb4: Layer already exists 
9708155555f8: Layer already exists 
b91611bea4a8: Layer already exists 
148b5a1af9ed: Layer already exists 
011b303988d2: Layer already exists 
master: digest: sha256:164b5fc83e34c2c1d59a430c7b64ecd010902f13c62ba9dcc50efb771c4060b2 size: 12564
                                                                                                                                                              
$ docker images --digests example.com/foo/bar
REPOSITORY                         TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
example.com/foo/bar   master              sha256:164b5fc83e34c2c1d59a430c7b64ecd010902f13c62ba9dcc50efb771c4060b2   d594640ae3af        2 hours ago         63.02 MB
example.com/foo/bar   <none>              sha256:6fd65f7141dc61adeb9f262784b1aca9848866d2d4b68c3a10ecf0aa2d1edef6   1c270a40466d        3 days ago          63.02 MB
example.com/foo/bar   <none>              sha256:0b9e94db5aaedb6f6407778d803e99b0e7dd2e710842611873411717dd51e7b8   c42d40e9c60b        3 days ago          63.02 MB
example.com/foo/bar   <none>              sha256:a5aee68356dba08f0576396d8cbd23cf48630391e00d3197c2b237cbedc8a7a2   998b383b2bcb        2 weeks ago         63.02 MB
example.com/foo/bar   <none>              sha256:076ff9b7dc7cadf2a74d7bf5b7226c0b69ef18e9d29834c2c2e0f3efca019aba   a6df32f2ad19        2 weeks ago         62.08 MB
example.com/foo/bar   <none>              sha256:a8a4411a3f6f89c9215a24adfa5ae3c62d04052c53039fd594002a78118ecf1d   7bc456afeef5        2 weeks ago         62.08 MB
example.com/foo/bar   <none>              sha256:eb448ad5b5d1a6b8d425e90c37056c82c90809ffbf3e6486f601351893fe2785   973e019e1f45        4 weeks ago         429.8 MB
```
But not when you specify an image tag (a bug).
```                                                                                                                                                              
$ docker images --digests example.com/foo/bar:master
REPOSITORY                         TAG                 DIGEST              IMAGE ID            CREATED             SIZE
example.com/foo/bar   master              <none>              d594640ae3af        2 hours ago         63.02 MB
```

```
$ docker version
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 28
 Running: 9
 Paused: 0
 Stopped: 19
Images: 328
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 381
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: active
 NodeID: en2leu93wlp34nkla3yxmyfos
 Is Manager: true
 ClusterID: eujs1t26dcn9io4jfb61y37gh
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.1.100
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: hubnet-1
ID: CG3A:5KVP:ITEW:CF74:GDPB:GLXU:PK5D:5Z6P:PXWD:AKAS:GKWK:D6LV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: j0hnsmith
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

### PR DESCRIPTION
**Pull request by nbaztec**
Fixes #29901

**- What I did**
~Added digest information to the `/images` endpoint when a filter is used.~
Added digest information to the `/images` endpoint when filtering by tag. Additionally a tag is attached when filtering by digest

**- How I did it**
~Aggregate and store digests when filter matches a reference using `FamiliarName` as key (as it's done in the CLI)~
Checking the code deeper made me realize that Tags & Digests are stored within a dictionary as such their iteration order was unrealiable. The new approach utilized the `id` and keeps track of the last Tag & Digests encountered and if a match was made in the process and one or the other is missing, it uses the last tracked values.

**- How to verify it**
~I've added a integration test to go with the changes.~
Integration tests would be added according to the new format

Before:
```
$ docker images --filter="reference=busybox:*"  --digests
REPOSITORY          TAG                 DIGEST              IMAGE ID            CREATED             SIZE
busybox             latest              <none>              efe10ee6727f        2 weeks ago         1.13 MB
busybox             mytag               <none>              efe10ee6727f        2 weeks ago         1.13 MB
```

```
$ docker images --filter="reference=busybox@sha256:2605*"  --digests
REPOSITORY          TAG                 DIGEST              IMAGE ID            CREATED             SIZE
busybox             <none>              sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4              efe10ee6727f        2 weeks ago         1.13 MB
```

After:
```
$ docker images --filter="reference=busybox:*"  --digests
REPOSITORY          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
busybox             latest              sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4   efe10ee6727f        2 weeks ago         1.13 MB
busybox             mytag               sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4   efe10ee6727f        2 weeks ago         1.13 MB
```

```
$ docker images --filter="reference=busybox@sha256:2605*"  --digests
REPOSITORY          TAG                 DIGEST              IMAGE ID            CREATED             SIZE
busybox             latest              sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4              efe10ee6727f        2 weeks ago         1.13 MB
```

**- Description for the changelog**
Fixes missing digest references when requesting images with a tag filter and missing tag names when filter reference was a digest.

**- A picture of a cute animal (not mandatory but encouraged)**
[Mia](http://i.imgur.com/HF8NMCO.jpg?1)

### CODE REVIEW

**Comment by nbaztec** [comment]
Does anyone know if I should just re-run the test to fix the timeout?

**Comment by tophj-ibm** [comment]
The issue is on our CI machines somewhere and not related to this pr. I increased the overall jenkins timeout for that job, so feel free to squash + push.

**Comment by nish-cnx** [comment]
Thanks. I pushed an empty commit and everything's good.

**Comment by nbaztec** [comment]
Thanks. I pushed an empty commit and everything's good.

**Comment by nish-cnx** [comment]
Should I resolve conflicts yet, or perhaps after someone has reviewed this?

**Comment by nbaztec** [comment]
Should I resolve conflicts yet, or perhaps after someone has reviewed this?

**Comment by nbaztec** [comment]
Is there any action required from my end?

**Comment by vdemeester** [comment]
Rebased and squashed

**Comment by olljanat** [comment]
@nbaztec this one needs to be rebased

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by nbaztec** [comment]
Tried rebasing, however cannot seem to run even vanilla tests #38516 
Any ideas? Thanks.

**Comment by olljanat** [comment]
@nbaztec sounds like issue on your machine. Try push changes to here so we can see output from CI.

**Comment by nbaztec** [comment]
Alright I got around to another machine and the tests are working fine. In process I found that the earlier approach was only half solving the problem. I've updated the PR description to include the updated info - now it fixes both digests and tags.

I still need help to write an integration test, since I didn't find much help on how to make `client.ImagePush(...)` work with the new integration tests - couldn't find any existing tests unfortunately.

Any help or direction is highly appreciated.

**Comment by nbaztec** [comment]
Any help guys?

**Comment by nbaztec** [comment]
@olljanat or anyone, I could use some help here on the new testing API.

**Comment by nbaztec** [comment]
Hey guys I'd really appreciate some help here.

**Comment by nbaztec** [comment]
closing due to no communication

**Pull request closed without merging**
