### PR TITLE
New features in mkimage-yum.sh script

### PR DESCRIPTION
**Pull request by FlorinAsavoaie**
Added -g and -p options for the contrib/mkimage-yum.sh script to allow generating images with the dependencies you want. I use this because I generate images where I only need "glibc" with its dependencies or "java-1.8.0-openjdk-headless" and so on. This makes sure that I don't get a lot of bogus packages from the Core group.

Possible usages now include sudo ./mkimage-yum.sh -y yum.conf -g '' -p java-1.8.0-openjdk-headless.

Also changed the "test" at the end to add --rm parameter to docker run so it doesn't leave a junk container and use bash to echo "success" in case you don't get coreutils in your dependencies tree.

Signed-off-by: Florin Asavoaie florin.asavoaie@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jfrazelle @tianon this replaces https://github.com/docker/docker/issues/18381 and https://github.com/docker/docker/pull/17900

**Comment by thaJeztah** [comment]
ping @jfrazelle @tianon could you have a look at this one?

**Comment by tianon** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
