### PR TITLE
Vendoring libnetwork

### PR DESCRIPTION
**Pull request by fcrisciani**
Fix for networkDB garbage collection (PR: https://github.com/docker/libnetwork/pull/1944)
Added extra logs to monitor the netowrkDB status and number of entries per network

Signed-off-by: Flavio Crisciani <flavio.crisciani@docker.com>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
It seems the Jenkins build is stuck. Not sure if there is a way to invoke it?

**Comment by thaJeztah** [comment]
@yongtang yes, we discovered it's not running; waiting for the team in San Francisco to have a look; we can merge these PR's once Jenkins is restored and has run.

**Comment by yongtang** [comment]
Looks like `build/vendor` is stuck in scheduling. Not sure if there is a way to invoke it manually?

**Comment by thaJeztah** [comment]
@fcrisciani can you attempt a rebase/force push?

**Comment by fcrisciani** [comment]
@thaJeztah looks like all the pipelines are green, should I still have to touch this?

**Comment by vieux** [comment]
@fcrisciani we are cutting 17.10 today, do we need to bring any other fix ? /cc @andrewhsu

**Comment by fcrisciani** [comment]
@vieux this is currently top of master, so it's the best we can do at the moment, I will try to shoot with at least another patch in the second RC

**Pull request merged**
