### PR TITLE
Add pgp.mit.edu fallback in Dockerfile

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM (ping @tianon @jfrazelle)!

Hopefully this should help us prevent [those kind of errors in CI](https://jenkins.dockerproject.org/job/Docker-PRs-userns/6149/console).

**Comment by icecrime** [comment]
Oh the irony

```
16:50:13 Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.oMp6Z4MMaC --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 6084F3CF814B57C1CF12EFD515CF4D18AF4F7421
16:50:13 gpg: requesting key AF4F7421 from hkp server p80.pool.sks-keyservers.net
16:52:13 gpg: keyserver timed out
16:52:13 gpg: keyserver receive failed: keyserver error
```

**Comment by tianon** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by aaronlehmann** [comment]
Could we check the keys into the repo and add them from those files? That seems more robust than depending on keyservers.

**Pull request merged**
