### PR TITLE
update containerd binary to v1.5.0

### PR DESCRIPTION
**Pull request by thaJeztah**
Welcome to the v1.5.0 release of containerd!

The sixth major release of containerd includes many stability improvements
and code organization changes to make contribution easier and make future
features cleaner to develop. This includes bringing CRI development into the
main containerd repository and switching to Go modules. This release also
brings support for the Node Resource Interface (NRI).

Highlights
--------------------------------------------------------------------------------

*Project Organization*

- Merge containerd/cri codebase into containerd/containerd
- Move to Go modules
- Remove selinux build tag
- Add json log format output option for daemon log

*Snapshots*

- Add configurable overlayfs path 
- Separate overlay implementation from plugin 
- Native snapshotter configuration and plugin separation 
- Devmapper snapshotter configuration and plugin separation 
- AUFS snapshotter configuration and plugin separation 
- ZFS snapshotter configuration and plugin separation 
- Pass custom snapshot labels when creating snapshot 
- Add platform check for snapshotter support when unpacking 
- Handle loopback mounts 
- Support userxattr mount option for overlay in user namespace 
- ZFS snapshotter implementation of usage 

*Distribution*

- Improve registry response errors 
- Improve image pull performance over HTTP 1.1 
- Registry configuration package 
- Add support for layers compressed with zstd 
- Allow arm64 to fallback to arm (v8, v7, v6, v5)

*Runtime*

- Add annotations to containerd task update API 
- Add logging binary support when terminal is true 
- Runtime support on FreeBSD 

*Windows*

- Implement windowsDiff.Compare to allow outputting OCI images 
- Optimize WCOW snapshotter to commit writable layers as read-only parent layers 
- Optimize LCOW snapshotter use of scratch layers 

*CRI*

- Add NRI injection points cri#1552
- Add support for registry host directory configuration 
- Update privileged containers to use current capabilities instead of known capabilities 
- Add pod annotations to CNI call 
- Enable ocicrypt by default 
- Support PID NamespaceMode_TARGET 

Impactful Client Updates
--------------------------------------------------------------------------------

This release has changes which may affect projects which import containerd.

*Switch to Go modules*

containerd and all containerd sub-repositories are now using Go modules. This
should help make importing easier for handling transitive dependencies. As of
this release, containerd still does not guarantee client library compatibility
for 1.x versions, although best effort is made to minimize impact from changes
to exported Go packages.

*CRI plugin moved to main repository*

With the CRI plugin moving into the main repository, imports under github.com/containerd/cri/
can now be found github.com/containerd/containerd/pkg/cri/.
There are no changes required for end users of CRI.

*Library changes*

oci

The WithAllCapabilities has been removed and replaced with WithAllCurrentCapabilities
and WithAllKnownCapabilities. WithAllKnownCapabilities has similar
functionality to the previous WithAllCapabilities with added support for newer
capabilities. WithAllCurrentCapabilities can be used to give privileged
containers the same set of permissions as the calling process, preventing errors
when privileged containers attempt to get more permissions than given to the
caller.

*Configuration changes*

New registry.config_path for CRI plugin

registry.config_path specifies a directory to look for registry hosts
configuration. When resolving an image name during pull operations, the CRI
plugin will look in the <registry.config_path>/<image hostname>/ directory
for host configuration. An optional hosts.toml file in that directory may be
used to configure which hosts will be used for the pull operation as well
host-specific configurations. Updates under that directory do not require
restarting the containerd daemon.

Enable registry.config_path in the containerd configuration file.

    [plugins."io.containerd.grpc.v1.cri".registry]
       config_path = "/etc/containerd/certs.d"
    Configure registry hosts, such as /etc/containerd/certs.d/docker.io/hosts.toml
    for any image under the docker.io namespace (any image on Docker Hub).

    server = "https://registry-1.docker.io"    

    [host."https://public-mirror.example.com"]
      capabilities = ["pull"]                  
    [host."https://docker-mirror.internal"]
      capabilities = ["pull", "resolve"]
      ca = "docker-mirror.crt"                 

If no hosts.toml configuration exists in the host directory, it will fallback
to check certificate files based on Docker's certificate file
pattern (".crt" files for CA certificates and ".cert"/".key" files for client
certificates).

*Deprecation of registry.mirrors and registry.configs in CRI plugin*

Mirroring and TLS can now be configured using the new registry.config_path
option. Existing configurations may be migrated to new host directory
configuration. These fields are only deprecated with no planned removal,
however, these configurations cannot be used while registry.config_path is
defined.

*Version 1 schema is deprecated*

Version 2 of the containerd configuration toml is recommended format and the
default. Starting this version, a deprecation warning will be logged when
version 1 is used.

To check version, see the version value in the containerd toml configuration.

    version=2

FreeBSD Runtime Support (Experimental)
--------------------------------------------------------------------------------

This release includes changes that allow containerd to run on FreeBSD with a
compatible runtime, such as runj. This
support should be considered experimental and currently there are no official
binary releases for FreeBSD. The runtimes used by containerd are maintained
separately and have their own stability guarantees. The containerd project
strives to be compatible with any runtime which aims to implement containerd's
shim API and OCI runtime specification.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
For reviewers; opening this separate from updating the vendor code, as I wanted to test if everything works without changes in dockerd itself (in case 20.10 is not EOL before containerd 1.4 reaches EOL, this allows us to update docker 20.10 as well)

**Comment by thaJeztah** [comment]
v1.5.0-beta.4 was release, so I should update this one

**Comment by thaJeztah** [comment]
Updated to Beta 4

**Review by AkihiroSuda — APPROVED** [review]

**Review by olljanat — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
@tonistiigi @cpuguy83 @tianon PTAL

**Comment by thaJeztah** [comment]
(not sure if we should cherry-pick already though, as we don't have containerd v1.5.x packages yet for the deb/rpm packages)

**Comment by AkihiroSuda** [comment]
> (not sure if we should cherry-pick already though, as we don't have containerd v1.5.x packages yet for the deb/rpm packages)

containerd 1.4 is expected to reach EOL on November, if Docker 20.10 is expected to be maintained after November, Docker 20.10 should update containerd to 1.5 or later to receive security updates.

**Comment by thaJeztah** [comment]
> Lib update?

Have some branches to update containerd and runc vendoring, but if containerd is keeping its stability guarantee, we should be able to update just the binary (and doing it separate here to verify that)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
