### PR TITLE
Add "--ipv6" flag in IT for network create when using ipv6 subnets

### LINKED ISSUE #21490: Experimental failures on network related tests
We've seen two occurrences of those failures in experimental builds:

```
10:34:28 FAIL: docker_experimental_network_test.go:326: DockerNetworkSuite.TestDockerNetworkIpvlanAddressing
10:34:28 
10:34:28 docker_experimental_network_test.go:340:
10:34:28     c.Assert(out, checker.Contains, "default via 2001:db8:abca::254 dev eth0")
10:34:28 ... obtained string = "" +
10:34:28 ...     "fe80::/64 dev eth0  metric 256 \n" +
10:34:28 ...     "unreachable default dev lo  metric -1  error -101\n" +
10:34:28 ...     "ff00::/8 dev eth0  metric 256 \n" +
10:34:28 ...     "unreachable default dev lo  metric -1  error -101\n"
10:34:28 ... substring string = "default via 2001:db8:abca::254 dev eth0"
```

```
10:34:29 FAIL: docker_experimental_network_test.go:213: DockerNetworkSuite.TestDockerNetworkIpvlanL2MultiSubnet
10:34:29 
10:34:29 docker_experimental_network_test.go:234:
10:34:29     c.Assert(err, check.IsNil)
10:34:29 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8203a6260), Stderr:[]uint8(nil)} ("exit status 1")
```

```
10:34:31 FAIL: docker_experimental_network_test.go:267: DockerNetworkSuite.TestDockerNetworkIpvlanL3MultiSubnet
10:34:31 
10:34:31 docker_experimental_network_test.go:289:
10:34:31     c.Assert(err, check.IsNil)
10:34:31 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc821a86d60), Stderr:[]uint8(nil)} ("exit status 1")
```

Example [here](https://jenkins.dockerproject.org/job/Docker-PRs-experimental/16919/console).

### PR DESCRIPTION
**Pull request by mavenugo**
Fixes #21490 

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by mavenugo** [comment]
This is NOT a flaky failure. it should have failed consistently due to https://github.com/docker/docker/pull/21396. It is possible though that the tests are Skipped due to the Kernel check that these tests depends on (v4.2). Is it possible that some of the Servers are running in kernel v4.2+ while others < 4.2 ?

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by thaJeztah** [comment]
We want to run this on the same fedora 22 server to be sure, so looking at how to do that :smile:

**Comment by thaJeztah** [comment]
alright, seems that that node is already destroyed; so we may have to trust that it's fixed. @mikedougherty will be looking into adding more 4.2+ kernels to CI

**Comment by icecrime** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
