### PR TITLE
Fix broken links in CONTRIBUTING.md

### LINKED ISSUE #17737: broken link in https://github.com/docker/docker/blob/master/CONTRIBUTING.md
I was reading through the contribution documentation, and under the section https://github.com/docker/docker/blob/master/CONTRIBUTING.md#design-and-cleanup-proposals, there's a link to http://docs.docker.com/opensource/project/advanced-contributing/ for advanced contributor details. That link leads to a blank page (not a 404 - just a blank page).

Wanted to let y'all know about the broken link as well as ask where I could find the details on how you're asking folks to present design and refactor concepts to the project.

Thanks!

-joe

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/docker/docker/issues/17737

thanks for reporting, @heckj

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @moxiegirl @SvenDowideit for review

**Comment by heckj** [comment]
awesome guys, thanks!

**Comment by moxiegirl** [comment]
Thanks @thaJeztah for the catch.

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
I'll take your comment as a LGTM as well, @moxiegirl, merging

**Pull request merged**
