### PR TITLE
Bring back support for DOCKER_RAMDISK

### LINKED ISSUE #21631: DOCKER_RAMDISK no longer supported in 1.11.0-rc2
DOCKER_RAMDISK is documented still for a system root running on a ramdisk. Since the 1.11 runc changes this no longer exists, although it is still in the docs. runc does have a mechanism to support this with a NoPivotRoot option, but it is not wired through.

I don't know how many people are using this, it has been raised in various issues. Docker for Mac and Windows are but I am planning to pivot away from this(!).

Have now removed requirements for this there, but other people might be using it possibly. AT least the docs should be updated if we decide to drop support.

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes #21631 

runc changeset: https://github.com/opencontainers/runc/compare/40f4e7...0c1c61
containerd changset: https://github.com/docker/containerd/compare/471bb075214cf0ad85f74f003ca00c7651638c79...07c95162cdcead88dfe4ca0ffb3cea02375ec54d

@justincormack @ibuildthecloud @crosbymichael 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by icecrime** [comment]
Seems we have a problem with gccgo:

```
22:23:58 + git clone https://github.com/opencontainers/runc.git /tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc
22:23:58 Cloning into '/tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc'...
22:24:00 + cd /tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc
22:24:00 + git checkout -q 0c1c615ebd6a15545b6a82ead01d2745ea49b242
22:24:00 + make static BUILDTAGS=seccomp apparmor selinux
22:24:00 CGO_ENABLED=1 go build -tags "seccomp apparmor selinux cgo static_build" -ldflags "-w -extldflags -static -X main.gitCommit=0c1c615ebd6a15545b6a82ead01d2745ea49b242" -o runc .
22:24:00 go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
22:24:08 # github.com/pquerna/ffjson/fflib/v1
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s: Assembler messages:
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:6: Error: no such instruction: `text scanStringSSE(SB),NOSPLIT,$0'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:15: Error: no such instruction: `text ·haveSSE42(SB),NOSPLIT,$0'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:16: Error: too many memory references for `xor'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:21: Error: too many memory references for `mov'
22:24:09 Makefile:21: recipe for target 'static' failed
22:24:09 make: *** [static] Error 2
```

**Comment by icecrime** [comment]
I don't know what's happening on gccgo:

```
22:23:58 + git clone https://github.com/opencontainers/runc.git /tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc
22:23:58 Cloning into '/tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc'...
22:24:00 + cd /tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc
22:24:00 + git checkout -q 0c1c615ebd6a15545b6a82ead01d2745ea49b242
22:24:00 + make static BUILDTAGS=seccomp apparmor selinux
22:24:00 CGO_ENABLED=1 go build -tags "seccomp apparmor selinux cgo static_build" -ldflags "-w -extldflags -static -X main.gitCommit=0c1c615ebd6a15545b6a82ead01d2745ea49b242" -o runc .
22:24:00 go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
22:24:08 # github.com/pquerna/ffjson/fflib/v1
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s: Assembler messages:
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:6: Error: no such instruction: `text scanStringSSE(SB),NOSPLIT,$0'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:15: Error: no such instruction: `text ·haveSSE42(SB),NOSPLIT,$0'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:16: Error: too many memory references for `xor'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:21: Error: too many memory references for `mov'
22:24:09 Makefile:21: recipe for target 'static' failed
22:24:09 make: *** [static] Error 2
```

It builds just fine locally: I'll trigger a rebuild on CI.

**Comment by tonistiigi** [comment]
I added a hack for `gccgo` build that removes the `ffjson` files before building runc and created issue in https://github.com/opencontainers/runtime-spec/issues/362

**Comment by icecrime** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by tiborvass** [comment]
Confirming LGTM

**Comment by stephan-henningsen** [comment]
Hi.  Could someone please clarify what the current status (as of January 2024) of `$DOCKER_RAMDISK` is?  https://github.com/moby/moby/discussions/47035

**Pull request merged**
