### PR TITLE
Merge release v1.9.0

### PR DESCRIPTION
**Pull request by tiborvass**
Ping @docker/core-maintainers

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :wink:

**Comment by thaJeztah** [comment]
LGTM!

**Comment by runcom** [comment]
LGTM

**Comment by calavera** [comment]
slowest build ever

**Comment by tiborvass** [comment]
@calavera just merge, this is not code

**Comment by calavera** [comment]
:boom:

**Pull request merged**
