### PR TITLE
Vendoring libnetwork @13be89d1cf79

### LINKED ISSUE #23669: `docker service create --publish` redirects all traffic to the container port
**Output of `docker version`:**

```
$ sudo docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc1
Storage Driver: devicemapper
 Pool Name: docker-253:0-275997-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 535.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 7.267 GB
 Metadata Space Used: 1.073 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: 96l9q5qrrcs5ciek08xuhgx66
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:9c61b296e3195f2c4642de1d1d7f9d70a26a087dd7e23a2dee8c2dd7a5b73c89
Runtimes: default
Default Runtime: default
Kernel Version: 4.1.13-9.pvops.qubes.x86_64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 650.9 MiB
Name: docker
ID: LL2N:6GYR:3752:5JCP:LPUQ:VDGV:BLLY:IZEP:QGCH:MARS:C2NP:UUKH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Output of `docker info`:**

```
$ sudo docker version
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:53:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:53:41 2016
 OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Linux laptop

**Steps to reproduce the issue:**
```
user@docker:~$ sudo docker service ls
ID  NAME  SCALE  IMAGE  COMMAND
user@docker:~$ nc google.com 80 | head -1
GET /
HTTP/1.0 302 Found
user@docker:~$ sudo docker service create --publish 80:80/tcp nginx
04tkfmxl527maanashuw5jb31
user@docker:~$ sudo docker service ls
ID            NAME            SCALE  IMAGE  COMMAND
04tkfmxl527m  nauseous_tesla  1      nginx  
user@docker:~$ nc google.com 80 | head -1
GET /
<!DOCTYPE html>
```

**Describe the results you received:**

All traffic on port 80 is redirected to the container running the service.

**Describe the results you expected:**

Some subset of all traffic (that bound for the `docker0` network, perhaps?) should be redirected to the container, leaving my traffic to the outside world alone.

**Additional information you deem important (e.g. issue happens only occasionally):**

After creating the service with a published port, here are the firewall rules:

```
$ sudo iptables -L -v -n -t nat
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 4 packets, 278 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   12   723 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    5   281 MASQUERADE  all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match src-type LOCAL
    0     0 MASQUERADE  all  --  *      !docker_gwbridge  172.18.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    0     0 ACCEPT     all  --  *      vif+    0.0.0.0/0            0.0.0.0/0           
    1    52 ACCEPT     all  --  *      lo      0.0.0.0/0            0.0.0.0/0           
  106  6617 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker_gwbridge *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-INGRESS (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    1    52 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.18.0.2:80
    8   515 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

### PR DESCRIPTION
**Pull request by mrjana**
Fixes #23669

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by mrjana** [comment]
@tiborvass @vieux janky failed due to an unrelated tests. Should we rebuild?

**Comment by tiborvass** [comment]
no its fine experimental worked. so it should have enough coverage

**Comment by vdemeester** [comment]
@mrjana and it's a known flakey test : https://github.com/docker/docker/issues/23401

**Pull request merged**
