### PR TITLE
Include apparmor/docker only when it exists.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
@calavera for cherry pick

**Comment by calavera** [comment]
this doesn't need to be in the release, we're cover there.

**Comment by tianon** [comment]
I'm a little confused what this fixes, but :+1: anyhow. :smile:

**Pull request merged**
