### PR TITLE
Add runcom to maintainers.people

### PR DESCRIPTION
**Pull request by runcom**
As suggested I'm adding myself to the maintainers.people :smiley_cat: 

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by tiborvass** [comment]
Proudly LGTM-ing first :P

**Comment by duglin** [comment]
LGTM

**Comment by runcom** [comment]
@tiborvass updated!

**Comment by estesp** [comment]
LGTM!

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM :tada:

**Comment by crosbymichael** [comment]
LGTM

**Comment by runcom** [comment]
Thanks! :smiley:

**Comment by runcom** [comment]
@thaJeztah thanks! :)

**Pull request merged**
