### PR TITLE
Vendor engine-api 0.2

### PR DESCRIPTION
**Pull request by calavera**
Vendor engine-api 0.2.1.You can read the full changelog in https://github.com/docker/engine-api/commit/a234637b37aa55700ad5650be7936a6128a196fc.

It also carries #19014.

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM once janky is happy

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
noooooooooooooooo it needs a rebase

**Comment by jfrazelle** [comment]
howwwwwwwww

**Comment by estesp** [comment]
..and bad timing too--just as Windows passes CI and all green!! :(

**Comment by calavera** [comment]
we might as well merge a new tags, there are a bunch of new things waiting :pensive:

**Comment by calavera** [comment]
I've rebased and bumped the version to fix all remaining issues for the 1.10 milestone.

**Comment by cpuguy83** [comment]
LGTM as long as janky is happy.

**Comment by tiborvass** [comment]
LGTM

**Comment by calavera** [comment]
go janky go!

**Pull request merged**
