### PR TITLE
Fix compose schema id for v3.2

### PR DESCRIPTION
**Pull request by dnephin**
This doesn't seem to break anything right now, but it's good to get it fixed either way.

cc @vdemeester

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM, @dnephin I guess should be cherry-picked in 17.04 ?

**Comment by dnephin** [comment]
Yes, it would be a good idea to cherry-pick for 17.04

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker/pull/31899

**Pull request merged**
