### PR TITLE
Ensure state is destroyed on daemont restart

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
but curious to find out what @LK4D4 find :)

**Comment by LK4D4** [comment]
I think we should merge) 
LGTM

**Comment by jfrazelle** [comment]
testing on lxc for due diligence, then will merge

**Comment by oncletom** [comment]
Hi there, I get this error with the latest ubuntu package.

```bash
$ docker --version
Docker version 1.6.0, build 4749651
```

```bash
$ docker info
Containers: 12
Images: 227
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 251
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-49-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.798 GiB
Name: vm-1189-user
```

Has it been fixed after the latest release or something?

Thanks :-)

**Comment by matevarga** [comment]
I see this with docker 1.10, compose 1.6, Ubuntu 15.10.

**Pull request merged**
