### PR TITLE
Revendor Microsoft/go-winio @ v0.4.5

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Bumps go-winio to the latest

@jstarks FYI

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Rebased after conflict in vendor.conf

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
