### PR TITLE
docker-py: upgrade and fix test script

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

### CODE REVIEW

**Comment by shin-** [comment]
LGTM :+1:

**Comment by shin-** [comment]
but probably good if @tianon can take a look!

**Comment by tianon** [comment]
Assuming the tests pass, this LGTM :+1: :smile:

**Comment by jfrazelle** [comment]
windows seems unreated since integration tests and not docker-py related

**Comment by calavera** [comment]
Experimental is failing with an unrelated issue and janky is green. LGTM, merging.

**Pull request merged**
