### PR TITLE
runconfig/opts: fix compilation issue

### PR DESCRIPTION
**Pull request by LK4D4**
it was introduced with #20566 as a result of merge

### CODE REVIEW

**Comment by icecrime** [comment]
Thanks! LGTM if green

**Comment by duglin** [comment]
LGTM if janky is happy - although he's already unhappy so this can only make it better ;-)

**Comment by tiborvass** [comment]
LGTM

**Comment by AndrewGuenther** [comment]
@LK4D4 I wrote the PR that caused this problem. Would you mind explaining this fix for me so that I understand going forward?

**Comment by calavera** [comment]
@AndrewGuenther another PR merged before caused yours to stop compiling. For some reason we didn't catch it in CI, although we merge each PR changes with the latest master head.

**Pull request merged**
