### PR TITLE
Use windows console mode constants from Azure/go-ansiterm

### PR DESCRIPTION
**Pull request by tklauser**
**- What I did**

Re-vendor github.com/Azure/go-ansiterm in order get the newly added console mode constants and use them in pkg/term instead of the local copies.

**- How I did it**

Get the constants into go-ansiterm via Azure/go-ansiterm#23, re-vendor into moby/moby and manually replace the constants in moby's pkg/term.

**- How to verify it**

All tests still pass.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @jstarks

**Comment by jhowardmsft** [comment]
LGTM

**Comment by jstarks** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks! It's all green, so merging 👍

**Pull request merged**
