### PR TITLE
Vendoring memberlist tag 0.1.0

### PR DESCRIPTION
**Pull request by fcrisciani**
Signed-off-by: Flavio Crisciani <flavio.crisciani@docker.com>

**- What I did**
Update memberlist dependency to the the release v0.1.0
**- How I did it**
vendoring

**- How to verify it**

**- Description for the changelog**

Vendoring memberlist dependency for libnetwork

### CODE REVIEW

**Comment by tophj-ibm** [comment]
@andrewhsu looks like the vendor-pr job / ubuntu-1404 (zfs) (i-0f3662f08d4e97993) is having cleanup issues with the workspace, I've restarted that job twice.

**Comment by andrewhsu** [comment]
@tophj-ibm i'll look into that node

**Comment by andrewhsu** [comment]
@tophj-ibm i've marked it offline so no new jobs can be scheduled on it. i kicked the vendor-pr job again and it turned green.

when i-0f3662f08d4e97993 is done with its workload i'll send it to the bits bin in heaven. perhaps the image needs updating before it is reincarnated. i'll look into it.

**Comment by fcrisciani** [comment]
The powerpc failue is a known race that I'm addressing with moby/moby/pull/32906

**Comment by fcrisciani** [comment]
@sanimej @mavenugo PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by aboch** [comment]
looks good to me too

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
