### PR TITLE
Use spf13/cobra for docker rename

### PR DESCRIPTION
**Pull request by yongtang**
This fix is part of the effort to convert commands to spf13/cobra #23211.

Thif fix coverted command `docker rename` to use spf13/cobra

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮
Need a rebase though 😇

**Comment by yongtang** [comment]
Thanks @vdemeester. The PR has been rebased.

**Comment by thaJeztah** [comment]
Oh, fun, just stumbled on a bug; while testing this. Opening an issue https://github.com/docker/docker/issues/23319

**Comment by thaJeztah** [comment]
unfortunately needs another rebase (but that's kinda expected :smile:)

LGTM after a rebase!

**Comment by yongtang** [comment]
@thaJeztah No problem. Just rebased. Guess will need several round to get all merged.

**Comment by thaJeztah** [comment]
Yes, it's probably all because the `api/client/commands.go`, but shouldn't be a difficult one. Thanks so much @yongtang, you're really helping us out!

**Pull request merged**
