### PR TITLE
Cleanup "autogen/" if we have successful build

### PR DESCRIPTION
**Pull request by tianon**
This way, we only leave around autogenerated files if the build fails (which is reasonable IMO, since that's when you'd need them for debugging the build failure).

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by duglin** [comment]
hmmm so if I manually stop the build (ctrl-c) and then rename stuff in the build, could it mess it?
What if I mess up trying to do renames in the build, could that be an issue?

**Comment by tianon** [comment]
Naw, we took care of that with
https://github.com/docker/docker/blob/master/project/make/.dockerversion#L3

**Comment by duglin** [comment]
Ah right, I forgot 

-Doug

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
