### PR TITLE
Make containers for make build/test based on the Host OS

### PR DESCRIPTION
**Pull request by rmccooey27**
We want to run test suite based on a container from the HOST OS.

Currently this code will support Fedora, Centos, RHEL.

It will still default to Ubuntu if it can not determine the OS.

### CODE REVIEW

**Comment by rhatdan** [comment]
Regan has been working with me as an Intern this Spring.  This is something we would like to get running under CI.

**Comment by thaJeztah** [comment]
Feels odd to put diffs under version control; I can imagine that it's hard to maintain those / keep them in sync.

**Comment by rhatdan** [comment]
@thaJeztah Don't see a real easy way to solve that problem.  I thought patches was better then trying to maintain multiple Dockerfiles.

**Comment by thaJeztah** [comment]
Yeah, both are bad; multiple Dockerfiles might be easier to compare though (diffs of diffs are quite confusing). At minimum I'd expect those files to be not inside the root of the repository, but in a subdirectory.

Perhaps https://github.com/docker/docker/pull/9176 could be useful here, idk.

@tianon is probably the best person to ask here; maybe he has some magic shell trickery up his sleeve.

**Comment by thaJeztah** [comment]
Ah! Just when I thought I was going mad; this popped up; https://github.com/docker/docker/pull/10990/files

I already seemed to remember something like this being worked on; I think this PR could build upon that?

**Comment by rhatdan** [comment]
@thaJeztah I agree moving them into a Distribution directory would be preferable to leaving them in the top level.  I think creating a single patch to convert from apt -> yum and then sed'ing the FROM lines for each arch might also simplify the process.  

Relying on the other pull request, #10990, would be fine, if I saw that one moving forward, but for now it looks like it is stalled also.

One nice thing about using PATCH is that it is something we do every day, after all git and github are based on it...

**Comment by thaJeztah** [comment]
> creating a single patch to convert from apt -> yum and then sed'ing the FROM lines for each arch might also simplify the process.

Yes, with the downside that that will create dependencies between those distros; makes sense in this case, but may not be desired in other cases (just thinking out loud here)

> if I saw that one moving forward, but for now it looks like it is stalled also.

Yeah, blame it on the pending release and activity around the birthday party, but it would be nice to see some traction.

> One nice thing about using PATCH is that it is something we do every day, after all git and github are based on it...

True, but updating patches would involve taking the main Dockerfile, apply the patch, change the resulting Dockerfile and then re-calculate the diff and revert the main Dockerfile (may be an easier workflow). Some of those steps may be required for reviewing.

I think what's needed is;

- A general decision on whether or not this is something the maintainers want
- A generic approach to facilitate variations on the Dockerfile (scripted, multiple Dockerfiles, patches). The approach should be easy to maintain, preferably minimise duplication

Just my personal thoughts here, but I think it would be good to have a decision; having multiple PRs trying to achieve the same thing is a bit of a waste.

**Comment by rhatdan** [comment]
I agree.  Although from the size of their python script,  theirs is much more complicated.

**Comment by thaJeztah** [comment]
@tiborvass @tianon perhaps you could look at this; it overlaps with https://github.com/docker/docker/pull/10990, different approach. Would be good to have a decision, I think (see my previous comment)

**Comment by tianon** [comment]
I definitely prefer the approach in #10990 than patch files in Git (especially since updating the patch file is going to be super fun), and I think being able to easily run the test suite in a different userspace is a better use-case than gccgo is.

However, I'm not convinced that we need 100% (or even 80%) parity for that use-case.

For a concrete example of what I mean, [`Dockerfile.simple`](https://github.com/docker/docker/blob/281b8f67e145f58a3b364ce469ae71e216961e8c/Dockerfile.simple) has very _little_ overlap with [the main `Dockerfile`](https://github.com/docker/docker/blob/281b8f67e145f58a3b364ce469ae71e216961e8c/Dockerfile).  It's essentially just the bare-minimum requirements for building and testing Docker in a Debian base image (which sounds pretty close to what you're trying to accomplish here).

Now that we have `docker build -f`, this can get more interesting, too.  IMO, a good place for these would be something under `contrib/`, like `contrib/integration-base/Dockerfile.debian`, and then the "standard build method" would be something like `docker build -t docker-integration:simple -f contrib/integration-base/Dockerfile.debian .`, which is then used in the ways described in the [following three lines of the head comment in `Dockerfile.simple`](https://github.com/docker/docker/blob/281b8f67e145f58a3b364ce469ae71e216961e8c/Dockerfile.simple#L2-L4).

**Comment by LK4D4** [comment]
I like requested feature. But I'm with @tianon that we should generate ALL dockerfiles and not maintain diffs. Or use something really supersimple like `Dockerfile.simple`.
Let's continue discussion of creating such Dockerfiles in #10990

**Pull request closed without merging**
