### PR TITLE
vendor: update swarmkit to cb6d8131

### PR DESCRIPTION
**Pull request by tonistiigi**
Note: this vendoring is for master only and should not be cherry picked to `v1.12`. Patches for `v1.12` are tracked in a different branch of swarmkit.

@aaronlehmann

### CODE REVIEW

**Comment by LK4D4** [comment]
At least swarm suite passed :+1:

**Comment by tonistiigi** [comment]
@LK4D4 `TestApiSwarmLeaderElection` fail in experimental. I'll see if I can reproduce locally.

**Comment by LK4D4** [comment]
@tonistiigi it might be a real stuff :/ API calls now can fail during reelection because there is no picker in raftproxy.

**Comment by aaronlehmann** [comment]
@LK4D4: Makes sense. Should we add polling in the test? Or should the engine retry API calls a few times before giving up?

**Comment by tonistiigi** [comment]
@aaronlehmann I think this should be handled by swarmkit. Otherwise it makes the API very inconvenient to use. Only swarmkit can make a decision that we need to wait more for the leader to be elected.

**Comment by aaronlehmann** [comment]
@LK4D4: Do we risk re-introducing the "worker takes a long time to reconnect" problem if we make the raft proxy hold the connection until a leader is available? I would think the leader election is fast enough that it wouldn't cause the worker to time out and think the manager it connected to is down. But it's so hard to reason about this...

**Comment by aaronlehmann** [comment]
Played around with this a bit in swarmkit, here are my thoughts: https://github.com/docker/swarmkit/issues/1354#issuecomment-238726387

I'm not convinced we should try to support highly available RPCs during leader failovers for now. It's deceptively difficult. It may be better to just live with the inconvenience of API commands failing when the leader fails, until a new leader is available.

**Comment by tonistiigi** [comment]
@LK4D4 @aaronlehmann This includes https://github.com/docker/swarmkit/pull/1359 now and is green(ish)

**Comment by aaronlehmann** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
