### PR TITLE
Move Erik to alumni

### PR DESCRIPTION
**Pull request by erikh**
Hi folks,

It was great contributing to this project -- and I expect to in the future -- but I don't believe I have the time and familiarity with the code anymore to continue as a maintainer. Sebastiaan put together this very flattering patch and I'm submitting it formally to ensure everyone knows I approve it.

Thank you for the time I had to spend on it, it was (and still is) a great project to be a part of. I'm sure I'll keep in contact with most of you through my other projects, so no need for farewells!

Signed-off-by: Sebastiaan van Stijn github@gone.nl

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @erikh! Don't be a stranger, and it was a pleasure having you as a maintainer, thank you!

LGTM

**Comment by erikh** [comment]
Merry Christmas!

**Comment by calavera** [comment]
Thanks for everything @erikh! :gift_heart:

**Comment by calavera** [comment]
LGTM

**Pull request merged**
