### PR TITLE
1.13.0-rc2 cherry-picks : part 2

### PR DESCRIPTION
**Pull request by vieux**
- [#27631](https://github.com/docker/docker/pull/27631)
  - d075b83dd6e5bbd4470400d44889ca71cf9dbd59 allow node update API to receive node name and id prefix
- [#28272](https://github.com/docker/docker/pull/28272)
  - 7c29f5beed19b55ac8f14880752d4825ba23eccf Windows: Perf: Use sequential file access
- [#28316](https://github.com/docker/docker/pull/28316)
  - d7257640835abe5e7c08235b3fd974e319dbd7b6 Update docs for `docker info` for most recent changes
- [#28346](https://github.com/docker/docker/pull/28346)
  - 9dabde5b01c50cbac3da20943ba3c4498a7516c4 Fix missing versions in example requests of api docs
- [#28420](https://github.com/docker/docker/pull/28420)
  - b1a91dcc0f0ba0bbad1d70943b423464b500657f update tini to a87614212b3a51a9cad57ff7989103a841546745
- [#28440](https://github.com/docker/docker/pull/28440)
  - b9b8d8b364a14b6f827c9db94f651dda372ed253 Don't validate platform-dep tmpfs opts on client
- [#28467](https://github.com/docker/docker/pull/28467)
  - d63dc45f0b34be6e25592ea6322a462497a89507 Remove redundant 'if' statement
- [#28468](https://github.com/docker/docker/pull/28468)
  - 70fdbff5f077e01897b8d284d1e29de64f8041eb Add zsh completion for 'docker system df'
- [#28475](https://github.com/docker/docker/pull/28475)
  - 947464e2f1a8df9addce4911f4c1264b2c606543 Update stats cli reference documentation
- [#27749](https://github.com/docker/docker/pull/27749)
  - a524c135dce6ce39ccbca68fdd38f5b575ad82f4 Edits to plugin docs after building authz plugin
- [#28100](https://github.com/docker/docker/pull/28100)
  - 7ffb4ad81ab8e4400b0a588552ffb99dc55d13aa Disable v1 protocol for the default registry
- [#28457](https://github.com/docker/docker/pull/28457)
  - a8139460ff98b081c06ecf28a821d6f456d9a079 explicitly show plugins as unsupported on !linux
- [#28501](https://github.com/docker/docker/pull/28501)
  - 5b0a52f7dcd04017a1def7326f8adbb8547ebe89 Skip cli initialization for daemon command
- [#28586](https://github.com/docker/docker/pull/28586)
  - 271b1f27563b18a125b89d2d2629246213dbfd96 fix infinite recursion
- [#28584](https://github.com/docker/docker/pull/28584)
  - 228ee16df3d738efaf001309370b26561c49edd6 Fix check config script on 4.8 kernels
- [#28580](https://github.com/docker/docker/pull/28580)
  - 1f039a66ac55c937f5dfa281a04009626d191f83 fix typos
- [#28560](https://github.com/docker/docker/pull/28560)
  - 2d08a764211035ec93aa3a97afb2baff074103da fix a typo
- [#28557](https://github.com/docker/docker/pull/28557)
  - ce33d4e1c3d2ca3672a4d7e8e2b553de842fef30 Update Tini to fix photon build-rpm compilation errors
- [#28554](https://github.com/docker/docker/pull/28554)
  - bf95472105e5dad55314cfff599abea5b81b134a refactor help func in CLI
- [#28552](https://github.com/docker/docker/pull/28552)
  - 158bb9bbd588aa03a3567f40b367025ccbd81fb3 3a0554585177a55802377423bb4529d305b4566f Fix use of cap in MultiReadSeeker; possible data corruption bug.
- [#28551](https://github.com/docker/docker/pull/28551)
  - 4130eb24e9e844bcfa9a336a7fef7698ad0e5c9f Reduce spew data dumped
- [#28533](https://github.com/docker/docker/pull/28533)
  - 972a246c671b52786a5e57743babfcf7b5b5ae99 judge manager before unlocking
- [#28530](https://github.com/docker/docker/pull/28530)
  - 3484e02590117d175d9c1ab24c583390b4e94a55 api/server/httputils: ensure consistent status code
- [#28523](https://github.com/docker/docker/pull/28523)
  - b6857e91c1625695abbf5897e13f688028880c33 Fix crash caused by `docker service inspect --pretty`
- [#28521](https://github.com/docker/docker/pull/28521)
  - d8b8b129948ef8586f5b2f576533952419e302f2 api: Remove omitempty tag on Parallelism
- [#28512](https://github.com/docker/docker/pull/28512)
  - 1144f8f1d4b1fd2bbf1f41bf5dad8d929d0dc06e Cleanup after plugin install.
- [#28505](https://github.com/docker/docker/pull/28505)
  - 7e03ce3f13baa61ce5547574163059b712b37025 Windows: Revert 27884
- [#28477](https://github.com/docker/docker/pull/28477)
  - a0d7b34d9cb0876f8583a6e15d1b1aaab8d2b9ab Update `images` cli reference with reference filter
- [#28462](https://github.com/docker/docker/pull/28462)
  - 89b123473774248fc3a0356dd3ce5b116cc69b29 Fix deadlock on cancelling healthcheck
- [#28458](https://github.com/docker/docker/pull/28458)
  - d22ac2f3a0de8e2ff6da8f1787e3ac3ac7438f17 Fix error messages for `--cpus` from daemon
- [#28447](https://github.com/docker/docker/pull/28447)
  - d910781c66262af95646d7a0b564d254afc4af8f dc1b6341b98c3d009342a878119f683bfe14b471 Using distribution reference pkg (pin image by digest)
- [#28415](https://github.com/docker/docker/pull/28415)
  - a3c4ab9b657018cf6fc33e70a44c790563c16043 Windows: Allow `USER` in builder
- [#28354](https://github.com/docker/docker/pull/28354)
  - 039aca05c2eae8a06dc16ff97110539feb44d13b Change the docker-tag usage text to be clearer
- [#28347](https://github.com/docker/docker/pull/28347)
  - 312cc7eebd326cc500e5742115d1e92e94ff60ee Use `map[string]bool` for `preProcessor` to ignore unknown fields
- [#28532](https://github.com/docker/docker/pull/28532)
  - 1d90d7604881e29b71819af9c092d565513aeeec api/server/httputils: service unavailable for disable swarm
- [#28565](https://github.com/docker/docker/pull/28565)
  - aff99136b44c0a3d9ef381afd38a5cd05328ddc6 Fix cfs period calculation
- [#28367](https://github.com/docker/docker/pull/28367)
  - 19e2c9177a111758e304ad9dbd0835cddbd840ab Fix a comment error
- [#28290](https://github.com/docker/docker/pull/28290)
  - 19bd1cee236b85d2e24fdf49d6181edb7e1f7f17 fix "fatal error: concurrent map read and map write" bugs when we concurrently execute lots of delete volumes and create or list volumes tasks
- [#28421](https://github.com/docker/docker/pull/28421)
  - 948e60691e523022f88e7f8129f02106a0f8826c Return warnings from service create/update when digest pinning fails
- [#28538](https://github.com/docker/docker/pull/28538)
  - ace786e9d517777473bd431e65d6c464d82e4f65 Fix several issues with `go vet` and `gofmt -s`
- [#28590](https://github.com/docker/docker/pull/28590)
  - 8b1aeb22febdb60e29b4d1ee52c6d4139af1cd62 Update containerd & runc
- [#28603](https://github.com/docker/docker/pull/28603)
  - f1b9df91722a229fd0cefd7a0868933b6b811544 swap position of "host" and "ip"
- [#28610](https://github.com/docker/docker/pull/28610)
  - 9f348d5625996faf7a0855b8eb52cdd4def3958e fix gofmt in master
- [#28613](https://github.com/docker/docker/pull/28613)
  - 79a891efb7365e4f7d129a0142e66d2852781608 skip api/types/container/ (like golint) and fix one pkg

- [#28438](https://github.com/docker/docker/pull/28438)
  - 5f81cf11f648835bd0182d297d265a4da6c469dd Use Container.Config.Shell instead of hardcoded for healthcheck. It make the code a little cleaner and more future/usage proof.
- [#28524](https://github.com/docker/docker/pull/28524)
  - 3976a33c1a578827da3726bec3927cc058fe326a router: Return explicit error rather than 404 for experimental.
- [#28537](https://github.com/docker/docker/pull/28537)
  - 9551dd03cfad2ec0a00d89c2177fb7b45b6ad885 Fix the typo
- [#28561](https://github.com/docker/docker/pull/28561)
  - 98bb08fe38d6faabb639b31ea34aac2ea65f519d error on cli when trying to use experimental feature with non experimental daemon
- [#28605](https://github.com/docker/docker/pull/28605)
  - 020b051dfb92edcb1e43cee77c881dd3e15481c0 Allow graphdriver plugins to use v2
- [#28611](https://github.com/docker/docker/pull/28611)
  - 9c559e6d0b7190b4698de59e692a047beba017fd fix a few golint errors
- [#28451](https://github.com/docker/docker/pull/28451)
  - 2c38d43eb5276a82f8e076058506468e0d5a2f9f Add HostConfig.Tmpfs to docs for container creation remote API

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by aluzzardi** [comment]
LGTM

**Comment by thaJeztah** [comment]
Couple of remaining golint errors;

```
02:58:04 cmd/docker/docker.go:84:3: error strings should not end with punctuation
```

Fixed by https://github.com/docker/docker/pull/28611

```
02:58:04 daemon/cluster/cluster.go:73:1: comment on exported var ErrSwarmCertificatesExpired should be of the form "ErrSwarmCertificatesExpired ..."
```

Fixed by https://github.com/docker/docker/pull/28537

```
02:58:04 daemon/cluster/cluster.go:1058:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
02:58:04 daemon/info_unix.go:16:1: exported method Daemon.FillPlatformInfo should have comment or be unexpected
02:58:04 daemon/info_windows.go:8:1: exported method Daemon.FillPlatformInfo should have comment or be unexpected
02:58:04 plugin/backend_unsupported.go:14:5: exported var ErrNotSupported should have comment or be unexported
02:58:04 volume/local/local.go:272:37: error strings should not end with punctuation
```
Fixed by https://github.com/docker/docker/pull/28611

**Comment by vieux** [comment]
@thaJeztah PR updated. it's now :green_heart: 

ping @docker/core-engine-maintainers

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
