### PR TITLE
Correct the message of ErrorCodeNoSuchContainer to "No such container"

### PR DESCRIPTION
**Pull request by wenchma**
Fixes issue #18424

Signed-off-by: Wen Cheng Ma wenchma@cn.ibm.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! sgtm, wondering if this should be considered an API change (I think this message is returned by the API); are people actually checking the status message?

**Comment by runcom** [comment]
I don't think it will be an API change, LGTM btw

**Comment by thaJeztah** [comment]
Yes, changes LGTM too

(userns failed, but doesn't look related, so triggered Janky)

**Comment by wenchma** [comment]
userns  build timeout

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
Don't think docs changes are needed, so LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
