### PR TITLE
Use checker assert for docker_cli_daemon_test.go

### PR DESCRIPTION
**Pull request by vdemeester**
Part of #16756 🐙

Uses some of the new checkers recently vendored 🐚. It's a long file (~1400 lines), and I'm a little bit worried that github 🐌 won't show the diff :scream_cat:.

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by vdemeester** [comment]
Hum yay too big to be shown in the github diff.. gonna be hard to review.. Maybe I should split the file into several (that makes sense together).

**Comment by vdemeester** [comment]
Splitted the commit to make it a little less painful to review.. I'll squash then once the review is done :wink: 

/ping @cpuguy83 @runcom @calavera @HuKeping

**Comment by cpuguy83** [comment]
This one needs a rebase :(

**Comment by HuKeping** [comment]
How can this happen that the github diff gone here.. #17700 has more lines but everything seems fine.

**Comment by vdemeester** [comment]
@HuKeping there is a limit of showing diff on a single file.. All the diff of this PR are on one file, that was not the case for #17700 :stuck_out_tongue_closed_eyes:.

**Comment by vdemeester** [comment]
@cpuguy83 rebased :wink:

**Comment by thaJeztah** [comment]
ping @vdemeester needs another rebase :'(

**Comment by LK4D4** [comment]
@vdemeester need rebase, tests failed.

**Comment by vdemeester** [comment]
arg.. I'll reopen it when fixed :p

**Comment by thaJeztah** [comment]
Are you still working on this one, @vdemeester? Perhaps cutting it into smaller PRs of that makes it easier?

**Pull request closed without merging**
