### PR TITLE
Replace two array with a map type, make it easier to understand.

### PR DESCRIPTION
**Pull request by miaoyq**
Replace two array with a map type, make it easier to understand.

Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

### CODE REVIEW

**Comment by thaJeztah** [comment]
Will this change result in a change in behavior? Given that arrays are ordered, but map ordering is randomized in Go

ping @mavenugo PTAL

**Comment by miaoyq** [comment]
Thanks @thaJeztah  for the review.
I think the networks are sequential independent, because `container.NetworkSettings.Networks' also is a map.

**Comment by thaJeztah** [comment]
Makes sense. SGTM

**Comment by aaronlehmann** [comment]
Can you please add a comment saying that the intermediate map is necessary because `connectToNetwork` modifies `container.NetworkSettings.Networks`? I was confused by this at first.

The code change looks okay.

**Comment by miaoyq** [comment]
Thanks a lot! @aaronlehmann @LK4D4 
I have added comment. PTAL

**Comment by LK4D4** [comment]
LGTM

**Comment by aboch** [comment]
@miaoyq This may change the order with which the container connects to each network.
I can't recollect now if there currently are any assumption or requirements about that order in the code.
Will check and let you know.

**Comment by miaoyq** [comment]
@aboch   Thanks!  Very willing to understand the details.  :smiley:

**Comment by thaJeztah** [comment]
Thanks for looking @aboch, yes, I had the same concern, but @miaoyq explained 👍 

LGTM

**Pull request merged**
