### PR TITLE
Allow images built for P and Z to be used for testing

### PR DESCRIPTION
**Pull request by brahmaroutu**
This PR will convert the Power and Z specific images required to run integration tests to proper names so that the tests can use them to run properly.

Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by brahmaroutu** [comment]
ping @tianon, this along with https://github.com/docker/docker/pull/14600 should get the integration tests work on Power and Z architectures.

**Comment by LK4D4** [comment]
ping @tianon

**Comment by thaJeztah** [comment]
ping @tianon any change you could review this?

**Comment by tianon** [comment]
I still think this is premature; we're not even properly testing compilation for these platforms yet, or verifying their client binaries the same way we already do for Windows, which I think is a much simpler first step without starting to prescribe (by our own official use) a particular naming scheme for non-linux-amd64 images.

**Comment by cpuguy83** [comment]
Closing per @tianon's comment.
We can re-open at a later date once we're ready to support this kind of thing.

Do we have an open issue detailing the todo items for this?

**Pull request closed without merging**
