### PR TITLE
closes #8945

### LINKED ISSUE #8945: [DOC] Haskell Docker API tba.
I just found this today; 
 Docker Remote API wrapper for Haskell - a Work in progress ; https://github.com/denibertovic/docker-hs 
The doc page said to add a bug if new API's were discovered :).
https://docs.docker.com/reference/api/remote_api_client_libraries/

### PR DESCRIPTION
**Pull request by emirozer**
apologies for forgetting the signing

### CODE REVIEW

**Comment by moxiegirl** [comment]
LGTM

ping @docker/docs-owners

**Comment by thaJeztah** [comment]
The change itself LGTM, but the linked project clearly mentions it's a work-in-progress and the last activity/commit is 4 months ago

Perhaps change the "Active" state to something else?

**Comment by moxiegirl** [comment]
@thaJeztah I checked the destination page; there is a disclaimer at the top and existing content on the page that shows other outdated projects.

http://docs.docker.com/reference/api/remote_api_client_libraries/

A WIP that is slow seems within this range

**Comment by thaJeztah** [comment]
Alright, LGTM :)

Linked issue https://github.com/docker/docker/issues/8945 must be closed manually (top comment misses the "closes" line, and can't edit on mobile)

**Comment by thaJeztah** [comment]
Thanks, @emirozer!

**Comment by emirozer** [comment]
@thaJeztah No problem at all! wanted to start contributing from lower exp level :)

**Comment by duglin** [comment]
@emirozer please remember the "Closes #..." in your initial comment and please include some descriptive text in the title - just so people don't need to jump around to the original issue just to remember what 8945 was about.

**Comment by thaJeztah** [comment]
@duglin surprisingly Github closed automatically in this case (I thought it ignored the title, but apparently not?)

**Comment by emirozer** [comment]
@duglin good point ! ty,

**Comment by moxiegirl** [comment]
The "closes" directive was in his title. :-D

**Comment by thaJeztah** [comment]
@moxiegirl yes, but I have seen PRs where that didn't work (but it might be they didn't use a `#` before the number)

**Pull request merged**
