### PR TITLE
Fixed file hashing for LCOW.

### PR DESCRIPTION
**Pull request by notanaverageman**
**- What I did**
While file hashes are being generated, they are searched on the host filesystem. For LCOW this always returns a file not found error and the file name is used instead of the SHA hash. This was causing wrong cache uses like #36793. I have fixed the hashing method for LCOW.

**- How I did it**
For LCOW, instead of trying to read the file from the host filesystem, use the container filesystem.

**- How to verify it**
#36793 has the necessary steps.

**- Description for the changelog**

Fixed file hash values for LCOW that caused wrong usage of layer caches.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jhowardmsft @johnstep PTAL

**Comment by cpuguy83** [comment]
Seems like this should be handled lower down in the abstraction, as is this is pretty sloppy.

**Comment by yusuf-gunaydin** [comment]
I am not familiar with this repository to make the abstraction and also do not have time for it. I have written a comment on #36793. If someone tries to fix this, he can use the information there. So, closing this.

**Comment by jhowardmsft** [comment]
I think the right/cleaner fix is: 

```
	fi, err := c.root.Lstat(fullPath)
	if err != nil {
		// Backwards compatibility: a missing file returns a path as hash.
		// This is reached in the case of a broken symlink.
		return relPath, nil
	}
```

which takes advantage of containerd\continuity\driver abstraction. 

I'll test this and put a replacement PR in if so.

**Comment by cpuguy83** [comment]
@yusuf-gunaydin understood, thanks for the contribution!

**Pull request closed without merging**
