### PR TITLE
Change mount point propogation to default to slave

### PR DESCRIPTION
**Pull request by rhatdan**
As an admin I would expect that if I volume mount a partition into a container, and then later add a mount point to the volume, it will show up in the container.

Docker-DCO-1.1-Signed-off-by: Dan Walsh dwalsh@redhat.com (github: rhatdan)

### CODE REVIEW

**Comment by rhatdan** [comment]
@alexlarsson Do you remember why we went with the default of MS_PRIVATE instead of MS_SLAVE?

**Comment by alexlarsson** [comment]
Wasn't the whole point of making this private to avoid performance issues with propagating mounts into this namespace due to the kernel being shit? I'm not 100% sure here, but this may be causing a performance regression wrt that.

**Comment by unclejack** [comment]
There's an issue related to this problem: https://github.com/docker/docker/issues/2891

**Comment by alexlarsson** [comment]
I think the issue was that if you have a 1000 containers running. Then when you start a new one it will create a new mount in the global namespace. This will propagate into all the running containers, as it may possibly be wanted there. However, in practice /var/docker is not available in those containers so the propagation is a no-op. However, the kernel code for this was pretty dumb, so it only noticed it was a no-op after a lot of work (O(n) in the number of mounts i think) had been done, and this for each sub-namespace. 

The end result was that to start a container we did O(n^2) work (n==number of running containers). So starting n new containers was O(n^3), and really slow. Marking the devicemapper mound directory private avoided the dumbness above by avoiding propagation early in the operation.

However, I question the above patch. Yes, the root of the container is MS_PRIVATE, but that does not necessarily hold for a volume that has been bind-mounted into the container. That bind mount should be MS_SLAVE.
I doubt the sysadmin is going to mount things inside "/var/docker/devmapper/...".

**Comment by rhatdan** [comment]
I guess I have two questions, should we optimize for the 1000s of containers use case versus the common 10's of containers use case.  Not having mount propogation into a container, is very confusing.
Now if we could get just the Volumes mounted into the container to propogate and not /var/lib/docker/devicemapper would that solve the problem?

**Comment by unclejack** [comment]
@rhatdan There are certainly Docker users and Docke deployments out there which require thousands of containers. I know there are people who are having problems because of the 1024 ports limit for the default Linux bridge.

**Comment by rhatdan** [comment]
@unclejack Understood, (openshift) for one.  We need a mechanism to change the default behaviour preferable though the daemon or via docker run commands.

**Comment by alexlarsson** [comment]
@rhatdan I don't necessarily disagree, but I don't see how the /var/lib/docker/devicemapper directory being private has to do with the volumes not being propagated. Surely the volume bind-mounts themselves are mounted as slave, and it should not matter that the root of the container is private?

**Comment by rhatdan** [comment]
I don't believe we do this now.  What I was seeing even in a privileged container, was when I run

docker run -ti -v /usr:/usr fedora /bin/sh
# mount --make-rslave /usr

Outside container
mount -o bind /tmp /usr/share

/usr/share would still not propagate.  

When I changed libcontainer to mount "/" SLAVE and the /var/lib/docker/devmapper to SLAVE, it worked.

Propogation was failing with devmapper mounted SLAVE but libcontainer "/" mounted PRIVATE.

It only worked when "/" was also mounted SLAVE.

I have not tried again with with /var/lib/devmapper as PRIVATE.

**Comment by alexlarsson** [comment]
Can you try "/" as slave and devmapper as private? Having devmapper as private is what fixed the performance issue i think.

**Comment by rhatdan** [comment]
Ok just tried an experiment with just the /var/lib/docker/devmapper mounted PRIVATE and it still worked.

**Comment by rhatdan** [comment]
We are cutting a build with this change and will have performance team check if there is any performance degradation.  thanks @alexlarsson

**Comment by LK4D4** [comment]
@rhatdan Any news from your performance team?

**Comment by rhatdan** [comment]
They found no difference, I believe.  @jerms can you confirm.

**Comment by cpuguy83** [comment]
ping what do we want to do with this?

**Comment by rhatdan** [comment]
I think the libcontainer changes which got merged were all we needed.  I will close this for now, and reopen if I find any problems.

**Pull request closed without merging**
