### PR TITLE
Fixing panic when sandbox is nil

### PR DESCRIPTION
**Pull request by pradipd**
Signed-off-by: Pradip Dhara <pradipd@microsoft.com>

**- What I did**
Fix panic in deleteLoadBalancerSandbox during dockere2e/tests
In the dockere2e/tests, there are multiple worker threads in reconcileTaskState deleting the network at the same time.

**- How I did it**
Reran the tests.  The tests no longer panic.  
Note that the tests still don't pass, but, that is not the concern here.

**- How to verify it**
Create a swarm with at least 2 nodes.
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock dockere2e/tests

**- Description for the changelog**
Fix panic in deleteLoadBalancerSandbox during dockere2e/tests

**- A picture of a cute animal (not mandatory but encouraged)**
Imagine a kitten playing with some yarn.

### CODE REVIEW

**Comment by pradipd** [comment]
@dperny @vieux FYI.  Here is the PR for the panic in dockere2e/tests

**Comment by dperny** [comment]
It is worthwhile to track down the root cause of multiple concurrent attempts to delete this network? Otherwise, if this fixes the issue (and doesn't result in a total failure to delete the network and leak resources), LGTM (but I am not a maintainer).

**Comment by pradipd** [comment]
I think that is a question for the maintainer.  
Do we expect multiple requests to delete the network?
If yes,  do we expect there to be multiple threads trying to delete the network at the same time?

**Comment by andrewhsu** [comment]
Looks like the panic was introduced in #34674

https://github.com/moby/moby/pull/34674/files#diff-470d751551967a09e51effadaf1d5cf4

**Comment by dperny** [comment]
Oh I see, you mean that the e2e tests we run call delete multiple times concurrent, and the daemon attempts to service all of those calls at once. Gotcha, never mind.

**Comment by vieux** [comment]
LGTM, if experimental passes, it means janky is flacky 

PTAL @tonistiigi @tiborvass

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
