### PR TITLE
#14474 skip DockerSuite.TestRunCapAddCHOWN on lxc

### LINKED ISSUE #14475: skip DockerSuite.TestRunCapAddCHOWN on lxc
create a patch to skip that test on lxc

### PR DESCRIPTION
**Pull request by azurezk**
To skip DockerSuite.TestRunCapAddCHOWN, I add a test requirement that return false in that test case
Fixes #14475 

Signed-off-by: Zhang Kun zkazure@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Sorry, this isn't right.
A plain old skip would suffice if we wanted to always skip (which we don't).
Here this should be `testRequires(c, NativeExecDriver)`

**Comment by azurezk** [comment]
Thank you! I misunderstood. Already fix it. :)

**Comment by runcom** [comment]
@azurezk sorry but seems like you pulled master instead of doing a rebase :/ and commit isn't signed, ping me on irc if you need any help with this :)

**Comment by azurezk** [comment]
Thank you! I' ve changed the commit and signed :)

**Comment by jfrazelle** [comment]
can you squash the commit please into one

**Comment by jfrazelle** [comment]
actually I am going to carry your commit in my patch for something else for lxc if thats ok

**Comment by jfrazelle** [comment]
carried here https://github.com/docker/docker/pull/14860 thanks!

**Pull request closed without merging**
