### PR TITLE
docs: update docs for API history

### PR DESCRIPTION
**Pull request by HuKeping**
The response of hitory API includes more information now.

Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @HuKeping!

I just checked and docker 1.7 (API v1.19) also outputs in this format; can you apply these changes to the 1.19 API document as well (perhaps older versions as well? Do we know which Docker version this change was introduced in?)

**Comment by HuKeping** [comment]
I'll check that

**Comment by HuKeping** [comment]
@thaJeztah It was commit bf57339527f153b502a6443a495824a40768e39f upstream. that introduce the `Comment` field, the other are always there but the docs does not shown them.

**Comment by thaJeztah** [comment]
LGTM, thanks @HuKeping!

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
