### PR TITLE
fix typo: transtions->transitions

### PR DESCRIPTION
**Pull request by scf0920**
Signed-off-by: Chengfei Shang <cfshang@alauda.io>

- What I did
fix typos
- How I did it
transtions->transitions

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! The change itself looks good, but looking at the commit message;

```
fix typo: transtions->transitions

Signed-off-by: cfshang <cfshang@alauda.io>
```


@scf0920 could you use your [real name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work) in the sign-off? Otherwise we'll have to add another entry in the `.mailmap` to map your alias to your real name 😅

**Comment by scf0920** [comment]
@thaJeztah Sorry...I updated my real name just now..

**Comment by thaJeztah** [comment]
@scf0920 oh! Can you update the actual commit message? Updating the PR description won't update the actual commit 😅 

To amend your commit; use `git commit --amend`, then edit the sign-off and save changes. After that _force push_ your changes (`git push -f`); doing so will automatically update the PR

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
