### PR TITLE
Delete meaningless subarch

### PR DESCRIPTION
**Pull request by wanghuaiqing2010**
Signed-off-by: wanghuaiqing <wanghuaiqing@loongson.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Could you provide more details about the reason for this change?

**Comment by wanghuaiqing2010** [comment]
I think that it is meaningless to add SubArches to newConfig.Architectures.
When docker is running on the system that has only one arch,
why do we add other arches to config.

**Comment by wanghuaiqing2010** [comment]
I read the link below carefully.
https://github.com/moby/moby/pull/24510

The code author explains the following reasons.

"I meant that the json file/data structure should always contain a map from the system architecture to the architectures that should be allowed, so that you can always use a single json file regardless of the target architecture, then at runtime it picks the architecture that you are running on and selects the target allowed architectures from the map. Am I being clear, not explaining very well? So the json file should still contain the complete map. The aim is that you can always use the same json file for every architecture, otherwise when we put it in /etc/docker/seccomp_default.json it would need to vary by architecture, which is horrible for packaging..."


I think that the field archmap is only meaningful to the editor of the file profile.json.
She made the editor aware of a mapping relationship that the system calls of one arch are allowed for another arch.

But subarch is meaningless for a running docker.
Only current arch is meaningful for a running docker.
Do you agree with me?

**Comment by AkihiroSuda** [comment]
Meaningful, e.g. i386 binary on amd64.

**Pull request closed without merging**
