### PR TITLE
Add missing error return for plugin creation.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Signed-off-by: Anusha Ragunathan <anusha.ragunathan@docker.com>

### CODE REVIEW

**Comment by cpuguy83** [comment]
Can we add a unit test for this?
The executor should be able to be stubbed out easily with something that just always returns an error.

**Comment by anusha-ragunathan** [comment]
@cpuguy83 : Added unit test. PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
