### PR TITLE
Update libcontainer to 5d6c507d7cfeff97172deedf3db13b5295bcacef

### PR DESCRIPTION
**Pull request by LK4D4**
It includes new Type() method for Factory, which needed for replacing
execdriver.Driver.

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @crosbymichael @tiborvass @jfrazelle

**Comment by tianon** [comment]
LGTM :+1:

**Comment by tiborvass** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
