### PR TITLE
Update copyright years

### PR DESCRIPTION
**Pull request by slay**
Signed-off-by: vereas oli@overrateddev.co

Updated copyright years to "2018" from "2017"

P.S:

### CODE REVIEW

**Comment by Vereas** [comment]
Should be all good now.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Actually; could you squash these commits? I think it's ok to have all changes in a single commit

**Comment by Vereas** [comment]
That should do it

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Review by Masoodshafiee — APPROVED** [review]

**Pull request merged**
