### PR TITLE
Remove codegen for variables

### PR DESCRIPTION
**Pull request by dnephin**
Follow up to #34226 (last commit is new)

Inject version and git commit variables using `-go build -ldflags -X` instead of generating new files.

### CODE REVIEW

**Comment by tianon** [comment]
For reference, this is essentially the opposite of https://github.com/moby/moby/pull/10665 added specifically for `gccgo` support (which was removed in https://github.com/moby/moby/pull/25978 due to upstream Go now officially supporting all the architectures `gccgo` support was added for in the first place), so I'm +1 on removing all the autogen bits. :+1:

**Review by vdemeester — APPROVED** [review]
LGTM w

**Comment by vdemeester** [comment]
ping @dnephin needs a *huuugggee* rebase 😅

**Comment by dnephin** [comment]
This was based on #34226 which is the one that made all these changes. I'll close this for now since it seems it's not going anywhere.

**Pull request closed without merging**
