### PR TITLE
Bump API Version to v1.23

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by tiborvass** [comment]
thanks guys, i closed it because i found an issue and was afraid you would merge it too quickly  :)

**Comment by tiborvass** [comment]
The new API docs for 1.23 is not showing on Github, please check out locally and do the diff locally

**Comment by runcom** [comment]
LGTM

**Pull request merged**
