### PR TITLE
vendor: cloud.google.com/go v0.92.0, google.golang.org/api v0.54.0

### PR DESCRIPTION
**Pull request by thaJeztah**
### vendor: cloud.google.com/go v0.92.0, google.golang.org/api v0.54.0

this removes a `tools.go` from the dependency, which caused various test
dependencies to be ending up in the dependency-tree, and are now gone.

- cloud.google.com/go v0.92.0: https://github.com/googleapis/google-cloud-go/compare/v0.81.0...v0.92.0
- google.golang.org/api v0.54.0: https://github.com/googleapis/google-api-go-client/compare/v0.46.0...v0.54.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @tianon PTAL


love it when someone removes one of those silly `tools.go` files from their repository (and making 34k lines of code disappear: https://github.com/googleapis/google-cloud-go/commit/15c1eb9730f0b514edb911161f9c59e8d790a5ec (they added it in https://github.com/googleapis/google-cloud-go/commit/c536dae6e0638a279604dde6dc84efe523b1a117#diff-39bad9c50a0f30bd6c067b83431bec76, which caused issues for us before in https://github.com/moby/moby/pull/39838)

**Comment by thaJeztah** [comment]
Ah.. crap.. `<flip table>`

```
vendor/cloud.google.com/go/logging/apiv2/config_client.go:269:62: undefined: logging.ListBucketsRequest
```

**Comment by thaJeztah** [comment]
ok, should be fixed

**Comment by thaJeztah** [comment]
And... of course.. the next issue;

```
 vendor/google.golang.org/grpc/status/status.go:190:32: cannot use any (type *anypb.Any) as type *any.Any in argument to ptypes.UnmarshalAny
```

**Comment by tianon** [comment]
"There's always a bigger fish."

:heart:

**Comment by thaJeztah** [comment]
Yeah; back to square one (grpc / protobuf and swarmkit);

```
=== RUN   TestCreateServiceSecretFileMode
    create_test.go:294: assertion failed: string "\x03\x00\x00\x00\x00\x00\x00\xc2Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node tgrl8lywbrzrncqp1t0aaq71b is not available\n" does not contain "-rwxrwxrwx"
--- FAIL: TestCreateServiceSecretFileMode (12.66s)

**Comment by thaJeztah** [comment]
rebased this; now that https://github.com/moby/moby/pull/43357 was merged I _think_ this should work again 🤞

**Comment by thaJeztah** [comment]
Yup, all green now, and removing a nice bunch of unused dependencies

@cpuguy83 @tianon ptal ❤️

**Review by tianon — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
