### PR TITLE
Update Packagers readme with seccomp info

### PR DESCRIPTION
**Pull request by lblackstone**
Signed-off-by: Levi Blackstone levi.blackstone@rackspace.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
I'd also mention you'll need libseccomp >= 2.2.1 (actually on fedora we'll need libseccomp-static)

**Comment by lblackstone** [comment]
@runcom That info is already included under the build dependencies (line 62).

**Comment by runcom** [comment]
Alright :) LGTM then

**Comment by thaJeztah** [comment]
LGTM, thanks @lblackstone

**Pull request merged**
