### PR TITLE
Update debian.md

### PR DESCRIPTION
**Pull request by G-eos**
Update to wotk with debian jessie

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM when signed.

**Comment by crosbymichael** [comment]
Feel free to reopen this PR if you are able to sign and update the changes.

Thanks for the contribution!

**Comment by G-eos** [comment]
Signed, sorry for the delay

**Comment by thaJeztah** [comment]
@G-eos looks like GitHub doesn't like re opening :'( (it's frayed out)

Can you create a replacement PR, and refer to this one?

**Comment by G-eos** [comment]
do you have any suggestion to do it fast (avoid to redo the modification by hand ?)

**Pull request closed without merging**
