### PR TITLE
Fix service update replicas

### PR DESCRIPTION
**Pull request by dnephin**
cc @vieux  @ehazlett

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by ehazlett** [comment]
lgtm -- thx

**Comment by dnephin** [comment]
I noticed a few more flags were broken so I made constants for a bunch of them and fixes some others.

**Comment by icecrime** [comment]
Re-LGTM :+1:

**Comment by justincormack** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by icecrime** [comment]
All tests are passed, only `userns` crapped itself.

Merging, thanks!

**Pull request merged**
