### PR TITLE
change validateNoSchema to validateNoScheme

### PR DESCRIPTION
**Pull request by allencloud**
validateNoSchema has a typo in func name.
It should be validateNoScheme.

### CODE REVIEW

**Comment by mlaventure** [comment]
`vendor` is a legitimate error, `userns` actually passed but CI got stuck afterwards.

**Comment by vdemeester** [comment]
@allencloud as @mlaventure said, the `vendor` build is failing because be do not change code in it without the same changes upstream (in the repo the changes are).

**Comment by thaJeztah** [comment]
ping @allencloud can you update your PR and revert the changes in the `vendor/` directory?

**Comment by allencloud** [comment]
@thaJeztah 
revert the changes in the vendor/ directory?
Sorry, Actually I do not understand this.
Since I do not change thing in vendor.
As well I can not follow the vendor build's failing.

**Comment by thaJeztah** [comment]
@allencloud you made a change in vendor/src/github.com/docker/distribution/registry/api/v2/urls.go, since that file is vendored (copied) from another repository, you shouldn't change those files; your change is here; https://github.com/docker/docker/pull/21607/files#diff-9560ef2430be0af7ce734cd21bdcc2ccR17

If you change that back, the "vendor" check will no longer fail

**Comment by allencloud** [comment]
@thaJeztah 
Thanks a lot. I forgot that I also fixed some typos in this typos
I have changed that.

**Comment by thaJeztah** [comment]
thanks! LGTM

**Comment by vdemeester** [comment]
LGTM 🐮
(experimental failure unrelated, merging)

**Pull request merged**
