### PR TITLE
TestBuildRUNoneJSON need Network

### PR DESCRIPTION
**Pull request by sunyuan3**
FROM hello-world:frozen
Pulling repository docker.io/library/hello-world
Network timed out

Signed-off-by: Yuan Sun sunyuan3@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
@sunyuan3 how did you run into that problem? The "frozen" images should be pulled and tagged before the tests are run;

https://github.com/docker/docker/blob/fa57eedff409edb7a4ad926b365213a944a97954/hack/make/.integration-daemon-setup

and 

https://github.com/docker/docker/blob/fa57eedff409edb7a4ad926b365213a944a97954/hack/make/.ensure-frozen-images

So wondering why that image was missing in your test?

**Comment by cpuguy83** [comment]
Yeah, NOTLGTM
Should not need network on this test.

**Comment by thaJeztah** [comment]
I'll close this PR, but interested to year how you ran into this problem

**Comment by sunyuan3** [comment]
I use the following command to run test. "make test" is not used.

docker run -d --privileged -v `pwd`:/go/src/github.com/docker/docker dockercore/docker:latest /bin/bash -c "cd /go/src/github.com/docker/docker && ./hack/make.sh binary test-integration-cli"

**Comment by hqhq** [comment]
@sunyuan3 `busybox:frozen` should already exist in your image `dockercore/docker:latest`, otherwise there would be something wrong with your image, this test case doesn't need network. Maybe update your image and try again?

**Pull request closed without merging**
