### PR TITLE
Vendoring libnetwork b66c038

### PR DESCRIPTION
**Pull request by aboch**
- Changes to build libnetwork in Solaris
- Fix an issue which may arise during sandbox cleanup (https://github.com/docker/libnetwork/pull/1157)
- Fix cleanup logic in case of ipv6 allocation failure
- Don't add /etc/hosts record if container's ip is empty (--net=none)
- Fix default gw logic for internal networks
- Fix bug when updating IPv6 gateway (https://github.com/docker/libnetwork/issues/1142)
- Fix for https://github.com/docker/libnetwork/issues/1113
- Fix for https://github.com/docker/libnetwork/issues/1069
- Fix for https://github.com/docker/libnetwork/issues/1117
- Increase the concurrent query rate-limit count

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by mavenugo** [comment]
@aboch could you please split the commits into 3 commits ?
1 for docker side changes, 1 for libnetwork only changes & the last for other vendor dependencies.

**Comment by aboch** [comment]
Failures are legit.

**Comment by thaJeztah** [comment]
ping @aboch were you looking into the failures?

**Comment by aboch** [comment]
Yes, libnetwork PR were pushed to fix those

**Comment by LK4D4** [comment]
@aboch can we please have a link here for reference?

**Comment by aboch** [comment]
@LK4D4 
https://github.com/docker/libnetwork/pull/1162
https://github.com/docker/libnetwork/pull/1170

**Comment by aboch** [comment]
I am not able to relate the win2lin failure to the changes this PR brings in.
There seem to be several win2lin failure recently, in fact.

**Comment by aboch** [comment]
All green. Thanks @thaJeztah for re-triggering the ci.

**Comment by thaJeztah** [comment]
I think this fixes https://github.com/docker/docker/issues/22772? Any other issues in docker/docker that are resolved by this?

Also completes https://github.com/docker/docker/pull/22091, so ping @amitkris 

LGTM

**Comment by thaJeztah** [comment]
ping @mavenugo @vdemeester @LK4D4 PTAL

**Comment by vdemeester** [comment]
LGTM 🐰

**Pull request merged**
