### PR TITLE
c8d/builder: Enable s3 cache backend 

### PR DESCRIPTION
**Pull request by vvoland**
Follow up to:
- https://github.com/moby/moby/pull/44079

(Included https://github.com/moby/moby/pull/44908 to run the buildkit tests against docker-containerd worker.)

This implements buildkit's `s3` cache backend, the downside is that brings in a lot of code from `aws-sdk-go-v2`.
However we already have the `aws-sdk-go-v2` in our dependencies, so perhaps it's okay as a first step.

This will allow us to enable buildkit CI tests for docker-containerd.

As @cpuguy83  proposed - ideally we should explore the options of keeping the cloud cache backends out of dockerd and moving them into a separate binary.
This requires more some work though.

**- What I did**
Enabled s3 cache backend for containerd builder.

**- How I did it**
Filled "s3" cache resolver with buildkit's `s3remotecache` and vendored s3 related modules from github.com/aws/aws-sdk-go-v2.

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by crazy-max — APPROVED** [review]
LGTM

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Leaving a "request changes" review on this one so that we can discuss the strategy/design before we proceed.

**Comment by thaJeztah** [comment]
Short summary;

- Vendoring some of the SDK's also brings _implicit_ support for some common environment-variables supported by those SDKs
- This means that running the daemon in an environment that has such variables set now implicitly grants the daemon access to those variables (most notably; credentials / tokens)
- While this could be considered "expected" and/or "by design", _at least_ we MUST (imo) document which environment-variables are consumed
- AND document _for what purpose_ they are used.
- As noted by @samuelkarp in a conversation on Slack, we already consume some of these variables for _logging_ (e.g., `awslogs`)
- _Possibly_ (to be looked at) also for some other logging drivers (`gcplogs` ?)

I should note that;

- When running `dockerd` as a systemd service, env-vars must be explicitly passed (using one of `Environment`, `EnvironmentFile`, or `PassEnvironment`)
- But when interactively running `dockerd` (from the command-line), it will inherit from the current shell's environment
- For `cache` backends, these credentials (see above) are _ONLY_ used as a _fallback_ (if `docker build` is run _without_ passing credentials)
- But: adding `cache` backends changes the "scope" of these env-vars; where they were previously used only for logging, now they may be used for other purposes (e.g., accessing `s3` buckets)

Things to discuss / look into:

- [ ] Make an inventory of environment-variables that we (implicitly) inherited, and may not (yet) have documented.
- [ ] While it's the user's responsibility to not set env-vars if they should not be used, as well as scoping those credentials to only have access to things they _should_ have access to, I think it's our responsibility to _document_ which env-vars we consume, in which conditions we consume them, and what they're used for.
- [ ] We must consider that (more so in the "interactive" / "manually" run `dockerd` case) these environment-variables may be _present_ in the daemon's environment, but that they were not intentionally set _to be consumed_ by `dockerd` (and may be set for other purposes).
- [ ] Do we want to _always_ consume these env-vars, or do we need a "gate" to allow the user to _explicitly_ opt-in to consuming them? (something similar to `PassEnvironment` ?)
- [ ] Likewise: do we want all caching backends to be automatically _enabled_, or should they be configurable? (enable/disable specific caching backends)?

**Comment by tianon** [comment]
I don't worry about the environment variables nearly so much as the precedent for adding these large sprawling cloud SDKs to our dependency tree and thus creating further constraints when we want to upgrade (or not) our other dependencies that they might share. :grimacing:

IMO the argument that "we already have it in our deps" isn't super compelling because we do (I thought) want to get _rid_ of it from there, and using more of it makes that harder to accomplish :sweat_smile:

(I am definitely not going to be a blocker either way! :bow:)

**Comment by cpuguy83** [comment]
I will happily block this on expanding the cloud SDKs, which I've been trying to get rid of for years :)
It's also not lost on me that the only cloud SDK not in tree right now (unless I missed something) is my employer's.

These things are huge and tend do things we really don't want in the daemon that are hidden away.

**Comment by rumpl** [comment]
Quick thought: could we imagine implementing an s3 cache using minio's client rather than with 80k of AWS SDK?

**Comment by tonistiigi** [comment]
> Quick thought: could we imagine implementing an s3 cache using minio's client rather than with 80k of AWS SDK?

cc @bpaquet

**Pull request closed without merging**
