### PR TITLE
Rep README Fixing broken logo image 

### PR DESCRIPTION
**Pull request by moxiegirl**
Fixes #11044 

(branch misnamed)
Signed-off-by: Mary Anthony mary.anthony@docker.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
does this fix https://github.com/docker/docker/pull/11044, if so can you put fixes #11044 so it closes the issue ;)

**Comment by moxiegirl** [comment]
@jfrazelle ok...this fixes #11044 I amended the last commit.

**Comment by jfrazelle** [comment]
sorry i meant to say putting it in the comment works as well, i just don't know if it works if i comment it :)

**Comment by moxiegirl** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
