### PR TITLE
refactor the function 'aufsMount' in 'daemon/graphdriver/aufs/aufs.go'

### PR DESCRIPTION
**Pull request by miaoyq**
Refactor the function `aufsMount` in `daemon/graphdriver/aufs/aufs.go`, make it easier to understand.

Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Maybe it will be much easier to understand if the function is split to multiple parts (especially statements about `b` and `bp`)

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
Can we trigger this on an AUFS enabled integration run?

**Comment by tonistiigi** [comment]
@cpuguy83 https://jenkins.dockerproject.org/job/Tonis%20Docker%20debugginig/label=aufs/84/console

**Review by cpuguy83 — APPROVED** [review]
The original fn is definitely hard to understand...
integration tests passed here on aufs: https://jenkins.dockerproject.org/job/Tonis%20Docker%20debugginig/label=aufs/86/console

LGTM

**Pull request merged**
