### PR TITLE
Add Rob Murray (@robmry) as maintainer

### PR DESCRIPTION
**Pull request by akerouanton**
Rob is currently a curator, and has been actively contributing to this repo for 7 months now.

Beside day-to-day triaging and bug fixing, Rob is an instrumental contributor to libnetwork, and amongst other things, to the ongoing work on IPv6 improvements.

I nominated Rob as maintainer, and votes passed, so opening a PR to make it official.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM!

**Review by laurazard — APPROVED** [review]
LGTM 🥳

**Review by vvoland — APPROVED** [review]

**Review by crazy-max — APPROVED** [review]
:tada:

**Review by robmry — APPROVED** [review]
LGTM! Thank you.

**Comment by thaJeztah** [comment]
🎉 

Screenshot 2024-06-07 at 17 53 37
Screenshot 2024-06-07 at 17 54 33

**Pull request merged**
