### PR TITLE
#38860 leftover problem

### PR DESCRIPTION
**Pull request by xichengliudui**
Signed-off-by: xichengliudui 1693291525@qq.com

**- What I did**
Ref: https://github.com/moby/moby/pull/38860

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
th

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by thaJeztah** [comment]
I see https://github.com/moby/moby/pull/38860 wasn't merged yet because it's missing a DCO sign-off; could you include these changes in that PR, and fix the sign-off?

**Pull request closed without merging**
