### PR TITLE
Update IPv6 docs with modern `ip` command use + `sysctl`

### LINKED ISSUE #10701: doc uses outdated commands
My issue is about that documentation:

http://docs.docker.com/v1.5/articles/networking/#ipv6

route -A inet6 add 2001:db8:0:2::/64 dev docker0

should be replaced by 
ip -6 route add 2001:db8:0:2::/64 dev docker0

ifconfig should be replaced by ip addr ; ip link

The first part correctly uses the doc-prefix 2001:db8::/32

But later 2002:: is used, this prefix is reserved for  6to4 and could confuse the reader.

I think it is also better to use 

sysctl net.ipv6.conf.eth0.accept_ra=2

instead of 

echo 2 > /proc/sys/net/ipv6/conf/eth0/accept_ra

to ipv6 itself, I tested only the first scenario

### PR DESCRIPTION
**Pull request by estesp**
Fixes: #10701

Updates the IPv6 documentation and images to reflect the more modern
`ip -6` command set versus `route` and `ifconfig`.  Also removes the
use of the special 2002: address range as that is reserved for 6to4
addressing.

Docker-DCO-1.1-Signed-off-by: Phil Estes estesp@linux.vnet.ibm.com (github: estesp)

### CODE REVIEW

**Comment by LK4D4** [comment]
nice, thanks

**Comment by SvenDowideit** [comment]
mmm, I'll have to test a few things and distros - though I think - yay :)

**Comment by estesp** [comment]
@SvenDowideit definitely validation would be good.. seems OK on Fedora 21 and Ubuntu 14.10 from the checking I did today.  Also, I don't have any good SVG tools and I was not happy that gliffy export-to-SVG seemed to generate larger files than the previous ones in the tree.  Only one has a significantly different canvas size, which shouldn't matter as SVG is only the vectors and text--so not sure what was done last time, but let me know if I need to use another tool to simplify them.

**Comment by thaJeztah** [comment]
I asked the reporter of #10701 if he could have a look at this PR as well to see if this resolves his issue, but there still are some issues, see https://github.com/docker/docker/issues/10701#issuecomment-74412504

(Sorry that this caused the discussion to be spread over two locations now)

**Comment by MalteJ** [comment]
@estesp thanks for this PR.
+1 for the ip command.
But we should use the documentation IPv6 address range `2001:db8::/32` defined by [RFC3849](https://tools.ietf.org/html/rfc3849) for our examples. Unfortunately the addresses in the graphs will get bigger. But I think we should use the reserved documentation address space. I mean, it is there for a reason.

**Comment by estesp** [comment]
@MalteJ PR is updated using only subnets from doc prefix address space.  I **think** I got everything right, but head starts swimming trying to keep all the subnets straight in the diagram and text :)

**Comment by estesp** [comment]
@SvenDowideit this PR has been updated to re-align all addresses around the doc prefix range, as well as all images.  @MalteJ has provided additional updates which I've merged in.  Please review when you are able.  Thanks!

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @SvenDowideit @MalteJ

**Comment by MalteJ** [comment]
LGTM
(that's my first lgtm :smile:)

**Pull request merged**
