### PR TITLE
update poule.yml

### PR DESCRIPTION
**Pull request by vieux**
see https://github.com/icecrime/poule/issues/13 for context.

ping @thaJeztah @icecrime

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

*Goes to `tail -f` the logs and see if the tool explodes when we merge this :innocent:*

**Review by vdemeester — APPROVED** [review]
LGTM :angel:

**Comment by icecrime** [comment]
Let's see how that goes...

**Comment by icecrime** [comment]
```
time="2016-12-02T18:06:27-05:00" level=debug msg="received GitHub event" action=closed event="pull_request" number=29090 repository="docker/docker" 
time="2016-12-02T18:06:27-05:00" level=info msg="running operation" operation=poule-updater repository="docker/docker" 
time="2016-12-02T18:06:27-05:00" level=info msg="updating configuration" dry_run=false item_num=29090 item_type="pull_request" repository="docker/docker" 
time="2016-12-02T18:06:27-05:00" level=info msg="updated configuration for repository \"docker/docker\" from GitHub"
```

:hugs:

**Comment by thaJeztah** [comment]
❤️

**Pull request merged**
