### PR TITLE
Update vendored engine-api for OpenBSD support

### PR DESCRIPTION
**Pull request by frenkel**
Update vendored engine-api to complete support for building docker on OpenBSD.

### CODE REVIEW

**Comment by thaJeztah** [comment]
oh! you need to update hack/vendor.sh to the right commit, then run that script, and commit the results. The hack/vendor.sh script makes sure that only the files that are actually needed are vendored in.

**Comment by frenkel** [comment]
Yes, sorry, forgot to commit it, I've now added it.

**Comment by thaJeztah** [comment]
hm, looks like this time it removed far too much :cry: @vdemeester any thoughts?

**Comment by frenkel** [comment]
I can also create a cherry-picked vendor update if that is an option. I won't be able to update the hack/vendor.sh script then though.

**Comment by vdemeester** [comment]
@frenkel I guess you're running `hack/vendor.sh` on OpenBSD right ? (that might be why it's removing too much stuff..)
I'll try it on my linux box to see how it goes :wink:

**Comment by thaJeztah** [comment]
oh! yes, that could explain!

**Comment by frenkel** [comment]
No, I screwed up, sorry. I stopped the vendor script because I only needed engine-api updated. Than apparently ran `git commit` with `-a` after the `git add` which I shouldn't have. Newest push should work just fine.

**Comment by vdemeester** [comment]
@frenkel Still see +3000 changes.. If you ran `hack/vendor.sh`, it did not cleaned the files :sweat:.

It should only push these diffs :

```bash
$ git diff --stat 
 hack/vendor.sh                                                | 2 +-
 vendor/src/github.com/docker/engine-api/client/client_unix.go | 2 +-
 vendor/src/github.com/docker/engine-api/types/types.go        | 7 ++++---
 3 files changed, 6 insertions(+), 5 deletions(-)
```

**Comment by thaJeztah** [comment]
@vdemeester do you have time to carry?

**Comment by frenkel** [comment]
I ran the `vendor.sh` script again and let it finish normally. Now there are only a few changes indeed. I've just pushed a correct commit to this pull requests branch. Sorry for all the fuzz.

**Comment by vdemeester** [comment]
@frenkel yay looks good :tada:. No biggies, it happens :D

LGTM 🐹

**Comment by calavera** [comment]
LGTM

**Pull request merged**
