### PR TITLE
Fixes #15299 Adding API for container migration.

### LINKED ISSUE #15299: Proposal: Migrate Containers from one storage to another.
Problem: 
We have users who are running docker (Production environment), using lvm devmapper on top of loopback devices. Since this storage option is not production ready, we recommend them to switch to a different storage. Being a production environment they don't want to loose their containers when migrating from one storage to another.

Currently they can achieve this using docker export/import. However there are some shortcomings with these commands.
Let's take an example.

1) I have my source docker (devmapper running on loopback devices) running with 1 image {fedora}.
2) I start a container on this image: docker run --name fedora_container -it fedora /bin/bash
3) I make some changes in the container: echo foobar > /home/foobar.txt
4) I stop the container and I want to migrate my images {fedora} and containers {fedora_container} to the new storage.

Current setup:

1) docker save fedora > fedora.tar
2) docker export -o fedora_container.tar fedora_container [This will tar up the container rootfs including the changes {foobar.txt} we made]
3) Switch to the new storage.
4) docker load < fedora.tar
5) cat fedora_container.tar | docker import - fedora_new:latest
6) Now I can start a container which will have my changes {foobar.txt} on this new image, fedora_new:latest

Shortcomings:

1) The container on the new storage is based on image {fedora_new} eventhough the original container was based on image {fedora}.
2) The image fedora_new is a completely standalone image which is not based on any image.
    docker inspect -f {{.Parent}} fedora_new = ""
3) Any metadata associated with the containers e.g Mount points is lost, since the container is recreated at the new storage.
4) Docker import results into an image (not container). This means if a user is trying to migrate X images and Y Containers.
   At the new storage he will see X+Y Images, and then he has to start all the containers again on these new images.
5) Since docker export tars up the entire rootfs, the tarball is heavy (In our example, we just created one file {foobar.txt} and the tar ball is ~200MB)

Proposal:

1) docker export with a new flag (--diff-metadata) will create a tarball with only the diff and metadata of the container. {~ 17 Kb in size}
2) docker import will:
        a) createRootfs on the new storage.
        b) Apply diff.
        c) setup metadata.
        d) load the container in the daemon.

After the import the user will see exact replica of `docker images` and `docker ps -a` in the new storage.

I have a working version of this proposal on my github branch.
https://github.com/shishir-a412ed/docker/tree/migrate_containers

How to:
EXPORT: docker export -o fedora_container.tar --diff-metadata fedora_container
IMPORT: cat fedora_container.tar|docker import --diff-metadata -

I am opening this proposal so that we can discuss how to best approach this problem. 
You can also take a look at my implementation, and if you like that approach I can open a PR and we can take it there.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes #15299 
Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by calavera** [comment]
This is a personal preference, but I'd rather have #13602 than this api.

**Comment by rhvgoyal** [comment]
@calavera 

IIUC, container checkpoint/restore API is completely orthogonal to this API. In checkpoint/restore we will save process state and restore it later. But restore expects that container file system is in same state as it was at the time of checkpoint. checkpoint/restore API does not seem to give any way to migrate the existing container environment. That API will only restore the container processes if underlying container file system is same.

IOW, I think both the APIs might actually be complementary. What if I want to checkpoint a container and restore it on a different host. First I should be able to recreate the container on different host before I can restore it. And to recreate the container I should now how container was created to begin with. (All the options which were used at create/run time)

So if we can come up with a way where container's rootfs can be migrated from one host to another, then checkpoint/restore should be able to use it too and restore the saved state on migrated container.

So to me it looks like that these two functionality are actually complimentary and one is not replacement for other. Am I missing something.

**Comment by boucher** [comment]
I completely agree that this is complementary to checkpoint/restore.

**Comment by tiborvass** [comment]
@shishir-a412ed I would like you to close this until we have a design agreement on #15299. Then you can reopen this. Feel free to link to branches of yours on the issue if you want to share code.

**Comment by shishir-a412ed** [comment]
@tiborvass 
Agreed. Closing this one, until a design decision is made on #15299 .

**Comment by tiborvass** [comment]
Thanks!

**Pull request closed without merging**
