### PR TITLE
after the changes to unit test framework, fixing gccgo to run unit tests

### PR DESCRIPTION
**Pull request by brahmaroutu**
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by brahmaroutu** [comment]
ping @LK4D4 please review.

**Comment by LK4D4** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :wink:

**Comment by brahmaroutu** [comment]
thanks @LK4D4 @vdemeester.

**Pull request merged**
