### PR TITLE
Update TestDaemonRestartWithLiveRestore: fix docker0 subnet missmatch

### PR DESCRIPTION
**Pull request by m-k8s**
**- What I did**

In some companies, continuous integrations are launched from a docker dind container (with the Gitlab CI docker executor for example).

When the tests are initiated from docker dind TestDaemonRestartWithLiveRestore fails because it checks that this subnet of the docker0 interface is `172.18.0.0/16` while it is not in this case, we have the `172.17.0.0/16` subnet instead.

Here is the error that is displayed when we run the integration tests from a dind container :
`service_test.go:47: assertion failed: 172.17.0.0/16 (out.IPAM.Config[0].Subnet string) != 172.18.0.0/16 (string)`

Ip subnets with docker dind :
```
machine 1:
docker0_subnet: 172.17.0.0/16

docker_dind_container:
  eth0_subnet: 172.17.0.0/16
  docker0_subnet: 172.18.0.0/16

   docker_integration_test_container:
     eth0_subnet: 172.18.0.0/16
     docker0_subnet: 172.17.0.0/16
```

Ip subnets with baremetal or vm server :
```
machine 1:
docker0_subnet: 172.17.0.0/16

docker_integration_test_container:
  eth0_subnet: 172.17.0.0/16
  docker0_subnet: 172.18.0.0/16
```

**- How I did it**

So instead of comparing the docker0 subnet with a hardcoded value in TestDaemonRestartWithLiveRestore, I compare it with the docker0 subnet that there was before restarting the docker daemon.

1. fetch the subnet from docker0
2. restart the docker daemon
3. fetch the subnet from docker0
4. Ensure that the docker0 subnet has not changed with daemon restarts

**- How to verify it**

The integration test should pass when initiated from a docker dind container: 
```
docker run --privileged --rm -v $(pwd):/app --workdir /app -it docker:dind sh
apk add make bash git
dockerd &> /dev/null &
make test-integration
```

**- Description for the changelog**

Update TestDaemonRestartWithLiveRestore: dynamic check of the docker0 subnet after restarting the docker daemon.

### CODE REVIEW

**Comment by thaJeztah** [comment]
CI failure is unrelated and a flaky test; the test passed (I restarted CI);

```
[2021-02-05T19:07:27.013Z] === RUN   TestDaemonRestartWithLiveRestore
[2021-02-05T19:07:27.954Z] --- PASS: TestDaemonRestartWithLiveRestore (1.04s)
```

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
@AkihiroSuda @cpuguy83 ptal

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
