### PR TITLE
Update golang to 1.18.0

### PR DESCRIPTION
**Pull request by thaJeztah**
just testing for now

depends on:

- [x] https://github.com/moby/moby/pull/43200
- [x] https://github.com/moby/moby/pull/43195
- [x] https://github.com/moby/moby/pull/43202

### CODE REVIEW

**Comment by thaJeztah** [comment]
interesting failure on golangci-lint. Guess it's not compatible with go1.18?

```
[WARN [runner] Can't run linter goanalysis_metalinter: S1021: failed prerequisites: inspect@github.com/docker/docker/api/types/blkiodev, isgenerated@github.com/docker/docker/api/types/blkiodev
[WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/go/src/github.com/docker/docker/api/types/blkiodev/blkio.go:3:8: could not import fmt (/usr/local/go/src/fmt/errors.go:7:8: could not import errors (/usr/local/go/src/errors/wrap.go:8:2: could not import internal/reflectlite (/usr/local/go/src/internal/reflectlite/swapper.go:8:2: could not import internal/goarch (-: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool))))]
[ERRO Running error: buildssa: analysis skipped: errors in package: [/go/src/github.com/docker/docker/api/types/blkiodev/blkio.go:3:8: could not import fmt (/usr/local/go/src/fmt/errors.go:7:8: could not import errors (/usr/local/go/src/errors/wrap.go:8:2: could not import internal/reflectlite (/usr/local/go/src/internal/reflectlite/swapper.go:8:2: could not import internal/goarch (-: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool))))] 
```

```
/go/src/github.com/docker/docker/api/types/blkiodev/blkio.go:3:8: could not import fmt
/usr/local/go/src/fmt/errors.go:7:8: could not import errors
/usr/local/go/src/errors/wrap.go:8:2: could not import internal/reflectlite
/usr/local/go/src/internal/reflectlite/swapper.go:8:2: could not import internal/goarch
-: could not load export data: cannot import "internal/goarch" 
    unknown iexport format version 2,
    export data is newer version - update tool
```

**Comment by thaJeztah** [comment]
Ah, some new linting failures, looks related to go1.18;

```
client/request.go:157:8: SA1019: err.Temporary is deprecated: Temporary errors are not well-defined. Most "temporary" errors are timeouts, and the few exceptions are surprising. Do not use this method. (staticcheck)
            if !err.Temporary() {
                ^
daemon/logger/templates/templates.go:23:14: SA1019: strings.Title is deprecated: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
    "title":    strings.Title,
                ^
pkg/plugins/pluginrpc-gen/template.go:67:9: SA1019: strings.Title is deprecated: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
    return strings.Title(s)
           ^
```

**Comment by thaJeztah** [comment]
Updated to 1.18beta2; https://github.com/golang/go/compare/go1.18beta1...go1.18beta2

**Comment by AkihiroSuda** [comment]
1.18 is GA now

**Comment by thaJeztah** [comment]
Yup! Rebased, and updated the PR to 1.18.0

**Review by tianon — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
