### PR TITLE
runconfig: opts: parse: lowercase errors

### PR DESCRIPTION
**Pull request by runcom**
also fix wrong function comment

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by duglin** [comment]
LGTM if you can make Janky happy  :-)

**Comment by runcom** [comment]
@duglin don't know what's happening, do you? :angel:

**Comment by thaJeztah** [comment]
Nope, very weird

**Comment by duglin** [comment]
nope - restarting - maybe janky just needs some coffee

**Comment by runcom** [comment]
janky's green now

**Comment by calavera** [comment]
LGTM

**Pull request merged**
