### PR TITLE
Fix error message for pause a restarting container

### PR DESCRIPTION
**Pull request by WeiZhang555**
This is follow of #19918

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by duglin** [comment]
Can we get a testcase for this?

**Comment by WeiZhang555** [comment]
@duglin I hope so, but it's too hard, the `Restarting` state is really hard to be caught, I can't find a way to keep the container's state to `restarting` and not change to `running`. That bothers me a lot.

Do you have any suggestion?

**Comment by thaJeztah** [comment]
I think this needs a rebase now, because the same error-type was added in https://github.com/docker/docker/pull/19914/files

**Comment by WeiZhang555** [comment]
@thaJeztah Rebased, thank you for your reminder! :smile:

**Comment by cpuguy83** [comment]
I agree, this is bound to be a flakey test.
Even if you loop over it to grab it while it's in restarting state there's still a race between reading the restarting state and then trying to pause it.

LGTM.

**Comment by jfrazelle** [comment]
LGTM

**Comment by WeiZhang555** [comment]
:fireworks:

**Pull request merged**
