### PR TITLE
Remove -run flag from commit command.

### PR DESCRIPTION
**Pull request by vdemeester**
This flag has been deprecated in version below 1.10 so it's safe to
remove now, according to our deprecation policy 🐅.
- [x] Need to check docs if there is anything to remove there 👼

/cc @thaJeztah @icecrime @tiborvass @duglin 

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by cpuguy83** [comment]
```
14:35:13 api/client/container/commit.go:4: imported and not used: "encoding/json"
14:35:13 api/client/container/commit.go:13: imported and not used: "github.com/docker/engine-api/types/container" as containertypes
```

**Comment by vdemeester** [comment]
@cpuguy83 ah lol.. pushed too quickly 😓

**Comment by thaJeztah** [comment]
Searched the docs but couldn't find any reference. I looks like it was [deprecated in docker 0.10]( https://github.com/docker/docker/blob/d834eb69102230716a4ff729617e6fe680ddcbb6/CHANGELOG.md#0100-2014-04-08), so we could add a mention in `deprecated.md` just for reference

**Comment by vdemeester** [comment]
@thaJeztah it's already in `deprecated.md` : https://github.com/docker/docker/blob/master/docs/deprecated.md#old-command-line-options

**Comment by thaJeztah** [comment]
@vdemeester that's different, that's deprecating the single-dash options, and replacing them with double dash (`-run` became `--run`);

> The following single-dash (-opt) variant of certain command line options are deprecated and replaced with double-dash options (--opt):

**Comment by vdemeester** [comment]
@thaJeztah true 👼

**Comment by duglin** [comment]
A comment in there says:
```
FIXME: --run is deprecated, it will be replaced with inline Dockerfile commands
```
do we have this?

**Comment by thaJeztah** [comment]
@duglin yup, through `--change`;

```
docker commit --change 'CMD ["cat", "/tmp/foo"]' ....
```

**Comment by duglin** [comment]
yea but `RUN` isn't supported via `--change`

**Comment by duglin** [comment]
From the docs:
```
Supported Dockerfile instructions: 
CMD|ENTRYPOINT|ENV|EXPOSE|LABEL|ONBUILD|USER|VOLUME|WORKDIR
```

**Comment by cpuguy83** [comment]
Because `RUN` doesn't make sense, and it's not the same thing as `--run` which IIRC takes a json object.

**Comment by vdemeester** [comment]
@duglin `--run` didn't really support it either, it takes a container `Config` — the flag was poorly named :sweat:.

**Comment by duglin** [comment]
whoa - that's just weird :-)

**Comment by thaJeztah** [comment]
> whoa - that's just weird :-)

Let's deprecate it!

Oh, wait 😜

**Comment by LK4D4** [comment]
It was really weird stuff.
LGTM

**Comment by vdemeester** [comment]
retest this please

**Comment by vdemeester** [comment]
well… it does not work with me :sweat_smile: documentation :sweat:

**Comment by thaJeztah** [comment]
retest this please

**Comment by thaJeztah** [comment]
works for me. guess Janky doesn't like you :joy:

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Pull request merged**
