### PR TITLE
Add powershell completion support

### PR DESCRIPTION
**Pull request by samneirinck**
Initial version of powershell tab completion. It completes commands and container names.

Based upon https://github.com/samneirinck/posh-docker

Signed-off-by: Sam Neirinck sam@samneirinck.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice, thank you!

ping @jhowardmsft @friism

**Comment by jhowardmsft** [comment]
@swernli This is probably one for you to take a look at :smile:

**Comment by swernli** [comment]
Seems fine to me.

**Comment by icecrime** [comment]
Thanks @samneirinck! Looks fine by me, plus it's `contrib/` so we don't need some extensive review.

LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by samneirinck** [comment]
👌 Thanks.

**Pull request merged**
