### PR TITLE
Fix the vendoring script on MacOS X

### PR DESCRIPTION
**Pull request by kencochrane**
Please provide the following information:
- What did you do? 

I fixed an issue with the vendoring script on Mac OSX
- How did you do it?

I added a parameter that was optional in linux, but required on Mac OSX
- How do I see it or verify it?

I ran the vendoring script locally. It wasn't working before, and now it is.

Full Details:

The version of sed on MacOS X is different then the one on linux. The mac version
requires a parameter for the inline (-i) flag, where this isn't required on linux.
On the mac it thinks the -e flag is the parameter, and it causes the vendoring script
to fail.

This fix adds an empty string '' as a parameter to sed, which works fine on both the
mac and linux versions.

For more info see: http://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

Signed-off-by: Ken Cochrane kencochrane@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
:heart_eyes: thanks @kencochrane. My current approach was running in a container :smile:

**Comment by kencochrane** [comment]
@thaJeztah you're welcome. I was doing the same, but sometimes I'm lazy :)

**Comment by cpuguy83** [comment]
Running this now. Seeing a lot of: `sed: can't read : No such file or directory`
`sed: can't read : No such file or directory`

And then it deleted a bunch of stuff from vendor.
```
	deleted:    vendor/src/github.com/docker/libnetwork/discoverapi/discoverapi.go
	deleted:    vendor/src/github.com/docker/libnetwork/ipams/null/null.go
	deleted:    vendor/src/github.com/docker/libnetwork/ipams/windowsipam/windowsipam.go
	deleted:    vendor/src/github.com/miekg/dns/.gitignore
	deleted:    vendor/src/github.com/miekg/dns/.travis.yml
	deleted:    vendor/src/github.com/miekg/dns/AUTHORS
	deleted:    vendor/src/github.com/miekg/dns/CONTRIBUTORS
	deleted:    vendor/src/github.com/miekg/dns/COPYRIGHT
	deleted:    vendor/src/github.com/miekg/dns/README.md
	deleted:    vendor/src/github.com/miekg/dns/client.go
	deleted:    vendor/src/github.com/miekg/dns/clientconfig.go
	deleted:    vendor/src/github.com/miekg/dns/defaults.go
	deleted:    vendor/src/github.com/miekg/dns/dns.go
	deleted:    vendor/src/github.com/miekg/dns/dnssec.go
	deleted:    vendor/src/github.com/miekg/dns/dnssec_keygen.go
	deleted:    vendor/src/github.com/miekg/dns/dnssec_keyscan.go
	deleted:    vendor/src/github.com/miekg/dns/dnssec_privkey.go
	deleted:    vendor/src/github.com/miekg/dns/doc.go
	deleted:    vendor/src/github.com/miekg/dns/edns.go
	deleted:    vendor/src/github.com/miekg/dns/format.go
	deleted:    vendor/src/github.com/miekg/dns/labels.go
	deleted:    vendor/src/github.com/miekg/dns/msg.go
	deleted:    vendor/src/github.com/miekg/dns/nsecx.go
	deleted:    vendor/src/github.com/miekg/dns/privaterr.go
	deleted:    vendor/src/github.com/miekg/dns/rawmsg.go
	deleted:    vendor/src/github.com/miekg/dns/sanitize.go
	deleted:    vendor/src/github.com/miekg/dns/scanner.go
	deleted:    vendor/src/github.com/miekg/dns/server.go
	deleted:    vendor/src/github.com/miekg/dns/sig0.go
	deleted:    vendor/src/github.com/miekg/dns/singleinflight.go
	deleted:    vendor/src/github.com/miekg/dns/tlsa.go
	deleted:    vendor/src/github.com/miekg/dns/tsig.go
	deleted:    vendor/src/github.com/miekg/dns/types.go
	deleted:    vendor/src/github.com/miekg/dns/types_generate.go
	deleted:    vendor/src/github.com/miekg/dns/udp.go
	deleted:    vendor/src/github.com/miekg/dns/udp_linux.go
	deleted:    vendor/src/github.com/miekg/dns/udp_other.go
	deleted:    vendor/src/github.com/miekg/dns/udp_windows.go
	deleted:    vendor/src/github.com/miekg/dns/update.go
	deleted:    vendor/src/github.com/miekg/dns/xfr.go
	deleted:    vendor/src/github.com/miekg/dns/zgenerate.go
	deleted:    vendor/src/github.com/miekg/dns/zscan.go
	deleted:    vendor/src/github.com/miekg/dns/zscan_rr.go
	deleted:    vendor/src/github.com/miekg/dns/ztypes.go
	deleted:    vendor/src/github.com/opencontainers/runc/libcontainer/keys/keyctl.go
	deleted:    vendor/src/golang.org/x/net/proxy/direct.go
	deleted:    vendor/src/golang.org/x/net/proxy/per_host.go
	deleted:    vendor/src/golang.org/x/net/proxy/proxy.go
	deleted:    vendor/src/golang.org/x/net/proxy/socks5.go
```

**Comment by tianon** [comment]
Maybe we need to do an explicit "-i.bak" and then "find vendor -name
'*.bak' -exec rm '{}' +" ?

**Comment by cpuguy83** [comment]
@kencochrane On a Mac.

**Comment by tianon** [comment]
Yeah -- the man page for GNU sed has this:
```
       -i[SUFFIX], --in-place[=SUFFIX]

              edit files in place (makes backup if extension supplied)
```

**Comment by cpuguy83** [comment]
Using GNU Sed 4.2.2, FYI.

**Comment by tianon** [comment]
If you switch to the long-form version `--in-place=` and do that, it _should_ work, but with the short form, `-i` and `-i''` will be exactly the same. :smile:

I think our best bet is going to just be to be explicit (since `--in-place` isn't 100% standard IIRC) and go with something like `-i.bak` and then delete the spurious backup files it creates.

**Comment by kencochrane** [comment]
@tianon so changing from ``-i ''`` to ``-i''`` made the error go away with GNU sed.

If you want to add the explicit extension, and then in the cleanup, remove, I can do that.

**Comment by kencochrane** [comment]
@tianon @cpuguy83 OK, I changed it so that we have `.orig` files, and then cleaned those up in the clean command. 

I tested it out with BSD sed on Mac OSX and GUN sed 4.2.2 on linux, and it works as planned.

**Comment by tianon** [comment]
:smile: LGTM :+1:

**Comment by cpuguy83** [comment]
Didn't see any of the sed errors this time, but....
:cry: it still removed everything listed above.

**Comment by kencochrane** [comment]
@cpuguy83 hmm are they files that are needed, if you do a git status, are they saying those files will be removed from the vendor directory, when they were there before?

**Comment by cpuguy83** [comment]
Presumably yes.

When running on linux they aren't removed.

**Comment by kencochrane** [comment]
@cpuguy83 hmm, I don't see that on my mac, I'll have to install the GNU sed and try again.

**Comment by kencochrane** [comment]
@cpuguy83 I can't reproduce it locally. how are you running the script?

I running ``hack/vendor.sh``

Here is my setup.

```
$ uname -a
Darwin Kens-MBPr.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
$ sed --version
gsed (GNU sed) 4.2.2
```
I tried both BSD sed and GNU sed, and got the same results.

**Comment by aaronlehmann** [comment]
It seems possible that the issue with extra files being removed is a separate one that's unrelated to `sed`. Whenever I run the vendor script on my Mac, it deletes `coreos/etcd` and `miekg/pkcs11`. I've seen the same thing happen on Linux. I suspected this had to do with build tags, but never investigated it deeply.

**Comment by kencochrane** [comment]
@aaronlehmann thanks for letting me know. If there was an easy way to reproduce, I can look at trying to fix, but unfortunately without a place to debug, I'll be shooting darts in the dark.

**Comment by calavera** [comment]
This change breaks my host again :crying_cat_face: 

image

```
➜  docker git:(kencochrane-fix_vendoring_script_macosx) ✗ sed --version
sed (GNU sed) 4.2.2
Copyright (C) 2012 Free Software Foundation, Inc.
➜  docker git:(kencochrane-fix_vendoring_script_macosx) ✗ uname -a
Linux david-dev-box 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by calavera** [comment]
I think we should go back to the original patch and fix only the problem with OS X.

**Comment by kencochrane** [comment]
@calavera ok, I'll go back to my original fix and see if that works better for everyone.

**Comment by tianon** [comment]
The ".orig" stuff we're pulling in is good, but I think we probably just
need to pull back in the workaround we had before that I was hoping was
related. :cry:

**Comment by kencochrane** [comment]
@tianon ok, lets do baby steps. I'll put back to my original fix, if that works for everyone, then I'll put back the .orig fix, if that works as well, then we can stop there and call it good.

**Comment by tianon** [comment]
The empty string is definitely broken for some implementations of sed,
though -- that's what I'm trying to say. :smile:

**Comment by kencochrane** [comment]
@tianon yeah that is what I'm finding out, putting the .orig back in, and testing that now. If it works for me in my 3 different sed setup, I'll update this PR with the change.

**Comment by kencochrane** [comment]
@cpuguy83 @tianon @calavera ok, I put back the hack, and left the .orig fix, I tested on my mac with BSD sed, and GNU sed, and GNU sed on linux, and they all worked for me. Please try it out and see if it works for you as well.

**Comment by cpuguy83** [comment]
:( still removing stuff for me.

**Comment by kencochrane** [comment]
@cpuguy83 :( I'm out of ideas. what happens when you run the vendor script without my changes? Do you have any other changes locally that might have affect the script?

**Comment by cpuguy83** [comment]
Yeah, it removes a bunch of vendor stuff which is why I always do it in Linux.

**Comment by cpuguy83** [comment]
So, this change isn't causing the issue, I was just hoping it would fix it.

**Comment by kencochrane** [comment]
@cpuguy83 ok, it is good to know this isn't getting any worse for you. Since this fixes my issue, we should probably merge it. Then if I can duplicate what you are seeing I can try and fix your issue in another PR. As @aaronlehmann said, it might be something with build tags.

**Comment by tianon** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
