### PR TITLE
Add Cecilia Payne-Gaposchkin to names generator.

### PR DESCRIPTION
**Pull request by soulshake**
Signed-off-by: AJ Bowen aj@gandi.net

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM, this is the first name we've added with a hyphen, but what could possibly go wrong...

**Comment by tianon** [comment]
LGTM, but I do agree with @jfrazelle that the hyphen and the length might be problematic, especially since these are supposed to be "easy to type"

**Comment by jfrazelle** [comment]
I see alot she is referred to as just Payne, do you think we could do that?

**Comment by MalteJ** [comment]
is condescending-payne-gaposchkin really shorter than an UUID?

**Comment by jfrazelle** [comment]
thats why I was saying just payne :)

**Comment by MalteJ** [comment]
+1 for Payne :)

**Comment by soulshake** [comment]
Word; changed it to `payne`. 
Too bad `gaposchkin` is more fun to say than it is to type. :smirk:

**Comment by jaslo** [comment]
If hyphenated names are now going in, I would suggest "Berners-Lee".

**Comment by jfrazelle** [comment]
we changed it to payne and also PRs welcome

**Pull request merged**
