### PR TITLE
Refactor few spec generation ops

### PR DESCRIPTION
**Pull request by crosbymichael**
This starts the refactor of docker spec generation to containerd SpecOpts.

This improves sharing of opts for other services and projects.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM :heart:

this is so much cleaner! thank you!

**Comment by thaJeztah** [comment]
This test looks to be flaky since recently

```
20:33:13 --- FAIL: Test (2321.68s)
20:33:13 panic: DockerDaemonSuite.TestCleanupMountsAfterDaemonAndContainerKill test timed out after 5m0s [recovered]
20:33:13 	panic: DockerDaemonSuite.TestCleanupMountsAfterDaemonAndContainerKill test timed out after 5m0s
```

**Comment by thaJeztah** [comment]
Same tests failing again https://jenkins.dockerproject.org/job/Docker-PRs-experimental/44887/console, https://jenkins.dockerproject.org/job/Docker-PRs/53709/console

I'll try once more to be sure

**Comment by thaJeztah** [comment]
ping @moby/moby-maintainers 🤗

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/issues/39061 for that test

**Comment by crosbymichael** [comment]
we have 2 lgtms can we merge?

**Comment by thaJeztah** [comment]
Yes!! 🎉

**Pull request merged**
