### PR TITLE
add EnvironmentFile=/etc/default/docker into docker.service

### PR DESCRIPTION
**Pull request by asdfsx**
add EnvironmentFile=/etc/default/docker into docker.service
so we can change the configerations by modify /etc/default/docker

### CODE REVIEW

**Comment by phemmer** [comment]
This is a dup, and has come up numerous times. For the latest, see #14513 

The documentation on how to adjust daemon options when using systemd can be found here: http://docs.docker.com/articles/systemd/#custom-docker-daemon-options

**Comment by jfrazelle** [comment]
yes please look at the other PRs that have come up about this, hope you can understand. thanks.

**Comment by asdfsx** [comment]
I wish these configure files can be installed automaticaly, not added by my hand someday.

**Comment by thaJeztah** [comment]
@asdfsx did you read the comment above? You *shouldnt* modify docker.service, but use dropins; http://docs.docker.com/articles/systemd/#custom-docker-daemon-options

**Pull request closed without merging**
