### PR TITLE
Describe IP field of Port definition

### PR DESCRIPTION
**Pull request by emanb29**
First PR, tried not to touch anything too important just in case. I saw it as the first step in clarifying docker/docker.github.io#6478, even if not directly related

**- What I did**
Attempted to clarify what "Container.Ports[].IP" refers to

**- How I did it**
Added a description

**- How to verify it**
Build docs and read, eg, 200 response info for "List Containers" (/containers/json)

**- Description for the changelog**
Describe IP field of swagger Port definition

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hm, looks like you have to re-generate the types as well (as some are generated from the swagger file)

```
04:31:05 Please update api/swagger.yaml with any api changes, then 
04:31:05 run `hack/generate-swagger-api.sh`.
```

Let me know if you need help with that!

**Comment by emanb29** [comment]
Unfortunately, since I'm developing on windows, I couldn't get make to behave, and docker refused to install on my usual ubuntu build VPS. Sorry, I may indeed need some help with that.

**Comment by thaJeztah** [comment]
No worries, I rebased your commit, re-ran the swagger-generation and pushed 👍

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
