### PR TITLE
swarm-scoped events should also contain tasks #37403

### PR DESCRIPTION
**Pull request by artheus**
**- What I did**
I implemented code for allowing users of the docker API to watch for Swarm Task events. I also added some code for allowing to filter by service name.

**- How I did it**
I went through the code for the API and the daemon to pin-point exactly what code needed to be added for this to work. I tried to follow the existing code standard as good as possible.

I made sure that I needed only to make the changes in this repository, to not having a chain of dependent pull-request which would only make releasing the code harder.

 I verified this by testing with the officially released command line client (unchanged), while running the changed daemon application in Swarm mode. This allowed me to see all tasks being created and changing, until they either Failed or got removed.

**- How to verify it**
* Check out the code for this pull-request
* Build the daemon binaries
    ```
    make
    ```
* Run the daemon
    ```
    sudo ./bundles/binary-daemon/dockerd
    ```
* Init Swarm mode
    ```
    docker swarm init
    ```
* Open a second terminal window and start listening for events with type task
    ```
    docker event --filter type=task
    ```
* In the first terminal, create a new service and watch the magic happen!
    ```
    docker service create --name nginx nginx:latest
    ```

Now you should see lots of task events turning up in the second terminal.

**- Description for the changelog**

Implemented watchable task events for swarm

### CODE REVIEW

**Comment by artheus** [comment]
Attempting to fix coverage issue, :hourglass_flowing_sand:

**Comment by artheus** [comment]
Increased the default timeout, by 5 seconds, in the swarm API test.

I do not think that this is the correct way to go forward, as the raft election timeout seems to be somewhere around 15 seconds. So I suspect my code to inflict some kind of delay in the election flow.

From what I can gather, it seems that the delay caused by my change-set might be due to part(s) of the docker/swarmkit project.

I will await further input from other contributors to this project, before going further with this as an issue.

**Comment by vdemeester** [comment]
As this is a duplicate of PR #37441, I'll close mine :wink:

**Comment by artheus** [comment]
@vdemeester 
> As this is a duplicate of PR #37441, I'll close mine 😉

I tried finding as many related issues and PRs as possible. It seems I am not very good at it.
Sorry for totally running over your PR. Thank you for the positive response, though!
👍

**Comment by artheus** [comment]
The failed test in `powerpc` seems to be completely related to the earlier failure in `janky`, my change seems to delay teardown of tasks, which in turn seems to delay the Raft Election timeout in Swarm clusters. I would say that this should be considered unexpected behaviour, from just adding a watch for tasks.

Though, it might be that the step-down from leader in the daemon is done pre-maturely (without this patch), when we do not listen for tasks, since there might be tasks still there, which we do not know about in the daemon.

I would be very grateful for any input on this.

**Comment by aaronlehmann** [comment]
I remember that in the past tasks were excluded here because the event buffer only had a limited size, and we were afraid that task events would overwhelm it. Has that changed in the time since then?

**Comment by artheus** [comment]
I can look into testning that. Anyone up for looking into the delay?

**Comment by olljanat** [comment]
Derek add label: rebuild/powerpc

**Comment by artheus** [comment]
@vdemeester @aaronlehmann I was just thinking about this issue, and the only Use-case I have for this is for proxies and load-balancers (for example Traefik) to be able to listen to this kind of events, so that it can reconfigure and start proxying to the new containers in swarm.
How would it be to start sending swarm-scoped events for whenever a container attaches/connects to an existing overlay network?

One other idea/thought I've been having is to let the Event buffer limit be configurable, and also let the task events be configurable. Something like how the "Task history limit" is now configurable on swarm level.

And one last thing. What about "Event output drivers" where the default behaviour is to use the internal buffering etc. But if you use a driver for this, all events will just be sent at the driver, disregarding any internal limits. For example, a Kafka driver which will just forward all events as JSON to a Kafka cluster.

**Comment by artheus** [comment]
I could make Pull-requests for any of these ideas. Though first, I would like a discussion which would lead to an agreement on which would be the preferable way to go.

**Comment by cpuguy83** [comment]
@artheus I think an event driver is a fantastic idea: https://github.com/moby/moby/issues/22917#issuecomment-318081442

Let's close this for now because tasks will most likely overload the event system today... and this has unfortunately gone really stale at this point.
This is more housekeeping than a rejection. 😇

**Pull request closed without merging**
