### PR TITLE
Article error in api/types/types.go

### PR DESCRIPTION
**Pull request by EnergyLiYN**

### CODE REVIEW

**Comment by allencloud** [comment]
has been covered in https://github.com/docker/docker/pull/29527

**Comment by EnergyLiYN** [comment]
Don‘t include this issue @allencloud

**Comment by allencloud** [comment]
In https://github.com/docker/docker/pull/29527/files, we can find that:

**Comment by thaJeztah** [comment]
Yes, this is included in https://github.com/docker/docker/pull/29527. Closing this one

**Pull request closed without merging**
