### PR TITLE
Fix some typos in comments and strings

### PR DESCRIPTION
**Pull request by stweil**
Most of them were found and fixed by codespell.

Signed-off-by: Stefan Weil sw@weilnetz.de

### CODE REVIEW

**Comment by calavera** [comment]
LGTM. Thanks!

**Comment by stweil** [comment]
For typos in the `vendor` directory I'll send a separate pull request.

Should I ignore the 4 failing checks / is there already someone working on those failures?

**Comment by calavera** [comment]
@stweil please, do **NOT** do that in the `vendor` directory. Those packages are updated automatically from their original sources.

**Comment by thaJeztah** [comment]
LGTM

**Pull request merged**
