### PR TITLE
Fixes deb package for Ubuntu 15.04 compatibility

### PR DESCRIPTION
**Pull request by aanc**
Ubuntu 15.04 introduces systemd as a replacement for upstart/SysV. As a result, docker startup script does not load variables from `/etc/default/variables`. This pull request is a proposition on how to fix that.

Associated issues: #12926 and #13384

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! IIRC, there was some work being done in this area, so I'll ping some people to have a look

ping @tianon @jfrazelle for deb packages and hack/make

**Comment by jfrazelle** [comment]
is a WIP and this has the same problems as #13415

**Comment by icecrime** [comment]
Ping @jfrazelle @tianon.

**Comment by tianon** [comment]
I'd actually be inclined to close this as a duplicate (https://github.com/docker/docker/pull/13923#issuecomment-112220002).

> See also #12134, #13415, #7220, and especially https://github.com/docker/docker/pull/5141#issuecomment-40940481, #3307, and #3627.

**Comment by jfrazelle** [comment]
closing

**Pull request closed without merging**
