### PR TITLE
Remove comments and unused structures in Windows resources

### PR DESCRIPTION
**Pull request by darstahl**
Signed-off-by: Darren Stahl <darst@microsoft.com>

**- What I did**

Removed a TODO that is finished.

Removed unused network structure, as it was implemented in HNS instead.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM.

Does this need a matching PR in opencontainers/runtime-spec? https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L477-L481

**Comment by darrenstahlmsft** [comment]
Pulled memory reservation in https://github.com/opencontainers/runtime-spec/pull/788, looking into networking. Might make sense to do some more stuff there.

**Comment by darrenstahlmsft** [comment]
Network Resource settings are removed by https://github.com/opencontainers/runtime-spec/pull/801

**Comment by jhowardmsft** [comment]
Restarted PPC again. Failure is unrelated. 

@johnstep PTAL

**Review by johnstep — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
