### PR TITLE
Vendor swarmkit and libnetwork in master

### LINKED ISSUE #25432: [swarm] corrupted manger not able to leave a cluster with --force
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: active
 NodeID: 2jml8zh2ap8gnw3ghchc03g09
 Error: rpc error: code = 2 desc = raft: no elected cluster leader
 Is Manager: true
 ClusterID:
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot interval: 0
  Heartbeat tick: 0
  Election tick: 0
 Dispatcher:
  Heartbeat period: Less than a second
 CA configuration:
  Expiry duration: Less than a second
 Node Address: 192.168.99.100
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: master1
ID: XFBC:QIPK:ZJH5:MGSZ:D6IA:32XG:TUHL:6E43:HXOQ:FVLW:OY64:HWD4
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 72
 Goroutines: 218
 System Time: 2016-08-05T09:22:12.607462985Z
 EventsListeners: 4
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
5 VirtualBox VMs cluster

**Steps to reproduce the issue:**
1. Create a cluster with 2 managers and 3 workers
2. Turn off the laptop

**Describe the results you received:**
```
docker@master1:~$ docker swarm leave
Error response from daemon: You are attempting to leave cluster on a node that is participating as a manager. The only way to restore a cluster that has lost consensus is to reinitialize it with `--force-new-cluster`. Use `--force` to ignore this message.
docker@master1:~$ docker swarm leave --force
Error response from daemon: context deadline exceeded
docker@master1:~$
```
manager logs -- 
[logs1.txt](https://github.com/docker/docker/files/403537/logs1.txt)

It might be related to https://github.com/docker/docker/issues/25395#issuecomment-237718994

**Describe the results you expected:**
```
docker@master1:~$ docker swarm leave --force
Node left the swarm.
docker@master1:~$
```
**Additional information you deem important (e.g. issue happens only occasionally):**

### LINKED ISSUE #27188: Execute syscall.NETLINK_XFRM from inside a container
Hi

I'm searching for a way how to execute syscall.NETLINK_XFRM from inside a container.

I tried to start the container with --privileged mode, without luck. I tried to run the container with `--security-opt seccomp=unconfined` as described in the [docs](https://docs.docker.com/engine/security/seccomp/) and also tried to extend the default docker profile by adding`"netlink_xfrm"` to the by default allowed syscall list (line 360 in the default.json), without success.

Can you tell me how I can make this syscall work? Is the seccomp profile the right way how to tackle that and if so, where and how should I specify the rule for this syscall?

Thank you for your help!

### LINKED ISSUE #27208: Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided
**Description**
```
$ docker deploy test
Loading bundle from test.dab
Creating network test_default
Creating service test_web
Creating service test_db
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided
```

I am following this tutorial:
http://blog.couchbase.com/2016/july/docker-services-stack-distributed-application-bundle

**Output of `docker version`:**
```
$ docker --version
Docker version 1.12.2-rc2, build ad9538a, experimental
$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 84
Server Version: 1.12.2-rc2
Storage Driver: devicemapper
 Pool Name: docker-253:0-105335-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.727 GB
 Data Space Total: 107.4 GB
 Data Space Available: 42.08 GB
 Metadata Space Used: 15.2 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: d85uyvzk62u9tcc3ea9svxhz2
 Is Manager: true
 ClusterID: dnei7dxkorw97wwa2sei3vbit
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.101.169
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 7.633 GiB
Name: dr-host
ID: BTUN:L4DP:LBBK:6GYY:ELP4:5QVA:RAXG:JGMO:XWJ7:LZNE:2VFN:SO37
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 dr-host:5000
 127.0.0.0/8

*** SWARM CONFIG
1 Leader, 3 extra nodes
I am running the above commands on the leader
```

### LINKED ISSUE #27382: Swarm mode. replicas than wanted
I started a service (storm-supervisor below) and assigned the replicas to be 3. However it turned out to be 17 running, this list shows the node rejected the task but still started the container.
The docker version is 1.12.2-rc3

```
test@ubuntu-7:~$ docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
1n0vlxe76smi1t4gnpear37gr    ubuntu-8  Ready   Active        
cth31u6fgp4d4juelqgt1794s *  ubuntu-7  Ready   Active        Leader
dv7mgk4fjyhcodvb2i0lnsl01    ubuntu-9  Down    Active        
```

```
test@ubuntu-7:~$ docker service ls
ID            NAME              REPLICAS  IMAGE                                    COMMAND
0gzfp9urn3ke  zookeeper1        1/1       sun/zookeeper                            
24ozqnx7yegv  zookeeper2        1/1       sun/zookeeper                            
27p97mbzzejy  mysql             1/1       mysql:5.6                                
2d5u293rvuoy  storm-supervisor  17/3      sun/storm                                start-service supervisor
```

```
test@ubuntu-7:~$ docker service ps storm-supervisor 
ID                         NAME                    IMAGE      NODE      DESIRED STATE  CURRENT STATE                    ERROR
0ifny4a9m19e3i5gapbcbyi0w  storm-supervisor.1      sun/storm  ubuntu-7  Running        Running 2 days ago               
7lmghokgg3bec3zf6nctv34b8   \_ storm-supervisor.1  sun/storm  ubuntu-9  Shutdown       Shutdown 2 days ago              
dd8t8yugy48n7gg5w2u01j3y2   \_ storm-supervisor.1  sun/storm  ubuntu-8  Shutdown       Rejected 2 days ago              "No such image: sun/storm:late…"
7kbrt7goamiakpheeez8dttcz   \_ storm-supervisor.1  sun/storm  ubuntu-8  Shutdown       Rejected 2 days ago              "No such image: sun/storm:late…"
660hca32708qqhmxjr6w5kikg   \_ storm-supervisor.1  sun/storm  ubuntu-8  Shutdown       Rejected 2 days ago              "No such image: sun/storm:late…"
b3n1c68wiaiwaow0z0emk1v35  storm-supervisor.2      sun/storm            Ready          New 4 seconds ago                
75y6f8snr815mlxftvs7c93xt   \_ storm-supervisor.2  sun/storm            Running        New 8 seconds ago                
33yf727hd1060gqc11f1zlmrd   \_ storm-supervisor.2  sun/storm  ubuntu-8  Running        Rejected less than a second ago  "No such image: sun/storm:late…"
11jjatalgjk9eqnozjdmyoutc   \_ storm-supervisor.2  sun/storm            Running        New 15 seconds ago               
ca0hlq6ghm6qxl52ex4ep3ldj   \_ storm-supervisor.2  sun/storm            Running        New 20 seconds ago               
emezr2phew6hcfw48tqp9punj   \_ storm-supervisor.2  sun/storm            Running        New 22 seconds ago               
0o3pdta4snler710l3laq4wtv   \_ storm-supervisor.2  sun/storm            Running        New 25 seconds ago               
0ybhr8d0tp89t0e8pc78wh2vf   \_ storm-supervisor.2  sun/storm            Running        New 42 seconds ago               
98qf9vfi1xdq74ghiktlpkvva   \_ storm-supervisor.2  sun/storm            Running        New 47 seconds ago               
b7vcmu8h7etgt2aekcn4c7pn4   \_ storm-supervisor.2  sun/storm            Running        New about a minute ago           
bk5hjxqasfitph6ltaqbnpvv8   \_ storm-supervisor.2  sun/storm            Running        New about a minute ago           
3qj5z9s9trs6bjanio84essjr   \_ storm-supervisor.2  sun/storm            Running        New about a minute ago           
17zvbraty2vcs034y92m0ngws   \_ storm-supervisor.2  sun/storm  ubuntu-8  Running        Preparing 3 seconds ago          
3kb5cehztmflm7j0aysk7z5ic   \_ storm-supervisor.2  sun/storm            Running        New about a minute ago           
892kon57zixt15fj8helix8ug   \_ storm-supervisor.2  sun/storm            Running        New 2 minutes ago                
2ml2kzvs4a7er3hozcfjyokvv   \_ storm-supervisor.2  sun/storm            Running        New 2 minutes ago                
esv41pfiu8e6dj0sfn2ox2y27   \_ storm-supervisor.2  sun/storm            Running        New 2 minutes ago                
7rig83vv5qu3o6tkxht0e6ruu   \_ storm-supervisor.2  sun/storm            Running        New 3 minutes ago                
evc9byp39f4cixpdrxusfb24z   \_ storm-supervisor.2  sun/storm            Running        New 3 minutes ago                
7j9kyrhm4mb9w16ala75y39nv   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 47 hours ago             
4ktwo4yrumeh5miqr0isp7qgz   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
2bkpkw9k2c2mtjft4jk00g6bm   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
2757j57ehfujdqjbm71f3w1wg   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
cyu7cj4owb6vz93kqye1j1ht2   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
665f7jy4qm58sgragktki6vus   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
7sytyzdtcv60qk3fgl0962k7q   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
71lud0ryauickt4d2ygci0lkw   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
2gnjxtlp46w4izd06wcd06lk3   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
dyw0rilas0cw1siv69tyc13dm   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
cg7xt5725zxvanarb36v97jxx   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
2hy2kivzdvbqweabt0hx6isvo   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
erlo24b80scerc16owtty292m   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
95ppduiq0429a5pihpp9jw3fw   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
dzliaka2pmdk53tdoyl1nthk1   \_ storm-supervisor.2  sun/storm  ubuntu-7  Running        Running 2 days ago               
b45erxbuzkc8a6pjwd6kb6b78  storm-supervisor.3      sun/storm  ubuntu-7  Running        Running 2 days ago   
```            

```
docker service create \
--replicas ${SUPERVISOR_NUM} \
--name supervisor \
--network my-network \
--mount type=bind,src=/mnt/Package,dst=/package,readonly \
--mount type=bind,src=/mnt/Data/storm-logs,dst=/logs \
31z4/storm:1.0.2 \
storm supervisor -c storm.zookeeper.servers="${storm_zookeeper_str}" -c storm.log.dir="/logs" -c nimbus.seeds="${nimbus_seeds_str}"
```

### LINKED ISSUE #27390: Swarm mode services cannot publish ports as both TCP and UDP
**Description**

Docker swarm mode services cannot publish a port using **both** the TCP and UDP protocols.

**Steps to reproduce the issue:**
1. Create a swarm mode cluster.
2. Run: `docker service create --name test -p 10000:10000 -p 10000:10000/udp alpine sleep 100000`

**Describe the results you received:**
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided

**Describe the results you expected:**
The service should have been created with port 10000 mapped for both TCP and UDP.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 1.12.2
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 57efxfpx4yqzx3vha67pmv998
 Is Manager: true
 ClusterID: 4oabtzwdobpc29fioqyzt49kt
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.1.30
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.851 GiB
Name: manage-0
ID: CMHY:WEPP:RVWT:KJIP:RZ5G:ZIZH:FL2V:CENO:UISY:WVUM:NMF2:XPMV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Windows 10 on a local Hyper-V cluster of Ubuntu-16.04 VMs.

### LINKED ISSUE #27469: [1.12.2] Service create with two ports published fails
When creating a service that publishes two ports, but doesn't specify the host-port, service create fails;

```bash
$ docker service create --publish 80 --publish 443 --name web nginx:alpine
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided
```

Note that this works;

```bash
docker service create --publish 80:80 --publish 443:443 --name web nginx:alpine
```

And so does;

```bash
docker service create --publish 80 --name web nginx:alpine
```

or

```bash
docker service create --publish 80 --name web nginx:alpine
```

or 

```bash
docker service create --publish 80:80 --publish 443 --name web nginx:alpine
```

Based on the above (especially the last one), it looks like published multiple ports tries to assign the same "random" port multiple times.

Tested on;

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

and on Linux (to exclude it being a Docker for Mac issue)

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:39:06 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:39:06 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

This looks to be a regression in 1.12.2.

### LINKED ISSUE #27486: docker daemon in swarm mode is crashing periodically
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

docker 1.12 in swarm mode is crashing periodically

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

docker exited unexpected

**Describe the results you expected:**

docker daemon running constantly

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Exec command is forbidden for me, but I am sure the server version is
 
docker 1.12.1

**Output of `docker info`:**

I have to upload a snapshot for some reason.

b03bbc34-9ccd-4887-9d6d-97d6f7724351

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical CentOS 7.2  

**Logs triggered** 

http://pastebin.com/s71CxSaq

### PR DESCRIPTION
**Pull request by aaronlehmann**
Also update grpc, as it was updated in swarmkit.

swarmkit fixes:
Fixes #27382
Fixes #27208
Fixes #25432
Fixes #27469
Fixes #27390

libnetwork fixes:
Fixes #27486
Fixes #27188
Brings changes needed by #23397

cc @tonistiigi @dperny

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]

**Comment by mavenugo** [comment]
we need to get https://github.com/docker/docker/pull/27287 in before this PR to make sure plugin-v1 works e2e for network plugins.

**Comment by aaronlehmann** [comment]
Merged #27287, and rebased this PR.

**Comment by justincormack** [comment]
Thanks! LGTM

**Comment by justincormack** [comment]
@aluzzardi can you re-LGTM after changes...

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
