### PR TITLE
Add zsh completion for 'docker network ls -f {id,name,type}'

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #17782

@thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
Awesome! I wonder; should we split this up into two PRs? One for `id`, `name` and `type`, because those are supported in 1.11 (see https://docs.docker.com/engine/reference/commandline/network_ls/#filtering), and one that adds `driver`?

If there will be another patch release (not planned currently), that would allow us to cherry-pick just those changes in the release branch.

LGTM otherwise!

**Comment by sdurrheimer** [comment]
@thaJeztah Done, the 'driver' filter is ready in another branch.

**Comment by thaJeztah** [comment]
thanks!

LGTM

ping @albers @vincentbernat PTAL

**Comment by vincentbernat** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
