### PR TITLE
[Revert #26825] cli: remove `--mount` from `docker run`

### PR DESCRIPTION
**Pull request by AkihiroSuda**
> **Note**: This PR was merged again for docker 17.05 in https://github.com/docker/docker/pull/32251

**- What I did**
This commit reverts 273eeb813c1db0f42c2ad5e053972eeb00907568 (#26825).

For the discussion so far, please refer to #28527.
> * Secrets: accept src as a short name for the source argument.
> * Ports: remove --port and have --publish support the long syntax
> * Mounts: deprecate --mount (maybe remove it from run immediately) and have --volume support the long syntax.

**- How I did it**

removed `--mount` from `runconfig/opts`

**- How to verify it**

Observe the CI

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

penguins

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @icecrime @thaJeztah

**Comment by thaJeztah** [comment]
LGTM (if green). Thanks so much @AkihiroSuda

**Comment by justincormack** [comment]
Sorry is the plan to do a long syntax version of `--volume` for 1.13?

**Comment by icecrime** [comment]
@justincormack I don't think it'll make it for 1.13 :disappointed: See [this comment](https://github.com/docker/docker/issues/28527#issuecomment-262817805) for a summary.

**Review by vdemeester — COMMENTED** [review]
LGTM 😓

**Comment by LK4D4** [comment]
This has two lgtms and green.

**Comment by stevvooe** [comment]
Could we please un-remove this? The `--mount` flag really opened up a lot of possibilities for us and removing it is a HUGE step back.

Even worse, it looks like all these decisions were made over the thanksgiving holiday.

**Comment by thaJeztah** [comment]
@stevvooe I think the discussion is still open; main reason for reverting it is to keep all options open; would be good to look at it again

**Pull request merged**
