### PR TITLE
Move some integration api tests

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by duglin** [comment]
@cpuguy83 are you aware of https://github.com/docker/docker/issues/12255 and the dibs on it?

**Comment by cpuguy83** [comment]
@duglin No, not really :)

**Comment by duglin** [comment]
Just trying to avoid duplicate work efforts.

**Comment by duglin** [comment]
@brahmaroutu @cpuguy83 perhaps you guys could chat (via irc?) to coordinate?

**Comment by brahmaroutu** [comment]
@cpuguy83 I have https://github.com/brahmaroutu/docker/tree/integration_tests_12255 which is practically parallel to yours.

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
@cpuguy83 Need rebase

**Comment by cpuguy83** [comment]
rebased

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
