### PR TITLE
Do not add to local volume cache if the volume driver's scope is global

### PR DESCRIPTION
**Pull request by ssuvasanth**
**Fix**
This fix avoids the inconsistency in the cache data across hosts in a cluster if the volume driver is designed for a global scope. 
Hence, this fixes the need to handle stale entries in the volume cache if the volume is deleted outside the host, where the volume was created.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I'd like to see a test code (`integration-cli`?) that reproduces the inconsistency

**Comment by ssuvasanth** [comment]
@AkihiroSuda I have added an integration test that could show the inconsistency.
Thank you for letting me know about the integration-cli. I am becoming aware of the guidelines.

**Comment by ssuvasanth** [comment]
@AkihiroSuda @thaJeztah 
Integration test succeeds.
daemon.TestMigratePre17Volumes panics.
drivers.GetAllDrivers() works fine for all except the TestMigratePre17Volumes.  Should we change the above test case?

>21:47:36 goroutine 57 [running]:
21:47:36 panic(0x1192b00, 0xc420010090)
21:47:36 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
21:47:36 testing.tRunner.func1(0xc420494600)
21:47:36 	/usr/local/go/src/testing/testing.go:579 +0x25d
21:47:36 panic(0x1192b00, 0xc420010090)
21:47:36 	/usr/local/go/src/runtime/panic.go:458 +0x243
21:47:36 `github.com/docker/docker/volume/drivers.GetAllDrivers(0x0, 0x0, 0x0, 0x0, 0x0)`
21:47:36 	/go/src/github.com/docker/docker/volume/drivers/extpoint.go:182 +0x79
21:47:36 github.com/docker/docker/volume/store.(*VolumeStore).getVolume(0xc420319f20, 0xc420194c8a, 0x4, 0x5, 0x1, 0x7fc3eb6b1000, 0x0)
21:47:36 	/go/src/github.com/docker/docker/volume/store/store.go:412 +0x28f
21:47:36 github.com/docker/docker/volume/store.(*VolumeStore).create(0xc420319f20, 0xc420194c8a, 0x4, 0x132c9d3, 0x5, 0x0, 0x0, 0xc420395f80, 0x4, 0xc420049501, ...)
21:47:36 	/go/src/github.com/docker/docker/volume/store/store.go:271 +0xd5
21:47:36 github.com/docker/docker/volume/store.(*VolumeStore).CreateWithRef(0xc420319f20, 0xc420194c8a, 0x4, 0x132c9d3, 0x5, 0xc420395a00, 0x4, 0x0, 0x0, 0x0, ...)
21:47:36 	/go/src/github.com/docker/docker/volume/store/store.go:225 +0x136
21:47:36 github.com/docker/docker/daemon.(*Daemon).verifyVolumesInfo(0xc420049db0, 0xc42000e5a0, 0x4, 0xc42000e5a0)
21:47:36 	github.com/docker/docker/daemon/_test/_obj_test/volumes_unix.go:182 +0x3cc
21:47:36 github.com/docker/docker/daemon.TestMigratePre17Volumes(0xc420494600)
21:47:36 	/go/src/github.com/docker/docker/daemon/daemon_unix_test.go:265 +0x66f
21:47:36 testing.tRunner(0xc420494600, 0x13f4270)
21:47:36 	/usr/local/go/src/testing/testing.go:610 +0x81
21:47:36 created by testing.(*T).Run
21:47:36 	/usr/local/go/src/testing/testing.go:646 +0x2ec
21:47:36 FAIL	github.com/docker/docker/daemon	2.036s
>

**Comment by AkihiroSuda** [comment]
IMO keeping the test code and updating GetAllDrivers would be safer than changing the test code

PTAL maintainers

**Comment by cpuguy83** [comment]
NOTLGTM

Stale cache entries are being handled in #27164

**Comment by ssuvasanth** [comment]
@cpuguy83 Thank you for the update.
There are 2 problems in the solution from PR #27164 related to the issue #27129.

1. Let's assume that an external driver `dr1` created a volume `vol1` in `host1` and now the `vol1` is deleted on `host2` by `dr1` (whose scope is global). Now the `host1` is not aware of the delete. The fix in #27164 allows another driver dr2,etc or local volume driver to create a volume with the same name `vol1` in `host1`. 
But it fails when the same `dr1` tries to create the same `vol1` in the same `host1`.

2. The PR #27164 still does not eliminate the inconsistency in volume cache in a global context:
    After creation of `vol1` by `dr1` on `host1`, the `host1`'s cache have `vol1` but not `host2`. 
    After deletion, `host1` still have `vol1` in its cache while `host2` never had any cache entry for `vol1` and it simply had to check with `dr1`(instead of cache) whose scope is global.

This inconsistency in the volume cache when the `vol1` is globally accessed in a cluster is undesirable.
And it looks a lot cleaner when we avoid adding the `vol1` to the cache at the cost of one extra 'getvolume()' in addition to checking in the cache when the volume's scope is `global`.

We can handle the cache for global volumes in swarm using zookeeper or swarm's in-built kv store, but that should be a different PR according to me. (correct me if I am wrong).

Even if we are going with the implementation of global cache in swarm, the handling of global volumes in local cache is still necessary and I think the approach in this PR still stands.

Please let me know your thoughts @cpuguy83 @AkihiroSuda @thaJeztah 

Btw, PR #27177 (which added a commit to #27164 ) was a mistake by me(I was new to the PR workflow). I have added a note in #27164 and I apologise again.

**Comment by cpuguy83** [comment]
@ssuvasanth The inconsistency is non-ideal but should be addressed correctly, with a global store.
The inconsistency is really irrelevant as the cache is only used to ensure unique names, the volume will not be displayed or referenceable unless it actually exists in the driver.
With the above PR it should fix issues with stale cache entries on create.
Also note that even with a global store we'll still need to handle stale entries.

The cache is not per-driver, it's for all drivers. Not consulting the cache because the driver reports that is is "global" is backwards. We need to ensure name uniqueness across all drivers, not just in a single driver (which in such a case I'd rely on the driver to handle anyway).

**Comment by ssuvasanth** [comment]
@cpuguy83 I am convinced. Volume names should be unique even if the driver that created it is offline and we need a cache in volume store for that. My intention of having a dual cache - one for local and one for global volumes is eradicated by the idea of a common global store. I am loving it.
Thank you @cpuguy83 .
Btw, where could the global store ideally keep the volume cache when implemented? I think that should not be the nodes' memory and in a location that could be accessed by all nodes(Eg: zookeeper). 
- Cheers, Vasanth

**Comment by thaJeztah** [comment]
Looks like this one should be closed, pending a different implementation, but let me know if I closed by mistake

**Comment by cpuguy83** [comment]
@ssuvasanth In swarm-mode, probably the swarm data store.
In none-swarm mode, the configured K/V store.

**Pull request closed without merging**
