### PR TITLE
Vendoring libnetwork

### LINKED ISSUE #14396: Unable to link to postgres container with docker-engine 1.7.0 on Fedora 22
#### Description of problem:
I am using the recommended Fedora 22 docker-engine (docker-engine-1.7.0-1.fc22.x86_64.rpm) from the [Fedora installation page](http://docs.docker.com/installation/fedora/).

Following the instructions on the [Dockerizing Postgresql](http://docs.docker.com/examples/postgresql_service/) and [Linking Containers](https://docs.docker.com/userguide/dockerlinks/#communication-across-links) docs pages I am unable to connect to a postgres container from the simple bash container via the psql command. I received the error:

```
psql: could not connect to server: No route to host
        Is the server running on host "172.17.0.8" and accepting
        TCP/IP connections on port 5432?
```

#### docker version
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

#### docker info
```
Containers: 1
Images: 16
Storage Driver: devicemapper
 Pool Name: docker-253:1-1319522-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 744.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 46.61 GB
 Metadata Space Used: 1.458 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.6-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 7.687 GiB
Name: *****
ID: NNLY:SH32:E4NY:4YV3:BQEJ:S5MV:QVOD:BQXZ:ED6T:H37F:4T5N:KABU
```

#### uname -a
```
Linux ***** 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

#### Environment details
Physical machine, Lenovo Thinkpad X220

#### How reproducible
Every time

#### Steps to Reproduce
1. Install docker-engine 1.7.0 as per the instructions for [Fedora 22 on installation page](http://docs.docker.com/installation/fedora/)
2. Follow the instructions on the [Dockerizing PostgreSQL page](http://docs.docker.com/examples/postgresql_service/)

#### Actual Results
Unable to connect to postgres container:
```
psql: could not connect to server: No route to host
        Is the server running on host "172.17.0.8" and accepting
        TCP/IP connections on port 5432?
```

#### Expected Results
Should connect to the postgres container and display the psql prompt.

#### Additional info
Tested on Mac OSX (Yosemite) with boot2docker 1.7.0 and Fedora 22 docker 1.6.0 from the fedora repo (installed using `sudo dnf install docker`) and in both cases it works fine.

### LINKED ISSUE #14859: fixed-cidr and default-gateway cause out of range error when subnetting bridge
The documentation for networking implies that I should be able to set a fixed-cidr which is a subnet of the bridge address. However the daemon barfs if the gateway I chose is not within the fixed-cidr range. This check should be that the gateway is within the CIDR of the bridge, not the fixed-cidr. 

    $ sudo ip addr add 192.168.0.254/24 dev docker1
    $ sudo docker -d --fixed-cidr=192.168.0.0/25 -b docker1 --default-gateway=192.168.0.250
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    INFO[0000] [graphdriver] using prior storage driver "aufs" 
    WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
    FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: requested ip is out of range 

Interestingly; Docker instances do get given the IPPrefexLength of the bridge. In my example /24, so there's no problem with assigning a default gateway outside of the fixed-cidr. 

My use case is that I want to have a bridge attached to a physical/virtual nic on multiple docker hosts, and allow containers on the hosts to share a Layer 2 network and use an external router.

$ docker --version
Docker version 1.7.1, build 786b29d

$docker info
Containers: 19
Images: 35
Storage Driver: aufs
 Root Dir: /home/data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-41-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.39 GiB
Name: goldfish
ID: SEDL:2YVT:EZLV:T44V:VBOB:74ME:NX4C:ZQFX:LBH2:QUXI:WCI3:RIGL
Username: tuxinvader
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

$ uname -a
Linux goldfish 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by mrjana**
Vendoring libnetwork commit f1c5671f1ee2133055144e566cd8b3a0ae4f0433

Fixes #14396 
Fixes #14859 

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

**Comment by LK4D4** [comment]
Isn't it possible to add tests for those issues?

**Comment by calavera** [comment]
@LK4D4 one of the changes has tests in the original PR:

https://github.com/docker/libnetwork/pull/288

The other change is very isolated to fedora, I think it will be hard to add a test:

https://github.com/docker/libnetwork/pull/409

**Comment by mrjana** [comment]
@LK4D4 @calavera Yeah we have a test for default gateway issue in libnetwork. Anything else that can be tested?

**Comment by icecrime** [comment]
LGTM

**Comment by icecrime** [comment]
@mrjana Many errors there:

```
Error response from daemon: Cannot start container 4d286287e3a6464c9715181dd3a19ce32896b62ecde302efbcb163f3dfe3bf8f: no available ip addresses on network
```

**Comment by mrjana** [comment]
@icecrime Know the issue. Will update the PR with a fix pretty soon

**Comment by icecrime** [comment]
Ignoring test which pings against docker.io.

**Pull request merged**
