### PR TITLE
Move Sven to alumni

### PR DESCRIPTION
**Pull request by thaJeztah**
Sven is very busy doing cool stuff, so moving him to our alumni list.

Thanks so much @SvenDowideit (you [merged my first PR!](https://github.com/docker/docker/pull/7185#issuecomment-50115023) \0/)

caption-comp-emu

/cc @docker/core-engine-maintainers

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐯
👍

**Comment by SvenDowideit** [comment]
LGTM!

and as my last act, I'll merge my removal from being able to merge :D

**Comment by thaJeztah** [comment]
Aye Aye!

**Comment by SvenDowideit** [comment]
Damn, should have pinged @metalivedev @jamtur01 and fred@!

**Comment by jamtur01** [comment]
LGTM :)

**Comment by metalivedev** [comment]
What's an alumni list? Does it get me a discount at IHOP?

**Comment by cpuguy83** [comment]
@metalivedev Discount on the Ribeye at IHOP.

**Comment by jamtur01** [comment]
Can I transfer my discount to Outback Steakhouse?

**Comment by SvenDowideit** [comment]
@fredlf - damnit, i couldn't remember your nic.

**Comment by SvenDowideit** [comment]
@jamtur01 nope - if i ever manage to get out your way, there's a game restaurant I want to go to :D

**Pull request merged**
