### PR TITLE
[WIP] Changing docker event message attributes to official ones

### LINKED ISSUE #20879: Modify docker event message to have labels in a single map
Currently docker merges labels with some container attributes in here: https://github.com/docker/docker/blob/master/daemon/events.go#L17

The way it is right now the user can start a container with the label "image=this-is-my-label" and that label won't show up in the docker events.

So my my proposal is:
- Somehow split engine-api message with labels in one map and remaining attributes in the other.

- Use the special labels assigned to docker e.g. "com.docker.container.image" and "com.docker.container.name"

Thoughts?

Ping @calavera

### PR DESCRIPTION
**Pull request by aanm**
**\- What I did**
Fixed https://github.com/docker/docker/issues/20879

**\- How I did it**
Change the attribute keys of events to have the official docker prefixes.

**\- How to verify it**
$ docker events --since=0
Then on a different terminal run
$ docker run hello-world

**\- A picture of a cute animal (not mandatory but encouraged)**
Docker in defense mode

Signed-off-by: André Martins aanm90@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like tests are failing

**Comment by thaJeztah** [comment]
ping @aanm were you still working on this?

**Comment by aanm** [comment]
Yep, still working on this. I thought it would be a quick change but is taking longer than I was expecting.

**Comment by thaJeztah** [comment]
yes, I noticed; no worries, let me change this to "WIP", and you can update the title back when it's ready for review. If you think it will take longer, would you like me to close this for now?

**Comment by aanm** [comment]
Please leave it open for now. Thank you

**Comment by aanm** [comment]
@thaJeztah Can you give me your input on this? I'm not sure if tests are failing because of my changes or not.

**Comment by thaJeztah** [comment]
@aanm given that all CI fails, there's probably a relation, but not sure what it is. Could be some part of the integration test suite still expecting the old event types?

**Comment by aanm** [comment]
@thaJeztah do you think this one is event related? I want to wait until all CI are green in master so I can rebase and see what the problem is.
```
22:58:28 FAIL: docker_cli_run_test.go:3662: DockerSuite.TestRunLinkToContainerNetMode
22:58:28 
22:58:28 docker_cli_run_test.go:3665:
22:58:28     dockerCmd(c, "run", "--name", "test", "-d", "busybox", "top")
22:58:28 /go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
22:58:28     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
22:58:28 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc820866540)} ("exit status 125")
22:58:28 ... "run --name test -d busybox top" failed with errors: /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: Conflict. The name "/test" is already in use by container 826a8e67a472b32d291d407070cb8b318bdf30e41062222bca5cef3f1aa16f07. You have to remove (or rename) that container to be able to reuse that name..
22:58:28 See '/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker run --help'.
22:58:28 , exit status 125
```

**Comment by thaJeztah** [comment]
@aanm that failure looks like a container wasn't removed; I saw more of those, so I'm wondering if some cleanup isn't triggered (due to an event not being recognized?)

I'll restart CI to see if there was just a general hiccup in the tests

**Comment by thaJeztah** [comment]
It's running again now

**Comment by aanm** [comment]
Made a new commit to see if this test still fails:

```
23:01:02 FAIL: docker_api_network_test.go:78: DockerSuite.TestApiNetworkInspect
23:01:02 
23:01:02 docker_api_network_test.go:85:
23:01:02     // run a container and attach it to the default bridge network
23:01:02     out, _ := dockerCmd(c, "run", "-d", "--name", "test", "busybox", "top")
23:01:02 /go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
23:01:02     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
23:01:02 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc820551a00)} ("exit status 125")
23:01:02 ... "run -d --name test busybox top" failed with errors: /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: Conflict. The name "/test" is already in use by container fb43c393dbdf0e5da8f4c7742858205c0bfa066b6d14b5574d2b5ad9be030159. You have to remove (or rename) that container to be able to reuse that name..
23:01:02 See '/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker run --help'.
23:01:02 , exit status 125
```

**Comment by thaJeztah** [comment]
@aanm I'm closing this for now to keep our tracker clean, but ping me if you had a chance to look at the tests

**Pull request closed without merging**
