### PR TITLE
Makes headings in documentation consistent

### LINKED ISSUE #10673: Docker headings using in consistent case
Our style guide states our headings should use sentence case but the implementation is inconsistent.  We should correct this. Also, menu's should match the case in the headings. Examples:

* https://docs.docker.com/
* https://docs.docker.com/userguide/dockerizing/
* https://docs.docker.com/installation/oracle/

I plan to do this one myself within the month sometime.

### PR DESCRIPTION
**Pull request by RickWieman**
This PR makes the headings of the documentation site more consistent, mostly by changing the capitalization (following the documentation style guidelines).
I manually walked through all the files and checked all the headings, so hopefully I tackled all inconsistencies :sweat_smile:

I skipped the older API references (I only did v1.9) and man pages, but I did update `mkdocs.yml`.

Fixes #10673.

If I missed something, or if I made some other mistake, please let me know and I'll fix it ASAP :blush:

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh, that's an awesome job! :heart: couple of nice catches as well (eg the "Using Chef" pagetitle).

Even in case you missed some; I think these are a great enhancement.

Two things that may need checking `apt-cacher-ng` and `cgroups`, to see if they should be all lowercase.

LGTM, but @moxiegirl will need to check if there are some special cases.

Bedankt!

**Comment by SvenDowideit** [comment]
very awesome - thank you!

I think I blacked out midway through reviewing, but it LGTM - so @docker/docs-owners - can someone start at the bottom? :)

**Comment by fredlf** [comment]
Wow, really great! Thanks so much for doing that. I checked about 2/3, starting at the bottom. 

Embarrassed by how many were on docs I've written or edited. And I'm the guy who wrote the style guide! :-) 

LVGTM

**Comment by moxiegirl** [comment]
Thanks Rick for doing this!  Needed doing and is obviously a popular PR in the docs team.  You get the Gatsby:

The Gatsby

**Comment by moxiegirl** [comment]
Rick can you rebase this? There is one conflict holding it back.

**Comment by RickWieman** [comment]
Nice to see that you all like it so much :smiley: 

Apparently the Amazon documentation was really shortened in the meantime, so I kicked out that file (which failed the first time due to a single space at the end of a line, hence the two forced pushes).

**Pull request merged**
