### PR TITLE
cmd/dockerd: unify flags, and remove opt.IPOpt()

### PR DESCRIPTION
**Pull request by thaJeztah**
- follow-up to https://github.com/moby/moby/pull/43509

See individual commits for details; more changes coming, related to validation and reload-logic, but opening PR's in smaller chunks to keep them focussed on specific areas.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@rumpl @ndeloof @tianon PTAL

**Review by tianon — APPROVED** [review]

**Review by rumpl — APPROVED** [review]
👍

**Comment by thaJeztah** [comment]
Thanks! Let me bring this one in

**Comment by thaJeztah** [comment]
Thanks! Let me bring this one in

**Comment by thaJeztah** [comment]
Interesting .... some github glitch 😂 
Screenshot 2022-04-29 at 09 20 00

**Pull request merged**
