### PR TITLE
make.sh: leave around the generated version

### PR DESCRIPTION
**Pull request by vbatts**
For positerity (largely of packagers) lets leave around the generated
version files that happen during build.
They're already ignored in git, and recreated on every build.

ping @tianon and @lsm5

Signed-off-by: Vincent Batts vbatts@redhat.com

### CODE REVIEW

**Comment by lsm5** [comment]
LGTM, this does help me build https://github.com/vbatts/docker-utils .

**Comment by duglin** [comment]
ping @brahmaroutu

**Comment by tianon** [comment]
This is essentially a revert of #10957, although that PR is sparse on the details of why it was opened (besides being "generally OK"). :disappointed:

**Comment by tianon** [comment]
I feel like there was a specific problem this was solving, but I can't remember what it was. :cry:

**Comment by brahmaroutu** [comment]
Generally, it is OK to leave them around. LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
does this need to be in 1.6.0

**Comment by vbatts** [comment]
I'd like to include it so the version is present for posterity in packages.

**Comment by tianon** [comment]
It's interesting to me that RedHat can (and prefers to) include build
artifacts like this in their "source" representations.  For Debian, the
focus is on the pristine, un-artifacted upstream source tarball (the "orig"
tarball), so build artifacts like this don't matter, especially since
they're trivially generated from the actual source code from upstream.
 (Just as some extra context for why I'm confused about this being good for
the packaging.)

**Comment by vbatts** [comment]
@tianon it is not to be confused with "orig" source, but like the btrfs
`version.h` that is a product of build and shipped in the -devel package.

**Comment by tianon** [comment]
Ahh, that makes more sense.

**Pull request merged**
