### PR TITLE
Prune command with dry run mode

### PR DESCRIPTION
**Pull request by adi-dhulipala**
This is a WIP PR to enable pruning volumes, containers, networks & images in dry-run mode.
I've opened this PR to track progress and request for comments.
The main discussion is on #30623

### CODE REVIEW

**Comment by yongtang** [comment]
@adhulipa Can you fix the issue of `dco/no`, as was reported by @GordonTheTurtle?

**Comment by adhulipa** [comment]
@yongtang will do!

**Comment by adhulipa** [comment]
Please excuse me for posting the WIP commit. I just wanted to save my work on my branch. But it looks like GitHub will also update my PR.

I still have to figure out how to write test for containers dry-run prune.

**Comment by adhulipa** [comment]
Looking into the failing checks.

**Comment by adhulipa** [comment]
I don't know what specifically was failing. Judgining by the logs from 
https://jenkins.dockerproject.org/job/Docker-PRs/51628/console
https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/301/console
https://jenkins.dockerproject.org/job/Docker-PRs-s390x/11899/console
I got the sense that I should pull in the latest changes and rebase my work.

Some errors I saw were
```
19:03:44 java.lang.NoClassDefFoundError: hudson.model.Computer
19:03:44 	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
```
The errors didn't seem related to my changes, but then again I'm new here and I'm probably missing something. 

I believe it may be difficult to review my changes since they include commits from other authors. 
Would you prefer for me to edit the PR such that only my commits show up?

**Comment by olljanat** [comment]
@adhulipa this one needs to be rebased

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by adhulipa** [comment]
Will update soon!

**Comment by drewcovi** [comment]
@adhulipa did this fail the review?

**Comment by olljanat** [comment]
@drewcovi it was not ever ready for review. Source branch looks to be very messy as it contains lot of commits which it should not and this have not ever passed CI build.

If someone plan to implement this one then please open new PR which is based on current master and contains only one commit.

**Comment by adhulipa** [comment]
@olljanat @drewcovi 
I will open a new PR (unless someone else needs help is building on top of my work; in which case, I'd be happy to pass along whatever knowledge I have)

The main thing is I haven't had a continuous block of time to work on this (sorry, I know this sounds like an excuse)

I'll open a new PR (a clean PR) when I get a chance again. Until then if someone else wants to work on this then I'd be happy to step back.

**Pull request closed without merging**
