### PR TITLE
docker stats: add blkio rate and blkio count

### PR DESCRIPTION
**Pull request by zhangyong-huawei**
Please provide the following information:
- What did you do?
- How did you do it?
- How do I see it or verify it?
- A picture of a cute animal (not mandatory but encouraged)

Signed-off-by: Zhang Yong zhangyong23@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can you provide a proper description of the pull request? (Also in the commit message)

Builds are failing, because this needs a gofmt;

```
11:04:00 These files are not properly gofmt'd:
11:04:00  - api/client/stats.go
11:04:00  - daemon/stats.go
11:04:00 
11:04:00 Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by zhangyong-huawei** [comment]
@thaJeztah thanks for your comments, I have updated the patch with gofmt and new commit log.

And also the short log for the pull is shown below, plese help review it, thanks.

blkio count is gotten from BlkioStats.IoServicedRecursive

blkio rate is calculated by introducing PreBlkioStats and PreRead in
types.Stats, thus we can get the rate by (BlkioStats - PreBlkioStats)/(Read - PreRead)

Now with the patch docker stats shows like below:
    $ docker stats
    CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BIO(Bytes)          BIO(Rate)           BIO(Counts)
    1285939c1fd3        0.07%               796 KB / 64 MB        1.21%               788 B / 648 B       3.568 MB / 512 KB   0 B / 0 B           37 / 35
    9c76f7834ae2        0.07%               2.746 MB / 64 MB      4.29%               1.266 KB / 648 B    12.4 MB / 0 B       0 B / 0 B           109 / 0
    d1ea048f04e4        0.03%               4.583 MB / 64 MB      6.30%               2.854 KB / 648 B    27.7 MB / 0 B       0 B / 0 B           211 / 0

**Comment by icecrime** [comment]
A few failures here!

```
01:46:20 # github.com/docker/docker/api/client
01:46:20 api/client/stats_unit_test.go:43: not enough arguments in call to calculateBlockIO
01:46:20 api/client/stats_unit_test.go:43: assignment count mismatch: 2 = 6
```

**Comment by zhangyong-huawei** [comment]
The patch is made before TestCalculBlockIO() is introduced.
I have updated the patch. And sorry for the noise.

Thanks,
ZhangYong

**Comment by cpuguy83** [comment]
Rate seems ok, but do we really need counts in the CLI?

**Comment by zhangyong-huawei** [comment]
By providing counts, the user can get bytes/transfer(even the IOPS);
thus the user could determine the most suitable block provider depending
on those info.

Thanks,
ZhangYong

**Comment by cpuguy83** [comment]
@zhanghuanzhong In such a case, I'd say let's provide IOPS instead of counts.
I take it as, what does an end user staring at the `docker stats` screen need to see. I doubt many will want to see write counts.  The API level is great to have write counts, but I think we should provide high level data in the `docker stats` UI.... just my opinion, let's see if anyone else agrees...

WDYT?

**Comment by thaJeztah** [comment]
agreed with @cpuguy83 - but perhaps at some point we could have a `--format` flag on stats, so that users can pick which stars they're interested in

**Comment by zhanghuanzhong** [comment]
@cpuguy83  I agree with you.

**Comment by thaJeztah** [comment]
@zhangyong-huawei can you rebase, and make the change as suggested by @cpuguy83 ?

**Comment by zhangyong-huawei** [comment]
@thaJeztah @cpuguy83 @zhanghuanzhong OK, I'll refresh the patch which provides IOPS instead of counts.

**Comment by zhangyong-huawei** [comment]
@thaJeztah @cpuguy83 @zhanghuanzhong  the patch is updated, please check it.

**Comment by thaJeztah** [comment]
@zhangyong-huawei ow :cry: looks like this needs another rebase already, or you missed some merge conflicts (see the output of the CI logs)

**Comment by thaJeztah** [comment]
@zhangyong-huawei will you be reopening a new PR?

**Comment by zhangyong-huawei** [comment]
@thaJeztah  I don't want to do that. The branch is removed is just because I have some problem to push my rebased branch. And I'm trying to fix it.

**Comment by thaJeztah** [comment]
@zhangyong-huawei alright, make sure you reopen the PR before you push, otherwise GitHub won't update. Feel free to open a new PR if that doesn't work

**Comment by zhangyong-huawei** [comment]
@thaJeztah  please check #21026, by the way, it passes my binary and test-unit test.

**Comment by zhanghuanzhong** [comment]
@zhangyong-huawei, thanks for your contribution.

**Pull request closed without merging**
