### PR TITLE
Add compose support of `attachable` in networks

### LINKED ISSUE #29975: [feat] Support network labels and attachable attributes in compose file format
I am missing the ability to pass labels and the 'attachable' flag to the networks declared in a compose file. That would allow me to let these be managed by docker stack instead of having to create them externally.

### PR DESCRIPTION
**Pull request by yongtang**
**- What I did**

This fix tries to address the issue raised in #29975 where it was not possible to specify `attachable` flag for networks in compose format.

**- How I did it**

This fix adds the support of `attachable` for compose v3.1 format.

**- How to verify it**

Additiona unit tests have been updated and added.

**- Description for the changelog**

Add support of `attachable` flag for networks in compose 3.1 format.

**- A picture of a cute animal (not mandatory but encouraged)**

wallpapers-wallpaper-pretty-flower-purple-photo-nice-flowers-high-resolution-images-green-lovely

This fix fixes #29975.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @dnephin @shin- PTAL

**Comment by AkihiroSuda** [comment]
What happens when you run  `docker stack rm foo`,  if there is a non-stack container attached to the stack network?

**Comment by dnephin** [comment]
cc @shin- for Compose file format changes that may impact docker-compose.

**Review by dnephin — APPROVED** [review]
LGTM

**Review by shin- — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
> What happens when you run docker stack rm foo, if there is a non-stack container attached to the stack network?

@dnephin ^^?

**Comment by dnephin** [comment]
I have no idea. Whatever happens when you do a `network rm` in that scenario. I guess it either fails or the container is forcefully removed by the engine?

**Comment by dnephin** [comment]
I tried it out:

```
$ docker network rm testfoo
Error response from daemon: rpc error: code = 9 desc = network gwsru0tunvf489g8nv3tan64j is in use by task 2w4j8yeiosez4mw90ana91l3y
```

**Pull request merged**
