### PR TITLE
[WIP] Improving load balancer performance

### PR DESCRIPTION
**Pull request by ahjumma**
**- What I did**
Improved swarm load balancer performance by setting a default sysctl variable.

**- How I did it**
Allowed IPVS connection table entries to be re-used rather than getting specially handled which was forcing clients to retry establishing TCP connections under a high load scenario.

**- How to verify it**

**- Description for the changelog**
Fixing #35082 
A detailed analysis is provided as a comment to the above issue at https://github.com/moby/moby/issues/35082#issuecomment-565245210.

**- A picture of a cute animal (not mandatory but encouraged)**
My lovely jindo dog :)
IMG_20191209_182503_691

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
thanks, but please submit to libnetwork repo and then revendor

https://github.com/docker/libnetwork

**Comment by ahjumma** [comment]
Hi @AkihiroSuda,

I have created a pull request at https://github.com/docker/libnetwork/pull/2491.
I will ping back once this change is accepted and pulled in at docker/libnetwork.

**Comment by ahjumma** [comment]
Hi @AkihiroSuda 

My pull request was accepted on libnetwork repo.
Could you please guide me through how I should revendor this repo?
I could not find guides on "vendoring" from [CONTRIBUTING.md](https://github.com/moby/moby/blob/master/CONTRIBUTING.md)

**Comment by AkihiroSuda** [comment]
Please update the libnetwork line in`vendor.conf` and then run `vndr` (https://github.com/LK4D4/vndr)

**Comment by ahjumma** [comment]
It looks like re-vendoring pull-request has been already made by @thaJeztah.
https://github.com/moby/moby/pull/40534

**Pull request closed without merging**
