### PR TITLE
Vendoring swarmkit a6519e28ff2a558f5d32b2dab9fcb0882879b398

### PR DESCRIPTION
**Pull request by abhi**
Signed-off-by: abhi <abhi@docker.com>

**- What I did**
vendoring swarmkit master branch

Includes 

- https://github.com/docker/swarmkit/pull/2468 Fix duplicate-IP or overlapping IP issues
- https://github.com/docker/swarmkit/pull/2376 Fix published ports not being updated if a service has the same number of host-mode published ports with PublishedPort 0
- https://github.com/docker/swarmkit/pull/2265 Make the task termination order deterministic

### CODE REVIEW

**Comment by abhi** [comment]
@fcrisciani @mavenugo

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by lbguilherme** [comment]
Will those fixes be backported to Docker 17.12.x? docker/swarmkit#2376 is causing issues on my production environment and the problem is fixed by upgrading to 18.01, but I don't want to be running on the Edge channel for this system

**Comment by thaJeztah** [comment]
Looks like this already went into 17.12; https://github.com/docker/docker-ce/pull/365

**Pull request merged**
