### PR TITLE
Rename GenericResources to NodeGenericResources in docker info

### PR DESCRIPTION
**Pull request by RenaudWasTaken**
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>

**- What I did**
Renamed GenericResources in NodeGenericResources in the info structure.

I realized displaying the Node Generic Resources in `docker info` would be a really useful feedback for the user and us when trying to orient users on how to use GenericResources.

**- How to verify it**
`dockerd  --node-generic-resources 'FOO=BAR' &`
`python3 -c 'import docker; client = docker.from_env(); print(client.info()["NodeGenericResources"])'`

Not a critical feature like #35970 just nice to have for 18.02, I have the CLI PR ready (without the revendoring).

cc @thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
I don't think we can change this; this field was added in API 1.32, so changing this means an API change; deprecation of the old field, and a different response based on which API version is called.

Not _impossible_, but I'm -1 on this if it's just for a 'nice to have'

**Comment by AkihiroSuda** [comment]
As @thaJeztah suggested, I think we should close this PR.

**Comment by thaJeztah** [comment]
Yes, I think we should close this one for now; if at some point we decide to do more extensive refactoring of this endpoint, we could include a change like this.

Closing for now, but feel free to discuss 👍

**Comment by RenaudWasTaken** [comment]
Sounds good will open a CLI PR with the old enpoint :)

**Pull request closed without merging**
