### PR TITLE
Check in latest Win2Lin Jenkins scripts

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Updating docker sources with the actual scripts currently running on Jenkins for the win2lin CI, and including the postbuild script (previously not checked in).

Note these are what actually is running in Jenkins and this PR is purely to sync sources to production. Obviously no functional changes in docker.

@mikedougherty

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by mikedougherty** [comment]
:+1:

**Comment by tiborvass** [comment]
LOL

**Comment by jhowardmsft** [comment]
Oh the irony of the Jenkins failure. Completely unrelated though. Kicked it off again.

**Comment by calavera** [comment]
LGTM

**Pull request merged**
