### PR TITLE
move resources parsing to ParseResources

### PR DESCRIPTION
**Pull request by hqhq**
Right now run and build will parse resources, in the future, set
will parse resources too, so it's needed to split the resources
configs into a separate function.

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by hqhq** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
Bunch of test failures

**Comment by hqhq** [comment]
@cpuguy83 Yeah, problem is it called `cmd.ParseFlags` twice, after some thought, I found it quite difficult to split the resource parsing. The whole FlagSet mechanisms (help info, error check, etc) are designed for one time parsing. Do you have any idea how we can do this?

**Comment by jfrazelle** [comment]
can you rebase please

**Comment by hqhq** [comment]
@jfrazelle Sorry this PR is still not working, I was thinking about close it, want to hear from @cpuguy83 and see if he has any idea how this can be archived.

**Comment by jfrazelle** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
I haven't had time to mess around with this, have a couple of ideas though.

**Comment by runcom** [comment]
I wonder if this still needs to be done due to #11442 being closed. Other than that I still like resource parsing to be moved

**Comment by runcom** [comment]
ping @cpuguy83

**Comment by LK4D4** [comment]
@cpuguy83 @hqhq What's up here? :)

**Comment by hqhq** [comment]
@LK4D4 @cpuguy83 I'll close this for now, will reopen when I figure out.
Thanks for your attention.

**Comment by cpuguy83** [comment]
Sorry, I'm traveling this week and have very limited time.

**Pull request closed without merging**
