### PR TITLE
Update doc style guide link, Fix #11568.

### LINKED ISSUE #11568: doc_style-guide.md was moved, but links remain unchanged in docs/README.md
In `docs/README.md` , the "Style guide" paragraph, "please see the style guide" links to `docs/sources/contributing/docs_style-guide.md`, but this document has been moved to `docs/sources/project/doc-style.md` in 8c575f2

### PR DESCRIPTION
**Pull request by southwolf**

### CODE REVIEW

**Comment by southwolf** [comment]
Sorry, my mistake. Already signed, please review. Thanks.

**Comment by SvenDowideit** [comment]
LGTM - @docker/docs-owners

**Comment by moxiegirl** [comment]
LGTM

**Comment by SvenDowideit** [comment]
oh. @southwolf you've signed one commit, but the first one is still unsigned.

its probably easiest to use `git fetch upstream && git rebase -i upstream/master` to rebase your commit, and then squash the 2 commits into one signed one.

**Comment by southwolf** [comment]
Since  moxiegirl  has already fix this document, I can close this PR now. Thank you @GordonTheTurtle  @SvenDowideit for the kind guides of using Git. Sorry for the troubles.

**Comment by southwolf** [comment]
Since  moxiegirl  has already fix this document, I can close this PR now. Thank you @GordonTheTurtle  @SvenDowideit for the kind guides of using Git. Sorry for the troubles.

**Pull request closed without merging**
