### PR TITLE
Added Logentries Driver

### PR DESCRIPTION
**Pull request by caarlos0**
Reopening https://github.com/docker/docker/pull/22699 because I removed my fork and github lost track of it.

Also made the changes asked by @thaJeztah .

Docs were made on PR https://github.com/docker/docker.github.io/pull/244

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

ping @vdemeester @albers @sdurrheimer if you could have a quick look at the completion scripts

**Comment by albers** [comment]
bash completion is perfect :+1:

**Review by sdurrheimer — APPROVED** [review]
ZSH completion LGTM

**Comment by thaJeztah** [comment]
Thanks @albers @sdurrheimer !

**Comment by caarlos0** [comment]
Thanks all!

**Comment by cpuguy83** [comment]
ping @caarlos0 can you take a look at bsphere/le_go#14 regarding licensing for le_go?

Thanks!

**Comment by caarlos0** [comment]
@cpuguy83 indeed there is no license... I'm not the owner of the lib though, maybe @bsphere can help us here :)

**Comment by bsphere** [comment]
@cpuguy83 @caarlos0 just added a LICENSE file to that repo (MIT).
let me know if you have any issues with such license

**Comment by cpuguy83** [comment]
❤️  thanks!

**Pull request merged**
