### PR TITLE
Add more maintainers to "auto-assign"

### PR DESCRIPTION
**Pull request by thaJeztah**
/cc @aaronlehmann @AkihiroSuda @aluzzardi @coolljt0725 @MHBauer @runcom @stevvooe as discussed per e-mail / slack 👍 

20090529021750_auto

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐻 👼

**Comment by runcom** [comment]
LGTM :)

**Comment by coolljt0725** [comment]
LGTM

**Comment by thaJeztah** [comment]
updated, added @duglin :smile:

**Review by MHBauer — APPROVED** [review]
lgtm

**Pull request merged**
