### PR TITLE
profiles/seccomp: use conditional (hard-coded) errNoRet for MIPS/non-MIPS

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to:

- https://github.com/moby/moby/pull/42836#issuecomment-963429850
- https://github.com/moby/moby/pull/42681#issuecomment-963433969
- https://github.com/opencontainers/runtime-spec/pull/1087#issuecomment-963463475

The value of ENOSYS differs between MIPS and non-MIPS architectures. While
this is not problematic for the embedded seccomp profile, it prevents the
profile from being saved as a portable JSON file that can be used for both
architectures.

To work around this situation, we include conditional rules for both arches.
and hard-code the value for ENOSYS in both.

For more details, refer to https://github.com/moby/moby/pull/42836#issuecomment-963429850
and https://github.com/opencontainers/runtime-spec/pull/1087#issuecomment-963463475

A test was added, which can be run with:

    go test --tags=seccomp -run TestLoadConditionalClone3 -v ./profiles/seccomp/

    === RUN   TestLoadConditionalClone3
    === RUN   TestLoadConditionalClone3/clone3_default_amd64
    === RUN   TestLoadConditionalClone3/clone3_default_mips
    === RUN   TestLoadConditionalClone3/clone3_cap_sys_admin_amd64
    === RUN   TestLoadConditionalClone3/clone3_cap_sys_admin_mips
    --- PASS: TestLoadConditionalClone3 (0.01s)
        --- PASS: TestLoadConditionalClone3/clone3_default_amd64 (0.00s)
        --- PASS: TestLoadConditionalClone3/clone3_default_mips (0.00s)
        --- PASS: TestLoadConditionalClone3/clone3_cap_sys_admin_amd64 (0.00s)
        --- PASS: TestLoadConditionalClone3/clone3_cap_sys_admin_mips (0.00s)
    PASS
    ok  	github.com/docker/docker/profiles/seccomp	0.015s

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tianon @AkihiroSuda @justincormack PTAL

**Review by tianon — APPROVED** [review]
LGTM

"Thanks!  I hate it."

:heart:

**Comment by thaJeztah** [comment]
Failure on Windows 2022 looks like a flaky (tracked in https://github.com/moby/moby/issues/42612);

```
=== RUN   TestRequestReleaseAddressDuplicate
    allocator_test.go:1531: IP 198.168.0.186/23 was previously allocated
--- FAIL: TestRequestReleaseAddressDuplicate (0.01s)
```

**Comment by thaJeztah** [comment]
discussing this change, and (see https://github.com/opencontainers/runtime-spec/pull/1087), perhaps the better solution is to fix the OCI spec to take a string instead of a number for the signal. This feature hasn't shipped yet in the OCI spec, so we can still fix it.

**Pull request closed without merging**
