### PR TITLE
Dockerfile: use TARGETPLATFORM with scopeo for frozen images stage

### PR DESCRIPTION
**Pull request by thaJeztah**
- this is the first commit from https://github.com/moby/moby/pull/43529

frozen-images stage doesn't use the download-frozen-image-v2.sh
anymore so we can effectively use TARGETPLATFORM from global scope.
The test util has been updated accordingly.

In a follow-up we can remove download-frozen-image-v2.sh script but
needs to look first at Dockerfile.e2e which seems not used anymore
in our pipeline.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Interesting; doesn't look related, but not sure I've seen this particular error before (integration-test (windows-2022, containerd, `./...`));

```
=== Failed
=== FAIL: github.com/docker/docker/integration/container TestWaitNonBlocked/wait-nonblocking-exit-random (1.64s)
    wait_test.go:44: assertion failed: error is not nil: Error response from daemon: failed to create shim task: hcs::CreateComputeSystem 5d19c8e979a045bb8db34788add4046c27e44e698d6d61a9c9be601bfb68a3cc: The parameter is incorrect.: unknown
    --- FAIL: TestWaitNonBlocked/wait-nonblocking-exit-random (1.64s)

=== FAIL: github.com/docker/docker/integration/container TestWaitNonBlocked (0.02s)
```

**Review by corhere — APPROVED** [review]
Is there any reason to keep `contrib/download-frozen-image-v2.sh` around?

**Comment by thaJeztah** [comment]
> Is there any reason to keep contrib/download-frozen-image-v2.sh around?

No _strong_ reason, other than that, at some point, it was used by many Kubernetes users to load images in their cluster. That said, I think someone already forked it as a standalone project, so perhaps it's fine to remove as well (it's a nice "reference" though on "how pull works").

**Comment by crazy-max** [comment]
> Is there any reason to keep `contrib/download-frozen-image-v2.sh` around?

Yeah we can remove download-frozen-image-v2.sh script in follow-up but needs to look first at Dockerfile.e2e which seems not used anymore in our pipeline. Didn't want to add too much refactoring in https://github.com/moby/moby/pull/43529

**Comment by thaJeztah** [comment]
@tianon this lgty?

**Comment by thaJeztah** [comment]
Discussed in the maintainers meeting, and possibly we can fix the same issue by adjusting the bash-script to take variant into account; @crazy-max will have a look if that's an option

**Comment by neersighted** [comment]
Closed in favor of the approach in #44114.

**Pull request closed without merging**
