### PR TITLE
🎉 Happy New Year!  🎉

### PR DESCRIPTION
**Pull request by timwangdev**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Haha, thank you! But it looks like you forgot to sign-off your commit; please follow the instructions above to fix that

**Comment by thaJeztah** [comment]
LGTM

**Comment by timwangdev** [comment]
Thanks!

**Comment by duglin** [comment]
While doing this, can you get some of the other files too?
NOTICE
pkg/symlink/LICENSE.BSD
pkg/symlink/LICENSE.APACHE
pkg/mflag/flag.go
pkg/mflag/flag_test.go
pkg/mflag/LICENSE

**Comment by timwangdev** [comment]
@duglin Done!

**Comment by duglin** [comment]
@timwangdev thanks!  Could you squash your commits down to one - then LGTM!

**Comment by timwangdev** [comment]
@duglin The commits have been squashed.

**Comment by duglin** [comment]
@timwangdev thanks! still LGTM

**Comment by thaJeztah** [comment]
Awesome, even better :-)

**Pull request merged**
