### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by OKEAMAH**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```markdown changelog

```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by OKEAMAH — COMMENTED** [review]
Xx

**Comment by cpuguy83** [comment]
What is the purpose of this PR?

**Review by OKEAMAH — COMMENTED** [review]
Cool

**Comment by thaJeztah** [comment]
Yeah, spam / bot account. Blocked, and closing this one.

**Pull request closed without merging**
