### PR TITLE
Correct the license

### PR DESCRIPTION
**Pull request by markelog**
According to https://apache.org/licenses/LICENSE-2.0#apply, this is how the apache license should be phraised. Also removed the current year, since it's not needed and relieves you from updating it every year

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Hm, no, I don't think this is correct (although the current LICENSE also isn't correct); the correct way is to;

- update the LICENSE file to be an _unmodified_ version of the license (so without copyright information in the license itself; that section is only an _example_
- add a license header to all files

There are different opinions on the year ranges (and that's still a bit of a grey area); I think the general concensus is that (if each file has a year mentioned) to _at least_ have the year in which a file was _added_, and if significant changes are made, to make it a "range".


The containerd project made similar changes a while back; https://github.com/containerd/containerd/pull/2108, and perhaps we should make the same modifications in this repository; they're using a tool to automatically add the headers to all files (and a check in CI to verify).

**Comment by markelog** [comment]
Wowzies, okay! Will update the PR

**Comment by thaJeztah** [comment]
Let me know if you need help (I started looking into that tool they used in containerd, but never had time to finish :sweat_smile:)

**Comment by AkihiroSuda** [comment]
I'm closing this, but please feel free to reopen if this change is still needed

**Pull request closed without merging**
