### PR TITLE
docker info show logging driver info

### PR DESCRIPTION
**Pull request by x1022as**
Signed-off-by: Deng Guangxing dengguangxing@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice!

I think this also needs to be added to the example output on http://docs.docker.com/reference/commandline/cli/#info

**Comment by thaJeztah** [comment]
Oh source file for that page is located here;
https://github.com/docker/docker/blob/master/docs/sources/reference/commandline/cli.md

**Comment by x1022as** [comment]
@thaJeztah , add it to docs/sources/reference/commandline/cli.md and docs/sources/userguide/labels-custom-metadata.md. Thanks

**Comment by thaJeztah** [comment]
:+1: Thanks! I *think* it's also [missing in the API docs](http://docs.master.dockerproject.com/reference/api/docker_remote_api_v1.18/#display-system-wide-information), now that I look at it, but that's not related to this PR

**Comment by jamtur01** [comment]
Docs LGTM Ping @moxiegirl @SvenDowideit @fredlf

**Comment by icecrime** [comment]
Why are we reviewing docs?

**Comment by icecrime** [comment]
I'm +1 on design, and I think it's simple enough for others to agree so I'm taking the liberty to push this to `2-needs-code-review`: maintainers speak up if you disagree :-)

**Comment by thaJeztah** [comment]
@icecrime apologies; the early docs review may be triggered by my earlier comment

**Comment by jfrazelle** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @moxiegirl @jamtur01

**Comment by jamtur01** [comment]
Docs LGTM

**Comment by moxiegirl** [comment]
LGTM

**Comment by icecrime** [comment]
<3

**Pull request merged**
