### PR TITLE
extract docker volume API from local

### PR DESCRIPTION
**Pull request by dongluochen**
Want to aggregate APIs for different docker functions. 

Signed-off-by: Dong Chen dongluo.chen@docker.com

### CODE REVIEW

**Comment by MHBauer** [comment]
I think this is interesting, because the API gets distributed by functional units vs being all in one place.

**Comment by dongluochen** [comment]
@MHBauer It's a refactor to group feature functions. It'd provide some flexibility in testing new features besides reducing complexity in local.go.                    
ping @vieux  @calavera

**Comment by calavera** [comment]
awesome, thanks @dongluochen!

LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
