### PR TITLE
Carries and closes 13361

### PR DESCRIPTION
**Pull request by moxiegirl**
Carries and closes #13361 

@gustavohenrique The .go file was already changed.  So, only the work on the .md file need be carried.

Signed-off-by: Mary Anthony mary@docker.com

cc/ @thaJeztah

### CODE REVIEW

**Comment by gustavohenrique** [comment]
Thanks @moxiegirl!

**Comment by thaJeztah** [comment]
Thanks Mary, LGTM

(this already got reviewed in the original PR, and author LGTM, so merging)

**Comment by thaJeztah** [comment]
Thanks for all the work and being patient, @gustavohenrique !

**Comment by moxiegirl** [comment]
Thanks @thaJeztah

**Comment by moxiegirl** [comment]
cherry-picked

**Pull request merged**
