### PR TITLE
Allow hostname to be updated on service

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM (cc @al)

**Comment by vieux** [comment]
LGTM (cc @al)

**Review by thaJeztah — CHANGES_REQUESTED** [review]
please update the reference docs as well https://github.com/docker/docker/blob/master/docs/reference/commandline/service_update.md

Also (if you want) the bash/zsh completion scripts

**Comment by dnephin** [comment]
updated the reference docs

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
