### PR TITLE
Provide graphics for Hello World page #11562

### PR DESCRIPTION
**Pull request by zelahi**
Providing gifs for the Hello world page. 

Summary:  Three new gifs were recorded and added to the hello world page.  The three gifs recorded are gifs following all the steps for each action.  
1. helloworld.gif
   - docker run ubuntu:14.04 /bin/echo 'Hello world'
2. interactivecontainer.gif
   - docker run -t -i ubuntu:14.04 /bin/bash
   - pwd
   - ls
   - exit
3. daemonized.gif
   -  docker run -d ubuntu:14.04 /bin/sh -c "while true; do echo hello world; sleep 1; done"
   -  /bin/sh -c "while true; do echo hello world; sleep 1; done"
   -  docker ps
   -  docker logs <process_name>
   -  docker stop <process_name>
   - docker ps

Referencing Issues: #11562 #16759 

Signed-off-by: Zuhayr Elahi elahi.zuhayr@gmail.com

### CODE REVIEW

**Comment by phemmer** [comment]
Git has never been good at storing large binary objects, and that docs/userguide/hello_world_images/daemonized.gif file would become the largest binary file in the repo.
Perhaps we could use https://git-lfs.github.com/ for these?

**Comment by zelahi** [comment]
Actually before we do that I think I want to make sure that the gifs are okay.  Because The other alternative I had to doing gifs to replace all the images

**Comment by thaJeztah** [comment]
@zelahi I've just had a conversation with the docs team and we're not sure we still need this. The original issue was created for the "Docker Birthday Party", and felt like a nice thing to add at the time, but the documentation layout has changed since, and we're not sure if the animated gifs are an "addition", or will have the opposite effect of "distracting" from the actual information on this page.

I'm really sorry (I know you spent quite some time to get the PR right), but I'm afraid I have to close this PR because of that. Your contribution is really appreciated, I hope you understand. :+1:

**Comment by zelahi** [comment]
Ahh its okay. No problem. I'll find another issue to work on.=)

**Comment by thaJeztah** [comment]
Thanks @zelahi, I felt quite bad having to close it :cry:

**Comment by zelahi** [comment]
I understand.  It wasn't a loss f as now I understand how to contribute and the process behind making contributions a lot better.  =)

**Comment by thaJeztah** [comment]
Good to hear! And looking forward to your future contributions!

**Pull request closed without merging**
