### PR TITLE
Add zsh completion for 'docker images' filters

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. https://github.com/docker/docker/pull/22369#discussion_r61688763

@vdemeester 

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐯
Thanks :wink:

**Comment by vdemeester** [comment]
@sdurrheimer needs a rebase :sweat: 
/cc @runcom @thaJeztah @jfrazelle @tianon for reviews

**Comment by sdurrheimer** [comment]
@vdemeester Done

**Comment by thaJeztah** [comment]
thanks! LGTM

**Pull request merged**
