### PR TITLE
build: buildkit now honors daemon's DNS config

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <tibor@docker.com>

Depends on https://github.com/moby/buildkit/pull/1060

### CODE REVIEW

**Comment by thaJeztah** [comment]
Build is failing on Windows;

```
02:59:01 # github.com/docker/docker/vendor/github.com/moby/buildkit/executor/oci
02:59:01 ..\..\vendor\github.com\moby\buildkit\executor\oci\mounts.go:96:34: undefined: ProcessMode
02:59:01 ..\..\vendor\github.com\moby\buildkit\executor\oci\mounts.go:99:8: undefined: ProcessSandbox
02:59:01 ..\..\vendor\github.com\moby\buildkit\executor\oci\user.go:23:21: undefined: user.GetPasswdPath
02:59:01 ..\..\vendor\github.com\moby\buildkit\executor\oci\user.go:27:20: undefined: user.GetGroupPath
```

**Comment by tiborvass** [comment]
Updated, PTAL @thaJeztah @tonistiigi

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]

**Comment by thaJeztah** [comment]
@tiborvass marked this one for cherry-pick; was that the intent?

**Comment by tiborvass** [comment]
It’s something that closes the gap between non-buildkit and BuildKit so I guess we could have it in a patch release yeah

**Comment by thaJeztah** [comment]
all green

**Pull request merged**
