### PR TITLE
api/server: fix profiler HTTP serving

### PR DESCRIPTION
**Pull request by unclejack**
This PR fixes the serving of the profiler over HTTP.

### CODE REVIEW

**Comment by unclejack** [comment]
ping @crosbymichael

**Comment by liusdu** [comment]
Hi, #11949 has fix your problem. you can rebase against the master and push again

**Comment by unclejack** [comment]
@liusdu Thank you for the ping! I appreciate it.

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
