### PR TITLE
add execute bit to contrib/report-issue.sh

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

but wondering if we actually use this script somewhere, I think it was only created as a work-in-progress

/cc @vbatts

**Comment by runcom** [comment]
the change LGTM, but as @thaJeztah pointed out, is there anyone using this script and is it up to date?

**Comment by vbatts** [comment]
I have no idea if anyone actually uses this. I would reckon probably not.

**Comment by thaJeztah** [comment]
Well, let's merge this and see if we want to keep this script after that

@glensc are you using this script?

**Comment by glensc** [comment]
@thaJeztah nope!

**Pull request merged**
