### PR TITLE
Fix workdir cache invalidation

### LINKED ISSUE #29950: WORKDIR not cached in build in 1.13.0-rc5 and master
With Dockerfile:
```
FROM alpine
WORKDIR /tmp
RUN sleep 10
```

build it twice with `docker build .`

```
 docker build .
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM alpine
latest: Pulling from library/alpine
0a8490d0dfd3: Already exists 
Digest: sha256:dfbd4a3a8ebca874ebd2474f044a0b33600d4523d03b0df76e5c5986cb02d7e8
Status: Downloaded newer image for alpine:latest
 ---> 88e169ea8f46
Step 2/3 : WORKDIR /tmp
 ---> 8cfc791cec6e
Removing intermediate container bbc25589a59a
Step 3/3 : RUN sleep 10
 ---> Running in eb89b7a78be0
 ---> c8b1cfdcd0ae
Removing intermediate container eb89b7a78be0
Successfully built c8b1cfdcd0ae
whale:buildcache justin$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM alpine
 ---> 88e169ea8f46
Step 2/3 : WORKDIR /tmp
 ---> 4afd83be5264
Removing intermediate container b700b978520a
Step 3/3 : RUN sleep 10
 ---> Running in 44863b0d200a
 ---> 768954eab6f7
Removing intermediate container 44863b0d200a
Successfully built 768954eab6f7
```

It sleeps both times, as `WORKDIR` no longer gets cached. This was fine in 1.13.0-rc4, it must have broken with the fixes in -rc5. Also broken on master where I first noticed it but it took me a while to work out where it was breaking.

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 1.13.0-rc5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.15-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: JB54:OBJA:7ZKI:HCAW:4KFH:TXX4:5ACG:RSRA:5CLU:OYXS:74FH:F2EY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 41
 System Time: 2017-01-06T16:10:30.828660221Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: justincormack
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #29950

@justincormack @yongtang

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
LGTM if janky is happy

**Comment by vieux** [comment]
LGTM

**Comment by yongtang** [comment]
Thanks @tonistiigi. It looks that when `b.commit()` is invoked, it actually used the `Cmd` from the container (associated with the `container.ID`), which is from `b.docker.ContainerCreate()`. While searching for the cache use the other one. I think the PR fix addressed the issue.

On a separate note, I feel like the context of the workdir has been changed. Maybe in the future we could think about if there are other ways for workdir?

**Comment by tonistiigi** [comment]
@yongtang Yes, definitely not obvious. There is `ContainerConfig` and `Config`. For builder case they only seem to differ by `Cmd`. Cache is based on `ContainerConfig` (needs to match the command of current command) but the parameter for `b.commit()` is `Config.Cmd`.

**Pull request merged**
