### PR TITLE
Respect `registry-mirrors` config when pull images from private repo.

### PR DESCRIPTION
**Pull request by haosdent**
**- What I did**

When pulling images from the private repository, use the addresses configured in `registry-mirrors` config if it exists.

**- How I did it**

Adjust condition check.

**- How to verify it**

Local test. According to the tcpdump result, it pull images from the `resitry-mirrors` if it is configured. 

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by haosdent** [comment]
This resolves an issue mentioned in https://github.com/dragonflyoss/Dragonfly/issues/299 .

**Comment by olljanat** [comment]
@haosdent CI fails to:
```
16:12:09 registry/service_v2.go:1::warning: file is not gofmted with -s (gofmt)
16:12:09 registry/service_v2.go:1::warning: file is not goimported (goimports)
```

**Comment by haosdent** [comment]
thx @olljanat , fixed 👍

**Comment by olljanat** [comment]
experimental and z failed to flaky test #37547 (which btw looks to be now fixed on #38499)

RS1 failed to #36801 which looks happening more rarely.

Let's try once more...

**Comment by olljanat** [comment]
Derek add label: rebuild/windowsRS1

**Comment by haosdent** [comment]
ohoh, thx @olljanat !

**Comment by olljanat** [comment]
@thaJeztah this one passes CI (except codecov) who would correct person to review it?

**Comment by haosdent** [comment]
Orz, thx @olljanat 's great helps!

**Comment by cpuguy83** [comment]
How is this related to #34319?

**Comment by haosdent** [comment]
@cpuguy83 thanks for the pr link, it lgtm if it could be merged. personally i think this pr didn't conflict with it. And in that pr, it try to resolve a bigger problem scope: config different registry mirror for different endpoint. That pr more like a feature while this pr try to fix a bug and avoid introduce new problems.

**Comment by cpuguy83** [comment]
Discussed this with maintainers today, I think we all agree the only way to really do this is to have this configured per registry otherwise you will end up with potentially conflicting image refs.
There is also an overarching issue here regarding auth for mirrors, passing through auth for the real registry to mirrors, and other such topics as discussed in https://github.com/moby/moby/issues/38591.

I don't think we can take this change in as is and encourage folks who want to see progress on this to take a look at #38591
Apologies on the late response! 😇

**Pull request closed without merging**
