### PR TITLE
WIP: Clearly indicate the demarcation of build stage in the build output

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Implement #36908

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Output is now

```
Sending build context to Docker daemon  3.584kB
Step 1/8 : FROM alpine
 ---> 3fd9065eaf02
Step 2/8 : RUN mkdir /stage1
 ---> Using cache
 ---> aaa8b3622f1c
Successfully built aaa8b3622f1c (stage: 0)
Step 3/8 : FROM alpine AS test
 ---> 3fd9065eaf02
Step 4/8 : COPY --from=0 /stage1 /
 ---> Using cache
 ---> 5bbf5a48c43a
Step 5/8 : RUN mkdir /stage2
 ---> Using cache
 ---> 4fed117aa3e0
Successfully built 4fed117aa3e0 (stage: test)
Step 6/8 : FROM alpine
 ---> 3fd9065eaf02
Step 7/8 : COPY --from=1 /stage* /
 ---> Using cache
 ---> 5d92b5fcd281
Step 8/8 : ENTRYPOINT ["ls"]
 ---> Using cache
 ---> 75c6d82559c2
Successfully built 75c6d82559c2 (stage: 2)
Successfully built 75c6d82559c2

```

**Comment by LaurentGoderre** [comment]
Any feedback on this?

**Comment by thaJeztah** [comment]
Thanks for contributing @LaurentGoderre - discussing this in the maintainers meeting, and we can see the information being useful, but we may need to look at the design; thing being discussed;

- perhaps we should start counting steps per stage (instead of globally)
- instead of showing the name of the stage after the committed image, put it at the same place as the `STEP X/Y`
- given that we're in the process of integrating BuildKit, we should make sure that we have similar information in BuildKit as well

Could you open a ticket in the buildkit repository https://github.com/moby/buildkit, so that we can discuss the design there, and once agreed on, implement it in both buildkit and here?

I'll close the PR here for now; let's discuss in buildkit after you opened an issue there 👍

**Comment by thaJeztah** [comment]
Continued in https://github.com/moby/buildkit/issues/521, and implemented in BuildKit in https://github.com/moby/buildkit/issues/549

**Pull request closed without merging**
