### PR TITLE
project: let's be done with ./hack/

### PR DESCRIPTION
**Pull request by vbatts**
@tianon @shykes et al

Signed-off-by: Vincent Batts vbatts@redhat.com

### CODE REVIEW

**Comment by tianon** [comment]
So, the reason I haven't made this change before now is because I think the plan is still to move the scripts somewhere else again, and that final location isn't necessarily decided on yet.

**Comment by tianon** [comment]
(I kinda wish we'd recreate `hack/` and move just the scripts back there with the docs left in `project/`, but I guess I was somewhat alone in being fond of the `hack/` name :angel:)

**Comment by vbatts** [comment]
where is that vote happening? because `./project/` is worlds better than `./hack/` and it follows along with the addition of https://dockerproject.com/ now, since it hosts the build, release, maintainers and packagers info... I couldn't see how a changing the name to something else would be _any_ more clear than `./project/` is.

**Comment by jfrazelle** [comment]
ya but we are also trying to get docker.org lol but someones sittin on it

**Comment by tianon** [comment]
https://github.com/docker/docker/issues/3502#issuecomment-63145996

**Comment by crosbymichael** [comment]
Sounds like this needs more talkin' bout the final plans for this dir.

**Comment by vbatts** [comment]
:8ball: says the future is cloudy

**Comment by crosbymichael** [comment]
probably right because you will have to have a dual with @tianon

**Comment by vbatts** [comment]
bad time tianon

**Comment by paultag** [comment]
thread of the year right here

**Pull request closed without merging**
