### PR TITLE
Better error messaging and logging for v2 registry requests

### PR DESCRIPTION
**Pull request by dmcgowan**
Adds uniformity to the v2 error messages as well as ensuring the error body gets into the debug logs.

### CODE REVIEW

**Comment by dmcgowan** [comment]
Fixes #10317

**Comment by dmp42** [comment]
LGTM - this is much needed! thanks!

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
FYI you have to put Fixes #10317 in the description for it to close the issue automagically.

**Pull request merged**
