### PR TITLE
Bump libcontainer to 6c198ae2d065c37f44316e0de3df7f3b88950923

### LINKED ISSUE #16206: 1.8.2-rc1: Docker-in-Docker pid=host fails to stop outer container
If you create a dind setup with --pid=host and launch a container the outer container can not be stopped.  Confusing, right?  Steps to reproduce.  I did this on an Ubuntu 14.04 host but should apply to all environments I assume:

Assuming `./docker` exists

1. Launch DIND

    ./docker run --name dind -it --privileged --pid=host -v /var/lib/docker -v $(pwd)/docker:/usr/bin/docker -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt busybox

2. Inside DIND launch Docker:

    docker daemon -D &

3. Launch container:

    docker run -d nginx

4. From host, stop dind outer container

    docker stop dind

You will see the following output from the outer Docker

```
INFO[0593] POST /v1.20/containers/951/stop?t=10         
DEBU[0593] Sending 15 to 951ac2b5f7ba2115fb26599165a5494889a54ccb73af39af1dc09c7cf72b6967 
INFO[0603] Container 951ac2b5f7ba2115fb26599165a5494889a54ccb73af39af1dc09c7cf72b6967 failed to exit within 10 seconds of SIGTERM - using the force 
DEBU[0603] Sending 9 to 951ac2b5f7ba2115fb26599165a5494889a54ccb73af39af1dc09c7cf72b6967 
WARN[0603] wait: no child processes                     
INFO[0613] Container 951ac2b5f7ba failed to exit within 10 seconds of kill - trying direct SIGKILL 
DEBU[0613] Cannot kill process (pid=3924) with signal 9: no such process. 
```

Doing a `ps` you see that `nginx`'s parent is now the host PID 1 and that the inner docker process has been killed.  A `docker ps` will show

````
951ac2b5f7ba        busybox             "/bin/sh"           11 minutes ago      Up 11 minutes                           dind
````

As you can see that container is considered running, but in fact the container PID is dead.  Any attempt to stop/kill the container will now result in the following

```
DEBU[0613] Cannot kill process (pid=3924) with signal 9: no such process. 
```

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

Ping @crosbymichael @LK4D4 @mrunalp 

Fixes #16206.

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM if green

**Comment by crosbymichael** [comment]
```go
if pr.Status == "green" {
    return crosbymichael.LGTM
}
panic("what have we done")
```

**Comment by jfrazelle** [comment]
lol

**Comment by LK4D4** [comment]
all red btw

**Comment by tiborvass** [comment]
@jfrazelle your `lol` has now even more meaning. (CI is red)

```
panic: what have we done

goroutine 1 [running]:
main.main()
	/janky:4 +0x42
exit status 2
```

**Comment by tiborvass** [comment]
For the record,

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x95c957]

goroutine 151 [running]:
github.com/opencontainers/runc/libcontainer/cgroups.func·001(0xc2086a3620, 0x5e, 0x0, 0x0, 0x7f63c0cfaa08, 0xc20811fe00, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/utils.go:332 +0x57
path/filepath.Walk(0xc2086a3620, 0x5e, 0xc2082df360, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:392 +0xb6
github.com/opencontainers/runc/libcontainer/cgroups.GetPids(0xc2086a3620, 0x5e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/utils.go:348 +0xa0
github.com/opencontainers/runc/libcontainer/cgroups/fs.(*Manager).GetPids(0xc2083ec720, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go:216 +0x142
github.com/opencontainers/runc/libcontainer.killCgroupProcesses(0x7f63c0d10570, 0xc2083ec720, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/init_linux.go:312 +0x18c
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Destroy(0xc2084b66c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/container_linux.go:242 +0x227
github.com/docker/docker/daemon/execdriver/native.func·002()
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:160 +0x4b
github.com/docker/docker/daemon/execdriver/native.(*Driver).Run(0xc208197d10, 0xc20818c000, 0xc2083426c0, 0xc208672b10, 0x1, 0x1, 0xc20848d530, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:196 +0xbca
github.com/docker/docker/daemon.(*Daemon).run(0xc208078dc0, 0xc20823fa00, 0xc2083426c0, 0xc20848d530, 0x0, 0xc2081fd600, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:950 +0x246
github.com/docker/docker/daemon.(*containerMonitor).Start(0xc208212f50, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/monitor.go:145 +0x484
github.com/docker/docker/daemon.*containerMonitor.Start·fm(0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:769 +0x39
github.com/docker/docker/pkg/promise.func·001()
	/go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x2f
created by github.com/docker/docker/pkg/promise.Go
	/go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xfb
...
```

**Comment by tiborvass** [comment]
Updated

**Comment by icecrime** [comment]
Still LGTM if green.

**Comment by tiborvass** [comment]
windows is always first to run ...

**Comment by tiborvass** [comment]
I wish there were a cheat button where we can empty all the build queue and prioritize this PR? :P

**Comment by crosbymichael** [comment]
@tiborvass u have to give sacrifices to the jenkins gods

**Comment by jfrazelle** [comment]
i spy green LGTM

**Comment by tiborvass** [comment]
omg it's building binaries!!

**Comment by abronan** [comment]
Such :green_apple: much wow

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
too slow @abronan

**Comment by tiborvass** [comment]
wow we were all just watching jenkins

**Comment by abronan** [comment]
totally :smile:

**Pull request merged**
