### PR TITLE
fixed typo in graphdb_test failure message

### PR DESCRIPTION
**Pull request by rileytg**
Signed-off-by: Riley Guerin rileytg.dev@gmail.com

### CODE REVIEW

**Comment by rileytg** [comment]
i think the test failure is unrelated:

```
---> Making bundle: test-docker-py (in bundles/1.8.0-dev/test-docker-py)
---> Making bundle: .integration-daemon-start (in bundles/1.8.0-dev/test-docker-py)
+++ /etc/init.d/apparmor start
 * Starting AppArmor profiles
Skipping profile in /etc/apparmor.d/disable: usr.sbin.rsyslogd
   ...done.
+++ exec docker --daemon --debug --host unix:///go/src/github.com/docker/docker/bundles/1.8.0-dev/test-docker-py/docker.sock --storage-driver vfs --exec-driver native --pidfile bundles/1.8.0-dev/test-docker-py/docker.pid --userland-proxy=true
......E..........................................................
======================================================================
ERROR: runTest (__main__.TestCreateContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/docker-py/tests/integration_test.py", line 153, in runTest
    res = self.client.create_container('busybox', 'true')
  File "/docker-py/docker/client.py", line 431, in create_container
    return self.create_container_from_config(config, name)
  File "/docker-py/docker/client.py", line 438, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/docker-py/docker/client.py", line 119, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/docker-py/docker/client.py", line 79, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
    raise Timeout(e)
Timeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=5)

----------------------------------------------------------------------
Ran 65 tests in 108.135s

FAILED (errors=1)
---> Making bundle: .integration-daemon-stop (in bundles/1.8.0-dev/test-docker-py)
+++++ cat bundles/1.8.0-dev/test-docker-py/docker.pid
++++ kill 30323
++++ /etc/init.d/apparmor stop
 * Clearing AppArmor profiles cache
   ...done.
All profile caches have been cleared, but no profiles have been unloaded.
Unloading profiles will leave already running processes permanently
unconfined, which can lead to unexpected situations.
```

How do I trigger a rebuild?

**Comment by rileytg** [comment]
@GordonTheTurtle should i be directing the question above at you?

**Comment by thaJeztah** [comment]
thanks for this! LGTM

to trigger a rebuild, you can ask a maintainer to do so in the #docker-dev IRC channel (providing the PR number)

**Comment by calavera** [comment]
LGMT. Thank you! merging

**Pull request merged**
