### PR TITLE
Change insane to infallible

### PR DESCRIPTION
**Pull request by ibuildthecloud**
I got what I felt was an unfortunately insensitive combination of insane + person so it just seemed better to not have that adjective.

### CODE REVIEW

**Comment by thaJeztah** [comment]
you're crazy :smile:

**Comment by vdemeester** [comment]
or should u say *insane* ! :joy_cat:

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
oh, yes, it does LGTM

**Pull request merged**
