### PR TITLE
integration-cli: add missing err check

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@runcom I think commit message looks like controversial to code(even if it's not). Maybe something about `dockerCmd`

**Comment by runcom** [comment]
@LK4D4 damn I was going to add it but thought not to lol

**Comment by runcom** [comment]
@LK4D4 updated

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
