### PR TITLE
More helpful error message when not sufficiently argumentative

### PR DESCRIPTION
**Pull request by justincormack**
The error message suggests you need one argument even when you
have provided one. Suggest having another argument.

Signed-off-by: Justin Cormack justin.cormack@docker.com

argument_clinic

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :heart_eyes_cat:

**Comment by vdemeester** [comment]
@justincormack need to update unit tests though :angel:

**Comment by justincormack** [comment]
@vdemeester ah yes...

**Comment by thaJeztah** [comment]
no argument here; LGTM :wink:

**Pull request merged**
