### PR TITLE
ZFS filesystem magic number check is fixed on FreeBSD

### PR DESCRIPTION
**Pull request by kvasdopil**

### CODE REVIEW

**Comment by estesp** [comment]
can you squash the commits to one?  Seems reasonable, by the way :)

**Comment by kvasdopil** [comment]
Done :)

**Comment by Mic92** [comment]
looks good to me.

**Comment by calavera** [comment]
I've restarted the build. Code LGTM.

**Comment by LK4D4** [comment]
Nice, thanks!
LGTM

**Pull request merged**
