### PR TITLE
Revendor libnetwork @ 36d3bed0e9

### LINKED ISSUE #1950: Saving endpoint to store fails in windows under concurrent load
We are trying to create a lot of parallel containers on windows. As part of the workflow multiple endpoints are being created and saved simultaneously. When this happens some container creation fails as docker is not able to save the endpoint to store:

time="2017-09-12T19:53:30.792343000-07:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: failed to create endpoint eager_newton on network nat: failed to save endpoint 53944a9 to store: failed to update store for object type *windows.hnsEndpoint: open C:\docker/network/files/local-kv.db.lock: The process cannot access the file cause it is being used by another process." error_type=types.internal module=api 

I am waiting for a repro machine to track this. Probably only happens on slow machines but creating an issue for tracking. This is also causing some noise in docker CI aswell.

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Fixes https://github.com/docker/libnetwork/issues/1950

This relates to a bunch of associated PRs, but ultimately is the fix for https://github.com/docker/libnetwork/issues/1950.

There is a bug in boltdb/bolt on Windows, which is unfortunately no longer maintained. The active maintained fork is now at https://github.com/etcd-io/bbolt. See https://github.com/etcd-io/bbolt/issues/121 for the bug, and https://github.com/etcd-io/bbolt/pull/122 for the fix. The tagged release with the fix is https://github.com/etcd-io/bbolt/releases/tag/v1.3.1-etcd.8.

Unfortunately, boltdb is used all over the place by many components. Hence to get this fix to moby/moby, I've had to go through https://github.com/docker/libkv/pull/202 which is where the database is used by libnetwork; then https://github.com/docker/libnetwork/pull/2268 to pull in the libkv fix; and now this PR to pull everything into moby/moby.

I still cannot remove boltdb/bolt from vendoring here as it's used by (at least) the following components still:

```
vendor/github.com/containerd/containerd/metadata/bolt.go:       "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/boltutil/helpers.go:   "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/buckets.go:    "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/containers.go: "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/content.go:    "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/db.go: "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/gc.go: "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/images.go:     "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/leases.go:     "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/migrations.go:import "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/namespaces.go: "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/metadata/snapshot.go:   "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/runtime/v1/linux/runtime.go:    "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/services/server/server.go:      "github.com/boltdb/bolt"
vendor/github.com/containerd/containerd/vendor.conf:github.com/boltdb/bolt e9cf4fae01b5a8ff89d0ec6b32f0d9c9f79aefdd
vendor/github.com/docker/swarmkit/agent/config.go:      "github.com/boltdb/bolt"
vendor/github.com/docker/swarmkit/agent/storage.go:     "github.com/boltdb/bolt"
vendor/github.com/docker/swarmkit/agent/worker.go:      "github.com/boltdb/bolt"
vendor/github.com/docker/swarmkit/node/node.go: "github.com/boltdb/bolt"
vendor/github.com/docker/swarmkit/vendor.conf:github.com/boltdb/bolt fff57c100f4dea1905678da7e90d92429dff2904
vendor/github.com/moby/buildkit/cache/metadata.go:      "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/cache/metadata/metadata.go:     "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/snapshot/blobmapping/snapshotter.go:    "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/solver/boltdbcachestorage/storage.go:   "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/solver/llbsolver/ops/exec.go:   "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/source/git/gitsource.go:        "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/source/http/httpsource.go:      "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/source/local/local.go:  "github.com/boltdb/bolt"
vendor/github.com/moby/buildkit/vendor.conf:github.com/boltdb/bolt e9cf4fae01b5a8ff89d0ec6b32f0d9c9f79aefdd
```

I've got a PR open to containerd/containerd here: https://github.com/containerd/containerd/pull/2634, but haven't yet opened PRs to ~~docker/swarmkit~~ or moby/buildkit. Those will follow shortly. Update - swarmkit opened. Buildkit depends on containerd PR.

There are three commits in this PR:

 - 1a6e2609ead86144b75067bfe5154dad5e42d5cf pulls in the latest libkv, and adds the required vendor for go.etcd.io/bbolt @ v1.3.1-etcd.8 which has the fix.
 - 5c20890b9b395564e18e4f8295539bcb8bf3d0de to update packages outside of vendor in the moby/moby repo which use boltdb/bolt and moves them to go.etcd.io/bbolt
 - 4ddebbe77f15da13f2f7736859cfc1939858d1a8 vendors libnetwork to the latest version, and also updates the libnetwork commit in `hack/dockerfile/install/proxy.installer`. I couldn't find any other places the libnetwork commit was referenced.

@mavenugo @johnstep @thaJeztah PTAL. 

@carlfischer1, @JMesser81, @dineshgovindasamy, @daschott FYI.

Phew! 💦 💦 💦

Full diff for Libnetwork;

- libnetwork (proxy); https://github.com/docker/libnetwork/compare/f30a35b091cc2a431ef9856c75c343f75bb5f2e2...36d3bed0e9f4b3c8c66df9bd45278bb90b33e911
- libnetwork (vendor); https://github.com/docker/libnetwork/compare/a79d3687931697244b8e03485bf7b2042f8ec6b6...36d3bed0e9f4b3c8c66df9bd45278bb90b33e911
  - https://github.com/docker/libnetwork/pull/2259 bridge: fix error handling for stale default gateways
  - https://github.com/docker/libnetwork/pull/2258 ipvs support get rs connection information (relates to https://github.com/kubernetes/kubernetes/pull/66012)
  - https://github.com/docker/libnetwork/pull/2069 Rolling back the port configs if failed to programIngress()

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@taylorb-microsoft FYI

**Comment by jhowardmsft** [comment]
> The question is should we wait for other PRs to be merged in other Repos and vendor them all together ? I personally dont think that is required.

@mavenugo No, it's not required. It is going to take some time to get those through - see for example this comment. https://github.com/containerd/containerd/pull/2634#issuecomment-420772074. I'll try my hardest though to get all components consistent ASAP.

**Comment by jhowardmsft** [comment]
docker/swarmkit PR opened at https://github.com/docker/swarmkit/pull/2748. Just moby/buildkit to go, and then revendoring them back into moby/moby

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Thanks! I looked at this a while back as well, and noticed I was opening the same can of worms (many projects using boltdb 😅

**Review by AkihiroSuda — APPROVED** [review]

**Comment by jhowardmsft** [comment]
containerd PR --> moby/moby is https://github.com/moby/moby/pull/37877

**Pull request merged**
