### PR TITLE
builder-next: disable mergeop and diffop

### PR DESCRIPTION
**Pull request by neersighted**
- Rebase of #45112 onto master
- Addresses #45111

Temporarily disable Merge/Diff until there is a proper solution to #45111. Dockerfiles will detect the missing capability for `COPY --link` and fall back to the behavior in 20.10.

### CODE REVIEW

**Review by tonistiigi — COMMENTED** [review]
Unless there is some time pressure with this, I'd make a different patch for master.

Merge/diff should be enabled when containerd is enabled. The ugly regexp can be avoided with some buildkit refactoring.

**Comment by neersighted** [comment]
The change is targeted to the graphdrivers as it's in `newGraphDriverController` -- as I understand it, mergeop and diffop are broken with the graphdriver backend until 0.12.x. If that's the case, there's a strong preference to accept a change on master first, even if it's immediately replaced with a better solution, to better understand the divergence of a previous branch and the development branch, and greatly reduce the chance a fix is ever missed.

**Comment by thaJeztah** [comment]
Looks like Ci is failing on master (perhaps differences between v0.10 and v0.11 of BuildKit and/or other changes)

**Comment by crazy-max** [comment]
> Merge/diff should be enabled when containerd is enabled. The ugly regexp can be avoided with some buildkit refactoring.

Will be sorted with https://github.com/moby/buildkit/pull/3711 hopefully. Will look like this in the workflow:

```yaml
      -
        name: Test
        run: |
          ./hack/test ${{ matrix.typ }}
        env:
          CONTEXT: "."
          TEST_DOCKERD: "1"
          TEST_DOCKERD_BINARY: "./build/moby/dockerd"
          TESTPKGS: "./${{ matrix.pkg }}"
          TESTFLAGS: "-v --parallel=1 --timeout=30m --run=//worker=dockerd$"
          BUILDKIT_TEST_FEATURE_MERGEDIFF: "0"
        working-directory: buildkit
```

**Comment by tonistiigi** [comment]
> Looks like Ci is failing on master (perhaps differences between v0.10 and v0.11 of BuildKit and/or other changes)

Yeah, that's a new test that didn't exist in v0.11.

**Comment by thaJeztah** [comment]
@neersighted looks like this one can be updated with changes from https://github.com/moby/moby/pull/45165 to help with CI (to skip tests)

**Comment by neersighted** [comment]
I've rebased on master and taken the solution from #45165; I'm updating #45112 next.

**Review by tonistiigi — APPROVED** [review]

**Review by crazy-max — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by corhere — APPROVED** [review]

**Pull request merged**
