### PR TITLE
Allow passing DOCKER_DEBUG= to `make`

### PR DESCRIPTION
**Pull request by aidanhs**
For easier debug builds

### CODE REVIEW

**Comment by aidanhs** [comment]
I suspect TestDaemonStartBridgeWithoutIPAssociation failing has nothing to do with this PR...

**Comment by icecrime** [comment]
Thanks! However I'm afraid we're dropping the `DEBUG` env var (cf #11965), and I'm not sure we do need this.

**Comment by aidanhs** [comment]
I'm not sure that's relevant. DEBUG in the makefile would be used to build docker with debugging symbols. See `hack/make.sh` - if DEBUG is not set, it excludes debugging symbols.

**Comment by icecrime** [comment]
My bad, I though the goal was to pass it down to running tests!

**Comment by aidanhs** [comment]
Turns out #10665 removed the DEBUG possibility without warning (which I didn't notice when devving on 1.5.0), so I've added that back now as well.
What are the chances of getting this in for the next release? Debug symbols are quite helpful.

**Comment by jfrazelle** [comment]
can you squash your commits LGTM otherwise

**Comment by aidanhs** [comment]
Done.

**Comment by thaJeztah** [comment]
ping @icecrime @tianon does this LGTY?

**Comment by tianon** [comment]
Yeah, I suppose this is OK, although I'm not too fond of using such a generic environment variable name for it (`DEBUG` is very likely to have lots of overlap with other projects and systems, so builders would be a lot more likely to have that set and then get no indication of why they have debug bits in their binaries that they didn't intend to).

**Comment by thaJeztah** [comment]
In that case, perhaps `DOCKER_DEBUG` to be in line with the other env vars?

**Comment by aidanhs** [comment]
I can make the change if you prefer, but this is just meant to be fixing any breakage.

Though since nobody apart from me has complained, there's an argument to be made that the breakage is near-nil.

**Comment by tianon** [comment]
+1 for "DOCKER_DEBUG" (especially since, as you point out, the impact is
pretty low)

**Comment by jfrazelle** [comment]
+1 DOCKER_DEBUG :)

**Comment by aidanhs** [comment]
Updated. Sanity check locally works.

**Comment by thaJeztah** [comment]
@aidanhs either GitHub is caching *really* aggressively or you forgot to stage changes, because I still see `DEBUG` in the PR

**Comment by aidanhs** [comment]
>.>
Fixed.

**Comment by thaJeztah** [comment]
Thanks! I kept refreshing the page to sanity-check myself LOLz


ping @jfrazelle @tianon the var was renamed, should be an easy review

**Comment by tianon** [comment]
LGTM

**Comment by tianon** [comment]
cc @jfrazelle

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
