### PR TITLE
Remove Pachyderm storage driver.

### LINKED ISSUE #19228: Doc link error: pachyderme volume plugin not found
Link at https://docs.docker.com/engine/extend/plugins/ to pachyderme volume plugin  link to 404 Not Found.

### PR DESCRIPTION
**Pull request by jdoliner**
closes https://github.com/docker/docker/issues/19228

### CODE REVIEW

**Comment by jdoliner** [comment]
We no longer have a volume driver. This in response to #19228

**Comment by tiborvass** [comment]
@jdoliner would you mind signing your work please as described in https://github.com/docker/docker/pull/19234#issuecomment-170550642 ?

**Comment by vdemeester** [comment]
ping @jdoliner

**Comment by jdoliner** [comment]
Sry for the delay, just pushed.

**Comment by vdemeester** [comment]
LGTM 🐶

**Pull request merged**
