### PR TITLE
integration-cli: TestSlowStdinClosing: add logs, and potential naming conflict

### PR DESCRIPTION
**Pull request by thaJeztah**
addresses ~(hopefully fixes)~ https://github.com/moby/moby/issues/43012

This test has become quite flaky on Windows / Windows with Containerd.

Looking at the test, I noticed that it's running a test three times (according
to the comment "as it failed ~ 50% of the time"). However;

- it uses the `--rm` option to clean up the container after it terminated
- it uses a fixed name for the containers that are started

I had a quick look at the issue that it was created for, and neither of those
options were mentioned in the reported bug (so are just part of the test setup).

I think the test was written when the `--rm` option was still client-side, in which
case the cli would not terminate until it removed the container (making the
remove synchronous). Current versions of docker have moved the `--rm` to the
daemon side, and (if I'm not mistaken) performed asynchronous.

~Due to the above, it's possible that, when iterating, the previous container still exists (Windows tends to be slower, so may also be slower to remove the container); combined with the test using a fixed name, this would cause a name conflict, causing the run to fail.~

This patch:

- removes the fixed name (the test doesn't require the container to have a
  specific name, so we can just use a random name)
- adds logs to capture the stderr and stdout output of the run (so that we're
  able to capture failure messages).

### integration-cli: TestSlowStdinClosing: use sub-tests
Use sub-tests so that the iterations can run in parallel (instead of
sequential), and to make failures show up for the iteration that they're
part of.

Note that changing to subtests means that we'll always run 3 iterations of
the test, and no longer fail early (but the test still fails if any of
those iterations fails.

Update: (see below); the failure looks to be specific to the Windows on containerd case, and is failing with;

```
=== RUN   TestDockerSuite/TestSlowStdinClosing
    docker_cli_run_test.go:4163: 
    docker_cli_run_test.go:4163: 
    docker_cli_run_test.go:4163: d:\CI\PR-43264\6\binary\docker.exe: Error response from daemon: failed to create shim: open \\.\pipe\containerd-29565631f602b7418a1df4233d21fb4d2a663689601e20424981c188624a6f9d-init-stdin: The system cannot find the file specified.: not found.
        
    docker_cli_run_test.go:4171: assertion failed: error is not nil: exit status 127
    --- FAIL: TestDockerSuite/TestSlowStdinClosing (7.95s)
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
/me grabs 🍿 to see what CI will say

**Comment by thaJeztah** [comment]
Okay; looks like it didn't fix it, but we do have more information now;

```
=== RUN   TestDockerSuite/TestSlowStdinClosing
[2022-02-18T23:45:31.220Z]     docker_cli_run_test.go:4169: d:\CI\PR-43264\1\binary\docker.exe: Error response from daemon: failed to create shim: open \\.\pipe\containerd-bbe99cae2aec8377dd236a57d14092c5022c3c41d4220eb393f26c478363d416-init-stdin: The system cannot find the file specified.: not found.
[2022-02-18T23:45:31.220Z]         
[2022-02-18T23:45:31.220Z]     docker_cli_run_test.go:4177: assertion failed: error is not nil: exit status 127

**Comment by thaJeztah** [comment]
Second run, and now it passes (in which case, the logs I added should probably be skipped);

```
[2022-02-19T11:45:16.010Z] === RUN   TestDockerSuite/TestSlowStdinClosing
[2022-02-19T11:45:18.955Z]     docker_cli_run_test.go:4163: 
[2022-02-19T11:45:21.902Z]     docker_cli_run_test.go:4163: 
[2022-02-19T11:45:24.849Z]     docker_cli_run_test.go:4163: 
```


I'll kick it once more to see if I can reproduce the flakiness (or if the failure the first time was just something unrelated)

**Comment by thaJeztah** [comment]
And one more time the same failure;

```
=== RUN   TestDockerSuite/TestSlowStdinClosing
    docker_cli_run_test.go:4163: 
    docker_cli_run_test.go:4163: 
    docker_cli_run_test.go:4163: d:\CI\PR-43264\6\binary\docker.exe: Error response from daemon: failed to create shim: open \\.\pipe\containerd-29565631f602b7418a1df4233d21fb4d2a663689601e20424981c188624a6f9d-init-stdin: The system cannot find the file specified.: not found.
        
    docker_cli_run_test.go:4171: assertion failed: error is not nil: exit status 127
    --- FAIL: TestDockerSuite/TestSlowStdinClosing (7.95s)
```

That's 2 out of six times that that failure happened.


I'll push a temporary commit, in which I re-add the container name to see if the failure we've seen here is the original failure for this test (or if there's possibly multiple reasons for this test to be flaky).

Perhaps also change the logging to only log something if there's actual output

**Comment by thaJeztah** [comment]
So, from the above; it looks like this PR is not fixing the issue (looks like it's not related to naming conflicts), but the changes in this PR at least make the error messages visible, and (with the change to use subtests) makes the iterations run in parallel, and easier to debug.

**Review by tianon — APPROVED** [review]
LGTM, but it might make sense to update the PR title so the merge commit is more accurate :sweat_smile:

**Review by cpuguy83 — APPROVED** [review]

**Comment by thaJeztah** [comment]
ah, crap. editing the title triggered CI again 😂 

It was ✅ .. I'll just bring it in 😂

**Pull request merged**
