### PR TITLE
Fix find and replace typo in dockerimages

### LINKED ISSUE #17920: Typo in docs
In this page: http://docs.docker.com/engine/userguide/dockerimages/

Instead of "Tip: You recommend you always use a specific tagged image, for example ubuntu:12.04. That way you always know exactly what variant of an image is being used.", it should be "Tip: We recommend you always use a specific tagged image, for example ubuntu:12.04. That way you always know exactly what variant of an image is being used."

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes #17920

Thanks for reporting, @sbasyal

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jamtur01 @SvenDowideit @moxiegirl ptal :smile:

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
danke!

**Comment by thaJeztah** [comment]
author LGTM thanks!

**Pull request merged**
