### PR TITLE
Vendoring libnetwork integrated with Docker discovery service

### PR DESCRIPTION
**Pull request by mavenugo**
This PR brings in end to end discovery and cluster-store integration with docker.
With this PR and #16645, docker multi-host networking will exit experimental.

cc @icecrime

### CODE REVIEW

**Comment by mavenugo** [comment]
@icecrime fixed the CI failures.
windows CI is failing on DockerSuite.TestExecStartFails which is not related to this change.

PTAL.

**Comment by ibuildthecloud** [comment]
Please merge soon :pray:

**Comment by icecrime** [comment]
LGTM (Windows CI issue tracked here #16738).

**Comment by vdemeester** [comment]
LGTM 🐼

**Comment by ibuildthecloud** [comment]
Woo Hoo!!!

**Pull request merged**
