### PR TITLE
Fix write after close on http response

### PR DESCRIPTION
**Pull request by dmcgowan**
Address #10228 but is not a confirmed fix

Both solutions should be valid and fix a possible panic caused by writing to an http.Response after the response has been finalized.  The fix in streams could fix a wider range of panics.  The registry fix is targeting a specific panic caused by a close on the progressreader being called by the network connection.  The NopCloser will prevent the network connection from being able to close the progressreader, which in turns attempts a flush on a writer bound to the http.Response to the client.

### CODE REVIEW

**Comment by stevvooe** [comment]
This PR should fix the panic but may be susceptible to leaking the `ProgressReader` (I am not really sure whether it will be garbage collected or not). I'm going to update this with a few commits that should shut this issue down.

**Comment by LK4D4** [comment]
drone failed

**Comment by dmcgowan** [comment]
This panic was also trigger on a v1 registry #9913

Configured nginx in the same way but yet to get a panic

**Comment by stevvooe** [comment]
@icecrime @jfrazelle I am going to back out the FlushingWriter changes to see if that clears up the tests.

**Comment by LK4D4** [comment]
Okay, I don't see harm in this PR. Also it is probably fixes pretty bad crashes :)
LGTM

**Comment by icecrime** [comment]
Agreed: I see no harm, only potential fixes. LGTM

**Pull request merged**
