### PR TITLE
Bump Go to 1.6rc1

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

Mi RC es su RC & vice versa :heart: 

Basically, if we ask and expect people to test our RCs, the minimum we can do to return the favor is to test others'.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Shouldn't we also update the RPM/deb build scripts? https://github.com/docker/docker/search?utf8=✓&q=GO_VERSION

**Comment by tiborvass** [comment]
@thaJeztah fixed

**Comment by thaJeztah** [comment]
LGTM :smile:

**Comment by tianon** [comment]
LGTM

**Comment by vdemeester** [comment]
> Basically, if we ask and expect people to test our RCs, the minimum we can do to return the favor is to test others'.

:heart_eyes_cat:

**Comment by jfrazelle** [comment]
yayyy!

**Comment by aaronlehmann** [comment]
I was curious what impact this had on build times, so I tried it out:

Go 1.5:

```
real    0m39.729s
user    1m31.600s
sys     0m26.280s
```

Go 1.6-rc1

```
real	0m37.315s
user	1m23.230s
sys	0m23.540s
```

**Comment by jfrazelle** [comment]
ITS BETTERRRRRRRRRR

**Comment by tianon** [comment]
Oh, my GitHub email comment didn't ever come through: As long as we don't release against the release candidate, I'm all for it!

**Comment by tianon** [comment]
There was also some IRC discussion: https://botbot.me/freenode/docker-maintainers/msg/58875061/

Do you think we could get some PR CI jobs setup for testing against Go 1.5 like we had for Go 1.4 once upon a time?  cc @jfrazelle

**Comment by jhowardmsft** [comment]
Can someone ping me right as this is about to merge as I need to take the Windows CI (both Windows to Linux and Windows TP4) offline to update the version of go on those servers too.

```
12:09:05 ---------------------------------------------------------------------------
12:09:05 WARN: CI should be using go version 1.6rc1, but it is using 1.5.3
12:09:05 
12:09:05        This CI server needs updating. Please ping #docker-dev or
12:09:05        #docker-maintainers.
12:09:05 ---------------------------------------------------------------------------
12:09:05 
```

**Comment by cpuguy83** [comment]
Looks like there's a change to `url.Parse` where it's actually doing some syntax checks and breaking our test (because we get a different error).

**Comment by jfrazelle** [comment]
LOL

On Fri, Jan 29, 2016 at 1:42 PM, Brian Goff <notifications@github.com>
wrote:

> Looks like there's a change to url.Parse where it's actually doing some
> syntax checks and breaking our test (because we get a different error).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/19797#issuecomment-176980641>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by tiborvass** [comment]
@duglin we're setting up CI for Go1.5 and Go1.4 :) So your concern should be addressed.

**Comment by duglin** [comment]
@tiborvass excellent! thanks!

**Comment by duglin** [comment]
@tiborvass actually, isn't that backwards?  Shouldn't all of the normal work we do be on what we're going to ship - meaning 1.5?  And then add a CI for 1.6.rc1?  Otherwise if we ship before 1.6 goes all then all of our ad-hoc/dev testing will have been on the wrong version.

**Comment by tiborvass** [comment]
@duglin the idea was to ship it in experimental.

**Comment by tiborvass** [comment]
it's an RC from the Go team, it's much more stable than our master branch :)

**Comment by duglin** [comment]
@tiborvass ship which in experimental? 1.6rc1?

**Comment by tiborvass** [comment]
@duglin yeah

**Comment by tiborvass** [comment]
Since we cannot get consensus on this, I'm closing it. Will add Go 1.6rc1 CI.

**Pull request closed without merging**
