### PR TITLE
Remove fsync in archive.NewTempArchive

### PR DESCRIPTION
**Pull request by burke**
This makes the "Buffering to disk" part of `docker push` 70% faster in my use-case (having already applied #12833, and to be clear, we're talking 11s -> 3s).

AIUI, fsync'ing here serves no valuable purpose: if the drive's operation is interrupted, so it the program's, and this archive has no value other than the immediate and transient one.

Is my assumption incorrect in some way?

### CODE REVIEW

**Comment by LK4D4** [comment]
Seems legit for me.

**Comment by crosbymichael** [comment]
LGTM

**Comment by burke** [comment]
I added another ~identical case where a tempfile used during the V2 registry push was fsync'd. This one makes far, far less difference to my runtime, but is also needlessly wasteful.

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
