### PR TITLE
man: add missing --add-runtime

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks, nice catch! Could you also update the command line reference? https://github.com/docker/docker/blob/master/docs/reference/commandline/dockerd.md

**Comment by runcom** [comment]
@thaJeztah `--add-runtime` is already in there, it's not sorted though

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by thaJeztah** [comment]
awesome! LGTM

**Pull request merged**
