### PR TITLE
[20.10 backport] dockerd-rootless-setuptool.sh: create CLI context "rootless"

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Cherry-pick https://github.com/moby/moby/pull/42084

### CODE REVIEW

**Comment by thaJeztah** [comment]
note: once this is merged and shipped, we'll needs to update the documentation as well, to mention the new context that's created

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
@tonistiigi @tiborvass PTAL? :pray:

**Review by tiborvass — APPROVED** [review]

**Comment by thaJeztah** [comment]
Removed the `docs/revisit` label as https://github.com/docker/docker.github.io/pull/12674 has been opened

**Pull request merged**
