### PR TITLE
Fix some Windows integration tests

### PR DESCRIPTION
**Pull request by icecrime**
Fix tests making the assumption that the daemon can be accessed through `unix:///var/run/docker.sock`.

### CODE REVIEW

**Comment by jfrazelle** [comment]
cool im gunna run jenkins on your branch

**Comment by jfrazelle** [comment]
you need to rebase w my fix

**Comment by jfrazelle** [comment]
https://jenkins.dockerproject.com/job/Windows%20PRs/label=windows/2/console

**Comment by icecrime** [comment]
Oops, had the change locally and forgot to rebase: done!

**Comment by jfrazelle** [comment]
wooohoooo watch it goooo https://jenkins.dockerproject.com/job/Windows%20PRs/label=windows/3/console

**Comment by tianon** [comment]
:+1:

**Comment by ahmetalpbalkan** [comment]
:tada: whoa, that's cool. LGTM. :shipit: 

cc: @sachin-jayant-joshi

**Comment by icecrime** [comment]
I think we can iterate on this PR rather than submit test by test: you can send PRs to [`icecrime/win_integrations_tests`](https://github.com/icecrime/docker/tree/win_integration_tests) if you want to participate.

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by tianon** [comment]
Lots of smaller PRs FTW! :)

**Comment by icecrime** [comment]
Apparently... :-)

**Pull request merged**
