### PR TITLE
test: update registry version to latest

### PR DESCRIPTION
**Pull request by rumpl**
**- What I did**

Updated the registry version used in the integration tests, the one used was 6 years old

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
- duplicate of https://github.com/moby/moby/pull/42889

TL;DR things are failing with a newer version, and we need to look into "where" that problem is; either a bug in registry, or in our code 😞

**Comment by rumpl** [comment]
Green!!!!

**Comment by thaJeztah** [comment]
🎉  could you include the changes from https://github.com/moby/moby/pull/42889 to install the registry from the binary (official image)? would be great if we don't have to do the building and just copy.

**Comment by rumpl** [comment]
Let’s do that in a followup? Since this one is green I want to merge it before it changes its mind.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
