### PR TITLE
Move attach command to cobra

### PR DESCRIPTION
**Pull request by WeiZhang555**
part of https://github.com/docker/docker/issues/23211

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Failing CI looks genuine;

```
16:38:49 ----------------------------------------------------------------------
16:38:49 FAIL: docker_cli_run_unix_test.go:146: DockerSuite.TestRunAttachDetachFromFlag
16:38:49 
16:38:49 docker_cli_run_unix_test.go:178:
16:38:49     c.Fatalf("expected 'hello', got %q", out)
16:38:49 ... Error: expected 'hello', got "Invalid escape keys ('ctrl-a,a') provided\r\n"
16:38:49 
16:38:50 
16:38:50 ----------------------------------------------------------------------
16:38:50 FAIL: docker_cli_run_unix_test.go:207: DockerSuite.TestRunAttachDetachFromInvalidFlag
16:38:50 
16:38:50 docker_cli_run_unix_test.go:235:
16:38:50     c.Assert(strings.TrimSpace(out), checker.Equals, errStr)
16:38:50 ... obtained string = "Invalid escape keys ('ctrl-A,a') provided"
16:38:50 ... expected string = "Invalid escape keys (ctrl-A,a) provided"
16:38:50 
16:38:51 
16:38:51 ----------------------------------------------------------------------
16:38:51 FAIL: docker_cli_run_unix_test.go:322: DockerSuite.TestRunAttachDetachKeysOverrideConfig
16:38:51 
16:38:51 docker_cli_run_unix_test.go:376:
16:38:51     c.Fatalf("expected 'hello', got %q", out)
16:38:51 ... Error: expected 'hello', got "Invalid escape keys ('ctrl-a,a') provided\r\n"
16:38:51 
16:38:51 
16:38:51 ----------------------------------------------------------------------
16:38:51 PASS: docker_cli_run_test.go:4287: DockerSuite.TestRunAttachFailedNoLeak	0.729s
16:38:52 
16:38:52 ----------------------------------------------------------------------
16:38:52 FAIL: docker_cli_run_unix_test.go:404: DockerSuite.TestRunAttachInvalidDetachKeySequencePreserved
16:38:52 
16:38:52 docker_cli_run_unix_test.go:449:
16:38:52     c.Fatalf("expected 'aba', got %q", out)
16:38:52 ... Error: expected 'aba', got "Invalid escape keys ('a,b,c') provided\r\n"
16:38:52 
16:38:53 
```

**Comment by vdemeester** [comment]
ah yes @WeiZhang555 you need to update the integration tests to remove the `'` :angel:

**Comment by WeiZhang555** [comment]
@vdemeester  You're right, fixed.

**Comment by thaJeztah** [comment]
ow, looks like this needs a rebase now :cry:

**Comment by WeiZhang555** [comment]
@thaJeztah Rebased

**Comment by thaJeztah** [comment]
LGTM

ping @vdemeester @dnephin PTAL

**Comment by dnephin** [comment]
LGTM

**Pull request merged**
