### PR TITLE
make the error message in TestRunSeccompDefaultProfile more precise

### PR DESCRIPTION
**Pull request by mountkin**
**\- What I did**
Add prefixes to the error message of `TestRunSeccompDefaultProfile` to make it much easier to track.

Currently if the test fails, the error message is something like 

```
10:14:07 
10:14:07 ----------------------------------------------------------------------
10:14:07 FAIL: docker_cli_run_unix_test.go:996: DockerSuite.TestRunSeccompDefaultProfile
10:14:07 
10:14:07 docker_cli_run_unix_test.go:1094:
10:14:07     c.Assert(err, checker.IsNil)
10:14:07 ... value *errors.errorString = &errors.errorString{s:"expected No such file or directory, got: /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: rpc error: code = 2 desc = \"containerd: container did not start before the specified timeout\".\n"} ("expected No such file or directory, got: /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: rpc error: code = 2 desc = \"containerd: container did not start before the specified timeout\".\n")
10:14:07 
10:14:07 
10:14:07 ----------------------------------------------------------------------
```

See https://jenkins.dockerproject.org/job/Docker-PRs/27858/console

It's quite hard to tell where the error was raised.

**\- How I did it**
Type with my hands.
**\- How to verify it**
See the error message when the test fails again.(Hoping never :innocent: )
**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Shijiang Wei mountkin@gmail.com

### CODE REVIEW

**Comment by justincormack** [comment]
Hi, yes that makes sense to me (The different hello messages were meant to help but are less clear). There is an intermittent issue with these tests which I am looking into, I can replicate it but it does differ between runs, hope to fix this soon.

**Comment by justincormack** [comment]
I have created a PR to split these tests, as that seems to fix the intermittent issues, https://github.com/docker/docker/pull/23073 so if this gets merged this PR will need to be updated.

**Comment by justincormack** [comment]
@mountkin It doesn't conflict but the numbers do need changing now, best to rebase and adjust.

**Comment by mountkin** [comment]
@justincormack rebased

**Comment by justincormack** [comment]
@mountkin thanks! LGTM, thanks.

**Comment by vdemeester** [comment]
LGtM 🐺

**Comment by thaJeztah** [comment]
nice one, @mountkin, thanks!

**Pull request merged**
