### PR TITLE
pkg/ioutils: TempDir: move to pkg/longpath

### PR DESCRIPTION
**Pull request by thaJeztah**
This utility wasn't very related to all other utilities in pkg/ioutils.
Moving it to longpath to also make it more clear what it does.

It looks like there's only a single (public) external consumer of this
utility, and only used in a test, and it's not 100% clear if it was
intentional to use our package, of if it was a case of "I actually meant
`io/ioutil.MkdirTemp`" (https://github.com/elastic/beats/pull/16306 / https://github.com/elastic/beats/blob/26f5d5c0d4ce559b1600dcfdbea0316006ace551/libbeat/autodiscover/template/config_test.go#L335) so we _could_ consider skipping the alias.

While moving the package, I also renamed `TempDir` to `MkdirTemp`, which
is the signature it matches in "os" from stdlib.

### CODE REVIEW

**Comment by thaJeztah** [comment]
One failure; could be related to the first commit (which switched to use `t.TempDir()`); moved that out and changed to use regular `os.MkdirTemp()`

```
=== FAIL: amd64.integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate (7.77s)
    testing.go:1097: TempDir RemoveAll cleanup: unlinkat /tmp/TestDockerAPISuiteTestContainersAPICreateMountsCreate4153205265/002: device or resource busy
    --- FAIL: TestDockerAPISuite/TestContainersAPICreateMountsCreate (7.77s)
```

**Comment by corhere** [comment]
Did you intend to squash the last two commits together? They have the same description

**Review by tianon — APPROVED** [review]
Changes LGTM (but the commits @corhere pointed out do look funny :smile:)

**Comment by thaJeztah** [comment]
> Did you intend to squash the last two commits together? They have the same description

Oh! Hm.. I guess I was planning to do so yes; looks like I may initially had the rename of the function separately, but then made up my mind that including it in the move itself would reduce code churn a bit.

Let me squash them, and update the commit message to mention the rename. 👍

**Comment by thaJeztah** [comment]
Rebased, and squashed the last two commits 👍

**Review by corhere — APPROVED** [review]

**Pull request merged**
