### PR TITLE
Specify ENV variables are also used for CMD.

### PR DESCRIPTION
**Pull request by jankoprowski**

### CODE REVIEW

**Comment by crosbymichael** [comment]
@jankoprowski Do you still want to make the change to `builder.md`?  If not I can do it now if you don't have the time.

**Comment by jankoprowski** [comment]
Apologize for delay. I will not find time to contribute. Sorry. Please make appropriate change in rest of the documentation by your own. Thanks.

**Comment by crosbymichael** [comment]
@jankoprowski no problem,  Thanks for responding.

**Comment by crosbymichael** [comment]
Opened the new PR retaining your commit with my edits.  Thanks again!

**Pull request closed without merging**
