### PR TITLE
migrate to new github.com/distribution/reference module

### LINKED ISSUE #18731: Reference package should not be forked
#18586 basically forked the `distribution/reference` package. We need to fix this up so this issue is tracking the movement. https://github.com/docker/distribution/pull/1277 has been submitted to upstream some changes from that PR but we'll need to undo the duplicate type definitions (reference.Named, etc.).

### PR DESCRIPTION
**Pull request by thaJeztah**
- related https://github.com/distribution/distribution/pull/4031
- supersedes and closes https://github.com/moby/moby/pull/43278
- closes https://github.com/moby/moby/issues/18731

The "reference" package was moved to a separate module, which was extracted from https://github.com/distribution/distribution/commit/b9b19409cf458dcb9e1253ff44ba75bd0620faa6

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
This might explode, so opening as draft. There's also still various other dependencies using this (including https://github.com/docker/distribution) so we should probably wait with this until we move to `github.com/distribution/distibution/v3`)

**Comment by thaJeztah** [comment]
Moving this one out of draft

@rumpl @crazy-max PTAL

**Review by rumpl — APPROVED** [review]
`Files changed 104` scared me at first but this on is an easy review :)

**Comment by thaJeztah** [comment]
Yeah, it _might_ conflict with some other PRs, but should be easy to resolve.

**Comment by thaJeztah** [comment]
- I'll bring this one in, and update my BuildKit PR (https://github.com/moby/buildkit/pull/4188) with this version of docker/docker 👍

**Pull request merged**
