### PR TITLE
contrib: remove download-frozen-image-v1 script

### PR DESCRIPTION
**Pull request by thaJeztah**
I don't think we still had a use for this script, and if someone needs this, it'll still be accessible in older tags/releases.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tianon @cpuguy83 ptal

**Review by tianon — APPROVED** [review]
Sad to see it go (it was so much simpler 😭), but fully understandable and agree.

(Perhaps we should also drop `-v2` from the other script filename so folks don't get confused about it being a script version number, but maybe dropping `-v1` completely will help. 😅)

**Comment by thaJeztah** [comment]
Yes, it's so much simpler than the v2 one! We could keep it of course, as the script itself doesn't require maintenance (I hit it a couple of times searching for references to v1 codepaths 😂), but it would be mostly for nostalgia.

Don't worry though, it will be in Git's history _forever_ ❤️ ❤️ ❤️ 

> Perhaps we should also drop -v2 from the other script filename so folks don't get confused about it being a script version number

I considered that, but was a bit worried that it might break too many users possibly relying on the name. And didn't want to add a symlink, as I recall we had some bad experiences with those in the past 😅 (might've been on windows only though)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
