### PR TITLE
(carry 18273) update description for restart policies

### PR DESCRIPTION
**Pull request by thaJeztah**
Carry of #18274, updated with suggestions by @moxiegirl 

Thanks @afeld for the original PR; I kept your commit in here :+1:

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @moxiegirl for review/merge

**Comment by moxiegirl** [comment]
@thaJeztah Needs a squash but otherwise LGTM.

**Comment by thaJeztah** [comment]
@moxiegirl I left the original commit in here for the carry, or is that not needed?

**Comment by thaJeztah** [comment]
all squashed

LGTM

**Comment by moxiegirl** [comment]
I usually leave the original comment in the commit message of the squash.  That way I still only have one commit.

**Comment by thaJeztah** [comment]
yes that's roughly what I did now, thanks :+1:

**Pull request merged**
