### PR TITLE
Update runc to 54296cf40ad8143b62dbcaa1d90e520a2136ddfe

### LINKED ISSUE #28109: Can not run any docker container (fresh install after reboot)
I have installed docker using script provided at https://get.docker.com/. I was able to test docker, but after a while I have to reboot system. After that I could not start any container (even after complete removal and reinstall). I've got the same error each time, and I was unable to find any solution:

`docker run -it ubuntu:16.04 /bin/sh`

```bash
Handler for POST /v1.24/containers
/38a049b5e8da8a720250856ce0e09a4c5a86cf8f1679da05aa79b787869df309/start 
returned error: invalid header field value "oci runtime error: container_linux.go:247: 
starting container process caused \"process_linux.go:359: container init caused 
\\\"rootfs_linux.go:53: mounting \\\\\\\"cgroup\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper
/mnt/8c26d2f3ae0b4d69b4375705d3c5b03386e64c9cec69dd012e972f2055acf820/rootfs\\\\\\\" 
at \\\\\\\"/sys/fs/cgroup\\\\\\\" caused \\\\\\\"no subsystem for mount\\\\\\\"\\\"\"\n" 
```
Linux 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
Docker version 1.12.3, build 6b644ec

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

--

https://github.com/opencontainers/runc/pull/1266 was cherry picked.

Closes #28109

### CODE REVIEW

**Comment by vieux** [comment]
LGTM ping @tonistiigi

**Review by tonistiigi — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Will also be included in 17.03.1 through https://github.com/docker/docker/issues/31666

**Pull request merged**
