### PR TITLE
integration: fix some linting issues, and don't fail build on artifact uploads 

### PR DESCRIPTION
**Pull request by thaJeztah**
Splitting these off from https://github.com/moby/moby/pull/39724, as they're not directly related to those changes.

- fix some linting issues reported by shellcheck
- Jenkinsfile: use wildcards for artefacts, and don't fail on empty bundles
- Jenkinsfile: don't mark build failed when failing to create bundles

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tiborvass @seemethere @andrewhsu PTAL

**Review by kolyshkin — APPROVED** [review]
Seems we have a repetitive code in N places ... would be awesome to somehow dedup it. I read a bit of jenkinsfile writing sorcery; alas, it appears to be impossible to do so when you only have a single file.

LGTM

**Comment by thaJeztah** [comment]
@kolyshkin yes; planning to do that once the state of the Jenkinsfile is a bit more stable; I had a pull request that did just that; https://github.com/moby/moby/pull/39708 (but want to rework it a bit to take parameters, so that we can use a similar approach for some other steps as well)

**Comment by thaJeztah** [comment]
I'm gonna bring this one in, so that I can rebase https://github.com/moby/moby/pull/39724, and get rid of these commits

**Pull request merged**
