### PR TITLE
Windows: fix rounding error in container resources

### PR DESCRIPTION
**Pull request by darstahl**
Fixes an overflow error causing issues with CPU percent and Memory limits.

/cc @jhowardmsft @jstarks 

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM.  Ugh, my bad

**Comment by tonistiigi** [comment]
LGTM. Does it really make sense to use uint16/uint8 in spec?

**Comment by jhowardmsft** [comment]
@tonistiigi That was the feedback when submitting to opencontainers to change to 8/16

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
