### PR TITLE
explain since format and give examples

### PR DESCRIPTION
**Pull request by tronicum**
relates to #29449
Please provide the following information:

**- What I did**
change command line info

**- How I did it**
used the power of vim

**- How to verify it**
waited for the CI to complete

**- Description for the changelog**
doc for cli docker logs --since

Write a short (one line) summary that describes the changes in this
pull request for inclusion in the changelog:

doc for cli docker logs --since

**- A picture of a cute animal (not mandatory but encouraged)**
imagine a santa clause in front if a christmas tree

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Please update this file as well? https://github.com/docker/docker/blob/master/docs/reference/commandline/logs.md

**Comment by tronicum** [comment]
there you go. signed (and squashed ;)

**Comment by tronicum** [comment]
@AkihiroSuda could you have a look please? i guess the windows test ist not failing because of my patch...

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
