### PR TITLE
Bump v1.7.0

### PR DESCRIPTION
**Pull request by jessfraz**
Scheduled to be released Tuesday, June 16th.

RC1 will be pushed to test.docker.com momentarily along with rpms.

Please help with testing as this will be the official RC.

It's a big one you guys.

### CODE REVIEW

**Comment by jfrazelle** [comment]
We have just pushed 1.7.0-rc1 to test.docker.com you can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc1
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.7.0-rc1
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.7.0-rc1
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc1.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.7.0-rc1.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.7.0-rc1.exe

Please test and make sure all links are working. 

cc @burke @bjaglin @proppy @vishh @ibuildthecloud who have been awesome at testing RCs in the past

This diff is huge so we need all the help we can get :D 

ping @docker/core-maintainers (haters gunna hate, hate, hate, hate shameless massive ping)

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.0-rc1/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.rc1.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc1/centos-6/SRPMS/docker-engine-1.7.0-0.1.rc1.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.0-rc1/centos-7/RPMS/x86_64/docker-engine-1.7.0-0.1.rc1.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc1/centos-7/SRPMS/docker-engine-1.7.0-0.1.rc1.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.0-rc1/fedora-20/RPMS/x86_64/docker-engine-1.7.0-0.1.rc1.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc1/fedora-20/SRPMS/docker-engine-1.7.0-0.1.rc1.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.0-rc1/fedora-21/RPMS/x86_64/docker-engine-1.7.0-0.1.rc1.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc1/fedora-21/SRPMS/docker-engine-1.7.0-0.1.rc1.fc21.src.rpm

**Comment by thaJeztah** [comment]
Regression in 1.7; https://github.com/docker/docker/pull/13535

**Comment by burke** [comment]
Looking good for us so far.

Not a bug, but a probably-intentional behaviour change I observed: On overlay, `${DOCKER_ROOT}/overlay/<cid>/merged` has become `${DOCKER_ROOT}/overlay/<cid>/root` for containers.

It would save us some grief in running a custom build if https://github.com/docker/docker/pull/13564 made it into 1.7.0.

**Comment by jfrazelle** [comment]
yup I've cherry-picked that commit so that will be in the next RC,
thanks @burke :)

**Comment by burke** [comment]
Excellent, thanks @jfrazelle!

**Comment by ewindisch** [comment]
@jfrazelle Just a reminder we need to make sure we get the patch from @tonistiigi cherry-picked once it's submitted. TY!

**Comment by jfrazelle** [comment]
We have just pushed 1.7.0-rc2 to test.docker.com you can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc2
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.7.0-rc2
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.7.0-rc2
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc2.tgz
**Windows 64bit client binary:** https://test.docker.com/builds/Windows/x86_64/docker-1.7.0-rc2.exe
**Windows 32bit client binary:** https://test.docker.com/builds/Windows/i386/docker-1.7.0-rc2.exe

**Comment by visualphoenix** [comment]
@jfrazelle any chance you will be creating rpms like you did for rc1?

**Comment by jfrazelle** [comment]
working on it, they take a bit longer

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.0-rc2/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.2.rc2.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc2/centos-6/SRPMS/docker-engine-1.7.0-0.2.rc2.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.0-rc2/centos-7/RPMS/x86_64/docker-engine-1.7.0-0.2.rc2.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc2/centos-7/SRPMS/docker-engine-1.7.0-0.2.rc2.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.0-rc2/fedora-20/RPMS/x86_64/docker-engine-1.7.0-0.2.rc2.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc2/fedora-20/SRPMS/docker-engine-1.7.0-0.2.rc2.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.0-rc2/fedora-21/RPMS/x86_64/docker-engine-1.7.0-0.2.rc2.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc2/fedora-21/SRPMS/docker-engine-1.7.0-0.2.rc2.fc21.src.rpm

**Comment by SvenDowideit** [comment]
Can you please add #13760 to this PR too? (so the doc changes are not lost)

**Comment by jfrazelle** [comment]
We have just pushed 1.7.0-rc3 to test.docker.com you can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc3
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.7.0-rc3
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.7.0-rc3
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc3.tgz
**Windows 64bit client binary:** https://test.docker.com/builds/Windows/x86_64/docker-1.7.0-rc3.exe
**Windows 32bit client binary:** https://test.docker.com/builds/Windows/i386/docker-1.7.0-rc3.exe

**Comment by tianon** [comment]
https://github.com/tianon/boot2docker/releases/tag/v1.7.0-rc3 :heart:

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.0-rc3/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.3.rc3.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc3/centos-6/SRPMS/docker-engine-1.7.0-0.3.rc3.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.0-rc3/centos-7/RPMS/x86_64/docker-engine-1.7.0-0.3.rc3.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc3/centos-7/SRPMS/docker-engine-1.7.0-0.3.rc3.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.0-rc3/fedora-20/RPMS/x86_64/docker-engine-1.7.0-0.3.rc3.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc3/fedora-20/SRPMS/docker-engine-1.7.0-0.3.rc3.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.0-rc3/fedora-21/RPMS/x86_64/docker-engine-1.7.0-0.3.rc3.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc3/fedora-21/SRPMS/docker-engine-1.7.0-0.3.rc3.fc21.src.rpm

**Fedora 22**
https://test.docker.com/rpm/1.7.0-rc3/fedora-22/RPMS/x86_64/docker-engine-1.7.0-0.3.rc3.fc22.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc3/fedora-22/SRPMS/docker-engine-1.7.0-0.3.rc3.fc22.src.rpm

**Comment by ibnesayeed** [comment]
Why are we in hurry? [Version 1.7.0 is due by May 16, 2016](https://github.com/docker/docker/milestones) which almost a year from now. :)

**Comment by icecrime** [comment]
@ibnesayeed This is a 1 year freeze period for DockerCon 2016 ;-) Nice catch, fixed (and by the way it moved to Thursday 18th I believe, cc @vieux).

**Comment by ibnesayeed** [comment]
@icecrime it was poking in my eyes for quite some time and I was looking for a good place to report it, but I was not convinced to increment the issue counter for a non-code related issue.

**Comment by jfrazelle** [comment]
We have just pushed 1.7.0-rc4 to test.docker.com you can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc4
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.7.0-rc4
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.7.0-rc4
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc4.tgz
**Windows 64bit client binary:** https://test.docker.com/builds/Windows/x86_64/docker-1.7.0-rc4.exe
**Windows 32bit client binary:** https://test.docker.com/builds/Windows/i386/docker-1.7.0-rc4.exe

**Comment by mavenugo** [comment]
Is the rc4 built purely to fix the MTU problem ?
Don’t say “yes" and break my heart :-)

Crosby is awesome and can’t thank him enough for taking it on his own.

-Madhu

**Comment by jfrazelle** [comment]
@mavenugo there were 2 other things ;)

**Comment by mavenugo** [comment]
Thanks @jfrazelle @crosbymichael

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.0-rc4/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.4.rc4.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc4/centos-6/SRPMS/docker-engine-1.7.0-0.4.rc4.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.0-rc4/centos-7/RPMS/x86_64/docker-engine-1.7.0-0.4.rc4.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc4/centos-7/SRPMS/docker-engine-1.7.0-0.4.rc4.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.0-rc4/fedora-20/RPMS/x86_64/docker-engine-1.7.0-0.4.rc4.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc4/fedora-20/SRPMS/docker-engine-1.7.0-0.4.rc4.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.0-rc4/fedora-21/RPMS/x86_64/docker-engine-1.7.0-0.4.rc4.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc4/fedora-21/SRPMS/docker-engine-1.7.0-0.4.rc4.fc21.src.rpm

**Fedora 22**
https://test.docker.com/rpm/1.7.0-rc4/fedora-22/RPMS/x86_64/docker-engine-1.7.0-0.4.rc4.fc22.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc4/fedora-22/SRPMS/docker-engine-1.7.0-0.4.rc4.fc22.src.rpm

**Comment by tianon** [comment]
https://github.com/tianon/boot2docker/releases/tag/v1.7.0-rc4

**Comment by jfrazelle** [comment]
We have just pushed 1.7.0-rc5 to test.docker.com you can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc5
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.7.0-rc5
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.7.0-rc5
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.7.0-rc5.tgz
**Windows 64bit client binary:** https://test.docker.com/builds/Windows/x86_64/docker-1.7.0-rc5.exe
**Windows 32bit client binary:** https://test.docker.com/builds/Windows/i386/docker-1.7.0-rc5.exe

**Comment by jfrazelle** [comment]
btw winndows build will fail on daemon compiling, so don't worry...

**Comment by tianon** [comment]
https://github.com/tianon/boot2docker/releases/tag/v1.7.0-rc5

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.0-rc5/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.5.rc5.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc5/centos-6/SRPMS/docker-engine-1.7.0-0.5.rc5.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.0-rc5/centos-7/RPMS/x86_64/docker-engine-1.7.0-0.5.rc5.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc5/centos-7/SRPMS/docker-engine-1.7.0-0.5.rc5.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.0-rc5/fedora-20/RPMS/x86_64/docker-engine-1.7.0-0.5.rc5.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc5/fedora-20/SRPMS/docker-engine-1.7.0-0.5.rc5.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.0-rc5/fedora-21/RPMS/x86_64/docker-engine-1.7.0-0.5.rc5.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc5/fedora-21/SRPMS/docker-engine-1.7.0-0.5.rc5.fc21.src.rpm

**Fedora 22**
https://test.docker.com/rpm/1.7.0-rc5/fedora-22/RPMS/x86_64/docker-engine-1.7.0-0.5.rc5.fc22.x86_64.rpm
https://test.docker.com/rpm/1.7.0-rc5/fedora-22/SRPMS/docker-engine-1.7.0-0.5.rc5.fc22.src.rpm

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @crosbymichael @calavera @icecrime @LK4D4

**Comment by icecrime** [comment]
LGTM :tada: :cookie:

**Comment by thaJeztah** [comment]
Yeah!! congrats and great work again!

**Comment by runcom** [comment]
:tada: gratz! :)

**Comment by thaJeztah** [comment]
has @tianon been notified for Boot2Docker?

**Comment by jfrazelle** [comment]
I am sure he is aware since he is watching this PR

**Comment by visualphoenix** [comment]
Will official RPMs go on this ticket or will they be hosted elsewhere?

On Thursday, June 18, 2015, Jessie Frazelle <notifications@github.com>
wrote:

> I am sure he is aware since he is watching this PR
>
> On Thu, Jun 18, 2015 at 11:06 AM, Sebastiaan van Stijn <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > has @tianon <https://github.com/tianon> been notified for Boot2Docker?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/docker/docker/pull/13528#issuecomment-113241826>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/13528#issuecomment-113243499>.
>


-- 
Raymond "VisualPhoenix" Barbiero

**Comment by thaJeztah** [comment]
@visualphoenix see the docs (not yet published); https://github.com/docker/docker/blob/v1.7.0/docs/installation/centos.md
https://github.com/docker/docker/blob/v1.7.0/docs/installation/fedora.md
https://github.com/docker/docker/blob/v1.7.0/docs/installation/rhel.md

**Comment by visualphoenix** [comment]
boo. just tested 1.7.0 on a freshly spun RHEL 6.6 host and daemon wont start. looks like a libnetwork bug.

**Comment by vishh** [comment]
congrats!!!

On Thu, Jun 18, 2015 at 12:27 PM, Raymond Barbiero <notifications@github.com

**Pull request merged**
