### PR TITLE
Add context.RequestID to event stream

### PR DESCRIPTION
**Pull request by duglin**
This PR adds a "request ID" to each event generated, the 'docker events'
stream now looks like this:

```
2015-09-10T15:02:50.000000000-07:00 [reqid: c01e3534ddca] de7c5d4ca927253cf4e978ee9c4545161e406e9b5a14617efb52c658b249174a: (from ubuntu) create
```

Note the `[reqID: c01e3534ddca]` part, that's new.

Each HTTP request will generate its own unique ID. So, if you do a
`docker build` you'll see a series of events all with the same reqID.
This allow for log processing tools to determine which events are all related
to the same http request.

I didn't propigate the context to all possible funcs in the daemon,
I decided to just do the ones that needed it in order to get the reqID
into the events and then exported funcs at the same top-level in the daemon so we have
consistency. 

I think the biggest question is the format of the event - so please let me know what you think.

In a subsequent PR I think we may need to modify the event even more since right now it seems too specific to images - e.g. it assumes there an image ID in each event, which may not be true going forward.

ping @icecrime @calavera @crosbymichael

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
ok I think this one is ready for design review. The biggest question is the format of the "request id" in the event.  

ping @icecrime @crosbymichael

**Comment by duglin** [comment]
Any chance of getting some eyes on this one?  Due to the amount of code changes, this one ends up in near daily (or more) rebases.

**Comment by calavera** [comment]
I guess there is no other way of propagating that request id to the events :pensive:

I'm going to move to the code review.

**Comment by duglin** [comment]
yup I really miss thread-local data, but that's not something we can do in go.

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
needs rebase sorry

**Comment by duglin** [comment]
daily rebase done  :-)

**Comment by duglin** [comment]
again!  :-)

**Comment by calavera** [comment]
still LGTM. Merging, quick, quick!

**Comment by tiborvass** [comment]
For reference parts of this were reverted in #16567

**Pull request merged**
