### PR TITLE
[19.03 backport] Testing changes

### PR DESCRIPTION
**Pull request by thaJeztah**
alternative to https://github.com/moby/moby/pull/40413, without the changes from https://github.com/moby/moby/pull/39829 (moving the `internal/test` package to `testutil`), and without the changes from https://github.com/moby/moby/pull/40412 (which were needed to get a clean cherry-pick of the "rename" cherry-pick)

- https://github.com/moby/moby/pull/39602 Add `FromClient` to test env execution
- https://github.com/moby/moby/pull/39904 DaemonCli: Move check into startMetricsServer
- https://github.com/moby/moby/pull/39889 Fix more signal handling issues in tests

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cpuguy83 @kolyshkin this one should also be good to review

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Don't see any Jenkinsfile changes in this, though.

**Comment by thaJeztah** [comment]
oh, yeah 😂 I think I reduced it down and it no longer has any Jenkins changes. Let me rename

**Comment by thaJeztah** [comment]
Argh.. and that triggered CI again 😞

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
