### PR TITLE
Remove apt.dockerproject.org from test

### PR DESCRIPTION
**Pull request by thaJeztah**
to address https://github.com/moby/moby/pull/41269#issuecomment-664605477

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tonistiigi @tiborvass @cpuguy83 PTAL

**Review by tiborvass — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
Many other references to `apt.dockerproject.org` in this repo. Mostly under docs/ but also in hack/

**Comment by thaJeztah** [comment]
I see some tests using `org.dockerproject` but that's because those are reserved. There's a couple of references to dockerproject.org related to jenkins and an old mailinglist; I'll have a look at those separately

**Comment by thaJeztah** [comment]
Rootless tests failed after timing out; failure is unrelated;

```
=== RUN   TestCgroupNamespacesRunHostMode
--- FAIL: TestCgroupNamespacesRunHostMode (60.00s)
    run_cgroupns_linux_test.go:34: [d4cc358a78c40] failed to start daemon with arguments [-u unprivilegeduser -E XDG_RUNTIME_DIR=/go/src/github.com/docker/docker/bundles/test-integration/TestCgroupNamespacesRunHostMode/d4cc358a78c40/xdgrun -E HOME=/home/unprivilegeduser -E PATH=/go/src/github.com/docker/docker/bundles/test-integration/../dynbinary-daemon:/go/src/github.com/docker/docker/bundles/test-integration/../binary-daemon:/usr/local/cli:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- dockerd-rootless.sh --data-root /go/src/github.com/docker/docker/bundles/test-integration/TestCgroupNamespacesRunHostMode/d4cc358a78c40/root --exec-root /tmp/dxr/d4cc358a78c40 --pidfile /go/src/github.com/docker/docker/bundles/test-integration/TestCgroupNamespacesRunHostMode/d4cc358a78c40/docker.pid --userland-proxy=true --containerd-namespace d4cc358a78c40 --containerd-plugins-namespace d4cc358a78c40p --default-cgroupns-mode private --host unix:///tmp/docker-integration/d4cc358a78c40.sock --debug --storage-driver overlay2] : [d4cc358a78c40] daemon exited and never started: context deadline exceeded
```

**Pull request merged**
