### PR TITLE
Oops, break should have been continue

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Title says it all. Mea culpa.  @thaJeztah @mlaventure @tonistiigi

### CODE REVIEW

**Comment by mlaventure** [comment]
We have no test being affected by either of them being MIA?

**Comment by tonistiigi** [comment]
LGTM

**Comment by jhowardmsft** [comment]
@mlaventure Correct :sad:. I wish it were easy to write one that would run under CI, but on my list to think about.

**Comment by mlaventure** [comment]
Alright, meanwhile: LGTM.

**Comment by vdemeester** [comment]
:sweat:

**Pull request merged**
