### PR TITLE
Porting container api tests from integration to integration-cli

### PR DESCRIPTION
**Pull request by brahmaroutu**

### CODE REVIEW

**Comment by LK4D4** [comment]
@runcom removed integration tests in #12771

**Comment by runcom** [comment]
yup already ported the ones you ported here :(

**Comment by brahmaroutu** [comment]
Hmm, runcom, sorry that was a huge PR I could not see these tests. Does this mean that you are addressing all of the remaining tests under 12255?

**Comment by icecrime** [comment]
Sorry @brahmaroutu, closing this :-/

**Pull request closed without merging**
