### PR TITLE
vendor: libcontainer: update libcontainer

### PR DESCRIPTION
**Pull request by cyphar**
Update the vendor'd version of libcontainer to include path sanitisation
fixes and some other cgroup fixes. In addition, a fix for gccgo 5.3 was
included.

This is blocked on opencontainers/runc#451 being merged, after which
I will correct the `hack/vendor.sh` referenced commit.

Signed-off-by: Aleksa Sarai asarai@suse.com

/cc @security-team @diogomonica

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
##### do not merge yet! depends on https://github.com/opencontainers/runc/pull/451

**Comment by cyphar** [comment]
To avoid someone accidentally merging this, I'll close this until opencontainers/runc#451 is merged.

**Comment by cyphar** [comment]
#19250 is this PR. I can't reopen this one because I pushed to the branch while the PR was closed (which seems like a bug in GitHub).

**Pull request closed without merging**
