### PR TITLE
Support v2 plugins in swarm mode

### PR DESCRIPTION
**Pull request by aaronlehmann**
This PR vendors a swarmkit PR that adds awareness of v2 plugins to the scheduler. Services that depend on a particular volume or network plugin will only be dispatched to nodes which have that plugin installed.

It updates the agent's executor to publish a list of v2 plugins to the manager.

It also fixes a problem in volume creation when the volume driver is a plugin. Trying to create a volume with the same name and parameters as one that already exists generally returns no error, but if a plugin name without a tag is specified, this always resulted in a conflict (`plugin` vs `plugin:latest`). The fix is to resolve the volume driver and compare its canonical name instead of the name passed in by the caller.

ping @anusha-ragunathan @vieux @tonistiigi @aluzzardi @nishanttotla @cpuguy83

### CODE REVIEW

**Comment by vieux** [comment]
@aaronlehmann test failure seems genuine. also does this depends on https://github.com/docker/swarmkit/pull/1808 ?

**Comment by aaronlehmann** [comment]
Yes, this depends on docker/swarmkit#1808. I updated this PR to formally vendor SwarmKit now that docker/swarmkit#1808 has been merged. I was originally going to do it in a separate PR, but it's important that the changes here get merged at the same time.

This also seems to fix the IPAM test failure. I think the branch being vendored here before was outdated.

The volume create test failure is because the test uses a volume driver that doesn't exist, and now it will get an error about that, instead of getting the name conflict it's looking for. Any ideas on how to solve that? Are there two volume drivers that can be used by the test to trigger the condition?

**Comment by aaronlehmann** [comment]
Fixed the other test. PTAL. This should be good to go.

**Comment by aluzzardi** [comment]
LGTM, minus the Windows failure

**Comment by aaronlehmann** [comment]
The Windows failure should be fixed now. I moved `TestVolumeCLICreateOptionConflict` to `DockerExternalVolumeSuite` because it now uses some Linux-specific code.

After this PR is merged, I plan to open a similar PR against the 1.13 branch. It will revendor swarmkit to the latest version of swarmkit's 1.13 branch (which includes the changes vendored here), and cherry-pick the two engine commits from this PR.

**Comment by aaronlehmann** [comment]
Opened a 1.13 version of this PR here: https://github.com/docker/docker/pull/29433. Removing the `process/cherry-pick` label and 1.13 milestone from this PR, since 1.13 will get this from the backport PR.

**Comment by aaronlehmann** [comment]
This should be merged ASAP because the 1.13 backport in #29433 was already merged.

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Pull request merged**
