### PR TITLE
Modularize dm.use_deferred_removal and dm.use_deferred_deletion logic.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
@rhvgoyal This is the PR for cleanup (modularizing) the devicemapper deferred removal and deferred deletion options.
Please do the review.

ping @thaJeztah

**Comment by runcom** [comment]
this isn't changing any logic right? if so, LGTM

**Comment by thaJeztah** [comment]
If we're going to do this, shouldn't we split "deferred removal" and "deferred deletion"? Also, there's still a dependency between calling this function, and requires running `determineDriverCapabilities()` first, so although I agree it looks a bit cleaner, it doesn't really separate the code

**Comment by shishir-a412ed** [comment]
@thaJeztah
I kept them together, as they are not mutually exclusive options. `dm.use_deferred_deletion` is dependent on `dm.use_deferred_removal`. So currently if you try to start `dockerd` with just `--storage-opt dm.use_deferred_deletion=true` it will not start and complain that `deferred removal` also needs to be there for `deferred deletion` to work. Hence I kept them together. 

It does call `determineDriverCapabilities()` right before this logic is executed.
https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L1634 

@runcom yeah no logic changed, just code cleanup. @rhvgoyal requested for this.

Shishir

**Comment by shishir-a412ed** [comment]
@thaJeztah 
I see what you are saying about `determineDriverCapabilities()`.
Should I move this:
https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L1628-L1636 inside `enableDeferredRemovalDeletion()` function.

Does that solve your problem ?

Shishir

**Comment by thaJeztah** [comment]
@shishir-a412ed no, I think it should be "ok" like it is now, it's just that I'm not really sure we gain much by this move.
Given that code was already like this :innocent: and that this slightly improves readability;

LGTM


Basically, I'm never fond of functions that have to be executed in a specific
order to work, and rely on "global" variables as a "communication channel"

To get what I think is proper separation is to;

- Instead of it reading driver-options, and storing them in "global" variables (inside `NewDeviceSet()`), Pass an "options" type to `initDevmapper()` (e.g. `initDevmapper(doInit, DevMapperOptions)`)
- Have the devicemapper provide information about its capabilities, i.e., instead of `determineDriverCapabilities(version)` let devicemapper provide this information, e.g. `devicemapper.SupportsDeferredRemoval()`

I know this is not the only part where these kind of constructs are used, but IMO
(highly opiniated opinion), a function should produce the same result with the
same set of parameters, so `f(x) = y` should always return the same `y` with the
same `x`. Passing `x` instead of storing it somewhere globally makes it more clear
what parameters are used, and makes it easier to test.

**Comment by thaJeztah** [comment]
restarting WindowsTP5 to have "green"

**Comment by vdemeester** [comment]
LGTM 🐺

**Pull request merged**
