### PR TITLE
Fix some issues in logfile reader and rotation

### PR DESCRIPTION
**Pull request by cpuguy83**
- Check errors.Cause(err) when comparing errors
- Fix bug where oldest log file is not actually removed. This in
particular causes issues when compression is enabled. On rotate it just
overwrites the data in the log file corrupting it.
- Use O_TRUNC to open new gzip files to ensure we don't corrupt log
files as happens without the above fix.

Signed-off-by: Brian Goff <cpuguy83@gmail.com>

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @miaoyq

**Review by anusha-ragunathan — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by miaoyq** [comment]
LGTM

**Pull request merged**
