### PR TITLE
Expand chown value of COPY command #35018

### PR DESCRIPTION
**Pull request by m-hu**
Signed-off-by: Hao Hu <hao.hu.fr@gmail.com>

**- What I did**
Provide a simple implementation for issue #35018

**- How I did it**
Expand the value of chown of COPY command

**- How to verify it**
Create a Dockerfile containing COPY chown=${envvar}, then use either ENV or ARG to set the value of envvar. Please note that the value should be valid for the current image. Then, see if the copy command is correctly executed.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like this is continued in https://github.com/moby/buildkit/pull/926

@tonistiigi was a re-vendor of BuildKit already planned?

**Comment by pptime** [comment]
Looks like a test failure due to network issue between Jenkins and the docker registry

**Comment by thaJeztah** [comment]
oh! I see https://github.com/moby/moby/pull/39132 also includes this change in the vendor code, so looks like this is no longer needed; let me close this one; thanks!!

**Comment by pptime** [comment]
Yeah, thx.

**Review by m-hu — COMMENTED** [review]
at maximum
irrelevant

**Pull request closed without merging**
