### PR TITLE
Redirect powershell completion

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

The version of the PowerShell completion module in the contrib folder is way out of date. Hence removing it and putting a readme.txt redirecting to the repo at https://github.com/samneirinck/posh-docker

@samneirinck

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@thaJeztah @vdemeester Should be a very simple review :smile:

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
ping @justincormack as you were working on including the Linux completion scripts in the packages; wondering if you wanted to do the same for Windows

**Comment by jhowardmsft** [comment]
@justincormack PTAL. Thanks.

**Review by thaJeztah — APPROVED** [review]
let me LGTM

we can discuss if we want to actually include the completion scripts in docker for windows (@justincormack)

**Comment by thaJeztah** [comment]
grmbl, CI didn't run and this broke it;

```
cp: cannot stat 'contrib/completion/powershell/*docker*': No such file or directory
Build step 'Execute shell' marked build as failure
```

**Comment by samneirinck** [comment]
It would be great to have it packaged into Docker for Windows, happy to discuss.

**Pull request merged**
