### PR TITLE
Change in man alias for --rm and --no-cache

### PR DESCRIPTION
**Pull request by j-mracek**
In docker run --rm is alias of --rm=true

In docker build --no-cache is alias --no-cache=true

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hm, actually, the values are the *default* values; also see https://github.com/docker/docker/issues/18300

**Comment by j-mracek** [comment]
docker run --help show:
--rm=false                      Automatically remove the container when it exits

but correct is:
--rm=true                      Automatically remove the container when it exits
or:
--rm                      Automatically remove the container when it exits

**Comment by MHBauer** [comment]
@j-mracek right, but the way the go flag package works (or used to work, anyway) is to show the *default* value on the help. Thus help is saying `--rm` defaults to false when you run the command, and not "to automatically remove the container when it exits, set the `--rm` flag to `false`. The `--help` text is automatically generated from the code, and is fixed by #18082.

This particular issue is how the man pages look. The _fix_ that golang made, was to hid default values that are `false`, `0`, or the empty string `""`. We need to decide whether to make similar changes to all the docs to match the new look.

**Comment by tiborvass** [comment]
@MHBauer interesting, do you have a a link to discussion/code regarding that change in Go?
I vote for updating man pages according to the change in Go. I understand how this could be confusing.

**Comment by j-mracek** [comment]
It is also question, if defaults is worth to mentioned in synopsis. From context I think that my pull-request is not so good, I would vote to remove defaults from synopsis. I can prepare it, if there will be agreement.

**Comment by MHBauer** [comment]
@tiborvass back through issues, for completion, #18082 -> https://github.com/docker/docker/issues/9406#issuecomment-81176423 -> https://go.googlesource.com/go/+/51d66601c45572484ed20f3a2be6f67d648b5f22

The key part is the `isZeroValue` function, which I retrofitted into the modified Docker mflag package.

**Comment by tiborvass** [comment]
@MHBauer thank you very much.

I say we should update all the boolean flags in the docs.

@j-mracek I suggest you either close this PR and open a more general one, or else simply modify the title of this PR and update this PR.

**Comment by thaJeztah** [comment]
Yup, I agree with changing the docs in general; we should have a consistent way of doing the man-pages as well, not sure if there's a convention in man-pages for booleans? Happy to hear suggestions there

/cc @moxiegirl because this will change many parts in the documentation

**Comment by moxiegirl** [comment]
@thaJeztah If this will change many `docs` files, shouldn't they be included here?

**Comment by thaJeztah** [comment]
@moxiegirl sorry, with "this" I meant;

> I say we should update all the boolean flags in the docs.

If we want to do that (can be this PR, or another one), we also should check what the best notation is for the man pages, perhaps you know?

**Comment by moxiegirl** [comment]
@thaJeztah Thanks for the clarification. I like the example proposed here:

https://github.com/docker/docker/pull/18082#issuecomment-158211222

image

Yes, that will require updating all the docs in `docker/docker` there is also impact to the other repos for consistency correct?

**Comment by thaJeztah** [comment]
> there is also impact to the other repos for consistency correct?

Probably, yes; if they want the output of `--help` the same on the commandline, they'll need the patch that @MHBauer did in this repo.

Documentation can be updated separate from that (if we want to), but would be best for consistency

**Comment by moxiegirl** [comment]
@thaJeztah ok...sounds like we need a little project management --- maybe an email out to team or something so all the repos can make the change.  WDYT?

**Comment by thaJeztah** [comment]
@moxiegirl yup, sounds like a plan; I'll write something up for the maintainers list

**Comment by j-mracek** [comment]
Ok, I am going to close pull-request

**Pull request closed without merging**
