### PR TITLE
Generate caps

### PR DESCRIPTION
**Pull request by LK4D4**
Close #13016 
Let's see how jenkins will like that.

### CODE REVIEW

**Comment by LK4D4** [comment]
Ok, it has same problem :) And I have no idea which.

**Comment by LK4D4** [comment]
Okay, I can reproduce this on my host, so, if you run tests on docker without CAP_AUDIT_READ in --privileged it will fail.

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

tests are failing because the inner docker is trying to drop more caps than the outer docker so the daemons need updated ( just for reference )

**Pull request merged**
