### PR TITLE
[23.0 backport] Dockerfile: use TARGETPLATFORM to build Docker

### PR DESCRIPTION
**Pull request by crazy-max**
* backport of https://github.com/moby/moby/pull/44546

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by crazy-max** [comment]
Got a small conflict with first commit in the Dockerfile in https://github.com/moby/moby/blob/b9fe30dad49db41fc8fb41da8fef46f0fb0d42b9/Dockerfile#L515

As discussed with @thaJeztah this is linked to https://github.com/moby/moby/pull/43219 which will not be backported

**Comment by crazy-max** [comment]
Got another conflict linked to https://github.com/moby/moby/commit/a3292263a3cb29c972b41511aeb0a3e36c8468c7

https://github.com/moby/moby/blob/63e861c87eebe6fc2700231dd544eff29e8aad54/Dockerfile#L584-L592

https://github.com/moby/moby/blob/b9fe30dad49db41fc8fb41da8fef46f0fb0d42b9/Dockerfile#L472-L477

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
