### PR TITLE
WIP/Proposal: using bats for testing upgrades

### PR DESCRIPTION
**Pull request by jessfraz**
This is a WIP PR, where I will push progress as it is made for adding bats (bash test framework) tests for testing docker upgrades via `apt-get upgrade` so we can try and avoid the problems we saw in 1.7.0.

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @tianon for opinions

**Comment by icecrime** [comment]
+1000!

Testing things like installing Docker 1.3, start a container with some volume, upgrade to 1.4, 1.5, 1.6, 1.7, and see at every step if everything is still running as expected would be immensely useful. We could have once script per scenario, and maybe try to add more as we introduce breaking changes (such as moving things in `~/.docker/` or `/var/lib/docker/` around.

**Comment by rtrauntvein** [comment]
+1 great idea :)

**Comment by thaJeztah** [comment]
> Testing things like installing Docker 1.3, start a container with some volume, upgrade to 1.4, 1.5, 1.6, 1.7

Testing upgrades when "skipping versions", e.g. upgrade 1.5 to 1.7 might be interesting to test too; I've seen those cases cause some trouble.

:100: for this!

**Comment by tiborvass** [comment]
@jfrazelle I like this EXCEPT that I want it all inside the container and have it install the version before and do upgrade tests. For yum's we can even run a yummy container inside docker for maximalized inception :)

Also would you mind clarifying what `make test-upgrade` consists of?

**Comment by jfrazelle** [comment]
@tiborvass dont worry, I think I had a brain aneurysm when i first opened this, after testing all the new debs/rpms locally in containers, we can do this all with containers ;)

**Comment by thaJeztah** [comment]
I keep reading "Batts" every time I see this PR, LOL

**Comment by abronan** [comment]
@tiborvass @jfrazelle +1 if this is done inside containers not touching to the host environment. We have quite a lot of bats scripts in *swarm* that could probably be reused here.

We thought about testing different versions of docker against a swarm version. So this is super close of what you want to achieve here.

**Comment by cpuguy83** [comment]
+1

**Comment by calavera** [comment]
how can we move this forward?

@jfrazelle can you provide some initial basic tests so we can merge this? I don't think they need to cover everything right now, we can iterate and keep adding more tests.

**Comment by thaJeztah** [comment]
@jfrazelle @calavera I think we should merge, and create a list of tests/scenarios we want (checkbox style); that way contributors can pick tests and work on them; like we did for the Golint stuff https://github.com/docker/docker/issues/14756

**Comment by icecrime** [comment]
Having at least one model of such test would be good (maybe even a simple one).

**Comment by tianon** [comment]
Sounds like a cool idea to me! :+1:

**Comment by thaJeztah** [comment]
> Having at least one model of such test would be good (maybe even a simple one).

Yes!

Just remembered; reeling in @ibuildthecloud here, because I think they have tests in Rancher doing upgrade/downgrade thingies. Perhaps he has thoughts on this subject :+1:

**Comment by tonistiigi** [comment]
One way is to have `bats` running in host, setting up the containers and possibly having the logic that certain `apt-get` tests are only tuned for debian etc. The other would be somewhat similar to the original idea where docker is installed/upgraded in host. Then there could possibly be some other script that copies bats and the test suit to different containers before running it. With the latter we could later reuse the test suite to run in bunch of vm checkpoints as well. Running docker-in-docker would only find a certain set of  issues, not the ones that come from kernel differences or other programs running in the system.

So I guess the question is if we want to have a tests for fine tuned upgrade paths or a set of generic upgrade checks that we want to work against all kinds of systems/kernels.

**Comment by jfrazelle** [comment]
closing will reopen when ready

**Pull request closed without merging**
