### PR TITLE
Optimize .dockerignore when there are exclusions

### LINKED ISSUE #20470: .dockerignore ! pattern results in slow builds on large contexts
I have a huge project. I want to include only files like `package.json` and `requirements.txt` in the build context. To do that, I tried adding a `.dockerignore` that excludes `*` and includes specific files (`!foo/requirements.txt`).

If I try to use `*` in `.dockerignore` and `!` to include specific files, it takes a really long time (if the context directory is large).

```
> du -sh .
1.1G . # this is in a BIG context

> cat empty.dock
FROM ubuntu

> cat .dockerignore
*
!foo/requirements.txt

> docker build -f empty.dock .
# HANGS for a really long time
Sending build context... etc etc
```

Now, if I remove the included file `!foo/bar.txt` from `.dockerignore`, then it's super fast!

```
> cat .dockerignore
*

> docker build -f empty.dock .
Sending build context... etc etc # INSTANT! :D
```

Any idea what's up?

### PR DESCRIPTION
**Pull request by duglin**
Closes #20470

Before this PR we used to scan the entire build context when there were
exclusions in the .dockerignore file (paths that started with !). Now we
only traverse into subdirs when one of the exclusions starts with that dir
path.

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by calavera** [comment]
@duglin is this a replacement of https://github.com/docker/docker/pull/20128 or just a general improvement?

**Comment by duglin** [comment]
@calavera I think #20128 is a different (but related) issue. I still haven't had a chance to review his code. His PR, if adopted, might replace this code I dunno, but until his PR is reviewed I think this improvement is needed.

**Comment by icecrime** [comment]
@duglin A failure on win2lin could be related:

```
10:09:22 FAIL: docker_cli_build_test.go:3420: DockerSuite.TestBuildDockerignoreExceptions
10:09:22 
10:09:22 docker_cli_build_test.go:3472:
10:09:22     c.Fatal(err)
10:09:22 ... Error: failed to build the image: Sending build context to Docker daemon 5.632 kB

10:09:22 Step 1 : FROM busybox
10:09:22  ---> d9551b4026f0
10:09:22 Step 2 : ADD . /bla
10:09:22  ---> 525151bf3a0d
10:09:22 Removing intermediate container bb73d439035b
10:09:22 Step 3 : RUN sh -c "[[ -f /bla/src/x.go ]]"
10:09:22  ---> Running in cd47636aea86
10:09:22  ---> c4744cd1dd6e
10:09:22 Removing intermediate container cd47636aea86
10:09:22 Step 4 : RUN sh -c "[[ -f /bla/Makefile ]]"
10:09:22  ---> Running in 1c650905761e
10:09:22  ---> cc828d2eb450
10:09:22 Removing intermediate container 1c650905761e
10:09:22 Step 5 : RUN sh -c "[[ ! -e /bla/src/_vendor ]]"
10:09:22  ---> Running in 34058da14892
10:09:22  ---> 6cee219e56d5
10:09:22 Removing intermediate container 34058da14892
10:09:22 Step 6 : RUN sh -c "[[ ! -e /bla/.gitignore ]]"
10:09:22  ---> Running in 5a0284b90ae2
10:09:22  ---> b8b5fdd2cd67
10:09:22 Removing intermediate container 5a0284b90ae2
10:09:22 Step 7 : RUN sh -c "[[ ! -e /bla/README.md ]]"
10:09:22  ---> Running in 14819c13dc08
10:09:22  ---> a1d0fe340d67
10:09:22 Removing intermediate container 14819c13dc08
10:09:22 Step 8 : RUN sh -c "[[  -e /bla/dir/dir/foo ]]"
10:09:22  ---> Running in 3ee3f23439de
10:09:22 The command '/bin/sh -c sh -c "[[  -e /bla/dir/dir/foo ]]"' returned a non-zero code: 1
```

**Comment by duglin** [comment]
@icecrime ok, windows issue is fixed!

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐹

**Comment by xaka** [comment]
It is possible that this PR broke nested exclusions (https://github.com/docker/docker/issues/30018) and better be reverted to bring important feature back to life? @vdemeester

**Pull request merged**
