### PR TITLE
Update response content for volume mounts

### PR DESCRIPTION
**Pull request by HackToday**
From docker inspect, it includes "Propagation" field, so
we update the doc to reflect that.

Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
Thanks! Can you also update the API docs? https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md#inspect-a-container

**Comment by HackToday** [comment]
@thaJeztah  seems that doc is old in many fileds except that one,

like 

Name, Driver not include.(check below example)


                "Name": "009fb2dbf89d224a9a99d527d6613f45c9a322daa7bc2c465882d0b23265443f",
                "Source": "/var/lib/docker/volumes/009fb2dbf89d224a9a99d527d6613f45c9a322daa7bc2c465882d0b23265443f/_data",
                "Destination": "/nice",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""


Do you think we need update those ?

**Comment by HackToday** [comment]
If yes, is it OK for just edit them in 1.22 version ? or need also take care of other versions ? For other versions I did not know if 1.21 or when support related fields. 

Could docker support multiple versions ?  for example, I can send API to ask docker to return the version of API I wanted (I ask 1.21, 1.20 etc)

**Comment by thaJeztah** [comment]
> If yes, is it OK for just edit them in 1.22 version ? or need also take care of other versions ? For other versions I did not know if 1.21 or when support related fields.

Yes that's fine

> Could docker support multiple versions ? for example, I can send API to ask docker to return the version of API I wanted (I ask 1.21, 1.20 etc)

Yes, it's possible; API is versioned, and you can request a specific version by using the right URL e.g. `/v1.21/.....`

If your question is "can I select which API version to use for the command-line"? You will be able to do that in docker 1.10; https://github.com/docker/docker/pull/15964

**Comment by HackToday** [comment]
@thaJeztah  PTAL.  Thanks

**Comment by HackToday** [comment]
Not sure if you have time to review it, just ping @thaJeztah or @moxiegirl

**Comment by thaJeztah** [comment]
Thanks for the ping, sorry for the delays, very busy indeed :)

LGTM!

**Comment by vdemeester** [comment]
LGTM 🐭

**Pull request merged**
