### PR TITLE
Add Justin Cormack to maintainers

### PR DESCRIPTION
**Pull request by thaJeztah**
Welcome, @justincormack!

**\- A picture of a cute animal (not mandatory but encouraged)**
unicornz

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @docker/core-engine-maintainers :tada:

**Comment by coolljt0725** [comment]
LGTM, 恭喜 ^-^

**Comment by vdemeester** [comment]
LGTM 🦄

**Comment by runcom** [comment]
LGTM :)

**Comment by cpuguy83** [comment]
LGTM

**Comment by tianon** [comment]
LGTM!

**Comment by estesp** [comment]
LGTM!

**Comment by thaJeztah** [comment]
This was already voted on per e-mail, and waaaaay too many LGTM's here, so I'l merge :tada:

**Comment by justincormack** [comment]
Thanks all!

**Comment by icecrime** [comment]
Congratulations!

**Comment by jhowardmsft** [comment]
Congrat. Can never have enough :gb:'s :smile:

**Comment by cpuguy83** [comment]
Oh I forgot we already had a 🇬🇧 .... :trollface:

**Pull request merged**
