### PR TITLE
only add the suites that exist we dont need the script for this

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon @tiborvass

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by tianon** [comment]
The script was to span the gap between releases, but it definitely seems pointless here now that we're using apt-ftparchive more effectively.

LGTM

**Comment by tiborvass** [comment]
@tianon do you mind also approving #21038 ?

**Comment by tiborvass** [comment]
No need for CI on this one.

**Pull request merged**
