### PR TITLE
Improve the example for LABEL maintainer

### PR DESCRIPTION
**Pull request by scjane**
Fix #1759

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ripcurld0** [comment]
It looks to me like this change doesn't bring any added-value to the docs.
@thaJeztah @duglin WDYT?

**Comment by scjane** [comment]
This issue is related to https://github.com/docker/docker.github.io/issues/1759. Please have a look. Thanks.

**Review by boaz0 — COMMENTED** [review]
LGTM

**Comment by vdemeester** [comment]
@scjane can you sign your commit ? 🙏

**Comment by AkihiroSuda** [comment]
ping @scjane 

LGTM except DCO

**Comment by scjane** [comment]
Sorry, I failed to amend the commit because my SourceTree client went wrong. I tried to fix it but nothing took effect.

**Comment by thaJeztah** [comment]
@scjane have you tried through the command-line?

**Comment by cpuguy83** [comment]
Closing since this doc doesn't exist in this repo anymore. Also please open docs changes against master branch.
If you'd like to still make this change, you can do so in github.com/docker/cli.
Thanks!

**Pull request closed without merging**
