### PR TITLE
Fix racy test TestLogsFollowSlowStdoutConsumer

### PR DESCRIPTION
**Pull request by aaronlehmann**
This test fails consistently in ARM CI. The test is racy because it depends on a 0.6 second sleep to give the test enough time to start following logs before the log output starts. Change it to poll for the existence of a file instead.

cc @tonistiigi

### CODE REVIEW

**Comment by tonistiigi** [comment]
@aaronlehmann Not sure I understand. If the process has already finished `logs -f` should still work for that container.

**Comment by aaronlehmann** [comment]
> @aaronlehmann Not sure I understand. If the process has already finished logs -f should still work for that container.
> 

@tonistiigi does logs -f always start from the beginning of the log stream? If so, why was the sleep there?

**Comment by tonistiigi** [comment]
@aaronlehmann I don't think it changes the start condition. I don't remember the details but this test was modeled after a bug in the attach/logs code and I think these conditions were how that bug could be reproduced.

**Comment by aaronlehmann** [comment]
@tonistiigi: I did some testing and it doesn't look like `docker logs -f` shows logs from the beginning of the container's output.

```
$ docker run -d busybox sh -c 'for i in `seq 1 5`; do yes X | head -c 200000; sleep 5; done'
a1685d1d78495a69c792b792be9ab022d57a5bae1109fd6d2d6c4eda542f544c
$ # wait about 15 seconds
$ docker logs -f a1685d1d78495a69c792b792be9ab022d57a5bae1109fd6d2d6c4eda542f544c | wc -l
  500000
```

However, if I do this without waiting, I see the full 1000000 bytes from `docker logs -f`.

I think the reason why the test is failing on ARM is that `docker logs -f` doesn't start until well after the container has started outputting the the logs, and we miss some of the expected output.

However, my first attempt didn't fix this, probably because forking off `docker logs -f` doesn't actually wait for attaching to the log stream. I've added some additional synchronization - let's see if that makes a difference.

**Pull request closed without merging**
