### PR TITLE
Bump API version to 1.32

### PR DESCRIPTION
**Pull request by thaJeztah**
ping @vieux @mavenugo @tiborvass

### CODE REVIEW

**Comment by thaJeztah** [comment]
windows failing on TestEventsLimit, which was flaky in the past, probably again https://github.com/moby/moby/issues/28873

```
17:22:45 ----------------------------------------------------------------------
17:22:45 FAIL: docker_cli_events_test.go:84: DockerSuite.TestEventsLimit
17:22:45 
17:22:45 docker_cli_events_test.go:116:
17:22:45     c.Assert(err, checker.IsNil, check.Commentf("%q failed with error", strings.Join(args, " ")))
17:22:45 ... value *errors.errorString = &errors.errorString{s:"exit status 125: d:\\CI\\CI-05121d555\\binary\\docker.exe: Error response from daemon: failed to create endpoint vigilant_allen on network nat: failed to save endpoint 7dccd36 to store: failed to update store for object type *windows.hnsEndpoint: open D:\\CI\\CI-05121d555\\daemon/network/files/local-kv.db.lock: The process cannot access the file because it is being used by another process.\n"} ("exit status 125: d:\\CI\\CI-05121d555\\binary\\docker.exe: Error response from daemon: failed to create endpoint vigilant_allen on network nat: failed to save endpoint 7dccd36 to store: failed to update store for object type *windows.hnsEndpoint: open D:\\CI\\CI-05121d555\\daemon/network/files/local-kv.db.lock: The process cannot access the file because it is being used by another process.\n")
17:22:45 ... "run --rm busybox true" failed with error
17:22:45
```

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by justincormack — APPROVED** [review]

**Comment by jhowardmsft** [comment]
@thaJeztah no, this is different.

@msabansal Interesting that this has cropped up in RS1 now. Could it be a libnetwork bug? (I know you were investigating internally on RS3 parallel start)

**Comment by msabansal** [comment]
Its a change in docker to save endpoints that's causing it. It is likely because of something in boltdb. I have the logs from a repro i need to look at. Will open a libnetwork issue after that.

**Comment by jhowardmsft** [comment]
@msabansal Cool, thanks!

**Pull request merged**
