### PR TITLE
Add zsh completion for 'docker swarm' commands

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #23363
@vincentbernat

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vincentbernat** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by thaJeztah** [comment]
LGTM. but this needs a rebase :cry:

**Comment by sdurrheimer** [comment]
Rebased

**Pull request merged**
