### PR TITLE
Introduce a client-side version of resolveAuthConfig

### PR DESCRIPTION
**Pull request by aaronlehmann**
This is similar to the version in the registry package, but uses the daemon's default index (as opposed to the default for the client's platform) if using the "official index".

This should fix authenticated registry operations on "win2lin". About to test.

NOTE: This PR includes #19973, and should be merged after that one.

cc @icecrime @tonistiigi

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

I tested login, push, logout on windows client + linux deamon.

**Comment by aaronlehmann** [comment]
This is also working for @friism.

**Comment by friism** [comment]
image

**Comment by tiborvass** [comment]
experimental hit #17215

**Comment by tiborvass** [comment]
gccgo failures unrelated, merging

**Comment by aaronlehmann** [comment]
This should not have been merged before #19973...

**Pull request merged**
