### PR TITLE
Apply build labels to images with only a FROM tag.

### LINKED ISSUE #21525: docker `build --label` does not create label
Run DOD from v1.11.0-rc1 tag:
```bash
$ echo "FROM busybox" > Dockerfile
$ docker build --label some-label=some-value --tag some-image .
[....]
$ docker inspect some-image | grep some-label
[nothing]
```
expected output: something with _some-label_ in it
actual output: nothing

**Output of `docker version`:**

```
Client:
 Version:      1.11.0-rc1
 API version:  1.23
 Go version:   go1.6
 Git commit:   7f4e4ac
 Built:        Fri Mar 25 18:39:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc1
 API version:  1.23
 Go version:   go1.6
 Git commit:   7f4e4ac
 Built:        Fri Mar 25 18:39:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-83-generic
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.858 GiB
Name: a9873e102def
ID: 4WE5:PDOY:U7BT:56Q3:P7DK:D5KK:JU3T:DR2V:RHA2:D56H:7G4L:YGJK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 22
 System Time: 2016-03-25T18:50:38.05557Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### PR DESCRIPTION
**Pull request by calavera**
Fixes #21525

/cc @tiborvass, @ehazlett 

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by ehazlett** [comment]
tested and this lgtm.  thanks!

**Comment by tiborvass** [comment]
LGTM

**Comment by tonistiigi** [comment]
Not directly from this change but `docker history` is inconsistent with `build --label`. On single `FROM` command it creates a new history line now that isn't associated with any `LABEL` commands. On multiline there is no new history item but the config is just altered for the last history item. Maybe `--label` should always make a new commit and specify the message as it would appear from `LABEL` command.

**Comment by runcom** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐧
But I share a little bit the concern of @tonistiigi, but we won't have time to fix this for 1.11 I think.

**Comment by tiborvass** [comment]
@tonistiigi I agree with you, and although I have thought of that solution, I haven't thought of the issues you brought up. The problem I had with the solution you're referring to is the output of `docker build` would be inconsistent: the "successfully built" ID would not be the actual final ID. So we could add a LABEL step after it, but it would look like it comes from the Dockerfile.

If we think it's important to make this right and agree that the additional LABEL step is a better solution, I think we *SHOULD* fix this for 1.11.0. I'd be happy to send a PR.

**Pull request merged**
