### PR TITLE
Add GPFS filesystem IDs

### PR DESCRIPTION
**Pull request by scaleoutsean**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can you squash, and sign off your commits? Otherwise we won't be able to review your PR, thanks!

**Comment by scaleoutsean** [comment]
I will please give me few days to set things up.

**Comment by thaJeztah** [comment]
ping @scaleoutsean just a friendly reminder :smile:

**Comment by scaleoutsean** [comment]
I hope this will do.
The instructions don't seem to work exactly to the letter. I hadn't use git client to begin with, so I downloaded my fork and messed around it until it appeared to do something. Don't know if that other commit (#18282) is supposed to appear in my PR, but it gets added after `git rebase -i HEAD~2` so I assume that's how it should be.

**Comment by thaJeztah** [comment]
I think you need to rebase, because there's a non-related commit in this pr now :cry:

**Comment by estesp** [comment]
@scaleoutsean I think you are an IBMer--if you need help with this reach out to myself or @duglin and I'm sure we can help you get this sorted out!

**Comment by scaleoutsean** [comment]
Thanks @thaJeztah and @estesp, I was traveling and didn't have time to attend to this.

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @estesp for the merge

**Comment by estesp** [comment]
LGTM

**Comment by thaJeztah** [comment]
@estesp @scaleoutsean does IBM need this change for docker 1.10? Looks like a simple change, so probably safe to cherry-pick, but just asking (otherwise it'll be in 1.11)

**Comment by scaleoutsean** [comment]
I can't speak for the company, but from my personal perspective it'd be nice to have it sooner because it makes Docker on this filesystem slightly easier to manage (when one sees the underlying filesystem is recognized rather than unknown).

**Comment by thaJeztah** [comment]
Alright, well basically it's a bug (docker doesn't recognize GPFS filesystem) :wink: so, let's mark it for cherry-picking

**Pull request merged**
