### PR TITLE
Dockerfile: Make it easier to use ctr in shell container

### PR DESCRIPTION
**Pull request by vvoland**
**- What I did**
Running `ctr` in `make shell` doesn't work by default - one has to invoke it via `ctr --address /run/docker/containerd/containerd.sock -n moby` or set the CONTAINERD_{ADDRESS,NAMESPACE} environment variables to be able to just use `ctr`.

Considering ephemeral nature of these containers it's cumbersome to do it every time manually - this commit sets the variables to the default containerd socket address and makes it much easier to use ctr.

Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>

**- How to verify it**
Before:
```bash
root@a8efcf765514:/go/src/github.com/docker/docker# ctr image ls
ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///run/containerd/containerd.sock: timeout"

root@a8efcf765514:/go/src/github.com/docker/docker# ctr --address /run/docker/containerd/containerd.sock -n moby image ls
REF                             TYPE                                                      DIGEST                                                                  SIZE    PLATFORMS                                                                                LABELS
docker.io/library/alpine:latest application/vnd.docker.distribution.manifest.list.v2+json sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a 3.1 MiB linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -

```

After:
```bash
root@a8efcf765514:/go/src/github.com/docker/docker# ctr image ls
REF                             TYPE                                                      DIGEST                                                                  SIZE    PLATFORMS                                                                                LABELS
docker.io/library/alpine:latest application/vnd.docker.distribution.manifest.list.v2+json sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a 3.1 MiB linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -

```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Reminds me that we need to re-discuss https://github.com/moby/moby/pull/43950 (which probably would make some of these not needed)

**Review by rumpl — APPROVED** [review]

**Comment by thaJeztah** [comment]
For others; I had a quick look to see if this environment variable is used in places _other than_ `ctr` itself, but it looks like it's handled in the `ctr` binary, so this should be fine®. See

https://github.com/containerd/containerd/blob/0181b103ea31177edc77e7071340e91786891708/cmd/ctr/app/main.go#L87
https://github.com/containerd/containerd/blob/0181b103ea31177edc77e7071340e91786891708/cmd/ctr/app/main.go#L101

@vvoland The only thing I was looking; what location do we use for the containerd socket in the `dev-systemd-true` situation? Is that the same path? If that stage uses containerd's default location, then these variables should probably be added in the `dev-systemd-false` stage.

**Comment by vvoland** [comment]
Looks like `dev-systemd-true` is mostly used now for the rootless integration tests. If you just run `dockerd` in the `make DOCKER_SYSTEMD=true shell` then it still uses the same `/run/docker/containerd/containerd.sock` socket.
If you run `DOCKER_ROOTLESS=1 test-integration` instead of `shell` it's something like: `/tmp/docker-1000/docker/containerd/containerd.sock`.
I guess it wouldn't hurt to keep it for both `dev-systemd-false` and `dev-systemd-true`, because integration tests aren't interactive by design so the dev probably won't use the `ctr`. 

Moving it to `dev-system-false` make sense to me too, so let's move it there.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by neersighted — APPROVED** [review]

**Pull request merged**
