### PR TITLE
Apparmor engine policy nofile

### PR DESCRIPTION
**Pull request by stefanberger**
Some extensions to your profile that I needed when running the devicemapper backend.

### CODE REVIEW

**Comment by stefanberger** [comment]
@ewindisch Here's a patch on top of your work.

**Comment by stefanberger** [comment]
@ewindisch This is an updated policy now with finer grained sub profiles not using 'file' anymore.

**Comment by jfrazelle** [comment]
going to close in favor of https://github.com/docker/docker/pull/14934, sorry , but it would be great if you could help us test that, @ewindisch lmk if this was the wrong thing

**Comment by ewindisch** [comment]
@jfrazelle thise just needs to be rebased on top of #14934 once that merges.

@stefanberger making PRs to ewindisch/docker is always an option, too. Thanks for helping out on this! We'll get your changes in once we get the current state of the repo sorted

**Pull request closed without merging**
