### PR TITLE
Remove systemd socket file from debs and rpms

### LINKED ISSUE #23981: Cannot start docker engine after upgrade of both fedora & docker-engine due to selinux errors
Previously running Fedora 23 with docker-engine{,-selinux} 1.10.3 from Docker repos (not Fedora repos) - working fine for months. Upgraded to Fedora 24, updated to Docker 1.11.2 throws an error:

```
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at line 148 of /var/lib/selinux/targeted/tmp/modules/100/virt/cil
/usr/sbin/semodule:  Failed!
```

Have a colleague with exactly the same problem. Tried uninstalling RPMs & reinstalling but no luck.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:31:13 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Laptop running Fedora 24

**Steps to reproduce the issue:**
Not sure it's 100% reproducible, but have a couple of colleagues with the same issue.

**Describe the results you received:**
Cannot start docker.

**Describe the results you expected:**
Able to start docker.

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #23981

The selinux issue we are seeing in the report is related to the socket
file for docker and nothing else.  By removing the socket docker starts
up correctly.

However, there is another motivation for removing socket activation from
docker's systemd files and that is because when you have daemons running
with `--restart always` whenever you have a host reboot those daemons
will not be started again because the docker daemon is not started by
systemd until a request comes into the docker API.

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by crosbymichael** [comment]
Tested and verified both issues on fedora 24

**Comment by thaJeztah** [comment]
Also needs an update to the documentation; the `dockerd` docs has a reference to `socket activation`; https://github.com/docker/docker/blob/master/docs/reference/commandline/dockerd.md#daemon-socket-option

**Comment by thaJeztah** [comment]
and probably the systemd docs; https://github.com/docker/docker/blob/master/docs/admin/systemd.md

**Comment by crosbymichael** [comment]
@thaJeztah those docs are just showing you how to configure it if you want the various things, it does not have to do with the default we ship

**Comment by thaJeztah** [comment]
It points to the files in our GitHub repo I think, but I can make changes in a follow up PR

**Pull request closed without merging**
