### PR TITLE
Expose RootFS in image inspect

### LINKED ISSUE #20451: [proposal] Expose layer IDs for images through the api
The concept of layers was added in `v1.10` but there is currently no way to ask from the API what layers an image is using. This would make it possible to observe what layers are shared and validate that layers are the same as in registry/load tarball.

Ways to implement this:

1) Add `rootfs` section to the image inspect output. This lists all layer IDs and a baselayer name in windows.

2) Add `docker inspect --raw`. That would show the raw content addressable image config. This has an added benefit that you can verify that sha256 of this config makes up the image ID. Note that not all fields in `docker inspect` are in the raw config(there is no parent, tags etc.).

3) Both 1 and 2?

Asked in:
#17366
#20399
#18727

cc @aaronlehmann @dmcgowan

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes #20451

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Code LGTM

**Comment by mlaventure** [comment]
:+1: , the docker remote api doc will need to be updated to add the output to the example response though :)

**Comment by tiborvass** [comment]
Ping @tonistiigi needs a rebase, otherwise looks good.

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
Windows failure is unfortuantely expected, and the other failures are just one test that is fixed in #21411

**Comment by HackToday** [comment]
do we have docs update for this ?

**Pull request merged**
