### PR TITLE
Fix broken documentation links

### PR DESCRIPTION
**Pull request by yoanisgil**
Note: I am using relative paths ... not sure if that's the way you handle this ;).

### CODE REVIEW

**Comment by calavera** [comment]
LGTM. Thank you!

/cc @thaJeztah, @moxiegirl

**Comment by calavera** [comment]
PS: This PR and #14963 are complementaries.

**Comment by thaJeztah** [comment]
Actually, these features are now (or coming with 1.8) no longer experimental, so, either they should be *removed* from this list, or a new heading should be added, e.g, "Previously experimental features" (perhaps a better title)

@moxiegirl any preference? I'm leaning towards adding a new heading, so that people landing on this page know what happened to an experimental feature.

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
@thaJeztah I'd prefer to remove them once they are no longer experimental.  Keeping an old list around seems like extra work --- we already have the material in the new docs.

**Comment by thaJeztah** [comment]
@moxiegirl sgtm (agreed, maintaining could be an issue)

@yoanisgil could you up date your PR, and *remove* the links instead?

**Comment by yoanisgil** [comment]
So we need to identify which of these features are no longer experimental
(I.e they are already present in master) and which one are not. Right ? Is
there an easy way to tell them apart. If not maybe someone with far more
knowledge of the project could help.

**Comment by thaJeztah** [comment]
@yoanisgil Both features are no longer experimental and can be removed from this page. The links should have been removed as part of https://github.com/docker/docker/pull/14659, but we missed that during review, so thanks for spotting that :-)

In future we should just pay better attention that the links are removed as well :-)

**Comment by thaJeztah** [comment]
Oh! These links are now removed in https://github.com/docker/docker/pull/15106, which makes this PR redundant.

I'll close this PR, but thanks for contributing @yoanisgil, much appreciated!

**Pull request closed without merging**
