### PR TITLE
pkg/parsers/kernel: gofmt hex value (preparation for Go 1.13+)

### PR DESCRIPTION
**Pull request by thaJeztah**
(separating from https://github.com/moby/moby/pull/39549)

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @kolyshkin @tiborvass PTAL

**Comment by thaJeztah** [comment]
Looks like `DockerSwarmSuite.TestSwarmClusterRotateUnlockKey` is still flaky; https://ci.docker.com/public/job/moby/job/PR-39883/1/execution/node/211/log/

```
20:24:13  FAIL: docker_cli_swarm_test.go:1333: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
...
20:24:13  docker_cli_swarm_test.go:1413:
20:24:13      c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
20:24:13  ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000934240), Stderr:[]uint8(nil)} ("exit status 1")
20:24:13  ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
20:24:13  
```

Test was updated in https://github.com/moby/moby/pull/39616 to fix the flakiness, but the interesting bit there is that the retry loop should have a 3 second sleep before retrying, but looking at the failure above, the test started (and failed) within a second, which means that
a different error / output was returned.

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/39885 to add more debugging to that test

**Comment by thaJeztah** [comment]
RS1 failing on https://github.com/moby/moby/issues/38521

https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39883/runs/1/nodes/178/log/?start=0

```
 ----------------------------------------------------------------------
 FAIL: docker_cli_start_test.go:190: DockerSuite.TestStartReturnCorrectExitCode
 
 docker_cli_start_test.go:200:
     c.Assert(exitCode, checker.Equals, 12, check.Commentf("out: %s", out))
 ... obtained int = 125
 ... expected int = 12
 ... out: time="2019-09-09T19:13:46Z" level=error msg="error waiting for container: EOF" 
```

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
