### PR TITLE
Vendoring boltdb @fff57c100

### LINKED ISSUE #24315: Docker fails to start: panic: runtime error: index out of range
**Output of `docker version`:**

```
Docker version 1.10.3, build 20f81dd
```

**Output of `docker daemon`:**

```
INFO[0001] Graph migration to content-addressability took 0.00 seconds
INFO[0001] Firewalld running: false
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xd8ff38, 0x1171e008)
        /home/theodor/resin-devices/resin-ts/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/panic.go:464 +0x330
github.com/boltdb/bolt.(*Bucket).pageNode(0x11711720, 0x6b720004, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/boltdb/bolt/bucket.go:696 +0x2f8
github.com/boltdb/bolt.(*Cursor).search(0x11bf8eb4, 0x11bf8e1c, 0x1b, 0x1b, 0x6b720004, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/boltdb/bolt/cursor.go:238 +0x30
github.com/boltdb/bolt.(*Cursor).seek(0x11bf8eb4, 0x11bf8e1c, 0x1b, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/boltdb/bolt/cursor.go:152 +0xd0
github.com/boltdb/bolt.(*Cursor).Seek(0x11bf8eb4, 0x11bf8e1c, 0x1b, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/boltdb/bolt/cursor.go:111 +0x5c
github.com/docker/libkv/store/boltdb.(*BoltDB).List.func1(0x118f9f00, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libkv/store/boltdb/boltdb.go:285 +0x178
github.com/boltdb/bolt.(*DB).View(0x1178ec00, 0x11bf8f24, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/boltdb/bolt/db.go:578 +0xb0
github.com/docker/libkv/store/boltdb.(*BoltDB).List(0x1193f9c0, 0x11711620, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libkv/store/boltdb/boltdb.go:299 +0x19c
github.com/docker/libnetwork/datastore.(*cache).kmap(0x11794670, 0xb54c6158, 0x1188bb60, 0x74ff8, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/datastore/cache.go:43 +0x20c
github.com/docker/libnetwork/datastore.(*cache).list(0x11794670, 0xb54c6158, 0x1188bb60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/datastore/cache.go:139 +0x48
github.com/docker/libnetwork/datastore.(*datastore).List(0x1170f170, 0x117115c0, 0x1b, 0xb54c6158, 0x1188bb60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/datastore/datastore.go:472 +0xd8
github.com/docker/libnetwork/drivers/bridge.(*driver).populateNetworks(0x1170e1b0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:49 +0x130
github.com/docker/libnetwork/drivers/bridge.(*driver).initStore(0x1170e1b0, 0x1187de20, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:42 +0x33c
github.com/docker/libnetwork/drivers/bridge.(*driver).configure(0x1170e1b0, 0x1187de20, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:395 +0x310
github.com/docker/libnetwork/drivers/bridge.Init(0xb54c5f68, 0x118d5860, 0x1187de20, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:140 +0x58c
github.com/docker/libnetwork.initDrivers(0x118d5860, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/drivers.go:20 +0x220
github.com/docker/libnetwork.New(0x1187dca0, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/vendor/src/github.com/docker/libnetwork/controller.go:189 +0x464
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0x118b0000, 0x11be2300, 0x0, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:532 +0x9c
github.com/docker/docker/daemon.NewDaemon(0x11be2300, 0x1171e638, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/.gopath/src/github.com/docker/docker/daemon/daemon.go:761 +0x1dfc
main.(*DaemonCli).CmdDaemon(0x11bd5ec0, 0x1170a108, 0x0, 0x0, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/docker/daemon.go:252 +0x1430
reflect.callMethod(0x119523a0, 0x11bf9e04)
        /home/theodor/resin-devices/resin-ts/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/reflect/value.go:631 +0x1ac
reflect.methodValueCall(0x1170a108, 0x0, 0x0, 0x1, 0x119523a0, 0x0, 0x0, 0x119523a0, 0x1171e4e8, 0x1efcc, ...)
        /home/theodor/resin-devices/resin-ts/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/reflect/asm_arm.s:29 +0x38
github.com/docker/docker/cli.(*Cli).Run(0x119522c0, 0x1170a108, 0x1, 0x1, 0x0, 0x0)
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x2e8
main.main()
        /home/theodor/resin-devices/resin-ts/build/tmp/work/armv5e-poky-linux-gnueabi/docker/1.10.3+git20f81dde9bd97c86b2d0e33bbbf1388018611929-r0/git/docker/docker.go:63 +0x40c
```

**Additional information**
I have the exact same setup (OS + docker 1.10) on a few machines with different architectures (e.g. x86, armv6, armv7), but on a machine with armv5  I get the error mentioned above. After a bit of code digging it look like docker does not find the correct index for my network interface (the id should be smaller id - 1).

Any hints will be heavily appreciated.

### PR DESCRIPTION
**Pull request by aboch**
Vendor to latest boltdb which Fixes #24315 

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

cc @stevvooe

**Comment by stevvooe** [comment]
LGTM

@tonistiigi Is this related to https://github.com/docker/swarmkit/issues/1503 by any chance?

**Comment by tonistiigi** [comment]
@stevvooe This specific bug seems to be about arm. But it may contain other fixes as well.

**Review by stevvooe — APPROVED** [review]

**Comment by aboch** [comment]
@stevvooe @tonistiigi 
It also bring in another change which under some condition would skip the unsafe pointer line which caused the panic seen in the swarmkit issue:
https://github.com/docker/docker/pull/26607/files#diff-359ba59531002d4ae90de84a80cfc635R204

**Comment by stevvooe** [comment]
Looks like we can close https://github.com/docker/swarmkit/issues/1503, then. We've pulled in these changes with https://github.com/docker/swarmkit/pull/1510.

**Comment by stevvooe** [comment]
@aaronlehmann Add this to the 1.12.2 milestone, as this should be backported.

**Pull request merged**
