### PR TITLE
Correct fmt.Fprintf and t.Fatalf

### PR DESCRIPTION
**Pull request by fate-grand-order**
Signed-off-by: Helen Xie <chenjg@harmonycloud.cn>

**- What I did**
Correct fmt.Fprintf and t.Fatalf, because the values used for formatting text does not appear to contain a placeholder.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
https://github.com/docker/docker/blob/master/CONTRIBUTING.md

> Signed-off-by: Joe Smith <joe.smith@email.com>
> Use your real name (sorry, no pseudonyms or anonymous contributions.)

**Comment by fate-grand-order** [comment]
I'm sorry and I have modified.

**Comment by AkihiroSuda** [comment]
We have so many similar issues
So I'm not sure we should try to fix them, but if we should, we should do it at once.

<details>
<summary>`Fprintf`</summary>
<pre>
cli/command/checkpoint/list.go: fmt.Fprintf(w, "\n")
cli/command/node/inspect.go:                    fmt.Fprintf(out, "\n\n")
cli/command/node/inspect.go:                    fmt.Fprintf(out, "\n")
cli/command/registry/search.go: fmt.Fprintf(w, "NAME\tDESCRIPTION\tSTARS\tOFFICIAL\tAUTOMATED\n")
cli/command/secret/ls.go:               fmt.Fprintf(w, "\n")
cli/command/swarm/unlock_key.go:                        fmt.Fprintf(dockerCli.Out(), "Successfully rotated manager unlock key.\n\n")
cli/command/system/info.go:     fmt.Fprintf(dockerCli.Out(), "Plugins: \n")
cli/command/system/info.go:     fmt.Fprintf(dockerCli.Out(), "\n")
cli/command/system/info.go:     fmt.Fprintf(dockerCli.Out(), "\n")
cli/command/system/info.go:             fmt.Fprintf(dockerCli.Out(), "\n")
cli/command/system/info.go:                     fmt.Fprintf(dockerCli.Out(), " Orchestration:\n")
cli/command/system/info.go:                     fmt.Fprintf(dockerCli.Out(), " Raft:\n")
cli/command/system/info.go:                     fmt.Fprintf(dockerCli.Out(), " Dispatcher:\n")
cli/command/system/info.go:                     fmt.Fprintf(dockerCli.Out(), " CA Configuration:\n")
cli/command/system/info.go:                             fmt.Fprintf(dockerCli.Out(), "  External CAs:\n")
cli/command/system/info.go:                     fmt.Fprintf(dockerCli.Out(), " Manager Addresses:\n")
cli/command/system/info.go:                     fmt.Fprintf(dockerCli.Out(), "\n")
cli/command/system/info.go:                     fmt.Fprintf(dockerCli.Out(), "Security Options:\n")
cli/command/system/info.go:                                                     fmt.Fprintf(dockerCli.Err(), "  WARNING: You're not using the default seccomp 
profile\n")
pkg/jsonmessage/jsonmessage.go:                                 fmt.Fprintf(out, "\n")
</pre>
</details>

<details>
<summary>`Fatalf`</summary>
<pre>
api/common_test.go:             t.Fatalf("expected an error, got nothing.")
api/server/httputils/form_test.go:              t.Fatalf("Expected an error.")
api/server/middleware/version_test.go:                  t.Fatalf("Expected version, got empty string")
api/server/middleware/version_test.go:                  t.Fatalf("Expected version, got empty string")
api/types/filters/parse_test.go:                t.Fatalf("Expected to not include a running status filter, got true")
api/types/filters/parse_test.go:                t.Fatalf("Expected to not include any field")
api/types/filters/parse_test.go:                t.Fatalf("Expected to include one field")
api/types/filters/parse_test.go:                t.Fatalf("Expected to match `running` when there are no filters, got false")
api/types/filters/parse_test.go:                t.Fatalf("Expected to match `running` with one of the filters, got false")
api/types/filters/parse_test.go:                t.Fatalf("Expected to not match `paused` with one of the filters, got true")
api/types/filters/parse_test.go:                t.Fatalf("Expected to match `running` when there are no filters, got false")
api/types/filters/parse_test.go:                t.Fatalf("Expected to match `running` with one of the filters, got false")
api/types/filters/parse_test.go:                t.Fatalf("Expected to not match `paused` with one of the filters, got true")
api/types/filters/parse_test.go:                t.Fatalf("Expected to not match only `running` with two filters, got true")
api/types/filters/parse_test.go:                t.Fatalf("Expected to not include a status key, got true")
api/types/filters/parse_test.go:                t.Fatalf("Expected to include a status key, got false")
api/types/filters/parse_test.go:                t.Fatalf("Expected to return an error, got nil")
api/types/filters/parse_test.go:                t.Fatalf("Expected to get an error, got nil")
builder/dockerfile/bflag_test.go:               t.Fatalf("Test-b2 Bool1 was supposed to be true")
builder/dockerfile/parser/parser_test.go:               t.Fatalf("Root line information doesn't match result.")
builder/dockerfile/parser/parser_test.go:                       t.Fatalf("Root line information doesn't match result.")
builder/dockerignore/dockerignore_test.go:              t.Fatalf("First element is not test1")
builder/dockerignore/dockerignore_test.go:              t.Fatalf("Second element is not /test2")
builder/dockerignore/dockerignore_test.go:              t.Fatalf("Third element is not /a/file/here")
builder/dockerignore/dockerignore_test.go:              t.Fatalf("Fourth element is not lastfile")
builder/remote_test.go:         t.Fatalf("Should have generated an error for an empty response")
builder/remote_test.go:         t.Fatalf("Remote context should not be nil")
builder/remote_test.go:         t.Fatalf("Cast error, remote context should be casted to tarSumContext")
builder/tarsum_test.go:         t.Fatalf("Directory should not exist at this point")
builder/tarsum_test.go:         t.Fatalf("File info should be nil")
builder/tarsum_test.go:         t.Fatalf("Directory should not exist at this point")
builder/tarsum_test.go:         t.Fatalf("Tar sum context should not be nil")
builder/tarsum_test.go:         t.Fatalf("Error should not be nil")
cli/command/container/opts_test.go:             t.Fatalf("Expected error with [valid streams are STDIN, STDOUT and STDERR], got nothing")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-a` should be an error but is not")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-a invalid` should be an error but is not")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-a stdout -a invalid` should be an error but is not")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-a stdout -a stderr -d` should be an error but is not")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-a stdin -d` should be an error but is not")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-a stdout -d` should be an error but is not")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-a stderr -d` should be an error but is not")
cli/command/container/opts_test.go:             t.Fatalf("Error parsing attach flags, `-d --rm` should be an error but is not")
cli/command/image/build/context_test.go:                t.Fatalf("Error should not be nil")
cli/command/image/build/context_test.go:                t.Fatalf("Error should not be nil")
cli/command/image/build/context_test.go:                t.Fatalf("Error should not be nil")
cli/command/image/build/context_test.go:                t.Fatalf("Error should not be nil")
client/client_test.go:                  t.Fatalf("expected error, got nil")
client/config/config_test.go:           t.Fatalf("Was supposed to fail")
client/config/config_test.go:           t.Fatalf("Expected error. File should not have been able to save with no file name.")
client/config/config_test.go:           t.Fatalf("Expected error. File should not have been able to save with no file name.")
client/container_copy_test.go:          t.Fatalf("expected an error, got nothing")
client/container_copy_test.go:          t.Fatalf("expected an error, got nothing")
client/container_inspect_test.go:               t.Fatalf("expected `bar` for label `foo`")
client/image_load_test.go:                      t.Fatalf("expected a JSON response, was not.")
cmd/dockerd/daemon_test.go:             t.Fatalf("expected debug to be copied from the common flags, got false")
daemon/daemon_linux_test.go:            t.Fatalf("Expected to unmount the shm (and the shm only)")
daemon/daemon_linux_test.go:            t.Fatalf("Expected to unmount the auf root (and that only)")
daemon/daemon_linux_test.go:            t.Fatalf("Expected not to clean up /dev/shm")
daemon/daemon_test.go:          t.Fatalf("Expected debug 'enabled', got 'disabled'")
daemon/daemon_unix_test.go:             t.Fatalf("Expected networkOptions error, got nil")
daemon/discovery_test.go:               t.Fatalf("discovery.ttl < discovery.heartbeat must fail")
daemon/discovery_test.go:               t.Fatalf("discovery.ttl == discovery.heartbeat must fail")
daemon/discovery_test.go:               t.Fatalf("negative discovery.heartbeat must fail")
daemon/discovery_test.go:               t.Fatalf("negative discovery.ttl must fail")
daemon/discovery_test.go:               t.Fatalf("invalid discovery.heartbeat must fail")
daemon/discovery_test.go:               t.Fatalf("invalid discovery.ttl must fail")
daemon/events_test.go:          t.Fatalf("LogEvent test timed out")
daemon/graphdriver/aufs/aufs_test.go:           t.Fatalf("Driver should not be nil")
daemon/graphdriver/aufs/aufs_test.go:           t.Fatalf("Response if dir id 1 is mounted should be false")
daemon/graphdriver/aufs/aufs_test.go:           t.Fatalf("Response if dir id 2 is mounted should be true")
daemon/graphdriver/aufs/aufs_test.go:           t.Fatalf("Dir id 2 should be mounted")
daemon/graphdriver/aufs/aufs_test.go:           t.Fatalf("Error should not be nil with parent does not exist")
daemon/graphdriver/aufs/aufs_test.go:           t.Fatalf("Archive should not be nil")
daemon/graphdriver/devmapper/devmapper_test.go:         t.Fatalf("data or metadata loop back size is incorrect")
daemon/graphdriver/devmapper/devmapper_test.go:         t.Fatalf("data or metadata loop back size is incorrect")
daemon/graphdriver/devmapper/devmapper_test.go:         t.Fatalf("Could not acquire devices lock after call to cleanupDeletedDevices()")
daemon/links/links_test.go:             t.Fatalf("DOCKER_1_PORT not found in env")
daemon/logger/copier_test.go:           t.Fatalf("failed to exit in time after the copier is closed")
distribution/pull_v2_test.go:           t.Fatalf("expected an invalid parent ID error from fixManifestLayers")
distribution/pull_v2_test.go:           t.Fatalf("expected an invalid parent ID error from fixManifestLayers")
distribution/push_v2_test.go:   m.t.Fatalf("Named() not implemented")
distribution/push_v2_test.go:   m.t.Fatalf("Manifests() not implemented")
distribution/push_v2_test.go:   m.t.Fatalf("Tags() not implemented")
distribution/push_v2_test.go:   m.repo.t.Fatalf("ServeBlob() not implemented")
distribution/xfer/transfer_test.go:                             t.Fatalf("transfer function not started even though concurrency limit not reached")
distribution/xfer/transfer_test.go:                                     t.Fatalf("too many jobs running")
distribution/xfer/transfer_test.go:                                     t.Fatalf("too many jobs running")
image/fs_test.go:               t.Fatalf("expected error from walker.")
integration-cli/daemon/daemon.go:               t.Fatalf("Please set the DEST environment variable")
integration-cli/daemon/daemon.go:               t.Fatalf("could not create daemon socket root")
integration-cli/docker_api_logs_test.go:                        c.Fatalf("expected log output to container 'hello', but it does not")
integration-cli/docker_api_stats_test.go:               c.Fatalf("Stats did not return after timeout")
integration-cli/docker_cli_attach_test.go:              c.Fatalf("Attaches did not initialize properly")
integration-cli/docker_cli_attach_test.go:              c.Fatalf("Attaches did not finish properly")
integration-cli/docker_cli_authz_unix_test.go:          c.Fatalf("docker version should return information of server side")
integration-cli/docker_cli_build_test.go:                       c.Fatalf("output should've contained the string: Error checking context")
integration-cli/docker_cli_build_test.go:               c.Fatalf("--force-rm shouldn't have left containers behind")
integration-cli/docker_cli_build_test.go:               c.Fatalf("context should have been deleted, but wasn't")
integration-cli/docker_cli_build_test.go:               c.Fatalf("context should have been deleted, but wasn't")
integration-cli/docker_cli_build_test.go:               c.Fatalf("ONBUILD instruction ran in grandchild of ONBUILD parent")
integration-cli/docker_cli_build_test.go:               c.Fatalf("Didn't use the cache - 1")
integration-cli/docker_cli_build_test.go:               c.Fatalf("Didn't use the cache - 2")
integration-cli/docker_cli_build_test.go:               c.Fatalf("Didn't use the cache - 3")
integration-cli/docker_cli_build_test.go:               c.Fatalf("test5 was supposed to fail to find passwd")
integration-cli/docker_cli_build_test.go:               c.Fatalf("build used cache, expected a miss!")
integration-cli/docker_cli_build_test.go:               c.Fatalf("build used cache, expected a miss!")
integration-cli/docker_cli_cp_test.go:          c.Fatalf("Expected copied file to be duplicate of the container symbol link target")
integration-cli/docker_cli_cp_test.go:          c.Fatalf("Expected copied file to be duplicate of the container symbol link target")
integration-cli/docker_cli_create_test.go:              c.Fatalf("Volume was not created")
integration-cli/docker_cli_daemon_test.go:              c.Fatalf("Bridge does not have an IPv6 Address")
integration-cli/docker_cli_daemon_test.go:              c.Fatalf("Container should have a link-local IPv6 address")
integration-cli/docker_cli_daemon_test.go:              c.Fatalf("Error opening key file")
integration-cli/docker_cli_daemon_test.go:              c.Fatalf("Error opening key file")
integration-cli/docker_cli_daemon_test.go:              c.Fatalf("Key not migrated")
integration-cli/docker_cli_daemon_test.go:              c.Fatalf("docker version should return information of server side")
integration-cli/docker_cli_daemon_test.go:                      c.Fatalf("mountinfo should not include the mountpoint of stop container")
integration-cli/docker_cli_events_unix_test.go:                 c.Fatalf("container should be still running but it's not")
integration-cli/docker_cli_external_volume_driver_unix_test.go:         c.Fatalf("volume create with down driver finished unexpectedly")
integration-cli/docker_cli_images_test.go:                      c.Fatalf("All output must be the same")
integration-cli/docker_cli_network_unix_test.go:                t.Fatalf("new container ip should not equal to old running container  ip")
integration-cli/docker_cli_network_unix_test.go:                t.Fatalf("80 port is allocated to old running container, it should failed on allocating to new container")
integration-cli/docker_cli_ps_test.go:          c.Fatalf("Calling \"docker ps -s\" timed out!")
integration-cli/docker_cli_pull_trusted_test.go:                c.Fatalf("Failed to create local temp dir")
integration-cli/docker_cli_run_test.go:         c.Fatalf("use a container name to link target failed")
integration-cli/docker_cli_run_test.go:         c.Fatalf("use a container id to link target failed")
integration-cli/docker_cli_run_test.go:         c.Fatalf("sys should be writable in privileged container")
integration-cli/docker_cli_run_test.go:         c.Fatalf("proc should be writable in privileged container")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run container with device mode ro should fail")
integration-cli/docker_cli_run_test.go:         c.Fatalf("/etc/resolv.conf does not exist")
integration-cli/docker_cli_run_test.go:         c.Fatalf("/etc/resolv.conf does not exist")
integration-cli/docker_cli_run_test.go:         c.Fatalf("/etc/resolv.conf does not exist")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Container should have exited with error code 0")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Container should have exited with error code 0")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Container should have exited with error code 0")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run with an invalid --mac-address should with error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Binding on used port must fail")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run IPC from a non exists container should with correct error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run PID from a non exists container should with correct error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Container should have host network namespace")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Set default restart policy failed")
integration-cli/docker_cli_run_test.go:                 c.Fatalf("Expected RO volume was RW")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Expected RW volume was RO")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Failed to create local temp dir")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Restarting notary server failed.")
integration-cli/docker_cli_run_test.go:         c.Fatalf("SECURITY: --cgroup-parent with ../../ relative paths cause files to be created in the host (this is bad) !!")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run --net=container with --dns should error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run --net=container with --mac-address should error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run --net=container with --add-host should error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run --net=container with -p should error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run --net=container with -P should error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("run --net=container with --expose should error out")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Bind mount under shared volume did not propagate to host")
integration-cli/docker_cli_run_test.go:         c.Fatalf("Bind mount under slave volume did not propagate to container")
integration-cli/docker_cli_run_unix_test.go:            c.Fatalf("/run mounted on tmpfs when it should have vailed within invalid mount option")
integration-cli/docker_cli_run_unix_test.go:            c.Fatalf("Should have generated an error saying Duplicate mount  points")
integration-cli/docker_cli_start_test.go:               c.Fatalf("Attach did not exit properly")
integration-cli/docker_cli_stats_test.go:               c.Fatalf("stats did not return immediately when not streaming")
layer/filestore_test.go:                t.Fatalf("Expected error committing with invalid layer parent directory")
layer/filestore_test.go:                t.Fatalf("Expected error starting transaction with invalid layer parent directory")
opts/opts_test.go:              t.Fatalf("ValidateMACAddress(`92:d0:c6:0a:33`) succeeded; expected failure on invalid MAC")
opts/opts_test.go:              t.Fatalf("ValidateMACAddress(`random invalid string`) succeeded; expected failure on invalid MAC")
opts/ulimit_test.go:            t.Fatalf("Expected error on invalid ulimit type")
pkg/archive/archive_linux_test.go:              t.Fatalf("Non-zero device number for whiteout")
pkg/archive/archive_test.go:            t.Fatalf("isArchive should return false as nil is not a valid archive header")
pkg/archive/archive_test.go:            t.Fatalf("Incorrectly recognised directory as an archive")
pkg/archive/archive_test.go:            t.Fatalf("Incorrectly recognised invalid tar path as archive")
pkg/archive/archive_test.go:            t.Fatalf("Incorrectly recognised invalid compressed tar path as archive")
pkg/archive/archive_test.go:            t.Fatalf("Did not recognise valid tar path as archive")
pkg/archive/archive_test.go:            t.Fatalf("Did not recognise valid compressed tar path as archive")
pkg/archive/archive_test.go:            t.Fatalf("Fail to create the destination file")
pkg/archive/archive_test.go:            t.Fatalf("Should fail as xz is unsupported for compression format.")
pkg/archive/archive_test.go:            t.Fatalf("Fail to create the destination file")
pkg/archive/archive_test.go:            t.Fatalf("Should fail as xz is unsupported for compression format.")
pkg/archive/archive_test.go:            t.Fatalf("Fail to create the destination file")
pkg/archive/archive_test.go:            t.Fatalf("Should fail as xz is unsupported for compression format.")
pkg/archive/archive_test.go:            t.Fatalf("The extension of an invalid compression should be an empty string.")
pkg/archive/archive_test.go:            t.Fatalf("The extension of an uncompressed archive should be 'tar'.")
pkg/archive/archive_test.go:            t.Fatalf("The extension of a bzip2 archive should be 'tar.bz2'")
pkg/archive/archive_test.go:            t.Fatalf("The extension of a bzip2 archive should be 'tar.gz'")
pkg/archive/archive_test.go:            t.Fatalf("The extension of a bzip2 archive should be 'tar.xz'")
pkg/archive/archive_test.go:            t.Fatalf("Command did not complete in 5 seconds; probable deadlock")
pkg/archive/archive_test.go:            t.Fatalf("Command should have failed")
pkg/archive/archive_test.go:            t.Fatalf("UntarPath with invalid destination path should throw an error.")
pkg/archive/archive_test.go:            t.Fatalf("Fail to create the destination file")
pkg/archive/archive_test.go:            t.Fatalf("UntarPath with invalid src path should throw an error.")
pkg/archive/archive_test.go:            t.Fatalf("Fail to create the destination file")
pkg/archive/archive_test.go:            t.Fatalf("Destination folder should contain the source file but did not.")
pkg/archive/archive_test.go:            t.Fatalf("Fail to create the destination file")
pkg/archive/archive_test.go:            t.Fatalf("UntarPath should throw an error if the destination if a file")
pkg/archive/archive_test.go:            t.Fatalf("Fail to create the destination folder")
pkg/archive/archive_test.go:            t.Fatalf("UntarPath should throw not throw an error if the extracted file already exists and is a folder")
pkg/archive/archive_test.go:            t.Fatalf("archiver.CopyWithTar with invalid src path should throw an error.")
pkg/archive/archive_test.go:            t.Fatalf("CopyWithTar with an inexistent folder shouldn't fail.")
pkg/archive/archive_test.go:            t.Fatalf("CopyWithTar with an inexistent folder should create it.")
pkg/archive/archive_test.go:            t.Fatalf("Destination file should be the same as the source.")
pkg/archive/archive_test.go:            t.Fatalf("Destination folder should contain the source file but did not.")
pkg/archive/archive_test.go:            t.Fatalf("archiver.CopyWithTar with invalid src path should throw an error.")
pkg/archive/archive_test.go:            t.Fatalf("CopyWithTar with an inexistent folder shouldn't fail.")
pkg/archive/archive_test.go:            t.Fatalf("CopyWithTar with an inexistent folder should create it.")
pkg/archive/archive_test.go:            t.Fatalf("CopyFileWithTar should throw an error with a folder.")
pkg/archive/archive_test.go:            t.Fatalf("Destination folder should contain the source file but did not.")
pkg/archive/archive_unix_test.go:                       t.Fatalf("Untar should have kept the 'security.capability' xattr.")
pkg/archive/archive_windows_test.go:            t.Fatalf("archiver.CopyWithTar should throw an error on invalid dest.")
pkg/directory/directory_test.go:                t.Fatalf("error is expected")
pkg/fileutils/fileutils_test.go:                t.Fatalf("error expected for non-existing symlink")
pkg/fileutils/fileutils_test.go:                t.Fatalf("ReadSymlinkedDirectory on a symlink to a file should've failed")
pkg/fileutils/fileutils_test.go:                t.Fatalf("Should not have match anything")
pkg/fileutils/fileutils_test.go:                t.Fatalf("Should not have match anything")
pkg/fileutils/fileutils_test.go:                t.Fatalf("Should have been a dir, seems it's not")
pkg/fileutils/fileutils_test.go:                t.Fatalf("Should have been a file, seems it's not")
pkg/httputils/resumablerequestreader_test.go:                   t.Fatalf("Expected a Range HTTP header, got nothing")
pkg/idtools/idtools_unix_test.go:               t.Fatalf("Trying to create a directory with Mkdir where the parent doesn't exist should have failed")
pkg/ioutils/fswriters_test.go:          t.Fatalf("Expected error reading file where should not exist")
pkg/ioutils/fswriters_test.go:          t.Fatalf("Expected error reading file where should not exist")
pkg/ioutils/readers_test.go:            t.Fatalf("readCloserWrapper should have call the anonymous func and thus, fail.")
pkg/ioutils/readers_test.go:            t.Fatalf("readErrWrapper should returned an error")
pkg/ioutils/readers_test.go:            t.Fatalf("readErrWrapper should have call the anonymous function on failure")
pkg/ioutils/readers_test.go:            t.Fatalf("readErrWrapper should not have called the anonymous function")
pkg/ioutils/writers_test.go:            t.Fatalf("writeCloserWrapper should have call the anonymous function.")
pkg/locker/locker_test.go:              t.Fatalf("lock should have completed")
pkg/locker/locker_test.go:              t.Fatalf("lock should not be blocked")
pkg/namesgenerator/names-generator_test.go:             t.Fatalf("Generated name does not contain an underscore")
pkg/namesgenerator/names-generator_test.go:             t.Fatalf("Generated name contains numbers!")
pkg/namesgenerator/names-generator_test.go:             t.Fatalf("Generated name does not contain an underscore")
pkg/namesgenerator/names-generator_test.go:             t.Fatalf("Generated name doesn't contain a number")
pkg/plugins/discovery_test.go:                  t.Fatalf("Expected TLS verification to be skipped")
pkg/plugins/discovery_unix_test.go:                     t.Fatalf("Expected TLS verification to be skipped")
pkg/pools/pools_test.go:                t.Fatalf("BufioReaderPool should have create a bufio.Reader but did not.")
pkg/pools/pools_test.go:                t.Fatalf("BufioReaderPool should not return a nil reader.")
pkg/pools/pools_test.go:                t.Fatalf("The buffer should have been empty, issue an EOF error.")
pkg/pools/pools_test.go:                t.Fatalf("NewReadCloserWrapper should not return a nil reader.")
pkg/pools/pools_test.go:                t.Fatalf("The ReaderCloser should have been closed, it is not.")
pkg/pools/pools_test.go:                t.Fatalf("BufioWriterPool should have create a bufio.Writer but did not.")
pkg/pools/pools_test.go:                t.Fatalf("BufioReaderPool should not return a nil writer.")
pkg/pools/pools_test.go:                t.Fatalf("BufioReaderPool should not return a nil writer.")
pkg/pools/pools_test.go:                t.Fatalf("The ReaderCloser should have been closed, it is not.")
pkg/progress/progressreader_test.go:            t.Fatalf("Expected some output when closing prematurely")
pkg/progress/progressreader_test.go:            t.Fatalf("Should have closed silently when read is complete")
pkg/registrar/registrar_test.go:                t.Fatalf("expected error when reserving an already reserved name to another object")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("NewStdWriter with an invalid StdType should not return nil.")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("Should fail when given an uncomplete or uninitialized StdWriter")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("Shouldn't have fail when given no data")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("Error while writing with StdWrite")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("Didn't get expected error.")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("Didn't get expected error")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("Didn't get expected error")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("StdCopy should not return an error with corrupted prefix.")
pkg/stdcopy/stdcopy_test.go:            t.Fatalf("Didn't get expected io.ErrShortWrite error")
pkg/stringutils/stringutils_test.go:                    t.Fatalf("Random number is repeated")
pkg/stringutils/stringutils_test.go:            t.Fatalf("Expected string t🐳st to be in slice")
pkg/stringutils/stringutils_test.go:            t.Fatalf("Expected string SLICE to be in slice")
pkg/stringutils/stringutils_test.go:            t.Fatalf("Expected string notinslice not to be in slice")
pkg/stringutils/stringutils_test.go:            t.Fatalf("Expected an empty string")
pkg/system/path_windows_test.go:                t.Fatalf("Expected error for d:")
pkg/system/path_windows_test.go:                t.Fatalf("Single character should pass")
pkg/system/path_windows_test.go:                t.Fatalf("Single character should be unchanged")
pkg/system/path_windows_test.go:                t.Fatalf("2 characters without colon should pass")
pkg/system/path_windows_test.go:                t.Fatalf("2 characters without colon should be unchanged")
pkg/system/path_windows_test.go:                t.Fatalf("abs path no drive letter should pass")
pkg/system/path_windows_test.go:                t.Fatalf("abs path without drive letter should be unchanged")
pkg/system/path_windows_test.go:                t.Fatalf("abs path no drive letter linux style should pass")
pkg/system/path_windows_test.go:                t.Fatalf("An absolute path should pass")
pkg/system/path_windows_test.go:                t.Fatalf("An absolute path should pass")
pkg/system/path_windows_test.go:                t.Fatalf("c: should fail")
pkg/system/path_windows_test.go:                t.Fatalf("c: should fail")
pkg/tarsum/tarsum_test.go:              t.Fatalf("Expected an error, got nothing.")
pkg/tarsum/tarsum_test.go:              t.Fatalf("Expected an error, got nothing.")
pkg/tarsum/tarsum_test.go:              t.Fatalf("Expected an error, got nothing.")
pkg/term/ascii_test.go:         t.Fatalf("Expected error, got none")
pkg/testutil/utils_test.go:             t.Fatalf("Expected the ls command to not be killed, was.")
pkg/testutil/utils_test.go:             t.Fatalf("Expected the command to be killed, was not.")
pkg/truncindex/truncindex_test.go:              t.Fatalf("Adding an id with ' ' should return an error")
pkg/truncindex/truncindex_test.go:              t.Fatalf("Adding an empty id should return an error")
pkg/truncindex/truncindex_test.go:              t.Fatalf("Deleting a non-existing id should return an error")
pkg/useragent/useragent_test.go:                t.Fatalf("VersionInfo should be valid")
pkg/useragent/useragent_test.go:                t.Fatalf("Expected VersionInfo to be invalid")
pkg/useragent/useragent_test.go:                t.Fatalf("Expected VersionInfo to be invalid")
runconfig/opts/envfile_test.go:         t.Fatalf("Expected an ErrBadEnvVariable, got nothing")
runconfig/opts/envfile_test.go:         t.Fatalf("Expected an ErrBadEnvVariable, got nothing")
volume/store/store_test.go:             t.Fatalf("Expected unknown driver error, got nil")
</pre>
</details>

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
