### PR TITLE
surfacing Learn by example topics to top level of Docker Engine docs

### PR DESCRIPTION
**Pull request by londoncalling**
**\- What I did**
Moved "Learn by example" tutorials up a level in the docs to show up under a menu right after "Install". This is to prepare for moving "Getting Started" tutorial into the docs menu (and merging it into one to cover all OS's). The "Getting Started" tutorial will be the landing page for Docker for Mac, Docker for Windows, Docker for Linux.

**\- How I did it**
Moved files around and added the right metadata and link forwarding to each file.

**\- How to verify it**
Local builds.

**\- Description for the changelog**
Surfacing tutorials in Docs menus instead of burying them under "User Guide"

Signed-off-by: Victoria Bialas victoria.bialas@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM!

and this makes me happy (we had some "moves" in the past that were a "remove" and "add" instead of an actual move) 👍 

screen shot 2016-06-13 at 20 20 47

**Comment by thaJeztah** [comment]
ping @vdemeester for review/merge 🐰

**Comment by vdemeester** [comment]
LGTM 🐭

**Comment by thaJeztah** [comment]
oh! @londoncalling looks like there were quite some links referring to these pages that need to be updated :cry:;

```
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../containers/dockerimages.md
18:26:55 * link error: (in page engine/userguide/intro.md) containers/dockervolumes.md
18:26:55 * link error: (in page engine/userguide/networking/dockernetworks.md) ../containers/dockervolumes.md
18:26:55 * link error: (in page engine/reference/commandline/volume_rm.md) ../../userguide/containers/dockervolumes.md
18:26:55 * link error: (in page engine/reference/commandline/volume_inspect.md) ../../userguide/containers/dockervolumes.md
18:26:55 * link error: (in page engine/reference/commandline/volume_ls.md) ../../userguide/containers/dockervolumes.md
18:26:55 * link error: (in page engine/reference/run.md) ../userguide/containers/dockervolumes.md
18:26:55 * link error: (in page engine/userguide/index.md) containers/dockervolumes.md
18:26:55 * link error: (in page engine/reference/commandline/volume_create.md) ../../userguide/containers/dockervolumes.md
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../networking/default_network/dockerlinks.md
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../../extend/plugins_volume.md
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../containers/dockerrepos.md
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../../extend/plugins.md
18:26:55 * link error: (in page engine/tutorials/dockerimages.md) ../eng-image/dockerfile_best-practices.md
18:26:55 * link error: (in page engine/reference/builder.md) ../userguide/containers/dockervolumes.md#mount-a-host-directory-as-a-data-volume
18:26:55 * link error: (in page engine/tutorials/dockerimages.md) ../../reference/builder.md
18:26:55 * link error: (in page engine/tutorials/usingdocker.md) ../../reference/commandline/cli.md
18:26:55 * link error: (in page engine/userguide/index.md) containers/dockerizing.md
18:26:55 * link error: (in page engine/userguide/intro.md) containers/dockerizing.md
18:26:55 * link error: (in page engine/examples/index.md) ../userguide/containers/dockerizing.md
18:26:55 * link error: (in page engine/tutorials/usingdocker.md) ../../reference/run.md
18:26:55 * link error: (in page engine/userguide/index.md) containers/dockerrepos.md
18:26:55 * link error: (in page engine/reference/builder.md) ../userguide/containers/dockerrepos.md
18:26:55 * link error: (in page engine/userguide/index.md) containers/networkingcontainers.md
18:26:55 * link error: (in page engine/userguide/intro.md) containers/networkingcontainers.md
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../../reference/commandline/run.md#mount-volumes-from-container-volumes-from
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../containers/usingdocker.md
18:26:55 * link error: (in page engine/reference/commandline/export.md) ../../userguide/containers/dockervolumes.md#backup-restore-or-migrate-data-volumes
18:26:55 * link error: (in page engine/reference/commandline/search.md) ../../userguide/containers/dockerrepos.md#searching-for-images
18:26:55 * link error: (in page engine/tutorials/usingdocker.md) ../../reference/commandline/run.md
18:26:55 * link error: (in page engine/tutorials/dockervolumes.md) ../../reference/glossary.md#union-file-system
18:26:55 * link error: (in page engine/userguide/index.md) containers/dockerimages.md
18:26:55 * link error: (in page engine/userguide/intro.md) containers/dockerimages.md
18:26:55 * link error: (in page engine/userguide/networking/default_network/dockerlinks.md) ../../containers/usingdocker.md
18:26:55 * link error: (in page engine/userguide/networking/default_network/dockerlinks.md) ../../containers/usingdocker.md
18:26:55 * link error: (in page engine/userguide/index.md) containers/usingdocker.md
18:26:55 * link error: (in page engine/userguide/intro.md) containers/usingdocker.md
18:26:55 * link error: (in page engine/reference/commandline/tag.md) ../../userguide/containers/dockerrepos.md#contributing-to-docker-hub
18:26:55 * link error: (in page engine/reference/builder.md) ../userguide/containers/dockerrepos.md#contributing-to-docker-hub
18:26:55 
```

**Comment by londoncalling** [comment]
@thaJeztah cool! I'll fix the links now, I expected that ;-)

**Comment by londoncalling** [comment]
@thaJeztah @SvenDowideit it looks like I fixed all link errors, but Dos build is still failing. Can someone give me another LGTM and let me know if it is okay to merge this?

**Comment by vdemeester** [comment]
```
22:40:11 ERROR: 2016/06/13 20:40:11 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockervolumes.md" on page "registry/deploying.md".
22:40:11 ERROR: 2016/06/13 20:40:11 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockerimages.md#building-an-image-from-a-dockerfile" on page "compose/gettingstarted.md".
22:40:11 ERROR: 2016/06/13 20:40:11 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockerimages.md#building-an-image-from-a-dockerfile" on page "compose/django.md".
22:40:11 ERROR: 2016/06/13 20:40:11 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockerimages.md#building-an-image-from-a-dockerfile" on page "compose/rails.md".
```

It looks like some documentation will need some update in `docker/compose` repository :stuck_out_tongue_closed_eyes:

**Comment by londoncalling** [comment]
@vdemeester thanks, I'll merge this and then update those docker/compose links

**Comment by londoncalling** [comment]
@SvenDowideit @thaJeztah please see also note in PR #23505

**Comment by SvenDowideit** [comment]
@londoncalling and one link in the docker/distribution repo :)

LGTM

**Comment by icecrime** [comment]
This PR seems to have broken the `documentation` CI job on `docker/docker`. That's the errors that I'm seeing on master:

```
ERROR: 2016/06/14 18:10:35 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockervolumes.md" on page "registry/deploying.md".
ERROR: 2016/06/14 18:10:35 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockerimages.md#building-an-image-from-a-dockerfile" on page "compose/gettingstarted.md".
ERROR: 2016/06/14 18:10:35 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockerimages.md#building-an-image-from-a-dockerfile" on page "compose/django.md".
ERROR: 2016/06/14 18:10:35 content_renderer.go:56: LinkResolver: No page found for "/engine/userguide/containers/dockerimages.md#building-an-image-from-a-dockerfile" on page "compose/rails.md".
```

Ping @SvenDowideit @londoncalling @thaJeztah!

**Comment by icecrime** [comment]
Ok so I read from the comments above that this was expected? Can you please let us know when we're supposed to ignore the `documentation` CI job?

**Comment by londoncalling** [comment]
@icecrime @sfsmithcha  this should fix it.

I’m re-organizing some tutorials for v1.12 docs—the bulk of the work is done, but I am working on one more that might break links again. I’m not sure how to handle this so that there is no gap in the builds working, because the links are across repos—I made changes to locations of files in `docker/docker/docs/engine/` then needed to update links targeting those files in `docker/compose` (just now done per https://github.com/docker/docker/pull/23492) and `docker/dtr`? (`registry/deploying.md` needs a fix) for which I don’t have permissions. Whichever changes got merged first would have broken the links. Any suggestions would be much appreciated. I’m still moving some files around in various repos.

**Comment by londoncalling** [comment]
@SvenDowideit @icecrime @sfsmithcha I don't have permissions to DTR, so still need to fix one link in `registry/deploying.md`

**Pull request merged**
