### PR TITLE
Windows: Fix scaling of NanoCPUs (--cpus) on Hyper-V containers

### PR DESCRIPTION
**Pull request by darstahl**
Signed-off-by: Darren Stahl <darst@microsoft.com>

**- What I did**

In current Docker versions, when calculating the result of setting NanoCPUs, it is assumed that all of the host's CPUs are available to the container. This assumption does not hold true for Hyper-V containers on Windows. Since Hyper-V containers are backed by Hyper-V technology, they require an explicit CPU count at creation.

This PR uses NanoCPUs to calculate the number of CPUs to expose to the container, as well as a percentage scaling to apply in order to reach the desired NanoCPUs target.

**- How I did it**

If NanoCPUs is set on a Hyper-V container, it is rounded up to the next whole CPUCount, and that many cores are enabled in the container. If the NanoCPUs value is not evenly divisible by 1000000000 (one whole CPU), a CPUPercent limit is applied to limit the available CPU resources to match the requested NanoCPUs.

Note that in current Windows releases, Hyper-V container CpuLimit (Percent) does not have the same effect on CPU resources as expected by NanoCPUs. This would result in odd scaling, so in current Windows releases NanoCPUs on Hyper-V containers is implemented with either CpuPercent or CpuCount, but not both (unless NanoCPUs is less than 1000000000). If the provided NanoCPUs value is being rounded, a warning will be provided to the user.

**- How to verify it**

Manual verification.

```
PS C:\Users\Administrator> docker run --rm --cpus 11.99 --isolation=hyperv microsoft/windowsservercore
WARNING: Your current OS version does not support Hyper-V containers with NanoCPUs greater than 1000000000 but not divisible by 1000000000, rounded to 12000000000
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>
```

| --cpus 	|   NanoCPUs  	| CpuCount 	| CpuPercent 	| NanoCPUs (Rounded) 	| CpuCount (Rounded) 	| CpuPercent (Rounded) 	|
|:------:	|:-----------:	|:--------:	|:----------:	|:------------------:	|:------------------:	|:--------------------:	|
|    0.5 	|   500000000 	|        1 	|         50 	|          500000000 	|                  1 	|                   50 	|
|      1 	|  1000000000 	|        1 	|          0 	|         1000000000 	|                  1 	|                    0 	|
|    1.1 	|  1100000000 	|        2 	|         55 	|         1000000000 	|                  1 	|                    0 	|
|    1.5 	|  1500000000 	|        2 	|         75 	|         2000000000 	|                  2 	|                    0 	|
|   11.9 	| 11900000000 	|       12 	|         99 	|        12000000000 	|                 12 	|                    0 	|

**- Description for the changelog**

Windows: Fix scaling of NanoCPUs (--cpus) on Hyper-V containers.

### CODE REVIEW

**Comment by darrenstahlmsft** [comment]
z failures are unrelated to this change

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by jhowardmsft** [comment]
LGTM. Restarted `z` but can't get it to pass. Merging as failure is unrelated.

**Pull request merged**
