### PR TITLE
Update to using alpine 3.10

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

**- What I did**
update to using alpine 3.10 https://alpinelinux.org/posts/Alpine-3.10.0-released.html

### CODE REVIEW

**Comment by tao12345666333** [comment]
```
03:47:13 To set a process to complain mode, use the command line tool
03:47:13 'aa-complain'. To really tear down all profiles, run the init script
03:47:13 with the 'teardown' option."
03:47:13 Removing test suite binaries
04:42:05 Build timed out (after 180 minutes). Marking the build as failed.
04:42:05 Build timed out (after 180 minutes). Marking the build as aborted.
04:42:05 Set build name.
04:42:05 New build name is '#39401'
04:42:05 Build was aborted
04:42:05 [PostBuildScript] - Executing post build scripts.
```

it seems to be timeout. can you please rebuild it? @thaJeztah  thank you. :heart:

**Comment by thaJeztah** [comment]
Interesting that Windows RS5 build worked here (but it failed on other PR's) (see https://github.com/moby/moby/pull/39403)

Information from that build;

https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/2808/consoleFull

That's on this node: https://jenkins.dockerproject.org/computer/azure-windows-rs5-2

```
17:42:46 INFO: Branch:rs5_release_svc_im Build:17763.437.190401-1813
17:42:46 INFO: Image microsoft/windowsservercore:latest is already loaded in the control daemon
17:42:46 INFO: Version of microsoft/windowsservercore:latest is '10.0.17763.437'
```

**Comment by thaJeztah** [comment]
A bit of a nit, but I see there's a typo in your PR's commit message (`alphine` instead of `alpine`); could you perhaps amend your commit and fix that (then CI will also be triggered again)

**Comment by tao12345666333** [comment]
thanks. I will fix the typo ASAP.

**Comment by tao12345666333** [comment]
These failed CI jobs need rebuild.

**Comment by thaJeztah** [comment]
kicked CI to run again

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by tao12345666333** [comment]
thank you. :heart:

**Comment by tao12345666333** [comment]
`windowsRS5-process` `windowsRS1` and `janky` has failed. we need rebuild again.

**Comment by tao12345666333** [comment]
Need rebuild windowsRS5-process job. Thanks.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
