### PR TITLE
Vendor docker/engine-api

### PR DESCRIPTION
**Pull request by WeiZhang555**
Vendor docker/engine-api 9bab0d5b73872e53dfadfa055dcc519e57b09439

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
looks like userns had connection issues, not related;
```
07:59:24 E: Failed to fetch http://httpredir.debian.org/debian/pool/main/p/python3-defaults/python3-minimal_3.4.2-2_amd64.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]
07:59:24 
07:59:24 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
07:59:24 Fetched 222 MB in 21s (10.4 MB/s)
```

**Comment by thaJeztah** [comment]
Relates to https://github.com/docker/docker/pull/20848 and https://github.com/docker/docker/pull/20970

**Comment by estesp** [comment]
LGTM

**Comment by tonyhb** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
