### PR TITLE
Move long compilations before Go install in Dockerfile

### PR DESCRIPTION
**Pull request by LK4D4**
Now we can avoid long compilations on Go update.

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by tiborvass** [comment]
how about we keep this for when we need to actually bust the cache?

**Comment by LK4D4** [comment]
@tiborvass No problem, just we need to not forget about it. Because I sorta tried to ask for this in two-three previous cache busts.

**Comment by tianon** [comment]
Why not just bust it?  Is a cache bust really such a huge deal that it's
worth deferring positives changes?  On my systems (even the slow ones) it
doesn't take all that long to get fresh cache again.

**Comment by tiborvass** [comment]
fine LGTM

**Comment by tianon** [comment]
:heart:

**Comment by unclejack** [comment]
Please wait, I've got one PR to send after integration-cli finishes running. That's also a cache bust.

**Comment by unclejack** [comment]
The other PR won't be needing changes to the Dockerfiles. Please feel free to merge.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
