### PR TITLE
fix default component checking

### PR DESCRIPTION
**Pull request by jessfraz**
this was never working before, i realized because http://apt.dockerproject.org/repo/conf/apt-ftparchive.conf only has testing listed in Sections it should have all 3

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @tiborvass

**Comment by mlaventure** [comment]
strange, both syntax should yield the same result.

**Comment by tiborvass** [comment]
@jfrazelle apt-ftparchive.conf is updated with whatever i need to update. So when i was uploading rcs, I removed the apt-ftparchive.conf and regenerated one from release-deb. This ensures that the apt scripts won't touch anything else but `testing`. If you look now, it should only have `main`. IOW, we could also just remove the entire file at the end of the release-deb script and never upload it, (and delete it from s3).

**Comment by jfrazelle** [comment]
yeah im going to close seems to be all good currently was just worried :)

**Pull request closed without merging**
