### PR TITLE
Remove packaging scripts

### PR DESCRIPTION
**Pull request by dnephin**
Part of #35115

These scripts have not been used for a while now, and should not be used again
because they are for releasing docker, not moby.

There is some packaging config in `contrib/` as well, but they are not removed as part of this PR.

cc @seemethere @andrewhsu to confirm

### CODE REVIEW

**Comment by dnephin** [comment]
Hmm, there is also a `hack/release.sh` that might not be used anymore

**Comment by seemethere** [comment]
@dnephin can confirm `hack/release.sh` is not used by us anymore

**Comment by dnephin** [comment]
Thanks, I've removed it as well

**Comment by thaJeztah** [comment]
In case it's useful; this is a branch I worked on a long time ago to remove all the build stuff https://github.com/moby/moby/compare/master...thaJeztah:remove-packaging-scripts

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Review by andrewhsu — APPROVED** [review]
LGTM

the packaging scripts are dead
long live [the packaging scripts](https://github.com/docker/docker-ce-packaging)

**Comment by andrewhsu** [comment]
Oh yeah, plenty more stuff in the `contrib` directory that could be removed as shown in @thaJeztah  branch https://github.com/moby/moby/compare/master...thaJeztah:remove-packaging-scripts

Can be a separate PR.

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
@andrewhsu yup, just discussed with @dnephin out of band; and agreed that we can clean that up in a follow up

**Pull request merged**
