### PR TITLE
17.03 bash/zsh completion script cherry-picks

### PR DESCRIPTION
**Pull request by thaJeztah**
cherry-picks of bash/zsh completion scripts for 17.03;

https://github.com/docker/docker/pull/30823 (c9fa3eed1b38cc3056107ab2d1572f829a513062)
https://github.com/docker/docker/pull/30939 (5d47cb901b90953e8e85bac4b66ff8fb0af04d07)
https://github.com/docker/docker/pull/30940 (27ab0086263986033bde45d0c48423408cd653ea)
https://github.com/docker/docker/pull/30941 (03db46362e5d913d5162e255ea5cff3d1fa73266)
https://github.com/docker/docker/pull/30943 (4f6e4bfd0259331a840cdf06157389fce24f9457)
https://github.com/docker/docker/pull/30944 (0d9bb4ee125d5051a1db9d8afa0dc03d81d840a9)
https://github.com/docker/docker/pull/30945 (da9a162301e36b7aa9a4925657f8c28121b11125)

PTAL @sdurrheimer @albers @vdemeester @vieux

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by albers** [comment]
@thaJeztah bash completion successfully verified, thanks for the ping.

**Comment by thaJeztah** [comment]
Thanks for checking @albers!

**Comment by vieux** [comment]
LGTM

**Pull request merged**
