### PR TITLE
replace canonical json package 

### PR DESCRIPTION
**Pull request by jessfraz**
replace weird canonical json package with one that is rebased
on the standard encoding/json package.

ping @tiborvass @diogomonica @endophage @icecrime

### CODE REVIEW

**Comment by jfrazelle** [comment]
also ping @tianon

**Comment by endophage** [comment]
Looks like this is also vendoring the latest updates from gotuf and notary, which is great, they're just minor bugfixes and error handling improvements.

LGTM!

**Comment by calavera** [comment]
This is also vendoring `vendor/src/github.com/docker/libnetwork/osl/test_linux.go` :pensive: 

docker/libnetwork#499 cannot come soon enough.

**Comment by jfrazelle** [comment]
updated

**Comment by tianon** [comment]
Nice, LGTM :+1:

**Comment by calavera** [comment]
LGTM

**Pull request merged**
