### PR TITLE
testing: update docker-py 4.4.1

### PR DESCRIPTION
**Pull request by thaJeztah**
run docker-py integration tests of the latest release;

full diff: https://github.com/docker/docker-py/compare/4.3.0...4.4.1

### CODE REVIEW

**Review by tianon — APPROVED** [review]
(Assuming the tests pass,) LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
failure may be legit (or a flaky test); https://ci-next.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-41709/runs/1/nodes/300/log/?start=0

```
=================================== FAILURES ===================================
________________________ ImageTest.test_tag_and_remove _________________________
tests/integration/models_images_test.py:158: in test_tag_and_remove
    assert image.id not in get_ids(client.images.list(repo))
E   AssertionError: assert 'sha256:d6e46aa2470df1d32034c6707c8041158b652f38d2a9ae3d7ad7e7532d22ebe0' not in ['sha256:c4e0b3d4be6108027ea0b773965e0f4dcc647fd703848a065d16f5d292e06d7c', 'sha256:c8560002686bac463723769f38c597d648...041158b652f38d2a9ae3d7ad7e7532d22ebe0', 'sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f', ...]
E    +  where 'sha256:d6e46aa2470df1d32034c6707c8041158b652f38d2a9ae3d7ad7e7532d22ebe0' = <Image: 'alpine:latest'>.id
E    +  and   ['sha256:c4e0b3d4be6108027ea0b773965e0f4dcc647fd703848a065d16f5d292e06d7c', 'sha256:c8560002686bac463723769f38c597d648...041158b652f38d2a9ae3d7ad7e7532d22ebe0', 'sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f', ...] = get_ids([<Image: 'dup-txt-tag:latest'>, <Image: 'some-tag:latest'>, <Image: ''>, <Image: 'docker-sdk-python3:4.4.0'>, <Image: 'alpine:latest'>, <Image: 'busybox:latest'>, ...])
E    +    where [<Image: 'dup-txt-tag:latest'>, <Image: 'some-tag:latest'>, <Image: ''>, <Image: 'docker-sdk-python3:4.4.0'>, <Image: 'alpine:latest'>, <Image: 'busybox:latest'>, ...] = <bound method ImageCollection.list of <docker.models.images.ImageCollection object at 0x7fb989723210>>('dockersdk.tests.images.test_tag')
E    +      where <bound method ImageCollection.list of <docker.models.images.ImageCollection object at 0x7fb989723210>> = <docker.models.images.ImageCollection object at 0x7fb989723210>.list
E    +        where <docker.models.images.ImageCollection object at 0x7fb989723210> = <docker.client.DockerClient object at 0x7fb9895e9150>.images
------- generated xml file: /src/bundles/test-docker-py/junit-report.xml -------
```

**Comment by thaJeztah** [comment]
Ok, looks like `docker-py` is making use of the deprecated `filter` query-arg; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/server/router/image/image_routes.go#L234-L240

https://github.com/docker/docker-py/blob/4.4.0/docker/api/image.py#L83-L90

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker-py/pull/2708 to fix docker-py

**Comment by thaJeztah** [comment]
updated to 4.4.1, which includes my fix for the above (https://github.com/docker/docker-py/pull/2708); https://github.com/docker/docker-py/compare/4.4.0...4.4.1

**Comment by thaJeztah** [comment]
docker-py is green now 🎉. s390x failure is unrelated (see https://github.com/moby/moby/issues/41933)

Screenshot 2021-01-26 at 12 34 59

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
