### PR TITLE
[Carry 14389] Ensure images downloaded by pullTagV2 are always cleaned up

### PR DESCRIPTION
**Pull request by calavera**
Previously, if only some of the downloads succeed, we would not close and delete the file handles. This does change the behavior of the registration to block on all downloads completing (whereas previously it would exit early after the first failure), which is necessary to ensure cleanup is only performed after the download portion has completed.

(We could also refactor the download function to take a signal when the registration has completed so it could wait and then clean itself up, but this would be a bit more involved.)

### CODE REVIEW

**Comment by vdemeester** [comment]
@calavera there is a compilation error : "graph/pull_v2.go:326: downloads[i].verified undefined (type downloadInfo has no field or method verified)" (https://github.com/docker/docker/pull/15414/files#diff-7e2a216082b6bd557c7ecebd68305e2eR326) :blush:

**Comment by calavera** [comment]
Fixed, thanks @vdemeester !

**Comment by icecrime** [comment]
```
FAIL: docker_cli_by_digest_test.go:460: DockerRegistrySuite.TestPullFailsWithAlteredLayer

docker_cli_by_digest_test.go:497:
    c.Fatalf("expected error message %q in output: %s", expectedErrorMsg, out)
... Error: expected error message "filesystem layer verification failed for digest sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" in output: sha256:8fd4d1376a1390b236db785755903a29839f4f7dd5440140dd0b6d806326cd7c: Pulling from dockercli/busybox-by-dgst
ca1780a6b6bf: Pulling fs layer
cf2616975b4a: Already exists
6ce2e90b0bc7: Already exists
8c2e06607696: Already exists
ca1780a6b6bf: Verifying Checksum
could not find image: no such id: ca1780a6b6bfe97d63e4cfca0ee7a0785629ddbf35645e39268efba54da964a5
```

**Comment by jlhawn** [comment]
@calavera I think the tempfile cleanup has been taken care of by @LK4D4's PR: https://github.com/docker/docker/pull/15545/files#diff-7e2a216082b6bd557c7ecebd68305e2eR278

Is it now okay to close this one?

**Comment by calavera** [comment]
@jlhawn sure, thanks for letting me know. Closing.

**Pull request closed without merging**
