### PR TITLE
Update curators list

### PR DESCRIPTION
**Pull request by thaJeztah**
Noticed @ripcurld changed his handle :smile:, also removed some old curators from the list

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL as well 👍

**Comment by arm64b** [comment]
please help to rebuild `experimental` node of PR #36604 😄

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
@arm64b restarted that build

**Comment by thaJeztah** [comment]
author LGTM - CI isn't testing this, so merging :smile:

**Comment by ripcurld** [comment]
@thaJeztah that's really nice of you :hugs: :smiley: 
LGTM although it's too late :wink:

**Comment by thaJeztah** [comment]
👍 thanks!

**Pull request merged**
