### PR TITLE
Fix issues of multiple published ports mapping to the same target port

### LINKED ISSUE #29730: [1.13.x] same container port published twice prevent service to run
This might be a known issue but I really think it's a weird one to have. If I publish the same container port on 2 ingress port, the service does not return any error and will never be scheduled — and it's really hard to know why without looking at the daemon logs.

```bash
$ docker service create --name never --publish 5000:80 --publish 5001:80 nginx:alpine
tjbepmsn4nvwevu2xuijfg6k9
$ docker service ls
ID            NAME   MODE        REPLICAS  IMAGE
tjbepmsn4nvw  never  replicated  0/1       nginx:alpine
$ docker service ps never
ID            NAME     IMAGE         NODE  DESIRED STATE  CURRENT STATE      ERROR  PORTS
qem9gxvaldy9  never.1  nginx:alpine        Running        New 2 minutes ago 
# Extract from the logs
ERRO[1550] task allocation failure                       error="service tjbepmsn4nvwevu2xuijfg6k9 to which this task qem9gxvaldy9bpbdtzhn6ornr belongs has pending alloc
ations"
ERRO[1550] task allocation failure                       error="service tjbepmsn4nvwevu2xuijfg6k9 to which this task qem9gxvaldy9bpbdtzhn6ornr belongs has pending alloc
ations"
```

Note that this is entirely possible using `docker run` : 

```
$ docker run -d --publish 5000:80 --publish 5001:80 nginx:alpine
# […]
d8381762d8a1
```

/cc @aaronlehmann @thaJeztah @stevvooe @mavenugo @icecrime @cpuguy83

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to address the issue raised in #29730 where a service with multiple published ports mapping to the same target port (e.g., `--publish 5000:80 --publish 5001:80`) can't be allocated.

The reason for the issue is that, `getPortConfigKey` is used for both allocated ports and configured (may or may not be allocated) ports. However, `getPortConfigKey` will not take into consideration the `PublishedPort` field, which actually could be different for different allocated ports.

This fix saves a map of `portKey:portNum:portState`,  instead of currently used `portKey:portState` so that multiple published ports could be processed.

An integration test has been added to address https://github.com/docker/swarmkit/pull/1835#issuecomment-269458665

See https://github.com/docker/swarmkit/pull/1835 for changes in SwarmKit.

This fix fixes #29730 

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
Updated the PR to vendor c97146840a26c9ce8023284d0e9c989586cc1857.

/cc @aaronlehmann @thaJeztah @aboch Please take a look.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by thaJeztah** [comment]
cherry-picked through https://github.com/docker/docker/pull/31143

**Pull request merged**
