### PR TITLE
Do not call out to Google on init

### PR DESCRIPTION
**Pull request by cpuguy83**
The GCP logging driver is calling out to GCP cloud service on package
init.
This is regardless if you are using GCP logging or not.

This change makes this happen on the first invocation of a new GCP
logging driver instance instead.

Signed-off-by: Brian Goff cpuguy83@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
This was introduced by #18766
ping @mikedanese

**Comment by tiborvass** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by mikedanese** [comment]
lgtm thanks!

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
