### PR TITLE
Uprev google/certificate-transparency to include Solaris support

### PR DESCRIPTION
**Pull request by amitkris**
This is a dependency for #23397.

Signed-off-by: Amit Krishnan krish.amit@gmail.com

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by justincormack — APPROVED** [review]

**Comment by thaJeztah** [comment]
All green, merging

**Comment by amitkris** [comment]
thanks @thaJeztah @vdemeester !

**Pull request merged**
