### PR TITLE
fix containerd restart problem

### PR DESCRIPTION
**Pull request by x1022as**
docker restart containerd without waiting for it to be ready.
500ms is not enough for containerd to start. so docker will try
to kill and restart containerd every 500ms, which will result in
many problems, such as event missing.

kill shim progress while containerd is down, you will see container
status is up even after containerd recover. digging the log, will see
the event missing because of killing and restarting containerd too many
times.

this pr will wait 15s for containerd to be ready

Signed-off-by: Deng Guangxing <dengguangxing@huawei.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by x1022as** [comment]
On host with heavy load, containerd restart may take several seconds(maybe 10+), in such case docker will try to kill and start containerd for many times, which will cause problems.

one problem I come across is missing event.  kill containerd-shim progress when containerd is down, after several trials of killing and restarting containerd, the exit event of container has been lost, and when containerd is up again, docker ps shows that container is still up, and docker rm will error out with shm busy.

I figure out an easy way to reproduce this:

1. start a containerd: `docker run -tid busybox sleep 1000`

2. kill containerd and remove the binary: `kill -9  $pid_of_containerd && mv /usr/bin/docker-containerd{,.bak}`

3. kill containerd-shim progress: `kill -9 $pid_of_container_shim `

4. recover containerd binary and wait for it to be ready: `mv /usr/bin/docker-containerd{.bak,}`

5. docker ps to get container status and docker rm to delete it

**Comment by tonistiigi** [comment]
cc @mlaventure

**Comment by mlaventure** [comment]
Which version of docker are you running?

We changed the `containerd` code to have the `healthcheck` service being the first thing registered, that should effectively fix the issue I think.

**Comment by x1022as** [comment]
@mlaventure  I am using 1.11, but have tried with docker master, this error still occurs.

it is supposed to be reproduced with steps mentioned above

**Comment by mlaventure** [comment]
@x1022as Hum, I see, normally `containerd` should get about 10secs to restart with the 3 tries, but we forgot to disable `FailFast` on the check call.

modify `_, err := healthClient.Check(ctx, &grpc_health_v1.HealthCheckRequest{})` to be `_, err := healthClient.Check(ctx, &grpc_health_v1.HealthCheckRequest{}, grpc.FailFast(false))`

To have the same effect as your change (albeit with a smaller timeout of 9s)

Note that docker still recovers for me on master without that change, it just takes a bit longer than expected.

**Comment by x1022as** [comment]
@mlaventure 
> Note that docker still recovers for me on master without that change, it just takes a bit longer than expected

I tried on master, the problem exist,  I killed containerd-shim while containerd is down, after containerd recoverd, docker will try to start and kill containerd for many times, during which the events is missing:
```
INFO[0098] libcontainerd: new containerd process, pid: 5985 
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0000] containerd: read past events                  count=1
WARN[0000] containerd: 8002ac22b2cfe702e0e83ae8ba55046025561581939c781f545971cb85512571:init shim died, killing associated process 
ERRO[0000] containerd: notify OOM events                 error="open /proc/5946/cgroup: no such file or directory"
DEBU[0000] containerd: container restored                id=8002ac22b2cfe702e0e83ae8ba55046025561581939c781f545971cb85512571
DEBU[0000] containerd: supervisor running                cpus=4 memory=3622 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
WARN[0000] containerd: 8002ac22b2cfe702e0e83ae8ba55046025561581939c781f545971cb85512571:init (pid 5946) does not exist 
DEBU[0000] containerd: process exited                    id=8002ac22b2cfe702e0e83ae8ba55046025561581939c781f545971cb85512571 pid=init status=255 systemPid=5946
DEBU[0098] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
DEBU[0099] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
DEBU[0099] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
INFO[0099] libcontainerd: new containerd process, pid: 6000 
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0000] containerd: read past events                  count=1
DEBU[0000] containerd: supervisor running                cpus=4 memory=3622 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
DEBU[0100] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
DEBU[0100] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
DEBU[0101] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
INFO[0101] libcontainerd: new containerd process, pid: 6009 
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=3622 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
DEBU[0101] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
DEBU[0102] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
DEBU[0102] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable 
INFO[0102] libcontainerd: new containerd process, pid: 6018 
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0000] containerd: read past events                  count=0
```
from 1 to 0.

when containerd is ready again, docker ps shows container is still up(it should not be, because shim has been killed), containerd got the exited event, and tried to send to dockerd, somehow it's missed.

`_, err := healthClient.Check(ctx, &grpc_health_v1.HealthCheckRequest{}, grpc.FailFast(false))` is really a nice way, but I am not sure whether 9s is enough( not sure if 15s is enough either :( ) when host is suffering heavy workload. under such condition, the heathcheck would occasionally fail even containerd is up.

**Comment by cpuguy83** [comment]
What's the status here?

**Comment by x1022as** [comment]
This problem has multiple reasons, this is not a proper solution.

grpc connection has retrying penalty up to 120s by default, if containerd has been down for a long time,  interval between two grpc reconnection tial will be 120s, this is long enough to start and kill containerd for many times( during which health check would fail due to lost connection). this is solved by https://github.com/moby/moby/pull/33483

and containerd open event logger file with trunc flag, this would result in event missing after continuous restart.

**Pull request closed without merging**
