### PR TITLE
Update hcsshim to v0.5.2

### PR DESCRIPTION
**Pull request by darstahl**
Update hcsshim to v0.5.2. This version includes a temporary workaround for some cases of the timeouts reported in https://github.com/docker/docker/issues/27588 (unfortunately I don't think it will fix the issue as reported, just a set of similar issues).

@msabansal This also includes some of your changes.

Signed-off-by: Darren Stahl darst@microsoft.com

/cc @jhowardmsft @jstarks

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by jhowardmsft** [comment]
LGTM if green.

**Comment by darrenstahlmsft** [comment]
All green 👍

**Comment by jhowardmsft** [comment]
Merging

**Pull request merged**
