### PR TITLE
Update Dockerfile.armhf

### PR DESCRIPTION
**Pull request by icecrime**
**\- What I did**
Bump ARM build to Go 1.6 and update some dependencies accordingly.

**\- How I did it**
Mostly with `vi`.

**\- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by icecrime** [comment]
BTW, without this PR the build is broken by the latest notary vendoring (which adopted the new `vendor/` directory layout, incompatible with Go 1.4).

**Comment by tonistiigi** [comment]
LGTM

**Comment by kencochrane** [comment]
:+1:

**Comment by vdemeester** [comment]
LGTM 🐰
@icecrime what a cute animal it is :D

**Pull request merged**
