### PR TITLE
Remove solaris files

### PR DESCRIPTION
**Pull request by crosbymichael**
For obvious reasons that it is not really supported now.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM assuming CI is happy.

**Review by thaJeztah — CHANGES_REQUESTED** [review]
There's a couple of other places that reference solaris, e.g. https://github.com/moby/moby/blob/master/cmd/dockerd/config_unix.go#L1

Also see https://github.com/moby/moby/pull/33187/files

**Comment by crosbymichael** [comment]
@thaJeztah updated

**Review by thaJeztah — APPROVED** [review]
couple of build tags are still there, but discussed out of band, and we can remove those later if we want to

LGTM

**Comment by vieux** [comment]
LGTM 👍

**Pull request merged**
