### PR TITLE
Remove reference to old Volumes field in inspect struct.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM. Was hitting TestRunCreateVolumeWithSymlink failing on master from a Windows CLI. Verified it passed with this fix.

**Comment by tiborvass** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by tiborvass** [comment]
It seems to have fixed the issue on windows. thanks @calavera ! Just 1 failure left :)

**Pull request merged**
