### PR TITLE
Vendor in libnetwork v0.6.0-rc2

### PR DESCRIPTION
**Pull request by sanimej**
Fixes docker/docker#19376
Fixes docker/docker#15819
Fixes docker/libnetwork#885, 
Fixes docker/docker#19448
Fixes docker/docker#19403

IT for service, network name with '.'

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Added impact/changelog because https://github.com/docker/docker/issues/15819 is now supported

**Pull request merged**
