### PR TITLE
bash completion for `docker daemon --authz-plugin`

### PR DESCRIPTION
**Pull request by albers**
Ref #15365
Thanks @jfrazelle!
@thaJeztah I assume that there is no way to figure out the available plugins yet, do completion will accept any value. Maybe the installed plugins could be included in output of `docker info`?

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh, just as with the other plugins, that'd make sense yes (I think we did that, right?)

**Comment by vdemeester** [comment]
LGTM 🐭
The completion for available plugins might be done in another PR (when/if we display them into docker info :wink: ).

**Comment by calavera** [comment]
I agree with @vdemeester. We can do that in a new PR.

LGTM

**Comment by thaJeztah** [comment]
Don't think we need to run CI here, merging :smile: thanks @albers!

**Pull request merged**
