### PR TITLE
Use go-systemd const instead of magic string in Linux version of dockerd

### PR DESCRIPTION
**Pull request by muesli**
**- What I did**

We currently use a magic string `READY=1` to indicate readiness of dockerd to systemd.
`go-systemd` `v17` provides a const we can use, so we can drop the magic string (which is a rather protocol-specific detail).

**- How I did it**

Bumped moby's `go-systemd` dependency to `v17`.

**- Description for the changelog**
```
Use go-systemd const instead of magic string in Linux version of dockerd
```

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

const is defined here: https://github.com/coreos/go-systemd/blob/master/daemon/sdnotify.go#L32

**Comment by cpuguy83** [comment]
Some issues:

```
17:14:26 daemon/listeners/listeners_linux.go:65:43: too many arguments in call to activation.TLSListeners
17:14:26 	have (bool, *tls.Config)
17:14:26 	want (*tls.Config)
17:14:26 daemon/listeners/listeners_linux.go:67:40: too many arguments in call to activation.Listeners
17:14:26 	have (bool)
17:14:26 	want ()
```

**Comment by muesli** [comment]
@cpuguy83 Thanks, didn't realize there's another go-systemd dependency in the codebase. Sorry for not catching that earlier. Looking into it now.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
hm; flaky test?

```
21:06:58 FAIL: docker_api_swarm_service_test.go:96: DockerSwarmSuite.TestAPISwarmServicesMultipleAgents
21:06:58 
21:06:58 [ddd056703fcaf] waiting for daemon to start
21:06:58 [ddd056703fcaf] daemon started
21:06:58 
21:06:58 [d9e6dc28e8bae] waiting for daemon to start
21:06:58 [d9e6dc28e8bae] daemon started
21:06:58 
21:06:58 [d67c17c766c05] waiting for daemon to start
21:06:58 [d67c17c766c05] daemon started
21:06:58 
21:06:58 [d9e6dc28e8bae] exiting daemon
21:06:58 docker_api_swarm_service_test.go:120:
21:06:58     waitAndAssert(c, defaultReconciliationTimeout, reducedCheck(sumAsIntegers, d1.CheckActiveContainerCount, d3.CheckActiveContainerCount), checker.Equals, instances)
21:06:58 docker_utils_test.go:435:
21:06:58     c.Assert(v, checker, args...)
21:06:58 ... obtained int = 6
21:06:58 ... expected int = 5
21:06:58 ... output: "a97a3534f14d\ne6244d701dd8\nccfac0029e7d\n", output: "f3856c2340a9\n12cd5f5eba25\n2166040ea6ef\n"
21:06:58 
21:06:58 [ddd056703fcaf] exiting daemon
21:06:58 [d67c17c766c05] exiting daemon
```

**Review by vdemeester — APPROVED** [review]
LGTM :lion:

**Comment by thaJeztah** [comment]
All green; ignoring codecov

**Pull request merged**
