### PR TITLE
vendor: update containerd to 63522d9

### PR DESCRIPTION
**Pull request by tonistiigi**
update to match buildkit

full diffs:

- https://github.com/containerd/containerd/compare/c7083eed5d8633d54c25fe81aa609010a4f2e495...63522d9eaa5a0443d225642c4b6f4f5fdedf932b
- https://github.com/containerd/console/compare/cb7008ab3d8359b78c5f464cb7cf160107ad5925...9290d21dc56074581f619579c43d970b4514bc08

@thaJeztah @dmcgowan @AkihiroSuda 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
hmf; vendor is failing;

```
01:27:11 The result of vndr differs
01:27:11 
01:27:11  D vendor/github.com/containerd/containerd/contrib/README.md
01:27:11  D vendor/github.com/containerd/containerd/docs/README.md
01:27:11 
01:27:11 Please vendor your package with github.com/LK4D4/vndr.
```

**Review by tiborvass — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by tiborvass** [comment]
This does not affect windows whatsoever.

**Pull request merged**
