### PR TITLE
Removed deprecated -d flag from docs

### LINKED ISSUE #15909: -d flag referenced in docs where daemon is used in the accompanying example
In https://docs.docker.com/project/set-up-dev-env/ (Start a container and run a test, part 8)

The command line example has been updated to use `daemon` rather than `-d`:

>`root@5f8630b873fe:/go/src/github.com/docker/docker#  docker daemon -D`

But the following explanation still refers to `-dD`, which was previously there

> The -dD flag starts the daemon in debug mode. You’ll find this useful when debugging your code.

### PR DESCRIPTION
**Pull request by lyndaoleary**
Hi, 
This addresses #15909 :)

fixes #15909

### CODE REVIEW

**Comment by lyndaoleary** [comment]
Sorry @GordonTheTurtle, I forgot oops :laughing:

**Comment by thaJeztah** [comment]
LGTM, thanks again Lynda!

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by thaJeztah** [comment]
Oh, I edited your top comment, and added `fixes #15909`, so that GitHub will automatically close the linked issue if this is merged. There are some forms you can use but (I checked, to be sure), "addresses ..." isn't in the list. You can find what you *can* use here; https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
