### PR TITLE
Remove push by ID

### PR DESCRIPTION
**Pull request by dmcgowan**
Pushing by image ID is not allowed in the Docker CLI and not supported by the registry. An unnamed image also cannot be pushed to a private registry, since no endpoint is specified and it will default to the hub. The hub also does not support this use case, therefore removing the code path is the best solution.

The ability to push a layer without a name is not allowed by the v2 registry.

Ping @dmp42 please verify this is not a supported feature by the Hub registry

### CODE REVIEW

**Comment by jfrazelle** [comment]
oooo the `-` is > `+` me likeeeyyyy

**Comment by dmp42** [comment]
LGTM

**Comment by stevvooe** [comment]
Note that we're not completely removing this functionality for v2. It will be reintroduced but securely in the future.

Please check out docker/distribution#46 for some details. @ncdc also has a proposal floating around for a cli syntax to support the immutable references.

**Comment by dmcgowan** [comment]
@stevvooe woudl this functionality include being able to push without any name associated with the layer?  This specific case would be forced to use the random identifier as the image name, which is completely meaningless.

**Comment by stevvooe** [comment]
@dmcgowan No, it requires an image name to proceed. I just wanted to clarify that we are not removing something without replacing it with better, more-secure functionality.

Some of this may be out of date, after the current discussions, but here is the basic plan:

https://github.com/docker/docker-registry/issues/804#issuecomment-68390604

**Comment by jfrazelle** [comment]
LGTM

**Comment by ncdc** [comment]
@stevvooe are you planning to support push by tag + digest, to push a specific manifest/digest combination?

**Comment by dmp42** [comment]
@ncdc let's keep these (interesting) discussions out of here - it does muddy things :)
This here is about removing dead code.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
