### PR TITLE
libnetwork/iptables: deprecate Passthrough

### PR DESCRIPTION
**Pull request by thaJeztah**
**- Description for the changelog**

```markdown changelog
libnetwork/iptables: deprecate Passthrough. This function was only used internally, and will be removed in the next release.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by akerouanton** [comment]
We consider libnetwork as an internal subsystem despite not being under internal/. Should we really mention that change in the changelog?

**Comment by thaJeztah** [comment]
I think I found some network-plugins importing this package, so it's mostly a precaution. We can decide to only mention these on GitHub release-notes, and no in the release-notes on docs.docker.com

**Review by vvoland — APPROVED** [review]

**Comment by vvoland** [comment]
(But personally, I wouldn't mind just ripping it out without deprecation notice either)

**Comment by thaJeztah** [comment]
Yeah, I think in most cases, people using things inside `libnetwork/` would have a hard time. That said; separation is a bit fuzzy as there are parts that are used, e.g. BuildKit depending on the resolvconf code; https://github.com/moby/buildkit/tree/4ea0679ee36557dd1249ec5b6cd3c88f39d81464/vendor/github.com/docker/docker/libnetwork

We should look at making the separation clearer. I could backport it to 27.x, then rip it out in master I guess

**Review by akerouanton — APPROVED** [review]

**Comment by thaJeztah** [comment]
I opened this PR for consideration; with that (and the plan to do a v27.5.0), I think we can remove both from master after that;

- https://github.com/moby/moby/pull/49119

**Pull request merged**
