### PR TITLE
20160606 docs cherry picks

### PR DESCRIPTION
**Pull request by thaJeztah**
docs cherry picks of these PR's

https://github.com/docker/docker/pull/22763 (9be8f04950f918b91e3d4166597e9e2eee74fbd6)
https://github.com/docker/docker/pull/23060 (068d466cc7cd4ef3915b983b61e9cd029936ac90)
https://github.com/docker/docker/pull/23106 (ef42e2f214dd528e3520d394d2d648de92f703cd)
https://github.com/docker/docker/pull/23143 (74c7363965625848c32a5af80526fb65ecb26064)
https://github.com/docker/docker/pull/23165 (8d75709f90ba9926d41cd7b91bb316e336af8f8c)
https://github.com/docker/docker/pull/23179 (09033b8df223c3d3ea1fc97bc86cd6f23e1cdfc3)
https://github.com/docker/docker/pull/23192 (e2528712db8b904de0ae7c076a3ddcf163a2734d)
https://github.com/docker/docker/pull/23193 (98c245c9e63793cf8ca03c5500e0820447c1861c)
https://github.com/docker/docker/pull/23251 (da703f026e0793e4caf349487f63a7c1ab09d1c3)
https://github.com/docker/docker/pull/23282 (cfcb470aad367dea7b9f6df96ff12f577a22a2b0)
https://github.com/docker/docker/pull/23293 (ac14aa11b6f9172c744affa9823d05fde721c5e0)

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @SvenDowideit ptal :heart:

**Comment by thaJeztah** [comment]
@vdemeester ptal :smile:

**Comment by thaJeztah** [comment]
retest this please

**Comment by SvenDowideit** [comment]
argh! 

```
20:21:46 ERROR: 2016/06/07 20:21:46 content_renderer.go:56: LinkResolver: No page found for "/engine/reference/commandline/dockerd.md#daemon-storage-driver-option" on page "machine/reference/create.md".
```

@thaJeztah can  you add a new commit to this PR, in which you add an `aliases` entry to the `daemon.md` file to link to `dockerd.md` - I think that'll make it work

**Comment by thaJeztah** [comment]
retest this please

**Comment by SvenDowideit** [comment]
actually, LGTM - this error is because the checker is too dumb to know to use the docs branch in machine.

**Comment by thaJeztah** [comment]
Thanks Sven!

**Pull request merged**
