### PR TITLE
Fix race with host networking causing `invalid argument` errors

### LINKED ISSUE #17577: [1.9.0-rc4] Containers failing randomly with `[8] System error: invalid argument`
The bug looks similar to #17527 and, in fact, is the new behaviour after #17527 has been patched, but sure is not its duplicate. 

I tried to narrow it down a little and here's what I've found. There are a few potential places in the code where this error could be thrown: usages of `libcontainer.SystemError`, all of them are in `vendor/src/github.com/opencontainers/runc/libcontainer/factory_linux.go`. The error is triggered by trying to run concurrent `--net=host` containers. If you run the repro script w/o `--net=host`, the issue goes away. 

Repro: the easiest is to run the following in the docker development container (the one built by `make binary`): 
```
# for i in {1..20}; do (docker run --net=host tianon/true&);done
```
which gives:
```
invalid argument
invalid argument
Error response from daemon: Cannot start container b3371732a3620966ace7d003a3f5b41e51ab110547221c0e211427079047de57: [8] System error: invalid argument
invalid argument
invalid argument
invalid argument
invalid argument
invalid argument
invalid argument
invalid argument
invalid argument
Error response from daemon: Cannot start container 1f0e719676d4f9419c672e46d00eb36e4398862f32c38f256d153a89676d904f: [8] System error: invalid argument
invalid argument
invalid argument
invalid argument
invalid argument
Error response from daemon: Cannot start container cbf72cf664dc100556516c137dd9a41b6061d1aeb76d894e835a9e1149a06055: [8] System error: invalid argument
Error response from daemon: Cannot start container a240f40aaa63963a6552c9db44a8c1534e683f33c569cb602ac3abd06175d701: [8] System error: invalid argument
Error response from daemon: Cannot start container d046cdba9fb2534b5e2712464b11d118c02c1bad3183251c4bb64a1f940eb273: [8] System error: invalid argument
Error response from daemon: Cannot start container 6f881fb3ad7c255e6984dc8eee4628554e0ff03f03e40d3e30b36ab27e4eac33: [8] System error: invalid argument
Error response from daemon: Cannot start container 7beac4495d223d053ebf29a83ad6cc1bf3a7130877c65837b57d0e389fb9f36f: [8] System error: invalid argument
Error response from daemon: Cannot start container 59070ed1ac03aa75a7ec92e592bf3f3fc653a6c80f5ab35e9c352c7b53151b62: [8] System error: invalid argument
Error response from daemon: Cannot start container 5809dd1a6dad4516ae2d73156dd8ce263bc9b31181c33d6c0e026c04f233e47c: [8] System error: invalid argument
Error response from daemon: Cannot start container 3c2a53c8c33aec244de66f858758ad35feb433f17c9dc26f1060ddf602c9d92c: [8] System error: invalid argument
Error response from daemon: Cannot start container 39b58318725fd9135438cd1241f01638e33a42a83b99c6533cc78e7aa5a57330: [8] System error: invalid argument
Error response from daemon: Cannot start container d4a5f1326cf3ac67372a7f045a1c8c048ea44cc15de61817d91504fbe9012d37: [8] System error: invalid argument
Error response from daemon: Cannot start container f6ed91e0926a292b94c309c471347b7998e07c45ae141b05f62dc5d173f66851: [8] System error: invalid argument
Error response from daemon: Cannot start container d3e18e82d422ce52c237f498fb27a06de581a462f79a104024eb0102f5ac2d5c: [8] System error: invalid argument
```

Supplementary info:
`docker version`:
```
Client:
 Version:      1.9.0-rc4
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   e6f5a3c
 Built:        Sat Oct 31 18:47:36 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc4
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   e6f5a3c
 Built:        Sat Oct 31 18:47:36 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
# docker info
Containers: 20
Images: 2
Server Version: 1.9.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS (containerized)
CPUs: 8
Total Memory: 15.63 GiB
Name: a1248732426a
ID: WZH3:IVXS:44HE:THGF:7JRD:PYE3:KUAK:MDZ2:U727:KLJR:WBDW:YBBZ
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 19
 System Time: 2015-10-31T19:30:50.035193143Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

`uname -a`:
```
Linux a1248732426a 3.13.0-65-generic #105-Ubuntu SMP Mon Sep 21 18:50:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
/cc @ibuildthecloud @tiborvass

### PR DESCRIPTION
**Pull request by mrjana**
Vendoring libnetwork @ 05a5a1510f85977f374a9b9804a116391bab5089

Fixes #17577 

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

**Comment by mavenugo** [comment]
thanks @mrjana. LGTM.

**Comment by thaJeztah** [comment]
Looks like the linked issue is on the 1.9.0 milestone, so added this one to it as well

**Comment by ibuildthecloud** [comment]
not-LGTM.  This does fix the original #17577 but I found more issues in the area of networking so it seems we should wait to vendor again.  Refer to #17577 for more info.

**Comment by ibuildthecloud** [comment]
LGTM.  Tested on RancherOS and networking issues are resolved

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
