### PR TITLE
Refactor ProcessConfig

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This PR resolves some outstanding TODO Windows comments by refactoring the ProcessConfig structure into platform agnostic and specific fields. It also removes the (now) redundant checkSupportedOptions check.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Rebased after LXC removal

**Comment by LK4D4** [comment]
LGTM
@jhowardmsft need rebase

**Comment by jhowardmsft** [comment]
Yup, rebased :)

**Comment by calavera** [comment]
LGTM

**Pull request merged**
