### PR TITLE
Use newer x/sys/windows SecurityAttributes struct

### PR DESCRIPTION
**Pull request by zx2c4**
This struct now has a properly typed member, so use the properly typed functions with it.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! I see `winio.SddlToSecurityDescriptor()` is also used in https://github.com/moby/moby/blob/ad1b781e44fa1e44b9e654e5078929aec56aed66/builder/dockerfile/copy_windows.go#L70

Haven't looked closely, but perhaps that one can also be replaced?

Perhaps it's worth to open a pull-request in the https://github.com/Microsoft/go-winio repository to mark `SddlToSecurityDescriptor` as deprecated, and make it an alias for the `/x/sys` implementation (or at least mark it deprecated, so that people that use the `go-winio` package get notified that they should replace it

**Comment by thaJeztah** [comment]
@tklauser @jterry75 PTAL

**Comment by thaJeztah** [comment]
Looks like there's an import that has to be removed, and perhaps the vendored `/x/sys` needs to be updated to a more current version;

```

[2019-09-30T15:24:13.154Z] pkg/system/filesys_windows.go:14:2: imported and not used: "github.com/docker/docker/vendor/github.com/Microsoft/go-winio" as winio
[2019-09-30T15:24:13.154Z] pkg/system/filesys_windows.go:106:13: undefined: "github.com/docker/docker/vendor/golang.org/x/sys/windows".SecurityDescriptorFromString
```

**Comment by zx2c4** [comment]
> Perhaps it's worth to open a pull-request

Already done.

> Haven't looked closely, but perhaps that one can also be replaced?

It could but it's not necessary since all the things its passed to treat it as an array of bytes.

> Looks like there's an import that has to be removed, and perhaps the vendored /x/sys needs to be updated to a more current version;

Will fix.

**Comment by zx2c4** [comment]
@thaJeztah Force-pushed. I haven't actually looked how to build this, so if it fails again, you can take over the PR if you want.

**Comment by jterry75** [comment]
> Thanks! I see `winio.SddlToSecurityDescriptor()` is also used in
> 
> https://github.com/moby/moby/blob/ad1b781e44fa1e44b9e654e5078929aec56aed66/builder/dockerfile/copy_windows.go#L70
> 
> Haven't looked closely, but perhaps that one can also be replaced?
> 
> Perhaps it's worth to open a pull-request in the https://github.com/Microsoft/go-winio repository to mark `SddlToSecurityDescriptor` as deprecated, and make it an alias for the `/x/sys` implementation (or at least mark it deprecated, so that people that use the `go-winio` package get notified that they should replace it

@kevpar - Can you work on getting this deprecated in go-winio? Thanks

**Comment by jterry75** [comment]
go-winio PR here: https://github.com/microsoft/go-winio/pull/165

**Comment by thaJeztah** [comment]
> Already done.
> go-winio PR here: microsoft/go-winio#165

perfect! thanks!

> @thaJeztah Force-pushed. I haven't actually looked how to build this, so if it fails again, you can take over the PR if you want.

No worries; for the vendored files, the `vendor.conf` needs to be updated to point to the right commit, otherwise the `vendor` check will fail in CI; I can push to this branch to make those changes.

**Comment by thaJeztah** [comment]
Looks like there's one more change needed;

```
# github.com/docker/docker/builder/dockerfile
builder/dockerfile/internals_windows.go:34:20: assignment mismatch: 2 variables but sid.String returns 1 values
builder/dockerfile/internals_windows.go:49:19: assignment mismatch: 2 variables but sid.String returns 1 values
```

**Comment by zx2c4** [comment]
> Looks like there's one more change needed;
> 
> ```
> # github.com/docker/docker/builder/dockerfile
> builder/dockerfile/internals_windows.go:34:20: assignment mismatch: 2 variables but sid.String returns 1 values
> builder/dockerfile/internals_windows.go:49:19: assignment mismatch: 2 variables but sid.String returns 1 values
> ```

All set.

**Comment by thaJeztah** [comment]
almost; 😂 🤷‍♂ 

```
# github.com/docker/docker/builder/dockerfile
builder/dockerfile/internals_windows.go:15:2: imported and not used: "github.com/docker/docker/vendor/github.com/pkg/errors"
```

let me carry the changes; I think I'll separate the vendor bump from the local changes in case we want to backport (which could make it slightly easier)

**Comment by thaJeztah** [comment]
carrying in https://github.com/moby/moby/pull/40021

**Pull request closed without merging**
