### PR TITLE
Bump to version v1.6.2

### LINKED ISSUE #13097: Mounting /sys is broken in Docker 1.6.1
Docker 1.6.1 broke the ability to mount `/sys` into a container. This is breaking [cAdvisor](https://github.com/google/cadvisor/) as it uses that for cgroup and network stats.

The fix was already merged to libcontainer: https://github.com/docker/libcontainer/pull/576

Can there be a Docker 1.6.2 with this fix?

/cc @vishh @rjnagal @crosbymichael

### PR DESCRIPTION
**Pull request by crosbymichael**
Lets get this show on the road.

Fixes #13097

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
Don't we want to include https://github.com/docker/libcontainer/pull/550 ? It is real daemon crash, no recover or stuff.

**Comment by crosbymichael** [comment]
@LK4D4 ok, I can take that commit also

**Comment by crosbymichael** [comment]
@LK4D4 done

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
Uploaded to:

```
Ubuntu/Debian: https://test.docker.com/ubuntu or curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.6.2-rc1
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.6.2-rc1
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.6.2-rc1
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.6.2-rc1.tgz
```

**Comment by rjnagal** [comment]
Verified cAdvisor with the new release. Thanks for the quick fix :+1:

**Comment by Thell** [comment]
can mount `-v /sys/fs/cgroup:/sys/fs/cgroup:ro`

**Comment by crosbymichael** [comment]
Thanks for testing all

**Comment by PikachuEXE** [comment]
When would this version be released?

**Comment by ewindisch** [comment]
LGTM

**Pull request merged**
