### PR TITLE
cmd/dockerd: fix some minor issues in Windows implementation

### PR DESCRIPTION
**Pull request by thaJeztah**
stumbled upon these by accident 😂  - I should probably also look at integrating some of these defaults into https://github.com/moby/moby/pull/43756, but decided to just open these separately, as that PR needs a bit more work.

-----

- properly use filepath.Join() for Windows paths
- use getDaemonConfDir() to get the path for storing daemon.json
- return error instead of logrus.Fatal(). The logrus.Fatal() was a left-over from when Cobra was not used, and appears to have been missed in commit fb83394714a9797f8ca5a08023a89560ce6c4aa3 (https://github.com/moby/moby/pull/25354), which did the conversion to Cobra.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Wondering if this is a buildkit bug; have seen it a few times; /cc @crazy-max 

```
[2022-08-09T21:26:28.349Z] #72 [vpnkit 1/2] COPY --from=vpnkit-amd64 /vpnkit /build/vpnkit.x86_64
[2022-08-09T21:26:28.349Z] #72 sha256:c0e1a70b68cbf39676beec79ce39fce21b4fe65bce17ff7506a08a7a4e2d23b9
[2022-08-09T21:26:28.349Z] #72 ERROR: mount already exists with name
```

**Comment by thaJeztah** [comment]
Seen this one a couple of times on Windows as well; https://github.com/moby/moby/runs/7755588826?check_suite_focus=true#step:14:734

```
=== FAIL: github.com/docker/docker/integration/container TestWaitNonBlocked/wait-nonblocking-exit-0 (1.34s)
    wait_test.go:44: assertion failed: error is not nil: Error response from daemon: hcs::CreateComputeSystem 39b4941e04d641e1bea1584f01c69c3a17995fa759d523992c0b10bf54bf3ec3: Element not found.
    --- FAIL: TestWaitNonBlocked/wait-nonblocking-exit-0 (1.34s)
```

**Comment by crazy-max** [comment]
> Wondering if this is a buildkit bug; have seen it a few times

Are Jenkins using BuildKit in the engine or `docker-container` driver with latest BuildKit stable through buildx?

**Comment by thaJeztah** [comment]
Just the built-in driver (easier for cleaning up resources). Looks like Ci is still on 20.10.14, but don't think many changes went in (buildkit related). But yeah, could be an old issue that has already been resolved. Wasn't sure if this error would come from buildkit or the front-end.

**Review by corhere — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Pull request merged**
