### PR TITLE
Clean some stuff from runconfig that are cli only…

### PR DESCRIPTION
**Pull request by vdemeester**
… or could be in `opts` package. Having `runconfig/opts` and `opts` doesn't really make sense and make it difficult to know where to put some code.

- This unexport anything that doesn't need to be exported as of now.
- This might unexport stuff used outside (I'll have to check that with `docker/libcompose` as an example)
- `cli/command/container/opts.go` is probably way too big, should be split at some point.

/cc @thaJeztah @dnephin @icecrime @tiborvass @runcom @cpuguy83 

🐸 :santa: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
hold of merging for now, if there's still cherry picking needed for 1.13

**Comment by thaJeztah** [comment]
It was discussed yesterday that we go ahead and merge, if needed PR's for 1.13 can be re-opened against the 1.13 branch directly

**Pull request merged**
