### PR TITLE
Add backward compatibility for info response type

### PR DESCRIPTION
**Pull request by jlhawn**
Between v1.24 and v1.25 of the API, the docker info response type had a change in the structure of the `SecurityOptions` field. Previously, it was a `[]string` but it is now a `[]SecurityOpt` which are custom struct types with `Key` and `Value` fields.

This patch adds a custom `UnmarshalJSON([]byte) error` method to the `SecurityOpt` type which can safely handle responses for pre-v1.25 API requests.

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :frog:
/cc @runcom @justincormack @cpuguy83

**Comment by runcom** [comment]
LGTM

**Comment by jlhawn** [comment]
While this PR does fix a problem, I think there's still a better option. From https://github.com/docker/docker/issues/28449#issuecomment-261030138:

> I think changing the structure of the SecurityOptions field in the docker info API response was a bad move which very clearly violates semantic versioning. We should keep that field the way it was, add a deprecation note, and add a different field name for the new structure.

**Comment by runcom** [comment]
@jlhawn I'm fine doing that either, that feature needed a better security options structure anyway, so...

**Comment by runcom** [comment]
@jlhawn are you taking care of that? I can work on that as well if you're ok with it

**Comment by jlhawn** [comment]
> @jlhawn are you taking care of that? I can work on that as well if you're ok with it

@runcom If you could take care of that that would be great. I only submitted this PR as a very small quick-fix but it looks like something more comprehensive would be required and I'm not as familiar with everything else.

**Comment by runcom** [comment]
> @runcom If you could take care of that that would be great. I only submitted this PR as a very small quick-fix but it looks like something more comprehensive would be required and I'm not as familiar with everything else.

ack, I'll create a PR after dinner :smile:

**Comment by vieux** [comment]
closed in favor of #28504

**Pull request closed without merging**
