### PR TITLE
[WIP] Set SELinux labels, and NoNewPrivileges on exec'd process

### LINKED ISSUE #37667: docker exec does not obey --security-opt no-new-privileges
**Description**

`docker run` supports starting a container with `no new privileges` enabled, however this does not seem to apply to processes started with `docker exec`

**Steps to reproduce the issue:**

1. Set up a test (suid root id)
```
$ sudo cp `which id` .
$ sudo chmod +s id
```

2. Check that it is working (elevate privs inside container)
```
$ docker run --rm -ti -v `pwd`:/test -u 1000:1000 centos:7 /test/id
uid=1000 gid=1000 euid=0(root) egid=0(root) groups=0(root)
```

3. Check that no-new-privs is working
```
$ docker run --rm -ti -v `pwd`:/test -u 1000:1000 --name nnp-test --security-opt no-new-privileges centos:7
bash-4.2$ /test/id
uid=1000 gid=1000 groups=1000
```

4. Check that no-new-privs is working with docker exec (in another terminal, leaving the container from previous step running)
```
$ docker exec -ti -u 1000:1000 nnp-test /test/id
uid=1000 gid=1000 euid=0(root) egid=0(root) groups=0(root)
```

**Describe the results you received:**
Eventhough the container was started with `--security-opt no-new-privileges` privilege elevation was possible through `docker exec`

**Describe the results you expected:**
No privilege elevation.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:45 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:14:07 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.17.14-202.fc28.x86_64
Operating System: Fedora 28 (Twenty Eight)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.53GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/37667

Processes started through `docker exec` did not automatically inherit the SELinux labels, and "No New Privileges" configuration from the containers' main process.

Making this "WIP", pending tests

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by justincormack** [comment]
Looks correct.

**Comment by stevvooe** [comment]
LGTM

**Comment by thaJeztah** [comment]
Actually, this needs an update; looking at the old behavior, this should be skipped when. the _container_ is started privileged, not when the _exec_ is started with privileged; I’ll try to update soon

**Comment by vdemeester** [comment]
ping @thaJeztah what is the status ? :angel:

**Comment by jraby** [comment]
Any update on this?

In environments which permit users to run commands inside a container via `docker exec` (`kubectl exec` for example, and probably any service with wrappers around docker), this allows users to run setuid programs even if the container was started with `no-new-privileges`, which could be a potential security problem.

It was working correctly in 17.06, and it is broken since 17.12. (just tested in 18.03 and 18.05)

**Comment by thaJeztah** [comment]
> In environments which permit users to run commands inside a container via docker exec (kubectl exec for example, and probably any service with wrappers around docker), this allows users to run setuid programs even if the container was started with no-new-privileges, which could be a potential security problem.

Ah, yes, I had a WIP commit for exactly that, but had some issues locally with running the tests; I just pushed my branch, but need to clean it up :sweat_smile:

**Comment by jraby** [comment]
For the record, the problem I was describing above seems to have been resolved by https://github.com/docker/engine/pull/178.

**Comment by crosbymichael** [comment]
Feel free to re-open when you have time to rebase this

**Pull request closed without merging**
