### PR TITLE
Api typed errors

### PR DESCRIPTION
**Pull request by cpuguy83**
Start using typed errors for API endpoints.
This makes sure that rep codes returned by the API are explicit rather than implied by the error string.

This is just the first one up for discussion, could probably knock out the rest (and get some tests for these!) if everyone pitches in pretty quickly.

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think @duglin and @stevvooe are interested in this?

**Comment by duglin** [comment]
@cpuguy83 @thaJeztah yeah, I'm on the verge of submitting https://github.com/duglin/docker/tree/UseErrorPackage to get feedback so that we can use the same error package that distribution is using.  Its basically the follow-on to https://github.com/docker/docker/pull/9509

**Comment by duglin** [comment]
See https://github.com/docker/docker/pull/15069

**Comment by stevvooe** [comment]
:-1: API errors should be defined with `errcode` package.

**Comment by cpuguy83** [comment]
Cool I wasn't aware of the errcode stuff. I'm good with it and will close this one.

**Comment by thaJeztah** [comment]
Yeah, I wasn't sure you knew, hence my "ping".

Thanks @cpuguy83 !

**Comment by stevvooe** [comment]
@cpuguy83 Sounds good. Let me know if you have questions about `errcode` or we need to add examples or clarification to the package documentation.

**Pull request closed without merging**
