### PR TITLE
hack/make/.go-autogen: fix typo in LDFLAGS variable

### PR DESCRIPTION
**Pull request by thaJeztah**
Introduced in https://github.com/moby/moby/commit/675b414f56063826457cbc8f0c165af67198bfa8 (https://github.com/moby/moby/pull/40180)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tonistiigi @cpuguy83 PTAL

**Comment by thaJeztah** [comment]
Looks like a flaky test on Windows (RS5)
https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-40389/runs/1/nodes/52/log/?start=0

```
=== FAIL: github.com/docker/docker/integration-cli TestDockerSuite/TestStartAttachMultipleContainers (62.16s)
    --- FAIL: TestDockerSuite/TestStartAttachMultipleContainers (62.16s)
        cli.go:29: assertion failed:
            Command:  d:\CI\PR-40389\1\binary\docker.exe run -d --name test2 busybox sleep 240
            ExitCode: 125
            Error:    exit status 125
            Stdout:   ee5370488006df8953720d813098f010f9eab324d15b828e8dcdd85a4b4d340f

            Stderr:   d:\CI\PR-40389\1\binary\docker.exe: Error response from daemon: hcsshim::PrepareLayer - failed failed in Win32: The device is not ready. (0x15).


            Failures:
            ExitCode was 125 expected 0
            Expected no error
```

**Review by tianon — APPROVED** [review]
LGTM 😅

**Review by cpuguy83 — APPROVED** [review]
Oy... LGTM.

**Pull request merged**
