### PR TITLE
Vendor go-systemd daemon and refactor pkg systemd

### PR DESCRIPTION
**Pull request by runcom**
use `SdNotify` provided func instead of docker's own
I just proxied the func from pkg/systemd to not break the api (even though the returned error is different now), I think code can just use go-systemd directly, I'll change the code if it's the case..

### CODE REVIEW

**Comment by tiborvass** [comment]
@runcom i'm not sure i understand this PR. Why does it say "forked from docker" and why would we vendor that? Ping @LK4D4

**Comment by runcom** [comment]
ping @tiborvass @LK4D4 
as per yesterday IRC chat, I removed pkg/systemd and adapted the code

**Comment by LK4D4** [comment]
Looks nice as for me

**Comment by tiborvass** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
