### PR TITLE
fix slow response for log read request with --since parameter for jsonfilelog

### PR DESCRIPTION
**Pull request by haveatry**
Signed-off-by: rpei <cspeiyb@gmail.com>

**- What I did**
Fix the issue as described in #31935 
**- How I did it**
  1. set --log-opt max-size to a small size, for example, 5m

  2. Based on the real need, set --log-opt max-file to one reasonable number.

  3. Before building the logic concatenation ReadSeeker, make code change to only select files whose mtime is later than the --since parameter. This could help reduce the range of total log records and let the docker daemon to give a quick response to client.
**- How to verify it**
1.Run a container to generate enough logs, the more, the better. In my test, the total log size is around 400M
2.Using the following command to verify how long to get a response from docker daemon. Please specify a relatively late timestamp to the since parameter. For a extreme case, you could specify a latest timestamp of all the logs to the --since parameter.
date;docker logs --since=xxxxx [container_id] > test.log 2>&1;date
**- Description for the changelog**
Make enhancement to reduce the total size of logs to search for the log read request with --since parameter.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by haveatry** [comment]
@stevenh Do you have any comment on the fix? Do I need to take any further action?

**Comment by stevenh** [comment]
@haveatry I think you may have auto completed the wrong name there, as I'm not familiar with this issue.

**Comment by haveatry** [comment]
@thaJeztah @stevenh do you know how to assign the issue to correct member?

**Comment by stevvooe** [comment]
Is the modtime guarantee strong enough for this work? Seems like we'd need a stronger guarantee, such as a timestamp in the file name.

**Comment by haveatry** [comment]
@stevvooe Thanks for your good suggestion. I double check the code logic and find that it would rename the log files when rotating log files. But such operation only updates the file change time, it will not update the modtime. I do not find other code logic that may change the log file property. Do you mean that a stronger guarantee is necessary to avoid manual operation to update the log file content?

The following are some log files properties  I get with the stat command.   
File: ‘b91db861ea8e1c6cb92bec45d04f49258137a8580ab84810f94ac7a442e7ff65-json.log.1’
Access: 2017-04-19 17:05:37.131686561 +0800
Modify: 2017-04-19 17:24:07.444370301 +0800
Change: 2017-04-19 17:24:07.449370079 +0800

File: ‘b91db861ea8e1c6cb92bec45d04f49258137a8580ab84810f94ac7a442e7ff65-json.log.2’
Access: 2017-04-19 16:44:57.762729268 +0800
Modify: 2017-04-19 17:05:37.127686739 +0800
Change: 2017-04-19 17:24:07.449370079 +0800

File: ‘b91db861ea8e1c6cb92bec45d04f49258137a8580ab84810f94ac7a442e7ff65-json.log.3’
Access: 2017-04-19 16:23:55.938743748 +0800
Modify: 2017-04-19 16:44:57.758729446 +0800
Change: 2017-04-19 17:24:07.449370079 +0800

**Comment by vdemeester** [comment]
@haveatry could you squash and sign off your commit ? 👼

**Comment by cpuguy83** [comment]
@haveatry I have the same concern as @stevvooe.
Also the file write time may not be the same time as when a log entry was captured.
We could store some metadata about rotated files.

**Comment by haveatry** [comment]
@cpuguy83 @stevvooe，thanks for your comment, I will update the fix as your suggestion

**Comment by haveatry** [comment]
@cpuguy83 Could you please help review my rework based on your suggestion?

**Comment by stevenh** [comment]
@haveatry you have conflicts which need resolving, likely need to rebase.

**Comment by haveatry** [comment]
@stevenh I met with the following error when I tried to rebase and fix the conflict. Do you have any suggestion to resolve this error?
[root@localhost docker]# git rebase  upstream/master
fatal: Needed a single revision
invalid upstream upstream/master

**Comment by stevenh** [comment]
Check your remotes with ```git remote -v``` to make sure upstream is the correct upstream name.

**Comment by fntlnz** [comment]
@haveatry were you able to rebase? This PR is getting old and don't want to lose your changes.

**Comment by haveatry** [comment]
ping for code review.

**Comment by AkihiroSuda** [comment]
This PR is not reviewable.
Please rebase this PR to exclude 250+ unrelated commits.

**Comment by haveatry** [comment]
@AkihiroSuda How to check which commit is unrelated? How can I exclude all unrelated commits?

**Comment by AkihiroSuda** [comment]
Please do `git rebase` so that `Commits` in this page only contains a single (or a few) commit(s)

image

**Comment by fntlnz** [comment]
@haveatry AFAICS you don't have a lot of conflicts but I would suggest you to squash your two commits in order to avoid resolving conflicts twice.
Also are you still interested in getting this merged?

**Comment by fntlnz** [comment]
@haveatry If not please let us know so that we can see if we can move this forward autonomously

**Comment by cpuguy83** [comment]
Closing since this has gone non-responsive and the commits appear to be messed up.

**Pull request closed without merging**
