### PR TITLE
Bump v1.8.0

### PR DESCRIPTION
**Pull request by calavera**
Track changes for Docker 1.8.0.

Release scheduled for Tuesday, August 11th.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Are RC builds tagged?  I can't find a tag anywhere.

**Comment by tianon** [comment]
https://github.com/docker/docker/releases/tag/v1.8.0-rc1 :+1:

**Comment by calavera** [comment]
We have just pushed 1.8.0-rc2 to https://test.docker.com. You can download it with the following:

RPMs/DEBs: curl -sSL https://test.docker.com | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.8.0-rc2
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.8.0-rc2
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.8.0-rc2
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.8.0-rc2.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.8.0-rc2.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.8.0-rc2.exe

Please test and make sure all links are working. You can see a list of the changes in the project changelog:

https://github.com/calavera/docker/blob/8a9d4eaa6e1645c66cd8047e87b8df323a6e7082/CHANGELOG.md

**Comment by burke** [comment]
We've been running rc2 on some build nodes for a few days and everything is looking good :+1:

**Comment by thaJeztah** [comment]
Thanks @burke!

**Comment by calavera** [comment]
I just tagged RC3 :scream_cat: We've started to use GitHub releases to keep track of changes and links. Feel free to download the binaries from the urls in https://github.com/docker/docker/releases/tag/v1.8.0-rc3.

**Comment by thaJeztah** [comment]
> We've started to use GitHub releases to keep track of changes and links

:+1: :100: thanks! Much easier to point users to the right downloads

@calavera should we add a link to this PR on the releases page?

**Comment by jfrazelle** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by thaJeztah** [comment]
Congrats all! And thanks @calavera for being release captain! Have one on me 🍺🍻🍷🍸🍼☕️

**Pull request merged**
