### PR TITLE
Small changes from #11967 for review comments

### PR DESCRIPTION
**Pull request by ibuildthecloud**
Infer type in server.go and also make server_windows.go consistent with server_linux.go.  I have no clue how server_windows.go is used but I'd hate to see the docker daemon on windows hit the same race condition.

### CODE REVIEW

**Comment by icecrime** [comment]
Ping @ahmetpbalkan @jonhowardmsft.

**Comment by ibuildthecloud** [comment]
@LK4D4 here's the small change to infer the type I should have done the in first place.  But then I seemed like you fix for server_linux.go should probaby apply to server_windows.go

**Comment by jhowardmsft** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
Code LGTM. However if we're maintaining something in more than one place that's generally a bad sign. Maybe we should refactor server logic to be in only one place.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
