### PR TITLE
Add Go Report Card badge

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by MHBauer** [comment]
We're going to have a docker with perfect spelling.

**Comment by calavera** [comment]
just wait until @jhowardmsft sees that they are marking `optimisation` as a spelling error.

**Comment by jhowardmsft** [comment]
cough :uk:

**Comment by MHBauer** [comment]
@calavera but that's British, isn't it? Can we use custom dictionaries?

**Comment by thaJeztah** [comment]
Next release will be in Klingon

**Comment by calavera** [comment]
I'm personally not very fond of adding badges of services that we don't use in a daily bases, fwiw.

**Comment by MHBauer** [comment]
Now that the  **OOH SHINY** has worn off for me. Is there value in adding the spelling or complexity plugins to the build? I think for the most part, the answer is no.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jhowardmsft** [comment]
I have to somewhat agree with the comment above from @MHBauer. But +1 for Klingon :)

**Comment by thaJeztah** [comment]
Alright, not everyone thinks we should add the badge, and not really attached to it, so closing

**Pull request closed without merging**
