### PR TITLE
vendor: bump libcontainer and its deps

### LINKED ISSUE #18535: Same IP address for different containers
I don't know how to reproduce, but sometimes I get this:
```
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "5cf320101baed9b2326d71ca777c17eba8872465292d8b2754a82543a1813fb1",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "80/tcp": [
                {
                    "HostIp": "127.0.0.3",
                    "HostPort": "85"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/5cf320101bae",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "6a5df1a32364c0bb66525587585e05900ca9c67a2642381fd4b14471f9c74b49",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.119",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:77",
        "Networks": {
            "bridge": {
                "EndpointID": "6a5df1a32364c0bb66525587585e05900ca9c67a2642381fd4b14471f9c74b49",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.119",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:77"
            }
        }
    }
```

```
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "639dc0fca859a6bb3dc538671ab20048fa2d15aecb2f372ece58dfbbe798f19a",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/639dc0fca859",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "3e38035bd8b5fe66f48b6db284b17fd98e2d6825123265acaf102e66036c3075",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.119",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:77",
        "Networks": {
            "bridge": {
                "EndpointID": "3e38035bd8b5fe66f48b6db284b17fd98e2d6825123265acaf102e66036c3075",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.119",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:77"
            }
        }
    }
```

```
 docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
Containers: 307
Images: 1001
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1989
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 32
Total Memory: 251.9 GiB
Name: DS4488
ID: 5S4Z:BR7A:22PL:BHAR:GUOD:GVE4:NPA3:XODE:NOBA:35GL:ZWKF:WZAX
```

```
Linux DS4488 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by runcom**
Pulls latest libcontainer code and updates its deps (and libnetwork)

Signed-off-by: Antonio Murdaca runcom@redhat.com

Fixes #18535

### CODE REVIEW

**Comment by runcom** [comment]
https://github.com/docker/docker/pull/17211 updated `go-systemd` to v4, now libnetwork isn't compiling because it's using v3 (and godbus/dbus v2), I'll try and update libnetwork as well otherwise this PR won't even compile

**Comment by runcom** [comment]
created https://github.com/docker/libnetwork/pull/765 to address the above comment

**Comment by tianon** [comment]
Wooot, "v0.0.5" now available! :smile: :heart:

**Comment by runcom** [comment]
updated! though this still needs libnetwork changes before being merged :(

**Comment by runcom** [comment]
@LK4D4 @tianon this can be reviewed now that libnetwork changes are in and it does compile

**Comment by tianon** [comment]
:metal: :+1:  LGTM

**Comment by LK4D4** [comment]
I'll wait for CI :D

**Comment by runcom** [comment]
oh noes, cross-compile failed lol

**Comment by runcom** [comment]
opened https://github.com/docker/libnetwork/issues/770 which address failures in cross compilation

**Comment by runcom** [comment]
\o/ green!

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
@tiborvass I added this to the 1.9.2 milestone for consideration, because it fixes https://github.com/docker/docker/issues/18145. **however** I see this PR not only updates libnetwork, but also libcontainer, and I'm not sure (*if* a 1.9.2 release is released) we want both in a patch release...

**Comment by sitamet** [comment]
@thaJeztah @tiborvass Please, add this to a 1.9.2 :( 
we are on production with 1.9.1 with #18535
the workaround (removing network local-kv.db) does not solve the real problem

**Comment by thaJeztah** [comment]
@sitamet we most likely won't be releasing 1.9.2; but this will be in docker 1.10; code freeze is this Thursday - scheduled for release February 4th

**Comment by sitamet** [comment]
@thaJeztah ok ... lets go forward then :S

**Pull request merged**
