### PR TITLE
Dockerfile's comments for "Run the test suite" are out of date becaus…

### PR DESCRIPTION
**Pull request by ShevYan**
Hi,

There are incorrect comments at the beginning of Dockerfile*. I just submit a pull request. Could you please check if my change is right? 

issue:

``` bash
[root@CentOS7-01 ~]# docker run --rm --privileged docker-dev:v1-12-0 hack/make.sh test

/go/src/github.com/docker/docker/hack/make.sh: line 316: /go/src/github.com/docker/docker/hack/make/test: No such file or directory
---> Making bundle: test (in bundles/1.12.0-dev/test)
```

cause:

``` bash
[root@CentOS7-01 ~]# docker run --rm --privileged docker-dev:v1-12-0 ls -a hack/make | grep test
.ensure-nnp-test
.ensure-syscall-test
test-deb-install
test-docker-py
test-install-script
test-integration-cli
test-old-apt-repo
test-unit
validate-test
```

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐯
/cc @tianon @thaJeztah

**Comment by dnephin** [comment]
I wonder if it would be better to restore the `hack/make/test` as an alias for these instead of changing the docs?

**Comment by ShevYan** [comment]
Thanks, @dnephin. So I just need add 'test' refer to 'dynbinary':

```bash
#!/bin/bash
set -e

# This script exists as backwards compatibility for CI
(
    DEST="${DEST}-unit"
    ABS_DEST="${ABS_DEST}-unit"
    . hack/make/test-unit
)

(

    DEST="${DEST}-integration-cli"
    ABS_DEST="${ABS_DEST}-integration-cli"
    . hack/make/test-integration-cli
)

(

    DEST="${DEST}-docker-py"
    ABS_DEST="${ABS_DEST}-docker-py"
    . hack/make/test-docker-py
)
```

**Comment by ShevYan** [comment]
@dnephin, thanks for your suggestion. I go through the scripts and did a test. If we want to add an alias for these, we need add 'dynbinary', 'cross' and 'binary' as well, otherwise we would get errors. So is it good to change "Run the test suite" to "Run the unit test suite" and just only run test-unit?
```bash
...
 # # Mount your source in an interactive container for quick testing:
 # docker run -v `pwd`:/go/src/github.com/docker/docker --privileged -i -t docker bash
 #
-# # Run the test suite:
-# docker run --privileged docker hack/make.sh test
+# # Run the unit test suite:
+# docker run --privileged docker hack/make.sh test-unit

...
```

**Comment by dnephin** [comment]
There is already an alias for both `binary`, and `dynbinary`, and `cross` already exists, so I don't think you need to do anything with them.  Why do you say that we'd need to create an alias for them?

**Comment by ShevYan** [comment]
Sorry for confusing. I mean add these into "test" alias like "make test".

**Comment by dnephin** [comment]
Oh, I don't think that's necessary. The docs reference `hack/make/test` (indirectly through `hack/make.sh`, but that's what it expects to exists).

I was just suggesting adding a script at `hack/make/test` that calls the other scripts

**Comment by ShevYan** [comment]
Yes, I understand that. However, test-integration-ci requires binary, so if we use "test" in dockerfile , we should add not only  "test-*" to the "test" script but also "binary".  "test-unit" does not require binaries, that's why I suggest changing "test" to "unit-test" in dockerfile. Anyway, it's okay for me to change as your suggestion.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
