### PR TITLE
Reduce logging level for "ip_local_port_range" proc file in not accessible.

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by jfrazelle** [comment]
sorry @vishh gordon does not like you for some reason, i swear its only you... i will look into it bc its def signed

**Comment by jfrazelle** [comment]
LGTM

**Comment by vishh** [comment]
@jfrazelle: I don't recall messing with gordon in the past :(

**Comment by estesp** [comment]
LGTM

**Pull request merged**
