### PR TITLE
Add support for 15.04, add systemd note for 15.04

### LINKED ISSUE #12002: add documentation: Ubuntu installation
I was following this page: https://docs.docker.com/installation/ubuntulinux/

After I installed docker but and ran the command: $ sudo docker run hello-world

It returned:

FATA[0000] Get http:///var/run/docker.sock/v1.17/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

can you please add a step in the instructions to run: service docker restart

This fixed the issue for me.

### PR DESCRIPTION
**Pull request by ankushagarwal**
Fixes #12002

Signed-off-by: Ankush Agarwal ankushagarwal11@gmail.com

### CODE REVIEW

**Comment by ankushagarwal** [comment]
CC @moxiegirl @thaJeztah @jfrazelle

**Comment by Jean85** [comment]
There's a typo: "installtion".
Can't fix it myself...

**Comment by thaJeztah** [comment]
> There's a typo: "installtion".

Yes, I noticed that one, thanks @Jean85 !

**Comment by thaJeztah** [comment]
@ankushagarwal sorry for not responding to this PR sooner, I actually had this open for a couple of days because I wasn't sure how to proceed here (I *did* notice the typos, but that's not the main issue). 

Because I don't have a clear answer now, I'll just put my thoughts here, perhaps you can think along;

- I agree this needs to be mentioned somewhere; some people expect that docker is *automatically* configured to start at boot (when using Systemd). (this *was* a deliberate decision, so that the *user* can decide wether or not docker should start automatically)
- Perhaps we should add a message to the installer that mentions that Docker is not configured to start automatically (just as the ["using Docker as non-root" message](https://github.com/docker/docker/blob/957622d452983f14bcc79443c9ff05780e1fd6bf/hack/install.sh#L224) in the installer)
- It's a bit strange that this section describes how to handle automatic start after installing on 15.04, but  there's no actual installation procedure / mention of 15.04 in the document. In fact, it's not mentioned below *"Docker is supported on these Ubuntu operating systems:"*.
- There's also sections on [systemd](https://docs.docker.com/articles/systemd/) and [host integration](https://docs.docker.com/articles/host_integration/) that can be relevant here, perhaps this should be put inside that document?



(I also think the section on 13.10 should be removed, because it doesn't really add anything and [13.10 is end-of-life as of July 2014](http://fridge.ubuntu.com/2014/07/17/ubuntu-13-10-saucy-salamander-end-of-life-reached-on-july-17-2014/), but that's unrelated here :smile:)

/cc @moxiegirl (we briefly discussed this on IRC)

**Comment by ankushagarwal** [comment]
I strongly believe that docker starting up on boot should be default behaviour regardless of the package manager or the system manager or the distro you are trying to install docker on and this behaviour should not differ from distro to distro or package manager or the system manager (systemd v/s upstart). On completing installation we can print a message saying something like "docker will start on boot....  Run command xyz to turn off docker starting on boot..."

I believe so because most system softwares are installed with expectation to start on bootup. Most systems softwares are _daemons_ (eg: sshd, crond, etc) and are always expected to run in the background without explicitly configuring them to do so.

The only reason I see why people wouldn't want docker to start on startup would be if they are experimenting with docker on their laptops. But I believe anybody trying to install docker on a server or a VM would want auto restart on boot as default behavior, with an easily configurable option to disable that.

People have been using `wget -qO- https://get.docker.com/ | sh` for a while and nobody has complained about docker automatically starting on boot, but started complaining when they did not see that behaviour.

**Comment by ankushagarwal** [comment]
Regarding the 15.04 comment, can we just update the docs and say we support 14.04 and above?

**Comment by moxiegirl** [comment]
@ankushagarwal  I don't think anyone disagrees that `docker` daemon should be started on boot.  With this contribution, there are two aspects here. 

- Adding messaging to the installer which is suggested but not implemented in this ticket
- Inclusion of the `systemd` startup material in the installation docs and *in other places*

We are leaning toward consolidating the material regarding configuration of startup options in another page.  This page is becoming the central location for that https://docs.docker.com/articles/systemd/ . It covers something a bit further than starting the daemon which is also useful.  Maybe you can consider adding your information to that page. 

And then, we will need a link from each installation out to that. What do you think?

**Comment by icecrime** [comment]
Installation is not specific to a given Ubuntu version, unfortunately administration is (as 15.04 introduced systemd). That being said, yes 15.04 is obviously supported, and indeed this could get a bit of a refresh: http://docs.docker.com/installation/ubuntulinux/#ubuntu

**Comment by ankushagarwal** [comment]
Sounds good. Will update the article to reflect that.

**Comment by moxiegirl** [comment]
Thanks @icecrime and @ankushagarwal.

**Comment by thaJeztah** [comment]
Thanks! I'd be +1 to mention support for the LTS releases (12.04, 14.04) separate from the "regular" releases, so **not** mention "14.04 and above". IIRC, 14.10 had some issues running docker and (being a non-LTS release), is no longer supported; http://fridge.ubuntu.com/2015/07/03/ubuntu-14-10-utopic-unicorn-reaches-end-of-life-on-july-23-2015/

So we should keep a good eye on those releases, and keep them up-to-date at all times (and make a mention of that?)

**Comment by ankushagarwal** [comment]
Makes sense. I'll make sure I'll take that into account.

**Comment by cpuguy83** [comment]
Is this one ready?

**Comment by ankushagarwal** [comment]
I'll update this by tomorrow.

**Comment by ankushagarwal** [comment]
Patch updated.
Could you guys please review : @thaJeztah @icecrime @cpuguy83 @moxiegirl

**Comment by jfrazelle** [comment]
LGTM

**Comment by ankushagarwal** [comment]
@jfrazelle : Is there a plan to do this(`sudo systemctl enable docker`) automatically in the install script?

**Comment by tianon** [comment]
It should already be fixed in the new packages that are on
apt.dockerproject.org. :+1:

**Comment by moxiegirl** [comment]
LGTM THANKS @ankushagarwal

**Pull request merged**
