### PR TITLE
Add event log for push

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM (with a slight hesitation as if we should log `localName` or `repoInfo.LocalName`, but I don't think it makes a huge difference).

**Comment by dmp42** [comment]
cc @docker/distribution-maintainers

**Comment by stevvooe** [comment]
LGTM, but I agree with @icecrime. This should `repoInfo.LocalName`.

**Comment by dmcgowan** [comment]
yes, `repoInfo.LocalName` should be used

**Comment by icecrime** [comment]
@Mashimiao Thanks for the contrib! Do you mind making this little change so we can proceed with merge?

**Comment by Mashimiao** [comment]
@icecrime  of course not, fixed.

**Comment by icecrime** [comment]
Thank you! LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
