### PR TITLE
Register OCI media types

### PR DESCRIPTION
**Pull request by dmcgowan**
OCI types are backwards compatible with Docker manifest types, however the media types must be registered.

Needed to support OCI images returned from the registry.
https://github.com/docker/distribution/pull/2076

### CODE REVIEW

**Comment by stevvooe** [comment]
Lgtm

**Comment by tonistiigi** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Pull request merged**
