### PR TITLE
Add rinse32 script

### PR DESCRIPTION
**Pull request by RobinGeuze**
Add a rinse32 script which is capable of building 32-bits docker images for RPM based distro's

Signed-off-by: Robin Geuze robing@transip.nl

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon @jfrazelle ptal

**Comment by LK4D4** [comment]
ping @tianon

**Comment by thaJeztah** [comment]
ping @tianon PTAL :heart:

**Comment by LK4D4** [comment]
Have no idea about this :( ping @tianon @tiborvass @mlaventure

**Comment by tianon** [comment]
Sorry about missing this!

I'm not sure I fully understand what's being done here that can't be done by just adding `--arch i386` to the normal `rinse` script? (or by using `linux32` on the entire `mkimage.sh` process)

**Comment by RobinGeuze** [comment]
Ye I tried running linux32 on the whole script and specifying --arch i386 in the optional arguments first. However that didn't seem to work properly, although I have to admit I can't recall exactely why that was. If I find some free time I'll play with it again see if I can find the specific reason.

**Comment by thaJeztah** [comment]
@RobinGeuze let me close this PR while you test out the alternatives, but ping me if it has to be reopened

**Pull request closed without merging**
