### PR TITLE
Add zsh completion for new fluentd log driver options

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref: #19439

@albers thx for the ping

### CODE REVIEW

**Comment by thaJeztah** [comment]
@sdurrheimer looks like you forgot to sign off

**Comment by albers** [comment]
@sdurrheimer wow, you're kinda fast!

**Comment by sdurrheimer** [comment]
@thaJeztah Fixed

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
awesome, LGTM!

**Pull request merged**
