### PR TITLE
ApplyDiff to RWLayer

### PR DESCRIPTION
**Pull request by ehazlett**
This adds an `ApplyDiff` method to the RWLayer interface to allow for adding content directly to a RWLayer.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
ping @kolyshkin PTAL

**Review by tiborvass — APPROVED** [review]

**Comment by tiborvass** [comment]
Ping @dmcgowan

**Review by dmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
