### PR TITLE
Migrate exec command to cobra

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Part of https://github.com/docker/docker/issues/23211

As suggested by @vdemeester , this PR should be reviewed after release of v1.12, probably
https://github.com/docker/docker/issues/23211#issuecomment-226852456

Cc @pdalpra @tkopczynski

### CODE REVIEW

**Comment by LK4D4** [comment]
@AkihiroSuda fails on janky are valid

**Comment by AkihiroSuda** [comment]
@LK4D4 done

**Comment by dnephin** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM too 🐯
But let's wait for 1.12 release to merge :angel:

**Comment by LK4D4** [comment]
@AkihiroSuda It's time! pls rebase and we'll merge.

**Comment by AkihiroSuda** [comment]
done. (change: 4f0b5105524649169d765bb94c2806209ab21904)

**Pull request merged**
