### PR TITLE
Add Portworx description

### PR DESCRIPTION
**Pull request by jsilberm**
**\- What I did**
Added documentation for Portworx volume plugin in docs.

**\- How I did it**
Markdown

**\- How to verify it**
Render check:  https://github.com/portworx/docker_docs/blob/master/docs/extend/legacy_plugins.md

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
looks like this needs a rebase, because there's a non-related commit in this

**Comment by jsilberm** [comment]
Should be done.  Please let me know if I missed (and what I should do instead).   Thanks

**Review by thaJeztah — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thanks! LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by jsilberm** [comment]
Thanks!

**Pull request merged**
