### PR TITLE
Update vndr commit to latest

### PR DESCRIPTION
**Pull request by vdemeester**
Some fixes and it also preserves directories with *.c files now.

See https://github.com/LK4D4/vndr/compare/a6e196d8b4b0cbbdc29aebdb20c59ac6926bb384...1fc68ee0c852556a9ed53cbde16247033f104111

Same as https://github.com/docker/cli/pull/1080

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
```
08:00:39 The result of vndr differs
08:00:39 
08:00:39  D vendor/archive/tar/LICENSE
08:00:39  D vendor/archive/tar/README.md
08:00:39  D vendor/archive/tar/common.go
08:00:39  D vendor/archive/tar/format.go
08:00:39  D vendor/archive/tar/reader.go
08:00:39  D vendor/archive/tar/stat_actime1.go
08:00:39  D vendor/archive/tar/stat_actime2.go
08:00:39  D vendor/archive/tar/stat_unix.go
08:00:39  D vendor/archive/tar/strconv.go
08:00:39  D vendor/archive/tar/writer.go
08:00:39 
08:00:39 Please vendor your package with github.com/LK4D4/vndr.
```

@tonistiigi @tiborvass @kolyshkin each and everytime I get powned by that :stuck_out_tongue: Tried to do what is written on the `vendor.conf` but I guess it doesn't seem to work anymore :sob:

**Comment by thaJeztah** [comment]
We should open a PR upstream to make the cleaning optional (e.g. have a `--clean` option, or if that's not accepted, have a `--no-clean`), but ideally `--clean`, because this is a change in behavior

**Comment by kolyshkin** [comment]
This unfortunate archive/tar kludge will (hopefully) go away once we'll switch to Go 1.11.

**Comment by kolyshkin** [comment]
> We should open a PR upstream to make the cleaning optional 

Or maybe add an exclusion list to it, i.e. be able to tell it some directories in `vendor/` are not to be managed by vndr.

**Pull request closed without merging**
