### PR TITLE
Remove userland proxy

### PR DESCRIPTION
**Pull request by icecrime**
This builds up on @phemmer work and comments (#6810, [`libcontainer's` #62](https://github.com/docker/libcontainer/pull/62)).

A few notes on the implementation:
- A new `--route-localnet` daemon flag was added to control the `net.ipv4.route_localnet` flag: it is _very_ succinctly documented, so maybe one of you will want to come up with a nice explanation paragraph for `docs/sources/articles/networking.md`.
- The new [iptable `POSTROUTING` rule](https://github.com/docker/docker/pull/6810#issuecomment-49370841) is not depending on any command line flag (I don't believe it has to be).
- Integration tests cover both container -> container communication through the host IP and host -> container communication through localhost.

### CODE REVIEW

**Comment by ikalnitsky** [comment]
Hi guys! The userland proxy is really weird and I'd like to see an option to disable it. Are there some plans about merging this patch? Or do you have another approach?

**Comment by LK4D4** [comment]
@ikalnitsky We too, but hairpin nat seems not working on CentOS :(

**Comment by pwaller** [comment]
@LK4D4 what about doing both the nat and the UL proxy, or was it decided this was a bad idea?

**Comment by LK4D4** [comment]
@pwaller maybe we can introduce `--disable-ul-proxy`

**Comment by phemmer** [comment]
Clarification, hairpin does not work on CentOS/RHEL 6 (issue with older kernels). 7 should be fine.
@pwaller we do use both. the userland proxy is for when the iptables rules don't match.

**Comment by pwaller** [comment]
Ah, I had missed the latter, thanks @phemmer.

**Comment by ikalnitsky** [comment]
Moreover, guys, perhaps it doesn't related to this thread, but I see strange behaviour on my system.

I have two containers. Both have ports bound to the host. I thought, that connectivity between these two containers through host would be performed by NAT, but actually it's performed by userland proxy. See iptables rules:

```
Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       tcp  --  !docker0 any     anywhere             anywhere             tcp dpt:8888 to:172.17.0.3:8888
    0     0 DNAT       tcp  --  !docker0 any     anywhere             anywhere             tcp dpt:9999 to:172.17.0.4:9999
```

Does anybody know why we have `!docker0` in the `in` field? Is it intended behaviour? I expected to see `any` here.

**Comment by phemmer** [comment]
@ikalnitsky Yes, this is the hairpin nat issue. See #6810 and #9269

**Pull request closed without merging**
