### PR TITLE
Make graph.Register take in io.Reader

### PR DESCRIPTION
**Pull request by tonistiigi**
Make graph.Register take in io.ReadCloser so it can close it.

As requested by @stevvooe in #15728

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by stevvooe** [comment]
While we're at it, we can probably get rid of `archive.Archive` and `archive.Reader`.

**Comment by tonistiigi** [comment]
@stevvooe updated

**Comment by stevvooe** [comment]
LGTM

**Comment by aaronlehmann** [comment]
I think this PR should remove the existing calls to `Close`, which I believe are these two:

https://github.com/docker/docker/blob/master/graph/pull_v1.go#L305
https://github.com/docker/docker/blob/master/graph/pull_v2.go#L282

`io.ReadCloser` provides no guarantee that `Close` can be called multiple times: "The behavior of Close after the first call is undefined. Specific implementations may document their own behavior." Even if it's harmless to call `Close` twice, it's not good to have extra calls to `Close` that are expected to fail.

Note that in the pull_v2.go case, it will take some extra logic to make sure `Close` is called exactly once, since there are some paths where `Register` does not get called.

**Comment by aaronlehmann** [comment]
Note that I'm working on a change that will wrap the v1 pull case's reader with a `NopCloser`, so this one will become moot soon.

**Comment by stevvooe** [comment]
@aaronlehmann That is a valid concern. If we take your argument to its conclusion, the `Register` function should really take an `io.Reader` and the caller should be responsible for `Close`, since it request allocation of the resource.

A [cursory look at the standard library](http://golang.org/search?q=io.ReadCloser) shows that `io.ReadCloser` is hardly ever taken as a function or method argument. Instead, it seems to be used as a return type to indicate the resource needs to be closed.

Furthermore, passing an `io.ReadCloser` down a function call stack leaves an ambiguous level responsibility. If you keep passing it down, who's responsibility is it to actually close? It really only makes sense to have the allocator close it and pass `io.Reader` down the stack, unless there are special cases where the caller needs to defer ownership, such as when handing it to a goroutine.

@tonistiigi What do you think?

**Comment by tonistiigi** [comment]
@stevvooe I'm ok either way. I could move the close to the error handlers in `pull_v2` and remove from `pull_v1`, make this a reader or just close this PR.

**Comment by stevvooe** [comment]
@tonistiigi Sorry to take this around a loop. I think we should change `Graph.Register` to take an `io.Reader` and issue the closes in the caller (ie pull_v2, pull_v1).

I know this all seems silly but the resource management gets easier if we get this correct.

**Comment by tonistiigi** [comment]
@stevvooe Updated. Actually made a meaningful change in `import.go`, please check that it's correct.

**Comment by stevvooe** [comment]
LGTM

Based on the `import.go` change, this rabbit hole may go deep... ;)

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
