### PR TITLE
Rest api documentation syntax error

### LINKED ISSUE #16266: Syntax Error REST-API Documentation Example
i think, the follow example on file 

* docker/docs/reference/api/docker_remote_api_v1.21.md
* docker/docs/reference/api/docker_remote_api_v1.20.md
* docker/docs/reference/api/docker_remote_api_v1.19.md
* ...
```
Ulimits: { "Name": "nofile", "Soft": 1024, "Hard", 2048 }}
```
should be
```
Ulimits: { "Name": "nofile", "Soft": 1024, "Hard": 2048 }
```

### PR DESCRIPTION
**Pull request by oprearocks**
Fixes #16266. 

Fixes the typos found in the Remote API docs - _Ulimits_

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM - could you please squash your commits?

**Comment by opreaadrian** [comment]
I've squashed the commits. Never used `squash` before, thanks for pointing out.

**Comment by thaJeztah** [comment]
LGTM, thanks so much!

If you're interested in contributing more, please have a look at our contribution guide, which contains a lot of information (including squashing and rebasing; https://docs.docker.com/project/work-issue/#pull-and-rebase-frequently)

**Comment by opreaadrian** [comment]
Thank you, for such a wonderful tool. I went through the docs again, with a bit more care this time.

**Pull request merged**
