### PR TITLE
Add cpuguy83 to maintainers.people

### PR DESCRIPTION
**Pull request by cpuguy83**
Didn't realize I didn't push this up.
Add myself to MAINTAINERS.people

### CODE REVIEW

**Comment by duglin** [comment]
do you need to change the indents?

**Comment by cpuguy83** [comment]
heh, probably, didn't notice locally.
Thanks.

**Comment by cpuguy83** [comment]
Updated

**Comment by duglin** [comment]
LGTM

**Comment by icecrime** [comment]
OMG how did we miss that. LGTM, ping @crosbymichael!

**Comment by unclejack** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
> OMG how did we miss that.

*cough* https://github.com/docker/docker/pull/10481#issuecomment-85746186 😇

**Pull request merged**
