### PR TITLE
vendor: vishvananda/netlink v1.1.0

### PR DESCRIPTION
**Pull request by thaJeztah**
- vishvananda/netlink: https://github.com/vishvananda/netlink/compare/v1.0.0...v1.1.0
- vishvananda/netns: https://github.com/vishvananda/netns/compare/7109fa855b0ff1ebef7fbd2f6aa613e8db7cfbc0...0a2b9b5464df8343199164a0321edf3313202f7e
- libnetwork: https://github.com/moby/libnetwork/compare/bf2bd42abc0a3734f12b5ec724e571434e42c669...beab24292cb13d13670985fc860215f9e296bd47
- github.com/moby/ipvs: new dependency (was previously part of libnetwork)

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
let me update the title, as it's probably better to describe it as updating netlink v1.1.0 (libnetwork only has minor change)

**Review by AkihiroSuda — APPROVED** [review]
LGTM (if green)

**Comment by thaJeztah** [comment]
@cpuguy83 @arkodg ptal

**Review by arkodg — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
