### PR TITLE
[Builder] Fix leaked layers when multi-stage build uses the same ID

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tonistiigi @simonferquel PTAL

**Comment by tonistiigi** [comment]
LGTM

Need to find a way to write tests for this case as we had an identical issue in the last version.

**Comment by dnephin** [comment]
I was thinking about how to test it. I think that it should be an assertion as part of the setup/teardown for the builder test suite. On every test it should compare the number of layers before the test runs, to the number after images are cleaned up. If they are ever different the test should fail. We would need to move all builder tests into a new `BuilderSuite`, but I think we should do that anyway.

WDYT?

**Comment by tonistiigi** [comment]
@dnephin SGTM

**Comment by thaJeztah** [comment]
@tonistiigi should the test be part of this PR, or ok as a follow up?

**Comment by tonistiigi** [comment]
@thaJeztah This was actually already merged as part of https://github.com/moby/moby/pull/33735 where we first so this happening.

**Comment by thaJeztah** [comment]
oh, I see; closing this one, because it's in https://github.com/moby/moby/pull/33735 indeed

**Pull request closed without merging**
