### PR TITLE
get os arch for release script

### PR DESCRIPTION
**Pull request by jessfraz**
this is because of the arm changes so dont cherry pick it into 1.10 or anything ;)

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by estesp** [comment]
kind of like `build-rpm` and `build-deb`, don't you also need the "integration daemon start" bundle to run before your "query daemon OS/arch" bundle runs?  Given it looks like `PACKAGE_ARCH` is going to be based on `DOCKER_ENGINE_OSARCH`, if a daemon isn't running, I don't think that will have a value, and so you end up with the default **amd64**

Of course I may be reading this all wrong, but that's what it looks like to me.

**Comment by jfrazelle** [comment]
nah this doesnt use docker in docker so really im just getting the default, dont worry i tested it doesnt error out

**Comment by jfrazelle** [comment]
all i need is the defeault we will never release from a non amd64 machine, even arm packages can be released from amd64 ;)

**Comment by jfrazelle** [comment]
merging bc i need to release experimental

**Comment by estesp** [comment]
No problem. Was just trying to understand the purpose; I'm sure you know what you're doing :)

**Comment by jfrazelle** [comment]
Let's be honest, I dont hahah

On Thu, Feb 11, 2016 at 3:10 PM, Phil Estes <notifications@github.com>
wrote:

> No problem. Was just trying to understand the purpose; I'm sure you know
> what you're doing :)
>
>
>
> Sent from my iPhone
> > On Feb 11, 2016, at 3:12 PM, Jess Frazelle <notifications@github.com>
> wrote:
> >
> > nah this doesnt use docker in docker so really im just getting the
> default, dont worry i tested it doesnt error out
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/20114#issuecomment-183095038>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by tiborvass** [comment]
@jfrazelle except it did use docker in docker for the release :( https://github.com/docker/docker/blob/master/project/RELEASE-CHECKLIST.md#8-publish-release-candidate-rpms-and-debs

**Pull request merged**
