### PR TITLE
Update dockerlinks.md

### PR DESCRIPTION
**Pull request by bgazzera**
Not much: There was a missing command to rerun the web container.

Signed-off-by: Bruno Gazzera bgazzera@paginar.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by bgazzera** [comment]
Not much: There was a missing command to rerun the web container.

Signed-off-by: Bruno Gazzera <bgazzera@paginar.com>

**Comment by bgazzera** [comment]
Not much: There was a missing command to rerun the web container.

Signed-off-by: Bruno Gazzera bgazzera@paginar.com

**Comment by thaJeztah** [comment]
@bgazzera the sign-off must be part of the commit-message itself, not the comment here on GitHub.

Going by the name of your branch (`patch-1`), you've made this PR via the GitHub web-interface. Unfortunately, (afaik) the web-interface doesn't allow you to amend your commit-message. To follow the instructions (https://github.com/docker/docker/pull/10156#issuecomment-70365802), you need a local checkout on  your computer.

(If you're unable to do this, one of the maintainer may be able to take over your PR)

**Comment by bgazzera** [comment]
@thaJeztah thank you for your help, 
I forked, cloned in my desktop, commited using the disclaimer and started a new PR #10167
I hope I got it right this time. Is there anything else I should do to clean-up the previous PR?

**Comment by thaJeztah** [comment]
Thanks for making the effort to fix the PR! If you can close this one (you should be able tom because you created it), it should be fine. Optionally, mention something like "closing, replaced by #10167"

**Comment by bgazzera** [comment]
closing, replaced by #10167"

**Pull request closed without merging**
