### PR TITLE
bash completion for `docker {run,create} --userns`

### PR DESCRIPTION
**Pull request by albers**
Ref: #20111

ping @sdurrheimer for zsh completion

### CODE REVIEW

**Comment by sdurrheimer** [comment]
Thx, this option is also available for `docker create` (https://github.com/docker/docker/blob/master/docs/reference/commandline/create.md)

**Comment by albers** [comment]
@sdurrheimer This PR also covers `docker create` because both commands share the completion function. Thanks for the notice, though.

**Comment by vdemeester** [comment]
LGTM 🐵

**Comment by albers** [comment]
@vdemeester updated commit message & PR title to reflect @sdurrheimer's comment about this also being valid for `create`

**Comment by calavera** [comment]
LGTM

**Pull request merged**
