### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by jamiehannaford**

### CODE REVIEW

**Comment by MHBauer** [comment]
In my understanding, the link is not broken. They aren't supposed to work in github.

**Comment by jamiehannaford** [comment]
@MHBauer Well, it's definitely broken on Github - which is where I discovered it. What page on `docs.docker.com` is it supposed to be on? I can't find it outside of Github.

**Comment by MHBauer** [comment]
I'm still learning, but I don't think that section is public yet. You can see what it looks like by running `make docs` if you have your dev environment set up.

**Comment by thaJeztah** [comment]
Correct, the links are created to that they work on docs.docker.com. Unfortunately, that means (some) links don't work on GitHub.

I'm going to close this issue, because this is intended. Thanks for your contribution, though, @jamiehannaford, much appreciated!

**Pull request closed without merging**
