### PR TITLE
Bump version to 1.11.2

### PR DESCRIPTION
**Pull request by mlaventure**

### CODE REVIEW

**Comment by bukzor** [comment]
This is the problem:

```
17:46:30 W: Failed to fetch http://llvm.org/apt/jessie/dists/llvm-toolchain-jessie-3.8/main/binary-amd64/Packages  404  Not Found
```

**Comment by mlaventure** [comment]
Yes, LLVM disabed their APT repo for now.

**Comment by icecrime** [comment]
LGTM (ignoring CI)

**Comment by thaJeztah** [comment]
LGTM (ignoring CI as well)

@mlaventure let me know if this can be merged, or we should wait so that it can be rebased on top of all other changes

**Comment by mlaventure** [comment]
We'll need to cherry pick the clang version change to be able to generate
the release.

**Comment by thaJeztah** [comment]
@mlaventure cherry pick is here; https://github.com/docker/docker/pull/23164

**Comment by PikachuEXE** [comment]
Seems missing CHANGELOG for this version (not very related to this issue though)

**Comment by icecrime** [comment]
@PikachuEXE Everything should be there, what do you think is missing? https://github.com/docker/docker/blob/v1.11.2/CHANGELOG.md

**Comment by PikachuEXE** [comment]
Sorry
I thought `master` is always got the latest CHANGELOG
Forgot to change the tags
Thanks for providing the link

**Comment by thaJeztah** [comment]
@PikachuEXE yes, I marked the changelog changes to be merged back to master, but didn't come round to it yet, I'll open a PR today :+1:

**Pull request merged**
