### PR TITLE
Bump SwarmKit to 831df679a0b8a21b4dccd5791667d030642de7ff

### PR DESCRIPTION
**Pull request by thaJeztah**
Full diff: https://github.com/docker/swarmkit/compare/49a9d7f6ba3c1925262641e694c18eb43575f74b...831df679a0b8a21b4dccd5791667d030642de7ff

Changes included:

- https://github.com/docker/swarmkit/pull/2523 Ingress network should not be attachable
- https://github.com/docker/swarmkit/pull/2535 [manager/state] Add fernet as an option for raft encryption
- https://github.com/docker/swarmkit/pull/2541 Log GRPC server errors
- https://github.com/docker/swarmkit/pull/2542 Log leadership changes at manager level
- https://github.com/docker/swarmkit/pull/2564 [state/raft] Increase raft ElectionTick to 10xHeartbeatTick
- https://github.com/docker/swarmkit/pull/2568 Remove the containerd executor
- https://github.com/docker/swarmkit/pull/2570 agent: backoff session when no remotes are available
  - addresses https://github.com/moby/moby/issues/36683
- https://github.com/docker/swarmkit/pull/2573 [ca/manager] Remove root CA key encryption support entirely
- https://github.com/docker/swarmkit/pull/2578 Fix agent logging race (fixes https://github.com/docker/swarmkit/issues/2576)
- https://github.com/docker/swarmkit/pull/2571 Adding logic to restore networks in order
  - Addresses network restore in leader change scenarios.

ping @anshulpundir @fcrisciani @stevvooe

### CODE REVIEW

**Comment by thaJeztah** [comment]
whoops, forgot to add the new dependency; fixing

**Comment by thaJeztah** [comment]
Attaching to ingress network is now forbidden, so looks like there’s a test to update;

```
TestServiceWithIngressNetwork (1.92s)
20:31:48 	daemon.go:283: [d316291918db3] waiting for daemon to start
20:31:48 	daemon.go:315: [d316291918db3] daemon started
20:31:48 	service_test.go:94: assertion failed: error is not nil: Error response from daemon: rpc error: code = InvalidArgument desc = Service cannot be explicitly attached to the ingress network "ingress"
20:31:48 	daemon.go:273: [d316291918db3] exiting daemon

**Comment by thaJeztah** [comment]
Updated to include the changes from https://github.com/moby/moby/pull/36767

Extra changes: https://github.com/docker/swarmkit/compare/82b9ea7031648c9c7aba4f7659b90f9fc692469d...831df679a0b8a21b4dccd5791667d030642de7ff


- https://github.com/docker/swarmkit/pull/2573 [ca/manager] Remove root CA key encryption support entirely
- https://github.com/docker/swarmkit/pull/2578 Fix agent logging race (fixes https://github.com/docker/swarmkit/issues/2576)
- https://github.com/docker/swarmkit/pull/2571 Adding logic to restore networks in order
  - Addresses network restore in leader change scenarios.

**Review by abhi — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
SGTM

**Review by boaz0 — APPROVED** [review]
LGTM :taco:

**Review by yongtang — APPROVED** [review]
LGTM

**Review by anshulpundir — APPROVED** [review]

**Comment by thaJeztah** [comment]
Janky failures are flaky tests: https://jenkins.dockerproject.org/job/Docker-PRs/48842/console (tracked through https://github.com/moby/moby/issues/36501)



```
19:52:28 ----------------------------------------------------------------------
19:52:28 FAIL: docker_api_swarm_service_test.go:32: DockerSwarmSuite.TestAPIServiceUpdatePort
19:52:28 
19:52:28 [d5d823d4da0c4] waiting for daemon to start
19:52:28 [d5d823d4da0c4] daemon started
19:52:28 
19:52:28 docker_api_swarm_service_test.go:38:
19:52:28     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
19:52:28 docker_utils_test.go:452:
19:52:28     c.Assert(v, checker, args...)
19:52:28 ... obtained int = 0
19:52:28 ... expected int = 1
19:52:28 
19:52:28 [d5d823d4da0c4] exiting daemon
19:52:40 

20:17:34 ----------------------------------------------------------------------
20:17:34 FAIL: docker_cli_swarm_test.go:1610: DockerSwarmSuite.TestSwarmPublishDuplicatePorts
20:17:34 
20:17:34 [d10dfa3b5f8a5] waiting for daemon to start
20:17:34 [d10dfa3b5f8a5] daemon started
20:17:34 
20:17:34 docker_cli_swarm_test.go:1618:
20:17:34     // make sure task has been deployed.
20:17:34     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
20:17:34 docker_utils_test.go:452:
20:17:34     c.Assert(v, checker, args...)
20:17:34 ... obtained int = 0
20:17:34 ... expected int = 1
20:17:34 
20:17:34 [d10dfa3b5f8a5] exiting daemon
20:17:37 
```

**Pull request merged**
