### PR TITLE
split compose deploy from deploy.go

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

split compose deploy from deploy.go, to better the code file organization. 
In the code base, we can be more clear that there are two kinds of deploy type for command `docker stack deploy`.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by AkihiroSuda** [comment]
failure seems legit
```
00:07:00.102 # github.com/docker/docker/cli/command/stack
00:07:00.103 ..\..\cli\command\stack\deploy.go:5: imported and not used: "os"
00:07:00.103 ..\..\cli\command\stack\deploy_composefile.go:17: imported and not used: "github.com/docker/docker/vendor/github.com/pkg/errors"
00:07:00.103 ..\..\cli\command\stack\deploy_composefile.go:21: undefined: command in command.DockerCli
00:07:00.103 ..\..\cli\command\stack\deploy_composefile.go:138: undefined: command in command.DockerCli
00:07:00.103 ..\..\cli\command\stack\deploy_composefile.go:160: undefined: command in command.DockerCli
00:07:00.103 ..\..\cli\command\stack\deploy_composefile.go:187: undefined: command in command.DockerCli
00:07:00.103 ..\..\cli\command\stack\deploy_composefile.go:224: undefined: command in command.DockerCli
00:07:00.103 ..\..\cli\command\stack\deploy_composefile.go:249: undefined: command in command.RetrieveAuthTokenFromImage
```

**Comment by allencloud** [comment]
Thanks for your feedback. @AkihiroSuda  updated, now.

**Review by LK4D4 — APPROVED** [review]
LGTM

**Pull request merged**
