### PR TITLE
Turn off GC during `make binary`

### PR DESCRIPTION
**Pull request by cpuguy83**
With GC:

```
real    1m14.221s
user    2m50.900s
sys 2m36.140s

real    1m12.348s
user    2m50.260s
sys 2m31.760s

real    1m11.747s
user    2m45.730s
sys 2m31.240s
```

No GC:

```
real    0m51.511s
user    1m35.400s
sys 1m4.390s

real    0m47.598s
user    1m30.110s
sys 0m49.160s

real    0m49.929s
user    1m31.450s
sys 0m53.290s
```

### CODE REVIEW

**Comment by cpuguy83** [comment]
No idea the adverse affects of this, but sure trims off a fair amount of time in dev cycle.

ping @tianon

**Comment by tianon** [comment]
Isn't there a golang/go issue or thread somewhere that discusses this problem/hack we can link to so we don't forget the context for it later?

I'm generally +1 but I'd like us to also link to something from upstream about the issue and why this changes things.

**Comment by cpuguy83** [comment]
I haven't seen a discussion on it, couldn't find one either.
Maybe @LK4D4 ?

**Comment by jfrazelle** [comment]
DAMN

**Comment by unclejack** [comment]
You'll want to use GOGC=1000 or something like that instead. Someone might run out of RAM with GOGC=off.

**Comment by tianon** [comment]
Huh, could've sworn I read a thread about disabling the garbage collector
during compilation upstream, but I can't find it now either.

**Comment by MHBauer** [comment]
I remember this discussion, not sure if there was a PR or issue, it was around the time of go1.5 switching. https://botbot.me/freenode/docker-dev/2015-10-27/?msg=52864230&page=3

**Comment by LK4D4** [comment]
I'm always compiling with `GOGC=off` :) Never saw any problems.

**Comment by cpuguy83** [comment]
How about `export GOGC=${DOCKER_GOGC:-1000}` instead?

**Comment by tianon** [comment]
In that case, why introduce DOCKER at all and not just set a default for
GOGC itself? :smile:

**Comment by cpuguy83** [comment]
@tianon In case people use it for other things.

**Comment by cpuguy83** [comment]
"it" being the `GOGC` var.

**Comment by tianon** [comment]
Ok, I suppose that's fair. :smile:  Maybe we should go more explicit and
call it the DOCKER_BUILD_GOGC so it's clear it doesn't apply to Docker's
runtime?

**Comment by cpuguy83** [comment]
Makes sense to me.

**Comment by cpuguy83** [comment]
Updated, also added a passthrough for the `DOCKER_INCREMENTAL_BUILD` var

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
