### PR TITLE
Vendor in libnetwork changes

### PR DESCRIPTION
**Pull request by arkodg**
Vendor in IP6Tables fixes

https://github.com/moby/libnetwork/pull/2600
https://github.com/moby/libnetwork/pull/2603

Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by arkodg** [comment]
cc @bboehmke @tiborvass

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
@arkodg this fixes https://github.com/moby/moby/issues/41774 ?

**Comment by bboehmke** [comment]
@thaJeztah I think moby/libnetwork#2604 is also required to fix #41774 completely. 

The exception from the description is fixed with this one but ip6tables would still not be usable (see the comments).

**Pull request merged**
