### PR TITLE
Add Aliyun mirror support to hack/install.sh

### PR DESCRIPTION
**Pull request by Hyzhou**
Signed-off-by: hyzhou.zhy <hyzhou.zhy@alibaba-inc.com>

Add Aliyun mirror support to hack/install.sh
I received an email today, The https transformation for Aliyun mirror is complete. @friism @thaJeztah 

we will just run this:
```
curl -sSL https://get.docker.com/ | sh -s -- --mirror Aliyun
```

Tested in Aliyun ECS：Ubuntu 16.04、CentOS7.2

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Hyzhou** [comment]
@thaJeztah What about this pull request now? :)

**Comment by thaJeztah** [comment]
Sorry for the delay, @Hyzhou, let me try to ping @dmp42 @andrewhsu again - PTAL

**Comment by unclejack** [comment]
Is there a reason why this has to be modified for every provider? Perhaps there should be a way to specify the mirror as a string which represents the URL where the mirror can be found?

I have some use cases for using a local mirror. It wouldn't always be the same mirror. Even without my particular use case, it'd be nice to not have to add a special case for every single mirror. I can imagine others might want to use their own mirror as well.

**Comment by thaJeztah** [comment]
@unclejack if you want to use your own mirror, it's probably best to write a custom script; I don't think we should allow setting any arbitrary mirror in the install script

**Comment by unclejack** [comment]
@thaJeztah I understand that. However, I can't say adding mirrors one by one is better either.

**Comment by dmp42** [comment]
@unclejack China is special. I don't think we should add more in there.

@thaJeztah I think this is fine and we should merge this, unless there is an issue?

+ @friism

**Review by thaJeztah — APPROVED** [review]
ok, let's go ahead; sorry for the delay 😊 

LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 👼

**Pull request merged**
