### PR TITLE
Enabled GitHub Flavored Markdown

### PR DESCRIPTION
**Pull request by moxiegirl**
GitHub flavored markdown is now supported for links and images. This is supported from Sven's work patching Hugo. Also, ran LinkChecker and FileResolver which are the validation tools he is working on currently for use with Leeroy. Yay! First step toward even better docs...thanks Sven for all your hard work.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @SvenDowideit  -- Worked really well Sven!  I ran it only on the docker/docker material the sub projects tend to use `master` at release time.  This let's us pull this into `docker/docker:master` and then fix only the broken bits in the other repos.

Nice job getting that image checker in there too.  That worked really well.  Found a missing file and everything.

**Comment by thaJeztah** [comment]
Awesome! Do the current links also still work, or is extra attention needed reviewing PR's?

**Comment by moxiegirl** [comment]
Hi @thaJeztah right now, if you run `make docs` on this you get errors returned on the Hugo build. Those errors are coming from downstream projects such as compose, machine etc. After this is pulled, you can test a new `docker/docker` PR by:

1.  Pulling the PR branch.
2.  Editing the `Dockerfile` to build only docker/docker
3.  Running `make docs`

The make should return only one error from `deprecated.md` --- I need to chat with someone to fix that one.

Once all the subprojects are updated. The procedure will be adjusted slightly. @SvenDowideit is working on automating the check so eventually no procedure is necessary except checking build validation.

**Comment by moxiegirl** [comment]
@thaJeztah The goal is to get this one pulled before the RC because it has such a large impact.  @SvenDowideit hopefully should come on today to check as well.

**Comment by SvenDowideit** [comment]
yay LGTM - there are some `https://docs.docker.com` links in here - but they're all from external projects, so that'll clear up when we make changes to the build pipeline.

**Comment by thaJeztah** [comment]
Thanks Sven!

Just arrived at SFO :-)

---

**Pull request merged**
