### PR TITLE
names-generator: use local random instance

### PR DESCRIPTION
**Pull request by ahmetb**
Minor change: Instead of seeding/polluting the global `rand.Random` instance,
creating a local `rand.Random` instance which provides the same level of randomness.

Signed-off-by: Ahmet Alp Balkan

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by estesp** [comment]
Actually, it would be better to add your rand instance initialization to an `init()` func, as you are seeding and re-seeding on every single call to get a name, when the proper use of an RNG is to seed once per instance of a program and then use until program exit.  I know you didn't introduce that, but if we are fixing it, might as well go the distance :)

**Comment by jfrazelle** [comment]
I tried to find a "go the distance" gif but chrome keeps crashing so yeah

**Comment by thaJeztah** [comment]
Yes, better make this file look really good in preparation of your big boss making his first contribution, @ahmetalpbalkan :smile:

Perhaps we really should open an issue "Bill Gates is missing in names generator", and ask @shykes to ping him on Twitter?

**Comment by ahmetalpbalkan** [comment]
@estesp I think seeding the global random is a bad idea. Imagine in my personal project I imported namesgenerator package and assumy my project has tests. Now because this code is executed my test runs will never generate random IDs consistently and it'll be notoriously hard to consistenly repro (eg some random length string causes a bug)

Anyway I think we should almost never seed global rand. If docker really wants to do that that should be in the file where the main() is. Otherwise it's a terrible idea to seed the global rand in a package that could be imported by others. 

@thajeztah the big boss knows me, I can get it done lol. I was just jokin' about adding gates do not take it seriously :D

**Comment by estesp** [comment]
I think we are discussing two different things--you moved from using the global random to a instance created just for the names generator: that is goodness from everything I know (which arguably may not be worth much!)

What I'm adding as an extra recommendation is that instead of creating a new instance every time someone asks for a name, put that in an `init()` inside the names generator package.  You won't be seeding the global rand, you will simply create one instance that is used every time you call the name generator.  Of course it would require a package level var that is setup in `init()` and then used in `GetRandomName()`

**Comment by ahmetalpbalkan** [comment]
@estesp ah yeah now I got you, sorry about that. I think since it's used only in one place and initializing Random is cheap, we can stick with this one don't you think?

**Comment by estesp** [comment]
It's definitely not that important--there are slight chances that in a very tight loop you end up with the same seed (http://stackoverflow.com/questions/12321133/golang-random-number-generator-how-to-seed-properly), but for this use case seems highly unlikely.

I prefer my recommendation from a "if someone else looked at this would it be a good example for using Golang rand" perspective, but I'm not going to live and die on it.. or hey, maybe we can just go with this and I get a free PR to refactor out to a package var? :) :)

**Comment by ahmetalpbalkan** [comment]
@estesp you're definitely right. I didnt think about the tight loop. we shouldnt rely on precision of the time we get from the system.  In fact this changes everything. I'll declare a package-scoped rand and update this PR.

**Comment by ahmetalpbalkan** [comment]
@estesp updates this. please review.

**Comment by estesp** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
