### PR TITLE
[Carry] Fix a panic where RUN [] would be supplied

### PR DESCRIPTION
**Pull request by tiborvass**
Closes #9989

/cc @erikh @duglin

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
whoa you all not going to wait for drone

**Comment by crosbymichael** [comment]
In @tiborvass I Trust

**Comment by tiborvass** [comment]
@crosbymichael famous last words

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
would have been funny if it failed on random racy test

**Comment by tiborvass** [comment]
@jfrazelle I had a 50/50 chance :)

**Comment by erikh** [comment]
Thank you so much @tiborvass!

**Pull request merged**
