### PR TITLE
Adds 'name' filter to the CLI reference.

### LINKED ISSUE #11309: Add "name" to the list of event issues
The event issues include a "name" filter. Add this to the list of event filters. Also fix the filtering list layout which displays like this:

image

### PR DESCRIPTION
**Pull request by RickWieman**
Also sorts the filter list and fixes the rendering of the bullet list.
Fixes #11309.

### CODE REVIEW

**Comment by MartijnDwars** [comment]
LGTM (not a maintainer)

**Comment by moxiegirl** [comment]
Thanks @RickWieman for the quick fix!

**Comment by moxiegirl** [comment]
LGTM

**Comment by albers** [comment]
Does this filter really exist?
`docker events --filter name=foo` reports events for *all* containers, just like `docker events --filter foo=bar` does.

**Comment by moxiegirl** [comment]
Added to master 7 days ago docker/events/events.go

**Comment by albers** [comment]
I tried this with the current dev state. Can you please post a usage example?

**Comment by albers** [comment]
If you are referring to e0fa57737879681a8888de992eb6d2f0e624da74, this seems to only add support for container names as an argument to the container filter. It does not introduce a new name=xxx filter.

**Pull request merged**
