### PR TITLE
Fix syntax errors in bash-completion (Closes: #23483)

### LINKED ISSUE #23483: bash-completion fails syntax check
~~~~
$ bash -n contrib/completion/bash/docker
contrib/completion/bash/docker: line 514: syntax error near unexpected token `('
contrib/completion/bash/docker: line 514: `             syslog-tls-@(ca-cert|cert|key))'
~~~~

~~~~
$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
~~~~

FYI @albers.

### PR DESCRIPTION
**Pull request by onlyjob**
Fixes #23483.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @albers PTAL :smile:

**Comment by albers** [comment]
see https://github.com/docker/docker/issues/23483#issuecomment-225545739

**Comment by thaJeztah** [comment]
closing per https://github.com/docker/docker/issues/23483#issuecomment-225567797

Thanks for contributing though, @onlyjob, it's appreciated

**Comment by thaJeztah** [comment]
aaaand reopening, per https://github.com/docker/docker/issues/23483#issuecomment-225705631

**Comment by thaJeztah** [comment]
LGTM

**Comment by albers** [comment]
LGTM (IANAM).

**Comment by thaJeztah** [comment]
counting @albers' LGTM, merging

**Comment by onlyjob** [comment]
Thank you. :)

**Pull request merged**
