### PR TITLE
ppc64le: remove go SHA check

### PR DESCRIPTION
**Pull request by tophj-ibm**
Makes it consistent with other Dockerfiles.

Signed-off-by: Christopher Jones tophj@linux.vnet.ibm.com

### CODE REVIEW

**Comment by LK4D4** [comment]
At least it compiled ok.
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by tophj-ibm** [comment]
@thaJeztah can I get this added to the next 1.12.x milestone 🙏  (I don't see a 1.12.2 one)? This fixes a major issue in 1.12 on power when building dind with a go version that isn't 1.6.2.

**Comment by justincormack** [comment]
@tophj-ibm marked it for cherry pick. No idea when/if there will be a 1.12.2 release at present.

**Comment by tophj-ibm** [comment]
thanks! just wanted to make sure it would be in if there was

**Pull request merged**
