### PR TITLE
builder: warning if `yum` is attempted on Overlay

### PR DESCRIPTION
**Pull request by AkihiroSuda**
#### What did you do?

As already mentioned in #10180, `yum` does not work properly with the Overlay storage unless the `yum-plugin-ovl` package is installed.
This commit makes the builder print a warning if `yum` is attempted on the Overlay storage.

I also updated the doc and a PNG image, but I'm not sure how to edit the PNG image properly..
So please let me know whether there is the source SVG/PPT/ODP for the PNG image.

Off-topic: it seems that we need consideration for color-blinded persons.

#### How did you do it?

`NewBuilder()` caches the result of `backend.SystemInfo()`.
`Builder.run()` prints a warning if `systemInfo.Driver` is `overlay` and `runConfig.Cmd` contains `yum`. The warning is printed only once.
#### How do I see it or verify it?

Prepare a Dockerfile like this:

``` dockerfile
FROM centos:centos6
RUN yum install -y sudo
RUN yum install -y perl
```

Make sure the `[Warning]` is printed (only when running with the Overlay driver).

```
$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM centos:centos6
 ---> 2e4f3f04a056
Step 2 : RUN yum install -y sudo
 ---> Running in 9a001586afe7
 ---> [Warning] On Overlay, `yum` does not work properly unless the `yum-plugin-ovl` package is installed.For further information, please refer to https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/
Loaded plugins: fastestmirror
Setting up Install Process
...
Installed:
  sudo.x86_64 0:1.8.6p3-20.el6_7                                                

Complete!
 ---> d721b5cbb456
Removing intermediate container 9a001586afe7
Step 3 : RUN yum install -y perl
 ---> Running in 1eade960f3ab
Loaded plugins: fastestmirror
Setting up Install Process
..
Running Transaction
  Installing : 1:perl-Pod-Escapes-1.04-141.el6_7.1.x86_64                   1/6 
  Installing : 1:perl-Module-Pluggable-3.90-141.el6_7.1.x86_64              2/6 
  Installing : 3:perl-version-0.77-141.el6_7.1.x86_64                       3/6 
  Installing : 4:perl-libs-5.10.1-141.el6_7.1.x86_64                        4/6 
  Installing : 1:perl-Pod-Simple-3.13-141.el6_7.1.x86_64                    5/6 
  Installing : 4:perl-5.10.1-141.el6_7.1.x86_64                             6/6

Rpmdb checksum is invalid: dCDPT(pkg checksums): perl-Pod-Simple.x86_64 1:3.13-141.el6_7.1 - u
```
#### A picture of a cute animal (not mandatory but encouraged)

https://upload.wikimedia.org/wikipedia/commons/f/f0/Emperor-pubs_hg.jpg
emperor-pubs_hg

Update #10180

Signed-off-by: Akihiro Suda suda.akihiro@lab.ntt.co.jp

### CODE REVIEW

**Comment by vdemeester** [comment]
Hum it doesn't feel right to me. These warning makes some check in the code that should not be there. The builder is and should be not aware of the inner working of the container and thus package manager or else..

I'm :-1: on this change.

**Comment by unclejack** [comment]
This isn't the right thing to do. Having build command, storage driver and distribution specific warnings/checks is wrong.

This issue needs to be addressed in the overlay code to fix the underlying problem.

NOT LGTM

**Comment by AkihiroSuda** [comment]
@vdemeester @unclejack Thank you for the comment.

Instead, I'm considering send a PR to [CentOS/sig-cloud-instance-images](https://github.com/CentOS/sig-cloud-instance-images) like this:

```patch
--- Dockefile.OLD       2016-03-01 09:09:22.863889323 +0000
+++ Dockefile   2016-03-01 09:10:19.427800883 +0000
@@ -6,6 +6,7 @@
     license="GPLv2" \
     build-date="2016-02-17"
 
+ONBUILD RUN echo [Warning] On Overlay, `yum` does not work properly unless the `yum-plugin-ovl` package is installed.For further information, please refer to https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/
 # Default command 
 CMD ["/bin/bash"]
```

Can I hear your comments about this?
Also, please review the document files?

**Comment by unclejack** [comment]
All issues should be addressed where it makes sense - in the Docker overlay code if they're bugs caused by the Docker Overlay storage driver or in the kernel code for Overlay.

Workarounds are good only until the proper fix is implemented.

**Pull request closed without merging**
