### PR TITLE
Migrate info command to cobra

### PR DESCRIPTION
**Pull request by tkopczynski**
Migrate `info` command to cobra (in file `api/client/system/info.go`).

Part of resolving #23211 

Signed-off-by: Tomasz Kopczynski tomek@kopczynski.net.pl

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by vdemeester** [comment]
@tkopczynski needs a rebase :angel:

**Comment by tkopczynski** [comment]
@vdemeester done 
It turns out that Docker is such an active project that I had to make rebase twice in just a couple of minutes ;)

**Comment by cpuguy83** [comment]
LGTM assuming janky is happy.

**Comment by thaJeztah** [comment]
oh, sorry @tkopczynski, this needs another rebase

**Comment by tkopczynski** [comment]
@thaJeztah Should be better now :)

**Comment by LK4D4** [comment]
@tkopczynski thanks!

**Pull request merged**
