### PR TITLE
Fixing bug in AttachStreams that would fail to close StdIn

### PR DESCRIPTION
**Pull request by swernli**
@jhowardmsft @darrenstahlmsft 
During a docker exec, if no TTY is specified, the code would still leave stdin open instead of closing it.  This change adds handling for the execConfig TTY bool that mirrors what is already done for container config.

Signed-off-by: Stefan J. Wernli swernli@microsoft.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Lots of test failures on the Linux side - some are in exec. Not sure if this change relates to those failures.

**Comment by swernli** [comment]
The latest version of the changes makes this behavior Windows only.  I left a TODO comment to indicate this should be considered as a possible fix for Linux.

**Comment by jhowardmsft** [comment]
LGTM if Janky passes. For others - I discussed whether to change the behaviour on all OSs but feel due to known failures hit with this change on Linux, the right thing for now is to annotate that with a TODO. This does stop the deadlock we were seeing on Windows.

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
