### PR TITLE
Prefix / is ignored when container is renamed

### PR DESCRIPTION
**Pull request by brahmaroutu**
Addresses #10996

Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
This is breaking rename test in docker-py, but it seems like this would make the rename behavior more consistent.

**Comment by LK4D4** [comment]
ping @shin-

**Comment by shin-** [comment]
@tianon How should we proceed? Do I create a branch on docker/docker-py with the test change and merge later?

**Comment by brahmaroutu** [comment]
@shin- will it be possible to check both cases for now? name=="hong_meiling" || name=="/hong_meiling"

**Comment by shin-** [comment]
https://github.com/docker/docker-py/pull/508

**Comment by jfrazelle** [comment]
@shin- you rock!

**Comment by jfrazelle** [comment]
@brahmaroutu can you pull in @shin- commit from https://github.com/docker/docker/pull/11068 and then yours will pass

**Comment by jfrazelle** [comment]
then we can merge both at the same time

**Comment by jfrazelle** [comment]
you can cherry-pick from his repo ;)

**Comment by brahmaroutu** [comment]
@jfrazelle Please see if this works.

**Comment by jfrazelle** [comment]
build looks good! great! LGTM ping @tianon for Dockerfile changes

**Comment by tianon** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
