### PR TITLE
Windows: Fix docker cp

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This fixes docker cp to work on Windows when using the windowsfilter storage driver. It is yet another instance of golang not supporting volume file paths which are required by the filter.  Note I have deliberately not factored this out into platform files as I want the VFS-on-Windows development capability to use filepath.Rel.

### CODE REVIEW

**Comment by calavera** [comment]
Is there a way we could have a test for this, even if it doesn't run? I'm guessing at some point we'll have a windows daemon running on CI and it would be great to have some regression tests there to validate our assumptions.

Can you elaborate on `I want the VFS-on-Windows development capability to use filepath.Rel.`? Sorry, I'm slightly slow this morning.

**Comment by jhowardmsft** [comment]
@calavera We have a new hire starting next week who is going to be focusing on the Windows test part of this, and I already have a long list of tests which need adding for Windows CI. I can add it to that list so we can start things running.  For the VFS bit - during the bring up of Docker daemon on Windows, Windows containers didn't exist. Neither did the filter storage driver. So I used VFS with the exec driver initially just launching a process outside of a container, but now HCSShim supports 'dummy mode' (is an exec driver option) which effectively is the same process launcher, just no containers involved. Having a mode in which (some) docker daemon development can be done on Windows without relying on a stable container back end has been extremely useful. That's the fallback case here where filepath.Rel is the right thing to do - no volume paths will be involved there. Hope that makes sense :)

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
