### PR TITLE
Update docs for HTTP_PROXY

### PR DESCRIPTION
**Pull request by icecrime**
Update docs to account for the changes introduced in #10739 (which shouldn't have been merged so fast, my bad).

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM - @fredlf @jamtur01

**Comment by SvenDowideit** [comment]
@icecrime the important thing is to know when the doc needs to be published :)

**Comment by jamtur01** [comment]
LGTM

**Comment by fredlf** [comment]
LGTM

**Pull request merged**
