### PR TITLE
devmapper: Fail to start container if xfs_nospace_max_retries can't be enforced

### PR DESCRIPTION
**Pull request by rhvgoyal**
We just introduced a new tunable dm.xfs_nospace_max_retries. But this tunable
will work only on new kernels where xfs supports this feature. On older
kernels xfs does not allow tuning this behavior.

There are two issues. First one is that if xfsSetNospaceRetries() fails,
it returns error but leaves the device activated and mounted. We should
be unmounting the device and deactivate it before returning.

Second issue is, if docker is started on older kernel, with
dm.xfs_nospace_max_retries specified, then docker will silently ignore the
fact that /sys file to tweak this behavior is not present and will continue.
But I think it might be better to fail initialization of graphdriver and 
docker if user specified storage option can not take effect.

This patch fixes it. After this patch, user will get an error like following
when container is run (if daemon is started with option
dm.xfs_nospace_max_retries)
# docker run -ti fedora bash

docker: Error response from daemon: devmapper: Failed to open file /sys/fs/xfs/dm-5/error/metadata/ENOSPC/max_retries:open /sys/fs/xfs/dm-5/error/metadata/ENOSPC/max_retries: no such file or directory.

Signed-off-by: Vivek Goyal vgoyal@redhat.com

### CODE REVIEW

**Comment by rhvgoyal** [comment]
@crosbymichael @runcom PTAL.

**Comment by crosbymichael** [comment]
@rhvgoyal can you change the error message to help the user know what they did wrong? 

Maybe something to the effect of `You specified dm.xfs_nospace_max_retries but it does not seem to be supported on your system: No such file or directory`

**Comment by rhvgoyal** [comment]
@crosbymichael Sure, will do.

**Comment by rhvgoyal** [comment]
@crosbymichael PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by runcom** [comment]
LGTM (pending tests)

**Comment by thaJeztah** [comment]
relates to https://github.com/docker/docker/pull/26212

**Comment by runcom** [comment]
@rhvgoyal is this (or #26212) fixing any issue present in 1.12.1? or is this just for master (upcoming 1.13)

**Comment by rhvgoyal** [comment]
@runcom, this fix is for 1.13

**Pull request merged**
