### PR TITLE
V2 manifest tarsum cache

### LINKED ISSUE #10269: Slow push against private registry for already uploaded images (due to manifests)
`docker push` in master is painfully slow. Pushing an image that is already pushed to the registry takes 42 seconds!

```
web605 ~ # time docker push docker.core.tf/topface-prod-app:20150122009
The push refers to a repository [docker.core.tf/topface-prod-app] (len: 1)
Sending image list
Pushing repository docker.core.tf/topface-prod-app (1 tags)
Image b18d0a2076a1 already pushed, skipping
Image 25c4824a5268 already pushed, skipping
Image 67b66f26d423 already pushed, skipping
Image 8b1c48305638 already pushed, skipping
Image 511136ea3c5a already pushed, skipping
Image c900195dcbf3 already pushed, skipping
Image 9d9561782335 already pushed, skipping
Image 6b4e8a7373fe already pushed, skipping
Image c27763e1f3e5 already pushed, skipping
Image d5199f68b2fe already pushed, skipping
Image bad562ead0dc already pushed, skipping
Image cf39b476aeec already pushed, skipping
Image 64463062ff22 already pushed, skipping
Image f3529e909ef6 already pushed, skipping
Image fc98f0324f03 already pushed, skipping
Image c44ba4e6e179 already pushed, skipping
Image da662fffdcfc already pushed, skipping
Image 9430c1ba71ec already pushed, skipping
Image 16f0d302f2a1 already pushed, skipping
Image 61cadf3f1b21 already pushed, skipping
Image b729d5ec6bc7 already pushed, skipping
Image faf76117ea89 already pushed, skipping
Image 9bce9f428093 already pushed, skipping
Image 250777f42f02 already pushed, skipping
Pushing tag for rev [9bce9f428093] on {https://docker.core.tf/v1/repositories/topface-prod-app/tags/20150122009}

real	0m42.665s
user	0m0.010s
sys	0m0.010s
```

Manifests are to blame:

```
web605 ~ # time curl -s http://web605:2375/v1.17/images/docker.core.tf/topface-prod-app/manifest?tag=20150122009 > /dev/null

real	0m56.246s
user	0m0.000s
sys	0m0.000s
```

I'm using devicemapper, unfortunately, and a lot of mounts/unmounts happen to calculate manifest. After looking at `perf report` it seems that sha sums are calculated too.

@dmcgowan, any ideas? #9784 introduced manifests.

### PR DESCRIPTION
**Pull request by dmcgowan**
Currently the tarsum is calculated each time a manifest is created, which is needed for every push call. Since the checksum value was added to image json to hold this value, make use of it if the value exists, otherwise compute it and save it.

@vbatts the second commit overwrites the image json value to include the checksum, is there any problem overwriting this value?

Fixes #10269
Depends on #10305

### CODE REVIEW

**Comment by dmp42** [comment]
@icecrime this fixes what is perceived as bad performance regression - which is why I think this should be part of 1.5

**Comment by jfrazelle** [comment]
anyway to have until tests or something?

**Comment by dmp42** [comment]
@jfrazelle probably we can push the same image twice in a row?
@dmcgowan can we add that / does that makes sense?

**Comment by dmcgowan** [comment]
To test this optimization first the manifest must be generated from layers without the checksum, then check that the sum now exists.  The tricky part is that checksum should always exists now with layers created by 1.5.  Should be able to recreate the condition by altering an image json then checking after manifest generating it works.

**Comment by dmp42** [comment]
I would be happy with a test that demonstrates this doesn't break push when this kicks-in.

**Comment by icecrime** [comment]
I think this addresses the comment I had in https://github.com/docker/docker/pull/9784/files#r22365404 so SGTM. Waiting for #10305 / rebase / drone before approving.

**Comment by icecrime** [comment]
@dmcgowan Can you rebase with #10305 merged please?

**Comment by crosbymichael** [comment]
@dmcgowan can you squash your commits because we will have to cherry pick these into the release?

**Comment by dmcgowan** [comment]
I will, can you confirm whether the second commit is safe?  Ideally the value is modified (as the second commit does), but if that is not safe because another system is relying on the json value not being modified (@vbatts can you think of any?), then I would like to at least get the first commit merged.

**Comment by crosbymichael** [comment]
I guess if there is a question if one commit should be merged and one commit not, we should open two PRs

**Comment by vbatts** [comment]
@dmcgowan I realize that having a checksum of the image layer by itself is nice and having that inside the layer.json is great. But for a image v1 layer, the calculated TarSum checksum is the layer.tar, with the `[]byte` payload of the raw json added on the final `Sum()` call. So if this json payload is being altered, then checksums will no longer validate. This is the assumption used for tools like `dockertarsum` (https://github.com/vbatts/docker-utils)
The runtime config of the layer is stored there. There must be assurance that the runtime config has not been tampered with.

**Comment by dmcgowan** [comment]
@vbatts understood, would this checksum better be stored in separate file similar to what was done for size?  Based on this I think I should strip out the save commit from this PR as Michael suggested and create a new one for saving.  We can discuss whether it should be stored separately in that PR.

**Comment by icecrime** [comment]
LGTM.

@vbatts Are you ok with it now that the json overriding part was removed?
@dmp42 @dmcgowan Do we feel this is sufficient to solve the performance issue? I have trouble understanding the interactions here: do we have a risk of someone repeatedly pushing the same image created prior to 1.5 and holding an older checksum version, and thus never benefiting from the cache?

**Comment by dmcgowan** [comment]
This will only partially fix the issue. The performance advantage will only be seen when an image is built by 1.5. As you said prior images will not benefit from the cache.  I am working on another fix which will store the checksum to disk, then the issue will be fully solved.

**Comment by icecrime** [comment]
Is it really necessary? I guess it's very likely that a push comes after a new build.

**Comment by dmcgowan** [comment]
Generated the other PR.  Not sure how necessary it is at this time, it certainly will improve performance in the cases where the image was generated pre 1.5, but it is probably too late in the cycle for get the change in that does not modify the original json.  Feel free to take that conversation over there so we can at least get this one passed the review process.

**Comment by vbatts** [comment]
so this will be a fairly incremental improvement of performance, since most images will not have a checksum on the layer. By not adding it back, then images pushed to the registry will also not include the checksum.

These changes themselves LGTM

**Comment by icecrime** [comment]
@vbatts Well, it does fix the issue for a pure 1.5 user I guess: he builds images with a proper checksum, and pushes/pulls images with proper checksums too. The only performance hit which we don't cover here as far as I understand is that of a user who uses 1.5 to push pre-1.5 images.

**Comment by vbatts** [comment]
Ah true

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
