### PR TITLE
remove old media type compat for plugins

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
LGMT (if tests pass)

**Comment by cpuguy83** [comment]
A few test failures.

**Comment by anusha-ragunathan** [comment]
@riyazdf : We have finalized the mediaType for plugins in 1.13. As a result, `riyaz/authz-no-volume-plugin` needs to be repushed using latest master. Can you please take care of this ASAP?

**Comment by riyazdf** [comment]
@anusha-ragunathan: sure, just re-pushed!  Please let me know if I need to change anything else on the plugin

**Comment by anusha-ragunathan** [comment]
Thanks much for the quick response @riyazdf

**Comment by anusha-ragunathan** [comment]
@riyazdf : `https://hub.docker.com/r/riyaz/authz-plugin-bad-manifest/` needs to be updated as well. Else `TestAuthZPluginBadManifestFailsDaemonStart` fails.

**Comment by riyazdf** [comment]
repushed and got it (and the entire suite) passing locally - please let me know if there other issues!

```
PASS: docker_cli_authz_plugin_v2_test.go:45: DockerAuthzV2Suite.TestAuthZPluginAllowNonVolumeRequest	10.428s
PASS: docker_cli_authz_plugin_v2_test.go:115: DockerAuthzV2Suite.TestAuthZPluginBadManifestFailsDaemonStart	8.825s
PASS: docker_cli_authz_plugin_v2_test.go:75: DockerAuthzV2Suite.TestAuthZPluginRejectVolumeRequests	9.359s
PASS: docker_cli_authz_plugin_v2_test.go:127: DockerAuthzV2Suite.TestNonexistentAuthZPluginFailsDaemonStart	15.996s
```

**Comment by thaJeztah** [comment]
Looks like there's a failing test; https://jenkins.dockerproject.org/job/Docker-PRs-experimental/28110/console

```
22:12:35 
22:12:35 ----------------------------------------------------------------------
22:12:35 FAIL: docker_cli_authz_plugin_v2_test.go:115: DockerAuthzV2Suite.TestAuthZPluginBadManifestFailsDaemonStart
22:12:35 
22:12:35 [d64203c27e267] waiting for daemon to start
22:12:35 [d64203c27e267] daemon started
22:12:35 docker_cli_authz_plugin_v2_test.go:118:
22:12:35     c.Assert(err, checker.IsNil)
22:12:35 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc423322a20), Stderr:[]uint8(nil)} ("exit status 1")
22:12:35 
22:12:35 [d64203c27e267] exiting daemon
```


Also this test is failing, probably not related, so may be flaky;

```
22:08:08 ----------------------------------------------------------------------
22:08:08 FAIL: docker_cli_prune_unix_test.go:26: DockerSwarmSuite.TestPruneNetwork
22:08:08 
22:08:08 [d763491403a44] waiting for daemon to start
22:08:08 [d763491403a44] daemon started
22:08:08 docker_cli_prune_unix_test.go:29:
22:08:08     c.Assert(err, checker.IsNil)
22:08:08 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc42352a180), Stderr:[]uint8(nil)} ("exit status 1")
22:08:08 
22:08:08 [d763491403a44] exiting daemon
22:08:11 
```

ping @AkihiroSuda ^^

**Comment by anusha-ragunathan** [comment]
LGTM again

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
