### PR TITLE
Fmt dockerfile error message

### PR DESCRIPTION
**Pull request by sakeven**
**\- What I did**
Format dockerfile error message to make them more readable and maintainable.
**\- How I did it**

**\- How to verify it**
Added and modified some tests in builder/dockerfile/dispatchers_test.go

miao

Signed-off-by: Sakeven Jiang sakeven.jiang@daocloud.io

### CODE REVIEW

**Comment by vdemeester** [comment]
@sakeven unit tests errors

```
11:27:05 --- FAIL: TestDispatch (0.30s)
11:27:05 	evaluator_test.go:194: Wrong error message. Should be "ARG requires exactly one argument definition". Got "ARG requires exactly one argument"
11:27:05 FAIL
11:27:05 coverage: 44.7% of statements
11:27:05 FAIL	github.com/docker/docker/builder/dockerfile	0.597s
```

**Comment by sakeven** [comment]
@vdemeester Fixed 😊

**Comment by duglin** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
