### PR TITLE
staticcheck: SA1019: strings.Title is deprecated (in Go 1.18)

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/moby/moby/pull/43194 https://github.com/moby/moby/pull/43194#issuecomment-1025757901

Replace it with golang.org/x/text/cases.Title()

    daemon/logger/templates/templates.go:23:14: SA1019: strings.Title is deprecated: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
    "title":    strings.Title,
    ^
    pkg/plugins/pluginrpc-gen/template.go:67:9: SA1019: strings.Title is deprecated: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
    return strings.Title(s)
    ^

TBH, I'm not sure if we really need this; most strings we generate will be ASCII,
so this would only be in case it's used for some user-provided string. We also
don't have a language to use, so would be using the "default".

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
I added a commit to https://github.com/moby/moby/pull/43194 that uses a `//nolint` instead. I personally think that should be ok to use instead (as it brings in way less code changes)

**Comment by thaJeztah** [comment]
Related ticket https://github.com/golang/go/issues/48367 and PR: https://go-review.googlesource.com/c/go/+/359485

**Comment by tianon** [comment]
Yeah, IMO the `//nolint` is better (maybe with a little comment about why we don't want to bring in such a huge pile of code for what I'd bet is a pretty rarely used template function).

**Comment by thaJeztah** [comment]
Yes, let's close this one. I basically did this as it was the recommended alternative, and I could've been "fine" with it if we already vendored all that code (but even then: what "locale" to pick?).

TBH, I feel like they should've have marked it deprecated, but just refined the docs for this function to describe that it's useful for ASCII(ish) use.

**Pull request closed without merging**
