### PR TITLE
Update docker-py to 4.3.0

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/docker/docker-py/compare/4.2.2...4.3.0

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by tianon — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Wonder what went wrong here;

```
Stacktrace
tests/integration/api_build_test.py:16: in <module>
    class BuildTest(BaseAPIIntegrationTest):
tests/integration/api_build_test.py:164: in BuildTest
    @requires_api_version('1.22')
tests/helpers.py:56: in requires_api_version
    docker.utils.version_lt(test_version, version),
docker/utils/utils.py:70: in version_lt
    return compare_version(v1, v2) > 0
docker/utils/utils.py:61: in compare_version
    if s1 == s2:
/usr/local/lib/python3.7/distutils/version.py:46: in __eq__
    c = self._cmp(other)
/usr/local/lib/python3.7/distutils/version.py:170: in _cmp
    if self.version != other.version:
E   AttributeError: 'StrictVersion' object has no attribute 'version'
```

Python 3.7 / 3.8 issue? I saw https://community.letsencrypt.org/t/certbot-failing-to-find-python-version-on-centos-6-10/105634/7, which also seemed to related to Python version compatibility

**Comment by thaJeztah** [comment]
Oh! Perhaps this is it;

```
exec docker run --rm ${run_opts} -e DOCKER_TEST_API_VERSION="${DOCKER_PY_TEST_API_VERSION}"
```

Still passing `-e DOCKER_TEST_API_VERSION`, which will set it to an empty string, and I guess it doesn't like that 🤔

**Comment by thaJeztah** [comment]
Removed the `DOCKER_TEST_API_VERSION` from the `docker run`

**Comment by thaJeztah** [comment]
👍 that fixed it

**Pull request merged**
