### PR TITLE
Improved "start a container" section 1.16 & 1.17 API docs

### PR DESCRIPTION
**Pull request by l0kix2**
It seems it was lost or something

I copypasted it from 1.5. Someone can confirm that api wasn't changed between versions?

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
I cant remember when we removed it... @cpuguy83 can you?

**Comment by cpuguy83** [comment]
I can't remember the PR... but yeah nothing has changed other than of course the new HostConfig fields that are available, copying from `create` correct.

**Comment by l0kix2** [comment]
We also have same problem in 1.17 docs https://docs.docker.com/reference/api/docker_remote_api_v1.17/#start-a-container
so i think i can extend this PR a little and add same data in corresponding file if everyone agrees that it should be there

**Comment by cpuguy83** [comment]
+1, thanks, just need to make sure fields for newer versions don't show up on older ones.

**Comment by l0kix2** [comment]
Made same patch for 1.17

@cpuguy83 newer fields can't show up on older ones, because i copypasted from 1.15 docs to 1.16 and 1.17.

Also is saq 
```
POST /containers/create POST /containers/(id)/start
New! (ReadonlyRootfs) can be passed in the host config to mount the container's root filesystem as read only.
```
in 1.17 changelog, so i copied piece about it from create to start section. Hope it's correct.

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
@cpuguy83 Can you eyeball and approve this one and I'll merge it.

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Looks like the same is needed for 1.18 and 1.19

**Comment by draghuram** [comment]
So is it sufficient if the 1.17 changes are ported into 1.18 and 1.19? I am wondering if there are any newer fields that need to be added as well.

**Comment by cpuguy83** [comment]
It should be sufficient to copy/paste from the create sections "HostConfig" for each of these.

Thanks for  taking care of this!

**Comment by draghuram** [comment]
Sure. But what about the following comment I mentioned in #10304?

<pre>
// This is kept for backward compatibility - hostconfig should be passed when
// creating a container, not during start.
</pre>

Shouldn't this be documented?

**Pull request merged**
