### PR TITLE
Disable privileged test in user namespace

### PR DESCRIPTION
**Pull request by tonistiigi**
CI didn't report this correctly in #21487

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by icecrime** [comment]
How does this need a rebase?

**Comment by icecrime** [comment]
All good on userns :+1:

`09:55:35 SKIP: docker_cli_run_unix_test.go:985: DockerSuite.TestRunPrivilegedAllowedDevices (Test cannot be run when remapping root)`

**Comment by icecrime** [comment]
Janky and userns green, a known failure on experimental, other jobs are irrelevant for this PR: merging!

**Pull request merged**
