### PR TITLE
bash completion for #16229

### PR DESCRIPTION
**Pull request by albers**
ref #16229

ping @jfrazelle, @tianon 
/cc @sdurrheimer new options

### CODE REVIEW

**Comment by sdurrheimer** [comment]
Thanks @albers for the ping. I did a PR #16629 for the zsh completion.

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM

**Comment by abronan** [comment]
@vdemeester :tada: :balloon: :beers: :cocktail:

**Comment by vdemeester** [comment]
@abronan you found me 🐸 ! :beers: :cocktail:

**Comment by albers** [comment]
@tiborvass I think this should go into 1.9 as the feature is present there

**Comment by albers** [comment]
@tiborvass Same as https://github.com/docker/docker/pull/16882#issuecomment-150580190: already present, see https://github.com/docker/docker/blob/release/v1.9/contrib/completion/bash/docker#L571-L572.
So please ignore the previous comment.

**Comment by vdemeester** [comment]
@albers I think it's already there, as it has been merged before the freeze (https://github.com/docker/docker/commits/master/contrib/completion/bash/docker).

**Comment by albers** [comment]
@vdemeester Yes, you're right. Thanks for investigating.
I find it hard to put together the tags from the PRs in github and the corresponding commits in local git history.
I'll have to get better at this.

**Pull request merged**
