### PR TITLE
Vendor libnetwork @ 6bbcd1b4a59bee65e6648130ad8709a413d10537

### PR DESCRIPTION
**Pull request by mavenugo**
* Removed Solaris support
* Addresses the endpoint_cnt issue exposed by https://github.com/moby/moby/issues/35310 

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
interesting;

```
23:23:42 The result of vndr differs
23:23:42 
23:23:42  M vendor/github.com/docker/libnetwork/vendor.conf

**Comment by mavenugo** [comment]
@thaJeztah vendor issue is resolved.

**Comment by thaJeztah** [comment]
Could this be related?

```
02:24:20 --- FAIL: TestCreateWithLBSandbox (3.14s)
02:24:20 	daemon.go:285: [d61ee4b7ad89d] waiting for daemon to start
02:24:20 	daemon.go:317: [d61ee4b7ad89d] daemon started
02:24:20 	assertions.go:226: 
                          
	Error Trace:	create_test.go:68
02:24:20 		
	Error:      	Received unexpected error:
02:24:20 		
	            	Error response from daemon: rpc error: code = FailedPrecondition desc = network 8s80aa3icf1cq0vauif7dkzlm is in use by task c8f1j3af2bkoqfjj4x6wsppv5
02:24:20 	daemon.go:275: [d61ee4b7ad89d] exiting daemon
02:24:20 	clean.go:108: Removing image sha256:bb7258701563f7c4a82f119ffff014519f042c757f6a437d7ab74e163ecb2c56
02:24:20 	clean.go:108: Removing image sha256:6390ed82ebfc324b49382026c64114255d9338ea095ded1dbb1f9d2037785eef
02:24:20 	clean.go:108: Removing image sha256:6e41d9bee787b4cdcdc012daca5a226e5236c94869123e8cf623f557e5f64e8d
02:24:20 	clean.go:108: Removing image sha256:f7d6b5265839a25ec74bdb5680ba1fcea90a90c57eb4ffef57eba7018cece09c
02:24:20 	clean.go:108: Removing image sha256:fd9166a8aa8212d1abd3a85aed239d7acedbdf442dbb25a5736abc83a6aa8b0e
02:24:20 	clean.go:108: Removing image sha256:20d98b40aa534d9bd3452e9894dc704e3a839945c8c5f02a17ee7a5d4de7edad
```

**Comment by thaJeztah** [comment]
ping @mavenugo could you have a look at that failure? It looks like it may be related

**Comment by thaJeztah** [comment]
Copying information from the other pull request;

brings in the following changes:

- https://github.com/docker/libnetwork#1975 bump docker/docker to master and unfork dependencies
- https://github.com/docker/libnetwork#2000 wait for iptables lock in support script
- https://github.com/docker/libnetwork#2002 Remove Solaris support
- https://github.com/docker/libnetwork#2004 endpoint_cnt store updates should not create an object (relates to https://github.com/moby/moby/issues/35310)
- https://github.com/docker/libnetwork#2007 Support override of binary name (relates to https://github.com/moby/moby/pull/34226)

These are the same changes as was merged in https://github.com/docker/docker-ce/pull/296 (for Docker CE 17.11)


Full diff; https://github.com/docker/libnetwork/compare/72fd7e5495eba86e28012e39b5ed63ef9ca9a97b...6bbcd1b4a59bee65e6648130ad8709a413d10537

**Comment by thaJeztah** [comment]
Closing this one, as it's superseded by https://github.com/moby/moby/pull/35620

**Pull request closed without merging**
