### PR TITLE
Make Makefile work on OS X

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

### CODE REVIEW

**Comment by tiborvass** [comment]
Ping @tianon

**Comment by jfrazelle** [comment]
oh whoa was it actually exiting the term session or something

**Comment by tiborvass** [comment]
@jfrazelle no it's just that `tac` does not exist on OS X...

**Comment by tiborvass** [comment]
And the reason it was put in the first place was to close the pipe or something

**Comment by jfrazelle** [comment]
ohhh i see

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
Yeah...  Go output chains like in `version` are often racy with output piping and get grumpy if what they're piped to closes stdin before they're ready (which `awk` does when you `exit`), hence `tac|tac` to force all of stdin to be read before passing it on.

LGTM

**Comment by tianon** [comment]
Should we wait for janky to finish since this affects the builds? (pretty minor effect, but still)

**Comment by cyphar** [comment]
@tianon You could use `sort` or something like that.

**Comment by tianon** [comment]
Except sort will mess with the ordering and break the awk :smile:

**Pull request merged**
