### PR TITLE
Should be english punctuation instead of other type of punctuation

### PR DESCRIPTION
**Pull request by EnergyLiYN**
Signed-off-by: lyn <energylyn@zju.edu.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

> Signed-off-by: Joe Smith <joe.smith@email.com>
> Use your real name (sorry, no pseudonyms or anonymous contributions.)

**Comment by AkihiroSuda** [comment]
Also, can you consider squashing this PR with https://github.com/docker/docker/pull/29537 ?

**Comment by EnergyLiYN** [comment]
i have signed by my name
image，there can be seen.

**Comment by EnergyLiYN** [comment]
I have merged #29537 and #29567,thanks for your time.

**Comment by AkihiroSuda** [comment]
@EnergyLiYN Can you use your real name for signing?

**Comment by AkihiroSuda** [comment]
The changes itself LGTM

**Comment by EnergyLiYN** [comment]
how to resign my real name?my real name is yanan Lee. @AkihiroSuda

**Comment by EnergyLiYN** [comment]
Now,i commit new change with my real name.  Thanks,@AkihiroSuda 
image

**Comment by AkihiroSuda** [comment]
Thank you for updating the sign, can you squash commits to a single commit?

**Comment by EnergyLiYN** [comment]
I have merged to single commit,thanks @AkihiroSuda

**Pull request closed without merging**
