### PR TITLE
[1.13.x] cherry-pick secrets to compose

### PR DESCRIPTION
**Pull request by vieux**
Add secrets to stack deploy #30144
Add SecretUpdate method to client #28720

### CODE REVIEW

**Comment by vieux** [comment]
ping @tiborvass @dnephin @ehazlett

**Comment by AkihiroSuda** [comment]
build failing
```
03:54:46 # github.com/docker/docker/cli/command/service
03:54:46 cli/command/service/update_test.go:437: cannot use apiClient (type secretAPIClientMock) as type "github.com/docker/docker/client".APIClient in argument to getUpdatedSecrets:
03:54:46 	secretAPIClientMock does not implement "github.com/docker/docker/client".APIClient (missing CheckpointCreate method)
```

**Comment by dnephin** [comment]
```diff
diff --git a/integration-cli/docker_cli_stack_test.go b/integration-cli/docker_cli_stack_test.go
index 0785686..fd9b154 100644
--- a/integration-cli/docker_cli_stack_test.go
+++ b/integration-cli/docker_cli_stack_test.go
@@ -8,7 +8,6 @@ import (
 	"strings"
 
 	"github.com/docker/docker/api/types/swarm"
-	"github.com/docker/docker/integration-cli/checker"
 	"github.com/docker/docker/pkg/integration/checker"
 	"github.com/go-check/check"
 )
```

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
