### PR TITLE
Run TestBuildCopyWilcardInName only on linux daemon and unix client

### PR DESCRIPTION
**Pull request by vdemeester**
Should fix `win2lin`.

/cc @thaJeztah @mlaventure @johnstep @tiborvass @duglin 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by justincormack — APPROVED** [review]

**Comment by duglin** [comment]
LGTM
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
Hmmm. This should work win2lin and on RS1 win2win... Let me look in a bit what's going on.

**Comment by jhowardmsft** [comment]
Yeah, this is the wrong fix. It's a test bug somewhere in the context building code, nothing to do with Windows not supporting wildcards. See this simple manual test which does similar (running against a Linux machine from a Windows client)

```
PS E:\docker\build\TestBuildCopyWildcardInName> $env:DOCKER_HOST="jhoward-ubuntu:2375"
PS E:\docker\build\TestBuildCopyWildcardInName> docker build .
Sending build context to Docker daemon 4.096 kB
Step 1/3 : FROM busybox
 ---> d9551b4026f0
Step 2/3 : COPY *.txt /tmp/
 ---> 566236cb63a7
Removing intermediate container 83eeb9cf1434
Step 3/3 : RUN ls -l /tmp/
 ---> Running in 90e0ed46386e
total 8
-rwxr-xr-x    1 root     root            47 Jan 20 18:21 file1.txt
-rwxr-xr-x    1 root     root            47 Jan 20 18:21 file2.txt
 ---> fa30e689e061
Removing intermediate container 90e0ed46386e
Successfully built fa30e689e061
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
PS E:\docker\build\TestBuildCopyWildcardInName>
```

@johnstep FYI

**Comment by jhowardmsft** [comment]
Oh actually, I see, I misread the comment and what the test is doing. Correct, Windows doesn't support `*` in a filename.

LGTM.

**Pull request merged**
