### PR TITLE
Added c++ client library for REST API

### PR DESCRIPTION
**Pull request by lasote**

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by lasote** [comment]
Thank you jfrazelle. Its ok now?

**Comment by jfrazelle** [comment]
Yep looks good :)

**Comment by SvenDowideit** [comment]
LGTM - @fredlf @jamtur01

**Pull request merged**
