### PR TITLE
Enable checkpoint/restore of containers with TTY

### PR DESCRIPTION
**Pull request by rst0git**
CRIU supports checkpoint and restore of tty devices since version 2.12
which was released on 8th of March 2017. Support for this functionality
was implemented with opencontainers/runc@1c43d09 (checkpoint: add
support for containers with terminals) and containerd/containerd@60daa41
(Allow to checkpoint and restore a container with console).

Therefore, we can enable the support in moby/docker.

Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>

**- How to verify it**
```
$ docker run -dit --name apache-app -p 8080:80 httpd:2.4
$ curl http://localhost:8080
<html><body><h1>It works!</h1></body></html>
$ docker checkpoint create apache-app c1
$ docker start --checkpoint c1 apache-app
$ curl http://localhost:8080
<html><body><h1>It works!</h1></body></html>
```

### CODE REVIEW

**Comment by rst0git** [comment]
@avagin @kolyshkin

**Comment by avagin** [comment]
LGTM

It would be good to add a test for this.

**Comment by olljanat** [comment]
Derek add label: rebuild/experimental

**Comment by rst0git** [comment]
Thanks for the feedback! The integration tests for C/R is a great idea I look into that.
The containerd and runc versions vendored in moby/moby are up to date and support tty c/r. I also tested this functionality manually with the development environment. Although, for this to work there it requires the patches from #38378.

**Comment by thaJeztah** [comment]
> Support for this functionality was implemented with opencontainers/runc@1c43d09 (checkpoint: add support for containers with terminals) and containerd/containerd@60daa41

double-checking; both are in the versions that are currently used in this repository? https://github.com/moby/moby/blob/master/hack/dockerfile/install/runc.installer#L7
and https://github.com/moby/moby/blob/master/hack/dockerfile/install/containerd.installer#L7

**Comment by avagin** [comment]
> Thanks for the feedback! The integration tests for C/R is a great idea and I will look into that.
https://github.com/avagin/docker/commit/fbcefa3f7bca8a1c6298df6efc3ba2d9f8724c16

**Comment by fntlnz** [comment]
@rst0git  thanks for adding the integration test, there's an error during checkpoint at line 93, doesn't seem to be related to the TTY but I think we need two test cases, one with and one without TTY

**Comment by rst0git** [comment]
> @rst0git thanks for adding the integration test, there's an error during checkpoint at line 93, doesn't seem to be related to the TTY but I think we need two test cases, one with and one without TTY

@fntlnz Thanks for the feedback. This integration test in now in moby#38452 
We could add a test case for TTY after it is merged.

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by gj** [comment]
Hey 👋 anything still blocking this PR from making it in? Happy to help move it along if so!

**Comment by cpuguy83** [comment]
Looks like it just needs an integration test.

**Comment by kolyshkin** [comment]
> Looks like it just needs an integration test.

@cpuguy83 the problem is, there are 0 tests for C/R at the moment. This is the subject of https://github.com/moby/moby/pull/38452 -- once it's there, it will be easy to add a case for TTY

**Comment by gj** [comment]
Now that #38452 is in, I've gone ahead and copied @avagin's excellent work to create an integration test for a container with TTY:

https://github.com/gj/moby/commit/ba7fe405355c55ebbe6e1c2db1c834b4cba92cb8

**Comment by rst0git** [comment]
@gj Would you like to open a PR with your changes?

**Comment by gj** [comment]
@rst0git sorry for not being more responsive on this. I've been trying to figure out how to attach IO streams to the test container restored from a checkpoint in the same style as [this test](https://github.com/containerd/containerd/blob/04b2e5bbf7d73c51cfbeb6f92d9200f70516cf55/container_checkpoint_test.go#L42) (helpfully pointed out by @avagin as a good example to follow).

**Comment by kolyshkin** [comment]
I guess we don't lose anything if we merge this one without a test case, which can be done as a followup.

@gj I suggest you open the PR with your changes (doesn't matter if it's ready for prime time or not) and mark it with `[WIP]` for now -- this way it will be much easier to track and review. Please cc me, @avagin and @rst0git on it so we can help.

**Comment by gj** [comment]
Will do that tonight @kolyshkin; thanks!

**Pull request merged**
