### PR TITLE
[WIP] Push all tags when no tag is specified

### PR DESCRIPTION
**Pull request by stevvooe**
In Docker 1.4, a push with no tag specified resulted in pushing all the tags
for an image. With changes in 1.5, this behavior was broken. The issue was the
interaction between the engine and the client. When requesting the manifest, if
the tag was not specified, the engine defaulted to latest. In cases where
latest was defined, only latest would be pushed. If latest was not defined, the
push would fail with an error message.  This behavior was the same between v1
and v2 pushes.

We address this by sending all the manifests for all tagged images if the tag
is not specified when fetching the manifest. The engine command image_manifest
was modified to return a collection of manifests rather than just a single one
to support this. The client code then loops to push each manifest individually.

Addresses regression described in #10444.

Signed-off-by: Stephen J Day stephen.day@docker.com

_This is a work in progress and demonstrates a possible fix. We probably want to tweak the protocol between the client and server to not be so silly._

### CODE REVIEW

**Comment by jfrazelle** [comment]
gofmt

**Comment by stevvooe** [comment]
> gofmt

Where? I ran it...

```
$ gofmt -d graph/manifest.go api/client/commands.go
```
No output. :camel:

**Comment by tiborvass** [comment]
@stevvooe `gofmt -w -s`

**Comment by crosbymichael** [comment]
Closing in favor of #10456

**Pull request closed without merging**
