### PR TITLE
Skip racey TestDockerCmdWithTimeout

### PR DESCRIPTION
**Pull request by cpuguy83**
Test was just introduced but appears racey.
Won't fail on my system but seems to fail 50/50 on CI.

ping @vdemeester @tiborvass

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
ping @jfrazelle

**Comment by jhowardmsft** [comment]
Should there be an issue opened to fix the test?

**Comment by cpuguy83** [comment]
#16360

**Comment by vdemeester** [comment]
Ah :sweat:… I wonder how it never fail on my laptop.. I'll try to fix it.. sorry :sob: :stuck_out_tongue_closed_eyes:

**Pull request merged**
