### PR TITLE
Update plugins.md

### PR DESCRIPTION
**Pull request by amylindburg**
Fixed broken link.

Signed-off-by: Amy Lindburg amy.lindburg@docker.com

### CODE REVIEW

**Comment by icecrime** [comment]
Nice catch :-)

**Comment by amylindburg** [comment]
There are some more broken links. You will see me again. Do I submit another pull request? Working on that...

**Comment by amylindburg** [comment]
Oh I guess my changes just got added? Sweet.

**Comment by amylindburg** [comment]
Oh wait, can I just add another commit? Is that kosher? Hey, let's see.

**Comment by icecrime** [comment]
@amylindburg You indeed can have multiple commits in a single PR, unfortunately we will ask you to [squash them](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) into one so have a simpler git history, and to ease bookkeeping for those who need to cherry-pick in the release branch ;-)

**Comment by amylindburg** [comment]
Makes sense will figure that out.

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
@jfrazelle looks like we missed this one in the 1.7 branch

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
