### PR TITLE
Fixed docker network link in faq

### PR DESCRIPTION
**Pull request by tophj-ibm**
Fixed a link to docker networks on the FAQ page.
Also it's worth noting, a lot of incorrect links aren't showing up in make docs via LinkResolver. I'd be happy to look at it, if you can point me in the right direction :)

ping @thaJeztah @moxiegirl
Signed-off-by: Christopher Jones tophj@linux.vnet.ibm.com

### CODE REVIEW

**Comment by MHBauer** [comment]
Link works for me in `make docs`.

**Comment by thaJeztah** [comment]
thanks @tophj-ibm, LGTM

**Comment by thaJeztah** [comment]
ping @moxiegirl @SvenDowideit for the merge

**Comment by moxiegirl** [comment]
LGTM Thank you @tophj-ibm for the contribution.

**Pull request merged**
