### PR TITLE
daemon/containerd: use "DiffID" type for diff fields

### PR DESCRIPTION
**Pull request by thaJeztah**
strong-type the fields with the expected type, to make it more explicit what we're expecting here.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by laurazard — COMMENTED** [review]
LGTM! <3 this was something I remembered marking down in my mind as "should look at again" at the time

**Review by laurazard — APPROVED** [review]

**Comment by thaJeztah** [comment]
Flaky test on Windows 2022 (let me post here in case it became more flaky);

```
=== FAIL: github.com/docker/docker/integration/container TestRemoveContainerWithRemovedVolume (18.28s)
    remove_test.go:40: timeout hit after 10s: waiting for container to be one of (exited), currently running

=== FAIL: github.com/docker/docker/integration/container TestRemoveContainerWithVolume (18.56s)
    remove_test.go:63: timeout hit after 10s: waiting for container to be one of (exited), currently running
```

**Comment by thaJeztah** [comment]
> this was something I remembered marking down in my mind as "should look at again" at the time

😄 Yes, I was initially looking "should we make it _less strict_ and change the type to be an alias (just accept `<any digest>`)"? 

But then again, there's "digests anywhere" and it looked like it would be useful to make it strong-typed,  so that when you're assigning a digest, you need to "think twice" if you have the "right kind of digest".

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
digests-everywhere

**Comment by laurazard** [comment]
@thaJeztah It's definitely better this way – I remember when working on it initially I was pretty confused as to what was valid and what kind of stuff I could throw there 😅

**Pull request merged**
