### PR TITLE
added functionality to interrupt the terminal when it is waiting for …

### PR DESCRIPTION
**Pull request by avaid96**
**\- What I did**
added functionality to term package to exit when it is waiting for a password with ctrl+c
(main reason for this is for notary- allows us to exit key generation while it is waiting for a passphrase)
**\- How I did it**
Used the os/signal package in the handleinterrupt function of term.go
**\- How to verify it**
run `docker login`, try to press `ctrl+c` when being asked for your password, it should exit
**\- Description for the changelog**
added functionality to term package to exit when it is waiting for a password with `ctrl+c`
**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Avi Vaid avaid1996@gmail.com

### CODE REVIEW

**Comment by avaid96** [comment]
windowsRS1 seems to be running into ```fatal: unable to access 'https://github.com/docker/docker.git/': Couldn't resolve host 'github.com'```, is this something I messed up or is it just Jenkins?

**Comment by thaJeztah** [comment]
Just Windows :smile:, I'll restart

**Comment by LK4D4** [comment]
LGTM

**Comment by justincormack** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, and all green

**Pull request merged**
