### PR TITLE
Updating aws-sdk-go to version 1.4.22

### PR DESCRIPTION
**Pull request by vdemeester**
Carry #27822

----

This change updates `aws/aws-sdk-go` to the most recent version.

The sdk update includes the move from `aws-sdk-go/private/signer/v4` to `aws-sdk-go/aws/signer/v4`, which (depending on your flavor of dependency management) was causing some conflicts on fresh projects that rely on `docker/docker`. 

**\- How I did it**
- update `hack/vendor.sh` with new package tag
- run `hack/vendor.sh`

**\- Description for the changelog**
Update aws-sdk-go to release 1.4.22

**\- A picture of a cute animal (not mandatory but encouraged)**

/cc @samuelkarp @rheinwein @thaJeztah

### CODE REVIEW

**Review by samuelkarp — APPROVED** [review]
LGTM

**Comment by rheinwein** [comment]
👼 thanks @vdemeester!

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by justincormack — APPROVED** [review]

**Comment by thaJeztah** [comment]
All 💚 merging

**Pull request merged**
