### PR TITLE
Add zsh completion for new 'docker container' subcommands

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #26025

Same logic as @albers #27579 PR, splitting commits for better review session.

@vincentbernat

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thank you @sdurrheimer!!

Also /cc @vdemeester @tianon @mlaventure

**Comment by cpuguy83** [comment]
Looks ok, but doesn't complete `docker container`.
We can probably squash this down a bit.

**Comment by sdurrheimer** [comment]
@cpuguy83 Hum, the `docker container` completion comes from the `docker --help` output.

Hum right, the `docker --help` has changed, commands are now split into two categories: `Management Commands` and `Commands`. We might need a fix in the zsh completion to handle that.

**Comment by cpuguy83** [comment]
Ah, that may be why -- I'm not on latest, just replaced my normal completion with this here.

**Comment by albers** [comment]
@sdurrheimer There's also #27468 pending, which might not be solvable by parsing help output.
The aliases should not appear in completion but be considered  when they are used.

**Comment by sdurrheimer** [comment]
@albers It won't be a problem, short aliases will not be handled the same way as main commands, I will handle that when #27468 will be merge.

**Comment by sdurrheimer** [comment]
@vincentbernat What do you think about the 1st level completion of docker commands, should we keep parsing the `docker --help` output, or should we switch to a hard list ?

**Comment by vincentbernat** [comment]
I don't have a strong opinion on this. If you need help to parse the new `docker --help`, I can do that if you copy/paste the current output in a gist.

**Comment by sdurrheimer** [comment]
@vincentbernat They introduce a new `Management Commands:` section, and there is also the `inspect` comment that is now on two lines which gives false results.

Here you go
```
$ docker

Usage:	docker COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/home/steve/.docker")
  -D, --debug              Enable debug mode
      --help               Print usage
  -H, --host list          Daemon socket(s) to connect to (default [])
  -l, --log-level string   Set the logging level (debug, info, warn, error, fatal) (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/steve/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/steve/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/steve/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  container   Manage containers
  image       Manage images
  network     Manage networks
  node        Manage Swarm nodes
  service     Manage services
  swarm       Manage Swarm
  system      Manage Docker
  volume      Manage volumes

Commands:
  attach      Attach to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker object(s) (e.g. container, image, volume,
network, node, service, or task) identified by name or ID
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Tag an image into a repository
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.
```

**Comment by vincentbernat** [comment]
Thanks. I propose the following:

```
_docker_subcommands=(${${${(M)${lines[$((${lines[(i)*Commands:]} + 1)),-1]}:# *}## #}/ ##/:})
```

This is a bit simpler (and works with older versions too). It also deals with the inspect line being cut (but the description should simply be shortened, I have created #28045 for that).

**Comment by sdurrheimer** [comment]
@vincentbernat Thank you very much, change added to the PR.

**Comment by sdurrheimer** [comment]
`docker image` and `docker system` PR waiting behind the scene.

**Comment by vieux** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐮
@sdurrheimer one question though : `docker con<tab>` doesn't propose `container`, is this intended ?

**Comment by sdurrheimer** [comment]
@vdemeester Same as for @cpuguy83, are you using a docker 1.13 client when doing the test ? First level commands are completed/cached from the `docker --help` output.

**Comment by vdemeester** [comment]
@sdurrheimer arg you're right, my client was 1.12.2 :sweat: It's working as expected once I switch 👼

**Pull request merged**
