### PR TITLE
Vendoring libnetwork

### PR DESCRIPTION
**Pull request by fcrisciani**
- fixes for networkdb
- few crash fixes

diff: https://github.com/docker/libnetwork/compare/248fd5e...24bb72a
Signed-off-by: Flavio Crisciani <flavio.crisciani@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
probably needs https://github.com/docker/libnetwork/pull/1856 to be merged first upstream

**Comment by fcrisciani** [comment]
@thaJeztah z looks like timed out, should we respin or can be a real issue?

**Comment by thaJeztah** [comment]
Not related, z has been timing out a lot recently; the timeout has been set longer now, so fingers crossed

- fixes for networkdb
- few crash fixes

Any specific issues you're aware of? (issues I can link to/from here)?

**Comment by fcrisciani** [comment]
@thaJeztah nothing specific to link, this vendoring brings:
- stability improvements for networkdb also in case of physical network issues. We did some testing on this area
- fixes 2 crashes 
- corner case scenario where ipam was not returning the correct IP if the pool of ip was not aligned but with a displacement

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
