### PR TITLE
Windows: Prevent logging errors when shutting down an already shut down container

### PR DESCRIPTION
**Pull request by darstahl**
This stops logging an error when attempting to shut down a previously terminated/shutdown container on Windows

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Could you split this into two commits - one for the revendor and one for the code change please? Thanks :smile:

**Comment by darrenstahlmsft** [comment]
Split into two commits :smile:

**Comment by darrenstahlmsft** [comment]
I can't see any changes to the behaviour of stop/kill. Docker should still block stop/kills on a container that is not in the correct state to do so and report the errors correctly. This should only affect the case when the init process is terminated and WaitExit still attempts to shutdown the container.

**Comment by jhowardmsft** [comment]
Right - I was reading the change on my phone yesterday. LGTM.

**Pull request merged**
