### PR TITLE
Migrate config list tests from integration-cli to api tests

### PR DESCRIPTION
**Pull request by yongtang**
This fix migrates config list tests from integration-cli to api tests

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by dnephin — COMMENTED** [review]
same comments as #36221

**Comment by yongtang** [comment]
Thanks @dnephin for the review. The PR has been updated, with code consolidation similar to #36221. Please take a look and let me know if there are any issues.

**Comment by yongtang** [comment]
The PR has been rebased to sync up the change from #36265 (`util` -> `internal`).

**Review by dnephin — APPROVED** [review]
LGTM

**Pull request merged**
