### PR TITLE
add gpg fingerprint for experimental

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon 

also we need to cherry-pick this before release ;)

### CODE REVIEW

**Comment by jfrazelle** [comment]
key is now on keyserver.ubuntu.com

**Comment by tianon** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
Test failures are completely unrelated

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
