### PR TITLE
Add --health-* flags to service create and update

### PR DESCRIPTION
**Pull request by cezarsa**
**\- What I did**

This PR is related to docker/docker#25303 and adds `--health-*` and `--no-healthcheck` flags to service create and update commands.

**\- How I did it**

The `ContainerSpec` was modified to include a `HealthConfig` instance which is them serialized to swarmkit. I also created a PR in swarmkit (docker/swarmkit#1641) which needs to be merged before this PR can be accepted.

For service create the behavior is similar to `docker run` with the same checks validating conflicting arguments. On service update it's also valid to set things like `--health-cmd ""` and `--health-timeout 0` to allow inheriting these attributes from the image. Setting `--no-healthcheck` will reset the HealthConfig to the NONE test and remove every other attribute.

**\- How to verify it**

Some test case were added to check if the commands are behaving correctly.

**\- Description for the changelog**

Add --health-\* and --no-healthcheck to service create and update

**\- A picture of a cute animal (not mandatory but encouraged)**
🐱

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like there's some golint errors;

```
00:10:17 ---> Making bundle: validate-lint (in bundles/1.13.0-dev/validate-lint)
00:10:17 Errors from golint:
00:10:17 cli/command/service/opts.go:72:6: exported type PositiveDurationOpt should have comment or be unexported
00:10:17 cli/command/service/opts.go:76:1: exported method PositiveDurationOpt.Set should have comment or be unexported
00:10:17 
00:10:17 Please fix the above errors. You can test via "golint" and commit the result.
```

**Comment by thaJeztah** [comment]
ping @stevvooe @aluzzardi @talex5

**Comment by cezarsa** [comment]
Thanks, I've fixed the lint errors. However, the code still doesn't compile on CI because it depends on docker/swarmkit#1641. If the swarmkit PR is approved (and updated on vendor) I'll rebase this PR and it should compile cleanly.

**Comment by thaJeztah** [comment]
@cezarsa to make CI pass during review, you can add a second commit that makes those changes in the vendored files. The "vendor" CI will fail, but all other tests can pass then. Once we're in "code review", and https://github.com/docker/swarmkit/pull/1641 is merged, you can then update the PR to update the vendor.sh an get the actual changes from SwarmKit

**Comment by cezarsa** [comment]
Thanks for the tip @thaJeztah. Tests are passing now.

**Comment by thaJeztah** [comment]
oh boy, looks like this needs a rebase now. :cry:

**Comment by vdemeester** [comment]
@cezarsa something is missing somehow. The healthcheck I provide for the service doesn't end-up into the container(s) created.

```
$ docker run -d --health-cmd="stat /etc/passwd" --health-interval=10s --health-retries=2 busybox top
$ docker service create --name test --health-cmd="stat /etc/passwd" --health-interval=10s --health-retries=2 busybox top
# … wait for a bit
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                    PORTS               NAMES
95b46e278bfb        busybox             "top"               14 seconds ago       Up 13 seconds (healthy)                       hungry_colden
7501f04e3610        busybox:latest      "top"               About a minute ago   Up About a minute                             test.1.lalhjh6envegchv54qjrkts4u
$ docker inspect --format={{.State.Health}} 95b
{healthy 0 [0xc42037e280 0xc42037e2d0 0xc42037e320 0xc42037e370 0xc42037e3c0]}
$ docker inspect --format={{.State.Health}} 750
<nil>
```

As shown in `inspect` or in `ps`, the container that was created as part of the service has no health check.

**Comment by icecrime** [comment]
Also ping @dongluochen and @aaronlehmann FYI!

**Comment by cezarsa** [comment]
Sorry @vdemeester, there was a bit of code missing. I just added it in https://github.com/docker/docker/pull/27369/commits/3d0132f88ca1e5e6fc97ff2781a64f7bc4f03cfc

I made this mistake because similar code exists in [swarmkit](https://github.com/docker/swarmkit/blob/master/agent/exec/container/container.go#L130) and I thought the daemon was using it, sorry. (I guess it will use in the future?)

Just tested it now and everything seems to be working now:
```
$ docker service create --health-cmd 'exit 1' busybox tail -f /dev/null
lb3l6fxxdehc8n65k172wpacy
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED                  STATUS                                     PORTS                    NAMES
9528efa658fc        busybox:latest      "tail -f /dev/null"      Less than a second ago   Up Less than a second (health: starting)                            hungry_montalcini.1.moaaurb2ugxc2cktv4qnabpoo
$ docker inspect --format={{.State.Health}} 95
{starting 0 []}
$ docker inspect --format={{.Config.Healthcheck.Test}} 95
[CMD-SHELL exit 1]
```

**Comment by dongluochen** [comment]
I test this code and it looks good to me. One small problem would be the default value for healthcheck interval and retries are not shown. But we haven't done it in `docker run`.

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
@cezarsa needs a rebase though :sweat_smile:

**Comment by thaJeztah** [comment]
looks like it's rebased

**Review by cpuguy83 — APPROVED** [review]
LGTM

Moving to docs review

**Comment by vdemeester** [comment]
@cezarsa could you squash all the commits that are not related to vendoring ? (this way we have one commit for vendoring, one for the actual diff)

**Review by thaJeztah — APPROVED** [review]
LGTM (after squashing)

**Comment by cezarsa** [comment]
Done. :)

**Comment by vdemeester** [comment]
@cezarsa perfect ! Thanks !
docs LGTM 🐸

**Pull request merged**
