### PR TITLE
Update docs/base in makefile docs-build.

### LINKED ISSUE #11230: docs/base image not updated during make docs
I just noticed that `make docs` doesn't make sure that the latest image for the [docs/base](https://registry.hub.docker.com/u/docs/base/builds_history/147632/) image is pulled, causing http://docs.docker.com and http://docs.master.dockerproject.com to use an older version of the stylesheet(s).

I'm not sure if this is something to be fixed in the https://github.com/docker/docs-base (explicitly tagging releases) or in the Makefile (always perform a `docker pull`).

ping @SvenDowideit (I think)

### PR DESCRIPTION
**Pull request by jessfraz**
closes #11230

### CODE REVIEW

**Comment by jfrazelle** [comment]
which means we can then merge #11237

**Comment by tianon** [comment]
@SvenDowideit's comment in https://github.com/docker/docker/issues/11230#issuecomment-78202866 totally still applies:
> if you make the Makefile do a `docker pull`, then you won't be able to make local changes to the docs-base image to test your changes to that project.

**Comment by jfrazelle** [comment]
oh damn, so what is the solution thenn

**Comment by tianon** [comment]
I guess you could just as easily `docker build docs` in that case, though, and skip the `Makefile` entirely. :+1:

**Comment by tianon** [comment]
Except for, you know, those extra bits of data that get generated, but if you've used the `Makefile` target even once, it'll at least build successfully since you'll have the files existing, even if they're stale.

**Comment by jfrazelle** [comment]
I would say that otherwise can we never merge #11237 lol

**Comment by jfrazelle** [comment]
ping @SvenDowideit @moxiegirl

**Comment by moxiegirl** [comment]
@jfrazelle Couldn't I just comment out the pull in the Makefile when I'm developing docs-base locally?  If that's all that is required, I can document this and we b GTG.

**Comment by jfrazelle** [comment]
Yes that would work :D

**Comment by moxiegirl** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks Jess for picking this up (I thought it would be more complicated; looking at this, I could have come up with this. Sorry for not attempting!)

> Couldn't I just comment out the pull in the Makefile when I'm developing docs-base locally?

Would be nice to have a cleaner option then that, sure. But for the time being, it could work. So a careful "lgtm" from me.

**Pull request merged**
