### PR TITLE
testing: bump docker-py 4.2.2

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/docker/docker-py/compare/4.2.1...4.2.2

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Hmmm. Looks like that test was not fully fixed for the changes in master;

```

[2020-07-16T14:37:39.495Z] _________ CreateContainerTest.test_invalid_log_driver_raises_exception _________
[2020-07-16T14:37:39.495Z] tests/integration/api_container_test.py:293: in test_invalid_log_driver_raises_exception
[2020-07-16T14:37:39.495Z]     assert excinfo.value.explanation in expected_msgs
[2020-07-16T14:37:39.495Z] E   AssertionError: assert 'error looking up logging plugin asdf: plugin "asdf" not found' in ["logger: no log driver named 'asdf' is registered", 'looking up logging plugin asdf: plugin "asdf" not found']
[2020-07-16T14:37:39.495Z] E    +  where 'error looking up logging plugin asdf: plugin "asdf" not found' = APIError(HTTPError('400 Client Error: Bad Request for url: http+docker://localhost/v1.39/containers/create')).explanation
[2020-07-16T14:37:39.495Z] E    +    where APIError(HTTPError('400 Client Error: Bad Request for url: http+docker://localhost/v1.39/containers/create')) = <ExceptionInfo APIError tblen=6>.value
```

**Comment by thaJeztah** [comment]
Looks like this is the difference;

```
error looking up logging plugin asdf: plugin "asdf" not found
      looking up logging plugin asdf: plugin "asdf" not found
```

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker-py/pull/2624 to fix the test

**Comment by thaJeztah** [comment]
disabled the failing test again for now

**Comment by thaJeztah** [comment]
All green now

**Review by tianon — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
