### PR TITLE
Fix data race in libcontainerd

### LINKED ISSUE #24580: [1.12-rc4] libcontainerd data race
```
Jul 13 11:30:19 localhost.localdomain docker[20494]: ==================
Jul 13 11:30:19 localhost.localdomain docker[20494]: WARNING: DATA RACE
Jul 13 11:30:19 localhost.localdomain docker[20494]: Write by goroutine 19:
Jul 13 11:30:19 localhost.localdomain docker[20494]:   github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/libcontainer
Jul 13 11:30:19 localhost.localdomain docker[20494]:   github.com/docker/docker/libcontainerd.(*remote).handleConnectionChange()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/libcontainer
Jul 13 11:30:19 localhost.localdomain docker[20494]: Previous read by goroutine 17:
Jul 13 11:30:19 localhost.localdomain docker[20494]:   github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon.func1()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/libcontainer
Jul 13 11:30:19 localhost.localdomain docker[20494]: Goroutine 19 (running) created at:
Jul 13 11:30:19 localhost.localdomain docker[20494]:   github.com/docker/docker/libcontainerd.New()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/libcontainer
Jul 13 11:30:19 localhost.localdomain docker[20494]:   main.(*DaemonCli).start()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/cmd/dockerd/daemon.go:275 +0x2caf
Jul 13 11:30:19 localhost.localdomain docker[20494]:   main.main()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x6ad
Jul 13 11:30:19 localhost.localdomain docker[20494]: Goroutine 17 (finished) created at:
Jul 13 11:30:19 localhost.localdomain docker[20494]:   github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/libcontainer
Jul 13 11:30:19 localhost.localdomain docker[20494]:   github.com/docker/docker/libcontainerd.New()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/libcontainer
Jul 13 11:30:19 localhost.localdomain docker[20494]:   main.(*DaemonCli).start()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/cmd/dockerd/daemon.go:275 +0x2caf
Jul 13 11:30:19 localhost.localdomain docker[20494]:   main.main()
Jul 13 11:30:19 localhost.localdomain docker[20494]:       /home/amurdaca/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x6ad
Jul 13 11:30:19 localhost.localdomain docker[20494]: ==================
```
/cc @mlaventure @tonistiigi @crosbymichael 

I can hardly reproduce this, testing with 1.12-rc4 on Fedora 24

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure mickael.laventure@gmail.com
## 

Fixes #24580

### CODE REVIEW

**Comment by runcom** [comment]
LGTM (re-running integration test but this seems the right fix)

**Comment by crosbymichael** [comment]
LGTM

It looks like the CI things are related to the swarm timing failures we have been seeing

**Comment by thaJeztah** [comment]
ping @runcom PTAL

**Comment by runcom** [comment]
LGTM - I tested again with integration-test and I cannot reproduce anymore

**Comment by crosbymichael** [comment]
@runcom thanks!

**Pull request merged**
