### PR TITLE
Add some helper text for magical ADD

### PR DESCRIPTION
**Pull request by duglin**
Closes: #15777

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by MHBauer** [comment]
does this note need the leading `>` chars? all the other `**Note**` have them.

**Comment by duglin** [comment]
wasn't sure since its indented - I figured @moxiegirl would let me know  :-)

**Comment by MHBauer** [comment]
screen shot 2016-01-22 at 13 56 09

Yup, looks funky.

**Comment by duglin** [comment]
Added the ">" per @MHBauer's suggestion - looked ok/normal to me.

**Comment by MHBauer** [comment]
Content reads fine. LGTM

Looks good too.
screen shot 2016-01-22 at 14 19 58
Yay!

@thaJeztah for review.

**Comment by thaJeztah** [comment]
LGTM, thanks @duglin!

**Comment by cyphar** [comment]
I remember we said we were going to deprecate this magic several releases ago? Is there any plan on following through with that?

**Comment by thaJeztah** [comment]
@cyphar I think it's been decided to keep it, because too many people would be affected by removing it. but yeah, it's far too magical

**Comment by cyphar** [comment]
:(

**Pull request merged**
