### PR TITLE
vendor: github.com/moby/buildkit v0.11.7-dev

### PR DESCRIPTION
**Pull request by thaJeztah**
- ~temporarily using my branch from https://github.com/moby/buildkit/pull/3503~

full diff: full diff: https://github.com/moby/buildkit/compare/0a15675913b7...616c3f613b54a893df758428c51fad63ae2ccb7d

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by neersighted — APPROVED** [review]

**Comment by neersighted** [comment]
Looks like we have legitimate test failures:
```
    --- FAIL: TestIntegration/TestBasicAzblobCacheImportExport/worker=dockerd-containerd (6.35s)
    --- FAIL: TestIntegration/TestBasicS3CacheImportExport/worker=dockerd-containerd (5.95s)
```

It looks like just like https://github.com/moby/moby/pull/45966 we're hitting `s3`/`azblob` test failures due to not implementing these exporters; we'll need to skip these tests in moby/moby.

cc @crazy-max

**Comment by thaJeztah** [comment]
Ah, bummer

**Comment by neersighted** [comment]
It looks like this results from a partial cherry-pick:
* https://github.com/moby/buildkit/commit/19969b9ae34b59a8f8e0eddf4e175089d0426bee added Azure/S3 compat flags for tests on the main branch
* https://github.com/moby/buildkit/commit/8a6503c22ddce1caae1de93f9c880cfe69e43f47 is a partial cherry pick, omitting the bits relevant to Azure/S3 tests
* https://github.com/moby/buildkit/commit/a31b349383f7e272b4fa2bcae75343a843339a17 then cherry-picked said tests, without the compat flags introduced in the above commits

A second cherry-pick applying the missing half of the changes should be sufficient.

**Comment by crazy-max** [comment]
related to https://github.com/moby/moby/pull/45966/commits/35e11f4a39934f5fdcaca06bf15616d28ff70adf, it should fine to do the same since https://github.com/moby/moby/commit/a87313497b3547c891720415846282219f0e71c0.

**Comment by thaJeztah** [comment]
I updated the vendor to include https://github.com/moby/buildkit/pull/4053



> related to [35e11f4](https://github.com/moby/moby/commit/35e11f4a39934f5fdcaca06bf15616d28ff70adf), it should fine to do the same since [a873134](https://github.com/moby/moby/commit/a87313497b3547c891720415846282219f0e71c0).

Do you mean I can remove the regex again? Or that the regex would have to be updated with some additional excludes?

**Comment by crazy-max** [comment]
> I updated the vendor to include [moby/buildkit#4053](https://github.com/moby/buildkit/pull/4053)
> 
> > related to [35e11f4](https://github.com/moby/moby/commit/35e11f4a39934f5fdcaca06bf15616d28ff70adf), it should fine to do the same since [a873134](https://github.com/moby/moby/commit/a87313497b3547c891720415846282219f0e71c0).
> 
> Do you mean I can remove the regex again? Or that the regex would have to be updated with some additional excludes?

Yes I think you can just remove it.

**Comment by neersighted** [comment]
Let's go ahead and do that in a separate PR I think, to ease cherry-picks to e.g. 23

**Comment by thaJeztah** [comment]
Ah, yes, I'm fine with doing it separately; looks like this one went green, so we could merge this (and I'll update my cherry-pick).

The v0.12 PR will of course need a  rebase after this, but I expect the rebase to be mostly trivial (famous last words).

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
