### PR TITLE
Vendor Libnetwork v0.7.0-rc.3

### LINKED ISSUE #1070: DNS message ID mismatch
Once in a while when trying to resolve a hostname from within a docker container using a Go binary I get "DNS message ID mismatch". This is happening in docker 1.11-rc2.

You can reproduce it with this script:

```go
package main

import (
    "fmt"
    "net"
)

func main() {
    for {
        _, err := net.LookupHost("google.com")
        if err != nil {
            fmt.Println(err)
        }
        fmt.Print(".")
    }
}
```

### PR DESCRIPTION
**Pull request by sanimej**
- Reverted the fix for EP join/leave in default gateway network introduced in RC2. It needs some rework.
- Fix to persist the network internal flag for bridge networks
- Fixes https://github.com/docker/libnetwork/issues/1070
- Move IPAM resource initialization out of init()
- Initialize overlay driver before network delete 

Signed-off-by: Santhosh Manohar santhosh@docker.com

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by thaJeztah** [comment]
CI is failing on one test; @sanimej is already looking into it

**Comment by sanimej** [comment]
@thaJeztah @icecrime bumped to libnetwork v0.7.0-rc.3. IT failure was because of a change introduced in RC2. It needs some rework and has been reverted. PTAL

**Comment by cpuguy83** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM thanks

**Comment by thaJeztah** [comment]
heads up! libnetwork team found a solution for the change that was reverted in v0.7.0-rc.3, and may have a v0.7.0-rc.4 ready soon. It's not a high priority issue, so it's possible we let it slip for rc4

**Pull request merged**
