### PR TITLE
Fix location of docker-{init,proxy}

### PR DESCRIPTION
**Pull request by mrueg**
Not sure why the docs point to /usr/libexec, the docker scripts in /hack seem to install them to /usr/bin

### CODE REVIEW

**Comment by justincormack** [comment]
The docs are just giving an example of where you might decide to install them.

**Comment by LK4D4** [comment]
I actually agree that it's confusing. Not any of our scripts installs them there.
@mrueg but you need to sign your commit, take a look at https://github.com/docker/docker/pull/30525#issuecomment-275818493

**Comment by justincormack** [comment]
@LK4D4 `/usr/libexec` is "The libexec/ directory contains small helper programs called by other programs" according to some interpretations of FHS, so it is a reasonable place to put these, as they are not intended to be called by the user directly.

**Comment by LK4D4** [comment]
@justincormack shouldn't we install them there then?

**Comment by vdemeester** [comment]
ping @mrueg for signing your commit.
/cc @thaJeztah too :angel:

**Comment by dnephin** [comment]
This is just an example, so I don't think it needs to match the path we use in the packages.

@LK4D4, @thaJeztah The commits are signed. Let's either merge this or close it.

**Comment by runcom** [comment]
> @justincormack shouldn't we install them there then?

on Fedora and RHEL, we install those binaries exactly under `/usr/libexec/docker`. The issue is this location isn't in $PATH and one must use "--userland-proxy-path=" flag.

**Comment by runcom** [comment]
btw, I think the example is right, and it shows a different location for init/proxy. What @mrueg is doing here is using the default locations which aren't really providing a great example of those "init-path" and "userland-proxy-path". I would rather leave this example as is.

**Comment by dnephin** [comment]
Ok, I agree.

@mrueg thanks for the contribution! I think we're happy with the current example, so we wont be changing it at this time.

**Pull request closed without merging**
