### PR TITLE
add pkcs11 build tag to deb and rpm builds

### PR DESCRIPTION
**Pull request by endophage**
Add the pkcs11 build tag to the amd64 deb and rpm generate.sh scripts then ran them to regenerate the Dockerfiles with this new tag.

The dynamically linked docker binary produced for both debs and rpms now links against libltdl.so

image

cc @tiborvass

### CODE REVIEW

**Comment by tiborvass** [comment]
Related to #21591

**Comment by tiborvass** [comment]
looks good, but will want to test it manually

**Comment by thaJeztah** [comment]
ping @tiborvass have you been able to test?

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
