### PR TITLE
Allow passing global datastore to libnetwork and v0.7.0-dev1 vendoring

### PR DESCRIPTION
**Pull request by aboch**
Allows to pass the global datastore configuration to the network controller after daemon boot.
In order to achieve this, it also reverts https://github.com/docker/docker/pull/19737

Vendoring brings:
- Fixes https://github.com/docker/docker/issues/20350
- Fixes https://github.com/docker/docker/issues/20145
- Initial Windows HNS integration
- Allow passing global datastore config to libnetwork after boot
- Set Recursion Available bit in DNS query responses
- Make sure iptables chains are recreated on firewalld reload

### CODE REVIEW

**Comment by sanimej** [comment]
@aboch Can you please cherry-pick an IT case for invalid input to embedded DNS server (6172b58b09d8fa6851e9dc671ffe82774f6b9879 in sanimej/dnsit branch)

**Comment by mavenugo** [comment]
@aboch can you please pick https://github.com/mavenugo/docker/commit/dc802b31bed2af1e6c432150f55cc8840691095d for IT on config-reload for cluster-store configurations.

**Comment by mavenugo** [comment]
@aboch the windows failures are legitimate. Failures indicate the absence of `networkOptions` function in `daemon_windows.go`. Please resolve these errors and include the IT : https://github.com/mavenugo/docker/commit/dc802b31bed2af1e6c432150f55cc8840691095d with your commit.

**Comment by thaJeztah** [comment]
Got this on Janky as well https://jenkins.dockerproject.org/job/Docker-PRs/23896/console;

```
7:07:48 # github.com/docker/docker/daemon
07:07:48 daemon/daemon.go:1646: daemon.networkOptions undefined (type *Daemon has no field or method networkOptions)
07:07:52 Build step 'Execute shell' marked build as failure
07:07:55 [PostBuildScript] - Execution post build scripts.
```

**Comment by calavera** [comment]
Glad to see this back! LGTM

@aboch don't forget to add this to the documentation about configuration reload:

https://github.com/docker/docker/blob/master/docs/reference/commandline/daemon.md#configuration-reloading

**Comment by aboch** [comment]
@mavenugo I had to change your test so that it can work on any machine. Will push it once I am done with the changes and verify it works.
@calavera I pushed the original changes to `docs/reference/commandline/daemon.md`. Can you please check if I have not missed other doc files. Thanks.

**Comment by mavenugo** [comment]
@aboch thanks. can you pls try this instead : https://github.com/mavenugo/docker/commit/bae3075c862db60f72edc3489ed4143481087870 ?

**Comment by calavera** [comment]
@aboch that information is good, but I think we should add a more detailed explanation about what happens when the cluster is reloaded.

**Comment by aboch** [comment]
@calavera Added some more information to the docs. PTAL.
Thanks.

**Comment by thaJeztah** [comment]
Flaky test is being worked on in https://github.com/docker/docker/pull/20464

**Comment by icecrime** [comment]
LGTM

**Pull request merged**
