### PR TITLE
Dry run test

### PR DESCRIPTION
**Pull request by nomadeous**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @moxiegirl perhaps it's cool if we have a repository that users can actually create pull requests against, and gordon saying "congrats!" (and giving them instructions if (e.g.) it needs a rebase or squashing)

**Comment by moxiegirl** [comment]
@thaJeztah That is a good idea. I used something similar at Bitbucket --- `docker/sandbox` ?

**Comment by nomadeous** [comment]
Yah
Sorry for the mistake :-(

**Comment by moxiegirl** [comment]
@nomadeous Hey it wasn't a mistake it was rather a clever thing to do. It was a unique experiment.

**Comment by thaJeztah** [comment]
@nomadeous no problem at all! It inspired us to update the docs and create a separate repository so that new contributors can actually test the procedure :+1: 

@moxiegirl where shall I create an issue to track that idea? This repository, or in the docs.docker.com repo?

**Comment by moxiegirl** [comment]
@thaJeztah The issue belongs on `docker/opensource` as it is about educating contributors.

**Comment by thaJeztah** [comment]
Done: see https://github.com/docker/opensource/issues/20

**Pull request closed without merging**
