### PR TITLE
DefaultDockerHost defines os specific default if DOCKER_HOST is unset

### PR DESCRIPTION
**Pull request by winiiiii**
docker api version: 1.41
DefaultDockerHost defines os specific default if DOCKER_HOST is unset
When my host does not set a value, the default value is not used

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can you explain a bit more what the issue is you're running into? Looking at `NewClientWithOpts`, I see it already sets this as a default, before applying options; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/client/client.go#L119-L125

If you want `NewClientWithOpts` to support DOCKER_HOST and DOCKER_VERSION, you can pass the `client.FromEnv` option, e.g.

```go
client, err := client.NewClientWithOpts(client.FromEnv)
```

or, with API-version negotiation enabled (generally recommended);

```go
client, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
```


I don't think we should make `WithHost()` pick the default, as it's an explicit option to set a custom host, but perhaps we could add options to replace this part of the code; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/client/options.go#L45-L55


Something like

```go
// WithVersionFromEnv overrides the client version with the version specified in
// the DOCKER_API_VERSION environment variable. If DOCKER_API_VERSION is not set,
// the version is not modified.
func WithVersionFromEnv() Opt {
	return func(c *Client) error {
		if version := os.Getenv("DOCKER_API_VERSION"); version != "" {
			return WithVersion(version)(c)
		}
		return nil
	}
}


// WithHostFromEnv overrides the client host with the host specified in the
// DOCKER_HOST environment variable. If DOCKER_HOST is not set, the host is
// not modified.
func WithHostFromEnv() Opt {
	return func(c *Client) error {
		if host := os.Getenv("DOCKER_HOST"); host != "" {
			return WithHost(host)(c)
		}
		return nil
	}
}
```

**Comment by wuguoguoya** [comment]
> Can you explain a bit more what the issue is you're running into? Looking at `NewClientWithOpts`, I see it already sets this as a default, before applying options;
> 
> https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/client/client.go#L119-L125
> 
> If you want `NewClientWithOpts` to support DOCKER_HOST and DOCKER_VERSION, you can pass the `client.FromEnv` option, e.g.
> 
> ```go
> client, err := client.NewClientWithOpts(client.FromEnv)
> ```
> 
> or, with API-version negotiation enabled (generally recommended);
> 
> ```go
> client, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
> ```
> 
> I don't think we should make `WithHost()` pick the default, as it's an explicit option to set a custom host, but perhaps we could add options to replace this part of the code;
> 
> https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/client/options.go#L45-L55
> 
> Something like
> 
> ```go
> // WithVersionFromEnv overrides the client version with the version specified in
> // the DOCKER_API_VERSION environment variable. If DOCKER_API_VERSION is not set,
> // the version is not modified.
> func WithVersionFromEnv() Opt {
> 	return func(c *Client) error {
> 		if version := os.Getenv("DOCKER_API_VERSION"); version != "" {
> 			return WithVersion(version)(c)
> 		}
> 		return nil
> 	}
> }
> 
> 
> // WithHostFromEnv overrides the client host with the host specified in the
> // DOCKER_HOST environment variable. If DOCKER_HOST is not set, the host is
> // not modified.
> func WithHostFromEnv() Opt {
> 	return func(c *Client) error {
> 		if host := os.Getenv("DOCKER_HOST"); host != "" {
> 			return WithHost(host)(c)
> 		}
> 		return nil
> 	}
> }
> ```

when i use client.NewClient("", "", nil, nil),  host  is empty, WithHost should use DefaultDockerHost,  instead of reporting an error, although NewClient is deprecated, thank you for your reply

**Comment by thaJeztah** [comment]
Yes, I'd recommend using `client.NewClientWithOpts`, because both `client.NewClient()` and `client.NewEnvClient()` are deprecated

**Comment by wuguoguoya** [comment]
> Yes, I'd recommend using `client.NewClientWithOpts`, because both `client.NewClient()` and `client.NewEnvClient()` are deprecated

ok, thank you, i am modifying and using client.NewClientWithOpts, i just think this change will be better

**Comment by thaJeztah** [comment]
>  i just think this change will be better

It's a change in behavior, and would mean that any user that uses this function to explicitly set a host would no longer receive an error-message if something is wrong with the host that's passed (which could be if (e.g.) the host is set through a variable, and that variable is unset / empty).

**Comment by wuguoguoya** [comment]
> > i just think this change will be better
> 
> It's a change in behavior, and would mean that any user that uses this function to explicitly set a host would no longer receive an error-message if something is wrong with the host that's passed (which could be if (e.g.) the host is set through a variable, and that variable is unset / empty).

I understand what you mean, thank you

**Pull request closed without merging**
