### PR TITLE
Do not relabel if user did not request it for non local volumes

### LINKED ISSUE #18005: Volume plugins fail when selinux is enabled
When a docker volume plugin is use, and docker daemon is running with --selinux-enabled, attempts to use a volume plugin will result in a confusing error message: ```Error response from daemon: no such file or directory```.  This appears to be because of selinux support, running the container with --security-opt label:disable fixes this.

Looking deeper into this, I believe this is related to [syscall_linux:138](https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/vendor/src/github.com/syndtr/gocapability/capability/syscall_linux.go#L138) where the daemon tries to set an selinux context on the volume path.  However, when using a volume plugin, path will evaluate to an empty string, hence the error message.

Strace output demonstrating this:
```
[pid  7442] read(61, "HTTP/1.1 200 OK\r\nContent-Type: appplication/vnd.docker.plugins.v1+json\r\nDate: Mon, 16 Nov 2015 09:16:08 GMT\r\nContent-Length: 3\r\n\r\n{}\n", 4096) = 133
[pid  7442] read(61, 0xc2085ae000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid  7442] write(61, "POST /VolumeDriver.Path HTTP/1.1\r\nHost: /run/docker/plugins/rexray.sock\r\nUser-Agent: Go 1.1 package http\r\nContent-Length: 27\r\nAccept: application/vnd.docker.plugins.v1+json\r\n\r\n{\"Name\":\"rexray-test-vol\"}\n", 203) = 203
[pid  7442] epoll_wait(4, {}, 128, 0)   = 0
[pid  7149] <... sched_yield resumed> ) = 0
[pid  7442] epoll_wait(4,  <unfinished ...>
[pid  7421] <... read resumed> "time=\"2015-11-16T09:16:08Z\" level=info msg=\"getting path to volume\" driverName=docker volumeID= volumeName=rexray-test-vol \n", 32768) = 124
[pid  7442] <... epoll_wait resumed> {{EPOLLOUT, {u32=2667585840, u64=140031486337328}}}, 128, -1) = 1
[pid  7421] read(39,  <unfinished ...>
[pid  7442] epoll_wait(4,  <unfinished ...>
[pid  7149] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  7149] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  7211] write(11, "{\"log\":\"time=\\\"2015-11-16T09:16:08Z\\\" level=info msg=\\\"getting path to volume\\\" driverName=docker volumeID= volumeName=rexray-test-vol \\n\",\"stream\":\"stdout\",\"time\":\"2015-11-16T09:16:08.437652525Z\"}\n", 198) = 198
[pid  7149] <... select resumed> )      = 0 (Timeout)
[pid  7149] clock[pid  7149] clock[pid  7149] clock[pid  7149] clock[pid  d  7149] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  7211] epoll_wait(4, {}, 128, 0)   = 0
[pid  7149] <... select resumed> )      = 0 (Timeout)
[pid  7442] <... epoll_wait resumed> {{EPOLLIN|EPOLLOUT, {u32=2667585840, u64=140031486337328}}}, 128, -1) = 1
[pid  7149] sched_yield( <unfinished ...>
[pid  7442] read(61, "HTTP/1.1 200 OK\r\nContent-Type: appplication/vnd.docker.plugins.v1+json\r\nDate: Mon, 16 Nov 2015 09:16:08 GMT\r\nContent-Length: 19\r\n\r\n{\"Mountpoint\": \"\"}\n", 4096) = 150
[pid  7442] lstat("", 0xc2085a6090)     = -1 ENOENT (No such file or directory)
[pid  7442] lsetxattr("", "security.selinux", "system_u:object_r:svirt_sandbox_file_t:s0", 41, 0) = -1 ENOENT (No such file or directory)
[pid  7442] write(2, "time=\"2015-11-16T09:16:08.755380971Z\" level=error msg=\"Handler for POST /containers/create returned error: no such file or directory\" \n", 135) = 135
[pid  7149] <... sched_yield resumed> ) = 0
[pid  7442] write(2, "time=\"2015-11-16T09:16:08.757670389Z\" level=error msg=\"HTTP Error\" err=\"no such file or directory\" statusCode=404 \n", 115 <unfinished ...>
```

### PR DESCRIPTION
**Pull request by rhatdan**
fixes #18005

Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
I think this is a better fix then https://github.com/docker/docker/pull/20829

Since it will fail if the user requests a relabel.  Should fix the rexray problem.

We are automatically labeling local volumes, but if the user uses other different volumes, he should request relabeling.  Then we can fail if the volume does not support the labeling.

**Comment by HackToday** [comment]
also ping @clintonskitson

**Comment by HackToday** [comment]
I tried above patch above, seems it could not work. Failed with following error
```
$ sudo ./docker-1.11.0-dev run -ti --volume-driver=rexray -v testtwo:/test busybox
permission denied
./docker-1.11.0-dev: Error response from daemon: Container command could not be invoked..
```

And docker logs are
```
Mar 02 09:24:17 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2005]: time="2016-03-02T09:24:17.166285982Z" level=debug msg="Closing buffered stdin pipe"
Mar 02 09:24:16 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2005]: time="2016-03-02T09:24:16.971304507Z" level=error msg="Handler for POST /v1.23/containers/b63e68846a4dc663bbcfa0e5efb8f336afc7d5c0e491c75c782decf108e0a802/start returned error: Container command could not be invoked."
Mar 02 09:24:15 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2005]: time="2016-03-02T09:24:15.150251640Z" level=error msg="Error unmounting container b63e68846a4dc663bbcfa0e5efb8f336afc7d5c0e491c75c782decf108e0a802: not mounted"
Mar 02 09:24:15 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2005]: time="2016-03-02T09:24:15.148944616Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/b63e68846a4dc663bbcfa0e5efb8f336afc7d5c0e491c75c782decf108e0a802/shm: invalid argument"
Mar 02 09:24:15 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2005]: time="2016-03-02T09:24:15.134551045Z" level=error msg="error locating sandbox id 7f3371375e5711701ad91e76eafd0ad82fb30c42ee2574d36b41b4bf5356155e: sandbox 7f3371375e5711701ad91e76eafd0ad82fb30c42ee2574d36b41b4bf5356155e not found"
Mar 02 09:24:08 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2005]: time="2016-03-02T09:24:08.140166342Z" level=debug msg="devmapper: UnmountDevice(hash=5a0cb8fafadc7a8861896e510f5132fde57bcd73b7766eebf60b3e173fda249a) END"
Mar 02 09:24:08 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker
```

**Comment by rhatdan** [comment]
@HackToday Could you print out the name of the bind.Driver and the bind.Mode before the Requires Relabel check?

**Comment by HackToday** [comment]
@rhatdan  I would have access environment tomorrow, right now, at home, I could not access that. :(

**Comment by rhatdan** [comment]
@HackToday Ok, this patch is supposed to prevent all non `local` volumes from doing the relabel, unless the user requests it.  The code above adds 'z" to the bind.Mode if the Driver is local which forces the relabel.  In the current code, the relabel is forced on all volume drivers which I believe is causing the issue with rexray, and other volumes that do not support XATTR (SELinux) labels.

I like this change better since we will still get failures if a user tries to mount a volume like rexray and specifies :Z or :z

**Comment by clintonskitson** [comment]
@rhatdan Confirmed, this patch works as well.

**Comment by rhatdan** [comment]
Excellent, I think this is the patch that should be merged into docker.

**Comment by thaJeztah** [comment]
This fixes https://github.com/docker/docker/issues/18005 ?

**Comment by rhatdan** [comment]
Yes it should.

**Comment by HackToday** [comment]
hi @rhatdan  as another issue https://github.com/docker/docker/issues/20855 which prevent me from verify your fix here, But I think if coreos works, it should work with atomic, Right?

Also, for our cases, since this fix can only be merged in 1.11.0 or 1.10.*, But atomic not integrated such new version, Is it possible to have some work-around for atomic ? (means, still enable selinux, but need user do something when run containers with volume driver)

**Comment by rhatdan** [comment]
If this gets merged into 1.11.0 we will cherrypick it into our docker-1.10 for Fedora and RHEL, or if it ends up in 1.10.3 we would upgrade to this.

**Comment by runcom** [comment]
ping @cpuguy83 @calavera

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by cpuguy83** [comment]
:+1 looks good.

**Comment by rhatdan** [comment]
Nice.

**Comment by miry** [comment]
@rhatdan is this patch merged in 1.10.3?

**Comment by thaJeztah** [comment]
@miry yes; just follow the link above: https://github.com/docker/docker/pull/21011

**Comment by miry** [comment]
For some reason I need to run in `privileged` to access the folder. 

```
$ docker run -ti --volume-driver=rexray -v testtwo:/test:rw busybox              
/ # touch /test/1
touch: /test/1: Permission denied 
```

```
$ docker run --privileged -ti --volume-driver=rexray -v testtwo:/test:rw busybox
/ # touch /test/1
/ #
```

**Comment by thaJeztah** [comment]
@miry could you open an issue for that? Better than discussing it on a merged PR; make sure to provide info about your setup (at least `docker version` and `docker info`)

**Pull request merged**
