### PR TITLE
Docker Toolbox Updates fixes #14561

### LINKED ISSUE #14561: Rewrite Mac installation for toolbox
Toolbox installation see [internal requirements](https://docker.atlassian.net/wiki/display/CORE/Docker+Toolbox+PRD)

### PR DESCRIPTION
**Pull request by moxiegirl**
- Tested Mac/iterated with Jeff on fixes
- Waiting on formal uninstall;manual now
- 4 hour work
- Fixe #14562 converting Windows to Mac
- Found errors in installer need fixes/another iteration
- Updated as far as possible with limited installation
- 3 Hours work
- Entering comments from PR review
- New screen captures and migration material
- Entering Sven's comment
- Testing with powershell, Seb's comments
- Fix link in upgrade
- Minor tweaks to http and typos
- Adding deprecation note

Signed-off-by: Mary Anthony mary@docker.com
(cherry picked from commit 6ca22add1845ca87ba9a3ec0c319a70f981545b2)

Conflicts:
    docs/installation/mac.md
    docs/installation/windows.md

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by thaJeztah** [comment]
@moxiegirl apart from the images, this is only whitespace changes, is that correct? https://github.com/docker/docker/pull/15514/files?w=1

Not sure if all whitespace changes are related (sorry, checking on my phone)

**Comment by moxiegirl** [comment]
@thaJeztah I thought you'd be asleep.  This pr was left out of the cherry pick cycle.  It is mostly images yes...the original PR was a while back.  If you spot any issues eagle eye...:-) please feel free to file an issue.

**Comment by thaJeztah** [comment]
@moxiegirl never asleep, always watching LOL. Will do! just noticed it was whitespace only in this one :-)

**Pull request merged**
