### PR TITLE
Remove CLI specific information for API error messages. Issue #17147

### PR DESCRIPTION
**Pull request by mrfuxi**
Signed-off-by: Karol Duleba mr.fuxi@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
Change LGTM, but you'll have to fix some tests that depend on that output :smile_cat:

**Comment by mrfuxi** [comment]
Had some problems last night running them. Will try again today

**Comment by mrfuxi** [comment]
Looks like Jenkins broke again. Can someone look at the build please?
Other than that, does this look right @calavera

**Comment by thaJeztah** [comment]
Yes, looks like the userns CI is a bit funky, I'll trigger a rebuild

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Won't let me merge since I'm on mobile and usersns is broken

**Comment by thaJeztah** [comment]
@cpuguy83 want me to merge, or trigger Janky again?

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by vdemeester** [comment]
I think we can merge, userns errors aren't related (and this change doesn't affect userns at all) so it feels safe to merge :stuck_out_tongue_closed_eyes:

**Comment by thaJeztah** [comment]
Thanks @vdemeester 

And thanks @mrfuxi for contributing!

**Pull request merged**
