### PR TITLE
Updating it with names of Two Indian Warriors

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**
**- What I did**
As suggested above, I've updated the file with the names of Two great Indian Warriors.

**- Description for the changelog**

Added two more names in the namesgenerator.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by eriksjolund** [comment]
How historic warriors are portrayed often depends on political opinion. I think it is better leaving that out.

**Comment by Saurabh-Thakre** [comment]
> How historic warriors are portrayed often depends on political opinion. I think it is better leaving that out.

Sorry, @eriksjolund I have little different thoughts on this. The reason I wanted this PR to get merge is that I see there are so many names with great persons on the list, and I would like to have two Indian names so we could show that We're keeping as diverse as we can. I believe in diversity, and practices that we can follow to ensure that.

Personally, I don't think there is any political opinion needed to make sure these are the true warriors and I didn't know that political role occupies important space here.
I'm fine if it's not getting merged, I just want to speak out about what I felt. Thank you for your inputs.

**Comment by milindw96** [comment]
+1 @Saurabh-Thakre  

@eriksjolund I feel u should plz have a look to  https://mr.wikipedia.org/wiki/%E0%A4%B6%E0%A4%BF%E0%A4%undersatand some history B5%E0%A4%BE%E0%A4%9C%E0%A5%80_%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%B0%E0%A4%BE%E0%A4%9C

**Comment by Shivkumar13** [comment]
+1 @Saurabh-Thakre 

I really don't think this is something that depends upon a political opinion. We should definitely follow good diversity practices. Thanks for bringing this up!

**Comment by hsirsulw** [comment]
+1 @Saurabh-Thakre 
I agree with Saurabh, and don't think it will become a political matter, We have already added many warriors and leaders names to the list.

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
https://github.com/moby/moby/blob/6c3d2b402f4b2b6a5bac4765606ab1c325c185c7/pkg/namesgenerator/names-generator.go#L120

The name list is limited to `notable scientists and hackers`

**Comment by Saurabh-Thakre** [comment]
> https://github.com/moby/moby/blob/6c3d2b402f4b2b6a5bac4765606ab1c325c185c7/pkg/namesgenerator/names-generator.go#L120
> 
> The name list is limited to `notable scientists and hackers`

Sure. I think I'd have to rework the PR as this list is limited to scientists and hackers. Thanks, @AkihiroSuda , appreciated. That being said I will close this one and will create another PR :)

**Pull request closed without merging**
