### PR TITLE
Update `images` cli reference with reference filter

### PR DESCRIPTION
**Pull request by vdemeester**
Follow-up for #27872 on docs.

/cc @thaJeztah @mstanleyjones 

:frog: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
@vdemeester can you also address https://github.com/docker/docker/pull/27872/files#r87613630 ?

**Comment by vdemeester** [comment]
Ah right, forgot about that :sweat:

**Review by thaJeztah — APPROVED** [review]
LGTM, but needs a rebase

**Pull request merged**
