### PR TITLE
Make 'docker push' faster at the small expense of extra registry disk space

### PR DESCRIPTION
**Pull request by rboyer**
Docker push currently uses default gzip settings to ship layers to the registry server.  This is somewhat cpu intensive and annoying when doing frequent pushes (as you would when inserting Docker into your CI pipeline).

Instead of using the default gzip settings use `gzip.BestSpeed` which is faster but compresses less completely than the defaults.  This pushes gzip closer to Google's Snappy compression library in spirit (["high speeds and reasonable compression"](https://code.google.com/p/snappy/)).

Timing comparision using the `google/golang` image over localhost into a sandbox registry:

```
# stock docker 1.3.1
$ time sudo docker push localhost:5050/google/golang
...
real    1m22.158s
user    0m0.217s
sys 0m0.138s

# docker 1.3.1 with the BestSpeed change
...
real    0m46.427s
user    0m0.224s
sys 0m0.133s
```

This is somewhat related to https://github.com/docker/docker/issues/7291 but that issue is locked from non-contributor comments.

### CODE REVIEW

**Comment by bobrik** [comment]
@crosbymichael I can open a proposal.

I'm thinking about adding cli flags for `docker push`. Base images could be pushed with best compression since they don't change that often, but changing layers on top of them could be compressed with faster compression level/algorithm. What do you think?

```
docker push --compression-algo=gzip --compression-level=3 my-image
```

**Comment by crosbymichael** [comment]
@bobrik Have you or are you able to create some benchmarks on the different compression algos and levels for docker images.  I know the main reason why we don't use compression is because of close CPU on a few of the providers causing pulls to be extremely slow when pulling and pushing images.  

Maybe this is just an edge case but I'm not sure we have any real benchmarks.  This may give us a better idea if we can change the default algo used with docker or if we are able to make a smart decision on what to use based on the machine. It may help by us not having to add a few of these flags to `push` and `pull`.  

What do you think?

**Comment by unclejack** [comment]
I think we need to pursue the option of using cgzip or shelling out to gzip first before we attempt to add other flags. This would be far more useful than adding a ton of flags.

Please keep in mind that the `compress/gzip` package has lower compression ratio than the regular gzip binary found on most distributions. The lower compression ratio and lower performance should be good reasons to pursue shelling out to `gzip` first.

**Comment by bobrik** [comment]
Ok let's discuss cgzip or shelling out to gzip in #10181 first. We can get back to flags later.

**Comment by shouze** [comment]
:+1: for compression

**Pull request closed without merging**
