### PR TITLE
Followup commit to https://github.com/docker/docker/pull/12986 

### PR DESCRIPTION
**Pull request by psankar**
Followup commit to https://github.com/docker/docker/pull/12986 where the information about the mailing lists, IRC channels, etc. are copied from the CONTRIBUTORS.md file to the README.md file also.

### CODE REVIEW

**Comment by jfrazelle** [comment]
I dont think this needs 3 commits can you please squash them

**Comment by psankar** [comment]
Even for the HTML tag removal, you do not need them to be individual micro-commits ? In my past doc submission patches (not for docker though), I was always told to split into micro-commits without merging such changes in a single commit. Thanks for the review.

**Comment by jfrazelle** [comment]
I think 1 will suffice

**Comment by psankar** [comment]
Merged the commits into a single commit. Please check again. Thanks.

**Comment by moxiegirl** [comment]
LGTM

ping @docker/docs-owners

**Comment by psankar** [comment]
Ping. Can someone either merge or deny it ? Thanks.

**Comment by moxiegirl** [comment]
@psankar We required two docs maintainers to merge. I'll ping them again.  ping @thaJeztah @jamtur01 @fredlf @SvenDowideit

**Comment by thaJeztah** [comment]
Sorry, missed the first ping (docs-owners doesn't work for me)

LGTM (I restarted the failed W1ndows build for good measures).

**Comment by fredlf** [comment]
LGTM. Sorry to be slow, was out on vacation last week.

**Pull request merged**
