### PR TITLE
fix libseccomp where version < 2.2.1

### PR DESCRIPTION
**Pull request by jessfraz**
maybe we can try and get them to up those versions ping @tianon

### CODE REVIEW

**Comment by tianon** [comment]
I don't think they'd consider bumping a major core library like that, except maybe in backports. :disappointed:

Regardless, this LGTM since building our own libraries to link packaged binaries against is dangerous territory so I'm happy to see any amount of that go.

**Comment by jfrazelle** [comment]
ya me too good riddance, so it _is_ in backports so wooooooop

**Comment by tianon** [comment]
Oh interesting -- I see it in wheezy-backports (but not jessie-backports),
so that makes me hopeful that such a thing might be accepted for jessie.

**Comment by hqhq** [comment]
@jfrazelle Sorry I don't understand this change, does this mean the deb package we build for ubuntu trusty will not support seccomp?

**Comment by jfrazelle** [comment]
it will not, the version is not high enough

**Comment by hqhq** [comment]
@jfrazelle Then why not just compile from source code like we do in [Dockerfile](https://github.com/docker/docker/blob/master/Dockerfile#L131-L143) ? Correct me if I missed something.

**Comment by jfrazelle** [comment]
So the way debs work is they install the header files from the other debs
they have access too if we link to a version the deb does not have access
too the binary will not run

**Comment by keloyang** [comment]
@jfrazelle  do you means the failure of " dpkg-shlibdeps: error: no dependency information found for /usr/lib/libseccomp.so.2” ?  if add the following to hack/make/.build-deb/rules:
```
override_dh_shlibdeps:
       dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
```
it can build the deb and the deb works for seccomp, WDYT ?

**Comment by hqhq** [comment]
@keloyang I think you can open a new PR and ping @jfrazelle , so we can see the whole change, I think we need to figure out a way to make a docker deb for ubuntu trusty which has seccomp supported.

**Pull request merged**
