### PR TITLE
goroutine fairness is not guaranteed causing the hang with GCCGO (x86 GCCGO CI)

### PR DESCRIPTION
**Pull request by brahmaroutu**
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
Moving it up makes sense since now the "continue" when n == 0 won't skip it.

**Comment by duglin** [comment]
LGTM

**Comment by brahmaroutu** [comment]
@LK4D4 can you please review this?

**Comment by aaronlehmann** [comment]
The call to `callSchedulerIfNecessary` doesn't feel right to me. What deadlock scenario is being prevented? If the code depends on the order in which goroutines are scheduled, I strongly feel that the code should be fixed to be more robust. Having a gccgo-only call to invoke the scheduler doesn't seem like the right fix.

At the very least, there should be a detailed comment explaining why we need this hack. But again, there must be a better way.

**Comment by duglin** [comment]
All it does is allow the runtime to switch to a different thread instead of getting stuck on this one. Our gcc-go folks are looking into a fix for gcc-go but in the meantime just moving this call up in the loop fixes a hang in our unit testcases - iotuils TestBufReaderCloseWithReaderCloser(). 

With simpleReaderCloser.Read() returning so fast the for-loop in bufReader.drain() becomes a thread hog.  There's actually a bug in that unit tests which I'll submit a PR for in a few minutes, but in the meantime since this call to callSchedulerIfNecessary() is already there, we might as well move it to a better spot.  :-)

**Comment by brahmaroutu** [comment]
@aaronlehmann This is gccgo only call, to avoid the hang. It will not affect the regular Golang execution flow.
If you have a better suggestion I am happy to try it out. 
Issue is that go-routines does not relinquish their execution run. Please see the following conversation https://groups.google.com/forum/#!msg/golang-nuts/uxnfIytdO7Y/Vmp7nHfk7oEJ  
sync.Mutex is a low-level synchronization primitive and does not guarantee fairness.

**Comment by aaronlehmann** [comment]
This makes more sense to me after reading the golang-nuts thread. Here's my understanding of what happens: `drain` is designed to read as fast as it can into a buffer, and if it can't keep up with the data source, it may read continuously, without yielding the goroutine and giving other goroutines a chance to consume the data.

I think the real problem is that we buffer incoming data without any size limit or throttling. The scheduler call works around one effect of this design problem, but there are other problems that can result, like running out of memory. I think a saner design would cap the buffer size, or pass data between goroutines with a buffered channel.

That said, I'm okay with this as a short-term fix. It's not really reasonable to ask you to redesign this piece of code in order to make Docker work with a particular compiler :). But I'd really appreciate it if you could add a comment explaining why the scheduler call is necessary. It was quite mysterious to me when I first encountered it last week.

I also wonder if we should make the scheduler call happen with the standard Go compiler, as well. If the code works as is with the standard Go compiler, that may just be a matter of luck. I don't know of any guarantee that a call to Lock will yield. Explicitly yielding seems safer than depending on `sync.Mutex` to do it.

**Comment by estesp** [comment]
I think your last push included an errant change in the commit from your standardized errors work (not to mention it will break when committed in the right PR because of `golint` comment doesn't match name error).  Repush when you get a chance.

**Comment by brahmaroutu** [comment]
@estesp thanks, removed extra file.

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
