### PR TITLE
Added a shortcut to run tests from within a docker, #11019

### LINKED ISSUE #11019: Makefile and make.sh don't have the same "targets" they should
**Summary**: Users can run `make test` but  have to run `make.sh binary cross test-unit test-integration test-integration-cli test-docker-py`. There might be other differences.

**Proposed solution**:

The `make.sh` command should accept arguments with the equvalent values to the make targets.  This should improve the UX and also reduce complexity in doc management. Win-win.

### PR DESCRIPTION
**Pull request by Plantain**
Closes #11019

### CODE REVIEW

**Comment by tiborvass** [comment]
@Plantain Thanks for your contribution! I added "Closes #11019" to your description, next time don't forget to add it it helps close the correct issue :)

**Comment by tiborvass** [comment]
LGTM

Ping @tianon

**Comment by tianon** [comment]
If we do this, I think we need to change the `Makefile` to actually use it so that we don't have the same list twice (which will inevitably get out of sync).

I'm on the fence on whether I like this, though.  Doesn't this make it less obvious to the user which bundles are actually executed?

**Comment by jfrazelle** [comment]
whats wrong with ./hack/make.sh w no arguements... that does everything :D

**Comment by jfrazelle** [comment]
I really am kinda a -1 on this because it is an extra level of abstraction I do not think we need, seeing as it could bring about this or the makefile to get out of sync with one another. I think the makefile is perfect for the level of abstraction we need.
and i agree with
> Doesn't this make it less obvious to the user which bundles are actually executed?
if anything the user can run `hack/make.sh` with no arguments and it will run all the test which is basically this and we already have that
Sorry!

**Pull request closed without merging**
