### PR TITLE
37889 partial metadata

### LINKED ISSUE #37889: Missing partial metadata for fluentd
https://github.com/moby/moby/blob/d6a7c22f7b9aa028623ef8c7cb31d1bb04dd9d84/daemon/logger/fluentd/fluentd.go#L166

In this case it is not enough to set the boolean. It is also important to add values of `PLogMetaData` to data.
i.e.
```go
if msg.PLogMetaData != nil {
    data["partial_message"] = "true"
    data["partial_id"] = msg.PLogMetaData.ID
    data["partial_ordinal"] = strconv.Itoa(msg.PLogMetaData.Ordinal)
    data["partial_last"] = strconv.FormatBool(msg.PLogMetaData.Last)
}
```
The same extension is needed for journald: https://github.com/moby/moby/blob/9c65b2206dbc4d950fcf40f94c9c05bd9130536c/daemon/logger/journald/journald.go#L107

### PR DESCRIPTION
**Pull request by vatcher**
Fixes #37889 Missing partial metadata

- Added additional metadata for partial logging messages
- Supports full metadata for partial logging messages

### CODE REVIEW

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Derek add label: rebuild/janky

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan PTAL

**Comment by anusha-ragunathan** [comment]
janky failure due to: 
```01:14:04 daemon/logger/journald/journald.go:1::warning: file is not gofmted with -s (gofmt)
01:14:04 daemon/logger/journald/journald.go:1::warning: file is not goimported (goimports)
```

New fields need to be documented at https://docs.docker.com/config/containers/logging/journald/ and https://docs.docker.com/config/containers/logging/fluentd/

**Comment by opteemister** [comment]
Any updates on this? It would be very helpful to have these flags. To concat Docker logs in fluentd.

**Comment by alexei38** [comment]
For fluentd merged on this RR https://github.com/moby/moby/pull/38952
It is already possible to use in night build

I Use https://github.com/fluent-plugins-nursery/fluent-plugin-concat

```
<filter>
  @type concat
  key log
  partial_key partial_last
  partial_value false
  separator ""
  use_first_timestamp true
</filter>
```

**Comment by opteemister** [comment]
@alexei38 thanks for letting know 👍

**Comment by thaJeztah** [comment]
@vatcher could you rebase this PR (as the first commit is no longer needed)?

**Comment by crosbymichael** [comment]
Feel free to re-open when you have time to rebase this PR on the previous fluentd change that was merged. 

Thanks!

**Pull request closed without merging**
