### PR TITLE
Revendor Microsoft/hcsshim @ v0.6.2

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Bumps Microsoft/hcsshim to v0.6.2

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@soccerGB FYI

**Comment by jhowardmsft** [comment]
@thaJeztah @johnstep PTAL. 

PS restarted z 😐

**Comment by jhowardmsft** [comment]
z started yet again...

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @johnstep PTAL

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
All ✅ now

**Pull request merged**
