### PR TITLE
correct the flag comments

### PR DESCRIPTION
**Pull request by hqhq**

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by hqhq** [comment]
Sorry for the mistake, added my SOB.

**Comment by jfrazelle** [comment]
@rhatdan this lgtm but I think you know best :D

**Comment by crosbymichael** [comment]
ping @vieux for review

**Comment by vieux** [comment]
LGTM

**Comment by rhatdan** [comment]
@jfrazelle Not sure why I would have a comment on this?

**Comment by jfrazelle** [comment]
because that was your patch no? the help output

**Comment by rhatdan** [comment]
I don't recall ever touching any of the data around --flagname.

**Comment by vbatts** [comment]
@rhatdan you must be tagged in @jfrazelle brain for attribution for _all_ help output, instead just _just_ getting the output sent to stdout. :-)

**Comment by jfrazelle** [comment]
yes exactlyyy :)

**Pull request merged**
