### PR TITLE
Cleanup volume integration tests

### PR DESCRIPTION
**Pull request by thaJeztah**
Some changes to these tests;

### Improvements to TestVolumesInspect

- use the volume-information that's returned by VolumeCreate as "expected"
- don't use an explict name for the volume, as it was only used to reference
  the volume for inspection
- improve the test-output on failure, so that "expected" and "actual" values
  are printed

Without this patch applied;

    === RUN   TestVolumesInspect
    --- FAIL: TestVolumesInspect (0.02s)
     	volume_test.go:108: assertion failed: false (bool) != true (true bool): Time Volume is CreatedAt not equal to current time
    FAIL

With this patch applied;

    === RUN   TestVolumesInspect
    --- FAIL: TestVolumesInspect (0.02s)
        volume_test.go:95: assertion failed: expression is false: createdAt.Truncate(time.Minute).Equal(now.Truncate(time.Minute)): CreatedAt (2018-11-01 16:15:20 +0000 UTC) not equal to creation time (2018-11-01 16:15:20.2421166 +0000 UTC m=+13.733512701)
    FAIL

### Enable volume tests on Windows

These tests don't seem to have anything Linux-specific, so enable them on Windows

### CODE REVIEW

**Comment by thaJeztah** [comment]
🤞 if they indeed work fine on Windows 😄

**Review by vdemeester — APPROVED** [review]
SGTM :ticket:

**Comment by thaJeztah** [comment]
Whoops; left some debugging code in there when testing the failure `.now.Add(time.Hour)` likely won't make the test pass LOL

**Comment by thaJeztah** [comment]
Fixed 😂

**Review by AkihiroSuda — APPROVED** [review]

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
