### PR TITLE
Bday comments after23rd

### PR DESCRIPTION
**Pull request by moxiegirl**
Updating with comments from the party contributors.
Adding some content tweaks based on email from Steve.

Signed-off-by: Mary Anthony mary.anthony@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
Super weird this stuff shouldn't have been merged into `docs` yet so I"m not sure why merge requests.

**Comment by moxiegirl** [comment]
This merge is into `docs` not master.  The last merge into `docs` was a couple of days ago, Sunday. This change didn't exist then: https://github.com/docker/docker/commit/617f18b0011b45a9ef71d4adb45b3ca45132e1e6

Can you take a look. @tiborvass tell me what is going on

**Comment by moxiegirl** [comment]
@SvenDowideit 
```
"yeah, I use `git cherry-pick -x -m0` - which uses the PR's commit message 
```
These are the same 27 commits it is borking on
Can you give me  L-G-T-M please? My local build is fine.

**Comment by moxiegirl** [comment]
@jfrazelle Hey Jess, I'm continually getting broken builds because of the 27 commits Sven made with the `-m0` option --- at least that is how I'm reading these breaks. Can you confirm I'm reading the build log correctly? If so, I'll merge this. Ty.

**Comment by jfrazelle** [comment]
Yeah I would say so

**Pull request merged**
