### PR TITLE
builder-next: close build context upload on cancel

### PR DESCRIPTION
**Pull request by tonistiigi**
fix https://github.com/moby/buildkit/issues/1138

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Review by tiborvass — APPROVED** [review]
Confirmed the fix

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tonistiigi does this affect 18.09 as well? If so, could you open backport for both 18.09 and 19.03 ?

**Comment by tonistiigi** [comment]
@thaJeztah 18.09 is affected as well but I don't think this is severe enough to need a backport to there

**Comment by thaJeztah** [comment]
it seemed a low-risk backport, hence me thinking it would qualify

**Pull request merged**
