### PR TITLE
Removes bind dir creation in daemon start.

### LINKED ISSUE #11644: Remove bind dir creation from daemon.setHostConfig
In `setHostConfig` under `daemon/start.go`, bind dirs are being created if they don't already exist.
This is redundant and short-circuiting the underlying volume subsystem (`volumes/repository.go`)

### PR DESCRIPTION
**Pull request by matthewkmayer**
Closes #11644 .

### CODE REVIEW

**Comment by matthewkmayer** [comment]
Sad, forgot to remove some unused imports.  Will fix.

**Comment by cpuguy83** [comment]
Note for reviewers, this should be handled by volumes/repository.go

**Comment by crosbymichael** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
@matthewkmayer thanks. can you please squash commits into one and `push -f` to your branch?

**Comment by icecrime** [comment]
LGTM

**Pull request merged**
