### PR TITLE
Automagically comment on style issues inline on PRs.

### PR DESCRIPTION
**Pull request by sevki**
This was a sideproject that proved to be useful before, I've added the
ability to traverse commits in a PR as well as a single commit. More
detail about this on sevki.org/joker.

```
 joker -repo=$REPO_NAME \
       -owner=$REPO_OWNER \
   -token=$GH_TOKEN \
   -pr=$PR \
   -scanner=golint
```

If the scanner flag is todo joker will parse comments in

```
 // TODO(sevki): write better documentation
```

format in the source and open issues assign them to people on github.
Joker can be easily extended to do go/vet or go/build analysis just
as easily as it does golint. Which is why there is a hack/github.sh

based on @icecrime's PR #14780

### CODE REVIEW

**Comment by jfrazelle** [comment]
cool project ;)

**Comment by sevki** [comment]
@jfrazelle
 high praise

**Comment by jfrazelle** [comment]
So I think this is something we could add to the Gordon bot possibly

**Comment by jfrazelle** [comment]
Yeah this is perfect for Gordon :) I'll checkout adding it tomorrow

**Comment by calavera** [comment]
yeah, I think it would work better in leeroy, other project could benefit of it.

**Comment by jfrazelle** [comment]
ok cool I'm going to close this here and we can continue talking about it as integration into https://github.com/jfrazelle/leeroy

**Pull request closed without merging**
