### PR TITLE
use "golang.org/x/net/context" instead of "context"

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Following on #28224 looks like a file slipped into `master` branch from 0f9fc54 with go import "context". This PR will change go to import "golang.org/x/net/context" instead of "context".

**- How I did it**

One character at a time.

**- How to verify it**

```
$ time make manpages # upon merge of PR, manpages will build
...
Step 13 : ENTRYPOINT man/generate.sh
 ---> Using cache
 ---> 1a10ea51a51f
Successfully built 1a10ea51a51f
docker run --rm \
                -v /Users/andrewhsu/src/thaJeztah-docker:/go/src/github.com/docker/docker/ \
                docker-manpage-dev
Generating man pages into ./man/man1

real    0m32.956s
user    0m0.070s
sys     0m0.082s
```

**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

🐘 

Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
Thanks! I guess we only changed the files from the "secrets" PR, and this one was merged after that

LGTM

**Comment by cpuguy83** [comment]
LGTM

We should probably add a validation until we are ready to drop 1.6 support.

**Comment by vieux** [comment]
LGTM thanks @andrewhsu

**Comment by thaJeztah** [comment]
all green, merging

**Pull request merged**
