### PR TITLE
1.11 rc2 cherry picks

### PR DESCRIPTION
**Pull request by thaJeztah**
Cherry picks for 1.11.0-rc2; contains the following PR's;

https://github.com/docker/docker/pull/21387
https://github.com/docker/docker/pull/21430
https://github.com/docker/docker/pull/21432
https://github.com/docker/docker/pull/21437
https://github.com/docker/docker/pull/21443
https://github.com/docker/docker/pull/21446
https://github.com/docker/docker/pull/21454
https://github.com/docker/docker/pull/21457
https://github.com/docker/docker/pull/21458
https://github.com/docker/docker/pull/21460
https://github.com/docker/docker/pull/21463
https://github.com/docker/docker/pull/21481
https://github.com/docker/docker/pull/21483
https://github.com/docker/docker/pull/21484
https://github.com/docker/docker/pull/21487
https://github.com/docker/docker/pull/21489
https://github.com/docker/docker/pull/21492
https://github.com/docker/docker/pull/21499
https://github.com/docker/docker/pull/21501

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tiborvass @docker/core-engine-maintainers all PR's cherry-picked cleanly, but please to be sure, and if I didn't miss a PR

**Comment by thaJeztah** [comment]
Two pull request that may need to be added (or in a separate PR);

- https://github.com/docker/docker/pull/20589
- https://github.com/docker/docker/pull/21432 (not merged yet)

**Comment by coolljt0725** [comment]
@thaJeztah  I think #20589 should be in, it fixes the deprecation caused by #20587

**Comment by thaJeztah** [comment]
@coolljt0725 can you open a separate cherry-pick PR against the bump branch for #20589? Then @tiborvass and @LK4D4 can make the decision and merge it tomorrow morning. I think that'd be the most effective way; if there's a reason to -not- merge it, we can leave it out. (I'm not sure why @LK4D4 said it wasn't needed)

**Comment by coolljt0725** [comment]
@thaJeztah  see #21506

**Comment by icecrime** [comment]
This may be missing the fix to Hub error messages expectations:

`08:35:58 FAIL: docker_cli_push_test.go:649: DockerSuite.TestPushToCentralRegistryUnauthorized`

**Comment by icecrime** [comment]
To be added: #21432.

**Comment by thaJeztah** [comment]
Added https://github.com/docker/docker/pull/21432 and https://github.com/docker/docker/pull/21437

**Comment by thaJeztah** [comment]
Added https://github.com/docker/docker/pull/20589 as well after discussing with @LK4D4 and @cpuguy83 who said it was good

**Comment by icecrime** [comment]
CI lost track of the PR progress, but the jobs are running, please don't rebuild:

Job | Link
-----|-------
janky | https://jenkins.dockerproject.org/job/Docker-PRs/25834/console
experimental | https://jenkins.dockerproject.org/job/Docker-PRs-experimental/17009/console
userns | https://jenkins.dockerproject.org/job/Docker-PRs-userns/8058/console
gccgo | https://jenkins.dockerproject.org/job/Docker-PRs-gccgo/3851/console
win2lin | https://jenkins.dockerproject.org/job/Docker-PRs-Win2Lin/24105/console

**Comment by icecrime** [comment]
FYI we have a failure in userns fixed in #21514. Otherwise it's all good.

**Comment by icecrime** [comment]
@tiborvass is carrying this to add the `-x` option to individual cherry-picks. However, all tests are green now :+1:

**Pull request closed without merging**
