### PR TITLE
Remove unnecessary check for number of commands

### PR DESCRIPTION
**Pull request by icecrime**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Testing for the number of commands in `help` output doesn't seem to
contribute much to the quality of the project, and adds additional
burden for the developer to update.

Signed-off-by: Arnaud Porterie (icecrime) arnaud.porterie@docker.com

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
Windows can be ignored because this test is skipped on Windows

**Comment by thaJeztah** [comment]
All others are green. merging

**Pull request merged**
