### PR TITLE
seccomp: add riscv64 mapping to seccomp_linux.go

### LINKED ISSUE #48454: seccomp not correctly detecting riscv64 architecture
### Description

See https://github.com/docker-library/official-images/pull/17403 for most of the context

Essentially seccomp doesn't support riscv64 right now so specifying it won't apply on a riscv64 architecture

```json
		{
			"names": [
				"riscv_flush_icache"
			],
			"action": "SCMP_ACT_ALLOW",
			"includes": {
				"arches": [
					"riscv64"
				]
			}
		},
```

but if you remove the includes it will work:

```json
		{
			"names": [
				"riscv_flush_icache"
			],
			"action": "SCMP_ACT_ALLOW"
		},
```

### Reproduce

1. On a riscv64 agent run an ubuntu docker image (default seccomp settings)
2. Run `apt-get update` and `apt-get install openjdk-21-jdk`
3. Observe the following error:

```bash
[0.024s][error][os] Syscall: RISCV_FLUSH_ICACHE not available; error='Operation not permitted' (errno=EPERM)
```

### Expected behavior

_No response_

### docker version

```bash
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.22.2
 Git commit:        24.0.7-0ubuntu4
 Built:             Wed Apr 17 20:08:25 2024
 OS/Arch:           linux/riscv64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.22.2
  Git commit:       24.0.7-0ubuntu4
  Built:            Wed Apr 17 20:08:25 2024
  OS/Arch:          linux/riscv64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:        
 runc:
  Version:          1.1.12-0ubuntu3
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.113+
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: riscv64
 CPUs: 4
 Total Memory: 15.35GiB
 Name: test-rise-ubuntu2404-riscv64-3.adoptopenjdk.net
 ID: 3ab95727-791b-4dba-b211-132e803c56b0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by gdams**
- fixes: https://github.com/moby/moby/issues/48454
- relates to https://github.com/moby/moby/commit/4c2f18f6cca5a89c1e0828a18f01e90ac40fc9b9 / https://github.com/moby/moby/pull/43553

**- What I did**

I added support for the `riscv64` architecture in Docker's seccomp profile by updating the architecture mappings. Specifically, I included `riscv64` in the `nativeToSeccomp` and `goToNative` maps in Docker's seccomp profile handling code.

**- How I did it**

- Updated the `nativeToSeccomp` map to include `"riscv64": specs.ArchRISC_V64` for proper architecture mapping.
- Updated the `goToNative` map to include `"riscv64": "riscv64"` for correct runtime architecture detection.
- Ensured that Docker’s seccomp profile now correctly applies for RISC-V-based containers.

**- How to verify it**

1. Run a Docker container on a native `riscv64` system.
2. Confirm that the `riscv_flush_icache` system call and other RISC-V-specific syscalls are correctly applied in the seccomp profile.
3. Ensure that no architecture mismatch errors or seccomp-related syscall restrictions occur for the RISC-V architecture.
4. Test the functionality of other architectures to ensure no regressions in behavior.

**- Description for the changelog**

```markdown changelog
Add support for RISC-V (riscv64) architecture in Docker's seccomp profile handling.
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by tianon — APPROVED** [review]
I tested this, although in a little bit of a roundabout way (the way I'm running into the issue on our official DOI build infrastructure, in fact :smile:)

I took this patch and applied it as-is to the vendored copy of this file in BuildKit, then used that to `docker buildx build https://github.com/adoptium/containers.git#07677395574f5d3462c3b6fdf5f6c4a0a350b683:21/jdk/ubuntu/noble`

Before:

```console
 > [3/5] RUN set -eux;     ARCH="$(dpkg --print-architecture)";     case "${ARCH}" in        amd64)          ESUM='51fb4d03a4429c39d397d3a03a779077159317616550e4e71624c9843083e7b9';          BINARY_URL='https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz';          ;;        arm64)          ESUM='d768eecddd7a515711659e02caef8516b7b7177fa34880a56398fd9822593a79';          BINARY_URL='https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.4_7.tar.gz';          ;;        ppc64el)          ESUM='c208cd0fb90560644a90f928667d2f53bfe408c957a5e36206585ad874427761';          BINARY_URL='https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_ppc64le_linux_hotspot_21.0.4_7.tar.gz';          ;;        riscv64)          ESUM='b04fd7f52d18268a935f1a7144dae802b25db600ec97156ddd46b3100cbd13da';          BINARY_URL='https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_riscv64_linux_hotspot_21.0.4_7.tar.gz';          ;;        s390x)          ESUM='c900c8d64fab1e53274974fa4a4c736a5a3754485a5c56f4947281480773658a';          BINARY_URL='https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_s390x_linux_hotspot_21.0.4_7.tar.gz';          ;;        *)          echo "Unsupported arch: ${ARCH}";          exit 1;          ;;     esac;     wget --progress=dot:giga -O /tmp/openjdk.tar.gz ${BINARY_URL};     echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -;     mkdir -p "/opt/java/openjdk";     tar --extract         --file /tmp/openjdk.tar.gz         --directory "/opt/java/openjdk"         --strip-components 1         --no-same-owner     ;     rm -f /tmp/openjdk.tar.gz /opt/java/openjdk/lib/src.zip;     find "/opt/java/openjdk/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf;     ldconfig;     java -Xshare:dump;:
/tmp/openjdk.tar.gz: OK
+ tar --extract --file /tmp/openjdk.tar.gz --directory /opt/java/openjdk --strip-components 1 --no-same-owner
 /tmp/openjdk.tar.gz /opt/java/openjdk/lib/src.zip
+ sort -u
+ find /opt/java/openjdk/lib -name *.so -exec dirname {} ;
+ ldconfig
+ java -Xshare:dump
[0.018s][error][os] Syscall: RISCV_FLUSH_ICACHE not available; error='Operation not permitted' (errno=EPERM)
Error occurred during initialization of VM
Unable to synchronize I-cache
```

After:

```console
#10 exporting to docker image format
#10 sending tarball 140.4s done
#10 DONE 299.7s
```

**Comment by tianon** [comment]
(IMO it also makes sense to backport this, at the very least to v27)

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
Thanks! Yes, more tests are always appreciated. I should add a warning that (from a quick look), currently those syscall tests are run as part of the "integration-cli" suite, e.g.; https://github.com/moby/moby/blob/29f4a79edd731cb4114da71019c7713b4c18583e/integration-cli/docker_cli_run_unix_test.go#L985-L995


We froze that suite, because we want to move away from requiring the `docker` CLI itself to be used for tests defined in this repository, and where possible verify behavior without the CLI itself involved (tests involving the CLI should be part of the docker/cli repository's e2e suite). While that's not the case yet, we could possibly make an exception (and temporarily disable the check that prevents new tests are added to the integration-cli suite in CI).

Containerd also maintains a copy of the seccomp-profile; long term we should look if we can unify those (potentially moving the secomp profile to a separate module) and perhaps we should at some point look at porting those tests over as well.

Either way; that last part is definitely orthogonal.

Happy to help with the `integration-cli` part (and where needed to temporarily disable that check).

**Comment by thaJeztah** [comment]
Test-failiures should be unrelated (we have some known flakiness in master; see https://github.com/moby/moby/issues/48400.

Gave CI another kick to see if it goes green, but if it doesn't, I'll probably merge this one.

**Comment by gdams** [comment]
> Test-failiures should be unrelated (we have some known flakiness in master; see #48400.
> 
> Gave CI another kick to see if it goes green, but if it doesn't, I'll probably merge this one.

That's great! do you need me to manually kick off the backports once this is merged or do you have some automated tooling?

**Comment by thaJeztah** [comment]
We don't have automated tooling (yet); the jury was still out on how to integrate automation but limiting permissions (i.e., we generally prefer automation to not have direct write access on the repository).

So cherry-picks are still manual; feel free to open backports for the release branch(es) though!

Some quick comments on that (we really need to write that down somewhere 🙈);

When cherry-picking, we prefer using the `-x` option, so that the cherry-picked commit has a reference to the original commit; i.e, something like

```bash
git cherry-pick -s -x <commit-sha>
```

(add the `-S` if you also (GPG)sign your commits)


And for backports, we want the PR description to have the branch in the title (e.g. `[v27.x backport] ...` or `[v26.1 backport] ...`

**Comment by thaJeztah** [comment]
LOL; and of course CI hit another flaky test (`TestNetworkDBIslands` this time); I'll bring this one in

**Comment by gdams** [comment]
@thaJeztah did you intentionally not add the `process/cherry-pick/24.0` label or was that an accident?

**Comment by thaJeztah** [comment]
@gdams yes; the 24.0 branch is no longer maintained, so we generally skip it; see https://github.com/moby/moby/blob/master/project/BRANCHES-AND-TAGS.md#branches


(yet it's a bit confusing 🙈)

**Comment by gdams** [comment]
> @gdams yes; the 24.0 branch is no longer maintained, so we generally skip it; see https://github.com/moby/moby/blob/master/project/BRANCHES-AND-TAGS.md#branches
> 
> (yet it's a bit confusing 🙈)

gotcha, wanted to double check! versions are always confusing ;) I've raised all the required backports then! Thanks for getting to this so quickly! I'm slightly amazed that it's taken 2 years for someone to pick this up but glad we've finally sorted it!

**Pull request merged**
