### PR TITLE
Mark network ui endpoints unix-only

### PR DESCRIPTION
**Pull request by tonistiigi**
This should unbreak experimental janky, that was brought down by #15459

cc @jfrazelle 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
awesome! LGTM

**Comment by vdemeester** [comment]
:+1:

**Comment by mavenugo** [comment]
LGTM

**Comment by vdemeester** [comment]
hum @calavera submitted this too #15483, which one is the more appropriate ?

**Comment by calavera** [comment]
oh, I didn't see this one, let me check.

**Comment by calavera** [comment]
I think this makes sense, since we still need to figure out the networking story on Windows. Merging.

**Pull request merged**
