### PR TITLE
cli: Add valid suffixes for remaining duration options

### PR DESCRIPTION
**Pull request by aaronlehmann**
#27733 added `(ns|us|ms|s|m|h)` to the descriptions of some
duration options, but not all. Add it to the remaining options for
consistency.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Maybe we don't need to explicitly mentione ns and us?

**Comment by vieux** [comment]
adding to 1.13 to have consistency

**Comment by thaJeztah** [comment]
> Maybe we don't need to explicitly mentione ns and us?

Yes I'm actually a bit in doubt (but help me make a decision!) if it's too much information (although technically correct); in what situations would someone use us, ns, or even ms for (e.g.) `--stop-grace-period`.

I _do_ agree this must be documented somewhere, wondering what the best solution is. Perhaps a central description of each datatype ("a duration is an integer ... valid units are ...")

**Comment by thaJeztah** [comment]
discussed with @vieux, let's merge as-is, and we can discuss other options in future :)

LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
