### PR TITLE
Removed deleteContainer calls

### LINKED ISSUE #13184: remove deleteContainer() calls in integration-cli tests
In integration-cli/ there are still calls to `deleteContainer()`. This isn't needed anymore with gocheck. All calls should be removed **where it makes sense to do so**.

### PR DESCRIPTION
**Pull request by fntlnz**
fixes #13184
Signed-off-by: Lorenzo Fontana fontanalorenzo@me.com

### CODE REVIEW

**Comment by runcom** [comment]
https://github.com/docker/docker/blob/master/integration-cli/docker_cli_by_digest_test.go#L38 missed this I think

**Comment by cpuguy83** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
someone else can pick up that other one for fun :)

**Comment by runcom** [comment]
Yup I'll create a beginner issue

**Comment by fntlnz** [comment]
:grinning:  sorry for that

**Pull request merged**
