### PR TITLE
Add network mode `none` to list of possible values

### PR DESCRIPTION
**Pull request by rhuss**
Addded this to the latest published API version 1.22. However, the change should probably be applied to older API versions, too, but I don't know how far to go back (i.e. since when this is available).

### CODE REVIEW

**Comment by rhuss** [comment]
One should probably also add that a custom network name can be used as well (if not one of the given keywords). 'guess this is possible since 1.21

**Comment by thaJeztah** [comment]
Can you also add this to 1.23?

Not sure which version "none" was introduced in, guess it's a long time ago yes, would be awesome if you could check

**Comment by rhuss** [comment]
Its hard for me to check, since the API versioning in Docker isn't really strict. E.g. if I'm using a Docker 1.10 engine and specify v1.18 as API version in the REST calls then v1.22 features not present in v1.18 can still be used if it's only part of the payload. E.g. if I specify a custom network name as `Networking` value in the host config and use `v1.18` (which was Docker 1.6) in the rest call against a `v1.22` (Docker 1.10) engine, it works without a problem. The same behaviour I suspect for mode `none`.

So in order to go backwards I would need to install all versions of Docker engines which is quite tedious. 

I'll try to give it a try for the oldest supported engine by installing this one.

**Comment by rhuss** [comment]
I installed Docker 1.2.0 (API 1.14) and verified that `none` is supported here as well. So I updated all API documents from 1.15 - 1.23 (1.14 doesn't has a corresponding documentation section).

In addition I added vor 1.21 - 1.23 the explanation that any other value is taken as a custom network name.

**Comment by thaJeztah** [comment]
:heart: thank you, that is really awesome!

LGTM!

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
