### PR TITLE
Update libseccomp-golang

### LINKED ISSUE #32714: seccomp does not support multiple arguments' rules working together
@mheon @jessfraz @justincormack
Hi, all. I'm working on generating suitable seccomp profiles for any Docker container. However, I'm not quite content with the functionalities of Docker seccomp, which only support limiting syscall by its name or some argument.
I read the [default seccomp profile](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) before, and I found that you put two argument's rules into one syscall object(e.g. [Line 525](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json#L525)). Seems that you were trying to let them work together(i.e. only ALLOW when those two rules are both matched). But actually it does not work that the syscall will be allowed when any one of the two rules is matched. I verified this by testing with some customized profiles.
I'm pretty sure that `libseccomp` supports applying multiple argument's rules together(refer to [my topic](https://groups.google.com/forum/#!topic/libseccomp/juKfwujESiQ)). So I checked the source code of `libseccomp-golang`, only found that it set one condition(argument's rule) per time([Line 310](https://github.com/moby/moby/blob/master/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go#L310)). 

```
for _, cond := range conds {
	cmpStruct := C.make_struct_arg_cmp(C.uint(cond.Argument), cond.Op.toNative(), C.uint64_t(cond.Operand1), C.uint64_t(cond.Operand2))
	defer C.free(cmpStruct)

	if err := f.addRuleWrapper(call, action, exact, C.scmp_cast_t(cmpStruct)); err != nil {
		return err
	}
}
```
I was very confused with the code here. Why use `seccomp_rule_add_[exact_]array()` while only setting one rule(instead of multiple rules) a time, `seccomp_rule_add[_exact]()` could do the same. 

So, here are my questions:

1. Is it in your milestone that supporting multiple arguments(of one syscall)' rules AND'd together. If not, is this feature acceptable enough for creating a PR?

2. Is there any possible way for developers to set seccomp bpf filters for containers without using libseccomp interfaces? I'd like to limit app with more complex rules, such as limiting based on syscall sequences?

3. One more puzzle. I have difficulty in understanding the default seccomp profile. what's the meaning of the magic number `2080505856`(or `0x7C020000`) in `clone`'s rule([Line 765](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json#L765)). I've searched internet for a while but got thing.

Thanks for your attention. Looking forward to your reply.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 24
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: ubuntu-one
ID: KTSQ:V7MO:PC3E:QMPV:A3F7:4M7S:UAIQ:3JGK:GFM6:O4CD:LHDT:6OCU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

KVM guest with Ubuntu 16.04.2 LTS installed.

### PR DESCRIPTION
**Pull request by justincormack**
Fix #32714

This fixes a bug in handling of multiple arguments specifed together.

We no longer have these in the default profile, but users may in their
profiles.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

heron_chick

### CODE REVIEW

**Comment by justincormack** [comment]
This should probably be backported...

**Comment by cpuguy83** [comment]
This also bumps the minimum libseccomp version to 2.2.0 (previously 2.1.0).
Jessie only appears to support 2.1.

**Comment by cpuguy83** [comment]
Ubuntu Trusty is also a problem.

**Comment by justincormack** [comment]
Ugh. Hmm, not sure what to do about that.

**Comment by mlaventure** [comment]
`jessie-backports` and `trusty-backports` both carry the 2.2 version

**Comment by justincormack** [comment]
We have in the past been reluctant to force backports on people, but these
distros are ancient....

Cc @ijc25

**Comment by mheon** [comment]
I've been considering spinning up a branch of the bindings that includes the fix, but does not increase the minimum supported version (v2.1.x is sufficiently broken with the bindings that I'm really reluctant to continue supporting it, but it's still in use by a number of common distros). If you guys consider the 2.2.x requirement a blocker I can see about making said branch.

I'll also note that the bug is really a `runc` issue and updating the vendor here won't resolve it. The vendor here is only used to create profiles, the affected filter load functionality is only used in `runc`.

**Comment by justincormack** [comment]
@mheon ah ok, so updating here is not that important, thanks.

We have not supported 2.1 for ages/ever, so those distros generally have had seccomp disabled (although I think in a few cases we may have insisted on backports, eg arm64) so that is not an issue.

It being in `runc` makes it more complicated, as we don't want to ship different `runc` versions, patched with different library vendorings for different distros really. I see `runc` hasnt decided whether to merge https://github.com/opencontainers/runc/pull/1424 either.

I think it is a bit problematic for us to have to either drop seccomp support on distros we previously had it or not work without backports where we did before. But on the other hand that would mean we can never upgrade in effect. So maybe insisting on backports is better, and using @ijc25 excuse that its not the latest Debian helps there.

**Comment by cpuguy83** [comment]
Ping @tianon for insight on this as well.

**Comment by ijc25** [comment]
> We have not supported 2.1 for ages/ever

I'm confused, Jessie has 2.1 and we currently support seccomp there, don't we? If not then we aren't actually dropping seccomp support for Jessie by requiring 2.2 and our problem goes away...

``
find -name \*Dockerfile\* | xargs grep -l seccomp  | grep debian
./contrib/builder/deb/aarch64/debian-stretch/Dockerfile
./contrib/builder/deb/aarch64/debian-jessie/Dockerfile
./contrib/builder/deb/amd64/debian-stretch/Dockerfile
```
So we seem to support seccomp for aarch64 on Jessie, but not amd64? Unless it is somehow in the base chroot, which seems unlikely.

**Comment by justincormack** [comment]
Oh, I am misremembering the versions then. But it may be an issue on Ubuntu
16.04.

On 17 May 2017 5:09 pm, "Ian Campbell" <notifications@github.com> wrote:

We have not supported 2.1 for ages/ever

I'm confused, Jessie has 2.1 and we currently support seccomp there, don't
we? If not then we aren't actually dropping seccomp support for Jessie by
requiring 2.2 and our problem goes away...

``
find -name *Dockerfile* | xargs grep -l seccomp | grep debian
./contrib/builder/deb/aarch64/debian-stretch/Dockerfile
./contrib/builder/deb/aarch64/debian-jessie/Dockerfile
./contrib/builder/deb/amd64/debian-stretch/Dockerfile

So we seem to support seccomp for aarch64 on Jessie, but not amd64?
Unless it is somehow in the base chroot, which seems unlikely.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/moby/moby/pull/33175#issuecomment-302139895>, or mute
the thread

**Comment by thaJeztah** [comment]
Prior discussion on using backports is here; https://github.com/moby/moby/issues/22870, and a PR here; https://github.com/moby/moby/pull/23245 (which was about a broken 2.2.0 version in ubuntu I think )

**Comment by tianon** [comment]
> Perhaps a good rule of thumb is to avoid requiring backports for stable but be willing to accept them for oldstable (which is what Jessie will become the moment Stretch is released).

+1, seems sane IMO

> Given the depth of the Stretch freeze right now we could maybe accept the backport needed in this PR on the basis that very soon Jessie will be oldstable?

If it's needed to make things work, I agree.

It's a little bit of bad form (IMO), but we could _technically_ include a backported package in our own repo if we're careful about making sure it doesn't break other packages on the system when it's installed (thus removing the need for folks to explicitly add `jessie-backports` to their sources, especially since the error they'll get from APT when they don't is _really_ non-obvious to the layperson).

**Comment by cpuguy83** [comment]
So jessie is now oldstable.

**Comment by justincormack** [comment]
Closing for now as not needed here as a bugfix; will reexamine the seccomp version issue once we are shipping new Debian stable.

**Pull request closed without merging**
