### PR TITLE
Cherrypicks 1.11.0 rc2

### PR DESCRIPTION
**Pull request by tiborvass**
Cherrypicking:
#21387
#21430
#21432
#21437
#21443
#21446
#21454
#21457
#21458
#21460
#21463
#21481
#21483
#21484
#21487
#21489
#21492
#21499
#21501
#21511
#21514
#21515

### CODE REVIEW

**Comment by icecrime** [comment]
Content LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
content LGTM

**Comment by icecrime** [comment]
Experimental hits #21453.

**Comment by icecrime** [comment]
- janky, userns, win2lin, windowsTP4: :green_apple: 
- experimental: :red_circle: : but known failure
- gccgo: :yellow_heart: irrelevant here and green up to merge point

**Comment by thaJeztah** [comment]
@icecrime looks like you want a job at Jenkins?

**Pull request merged**
