### PR TITLE
Fix race in httpsRequestModifier.ModifyRequest when writing tlsConfig

### PR DESCRIPTION
**Pull request by runcom**
As title says, logs here: https://gist.github.com/runcom/2bcd9c2cc8b1dfb10328

ping @tiborvass @LK4D4 

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by tiborvass** [comment]
I wish we could just merge my PR #13375 :( Ping @dmcgowan

**Comment by runcom** [comment]
@tiborvass if your PR fixes this I'll close this :)

**Comment by runcom** [comment]
oh yes it makes this pr not needed since you're deleting httpsRequestModifier struct

**Comment by tiborvass** [comment]
@runcom yeah but don't close this PR yet

**Comment by tiborvass** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
