### PR TITLE
Support Elementary OS

### PR DESCRIPTION
**Pull request by Sarkie**
Its an Ubuntu based distro, all worked for me with the above changes. Assumed the quotes were needed because of the space.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@Sarkie can you sign-off you pull request using the instructions above? Unfortunately, we cannot accept pull-requests that are not signed-off. Thanks!

**Comment by Sarkie** [comment]
@GordonTheTurtle @thaJeztah Sorry just got these notifications, will do these asap! Sorry!

**Comment by tianon** [comment]
This looks like a dup of #11857 :+1:

**Comment by thaJeztah** [comment]
Oh, you're right!

So sorry I missed that, @Sarkie it is indeed a dup of #11857. Are you okay with closing this PR? (thanks a lot for your contribution, though!)

**Comment by Sarkie** [comment]
Boo! Ah well, thought I'd have my name in shiny lights!

**Comment by tianon** [comment]
We :heart: you anyways!!  Thanks for making the effort, and please don't
let it discourage you from making more PRs!

**Comment by thaJeztah** [comment]
Look around for other issues; maybe you find one that you like to work on, and you get your eternal position on the "list of fame". Thanks sooooo much for contributing, really appreciated

**Pull request closed without merging**
