### PR TITLE
Add the list of possible values for --log-level to help text

### LINKED ISSUE #10034: Docker --log-level implemented, but not documented
$ docker --help 2>&1 | grep log-level
  -l, --log-level="info"                 Set the logging level

This was implemented, likely as a result of https://github.com/docker/docker/issues/5198, yet it is not documented anywhere on the Docker website it seems. Also, it is not documented in man docker, and docker --help only lists the existence of the option, but not it's usage details.

### PR DESCRIPTION
**Pull request by duglin**
Closes #10034

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM - @fredlf @jamtur01 @jfrazelle @tiborvass

**Comment by SvenDowideit** [comment]
mmm, will this need bash and fish prompting changes too?

**Comment by jamtur01** [comment]
LGTM

**Comment by tiborvass** [comment]
@duglin do you think we could update the shell completions accordingly like Sven said?
But if you prefer we do this in another PR i'm fine with that too.

**Comment by duglin** [comment]
@tiborvass @SvenDowideit yep was starting to look at the completion stuff last night - never played with that stuff before so there's a learning curve for me...

**Comment by thaJeztah** [comment]
@duglin For fish, there looks to be a script to update the completions (https://github.com/docker/docker/blob/master/contrib/completion/fish/docker.fish#L4). Do we currently have completion for daemon flags in bash? I glanced over the bash completion yesterday, but didn't find anything related to that.

Perhaps @albers is willing to assist? He made some awesome changes to the bash completions, so instead of you having to figure out how they work, maybe he can help?

**Comment by albers** [comment]
I will include this in my next chunk of additions to bash completion, which will be due soon. Thanks for pointing me at it.

**Comment by thaJeztah** [comment]
Thanks, @albers!

@duglin that leaves `fish` and `zsh`. I can have a quick go at fish completions for this if you want (they don't look complicated)?

**Comment by icecrime** [comment]
LGTM: I'll update `fish` completion once this is merged (top-level flags are not currently part of the `bash` and `zsh` completions).

**Comment by albers** [comment]
I'm already working on the deamon flags.

**Comment by icecrime** [comment]
@albers Perfect thanks!

**Comment by crosbymichael** [comment]
LGTM

**Comment by albers** [comment]
@thaJeztah @icecrime bash completion for daemon flags is completed, see #10219.

**Comment by duglin** [comment]
@albers thanks a ton!

**Pull request merged**
