### PR TITLE
Revendor Microsoft\hcsshim @ v0.5.17

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Updates HCSShim to v0.5.17. 

@darrenstahlmsft @jstarks FYI.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Updated to v0.5.17 to include the finalizer changes for go 1.8 support

**Comment by cpuguy83** [comment]
Looks like you need to update your version of `vndr` possibly and re-vendor again.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Guessing the extra deps being removed is due to the docker/cli move since everything is compiling nicely.

**Comment by thaJeztah** [comment]
@jhowardmsft can you do a rebase; looks like there's a merge commit in this that's causing the DCO check to fail

**Comment by jhowardmsft** [comment]
Yeah, just done :)

**Comment by thaJeztah** [comment]
Windows has a weird failure, probably not related

```
8:49:44 open d:\temp\docker-import-281061750\repositories: The system cannot find the file specified.
18:49:44 
18:49:44 
18:49:44 ERROR: Failed 'ERROR: Failed to load d:\baseimages\windowsservercore.tar' at 05/09/2017 18:49:44
18:49:44 
```

**Comment by jstarks** [comment]
@jhowardmsft It's hard for me to see how the hcsshim changes could cause this error since they should only affect importing diff layers.

**Comment by jhowardmsft** [comment]
Yeah, it looks like a few of the new 5B nodes didn't deploy correctly for some reason - this just happened to hit a bad node. It's running on a good node now.

**Comment by thaJeztah** [comment]
Windows is 💚

**Review by mlaventure — APPROVED** [review]
LGTM

**Pull request merged**
