### PR TITLE
handle debug mode for clients

### LINKED ISSUE #19890: client debug mode doesn't work
Setting `-D` on the client doesn't do anything anymore, should have a bunch of log messages.

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #19890

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐲

**Comment by duglin** [comment]
solves #16264 too?

**Comment by cpuguy83** [comment]
Nope.

**Comment by duglin** [comment]
What does this PR do?  What output should look different?  `docker -D info`  and `ps` looks the same to me.

**Comment by cpuguy83** [comment]
There is debug logging for various things, like hijack.

**Comment by duglin** [comment]
can we get a testcase added so that we know when someone breaks this?

**Comment by calavera** [comment]
LGTM

**Pull request merged**
