### PR TITLE
before adjusting should check whether need return or not

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM 

Ping @hqhq just because I remember something about first adapting and the verifing

**Comment by hqhq** [comment]
#15390 If we want to move it to somewhere, better move it before verifying.

**Comment by Mashimiao** [comment]
Well, Though verifying functions checks a lot of config options, already adapted or not will not affect verifying. And if something  else wrong, adapting will not be needed. So I think leave adapting after verifying is better.

**Comment by hqhq** [comment]
> Though verifying functions checks a lot of config options, already adapted or not will not affect verifying

What do you mean about "already adapted or not will not affect verifying"? 
My logic is quite simple: After verifying, configs are considered as legal, but adapt could make them unlegal, and we don't have verifying afterward, so there is a potential risk here.
Verifying configs after any possible configs changing seems more reasonable to me.

Anyway, as #15390 said, we are talking about non existed bug, I think maintainers just don't care. So I don't object this PR :)

**Comment by runcom** [comment]
Fair enough, though a possible test case for this wrong err check would be useful, I'll take care of this in another PR

**Comment by calavera** [comment]
LGTM

**Pull request merged**
