### PR TITLE
Fix typo in named test and docs.

### PR DESCRIPTION
**Pull request by tophj-ibm**
Changes "deivce" to "device" in integration test and in docs

Signed-off-by: Christopher Jones tophj@linux.vnet.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
LGTM if janky is happy

**Comment by MHBauer** [comment]
Maybe here too:
```
λ ag deivce
daemon/graphdriver/devmapper/deviceset.go
528:		return fmt.Errorf("Deivce Deferred Removal Cancellation Failed: %s", err)
```

**Comment by tophj-ibm** [comment]
good call

**Comment by runcom** [comment]
LGTM

**Comment by MHBauer** [comment]
@tophj-ibm might as well fix all the typos of a type if they are found

@dug Not sure why anything would fail here if it wasn't flaky or already broken.

**Comment by calavera** [comment]
LGTM

**Pull request merged**
