### PR TITLE
Fix changed google cloud URLs

### PR DESCRIPTION
**Pull request by nickandrew**
All documentation has been moved to cloud.google.com.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@nickandrew thanks for your contribution! Would you be able to sign-off your commit using the instructions that @GordonTheTurtle gave you?

If you run into trouble, feel free to ask for assistance in the #docker-dev IRC channel, or leave a comment here. Thanks!

**Comment by SvenDowideit** [comment]
LGTM when signed :)

**Comment by crosbymichael** [comment]
@nickandrew thanks for the PR.  Sorry for the complication's with signing the commits but rules are rules.   Fee free to sign and reopen this PR when you have time and feel like it.  

Thanks for the PR and let us know if you have any questions.

**Comment by nickandrew** [comment]
Sorry, I only just saw these. The source file has been renamed; I'll open another pull request with a signed patch now.

**Comment by thaJeztah** [comment]
@nickandrew no worries! Can you add the link to the new PR here after you created it?

**Pull request closed without merging**
