### PR TITLE
Remove redundant return nil

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**- What I did**
Remove redundant return nil

### CODE REVIEW

**Comment by allencloud** [comment]
compiling error:
```
04:05:43 # github.com/docker/docker/daemon/cluster
04:05:43 daemon/cluster/cluster.go:1075: no new variables on left side of :=
04:05:43 daemon/cluster/cluster.go:1269: no new variables on left side of :=
04:05:43 daemon/cluster/cluster.go:1593: no new variables on left side of :=
```

**Comment by yuexiao-wang** [comment]
Updated and thanks

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
