### PR TITLE
Update hcsshim vendor to v0.8.20

### LINKED ISSUE #42610: Windows: If HcsShutdownComputeSystem returns ERROR_PROC_NOT_FOUND, moby leaks the container
HCS provides two functions to stop a container:
- `HcsShutdownComputeSystem` is used first, and attempts to gracefully stop the container.
- `HcsTerminateComputeSystem` is used if shutdown fails, and force stops the container.

moby uses `hcsshim.IsAlreadyStopped` to check if the error returned from `HcsShutdownComputeSystem` indicates that the container has already terminated, and only calls `HcsTerminateComputeSystem` if it is still running. However, due to a bug in `hcsshim.IsAlreadyStopped`, this function returned `true` if the error was `ERROR_PROC_NOT_FOUND`, which can be returned even if the container is left running. When this happened, moby would effectively leak the container, leaving it running in HCS, but assuming from moby's point of view that it had stopped.

### PR DESCRIPTION
**Pull request by kevpar**
Full set of changes: https://github.com/Microsoft/hcsshim/compare/v0.8.16...v0.8.20

Importantly brings in https://github.com/microsoft/hcsshim/pull/1065,
which fixes #42610.

Signed-off-by: Kevin Parsons <kevpar@microsoft.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think you used `vndr` directly to revendor. We currently had to wrap it in a script to ignore a local copy of golang's `archive` package. Can you try running `hack/vendor.sh` instead (or revert the changes in `vendor/archive` if that's faster)

```
[2021-07-09T00:26:33.174Z] The result of vndr differs
[2021-07-09T00:26:33.174Z] 
[2021-07-09T00:26:33.174Z] ?? vendor/archive/tar/example_test.go
[2021-07-09T00:26:33.174Z] ?? vendor/archive/tar/reader_test.go
[2021-07-09T00:26:33.174Z] ?? vendor/archive/tar/strconv_test.go
[2021-07-09T00:26:33.174Z] ?? vendor/archive/tar/tar_test.go
[2021-07-09T00:26:33.174Z] ?? vendor/archive/tar/testdata/
[2021-07-09T00:26:33.174Z] ?? vendor/archive/tar/writer_test.go
```

We should update the vendor-check to update the `Please vendor your package with github.com/LK4D4/vndr` message accordingly.

**Comment by thaJeztah** [comment]
Otherwise LGTM. 

Assuming we want this to be included in a docker 20.10 release (which currently uses the `moby` branch on hcsshim, I also opened https://github.com/microsoft/hcsshim/pull/1066, which back ports the fix mentioned to that branch

**Comment by thaJeztah** [comment]
also prepared https://github.com/moby/moby/pull/42613 for 20.10

**Comment by kevpar** [comment]
@thaJeztah I did not realize there was a separate vendor script, I'll try that :)

**Comment by thaJeztah** [comment]
Yes, it's a bit unfortunate that we (again) had to fork the archive package, due to a security issue in the archive package (when using under specific conditions); we should try to get rid of it (more details in https://github.com/moby/moby/issues/42402)

**Comment by kevpar** [comment]
> Yes, it's a bit unfortunate that we (again) had to fork the archive package, due to a security issue in the archive package (when using under specific conditions); we should try to get rid of it (more details in #42402)

I've created a new PR to fix the vendor error message and also allow the vendor script to work on Windows: #42634

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks for updating!

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by kevpar** [comment]
Test `TestNetworkDBIslands` in the CI seems to be failing with lots of errors like `dial tcp 172.17.0.2:10033: connect: connection refused`. This seems unrelated to the changes here.

**Comment by thaJeztah** [comment]
Yes, CI is super flaky since libnetwork was moved into this repository (it was flaky in that repository, but becomes more apparent here). Some PR's in flight to try to improve the situation (https://github.com/moby/moby/pull/42625, https://github.com/moby/moby/pull/42594)

**Comment by thaJeztah** [comment]
Failure on arm64 is a known flaky test: https://github.com/moby/moby/issues/42582

```
=== FAIL: libnetwork/drivers/bridge TestCreateParallel (0.28s)
time="2021-07-13T20:05:30Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/net31/ is not added to the store"
time="2021-07-13T20:05:30Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/net3/ is not added to the store"
    bridge_test.go:1133: Success should be 1 instead: 2
```

everything else is green

**Comment by kevpar** [comment]
Thanks @thaJeztah! :)

**Pull request merged**
