### PR TITLE
Properly stop test daemon in integration-cli

### PR DESCRIPTION
**Pull request by icecrime**
Always stop the test daemon in an attempt to fix race conditions in subsequent tests.

### CODE REVIEW

**Comment by aluzzardi** [comment]
I see a few missing ones, such as in `TestDaemonRestartRenameContainer` - was that on purpose or simply an overlook?

**Comment by jfrazelle** [comment]
omg nice find (facepalm)

**Comment by jfrazelle** [comment]
LGTM after the ones @aluzzardi mentioned are added this is going to fix so many things

**Comment by icecrime** [comment]
This was totally intentional to check if your reviews were thorough :innocent: Thanks, no idea how I missed those...

**Comment by aluzzardi** [comment]
I think there are a few trickier tests that use `d.Start()` (rather than `d.StartWithBusybox`) that might have escaped:
```
TestDaemonUpgradeWithVolumes
TestDaemonExitOnFailure
TestDaemonUnixSockCleanedUp
```

Some of them do multiple starts, not sure if deferring a single `Stop` will stop all the started daemons - could you double check?

**Comment by icecrime** [comment]
Good catch, `TestDaemonUnixSockCleanedUp` had one code path which wouldn't stop the daemon.

**Comment by jfrazelle** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
