### PR TITLE
Improve build cancelation description in CHANGELOG

### PR DESCRIPTION
**Pull request by pwaller**
The existing text didn't explain what had changed.

(See #9774)

Signed-off-by: Peter Waller p@pwaller.net

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks, LGTM (had to look it up, but apparently, both "canceled" and "cancelled" are ok :smile:)

**Comment by pwaller** [comment]
Yeah, I'm a brit so spell it 'Cancelled', but I take it that docker uses en-US, where I think it's spelled "cancelation"?.

**Comment by thaJeztah** [comment]
@pwaller well I'm Dutch, but I doubt writing it in Dutch will make it more readable :smile: Either way should be fine I think (it's just a change log)

**Comment by moxiegirl** [comment]
LGTM

**Pull request merged**
