### PR TITLE
Add proper "netgo" compiling, thanks to rsc ♥

### PR DESCRIPTION
**Pull request by tianon**
See https://github.com/golang/go/issues/9369#issuecomment-69864440!

### CODE REVIEW

**Comment by LK4D4** [comment]
Tested locally. Works.

**Comment by MalteJ** [comment]
How do I check if it works?
If it's just about compiling, it works on my machine.

**Comment by tianon** [comment]
It should compile without warnings and should produce a working binary that is 100% statically compiled (ie, `ldd bundles/$(cat VERSION)/docker-$(cat VERSION)` produces `not a dynamic executable`)

**Comment by LK4D4** [comment]
Build succeeded on drone - LGTM

**Comment by jfrazelle** [comment]
works locally LGTM

**Comment by jfrazelle** [comment]
ugh test-integration doesn't like it, but everything else does :(

On Wed, Jan 14, 2015 at 8:43 AM, Alexander Morozov <notifications@github.com

**Pull request merged**
