### PR TITLE
bump logrus

### PR DESCRIPTION
**Pull request by jessfraz**
want to try out new vendoring builder for leeroy
ping @vdemeester ;)

### CODE REVIEW

**Comment by jfrazelle** [comment]
hmmm :(

**Comment by jfrazelle** [comment]
woohoo \o/

**Comment by vdemeester** [comment]
Oh by it's working :heart_eyes_cat: :tada:

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
:tada: nice work on the vendor CI @vdemeester, happy with that!

**Pull request merged**
