### PR TITLE
[19.03] vendor: containerd 481103c8793316c118d9f795cde18060847c370e

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/containerd/containerd/compare/7c1e88399ec0b0b077121d9d5ad97e647b11c870...481103c8793316c118d9f795cde18060847c370e

- Fix error handling for task deletion
- Snapshots/devmapper: deactivate thin device after committed
- Fix fd leak of shim log
- Fix killall when use pidnamespace
- Improve ARM platform matching

**- Description for the changelog**

```markdown
- Improve ARM platform matching
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
These changes should bring in fixes w.r.t. matching the correct arm image. Note that this is _not_ a cherry-pick from master, but just bumping the containerd version to the merge commit with the fix (https://github.com/containerd/containerd/pull/3270)

**Comment by thaJeztah** [comment]
@StefanScherer @tonistiigi @cpuguy83 PTAL

**Review by StefanScherer — APPROVED** [review]
LGTM, 
internal tests show that a `DOCKER_BUILDKIT=1 docker build` now work with multi-arch images used in `FROM`.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
