### PR TITLE
Fix regression bind mounting shared.

### LINKED ISSUE #13937: [1.7.0-dev] regression: using a bindfs mount as a volume ignores bindfs
When mounting a [bindfs](http://bindfs.org/) mount as a volume in docker, docker 1.7.x ignores `bindfs`. Consider:

```ShellSession
/tmp/acltest# docker -v
Docker version 1.7.0-dev, build 5e06332
/tmp/acltest# mkdir testa
/tmp/acltest# mkdir testb
/tmp/acltest# touch testb/this-should-not-be-visible
/tmp/acltest# touch testa/this-should-be-visible
/tmp/acltest# bindfs -u 2001 -g 2001 -o nonempty testa/ testb/
/tmp/acltest# ls -l
razem 0
drwxr-xr-x 2 root root 60 cze 15 01:36 testa
drwxr-xr-x 2 2001 2001 60 cze 15 01:36 testb
/tmp/acltest# ls -l testb/
razem 0
-rw-r--r-- 1 2001 2001 0 cze 15 01:36 this-should-be-visible
/tmp/acltest# docker run --rm -ti --name acl-test -v /tmp/acltest/testb:/tmp/testb/ debian:jessie
root@f264843e4941:/# ls -l /tmp
total 0
drwxr-xr-x 2 root root 60 Jun 14 23:36 testb
root@f264843e4941:/# ls -l /tmp/testb/
total 0
-rw-r--r-- 1 root root 0 Jun 14 23:36 this-should-not-be-visible
```

This used to work ([and was used](https://github.com/docker/docker/issues/7198#issuecomment-71644795)) in 1.5.x:

```ShellSession
/tmp/acltest # docker -v
Docker version 1.5.0, build a8a31ef
/tmp/acltest # mkdir testa
/tmp/acltest # mkdir testb
/tmp/acltest # touch testb/this-should-not-be-visible
/tmp/acltest # touch testa/this-should-be-visible
/tmp/acltest # bindfs -u 2001 -g 2001 -o nonempty testa/ testb/
/tmp/acltest # ls -l
total 8
drwxr-xr-x 2 root root 4096 Jun 15 01:28 testa
drwxr-xr-x 2 2001 2001 4096 Jun 15 01:28 testb
/tmp/acltest # ls -l testb/
total 0
-rw-r--r-- 1 2001 2001 0 Jun 15 01:28 this-should-be-visible
/tmp/acltest # docker run --rm -ti --name acl-test -v /tmp/acltest/testb:/tmp/testb/ debian:jessie
root@4c3764b08aad:/# ls -l /tmp
total 4
drwxr-xr-x 2 2001 2001 4096 Jun 14 23:28 testb
root@4c3764b08aad:/# ls -l /tmp/testb/
total 0
-rw-r--r-- 1 2001 2001 0 Jun 14 23:28 this-should-be-visible
```

Actual Results:
- docker volume-mounts the directory as if it is not bindfs-mounted

Expected Results:
- docker should volume-mount the directory in accordance to bindfs-mount settings (as 1.5.x did)

Docker 1.5.x system info:
```ShellSession
# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef
# docker info
Containers: 60
Images: 340
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 460
Execution Driver: native-0.2
Kernel Version: 3.19.0-16-generic
Operating System: Ubuntu 15.04
CPUs: 8
Total Memory: 47.16 GiB
Name: woodward
ID: TQ5P:IBY2:OKHL:EWZH:LGTA:GDOF:K3YZ:KC3R:3ERG:OQ32:AVTF:LVKX
WARNING: No swap limit support
# uname -a
Linux hostname 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/issue.net
Ubuntu 15.04
```

Docker 1.7.x system info:
```ShellSession
$ docker version
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 5e06332
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 5e06332
OS/Arch (server): linux/amd64
$ docker info
Containers: 7
Images: 656
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 670
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-54-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.707 GiB
Name: hostname
ID: GQL4:OR5L:J2YV:5TG5:X4LU:4ZJO:VNMH:WDY2:FPWP:G5X4:DKEZ:5MLV
WARNING: No swap limit support
$ uname -a
Linux hostname 3.13.0-54-generic #91-Ubuntu SMP Tue May 26 19:15:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue.net 
Ubuntu 14.04.2 LTS
```

### PR DESCRIPTION
**Pull request by calavera**
Closes #13937

/cc @crosbymichael, @cpuguy83

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
cherry-picked

**Comment by carlossg** [comment]
Was this supposed to be included in rc5? rc2 was working fine but rc5 is not

**Comment by jfrazelle** [comment]
It is supposed to be included

**Comment by jfrazelle** [comment]
ping @calavera

**Comment by calavera** [comment]
Yes, this is in RC5. @carlossg you might need to restart the daemon if you were using one of the previous RCs. The init script should have changed, but we don't restart the daemon if it's already running afaik.

**Comment by carlossg** [comment]
I have made a quick test, creating a gist
I have restarted the daemon and run some commands in two ubuntu servers running rc2 and rc5, you can see the difference, only in rc2 container and host dirs are synced
https://gist.github.com/carlossg/3bbdfaf007dc3d445307

Another thing I realized with rc2 is that the shared mount base folder needs to exist before the docker daemon is started, otherwise containers won't pick up the host dir changes, not sure if it is expected but I can live with that

**Comment by cpuguy83** [comment]
@carlossg Can you paste your docker upstart config (or whatever you use as your init)?

**Comment by carlossg** [comment]
Not in front of my computer, but Docker was installed with the test.docker.com shell script, upgraded from 1.6

**Comment by carlossg** [comment]
With some more testing, version 1.6.1 is broken, fixed in rc1 and rc2, and broken again in rc3 to rc5, matching what @cpuguy83 [mentioned in #13937](https://github.com/docker/docker/issues/13937#issuecomment-112140961)

Docker was installed with `curl -sSL https://test.docker.com/ | sh ` but then I switch versions with just apt-get
The PR changes are indeed in /etc/init/docker.conf, maybe this is not the right issue to comment on but the regression is still there.

**Comment by carlossg** [comment]
Ok, so maybe I jumped into the first issue I found, seems that the support for shared mounts was consciously removed in rc3 by #13854

**Pull request merged**
