### PR TITLE
Remove `stripTrailingCharacters` from tests

### PR DESCRIPTION
**Pull request by cpuguy83**
This was just an alias to `strings.TrimSpace`

### CODE REVIEW

**Comment by duglin** [comment]
funny - gotta wonder why it was done in the first place :-)

**Comment by duglin** [comment]
LGTM once janky is happy

**Comment by unclejack** [comment]
That particular function looked like this before:
```
 func stripTrailingCharacters(target string) string {
	target = strings.Trim(target, "\n")
	target = strings.Trim(target, " ")
	return target
}
```

It was modified by https://github.com/docker/docker/commit/f3ed42286e7df3a35ca41a4d19fab2a53a08b382

**Comment by duglin** [comment]
yea I noticed that too and not thrilled with that impl since it didn't work for a mixture of \n and spaces.

**Comment by cpuguy83** [comment]
Yeah, `TrimSpace` is matching against `'\t', '\n', '\v', '\f', '\r', ' ', 0x85, 0xA0`

**Comment by icecrime** [comment]
Sorry I kept it alive in my previous PR I guess...

LGTM

**Pull request merged**
