### PR TITLE
Remove writeJSONEnv, fixes #12597

### LINKED ISSUE #12597: remove unused writeJSONEnv from api/server/server.go
subj

### PR DESCRIPTION
**Pull request by runcom**
Fixes: #12597

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by LK4D4** [comment]
@runcom Can I ask you to left such issues to less qualified developers? :)
There is plenty of work for your skill level in repo, too.
LGTM

**Comment by runcom** [comment]
@LK4D4 my bad...and point me to some work pls!!!!!! :smile:

**Comment by LK4D4** [comment]
@runcom `graph/service.go` contains some engine jobs, which should be removed.

**Pull request merged**
