### PR TITLE
[1.11] vendor runc to fix issue#21808

### LINKED ISSUE #21808: [1.11.0-rc3] Mounting /dev breaks the host tty
**Steps to reproduce the issue:**
1. docker run -v /dev:/dev busybox
2. start new terminal (e.g. run `xterm`)

**Describe the results you received:**
Unable to start new terminal, strace shows there's no pty's available.
So far I can see that when mounting `/dev` as in step 1, `/dev/ptmx` is changed to a symlink
All the pts mounts are in place, everything else seems to be normal.

**Describe the results you expected:**
mounting `/dev` into a container should not break the host's pty

**Additional information you deem important (e.g. issue happens only occasionally):**
This does not happen on 1.10

### PR DESCRIPTION
**Pull request by tiborvass**
Fixes #21808

https://github.com/opencontainers/runc/compare/6c88a526cdd74aab90cc88018368c452c7294a06...e87436998478d222be209707503c27f6f91be0c5

### CODE REVIEW

**Comment by cpuguy83** [comment]
Haven't seen this one before... from userns:
```
19:11:18 FAIL: docker_cli_build_unix_test.go:22: DockerSuite.TestBuildResourceConstraintsAreUsed
19:11:18 
19:11:18 docker_cli_build_unix_test.go:34:
19:11:18     c.Fatal(err)
19:11:18 ... Error: "build --no-cache --rm=false --memory=64m --memory-swap=-1 --cpuset-cpus=0 --cpuset-mems=0 --cpu-shares=100 --cpu-quota=8000 --ulimit nofile=42 -t testbuildresourceconstraints ." failed with errors: exit status 1 : "Sending build context to Docker daemon 2.048 kB\r\r\nStep 1 : FROM hello-world:frozen\n ---> 690ed74de00f\nStep 2 : RUN /hello\n ---> Running in d97863715ade\nContainer command '/hello' could not be invoked.\n"
19:11:18 
```

**Comment by cpuguy83** [comment]
Yeah, that test seems to be broken by the PR.

**Comment by LK4D4** [comment]
https://github.com/docker/docker/blob/master/daemon/start.go#L147 it's from here, but I'm not sure what's going on

**Comment by LK4D4** [comment]
@hqhq we think that failures on CI because of your changes in runc. Maybe you can provide some info.
I can't reproduce locally.

**Comment by hqhq** [comment]
@LK4D4 ok, I'll take a look.

**Comment by hqhq** [comment]
https://github.com/opencontainers/runc/pull/744 will fix this.

**Comment by LK4D4** [comment]
@hqhq thanks!

**Comment by crosbymichael** [comment]
@tiborvass should this be open or closed?

**Comment by tiborvass** [comment]
@crosbymichael closed, but not by the PR from @hqhq

**Comment by tiborvass** [comment]
I reopened it, since it seems like we do want this for 1.11.0

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
