### PR TITLE
1.13.x: Re-vendor swarmkit to a2080913b9cf2cac309845a28902896d65d3f527

### PR DESCRIPTION
**Pull request by aluzzardi**
Includes:
- https://github.com/docker/swarmkit/pull/1749
- https://github.com/docker/swarmkit/pull/1753
- https://github.com/docker/swarmkit/pull/1760
- https://github.com/docker/swarmkit/pull/1762
- https://github.com/docker/swarmkit/pull/1764
- https://github.com/docker/swarmkit/pull/1765

/cc @aaronlehmann @LK4D4 @vieux 

Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Fixes #28039

**Comment by mlaventure** [comment]
```
22:05:42 These files are not properly gofmt'd:
22:05:42  - cli/command/formatter/container_test.go
22:05:42 
22:05:42 Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by aluzzardi** [comment]
@mlaventure This PR doesn't touch `cli/` so the branch must be broken.

**Comment by LK4D4** [comment]
Just CI didn't report linters problems for some time.

**Comment by aluzzardi** [comment]
https://github.com/docker/docker/pull/28538 this is the fix for master. We have to cherry pick it.

Unrelated to this PR though

**Comment by aaronlehmann** [comment]
Makes sense. See https://github.com/docker/docker/issues/28592.

**Comment by aluzzardi** [comment]
Cherry-picked #28538 for 1.13 in #28609

**Comment by aaronlehmann** [comment]
Also fixes #28496

**Comment by vieux** [comment]
LGTM ping @docker/core-engine-maintainers

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
