### PR TITLE
remove --init-path from client

### PR DESCRIPTION
**Pull request by runcom**
Fix https://github.com/docker/docker/issues/32355

@justincormack @thaJeztah PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh, I think we should keep the `--init`, just remove the `--init-path`. Allowing users to enable/disable `--init` per container is fine, but specifying a different _path_ per container didn't work, and didn't make much sense, as the `--init-path` was added to allow the init binary to be in a custom location on some distros

**Comment by justincormack** [comment]
Yes, the boolean should still be there to enable/disable on a per run basis....

**Comment by runcom** [comment]
updated to leave `--init`

**Review by vdemeester — APPROVED** [review]
LGTM 🐻

**Comment by thaJeztah** [comment]
ugh, needs a rebase @runcom 😢

**Comment by runcom** [comment]
rebased!

**Comment by vieux** [comment]
@thaJeztah shouldn't we deprecate instead of removing ?

**Comment by thaJeztah** [comment]
@vieux we could keep the flag; point is that the flag never was intended to be on `docker run` / `docker create`, and it even looks like it never worked;

```bash
docker run --init-path=/hello/world --init -dit --name foobar busybox

docker inspect foobar | grep world
<empty>
```

**Comment by runcom** [comment]
ping @thaJeztah where are we on this?

**Comment by runcom** [comment]
Anyone? :angel:

**Review by mlaventure — APPROVED** [review]
LGTM

Given that it doesn't look that it was saved on disk, I'm fine with removing it outright.

**Pull request merged**
