### PR TITLE
Filesystem Quotas

### PR DESCRIPTION
**Pull request by Mic92**
Because it was trivial to set this property for zfs, I have  implemented per container filesystem quotas.
For obvious reason these includes also code needed for the zfs driver, with the quota patch applied on top.

TODO:
- it would be great, if someone else could add support for other filesystems. Somebody has done this for [btrfs](https://github.com/docker/docker/compare/master...majst01:master). Devicemapper + ext4 should be also possible. I have extended the graphtest, to test this feature. If somebody get something working, they can send me a PR and I will merge it into this PR. 
- I don't like the current the way, I have extended the driver interface. In the best case it would  just be another optional interface. But this is not possible, because the NaiveDiffDriver hides any interfaces implemented in the underlying ProtoDriver.
- Integration tests are needed.
- Quotas are only applied to the rootfs not volumes. For volumes always vfs is chosen as filesystem. For an effective quota for both rootfs and volume would have been on the same filesystem, which is incompatible with current graph design.

### CODE REVIEW

**Comment by calavera** [comment]
The feature looks useful, but I'd rather seen #9411 merged into master before reviewing this PR in deep.

/cc @jfrazelle because she's assigned to #9411

**Comment by unclejack** [comment]
This PR is certainly something to discuss after #9411. #9411 is something I really want to get merged.

Quotas are yet another feature I'd like to have in Docker, but that needs to be discussed first. The reason why it needs to be discussed is so that we ensure that:
1) it ties into everything it needs to - `docker run`, `docker build` and into volumes
2) we discuss ways to implement these quotas for the various storage backends
3) we need to figure out a way to make this work transparently for the users so they don't a) have to set something up before using these quotas and b) this doesn't affect their system in any way

1) is pretty easy to address, but 2) is an entirely different story.

Let's get #9411 and discuss file system quotas after that. It's OK if we come up with a strategy for some of the graph drivers and implement file system quotas for the others later on.

I'm going to close this PR for now and we can continue the discussion after we get #9411 merged.

**Comment by blackfader** [comment]
@Mic92  hi , i am very Interest in “disk quota” ， this case can use “disk quota” in every container？ ths。

**Comment by Mic92** [comment]
@blackfader the thing I did is exposing:  zfs set quota=<VALUE> zpool/container-rootfs
via docker command line, so there is a per container quota

**Comment by blackfader** [comment]
@Mic92  it is cool! I don't understand docker not merge master， I want to use ， your fork docker project is not lastest ， I want merger this to docker master lastest.

**Pull request closed without merging**
