### PR TITLE
Fix Windows on master

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

The version_lib.go change has broken Windows on master. This is because NTFS is a case-insensitive file system, so you can't have VERSION (the file) and a version/ top-level directory. This renames the version/ package to versionlib/

@jfrazelle @vdemeester

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM pending janky

**Comment by jfrazelle** [comment]
fingers crossed

**Comment by thaJeztah** [comment]
Oh! I had the same on your "weather" app, Jess, LOL

**Comment by icecrime** [comment]
LGTM if green.

**Comment by stevvooe** [comment]
Remove the `VERSION` file? Is that still needed?

Also, Go doesn't really have libraries. It has packages. Maybe this goes in `pkg/version`?

**Comment by jfrazelle** [comment]
we need the file

**Comment by jhowardmsft** [comment]
I've got to disappear for a couple of hours. Happy to change things, but it might be quicker if someone else does the changes if this PR needs updating. Short story is still that master is broken on Windows currently otherwise.

**Comment by jfrazelle** [comment]
no worries im fine w yours

**Comment by thaJeztah** [comment]
```
hack/make.sh: line 69: ./VERSION: No such file or directory
Build step 'Execute shell' marked build as failure
```

**Comment by jhowardmsft** [comment]
Wth? That has to be something else. Will be back online in 90mins or so

**Comment by cpuguy83** [comment]
Yeah, this is also breaking building from OSX

**Comment by cpuguy83** [comment]
Closing since the code this touches was reverted.

**Comment by jhowardmsft** [comment]
https://github.com/docker/docker/pull/17423

**Comment by mountkin** [comment]
I was hit by the same problem in one of my project.
Everything worked well until a colleague tried to `git clone` the project on OSX.
Finally we changed the `VERSION` file to `VERSION.txt` to make the case-insensitive filesystems happy :sweat_smile:

**Pull request closed without merging**
