### PR TITLE
Improve scalability of the Linux load balancing

### LINKED ISSUE #30820: Swarm Mode at Scale
**Description**

I'm in the process of migrating an LXC setup to a Docker Swarm environment. The size of this setup is 50 nodes with about 10k services running. The cluster with 50 nodes (32GB RAM) seems to be working as expected. When I now try to start services I get stuck at around 500 - 700 services. After that point `docker ls` shows entries like: `rxlga525wqjd <service-name> replicated  0/1 <container>`

and `docker service ps <service-name>` shows:

```
ixoggohaa7kc  <service-name>      <container>  prd-pro-16  Running        Running 1 second ago                                     
p0gziroccv42   \_ <service-name>  <container>  prd-pro-24  Shutdown       Failed 12 seconds ago  "starting container failed: co…"  
j0fvbve416gz   \_ <service-name>  <container>  prd-pro-35  Shutdown       Failed 2 minutes ago   "starting container failed: co…"  
873vsi6c80vx   \_ <service-name>  <container>  prd-pro-24  Shutdown       Failed 4 minutes ago   "starting container failed: co…"  
```

Every container is connected to 2 networks, `proxy` (10.1.0.0/16) and `db` (10.2.0.0/16). Running containers are reachable.

**Steps to reproduce the issue:**
1. start Docker Swarm Mode with 50 nodes
2. start > 500 services and wait till they fail to start up

**Describe the results you received:**

After about 500 containers creating a new service doesn't work anymore.

**Describe the results you expected:**

Service creation works within 1 or 2 seconds.

**Additional information you deem important (e.g. issue happens only occasionally):**

When I log into the node where the container is started and run `docker ps` the command hangs until the container fails. Creating a new container directly on a node that has failed before works as expected and container start up takes less than a second.

All machines appear to be idle and there are no tremendous peaks in load/memory from what I can see. The average load per machine is 10 - 15 containers with around 100 - 150 MB memory usage each.

I am aware that debugging this is hard and I'm very happy to do screen sharing or provide any logs that might be needed to get to the bottom of this behaviour. I'm grateful for every input!

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ssci1al4vgi7nzirptugjrpsl
 Is Manager: true
 ClusterID: qfi82y6p6rpnnfxkarxxfdca4
 Managers: 3
 Nodes: 50
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.133.6.234
 Manager Addresses:
  10.133.6.234:2377
  10.133.8.162:2377
  10.133.8.89:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.42 GiB
Name: prd-pro-01
ID: 37WG:BKQR:YXQF:LTMK:P3IQ:CDQ5:ZEM5:PI6L:32DR:3KET:QH4Z:GB5N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ghostengineering
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
DigitalOcean

### LINKED ISSUE #37349: Using `--dns-option=ndots:0` w/ user-defined networking results in duplicate ndots:0 options
**Description**

When using user-defined networking and specifying `--dns-option=ndots:0` in the `docker run` incantation (this is the default value Docker uses otherwise), Docker sets _two_ `ndots:0` options in `/etc/resolv.conf`.

Setting `--dns-option=ndots:1` results in the expected behavior, so I suspect this is a regression introduced in https://github.com/docker/libnetwork/pull/2065 (vendored in https://github.com/moby/moby/pull/36137) to fix the behavior with a user-specified `ndots` option.

**Steps to reproduce the issue:**
1. Create a Docker network with `docker network create...`
2. Run a container in that network, specifying `ndots:0` with something like `docker run --network <network-name> --dns-option=ndots:0...`
3. Check contents of `/etc/resolv.conf` within the container.

In our case it looks like this:

```
$ docker network create --subnet 192.168.0.0/24 docker0

$ docker run \
    -e "HOSTNAME=$HOSTNAME" \
    -v /dev/mqueue:/dev/mqueue \
    -v "${PERSISTENCE_DIR}:/opt/test:Z" \
    -v /etc/environment:/etc/environment:ro \
    -v /dev/log:/dev/log \
    ${VOLUME_COMMAND} \
    --name test-container \
    --network docker0 \
    --dns=192.168.0.1 \
    --dns-search ops.test.local \
    --dns-option=ndots:0 \
    --hostname "$HOSTNAME" \
    --ip 192.168.0.2 \
    --storage-opt size=75G \
    --ulimit nofile=950000:950000 \
    --ulimit nproc=32768:32768 \
    --add-host "$(hostname -f):$(facter -p ipaddress_eth0)" \
    --add-host "$(hostname -s):$(facter -p ipaddress_eth0)" \
    --add-host "$(hostname -f):192.168.0.2" \
    --add-host "$(hostname -s):192.168.0.2" \
    --tty \
    --log-driver syslog \
    --log-opt syslog-address=udp://127.0.0.1:514 \
    --log-opt syslog-format=rfc5424 \
    --log-opt tag=test-container \
    "test-centos-image"
```

**Describe the results you received:**

`/etc/resolv.conf` within the container has two `ndots:0` options:

```
[test@testhost /]$ cat /etc/resolv.conf
search ops.test.local
nameserver 127.0.0.11
options ndots:0 ndots:0
```

**Describe the results you expected:**

Should only list `ndots:0` once:

```
[test@testhost /]$ cat /etc/resolv.conf
search ops.test.local
nameserver 127.0.0.11
options ndots:0
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Setting the option to anything other than `0`, like ``, results in the correct behavior:

```
[test@testhost /]$ cat /etc/resolv.conf
search ops.test.local
nameserver 127.0.0.11
options ndots:1
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-67390432-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 80.53GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /opt/docker/100000.100000/devicemapper/devicemapper/data
 Metadata loop file: /opt/docker/100000.100000/devicemapper/devicemapper/metadata
 Data Space Used: 1.788GB
 Data Space Total: 107.4GB
 Data Space Available: 48.36GB
 Metadata Space Used: 3.633MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.144GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
 userns
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.517GiB
Name: testhost.ops.test.local
ID: NKFA:NRPY:QIV3:APOD:JI3A:H6BO:343T:4LCF:4ZZY:GNKW:FWV4:YJYI
Docker Root Dir: /opt/docker/100000.100000
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://<omitted>.ops.test.local:8888/
HTTPS Proxy: http://<omitted>.ops.test.local:8888/
No Proxy: localhost,127.0.0.1,test.local,169.254.169.254
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running Docker 18.0.3.1 on CentOS 7 on AWS.

### PR DESCRIPTION
**Pull request by ctelfer**
full diff: https://github.com/docker/libnetwork/compare/430c00a6a6b3dfdd774f21e1abd4ad6b0216c629...3ac297bc7fd0afec9051bbb47024c9bc1d75bf5b

Changes included;
 
- https://github.com/docker/libnetwork/pull/2138 Improve load balancing scalability in swarm mode
- https://github.com/docker/libnetwork/pull/2199 Use new plugin interfaces provided by plugin pkg
- https://github.com/docker/libnetwork/pull/2200 Adjust corner case for reconnect logic
- https://github.com/docker/libnetwork/pull/2212 Fix duplicate ndots:0, and improve validation
  - fixes https://github.com/moby/moby/issues/37349
- https://github.com/docker/libnetwork/pull/2154 Add knobs on LB sandbox
- https://github.com/docker/libnetwork/pull/2215 Fix error handling about bridgeSetup
- https://github.com/docker/libnetwork/pull/2221 Use fmt precision to limit string length
- https://github.com/docker/libnetwork/pull/2216 NetworkDB qlen optimization

**- What I did**

Improve the scalability of the Linux load balancing in overlay networks by allocating a load balancing endpoint per overlay network in a manner similar to ingress and programming it with all load-balancing rules for a given network.

**- How I did it**

This change allocates a load balancer endpoint IP address for all overlay networks rather than just "ingress" and windows overlay networks.  Swarmkit is already performing this IP address allocation, but moby was not making use of these IP addresses for Linux overlay networks (except ingress).  The updated version of libnetwork in this PR creates a load balancing sandbox and endpoint for each node in the cluster for each overlay network.  It programs all load balancing state for a given network in that sandbox.  This scheme is similar to how the Windows overlay networking driver works as it also allocates a per-node per-network IP address.

In the prior scheme, libnetwork would program each container's network namespace with every piece of load balancing state for every other container that shared *any* network with the first container.  This meant that the amount of kernel state on a given node scaled with the square of the number of services in the cluster and with the square of the number of containers per service.  With the new scheme, kernel state at each node scales linearly with the number of services and the number of containers per service.  This also reduces the number of system calls required to add or remove tasks and containers.  Previously the number of system calls required grew linearly with the number of other tasks that shared a network with the container.  Now the number of system calls grows linearly only with the number of networks that the task/container is attached to.  This results in a significant performance improvement when adding and removing services to a cluster that already heavily loaded.

The primary disadvantage to this scheme is that it requires the allocation of an additional IP address per node per subnet for every node in the cluster that has a task on the given subnet.  However, as mentioned, swarmkit is already allocating these IP addresses for every node and they are going unused.  Future swarmkit modifications should be examined to only allocate said IP addresses when nodes actually require them.

This should address and hopefully resolve https://github.com/moby/moby/issues/30820.

**- How to verify it**

Do the following before and after the change:
* Start up a cluster of docker nodes (say 3 nodes).
* Spin up 20-50 services each with 10-20 containers each attached to 2-5 networks.
* Measure the time it takes for the creation to converge.
* Delete the services.
* Measure the time it takes for all networks to be removed.

Will look into adding test data to this PR.

**- Description for the changelog**

Improve the scalability of Linux load balancing.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@ctelfer I see some failures; not sure if they're flaky, or related

**Comment by ctelfer** [comment]
I did some investigating onthe tests that are failing.

The `powerPC` tests failed due to failure to fetch stuff from the Internet to set up the test.  Can't do anything about that.

Under `janky` there were 7 tests that failed
 * TestPruneNetwork
 * TearDownTest
 * TestSwarmNetworkIPAMOptions
 * TestDockerNetworkCustomIPAM
 * TestAPIServiceUpdatePort
 * TestSwarmPublishDuplicatePorts
 * TestSwarmServiceNetworkUpdate

Of these, one (TestDockerNetworkIPAMOptions) that went and dumped goroutine traces.  I reran a full integration-cli test run on `master`  (`dca4cab`, i.e. without my changes) and found that at least 4 of the 7 (maybe more, lost some of the logs) including the IPAM one failed in the exact same way.

I also ran the failing tests individually and most of them passed individually in the `scalable-lb` branch.  One that didn't was TestPruneNetwork.  That one definitely failed on `master` for me as well in a full run.  `TestSwarmServiceNetworkUpdate` is also giving me inconsistent results -- sometimes passing sometimes failing when run individually.  It may be that some of the others are flaky and I just haven't run them enough times to cause them to fail.

In the `z` test suite two tests failed and they were two that failed and they were both tests that failed in `janky` and which failed for me in master:  `TestPruneNetwork` and `TearDownTest`.

Finally, we have the `experimental` set where 4 tests failed.  Of these `TestPruneNetwork`, `TearDownTest` and `TestDockerNetworkCustomIPAM` are all familiar (see above) and all failed on `master` for me.  The one new one is `TestSwarmClusterRotateUnlockKey`.  Not sure what to make of that one, but don't think it is likely to be related to my changes.

I will keep investigating.

**Comment by thaJeztah** [comment]
@ctelfer also look at https://github.com/moby/moby/issues/37306 to filter tests that are known to be flaky (but need looking into)

**Comment by ctelfer** [comment]
Ok, so good, bad, ugly time.
 * The good:  I looked more closely at the `TestSwarmServiceNetworkUpdate` test found an error.  
 * The bad: it's actually an existing bug that MOSTLY won't show up in older versions ... but could
 * The ugly:  patching it means another bump in libnetwork which also means bringing in other changes -- fortunately mostly minor

Details -- it turns out that there is (was) a lot of libnetwork debug code of the form `logrus.LEVELf("...%s...", ..., ENTITY.ID()[0:7]... )`.  LEVEL could be `Debug`, or `Error`, etc... and ENTITY could be a sandbox or an endpoint or a network.  The goal of the slice was obviously to limit the length of the output.  BUT .. the problem was that it was possible to have IDs that were less than 7 characters long.  The one I was hitting were sandbox IDs which were not UUIDs, but instead names (for reasons I don't completely understand).    This meant that under the right circumstances the slice would specify a length longer than the string and the goroutine would panic.

In one particular instance, if one specified an overlay network name that was 2 characters or less in the previous libnetwork code and that network required a network sandbox (i.e. on a Windows node), then the sandbox name would be 6 or less characters and panic.  The scalable network patch made this worse by making use of more load-balancer sandboxes with user-specified names (as opposed to `ingress`) in the unix world and also by shortening the sandbox prefix by 1 character meaning that 3 character network names could now trigger the panic as well.

I patched libnetwork to use `logrus.LEVELf("... %.7s ....", ... ENTITY.ID() ...)`  instead which specifies a precision in the string formatting giving a maximum (instead of fixed) width, which is safe.  However, bringing in this libnetwork version also means accepting the following mods as well: 
     * 6c7c6017 - Fix error handling about bridgeSetup
     * 5ed38221 - Optimize networkDB queue
     * cfa9afdb - ndots: produce error on negative numbers
     * 5586e226 - improve error message for invalid ndots number
     * 449672e5 - Allows to set generic knobs on the Sandbox
     * 6b4c4af7 - do not ignore user-provided "ndots:0" option
     * 843a0e42 - Adjust corner case for reconnect logic

Fortunately, most of these are non-controversial minor bug fixes.   The only ones that alter behavior significantly is the 5ed38221 patch which attempts to prevent gossip queue length explosion.  Doing so can slow gossip convergence, but should only really do so when the gossip network is a bit overloaded in the first place (and so it hopefully speeds some of it up in that case).

I did rerun the all the SwarmSuite tests w/ the aforementioned libnetwork bump and all of them passed.  Hopefully, the newest push gets a clean bill of health from moby CI then.

**Review by thaJeztah — APPROVED** [review]
LGTM

z is a flaky test

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
for reference; flaky failure on s390x is tracked through https://github.com/moby/moby/issues/37408


```
20:47:05 FAIL: docker_api_swarm_service_test.go:311: DockerSwarmSuite.TestAPISwarmServicesFailedUpdate
20:47:05 
20:47:05 [d8493890b28f4] waiting for daemon to start
20:47:05 [d8493890b28f4] daemon started
20:47:05 
20:47:05 [da76d9454d5b9] waiting for daemon to start
20:47:05 [da76d9454d5b9] daemon started
20:47:05 
20:47:05 [d475ab3ed458c] waiting for daemon to start
20:47:05 [d475ab3ed458c] daemon started
20:47:05 
20:47:05 docker_api_swarm_service_test.go:347:
20:47:05     waitAndAssert(c, defaultReconciliationTimeout, daemons[0].CheckRunningTaskImages, checker.DeepEquals,
20:47:05         map[string]int{image1: instances})
20:47:05 docker_utils_test.go:435:
20:47:05     c.Assert(v, checker, args...)
20:47:05 ... obtained map[string]int = map[string]int{"busybox:latest":4}
20:47:05 ... expected map[string]int = map[string]int{"busybox:latest":5}
20:47:05 
20:47:05 [d8493890b28f4] exiting daemon
20:47:05 [da76d9454d5b9] exiting daemon
20:47:05 [d475ab3ed458c] exiting daemon
```

**Comment by rjshrjndrn** [comment]
So, is it safe to have a n/w with /16 CIDR in overlay network?

**Comment by ctelfer** [comment]
Yes, this should be safe.   There was never anything inherently wrong with using a /16 network in the first place.  There were admonitions in the past about not using larger subnet sizes as a crude way of keeping people from trying to create networks with large numbers of services (or large numbers of containers or nodes).  The previous load balancer would take minutes to hours to complete a `docker service create...` when the network had more than some threshold (10s to 100s ish) of containers and/or services especially if all on the same overlay(s).  I'm not sure that saying "keep subnets smaller than X" was the right way to prevent people from tripping over that problem, but that's what it was trying to do.  In any case, the new scheme will definitely prevent the aforementioned issues.

**Comment by rnataraja** [comment]
Why was this change made in engine/daemon/network.go ?
From 
agent && driver == “overlay” && (create.Ingress || runtime.GOOS == “windows”) 
to 
agent && driver == "overlay"

Does this break the case of Overlay network (non -ingress) which is attachable being attached to a non swarm conatiner?

**Comment by rnataraja** [comment]
@ctelfer false alarm. potentially, this is due to my IPAM plugin failing to allocate IP for the LB Node.

**Comment by yuvalo** [comment]
Adding the new load balancer introduces a new behavior:
When a container communicates with another service, it will go through the load balancer and hide the source IP address. 
This is a potential problem in cases where the source IP matters for an application.

**Comment by q0rban** [comment]
> So, is it safe to have a n/w with /16 CIDR subnet in overlay network?

> Yes, this should be safe. There was never anything inherently wrong with using a /16 network in the first place...

It's been 6 years since this is merged in, and yet the documentation still states to avoid using anything other than a `/24` for swarm networks. Should that documentation be updated?

**Comment by thaJeztah** [comment]
- @q0rban tracked in https://github.com/docker/docs/issues/11412 (contributions welcome in that repository)

**Pull request merged**
