### PR TITLE
Modify func name from TestChtimes to TestChtimesLinux

### PR DESCRIPTION
**Pull request by lixiaobing1**
Modify func name from TestChtimes to TestChtimesLinux

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
oh, can you squash your commits?

**Comment by lixiaobing10051267** [comment]
I commit with --no-edit arg.

**Comment by thaJeztah** [comment]
perhaps you missed the `--amend` when doing so; you can squash your commits, by doing an interactive rebase; some explanation can be found in our contributors guide; https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently

**Comment by lixiaobing10051267** [comment]
ok, thanks very much:)

**Comment by lixiaobing10051267** [comment]
@thaJeztah commits have been squashed:)

**Comment by thaJeztah** [comment]
re-LGTM

**Comment by vdemeester** [comment]
LGTM 👼

**Pull request merged**
