### PR TITLE
bump x/sys to fix riscv64 epoll

### LINKED ISSUE #39461: [Risc-V] Interactive terminal and tail logs not working
Recently Risc-V architecture have been added to Docker (moby/moby) as PR #39327.

We are using Docker with Containerd and [crun](https://github.com/giuseppe/crun) runtime since runc depends on CGO that's not available on this arch yet.

I found-out that running a container with `-it` to get an interactive terminal doesn't provide the terminal and freezes the session. If the container is stopped, control is returned and all inputs given to the terminal is printed at once.

Another problem that might be similar is that following the logs with `logs -f` also doesn't stream the data. It only prints what's already logged and freezes. If one cancel the log tail and run again, it prints all logged messages.

To reproduce, I have packed a [Risc-V Qemu VM](https://drive.google.com/open?id=1O3dQouOqygnBtP5cZZ3uOghQO7hlrFhD) and the Docker, Crun and [Containerd binaries tarball](https://drive.google.com/open?id=1Op8l6yq6H_C_zpZUpvO-zHxwbtcrAGcQ). There is a install script in the tarball and more details in the [tracker repo](https://github.com/carlosedp/riscv-bringup).

Versions:

```
carlosedp in ~ at fedora-unleashed
➜ crun --version
crun 0.6

carlosedp in ~ at fedora-unleashed
➜ containerd --version
containerd github.com/containerd/containerd 1.2.0+unknown

➜ docker version
Client:
 Version:           unknown-version
 API version:       1.40
 Go version:        devel +2bdba6c078 Fri May 24 18:40:32 2019 +0000
 Git commit:        unknown-commit
 Built:             unknown-buildtime
 OS/Arch:           linux/riscv64
 Experimental:      true

Server:
 Engine:
  Version:          library-import
  API version:      1.41 (minimum version 1.12)
  Go version:       devel +f980a63fcb Fri May 24 20:26:57 2019 +1000
  Git commit:       library-import
  Built:            library-import
  OS/Arch:          linux/riscv64
  Experimental:     false
 containerd:
  Version:          1.2.0+unknown
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        3c53686
```
Cc. @tonistiigi

### PR DESCRIPTION
**Pull request by carlosedp**
Signed-off-by: Carlos de Paula <me@carlosedp.com>

Bump x/sys to golang/sys#40.

Fixes https://github.com/moby/moby/issues/39461.

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks! I noticed there's another PR that updates this dependency, which may also include these changes? https://github.com/moby/moby/pull/39707

**Comment by carlosedp** [comment]
@thaJeztah The changes required by this PR were still not present in `x/sys` from that PR. It's one commit behind.

**Comment by thaJeztah** [comment]
Ah, thx for checking!

**Comment by carlosedp** [comment]
Apparently Jenkins CI got a hiccup... can't find the real error on it's log.

**Review by justincormack — APPROVED** [review]

**Comment by carlosedp** [comment]
@thaJeztah can you retrigger the CI to check this? Thanks!

**Comment by AkihiroSuda** [comment]
Please sign the commit with your both first name and surname, then LGTM

**Comment by thaJeztah** [comment]
@AkihiroSuda could you also review https://github.com/moby/moby/pull/39707 ?

**Comment by carlosedp** [comment]
Updated @thaJeztah @AkihiroSuda

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
