### PR TITLE
Installation on Joyent

### PR DESCRIPTION
**Pull request by misterbisson**
Installation documentation for Joyent's version 1 Docker container service.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
2 things - 

to date, we've asked that platform installation docs get a user to a fully working Docker installation without referring to external docs - so those users are protected from moving links, and are able to get up to step one without clicking about.

And this PR is an example of why - your blog link to getting started is broken.

**Comment by misterbisson** [comment]
[This blog post](https://www.joyent.com/blog/first-steps-with-joyents-container-service)?

I'm getting the following:

```
$ curl -I https://www.joyent.com/blog/first-steps-with-joyents-container-service
HTTP/1.1 200 OK
Server: Apache
Vary: Accept-Encoding
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html
Date: Wed, 04 Mar 2015 00:45:04 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Transfer-Encoding: chunked
Connection: Keep-Alive
Set-Cookie: PHPSESSID=if7brjk1eigkl43fve7hdvqpi0; path=/
X-Cache-Info: not cacheable; response specified "Cache-Control: no-store"
```

**Comment by misterbisson** [comment]
It appears the earlier comment has since been edited and doesn't reference a broken link to a blog post.

**Comment by misterbisson** [comment]
> we've asked that platform installation docs get a user to a fully working Docker installation without referring to external docs

Understood. I've added more separation between the getting started section (which I believe can be completed without referring to external docs) and the next steps, which emphatically do link elsewhere.

I believe this is in line with some other accepted additions to the documentation, but please correct me if I'm misreading any of this:

1. https://github.com/docker/docker/blob/master/docs/sources/installation/softlayer.md
1. https://github.com/docker/docker/blob/master/docs/sources/installation/google.md

**Comment by SvenDowideit** [comment]
@misterbisson it looks like something's gone a bit awry with your PR.

can you please `git rebase -i upstream/master` your commits, squash them, and sign them?

**Comment by misterbisson** [comment]
@SvenDowideit thanks for the reminder. Fixed.

**Comment by jamtur01** [comment]
Ping @moxiegirl @SvenDowideit @fredlf - might be changing in light of new proposed installation methodology?

**Comment by moxiegirl** [comment]
@jamtur01 Yes, it will likely change but not until April. Until then... @misterbisson Casey I am not sure of the order from your original it looked like you had them configuring the CLI after the first used it.  Also, you had what is called a stacked head... try the markdown here:

https://gist.github.com/moxiegirl/30a3805c7dc1cbab87d3

**Comment by moxiegirl** [comment]
With changes LGTM

**Comment by jamtur01** [comment]
Then LGTM to also - thanks for clarifying @moxiegirl !

**Comment by SvenDowideit** [comment]
you need to add the new document to the `docs/mkdocs.yml` file to get the documentation build system to pick it up (run `make docs` to test)

The last line of the docs should really be broken up - we're still trying to break up lines to 80-chars so that the GithHub diffs work better

**Comment by misterbisson** [comment]
Thanks all and apologies for the delay. I was really knocked down by a cold. I'm resolving the conflicts and updating the PR now.

**Comment by misterbisson** [comment]
@SvenDowideit @moxiegirl @jamtur01 I think this is all cleaned up per suggestions.

**Comment by SvenDowideit** [comment]
LGTM - is there any chance of also mentioning a link to how to use Docker on SmartOS ?

**Comment by misterbisson** [comment]
> any chance of also mentioning a link to how to use Docker on SmartOS

@SvenDowideit I think that's best left to an entirely separate pull request.

I've resolved the merge conflict.

**Pull request merged**
