### PR TITLE
Alphabetize makefile targets

### PR DESCRIPTION
**Pull request by tophj-ibm**
Sorts the makefile targets alphabetically

I didn't see a reason why they weren't and there didn't seem to be any cohesion between them, so sort them alphabetically (except default) to make it easier to find things.

Signed-off-by: Christopher Jones tophj@linux.vnet.ibm.com

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by tonistiigi** [comment]
@mavenugo Looks like #20398 in experimental

**Comment by mavenugo** [comment]
@tonistiigi Sorry. I dont understand the context of your comment in this PR ?

**Comment by tonistiigi** [comment]
@mavenugo Just fyi that the experimental CI for this PR failed with the same error that is in #20398 https://jenkins.dockerproject.org/job/Docker-PRs-experimental/22905/console

**Pull request merged**
