### PR TITLE
Refactor code in cmd/dockerd/daemon.go

### PR DESCRIPTION
**Pull request by medakk**
Signed-off-by: Karthik Karanth <karanth.karthik@gmail.com>

**- What I did**
Broke down the large `start()` function in `cmd/dockerd/daemon.go` into functions.

**- Description for the changelog**

Refactor code for better readability in `cmd`

**- A picture of a cute animal (not mandatory but encouraged)**
mbegu

### CODE REVIEW

**Review by mlaventure — APPROVED** [review]
LGTM

Failed janky doesn't seem related, I'll restart the job

**Review by dnephin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by thaJeztah** [comment]
experimental (https://jenkins.dockerproject.org/job/Docker-PRs-experimental/40241/console) has some failures in flaky tests; (tracked through https://github.com/moby/moby/issues/36501)

```
15:40:29 ----------------------------------------------------------------------
15:40:29 FAIL: docker_api_swarm_service_test.go:33: DockerSwarmSuite.TestAPIServiceUpdatePort
15:40:29 
15:40:29 [dd7d68a3e55eb] waiting for daemon to start
15:40:29 [dd7d68a3e55eb] daemon started
15:40:29 
15:40:29 docker_api_swarm_service_test.go:39:
15:40:29     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
15:40:29 docker_utils_test.go:452:
15:40:29     c.Assert(v, checker, args...)
15:40:29 ... obtained int = 0
15:40:29 ... expected int = 1
15:40:29 
15:40:29 [dd7d68a3e55eb] exiting daemon
15:40:41 

15:40:29 ----------------------------------------------------------------------
15:40:29 FAIL: docker_api_swarm_service_test.go:33: DockerSwarmSuite.TestAPIServiceUpdatePort
15:40:29 
15:40:29 [dd7d68a3e55eb] waiting for daemon to start
15:40:29 [dd7d68a3e55eb] daemon started
15:40:29 
15:40:29 docker_api_swarm_service_test.go:39:
15:40:29     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
15:40:29 docker_utils_test.go:452:
15:40:29     c.Assert(v, checker, args...)
15:40:29 ... obtained int = 0
15:40:29 ... expected int = 1
15:40:29 
15:40:29 [dd7d68a3e55eb] exiting daemon
15:40:41 
```


This one was mentioned as being flaky in https://github.com/moby/moby/pull/36425#issuecomment-368842724

```
15:51:31 FAIL: docker_api_swarm_service_test.go:615: DockerSwarmSuite.TestAPISwarmServicesPlugin
15:51:31 
15:51:31 [d098922e57e4a] waiting for daemon to start
15:51:31 [d098922e57e4a] daemon started
15:51:31 
15:51:31 [dff3892afb377] waiting for daemon to start
15:51:31 [dff3892afb377] daemon started
15:51:31 
15:51:31 [d3afb82b4af83] waiting for daemon to start
15:51:31 [d3afb82b4af83] daemon started
15:51:31 
15:51:31 docker_api_swarm_service_test.go:684:
15:51:31     waitAndAssert(c, defaultReconciliationTimeout, d1.CheckPluginRunning(repo), checker.False)
15:51:31 docker_utils_test.go:452:
15:51:31     c.Assert(v, checker, args...)
15:51:31 ... obtained bool = true
15:51:31 ... &{Config:{Args:{Description: Name: Settable:[] Value:[]} Description: DockerVersion:dev Documentation: Entrypoint:[/basic] Env:[] Interface:{Socket:basic.sock Types:[.docker.dummy/1.0/]} IpcHost:false Linux:{AllowAllDevices:false Capabilities:[] Devices:[]} Mounts:[] Network:{Type:} PidHost:false PropagatedMount: User:{GID:0 UID:0} WorkDir: Rootfs:0xc4209db7d0} Enabled:true ID:1aa261deb065c9244f702bfa648b82f2240e0a39b9b29b3d6c930d4c1b84b013 Name:127.0.0.1:5000/swarm/test:v1 PluginReference:127.0.0.1:5000/swarm/test:v1 Settings:{Args:[] Devices:[] Env:[] Mounts:[]}}
15:51:31 
15:51:31 [d098922e57e4a] exiting daemon
15:51:31 [dff3892afb377] exiting daemon
15:51:31 [d3afb82b4af83] exiting daemon
15:51:55 
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
