### PR TITLE
Added Leslie Lamport to the list of scientists

### PR DESCRIPTION
**Pull request by alimate**
**\- What I did**
I just added the name of Leslie Lamport to the list of notable scientists and hackers.

**\- How I did it**
Pressed an Enter and added the name and then a comma!

**\- How to verify it**
Run a container without --name option and if you were lucky, you would see something like naughty_lamport

### CODE REVIEW

**Comment by tiborvass** [comment]
@alimate Thanks! Please add a woman as well: https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go#L79

Also, you need to gofmt the code that was changed, let us know if you need help

**Comment by thaJeztah** [comment]
ping @alimate can you update your PR?

**Comment by alimate** [comment]
I've added one woman. For gofmt, should i just run the `gmfmt <path_to_file>`?

**Comment by cpuguy83** [comment]
@alimate `gofmt -s -w <path to file>`

**Comment by thaJeztah** [comment]
LGTM, but may need a squash

**Comment by jhowardmsft** [comment]
Needs a rebase too

**Comment by alimate** [comment]
Why rebase?

**Comment by thaJeztah** [comment]
@alimate because there are merge conflicts. Also looks like there's now a non-related commit in this PR (https://github.com/docker/docker/pull/21807/commits/13b4ee21b52f59defe47dbb510087b57c3530f3d)

**Comment by thaJeztah** [comment]
ping @alimate can you rebase your PR? in its current state, we cannot merge it

**Comment by thaJeztah** [comment]
looks like there's still an issue @alimate, because there's still a foreign commit in this PR. Can you try rebasing to get rid of that commit?

**Comment by alimate** [comment]
@thaJeztah  Is it OK if i create a brand new PR with a brand new branch with only my commit? Apparently i did use someone else's branch and there are a few other foreign commits

**Comment by thaJeztah** [comment]
Sure, let me close this one

**Pull request closed without merging**
