### PR TITLE
Bump md2man

### LINKED ISSUE #10667: Markdown syntax problems in manpages
There are errors in the manpages because parameters in angle brackets aren't included in `md2man` output. For [example][], 
```
**ADD ["<src>"... "<dest>"]** This form is required for paths containing whitespace.
```
renders as
```
ADD [""... ""] This form is required for paths containing whitespace.
```
Note the missing `<src>` and `<dest>`.
This can also be seen in GitHub's rendering of the text:

**ADD ["<src>"... "<dest>"]** This form is required for paths containing whitespace.

[example]: https://github.com/docker/docker/blame/master/docs/man/Dockerfile.5.md#L137

--------------
**PROBLEM**: man docs are often imporoperly formatted, using quotes or bolds when code blocks/segments are required

**PROPOSED SOLUTION**: man docs should be updated to use appropriate backticks for either inline or blocked code.
The `dockerfile.5.md` has already been gone through, but wouldn't hurt another set of eyes.

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #10667

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
that was fast btw

**Comment by tiborvass** [comment]
LGTM

**Comment by tianon** [comment]
Like I mentioned in #10667, I'm not at all a fan of this fix -- it feels like we're fixing the wrong thing.

I won't block the merge though if I'm in the minority -- the change itself here LGTM.

**Comment by jfrazelle** [comment]
hmmm could be, what do you think we do instead, change all the < to &lt;

**Comment by tianon** [comment]
No, I think we should mark the affected code blocks in our Markdown as code blocks (either with indentation, fencing, or backticks).

**Comment by jfrazelle** [comment]
oh yeah i agree

**Comment by jfrazelle** [comment]
I thought they were sorry, for misunderstanding, we definitely should

**Comment by cpuguy83** [comment]
Yes, this.  There's a lot of mis-use of MD, I think.
Though to be fair, before this patch, html tags were just completely ignored :)

**Comment by tianon** [comment]
I'd love to see HTML tags become a hard failure here, to help catch these bugs in the future! :smiling_imp:

**Comment by cpuguy83** [comment]
That's doable.

**Comment by cpuguy83** [comment]
Closing for now (not like we're fixing for 1.5 anyhow :) )

**Pull request closed without merging**
