### PR TITLE
[vim] Be case insensitive for D in dockerfile

### PR DESCRIPTION
**Pull request by kunaltyagi**
**- What I did and How I did it**
Set the regex to accept d and D

**- Description for the changelog**
Allow vim to be case insensitive for D in dockerfile

**- A picture of a cute animal (not mandatory but encouraged)**
:dog2:

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Changes look good to me, but can you sign-off and amend your commit? See the instructions above, but let me know if you need a hand

**Comment by kunaltyagi** [comment]
Added signoff line

**Review by thaJeztah — APPROVED** [review]
Awesome, LGTM, thanks!

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
