### PR TITLE
Cleanup hack/make scripts - part 1

### PR DESCRIPTION
**Pull request by dnephin**
First remove old aliases for hack/make binary scripts. Rename the remaining scripts with `-engine` suffix to make space for building other binaries and match changes coming in #34226

Second commit: start moving some code out of `hack/make.sh` into separate library scripts so they can be sourced where they are needed. This will eventually allow us to make the dependencies between these scripts easier to work with and remove the need for a "driver" script.

### CODE REVIEW

**Comment by coolljt0725** [comment]
@dnephin  needs rebase
@tianon PTAL

**Comment by coolljt0725** [comment]
ping @dnephin   are your still working on this?

**Comment by dnephin** [comment]
I'm waiting for it to be reviewed

**Comment by coolljt0725** [comment]
@dnephin  looks like it needs a rebase :)
@tianon  can you PTAL?

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by dnephin** [comment]
rebased

**Comment by thaJeztah** [comment]
CI is failing;

```
22:47:44 
22:47:44 ---> Making bundle: binary-engine (in bundles/binary-engine)
22:47:44 /go/src/github.com/docker/docker/hack/make/.go-autogen: line 7: PLATFORM: unbound variable
```

**Comment by thaJeztah** [comment]
also ping @tianon - I'd like to have a review from him on this

**Comment by tianon** [comment]
I do like the idea of finally moving away from the `make.sh` centralized controller script (which has remained essentially unchanged in usage since it was refactored back in https://github.com/docker/docker/commit/3d39336a46a0d7f411467d29eb6328dc1ab3e900 to use the things we call "bundles" today), but I worry that without a clear up-front design/plan, we're going to end up with just a collection of random scripts that aren't very well organized and that the gains won't be as great as they could be if we create a concrete plan before we make any changes to the code itself.  Thoughts?

**Comment by dnephin** [comment]
@tianon that is very reasonable. I've written up a proposal in #35937

**Comment by dnephin** [comment]
I've rebased.  This PR is only a small step, but I believe it does start moving a few things in the direction of #35937

**Comment by vdemeester** [comment]
ping @dnephin @tianon what is the status here ? 👼

**Comment by dnephin** [comment]
I rebased this to run with the latest master

**Pull request closed without merging**
