### PR TITLE
Improve key specific bash subcompletions

### PR DESCRIPTION
**Pull request by albers**
This PR is about bash completion for options with map values, where the completion of the value depends on the key.

Examples:

> docker network ls --filter type=
> docker network ls --filter name=

where completion of the value depends on the key (`type` or `name` in this case).

The previous idiom of handling this was to check against `${words[$cword-2]}$prev=`, which is quite obscure and not specific enough.

In #19541, a more specifc alternative was needed but only introduced in one addition so that the PR could be included in 1.10. This PR replaces all remaining occurrences of the old idiom with the new one.

In order to keep it simpler to review, it is broken into two commits: one just swapping the execution order in some completions and another one with the actual change.

This PR also improves completion on Mac OS, where completion of `key=` will append a trailing whitespace. After backstepping, you can now use the subcompletions.

ping @jfrazelle @tianon please review.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon ptal (Thanks @albers !)

**Comment by tianon** [comment]
Nice!  LGTM

**Comment by vdemeester** [comment]
ahh cool, it did not run all tests for contrib :tada: — but weirdly enough it did run the documentation build :sweat_smile:

**Comment by thaJeztah** [comment]
LGTM

@vdemeester the documentation CI is not triggered through @GordonTheTurtle, so that could be expected

**Pull request merged**
