### PR TITLE
[26.1 backport] update to go1.22.6

### PR DESCRIPTION
**Pull request by austinvazquez**
**- What I did**
* Backported https://github.com/moby/moby/pull/48058 to 26.1 as a precursor for the golangci-lint update.
* Backported https://github.com/moby/moby/pull/47743 to 26.1 for Docker on Windows integration testing.
* Backported https://github.com/moby/moby/pull/48300 to 26.1.
* Backported https://github.com/moby/moby/pull/48359 to 26.1 for the golangci-lint update.
* Backported https://github.com/moby/moby/pull/46982 to 26.1.

**- How I did it**
```
git cherry-pick -xsS b24c2e95e57c5927765fa1ff5820576dda6e6242
git cherry-pick -xsS 6bd7835cb6965d8a2a86b0e32d9b44e42f09c7b5
git cherry-pick -xsS c7b36f8953dccc852ba5ea75134d89617c2952aa
git cherry-pick -xsS 2b7a6875548197faf0494fda1029afc15a88e301
git cherry-pick -xsS 3ca38f0b5e4a88b67205003b678474e07ab727ed
git cherry-pick -xsS 6bbacbec269bef3ab39c7614494a9ff504d428a0
git cherry-pick -xsS b79a4696ee45e3f28a5b772cbf0cb33fda000d6c
git cherry-pick -xsS 6008c42ca2903467964c430c0030a29ae4cc858e
git cherry-pick -xsS 06bfe8bab3038b37733d515954301b651b70326e
git cherry-pick -xsS 7b60a7047d982ba99cc6c0974bfb4eccf35fa705
git cherry-pick -xsS c308bd3e0e765ca0bd1161ecf8f7c4a9e5e74f4e
git cherry-pick -xsS b56c58a8601ab78a940c7e1c8cf5570d142d8abb
git cherry-pick -xsS 81a1ca02175a82911559cc20424d825375eaae98
git cherry-pick -xsS f434cdd14a99c38dc47f55680f624b4bae44e196
git cherry-pick -xsS 068c1bf3be15a41ec79ca6eb822e142f1a9cdc12
git cherry-pick -xsS 4a93233b8830ad5448ed7c848555f9b379b90ed1
git cherry-pick -xsS 0fd3a53c12b703bc636f525fd6364c1e83b3083f
git cherry-pick -xsS 005b488506e7b86cc0ce7a8268a577cb507c7d59
git cherry-pick -xsS 1ad5b5abb2a2eb3525ad175b1b76b6a6aa6ce598
git cherry-pick -xsS e853c093bf8b9b614b187d4571588f30e08d605d
git cherry-pick -xsS 4cd5c2b6435a4cc1afd01c01b85f01dfe9aa4da3
git cherry-pick -xsS 3df59c9dcf0063d8d833215771d1a2c15d9fad03
git cherry-pick -xsS 9b11bb507b37416493ddad926340defbe371e338
git cherry-pick -xsS f5108e9c6bfde83b7774dafaa355b6a413201131
```
resolving conflicts along the way.

**- How to verify it**
Successful CI verification should be enough

**- Description for the changelog**
```markdown changelog
Update toolchain in CI to Go 1.22.6
```

**- A picture of a cute animal (not mandatory but encouraged)**
🐘

### CODE REVIEW

**Comment by austinvazquez** [comment]
For completeness, it would be good to cherry-pick #48300. Not required but minimizes drift between the two trees. Will push another revision with this commit.

**Review by cpuguy83 — APPROVED** [review]

**Comment by cpuguy83** [comment]
```
=== FAIL: amd64.integration.container TestCreateWithCDIDevices (0.93s)
    cdi_test.go:68: assertion failed: [] does not contain FOO=injected

```

**Comment by thaJeztah** [comment]
Failure is a new one (haven't seen it before);

```
=== Failed
=== FAIL: amd64.integration.container TestCreateWithCDIDevices (0.93s)
    cdi_test.go:68: assertion failed: [] does not contain FOO=injected
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
