### PR TITLE
Add a short flag for docker stack deploy

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Comment by thaJeztah** [comment]
code LGTM, but don't forget the docs https://github.com/docker/docker/blob/master/docs/reference/commandline/stack_deploy.md, and completion scripts

**Comment by dnephin** [comment]
added to reference docs

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks

**Pull request merged**
