### PR TITLE
Adding support for Long term Mint releases in docker

### PR DESCRIPTION
**Pull request by lerignoux**
Added linux mint support as ubuntu version and updated documentation

### CODE REVIEW

**Comment by jfrazelle** [comment]
sorry this is a dup of https://github.com/docker/docker/pull/15001 but can you please help with testing that

**Comment by thaJeztah** [comment]
I think #15001 already covers the install.sh changes for mint, and was previously voted as the prefered approach.

@lerignoux could you test if #15001 works for you?

**Comment by jfrazelle** [comment]
lol jynx

**Pull request closed without merging**
