### PR TITLE
daemon: WithCapabilities(): drop CAP_NET_BIND_SERVICE if not needed

### PR DESCRIPTION
**Pull request by thaJeztah**
Commit dae652e2e5e47d99c8febd5bc81df0a3269beb74 (https://github.com/moby/moby/pull/41030) added support for non-privileged containers to use privileged ports if the host supports it.

Because of that, we should be able to conditionally drop CAP_NET_BIND_SERVICE from the list of capabilities.

This patch updates oci.WithCapabilities() to check if the container was configured to disable privileged ports (ip_unprivileged_port_start = 0), and if so, it drops CAP_NET_BIND_SERVICE.

See the [Linux documentation on ip_unprivileged_port_start](https://github.com/torvalds/linux/blob/v5.13/Documentation/networking/ip-sysctl.rst)

    ip_unprivileged_port_start - INTEGER
        This is a per-namespace sysctl. It defines the first unprivileged port in
        the network namespace. Privileged ports require root or CAP_NET_BIND_SERVICE
        in order to bind to them. To disable all privileged ports, set this to 0.
        They must not overlap with the ip_local_port_range.

        Default: 1024

And [capabilities(7)](https://man7.org/linux/man-pages/man7/capabilities.7.html)

    CAP_NET_BIND_SERVICE
        Bind a socket to Internet domain privileged ports (port
        numbers less than 1024).

With this patch applied:

    docker run -d --rm -p 80:80 -u 1000:1000 busybox /bin/sh -c 'echo -e "HTTP/1.1 200 OK\n\nhello world" | nc -l -p 80'
    e9768c2ade4f56ea0ddb62396ee9e6e0ea45f5f95780e97f13bfbc98ed1326b3

    ctr -a /var/run/docker/containerd/containerd.sock -n=moby c info e9768c2ade4f56ea0ddb62396ee9e6e0ea45f5f95780e97f13bfbc98ed1326b3 | jq .Spec.process.capabilities.bounding
    [
      "CAP_CHOWN",
      "CAP_DAC_OVERRIDE",
      "CAP_FSETID",
      "CAP_FOWNER",
      "CAP_MKNOD",
      "CAP_NET_RAW",
      "CAP_SETGID",
      "CAP_SETUID",
      "CAP_SETFCAP",
      "CAP_SETPCAP",
      "CAP_SYS_CHROOT",
      "CAP_KILL",
      "CAP_AUDIT_WRITE"
    ]

    curl localhost
    hello world

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Discussing in the maintainers meeting, and because this capability effectively never worked correctly without ambient capabilities, but also doesn't cause much risk (unless running with `--network=host`), so not really worth the complexity of this PR.

We'd rather drop it from the default list altogether, once we stop supporting kernels that don't have ``, which looks to have been added in https://github.com/torvalds/linux/commit/4548b683b78137f8eadeb312b94e20bb0d4a7141, (kernel 4.11)

**Comment by justincormack** [comment]
Can't we just drop it if the ip_unprivileged_port_start sysctl succeeds?

**Comment by thaJeztah** [comment]
> Can't we just drop it if the ip_unprivileged_port_start sysctl succeeds?

I think that's what this PR did (or is that not what you meant?)

**Pull request closed without merging**
