### PR TITLE
Revert fsnotify changes

### PR DESCRIPTION
**Pull request by cpuguy83**
Reverts changes to remove fsnotify from json log reader.
This caused a slowdown that made TestLogsFollowSlowStdoutConsumer fail on ARM 100% of the time.

```
benchmark                               old ns/op     new ns/op     delta
BenchmarkJSONFileLogger-8               53205         53077         -0.24%
BenchmarkJSONFileLoggerWithReader-8     93100         56483         -39.33%

benchmark                               old MB/s     new MB/s     speedup
BenchmarkJSONFileLogger-8               68.23        68.39        1.00x
BenchmarkJSONFileLoggerWithReader-8     20.30        33.46        1.65x

benchmark                               old allocs     new allocs     delta
BenchmarkJSONFileLogger-8               30             30             +0.00%
BenchmarkJSONFileLoggerWithReader-8     193            128            -33.68%

benchmark                               old bytes     new bytes     delta
BenchmarkJSONFileLogger-8               960           960           +0.00%
BenchmarkJSONFileLoggerWithReader-8     5753          3857          -32.96%
```

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @LK4D4 @anusha-ragunathan @mountkin

**Comment by mountkin** [comment]
@cpuguy83 can you check if #20605 mitigates the performance issue introduced by #19498 ?
In my test environment #20605 + #19498 is faster than the old approach.

fsnotify:
```
BenchmarkJSONFileLogger-8          	  200000	     67501 ns/op	  53.78 MB/s	     960 B/op	      30 allocs/op
BenchmarkJSONFileLoggerWithReader-8	  100000	    127740 ns/op	  14.80 MB/s	    5875 B/op	     197 allocs/op
```

#20605 + #19498
```
BenchmarkJSONFileLogger-8          	  300000	     57026 ns/op	  63.65 MB/s	     960 B/op	      30 allocs/op
BenchmarkJSONFileLoggerWithReader-8	  100000	    180476 ns/op	  10.47 MB/s	    2043 B/op	      80 allocs/op
```

BTW, I'm seeing the file poller is leaking a lot of fds on rotation (with the following test command)
```
docker run -d --name=test --log-opt max-size=50 --log-opt max-file=5 busybox sh -c "sleep 1;yes X|head -c 200"; docker logs -f test
```

**Comment by cpuguy83** [comment]
I ran arm tests on your PR and they failed.

**Comment by mountkin** [comment]
Can you help to test if https://github.com/mountkin/docker/tree/jsonlog-with-read-indexes fixed the ARM tests? I haven't got an ARM environment.

**Comment by cpuguy83** [comment]
I don't have one either, it's just part of CI.

**Comment by mountkin** [comment]
I'll open another PR to see the ARM tests result :smiley:

**Comment by cpuguy83** [comment]
@mountkin Yeah, I see that we are missing a `defer f.Close()` in the pollers watch function... will follow-up after this PR if it gets merged.

**Comment by anusha-ragunathan** [comment]
LGTM.

**Comment by LK4D4** [comment]
Actually `docker logs -f` doesn't work with rotation at all in master("bad file descriptor").

**Comment by LK4D4** [comment]
Test passed on arm, I'm merging.
LGTM

**Pull request merged**
