### PR TITLE
add testcase in layer/empty_test.go with Platform(),Metadata()

### PR DESCRIPTION
**Pull request by chchliang**
Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>

Add testcase in layer/empty_test.go with Platform(),Metadata() method.

### CODE REVIEW

**Comment by chchliang** [comment]
@GordonTheTurtle 

I have not modified here.

07:12:16 ----------------------------------------------------------------------
07:12:16 FAIL: docker_cli_daemon_test.go:1802: DockerDaemonSuite.TestDaemonNoSpaceLeftOnDeviceError
07:12:16 
07:12:16 [dc15407d2e882] waiting for daemon to start
07:12:16 [dc15407d2e882] daemon started
07:12:16 
07:12:16 docker_cli_daemon_test.go:1830:
07:12:16     c.Assert(pullOut, checker.Contains, "no space left on device")
07:12:16 ... obtained string = "" +
07:12:16 ...     "2: Pulling from library/registry\n" +
07:12:16 ...     "no matching manifest for linux/ppc64le in the manifest list entries\n"
07:12:16 ... substring string = "no space left on device"
07:12:16 
07:12:16 [dc15407d2e882] exiting daemon
07:12:18 
07:12:18 ----------------------------------------------------------------------

**Comment by thaJeztah** [comment]
ping @tonistiigi @dnephin PTAL

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
I think `Platform` on layer interface is wrong and should be removed. #34859 is at least changing it.  Testcase for metadata SGTM.

**Comment by chchliang** [comment]
@tonistiigi
Remove  the `Platform` testcase?

**Comment by tonistiigi** [comment]
Yes. If #34859 turns out to keep it in some form we can revisit it.

**Comment by chchliang** [comment]
@tonistiigi
Ok,i have removed the Platform testcase,thank you!

**Review by tonistiigi — APPROVED** [review]
LGTM

**Pull request merged**
