### PR TITLE
zfs nitpicks

### PR DESCRIPTION
**Pull request by kolyshkin**
Found these while reading the zfs code. IMHO worth fixing for the sake of future readers of the code.

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
can you squash into one commit please

**Comment by jfrazelle** [comment]
ping @Mic92 zfs maintainer :)

**Comment by Mic92** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
