### PR TITLE
awslogs log batch is flushed when an additional event would cause overflow

### PR DESCRIPTION
**Pull request by npgm**
**- What I did**
After the multiline support change, awslogs driver did not control for batch size overflow. The batch size was not maintained across processEvent and consecutive sufficiently large log events would result in a batch being rejected by cloudwatch. 

**- How I did it**
I maintain the batch size across calls to processEvent through use of the batchBuf struct. 

**- How to verify it**
See the example test, will fail with `git checkout master -- cloudwatchlogs.go`

**- Description for the changelog**
awslogs will no longer exceed maximum bytes per a put

**- A picture of a cute animal (not mandatory but encouraged)**
🐌

### CODE REVIEW

**Comment by npgm** [comment]
Will this make it to the actual docker distribution as well? I'm running into this issue and want to see it fixed.

**Comment by thaJeztah** [comment]
ping @samuelkarp @mixja

**Comment by mixja** [comment]
@npgm - I'm not sure this is the right approach as it is modifying the original data structure used for event processing before the multiline logging was added.  I will look into this and see where the root cause of the issue is as there is a check in the current code for this exact scenario.

**Comment by mixja** [comment]
@npgm - I think I have resolved the bug as per https://github.com/mixja/docker/commit/b6f241faf02d97353b6f765510475d976849e4fc, but need to add some test cases to validate (this commit does pass your test case).  

The issue was that the processEvent method was not taking into consideration existing events in events slice, also I noted that I was not taking into consideration the appendage of a new line character in one of the size calculations.

**Comment by npgm** [comment]
@mixja in your for loop won't you need to add perEventBytes as well?

Thanks for fixing

**Comment by mixja** [comment]
@npgm - yes you are correct, I have updated

**Comment by samuelkarp** [comment]
@mixja https://github.com/moby/moby/compare/master...mixja:fix-awslogs-max-event-processing looks correct to me.  Are you going to open a PR for that?

**Comment by jmenga** [comment]
@samuelkarp - yes I will open a PR once I write a few test cases to make sure this fix is rock solid

**Comment by cpuguy83** [comment]
What's the status on this one?

**Comment by mixja** [comment]
@cpuguy83 - sorry this slipped off my radar.  https://github.com/moby/moby/compare/master...mixja:fix-awslogs-max-event-processing appears to fix the issue and fixed the OP failing test, I just needed to write some further tests.  I will get on to this in the next few days and raise the PR.

**Comment by cpuguy83** [comment]
Thanks for the update @mixja!

**Comment by mixja** [comment]
@cpuguy83 - I have looked at this again and the changes made in https://github.com/moby/moby/commit/ad14dbf1346742f0607d7c28a8ef3d4064f5f9fd resolve the original issue.  [I added the test that failed for the original issue and all tests pass OK](https://github.com/mixja/docker/commit/8a8958f4247e78342ac30e5345610b3299aff268).

[Note there is a small bug I found here](https://github.com/mixja/docker/blob/fix-awslogs-max-event-processing/daemon/logger/awslogs/cloudwatchlogs.go#L437), but I will raise a separate PR for this. 

Therefore I would recommend this issue is closed.

**Comment by cpuguy83** [comment]
Awesome, thanks!

**Pull request closed without merging**
