### PR TITLE
Update SECURITY.md to have an option to keep name anonymous if requested

### PR DESCRIPTION
**Pull request by yongtang**
Update SECURITY.md to have an option to keep name anonymous if requested

Note this is a follow up on #39378, think it makes sense to allow people keep their name confidential for vulnerability findings.

/cc @cpuguy83 @justincormack @thaJeztah 

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @justincormack

**Review by shehrozkhan88 — COMMENTED** [review]
https://github.com/moby/moby/pull/39373#issue-289364795

**Pull request merged**
