### PR TITLE
DO NOT MERGE: testing z ci

### PR DESCRIPTION
**Pull request by tophj-ibm**
DO NOT MERGE!!!! 

Testing Z CI related to several machines not loading frozen images correctly. I can't recreate the failures locally on the machines.

### CODE REVIEW

**Comment by tophj-ibm** [comment]
@thaJeztah (and anyone else) if you see z CI fail, especially with frozen images problems, can you let me know asap? I suspect that something is wrong with the environment on the machine itself, but I have been unable to recreate it on any of my tests, and our cron triggered cleanup scripts have wiped away any logs I could use.

**Comment by kolyshkin** [comment]
@tophj-ibm can you take a look, this one looks relevant:
https://ci.qa.aws.dckr.io/job/docker-ee-pr-s390x/154/console

**Comment by kolyshkin** [comment]
> @tophj-ibm can you take a look, this one looks relevant:
> https://ci.qa.aws.dckr.io/job/docker-ee-pr-s390x/154/console

Here's the copy of the output: 
https://gist.github.com/kolyshkin/0657a9e3fcb79d451f8772ad83cfebc1

**Comment by tophj-ibm** [comment]
@kolyshkin taking a look now, had to get access to some of those nodes

**Comment by tophj-ibm** [comment]
that didn't work correctly, sorry for spam

**Pull request closed without merging**
