### PR TITLE
cleanup hack/.vendor-helpers.sh

### PR DESCRIPTION
**Pull request by jessfraz**
seccomp is already in $dockerBuildTags
ping @tianon

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @calavera

**Comment by jfrazelle** [comment]
hang on im going to add other stuff to this

**Comment by tianon** [comment]
LGTM as-is -- I wonder if we should instead consider just collecting a list of all possible build tags we might care about and try every permutation, but that sounds even more computationally expensive than what we already do here :disappointed:

**Comment by jfrazelle** [comment]
ok cool i can do other stuff in another pr :)

**Comment by calavera** [comment]
LGTM

**Pull request merged**
