### PR TITLE
Cleanup: changed ./hack to ./project in README.md

### PR DESCRIPTION
**Pull request by grossws**

### CODE REVIEW

**Comment by grossws** [comment]
@GordonTheTurtle, fixed

**Comment by SvenDowideit** [comment]
LGTM - @jfrazelle @tiborvass

**Comment by SvenDowideit** [comment]
actually, I'm confused - I seem to have a make.sh in both `hack` and `project`, and the Dockerfile still refers to the `hack` one

@tianon ??

**Comment by grossws** [comment]
`hack` is symlink now, so its contents should be same as `project`'s

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
NOOOOO https://github.com/docker/docker/issues/10741

**Comment by ahmetalpbalkan** [comment]
@tianon hahaahahaha

**Pull request merged**
