### PR TITLE
Remote API doc fix wrong JSON properties for /events

### PR DESCRIPTION
**Pull request by davinashreddy**
Remote API, 1.22 & 1.23 generates wrong JSON properties for /events. Issue #20194 

Signed-off-by: Avinash Desireddy avinashreddy1090@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like you pulled in a non-related commit during rebasing.

**Comment by thaJeztah** [comment]
@calavera was it the intent to have these properties in mixed case? e.g. I see theres both an `id` (lowercase) and `ID` in the response.

**Comment by davinashreddy** [comment]
@thaJeztah yes. I figured it during pull but just followed the instructions provided by GordonTheTurtle

**Comment by calavera** [comment]
Docs LGTM, but there are some extra commits that I think are not related, can we get rid of them?

**Comment by calavera** [comment]
@davinashreddy please, let us know if you can address the issues in your changes, otherwise we'll have to close this PR without merging it.

**Comment by davinashreddy** [comment]
@calavera sorry. I am unable to address this right now. We can go ahead and close this PR without merging it. Thanks.

**Pull request closed without merging**
