### PR TITLE
Btrfs has eliminated the BTRFS_BUILD_VERSION in latest version

### PR DESCRIPTION
**Pull request by rhatdan**
They say we should only use the BTRFS_LIB_VERSION

They will no longer support this since it had to be managed manually

Docker-DCO-1.1-Signed-off-by: Dan Walsh dwalsh@redhat.com (github: rhatdan)

### CODE REVIEW

**Comment by tianon** [comment]
Does that mean http://repo.or.cz/w/btrfs-progs-unstable/devel.git/commit/514c5689bd672b21fa8033a7a48eae56a6e36b7f was reverted?

cc @lsm5 @vbatts

**Comment by rhatdan** [comment]
The comments in the bugzilla seemed to indicate that upstream would not take a patch to put the BTRFS_BUILD_VERSION back since it was being manually created while BTRFS_LIB_VERSION can be automatically created.

**Comment by jfrazelle** [comment]
```
# github.com/docker/docker/daemon/graphdriver/btrfs
./version_test.go:10: invalid argument BtrfsLibVersion() (type int) for len
Precompiled: github.com/docker/docker/daemon/graphdriver/overlay
Precompiled: github.com/docker/docker/daemon
Precompiled: github.com/docker/docker/daemon/networkdriver
Precompiled: github.com/docker/docker/daemon/graphdriver/devmapper
Precompiled: github.com/docker/docker/daemon/graphdriver/vfs
Precompiled: github.com/docker/docker/daemon/networkdriver/ipallocator
Precompiled: github.com/docker/docker/daemon/networkdriver/portallocator
Precompiled: github.com/docker/docker/daemon/networkdriver/portmapper
Precompiled: github.com/docker/docker/daemon/networkdriver/bridge
```

**Comment by lsm5** [comment]
@tianon @rhatdan for now, sandeen and kdave sound ok with it: https://bugzilla.redhat.com/show_bug.cgi?id=1202373#c4 and given that the patch grabs whatever value exists for PACKAGE_VERSION from its config.h, it shouldn't be a hassle I think. correct me if i'm wrong.

**Comment by jfrazelle** [comment]
can you fix the unit test @rhatdan, otherwise this seems like a sane fix to me :)

**Comment by rhatdan** [comment]
Fixed.

**Comment by jfrazelle** [comment]
still failing the unit tests, would be nice to get this into 1.6.0-rc2, do you want us to carry

**Comment by vbatts** [comment]
@jfrazelle strange. and the build box has the have /usr/include/btrfs/version.h?

```
+ go test -test.timeout=45m github.com/docker/docker/daemon/graphdriver/btrfs
--- FAIL: TestLibVersion (0.00s)
	version_test.go:11: expected output from btrfs lib version > 0
FAIL
```

would only happen if docker was built with btrfs_noversion

**Comment by vbatts** [comment]
OH! ubuntu ... :-( 
it _is_ built with `btrfs_noversion`

**Comment by jfrazelle** [comment]
oh so wait should i just upgrade btrfs-tools is that the problem

**Comment by vbatts** [comment]
well, ideally the test would be on a newer btrfs... but would mean the test will fail when there is no version.h.

@rhatdan perhaps move you Lib Version test to a _test.go file that has the build tags of `// +build linux,btrfs_noversion`

**Comment by rhatdan** [comment]
Sadly I did that locally but never pushed.

**Comment by vbatts** [comment]
https://www.youtube.com/watch?v=vCadcBR95oU

**Comment by vbatts** [comment]
\o/

**Comment by vbatts** [comment]
LGTM

**Comment by tianon** [comment]
Aw, that's a shame.  The library version is completely 1000% meaningless to me (where the "build version" actually matches the version number of the package I've got installed), but OK.

LGTM

**Comment by tianon** [comment]
Couldn't we instead find a way to conditionally include this based on that one release of btrfs-progs that doesn't have the build version info (since they added it back thanks to @lsm5)?

**Comment by tianon** [comment]
It's especially worrying since they never responded to https://bugzilla.redhat.com/show_bug.cgi?id=1202373#c5 to tell us whether they approve of our use of this header bit or not. :cry:

**Comment by vbatts** [comment]
@tianon an `#ifdef` check would be easy enough, and the stubbing out that info in the `Status()`. That's what I'd started. Perhaps by that time, we can have a better position from upstream.

**Comment by jfrazelle** [comment]
/me is not pleased there is a merge commit tsk tsk

**Comment by tianon** [comment]
@vbatts :+1: :heart_eyes:

**Comment by vbatts** [comment]
Meaningless, but more than nothing. I also understand the difficulty in
maintaining a string like that, when it is not automatically produced. When
/if they add a better version string, we'll consume it.

**Comment by tianon** [comment]
They did, though!  @lsm5 sent the patch and they applied it, and it
shouldn't be a problem going forward because it's autogenerated now instead
of manually curated.

**Comment by vbatts** [comment]
Ah yeah. I had to dig for that commit. it's not in their master
http://git.kernel.org/cgit/linux/kernel/git/kdave/btrfs-progs.git/commit/?h=v3.19.x&id=514c5689bd672b21fa8033a7a48eae56a6e36b7f

**Comment by lsm5** [comment]
/me is late to the party... the BUILD_VERSION patch has now landed in btrfs-progs master branch

**Comment by jfrazelle** [comment]
yayyyyy!

**Pull request merged**
