### PR TITLE
Fix TestUpdateKernelMemoryUninitialized on new kernel version

### LINKED ISSUE #25073: s390x: TestUpdateKernelMemoryUninitialized fails for CI
The CI test DockerSuite.TestUpdateKernelMemoryUninitialized currently fails on s390x:

https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/74/consoleFull

```
TESTFLAGS='-check.f DockerSuite.TestUpdateKernelMemoryUninitialized' DOCKER_GRAPHDRIVER=vfs DOCKER_EXECDRIVER=native TIMEOUT="120m" hack/make.sh test-integration-cli

FAIL: docker_cli_update_unix_test.go:132: TestUpdateKernelMemoryUninitialized.pN52_github_com_docker_docker_int<-egration_cli.DockerSuite

docker_cli_update_unix_test.go:139:
    // Update kernel memory to a running container without kernel memory initialized is not allowed.
    c.Assert(err, check.NotNil)
... value = nil
```

System Information for Jenkins node (Docker host):

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux lxdeb02 4.6.0-1-s390x #1 SMP Debian 4.6.4-1 (2016-07-18) s390x GNU/Linux

$ cat /proc/cmdline 
root=/dev/disk/by-path/ccw-0.0.0150-part2 cgroup_enable=memory swapaccount=1 BOOT_IMAGE=0

$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.4.2 gccgo (GCC) 5.3.0
 Git commit:   20f81dd
 Built:        Thu Apr 28 12:38:04 2016
 OS/Arch:      linux/s390x

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.4.2 gccgo (GCC) 5.3.0
 Git commit:   20f81dd                                                          
 Built:        Thu Apr 28 12:38:04 2016                                         
 OS/Arch:      linux/s390x 
```

CI Docker version: bad654b00c954e31007c5004629e236c06ca4046

```
$ docker version                                          
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.1 gccgo (GCC) 6.1.0
 Git commit:   bad654b
 Built:        Tue Jul 26 11:54:03 2016
 OS/Arch:      linux/s390x

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.1 gccgo (GCC) 6.1.0
 Git commit:   bad654b
 Built:        Tue Jul 26 11:54:03 2016
 OS/Arch:      linux/s390x

$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.12.0-dev
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.0-1-s390x
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: s390x
CPUs: 2
Total Memory: 31.38 GiB
Name: b586aa5f5665
ID: VMY7:KSD2:X2HC:36Y6:GIF7:567I:CUQF:BBKV:5JOG:ELWT:3CTO:SV5W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

### PR DESCRIPTION
**Pull request by hqhq**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Fixes: #25073

Update kernel memory on running containers without initialized
is forbidden only on kernel version older than 4.6.

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Comment by michael-holzheu** [comment]
Hmm this is weird...

With your patch I get the following error message on s390x:

```
---> Making bundle: .ensure-syscall-test (in bundles/1.12.0-dev/test-integration-cli)
---> Making bundle: .ensure-nnp-test (in bundles/1.12.0-dev/test-integration-cli)
+ go test -check.f DockerSuite.TestUpdateKernelMemoryUninitialized -check.v -check.timeout=120m -test.timeout=360m github.com/docker/docker/integration-cli
# testmain
/usr/bin/ld: $WORK/libgo-sqlite3.a427057433(sqlite3-binding.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2'
//lib/s390x-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
---> Making bundle: .integration-daemon-stop (in bundles/1.12.0-dev/test-integration-cli)
+++++ cat bundles/1.12.0-dev/test-integration-cli/docker.pid
++++ kill 4179
```

**Comment by michael-holzheu** [comment]
Looks like a gccgo specific problem. My current theory is that now daemon/daemon_unix.go that requires libpthread is linked to the integration test.

**Comment by michael-holzheu** [comment]
If I move the kernel version check into the integration testsuite it works with gccgo:

```
diff --git a/integration-cli/docker_cli_update_unix_test.go b/integration-cli/docker_cli_update_unix_test.go                                                  
index 96cb288..6595e9a 100644                                                                                                                                 
--- a/integration-cli/docker_cli_update_unix_test.go                                                                                                          
+++ b/integration-cli/docker_cli_update_unix_test.go
@@ -7,8 +7,9 @@ import (
        "fmt"
        "strings"
 
-       "github.com/docker/docker/daemon"
+       "github.com/Sirupsen/logrus"
        "github.com/docker/docker/pkg/integration/checker"
+       "github.com/docker/docker/pkg/parsers/kernel"
        "github.com/docker/engine-api/types"
        "github.com/go-check/check"
 )
@@ -130,10 +131,21 @@ func (s *DockerSuite) TestUpdateKernelMemory(c *check.C) {
        c.Assert(strings.TrimSpace(out), checker.Equals, "104857600")
 }
 
+func checkKernelVersion(k, major, minor int) bool {
+       if v, err := kernel.GetKernelVersion(); err != nil {
+               logrus.Warnf("error getting kernel version: %s", err)
+       } else {
+               if kernel.CompareKernelVersion(*v, kernel.VersionInfo{Kernel: k, Major: major, Minor: minor}) < 0 {
+                       return false
+               }
+       }
+       return true
+}
+
 func (s *DockerSuite) TestUpdateKernelMemoryUninitialized(c *check.C) {
        testRequires(c, DaemonIsLinux, kernelMemorySupport)
 
-       isNewKernel := daemon.CheckKernelVersion(4, 6, 0)
+       isNewKernel := checkKernelVersion(4, 6, 0)
        name := "test-update-container"
        dockerCmd(c, "run", "-d", "--name", name, "busybox", "top")
        _, _, err := dockerCmdWithError("update", "--kernel-memory", "100M", name)
```

**Comment by hqhq** [comment]
@michael-holzheu I updated this PR, can you please test again?

**Comment by michael-holzheu** [comment]
> @michael-holzheu I updated this PR, can you please test again?

Looks good now:

```
---> Making bundle: .ensure-httpserver (in bundles/1.13.0-dev/test-integration-cli)
---> Making bundle: .ensure-syscall-test (in bundles/1.13.0-dev/test-integration-cli)
---> Making bundle: .ensure-nnp-test (in bundles/1.13.0-dev/test-integration-cli)
+ go test -check.f DockerSuite.TestUpdateKernelMemoryUninitialized -check.v -check.timeout=120m -test.timeout=360m github.com/docker/docker/integration-cli
INFO: Testing against a local daemon
PASS: docker_cli_update_unix_test.go:133: TestUpdateKernelMemoryUninitialized.pN52_github_com_docker_docker_integration_cli.DockerSuite 4.229s
OK: 1 passed
```

**Comment by vdemeester** [comment]
LGTM :cat:

**Comment by thaJeztah** [comment]
docs LGTM

we may want to improve a bit in a follow up (all the versions in the main text make it a bit difficult to read), but good for now

**Pull request merged**
