### PR TITLE
Windows: Dockerfile for TP5

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Updates dockerfile.windows to 
- Not sleep (TP4 workaround)
- Refresh to latest version of git

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by icecrime** [comment]
Mmm something broke:

```
16:44:45 Step 5 : COPY . /go/src/github.com/docker/docker
16:44:58  ---> 67fa28e6d02f
16:44:58 Removing intermediate container 9b922fcbba03
16:44:58 Successfully built 67fa28e6d02f
16:44:58 + lastec=0
16:44:58 + set +x
16:44:58 INFO: Building the test binary...
16:44:58 + docker run --rm -v 'd:\CI\CI-7484202:c:\target' docker sh -c 'cd /c/go/src/github.com/docker/docker; \
16:44:58 	hack/make.sh binary; \
16:44:58 	ec=$?; \
16:44:58 	if [ $ec -eq 0 ]; then \
16:44:58 		robocopy /c/go/src/github.com/docker/docker/bundles/$(cat VERSION)/binary /c/target/binary; \
16:44:58 	fi; \
16:44:58 	exit $ec'
16:45:01 C:\Windows\system32\docker.exe: Error response from daemon: Container command 'sh' not found or does not exist.
```

**Comment by jhowardmsft** [comment]
Sigh :smiling_imp: Welcome to new bugs in TP5.... Some will be fixed in the ZDP and servicing fixes that are in the pipeline. Restarted.

**Comment by jhowardmsft** [comment]
Fascinating. It wasn't a TP5 bug causing the previous failure. Something has changed in the git for Windows installer between 2.7.2 and 2.8.1 that I had bumped it to. Reverted that bit of the change and will investigate the cause of that failure for a separate PR.

**Comment by cpuguy83** [comment]
LGTM

**Comment by StefanScherer** [comment]
No more "Sleep" - awesome!

**Pull request merged**
