### PR TITLE
Remove vim syntax files

### PR DESCRIPTION
**Pull request by honza**
The new canonical place for the vim syntax file is in the upstream vim
tree.  All improvements and patches should be submitted there.

https://github.com/vim/vim/blob/master/runtime/syntax/dockerfile.vim

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by thaJeztah — COMMENTED** [review]
generally looks good to me, but:

- should we keep a README and point to the new location / installation instructions?
- I'm curious where the files in the vim repository were obtained from; the commit adding it there (https://github.com/vim/vim/commit/34401cca5ae3dce543154c967d727b13254e15b5#diff-b31c517c9785059e366523fbf07f734f) doesn't mention that; I see the content is different from the one in this repository, so either could have been an outdated version, or updated version (I'm not familiar with these files)

More worrisome: the files in this repository were added through https://github.com/moby/moby/commit/ace059e409f0df056ace0191b02504d051b81d92, taking them from the original repository with approval from the author. While the files in the vim repository mention the original author ([here](https://github.com/vim/vim/blob/56c860c315c517d304320e12bf7b5c1479546dae/runtime/syntax/dockerfile.vim#L2) and [here](https://github.com/vim/vim/blob/a87b72cc316e065d66dcbcf7ec1cde330adef3a3/runtime/ftplugin/dockerfile.vim#L3)), the repository doesn't look to have copied the LICENSE, nor retained the copyright, thus seem to be violating the original license; https://github.com/honza/dockerfile.vim/blob/82711a335dadab82508aed0f34bc4591a09c7d4f/LICENSE

**Comment by thaJeztah** [comment]
LOL, and I just realised you are the original author 🤦‍♂ 😂 

I guess the license issue is not a problem then; still: would it be useful to have the README updated instead of removed you think?

**Comment by honza** [comment]
Hey, thanks for doing the due diligence on this. I'm happy to add a simple README with a link to the vim version.

**Review by AkihiroSuda — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
perfect, thank you!

LGTM

**Comment by thaJeztah** [comment]
Test failures are unrelated; let me go ahead and merge this one

**Pull request merged**
