### PR TITLE
Remove some fmt.Printf from integration-cli/daemon…

### PR DESCRIPTION
**Pull request by vdemeester**
… to flood a little bit less the integration cli output. This also makes `Daemon` usable with both `go-check` and `testing` :angel: 

/cc @vieux @aaronlehmann @thaJeztah 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Thanks.

I believe until things changed recently, these messages were printed for failed tests, but not successful tests. That was a nice compromise because it was easy to get the daemon IDs when investigating a test failure.

Are we going back to that approach, or will this also remove the output when a test fails?

**Comment by vdemeester** [comment]
@aaronlehmann you're right, should have done that in the first place :angel: I'll work on it :angel:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
All green

**Pull request merged**
