### PR TITLE
Return rpm version of packages in docker version

### PR DESCRIPTION
**Pull request by rhatdan**
Docker-DCO-1.1-Signed-off-by: Dan Walsh dwalsh@redhat.com (github: rhatdan)

We have been asked to add this for our support people.  Not sure if this is something docker would be interested in, and it obviously would need to have apt/dep support added.

### CODE REVIEW

**Comment by phemmer** [comment]
This seems rather odd to me. Manually running `rpm -qf /path/to/foo` is global, it works for all software. After all, `grep --version` doesn't show the rpm package version. What makes docker different?

**Comment by rhatdan** [comment]
Simplifies support flow, and it returns client and server version.
Red Hat support asked for it.  I agree in most cases it is just doing two commands to get output.

**Comment by jfrazelle** [comment]
I do not know if this is something we want to support

**Comment by rhatdan** [comment]
@jfrazelle Understood.  Just wanted to point it out to you guys, that we have this patch.

**Comment by jfrazelle** [comment]
So I am going to close as I do not think it is something we need. But thanks for bringing it to our attention. Sorry for the huge delay.

**Comment by rhatdan** [comment]
No problem, I think this is entirely a distribution thing.  I am not crazy about it, but Red Hat support wants it...

**Pull request closed without merging**
