### PR TITLE
Add bash completion for `docker build --network`

### PR DESCRIPTION
**Pull request by albers**
Ref: #27702

Completion is the same as for `docker run --network`. Is that correct?

Please schedule for 1.13.0
Ping @sdurrheimer for zsh completion

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think it supports all the same options yes, but @cpuguy83  @justincormack just to be sure

**Comment by vieux** [comment]
ping @cpuguy83 @justincormack

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Pull request merged**
