### PR TITLE
loopback (and devicemapper) cleanup

### PR DESCRIPTION
**Pull request by vbatts**
There is no logic change here, re-arrange and cleanup.

The loopback logic is not technically exclusive to the devicemapper driver. This reorganizes the code such that the loopback code is usable outside of the devicemapper package and driver.

ping @calavera @rhvgoyal @tiborvass

### CODE REVIEW

**Comment by rhvgoyal** [comment]
@vbatts Do you have a user in mind who is planning to use loopback package?

**Comment by rhvgoyal** [comment]
I think in general sounds like a good idea. If breaking existing users of devicemapper is not a concern, I think it should be fine to make this change.

**Comment by vbatts** [comment]
@rhvgoyal i'm presently re-using the code myself, and found that it's useful, but I don't need the devicemapper package.
And yes, if there were existing users from `pkg/devmapper` they'd have to switch to `pkg/loopback`. Broken, but not devastating.

**Comment by runcom** [comment]
@vbatts needs rebase :(

**Comment by vbatts** [comment]
done

**Comment by runcom** [comment]
LGTM, I doubt anyone out there uses pkg/devmapper (we broke pkg/... interfaces other times as well)

**Comment by calavera** [comment]
LGTM

**Pull request merged**
