### PR TITLE
docker 1.8+ no longer needs dind

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon idk what to make the entrypoint tbh or if you think this is too soon ;)

### CODE REVIEW

**Comment by jfrazelle** [comment]
hmm weird errors... need to investigate why...

**Comment by jfrazelle** [comment]
the windows side is because i need to update those servers

**Comment by thaJeztah** [comment]
Is this still needed? https://github.com/docker/docker/blob/master/hack/dind#L14

**Comment by tianon** [comment]
Ohh, because it auto-mounts the cgroup hierarchy?  Very interesting indeed.

IMO we should still keep the entrypoint around for a while since it'll still be needed on older Docker versions, but making it do the mounting nonsense conditionally based on whether we've already got it all mounted seems really sane. :+1: (ie, `if ! mountpoint -q /sys/fs/cgroup; then ...`)

**Comment by jfrazelle** [comment]
nice yeah

**Comment by tianon** [comment]
LGTM :metal:

**Comment by tianon** [comment]
(much easier to review via https://github.com/docker/docker/pull/15596/files?w=1 now)

**Pull request merged**
