### PR TITLE
daemon: remove v1 shim configuration for containerd

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/moby/moby/pull/41656 (specifically https://github.com/moby/moby/pull/41656#discussion_r520316903)

This removes the plugin section from the containerd configuration file (`/var/run/docker/containerd/containerd.toml`) that is generated when starting containerd as child process;

```toml
[plugins]
  [plugins.linux]
    shim = "containerd-shim"
    runtime = "runc"
    runtime_root = "/var/lib/docker/runc"
    no_shim = false
    shim_debug = true
```

This configuration doesn't appear to be used since commit: 0b14c2b67a4ef8637c5f4680b33763224e4b40e8 (https://github.com/moby/moby/pull/41210), which switched the default runtime to to io.containerd.runc.v2.

Note that containerd itself uses `containerd-shim` and `runc` as default for `shim` and `runtime` v1, so omitting that configuration doesn't seem to make a difference.

I'm slightly confused if any of the other options in this configuration were actually used: for example, even though `runtime_root` was configured to be `/var/lib/docker/runc`, when starting a container with that coniguration set on docker 19.03, `/var/lib/docker/runc` doesn't appear to exist:

```console
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
098baa4cb0e7        nginx:alpine        "/docker-entrypoint.…"   59 minutes ago      Up 59 minutes       80/tcp              foo

$ ls /var/lib/docker/runc
ls: /var/lib/docker/runc: No such file or directory

$ ps auxf
PID   USER     TIME  COMMAND
    1 root      0:00 sh
   16 root      0:11 dockerd --debug
   26 root      0:09 containerd --config /var/run/docker/containerd/containerd.toml --log-level debug
  234 root      0:00 containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/09
  251 root      0:00 nginx: master process nginx -g daemon off;
  304 101       0:00 nginx: worker process
...

```

**- Description for the changelog**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@AkihiroSuda @cpuguy83 @tonistiigi PTAL; IIUC, this configuration was not used at all. I'm slightly confused though why the `runtime_root ` was not used (or perhaps I didn't check correctly). Also wondering if the v2 shim does not need a similar section in the `containerd.toml` that we generate

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
@cpuguy83 @tonistiigi PTAL

**Comment by thaJeztah** [comment]
Rebased

**Comment by thaJeztah** [comment]
rebased

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Rebased to get a fresh run of CI

Is this one Good to go? (Anything we need to mention in the documentation?)

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
