### PR TITLE
Remove subdirectories MAINTAINERS files

### PR DESCRIPTION
**Pull request by icecrime**
Remove all subdirectories `MAINTAINERS` files in favor of the newly created one at the root.

### CODE REVIEW

**Comment by tianon** [comment]
Would you mind if we keep the ones in `contrib/`?  I think it's fine if they're officially meaningless, but IMO they're still useful for knowing who the "bodies on the ground" are, so to speak (ie, who can I ping on this issue for useful review).

**Comment by tianon** [comment]
Especially because otherwise I have to try and remember who these folks are, and I'm not at all good at that. :innocent:

**Comment by tianon** [comment]
Maybe even rename them to something else to make their status clear, like `REVIEWERS`?

**Comment by icecrime** [comment]
Thanks @tianon, makes sense!

**Comment by crosbymichael** [comment]
i'll merge if this looks good to you @tianon

**Comment by tianon** [comment]
LGTM :heart:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
