### PR TITLE
Use different host and container port for clarity

### LINKED ISSUE #11953: [DOC] Provide example with different inside / outside ports numbers
In this page:

https://docs.docker.com/userguide/dockerlinks/#connect-using-network-port-mapping

the `-p` flag is explained.
The example maps port 5000 inside the container to the same port on the host machine.
An example that used two different ports would help readers tell at a glance which side of the ":" refers to container and which one to the host machine.

### PR DESCRIPTION
**Pull request by ankushagarwal**
Fixes #11953

Signed-off-by: Ankush Agarwal ankushagarwal11@gmail.com

### CODE REVIEW

**Comment by ankushagarwal** [comment]
@marcelloromani  : This should fix #11953
Ping @moxiegirl for review

**Comment by moxiegirl** [comment]
LGTM

**Comment by marcelloromani** [comment]
LGTM too.

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
