### PR TITLE
What if authConfig or factory is Nill?

### PR DESCRIPTION
**Pull request by hashneo**

### CODE REVIEW

**Comment by duglin** [comment]
ping @dmcgowan 
Seems ok

**Comment by jfrazelle** [comment]
LGTM ping @tiborvass @dmcgowan

**Comment by tiborvass** [comment]
Initially thought would be better to error out, but I now think it's okay like this.

LGTM
But @dmcgowan has the verdict :)

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
