### PR TITLE
Fix phrasing when referring to the freezer cgroup

### PR DESCRIPTION
**Pull request by odinuge**
**- What I did**
Fix phrasing when referring to the freezer cgroup

ref. http://man7.org/linux/man-pages/man7/cgroups.7.html

**- How I did it**
`N/A`

**- How to verify it**
`N/A`

**- Description for the changelog**

Fix phrasing when referring to the freezer cgroup

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Flaky test on docker-py; https://jenkins.dockerproject.org/job/Docker-PRs/55488/console

```
19:03:26 =================================== FAILURES ===================================
19:03:26 __________________ AttachContainerTest.test_attach_no_stream ___________________
19:03:26 tests/integration/api_container_test.py:1250: in test_attach_no_stream
19:03:26     assert output == 'hello\n'.encode(encoding='ascii')
19:03:26 E   AssertionError: assert b'' == b'hello\n'
19:03:26 E     Right contains more items, first extra item: 104
19:03:26 E     Use -v to get the full diff
```

**Comment by thaJeztah** [comment]
All green now 👍 merging. Thanks!

**Pull request merged**
