### PR TITLE
Docs: Add docker-elements to remote API client lib doc page

### LINKED ISSUE #16824: [Doco] Add docker-elements onto the remote API Client Libraries
Add docker-elements on the remote API Client Libraries page https://docs.docker.com/reference/api/remote_api_client_libraries/

Name: docker-elements
Language/Framework: HTML5/JavaScripts (Polymer Web Components)
Link: https://github.com/kapalhq/docker-elements

These elements are reusable HTML WebComponents that can be reused in HTML5 app or even in Server-Side WebApp

### PR DESCRIPTION
**Pull request by jwayong**
Add docker-elements to remote API client lib doc page. https://github.com/kapalhq/docker-elements

This should close #16824

### CODE REVIEW

**Comment by thaJeztah** [comment]
Great, thanks! LGTM

out of interest; is there a demo already; how do I use/run this? Perhaps you should add a Dockerfile to the repository to run the project and start a demo.

**Comment by jwayong** [comment]
@thaJeztah there's a very vanilla demo on http://kapalhq.github.io/docker-elements/, if you visit the site it will docker pull the example container jess/visualstudio and if you run Linux desktop with hardware graphic driver (non-vm) it will even spawn up the container in the desktop for u.

We are working currently on the detailed documentation (proper API doco), more demos and a complementary tools for this.

**Comment by thaJeztah** [comment]
Ah, right, thanks!

**Comment by thaJeztah** [comment]
ping @fredlf @jamtur01 @moxiegirl @SvenDowideit for review

**Comment by jwayong** [comment]
@thaJeztah I've updated doco with example on this page http://kapalhq.com/docker-elements/docs/ 
Check out the demo for docker-attach or docker-create (they're the same). Thx..

**Pull request merged**
