### PR TITLE
pkg: remove random package

### PR DESCRIPTION
**Pull request by stevvooe**
The unnecessary `random` package has been removed in favor of using the
`math/rand` package directly. Seeding of the random value from crypto
has been added to the `stringid` package to account for the change.

May need to add an equivalent seed to `namesgenerator`, but this is
often used with `stringid` and has collision protection.

Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I don't expect stringid to initialize the global rand.
I think we should avoid using global rand, and pass local rand instances to pkgs as args

**Comment by stevvooe** [comment]
@akihirosudo this package is somewhat broken in this regard -- these should just use thee crypto rand and be done with it.

**Comment by thaJeztah** [comment]
ping @LK4D4 ptal :heart:

**Comment by vieux** [comment]
SGTM

**Comment by stevvooe** [comment]
> I think we should avoid using global rand, and pass local rand instances to pkgs as args

This is a more extensive refactoring. Really, we should be focused on minimizing the number of dependencies. Seeding the global PRNG doesn't seem like a bad thing.

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by tonistiigi** [comment]
We could make a `seed` pkg that just runs the init and the `stringid` and `namesgenerator` would import it. SGTM as is as well, although would be nice to document that `namesgenerator` requires an external seed call.

**Comment by stevvooe** [comment]
> We could make a seed pkg

Considered this, but then we'd be in the same situation.

I can add seeding to the namesgenerator, as well, if that helps.

I think the right solution here is to allow one to seed the package, rather than forcing the user to create a fully baked, thread-safe source.

**Comment by thaJeztah** [comment]
@tonistiigi did you want the additional changes to be made?

**Comment by tonistiigi** [comment]
@thaJeztah No, was just pointing out alternative approaches.

We do actually already vendor `github.com/sean-/seed` that does basically the same thing. We don't explicitly call it in docker code, but memberlist pkg calls it in init phase.

**Comment by thaJeztah** [comment]
So; that's a "LGTM" ? 😇

**Comment by aaronlehmann** [comment]
@stevvooe @tonistiigi: What's the status of this one?

If there are no outstanding requests, seems like it would be nice to merge it and get rid of a package we can do without.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
I see thumbs ups, and desires to merge, so I am merging with 2 LGTMS and some 👍 .

**Comment by stevvooe** [comment]
Let me know if this causes problems.

**Pull request merged**
