### PR TITLE
Add apparmor

### PR DESCRIPTION
**Pull request by jessfraz**
Docker-DCO-1.1-Signed-off-by: Jessica Frazelle jess@docker.com (github: jfrazelle)

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @tianon this IS drone fix

**Comment by tianon** [comment]
Ugh.  AppArmor _again_.  FML.

LGTM, begrudgingly

**Comment by jfrazelle** [comment]
Seriously so hard to track down but the reason the daemon wasn't starting
was no file /sbin/apparmor_parser ughhhhh

**Comment by tianon** [comment]
IT'S GREEN!

**Comment by jfrazelle** [comment]
Lol we updated the image on drone before ;) thanks for the fast merge phew

**Pull request merged**
