### PR TITLE
unexport error errPruneRunning

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

This is PR tries to not export the error errPruneRunning, since I think it will not be used out of the package's scope.

And ping @gdevillele . This is a thought come from your PR. Thanks ☀️ 

**- What I did**
1. unexport error errPruneRunning

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by gdevillele — APPROVED** [review]
I was wondering if it would be useful to access this value from outside the package to test the error type.
Otherwise,
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

Was thinking the same as well, but if we need it, we can always export it again :smile:

**Review by cpuguy83 — APPROVED** [review]
LGTM

Generally it's a really bad time if you are trying to import the daemon package.

**Comment by gdevillele** [comment]
@cpuguy83 😅

**Pull request merged**
