### PR TITLE
Bump gometalinter to v2.0.6

### PR DESCRIPTION
**Pull request by thaJeztah**
Taken from https://github.com/moby/moby/pull/37358

Full diff: https://github.com/alecthomas/gometalinter/compare/bfcc1d6942136fd86eb6f1a6fb328de8398fbd80...v2.0.6

ping @kolyshkin @vdemeester

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
PowerPC failure  https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/10466/console is a flaky test https://github.com/moby/moby/issues/37408

```
15:30:39 FAIL: docker_api_swarm_service_test.go:311: DockerSwarmSuite.TestAPISwarmServicesFailedUpdate
15:30:39 
15:30:39 [d8780b649329d] waiting for daemon to start
15:30:39 [d8780b649329d] daemon started
15:30:39 
15:30:39 [d36085d55aad5] waiting for daemon to start
15:30:39 [d36085d55aad5] daemon started
15:30:39 
15:30:39 [d7c14d7b77c62] waiting for daemon to start
15:30:39 [d7c14d7b77c62] daemon started
15:30:39 
15:30:39 docker_api_swarm_service_test.go:347:
15:30:39     waitAndAssert(c, defaultReconciliationTimeout, daemons[0].CheckRunningTaskImages, checker.DeepEquals,
15:30:39         map[string]int{image1: instances})
15:30:39 docker_utils_test.go:435:
15:30:39     c.Assert(v, checker, args...)
15:30:39 ... obtained map[string]int = map[string]int{"busybox:latest":4}
15:30:39 ... expected map[string]int = map[string]int{"busybox:latest":5}
15:30:39 
15:30:39 [d8780b649329d] exiting daemon
15:30:39 [d36085d55aad5] exiting daemon
15:30:39 [d7c14d7b77c62] exiting daemon
```

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
Raising the gometalinter version actually didn't help with the issue we see in https://github.com/moby/moby/pull/37358, but it doesn't hurt either.

LGTM

**Comment by thaJeztah** [comment]
Yeah, I thought it was good to bump it; previous version was quite old by now

**Pull request merged**
