### PR TITLE
Add zsh completion for 'docker image build --cache-from'

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #26839

Signed-off-by: Steve Durrheimer <s.durrheimer@gmail.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by sdurrheimer** [comment]
@thaJeztah Is there a nightly build of docker for mac ? That would be practical.

**Comment by thaJeztah** [comment]
@sdurrheimer hm, not sure if there is one already @justincormack?

To run master, you can either build master, and run in a container, or use this script; https://github.com/docker/docker/pull/26565 to install a custom binary in docker for mac; that's purely for testing though, and in some cases may require a factory reset after switching / switching back

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
