### PR TITLE
daemon:containerStart() fix unhandled error for saveApparmorConfig

### PR DESCRIPTION
**Pull request by thaJeztah**
notice this error was unhandled

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]

**Comment by thaJeztah** [comment]
I'm confused; it looks like all tests completed within 2 hours, but somehow the tests were terminated
Screenshot 2019-08-29 at 23 55 55


Looking at the results;

```
Stage : Start - (34 sec in block)	DCO-check
Stage : Start - (2 hr 0 min in block)	Build
---------------------------------------------------------------------------
Stage : Start - (21 min in block)	unit-validate
Stage : Start - (53 min in block)	janky
Stage : Start - (17 min in block)	z
Stage : Start - (37 min in block)	powerpc
Stage : Start - (58 min in block)	windowsRS5-process
```

RS1 looks like the culprit; Run tests - (2 hr 51 min in block)

https://ci.docker.com/public/job/moby/job/PR-39828/1/flowGraphTable/


```
Branch: windowsRS1 - (1 ms in block)							Success
Stage : Start - (2 hr 51 min in block)							Success
windowsRS1 - (2 hr 51 min in block)							Success
Allocate node : Start - (2 hr 51 min in block)						Success
Allocate node : Body : Start - (2 hr 51 min in block)					Success
Allocate workspace : Start - (2 hr 51 min in block)					Success
Allocate workspace : Body : Start - (2 hr 51 min in block)				Success
Check out from version control - (33 sec in self)					Success
Set environment variables : Start - (2 hr 51 min in block)				Success
Set environment variables : Body : Start - (2 hr 51 min in block)			Success
Set environment variables : Start - (2 hr 51 min in block)				Success
Set environment variables : Body : Start - (2 hr 51 min in block)			Success
Stage : Start - (5.7 sec in block)					Print info	Success
Print info - (5.7 sec in block)								Success
Shell Script - (3 sec in self)								Success
Shell Script - (2.6 sec in self)							Success
Stage : Start - (2 hr 51 min in block)					Run tests	Success
Run tests - (2 hr 51 min in block)							Success
PowerShell Script - (1 hr 59 min in self)						Success
```

Looking at the output from that PowerShell script; https://ci.docker.com/public/job/moby/job/PR-39828/1/execution/node/196/log/?consoleFull

```
20:32:20  INFO: executeCI.ps1 starting at Thu Aug 29 18:32:19 CUT 2019
...
20:45:24  INFO: Running unit tests...
20:49:27  INFO: Unit tests ended at 08/29/2019 18:49:27. Duration:00:04:16.2050106
...
20:50:07  INFO: Running integration tests at 08/29/2019 18:50:07...
22:00:46  INFO: Integration tests ended at 08/29/2019 20:00:45. Duration:01:07:07.2316333
....
22:01:31  INFO: executeCI.ps1 exiting at Thu Aug 29 20:01:25 CUT 2019. Duration 01:29:05.7882024	
```

So, it seems as if the tests completed, but the PowerShell script didn't _terminate_, leading to Jenkins killing it after 2 hours (not sure where the `2 hr 51min` comes from; that's confusing as well, as that would mean it kept going passed the max time limit)

**Comment by thaJeztah** [comment]
^^ @StefanScherer @vikramhh any ideas?

**Comment by thaJeztah** [comment]
merging this, because everything passed

**Comment by StefanScherer** [comment]
@thaJeztah I'm investigating in TAR-1105

**Comment by thaJeztah** [comment]
Thanks @StefanScherer !

**Pull request merged**
