### PR TITLE
Add zsh completion for 'docker daemon --live-restore'

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #23213

@albers Thx for the ping
@vincentbernat

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by albers** [comment]
@sdurrheimer did you notice #23363?

**Comment by sdurrheimer** [comment]
Yep, but can't do it right now. It's on my TODO list.

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
