### PR TITLE
Vendoring libkv @v0.2.1

### PR DESCRIPTION
**Pull request by abronan**
Update `libkv` to `v0.2.1`.

Includes:
- **(bug fix)** zk: fix wrong error code check on List

Signed-off-by: Alexandre Beslic alexandre.beslic@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
@abronan @icecrime should this be in 1.12 ? 👼

**Comment by thaJeztah** [comment]
LGTM, sounds like it should be on the milestone, so I'll add it, but please let us know if it shouldn't be :smile:

**Comment by justincormack** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
