### PR TITLE
Seccomp initial support

### PR DESCRIPTION
**Pull request by keloyang**
Add user interface for seccomp.
As #17142 mentioned,we can start a container with seccomp surpout use the following command,

``` js
docker run --rm -ti --security-opt seccomp:path  ubuntu bash
```

if the path is't exist,it will create a template for seccomp config,and you can modify it for yourself.
seccomp config template,

``` js
{
    "defaultAction": "SCMP_ACT_ALLOW",
    "architectures": null,
    "syscalls": [
        {
            "name": "unshare",
            "action": "SCMP_ACT_ERRNO",
            "args": null
        },
        {
            "name": "setns",
            "action": "SCMP_ACT_ERRNO",
            "args": null
        },
        ...
    ]
}
```

Attention ,this pr use libseccomp, ensure your compile environment support.

Signed-off-by: keloyang yangshukui@huawei.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Can you split the vendoring into a separate commit?

**Comment by keloyang** [comment]
updated,thank you.

**Comment by jfrazelle** [comment]
see https://github.com/docker/docker/issues/17142, would love to get your opinion on that

**Comment by thaJeztah** [comment]
ping @jfrazelle should we close this while we're still working out / discussing https://github.com/docker/docker/issues/17142?

**Comment by jfrazelle** [comment]
I can carry and make this how we want phase 1






On Thu, Nov 12, 2015 at 3:00 AM -0800, "Sebastiaan van Stijn" <notifications@github.com> wrote:












ping @jfrazelle should we close this while we're still working out / discussing #17142?

**Comment by thaJeztah** [comment]
@jfrazelle sgtm. Are you okay with that @keloyang ?

**Comment by jfrazelle** [comment]
hello i have opened https://github.com/docker/docker/pull/17989 as a replacement, I am unsure if we want to generate a config and i used the open containers spec to parse the config, thank you so much for your time on this I would appreciate feedback on that one

**Pull request closed without merging**
