### PR TITLE
docs: update link to docs contribution guide

### PR DESCRIPTION
**Pull request by dvdksn**
**- What I did**

Updated the external link to the docs contribution guidelines at docs.docker.com (current link 404s)

**- How I did it**

Edit CONTRIBUTING.md

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
> current link 404s

Did we miss adding a redirect? (As that link used to work)

**Comment by dvdksn** [comment]
> Did we miss adding a redirect? (As that link used to work)

Yes, seems like it. I'm not sure but I think those pages were removed when we published the new contribution guide. Problem is, there seems to've been instructions for contributing to Docker OSS on those pages that we've now lost. I am not sure what the canonical location of such information should be, perhaps docs.docker.com, or perhaps the repo (docker/cli also links off to the dead links but there is no good replacement currently)

**Review by neersighted — CHANGES_REQUESTED** [review]
Hmm, this is actually not the right contributing guide -- this is a guide for contributing to docs.docker.com, not Moby. I think we're probably best off just dropping this image entirely.

**Comment by thaJeztah** [comment]
🤦 yes, you're right; we used to host our contributing guide there, but it was removed again from the docs, and moved back in this repository at https://github.com/moby/moby/tree/master/docs/contributing (definitely needs some TLC though, as it's quite outdated). We could link to that section though.

**Comment by neersighted** [comment]
The same mistake was made in #44744, and I did not catch it. That PR should not have been merged either.

@dvdksn thanks for the contribution -- however, because of no fault of yours (the docs are badly broken/ossified), I don't think this PR will ever be mergable without turning it into a revamp and resurrection of the (very old, gone for years) missing content (e.g. https://github.com/docker/docs/tree/7cfe2e9da240cd9d2dc475593af1a4840a518614/opensource).

I'm going to close this for now as I suspect you won't have the inclination to do all the work needed to make the broken links actually meaningful. If I'm wrong about, please feel free to reach out. I'm planning to take on some of this work myself, and would be happy to coordinate.

**Pull request closed without merging**
