### PR TITLE
Refactor Dockerfile.parser and directive

### PR DESCRIPTION
**Pull request by dnephin**
Don't expose parser.Directive outside of the parser package
Remove duplication in `parser.Parse()` and make it easier to support #29161

### CODE REVIEW

**Comment by dnephin** [comment]
@yongtang I think this will make #29161 cleaner. No need to pass in `stderr`, you can just return Warnings as part of `Result()` and handle them in the builder.

**Comment by yongtang** [comment]
Thanks @dnephin I am on the road but will try to take a look and update #29161 in the next several days. (my flight is with united airline 😢)

**Review by tonistiigi — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by jhowardmsft** [comment]
@dnephin Hmmm, just seen this. By having `processFirstLine` separate from `processLine`, it means adding additional parse directives is very problematic (which is what I'm currently trying to do in another PR).

What was the rationale for splitting the first line out and not just treating every line as "just another line".

**Comment by jhowardmsft** [comment]
Oh, I see. It's the BOM handling. I'll figure it out :)

**Comment by dnephin** [comment]
Ya, I was thinking about that case when I was making these changes, but didn't want to worry about it in case we never added another directive.

I think `d.processLine()` can be called in both cases, and the `Directive()` `d.processingComplete = true` can be set to true on the first non-directive line, instead of after the first line.

**Pull request merged**
