### PR TITLE
Skip evaluation of symlinks to data root on IoT Core

### PR DESCRIPTION
**Pull request by darstahl**
Signed-off-by: Darren Stahl <darst@microsoft.com>

**- What I did**

Due to the default configuration on IoT core and https://github.com/golang/go/issues/20506 the provided path to the root and tmp should not be expanded on IoT Core.

**- How I did it**

Skip evaluation of symlinks to data root on IoT Core

**- How to verify it**

Internal verification

/cc @jhowardmsft

### CODE REVIEW

**Comment by darrenstahlmsft** [comment]
This depends on https://github.com/moby/moby/pull/33414, will update once merged.

**Comment by darrenstahlmsft** [comment]
@jhowardmsft @johnstep PTAL

**Comment by jhowardmsft** [comment]
Yup, LGTM.

**Review by lowenna — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by darrenstahlmsft** [comment]
Experimental and z could use a rebuild :)

**Comment by jhowardmsft** [comment]
Jobs restarted

**Comment by darrenstahlmsft** [comment]
z passed but CI process crashed before it could report, and experimental failed with:
```
04:06:02 ----------------------------------------------------------------------
04:06:02 FAIL: docker_cli_stack_test.go:59: DockerSwarmSuite.TestStackDeployComposeFile
04:06:02 
04:06:02 [d6d8842241644] waiting for daemon to start
04:06:02 [d6d8842241644] daemon started
04:06:02 
04:06:02 docker_cli_stack_test.go:76:
04:06:02     c.Assert(err, checker.IsNil)
04:06:02 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420131b00), Stderr:[]uint8(nil)} ("exit status 1")
04:06:02 
04:06:02 [d6d8842241644] exiting daemon
04:06:04 
04:06:04 ----------------------------------------------------------------------
```

Which looks totally unrelated.

**Comment by darrenstahlmsft** [comment]
CI is 💚

**Pull request merged**
