### PR TITLE
Sorting make targets and DOCKER_ENV vars in alphabetical order

### PR DESCRIPTION
**Pull request by DieterReuter**
In order to get a better readability and for easier maintenance I just sorted both the make targets and the DOCKER_ENV variables in alphabetical order. One exception is the `default` make target which should be at top.
I just sorted the labels of the .PHONY line in alphabetical order as well.

No functional changes applied at all.

### CODE REVIEW

**Comment by runcom** [comment]
:heart_eyes: ping @jfrazelle @tianon

**Comment by DieterReuter** [comment]
Sorted the .PHONY line as well. ;-)

**Comment by DieterReuter** [comment]
Connects to #17802.

**Comment by thaJeztah** [comment]
Nice! LGTM

ping @tianon @jfrazelle PTAL

**Comment by calavera** [comment]
LGTM

**Pull request merged**
