### PR TITLE
Carry #25134: Remove join-tokens from the /info API

### PR DESCRIPTION
**Pull request by aaronlehmann**
join-tokens are not needed for this endpoint, and should not be as part of /info

per https://github.com/docker/docker/pull/24492#issuecomment-235006362

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Note that this is opened against bump_v1.12.0, so it MUST be cherry-picked to master. I was asked to do this, but I'm not sure who's responsible for taking care of this. In general, I think it's much better to be consistent about the workflow for getting PRs into releases. If changes can flow in both directions, it's very easy to make mistakes.

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by vdemeester** [comment]
LGTM 👼
/cc @tiborvass

**Comment by tiborvass** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
@aaronlehmann can you check the win2lin failure? it feels unrelated but legitly weird:
```
20:36:09 vendor\src\github.com\docker\distribution\registry\api\errcode\register.go:74: undefined: http.StatusTooManyRequests
```

**Pull request merged**
