### PR TITLE
extend mirror for supporting private registry

### PR DESCRIPTION
**Pull request by TrumanLing**
extend mirror for supporting private registry

Signed-off-by: Ling FaKe lingfake@huawei.com

### CODE REVIEW

**Comment by TrumanLing** [comment]
#18818

**Comment by hqhq** [comment]
There are compile errors in test files.

**Comment by TrumanLing** [comment]
The windows error looks like nothing with my PR.

**Comment by thaJeztah** [comment]
@TrumanLing looks like this needs a rebase; GitHub reports that there are merge conflicts

**Comment by thaJeztah** [comment]
I'd really like to have input of @dmp42 @stevvooe, @RichardScothern for "registry" and @tonistiigi for the engine side on this

**Comment by TrumanLing** [comment]
@thaJeztah thx for your reponse, and I will rebase it, and want to hear opinions form them(  @dmp42 @stevvooe, @RichardScothern and @tonistiigi ) as well.

**Comment by TrumanLing** [comment]
@thaJeztah I have rebased it, and make a new PR #19009, please refer. Any problem, free to contact me:))))

**Comment by thaJeztah** [comment]
I'll close this one then.

**Pull request closed without merging**
