### PR TITLE
Adding IPv6 NDP Proxying documentation

### PR DESCRIPTION
**Pull request by MalteJ**
I have written some documentation on how to use IPv6 when your Docker host does not have a whole IPv6 subnet assigned but is only part of a subnet (e.g. via router advertisements) using NDP proxying.

I just have tested this with an Ubuntu Droplet on Digital Ocean. It would be great if there would be a few people testing this on their local environment, too.

This method should allow users to run globally routed containerized IPv6 applications from within their home network.

### CODE REVIEW

**Comment by jfrazelle** [comment]
cool thanks @MalteJ!

**Comment by estesp** [comment]
Hey @MalteJ, I've been fighting with this a bit given I'm having trouble getting Linode's IPv6 setup to do what I think it should.  They give out /116's that you can ask for in addition to getting the "normal" IPv6 addr for the node--outbound IPv6 works great, but I'm not getting IMCP6 (neigh, echo or anything) on the node when I ping in to one of the /116 addresses.  It looks like DO's docs are very similar to Linode--they expect you to add additional addresses to your main (eth0) interface, and then they are "active", but I obviously want to assign those to the container (which is working fine via `--fixed-cidr-v6=`).  Any thoughts here on how you have it working in DO in case that helps me?  Linode support doesn't appear to know much about Docker; not that they need to, but they are just expecting that I put one of my /116 addresses on to eth0 and if that works, they are happy.

**Comment by MalteJ** [comment]
@estesp please check you have a route to your `fixed-cidr-v6` subnet configured. Docker will not set up the route if the bridge docker0 already exists.

**Comment by estesp** [comment]
Yes, route is working fine.  I can ping containers via IPv6 from the docker host (and vice verse--I can ping host via IPv6 from containers, however I cannot get roundtrip from container to external IPv6 a'la `ping6 www.google.com` - DNS AAAA resolution is fine, but ping response is not received)

**Comment by MalteJ** [comment]
I have tried this with Ubuntu 14.04 on Linode. When I start Docker and let it create a new bridge I loose the host's IPv6 default gateway:

    root@localhost:~# ip -6 route
    default via fe80::1 dev eth0  metric 1024
    2a01:7e00::2e:7000/125 dev docker0  metric 1024
    2a01:7e00::/64 dev eth0  proto kernel  metric 256  expires 2591785sec
    fe80::/64 dev eth0  proto kernel  metric 256
    fe80::/64 dev docker0  proto kernel  metric 256

    root@localhost:~# service docker start
    docker start/running, process 5267

    root@localhost:~# ip -6 route
    2a01:7e00::2e:7000/125 dev docker0  metric 1024
    2a01:7e00::/64 dev eth0  proto kernel  metric 256  expires 2591785sec
    fe80::/64 dev eth0  proto kernel  metric 256
    fe80::/64 dev docker0  proto kernel  metric 256

do you have the same problem?
then re-add the default gw:

    ip -6 route add default via fe80::1 dev eth0

**Comment by estesp** [comment]
yeah, I found the same problem and added back my default route.

**Comment by MalteJ** [comment]
so it does work for you, now? (I need some +1 for this PR :wink:)

**Comment by estesp** [comment]
I think your instructions are correct; I am still not working right on Linode but I think it has nothing to do with your instructions, but rather with some poor setup between my Ubuntu node <--> Linode IPv6 setup.  They have asked for more details or close the support case, so I may try one more time, but I don't think we need to hold up this PR as the instructions, I believe, are correct for proxying NDP.  **LGTM**

**Comment by thomasschaeferm** [comment]
I think 
"ifconfig eth0 down"
kills all the routes.

**Comment by MalteJ** [comment]
@thomasschaeferm yeah, I meant `ifconfig docker0 down`. Not eth0 :wink:

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
DO instance

**Comment by estesp** [comment]
I have this working now on my Linode.. my network stack was in a bad state apparently after doing too much playing around w/IPv6 :) Your directions work perfectly with the /116 range they provided me.

LGTM

**Comment by thomasschaeferm** [comment]
.... my network stack was in a bad state apparently after doing too much playing around w/IPv6 :)....

I can confirm this statement. Or in different words: repetition fails sometimes. 
I am not sure about the reason. (Networkmanager?, ...)

**Pull request merged**
