### PR TITLE
Use a docker-py version that includes latest integration test fixes

### PR DESCRIPTION
**Pull request by shin-**
Should help #11003 #11030 ! cc @tianon 

Signed-off-by: Joffrey F joffrey@docker.com

### CODE REVIEW

**Comment by estesp** [comment]
Chicken-and-egg.. you need #11003 applied to pass tests, and #11003 needs this PR to pass tests :)

**Comment by jfrazelle** [comment]
Can the one that this needs to pass pull this commit into their pr

**Comment by jfrazelle** [comment]
So #11003 should pull this commit in

**Comment by jfrazelle** [comment]
going to close this since it will be included in 11003, thanks so much @shin- for working on these fixes so quickly we seriously appreciate it

**Pull request closed without merging**
