### PR TITLE
Added the BINDCONTEXT dockerfile instruction

### LINKED ISSUE #3056: Proposal: Dockerfile add BIND_CONTEXT
Currently I have mostly-useless commands in my Dockerfile like
    ADD stuff /docker_setup
    RUN /docker_setup/install.sh && rm -rf /docker_setup

This is ugly.  Can we have:
    BIND_CONTEXT /docker_context
    RUN /docker_context/stuff/install.sh

I'm not picky about the syntax.  I want to have docker build do what docker run -v does, but during the build process.

### PR DESCRIPTION
**Pull request by a-ba**
closes #3056

The `BINDCONTEXT <mountpoint>` instruction arranges for the context to be mounted at the location `<mountpoint>` inside the container during the subsequent `RUN` commands.

The context is mounted in read-write mode. This is convenient when building something from sources located in the context since only files that are explicitly installed will persist in the image. Everything else (sources, intermediate files,...) is wiped out when the build is over.

The command is also useful when dealing with a voluminous files. Using BINDCONTEXT instead of ADD avoid making extra copies of temporary files and avoids keeping them in the final image. Depending on the case, this can mitigate #2224 and #332.

There are two outstanding questions:
1. the command mounts _directly_ the context directory and let the user modify it (and possibly mess up with next dockerfile commands). An alternatives would be to write changes in an aufs layer to leave the server context intact, but this adds a dependency on aufs (and I wondef if this is really necessary).
2. the <mountpoint> stays in the image after the build and is listed in the 'Volumes' section of the image config. Ideally I would prefer removing it from the config and from the filesystem (if it did not exist prior to the mount). I am not very familiay with the runtime API, is there a way to do that cleanly before the commit ?

### CODE REVIEW

**Comment by icecrime** [comment]
We're closing this one in favor of an ulterior docs PR: maintainers (@crosbymichael @unclejack @tiborvass) are against a new Dockerfile verb for this purpose, and are suggesting other possibilities (such as having the context *always* bind-mounted in the container as part of a build process).

**Comment by mkscrg** [comment]
@icecrime can you ref that PR? I'd like to keep following along on this issue

**Comment by tiborvass** [comment]
@mkscrg there is none afaict, but as soon as there is one, we'll add a reference to it on this one.

**Comment by tianon** [comment]
Always bind-mounting the context won't work.  Once the context is
bind-mounted, we _have_ to cache-bust at that point based on the entire
context, which means that if we bind-mount it by default, we're
cache-busted at line 1 every time any file in the entire context changes.

**Comment by crosbymichael** [comment]
@tianon good point

**Comment by tianon** [comment]
What if we essentially copied what `COPY` and `ADD` look like?

```Dockerfile
MOUNT-CONTEXT some-dir /somewhere-in-the-image
MOUNT-CONTEXT some/sub/directory /somewhere-else
MOUNT-CONTEXT . /ALL-THE-THINGS
```

**Comment by crosbymichael** [comment]
@tianon http://youtu.be/5NPBIwQyPWE?t=1m7s

**Comment by tianon** [comment]
@crosbymichael :heart:

**Comment by a-ba** [comment]
i am still maintaining the patch at https://github.com/a-ba/docker/tree/3056-bindcontext (up to date with 1.6.0) since we have no alternative for the moment

ADDTMP would be fine for us though it does not help in handling large files (but that part should rather be addressed by caching/CoW, eg. #9553)

**Comment by dagelf** [comment]
@a-ba 1) Is the idea for your "BINDCONTEXT" to be silently ignored if the local context is not available?
2) Is the idea to only have it available during build?
3) Would it be a big hassle to make it accept the path-in-host:path-in-image format?
4) Do you have any issues with calling it "BINDMOUNT" rather? Because isn't that in fact what it is doing? Context generally refers to metadata or something else, rather than a tree of the filesystem, whereas the word MOUNT is pretty clear in its purpose.

**Comment by a-ba** [comment]
> 1) Is the idea for your "BINDCONTEXT" to be silently ignored if the local context is not available?

There is always a context: at least it contains the Dockerfile. If there is only a Dockerfile, BINDCONTEXT would not be ignored however it would be mostly useless.

> 2) Is the idea to only have it available during build?

yes

> 3) Would it be a big hassle to make it accept the path-in-host:path-in-image format?

There are two problems with letting the user bind an arbitrary directory from the machine: security (it gives root access) and side-effects (we have no guarantee that the data will not be altered after they are fingerprinted and before they are used in the build)

`path-in-context:path-in-image` would be ok (for binding part of the context)

> 4) Do you have any issues with calling it "BINDMOUNT" rather? Because isn't that in fact what it is doing? Context generally refers to metadata or something else, rather than a tree of the filesystem, whereas the word MOUNT is pretty clear in its purpose. 

"Context generally refers to metadata or something else" but in the case of docker it refers to the archive we ship to the server for the build. It is used everywhere in the documentation.
http://docs.docker.com/reference/commandline/cli/#build

However I agree that the word CONTEXT should not be in the command name, but for an other reason: to make it consistent with the other commands that use the context : ADD and COPY

**Comment by a-ba** [comment]
Now I am thinking of another solution : why not just mount /tmp from a temporary external volume during the whole build ?

Thus, instead of writing: `BINDCONTEXT /context`  or `ADDTMP . /context`

we would just write : `ADD /context /tmp/context`

By convention everything in /tmp is discarded at the end of the build. It is easy to understand and it does not require to introduce a new keyword.

The only downside is that it breaks old Dockerfile where the user expects to have something remaining in /tmp/ in the final image (but is it a real concern?)

**Comment by thaJeztah** [comment]
@a-ba please see the roadmap; https://github.com/docker/docker/blob/master/ROADMAP.md

There's a feature freeze on the Dockerfile syntax, because we're in the process of moving the "builder" client-side, which will allow alternative implementations to the Dockerfile, and more flexibility.

**Comment by dagelf** [comment]
The /tmp use case would be useless if you're wanting to have a local apt or portage repository available (which you don't want in the image.) In the case of the apt respository - Ubuntu knows to fetch it from a certain path, or from the internet if that path is not available.

**Comment by briceburg** [comment]
The naming of a `MOUNTCONTEXT` directive proposed in https://github.com/moby/moby/issues/30110#issuecomment-272424395 speaks to me. This is useful -- especially for enmasse  copying from the context under particular ownership.

**Pull request closed without merging**
