### PR TITLE
Ensure that install the latest version of tini

### PR DESCRIPTION
**Pull request by lcnja**
### Ensure that install the latest version of tini
*    Get information of the  latest tini version from [here](https://api.github.com/repos/krallin/tini/releases/latest)
*    Get the latest version automatically
*    Discard update tini manually

### CODE REVIEW

**Comment by lcnja** [comment]
@GordonTheTurtle  


Verified now

image

**Comment by thaJeztah** [comment]
Thanks for contributing; I'm don't think we should to this though; we pin dependencies to a specific version (or commit) to make builds reproducible, and to make sure that we don't pull in different versions (possibly containing regressions, or unwanted changes).

Is there a specific reason you want to make this change?

**Comment by lcnja** [comment]
@thaJeztah 

oh, got it, thanks for the reply

**Comment by thaJeztah** [comment]
You're welcome!

**Pull request closed without merging**
