### PR TITLE
vendor: update fifo to 14056439

### LINKED ISSUE #27760: Short lived containers stdin close err
On master, when running a short-lived container, the daemon gets errors in the logs about not being able to close the stdin fifo.

For builds I frequently see:

```
ERRO[0026] error closing stdin: %+vfifo /proc/self/fd/20 was closed before opening
```

For `docker run` I see:

```
WARN[0010] failed to close stdin: %!v(MISSING)
```

I'm not sure why I'd get different errors here, may just be race conditions.

Ping @tonistiigi

### PR DESCRIPTION
**Pull request by tonistiigi**
- fixes #27760
- improves logging

https://github.com/tonistiigi/fifo/compare/b4c3a126bac4051ae3fa83bfcb3c60ab7a9da0dd...1405643975692217d6720f8b54aeee1bf2cd5cf4

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
windows hanged up,  but perhaps not related (also seen in https://github.com/docker/docker/pull/28132#issuecomment-259028023)
```
..
01:17:58.321 SKIP: docker_cli_ps_test.go:666: DockerSuite.TestPsImageIDAfterUpdate (Test requires a Linux daemon)
01:17:58.512 SKIP: docker_cli_ps_test.go:528: DockerSuite.TestPsLinkedWithNoTrunc (Test requires a Linux daemon)
01:18:31.455 PASS: docker_cli_ps_test.go:20: DockerSuite.TestPsListContainersBase	30.620s
01:19:17.960 PASS: docker_cli_ps_test.go:309: DockerSuite.TestPsListContainersFilterAncestorImage	46.111s
01:19:18.538 PASS: docker_cli_ps_test.go:568: DockerSuite.TestPsListContainersFilterCreated	0.315s
01:20:04.312 PASS: docker_cli_ps_test.go:449: DockerSuite.TestPsListContainersFilterExited	44.174s
03:20:41.833 Build timed out (after 200 minutes). Marking the build as failed.
```

anyway restarting CI

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by AkihiroSuda** [comment]
cc @cpuguy83

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
