### PR TITLE
skip TestAuthApi if no network is available

### PR DESCRIPTION
**Pull request by thaJeztah**
addresses https://github.com/docker/docker/pull/22254#discussion_r60947097

only run this integration test if we have networking, to allow running the tests off-line if needed

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @aaronlehmann :smile:

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by aaronlehmann** [comment]
LGTM

**Comment by LK4D4** [comment]
@thaJeztah really bad example of commit message :)

**Comment by thaJeztah** [comment]
@LK4D4 oh, come-on! haha suggestions?

**Comment by thaJeztah** [comment]
@LK4D4 better?

**Comment by LK4D4** [comment]
@thaJeztah yup, lgtm

**Pull request merged**
