### PR TITLE
Refactor ipvlan network integration tests to use network package

### PR DESCRIPTION
**Pull request by adshmh**
**- What I did**
refactored ipvlan network integration tests to use network.Create from `integration/internal/network` package.

**- How I did it**
Modified integration tests under `integration/network/ipvlan`

**- How to verify it**

**- Description for the changelog**
ipvlan network Integration tests now use network package 

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
@adshmh looks like this needs a rebase 😢

**Comment by adshmh** [comment]
Thank you, rebased.

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
