### PR TITLE
Move setHostConfig to daemon file

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by hqhq** [comment]
May I ask why doing this? What's the benefit?

**Comment by icecrime** [comment]
As `setHostConfig` is used in both `start.go` and `create.go`: LGTM.

**Comment by hqhq** [comment]
I see, thanks.

**Comment by duglin** [comment]
LGTM

**Pull request merged**
