### PR TITLE
Revert "Make daemon to start with no userlandproxy by default"

### PR DESCRIPTION
**Pull request by jessfraz**
:cry:

### CODE REVIEW

**Comment by jfrazelle** [comment]
this fixes ci

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
:tada:

**Comment by phemmer** [comment]
I'm curious, what prompted this?

**Comment by jfrazelle** [comment]
we couldnt run 2 tests in parallel without triggering a buch of `unregister_netdevice` :(

**Comment by jfrazelle** [comment]
on a stock 3.19 kernel, which if we cant run our ci, then other people would probably have the same issues on such kernels

**Comment by jfrazelle** [comment]
pretty disappointed, but if you can think of anything to avoid it... we would be greatful

**Comment by phemmer** [comment]
can you point me to a failed build which exhibited the issue? might take a look if I get time.

**Comment by jfrazelle** [comment]
well it woiuld just freeze randomly, so there itsnt great output the key thing was the bajillion `unregister_netdevice` in dmesg, then you would have to reboot the server

**Comment by mrjana** [comment]
@jfrazelle I believe disabling `userlandproxy` made container stop much more quicker creating more chance for a race and it started becoming more common in CI. But I think the underlying problem with `unregister_netdevice` is still present in 3.19 kernel. 

But I do agree that reverting the userlandproxy commit is the best decision for CI ATM

**Comment by LK4D4** [comment]
@mrjana btw I think it's okay for me on 4.2, apart from that ports not forwarded :D I can't reproduce unregister_netdevice even with super highflow of containers starting-dying.

**Comment by mrjana** [comment]
@LK4D4 yeah probably the issue got fixed in 4.2. we should bisect and see which patch fixed the issue.

**Pull request merged**
