### PR TITLE
fix bash error in release.sh

### PR DESCRIPTION
**Pull request by vieux**
ping @tianon @andrewhsu

### CODE REVIEW

**Comment by tianon** [comment]
Do you know what the error was?  I'd personally consider what we have in there now to be the more correct of these (the single `[` version), since we're just using `-eq` which doesn't require `[[`. :confused:

**Comment by vieux** [comment]
@tianon a syntax error "undefined [" when `$SKIP_RELEASE_BUILD` was undefined

**Comment by tianon** [comment]
Oh odd -- you should get that with `[[` too.  I think the easiest fix is probably to swap `-eq` for `=`
(`[ "$SKIP_RELEASE_BUILD" = '1' ]`)

**Comment by thaJeztah** [comment]
Do we need it to be `1` exactly, or is `if [ -n "$SKIP_RELEASE_BUILD" ];` enough?

**Comment by vieux** [comment]
@tianon WDYT ? ^^

**Comment by tianon** [comment]
That sounds great to me, although in that case, setting it to '0' would be
considered true (only the empty string would be false), so it depends on
how you want to use it.

**Comment by thaJeztah** [comment]
ping @vieux 😇

**Comment by tianon** [comment]
I spoke some more with @vieux about this, and the conclusion is that if it's set to 1 we skip the tests, if it's undefined, =0 or =2 we don't, so I'm going to update to use `=` instead of `-eq` in just a minute. :+1:

**Comment by vieux** [comment]
LGTM :D

**Review by thaJeztah — APPROVED** [review]
who am I to disagree? :heart:

LGTM

**Comment by tianon** [comment]
image

**Comment by thaJeztah** [comment]
Sweet 💤

**Comment by thaJeztah** [comment]
CI doesn't run this, so

Keep your head up, movin' on

**Pull request merged**
