### PR TITLE
[RFC]Remove intermediate container for 'ENV' command

### PR DESCRIPTION
**Pull request by arm64b**
We can remove the intermediate container for 'ENV' command since we don't need to run something inside a container for this.

Signed-off-by: Dennis Chen <dennis.chen@arm.com>

### CODE REVIEW

**Comment by arm64b** [comment]
I am thinking... 😄

**Comment by thaJeztah** [comment]
```
10:41:21 --- FAIL: TestEnv2Variables (0.00s)
10:41:21 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
10:41:21 	panic: runtime error: invalid memory address or nil pointer dereference
10:41:21 [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaea2fc]
10:41:21 
10:41:21 goroutine 14 [running]:
10:41:21 testing.tRunner.func1(0xc420458690)
10:41:21 	/usr/local/go/src/testing/testing.go:742 +0x29d
10:41:21 panic(0xbc92e0, 0x1326ef0)
10:41:21 	/usr/local/go/src/runtime/panic.go:502 +0x229
10:41:21 github.com/docker/docker/builder/dockerfile.(*imageProber).Probe(0xc42045e240, 0x0, 0x0, 0xc420347540, 0x4114d8, 0x30, 0xc182c0, 0xc420065c01)
10:41:21 	/go/src/github.com/docker/docker/builder/dockerfile/imageprobe.go:44 +0x5c
10:41:21 github.com/docker/docker/builder/dockerfile.(*Builder).probeCache(0xc420420b40, 0xc420445340, 0xc420347540, 0x1, 0xc420347540, 0x17)
10:41:21 	/go/src/github.com/docker/docker/builder/dockerfile/internals.go:400 +0x75
10:41:21 github.com/docker/docker/builder/dockerfile.dispatchEnv(0xc420445340, 0xc420422b28, 0xc420420b40, 0x0, 0x0, 0xc42045e280, 0xc420440580, 0x0, 0x0)
10:41:21 	/go/src/github.com/docker/docker/builder/dockerfile/dispatchers.go:62 +0x5ed
10:41:21 github.com/docker/docker/builder/dockerfile.dispatch(0xc420445340, 0xc420422b28, 0xc420420b40, 0x0, 0x0, 0xc42045e280, 0xd4c3c0, 0xc420440580, 0x0, 0x0)
10:41:21 	/go/src/github.com/docker/docker/builder/dockerfile/evaluator.go:69 +0xaac
10:41:21 github.com/docker/docker/builder/dockerfile.TestEnv2Variables(0xc420458690)
10:41:21 	/go/src/github.com/docker/docker/builder/dockerfile/dispatchers_test.go:51 +0x228
10:41:21 testing.tRunner(0xc420458690, 0xcf9e18)
10:41:21 	/usr/local/go/src/testing/testing.go:777 +0xd0
10:41:21 created by testing.(*T).Run
10:41:21 	/usr/local/go/src/testing/testing.go:824 +0x2e0
10:41:21 FAIL	github.com/docker/docker/builder/dockerfile	0.016s
```

**Comment by arm64b** [comment]
Below commands support commit an image (by design?)

```
var validCommitCommands = map[string]bool{
	"cmd":         true,
	"entrypoint":  true,
	"healthcheck": true,
	"env":         true,
	"expose":      true,
	"label":       true,
	"onbuild":     true,
	"user":        true,
	"volume":      true,
	"workdir":     true,
}
```

Will check other commands not in this map if it can support add image layer only instead of intermediate container.

**Comment by thaJeztah** [comment]
@arm64b I'd have to check, but are those the options that can be set when doing `docker commit --change ....` ?

**Pull request closed without merging**
