### PR TITLE
Clean some integration-cli/fixtures package/files

### PR DESCRIPTION
**Pull request by vdemeester**
- Move go package used by both `integration-cli` and `integration` to
  `internal/test/fixtures`.
- Remove fixtures that are not used anymore (moved to `docker/cli` a
  while ago) : deploy, notary, secrets. (relates to https://github.com/moby/moby/pull/36515, https://github.com/docker/cli/pull/924)

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by thaJeztah** [comment]
```
15:33:06 ----------------------------------------------------------------------
15:33:06 FAIL: check_test.go:407: DockerPluginSuite.SetUpSuite
15:33:06 
15:33:06 check_test.go:415:
15:33:06     c.Assert(err, checker.IsNil, check.Commentf("failed to create plugin"))
15:33:06 ... value *errors.withStack = error building basic plugin bin: can't load package: package ./fixtures/plugin/basic: cannot find package "./fixtures/plugin/basic" in:
15:33:06 	/go/src/github.com/docker/docker/integration-cli/fixtures/plugin/basic
15:33:06 : exit status 1 ("error building basic plugin bin: can't load package: package ./fixtures/plugin/basic: cannot find package \"./fixtures/plugin/basic\" in:\n\t/go/src/github.com/docker/docker/integration-cli/fixtures/plugin/basic\n: exit status 1")
15:33:06 ... failed to create plugin
15:33:06 
```

**Comment by cpuguy83** [comment]
Yeah, I was afraid of that.

**Comment by vdemeester** [comment]
@cpuguy83 yeah I forgot to change something :sweat_smile: Fixing it :wink:

**Comment by vdemeester** [comment]
@cpuguy83 @thaJeztah should be fixed :wink:

**Review by thaJeztah — APPROVED** [review]
LGTM, but needs a minor rebase

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
