### PR TITLE
Cherry-pick #25191 to master

### PR DESCRIPTION
**Pull request by mavenugo**
Cherry-picked from https://github.com/docker/docker/pull/25191

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM. I hit this yesterday on a Windows CI run.

**Comment by jhowardmsft** [comment]
@tiborvass OK to merge into master?

**Comment by tiborvass** [comment]
@jhowardmsft it's up to @mavenugo whether he wants to actually change this pr to be a `git cherry-pick -x` of the other PR. I'm fine either way as long as they are linked in the description.

**Comment by tiborvass** [comment]
Actually no i'm not fine, I want them to be linked in git commit as well. @mavenugo can you please do `git cherry-pick -x` of your other PR and update the description to reference it ?

**Comment by mavenugo** [comment]
@tiborvass done

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
