### PR TITLE
CI: Display error details on Windows unit and integration tests and clean Go cache before build

### PR DESCRIPTION
**Pull request by olljanat**
**- What I did**
Display error details on Windows unit and integration tests like discussed on https://github.com/moby/moby/pull/39226#issuecomment-493459632

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like we get some warnings from `go vet` now (haven't googled yet what would cause those); https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/2446/console

```
16:59:41 go : # fmt
16:59:41 At line:1 char:1
16:59:41 + go test "-check.v" "-tags" "autogen" "-check.timeout" "10m" "-test.ti ...
16:59:41 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:59:41     + CategoryInfo          : NotSpecified: (# fmt:String) [], RemoteException
16:59:41     + FullyQualifiedErrorId : NativeCommandError
16:59:41  
16:59:41 vet.exe: in fmt, can't import facts for package "strconv": open 
16:59:41 \localappdata\go-build\e3\e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d: The system cannot find 
16:59:41 the path specified.
16:59:41 # context
16:59:41 vet.exe: in context, can't import facts for package "errors": open 
16:59:41 \localappdata\go-build\e3\e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d: The system cannot find 
16:59:41 the path specified.
16:59:41 # archive/tar
```

Unfortunately the last error still doesn't provide info _what_ failed; it looks like that's printed if the last exit status was != 0, but I don't see (at a glance) why https://github.com/moby/moby/blob/1d62807db3bcbb3d793a5bb396d17aa62a59537c/hack/ci/windows.ps1#L837-L841

**Comment by olljanat** [comment]
Hmm. Those vet errors looks like that there is some cheap on build server cache. Maybe we should also include `go clean -cache` to be run end of the builds?

**Comment by olljanat** [comment]
Looks that RS1 actually prints more details: https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25217/console

```
23:31:40 INFO: DOCKER_HOST at tcp://127.0.0.1:2357
23:31:41 # runtime/cgo
23:31:41 exec: "gcc": executable file not found in %PATH%
```

Also noticed that busybox is actually rebuild on every CI run.
```
23:31:40 REPOSITORY                    TAG                 IMAGE ID            CREATED                  SIZE
23:31:40 busybox                       latest              b1d00093f848        Less than a second ago   7.17GB
```

**Comment by olljanat** [comment]
Hmm. Now RS1 was stuck on state doing nothing until it times out: `
23:54:23 INFO: Commit hash is 67c0a5a8e9
23:54:23 INFO: Nuke-Everything...
23:54:23 INFO: Container count on control daemon to delete is 0
03:44:20 Build timed out (after 230 minutes). Marking the build as failed.
03:44:20 Set build name.
03:44:20 New build name is '#39232'
03:44:20 Build was aborted
`

**Comment by olljanat** [comment]
Derek add label: rebuild/windowsRS1

**Comment by olljanat** [comment]
powerpc and z failures are unrelated as this only touches Windows CI build script.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

**Comment by olljanat** [comment]
Hmm. I included these to #39240 and noticed that those vet errors gets printed only on RS1 and not on RS5 and they still are there even with `go clean -cache`.

Something is very wrong on those Windows CI servers...

**Comment by thaJeztah** [comment]
^^ ping @jhowardmsft PTAL

**Comment by olljanat** [comment]
Blah. I looks to be that Go uses variable `TMP` to set temporary folder and currently `windows.ps1` sets only `TEMP` variable.

Will test to update it on #39240

**Comment by olljanat** [comment]
Found it. `$env:LOCALAPPDATA` value is incorrectly just `\localappdata` instead of correct path. Fixed on #39259

Will close this one.

**Pull request closed without merging**
