### PR TITLE
Remove File List

### PR DESCRIPTION
**Pull request by jbruni**
This list is outdated. It could be updated instead of removed... but why should it be maintained? I do not see a reason.

Signed-off-by: João Bruni contato@jbruni.com.br

### CODE REVIEW

**Comment by jbruni** [comment]
:-) I'm trying to find my way into contributing... I've read "everything should be a pull request"... But I do not know where to create pull request regarding docker.com website...

@fredlf, @jamtur01, @SvenDowideit : at "Why do sysadmins like it?" section at https://www.docker.com/whatisdocker/ it says:

```
Sysadmins use Docker to provide standardized environments for their development, QA,
and production teams, reducing “works on my machine” finger-pointing.
```

Shouldn't it be 'reducing "**doesn't work** on my machine" finger-pointing' ?

Thank you.

**Comment by jamtur01** [comment]
No. The comment refers to the classic: "worked in dev, Ops problem now" concept.

**Comment by jbruni** [comment]
@jamtur01 - Oh! Now I see. I expect you also understood the alternative perspective/interpretation raised.

**Comment by jfrazelle** [comment]
LGTM

**Comment by fredlf** [comment]
I can see some value to having a file list. E.g., it might help people figure out which files they need to revise. I can also see that manually maintaining it is a PITA. I imagine it would not be hard to automate the generation of the list, but I don't have the skills to do that myself.

Thoughts, @SvenDowideit @jamtur01 ?

**Comment by jamtur01** [comment]
Automation +1 or remove.

**Comment by SvenDowideit** [comment]
+1 to remove. its pretty unusual to add a static file list to a checked in README file - and it doesn't really add to the findability, given that its hidden in the same directory.

LGTM :)

@fredlf @jamtur01

**Comment by fredlf** [comment]
Well, there might be some value to just being able to easily scan the list, but I doubt that value, if present, is worth the trouble it would take to realize it. So LGTM, I guess

**Pull request merged**
