### PR TITLE
Add --ignore flag to 'docker rm' so missing container doesn't return error

### PR DESCRIPTION
**Pull request by duglin**
This will allow for an idempotent 'docker rm' command similar to what
"rm -f" can do.

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
itsnt this the same as doinng docker rm thing 2&>/dev/null

**Comment by duglin** [comment]
close but that will still give you a non-zero exit code.
You'd need to do: `docker run things >/dev/null 2>&1 || echo` or something. Kind of a hack.

**Comment by calavera** [comment]
What if we don't show any output when code is `NotFound`? that would also give us an idempotent command, wouldn't it?

**Comment by duglin** [comment]
its not just about seeing an error, its also the exit code.  But I don't think we should change the current behavior (showing error msg and non-zero exit code) w/o some new flag.

**Comment by albers** [comment]
I think `--ignore` isn't self-explaining. `--ignore-non-existent` would be better.

**Comment by calavera** [comment]
I personally think that adding a flag to modify the exit status is not a very good idea, regardless how self-explanatory is. I'd rather consider returning `1` for containers that don't exist a bug in docker's cli that we should fix.

**Comment by duglin** [comment]
Changing the default behavior is an option but I'm not sure its the right one given it would break backwards compat.  Looking the normal 'rm' cmd line, it returns non-zero if the file isn't there, but adding '-f' changes it to zero - so from that perspective this PR would be consistent with what I think people probably expect.

To be honest, what I think is odd is that it echos the container ID/name to the screen.  That's just weird to me  :-)  but that's a different issue.

As for the flag name, `--ignore` might be too terse, but `--ignore-not-existent` is a kind of long.  Would be nice if we could think of something better...  maybe `--ignore-missing`?  dunno

**Comment by calavera** [comment]
But we already have a `-f` flag too. If we want to be consistent with `rm -f` why don't we make `docker rm -f` consistent without adding another flag?

**Comment by duglin** [comment]
I would love to use '-f' but it already means something else (kill container if running).  Overloading that with "ok if not there" feels awkward.  If everyone else want to head that way I can be convinced, it just didn't feel right at first to me.

**Comment by albers** [comment]
`--ignore-missing` sounds better to me. I don't think option length is much of an issue because we have command completion.

Doug Davis <notifications@github.com> hat geschrieben:

Changing the default behavior is an option but I'm not sure its the right one given it would break backwards compat.  Looking the normal 'rm' cmd line, it returns non-zero if the file isn't there, but adding '-f' changes it to zero - so from that perspective this PR would be consistent with what I think people probably expect.

To be honest, what I think is odd is that it echos the container ID/name to the screen. That's just weird to me :-) but that's a different issue.

As for the flag name, --ignore might be too terse, but --ignore-not-existent is a kind of long. Would be nice if we could think of something better... maybe --ignore-missing? dunno

**Comment by calavera** [comment]
> so from that perspective this PR would be consistent with what I think people probably expect.

`rm -f` can never be consistent with `docker rm -f --ignore-missing` because it uses an extra flag, the input is already inconsistent. If we're thinking about what people might expect, I bet people expect to not need an extra flag.

> I would love to use '-f' but it already means something else

`-f` is the short for `--force`, we define what `--force` means. This is the description if `-f` in the `rm` manual:

```
-f, --force
              ignore nonexistent files and arguments, never prompt
```

It means two things, ignore nonexistent files, and never prompt. In the same way `-f` can mean two things for Docker.

If we want to be consistent `docker rm -f` must mean the same as `rm -f`. Adding an extra flag doesn't make Docker consistent with rm. Making `docker rm -f` behave in the same way `rm -f` behaves, makes docker consistent with rm.

**Comment by duglin** [comment]
to be clear, by consistent with rm I didn't mean char-for-char - I meant that by default you get non-zero exit code when the file isn't there, but you can tell it to ignore it via a flag.  That's it.

**Comment by jfrazelle** [comment]
I dont think this needs a new flag i thinnk it can be handlded with -f and pipes

**Comment by duglin** [comment]
@jfrazelle how does -f help ?

**Comment by jfrazelle** [comment]
I'm saying --ignore can be done w bash and pipes, you can choose to do rm
or rm -f then pipe it to whatever you want

**Comment by duglin** [comment]
But w/o some kind of flag to say "ignore missing containers" you can't easily tell if a non-zero return code is due to a 404 or something else.

**Pull request closed without merging**
