### PR TITLE
Make official install instructions use curl instead of wget

### LINKED ISSUE #14650: Linux installation: cannot verify get.docker.com's certificate
The recommanded installation procedure on Linux with `wget` is failing:
```
wget -qO- https://get.docker.com/ | sh
```
returns no error (exit 0) but nothing happen either.

Trying a simple `wget https://get.docker.com` reveals an SSL certificate verification issue:
```
--2015-07-15 10:44:50--  https://get.docker.com/
Resolving get.docker.com (get.docker.com)... 52.0.250.56, 52.6.66.251, 54.210.203.88
Connecting to get.docker.com (get.docker.com)|52.0.250.56|:443... connected.
ERROR: cannot verify get.docker.com's certificate, issued by `/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3':
  Unable to locally verify the issuer's authority.
To connect to get.docker.com insecurely, use `--no-check-certificate'.
```

So, unfortunately, passing the `--no-check-certificate` option to grab the script is the only way to go at the moment.

### PR DESCRIPTION
**Pull request by ankushagarwal**
YOU GO CURL

Fixes #14650

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Reviewers :
Docs : @moxiegirl @thaJeztah 
Infra maintainers : @jfrazelle @crosbymichael

**Comment by thaJeztah** [comment]
LGTM I like curl because I can remember the `-sSL` :-)

**Comment by ankushagarwal** [comment]
Me too :)

**Comment by jfrazelle** [comment]
LGTM hahaha love the title

**Comment by vdemeester** [comment]
Shouldn't we add a little "If you don't have ``curl`` and/or have/like ``wget``, the equivalent is ``wget -qO-``" ?
But other than that, yeah ``curl -sSL`` is easier to remember :blush: so :+1:

**Comment by LK4D4** [comment]
but wget is cooler!

**Comment by thaJeztah** [comment]
Right-click the URL in your webbrowser and choose "save linked file as..."  😜

**Comment by moxiegirl** [comment]
LGTM thanks @ankushagarwal

**Comment by moxiegirl** [comment]
@calavera cherry pick?

**Comment by calavera** [comment]
cherry picked into #15091

**Comment by tianon** [comment]
Next person to crack at this ought to add `-f` to all those `curl` invocations. :innocent:

**Pull request merged**
