### PR TITLE
Change seccomp blacklist to a whitelist

### PR DESCRIPTION
**Pull request by jessfraz**
Running various tests on official images, but opening the discussion. ping @justincormack

### CODE REVIEW

**Comment by phemmer** [comment]
I was wondering why we weren't using a whitelist instead. The whitelist makes more sense to me for one main reason: default action is secure (http://stackoverflow.com/a/504424/486035).
With a blacklist, even if we blacklisted every possible syscall that could be abused, new kernels can come out which introduce new syscalls, and if docker's blacklist is old, it won't protect them.

:+1:

**Comment by jfrazelle** [comment]
does this mean you will compile seccomp into your binary now 0:)

**Comment by cpuguy83** [comment]
SGTM

**Comment by thaJeztah** [comment]
Using a white list sounds like a better approach to me, so +1

Tentatively moving this to code review

**Comment by justincormack** [comment]
The `clone` rule needs fixing, will send patch.

I am slightly inclined to add back in the comments from the blacklisted syscalls as documentation of the ones not in the whitelist, not sure what anyone thinks.

**Comment by justincormack** [comment]
Ok I have tested this extensively: tested that individual syscalls are being correctly filtered, used it as my default docker install and built stuff (eg docker/docker, Linux kernel compile), double checked the syscall list for 32 bits, arm, powerpc. So LGTM.

For reference easiest way to check individual syscalls being filtered is:
```
docker run -it --cap-add ALL justincormack/ljsyscall -e "print(require('syscall').acct('/tmp/t'))"
nil	Operation not permitted
docker run -it --cap-add ALL justincormack/ljsyscall -e "print(require('syscall').clone('newuts,newpid'))"
nil	Operation not permitted
docker run -it --cap-add ALL --security-opt seccomp:unconfined justincormack/ljsyscall -e "print(require('syscall').acct('/tmp/t'))"
nil	No such file or directory
docker run -it --cap-add ALL --security-opt seccomp:unconfined justincormack/ljsyscall -e "print(require('syscall').clone())"
11
0
```

**Comment by jfrazelle** [comment]
Thanks I can add those as integration tests :) and I'm working on all new docs with the old comments as well

**Comment by jfrazelle** [comment]
opened additional tests here: https://github.com/docker/docker/pull/19002 and docs will come soon in another PR

**Comment by cpuguy83** [comment]
Looks like you have `settimeofday` in the whitelist, shouldn't that be blocked?

**Comment by jfrazelle** [comment]
Good catch thanks

**Comment by cpuguy83** [comment]
LGTM

**Comment by justincormack** [comment]
Looking good after more testing. There is one issue that running compatible architectures is currently blocked (eg 32 bit x86 on x86_64). There is an easier fix or a nicer one, will look at it tomorrow, but need not stop merging.

**Comment by calavera** [comment]
I wonder if we can make this file easy to read/scan by putting all those signal names together. Something like:

```go
var names = []string{"accept" ,"accept4"...}
var defaultSeccompProfile = &configs.Seccomp{
	DefaultAction: configs.Errno,
}

func init() {
  var syscalls []*configs.Syscall
  for _, name := range names {
  }
}
```

**Comment by calavera** [comment]
sorry, wrong button :smile:

**Comment by calavera** [comment]
That file looks quite long but whatever. LGTM

**Comment by jfrazelle** [comment]
we could use go generate? I was thinking about that in the beginning

**Comment by justincormack** [comment]
Unfortunately Linux has too many syscalls, and it matches the libcontainer spec format, well the Go is a bit more readable. It is not ideal, but not sure there is much that can be done.

**Comment by jfrazelle** [comment]
no i want it to be good :(

**Comment by jfrazelle** [comment]
FWIW it will be easier to see the diff once its merged ;)

**Comment by thaJeztah** [comment]
will merging make all red Janky's go green? :innocent:

**Comment by jfrazelle** [comment]
i think it was becausse llvm repo was screwed up

**Comment by jfrazelle** [comment]
green \o/

**Review by Gajuanlaw9 — APPROVED** [review]

**Pull request merged**
