### PR TITLE
Add install step to start docker daemon

### PR DESCRIPTION
**Pull request by gabesullice**
https://github.com/docker/docker/issues/12427

### CODE REVIEW

**Comment by phemmer** [comment]
It's convention in debian based distributions for services to start automatically upon package installation. Thus manual start should not be necessary.

**Comment by moxiegirl** [comment]
@gabesullice I tested the installation when I rewrote this page. A daemon start wasn't required as per @phemmer .  Are you finding that is when you test? What are the steps you are following? I'd like to duplicate it.

**Comment by gabesullice** [comment]
Yeah, I'm going to retest this again tonight too, but I did have to start
the docker daemon by hand when I filed the issue. Additional context: I was
installing on Ubuntu 13.10.

**Comment by moxiegirl** [comment]
@gabesullice I believe ya had to start by hand. Thanks for doing the further testing.  I'm gonna test on my end.  That's a pretty popular page but 13.10 not sure how that stacks up so you may have run into something.  I retested on 13.10. Here is my transcript.

https://gist.github.com/moxiegirl/9fb8f0f846afca92ed3f

**Comment by moxiegirl** [comment]
Closing as @gabesullice's testing proved this unable to dup.

**Pull request closed without merging**
