### PR TITLE
Update vendored distribution repo to new version

### LINKED ISSUE #14975: Registry Client response code acceptance is too narrow
Details are in docker/distribution#748 but we need to fix this for 1.8. We'll need to fix this in distribution then update the vendored version.

History repeating itself: #10402.

### PR DESCRIPTION
**Pull request by aaronlehmann**
This version includes a fix that avoids checking against specific HTTP
status codes. The previous behavior violated the registry API spec.

Fixes #14975

Signed-off-by: Aaron Lehmann aaron.lehmann@docker.com

### CODE REVIEW

**Comment by dmp42** [comment]
cc @docker/distribution-maintainers

**Comment by calavera** [comment]
> The previous behavior violated the registry API spec.

This sounds reasonable to add to 1.8 but it looks like we're also adding some new logic in that `Clear` function. Is that necessary for the release?

**Comment by aaronlehmann** [comment]
As far as I know, it's not necessary. It's there because I'm updating distribution to the latest master. It would be possible to branch from the earlier revision and apply only the HTTP status code change, if that's something we want to consider.

**Comment by dmcgowan** [comment]
It is not necessary, the client does not currently call `Delete` so the new logic should not be on any other call path.

**Comment by aaronlehmann** [comment]
Does anyone know why the tests are failing? I see failures like the following which don't have an obvious connection to updating the dependency:

    FAIL: docker_cli_run_test.go:1325: DockerSuite.TestRunCopyVolumeUidGid
    
    docker_cli_run_test.go:1341:
       c.Fatalf("Wrong /hello ownership: %s, expected dockerio:dockerio", out)
    ... Error: Wrong /hello ownership: 2015/07/25 04:16:19 error generating version 4 uuid, retrying: open /dev/urandom: operation not permitted
    dockerio:dockerio, expected dockerio:dockerio

**Comment by dmcgowan** [comment]
This error occurs when the UUID library is unable to get enough random bits due to  entropy exhaustion `open /dev/urandom: operation not permitted`

**Comment by dmp42** [comment]
@calavera IIRC this is a code path that the engine does not use (for the registry soft-delete feature), but I'll let @RichardScothern & @aaronlehmann confirm that this indeed has no effect.

**Comment by icecrime** [comment]
Our CI is gone fishing. Otherwise LGTM!

**Comment by icecrime** [comment]
Waiting from green tests.

**Comment by jfrazelle** [comment]
failed on /dev/urandom... le sighhhh, but merging

**Pull request merged**
