### PR TITLE
new feature: `docker -H ssh://host`

### LINKED ISSUE #31871: [Proposal] docker -H ssh://me@host/var/run/docker.sock
I suggest adding support for forwarding the API socket over SSH: `docker -H ssh://me@host/var/run/docker.sock`. (or in short form: `docker -H ssh://host`)

i.e. it is a user-friendly equivalent of the following script:
```sh
#!/bin/sh
tmp=$(mktemp -d)
chmod 700 $tmp
ssh -N -L $tmp/docker.sock:/var/run/docker.sock &
sshpid=$!
docker -H unix://$tmp/docker.sock $@
status=$?
kill $sshpid
rm -rf $tmp
exit $status
```

Motivations:

* No mess of setting up TLS properly (`ssh-keygen` vs a bunch of [`openssl blah -blah -blah -blah ...`](https://docs.docker.com/engine/security/https/#create-a-ca-server-and-client-keys-with-openssl), #6817)
* Single user account management for both regular SSH session and Docker session
* Single login monitoring for both

cc @diogomonica

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Implemented `docker -H ssh://host`, which allows connecting to a Unix socket listening on a remote daemon via an OpenSSH connection.

```
[docker] ----- TCP -----> [sshd] -- Unix --> [dockerd]
```

Closes https://github.com/docker/docker/issues/31871

Motivations:

- No mess of setting up TLS properly (`ssh-keygen` vs a bunch of [openssl blah -blah -blah -blah ...](https://docs.docker.com/engine/security/https/#create-a-ca-server-and-client-keys-with-openssl), #6817)
- Single user account management for both regular SSH session and Docker session
- Single login monitoring for both

Currently supported auth methods:

 - SSH Agent (on Unix)
 - pageant (on Windows, **UNTESTED**)
 - Private key file, e.g. `~/.ssh/id_rsa`

The feature is purely implemented on the client side.
No need to configure the daemon.

**- How I did it**

By doing an equivalent of `ssh -L local.sock:/var/run/docker.sock` using `golang.org/x/crypto/ssh`, rather than `os/exec`-ing `ssh` binary.

Technically, this is known as the OpenSSH "streamlocal" extension.
https://github.com/openssh/openssh-portable/blob/461f50e7ab8751d3a55e9158c44c13031db7ba1d/PROTOCOL#L235-L285

**- How to verify it**

* No need to configure the daemon. Even no need to replace the daemon built from this PR.  I confirmed this PR works well with vanilla 17.03.0-ce daemon.

* You just need to create a SSH user account that satisfies:
  * Accessible to `/var/run/docker.sock`
  * Configured to use publickey/privatekey authentication (If you set passphrase to keys, you need to set up `ssh-agent`)

* Run the docker client with `-H ssh://[user@]host[:port][socketpath]` . (or set `DOCKER_HOST` to `ssh://...`)

e.g.
```
$ docker -H ssh://host run ...
```

```
$ DOCKER_HOST=ssh://host docker run ...
```

```
$ docker -H ssh://me@host run ...
```

```
$ docker -H ssh://me@host:22/var/run/docker.sock run...
```

**- Description for the changelog**
Now docker client can connect to a Unix socket listening on a remote daemon via an OpenSSH connection

**- A picture of a cute animal (not mandatory but encouraged)**

penguins

TODO

- [ ] Make decision on whether we should support insecure HTTP over TCP over SSH (for Windows) https://github.com/docker/docker/pull/32161#issuecomment-289977681
- [X] Support pageant on Windows
- [ ] Test on Windows
- [X] Vendor `golang.org/x/crypto`: https://go-review.googlesource.com/#/c/38614/ when merged
- [ ] Vendor docker/go-connections#36
- Support reading ~/.ssh/config and /etc/ssh/ssh_config (another PR in future, probably by executing `ssh` instead of calling `golang.org/x/crypto`)

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like CI is failing, @AkihiroSuda 

On Windows;

```
08:27:04 # github.com/docker/docker/opts
08:27:04 ..\..\opts\hosts.go:86: undefined: idtools.LookupUID
08:27:04 ..\..\opts\hosts.go:187: u.Port undefined (type *url.URL has no field or method Port)
08:27:04 ..\..\opts\hosts.go:188: u.Hostname undefined (type *url.URL has no field or method Hostname)
08:27:05 # github.com/docker/docker/vendor/github.com/docker/go-connections/sockets
08:27:05 ..\..\vendor\github.com\docker\go-connections\sockets\sockets_windows.go:36: undefined: syscall in syscall.EAFNOSUPPORT
```

**Comment by justincormack** [comment]
Is there a way of specifying a different remote socket location? Sorry, on
phone not looked at details yet. Generally like the idea.

**Comment by AkihiroSuda** [comment]
@thJeztah Seems I was depending on Go 1.8 `net/url` :sweat_smile: , I'll update later

@justincormack  yes, e.g. `ssh://host/var/run/foo.sock`

**Comment by friism** [comment]
Could the remote endpoint also be a TCP port, in addition to a Unix socket? Otherwise this won't work on Windows, because [SSH-forwarding to a named pipe is not a thing afaik](https://github.com/PowerShell/Win32-OpenSSH/issues/435).

The way I typically use Windows instances with Docker and sshd is that I firewall all ports except 22, run dockerd on port 2375 and then tunnel to port 2375 over SSH from the outside. This PR would work great for that.

**Comment by nathanleclaire** [comment]
This is really cool @AkihiroSuda !

Something that caught my eye:

> Private key file, e.g. `~/.ssh/id_rsa`

Is this accurate? The PR strikes me as being more likely for public key auth with default key. How do you specify the private key path?

If the `~/.ssh/config` was supported, one might be able to `docker -H instance run ...`. That'd be pretty cool :)

**Comment by AkihiroSuda** [comment]
@friism

> Could the remote endpoint also be a TCP port, in addition to a Unix socket?

I fear people can accidentaly expose the insecure 2375/tcp port to the Internet when they try to enable 2375.

So my suggestion is to propose implementing NPFS to OpenSSH upstream, if it is feasible.
(After https://github.com/openssh/openssh-portable/pull/63 gets merged)

WDYT?

@nathanleclaire

>> Private key file, e.g. ~/.ssh/id_rsa
> Is this accurate? The PR strikes me as being more likely for public key auth with default key.

I think accurate.
Since private key file contains public key data as well, `x/crypto/ssh` provides `PublicKeys` auth as follows:

```go
signer, _ := ssh.ParsePrivateKey("/home/me/.ssh/id_rsa")
config := &ssh.ClientConfig{
    Auth: []ssh.AuthMethod{
        ssh.PublicKeys(signer),
    },
}
```
https://godoc.org/golang.org/x/crypto/ssh#PublicKeys

> How do you specify the private key path?

Please refer to `vendor/github.com/docker/go-connections/sshutils/auth.go`.
Following files under `~/.ssh` are used: id_rsa, id_ed25519, id_ecdsa, id_dsa, identity.

You can also use SSH agent (`ssh-add`) to set arbitrary key path.

> If the ~/.ssh/config was supported, one might be able to docker -H instance run .... That'd be pretty cool :)

I'll try to implement `~/.ssh/config` parser, but could you please elaborate what do you mean by `docker -H instance`?

**Comment by nathanleclaire** [comment]
> I'll try to implement ~/.ssh/config parser

For what it's worth, it's just a feature request, so don't feel obligated :) the full config file is probably pretty big in scope

> but could you please elaborate what do you mean by docker -H instance?

So, if you have a stanza in `~/.ssh/config` like follows:

```
Host dev
    Host akihirosuda.com
    Port 2222
    User akihiro
    IdentityFile ~/.ssh/ec2.pem
```

Then instead of typing:

```
$ ssh -p 2222 -i ~/.ssh/ec2.pem akihiro@akihirosuda.com
```

to get in you can type only:

```
$ ssh dev
```

So I had idea that maybe `docker -H ssh://dev ps` might similarly.

**Comment by AkihiroSuda** [comment]
added an integration test.
not sure why failing. locally passes... :sob: 
```
00:59:27.511 ----------------------------------------------------------------------
00:59:27.511 FAIL: docker_cli_ssh_unix_test.go:20: DockerDaemonSuite.TestSSHClientWithSSHAgent
00:59:27.511 
00:59:27.511 [d1b2eb66bad2d] waiting for daemon to start
00:59:27.511 [d1b2eb66bad2d] daemon started
00:59:27.511 
00:59:27.511 docker_cli_ssh_unix_test.go:48:
00:59:27.511     c.Assert(result, icmd.Matches, x.Expected)
00:59:27.512 ... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc4204c0160), ExitCode:1, Error:(*exec.ExitError)(0xc421ac3360), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc4201ae360), errBuffer:(*cmd.lockedBuffer)(0xc4201ae3f0)} ("\nCommand:  /go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker -H ssh://localhost:60022/tmp/test-ssh-client636095177/docker.sock run --rm busybox echo hello ssh\nExitCode: 1\nError:    exit status 1\nStdout:   \nStderr:   ssh: handshake failed: read tcp 127.0.0.1:54463->127.0.0.1:60022: read: connection reset by peer\n\n")
00:59:27.512 ... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"hello ssh", Err:""}
00:59:27.513 ... 
00:59:27.513 Command:  /go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker -H ssh://localhost:60022/tmp/test-ssh-client636095177/docker.sock run --rm busybox echo hello ssh
00:59:27.513 ExitCode: 1
00:59:27.513 Error:    exit status 1
00:59:27.513 Stdout:   
00:59:27.513 Stderr:   ssh: handshake failed: read tcp 127.0.0.1:54463->127.0.0.1:60022: read: connection reset by peer
00:59:27.513 
00:59:27.513 
00:59:27.513 Failures:
00:59:27.513 ExitCode was 1 expected 0
00:59:27.513 Expected stdout to contain "hello ssh"
00:59:27.513 Expected no error
00:59:27.513 
00:59:27.513 
00:59:27.513 [d1b2eb66bad2d] exiting daemon
00:59:28.894 
00:59:28.894 ----------------------------------------------------------------------
```

**Comment by tonistiigi** [comment]
So why not shell out to `ssh` instead. This is how rsync, scp, systemd etc do it. One of the benefits is that I don't think this supports the configuration from my `.ssh/config`. Is it really important to support this for users who don't even have ssh in their system.

**Comment by friism** [comment]
> I fear people can accidentaly expose the insecure 2375/tcp port to the Internet when they try to enable 2375.

Yup, that's a relevant concern. I understand it if you don't want to support TCP for that reason, I'm just saying that it can be used safely and it would make this PR work on Windows.

> Is it really important to support this for users who don't even have ssh in their system.

I think that's a nice property. SSH is not commonly found on Windows systems.

**Comment by jhowardmsft** [comment]
FYI - https://github.com/PowerShell/Win32-OpenSSH

**Comment by friism** [comment]
@jhowardmsft unfortunately it doesn't support tunnelling named pipes yet: https://github.com/PowerShell/Win32-OpenSSH/issues/435

**Comment by arianitu** [comment]
This is awesome, after looking at how to talk to the docker server remotely in a secure manner, it really doesn't make any sense. How am I suppose to ever revoke a client certificate if the docker server doesn't support certificate revocation lists (CRLs)? 

What's the point having all this key infrastructure if you can't even revoke a client? Essentially, if one of your clients leaves your organization, or you decide to fire that person, or simply don't want an individual access to your docker server anymore, you probably want to revoke their certificate before giving them the news (as an example.)

I was thinking, the docker server should just use ssh, if you need to force a client to leave your organization, you can just remove their public key (this PR is even nicer, it's only a client side change that talks to the docker server via SSH)

Do you think this will be merged anytime soon, or what do the Docker maintainers feel about this? Do you guys plan on adding CRLs to the server, or merging this in? Perhaps both is fine, where you use TLS for more complicated management of a docker server, while SSH is used for a small group of people to manage a docker server.

Can the Docker maintainers sort of give us perspective of what the original goal of using TLS was, why was TLS picked over SSH which seems pretty nice as a method of securely talking to a docker server.

**Comment by AkihiroSuda** [comment]
Updated PR

- PR for `golang.org/x/crypto` merged as https://github.com/golang/crypto/commit/3cddcd6758340b7620ed7f7895422317fab91e45
- Still need to vendor https://github.com/docker/go-connections/pull/36

@tonistiigi As @friism said, I think we need to keep go implementation for Windows, but I think it is good to support "exec" style driver in future PR. e.g. `DOCKER_HOST=ssh://foo docker --ssh-opt driver=exec`

**Comment by tonistiigi** [comment]
If we really expect Windows users to not want to install ssh but want to use ssh to connect to Docker we could ship `docker-ssh-client` binary on Windows together with Docker. How would these users even generate their private keys?

There is no reason for unix users to expect that regular SSH features do not work as they are supported by other similar applications. This PR already contains lots of copied `ssh(1)` features like loading keys from `$HOME/.ssh` and `SSH_AUTH_SOCK` env. There is a comment that hints adding whole `.ssh/config` parsing in the future, why would we want to maintain this? As a potential user I couldn't use this as I use `opensc-pkcs11` for everything and `ProxyCommand` regularily.

**Comment by AkihiroSuda** [comment]
Ok, for Unix I'll switch to os/exec

For Windows, I'm not sure what exe needs to be shipped with Docker.
( MSYS ssh + https://github.com/cuviper/ssh-pageant ? )

**Comment by friism** [comment]
@tonistiigi yeah, I think you're right - it's a reasonable assumption that someone wanting to use this will have ssh installed on the system.

**Comment by AkihiroSuda** [comment]
Also, I fear Windows implementation for os/exec would need to listen insecure HTTP locally, unless ssh.exe supports NPFS

**Comment by friism** [comment]
@AkihiroSuda maybe I'm missing something, but I was just thinking about connecting from the client running on Windows to a daeomon running behind sshd on Linux.

**Comment by rca** [comment]
I have not used windows in a while, but in old times I used plink.exe to leverage all the goodness of putty, puttygen, and pageant for a command line tool that needed an ssh tunnel into another server. 

http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

http://the.earth.li/~sgtatham/putty/0.52/htmldoc/Chapter7.html

**Comment by AkihiroSuda** [comment]
@friism 
Windows client ssh.exe needs to listen for docker.exe:

```
(Windows) [ [docker.exe] -- TCP, ideally NPFS --> [ssh.exe] ]---------- TCP ----------> [ [sshd] -- Unix --> [dockerd] ] (Linux)

```

**Comment by stevvooe** [comment]
@AkihiroSuda Does this support equivalent of `ssh -i` to select the key?

**Comment by AkihiroSuda** [comment]
@stevvooe 

Yes, via ssh-agent on Unix and pageant on Windows,

At least, for Unix, I'll remove built-in SSH client and move to just invoke `ssh` via `os/exec` (after DockerCon probably).
I think we can still use `ssh-agent` for `os/exec`.

**Comment by stevvooe** [comment]
> At least, for Unix, I'll remove built-in SSH client and move to just invoke ssh via os/exec (after DockerCon probably).

This is the easiest way to keep the expected functionality, including honoring the configuration. In a perfect world, it would be desirable to avoid, since this means we'd have two client implementations to gain windows support. Perhaps, we could autodetect the presence of the ssh installation and use one or the other depending on that result.

**Comment by AkihiroSuda** [comment]
opened https://github.com/moby/moby/pull/33566.
The new PR uses `os/exec` on Unix, and  should even work with ~/.ssh/config.

**Comment by thaJeztah** [comment]
Nice!

**Comment by frakman1** [comment]
@AkihiroSuda Nice feature. It works well when I have IP access to the remote docker server. However, if I am on a different network it hangs forever causing lockup issues in my scripts that use this feature.
Is there a way to pass along the usual ssh options? Something like:
`ssh -o ConnectTimeout=5 -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -o LogLevel=ERROR username@host'

**Comment by AkihiroSuda** [comment]
~/.ssh/config

**Pull request closed without merging**
