### PR TITLE
Add Aristotle to list of names

### PR DESCRIPTION
**Pull request by gwendolynne**
**- What I did**
Added Aristotle (one of the world's greatest scientific minds) to names-generator.

**- How I did it**
Inserted entry for Aristotle, in alphabetical order, that mimicked the format of other entries.

**- How to verify it**
Scroll to Maria Ardinghelli and look below.

**- Description for the changelog**

Added Aristotle to the list of names. 

**- A picture of a cute animal (not mandatory but encouraged)**
Bunny, the 10-year old, one-eyed Goldfish: 
bunny__20150509_112943__200x200

### CODE REVIEW

**Review by boaz0 — COMMENTED** [review]
SGTM minus the `dco/no` issue

**Comment by AkihiroSuda** [comment]
Please add a female as well?
https://github.com/moby/moby/pull/30006#issuecomment-271388619

**Comment by LK4D4** [comment]
@gwendolynne would you mind signing your commit? Thanks!

**Comment by AkihiroSuda** [comment]
ping @gwendolynne

**Comment by AkihiroSuda** [comment]
pingping @gwendolynne

**Comment by thaJeztah** [comment]
let's close for now

**Pull request closed without merging**
