### PR TITLE
[20.10 backport] fix local context

### PR DESCRIPTION
**Pull request by rumpl**
* backport of https://github.com/moby/moby/pull/44091

### CODE REVIEW

**Review by thaJeztah — DISMISSED** [review]
LGTM

**Comment by thaJeztah** [comment]
Looks like build is failing;


```

[2022-09-07T13:31:27.892Z] # github.com/docker/docker/daemon
[2022-09-07T13:31:27.892Z] daemon/content.go:33:54: undefined: ns
[2022-09-07T13:31:27.892Z] daemon/daemon.go:1130:47: too many arguments in call to d.configureLocalContentStore
[2022-09-07T13:31:27.892Z] 	have (string)
[2022-09-07T13:31:27.892Z] 	want ()
[2022-09-07T13:31:27.892Z] # github.com/docker/docker/daemon
[2022-09-07T13:31:27.892Z] daemon/content.go:33:54: undefined: ns
[2022-09-07T13:31:27.892Z] daemon/daemon.go:1130:47: too many arguments in call to d.configureLocalContentStore
[2022-09-07T13:31:27.892Z] 	have (string)
[2022-09-07T13:31:27.892Z] 	want ()
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@corhere @cpuguy83 PTAL

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
