### PR TITLE
Add openat2 and faccessat2 to default seccomp profile.

### PR DESCRIPTION
**Pull request by tao12345666333**
follow up to https://github.com/moby/moby/pull/41344#discussion_r469919978

Note: `openat2()`  first appeared in Linux 5.6. And Glibc does not provide a wrapper for this system call; call it using
       `syscall(2)`.

ref: https://man7.org/linux/man-pages/man2/openat2.2.html

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Oh, you need to edit or re-generate the JSON variant of the profile as well;

```

[2020-08-14T07:09:16.081Z] The result of go generate ./profiles/seccomp/ differs
[2020-08-14T07:09:16.081Z] 
[2020-08-14T07:09:16.081Z]  M profiles/seccomp/default.json
[2020-08-14T07:09:16.081Z] 
[2020-08-14T07:09:16.081Z] Please re-run go generate ./profiles/seccomp/
```

After this is merged, could you also open a pull request in containerd to update the profile to match? https://github.com/containerd/containerd/tree/master/contrib/seccomp

**Comment by thaJeztah** [comment]
I wonder if libseccomp needs an update for this; I see only a single occurence of `openat2` https://github.com/seccomp/libseccomp/search?q=openat2&unscoped_q=openat2

but many occurrences of `openat` https://github.com/seccomp/libseccomp/search?q=openat&unscoped_q=openat

**Comment by tao12345666333** [comment]
Thanks, let me take a look.

**Comment by tao12345666333** [comment]
> I wonder if libseccomp needs an update for this; I see only a single occurence of `openat2` https://github.com/seccomp/libseccomp/search?q=openat2&unscoped_q=openat2

@thaJeztah it seems like libseccomp has been updated (release/2.4)  https://github.com/seccomp/libseccomp/commit/b3206ad5645dceda89538ea8acc984078ab697ab

**Comment by tao12345666333** [comment]
> After this is merged, could you also open a pull request in containerd to update the profile to match?

Opened PR  https://github.com/containerd/containerd/pull/4481

**Comment by thaJeztah** [comment]
>  it seems like libseccomp has been updated (release/2.4) seccomp/libseccomp@b3206ad

Ah; yes, I see they switched to a different approach for "master" and the 2.5 branch, and now use a csv;  https://github.com/seccomp/libseccomp/commit/f5b3166d6126f4a45b59d6af6780b5e00a0e9867

Master (and 2.5 branch) already had the `openat2` syscall (in the above commit) and later updated to kernel 5.8.x in https://github.com/seccomp/libseccomp/commit/5696c896409c1feb37eb502df33cf36efb2e8e01#diff-afab4e57b1c976404582fcde2763f6b6L236

**Comment by thaJeztah** [comment]
Looking at that last link; should we add `faccessat2` as well? I see that was newly added, and l see `faccessat` is in our current profile?

**Comment by tao12345666333** [comment]
Yes, I missed it. 
Thanks. Let me add it.

**Review by AkihiroSuda — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by justincormack — APPROVED** [review]

**Comment by thaJeztah** [comment]
Hmmm

> All nodes of label ‘ppc64le-ubuntu-1604’ are offline

**Comment by thaJeztah** [comment]
Ignoring the ppc64le stage, which is unrelated

**Pull request merged**
