### PR TITLE
add missing API changes

### LINKED ISSUE #31123: API version confusion between 1.13.1 and 1.14
It appears some code was written with the assumption that API version 1.26 corresponds to Docker 1.14. When 1.13.1 was released, it took over that version number, and 1.14 is now supposed to be 1.27. We need to check the code and make sure 1.14-specific features and changes aren't gated on API version 1.26.

Grepping, here are a few spots that may be affected:

```
api/server/router/container/container_routes.go:                // In case version is higher than 1.26,
 a binary frame will be sent.
api/server/router/container/container_routes.go:                if versions.GreaterThanOrEqualTo(versio
n, "1.26") {
```

```
api/server/router/network/network_routes.go:            // Versions < 1.26 fetches all the containers a
ttached to a network
api/server/router/network/network_routes.go:            // run across all the networks. Starting API ve
rsion 1.26, this detailed
api/server/router/network/network_routes.go:            if versions.LessThan(httputils.VersionFromConte
xt(ctx), "1.26") {
```

cc @thaJeztah @vdemeester

### PR DESCRIPTION
**Pull request by vieux**
fix #31123

/cc @vdemeester @thaJeztah

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
@thaJeztah I added one more change, instead of duplication the API version, I imported the api `pkg`

/cc @vdemeester @dnephin please tell me if it's a problem.

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by dnephin — APPROVED** [review]
LGTM

**Pull request merged**
