### PR TITLE
Fixes Issue #11836 by adding explicit mentions of "API version" in error message

### LINKED ISSUE #11836: Misleading error message when client and server API version mismatch
For instance:    
    erwan@laptop:~/Projects/docker/machine$ script/build
    FATA[0000] Error: client and server don't have same version (client : 1.18, server: 1.17)
    erwan@laptop:~/Projects/docker/machine$ docker --version
    Docker version 1.5.0-dev, build 6a43d71

This message is a bit misleading. The missing keyword here seems to be "API version" :)

### PR DESCRIPTION
**Pull request by lobatt**
Signed-off-by: chli chli@freewheel.tv

Closes #11836

### CODE REVIEW

**Comment by rrarunan** [comment]
@lobatt Can you please add a `closes` or `fixes` keyword so its easy for tracking the fix? Thanks!

**Comment by crosbymichael** [comment]
LGTM

Thanks @lobatt !

**Comment by lobatt** [comment]
Thanks @crosbymichael for the review!

@rrarunan I am sorry, but by adding closes or fixes keyword do you mean in the request title?
Title changed now, let me know if I need to do anything else.

**Comment by lobatt** [comment]
Thanks @rogaha , I think i figured it out :)

**Pull request merged**
