### PR TITLE
remove docker-unconfined profile we were not using it

### PR DESCRIPTION
**Pull request by jessfraz**
it breaks otherwise on wheezy

ping @ewindisch :(

### CODE REVIEW

**Comment by crosbymichael** [comment]
+1

**Comment by crosbymichael** [comment]
LGTM

**Comment by ewindisch** [comment]
LGTM -- We could just remove 'ptrace' and 'signal' and it would work, but no harm in removing it for now I guess.

**Comment by calavera** [comment]
cheery picked into #15091

**Pull request merged**
