### PR TITLE
Include swarmkik dek rotation fixes in re-vendor

### PR DESCRIPTION
**Pull request by cyli**
This includes the fix from https://github.com/docker/swarmkit/pull/1766.

Thanks @LK4D4 for updating the swarmkit `bump_v1.13.0` branch!

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
@cyli separate PR coming for master branch?

**Comment by thaJeztah** [comment]
All green, merging

**Comment by cyli** [comment]
@thaJeztah I included the vendor as part of https://github.com/docker/docker/pull/28566, but I can split it out if that would be easier to cherry-pick?

**Comment by thaJeztah** [comment]
@cyli the other part of that PR needs to be cherry-picked into the release branch? Perhaps best to discuss with @vieux what's easiest. Given that it's two separate commits, perhaps it's not needed to split into two PR's but I'll leave that to him :smile:

**Comment by cyli** [comment]
Well, it's just tests, so not critical, but they caught the edge case bug that caused the need to revendor, so could be useful to have there :)

**Pull request merged**
