### PR TITLE
daemon: Remove daemon datastructure dump functionality

### PR DESCRIPTION
**Pull request by aaronlehmann**
When sending SIGUSR1 to the daemon, it can crash because of a concurrent map access panic, showing a stack trace involving dumpDaemon. It appears it's not possible to recover from a concurrent map access panic (see https://gist.github.com/aaronlehmann/281681d458e30e1d9b4637952f22793a for a demonstration). Since it's important that SIGUSR1 not be a destructive operation, sadly the best course of action I can think of is to remove this functionality.

cc @jhowardmsft @cpuguy83

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Huh. That really sucks as I've found this invaluable. LGTM 😢

**Review by thaJeztah — APPROVED** [review]
LGTM (unfortunately)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tianshuang** [comment]
@aaronlehmann I need to do a datastructure dump of dockerd, is there another way now?

**Pull request merged**
