### PR TITLE
update intro to say there are four things to consider

### PR DESCRIPTION
**Pull request by friism**
This is a simple docs update

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by icecrime** [comment]
@thaJeztah @SvenDowideit What's up with docs CI?

**Comment by SvenDowideit** [comment]
nice :) I was about to make a PR that said "several" - looking into CI

**Comment by SvenDowideit** [comment]
ah, this time its the old hugo dir creation race condition :(

**Comment by sanscontext** [comment]
Protip: s/specific number/several. ;)

**Comment by SvenDowideit** [comment]
currently in #25581

**Pull request merged**
