### PR TITLE
Make first letter of error message lowercase 

### PR DESCRIPTION
**Pull request by mqliang**
Capitalize first letter of Err message to keep consistancy

Signed-off-by: mqliang mqliang.zju@gmail.com

### CODE REVIEW

**Comment by phemmer** [comment]
They should be going the other way, to lowercase. https://github.com/golang/go/wiki/CodeReviewComments#error-strings

**Comment by calavera** [comment]
I agree with @phemmer. We want lowercase :smile_cat:

**Comment by mqliang** [comment]
@phemmer @calavera Ok, I have reworked my PR and repushed, thanks.

**Comment by stevvooe** [comment]
Closing this.

**Pull request closed without merging**
