### PR TITLE
add check flag for CONFIG_NETFILTER_XT_MATCH_IPVS CONFIG_IP_VS_NFCT C…

### PR DESCRIPTION
**Pull request by alexchenfeng**
add CONFIG_NETFILTER_XT_MATCH_IPVS , CONFIG_IP_VS_NFCT , CONFIG_IP_VS_RR kernel config check  in contrib/check-config.sh.

Signed-off-by: alexchen alexchenunix@gmail.com

Replaces https://github.com/docker/docker/pull/26940

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @mrjana @mavenugo @justincormack PTAL

also let me know if you want this to be added to 1.12.2; afaict there's no risk involved, so I'm fine with adding it if it makes it easier for you to debug issues

**Comment by mrjana** [comment]
@thaJeztah Yes, let's add it into 1.12.2. LGTM

**Review by mrjana — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
