### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by WeiZhang555**
Fix wrong descriptions in docs

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by WeiZhang555** [comment]
ping @thaJeztah @moxiegirl

**Comment by thaJeztah** [comment]
Ha! How did that happen? Possibly a merge gone wrong?

LGTM

**Comment by thaJeztah** [comment]
ping @vdemeester :-)

**Comment by vdemeester** [comment]
oohhh boy :sweat: 
LGTM 🐮

@thaJeztah should we put it in 1.10.2 if there is any ? (as it is in man pages)

**Comment by thaJeztah** [comment]
@vdemeester yes, let's add it (was confused for a moment, thinking it was docs).

**Pull request merged**
