### PR TITLE
To break the loop when found in search_test.go

### PR DESCRIPTION
**Pull request by lixiaobing1**
To break the loop when found in search_test.go

### CODE REVIEW

**Comment by lixiaobing10051267** [comment]
have put an issue: #24980

**Comment by lixiaobing10051267** [comment]
problem has bee fixed :)

**Comment by thaJeztah** [comment]
LGTM

**Comment by lixiaobing10051267** [comment]
@thaJeztah are there some problems about this pr?

**Comment by thaJeztah** [comment]
No, all looks good, it just needs another review when someone has time

**Comment by LK4D4** [comment]
LGTM
@lixiaobing10051267 thanks!

**Pull request merged**
