### PR TITLE
Not protect dangling images for integration-cli

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @duglin @cpuguy83 @tianon

**Comment by cpuguy83** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Comment by LK4D4** [comment]
@cpuguy83 You can change to `NOT LGTM`, then happy users of plugin will see that PR can't be merged

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Waiting on janky.

**Comment by LK4D4** [comment]
Okay, seems like Brian already out of work. Merging myself :P

**Pull request merged**
