### PR TITLE
Make Environment replacement note less kludgy

### LINKED ISSUE #14734: Documentation: Environment replacement needs improvement
Found a few problems with this section:
https://docs.docker.com/reference/builder/#environment-replacement

> Note: prior to 1.3, Dockerfile environment variables were handled similarly, in that they would be replaced as described below. However, there was no formal definition on as to which instructions handled environment replacement at the time. After 1.3 this behavior will be preserved and canonical.

>... there was no formal definition on as to which instructions handled environment replacement at the time
1. This sentence doesn't make sense.

Dockerfile environment variables were handled similarly
2. Similarly to what? Perhaps the note block should be moved after the explanation of Environment variable.

Perhaps someone could review the Environment variable section and reorganize the material presented.

### PR DESCRIPTION
**Pull request by ankushagarwal**
Fixes #14734

Signed-off-by: Ankush Agarwal ankushagarwal11@gmail.com

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Ping @thaJeztah @moxiegirl @erikh for review

**Comment by thaJeztah** [comment]
Hm, reading this, I'm actually wondering if we still need this note at all. Basically, all it says is "since version 1.3 we added documentation"

/cc @moxiegirl wdyt? ^^

Looking at PR https://github.com/docker/docker/pull/14735, I think that PR was meant to resolve https://github.com/docker/docker/issues/14734 (but it wasn't linked)?

**Comment by erikh** [comment]
Either way works for me, fwiw. It’s probably not a huge issue to remove it, since 1.3 is so far behind us.



On August 7, 2015 at 2:06:35 PM, Sebastiaan van Stijn (notifications@github.com) wrote:

Hm, reading this, I'm actually wondering if we still need this note at all. Basically, all it says is "since version 1.3 we added documentation"

/cc @moxiegirl wdyt? ^^

Looking at PR #14735, I think that PR was meant to resolve #14734 (but it wasn't linked)?

**Comment by ankushagarwal** [comment]
As I was re-writing it, I too, was thinking that it can be removed since 1.3 is very old.

**Comment by thaJeztah** [comment]
I'm +1 for removing (sorry for the time you put in rewriting it <3)

**Comment by ankushagarwal** [comment]
Updated

**Comment by thaJeztah** [comment]
LGTM! Thanks @ankushagarwal!

ping @moxiegirl - we opted for removing the note, because it no longer added much

**Comment by moxiegirl** [comment]
LGTM --- wonderful catch!

**Comment by moxiegirl** [comment]
@calavera cherry pick?

**Comment by calavera** [comment]
cherry picked into #15091

**Pull request merged**
