### PR TITLE
Add Quantities of Service Configuration for Swarm

### PR DESCRIPTION
**Pull request by ghostplant**
Currently, these configurations are not updated to swarm while standalone services support.
This merges container configurations from two separated working streams into one.

Fixing 2 old issues:
1) https://github.com/docker/docker/issues/28618
2) https://github.com/docker/docker/issues/28619

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
/cc @thaJeztah @aaronlehmann @cpuguy83

**Comment by ghostplant** [comment]
Currently, quantities of container resource configures is separately maintained by two different working namespace to do the same thing, which makes swarm lags far behind docker standalone containers in terms of resource configurations.

Maybe kernel can support more CGroup limits type in the future, so adding flags is an extremely heavy task for both docker standalone configs and docker swarm configs.

**Example:**
`docker run -it --rm --label com.docker.resource.climit.pids=1024 registry`
`docker service create --container-label com.docker.resource.climit.pids=1024 registry`

**Comment by ghostplant** [comment]
I skip adding some resource limit that both docker standalone and swarm mode support, such as cpu_limit and (physical)memory_limit.

It adds the following configurations for swarm at the mement:

com.docker.resource.climit.pids
com.docker.resource.climit.cpu_shares
com.docker.resource.climit.blkio_weight
com.docker.resource.climit.memsw
com.docker.resource.climit.oom_kill_disable

com.docker.resource.ulimit.opts  // open files, .. etc.
com.docker.storage.opts // (e.g. size=10G), quota limit for btrfs/devmapper/xfs/zfs .. etc.

com.docker.volume.default.disable_anonymous // no volume if anonymous
com.docker.volume.default.driver // set default volume driver that anonymous volumes are passed to instread of local.

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
This should be handled in Swarmkit rather than abusing labels as if they are hostconfig.

Related discussion:  https://github.com/docker/swarmkit/pull/1932

**Comment by ghostplant** [comment]
@AkihiroSuda I see Swarm already uses many container labels to store some service data, such as `com.docker.swarm.taskname`.
Besides, I think maintaining same resources by two different streams is an endless work and always keeps API changing.
Since kmem is replaced by pids, I think removing out-of-date resource configs for both of them is also quite heavy.

**Comment by ghostplant** [comment]
@AkihiroSuda 
I don't think this is abusing labels. In swarm mode, `--label` is a different space that users/docker-compose can store data.

**Comment by thaJeztah** [comment]
I agree with @AkihiroSuda. These options should not be set through labels; _if_ implemented, these options should be set through a flag.

**Comment by ghostplant** [comment]
@thaJeztah Well.. This is native labels used by swarm instead of swarm labels..

**Comment by thaJeztah** [comment]
It's not about labels being "native" or not, but that labels are not the right approach for setting these options.

"hostname", "env" or "name" are also "native" options, but (as a weird example) I would not expect setting `--hostname=com.docker.security-opt.no-new-privileges` to set `--security-opt=no-new-privileges`

**Pull request closed without merging**
