### PR TITLE
Resolve connection reset by peer regression

### LINKED ISSUE #30816: [REGRESSION] connection reset by peer when attaching stdin AND stderr at run
**Description**

echo'ing something while attaching stdin AND stderr at docker run isn't working anymore. Works fine if you use just stdin or just stderr instead.

**Steps to reproduce the issue:**
1. `echo true | docker run -a stdin -a stderr --tty=false fedora bash`
2. `echo true | docker run -a stdin -a stderr fedora bash`
3.

**Describe the results you received:**
```sh
$ echo true | docker run -a stdin -a stderr fedora bash
read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Describe the results you expected:**

just exit == 0

**Additional information you deem important (e.g. issue happens only occasionally):**

if you revert this https://github.com/docker/docker/pull/30446 - everything works ok again.

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   41650df
 Built:        Wed Feb  8 09:46:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   41650df
 Built:        Wed Feb  8 09:46:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 51
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: cc oci runc
Default Runtime: oci
Init Binary: docker-init
containerd version: 78fb8f45890a601e0fd9051cf9f9f74923e950fd
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.9.7-201.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44GiB
Name: runcom.usersys.redhat.com
ID: 62I5:E7N5:VHP3:HEWA:7I2L:JLUR:JQV7:SDPV:GYHS:LFYI:QBIH:KRRV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 24
 System Time: 2017-02-08T10:00:49.513415092+01:00
 EventsListeners: 0
Username: runcom
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

everywhere

### PR DESCRIPTION
**Pull request by jim-minter**
Fixes #30816 (regression introduced by #30446)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! @vieux added this to the 17.04 milestone, because it looks like this regression was introduced in 17.04

ping @cpuguy83 @runcom PTAL

**Comment by runcom** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
all green, thanks!

**Pull request merged**
