### PR TITLE
Vendor swarmkit 9fdea50

### PR DESCRIPTION
**Pull request by aaronlehmann**
This includes a change to support ingress network replacement and two important scheduler fixes:

- Allow replacing ingress network  https://github.com/docker/swarmkit/pull/2028
- scheduler: Fix accounting when task ends up in multiple groups https://github.com/docker/swarmkit/pull/2031
- scheduler: Correctly count tasks at bottom level of decision tree  https://github.com/docker/swarmkit/pull/2032

cc @aboch @vieux

### CODE REVIEW

**Comment by aboch** [comment]
As soon as this goes in, I will remove the swarmkit vendoring from #31714

**Comment by mavenugo** [comment]
@aaronlehmann @aboch Curious to know how dependent #31714 is on this PR ? 
By picking this PR without #31714, will there be any impact to the ingress network ?

**Comment by aboch** [comment]
@mavenugo There _should_ not be impact to the swarm ingress network.
But user will be able to remove the ingress network with this vendoring only. 
And the CI is failing for that.

**Comment by mavenugo** [comment]
> But user will be able to remove the ingress network with this vendoring only.

@aboch that does mean there is an impact with ingress network... isnt it ?

@aaronlehmann @aboch if we are targetting this PR to be part of 17.04, then I guess we have to pull in the docker side and libnetwork changes from https://github.com/docker/docker/pull/31714 to this one ?

**Comment by aaronlehmann** [comment]
Oops. I've added the test change from #31714.

**Comment by mavenugo** [comment]
@aaronlehmann i dont think adding just the IT is going to help since the tests need the `--ingress` option and it will fail without having the other changes from https://github.com/docker/docker/pull/31714.

Since the swarmkit brought in the ingress changes earlier than other changes that you are vendoring in, I dont see a way out other than merging this PR of yours and @aboch's :-(
Unless we rebase swarmkit and re-adjust the commit ordering and pick up a GIT SHA that is older than @aboch's changes and effectively removing the ingress swarmkit changes.

**Comment by aaronlehmann** [comment]
Ah, I didn't realize that.

I could remove this test and allow it to be re-added shortly afterwards in #31714. It isn't testing anything particularly critical (just that the ingress network can't be removed, which is now allowed). Or this PR can be subsumed into #31714. Either way is fine.

**Comment by mavenugo** [comment]
Yes. I think it is better to just merge this PR with https://github.com/docker/docker/pull/31714.
@aboch can you pls consider taking this over in your PR ?

**Comment by aboch** [comment]
ok

**Comment by aboch** [comment]
So I carried this in #31714

**Comment by aaronlehmann** [comment]
Thanks

**Pull request closed without merging**
