### PR TITLE
fix a couple of typo

### PR DESCRIPTION
**Pull request by jianliao82**
fix a couple of typo 

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! The change itself looks good, but looking at the commit message;

```
fix typo

fix typo

Signed-off-by: jliao <jliao@alauda.io>
```


@jianliao82 could you use your [real / full name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work) in the sign-off? Otherwise we'll have to add another entry in the `.mailmap` to map your alias to your full name 😅

**Review by jianliao82 — COMMENTED** [review]
already update the commit

**Comment by jianliao82** [comment]
@thaJeztah already update the commit, Could you help to take a look at it again?

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
