### PR TITLE
[17.03] Update libnetwork vendor

### PR DESCRIPTION
**Pull request by cpuguy83**
Pulls in docker/libnetwork#1750

### CODE REVIEW

**Comment by cpuguy83** [comment]
Ping @mlaventure @thaJeztah

**Comment by mavenugo** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
related PR on master; https://github.com/moby/moby/pull/31343

**Review by mlaventure — APPROVED** [review]
LGTM

**Pull request merged**
