### PR TITLE
Convert some "daemon" static error strings to the new errocode package format

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by calavera** [comment]
This LGTM, but I wonder if having the errors package inside api makes sense. We're using the errors everywhere, maybe the package should be `github.com/docker/docker/errors`. What do you think?

**Comment by duglin** [comment]
I put it there originally because I viewed it as something that went along with the APIs - meaning from an API-user perspective they would eventually see the error codes via API calls and so it was kind of related to the structs they were seeing in the json.

But you are right that its not just an API thing, so I'm ok with moving it if people want.

**Comment by duglin** [comment]
If I can get one more LGTM then I'll issue a PR for the move :-)   - don't want to do it while some error PRs are lingering

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ill merge then you can move :)

**Comment by duglin** [comment]
@jfrazelle thanks!!!

**Pull request merged**
