### PR TITLE
Reduce spew data dumped

### LINKED ISSUE #28517: Sigusr1 generates huge files
#27331 added daemon-data logging on `sigusr1` (in addition to printing stacktraces).

In linux this file contains a lot of useless information, for example array of 65536 IP addresses. While we can use this file to figure out where to cut allocations the current form doesn't help debugging actual problems and makes is harder for users to send us these files.

For empty daemon this file contains 102297 lines and is `6.3MB`.
As soon as swarm mode is enabled the file had `8312739` lines, `731MB` and took 14 seconds to generate(plus shows some proto warnings). I'd assume it contains CA keys when swarm is not locked.

### PR DESCRIPTION
**Pull request by cpuguy83**
Instead of dumping the whole daemon, only dump some specific items.

Closes #28517

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @tonistiigi

**Comment by jhowardmsft** [comment]
Nit - if we're going to split, we should probably not dump things like the UID/GID maps on Windows, but not an issue. LGTM.

**Comment by cpuguy83** [comment]
Going to make one change here so that we can dump a struct with actual names instead of directly dumping the objects.

**Comment by cpuguy83** [comment]
There, and now it's a bit more clear what's being dumped.

**Comment by jhowardmsft** [comment]
Still LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by tonistiigi** [comment]
cc @aaronlehmann @thaJeztah

**Comment by aaronlehmann** [comment]
This reduces the size to to 6.6K for me (!)

LGTM, assuming this is enough output to be useful for debugging

**Review by thaJeztah — APPROVED** [review]
SGTM (assuming this gives enough information :smile:)

**Pull request merged**
