### PR TITLE
Replace pkg/version with engine-api/types/versions

### PR DESCRIPTION
**Pull request by calavera**
We moved the versioning code to the api repo to share so it doesn't
make sense anymore to keep this package here.

I updated the engine-api vendor, removed the package and update the code
where it was necessary.

### CODE REVIEW

**Comment by vdemeester** [comment]
@calavera damn, we did the same change then (except from `CopyToContainer`) :stuck_out_tongue_closed_eyes: (ref: #22153)

**Comment by calavera** [comment]
ups, sorry, I didn't see it

**Comment by thaJeztah** [comment]
haha; great minds think alike?

**Comment by vdemeester** [comment]
@calavera np :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
