### PR TITLE
Update aws-sdk-go and go-ini

### PR DESCRIPTION
**Pull request by yongtang**
This fix updates aws-sdk-go and go-ini to recent versions. The aws-sdk-go used to be `v1.4.22` which was more than a year old, and go-ini used to be `pre-1.0` release.

This fix updates aws-sdk-go to v1.12.66 and go-ini to v1.25.4:
```
github.com/aws/aws-sdk-go v1.12.66
github.com/go-ini/ini v1.25.4
```

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Full diffs:

- https://github.com/aws/aws-sdk-go/compare/v1.4.22...v1.12.66
- https://github.com/go-ini/ini/compare/060d7da055ba6ec5ea7a31f116332fe5efa04ce0...v1.25.4

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @samuelkarp @cpuguy83 @anusha-ragunathan

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
