### PR TITLE
Add a buffered Writer between layer compression and layer upload

### PR DESCRIPTION
**Pull request by aaronlehmann**
Without this buffering, the compressor was outputting 64 bytes at a
time to the HTTP stream, which was resulting in absurdly small chunk
sizes and a lot of extra overhead. The buffering restores the chunk size
to 32768 bytes, which matches the behavior with 1.8.2.

Times pushing to a local registry:

1.8.2: 0m18.934s
master: 0m20.564s
master+this commit: 0m17.593s

Fixes: #17038

### CODE REVIEW

**Comment by tiborvass** [comment]
@aaronlehmann YOU DA KING!!!

**Comment by LK4D4** [comment]
Much better. It was even worse with go1.5, like 4 times slower then 1.8.2

**Comment by thaJeztah** [comment]
:+1: thanks!!!

**Comment by icecrime** [comment]
Like a boss.

**Comment by thaJeztah** [comment]
94840 jpg

**Comment by cpuguy83** [comment]
ping @burke to confirm

**Comment by unclejack** [comment]
@aaronlehmann Please use pkg/pools for that writer.

**Comment by burke** [comment]
Nailed it -- I can't even explain how much this improved my day. Thanks, @aaronlehmann!

```
Oct 23 15:47:58.395:	80e2e3f7fda7: Preparing
Oct 23 15:47:58.560:	80e2e3f7fda7: Pushing
7fda7: Preparing
Oct 23 15:47:58.560:	80e2e3f7fda7: Pushing
Oct 23 15:48:12.232:	80e2e3f7fda7: Pushed
Oct 23 15:48:12.472:	e07b6095233b: Image already exists
Oct 23 15:48:12.713:	8db39f7a1862: Image already exists
Oct 23 15:48:13.001:	b25524db876d: Image already exists
Oct 23 15:48:13.288:	c290db7a5070: Image already exists
Oct 23 15:48:13.609:	454c2d886fcc: Image already exists
Oct 23 15:48:13.956:	ba5e0000ba5c: Image already exists
Oct 23 15:48:13.958:	c49e03e204c5ab006783ef4091d67e20ad66758b: digest: sha256:9e8be2ddb475c109166e533bac46efaf92204ee17a367ef72dd936983c6b4d37 size: 11596
```

**Comment by stevvooe** [comment]
@aaronlehmann Is 32768 optimal? I would think something around 512KB to 1MB would be the sweet spot. I'm assuming that this buffer size will maintain compression stability. Nice job tracking this down.

**Comment by stevvooe** [comment]
LGTM

**Comment by aaronlehmann** [comment]
@stevvooe: I experimented with larger buffer sizes, but found that the HTTP stream was still using 32768 byte chunks even with larger buffers. The limitation is probably somewhere in Go's HTTP client; I didn't track it down.

This shouldn't have any positive or negative impact on compression stability because the buffer buffers the *output* of the compressor.

**Comment by stevvooe** [comment]
@aaronlehmann Interesting. Let's get this merged.

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
@unclejack aaargh my bad I completely forgot your comment. I'll send a PR to address it

**Comment by unclejack** [comment]
@stevvooe You most certainly don't want to go above 32 KB for this. I've tested this in the past extensively.

@tiborvass Ok, thanks! <3

**Comment by stevvooe** [comment]
@unclejack Based on what? Do you have test data? Under what conditions? 32KB is very small for a large pipe with low latency. On the other hand, I would expect larger buffer sizes to stress GC.

**Comment by burke** [comment]
@stevvooe I've seen things like this cap out at 32k before. I Am Not A Network Engineer™ but people tell me it's because a lot of [network hardware will tear apart IP frames over 32k](https://en.wikipedia.org/wiki/IP_fragmentation), forcing the client to receive in 32k chunks anyway.

**Comment by stevvooe** [comment]
@burke Of course the hardware will tear apart large frame, but we are talking about unit of transfer to the kernel for the write/read call. This will be optimally set as a function of the bandwidth delay product. I'm not sure why we would see a cap of 32KB in performance increases for sufficiently large networks. There are likely other factors that make 32KB optimal, such as buffer allocation and non-optimal network links.

32KB is probably fine when it comes down to it.

**Pull request merged**
