### PR TITLE
volumes/local: gofmt

### PR DESCRIPTION
**Pull request by thaJeztah**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Rate limited on hub.

**Review by tianon — APPROVED** [review]
LGTM :eyes:

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Failure on s390x is unrelated: `docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password.`

Merging.

**Pull request merged**
