### PR TITLE
no more 'docker node reject' in docs

### PR DESCRIPTION
**Pull request by vieux**
ping @sfsmithcha @icecrime @thaJeztah

### CODE REVIEW

**Comment by vieux** [comment]
not sure about how to fix this one

**Comment by SvenDowideit** [comment]
this is jenkins & hugo going wonkey

**Comment by SvenDowideit** [comment]
retest this please

**Comment by SvenDowideit** [comment]
LGTM

**Comment by icecrime** [comment]
Thanks! LGTM

**Comment by sfsmithcha** [comment]
LGTM

**Pull request merged**
