### PR TITLE
Easily use $(docker swarm join-token worker|manager) without copy paste.

### PR DESCRIPTION
**Pull request by timezstyle**
Consider we already created node-1, node-2 with docker-machine,
And node-1 already use
`docker swarm init --advertise-addr $(docker-machine ip node-1)`

`export MANAGER_HOST=tcp://$(docker-machine ip node-1):2376`
# switch to node-2

`eval $(docker-machine env node-2)`
# join to worker

`eval $(docker -H $MANAGER_HOST swarm join-token worker)`
# or join to manager

`eval $(docker -H $MANAGER_HOST swarm join-token manager)`

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @aaronlehmann WDYT?
Was it intentional that the token output was not `eval`-able?

**Comment by aaronlehmann** [comment]
For scripting purposes, you can use the `-q` option to just get the token.

**Comment by thaJeztah** [comment]
Correct, the `-q` / `--quiet` option is designed for this, so I think we should close this one.

Thanks for contributing though, @timezstyle. I'm closing this PR, but let me know if there's reason you think it should not be closed

**Comment by timezstyle** [comment]
@thaJeztah @aaronlehmann 

Thanks for viewing.

But I still think more easily way will be nice.


> For example:

eval $(docker-machine env manager-node-1)
docker swarm init --advertise-addr $(docker-machine ip manager-node-1)
export MANAGER_1_HOST=tcp://$(docker-machine ip manager-node-1):2376
#maybe we don't need
export MANAGER_1_MANAGER_TOKEN=$(docker swarm join-token -q manager)
export MANAGER_1_WORKER_TOKEN=$(docker swarm join-token -q worker)

eval $(docker-machine env manager-node-2)
docker swarm init --advertise-addr $(docker-machine ip manager-node-2)
export MANAGER_2_HOST=tcp://$(docker-machine ip manager-node-2):2376
#maybe we don't need
export MANAGER_2_MANAGER_TOKEN=$(docker swarm join-token -q manager)
export MANAGER_2_WORKER_TOKEN=$(docker swarm join-token -q worker)

.
.
.

eval $(docker-machine env worker-node-3)
docker swarm join \
    --token $MANAGER_1_WORKER_TOKEN \
    $(docker-machine ip manager-node-1):2377 


eval $(docker-machine env worker-node-4)
docker swarm join \
    --token $MANAGER_2_WORKER_TOKEN \
    $(docker-machine ip manager-node-2):2377


> or just

eval $(docker-machine env worker-node-3)
eval $(docker -H $MANAGER_1_HOST swarm join-token worker)

eval $(docker-machine env worker-node-4)
eval $(docker -H $MANAGER_2_HOST swarm join-token worker)


Please advise.

**Pull request closed without merging**
