### PR TITLE
Plugins fixes

### PR DESCRIPTION
**Pull request by tiborvass**
Fixes bug in install and adds disabled flag
Removes automatic mounting of a state dir
And fixes to command usage

### CODE REVIEW

**Comment by vdemeester** [comment]
@tiborvass cherry-pick commit from https://github.com/docker/docker/compare/master...vdemeester:defaulttag-on-plugin-commands too :angel:

**Comment by vdemeester** [comment]
LGTM 🐺

**Comment by vieux** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by vdemeester** [comment]
@tiborvass I think there is a regression on legacy volume driver, we should handle the ref/tag thingy only when the plugin is not legacy :angel: 

```
20:19:30 FAIL: docker_cli_external_volume_driver_unix_test.go:314: DockerExternalVolumeSuite.TestExternalVolumeDriverDeleteContainer
20:19:30 
20:19:30 [d37953936] waiting for daemon to start
20:19:30 [d37953936] daemon started
20:19:30 docker_cli_external_volume_driver_unix_test.go:319:
20:19:30     c.Assert(err, checker.IsNil, check.Commentf(out))
20:19:30 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc82047ed60), Stderr:[]uint8(nil)} ("exit status 125")
20:19:30 ... /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: create d55d6408b2e65f16ca73bc76b3bda86dcf3611e13421576ea459406e1850b729: create d55d6408b2e65f16ca73bc76b3bda86dcf3611e13421576ea459406e1850b729: Error looking up volume plugin test-external-volume-driver: legacy plugin: plugin not found.
20:19:30 See '/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/../binary-client/docker run --help'.
20:19:30 
20:19:30 
20:19:30 [d37953936] exiting daemon
20:19:30 
20:19:30 ----------------------------------------------------------------------
```

**Comment by anusha-ragunathan** [comment]
if defaultTag works for enable/disable/rm, tests can be updated accordingly.

**Comment by vdemeester** [comment]
Last commit fixes the failures :angel: :+1: 
re-LGTM 🐯

**Comment by tiborvass** [comment]
the previously failing tests are now working, as confirmed by experimetnal CI, merging.

**Pull request merged**
