### PR TITLE
[23.0 backport] libnetwork: cleanup config package, remove old integration tests

### PR DESCRIPTION
**Pull request by thaJeztah**
- backport of https://github.com/moby/moby/pull/44193

Not 100% sure if we need this, although it may help to have the 23.0 branch more in sync with master (and it removes a bunch of dead code). I actually started this backport as I ran into a merge conflict in https://github.com/moby/moby/pull/44727, and thought it would be because of the changes from this PR, but that didn't turn out to be the cause. I had the cherry-pick done, so thought I'd open as a PR for consideration.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@corhere @neersighted let me know what you think (happy to close if we don't want this one)

**Comment by neersighted** [comment]
I'm not opposed to bringing this in, since it's mostly cleanup and will make maintaining the branch easier.

**Comment by thaJeztah** [comment]
Thanks! 

Looks like CI is timing out though; wondering if there's an actual issue in the changes (I need to have a look why it's timing out)

**Comment by neersighted** [comment]
It's looking like there might be legitimate test failures here caused by the daemon dying or failing to start:

```
=== RUN   TestDockerNetworkSuite/TestDockerNetworkCreateDelete
    docker_cli_network_unix_test.go:46: [dc9c21e3f9cc4] daemon is not started
=== RUN   TestDockerNetworkSuite/TestDockerNetworkCreateDeleteSpecialCharacters
    docker_cli_network_unix_test.go:46: [dd0692f927aba] daemon is not started
=== RUN   TestDockerNetworkSuite/TestDockerNetworkCreateHostBind
    docker_cli_network_unix_test.go:46: [d4dfc804437cd] daemon is not started
=== RUN   TestDockerNetworkSuite/TestDockerNetworkCreateLabel
    docker_cli_network_unix_test.go:46: [d2a4da4965150] daemon is not started
=== RUN   TestDockerNetworkSuite/TestDockerNetworkCreatePredefined
    docker_cli_network_unix_test.go:46: [d0623bda6a713] daemon is not started
```

**Comment by thaJeztah** [comment]
Interesting. Curious why that doesn't happen on master. Could there be an issue elsewhere that's exposed by these changes?

**Comment by neersighted** [comment]
...it looks like the job finally passed, but took nearly an hour running the integration tests?

**Comment by thaJeztah** [comment]
Would have to check other CI runs. It's _possible_ integration tests take that long 🤔

**Comment by thaJeztah** [comment]
Here's from another PR (the CLANG PR); https://github.com/moby/moby/actions/runs/3952053485

**Comment by neersighted** [comment]
Okay, yikes, it looks like I just haven't internalized how long that one job is taking. @crazy-max can we do anything to divide the workload up more evenly?

**Comment by crazy-max** [comment]
> Would have to check other CI runs. It's _possible_ integration tests take that long 🤔

Yes atm we have a 2h timeout https://github.com/moby/moby/pull/44539. What test suite took more than that? I guess this one?: https://github.com/moby/moby/actions/runs/3952643258/jobs/6768015975

image

> Okay, yikes, it looks like I just haven't internalized how long that one job is taking. @crazy-max can we do anything to divide the workload up more evenly?

Yes as I said https://github.com/moby/moby/pull/43682#issuecomment-1146617679 I don't calculate cyclomatic complexities of tests functions in gotestlist to add some "weight" and distribute a bit better. In the meantime as `integration-cli` tests should be frozen, we could create a manual matrix if we continue to have this issue frequently.

**Review by neersighted — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thanks!

Yes, we should look at (if needed, manually) splitting up the tests. Currently there's too much of a difference between the different suites we run, so all of them are "idling" waiting for that final one (`integration-cli`) to complete 😂

**Pull request merged**
