### PR TITLE
pkg/ioutils: remove unused functions

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

Animal:

:dog:

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by cpuguy83** [comment]
FYI this is not used in the daemon, but is used by the CLI, so docker/cli will need to find an alternative.

**Comment by stevvooe** [comment]
@cpuguy83 Is there a way to do cross-project usage analysis?

PR still stands: these have nothing to do with io and are very specific to the way the cli prints things. We should probably move these functions there.

**Comment by aaronlehmann** [comment]
I support doing this, but think it should be preceded by a PR in `cli` that removes the dependency.

**Comment by stevvooe** [comment]
@aaronlehmann Removed this in https://github.com/docker/cli/pull/66.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Twice the LGTM's b/c GH is weird like that.

**Pull request merged**
