### PR TITLE
Reorganize client and cli packages

### PR DESCRIPTION
**Pull request by dnephin**
Following the split of the binaries into two package the names of files and packages was left a little scattered.  This PR moves a few things around so that the package names and file names better match their contents.

33c9eda - cleanup the `cli` package by moving all the flag related structs into the `cli/flags` package

30e3620 - move the `ConfigFile` struct into a new package. This will allow us to create a new default no-arg constructor for a `ConfigFile` object. Previously this was not possible because of a circular reference between `cliconfig/credentials` and `cliconfig/`

2f9dd13 - consolidate the contents of `cmd/docker/client.go` into `cmd/docker/docker.go`. Now that everything in the `cmd/docker` directory is for the client there's no real value in splitting them into separate files.

### CODE REVIEW

**Comment by icecrime** [comment]
```
11:49:19 ---> Making bundle: validate-lint (in bundles/1.12.0-dev/validate-lint)
11:49:19 Errors from golint:
11:49:19 cli/usage.go:9:1: comment on exported var DockerCommandUsage should be of the form "DockerCommandUsage ..."
```

**Comment by dnephin** [comment]
Fixed! thanks

**Comment by tonistiigi** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
