### PR TITLE
c8d/pull: Progress fixes

### PR DESCRIPTION
**Pull request by vvoland**
**- What I did**
- Emit `Pulling fs layer` (fixes issue in Docker Desktop)
- Guard `io.Writer` in `progressOutput` with a mutex
- Don't emit `Downloading` when no progress was made yet 

**- How I did it**
See commits.

**- How to verify it**

**- Description for the changelog**
```markdown changelog
containerd image store: Fix image pull not emitting `Pulling fs layer` status
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by dmcgowan** [comment]
> Guard io.Writer in progressOutput with a mutex

What is the issue seen for this? Is `prog.LastUpdate` not actually the last update or is the writer itself not protected?

**Comment by vvoland** [comment]
The writer itself is not protected. I noticed that after I experienced random failures when adding that additional progress update. This happens because `HandlerFunc` is executed with `images.Dispatch` on containerd side so using non-thread safe things in the handler func isn't safe.

**Review by neersighted — APPROVED** [review]

**Review by dmcgowan — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]

**Comment by thaJeztah** [comment]
Failures are the expected ones (containerd snapshotter on Windows)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
