### PR TITLE
add script to test the old apt-repo

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon @cpuguy83 

we can run this on jenkins to ensure people know the old apt repo works for various versions that are not in the new repos :)

related: #12461

### CODE REVIEW

**Comment by jfrazelle** [comment]
@mattmoor you will hopefully like this :)

**Comment by cpuguy83** [comment]
What's the correct way to run this? just run hack/make.sh test-old-apt-repo fails unless you have `docker` in your `$PATH`

**Comment by jfrazelle** [comment]
hack/make/test-old-apt-repo

**Comment by cpuguy83** [comment]
+1

**Comment by thaJeztah** [comment]
nice!

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
Oh I like that ! :wink: 
LGTM

**Pull request merged**
