### PR TITLE
daemon/exec_linux: assorted cleanups

### PR DESCRIPTION
**Pull request by laurazard**
**- What I did**

Cleanup following https://github.com/moby/moby/pull/46715

**- How I did it**

Removed a duplicate import (and made according adjustments), and removed `withResetAdditionalGIDs` since it's no longer necessary (see discussion on https://github.com/moby/moby/pull/46715#discussion_r1371371282)

**- How to verify it**

Same steps as https://github.com/moby/moby/pull/46715

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Review by rumpl — APPROVED** [review]

**Comment by laurazard** [comment]
Hah, we were using the `oci` import for creating the slice and the `coci` import for the options inside it 😅 

https://github.com/moby/moby/pull/46723/commits/2b203ad8d898bc48ce16555a9262f7f096eb6a35

**Comment by laurazard** [comment]
@thaJeztah wanna TAL?

**Comment by thaJeztah** [comment]
LGTM, but needs a rebase now 😅

**Review by thaJeztah — APPROVED** [review]
LGTM after rebase

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
