### PR TITLE
Run unit tests as single command

### PR DESCRIPTION
**Pull request by LK4D4**
For me it increased speed of unit-tests tremendously, however this disabled
coverage profiles generation, which I think is pretty good tradeoff.

### CODE REVIEW

**Comment by tiborvass** [comment]
Ping @tianon  too ;)

**Comment by LK4D4** [comment]
```
- It's BASH time!
- No, @tianon, no!
```

**Comment by calavera** [comment]
can we have a flag to enable coverage profile generation on demand? I think it's a good tradeoff, but I'd still like to be able to generate those profiles if we want easily.

**Comment by LK4D4** [comment]
@calavera I think you can generate them with `$TESTFLAGS`, however I think it's easier to generate them with just `go test` without involving bash magic.

**Comment by calavera** [comment]
sounds good to me.

@jfrazelle what do you think?

**Comment by jfrazelle** [comment]
LGTM!

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
oh shit sorry just saw the cover comments omg im the worst

**Pull request merged**
