### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by aochagavia**

### CODE REVIEW

**Comment by aochagavia** [comment]
I see you need to sign the commits, but I have no time to do it now (I would have to investigate how to do that on Windows). Feel free to treat this PR as an issue.

**Comment by duglin** [comment]
just add `-s` to your `git commit` command, and make sure you have the git config properties `user.name` and `user.email` set.

**Comment by aochagavia** [comment]
Done. Thanks! I didn't expect it to be that easy :smile:

**Comment by duglin** [comment]
LGTM

**Pull request merged**
