### PR TITLE
Switch all logging to use containerd log pkg

### PR DESCRIPTION
**Pull request by cpuguy83**
This unifies our logging and allows us to propagate logging and trace contexts together.

### CODE REVIEW

**Comment by cpuguy83** [comment]
This is mostly a grep->sed to replace things but needed some help to clean things up after

```
git grep 'logrus\.' | grep -v vendor | grep '.go' | grep -v '//' | grep -v GetLevel | grep -v SetLevel | grep -v AddHook | grep -v '[aA-zZ]+Level' | awk -F':' '{ print $1 }' | xargs sed -i 's,logrus\.,log.G(ctx).,'
```

```bash
while ! (
    printf '%s\n\n%s' 'module github.com/docker/docker' 'go 1.19' >"go.mod"
    GO111MODULE=on go build -mod=vendor -modfile=vendor.mod -gcflags='-e' ./cmd/dockerd 2>errs.txt
); do
    grep "command-line-arguments" errs.txt | bash -xc 'while IFS= read -r line; do IFS=: read -r file num extra <<<$line; sed -i "${num}s,command-line-arguments/endor/,," $file; done'
    grep "undefined: ctx" errs.txt | bash -xc 'while IFS= read -r line; do IFS=: read -r file num extra <<<$line; sed -i "${num}s,ctx,context.TODO()," $file; done'
    grep "log\.G(ctx)\.ErrorKey" errs.txt | bash -xc 'while IFS= read -r line; do IFS=: read -r file num extra <<<$line; sed -i "${num}s,log\.G(ctx)\.ErrorKey,logrus.ErrorKey," $file; done'
    grep "log\.G(context\.TODO())\.ErrorKey" errs.txt | bash -xc 'while IFS= read -r line; do IFS=: read -r file num extra <<<$line; sed -i "${num}s,log\.G(context\.TODO())\.ErrorKey,logrus.ErrorKey," $file; done'
    rm go.mod
    grep "undefined: context" errs.txt | bash -xc 'while IFS= read -r line; do IFS=: read -r file extra <<<$line; goimports -w ./${file}; done'
    grep "undefined: logrus" errs.txt | bash -xc 'while IFS= read -r line; do IFS=: read -r file extra <<<$line; goimports -w ./${file}; done'
done
```

Found goimports was giving me the wrong import for logrus... which was really strange. See the script above for that correction as well.
There was probably a couple of other cases that I manually fixed when I first started going through it.

**Comment by cpuguy83** [comment]
Also really fun... `-gcflags='e'` should give me all compile errors but it wasn't working and hence the loop.

**Comment by cpuguy83** [comment]
All green.

**Comment by cpuguy83** [comment]
So really https://github.com/moby/moby/pull/45799#issuecomment-1604778815 was not enough and go tooling is so bad for this.
I ended up resorting to using golangci-lint to get all errors.

**Comment by thaJeztah** [comment]
In general, I'm a big "plus 1" to doing this (and removing the logrus from everywhere). I'm wondering if we should consider making the `log` package a separate module in containerd if it's gonna be used more outside of containerd itself.

A couple of things that I'm wondering (also with in the back of my mind that  `slog` is becoming a thing);
 
- First of all, I went looking for the context-logger part of Golang's slog, as I recalled that being shown in some examples (e.g. https://thedevelopercafe.com/articles/logging-in-go-with-slog-a7bb489755c2). Unfortunately, it looks like that part was removed in https://github.com/golang/exp/commit/c42ee1cf562e374f85357c6b1d9deb70334b8bf7. Does anyone know if there's more information around that, and/or if there's plans to bring that back in some form?
- I see the slog package has a `WithAttrs` option; wondering if it would make sense to have an adaptor for that (and what the best moment would be to implement/apply that if we want to reduce code-churn); https://pkg.go.dev/golang.org/x/exp/slog#Handler.WithAttrs

**Comment by neersighted** [comment]
Related (from long ago; probably should be closed, but still attacking a related issue): https://github.com/moby/moby/issues/36155

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by neersighted — APPROVED** [review]

**Comment by thaJeztah** [comment]
We discussed using the log.Fields  alias, but that's not yet in the 1.6 branch, so we should look at getting that backported.

**Pull request merged**
