### PR TITLE
bump pkg/errors v0.8.1

### PR DESCRIPTION
**Pull request by thaJeztah**
https://github.com/pkg/errors/compare/v0.8.0...v0.8.1

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
rebased

**Comment by thaJeztah** [comment]
rebased again to get the fix for the windows images in

**Comment by thaJeztah** [comment]
```
02:19:43 OK: 1451 passed, 53 skipped
02:19:43 PASS

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
