### PR TITLE
update to golang 1.19.1

### PR DESCRIPTION
**Pull request by thaJeztah**
- depends on https://github.com/moby/moby/pull/44099

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
We may need to make changes because of;


> New unix build constraint
>
> The build constraint unix is now recognized in //go:build lines. The constraint is satisfied if the target operating system, also known as GOOS, is a Unix or Unix-like system. For the 1.19 release it is satisfied if GOOS is one of aix, android, darwin, dragonfly, freebsd, hurd, illumos, ios, linux, netbsd, openbsd, or solaris. In future releases the unix constraint may match additional newly supported operating systems.

**Comment by thaJeztah** [comment]
Indeed... they try to use SemVer rules for software that doesn't use SemVer; https://github.com/actions/setup-go/tree/v3.2.0#supported-version-syntax

> Supported version syntax
>
> The go-version input supports the following syntax:
>
> Specific versions: 1.15, 1.16.1, 1.17.0-rc.2, 1.16.0-beta.1
>
> SemVer's version range syntax: ^1.13.1, >=1.18.0-rc.1
> For more information about semantic versioning, please refer to semver documentation.

**Comment by thaJeztah** [comment]
And some failures on Windows 2022; could be just "slow" or an actual regression somewhere;

```
=== Failed
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_local/tty/stdout_and_stderr (20.04s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_local/tty/stdout_and_stderr (20.04s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_local/without_tty/stdout_and_stderr (22.15s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_local/without_tty/stdout_and_stderr (22.15s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_local/without_tty/only_stdout (23.45s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_local/without_tty/only_stdout (23.45s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_local/tty/only_stdout (19.39s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_local/tty/only_stdout (19.39s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_local (0.02s)
    --- FAIL: TestLogs/driver_local (0.02s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_json-file/without_tty/only_stderr (19.45s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_json-file/without_tty/only_stderr (19.45s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_json-file/tty/stdout_and_stderr (20.33s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_json-file/tty/stdout_and_stderr (20.33s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_json-file/without_tty/only_stdout (20.09s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_json-file/without_tty/only_stdout (20.09s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_json-file/without_tty/stdout_and_stderr (20.30s)
    logs_test.go:139: timeout hit after 10s: waiting for container to be stopped
        --- FAIL: TestLogs/driver_json-file/without_tty/stdout_and_stderr (20.30s)
=== FAIL: github.com/docker/docker/integration/container TestLogs/driver_json-file (0.02s)
    --- FAIL: TestLogs/driver_json-file (0.02s)
=== FAIL: github.com/docker/docker/integration/container TestLogs (119.15s)
```

**Comment by thaJeztah** [comment]
rebased, and updated to rc1

**Comment by thaJeztah** [comment]
updated to RC2

**Comment by AkihiroSuda** [comment]
Is this still WIP?

**Comment by thaJeztah** [comment]
> Is this still WIP?

I left it in draft as there was no release yet, and was considering if we should wait for a `.1`, but now that we have a 22.06 branch, at least it should be good to go for master (and perhaps for 22.06 as well)

**Comment by thaJeztah** [comment]
@AkihiroSuda @cpuguy83 @tianon PTAL (22.06 version is green as well; https://github.com/moby/moby/pull/44085)

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Interesting;

```
INFO [runner] Processors filtering stat (out/in): uniq_by_line: 1/1, diff: 1/1, max_from_linter: 1/1, filename_unadjuster: 2138/2138, skip_files: 2138/2138, exclude-rules: 80/2015, max_per_file_from_linter: 1/1, source_code: 1/1, path_shortener: 1/1, sort_results: 1/1, path_prettifier: 2138/2138, autogenerated_exclude: 2015/2138, exclude: 2015/2015, severity-rules: 1/1, path_prefixer: 1/1, cgo: 2138/2463, identifier_marker: 2015/2015, max_same_issues: 1/1, skip_dirs: 2138/2138, nolint: 1/80 
INFO [runner] processing took 85.464476ms with stages: nolint: 33.716184ms, identifier_marker: 22.070715ms, path_prettifier: 9.728443ms, autogenerated_exclude: 8.841485ms, exclude-rules: 7.749763ms, skip_dirs: 1.754946ms, cgo: 1.390971ms, filename_unadjuster: 171.721µs, source_code: 31.272µs, uniq_by_line: 3.122µs, max_same_issues: 1.305µs, max_per_file_from_linter: 1.29µs, path_shortener: 991ns, exclude: 557ns, skip_files: 452ns, diff: 361ns, max_from_linter: 278ns, severity-rules: 241ns, sort_results: 212ns, path_prefixer: 167ns 
INFO [runner] linters took 1m49.615498289s with stages: goanalysis_metalinter: 1m49.529833919s 
daemon/content.go:66: File is not `goimports`-ed (goimports)
//  labels.*
INFO File cache stats: 1707 entries of total size 8.7MiB 
INFO Memory: 2885 samples, avg is 323.0MB, max is 1223.3MB 
INFO Execution took 4m48.309496089s
script returned exit code 1
```

**Comment by thaJeztah** [comment]
Ah; line was added recently in https://github.com/moby/moby/commit/878906630bdf9edd58dda0b4a3887da86e4e0da2 (https://github.com/moby/moby/pull/44091)

https://github.com/moby/moby/blob/ff76e05913aec1b9e05375b8afc94dd721e7ca6d/daemon/content.go#L66

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
Let me bring this one in for master at least

**Pull request merged**
