### PR TITLE
Bump SwarmKit to remove deprecated grpc metadata wrappers

### PR DESCRIPTION
**Pull request by thaJeztah**
Updates swarmkit to 33d06bf5189881b4d1e371b5571f4d3acf832816, to bring in
docker/swarmkit#2610 (Don't use wrappers for grpc metadata)

full diff: https://github.com/docker/swarmkit/compare/9c2aa152c3054371b833483a7ddad8d15052ec4f...33d06bf5189881b4d1e371b5571f4d3acf832816

ping @dmcgowan @crosbymichael @tonistiigi

### CODE REVIEW

**Comment by thaJeztah** [comment]
This is green now :+1:

**Comment by dmcgowan** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
