### PR TITLE
aufs: remove mntL

### PR DESCRIPTION
**Pull request by kolyshkin**
Commit 5cd62852fa199f27 (PR #39107) added a lock around call to `unix.Mount()`
to avoid the race in aufs kernel code related to xino file creation
and removal. While this is going to be fixed in the kernel, we still
need to support the current aufs, so some kind of fix is required.

A think a better fix (rather than a lock) is to add a random suffix
to the file name (note it is and was a separate file per mount,
never mind the same file name -- the file is created/opened and
removed instantly, so each mount deals with its own file).

With the suffix added, the possibility to hit the race is extremely
low, and we don't have to do any locking.

Note we don't add any more characters, instead we're replacing
`xino` with four random characters in the 0-9a-z range.

See also: https://sourceforge.net/p/aufs/mailman/message/36674769/

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @dmcgowan

**Review by dmcgowan — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
> With the suffix added, the possibility to hit the race is extremely
> low, and we don't have to do any locking.

Probability theory just laughed in my face, as this actually happened once in 6050000 containers created, on a high-end hardware with 1000 parallel "docker create" running.

One way to work around this is increase the randomness by adding more characters, which will further decrease the probability, but won't eliminate it entirely. Another is to fix it upstream (done, see https://github.com/sfjro/aufs5-standalone/commit/abf61326f495352958303860873213e6101a7337, but might not be packported to ubuntu).

Overall, as much as I like this solution, I think we need to revert it :-\

**Pull request merged**
