### PR TITLE
check err

### PR DESCRIPTION
**Pull request by yu8833**
Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
CI failing

**Comment by YuPengZTE** [comment]
Thanks @AkihiroSuda , CI has been OK, PTAL.

**Comment by duglin** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Pull request merged**
