### PR TITLE
Update libcontainer

### PR DESCRIPTION
**Pull request by jessfraz**
update libcontainer

### CODE REVIEW

**Comment by jfrazelle** [comment]
hmmm something is broken w cpushares will lookinnto it tomorrow

**Comment by cyphar** [comment]
I promise it wasn't me. :pray:

**Comment by LK4D4** [comment]
@tianon we lost tags again!

**Comment by jfrazelle** [comment]
do u wanna tag :)

**Comment by tianon** [comment]
Arrrrrg

**Comment by cyphar** [comment]
@jfrazelle Uhhh, yeah the bug is my fault.

**Comment by jfrazelle** [comment]
closing for time being

**Pull request closed without merging**
