### PR TITLE
Adding in 1.60 release notes

### PR DESCRIPTION
**Pull request by moxiegirl**
Updating with thaJetzah's comments
Adding in Fred's copy edits

Signed-off-by: Mary Anthony mary@docker.com
(cherry picked from commit 1f4ef5192c05723e231acc47813c4c8455a0166b)

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM (not a maintainer)

**Comment by moxiegirl** [comment]
@thaJeztah yet...

**Comment by moxiegirl** [comment]
ping @docker/docs-owners

**Comment by fredlf** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
