### PR TITLE
Dockerfile: make cli stages more resilient against unclean termination

### PR DESCRIPTION
**Pull request by thaJeztah**
- relates to https://github.com/moby/buildkit/issues/3955

The Dockerfile in this repository performs many stages in parallel. If any of those stages fails to build (which could be due to networking congestion), other stages are also (forcibly?) terminated, which can cause an unclean shutdown.

In some case, this can cause `git` to be terminated, leaving a `.lock` file behind in the cache mount. Retrying the build now will fail, and the only workaround is to clean the build-cache (which causes many stages to be built again, potentially triggering the problem again).

     > [dockercli-integration 3/3] RUN --mount=type=cache,id=dockercli-integration-git-linux/arm64/v8,target=./.git     --mount=type=cache,target=/root/.cache/go-build,id=dockercli-integration-build-linux/arm64/v8     /download-or-build-cli.sh v17.06.2-ce https://github.com/docker/cli.git /build:
    #0 1.575 fatal: Unable to create '/go/src/github.com/docker/cli/.git/shallow.lock': File exists.
    #0 1.575
    #0 1.575 Another git process seems to be running in this repository, e.g.
    #0 1.575 an editor opened by 'git commit'. Please make sure all processes
    #0 1.575 are terminated then try again. If it still fails, a git process
    #0 1.575 may have crashed in this repository earlier:
    #0 1.575 remove the file manually to continue.

This patch:

- Updates the Dockerfile to remove `.lock` files (`shallow.lock`, `index.lock`) that may have been left behind from previous builds. I put this code in the Dockerfile itself (not the script), as the script may be used in other situations outside of the Dockerfile (for which we cannot guarantee no other git session is active).
- Adds a `docker --version` step to the stage; this is mostly to verify the build was successful (and to be consistent with other stages).

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
- docker-py failure is unrelated, and will be fixed by https://github.com/moby/moby/pull/45769

**Review by neersighted — APPROVED** [review]
I've run into this a bit myself, and ended up with this same kludge locally. It's not pretty, but it will have to do for now.

**Review by vvoland — COMMENTED** [review]
Should we also add  `sharing=private` or `sharing=locked` just in case? So that we don't force remove the lock if for some reason there are multiple runs of the same $TARGETPLATFORM (multiple `docker build` at the same time?).

**Comment by thaJeztah** [comment]
> Are those handled across multiple parallel builds, or is that for "multiple parallel stages that are part of the same build"?

Okay, so learned something new Today; I thought they only protected against parallel use within a single graph, but they do protect against multiple  builds in parallel. I can add those.

**Comment by thaJeztah** [comment]
@vvoland updated, and added `sharing=locked`;

```patch
diff --git a/Dockerfile b/Dockerfile
index 98fa071e9f..7b6525832a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -255,7 +255,7 @@ COPY hack/dockerfile/cli.sh /download-or-build-cli.sh
 ARG DOCKERCLI_REPOSITORY
 ARG DOCKERCLI_VERSION
 ARG TARGETPLATFORM
-RUN --mount=type=cache,id=dockercli-git-$TARGETPLATFORM,target=./.git \
+RUN --mount=type=cache,id=dockercli-git-$TARGETPLATFORM,sharing=locked,target=./.git \
     --mount=type=cache,target=/root/.cache/go-build,id=dockercli-build-$TARGETPLATFORM \
         rm -f ./.git/*.lock \
      && /download-or-build-cli.sh ${DOCKERCLI_VERSION} ${DOCKERCLI_REPOSITORY} /build \
@@ -267,7 +267,7 @@ COPY hack/dockerfile/cli.sh /download-or-build-cli.sh
 ARG DOCKERCLI_INTEGRATION_REPOSITORY
 ARG DOCKERCLI_INTEGRATION_VERSION
 ARG TARGETPLATFORM
-RUN --mount=type=cache,id=dockercli-integration-git-$TARGETPLATFORM,target=./.git \
+RUN --mount=type=cache,id=dockercli-integration-git-$TARGETPLATFORM,sharing=locked,target=./.git \
     --mount=type=cache,target=/root/.cache/go-build,id=dockercli-integration-build-$TARGETPLATFORM \
         rm -f ./.git/*.lock \
      && /download-or-build-cli.sh ${DOCKERCLI_INTEGRATION_VERSION} ${DOCKERCLI_INTEGRATION_REPOSITORY} /build \
```

**Comment by thaJeztah** [comment]
Unrelated; seen this fail a couple of times; maybe needs a `sudo`

```
Run if [ ! -e /etc/docker/daemon.json ]; then
  if [ ! -e /etc/docker/daemon.json ]; then
   echo '{}' | tee /etc/docker/daemon.json >/dev/null
  fi
  DOCKERD_CONFIG=$(jq '.+{"experimental":true,"live-restore":true,"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' /etc/docker/daemon.json)
  sudo tee /etc/docker/daemon.json <<<"$DOCKERD_CONFIG" >/dev/null
  sudo service docker restart
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GO_VERSION: 1.20.5
    GOTESTLIST_VERSION: v0.3.1
    TESTSTAT_VERSION: v0.1.3
    ITG_CLI_MATRIX_SIZE: 6
    DOCKER_EXPERIMENTAL: 1
    DOCKER_GRAPHDRIVER: overlay2
tee: /etc/docker/daemon.json: Permission denied
Error: Process completed with exit code 1.
```

**Review by neersighted — APPROVED** [review]
Re-affirming LGTM; I'd love to see this in sooner than later because I keep having to apply this locally 😅

**Review by vvoland — APPROVED** [review]

**Pull request merged**
