### PR TITLE
[23.0 backport] builder: handle host-gateway with extra hosts

### PR DESCRIPTION
**Pull request by thaJeztah**
- backport of https://github.com/moby/moby/pull/44537
- fixes https://github.com/moby/moby/pull/44537

(cherry picked from commit 521b8c02cc8912dc05cf178f83ea73b1b77698bd)

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh! This is something we should look into;

```
47 [containerd 3/3] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         PREFIX=/build /install.sh containerd
#47 189.5 + bin/containerd
#47 224.8 # github.com/containerd/containerd/cmd/containerd
#47 224.8 /usr/bin/ld: /tmp/go-link-1156009798/000019.o: in function `New':
#47 224.8 /tmp/tmp.sKLKl4HYkY/src/github.com/containerd/containerd/vendor/github.com/miekg/pkcs11/pkcs11.go:77: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
#47 224.9 + bin/containerd-stress
```

```
warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Comment by crazy-max** [comment]
> Oh! This is something we should look into;
> 
> ```
> 47 [containerd 3/3] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod         PREFIX=/build /install.sh containerd
> #47 189.5 + bin/containerd
> #47 224.8 # github.com/containerd/containerd/cmd/containerd
> #47 224.8 /usr/bin/ld: /tmp/go-link-1156009798/000019.o: in function `New':
> #47 224.8 /tmp/tmp.sKLKl4HYkY/src/github.com/containerd/containerd/vendor/github.com/miekg/pkcs11/pkcs11.go:77: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> #47 224.9 + bin/containerd-stress
> ```
> 
> ```
> warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> ```

Yes this is fixed with https://github.com/moby/moby/pull/44513/commits/756ee376aad1af35553c0fa0de0bf725c73e9db6

**Comment by thaJeztah** [comment]
> Yes this is fixed with https://github.com/moby/moby/commit/756ee376aad1af35553c0fa0de0bf725c73e9db6

I was wondering that indeed 😅

**Comment by thaJeztah** [comment]
All green now 👍

**Pull request merged**
