### PR TITLE
image -f function add 'tag' search options

### PR DESCRIPTION
**Pull request by zhouhao3**
My idea is to be able to execute images -f tag=XXX,This is my general idea,There's a little bit of a problem with the pr, if there is any wrong place, please advise

Signed-off-by: zhouhao zhouhao@cn.fujitsu.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Makes sense to me. Can you add a test?

**Comment by q384566678** [comment]
@cpuguy83 Do you think this test is correct

**Comment by stevvooe** [comment]
Would we add this without adding a `name` filter?

**Comment by q384566678** [comment]
How do you feel about such a change? @cpuguy83 @vdemeester @stevvooe

**Comment by stevvooe** [comment]
Let me say it differently: this doesn't make sense without adding a `name` filter.

**Comment by q384566678** [comment]
I can not understand your point of view,Can you explain in detail ? Where to add a name filter?thank you very much. @stevvooe

**Comment by q384566678** [comment]
You mean to add a name filter, so it is better to use direct docker images name: [tag]
My idea is that when you pull some images, you can identify the classification by TAG, when you want to use that category, you can directly through the tag function to search display @cpuguy83 @vdemeester @GordonTheTurtle @olleolleolle

**Comment by stevvooe** [comment]
@q384566678 I'm not sure I follow. What is the point in adding a tag filter without adding a name filter?

**Comment by vdemeester** [comment]
Agreeing with @stevvooe, we should add a `name` filter if we add a `tag` one :angel:

**Comment by thaJeztah** [comment]
Wondering if a "name" filter is added, would they be combined as "or"? So would

    --filter name=ubuntu --filter tag=latest

Return all images that are either "ubuntu" or have tag "latest"?

**Comment by stevvooe** [comment]
> My idea is that when you pull some images, you can identify the classification by TAG, when you want to use that category, you can directly through the tag function to search display

It sounds like this infers some different model of tagging that the one assumed in docker. There generally aren't relationships between tags of images with different names. For example, there is no assumption that `ubuntu:latest` and `redis:latest` have any relationship expect those were the latest images to be pushed to each repository, respectively. Trying to build relationships, such as a category, using tags, may lead to problems down the road. This would be much better handled by an external metadata system.

It might be better to fold this into a single `name` filter which acts on both the name and tag together (per @thaJeztah's point):

```
--filter name=*:latest
```

We could get somewhat the same behavior as originally requested, while also supporting a tagging model that is more in line with how things actually work.

**Comment by stevvooe** [comment]
@q384566678 Any reason to close this? I think there is definitely a feature gap here. Let me know!

**Comment by q384566678** [comment]
I close it because I have no idea to continue to improve, if you said, add name filter.So : 
  --filter name=ubuntu:latest
If you want to use the name: tag to search the image, you can directly use：
docker images ubuntu：latest
So I do not think it is necessary to do so. @stevvooe

**Pull request closed without merging**
