### PR TITLE
Some check_config enhancement

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @tianon

**Comment by thaJeztah** [comment]
ping @tianon could you have a look at this?

**Comment by tianon** [comment]
LGTM assuming @LK4D4 is OK with the new requirement additions :+1:

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @hqhq !

**Pull request merged**
