### PR TITLE
Removing deprecated notice to update mkdocs.yml in docs README

### PR DESCRIPTION
**Pull request by lerignoux**
Signed-off-by: Laurent Erignoux lerignoux@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
ping @thaJeztah @moxiegirl, we should replace that with the actual workflow :wink:.

**Comment by moxiegirl** [comment]
LGTM @lerignoux  thank you for that.  @vdemeester I actually have an updated one on `docker/compose` I just need time. Even the compose one is slightly out of date.  :-/

**Comment by vdemeester** [comment]
@moxiegirl ok np :wink: If you need help, feel free to ping :blush:

**Comment by moxiegirl** [comment]
@vdemeester Awww, thanks, you should always feel free to make a PR.  Always appreciate help from a contributor with a good eye. :-D

**Comment by vdemeester** [comment]
@moxiegirl yeah that is true :blush:

**Pull request merged**
