### PR TITLE
Fix parsing resources from compose file for stack deploy.

### LINKED ISSUE #29998: Docker 1.13.0-rc5 stack deploy compose resources limits "failed to parse  as a rational number"
Hi

**Description**

Seems Docker deploy it's not parsing compose file properly.

**Steps to reproduce the issue:**
1. docker stack deploy --compose-file test.yml test

```yaml
version: "3"
services:
  test:
    command: "tail -f /var/log/messages"
    deploy:
      resources:
        limits:
          #cpus: "0.001"           #<----------------------uncommenting this, works
          memory: 2G
        #reservations:
          #cpus: "0.0002"
          #memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: "ubuntu:16.04"
```

**Describe the results you received:**

```
Creating network test_default
failed to parse  as a rational number
```

**Describe the results you expected:**

```
To properly deploy the stack
```

**Additional information you deem important (e.g. issue happens only occasionally):**

If "_#cpus: "0.001"_" **uncommented**, everything works as it should

**Output of `docker version`:**

```
Docker version 1.13.0-rc5, build 43cc971
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.13.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: zgu2hkue7e4i3yjq2j4002pv5
 Is Manager: true
 ClusterID: k874fkf2is4uf7668j6n6qpvu
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 155.54.66.85
 Manager Addresses:
  155.54.66.85:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.692 GiB
Name: equipo
ID: QKUC:U2CA:OSHZ:7MDJ:JNVT:7U6S:KAOZ:UGOG:UBOH:EA75:VBHK:QOQG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
uname -a
Linux pc 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

cat /etc/debian_version 
8.6
```

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #29998 for master. See #30004 for 1.13.x fix

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by mostolog** [comment]
Having a quick eye on patch...wouldn't it fail also if cpu but not memory are specified?

**Comment by dnephin** [comment]
I just confirmed that only cpu is fine. It's being convereted from the `types.UnitBytes` type, which is just an alias for int64, so the default zero value is compatible int64.

**Comment by mostolog** [comment]
Thanks!

**Pull request merged**
