### PR TITLE
Fix building gccgo from makefile

### PR DESCRIPTION
**Pull request by tonistiigi**
`make gccgo` didn't use the correct Dockerfile.

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Note: userns is actually green, but GitHub didn't receive the notification; https://jenkins.dockerproject.org/job/Docker-PRs-userns/8260/console

```
18:15:44 Archiving artifacts
18:15:48 Notifying endpoint 'HTTP:https://leeroy.dockerproject.org/notification/jenkins'
18:15:49 Finished: SUCCESS
```

**Comment by vieux** [comment]
@tonistiigi probably not important, but `make gccgo` prints `WARNING! I don't seem to be running in a Docker container.`

We might want to update this line as well: https://github.com/docker/docker/blob/master/hack/make.sh#L40

ping @tianon

**Comment by tianon** [comment]
That line should actually be working since `Dockerfile.gccgo` still uses `/go/src/github.com/docker/docker` :disappointed: (https://github.com/docker/docker/blob/40dc921da21e4f1fd165f1d7da87d600e3eb8609/Dockerfile.gccgo#L73 and https://github.com/docker/docker/blob/40dc921da21e4f1fd165f1d7da87d600e3eb8609/Dockerfile.gccgo#L102)

Regardless, this PR LGTM :+1:

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
@tianon `DOCKER_CROSSPLATFORMS ` is the issue, it's empty 

https://github.com/docker/docker/blob/master/Dockerfile#L136 <- this is nowhere in `Dockerfile.gccgo`

**Comment by tianon** [comment]
Ohhh, it's checking for both.  Maybe it makes sense to just relax that check and not worry too much about people not seeing the warning if they're crazy and happen to use `/go/...`? :smile:  (although that's material for a separate PR, IMO)

**Comment by vieux** [comment]
@tianon agreed.

**Comment by tianon** [comment]
Oh no, that should still be fine, since it's `||`:
```bash
if [ "$PWD" != "/go/src/$DOCKER_PKG" ] || [ -z "$DOCKER_CROSSPLATFORMS" ]; then
```

**Comment by vieux** [comment]
@tianon ?? `$DOCKER_CROSSPLATFORMS` is empty so it enters the if and unsets `inContainer`

**Comment by tianon** [comment]
Doh, right.  Doing way too many things at once, sorry. :disappointed:

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
