### PR TITLE
Skip graphdriver/quota TestBlockDev if dependencies are not available

### PR DESCRIPTION
**Pull request by dnephin**
Previously running this test in the standard docker-dev container (kernel 4.13.12) would result in thousands of lines of dmesg output cluttering the test output, and a test failure.

This change skips the test instead of failing when xfs is not available, and only prints the last 100 liens of dmesg on failure.

I'd also be happy to remove the `dmesg` output entirely, I'm not sure if it's really necessary.

cc @sargun

### CODE REVIEW

**Comment by sargun** [comment]
Previously, the test was written this way, but IIRC, @cpuguy83 had the opinion that this test should be required.

**Review by cpuguy83 — COMMENTED** [review]
I don't remember this... But seems ok to skip I'd xfs is not supported. May also be good to mount directly with unix.Mount... but currently on mobile and don't have the full context for the test at the moment.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by sargun** [comment]
Er, one comment, I think it'd be better to look at `/proc/filesystems` to determine whether the FS is supported or not.

**Comment by dnephin** [comment]
That is an option, but I'm not sure if it's worth doing the extra work to parse that output. Do you expect the mount could fail with different errors?

Any opinions on removing  the `dmesg` output entirely, vs leaving it as-is (last 100 lines) ?

**Comment by dnephin** [comment]
Changes to skip the test when `/proc/fs/xfs` doesn't exist.

**Comment by sargun** [comment]
@dnephin Slight suggestion - Try calling out modprobe xfs, as sometimes people don't have this compiled in, and it only gets loaded on demand. Or short circuit only if after the mount command `/proc/fs/xfs` doesn't exist.

**Comment by dnephin** [comment]
The mount command would have already failed, so doing it after the mount command would mean going back to my original version which checks the error string from `mount`.

I don't think it's ok to `modprobe` in a test suite.

**Comment by dnephin** [comment]
I changed this around, so the `/proc/fs/xfs` check is only done after the mount fails.

**Comment by sargun** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐹

**Pull request merged**
