### PR TITLE
Bump 1.8.2.

### PR DESCRIPTION
**Pull request by calavera**
Track changes for 1.8.2.

Release scheduled for Thrusday, September 10th.

### CODE REVIEW

**Comment by mavenugo** [comment]
@calavera cherry-pick of https://github.com/docker/docker/issues/15601 needs a bit more attention. Since this is a vendor package upgrade, can you please run `hack/vendor.sh`which will bring in few more changes to the netlink package which is missing in the cherry-pick.
Once you run `hack/vendor.sh`, the netlink package will be inline with the docker master.

**Comment by calavera** [comment]
@mavenugo so far, the changes in this branch are consistent with #15601. Please, feel free to point me to another changeset to cherry pick if that's not a complete fix. I won't definitely run `hack/vendor.sh` in this branch.

**Comment by mavenugo** [comment]
@calavera ok. the other part of the netlink upgrade came from : https://github.com/docker/docker/pull/15584. We just need the netlink code to be updated.

**Comment by moxiegirl** [comment]
@calavera Since the 1.8.0 release, there have been cherry-picks into docs.   You'll need to make sure that you include all these in this new bump.

To see what has been cherry-picked into `docs` since the last major release:

https://github.com/docker/docker/commits/docs

Can you confirm all this is includede?

**Comment by calavera** [comment]
@moxiegirl I was thinking about leaving the docs branch as it is, so we don't have to add more cherry picking to the list.

**Comment by moxiegirl** [comment]
@calavera Yay! works for me thank you sir.

**Comment by jfrazelle** [comment]
We have pushed 1.8.2-rc1 https://github.com/docker/docker/releases/tag/1.8.2-rc1

**Comment by tianon** [comment]
@jfrazelle is that tag missing the `v` prefix on purpose? (ie previous tags, https://github.com/docker/docker/tags)

**Comment by jfrazelle** [comment]
ah boooo

**Comment by jfrazelle** [comment]
fixed https://github.com/docker/docker/releases/tag/v1.8.2-rc1

**Comment by jfrazelle** [comment]
now to find what was wrong w copy paste from release checklist :/

**Comment by icecrime** [comment]
RC1 is up (thanks @calavera  and @jfrazelle) :tada:

> RPMs/DEBs: curl -sSL https://test.docker.com | sh
> Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.8.2-rc1
> Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.8.2-rc1
> Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.8.2-rc1
> Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.8.2-rc1.tgz
> Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.8.2-rc1.exe
> Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.8.2-rc1.exe

**Comment by achanda** [comment]
@icecrime the link to draft changelog is broken

**Comment by icecrime** [comment]
Ah interesting, apparently you need write access to a repo to read a draft release :cry: Well...

## Distribution:

- Fixes rare edge case of handling GNU LongLink and LongName entries.
- Avoid buffering to tempfile when pushing to registry V2.
- Fix ^C on docker pull.
- Fix docker pull issues on client disconnection.
- Fix issue that caused the daemon to panic when loggers weren't configured properly.
- Fix goroutine leak pulling images from registry V2.

## Runtime:

- Fix a bug mounting cgroups for docker daemons running inside docker containers.
- Initialize log configuration properly.

## Client:

- Handle -q flag in docker ps properly when there is a default format.

## Networking:

- Fix several corner cases with netlink.
- Fixed an incorrect network namespace switch issue.

## Contrib:

- Fix several issues with bash completion.

**Comment by marcogallotta** [comment]
> Avoid buffering to tempfile when pushing to registry V2.

It doesn't look like this was actually cherry-picked?

**Comment by calavera** [comment]
@achanda, @icecrime the good release tag is https://github.com/docker/docker/releases/tag/v1.8.2-rc1.

**Comment by ibuildthecloud** [comment]
Running into some issues, docker-in-docker w/ `--pid=host` is failing for different reasons now.  I'll be troubleshooting this issue further to determine if it's my environment or an issue in 1.8.

**Comment by ibuildthecloud** [comment]
DIND w/ `--pid=host` is a no-go.  Just filed an issue https://github.com/docker/docker/issues/16206

@LK4D4

**Comment by jfrazelle** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
