### PR TITLE
[20.10] errdefs: move GetHTTPErrorStatusCode to api/server/httpstatus

### PR DESCRIPTION
**Pull request by dims**
Request to cherry pick https://github.com/moby/moby/pull/43399 to the 20.10 branch

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like there's a failure that may be legit (looking from my phone, so haven't checked further);

```
[2022-03-22T20:47:34.990Z] ERRO Running error: buildssa: analysis skipped: errors in package: [/go/src/github.com/docker/docker/errdefs/http_helpers.go:38:19: undeclared name: fmt -: could not load export data: no export data for "github.com/docker/docker/errdefs"]

**Comment by thaJeztah** [comment]
I think you'll have to cherry-pick https://github.com/moby/moby/commit/24aaa7f8c9c948f58e1326a044ae8978b0b19f1f (https://github.com/moby/moby/pull/42999) as well (before the one you cherry-picked) to fix the failure.

**Comment by dims** [comment]
Thanks for the tip @thaJeztah. I've updated this now!.

**Review by thaJeztah — APPROVED** [review]
it builds, ship it! 😂 

without joking: LGTM, but I'd prefer others to have a look as well as I'm biased (being the original author)

**Comment by thaJeztah** [comment]
@tianon @cpuguy83 @AkihiroSuda let me know if you're ok with this patch for a patch release

**Comment by dims** [comment]
@AkihiroSuda this one is in the same boat as the other one : https://github.com/moby/moby/pull/43407#issuecomment-1076414170

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
thanks! let me get this one in

**Pull request merged**
