### PR TITLE
Allow SEO crawling from docs site

### PR DESCRIPTION
**Pull request by nathanleclaire**
I think it should be this way instead, perhaps there is a reason to not index the content I have overlooked though.  cc @jfrazelle @crosbymichael does it look good to you?

Signed-off-by: Nathan LeClaire nathan.leclaire@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
hmmmm ya I think that should be fine ping @tianon LGTM

**Comment by tianon** [comment]
I think this was to prevent robots from scraping the `master` docs, actually (since those can be confusing when you're actually running a release).

@SvenDowideit would actually be the one to ask, not me. :+1:

**Comment by nathanleclaire** [comment]
Interesting point @tianon  - I don't know much about the deploy / staging process so it'd be good to get some input on the thread from someone who is, but perhaps we can include a check like https://github.com/nathanleclaire/docker/blob/bots_are_our_friends/docs/release.sh#L124 to conditionally disallow or allow based on whether you're going to "real prod" or not.

**Comment by jfrazelle** [comment]
we figured it out, it was in my cleanup a mistake :( sorry guys

**Comment by nathanleclaire** [comment]
OK I've updated to be how it was before -- caveat that I haven't actually run the script.  @tianon @jfrazelle does the syntax and logic LGTY?

**Comment by nathanleclaire** [comment]
Update: there was already a check to make sure we don't push dev docs to docs.docker.com in main so I took it out of this function

**Comment by jfrazelle** [comment]
I'll try it out :)

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @tiborvass

**Comment by tiborvass** [comment]
LGTM

I could be nitpicking though to ask for `<<-'EOF'` and indent the contents :)

**Comment by jfrazelle** [comment]
ping @tianon :D

**Comment by nathanleclaire** [comment]
> indent the contents :)

Will `robots.txt` work if there is indentation before the directives in the file though?

> I could be nitpicking though to ask for <<-'EOF' and indent the contents :)

This would replace the top EOF in the blocks?  Why? (my bash fu fail me here)

**Comment by tiborvass** [comment]
If you add the `-` then it will remove indentation

**Comment by tiborvass** [comment]
```
#!/bin/bash
if true; then
	cat <<-'EOF'
	hello world
	EOF
fi
```

**Comment by nathanleclaire** [comment]
Ah.  Yes I'd rather do that.  I will update

**Comment by nathanleclaire** [comment]
OK updated!  @tiborvass @jfrazelle let me know if there are any more issues.

**Comment by jfrazelle** [comment]
trying now

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
thanks @nathanleclaire !

**Comment by nathanleclaire** [comment]
:+1:

**Comment by moxiegirl** [comment]
LGTM

**Comment by nathanleclaire** [comment]
:confetti_ball: :balloon:  :tada:

**Comment by thaJeztah** [comment]
Thanks for spotting this, @nathanleclaire!

**Pull request merged**
