### PR TITLE
Update container-device-interface to v0.6.2

### PR DESCRIPTION
**Pull request by elezar**
**- What I did**

Updated the CDI (container-orchestrated-devices) dependency to v0.6.2 which includes moving the CDI specs to a separately versioned go submodule.

**- How I did it**
Replaced the `github.com/container-orchestrated-devices/container-device-interface` imports and module entries with `tags.cncf.io/container-device-interface` and bumped version to `v0.6.2`. Updated vendoring.

**- How to verify it**

Changes are limited to import and vendoring changes.

**- Description for the changelog**

Updated tags.cncf.io/container-device-interface to v0.6.2

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hm.. looks very unrelated, but never seen this error before (probably a glitch, I'll give CI a kick);

```
 > [integration-tests-base  3/18] RUN apk add --no-cache nodejs npm   && npm install -g azurite@3.18.0:
1.676 *
1.676 (3/5) Installing icu-libs (73.2-r2)
1.764 (4/5) Installing nodejs (18.18.2-r0)
2.482 (5/5) Installing npm (9.6.6-r0)
2.975 Executing busybox-1.36.1-r2.trigger
2.995 OK: 570 MiB in 83 packages
14.29 npm ERR! code E409
14.32 npm ERR! 409 Conflict - GET https://registry.npmjs.org/args
14.32 
14.33 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-04T00_10_14_476Z-debug-0.log
```

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
We probably need a PR in containerd as well (at least for "v2"); it looks like it's still on v0.6.1; https://github.com/containerd/containerd/blob/bd2db42464d7f0897b72a3859636b4a0af5b7c7e/go.mod#L12

**Comment by elezar** [comment]
Thanks. The containerd updates are on my todo list.

**Pull request merged**
