### PR TITLE
pkg: chrootarchive: chroot_linux: fix docker build

### LINKED ISSUE #22587: Error cleaning up after pivot: remove /var/lib/docker/tmp/docker-builder113372687/.pivot_root936443744: no such file or directory
**Output of `docker version`:**

```
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.1
 Git commit:   08ec360
 Built:        Sun May  8 12:39:42 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.1
 Git commit:   08ec360
 Built:        Sun May  8 12:39:42 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
docker info
Containers: 30
 Running: 0
 Paused: 0
 Stopped: 30
Images: 138
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.2-302.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44 GiB
Name: localhost.localdomain
ID: JQDM:ZDU3:BYSR:SIMJ:QGDH:GBGW:MF7Q:VYLQ:UYFD:W5KY:H4WG:PIMF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 25
 System Time: 2016-05-08T12:42:03.783123312+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 localhost
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. `make`
2.
3.

**Describe the results you received:**
```
$ make
docker build  -t "docker-dev:master" -f "Dockerfile" .
Sending build context to Docker daemon 196.1 MB
Error response from daemon: Untar re-exec error: exit status 1: output: Error cleaning up after pivot: remove /var/lib/docker/tmp/docker-builder606958863/.pivot_root892405879: no such file or directory
Makefile:67: recipe for target 'build' failed
make: *** [build] Error 1**
```

**Describe the results you expected:**
`make` works

**Additional information you deem important (e.g. issue happens only occasionally):**
Reverting https://github.com/docker/docker/pull/22506 makes this working again.

### PR DESCRIPTION
**Pull request by runcom**
The path we're trying to remove doesn't exist after a successful
chroot+chdir because a / is only appended after pivot_root is
successful and so we can't cleanup anymore with the old path.
Also fix leaking .pivot_root dirs under /var/lib/docker/tmp/docker-builder*
on error.

Fix https://github.com/docker/docker/issues/22587
Introduced by https://github.com/docker/docker/pull/22506

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by LK4D4** [comment]
It looks okay for me.
LGTM

**Comment by cpuguy83** [comment]
Not sure I understand why it's a problem since this is removed in its own process before it ever returns from calling `chroot`.

**Comment by runcom** [comment]
> Not sure I understand why it's a problem since this is removed in its own process before it ever returns from calling chroot.

that's my conclusion as well - though, I'm constantly getting this and (still to be understood) somehow, somewhere the dir gets removed before that os.Remove

**Comment by LK4D4** [comment]
We can find it if we check for specific string in os.Remove directly and panic there :)

**Comment by runcom** [comment]
yup, just talked to @cpuguy, gonna test this out more

**Comment by runcom** [comment]
so it seems pivot_root fails on my box and chroot is successfull -> then that path doesn't exists in the new root (my guess)

**Comment by runcom** [comment]
this is also leaking empty `.pivot_root` directories under `/var/lib/docker/tmp/docker-builder*/.pivot_root*`

**Comment by runcom** [comment]
so the problem is that if chroo+chdir is successful you can't remove `pivotDir` (the original one) but you need the one at https://github.com/docker/docker/pull/22603/files#diff-5747d7484fa2318ee40d993d08fcfe53R65 ...

**Comment by cpuguy83** [comment]
Ah, good catch.
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by runcom** [comment]
there seems to be something not yet correct here:
```
$ sudo systemctl stop docker
$ sudo rm -rf /var/lib/docker 
rm: cannot remove '/var/lib/docker/tmp/docker-builder054675383': Device or resource busy
```

**Comment by runcom** [comment]
probably because we unshare mnt ns and mount path..

**Pull request merged**
