### PR TITLE
Make docker stack deploy (and docker service update) more idempotent

### PR DESCRIPTION
**Pull request by vdemeester**
Sort some slice fields before sending them to the swarm api so that it won't trigger an update. This is the server side implementation of #29732, against `master` (so to be cherry-picked).

Closes #29732 if merged.

---

Make sure running multiple times `docker stack deploy --compose-file docker-compose.yml foo` on the same unchanged file doesn't update the services each times. This is mainly due to the use of `map` .

This is related to #29676

You can reproduce and validate this using the following compose file or playing with flag order on `docker service update`.

```yaml
version: "3.0"

services:
  test:
    image: busybox
    command: top
    extra_hosts:
      - foo:1.1.1.1
      - bar:2.2.2.2
    environment:
      - FOO=BAR
      - FAR=BOO
    ports:
      - "5000:80"
      - "5001:81"
    networks: [front-tier, back-tier]

networks:
  front-tier:
  back-tier:
```

This also helps with `Error response from daemon: rpc error: code = 2 desc = changing network in service is not supported` when you didn't change the networks.

/cc @thaJeztah @dnephin @icecrime @cpuguy83 @aaronlehmann @aanand 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
My preference is to do this sorting on the client side (as in #29732), not on the server side. We have a convention that everything inside `Spec` is considered user data and isn't modified except as necessary for serialization/deserialization. Sorting on the server side isn't the worst thing we could do, but does deviate from this convention, and could introduce some corner cases (for example, a client might think it is looking at stale data if the sorting changes the order of the fields relative to what it submitted). Doing this at the engine API level would also introduce an inconsistency between the gRPC API and the engine API, and we try to avoid those.

cc @stevvooe

> This also helps with `Error response from daemon: rpc error: code = 2 desc = changing network in service is not supported` when you didn't change the networks.

This may be a swamkit bug in `controlapi`. I suspect it shouldn't reject the update if the list of networks is the same, and only the ordering has changed. This probably wasn't considered when adding the check, since the restriction was intended as a temporary stopgap.

**Comment by LK4D4** [comment]
I'm with @aaronlehmann here

**Comment by thaJeztah** [comment]
Me too; was discussing with @vdemeester earlier and it makes sense with @aaronlehmann's explanation

**Review by dnephin — COMMENTED** [review]
design LGTM

**Comment by vdemeester** [comment]
Closing based on the comment. Quoting @thaJeztah 👼 "Client side sorting doesn't prevent us from doing it on the daemon at some point".

**Pull request closed without merging**
