### PR TITLE
Blacklist zfs with overlay

### LINKED ISSUE #10313: Overlay does not work with zfs backed /var/lib/docker
Seems to be the same issue as: #9820 

I know the resolution was to add a message, may want to also add a message for this scenario though I don't know how popular ZFS is on linux.

Containers: 0
Images: 5
Storage Driver: overlay
Execution Driver: native-0.2
Kernel Version: 3.18.2-2-ARCH
Operating System: Arch Linux
CPUs: 8
Total Memory: 23.55 GiB
ID: CFFY:XV6I:5J5P:7MAN:YGGK:E5T2:W23N:H72E:D43D:ZXCK:IUDI:BNI2
WARNING: No swap limit support

INFO[0113] -job pull(ubuntu, latest) = OK (0)
DEBU[0125] Calling POST /containers/create
INFO[0125] POST /v1.16/containers/create
INFO[0125] +job create()
invalid argument
INFO[0126] -job create() = ERR (1)
ERRO[0126] Handler for POST /containers/create returned error: invalid argument
ERRO[0126] HTTP Error: statusCode=500 invalid argument

### PR DESCRIPTION
**Pull request by jessfraz**
Fixes #10313

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by unclejack** [comment]
LGTM

**Comment by crossan007** [comment]
is zfs as a backing filesystem still blacklisted on overlay2?

**Pull request merged**
