### PR TITLE
Vendor libnetwork#1473

### PR DESCRIPTION
**Pull request by mavenugo**
This fixes one of the issues seen during debugging a docker issue.
@mrjana to add more details.

### CODE REVIEW

**Comment by mrjana** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by mlaventure** [comment]
@mrjana could you add a comment with exactly what's being fixed for future reference?

Thanks!

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
@mrjana don't forget to add a comment as @mlaventure suggested, thanks.

**Pull request merged**
