### PR TITLE
Fix use of cap in MultiReadSeeker; possible data corruption bug.

### PR DESCRIPTION
**Pull request by tomwilkie**
**- What I did**

Tried to use MultiReadSeeker; hit a possible data corruption bug.

**- How I did it**

See my usage here: https://github.com/weaveworks/cortex/pull/142/files#diff-e179054c3d912cc0aaa6f11efb991521R72

Was building a reader out of multiple smaller readers; noticed that results from reading this reader were invalid.

This is due to MultiReadSeeker.Read using the passed in buffers capacity and not length, in violation of the [Read contract](https://golang.org/pkg/io/#Reader):

> Read reads up to **len(p)** bytes into p.

**- How to verify it**

I've added a test (`TestMultiReadSeekerSmallReads`) which fails without this change.

### CODE REVIEW

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Minor nit in var naming, but I think this looks good.

**Comment by tomwilkie** [comment]
(re pushed with DCO)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
Discussed with @tonistiigi and probably won't hurt to cherry pick this into 1.13

**Pull request merged**
