### PR TITLE
Disable ANSI emulation in certain windows shells

### PR DESCRIPTION
**Pull request by ahmetb**
This disables recently added ANSI emulation feature in certain Windows
shells (like ConEmu) where ANSI output is emulated by default with builtin
functionality in the shell.

MSYS (mingw) runs in cmd.exe window and it doesn't support emulation.

Cygwin doesn't even pass terminal handles to docker.exe as far as I can
tell, stdin/stdout/stderr handles are behaving like non-TTY. Therefore not
even including that in the check.

Signed-off-by: Ahmet Alp Balkan ahmetalpbalkan@gmail.com
cc: @sachin-jayant-joshi @tiborvass @icecrime

### CODE REVIEW

**Comment by jfrazelle** [comment]
do we need this for 1.6

**Comment by ahmetalpbalkan** [comment]
@jfrazelle yes yes yes that'd be super nice. if things go horribly wrong people this code will behave like a security switch and when people use ConEmu shell, the new windows ANSI term code recently merged won't be called at all.

**Comment by jfrazelle** [comment]
code changes LGTM just waiting on janky

**Comment by jfrazelle** [comment]
we can ignore the `TestPullVerified` failure

**Comment by cpuguy83** [comment]
I don't have a system to test on, but code LGTM

**Pull request merged**
