### PR TITLE
Add test coverage for pkg/pools (#11588)

### LINKED ISSUE #11588: pkg/pools - Test coverage
**Problem**
 
pkg/pools - Test coverage
 
**Solution**
 
The `pkg/pools` package is used by Docker archive management, yet the package has no test coverage.
 
Improve test coverage on the `pkg/pools` package. You can use the following commands to measure progress:
 
    cd pkg/pools
    go test -cover -coverprofile /dev/stderr 2>&1 >/dev/null | go tool cover -func /dev/stdin

### PR DESCRIPTION
**Pull request by vdemeester**
Add some tests to `pkg/pools`, related to #11588 – increase the coverage from 0 to 100% :smile_cat:.

I'm not sure all my tests are great, so reviews are more than welcome !

Signed-off-by: Vincent Demeester vincent@sbr.pm

Closes #11588

### CODE REVIEW

**Comment by runcom** [comment]
SGTM if janky's happy

**Comment by vdemeester** [comment]
Is it me or Janky is taking a *looonnng* time :open_mouth: (more than 35min a build)

**Comment by vdemeester** [comment]
> Build timed out (after 45 minutes). Marking the build as aborted.

@jfrazelle Something is wrong with Janky ? He looks tired :tired_face:

**Comment by duglin** [comment]
he just misses you

**Comment by unclejack** [comment]
@vdemeester I've restarted the build on janky. Let's see how it goes.

**Comment by vdemeester** [comment]
@unclejack Thanks :smile:, but timout again :sob: 
@duglin probably :wink:

**Comment by runcom** [comment]
```
---> Making bundle: test-docker-py (in bundles/1.7.0-dev/test-docker-py)
+++ exec docker --daemon --debug --host unix:///go/src/github.com/docker/docker/bundles/1.7.0-dev/test-docker-py/docker.sock --storage-driver vfs --exec-driver native --pidfile /go/src/github.com/docker/docker/bundles/1.7.0-dev/test-docker-py/docker.pid --userland-proxy=true
..........EE..EE..............................Build timed out (after 45 minutes). Marking the build as failed.
```
seems like it timeouts in test-docker-py after some errors (?)

**Comment by unclejack** [comment]
@runcom It looks like integration-cli is taking too long: `ok  	github.com/docker/docker/integration-cli	2355.231s`

**Comment by vdemeester** [comment]
First time :
```
---> Making bundle: test-docker-py (in bundles/1.7.0-dev/test-docker-py)
+++ exec docker --daemon --debug --host unix:///go/src/github.com/docker/docker/bundles/1.7.0-dev/test-docker-py/docker.sock --storage-driver vfs --exec-driver native --pidfile /go/src/github.com/docker/docker/bundles/1.7.0-dev/test-docker-py/docker.pid --userland-proxy=true
...........Build timed out (after 45 minutes). Marking the build as failed.
Build timed out (after 45 minutes). Marking the build as aborted.
Build was aborted
```

Second time : 
```
---> Making bundle: test-docker-py (in bundles/1.7.0-dev/test-docker-py)
+++ exec docker --daemon --debug --host unix:///go/src/github.com/docker/docker/bundles/1.7.0-dev/test-docker-py/docker.sock --storage-driver vfs --exec-driver native --pidfile /go/src/github.com/docker/docker/bundles/1.7.0-dev/test-docker-py/docker.pid --userland-proxy=true
..........EE..EE..............................Build timed out (after 45 minutes). Marking the build as failed.
Build timed out (after 45 minutes). Marking the build as aborted.
Build was aborted
```

I'm wondering why it's taking so long for the integration test (Just added some unit tests).

**Comment by runcom** [comment]
@unclejack uhm unless I'm hitting the wrong button
```
OK: 669 passed, 1 skipped
PASS
```
so integration-cli is indeed already finished, what am  I missing?

**Comment by unclejack** [comment]
@runcom @vdemeester The system running the build seems to be having some troubles. The 2355 seconds (39m15s) required for the integration-cli execution is telling me that the 45 minutes timeout is reached during the docker-py tests.

**Comment by LK4D4** [comment]
maybe something with hub

**Comment by vdemeester** [comment]
hum :cry: .. Most of the build are ok, although there is something at the end of somes :

https://jenkins.dockerproject.com/job/Docker-PRs/8077/console
```
Error response from daemon: no such id: docker-pr8077
time="2015-05-15T17:15:14-04:00" level=fatal msg="Error: failed to remove one or more containers" 
docker: "rmi" requires a minimum of 1 argument. See 'docker rmi --help'.
```

**Comment by vdemeester** [comment]
Ok, just rebased it against master and push to see if it buils ok this moring (in France) and yay \o/

**Comment by crosbymichael** [comment]
@unclejack janky happy, can you please review this one?

**Comment by vdemeester** [comment]
anybody ? :sob:

**Comment by unclejack** [comment]
@crosbymichael @vdemeester Thanks, I'll review today.

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
100% indeed
LGTM

**Pull request merged**
