### PR TITLE
[20.10] Bump hcsshim for error details fix

### PR DESCRIPTION
**Pull request by cpuguy83**
This pulls in fixes from the moby branch for hcsshim that 20.10 uses.
Not bumping up to the latest release because the diff is huge.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Error is due to error string matching no longer working since the returned error no longer contains the container command, tracking this in https://github.com/moby/moby/pull/42270

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tonistiigi @tianon ptal

**Review by AkihiroSuda — APPROVED** [review]

**Comment by joelavoie7881** [comment]
`` #42582

**Pull request merged**
