### PR TITLE
Zsh completion updates and improvements

### PR DESCRIPTION
**Pull request by sdurrheimer**
Zsh completion update for the following commits:
- [respect -H in bash completion](https://github.com/docker/docker/commit/db5b4a2a69064c803fea249a0983dbbcb4564717)
- [Add new logging driver: fluentd](https://github.com/docker/docker/commit/361a582ba0bccea04a8ea1799e68779fa66abb9f)
- [Flag Addition: --type flag added for docker inspect command](https://github.com/docker/docker/commit/2cb74e691538351efbdee7a78be6535f22c5d024)

In addition, some Shell script improvements

@tianon @jfrazelle

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM unsure if this needs 4 commits tho can you squash also ping @bfirsh Who I believe uses zsh

**Comment by thaJeztah** [comment]
Also ping @vincentbernat and @felixr because they maintain this at https://github.com/felixr/docker-zsh-completion

**Comment by vincentbernat** [comment]
I think there are a lot of changes in the last commit that are not needed at all.

 - There are a lot of excessive quoting (and maybe this is the cause of using `${array[@]}` in the first place). As zsh almost never execute word splitting (with the exception of `$()`), those quotes are not needed and `$array` can be used directly.
 - For spaces between function names and parentheses, it seems the usual way would be to use a space
 - `=` is already matching correctly the provided pattern: `emulate zsh -c '[[ stopped = (stopped|started) ]]'`

And the remaining contain some cosmetic changes that would be better in a separate commit.

**Comment by sdurrheimer** [comment]
> There are a lot of excessive quoting (and maybe this is the cause of using `${array[@]}` in the first place). As zsh almost never execute word splitting (with the exception of `$()`), those quotes are not needed and `$array` can be used directly.

You're right, maybe I shouldn't make it more POSIX compliant since this script is only used by zsh.

> For spaces between function names and parentheses, it seems the usual way would be to use a space

Most of functions have not been declared with a space between function names and parentheses. 

I changed those with spaces to be more consistent.
> `=` is already matching correctly the provided pattern: `emulate zsh -c '[[ stopped = (stopped|started) ]]'`

Same as the first comment.

As for the separate cosmetic commit, those commits will be squashed as requested above. So I think it doesn't matter much.

**Comment by vincentbernat** [comment]
❦ 13 juillet 2015 07:24 -0700, Steve Durrheimer <notifications@github.com> :

>>     There are a lot of excessive quoting (and maybe this is the cause
>>     of using ${array[@]} in the first place). As zsh almost never
>>     execute word splitting (with the exception of $()), those quotes
>>     are not needed and $array can be used directly.
>
> You're right, maybe I shouldn't make it more POSIX compliant since
> this script is only used by zsh.

Moreover, arrays are not POSIX.

>>     For spaces between function names and parentheses, it seems the
>>     usual way would be to use a space
>
> Most of functions have not been declared with a space between function
> names and parentheses. 

Oh, OK then.

>>     = is already matching correctly the provided pattern: emulate zsh -
>>     c '[[ stopped = (stopped|started) ]]'
>
> Same as the first comment.

`[[` is not POSIX either. ;-)

> As for the separate cosmetic commit, those commits will be squashed as
> requested above. So I think it doesn't matter much.

I think that cosmetic changes should still be in a separate commit since
it is not related at all with the remaining, feature-wise. @jfrazelle,
would that be OK?
-- 
Seeing that death, a necessary end,
Will come when it will come.
		-- William Shakespeare, "Julius Caesar"

**Comment by jfrazelle** [comment]
sgtm thanks!

**Comment by jfrazelle** [comment]
also thanks so much for reviewing i dont use zsh soooo thinngs slip by :)

**Comment by sdurrheimer** [comment]
I didn't mean strict compliance but nevermind. I did the change and I have split le last commit into two.

**Comment by vincentbernat** [comment]
The first commit needs the last part of the second commit. Otherwise, OK for me.

**Comment by sdurrheimer** [comment]
Yep I have seen it, was waiting for the build to finish.

**Comment by jfrazelle** [comment]
ok now we are at 5 commits can we make at most 2?

**Comment by vincentbernat** [comment]
@sdurrheimer I didn't notice there was so much changes in completion since the last time I looked. Notably, #14074 is quite a mess. I don't think I am up to really review anything. Since previous changes were done in one commit, I don't object that you squash everything into a single commit.

**Comment by jfrazelle** [comment]
Sorry about that. Let me know what we can do to help.

**Comment by sdurrheimer** [comment]
I think I don't understand, is contributing to this problematic ? Since I was contributing docker-composes' zsh completion, I was thinking I can help here too.

**Comment by jfrazelle** [comment]
no we need contributors and maintainers :)

**Comment by thaJeztah** [comment]
@sdurrheimer your contribution is very welcome! As @vincentbernat explained, there are quite some changes since he last looked at this file, so he needs a bit of time to catch up with those changes. And, yes, we can use more "eyes" on these scripts for review.

In the meantime, could you squash down your commits to two commits (one of them just containing the cosmetically changes)? Thanks!

**Comment by vincentbernat** [comment]
@sdurrheimer You are definitely welcome to contribute. You made a lot of changes and I just failed to comment in due time on some of them. It is my loss and it shouldn't prevent you to do more contributions as it is important to keep the completion up-to-date. Your work is appreciated!

**Comment by albers** [comment]
@vincentbernat Can you please be more specific about what you dislike in the recent changes?
Are your concerns about commit granularity? Are they about style (something like not using zsh idioms)?
I think the point is that most of us are not really familiar with zsh hacking. We would really appreciate your expert advice here just to set us on the right track. Maybe you can point us to some style guide or recommended reading.

**Comment by vincentbernat** [comment]
Mostly commit granularity. Looking at the diff, I was thinking that everything was changed, but in fact, there was some reordering, some "massive" (but good) changes (using `(-s --long)` everywhere), more options added, some misc feature changes. I do understand that the project doesn't want to have too many commits inside the `contrib/` branch, but this makes hard to review changes (and later, to pinpoint problems).

And unfortunately, I am no ZSH expert either (notably on completion which is still like black magic for me). I just appreciate deeply nested argument expansions (which is another form of black magic).

**Comment by jfrazelle** [comment]
LGTM thanks

**Comment by thaJeztah** [comment]
Thanks for your contribution @sdurrheimer !

**Pull request merged**
