### PR TITLE
Better logging for errors in some tests

### PR DESCRIPTION
**Pull request by cpuguy83**
Added stdout/stderr to some of the error messages

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by icecrime** [comment]
I don't know about those experimental failures, do you?

```
10:34:28 FAIL: docker_experimental_network_test.go:326: DockerNetworkSuite.TestDockerNetworkIpvlanAddressing
10:34:28 
10:34:28 docker_experimental_network_test.go:340:
10:34:28     c.Assert(out, checker.Contains, "default via 2001:db8:abca::254 dev eth0")
10:34:28 ... obtained string = "" +
10:34:28 ...     "fe80::/64 dev eth0  metric 256 \n" +
10:34:28 ...     "unreachable default dev lo  metric -1  error -101\n" +
10:34:28 ...     "ff00::/8 dev eth0  metric 256 \n" +
10:34:28 ...     "unreachable default dev lo  metric -1  error -101\n"
10:34:28 ... substring string = "default via 2001:db8:abca::254 dev eth0"
10:34:28 
10:34:29 
10:34:29 ----------------------------------------------------------------------
10:34:29 FAIL: docker_experimental_network_test.go:213: DockerNetworkSuite.TestDockerNetworkIpvlanL2MultiSubnet
10:34:29 
10:34:29 docker_experimental_network_test.go:234:
10:34:29     c.Assert(err, check.IsNil)
10:34:29 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8203a6260), Stderr:[]uint8(nil)} ("exit status 1")
10:34:29 
10:34:31 
10:34:31 ----------------------------------------------------------------------
10:34:31 FAIL: docker_experimental_network_test.go:267: DockerNetworkSuite.TestDockerNetworkIpvlanL3MultiSubnet
10:34:31 
10:34:31 docker_experimental_network_test.go:289:
10:34:31     c.Assert(err, check.IsNil)
10:34:31 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc821a86d60), Stderr:[]uint8(nil)} ("exit status 1")
```

**Comment by cpuguy83** [comment]
I don't know, but I think we found some more places that need extra logging :)

**Comment by cpuguy83** [comment]
pushed an update that makes `dockerCmdWithError` append the output to the error if there is an error.
This was `c.Assert(err, checker.IsNil)` will actually print a helpful message

**Comment by icecrime** [comment]
Consistent failure here:

```
20:46:21 FAIL: docker_cli_run_test.go:77: DockerSuite.TestRunExitCodeOne
20:46:21 
20:46:21 docker_cli_run_test.go:80:
20:46:21     c.Fatal(err)
20:46:21 ... Error: exit status 1: 
```

**Comment by cpuguy83** [comment]
Don't know why that's changed, but it's not a proper check anyway.
It's checking that `err` is not nil, and then checking that `err.Error()` is `exit status 1`, and then checking that the exit code is 1.
The value of `err.Error()` doesn't matter here, and is not even set by the CLI. So just updating this to remove the check.

**Comment by cpuguy83** [comment]
all :green_heart:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
