### PR TITLE
Cleanup compose convert error messages

### PR DESCRIPTION
**Pull request by dnephin**
* error when the secret isn't defined in the Compose file
* include the service name in error messages

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Comment by nathanleclaire** [comment]
Awesome @dnephin ! Thanks

**Comment by thaJeztah** [comment]
Adding label "changelog", see https://github.com/moby/moby/issues/32822

**Pull request merged**
