### PR TITLE
Remove Ubuntu 14.10 (Utopic Unicorn) from build-deb targets

### PR DESCRIPTION
**Pull request by tianon**
As of July 23, 2015, it is officially EOL (https://lists.ubuntu.com/archives/ubuntu-announce/2015-July/000198.html) and will receive no further updates.

### CODE REVIEW

**Comment by tianon** [comment]
cc @jfrazelle

**Comment by jfrazelle** [comment]
we need the generate script too ;)

**Comment by tianon** [comment]
There's nothing utopic-specific in the generator script, is there?

**Comment by tianon** [comment]
https://github.com/docker/docker/blob/2084eee02c49fba22b2396abc626c1e6c7fc8ec2/contrib/builder/deb/generate.sh

Only precise and wheezy specific exceptions from what I can see there.

**Comment by jfrazelle** [comment]
oh duh nice

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
