### PR TITLE
[WIP] Bump docker-py to 4.0.1+

### PR DESCRIPTION
**Pull request by thaJeztah**
update the docker-py tests to use the latest release https://github.com/docker/docker-py/releases/tag/4.0.1

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @shin- @ulyssessouza PTAL

**Comment by thaJeztah** [comment]
Getting some errors; @shin- @ulyssessouza ptal if those need fixing;

```
16:52:29 ==================================== ERRORS ====================================
16:52:29 _____ ERROR at setup of AttachContainerTest.test_attach_stream_and_cancel ______
16:52:29 Error evaluating 'xfail' expression
16:52:29     
16:52:29      ^
16:52:29 SyntaxError: invalid syntax
16:52:29 ________________ ERROR at setup of TestStore.test_store_and_get ________________
16:52:29 /docker-py/tests/integration/credentials/store_test.py:31: in setup_method
16:52:29     raise Exception('No supported docker-credential store in PATH')
16:52:29 E   Exception: No supported docker-credential store in PATH
16:52:29 _______________ ERROR at setup of TestStore.test_get_nonexistent _______________
16:52:29 /docker-py/tests/integration/credentials/store_test.py:31: in setup_method
16:52:29     raise Exception('No supported docker-credential store in PATH')
16:52:29 E   Exception: No supported docker-credential store in PATH
16:52:29 _______________ ERROR at setup of TestStore.test_store_and_erase _______________
16:52:29 /docker-py/tests/integration/credentials/store_test.py:31: in setup_method
16:52:29     raise Exception('No supported docker-credential store in PATH')
16:52:29 E   Exception: No supported docker-credential store in PATH
16:52:29 _______________ ERROR at setup of TestStore.test_unicode_strings _______________
16:52:29 /docker-py/tests/integration/credentials/store_test.py:31: in setup_method
16:52:29     raise Exception('No supported docker-credential store in PATH')
16:52:29 E   Exception: No supported docker-credential store in PATH
16:52:29 ____________________ ERROR at setup of TestStore.test_list _____________________
16:52:29 /docker-py/tests/integration/credentials/store_test.py:31: in setup_method
16:52:29     raise Exception('No supported docker-credential store in PATH')
16:52:29 E   Exception: No supported docker-credential store in PATH
16:52:29 __________ ERROR at setup of TestStore.test_execute_with_env_override __________
16:52:29 /docker-py/tests/integration/credentials/store_test.py:31: in setup_method
16:52:29     raise Exception('No supported docker-credential store in PATH')
16:52:29 E   Exception: No supported docker-credential store in PATH
16:52:29 =================================== FAILURES ===================================
16:52:29 ___________________ SwarmTest.test_init_swarm_data_path_addr ___________________
16:52:29 /docker-py/tests/integration/api_swarm_test.py:254: in test_init_swarm_data_path_addr
16:52:29     assert self.init_swarm(data_path_addr='eth0')
16:52:29 /docker-py/tests/integration/base.py:127: in init_swarm
16:52:29     return self._init_swarm(self.client, **kwargs)
16:52:29 /docker-py/tests/integration/base.py:94: in _init_swarm
16:52:29     '127.0.0.1', listen_addr=helpers.swarm_listen_addr(), **kwargs
16:52:29 /docker-py/docker/utils/decorators.py:34: in wrapper
16:52:29     return f(self, *args, **kwargs)
16:52:29 /docker-py/docker/api/swarm.py:170: in init_swarm
16:52:29     return self._result(response, json=True)
16:52:29 /docker-py/docker/api/client.py:267: in _result
16:52:29     self._raise_for_status(response)
16:52:29 /docker-py/docker/api/client.py:263: in _raise_for_status
16:52:29     raise create_api_error_from_http_exception(e)
16:52:29 /docker-py/docker/errors.py:31: in create_api_error_from_http_exception
16:52:29     raise cls(e, response=response, explanation=explanation)
16:52:29 E   APIError: 400 Client Error: Bad Request ("interface eth0 has more than one IPv6 address (2001:db8:1::242:ac11:2 and fe80::42:acff:fe11:2)")
16:52:29 _________________ SwarmTest.test_join_on_already_joined_swarm __________________
16:52:29 /docker-py/tests/integration/models_swarm_test.py:37: in test_join_on_already_joined_swarm
16:52:29     client.swarm.init()
16:52:29 /docker-py/docker/models/swarm.py:126: in init
16:52:29     node_id = self.client.api.init_swarm(**init_kwargs)
16:52:29 /docker-py/docker/utils/decorators.py:34: in wrapper
16:52:29     return f(self, *args, **kwargs)
16:52:29 /docker-py/docker/api/swarm.py:170: in init_swarm
16:52:29     return self._result(response, json=True)
16:52:29 /docker-py/docker/api/client.py:267: in _result
16:52:29     self._raise_for_status(response)
16:52:29 /docker-py/docker/api/client.py:263: in _raise_for_status
16:52:29     raise create_api_error_from_http_exception(e)
16:52:29 /docker-py/docker/errors.py:31: in create_api_error_from_http_exception
16:52:29     raise cls(e, response=response, explanation=explanation)
16:52:29 E   APIError: 400 Client Error: Bad Request ("could not choose an IP address to advertise since this system has multiple addresses on different interfaces (172.17.0.2 on eth0 and 172.20.0.1 on br-eoa2i7561b7k)")
16:52:29 - generated xml file: /go/src/github.com/docker/docker/bundles/test-docker-py/results.xml -
```

**Comment by thaJeztah** [comment]
@ulyssessouza I tried re-running CI, but same failures again

**Comment by shin-** [comment]
@thaJeztah In v4, we baked in support for credential stores (it used to be a separate library), and so the integration tests moved as well. It probably makes sense to add an env switch so that the moby test suite can skip these. I'll update here once I've done that (or if one of you gets to it before I do, feel free!)

**Comment by thaJeztah** [comment]
We might be able to get around that if the test dockerfile does that setup and we go for https://github.com/moby/moby/pull/39068

**Comment by thaJeztah** [comment]
added a "WIP" commit to bump to master

**Comment by thaJeztah** [comment]
obsoleted by https://github.com/moby/moby/pull/39068

**Pull request closed without merging**
