### PR TITLE
update containerd/console to fix race: lock Cond before Signal

### PR DESCRIPTION
**Pull request by thaJeztah**
Full diff: https://github.com/containerd/console/compare/9290d21dc56074581f619579c43d970b4514bc08...5d1b48d6114b8c9666f0c8b916f871af97b0a761

brings in https://github.com/containerd/console/pull/27 "console_linux: Fix race: lock Cond before Signal"

relates to https://github.com/moby/moby/issues/35865, but has to be vendored into containerd to fix that issue

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @crosbymichael @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
Bump for c8d 1.1 - https://github.com/containerd/containerd/pull/2444

**Comment by thaJeztah** [comment]
oh and c8d master; https://github.com/containerd/containerd/pull/2442

**Comment by tonistiigi** [comment]
opened #37411 that contains this as a containerd dependency

**Comment by thaJeztah** [comment]
Closing because https://github.com/moby/moby/pull/37411 was merged and contains this change;

https://github.com/moby/moby/blob/ae1160b8d8dd0b877bb58226852422c63b7210ce/vendor/github.com/containerd/console/console_linux.go#L263-L275

**Pull request closed without merging**
