### PR TITLE
Updated docs for Joyent Triton

### PR DESCRIPTION
**Pull request by misterbisson**
Joyent's Triton offers Docker service on bare metal with no need to configure Docker hosts. Each `docker run` provisions the container on an available compute node in the selected data center. Some background on this can be found in https://www.joyent.com/developers/videos/bryan-cantrill-virtualizing-the-docker-remote-api-with-triton and https://www.joyent.com/developers/videos/docker-and-the-future-of-containers-in-production. There's a screencast of how this works to deploy a clustered database in https://www.joyent.com/blog/couchbase-in-docker-containers.

The Triton Elastic Container Service for Docker replaces our previous Docker service based on KVM hosts.

I was waiting to update these docs based on https://github.com/docker/machine/pull/1197, but I'm not clear on when that will proceed, so I moving ahead now with what we have.

Signed-off-by: Casey Bisson casey.bisson@joyent.com

### CODE REVIEW

**Comment by dekobon** [comment]
+1 Having the docs for running on Triton right in the documentation will make it a lot easier for myself when I forget how to set it up on a new machine.

**Comment by SvenDowideit** [comment]
LGTM?

**Comment by LK4D4** [comment]
ping @moxiegirl @thaJeztah

**Comment by moxiegirl** [comment]
@misterbisson I'm kind of thinking we should point to Joyent's documentation for installing Docker. I can from this blog https://www.joyent.com/blog/container-service-preview that they are more detailed than on this page.   Also "Docker CLI tools" isn't really our product but Joyent's and it is confusing to see this here. 

This is what we did for AWS:

http://docs.docker.com/installation/amazon/

WDYT?

**Comment by thaJeztah** [comment]
I agree with @moxiegirl here; We should guide the users to Joyent's documentation. Joyent will need those docs anyway, so better link there than to copy, at the risk things get out of sync.

**Comment by misterbisson** [comment]
Thanks @moxiegirl and @thaJeztah for the review. I'll take a look at the AWS documentation, but I should clarify that "Docker CLI tools" is a Docker thing, not Jeyent's. These include `docker`, `docker-compose`, `docker-swarm` and hopefully `docker-machine` [soon](https://github.com/docker/machine/pull/1197) too. Unlike AWS, Joyent exposes a Docker API endpoint, so using it is a matter of pointing the Docker apps on your laptop to that endpoint (one endpoint per data center).

Joyent's docs for installing and configuring this are here: https://docs.joyent.com/public-cloud/api-access/docker

**Comment by moxiegirl** [comment]
@misterbisson Hmm, I must have misread the Joyent doc.  If a user installs Docker Engine they user will get the Docker command line interface (CLI).   I don't typically use Docker CLI tools because it seems redundant.... @thaJeztah has a near encyclopedic knowledge of Docker ... Seb do you recall this in use?

**Comment by thaJeztah** [comment]
Hm, if I understand correctly here, "Docker CLI (tools)" is not really a product, but more a short way of describing the [docker binaries on the command line](https://docs.docker.com/reference/commandline/cli/). So, yes, any user working with docker on the command line is using the "Docker CLI tools", but I don't think we refer to them like this, but just as "using docker (-compose/-machine/-swarm) on the command line"

**Comment by thaJeztah** [comment]
@misterbisson have you had the time yet to look at this? (Just a friendly reminder)

**Comment by misterbisson** [comment]
@thaJeztah I got sidetracked, but I'm hoping to update the PR to change the language this weekend. Thank you.

**Comment by thaJeztah** [comment]
No worries, I was just browsing through open PRs to check up on their status. Just ping us when you're done :+1:

**Comment by thaJeztah** [comment]
ping @misterbisson ? :smile:

**Comment by cpuguy83** [comment]
Do we mind carrying this?

**Comment by moxiegirl** [comment]
@cpuguy83 I'll carry.

**Comment by cpuguy83** [comment]
Thanks @moxiegirl!

**Pull request closed without merging**
