### PR TITLE
cant run volume on windows w remote daemon host

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM assuming it's green :green_book:

**Comment by jfrazelle** [comment]
windows is green!

**Comment by vdemeester** [comment]
@jfrazelle :tada:

**Comment by calavera** [comment]
userns is greeen :tada: :green_heart: 

Go experimental, go :exclamation:

**Pull request merged**
