### PR TITLE
Swap usage of LazyDLL and LoadDLL to LazySystemDLL

### PR DESCRIPTION
**Pull request by darstahl**
**- What I did**

This ensures that the DLLs loaded by Docker come from the system folders.

**- How I did it**

Use NewLazySystemDLL instead of other DLL loading functions for system DLLs.

Signed-off-by: Darren Stahl <darst@microsoft.com>

/cc @jhowardmsft @jstarks

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM. Marking 1.13 (@thaJeztah FYI)

**Comment by tonistiigi** [comment]
@darrenstahlmsft nit: include `golang.org/x/sys/windows` in the same block as the rest of the non-standard imports.

**Comment by darrenstahlmsft** [comment]
@tonistiigi fixed

**Comment by tonistiigi** [comment]
LGTM

**Comment by darrenstahlmsft** [comment]
Experimental failure unrelated, looks like a network glitch. (504)

**Pull request merged**
