### PR TITLE
added rx-docker-client library

### PR DESCRIPTION
**Pull request by shekhargulati**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@shekhargulati can you sign your commit, using the instructions above? thanks!

**Comment by shekhargulati** [comment]
@thaJeztah yes I will do it. I am currently travelling so have limited internet bandwidth. I will do it tomorrow. Thanks.

**Comment by shekhargulati** [comment]
@thaJeztah done

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
