### PR TITLE
Remove `sources/` under `docs` directory

### PR DESCRIPTION
**Pull request by yous**
See #13936.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM. Thanks @yous! We're in the middle of migrating to new tooling for the documentation, looks like we missed these :)

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit 

@moxiegirl I added this to the milestone, but feel free to remove

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
@yous Nice! Thanks for helping with our migration!

**Comment by thaJeztah** [comment]
@moxiegirl I already triggered a rebuild once for this PR, but it looks like the experimental and windows builds are all failing at the moment

**Comment by moxiegirl** [comment]
@jfrazelle cherry-pick please

**Comment by yous** [comment]
Thank you all! :blush:

**Pull request merged**
