### PR TITLE
PowerShell: fix "Nuke-Everything" failing to remove images

### PR DESCRIPTION
**Pull request by thaJeztah**
I noticed this error in CI on https://github.com/moby/moby/pull/38418:

```
20:37:25 INFO: Non-base image count on control daemon to delete is 9
20:37:25 "docker rmi" requires at least 1 argument.
20:37:25 See 'docker rmi --help'.
20:37:25
20:37:25 Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]
20:37:25
20:37:25 Remove one or more images
```

Which indicated that the PowerShell script managed to find images to delete, but
not actually passing the images to `docker rmi`.

The reason for this failing was that the script attempted to convert the
collection/array to a string, which produces;

```powershell
Write-Output $(docker images --format "{{.Repository}}:{{.ID}}" | `
>>         select-string -NotMatch "windowsservercore" | `
>>         select-string -NotMatch "nanoserver" | `
>>         select-string -NotMatch "docker" `
>>         ).ToString()
System.Object[]
```

Which, when trying to split by the chosen separator (`:`), will return the same;

```powershell
Write-Output "System.Object[]".Split(":")[0]
```

This patch:

- Adds an intermediate variable (`$allImages`) to make the code better readable
- Switches the separator to `#`, to prevent breaking on images pulled from a
  repository with a port in its name (`myregistry:5000/my/image`)
- Switches to use a comma-separated list for `-NotMatch` (for readability)

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @johnstep @jhowardmsft @vdemeester @olljanat PTAL 🤗

**Comment by thaJeztah** [comment]
🎉 Looks like it works https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/804/console

```
21:53:37 INFO: Container count on control daemon to delete is 0
21:53:37 INFO: Non-base image count on control daemon to delete is 20
21:53:38 Deleted: sha256:01dd5f3dbf1eb710a0ba5e7297ba093cfab47d557c4e6ef4d9cdc1062d64d44d
21:53:38 Deleted: sha256:090c83237ee0618a2499c96eced4ce232dade3c8a82988d6286a879527083c69
21:53:39 Deleted: sha256:5a577cd9236b31018f306e1314e5e123180e66bd94253537ff30d5a433267a8b
21:53:39 Deleted: sha256:ebdee74690d14f67156ec634a462cd7ced73dcd4a6bf846da5808b3611595125
21:53:40 Deleted: sha256:cc5e3bb72b8fe870877e211371020ab5857eb27a6ecc9e74051bfc16eb3934c9
21:53:40 Deleted: sha256:e6a1ed63d3a5f103da16bb42e62f901b56f65b1609e63315f16d94d9982de589
21:53:42 Deleted: sha256:5617ddc961ef7eed750b8c9b5292f5137b35bcd450d475be23d427814b51c647
21:53:42 Deleted: sha256:4a9235756091249ded3e181620007b1f44ec43afee252721278cf673237c88e6
21:53:43 Deleted: sha256:64151227ee40c87bb69fbdb1212b3fdcabeadca21857c32c89eb5a533faa0f05
21:53:43 Deleted: sha256:a164191c4e42bd236f31ba9b36c51389be400aae45587bb8ea2c2b3e7462e9ed
21:53:44 Deleted: sha256:fb6c57676a423801bd167603bd8cd8e37767463063f98ca9d09ecc9b82a2bd5e
21:53:44 Deleted: sha256:ef151232965840d7477b3828f3a7fdd5d745254f8ffb66056cada8ffec756d43
21:53:45 Deleted: sha256:190237e06f53d13b13d4d4ef6cdef5642eed23031aad136778b512ed8eaede48
21:53:45 Deleted: sha256:6b2ad2402ce3e61b76b5648d94c28964699d8d44952db335374bed75693cdc26
21:53:46 Deleted: sha256:97a18e8a1e14de3ade22c333c59198e5efad8bb484cdb308f95c8846723af4e7
21:53:46 Deleted: sha256:62ebdc2670ef7fb30c523bdaf6df2de0e2a17dedc4390c0ad094e5b5513319f1
21:53:48 Deleted: sha256:1a455b4db09f21a24ba30dc804bc53dbcce1e0f8174f4c6c3c538ebd81479750
21:53:48 Deleted: sha256:e1036e25aaf3d32bef8a370b20c009a38f1a46fdbc592448ae06851d9c0b6373
21:53:49 Deleted: sha256:67ae1eb5155cc43c8e271ccd54eef192f79995937df36ea78bc5de5fc23e93a0
21:53:49 Deleted: sha256:bef0c969feea38d52706c783d3c15bf6b0f2511c6734977e7af767be6783d502
21:53:50 Deleted: sha256:c10e0df20ca94b8bdcd3458d47162e82db76aae592598433166e313bbf49e3a2
21:53:50 Deleted: sha256:543c891d38a2678dc69b883f1566d5267ca053fb7a1e0bdc3de8304c8f5a58ae
21:53:51 Deleted: sha256:03130c618d9be21f233913e6298fd81f2b74e909323f0e3511a306f9f3889cda
21:53:51 Deleted: sha256:46c74733d9426cb3ba7d39006cde432553d012a713119a866fa4f5926d4b4be8
21:53:53 Deleted: sha256:c6a49850fe78d85fcea9328b933dfe3ff044ae8bd69a1e4dfb59036b90bd7588
21:53:53 Deleted: sha256:ee381c3181101267b392c4644037a18ef78c9f0d4e6140309880a5adc469e8ad
21:53:54 Deleted: sha256:6bd7987c87fb1100dcca1cc1f228ad11d2709abf08b27ceb37995ee96c069318
21:53:54 Deleted: sha256:8cbb5dc6f86040c4dbec0fb7d6cb89bb082f827ed272c8dd82e766d4af7657b8
21:53:55 Deleted: sha256:2539e5b05325d63f55efb8a83e3d0f01613ab2b95e95e5b79d800e7f6e23fcd6
21:53:55 Deleted: sha256:f50d84168d123c3abe808c5634f8b3a4d026c58d433bd09b64b1653264fd23ac
21:53:56 Deleted: sha256:a2dfc9795b8f6751bf48a765ce9541edd4fafa47a5ea565556e44687cade6282
21:53:56 Deleted: sha256:bc4224741ee5f43068e2f0aed7fe14b9ef7dd48e7b401e4b5c438d8ae631c498
21:53:58 Deleted: sha256:6ed9f3600ce70cc3d5576636ad62267e3255f1c8cf1a2ddda2cea999629eac3e
21:53:58 Deleted: sha256:9e6665696f7fbcca4e92441f13fd30177fc34cc4871adb557608513c035a6867
21:53:58 Deleted: sha256:c5aa3dc7950e949f3d0a6f60df290be92a6ac61819b4d943cedd1942cf6da21f
21:53:58 Deleted: sha256:f22b3685cc7d089d4f8afdbee4997844610be02f4db839d7c3f8106378f0aa6b
21:53:58 Deleted: sha256:4f29828436ef673b7f2487af266872dae22f14fb5f7f730f838457410779d520
21:53:58 Deleted: sha256:8e9a22dada26884cb70a76979e426bc21dc580e682f42e4940db0f9d629fe4d8
21:53:58 Deleted: sha256:88e102c2897f67dfed3a6950f8424253720278ea50082dc9c16a288c6bdcdef9
21:53:58 Deleted: sha256:8841e811c79bf7a8ee590bebbb395642d6608b539352c55a3043c1df39bda3ce
21:54:04 Deleted: sha256:abf5e40fccd4fea734c0c00ff428141420b2cf6b8591b8b1ecb1f4d4ca3bada2
21:54:04 Deleted: sha256:d7114e2cf361c18965368c1e3e58b3c27f7a968da1007d00b6f2472c10b66eab
21:54:04 Deleted: sha256:d8dbae4e905eb95c382799a6a7143ec4dfc964574497359be975dc8c072cc583
21:54:04 Deleted: sha256:a71dc436ebf58b32c8a966db362cf3c98e7cb0e095156584c544e69f8da1c53a
21:54:04 Deleted: sha256:8448a743abd7d6fdbf40b30e4be77284a9f1647532a0c9c121a882e51557b2ef
21:54:04 Deleted: sha256:3c21ac0d5356a603edf9d196735dd5a3f030b91302aa14b9c64c889d47ff088c
21:54:04 Deleted: sha256:18608ecde47ade2d9a1c3596c4685d6e13df6fb8edc0ab2ec2f9fdb3cb304dd4
21:54:04 Deleted: sha256:79f464db6fe6ceaa556b8b814054e903a9c49e5e2df93c3533ae88a98481aede
21:54:04 Deleted: sha256:374323da5ca1c9b2583eacdf4e88bda59004ff90b8bc75913830a13b249527fb
21:54:04 Deleted: sha256:a09671483909e1d099e6b41496968da539ef10b58698acdf6f191aab9d73dae4
```

**Comment by olljanat** [comment]
Removing issue was most probably caused by changes on #38418 
How ever it is definitely more readable like this :+1:

**Comment by olljanat** [comment]
Actually old script probably worked fine when there was non-base images waiting for removal but just shown error when zero was found.

**Comment by thaJeztah** [comment]
That was my initial thought as well (there were no non-base images), but look at the output before the error;

    INFO: Non-base image count on control daemon to delete is 9

So there were 9 images found to be removed, but then it failed to remove them

**Comment by thaJeztah** [comment]
The problem is the `.ToString()` - it won't work on a collection/array; you can try it on your own machine;

```powershell
$allImages = $(docker images --format "{{.Repository}}#{{.ID}}")

Write-Output "All images:",$allImages,"All images (toString):",$allImages.ToString(),"All images (splitted):",$allImages.ToString().Split("#")[0]
```

Which produces something like

```powershell
PS> $allImages = $(docker images --format "{{.Repository}}#{{.ID}}")
PS> Write-Output "All images:",$allImages,"All images (toString):",$allImages.ToString(),"All images (splitted):",$allImages.ToString().Split("#")[0]
All images:
mywebsite#5d95a1b7a3d6
<none>#af3a37d616c9
example#18a5ce7379b8
<none>#0b971563d14e
<none>#1ca6b2c6666b
docker-dev#23f8c03a672d
<none>#0049f4783468
<none>#5c2c0e8d947b
docker-dev#8a1a105f8695

All images (toString):
System.Object[]

All images (splitted):
System.Object[]
```

**Review by vdemeester — COMMENTED** [review]
SGTM
/cc @simonferquel @johnstep @jhowardmsft

**Review by fntlnz — APPROVED** [review]
LGTM

**Pull request merged**
