### PR TITLE
execdriver/utils.go: add CAP_AUDIT_READ

### PR DESCRIPTION
**Pull request by Thell**
Finish addition of CAP_AUDIT_READ such that audit_read and all pass the capability as listed in bash completion and in syndtr/gocapability/capability.

Tested locally using a recently built libcap and capsh against 3.19 series kernel headers on ubuntu and using capsh --supports and --print to confirm cap gets added.

### CODE REVIEW

**Comment by Thell** [comment]
Reference https://github.com/docker/docker/issues/13007#issue-73465216

**Comment by LK4D4** [comment]
Can someone try DockerSuite.TestExecWithPrivileged against windows and get logs? Seems like something isn't cool with that test.
ping @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@LK4D4 that's a not helpful err message we're getting. can you please rebuild? Let's see if it's happening consistently. What are we assuming to find in the logs?

**Comment by LK4D4** [comment]
@ahmetalpbalkan I rebuild three times. We're assuming to see some error on start.

**Comment by ahmetalpbalkan** [comment]
@LK4D4 could this be happening because docker daemons we use are older (than the code submitted in the PR) and the tests pass on Linux just fine b/c daemon is built from the same code as the PR? If that's the case Jess can update those.

However I can see some new tests that I didn't come across before, if their `testRequires(...)` checks are missing that might be another case. Do we know if this happened before (i.e. did we merge such a PR with bunch of tests failing on Windows)?

**Comment by LK4D4** [comment]
@ahmetalpbalkan Nope, it is only for this. You're probably right about another code for daemon. Thanks.

**Comment by crosbymichael** [comment]
Probably just need to rebuild the docker images to get the new gocapability version

**Comment by jfrazelle** [comment]
it updates the image everytime...

**Comment by jfrazelle** [comment]
the daemon is built from the same code as the PR, we spin up a container and point to that port on the machine for dind on the remote linux host

**Comment by jfrazelle** [comment]
The only thing I can think of is those machines do not have that cap? because I have no idea what else it could be we build dind on those machines so we have the updated daemon

**Comment by ahmetalpbalkan** [comment]
lxc is failing, too now. I don't know this new framework we switched, but looks like there's a problem with it:

```
DockerSuite.TestRunCapAddALLCanDownInterface                0.72

----------------------------------------------------------------------
FAIL: docker_cli_run_test.go:1091: DockerSuite.TestRunCapAddALLCanDownInterface

docker_cli_run_test.go:1095:
    c.Fatal(err, out)
... Error: exit status 255
```

Where did the stderr+stdout from the executed from output go? Why do we only see the exit code? Did the program exit without an output?

In the windows failure with I see:

```
FAIL: docker_cli_exec_test.go:638: DockerSuite.TestExecWithPrivileged

docker_cli_exec_test.go:654:
    c.Fatal(err, out)
... Error: exit status 4294967295
```

In this case `4294967295` is `0xffffffff` (`-1`). It's not a well defined win32 error code. Either docker is exiting with -1, or go runtime is exiting with -1 or it's actually a win32 error code that is not very well known (or I can't seem to find it). Again, there's no stdout/stderr in the failure. (why?)

**Comment by Thell** [comment]
Perhaps, being that the fix for https://github.com/docker/libcontainer/issues/452 removed [the test][2] done via /proc/sys/kernel/cap_last_cap has something to do with this and there wasn't any code pushing past cap_block_suspend (37) during testing, but with https://github.com/docker/docker/pull/10853#issuecomment-98821661 it became _possible_ to go over and the safeguard was gone for the images that have older kernels as well as a reliance on the /proc/ path creating an out of bounds?

The last [few commits][1] (a few days ago) in syndtr/gocapability by @LK4D4 show the caps being auto generated...

[1]:https://github.com/syndtr/gocapability/commits/master
[2]:https://github.com/syndtr/gocapability/commit/390383862b7f6274f1cda959262d720cb57a8437 "Not fail on Apply if there is no /proc/sys/kernel/cap_last_cap file"

**Comment by Thell** [comment]
FYI - adding CAP_AUDIT_READ allows ubuntu:vivid to boot via systemd in docker without any errors (if a proper .target) is selected using `--privileged` or if hugepages is masked using `--cap-add sys_admin --cap-add audit_read`...

**Comment by jfrazelle** [comment]
its still failing even with the windows hosts updated to docker master https://jenkins.dockerproject.com/job/Windows-PRs/4628/consolehttps://jenkins.dockerproject.com/job/Windows-PRs/4628/console

**Comment by jfrazelle** [comment]
sorry that was weird i did not mean to close

**Comment by jfrazelle** [comment]
nm i did because 13091 fixed

**Pull request closed without merging**
