### PR TITLE
Fix spelling mistakes in documentation

### PR DESCRIPTION
**Pull request by jogo**
While reading  some of the docs I noticed a few errors, so I ran
misspellings (https://pypi.python.org/pypi/misspellings) on markdown files

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks so much! LGTM

ping @jfrazelle @calavera I've never worked with the "misspellings" tool mentioned, could it be interesting for automated scanning for small typos?

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by jogo** [comment]
@thaJeztah misspellings looks for common misspellings and in my experience does a good job of only finding real typos. I think it would be a good candidate for some sort of automation.

You can try it out for yourself with:

  pip install misspellings
  git ls-files | grep -V vendor | grep md$ | xargs misspellings

limited search to non vendored code, and documentation only. Since vendored docs should be fixed upstream, and sometimes a misspelled word hidden in a non-user facing location (that doesn't make grepping harder) doesn't matter much.

**Comment by thaJeztah** [comment]
@jogo definitely looks interesting. I'm always a bit wary of automated spell checks (especially when combined with source code), but this looks interesting because it's limited to "common" misspellings.

Perhaps we could give it a go at some point to see if it works out okay.

**Comment by SvenDowideit** [comment]
LGTM

**Comment by jogo** [comment]
Thank you for the prompt review. 

Strange question:  I have been reading up the workflow documentation for Docker, and from what I read in CONTRIBUTING it says:

    A change requires LGTMs from an absolute majority of the maintainers of each component affected.

Yet I only see two LGTM's on this patch.  So what is the review process?

**Comment by thaJeztah** [comment]
@jogo for documentation changes, there's generally two "LGTM"s required from the docs-maintainers.

I think the description in the CONTRIBUTING and MAINTAINERS documents may need some updating

**Pull request merged**
