### PR TITLE
integ-cli: Fix race in TestLogsSince

### PR DESCRIPTION
**Pull request by ahmetb**
`TestLogsSince` used to rely on time synchronization and precision of
the timestamps. This change provides a less flaky alternative.

> NOTE: Looks like this is currently blocking nearly all windows CI. Please
> take a look.

Signed-off-by: Ahmet Alp Balkan 
cc: @jhowardmsft pls review

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
Windows CI server looks down, somebody please rebuild once fixed.

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
Thanks for reviewing folks <3

**Pull request merged**
