### PR TITLE
Don't run tests twice

### PR DESCRIPTION
**Pull request by rumpl**
**- What I did**

Made some tests only run once

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vvoland — APPROVED** [review]
This was so tricky to find! 😆

**Review by thaJeztah — APPROVED** [review]
LGTM 😂

**Comment by thaJeztah** [comment]
":warning: CodeCov: merging this PR will reduce coverage with 50%" ? 😂 😜

**Review by akerouanton — APPROVED** [review]
LGTM

**Review by sam-thibault — APPROVED** [review]

**Pull request merged**
