### PR TITLE
Simplify blkio resources setup in spec

### PR DESCRIPTION
**Pull request by tonistiigi**
Removed duplicated code.

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like gccgo is trying to run a static daemon with devicemapper? https://jenkins.dockerproject.org/job/Docker-PRs-gccgo/4989/console

```
21:06:31 time="2016-04-29T21:06:00Z" level=error msg="There are no more loopback devices available." 
21:06:31 --- FAIL: TestDevmapperIncreaseLoopBackSize (0.00s)
21:06:31 	graphtest_unix.go:81: graphdriver: loopback attach failed
21:06:31 	graphtest_unix.go:85: loopback attach failed
21:06:31 time="2016-04-29T21:06:00Z" level=error msg="devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a dynamic binary to use devicemapper or select a different storage driver. For more information, see 
```

**Comment by aaronlehmann** [comment]
LGTM

**Comment by tonistiigi** [comment]
@thaJeztah That is from devicemapper unit tests. Probably some previous run didn't release loopbacks properly.

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
