### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by icecrime**
~~Open for discussion: should we add the entire `vendor/` subdirectory to `.gitignore` to make it obvious to newcomers that you should never have changes in that? I'm assuming that people who know about `hack/vendor.sh` will understand the extra requirement to `git add -f vendor/src/`.~~

Cf. https://github.com/docker/docker/pull/11713#issuecomment-85590474 as to why this won't help. Updating the PR to keep the sorting commit only.

### CODE REVIEW

**Comment by tianon** [comment]
I don't think adding `vendor/` here will really help though.  The files that are already there will still show up as changed, so I think this would just cause more potential for legitimate updates missing files than helping newcomers. :cry:

**Comment by tianon** [comment]
I'm +1 on 347c02c27a8b940058a0df1d999a2f005a209dba though! :+1: :heart:

**Comment by LK4D4** [comment]
So many trash there.

**Comment by icecrime** [comment]
Oops you're right... I thought that git would ignore them for modification too, not only "initial" add :-( Updating to keep 347c02c only.

**Comment by crosbymichael** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
