### PR TITLE
fix the mistak of url format

### PR DESCRIPTION
**Pull request by yu8833**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by ripcurld00d** [comment]
LGTM
PTAL @thaJeztah

**Review by boaz0 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by vdemeester** [comment]
Removed from the milestone as I think `project/TOOLS.md` is not publish in docs.docker.com so it doesn't really have to be in the milestone :angel: 
/cc @thaJeztah

**Comment by thaJeztah** [comment]
Thanks @YuPengZTE LGTM too

**Pull request merged**
