### PR TITLE
Re-run vndr to fix master

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/moby/moby/pull/39966#issuecomment-538088938, https://github.com/moby/moby/pull/40032#issuecomment-537906157, https://github.com/moby/moby/pull/39713#issuecomment-537902850

Pull requests started failing because vendoring didn't match;

```
The result of vndr differs

D vendor/golang.org/x/sync/singleflight/singleflight.go

Please vendor your package with github.com/LK4D4/vndr.
```

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM assuming CI is happy.

Do we know what happened?

**Comment by thaJeztah** [comment]
No, I just found out that the problem was on master (see https://github.com/moby/moby/pull/40032#issuecomment-537906157), I initially thought it was something weird with `vndr`

Likely a PR got merged out of order, or perhaps got merged on "red"

I'd like to find the PR though (in case it's one that we have to backport, so that we can cherry-pick them together)

**Comment by thaJeztah** [comment]
I think this is the one; https://github.com/moby/moby/commit/3c548254a2720f2c02ae47daea264a71e357eb6b https://github.com/moby/moby/pull/39983

**Comment by thaJeztah** [comment]
Ah! I understand why; this is from that PR:

```
[2019-10-02T20:48:17.877Z] + docker run --rm -t --privileged -v /home/ubuntu/workspace/moby_PR-39983/.git:/go/src/github.com/docker/docker/.git --name docker-pr4 -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT=6ca3ec88ae9e1435abbed665ec598c00058659da -e DOCKER_GRAPHDRIVER docker:6ca3ec88ae9e1435abbed665ec598c00058659da hack/validate/vendor
[2019-10-02T20:48:18.810Z] No vendor changes in diff.
```

The vendor check only runs if `vendor.conf` is modified, but in this case the `import` was removed, therefore also affecting what has to be vendored

**Review by arkodg — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]

**Comment by thaJeztah** [comment]
> The vendor check only runs if vendor.conf is modified, but in this case the import was removed, therefore also affecting what has to be vendored

perhaps we should have a check if imports are added/removed (but that might be overhead); this likely is a bit of a corner case (last import of a package removed), so perhaps we should just take it for granted

**Comment by thaJeztah** [comment]
Vendor check passed now:

Screenshot 2019-10-03 at 22 45 54

**Pull request merged**
