### PR TITLE
Move timeutils functions to the only places where they are used.

### PR DESCRIPTION
**Pull request by calavera**
- Move time json marshaling to the jsonlog package: this is a docker
  internal hack that we should not promote as a library.
- Move Timestamp encoding/decoding functions to the API types: This is
  only used there. It could be a standalone library but I don't this
  it's worth having a separated repo for this. It could introduce more
  complexity than it solves.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
+1 LGTM

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by unclejack** [comment]
LGTM

**Comment by mikebrow** [comment]
Reviewed.  No issues found.

**Comment by thaJeztah** [comment]
thanks @mikebrow!

**Pull request merged**
