### PR TITLE
"docker network" missing from docker --help

### PR DESCRIPTION
**Pull request by kunalkushwaha**
Signed-off-by: Kunal Kushwaha kunal.kushwaha@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
do we need to call that `initExperimental` function anywhere?

**Comment by WeiZhang555** [comment]
`docker network` is an experimental feature, are you trying to add it to standard release ?

**Comment by kunalkushwaha** [comment]
@calavera I changed the function name to init(), so no need to invoke explicitly. Invoking initExperimental() from flags.go was causing error in standard build.

@WeiZhang555  Its only for experimental. Please refer #14229 .

**Comment by calavera** [comment]
thanks for the change @kunalkushwaha. It looks like there is a issue testing the output of the help command in experimental.

**Comment by kunalkushwaha** [comment]
@calavera I looked into the test case. The reason of failing this test case is length of command help generated during test. i.e.
``/go/src/github.com/docker/docker/bundles/1.8.0-dev/test-integration-cli/../binary/docker network [OPTIONS] COMMAND [OPTIONS] [arg...]``

The current path is appended along with command, which make the help string too long the 80 (limit in test case [docker_cli_help_test](https://github.com/docker/docker/blob/master/integration-cli/docker_cli_help_test.go#L127)

Exact error is shown below.
```
----------------------------------------------------------------------
FAIL: docker_cli_help_test.go:14: DockerSuite.TestHelpTextVerify

docker_cli_help_test.go:129:
    c.Fatalf("Help for %q is too long(%d chars):\n%s", cmd,
        len(line), line)
... Error: Help for "network" is too long(140 chars):
Usage: /go/src/github.com/docker/docker/bundles/1.8.0-dev/test-integration-cli/../binary/docker network [OPTIONS] COMMAND [OPTIONS] [arg...]
---------------------------------------------------------------------- 
```

I tested with ``docker --help`` and ``docker network --help``, it works fine on console

**Comment by calavera** [comment]
Yeah, that's a bug. Can you trye fixing it by hardcoding `docker` in the network command initialization?

https://github.com/docker/docker/blob/master/api/client/network.go#L14

**Comment by kunalkushwaha** [comment]
@calavera This fix has led me to make changes at couple of places.
- Please review it and let me know, if any changes are required.

1.  As per your suggestion, I hardcoded the ``docker``.
2. In HelpTest file [docker-cli-help-test](https://github.com/docker/docker/pull/14626/files#diff-ce249bca1bc5c8ba541d96f2df077edcL178) , A short help is expected from all commands, So I made ``network`` in noShortList. 
    - I think, all plugin based commands, can be safely put in this list like ``network`` , ``volume`` 

3. There is a check for exact number of commands in list. Since, experimental commands cannot be part of main list, I modified the condition to ``<``.

4. Help test also [check](https://github.com/docker/docker/blob/master/integration-cli/docker_cli_help_test.go#L144) a condition for 4 spaces. In Libnetwork, the subcommands, are printed with 4 spaces in the help, So it is reduced to 2 spaces.

**Comment by calavera** [comment]
all that sounds very reasonable, thank you. Unfortunately, we need to port any code that touches libnetwork to docker/libnetwork first if we want to change it.

**Comment by LK4D4** [comment]
waiting for merge in libnetwork

**Comment by tiborvass** [comment]
@LK4D4 what's up with this? are we still waiting on libnetwork?

**Comment by tiborvass** [comment]
Ping @calavera @LK4D4

**Comment by mavenugo** [comment]
@tiborvass afaik this PR was waiting on https://github.com/docker/libnetwork/pull/410, which got merged a couple of weeks ago.

**Comment by cpuguy83** [comment]
Looks like we have this libnetwork change in Docker already.
@kunalkushwaha can you do a rebase?

**Comment by cpuguy83** [comment]
Looks like subcommands in are not sorted properly :(

**Comment by kunalkushwaha** [comment]
@cpuguy83  Sorting of commands is removed from code now, which is resulting in this.
Please look at commit [4d212f78539](https://github.com/docker/docker/commit/4d212f7853912a2826e1cc725d831515553fde9c#diff-b715a530d535012e418a564a3eafedb9L39) of docker.go 

Since, experimental flag is loaded after flag.go, commands defined in flags_experimental.go is append at end of list, So the sort test will fail for experimental flags.

**Comment by cpuguy83** [comment]
@kunalkushwaha We can add it back here. No harm.

**Comment by calavera** [comment]
LGTM, commands are properly sorted now.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
