### PR TITLE
Fixes oom error

### PR DESCRIPTION
**Pull request by ashahab-altiscale**
This fixes the oom error by creating a state.json under the lxc directory, and getting oom notifications.
Signed-off-by: Abin Shahab ashahab@altiscale.com (github: ashahab-altiscale)

### CODE REVIEW

**Comment by ashahab-altiscale** [comment]
@jfrazelle @dineshs-altiscale One more fix.

**Comment by dineshs-altiscale** [comment]
LGTM

**Comment by ashahab-altiscale** [comment]
@crosbymichael

**Comment by jfrazelle** [comment]
This is your jenkins build on lxc https://jenkins.dockerproject.com/job/LXC%20PR%20Test/label=ubuntu-aufs-lxc/1/console

**Comment by ashahab-altiscale** [comment]
@jfrazelle Thanks so much! So if all my pull requests go through, can we have a notification from the lxc builds for every pull requests? That'd ensure that no new breaks are introduced.

**Comment by jfrazelle** [comment]
YES! That would be my fav :)

**Comment by ashahab-altiscale** [comment]
So let us know if there's anything else we need to do. The two tests that would continue to break are: 

1) readonly rootfs
2) pid namespace

I will work with lxc to implement these, but since these are new features(like exec), can we ignore those two tests for lxc?

**Comment by ashahab-altiscale** [comment]
I see a large number of new test breaks on this pull. Are they happenning
in master?

**Comment by jfrazelle** [comment]
master is running here https://jenkins.dockerproject.com/job/LXC%20PR%20Test/label=ubuntu-aufs-lxc/2/console

**Comment by ashahab-altiscale** [comment]
Wow, seems like I introduced a lot of breaks on this branch. I'll look.

**Comment by jfrazelle** [comment]
ill try building again, may have been a fluke

**Comment by ashahab-altiscale** [comment]
Thank you Jessie.

**Comment by jfrazelle** [comment]
looks to be not a fluke :(
https://jenkins.dockerproject.com/job/LXC%20PR%20Test/3/label=ubuntu-aufs-lxc/console

**Comment by ashahab-altiscale** [comment]
Cool! Your CI builds have proved to be useful :). I'll fix these. I ran all test several times, but could not reproduce, not sure why.

**Comment by ashahab-altiscale** [comment]
@jfrazelle I cannot reproduce the issues(except for the ones I expect to break). All of the "build" tests pass on my box.
Can you ensure that all images tagged "docker" or "<none>" are cleaned off the jenkins slave before a build executes? I feel there's some staleness going on here.

**Comment by ashahab-altiscale** [comment]
Here the breaks I see, all expected:
--- FAIL: TestGetContainerStats (5.53s)
	docker_api_containers_test.go:297: EOF
--
--- FAIL: TestEventsContainerFailStartDie (1.87s)
	docker_cli_events_test.go:76: Container run with command blerg should have failed, but it did not
--
--- FAIL: TestRunModePidHost (1.16s)
	docker_cli_run_test.go:2768: PID different with --pid=host pid:[4026532160] != pid:[4026532228]
--
--- FAIL: TestRunContainerWithReadonlyRootfs (1.49s)
	docker_cli_run_test.go:3005: expected container to error on run with read only error
--
--- FAIL: TestSaveDirectoryPermissions (3.91s)
	docker_cli_save_load_test.go:425: failed to find the layer with the right content listing

**Comment by ashahab-altiscale** [comment]
@jfrazelle any chance you can rerun this on a clean jenkins box?

**Comment by ashahab-altiscale** [comment]
@jfrazelle I've run the test on this branch multiple times, and I could not reproduce the tests.

**Comment by jfrazelle** [comment]
Sorry I will try again first thing tomorrow

**Comment by ashahab-altiscale** [comment]
Thanks!

**Comment by ashahab-altiscale** [comment]
Here are my breaks(someone committed 2 new tests already :/ ):

--- FAIL: TestGetContainerStats (6.43s)
--- FAIL: TestMainHelpWidth (0.10s)
--- FAIL: TestCmdHelpWidth (0.55s)
--- FAIL: TestRunModePidHost (1.28s)
--- FAIL: TestRunContainerWithReadonlyRootfs (1.70s)
--- FAIL: TestSaveDirectoryPermissions (4.13s)

**Comment by jfrazelle** [comment]
When you run these is it directly on your host? because jenkins runs them in a container so they should not be effected by other things on the host? I am wondering if that is our issue in the discrpency between our output and yours

**Comment by ashahab-altiscale** [comment]
I run "make test" directly on my host, but it creates a docker container, copies the source inside, and then compiles and launches the tests inside that container(docker in docker). Does jenkins have another level of container?

**Comment by jfrazelle** [comment]
No thats exactly what we do.... hmmmm

**Comment by ashahab-altiscale** [comment]
If you're running 'make test' in jenkins, I'd suggest executing the following two lines before running 'make test':

```
docker rmi -f `docker images -a | grep 'docker' | awk '{print $3}'`
docker rmi -f `docker images -a | grep '<none>' | awk '{print $3}'`
```

**Comment by jfrazelle** [comment]
ill make a vm locally and test there so it is isolated

**Comment by ashahab-altiscale** [comment]
I'm pretty sure jenkins has stale docker:<branchname> images lying around.

**Comment by jfrazelle** [comment]
Right now we run multiple tests at once so as to utilize cpu power. There
will always be other tasks running on the same machine. Which is kinda the
point of containers no? I don't understand why this wouldn't work with lxc.

**Comment by ashahab-altiscale** [comment]
Can we tell the lxc tests to not use cached images? We don't mind the wait :)

**Comment by ashahab-altiscale** [comment]
@jfrazelle What was the result on your vm?

**Comment by jfrazelle** [comment]
I keep getting the same thing, I even cleared everything off the server and
made sure nothing else could run and am still getting
https://jenkins.dockerproject.com/job/LXR-PRs/5/console

**Comment by jfrazelle** [comment]
Could it be the version of lxc we are using do we need to bump it again?
because the tests pass as expected w master even if other things are
lingering around.

**Comment by ashahab-altiscale** [comment]
Closing as #10510 covers this.

**Pull request closed without merging**
