### PR TITLE
fix duplicate command in uninstall instructions

### PR DESCRIPTION
**Pull request by zunayed**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! can you sign-off your commit using the instructions that @GordonTheTurtle gave above?

**Comment by thaJeztah** [comment]
Oh, actually, I see there's a sign-off; but can you change "root" to your actual name?

**Comment by zunayed** [comment]
@thaJeztah let me know if the sign-off is good now

**Comment by thaJeztah** [comment]
Excellent! Sorry for all the hassle :)

LGTM

**Pull request merged**
