### PR TITLE
1.12.0 final cherry picks

### LINKED ISSUE #25109: libnetwork: panic in restore code
```
Jul 26 19:25:57 deathstar systemd[1]: Starting docker...
Jul 26 19:25:57 deathstar systemd[1]: Started docker.
Jul 26 19:25:57 deathstar docker[24013]: time="2016-07-26T19:25:57.089163560-07:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DO
Jul 26 19:25:57 deathstar docker[24013]: time="2016-07-26T19:25:57.089871702-07:00" level=info msg="libcontainerd: new containerd process, pid: 24027"
Jul 26 19:25:57 deathstar docker[24013]: time="2016-07-26T19:25:57.098125588-07:00" level=warning msg="containerd: low RLIMIT_NOFILE changing to max" current=1024 max=4096
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.288050675-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.288728923-07:00" level=info msg="Loading containers: start."
Jul 26 19:25:58 deathstar docker[24013]: .time="2016-07-26T19:25:58.288810308-07:00" level=error msg="Failed to load container 689687a7cf7a900bbd7652ccb515264ba2c123b713e4b
Jul 26 19:25:58 deathstar docker[24013]: .time="2016-07-26T19:25:58.289900841-07:00" level=warning msg="libcontainerd: restore was called on a fully synced container (6a889
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.294715331-07:00" level=info msg="Firewalld running: false"
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.343434041-07:00" level=error msg="getEndpointFromStore for eid 1c0c0f29aa21249d36655fec12eabd97e5ab713075
Jul 26 19:25:58 deathstar docker[24013]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 26 19:25:58 deathstar docker[24013]: [signal 0xb code=0x1 addr=0x18 pc=0x8b5c9f]
Jul 26 19:25:58 deathstar docker[24013]: goroutine 1 [running]:
Jul 26 19:25:58 deathstar docker[24013]: panic(0x1b1b820, 0xc82000e070)
Jul 26 19:25:58 deathstar docker[24013]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/libnetwork.(*sandbox).restoreOslSandbox(0xc820257860, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:729 +0x1cf
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/libnetwork.(*controller).sandboxCleanup(0xc82020e000, 0xc8201cb050)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_store.go:261 +0x1645
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/libnetwork.New(0xc82037cd00, 0x7, 0x8, 0x0, 0x0, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/controller.go:219 +0xa26
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc820426820, 0xc820162380, 0xc8201cb050, 0x0, 0x0, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/daemon/daemon_unix.go:638 +0xf5
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/docker/daemon.(*Daemon).restore(0xc820426820, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/daemon/daemon.go:225 +0xa8f
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/docker/daemon.NewDaemon(0xc820162380, 0x7fdae2cdf730, 0xc820402098, 0x7fdae2cdf178, 0xc82037ac30, 0x0, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/daemon/daemon.go:603 +0x329c
Jul 26 19:25:58 deathstar docker[24013]: main.(*DaemonCli).start(0xc82045d680, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:270 +0x1a0e
Jul 26 19:25:58 deathstar docker[24013]: main.main()
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x491
Jul 26 19:25:58 deathstar systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 26 19:25:58 deathstar systemd[1]: docker.service: Unit entered failed state.
```

### PR DESCRIPTION
**Pull request by tiborvass**
Cherrypicks:
- [#25059](https://github.com/docker/docker/pull/25059)
  - 13c138e bash completion for container labels to `service {create,update}`
- [#25060](https://github.com/docker/docker/pull/25060)
  - 34d9a82 Remove bash completion for `docker swarm inspect`
- [#25068](https://github.com/docker/docker/pull/25068)
  - df167d3 Fix issue with test ordering for TestParseWords
- [#25094](https://github.com/docker/docker/pull/25094)
  - 3cddda3 Remove the Require on the socket for the rpm
- [#25086](https://github.com/docker/docker/pull/25086)
  - 5c05b84 Update diff apply test to check sub directories
  - 1c0f665 Fix files in subdirectories creating bad whiteout
- [#25080](https://github.com/docker/docker/pull/25080)
  - 755be79 Move directive out of globals
- [#25111](https://github.com/docker/docker/pull/25111)
  - c75de8e Fix daemon panic on restoring containers
- [#25010](https://github.com/docker/docker/pull/25010)
  - 6440cac update rolling update tutorial to reflect default parallelism and update on failure
- [#25131](https://github.com/docker/docker/pull/25131)
  - b1ae883 Vendoring libnetwork to fix #25109

### CODE REVIEW

**Comment by tiborvass** [comment]
Had to rebase, the only conflict was related to a duplicate of https://github.com/docker/docker/pull/25010/files#diff-8bd681a5ff591b46983111272e994605L108 so it should be safe.

**Comment by justincormack** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
documentation CI can be ignored; will be fixed when 1.12.0 is tagged;

```
21:56:33 ERROR: (404) 10 links to (https://github.com/docker/docker/releases/tag/v1.12.0)
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
21:56:33 			 link https://github.com/docker/docker/releases/tag/v1.12.0 on page engine/deprecated.md
```

**Pull request merged**
