### PR TITLE
Revendor Microsoft/hcsshim @ v0.6.9

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard (VM) <jhoward@ntdev.microsoft.com>

Fixes https://github.com/docker/for-win/issues/1947
Fixes https://github.com/moby/moby/issues/36919

Files are in certain circumstances omitted from layers on commit during a build step on Windows. See https://github.com/Microsoft/hcsshim/pull/165 for more detail.

@carlfischer1 This probably should be backported. @thaJeztah @johnstep PTAL.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Should we have a test for this?

**Comment by jhowardmsft** [comment]
@thaJeztah Feel free to add one, but I've got to get back to my regularly scheduled day job....

**Review by johnstep — APPROVED** [review]
LGTM

Why the white space changes to other files?

**Comment by jhowardmsft** [comment]
As mentioned offline, 🤷‍♂️. If you look at  https://github.com/Microsoft/hcsshim/pull/165, it was a one line change. This is what vendoring pulled in....

**Comment by thaJeztah** [comment]
Full diff is https://github.com/Microsoft/hcsshim/compare/v0.6.8...v0.6.9; whitespace changes are because of https://github.com/Microsoft/hcsshim/pull/157

**Comment by thaJeztah** [comment]
@jhowardmsft my concern is that both the previous revendor that introduced this regression (https://github.com/moby/moby/pull/35924), and this PR do not have any test added (nor here, or in the hcsshim repository); in fact, apart from a check for CLA, there's no CI running on the hcsshim repository at all (at least, not publicly).

Both issues were not caught by CI, which makes it perfectly possible that future regressions won't be caught as well if there's no test-case covering this situation.

**Comment by jhowardmsft** [comment]
I will leave that as an exercise for someone else as a follow-up. I don't think it's unreasonable for a Windows repo to have files in it using Windows default line endings (CRLF). However, the bug fix itself is important as layers are missing files during builds. I think that trumps line-endings.

**Comment by jhowardmsft** [comment]
Closing in favour of https://github.com/moby/moby/pull/36985

**Pull request closed without merging**
