### PR TITLE
Image mag

### PR DESCRIPTION
**Pull request by carolfh**
ping for LGTM @moxiegirl

### CODE REVIEW

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
ping @thaJeztah --- Seb this is Carol the new contract write on DTR.  @carolfh this is Seb who is every where. :-D

**Comment by thaJeztah** [comment]
Hello Carol, good to have you on board! If you ever need assistance, a PR reviewed, feel free to @ mention ("ping") me here, or on IRC (I'm in the EU (CET) timezone, so I might not respond directly :smile:

changes LGTM (thanks!)

@moxiegirl do we need to keep these as separate commits for the internal issue tracker, or is squashing ok?

**Comment by moxiegirl** [comment]
@thaJeztah Good catch, @carolfh needs to rebase and squash.

**Comment by moxiegirl** [comment]
LGTM Thanks @carolfh

**Comment by carolfh** [comment]
thanks @moxiegirl for your help!
and hello @thaJeztah. looking forward to working with ya!

**Comment by thaJeztah** [comment]
Congrats on your first pull-request being merged! :tada: :dancers:

**Comment by carolfh** [comment]
@thaJeztah LOL, why thank you....gearing up to do some more ;D

**Pull request merged**
