### PR TITLE
 vendor: update buildkit to 9acf51e491

### PR DESCRIPTION
**Pull request by tonistiigi**
Brings in fixes for:

- https://github.com/moby/buildkit/issues/457 Stripped newlines in non-interactive (`--no-progress`) output
- https://github.com/moby/buildkit/issues/412 dockerfile: USER doesn't set additional group
- https://github.com/moby/buildkit/pull/484 pull: do not send duplicate status for completed jobs
- https://github.com/moby/buildkit/pull/470 Ensure BaseName of Stage is not blank
  - relates to https://github.com/moby/moby/issues/37325

full diff: https://github.com/moby/buildkit/compare/cce2080ddbe4698912f2290892b247c83627efa8...9acf51e49185b348608e0096b2903dd72907adcb

@tiborvass @AkihiroSuda

### CODE REVIEW

**Review by tiborvass — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
z has DNS issues

**Comment by tiborvass** [comment]
Failing tests are flakey

**Pull request merged**
