### PR TITLE
Add sakla to pkg/namesgenerator/names-generator.go

### PR DESCRIPTION
**Pull request by LukeJaffe**
Signed-off-by: Jaffe, Lucas William <jaffe5@llnl.gov>

**- What I did**
Add sakla to pkg/namesgenerator/names-generator.go.

**- How I did it**
Edit pkg/namesgenerator/names-generator.go.

**- How to verify it**
Check pkg/namesgenerator/names-generator.go lines 506-508.

**- Description for the changelog**
Add sakla to pkg/namesgenerator/names-generator.go

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by boaz0 — COMMENTED** [review]
Can you replace Linkedin with another link so people who don't use Linkedin can read?

**Comment by thaJeztah** [comment]
Yes, ran into the same, couldn't find good background information

ping @tiborvass PTAL

**Comment by AkihiroSuda** [comment]
ping @LukeJaffe

**Comment by AkihiroSuda** [comment]
ping @LukeJaffe

**Comment by thaJeztah** [comment]
Let me close this, as this went stale

**Pull request closed without merging**
