### PR TITLE
resolvconf: add //go:build directives to prevent downgrading to go1.16 language

### PR DESCRIPTION
**Pull request by thaJeztah**
- introduced in https://github.com/moby/moby/pull/47497
- relates to https://github.com/moby/buildkit/pull/4772

Commit 8921897e3b941202d7d46143fa565008ca242205 introduced the uses of `clear()`, which requires go1.21, but Go is downgrading this file to go1.16 when used in other projects (due to us not yet being a go module);

    0.175 + xx-go build '-gcflags=' -ldflags '-X github.com/moby/buildkit/version.Version=b53a13e -X github.com/moby/buildkit/version.Revision=b53a13e4f5c8d7e82716615e0f23656893df89af -X github.com/moby/buildkit/version.Package=github.com/moby/buildkit -extldflags '"'"'-static'"'" -tags 'osusergo netgo static_build seccomp ' -o /usr/bin/buildkitd ./cmd/buildkitd
    181.8 # github.com/docker/docker/libnetwork/internal/resolvconf
    181.8 vendor/github.com/docker/docker/libnetwork/internal/resolvconf/resolvconf.go:509:2: clear requires go1.21 or later (-lang was set to go1.16; check go.mod)

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```markdown changelog

```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
@vvoland @robmry PTAL

**Comment by robmry** [comment]
Should the directive be "go1.21" instead of "go1.19"?

**Comment by thaJeztah** [comment]
> Should the directive be "go1.21" instead of "go1.19"?

🤦 yes, it should be. I copy/pasta'd it, and forgot to update.

**Comment by thaJeztah** [comment]
Updated to go1.21

**Review by robmry — APPROVED** [review]

**Comment by thaJeztah** [comment]
These have become flaky recently; https://github.com/moby/moby/issues/47573

```
=== Failed
=== FAIL: amd64.integration.plugin.logging TestReadPluginNoRead/default (0.89s)
    read_test.go:90: assertion failed: strings.TrimSpace(buf.String()) is not "hello world": []
    --- FAIL: TestReadPluginNoRead/default (0.89s)

=== FAIL: amd64.integration.plugin.logging TestReadPluginNoRead (5.26s)
    read_test.go:93: [d31e37ef4418e] daemon is not started
```

**Pull request merged**
