### PR TITLE
Revert "Move layer mount refcounts to mountedLayer"

### PR DESCRIPTION
**Pull request by tonistiigi**
This reverts commit 563d0711f83952e561a0d7d5c48fef9810b4f010.

Seems to cause issues on overlayfs on builder `ADD/COPY` commands.

```
» docker build --no-cache .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM scratch
 --->
Step 2 : ADD abc /
lstat : no such file or directory
```

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
Merging to unblock.

**Comment by cpuguy83** [comment]
Looking at this. I must have changed something and didn't re-run the test suite against the various graph drivers.

**Comment by thaJeztah** [comment]
@cpuguy83 did you want to re-implement it for 1.12? Just checking so we don't forget

**Comment by tonistiigi** [comment]
@thaJeztah This was already put back with #21454

**Comment by thaJeztah** [comment]
@tonistiigi oh, thanks! sorry, lost track

**Pull request merged**
