### PR TITLE
filenotify: don't close channels to avoid panic

### PR DESCRIPTION
**Pull request by LK4D4**
ping @tiborvass @tonistiigi @cpuguy83

### CODE REVIEW

**Comment by cpuguy83** [comment]
:+1: Just w/o the commented code :)

**Comment by tiborvass** [comment]
Replaces #20522

**Comment by aaronlehmann** [comment]
LGTM

**Comment by aaronlehmann** [comment]
Would change the comment slightly though - GC doesn't close channels, it just frees their memory.

**Comment by tonistiigi** [comment]
The slightly modified original testcase `docker rm test;docker run -d --name=test --log-opt max-size=50 --log-opt max-file=5 busybox sh -c "sleep 10;yes X|head -c 200; sleep 2"; docker logs -f test` still causes a leak, the watcher goroutine keeps scanning and never goes away. This issue for that is probably in `jsonfilelog/read`, not in poller. Not to say that poller doesn't too weird stuff as well, `poller.Close` is a no-op and these channels are all closed by `poller.Remove`.

**Comment by tonistiigi** [comment]
It's not making anything worse, SGTM so we don't have a panic in 1.10.2

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
