### PR TITLE
Allow SEO crawling from docs site

### PR DESCRIPTION
**Pull request by moxiegirl**
Signed-off-by: Nathan LeClaire nathan.leclaire@gmail.com

Docker-DCO-1.1-Signed-off-by: Nathan LeClaire nathan.leclaire@gmail.com (github: nathanleclaire)

(cherry picked from commit de03f4797b614fb192a72c83812c2a04a1939c87)

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @jfrazelle arrrgh it is dying because of those merge commits! Can I get an LGTM anyway? It builds locally.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
gotchu :)

**Comment by jfrazelle** [comment]
thanks @moxiegirl sorry about this whole ordeal

**Comment by moxiegirl** [comment]
@jfrazelle no worries Jess. It is pretty cool Fanette caught it so quick! Good team those Docker folks!

**Pull request merged**
