### PR TITLE
Small cleanup now that we have multiple details about the server stored on the cli

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by ehazlett** [comment]
@dnephin rebase please, thx!

**Comment by dnephin** [comment]
rebased

**Comment by ehazlett** [comment]
LGTM (nam)

**Comment by cpuguy83** [comment]
`ServerType` type (and subsequent interface method) is a bit weird.
Other than that it looks ok.

**Comment by thaJeztah** [comment]
Thinking..  are `ServerDetails`, `ServerProperties`, `ServerInfo` better options?

**Comment by cpuguy83** [comment]
`ServerInfo` seems better.

**Comment by dnephin** [comment]
SGTM, I changed the name to `ServerInfo`

**Comment by coolljt0725** [comment]
LGTM ping @cpuguy83  @thaJeztah

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
