### PR TITLE
update status code for network api

### LINKED ISSUE #30698: [DOC] network api docs seem to miss some status codes
Hi, All,

I found in swagger.yml and api doc, there are some missing status codes about network:

```
GET /networks/(id or name) misses status code of 500;
DELETE /networks/(id or name) missed status code of 403;
```

Here is my environment, we can see that there are two network has a prefix network id of `a`:
```
root@ubuntu:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
b80b14598d1f        allen               bridge              local
abe5fa290b6d        allen2              bridge              local
db8dfef4e6de        allen3              bridge              local
a89bfaea7f72        allen4              bridge              local
fd6a89aad8ff        bridge              bridge              local
85ded5476b05        docker_gwbridge     bridge              local
d909a9f88b4c        host                host                local
z1sybtvc99hu        ingress             overlay             swarm
615a39ff6c47        none                null                local
```
Then we send an http request like the following pic, we found the status code is 500 which is not versioned in the swagger.yml nor api docs:

Second, we send a DELETE request for network `host`, then daemon will response a status code of 403 which is also not versioned in swagger.yml or api docs. Here is test pic:
wechatimg4

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
There is no status code 500 for api endpoint `GET /networks/(id or name), nor 404 for `DELETE /networks/(id or name)`

**Describe the results you expected:**
related status codes are versioned in doc

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 37
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 202
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: gkdoxio9hz1b325t544ftpry4
 Is Manager: true
 ClusterID: 3bidcebapq2115pts6cik50ah
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.59.103
 Manager Addresses:
  192.168.59.103:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: Q2ZC:GWDN:27OH:GRMH:G6QU:W7QP:4TIX:Q5F6:YEVK:45XP:EXHC:HOB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 132
 System Time: 2017-01-29T14:51:41.049720516+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://a.b.c/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

fixes https://github.com/docker/docker/issues/30698

**- What I did**
1. add status code 500 for api endpoint `GET /networks/(id or name)`, status code 500 is from https://github.com/docker/docker/blob/master/daemon/network.go#L61;
2. add status code 403 for api endpoint `DELETE /networks/(id or name)`, status code is from https://github.com/docker/docker/blob/master/daemon/network.go#L454;
3. update network api endpoints' url, replace `id` with `id or name`.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by allencloud** [comment]
CI fails in janky:
```
07:21:52 =================================== FAILURES ===================================
07:21:52 _______________ ArchiveTest.test_get_file_archive_from_container _______________
07:21:52 /docker-py/tests/integration/container_test.py:498: in test_get_file_archive_from_container
07:21:52     self.client.start(ctnr)
07:21:52 /docker-py/docker/utils/decorators.py:21: in wrapped
07:21:52     return f(self, resource_id, *args, **kwargs)
07:21:52 /docker-py/docker/api/container.py:383: in start
07:21:52     self._raise_for_status(res)
07:21:52 /docker-py/docker/client.py:177: in _raise_for_status
07:21:52     raise errors.APIError(e, response, explanation=explanation)
07:21:52 E   APIError: 500 Server Error: Internal Server Error ("endpoint with name epic_hermann already exists in network bridge")
07:21:52 ============== 1 failed, 118 passed, 3 skipped in 144.46 seconds ===============
```

I am afraid changed I made takes affect in docker-py, but I have no idea what to do in docker-py. 
Could you give me some guidance? ping @thaJeztah @vdemeester

**Comment by LK4D4** [comment]
ping @shin-

**Comment by shin-** [comment]
Looks like a random naming conflict - try kicking up the build again.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
verified with docker 1.9 for the older API versions

**Comment by justincormack** [comment]
The 500 status code is not correct - the request is invalid (multiple IDs match the short ID), not the server having a problem, it should be a 400 error. So we should not document it, we should fix.

I recommend http://racksburg.com/choosing-an-http-status-code/

**Comment by allencloud** [comment]
Thanks for the double check @thaJeztah
 
And thanks for your feedback, @justincormack . What you mentioned is reasonable, I think. At first, I think we should fix this without doubt. While maybe this is a two-phase work.

1. Since the old versions of docker suffer such improper status code of 500 for a long time, and these old versions' code has already frozen. As a result, I think what can do is add this status code of 500 in the old api docs to keep consistency. After all, api docs miss the status code, sometimes it may cause issues for user's experience with daemon's API.

2. fix this status code 500 to be a more accurate status code 400 in a follow-up PR.

WDYT? @justincormack

**Comment by allencloud** [comment]
ping @justincormack ^^

**Comment by allencloud** [comment]
I think now pr https://github.com/docker/docker/pull/30453 added code https://github.com/docker/docker/blob/master/api/server/router/network/network_routes.go#L147 and https://github.com/docker/docker/blob/master/api/server/router/network/network_routes.go#L157 in docker/master. And this pr introduced a kind of error which will be returned a status code of 500.

I think it seems OK for master to add 500. While for the legacy, any input? @justincormack @thaJeztah

**Comment by LK4D4** [comment]
ping @justincormack @thaJeztah

**Comment by allencloud** [comment]
ping @justincormack @thaJeztah 
Sorry for bothering you again. And I sincerely wish we could make this move on. This pr maybe could help something in improving the docs about status code.

Yeah, I totally agree on that `401` is better for multi networks matching. 

While for the old versions of Docker, they still lack the more precise status code `403` and `500` for `GET /networks/{id}` doc. 

In master, I think there some places which return 500 now, like:
```
        if err := httputils.ParseForm(r); err != nil {
		return err
	}
```
and 
```
return fmt.Errorf("network %s is ambiguous (%d matches found based on name)", term, len(listByFullName))
```

So, adding a 500 seems OK, but for 401 bad request, I think we need a follow-up. We should consider more about that, because `POST /networks/{id or nam}/connect` and `POST /networks/{id or name}/disconnect` should also be taken into consideration. WDYT?

**Comment by LK4D4** [comment]
ping @thaJeztah @justincormack

**Comment by allencloud** [comment]
Could we move on this pr currently, my friends? Any feedback helps. 😃

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by allencloud** [comment]
Seems, z and powerpc, there is always one who is naughty to pick errors 😄

**Pull request merged**
