### PR TITLE
Don't mount /proc as ro

### LINKED ISSUE #15135: [1.8.0-rc1] docker exec doesn't work on read-only containers
Reproducing:

```
docker run --read-only=true -it -d --name t1 busybox sh
docker exec t1 ls / # error: read-only file system
```

Regression point should be at #13669

```
> docker version
Client:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:
 OS/Arch:      linux/amd64
> docker info
Containers: 19
Images: 10
Storage Driver: aufs
 Root Dir: /home/vagrant/graph_root/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-34-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 1.462 GiB
Name: docker-vagrant
ID: PXAE:AAN7:YVY2:K4P6:KFZI:TKSX:UYRE:FW4R:PSYZ:2LOY:UYFK:V7TY
Debug mode (server): true
File Descriptors: 39
Goroutines: 28
System Time: 2015-07-29T23:09:35.606016507+03:00
EventsListeners: 0
Init SHA1:
Init Path: /home/vagrant/bundles/1.8.0-rc1/latest/binary/docker
Docker Root Dir: /home/vagrant/graph_root
WARNING: No swap limit support
> uname -a
Linux docker-vagrant 3.16.0-34-generic #45~14.04.1-Ubuntu SMP Tue Mar 24 11:14:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by crosbymichael**
This caused a regression with LSM labeling.

Fixes #15135

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by ewindisch** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by crosbymichael** [comment]
don't wait for the tests, just merge it, i'm a professional 
<a href="url"></a>

**Comment by ewindisch** [comment]
Failing on proc/<pid>/ns which can be ignored. Fix for that in #15161

**Comment by crosbymichael** [comment]
MERGE IT

<a href="url"></a>

**Comment by calavera** [comment]
@crosbymichael still failing:
```
FAIL: docker_cli_run_test.go:1993: DockerSuite.TestContainerNetworkMode

docker_cli_run_test.go:2006:
    c.Fatal(err)
... Error: readlink /proc/2415/ns/net: permission denied
```

**Comment by ewindisch** [comment]
@calavera  that's fixed in #15161 and is unrelated to this change

**Comment by tiborvass** [comment]
Fixes for failures in experimental were merged in #15161, and windows has unrelated urandom failures. Merging.

**Comment by calavera** [comment]
cherry picked into #15091

**Pull request merged**
