### PR TITLE
Moby Dev Report 2017 06 26

### PR DESCRIPTION
**Pull request by vieux**
ping @tonistiigi @thaJeztah @justincormack

### CODE REVIEW

**Comment by vieux** [comment]
@tonistiigi maybe the buildkit section should live in the buildkit repo in the future ?

**Comment by AkihiroSuda** [comment]
Can we have a link to lock-less docker ps?
https://github.com/moby/moby/issues/31273

**Comment by tonistiigi** [comment]
@vieux I don't care what repo but I'd prefer to write only one that has build topics.

The titles are bit off, the subtitles of builder are on the same level as linuxkit and packages.

**Review by thaJeztah — COMMENTED** [review]
content looks OK, but heading levels need some fixing (as @tonistiigi mentioned)

**Comment by vieux** [comment]
@AkihiroSuda @tonistiigi @thaJeztah PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by tiborvass** [comment]
@vieux there is builder material in the main one too, should probably be just a link.

**Pull request merged**
