### PR TITLE
Update API docs to show that /containers/{id}/kill returns HTTP 409

### LINKED ISSUE #36068: Update API docs to show that /containers/{id}/kill returns HTTP 409
**Description**

The [API docs](https://docs.docker.com/engine/api/v1.35/#operation/ContainerKill) for `containers/{id}/kill` say that this endpoint returns one of there HTTP error codes: 204, 404, 500.

But if you try to invoke this endpoint on a container with `exited` status, the API returns HTTP 409.

**Steps to reproduce the issue:**

```
# Container is created and exits. Then we try to send it a signal
curl --unix-socket /var/run/docker.sock -X POST http://localhost/containers/"$(docker run -d alpine echo 'hello'; sleep 1)"/kill -I


HTTP/1.1 409 Conflict
Api-Version: 1.32
Content-Length: 193
Content-Type: application/json
Date: Sat, 20 Jan 2018 00:48:13 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/17.09.1-ce (linux)
```

**Describe the results you expected:**
Expected this HTTP error code to be documented in the API docs.

**Output of `docker version`:**

```
docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### PR DESCRIPTION
**Pull request by shutefan**
Resolves #36068

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for contributing! I'd like to have a quick check with other maintainers to verify if 409 is also the _correct_ status code in this situation, or if this endpoint was intended to be idempotent (i.e. the container was already killed), in which case this would be a bug.

**Comment by thaJeztah** [comment]
Discussing in the maintainers meeting; and `kill` is not just for killing the container, but to signal the process; if the container is not running we cannot signal it, so 409 is probably the correct status code

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🌯

**Pull request merged**
