### PR TITLE
Bump swarmkit to 0fe3f12bdbfee0d47216de0118c569b1042e1588

### PR DESCRIPTION
**Pull request by thaJeztah**
Full diff: https://github.com/docker/swarmkit/compare/bd69f6e8e301645afd344913fa1ede53a0a111fb...0fe3f12bdbfee0d47216de0118c569b1042e1588

Changes included:

- docker/swarmkit#2594 [fips] Support a flag that indicates that the cluster requires mandatory FIPS mode on all nodes
- docker/swarmkit#2586 [fips] Propagate the FIPS boolean to the manager, raft storage layer, and raft DEK management
- docker/swarmkit#2452 vendor: update gRPC, protobuf
- docker/swarmkit#2644 Bump CFSSL
- docker/swarmkit#2635 Minor cleanup of raft encryption algorithms
- docker/swarmkit#2622 [docs] Document how raft encryption works
- docker/swarmkit#2652  Fix `deepcopy.Copy` panicing with BoolValue

Updated vendors related to the above;
- update google.golang.org/grpc to v1.7.5 (full diff: https://github.com/grpc/grpc-go/compare/v1.3.0...v1.7.5)
- update github.com/gogo/protobuf to v0.5 (full diff: https://github.com/gogo/protobuf/compare/v0.4...v0.5)
- update github.com/golang/protobuf to 1e59b77b52bf8e4b449a57e6f79f21226d571845 (full diff: https://github.com/golang/protobuf/compare/7a211bcf3bce0e3f1d74f9894916e6f116ae83b4...1e59b77b52bf8e4b449a57e6f79f21226d571845)

### Bump Google Cloud SDK for gRPC 
- golang.org/x/oauth2 https://github.com/golang/oauth2/compare/96382aa079b72d8c014eb0c50f6c223d1e6a2de0...cdc340f7c179dbbfa4afd43b7614e8fcadde4269
- google.golang.org/api https://github.com/google/google-api-go-client/compare/3cc2e591b550923a2c5f0ab5a803feda924d5823...d7aa31fbd7da4467a8056610e654315a4c1f068e
- cloud.google.com/go https://github.com/GoogleCloudPlatform/google-cloud-go/compare/9d965e63e8cceb1b5d7977a202f0fcb8866d6525...v0.22.0
  - Before this we were roughly on v0.6.0; https://github.com/GoogleCloudPlatform/google-cloud-go/compare/9d965e63e8cceb1b5d7977a202f0fcb8866d6525...v0.6.0
- github.com/googleapis/gax-go https://github.com/googleapis/gax-go/compare/da06d194a00e19ce00d9011a13931c3f6f6887c7...de2cc08e690b99dd3f7d19937d80d3d54e04682f
- google.golang.org/genproto https://github.com/google/go-genproto/compare/d80a6e20e776b0b17a324d0ba1ab50a39c8e8944...7bb2a897381c9c5ab2aeb8614f758d7766af68ff
- go.opencensus.io v0.9.0

### Update gRPC, protobuf, to match containerd 1.1.0

- google.golang.org/grpc https://github.com/grpc/grpc-go/compare/v1.7.5...v1.10.1
- github.com/golang/protobuf https://github.com/golang/protobuf/compare/1e59b77b52bf8e4b449a57e6f79f21226d571845...v1.1.0
- github.com/gogo/protobuf https://github.com/gogo/protobuf/compare/v0.5...v1.0.0
- github.com/cloudflare/cfssl https://github.com/cloudflare/cfssl/7fb22c8cba7ecaf98e4082d22d65800cf45e042a...1.3.2
- github.com/google/certificate-transparency-go https://github.com/google/certificate-transparency-go/compare/d90e65c3a07988180c5b1ece71791c0b6506826e...05f3323c246e07b553be6d6eea92ee871d716dbb
- golang.org/x/crypto https://github.com/golang/crypto/compare/558b6879de74bc843225cde5686419267ff707ca...1a580b3eff7814fc9b40602fd35256c63b50f491

### Update BuildKit and dependencies

Updates BuildKit to current master (github.com/moby/buildkit): https://github.com/moby/buildkit/compare/be6da00944c2adebb9b8bac9176d5c6e88aa2b61...7a4a2a2d8dda82e6652fe4af9abb3a460408389f

Update vendored dependencies to match BuildKit:

- add github.com/grpc-ecosystem/grpc-opentracing dependency
- add github.com/opentracing/opentracing-go dependency
- downgrade github.com/pkg/errors to a tagged release: https://github.com/pkg/errors/compare/v0.8.0...839d9e913e063e28dfd0e6c7b7512793e0a48be9
- github.com/containerd/continuity https://github.com/containerd/continuity/compare/d8fb8589b0e8e85b8c8bbaa8840226d0dfeb7371...3e8f2ea4b190484acb976a5b378d373429639a1a
  - containerd/continuity#110 Add fstest.CreateSocket
- github.com/containerd/fifo https://github.com/containerd/fifo/compare/fbfb6a11ec671efbe94ad1c12c2e98773f19e1e6...3d5202aec260678c48179c56f40e6f38a095738c
  - Add apache license to files
- github.com/containerd/go-runc https://github.com/containerd/go-runc/compare/4f6e87ae043f859a38255247b49c9abc262d002f...f271fa2021de855d4d918dbef83c5fe19db1bdd5
  - containerd/go-runc#37 runc: be able to get the full ps data (ps -f table)
  - containerd/go-runc#40 Add ConsoleSocket to RestoreOpts
- github.com/containerd/console https://github.com/containerd/console/compare/2748ece16665b45a47f884001d5831ec79703880...cb7008ab3d8359b78c5f464cb7cf160107ad5925
  - containerd/console#21 Add OpenBSD support
- github.com/syndtr/gocapability https://github.com/syndtr/gocapability/compare/2c00daeb6c3b45114c80ac44119e7b8801fdd852...db04d3cc01c8b54962a58ec7e491717d06cfcc16
  - syndtr/gocapability#11 Add support for ambient capabilities
  - syndtr/gocapability#13 Fix issue #12: break too early
- golang.org/x/net https://github.com/golang/net/compare/5561cd9b4330353950f399814f427425c0a26fd2...0ed95abb35c445290478a5348a7b38bb154135fd
- golang.org/x/text https://github.com/golang/text/compare/f72d8390a633d5dfb0cc84043294db9f6c935756...19e51611da83d6be54ddafce4a4af510cb3e9ea4
- golang.org/x/time https://github.com/golang/time/compare/a4bde12657593d5e90d0533a3e4fd95e635124cb...f51c12702a4d776e4c1fa9b0fabab841babae631
- github.com/tonistiigi/fsutil https://github.com/tonistiigi/fsutil/compare/dea3a0da73aee887fc02142d995be764106ac5e2...93a0fd10b669d389e349ff54c48f13829708c9b0
  - tonistiigi/fsutil#16 Don not hang on diskwriter errors
  - tonistiigi/fsutil#17 fix fd leak on send
  - tonistiigi/fsutil#18 avoid possible receiver panic/deadlock on sender error
  - tonistiigi/fsutil#20 receive: read stream to EOF on close
  - tonistiigi/fsutil#21 avoid not-exist error on walker
  - tonistiigi/fsutil#27 Generalize chtimes() implementation for non-linux platforms
  - tonistiigi/fsutil#28 walker: handle parents and subdirs in includepatterns

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cyli PTAL

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Bumped once more to include https://github.com/docker/swarmkit/pull/2452

**Comment by cpuguy83** [comment]
Compile issues.

**Comment by thaJeztah** [comment]
dang; looks like issues in other vendors 😓

**Review by cyli — APPROVED** [review]
The changes themselves LGTM - the API changes are just in swarmkit, and the FIPS boolean will just be false here since it's not routed through to the engine.

Sorry about the vendor issues :|

**Comment by thaJeztah** [comment]
Bumped BuildKit a bit, and looks to be building now (CI is down, so don't know if it passes)

**Comment by thaJeztah** [comment]
^^ WARNING: CI is down; don't be fooled an think it's green 😅

**Comment by thaJeztah** [comment]
```
01:02:40 integration/build/build_session_test.go:88:34:warning: cannot use "foo1" (constant of type string) as context.Context value in argument to session.NewSession: missing method Deadline (gosimple)
01:02:40 integration/build/build_session_test.go:88:47:warning: too few arguments in call to session.NewSession (gosimple)
```

**Comment by thaJeztah** [comment]
Looks like `TestAPISwarmLeaderElection` (https://github.com/moby/moby/issues/32673) is still flaky (or more broken and now consistently failing), but now returning a different error message;

```
15:45:59 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
15:45:59 
15:45:59 [d41490226b62f] waiting for daemon to start
15:45:59 [d41490226b62f] daemon started
15:45:59 
15:45:59 [d806245312d30] waiting for daemon to start
15:45:59 [d806245312d30] daemon started
15:45:59 
15:45:59 [d240dbf1808f3] waiting for daemon to start
15:45:59 [d240dbf1808f3] daemon started
15:45:59 
15:45:59 [d41490226b62f] exiting daemon
15:45:59 assertion failed: error is not nil: Error response from daemon: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
15:45:59 [d806245312d30] exiting daemon
15:45:59 [d240dbf1808f3] exiting daemon
15:46:14 
```

**Comment by vdemeester** [comment]
@thaJeztah rebased and updated swarmkit and updated the description

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by thaJeztah** [comment]
hmf, looks like we need to re-vndr; 

```
13:08:18  M vendor/github.com/containerd/continuity/fs/copy.go
13:08:18  M vendor/github.com/containerd/continuity/fs/copy_linux.go
13:08:18  M vendor/github.com/containerd/continuity/sysx/xattr_linux.go
13:08:18 ?? vendor/github.com/containerd/continuity/sysx/xattr_linux_386.go
13:08:18 ?? vendor/github.com/containerd/continuity/sysx/xattr_linux_amd64.go
13:08:18 ?? vendor/github.com/containerd/continuity/sysx/xattr_linux_arm.go
13:08:18 ?? vendor/github.com/containerd/continuity/sysx/xattr_linux_arm64.go
13:08:18 ?? vendor/github.com/containerd/continuity/sysx/xattr_linux_ppc64.go
13:08:18 ?? vendor/github.com/containerd/continuity/sysx/xattr_linux_ppc64le.go
13:08:18 ?? vendor/github.com/containerd/continuity/sysx/xattr_linux_s390x.go
```

**Comment by vdemeester** [comment]
Rebased :sweat_smile:

**Comment by vdemeester** [comment]
```
09:06:40 --- FAIL: TestLocalVolumeSize (0.00s)
09:06:40 	service_linux_test.go:66: assertion failed: 1024 (ls[1].UsageData.Size int64) != 1 (int64)
09:06:40 FAIL
```

Flaky unit tests ? can't reproduce this failure on my laptop...

**Comment by vdemeester** [comment]
@thaJeztah I guess this has been "taken over" by https://github.com/moby/moby/pull/36895, am I right ?

**Comment by thaJeztah** [comment]
Yes, let's close this one; there's some dependencies that could be updated, but we can do separate

**Pull request closed without merging**
