### PR TITLE
api/server/httputils: compile with go < 1.7 (WriteJSON)

### PR DESCRIPTION
**Pull request by runcom**
See https://github.com/docker/docker/pull/27060#issuecomment-251342716
#27060 broke compatibility with golang < 1.7. This patch should restore it. Testing with golang 1.6.x, 1.7.x and master.

@vdemeester @thaJeztah PTAL

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐸 :sweat_smile:

**Comment by justincormack** [comment]
LGTM

**Comment by justincormack** [comment]
Windows failure unrelated.

**Pull request merged**
