### PR TITLE
Add test TestRestartPolicyWithLiveRestore

### PR DESCRIPTION
**Pull request by tonistiigi**
Bring in test from #29643 . The issue itself does not apply to master but it would be useful to have a testcase for this logic.

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM (nam)

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by mlaventure** [comment]
LGTM, small conflict to be resolved.

**Comment by tonistiigi** [comment]
Updated to take out the sleep constant. PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
