### PR TITLE
Fix ambassador script

### PR DESCRIPTION
**Pull request by aidanhs**
based on SvenDowideit/dockerfiles#37

Requires that to be merged first, and the image on the docker hub needs to be updated. @SvenDowideit

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @SvenDowideit, I'll assign this to you :smile:

**Comment by tiborvass** [comment]
Ping @SvenDowideit

**Comment by SvenDowideit** [comment]
merged upstream,  LGTM - @moxiegirl @thaJeztah

**Comment by thaJeztah** [comment]
cool, thanks!

LGTM

**Pull request merged**
