### PR TITLE
devicemapper: API for cookie support

### PR DESCRIPTION
**Pull request by vbatts**
devicemapper API for cookie support

Signed-off-by: Vincent Batts vbatts@redhat.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
:cookie:

**Comment by vbatts** [comment]
10sec in the microwave

**Comment by jfrazelle** [comment]
:clap:

**Comment by vbatts** [comment]
I had more cookies for devicemapper, but the docker project Dockerfile doesn't support the functions :-(

**Comment by vbatts** [comment]
rebased. PTAL

**Comment by icecrime** [comment]
LGTM

**Comment by icecrime** [comment]
Just FYI: we confirmed on IRC that this adds mapping for a new API which *isn't yet used* in Docker, so no expected side effects. (cc @unclejack)

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
