### PR TITLE
vendor notary for docker1.11

### PR DESCRIPTION
**Pull request by riyazdf**
This vendors Notary for Docker 1.11 -- this version of Notary doesn't fallback when attempting to sign delegation roles, and instead leaves this logic to Docker (handled in #21046). Also general improvements  and fixes around error messaging, passphrase handling, and metadata manipulation and validation.

Signed-off-by: Riyaz Faizullabhoy riyaz.faizullabhoy@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Tests are failing;

```
18:17:43 ----------------------------------------------------------------------
18:17:43 FAIL: docker_cli_build_test.go:5713: DockerTrustSuite.TestTrustedBuild
18:17:43 
18:17:43 docker_cli_build_test.go:5714:
18:17:43     repoName := s.setupTrustedImage(c, "trusted-build")
18:17:43 github.com/docker/docker/integration-cli/_test/_obj_test/trust_server.go:235:
18:17:43     ...open github.com/docker/docker/integration-cli/_test/_obj_test/trust_server.go: no such file or directory
18:17:43 ... Error: Error running trusted push: exit status 1
18:17:43 The push refers to a repository [127.0.0.1:5000/dockercli/trusted-build]
18:17:43 5f70bf18a086: Preparing
18:17:43 9508eff2c687: Preparing
18:17:43 5f70bf18a086: Pushed
18:17:43 9508eff2c687: Pushed
18:17:43 latest: digest: sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8 size: 711
18:17:43 Signing and pushing trust metadata
18:17:43 Finished initializing "127.0.0.1:5000/dockercli/trusted-build"
18:17:43 time="2016-03-17T18:17:43Z" level=error msg="couldn't add target to targets/releases: tuf: invalid role targets/releases. delegation does not exist" 
18:17:43 tuf: invalid role targets/releases. delegation does not exist
18:17:43 
```

**Comment by riyazdf** [comment]
@thaJeztah yeah, this vendor won't pass CI until #21046 is merged, but we wanted to keep this vendoring as a separate PR from the docker feature itself -- I'll make sure to rebase and ping once this is ready :)

**Comment by thaJeztah** [comment]
Ping @riyazdf https://github.com/docker/docker/pull/21046 was merged

**Comment by thaJeztah** [comment]
Oh, perhaps it was updated already :smile:

**Comment by icecrime** [comment]
LGTM

**Comment by riyazdf** [comment]
@thaJeztah I updated this PR earlier but I'm currently trying to update again with a further vendor of notary, I'll ping back once this is no longer WIP

**Comment by riyazdf** [comment]
ping @thaJeztah @icecrime, no longer WIP and ready for review :)

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
Janky is hitting #19368 which was supposed to be fixed by #20246 :(

**Comment by icecrime** [comment]
@riyazdf Needs a rebase :-(

**Pull request merged**
