### PR TITLE
plugin/store.Get: return a specific error if plugin is disabled

### PR DESCRIPTION
**Pull request by dsheets**
**- What I did**

Previously, a 'plugin not found' error would be returned if a plugin to be retrieved was found but disabled. This was misleading and incorrect. Now, a new error `plugin.ErrDisabled` is returned in this case. This makes the error message when trying to statically start plugins (from `daemon.json` or `dockerd` command line) accurate.

**- How I did it**

I created a new type alias `ErrDisabled` to mirror `ErrNotFound` and `ErrAmbiguous`. It satisfies the `error` interface.

**- How to verify it**

```
docker plugin install --grant-all-permissions riyaz/authz-no-volume-plugin
docker plugin disable riyaz/authz-no-volume-plugin
```

then restart `dockerd` and add `--authorization-plugin=riyaz/authz-no-volume-plugin` to the command line. `docker.log` will then have the "found but disabled" message instead of the "not found" message.

I tried to write a test for this but I couldn't figure out how to match on the daemon log error.

**- Description for the changelog**

Probably does not deserve a changelog entry but if you add one:

"Improved error message when trying to start daemon with installed but disabled plugin"

**- A picture of a cute animal (not mandatory but encouraged)**

Suncus etruscus
By Trebol-a - Own work, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=4607913

[*Suncus etruscus*](https://en.wikipedia.org/wiki/Etruscan_shrew), the Etruscan shrew, is the smallest known mammal by mass and consumes 1.5-2x its own body weight in food per day. It has a very high heart rate of up to 1511 beats/minute.

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

libnetwork is consuming this error, but the usage doesn't seem to change at all by changing the error here.

ping @sanimej

**Review by thaJeztah — APPROVED** [review]
LGTM as well, but ping @sanimej if changes are needed in libnetwork

**Comment by sanimej** [comment]
The way the plugin errors are getting used is incorrect. For ex: libnetwork references the `ErrNotFound` error from docker/pkg/plugins package. But the plugingetter's Get returns `ErrNotFound` (or any other for matter) defined in plugin package. So the equality check is not going work. We can move the error definitions from plugin/store.go to pkg/plugins ?

This is an existing issue and not specific to this PR. We can either address it here or do it as a separate PR.

**Comment by cpuguy83** [comment]
Ugh, I'd prefer not to expand the surface area of plugingetter.

**Comment by sanimej** [comment]
plugingetter doesn't have to change. We can move the error types defined in plugin/store.go to pkg/plugins/discovery.go. Since pkg/plugins is included by the plugin package and the clients (like libnetwork) as well the same type will get used.

**Comment by sanimej** [comment]
I don't want to block this PR though. This LGTM. Lets fix the incorrect error type reference in a separate PR.

**Comment by thaJeztah** [comment]
ping @sanimej were you planning on working on those changes, or do we have to open an issue for tracking that?

**Pull request merged**
