### PR TITLE
Add docs checking Jenkinsfile

### PR DESCRIPTION
**Pull request by SvenDowideit**
converting manually administered docs jenkins checkers to Jenkinsfile pipeline.

### CODE REVIEW

**Comment by vdemeester** [comment]
Hum the name appearing in the github checks is weird (`continous-integration/jenkins/pr-merge`) and it never get the status back…

**Comment by SvenDowideit** [comment]
Looks like the status came back :)

wrt the name - yeah - that's a @mikedougherty thing - I don't control that.

**Comment by mikedougherty** [comment]
LGTM

**Comment by cpuguy83** [comment]
@mikedougherty How do we change the check names?

**Comment by mikedougherty** [comment]
it doesn't seem to be supported by the plugin at the moment. there's at least [one ticket](https://issues.jenkins-ci.org/browse/JENKINS-35453) i found related to it, but no idea when any changes will land.

this particular context string mimics the ones that travis CI and appveyor use (e.g. you can see "continuous-integration/appveyor/pr" on this [compose pr](https://github.com/docker/compose/pull/3871)) so it seems appropriate to me?

**Comment by cpuguy83** [comment]
Only appropriate if it was running the main CI, but it's only running docs.

**Comment by SvenDowideit** [comment]
While its nice that you guys are holding up this change just because you don't like the colour of the bike-shed - every other Docker project, internally and externally is now using this exact same Jenkinsfile pipeline.

I'd suggest you get over it, merge this, and then if you really care about the words make a PR to Jenkins pipeline to make it configurable.

**Comment by vdemeester** [comment]
@SvenDowideit fair enough :angel: 
LGTM 🐸

**Comment by thaJeztah** [comment]
ping @cpuguy83 is this ready to go?

**Comment by dnephin** [comment]
Now that docs have been moved to another repo this PR is no longer relevant

**Pull request closed without merging**
