### PR TITLE
chore: fix mismatched function names in godoc

### PR DESCRIPTION
**Pull request by availhang**
fix mismatched function names in godoc

### CODE REVIEW

**Review by neersighted — APPROVED** [review]
LGTM with a couple nits:
* Please update the PR body with what you did
* Could you make the commit message more descriptive? e.g. `chore: fix mismatched function names in godoc`
* Would you please mind committing under and signing off your commits with [your name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work)?

**Comment by availhang** [comment]
> LGTM with a couple nits:
> 
> * Please update the PR body with what you did
> * Could you make the commit message more descriptive? e.g. `chore: fix mismatched function names in godoc`
> * Would you please mind committing under and signing off your commits with [your name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work)?



> * fix mismatched function names in godoc



> LGTM with a couple nits:
> 
> * Please update the PR body with what you did
> * Could you make the commit message more descriptive? e.g. `chore: fix mismatched function names in godoc`
> * Would you please mind committing under and signing off your commits with [your name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work)?

Of course. Thanks.


Modified,Please review again.

**Comment by neersighted** [comment]
Looks good with the exception of the name; I see "George Ma" is the name on your GitHub profile. Would you mind using that for both the commit and the sign-off, unless there is another name more associated with you as a person?

**Comment by availhang** [comment]
> Looks good with the exception of the name; I see "George Ma" is the name on your GitHub profile. Would you mind using that for both the commit and the sign-off, unless there is another name more associated with you as a person?

Thanks.

Modified

**Comment by neersighted** [comment]
You'll need to change the committer name to match to make the DCO check pass: https://github.com/moby/moby/pull/47613/checks?check_run_id=22967618835

**Comment by availhang** [comment]
> You'll need to change the committer name to match to make the DCO check pass: https://github.com/moby/moby/pull/47613/checks?check_run_id=22967618835

Sorrry, should I use George Ma or availhang?

**Comment by availhang** [comment]
> George Ma -- the check requires it to match the sign-off.

Thank you, it seems that all CIs have been approved

**Review by neersighted — APPROVED** [review]

**Pull request merged**
