### PR TITLE
Fix incorrect loop variable usage in parallel test closures

### PR DESCRIPTION
**Pull request by rvolosatovs**
**- What I did**

Ensure that loop variables are copied for use within parallel test closures.

**- How I did it**
Discovered a few instances, where loop variable is incorrectly used
within a test closure, which is marked as parallel while working on #42559 
Few of these were actually loops over singleton slices, therefore the issue
might not have surfaced there (yet), but it is good to fix there as
well, as this is an incorrect pattern used across different tests.

There could potentially be (many) more, I just did a simple search for loops using `ep` within `/integration` and fixed incorrect usages. Perhaps a good idea to verify this across codebase as the next step?

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

I'm sure there's more like these. I recall there's a linter for this as well, but it's probably not enabled in our CI (we should do so)

**Comment by thaJeztah** [comment]
Hmm interesting;

```
=== RUN   TestContainerInvalidJSON//containers/foobar/copy
=== PAUSE TestContainerInvalidJSON//containers/foobar/copy
=== CONT  TestContainerInvalidJSON//containers/foobar/copy
=== CONT  TestContainerInvalidJSON//containers/foobar/copy
    container_test.go:28: assertion failed: 404 (res.StatusCode int) != 400 (http.StatusBadRequest int)
    --- FAIL: TestContainerInvalidJSON//containers/foobar/copy (0.00s)

**Comment by rvolosatovs** [comment]
Looks like the endpoint was deprecated in https://github.com/moby/moby/pull/22149. Removed the test, since the endpoint returns an error since 1.12.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@cpuguy83 @AkihiroSuda ptal

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
