### PR TITLE
Cleanup: Factor cmdAttempt out of cli.clientRequestAttemptLogin

### PR DESCRIPTION
**Pull request by devx**
The function cli.clientRequestAttemptLogin is doing to many things. I factored out the anonymous function that is assigned to cmdAttempt out; to it's own function thus making the code more readable and easier to maintain.

Signed-off-by: Victor Palma palma.victor@gmail.com

### CODE REVIEW

**Comment by devx** [comment]
Failure is not due to code but probably due to host machine running the test:

 retrying: open /dev/urandom: operation not permitted

----------------------------------------------------------------------
FAIL: docker_cli_run_test.go:555: DockerSuite.TestRunEnvironmentErase

docker_cli_run_test.go:583:
    c.Fatalf("Wrong environment: should be %d variables, not: %q\n", len(goodEnv), strings.Join(actualEnv, ", "))
... Error: Wrong environment: should be 2 variables, not: "2015/07/21 16:04:11 error generating version 4 uuid, retrying: open /dev/urandom: operation not permitted, HOME=/root, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

**Comment by devx** [comment]
This seems to be a host issue:

**open /dev/urandom: operation not permitted**

```
FAIL: docker_cli_run_test.go:2472: DockerSuite.TestRunCapAddCHOWN

docker_cli_run_test.go:2476:
    c.Fatalf("expected output ok received %s", actual)
... Error: expected output ok received 2015/07/21 18:26:05 error generating version 4 uuid, retrying: open /dev/urandom: operation not permitted
ok
```

**Comment by cpuguy83** [comment]
I'm on the fence on this re-factoring, but won't block.
LGTM.

ping @calavera

**Comment by calavera** [comment]
I like it, thank you!

Merging :tada:

**Pull request merged**
