### PR TITLE
Add zsh completion for 'docker stack' subcommand

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. ##28677, #28815

Side note: `docker stack ls` should have a `list` alias to be consistent with other `ls` commands.

Signed-off-by: Steve Durrheimer <s.durrheimer@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by albers** [comment]
> Side note: docker stack ls should have a list alias to be consistent with other ls commands.

The alias exists, but it is missing in the docs. I created #28865 for that.

```bash
$ docker stack ls --help

Usage:  docker stack ls

List stacks

Aliases:
  ls, list

Options:
      --help   Print usage
```

**Comment by sdurrheimer** [comment]
Ok `list` alias added.

**Comment by LK4D4** [comment]
LGTM

**Review by dnephin — COMMENTED** [review]
LGTM

**Pull request merged**
