### PR TITLE
Remove some redundant code and cleanup validation

### PR DESCRIPTION
**Pull request by thaJeztah**
See individual commits for details

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM if green :tiger:

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by vdemeester** [comment]
```
06:59:17 === RUN   TestCheckpoint
06:59:18 --- FAIL: TestCheckpoint (1.59s)
06:59:18     checkpoint_test.go:40: Error (criu/util.c:816): exited, status=3
06:59:18         Warn  (criu/net.c:2840): Unable to get socket network namespace
06:59:18         Warn  (criu/net.c:2840): Unable to get tun network namespace
06:59:18         Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
06:59:18         Warn  (criu/net.c:2840): Unable to get socket network namespace
06:59:18         Warn  (criu/kerndat.c:881): Can't keep kdat cache on non-tempfs
06:59:18         Looks good.
06:59:18     checkpoint_test.go:51: Start a container
06:59:18     checkpoint_test.go:69: ++ type -P true
06:59:18         ++ type -P ip6tables-restore
06:59:18         + mount --bind /bin/true /sbin/ip6tables-restore
06:59:18         ++ type -P true
06:59:18         ++ type -P ip6tables-save
06:59:18         + mount --bind /bin/true /sbin/ip6tables-save
06:59:18     checkpoint_test.go:81: Do a checkpoint and leave the container running
06:59:18     checkpoint_test.go:24: Exec: [touch /tmp/test-file]
06:59:18     checkpoint_test.go:28: 
06:59:18     checkpoint_test.go:115: Do a checkpoint and stop the container
06:59:18     checkpoint_test.go:144: Restore the container
06:59:18     checkpoint_test.go:146: assertion failed: error is not nil: Error response from daemon: failed to upload checkpoint to containerd: commit failed: content sha256:d577e54a7a0fb20548164606d7b6249d03027e5821101abe80fe1fca7f8c7cb8: already exists
06:59:18     checkpoint_test.go:77: ++ type -P ip6tables-restore
06:59:18         + umount -c -i -l /sbin/ip6tables-restore
06:59:18         ++ type -P ip6tables-save
06:59:18         + umount -c -i -l /sbin/ip6tables-save
```

**Comment by thaJeztah** [comment]
I think that test was added recently; looks like this is the failure;

```
Error response from daemon: failed to upload checkpoint to containerd: commit failed: content sha256:d577e54a7a0fb20548164606d7b6249d03027e5821101abe80fe1fca7f8c7cb8: already exists

**Pull request merged**
