### PR TITLE
Fix api/containers/commit calling builder.Commit

### PR DESCRIPTION
**Pull request by cpuguy83**
This API is not a builder API and shouldn't be calling it.
Furthermore, the builder's own commit call was calling daemon.Commit and
nothing else was using builder.Commit other than api/containers/commit

### CODE REVIEW

**Comment by cpuguy83** [comment]
Found this while reviewing #15568

ping @LK4D4 @jfrazelle

**Comment by cpuguy83** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
I think this is in the wrong place. The filesystem commit is called in more places than just the docker commit command and should not be blocked generally on Windows.

**Comment by cpuguy83** [comment]
Nevermind, there's a bigger issue here because of things like `--changes LABEL`...
Closing for now.

**Pull request closed without merging**
