### PR TITLE
Add maximum egress bandwidth option for Windows containers

### PR DESCRIPTION
**Pull request by darstahl**
Added network maximum egress bandwidth control for Windows containers via a new CLI flag `--net-maxbandwidth`, which sets a generic option added to the Windows libnetwork driver with https://github.com/docker/libnetwork/pull/1061

Corgi!

**TODO**
- [x] engine-api changes in https://github.com/docker/engine-api/pull/180 merged and re-vendored
- [x] libnetwork changes in https://github.com/docker/libnetwork/pull/1061 merged and re-vendored

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
@darrenstahlmsft is this still WIP, or ready for review?

**Comment by darrenstahlmsft** [comment]
Sorry, was waiting on vendor but CI was being weird. This is ready for review now.

**Comment by jhowardmsft** [comment]
Design LGTM.

**Comment by thaJeztah** [comment]
Design LGTM

**Comment by unclejack** [comment]
Folks, why would we add this new flag? It doesn't seem OK to me to have a flag like this. We should have something similar to `--storage-opt` for networking, e.g. `--network-opt` or something. `--network-opt` would let us have something extensible.

I'm not OK with this design because it introduces flag pollution.

**Comment by jhowardmsft** [comment]
Has the horse not already left the stable though - look for example at --device-read and --device-write and prime examples, and further the current set of network related options from `docker run --help`

**Comment by unclejack** [comment]
@jhowardmsft The fact that it's bad doesn't mean we should keep making it worse.

**Comment by thaJeztah** [comment]
I must admit that I like the suggestion of `--network-opt`

**Comment by unclejack** [comment]
`docker run` has a lot of flags already and we might want to try to think of ways to avoid adding many more. Today, we'd only be adding egress bandwidth limiting through a flag, but we might need to add something similar or something we're not aware of right now. Adding that new option would mean that we need to add yet one more flag to an already large number of flags.

`--storage-opt` enables us to set options per container for the storage driver with a single flag and without having Docker know the flags for every individual storage driver. I think we should do the same for networking to enable the same thing for network drivers. We can avoid having too many flags and having too many dedicated fields to store these options.

**Comment by cpuguy83** [comment]
ping @mavenugo 

Ideally this would lineup with whatever kind of solution we come up with for the linux side as well.
I'm not sure `network-opt` is great, especially since we probably don't want this to be driver dependent (if implemented on linux).

**Comment by thaJeztah** [comment]
ping @mavenugo could you have a look?

**Comment by mavenugo** [comment]
There are no driver specific knobs to the `docker run` command and for a very good reason. Any network option that we have in `docker run` is managed by libnetwork core and brings in consistency across drivers to provide portability guarantees.

I agree that we should not masquerade a driver specific option as a top-level flag and confuse the users when it is clearly not applicable to other drivers. If we come up with a `network-opt` like feature, then the container becomes a non-portable entity across network drivers.

We had multiple discussions on similar ops centric policies not able to find its place in `docker run` command-line. The more we discuss on such topics, the more am convinced that we should absolutely come up with a policy framework that is Ops focussed and assigned to a network (rather than individual containers). That provides a way for containers to be defined free of Ops specific requirements and also Ops have full control over how containers are deployed.

Hence atm am -1 on the design.

**Comment by jainvipin** [comment]
agree with @mavenugo; IMHO, it needs to fold into the umbrella of an ops policy; if a container can be associated with an ops policy that can have some of the network params a network/service is associated with - it would work and be very generic.

**Comment by icecrime** [comment]
Agree with @mavenugo and @unclejack.

Shall we revert engine-api#180?

**Comment by thaJeztah** [comment]
Looks like this should be closed. Can someone open a PR to revert https://github.com/docker/engine-api/pull/180 ?

**Pull request closed without merging**
