### PR TITLE
renaming id() to state clearly that it's related to the networkAttachment

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <yasstij11@gmail.com>

**- What I did** : little renaming, see #33679 

ping @stevvooe @thaJeztah

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by stevvooe** [comment]
LGTM

woooo!

**Review by stevvooe — APPROVED** [review]

**Comment by thaJeztah** [comment]
all green, merging! thanks so much!

**Comment by yastij** [comment]
@thaJeztah @stevvooe see you on next PR 😄

**Pull request merged**
