### PR TITLE
Minor grammar fix in Docs/Userguide/Labels

### PR DESCRIPTION
**Pull request by daviddyball**

### CODE REVIEW

**Comment by daviddyball** [comment]
Thanks @GordonTheTurtle, pushed a signed version just now.

**Comment by SvenDowideit** [comment]
LGTM - @thaJeztah @moxiegirl

**Comment by vdemeester** [comment]
Note that this is kinda changed by #15903 I think :sweat_smile:

**Comment by daviddyball** [comment]
Closing in favour of #15903 as it replaces the text anyway. Thanks for pointing that out @vdemeester

**Comment by thaJeztah** [comment]
Thanks for contributing @daviddyball !

**Pull request closed without merging**
