### PR TITLE
17982 integrate `--push` with `docker build`  

### LINKED ISSUE #17982: Feature request: docker build could have the ability to `--push`
`docker-build` should be able to `--push` images or individual layers while they are being built to the registry. Each layer once built can be pushed asynchronously (better option) or once the images are built completely.

### PR DESCRIPTION
**Pull request by askb**
This is a PR integrates the `--push` with `docker build` (fixes #17982). When `$ docker build --push -t 192.168.1.34:5000/mytestimage .` is run the output looks like the following:

```
root@018e57a77eb2:/go/src/github.com/docker/docker/mytestimage# docker build --pull --push -t 192.168.1.34:5000/mytestimage .
Sending build context to Docker daemon 32.77 kB
Step 1 : FROM 192.168.1.34:5000/ubuntu:latest
latest: Pulling from ubuntu
c63fb41c2213: Pull complete 
99fcaefe76ef: Pull complete 
5a4526e952f0: Pull complete 
1d073211c498: Pull complete 
Digest: sha256:30550d609f2de731f61ad154ee50b267bec31ca373eaf424b8adbc836dc17f70
Status: Downloaded newer image for 192.168.1.34:5000/ubuntu:latest
 ---> 1d073211c498
Step 2 : RUN apt-get install -y         iputils-ping
 ---> Running in 98d83439c38d
Reading package lists...
Building dependency tree...
Reading state information...
iputils-ping is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 ---> b94994b8249b
Removing intermediate container 98d83439c38d
Step 3 : ENV var1 ping var2 8.8.8.8
 ---> Running in 8f868ae6247e
 ---> d3ae5eface6d
Removing intermediate container 8f868ae6247e
Step 4 : CMD $var1 $var2
 ---> Running in f67f0d84fb63
c63fb41c2213: Pushed 
99fcaefe76ef: Pushed 
5a4526e952f0: Pushed 
The push refers to a repository [192.168.1.34:5000/mytestimage] (len: 1)
42fc980d80ff: Pushed 
d3ae5eface6d: Pushed 
b94994b8249b: Pushed 
latest: digest: sha256:dc962174740386ddddf6df85f00ebb1e330cc9ff5d642534bdbe2aabc7601f2c size: 12573
```

Changes include: 
- Modified `type Config struct`, added member `Push` of bool type.
- Updated `local.postBuild()` function for server to check if cli request is received to build image with the `--push` flag.
- When the `--push` flag is set invoke `s.daemon.PushImage()` after the build is successfully completed.
- Added test for `--push` flag for.
- Cli side changes:
  - Now `client.CmdBuild()` function reflects the usage for `--push` flag
  - push=true is set, when the flag is used.
- Updated `man docker-build`
- Updated docs `build.md` to reflect the changes

### CODE REVIEW

**Comment by calavera** [comment]
Pushing/Pulling is going to change a lot with #17924. I'm still not sure if we want this, but this has way less priority than #17924 and we should not implement it before that other PR lands.

**Comment by vdemeester** [comment]
Agree with @calavera and as we are moving the builder outside the daemon, I think the `push` option should even be client-side.

**Comment by LK4D4** [comment]
Anyway I think it's better to have separate commands.

**Comment by askb** [comment]
thanks for notifying me on these upcoming design changes, I was unaware. I am ok, if this needs to wait until major #17924 changes get completed. Giving `docker build` the ability to `push`, `pull` (already implemented) and `tag` images would be pretty useful for admin's to update and distribute builds frequently.

**Comment by calavera** [comment]
@askb I'm sorry, but I'm going to close this PR. It's obvious that we don't want to have this feature yet, and it's also open to a bigger discussion, specially around client side builder.

Thanks a lot for putting this together. Please, feel free to start a conversation in a issue about the problems you're trying to solve having this option. I think it will be good to have it in mind for the future builder.

**Pull request closed without merging**
