### PR TITLE
OpenRC: pass extra environment variables to configure http(s) proxy for daemon

### PR DESCRIPTION
**Pull request by gagara**
**- What I did**
Implemented https://github.com/moby/moby/issues/40201

**- How I did it**
Pass extra environment variables to docker daemon. In particular:
- `HTTP_PROXY`
- `HTTPS_PROXY`
- `NO_PROXY`

Values for env vars can be defined in openrc conf.d file as:
- `DOCKER_HTTP_PROXY`
- `DOCKER_HTTPS_PROXY`
- `DOCKER_NO_PROXY`

**- How to verify it**
Install docker on openrc-enabled system. e.g. on Gentoo:
```
# emerge docker
``` 
After installation proxy servers can be configured in `/etc/conf.d/docker` file 

**- Description for the changelog**

OpenRC: added support of http(s) proxy configuration for docker daemon

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tianon PTAL

**Comment by tianon** [comment]
This seems really odd to me -- I can't find any other examples of OpenRC services with a similar pattern of custom proxy environment variables.  I would think there's a more generic way of handling this sort of thing in OpenRC?

**Comment by gagara** [comment]
From my understanding this is the only option we have. `dockerd` has no special arguments for proxy configuration, thus we can't use more generic `DOCKER_OPTS` here. `daemon.json` also have no such options, so we can't configure it externally. Besides doc for systemd recommends to use env vars for this case, so we are consistent with approach here.
The only way to provide custom env vars for `start-stop-daemon` in openrc is using `--env` args as I know.
We can involve openrc maintainers to clarify this. @williamh wdyt?

**Comment by tianon** [comment]
Isn't the `confd` file sourced as part of the init script?  Can't you just do `export HTTP*_PROXY=...` directly instead?

**Comment by gagara** [comment]
well, it is sourced. Unfortunately there is no much doc on how it is recommended. `/etc/rc.conf` says:
```
# By default we filter the environment for our running scripts. To allow other
# variables through, add them here. Use a * to allow all variables through.
#rc_env_allow="VAR1 VAR2"
```
However if I do `export HTTP_PROXY=....` it works even w/o whitelisting it in `rc_env_allow`. dunno why.
On the other hand I can't find any other service which uses `export` in `conf.d` file. But I have logstash which uses similar approach as proposed here.

**Comment by williamh** [comment]
I prefer passing environment variables to start-stop-daemon like this, but I also have a question about this proposal.
The way it is set up looks like you have to uncomment and configure all three options in the conf.d file. In the init script, wouldn't it be better to check which options are set and add the appropriate ones to START_STOP_DAEMON_ARGS instead of all three of them?

**Comment by gagara** [comment]
I was trying to make it as simple as possible, since e.g. `HTTP_PROXY=""` is valid env declaration it should work even with empty config.
However I agree, it makes sense to have it conditional. It will preserve system wide configuration in case we have empty configuration here. I will update PR

**Review by aliceinwire — APPROVED** [review]

**Comment by thaJeztah** [comment]
Looks like there's no real consensus on this PR, but https://github.com/moby/moby/pull/42835 implemented ways to configure the daemon's proxy settings through either `daemon.json` or using `--http-proxy`, `--https-proxy` and `--no-proxy` command-line options for `dockerd`.

That patch has not yet been released (will be in the release after `20.10`), but with those, it should be possible to set those options through either `daemon.json` or to set them as `DOCKER_OPTS` (which is used by the OpenRC script).

I'm closing this PR for reasons above, but thank you for contributing; also feel free to continue the conversation!

**Pull request closed without merging**
