### PR TITLE
Prevent network connect/disconnect on swarm scoped networks

### PR DESCRIPTION
**Pull request by mavenugo**
Swarm handles service updates quite differently and also it doesnt
support worker driven manager operations (especially that results in resource manipulation). Hence we must prevent containers from connecting to swarm scoped networks

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @tiborvass @thaJeztah @vdemeester

**Comment by thaJeztah** [comment]
is this something that will / can be supported in future?

**Comment by mavenugo** [comment]
@thaJeztah we can support it when we support `docker run` on swarm-scoped networks.

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by thaJeztah** [comment]
> we can support it when we support docker run on swarm-scoped networks.

Thanks! I thought something changed in that respect, so wanted to check

**Comment by thaJeztah** [comment]
LGTM

**Pull request merged**
