### PR TITLE
integration-cli: run goimports

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <tibor@docker.com>

Compile error introduced by #39945

### CODE REVIEW

**Comment by tiborvass** [comment]
FYI @vikramhh you should probably add `goimports -w` to a post-save hook in your editor :)

**Review by tonistiigi — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
did CI pass on the other one, or did we overlook?

**Comment by tiborvass** [comment]
@thaJeztah don't ask me embarrassing questions :P yes it was an oversight.

This time it fails on the following:
```
[2019-09-19T21:56:40.686Z] === FAIL: amd64.integration.service TestInspect (11.99s)
[2019-09-19T21:56:40.686Z]     inspect_test.go:23: Creating a new daemon at: /go/src/github.com/docker/docker/bundles/test-integration/TestInspect
[2019-09-19T21:56:40.686Z]     daemon.go:336: [de36f1b3f7a36] waiting for daemon to start
[2019-09-19T21:56:40.686Z]     daemon.go:336: [de36f1b3f7a36] waiting for daemon to start
[2019-09-19T21:56:40.686Z]     daemon.go:364: [de36f1b3f7a36] daemon started
[2019-09-19T21:56:40.686Z]     inspect_test.go:39: timeout hit after 10s: waiting for tasks to enter run state. task failed with error: task: non-zero exit (1)
[2019-09-19T21:56:40.686Z]     daemon.go:472: [de36f1b3f7a36] Stopping daemon
[2019-09-19T21:56:40.686Z]     daemon.go:307: [de36f1b3f7a36] exiting daemon
[2019-09-19T21:56:40.686Z]     daemon.go:459: [de36f1b3f7a36] Daemon stopped
```

Not sure if you've seen it.

**Comment by thaJeztah** [comment]
LOL, sorry; was reading on my phone 😂

**Comment by tiborvass** [comment]
RS5:
```
[2019-09-19T23:11:07.813Z] --- FAIL: TestJSONFileLoggerWithOpts (0.02s)

[2019-09-19T23:11:07.813Z]     jsonfilelog_test.go:187: open C:\Users\ContainerAdministrator\AppData\Local\Temp\docker-logger-550729221\container.log.1: The process cannot access the file because it is being used by another process.
```

**Comment by tiborvass** [comment]
Merging since this is really needed and RS5 is unrelated.

**Comment by andrewhsu** [comment]
i saw the flaky test failure on Windows: `TestJSONFileLoggerWithOpts` #36801 in the [logs](https://ci.docker.com/public/job/moby/job/PR-39965/2/execution/node/164/log/)

**Pull request merged**
