### PR TITLE
Windows port of Docker Client

### PR DESCRIPTION
**Pull request by ahmetb**
# Docker CLI for Windows

### Introduction

This pull request contains the set of changes to compile and get the Docker client working on Microsoft Windows.

Changes were mostly around `pkg/term` to get the `docker attach` and other TTY-involving parts working on Windows terminals, `pkg/archive` and `utils` which rely on Unix-specfic calls or structures like stat and other things like home directory or path separators.

We haven't gotten the CLI integration tests running on Windows, yet, therefore functionality is mostly verified manually (more about this below). There are known bugs, which we are looking forward to fix very soon.

Since some of the client code uses packages which contains daemon code (and therefore closely coupled to Linux), we had to provide alternative implementations to those using Go build tags. Those functions mostly return errors when they are called because they shouldn't be called on client code paths.

Running `make cross` now produces 386/amd64 versions of `docker.exe`!
### Known issues
- **Integration-CLI tests not executed:** Most of this test suite assumes
  the daemon is running on the same machine as the client (not possible on Windows, yet)
  and uses Unix sockets to verify the results. These need to be skipped, where
  applicable, or these tests should be converted to use the Remote API over HTTP
  instead of using Unix sockets.
- **Path issues:** Due to the difference between Unix and Windows path separators,
  functionality involving Dockerfile and .dockerignore (e.g. `docker build`) are not
  yet working properly.
- **ANSI.SYS dependency for TTY:** ANSI escape sequences used by TTY terminal code
  (e.g. `docker attach`) are not natively working in the Windows Command Line (cmd.exe)
  or PowerShell. The reason is, ANSI.SYS has not been shipping since Windows 7.
  However, other terminal emulators like [ConEmu](https://code.google.com/p/conemu-maximus5/)
  or ANSI.SYS alternatives like [ansicon](https://github.com/adoxa/ansicon)
  solve this problem. We will be searching for solutions that work out-of-the box.

Signed-off-by: Ahmet Alp Balkan ahmetb@microsoft.com 
Signed-off-by: John Gossman johngos@microsoft.com

### CODE REVIEW

**Comment by so0k** [comment]
Do volume mounts work from windows client?

```docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8-dirty
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8-dirty
```
from windows 8.1 64bit, using ansicon and with latest docker build from https://master.dockerproject.com/
```
D:\prj\drfquickstart>ansicon
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\prj\drfquickstart>docker version
Client version: 1.4.1-dev
Client API version: 1.16
Go version (client): go1.4
Git commit (client): 7eb5262
OS/Arch (client): windows/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8-dirty
```

trying to use volume mount with Windows path notation:
```D:\prj\drfquickstart>docker run -it --rm -v D:\prj\drfquickstart:/usr/src/app/ python:3 bash
invalid value "D:\\prj\\drfquickstart:/usr/src/app/" for flag -v: \prj\drfquickstart:/usr/src/app/ is not an absolute path
```
trying to use volume mount with unix path notation:
```D:\prj\drfquickstart>dir /B
db.sqlite3
manage.py
pip-cache
quickstart.sublime-project
quickstart.sublime-workspace
tutorial

D:\prj\drfquickstart>docker run -it --rm -v /D/prj/drfquickstart/:/usr/src/app/ python:3 bas
root@006dc57efb28:/usr/src/python# ls -l /usr/src/app/
total 0
```

if I run a privileged container - share the windows folder & install cifs-utils in my dev box - I can mount the windows folder... so I can work around, but... any plans on volume mounts?

**Comment by SvenDowideit** [comment]
no, volume mounts are only local to the Docker daemon host - and using the windows docker client will not create any links to do this for you.

in the boot2docker management tool, we create a vbox share of `c:\Users` that is mounted into the Docker host, and thus can be used - you'd need to create something similar manually in hyper-v, and then bind mount using unix paths.

using containerised network mounts won't work, as they're not recusivly bind mounted into other containers via the volumes (I tried to make it work, but failed - i'm not sure that you can tbh) 

the most reliable solution I've had, is to mount the windows dir into the host, and then use that bind mount. And I'm probably going to do more work in b2d to try out a few things we can benchmark, and then chose what goes into docker-machine.

**Comment by so0k** [comment]
Ok, thank you for your reply.

in that case, I'm not sure if the docker windows client can give me any advantage over putty for containerized development of Linux applications? Until there is a windows docker deamon for windows application development.

given the different environment, I assume it is also not possible to do "docker in docker" by mounting docker bin & socket from windows client

as for my work around: I currently have docker images with cifs-utils, while still manually mounting the windows shares, I will try to automate it similar to this: http://chapeau.freevariable.com/2014/08/docker-uid.html

I prefer not to install cifs-utils on the host server (which is running the docker deamon)/

**Comment by SvenDowideit** [comment]
note that a windows docker daemon will only be useful for containerising native windows applications.

I personally find the docker native osx and windows clients very useful - as they allow me to run a `docker build` directly from my local host, which pushes all the source code from windows to the container, and then I run the container on the linux box.

Note that my workflow does not bind-mount (the `-v /hostdir:/containerdir`) at all, as that won't work in a performant way for _any_ remote Docker daemon - and some of mine are out in the cloud.

I don't understand why you'd need to install cifs-tools - last time I worked on this, I thought `mount -t cifs ...` worked with no changes on boot2docker (and tbh, thats the most likely type of solution we'll persue in the shorter term - the remove volumes proposal seems not to be proceeding yet.

**Comment by so0k** [comment]
yes, I noted that the windows docker deamon would only be useful for windows application development in my reply :)

I can see that building containers is easier with the native windows docker client, but having a containerized development environment is not.

Re: b2d - When on Windows 8.1, Hyper-V prevents the usage of Virtual Box / VMWare player. I can run boot2docker on Hyper-V.. However I would still have to learn all the pitfalls of Tiny Core Linux and won't be able to use VB Guest additions etc.... I invested time in learning CoreOS (prior to the Rocket announcement) and prefer to use a local CoreOS instance for app development as it matches the server I deploy to (for now).

**Comment by stuaxo** [comment]
Re: ANSI.SYS - Maybe you could have a word with the Windows team and get this supported for Windows 11 if not 10 ?

**Comment by ksmutny** [comment]
Please, is there an archive of official builds of Windows client? The builds on https://master.dockerproject.com are nightly and got out of sync with boot2docker. I have a boot2docker in Hyper-V (on Windows 8.1) with API version 1.17, the official Windows client build has API version 1.18. I want to avoid compiling the client myself. Thanks in advance for any help.

**Comment by ahmetalpbalkan** [comment]
@ksmutny there is no official build of Windows CLI yet. We are planning to release one for Docker 1.6.0.

**Comment by ksmutny** [comment]
@ahmetalpbalkan Ok then, thanks. I compiled it according to your instructions and it works like a charm :)

**Comment by markl17** [comment]
you can always compile your own docker with go compiler

**Comment by BGaudreault** [comment]
Hi, not sure if this is the [Docker repo] you mentioned in ahmetalpbalkan.com/blog/compiling-docker-cli-on-windows, but I'm getting the following error installing on a 32-bit OS (hope that's supported!): 

"..\utils\utils.go:22:2: cannot find package "github.com/docker/docker/autogen/do
ckerversion" in any of:
        C:\Go\src\github.com\docker\docker\autogen\dockerversion (from $GOROOT)
        C:\Go\src\github.com\docker\docker\autogen\dockerversion (from $GOPATH)
        C:\Go\src\github.com\docker\docker\vendor\src\github.com\docker\docker\a
utogen\dockerversion"
cc: @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@BGaudreault this comment should go to the blog post's comment section; not here.

**Comment by petersellars** [comment]
When trying to build as per https://ahmetalpbalkan.com/blog/compiling-docker-cli-on-windows/ I am getting the following error:

    E:\Projects\docker-windows\src\github.com\docker\docker\docker>go build -v
    ..\utils\utils.go:22:2: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
        C:\Go\src\github.com\docker\docker\autogen\dockerversion (from $GOROOT)
        E:\Projects\docker-windows\src\github.com\docker\docker\autogen\dockerversion (from $GOPATH)
        E:\Projects\docker-windows\src\github.com\docker\docker\vendor\src\github.com\docker\docker\autogen\dockerversion

Am new to Go and wondering if this is path related or environment related.

**Comment by tiborvass** [comment]
Hey everyone, if you have docker-related questions, feel free to reach out on the [docker-user mailing list](https://groups.google.com/forum/#!forum/docker-user) instead of commenting on this merged PR, that'd be much appreciated, thanks!

**Pull request merged**
