### PR TITLE
Remove unnecessary var decls

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by jfrazelle** [comment]
these things you are finding and fixing make me sad LGTM

**Comment by HuKeping** [comment]
The var decls outside of the loop will only take 2 address to keep all the data no matter how many loops in "for", re-define them in every loop might not. But we would hope that the Go compiler would do that optimization automatically for us, but you never know.

**Comment by LK4D4** [comment]
@HuKeping If it's so, then we probably need to just rewrite whole docker project :)

**Comment by runcom** [comment]
LGTM

**Pull request merged**
