### PR TITLE
[do not merge] Debugging win2lin issues

### PR DESCRIPTION
**Pull request by tonistiigi**

### CODE REVIEW

**Comment by WeiZhang555** [comment]
Oh, I'm a little bit worried now, hope you don't have to do real revert because I love my PR :crying_cat_face: :taxi:

**Comment by tonistiigi** [comment]
@WeiZhang555 Did win2lin pass in your PR before it went to docs-review?

**Comment by WeiZhang555** [comment]
@toddjcrane Yes, I think so. At least it's not always blocked on this `TestBuildBlankName`.

**Comment by WeiZhang555** [comment]
I see the problem, I'll also do an investigation to find a real fix.

**Comment by WeiZhang555** [comment]
I'm on my mobile. Just checked my PR, the last integ-test is truly stuck in win2lin, but I'm sure it passed before, and the codes didn't change that much.

**Comment by michael-holzheu** [comment]
The CI on s390x hangs in "DockerSuite.TestEventsLimit": See issue #25533.

**Comment by WeiZhang555** [comment]
@tonistiigi I made a PR to fix this, PTAL.

**Pull request closed without merging**
