### PR TITLE
[1.13] Vendor swarmkit 30a4278

### LINKED ISSUE #29730: [1.13.x] same container port published twice prevent service to run
This might be a known issue but I really think it's a weird one to have. If I publish the same container port on 2 ingress port, the service does not return any error and will never be scheduled — and it's really hard to know why without looking at the daemon logs.

```bash
$ docker service create --name never --publish 5000:80 --publish 5001:80 nginx:alpine
tjbepmsn4nvwevu2xuijfg6k9
$ docker service ls
ID            NAME   MODE        REPLICAS  IMAGE
tjbepmsn4nvw  never  replicated  0/1       nginx:alpine
$ docker service ps never
ID            NAME     IMAGE         NODE  DESIRED STATE  CURRENT STATE      ERROR  PORTS
qem9gxvaldy9  never.1  nginx:alpine        Running        New 2 minutes ago 
# Extract from the logs
ERRO[1550] task allocation failure                       error="service tjbepmsn4nvwevu2xuijfg6k9 to which this task qem9gxvaldy9bpbdtzhn6ornr belongs has pending alloc
ations"
ERRO[1550] task allocation failure                       error="service tjbepmsn4nvwevu2xuijfg6k9 to which this task qem9gxvaldy9bpbdtzhn6ornr belongs has pending alloc
ations"
```

Note that this is entirely possible using `docker run` : 

```
$ docker run -d --publish 5000:80 --publish 5001:80 nginx:alpine
# […]
d8381762d8a1
```

/cc @aaronlehmann @thaJeztah @stevvooe @mavenugo @icecrime @cpuguy83

### LINKED ISSUE #31014: Swarm stops scheduling replicas after node constraint is met again
**Description**

I'm using a single-node Swarm cluster. Docker Swarm can detect once a node label constraint of a service is no longer fulfilled and stops the replicas on this node. Being a one node cluster, the service remains without running replicas. However, after the the node is updated so that the label constraint is met again, Swarm does not start new containers.

**Steps to reproduce the issue:**
1. `docker swarm init`
2. `docker node ls`
```
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
ozjnr1swpr0jut5w06glm7g9k *  dev       Ready   Active        Leader
```
3. `docker node update --label-add 'test=activated' ozjnr1swpr0jut5w06glm7g9k`
4. `docker service create --name test --constraint "node.labels.test == activated" --replicas 5 alpine:3.5 sleep 10d`
5. Verify that tasks are in `running` state: `docker service ps test`
```
ID            NAME    IMAGE       NODE  DESIRED STATE  CURRENT STATE          ERROR  PORTS
6tb88aij9cqo  test.1  alpine:3.5  dev   Running        Running 6 seconds ago
mfsmam0qvrxg  test.2  alpine:3.5  dev   Running        Running 6 seconds ago
7cxx5dirw6mg  test.3  alpine:3.5  dev   Running        Running 6 seconds ago
ki9dh2t5x7at  test.4  alpine:3.5  dev   Running        Running 6 seconds ago
yga3j0bb83mn  test.5  alpine:3.5  dev   Running        Running 6 seconds ago
```
6. `docker node update --label-add 'test=deactivated' ozjnr1swpr0jut5w06glm7g9k`
7. Verify that tasks are in `shutdown` state: `docker service ps test`
```
ID            NAME    IMAGE       NODE  DESIRED STATE  CURRENT STATE            ERROR  PORTS
6tb88aij9cqo  test.1  alpine:3.5  dev   Shutdown       Shutdown 17 seconds ago
mfsmam0qvrxg  test.2  alpine:3.5  dev   Shutdown       Shutdown 17 seconds ago
7cxx5dirw6mg  test.3  alpine:3.5  dev   Shutdown       Shutdown 17 seconds ago
ki9dh2t5x7at  test.4  alpine:3.5  dev   Shutdown       Shutdown 17 seconds ago
yga3j0bb83mn  test.5  alpine:3.5  dev   Shutdown       Shutdown 17 seconds ago
```
8. `docker node update --label-add 'test=activated' ozjnr1swpr0jut5w06glm7g9k`
9. Observe state of tasks `docker service ps test`

**Describe the results you received:**

Even after some time, tasks are not started again:

```sh
$ docker service ps test
ID            NAME    IMAGE       NODE  DESIRED STATE  CURRENT STATE                ERROR  PORTS
6tb88aij9cqo  test.1  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
mfsmam0qvrxg  test.2  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
7cxx5dirw6mg  test.3  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
ki9dh2t5x7at  test.4  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
yga3j0bb83mn  test.5  alpine:3.5  dev   Shutdown       Shutdown about a minute ago

$ docker node inspect --pretty ozjnr1swpr0jut5w06glm7g9k
ID:                     ozjnr1swpr0jut5w06glm7g9k
Labels:
 - test = activated
Hostname:               dev
Joined at:              2017-02-14 18:45:50.966253791 +0000 utc
Status:
 State:                 Ready
 Availability:          Active
 Address:               127.0.0.1
Manager Status:
 Address:               192.168.178.40:2377
 Raft Status:           Reachable
 Leader:                Yes
Platform:
 Operating System:      linux
 Architecture:          x86_64
Resources:
 CPUs:                  4
 Memory:                7.788 GiB
Plugins:
  Network:              bridge, host, macvlan, null, overlay
  Volume:               local
Engine Version:         1.13.1
```

**Describe the results you expected:**

Swarm schedules new containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

If the service is updated, even just with `docker service update test`, Swarm is able to schedule new containers:
```sh
$ docker service ps test
ID            NAME        IMAGE       NODE  DESIRED STATE  CURRENT STATE                ERROR  PORTS
xpch0tjjyij3  test.1      alpine:3.5  dev   Running        Running 5 seconds ago
6tb88aij9cqo   \_ test.1  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
q7ncofyq141h  test.2      alpine:3.5  dev   Running        Running 5 seconds ago
mfsmam0qvrxg   \_ test.2  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
ziv8idimpovu  test.3      alpine:3.5  dev   Running        Running 5 seconds ago
7cxx5dirw6mg   \_ test.3  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
5ggsi8xhdjez  test.4      alpine:3.5  dev   Running        Running 5 seconds ago
ki9dh2t5x7at   \_ test.4  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
jhzvbjm3s0ob  test.5      alpine:3.5  dev   Running        Running 5 seconds ago
yga3j0bb83mn   \_ test.5  alpine:3.5  dev   Shutdown       Shutdown about a minute ago
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:57:21 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-37-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.788 GiB
Name: dev
ID: FBY5:U4RZ:VVDD:RYAD:HNXV:DOBX:7N7N:MFPM:IXG3:ICLV:VHLH:Q7NJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker runs directly on a physical machine. It is the only node in the Swarm cluster.

### PR DESCRIPTION
**Pull request by aaronlehmann**
Vendor a new swarmkit for 1.13.2

This brings in two fixes:

- https://github.com/docker/swarmkit/pull/1835 - Fixes #29730
- https://github.com/docker/swarmkit/pull/1958 - Fixes #31014

cc @thaJeztah @yongtang

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Updated the vendoring to include a second fix.

**Comment by yongtang** [comment]
There are two Jenkins failures on Windows.

The first is related to #30890 and should have been fixed in #30893
```
02:04:41 ----------------------------------------------------------------------
02:04:41 FAIL: docker_cli_build_test.go:533: DockerSuite.TestBuildLastModified
02:04:41 
02:04:41 docker_cli_build_test.go:555:
02:04:41     out, _ = dockerCmd(c, "run", name, "ls", "-le", "/file")
02:04:41 docker_utils.go:505:
02:04:41     c.Assert(result, icmd.Matches, icmd.Success)
...
...
```

The second failure seems to be caused by network failure:
```
 FAIL: docker_cli_build_test.go:4585: DockerSuite.TestBuildNotVerboseFailureWithNonExistImage
02:05:09 
02:05:09 docker_cli_build_test.go:4598:
02:05:09     c.Fatal(fmt.Errorf("Test[%s] expected that quiet stderr and verbose stdout are equal; quiet [%v], verbose [%v]", testName, qstderr, vstdout+vstderr))
02:05:09 ... Error: Test[quiet_build_not_exists_image] expected that quiet stderr and verbose stdout are equal; quiet [Sending build context to Docker daemon 2.048 kB

02:05:09 Step 1/1 : FROM busybox11
02:05:09 Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: getaddrinfow: No such host is known.
02:05:09 ], verbose [Sending build context to Docker daemon 2.048 kB

02:05:09 Step 1/1 : FROM busybox11
02:05:09 repository busybox11 not found: does not exist or no pull access
02:05:09 ]
02:05:09 
```

**Comment by thaJeztah** [comment]
the lastmodified error can be ignored; fix for the 1.13.x branch is included in https://github.com/docker/docker/issues/31140

**Comment by vieux** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
