### PR TITLE
Fix tgz for Windows binaries

### PR DESCRIPTION
**Pull request by tianon**
Sorry @jfrazelle; got distracted :innocent:

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by jfrazelle** [comment]
lol you got the bot

**Comment by jfrazelle** [comment]
tested locally, lgtm, go ahead and merge after you sign your commit

**Comment by tianon** [comment]
You should update the script to detect when the submitter is in a `MAINTAINERS` file and instead just post:

**Comment by tianon** [comment]
It'd also be swell if Drone could keep enough output for me to see what the heck failed to verify that it's unrelated...

**Pull request merged**
