### PR TITLE
Patch mkimage-yum.sh to work with Amazon Linux (2014.09)

### PR DESCRIPTION
**Pull request by lkinley**

### CODE REVIEW

**Comment by lkinley** [comment]
Ok, done... do I need to create a new pull request?

**Comment by tiborvass** [comment]
@lkinley no you don't! You just updated the current pull request :)
@jfrazelle do you think we should update the text to say something like "This will update the existing pull request, so no need to open a new one" ?

Ping @tianon :)

**Comment by jfrazelle** [comment]
i will do that ;)

**Comment by jfrazelle** [comment]
hmmm seems sane to me, @tianon?

**Comment by tianon** [comment]
Copying the file from the host is less than ideal, but I don't see a better way, so

LGTM :+1:

**Pull request merged**
