### PR TITLE
[Fix 15520] wrong feature description (rollover) in changelog

### LINKED ISSUE #15520: 1.8.0 release notes document non-existent logging driver "rollover"
Similar to #15518.

In https://github.com/docker/docker/releases/tag/v1.8.0, section "Runtime":

>Add rollover log driver, and --log-driver-opts flag

Also in changelog.

    # docker daemon --log-driver rollover
    INFO[0000] [graphdriver] using prior storage driver "aufs"
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
    FATA[0000] Error starting daemon: error finding the logging driver: logger: no log driver named 'rollover' is registered

"rollover" is not a new logging driver. It is a new configurable behaviour of the json-file logging driver, introduced in #11485, see https://github.com/docker/docker/pull/11485/files#diff-bf81424845bcab2902c9809e30dfe6e0R35

### PR DESCRIPTION
**Pull request by albers**
Fixes #15520.
If this is accepted, someone should update the release notes accordingly

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

Thanks!

**Comment by thaJeztah** [comment]
LGTM thanks!

**Comment by thaJeztah** [comment]
ping @calavera for editing the release notes?

**Comment by vanthome** [comment]
Is there an example anywhere of how to actually use these options? as far as I can see there is a param `maxSize` for the json file driver but I cannot find any docs how to use it.

**Comment by albers** [comment]
@vanthome See https://docs.docker.com/reference/logging/overview/#the-json-file-options

**Pull request merged**
