### PR TITLE
Cleanup libseccomp.a hack since dockerinit is gone

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by cyphar** [comment]
Wow, does that work? I tried to do the same when I removed dockerinit, but Jenkins wasn't happy about it.

**Comment by thaJeztah** [comment]
ping @tianon @jfrazelle ptal

**Comment by jfrazelle** [comment]
testing this now thanks

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
Don't we need to do this in more places too?  Or is it OK for us to just start with the RPM code?

**Comment by jfrazelle** [comment]
I think that is the only place we still do this other than the main
Dockerfile, where we need it because the libseccomp in trusty is too old a
version

On Tue, Feb 2, 2016 at 9:42 AM, Tianon Gravi <notifications@github.com>
wrote:

> Don't we need to do this in more places too? Or is it OK for us to just
> start with the RPM code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/19851#issuecomment-178707654>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by tianon** [comment]
Ah nice, OK!  LGTM :+1:

**Comment by cyphar** [comment]
@jfrazelle we still do it in all the main Dockerfiles, but it's not statically compiling it AFAICS.

**Comment by jfrazelle** [comment]
yeah i know because trusty version is too low

On Tue, Feb 2, 2016 at 2:04 PM, Aleksa Sarai <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> we still do it in all the main
> Dockerfiles, but it's not statically compiling it AFAICS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/19851#issuecomment-178849291>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Pull request merged**
