### PR TITLE
daemon/state: separate part of SetRestarting to setRestarting

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by calavera** [comment]
why? `setRestarting` is not used anywhere else.

**Comment by Mashimiao** [comment]
I think it's similar to functions SetRunning(), SetStopped(). They both have setXXX().
And seems more clear and logical to read.

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
Do any of them need to be exported? It doesn't look like it (and logically I'd think only daemon would set these).

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
we can make the others private in follow up ;)

**Pull request merged**
