### PR TITLE
Update docker_remote_api_v1.21.md to complete the docs

### PR DESCRIPTION
**Pull request by tracylihui**
Update docker_remote_api_v1.21.md to complete the docs. Tht old docs is short of name about containers apis.
#20536

Signed-off-by: tracylihui 793912329@qq.com

### CODE REVIEW

**Comment by tracylihui** [comment]
@thaJeztah

**Comment by thaJeztah** [comment]
LGTM, perhaps we can combine all the API changes in a single PR? I see https://github.com/docker/docker/pull/20542 as well, would be nice to have them all in a single PR, I think @longliqiang88

**Comment by tracylihui** [comment]
yes,I will test other Api Versions. And combine in a single PR

**Comment by tracylihui** [comment]
I found that the PR of @longliqiang88 has been merged. So I don't need to change   docker_remote_api_v1.20.md. So I make a new commit to change from docker_remote_api_v1.14.md to docker_remote_api_v1.19.md. So the old version and v1.21 has been changed too. If there's no problem, I hope it can be merged.Thanks. @thaJeztah @vdemeester

**Comment by vdemeester** [comment]
LGTM 🐺

**Pull request merged**
