### PR TITLE
Re-vendor latest swarmkit fixes.

### PR DESCRIPTION
**Pull request by cyli**
These are the latest swarmkit changes, including many of the fixes merged into docker-ce.

cute

cc @thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks!! looks like CI is failing 😢

**Comment by aaronlehmann** [comment]
Oops, I opened a similar PR at #33642. Mine is slightly more up-to-date.

**Comment by thaJeztah** [comment]
This one definitely has a cuter image though 😃

**Comment by thaJeztah** [comment]
Chatted with @cyli on Slack; closing this one (thanks! 🤗)

**Pull request closed without merging**
