### PR TITLE
vendor: remove vendored golang.org/x/tools, as it's not needed

### PR DESCRIPTION
**Pull request by thaJeztah**
This dependency was added in 6cdbf07be9d0ad08776df0b65fb1b3e4e617c42a https://github.com/moby/moby/pull/39838,  but looks like the code was vendored manually, or vendored, then removed from vendor.conf.

This commit removes the vendored files, as they are not needed to build our binaries.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tiborvass PTAL; I recall we had a discussion at the time about the large number of dependency lines added, but you managed to reduce the amount; not sure how the x/tools packages could've gone into vendor, and CI not failing on that though; https://github.com/moby/moby/pull/39838#issuecomment-702445921

**Comment by tiborvass** [comment]
@thaJeztah What's weird is that we still have a `vendor/golang.org/x/tools` folder, when there is no such dependency. Instead of adding it back, I suggest we remove the folder altogether.

**Comment by thaJeztah** [comment]
hmm.. good one; trying that (pushed an update)

**Review by tiborvass — APPROVED** [review]

**Comment by thaJeztah** [comment]
@cpuguy83 @AkihiroSuda ptal

**Review by chris-crone — APPROVED** [review]
SGTM but I don't have experience here.

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
