### PR TITLE
Fixes #13211 linkLocalIPv6FromMac

### LINKED ISSUE #13211: autogenerated LinkLocalIPv6Address can create two containers with the same ipv6 address
## Description of problem:
When I create containers without specifying any ip or mac address, ipv4, mac address and ipv6 are autogenerated (at least since version 1.5 for ipv6).

It looks like ip v4 and mac address can't conflicts, but you can generate two containers with the same ip v6:

## `docker version`:
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64

## `docker info`:
Containers: 11
Images: 185
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 207
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 15.59 GiB
Name: *the server's name*
ID: KU57:P757:EDQZ:P4Q2:6SF2:MLXX:WY2K:TW62:CX7C:EVHS:DORS:K6ZH
WARNING: No swap limit support

## `uname -a`:

Linux *the server's name* 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

## Environment details (AWS, VirtualBox, physical, etc.):

physical server

## How reproducible:

Always

## Steps to Reproduce:
* start docker daemon (because it will restart the auto assignation of ips to 172.17.0.1)
* create 17 containers
* create a container "test1"
* create 238 other useless containers
* create a container "test2"

## Expected results based on how ipv6 affectation seems to work in spirit:

| name | IPv4 | mac | IPv6 |
| ------- | ------ | ------ | ------ |
| test1 | 172.17.0.18 | 02:42:ac:11:00:12 | fe80::42:acff:fe11:12 |
| test2 | 172.17.1.2 | 02:42:ac:11:01:02 | **fe80::42:acff:fe11:102** |

## Actual results:

| name | IPv4 | mac | IPv6 |
| ------- | ------ | ------ | ------ |
| test1 | 172.17.0.18 | 02:42:ac:11:00:12 | fe80::42:acff:fe11:12 |
| test2 | 172.17.1.2 | 02:42:ac:11:01:02 | **fe80::42:acff:fe11:12** |

## Additional info:

It seems to me that the problem lies in #8947 in the file `daemon/networkdriver/bridge/driver.go` with the line:

```go
return fmt.Sprintf("fe80::%x%x:%xff:fe%x:%x%x/64", hw[0], hw[1], hw[2], hw[3], hw[4], hw[5]), nil
```

which should look like (in spirit, I don't do go):
```go
return fmt.Sprintf("fe80::%x:%x:%x:%x/64", hw[0]*0x100+hw[1], hw[2]*0x100+0xff, 0xfe*0x100+hw[3], hw[4]*0x100+hw[5]), nil
```

As I never wrote a line of go, I won't create a PR: I prefer to have someone who know what he's doing to do it.

### PR DESCRIPTION
**Pull request by MalteJ**
Kudos to @gissehel for his great work on investigation and the fabulous bug report!

fixes #13211

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks @MalteJ!

ping @mrjana to check if Libnetwork doesn't have the same bug.

**Comment by mrjana** [comment]
In libnetwork we are deprecating this as inspect value. The eth0 interface inside the container will have this linklocal ipv6 address assigned to the interface itself. So if you do `ip -6 addr show dev eth0` you should see the link local ipv6 address.

**Comment by jfrazelle** [comment]
so I think this needs to be opened on libnetwork now? then pulled in here am i correct

**Comment by thaJeztah** [comment]
@jfrazelle according to @mrjana's https://github.com/docker/docker/pull/13226#issuecomment-102257975 this shouldn't be a problem in Libnetwork. But I'm interested to hear if there's a regression test in place

**Comment by jfrazelle** [comment]
cool @MalteJ can you rebase please :)

**Comment by MalteJ** [comment]
@jfrazelle well, it looks like the files I have edited disappeared from master branch :smile:

**Comment by thaJeztah** [comment]
@MalteJ is the test case still useful for libnetwork?

**Comment by mavenugo** [comment]
@mrjana can you suggest the course of action for this PR ?

**Comment by mrjana** [comment]
@MalteJ @thaJeztah @jfrazelle @mavenugo This test is moot because in the libnetwork bridge driver we don't generate the linklocal address from MAC at all. We leave it to the kernel to do it for us because of the way we plumb the interfaces. So this(the generation part) doesn't need to be tested. What may be tested is add an integration-cli to ensure that this is the case when container is brought up and the the container eth0 address has the linklocalFromMac setup correctly. 

But, we should probably remove the `linklocalFromMAC` field from `NetworkSettings` because it's not populated any more.

**Comment by icecrime** [comment]
Sorry @MalteJ, another one that we seem to have dropped with the big move to libnetwork =/ I'm closing this as my understanding from the above comments is that it's not relevant anymore.

**Comment by MalteJ** [comment]
no problem. I am happy we have the new network stack!

**Comment by icecrime** [comment]
<3

**Pull request closed without merging**
