### PR TITLE
ineffectual assignment to isCanonical, delete it, and make the "if" sentence to fit the golang usage

### PR DESCRIPTION
**Pull request by yu8833**
Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

**- What I did**
Ineffectual assignment to isCanonical, delete it, and make the "if" sentence to fit the golang usage. 
**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by dnephin — APPROVED** [review]
LGTM

We should start using stricter lint against this repo to catch these!

**Comment by thaJeztah** [comment]
Windows failure looks unrelated;

```
10:31:58 ----------------------------------------------------------------------
10:31:58 FAIL: docker_cli_events_test.go:84: DockerSuite.TestEventsLimit
10:31:58 
10:31:58 docker_cli_events_test.go:116:
10:31:58     c.Assert(err, checker.IsNil, check.Commentf("%q failed with error", strings.Join(args, " ")))
10:31:58 ... value *errors.errorString = &errors.errorString{s:"exit status 125: d:\\CI\\CI-6fbb16259\\binary\\docker.exe: Error response from daemon: failed to create endpoint nervous_goldwasser on network nat: failed to save endpoint 1a9249d to store: failed to update store for object type *windows.hnsEndpoint: open D:\\CI\\CI-6fbb16259\\daemon/network/files/local-kv.db.lock: The process cannot access the file because it is being used by another process.\n"} ("exit status 125: d:\\CI\\CI-6fbb16259\\binary\\docker.exe: Error response from daemon: failed to create endpoint nervous_goldwasser on network nat: failed to save endpoint 1a9249d to store: failed to update store for object type *windows.hnsEndpoint: open D:\\CI\\CI-6fbb16259\\daemon/network/files/local-kv.db.lock: The process cannot access the file because it is being used by another process.\n")
10:31:58 ... "run --rm busybox true" failed with error
10:31:58 
```

**Comment by thaJeztah** [comment]
That test was flaky a number of times https://github.com/moby/moby/issues/28873 https://github.com/moby/moby/issues/22601 https://github.com/moby/moby/issues/25533

**Pull request merged**
