### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by dave-tucker**
**- What I did**

This commit uses the existing jenkins freestyle job configuration to
create a jenkinsfile. This allows the project to use multi-branch
pipelines in jenkins and to allow others to contribute to the CI setup.

**- How I did it**

Copy/Paste 😉 

**- How to verify it**

A test job: https://jenkins.dockerproject.org/job/dave-tucker/job/jenkinsfile-test/

**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by thaJeztah** [comment]
:tada:

@cpuguy83 @olljanat @vdemeester

**Comment by olljanat** [comment]
Nice. Now "just" need study how to install and configure Jenkins...

**Review by vdemeester — APPROVED** [review]
LGTM :heart_eyes: 
@dave-tucker I :heart: u ! :hugs:

**Review by AkihiroSuda — APPROVED** [review]

**Comment by dave-tucker** [comment]
A couple of things to bear in mind 🐻 

1) To ensure this doesn't get merged and bit-rot we should have a clear plan to enable a Jenkins Multi-branch pipeline for `moby/moby`. This will involve stopping `leeroy` sending webhooks to the old Jenkins freestyle jobs

1) To do a rebuild of a PR for a certain job for a given PR, one will have to use the Jenkins UI. The Multibranch pipeline plugin will create a "branch" each PR. You just need to hit "build", deselect the builds that you don't want and then you are done. In theory this could be automated so the slack/irc style rebuild commands still work.

1) I've used the checked in powershell script for Windows RS1 CI vs. the one that is in-lined in the Jenkins job as it makes the Jenkinsfile over 1000 lines 😨 This is the same script used for RS5. @jhowardmsft do you think that this would be ok?

1) There are some inconsistencies between how the `bundles.tar.gz` is created and how container cleanup happens. It would be nice to fix this but it could be done in a follow up.

1) I haven't seen a green build just yet. @thaJeztah I might need your help figuring out what is just flaky vs. what's a genuine failure.

**Comment by olljanat** [comment]
@dave-tucker first of all. Thanks for sharing this config with us. Just to have it visible simplifies many things as we don't need to guess. 

> 1. To ensure this doesn't get merged and bit-rot we should have a clear plan to enable a Jenkins Multi-branch pipeline for `moby/moby`. This will involve stopping `leeroy` sending webhooks to the old Jenkins freestyle jobs
> 2. To do a rebuild of a PR for a certain job, one will have to use the Jenkins UI. The Multibranch pipeline plugin will create a "branch" each PR. You just need to hit "build", deselect the builds that you don't want and then you are done. In theory this could be automated so the slack/irc style rebuild commands still work.

I don't know how others want to use this config but I would prefer to move logic to Jenkinsfile to generic bash scripts. First example of that kind of approach is on https://github.com/olljanat/moby/commit/936fc81774a8683f5d2f1a79858c40ab580f22e5

On that way:
- contributors are able to test/debug most common CI related things locally without need to setup Jenkins.
- we can allow contributors to enable CircleCI to forked repos by including super simple config like this to Moby https://github.com/olljanat/moby/commit/a1dcada61c5794dc0b65807895f7c5986cd1df43 (you can see log from test run on [here](https://circleci.com/gh/olljanat/moby/159) )
- IMO, we don't necessarily need migrate Jenkins to use Jenkinsfile but instead of just export it to here on documentation purposes as it should need updates very rarely.

> 3. I've used the checked in powershell script for Windows RS1 CI vs. the one that is in-lined in the Jenkins job as it makes the Jenkinsfile over 1000 lines fearful This is the same script used for RS5. @jhowardmsft do you think that this would be ok?

I have understood that that logic have been in Jenkins on past and it was moved to PowerShell to simplify local debugging (seen comment on some old PR).

> 4. There are some inconsistencies between how the `bundles.tar.gz` is created and how container cleanup happens. It would be nice to fix this but it could be done in a follow up.

Fixed already on example commit above :wink:

> 5. I haven't seen a green build just yet. @thaJeztah I might need your help figuring out what is just flaky vs. what's a genuine failure.

At least most common flaky issues are listed on #37306

**Comment by dave-tucker** [comment]
Updated to add a 3 hr timeout to avoid builds staying in a pending state forever.

**Comment by dave-tucker** [comment]
@olljanat I like the bash scripts ❤️

**Comment by dave-tucker** [comment]
I pushed some changes to add a `customWorkspace` for the Windows builds as I missed this when extracting info from the current Jenkins builds.

Now I think this is good to go 🎉 

See: https://jenkins.dockerproject.org/job/dave-tucker/job/jenkinsfile-test/

I've seen it pass at least once on each set of tests.

**Comment by cpuguy83** [comment]
> java.lang.NoSuchMethodError: No such DSL method 'addFailedStep'

**Comment by dave-tucker** [comment]
Good catch @cpuguy83 - I've just updated this PR to fix that!

**Comment by cpuguy83** [comment]
> Exception from GitHubCommitStatusSetter for windowsRS5-process: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method hudson.plugins.git.GitSCM getRepositories

**Comment by cpuguy83** [comment]
Oh, somehow I grabbed logs from an old run...

**Comment by cpuguy83** [comment]
Oh well, powerpc has the same error on the last run.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Let's merge this; the file won't be used for now, as follow-up changes are needed to change the CI config and so on 😇

**Comment by dave-tucker** [comment]
@cpuguy83 @thaJeztah thanks!

> Exception from GitHubCommitStatusSetter for windowsRS5-process: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method hudson.plugins.git.GitSCM getRepositories

This is a quick fix - I just need to add that method to the whitelist in Jenkins...
But if I did that now, then it would start setting commit status for real, which we don't want until we actually do the migration to Jenkins Multibranch Pipelines 😉

**Pull request merged**
