### PR TITLE
remove swarm, machine and compose from the 1.5.0 release docs

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit SvenDowideit@home.org.au

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@fredlf @jamtur01 @icecrime

**Comment by fredlf** [comment]
LGTM. Thanks Sven. Sorry for churn.

**Comment by SvenDowideit** [comment]
this might not be needed, so I'm going to close it for now

**Comment by SvenDowideit** [comment]
turns out that yup, we want to remove these from 1.5.0 - they'll go out in an update

**Comment by fredlf** [comment]
Yes, that's correct. We should not add these with 1.5. Churn, churn, churn.

**Comment by SvenDowideit** [comment]
@icecrime what that means, is this PR needs to be merged into 1.5.0 - I'll rebase in a mo

**Comment by SvenDowideit** [comment]
@jamtur01

**Pull request merged**
