### PR TITLE
Add zsh completion for 'docker service' commands

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #23363
@vincentbernat

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
@sdurrheimer could you pls rebase

**Comment by sdurrheimer** [comment]
@runcom Rebased

**Pull request merged**
