### PR TITLE
Update libcontainer to a37b2a4f152e2a1c9de596f54c0

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@crosbymichael let's create tag v2.0.1 in libcontainer :)

**Comment by jfrazelle** [comment]
sys test needs to be updated other than that LGTM

**Comment by tianon** [comment]
hack change LGTM :+1:

**Comment by crosbymichael** [comment]
that test failure is not my fault

**Comment by crosbymichael** [comment]
it passed!

**Comment by LK4D4** [comment]
I'll create tag anyway :E Because I'm TAGGER.
LGTM

**Comment by thaJeztah** [comment]
image

**Pull request merged**
