### PR TITLE
Improved readability of README.md

### PR DESCRIPTION
**Pull request by jasdeepgill**
**- What I did**
Changes on line 8 and 9. Three 'ands' were used in the sentence, split sentence into two to improve readability.

Line 32:
Again multiple 'ands' were used, so sentence was split into two. Better to use another sentence then to keep adding on by using 'and'. 

Line 35:

Split sentence into two as again multiple 'ands' were used to add onto the sentence. Both sentences have their own topic. The first talks about who supports Moby and the second is about how Moby is not for commercial support. 

**- How I did it**
Using githubs website and editing the document.
**- How to verify it**

**- Description for the changelog**

Improved readability of README.md

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
thanks for contributing; looks like your commit misses a DCO sign-off (https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work), which causes CI to fail

Could you amend your commit with a DCO sign-off? (Unfortunately it's not possible to do this from the GitHub web ui, so you will have to do this from the command-line); let me know if you need help doing to

**Comment by jasdeepgill** [comment]
Do I have to make a new commit? And how do I commit the file from cmd line. Do I have to clone the whole repo?

**Comment by thaJeztah** [comment]
> Do I have to make a new commit? And how do I commit the file from cmd line. Do I have to clone the whole repo?

Yes, unfortunately it's not possible to fix commit messages through the GitHub web UI, so you need to clone your fork of the repo, and amend your commit;

Make your name and e-mail is configured correctly in git (see https://help.github.com/en/github/using-git/setting-your-username-in-git and https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git);

```bash
git config --global user.name "Your Real Name"
git config --global user.email "you@example.com"
```

check out your fork of the repository, and switch to the branch used for this PR

```bash
git clone https://github.com/jasdeepgill/moby.git
cd moby/
git checkout patch-1
```

Sign-off and amend the commit:

```bash
git commit -s --amend --no-edit
```

Force-push your changes:

```bash
git push -f origin
```

**Comment by AkihiroSuda** [comment]
ping

**Comment by AkihiroSuda** [comment]
Closing because of inactivity

**Pull request closed without merging**
