### PR TITLE
Carry 23694: Default port for listen addr 

### PR DESCRIPTION
**Pull request by tiborvass**
Closes #23694 
# 

Allow `--listen-addr a.x.y.z` to use a default port

Adds some unit tests for swarm options

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
except:
```
1:25:23 # github.com/docker/docker/api/client/swarm
01:25:23 api/client/swarm/opts.go:58: no new variables on left side of :=
01:25:23 api/client/swarm/opts.go:58: cannot assign uint64 to port (type string) in multiple assignment
01:25:23 api/client/swarm/opts.go:60: undefined: parts
01:25:23 api/client/swarm/opts.go:62: cannot convert port (type string) to type uint16
01:25:23 api/client/swarm/opts.go:77: cannot use a.port (type uint16) as type string in argument to net.JoinHostPort
```

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
Got a test failing:

```
01:39:05 --- FAIL: TestNodeAddrOptionSetInvalidFormat (0.00s)
01:39:05 	assert.go:37: Expected error to contain 'Invalid url', got 'too many colons in address http://localhost:4545'
```

**Comment by tiborvass** [comment]
Fixed it

**Comment by tonistiigi** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Pull request merged**
