### PR TITLE
Bump vndr to 9909bb2b8a0b7ea464527b376dc50389c90df587

### PR DESCRIPTION
**Pull request by thaJeztah**
This bumps vndr to 9909bb2b8a0b7ea464527b376dc50389c90df587 (current master)
and revendors dependencies.

Includes a change that prunes go files with `+build ignore` (https://github.com/LK4D4/vndr/pull/50)

Complete diff; https://github.com/LK4D4/vndr/compare/c56e082291115e369f77601f9c071dd0b87c7120...9909bb2b8a0b7ea464527b376dc50389c90df587

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
ugh, looks like this one is flaky;

```
22:36:13 ----------------------------------------------------------------------
22:36:13 FAIL: docker_cli_swarm_test.go:1146: DockerSwarmSuite.TestSwarmLockUnlockCluster
22:36:13 
22:36:13 [d6dd4af73d088] waiting for daemon to start
22:36:13 [d6dd4af73d088] daemon started
22:36:13 
22:36:13 [d072353b4c428] waiting for daemon to start
22:36:13 [d072353b4c428] daemon started
22:36:13 
22:36:13 [d36d02feae8c0] waiting for daemon to start
22:36:13 [d36d02feae8c0] daemon started
22:36:13 
22:36:13 [d072353b4c428] exiting daemon
22:36:13 [d072353b4c428] waiting for daemon to start
22:36:13 [d072353b4c428] daemon started
22:36:13 
22:36:13 [d072353b4c428] exiting daemon
22:36:13 [d6dd4af73d088] exiting daemon
22:36:13 [d6dd4af73d088] waiting for daemon to start
22:36:13 [d6dd4af73d088] daemon started
22:36:13 
22:36:13 [d36d02feae8c0] exiting daemon
22:36:13 [d36d02feae8c0] waiting for daemon to start
22:36:13 [d36d02feae8c0] daemon started
22:36:13 
22:36:13 [d072353b4c428] waiting for daemon to start
22:36:13 [d072353b4c428] daemon started
22:36:13 
22:36:13 docker_cli_swarm_test.go:1192:
22:36:13     // d2 is now set to lock
22:36:13     checkSwarmUnlockedToLocked(c, d2)
22:36:13 docker_utils_test.go:471:
22:36:13     c.Assert(v, checker, args...)
22:36:13 ... obtained bool = false
22:36:13 ... expected bool = true
22:36:13 
22:36:13 [d6dd4af73d088] exiting daemon
22:36:13 [d072353b4c428] exiting daemon
22:36:13 [d36d02feae8c0] exiting daemon
22:36:27 
22:36:27 ----------------------------------------------------------------------
```

**Comment by vieux** [comment]
very nice, LGTM

**Pull request merged**
