### PR TITLE
Fix install script for redhatenterpriseserver

### LINKED ISSUE #24039: Install script broken for RHEL 7.2
```
# ./install-docker.sh 
in do_install()
debug do_install3 lsb_dist=redhatenterpriseserver

  Either your platform is not easily detectable, is not supported by this
  installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
  a package for Docker.  Please visit the following URL for more detailed
  installation instructions:

    https://docs.docker.com/engine/installation/
```

The box is a Virtual Machine. 

```
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

**Steps to reproduce the issue:**
1. RHEL 7.2 box
2. curl -fsSL https://test.docker.com/ | sh

**Describe the results you received:**
The install script doesn't handle the RHEL 7.2 distribution correctly. The case statement in do_install() looks for redhat, but in my case lsb_dist=RedHatEnterpriseServer.

**Describe the results you expected:**
The test version of Docker to be installed on my RHEL 7.2 box (1.12.x).

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/docker/docker/issues/24039

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon @kencochrane @adamjk-dev PTAL, thanks!

**Comment by kencochrane** [comment]
LGTM

**Comment by tianon** [comment]
"special" :see_no_evil:

LGTM

**Comment by adamjk-dev** [comment]
We need to pull in my latest changes to truly fix this issue: https://github.com/adamjk-dev/docker/commit/290afda51c3fd238e234f0386bf83d8777b4c6db

**Comment by thaJeztah** [comment]
@kencochrane @tianon actually, I just suggested @adamjk-dev to open  pull request, then we can close this one

**Comment by kencochrane** [comment]
ok

**Comment by adamjk-dev** [comment]
https://github.com/docker/docker/pull/24069

**Pull request closed without merging**
