### PR TITLE
indicate HostConfig to be used for "create container" (add again)

### PR DESCRIPTION
**Pull request by gesellix**
As proposed in #13466 ([comment](https://github.com/docker/docker/issues/13466#issuecomment-121379461)) this re-adds a [commit from master](https://github.com/gesellix/docker/commit/16e649c589ce60ba56812a8fffb98aee34fceb94) originally applied with PR #13615 to be applied on the `docs` branch.

Is this the way to go for docs changes?
/cc @moxiegirl

Signed-off-by: Tobias Gesellchen tobias@gesellix.de

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM

**Comment by moxiegirl** [comment]
@gesellix yes. you are at the right place. LGTM @thaJeztah for the merge.

**Comment by thaJeztah** [comment]
LGTM, thanks @gesellix !

**Comment by gesellix** [comment]
thanks you all, too! I hope this will now stay in the right branch ;-)

**Pull request merged**
