### PR TITLE
Updating wrong control code

### PR DESCRIPTION
**Pull request by moxiegirl**
Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Typing `exit` also works. However, there's this PR: https://github.com/docker/docker/pull/18546 that is working on this, and a different proposal. Let me know if you're in a hurry getting this in, or if we work on the other PR

**Comment by moxiegirl** [comment]
@thaJeztah No hurry.  It can wait.

**Comment by MHBauer** [comment]
I feel like there is still a couple different PRs floating about with conflicting changes. I'll circle back around again later.

**Comment by icecrime** [comment]
@thaJeztah @MHBauer Close? Carry? :-(

**Comment by thaJeztah** [comment]
I'll close this one, if needed, we can carry the other PR

**Pull request closed without merging**
