### PR TITLE
dockerfile: update docker-py

### PR DESCRIPTION
**Pull request by tonistiigi**
Should fix docker-py tests currently broken in master.

I haven't tracked down what PR broke it yet. Would be good to check but needs manual bisecting as master ci was down.

@shin- @dnephin @tiborvass  

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Thanks @tonistiigi!

**Review by lowenna — COMMENTED** [review]
LGTM (assuming docker-py tests are green)

**Review by dnephin — APPROVED** [review]
LGTM on green

**Comment by dnephin** [comment]
On an unrelated note, we should definitely be running the `docker-py` suite in parallel instead of at the end of janky

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by shin-** [comment]
You need to update Dockerignore for other archs too

**Comment by jhowardmsft** [comment]
@shin- Yeah, good catch.

**Comment by thaJeztah** [comment]
diff is http://github.com/docker/docker-py/compare/dc2b24dcdd4ed7c8f6874ee5dd95716761ab6c93...a962578e515185cf06506050b2200c0b81aa84ef

**Pull request merged**
