### PR TITLE
Don't store runtime in container's config if not specified

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure mickael.laventure@gmail.com
## 

This should prevent #24343 from ever occurring again.

ping @cpuguy83

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by icecrime** [comment]
My first feeling is: not LGTM.

I like the current behavior where the runtime is "pinned" at container creation time, in such way that if the daemon is restarted with a different set of runtimes and/or a different default, my container will either restart *predictably* or fail because its runtime is nowhere to be found anymore.

**Comment by thaJeztah** [comment]
we had a similar discussion on logging drivers; we now store the logging driver in the container config upon creation; so if a container is started without explicitly specifying a logging driver, that driver is "pinned" in the container config.

from that perspective it may be consistent

**Comment by jfrazelle** [comment]
I agree with @icecrime @thaJeztah

**Comment by icecrime** [comment]
@cpuguy83 @mlaventure Are you ok closing this one?

**Comment by cpuguy83** [comment]
It's fine.

**Comment by thaJeztah** [comment]
I'll go ahead and close, but happy to hear from @mlaventure

**Comment by mlaventure** [comment]
All good for me, consistency with logging behavior is probably best. thanks @thaJeztah

**Pull request closed without merging**
