### PR TITLE
error strings should not be capitalized or end with punctuation

### PR DESCRIPTION
**Pull request by yu8833**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Comment by allencloud** [comment]
Good job to fix this. While, I am wondering if we could use `grep` to find all the cases and fix them as much as possible.  Then we can finish this more and save more resources like CI machines @YuPengZTE

Just my thought. WDYT @AkihiroSuda @thaJeztah

**Comment by AkihiroSuda** [comment]
golint should be able to find such mistakes: https://github.com/golang/lint/blob/master/lint.go#L1167-L1168

Please run golint to find other mistakes as well?

**Comment by YuPengZTE** [comment]
@allencloud @AkihiroSuda 
golint can do this, and the result.txt is the check result, but some is not good to fix, such as "docker\registry\session.go:436:27":
"Network timed out while trying to connect to %s. You may want to check your internet connection or if you are behind a proxy."
There must be a mark in the middle of the two sentences.
Unless synthesize a sentence.
[result.txt](https://github.com/docker/docker/files/605740/result.txt)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
