### PR TITLE
Document VERSION file update scheme

### PR DESCRIPTION
**Pull request by icecrime**
Ping @jfrazelle @tianon!

### CODE REVIEW

**Comment by jfrazelle** [comment]
Woooo just in time LGTM :)

**Comment by thaJeztah** [comment]
Thanks!! This has been sooooooo confusing.

One note/question; this means that a `x.y.1` bugfix release will always be cherry-picked (separate branch?) and there won't be a `x.y.1-dev` "version" in master? 

Alternatively, `Z` could be increment end after a release, (e.g. `1.6.1-dev`) and if it becomes clear that there will not be a `x.y.1` release, the version will be incremented without releasing the `x.y.1` release.

**Comment by tianon** [comment]
LGTM

**Comment by icecrime** [comment]
@thaJeztah Yes I think so: as far as I can tell, we never build patch releases from master, but always from the previous tag.

**Pull request merged**
