### PR TITLE
vendor swarmkit 970b45afa1c9da9ed4b9c793669cedbb05ad3833

### PR DESCRIPTION
**Pull request by dongluochen**
To unblock #28938. 

Ping @aaronlehmann @aluzzardi. 

Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
@dongluochen: I expect integration tests will fail until #31714 is merged. This is blocking swarmkit vendoring because the current integration tests expect deleting the ingress network to fail, but in the latest swarmkit it is allowed.

**Comment by aaronlehmann** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
windows failure is a flaky test https://github.com/docker/docker/issues/32219

**Pull request merged**
