### PR TITLE
add missing filter type in swagger.yml and sort filter type in alphabets

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

I found that there are some missing types about filter in daemon API in swagger.yml. Here is the missing type list:

1. in `GET /containers/json`, filter type `expose` and `publish`;
2. in `GET /events`, filter type `plugin`;
3. in `GET /volumes`, filter type `label`;

Secondly, I sort the all filter type in swagger.yml sorted by alphabet sequence.

Thirdly, I add filter type `volume`, `network` and `isolation` in command `ps` and sorted this filter types. Also update events command line reference to sort filter types.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @dnephin @vdemeester

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
/cc @thaJeztah

**Comment by thaJeztah** [comment]
Do you know which of these are in 1.13, and which for the upcoming 1.14 release? (would be great to have them in separate commits/PR's if needed, so that we can cherry-pick)

**Comment by allencloud** [comment]
`plugin` filter in `GET /events` is in docker 1.13.0: https://github.com/docker/docker/blob/v1.13.0/daemon/events/filter.go#L65-L67

`label` filter in `GET /volumes` is in docker 1.13.0:https://github.com/docker/docker/blob/v1.13.0/daemon/list.go#L24

`expose` and `publish` filters in `GET /containers/json` are in **docker/master, not in docker 1.13.0**:
https://github.com/docker/docker/blob/master/daemon/list.go#L41-L42

So I need to separate the PR. thanks a lot @thaJeztah

**Review by mlaventure — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
