### PR TITLE
cleanup: remove unneeded locks

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by runcom** [comment]
seems legit

**Comment by duglin** [comment]
This is related to #12812 as it added a new func due to the locking stuff.

**Comment by duglin** [comment]
@LK4D4 do you know the history of these locks? I think it makes sense to have a lock in cases where we need to ensure that we're going to get a consistent view of the data because we're accessing multiple properties and we don't want to run the risk of someone else changing 1/2 the data on us while we're examining the properties.

However, in this case locking the container just to retrieve one property doesn't seem to provide a lot of value. What's interesting about this case/func is that since its returning a pointer to a struct/HostConfig the lock doesn't really help anything because when people go to access the data in the struct there's no guarantee that the data is unchanged/consistent since the lock is gone and we didn't return a copy of the struct.

So, I guess what I'm saying is that unless we make some bigger changes to how we deal with locks, I think I'm +1 to the idea of removing the locks.  However, I'm -1 on removing the functions because #12812 wanted to use at least one of them. The reason those exist is because "hostConfig" is private and there was no way for a non-container func to access them.  Granted if no one is calling them then who cares :-)  but #12812 found a reason for at least the get() one.

**Comment by duglin** [comment]
@LK4D4 you ok with removing the lock in those funcs?

**Comment by LK4D4** [comment]
@duglin I don't see where #12812 using those functions.
Also locks is actually mostly unnecessary in containers code. If functions unused - then let's remove them.

**Comment by duglin** [comment]
@LK4D4  #12812 used to use those func but then he ran into a deadlock situation due to all of the locks. So if we remove those locks then he can remove the extra WriteAs func that was added and go back to much smaller code change - which uses the funcs mentioned in this PR.

**Comment by LK4D4** [comment]
@duglin Yes, you can remove locks of course if it's producing deadlock.

**Comment by duglin** [comment]
I would suggest one of two next steps:
1) change this PR to just remove those locks - then #12812 can be reverted back to the old solution that didn't need the new func.
2) close this PR and remove the locks in #12812, and still revert the code back to the old solution.

@Mashimiao its up to you if you want to keep this PR just to remove the locks.

**Comment by Mashimiao** [comment]
Hi @duglin 
in #12669, according to your suggestion, I'm using daemon's SetHostConfig to replace container's SetHostConfig. But There will still locks in SetHostConfig

**Comment by duglin** [comment]
@Mashimiao I think there's some confusion.  Let's do this...
can you change this PR to **just** remove the locks in SetHostConfig and GetHostConfig ?  Change the title of the PR to something like "remove unneeded locks".
Then we can get that merged and worry about the other PRs ( #12669 and #12812 ) after that.

**Comment by Mashimiao** [comment]
@duglin   I have changed the title and code

**Comment by duglin** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
btw we need to reconsider many public functions now, when we removed integration tests.

**Pull request merged**
