### PR TITLE
Use spf13/cobra for docker stop

### PR DESCRIPTION
**Pull request by yongtang**
This fix is part of the effort to convert commands to spf13/cobra #23211.

Thif fix coverted command `docker stop` to use spf13/cobra

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like we may need to add some extra parsing if people use a single dash (but that's probably a "global" change, not for this PR);

```
docker stop -time=20 aa bb
invalid argument "ime=20" for time=20: strconv.ParseInt: parsing "ime=20": invalid syntax
See 'docker stop --help'.
```

@vdemeester @dnephin wdyt? ^^

**Comment by thaJeztah** [comment]
(current error looks like this);

```
docker stop -time=20 aa
invalid value "aa" for flag -t: strconv.ParseInt: parsing "aa": invalid syntax
See 'docker stop --help'.
flag provided but not defined: -time
See 'docker stop --help'.
```

**Comment by thaJeztah** [comment]
LGTM (unless we decide to make that change as part of this PR)

**Comment by vdemeester** [comment]
@thaJeztah yeah this can be changed after (and both error are not really good anyway :angel:)
LGTM 🐼

**Pull request merged**
