### PR TITLE
Improve/fix "Dockerizing Applications" page.

### PR DESCRIPTION
**Pull request by charleswhchan**
- Try to update the wording for the notes.

Signed-off-by: Charles Chan charleswhchan@users.noreply.github.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks, @charleswhchan. Hm, I'm not entirely convinced these improve the current wording. Was there anything in particular you found hard to read in the original text?

/cc @moxiegirl

**Comment by charleswhchan** [comment]
I could not pinpoint the issue, just the sentence felt unnatural when I was reading it. Perhaps grammar or sentence structure? 

You are welcome to disregard the changes if they do not improve the original.

**Comment by moxiegirl** [comment]
@charleswhchan Your rewrite does improve those two sentences.  The piece as a whole has other problems. For example, the use of first person plural everywhere.   In any case, I think we can merge this small change.

LGTM

**Comment by moxiegirl** [comment]
@thaJeztah This is a small change and it sounded like you had no major objects. I'll merge it.

**Pull request merged**
