### PR TITLE
Adding in comments from party

### PR DESCRIPTION
**Pull request by moxiegirl**
Updating some small areas that people commented on.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @spf13 @jamtur01 @fredlf @SvenDowideit

**Comment by fredlf** [comment]
LGTM, but I really don't see the need to constantly open new browser windows for users.

I am not alone in this view: 
http://www.nngroup.com/articles/top-10-mistakes-web-design/
http://www.smashingmagazine.com/2008/07/01/should-links-open-in-new-windows/

**Comment by moxiegirl** [comment]
Thanks Fred.  I only do _blank with links inside tutorials or procedures where I don't want users to navigate away from a specific point of the document.  I've read studies that go both ways. None of the  studies I've found focus on prefaces when users are learning tasks or following procedures.  I'm happy to do a usability study at some point.

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
