### PR TITLE
Move TimeoutConn to seperate pkg dir.

### PR DESCRIPTION
**Pull request by gewoonrik**
I have moved TimeoutConn to a seperate pkg dir and renamed the constructor and type as suggested in #10965.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Needs `gofmt -s -w`

**Comment by gewoonrik** [comment]
Yup, got it, will fix.

**Comment by gewoonrik** [comment]
Fixed it.

**Comment by estesp** [comment]
Still failed--you should try running tests locally before submitting the patch.  The registry function you are changing has a variable called `timeout` already.  You need to change that variable name to use the package properly within that code.

**Comment by gewoonrik** [comment]
You are right, I should have ran all tests instead of only the test I had moved.

**Comment by ahmetalpbalkan** [comment]
@gewoonrik how about calling the new package `timeoutconn`? `timeout.New` reminds me of timeout channels like time.After.

**Comment by gewoonrik** [comment]
Good suggestion! I agree.

**Comment by estesp** [comment]
Thanks for applying all the comments; the updates look good.

LGTM

**Comment by ahmetalpbalkan** [comment]
LGTM

**Comment by jfrazelle** [comment]
pretty! LGTM

**Pull request merged**
