### PR TITLE
Fixes broken link in docs.

### LINKED ISSUE #24428: [Docs] deprecated.md broken link
The [deprecated.md](https://github.com/docker/docker/blob/b98ba9a1d66d9b82eec510fb60a1ff7d7f2e7b0f/docs/deprecated.md) page is linking to the Github v1.12.0 release page, but that tag doesn't exist yet. Only v1.12.0-rc*

Replace the link by a valid one like the [v1.12.0-rc3](https://github.com/docker/docker/releases/tag/v1.12.0-rc3)

### PR DESCRIPTION
**Pull request by joaofnfernandes**
Fixes #24428

### CODE REVIEW

**Comment by yongtang** [comment]
I think when `1.12.0` is formally released, we want to have the link pointing to `1.12.0` not `1.12.0-rc3`. So there might be a chicken and egg issue here. We probably need to change back to `1.12.0` just before the `1.12.0` release (or cherry pick the change).

**Comment by SvenDowideit** [comment]
yes, its horrible that we've released broken documentation for a release that hasn't happened yet :(

unfortunately, the docs tooling expects there should be no broken links - and we've finally fixed enough that these are standing out like sore thumbs.

The other option, is to defuse the links (ie, put `backtics` around them)

**Comment by SvenDowideit** [comment]
@joaofnfernandes @thaJeztah what if we set the links to https://github.com/docker/docker/releases/ for now, and someone promises to fix it when 1.12.0 actually happens?

**Comment by joaofnfernandes** [comment]
I've changed the link to point to https://github.com/docker/docker/releases/.

In my opinion if we decide to link to something, we need to ensure that page exists, otherwise we're providing a bad user experience.
The other option is not linking, which also works.

**Comment by thaJeztah** [comment]
Alright, let's go for this, given that we remove it before GA

LGTM

**Pull request merged**
