### PR TITLE
Add Boaz Shuster ("ripcurld0") as curator

### PR DESCRIPTION
**Pull request by thaJeztah**
@ripcurld0 has been helping out a lot, so adding him as curator \o/

ping @moby/moby-maintainers 

**- A picture of a cute animal (not mandatory but encouraged)**

cute-animal-mammal-rodent-nager-nature-mouse-1751016

image taken from http://maxpixel.freegreatpicture.com/Mammal-Cute-Mouse-Rodent-Nature-Animal-Nager-1708347

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
author LGTM, windows failure is not related :smile:

**Comment by thaJeztah** [comment]
Welcome @ripcurld0 !

**Comment by yongtang** [comment]
Congratulations @ripcurld0! 👍

**Comment by ripcurld0** [comment]
I am so honored! 🎆 🎖 🕺

**Pull request merged**
