### PR TITLE
update fsnotify to v1.4.7

### PR DESCRIPTION
**Pull request by thaJeztah**
Fixes a possible deadlock on closing the watcher on kqueue

Full diff: https://github.com/fsnotify/fsnotify/compare/4da3e2cfbabc9f751898f250b49f2439785783a1...v1.4.7

Relevant change:

- https://github.com/fsnotify/fsnotify/pull/230 Fix possible deadlock on closing the watcher on kqueue

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
Janky https://jenkins.dockerproject.org/job/Docker-PRs/49957/console is failing on https://github.com/moby/moby/issues/34988 / https://github.com/moby/moby/issues/35039;

```
16:32:51 FAIL: check_test.go:347: DockerSwarmSuite.TearDownTest
16:32:51 
16:32:51 check_test.go:352:
16:32:51     d.Stop(c)
16:32:51 /go/src/github.com/docker/docker/internal/test/daemon/daemon.go:401:
16:32:51     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
16:32:51 ... Error: Error while stopping the daemon d80b0e79aeaf1 : exit status 130
16:32:51 
16:32:51 
16:32:51 ----------------------------------------------------------------------
16:32:51 PANIC: docker_api_swarm_test.go:359: DockerSwarmSuite.TestAPISwarmRaftQuorum
16:32:51 
16:32:51 [d80b0e79aeaf1] waiting for daemon to start
16:32:51 [d80b0e79aeaf1] daemon started
16:32:51 
16:32:51 [df17fe9c389ba] waiting for daemon to start
16:32:51 [df17fe9c389ba] daemon started
16:32:51 
16:32:51 [daa1fbf534ff8] waiting for daemon to start
16:32:51 [daa1fbf534ff8] daemon started
16:32:51 
16:32:51 [df17fe9c389ba] exiting daemon
16:32:51 [daa1fbf534ff8] exiting daemon
16:32:51 [df17fe9c389ba] waiting for daemon to start
16:32:51 [df17fe9c389ba] daemon started
16:32:51 
16:32:51 [d80b0e79aeaf1] daemon started
16:32:51 Attempt #2: daemon is still running with pid 32014
16:32:51 Attempt #3: daemon is still running with pid 32014
16:32:51 Attempt #4: daemon is still running with pid 32014
16:32:51 [d80b0e79aeaf1] exiting daemon
16:32:51 ... Panic: Fixture has panicked (see related PANIC)
```

PowerPC https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/10386/console as well;

```
16:34:18 FAIL: docker_api_swarm_test.go:359: DockerSwarmSuite.TestAPISwarmRaftQuorum
16:34:18 
16:34:18 [dfe5749ccf4c7] waiting for daemon to start
16:34:18 [dfe5749ccf4c7] daemon started
16:34:18 
16:34:18 [d8176498bf951] waiting for daemon to start
16:34:18 [d8176498bf951] daemon started
16:34:18 
16:34:18 [d6a1ac85d7cf1] waiting for daemon to start
16:34:18 [d6a1ac85d7cf1] daemon started
16:34:18 
16:34:18 [d8176498bf951] exiting daemon
16:34:18 [d6a1ac85d7cf1] exiting daemon
16:34:18 docker_api_swarm_test.go:385:
16:34:18     // d1 will eventually step down from leader because there is no longer an active quorum, wait for that to happen
16:34:18     waitAndAssert(c, defaultReconciliationTimeout, func(c *check.C) (interface{}, check.CommentInterface) {
16:34:18         _, err = cli.ServiceCreate(context.Background(), service.Spec, types.ServiceCreateOptions{})
16:34:18         return err.Error(), nil
16:34:18     }, checker.Contains, "Make sure more than half of the managers are online.")
16:34:18 docker_utils_test.go:435:
16:34:18     c.Assert(v, checker, args...)
16:34:18 ... obtained string = "Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
16:34:18 ... substring string = "Make sure more than half of the managers are online."
16:34:18 
16:34:18 [dfe5749ccf4c7] exiting daemon
```

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
