### PR TITLE
remove parallel we no longer use it

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon

### CODE REVIEW

**Comment by calavera** [comment]
now that you're at it, I think we don't use mercurial anymore either, do we?

**Comment by LK4D4** [comment]
@calavera maybe it's needed for some `go get` stuff :)

**Comment by tianon** [comment]
LGTM

Yeah, mercurial is still used for vendoring/go get.

**Comment by calavera** [comment]
LGTM

**Pull request merged**
