### PR TITLE
integration: fix flaky TestSwarmServiceWithGroup

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by vdemeester** [comment]
```
23:24:57 FAIL: docker_cli_swarm_test.go:246: DockerSwarmSuite.TestSwarmContainerAutoStart
```

janky failed on the other flaky test, restarting it

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Merging since there is no way RS1 test failures are from this.

**Pull request merged**
