### PR TITLE
update MAINTAINERS file

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux vieux@docker.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
can you also add michael to the bottom kill 2 birds w 1 stone

**Comment by jfrazelle** [comment]
:smiling_imp:

**Comment by vieux** [comment]
done, got a 3rd bird with `Github` -> `GitHub`

**Comment by jfrazelle** [comment]
omg its like Christmas LGTM

**Comment by thaJeztah** [comment]
Doh! Now I need to remove him from https://github.com/docker/docker/pull/10481?

**Comment by jfrazelle** [comment]
sorrry the other one needs more review because I dont know if we want to restucture those subsystems or not

**Comment by thaJeztah** [comment]
Yes, I kinda suspected that :smile: no prob

**Comment by vieux** [comment]
ping @crosbymichael

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
