### PR TITLE
Fedora 22 manual network configuration and ip forwarding

### PR DESCRIPTION
**Pull request by yyekhlef**
With systemd in version 219 IP forwarding should be forced in the interface configuration file.
Following @cles commit #6bd15a68c

### CODE REVIEW

**Comment by yyekhlef** [comment]
As mentioned in #14185 also for Fedora 22.
I didn't raise an issuefor this PR, don't know if I have to.
 
cc @thaJeztah @moxiegirl :-)

**Comment by thaJeztah** [comment]
> I didn't raise an issuefor this PR, don't know if I have to.

That's perfectly fine, no need to clutter the issue tracker :+1: 

LGTM, but could you squash your commits to a single commit?

thanks for your contribution

ping @moxiegirl for review (do we want this in 1.8?)

**Comment by moxiegirl** [comment]
@yyekhlef Thank you for the contribution!  LGTM

**Comment by moxiegirl** [comment]
@calavera Cherry pick?

**Comment by calavera** [comment]
cherry picked into #15091

**Pull request merged**
