### PR TITLE
Add `--dns-option` to `docker run` and hide `--dns-opt`

### PR DESCRIPTION
**Pull request by yongtang**
This fix is a follow up to #27567 based on comment:
https://github.com/docker/docker/pull/27567#issuecomment-259295055

In #27567, `--dns-options` has been added to `service create/update` (together with `--dns` and `--dns-search`). Though `--dns-opt` was used in `docker run` previously.

This fix add `--dns-option` to `docker run/create`, and hide `--dns-opt`.

This fix change `--dns-options` to `--dns-option` for `docker service create` and `docker service update`.

It is still possible to use `--dns-opt` with `docker run/create`, though it will not show up in help output.

This fix also updates the docs and bash/zsh completion scripts.

cc @thaJeztah @stevvooe 

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
Since multiple options may be taken, the flag should be `--dns-option`. For example:

`docker run --dns-option debug --dns-option timeout:25`

**Comment by yongtang** [comment]
@stevvooe The `docker service create` use `--dns-options`. Should we change `service create` to `--dns-option` (and `--dns-option-add/rm` for `service update`) as well?

**Comment by stevvooe** [comment]
@yongtang Yes, let's make them consistent and we can do it in this PR.

Thanks!

**Comment by vdemeester** [comment]
@yongtang I think we should mark the flag `--dns-opt` in the `deprecated.md` /cc @thaJeztah

**Comment by stevvooe** [comment]
LGTM

**Comment by thaJeztah** [comment]
@vdemeester we can also decide to keep it as alias, not sure what's best (comparing it to `--net` / `--network`). I'm ok with doing that separately

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
discussed with @vdemeester and he's ok with just hiding

**Review by vdemeester — APPROVED** [review]
Alright, I'm ok to hide it, just like `--net` and `--network`.
LGTM 🐸

**Comment by thaJeztah** [comment]
docs look good as well, all green: merging

**Pull request merged**
