### PR TITLE
fix a potential error in the `pkg/plugins/discovery.go`

### PR DESCRIPTION
**Pull request by miaoyq**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**
I modify  `if err != nil || fi.IsDir()` to  `if err != nil || (fi != nil && fi.IsDir())`

Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cpuguy83 ptal

**Comment by cpuguy83** [comment]
I don't see any harm with this, but also don't see how `fi` would be nil when `err` is not.
Did you see a panic somewhere?

**Comment by miaoyq** [comment]
The realization of the function `Walk` is as follows:
```go
func Walk(root string, walkFn WalkFunc) error {
	info, err := os.Lstat(root)
	if err != nil {
		return walkFn(root, nil, err)
	}
	return walk(root, info, walkFn)
}
```
As can be seen from the code, `fi` may be `nil`, So I added `fi != nil`
@cpuguy83

**Comment by cpuguy83** [comment]
Sure it can be `nil`, but only when `err` is not `nil`.

**Comment by miaoyq** [comment]
Oh, I got it, Thanks！

**Pull request closed without merging**
