### PR TITLE
daemon/graphdriver: split, internalize packages to separate snapshotters and graphdrivers

### PR DESCRIPTION
**Pull request by thaJeztah**
- relates to https://github.com/moby/moby/issues/32989

### daemon/graphdriver: move FsMagic utilities to an internal package

These utilities were used in both graphdrivers and snapshotters. Move them
to a separate package, to help decoupling snapshotters and graphdrivers,
and make it internal, as it's not intended to be used as a generic utility
package (we can still make it public if there would be a need).

### daemon/internal/fstype: make FsMagic values not platform-dependent

While detection of filesystem-types may not be supported on all platforms,
it should be ok to define the types; this would allow for these types to
be used to print names (e.g.) in cross-platform situations.

### daemon/graphdriver: simplify Checker, remove NewFsChecker, NewDefaultChecker

The Checker interface was introduced in 1ba05cdb6ade7e3abd4c4c3221b5e27645460111
as an optimization to allow passing a simplified check for situations that
don't require mountinfo.Mounted to be executed (as that may result in parsing
 `/proc/self/mountinfo`).

The Checker was defined as an interface with a single `IsMounted` method,
possibly with the intent to allow for additional kind of checks to be added.
No new additions were made since its inception 9 Years ago, and if a need would
arrive, could probably be implemented as part of the check.

This patch simplifies the definition to a function, removing the need to
implement a wrapper struct just to satisfy the interface. The `Checker`
type definition is somewhat redundant, but is kept to have a place to
provide GoDoc.

The `NewFsChecker` and `NewDefaultChecker` utilities are removed as part
of this change, favoring a local definition for storage-drivers that
used them.

### daemon/graphdriver: move RefCounter to an internal package

The RefCounter is used in both graphdrivers and snapshotters. Move it
to a separate package to help decoupling snapshotters and graphdrivers,
and make it internal, as it's not intended to be used as a generic utility
package (we can still make it public if there would be a need).

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vvoland — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@cpuguy83 this one LGTY?

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

**Comment by thaJeztah** [comment]
@cpuguy83 updated; PTAL

**Comment by thaJeztah** [comment]
@cpuguy83 ptal 🤗

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
