### PR TITLE
Remove TestPushInterrupt

### PR DESCRIPTION
**Pull request by aaronlehmann**
This test relies on a race condition, and has been failing often in CI.

cc @stevvooe @jhowardmsft

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

Do we have another way to cover this condition?

**Comment by aaronlehmann** [comment]
I don't think we have another way to cover it, at present.

I have a PR ready to submit that will make pushes use the same `Broadcaster` mechanism that pulls use, to fix #9132. This will remove the "already in progress" message, which will render the test even less useful. That PR adds a few tests for concurrent pushes, though none of them exactly match what this test is trying to do.

**Comment by jhowardmsft** [comment]
LGTM. Restarted Windows Jenkins.

**Comment by dmcgowan** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
