### PR TITLE
integration: fix flaky TestSwarmContainerAutoStart

### LINKED ISSUE #26588: DockerSwarmSuite.TestSwarmContainerAutoStart is flaky
Noticed in https://github.com/docker/docker/pull/26584 on experimental CI.

```
01:14:43 ----------------------------------------------------------------------
01:14:43 FAIL: docker_cli_swarm_test.go:246: DockerSwarmSuite.TestSwarmContainerAutoStart
01:14:43 
01:14:43 [d20f68f1ba9c8] waiting for daemon to start
01:14:43 [d20f68f1ba9c8] daemon started
01:14:43 [d20f68f1ba9c8] exiting daemon
01:14:43 [d20f68f1ba9c8] waiting for daemon to start
01:14:43 [d20f68f1ba9c8] daemon started
01:14:43 docker_cli_swarm_test.go:265:
01:14:43     c.Assert(strings.TrimSpace(out), checker.Not(checker.Equals), "")
01:14:43 ... obtained string = ""
01:14:43 ... expected string = ""
01:14:43 
01:14:43 [d20f68f1ba9c8] exiting daemon
01:14:45 
01:14:45 ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by LK4D4**
Fix #26588

### CODE REVIEW

**Comment by darrenstahlmsft** [comment]
windowsRS1 failure is unrelated. I'm tracking down a fix for it

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by tonistiigi** [comment]
@LK4D4 Can you explain what is going on here? We don't return from `run` until the container has been started and after restart we don't connect the API(checked by `daemon.Restart`) before they have been restored.

**Comment by LK4D4** [comment]
@tonistiigi? It used to be a different way; that's why we had `waitRun`. There was a gap between `run -d` and `Running` state(and show in `ps -q`). Maybe you're right and problem is in something else.

**Comment by tonistiigi** [comment]
@LK4D4 I think it should go with this path:
https://github.com/docker/docker/blob/master/daemon/start.go#L153
https://github.com/docker/docker/blob/master/libcontainerd/container_linux.go#L128
https://github.com/docker/docker/blob/master/daemon/monitor.go#L91

**Comment by LK4D4** [comment]
Yup, you're right! Then I don't know origin of failure :( Will try to find.

**Comment by tonistiigi** [comment]
@LK4D4 The issue here is that regular containers that get their overlay networks from swarm manager skip restore and are only started in `daemon.RestartSwarmContainers`. So for a quick fix, half of this PR makes sense. But we should probably figure out a way to block API until these containers are started as well to be compatible with everything else. cc @mrjana

**Comment by tonistiigi** [comment]
@mrjana Some suspicious lines from logs: https://gist.github.com/tonistiigi/00de73e9a25bf7f404ec8cc563a03429#file-docker-log-L517-L565

**Pull request closed without merging**
