### PR TITLE
Cherry picks for 1.12.0 rc2

### LINKED ISSUE #23017: Missing command completion of `dockerd`
Currently we have split docker binary to `dockerd` and `docker`, the command completion of `dockerd` is missing for now.

ping @albers  @sdurrheimer

### LINKED ISSUE #23376: Installation instructions for RHEL/CentOS should take "Server" version into account
The installation instructions currently use `$releasever` to configure the right YUM repository to use, however the instructions don't take into account the `Server` releases output the version in a different format (e.g. `7Server` instead of just `7`).

```
$ sudo tee /etc/yum.repos.d/docker.repo <<-'EOF'
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF
```

The installation script correctly strips the `Server` before generating the URL, so we should update the documentation to do the same, or show how to;
https://github.com/docker/docker/blob/v1.11.2/hack/install.sh#L283-L285

As reported by Aleksandr Vinokurov on Twitter https://twitter.com/aleksandrvin/status/740548856316858368 (thanks!)

Also;
https://access.redhat.com/discussions/2134691

### LINKED ISSUE #23596: /v1.23/containers/json API returns empty string for NetworkID.
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 62
 Running: 5
 Paused: 0
 Stopped: 57
Images: 57
Server Version: 1.11.2
Storage Driver: zfs
 Zpool: tank
 Zpool Health: ONLINE
 Parent Dataset: tank/docker
 Space Used By Parent: 2981614592
 Space Available: 100508783616
 Parent Quota: no
 Compression: lz4
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: vxlan bridge null host
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.842 GiB
Name: dc1-dks04
ID: T37Y:UHKY:FDQD:36FE:46U2:I2OV:TPO7:GG5G:KMRA:7FX4:XQRA:TZ5A
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://dc1-dks04.in.trilliumstaffing.com:8500
Cluster advertise: 10.1.8.169:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  `docker run -d busybox sleep 1000`
2. `curl --unix-socket /var/run/docker.sock http:/v1.23/containers/json | jq`

**Describe the results you received:**
```json
[
  {
    "Id": "ce43bbddcd79c43797eed177d18b8a0cbdea4827f18b6a0580947d3d2637f508",
    "Names": [
      "/small_yonath"
    ],
    "Image": "busybox",
    "ImageID": "sha256:47bcc53f74dc94b1920f0b34f6036096526296767650f223433fe65c35f149eb",
    "Command": "sleep 1000",
    "Created": 1466024674,
    "Ports": [],
    "Labels": {},
    "State": "running",
    "Status": "Up 3 minutes",
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "",
          "EndpointID": "09bca838a4d3244f2fcc02f3509edd665d75182397e54a8ab0ff12577f8349b3",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.2",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:02"
        }
      }
    },
    "Mounts": []
  }
]
```

**Describe the results you expected:**

The  `"NetworkID"` field should contain the networkID, not the empty string. The sample in the [docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/) has the NetworkID.

### PR DESCRIPTION
**Pull request by tiborvass**
Cherrypicking the following:
- [#23555](https://github.com/docker/docker/pull/23555)
  - 4104c1d Remove the node leader column, show leader as status.
- [#23505](https://github.com/docker/docker/pull/23505)
  - 0254c12 surfacing Learn by example topics to top level of Docker Engine docs fixing links after moving surfacing tutorials
- [#23557](https://github.com/docker/docker/pull/23557)
  - fec98ec Update experimental/README.md
- [#23301](https://github.com/docker/docker/pull/23301)
  - 756f6ce daemon: allow tmpfs to trump over VOLUME(s)
- [#23579](https://github.com/docker/docker/pull/23579)
  - 22f827a Fix hanging integration tests
- [#23542](https://github.com/docker/docker/pull/23542)
  - f2f97f7 Vendoring libnetwork 0d517a9e4e5cbdb889b3257eebd2351addcd46d4
  - 5af8e2a Vendoring swarmkit 682e0b69be208176d6055cba855a5e9cf15c7cb4
  - 07e39e9 Use service alias and configure container's --net-alias
- [#23565](https://github.com/docker/docker/pull/23565)
  - fa94eb4 fix links for #23505
- [#23510](https://github.com/docker/docker/pull/23510)
  - d3fad80 Fixes #23376 Broken URL for Centos yum repo for docker changed to now have a hardcoded centos version 7
- [#23604](https://github.com/docker/docker/pull/23604)
  - 1d80f8c fixing links and merge conflicts
- [#23602](https://github.com/docker/docker/pull/23602)
  - e927df7 Update libnetwork to 96d45528599c32354230480a1ebc0
- [#23558](https://github.com/docker/docker/pull/23558)
  - bd63170 Fix TestRunWithRuntime\* on arm
- [#23601](https://github.com/docker/docker/pull/23601)
  - 4df0349 Change SCALE to REPLICAS.
- [#23577](https://github.com/docker/docker/pull/23577)
  - d6d448a Avoid back and forth conversion between strings and bytes.
- [#23593](https://github.com/docker/docker/pull/23593)
  - bdf01cf Move mlock back into the default ungated seccomp profile
- [#23572](https://github.com/docker/docker/pull/23572)
  - bf988fc Change 'invald' to 'invalid' in volume opts errors
- [#23612](https://github.com/docker/docker/pull/23612)
  - f22d017 Service `--update-parallelism` defauls to 0
- [#23583](https://github.com/docker/docker/pull/23583)
  - ec4857d Add accept-permissions flag for install.
  - a2d48c9 Add basic integration tests for plugins.
- [#23625](https://github.com/docker/docker/pull/23625)
  - 18a59bb Remove out-of-date health test
- [#23623](https://github.com/docker/docker/pull/23623)
  - bc033cb advisory can't be in the [menu] section
- [#23568](https://github.com/docker/docker/pull/23568)
  - 88d4da7 Fix URL to issue
- [#23581](https://github.com/docker/docker/pull/23581)
  - c26e7d8 Fix String() for some option types
- [#23491](https://github.com/docker/docker/pull/23491)
  - e233c8d Update release script installation instructions
- [#23636](https://github.com/docker/docker/pull/23636)
  - db435f5 Set systemd KillMode
- [#23606](https://github.com/docker/docker/pull/23606)
  - 0858953 fix docker swarm init/update --secret
  - a579ce8 use same hash for same secret
  - aed7667 Add api tests for secret update
- [#23613](https://github.com/docker/docker/pull/23613)
  - b86cb29 api/client/service: list running services over replicas
- [#23635](https://github.com/docker/docker/pull/23635)
  - ad85d29 Fixes #23596-returns empty string for NetworkID in response to /containers/json
- [#23633](https://github.com/docker/docker/pull/23633)
  - aadd88c docs: move "advisory" to  general metadata
- [#23515](https://github.com/docker/docker/pull/23515)
  - 136323b Add ecryptfs check for overlay2
- [#23640](https://github.com/docker/docker/pull/23640)
  - 920e65c api/client/service: fix minor spelling error in service inspect
- [#23520](https://github.com/docker/docker/pull/23520)
  - eee20b5 Add security info to `docker info`
- [#23624](https://github.com/docker/docker/pull/23624)
  - 78f3094 Fix restore active sandbox
- [#23641](https://github.com/docker/docker/pull/23641)
  - f8d9701 Add the seccomp build tag for s390x now runc updated
- [#23639](https://github.com/docker/docker/pull/23639)
  - 7f2f6ed Vendoring Libnetwork caf22bd9a6a53dfe91b0266274155bc69235e8ed
- [#23646](https://github.com/docker/docker/pull/23646)
  - 07e1c62 Update docker info output example
- [#23570](https://github.com/docker/docker/pull/23570)
  - 58529a1 Bump engine-api to c57d0447ea1ae71f6dad83c8d8a1215a89869a0c
  - 2c82337 Update docker plugin install code…
  - 4a70cb5 Update ServiceInspectWithRaw
- [#23648](https://github.com/docker/docker/pull/23648)
  - 2d4b285 fix "overlay" -> "overlay2" in error message
- [#23549](https://github.com/docker/docker/pull/23549)
  - 79eada3 Do not show empty tags for digest references in output
- [#23643](https://github.com/docker/docker/pull/23643)
  - 2783568 Update swarmkit to 310f1119
  - a83bba4 Update daemon to new swarmkit
  - 1973cee Return membership status on join without timeout
- [#23637](https://github.com/docker/docker/pull/23637)
  - 4c9e21b add some more fields in docker service inspect -p
- [#23644](https://github.com/docker/docker/pull/23644)
  - 826f6f0 Fix removing containers on leaving from pending state
- [#23580](https://github.com/docker/docker/pull/23580)
  - 5e156fd Fix removing plugins
  - dfd9187 Implement plugin restore after daemon restart
- [#23651](https://github.com/docker/docker/pull/23651)
  - 7d8d51a Add cert-expiry to swarm update
  - a933ac3 Add integration test for parsing swarm update options
- [#23647](https://github.com/docker/docker/pull/23647)
  - eb96223 improve some messages in the node subcmds
- [#23652](https://github.com/docker/docker/pull/23652)
  - c0ea589 Add some tests for bundlefile and improve the error messages for LoadFile
- [#23656](https://github.com/docker/docker/pull/23656)
  - 3b2132c update output for node commands, minor edits
- [#23673](https://github.com/docker/docker/pull/23673)
  - 2322ccb fix invalid typo in error message
- [#23674](https://github.com/docker/docker/pull/23674)
  - c34d752 Missing line feed after accepting node
- [#23663](https://github.com/docker/docker/pull/23663)
  - dc2fc75 bash completion for `docker swarm update --cert-expiry`
- [#23675](https://github.com/docker/docker/pull/23675)
  - 22e781e Add disable flag for plugin Install.
- [#23664](https://github.com/docker/docker/pull/23664)
  - bd1fc1e fix #23017, add zsh completion for dockerd
- [#23676](https://github.com/docker/docker/pull/23676)
  - 0ec7873 `docker swarm`: more consistent CLI help
- [#23682](https://github.com/docker/docker/pull/23682)
  - 4fea811 Check if DriverState is valid before using in convert
- [#23688](https://github.com/docker/docker/pull/23688)
  - 3386e35 Add newline to promote/demote message
- [#23687](https://github.com/docker/docker/pull/23687)
  - 70e2585 Vendoring libnetwork @13be89d1cf79
- [#23681](https://github.com/docker/docker/pull/23681)
  - 4b70d45 plugins: install should not automatically accept all permissions
  - 15ff9de plugins: remove automatic mounting of a state dir
  - 65ed9da plugins: fix usage for plugin commands
  - cb321e8 Update plugin command with defaulttag
  - 8ba17b4 plugins: fix name handling for legacy plugins
- [#23692](https://github.com/docker/docker/pull/23692)
  - 3c60b7b Improve `docker service inspect --pretty`

### CODE REVIEW

**Comment by icecrime** [comment]
- Experimental hanged but was green (cc @tonistiigi)
- Documentation ¯\_(ツ)_/¯

**Comment by thaJeztah** [comment]
documentation failures are expected; the docker for mac docs are in a private repo, so are not included in the docs build here

```
 Filtered (engine) Summary:

* link error: (in page engine/getstarted/last_page.md) /docker-for-mac/index.md
* link error: (in page engine/getstarted/last_page.md) /docker-for-mac/index.md
* link error: (in page engine/getstarted/step_one.md) /docker-for-mac/index.md
* link error: (in page engine/getstarted/step_one.md) /docker-for-windows/index.md
```

**Comment by thaJeztah** [comment]
LGTM

**Comment by tiborvass** [comment]
Do not merge yet, i'll have to add more here

**Comment by thaJeztah** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM :+1:

**Pull request merged**
