### PR TITLE
Update docker load security docs

### LINKED ISSUE #24779: Why is Docker load command not secure?
https://docs.docker.com/engine/security/security/ says"   -  it should be noted that ‘docker load’ is a mechanism for backup and restore and is not currently considered a secure mechanism for loading images" but it does not provide any reason why it is not secure. Can anyone help me understanding that?

### PR DESCRIPTION
**Pull request by tonistiigi**
Previous comment was added in docker v1.5 and the original issues it is referring to do not apply anymore.

fixes #24779

@aaronlehmann

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

May want to add something about knowing source of a docker load file, but this is fine.

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by tangzhankun** [comment]
I saw this doc saying that "limiting the possibility of an attacker causing a collision with an existing image". Do you mean that "docker load" now won't replace existing image with a same tag name in the tar file (generated by "docker save") ?
As far as I know, one can tag a centos image with the name, for instance "ubuntu:14.04". And docker save it to a tar file. Then if another host "docker load" this tar file, this command would force to replace existing ubuntu:14.04. How can I avoid this?  Add an option "--override" to "docker load" and make it won't replace existing image others are using by default seems more reasonable to me.  Thoughts?
Please correct me if I missed something important.

**Comment by stevvooe** [comment]
@tangzhankun This addition has nothing to do with naming. This is about ensuring that layers cannot be replaced by with different content. `docker load` behavior for naming should be unaffected.

**Comment by tangzhankun** [comment]
@stevvooe , Thanks for the explanation. I guess I need to raise an issue for the behavior changes of "docker load". I think it should add option to let the user choose whether to replace existing same tag name image.

**Pull request merged**
