### PR TITLE
Remove job from stop

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by LK4D4** [comment]
We need some day decide what we want. Because in some PRs we getting container in api function and in some in daemon method.

**Comment by runcom** [comment]
@LK4D4 I thought about that, I liked much to have the daemon do the service layer btw, I'll happily refactor then we you decide..

**Comment by cpuguy83** [comment]
Also very much in favor of having methods on daemon, at least for now.
Let the API talk to one thing (daemon).

LGTM.

**Comment by duglin** [comment]
LGTM

**Pull request merged**
