### PR TITLE
Use spf13/cobra for docker pause

### PR DESCRIPTION
**Pull request by yongtang**
This fix is part of the effort to convert commands to spf13/cobra #23211.

Thif fix coverted command `docker pause` to use spf13/cobra

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
thanks, LGTM, but needs a rebase

**Comment by yongtang** [comment]
Thanks @cpuguy83 @thaJeztah the PR has been rebased.

**Comment by vdemeester** [comment]
LGTM 🐵

**Comment by LK4D4** [comment]
@yongtang need rebase :/

**Comment by yongtang** [comment]
Thanks. Just rebased again.

**Pull request merged**
