### PR TITLE
Update libcontainer to v0.0.2

### PR DESCRIPTION
**Pull request by LK4D4**
This is fix for proper setup of nested containers cgroups.

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
@LK4D4 are there issues that can be closed because of this? There are some [open issues regarding cgroups](https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cgroup+in%3Atitle), but I don't know if any of them should be fixed because of this. Perhaps you can check them?

**Comment by LK4D4** [comment]
I think some will be closed by previous PR. I'll take a look, thanks!

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
