### PR TITLE
Revert PR 29188 add selinux policy for centos-7 on 1.12.x branch

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Revert PR #29188 "add selinux policy for centos-7 on 1.12.x branch" to keep CentOS7.2 working.

**- How I did it**

$ git revert 97b6626
$ git revert 5455138
$ git revert 7e30cb6

**- How to verify it**

Make sure RPMs still build:
```
$ make DOCKER_BUILD_PKGS=centos-7 rpm
```

**- Description for the changelog**

Remove the line:

> Update selinux policy for distros based on RHEL7.3

**- A picture of a cute animal (not mandatory but encouraged)**

🕊

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
Needs an update to the changelog as well;

> Update selinux policy for distros based on RHEL7.3 #29188

**Comment by thaJeztah** [comment]
oh, never mind, see you mentioned that :blush: wasn't sure if we wanted it as part of the PR

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
