### PR TITLE
seccomp: remove modify_ldt

### PR DESCRIPTION
**Pull request by jessfraz**
re: https://github.com/docker/docker/pull/22579/files#diff-2441fc0087d867021a1308a30c5d00baR80

@justincormack let me know if this is a terrible mistake

### CODE REVIEW

**Comment by jfrazelle** [comment]
hmm janky got a new font, but still hates me

**Comment by justincormack** [comment]
For reference this was added because Go uses it on i386 binaries see https://github.com/docker/docker/pull/19218 https://github.com/docker/docker/issues/19201

However it has recently been removed from Go in https://github.com/golang/go/commit/0f86d1edfb87fddb2c7f50d177b67f48219151f3 with a note that it is not available on some newer kernels, and has to be explicitly made available on others, and replaced by the modern `set_thread_area`. Issue is https://github.com/golang/go/issues/14795. It does not seem this commit is in a release yet though.

There is also an unconfirmed suggestion that Wine uses it (allegedly even for 64 bit code) https://lkml.org/lkml/2015/7/21/759 would like to confirm if this the case because we have a lot of Steam users it seems based on other issues.

So a bit unsure, would like to block it, but I would be happier if there was a Go release that worked, as no 32 bit Go programs will run at all, and people do use 32 bit mode a bit.

**Comment by jfrazelle** [comment]
Ah I have a wine container I can test, and that's super interesting about
go

On Sunday, May 8, 2016, Justin Cormack <notifications@github.com> wrote:

> For reference this was added because Go uses it on i386 binaries see
> #19218 <https://github.com/docker/docker/pull/19218> #19201
> <https://github.com/docker/docker/issues/19201>
>
> However it has recently been removed from Go in golang/go@0f86d1e
> <https://github.com/golang/go/commit/0f86d1edfb87fddb2c7f50d177b67f48219151f3>
> with a note that it is not available on some newer kernels, and has to be
> explicitly made available on others, and replaced by the modern
> set_thread_area. Issue is golang/go#14795
> <https://github.com/golang/go/issues/14795>. It does not seem this commit
> is in a release yet though.
>
> There is also an unconfirmed suggestion that Wine uses it (allegedly even
> for 64 bit code) https://lkml.org/lkml/2015/7/21/759 would like to
> confirm if this the case because we have a lot of Steam users it seems
> based on other issues.
>
> So a bit unsure, would like to block it, but I would be happier if there
> was a Go release that worked, as no 32 bit Go programs will run at all, and
> people do use 32 bit mode a bit.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/22580#issuecomment-217705337>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
I think we can hold off for now, but just for future reference I will try some things, I have a steam container as well ;)

**Comment by jfrazelle** [comment]
I'm going to close as it's not realistic at this point in time, but will give updates on this thread after further testing so we have it for the future :)

**Comment by justincormack** [comment]
cool, it would be good to work out when we can reasonably remove it.

**Pull request closed without merging**
