### PR TITLE
Fix archive/changes_test.go on FreeBSD

### PR DESCRIPTION
**Pull request by kzys**
These two commits are required for fixing the test.

### CODE REVIEW

**Comment by oubiwann** [comment]
Hey, all -- what's the overall status on FreeBSD support?

I see that the following have occurred:
 * #7901 - Implement Docker on ZFS: closed in favor of #9411
 * #9411 - zfs-utils based zfs graph driver: merged
 * https://codereview.appspot.com/102640045/  was merged
 * I see lots of FreeBSD branches in @kzys' docker fork: https://github.com/kzys/docker
 * The main docker repo has lots of FreeBSD references peppered throughout (4 pages of search results)
 * The ChangeLog indicates that there is now FreeBSD support for the Docker client

Is there a roadmap, dev plan, or task list anywhere for FreeBSD support? 

Hope this is still in the works!

**Comment by thaJeztah** [comment]
@oubiwann actually, another contributor (@kvasdopil) is currently working on making Docker work on FreeBSD (see https://github.com/docker/docker/issues/13423). Looks to be stalled in https://github.com/docker/docker/pull/13542 at the moment (maintainers have been busy for DockerCon and the 1.7 release), but I'll see if I can get it moving again.

**Comment by kzys** [comment]
Sorry about that. I haven't know that @kvasdopil is taking over the efforts. Awesome :)

**Comment by thaJeztah** [comment]
@kzys I know he's working on it, not sure if he's using the same approach.

Are you interested in helping? (if he needs help)

**Comment by oubiwann** [comment]
@thaJeztah Oh, man -- this is GREAT news! I can't want to try it out :-D
Thanks for the info!

**Comment by thaJeztah** [comment]
@oubiwann it may still take a while, I think he's only working on the basics so far. Best way to keep up is subscribing to the pull requests.

**Pull request closed without merging**
