### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jessfraz**
merge https://github.com/docker/docker/pull/13528#commits-pushed-62fa0ac first.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM (after the 1.7 release)

one nit/idea; should "1.8 (not yet released)" be added at the top of the change log?

**Comment by jfrazelle** [comment]
i dont think we usually do that

**Comment by jfrazelle** [comment]
its kinda confusing, you should see the latest release first

**Comment by jfrazelle** [comment]
ping @icecrime @calavera @crosbymichael @tiborvass @LK4D4 whoever haha

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
Janky still has to LGTM :)

**Comment by icecrime** [comment]
LGTM

**Comment by icecrime** [comment]
I never remember, we bump API version separately?

**Comment by jfrazelle** [comment]
yes its been done ;)

**Pull request merged**
