### PR TITLE
made location of "repositories-"+d.driver.String() configurable

### PR DESCRIPTION
**Pull request by nnordrum**
made location of "repositories-"+d.driver.String() configurable, so it's easier to protected it when /var/lib/docker fills up.

If -repositories is not specified in daemon startup parameters, it will default back to use config.Root.

The one gap that may need to be addressed is usage of -g WITHOUT usage of -repositories. I figured I'd take it this far, then use the PR to start the discussion on the the best option for how to deal with those situations.

### CODE REVIEW

**Comment by cpuguy83** [comment]
What is this fixing?

:-1: to having this configurable. It should be kept with everything else.

**Comment by nnordrum** [comment]
```
# ls -l
total 300
drwxr-xr-x.  34 root root   8192 Nov  3 11:24 containers
drwxr-xr-x.   4 root root     31 Oct 28 17:18 devicemapper
drwx------. 566 root root  53248 Nov  3 11:18 graph
drwx------.   2 root root     33 Sep  4 18:42 init
-rw-r--r--.   1 root root  67584 Nov  3 11:24 linkgraph.db
-rw-------.   1 root root  33906 Nov  3 11:20 repositories-devicemapper
-rw-------.   1 root root  36864 Oct 28 13:00 repositories-devicemapper.corrupt
drwx------.   3 root root     94 Nov  3 11:03 tmp
drwx------.   2 root root     26 Sep  4 18:53 trust
drwxr-xr-x.   3 root root     16 Oct 28 17:18 vfs
drwx------. 647 root root 192512 Nov  3 11:16 volumes
```
my `/var/lib/docker` mount filled up, which caused the repositories-devicemapper to become corrupt. To prevent this, I created separate LVs for containers, device mapper, and vfs. It would be easier if the repositories-* files were in a separate directory, so I could isolate that one directory from the file system filling up instead of having to isolate a number of other directories.

Ideally, I would like to see the repositories-* files stored in a repositories directory by default, and/or docker should be ***much*** more defensive about writing to the repositories-* file to prevent it from getting corrupt, but I figured that would be a ***LOT*** harder to push through... 

I realize this seems kinda stupid if you're running on a MacBook as your primary environment, but when you're using SAN-backed storage, you can't/don't want to necessarily just keep throwing disk at it. Also, I know you can/should be cleaning things up more regularly, but that only encourages you to have a smaller /var/lib/docker.

**Comment by cpuguy83** [comment]
Wouldn't it be better to keep Docker from messing up this file in cases like this?

**Comment by nnordrum** [comment]
Absolutely--but that's a broader fix with potential implications well beyond my understanding of docker guts... 

Ideally, I think I'd still like it in a child directory though (and move link graph.db while we're at it) so it's relatively easy to move the different subdirectories to different storage types (i.e. empty root with only child dirs) if one so desires.

**Comment by nnordrum** [comment]
what about that for a safer file save? I'm *far* from a Go expert, so there likely is a better way to do that that I'm just not aware of. would back out f17d624 if a581817 would be the preferred way to go.

**Comment by LK4D4** [comment]
I don't know, sounds hackish. Too many moving parts is bad, too.
ping @docker/core-maintainers

**Comment by nnordrum** [comment]
I agree that my PR is likely not the best way to do it, but the problem still exists--the repositories-devicemapper file can get corrupt when the file system fills up, and it's painful to recover from. The file should be better protected, in one way or another. It seems like linking it to somewhere else that's protected is the preferred option.

**Comment by LK4D4** [comment]
@nnordrum Is this problem only with devicemapper? Why not protect place where repositories-devicemapper now?

**Comment by thaJeztah** [comment]
ping @nnordrum have you tried if symlinking is a solution for your use case?

I understand your thought, but we should also guard against making each and every option configurable, unless there's a really strong reason to do so.

**Comment by calavera** [comment]
It looks like there is certain opposition to this change and an easy workaround, creating that symlink. I'm going to close this PR, but please, feel free to open an issue where we can discuss the specific problem and a broader solution further.

**Comment by nnordrum** [comment]
@thaJeztah I'm going to symlink. I just want to keep my setup as close to stock as possible, and thought that having better protection for this file, or moving it into a subdirectory (which I could create a separate LV for), would help protect it and keep everything stock.

**Pull request closed without merging**
