### PR TITLE
[RFC]/[WIP] Update go to 1.9

### PR DESCRIPTION
**Pull request by yongtang**
This PR is an effort to see if we could update go to 1.9:

The go1.9 has already been released on 08/24/2017:
https://blog.golang.org/go1.9

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
The following warning:
```
21:23:50 # github.com/docker/docker/cmd/dockerd
21:23:50 /tmp/go-link-468295388/000010.o: In function `mygetgrouplist':
21:23:50 /usr/local/go/src/os/user/getgrouplist_unix.go:15: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
21:23:50 /tmp/go-link-468295388/000010.o: In function `mygetgrgid_r':
21:23:50 /usr/local/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
21:23:50 /tmp/go-link-468295388/000010.o: In function `mygetgrnam_r':
21:23:50 /usr/local/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
21:23:50 /tmp/go-link-468295388/000010.o: In function `mygetpwnam_r':
21:23:50 /usr/local/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
21:23:50 /tmp/go-link-468295388/000010.o: In function `mygetpwuid_r':
21:23:50 /usr/local/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

points to the usage of `os/user` in `vendor/golang.org/x/oauth2/google/sdk.go`.

The above issue is loosely related to #29478 which avoids calling `os/user`.

**Comment by yongtang** [comment]
Another warning:
```
/tmp/go-build/net/_obj/cgo-gcc-prolog:46: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

could be fixed by adding `-tags "netgo"`

**Comment by cpuguy83** [comment]
Dup of #33892?

**Comment by yongtang** [comment]
@cpuguy83 didn't notice #33892, let me close this on. Thanks.

**Pull request closed without merging**
