### PR TITLE
Add zsh completion for the new 'docker secret' command

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #27794

I didn't manage to test it on a 1.13 build yet. I would really appreciate if someone can test it to confirm that secret completion is working well.

ping @albers for bash completion

Signed-off-by: Steve Durrheimer <s.durrheimer@gmail.com>

### CODE REVIEW

**Comment by albers** [comment]
@sdurrheimer Thanks for the ping.

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Thank you @sdurrheimer !

**Comment by vdemeester** [comment]
@sdurrheimer don't forget to also add `--secret` completion to `service create` and `service update` 👼

**Pull request merged**
