### PR TITLE
Fixes work of inspectResponse in case of ContentLength=-1

### PR DESCRIPTION
**Pull request by skabashnyuk**
**- What I did**
Provide a fix for https://github.com/docker/docker/issues/30500. Unable to build dockerfile hosted remotely if ContentLength=-1
**- How I did it**
I've sliced ```preamble``` array for a number of bytes  actually read from stream in this  line ```	rlen, err := r.Read(preamble)```
**- How to verify it**
In ```TestMakeRemoteContext``` replace ```remoteURL := serverURL.String()```
with ```	remoteURL := "https://raw.githubusercontent.com/mkuznyetsov/dockerfiles/master/Dockerfile"```
```dockerfile``` content should be 

```[70 82 79 77 32 99 111 100 101 110 118 121 47 117 98 117 110 116 117 95 106 100 107 56 58 108 97 116 101 115 116 10]```
instead of 
```[70 82 79 77 32 99 111 100 101 110 118 121 47 117 98 117 110 116 117 95 106 100 107 56 58 108 97 116 101 115 116 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]```

 

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Can you consider adding an UT?

**Comment by skabashnyuk** [comment]
test added
without fix
```

Sun Jan 29 22:21:43 UTC 2017
=== RUN   TestUnknownContentLength
--------
-1
--------
--- FAIL: TestUnknownContentLength (0.00s)
	remote_test.go:169: Corrupted response body FROM busybox
FAIL
coverage: 11.9% of statements
exit status 1
FAIL	github.com/docker/docker/builder	0.014s
make: *** [test-unit] Error 1
```
with fix
```
---> Making bundle: test-unit (in bundles/1.14.0-dev/test-unit)
Sun Jan 29 22:20:35 UTC 2017
=== RUN   TestUnknownContentLength
--------
-1
--------
--- PASS: TestUnknownContentLength (0.00s)
PASS
coverage: 11.9% of statements
ok  	github.com/docker/docker/builder	0.010s
```

**Comment by LK4D4** [comment]
LGTM
ping @docker/core-engine-maintainers

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
