### PR TITLE
Update swarmkit to 25572005f

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes the ci flakiness with drain test and issues with manager demotion.

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM if green.

**Comment by mlaventure** [comment]
Should the test be re-enabled too then?

**Comment by tonistiigi** [comment]
@mlaventure It is in b38408fd0287a5d6eda4f8083b83806faf5d5cbd . There was a slight issue in the test as well so I changed it a bit but the assertion that failed before is still there.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
