### PR TITLE
Add bash completion for `docker service {create,update} --tty`

### PR DESCRIPTION
**Pull request by albers**
Ref: #28076

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM!

**Comment by albers** [comment]
@thaJeztah please tag this for 1.13.0

**Comment by thaJeztah** [comment]
done!

**Comment by albers** [comment]
Thanks @thaJeztah!

**Pull request merged**
