### PR TITLE
Add Fedora 25 RPMs

### PR DESCRIPTION
**Pull request by thaJeztah**
This is a temporary version for building
Fedora 25. Fedora 25 will be released during
code-freeze, and is currently in beta, so no
official images are available yet.

Current release date is scheduled for 2016-11-15
https://fedoraproject.org/wiki/Releases/25/Schedule

Once released, the image will be updated for
GA

addresses https://github.com/docker/docker/issues/27500 (but don't close until we have the official images)

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @andrewhsu @runcom PTAL

**Comment by andrewhsu** [comment]
I'll have a go at installing the rpm on a [fedora 25 prerelease](https://getfedora.org/en/workstation/prerelease/) image.

**Comment by andrewhsu** [comment]
Hmm...building an rpm from the `add-fedora-25` branch, I'm getting build errors:
```
$ time make DOCKER_BUILD_PKGS=fedora-25 rpm
...
 ---> c4da4c3ff04c
Removing intermediate container 8acc1ada95f4
Step 10/13 : ENV GOPATH $GOPATH:/manvendor
 ---> Running in 84eb3d62e768
 ---> 0bbf8b31eb9c
Removing intermediate container 84eb3d62e768
Step 11/13 : RUN go build -o /usr/bin/go-md2man github.com/cpuguy83/go-md2man
 ---> Running in 19d5129327a1
 ---> ee37c8c66708
Removing intermediate container 19d5129327a1
Step 12/13 : WORKDIR /go/src/github.com/docker/docker/
 ---> Running in 416a0bab3ba2
 ---> 3c6e06fba8e8
Removing intermediate container 416a0bab3ba2
Step 13/13 : ENTRYPOINT man/generate.sh
 ---> Running in c5ca8acbd63f
 ---> ee52f4b649a9
Removing intermediate container c5ca8acbd63f
Successfully built ee52f4b649a9
docker run --rm \
        -v /go/src/github.com/docker/docker:/go/src/github.com/docker/docker/ \
        docker-manpage-dev
cli/command/secret/create.go:4:2: cannot find package "context" in any of:
        /go/src/github.com/docker/docker/vendor/context (vendor tree)
        /usr/lib/go/src/context (from $GOROOT)
        /go/src/context (from $GOPATH)
        /manvendor/src/context
Makefile:106: recipe for target 'manpages' failed
make: *** [manpages] Error 1
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/build-rpm)
+++++ cat bundles/1.13.0-dev/build-rpm/docker.pid
++++ kill 4957
make: *** [rpm] Error 1

real    3m38.572s
user    0m2.778s
sys     0m1.061s
```

**Comment by thaJeztah** [comment]
Scrolling through my history, looks like we may have to bump SELinux as well;

```
make -f /usr/share/selinux/devel/Makefile docker.pp
make[1]: Entering directory '/root/rpmbuild/BUILD/docker-engine-selinux'
docker.if:71: Error: duplicate definition of docker_exec_lib(). Original definition on 506.
docker.if:109: Error: duplicate definition of docker_read_share_files(). Original definition on 510.
docker.if:128: Error: duplicate definition of docker_manage_lib_files(). Original definition on 518.
docker.if:148: Error: duplicate definition of docker_manage_lib_dirs(). Original definition on 523.
docker.if:184: Error: duplicate definition of docker_lib_filetrans(). Original definition on 527.
docker.if:202: Error: duplicate definition of docker_read_pid_files(). Original definition on 531.
docker.if:221: Error: duplicate definition of docker_systemctl(). Original definition on 535.
docker.if:264: Error: duplicate definition of docker_use_ptys(). Original definition on 539.
docker.if:314: Error: duplicate definition of docker_stream_connect(). Original definition on 543.
docker.if:333: Error: duplicate definition of docker_spc_stream_connect(). Original definition on 547.
docker.if:392: Error: duplicate definition of domain_stub_named_filetrans_domain(). Original definition on 1605.
docker.if:398: Error: duplicate definition of lvm_stub(). Original definition on 14.
docker.if:403: Error: duplicate definition of staff_stub(). Original definition on 13.
docker.if:408: Error: duplicate definition of virt_stub_svirt_sandbox_domain(). Original definition on 29.
docker.if:413: Error: duplicate definition of virt_stub_svirt_sandbox_file(). Original definition on 51.
docker.if:418: Error: duplicate definition of fs_dontaudit_remount_tmpfs(). Original definition on 5113.
docker.if:425: Error: duplicate definition of dev_dontaudit_list_all_dev_nodes(). Original definition on 221.
docker.if:432: Error: duplicate definition of kernel_unlabeled_entry_type(). Original definition on 3925.
docker.if:439: Error: duplicate definition of kernel_unlabeled_domtrans(). Original definition on 3904.
docker.if:448: Error: duplicate definition of files_write_all_pid_sockets(). Original definition on 7980.
docker.if:455: Error: duplicate definition of dev_dontaudit_mounton_sysfs(). Original definition on 4635.
```

/cc @crosbymichael

**Comment by vieux** [comment]
I think what's going on it, in order to generate the man pages, we have to build the client.
We do that using the `man/Dockerfile` and this dockerfile comes with an older verion of go.

the secrets PR added the `context` dependencie in the client, only available in go 1.7

**Comment by thaJeztah** [comment]
@vieux oh, thinking of it, it could be I built before rebasing, which would explain that

**Comment by vieux** [comment]
@andrewhsu #28224 was merged, can you retest please ?

**Comment by andrewhsu** [comment]
I still get build errors:
```
$ time make DOCKER_BUILD_PKGS=fedora-25 rpm
...
docker run --rm \
        -v /go/src/github.com/docker/docker:/go/src/github.com/docker/docker/ \
        docker-manpage-dev
cli/command/swarm/unlock.go:5:2: cannot find package "context" in any of:
        /go/src/github.com/docker/docker/vendor/context (vendor tree)
        /usr/lib/go/src/context (from $GOROOT)
        /go/src/context (from $GOPATH)
        /manvendor/src/context
Makefile:106: recipe for target 'manpages' failed
make: *** [manpages] Error 1
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/build-rpm)
+++++ cat bundles/1.13.0-dev/build-rpm/docker.pid
++++ kill 4996
make: *** [rpm] Error 1

real    3m59.576s
user    0m2.394s
sys     0m0.650s
```

The `make manpages` is not even working on the `add-fedora-25` branch:
```
$ time make manpages
...
Step 13 : ENTRYPOINT man/generate.sh
 ---> Using cache
 ---> 1a10ea51a51f
Successfully built 1a10ea51a51f
docker run --rm \
                -v /Users/andrewhsu/src/thaJeztah-docker:/go/src/github.com/docker/docker/ \
                docker-manpage-dev
cli/command/swarm/unlock.go:5:2: cannot find package "context" in any of:
        /go/src/github.com/docker/docker/vendor/context (vendor tree)
        /usr/lib/go/src/context (from $GOROOT)
        /go/src/context (from $GOPATH)
        /manvendor/src/context
make: *** [manpages] Error 1

real    0m7.301s
user    0m0.069s
sys     0m0.081s
```

Looks like 0f9fc54 brought in `"context"` to `cli/command/swarm/unlock.go`. I've created #28243.

**Comment by thaJeztah** [comment]
Flaky test? or due to the API version fallback (@vieux?)

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/26558/console

```
10:40:42 ----------------------------------------------------------------------
10:40:42 FAIL: docker_cli_authz_unix_test.go:318: DockerAuthzSuite.TestAuthZPluginAllowEventStream
10:40:42 
10:40:42 [dd102c2b636b5] waiting for daemon to start
10:40:42 [dd102c2b636b5] daemon started
10:40:42 docker_cli_authz_unix_test.go:377:
10:40:42     assertURIRecorded(c, s.ctrl.requestsURIs, fmt.Sprintf("/containers/%s/start", containerID))
10:40:42 docker_cli_authz_unix_test.go:475:
10:40:42     c.Fatalf("Expected to find URI '%s', recorded uris '%s'", uri, strings.Join(uris, ","))
10:40:42 ... Error: Expected to find URI '/containers/99dcadcca0e73309dfd18ac7e122691ca95dac8e3be1cb59bf764fa3b65f3706/start', recorded uris '/_ping,/info,/_ping,/v1.25/images/load?quiet=1,/_ping,/_ping,/v1.25/events?since=1478774441,/v1.25/containers/create,/v1.25/events?filters=%7B%22container%22%3A%7B%2299dcadcca0e73309dfd18ac7e122691ca95dac8e3be1cb59bf764fa3b65f3706%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D,/_ping,/v1.25/containers/99dcadcca0e73309dfd18ac7e122691ca95dac8e3be1cb59bf764fa3b65f3706/json'
10:40:42 
10:40:42 [dd102c2b636b5] exiting daemon
10:40:43 
10:40:43 ----------------------------------------------------------------------
```

**Comment by andrewhsu** [comment]
Now that #28243 is in master, verifying again with rebase to master.

**Comment by andrewhsu** [comment]
Hmm...coming across this error when building:
```
$ time make DOCKER_BUILD_PKGS=fedora-25 rpm
...
---> Making bundle: build-rpm (in bundles/1.13.0-dev/build-rpm)
INFO: Waiting for daemon to start...
+++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/1.13.0-dev/build-rpm/docker.sock --storage-driver aufs --pidfile bundles/1.13.0-dev/build-rpm/docker.pid --userland-proxy=true
.
docker build -t docker-manpage-dev -f "man/Dockerfile" ./man
Sending build context to Docker daemon 779.3 kB
Step 1/13 : FROM alpine:3.4
Get https://registry-1.docker.io/v2/library/alpine/manifests/3.4: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 172.17.0.2:59584->192.168.65.1:53: i/o timeout
Makefile:106: recipe for target 'manpages' failed
make: *** [manpages] Error 1
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/build-rpm)
+++++ cat bundles/1.13.0-dev/build-rpm/docker.pid
++++ kill 4992
make: *** [rpm] Error 1

real    1m52.640s
user    0m2.559s
sys     0m0.676s
```

Even though `manpages` is building for me:
```
$ time make manpages
...
Step 13 : ENTRYPOINT man/generate.sh
 ---> Running in 20e85e7b839c
 ---> 2f3635868d7d
Removing intermediate container 20e85e7b839c
Successfully built 2f3635868d7d
docker run --rm \
                -v /Users/andrewhsu/src/thaJeztah-docker:/go/src/github.com/docker/docker/ \
                docker-manpage-dev
Generating man pages into ./man/man1

real    1m7.488s
user    0m0.084s
sys     0m0.091s
```

**Comment by vieux** [comment]
failure is unrelated can we merge @andrewhsu ?

**Comment by runcom** [comment]
LGTM, Fedora 25 will be out next week though

**Comment by thaJeztah** [comment]
Thanks @runcom, we can update once it's out :tada:

**Comment by andrewhsu** [comment]
LGTM

Stuff works now. Turns out I had an issue with docker for mac beta release this morning (living on the edge).

```
$ time make DOCKER_BUILD_PKGS=fedora-25 rpm
Successfully built 47e2cede7bc9
RPMS/
RPMS/noarch/
RPMS/noarch/docker-engine-selinux-1.13.0-0.0.20161109.171613.git33c4a2c.fc25.noarch.rpm
RPMS/x86_64/
RPMS/x86_64/docker-engine-debuginfo-1.13.0-0.0.20161109.171613.git33c4a2c.fc25.x86_64.rpm
RPMS/x86_64/docker-engine-1.13.0-0.0.20161109.171613.git33c4a2c.fc25.x86_64.rpm
SRPMS/
SRPMS/docker-engine-selinux-1.13.0-0.0.20161109.171613.git33c4a2c.fc25.src.rpm
SRPMS/docker-engine-1.13.0-0.0.20161109.171613.git33c4a2c.fc25.src.rpm
Untagged: docker-temp/build-rpm:fedora-25
Deleted: sha256:47e2cede7bc9bc1791d96eb7ce23ed3929f2369281a5f4867605e919ddc168cc
...
Deleted: sha256:0e1166e51b735c9c22d99d31dcc9ff99ffb101793f01ed92801d0f431088206b
++++ cat bundles/1.13.0-dev/build-rpm/docker.pid
+++ kill 4997


real    13m38.596s
user    0m2.731s
sys     0m1.130s
```

**Pull request merged**
