### PR TITLE
vendor: github.com/moby/swarmkit/v2 v2.0.0-20230406225228-75e92ce14ff7

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on https://github.com/moby/moby/pull/45290

---

- update various dependencies
- Windows: Support local drivers internal, l2bridge and nat https://github.com/moby/swarmkit/pull/3121

full diff: https://github.com/moby/swarmkit/compare/e28e8ba9bc83...75e92ce14ff7bec88cda5fbd4c2d0130859657ec

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by neersighted — APPROVED** [review]
We should take a look at SwarmKit and decide if we need to create a 23.0 branch for future backports/if we can no longer take master into 23.0 (e.g. I don't think we should cherry-pick this change into 23.0).

**Comment by thaJeztah** [comment]
> We should take a look at SwarmKit and decide if we need to create a 23.0 branch for future backports/if we can no longer take master into 23.0 (e.g. I don't think we should cherry-pick this change into 23.0).
 
Yes, we need to have a look at that. Some quick thoughts;

- Ideally, we would be able to stick to regular Go (and SemVer) conventions (i.e., where possible we should try to avoid having to avoid "special" branches; things can get complicated fast (especially if go modules would try to resolve "minimum version"; is a 20240101 pseudo version from a 23.0 branch "newer" than a "20230601" pseudo version from master/main??))
- ^^ because in that case, we will end up with having to enforce versions (`replace` rules all over again?)
- However, if we do, it means we may have to "gate" new features if they (currently) are automatically exposed in Moby's set of features (can we?)

**Comment by thaJeztah** [comment]
Was wondering if we could gate these options (based on API version?) on our side; that way we could (at least for this one), still maintain a single branch / release cycle for swarm kit.

For "23.0 branch"; perhaps we could still do this, but base branches on _minor_ versions ("new features added").

- Tag whatever 23.0 currently uses as `v2.0.0`
- Create a `v2.1.0`  tag (based on master/main) with this feature included
- If we need fixes for 23.0, without introducing new features (for if we don't have the option to block new features on our side), we can create a `v2.0` branch, backport fixes, and tag as `v2.0.1` (etc)


@neersighted @dperny any thoughts?

**Comment by thaJeztah** [comment]
The only risk with "long-lived-branches for minor releases" is that SemVer won't agree, so if _any_ dependency would have "v2.1.0" (or up) as minimum version, then Go modules may force us to update (unless we apply `replace` rules).

**Review by tianon — APPROVED** [review]

**Pull request merged**
