### PR TITLE
Display SystemStatus field in docker info

### LINKED ISSUE #19277: Add new field for Swarm in Docker Engine API
Currently, the `/info` endpoint for the Swarm API uses `DriverStatus` field in the Engine API. We would like to create a new field exclusively for Swarm to use.

Corresponding `docker/swarm` issue: https://github.com/docker/swarm/issues/1625

cc @calavera @vieux

### PR DESCRIPTION
**Pull request by nishanttotla**
Fixes #19277. Please also see related `docker/engine-api` PR https://github.com/docker/engine-api/pull/46 and `docker/swarm` issue https://github.com/docker/swarm/issues/1625

Signed-off-by: Nishant Totla nishanttotla@gmail.com

### CODE REVIEW

**Comment by nishanttotla** [comment]
cc @calavera @vieux

**Comment by nishanttotla** [comment]
Amended commit to remove changes in vendor. `docker/engine-api` will be vendored in again at the end of this week, after which the new field added in https://github.com/docker/engine-api/pull/46 should be ready to use.

**Comment by thaJeztah** [comment]
So this will only show information when talking to Swarm? (Asking, to check if the documentation needs to be updated)

**Comment by vieux** [comment]
SGTM

The output of docker info is going to be exactly the same (but the underlying JSON will be different)

**Comment by nishanttotla** [comment]
@thaJeztah that's right. Technically it could also be used by any other tool built on top of Docker, to print status info.

**Comment by dongluochen** [comment]
SGTM.

**Comment by tiborvass** [comment]
@nishanttotla Out of curiosity, I see it is in the API already for 1.10, but why do you need it also to be in the output of the client-side `docker info` ?

**Comment by nishanttotla** [comment]
@tiborvass For users that talk to Swarm manager using the Docker client, the cluster information will be put into `SystemStatus` for the new API version (1.23 and beyond), instead of `DriverStatus` as was previously the case.

**Comment by tiborvass** [comment]
@nishanttotla so is this considered a bugfix? Since information is lost compared to 1.9 if we don't take this PR for 1.10 ?

**Comment by nishanttotla** [comment]
@tiborvass Since `SystemStatus` field has already been merged into `engine-api` and vendored, I think we could consider this a bug fix.

If this isn't merged, then to not lose information, we'd have to start supporting the new field only from the next API version.

**Comment by thaJeztah** [comment]
I think we should be able to add it to the 1.10 milestone

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by duglin** [comment]
when I try to build this branch I see:
```
api/client/info.go:45: info.SystemStatus undefined (type types.Info has no field or method SystemStatus)
```
is there something special I need to do ?

**Comment by tiborvass** [comment]
@duglin what command do you type when you're building this branch?

**Comment by duglin** [comment]
huh?  just `make binary`

**Comment by duglin** [comment]
where's the PR that added this to the rest of the engine?

**Comment by duglin** [comment]
Can we get a testcase for this? I don't see any new output when I do "docker info" so I think its important that we make sure the output is visible when whatever magic steps are necessary to enable it, and that it shows the right stuff.

**Comment by duglin** [comment]
btw - I did get it to build but only after I rebased from master.

**Comment by duglin** [comment]
Also, are there doc changes we need for this? Perhaps even just to update sample output?  I dunno, since I'm not clear when this should appear in the output.

**Comment by nishanttotla** [comment]
@duglin The `engine-api` changes are vendored in, so you can see the changes reflected here: https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/engine-api/types/types.go

The new field itself is used by Swarm only for now, and doesn't print anything if you're not using the Docker client to talk to a Swarm manager.

**Comment by duglin** [comment]
@nishanttotla yea I saw that but I didn't realize that there was no corresponding engine code associated with it - I understand now, thanks.

I am wondering though.  Given the APIs are meant to be a bit generic and Swarm is just one possible alternative backend for the APIs, does it really make sense to hard-code "SystemStatus" into the APIs rather than defining a well known extension point that allows for implementation-specific API backends to add their own data?  In other words, is the engine-api going to change to add a new field for each backend that wants to expose something just for them?  I would guess no, and in that case I wouldn't want to treat Swarm any differently, or special, from any other backend.

For example, I could imagine someone wanting their notion of a user to be returned as part of the "docker info".  How would that implementation add that to "docker info"?  Whatever that answer is should probably be the same answer for how Swarm would expose SystemStatus.  no?

ping @icecrime

**Comment by nishanttotla** [comment]
@duglin that's a fair point, which is why the field is generic and not tied down to Swarm in any way. Any other application that builds on top of Engine and wants to support the Docker API can use this field to print additional info. The discussion on #19277 and https://github.com/docker/engine-api/issues/44 makes this more explicit.

**Comment by duglin** [comment]
Ah, so you're saying "SystemStatus" is meant to be that extension point?  If so, ok - just not the words I would have picked since it implies one particular type of data.  Something more generic would have probably have been better.

I do think we need some docs around this then so tooling folks know that they're supposed to use this.

**Comment by nishanttotla** [comment]
@duglin we had `CustomStatus` in mind earlier, but @calavera thought it made more sense to use `SystemStatus`. I can open a separate PR to update documentation about this.

**Comment by thaJeztah** [comment]
@duglin should it be documented in the docker-api docs, or swarm?

**Comment by duglin** [comment]
@thaJeztah probably engine-api since its the one defining the extension point.

**Comment by nishanttotla** [comment]
If you can point me to where the documentation should be, I can open another PR updating it.

**Comment by thaJeztah** [comment]
Error on gccgo;
```
19:46:41 FAIL: docker_cli_network_unix_test.go:995: TestDockerNetworkHostModeUngracefulDaemonRestart.pN59_github_com_docker_docker_integration_cli.DockerNetworkSuite
19:46:41 
19:46:41 [d59175000] waiting for daemon to start
19:46:41 [d59175000] daemon started
19:46:41 [d59175000] exiting daemon
19:46:41 [d59175000] waiting for daemon to start
19:46:41 [d59175000] daemon started
19:46:41 docker_cli_network_unix_test.go:1016:
19:46:41     c.Assert(err, checker.IsNil)
19:46:41 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc20d08e8a0)} ("exit status 1")
19:46:41 
19:46:41 [d59175000] exiting daemon
19:46:43 
```

**Comment by vieux** [comment]
@thaJeztah unrelated I believe

**Comment by thaJeztah** [comment]
@vieux oh, actually wanted to add that (I was copying the error in case it's flaky)

@nishanttotla was working on documentation, so it'll rebuild after those changes are pushed

**Comment by nishanttotla** [comment]
Updated API documentation for the new field.

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by SvenDowideit** [comment]
yup, docs LGTM to me

**Comment by vdemeester** [comment]
LGTM 🐮

**Pull request merged**
