### PR TITLE
install: use XFS for devmapper on CentOS/RHEL/Fedora

### LINKED ISSUE #17464: 1.9rc3 daemon cannot start on fresh RHEL7.1 vm in AWS
```
[ec2-user@ip-172-31-28-106 ~]$ sh
sh-4.2$ curl -sSL test.docker.com | sh
+ sudo -E sh -c 'sleep 3; yum -y -q install docker-engine'
warning: /var/cache/yum/x86_64/7Server/docker-testing-repo/packages/docker-engine-selinux-1.9.0-0.3.rc3.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.9.0-0.3.rc3.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ec2-user

Remember that you will have to log out and back in for this to take effect!

sh-4.2$ docker version
Client:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:42:24 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
sh-4.2$ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
sh-4.2$ sudo /bin/systemctl start docker.service
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
sh-4.2$ sudo systemctl status docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled)
   Active: failed (Result: timeout) since Wed 2015-10-28 19:43:49 EDT; 1min 35s ago
     Docs: https://docs.docker.com
 Main PID: 10811

Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal docker[10811]: time="2015-10-28T19:42:17.912940792-04:00" level=info msg="API listen on /var/run/docker.sock"
Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal docker[10811]: time="2015-10-28T19:42:17.997419286-04:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to r...hinpooldev section."
Oct 28 19:43:47 ip-172-31-28-106.us-west-2.compute.internal systemd[1]: docker.service operation timed out. Terminating.
Oct 28 19:43:49 ip-172-31-28-106.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Oct 28 19:43:49 ip-172-31-28-106.us-west-2.compute.internal systemd[1]: Unit docker.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
sh-4.2$ sudo journalctl -xn
-- Logs begin at Wed 2015-10-28 19:34:55 EDT, end at Wed 2015-10-28 19:45:38 EDT. --
Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal docker[10811]: time="2015-10-28T19:42:17.912940792-04:00" level=info msg="API listen on /var/run/docker.sock"
Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal kernel: device-mapper: uevent: version 1.0.3
Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal kernel: device-mapper: ioctl: 4.29.0-ioctl (2014-10-28) initialised: dm-devel@redhat.com
Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal kernel: loop: module loaded
Oct 28 19:42:17 ip-172-31-28-106.us-west-2.compute.internal docker[10811]: time="2015-10-28T19:42:17.997419286-04:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev
Oct 28 19:43:47 ip-172-31-28-106.us-west-2.compute.internal systemd[1]: docker.service operation timed out. Terminating.
Oct 28 19:43:49 ip-172-31-28-106.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Oct 28 19:43:49 ip-172-31-28-106.us-west-2.compute.internal systemd[1]: Unit docker.service entered failed state.
Oct 28 19:45:24 ip-172-31-28-106.us-west-2.compute.internal sudo[10860]: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/systemctl status docker.service
Oct 28 19:45:38 ip-172-31-28-106.us-west-2.compute.internal sudo[10863]: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/journalctl -xn
sh-4.2$ uname -a
Linux ip-172-31-28-106.us-west-2.compute.internal 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux
sh-4.2$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

Fixes #17464

Ping @jfrazelle @tianon @rhvgoyal

### CODE REVIEW

**Comment by jfrazelle** [comment]
nice you used a drop in!, i mean it fixes the issue but we should hold on to our butts ;)
LGTM but tianon may know a better way

**Comment by rhvgoyal** [comment]
So with this change previously we were defaulting to devicemapper and ext4 on fedora/centos/rhel and now we will default to devicemapper and xfs? If yes, sounds good.

**Comment by tiborvass** [comment]
@rhvgoyal for people installing with our script from `https://get.docker.com/` (the file I modified is what will be uploaded at that address). However, if you manually run the docker daemon, it will still use ext4. Didn't want to make drastic changes right now for 1.9.

**Comment by rhvgoyal** [comment]
@tiborvass I understand the install.sh part. So changes will not affect all configurations instead will be limited to a subset.

**Comment by tiborvass** [comment]
@rhvgoyal correct, only on CentOS/RHEL/Fedora.

**Comment by tiborvass** [comment]
@rhvgoyal if you think there's a better fix we can discuss something for a subsequent release.

**Comment by rhvgoyal** [comment]
@tiborvass I can think of either defaulting to xfs or getting rid of ext4 special mkfs options. I think this is not limited to fedora/centos/rhel only. Any other distribution if they try to use devicemapper graph driver, should run into this on AWS or a slower storage.

**Comment by tiborvass** [comment]
@jfrazelle @tianon actually this is probably a very bad script, it will overwrite whatever the user has.

**Comment by tianon** [comment]
Yeah, this is a really dangerous way to solve the issue.  I'm not sure I understand completely why we need to modify this value just in this one case and not for the whole daemon?  If we're running into an issue on those platforms, wouldn't it follow that we either are or will soon run into the same issue on others?

**Comment by tiborvass** [comment]
@tianon @rhvgoyal on a second thought, since the default loopback device is discouraged anyways, I don't mind changing anything in docker that makes the first install experience a better one. So I'm open to changing the default to `xfs` in docker, or removing the `lazy_itable_init=0` and `lazy_journal_init=0` options for `ext4`.

**Pull request closed without merging**
