### PR TITLE
Add more russian scientists in names-generator.go

### PR DESCRIPTION
**Pull request by asmfreak**
**- What I did**
Add some notable russian scientists to names-generator.go

**- How I did it**
Edit names-generator.go on github

**- Description for the changelog**
Added some notable russian scientists to names-generator.go

**- A picture of a cute animal (not mandatory but encouraged)**
kitteh

Any additions are welcome.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Please add females as well?

**Comment by kolyshkin** [comment]
I can suggest
* https://en.wikipedia.org/wiki/Tatiana_Proskouriakoff (I'd suggest traditional Russian spelling, Proskuriakova)
* https://en.wikipedia.org/wiki/Lina_Stern

**Comment by kolyshkin** [comment]
@ASMfreaK can you please squash these two commits into one? Also, second commit has some whitespace changes which need to be removed.

**Comment by ASMfreaK** [comment]
Is this sufficient?

**Comment by kolyshkin** [comment]
LGTM (not a maintainer)

**Review by vdemeester — APPROVED** [review]
LGTM 🇷🇺

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
