### PR TITLE
fix runtime issue for TestEventsFilterContainer

### PR DESCRIPTION
**Pull request by LK4D4**
It is totally fixes race with losing last event.
Closes #12707

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @duglin @cpuguy83

**Comment by duglin** [comment]
LGTM assuming janky is happy

**Comment by duglin** [comment]
Almost to the point where we need another util func to do 'docker run' and return the out, err and ID

**Comment by cpuguy83** [comment]
@duglin Thinking the same thing... and people don't need to name their containers that way.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
