### PR TITLE
Move api handlers to separate file

### PR DESCRIPTION
**Pull request by cpuguy83**
Cleans up server.go so it pretty much just has the setup stuff.

### CODE REVIEW

**Comment by runcom** [comment]
+1 (this needs rebase unluckly)

**Comment by cpuguy83** [comment]
rebased

**Comment by calavera** [comment]
I wonder if it makes more sense to divide the handlers in specific files, like we've done with the client.

**Comment by cpuguy83** [comment]
I've thought about it... at least something like `containers.go`, `images.go`, `exec.go`

**Comment by icecrime** [comment]
I'm +1 for "domain" split, this file is way to huge ;-)

**Comment by tiborvass** [comment]
@cpuguy83 any update on this? I think it's welcome but I agree with others it needs to be split like the client is.

**Comment by cpuguy83** [comment]
By "domain" to me is different than by action like the cli is today.
I guess if we just clarify which way to go I can get this going.

**Comment by thaJeztah** [comment]
Splitting by domain sounds like a good start, but I'm not really the "coding guy" here, so just my 0.02 ;-)

**Comment by tiborvass** [comment]
@cpuguy83 +1 on domain, rebase please :)

**Comment by cpuguy83** [comment]
Updated

**Comment by calavera** [comment]
cool. I like it much much better :fireworks: LGTM.

**Comment by thaJeztah** [comment]
Nice! LGTM (fwiw)

**Comment by calavera** [comment]
it needs a rebase. Let's try to merge this as soon as janky is happy.

**Comment by cpuguy83** [comment]
Rebased again

**Comment by thaJeztah** [comment]
@cpuguy83 I tentatively moved this to "ready to merge", Following the above discussion, I think that's correct here? Or do you want another final LGTM check before merging?

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
