### PR TITLE
revendor engine-api

### PR DESCRIPTION
**Pull request by cpuguy83**
Revendoring engine-api separate of any PR because changes required just to make docker compile are too numerous for other PR's to have to implement.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Found more issues with engine-api swallowing errors after a recent change, breaking some tests here: fixed in docker/engine-api#366

**Comment by LK4D4** [comment]
@cpuguy83 merged!

**Comment by cpuguy83** [comment]
And docker-py tests...
ping @shin-

**Comment by cpuguy83** [comment]
This was removed from the API, but maybe needs to be added for older API versions?

`EXEC_DRIVER = c.info()['ExecutionDriver']`

**Comment by cpuguy83** [comment]
Opened docker/docker-py#1162 to address calls to `ExecutionDriver` from the `docker info` output in docker-py tests.
Also added a temporary wrapper around the info struct for older API versions.

**Comment by cpuguy83** [comment]
Ok, this is updated with the new docker-py bump, looks like all issues are resolved.

**Comment by LK4D4** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 👼

**Pull request merged**
