### PR TITLE
Fix signal forwarding issue

### PR DESCRIPTION
**Pull request by creack**
The issue is that we can't kill pid 1. By default, now dockerinit forkexec instead of exec. Resulting in the process started to be pid 2.

The previous behavior is still available via the '-fork' option of `docker run`.

Note that disabling fork will result in uninterruptible process.

I also noticed that this PR make some races within the test more obvious. I'll work on it, but it is a separate issue.

### CODE REVIEW

**Comment by anacrolix** [comment]
Why is this closed? It doesn't appear to be fixed.

**Comment by phemmer** [comment]
@anacrolix This is a pull request. Issues are tracked separately. See #3793

**Comment by rafaelcapucho** [comment]
why this PR is not accepted yet? we need a definitive way to solve it

https://issues.apache.org/jira/browse/MESOS-3829

**Comment by giuffresoft79** [comment]
Hello, i have this problem with SIGTERM....

**Comment by cpuguy83** [comment]
If you're apps aren't receiving signals, it's probably because the app has been inited improperly OR it drops default signal handlers when run as PID 1.

**Comment by DJviolin** [comment]
My solution for the PID1 problem:

```
#!/bin/bash

docker run --rm -it -p 8083:80 -v $HOME/node/work/:/root/node/:rw node_node "echo pid1 > /dev/null && node $@"
```

Here is my Dockerised Node.js development environment: https://github.com/DJviolin/Node.js-Development-Environment

**Comment by tobilg** [comment]
@rafaelcapucho This problem still seems to exist in current Mesos versions, together with Docker 1.8 IMHO...

Is there any suggested fix/workaround?

**Pull request closed without merging**
