### PR TITLE
Updates to macvlan/ipvlan experimental docs

### PR DESCRIPTION
**Pull request by nerdalert**
- Added a few more diagrams.
- Fixed typos and a few additional  details.

Signed-off-by: Brent Salisbury brent@docker.com

### CODE REVIEW

**Comment by mavenugo** [comment]
LGTM. thanks @nerdalert

**Comment by thaJeztah** [comment]
Thanks @nerdalert LGTM; can you rebase, because there's merge conflicts

**Comment by nerdalert** [comment]
@thaJeztah done thanks!

**Comment by thaJeztah** [comment]
thanks! LGTM

**Comment by thaJeztah** [comment]
ping @vdemeester for review/merge

**Comment by thaJeztah** [comment]
let me merge, taking @mavenugo's LGTM into account; these are experimental docs, so will be revisited once this leaves experimental

**Pull request merged**
