### PR TITLE
Check drivers before vol create

### PR DESCRIPTION
**Pull request by cpuguy83**
Probe all drivers if volume driver not specified

This fixes an issue where `docker run -v foo:/bar --volume-driver
<remote driver>` -> daemon restart -> `docker run -v foo:/bar` would make a `local` volume after the restart instead of using the existing volume from the remote driver.

Also removes back-compat hacks from for volume plugins.
Hacks were added as interim support for 1.10 but should not be needed for 1.11.

Addresses 1 and 2 from #20176

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
And just realized I didn't push  a test with this, updated with the test.

**Comment by calavera** [comment]
Awesome :metal:

**Comment by clintonskitson** [comment]
This tests good for me @cpuguy83.  Well done!

**Comment by shishir-a412ed** [comment]
@cpuguy83 
1) docker run -v foo:/bar --volume-driver <remote driver>
2) docker daemon restart
3) docker run -v foo:/bar 

In step 3, after the daemon restart, Do I need to pass `--volume-driver` again ? or with your fix it would automatically pick up `remote driver` volume `foo` and not create a `local` volume ?

PS: asking because in your description you did not mention `--volume-driver` after daemon restart.

**Comment by cpuguy83** [comment]
@shishir-a412ed The description isn't 100% correct. The container in step 1 would need to be removed

See the test I added.
But yes, the idea is you shouldn't have to specify a volume driver in step 3 since we never removed the volume.

**Comment by clintonskitson** [comment]
@cpuguy83 I believe the the precise way of saying that would be because we never removed the container.  I believe a volume that is not being used will not persist across docker restarts.

**Comment by cpuguy83** [comment]
@clintonskitson If the container is not removed, then this is not a problem since the container's volumes will be registered with the correct driver.

**Comment by shishir-a412ed** [comment]
@cpuguy83 I see. Thanks for the clarification.

**Comment by clintonskitson** [comment]
Yup crossing theads here, my fault.  https://github.com/docker/docker/issues/20176 issue #3 refers to making it deterministic and valid in both cases all the time.

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
