### PR TITLE
Move errors package to api/errors

### PR DESCRIPTION
**Pull request by dnephin**
Every time I see this package I don't expect it to be api errors. Moving it to the `api/errors` package should make this more obvious.

```
gomvpkg \
    -from github.com/docker/docker/errors \
    -to github.com/docker/docker/api/errors \
    -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
```

### CODE REVIEW

**Comment by cpuguy83** [comment]
Really not even an api error, these are http layer errors.
Ideally we'd define a set of API errors... like `object not found`, and have the HTTP layer know "ok, that needs to be a 404 error"

**Comment by dnephin** [comment]
True, that's basically what this is trying to do, but the naming could be a lot better.

It would be really great if we could enforce a specific error type, then we could remove [this hack](https://github.com/docker/docker/blob/c2ec7454900b62122f97911740b789d73e6a53c7/api/server/httputils/errors.go#L47-L69)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Pull request merged**
