### PR TITLE
Random additions

### PR DESCRIPTION
**Pull request by JamesKyburz**
Additions to the random name generator.

### CODE REVIEW

**Comment by unclejack** [comment]
Please make the changes as the bot has commented above and also squash the two commits into a single one.

**Comment by JamesKyburz** [comment]
okidoki

James Kyburz
Cell: +46 734 448489 | Google Talk: james.kyburz | Skype: james.kyburz
http://twitter.com/jameskyburz

**Comment by JamesKyburz** [comment]
Made the changes.

**Comment by unclejack** [comment]
@JamesKyburz Thank you, both for making the changes and for the PR.

LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
