### PR TITLE
revendor swarmkit to 53fcdeba083627b1a2616612a103019b73c6d5ce

### PR DESCRIPTION
**Pull request by aluzzardi**
/cc @cyli @diogomonica @vieux

### CODE REVIEW

**Comment by thaJeztah** [comment]
@aluzzardi this is the counterpart to https://github.com/docker/docker/pull/28729 (which is for 1.13) right? Guess we should change the milestone to 1.14 for this one of that's correct

**Comment by vieux** [comment]
yes my bad

**Comment by aluzzardi** [comment]
Rebased

**Review by justincormack — APPROVED** [review]

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
