### PR TITLE
Remove cgroup read-only flag when privileged

### LINKED ISSUE #14543: Can no longer run DinD - Error starting daemon: error initializing graphdriver
I see the following error trying to start docker inside docker
FATA[0000] Error starting daemon: error initializing graphdriver: Error found less than 3 fields post '-' in "193 192 0:54 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs  rw"

$ docker version
```
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   b7e8169
 Built:        Fri Jul 10 21:20:22 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   b7e8169
 Built:        Fri Jul 10 21:20:22 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

cgroups outside:
```
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,clone_children)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
```

cgroups inside:
```
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,relatime,cpuset,clone_children)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,relatime,memory)
cgroup on /sys/fs/cgroup/name=systemd type cgroup (ro,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,relatime,perf_event)
```

### PR DESCRIPTION
**Pull request by hqhq**
Fixes: #14543

It needs libcontainer fix from:
https://github.com/opencontainers/runc/pull/91

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
oh this is the fix i need thanks

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
Btw, we found severe bug in libcontainer, which prevents mounting `/sys/fs/cgroup` with proper flags to container. And that's what you saw @jfrazelle

**Comment by jfrazelle** [comment]
im glad im not goinng crazy haha

**Comment by hqhq** [comment]
Now we have the real fix from https://github.com/opencontainers/runc/pull/127, I'm not sure if we still need this, but @mrunalp did mention we have use cases need cgroup to be writable, and I think enable it in privileged model seems still controllable.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
