### PR TITLE
Revert libnetwork

### PR DESCRIPTION
**Pull request by jessfraz**
:(

### CODE REVIEW

**Comment by jfrazelle** [comment]
This is only if a solution is not found soon for the kernel lock ups on 3.18/3.19

**Comment by vdemeester** [comment]
This is linked to #13498 (just to link the PR to the issue :wink: ).

**Comment by jfrazelle** [comment]
closing becase @mrjana is amazing :)

**Comment by mavenugo** [comment]
> closing becase @mrjana is amazing :)

+1 to that :)

**Comment by thaJeztah** [comment]
it has been resolved? \o/

**Pull request closed without merging**
