### PR TITLE
Removing dependencies from pkg into Docker internal code

### LINKED ISSUE #10922: autogen + go get?
for better or worse there are some projects out there that are linking to Docker packages, including term, stdcopy, archive, parsers, etc. Here is an example:
https://github.com/samalba/dockerclient/blob/master/dockerclient_test.go

By excluding the autogen folder from the repository it is no longer go gettable:

```
../../docker/docker/utils/utils.go:24:2: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/src/go/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
Makefile:26: recipe for target 'build' failed
```

### PR DESCRIPTION
**Pull request by brahmaroutu**
Closes #10922
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

@brahmaroutu Thanks for working on this!

**Comment by crosbymichael** [comment]
If you have time a rebase is needed, if not one, of use can rebase this before it's merged.

**Comment by brahmaroutu** [comment]
@crosbymichael I rebased the code now.

**Comment by crosbymichael** [comment]
ping @jfrazelle @tiborvass

**Comment by jfrazelle** [comment]
kewl lgtm

**Pull request merged**
