### PR TITLE
Windows: CLI Improvement (TP3)

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

@swernli @brendandixon @ahmetalpbalkan @jstarks @tiborvass @icecrime 

The Ansi parser and their associated actions have been decoupled. Now
parsing results in call backs to an interface which performs the
appropriate actions depending on the environment.

This improvement provides a functional Vi experience and the vttest no
longer panics.

This PR replaces the stale docker/docker #13224.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
This PR is needed for the TP3 build for correct ANSI support in Windows containers. But also improves the Linux experience significantly.

**Comment by thaJeztah** [comment]
@jhowardmsft just for my info; is TP3 to be presented at the same time as Docker 1.8? Wondering if these should be marked somehow to make sure they get in in time (if it's any of "our" worries here :wink:)

**Comment by jhowardmsft** [comment]
The current plan is that the docker daemon Windows release to support TP3 will be in 1.9.0-dev. I though we were supposed to have snapped to 1.8 earlier this week and the version bumped. I haven't seen that happen though? Certainly though, there are a few PRs which are still needed to support TP3, but we're very close now :)

**Comment by thaJeztah** [comment]
With the version bump, you mean the version bump here? https://github.com/docker/docker/blob/master/VERSION (it's 1.8-dev now)

**Comment by jhowardmsft** [comment]
Yup, that's the one.

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
merging, its a big one but if anything goes wrong we know where to find you ;)

**Comment by thaJeztah** [comment]
> if anything goes wrong we know where to find you ;)

Yup. on Bing searching for Nyancats 😉🐱🐱

**Pull request merged**
