### PR TITLE
IPv6 iptables config option

### LINKED ISSUE #21614: do not expose ports over IPv6 unless published
Currently with IPv6 in practice port publishing is no-op. With IPv6 it is expected that a container that is exposed to outside world should have globally routable IPv6 address so all its ports are exposed.

This is bad from a security point of view as it makes very easy to accidentally expose a port that should only be open to members of a docker network. Case in point is a password-less database container that is a part of an application that is exposed over IPv6 to Internet. With typical images unless one is careful such DB container can also be exposed to the internet over IPv6.

It would be nice if docker provide a setting so only ports that are explicitly exposed on the command line will be reachable over IPv6 from outside a docker network. Other ports should be blocked by a firewall rule.

### LINKED ISSUE #25407: Please implement IPv6 NAT as an available alternative option when using docker with IPv6 enabled
Docker's current IPv6 behavior currently still has the following outstanding problems:
- it lacks -p/--publish and EXPOSE functionality similar to IPv4 (with non-EXPOSE'd ports being hidden, and -p/--publish only using the userland proxy which changes the source IP address to the userland proxy container which makes it near-useless for not all but some protocols because of security reasons - e.g. HTTP can deal with this with proxy headers, but other TCP-based protocols can't). This is a huge pitfall for many users of smaller servers who don't set up manual iptable rules but rely on docker to work as they have grown to expect it out of the box
- it always requires setting up an entire IPv6 prefix which _should_ always be available in theory, but in certain home networks it requires changing the router configuration to be able to trivially use a larger IPv6 prefix range from a single machine, and multiple lan / wlan interfaces on a laptop can make this task more complicated as well

Due to those and other reasons, it would be very nice if IPv6 NAT was added as han _option_ (**not** a full replacement for the current IPv6 default behavior) which could be enabled by the user if desired, to perfectly copy the current IPv4 NAT behavior and resolve all of the things listed above and provide an easy to use standard behavior that "just works".

Please note I agree NAT for IPv6 is often a terrible idea in a larger datacenter where you write custom routing and address assignments anyway - which is why NAT should be an option, not a replacement for the current behavior -, but for small servers and laptops where people just want a working default solution, it would be a big improvement.

There is a temporary implementation available from @robbertkl as a privileged container that modifies the iptables rules on the host with automated container discovery using dockergen: https://github.com/robbertkl/docker-ipv6nat . However, it would be neat if this functionality was integrated into docker itself like IPv4 NAT.

(I created this ticket out of a discussion in ticket #13481 where you can read up more details on the previous discussion)

### PR DESCRIPTION
**Pull request by bboehmke**
~~**Note: This requires pull request moby/moby#41604 to be merged first**~~ (already merged)

**- What I did**
Added an config option to enable the IPv6 iptables rule creation based on moby/libnetwork#2572.

This should close #25407.
fixes https://github.com/moby/moby/issues/21614

**- How I did it**
Add a config option `ip6tables` (like `iptables` for IPv4) which can be used to enable the IPv6 iptables rule creation.
By default this option is disabled too keep backward compatibility.

**- How to verify it**
To enable this functionality it is required to enable ipv6, set a fixed cidr and enable the ip6itpables.

This can be done for example via CLI parameters on the daemon:
```
dockerd --ipv6 --fixed-cidr-v6 fd00:dead:beef::/48 --ip6tables
```
or by setting the configurations inside the `daemon.json`.

Now a container can be started and if a port is published the IPv6 NAT iptables rules are also created.

**- Description for the changelog**

`--ip6tables` enables IPv6 iptables rules (only if experimental)

### CODE REVIEW

**Comment by bboehmke** [comment]
@arkodg @thaJeztah PTAL

Also I am not sure if there is also changes for the documentation needed.

**Comment by arkodg** [comment]
I see a `make swagger-docs` that might be needed to generate docs

**Comment by bboehmke** [comment]
The swagger part seems to be more for the API of the docker daemon which should not be changed here.

The the documentation that maybe have to be updated are this 2 sections in the docker daemon documentation:
 * https://docs.docker.com/engine/reference/commandline/dockerd/#daemon
 * https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

If you can give me a hint how this is updated I can also add a change for this.

**Comment by arkodg** [comment]
ah good point
there a `Request doc changes` link to the right
 https://github.com/docker/docker.github.io/issues/new?body=File:%20[engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)
this flag would need to get consumed by `libnetwork` which would then need to get vendored in and that version would need to get released in the `docker-ce` package, before the doc changes go live

**Review by arkodg — APPROVED** [review]

**Comment by arkodg** [comment]
ptal @tiborvass @thaJeztah

**Comment by bboehmke** [comment]
@arkodg I directly created a PR for the documentation change -> docker/cli#2846

I hope this is enough (and it was the right position for the change).

**Comment by arkodg** [comment]
yah that should be good enough imo, thanks for the proactive change

**Comment by thaJeztah** [comment]
@arkodg does this feature require additional dependencies to be defined in the packages, or can we assume that if iptables is present, ip6tables is as well?

Also; does the `check-config.sh` need additional checks for troubleshooting? https://github.com/moby/moby/blob/master/contrib/check-config.sh#L191-L197

**Comment by bboehmke** [comment]
I did a quick check for some linux distributions.

ip6tables **included** in iptables package for the following:
 * [debian](https://packages.debian.org/buster/iptables)
 * [ubuntu](https://packages.ubuntu.com/bionic/iptables)
 * [arch linux](https://www.archlinux.org/packages/core/x86_64/iptables/)

ip6tables **NOT** included in iptables package for the following:
 * alpine linux: [ip6tables](https://pkgs.alpinelinux.org/package/edge/main/x86_64/ip6tables) & [iptables](https://pkgs.alpinelinux.org/package/edge/main/x86_64/iptables)

I hope this is useful

**Comment by thaJeztah** [comment]
Thanks for checking!

Discussing this in the maintainers meeting, and we're considering to mark the feature as "experimental" for the initial implementation, as it didn't have testing yet, so there could still be issues with it.

**Comment by ell1e** [comment]
Will it be possible to specify a single IPv6 address for `--fixed-cidr-v6` if `--ip6tables` is enabled? (Or alternatively can be `--fixed-cidr-v6` omitted entirely in that case?) Sorry if this is nonsense, but in my head it feels like that should be possible to allow IPv6 NAT operation behind a single predetermined public ip similar to IPv4 NAT which wasn't possible before, but which I would at least *expect* to work now

**Comment by tianon** [comment]
Very interesting idea, @ell1e -- are you thinking the containers would just have use link-local IPs instead?

(I'm just clarifying the idea, the question itself is likely better for libnetwork maintainers as to whether it's possible :sweat_smile:)

**Comment by ell1e** [comment]
Yes, in fact I would have assumed that would be naturally the case with `--ip6tables` (since otherwise what is the point of the NAT if the containers are still publicly reachable through other routes?)

**Comment by bboehmke** [comment]
@ell1e I currently only tested with a single public IPv6 by setting the `fixed-cidr-v6`to the private subnet `fd00:dead:beef::/48`.
This should then work exactly like the IPv4 NAT.

The only thing is that it is currently required to define a fixed-cidr-v6 otherwise it will not work (because there is no default subnet specified).

**Comment by ell1e** [comment]
Ok, so wouldn't it make sense if ommitting `--fixed-cidr-v6` made it default to a private subnet automatically if `--ip6tables` is specified? To mirror the IPv4 NAT default behavior.

**Comment by arkodg** [comment]
yah in the future we could possible use a subnet within `fd00::/8` as a default Ipv6 network which eliminates the need to explicitly add `--fixed-cidr-v6`

**Comment by ell1e** [comment]
I wonder, maybe it might even be worth having docker print a warning if a non-private v6 subnet is specified in combination with the NAT6....? In case some folks migrate their old config with `--fixed-cidr-v6` set to a public range by just *adding* the NAT6 option without realizing that will kind of circumvent the NAT in a way. I think there is some great value in being able to omit this option from the start, so users are conceptually trained to let go of their old configs and do it right.

**Comment by arkodg** [comment]
just realized that we have some iptables related integration tests here
https://github.com/moby/moby/blob/6c0a036dce2051cc0d73221965e76e3d2e6a8a3a/integration/network/network_test.go#L96
could you maybe add one more (with this dockerd setting enabled) to give the feature more life :)

**Comment by arkodg** [comment]
@bboehmke spoke to @thaJeztah and looks like this flag/feature will need to be marked as experimental for the 20.10 release
probably need to add a 
```
if conf.BridgeConfig.EnableIP6Tables && !daemon.HasExperimental() {
    error out
}
```
in

https://github.com/moby/moby/blob/ca520bd1b807ace7c041bf416cb1bba385d968e5/daemon/daemon_unix.go#L738

**Comment by bboehmke** [comment]
I have used `conf.Experimental` directly instead of `daemon.HasExperimental()` because there is no `daemon` in this function.

Is cd63cc8 enough?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tiborvass — DISMISSED** [review]

**Comment by arkodg** [comment]
thanks @bboehmke 
another followup PR is needed (happy to raise one) to make sure `--ipv6` as well as  `--fixed-cidr-v6` are set as well when setting `--ip6tables` and bail out early if that's not the case

**Comment by tiborvass** [comment]
@arkodg agreed, if you send me a commit I can add it to this PR.

**Comment by arkodg** [comment]
sure here's the commit https://github.com/arkodg/moby/commit/0aa488f38241693d365b78095a462310cbda0f9c

**Comment by tiborvass** [comment]
@arkodg @thaJeztah updated with the commit that ensures --ipv6 and --fixed-cidr-v6 are specified when using --ip6tables

**Review by tiborvass — APPROVED** [review]

**Comment by bboehmke** [comment]
Is it really required to have ipv6 and fixed-cidr in daemon level?

I have not tested it but it should also be possible to have only ipv4 in the daemon and then use a ipv6 enabled Network. In this case this validation is maybe to much.

What do you think?

**Comment by arkodg** [comment]
not adding it means, it won't be enabled on the `default` bridge/network.
im okay either way, would like to see this PR merged soon

**Comment by bboehmke** [comment]
I think the big question here is do we want to force the user to configure the default network to use this feature?

Currently it is already possible to have ipv6 only in a custom network without enabling it on the default one.

**Comment by tiborvass** [comment]
Per the comments above, I removed c2b421e072586bfd9be64cf8fa2b17718d9686ed

**Review by tianon — APPROVED** [review]
LGTM

**Comment by ell1e** [comment]
I think it would be better to require an option to not by default implicity set `--ipv6` and `--fixed-cidr-v6`  (the latter defaulting to a private range then) when just putting `--ip6tables`. I don't think it's a good user experience, or covers the what I assume is the **common** use case which is to just mirror how the IPv4 setup works.

While I understand from the above comments there are other uses, I don't think that should be the default experience when putting `--ip6tables`. Rather, I think it would make more sense to require those to use `--fixed-cidr-v6` with something else manually then, and to have something like `--no-ipv6` in addition.

Otherwise, the options are just going to be an even more wild unusable mess than they already are now IMHO. I mean, sure documentation can help and it's great the feature is now there at all, but I think if you're not optimizing the options for the likely most common use then you're setting yourself up for confused tickets for years (since now is probably the latest moment in time where this can still be changed without messing up everyone's launch options in real deployments later).

**Comment by tomalok** [comment]
Let's not over-complicate things if possible.

What's the current state of things?  As I understand it, those who want to use IPv6 must use *both* `--ipv6` and `--fixed-cidr-v6` in order for it to work?

If that's true (and I am by no means an expert), then to use IPv6 without any specified CIDR I would expect `--ipv6` to be sufficient.  It should pick a suitable non-routable IPv6 block, and do NAT with `ip6tables` just like how IPv4 works today.

To use a specific IPv6 CIDR, use of `--fixed-cidr-v6` could also imply `--ipv6` but not error out if `--ipv6` is also specified.  No `ip6tables` would be managed/manipulated, in line with what (i think) is the current behavior.

If someone wants to specify their own IPv6 CIDR *and* do NAT, then there should be some new way to explicitly turn it on, like `--ipv6-nat` would be specified alongside the `--fixed-cidr-v6`.

It would be okay to specify `--ipv6-nat` with `--ipv6` -- since that's the default behavior without the `--fixed-cidr-v6`.

Summarized, I think this is simplest...
* `--ipv6 [--ipv6-nat]` - turn on IPv6 support, default non-routable IPv6 CIDR, use `ip6tables`
* `[--ipv6] --fixed-cidr-v6 <cidr>` - turn on IPv6 support, using specified IPv6 CIDR, do **not** use NAT/`ip6tables`
* `[--ipv6] --fixed-cidr-v6 <cidr> --ip6-nat` - turn on IPv6 support, use specified IPv6 CIDR, use NAT/`ip6tables`

**Comment by tianon** [comment]
I agree there's a ton of room for improvement/adjustment in Docker's IPv6 support (and I want to see it!), but this PR is just adding a flag to enable one bit of optional new behavior that wasn't previously available, so I don't think it makes sense to make any drastic changes in this context (and is why I've added my own "LGTM" to this PR, especially with the new flag under experimental).

I think the overall experience improvement discussion should probably move to a separate issue(/PR).

**Comment by ell1e** [comment]
> Summarized, I think this is simplest...
>
>    --ipv6 [--ipv6-nat] - turn on IPv6 support, default non-routable IPv6 CIDR, use NAT/ip6tables
>    [--ipv6] --fixed-cidr-v6 <cidr> - turn on IPv6 support, using specified IPv6 CIDR, do not use NAT/ip6tables
>    [--ipv6] --fixed-cidr-v6 <cidr> --ip6-nat - turn on IPv6 support, use specified IPv6 CIDR, use NAT/ip6tables

I like this idea. While I think the options I suggested conceptually make slightly more sense, this one is very practical to add in without breaking old configs while addressing my main concern (which is that `--ipv6` should be transitioned to something where it "just works" like IPv4, which is what people usually expect).

@tianon is it common to rename options around again of experimental stuff, though? There might be some merit to get it right the first time, maybe. (I'm not familiar enough with how docker is commonly maintained here.) But I'd be happy to put it into a separate issue, I'm just wondering if that means it won't be addressed for another ten years because then many are already used to the "weird" options.

**Comment by bboehmke** [comment]
There are currently two options to use ipv6:

1. via default bridge via `--ipv6` and `--fixed-cidr-v6`
2. via user defined network created with `--ipv6`

Based on this it is possible to enable ipv6 only for specific networks without enabling it for the default bridge.

The `--ip6tables` would only enable the ip6tables NAT rule creation but only for ipv6 enabled networks.
Because the change ip6tables is working like the iptables (ipv4) it is not possible to enable it only for a single network (like `--iptables`)

Maybe this can be changed in the future but I have no idea if this is possible at all.

In my opinion the `--ip6tables` enables only the iptables rule creation for IPv6 enabled networks without requiring a configured network at startup.

**Comment by ell1e** [comment]
> In my opinion the --ip6tables enables only the iptables rule creation for IPv6 enabled networks without requiring a configured network at startup.

Interesting, is there a specific reason why it needs to be like that? Ideally I think the most useful way for this new thing to work would be to have one easy option to enable it for everything, exactly like IPv4, including for the default bridge and other places. This would also work nicely with @tomalok 's option suggestion that promotes a single `--ipv6` with no extra option to do all this magic in the future.

**Comment by tianon** [comment]
> @tianon is it common to rename options around again of experimental stuff, though? There might be some merit to get it right the first time, maybe. (I'm not familiar enough with how docker is commonly maintained here.) But I'd be happy to put it into a separate issue, I'm just wondering if that means it won't be addressed for another ten years because then many are already used to the "weird" options.

Absolutely - the whole point of requiring "experimental" for flags is to let users test them early while they're still completely subject to change (or even removal).

**Comment by bboehmke** [comment]
@ell1e The current IPv6 implementation is currently build that way that if you set this option on the daemon only the default network will have IPv6 and the user created ones not (at least if not configured explicit on creation of the network).

In some setups (especially for the first steps with IPv6) it can be a good idea to do not change the default bridge but do first tests with a separate network with IPv6 enabled (this was the way I started with IPv6).

Maybe default values the IPv6 cidr would make the situation a bit easier but this is not present so far.

**Comment by tiborvass** [comment]
So are there any objections for merging this as-is?

**Comment by arkodg** [comment]
lets continue the discussions of default IPv6 flags in a separate PR / issue since reaching a consensus for it here is gating the IPv6 NAT feature
@tiborvass can we please merge this PR, so this feature (still experimental) can be released soon, thanks

**Review by thaJeztah — APPROVED** [review]
LGTM; let's merge this one

Could someone open a ticket to describe and track improvements that we want to make? I'm trying to follow the discussion, but perhaps someone could write up something 🤗

**Comment by ell1e** [comment]
@thaJeztah I made a ticket here, I hope that will be suitable: https://github.com/moby/moby/issues/41754

**Comment by thaJeztah** [comment]
Thanks!

**Comment by WallaceSUI** [comment]
Hey team,

Just wonder when (by date or by release) you plan to make this implementation as non-experimental (remove parameter "experimental")? 

Thanks a lot.

**Comment by akerouanton** [comment]
For the record, I answered @WallaceSUI question here: https://github.com/moby/moby/discussions/45384.

**Pull request merged**
