### PR TITLE
Bump go-connections for TLS 1.3 support 

### LINKED ISSUE #40495: [roadmap] Support TLS1.3
Tracking issue to track support for TLS1.3, now that Go supports it out of the box

related

- [x] https://github.com/docker/go-connections/pull/68 Add TLS 1.3 to list of TLS versions
- [x] review list of cyphers for TLS 1.3 (?)
- [ ] revendor go-connections https://github.com/moby/moby/pull/41042
- [ ] (tag, and) revendor docker/go-connections

### PR DESCRIPTION
**Pull request by thaJeztah**
~testing https://github.com/moby/moby/pull/41042 with API version negotiation enabled on the testutil client~

- fixes https://github.com/moby/moby/issues/40495
- carries https://github.com/moby/moby/pull/41042
- closes https://github.com/moby/moby/pull/41042
- closes https://github.com/moby/moby/pull/46739

### CODE REVIEW

**Comment by thaJeztah** [comment]
OK, so this "fixes" the failures, but it doesn't look right;


```

[2020-06-09T14:23:45.417Z] Running D:\gopath\src\github.com\docker\docker\integration\service
[2020-06-09T14:23:48.388Z] INFO: Windows Base image is  mcr.microsoft.com/windows/servercore:ltsc2019
[2020-06-09T14:23:48.388Z] INFO: Testing against a local daemon
[2020-06-09T14:23:48.388Z] ok  	github.com/docker/docker/integration/service	0.315s

...

[2020-06-09T14:23:48.388Z] === SKIP: github.com/docker/docker/integration/service TestCreateServiceCapabilities (0.00s)
[2020-06-09T14:23:48.388Z]     create_test.go:481: versions.LessThan(testEnv.DaemonAPIVersion(), "1.41"): setting service capabilities is unsupported before api v1.41
```

Why is the daemon it's testing against an older daemon? Is it testing against the pre-installed daemon on the host, instead of the one that was built (and should be used for tests)?

**Comment by thaJeztah** [comment]
Earlier, I see these debug lines;

```

[2020-06-09T14:15:29.442Z] INFO: go version go1.13.12 windows/amd64
[2020-06-09T14:15:29.442Z] INFO: Running the daemon under test in debug mode
[2020-06-09T14:15:29.442Z] INFO: Starting a daemon under test...
[2020-06-09T14:15:29.442Z] INFO: Args: -H tcp://0.0.0.0:2357 --data-root d:\CI\PR-41084\1\daemon --pidfile d:\CI\PR-41084\1\docker.pid -D
[2020-06-09T14:15:29.442Z] INFO: Process started successfully.
[2020-06-09T14:15:29.442Z] INFO: Start tailing logs of the daemon under tests
[2020-06-09T14:15:29.442Z] INFO: Waiting for the daemon under test to start...
[2020-06-09T14:15:32.417Z] INFO: Daemon under test started and replied!
[2020-06-09T14:15:32.417Z] INFO: Docker version of the daemon under test
[2020-06-09T14:15:32.417Z] 
[2020-06-09T14:15:32.417Z] Client:
[2020-06-09T14:15:32.417Z]  Version:      17.06.2-ce
[2020-06-09T14:15:32.417Z]  API version:  1.30
[2020-06-09T14:15:32.417Z]  Go version:   go1.8.3
[2020-06-09T14:15:32.417Z]  Git commit:   cec0b72
[2020-06-09T14:15:32.417Z]  Built:        Tue Sep  5 19:57:19 2017
[2020-06-09T14:15:32.417Z]  OS/Arch:      windows/amd64
[2020-06-09T14:15:32.417Z] 
[2020-06-09T14:15:32.417Z] Server:
[2020-06-09T14:15:32.417Z]  Version:      0.0.0-dev
[2020-06-09T14:15:32.417Z]  API version:  1.41 (minimum version 1.24)
[2020-06-09T14:15:32.417Z]  Go version:   go1.13.12
[2020-06-09T14:15:32.417Z]  Git commit:   896024cfc0
[2020-06-09T14:15:32.417Z]  Built:        06/09/2020 14:13:42
[2020-06-09T14:15:32.417Z]  OS/Arch:      windows/amd64
[2020-06-09T14:15:32.417Z]  Experimental: false
```

So it looks like either `DOCKER_HOST` should be set for these tests, or `-H tcp://0.0.0.0:2357` should be passed to the client

**Comment by thaJeztah** [comment]
So... these are only used in Windows.ps1? https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/hack/ci/windows.ps1#L591-L596


Further down, it's used to set `DOCKER_HOST` (in two places);

https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/hack/ci/windows.ps1#L883-L885

https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/hack/ci/windows.ps1#L924-L929

**Comment by thaJeztah** [comment]
So, testutil creates the client here; https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/testutil/environment/environment.go#L39

Which uses `FromEnv`; https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/client/options.go#L45-L49

Which uses `WithHost()`; https://github.com/moby/moby/blob/07e6b843594e061f82baa5fa23c2ff7d536c2a05/client/options.go#L89-L91

Which calls `sockets.ConfigureTransport(transport, c.proto, c.addr)`


I suspect this may be related https://github.com/docker/go-connections/commit/fb772cf57ab026bb75d4b3808e9b1761cd66e6c4#diff-998ed58b58f0b5f52161ef8e4e27692d

https://github.com/docker/go-connections/pull/61

@AkihiroSuda could you have a look?

**Comment by thaJeztah** [comment]
Reverting https://github.com/docker/go-connections/pull/61 and https://github.com/docker/go-connections/pull/58 resolves the problem on Windows, so we need to look at those

**Review by corhere — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
