### PR TITLE
Vendoring swarmkit @3f135f206179e

### PR DESCRIPTION
**Pull request by mrjana**
Adds support for `service update -p`

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

**Comment by mrjana** [comment]
ping @icecrime @mavenugo

**Comment by vieux** [comment]
SGTM ping @tonistiigi

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by aaronlehmann** [comment]
LGTM

janky failed to remove the container, after all tests passed. Merging.

**Pull request merged**
