### PR TITLE
Switch docker-py clone to use an explicit commit for natural cache-busting

### PR DESCRIPTION
**Pull request by tianon**
cc @jfrazelle

ref https://github.com/docker/docker/pull/10058#issuecomment-69797986

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
otherwise I was going to have to bust the cache on the half-dozen jenkins servers lol

**Comment by tianon** [comment]
Every time `docker build --no-cache` is necessary, a kitten dies.

**Comment by crosbymichael** [comment]
LGTM

**Comment by shin-** [comment]
sorry :3 I realized afterwards I should have made another tag. WIll know if there's a next time.

**Comment by tianon** [comment]
No worries, this'll let us more clearly update even without a new tag (so
we could take advantage of unreleased tests in master if we needed to / you
wanted us to).

**Pull request merged**
