### PR TITLE
Process isolation containers on Windows Client

### PR DESCRIPTION
**Pull request by kika123**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Process isolation containers work fine on Windows client these days. This PR enables them to be set as default.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
No. This is explicit licensing policy. Does NOT LGTM.

**Comment by kika123** [comment]
So why does it work officially on Hyper-V containers and via PowerShell containers then? (Windows 10 Enterprise N)

**Comment by jhowardmsft** [comment]
As per above this is not a technical debate - this is licensing. Closing.

**Comment by thaJeztah** [comment]
This has now been done in https://github.com/moby/moby/pull/38000

**Pull request closed without merging**
