### PR TITLE
We need to relabel newly created container volumes

### PR DESCRIPTION
**Pull request by rhatdan**
This will add a label to any volume that is shared into a container.

Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
@shishir-a412ed Could you try this out with docker-lvm-plugin.  Works for me.  :^)

**Comment by shishir-a412ed** [comment]
@dwalsh works fine for me. I did this:

```
1) docker volume create -d lvm --name selinux_labels --opt size=250M
2) docker volume ls (This should list the selinux_labels logical volume created by our plugin)
3) docker run -it -v selinux_lables:/run fedora /bin/bash
4) Inside the container shell: ls -lZ
```

drwxr-xr-x.   2 root root system_u:object_r:svirt_sandbox_file_t:s0              6 May 27 15:05 run

**Comment by crosbymichael** [comment]
@rhatdan i believe the test failures are real and related to this change.  It is the same tests on each of the checks that are failing.

**Comment by LK4D4** [comment]
ping @rhatdan

**Comment by rhatdan** [comment]
I had forgotten about this one, Updated to upstream and will take a fresh look at this.

**Comment by cpuguy83** [comment]
Since the dir is part of the container's rootfs, why wouldn't this already be labeled?

**Comment by crosbymichael** [comment]
LGTM

@cpuguy83 labels are applied per mountpoint

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
