### PR TITLE
Add IP_NF_MANGLE to check-config.sh

### LINKED ISSUE #46636: iptables (legacy) doesn't work with swarm published ports; iptables (nf_tables) is required
### Description

...that's `iptables` built with `--enable-nftables`.

I found this bug on [Lightwhale](https://lightwhale.asklandd.dk/), which is a custom Linux distro I'm building from scratch.  Now bare with me...!

This took some time to debug, because classic `docker run` and `docker compose` works, and so do most swarm features. But I specifically wanted to play with the [routing mesh](https://docs.docker.com/engine/swarm/ingress/) and that's when I discovered that I cannot connected from the host to a published port on the host (please see test case).

So I started comparing with a working, main stream Linux desktop.  I compared  `docker inspect this` and `than`.  Then I install the official [static binary](https://docs.docker.com/engine/install/binaries/) build of docker, and followed the [prerequisites](https://docs.docker.com/engine/install/binaries/#prerequisites) carefully, even ran the [check-config.sh](https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh) script, but it kept failing.  I finally found a difference in the output of `iptables-save` and eventually discovered that `iptables` isn't just `iptables`!

Apparently I needed to enable `--enable-nftables` flag when compiling `iptables`.

It would be helpful if...:
1. docker tested if the installed `iptables` that [it finds](https://github.com/moby/moby/blob/master/libnetwork/iptables/iptables.go#L111) is actually of the correct build. Maybe run `iptables --version` and expect  `"(nf_tables)"` as in e.g. `iptables v1.8.9 (nf_tables)`.
2. [check-config.sh](https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh) similarly tested for a working `iptables` command. 
3. `docker info` printed the path for `iptables` and output of `iptables --version` since it's obviously heavily depending on it, and for it to be in a supported version and build.
4. it was specifically stated in the docs, that `iptables (nf_tables)` is required, and not just "iptables version 1.4 or higher".  I already did file request for that change.

You won't find any hints in the `docker version` and `docker info` below. But I've added two session logs of a failing and successful test.  It includes output of `iptables --version` and `iptables-save`. 

### Reproduce

sudo iptables --version  # (legacy) or (nf_tables)
docker swarm init --default-addr-pool 10.22.0.0/16
docker service create --publish published=8088,target=80 --name=www nginx:1.25.2-alpine
curl 127.0.0.1:8088  # Connection refused or HTML
sudo iptables-save --version
sudo iptables-save  # (legacy) or (nf_tables)

### Expected behavior

iptables v1.8.9 (nf_tables)

curl to output response from nginx.

### docker version

```bash
Client:
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.10
 Git commit:        23.0.5
 Built:             unknown-buildtime
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.10
  Git commit:       buildroot
  Built:            
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        
 runc:
  Version:          1.1.7
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.15.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: tmpfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: N/A
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 6.1.32
 Operating System: Lightwhale 2.0.4
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.946GiB
 Name: lightwhale
 ID: e5308f03-9b08-4362-801d-ba768c7bbf8c
 Docker Root Dir: /mnt/lightwhale-data/docker
 Debug Mode: true
  File Descriptors: 22
  Goroutines: 39
  System Time: 2023-10-13T00:44:46.498736037+02:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Notice the difference in `iptables v1.8.9 (legacy)` and `iptables v1.8.9 (nf_tables)`, and also how the `iptables-save` output is reversed but also has other subtle, critical differences;

[test-fail.log](https://github.com/moby/moby/files/12887801/test-fail.log)
[test-success.log](https://github.com/moby/moby/files/12887802/test-success.log)

### PR DESCRIPTION
**Pull request by stephan-henningsen**
Add IP_NF_MANGLE to "Generally Required" kernel features, since it appears to be necessary for Docker Swarm to work.

Closes #46636

**- What I did**
Used the `check-config.sh` script for my custom Linux to be compatible with Docker.  And it mostly works, except connecting to local services in swarm mode! 

I tested on a single-node swarm cluster and started a simple web service:
```
docker swarm init --default-addr-pool 10.22.0.0/16
docker service create --publish published=8088,target=80 --name=www nginx:1.25.2-alpine
curl 127.0.0.1:8088
``` 
The last command will fail to connect to the published port: `curl: (7) Failed to connect to 127.0.0.1 port 8088 after 0 ms: Error`

**- How I did it**
I isolated the cause for the connection refused to a single kernel module, using lots of `lsmod` and `diff` between a working system and my broken system, and moving various kernel modules out of the way and back again. It took some time.

**- How to verify it**
First establish a failing test case:
1. Boot into a Linux that starts a Docker Engine but any swarm nodes.
2. `sudo mv /lib/modules/6.1.51/kernel/net/ipv4/netfilter/iptable_mangle.ko{,.disabled}` (or equivalent) to move kernel modules out of the way.
3. `docker swarm init --default-addr-pool 10.22.0.0/16`
4. `docker service create --publish published=8088,target=80 --name=www nginx:1.25.2-alpine`
6. `curl 127.0.0.1:8088`
Expected: Connected, HTML is shown .
Actual: Connection failed.
Run `lsmod | grep iptable_mangle` and confirm the module isn't loaded.

Cleanup:
1. `docker service rm www`
2. `docker swarm leave --force`

Now confirm that the module is indeed required by swarm:
1. `sudo mv /lib/modules/6.1.51/kernel/net/ipv4/netfilter/iptable_mangle.ko{.disabled,}` to reinstall kernel module
2. `docker swarm init --default-addr-pool 10.22.0.0/16`
3. `lsmod | grep iptable_mangle` and confirm the module is loaded but unused.
4. `docker service create --publish published=8088,target=80 --name=www nginx:1.25.2-alpine`
5. Run `lsmod | grep iptable_mangle` and confirm the module is in fact loaded and in use.
6. `curl 127.0.0.1:8088`
Expected/Actual: `iptable_mangle` is listed, HTML is shown.

**- Description for the changelog**
Add IP_NF_MANGLE to the list of "Generally Required" because it is required by Swarm.

**- A picture of a cute animal (not mandatory but encouraged)**

```
                               __
                              /\_\
                             _\/_/
                            /\_\
                            \/_/_
                              /\_\
                              \/_/
                             /\_\               .
                             \/_/              ::
                              .:::::::::::::..::::.
                              :::::::::::::::::
                              ;;;;;;.:::::::::
                               ;;;;;;:::::::
                                 ;;;:::::

                        https://lightwhale.asklandd.dk

```

Signed-off-by: Stephan Henningsen <stephan+github@asklandd.dk>

### CODE REVIEW

**Review by neersighted — APPROVED** [review]
I'm not 100% sure this is the correct place. There are three places that we create mangle rules (and the last one in my list is the one you got bit by):
* SCTP packet egress: https://github.com/moby/moby/blob/b85185e65910b5cb06fc6b81366c87b976a6a134/libnetwork/iptables/iptables.go#L363-L380
* Encrypted overlay networks: https://github.com/moby/moby/blob/b85185e65910b5cb06fc6b81366c87b976a6a134/libnetwork/drivers/overlay/encryption.go#L228-L250
* IPVS load-balancing: https://github.com/moby/moby/blob/b85185e65910b5cb06fc6b81366c87b976a6a134/libnetwork/service_linux.go#L547-L554

The latter two are only used with the `overlay` network driver, so I'm somewhat inclined to say that this should be scoped to the driver. On the other hand, we do rely on this for SCTP in certain situations, and other netfilter/xtables features are listed here.

I'll defer to @akerouanton and @corhere on whether this should be moved (or checked twice, once for overlay and one for SCTP, etc.) or not.

**Comment by neersighted** [comment]
Oh, also, forgot:

---

Thank you for contributing! It appears your commit message is missing a DCO sign-off,
causing the DCO check to fail.

We require all commit messages to have a `Signed-off-by` line with your name
and e-mail (see ["Sign your work"](https://github.com/moby/moby/blob/v20.10.11/CONTRIBUTING.md#sign-your-work)
in the CONTRIBUTING.md in this repository), which looks something like:

```
Signed-off-by: YourFirsName YourLastName <yourname@example.org>
```

There is no need to open a new pull request, but to fix this (and make CI pass),
you need to _amend_ the commit(s) in this pull request, and "force push" the amended
commit.

Unfortunately, it's not possible to do so through GitHub's web UI, so this needs
to be done through the git commandline.

You can find some instructions in the output of the DCO check (which can be found
in the "checks" tab on this pull request), as well as in the [Moby contributing guide](https://github.com/moby/moby/blob/v20.10.11/docs/contributing/set-up-git.md).

Steps to do so "roughly" come down to:

1. Set your name and e-mail in git's configuration:

    ```bash
    git config --global user.name "YourFirstName YourLastName"
    git config --global user.email "yourname@example.org"
    ```

    (Make sure to use your _real_ name (**not your GitHub username/handle**) and e-mail)


2. Clone your fork locally
3. Check out the branch associated with this pull request
4. Sign-off and amend the existing commit(s)

    ```bash
    git commit --amend --no-edit --signoff
    ```

    If your pull request contains multiple commits, either squash the commits (if
    needed) or sign-off each individual commit.

5. _Force push_ your branch to GitHub (using the `--force` or [`--force-with-lease`](https://stackoverflow.com/questions/52823692/git-push-force-with-lease-vs-force) flags) to update the pull request.


Sorry for the hassle (I wish GitHub would make this a bit easier to do), and let me know if you need help or more detailed instructions!

**Review by corhere — APPROVED** [review]
SCTP is the transport protocol used in WebRTC so not much of an edge case these days. Just about anyone running a multiplayer browser game, realtime chat or other similar server in a container is going to run into this. I think it makes sense to consider SCTP packet egress a baseline feature, so unless we can work around the kernel issue without it, IP_NF_MANGLE would have to be generally required.

**Comment by stephan-henningsen** [comment]
> Oh, also, forgot:
> 
> Thank you for contributing! It appears your commit message is missing a DCO sign-off, causing the DCO check to fail.

Yes, I had a feeling I would fail here.  I found out about the sign-off too late, panicked, and added it in the PR comment ;)

I believe it's properly signed off now.

**Pull request merged**
