### PR TITLE
Bumping up the bolt version to latest commit tag for compiling Power …

### PR DESCRIPTION
**Pull request by brahmaroutu**
…and Z

Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

sorry to duplicate the effort from @hqhq #16898 but now that the support for Power and Z are also merged this PR is going to help setup Power and Z CI runs.

### CODE REVIEW

**Comment by brahmaroutu** [comment]
also please see @tianon boltdb/bolt#438

**Comment by hqhq** [comment]
Aren't we waiting for a tag for bolt? Once we got that, or got answer from bolt, I can rebase #16898 , it'll surely including Power and Z.

**Comment by brahmaroutu** [comment]
@hqhq Sure that will work for me.

**Comment by jfrazelle** [comment]
@brahmaroutu so are we inn favor of @hqhq 's then, can we close this and wait forr a tag

**Comment by brahmaroutu** [comment]
Sure, closing this.

**Pull request closed without merging**
