### PR TITLE
Remove tar copy-up for tmpfs mounts

### PR DESCRIPTION
**Pull request by crosbymichael**
We cannot rely on the tar command for this type of operation because tar
versions, flags, and functionality can very from distro to distro.
Since this is in the container execution path it is not safe to have
this as a dependency from dockers POV where the user cannot change the
fact that docker is adding these pre and post mount commands.

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
design LGTM

**Comment by justincormack** [comment]
docs need updating for this "The mount copies the underlying content of my_image into /tmp" in man/docker-create.1 and man/docker-run.1

**Comment by tiborvass** [comment]
LGTM

**Comment by tianon** [comment]
So where/how is this copying going to take place as an alternative?

**Comment by crosbymichael** [comment]
@tianon we can release this and see if it's actually an issue for users and if it is find a better solution that does not shell out to tar

**Comment by justincormack** [comment]
I think it is useful without the tar feature myself, eg to mount /tmp with read only. Changing the behaviour later to reinstate does not seem to be a problem though if there is a clean solution.

**Comment by tianon** [comment]
Ok

**Comment by thaJeztah** [comment]
sounds reasonable to me, so LGTM

**Comment by MHBauer** [comment]
browsing through the docs for tmpfs:

does L#172 here need to change?
```
docs/reference/commandline/run.md
166:### mount tmpfs (--tmpfs)
167-
168:    $ docker run -d --tmpfs /run:rw,noexec,nosuid,size=65536k my_image
169-
170:    The --tmpfs flag mounts a tmpfs into the container with the rw,noexec,nosuid,size=65536k options.
171-
172-    Underlying content from the /run in the my_image image is copied into tmpfs.
```
How about L#1369 here:
```
docs/reference/run.md
1367:    --tmpfs=[]: Create a tmpfs mount with: container-dir[:<options>], where the options are identical to the Linux `mount -t tmpfs -o` command.
1368-
1369-    Underlying content from the "container-dir" is copied into tmpfs.
1370-
1371:    $ docker run -d --tmpfs /run:rw,noexec,nosuid,size=65536k my_image
1372-
```

**Comment by icecrime** [comment]
Merging: @MHBauer docs updates will be taken care of by @thaJeztah in a followup PR.

**Comment by rhatdan** [comment]
It would have been nice if I was notified.

This is definitely a problem.  As I stated in the other pull request, this breaks --read-only feature for running containers like httpd which depend on having a writable /run.  Since the underlying  image will have /run/httpd and httpd will blow up without it.

If the distribution does not have tar, the commands will not run.   And do we have an example of a tar command that does not support these options?

Could we ship a gotar version in docker for this support?  

@cpuguy83 Does docker volumes do something similar to this?

**Pull request merged**
