### PR TITLE
Skip some test on remote daemon for e2e run(s)

### PR DESCRIPTION
**Pull request by vdemeester**
We may need to run those on the CI too at some point.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by tiborvass** [comment]
Some are still missing, will add commits to this PR

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AntaresS — APPROVED** [review]
LGTM!

**Comment by tiborvass** [comment]
Don't merge yet.

**Comment by tiborvass** [comment]
@cpuguy83 @AntaresS feel free to review now. I removed `daemon` creation at all in integration/build because it was there only to enable experimental mode. Instead I added an experimental requirement to the test.

**Comment by tiborvass** [comment]
Investigating TestServicePlugin failure...

**Comment by tiborvass** [comment]
LGTM

**Comment by vdemeester** [comment]
> @cpuguy83 @AntaresS feel free to review now. I removed daemon creation at all in integration/build because it was there only to enable experimental mode. Instead I added an experimental requirement to the test.

@tiborvass right, I did that because I wanted to remove the experimental build/check at all at some point 👼

**Pull request merged**
