### PR TITLE
libnetwork: delete CHANGELOG.md

### PR DESCRIPTION
**Pull request by corhere**
It hasn't been updated since 2016.

Signed-off-by: Cory Snider <csnider@mirantis.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Hm.. think I saw the same failure on another PR; wondering if there's an issue somewhere, or just sheer luck;

```
=== Failed
=== FAIL: github.com/docker/docker/integration/container TestKillContainer/killing_signal (12.94s)
    kill_test.go:73: timeout hit after 10s: waiting for container to be one of (exited), currently running
    --- FAIL: TestKillContainer/killing_signal (12.94s)

=== FAIL: github.com/docker/docker/integration/container TestKillContainer (29.28s)
    main_test.go:32: assertion failed: error is not nil: Error response from daemon: Could not kill running container da6ff2504a5136240e8ff954c05aa5968de0534461ab13a2166655aaa9713426, cannot remove - tried to kill container, but did not receive an exit event: failed to remove da6ff2504a5136240e8ff954c05aa5968de0534461ab13a2166655aaa9713426

=== FAIL: github.com/docker/docker/integration/container TestRenameInvalidName (15.68s)
    main_test.go:32: assertion failed: error is not nil: Error response from daemon: Could not kill running container ae1e5f39ab256e9c509650f26ea63b065a483bb22af1596eb7ea35d21470c116, cannot remove - tried to kill container, but did not receive an exit event: failed to remove ae1e5f39ab256e9c509650f26ea63b065a483bb22af1596eb7ea35d21470c116

=== FAIL: github.com/docker/docker/integration/container TestContainerWithAutoRemoveCanBeRestarted/kill (29.23s)
    restart_test.go:206: assertion failed: error is not nil: Error response from daemon: Cannot kill container: 0162e09dd964c75d9d2e9c33bf0271bfaf7bfabf203825166d427cb73384dee1: tried to kill container, but did not receive an exit event
    restart_test.go:192: Cleaning up test container failed with error: Error response from daemon: Could not kill running container 0162e09dd964c75d9d2e9c33bf0271bfaf7bfabf203825166d427cb73384dee1, cannot remove - tried to kill container, but did not receive an exit event
    --- FAIL: TestContainerWithAutoRemoveCanBeRestarted/kill (29.23s)

=== FAIL: github.com/docker/docker/integration/container TestContainerWithAutoRemoveCanBeRestarted (36.68s)
```

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by corhere** [comment]
@thaJeztah there's an issue somewhere. I hit those same failures three times in a row on #44888 yesterday and opened this one as a "control" to confirm that the failures are unrelated to my changes.

**Comment by thaJeztah** [comment]
@corhere could it be the containerd v1.7.0-beta.3 update? I think we merged that one recently?

**Comment by corhere** [comment]
> could it be the containerd v1.7.0-beta.3 update? I think we merged that one recently?

That's what I'm thinking. It was merged yesterday.

**Pull request merged**
