### PR TITLE
Remove the rest of v1 manifest support

### LINKED ISSUE #33356: Replace the engine ID fingerprint with an UUID
**Description**

Currently the `engine ID` shown in `docker info` is the `fingerprint ID` used to `sign` the deprecated `manifest schema v1`. The key signature and finger on these manifests are not checked or used any longer for security, deprecated by notary. So, given this context, we could: 

1) Generate ephemeral `fingerprint` keys to push the `v1` manifests
2) Replace the current `engine ID` with an `UUID` generated once

**Suggested format**

**Location**: `<docker_storage_directory>/engine_uuid`

```
/var/lib/docker # cat engine_uuid
0df9fdce-f163-41f0-92bb-d0df29dd79bc
/var/lib/docker #
```

/cc @dmp42 @friism

### PR DESCRIPTION
**Pull request by justincormack**
As people are using the UUID in `docker info` that was based on the v1 manifest signing key, replace
with a UUID instead.

Remove deprecated `--disable-legacy-registry` option that was scheduled to be removed in 18.03.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

fix #33356
closes https://github.com/moby/moby/pull/35479

Note this does not yet remove libtrust as docker/distribution is still using it.

dog

### CODE REVIEW

**Comment by dmcgowan** [comment]
:+1: on making this change. This is doing a couple things that are worth noting, it is completely removing the ability to pull from a v1 registry, removing the ability to push schema 1 (deprecating some early versions of the v2 registry and might still break push to quay.io), and changing the engine ID which was once used by classic swarm but not sure if it still relies on this.

**Review by dmcgowan — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by fntlnz — APPROVED** [review]
LGTM :angel:

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
CI failing

```
18:11:18 ----------------------------------------------------------------------
18:11:18 FAIL: docker_cli_pull_local_test.go:201: DockerSchema1RegistrySuite.TestConcurrentPullMultipleTags
18:11:18 
18:11:18 assertion failed: 
18:11:18 Command:  /usr/local/cli/docker push 127.0.0.1:5000/dockercli/busybox:recent
18:11:18 ExitCode: 1
18:11:18 Error:    exit status 1
18:11:18 Stdout:   The push refers to repository [127.0.0.1:5000/dockercli/busybox]
18:11:18 0271b8eebde3: Preparing
18:11:18 0271b8eebde3: Pushed
18:11:18 
18:11:18 Stderr:   tag invalid
18:11:18 
18:11:18 
18:11:18 Failures:
18:11:18 ExitCode was 1 expected 0
18:11:18 Expected no error
18:11:21 
18:11:21 ----------------------------------------------------------------------
18:11:21 FAIL: docker_cli_push_test.go:203: DockerSchema1RegistrySuite.TestConcurrentPush
18:11:21 
18:11:21 docker_cli_push_test.go:204:
18:11:21     testConcurrentPush(c)
18:11:21 docker_cli_push_test.go:183:
18:11:21     c.Assert(err, checker.IsNil, check.Commentf("concurrent push failed with error: %v", err))
18:11:21 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000875480), Stderr:[]uint8(nil)} ("exit status 1")
18:11:21 ... concurrent push failed with error: exit status 1
18:11:21 
```

**Comment by dmcgowan** [comment]
The `DockerSchema1RegistrySuite` needs to be removed. A single test which verifies schema1 pull still works would be ideal, but this would also require the test uploading a schema1 image directly to the registry for testing. We don't currently have this sort of this interaction from the test but it would be useful. Can we remove the suite and add a marker for testing schema1, perhaps there is a better way to force it (could also be done by letting the registry downconvert by stripping the content type headers).

**Comment by AkihiroSuda** [comment]
LGTM after removal of the failing suite

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by olljanat** [comment]
@justincormack can you remove that failing test suite?

**Review by tao12345666333 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
I rebased this.

**Comment by cpuguy83** [comment]
And removed the schema1 test suite.

**Comment by thaJeztah** [comment]
Need to move the new test;

```
00:10:11 The following new tests were added to integration-cli:
00:10:11 
00:10:11 +func (s *DockerDaemonSuite) TestDaemonUUIDGeneration(c *check.C) {
00:10:11 
00:10:11 integration-cli is deprecated. Please add an API integration test to
00:10:11 ./integration/COMPONENT/. See ./TESTING.md for more details.

**Comment by cpuguy83** [comment]
Moved that test to integration/system, also just using the API to parse the UUID from `docker info` instead of checking on disk state.

**Comment by cpuguy83** [comment]
Looks like another test to clean up:

```
18:43:32 FAIL: docker_cli_daemon_test.go:1180: DockerDaemonSuite.TestDaemonWithWrongkey
18:43:32 
18:43:32 Creating a new daemon
18:43:32 [dd1f590b70fae] waiting for daemon to start
18:43:32 [dd1f590b70fae] daemon started
18:43:32 
18:43:32 [dd1f590b70fae] exiting daemon
18:43:32 docker_cli_daemon_test.go:1197:
18:43:32     c.Fatalf("Error reading key.json file: %s", err)
18:43:32 ... Error: Error reading key.json file: open /etc/docker/key.json: no such file or directory
18:43:32 
18:43:35 
18:43:35 ----------------------------------------------------------------------
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Actually; can we also remove this from the Dockerfile https://github.com/moby/moby/blob/20e8572a4c6b078c6199d6ac2010b8a0d381ef5c/Dockerfile#L50-L57

**Comment by cpuguy83** [comment]
Updated to remove the schema1 registry build.

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
