### PR TITLE
Avoid to pull existing layers

### PR DESCRIPTION
**Pull request by accepting**
Signed-off-by: JunLi <lijun.git@gmail.com>

**- What I did**
Consider this situation: There is an image which contains layers a, b(from bottom-most to top-most). And layer b already exists locally, while layer a does not exist. When pulling this image with the current docker version, it will pull both layer a and layer b. 

The situation above makes sense for the current docker version, because it pulls layer a and layer b **concurrently**. Before it finishes pulling layer a, it can not know the `diffID` of layer a. As a consequence,  it can not figure out the `chainID` of layer a and layer b, and it cannot know whether layer b is already existed locally under directory of `layerdb/sha256`. Therefore, docker must also pull layer b.

related issue: #33155

**- How I did it**
As reading related source code, I found that all the `diffID` of the image layers exists in its config file(`configRootFS.DiffIDs`). Hence, before downloading all the layers, we can first check whether the situation above is met. If yes, we wait the downloading procedure for image config. Then we can update all the layer metadatas, and fill their `diffID` field. Based on that knowledge, we can figure out whether layer b is already existed locally.

**- Description for the changelog**

Avoid to pull exsiting layers

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tonistiigi @dmcgowan PTAL

**Comment by accepting** [comment]
@tonistiigi @dmcgowan take a look?

**Comment by accepting** [comment]
anyone take a look?

**Comment by tonistiigi** [comment]
I have a bit trouble understanding this. Can you post reproducing steps maybe (or public images where this appears).

If I understand correctly, the case you are fixing is where the uncompressed layers have not changed but the compressed layers blobs have. Instead of pulling layers again and discovering that the uncompressed part was the same you try to check the uncompressed hash from the config. That makes sense although it is tricky because this case seems quite rare while downloading the config would make all pulls slightly slower.

What I don't understand is how this can be triggered by finding a compressed match of one of the child layers. How does finding such a layer increase the chance that a parent layer already exists but with a different compression?

Also, note that containerd storage layer that is about to replace the current moby code does not have any special handling for uncompressed blobs and always keeps a local compressed copy.

**Comment by accepting** [comment]
Here I reproduce with three hosts:
* host-1, docker 1.13.1 with go1.9.4
* host-2, docker 17.03.2-ce with go1.7.5
* host-3, docker 1.13.1 with go1.9.4 

and docker regsitry:  my-registry.com

### **Step 1:**

Build base image: test/test:v1 and test/test:v2 with dockerfile:
```
FROM busybox:1.27.1
ADD test /opt/
CMD "ls"
```

**On host-1:** 
```
$ docker build -t my-registry.com/test/test:v1 .

Sending build context to Docker daemon 15.87 kB
Step 1/3 : FROM busybox:1.27.1
Trying to pull repository docker.io/library/busybox ...
1.27.1: Pulling from docker.io/library/busybox
9e87eff13613: Pull complete
Digest: sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4
Status: Downloaded newer image for docker.io/busybox:1.27.1
---> efe10ee6727f
Step 2/3 : ADD test /opt/
---> 64fe20911e6b
Removing intermediate container afed9da1d942
Step 3/3 : CMD "ls"
---> Running in a7ae55c91438
---> 8c1f29ba60b0
Removing intermediate container a7ae55c91438
Successfully built 8c1f29ba60b0

$ docker push my-registry.com/test/test:v1

The push refers to a repository [my-registry.com/test/test]
96545b9469e6: Pushed
08c2295a7fa5: Pushed
```

Get all the layers of the image:
```
$ docker inspect my-registry.com/test/test:v1

...       
       "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:08c2295a7fa5c220b0f60c994362d290429ad92f6e0235509db91582809442f3",
                "sha256:96545b9469e668ed9f22e38b808df6b232238bcdc20fc2848f51c8df79cf3e62"
            ]
        }
```

Read the v2metadata-by-diffid of the its first layer
```
$ cat /var/lib/docker/image/overlay2/distribution/v2metadata-by-diffid/sha256/08c2295a7fa5c220b0f60c994362d290429ad92f6e0235509db91582809442f3

[{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"docker.io/library/busybox","HMAC":""},{"Digest":"sha256:daacdb2949be2c830e78b878ff144e38132faee2c2dcc20a544a5e0460fbdbf3","SourceRepository":"my-registry.com/test/test","HMAC":"f118b31efc7be77652a11a07d488ab953c667319a4256f1e489714ccb7cf4507"}]
```
**On host-2:**  
```
$ docker build -t my-registry.com/test/test:v2 .

Sending build context to Docker daemon 4.096 kB
Step 1/3 : FROM busybox:1.27.1
1.27.1: Pulling from library/busybox
9e87eff13613: Pull complete
Digest: sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4
Status: Downloaded newer image for busybox:1.27.1
---> efe10ee6727f
Step 2/3 : ADD test /opt/
---> 9bdd2596ba86
Removing intermediate container 407beb0c664d
Step 3/3 : CMD "ls"
---> Running in b9567fc4bb14
---> 793118a9c0b2
Removing intermediate container b9567fc4bb14
Successfully built 793118a9c0b2

$ docker push my-registry.com/test/test:v2

The push refers to a repository [my-registry.com/test/test]
e694b429c1ba: Pushed
08c2295a7fa5: Pushed

$ docker inspect my-registry.com/test/test:v1

...        
       "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:08c2295a7fa5c220b0f60c994362d290429ad92f6e0235509db91582809442f3",
                "sha256:e694b429c1ba141eb5a8564d50e5a6090f6c9e7ed4a93d3988d0f4c5ff49f218"
            ]
        }

$ cat /var/lib/docker/image/overlay2/distribution/v2metadata-by-diffid/sha256/08c2295a7fa5c220b0f60c994362d290429ad92f6e0235509db91582809442f3

[{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"docker.io/library/busybox","HMAC":""},{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"my-registry.com/test/test","HMAC":"83c4e9c3933b844dfd73e6d88a729e1c7a194eee54322581e7e10e4381684ac1”}]
```

### **Step 2:**
On host-2, pull test/test:v1
```
$ docker pull my-registry.com/test/test:v1

v1: Pulling from test/test
daacdb2949be: Pull complete
65aa69558e92: Pull complete
```
Now, Look at the v2metadata_by_diffid of the common layer, whose diffid is 08c2295a7fa5c220b0f60c994362d290429ad92f6e0235509db91582809442f3

```
$ cat /var/lib/docker/image/overlay2/distribution/v2metadata-by-diffid/sha256/08c2295a7fa5c220b0f60c994362d290429ad92f6e0235509db91582809442f3


[{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"docker.io/library/busybox","HMAC":""},{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"my-registry.com/test/test","HMAC":"83c4e9c3933b844dfd73e6d88a729e1c7a194eee54322581e7e10e4381684ac1"},{"Digest":"sha256:daacdb2949be2c830e78b878ff144e38132faee2c2dcc20a544a5e0460fbdbf3","SourceRepository":"my-registry.com/test/test","HMAC":""}]
```

### **Step 3:**
On host-2, build image test/test2:v1 based on test/test:v1 with Dockerfile:
```
FROM my-registry.com/test/test:v1
ADD test2 /opt/
CMD "ls"
```
```
$ docker build -t my-registry.com/test/test2:v1 .

Sending build context to Docker daemon 3.072 kB
Step 1/3 : FROM my-registry.com/test/test:v1
---> 8c1f29ba60b0
Step 2/3 : ADD test2 /opt/
---> 58fa35d22b2b
Removing intermediate container 60d556fa9815
Step 3/3 : CMD "ls"
---> Running in d3b1222aed68
---> 26daf2ef7ddd
Removing intermediate container d3b1222aed68
Successfully built 26daf2ef7ddd

$ docker push my-registry.com/test/test2:v1

The push refers to a repository [my-registry.com/test/test2]
c681daa1ca38: Pushed
96545b9469e6: Mounted from test/test
08c2295a7fa5: Mounted from test/test

$ cat /var/lib/docker/image/overlay2/distribution/v2metadata-by-diffid/sha256/08c2295a7fa5c220b0f60c994362d290429ad92f6e0235509db91582809442f3

[{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"docker.io/library/busybox","HMAC":""},{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"my-registry.com/test/test","HMAC":"83c4e9c3933b844dfd73e6d88a729e1c7a194eee54322581e7e10e4381684ac1"},{"Digest":"sha256:daacdb2949be2c830e78b878ff144e38132faee2c2dcc20a544a5e0460fbdbf3","SourceRepository":"my-registry.com/test/test","HMAC":""},{"Digest":"sha256:9e87eff13613eed2f67b0188f8604d1bbdd3a7f5d6a4f565e8923817db65d6e5","SourceRepository":"my-registry.com/test/test2","HMAC":"b563d39f488f2bc983be8dadde1aec4c05ab19ea0efb7008dc4ae12c71ff9952"}]
 ```

### **Step 4:**
**On host-3**
First, pull the base image test/test:v1.
```
$ docker pull my-registry.com/test/test:v1

Trying to pull repository my-registry.com/test/test ...
v1: Pulling from my-registry.com/test/test
daacdb2949be: Pull complete
65aa69558e92: Pull complete
```
Then, pull test/test2:v1. **We expect docker will only pull the new layer.**
```
$ docker pull my-registry.com/test/test2:v1

Trying to pull repository my-registry.com/test/test2 ...
v1: Pulling from my-registry.com/test/test2
9e87eff13613: Pull complete
65aa69558e92: Pull complete
2b64e185835c: Pull complete
```
However, docker pull all layers here.

**Comment by accepting** [comment]
@tonistiigi After deeply reading the code, I found the main reason to cause the situation above is that one layer can be compressed to different gzip files with different versions of golang. More detailedly, difference occurs between golang version 1.7.5(or before) and 1.8(or after).

For more details, you can refer to links: 
https://github.com/golang/go/blob/cd6b6202dd1559b3ac63179b45f1833fcfbe7eca/src/compress/gzip/gzip.go#L157
https://github.com/golang/go/blob/753452fac6f6963b5a6e38a239b05362385a3842/src/compress/gzip/gzip.go#L158

**Comment by accepting** [comment]
@tonistiigi @justincormack

**Comment by tonistiigi** [comment]
@accepting What's the 3rd layer in your push/pull if the rootfs only has 2. Is it because your registry does not support schema2. Am I right to assume that your fix only works if you have the `CMD ls` that is the layer that has the match and makes the other layers wait for config download? If this is the case then I repeat my earlier comment that this condition seems arbitrary and not relevant for the general case. I wouldn't mind waiting for config for all layers though that would fix this issue for general case, but with the move to containerd storage this code would be removed so I'm not sure there is a reason to temporarily add it.

**Comment by accepting** [comment]
@tonistiigi  Thanks for your comments!
First, the docker registry I used above is setup with image `docker.io/registry:2`, and it supports schema2.

Second, `CMD ls` has nothing to do with our discussion, because that directive does not generate a layer in docker registry. 

Third, to reproduce the situation above, we just need to follow several steps:
1. On host-1 and host-2, pull a docker images from outside registry, such as xxxx. Assume it consists of `n` layers.
2. On host-1 and host-2, build new images xxx-1, xxx-2 accordingly based on the image xxxx. And push them to our private registry, such as `my-registry`. Assume images xxx-1 and xxx-2 consists of `m` layers.
3. On host-2, pull xxx-1.
4. On host-2, build another image, such as yyyy, based on the image xxx-1. Assume images yyyy consists of `p` layers.
5. On host-3, pull image xxx-1 first. Then pull image yyyy. 
**These steps has no requirements to the content of the involed Dockerfiles used to build xxx-1, xxx-2 and yyyy.**

In step 5, when we pull image yyyy, we expect docker only pull `p - m` layers, because its base image xxx-1 is already pulled. Howerer, docker will pull `p` layers. 

The key to reproduce the case is only: **different docker version in host-1 and host-2, of which one uses docker with golang 1.7.5 or before, while another uses docker with golang 1.8 or after.**

**Comment by olljanat** [comment]
@accepting CI is failing to error:
```
15:39:50 distribution/pull_v2.go:631:36:warning: should replace i += 1 with i++ (golint)
15:39:50 Build step 'Execute shell' marked build as failure
```

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by cpuguy83** [comment]
Closing since this has gone stale.

Maybe a maintainer familiar with the push/pull semantics can look at this.
Also we would like to move to use containerd for distribution, and so any fix (if one is needed) should (also) go there.

**Pull request closed without merging**
