### PR TITLE
Windows: Add cred spec test with well form credentials

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Adds a Windows-specific CI test with a well-formed credential spec. 

@patricklang FYI.

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 👼
/cc @justincormack

**Comment by jhowardmsft** [comment]
@cpuguy83

**Comment by jhowardmsft** [comment]
@justincormack PTAL. Thanks :smile:

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
