### PR TITLE
Vendoring libnetwork @802895f

### LINKED ISSUE #29829: network name format in docker 1.13
With the fix for issue #27449, docker 1.13 has a very strict check on the network names. This breaks some plugin implementations  that use the character '/' as a separator for encoding tenant name. Please allow some symbols like '/', ':', etc

### LINKED ISSUE #30609: Docker CLI/API allows containers to be set to an invalid name
**Description**

Docker CLI/API is allows containers to be set to an invalid name

**Steps to reproduce the issue:**
1. docker create --name invalidname- {any image}
2. docker start invalidname-

also

1. docker run -itd --name validname {any image}
2. docker rename validname invalidname2-
3. docker stop invalidname2-
4. docker start invalidname2-

**Describe the results you received:**
```
Error response from daemon: invalid name: "invalidname-" includes invalid characters, resource name has to conform to "^[\\w]+[\\w-. ]*[\\w]+$"
Error: failed to start containers: invalidname-
```

```
Error response from daemon: invalid name: "invalidname2-" includes invalid characters, resource name has to conform to "^[\\w]+[\\w-. ]*[\\w]+$"
Error: failed to start containers: invalidname2-
```

**Describe the results you expected:**
creating and renaming a container should not allow invalid names. CLI states valid names are: [a-zA-Z0-9][a-zA-Z0-9_.-]
Names do not appear to be allowed to end with period or dash, but these conditions are not caught.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 1.13.1-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.6-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: K2GS:Q25F:CY3U:4MY3:O2D4:SF26:3UDA:EMSM:5QIC:FFB5:OH6G:SVDX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 36
 System Time: 2017-01-31T22:32:08.992451828Z
 EventsListeners: 1
Username: djones
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac; Also able to repro on Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by aboch**
Fixes #29829
Fixes #30609

Also changes to
- ease the load on external kv stores when retrieving tp level network objects
- expose nw db node discovery notifications to external drivers
- harden ipvs service creation/removal logic

### CODE REVIEW

**Comment by thaJeztah** [comment]
this one's for master, and cherry-picked into 1.13.1 through https://github.com/docker/docker/issues/30692

**Comment by yongtang** [comment]
@aboch I think this PR also fixes #30609

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
