### PR TITLE
Fix code typo error

### PR DESCRIPTION
**Pull request by JoeWrightss**
Fix typo: "nameAssocation" to "nameAssociation" in line 476.

### CODE REVIEW

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Z failed to error which I have not seen earlier:
```
09:15:34 FAIL: docker_cli_push_test.go:203: DockerSchema1RegistrySuite.TestConcurrentPush
09:15:34 
09:15:34 docker_cli_push_test.go:204:
09:15:34     testConcurrentPush(c)
09:15:34 docker_cli_push_test.go:183:
09:15:34     c.Assert(err, checker.IsNil, check.Commentf("concurrent push failed with error: %v", err))
09:15:34 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000c77380), Stderr:[]uint8(nil)} ("exit status 1")
09:15:34 ... concurrent push failed with error: exit status 1
```
Let's try again...

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by olljanat** [comment]
And now RS1 failed to error which I have not seen earlier:
```
10:58:35 FAIL: docker_cli_start_test.go:189: DockerSuite.TestStartReturnCorrectExitCode
10:58:35 
10:58:35 docker_cli_start_test.go:199:
10:58:35     c.Assert(exitCode, checker.Equals, 12, check.Commentf("out: %s", out))
10:58:35 ... obtained int = 125
10:58:35 ... expected int = 12
10:58:35 ... out: time="2018-12-31T10:58:35Z" level=error msg="error waiting for container: EOF" 
```

**Comment by olljanat** [comment]
Derek add label: rebuild/windowsRS1

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by olljanat** [comment]
Some other new error on RS1. Weird:
```
11:19:13 2018/12/31 11:18:40 http: panic serving 127.0.0.1:49219: Plugin not ready
11:19:13 goroutine 40 [running]:
11:19:13 net/http.(*conn).serve.func1(0xc000140000)
11:19:13 	c:/go/src/net/http/server.go:1746 +0xd7
11:19:13 panic(0x7eb7c0, 0x8f3fc0)
11:19:13 	c:/go/src/runtime/panic.go:513 +0x1c7
11:19:13 github.com/docker/docker/pkg/plugins.TestFailOnce.func1(0x8fbf20, 0xc00014c000, 0xc000128200)
11:19:13 	c:/go/src/github.com/docker/docker/pkg/plugins/client_test.go:55 +0x56
11:19:13 net/http.HandlerFunc.ServeHTTP(0xc00010c070, 0x8fbf20, 0xc00014c000, 0xc000128200)
11:19:13 	c:/go/src/net/http/server.go:1964 +0x4b
11:19:13 net/http.(*ServeMux).ServeHTTP(0xc000104150, 0x8fbf20, 0xc00014c000, 0xc000128200)
11:19:13 	c:/go/src/net/http/server.go:2361 +0x12e
11:19:13 net/http.serverHandler.ServeHTTP(0xc00012c000, 0x8fbf20, 0xc00014c000, 0xc000128200)
11:19:14 	c:/go/src/net/http/server.go:2741 +0xb2
11:19:14 net/http.(*conn).serve(0xc000140000, 0x8fc2a0, 0xc000110180)
11:19:14 	c:/go/src/net/http/server.go:1847 +0x64d
11:19:14 created by net/http.(*Server).Serve
11:19:14 	c:/go/src/net/http/server.go:2851 +0x2fc
11:19:14 time="2018-12-31T11:18:40Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49218/Test.FailOnce: Post http://127.0.0.1:49218/Test.FailOnce: EOF, retrying in 1s"
11:19:14 time="2018-12-31T11:18:41Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49223/Test.Echo: Post http://127.0.0.1:49223/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 1s"
11:19:14 time="2018-12-31T11:18:43Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49223/Test.Echo: Post http://127.0.0.1:49223/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 2s"
11:19:14 time="2018-12-31T11:18:45Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49223/Test.Echo: Post http://127.0.0.1:49223/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 4s"
11:19:14 time="2018-12-31T11:18:50Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49223/Test.Echo: Post http://127.0.0.1:49223/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 8s"
11:19:14 --- FAIL: TestClientWithRequestTimeout (0.00s)
11:19:14     client_test.go:259: assertion failed: 
11:19:14         --- context.DeadlineExceeded
11:19:14         +++ err
11:19:14         :
11:19:14         	-: context.deadlineExceededError{}
11:19:14         	+: &net.OpError{Op: "dial", Net: "tcp", Addr: s"127.0.0.1:49294", Err: &poll.TimeoutError{}}
11:19:14         
11:19:14 time="2018-12-31T11:18:58Z" level=warning msg="Unable to locate plugin: vegetable, retrying in 1s"
11:19:14 time="2018-12-31T11:18:59Z" level=warning msg="Unable to locate plugin: vegetable, retrying in 2s"
11:19:14 time="2018-12-31T11:19:01Z" level=warning msg="Unable to locate plugin: vegetable, retrying in 4s"
11:19:14 time="2018-12-31T11:19:05Z" level=warning msg="Unable to locate plugin: vegetable, retrying in 8s"
11:19:14 FAIL
11:19:14 coverage: 73.6% of statements
11:19:14 FAIL	github.com/docker/docker/pkg/plugins	34.918s
```

**Comment by olljanat** [comment]
Derek add label: rebuild/windowsRS1

**Comment by olljanat** [comment]
Weird. RS1 does not like this PR at all.
```
15:52:45 FAIL: check_test.go:107: DockerSuite.TearDownTest
15:52:45 
15:52:45 assertion failed: error is not nil: Error response from daemon: container 73045cbd60b3b5a795bf285b94ca2ea8d1a7aaae2b1bef4a9ade93b2d72ca956: driver "windowsfilter" failed to remove root filesystem: hcsshim::GetComputeSystems: Access is denied.: failed to remove 73045cbd60b3b5a795bf285b94ca2ea8d1a7aaae2b1bef4a9ade93b2d72ca956
15:52:45 
15:52:45 ----------------------------------------------------------------------
15:52:45 PANIC: docker_cli_start_test.go:189: DockerSuite.TestStartReturnCorrectExitCode
15:52:45 
15:52:45 docker_cli_start_test.go:199:
15:52:45     c.Assert(exitCode, checker.Equals, 12, check.Commentf("out: %s", out))
15:52:45 ... obtained int = 125
15:52:45 ... expected int = 12
15:52:45 ... out: time="2018-12-31T15:52:34Z" level=error msg="error waiting for container: EOF" 
15:52:45 
15:52:45 
15:52:45 ... Panic: Fixture has panicked (see related PANIC)
```

**Comment by olljanat** [comment]
Derek add label: rebuild/windowsRS1

**Review by vdemeester — APPROVED** [review]
LGTM :tiger: 
/cc @thaJeztah

**Review by thaJeztah — CHANGES_REQUESTED** [review]
changes LGTM, but the sign-off may have to be fixed;

@JoeWrightss could you make sure your sign-off is using your real name, not your GitHub alias?

```
Signed-off-by: JoeWrightss <zhoulin.xie@daocloud.io>
```

**Comment by JoeWrightss** [comment]
@thaJeztah , thank you for your reminding, and I have change my sign-off in my real name now.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
