### PR TITLE
use of checkers on docker_cli_v2_only.go

### PR DESCRIPTION
**Pull request by echo33**
Signed-off-by: weiyan weiyan3@huawei.com

### CODE REVIEW

**Comment by HuKeping** [comment]
nit... use `checker` instead of `check` would be better

**Comment by vdemeester** [comment]
@HuKeping :heart_eyes_cat:

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐼

**Comment by echo33** [comment]
@HuKeping I got it, thanks

**Comment by echo33** [comment]
@cpuguy83  thanks

**Comment by echo33** [comment]
@vdemeester I got it, thanks

**Pull request merged**
