### PR TITLE
[test-integration] Clean utils.go from most of its content

### PR DESCRIPTION
**Pull request by vdemeester**
Most of the code is now on pkg/integration. The last function of `utils.go` is `runCommandWithOutput` and is used 236 times, so… this will be a PR by itself :angel: 

/cc @dnephin @thaJeztah @vieux @mavenugo @tiborvass 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM!

**Comment by vdemeester** [comment]
Rebased 👼

**Comment by cpuguy83** [comment]
```
18:01:15 These files are not properly gofmt'd:
18:01:15  - integration-cli/docker_cli_push_test.go
18:01:15 
18:01:15 Please reformat the above files using "gofmt -s -w" and commit the result
```

**Review by thaJeztah — APPROVED** [review]
LGTM (if green)

**Comment by thaJeztah** [comment]
it's green :smile:

**Pull request merged**
