### PR TITLE
README: Update Github url for vim syntax plugin

### PR DESCRIPTION
**Pull request by danihodovic**
**- What I did**
Updated the path for the vim syntax plugin from docker/docker to moby/moby.

**- How I did it**

**- How to verify it**
I installed the plugin for myself.

**- Description for the changelog**

README: Updated the vim syntax plugin path from docker/docker to moby/moby.

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by yongtang** [comment]
Not sure who is the best person to look into this area, maybe @thaJeztah?

**Comment by thaJeztah** [comment]
Hm; I'm not a vim user; not sure what the `docker/docker` / `moby/moby` part does in these instructions. The canonical import path for this repository when importing the code in Go is still `github.com/docker/docker`, but not sure if that's relevant here.

**Comment by ripcurld** [comment]
@thaJeztah - basically it is a way to import vim plugins (like syntax highlight or auto completion). It suggests to get Dockerfile syntax highlights from `moby/moby` (this repository) instead of `docker/docker`.

**Comment by thaJeztah** [comment]
docker/docker of course still redirects here. Erm, yes, so, I'd happily defer review of this PR to someone else 😅, as I don't really know what's best. (Orthogonal, but I think there were also plans to eventually move the Dockerfile syntax itself, now that both BuildKit and this repository implement the syntax; having it in a standalone repository would make sense from that perspective)

**Review by fntlnz — APPROVED** [review]
LGTM - :pencil2:

**Review by thaJeztah — APPROVED** [review]
Alright let's merge this one; thanks!!

**Pull request merged**
