### PR TITLE
Move directory size calculation to pkg/ (fixes #10970)

### LINKED ISSUE #10970: Move TreeSize function to separate /pkg dir
**Summary**: 

Currently there is code in `/utils/utils_daemon.go` to handle getting the size of a directory specified by a path.  This `utils` package is too large and needs to be broken up.

**Proposed solution**:

Move the `TreeSize` function into a separate package inside `/pkg` called `directory`.  The build tag at the top of this file will need to be changed from `// +build daemon` to `// +build linux` as it uses `syscall.Stat_t` which is a linux only type.  Because of the new directory the function name can be changed to `Size`.

### PR DESCRIPTION
**Pull request by martijndwars**
This PR fixes #10970 and adds some test cases.

### CODE REVIEW

**Comment by estesp** [comment]
This looks good, thanks for the added tests!  I think you can use `t.Fatalf` everywhere you have used `t.Errorf` to match what's done in all the other unit and integration tests in Docker.

**Comment by MartijnDwars** [comment]
Thanks for the feedback! `t.Fatalf` is indeed more appropriate.

**Comment by gewoonrik** [comment]
@MartijnDwars You forgot to sign your commit ;)

**Comment by estesp** [comment]
Can you please squash these 2 commits into 1?  Then I think this is ready to go--thanks!

**Comment by MartijnDwars** [comment]
Done!

**Comment by estesp** [comment]
LGTM

**Comment by crosbymichael** [comment]
@MartijnDwars very nice, thanks for doing this!

LGTM

**Pull request merged**
