### PR TITLE
Improve test accuracy for pkg/chrootarchive

### PR DESCRIPTION
**Pull request by yestin**
Check test correctness of untar by comparing destination with
source.

The symbolic link copying fails the tests of ChrootCopyWithTar
and ChrootCopyFileWithTar. The implementation of ChrootCopyFileWithTar
follows the symbolic link and copies the regular file. The behaviour
is different from tar/untar, but clarification is needed before
making the test case a failure.

This is a supplement to the #11601 fix.

Signed-off-by: Yestin Sun sunyi0804@gmail.com

### CODE REVIEW

**Comment by yestin** [comment]
The build failure does not seem to be related to my change.

--- FAIL: TestEventsFilterContainerID (1.36s)
	docker_cli_events_test.go:355: Expected 3 events, got 2: [2015-03-30T04:35:05.000000000Z 277544aef42bfef1e21252bbf26606b6e728cbd73f37cc7b768279ca2e16f34a: (from busybox:latest) create 2015-03-30T04:35:05.000000000Z 277544aef42bfef1e21252bbf26606b6e728cbd73f37cc7b768279ca2e16f34a: (from busybox:latest) start]

Any hints?

**Comment by LK4D4** [comment]
ping @unclejack about links copying. Maybe we can just not test hashes for such cases.

**Comment by yestin** [comment]
Still struggling to get my Windows virtual machine to build the tests and the documentation for Windows is very limited. I will upload a new PR as soon as I get it sorted out.

**Comment by yestin** [comment]
Still can not get Window VM to set up the test environments. I have to split this change into small pieces and see who is the culprit that broke the Windows unit test. PR #12204 passes the test. After it is merged, I can upload the part 2 and part 3.

**Pull request closed without merging**
