### PR TITLE
docs: update docker inspect part of docs

### PR DESCRIPTION
**Pull request by HuKeping**
The docker inspect part of docs is quit different with what it
really be.

relate with #9968

Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
Should the older versions of the docs also be updated, wrt the missing restartPolicy? https://github.com/docker/docker/pull/9968#issuecomment-69451297

**Comment by SvenDowideit** [comment]
LGTM - @HuKeping if you're interested in updating further back, awseome, but I would merge this quickly, and then do follow on PR's (Unless my co-maintainers take longer than you do :) )

@fredlf @jamtur01

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
