### PR TITLE
WIP: hack DNS options until it mostly works

### PR DESCRIPTION
**Pull request by thockin**
This is just hacking until the basic feature set works.  Looking for approval on the feature overall.  I just found everywhere (I hope) DNS search was mentioned and replicated and tweaked.

Regarding #14069

Signed-off-by: Tim Hockin tim.hockin@google.com

### CODE REVIEW

**Comment by LK4D4** [comment]
Makes sense for me.
ping @docker/core-maintainers

**Comment by icecrime** [comment]
Makes sense for me too: moving to code review.

**Comment by icecrime** [comment]
The changes to `vendor/src/github.com/docker/libnetwork/` must be submitted in a PR against docker/libnetwork, then we'll update the vendored dependency through the `make/vendor.sh` script here.

**Comment by thockin** [comment]
Great, I'll re-tool the PR into a libnetwork part and a docker part this
week.  Mean time, any feedback on either part can accumulate here, and I'll
fix it in the offshoot PRs.

**Comment by tiborvass** [comment]
Ping @thockin 
Feel free to close your PR and reopen it once it's ready.

**Comment by icecrime** [comment]
@thockin Hey! Let me know when the change in libnetwork made it through and I can reopen here.

**Comment by thockin** [comment]
ACK.  I just need to make time.

**Comment by thockin** [comment]
libnetwork: https://github.com/docker/libnetwork/pull/467

**Comment by thockin** [comment]
libnetwork change is in, I guess I need to wait for that to be vendored in?  How often does that happen?

**Comment by mavenugo** [comment]
@thockin vendored-in based criticality of the fixes for docker project.
We have an upcoming vendor-in planned for the user-namespace support.

**Comment by thockin** [comment]
I'm going to re-open this PR - it needs a new libnetwork, but is otherwise done, I think.

**Comment by thaJeztah** [comment]
@thockin are you still working on this? Libnetwork was vendored, so your change is probably in there :)

**Comment by thaJeztah** [comment]
This was replaced by https://github.com/docker/docker/issues/16031

**Pull request closed without merging**
