### PR TITLE
Rename integration-cli to integration…

### PR DESCRIPTION
**Pull request by vdemeester**
… and `test-integration-cli` to `test-integration`. These tests
include more than `cli` integration tests and now that `cli` is no
more in here (but in `docker/cli` it makes even less sense to keep
that name.

🦁

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by thaJeztah** [comment]
There's some other PR's that we'd like to have merged before 17.06 code freeze, but we can make this change after those are in 🤗

**Comment by vdemeester** [comment]
> There's some other PR's that we'd like to have merged before 17.06 code freeze, but we can make this change after those are in :hugs:

Definitely :wink:

**Comment by AkihiroSuda** [comment]
windows failing

**Comment by vdemeester** [comment]
> windows failing

This is to be expected for now, I would need to update the CI (but we'll wait a bit for that though)

**Comment by vdemeester** [comment]
After discussing the subject in daily #moby-project, let's close this one for now, taking another note (issue/ml to come to discuss on the subject 😉)

**Pull request closed without merging**
