### PR TITLE
v1 spec: fix typos and formatting

### PR DESCRIPTION
**Pull request by TomasTomecek**
https://github.com/TomasTomecek/docker/blob/fix-v1-spec-typos/image/spec/v1.md

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @jlhawn @steeve @dmcgowan

**Comment by jlhawn** [comment]
LGTM

thanks @TomasTomecek

**Comment by dmcgowan** [comment]
LGTM

**Comment by TomasTomecek** [comment]
That was quick! Thanks for such a fast response.

**Pull request merged**
