### PR TITLE
pkg/system: fix compile on darwin (macOS)

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/docker/cli/pull/2835

### CODE REVIEW

**Comment by thaJeztah** [comment]
Failure is flakiness when building the e2e image; I'm removing that from CI in https://github.com/moby/moby/pull/41660, as we don't use the image that's built

**Comment by tonistiigi** [comment]
Files are named wrong if they don't work on darwin

**Comment by thaJeztah** [comment]
I was looking at that, but that may be because of bsd

**Comment by tonistiigi** [comment]
BSD is unix so file shouldn't be called like that.

**Comment by thaJeztah** [comment]
what would the right name be? `_linux_or_bsd_or_openbsd.go` ?

**Comment by tonistiigi** [comment]
Don't need a suffix, can just split based on functionality(doesn't seem to matter atm as there is no regular `rm.go` anyway). Otherwise `_nowindows`.

**Comment by thaJeztah** [comment]
renamed some files. PTAL

**Review by tonistiigi — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
