### PR TITLE
daemon: oci: obey CL_UNPRIVILEGED for user namespaced daemon

### PR DESCRIPTION
**Pull request by cyphar**
When runc is bind-mounting a particular path "with options", it has to
do so by first creating a bind-mount and the modifying the options of
said bind-mount via remount. However, in a user namespace, there are
restrictions on which flags you can change with a remount (due to
CL_UNPRIVILEGED being set in this instance). Docker historically has
ignored this, and as a result, internal Docker mounts (such as secrets)
haven't worked with --userns-remap. Fix this by preserving
CL_UNPRIVILEGED mount flags when Docker is spawning containers with user
namespaces enabled.

[Chester the Puppy](https://flic.kr/p/qnq6T6)

###### [Chester the Puppy](https://flic.kr/p/qnq6T6) by [Karen Blaha](https://www.flickr.com/photos/vironevaeh/)

Ref: https://github.com/opencontainers/runc/pull/1603
Signed-off-by: Aleksa Sarai <asarai@suse.de>

/cc @justincormack

### CODE REVIEW

**Comment by cyphar** [comment]
I corrected the previous SystemZ failure (due to arch-specific type issues), but this failure looks unrelated.

**Comment by cyphar** [comment]
This is something to consider for `cri-o`. I can work up a patch for you guys as well.

/cc @runcom @mrunalp

**Comment by runcom** [comment]
> This is something to consider for cri-o. I can work up a patch for you guys as well.

would be awesome :)

**Comment by tophj-ibm** [comment]
something appears wrong with z-node8, I'm seeing only it fail everywhere. I took it out of the pool and messaged one of the Z guys. Looking at the p test

**Comment by crosbymichael** [comment]
LGTM

@justincormack PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
