### PR TITLE
Rename `Daemon.Get` to `Daemon.GetContainer`.

### PR DESCRIPTION
**Pull request by calavera**
This is more aligned with `Daemon.GetImage` and less confusing.

/cc @tiborvass, @anusha-ragunathan, @MHBauer

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by duglin** [comment]
minor but very helpful! LGTM once janky is happy.

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by MHBauer** [comment]
Makes sense from an external view of the interface. Best to have it now in preparation for other changes coming.

**Comment by thaJeztah** [comment]
boo Janky

**Comment by calavera** [comment]
it's finally :green_heart: :exclamation:

**Comment by thaJeztah** [comment]
LGTM!

**Pull request merged**
