### PR TITLE
Port test from integration tests to integration-cli

### PR DESCRIPTION
**Pull request by brahmaroutu**
Addresses #12255
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Doesn't look like you removed the integration tests?

**Comment by brahmaroutu** [comment]
These tests are already removed.

**Comment by cpuguy83** [comment]
Oh you're right, I think I recall seeing new tests already added for at least the first one... let me check.

**Comment by cpuguy83** [comment]
Yes, here's the RestartKillWait: `https://github.com/docker/docker/blob/master/integration-cli/docker_cli_daemon_test.go#L900`

**Comment by brahmaroutu** [comment]
Thanks for taking all that trouble to find that ported test. I can take out the first test. But one subtle difference is that my test runs through cli code and the test you are pointing to is directly calling methods on daemon(is it a true cli?) Please advice.

**Comment by cpuguy83** [comment]
It is a CLI test, not calling methods directly on daemon.

**Comment by jfrazelle** [comment]
yes i do not think we need this then sorry :(

**Pull request closed without merging**
