### PR TITLE
vendor: bump libnetwork bf2bd42abc0a3734f12b5ec724e571434e42c669

### LINKED ISSUE #2406: Internal macvlan network overrides default gateway
I have container which needs to be connected to multiple overlay networks and one internal macvlan network.
Every time I connect the container to the macvlan network, it's default gateway will be set to non-existent default gateway.

I don't think internal networks should touch default gateway at all.

### LINKED ISSUE #39392: Containers can't communicate over macvlan internal network in swarm
**Description**

I'm trying to create macvlan private network for swarm service to communicate with non-docker system on the same VLAN.
In my case I have to create template networks for the macvlan one.
If I create the network as internal then containers can't communicate with each other.
If I create the network as non-internal it will change default gateway and break communication with rest of my network. 

It's not possible to create internal config-only network.

**Steps to reproduce the issue:**

1. create config-only networks:
on node1:
_docker network create --config-only --subnet 10.20.30.0/24 -o parent=enp1s0.30 --ip-range 10.20.30.192/27 private_net_template_
on node2:
_docker network create --config-only --subnet 10.20.30.0/24 -o parent=enp1s0.30 --ip-range 10.20.30.224/27 private_net_template_

2. create network:
_docker network create -d macvlan --internal --scope swarm --attachable --config-from private_net_template private_net_

**Describe the results you received:**

Internal parameter of the config-from network is overwritten by the config-only network.
Dummy interface is used as parent interface of the config-from private_net.

**Describe the results you expected:**

The private_net should use interface specified in it's config-from network.
Existing default gateway in container should not be changed for internal macvlan network.

**Additional information you deem important (e.g. issue happens only occasionally):**

I can create network without the --internal parameter but in such case it will change default gateway to non-existent ip from the network ip range which breaks communication.

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 34
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: r2t1fkcjozyq3gm8vv7owwzxn
 Is Manager: true
 ClusterID: qynxz17vjb84n0vxbp2926s2o
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.64.10.57
 Manager Addresses:
  10.64.10.57:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-9-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.956GiB
Name: apex7
ID: J5R3:JKMK:N5JS:37VX:QH7K:QNBL:4HR3:XAGQ:EDU4:J3AA:RF6F:JMGF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 149
 System Time: 2019-06-21T10:45:10.561415698-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was tested on linux KVM VMs but this doesn't really matter.

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/moby/libnetwork/compare/264bffcb88c1b6b7471c04e3c6b3f301233a544b...bf2bd42abc0a3734f12b5ec724e571434e42c669

relevant changes:

- docker/libnetwork#2407 Macvlan internal network should not change default gateway
    - fixes docker/libnetwork#2406 Internal macvlan network overrides default gateway
- vendor godbus/dbus v5
- Fix InhibitIPv4 nil panic
- Cleanup VFP during overlay network removal
    - fixes VFP leak in windows overlay network deletion

this should be the last one listed in https://github.com/moby/moby/issues/39392#issuecomment-591997438 to be vendored, so

fixes https://github.com/moby/moby/issues/39392 on master

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like CI is broken @stefanscherer

4296F8E3-AFDA-4B99-BAF2-5D738050DC02

**Review by AkihiroSuda — APPROVED** [review]

**Comment by cpuguy83** [comment]
Lots of macvlan/ipvlan failures.

**Comment by thaJeztah** [comment]
Yes, noticed them; looks like it's related to that change. Not familiar enough with them to tell if the tests are incorrect, or if it's breaking things.

@arkodg @lemrouch PTAL

**Comment by arkodg** [comment]
@lemrouch couple of things I've realized after looking at https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L153 and https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L135

We might still want to keep the dummyParent in case `config.ConfigFrom` is empty which will be needed so https://github.com/docker/libnetwork/commit/43a5e910fce38194d2c8e8c9d426042af7ef28fd will be needed to reworked to take care of that case

**Comment by arkodg** [comment]
@lemrouch  Looking at https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L179 and https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L247 
https://github.com/docker/libnetwork/commit/8d1f97eb6c04b936952d9efb241845de759aafdc
will be needed to be reworked to make sure we skip creating a gateway for an internal macvlan/ipvlan network only if an existing non-internal network exists

**Comment by lemrouch** [comment]
> https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L179
> and
> 
> https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L247

Those tests are broken by design. They are basically saying: make sure _isolated network_ is not isolated at all and can reach public ip address.

**Comment by lemrouch** [comment]
> @lemrouch Looking at
> 
> https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L179
> and
> 
> https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L247
> 
> [docker/libnetwork@8d1f97e](https://github.com/docker/libnetwork/commit/8d1f97eb6c04b936952d9efb241845de759aafdc)
> will be needed to be reworked to make sure we skip creating a gateway for an internal macvlan/ipvlan network only if an existing non-internal network exists

Again, internal networks should not mess with default gateways as this will break routing via regular network. The test is wrong.

**Comment by arkodg** [comment]
> > @lemrouch Looking at
> > https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L179
> > 
> > and
> > https://github.com/moby/moby/blob/40b2b4b083064d56be6aeb74c04da6e4a8f73d59/integration/network/macvlan/macvlan_test.go#L247
> > 
> > [docker/libnetwork@8d1f97e](https://github.com/docker/libnetwork/commit/8d1f97eb6c04b936952d9efb241845de759aafdc)
> > will be needed to be reworked to make sure we skip creating a gateway for an internal macvlan/ipvlan network only if an existing non-internal network exists
> 
> Again, internal networks should not mess with default gateways as this will break routing via regular network. The test is wrong.

but @lemrouch these are not internal networks, just a macvlan network with an empty parent

**Comment by arkodg** [comment]
also this err should not be nil, the test code looks fine to me
```
	_, err := container.Exec(timeoutCtx, client, id1, []string{"ping", "-c", "1", "-w", "1", "8.8.8.8"})
		// FIXME(vdemeester) check the time of error ?
		assert.Check(t, err != nil)
```
but the err is `nil`
```
macvlan_test.go:171: assertion failed: err is nil
```

**Comment by arkodg** [comment]
```
+++ b/vendor/github.com/docker/libnetwork/drivers/macvlan/macvlan_network.go
@@ -61,8 +61,6 @@ func (d *driver) CreateNetwork(nid string, option map[string]interface{}, nInfo
        // if parent interface not specified, create a dummy type link to use named dummy+net_id
        if config.Parent == "" {
                config.Parent = getDummyName(stringid.TruncateID(config.ID))
-               // empty parent and --internal are handled the same. Set here to update k/v
-               config.Internal = true
        }
        foundExisting, err := d.createNetwork(config)
        if err != nil {
@@ -100,18 +98,16 @@ func (d *driver) createNetwork(config *configuration) (bool, error) {
                }
        }
        if !parentExists(config.Parent) {
-               // if the --internal flag is set, create a dummy link
-               if config.Internal {
+               // Create a dummy link
+               if config.Parent == getDummyName(stringid.TruncateID(config.ID)) {
                        err := createDummyLink(config.Parent, getDummyName(stringid.TruncateID(config.ID)))
                        if err != nil {
                                return false, err
                        }
                        config.CreatedSlaveLink = true
                        // notify the user in logs they have limited communications
-                       if config.Parent == getDummyName(stringid.TruncateID(config.ID)) {
-                               logrus.Debugf("Empty -o parent= and --internal flags limit communications to other containers inside of network: %s",
-                                       config.Parent)
-                       }
+                       logrus.Debugf("Empty -o parent= limit communications to other containers inside of network: %s",
+                               config.Parent)
```
 fixes
    --- PASS: TestDockerNetworkMacvlan/MultiSubnet (24.72s)
    --- PASS: TestDockerNetworkMacvlan/Addressing (6.99s)

The above code tries to further separate the difference in meaning between empty Parent and internal network which can or cannot be the same

unclear why 
```
=== FAIL: amd64.integration.network.macvlan TestDockerNetworkMacvlan/InternalMode (13.45s)
    --- FAIL: TestDockerNetworkMacvlan/InternalMode (13.45s)
        macvlan_test.go:171: assertion failed: err is nil
        macvlan_test.go:172: assertion failed: expression is false: timeoutCtx.Err() == context.DeadlineExceeded
```

**Comment by lemrouch** [comment]
> unclear why the below test is failing
> 
> ```
> === FAIL: amd64.integration.network.macvlan TestDockerNetworkMacvlan/InternalMode (13.45s)
>     --- FAIL: TestDockerNetworkMacvlan/InternalMode (13.45s)
>         macvlan_test.go:171: assertion failed: err is nil
>         macvlan_test.go:172: assertion failed: expression is false: timeoutCtx.Err() == context.DeadlineExceeded
> ```
It's test for internal network. That means there is no default gateway anymore.
My guess is:
- the ping used to try to pass ICMP packet to nonexistent gw (internal MACLAN network imagined one, remeber?) and timed out
- now it has no default route so the ping gets _ping: connect: Network is unreachable_ immediately

**Comment by arkodg** [comment]
@lemrouch you're right, it still does give a `nil` error so the code can be changed to
```
-               timeoutCtx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
-               defer cancel()
-               _, err := container.Exec(timeoutCtx, client, id1, []string{"ping", "-c", "1", "-w", "1", "8.8.8.8"})
-               // FIXME(vdemeester) check the time of error ?
-               assert.Check(t, err != nil)
-               assert.Check(t, timeoutCtx.Err() == context.DeadlineExceeded)
+               result, _ := container.Exec(ctx, client, id1, []string{"ping", "-c", "1", "8.8.8.8"})
+               assert.Check(t, strings.Contains(result.Combined(), "Network is unreachable"))
```
which fixes the issue, will raise a PR for these soon

**Comment by thaJeztah** [comment]
Updated to current master, to include https://github.com/moby/libnetwork/pull/2523, which should  fix the CI failures

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
still failing

**Comment by thaJeztah** [comment]
😢 @arkodg PTAL 🤗

**Review by tao12345666333 — APPROVED** [review]
LGTM

I encountered a similar problem and fixed by this PR https://github.com/moby/libnetwork/pull/2519
(included in this vendor)

**Comment by arkodg** [comment]
@thaJeztah ` TestDockerNetworkMacvlan/InternalMode` and `TestDockerNetworkIpvlan/L3InternalMode` need to be rewritten to incorporate https://github.com/moby/moby/pull/40596#issuecomment-594089312

**Comment by thaJeztah** [comment]
@arkodg ah, sorry, overlooked that one, thought it was being handled by the changes in libnetwork 👍

**Review by arkodg — APPROVED** [review]
LGTM , thanks for incorporating the test changes

**Comment by arkodg** [comment]
@thaJeztah similar changes needed in `TestDockerNetworkIpvlan/L2InternalMode` as well, my bad

**Comment by thaJeztah** [comment]
d'oh! I saw that test and wanted to check it, but was in a hurry and forgot. Thanks!

**Comment by trapier** [comment]
@thaJeztah: would like to see this in CE 19.03.8.  Looks like the pattern for 19.03 is to backport from master.  Would like to confirm intent to backport this for 19.03.8, as well as offer any assistance from Mirantis to help make it so.

**Comment by thaJeztah** [comment]
>  Looks like the pattern for 19.03 is to backport from master. Would like to confirm intent to backport this for 19.03.8, as well as offer any assistance from Mirantis to help make it so.

For libnetwork, the 19.03 branch vendors from the corresponding bump_v19.03 branch in libnetwork (and 18.09 from the bump_v18.09 libnetwork branch).

I can open a bump PR for the 19.03 branch, or perhaps @SamWhited can update https://github.com/moby/moby/pull/40617 to get the latest changes from libnetwork

**Comment by thaJeztah** [comment]
@cpuguy83 @AkihiroSuda @arkodg this is green now, PTAL 👍

**Comment by SamWhited** [comment]
> I can open a bump PR for the 19.03 branch, or perhaps @SamWhited can update #40617 to get the latest changes from libnetwork

Wilco.

**Comment by arkodg** [comment]
@thaJeztah lets merge this PR
@SamWhited the failures in your PR for https://github.com/moby/moby/pull/40617 are unrelated to the failures encountered in this PR (and changes made here)

**Comment by SamWhited** [comment]
Updated. Will take a look at any failures when CI finishes running.

**Pull request merged**
