### PR TITLE
update tools urls and remove things we dont use

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
What about our dear leeroy ? 😄
LGTM 🐧

**Comment by jfrazelle** [comment]
he's there https://github.com/docker/docker/pull/19730/files#diff-9dacf7ac7d45a6b0d64601ac873d9723L13

**Comment by vdemeester** [comment]
ah 😸 yay 😄

**Pull request merged**
