### PR TITLE
br_netfilter is not loadable as a module.

### PR DESCRIPTION
**Pull request by mdavranche**
See issue #13969.

### CODE REVIEW

**Comment by unclejack** [comment]
It can be a module: `CONFIG_BRIDGE_NETFILTER=m` in the kernel's config, thus requiring modprobe to load.

NOT LGTM

**Comment by mdavranche** [comment]
As writen in net/Kconfig file (Linux source code), CONFIG_BRIDGE_NETFILTER cannot be compiled as a module:

config BRIDGE_NETFILTER
        bool "Bridged IP/ARP packets filtering"

Bool means you can only write
CONFIG_BRIDGE_NETFILTER=y
or
# CONFIG_BRIDGE_NETFILTER is not set

Trying to use CONFIG_BRIDGE_NETFILTER=m will lead to CONFIG_BRIDGE_NETFILTER=y

Options that can be compiled as a module are "tristate", not "bool".

This way to do is documented in Documentation/kbuild/kconfig-language.txt (Linux source code).

**Comment by unclejack** [comment]
Here's the module I've got out of that option: `/lib/modules/3.18.16/kernel/net/bridge/br_netfilter.ko`.

**Comment by mdavranche** [comment]
Indeed, the BRIDGE_NETFILTER option is tristate since this commit:
https://github.com/torvalds/linux/commit/34666d467cbf1e2e3c7bb15a63eccfb582cdd71f
My bad.

Do you think we have to make a test before trying to load the module? Maybe it had been built using =y, not =m...

**Comment by unclejack** [comment]
@mdavranche I think something like this would work:
(pseudo-code following)
```
err = modprobe_module
if ok = check_if_bridge_netfilter_is_ok; err != nil && ok != nil {
     error_out
}
```

**Comment by mdavranche** [comment]
I totally agree with this way to do.
I updated my pull request with this (see commit 061b47c87fc351db7d8321639ae754f52c893906).

**Comment by mdavranche** [comment]
@unclejack What do you think about this new code?

Thanks in advance for your answer.

**Comment by unclejack** [comment]
@mdavranche Does it actually fail when br_netfilter isn't loaded?

**Comment by mdavranche** [comment]
@unclejack I made a few tests to explain exactly what happens.


Test 1: br_netfilter is compiled as a module. Docker with or without patch (same behaviour).

None of the modules that Docker will attempt to load are loaded:
$ lsmod | grep -E "bridge|nf_nat|br_netfilter"
$

Let's start Docker daemon:
# docker -d

No warning, everything works well. Easy =)


Test 2, docker without the patch:

# docker version
Client version: 1.8.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): 51264fa-dirty
OS/Arch (client): linux/amd64
Server version: 1.8.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 51264fa-dirty
OS/Arch (server): linux/amd64

We use a 3.16.0 kernel, with br_netfilter builtin:
$ grep BRIDGE_NETFILTER /boot/config-3.16.0
CONFIG_BRIDGE_NETFILTER=y

None of the modules that Docker will attempt to load are loaded:
$ lsmod | grep -E "bridge|nf_nat|br_netfilter"
$

Let's start Docker daemon:
# docker -d

We have the following warning:
WARN[0000] Running modprobe bridge nf_nat failed with message: insmod /lib/modules/3.16.0-ovh-amd64/kernel/net/llc/llc.ko
insmod /lib/modules/3.16.0-ovh-amd64/kernel/net/802/stp.ko
insmod /lib/modules/3.16.0-ovh-amd64/kernel/net/bridge/bridge.ko
insmod /lib/modules/3.16.0-ovh-amd64/kernel/net/netfilter/nf_conntrack.ko
insmod /lib/modules/3.16.0-ovh-amd64/kernel/net/netfilter/nf_nat.ko
, error: exit status 1

This is a false positive: "modprobe -va bridge nf_nat br_netfilter" returns an error exit code because the br_netfilter module does not exist. The output is also wrong: it is the stdout of the "modprobe -va bridge nf_nat" command.

Let's stop Docker daemon:
kill -TERM `cat /var/run/docker.pid`

bridge and nf_nat had been loaded. Let's see what happens on next start:
# lsmod | grep -E "bridge|nf_nat|br_netfilter"
nf_nat_ipv4            12912  1 iptable_nat
nf_nat                 18241  3 ipt_MASQUERADE,nf_nat_ipv4,iptable_nat
nf_conntrack           87424  6 ipt_MASQUERADE,nf_nat,nf_nat_ipv4,xt_conntrack,iptable_nat,nf_conntrack_ipv4
bridge                106102  0
stp                    12437  1 bridge
llc                    12745  2 stp,bridge
# docker -d

We now have the following warning:
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1

Same reason: "modprobe -va bridge nf_nat br_netfilter" returns an error exit code because the br_netfilter module does not exist. The output is now empty as "modprobe -va bridge nf_nat" returns nothing (already loaded). Note that we should see an error. The pull request #13980 fixes this output problem.

Note that everything works well, we just have a false warning.


Test 3, docker with the patch:

# docker version
Client version: 1.8.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): 51264fa-dirty
OS/Arch (client): linux/amd64
Server version: 1.8.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 51264fa-dirty
OS/Arch (server): linux/amd64

None of the modules that Docker will attempt to load are loaded:
$ lsmod | grep -E "bridge|nf_nat|br_netfilter"
$

Let's start Docker daemon:
# docker -d

We have no warning. Everything is fine. bridge and nf_nat modules had been loaded:

# lsmod | grep -E "bridge|nf_nat|br_netfilter"
nf_nat_ipv4            12912  1 iptable_nat
nf_nat                 18241  3 ipt_MASQUERADE,nf_nat_ipv4,iptable_nat
nf_conntrack           87424  6 ipt_MASQUERADE,nf_nat,nf_nat_ipv4,xt_conntrack,iptable_nat,nf_conntrack_ipv4
bridge                106102  0
stp                    12437  1 bridge
llc                    12745  2 stp,bridge

When we restart Docker daemon, no warning too, everything works well.

**Comment by calavera** [comment]
Please, apply this change in https://github.com/docker/libnetwork. We can vendor the library in docker when the change is merged in its master branch.

Closing this PR. Thanks for taking time testing this behavior!

**Comment by pnedunuri** [comment]
Hello,

A question in lines of "bridge under /proc/sys/net/ being unavailable". Is there a way to modprobe in docker or any other solution to make it available?

Any inputs greatly appreciated!

Thanks!

**Comment by mdavranche** [comment]
My personal opinion is that it is not Docker's purpose to do that. I hope Docker will never alter my kernel modules, or whatever system prerequisite it'll need. Such things should be handled by your configuration management system (Puppet, or whatever).

**Pull request closed without merging**
