### PR TITLE
Fix volume plugin serialization.

### LINKED ISSUE #13818: volume-driver: In response type "error" is expected, but there is no way to decode it from json
Here is the definition of expected response from plugins of volume in volume/drivers/proxy.go:
https://github.com/docker/docker/blob/master/volume/drivers/proxy.go#L14

```
type volumeDriverResponse struct {
        Mountpoint string `json:",ommitempty"`
        Err        error `json:",ommitempty"`
}
```

I don't believe you can actually decode/encode from/to type "error", which is defined as:

```
type error interface {
        Error() string
}
```

It's an interface, not an struct, and no exportable field available.

This result in any non-null error message from external plugin shows:

```
ERRO[0071] Handler for POST /containers/create returned error: External volume driver request failed for test: json: cannot unmarshal object into Go value of type error
ERRO[0071] HTTP Error                                    err=External volume driver request failed for test: json: cannot unmarshal object into Go value of type error statusCode=500
```

BTW: Also, there are typos in struct descriptor: "ommitempty" should be "omitempty"

### PR DESCRIPTION
**Pull request by calavera**
Unmarshal errors into strings.
Fix `omit` typos.

Fixes #13818

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by yasker** [comment]
LGTM. @calavera thank you for quick fix!

**Comment by LK4D4** [comment]
@calavera Janky failed :/

**Comment by calavera** [comment]
it looks like `make test` doesn't like to have directories where all tests are excluded, it should be fixed now.

**Comment by calavera** [comment]
@LK4D4 all green :tada:

**Comment by runcom** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
