### PR TITLE
Windows CI: Address simple failures in TestPS*

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This addresses the simple failures found in TestPS\* integration-cli tests when run against a Windows daemon. It annotates tests that currently have no chance of running successfully on Windows with the reason. Obviously there will be further follow-up PRs to address to more interesting tests which remain skipped which should be possible to port. 

This PR increases coverage by having another 9 tests covered in Windows to Windows CI.

```
E:\go\src\github.com\docker\docker>runtest wl TestPs
Running test TestPs
DOCKER_TEST_HOST=tcp://127.0.0.1:2375
DOCKER_HOST=tcp://127.0.0.1:2375
=== RUN   Test
INFO: Testing against a local daemon
PASS: docker_cli_ps_test.go:569: DockerSuite.TestPsDefaultFormatAndQuiet        3.018s
PASS: docker_cli_ps_test.go:558: DockerSuite.TestPsFormatHeaders        3.139s
SKIP: docker_cli_ps_test.go:529: DockerSuite.TestPsFormatMultiNames (Test requires a Linux daemon)
SKIP: docker_cli_ps_test.go:478: DockerSuite.TestPsGroupPortRange (Test requires a Linux daemon)
SKIP: docker_cli_ps_test.go:588: DockerSuite.TestPsImageIDAfterUpdate (Test requires a Linux daemon)
SKIP: docker_cli_ps_test.go:459: DockerSuite.TestPsLinkedWithNoTrunc (Test requires a Linux daemon)
SKIP: docker_cli_ps_test.go:19: DockerSuite.TestPsListContainersBase (Test requires a Linux daemon)
PASS: docker_cli_ps_test.go:249: DockerSuite.TestPsListContainersFilterAncestorImage    24.376s
PASS: docker_cli_ps_test.go:499: DockerSuite.TestPsListContainersFilterCreated  0.584s
PASS: docker_cli_ps_test.go:380: DockerSuite.TestPsListContainersFilterExited   19.384s
PASS: docker_cli_ps_test.go:211: DockerSuite.TestPsListContainersFilterID       6.130s
PASS: docker_cli_ps_test.go:344: DockerSuite.TestPsListContainersFilterLabel    9.351s
PASS: docker_cli_ps_test.go:226: DockerSuite.TestPsListContainersFilterName     6.631s
PASS: docker_cli_ps_test.go:172: DockerSuite.TestPsListContainersFilterStatus   7.464s
SKIP: docker_cli_ps_test.go:130: DockerSuite.TestPsListContainersSize (Test requires a Linux daemon)
SKIP: docker_cli_ps_test.go:642: DockerSuite.TestPsNotShowPortsOfStoppedContainer (Test requires a Linux daemon)
SKIP: docker_cli_ps_test.go:417: DockerSuite.TestPsRightTagName (Test requires a Linux daemon)
SKIP: docker_cli_ps_test.go:490: DockerSuite.TestPsWithSize (Test requires a Linux daemon)
SKIP: docker_cli_by_digest_test.go:347: DockerRegistrySuite.TestPsListContainersFilterAncestorImageByDigest
OK: 9 passed, 10 skipped
--- PASS: Test (88.84s)
PASS
ok      _/E_/go/src/github.com/docker/docker/integration-cli    89.006s
```

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Fascinating. Linux busybox doesn't have `sleep`. Huh.

**Comment by StefanScherer** [comment]
@jhowardmsft It's a "busy" box, it doesn't sleep :laughing:

**Comment by jhowardmsft** [comment]
Fixed.

**Comment by thaJeztah** [comment]
Same question here as in https://github.com/docker/docker/pull/19604#discussion_r50629385; Wondering if replacing `top` with `sleep` could bring unwanted side-effects, given that they ware replaced with `top` especially to fix some test inconsistencies

**Comment by jhowardmsft** [comment]
@thaJeztah Same answer: https://github.com/docker/docker/pull/19604#discussion_r50629526

**Comment by duglin** [comment]
LGTM

**Comment by icecrime** [comment]
This makes me think that we should perhaps have a helper test function to run a "infinitely blocking" container that would be system dependent but still LGTM.

**Pull request merged**
