### PR TITLE
LCOW: Prefer Windows over Linux in a manifest list

### PR DESCRIPTION
**Pull request by johnstep**
When a manifest list contains both Linux and Windows images, always prefer Windows when the platform OS is unspecified. Also, filter out any Windows images with a higher build than the host, since they cannot run.

Signed-off-by: John Stephens <johnstep@docker.com>

See https://github.com/moby/moby/pull/37350#pullrequestreview-132641898 for details.

### CODE REVIEW

**Comment by johnstep** [comment]
No, this was an accidental regression. The comparison function did not handle a mixture of Linux and Windows in the filtered list, and only looked for an exact match by build number, which would have already been preferred over Linux. This change is for the Hyper-V case, where there is a Windows match, but the build number is lower than the host; it can still run in a Hyper-V container (Docker for Windows), so it should still be preferred over the Linux image.

Note that Linux was not _explicitly_ preferred before, but rather whatever came first in the manifest list was preferred, if no exact match. This change allows for more predictable and expected default behavior. One can argue about giving the manifest author control, but a user can always override with the `platform` switch, and the defaults should provide a consistent experience.

PS: For Windows Server with Hyper-V _disabled_, there is still the issue of pulling a Windows image that cannot run, when an exact build match is not found, but LCOW also requires Hyper-V, so no image in the manifest list will run. It might be worth considering failing instead of pulling, but the pull could be happening as part of setting up a system, and perhaps Hyper-V will become available after restarting. Therefore, it seems safest to leave that alone for now.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by clnperez** [comment]
Out of curiosity, is the platform os ever unspecified on anything other than windows? (Im assuming that means host-side)

**Review by lowenna — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@clnperez you mean if images can have an empty OS field?

**Comment by clnperez** [comment]
@thaJeztah no, i was trying to figure out where an empty os field could be. never in am image on the registry iiuc, or in a manifest list, so it seemed like the only other place was on the client/engine itself

**Pull request merged**
