### PR TITLE
Fix vendoring for fluent-logger-golang

### PR DESCRIPTION
**Pull request by LK4D4**
Done just by running hack/vendor.sh

### CODE REVIEW

**Comment by thaJeztah** [comment]
is this for 1.8?

**Comment by LK4D4** [comment]
@thaJeztah Don't think that it will change much for release, so maybe easier to skip.

**Comment by icecrime** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

backlog on janky, setting to ready-for-merge, this will be good once janky runs.

**Pull request merged**
