### PR TITLE
update service create/update docs

### PR DESCRIPTION
**Pull request by thaJeztah**
adds the 'registry-auth' flag, and removes the 'mode'
flag.

relates to https://github.com/docker/docker/pull/23584

### CODE REVIEW

**Comment by aaronlehmann** [comment]
We should probably have a long description of the `--registry-auth` option underneath with a frank discussion of the security impacts. It should explain that when this option is used, the pull credentials (which may contain the registry password) are copied to any agent where the service is scheduled. We should recommend against running the swarm without a join secret.

It should also point out that running `docker service update --registry-auth` will update the credentials to the current ones stored on the client.

**Comment by thaJeztah** [comment]
We can expand on this; however, if we want to have a two-line description for a flag, it should be in the `--help` output as well, not sure how that works with Cobra (?)

/cc @sfsmithcha

**Comment by aaronlehmann** [comment]
I was of files like `swarm_init.md` that have extended descriptions of each flag below the help output. To me it would make sense to add an extended description for `--registry-auth`.

**Comment by thaJeztah** [comment]
Actually, closing this PR for now, as https://github.com/docker/docker/pull/24291 includes this change. Agreed though that we should have some more information about that flag;

**Pull request closed without merging**
