### PR TITLE
Add chmod flag

### LINKED ISSUE #34819: Proposal: Add --chmod flag to ADD/COPY commands (analogous to --chown)
**Description**
I've bumped into #34263 being merged and it hit me that `--chmod` would be nice in conjunction with this feature.

I frequently build Linux images from a Windows machine and I'm kind of annoyed with the 755 mode the added/copied files end up with.

ADD/COPY with `--chown` and `--chmod` together will be a readable and maintainable notation delivering precise control over permissions.

I'm aware of #29853, but I don't think this issue is a duplicate (that one seems to be stale).

### PR DESCRIPTION
**Pull request by reporter123**
Closes #34819
Continuation of PR #36123. Original poster seems to have lost interest and closed PR 21 days after last contact.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I guess we want to freeze the legacy builder, and to have this as a BuildKit feature?

cc @tonistiigi

**Comment by tonistiigi** [comment]
@AkihiroSuda Ideally yes. Also added chmod to https://github.com/moby/buildkit/issues/396 in case anyone wants to help with that.

**Comment by thaJeztah** [comment]
Discussing this in the maintainers meeting; and we think it's best to focus on development in BuildKit (otherwise we'd have to implement twice); let's continue the discussion over there (and on moby/buildkit#396)

**Comment by AkihiroSuda** [comment]
Implemented in moby/buildkit#1492

**Pull request closed without merging**
