### PR TITLE
Remove "mkimage.sh" and associated scripts

### PR DESCRIPTION
**Pull request by tianon**
I looked at fixing https://bugs.debian.org/969940, but these scripts haven't been materially changed in 2-3 years and better alternatives exist elsewhere, so we should probably just remove them instead.

(Consider this a request for comment from Moby maintainers and/or community members who might be using them :sweat_smile:)

IMO, it would also make sense to remove the other `mkimage-*.sh` scripts (`alpine`, 3x `arch` :exclamation:, `crux`, `pld`, `yum`), but I've been less directly involved in those so I'm not positive how much use they've seen (happy to throw them in here too if maintainers agree).

### CODE REVIEW

**Comment by cpuguy83** [comment]
Maybe a link to a reference where the better alternatives exist, or update the ones in contrib to match the better ones?

**Comment by thaJeztah** [comment]
I never used these myself; not sure how popular they are (if they're broken, probably not too popular ☺️)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
a readme/link to alternatives would perhaps be nice yes (if we have some place to put it)

**Comment by tianon** [comment]
Sorry, yes, that's what I've been struggling with -- I don't think these are good examples anymore, or even great for folks to use.  They don't have exact replacements, but functionally the idea is simply "generate some content and package it into an image via `ADD tarball /`.  For things like Fedora, CentOS, etc. the relevant release teams publish official tarballs for use in Docker / chroots.  For BusyBox, this wasn't a great way to create a BusyBox image to begin with (the result isn't exactly super useful).  For Debian, you can get away with something as simple as `debootstrap ... && tar -cC ... . | docker import`.

If we remove this completely, I'm not sure where we'd put a note about alternatives, but also I'm not sure we really should -- either our documentation or better yet each project's documentation is a better place IMO.

We do have the following note on the whole `contrib/` directory:

> The `contrib` directory contains scripts, images, and other helpful things which are not part of the core docker distribution. Please note that they could be out of date, since they do not receive the same attention as the rest of the repository.

**Review by cpuguy83 — APPROVED** [review]
Fine with @tianon's explanation.

LGTM

**Comment by tianon** [comment]
Coming back to this from a fresh thought process, another way to put my sentiment is that these scripts are unmaintained, and the ecosystem at large is mature enough now that I don't think it's necessarily our responsibility to help users find alternatives -- these were really helpful when there weren't a lot of base images available, and now we're to the point where that's not remotely accurate (lots of folks have their own special base images these days). :sweat_smile:

**Comment by thaJeztah** [comment]
Agreed; makes sense

**Comment by tianon** [comment]
Looking at this now years later, I'm even more firmly of the opinion that we should remove _all_ the `contrib/mkimage-*` scripts, if someone wanted to open a PR. :eyes: :heart:

(They're all very outdated/unmaintained now.)

I'd even go slightly further and suggest we should consider including `contrib/dockerize-disk.sh` in the culling, but I feel less strongly about that one.

**Comment by thaJeztah** [comment]
Yeah, I agree; at least, they haven't been maintained in Years; which may mean they still work, but could just as well be completely broken.

A quick look to see if I can find references to anyone using `contrib/mkimage-XXX` gives me 20 hits; https://grep.app/search?q=contrib%2Fmkimage-


The only _potentially active_ reference I could find was this one;

- https://github.com/vimagick/dockerfiles/blob/5675c4c1e5dc5c7cffc554e87a44451f13f471fb/alpine-arm/Makefile


All the other ones were either forked / inspired by, archived, or some docs linking;

- archived; https://github.com/conda-archive/conda-docker/blob/375429c4d20f8971dc66fd2b779f52abfc9d12b9/centos6-32-minimal-base/create_docker_image.sh
- fork based on; https://github.com/gliderlabs/docker-alpine/blob/25d285ff5901c40b3e655995a17ee9c4e1590af6/builder/scripts/mkimage-alpine.bash
- fork based on; https://github.com/wazuh/wazuh-packages/blob/5f5d9f521078f6fa68bcf24fba4f9831c6aa33d2/rpms/CentOS/5/i386/docker_builder.sh
- fork based on; https://github.com/rhoit/my-config/blob/5700d347cb4ea467beecda0a7b28da7ab2b0eb77/docker/mkimage-arch.sh
- docs linking to the script; https://github.com/zembutsu/docs.docker.jp/blob/b99dd15defc2e56a82018002aba50386b286a6d1/engine/userguide/eng-image/baseimages.rst
- fork based on; https://github.com/sapk/dockerfiles/blob/86dd180e9fa5e98ee2110a55b407ba8896099240/archlinux/Dockerfile
- changelog; https://github.com/docker/docs/blob/a1774fe925fa8ea1065cceb3877e67fc57967c9f/content/manuals/engine/release-notes/prior-releases.md
- archived; https://github.com/conda-archive/conda-docker/blob/375429c4d20f8971dc66fd2b779f52abfc9d12b9/centos6-32-minimal-base/create_docker_image.sh
- fork based on; https://github.com/epheo/shaddock/blob/2c27eba0c1df5fdb98233a9121cfb0c2c797c421/tests/model/utils/arch_dockerimage_basebuilder.sh
- archived; https://github.com/LCTT/TranslateProject/blob/4948360714403ebcefc3abff80dcc69ad706bf5d/published/201505/20150330%202%20Ways%20to%20Create%20Your%20Own%20Docker%20Base%20Image.md
- archived, changelog; https://github.com/docker-archive/docker-ce/blob/44a430f4c43e61c95d4e9e9fd6a0573fa113a119/components/engine/CHANGELOG.md
- archived; https://github.com/docker-archive/leeroy/blob/e1d2556ecf85d11d5b739b300928fcae641c51aa/github/pull_request_test.go
- fork based on; https://github.com/hepsw/docks/blob/1ef30a922a6df692a193a318b6cf7828c00fe6de/mkimage-slc5.sh
- fork based on; https://github.com/hepsw/docks/blob/1ef30a922a6df692a193a318b6cf7828c00fe6de/mkimage-slc.sh
- docs linking to the script; https://github.com/CoinXu/blog/blob/952b87bbf07fda877de8c8d68cb32a88908a26b4/tools/docker/4-2-create-a-base-image.md
- archived; https://github.com/hypriot/rpi-alpine-scratch/blob/adbd320c195ffe368cc00c8496ca4da7b31f703c/.drone.yml
- docs refering (in comment); https://github.com/YahuiWong/docker-ss-tproxy/blob/bab18708cbf522aa1d43f4a47f63c7c2b6b9e639/README.md
- archived, changelog; https://github.com/rancher/docker-from-scratch/blob/084910d99b12408467a559f338e5a27bf4a1aed3/vendor/github.com/docker/docker/CHANGELOG.md

**Comment by thaJeztah** [comment]
So, yeah, I think it should be safe to just ditch those scripts.

**Comment by thaJeztah** [comment]
- opened a PR to remove them; https://github.com/moby/moby/pull/50297

**Pull request merged**
