### PR TITLE
Custom login logics: Azure container registry allows retrieving access token as username/password

### PR DESCRIPTION
**Pull request by shhsu**
**- What I did**
The motivation of this feature is to allow user of Azure Container Registry to perform a device login with Azure Active Directory (AAD). The user would optionally not need to provide username and password and the login would be done with a token obtained from AAD.

```
>docker login peterhsuaadacr-microsoft.azurecr.io
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code B2BQTS7A2 to authenticate.
Login Succeeded
```

**- How I did it**
When calling `docker login`, if the username and password are not provided but the serverAddress is present, we would try and detect if the registry can perform custom login workflow. In the case of ACR, we verify the host domain. If the domain is verified to be ACR, the custom device login and access token retrieval logic is performed. The result of these operation would be passed back to the login workflow as an `AuthConfig` object

**- How to verify it**
I manually verified by running docker login on my AAD enabled registry.
I also checked and the username/password scenario didn't break for
1. github itself
2. an AAD enabled registry
3. an azure docker registry that does not have AAD enabled

**- Description for the changelog**
{f36b3d150} Initial commit

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Why not implement this as 3rd party helper?
https://github.com/docker/docker-credential-helpers

**Comment by thaJeztah** [comment]
Yes, this looks like something the credentials-helpers were designed for

**Comment by shhsu** [comment]
@Sajay Antony
@sivagms

**Comment by shhsu** [comment]
/cc @jhowardmsft

Note: re-discussing our requirements. We will look at the possibility to move the AAD specific logic out to an external executable like `docker-login-aad.exe`

**Comment by shhsu** [comment]
I have now changed the logic considerably. The user would now configure custom login logic via `config.json` like the following:

```
{
	"registry-auth-config": [
		{
			"login-module": "acr",
			"condition-server": "*.azurecr.io",
			"condition-type": "Bearer",
			"condition-realm": "https://*.azurecr.io/oauth2/token",
		}
	]
}
```

In the case where user did not provide username or password, docker would still hit the url `https://{registry}/v2` and receives a challenge with status 401. docker would then read the `Www-authenticate` header and determine the challenge type and parameters. docker would then try to dispatch the login request to the specified `docker-login-{login-module}` executable file based on the criteria that the config file specifies. The criteria can be based on the challenge type (Bearer. Basic), challenge Realm, or login server url.

With the above example, if a request is made to any registry with address `*.azurecr.io`, and the challenge type is `Bearer` and the challenge realm is `https://*.azurecr.io/oauth2/token`, docker would call `docker-login-acr.exe` to perform the login. It would pass the entire content of `Www-authenticate` header and the login server address to the submodule as parameter. The callee is responsible to reply with an object populated with `Username`, `Password` and `ServerAddress` for docker to perform the final login.

Optionally, the login module can also bail out by passing back empty username and password to ask docker to do a prompt for username and password. This is for backward compatibility.

**Comment by shhsu** [comment]
Since the login logic has drastically changed on moby. I will prepare a new PR that suits the new code

**Comment by shhsu** [comment]
Note that I didn't merge the code. Moving the code to another branch and tried to rebase this branch results in the system thinking I merged. A new PR will be created to replace this one

**Pull request closed without merging**
