### PR TITLE
update copyrights to 2015

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux vieux@docker.com

### CODE REVIEW

**Comment by crosbymichael** [comment]
sdalfj

failed drone

**Comment by vieux** [comment]
this is why we all love goimport :D

**Comment by vieux** [comment]
should be good now

**Comment by jfrazelle** [comment]
LGTM

**Comment by vieux** [comment]
ping @SvenDowideit @fredlf for the doc change

**Comment by tiborvass** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by fredlf** [comment]
Why no docs LGTMs?

**Pull request merged**
