### PR TITLE
Check alternate os release files in Red Hat derivatives.

### LINKED ISSUE #13880: Cannot get OS name in centos 6
centos 6 do not has file /etc/os-release. So can not get name

### PR DESCRIPTION
**Pull request by calavera**
Fixes #13880

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
-1 on this, we thought a lot about it and we deliberately decided not to include other files. /etc/os-release is becoming standard, and we want to push for that. This is how we managed to get Amazon Linux adopt /etc/os-release. So let's do the same for CentOS :) I'm willing to open a bug on their site.

**Comment by calavera** [comment]
@tiborvass It's not more about future releases but about old releases that we support. I believe CentOS 7 uses /etc/os-release, but who knows.

I'm also okay with not doing this, fwiw, but I thought it would be easy to implement. I didn't know this was a deliberated decision.

**Comment by tiborvass** [comment]
@calavera no problem it's totally understandable :)

CentOS 6.6 is still maintained as far as i know, so we should be able to file a bug there.

**Comment by lsm5** [comment]
I doubt centos6 would include /etc/os-release unless rhel6 starts including it. But @kbsingh and @jperrin might have a more informed response.

**Comment by kbsingh** [comment]
hi guys,

@lsm5 thanks for the ping. 

We can certainly look at adding an os-release to CentOS-6 as well.
Note: 6.6 is just a point in time snapshot of CentOS-6; ideally we should refer to the distro as CentOS-6 as this is something we'd carry through the life of CentOS-6 if it gets in, 6.6 on the other hand is deprecated in another 3 months.

@tiborvass if you can file a bug report at https://bugs.centos.org, against CentOS-6 and component centos-release, lets take it from there.

**Comment by tiborvass** [comment]
@lsm5 @kbsingh thanks guys! What category is this? I put OTHER for now but if there is a better category let me know.

**Comment by tiborvass** [comment]
There I filed https://bugs.centos.org/view.php?id=8894. Closing PR

**Pull request closed without merging**
