### PR TITLE
check-config.sh: add NETFILTER_XT_MARK

### PR DESCRIPTION
**Pull request by fff7d1bc**
Points out another symbol that Docker might need. in this case Docker's
mesh network in swarm mode does not route Virtual IPs if it's unset.

From /var/logs/docker.log:
    time="2021-02-19T18:15:39+01:00" level=error msg="set up rule failed, [-t mangle -A INPUT -d 10.0.1.2/32 -j MARK --set-mark 257]:  (iptables failed: iptables --wait -t mangle -A INPUT -d 10.0.1.2/32 -j MARK --set-mark 257: iptables v1.8.7 (legacy): unknown option \"--set-mark\"\nTry `iptables -h' or 'iptables --help' for more information.\n (exit status 2))"

Bug: https://github.com/moby/libnetwork/issues/2227
Bug: https://github.com/docker/for-linux/issues/644
Bug: https://github.com/docker/for-linux/issues/525

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Looks like the commit message is missing a DCO sign-off, which makes CI fail; https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

When updating, please amend the existing commit (single commit for the pull request should be ok); let me know if you need help making those changes

**Comment by slashbeast** [comment]
Thanks for pointing it out, updated with gpg signed commit.

**Comment by thaJeztah** [comment]
> Thanks for pointing it out, updated with gpg signed commit.

Thanks! gpg signing is optional, but the "signed-off-by" line is the one that's checked on

Is see DCO check is happy now, thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tianon ptal <3

**Review by tianon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
