### PR TITLE
Remove in memory libcontainer containers map

### PR DESCRIPTION
**Pull request by crosbymichael**
This removes the in memory map and makes the libcontainerd code bind to containerd is a more conventional way.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Janky / Experimental

```
21:39:06 PASS: docker_cli_proxy_test.go:23: DockerDaemonSuite.TestCLIProxyProxyTCPSock	0.539s
21:44:06 --- FAIL: Test (2364.68s)
21:44:06 panic: DockerDaemonSuite.TestCleanupMountsAfterDaemonAndContainerKill test timed out after 5m0s [recovered]
21:44:06 	panic: DockerDaemonSuite.TestCleanupMountsAfterDaemonAndContainerKill test timed out after 5m0s
```

Power / Z (interestingly; those don't seem to be timing out the individual test after 5 minutes):

```
21:31:15 PASS: docker_cli_proxy_test.go:23: DockerDaemonSuite.TestCLIProxyProxyTCPSock	0.554s
01:21:28 Build timed out (after 300 minutes). Marking the build as failed.
01:21:28 Build timed out (after 300 minutes). Marking the build as aborted.
```

**Comment by crosbymichael** [comment]
@thaJeztah look at the daemon log for janky, its 60GB+

**Comment by thaJeztah** [comment]
This is the last bit of the s390x test-logs (in case it helps);

```
time="2019-03-25T21:31:14Z" level=debug msg="serving api on unix socket" socket="[inherited from parent]" 
time="2019-03-25T21:31:14.335086810Z" level=debug msg="garbage collected" d=1.567714ms 
time="2019-03-25T21:31:14.474735963Z" level=debug msg="event published" ns=moby topic="/tasks/create" type=containerd.events.TaskCreate 
time="2019-03-25T21:31:14.475104069Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/create
time="2019-03-25T21:31:14.475179759Z" level=error msg="failed to process event" container=9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e error="no such container: 9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e" event=create event-info="{9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e 9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e 5958 0 0001-01-01 00:00:00 +0000 UTC false <nil>}" module=libcontainerd namespace=moby
time="2019-03-25T21:31:14.495274373Z" level=debug msg="event published" ns=moby topic="/tasks/start" type=containerd.events.TaskStart 
time="2019-03-25T21:31:14.496286123Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/start
time="2019-03-25T21:31:14.496336100Z" level=error msg="failed to process event" container=9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e error="no such container: 9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e" event=start event-info="{9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e 9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e 5958 0 0001-01-01 00:00:00 +0000 UTC false <nil>}" module=libcontainerd namespace=moby
time="2019-03-25T21:31:14.588644109Z" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit 
time="2019-03-25T21:31:14.588867014Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/exit
time="2019-03-25T21:31:14.588923196Z" level=error msg="failed to process event" container=9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e error="no such container: 9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e" event=exit event-info="{9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e 9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e 5958 0 2019-03-25 21:31:14.570435895 +0000 UTC false <nil>}" module=libcontainerd namespace=moby
time="2019-03-25T21:31:14.620794836Z" level=info msg="shim reaped" id=9505d6e8d3a90a8df83902aa73fb5d534bca60aa62e56f0b6ea260542b4e7e1e 
time="2019-03-25T21:31:14.630561326Z" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete 
time="2019-03-25T21:31:14.630765629Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/delete
time="2019-03-25T21:31:14.630783073Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
time="2019-03-25T21:31:14.634730087Z" level=debug msg="event published" ns=moby topic="/containers/delete" type=containerd.events.ContainerDelete 
time="2019-03-25T21:31:15.037830415Z" level=debug msg="Calling GET /v1.40/containers/json?all=1&filters=%7B%22status%22%3A%7B%22paused%22%3Atrue%7D%7D&limit=0"
time="2019-03-25T21:31:15.038310520Z" level=debug msg="Calling GET /v1.40/containers/json?all=1&limit=0"
time="2019-03-25T21:31:15.038706425Z" level=debug msg="Calling GET /v1.40/images/json"
time="2019-03-25T21:31:15.041332234Z" level=debug msg="Calling GET /v1.40/volumes"
time="2019-03-25T21:31:15.041358201Z" level=debug msg=VolumeStore.Find ByType=service.CustomFilter ByValue=0x110ad4300
time="2019-03-25T21:31:15.042132845Z" level=debug msg="Calling GET /v1.40/networks"
time="2019-03-25T21:31:15.042883206Z" level=debug msg="Calling GET /v1.40/plugins"
time="2019-03-25T21:31:15.616323267Z" level=debug msg="Calling GET /v1.40/containers/json?all=1&filters=%7B%22status%22%3A%7B%22paused%22%3Atrue%7D%7D&limit=0"
time="2019-03-25T21:31:15.616665464Z" level=debug msg="Calling GET /v1.40/containers/json?all=1&limit=0"
time="2019-03-25T21:31:15.616921549Z" level=debug msg="Calling GET /v1.40/images/json"
time="2019-03-25T21:31:15.619305025Z" level=debug msg="Calling GET /v1.40/volumes"
time="2019-03-25T21:31:15.619336132Z" level=debug msg=VolumeStore.Find ByType=service.CustomFilter ByValue=0x110ad4300
time="2019-03-25T21:31:15.619817565Z" level=debug msg="Calling GET /v1.40/networks"
time="2019-03-25T21:31:15.620349710Z" level=debug msg="Calling GET /v1.40/plugins"
time="2019-03-25T21:31:16.136823273Z" level=debug msg="Calling GET /v1.40/images/get?names=busybox%3Alatest"
time="2019-03-25T21:31:16.137245685Z" level=debug msg="CreateV1ID {\"architecture\":\"s390x\",\"config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"ArgsEscaped\":true,\"Image\":\"sha256:1a7eb4a865a7c853e6c79072f53f4d568ca71f8f9c978858b6999400e4101cad\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"43993a255bacf17c7dcbe3bca72a4d01f34f3ab03e229153ca07f3dd2e75b44e\",\"container_config\":{\"Hostname\":\"43993a255bac\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"sh\\\"]\"],\"ArgsEscaped\":true,\"Image\":\"sha256:1a7eb4a865a7c853e6c79072f53f4d568ca71f8f9c978858b6999400e4101cad\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2017-11-02T08:18:28.648547045Z\",\"docker_version\":\"17.06.1-ce\",\"layer_id\":\"sha256:9e8a9a5f2215360420e8ec8da77e61b2512dd80f864957a0dacaa1c8fa58b8fe\",\"os\":\"linux\"}"
time="2019-03-25T21:31:16.137482498Z" level=debug msg="Assembling tar data for 3bde9804504f03ecf736a618aa81f611e295af4cf1aaaafe985ba770105a4b7b"
time="2019-03-25T21:31:16.534097265Z" level=debug msg="event published" ns=moby topic="/containers/create" type=containerd.events.ContainerCreate 
time="2019-03-25T21:31:16.542976310Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a/shim.sock" debug=true pid=6241 
time="2019-03-25T21:31:16Z" level=debug msg="registering ttrpc server" 
time="2019-03-25T21:31:16Z" level=debug msg="serving api on unix socket" socket="[inherited from parent]" 
time="2019-03-25T21:31:16.906495777Z" level=debug msg="event published" ns=moby topic="/tasks/create" type=containerd.events.TaskCreate 
time="2019-03-25T21:31:16.907231456Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/create
time="2019-03-25T21:31:16.907305504Z" level=error msg="failed to process event" container=649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a error="no such container: 649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a" event=create event-info="{649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a 649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a 6259 0 0001-01-01 00:00:00 +0000 UTC false <nil>}" module=libcontainerd namespace=moby
time="2019-03-25T21:31:16.923948950Z" level=debug msg="event published" ns=moby topic="/tasks/start" type=containerd.events.TaskStart 
time="2019-03-25T21:31:16.924274322Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/start
time="2019-03-25T21:31:16.924363763Z" level=error msg="failed to process event" container=649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a error="no such container: 649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a" event=start event-info="{649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a 649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a 6259 0 0001-01-01 00:00:00 +0000 UTC false <nil>}" module=libcontainerd namespace=moby
time="2019-03-25T21:31:17.375662852Z" level=debug msg="event published" ns=moby topic="/tasks/exit" type=containerd.events.TaskExit 
time="2019-03-25T21:31:17.377665435Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/exit
time="2019-03-25T21:31:17.377764624Z" level=error msg="failed to process event" container=649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a error="no such container: 649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a" event=exit event-info="{649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a 649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a 6259 143 2019-03-25 21:31:17.348966 +0000 UTC false <nil>}" module=libcontainerd namespace=moby
time="2019-03-25T21:31:17.425173253Z" level=info msg="shim reaped" id=649feb44257a0b019cd7f45b73261ac82acd74c1a7db28bfe2484949b53fbd3a 
time="2019-03-25T21:31:17.434868712Z" level=debug msg="event published" ns=moby topic="/tasks/delete" type=containerd.events.TaskDelete 
time="2019-03-25T21:31:17.435019483Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/delete
time="2019-03-25T21:31:17.435046717Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
time="2019-03-25T21:33:30.691156576Z" level=debug msg="clean 45 unused exec commands"
```

**Comment by thaJeztah** [comment]
Logs of the powerpc run; https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/13837/console

```
time="2019-03-27T19:05:49.556836094Z" level=debug msg="Calling POST /v1.40/plugins/test/enable?timeout=30"
time="2019-03-27T19:05:49.558943639Z" level=debug msg="bundle dir created" bundle=/run/docker/plugins/6da598978f0f98980cc1df35a56658d3b6d0ad22de832f2a2f54b33ef469b9ca module=libcontainerd namespace=plugins.moby root=/go/src/github.com/docker/docker/bundles/test-integration/d288c678baf32/root/plugins/6da598978f0f98980cc1df35a56658d3b6d0ad22de832f2a2f54b33ef469b9ca/rootfs
time="2019-03-27T19:05:49.736262849Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unknown\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/errdefs.init.ializers\n\t/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs/errors.go:39\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:188\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_ppc64x.s:856" error_type="*errors.fundamental" module=api
time="2019-03-27T19:05:49.736340519Z" level=error msg="Handler for POST /v1.40/plugins/test/enable returned error: failed to start io pipe copy: containerd-shim: opening init-stdout failed: open init-stdout: no such file or directory: unknown"
time="2019-03-27T19:05:49.736521010Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unknown\ngithub.com/docker/docker/vendor/github.com/containerd/containerd/errdefs.init.ializers\n\t/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs/errors.go:39\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:188\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_ppc64x.s:856" error_type="*errors.fundamental" module=api
time="2019-03-27T19:05:49.737268201Z" level=info msg="Processing signal 'interrupt'"
time="2019-03-27T19:05:49.737474316Z" level=debug msg="daemon configured with a 15 seconds minimum shutdown timeout"
time="2019-03-27T19:05:49.737515672Z" level=debug msg="start clean shutdown of all containers with a 15 seconds timeout..."
time="2019-03-27T19:05:49.738003917Z" level=debug msg="Unix socket /tmp/dxr/d288c678baf32/libnetwork/1f2b89b2381bbfd537699813aa7c109965e74d07f249f9dc3717babb83bf8a2b.sock doesn't exist. cannot accept client connections"
time="2019-03-27T19:05:49.738073622Z" level=debug msg="Cleaning up old mountid : start."
time="2019-03-27T19:05:49.738130392Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
time="2019-03-27T19:05:49.738586326Z" level=debug msg="Cleaning up old mountid : done."
time="2019-03-27T19:05:49.738906591Z" level=debug msg="Clean shutdown succeeded"
time="2019-03-27T19:05:49.738973282Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
```

Cleaning up the error-message;

```
github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs.init.ializers
	/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/errdefs/errors.go:39
runtime.main
	/usr/local/go/src/runtime/proc.go:188
runtime.goexit
	/usr/local/go/src/runtime/asm_ppc64x.s:856
```

This looks funny: `errdefs.init.ializers`, but not much info there [`/usr/local/go/src/runtime/proc.go:188`](https://github.com/golang/go/blob/go1.12.1/src/runtime/proc.go#L188), [`/usr/local/go/src/runtime/asm_ppc64x.s:856`](https://github.com/golang/go/blob/go1.12.1/src/runtime/asm_ppc64x.s#L856)


I do notice that that socket path is 104 characters long (but I _think_ that's exactly the maximum length?); 

```
Unix socket /tmp/dxr/d288c678baf32/libnetwork/1f2b89b2381bbfd537699813aa7c109965e74d07f249f9dc3717babb83bf8a2b.sock doesn't exist. cannot accept client connections
```

**Comment by crosbymichael** [comment]
Experimental is failing on everything right now.  I think this is good to go for review

**Review by dmcgowan — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Has experimental been timing out for each of these runs or just different errors?

**Comment by crosbymichael** [comment]
timeouts, it maybe legit, other prs recently are failing on it so idk

**Comment by thaJeztah** [comment]
Linting failure;

```
22:15:07 libcontainerd/types/types.go:65:6:warning: exported type Process should have comment or be unexported (golint)
22:15:07 daemon/util_test.go:29:2:warning: wrong number of return values (want 4, got 3) (gosimple)
```

**Comment by thaJeztah** [comment]
@crosbymichael needs a rebase now, likely because your other PR was merged

**Comment by crosbymichael** [comment]
Everything is good now

**Comment by crosbymichael** [comment]
rs5-process is ci failures and its not re-triggering

**Comment by thaJeztah** [comment]
😞 yeah, for some reason it won't trigger through labels (it works if you use `rebuild/*`); I triggered it manually in Jenkins

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
