### PR TITLE
Ignore Intellij based IDE project settings

### PR DESCRIPTION
**Pull request by stevedotmt**
IDEs that are based on [intellij](https://www.jetbrains.com/idea/) such
as [GoLand](https://www.jetbrains.com/go/) create a `.idea` to save
local settings for the user.

Add the `.idea` folder to prevent users from accidentally committing it.

**- What I did**
Ignore Intellij based IDE project settings
**- How I did it**
Add `.idea` to `.gitignore`
**- How to verify it**
```
touch .idea/test
git status -s
```

**- Description for the changelog**
Ignore Intellij based IDE project settings

**- A picture of a cute animal (not mandatory but encouraged)**
[Cute penguin 🐧 ](http://www.awesomelycute.com/gallery/2015/05/cute-baby-penguin-8.jpg)

### CODE REVIEW

**Comment by cpuguy83** [comment]
This should go into your global gitignore.

**Comment by steveazz** [comment]
> This should go into your global gitignore.

@cpuguy83 I do get that, but not everyone has that setup locally, and it's one more thing the developer has to remember to do.

That being said you can close this PR if you disagree 🚀

**Comment by AkihiroSuda** [comment]
Thanks for contribution, but I agree with @cpuguy83.
Let me close this PR.

**Comment by steveazz** [comment]
Thank you 🙇

**Pull request closed without merging**
