### PR TITLE
[1.12.x] added date after version number in changelog

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Add date after version in `CHANGELOG.md` so RPMs can generate their changelog from it. With out this PR, RPMs fail to build.

**- How I did it**

In my pajamas.

**- How to verify it**

See that the version line in the CHANGELOG.md now has the date in parenthesis after the version number.

**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

🛌

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

take into account that we need to update this once a definitive date is known (it's just a "placeholder" now)

**Review by vdemeester — CHANGES_REQUESTED** [review]
Should we make sure it's a placeholder then ? (by putting an absolute wrong date or something else ?)
@thaJeztah @andrewhsu

**Comment by andrewhsu** [comment]
@vdemeester I think putting a date of today and updating it for GA should be good enough. We should keep a procedure of always making sure date is correct when releasing.

If there is a chance that the date is not updated, worst case is it is released with a close-to-correct date. If we put an absolutely wrong date, worst case is it is released with an absolutely wrong date.

**Comment by vieux** [comment]
LGTM

**Pull request merged**
