### PR TITLE
Unify API-version checks

### PR DESCRIPTION
**Pull request by thaJeztah**
Just a minor nit / code-cleanup

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by olljanat** [comment]
Derek add label: rebuild/windowsRS5-process

**Comment by olljanat** [comment]
Derek remove label: rebuild/windowsRS5-process

**Comment by thaJeztah** [comment]
@olljanat I think the current trick to restart WindowsRS5 is to use `rebuild/*` (which restarts all the jobs that failed)

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
> not sure if I can say so but I just did 😃

@olljanat Yes, you can leave a LGTM, and maintainers can take non-maintainer LGTM's into account 👍 more eyes is always better, and _reviewing can be done by anyone_ (and is greatly appreciated 🤗)

In general, the rule is to have two _maintainer_ LGTM's before we either _merge_  (or move a pull request to the `status/4-merge` stage).

It's really a matter of trust; a maintainer could decide that a trivial change does not require another reviewer, and merge with a single LGTM (or "count" non-maintainer LGTM's). The opposite can also happen; a maintainer seeing a non-trivial change, and asking more contributors/maintainers to review / LGTM before merging.

In this case, the change was fairly trivial (and non-risky), but be cautious with moving a PR to `status/4-merge`, as there _may_ have been a reason a maintainer did not move it to that state yet (in case of doubt; feel free to "ping" either on GitHub or Slack)

**Comment by AkihiroSuda** [comment]
> It's really a matter of trust; a maintainer could decide that a trivial change does not require another reviewer, and merge with a single LGTM (or "count" non-maintainer LGTM's). 

Can we more clearly mention this in the MAINTAINERS file?

**Comment by thaJeztah** [comment]
I think it's a bit of an unwritten rule, but we could add some more information about the maintainers taking responsibility for making the _right_ decisions. The official process is in https://github.com/moby/moby/blob/b80472cef449d900ca9496d97e1527556ff6a04f/project/REVIEWING.md#code-review---status2-code-review (and bits in https://github.com/docker/opensource/blob/ed974a99af0ae96e8ada7300fe2ce877f3444862/MAINTAINERS, but there's definitely parts in there that need an update / are outdated).

I'm not sure if I have time myself soon to work on making those changes (I can try), but if someone else has ideas / proposals, I'm happy to help

**Pull request merged**
