### PR TITLE
Add missing debug client mode info in docs.

### PR DESCRIPTION
**Pull request by calavera**
We added that information in #19901 but I forgot to add it to the docs, sorry :pensive:

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
Oh! Wasn't aware it was added to the output

LGTM

**Comment by calavera** [comment]
This didn't make it in the release, I don't think we have to cherry pick, do we?

**Comment by thaJeztah** [comment]
@calavera oh! Good catch, I thought it was (in the release)

**Pull request merged**
