### PR TITLE
Fix output for inspect non exist container

### PR DESCRIPTION
**Pull request by hqhq**
Before:
$ docker inspect adsf
Error: No such image or container: adsf
[]

After:
$ docker inspect adsf
Error: No such image or container: adsf

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by runcom** [comment]
SGTM

**Comment by duglin** [comment]
This was discussed before and sadly I don't think we can change this. Since you can specify more than one image/container you can get both an error message and the json output.  Weird I know.  But that means its valid to get `[ ]` because someone may be piping the output to a json processor.
See https://github.com/docker/docker/pull/9500

**Comment by runcom** [comment]
oh this https://github.com/docker/docker/pull/9500#issuecomment-65846734 makes sense..

**Comment by hqhq** [comment]
Yeah, I see, thank for that info. Closing this...

**Comment by thaJeztah** [comment]
@hqhq @duglin could one of you create a pull-request that adds a comment to that code, explaining *why* it should stay as-is (you can add a reference to https://github.com/docker/docker/pull/9500#issuecomment-65846734)

Given that it's the *second* time someone tries to improve this, I think a comment should be added

**Comment by hqhq** [comment]
@thaJeztah @duglin I was trying to add this comment, then I realized that `docker inspect -f` doesn't return array, if we write that comment, people would confuse about that (inspect always return array).

If we change code to let `inspect -f` return array, that'll break `inspectField` and many other test cases and even user applications. So I'm not sure that's worth do to.

Now I start thinking maybe we should reopen this, cause keep `inspect` return array doesn't seem necessary and fully correct.

**Comment by duglin** [comment]
@hqhq I think its ok for the comment to say that the results are returned as an array **when** `-f` isn't specified.

**Pull request closed without merging**
