### PR TITLE
fix image delete problem

### LINKED ISSUE #12135: docker image delete problem
The days I was study on the docker source code,mainly about the deleting of images.I think I  found some problems,and I will explain in examples:

Image `ubuntu:14.11`(just for test) and `ubuntu:14.12`  have the same image id:
screen shot 2015-04-07 at 4 31 20 pm

Start a container from image `ubuntu:14.11`:
screen shot 2015-04-07 at 4 32 48 pm

Delete image with it's short id :
screen shot 2015-04-07 at 4 35 05 pm

no errors while the container is still running

ENV:
ubuntu:14.04, docker 1.5.0 ,driver:aufs

### PR DESCRIPTION
**Pull request by hangyan**
fixes #12135

Signed-off-by: Hang Yan yanhangyhy@gmail.com

### CODE REVIEW

**Comment by hangyan** [comment]
I checked the console output,tagging the same images multiple times then removing,if there are still containers using it,i think it's reasonable to fail.

**Comment by thaJeztah** [comment]
Is this solving the same issue as https://github.com/docker/docker/pull/11058 ?

**Comment by icecrime** [comment]
@hangyan Thanks for the contribution! However, one of the integration tests is failing:

```
--- FAIL: TestRmiTagWithExistingContainers (0.37s)
	docker_cli_rmi_test.go:94: Could not remove tag busybox:newtag: exit status 1: Error response from daemon: Conflict, cannot delete 4986bf8c1536 because the container b10758f84ffb is using it, use -f to force
		time="2015-04-08T01:58:07Z" level=fatal msg="Error: failed to remove one or more images"
```

**Comment by hangyan** [comment]
@icecrime I saw it,but i don't think the logic it's right. An image id mapping to one repo and multiple tags,if there are containers running (or not) , the image should not be deleted.

**Comment by jfrazelle** [comment]
this is removing something I had added in https://github.com/docker/docker/pull/7963, so I will take a look tomorrow

**Comment by jfrazelle** [comment]
the image delete code definitely needs a refactor tho because I remember the headache I head the first time around

**Comment by jfrazelle** [comment]
also adding an integration test to this, for the exact problem it is fixing would be great

**Comment by x1022as** [comment]
This pr is working on different things with #11058 . 

I have tested this pr locally. It works fine except:
    if I have tagged imageID to `busybox:latest` `busybox:test` ... , if `run` with one of them, neither one can be `rmi`. Not sure if this is reasonable.

This is what official docker act, when `run` with one of the image:
    `rmi` will not fail until the last image, (even fail with '-f'  )
    `rmi -f imageID` will delete all the images successfully

**Comment by jfrazelle** [comment]
I will carry this with an integration-cli test

**Comment by jfrazelle** [comment]
closing because i cannot recreate this issue with 1.6.0 or master

**Pull request closed without merging**
