### PR TITLE
Add missing 'Names' field to /containers/json API output

### LINKED ISSUE #14675: Documentation of 'list containers' API call misses 'Names' element
When calling `GET /containers/json` the objects in the returned array contain a `Names` element with an array. This property is not documented in the [API doc](https://docs.docker.com/reference/api/docker_remote_api_v1.19/) so I wonder whether this is an official feature and one can use it without being afraid that it gets removed later ?

Also, why is this an array and no a scalar value because AFAIK a container can carry only a single name (this can be also infered from the response of 'container inspect').

### PR DESCRIPTION
**Pull request by duglin**
Closes #14675

Wasn't sure how far back I needed to go so I did just a few.

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by tiborvass** [comment]
@duglin seems like you have to go back till `1.15` was introduced in #5518.

**Comment by duglin** [comment]
@tiborvass thanks!  I was going to check on that when I got into the office.

**Comment by SvenDowideit** [comment]
LGTM

**Comment by duglin** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
LGTM

**Comment by karthikkn** [comment]
In the changes made to the file, api/docker_remote_api_v1.16.md

I believe, it should be "sleepy_dog" instead of "sleep_dog"

"Id": "3176a2479c92",
"Names":["/sleep_dog"],

**Comment by duglin** [comment]
opps, @moxiegirl did you want me to fix that?  Its not wrong, just not consistent across the versions.

**Comment by moxiegirl** [comment]
Um, should we just let sleeping dogs lie?

**Comment by duglin** [comment]
LOL fine by me

**Comment by moxiegirl** [comment]
Sorry, couldn't rest that...it is consistent internally within that particular version so I'm good with leaving it as.  Though thanks @karthikkn for the good eye.

**Pull request merged**
