### PR TITLE
Update go-check

### PR DESCRIPTION
**Pull request by hqhq**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

It includes a small improvement, we hit test timeout sometimes
for some reason, print out the timed out case would be very
helpful.

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Comment by vdemeester** [comment]
```
08:56:47 --- FAIL: Test (15890.59s)
08:56:47 panic: DockerSuite.TestEventsLimit test timed out after 4h0m0s [recovered]
08:56:47 	panic: DockerSuite.TestEventsLimit test timed out after 4h0m0s
```

It does the job :sweat_smile:

**Comment by vdemeester** [comment]
Let's merge this, win* failures are not related (and won't be affected by this one)

**Pull request merged**
