### PR TITLE
builder: add a test for `ENV name` (without `=value`)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Review by boaz0 — COMMENTED** [review]
LGTM unless performance is really important here.
regexp are very expensive. Can we use strings.Contains and strings.Split instead?

**Comment by AkihiroSuda** [comment]
@ripcurld0 

I'm not using regexp here.
Probably you tried to review another PR https://github.com/opencontainers/image-spec/pull/693?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by dnephin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Pull request merged**
