### PR TITLE
Change the systemd default back to non-socket-activation

### PR DESCRIPTION
**Pull request by tianon**
This reintroduces the `contrib/init/systemd/socket-activation` subdirectory for the "socket activation" variation of the Docker systemd service file.

In the context of "restart policies" and the Docker daemon lifecycle, socket activation, while a neat feature with solid use cases, is not a sane default for the majority of users anymore.

cc @philips @lsm5 @jfrazelle

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I'm pretty sure there are docs changes needed to go with this.

**Comment by lsm5** [comment]
LGTM

**Comment by phemmer** [comment]
I'm just curious, but why not just just enable the `docker.service` unit so that it starts by default (in addition to the `docker.socket` unit)?

One of the reasons systemd introduced the whole socket unit thing was so that service B, which depends on service A, can start up without waiting for service A to fully come up. The socket will be there, and any connection requests will just block until A finishes coming up.
So by doing this you make the startup process take longer if any other units depend on it. Not that docker takes a while to start, but I don't feel like this is the right solution.

**Comment by jfrazelle** [comment]
LGTM, we weren't really using it anyways

@phemmer we could do that too

**Comment by philips** [comment]
I like @phemmer 's suggestion. It keeps us from a needless fork of the config files.

**Comment by tianon** [comment]
I think the discussion on https://github.com/docker/docker/pull/10144 explains pretty well why I think it was a mistake to take the socket file generation out of Docker's control -- while it's nice to be able to have other service files depend on `docker.socket` to know that they have some kind of socket they can connect to, we actually lose functionality by doing so, including the ability to even tell if Docker itself is up and ready for commands without blocking.

**Comment by jfrazelle** [comment]
@phemmer @philips any comments on that

**Comment by phemmer** [comment]
The only reason I see from #10144 on why systemd should not control the socket is because when doing so, docker can't control the ownership. And I don't see this as an issue. It's neither good nor bad behavior in my opinion. Each method just has a different way of setting permissions.

> the ability to even tell if Docker itself is up and ready for commands without blocking.

Why is this necessary? If systemd is starting docker, and everything is properly depending on `docker.socket`, and is properly waiting for docker to finish starting, why do we need to know that it's still starting without blocking?
Lets say you want to start service Foo, which needs docker. With systemd `docker.socket`, the app connects and it blocks waiting. Without systemd `docker.socket`, something has to periodically poll docker to know that it's ready before starting service Foo. Polling will always be slower as docker can start responding in between polling intervals. I can't think of any scenario where having to poll would be a good thing.

**Comment by philips** [comment]
I agree with @phemmer. What part of #10144 implies things would be better if docker owned the creation of the socket file?

The root problem in this issue is restart policies don't work if Docker doesn't start. This is fixed by making Docker start in the default.target. This can be done w/o removing socket activation which has desirable traits like removing polling as @phemmer points out.

**Comment by philips** [comment]
That said if @tianon wants to split things back out I am fine doing that; I just don't see a sound argument in relation to fixing this particular bug.

**Comment by tianon** [comment]
Ok, fair enough! :+1:

Is that something you can point me to some simple hrefs for how to do in
the context of our current packages? :innocent:

**Comment by phemmer** [comment]
> Is that something you can point me to some simple hrefs for how to do

You mean how to change the `docker.service` unit to start by default? The unit already does this [here](https://github.com/docker/docker/blob/50bf3cbedc923985868bd84515460aad174dcccb/contrib/init/systemd/docker.service#L15). But for the `[Install]` section to be evaluated, something needs to enable the service. This would be up to the package maintainer or user. Basically whoever is currently calling `systemctl enable docker.socket` should instead call `systemctl enable docker.service`.
(You could modify the `docker.socket` unit to start `docker.service` when it is started, but I would consider this to be bad behavior)

**Pull request closed without merging**
