### PR TITLE
Fixed some differences between API and Docs

### LINKED ISSUE #21627: Docker 1.10 API docs on exec inspect seem wrong
**Output of `docker version`:**

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.6
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.10.3
Server API version: 1.22
Go version (server): go1.5.3
Git commit (server): 20f81dd
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
Images: 1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
CPUs: 2
Total Memory: 1.955 GiB
Name: 1.10.3-vmware
ID: NYFA:XWPO:HDL2:SDNL:LWHQ:WPS2:SU2X:IHRA:K5F3:5XJ2:RGZJ:HWTK
Debug mode (server): true
File Descriptors: 25
Goroutines: 38
System Time: 2016-03-29T19:59:33.113353448Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: dxia
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarefusion
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. do a docker exec create
2. do docker exec start
3. docker exec inspect

```
curl --insecure --cert ~/.docker/machine/machines/1.10.3-vmware/b2d-client-side.p12 --pass tcuser 'https://192.168.212.133:2376/exec/f33bbfb39f5b142420f4759b2348913bd4a8d1a6d7fd56499cb41a1bb91d7b3b/json' -vvv

*   Trying 192.168.212.133...
* Connected to 192.168.212.133 (192.168.212.133) port 2376 (#0)
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
* Client certificate: dxia
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: dxia.1.10.3-vmware
* Server certificate: dxia
> GET /exec/f33bbfb39f5b142420f4759b2348913bd4a8d1a6d7fd56499cb41a1bb91d7b3b/json HTTP/1.1
> Host: 192.168.212.133:2376
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.10.3 (linux)
< Date: Tue, 29 Mar 2016 19:47:24 GMT
< Content-Length: 379
<
{"ID":"f33bbfb39f5b142420f4759b2348913bd4a8d1a6d7fd56499cb41a1bb91d7b3b","Running":false,"ExitCode":2,"ProcessConfig":{"tty":true,"entrypoint":"sh","arguments":["-c","exit 2"],"privileged":false,"user":"1000"},"OpenStdin":true,"OpenStderr":true,"OpenStdout":true,"CanRemove":false,"ContainerID":"b53ee82b53a40c7dca428523e34f741f3abc51d9f297a14ff874bf761b995126","DetachKeys":""}
```

**Describe the results you received:**
There's only a `ContainerID` instead of the entire `Container` object as stated in the docs here https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md#exec-inspect.

**Describe the results you expected:**
The docs should correspond to the behavior.

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by senk**
fixes #21627

**\- What I did**
Fixed some return codes and example reponses to match actual API responses
**\- How I did it**
Tested Commands with local boot2docker and API Calls (attached at bottom for reference)
**\- How to verify it**
Test the api according to my references

Signed-off-by: Robin Naundorf r.naundorf@fh-muenster.de

Shell-History:

```
curl --insecure --cert ~/.docker/machine/machines/1.10.3-vmware/b2d-client-side.p12 --pass tcuser -H "Content-Type: application/json" -X POST -d '{"AttachStdin": false,"AttachStdout": true,"AttachStderr": true,"DetachKeys": "ctrl-p,ctrl-q","Tty": false,"Cmd": ["date"]}' 'https://172.16.234.135:2376/containers/592ba31846e81c5ab5480c8dfabd84061d519ade980e7b6f710503c964939d0d/exec' -vvv
*   Trying 172.16.234.135...
* Connected to 172.16.234.135 (172.16.234.135) port 2376 (#0)
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
* Client certificate: robin
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: robin.1.10.3-vmware
* Server certificate: robin
> POST /containers/592ba31846e81c5ab5480c8dfabd84061d519ade980e7b6f710503c964939d0d/exec HTTP/1.1
> Host: 172.16.234.135:2376
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 123
>
* upload completely sent off: 123 out of 123 bytes
< HTTP/1.1 201 Created
< Content-Type: application/json
< Server: Docker/1.10.3 (linux)
< Date: Wed, 30 Mar 2016 07:32:56 GMT
< Content-Length: 74
<
{"Id":"0b8c9f471a746a43781765435f80b86172ccc33b5b20504d9aca0c55a2820965"}
* Connection #0 to host 172.16.234.135 left intact


curl --insecure --cert ~/.docker/machine/machines/1.10.3-vmware/b2d-client-side.p12 --pass tcuser -H "Content-Type: application/json" -X POST -d '{"Detach": false,"Tty": false}' 'https://172.16.234.135:2376/exec/171e209b52d2623c5548295aa6d37a67b98756a62fda53051d9d8814f856e568/start' -vvv
*   Trying 172.16.234.135...
* Connected to 172.16.234.135 (172.16.234.135) port 2376 (#0)
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
* Client certificate: robin
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: robin.1.10.3-vmware
* Server certificate: robin
> POST /exec/171e209b52d2623c5548295aa6d37a67b98756a62fda53051d9d8814f856e568/start HTTP/1.1
> Host: 172.16.234.135:2376
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 30
>
* upload completely sent off: 30 out of 30 bytes
< HTTP/1.1 200 OK
< Content-Type: application/vnd.docker.raw-stream
* no chunk, no close, no size. Assume close to signal end
<
Wed Mar 30 07:34:26 UTC 2016
* Closing connection 0




curl --insecure --cert ~/.docker/machine/machines/1.10.3-vmware/b2d-client-side.p12 --pass tcuser 'https://172.16.234.135:2376/exec/171e209b52d2623c5548295aa6d37a67b98756a62fda53051d9d8814f856e568/json' -vvv
*   Trying 172.16.234.135...
* Connected to 172.16.234.135 (172.16.234.135) port 2376 (#0)
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
* Client certificate: robin
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: robin.1.10.3-vmware
* Server certificate: robin
> GET /exec/171e209b52d2623c5548295aa6d37a67b98756a62fda53051d9d8814f856e568/json HTTP/1.1
> Host: 172.16.234.135:2376
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.10.3 (linux)
< Date: Wed, 30 Mar 2016 07:35:20 GMT
< Content-Length: 369
<
{"ID":"171e209b52d2623c5548295aa6d37a67b98756a62fda53051d9d8814f856e568","Running":false,"ExitCode":0,"ProcessConfig":{"tty":false,"entrypoint":"date","arguments":[],"privileged":false,"user":""},"OpenStdin":false,"OpenStderr":true,"OpenStdout":true,"CanRemove":true,"ContainerID":"592ba31846e81c5ab5480c8dfabd84061d519ade980e7b6f710503c964939d0d","DetachKeys":"EBE="}
* Connection #0 to host 172.16.234.135 left intact


curl --insecure --cert ~/.docker/machine/machines/1.10.3-vmware/b2d-client-side.p12 --pass tcuser 'https://172.16.234.135:2376/exec/171e209b52d2623c5548295aa6d37a67b98756a62fda53051d9d8814f856e568/json' | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   369  100   369    0     0   1157      0 --:--:-- --:--:-- --:--:--  1156
{
    "CanRemove": true,
    "ContainerID": "592ba31846e81c5ab5480c8dfabd84061d519ade980e7b6f710503c964939d0d",
    "DetachKeys": "EBE=",
    "ExitCode": 0,
    "ID": "171e209b52d2623c5548295aa6d37a67b98756a62fda53051d9d8814f856e568",
    "OpenStderr": true,
    "OpenStdin": false,
    "OpenStdout": true,
    "ProcessConfig": {
        "arguments": [],
        "entrypoint": "date",
        "privileged": false,
        "tty": false,
        "user": ""
    },
    "Running": false
}
```

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮
/cc @thaJeztah

**Comment by senk** [comment]
i should fix it for v1.23 and v1.24 too

**Comment by senk** [comment]
changed it in v1.22,v1.23,v1.24

**Comment by thaJeztah** [comment]
LGTM, thanks!!

**Pull request merged**
