### PR TITLE
deb: add fish completions

### PR DESCRIPTION
**Pull request by thaJeztah**
This adds the Fish completions to the .deb package.

Relates to https://github.com/docker/docker/issues/16668

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon @jfrazelle ptal, really no idea if this is all that's needed for the .deb packages (does it automatically handle creating the target directory if it's not there?)

**Comment by jfrazelle** [comment]
Yes LGTM

**Comment by faho** [comment]
Same thing as #16668 - `pkg-config` would also work if a distribution put the path somewhere else.

**Comment by thaJeztah** [comment]
\o/ :fish:

**Pull request merged**
