### PR TITLE
fix a race in json logger reader

### PR DESCRIPTION
**Pull request by mountkin**
The json decoder starts to decode immediately a inotify event is
received.
But at the time the inotify event is trigged, the json log
entry might haven't been fully written to the disk.
In this case the decoder will return an "io.UnexpectedEOF" error, but
there is still data remaining in the decoder's buffer. And the data
should be passed to the decoder when the next inotify event is
triggered.

fixes https://jenkins.dockerproject.org/job/Windows-PRs/16236/console and https://jenkins.dockerproject.org/job/Docker-PRs/18950/console
Signed-off-by: Shijiang Wei mountkin@gmail.com

### CODE REVIEW

**Comment by mountkin** [comment]
Here is the `io.ErrUnexpectedEOF` in json decoder: https://golang.org/src/encoding/json/stream.go?s=1071:1118#L120

**Comment by cpuguy83** [comment]
Oh nice catch!
Did you by chance see this error?

**Comment by mountkin** [comment]
@cpuguy83 I can 100% reproduce the error by wrapping the body of TestRunSlowStdoutConsumer or TestLogsFollowSlowStdoutConsumer in a loop and run the integration test.

**Comment by cpuguy83** [comment]
That's really awesome!

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by mountkin** [comment]
hmm... still seeing the `io.ErrUnexpectedEOF` error after 10 (`maxJSONDecodeRetry`) retries.
Shall we increase the `maxJSONDecodeRetry` to 15 or 20? Or is there a better approach to handle the `io.ErrUnexpectedEOF` in json decoder? @cpuguy83 @LK4D4

**Comment by mountkin** [comment]
Still failing even if I increased the `maxJSONDecodeRetry` to 20.
I removed the retry counter when `io.ErrUnexpectedEOF` occurs and the test passed.
```go
        if err == io.ErrUnexpectedEOF {
          reader := io.MultiReader(dec.Buffered(), f)
          dec = json.NewDecoder(reader)
          continue
        }
```

But I'm wondering if there are chances that it falls in a dead loop :sweat:  To make it safer I think we can change `maxJSONDecodeRetry` to 20000 or so.

**Pull request merged**
