### PR TITLE
Migrate restart command to cobra

### PR DESCRIPTION
**Pull request by WeiZhang555**
part of #23211

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
@WeiZhang555 need rebase...

**Comment by WeiZhang555** [comment]
Rebased.

**Comment by vdemeester** [comment]
@WeiZhang555 needs another rebase 😅

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by thaJeztah** [comment]
LGTM, thanks @WeiZhang555

**Pull request merged**
