### PR TITLE
invalide detach keys provided

### PR DESCRIPTION
**Pull request by lixiaobing1**
invalide detach keys provided。

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
LGTM but tests need to be updated

**Comment by thaJeztah** [comment]
Yes, looks like an integration test has to be updated;

```
09:26:12 ----------------------------------------------------------------------
09:26:12 FAIL: docker_cli_run_unix_test.go:205: DockerSuite.TestRunAttachDetachFromInvalidFlag
09:26:12 
09:26:12 docker_cli_run_unix_test.go:233:
09:26:12     c.Assert(strings.TrimSpace(out), checker.Equals, errStr)
09:26:12 ... obtained string = "Invalid detach keys (ctrl-A,a) provided"
09:26:12 ... expected string = "Invalid escape keys (ctrl-A,a) provided"
09:26:12 
09:26:13 
09:26:13 ----------------------------------------------------------------------
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Comment by vieux** [comment]
LGTM

**Pull request merged**
