### PR TITLE
parsers: update comment of PartParser

### PR DESCRIPTION
**Pull request by chenhanxiao**
The original one is a little confused.

Signed-off-by: Chen Hanxiao chenhanxiao@cn.fujitsu.com

### CODE REVIEW

**Comment by duglin** [comment]
This code is just a generic parser that's meant to take a series of colon separated words as a template and then parse the incoming data per that template.  Notice this func is called from a number of places with different templates.  The comment that you're looking at is (I believe) just an example template that someone could use - its not meant to imply that its the only template (words) that should be used.  So, perhaps if there was "e.g." in front of it then it might be less confusing.  But as it is, its not technically wrong.

**Comment by duglin** [comment]
I'm inclined to close this unless you want to modify your PR to add some more comments to this function so that its clear what its doing.

**Comment by jfrazelle** [comment]
Hi @chenhanxiao I am inclined to agree with @duglin. I am sorry. We appreciate your contribution. I am sure if you are willing to still help us out, there are a bunch of places that could use this awesome attention to detail when it comes to comments :)

**Comment by chenhanxiao** [comment]
@jfrazelle @duglin 
I agree.

Thanks for you comments.

**Pull request closed without merging**
