### PR TITLE
Add Ubuntu 16.10 Yakkety Yak

### LINKED ISSUE #27521: [1.13] Add Ubuntu 16.10 "yakkety yak" debs
Ubuntu 16.10 was released https://wiki.ubuntu.com/YakketyYak/ReleaseSchedule, so we should add this to the list of supported versions for 1.13

Also should be added to the installation docs in the "vnext-engine" branch; https://github.com/docker/docker.github.io/blob/vnext-engine/engine/installation/linux/ubuntulinux.md

/cc @vieux @andrewhsu

### PR DESCRIPTION
**Pull request by thaJeztah**
Ubuntu 16.10 has been released http://releases.ubuntu.com/yakkety/

Note that this is a short-term release, so will
EOL (and removed again) in 9 months

fixes https://github.com/docker/docker/issues/27521

### CODE REVIEW

**Comment by andrewhsu** [comment]
I think some packages need to be updated:
```
$ docker build -t yy .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM ubuntu:yakkety
 ---> df4ba6fcd70e
Step 2 : RUN apt-get update && apt-get install -y apparmor bash-completion btrfs-tools build-essential curl ca-certificates debhelper dh-apparmor dh-systemd git libapparmor-dev libdevmapper-dev libltdl-dev libseccomp-dev libsqlite3-dev pkg-config libsystemd-journal-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*
 ---> Running in 375f069a549d
Get:1 http://security.ubuntu.com/ubuntu yakkety-security InRelease [93.3 kB]
...
Get:17 http://archive.ubuntu.com/ubuntu yakkety-updates/main amd64 Packages [71.7 kB]
Fetched 22.8 MB in 11s (2023 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Package libsystemd-journal-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libsystemd-dev

E: Package 'libsystemd-journal-dev' has no installation candidate
The command '/bin/sh -c apt-get update && apt-get install -y apparmor bash-completion btrfs-tools build-essential curl ca-certificates debhelper dh-apparmor dh-systemd git libapparmor-dev libdevmapper-dev libltdl-dev libseccomp-dev libsqlite3-dev pkg-config libsystemd-journal-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by thaJeztah** [comment]
@andrewhsu shucks, I'll check

**Comment by tophj-ibm** [comment]
@thaJeztah you might want to swap the logic here https://github.com/docker/docker/blob/master/contrib/builder/deb/amd64/generate.sh#L84 so it selects libsystemd-dev by default (because it's being updated) and libsystemd-journal-dev for the older distros / jessie.

**Comment by thaJeztah** [comment]
@tophj-ibm oh, thanks! yes, that would make sense :)

**Comment by thaJeztah** [comment]
@tophj-ibm @andrewhsu updated, PTAL

**Comment by tophj-ibm** [comment]
Tested on a 16.10 vm and everything worked.
LGTM

**Comment by andrewhsu** [comment]
LGTM

**Comment by mlaventure** [comment]
Successfully built.

LGTM

**Comment by vieux** [comment]
SGTM

**Comment by thaJeztah** [comment]
documentation changes in https://github.com/docker/docker.github.io/issues/504

**Pull request merged**
