### PR TITLE
Fix secret mounting with userns_remap enabled

### PR DESCRIPTION
**Pull request by jiashuChen**
# NEW COMMENT
@cpuguy83 @tonistiigi I have implemented a new solution based on the feedback from you guys, the idea now is to create a new `tmp` directory specifically for buidkit tracked by the `BUILDKIT_TMPDIR` environment variable. This tmp directory by default will live under `/var/lib/docker/buildkit/${uid}:${gid}/tmp`. This will allow secret mount to work as well as ensuring that buildkit won't have access to other content in the `/var/lib/docker/$uid}:${gid}/tmp` directory.

This change is now dependent on another pull request here https://github.com/moby/buildkit/pull/2723. I noticed that the `buildkit` version this repo currently depends on is from https://github.com/moby/buildkit/commit/9f254e18360a24c2ae47b26f772c3c89533bcbb7 which was created in 2021. I did some quick test, and I believe refactor might will be expected after the buildkit pr https://github.com/moby/buildkit/pull/2723 merges.

The current CI failure is related to vendor validation (due to using my own test version of buildkit) which can be resolved easily after https://github.com/moby/buildkit/pull/2723 is approved and merged. link to CI run https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43354/11/pipeline.

# ORIGINAL COMMENT
Related issue:

- https://github.com/moby/buildkit/issues/2087
- https://github.com/moby/buildkit/issues/2200

The previous commit here https://github.com/moby/moby/commit/bfedd2725971303efb7a2fe5d6990317b381622f modified
the owner and permission of the DOCKER_TMP to `root:root` and `700`
respectively, and it seems to have assumed that the folder is not
needed by the remapped root user, however, this is not actually the case.
E.g. container secret mounting function creates temp secret files inside
this folder.

For instance, container secrets. we observe the following error when docker daemon has
`userns_remap` configured.

```
5 [2/2] RUN 	--mount=type=secret,id=notasecret 	set -exu 	&& ls -l /run/secrets/ 	&& cat /run/secrets/notasecret
5 sha256:a16175a432881d90de1e071dc3e693eef28bc0316f31b5abc89cdf1b5598ee08
5 0.101 container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/var/lib/docker/1000.997/tmp/buildkit-secrets408149551/p6b88c12u265nm42u6whkbw18" to rootfs at "/run/secrets/notasecret" caused: stat /var/lib/docker/1000.997/tmp/buildkit-secrets408149551/p6b88c12u265nm42u6whkbw18: permission denied
5 ERROR: executor failed running [/bin/sh -c set -exu 	&& ls -l /run/secrets/ 	&& cat /run/secrets/notasecret]: exit code: 1
```

This is because when secrets are created [here](https://github.com/jiashuChen/moby/blob/03f1c3d78fabe56b7a7d550132c83b54ce666355/daemon/container_operations_unix.go#L221-L226), although the docker daemon set the secret file with remapped user and group being the owner, because this file is under the `/var/lib/docker/1000.997/` folder which is owned by host root user with permission set to `700`. the following systemcall will fail and cause the above STE error

```
newfstatat(AT_FDCWD, "/var/lib/docker/1000.997/tmp/buildkit-secrets288035449/yllcqdca15wpldnq0upgcctzu", 0xc0001e36f8, 0) = -1 EACCES (Permission denied)
```

How to replicate:
Dockerfile
```
FROM alpine:latest

RUN \
	--mount=type=secret,id=notasecret \
	set -exu \
	&& ls -l /run/secrets/ \
	&& cat /run/secrets/notasecret
```

Command:
```
NOTASECRET=no DOCKER_BUILDKIT=1 \
docker build \
    --no-cache \
    --progress plain \
    --secret id=notasecret,env=NOTASECRET \
    -t secretmounttest:latest \
    -f Dockerfile .
```

Without my change what the temp dir looks like
```
root@my-desktop:/var/lib/docker/1000.997# ls -l
total 44
drwx--x--x 4 root root   4096 Mar 10 18:15 buildkit
drwx--x--- 2 root docker 4096 Mar 10 18:15 containers
drwx------ 3 root root   4096 Mar 10 18:15 image
drwxr-x--- 3 root root   4096 Mar 10 18:15 network
drwx--x--- 3 root docker 4096 Mar 10 18:15 overlay2
drwx------ 4 root root   4096 Mar 10 18:15 plugins
drwx------ 2 root root   4096 Mar 10 18:15 runtimes
drwx------ 2 root root   4096 Mar 10 18:15 swarm
drwx------ 2 root root   4096 Mar 10 18:15 tmp
drwx------ 2 root root   4096 Mar 10 18:15 trust
drwx-----x 2 root root   4096 Mar 10 18:15 volumes
```

With my change what the temp dir looks like
```
root@my-desktop:/var/lib/docker/1000.997# ls -l
total 44
drwx--x--x 4 root root   4096 Mar 10 18:15 buildkit
drwx--x--- 2 root docker 4096 Mar 10 18:15 containers
drwx------ 3 root root   4096 Mar 10 18:15 image
drwxr-x--- 3 root root   4096 Mar 10 18:15 network
drwx--x--- 3 root docker 4096 Mar 10 18:15 overlay2
drwx------ 4 root root   4096 Mar 10 18:15 plugins
drwx------ 2 root root   4096 Mar 10 18:15 runtimes
drwx------ 2 root root   4096 Mar 10 18:15 swarm
drwx--x--- 2 root docker 4096 Mar 10 18:15 tmp
drwx------ 2 root root   4096 Mar 10 18:15 trust
drwx-----x 2 root root   4096 Mar 10 18:15 volumes
```

### CODE REVIEW

**Comment by jiashuChen** [comment]
Docker build with my change:
```
#1 [internal] load build definition from Dockerfile
#1 sha256:622e875471fbfc54756c18e91855dedf2baaec2e8794b0f19663db6bb71599b9
#1 transferring dockerfile: 177B done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 sha256:0d45a535e874865220921f7591aa82ab11bef03cfdc46b1ec9e83454597fa338
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 sha256:d4fb25f5b5c00defc20ce26f2efc4e288de8834ed5aa59dff877b495ba88fda6
#3 DONE 3.4s

#4 [stage-0 1/2] FROM docker.io/library/alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
#4 sha256:34c5df6b40e5466664adaaec74e2bd3ac818d2a65a457548ecaefd7625cb2d00
#4 resolve docker.io/library/alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 0.0s done
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 0B / 2.82MB 0.1s
#4 sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 1.64kB / 1.64kB done
#4 sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3 528B / 528B done
#4 sha256:c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18 1.47kB / 1.47kB done
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 2.10MB / 2.82MB 0.4s
#4 extracting sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 2.82MB / 2.82MB 0.5s done
#4 extracting sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 0.1s done
#4 DONE 0.6s

#5 [stage-0 2/2] RUN 	--mount=type=secret,id=notasecret 	set -exu 	&& ls -l /run/secrets/ 	&& cat /run/secrets/notasecret
#5 sha256:a16175a432881d90de1e071dc3e693eef28bc0316f31b5abc89cdf1b5598ee08
#5 0.257 + ls -l /run/secrets/
#5 0.258 total 4
#5 0.258 -r--------    1 root     root             2 Mar 10 07:16 notasecret
#5 0.258 + cat /run/secrets/notasecret
#5 0.258 no#5 DONE 0.3s

#6 exporting to image
#6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#6 exporting layers 0.0s done
#6 writing image sha256:0a601353f69e4a91c244344014ee69b700ffbc5bd6bbd5e6de757d255bb9ad1d done
#6 naming to docker.io/library/secretmounttest:latest done
#6 DONE 0.0s

```

**Comment by jiashuChen** [comment]
Docker build log without my change:
```
#1 [internal] load build definition from Dockerfile
#1 sha256:ff7e9fb6f82c64af5f81a0f859689dae86de3aef971b1347db5fd74cc449c1c7
#1 transferring dockerfile: 38B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:3eae092c65aa232d7b76fe91277420376169f512316c7fda40732a74ba8bc322
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 sha256:d4fb25f5b5c00defc20ce26f2efc4e288de8834ed5aa59dff877b495ba88fda6
#3 DONE 1.8s

#4 [stage-0 1/2] FROM docker.io/library/alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
#4 sha256:34c5df6b40e5466664adaaec74e2bd3ac818d2a65a457548ecaefd7625cb2d00
#4 CACHED

#5 [stage-0 2/2] RUN 	--mount=type=secret,id=notasecret 	set -exu 	&& ls -l /run/secrets/ 	&& cat /run/secrets/notasecret
#5 sha256:a16175a432881d90de1e071dc3e693eef28bc0316f31b5abc89cdf1b5598ee08
#5 0.096 container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/var/lib/docker/1000.997/tmp/buildkit-secrets3453442658/upz6bp7op0i7b15u66a230oot" to rootfs at "/run/secrets/notasecret" caused: stat /var/lib/docker/1000.997/tmp/buildkit-secrets3453442658/upz6bp7op0i7b15u66a230oot: permission denied
#5 ERROR: executor failed running [/bin/sh -c set -exu 	&& ls -l /run/secrets/ 	&& cat /run/secrets/notasecret]: exit code: 1
------
 > [stage-0 2/2] RUN 	--mount=type=secret,id=notasecret 	set -exu 	&& ls -l /run/secrets/ 	&& cat /run/secrets/notasecret:
------
executor failed running [/bin/sh -c set -exu 	&& ls -l /run/secrets/ 	&& cat /run/secrets/notasecret]: exit code: 1
```

**Comment by tonistiigi** [comment]
cc @cpuguy83

**Comment by jiashuChen** [comment]
@tonistiigi @cpuguy83 Hi, I notice the current CI failure seems to be network related, however, I don't have permission to re-run or manually kick off the verification again, would someone be able to help with this?

```
[2022-03-10T10:52:10.386Z] gopath\pkg\mod\gotest.tools\gotestsum@v1.7.0\cmd\flags.go:9:2: github.com/google/shlex@v0.0.0-20191202100458-e7afc7fbc510: Get "https://proxy.golang.org/github.com/google/shlex/@v/v0.0.0-20191202100458-e7afc7fbc510.zip[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43354/5/pipeline#step-290-log-317)": read tcp 172.28.6.53:49157->142.250.189.241:443: wsarecv: An existing connection was forcibly closed by the remote host.

[2022-03-10T10:52:10.386Z] gopath\pkg\mod\gotest.tools\gotestsum@v1.7.0\cmd\flags.go:10:2: github.com/pkg/errors@v0.9.1: Get "https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.zip[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43354/5/pipeline#step-290-log-318)": read tcp 172.28.6.53:49157->142.250.189.241:443: wsarecv: An existing connection was forcibly closed by the remote host.

[2022-03-10T10:52:10.386Z] gopath\pkg\mod\gotest.tools\gotestsum@v1.7.0\cmd\tool\slowest\ast.go:12:2: golang.org/x/tools@v0.1.0: Get "https://proxy.golang.org/golang.org/x/tools/@v/v0.1.0.zip[](https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-43354/5/pipeline#step-290-log-319)": read tcp 172.28.6.53:49157->142.250.189.241:443: wsarecv: An existing connection was forcibly closed by the remote host.

[2022-03-10T10:52:10.854Z] gotestsum install failed...
```

**Comment by jiashuChen** [comment]
hmmm, looks like we have a flaky test case failing this time. Would you guys mind re-try the CI run again? @thaJeztah @cpuguy83

**Comment by cpuguy83** [comment]
I'm a bit leery to give the remapped root user access to the random files that might wind in the temp dir.
I think it would be best to have the builder use a specific dir for this.

**Comment by jiashuChen** [comment]
> I'm a bit leery to give the remapped root user access to the random files that might wind in the temp dir. I think it would be best to have the builder use a specific dir for this.

oh I see @cpuguy83.

I this case just want to propose a potential solution. What if we create a folder called `container_secrets` inside the with the following ownership and permission, `root:docker_group` and `710`. So for the following daemon config:
```json
{
  "userns-remap": "user:docker"
}
```
we will have the following folder structure:
```
root@my-desktop:/var/lib/docker/1000.997# ls -l
total 44
drwx--x--x 4 root root   4096 Mar 10 18:15 buildkit
drwx--x--- 2 root docker 4096 Mar 10 18:15 containers
drwx--x--- 2 root docker  4096 Mar 10 18:15 container_secrets
drwx------ 3 root root   4096 Mar 10 18:15 image
drwxr-x--- 3 root root   4096 Mar 10 18:15 network
drwx--x--- 3 root docker 4096 Mar 10 18:15 overlay2
drwx------ 4 root root   4096 Mar 10 18:15 plugins
drwx------ 2 root root   4096 Mar 10 18:15 runtimes
drwx------ 2 root root   4096 Mar 10 18:15 swarm
drwx------ 2 root root  4096 Mar 10 18:15 tmp
drwx------ 2 root root   4096 Mar 10 18:15 trust
drwx-----x 2 root root   4096 Mar 10 18:15 volumes
```

I think I might need to modify both this repo and the buildkit repo.

**Comment by cpuguy83** [comment]
Or `buildkit/mounts/secrets`

**Comment by thaJeztah** [comment]
@tonistiigi @cpuguy83 ptal

**Comment by jiashuChen** [comment]
Hi, Can I ask for a re-review? I've rebased my pull request to resolve the conflict (master branch upgraded buildkit version)

**Comment by jiashuChen** [comment]
Looks like this issue has been fixed in the latest docker release `20.10.15` through an upgrade of `runc` from `1.0.3` to `1.1.0`. I haven't had time to investigate in detail yet. However, I suspect this change fixed the issue https://github.com/opencontainers/runc/pull/3057. 

For others experiencing the same issue. Please upgrade docker engine to `20.10.15`

**Pull request closed without merging**
