### PR TITLE
update TestRunWithBlkioInvalidWeight

### PR DESCRIPTION
**Pull request by sunyuan3**
Signed-off-by: Yuan Sun sunyuan3@huawei.com

### CODE REVIEW

**Comment by HuKeping** [comment]
WIP? I think there is really a lot of work to do here :smile_cat:

**Comment by vdemeester** [comment]
@HuKeping I think this is just to updates this test and not all. I hope at least because I'm working on it since this week end :stuck_out_tongue_closed_eyes:.

**Comment by sunyuan3** [comment]
This PR is to add output verification in TestRunWithBlkioInvalidWeight, not update all cases in this file.

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐬

**Pull request merged**
