### PR TITLE
Remove reference package dependency from the api.

### PR DESCRIPTION
**Pull request by calavera**
This change removes the dependency from the reference package by delegating the reference resolution to the daemon. The behavior is exactly the same.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
@calavera cool :heart_eyes_cat: This will make the follow-up of #21657 and docker/engine-api#162 easier to do :+1:

**Comment by LK4D4** [comment]
@calavera golint failure

**Comment by calavera** [comment]
@LK4D4 fixed

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by MHBauer** [comment]
Missed this at the time. Agree with it.

**Pull request merged**
