### PR TITLE
Fix TestAuthZPluginAllowEventStream for multiarch

### PR DESCRIPTION
**Pull request by StefanScherer**
This PR fixes the integration test TestAuthZPluginAllowEventStream of PR #20002 to support multiarch.
Instead of pulling busybox the daemon under test must be started with the preloaded busybox image to remain on the correct CPU architecture.

I have left the `check.Commentf(out)` in the assert as a good practice to give more details in case of an error.

/cc @tophj-ibm

### CODE REVIEW

**Comment by runcom** [comment]
> I have left the check.Commentf(out) in the assert as a good practice to give more details in case of an error.

:)

LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by estesp** [comment]
Only change is to a `_unix_test.go` test file, so Windows failures are unrelated (and seem like Windows CI in general is not working at all).  LGTM

**Comment by StefanScherer** [comment]
Yes, the Windows issues are unrelated. Now we're back to green on ARM.

**Comment by tophj-ibm** [comment]
all green on power now too, thanks @StefanScherer!

**Pull request merged**
