### PR TITLE
Skip plugin tests if not in amd64

### LINKED ISSUE #28305: CI fails on z and power due to newly enabled testcases
The following CI testcases currently fail on power and z:

- FAIL: docker_cli_plugins_test.go:62: DockerSuite.TestPluginActive
- FAIL: docker_cli_daemon_plugins_test.go:83: DockerDaemonSuite.TestDaemonKillLiveRestoreWithPlugins
- FAIL: docker_cli_daemon_plugins_test.go:116: DockerDaemonSuite.TestDaemonShutdownLiveRestoreWithPlugins
- FAIL: docker_cli_daemon_plugins_test.go:187: DockerDaemonSuite.TestVolumePlugin
- FAIL: docker_cli_authz_plugin_v2_test.go:43: DockerAuthzV2Suite.TestAuthZPluginAllowNonVolumeRequest
- FAIL: docker_cli_authz_plugin_v2_test.go:72: DockerAuthzV2Suite.TestAuthZPluginRejectVolumeRequests
- FAIL: docker_cli_network_unix_test.go:771: DockerNetworkSuite.TestDockerPluginV2NetworkDriver

All the tests have been skipped before because of "Test requires an experimental daemon". Commit c410222e42fb9195909390337bc129c6481e2453 has moved the tests non-experimental.

See jenkins runs:

- https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/1142
- https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/2332

```
FAIL: docker_cli_plugins_test.go:62: DockerSuite.TestPluginActive

docker_cli_plugins_test.go:68:
    c.Assert(err, checker.IsNil)
... value *errors.errorString = &errors.errorString{s:"\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker volume create -d tiborvass/no-remove:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: create f8998578c8f95038de215a89848aea453fad56959a8d704a2f15fdc62b6e5a70: Post http://%2Frun%2Fdocker%2Fda02116dc1b0b12e793e2e0dfd15f145a06c600875cec26d6c5faddb3c34ab3b%2Fplugin.sock/VolumeDriver.Create: dial unix /run/docker/da02116dc1b0b12e793e2e0dfd15f145a06c600875cec26d6c5faddb3c34ab3b/plugin.sock: connect: no such file or directory\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n"} ("\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker volume create -d tiborvass/no-remove:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: create f8998578c8f95038de215a89848aea453fad56959a8d704a2f15fdc62b6e5a70: Post http://%2Frun%2Fdocker%2Fda02116dc1b0b12e793e2e0dfd15f145a06c600875cec26d6c5faddb3c34ab3b%2Fplugin.sock/VolumeDriver.Create: dial unix /run/docker/da02116dc1b0b12e793e2e0dfd15f145a06c600875cec26d6c5faddb3c34ab3b/plugin.sock: connect: no such file or directory\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n")
```

```
FAIL: docker_cli_daemon_plugins_test.go:83: DockerDaemonSuite.TestDaemonKillLiveRestoreWithPlugins

[d3726c72137d3] waiting for daemon to start
[d3726c72137d3] daemon started
docker_cli_daemon_plugins_test.go:110:
    c.Fatalf("Expected exit code '0', got %d err: %v output: %s ", ec, err, out)
... Error: Expected exit code '0', got 1 err: exit status 1 output:  

[d3726c72137d3] waiting for daemon to start
[d3726c72137d3] daemon started
[d3726c72137d3] exiting daemon
time="2016-11-11T03:16:17Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.0-1-s390x/modules.dep.bin'`, error: exit status 1" 
time="2016-11-11T03:16:17Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.0-1-s390x/modules.dep.bin'`, error: exit status 1" 
```

```
FAIL: docker_cli_daemon_plugins_test.go:116: DockerDaemonSuite.TestDaemonShutdownLiveRestoreWithPlugins

[d633f5078662c] waiting for daemon to start
[d633f5078662c] daemon started
docker_cli_daemon_plugins_test.go:143:
    c.Fatalf("Expected exit code '0', got %d err: %v output: %s ", ec, err, out)
... Error: Expected exit code '0', got 1 err: exit status 1 output:  

[d633f5078662c] waiting for daemon to start
[d633f5078662c] daemon started
[d633f5078662c] exiting daemon
```

```
FAIL: docker_cli_daemon_plugins_test.go:187: DockerDaemonSuite.TestVolumePlugin

[d64995abdc959] waiting for daemon to start
[d64995abdc959] daemon started
docker_cli_daemon_plugins_test.go:213:
    c.Fatalf("Could not create volume: %v %s", err, out)
... Error: Could not create volume: exit status 1 Error response from daemon: create plugin-volume: Post http://%2Frun%2Fdocker%2F5bbbc29e03f1ca743ff9114275af2c1f50ceaa376a91793a47436bad0e515f17%2Fplugin.sock/VolumeDriver.Create: dial unix /run/docker/5bbbc29e03f1ca743ff9114275af2c1f50ceaa376a91793a47436bad0e515f17/plugin.sock: connect: no such file or directory

docker_cli_daemon_plugins_test.go:213:
    c.Fatalf("Could not create volume: %v %s", err, out)
docker_cli_daemon_plugins_test.go:207:
    c.Fatalf("Could not remove plugin: %v %s", err, out)
... Error: Could not remove plugin: exit status 1 Error response from daemon: plugin tiborvass/no-remove:latest is in use


[d64995abdc959] exiting daemon
```

```
FAIL: docker_cli_authz_plugin_v2_test.go:43: DockerAuthzV2Suite.TestAuthZPluginAllowNonVolumeRequest

[d850096b9b75f] waiting for daemon to start
[d850096b9b75f] daemon started
[d850096b9b75f] exiting daemon
[d850096b9b75f] waiting for daemon to start
[d850096b9b75f] received status != 200 OK: 404 Not Found
[d850096b9b75f] daemon started
docker_cli_authz_plugin_v2_test.go:50:
    c.Assert(s.d.LoadBusybox(), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"could not load busybox image: Error response from daemon: plugin riyaz/authz-no-volume-plugin:latest failed with error: Post http://%2Frun%2Fdocker%2F63311306d75f76205fec9d4dba6c961e2a6d4ca238f640235e6d1e67d29ea11e%2Fauthz-plugin.sock/AuthZPlugin.AuthZReq: dial unix /run/docker/63311306d75f76205fec9d4dba6c961e2a6d4ca238f640235e6d1e67d29ea11e/authz-plugin.sock: connect: no such file or directory\n"} ("could not load busybox image: Error response from daemon: plugin riyaz/authz-no-volume-plugin:latest failed with error: Post http://%2Frun%2Fdocker%2F63311306d75f76205fec9d4dba6c961e2a6d4ca238f640235e6d1e67d29ea11e%2Fauthz-plugin.sock/AuthZPlugin.AuthZReq: dial unix /run/docker/63311306d75f76205fec9d4dba6c961e2a6d4ca238f640235e6d1e67d29ea11e/authz-plugin.sock: connect: no such file or directory\n")

```

```
FAIL: docker_cli_authz_plugin_v2_test.go:72: DockerAuthzV2Suite.TestAuthZPluginRejectVolumeRequests

[df6c08ecba979] waiting for daemon to start
[df6c08ecba979] daemon started
[df6c08ecba979] exiting daemon
[df6c08ecba979] waiting for daemon to start
[df6c08ecba979] received status != 200 OK: 404 Not Found
[df6c08ecba979] daemon started
docker_cli_authz_plugin_v2_test.go:104:
    c.Assert(out, checker.Contains, fmt.Sprintf("Error response from daemon: plugin %s failed with error:", authzPluginNameWithTag))
... obtained string = "" +
...     "[]\n" +
...     "Error: No such volume: test\n"
... substring string = "Error response from daemon: plugin riyaz/authz-no-volume-plugin:latest failed with error:"

[df6c08ecba979] exiting daemon
[df6c08ecba979] waiting for daemon to start
[df6c08ecba979] exiting daemon
docker_cli_authz_plugin_v2_test.go:104:
    c.Assert(out, checker.Contains, fmt.Sprintf("Error response from daemon: plugin %s failed with error:", authzPluginNameWithTag))
docker_cli_authz_plugin_v2_test.go:82:
    c.Assert(s.d.Restart(), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"[df6c08ecba979] Daemon exited during startup"} ("[df6c08ecba979] Daemon exited during startup")
```

```
FAIL: docker_cli_network_unix_test.go:771: DockerNetworkSuite.TestDockerPluginV2NetworkDriver

docker_cli_network_unix_test.go:788:
    dockerCmd(c, "network", "create", "-d", npNameWithTag, "v2net")
docker_utils.go:505:
    c.Assert(result, icmd.Matches, icmd.Success)
... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc420678420), ExitCode:1, Error:(*exec.ExitError)(0xc421fe24c0), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc4206ce510), errBuffer:(*cmd.lockedBuffer)(0xc4206ce630)} ("\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker network create -d mavenugo/test-docker-netplugin:latest v2net\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: could not resolve driver mavenugo/test-docker-netplugin:latest in registry\n\n")
... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
... 
Command: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker network create -d mavenugo/test-docker-netplugin:latest v2net
ExitCode: 1, Error: exit status 1
Stdout: 
Stderr: Error response from daemon: could not resolve driver mavenugo/test-docker-netplugin:latest in registry


Failures:
ExitCode was 1 expected 0
Expected no error
```

### PR DESCRIPTION
**Pull request by tonistiigi**
Quick solution for #28305 until plugins are ported to other architectures.

fixes #28305 

@vieux @tiborvass 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM, failure on Z is unrelated

**Comment by tophj-ibm** [comment]
looks good to me too, thanks!

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tophj-ibm** [comment]
arm ci failed because node arm-7 ran out of space, do the hypriot guys still own those?

**Comment by tiborvass** [comment]
@tophj-ibm no, we do.

**Comment by thaJeztah** [comment]
@vieux added cherry pick to make the tests work on the release branch as well

**Pull request merged**
