### PR TITLE
bump libnetwork to 430c00a

### LINKED ISSUE #348: driver.CreateEndpoint response are going to be lost.
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Network driver response are going to be written to KV storage and assigned to container sandbox 
E.g. MacAddress from driver.CreateEndpoint should be assigned to container interface 

### Actual behavior
Network driver response are going to be lost, because n.getController().updateToStore(ep) performed before driver call CreateEndpoint.
e.g. MacAddress lost 

### Steps to reproduce the behavior
Use driver with CreateEndpoint response like this:
`Jun 22 09:52:10 host libnetwork-plugin[23217]: time="2018-06-22T09:52:10Z" level=info msg="CreateEndpoint response" JSON="{"Interface":{"Address":"","AddressIPv6":"","MacAddress":"EE:EE:EE:EE:EE:EE"}}"`

Look at MacAddress with 'docker inspect <continer_id> 
Look at MacAddress inside container 'ip a' etc. 

I had debugging code flow. At `(daemon *Daemon) connectToNetwork` method I always have incomplete data (no driver response included). Endpoint.Info() has priority on return data from KV storage, but data in storage is incomplete. 
This result in container creation with broken network config. 

Can see this bug only at docker-ce, seems because of this commit (missing at moby): 
https://github.com/docker/docker-ce/commit/eeeede3c5fb19289726b8b5a2481e17094302f48

**Output of `docker version`:**

```
docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:14:54 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:18:36 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge calico host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.13-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.68GiB
Name: host_here
ID: GUWI:3FBN:FM7T:35QK:FJJJ:VM7E:CJMD:EV5L:KDIU:W22T:DMXJ:KTZL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 39
 Goroutines: 66
 System Time: 2018-06-22T09:58:24.492505617Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Cluster Store: etcd://<host_here>:2379
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

### PR DESCRIPTION
**Pull request by ctelfer**
Bump libnetwork to 430c00a6a6b3dfdd774f21e1abd4ad6b0216c629.

Full diff: https://github.com/docker/libnetwork/compare/19279f0492417475b6bfbd0aa529f73e8f178fb5...430c00a6a6b3dfdd774f21e1abd4ad6b0216c629

Relevant changes:
 * Update vendoring for go-sockaddr (8df9f31a) https://github.com/hashicorp/go-sockaddr/compare/acd314c5781ea706c710d9ea70069fd2e110d61d...6d291a969b86c4b633730bfc6b8b9d64c3aafed9
 * Fix inconsistent subnet allocation by preventing allocation of
   overlapping subnets (8579c5d2)
 * Handle IPv6 literals correctly in port bindings (474fcaf4)
 * Update vendoring for miekg/dns (8f307ac8)
 * Avoid subnet reallocation until required (9756ff7ed)
 * Bump libnetwork build to use go version 1.10.2 (603d2c1a)
 * Unwrap error type returned by PluginGetter (aacec8e1)
 * Update vendored components to match moby (d768021dd)
 * Add retry field to cluster-peers probe (dbbd06a7)
 * Fix net driver response loss on createEndpoint (1ab6e506)
   (fixes https://github.com/docker/for-linux/issues/348)

Signed-off-by: Chris Telfer <ctelfer@docker.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by ctelfer** [comment]
Pushed a 2nd commit to adjust a unit test that employed overlapping subnets.

**Review by abhi — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
> The TestDockerNetworkIPAMMultipleNetworks test allocates several networks simultaneously with overlapping IP addresses.  Libnetwork now forbids this.

This may be a breaking change for people using that as a feature, or did this never work properly?

**Comment by ctelfer** [comment]
@abhi and @fcrisciani can elaborate, but as I understand it this did *not* work properly, especially for swarm.  In swarm mode it would accept the configuration as allowable, but when trying to create tasks in a service it would fail the network allocation and just leave the service pretty much in limbo.

**Review by fcrisciani — APPROVED** [review]
LGTM

**Comment by abhi** [comment]
@thaJeztah do you know the real use case/history of overlapping subnet ? 
In swarm we fail overlapping subnets but we do not fail "exact" subnets for 2 different networks. It was working behind the scenes because it was using the pool id. But in libnetwork this has not been fully implemented e2e though it can be supported. This was causing some silent errors as well. So we make sure if its overlapping subnet we just error it out.

**Comment by thaJeztah** [comment]
Not sure if there's a real _use case_ (as in "need to have these networks in the same range"), but (just from the top of my head) thinking of users that have a template / compose file to create networks with an IP-range, and may be using the same template / compose file for multiple stacks.

**Comment by thaJeztah** [comment]
PowerPC failure looks unrelated; there was an old issue for this test https://github.com/moby/moby/issues/34988, but should've been fixed by https://github.com/moby/moby/pull/35173.

Not sure if it's a different issue now

```
20:51:35 FAIL: check_test.go:347: DockerSwarmSuite.TearDownTest
20:51:35 
20:51:35 check_test.go:352:
20:51:35     d.Stop(c)
20:51:35 /go/src/github.com/docker/docker/internal/test/daemon/daemon.go:401:
20:51:35     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
20:51:35 ... Error: Error while stopping the daemon d96103a2b0b0e : exit status 130
20:51:35 
20:51:35 
20:51:35 ----------------------------------------------------------------------
20:51:35 PANIC: docker_api_swarm_test.go:359: DockerSwarmSuite.TestAPISwarmRaftQuorum
20:51:35 
20:51:35 [d96103a2b0b0e] waiting for daemon to start
20:51:35 [d96103a2b0b0e] daemon started
20:51:35 
20:51:35 [dec520e876db4] waiting for daemon to start
20:51:35 [dec520e876db4] daemon started
20:51:35 
20:51:35 [d6bfca0b0791f] waiting for daemon to start
20:51:35 [d6bfca0b0791f] daemon started
20:51:35 
20:51:35 [dec520e876db4] exiting daemon
20:51:35 [d6bfca0b0791f] exiting daemon
20:51:35 [dec520e876db4] waiting for daemon to start
20:51:35 [dec520e876db4] daemon started
20:51:35 
20:51:35 [d96103a2b0b0e] daemon started
20:51:35 Attempt #2: daemon is still running with pid 7420
20:51:35 Attempt #3: daemon is still running with pid 7420
20:51:35 Attempt #4: daemon is still running with pid 7420
20:51:35 [d96103a2b0b0e] exiting daemon
20:51:35 ... Panic: Fixture has panicked (see related PANIC)
```

**Comment by thaJeztah** [comment]
Agreed that it could be accidentally; curious: what happens with existing networks (that have overlapping subnets) after upgrading?

**Comment by thaJeztah** [comment]
Discussing this with @fcrisciani and @ctelfer; although a corner-case, there may be users out there that currently have overlay network that have an overlapping subnet; for those, it will be needed to re-create the network, so for Docker we need a mention in the changelog

**Pull request merged**
