### PR TITLE
Add --pid flag for staying in the host's pid namespace

### PR DESCRIPTION
**Pull request by crosbymichael**
Replaces #9339

This adds an integration test for the --pid host mode

### CODE REVIEW

**Comment by jfrazelle** [comment]
kewl LGTM, I bet next will come `--pid=container` ;)

**Comment by crosbymichael** [comment]
This has been LGTM'ed in the other PR, merging.

**Comment by ibuildthecloud** [comment]
I just shed of tear of joy when I noticed this PR was merged.  I'll be a sobbing baby when `--pid=container` lands.

**Comment by thockin** [comment]
Is there a PR open for --pod=container ?

**Comment by jfrazelle** [comment]
I was making a joke that it would be next, but no one has made it yet

**Comment by thockin** [comment]
Consider this a request?

**Comment by thaJeztah** [comment]
@thockin @ibuildthecloud it looks like you both have use-cases to describe why it's useful. Could you please create a new issue describing this? It'd make it easier to track, and a decision to implement it (or not) can be made there.


(Sorry for meddling in this, @jfrazelle :smile: trying to keep my head sane following things)

**Comment by thaJeztah** [comment]
People looking for `--pid=container`; @thockin opened a new issue for that here: https://github.com/docker/docker/issues/10163 (thanks!)

**Comment by wires** [comment]
I cannot seem to figure out how start a container with `--pid=host` using the API, Does this command line option an API analogue?

**Pull request merged**
