### PR TITLE
Update services cli docs with --port

### PR DESCRIPTION
**Pull request by vdemeester**
Follow-up of https://github.com/docker/docker/pull/27917. Still needs some work…

/cc @thaJeztah @mavenugo 

:frog: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by mavenugo** [comment]
@vdemeester should we wait for https://github.com/docker/docker/issues/28527 to be decided if it is targeted for 1.13 ?

**Comment by vdemeester** [comment]
@mavenugo hum right, we might want to wait for #28527 before merging this. I'll update and complete it based on the discussion on the issue :wink:

**Comment by thaJeztah** [comment]
@vdemeester it was decided to drop `--port`, and unify to `--publish`; https://github.com/docker/docker/issues/28527#issuecomment-262817805. Are you interested in implementing that, or should someone else work on it?

**Comment by vdemeester** [comment]
Ah right, yes I'll work on it :angel: 
Closing this one for now.

**Pull request closed without merging**
