### PR TITLE
rename req to resp

### PR DESCRIPTION
**Pull request by mqliang**
`req` is misleading and confusing, rename as `resp`

Signed-off-by: mqliang mqliang.zju@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
@mqliang needs rebase :(

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
LGTM pending exp

**Comment by LK4D4** [comment]
exp failure is weird :)

**Comment by calavera** [comment]
Experimental build passed. Merging.

**Pull request merged**
