### PR TITLE
ready for merge: surfacing Learn by example topics to top level of Docker Engine docs

### PR DESCRIPTION
**Pull request by londoncalling**
**\- What I did**

added merged getting started tutorial (using a different branch than for moving existing tutorials)

**\- How I did it**
copied files from original getting started tutorial over to docker/docker and modified the content

**\- How to verify it**

local build

fixing links after moving surfacing tutorials

fixing more links for the newly located tutorials

WIP: merging 3 getting started tutorials into one to cover all platforms, added new files

Signed-off-by: Victoria Bialas victoria.bialas@docker.com

### CODE REVIEW

**Comment by londoncalling** [comment]
@SvenDowideit @thaJeztah 

Okay, I might have just done something lame here but I don’t think particularly dangerous. I had an original PR, this one: #23492 , where I moved the “Learn by example” files up (surfaced) in Docker Engine docs.

Then I created a new branch off of that one I was using to do that, and created a merged getting started tutorial, also in that same repo. When I went to commit and push those files, I assumed I would have to create a new PR because they were on a different branch. It looks like that was unnecessary. But anyway, now I have two PRs. I haven’t looked two closely but I’m pretty sure that this PR includes all changes from both.

**Comment by SvenDowideit** [comment]
should work :)

**Comment by londoncalling** [comment]
@SvenDowideit when this is merged it should fix the 2 link errors on the builds for https://github.com/docker/toolbox/pull/513

**Comment by SvenDowideit** [comment]
LGTM - I'll fix the others as i go

**Comment by londoncalling** [comment]
Thanks! 👍

**Pull request merged**
