### PR TITLE
[27.x] vendor: update buildkit to v0.17.1, pin github.com/microsoft/hcsshim to v0.11.x

### PR DESCRIPTION
**Pull request by thaJeztah**
backport:

- https://github.com/moby/moby/pull/48751
- https://github.com/moby/moby/pull/48792
- https://github.com/moby/moby/pull/48801
- https://github.com/moby/moby/pull/48836
- closes https://github.com/moby/moby/pull/48795
- closes https://github.com/moby/moby/pull/48802

Alternative to https://github.com/moby/moby/pull/48795. In this variant, we pin hcsshim to v0.11.x, matching what containerd uses; this allows us to ship the BuildKit update in a 27.x minor release without that forcing our hands on updating all (indirect) dependencies of hcsshim (which includes OTEL updates and some other ones).

**- Description for the changelog**

```markdown changelog
TODO add change-log for buildkit changes 
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by austinvazquez** [comment]
For the changelog does a user care about pinned hcsshim here or is it as simple as this?
```
Update BuildKit to v0.17.0
```

**Comment by thaJeztah** [comment]
I originally opened this against the wrong branch; looks like GItHub actions didn't pick up that I changed; let me try if close/reopen does the trick

**Review by crazy-max — APPROVED** [review]
SGTM

**Comment by thaJeztah** [comment]
Updated to v0.17.1 (added https://github.com/moby/moby/pull/48836)

**Review by vvoland — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
