### PR TITLE
Bugfix: bad format for CJK words

### LINKED ISSUE #19364: `docker search` output formatting incorrect
# Problem

Output formatting of `docker search` doesn't work very well with (I assume) wide chars:

```
-> % docker search ubuntu
NAME                              DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
ubuntu                            Ubuntu is a Debian-based Linux operating s...   2978      [OK]
ubuntu-upstart                    Upstart is an event-based replacement for ...   58        [OK]
torusware/speedus-ubuntu          Always updated official Ubuntu docker imag...   25                   [OK]
ubuntu-debootstrap                debootstrap --variant=minbase --components...   23        [OK]
tleyden5iwx/ubuntu-cuda           Ubuntu 14.04 with CUDA drivers pre-installed    18                   [OK]
rastasheep/ubuntu-sshd            Dockerized SSH service, built on top of of...   16                   [OK]
neurodebian                       NeuroDebian provides neuroscience research...   15        [OK]
ioft/armhf-ubuntu                 [ABR] Ubuntu Docker images for the ARMv7(a...   7                    [OK]
sameersbn/ubuntu                                                                  5                    [OK]
nuagebec/ubuntu                   Simple always updated Ubuntu docker images...   4                    [OK]
nimmis/ubuntu                     This is a docker images different LTS vers...   3                    [OK]
nickistre/ubuntu-lamp-wordpress   LAMP on Ubuntu with wp-cli installed            3                    [OK]
maxexcloo/ubuntu                  Docker base image built on Ubuntu with Sup...   2                    [OK]
nickistre/ubuntu-lamp             LAMP server on Ubuntu                           1                    [OK]
densuke/ubuntu-jp-remix           Ubuntu Linuxの日本語remix風味です                       1                    [OK]
sylvainlasnier/ubuntu             Ubuntu 15.10 root docker images with commo...   1                    [OK]
isuper/base-ubuntu                This is just a small and clean base Ubuntu...   1                    [OK]
seetheprogress/ubuntu             Ubuntu image provided by seetheprogress us...   1                    [OK]
konstruktoid/ubuntu               Ubuntu base image                               0                    [OK]
webhippie/ubuntu                  Docker images for ubuntu                        0                    [OK]
esycat/ubuntu                     Ubuntu LTS                                      0                    [OK]
birkof/ubuntu                     Ubuntu 14.04 LTS (Trusty Tahr)                  0                    [OK]
teamrock/ubuntu                   TeamRock's Ubuntu image configured with AW...   0                    [OK]
rallias/ubuntu                    Ubuntu with the needful                         0                    [OK]
zoni/ubuntu                                                                       0                    [OK]
```

Note how the `densuke/ubuntu-jp-remix` formatting is skewed.
# Version

```
-> % docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
# Info

```
-> % docker info
Containers: 0
Images: 22
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dockra
ID: RPDM:O2PB:S5IB:J7KL:UKTM:AJV7:4FH4:HDKS:DHRL:NNOF:OUTG:GSSY
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2016-01-15T15:10:17.591596248Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: noseglid
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
# Machine

```
-> % uname -a
Darwin Alexanders-MacBook-Air.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by WeiZhang555**
Close https://github.com/docker/docker/issues/19364

Golang tabwriter can't handle CJK words correctly, replace Golang
tabwriter with modified version, which will display CJK words in 2
columes.

Need vendoring of [WeiZhang555/tabwriter](https://github.com/WeiZhang555/tabwriter), which is a slightly modified
version of Golang tabwriter. Also depend on `moznion/go-unicode-east-asian-width/`

After fix:

search-ubuntu

search2

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by runcom** [comment]
Nice! btw tests are failing because you need to update `./hack/vendor.sh` to import new code (not just copying it under vendor/src

**Comment by WeiZhang555** [comment]
@runcom Thank you for reminder, I'm not familiar with this, let me have a try :smile:

**Comment by WeiZhang555** [comment]
@runcom just noticed you updated something.

>Btw, can't this be fixed in golang upstream and we could just wait the next release for fixing this?

I have a deep look into this, and it seems there is a thorny problem here, some unicode chars have ambiguous width which can be 2 or 1 columns, and there's no clear standard settled down so far.
But I will upstream this to Golang whatever,  to see what they'll say about this. I think we can use it first before they accept this.

**Comment by cyphar** [comment]
I concur with @runcom, IMHO it would make more sense to have this merged in to Go so that everyone (including us) can benefit from it (since you've modified the code for the standard library).

**Comment by unclejack** [comment]
+1 This change should go into Go's stdlib instead. I think that would be a very good idea because there are lots of people who would be more than happy to see this committed to the official Go stdlib because it fixes issues they run into.

@WeiZhang555 Please try to submit this as a CL to Go. I think the Go maintainers will advise you regarding changes required to get the code merged. I'll leave this PR open for now.

**Comment by WeiZhang555** [comment]
@cyphar Yes, that sounds reasonable. I'll keep pushing the Go community to see if I can make this tabwriter merged, that may take some time. :smile:

**Comment by WeiZhang555** [comment]
@unclejack I'll do that, thank you for help!

**Comment by WeiZhang555** [comment]
Some updates:
I think we can't get this fixed before Go 1.6 or even before 1.7, the Go community has already had some discussions before, and it turns out to be a very complicated problem. It's not only related to CJK words but also related to fonts. And I'm also assuming that CJK:character = 2:1 which is also not always true, because there's no standard mapping currently.

The related thread is here: https://github.com/golang/go/issues/12073#issuecomment-174166681

I think this one can be closed now because I can't give a perfect solution currently, it's more than I can do for now.

**Comment by icecrime** [comment]
Thanks for the effort @WeiZhang555! I'm closing as per your comment, but please anyone voice your opinion if you feel we should proceed nevertheless.

**Pull request closed without merging**
