### PR TITLE
Bump containerd daemon to v1.1.1

### PR DESCRIPTION
**Pull request by cpuguy83**
full diff: https://github.com/containerd/containerd/compare/e5fb877b9f6c14b15f48643735a8c9764a7319d3...d64c661f1d51c48782c9cec8fda7604785f93587

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @dmcgowan @crosbymichael

**Review by dmcgowan — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Jankyhttps://jenkins.dockerproject.org/job/Docker-PRs/50034/console failing on a flaky test https://github.com/moby/moby/issues/37408

```
00:27:42 FAIL: docker_api_swarm_service_test.go:311: DockerSwarmSuite.TestAPISwarmServicesFailedUpdate
00:27:42 
00:27:42 [d2da00e68e69e] waiting for daemon to start
00:27:42 [d2da00e68e69e] daemon started
00:27:42 
00:27:42 [dba951d7fb2e2] waiting for daemon to start
00:27:42 [dba951d7fb2e2] daemon started
00:27:42 
00:27:42 [d635d17dbe418] waiting for daemon to start
00:27:42 [d635d17dbe418] daemon started
00:27:42 
00:27:42 docker_api_swarm_service_test.go:347:
00:27:42     waitAndAssert(c, defaultReconciliationTimeout, daemons[0].CheckRunningTaskImages, checker.DeepEquals,
00:27:42         map[string]int{image1: instances})
00:27:42 docker_utils_test.go:435:
00:27:42     c.Assert(v, checker, args...)
00:27:42 ... obtained map[string]int = map[string]int{"busybox:latest":4}
00:27:42 ... expected map[string]int = map[string]int{"busybox:latest":5}
00:27:42 
00:27:42 [d2da00e68e69e] exiting daemon
00:27:42 [dba951d7fb2e2] exiting daemon
00:27:42 [d635d17dbe418] exiting daemon
```

s390x https://jenkins.dockerproject.org/job/Docker-PRs-s390x/10339/console  is a flaky test as well; https://github.com/moby/moby/issues/32673

```
00:17:59 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:17:59 
00:17:59 [d269cb7908474] waiting for daemon to start
00:17:59 [d269cb7908474] daemon started
00:17:59 
00:17:59 [d6338bf93925f] waiting for daemon to start
00:17:59 [d6338bf93925f] daemon started
00:17:59 
00:17:59 [dba84927929f5] waiting for daemon to start
00:17:59 [dba84927929f5] daemon started
00:17:59 
00:17:59 [d269cb7908474] exiting daemon
00:17:59 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
00:17:59 [d6338bf93925f] exiting daemon
00:17:59 [dba84927929f5] exiting daemon
```


restarting both

**Review by boaz0 — COMMENTED** [review]
LGTM :rocket:

**Pull request merged**
