### PR TITLE
Remove v1.10 migrator

### PR DESCRIPTION
**Pull request by AkihiroSuda**
The v1.10 layout and the migrator was added in 2015 via #17924.

Although the migrator is not marked as "deprecated" explicitly in
[`cli/docs/deprecated.md`](https://github.com/docker/cli/blob/master/docs/deprecated.md), I suppose people should have already migrated
from pre-v1.10 and they no longer need the migrator, because pre-v1.10
version do not support schema2 images (and these versions no longer
receives security updates).

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by lowenna — APPROVED** [review]
No concerns from the Windows side

**Review by andrewhsu — APPROVED** [review]
SGTM w.r.t. removing deadwood code

**Comment by tonistiigi** [comment]
SGTM

**Comment by thaJeztah** [comment]
Quick chat with @tonistiigi - he's ok with removing this, but wondered if we could produce a decent error message if we run into store that wasn't migrated yet; I'm not sure if there's an easy way to detect that without scanning all directories; if there is, I think that would be a nice follow-up, but if we need to scan all directories, then I think we should leave it as is

**Comment by thaJeztah** [comment]
Moved this one to "merge", but if you want to make that enhancement in this PR @AkihiroSuda, let me know, otherwise feel free to push the merge button 👍

**Pull request merged**
