### PR TITLE
[20.10 backport] quota: adjust build-tags to allow build without CGO

### PR DESCRIPTION
**Pull request by pete-woods**
Backport #42172 to `20.10`

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]

**Comment by pete-woods** [comment]
Just double checking if there's anything else I need to do on this PR for it to move forward? Or if it's just waiting on 20.10.9 to become an actual planned release?

**Comment by pete-woods** [comment]
> > Just double checking if there's anything else I need to do on this PR for it to move forward?
> 
> 
> 
> nope, you should be all set! we'll include this in an upcoming patch release 👍 

Awesome, thanks! 🙏

**Comment by thaJeztah** [comment]
Sorry for the delay on merging this one; our 20.10 release branch was frozen in preparation of the 20.10.9 security release; we'll continue merging regular back ports now, and will do a 20.10.10 patch release soon

**Pull request merged**
