### PR TITLE
Bump v1.6.0

### PR DESCRIPTION
**Pull request by jessfraz**
Scheduled to be released Tuesday, April 7th. 

RC1 will be pushed to test.docker.com tomorrow morning (March 23) around 12 PST.

Please help with testing as this will be the official RC.

Here we go :) 

whale

### CODE REVIEW

**Comment by jfrazelle** [comment]
We have just pushed 1.6.0-rc1 to test.docker.com you can download with the following:

> NOTE: For the time being with the changes to registry v2, **if you push an image with the RC you CANNOT pull it with a previous version**, next week the registry team will make the switch for this to happen but for now, please be aware of this.

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc1
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc1
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.6.0-rc1
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc1.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0-rc1.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.6.0-rc1.exe


Please test and make sure all links are working.

cc @burke @bjaglin @proppy who have been awesome at testing RCs in the past

**Comment by jfrazelle** [comment]
also pinging @thokin to test kubes :D

**Comment by wolfeidau** [comment]
Heya

Is there a high level changelog somewhere with with all the stuff that is added/fixed ect?

Even just a "highlights" would be cool!

Thanks

**Comment by jfrazelle** [comment]
yep checkout the last commit

**Comment by wolfeidau** [comment]
:+1: Thanks exactly what i was after!

**Comment by lukemarsden** [comment]
Does this release fix `devicemapper` issues on Ubuntu? I was disappointed when I found that the latest Docker (1.5) on the latest LTS Ubuntu (14.04) didn't work as per https://github.com/docker/docker/issues/4036. Maybe @unclejack knows?

**Comment by jfrazelle** [comment]
Do you have udev? Why not use instead aufs or overlay?

**Comment by lukemarsden** [comment]
@jfrazelle AUFS is fine, the issue is that devicemapper has become the default on Ubuntu (since docker 1.5?) and that it doesn't work. Broken defaults = bad user experience. Switching the default to AUFS on Ubuntu would be a good fix. This is a high priority fix IMO.

**Comment by unclejack** [comment]
@lukemarsden The fixes for devicemapper for Ubuntu require that we provide distro and distro version specific repositories for Docker in order to provide dynamically linked Docker binaries.

That's the only valid fix for the problem, along with disallowing it by default for static binaries in a future release after we've migrated everyone to dynamically linked binaries.

**Comment by lukemarsden** [comment]
@unclejack yeah, that sounds like a lot of packing work. What do you think to changing the default back to AUFS on Ubuntu until that's happened?

**Comment by jfrazelle** [comment]
It's not a matter of making the default aufs, that is the first driver that
is tried, the user needs to install aufs from the linux kernel extras

**Comment by unclejack** [comment]
@lukemarsden As @jfrazelle has stated above, there's no change that we've made. If AUFS is there, it's used. If it's not, it's the user's/vendor's fault for not having installed the kernel which includes AUFS.

**Comment by lukemarsden** [comment]
Ahh, I see. And it looks like the script at https://docs.docker.com/installation/ubuntulinux/#installing-docker-on-ubuntu does that, too. Sorry for the noise!

**Comment by burke** [comment]
We're running the RC on a handful of servers, no issues so far!

**Comment by burke** [comment]
I won't have time to dig in to this today, but:

```
root@sb3:/etc/sv# docker ps | grep f9f5 | tail -1
ad7b00ea65af        f9f5cd9fb80c1ca1afe11a8fd6808bde8a2b253352562bd13e8bd200486d827c:latest   "/sbin/borginit hear   About an hour ago    Up About an hour                              borg-run-f9f5cd9fb80c1ca1afe11a8fd6808bde8a2b253352562bd13e8bd200486d827c-8459
root@sb3:/etc/sv# docker top ad7b
FATA[0000] Error response from daemon: [8] System error: mountpoint for devices not found
root@sb3:/etc/sv# docker stop ad7b
Error response from daemon: Cannot stop container ad7b: [2] Container does not exist: container destroyed
FATA[0000] Error: failed to stop one or more containers
root@sb3:/etc/sv# docker kill ad7b
Error response from daemon: Cannot kill container ad7b: [2] Container does not exist: container destroyed
FATA[0000] Error: failed to kill one or more containers
root@sb3:/etc/sv#
```

We have this running on a crontab every few minutes. It looks like all the completed jobs are piling up in a weird broken state. I'll dig some tomorrow and open an issue unless someone immediately knows what the problem is.

**Comment by jfrazelle** [comment]
oooo libcontainer bug cc @LK4D4 @crosbymichael ^

**Comment by LK4D4** [comment]
Error is definitely from cgroup devices.

**Comment by burke** [comment]
Let me know if there's anything specific I can provide to help.

**Comment by richtera** [comment]
I am getting these types of errors when using 1.6 rc1:
This seems similar to the devicemapper problems previously? Or is this a completely different issue?
```
2015/03/25 14:36:04 Error response from daemon: Cannot start container 7217b7b37d369538bd6f1afcebe1ccf2cf56fe5638782a239d535687ddb556b3: Cannot find child for /weavedns
```
Trying to launch it a second time works.
Docker:
```
$ sudo docker version
Client version: 1.6.0-rc1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 746e830
OS/Arch (client): linux/amd64
Server version: 1.6.0-rc1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 746e830
OS/Arch (server): linux/amd64
```
Weave
```
$ sudo weave version
weave script (unreleased version)
weave router git-066d8001dd6d
weave DNS git-066d8001dd6d
weave exec (unreleased version)
```

**Comment by cpuguy83** [comment]
@richtera do you have a way to repro?

**Comment by jfrazelle** [comment]
We have just pushed 1.6.0-rc2 to test.docker.com you can download with the following:

> NOTE: For the time being with the changes to registry v2, **if you push an image with the RC you CANNOT pull it with a previous version**, next week the registry team will make the switch for this to happen but for now, please be aware of this.

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc2
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc2
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.6.0-rc2
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc2.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0-rc2.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.6.0-rc2.exe

**Comment by richtera** [comment]
@cpuguy83  I can no longer reproduce. I was suspecting that I had some left over 1.5.0 on my system. It no longer has this problem. I will pull rc2 when I get a chance.

**Comment by tfoote** [comment]
Testing 1.6.0-rc2 does not appear to resolve #9139 Details in that thread at: https://github.com/docker/docker/issues/9139#issuecomment-87033577

**Comment by jfrazelle** [comment]
We have just pushed 1.6.0-rc3 to test.docker.com you can download with the following:

> NOTE: For the time being with the changes to registry v2, **if you push an image with the RC you CANNOT pull it with a previous version**, next week the registry team will make the switch for this to happen but for now, please be aware of this.

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc3
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc3
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.6.0-rc3
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc3.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0-rc3.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.6.0-rc3.exe

**Comment by jfrazelle** [comment]
We have just pushed 1.6.0-rc4 to test.docker.com you can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc4
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc4
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.6.0-rc4
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc4.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0-rc4.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.6.0-rc4.exe

@burke your problem should be good now :D

**Comment by LK4D4** [comment]
ping @sdake for tests :)

**Comment by sdake** [comment]
@LK4D4 testing now, I'll get back to you.

**Comment by sdake** [comment]
@lk4d4 start problems are gone.  stop problems are gone.  restart:always problems are gone.

I did notice the first time I tried it something went wonky with --pid=host networking.  We have a glance container which checks for the existence of keystone here:

https://github.com/stackforge/kolla/blob/master/docker/glance/glance-api/start.sh#L14

wait_for is implemented here:

https://github.com/stackforge/kolla/blob/master/docker/base/kolla-common.sh#L42

The container never seemed to find keystone.  The rest of the containers were able to find keystone.  I was able to access keystone directly from the host.

The wait_for call is a bit complex, so it could be buggy and was just refactored in the last 2 days or so.

The container did restart and exit with the wait_for call multiple times, so I'm unclear if the container networking isn't setup up properly or the wait_for call is busted.

I was unable to reproduce this problem after several tries.

**Comment by zoobab** [comment]
Managed to run docker over an openvz kernel:

Linux version 2.6.32-openvz-042stab105.14-amd64 (root@kbuild-ubu-x64) (gcc version 4.4.6 (Ubuntu/Linaro 4.4.6-11ubuntu2) ) #1 SMP Fri Mar 13 20:14:15 MSK 2015

It fixes the udev bug which was causing problems with 0.15. Will try to find the link to the bug in question.

Great news.

**Comment by burke** [comment]
Yup, my problem is fixed now! :cake:

**Comment by Govinda-Fichtner** [comment]
I was just trying to push an image to the Docker Hub with Docker 1.6rc4 and got an error. Tried it several times and had no luck.

```
$ docker push hypriot/rpi-mysql
The push refers to a repository [hypriot/rpi-mysql] (len: 2)
f22ea589cc4e: Image already exists
f22ea589cc4e: Image already exists
23d7b26ee3be: Image already exists
0817ecccd2a8: Image already exists
5e2318a394c5: Image already exists
ce30290bd446: Image already exists
2428880113f4: Image already exists
b8dec85ac677: Image already exists
8eeaa971a191: Image already exists
313060e9f936: Image successfully pushed
59604105ee50: Image push failed
98ce9bc46881: Image successfully pushed
7d67bef4dc82: Image successfully pushed
Digest: sha256:c85cd0b2a8bca858a3f43949733c34520b6de7367dceed2d58f1102dd30473a2

FATA[1525] Error pushing to registry: Server error: 504 trying head request for hypriot/rpi-mysql - sha256:0e35ee6965b94ccdf27bf141ea6a62b8ddd639b3b8a6966edd66358c1d826867
```

After switching back to Docker 1.5.0 everything worked as expected and I was able to upload the image just fine.
```
$ docker push hypriot/rpi-mysql
The push refers to a repository [hypriot/rpi-mysql] (len: 2)
Sending image list
Pushing repository hypriot/rpi-mysql (2 tags)
7d67bef4dc82: Image already pushed, skipping
98ce9bc46881: Image already pushed, skipping
4c34e8a1be05: Image successfully pushed
313060e9f936: Image successfully pushed
59604105ee50: Image successfully pushed
8eeaa971a191: Image successfully pushed
b8dec85ac677: Image successfully pushed
2428880113f4: Image successfully pushed
ce30290bd446: Image successfully pushed
5e2318a394c5: Image successfully pushed
0817ecccd2a8: Image successfully pushed
23d7b26ee3be: Image successfully pushed
f22ea589cc4e: Image successfully pushed
Pushing tag for rev [f22ea589cc4e] on {https://cdn-registry-1.docker.io/v1/repositories/hypriot/rpi-mysql/tags/5.5}
Pushing tag for rev [f22ea589cc4e] on {https://cdn-registry-1.docker.io/v1/repositories/hypriot/rpi-mysql/tags/latest}
```

I know that I am using Docker on ARM which is not supported as far as I know. But still this problem might not be restricted to ARM so I hope this information is still useful.

Apart from this Docker 1.6 rc4 works well for me.

**Comment by LK4D4** [comment]
ping @dmcgowan @dmp42 @stevvooe

**Comment by jfrazelle** [comment]
We have just pushed 1.6.0-rc5 to test.docker.com 

**This RC only has changes for docker.exe, there are no changes from rc4 for linux.**

You can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc4
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc5
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.6.0-rc5
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc5.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0-rc5.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.6.0-rc5.exe

**Comment by jfrazelle** [comment]
@ahmetalpbalkan @brendandixon @jhowardmsft not doing a whole RC just windows and one commit, so binaries are here for testing:

http://jesss.s3.amazonaws.com/tmp/386/docker-1.6.0-rc6.exe http://jesss.s3.amazonaws.com/tmp/386/docker-1.6.0-rc6.exe.md5
http://jesss.s3.amazonaws.com/tmp/386/docker-1.6.0-rc6.exe.sha256
http://jesss.s3.amazonaws.com/tmp/amd64/docker-1.6.0-rc6.exe
http://jesss.s3.amazonaws.com/tmp/amd64/docker-1.6.0-rc6.exe.md5
http://jesss.s3.amazonaws.com/tmp/amd64/docker-1.6.0-rc6.exe.sha256

**Comment by jfrazelle** [comment]
We have just pushed 1.6.0-rc6 to test.docker.com 

You can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc6
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc6
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.6.0-rc6
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc6.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0-rc6.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.6.0-rc6.exe

**Comment by jfrazelle** [comment]
@ibuildthecloud @burke @vishh can you all please check the issues filed were corrected

**Comment by ahmetalpbalkan** [comment]
I can verify the ctrl+C issue in the windows client is fixed. I get a better experience overall w/ the fixes. @brendandixon

**Comment by jfrazelle** [comment]
@ibuildthecloud can you test rancher, @vishh can you test kubes :D

**Comment by vishh** [comment]
The latest rc works for kubernetes!

**Comment by wolfeidau** [comment]
Just been road testing 1.6.0-rc6 with docker-compose and for some reason logging information isn't always being shown for all the services I launch. This happens maybe one out of every 3 runs.

Is this a known issue with docker-compose?

Seemed to be working fine with 1.5.0.

**Comment by jfrazelle** [comment]
ping @aanand

**Comment by aanand** [comment]
@wolfeidau There are known issues with docker-compose about output sometimes randomly not showing up: https://github.com/d11wtq/dockerpty/issues/26

Most likely the timing of something has changed and tripped a race condition, but I'll investigate tomorrow.

**Comment by wolfeidau** [comment]
@aanand Thanks for the info, compose is a very handy tool.

**Comment by jfrazelle** [comment]
damn you @GordonTheTurtle we dont want you here

**Comment by aanand** [comment]
I can't reproduce the problem you're seeing, so I'm inclined to believe it's https://github.com/d11wtq/dockerpty/issues/26 and not a Docker regression.

**Comment by jfrazelle** [comment]
We have just pushed 1.6.0-rc7 with 2 small changes to the upstart script and a check to make sure bridge kernel mod is loaded to test.docker.com 

You can download with the following:

**Ubuntu/Debian:** `curl -sSL https://test.docker.com/ubuntu | sh` or `curl -sSL https://test.docker.com/ | sh`
**Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc7
**Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc7
**Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.6.0-rc7
**Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc7.tgz
**Windows 64bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0-rc7.exe
**Windows 32bit client binary:** http://test.docker.com.s3.amazonaws.com/builds/Windows/i386/docker-1.6.0-rc7.exe

**Comment by icecrime** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
LGTMLGTMLGTM yeah come on

**Comment by icecrime** [comment]
:tada:

**Comment by jfrazelle** [comment]
we need @crosbymichael <3

**Comment by jfrazelle** [comment]
and @LK4D4

**Comment by LK4D4** [comment]
And lxc :)

**Comment by jfrazelle** [comment]
ok lxc passed fire ze missiles

**Comment by thaJeztah** [comment]
(quietly) and me? lgtm!!

**Comment by LK4D4** [comment]
LGTM

**Comment by bfirsh** [comment]
yaaay

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
:tada:

**Comment by burke** [comment]
Woohoo, great work :)

```
Chef Client finished, 62/1171 resources updated in 82.349480175 seconds
burke@borg2.ash:~ $ docker version
Client version: 1.6.0
``

**Comment by vishh** [comment]
Yuhoooo!!

**Comment by runcom** [comment]
gratzzzz

**Comment by ahmetalpbalkan** [comment]
**Windows client 32-bit: ** https://get.docker.com/builds/Windows/i386/docker-1.6.0.exe
**Windows client 64-bit: ** https://get.docker.com/builds/Windows/x86_64/docker-1.6.0.exe

Or use [Chocolatey](https://chocolatey.org/packages/docker):

    choco install docker

**Comment by frntn** [comment]
Congrats !
Great work :)

**Pull request merged**
