### PR TITLE
Trying to find rule for AppArmor DENIED error related to mount/pivot_r…

### PR DESCRIPTION
**Pull request by stefanberger**
…oot op

This is the so-far-fruitless-attempt to find an AppArmor rule for the following
deny:

type=AVC msg=audit(1444521663.545:61650): apparmor="DENIED" operation="mount" info="failed srcname match" error=-13 profile="/usr/bin/docker" name="/.pivot_root465400889/" pid=1214931 comm="exe" flags="rw, rprivate"

aa-genprof on my Ubuntu 14.04.2 doesn't help generate the rule, either.

(apparmor-utils  version 2.8.95~2430-0ubuntu)

Signed-off-by: Stefan Berger stefanb@linux.vnet.ibm.com

### CODE REVIEW

**Comment by stefanberger** [comment]
@ewindisch Maybe your team has better luck ... ?

**Comment by ewindisch** [comment]
I'll try and reproduce on Monday.

**Comment by stefanberger** [comment]
Any luck on that so far ?

**Comment by stefanberger** [comment]
@jfrazelle did you have luck so far with finding a rule for this deny error ?

**Comment by jfrazelle** [comment]
Yes I think I have an idea I will try today






On Mon, Oct 19, 2015 at 8:16 AM -0700, "Stefan Berger" <notifications@github.com> wrote:












@jfrazelle did you have luck so far with finding a rule for this deny error ?

**Comment by stefanberger** [comment]
On Ubuntu 14.04.3 with a 3.19.0-25-generic kernel the following errors appear when doing
```docker run -ti ubuntu /bin/bash```

```
type=AVC msg=audit(1445530888.478:1231): apparmor="ALLOWED" operation="mount" info="Failed name lookup - disconnected path" error=-13 profile="/usr/bin/docker" name="/run/docker/netns/e5d0b4fbb507/" pid=6158 comm="docker" srcname="" flags="rw, bind"
type=AVC msg=audit(1445530888.570:1232): apparmor="ALLOWED" operation="mount" info="failed flags match" error=-13 profile="/usr/bin/docker" name="/.pivot_root326771004/" pid=7762 comm="exe" flags="rw, rprivate"
type=AVC msg=audit(1445530888.578:1233): apparmor="ALLOWED" operation="ptrace" profile="/usr/bin/docker" pid=6158 comm="docker" requested_mask="trace" peer="docker-default"
```

The 1st error should be addressed already by this rule, but it doesn't seem to accept it. 
```
mount -> /run/docker/netns/**/,
```

The 2nd error is again the problem pointed out in this PR. Having tried a variation of rules like the following ones doesn't seem to address the 'failed flags match' error message:

```
  mount options in (rw,rprivate)       -> /.pivot_root[0-9]*,
  mount options=(rw,rprivate)          -> /.pivot_root[0-9]*/,
  mount options=rw options=rprivate    -> /.pivot_root[0-9]*/,
  mount options=rw                     -> /.pivot_root[0-9]*/,
  mount            options=rprivate    -> /.pivot_root[0-9]*/,
  mount options in (rw,rprivate)       -> /.pivot_root[0-9]*/,
```

**Comment by stefanberger** [comment]
The lazy rule (no options given) is the one that makes the 2nd error go away:
```
mount -> /.pivot_root[0-9]*/
```

**Pull request closed without merging**
