### PR TITLE
Add intValue and use it to get timeout form param in postContainersRestart

### LINKED ISSUE #12607: Remove error check
Assignment, error check (and return) at https://github.com/docker/docker/blob/master/api/server/server.go#L947-950 should be removed.

Implement `intValue` in https://github.com/docker/docker/blob/master/api/server/form.go (following how `int64Value` is implemented to return 0 on error) and use it directly in the call to `ContainerRestart` at https://github.com/docker/docker/blob/master/api/server/server.go#L952 like `intValue(r.Form.Get("t"))`

### PR DESCRIPTION
**Pull request by adcaes**
Fixes #12607 

Signed-off-by: Adria Casas adriacasas88@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
:+1: but I'd rather put `intValue(r, "t")` directly inside function call though

**Comment by adcaes** [comment]
@runcom I thought it made the code a bit more readable, but it is also less compact, so I have changed it as you suggested :)

**Comment by runcom** [comment]
@adcaes thanks!

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
:sparkles: LGTM :sparkles:

**Comment by duglin** [comment]
There are other Atoi's in there, any reason you didn't do those too?

**Comment by jfrazelle** [comment]
we might as well clean em all up, or not abstract this out

**Comment by calavera** [comment]
@adcaes can you replace all the `Atoi` calls in `api/server/server.go`. That way the file remains consistent.

**Comment by adcaes** [comment]
Makes sense, will do that.

**Comment by adcaes** [comment]
@calavera I have done as you recommended and replaced all `Atoi` calls to parse form fields in `api/server/server.go` with `intValue`. For consistency I have also replaced `ParseInt` calls with the already existing `int64Value`.

**Comment by adcaes** [comment]
I have realized the last modification makes a test checking that container resize fails if providing non int for height and width returns internal server error, whereas with the new approach parsing int parameters sets the value of the parameter to zero on parsing error. The test is https://github.com/docker/docker/blob/master/integration-cli/docker_api_resize_test.go#L25

Would appreciate some ideas on how to proceed; I could delete the test, or maybe this prove that defaulting to zero on error is not a good idea and is better to return Internal Server Error. In that case we should not use get rid of int64Val and intVal helper functions or modify their behavior to return error on parsing error.

**Comment by runcom** [comment]
ouch, I wrote that test lol and yes indeed that's a case where a parsing error is needed. IHMO we should modify the `intVal` and `int64Val` to just return an error and not trick the behaviour of `strconv.ParseInt` in those function to return `0` on error.
Better handling any default value on error in the caller so if `intVal` or `int64Val` returns an error the caller could manage to set any default value or raise the error received.
I think it's not `intVal` or `int64Val` to return default value.
@calavera @duglin @jfrazelle wdyt?

**Comment by duglin** [comment]
I'm not keen on hiding parsing errors either.  IMO if we convert "foo" to zero the client may get unexpected results and that would be bad.  I would much prefer to generate an error and stop.  Whether that's done in a common util func or in-line, I don't care much - as long as we're consistent about it.

**Comment by duglin** [comment]
To be clear, I'm not thrilled with the current int64Value either.

**Comment by LK4D4** [comment]
We need to keep old behavior. Apart from this I'm totally okay with checking errors

**Comment by runcom** [comment]
@calavera are you ok in removing int64Value and intValue due to if they return errors they're just proxy to strconv?

**Comment by calavera** [comment]
as @LK4D4 mentions, those methods need to keep the old behavior. Unfortunately, the old behavior means that "asdf" returns 0. I'm not supper happy about it either, though. I'll leave it up to you, but I'd rather not rewrite all the client/server interactions just yet.

**Comment by adcaes** [comment]
So my suggestion would be to get rid of int64Value (and ofc not adding intValue), to make clear that is not the desired way to handle errors, but keeping the current behavior in the only endpoint that uses int64Value, and leave all the other endpoints as they were. Anyone that disagrees?

**Comment by runcom** [comment]
@adcaes I'd go with directly using strconv if everyone's happy with this

**Comment by adcaes** [comment]
@runcom, could you be a bit more specific. Do you mean getting rid of int64value but keeping the current behavior (use 0 when parsing error) in the places where int64value is used, or also return an error in those cases?

**Comment by runcom** [comment]
@adcaes I mean removing int64Value and not adding intValue and just use strconv with err and timeout checking in the server controllers

**Comment by adcaes** [comment]
@runcom what do you suggest for the use of int64Value in https://github.com/docker/docker/blob/master/api/server/server.go#L1334 ?
I assume we have to keep the current behavior, so continue using something like int64Value. I could rename it to int64ValueOrZero, the name is not very nice, but shows what the function really does.

**Comment by runcom** [comment]
@adcaes yes I've seen in some other pr (windows ones IIRC) `intValueOrDefault` (insted of `Zero`). I don't dislike this but let's hear maintainers too

**Comment by tiborvass** [comment]
@adcaes sorry needs a rebase!

**Comment by runcom** [comment]
also why @GordonTheTurtle added os/windows

**Comment by tiborvass** [comment]
@runcom idk it's acting weird. Can you remove the label?

**Comment by runcom** [comment]
@tiborvass pretty sure I cannot do that :smile:

**Comment by adcaes** [comment]
@runcom I have modified the commit and now it is only renaming `int64Value` to `int64ValueOrZero`. We could also use `int64ValueOrDefault` following the style in https://github.com/docker/docker/blob/master/pkg/term/winconsole/term_emulator.go#L225, though in this case the default would always be zero.

**Comment by runcom** [comment]
@adcaes thank you, what about the original issue? it should be implemented in this pr right? (it was about containerRestart default value, or am I missing something?)

**Comment by adcaes** [comment]
@runcom After the discussion in this PR I was under the impression that hiding parsing errors is not desired, so I thought we didn't want to implement the original issue. 

Please correct me if I misunderstood and we still want to default to zero on non parseable int in the timeout parameter used in ContainerRestart at https://github.com/docker/docker/blob/master/api/server/server.go#L920 as requested in the original issue.

**Comment by runcom** [comment]
@adcaes right (sorry forgot), if other maintainers are ok with this I'm ok on this since we need to keep old behaviour

**Comment by calavera** [comment]
this change LGTM.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
