### PR TITLE
gitignore: cleanup some not needed entries

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by runcom** [comment]
LGTM :smile:

**Comment by thaJeztah** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🕊

**Comment by icecrime** [comment]
Is that a flaky test? (cc @calavera @thaJeztah)

```
16:58:59 FAIL: docker_cli_build_test.go:4872: DockerSuite.TestBuildNotVerboseFailure
16:58:59 
16:58:59 docker_cli_build_test.go:4892:
16:58:59     c.Fatal(fmt.Errorf("Test[%s] expected that quiet stderr and verbose stdout are equal; quiet [%v], verbose [%v]", te.TestName, qstderr, vstdout+vstderr))
16:58:59 ... Error: Test[quiet_build_not_exists_image] expected that quiet stderr and verbose stdout are equal; quiet [Sending build context to Docker daemon 2.048 kB


16:58:59 Step 1 : FROM busybox11
16:58:59 Get https://registry-1.docker.io/v2/library/busybox11/manifests/latest: EOF
16:58:59 ], verbose [Sending build context to Docker daemon 2.048 kB


16:58:59 Step 1 : FROM busybox11
16:58:59 Pulling repository docker.io/library/busybox11
16:58:59 Error: image library/busybox11 not found
16:58:59 ]
```

**Comment by vdemeester** [comment]
@icecrime looks like it :sweat_smile: 
Let's create an issue to investigate :wink:

**Comment by tonistiigi** [comment]
This breaks the vendor script for the Vagrantfile: https://jenkins.dockerproject.org/job/Docker-PRs-vendor/476/console #21261

**Pull request merged**
