### PR TITLE
fix lxc build

### PR DESCRIPTION
**Pull request by jessfraz**
fix for if `c.Network` is `nil` and bad test.

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM (FYI for reviews the [same test](https://github.com/docker/docker/blob/edb7e84ddbe8df4767e7249c76551ce69d68e8f4/daemon/execdriver/native/create.go#L92-L94) exists on the native driver side).

**Comment by jfrazelle** [comment]
its green! merge it ;D

**Comment by LK4D4** [comment]
LGTM

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
