### PR TITLE
zfs: expose mountpoint/dataset on inspection

### PR DESCRIPTION
**Pull request by kim0**

### CODE REVIEW

**Review by AkihiroSuda — COMMENTED** [review]
This code cannot  be compiled

**Comment by thaJeztah** [comment]
```
14:16:43 # github.com/docker/docker/daemon/graphdriver/zfs
14:16:43 daemon/graphdriver/zfs/zfs.go:223: cannot use [][2]string literal (type [][2]string) as type map[string]string in return argument
14:17:10 Unable to find image 'busybox:latest' locally
14:17:11 latest: Pulling from library/busybox
```

**Comment by vdemeester** [comment]
ping @kim0 : could you fix the compilation errors and add a description on the use case for this PR ?

**Comment by kim0** [comment]
@vdemeester .. The use case is: When running docker on zfs backend, zfs creates a zfs dataset per container. The name of this dataset currently is buried inside the zfs driver and there is no way to extract it. This patch enables extracting the volume (dataset) name through normal `docker inspect`. The benefit of exposing the dataset name, is the ability to revert a docker container to an earlier image through its zfs snapshot. As well as the ability to migrate it to a different host through a zfs send | recv operation. Roughly all the benefits of using zfs, need this patch!

Unfortunately however I am unable to fix it, as this patch was sent to me by the docker zfs driver maintainer. I submitted it on his behalf, and unfortunately it seems he wrote it based on older docker codebase. If anyone has the ability to fix it (the fix is probably a tiny nudge), please do or let me know how!

**Comment by kim0** [comment]
@mic92 if you can take a look why this is failing and update the patch, let me know! As I mentioned earlier, I can donate a cloud server for you to work from if that helps with the bandwidth issues you might be facing. Thanks!

**Comment by Mic92** [comment]
@kim0 Shortly after I had posted my patch, I had updated it: https://github.com/docker/docker/issues/27504#issuecomment-257281969

**Comment by Mic92** [comment]
I think in order to get this merged, you should squash everything into a single commit, which is also signed off. If you update your commit, use `git-rebase` instead of `git-merge`.

**Comment by kim0** [comment]
@vdemeester .. I updated the pull-request. Is this failure on Windows real? I doubt it, since zfs can't even run there.

**Comment by kim0** [comment]
@vdemeester .. Thanks! Hope this can make it in the next 1.14 :)

**Comment by 00angus** [comment]
Wow, great :)
Thank you all, for your efforts :) Really appreciated here!

**Comment by AkihiroSuda** [comment]
The code itself is LGTM, other storage drivers provides similar metadata as well.

However, some questions about the usecase...

> The benefit of exposing the dataset name, is the ability to revert a docker container to an earlier image through its zfs snapshot. 

Why not use data volume?

> As well as the ability to migrate it to a different host through a zfs send | recv operation. 

Why not use registry?

**Comment by kim0** [comment]
Thanks for the LGTM. I have to say, your "why not use X" make a lot of sense. For example, an immutable stateless container should indeed keep all data in a volume. However, some of the non-ideal containers I'm working with, have accumulated internal state. zfs snapshots allow me granular light-weight snapshots every 5 mins, which is something I quite like. 

Another real-life use-case, is I'm running many production containers. They and their data volumes live on a zfs-pool (zpool). I want to regularly backup all containers and their data-volumes, and ship them to a remote host (send | recv). I want to know that the image I just backed up, has an atomic view of the containers and their data-volumes. I want the process to be as light weight and transparent as possible. zfs backend provides all that, while docker tooling without zfs is slightly worse user-experience, at least for me.

In all cases, I guess docker should not actively hide where it keeps my data. The operator should decide what they want to do, and as you mentioned other storage drivers offer the same capability. 

Thanks

**Comment by Mic92** [comment]
I see also some other use cases, where people want to set additional dataset options for individual containers, which is currently not possible through docker cli.

**Review by vdemeester — APPROVED** [review]
LGTM
/cc @thaJeztah @cpuguy83 @tonistiigi

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
