### PR TITLE
Update AWS SDK to latest release 1.4.22

### PR DESCRIPTION
**Pull request by rheinwein**
This change updates `aws/aws-sdk-go` to the most recent version.

The sdk update includes the move from `aws-sdk-go/private/signer/v4` to `aws-sdk-go/aws/signer/v4`, which (depending on your flavor of dependency management) was causing some conflicts on fresh projects that rely on `docker/docker`. 

**\- How I did it**
- update `hack/vendor.sh` with new package tag
- run `hack/vendor.sh`

**\- Description for the changelog**
Update aws-sdk-go to release 1.4.22

**\- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by justincormack** [comment]
The vendor script is failing, but I don't know that is your fault, let me take a look.

**Comment by justincormack** [comment]
Hmm, no there seems to be an issue with `vendor/src/golang.org/x/sys/unix` and `vendor/src/github.com/docker/libnetwork/drivers/solaris`

**Comment by rheinwein** [comment]
@justincormack curses. I'll look at it a bit more and fix. Thanks!

**Comment by justincormack** [comment]
I just tested and it is passing in master, so its probably just being spiteful. Hopefully soon we can get rid of the custom vendor script pain!

**Comment by thaJeztah** [comment]
Wowza 
screen shot 2016-10-28 at 5 40 02 pm

it was already huge. Are they adding a whole new SDK with each update?

**Comment by thaJeztah** [comment]
@rheinwein the PR title says 1.4.22, but the commit says 1.3, or am I looking at the wrong version number 😅 ?

**Comment by thaJeztah** [comment]
ping @samuelkarp is there some way to get a smaller dependency for the logging drivers? As mentioned, the dependency was already huge, but this is becoming even more huge.

**Comment by samuelkarp** [comment]
@thaJeztah Looking at `git show cc45e1006b6a12fd54bbd323d229be1462fc67db --summary` and the list of files, this commit includes:
* Two new credential providers for AWS credentials
 * The [`endpointcreds`](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/endpointcreds/) provider that gets used for [IAM roles for Amazon ECS tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) (likely not used, since the ECS agent typically runs as a Docker container and wouldn't set the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable for the Docker daemon, but it's in the default credential handler chain, so it gets included).
 * The [`stscreds`](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/) provider that provides [assume role](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) capability to the SDK (this may get used depending on how a customer configures their credentials).
* Updates to the v4 signer (called out by @rheinwein)
* Support for the [`query`](https://github.com/aws/aws-sdk-go/tree/master/private/protocol/query) protocol, which is used by the [`sts` client](https://github.com/aws/aws-sdk-go/blob/131bbf45b9ca5611021fa1dcdd16c803502eb2d8/service/sts/service.go#L105-L109)
* The libnetwork Solaris bridge driver (no idea where this is coming from, it's definitely not imported by the AWS SDK for Go)
* The `golang.org/x/sys/unix` package (probably imported by the libnetwork Solaris bridge driver)

I think the bulk of the commit is caused from the new protocol being imported and from vendoring `golang.org/x/sys/unix` (and I don't know why that's in the same commit).

What are your concerns about the size of the SDK?  I'm happy to pass along any feedback you have to our SDK team.

**Comment by rheinwein** [comment]
@thaJeztah  Yeah, I bumped it down to 1.3 to see if I could troubleshoot the issues with the vendor check, but (as you can see) it didn't help much. :) I'll move it back to 1.4.22 today. Sorry for huge-ifying something that's already huge!

**Comment by rheinwein** [comment]
@justincormack @thaJeztah -- As @samuelkarp pointed out (thanks!), the root issue with this PR being so big is that it adds two new packages: `vendor/src/github.com/docker/libnetwork/drivers/solaris/` and `vendor/src/golang.org/x/sys/unix/`.

In the vendor script, we reference `libnetwork` at [f4338b6](https://github.com/docker/libnetwork/tree/f4338b6f1085ccfe5972e655cca8a1d15d73439d/drivers), which definitely includes the new solaris driver, but it's not in `vendor` on master: https://github.com/docker/docker/tree/master/vendor/src/github.com/docker/libnetwork/drivers 

Therefore, just  running the vendor script on master also results in adding these two packages -- outside of the scope of this PR. Were they left out of `vendor` intentionally? If not, is it best to open a separate PR to fix those missing deps, then rebase this one?

**Comment by samuelkarp** [comment]
@thaJeztah If you have any concerns about the SDK I know @jasdel is interested in hearing them.

**Comment by vdemeester** [comment]
This is weird… I do have the same result as the `vendor` ci check… I don't know why running `./hack/vendor.sh` would add `golang.org/x/sys/unix/` or `github.com/docker/libnetwork/drivers/solaris/` to the vendored folder but it should definitely not :sweat: (and it does not on my laptop or the ci either).

**Comment by vdemeester** [comment]
Carried in #27907 👼

**Pull request closed without merging**
