### PR TITLE
allow vendoring of test packages

### PR DESCRIPTION
**Pull request by jessfraz**
allow vendoring of deps that are only in test files

ping @tianon 

@icecrime this solves your prob in https://github.com/docker/docker/pull/16229, you can cherry-pick to test ;)

### CODE REVIEW

**Comment by icecrime** [comment]
`ln: ‘.gopath/src/..’: cannot overwrite directory` :crying_cat_face:

**Comment by jfrazelle** [comment]
Shit I didn't force push ugh lol

**Comment by jfrazelle** [comment]
hmmm nope i think that is the same :/

**Comment by jfrazelle** [comment]
idk do you still get the error?

**Comment by icecrime** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
