### PR TITLE
api/client/build: typo in error

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts vbatts@redhat.com

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by cpuguy83** [comment]
Don't need any of this direcotry!

LGTM

**Comment by vbatts** [comment]
silly window failed.. Rebuilding and fixed three moar direcotrys.

**Comment by calavera** [comment]
I think the problem here was that the previous word didn't have the proper dashes: `direc-o-try`. :trollface: 

But this LGTM anyways. Merging since the silly windows flacky errors are unrelated.

**Pull request merged**
