### PR TITLE
fix "fatal error: concurrent map read and map write" bugs when we concurrently execute lots of delete volumes and create or list volumes tasks

### PR DESCRIPTION
**Pull request by KevinTHU**
**- What I did**
The globalLock use of struct type VolumeStore is not very correct in docker volume packages, sometimes it will cause "fatal error: concurrent map read and map write" because we concurrently execute lots of delete volumes and create or list volumes tasks. Add globalLock.Lock for read tasks will resolve this error, but the performance of docker would be lower too much, so I change type of globalLock from sync.Mutex to RWMutex, and all read task codes are around with globalLock.RLock, then the concurrent error will not happen, and the performance would not be lower too much either.

**- How I did it**
change VolumeStore.globalLock type from Mutex to RWMutex, and add globalLock.RLock() for the read task codes of names, refs, labels and options in VolumeStore

**- How to verify it**
concurrently execute lots of delete volumes and create or list volumes tasks, and docker will never down like before.

**- Description for the changelog**
none

**- A picture of a cute animal (not mandatory but encouraged)**
none

Signed-off-by: He Xin <he_xinworld@126.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
SGTM, but it doesn't compile 
```
00:02:19.200 # github.com/docker/docker/volume/store
00:02:19.200 volume/store/store.go:556: s.globalLock.UnLock undefined (type sync.RWMutex has no field or method UnLock, but does have Unlock)
```

**Comment by KevinTHU** [comment]
@AkihiroSuda sorry, I have no build enviroment, I will re PR it again~~=_=!!

**Comment by AkihiroSuda** [comment]
Oh, you didn't have to close this PR 

```
$ git commit -a -s --amend
$ git push -f
```

:+1:

**Comment by KevinTHU** [comment]
yeah, I just know that, but this is a good help, thx~

**Pull request closed without merging**
