### PR TITLE
Make daemon events listen for plugin lifecycle events.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
engine-api vendoring required.

Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
@anusha-ragunathan experimental failure is a panic from plugins: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x649db1]

goroutine 1 [running]:
panic(0x1b21a80, 0xc820014080)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/plugin.(*Manager).Shutdown(0x0)
	/go/src/github.com/docker/docker/plugin/manager_linux.go:133 +0xa01
github.com/docker/docker/daemon.pluginShutdown()
	/go/src/github.com/docker/docker/daemon/daemon_experimental.go:15 +0x23
github.com/docker/docker/daemon.(*Daemon).Shutdown(0xc820406820, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:690 +0x3e5
github.com/docker/docker/daemon.NewDaemon.func1(0xc82020b948, 0xc820406820)
	/go/src/github.com/docker/docker/daemon/daemon.go:461 +0x37
github.com/docker/docker/daemon.NewDaemon(0xc820135880, 0x7f3eb9df4ed8, 0xc820028190, 0x7f3ebb62ef98, 0xc8203ef450, 0x0, 0x7f3ebb628028, 0xc820411770)
	/go/src/github.com/docker/docker/daemon/daemon.go:531 +0x1c6c
main.(*DaemonCli).start(0xc8203edce0, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:265 +0x1956
main.main()
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x491

```

**Comment by thaJeztah** [comment]
ping @tiborvass added this to 1.12, but wasn't sure if it's critical for 1.12

**Comment by anusha-ragunathan** [comment]
@thaJeztah : Its a nice-to-have, not 1.12 critical.

**Comment by anusha-ragunathan** [comment]
@tonistiigi : panic resolved. experimental failure is unrelated and caused after the tests passed and at a time when the windows slave went offline while the packages were being created. Unrelated.

**Comment by thaJeztah** [comment]
ping @vdemeester @cpuguy83 PTAL 😇

**Comment by vdemeester** [comment]
@anusha-ragunathan needs vendoring update (now it's merged 👼)
Once vendoring done, LGTM 🐹

**Comment by vdemeester** [comment]
@thaJeztah @anusha-ragunathan this might need documentation updates (on events) but I wonder how to *distinguish* experimental events from the others ?

**Comment by thaJeztah** [comment]
@vdemeester good point; perhaps "plugin load (experimental)" on the list with event-types. FWIW; I'm okay with doing it in a follow up as long as we have an issue to track it.

also, ping @tiborvass PTAL

**Comment by anusha-ragunathan** [comment]
@vdemeester @thaJeztah : I dont think that is necessary. For example, we don’t mark the plugin CLI explicitly as experimental. On a similar vein, we dont need to mark experimental events. Once daemon is experimental, the entire plugin feature is considered experimental.

**Comment by anusha-ragunathan** [comment]
FYI, I just tested filtering plugin events by name and ID and it doesnt work. Will fix it soon.

**Comment by thaJeztah** [comment]
@anusha-ragunathan https://github.com/docker/docker/pull/24932 also bumps engine-api, so depending on which one is merged first, one of us has to rebase :)

**Comment by vdemeester** [comment]
@anusha-ragunathan what I mean is, in the online [event documentation](https://docs.docker.com/engine/reference/commandline/events/) (and probably man pages ?), should we display the plugin events or not ? 
We do document experimental command, like [plugin install](https://docs.docker.com/engine/reference/commandline/plugin_install/), … but events that are only fired in experimental, I don't know 👼

**Comment by anusha-ragunathan** [comment]
@thaJeztah : You beat me to it :) 
@vdemeester : I agree. What I meant was, there is no need to change the events themselves to say "plugin (experimental)". It can be covered in docs.

**Comment by tiborvass** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
@vdemeester @thaJeztah : Filtering by plugin ID and name works. Also added docs. PTAL.

**Comment by thaJeztah** [comment]
retest this please

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
actually, looks like the failing CI is related;
https://jenkins.dockerproject.org/job/Docker-PRs-experimental/21623/console

```
8:14:32 ----------------------------------------------------------------------
18:14:32 FAIL: docker_cli_events_test.go:300: DockerSuite.TestEventsPluginOps
18:14:32 
18:14:32 docker_cli_events_test.go:318:
18:14:32     c.Assert(pluginEvents, checker.HasLen, 4, check.Commentf("events: %v", events))
18:14:32 ... obtained []string = []string(nil)
18:14:32 ... n int = 4
18:14:32 ... events: [2016-07-25T18:14:32.525893140Z plugin pull 6db34ea49fa3c14be4687d45e8f1fa260b5c250b1ee9dc0c5c32c223f955202c (name=tiborvass/no-remove:latest) 2016-07-25T18:14:32.600123673Z plugin enable 6db34ea49fa3c14be4687d45e8f1fa260b5c250b1ee9dc0c5c32c223f955202c (name=tiborvass/no-remove:latest) 2016-07-25T18:14:32.614796033Z plugin disable 6db34ea49fa3c14be4687d45e8f1fa260b5c250b1ee9dc0c5c32c223f955202c (name=tiborvass/no-remove:latest) 2016-07-25T18:14:32.627199859Z plugin remove 6db34ea49fa3c14be4687d45e8f1fa260b5c250b1ee9dc0c5c32c223f955202c (name=tiborvass/no-remove:latest)]
18:14:32 
```

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
