### PR TITLE
Vendor engine-api with client context changes.

### PR DESCRIPTION
**Pull request by calavera**
~~This is blocked by https://github.com/docker/engine-api/pull/74.~~

### CODE REVIEW

**Comment by cpuguy83** [comment]
/tmp/go-build063489455/github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:224: undefined: sockets.ConfigureTCPTransport

**Comment by calavera** [comment]
It also depends on https://github.com/docker/engine-api/pull/76

**Comment by thaJeztah** [comment]
ping @calavera https://github.com/docker/engine-api/pull/76 was merged

**Comment by calavera** [comment]
rebased. :fingers_crossed:

**Comment by estesp** [comment]
I don't know if it matters as we can do another vendoring soon, but docker/engine-api#71 would be helpful to get in so we can finish up that long-standing "get C/R in experimental" PR..

**Comment by calavera** [comment]
@estesp having this in is blocking other PRs, I rather have it in as soon as possible. We can vendor again with more specific changes.

**Comment by estesp** [comment]
@calavera works for me, thanks

**Comment by anusha-ragunathan** [comment]
Rest of 6e2c3b7 looks okay.

**Comment by calavera** [comment]
It looks like this doesn't build on Win 386: https://github.com/Microsoft/go-winio/issues/2

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by tiborvass** [comment]
win2lin passed CI, but then got stuck for some reason. Merging

**Pull request merged**
