### PR TITLE
Update Windows TP3 registry endpoints

### PR DESCRIPTION
**Pull request by icecrime**
Ping @dmp42 @jhowardmsft.

### CODE REVIEW

**Comment by dmp42** [comment]
Thanks @icecrime
LGTM

**Comment by jhowardmsft** [comment]
Perfect :) LGTM

**Comment by icecrime** [comment]
Nevermind, search will still not work. Sorry for the noise.

**Comment by icecrime** [comment]
Reopened as a simpler alternative to #15678.

**Comment by tiborvass** [comment]
@swernli can you test `docker search` and `docker login` on this PR please?

**Comment by swernli** [comment]
Testing now...

**Comment by swernli** [comment]
docker search works.  Login displays the right default server in the error message (https://registry-win-tp3.docker.io/v1/)) but I don't have a username/password to actually test logging in all the way.

**Comment by tiborvass** [comment]
@swernli Welcome to the sign up page https://hub.docker.com/ :P

**Comment by tiborvass** [comment]
@swernli are you testing windows to windows and windows to linux?

**Comment by swernli** [comment]
I'm testing Windows to Windows... I don't currently have a Linux machine for the other scenarios.

**Comment by tiborvass** [comment]
@swernli ok thanks no problem i can test windows to linux

**Comment by tiborvass** [comment]
`docker search` works fine on windows 2 linux, it does the search from the hub.
However `docker login` outputs `Username:` but doesn't show my username when i type it.

**Comment by tiborvass** [comment]
I can confirm `docker login` doesnt work with `1.8.1` either, so this PR is good to go on my end (tested with windows 2 linux)

LGTM

**Comment by tiborvass** [comment]
@swernli just to confirm, `docker search` on windows to windows, returns the list of windows images, not linux ones, correct?

**Comment by jfrazelle** [comment]
LGTM

**Comment by swernli** [comment]
@tiborvass Yup, it showed the Windoes images, and I was even able to try pulling them with the friendly names.

**Comment by tiborvass** [comment]
@swernli thanks for confirming

**Pull request merged**
