### PR TITLE
[WIP] Add `docker daemon` to bash completion

### PR DESCRIPTION
**Pull request by albers**
This amends #13771. It assumes that the changes to bash completion in that PR are removed.
ping @tianon @jfrazelle for review
ping @tiborvass @thaJeztah 

Also renamed `$main_options_with_args` to `$global_options_with_args` to make its intent clearer.
Got rid of `$global_options_with_args_glob` by inlining.
Will add the zfs storage driver in another PR.

### CODE REVIEW

**Comment by thaJeztah** [comment]
you're awesome, @albers! I'm not very well at these scripts to review, just :heart:

**Comment by tiborvass** [comment]
Thanks @albers would you mind closing this PR until the other one is merged? You can then reopen it before pushing to the branch. We don't like to have dependencies among PRs :) Thanks for your work though, really appreciated.

**Comment by albers** [comment]
Temporarily closed as requested by @tiborvass.

**Comment by albers** [comment]
Reopening as #13771 is merged.

**Comment by albers** [comment]
Will take care of the conflicts in about a week.

**Comment by thaJeztah** [comment]
I added this to the 1.8 milestone, because it's part of https://github.com/docker/docker/pull/13771

ping @calavera for https://github.com/docker/docker/pull/13934#issuecomment-124369968, because I don't know when code-freeze is for 1.8 (but I assume we can get this in during the release-candidates as well)

**Comment by albers** [comment]
There was a discussion recently that the completions are sort of tooling and therefore should not be strictly impacted by code freeze, see [here](https://github.com/docker/compose/pull/1325#issuecomment-107205342).
I hope others share this view. Changes to completion always come in late.

**Comment by icecrime** [comment]
@albers Needs rebase, sorry!

**Comment by albers** [comment]
No problem, rebase is mostly due to changes of my own.

**Comment by tiborvass** [comment]
@albers sorry need a rebase :)

Also, the "global flags" (-D, --tls, ...) are now valid after the `daemon` command. And having them before the `daemon` command is invalid, even though we can't really help the user in the autocompletion..

**Comment by calavera** [comment]
@albers did you have time to look into this? I'd :heart: to have it ready for the RC2.

**Comment by albers** [comment]
@calavera I will do it on friday. Sorry, can't get to it earlier.

**Comment by tiborvass** [comment]
@albers no problem I'll carry it. Thanks for your help so far!

**Comment by tiborvass** [comment]
Carried in #15166

**Pull request closed without merging**
