### PR TITLE
read seccomp profile locally then pass to daemon

### PR DESCRIPTION
**Pull request by jessfraz**
Signed-off-by: Jessica Frazelle acidburn@docker.com

### CODE REVIEW

**Comment by justincormack** [comment]
This fixes adding custom seccomp filters when using docker-machine. LGTM.

**Comment by jfrazelle** [comment]
ping @cpuguy83 :innocent:

**Comment by cpuguy83** [comment]
So the seccomp profile will be loaded from the client?

**Comment by jfrazelle** [comment]
yes and passed to daemon

**Comment by cpuguy83** [comment]
What if the profile is on the daemon?

**Comment by justincormack** [comment]
If it has to be on the daemon you need a whole config management setup to get it there, which makes it complex. But mainly, it is part of the runc spec, which should all come from the same place, not be assembled from parts on the client and parts on the server. All the other parameters for how to run a container, eg the capabilities come from the client. The fact it is in a file is just because it is a bit big to type on the command line...

**Comment by cpuguy83** [comment]
Oh I agree, but doesn't the other security profiles come from the daemon side and not the client?
Is there a way to still use a file on the daemon?

**Comment by justincormack** [comment]
I think it is a bug if they do as well. I think I may have just been the first person to notice in this case.

**Comment by jfrazelle** [comment]
well its not really a bug because apparmor is not a file it is a string of a profile name

**Comment by justincormack** [comment]
Processing the apparmor file format client side would be a bit of a pain because of inclusions etc and the host would need tooling, so it is a bit more problematic. seccomp already has a json format, so it is better to do the right thing...

**Comment by cpuguy83** [comment]
Yep makes sense to me.
Can you add an integration test for this?

**Comment by jfrazelle** [comment]
Something for just testing client is passing to daemon... I couldn't think of something that would break on master but there are tests that pass profiles, do you have an idea... Sorry been a long day brain kinda fried :)

**Comment by cpuguy83** [comment]
@jfrazelle There's tests that test the client reading a file and passing it to the daemon?

**Comment by jfrazelle** [comment]
theres a few here https://github.com/docker/docker/blob/master/integration-cli/docker_cli_run_unix_test.go#L727 I can add more tho

**Comment by cpuguy83** [comment]
@jfrazelle Ah, that one is good, but I think can remove SameHostDaemon now?

**Comment by crosbymichael** [comment]
Does this change the semantics on what is an ops concern and dev concern if the profile comes from the client and there is not a way to see it on the daemon side?

**Comment by jfrazelle** [comment]
true i am unsure how to solve tho, ideally, the dev would be the ones
writing the profile since they know what syscalls should be allowed

**Comment by justincormack** [comment]
The profile is currently a dev concern, as it is per `docker run` (if specified), and your code may not work with a different profile. Ops might want to specify a profile too on the daemon I guess (and they are stackable so thats ok), but I think we need to have more real world experience first.

**Comment by cpuguy83** [comment]
The profile is in the container's inspect output

Though I did notice it's weirdly escaped.

```json
            "SecurityOpt": [
                "seccomp:{\n\t\"defaultAction\": \"SCMP_ACT_ALLOW\",\n\t\"syscalls\": [\n\t\t{\n\t\t\t\"name\": \"unshare\",\n\t\t\t\"action\": \"SCMP_ACT_ERRNO\"\n\t\t}\n\t]\n}\n"
            ]
```

**Comment by jfrazelle** [comment]
because securityOpt is a map[string]string I dont unmarshal until it gets
to the daemon... unless we want to change that type for this api version

**Comment by jfrazelle** [comment]
its a little hokey becuase allthingsOpt, storageOpt, etc are
map[string]string :(

**Comment by crosbymichael** [comment]
If this is going to go through the API do you think we need to version the type so that it is not broken by accident?

**Comment by jfrazelle** [comment]
like type `string[]` as something else here https://github.com/docker/engine-api/blob/master/types/container/host_config.go#L224

**Comment by crosbymichael** [comment]
I mean the json that is being shoved in that string.  It has a format and is expected on both sides so if its changed in the future clients are going to break if its not versioned.

**Comment by jfrazelle** [comment]
ohhh sorry

**Comment by jfrazelle** [comment]
this relies on https://github.com/docker/docker/pull/19243

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
