### PR TITLE
Modify incorrect punctuation

### PR DESCRIPTION
**Pull request by EnergyLiYN**
Signed-off-by: yanan Lee <energylyn@zju.edu.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Could you please update existing pull requests, instead of closing, and opening a new one? (https://github.com/docker/docker/pull/29595) see the contributors guide https://docs.docker.com/opensource/workflow/work-issue/ for tips/hints

**Comment by thaJeztah** [comment]
Also, I'm not sure if these need updating; the curly quotes are actually the correct ones to use, but they are not used in most places.

In addition _if_ we want to update this; the same text is present in all versions of the API documentation  (see https://github.com/docker/docker/search?utf8=✓&q=%22“cpu_stats”%22, although GitHub only shows the first occurrence in a file

**Review by thaJeztah — CHANGES_REQUESTED** [review]
I personally don't think it's worth updating these, as they are not really incorrect, but possibly other maintainers think it's worth updating

**Comment by thaJeztah** [comment]
Also see http://practicaltypography.com/straight-and-curly-quotes.html

**Comment by AkihiroSuda** [comment]
Seems a dupe of https://github.com/docker/docker/pull/29572

**Pull request closed without merging**
