### PR TITLE
devmapper: Break down setupBaseImage() function into smaller pieces

### PR DESCRIPTION
**Pull request by rhvgoyal**
Right now setupBaseImage() function is doing lots of things and doing more changes in this code is little hard. So break down this function into smaller functions so that it is little easier to understand the code and make changes to it.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
CC @LK4D4 @calavera @vbatts

**Comment by LK4D4** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
