### PR TITLE
fix double [y/N] in container prune

### PR DESCRIPTION
**Pull request by vieux**
ping @mlaventure

### CODE REVIEW

**Comment by mlaventure** [comment]
LGTM

**Comment by tiborvass** [comment]
Why was it bad?

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by thaJeztah — APPROVED** [review]
LGTM [y/N]

**Comment by vieux** [comment]
@tiborvass `[y/N]` is already added in the helper function.

```
 $ docker container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N]  [y/N] ^C
```

**Pull request merged**
