### PR TITLE
WIP: Move networking settings from createOption to oci runtime-spec

### PR DESCRIPTION
**Pull request by darstahl**
Signed-off-by: Darren Stahl <darst@microsoft.com>

**- What I did**

Moved networking options from libcontainerd createOption to OCI runtime-spec

**- How to verify it**

Networking still works. Existing CI tests.

See https://github.com/opencontainers/runtime-spec/pull/801 for runtime-spec PR

/cc @jhowardmsft @jstarks

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Overall, changes look good. Obviously requires the OCI change to be merged and a re-vendor.

**Comment by MHBauer** [comment]
@darrenstahlmsft @jhowardmsft rebasing and vendoring yet to do?

**Comment by darrenstahlmsft** [comment]
I think current plan is @jhowardmsft will cherrypick this commit and make a single PR with all the OCI runtime-spec changes for Windows.

**Comment by jhowardmsft** [comment]
Yes that's the plan. And someone might need to carry to fix up the Linux issues subsequently

**Comment by jhowardmsft** [comment]
I'm closing this. Will open a new PR based on https://github.com/Microsoft/docker/tree/jjh/oci-convergence which caters for moving all options, including networking, to the spec ones once the final two OCI PRs are themselves merged.

**Pull request closed without merging**
