### PR TITLE
Update understanding-docker.md again 

### PR DESCRIPTION
**Pull request by vanpire110**
update docs/introduction/understanding-docker.md  again

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM - @moxiegirl @thaJeztah

**Comment by moxiegirl** [comment]
AND that LGTM!

**Comment by thaJeztah** [comment]
merging, failing documentation CI is unrelated.

**Comment by thaJeztah** [comment]
Thanks for your contribution @vanpire110!

**Comment by thaJeztah** [comment]
@vanpire110 in future, please update your existing pull request, instead of opening a new one; that makes it easier for us to keep track and review, thanks!

**Pull request merged**
