### PR TITLE
[17.03.x] Docs cherry picks

### PR DESCRIPTION
**Pull request by thaJeztah**
Cherry-picking;

https://github.com/docker/docker/pull/30731 (8d28fc8fc4db3c89d20679a022ea9cb5d3644b44)
https://github.com/docker/docker/pull/30832 (e8b92f154d68d17a09fa62ef8cd1b72163887c58)
https://github.com/docker/docker/pull/31291 (27c9a6e9c22a6cf0c6dae7f59cf8f7d56a67f560)
https://github.com/docker/docker/pull/31398 (fb5ccc66054df1459d7844e237a2aaae085ec274)
https://github.com/docker/docker/pull/31467 (9321a12115466a46013dd2258cd9ad658d303c48)

ping @vdemeester @mstanleyjones PTAL

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
LOL, what are the chances? 

```
11:13:16 ----------------------------------------------------------------------
11:13:16 FAIL: docker_cli_secret_create_test.go:55: DockerSwarmSuite.TestSecretCreateResolve
11:13:16 
11:13:16 [dc1550f165a0f] waiting for daemon to start
11:13:16 [dc1550f165a0f] daemon started
11:13:16 docker_cli_secret_create_test.go:86:
11:13:16     c.Assert(out, checker.Not(checker.Contains), name)
11:13:16 ... obtained string = "" +
11:13:16 ...     "ID                          NAME                        CREATED                  UPDATED\n" +
11:13:16 ...     "2d32d0j1foonh0nvdjg8dr2gd   vomwk5g8qv97fjrmds4h8ub5j   Less than a second ago   Less than a second ago\n"
11:13:16 ... substring string = "foo"
11:13:16 
11:13:16 [dc1550f165a0f] exiting daemon
```

`2d32d0j1foonh0nvdjg8dr2gd`, yup, that contains `foo` :joy:

**Comment by thaJeztah** [comment]
anyway, not related, so merging :smile:

**Pull request merged**
