### PR TITLE
Refactor container validation

### PR DESCRIPTION
**Pull request by thaJeztah**
Follow-up to https://github.com/moby/moby/pull/38382

### CODE REVIEW

**Comment by kolyshkin** [comment]
SGTM, and thanks!

**Comment by olljanat** [comment]
@thaJeztah CI fails
```
09:34:20 daemon/container.go:270:2:warning: 'if err != nil { return err }; return nil' can be simplified to 'return err' (S1013) (gosimple)
```

**Comment by thaJeztah** [comment]
Ah, booh.

I saw that one when working on this, but decided not to change it (anticipating possibly more validation steps to be added in future). Forgot about the linter, haha 😢

**Comment by thaJeztah** [comment]
Updated

**Comment by olljanat** [comment]
Derek add label: rebuild/janky

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM :taco:

**Pull request merged**
