### PR TITLE
updating notary to released 0.5.0 version

### PR DESCRIPTION
**Pull request by endophage**
Worked out for some reason rebasing my previous PR against master caused it to drop my commit. Not sure what happened there but here's the notary version bump. Ready to go assuming CI passes.

### CODE REVIEW

**Comment by vdemeester** [comment]
@endophage @tiborvass @thaJeztah @icecrime is this for 1.13 ? :angel:

**Comment by tiborvass** [comment]
@vdemeester According to @endophage no.

**Comment by vdemeester** [comment]
Ok :angel:

**Review by justincormack — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
