### PR TITLE
Add logdrivers to /info

### PR DESCRIPTION
**Pull request by cpuguy83**
This is required for swarmkit to be able to filter based on log driver.

download-1

### CODE REVIEW

**Comment by aaronlehmann** [comment]
```
daemon/logger/factory.go:38:1: exported function ListDrivers should have comment or be unexported
```

**Comment by anusha-ragunathan** [comment]
Adding pluginv2 drivers to `docker info` is not necessary. Swarmkit should query `docker plugin ls` and look for type `LogDriver` for scheduling decisions. This is how its done for volumes and networks.

**Comment by cpuguy83** [comment]
@anusha-ragunathan V2 drivers are not registered in the logger package, only with the plugingetter. So `/info` only ends up returning built-ins and v1.

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by dnephin** [comment]
I moved this to 17.06. I assume it's not making 17.05, right ?

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Yep

**Comment by thaJeztah** [comment]
@cpuguy83 looks like this needs an update to the swagger file?

**Comment by thaJeztah** [comment]
and API changelog

**Comment by mlaventure** [comment]
Oups. Should probably teach Gordon how to detect those :sweat_smile: :angel:

**Pull request merged**
