### PR TITLE
Make version check return 400 instead of 404

### LINKED ISSUE #13321: Client API vs Server API version mismatch shouldn't return 404
I'm using the docker python client without running the ping() call after connecting.
When trying to remove a container (that might not be there) I'm suppressing 404 API errors.
I had a bug in my code since the API returns 404 on version mismatch.

### PR DESCRIPTION
**Pull request by duglin**
Because 404 is just wrong 

Closes: #13321

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by estesp** [comment]
This looks right-- we don't talk about version mismatch in the docs, so it is not defined right now, but 400 makes way more sense than 404.  Do we need a note on version mismatch in the API docs?

code: LGTM

**Comment by duglin** [comment]
docs update wouldn't hurt.  Let me see if I can find a good spot for that.

**Comment by thaJeztah** [comment]
@duglin also needs a note in the "what's new" section of the API

**Comment by runcom** [comment]
+1 and code LGTM

**Comment by thaJeztah** [comment]
thinking of that (and now it becomes complicated); is this to be considered a "breaking change"? If so; should this only be changed for API >= 1.19?

**Comment by duglin** [comment]
@thaJeztah since we're talking about an existing error condition here, and just producing a more appropriate message, I'm leaning towards thinking we don't need to worry about breaking people.  But if other maintainers feel strongly about it I can add the if-stmt.

**Comment by duglin** [comment]
ok - added some doc updates.

**Comment by duglin** [comment]
ping @LK4D4

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
@LK4D4 docs review? 😉

(No worries, I think it's fine :))

**Comment by duglin** [comment]
ping @moxiegirl @fredlf if you guys see anything wrong with the docs please let me know and I'll open a new PR to fix it.

**Comment by moxiegirl** [comment]
@duglin Looks good to me Doug.

**Comment by duglin** [comment]
@moxiegirl great- thanks for checking

**Pull request merged**
