### PR TITLE
Fix issue with concurrent pulls of repositories sharing layers

### LINKED ISSUE #9718: Concurrent pulls fail
This issue seems to be triggered while pulling multiple images which map up to an identical base image.  A reproducible example is below.  This has been reproduced on Ubuntu 14.04 with DeviceMapper and the Amazon ECS-Optimized Amazon Linux AMI.  This has also been reproduced on Docker 1.3.3 and Docker 1.4.1.
```
    [ec2-user@ip-172-31-35-232 ~]$ docker version
    Client version: 1.4.1
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 5bc2ff8
    OS/Arch (client): linux/amd64
    Server version: 1.4.1
    Server API version: 1.16
    Go version (server): go1.3.3
    Git commit (server): 5bc2ff8
    [ec2-user@ip-172-31-35-232 ~]$ 
    [ec2-user@ip-172-31-35-232 ~]$ docker -D info
    Containers: 0
    Images: 0
    Storage Driver: devicemapper
    Pool Name: docker-202:1-1835239-pool
    Pool Blocksize: 65.54 kB
    Data file: /var/lib/docker/devicemapper/devicemapper/data
    Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
    Data Space Used: 307.2 MB
    Data Space Total: 107.4 GB
    Metadata Space Used: 725 kB
    Metadata Space Total: 2.147 GB
    Library Version: 1.02.82-git (2013-10-04)
    Execution Driver: native-0.2
    Kernel Version: 3.14.26-24.46.amzn1.x86_64
    Operating System: Amazon Linux AMI 2014.09
    CPUs: 1
    Total Memory: 1.957 GiB
    Name: ip-172-31-35-232
    ID: 2RCA:OSRS:4M6S:XHJG:MAUC:IYAA:KIGE:K2HM:VBRF:SCXN:LTRD:T3WP
    Debug mode (server): false
    Debug mode (client): true
    Fds: 57
    Goroutines: 58
    EventsListeners: 0
    Init Path: /usr/bin/docker
    Docker Root Dir: /var/lib/docker
    [ec2-user@ip-172-31-35-232 ~]$ uname -a
    Linux ip-172-31-35-232 3.14.26-24.46.amzn1.x86_64 #1 SMP Wed Dec 10 10:02:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    [ec2-user@ip-172-31-35-232 ~]$ docker images
    REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
    [ec2-user@ip-172-31-35-232 ~]$ cat repro
    docker run nginx &
    docker run mysql &
    [ec2-user@ip-172-31-35-232 ~]$ sh repro
    [ec2-user@ip-172-31-35-232 ~]$ Unable to find image 'mysql:latest' locally
    Unable to find image 'nginx:latest' locally
    mysql:latest: The image you are pulling has been verified
     
    f10807909bc5: Pulling fs layer
    f6fab3b798be: Pulling fs layer
    d832c6f40cc3: Pulling fs layer
    cfab4f0d8972: Pulling fs layer
    cf8221608a63: Pulling fs layer
    4755e012c4cf: Pulling fs layer
    e012a865bac8: Pulling fs layer
    e2778dfe9ae9: Pulling fs layer
    b15206a696ec: Pulling fs layer
    9280b0f1af9a: Pulling fs layer
    9f1c487e78cd: Pulling fs layer
    10491040baf9: Pulling fs layer
    d8978d323757: Pulling fs layer
    f10807909bc5: Download complete
    f10807909bc5: Extracting [=================================================> ] 89.69 MB/90.17 MB 0
    d832c6f40cc3: Download complete
    f10807909bc5: Pull complete
    f10807909bc5: Download complete
    f6fab3b798be: Error downloading dependent layers
    d21beea329f5: Download complete
    04499cf33a0e: Download complete
    b15206a696ec: Downloading [====> ] 10.8 MB/118.7 MB 19s
    b15206a696ec: Download complete
    92360dceda1a: Download complete
    9495a555677d: Download complete
    911e2df03930: Download complete
    88daddf047c6: Download complete
    db8a64f62509: Download complete
    e46b3488b010: Download complete
    e46b3488b010: Error pulling image (latest) from nginx, Driver devicemapper failed to create image rootfs f10807909bc552de261ca7463effc467600c3dca68d8e7704425283a6911d2ca: device f10807909bc552de261ca7463effc467600c3dca68d8e7704425283a6911d2ca already exists 3dca68d8e7704425283a6911d2ca already exists
    FATA[0032] Error pulling image (latest) from nginx, Driver devicemapper failed to create image rootfs f10807909bc552de261ca7463effc467600c3dca68d8e7704425283a6911d2ca: device f10807909bc552dea385835786ac: Error pulling image (latest) from mysql, Error mounting '/dev/mapper/docker-202:1-1835239-f6fab3b798be3174f45aa1eb731f8182705555f89c9026d8c1ef230cbf8301dd' on '/var/lib/docker/devicemapper/mnt/f6fab3b798be3174f45aa1eb731f8182705555f89c9026d8c1ef230cbf8301dd': invalid argument 9c9026d8c1ef230cbf8301dd': invalid argument
    FATA[0034] Error pulling image (latest) from mysql, Error mounting '/dev/mapper/docker-202:1-1835239-f6fab3b798be3174f45aa1eb731f8182705555f89c9026d8c1ef230cbf8301dd' on '/var/lib/docker/devicemapper/mnt/f6fab3b798be3174f45aa1eb731f8182705555f89c9026d8c1ef230cbf8301dd': invalid argument
    ^C
    [ec2-user@ip-172-31-35-232 ~]$ docker ps -a
    CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
    [ec2-user@ip-172-31-35-232 ~]$ docker images
    REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
    <none> <none> f10807909bc5 5 weeks ago 85.1 MB
```

### PR DESCRIPTION
**Pull request by burke**
ping @LK4D4 because the removed `FIXME` line has your name on it :)
fixes #9718 
### Summary of problem

If two repositories sharing layers (e.g. a common baseimage) were pulled concurrently, it would predictably result in a corrupted layer on disk (at least on overlay; behaviour would probably vary by storage driver).
### Solution

By releasing the token back to the pool after extracting, we hold the mutex over the entire sensitive region. I also had to move a few output lines around to get matching output in the two cases.
### To reproduce

_(Note that the two images I pull share a baseimage (`ba5e0000`, which you'll see in the log outputs below). I used my own internal images because it was easy for me, but any comparable situation should trigger this also.)_

``` bash
#!/bin/bash
set -xeuo pipefail

sudo rm -rf docker-graph

(
  sudo ./docker-1.9.0-dev daemon \
    --graph="$(pwd)/docker-graph" \
    --host="unix://$(pwd)/docker.sock" \
    --pidfile="$(pwd)/docker.pid" \
    --storage-driver='overlay'
    #--debug \
) &
dockerpid=$!
trap "sudo kill ${dockerpid}" EXIT

sleep 3

pids=()
(
  env DOCKER_HOST="unix://$(pwd)/docker.sock" \
    ./docker-1.9.0-dev run registry.ash.shopify.io/argus-server:6d730e3fe6dff954f118ff92f22e55da41fb4414 > p1.txt 2>&1
) &
pids+=($!)

(
  env DOCKER_HOST="unix://$(pwd)/docker.sock" \
    ./docker-1.9.0-dev run registry.ash.shopify.io/kafkahttp:be0045a792a156d86dc2d6f8309bbfcd15abff54 > p2.txt 2>&1
) &
pids+=($!)

wait ${pids[*]} ${dockerpid}
```
##### Docker log

_(includes some logs I had inserted before this PR. `found` indicates whether there was already a broadcaster in the pool)_

```
INFO[0003] POST /v1.21/containers/create
INFO[0003] POST /v1.21/containers/create
ERRO[0003] Handler for POST /containers/create returned error: No such image: registry.ash.shopify.io/kafkahttp:be0045a792a156d86dc2d6f8309bbfcd15abff54
ERRO[0003] HTTP Error                                    err=No such image: registry.ash.shopify.io/kafkahttp:be0045a792a156d86dc2d6f8309bbfcd15abff54 statusCode=404
ERRO[0003] Handler for POST /containers/create returned error: No such image: registry.ash.shopify.io/argus-server:6d730e3fe6dff954f118ff92f22e55da41fb4414
ERRO[0003] HTTP Error                                    err=No such image: registry.ash.shopify.io/argus-server:6d730e3fe6dff954f118ff92f22e55da41fb4414 statusCode=404
INFO[0003] POST /v1.21/images/create?fromImage=registry.ash.shopify.io%2Fkafkahttp&tag=be0045a792a156d86dc2d6f8309bbfcd15abff54
INFO[0003] POST /v1.21/images/create?fromImage=registry.ash.shopify.io%2Fargus-server&tag=6d730e3fe6dff954f118ff92f22e55da41fb4414
WARN[0004] pull pool result                              found=false id=ba5e0000ba5c78297d0409cf1e53a3aed476d79ae3d7e267c64d67b0536b5d1c
WARN[0004] pull pool result                              found=false id=632342f6adc50af753bf8bae5d0086871a378047d65677a4546fddf303d58dd5
WARN[0004] pull pool result                              found=false id=b955e3d5afa7536b7d9e27d8d5aedb1fca7a2e2cfbb0f34fc57e19527cb9d785
WARN[0004] pull pool result                              found=false id=e73ef6501f7e51ed1d2294a235ca0138ef106c862c9264ba601981ee917bfb6c
WARN[0004] pull pool result                              found=true id=ba5e0000ba5c78297d0409cf1e53a3aed476d79ae3d7e267c64d67b0536b5d1c
WARN[0004] pull pool result                              found=false id=b9ab84e78d6bbdb77e8e3e1a818eb2589492baebd09bf113cd54c78e0e4283a1
WARN[0004] pull pool result                              found=false id=4f1b1a4d03b5d65312cc7028d7edaeffed7903e9d3cedc14147513a829c5fc39
WARN[0005] download function returned                    found=false id=b955e3d5afa7536b7d9e27d8d5aedb1fca7a2e2cfbb0f34fc57e19527cb9d785
WARN[0005] download function returned                    found=false id=e73ef6501f7e51ed1d2294a235ca0138ef106c862c9264ba601981ee917bfb6c
WARN[0006] download function returned                    found=false id=632342f6adc50af753bf8bae5d0086871a378047d65677a4546fddf303d58dd5
WARN[0006] download function returned                    found=false id=b9ab84e78d6bbdb77e8e3e1a818eb2589492baebd09bf113cd54c78e0e4283a1
WARN[0006] download function returned                    found=false id=4f1b1a4d03b5d65312cc7028d7edaeffed7903e9d3cedc14147513a829c5fc39
WARN[0009] download function returned                    found=false id=ba5e0000ba5c78297d0409cf1e53a3aed476d79ae3d7e267c64d67b0536b5d1c
WARN[0019] broadcaster wait completed                    found=true id=ba5e0000ba5c78297d0409cf1e53a3aed476d79ae3d7e267c64d67b0536b5d1c
WARN[0019] download function returned                    found=true id=ba5e0000ba5c78297d0409cf1e53a3aed476d79ae3d7e267c64d67b0536b5d1c
```
##### p1.txt

```
Unable to find image 'registry.ash.shopify.io/argus-server:6d730e3fe6dff954f118ff92f22e55da41fb4414' locally
6d730e3fe6dff954f118ff92f22e55da41fb4414: Pulling from argus-server
ba5e0000ba5c: Pulling fs layer
632342f6adc5: Pulling fs layer
b955e3d5afa7: Pulling fs layer
e73ef6501f7e: Pulling fs layer
b955e3d5afa7: Verifying Checksum
b955e3d5afa7: Download complete
e73ef6501f7e: Verifying Checksum
e73ef6501f7e: Download complete
632342f6adc5: Verifying Checksum
632342f6adc5: Download complete
ba5e0000ba5c: Verifying Checksum
ba5e0000ba5c: Download complete
ba5e0000ba5c: Pull complete
632342f6adc5: Pull complete
b955e3d5afa7: Pull complete
e73ef6501f7e: Pull complete
Digest: sha256:fa9955121c2f77bfe696e68815744e069ea09044aa0888b2361e7ccc4ee22c07
Status: Downloaded newer image for registry.ash.shopify.io/argus-server:6d730e3fe6dff954f118ff92f22e55da41fb4414
```
##### p2.txt

```
Unable to find image 'registry.ash.shopify.io/kafkahttp:be0045a792a156d86dc2d6f8309bbfcd15abff54' locally
be0045a792a156d86dc2d6f8309bbfcd15abff54: Pulling from kafkahttp
ba5e0000ba5c: Pulling fs layer
b9ab84e78d6b: Pulling fs layer
4f1b1a4d03b5: Pulling fs layer
b9ab84e78d6b: Verifying Checksum
b9ab84e78d6b: Download complete
4f1b1a4d03b5: Verifying Checksum
4f1b1a4d03b5: Download complete
ba5e0000ba5c: Verifying Checksum
ba5e0000ba5c: Download complete
ba5e0000ba5c: Pull complete
b9ab84e78d6b: Pull complete
4f1b1a4d03b5: Pull complete
Digest: sha256:3fdc81727964ab6729622fb66009f8c01b622ff090ef3457d8448b6f542c5da5
Status: Downloaded newer image for registry.ash.shopify.io/kafkahttp:be0045a792a156d86dc2d6f8309bbfcd15abff54
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
@burke looks like it has merge conflicts :'(

**Comment by burke** [comment]
Wow, does it ever. Fixing, thanks.

**Comment by burke** [comment]
Haha, I think this was already fixed for 1.9.0, I had just rebased my master branch against my fork to test, not upstream. Fail.

**Comment by thaJeztah** [comment]
Haha, that's one for the books :+1:

Thanks @burke

**Pull request closed without merging**
