### PR TITLE
Fixes #15349 too many apis

### LINKED ISSUE #15349: docs for API < 1.14 is broken
From https://docs.docker.com/reference/api/docker_remote_api/

https://docs.docker.com/reference/api/docker_remote_api_v1.15/
https://docs.docker.com/reference/api/docker_remote_api_v1.14/

are working, but

https://docs.docker.com/reference/api/docker_remote_api_v1.13/
https://docs.docker.com/reference/api/docker_remote_api_v1.12/
....

doesn't (404)

### PR DESCRIPTION
**Pull request by moxiegirl**
Fixes #15349 too many apis

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @docker/docs-owners

**Comment by thaJeztah** [comment]
I'm good with removing the links, but unsure if we should remove the deprecation messages. The deprecation announcements are useful for users that need to migrate to a newer API.

/cc @duglin for thoughts as well

**Comment by thaJeztah** [comment]
(on a side note: is there a way for me to get added to the docker/docs-owners group, because I don't get notified for those pings :smile:)

**Comment by duglin** [comment]
Not sure we have to keep really old deprecation messages.  Having them in the release in which we deprecated them, and then a "they're gone" note in the release in which they were removed is probably sufficient.

**Comment by moxiegirl** [comment]
I agree with @duglin .  author LGTM

**Comment by moxiegirl** [comment]
@thaJeztah for the merge

**Comment by thaJeztah** [comment]
LGTM, thanks both!

**Comment by thaJeztah** [comment]
ping @calavera for cherry pick

**Comment by calavera** [comment]
cherry picked into #15091

**Pull request merged**
