### PR TITLE
Fix duplicate display of dangling images

### PR DESCRIPTION
**Pull request by ncdc**
Signed-off-by: Andy Goldstein agoldste@redhat.com

### CODE REVIEW

**Comment by ncdc** [comment]
@stevvooe @dmcgowan @jlhawn @vbatts PTAL

Dangling images have both `RepoTags` `<none>:<none>` and `RepoDigests` `<none>@<none>` set. The CLI loops through both arrays and displays whatever entries exist. As such, a dangling image is listed twice. This should fix that issue, and simplify the way we print the output.

**Comment by vbatts** [comment]
i will take a look.

@jfrazelle this shouldprobably be on the 1.6 milestone tag too.

**Comment by ncdc** [comment]
Writing a test case for this now...

**Comment by ncdc** [comment]
Test added :smile:

**Comment by ncdc** [comment]
Hmm, not sure what's happening to the daemon in Linux. I'm seeing the same issue locally as well:

```
[PASSED]: run - disable networking with -n=false
time="2015-03-18T15:02:43Z" level=fatal msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?" 

time="2015-03-18T15:02:43Z" level=fatal msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?" 

--- FAIL: TestRunLinksContainerWithContainerName (0.14s)
```

**Comment by ncdc** [comment]
Yay, happy Jenkins!

**Comment by LK4D4** [comment]
@ncdc Omg, you know how to do dangling image. We have worst test ever about `-f` where it created by some undetermined magic.

**Comment by ncdc** [comment]
@LK4D4 does this make you happy? :smiley:

**Comment by LK4D4** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by jlhawn** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jlhawn** [comment]
It's nice that this was all done on the client side only :+1: 

@ncdc 
> Dangling images have both `RepoTags` `<none>:<none>` and `RepoDigests` `<none>@<none>` set.

It would be nice if the daemon just did not include a `RepoTags` or `RepoDigests` entry in this case then the client would know to just display one line with `<none>`s in this case ... something to think about for a later time.

**Comment by ncdc** [comment]
I had considered that and I do think it'd be nicer to do it that way, but
in the interest of time I went with this approach.

**Pull request merged**
