### PR TITLE
Change the btrfs_noversion check to be automatic

### PR DESCRIPTION
**Pull request by tianon**
cc @vbatts :heart:

### CODE REVIEW

**Comment by tianon** [comment]
I tested this on Debian Wheezy and Ubuntu Trusty/14.04. :+1:

(I also tested Ubuntu Precise/12.04, and determined that apparently, [version `0.19+20100601-3ubuntu3` of `btrfs-tools`](http://packages.ubuntu.com/precise/btrfs-tools) is not greater than 3.8, and is missing basic things like `btrfs/ioctl.h`, so we just can't even go there.)

**Comment by tianon** [comment]
Excellent, this totally worked on Windows, too (as in, didn't cause trouble and blow up).

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
