### PR TITLE
[19.03 backport][Carry 39595] Tailor CI for ARM, skip legacy integration test

### PR DESCRIPTION
**Pull request by thaJeztah**
moved from https://github.com/docker/engine/pull/413

backport of https://github.com/moby/moby/pull/39678

carry of https://github.com/moby/moby/pull/39595 Tailor CI for ARM, skip legacy integration test
closes https://github.com/moby/moby/pull/39595 Tailor CI for ARM, skip legacy integration test
fixes https://github.com/moby/moby/issues/39479 Jenkins CI for arm64

**- What I did**
This PR is trying to make a minimal test set (without legacy integration test cases) for ARM. 
Introduce a new environment variable SKIP_LEGACY_INTEGRATION_TEST to control whether legacy integration test cases are ignored or not. 

**- How I did it**

- Introduce a new environment variable SKIP_LEGACY_INTEGRATION_TEST, default value is "no". 
- If it's set to "yes" or anything rather than "no", legacy integration suites will be skipped.
- In arm CI, SKIP_LEGACY_INTEGRATION_TEST is set to "yes".
- CI for other architecture's are not impacted.

**- How to verify it**
Run "make test-integration" on an ARM machine.

**- Description for the changelog**

See the discussion in issue: https://github.com/moby/moby/issues/39479
Backgroud: CI on arm (32 and 64 bit) architecture took too long time to finish. So the CI for it was stopped. Now I am trying to bring it back, and try to set a minimal set in it to save time.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by tianon — APPROVED** [review]
LGTM

**Comment by tiborvass** [comment]
@thaJeztah can you rerun CI?

**Comment by thaJeztah** [comment]
Rebased

**Review by tiborvass — DISMISSED** [review]

**Comment by tiborvass** [comment]
`[2020-04-30T15:45:16.610Z]     config_test.go:319: assertion failed: string "overlay on / type overlay (rw,relatime,lowerdir=/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/db7e8a20d6864/root/overlay2/l/YJ4JXJSOUVQ6V32HXVLRANII3H:/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/db7e8a20d6864/root/overlay2/l/EM4EVRUFJALYIUXZAEP7LPUDNT,upperdir=/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/db7e8a20d6864/root/overlay2/bbb92f11f3aa67f54819dc742b0e0ba76b5c63bf613a3e2e95b823519ecbc392/diff,workdir=/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/db7e8a20d6864/root/overlay2/bbb92f11f3aa67f54819dc742b0e0ba76b5c63bf613a3e2e95b823519ecbc392/work)\nproc on /proc type proc (rw,nosuid,nodev,noexec,relatime)\ntmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)\ndevpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)\nsysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)\ntmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)\ncgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)\ncgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)\ncgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)\ncgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)\ncgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)\ncgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)\ncgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)\ncgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)\ncgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)\ncgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)\ncgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)\ncgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)\nmqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)\nshm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)\noverlay on /sbin/docker-init type overlay (ro,relatime,lowerdir=/var/lib/docker/overlay2/l/SFYD5AGBUSRIFMXXUE2465YBQL:/var/lib/docker/overlay2/l/K5AESDTA5MH6V35Q7VMADNWYWB:/var/lib/docker/overlay2/l/EJF3ITLSNYFWGKMUR225WBISXW:/var/lib/docker/overlay2/l/GL3IJG45XDMMNODSSO2MZNWDN4:/var/lib/docker/overlay2/l/455Y6SCU3E62AT2NMZ7YCPNPJF:/var/lib/docker/overlay2/l/PXNT2RTRQWDFNYA2AAQDXLD5A5:/var/lib/docker/overlay2/l/T4TLRYH54WOKKXYNPQMZPSZE65:/var/lib/docker/overlay2/l/ZOC6DW7XFM7JWZN6J2BRAB5DMF:/var/lib/docker/overlay2/l/5IWCWFEAVNRHHC37RLUQ22RIHQ:/var/lib/docker/overlay2/l/V6M2RHSZU655AB3GN4WZB37NNC:/var/lib/docker/overlay2/l/ZDHGLPPHHIBHOZ2LNUPP6GFKHD:/var/lib/docker/overlay2/l/UPQPDP4MVUOFGXZSUOXTSI6G67:/var/lib/docker/overlay2/l/JWTZ4TKXXJV5JIPWSEWP5IQL6B:/var/lib/docker/overlay2/l/DS2RA26VERZ3VVDS3NG6F7UKNM:/var/lib/docker/overlay2/l/I2REXWZM3FS5XNZ5ULUZCLG3OZ:/var/lib/docker/overlay2/l/DZUYZZUGZKVYN4N2OPL3EGCMOX:/var/lib/docker/overlay2/l/OZGSNNOFIHKBH26DLVNEPTKE4C:/var/lib/docker/overlay2/l/IY3LL7G)\n" does not contain "tmpfs on /templated_config-TestTemplatedConfig type tmpfs"`

**Comment by thaJeztah** [comment]
That failure looks the same as the one we were having on the original PR; https://github.com/moby/moby/pull/39678#issuecomment-522538670. That disappeared after a rebase (might be fixed on master but don't know _what_ fixed it)

**Comment by thaJeztah** [comment]
I'm closing this PR, as 19.03 has not been maintained for 2 Years, and there are no plans for more 19.03.x patch releases.

**Pull request closed without merging**
