### PR TITLE
fix #23017, add zsh completion for dockerd

### LINKED ISSUE #23017: Missing command completion of `dockerd`
Currently we have split docker binary to `dockerd` and `docker`, the command completion of `dockerd` is missing for now.

ping @albers  @sdurrheimer

### PR DESCRIPTION
**Pull request by leonhartX**
Just call all `docker daemon` completion when the command is `dockerd`. 

Signed-off-by: Ke Xu leonhartx.k@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @sdurrheimer PTAL

**Comment by vincentbernat** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
