### PR TITLE
Update runc to 0351df1c5a66838d0c392b4ac4cf9450de844e2d

### PR DESCRIPTION
**Pull request by yongtang**
This fix updates runc to f1e19e9744545dabaf8227942fcc478f90d2cc3e

With this fix the warnings generated by netgo and dlopen by go 1.9 are addressed.

See
- https://github.com/opencontainers/runc/pull/1577
- https://github.com/opencontainers/runc/pull/1579

This fix is part of the efforts for go 1.9: https://github.com/moby/moby/pull/33892

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Full diff is https://github.com/opencontainers/runc/compare/1c81e2a794c6e26a4c650142ae8893c47f619764...f1e19e9744545dabaf8227942fcc478f90d2cc3e

**Comment by thaJeztah** [comment]
Hm, looks like there's an issue with newlines (again?) in this RunC update;

```
23:47:15 ----------------------------------------------------------------------
23:47:15 FAIL: docker_cli_service_logs_test.go:255: DockerSwarmSuite.TestServiceLogsTTY
23:47:15 
23:47:15 [d424a66579867] waiting for daemon to start
23:47:15 [d424a66579867] daemon started
23:47:15 
23:47:15 docker_cli_service_logs_test.go:290:
23:47:15     // for some reason there is carriage return in the output. i think this is
23:47:15     // just expected.
23:47:15     result.Assert(c, icmd.Expected{Out: "out\r\nerr\r\n"})
23:47:15 /go/src/github.com/docker/docker/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go:61:
23:47:15     t.Fatalf("at %s:%d - %s\n", filepath.Base(file), line, err.Error())
23:47:15 ... Error: at docker_cli_service_logs_test.go:290 - 
23:47:15 Command:  /usr/local/bin/docker --host unix:///tmp/docker-integration/d424a66579867.sock service logs --raw TestServiceLogsTTY
23:47:15 ExitCode: 0
23:47:15 Error:    <nil>
23:47:15 Stdout:   out
23:47:15 err
23:47:15 
23:47:15 Stderr:   
23:47:15 
23:47:15 Failures:
23:47:15 Expected stdout to contain "out\r\nerr\r\n"
```


ping @dqminh could this be related to https://github.com/opencontainers/runc/commit/6cfb498d2ce9704e6b9ff86db383ba6466e70ff7 and https://github.com/opencontainers/runc/commit/1439022b60a0919f08a4fa53009c9e9107b5d282 ?

**Comment by AkihiroSuda** [comment]
ping @dqminh

**Comment by thaJeztah** [comment]
ping @mlaventure @crosbymichael

**Comment by mlaventure** [comment]
The TTY failure should get fixed once https://github.com/opencontainers/runc/pull/1600 is merged and this PR updated.

**Comment by thaJeztah** [comment]
ping @yongtang https://github.com/opencontainers/runc/pull/1600 was merged 👍

**Comment by yongtang** [comment]
Thanks @thaJeztah The PR was updated with the merged runc changes a couple of hours ago.

Now all Jenkins build expect `powerpc` passes. The `powerpc` failure seems to be unrelated:
https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/6138/console

Let me retry the powerpc build.

**Comment by thaJeztah** [comment]
oh, dang missed that! sorry for the noise 👍

**Comment by yongtang** [comment]
All tests passed. Please take a look.

**Review by vdemeester — APPROVED** [review]
LGTM 🐮
/cc @mlaventure

**Review by mlaventure — APPROVED** [review]
LGTM

**Pull request merged**
