### PR TITLE
Capitalized Docker and Swarm for consistency in new CLI commands

### PR DESCRIPTION
**Pull request by tiffanyfay**
Mandatory cute animal as per contributing instructions.

cute-turtle

### CODE REVIEW

**Comment by icecrime** [comment]
Ha thanks! :+1: Ping @dnephin.

**Comment by thaJeztah** [comment]
hm some weird failures, also this on win2lin;

```
07:42:20 # github.com/docker/swarmkit/identity
07:42:20 vendor\src\github.com\docker\swarmkit\identity\randomid.go:54: nn.Text undefined (type big.Int has no field or method Text)
```

**Comment by dnephin** [comment]
LGTM, Thanks!

**Comment by icecrime** [comment]
@thaJeztah I believe win2lin needs to be updated to Go 1.6.x. Is that something we can do? (cc @jhowardmsft)

**Comment by tiffanyfj** [comment]
@thaJeztah  I would be impressed if my changes broke win2lin (or anything really) :P.

**Comment by justincormack** [comment]
Oh its very picky....

**Comment by jhowardmsft** [comment]
It does need upgrading, but that's not the cause here.

```
11:05:05 # github.com/docker/swarmkit/identity
11:05:05 vendor\src\github.com\docker\swarmkit\identity\randomid.go:54: nn.Text undefined (type big.Int has no field or method Text)
11:06:31 + ec=1
11:06:31 + set +x
11:06:31 ERROR: Build of binary on Windows failed
```

**Comment by thaJeztah** [comment]
@tiffanyfj yes, it would surprise me as well :smile:

**Comment by tiffanyfj** [comment]
@jhowardmsft It actually is because of the Go version. `Text` was added in go1.6 and this is running go1.5.3.
https://github.com/golang/go/commit/8d701f092d5dba49a79fada561e90cfdb84f2bd1

**Comment by jhowardmsft** [comment]
Ah, I see. I really stacked with things right now. It might have to be a weekend job to get them upgraded.

**Comment by thaJeztah** [comment]
Oh sorry, needs a rebase now :cry:

**Comment by tiffanyfj** [comment]
@thaJeztah: Rebased

**Comment by thaJeztah** [comment]
I think win2lin was updated, so restarting again. Fingers crossed :metal:

**Comment by justincormack** [comment]
It needs rebasing again... but swarm has been merged so you want to PR against master now...

**Comment by thaJeztah** [comment]
ouch, yes. Sorry @tiffanyfj, I think I should close this, because you can't change a PR to be against a different branch once opened :cry:

**Comment by tiffanyfj** [comment]
No worries. I'll make one against master after I check that it still applies. Thanks.

**Pull request closed without merging**
