### PR TITLE
Fix #11589 by adding README and comments to exported functions

### LINKED ISSUE #11589: pkg/networkfs/resolvconf - Document exported functions and types
**Problem**
 
pkg/networkfs/resolvconf - Document exported functions and types
 
**Solution**
 
The `pkg/networkfs/resolvconf` package is used for `/etc/resolv.conf` file manipulation in Docker networking code. It is meant to be reused by other applications, however it lacks documentation.
 
Add a README.md to the package, and code comments to the package's exported symbols.

### PR DESCRIPTION
**Pull request by arthurbarr**
Fixes #11589

### CODE REVIEW

**Comment by LK4D4** [comment]
@arthurbarr Also, can you duplicate `README.md` contents in `resolv.conf` top in form of `Package resolvconf ....`
See http://blog.golang.org/godoc-documenting-go-code
Also I wanna ask you to change other comments in that file to fit conventions listed in link above.

**Comment by LK4D4** [comment]
And seems like file is not properly formatted with `gofmt`.

**Comment by crosbymichael** [comment]
LGTM

@arthurbarr thanks!

**Comment by tiborvass** [comment]
@arthurbarr apologies, would you mind rebasing it?

**Comment by arthurbarr** [comment]
Re-based on master.  I'm not sure why the Windows build is now failing though - any pointers would be much appreciated!

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
