### PR TITLE
Add missing subcommand in set-up-prereqs doc.

### PR DESCRIPTION
**Pull request by mizzy**
Hi

I've found that `commit` subcommand is missing in `9. Sign and commit your change.` section of set-up-prereqs doc.

Please check it.

### CODE REVIEW

**Comment by RickWieman** [comment]
LGTM (not a maintainer)

**Comment by duglin** [comment]
LGTM
/cc @moxiegirl @SvenDowideit

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
@mizzy Thank you for the great catch! I have to make your fix on another branch as we pushed a revised structure to the contributor's guide last night.  I'm going to close this.  I'll add a comment after your change is live so you can see it.

**Pull request closed without merging**
