### PR TITLE
daemon: isolate windows only graphdriver logic

### PR DESCRIPTION
**Pull request by vbatts**
Tidying up the presence of interfaces for all platforms.

ping @swernli @dmcgowan

### CODE REVIEW

**Comment by swernli** [comment]
Minor nitpick, but is the "_windows" really necessary in "imagerestorer_windows.go" since it's already in daemon/graphdriver/windows?

@stevvooe Stephen, I remember you mentioned a preference for not having too many methods whose implementation is split between Windows and unix (since it requires looking into two files to figure out what's going on).  Does this split seem fine to you?

**Comment by vbatts** [comment]
@swernli I figured to be safe, because there is nothing _technically_ stopping a linux implementation from important from the `github.com/docker/docker/daemon/graphdriver/windows` package, but the `_windows` is a build tag gated option.

**Comment by swernli** [comment]
Sounds reasonable.  LGTM assuming the Jenkins tests pass.

**Comment by dmcgowan** [comment]
Thanks Vincent! You know how to preserve my sanity :heart_eyes_cat:

Looks like some fixup is still needed to get ci passing
```
daemon/graphdriver/windows/windows.go:406: undefined: graphdriver.Tagger
daemon/graphdriver/windows/windows.go:406: undefined: graphdriver.Recorder
```

**Comment by vbatts** [comment]
rebased

**Comment by stevvooe** [comment]
Seems odd to replace file-based feature detection with runtime feature detection. Do we never see ourselves having custom images on non-windows platforms? My original fear with adding this was that we would have a custom image feature that only works on windows. This patch seems to support that story, rather than leaving in the stubs to add cross-platform support.

This is beneficial in that we don't pay the runtime cost for detection.

**Comment by vbatts** [comment]
@stevvooe while I see that, of the history of graphdrivers, they all have been linux-vfs-ish. 
This is isolating the windows only logic. There is not a cross-platform benefit of the stubs that do not make sense anywhere but windows. :-\

**Comment by dmcgowan** [comment]
@stevvooe what probably does not show up clearly in the diff on github is that previously this was exposing interfaces in the `graphdriver` package that were dependent on the `image` package. If Windows needs to do that it should not be done by adding to the exposed interface of a package such as `graphdriver`, which was the original motivation for this change.

**Comment by stevvooe** [comment]
@vbatts @dmcgowan You're both missing future possibilities for short term cleanup. This interface can provide the ability for any os to load custom images at startup. The functionality is not limited to windows. Might as well remove the interfaces all together with that logic.

If we don't see other operating systems supporting this, I don't see why we should support it with windows.

**Comment by dmcgowan** [comment]
Not missing anything. I don't disagree with the functionality only the code organization. The `graphdriver` exposes an interface for managing copy-on-write filesystem layers, not Docker image layers. Since this functionality is higher level than this, it really belongs in the next layer up the interface stack. Problem is the next layer up does not currently exist, causing the daemon and graph packages to directly use this interface to manage image and container layers. In 1.10 we are refactoring the use of graphdrivers to add these missing higher level interfaces. Once these interfaces exist, that is where custom image logic should be implemented. We had this in mind, specifically the window's use case when designing the new interface and believe it will provide a much better code base for all the "future possibilities". This specific cleanup undoes changes to the `graphdriver` interface which should not have been allowed in the first place. This should be made more clear by moving this package to either its own repository or renamed to express its scope (Josh started this work but it was never merged back).

**Comment by thaJeztah** [comment]
ping @dmcgowan @stevvooe what's the status here?

Does this conflict with @tonistiigi's refactoring in https://github.com/docker/docker/pull/17924?

**Comment by dmcgowan** [comment]
Changes made in #17924 supersede this change and accomplish the same goal.

**Pull request closed without merging**
