### PR TITLE
Support TLS remote test daemon

### PR DESCRIPTION
**Pull request by tiborvass**
This will allow us to have a windows-to-linux CI, where the linux host
can be anywhere, connecting with TLS.

Signed-off-by: Tibor Vass tibor@docker.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by jhowardmsft** [comment]
LGTM, but also needs a tweak to add TLS to the tear-down script (postbuild.sh in the sources) to avoid this in the output, and to ensure the CI remains reliable.

```
09:11:28 INFO: Deleting pre-existing containers and images...
09:11:50 An error occurred trying to connect: Get https://159.203.124.44:2376/v1.22/containers/json?all=1: dial tcp 159.203.124.44:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by jhowardmsft** [comment]
@tiborvass Oh BTW, it also needs the same scripts updates in `Docker Master (Windows)` in Jenkins: https://jenkins.dockerproject.org/job/Docker%20Master%20(windows)/configure

**Comment by tiborvass** [comment]
@jhowardmsft yes, thanks will fix that, but want to have a first run :)

**Comment by jhowardmsft** [comment]
Very cool with the hybrid mode. LGTM.

**Comment by tiborvass** [comment]
Ping @tianon

**Comment by tianon** [comment]
Seems reasonable :+1:

(`hack/` change LGTM)

**Comment by thaJeztah** [comment]
\o/ thanks @tiborvass nice work!

**Pull request merged**
