### PR TITLE
Bump 1.8.1

### PR DESCRIPTION
**Pull request by icecrime**
Emergency release to address #15536.

### CODE REVIEW

**Comment by amylindburg** [comment]
@tianon @jeffdm head's up that we will need a 1.8.1 b2d.iso and 1.8.1 Toolbox.

**Comment by dmp42** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
