### PR TITLE
gitignore: add *.rej

### PR DESCRIPTION
**Pull request by chenhanxiao**
Ignore noise from unsuccessful patch operation.

Signed-off-by: Chen Hanxiao chenhanxiao@cn.fujitsu.com

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
LGTM

**Comment by runcom** [comment]
I think this shouldn't go in gitignore, why not patch file then for example? rej file could even be fixed and applied exactly like patch files. Also I don't feel OK in adding things to gitignore just because I'm lazy deleting them (may not be this case eh), rm *.rej should suffice like you would eventually do with patch files

**Comment by chenhanxiao** [comment]
@runcom 
Yes, since we've added *.orig, we'd better go with it.
Also, this will reduce noise from `git status`.

**Comment by runcom** [comment]
Alright, many projects include both so I think we can go with this as well

**Comment by runcom** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
