### PR TITLE
report error when ShmSize is 0

### PR DESCRIPTION
**Pull request by allencloud**
1.report err when --shm-size=0
2.add unit test for 0

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think it was like this originally; https://github.com/docker/docker/pull/16168, but changed in https://github.com/docker/docker/commit/5190794f1d85d5406611eb69c270df62ac1cdc7f, which no longer used a pointer for this value. See the discussion here; https://github.com/docker/docker/pull/18977#discussion_r48884767

I wonder if there's a reasonable minimum for shm; is `shm=0` valid on Linux? Or should we have a minimum, like https://github.com/docker/docker/blob/eed9c930b85ac1489129e4e36e0945bb3ee6954f/daemon/daemon_unix.go#L360-L362 

ping @anusha-ragunathan any ideas?

**Comment by anusha-ragunathan** [comment]
@thaJeztah : shmsize is the /dev/shm mount size. The actual value to the mount syscall cannot be 0. However, if someone sets it to 0, instead of erroring out, we set it to be the default value (65K) and proceed. IMO, there's no need to report an error on 0. Existing behaviour is fine.

**Comment by thaJeztah** [comment]
@anusha-ragunathan is "1" a valid size? (wondering if we need a minimum amount)

**Comment by anusha-ragunathan** [comment]
1 is valid, but it gets converted to a 4k. 

Essentially, 4k is the minimum and 65536k is the default

**Comment by thaJeztah** [comment]
I think we can close this, given the discussion above

Thanks @allencloud !!

**Pull request closed without merging**
