### PR TITLE
Move listeners and port allocation outside the server. 

### PR DESCRIPTION
**Pull request by calavera**
The daemon will fail to start if the port is in use. We don't need to allocate the port twice.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by icecrime** [comment]
The goal of this code was _not_ to prevent the daemon to start, but to prevent the automatic port allocation to attribute the daemon's listening port to a container.

**Comment by icecrime** [comment]
That's to say that I'm -1 for this PR, and it's absolutely unrelated to the fact that adding this code was among my first patches to Docker (:crying_cat_face:).

**Comment by calavera** [comment]
@icecrime I took the listener and port allocation outside the server, let me know what you think.

**Comment by icecrime** [comment]
LGTM :+1:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
