### PR TITLE
Add Daniel Lewin to names collection

### PR DESCRIPTION
**Pull request by valgaze**
Add Daniel Lewin to names collection (https://en.wikipedia.org/wiki/Daniel_Lewin)

**\- A picture of a cute animal (not mandatory but encouraged)**
doodle

Signed-off-by: Victor Algaze valgaze@gmail.com

### CODE REVIEW

**Comment by coolljt0725** [comment]
LGTM

**Comment by justincormack** [comment]
It has been normal practise to add a man and a woman at the same time.

**Comment by valgaze** [comment]
@justincormack Didn't catch that tradition-- I'll push up a change with Joan Clarke

**Comment by justincormack** [comment]
@valgaze excellent choice.

LGTM

**Comment by justincormack** [comment]
Known issue with experimental, unrelated.

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
