### PR TITLE
Move portmapper initialization to var block

### PR DESCRIPTION
**Pull request by LK4D4**
Race between InitDriver and RequestPort could lead to panic.

Signed-off-by: Alexander Morozov lk4d4@docker.com

### CODE REVIEW

**Comment by erikh** [comment]
LGTM

**Comment by crosbymichael** [comment]
We will have to do this lazily ;)  my bad

**Comment by LK4D4** [comment]
I'll fix it here

**Comment by LK4D4** [comment]
@crosbymichael PTAL

**Comment by jfrazelle** [comment]
ooo sync.Once fancy!

**Comment by jfrazelle** [comment]
anyway to reproduce the panic with integration-cli test

**Comment by LK4D4** [comment]
@jfrazelle Yup, like 50/50 chance :)

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
no worries then :)

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
