### PR TITLE
Update to Joyent Install Doc

### PR DESCRIPTION
**Pull request by FindyDeLo**
Link images from Joyent.com docs

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I'd feel more comfortable if images used on our docs were in a github repo we had access to - but I'll leave that up to others.

LGTM - @docker/docs-owners

**Comment by delojoyent** [comment]
signed and repushed

**Comment by fredlf** [comment]
Please remove the exclamation points, they are not appropriate for technical documentation. 
I agree with Sven, linking to remote images is not really a good practice for a number of reasons. Can you please just add the files? Thanks. Much appreciated.

**Comment by icecrime** [comment]
Aren't the exclamation points just markdown for images?

@delojoyent Can you please add the image files to the repo instead of linking externally? If not, we'll have to carry the PR (ping @moxiegirl), thanks!

**Comment by fredlf** [comment]
@icecrime Oh, you're right. I'm an idiot. Ignore me!

**Comment by moxiegirl** [comment]
Created an issue for the carry: https://github.com/docker/docker/issues/12062

**Pull request closed without merging**
