### PR TITLE
Fix docker ps output : NAMES -> NAME

### PR DESCRIPTION
**Pull request by ankushagarwal**
Containers can only have a unique name

### CODE REVIEW

**Comment by LK4D4** [comment]
There will be names with --no-trunc :)

**Comment by ankushagarwal** [comment]
I am sorry, but I am not sure if I understand the relation to the no-trunc option

**Comment by phemmer** [comment]
@ankushagarwal see [line 132](https://github.com/docker/docker/pull/14128/files#diff-5b52b6cb87954b934a978ad11c746872R132). `names` is a slice, that can contain multiple values [if `--no-trunc` is passed](https://github.com/docker/docker/pull/14128/files#diff-5b52b6cb87954b934a978ad11c746872R137)

**Comment by ankushagarwal** [comment]
I see. I'm still confused. The `daemon/container.go` (https://github.com/docker/docker/blob/master/daemon/container.go#L70) struct allows a single name, while the api/types/types.go allows multiple container names (https://github.com/docker/docker/blob/master/api/types/types.go#L111). Is there a way to give multiple names to containers?

**Comment by calavera** [comment]
I'm very confused with this too. I've never seen a container with two names, and it looks like `/` is a forbidden character in the name:

```
Invalid container name (name1/name2), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

/cc @LK4D4

**Comment by crosbymichael** [comment]
LGTM

It's good that people don't know that containers can have multiple names.  It was basically not used at all.

**Comment by tianon** [comment]
For those still confused, containers get a new name for each container
they're linked to (/my-app/db, for example).

**Comment by jgangemi** [comment]
could an update also be made to the remote api docs that explains this why/how containers can have multiple names?

**Comment by thaJeztah** [comment]
@ankushagarwal can you check the documentation? There should be examples showing the output of `docker ps` that need to be modified because of this.

@jgangemi could you open a separate issue (or, even better, a pull-request) for that?

**Comment by ankushagarwal** [comment]
@thaJeztah : Updated the docs.

**Comment by thaJeztah** [comment]
@ankushagarwal thx!

@LK4D4 @tianon any objections to this change, or LGTY?

**Comment by duglin** [comment]
my would we do this? See this output:
```
$ docker ps --no-trunc
CONTAINER ID                                                       IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
9bbd5c05cc2d751630f2c7ff44fe4bee39fa4ef6249e45751e45a0fb65ae2744   ubuntu              "sleep 6000"        14 minutes ago      Up 14 minutes                           test4                                   
4c9344641a8c2528f41aca168bc97a751416bda4730349f1c955f5c2078e6c4d   ubuntu              "sleep 6000"        15 minutes ago      Up 15 minutes                           fervent_torvalds                        
d3b32d69d447c361705716bd31f6d74d577ba484b6b27710e9346f2a6a0357b1   ubuntu              "sleep 6000"        15 minutes ago      Up 15 minutes                           fervent_torvalds/test,test,test4/test 
```

I think we should close this since you can have multiple names for containers - as @tianon said, link 'em and you get multiple names.

**Comment by duglin** [comment]
Although, I guess we could make it "NAME" when "--no-trunc" is not used but that's kind of a lot of work with minimal benefit.

**Comment by ankushagarwal** [comment]
@duglin makes sense. Closing this.

**Pull request closed without merging**
