### PR TITLE
a few cherry-picks

### PR DESCRIPTION
**Pull request by vieux**
return an empty stats if the container is restarting #28026
re-vendor syslog log driver #28670
api/server/httputils: ensure consistent status code #28530
run dnf upgrade before installing in fedora #29115 
hack/make.sh: fix BUILDTIME #29082

### CODE REVIEW

**Comment by vieux** [comment]
ping @vdemeester @tonistiigi

**Comment by vieux** [comment]
ping @cpuguy83

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Pull request merged**
