### PR TITLE
Create `builder/dockerignore` and `pkg/gitutils` to clean up `utils`

### PR DESCRIPTION
**Pull request by tiborvass**
As part of making `builder/*` more independent, this PR removes the dependency on `utils`.

Ping @calavera @duglin @vdemeester  @anusha-ragunathan

### CODE REVIEW

**Comment by estesp** [comment]
The tests need moved from `utils/` to the proper new package location:
```
# github.com/docker/docker/utils
utils/utils_test.go:36: undefined: ReadDockerIgnore
utils/utils_test.go:56: undefined: ReadDockerIgnore
```

**Comment by tiborvass** [comment]
Thanks @estesp

**Comment by vdemeester** [comment]
LGTM 🐹 :heart_eyes_cat:

**Comment by cpuguy83** [comment]
LGTM

**Comment by tiborvass** [comment]
seems stuck at events :( :(

**Comment by estesp** [comment]
@tiborvass yes, we can restart just janky.. I noted on IRC that the positive OOM test seems to be hanging more lately on CI :(

**Pull request merged**
