### PR TITLE
Add new --block-registry parameter to the daemon

### PR DESCRIPTION
**Pull request by pdevine**
The change allows specific registries to be blocked on the CLI so that
people do not accidentally push or pull images from that registry.

ping @stevvooe and @tiborvass

### CODE REVIEW

**Comment by thaJeztah** [comment]
For reference; this looks similar to an earlier PR; https://github.com/docker/docker/pull/10411 (and linked PRs from that)?

**Comment by cpuguy83** [comment]
While a blacklist can be useful, I would like to see a whitelist functionality as well.

**Comment by pdevine** [comment]
@cpuguy83 I'll add it. I just wanted to get something out for review to make sure I was headed in the right direction and on the off chance that someone wanted to get this in to 1.7.

**Comment by cpuguy83** [comment]
@pdevine Is there some reason you have the libnetwork commit there?

**Comment by thaJeztah** [comment]
I'm really interested in getting an opinion from the distribution team, given that the previous attempt at creating this (https://github.com/docker/docker/pull/10411) was closed because it hadn't been approved/discussed with that team first (https://github.com/docker/docker/pull/10411#issuecomment-85740698).

I just want to prevent wasting time if this gets rejected for possibly the same reasons.

IIUC correctly, the other proposal uses `--add-registry` for whitelisting and, according to https://github.com/docker/docker/pull/10411#issuecomment-86141834, RedHat currently distributes Docker with those patches (which, basically, isn't our concern, but worth taken into account)

For those reasons;

ping @stevvooe @dmcgowan @dmp42

**Comment by dmcgowan** [comment]
I remain -1 on adding this flag. Such configuration for managing allowed/disallowed registries should work more like the git remote command. There is on going work for this functionality in the distribution repo (see https://github.com/docker/distribution/pull/344). These category of flags will just complicate integration later on or require quickly deprecating them.

**Comment by stevvooe** [comment]
:-1: 

The ability to block a registry is going to be a part of the namespace proposal (docker/distribution#303).

**Comment by cpuguy83** [comment]
Ok, but what's the proposal as it relates to docker?

**Comment by dmcgowan** [comment]
@cpuguy83 the docker daemon should defer to the distribution packages for registry related communication, including the namespace package for turning an image name into a list of locations to get content for that name.

**Comment by cpuguy83** [comment]
@dmcgowan A UI is still needed for this. So ultimately you are just opposed to have the actual filtering logic implemented in Docker at all. Is that accurate?

**Comment by pdevine** [comment]
@cpuguy83 I think the other commit got pulled in by github thanks to my clock being screwed up when I rebased to fix a unit test.  I'll sort that out if we end up wanting to commit.

**Comment by icecrime** [comment]
We have two -1 from distribution maintainers: that would qualify for me to close. What do you think @pdevine?

**Pull request closed without merging**
