### PR TITLE
Fix cancelling builder on chunked requests

### LINKED ISSUE #32417: Build keeps running after an api connection have been closed
**Description**

When using the api endpoint /build. By the documentation, when the connection is disconnected from any reason the build should stop. But when sending chunked data with addition to header `Expect: 100-continue` the docker daemon would not stop the build.

**Steps to reproduce the issue:**
1. create a Dockerfile with infinite loop:
```
FROM alpine
RUN while true; do sleep 5; done
```
2. archive the Dockerfile into a tar file
```
tar -cvf context.tar Dockerfile
```
3. run build image api with headers `Transfer-Encoding:chunked` and `Expect: 100-continue`:
```
curl --unix-socket /var/run/docker.sock http:/build --data-binary @./context.tar -H "Transfer-Encoding:chunked"
# Expect: 100-continue is added automatically by curl 
```
4. use `SIGINT`/`CTRL-C` to exit curl
5. run `docker ps` to see live containers

**Describe the results you received:**
There is a docker container still running from the build with the command of the infinite loop.

**Describe the results you expected:**
That there won't be any container left from the building process.

**Additional information you deem important (e.g. issue happens only occasionally):**
Since I'm using `docker-machine` my curl command used tls parameter and not unit-socket:
```
curl --cacert /path/to/ca.pem \
         --cert /path/to/cert.pem \
         --key /path/to/key.pem \
         https://docker-machine:2376/build ...
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: ##
 Running: ##
 Paused: ##
 Stopped: ##
Images: ##
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: ##
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.52-boot2docker
Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: codefresh
ID: WMNW:DC75:4663:BZTY:6B6I:SE2Z:M4SU:YGKB:H3TM:HW3H:N2N5:SQKL
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: ##
 Goroutines: ##
 System Time: 2017-04-06T21:03:56.046934151Z
 EventsListeners: 0
Username: ##
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries: ##
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
curl version (by `curl -V`):
```
curl 7.53.1 (x86_64-apple-darwin15.6.0) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #32417

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM, should probably be cherry-picked in 17.06.x ? /cc @mlaventure

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
@vieux it was reported with 17.03, so not new, and IIUC when directly using the API https://github.com/moby/moby/issues/32417, to probably not _critical_, more "good to have"

**Comment by thaJeztah** [comment]
all green 💚

**Pull request merged**
