### PR TITLE
vendor: github.com/Microsoft/hcsshim v0.8.22

### PR DESCRIPTION
**Pull request by thaJeztah**
No significant changes for our vendored code, but reverts back containerd minimal
dependency to v1.4.9.

full diff: https://github.com/Microsoft/hcsshim/compare/v0.8.20...v0.8.22

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
```
=== FAIL: cmd/docker-proxy TestSCTP4Proxy (0.29s)
2021/11/05 14:07:50 Can't forward traffic to backend sctp/127.0.0.1:34208: transport endpoint is already connected
```

**Comment by thaJeztah** [comment]
> Unable to delete '/home/ubuntu/workspace/moby_PR-42987'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts. (Discarded 9 additional exceptions)

For those reading along; that one is tracked through https://github.com/moby/moby/issues/42974, and I was trying to debug in https://github.com/moby/moby/pull/42995

**Comment by thaJeztah** [comment]
Failure on Windows (flaky test?); opened https://github.com/moby/moby/issues/43012

```
=== RUN   TestDockerSuite/TestSlowStdinClosing
    docker_cli_run_test.go:4177: assertion failed: error is not nil: exit status 127
    --- FAIL: TestDockerSuite/TestSlowStdinClosing (0.92s)
```

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by samuelkarp — APPROVED** [review]
LGTM

**Pull request merged**
