### PR TITLE
Fall back to V1 when there are no basic auth credentials

### PR DESCRIPTION
**Pull request by aaronlehmann**
This makes the behavior consistent with having incorrect credentials. It addresses part of https://github.com/docker/docker/issues/19834, though this issue mentions a lot of things so I won't say it completely fixes it (I'd suggest splitting that issue into smaller issues that we can evaluate and triage separately).

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by icecrime** [comment]
Haven't tested, but code LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by runcom** [comment]
Coll

**Comment by bibstha** [comment]
Hi guys, why should authentication be absolutely necessary to run a private v2 registry? We already have an ssl endpoint which run off a local ip address and adding basic auth is moot. Any thoughts?

**Comment by aaronlehmann** [comment]
Authentication isn't necessary. By default, the v2 registry doesn't require authentication. This PR only covers the case where the registry asks for basic auth credentials and the user hasn't provided any.

**Pull request merged**
