### PR TITLE
Fix wrong command in changelog

### PR DESCRIPTION
**Pull request by albers**
Fixes a wrong command in the changelog: `s/create service/service create/`

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
oops! LGTM

**Comment by thaJeztah** [comment]
@vieux @tiborvass FYI

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by justincormack — APPROVED** [review]

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
