### PR TITLE
[test/integration] Small daemon refactoring and add swarm init/join helpers

### PR DESCRIPTION
**Pull request by vdemeester**
:lion: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
hum I broke something :thinking:

**Comment by thaJeztah** [comment]
Janky is failing on a flaky test; https://jenkins.dockerproject.org/job/Docker-PRs/48971/console, which is tracked through https://github.com/moby/moby/issues/32673

```
16:29:12 ----------------------------------------------------------------------
16:29:12 FAIL: docker_api_swarm_test.go:297: DockerSwarmSuite.TestAPISwarmLeaderElection
16:29:12 
16:29:12 [d478405b8f18b] waiting for daemon to start
16:29:12 [d478405b8f18b] daemon started
16:29:12 
16:29:12 [d5b688c6ab843] waiting for daemon to start
16:29:12 [d5b688c6ab843] daemon started
16:29:12 
16:29:12 [deb10f5554730] waiting for daemon to start
16:29:12 [deb10f5554730] daemon started
16:29:12 
16:29:12 [d478405b8f18b] exiting daemon
16:29:12 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
16:29:12 [d5b688c6ab843] exiting daemon
16:29:12 [deb10f5554730] exiting daemon
16:29:36 
```

Windows failure (https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/20409/console) is also flaky https://github.com/moby/moby/issues/33301

```
16:10:27 ----------------------------------------------------------------------
16:10:27 FAIL: docker_api_logs_test.go:23: DockerSuite.TestLogsAPIWithStdout
16:10:27 
16:10:27 docker_api_logs_test.go:55:
16:10:27     c.Fatal("timeout waiting for logs to exit")
16:10:27 ... Error: timeout waiting for logs to exit
16:10:27 
```

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM

**Pull request merged**
