### PR TITLE
Update API plugin response examples

### LINKED ISSUE #34241: PluginList operation response is different from the documentation
Docker API documentation needs to be updated.

The `/plugins` endpoint returns the following response: https://github.com/moby/moby/blob/0ac25dfc751fa4304ab45afd5cd8705c2235d101/api/types/plugin_responses.go#L1

Based on https://github.com/moby/moby/blob/0ac25dfc751fa4304ab45afd5cd8705c2235d101/api/types/plugin.go#L8-L31

The plugin object is quite different from the one documented in the 200 response sample at https://docs.docker.com/engine/api/v1.30/#operation/PluginList

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/34241

**- What I did**

Updated API response examples for the plugin endpoints

**- How I did it**

Remove example structs, and set per-property examples instead

**- How to verify it**

run `make swagger-docs` and visit https://localhost:9000 in your browser

**- Description for the changelog**

    Update API response examples for plugin endpoints

ping @deviantony  @tiborvass @vieux PTAL

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
👍 LGTM

**Comment by thaJeztah** [comment]
boo!

```
16:34:13 api/swagger.yaml
16:34:13   1624:26   error    too many spaces after colon  (colons)
``

LOL, I'll update

**Comment by deviantony** [comment]
Looks like I have encoding issues when I run the docs locally but I can see it in all the endpoints so it's probably related to my setup.

redoc

Other than that, LGTM.

**Review by deviantony — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @tiborvass @vieux @cpuguy83 PTAL

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
author LGTM 👍

**Pull request merged**
