### PR TITLE
Skip kernel-memory tests on RHEL/CentOS daemons

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/opencontainers/runc/pull/1921, https://github.com/moby/moby/pull/38128

RHEL/CentOS 3.10 kernels report that kernel-memory accounting is supported, but it actually does not work.

Runc (when compiled for those kernels) will be compiled without kernel-memory support, so even though the daemon may be reporting that it's supported, it actually is not.

This cause tests to fail when testing against a daemon that's using a runc version without kmem support.

For now, skip these tests based on the kernel version reported by the daemon.

This should fix failures such as:

```
FAIL: /go/src/github.com/docker/docker/integration-cli/docker_cli_run_unix_test.go:499: DockerSuite.TestRunWithKernelMemory

assertion failed:
Command:  /usr/bin/docker run --kernel-memory 50M --name test1 busybox cat /sys/fs/cgroup/memory/memory.kmem.limit_in_bytes
ExitCode: 0
Error:    <nil>
Stdout:   9223372036854771712

Stderr:   WARNING: You specified a kernel memory limit on a kernel older than 4.0. Kernel memory limits are experimental on older kernels, it won't work as expected and can cause your system to be unstable.

Failures:
Expected stdout to contain "52428800"

FAIL: /go/src/github.com/docker/docker/integration-cli/docker_cli_update_unix_test.go:125: DockerSuite.TestUpdateKernelMemory

/go/src/github.com/docker/docker/integration-cli/docker_cli_update_unix_test.go:136:
    ...open /go/src/github.com/docker/docker/integration-cli/docker_cli_update_unix_test.go: no such file or directory
... obtained string = "9223372036854771712"
... expected string = "104857600"

----------------------------------------------------------------------
FAIL: /go/src/github.com/docker/docker/integration-cli/docker_cli_update_unix_test.go:139: DockerSuite.TestUpdateKernelMemoryUninitialized

/go/src/github.com/docker/docker/integration-cli/docker_cli_update_unix_test.go:149:
    ...open /go/src/github.com/docker/docker/integration-cli/docker_cli_update_unix_test.go: no such file or directory
... value = nil
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by fntlnz — APPROVED** [review]
LGTM :dog:

**Review by seemethere — APPROVED** [review]

**Comment by thaJeztah** [comment]
z failure is a known flaky

```
19:02:19 --- FAIL: TestServiceUpdateSecrets (3.65s)
19:02:19     daemon.go:296: [dd206e667e912] waiting for daemon to start
19:02:19     daemon.go:328: [dd206e667e912] daemon started
19:02:19     update_test.go:126: assertion failed: error is not nil: Error response from daemon: rpc error: code = Unknown desc = update out of sequence
19:02:19     daemon.go:283: [dd206e667e912] exiting daemon
19:02:19 === RUN   TestServiceUpdateConfigs
19:02:23 --- FAIL: TestServiceUpdateConfigs (3.71s)
19:02:23     daemon.go:296: [d3fb0fa7599a4] waiting for daemon to start
19:02:23     daemon.go:328: [d3fb0fa7599a4] daemon started
19:02:23     update_test.go:188: assertion failed: error is not nil: Error response from daemon: rpc error: code = Unknown desc = update out of sequence
19:02:23     daemon.go:283: [d3fb0fa7599a4] exiting daemon
```

I'll merge this one

**Comment by kolyshkin** [comment]
Would be slightly better to check that suffix ("tag") containes `.el7.` substring, but practically the check for 3.10 is fine, too, as there are no other distros I'm aware of that runs this kernel version.

**Comment by thaJeztah** [comment]
> Would be slightly better to check that suffix ("tag") containes .el7. substring, but practically the check for 3.10 is fine, too, as there are no other distros I'm aware of that runs this kernel version.

Yes, was doubting to be more specific, but given that we're not running CI on any other 3.x kernels that support kmem support, I decided to keep it simple

**Pull request merged**
