### PR TITLE
daemon: don't listen on the same address multiple times

### PR DESCRIPTION
**Pull request by thaJeztah**
see https://github.com/moby/moby/pull/39454#issuecomment-511054056

Before this change:

    dockerd -H unix:///run/docker.sock -H unix:///run/docker.sock -H unix:///run/docker.sock
    ...
    INFO[2019-07-13T00:02:36.195090937Z] Daemon has completed initialization
    INFO[2019-07-13T00:02:36.215940441Z] API listen on /run/docker.sock
    INFO[2019-07-13T00:02:36.215933172Z] API listen on /run/docker.sock
    INFO[2019-07-13T00:02:36.215990566Z] API listen on /run/docker.sock

After this change:

    dockerd -H unix:///run/docker.sock -H unix:///run/docker.sock -H unix:///run/docker.sock
    ...
    INFO[2019-07-13T00:01:37.533579874Z] Daemon has completed initialization
    INFO[2019-07-13T00:01:37.567045771Z] API listen on /run/docker.sock

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83

**Comment by thaJeztah** [comment]
hmmm looks like this broke TestInfoAPIWarnings. Weird

**Comment by thaJeztah** [comment]
oh, I'm stupid; I see where I went wrong

**Comment by thaJeztah** [comment]
experimental is failing on `TestInspectNetwork`

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/45926/consoleFull

```
01:03:29 --- FAIL: TestInspectNetwork (5.04s)
01:03:29     inspect_test.go:18: Creating a new daemon
01:03:29     daemon.go:336: [d31da1d0eee59] waiting for daemon to start
01:03:29     daemon.go:336: [d31da1d0eee59] waiting for daemon to start
01:03:29     daemon.go:336: [d31da1d0eee59] waiting for daemon to start
01:03:29     daemon.go:336: [d31da1d0eee59] waiting for daemon to start
```

Error messages:

```
time="2019-07-13T01:03:25.303653977Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh2" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh2: no such file or directory"
time="2019-07-13T01:03:25.303669202Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh3" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh3: no such file or directory"
time="2019-07-13T01:03:25.303685835Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh1" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh1: no such file or directory"
time="2019-07-13T01:03:25.365879415Z" level=error msg="error reading the kernel parameter net.ipv4.vs.expire_nodest_conn" error="open /proc/sys/net/ipv4/vs/expire_nodest_conn: no such file or directory"
time="2019-07-13T01:03:25.550470174Z" level=error msg="error reading the kernel parameter net.ipv4.vs.expire_nodest_conn" error="open /proc/sys/net/ipv4/vs/expire_nodest_conn: no such file or directory"
time="2019-07-13T01:03:27.471109224Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."
time="2019-07-13T01:03:28.609238397Z" level=error msg="Inconsistent driver and libnetwork state for endpoint 7247aa6ba3417af3500405cc16bd86795e19466a71cad964ef767d3b3cdba4e9"
time="2019-07-13T01:03:28.610509263Z" level=error msg="Inconsistent driver and libnetwork state for endpoint 7247aa6ba3417af3500405cc16bd86795e19466a71cad964ef767d3b3cdba4e9"
time="2019-07-13T01:03:28.612106921Z" level=error msg="Inconsistent driver and libnetwork state for endpoint 7247aa6ba3417af3500405cc16bd86795e19466a71cad964ef767d3b3cdba4e9"
time="2019-07-13T01:03:28.620044315Z" level=error msg="Inconsistent driver and libnetwork state for endpoint 7247aa6ba3417af3500405cc16bd86795e19466a71cad964ef767d3b3cdba4e9"
time="2019-07-13T01:03:28.630295745Z" level=error msg="Error getting tasks: service yblygwx0w3n4dvm4ptgqs6xyj not found"
time="2019-07-13T01:03:28.635662636Z" level=error msg="failed to remove node" error="rpc error: code = Aborted desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=3oz6vheefok39p6f0zmfhgsci node.session=j6o0l9cxk86424zxnt91sfzup
time="2019-07-13T01:03:28.635931450Z" level=error msg="failed to receive changes from store watch API" error="rpc error: code = Unknown desc = context canceled"
time="2019-07-13T01:03:28Z" level=error msg="set up rule failed, [-t mangle -D INPUT -d 10.0.0.2/32 -j MARK --set-mark 256]:  (iptables failed: iptables --wait -t mangle -D INPUT -d 10.0.0.2/32 -j MARK --set-mark 256: iptables: No chain/target/match by that name.\n (exit status 1))"
time="2019-07-13T01:03:28.684492128Z" level=error msg="Failed to delete firewall mark rule in sbox lb_1rql (lb-Over): reexec failed: exit status 8"
time="2019-07-13T01:03:28.684565709Z" level=error msg="Failed add IP alias 10.0.0.2 to network 1rqlilvhciazip8c26o9hf3dr LB endpoint interface eth0: cannot assign requested address"
```

Full logs attached:
[docker.log](https://github.com/moby/moby/files/3388308/docker.log)

**Comment by thaJeztah** [comment]
(rebased to get the latest fixes in)

**Comment by thaJeztah** [comment]
one possible flaky on powerpc; https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/14865/console

I'll download and check the bundle

```
15:01:44 FAIL: docker_api_swarm_service_test.go:63: DockerSwarmSuite.TestAPISwarmServicesCreate
15:01:44 
15:01:44 Creating a new daemon
15:01:44 [d680853c0f2d2] waiting for daemon to start
15:01:44 [d680853c0f2d2] waiting for daemon to start
15:01:44 [d680853c0f2d2] daemon started
15:01:44 
15:01:44 waited for 1.293613486s (out of 30s)
15:01:44 waited for 1.291748626s (out of 30s)
15:01:44 docker_api_swarm_service_test.go:93:
15:01:44     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 0)
15:01:44 docker_utils_test.go:435:
15:01:44     c.Assert(v, checker, args...)
15:01:44 ... obtained int = 1
15:01:44 ... expected int = 0
15:01:44 ... output: "0697afb52501\n"
15:01:44 
15:01:44 waited for 30.040386071s (out of 30s)
15:01:44 [d680853c0f2d2] Stopping daemon
15:01:44 [d680853c0f2d2] exiting daemon
15:01:44 [d680853c0f2d2] Daemon stopped
15:02:14 
15:02:14 -

**Comment by thaJeztah** [comment]
Error messages in the logs of that failing test;

```
time="2019-07-13T13:01:11.226286097Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh3" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh3: no such file or directory"
time="2019-07-13T13:01:11.226336974Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh1" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh1: no such file or directory"
time="2019-07-13T13:01:11.226383933Z" level=error msg="error reading the kernel parameter net.ipv4.neigh.default.gc_thresh2" error="open /proc/sys/net/ipv4/neigh/default/gc_thresh2: no such file or directory"
time="2019-07-13T13:01:11.401028844Z" level=error msg="error reading the kernel parameter net.ipv4.vs.expire_nodest_conn" error="open /proc/sys/net/ipv4/vs/expire_nodest_conn: no such file or directory"
time="2019-07-13T13:01:13.866332640Z" level=error msg="failed transaction: update task desired state to REMOVE" error="update out of sequence" module=node node.id=p2ooccli7j4s22fohkogk2to8
time="2019-07-13T13:01:43.911326393Z" level=error msg="failed to remove node" error="rpc error: code = Aborted desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=p2ooccli7j4s22fohkogk2to8 node.session=mni1w1onw2cbkz21626zj60ts
time="2019-07-13T13:01:43.912337728Z" level=error msg="failed to receive changes from store watch API" error="rpc error: code = Unknown desc = context canceled"
```

[docker.log](https://github.com/moby/moby/files/3389124/docker.log)

**Review by AkihiroSuda — APPROVED** [review]

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
