### PR TITLE
Handle escaped characters sent by a HTTP client

### PR DESCRIPTION
**Pull request by shiroyuki**
When the request was sent from a HTTP client, the tag value may be escaped. This is to unescape the value first before parse the tag value.

**How to reproduce:**
1. Use docker-py's Client to build an image with a tag like "john/doe".
2. When you run `docker images -a`, you will notice that the new image does not have the tag "john/doe".

### CODE REVIEW

**Comment by cpuguy83** [comment]
Needs a go-fmt.

**Comment by shiroyuki** [comment]
@cpuguy83 what do you mean by **go-fmt**?

**Comment by vdemeester** [comment]
@shiroyuki That's what the CI says (you can run it locally using `make validate`)

> ---> Making bundle: validate-gofmt (in bundles/1.9.0-dev/validate-gofmt)
> These files are not properly gofmt'd:
>  - pkg/parsers/parsers.go
>
> Please reformat the above files using "gofmt -s -w" and commit the result.

**Comment by shiroyuki** [comment]
@vdemeester Oh. Thank you. :smiley:

**Comment by shiroyuki** [comment]
I just double-checked the failed integration-CLI tests. It seems to be unrelated to my changes and it also passes on my local copy. Can anyone rerun the tests or any maintainers rerun the **userns** check?

**Comment by thaJeztah** [comment]
I kicked the users build, but there's a flaky test, so don't worry about it too much

Thanks @shiroyuki !

**Comment by vdemeester** [comment]
Speaking of test, would be really cool to add a test on that :wink:, probably [here](https://github.com/docker/docker/blob/master/pkg/parsers/parsers_test.go#L123).

**Comment by thaJeztah** [comment]
ping @shiroyuki could you add a test, as @vdemeester asked above? https://github.com/docker/docker/pull/17204#issuecomment-150122325 Thanks!

**Comment by endophage** [comment]
I'm not sure this change is necessary given current limitations on permitted characters in repo and tag names. However in the spirit of defensive programming (and in the expectation we will support a wider range of characters in the future), this is a good update.

Pending tests, LGTM.

**Comment by shiroyuki** [comment]
@thaJeztah I'll add a test for this case. Please give me a day. :smile:

**Comment by shiroyuki** [comment]
Tests added and CI jobs seemed to be happy. Can anyone review the tests? :smiley:

**Comment by endophage** [comment]
Would like to see at some negative tests containing a mix of valid and invalid escape sequences.

**Comment by shiroyuki** [comment]
@endophage I saw duplicated code in the test. Should I also refactor the test while adding negative cases?

**Comment by endophage** [comment]
If you truly feel it's duplicated then sure, that would be awesome!

**Comment by dmcgowan** [comment]
I know this seemed to skip the design phase but I have an issue with where this is occurring. I agree with the goal of handling escaped characters but this should be done at the HTTP api level, not in the parser package. This function is called from many different parts of the code many of which should not have escaped content.

**Comment by aaronlehmann** [comment]
I agree with @dmcgowan. HTTP unescaping shouldn't be by the tag parser.

**Comment by shiroyuki** [comment]
I now see that this should be handled over there. But...

Initially, the scope of this problem is only on how the server API endpoints deals with encoded characters. Consider that the following examples are how each endpoint handles the request data.

Suppose `key` is `string` and `request` is `*http.Request`.

``` go
value := r.Form.Get(key)
```

or 

``` go
value := r.FormValue(key)
```

This means the problem related to the tag name is just the beginning of the other problems potentially caused by the similar coding pattern. I'll go ahead working fixing the tag problem. But should I go ahead and decode/unescape everything?

**Comment by shiroyuki** [comment]
I will deal from the request handler and abandon this PR.

**Comment by shiroyuki** [comment]
@dmcgowan I reimplemented according to your suggestion and resubmitted as #17917. Can you check when you have a minute?

**Pull request closed without merging**
