### PR TITLE
Add zsh completion for 'docker stats --all -a'

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref #16742

@albers @thaJeztah Thx for the ping guys.
@vincentbernat FYI

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vincentbernat** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @sdurrheimer :+1:

**Pull request merged**
