### PR TITLE
Version 1.2.0 set root:root permissions on /var/run/docker.socket

### PR DESCRIPTION
**Pull request by jessfraz**
Version 1.2.0 set root:root permissions on /var/run/docker.socket instead of root:docker for Debian Jessie. 
This change fixes that.

Signed-off-by: Jessica Frazelle jfrazelle@users.noreply.github.com

### CODE REVIEW

**Comment by zaidiahmed** [comment]
docker 1.6 is seeing this issue:
root:root owns docker.socket 

CENTOS7
DOCKER 1.6

yum install docker

service docker start

ls -ltr /var/run/docker.sock

**Comment by jfrazelle** [comment]
That would be a problem w the rpm centos is distributing, unfortunately we
don't control those but will have our own by 1.7.0 :)

**Comment by jfrazelle** [comment]
So you will need to take that up with their bug tracker

**Comment by zaidiahmed** [comment]
Thanks you.

**Pull request closed without merging**
