### PR TITLE
Makes a few modifications to the name generator.

### PR DESCRIPTION
**Pull request by debayande**
## What I did
Made a few modifications to the name generator

## How I did it
I made the modifications in question to `pkg/namesgenerator/names-generator.go`

## How does one verify it
Please check `pkg/namesgenerator/names-generator.go`

## A description for the changelog
* Replaces `cocks` with `cerf` as the former might be perceived as
offensive by some people (as pointed out by @jeking3
[here](https://github.com/moby/moby/pull/37157#commitcomment-31758059))
* Removes a duplicate entry for `burnell`
* Re-arranges the entry for `sutherland` to ensure that the names are in
sorted order
* Adds entries for `shamir` and `wilbur`

## A picture of a cute animal (not mandatory but encouraged)
image

Signed-off-by: Debayan De <debayande@users.noreply.github.com>

### CODE REVIEW

**Review by fntlnz — APPROVED** [review]
LGTM thanks @debayande

**Review by yongtang — APPROVED** [review]
LGTM

**Review by thaJeztah — COMMENTED** [review]
LGTM

**Comment by justincormack** [comment]
Why did we remove Burnell?

**Comment by thaJeztah** [comment]
> * Removes a duplicate entry for `burnell`

She was in there twice 😅

**Pull request merged**
