### PR TITLE
libnetwork/drivers/overlay: support IPv6 transport

### LINKED ISSUE #41691: Docker swarm does not send VXLAN traffic when configured to use IPv6
**Description**

Using [this guide](https://docs.docker.com/network/network-tutorial-overlay/) to setup overlay networking between two standalone containers on different hosts, everything works up until the point that I use ping to test connectivity between the containers, which does not work -- DNS resolution works fine, but the containers cannot communicate.

The issue occurs when the swarm is initiated using an IPv6 address: `docker swarm init --advertise-addr <IPv6::addr>`.  `tcpdump` on both hosts shows that packets are flowing correctly over the IPv6 interface on ports 2377 and 7946, but there is no traffic at all on the VXLAN port 4789 (IPv6 or IPv4).

There are no firewalls on either host and testing using `netcat` with Docker shutdown shows that there are no issues communicating between hosts on port 4789, both IPv6 and IPv4.

Following the guide again, but forcing Docker to use the IPv4 interface (`docker swarm init --advertise-addr <IPv4.addr>`) makes everything work properly, so this appears to be only an IPv6 issue.

**Steps to reproduce the issue:**
1. Follow [this guide](https://docs.docker.com/network/network-tutorial-overlay/)
2. Specify an IPv6 address for the `docker swarm init --advertise-addr` command
3. Try to ping between containers

**Describe the results you received:**

There is no network connectivity between the containers.

**Describe the results you expected:**

There should be network connectivity between the containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-54-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.941GiB
 Name: beta
 ID: BSTM:JVK3:KORD:JEZ5:CTS5:NSLV:OWX5:MM7W:2L7J:3CHP:TO6Y:S4B6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The hosts are Xen VPS instances.  OS is Ubuntu 20.04, but I have also tried Ubuntu 18.04 with the same Docker version.

### PR DESCRIPTION
**Pull request by corhere**
- Fixes #41691

The forwarding database (fdb) of Linux VXLAN links are restricted to entries with destination VXLAN tunnel endpoint (VTEP) address of a single address family. Which address family is permitted is set when the link is created and cannot be modified. The overlay network driver creates VXLAN links such that the kernel only allows fdb entries to be created with IPv4 destination VTEP addresses. If the Swarm is configured with IPv6 advertise addresses, creating fdb entries for remote peers fails with `EAFNOSUPPORT` (address family not supported by protocol).

**- What I did**
Make overlay networks functional over IPv6 transport by configuring the VXLAN links for IPv6 VTEPs and inserting the iptables rules into ip6tables if the local node's advertise address is an IPv6 address.

**- How I did it**
By replicating what `ip -6 link add vxlan0 type vxlan` would do.

**- How to verify it**
Set up a multi-node swarm with IPv6 advertise addresses. Create an overlay network and run containers on two of the nodes, both attached to the overlay. Check that the two containers can pass traffic to each other through the overlay network.

Repeat with an encrypted overlay network. Run two containers attached to the overlay, exec into one and ping the other. On the host of the other container, delete the MANGLE OUTPUT rule from ip6tables and verify that the pings stop.

**- Description for the changelog**

- Added support for overlay networks over IPv6 transport

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Getting a compile failure, but only on Jenkins (arm64) 🤔 

```

[2023-11-09T23:08:23.312Z] === Errors
[2023-11-09T23:08:23.312Z] libnetwork/sandbox_store.go:278:41: undefined: scope
[2023-11-09T23:08:23.312Z] libnetwork/store.go:71:14: undefined: scope
[2023-11-09T23:08:23.312Z] libnetwork/store.go:108:14: undefined: scope
```

**Review by akerouanton — APPROVED** [review]
LGTM

**Comment by robmry** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

thanks all for helping review 👍

**Comment by gabrielmocan** [comment]
Now it's possible to set de docker_gwbridge with IPv6 and containers will get their IPv6 based on the gwbridge IPv6 prefix?

Or even dual stack?

**Pull request merged**
