### PR TITLE
[WIP] Support containerd shim v2

### LINKED ISSUE #38559: Any plans to support containerd shim v2?
Since containerd implements the shimv2 API(https://github.com/containerd/containerd/pull/2434) and Kata supports the v2 API too(https://github.com/kata-containers/runtime/pull/572), does moby has any plans to support it?

### PR DESCRIPTION
**Pull request by BetaXOi**
Support invoking a customized version of shim

Fixes #38559 
Relates to https://github.com/docker/cli/pull/1635

Signed-off-by: NingBo <ning.bo9@zte.com.cn>

### CODE REVIEW

**Comment by cpuguy83** [comment]
Is this still work in progress?

**Comment by thaJeztah** [comment]
New PR (part of the bigger effort to integrate with the containerd meta-store) is here; https://github.com/moby/moby/pull/38943

**Comment by thaJeztah** [comment]
Let me close this one for now (I also think this will be part of the containerd integration that's being worked on) but let us know if you want to work on this again

**Comment by thaJeztah** [comment]
For those arriving here; should be addressed by;

- https://github.com/moby/moby/pull/43800

**Pull request closed without merging**
