### PR TITLE
remove unnecessary temporary variable

### PR DESCRIPTION
**Pull request by mqliang**
remove unnecessary temporary variable

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @mqliang, looks like you forgot to sign-off your commit. Can you fix that, using the steps that @GordonTheTurtle described above?

**Comment by aaronlehmann** [comment]
LGTM once signed.

**Comment by mqliang** [comment]
@thaJeztah @aaronlehmann signed.

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks for another contribution @mqliang !

**Pull request merged**
