### PR TITLE
Update compose schema v3

### PR DESCRIPTION
**Pull request by dnephin**
The compose v3 schema was updated in `docker/compose`, so bringing those changes in here.

Also fix a bug with the hack/validate script

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
Should this be cherry-pick ? (if it's v3 and not v3.1)

**Comment by dnephin** [comment]
It wouldn't hurt, but I don't think it's a P0. This patch wont apply because in the 1.13 branch these files are still under vendor.

**Comment by vdemeester** [comment]
@dnephin ohh true. But that means the `v3` compose file format `1.13.0` will differ from the `v3` supported in compose, right ?

**Comment by dnephin** [comment]
The only difference is for these two new fields. If they are in a Compose file it will error instead of getting a warning about "unsupported options". Since they are brand new they aren't going to be widely used. It's a bug, but I don't think i would consider it a P0. Should be fine for a patch release.

**Comment by dnephin** [comment]
More fixes to match Compose master

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by vdemeester** [comment]
ping @thaJeztah #30297 has 1.13.1 milestone, should this be cherry-picked ?

**Comment by dnephin** [comment]
Yes, I think it should

**Comment by vieux** [comment]
this PR is included in https://github.com/docker/docker/pull/30325 and it was already cherry-picked in 1.13.x

**Pull request merged**
