### PR TITLE
Bump docker/distribution to 83389a148052d74ac602f5f1d62f86ff2f3c4aa5

### PR DESCRIPTION
**Pull request by novas0x2a**
vendored distribution is quite old, and current distribution contains an
API break, which means it's not possible to vendor a bugfixed
distribution and docker/docker master at the same time.

Note: locally, TestTarUntarWithXattr fails for me in both this branch and the current master; I'm not sure what's happening, but I don't think it's related to this PR. (I'm hoping the CI tests will pass).

**- What I did**

Bumped docker/distribution and made the minor changes necessary to deal with that.

**- How I did it**

Typing frantically until it was done.

**- How to verify it**

In theory this should be pretty low-impact, since docker/moby doesn't actually use a lot of the distribution package. I'd expect that if it compiles and passes tests, it'd probably work.

**- Description for the changelog**
Updated vendored copy of docker/distribution to ease projects trying to vendor both moby/moby (docker/docker) and docker/distribution.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by novas0x2a** [comment]
Some of the jenkins builds failed, but it doesn't look like the failures had anything to do with my changes. Can you retrigger?

**Comment by thaJeztah** [comment]
hm, looks like I don't have an option / permissions to restart the `vendor` CI; can you try force-pushing your branch to  trigger CI?

**Comment by thaJeztah** [comment]
Full diff is https://github.com/docker/distribution/compare/edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c...83389a148052d74ac602f5f1d62f86ff2f3c4aa5

**Comment by novas0x2a** [comment]
Looks like mostly green this time; presumably (from their names) experimental and janky aren't expected to pass?

**Comment by novas0x2a** [comment]
Heyyyy all green now

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @dmcgowan @cpuguy83

**Comment by stevvooe** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :lion:

**Pull request merged**
