### PR TITLE
Add swagger.yaml and generate a few types from the spec

### PR DESCRIPTION
**Pull request by dnephin**
Related issues: #22931, #5893, https://github.com/docker/engine-api/issues/77

The swagger spec was developed here: https://github.com/bfirsh/docker-api-reference/blob/master/swagger.yaml. That repo include some validation checks which I think we should also include if this PR is merged.

The swagger spec will initially be used:
- to generate the types used by the api `api/types`
- to generate api reference documentation https://bfirsh.github.io/docker-api-reference/

Eventually we should also be able to generate `api/server/router/*` and most of `client/*` from the spec. Most of the code in those packages is very boilerplate, and would be a lot more consistent if it were generated from a spec.

### CODE REVIEW

**Comment by dnephin** [comment]
I'm going to continue to add a few types of this PR as it is being discussed.

cc @bfirsh , @cpuguy83

**Comment by dnephin** [comment]
I guess the types could also be generated from a `go:generate` instruction.

**Comment by vieux** [comment]
Big 👍 on the proposed change.

**Comment by dnephin** [comment]
@mlaventure the generated types are now using normal `// ` go comments

**Comment by mlaventure** [comment]
It looks some much cleaner, thanks!

They're not go-lint proof, but I see we added them to the skip list,

LGTM

**Comment by LK4D4** [comment]
design LGTM

**Comment by thaJeztah** [comment]
ping @dnephin can you rebase? Then I think we should be ready to go.

We may need to describe the process (i.e. when to generate, integrate into CI etc)

**Comment by dnephin** [comment]
rebased

**Comment by dnephin** [comment]
Yes, this also needs CI integration. It should work the same way as our vendor check (but it runs much faster).

**Comment by thaJeztah** [comment]
looks like we have enough LGTM's and CI is :green_heart:, merging

**Pull request merged**
