### PR TITLE
Allow non-seccomp platforms to pass integration-cli tests

### PR DESCRIPTION
**Pull request by estesp**
Since seccomp is still a configurable build-tag, add a requirements
entry for seccomp, as well as move seccomp tests to "_unix" given it
won't be applicable to other platforms at this time.

Docker-DCO-1.1-Signed-off-by: Phil Estes estesp@linux.vnet.ibm.com (github: estesp)

### CODE REVIEW

**Comment by jfrazelle** [comment]
eeee sorry!

**Comment by jfrazelle** [comment]
LGTM as long as tests good

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :heart_eyes_cat:

**Pull request merged**
