### PR TITLE
Add 'TAG' instruction of Dockerfile.

### LINKED ISSUE #5603: Add TAG command to Dockerfile
Like the MAINTAINER command, a TAG command would allow a Dockerfile to record the intended destination for a container after a build.  When doing a `docker build` from command line, the TAG command would allow a default `-t mytag/mycontainer` to be used.  If `docker build` is passed a different `-t mytag/mycontainer` then it would overwrite the TAG command in the dockerfile.

This would be especially useful for those of us using a private docker registry so we can see what others tagged a built container as when it was pushed to a private registry.

### PR DESCRIPTION
**Pull request by xuxinkun**
closes #5603
Signed-off-by: xuxinkun xuxinkun@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
@xuxinkun if I understand correctly, this is an implementation of https://github.com/docker/docker/issues/5603 ?

If it is, please add `closes #5603` to the description.

Note to reviewers / maintainers; this is an implementation of a **proposal**, no decision was taken yet on that proposal.

**Comment by xuxinkun** [comment]
@thaJeztah You are right. As you say in #5603 , the TAG should allow to:
Create multiple images from a single Dockerfile
Create different tags for the same image

By this pull request, these could be easily achieved.

But I don't think it is an good idea for Overriding. So even with 'build -t', TAG instruction in the Dockerfile also should be taken effect.

**Comment by thaJeztah** [comment]
Oh, that's really a long time ago (actually forgot about that proposal).

The important thing here is that the proposal #5603 has not (yet?) been accepted by the core maintainers. Adding new commands to the Dockerfile syntax is not something that should be taken lightly, because we don't want to add too many commands (that need to be maintained and only "clutter" the Dockerfile syntax).

Thanks for giving this a go, though; Lets see if the maintainers can make a decision on this.

**Comment by xuxinkun** [comment]
@thaJeztah 'TAG' command can easily tag the middle image layer in Dockerfile, which will cause some interesting things. Please see here https://github.com/docker/docker/issues/12987.

**Comment by cpuguy83** [comment]
-1, I don't think it makes sense for dockerfile to dictate how the image is actually being referenced.

**Comment by duglin** [comment]
This one is kind of interesting.  My initial reaction was the same as @cpuguy83's, at least for the final image produced, but what's bugging me is that the user is kind of hosed for those intermediate images.

I think today the recommended way to save those intermediate images would be to split up your Dockerfile so that each image gets its own Dockerfile and then you can use the '-t' flag to name each one during the 'docker build'. And then the N+1 Dockerfile would just use `FROM <<N's image name>`.
E.g.
```
$ docker build -t baseImage baseDir/
$ docker build myAppDir/
```
where myAppDir/Dockerfile started with
```
FROM baseImage
```

So, the real question seems to be whether forcing this split is ok from a usability perspective. Are Dockerfiles like Makefiles where-in they are **supposed** to be used for multiple targets (images) or should it be a one-to-one (Dockerfile->image) mapping?

I think historically its been 1-1. Does the introduction of 'compose' provide enough of that extra layer on top to build all of these images w/o forcing people to use something like 'make' as well?  It seems pretty close.  But I'd be interested in hearing what others think.

**Comment by thaJeztah** [comment]
It would certainly make it easier to update a range of images that build upon each other.

Currently, we **do** allow multiple `FROM` instructions in a Dockerfile, but you'll have to manually grab the layer ID and tag it, which (IMO) is not very useful (see for example: https://docs.docker.com/reference/builder/#dockerfile-examples)

**Comment by xuxinkun** [comment]
As @thaJeztah say, Dockerfile can contain several `FROM` instructions. So, `TAG` support is useful for not only tagging intermediate images, but also tagging several images in one Dockerfile. The user will not need to remember the tag but record the tag in Dockerfile by `TAG` command.

**Comment by xuxinkun** [comment]
@cpuguy83 I think tag is also a part of image. The parameter of `docker build` such as -q, --rm is used to guide how to build a image. But what the image really is(image-id), what the image contains or how the image should deploy(image-config) is the attribute of the image. These things can be defined in Dockerfile. Tag is also an attribute of the image. So that's why I think Dockerfile should have `TAG` command.

**Comment by thaJeztah** [comment]
I *do* understand @cpuguy83's concerns and this *should* get a proper thinking.

**If** this is accepted, then my original comment: https://github.com/docker/docker/issues/5603#issuecomment-51389946 still stands; if the Dockerfile is built with a `-t / --tag` specified, then all `TAG` instructions should be ignored and *only* the final image should be tagged (with the name/tag specified in the `-t / --tag`). That way, the user is still in control and *not* the Dockerfile.

**Comment by xuxinkun** [comment]
@thaJeztah Maybe you are right. I change my mind. I will provide the feature that '-t' can ignore all `TAG` instruction. But by default, 'TAG' instruction can force overriding the tags.  If this could be accepted, I will code this in these days.

**Comment by duglin** [comment]
I totally forgot about the fact that we can have more than one FROM in a Dockerfile. IMO that changes quite a lot because getting the image IDs for the intermediate images is going to be more than a little challenging.  What's the recommended way for people to tag those?  I hope we're not expecting them to grep/sed/awk the build output?  I'm not sure I can see another option aside from something like a TAG command.  Part of me would almost prefer to ban multiple FROM :-)

If people are worried about a Dockerfile author stomping on an existing image name, I suppose one option would be to make -t not only set the final image name but also be a prefix for the intermediate TAG names. So, not ignore them, just modify them.  But I can't decide if that's a hack or not.  Ignoring seems harsh to me since they clearly think they're important enough to tag.

**Comment by thaJeztah** [comment]
> I totally forgot about the fact that we can have more than one FROM in a Dockerfile.

The first time I saw that example Dockerfile I wanted to create a PR, because I thought multiple examples ended up in the same "code" block by accident.

We don't expect users to use advanced tooling such as `grep`, `awk`, and `sed`, [the instructions are simple](https://docs.docker.com/reference/builder/#from):

> Simply make a note of the last image ID output by the commit before each new FROM command

:+1:.

> Ignoring seems harsh to me since they clearly think they're important enough to tag.

It's a tough one; the user should be in control, not the Dockerfile, but agreed, what if I want to tag those individual steps, but using my own naming?

**Comment by icecrime** [comment]
This was already discussed in the (distant) past: #886. What's the reason for reconsidering?

**Comment by thaJeztah** [comment]
@icecrime I think this is the result of the linked issue still being opened and "dibs-ed" by this contributor. At this moment I think there's two decisions to be made, because they're a bit "linked";

- Do we want to keep support for multiple `FROM` instructions? (They're quite useless without being able to actually name/tag them)
- Do we want to support a `TAG` instruction in the Dockerfile?

**Comment by duglin** [comment]
I think https://github.com/docker/docker/issues/13026 is related to this because if we remove support for multiple `FROM`s then I think the need for this decreases.

**Comment by tiborvass** [comment]
Closing per https://github.com/docker/docker/issues/5603#issuecomment-115434824

**Pull request closed without merging**
