### PR TITLE
Fix broken links at plugins documentation

### PR DESCRIPTION
**Pull request by agonzalezro**

### CODE REVIEW

**Comment by calavera** [comment]
LGTM. Thank you!

**Comment by thaJeztah** [comment]
@calavera @agonzalezro unfortunately, this PR is not correct; these links *do* work when running `make build`. See here for more information; https://github.com/docker/docker/pull/15546#issuecomment-130873938

There's WIP to make these links work both on GitHub and in the documentation, but that change isn't in yet (and won't work with absolute `/docs/....` links)

**Comment by agonzalezro** [comment]
It makes sense. Sorry, I didn't realize.

Do you want me to create a revertion?

**Comment by thaJeztah** [comment]
@agonzalezro that would be great! Sorry for being just too late to notice

**Pull request merged**
