### PR TITLE
Post 1.4.1 docs update 2a

### PR DESCRIPTION
**Pull request by SvenDowideit**
Bring in some more spelling fixes

and add the registry-mirror article

### CODE REVIEW

**Comment by jfrazelle** [comment]
We are actually running the tests as a merge to the specific branch they are for, vs just checking out and hoping all goes well when we push the button... this may have something to do with that

**Comment by jfrazelle** [comment]
Also this is pre us upgrading to go1.4 so yeah that def has something to do with it
dont worry in the near future drone will actually build the dockerfile too

**Comment by SvenDowideit** [comment]
@fredlf @jamtur01 ready for merge

**Comment by SvenDowideit** [comment]
@jfrazelle yeah, I'm looking forward to when drone helps me more ;)

**Pull request merged**
