### PR TITLE
update D4M D4W advisory in swarm tutorial

### PR DESCRIPTION
**Pull request by sfsmithcha**
**\- What I did**
Updates advisory on getting started with swarm mode tutorial to clarify link to install for GA and to clarify single-node works for D4M/D4W.
**\- How I did it**
Edited index.md for the tutorial
**\- How to verify it**
Verify text is accurate/correct.

Signed-off-by: Charles Smith charles.smith@docker.com

### CODE REVIEW

**Comment by sfsmithcha** [comment]
ping @londoncalling @mgoelzer @friism

**Comment by mgoelzer** [comment]
lgtm/ianam

**Comment by thaJeztah** [comment]
LGTM, but needs a rebase :cry:

**Comment by sfsmithcha** [comment]
Rebased. (was expected b/c of https://github.com/docker/docker/pull/25425 )

**Pull request merged**
