### PR TITLE
[WIP] update swarmkit dependecies to support plugable secrets

### PR DESCRIPTION
**Pull request by liron-l**
Updating swarmkit dependencies.

Add more parameters for the secret driver API.

Signed-off-by: Liron Levin <liron@twistlock.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ehazlett** [comment]
This doesn't appear to be ready yet (just the vendor update).  Perhaps add a `WIP` to the title to let us know it's still in progress and remove it when ready.  Feel free to mention if you have questions along the way.  Thanks!

**Comment by liron-l** [comment]
Thanks @ehazlett, I've updated the title. 
The work for this feature is almost completed, but we do need to update the vendor dependencies in order to continue developing. Thanks!

**Comment by diogomonica** [comment]
@liron-l is this ready to go?

**Comment by liron-l** [comment]
Yes.

**Comment by aaronlehmann** [comment]
@liron-l: Needs a rebase.

**Comment by liron-l** [comment]
@aaronlehmann, @dmcgowan do you know why swarmkit is referenced from `https://github.com/dmcgowan/swarmkit.git`?

**Comment by aaronlehmann** [comment]
I think it's related to #34272

**Comment by liron-l** [comment]
Thanks @aaronlehmann so now we need to wait for docker/swarmkit#2334 before updating `swarmkit` reference.

**Comment by liron-l** [comment]
@diogomonica @aaronlehmann PTAL, update the swarmkit references to latest.

**Review by aaronlehmann — APPROVED** [review]

**Comment by mlaventure** [comment]
ping @diogomonica @ehazlett

**Comment by liron-l** [comment]
Thanks @mlaventure, which additional reviewers are required to approve this change?

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
