### PR TITLE
[23.0 backport] builder: define GetRemotes for the worker

### PR DESCRIPTION
**Pull request by thaJeztah**
- (partial) backport of https://github.com/moby/moby/pull/44920 (only the first commit)
- relates to https://github.com/moby/moby/pull/44936
- fixes https://github.com/moby/moby/issues/44918
- fixes https://github.com/docker/buildx/issues/1325 

The function signature has changed since v0.10.

(cherry picked from commit 335907d1878ffc33dccd45cc8121b1f10e900157)

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Kept this in draft for now, pending https://github.com/moby/moby/pull/44920#issuecomment-1420712165 (in case we want to fix the commit message)

**Comment by thaJeztah** [comment]
Failure on Windows-2022 https://github.com/moby/moby/actions/runs/4114098814/jobs/7101259444 in `TestTopWindowsCoreProcesses`. Looks like a flake, but posting here in case it'll happen again. 

```
=== Failed
=== FAIL: github.com/docker/docker/integration-cli TestDockerCLITopSuite/TestTopWindowsCoreProcesses (15.63s)
    check_test.go:359: assertion failed: error is not nil: Error response from daemon: Could not kill running container 24ce24434e62d6a16260e0160300c3e2c6aa6d7e4e080c37f61ae794665e7e83, cannot remove - tried to kill container, but did not receive an exit event: failed to remove 24ce24434e62d6a16260e0160300c3e2c6aa6d7e4e080c37f61ae794665e7e83
    --- FAIL: TestDockerCLITopSuite/TestTopWindowsCoreProcesses (15.63s)

```

**Comment by thaJeztah** [comment]
re-did the cherry-pick as https://github.com/moby/moby/pull/44920 was rebased

we may have to rebase this one after https://github.com/moby/moby/pull/44952 is merged

**Comment by thaJeztah** [comment]
Rebased; this should be ready for review ./cc @neersighted @tonistiigi

**Review by tonistiigi — APPROVED** [review]

**Review by neersighted — APPROVED** [review]

**Pull request merged**
