### PR TITLE
iptables: a rule with ip must be matched exactly in iptables-save

### PR DESCRIPTION
**Pull request by guoxiuyan**
A bridge named "docker0" will be created when docker daemon start for the first time, and docker0 will not be destroyed after docker daemon exit.

If docker0 is not exclusive to docker daemon, another application can change the IP of docker0, then the network in containers will not work after docker daemon restart.

Because the docker daemon will check if the rules about docker0 are already in iptables or iptables-save, but the IP in a rule will be repalced by "?", then the check of the rule in iptables-save will always returns true.

So the new IP of docker0 does not have rules in iptables or iptables-save, the network in cantainer will not work.

I handle this bug by using network address to replace IP in a rule, then checking if the rule contained in iptables-save.

Signed-off-by: Guo Xiuyan guoxiuyan@huawei.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
just curious why is another application changing the ip of docker0

**Comment by LK4D4** [comment]
Actually even docker with --bip can do this.

**Comment by guoxiuyan** [comment]
@jfrazelle docker0 is not protected by docker daemon.
In fact, docker0 can created by cmd brctl before docker deamon run or modified at any time.

**Comment by guoxiuyan** [comment]
@LK4D4 I have tried docker -b docker0, but it can not work.
You can find this bug as followed.
1.run docker -d, then we can get docker0 with IP 172.17.42.1/16
2.modify the IP, ip addr del 172.17.42.1/16 dev docker0
3.add another IP to docker0, ip addr add 173.17.42.1/16 dev docker0
4.restart docker daemon, docker -d
you can find the network can not work in container, and there are no chains in iptables-save of 173.17.42.1/16 on host in fact.

**Comment by jfrazelle** [comment]
no i understand that what I don't understand is why another application would want to change it

**Comment by guoxiuyan** [comment]
@jfrazelle If we need to construct a complex net to link some containers on docker0, so that we may have to reconfigure the IP of docker0. 
Maybe root user will change the IP of docker0 instead of other applications.

**Comment by guoxiuyan** [comment]
@LK4D4 docker --bip=173.17.42.1/16 can not work either.

**Comment by jfrazelle** [comment]
I do not think this is a fix we need. You can also `rm -rf /var/lib/docker` while docker is running and we aren't making a fix for that. You should not be changing the bridge that docker is using after we have created it.

**Comment by jfrazelle** [comment]
NOT LGTM

**Comment by guoxiuyan** [comment]
@jfrazelle May I just add some information to user to notify that the IP
 has been changed and iptables will not match the IP rules, in order to enhance the use of docker?

**Comment by jfrazelle** [comment]
wdyt @unclejack I am just worried things will be slower if it is checking this on _every_ rule

**Comment by LK4D4** [comment]
I'm not sure that this is relevant, but sequence:
```
docker -d
stop docker
ip link del docker0
docker -d --bip=<other bip>
```
will lead to containers which don't see outer network without any notifications, because `Exists` checking not exact matching.

**Comment by LK4D4** [comment]
Proper fix I think will be just drop this rules on daemon stop.

**Comment by guoxiuyan** [comment]
@jfrazelle regexp operation is alreay used in push.go, maybe one more check will not have the docker user sensed slow.

**Comment by guoxiuyan** [comment]
@LK4D4 I want to use this method at first, but the rules in iptales may be not created by docker, so that drop rules can confilt with other users.
@jfrazelle  If docker0 is exclusive to docker, we can fix it on daemon stop.

**Comment by WIZARD-CXY** [comment]
I met the same problem when using flannel to change the docker -bip option.After some debugging, I think it is the iptables Exists method's bug too .Looking forward to your correct version !

**Comment by guoxiuyan** [comment]
@jfrazelle Should I use @LK4D4 proposal to del iptable rules when daemon stops, or insist on my former method(or print info to notify user)?
Or just close this issue?
Sincerely wait for your support.

**Comment by jfrazelle** [comment]
I would say @lk4d4's solution seems like a good compromise and something we
should do.

**Comment by guoxiuyan** [comment]
@jfrazelle That sounds OK, I will try to fix it with @LK4D4 's method

**Comment by jfrazelle** [comment]
Hey @guoxiuyan I am going to go ahead and close this one but feel free to open a new one with the new implementation, that way also the comments will be clear and not super noisy when other maintainers come to review (fresh slate :) thanks

**Comment by guoxiuyan** [comment]
@jfrazelle OK, I will correct my pull request and then open another one.

**Pull request closed without merging**
