### PR TITLE
Libnetwork vendoring

### PR DESCRIPTION
**Pull request by fcrisciani**
closes https://github.com/moby/moby/pull/35415 

- removed support for Solaris
- networkdb fixed race on node management (relates to https://github.com/moby/moby/issues/35548)
- Addresses the endpoint_cnt issue exposed by https://github.com/moby/moby/issues/35310 

Signed-off-by: Flavio Crisciani <flavio.crisciani@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
There's this one as well; https://github.com/moby/moby/pull/35415 but there was a failure that I wasn't sure of if it was related; https://github.com/moby/moby/pull/35415#issuecomment-342554648

**Comment by thaJeztah** [comment]
Copying information from the other pull request;

brings in the following changes:

- https://github.com/docker/libnetwork#1975 bump docker/docker to master and unfork dependencies
- https://github.com/docker/libnetwork#2000 wait for iptables lock in support script
- https://github.com/docker/libnetwork#2002 Remove Solaris support
- https://github.com/docker/libnetwork#2004 endpoint_cnt store updates should not create an object (relates to https://github.com/moby/moby/issues/35310)
- https://github.com/docker/libnetwork#2007 Support override of binary name (relates to https://github.com/moby/moby/pull/34226)

These are the same changes as was merged in https://github.com/docker/docker-ce/pull/296 (for Docker CE 17.11) (Full diff; https://github.com/docker/libnetwork/compare/72fd7e5495eba86e28012e39b5ed63ef9ca9a97b...6bbcd1b4a59bee65e6648130ad8709a413d10537)

Additional changes in this PR:

https://github.com/docker/libnetwork/compare/6bbcd1b4a59bee65e6648130ad8709a413d10537...f7d21337cf1eb628ad54eecac0881fa23ec266df

- https://github.com/docker/libnetwork/pull/2013 NetworkDB node management race
- https://github.com/docker/libnetwork/pull/1957 Add test to confirm garbage collection (not relevant to this vendoring)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
