### PR TITLE
Remove "seccomp" build tag

### PR DESCRIPTION
**Pull request by tianon**
Similar to the (now removed) `apparmor` build tag, this build-time toggle existed for users who needed to build without the `libseccomp` library.  That's no longer necessary, and given the importance of seccomp to the overall default security profile of Docker containers, it makes sense that any binary built for Linux should support (and use by default) seccomp if the underlying host does.

(As discussed in https://github.com/moby/moby/pull/42486#discussion_r647737707 :smile:)

This does some changes in `vendor/github.com/moby/buildkit` so it's not 100% ready to merge as-is. :sweat_smile:

### CODE REVIEW

**Comment by cpuguy83** [comment]
As I recall buildkit also needs to drop the build tag.

**Comment by thaJeztah** [comment]
This may conflict with https://github.com/moby/moby/pull/42005

**Comment by thaJeztah** [comment]
> This may conflict with #42005

Looks like you're lucky; I tried rebasing this locally, and looks like it still applies cleanly 😅

**Comment by tianon** [comment]
Thanks to https://github.com/moby/buildkit/pull/2338 and a rebase, I think this is ready for review! :clinking_glasses:

**Review by thaJeztah — APPROVED** [review]
LGTM (if green)

Completely forgot about this one! Guess we can make some changes in our packaging as well after this is merged 👍

**Comment by thaJeztah** [comment]
Looks green(ish); some windows failures that are unrelated (gave it another kick)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker-ce-packaging/pull/693 to remove the obsolete build-tags from our build-scripts

**Pull request merged**
