### PR TITLE
Add support for swarm mode templating

### LINKED ISSUE #28022: document templating features in swarm mode
https://github.com/docker/docker/pull/27995 added templating features for swarm mode, but they were not documented yet.

The docs should be updated to document the templating, and include examples on how / when to use them

### PR DESCRIPTION
**Pull request by vdemeester**
Wire templating support of swarmkit for the engine, in order to be used through services 🐮 — #27995 updated swarmkit but did not *wire* it (and thus the package wasn't kept either).

- [x] Tests
- [ ] Documentations

Closes #28022

/cc @thaJeztah @stevvooe @aaronlehmann @icecrime 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
@AkihiroSuda doesn't need vendoring, it's already vendored (just wasn't used so the package was cleaned) — the vendor check is green :wink:

**Comment by AkihiroSuda** [comment]
oh, sorry 😅

**Comment by stevvooe** [comment]
Thanks for carrying this!

I suspect we will run into some validation problems when passing through template syntax. It might be good to have a few tests that create services that flex these pipelines end to end.

Specific areas in order of sensitivity:

- Mount source/target validated as path
- Hostname may have aggressive validation
- Env, although most just looks for an `=`

**Comment by vieux** [comment]
docker/swarmkit#1738 was merged

**Comment by vieux** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by thaJeztah** [comment]
@vieux @vdemeester looks like we missed this in the changelog

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/issues/28022 is tracking the documentation part, so removing docs/revisit

**Pull request merged**
