### PR TITLE
Return membership status on join without timeout

### PR DESCRIPTION
**Pull request by tonistiigi**
- Update swarmkit to 310f1119
- If manual acceptance is needed to join, user doesn't need to wait for the timeout.
- More helpful error/status messages.

@diogomonica @nathanleclaire

### CODE REVIEW

**Comment by nathanleclaire** [comment]
👍 On the new error messages -- didn't even know the membership status could be accessed using `docker info`.

**Comment by diogomonica** [comment]
LGTM

**Comment by vieux** [comment]
LGTM 👍

**Comment by icecrime** [comment]
LGTM (assuming green).

**Comment by justincormack** [comment]
Shouldn't the vendoring be done via `hack/vendor.sh`? Otherwise LGTM.

**Comment by icecrime** [comment]
@justincormack It is! WDYM?

**Comment by tiborvass** [comment]
@justincormack wdym? it's being done via hack/vendor.sh

**Comment by justincormack** [comment]
Sorry its late and I missed that... LGTM

**Pull request merged**
