### PR TITLE
Support --net=container:<NameOrID> support for windows. Fixes #30152

### LINKED ISSUE #30152: Support --net=container:<NameOrId> for Windows containers (Process Isolation only)
**Description**
Support for Windows containers to share network Endpoints

Enable --net=container:<NameOrId> for windows

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by madhanrm**
**- What I did**
Enabled --net=container option for windows
Populated the referred container name to the new container and pass it down to hcsshim

**- How I did it**
Support is already available in docker. Just enabled it for Windows.

**- How to verify it**
Verified the running the relevant cmdlets

**- Description for the changelog**
Support for Windows containers to share network Endpoints
Enable --net=container: for windows

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @jhowardmsft

**Comment by LK4D4** [comment]
Have no idea about this :( ping @jhowardmsft

**Comment by jhowardmsft** [comment]
@jmesser81 @msabansal

**Comment by madhanrm** [comment]
@jhowardmsft Can you take a look at this PR. Bwt, am not sure the reason for the vendor check failure. Can you let me know the fix for that is?

**Comment by msabansal** [comment]
@madhanrm For vendoring you need to update vendor.conf and then run the vndr tool at github.com/LK4D4/vndr

**Comment by madhanrm** [comment]
I'll open a new one, with vendoring changes

**Pull request closed without merging**
