### PR TITLE
Change tls to TLS

### PR DESCRIPTION
**Pull request by yuexiao-wang**
1. Change tls to TLS
2. Fix some typo for swarm

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I wonder this PR is too nitpicky.
Also, please consider squashing similar PRs #29573 if this fix is still needed

**Comment by yuexiao-wang** [comment]
@AkihiroSuda PTAL
It has been squashed from PRs #29573

**Comment by yuexiao-wang** [comment]
@AkihiroSuda PTAL
Thanks

**Comment by AkihiroSuda** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
