### PR TITLE
Use waitRun in TestDockerNetworkHostModeUngracefulDaemonRestart

### PR DESCRIPTION
**Pull request by mavenugo**
Fixes https://github.com/docker/docker/issues/19368

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by clnperez** [comment]
I'll try this out. I've played around with the existing waitRun (with no luck), and also inserting sleeps (as sanity-checks) but so far no dice.

**Comment by clnperez** [comment]
This failed in the same way my experiments with waitRun have been failing:

```
docker_cli_network_unix_test.go:1026:
c.Assert(err, checker.IsNil)
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc2097cbfe0)} ("exit status 1")  
```

**Comment by cpuguy83** [comment]
LGTM even it doesn't improve the flakiness.

**Comment by clnperez** [comment]
Well, it passed 4 times in a row, but then failed with
```
docker_cli_network_unix_test.go:1027: 
    c.Assert(err, checker.IsNil) 
... value *errors.errorString = &errors.errorString{s:"condition \"\"false\" == \"true
\"\" not true in time"} ("condition \"\"false\" == \"true\"\" not true in time") 
[d88919000] exiting daemon 
OOPS: 0 passed, 1 FAILED
--- FAIL: Test (26.97s) 
```

**Comment by mavenugo** [comment]
@clnperez I guess gccgo is way too slow for the existing waitRun timeout as well (which is 5 seconds).
@cpuguy83 WDYT ?

**Comment by mavenugo** [comment]
@clnperez do you see any improvement from your previous trails ?
Can you increase the timeout from 5 seconds to say 10 seconds and see if that improves ?

**Comment by cpuguy83** [comment]
It's fine to bump up the timeout assuming the timeout is non-blocking (ie, on success we don't have to wait the timeout period).

**Comment by mavenugo** [comment]
@cpuguy83 i agree. I will just bump up the timeout for this test alone to 10 seconds if that helps with the flakiness.

**Comment by clnperez** [comment]
Yes an improvement, it was failing almost every time before, then 4/5 times with your patch and the 5s timeout. Increasing the timeout to 10s has passed all 10 of the 10 times I tried it.

**Comment by mavenugo** [comment]
Thanks. will increase the timeout for this case.

**Comment by icecrime** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by clnperez** [comment]
Awesome, @mavenugo! Thanks!

**Pull request merged**
