### PR TITLE
Bump API version to 1.39

### PR DESCRIPTION
**Pull request by dhiltgen**
Signed-off-by: Daniel Hiltgen <daniel.hiltgen@docker.com>

### CODE REVIEW

**Comment by cpuguy83** [comment]
What's FC?

**Comment by dhiltgen** [comment]
> What's FC?

Feature Complete for the upcoming release.

References:
* https://blog.docker.com/2018/07/extending-support-cycle-docker-community-edition/
* https://docs.docker.com/install/#pre-releases

**Comment by tiborvass** [comment]
For the record, the only change I found so far was #37156

**Review by tiborvass — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Review by boaz0 — COMMENTED** [review]
LGTM :robot:

**Review by andrewhsu — APPROVED** [review]
LGTM

**Pull request merged**
