### PR TITLE
Bash scripts; use double brackets, fix bare variables, add quotes

### PR DESCRIPTION
**Pull request by thaJeztah**
These scripts explicitly use Bash, so we should be able to use `[[` instead of `[` (which seems to be recommended).

Also added curly brackets to some bare variables, and quoted some paths.

This makes my IDE a bit more silent :-)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tianon @albers PTAL; happy to close if these changes don't make sense

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by tianon** [comment]
Ah, wish I'd dug in and seen this sooner. :disappointed: (Sorry!)

See https://serverfault.com/a/705144 for a great (very extensive) post which outlines some of my own thoughts on this topic.

**Comment by thaJeztah** [comment]
@tianon want me to revert the double-bracket changes? I know we tried to avoid Bashisms in the past, but I noticed these files used `/bin/bash`

**Pull request merged**
