### PR TITLE
Convert "vendor.conf" to "go.mod" with minimal changes [DNM]

### PR DESCRIPTION
**Pull request by tianon**
I created this with a script that I wrote that parsed `vendor.conf` and generated a series of `go mod download` + `go list -m` (to scrape the appropriate "Go version" string for each commit hash) + `go mod edit -replace=...`+`go mod edit -require=...` (since `go mod init` will convert `vendor.conf`, but does not support `replace`...).

Running `go mod tidy` on the result gets very sad because it wants to make sure not just our dep tree but the dep tree of our dep tree's _tests_ are also good, so you know, it's an absolute mess.

However, with this I _was_ able to successfully `go build -o dockerd -tags 'apparmor seccomp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper' ./cmd/dockerd` in a stock `golang:latest` container without any `GOPATH` footwork, so it's close enough that I figured it was worth opening as a PR and letting CI tell me horrible things about it. :smile:

Some concrete adjustments I had to make include:

- ~~updating `google.golang.org/grpc` v1.33.2 to v1.37.1~~
- updating `github.com/hashicorp/consul` v0.5.2 to `github.com/hashicorp/consul/api` v1.1.0

Relates to #41504 (and likely others)

### CODE REVIEW

**Comment by tianon** [comment]
```console
$ go mod tidy
go: finding module for package google.golang.org/grpc/naming
go: finding module for package camlistore.org/pkg/throttle
github.com/docker/docker/libnetwork imports
	github.com/docker/libkv/store/zookeeper imports
	github.com/samuel/go-zookeeper/zk tested by
	github.com/samuel/go-zookeeper/zk.test imports
	camlistore.org/pkg/throttle: module camlistore.org@latest found (v0.0.0-20171230002226-a5a65f0d8b22), but does not contain package camlistore.org/pkg/throttle
github.com/docker/docker/libnetwork imports
	github.com/docker/libkv/store/etcd imports
	github.com/coreos/etcd/client tested by
	github.com/coreos/etcd/client.test imports
	github.com/coreos/etcd/integration imports
	github.com/coreos/etcd/proxy/grpcproxy imports
	google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.38.0), but does not contain package google.golang.org/grpc/naming
```

**Comment by thaJeztah** [comment]
This is also removing the vendor directory?

I think the problem is not so much if _we_ are able to (somehow) use `go.mod` to vendor our dependencies, but the problem will be that others can no longer use this repository as a dependency, as go modules will refuse to use this module, unless we rewrite our import paths to be `github.com/docker/docker/v20` or `github.com/docker/docker/v21`, and then it will refuse to use our tags, because `v21.07` doesn't exist (not SemVer) so then it will version it as `docker 1.13` (with Sirupsen/logrus)

**Comment by thaJeztah** [comment]
As to the libnetwork dependencies; I'm hoping to get rid of a whole bunch of pre-historic dependencies if I get https://github.com/moby/moby/pull/42247 to work (need to re-do it, now that libnetwork is in this repository)

**Comment by tianon** [comment]
Yeah, I figured removing the `vendor/` directory was the easiest way to make sure the CI actually ended up using my `go.mod` instead of falling back to something in `vendor/` :sweat_smile:
(I'm in the middle of rebasing to fix that conflict too so it can test again.)

Ultimately, I think ditching `vendor/` is probably a "good" idea (especially with `go.mod`+`go.sum` giving us similar benefit to hard-coded `vendor/`), but I don't think we should rush into any of this.  I don't expect us to merge this now (or even any time soon), but I think it's a useful exercise.

As for the versioning issues, we already have those today, right?  Folks trying to import `github.com/docker/docker` have been having a bad time for years, and Go modules made it worse, but I don't think us having an explicit `go.mod` makes that even worse, does it?  (Arguably should be slightly better since there'll then be a known "good" set of dependencies they can inherit from/share.)

**Comment by thaJeztah** [comment]
If we _do_ want to use `go mod` just for for vendoring, we could rename the `go.mod` to `no.mod` (e.g.) and `go mod vendor -modfile=no.mod`. That is: hoping that in that case, `go` doesn't see the repository as being a go module.

**Comment by thaJeztah** [comment]
> As for the versioning issues, we already have those today, right? Folks trying to import github.com/docker/docker have been having a bad time for years, and Go modules made it worse,

Currently they're still able to use it (go modules adds the `+incompatible`, but still allows using it). The moment it finds a `go.mod`, it will refuse to use our code as a dependency; produce an error, and that's it.

**Comment by thaJeztah** [comment]
Let me close this one in favour of https://github.com/moby/moby/pull/43075 / https://github.com/moby/moby/pull/43101, which we will use as an intermediate "stepping stone" towards a full migration to go modules ❤️

**Pull request closed without merging**
