### PR TITLE
Revendor hcsshim

### LINKED ISSUE #22855: Cannot delete files from wwwroot with Dockerfile
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 29
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.423 GiB
Name: WIN-CCH6NOM9R5L
ID: REUT:4Z3Z:JFDG:ENK6:2LSA:MBU2:TUSB:KCJO:UN27:3HDO:HF5G:YVDL
Docker Root Dir: C:\ProgramData\docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Windows Server Core 2016 TP5 in local Hyper-V VM

**Steps to reproduce the issue:**
1. Build this dockerfile
```
FROM microsoft/iis
RUN powershell remove-item c:\inetpub\wwwroot\iisstart.*
```

**Describe the results you received:**
If I run a container with this image, the `iisstart.*` files are still inside `c:\inetpub\wwwroot`

**Describe the results you expected:**
`iisstart.*` files should be removed from `c:\inetpub\wwwroot`

**Additional information you deem important (e.g. issue happens only occasionally):**
StackOverflow question: http://stackoverflow.com/q/37336884/3199781

cc: @jhowardmsft

### LINKED ISSUE #23048: Deleted file appears on commited image
We're experiencing an issue that file once created and commited  in one image, later deleted and commited in second image, still exists in second image. 

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 2 GiB
Name: windows
ID: BSMS:IGWX:IYAC:EE3R:ZDZB:QVOI:RZPG:5FDR:AOOL:ZYYT:DJIY:QND2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker server is Server 2016 TP5. Docker client is Ubuntu 14.04. Both running in VirtualBox

**Steps to reproduce the issue:**
1. Start container from base image `docker run -it windowsservercore cmd` and create `C:\file1.txt` inside
2. Commit container as image1 `docker commit ae141c8f9f3a image1`
3. Start container from image1 and check that test file is there - yes it is.
```
docker run -it image1 cmd

Microsoft Windows [Version 10.0.14300]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is 3E22-E3DC

 Directory of C:\

05/26/2016  11:56 AM                14 file1.txt
03/25/2016  05:28 AM    <DIR>          inetpub
03/25/2016  04:22 AM    <DIR>          PerfLogs
05/26/2016  11:59 AM    <DIR>          Program Files
03/25/2016  04:22 AM    <DIR>          Program Files (x86)
05/26/2016  11:59 AM    <DIR>          Users
05/26/2016  11:59 AM    <DIR>          Windows
               1 File(s)             14 bytes
               6 Dir(s)  21,236,789,248 bytes free
```
4. Delete test file `del file1.txt` and commit container as image2 `docker commit 4defd2a255a6 image2`
5. Start container from image2 and check that test file is not there - but it still exists.
```
docker  run -it image2 cmd

Microsoft Windows [Version 10.0.14300]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is 3E22-E3DC

 Directory of C:\

05/26/2016  11:56 AM                14 file1.txt
03/25/2016  05:28 AM    <DIR>          inetpub
03/25/2016  04:22 AM    <DIR>          PerfLogs
05/26/2016  12:00 PM    <DIR>          Program Files
03/25/2016  04:22 AM    <DIR>          Program Files (x86)
05/26/2016  12:00 PM    <DIR>          Users
05/26/2016  12:00 PM    <DIR>          Windows
               1 File(s)             14 bytes
               6 Dir(s)  21,236,785,152 bytes free
```

**Describe the results you received:**

Test file `C:\file1.txt` exists

**Describe the results you expected:**

Test file `C:\file1.txt` not exists

### PR DESCRIPTION
**Pull request by darstahl**
Revendor hcsshim.

Fixes https://github.com/docker/docker/issues/23048
Fixes https://github.com/docker/docker/issues/22855

Added a CI test to verify that deleted files are deleted in a committed layer.

**\- A picture of a cute animal (not mandatory but encouraged)**

Sealion!

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by darrenstahlmsft** [comment]
CI doesn't seem to be running on this PR... Anyone have any ideas?

**Comment by thaJeztah** [comment]
Yeah, we have issues with CI :cry:

LGTM (once CI is running again, and hopefully green)

**Comment by LK4D4** [comment]
@darrenstahlmsft both windows CI failed with weird errors :/

**Comment by darrenstahlmsft** [comment]
I'm unable to repro locally. I'll restart the CI in case it is transient.

**Comment by LK4D4** [comment]
@darrenstahlmsft one more error :)

**Comment by darrenstahlmsft** [comment]
@LK4D4 CI is green now. PTAL :)

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by darrenstahlmsft** [comment]
Thanks!

**Pull request merged**
