### PR TITLE
Fix test case

### PR DESCRIPTION
**Pull request by WeiZhang555**
"TestRestartContainerwithRestartPolicy" contains some codes that could be
flaky, it's supposed to be fixed in #22256.

This commit removes unnecessary code, make the test case cleaner.

I'm not 100% sure, just an attempt. This test case is introduced in #21854, if Janky isn't green on this, I'll close it for now.

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by WeiZhang555** [comment]
All passed, `experimental` failed on unrelated error.  It seems really fixed. Let me re-trigger the integration-test again to double check.

**Comment by WeiZhang555** [comment]
Second integration test result is still very good:
image

Windows TP5 failed on flaky test, which is caused by slow start speed of Windows container:
```
07:22:51 ----------------------------------------------------------------------
07:22:51 FAIL: docker_cli_restart_test.go:222: DockerSuite.TestRestartContainerwithRestartPolicy
07:22:51 
07:22:51 docker_cli_restart_test.go:229:
07:22:51     c.Assert(err, checker.IsNil)
07:22:51 ... value *errors.errorString = &errors.errorString{s:"condition \"\"false true\" == \"false false\"\" not true in time"} ("condition \"\"false true\" == \"false false\"\" not true in time")
07:22:51 
07:23:11 
07:23:11 ----------------------------------------------------------------------
```

I'll bump up waiting timeout for Windows.

**Comment by WeiZhang555** [comment]
Flaky windows test is fixed. Let me see how is the third test...

**Comment by WeiZhang555** [comment]
I think the result is good :smile:

**Comment by thaJeztah** [comment]
Weird; build timed out after 200 minutes, but the test kept running for another hour? https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP5/1104/console

```
12:08:18 PASS: docker_cli_rm_test.go:38: DockerSuite.TestRmContainerRunning	4.684s
12:08:25 PASS: docker_cli_rm_test.go:11: DockerSuite.TestRmContainerWithRemovedVolume	6.383s
14:51:05 Build timed out (after 200 minutes). Marking the build as failed.
14:51:06 Build was aborted
14:51:06 [PostBuildScript] - Execution post build scripts.
14:51:06 [docker] $ sh -xe C:\Users\jenkins\hudson939509379339529658.sh
16:08:25 --- FAIL: Test (16346.37s)
16:08:25 panic: test timed out after 4h0m0s [recovered]
16:08:25 	panic: test timed out after 4h0m0s
```


But, `TestRestartContainerwithRestartPolicy` succeeded indeed 👍 

    12:06:38 PASS: docker_cli_restart_test.go:222: DockerSuite.TestRestartContainerwithRestartPolicy	65.871s

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
