### PR TITLE
raise an error if rmi -f with multiple tags and running container

### PR DESCRIPTION
**Pull request by mountkin**
Fixes https://github.com/docker/docker/issues/14116

Signed-off-by: Shijiang Wei mountkin@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
hmmm...
This is like the 30th time this has changed... and I believe the last change is the one that added the len(repoAndtags) bit...

**Comment by mountkin** [comment]
hahahaha...
It's funny that why there are so many people like to change this line :laughing:

**Comment by cpuguy83** [comment]
I'm really not sure what this line is doing without re-reading again... but it seems like daemon.canDeleteImage should return an error if a container is using it, no matter what.

**Comment by cpuguy83** [comment]
Also, I was totally hit by this issue today.
I had a shell into a container, in a separate terminal I did an `rmi -f` on dangling images, and the image for the container I was in was removed.

**Comment by crosbymichael** [comment]
I think the change makes sense, we absolutely do not want to have dangling images so we should either kill all the containers or return an error saying something is going to happen that you probably don't expect.

**Comment by mountkin** [comment]
@cpuguy83  The line was first added in https://github.com/docker/docker/pull/7963 and modified in https://github.com/docker/docker/pull/13596
According the code in the master, the `daemon.canDeleteImage` is called only when the image has 1 or 0 tags or deleting by image ID.
Since you were deleting dangling images, `len(repos)` should be 0, so the `daemon.canDeleteImage` should be called and the image of the running container should not be removed. 
But in fact you image was removed, perhaps the image of some of your containers had been force removed, so the `daemon.canDeleteImage` returned nil at this line https://github.com/docker/docker/blob/master/daemon/image_delete.go#L158? I think it shouldn't return nil when the image of a container is not found, instead it should continue the loop and check whether there are other containers using the image. It's another bug, maybe.

**Comment by LK4D4** [comment]
LGTM
ping @docker/core-maintainers

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
thanks for the fix and the test :)

**Pull request merged**
