### PR TITLE
Vendor engine-api v0.3.2 in release 1.11.

### PR DESCRIPTION
**Pull request by calavera**
This change is going to be merged in the bump_v1.11.0 branch directly.

/cc @tiborvass

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
I cherry-picked those two extra commits to make CI build on bump_v1.11.0 again.

**Comment by tiborvass** [comment]
Thanks LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
