### PR TITLE
[do not merge] update to go1.20.6 and add client host fix

### PR DESCRIPTION
**Pull request by thaJeztah**
Just for testing the combination of these two PRs:

- https://github.com/moby/moby/pull/45942
- https://github.com/moby/moby/pull/45941

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like we need more code updated;

```
[2023-07-12T12:54:46.838Z] === Failed
[2023-07-12T12:54:46.838Z] === FAIL: pkg/authorization TestAuthZRequestPluginError (15.01s)
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:30Z" level=warning msg="Unable to connect to plugin: //tmp/authz4264769183/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz4264769183%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 1s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:31Z" level=warning msg="Unable to connect to plugin: //tmp/authz4264769183/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz4264769183%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 2s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:33Z" level=warning msg="Unable to connect to plugin: //tmp/authz4264769183/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz4264769183%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 4s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:37Z" level=warning msg="Unable to connect to plugin: //tmp/authz4264769183/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz4264769183%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 8s"
[2023-07-12T12:54:46.838Z]     authz_unix_test.go:50: Failed to authorize request Post "http://%2F%2Ftmp%2Fauthz4264769183%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq": http: invalid Host header
[2023-07-12T12:54:46.838Z] 
[2023-07-12T12:54:46.838Z] === FAIL: pkg/authorization TestAuthZRequestPlugin (15.01s)
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:45Z" level=warning msg="Unable to connect to plugin: //tmp/authz2422457390/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz2422457390%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 1s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:46Z" level=warning msg="Unable to connect to plugin: //tmp/authz2422457390/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz2422457390%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 2s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:48Z" level=warning msg="Unable to connect to plugin: //tmp/authz2422457390/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz2422457390%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 4s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:53:52Z" level=warning msg="Unable to connect to plugin: //tmp/authz2422457390/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz2422457390%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 8s"
[2023-07-12T12:54:46.838Z]     authz_unix_test.go:82: Failed to authorize request Post "http://%2F%2Ftmp%2Fauthz2422457390%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq": http: invalid Host header
[2023-07-12T12:54:46.838Z] 
[2023-07-12T12:54:46.838Z] === FAIL: pkg/authorization TestAuthZResponsePlugin (15.01s)
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:00Z" level=warning msg="Unable to connect to plugin: //tmp/authz3990016376/authz-test-plugin.sock/AuthZPlugin.AuthZRes: Post \"http://%2F%2Ftmp%2Fauthz3990016376%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZRes\": http: invalid Host header, retrying in 1s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:01Z" level=warning msg="Unable to connect to plugin: //tmp/authz3990016376/authz-test-plugin.sock/AuthZPlugin.AuthZRes: Post \"http://%2F%2Ftmp%2Fauthz3990016376%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZRes\": http: invalid Host header, retrying in 2s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:03Z" level=warning msg="Unable to connect to plugin: //tmp/authz3990016376/authz-test-plugin.sock/AuthZPlugin.AuthZRes: Post \"http://%2F%2Ftmp%2Fauthz3990016376%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZRes\": http: invalid Host header, retrying in 4s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:07Z" level=warning msg="Unable to connect to plugin: //tmp/authz3990016376/authz-test-plugin.sock/AuthZPlugin.AuthZRes: Post \"http://%2F%2Ftmp%2Fauthz3990016376%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZRes\": http: invalid Host header, retrying in 8s"
[2023-07-12T12:54:46.838Z]     authz_unix_test.go:112: Failed to authorize request Post "http://%2F%2Ftmp%2Fauthz3990016376%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZRes": http: invalid Host header
[2023-07-12T12:54:46.838Z] 
[2023-07-12T12:54:46.838Z] === FAIL: pkg/authorization TestMiddlewareWrapHandler/Positive_Test_Case_: (15.01s)
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:30Z" level=warning msg="Unable to connect to plugin: //tmp/authz1534243050/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz1534243050%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 1s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:31Z" level=warning msg="Unable to connect to plugin: //tmp/authz1534243050/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz1534243050%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 2s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:33Z" level=warning msg="Unable to connect to plugin: //tmp/authz1534243050/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz1534243050%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 4s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:37Z" level=warning msg="Unable to connect to plugin: //tmp/authz1534243050/authz-test-plugin.sock/AuthZPlugin.AuthZReq: Post \"http://%2F%2Ftmp%2Fauthz1534243050%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header, retrying in 8s"
[2023-07-12T12:54:46.838Z] time="2023-07-12T12:54:45Z" level=error msg="AuthZRequest for GET www.example.com/auth returned error: plugin plugin failed with error: Post \"http://%2F%2Ftmp%2Fauthz1534243050%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq\": http: invalid Host header"
[2023-07-12T12:54:46.838Z]     middleware_unix_test.go:60: assertion failed: error is not nil: plugin plugin failed with error: Post "http://%2F%2Ftmp%2Fauthz1534243050%2Fauthz-test-plugin.sock/AuthZPlugin.AuthZReq": http: invalid Host header
[2023-07-12T12:54:46.838Z] 
[2023-07-12T12:54:46.838Z] === FAIL: pkg/authorization TestMiddlewareWrapHandler (30.02s)
```

**Comment by thaJeztah** [comment]
BuildKit tests still failing on this one, but probably because BuildKit v0.11 uses docker engine v23.0.0-rc.1; https://github.com/moby/buildkit/blob/0a0807ebcc8573d6da9be70728c2f75408a6dad2/go.mod#L30C18-L30C52

```
github.com/docker/docker v23.0.0-rc.1+incompatible
```

So this fix would have to be backported to v23, and buildkit would have to update the dependency.. fun fun

**Comment by thaJeztah** [comment]
Alright; CI finished, and looks like everything is green except for BuildKit CI

Screenshot 2023-07-12 at 19 01 50


Once https://github.com/moby/moby/pull/45947 is merged, I guess I could temporarily pin BuildKit CI to v1.20.5, but it looks like that PR still has some failures (not sure what)

**Comment by crazy-max** [comment]
Can you also bump go version in buildkit workflow? https://github.com/moby/moby/blob/d93d3e2d75a7071f8fd4c3543190c31cc596a0a4/.github/workflows/buildkit.yml#L16

**Comment by thaJeztah** [comment]
That will probably make it fail again until BuildKit is fixed with this fix?

**Comment by thaJeztah** [comment]
This one was just for testing; closing

**Pull request closed without merging**
