### PR TITLE
Update builder.md

### PR DESCRIPTION
**Pull request by scjane**
Fix an invalid link.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ripcurld0** [comment]
@scjane can you please do `git commit -s --amend` and then `git push -f origin patch-3`?

**Review by boaz0 — APPROVED** [review]
LGTM

**Comment by duglin** [comment]
LGTM once CLA is signed

**Review by tonistiigi — APPROVED** [review]
LGTM

**Comment by scjane** [comment]
Sorry, I failed to amend the commit because my SourceTree client went wrong. I tried to fix it but nothing took effect and git downloading is not available due to network limit.

**Comment by tonistiigi** [comment]
@scjane I fixed this up for you. Please confirm that everything is correct and we'll get this merged.

**Comment by scjane** [comment]
@tonistiigi Thanks a lot. I've checked it.

**Comment by tonistiigi** [comment]
Ah, it completely went unnoticed that this was against `17.03.x`.

@vieux Do you want me to restore the branch?
@scjane These changes should go in `master` branch first.

**Pull request merged**
