### PR TITLE
client/request, client/error: Resolve conflict between errors and github.com/pkg/errors

### PR DESCRIPTION
**Pull request by phuongtnd1994**
errors.As and errors.Is is as part of errors package,
the original code is using github.com/pkg/errors which let to error when using in other project as SDK

Signed-off-by: Phuong TND <phuongtnd.neu@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
> which let to error when using in other project as SDK

can you describe the problem you had?


Also; looks like you opened this PR from a branch based on the 27.x branch, not based on master, which causes all the extra commits to be included.

**Comment by phuongtnd1994** [comment]
> > which let to error when using in other project as SDK
> 
> can you describe the problem you had?
> 
> Also; looks like you opened this PR from a branch based on the 27.x branch, not based on master, which causes all the extra commits to be included.

Hi,

I use github.com/docker/docker package with go 1.23 to learn to write tiny orchestrator program 
When build it i face the error:

# github.com/docker/docker/client
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/errors.go:28:16: undefined: errors.As
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/request.go:127:14: undefined: errors.Is
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/request.go:129:14: undefined: errors.Is
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/request.go:153:13: undefined: errors.Is

I found that in errors.go and request.go we use github.com/pkg/errors
but errors.As an is errors.Is are in errors package (cs.opensource.google/go/go)

So I have to change the code to overcome it

Since this is my first time committing to an open-source project, if there are any mistakes, please guide me. Thank you.

**Comment by thaJeztah** [comment]
Both "errors.Is" and "errors.As" are implemented in the pkg/errors module, so wondering why you'd get that error;

https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/go113.go#L16
https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/go113.go#L31

**Comment by phuongtnd1994** [comment]
> Both "errors.Is" and "errors.As" are implemented in the pkg/errors module, so wondering why you'd get that error;
> 
> https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/go113.go#L16 https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/go113.go#L31

This is because in :

https://github.com/moby/moby/blob/master/client/errors.go
and 
https://github.com/moby/moby/blob/master/client/request.go

are using 
import(
...
"github.com/pkg/errors"
)

https://pkg.go.dev/github.com/pkg/errors@v0.8.1#pkg-functions

doesn't have .Is and .As

**Comment by phuongtnd1994** [comment]
> Both "errors.Is" and "errors.As" are implemented in the pkg/errors module, so wondering why you'd get that error;
> 
> https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/go113.go#L16 https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/go113.go#L31

I got it

By using https://pkg.go.dev/github.com/pkg/errors@v0.9.1#pkg-functions

All needed functions are available

Sorry for that, I dont know why default for this docker library dependencies is 0.8.1

Thank you and have a nice day!

**Comment by thaJeztah** [comment]
Ah, yes, it won't work with an old version of that dependency. Let me close this PR

**Pull request closed without merging**
