### PR TITLE
Update engine api again for CopyToContainer and versions

### PR DESCRIPTION
**Pull request by vdemeester**
Updating `engine-api` to `a2999dbd3471ffe167f2aec7dccb9fa9b016dcbc` 🐼. This brings the following :
- Update the `CopyToContainer` signature
- Usage of `types/versions` package instead of `pkg/version`
- Removing `pkg/version` (in a separation commit so easy to revert if we don't want to remove it)

🐸

### CODE REVIEW

**Comment by thaJeztah** [comment]
Janky is failing; https://jenkins.dockerproject.org/job/Docker-PRs/26580/console

```
14:41:16 + go test -check.v -check.timeout=5m -test.timeout=360m github.com/docker/docker/integration-cli
14:41:43 # github.com/docker/docker/integration-cli
14:41:43 ./docker_api_test.go:52: "github.com/docker/docker/api".DefaultVersion.String undefined (type string has no field or method String)
14:41:43 ./docker_api_test.go:67: "github.com/docker/docker/api".MinVersion.String undefined (type string has no field or method String)
14:41:43 ---> Making bundle: .integration-daemon-stop (in bundles/1.12.0-dev/test-integration-cli)
```

**Comment by vdemeester** [comment]
@thaJeztah hum.. missed some :sweat:

**Comment by calavera** [comment]
LGTM

**Comment by jhowardmsft** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
