### PR TITLE
Add test for net=container and links

### LINKED ISSUE #9340: --link should be disallowed with --net=container
I am trying to understand and use the ``--net=container`` feature. When I use a command like this:
```
docker run -d --restart=no --cpu-shares=512 --link db:db -p 443 --net=container:other-web-app -v /etc/someVolume  --name=test-net-container base-image
```
I get this error:
```
2014/11/25 21:51:43 Error response from daemon: Cannot start container 1e02f12a2fdceb2f057f0cd58cf29ffe45790dc8ecae7be88456f79dccc58c7e: parent IP '' is invalid
```

I have not been able to find where this error is coming from (doesn't seem docker/libcontainer code), however it is my guess that you cannot link to a container when using ``--net=container`` mode. I got there by successfully running the same command without the ``--link`` option :
```
docker run -d --restart=no --cpu-shares=512 -p 443 --net=container:other-web-app -v /etc/someVolume  --name=test-net-container base-image
```

If I am not mistaken, shouldn't the ``--link`` option be disallowed (or at least a more explanatory error message given)?

### PR DESCRIPTION
**Pull request by willhf**
closes #9340
In writing a test for this we discovered that the check was wrong, hence the prefix change.

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by duglin** [comment]
LGTM once janky is happy

**Comment by duglin** [comment]
Do we need to modify the code at:
https://github.com/willhf/docker/blob/9340_test/runconfig/parse.go#L136
https://github.com/willhf/docker/blob/9340_test/runconfig/parse.go#L449

**Comment by estesp** [comment]
we should consider the merged #11369 and the proposed #11516 before taking on a test for something we may decide is a supported config now

**Comment by icecrime** [comment]
@willhf Can you please update your PR addressing @duglin's comment? Thanks!

**Comment by willhf** [comment]
@icecrime done!
Sorry for the delay.

**Comment by icecrime** [comment]
@estesp True, but until we figure this out, don't you think that's a valid patch?

I'm thinking LGTM for now.

**Comment by estesp** [comment]
@icecrime yes, actually, let's merge this as the other work isn't really complete, and it is correct that even with #11369, it is still correct that **both** flags together do not work (see the @cpuguy83 comment here: https://github.com/docker/docker/issues/9340#issuecomment-85784502)

Given that, I'm good with merging this now and then understanding how we appropriately finish out the updated capability that you can link to another container started with `--net=container:something`.

LGTM

**Comment by icecrime** [comment]
No docs needs as far as I can tell.

**Pull request merged**
