### PR TITLE
Add `ARG` instruction syntax for vim

### PR DESCRIPTION
**Pull request by zchee**
Add `ARG` instruction syntax.

`ARG` also `--build-arg` has been released Docker version 1.9.
https://github.com/docker/docker/releases/tag/v1.9.0

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐶

**Comment by zchee** [comment]
@vdemeester :cat: :tada:

**Comment by coolljt0725** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
@thaJeztah I've added this to the milestone, pls feel free to remove it if it's not desired

**Comment by thaJeztah** [comment]
@runcom should be fine, nice addition, so :+1:

**Comment by tianon** [comment]
Niiiice :smile:

**Comment by zchee** [comment]
@all
Thanks :)

**Pull request merged**
