### PR TITLE
Use formatter in docker diff

### PR DESCRIPTION
**Pull request by boaz0**
**- What I did**
Use formatter.Context to print changes in the diff command
related to #30431

**- How I did it**
* Create cli/command/formatter/diff.go
* Add unit tests to cli/command/formatter/diff_test.go
* Update integration-cli tests

**- How to verify it**
```sh
$ TESTFLAGS='-check.f DockerSuite.TestDiff*' hack/make.sh test-integration-cli
$ TESTDIRS='cli/command/formatter/' TESTFLAGS='-test.run ^TestDiff*' hack/make.sh test-unit
```

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
This can break compatibility due to the newly added table header.
Can we remove the table header by default?

**Comment by ripcurld0** [comment]
☑️ tests failed not due to the changes.

**Comment by mlaventure** [comment]
@ripcurld0 sorry, I mistakenly pressed the `update branch` button, could you rebase your local copy and force push?

**Comment by ripcurld0** [comment]
@mlaventure no problem. Let me know if I forgot anything or did it wrongly. :smile:

**Review by mlaventure — APPROVED** [review]
LGTM

ping @AkihiroSuda

**Comment by AkihiroSuda** [comment]
LGTM as "refactoring", but why not implement `docker diff --format`?

**Comment by ripcurld0** [comment]
@AkihiroSuda there are only two columns right now thus I am not sure if it's worth it.

**Review by vdemeester — APPROVED** [review]
LGTM 👼

**Comment by mlaventure** [comment]
Windows failure is a flaky test, merging.

Thanks for your patience and contribution @ripcurld0 !

**Comment by ripcurld0** [comment]
@mlaventure @AkihiroSuda  @vdemeester thanks a lot 🌷

**Pull request merged**
