### PR TITLE
Move layer mount refcounts to mountedLayer

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Revert e91de9f and add fix to commit 563d071 by properly using the newly added mounted() call.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Experimental got a timeout on https://jenkins.dockerproject.org/job/Docker-PRs-experimental/16884/console

```
21:57:38 PASS: docker_api_stats_test.go:219: DockerSuite.TestApiStatsContainerNotFound	0.001s
22:02:38 --- FAIL: Test (310.68s)
22:02:38 panic: test timed out after 5m0s [recovered]
22:02:38 	panic: test timed out after 5m0s
```

**Comment by anusha-ragunathan** [comment]
Known issue. Will be fixed by https://github.com/docker/docker/issues/21408

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
Ran the test suites locally on aufs and overlay.
LGTM

**Comment by cpuguy83** [comment]
gccgo is stuck on  #21408, merging

**Pull request merged**
