### PR TITLE
Split and remove pkg/stringutils

### PR DESCRIPTION
**Pull request by ChiuWang**
Signed-off-by: Chao Wang <wangchao.fnst@cn.fujitsu.com>

**- What I did**
Split the package first, see tasklist at [#35313](https://github.com/moby/moby/pull/35313) and remove it safely now.
**- How I did it**
According to @thaJeztah  's suggestion at [#35034(closed)](https://github.com/moby/moby/pull/35034#pullrequestreview-68582683)

And maybe it should be added to the tasklist at [Find a place for /pkg #32989](https://github.com/moby/moby/issues/32989) @dnephin

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

Thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!!

**Comment by thaJeztah** [comment]
oh, oops, saw you requested a review from @vdemeester as well; let me know if I merged too soon 😅

**Comment by charrywanganthony** [comment]
@thaJeztah @dnephin  You are welcome. If there's sth else that I 🐖  can help, plz @me. 😈

**Pull request merged**
