### PR TITLE
Enhanced port integration-cli tests

### PR DESCRIPTION
**Pull request by mavenugo**
THe port tests in integration-cli tests just for the port-mapping as
seen by Docker daemon. But it doesn't perform a more indepth testing by
checking for the exposed port on the host.

This change helps to fill that gap.

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Can we use `net.Dial` instead of `nc`?

Or maybe even better, use another container with `--net=host`, then you can even use `nc` as well... and it should work with Windows.

**Comment by mavenugo** [comment]
@cpuguy83 Good suggestion. Thanks. Updated the PR with your suggestion.

**Comment by cpuguy83** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
