### PR TITLE
The first letter should be small in error of remote.go

### PR DESCRIPTION
**Pull request by yu8833**
**\- What I did**
Fix the typo of the first letter in error
**\- How I did it**
Modify the first letter capital to lowercase

Signed-off-by: YuPengZTE yu.peng36@zte.com.cn

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
/cc @runcom @thaJeztah @dnephin

**Comment by dnephin** [comment]
Why should the first letter be lower case? Is the error message prefixed with other messages?

**Comment by thaJeztah** [comment]
@dnephin afaik, it's convention to lowercase error messages (can't find a reference right now)

**Comment by aaronlehmann** [comment]
Reference here: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

**Comment by LK4D4** [comment]
LGTM
win failure is unrelated

**Pull request merged**
