### PR TITLE
Add Linux Mint 17.x and 13 support to install.sh

### PR DESCRIPTION
**Pull request by edsfocci**
Works on my machine:

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"

Signed-off-by: Ed Solis edsfocci@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
Hi @edsfocci, 

Thanks for teh contribution but there is already some work for the support : here #15001 :wink:

**Comment by thaJeztah** [comment]
Thanks @edsfocci, I think there's another PR currently that is intended to solve this in a more generic way; https://github.com/docker/docker/pull/15001

Could you give  https://github.com/docker/docker/pull/15001 a test, and check if that works for you?

**Comment by thaJeztah** [comment]
(Sorry for the duplicate commenting, our comments just crossed.. LOL

**Comment by edsfocci** [comment]
Signed-off-by: Ed Solis <edsfocci@gmail.com>

**Comment by edsfocci** [comment]
I already installed; any uninstall script?

**Comment by thaJeztah** [comment]
Good one, I think `apt-get purge docker-engine` would do the removal, but won't remove the apt repo. Perhaps the blog post can give you some pointers there http://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by edsfocci** [comment]
Eh, it's alright I guess; if the other commit is more accepted (https://github.com/docker/docker/pull/15001), I'll let him have it.

I haven't specifically tested the file on my computer, but I've tested the lsb_release commands and the outputs seem to look good for my machine ("ubuntu" and "trusty" for upstream release). Also, according to their checklist, Linux Mint looks like it's tested as working (https://github.com/docker/docker/pull/15001#issuecomment-125721830).

**Comment by thaJeztah** [comment]
Thanks @edsfocci, and thanks so much for contributing, even if it didn't get merged, it's really appreciated :+1:

**Pull request closed without merging**
