### PR TITLE
Interpolate over multiple ENV arguments when one includes another

### PR DESCRIPTION
**Pull request by pritambaral**
As of Docker v1.4.1, for an entry in a Dockerfile like:

```
ENV FOO=42 BAR=$FOO:42
```

the `$FOO` in `BAR` does not get replaced with `42` when the variables are interpolated

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by pritambaral** [comment]
Done.

**Comment by SvenDowideit** [comment]
wow, the docs don't mention that this doesn't work atm :/

can you please add an example of this working to the `builder.md` and `Dockerfile.5.md`

and I'm betting you need to add tests to show different variations - including horror examples like

```
ENV ON there
ENV ONE 1
ENV SOMETHING $ONE
```

:)

**Comment by jfrazelle** [comment]
yes tests would be awesome!!

**Comment by jfrazelle** [comment]
this is breaking ALOT... see drone

**Comment by jfrazelle** [comment]
actually you just need to rebase you are missing sqlite fixes

**Comment by pritambaral** [comment]
@SvenDowideit About the tests, I don't think I can create tests that do not commit images, without extracting `func (b *Builder) commit(...` into `var commit = func (b *Builder, ...` and stubbing out the extracted function in builder_test.go.

Is that okay? Of course, the test would `b.Daemon.Delete(id)`

**Comment by vbatts** [comment]
_review session_

this is a special use-case need for this, it is static replacement, and the modifications needed to the parser are not worth ensuring all other use cases stay safe. Closing this PR as there is general disagreement among the core team that this behavior should even be allowed.

**Pull request closed without merging**
