### PR TITLE
names-generator homage to IBM's elite

### PR DESCRIPTION
**Pull request by jessefarinacci**
**- What I did**

Added a simple homage to IBM's elite: TJ Watson, and Ginny Rometty

**- How I did it**

Updated names-generator with description and linkage for TJ Watson and Ginny Rometty

**- How to verify it**

Launch containers without specifying --name

**- Description for the changelog**

ADD: Thomas J Watson and Ginny Rometty homage in the container names generator

**- A picture of a cute animal (not mandatory but encouraged)**

Fish:  ```><>```

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! Can you fix the sign-off (our bot @GordonTheTurtle left some instructions, but let us know if you need help doing so)

Also; can you add a woman as well? We try to keep this list balanced, as described here; https://github.com/docker/docker/blob/v17.03.0-ce/pkg/namesgenerator/names-generator.go#L107

**Comment by jessefarinacci** [comment]
@thaJeztah done

**Comment by jessefarinacci** [comment]
Sorry, I just saw the second part of your request @thaJeztah .. complete now, thank you! :)

**Comment by thaJeztah** [comment]
Thanks!

ping @anusha-ragunathan @jpetazzo PTAL :heart:

**Comment by tophj-ibm** [comment]
oh no, the IBM CI apparently doesn't want to this to happen 🤣  

(I'll restart them both)

**Comment by jpetazzo** [comment]
Hi!

Thanks for suggesting these additions. However, I see a couple of reasons to withhold them, at least until we can have a broader discussion.

First of all, we try to add mostly _inventors_ to the list. People who have showed creative tinkering, preferably in a scientific (or science-related) field. Indeed, Watson Sr. turned the then-unknown CTR Company into IBM, scaling it from a few millions to almost a billion dollar revenue; but he was mostly remembered for being an outstanding salesman. His role as an inventor is debatable. In his early career, when he was working for NCR, he was part of a group that sabotaged their competitors' machine. I don't know if that should qualify him as a great inventor, though. Then, still at NCR, he devised a very ingenious plan to eliminate the second-hand market (by undercutting the second-hand resellers until they go out of business). But on the _technical_ side, what did he invent? Furthermore, there is a controversy about his role during World War II and the supply by IBM of a census system (similar to the one they had sold to the US) which was then used by Nazi Germany to keep track of Jews and Gipsies. Watson even received a Nazi decoration for his collaboration. He sent back his medal, and officially disapproved of IBM's European subsidiaries collaboration with the Nazis; but according to IBM, all the documentation that would allow to prove or disprove these theories has been destroyed, unfortunately. (You can read more about these events in the book [IBM and the Holocaust](https://en.wikipedia.org/wiki/IBM_and_the_Holocaust), to be taken with a grain of salt of course.)

Given the fact that Watson was primarily a businessman, and that we try to make this a list of famous inventors, I would personally leave him out; but it's just my personal opinion – I'm totally open to discussion!

As for Rometty, I'm not aware of her background, so I'll pass (but will be happy to do research if needed).

Thank you regardless for the contribution!

**Comment by MHBauer** [comment]
It seems a little weird to nominate people to this list based on who they work for. Each individual should be standing on their own merits.

(Yes I work for IBM. This is my personal opinion. You can be sure that there's fifteen other IBMers looking at this PR as well.)

**Comment by jessefarinacci** [comment]
Yep. I think that's fair. I really was only trying to add TJ Watson/Watson AI, but then hit the other requirement for gender balance. I can just drop this PR, I think we've considered this for too many cycles already, given all the comments in thread. Thanks!

**Comment by thaJeztah** [comment]
Thanks @jessefarinacci, it's appreciated; it's tricky to add people to the list if there's a possible doubt, so we try to edge on the "safe side"

**Pull request closed without merging**
