### PR TITLE
vendor: github.com/opencontainers/runc v1.0.0-rc95

### PR DESCRIPTION
**Pull request by thaJeztah**
testing if things break with https://github.com/opencontainers/runc/pull/2700

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ok, Windows indeed now fails to build (related to https://github.com/opencontainers/runc/pull/2700);

```
INFO: Building the test binaries at 03/13/2021 14:53:17...
INFO: make.ps1 starting at 03/13/2021 14:53:21
INFO: Git commit (fea761a6a7) assumed from DOCKER_GITCOMMIT environment variable
INFO: Invoking autogen...
INFO: Building daemon...
powershell.exe : # github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/user
At D:\gopath\src\github.com\docker\docker@tmp\durable-82e8d70c\powershellWrapper.ps1:3 char:1
+ & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (# github.com/do...bcontainer/user:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

..\..\vendor\github.com\opencontainers\runc\libcontainer\user\lookup.go:19:9: undefined: lookupUser
..\..\vendor\github.com\opencontainers\runc\libcontainer\user\lookup.go:26:9: undefined: lookupUid
..\..\vendor\github.com\opencontainers\runc\libcontainer\user\lookup.go:33:9: undefined: lookupGroup
..\..\vendor\github.com\opencontainers\runc\libcontainer\user\lookup.go:40:9: undefined: lookupGid
# github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/devices
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:19:18: undefined: unix.Lstat
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:26:11: undefined: unix.Stat_t
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:36:15: undefined: unix.Major
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:37:15: undefined: unix.Minor
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:39:16: undefined: unix.S_IFMT
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:40:7: undefined: unix.S_IFBLK
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:42:7: undefined: unix.S_IFCHR
..\..\vendor\github.com\opencontainers\runc\libcontainer\devices\devices.go:44:7: undefined: unix.S_IFIFO
```

**Comment by thaJeztah** [comment]
Also a couple of failures (look unrelated to https://github.com/opencontainers/runc/pull/2700, but should be looked at)

Panic in TestExecSetPlatformOpt on s390x, arm64, ppc64le;

```
=== RUN   TestExecSetPlatformOpt
--- FAIL: TestExecSetPlatformOpt (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2656410]
goroutine 80 [running]:
testing.tRunner.func1(0xc000189c00)
	/usr/local/go/src/testing/testing.go:874 +0x41a
panic(0x28d1320, 0x402c010)
	/usr/local/go/src/runtime/panic.go:679 +0x1d4
github.com/docker/docker/daemon.WithRlimits.func1(0x305a660, 0xc0000ba010, 0x0, 0x0, 0x0, 0xc000172700, 0xe0, 0x6)
	/go/src/github.com/docker/docker/daemon/oci_linux.go:47 +0x40
github.com/docker/docker/daemon.(*Daemon).execSetPlatformOpt(0xc000410d20, 0xc00039ac80, 0xc000073e98, 0xc000638000, 0x40de240, 0xc000433538)
	/go/src/github.com/docker/docker/daemon/exec_linux.go:56 +0x2ec
github.com/docker/docker/daemon.TestExecSetPlatformOpt(0xc000189c00)
	/go/src/github.com/docker/docker/daemon/exec_linux_test.go:25 +0xdc
testing.tRunner(0xc000189c00, 0x2c94060)
	/usr/local/go/src/testing/testing.go:909 +0xd6
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x36c
FAIL	github.com/docker/docker/daemon	0.086s
```

Failure (no message "what") in `TestRootMountCleanup` on ppc64le and s390x

```
=== RUN   TestRootMountCleanup
=== PAUSE TestRootMountCleanup
```

And same for these tests (on ppc64le, arm64 and s390x)

```
=== RUN   TestGetBlkioWeightDevices
=== PAUSE TestGetBlkioWeightDevices

=== RUN   TestGetBlkioThrottleDevices
=== PAUSE TestGetBlkioThrottleDevices

=== RUN   TestVerifyPlatformContainerResources
=== PAUSE TestVerifyPlatformContainerResources
```

Looking if I see anything common among those;

<details>
<summary>arm64 docker info;</summary>

```
 + docker version
 Client: Docker Engine - Community
  Version:           20.10.3
  API version:       1.41
  Go version:        go1.13.15
  Git commit:        48d30b5
  Built:             Fri Jan 29 14:33:53 2021
  OS/Arch:           linux/arm64
  Context:           default
  Experimental:      true

 Server: Docker Engine - Community
  Engine:
   Version:          20.10.3
   API version:      1.41 (minimum version 1.12)
   Go version:       go1.13.15
   Git commit:       46229ca
   Built:            Fri Jan 29 14:32:08 2021
   OS/Arch:          linux/arm64
   Experimental:     true
  containerd:
   Version:          1.4.3
   GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
  runc:
   Version:          1.0.0-rc92
   GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
  docker-init:
   Version:          0.19.0
   GitCommit:        de40ad0


 + docker info
 Client:
  Context:    default
  Debug Mode: false
  Plugins:
   app: Docker App (Docker Inc., v0.9.1-beta3)
   buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

 Server:
  Containers: 0
   Running: 0
   Paused: 0
   Stopped: 0
  Images: 0
  Server Version: 20.10.3
  Storage Driver: overlay2
   Backing Filesystem: extfs
   Supports d_type: true
   Native Overlay Diff: true
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Cgroup Version: 1
  Plugins:
   Volume: local
   Network: bridge host ipvlan macvlan null overlay
   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
  Swarm: inactive
  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
  Default Runtime: runc
  Init Binary: docker-init
  containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
  runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
  init version: de40ad0
  Security Options:
   apparmor
   seccomp
    Profile: default
  Kernel Version: 4.15.0-1093-aws
  Operating System: Ubuntu 16.04.7 LTS
  OSType: linux
  Architecture: aarch64
  CPUs: 4
  Total Memory: 7.525GiB
  Name: ip-10-100-108-47
  ID: HS3U:IGO5:VPJI:V5M2:5SX2:V5CR:PRXJ:5HSF:G7SK:JBQF:ATHM:TB3S
  Docker Root Dir: /var/lib/docker
  Debug Mode: false
  Registry: https://index.docker.io/v1/
  Labels:
  Experimental: true
  Insecure Registries:
   127.0.0.0/8
  Live Restore Enabled: true

 WARNING: No swap limit support
```

</details>

<details>
<summary>ppc64le docker info;</summary>

```
 + docker version
 Client:
  Version:           18.06.1-ce
  API version:       1.38
  Go version:        go1.10.3
  Git commit:        e68fc7a
  Built:             Tue Aug 21 17:26:10 2018
  OS/Arch:           linux/ppc64le
  Experimental:      false

 Server:
  Engine:
   Version:          18.06.1-ce
   API version:      1.38 (minimum version 1.12)
   Go version:       go1.10.3
   Git commit:       e68fc7a
   Built:            Tue Aug 21 17:24:20 2018
   OS/Arch:          linux/ppc64le
   Experimental:     true

 + docker info
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 18.06.1-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
 runc version: 69663f0bd4b60df09991c08812a60108003fa340
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-130-generic
 Operating System: Ubuntu 16.04.3 LTS
 OSType: linux
 Architecture: ppc64le
 CPUs: 4
 Total Memory: 7.972GiB
 Name: ppc64le-ubuntu-14
 ID: WOPC:TAG6:HOGL:S7JK:UILM:CDDZ:Y2NL:NBVS:26FK:OZ4Z:642S:KUOE
 Docker Root Dir: /var/lib/docker
 Debug Mode (client): false
 Debug Mode (server): false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

</details>

<details>
<summary>s390x docker info;</summary>

```
 + docker version
 Client: Docker Engine - Community
  Version:           19.03.7
  API version:       1.40
  Go version:        go1.12.17
  Git commit:        7141c199a2
  Built:             Sat Mar  7 16:48:47 2020
  OS/Arch:           linux/s390x
  Experimental:      false

 Server: Docker Engine - Community
  Engine:
   Version:          19.03.7
   API version:      1.40 (minimum version 1.12)
   Go version:       go1.12.17
   Git commit:       7141c199a2
   Built:            Sat Mar  7 16:47:46 2020
   OS/Arch:          linux/s390x
   Experimental:     true
  containerd:
   Version:          1.2.13
   GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
  runc:
   Version:          1.0.0-rc10
   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
  docker-init:
   Version:          0.18.0
   GitCommit:        fec3683


 + docker info
 Client:
  Debug Mode: false

 Server:
  Containers: 0
   Running: 0
   Paused: 0
   Stopped: 0
  Images: 0
  Server Version: 19.03.7
  Storage Driver: overlay2
   Backing Filesystem: <unknown>
   Supports d_type: true
   Native Overlay Diff: true
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Plugins:
   Volume: local
   Network: bridge host ipvlan macvlan null overlay
   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
  Swarm: inactive
  Runtimes: runc
  Default Runtime: runc
  Init Binary: docker-init
  containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
  runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
  init version: fec3683
  Security Options:
   apparmor
   seccomp
    Profile: default
  Kernel Version: 4.15.0-91-generic
  Operating System: Ubuntu 18.04.4 LTS
  OSType: linux
  Architecture: s390x
  CPUs: 2
  Total Memory: 7.861GiB
  Name: s390x-ubuntu-16
  ID: KX4W:OISZ:E4EJ:3QOX:GCSE:TDK3:6NVC:NGLB:7US2:36DL:6NT2:YLOM
  Docker Root Dir: /var/lib/docker
  Debug Mode: false
  Registry: https://index.docker.io/v1/
  Labels:
  Experimental: true
  Insecure Registries:
   127.0.0.0/8
  Live Restore Enabled: false

 WARNING: No swap limit support
```

</details>

- docker version is different (20.10.3, 18.06.1-ce, 19.03.7)
- ubuntu versions are different (16.04.7, 16.04.3 LTS, 18.04.4 LTS)
- kernel is all 4.x (4.15.0-1093-aws, 4.4.0-130-generic, 4.15.0-91-generic)

**Comment by thaJeztah** [comment]
I'll remove the CRIU bump from this PR in favor of https://github.com/moby/moby/pull/42453

**Comment by thaJeztah** [comment]
@AkihiroSuda @cpuguy83 @kolyshkin PTAL

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by samuelkarp — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
