### PR TITLE
Fix the docker daemon restart command for ubuntu.

### PR DESCRIPTION
**Pull request by orsenthil**
**\- What I did**

Fix an instruction in the documentation.

**\- How I did it**

Tried the incorrect instruction.

**\- How to verify it**

Tried the correct instruction.

**\- Description for the changelog**

Fix the docker daemon restart instruction.

🐳

### CODE REVIEW

**Comment by thaJeztah** [comment]
What version of Ubuntu did you try it on? Original version worked for me;

```
sudo restart docker
docker start/running, process 3662
```

**Comment by orsenthil** [comment]
@thaJeztah , I am on 16.04

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
$ sudo restart docker
sudo: restart: command not found
$ sudo service docker restart
$
```

**Comment by thaJeztah** [comment]
@orsenthil hm, strange; looks to be working on one of my 16.04 boxes, but not on another; possibly it's an optional install. Ubuntu suggests installing upstart, but that doesn't make sense on a system using systemd.

Alright, this should work on both `upstart` and `systemd`, so  LGTM

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
