### PR TITLE
Minor changes to experimental docs

### PR DESCRIPTION
**Pull request by icecrime**
Ping @moxiegirl!

### CODE REVIEW

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
@thaJeztah give this a glance if you have a mo....please!

**Comment by thaJeztah** [comment]
Hadn't though about that possible confusion :+1:

LGTM, thanks @icecrime

**Comment by moxiegirl** [comment]
@jfrazelle cherry-pick please.

**Comment by jfrazelle** [comment]
im goinng to need these ones in order of which they were merged otherwise im gettting a ton of conflicts ;)

**Comment by jfrazelle** [comment]
found it was missing 95dfc4c4a545c3ca35ad7582bbfe4a627bd6a5fc

**Comment by moxiegirl** [comment]
ugh...ok. I'll prepare a list for you @jfrazelle

**Comment by jfrazelle** [comment]
i got it :)

**Pull request merged**
