### PR TITLE
man page fix: remove -e/--exec-drive=native related description

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
In the existing description:  
"As a result, you must also specify **-s=**native for this option to have effect. The -following is the only *native* option:"
I believe the author meant  `-e=native`. However, since that flag (-e / --exec-driver=native) has been removed, we can remove the associated description as well.

ping @thaJeztah

**Comment by thaJeztah** [comment]
Nice catch! I did a quick search, and noticed that some of the old API docs also still mention this, I think we can remove that as well; https://github.com/docker/docker/search?utf8=✓&q=%22exec-driver%22

Could you include that in this PR? :heart:

**Comment by shishir-a412ed** [comment]
@thaJeztah Sure thing.

**Comment by shishir-a412ed** [comment]
@thaJeztah PTAL

**Comment by thaJeztah** [comment]
LGTM! Thanks!

ping @moxiegirl for review/merge

**Comment by moxiegirl** [comment]
@shishir-a412ed Thank you sir! LGTM

**Pull request merged**
