### PR TITLE
Run the macvlan/ipvlan integration tests

### PR DESCRIPTION
**Pull request by robmry**
**- What I did**

While looking at https://github.com/moby/moby/pull/47318, I wondered why the change hadn't caused test `TestDockerNetworkMacvlan/OverlapParent` to fail...

The macvlan/ipvlan tests haven't been running since a hiccup in https://github.com/moby/moby/pull/45652.

**- How I did it**

Call the test functions.

**- How to verify it**

Tests now run.

**- Description for the changelog**

Fixed integration tests for ipvlan/macvlan.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by robmry** [comment]
> Wondering if (as a follow-up) we should remove the extra indirect of the closure, and make the signature of those subtests less error-prone, e.g. something like;

Sure - can do ... I'll add another commit to this PR, it might kick the flaky test into working.

**Comment by thaJeztah** [comment]
Yeah, I like the minimal changes if we want to backport this, but for "master" at least (I think) changing the signature may make it less error prone (that's just at a quick glance though, so take pinches of salt if you don't agree!)

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

for others; the diff is mostly whitespace, and much easier to review with whitespace changes removed; add `?w=1` to the "changes" URL for that; https://github.com/moby/moby/pull/47382/files?w=1

**Pull request merged**
