### PR TITLE
Poule: remove random assign

### PR DESCRIPTION
**Pull request by thaJeztah**
ping @tonistiigi

### CODE REVIEW

**Review by andrewhsu — APPROVED** [review]
SGTM w.r.t. reducing signal to noise so assignee knows a manually-assigned PR is specifically asked for

**Review by tonistiigi — APPROVED** [review]
Lets try to encourage manual assign more

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Merging since DCO check passed, no code changes at all.

**Comment by thaJeztah** [comment]
LOL @icecrime is watching

Screenshot 2019-09-05 at 21 30 31


edixjf9183

**Pull request merged**
