### PR TITLE
[wip] Update containerd runtime to v1.2.0

### LINKED ISSUE #942: Use Authorizer for image registry auth
Use the `Authorizer` introduced in https://github.com/containerd/containerd/pull/2690.

This is for https://github.com/containerd/containerd/issues/2683

### LINKED ISSUE #948: IPAM IP leakage
Reported by @lbernail.

After a node reboot, all network namespaces in `/var/run/netns` will be wiped out.

In that case, we'll skip `teardown` the cni network, because the network namespace has already gone. https://github.com/containerd/cri/blob/master/pkg/server/sandbox_stop.go#L64

However, if `host-local` `ipam` is being used, it checkpoints allocated ip in `/var/lib/cni/containerd-net/`, and the checkpoint won't be wiped out, e.g.
```console
$ ls /var/lib/cni/networks/containerd-net/
10.88.0.2  last_reserved_ip.0  lock
```
**If we skip `teardown`, the ip will be leaked forever.**

To fix this problem, we need to:
1) Teardown the network even if network namespace doesn't exist.
2) Ignore "no such file or directory" error in go-cni.

Actually, we should be able to pass in empty network namespace if it doesn't exist (see [the PR](https://github.com/containernetworking/plugins/commit/72337159c1c28772f752e9abedf74f7b24fce11a)). However, the behavior is not consistent across different plugins right now, at least `loopback` and `host-device` still returns error. And we are using `loopback` by default.

I've filed https://github.com/containernetworking/plugins/issues/210 for this. Before that is fixed, let's just ignore the "no such file or directory" error, which the cni libraries in kubernetes are doing as well: [cni](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/cni/cni.go#L329), [kubenet](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go#L591).

We should fix this and cherrypick into all supported branches.

### PR DESCRIPTION
**Pull request by thaJeztah**
Updated to v1.2.0. (c4446665cb9c30056f4998ed953e6d4ff22c7c39)

changes since the last bump: https://github.com/containerd/containerd/compare/405518591d1d94adebc110782da8205110bf7cd5...v1.2.0

- https://github.com/containerd/containerd/pull/2742 bugfix: return the context error during event subscribe
- https://github.com/containerd/containerd/pull/2729 runtime-v2: add validation for runtime name
- https://github.com/containerd/containerd/pull/2741 Update cri to f913714917d2456d7e65a0be84962b1ce8acb487
  - fixes https://github.com/containerd/cri/issues/942 Use Authorizer for image registry auth 
  - fixes https://github.com/containerd/cri/issues/948 IPAM IP leakage
  - Support runtime type specific configuration.

updated to current master, which should be pretty close to v1.2.0 GA (not tagged yet), and includes the fix for the failures here;

diff since v1.2.0-rc.2: https://github.com/containerd/containerd/compare/v1.2.0-rc.2...405518591d1d94adebc110782da8205110bf7cd5

- https://github.com/containerd/containerd/pull/2724 Update runc to 58592df56734acf62e574865fe40b9e53e
- https://github.com/containerd/containerd/pull/2725 enhance: split config from server package
- https://github.com/containerd/containerd/pull/2727 allow idempotence when adding a task to cgroup metrics collection

release notes: https://github.com/containerd/containerd/releases/tag/v1.2.0-rc.2

full diff since rc.1: https://github.com/containerd/containerd/compare/v1.2.0-rc.1...v1.2.0-rc.2

Possibly relevant changes;

- https://github.com/containerd/containerd/pull/2721 add memory limit, pid info into metric subcommand
- https://github.com/containerd/containerd/pull/2714 Fix writer deadlock in local store
- https://github.com/containerd/containerd/pull/2720 Fix stress test for image config opt requirements
- https://github.com/containerd/containerd/pull/2691 bugfix: cache empty layer for docker schema1 image
- https://github.com/containerd/containerd/pull/2717 Set uncompressed label on diff when already exists
- https://github.com/containerd/containerd/pull/2702 Update cri to 8506fe836677cc3bb23a16b68145128243d843b5
- https://github.com/containerd/containerd/pull/2688 decode spec in `ctr c info`

full diff since rc.0: https://github.com/containerd/containerd/compare/v1.2.0-rc.0...v1.2.0-rc.1

- New V2 Runtime with a stable gRPC interface for managing containers through
  external shims.
- Updated CRI Plugin, validated against Kubernetes v1.11 and v1.12, but it is
  also compatible with Kubernetes v1.10.
- Support for Kubernetes Runtime Class, introduced in Kubernetes 1.12
- A new proxy plugin configuration has been added to allow external
  snapshotters be connected to containerd using gRPC.-
- A new Install method on the containerd client allows users to publish host
  level binaries using standard container build tooling and container
  distribution tooling to download containerd related binaries on their systems.
- Add support for cleaning up leases and content ingests to garbage collections.
- Improved multi-arch image support using more precise matching and ranking
- Some Minor API additions

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @dmcgowan @vdemeester @crosbymichael @kolyshkin PTAL

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by thaJeztah** [comment]
Ok; looks like this is actually failing:

Janky timed out;

```
11:31:34 Build timed out (after 200 minutes). Marking the build as failed.
11:31:34 Build timed out (after 200 minutes). Marking the build as aborted.
11:31:34 Set build name.
11:31:34 New build name is '#37932'
11:31:34 Build was aborted
```

Experimental  https://jenkins.dockerproject.org/job/Docker-PRs-experimental/42382/console

```
08:30:41 --- FAIL: TestContainerStartOnDaemonRestart (2.34s)
08:30:41     daemon.go:292: [d597195c12a96] waiting for daemon to start
08:30:41     daemon.go:324: [d597195c12a96] daemon started
08:30:41     daemon.go:292: [d597195c12a96] waiting for daemon to start
08:30:41     daemon.go:324: [d597195c12a96] daemon started
08:30:41     daemon_linux_test.go:65: assertion failed: error is not nil: Error response from daemon: monitor task: cgroup is already being collected: unknown: failed to start test container
08:30:41     daemon.go:282: [d597195c12a96] exiting daemon
```
PowerPC; same failure: https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/11578/console

```
13:36:44 --- FAIL: TestContainerStartOnDaemonRestart (4.19s)
13:36:44     daemon.go:291: [dec29adbcc719] waiting for daemon to start
13:36:44     daemon.go:323: [dec29adbcc719] daemon started
13:36:44     daemon.go:291: [dec29adbcc719] waiting for daemon to start
13:36:44     daemon.go:323: [dec29adbcc719] daemon started
13:36:44     daemon_linux_test.go:65: assertion failed: error is not nil: Error response from daemon: monitor task: cgroup is already being collected: unknown: failed to start test container
13:36:44     daemon.go:281: [dec29adbcc719] exiting daemon
```

Z; same failure; https://jenkins.dockerproject.org/job/Docker-PRs-s390x/11444/console

```
09:45:49 --- FAIL: TestContainerStartOnDaemonRestart (2.94s)
09:45:49     daemon.go:291: [d4f1dc69ce69b] waiting for daemon to start
09:45:49     daemon.go:323: [d4f1dc69ce69b] daemon started
09:45:49     daemon.go:291: [d4f1dc69ce69b] waiting for daemon to start
09:45:49     daemon.go:323: [d4f1dc69ce69b] daemon started
09:45:49     daemon_linux_test.go:65: assertion failed: error is not nil: Error response from daemon: monitor task: cgroup is already being collected: unknown: failed to start test container
09:45:49     daemon.go:281: [d4f1dc69ce69b] exiting daemon
```

**Comment by thaJeztah** [comment]
I see the same failure was happening on my old PR; https://github.com/moby/moby/pull/37710#issuecomment-416724875

**Comment by thaJeztah** [comment]
Error originates from this part in containerd; https://github.com/containerd/containerd/blob/94cfce62ba9eabb58417cb5a663dc7a9feb68c07/metrics/cgroups/metrics.go#L135-L148

**Comment by AkihiroSuda** [comment]
rc1 is available now

**Comment by thaJeztah** [comment]
Rebased on https://github.com/moby/moby/pull/37710, to see if that fixes the problem

**Comment by thaJeztah** [comment]
Ok that didn't help; still failing on the same.

Here's from an earlier run (without the containerd client bump);

```
time="2018-10-04T15:47:40.101249463Z" level=info msg="API listen on /tmp/docker-integration/d5e35f489c854.sock"
time="2018-10-04T15:47:40.104573736Z" level=debug msg="Calling GET /_ping"
time="2018-10-04T15:47:40.106633678Z" level=debug msg="Calling GET /info"
time="2018-10-04T15:47:40.134842186Z" level=debug msg="Calling POST /v1.39/containers/a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9/start"
time="2018-10-04T15:47:40.136141754Z" level=debug msg="container mounted via layerStore: &{/go/src/github.com/docker/docker/bundles/test-integration/d5e35f489c854/root/overlay2/0d5167e2a76dd9b0260451a03173c3bd5f0ae0eb8819ac532842621bda76ab08/merged 0x563118c264c0 0x563118c264c0}"
time="2018-10-04T15:47:40.136561020Z" level=debug msg="Assigning addresses for endpoint naughty_chatelet's interface on network bridge"
time="2018-10-04T15:47:40.136592480Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[])"
time="2018-10-04T15:47:40.136624967Z" level=debug msg="Request address PoolID:172.18.0.0/16 App: ipam/default/data, ID: LocalDefault/172.18.0.0/16, DBIndex: 0x0, Bits: 65536, Unselected: 65533, Sequence: (0xc0000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:0 Serial:false PrefAddress:<nil> "
time="2018-10-04T15:47:40.139394140Z" level=debug msg="Assigning addresses for endpoint naughty_chatelet's interface on network bridge"
time="2018-10-04T15:47:40.142740759Z" level=debug msg="Programming external connectivity on endpoint naughty_chatelet (0ed72fa5797217710c9f61181d783182620e48bdde18e5642d525144c9e9b008)"
time="2018-10-04T15:47:40.143331099Z" level=debug msg="EnableService a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9 START"
time="2018-10-04T15:47:40.143356155Z" level=debug msg="EnableService a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9 DONE"
time="2018-10-04T15:47:40.145770162Z" level=debug msg="bundle dir created" bundle=/tmp/dxr/d5e35f489c854/containerd/a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9 module=libcontainerd namespace=moby root=/go/src/github.com/docker/docker/bundles/test-integration/d5e35f489c854/root/overlay2/0d5167e2a76dd9b0260451a03173c3bd5f0ae0eb8819ac532842621bda76ab08/merged
time="2018-10-04T15:47:40.399479908Z" level=debug msg="sandbox set key processing took 110.297666ms for container a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9"
time="2018-10-04T15:47:40.506001325Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/create
time="2018-10-04T15:47:40.506504381Z" level=error msg="stream copy error: read /proc/self/fd/19: file already closed"
time="2018-10-04T15:47:40.506573964Z" level=error msg="stream copy error: read /proc/self/fd/20: file already closed"
time="2018-10-04T15:47:40.518577066Z" level=error msg="failed to delete failed start container" container=a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9 error="cannot delete running task a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9: failed precondition"
time="2018-10-04T15:47:40.523188576Z" level=debug msg="Revoking external connectivity on endpoint naughty_chatelet (0ed72fa5797217710c9f61181d783182620e48bdde18e5642d525144c9e9b008)"
time="2018-10-04T15:47:40.523741694Z" level=debug msg="DeleteConntrackEntries purged ipv4:0, ipv6:0"
time="2018-10-04T15:47:40.615004148Z" level=debug msg="Releasing addresses for endpoint naughty_chatelet's interface on network bridge"
time="2018-10-04T15:47:40.615059361Z" level=debug msg="ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.2)"
time="2018-10-04T15:47:40.615096593Z" level=debug msg="Released address PoolID:LocalDefault/172.18.0.0/16, Address:172.18.0.2 Sequence:App: ipam/default/data, ID: LocalDefault/172.18.0.0/16, DBIndex: 0x0, Bits: 65536, Unselected: 65532, Sequence: (0xe0000000, 1)->(0x0, 2046)->(0x1, 1)->end Curr:3"
time="2018-10-04T15:47:40.678451004Z" level=error msg="a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9 cleanup: failed to delete container from containerd: cannot delete running task a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9: failed precondition"
time="2018-10-04T15:47:40.678545724Z" level=error msg="Handler for POST /v1.39/containers/a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9/start returned error: monitor task: cgroup is already being collected: unknown"
time="2018-10-04T15:47:40.680743288Z" level=debug msg="Calling DELETE /v1.39/containers/a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9?force=1"
time="2018-10-04T15:47:40.689905866Z" level=info msg="Processing signal 'interrupt'"
time="2018-10-04T15:47:40.690034120Z" level=debug msg="daemon configured with a 15 seconds minimum shutdown timeout"
time="2018-10-04T15:47:40.690170179Z" level=debug msg="start clean shutdown of all containers with a 15 seconds timeout..."
time="2018-10-04T15:47:40.691324619Z" level=debug msg="Unix socket /tmp/dxr/d5e35f489c854/libnetwork/2d75bb866ce6b3a84b0c820e460c478f65245b97baadaf1e08c7383aa5fcbe97.sock doesn't exist. cannot accept client connections"
time="2018-10-04T15:47:40.691422182Z" level=debug msg="Cleaning up old mountid : start."
time="2018-10-04T15:47:40.692104928Z" level=debug msg="Cleaning up old mountid : done."
time="2018-10-04T15:47:40.692626051Z" level=debug msg="Clean shutdown succeeded"
```

Looks like this may be part of the problem ("cannot delete running task "). This is after the daemon and containerd are started again;

```
time="2018-10-04T15:47:40.518577066Z" level=error msg="failed to delete failed start container" container=a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9 error="cannot delete running task a264029c90f49ad4ce973f4780234f7ad780bde41d39b9255dc48af6060408f9: failed precondition"
```

- daemon logs of that test [docker.log](https://github.com/moby/moby/files/2450116/docker.log)
- test logs [test.log](https://github.com/moby/moby/files/2450118/test.log)

**Comment by thaJeztah** [comment]
@crosbymichael if you have any ideas on that failure ^^ - I won't have time this evening, but if you have any ideas 🤗

**Comment by crosbymichael** [comment]
This can be closed right?

**Comment by thaJeztah** [comment]
The other PR only updated the client; the version of the containerd binary in this repository (and running in CI) is still on 1.1.4

**Comment by crosbymichael** [comment]
How are you supposed to figure out what is wrong when there is basically nothing in the test output of what happened?

**Comment by thaJeztah** [comment]
For these cases, it'd be to download the bundles from Jenkins, and find the daemon logs for the daemon that ran for that test 😟

**Comment by crosbymichael** [comment]
@thaJeztah are you still looking into the issues to get this merged?

**Comment by thaJeztah** [comment]
@crosbymichael well, haven't solved it yet, but hadn't much time to dive into it t.b.h., so if you have any ideas for a possible cause 😓

**Comment by dmcgowan** [comment]
Can you update this and point to https://github.com/containerd/containerd/pull/2727

**Comment by mikebrow** [comment]
@thaJeztah because my commit hasn't been merged into a branch on master yet (nudge @dmcgowan :-) I had to clone from my fork to successfully test out the fix:
```
CONTAINERD_COMMIT=c16281f4201d6ee94563bc7b3adbcea9c7dbe7c4 # v1.2.0-rc.2
...
	git clone https://github.com/mikebrow/containerd.git "$GOPATH/src/github.com/containerd/containerd"
...
```

**Comment by thaJeztah** [comment]
:heart: thanks @mikebrow !

**Comment by mikebrow** [comment]
anytime, cheers!

**Comment by thaJeztah** [comment]
Looks like CI is hanging after completion;


```
12:20:38 Build timed out (after 180 minutes). Marking the build as failed.
12:20:38 Build timed out (after 180 minutes). Marking the build as aborted.
```

```
14:20:15 Build timed out (after 300 minutes). Marking the build as failed.
14:20:15 Build timed out (after 300 minutes). Marking the build as aborted.
```

Which looks the same as https://github.com/moby/moby/pull/38062#issuecomment-432441880

> CI seems to be hanging because of leaked `containerd-shim` processes created while `docker-py` ran.
> 
> Logs and processes in: https://gist.github.com/tonistiigi/a5739d2c0f82442c0317bea044cc56e2
> 
> From the logs. The test ran a `DELETE` request for that failed with
> 
> ```
> time="2018-10-23T19:03:57.531600098Z" level=error > msg="fc42a122b164349bced9e08588f6782f65de38e823b5649467533cd07d359464 cleanup: failed to delete container from containerd: cannot delete running task fc42a122b164349bced9e08588f6782f65de38e823b5649467533cd07d359464: failed precondition"
> ```
> 
> and leaked the shim process.

**Comment by thaJeztah** [comment]
Linking, just in case there's a relation https://github.com/moby/moby/issues/37072

**Comment by thaJeztah** [comment]
Rebased, after https://github.com/moby/moby/pull/38128 was merged (which updates runc)

**Comment by thaJeztah** [comment]
Closing, because https://github.com/moby/moby/pull/38168 was merged, which has these changes

**Pull request closed without merging**
