### PR TITLE
Bump swarmkit

### PR DESCRIPTION
**Pull request by cpuguy83**
This fixes some dispatcher races.

Full diff: https://github.com/docker/swarmkit/compare/f74983e7c015a38a81c8642803a78b8322cf7eac...49a9d7f6ba3c1925262641e694c18eb43575f74b

### CODE REVIEW

**Review by yongtang — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :taco:

**Comment by cpuguy83** [comment]
Yes, at least partially. I'm hoping this stabilizes CI a bit, which has had lots of deadlock issues from swarmkit since the last bump.

**Comment by thaJeztah** [comment]
@cpuguy83 just CI, or actual issue? Do we need to include this in 18.03?

**Comment by cpuguy83** [comment]
It's a real problem thY should be included in 18.03.
This is being backported to 17.12.1, IIRC.

**Comment by thaJeztah** [comment]
18.03 backport: https://github.com/docker/docker-ce/pull/451

**Pull request merged**
