### PR TITLE
builder-next: userns remap support

### PR DESCRIPTION
**Pull request by tonistiigi**
Allow buildkit builds with `userns-remap` flag.

~Depends on https://github.com/moby/buildkit/pull/1046~

### CODE REVIEW

**Comment by tonistiigi** [comment]
Updated vendor

**Comment by thaJeztah** [comment]
@AkihiroSuda @estesp @tiborvass PTAL

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Seeing these kind of failures more often again; https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/2730/console

```
18:50:48 --- FAIL: TestJSONFileLoggerWithOpts (0.01s)
18:50:48     jsonfilelog_test.go:187: open C:\Users\ContainerAdministrator\AppData\Local\Temp\docker-logger-895282073\container.log.1: The process cannot access the file because it is being used by another process.
```

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
