### PR TITLE
Cleanup container reg for lxc special case

### PR DESCRIPTION
**Pull request by cpuguy83**
The lxc code here is doing the exact same thing on calling
execdriver.Terminate, so let's just use that.

Also removes some dead comments originally introduced
50144aeb42283848db730b936d6b5b6332ec6565 but no longer relevant since we
have restart policies.

### CODE REVIEW

**Comment by LK4D4** [comment]
@cpuguy83 Looks like lxc fail caused by other error, which you fixed in another PR.

**Comment by cpuguy83** [comment]
Indeed

**Comment by cpuguy83** [comment]
This one is ready.

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
