### PR TITLE
Add zsh completion for 'docker plugin' commands

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #23446

@vincentbernat
ping @albers for bash completion

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vincentbernat** [comment]
LGTM

**Comment by albers** [comment]
can you please add a ref to the implementing PR?

Steve Durrheimer <notifications@github.com> hat geschrieben:

@vincentbernat
ping @albers for bash completion

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

You can view, comment on, or merge this pull request online at:

  https://github.com/docker/docker/pull/24273

Commit Summary

Add zsh completion for 'docker plugin' commands
File Changes

M contrib/completion/zsh/_docker     (101)
Patch Links:

https://github.com/docker/docker/pull/24273.patch
https://github.com/docker/docker/pull/24273.diff

**Comment by sdurrheimer** [comment]
@albers done

**Comment by albers** [comment]
Thanks @sdurrheimer

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
hm, how should we deal with these completions, since they're only available in the experimental builds? I think for bash we decided to not implement them

**Pull request merged**
