### PR TITLE
Remove engine usage from attach

### PR DESCRIPTION
**Pull request by LK4D4**
ping @tiborvass

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM waiting for CI

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Well I was waiting for Windows CI to re-run, but you seemed to have pushed an update  now :(

**Comment by LK4D4** [comment]
@cpuguy83 yup :) No worries, windows was failed only on `TestPullVerify`.

**Comment by jfrazelle** [comment]
*shakes fist in air* at that test

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
