### PR TITLE
Update vendored libcontainer

### PR DESCRIPTION
**Pull request by boucher**

### CODE REVIEW

**Comment by LK4D4** [comment]
Haha, it's tagged!
ping @tianon

**Comment by tianon** [comment]
@LK4D4 nice!  The dependency tree is still cyclic (because of a few `pkg/` imports left in libcontainer), but that's a good step in the right direction. :+1:

LGTM

**Comment by boucher** [comment]
ping @LK4D4

**Comment by LK4D4** [comment]
LGTM
@boucher Thanks!

**Pull request merged**
