### PR TITLE
Fix build-deb

### PR DESCRIPTION
**Pull request by tianon**
This fixes the part of #12996 that I forgot. :angel:

This also fixes a minor path issue (there's no `libexec` in Debian), and fixes a minor bug with the `debVersion` parsing.

Thanks to @chrissnell for pointing this issue out (in https://github.com/docker/docker/issues/12535#issuecomment-99572386).

### CODE REVIEW

**Comment by tianon** [comment]
cc @jfrazelle

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
Merging since the fix is so simple; thanks @jfrazelle and thanks again @chrissnell

**Comment by thaJeztah** [comment]
is there some way to realize https://github.com/docker/docker/issues/12535#issuecomment-99705375 ? I think master.dockerproject.com only has static builds, correct?

**Comment by tianon** [comment]
Yeah, I'm thinking we could get at least the raw debs on there, but I need
to chat with @jfrazelle about how to make that happen most effectively. :+1:

**Comment by thaJeztah** [comment]
great! thanks in advance (in name of those requesting :))

**Comment by jfrazelle** [comment]
ya I was thinking nightlies ;) have some ideas

**Comment by thaJeztah** [comment]
Docker Canary! (no, "Dolphin"🐬 channel)

**Pull request merged**
