### PR TITLE
Bump SwarmKit to 1a0ebd43b2d156983a695f90e56f4ecba6ced902

### PR DESCRIPTION
**Pull request by thaJeztah**
https://github.com/docker/swarmkit/compare/8af8c420f491f006ab1730e08d446a795b1667d7...1a0ebd43b2d156983a695f90e56f4ecba6ced902

relevant changes:

- https://github.com/docker/swarmkit/pull/2771 Allow using Configs as CredentialSpecs
- https://github.com/docker/swarmkit/pull/2804 Make Service.UpdateStatus non-ambiguous
- https://github.com/docker/swarmkit/pull/2805 Refactor condition in restart supervisor
- https://github.com/docker/swarmkit/pull/2780 api: add BindOptions.NonRecursive
  - related to https://github.com/moby/moby/pull/38003
- https://github.com/docker/swarmkit/pull/2790 Fix possible panic if NetworkConfig is nil
- https://github.com/docker/swarmkit/pull/2797 Include old error-message for backward compatibility
  - related to https://github.com/docker/swarmkit/pull/2779 / https://github.com/moby/moby/issues/38140 / https://github.com/moby/moby/pull/38142

See description below for the original PR description (before swarmkit bump)

In situations where only annotations of a service were updated, SwarmKit never marks a service as `UpdateStateUpdating`; the service's `UpdateStatus` is set to `nil`, and never updated after.

Because of this, it's not possible to verify if the update actually happened (unless comparing the services `Version` before and after).

This patch modifies the SwarmKit vendored code to try to make this situation non-ambigious, and mark the services as "updated" in all cases.

Relates to https://github.com/moby/moby/pull/38499#issuecomment-452679063 :

> Looking at that code; https://github.com/moby/moby/pull/38499#issuecomment-452570204
> 
> 
> As part of the Service update, [`controlapi.UpdateService()`](https://github.com/docker/swarmkit/blob/0091d9285168040649140c76629e4284857e5365/manager/controlapi/service.go#L721-L846) sets `Updatestatus` to `nil` to [indicate that an update is in progress](https://github.com/docker/swarmkit/blob/0091d9285168040649140c76629e4284857e5365/manager/controlapi/service.go#L827-L828); after that the updated service is written to the store ([`store.UpdateService()`](https://github.com/docker/swarmkit/blob/0091d9285168040649140c76629e4284857e5365/manager/controlapi/service.go#L837)), which updates the `UpdatedAt` and `Version`.
> 
> [`Updater.Run()`](https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L123-L308) checks if any tasks are "dirty" and need updating; https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L137-L141
> 
> ```go
> 	var dirtySlots []orchestrator.Slot
> 	for _, slot := range slots {
> 		if u.isSlotDirty(slot) {
> 			dirtySlots = append(dirtySlots, slot)
> 		}
> 	}
> ```
> 
> Some changes on a service don't require updates to the task (container); to check if updates are needed, these functions are called:
> 
> - [`Updater.isSlotDirty()`](https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L530-L532)
>     - -> [`Updater.isTaskDirty`](https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L522-L528)
>       - -> [`orchestrator.IsTaskDirty()`](https://github.com/docker/swarmkit/blob/7567d47988d82a78b052c4b9ba1e61399e0e7897/manager/orchestrator/task.go#L63-L113)
> 
> If changes are needed, `len(dirtySlots) > 0`, in which case and update is started (if no update is in progress yet). From that part of the code, it's clear that [`service.UpdateStatus == nil` is required](https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L152-L155) to even consider starting an update. [`Updater.startUpdate()`](https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L534-L556) is called, which sets the service's UpdateStatus to `UpdateStatus_UPDATING`, and sets the `UpdateStatus.StartedAt` to the current time.
> 
> However, in case of the `service-label` update, no updates to the tasks are needed, so `len(dirtySlots) == 0`; in that case, no action is needed, given that no update (or "rollback") was ever started for this. In that case, the [`Service.UpdateStatus` is not updated, so remains `nil`](https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L144-L149)
> 
> ```go
> 	// Abort immediately if all tasks are clean.
> 	if len(dirtySlots) == 0 {
> 		if service.UpdateStatus != nil &&
> 			(service.UpdateStatus.State == api.UpdateStatus_UPDATING ||
> 				service.UpdateStatus.State == api.UpdateStatus_ROLLBACK_STARTED) {
> 			u.completeUpdate(ctx, service.ID)
> 		}
> 		return
> 	}
> ```
> 
> Even if we _would_ skip the check (if an updated or rollback was started), `update.completeUpdate()` checks `service.UpdateStatus`. If `service.UpdateStatus == nil`, it [assumes that _another_ update was started, so the `service.UpdateStatus` is not updated](https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/orchestrator/update/updater.go#L627-L630);
> 
> ```go
> 	if service.UpdateStatus == nil {
> 		// The service was changed since we started this update
> 		return nil
> 	}
> ```
> 
> 
> Based on the  above, it looks like `service.UpdateStatus == nil` is ambiguous; as it can either be;
> 
> - An update was triggered, but no action was required (in which case it's equal to `UpdateStatus_COMPLETED` or `UpdateStatus_ROLLBACK_COMPLETED`)
> - An update was triggered, but the actual update was not yet started
> 
> I _think_ we can make it non-ambiguous if we set the status to `UpdateStatus_COMPLETED` if there are no tasks to update (`len(dirtySlots) == 0`); this requires a change to `Updater.Run()` (change the check), and to `update.completeUpdate()`

### CODE REVIEW

**Comment by thaJeztah** [comment]
Let's see if this works; updated the vendored code in this PR just to give it a quick try 😅

**Comment by olljanat** [comment]
Tested with my new tool #38523 works (renamed test to trigger test). Passed nicely all 25 tries. Log from that test: [38520_test-integration-flaky.log](https://github.com/moby/moby/files/2742555/38520_test-integration-flaky.log)

Looks good :+1

**Comment by thaJeztah** [comment]
Opened an upstream PR in SwarmKit; https://github.com/docker/swarmkit/pull/2804

**Comment by thaJeztah** [comment]
Ping @dperny - guess we need an updated description in the API reference for 
https://github.com/docker/swarmkit/pull/2771 ? Do we need a test for that?

ping @AkihiroSuda this brings in https://github.com/docker/swarmkit/pull/2780 (did you prepare changes already for `docker service create`? Are changes needed?

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by AkihiroSuda** [comment]
> ping @AkihiroSuda this brings in docker/swarmkit#2780 (did you prepare changes already for docker service create? Are changes needed?

I can open follow-up PR

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
All green

**Pull request merged**
