### PR TITLE
Fix VFS vs quota regression

### PR DESCRIPTION
**Pull request by kolyshkin**
**- What I did**
Fixed https://github.com/moby/moby/issues/35815

**- How I did it**
1. `ENOSYS` from `mknod()` is now treated as "quota not supported".
2. Any errors returned from `quota.NewControl()` are now ignored (and logged).

**- How to verify it**
Start daemon with vfs driver backed by osxfs

**- Description for the changelog**
Fix vfs graph driver failure to initialize because of failure to setup fs quota

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL

/cc @sargun

**Comment by kolyshkin** [comment]
Now this is a rather conservative fix, only making `ENOSYS` from `mknod()` a special case. A less conservative fix would be to treat any error from `quota.NewControl()` as "quota not supported", essentially ignoring any errors during quota init.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by sargun** [comment]
@kolyshkin I would change to making it so that any error returned from initializing quota in the VFS driver code marks it as quota not supported. It'd also fix the user namespaces case in a general way.

**Comment by kolyshkin** [comment]
@sargun makes sense. I will keep this patch (as it makes sense for other graphdrivers, too) and add another one.

**Comment by sargun** [comment]
LGTM.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
All tests passed now, including `z` 🎉

**Pull request merged**
