### PR TITLE
Updated Windows mounting example

### PR DESCRIPTION
**Pull request by petrsvihlik**
**\- What I did**
Corrected an example of mounting persistent storage on windows according to http://superuser.com/questions/1051520/docker-windows-container-how-to-mount-a-host-folder-as-data-volume-on-windows
The original syntax was not working...

**\- How I did it**
By typing letters on my keyboard.

**\- How to verify it**
Run the example command. I tested it on WS2016 TP5. Works fine.

**\- Description for the changelog**
Updated example of mounting persistent storage on Windows

**\- A picture of a cute animal (not mandatory but encouraged)**
My pug

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks! I think the difference here might be what kind of daemon you're using; the example works if you're running Docker Toolbox (which uses a VirtualBox VM), but may not work against a native Windows Daemon.

We may need to make a distinction here between these setups; let me give this some thinking

**Comment by petrsvihlik** [comment]
Yeah, that was my case. I was using PS against the windows daemon... I probably should have used the [Windows Containers documentation](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_data) on MSDN. However, it's a bit confusing for newcomers. I would expect one syntax across all platforms. :)

**Comment by thaJeztah** [comment]
ping @friism any suggestions how we should do this?

**Comment by friism** [comment]
Ultimately I think we need a separate doc for Windows containers, cc @neilpeterson, or else stage-manage the steps in this doc very carefully. There are at least these cases:

 * OS X/Linux running against Linux Docker daemon
 * Windows running against Linux Docker daemon (and here there are sub-cases because you can get owned by cygwin-like shells trying to help you by re-writing paths)
 * Windows running against Windows daemon

Is there a good way to manage that sort of stuff in the current docs system? @neilpeterson, what are your thoughts?

**Comment by neilpeterson** [comment]
As a stop gap or even potential long term solution, we do have a [doc on MSDN](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_data) which should detail proper syntax for Windows.

I have a backlog of changes propose into the Docker docs, I could include a reference to the Windows doc, if you would be open to that. 

I assume that we will run into similar circumstances with other discrepancies, we may want to figure out some firm strategy around this.

**Comment by SvenDowideit** [comment]
@friism @thaJeztah ?

**Comment by jhowardmsft** [comment]
Actually the 'correct' syntax on native Windows shells is to use backslash not forward slashes....

**Comment by LK4D4** [comment]
ping @petrsvihlik

**Comment by crosbymichael** [comment]
Like @jhowardmsft said, this should be a backslash.

**Comment by sfsmithcha** [comment]
ping @londoncalling can you correct the syntax and carry this pr or otherwise close it? thanks.

**Comment by petrsvihlik** [comment]
sorry, I was off for a couple of days. i've updated the example

**Comment by sfsmithcha** [comment]
CI error is incorrect/unrelated.

@petrsvihlik , please sign the most recent commit and squash your commits.

**Comment by londoncalling** [comment]
@sfsmithcha LGTM after @petrsvihlik 's fixes to syntax. The docs error is bogus I believe. (I don't have merge permissions on `docker/docker` so you'll have to merge it.)

**Comment by crosbymichael** [comment]
This needs to be squashed into 1 commit before it can be merged

**Comment by londoncalling** [comment]
LGTM, docs fail doesn't seem to be real. It's complaining about a link that works.

**Comment by petrsvihlik** [comment]
@crosbymichael @sfsmithcha sure, I just need a little bit of time to figure out how :) i tried `git rebase -i` as shown above and it takes quite a lot of time to run and it fails in the end. i want to dive into it to learn something new. give me a few days pls :)

**Comment by petrsvihlik** [comment]
I somehow f*cked up my branch...Created a new PR: https://github.com/docker/docker/pull/26294

**Pull request closed without merging**
