### PR TITLE
volume/local: refactor validation to allow invalidating early

### PR DESCRIPTION
**Pull request by thaJeztah**
- follow up to https://github.com/moby/moby/pull/43591

See individual commits for details.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
Rebased to get a fresh run of CI (perhaps fixing the CodeCov failure)

**Comment by thaJeztah** [comment]
booh. codecov/patch now fails ("39.68% of diff hit (target 50.00%)")

**Comment by thaJeztah** [comment]
CodeCov still doesn't like it, but looks like it's just confused (shows coverage changes in distribution and logging  code 😂🤷‍♂️)

**Comment by thaJeztah** [comment]
@cpuguy83 ptal

**Review by cpuguy83 — APPROVED** [review]

**Comment by thaJeztah** [comment]
thx! Let me get this one in 👍

**Pull request merged**
