### PR TITLE
Remove contents of docs/ except for reference, point to new location

### PR DESCRIPTION
**Pull request by mdlinville**
I screwed up #27297 and this PR carries that PR. Sorry @johndmulhausen @thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like there's some stray `.DS_Store` files;

```
ls -la docs/userguide/
total 16
drwxr-xr-x  3 sebastiaan  staff   102 Oct 14 10:07 .
drwxr-xr-x  7 sebastiaan  staff   238 Oct 14 10:07 ..
-rw-r--r--@ 1 sebastiaan  staff  6148 Oct 14 10:08 .DS_Store

ls -la docs/installation/
total 24
drwxr-xr-x  4 sebastiaan  staff   136 Oct 14 10:07 .
drwxr-xr-x  7 sebastiaan  staff   238 Oct 14 10:07 ..
-rw-r--r--@ 1 sebastiaan  staff  8196 Oct 14 10:07 .DS_Store
drwxr-xr-x  3 sebastiaan  staff   102 Oct 14 10:07 images

ls -la docs/installation/images/
total 16
drwxr-xr-x  3 sebastiaan  staff   102 Oct 14 10:07 .
drwxr-xr-x  4 sebastiaan  staff   136 Oct 14 10:07 ..
-rw-r--r--@ 1 sebastiaan  staff  6148 Dec 23  2015 .DS_Store
```

**Comment by thaJeztah** [comment]
Oh, there's a couple more :D

**Comment by thaJeztah** [comment]
Some additional things that need to be removed; there's some leftovers in the Makefile for `make docs` (we probably need an alternative for that, but not sure how to realize that with the new repo)

- https://github.com/docker/docker/blob/master/Makefile#L96-L97
- https://github.com/docker/docker/blob/master/Makefile#L1
- https://github.com/docker/docker/blob/master/Makefile#L59

**Comment by mstanleyjones** [comment]
The .DS_Store was a false positive. I've removed the lines from the MAKEFILE. PTAL again @thaJeztah

**Comment by thaJeztah** [comment]
Oops! the `.DS_Store` files were in my local checkout, and git ignores them so when switching branches, it keeps those :D

**Comment by thaJeztah** [comment]
I just discussed with @anusha-ragunathan, and we think that the `docs/extend` directory should be considered reference docs, as it's really close to the code.

Possibly the https://github.com/docker/docker/blob/master/docs/extend/legacy_plugins.md can be considered "docs" (and handled in the docker.github.io repository), and I _think_ the menu.md is no longer needed now that we no longer use hugo (https://raw.githubusercontent.com/docker/docker/master/docs/extend/menu.md)

**Comment by mstanleyjones** [comment]
I think it will be really hard to say that the extend/ directory should be maintained here except for the one file which should be maintained elsewhere, so let's just commit to maintaining extend/ here too. I'll update the PR.

**Comment by mstanleyjones** [comment]
OK, extend/ is back.

**Review by thaJeztah — APPROVED** [review]
LGTM 👋 :cry:

**Pull request merged**
