### PR TITLE
cgroup2: use "systemd" cgroup driver by default when available

### LINKED ISSUE #40836: change the default cgroup driver to "systemd" (on cgroup v2 hosts)
The "systemd" cgroup driver is always preferred over "cgroupfs" on systemd-based hosts.

I suggest changing the default driver from "cgroupfs" to "systemd".
To avoid causing compatibility issues on existing cgroup v1 hosts, probably we should begin with changing the default on cgroup v2 hosts.

ref: https://github.com/opencontainers/runc/issues/2315#issuecomment-614185239
cc @kolyshkin

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**
Use "systemd" cgroup driver by default on systemd-based cgroup v2 hosts, because the "systemd" cgroup driver is always preferred over "cgroupfs" on systemd-based hosts.

This commit does not affect cgroup v1 hosts.

**- How I did it**

**- How to verify it**
`docker info`

**- Description for the changelog**

cgroup2: use "systemd" cgroup driver by default when available

**- A picture of a cute animal (not mandatory but encouraged)**

- - -
Fix https://github.com/moby/moby/issues/40836

~Marking as WIP until https://github.com/opencontainers/runc/pull/2281 gets merged~ (**EDIT**: ready to review/merge)

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Marking as WIP until https://github.com/opencontainers/runc/pull/2281 gets merged

**Comment by AkihiroSuda** [comment]
@thaJeztah @kolyshkin WDYT?

**Comment by AkihiroSuda** [comment]
Ready for review/merge

**Comment by AkihiroSuda** [comment]
@kolyshkin @thaJeztah  @cpuguy83 @tianon PTAL

**Comment by tianon** [comment]
Doesn't the `systemd` cgroup driver have some downsides?

(Maybe @ibuildthecloud would be willing to chime in on this one? :sweat_smile: :heart:  https://twitter.com/ibuildthecloud/status/1258251075519307782)

**Comment by thaJeztah** [comment]
@AkihiroSuda do you think this is critical to have? Wondering if we could (for the upcoming) release stick to the old (users can change the configuration if desired), and look further for the release after?

**Comment by thaJeztah** [comment]
@AkihiroSuda what's the result of running cgroupfs when cgroups v2 is used? Is it non-functional, or "works" ? (You mention it's always preferred to use systemd cgroups in that case; we were wondering "why")

**Comment by AkihiroSuda** [comment]
> Doesn't the systemd cgroup driver have some downsides?

On cgroup v1, it had, because it was not used by default and didn't get many users and contributors.
The systemd driver for v2 will be more matured if we make it default.

Podman has already switched the default to systemd.
Kubernetes recommends systemd as well: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers

> do you think this is critical to have?  Wondering if we could (for the upcoming) release stick to the old (users can change the configuration if desired), and look further for the release after?

Not critical, but let's change the default from the beginning of the support of cgroup v2 to minimize confusion.

> what's the result of running cgroupfs when cgroups v2 is used? Is it non-functional, or "works" ?

Works on rootful, non-functional on rootless as in v1.

> You mention it's always preferred to use systemd cgroups in that case; we were wondering "why"

Mostly for supporting cgroup in rootless, but even for rootful, cgroupfs driver is kinda invading systemd's "soveignty"

**Comment by AkihiroSuda** [comment]
cc @kolyshkin @giuseppe @filbranden @lifubang

**Comment by AkihiroSuda** [comment]
@tianon @thaJeztah WDYT?

**Comment by tianon** [comment]
Aren't there still some features which aren't yet supported for cgroupv2?  What happens when a user tries to use those with this implementation (with or without a hybrid setup)?

**Comment by AkihiroSuda** [comment]
@tianon `--kernel-memory` and `--oom-kill-disable` are not supported (because kernel doesn't support them). These flags are ignored with `WARNING` logs on client side. The "hybrid" mode is almost meaningless and just treated as legacy in Moby.

**Comment by tianon** [comment]
Ok, seems sane to me :+1:

(however, I think there are more folks who have been CC'd here who ought to / I'd like to see weigh in :sweat_smile:)

**Comment by giuseppe** [comment]
it looks like a good idea, especially for enabling rootless

**Comment by filbranden** [comment]
+1, I agree. systemd cgroup driver should be the default for cgroup2 hosts. Thanks for sending a PR to make that so, @AkihiroSuda !

**Comment by AkihiroSuda** [comment]
@tianon @thaJeztah LGTY?

**Review by tianon — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
SGTM

@dmcgowan @tonistiigi PTAL (you ok with this?)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
