### PR TITLE
Fix swagger volume type generation

### PR DESCRIPTION
**Pull request by cpuguy83**
This was broken by bf6a790f00ab96bb8857e3c73502909ee5e36217

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
😡

**Comment by dnephin** [comment]
I would just add it to the exclude list in `hack/validate/gometalinter.json`, like we did for container

**Comment by cpuguy83** [comment]
Fixed.

**Review by thaJeztah — APPROVED** [review]
still LGTM (if green)

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
