### PR TITLE
bump containerd to 1137bf2ba633587aa5d8ce41862c3306519f074b

### LINKED ISSUE #28821: stop container show "containerd: deleting container                error=exit status 1" in daemon log
**Description**
stop a container, there will be a *Error* log in the daemon log.
`````
$ docker run -ti busybox
/ # exit
$
`````
````
DEBU[0013] containerd: process exited                    id=92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65 pid=init status=0 systemPid=32534
ERRO[0013] containerd: deleting container                error=exit status 1: "container 92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65 does not exist\none or more of the container deletions failed\n"
DEBU[0013] libcontainerd: received containerd event: &types.Event{Type:"exit", Id:"92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65", Status:0x0, Pid:"init", Timestamp:(*timestamp.Timestamp)(0xc420dab850)}

````

**Steps to reproduce the issue:**
1. start a container
2. stop a container
3. check the daemon log

**Describe the results you received:**
There is a error log in daemon log say `containerd: deleting container                error=exit status 1: "container 92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65 does not exist\none or more of the container deletions failed\n"`

**Describe the results you expected:**
There should be no error log if the container stop normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   03ba9a4
 Built:        Fri Nov 25 03:23:12 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          03ba9a4
 Built:               Fri Nov 25 03:23:12 2016
 OS/Arch:             linux/amd64
 Experimental:        false

```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 4
Server Version: 1.14.0-dev
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: r1keowap3efura5ce9s0n3450
 Is Manager: true
 ClusterID: prthuhirjmtd28v0spdkq7fv9
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.175.125.216
 Manager Addresses:
  10.175.125.216:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: a6e649f5835b7ebf354a73ff3a80f3223e3cb5de (expected: 51371867a01c467f08af739783b8beafc154c4d7)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.3.0
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.859 GiB
Name: centos
ID: OHKU:Z55T:2FD6:U7OF:BPAP:V7WE:JVLN:RJIK:SUR4:PE5E:PJCQ:B3QW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 126
 System Time: 2016-11-24T22:28:43.236602291-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ping @mlaventure

### LINKED ISSUE #30156: container output becomes windows-ised
**Description**
If we running a container with a tty(-t/--tty), the output gets a `\n` translated to `\r\n` on output.This happens for both `docker run` and `docker exec`.

```
# docker run -t ubuntu:latest echo hello | cat -v
hello^M
# docker run -tid ubuntu:latest 
845634fb34f7d91112680303f302905ca260f7101e4f1305155476537e65a02e
# docker exec -t 845634fb34f7d91112680303f302905ca260f7101e4f1305155476537e65a02e echo hello | cat -v
hello^M
```

**Steps to reproduce the issue:**
1. use the latest docker
2. run a container with `-t/-tty`

```
 docker run -t ubuntu:latest echo hello | cat -v
```

**Describe the results you received:**

```
# docker run -t ubuntu:latest echo hello | cat -v
hello^M
```

**Describe the results you expected:**
```
# docker run -t ubuntu:latest echo hello | cat -v
hello
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   1eafa0f
 Built:        Sat Jan 14 03:08:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   1eafa0f
 Built:        Sat Jan 14 03:08:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by thaJeztah**
diff is
https://github.com/docker/containerd/compare/03e5862ec0d8d3b3f750e19fca3ee367e13c090e...1137bf2ba633587aa5d8ce41862c3306519f074b

includes https://github.com/docker/containerd/pull/371, https://github.com/docker/containerd/pull/436, https://github.com/docker/containerd/pull/428

fixes https://github.com/docker/docker/issues/30156
fixes https://github.com/docker/docker/issues/28821
addresses https://github.com/docker/docker/issues/30026

not sure if it "closes" the last one, @mlaventure? (oops, sorry for the wrong ping @mlarcher)

### CODE REVIEW

**Comment by datawolf** [comment]
With the patch https://github.com/docker/containerd/commit/717679b7ad0fbc5a9b3b3ffc8b0d1b1d543a301b which fix `^M` issue, the output of `docker run` is confusing when we running a container with `tty(-t/--tty)` and `-i(--interactive)`, it looks like: 

```
$ docker run -ti hello-world

Hello from Docker!
                  This message shows that your installation appears to be working correctly.
				  
                                                                                            To generate this message, Docker took the following steps:
                                                                                                                                                      1. The Docker client contacted the Docker daemon.
                                                  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
                                                                                                                           3. The Docker daemon created a new container from that image which runs the
                                                    executable that produces the output you are currently reading.
                                                                                                                   4. The Docker daemon streamed that output to the Docker client, which sent it
                                              to your terminal.

                                                               To try something more ambitious, you can run an Ubuntu container with:
                                                                                                                                      $ docker run -it ubuntu bash

            Share images, automate workflows, and more with a free Docker Hub account:
                                                                                       https://hub.docker.com

                                                                                                             For more examples and ideas, visit:
                                                                                                                                                 https://docs.docker.com/engine/userguide/

```

But when we use `docker run -t hello-world`(without `-i(--interactive)`) to running a container, the output is correct. 

With `-i(--interactive)`, the terminal will be set to raw mode, which `\n` can not set the column to zero.

Does anyone knows how to fix this issue?

**Comment by coolljt0725** [comment]
@thaJeztah   yes, this could close #28821

**Comment by mlaventure** [comment]
This can't be merged until we fix the terminal output, I've added my point of view to the issue that lead to that change in containerd: https://github.com/docker/docker/issues/30156#issuecomment-273522133

**Comment by justincormack** [comment]
@thaJeztah shall we close this until the terminal issue is resolved?

**Comment by thaJeztah** [comment]
Yes, let's close this one. I can create another PR that includes just the fixes for https://github.com/docker/docker/issues/28821

**Pull request closed without merging**
