### PR TITLE
add more logs for api server

### LINKED ISSUE #11618: The docker api logs are lacking and can be verbose and not useful
**Problem**
 
The docker api logs are lacking and can be verbose and not useful.
 
**Solution**
 
Review the logging calls in https://github.com/docker/docker/tree/master/api/server and use our standard log package `github.com/Sirupsen/logrus` to make meaningful log messages.
 
It could be helpful to remove all existing log calls and then go through and log meaning requests, warnings, errors, and debug messages for the API.

### PR DESCRIPTION
**Pull request by wonderflow**
Mainly add error logs.

Closes #11618

Please check and tell me if there's anything I missed.

Signed-off-by: Sun Jianbo wonderflow@zju.edu.cn

### CODE REVIEW

**Comment by HuKeping** [comment]
hi @wonderflow, actually we prefer `logrus` without the alias `log`

**Comment by wonderflow** [comment]
@HuKeping Thanks!

**Comment by cpuguy83** [comment]
I'm not sure that I like this.
If the function is returning an error, than the caller should be handling logging.

**Comment by wonderflow** [comment]
@cpuguy83 What do you suggest then? I'll be appreciate if you could give some advices. Thanks.

**Comment by cpuguy83** [comment]
For instance, right now with this PR here is the logging (server only) for when you try to pause an already paused container:

```
root@c7be71460a24:/go/src/github.com/docker/docker# docker pause test > /dev/null 2>&1
DEBU[0659] Calling POST /containers/{name:.*}/pause
INFO[0659] POST /v1.19/containers/test/pause
ERRO[0659] Can not pause conatiner test: Container 9c087258866d2303056b5aa084efff9761165f379a09fc453efc38df668e81da is already paused
ERRO[0659] Handler for POST /containers/{name:.*}/pause returned error: Cannot pause container test: Container 9c087258866d2303056b5aa084efff9761165f379a09fc453efc38df668e81da is already paused
ERRO[0659] HTTP Error: statusCode=500 Cannot pause container test: Container 9c087258866d2303056b5aa084efff9761165f379a09fc453efc38df668e81da is already paused
```

But on master it's:
```
root@d823aa94a1de:/go/src/github.com/docker/docker# docker pause test > /dev/null 2>&1
DEBU[0037] Calling POST /containers/{name:.*}/pause
INFO[0037] POST /v1.19/containers/test/pause
ERRO[0037] Handler for POST /containers/{name:.*}/pause returned error: Cannot pause container test: Container 3b186301d71f4a1e4ff1599c03a32cfddc2bf74e49216fe5860e5f081c7238f0 is already paused
ERRO[0037] HTTP Error: statusCode=500 Cannot pause container test: Container 3b186301d71f4a1e4ff1599c03a32cfddc2bf74e49216fe5860e5f081c7238f0 is already paused
```

**Comment by wonderflow** [comment]
So, we actually don't need to add log for error, as functions in api/server.go are all called by others.

What I need to do is to figure out where to add "warning" and "debug" . Am I right?

**Comment by icecrime** [comment]
I agree with @cpuguy83 here: those errors are already logged by the caller, so the additional logs don't display any new information. I'm going to close this, but feel free to keep discussing here if you feel we're missing something.

**Comment by thaJeztah** [comment]
@icecrime @cpuguy83 Is this *implementation* not the right one, or is the issue it's trying to revolve (https://github.com/docker/docker/issues/11618) not an actual issue?

If the latter, then https://github.com/docker/docker/issues/11618 can be closed, right?

**Pull request closed without merging**
