### PR TITLE
Carry 25001: Add container labels to service create/update

### PR DESCRIPTION
**Pull request by tiborvass**
Carrying #25001

Rebased and fixed a panic.

Closes #25001

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Really strange:
```
--- FAIL: TestParseWords (0.00s)
02:38:43 	parser_test.go:124: length check failed. input: foo\ bar, expect: [foo\ bar], output: [foo\ bar]
```

**Comment by mlaventure** [comment]
@cpuguy83 this one has been flaky lately, I think @tonistiigi determined it came after the change to add the escape handling to the Dockerfile.

Basically, the test fail if another test initializing the global variable is not run first. Can't remember which variable though and @tonistiigi is on leave atm.

**Comment by tiborvass** [comment]
@cpuguy83 @mlaventure yes, I restarted it since and it passed so we're good :)

**Comment by mlaventure** [comment]
LGTM

On another note, I know I'm late to the party, but just wondering, regarding the confusion between service labels and container labels, did we consider using the term `tags` for the services instead?

**Comment by stevvooe** [comment]
> did we consider using the term tags for the services instead?

No and this would cause a ton of confusion.

The main confusion here is that we have introduced a new concept and need to teach people about. Services and containers are separate objects and we need to pound this home, as it is powerful.

Perhaps, inheritance of labels is the right behavior but that is not something we can go back from.

LGTM

**Comment by tiborvass** [comment]
Was hitting #24590, merging.

**Pull request merged**
