### PR TITLE
[v1.13] vendor: update runc to 2f7393a4

### PR DESCRIPTION
**Pull request by tonistiigi**
https://github.com/docker/runc/compare/51371867a01c467f08af739783b8beafc154c4d7...2f7393a47307a16f8cee44a37b262e8b81021e3e

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
@LK4D4 vndr doing something wrong here. `nsenter` shouldn't be a vendored dependency of docker.

**Comment by LK4D4** [comment]
Vndr just saves all c files in case if some cgo uses them(it is the case with sqlite). Not a big deal I think :)

**Comment by vieux** [comment]
SGTM test error unrelated

**Comment by vieux** [comment]
ping @mlaventure @tonistiigi @crosbymichael please merge as soon as it looks good to you we we can kick off the rc6 builds

**Review by justincormack — APPROVED** [review]

**Review by justincormack — APPROVED** [review]

**Comment by mlaventure** [comment]
LGTM

**Pull request merged**
