### PR TITLE
vendor: remove unused package

### PR DESCRIPTION
**Pull request by tonistiigi**
last import removed in #33665

@tiborvass 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by tiborvass** [comment]
`-444` lines... it's a curse :P

LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
frozen images...

**Comment by aaronlehmann** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
