### PR TITLE
Respect --bridge=none

### LINKED ISSUE #26071: -b none ignored on daemon start-up if a bridge was previously defined
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: hyperion-xenial
ID: 2JRO:CZ2K:3QQ7:M6FE:L537:EYG7:FZVW:RJOO:ZVVW:GB6C:VC35:OMUZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Confirmed on both physical and VirtualBox

**Steps to reproduce the issue:**

1. Install docker-engine on Ubuntu Xenial/16.04 which causes it to autostart
2. Add a systemd drop-in that disables the bridge, e.g. /etc/systemd/system/docker.service.d/nobridge.conf

    ```
    [Service]
    ExecStart=
    ExecStart=/usr/bin/docker daemon -H fd:// -b none
    ```

3. Reload systemd config and restart Docker.

**Describe the results you received:**
The docker0 bridge is still present and persists across reboots

**Describe the results you expected:**
In previous versions (I believe as late as 1.11) the docker0 bridge would disappear once the `-b none` flag was added to the daemon start-up

**Additional information you deem important (e.g. issue happens only occasionally):**
It appears that the docker0 bridge information gets stored in the network key/value store on the intitial installation start-up and Docker will bring the bridge up on later restarts even if the `-b none` flag is present.  I can get the old/desired behavior by stopping Docker, deleting /var/lib/docker/network/files/local-kv.db, and rebooting the machine.  Instead of rebooting, I can also manually delete docker0 using brctl  and then start Docker.

### PR DESCRIPTION
**Pull request by aboch**
If daemon is started with `--bridge=none`:
- Do not create the default "bridge" network
- Get rid of the docker0 bridge if present

Fixes #26071

### CODE REVIEW

**Comment by thaJeztah** [comment]
@aboch IIRC correctly, this was a regression in 1.12

ping @vieux FYI

**Comment by aboch** [comment]
@thaJeztah Actually no, I see the wrong behavior with docker 1.11.2.

**Comment by thaJeztah** [comment]
Oh, thanks, I must've mixed up the numbers then

**Comment by tonistiigi** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
