### PR TITLE
WIP: Join api

### PR DESCRIPTION
**Pull request by ibuildthecloud**
Adds `/join` API and `docker join` command.  This allows a running Docker Engine to dynamically join a cluster.  This introduces a new file `/var/lib/docker/discovery/config.json` in which the state is persisted for the discovery info.

This PR is based on https://github.com/docker/docker/pull/16229 and additionally needs more changes from @mavenugo for network integration before this can be merged.  I'm posting this now to see if the initial approach seems fine.  Changes are in https://github.com/docker/docker/commit/ca5e03bd73e0ad4fef233edf4c024331800c6f82

Fixes: https://github.com/docker/docker/issues/16416

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@abronan What do you suggest should change?  Basically this PR allows you to set discovery address, backend, and kv store as three separate and individual configurable parameter.  The only way they are associated is just that they all must be set in one atomic operation.

**Comment by aluzzardi** [comment]
@ibuildthecloud Not sure how I feel about this one.

I see the use case, but I think it's a workaround the fact we don't have a configuration file nor a dynamic way to update it.

Thoughts? /cc @icecrime

**Comment by ibuildthecloud** [comment]
@aluzzardi I definitely understand that sentiment, it would be great to have a configuration file, but I think this does address a different concern.  In the ideal world I should be able to dynamic join and leave a cluster.  This is quite common in clustered systems.  I view this as just a first step, eventually this should be fully dynamic, right now we compromise on the semi-static approach proposed here.

Even if you had a configuration file, it actually doesn't help me.  A real use case is this.  I work with plenty of companies where configuration management is managed by a central team.  So they have corporate wide standard puppet modules, or whatever CM framework.  As soon as you have to edit a configuration file it becomes this massive battle because you now need to talk to another team for them to update puppet to manage the config.  Something like this is impossible because what is the value you tell puppet team to put as "discovery backend".  It just becomes a nightmare.  It's much better to be able to specify this information after the fact in an API/CLI call.

**Comment by cpuguy83** [comment]
+1 to @ibuildthecloud's comment.

**Comment by LK4D4** [comment]
@ibuildthecloud now `pkg/discovery` stuff was merged. We can rebase and reduce patch size.
btw design sounds ok for me

**Comment by thaJeztah** [comment]
ping @ibuildthecloud :-) https://github.com/docker/docker/pull/16455#issuecomment-150630503

**Comment by aluzzardi** [comment]
If we add this to the API, then we are stuck with the current implementation

**Comment by thaJeztah** [comment]
Ping @aluzzardi @abronan I see the Swarm team has objections against this PR; how should we proceed here? Is there a counter-proposal that would get this going, or do we have to reject this?

**Comment by calavera** [comment]
> I see the use case, but I think it's a workaround the fact we don't have a configuration file nor a dynamic way to update it.

We've expressed interest in having a dynamic configuration file for 1.10. As discussed in a previous maintainers meeting, we decided that that's a best first step than adding a new api endpoint, although we don't discard adding that endpoint in the future if it's still necessary. I think we should close this PR.

For reference, see #17559 for the configuration proposal.

**Comment by thaJeztah** [comment]
@ibuildthecloud Following the discussion above, I'm going to go ahead and close this while https://github.com/docker/docker/issues/17559 is being worked on as a first step. We do want to be able to change settings on a running daemon eventually, but we decided to work on a configuration file first, and work from that, so I think this should be closed for now. Also see https://github.com/docker/docker/issues/17560 for an API proposal

**Pull request closed without merging**
