### PR TITLE
Soften limitation of update kernel memory

### PR DESCRIPTION
**Pull request by hqhq**
**\- What I did**

Soften the limitation of update kernel memory, allow to update kernel memory of a running container if the container initialized kernel memory when it's started.

**\- How I did it**

Remove limitation in Docker (we already have runc supported this) and update docs and test cases.

**\- How to verify it**

```
# docker run -ti --name test --kernel-memory 50M ubuntu bash
(switch to another terminal with this container running)
# docker update --kernel-memory 100M test
(This should succeed)
```

**\- Description for the changelog**

Kernel memory is not allowed to be updated if container is
running, it's not actually a precise kernel limitation.

Before kernel version 4.6, kernel memory will not be accounted
until kernel memory limit is set, if a container created with
kernel memory initialized, kernel memory is accounted as soon
as process created in container, so kernel memory limit update
is allowed afterward. If kernel memory is not initialized,
kernel memory consumed by processes in container will not be
accounted, so we can't update the limit because the account
will be wrong.

So update kernel memory of a running container with kernel memory
initialized is allowed, we should soften the limitation by docker.

**\- A picture of a cute animal (not mandatory but encouraged)**

image

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
sgtm

**Comment by justincormack** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
@hqhq can you also update the online docs; https://github.com/docker/docker/blob/master/docs/reference/commandline/update.md ?

**Comment by hqhq** [comment]
@thaJeztah Updated.

**Comment by SvenDowideit** [comment]
Docs LGTM

**Comment by thaJeztah** [comment]
docs LGTM, thanks!

**Pull request merged**
