### PR TITLE
Finally remove our copy of "archive/tar" now that Go 1.4 is the minimum!

### PR DESCRIPTION
**Pull request by tianon**
IT'S ABOUT TIME. :tada:

### CODE REVIEW

**Comment by tianon** [comment]
I can barely even remember back to a time when we weren't forking or vendoring `archive/tar`! :joy:

**Comment by tianon** [comment]
ec61c46bf73b8c727fe8de1982d86a1417a8a0c4 is the oldest "use a different `archive/tar`" commit I can find :heart:

**Comment by LK4D4** [comment]
LGTM

**Comment by tianon** [comment]
b762d3a7391dd526826a0a1f1c983ea5e54852f5 is when we first officially vendored it

**Comment by jfrazelle** [comment]
omg LGTM

**Comment by jfrazelle** [comment]
omg omg omg omg

**Comment by jfrazelle** [comment]
```
$ git diff --shortstat origin/release..origin/master
 736 files changed, 39777 insertions(+), 27858 deletions(-)
```

**Pull request merged**
