### PR TITLE
vendor: github.com/tonistiigi/fsutil

### PR DESCRIPTION
**Pull request by thaJeztah**
- follow-up to https://github.com/moby/moby/pull/44226
- depends on https://github.com/tonistiigi/fsutil/pull/136
- depends on https://github.com/moby/buildkit/pull/3144

testing if all works combined

### CODE REVIEW

**Comment by thaJeztah** [comment]
okay; looks like the BuildKit version we use is not yet compatible with the latest `tonistiigi/fsutil`

```
vendor/github.com/moby/buildkit/session/filesync/filesync.go:112:20: cannot use dir.Map (variable of type func(string, *types.Stat) bool) as type fsutil.MapFunc in struct literal
```

**Comment by thaJeztah** [comment]
Hmm... dang; this doesn't work it looks like 🤔 ;

```
#40 44.74 vendor/github.com/moby/buildkit/client/workers.go:20:18: undefined: BuildkitVersion
#40 44.74 vendor/github.com/moby/buildkit/client/workers.go:44:21: undefined: fromAPIBuildkitVersion
```

**Comment by thaJeztah** [comment]
Nevermind 🤦 didn't stage a new file that was vendored

**Comment by thaJeztah** [comment]
This one is still failing; perhaps missing a `skip` ?

```
=== CONT  TestIntegration/TestNamedImageContextPlatform/worker=dockerd/frontend=client
2022/10/04 12:47:46 http2: server connection error from localhost: connection error: PROTOCOL_ERROR
    dockerfile_test.go:5480: 
        	Error Trace:	dockerfile_test.go:5480
        	            				run.go:87
        	            				run.go:201
```

**Comment by thaJeztah** [comment]
Or the Version changes cause the error 🤔 (`PROTOCOL_ERROR`)

**Comment by thaJeztah** [comment]
Okay, different error now, but still failing (so probably we're still missing a "skip" in BuildKit);


```
=== CONT  TestIntegration/TestNamedImageContextPlatform/worker=dockerd/frontend=builtin
    dockerfile_test.go:5480: 
        	Error Trace:	dockerfile_test.go:5480
        	            				run.go:87
        	            				run.go:201
        	Error:      	Received unexpected error:
        	            	exporter "image" could not be found
        	            	github.com/moby/buildkit/util/stack.Enable
        	            		/src/util/stack/stack.go:77
        	            	github.com/moby/buildkit/util/grpcerrors.FromGRPC
        	            		/src/util/grpcerrors/grpcerrors.go:188
        	            	github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor
        	            		/src/util/grpcerrors/intercept.go:41
        	            	google.golang.org/grpc.(*ClientConn).Invoke
        	            		/src/vendor/google.golang.org/grpc/call.go:35
        	            	github.com/moby/buildkit/api/services/control.(*controlClient).Solve
        	            		/src/api/services/control/control.pb.go:1443
        	            	github.com/moby/buildkit/client.(*Client).solve.func2
        	            		/src/client/solve.go:209
        	            	golang.org/x/sync/errgroup.(*Group).Go.func1
        	            		/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1594
        	            	failed to solve
        	            	github.com/moby/buildkit/client.(*Client).solve.func2
        	            		/src/client/solve.go:222
        	            	golang.org/x/sync/errgroup.(*Group).Go.func1
        	            		/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1594
        	Test:       	TestIntegration/TestNamedImageContextPlatform/worker=dockerd/frontend=builtin
    sandbox.go:234: stdout: /usr/bin/dockerd
    sandbox.go:234: stderr: /usr/bin/dockerd
    sandbox.go:237: > startCmd 2022-10-04 14:04:46.779800658 +0000 UTC m=+106.006244030 [/usr/bin/dockerd --data-root /tmp/integration3653410606/dwm18pdoda08r/root --exec-root /tmp/dxr/dwm18pdoda08r --pidfile /tmp/integration3653410606/dwm18pdoda08r/docker.pid --host unix:///tmp/integration3653410606/dwm18pdoda08r/docker.sock --userland-proxy=false --containerd-namespace dwm18pdoda08r --containerd-plugins-namespace dwm18pdoda08rp --bip 10.66.66.1/24 --default-address-pool base=10.66.66.0/16,size=24 --debug]
```

**Comment by crazy-max** [comment]
> Okay, different error now, but still failing (so probably we're still missing a "skip" in BuildKit);

Will be fixed by https://github.com/moby/buildkit/pull/3176

**Pull request closed without merging**
