### PR TITLE
[20.10] vendor: github.com/moby/buildkit eeb7b65ab7d651770a5ec52a06ea7c96eb97a249 (v0.8 branch)

### PR DESCRIPTION
**Pull request by crazy-max**
* https://github.com/moby/buildkit/pull/3186

- fixes https://github.com/moby/moby/issues/42261
- fixes https://github.com/docker/for-win/issues/10839

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@crazy-max looks like some additional packages have to be pulled into vendor;

```

[2022-10-20T22:24:32.383Z] vendor/github.com/moby/buildkit/util/progress/logs/logs.go:13:2: cannot find package "github.com/armon/circbuf" in any of:
[2022-10-20T22:24:32.383Z] 	/go/src/github.com/docker/docker/vendor/github.com/armon/circbuf (vendor tree)
[2022-10-20T22:24:32.383Z] 	/usr/local/go/src/github.com/armon/circbuf (from $GOROOT)
[2022-10-20T22:24:32.383Z] 	/go/src/github.com/armon/circbuf (from $GOPATH)
```

**Comment by crazy-max** [comment]
Ahhh indeed I was still in the go modules world my bad.

**Comment by thaJeztah** [comment]
I think usually it adds them with `vndr` as well, unless it's a new dependency, but yeah.. 😂

**Comment by crazy-max** [comment]
> I think usually it adds them with `vndr` as well, unless it's a new dependency, but yeah.. 😂

Yes was a new one

**Comment by thaJeztah** [comment]
Failures will be fixed once https://github.com/moby/moby/pull/44340 is merged

**Comment by thaJeztah** [comment]
_Almost_ green now; wondering if it would be newline or whitespace changes. Let me try to run a vendor on this branch;

```
 The result of vndr differs
 
  M vendor/github.com/armon/circbuf/LICENSE
 
 Please vendor your package with github.com/LK4D4/vndr.
```

**Comment by thaJeztah** [comment]
ah!

```
git diff
diff --git a/vendor/github.com/armon/circbuf/LICENSE b/vendor/github.com/armon/circbuf/LICENSE
old mode 100644
new mode 100755
```

**Review by thaJeztah — APPROVED** [review]
all green now, thanks!

LGTM

**Pull request merged**
