### PR TITLE
Fix typo in deprecation doc

### PR DESCRIPTION
**Pull request by duglin**
thanks @tiborvass

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by tiborvass** [comment]
@duglin might as well fix `s/replace/replaced/` somewhere in there :)

**Comment by duglin** [comment]
@tiborvass took me a while to realize you were talking about a different file   ;-)  but I did find it.  thanks!

**Comment by tiborvass** [comment]
lol sorry! LGTM

**Comment by SvenDowideit** [comment]
LGTM

**Comment by estesp** [comment]
LGTM

**Pull request merged**
