### PR TITLE
Increase flaky test sleep, replace deprecated assert

### LINKED ISSUE #47590: Flaky test: TestNewClientWithTimeout
### Description

```
=== FAIL: github.com/docker/docker/pkg/plugins TestNewClientWithTimeout (0.03s)
    client_test.go:167: started remote plugin server listening on: http://127.0.0.1:49311/
    client_test.go:180: assertion failed: error is nil, not os.IsTimeout
```

### docker version

```bash
master @ 23e1af45c67b6931d4942c73652bb9883fe499d8
```

### PR DESCRIPTION
**Pull request by adams1mon**
**- What I did**
- tried to fix #47590
- increased mock handler processing time to 50ms to try to prevent it from finishing before the 10ms client timeout occurs
- replaced deprecated error type assertion

**- How I did it**
- I tried to run the test with increasingly close processing and timeout times, flakiness occurred when the timeout and processing times were ~5ms apart ***on my machine***

**- How to verify it**
- I really don't know

**- Description for the changelog**

```markdown changelog

```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vvoland — COMMENTED** [review]
Thanks for picking this up!

For verifying whether the test is still flaky - you could add a new temporary commit that would modify the code so that the test code is ran like x100 times:

```go
func TestNewClientWithTimeout(t *testing.T) {
    t.Parallel()
    for i := 0; i < 100; i++ {
        t.Run(strconv.Itoa(i), func(...) {
           <test body...>
        }
    }
}

**Comment by adams1mon** [comment]
Modified it to run the test 100 times. I also ran it with go test -count 100 multiple times to see if it fails, it seemed fine.

**Comment by vvoland** [comment]
Closing and reopening to re-run the CI.

**Review by vvoland — COMMENTED** [review]
LGTM (after removing the last commit 😄)

**Comment by adams1mon** [comment]
Reverted the last commit, I hope the test won't fail anymore. I don't really know why it was failing in the first place, maybe the timeouts aren't that accurate and some additional waiting happens somewhere when the system is under load? 
Although I think the millisecond range is pretty large for this kind of error to occur.

**Comment by adams1mon** [comment]
The changed test passed, but some networkdb test (TestNetworkDBIslands) failed :(

**Comment by vvoland** [comment]
The networkdb test is a known flaky, don't worry about it.

As for removing the commit - instead of reverting it with another commit, you can just remove it so the PR has only the first commit. You can do that with `git rebase` or `git reset` and then force push to the branch PR.

**Comment by adams1mon** [comment]
Done (I thought the commits would be squashed on merge)

**Review by vvoland — APPROVED** [review]
LGTM

**Pull request merged**
