### PR TITLE
1.10.3 cherrypicks

### PR DESCRIPTION
**Pull request by tiborvass**
Please provide the following information:
- What did you do?

I cherrypicked: #20981 #20834 #20831 #20737 #20706 #20636 #20725 #20729 #20672 #20682 #20685 #20680 #20647 #20417 #20967 #20697 
- How did you do it?

`git cherry-pick -x origin/pull/$pr` + resolving conflicts
- How do I see it or verify it?

Read each commit and make sure all commits from the PRs are here. There should be exceptionally one commit per PR this time.

Especially review: f05d42ee03aa48a9852a316857a0ea8677869618 and ac47ad8ea4a281e81276e74d1a0bbaaa2a1f45f9 for which I needed to resolve not-that-trivial conflicts.
- A picture of a cute animal (not mandatory but encouraged)

Vizsla

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM :smile:

**Comment by aaronlehmann** [comment]
LGTM

**Comment by tiborvass** [comment]
For the record: https://jenkins.dockerproject.org/job/Docker-PRs-Win2Lin/22836/console

**Comment by thaJeztah** [comment]
win2lin ran into https://github.com/docker/docker/issues/18672 (see https://jenkins.dockerproject.org/job/Docker-PRs-Win2Lin/22861/console)

```
05:50:14 FAIL: docker_cli_stats_test.go:94: DockerSuite.TestStatsAllNewContainersAdded
05:50:14 
05:50:14 docker_cli_stats_test.go:126:
05:50:14     c.Fatal("failed to observe new container created added to stats")
05:50:14 ... Error: failed to observe new container created added to stats
```

**Comment by tiborvass** [comment]
windowsTP4 is expected to fail on the 1.10 branch.
win2lin passed except for TestStatsAllNewContainersAdded as mentioned above, which wasn't fixed, only skipped for now. I could have cherrypicked #20817 but since CI is having a lot of issues right now and that PR only changes test code, we're merging this.

**Comment by thaJeztah** [comment]
> but since CI is having a lot of issues right now and that PR only changes test code, we're merging this.

LGTM

**Comment by tiborvass** [comment]
For the record 3 commits from this PR were reverted in #21068.

**Pull request merged**
