### PR TITLE
Fix LXC stop signals

### LINKED ISSUE #12859: TestWaitBlockedExitRandom broken on lxc
fix this test so it works on lxc

```

----------------------------------------------------------------------
FAIL: docker_cli_wait_test.go:109: DockerSuite.TestWaitBlockedExitRandom

docker_cli_wait_test.go:131:
    c.Fatalf("expected exit 99, got %s", status)
... Error: expected exit 99, got 0

```

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #12859

`lxc-stop` does not support sending arbitrary signals.
By default, `lxc-stop -n <id>` would send `SIGPWR`.
The lxc driver was always sending `lxc-stop -n <id> -k`, which always
sends `SIGKILL`. In this case `lxc-start` returns an exit code of `0`,
regardless of what the container actually exited with.
Because of this we must send signals directly to the process when we
can.

Also need to set quiet mode on `lxc-start` otherwise it reports an error
on `stderr` when the container exits cleanly (ie, we didn't SIGKILL it),
this error is picked up in the container logs... and isn't really an
error.

Also cleaned up some potential races for waitblocked test.

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @jfrazelle @ashahab-altiscale

**Comment by ashahab-altiscale** [comment]
@cpuguy83 This is great, thanks for the patch.
Why is the test timing out?

**Comment by cpuguy83** [comment]
Good question, need to figure out which one it's choking on.

**Comment by cpuguy83** [comment]
Found it, sending SIGKILL to lxc-start was causing it to hang, however using lxc-stop seems to be OK.
So made it use lxc-stop when sig is 9.

**Comment by LK4D4** [comment]
LGTM

**Comment by ashahab-altiscale** [comment]
LGTM. And thanks.

**Pull request merged**
