### PR TITLE
Vendor distribution to correct config blob media type in schema2 manifest

### PR DESCRIPTION
**Pull request by aaronlehmann**
@nwt noticed that the media type specified in the config section of a
schema2 manifest is application/octet-stream, instead of the correct
value application/vnd.docker.container.image.v1+json.

This brings in https://github.com/docker/distribution/pull/1622 to fix
this.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
@dmp42 inquired about getting this into 1.11. It fixes a spec compliance issue with the manifests generated by `docker push`. There are no user-facing problems with the manifests that reference the incorrect content type, but it would be nice if 1.11 produced manifests without this deviation from the spec. If it's too late for 1.11, nothing especially bad will happen.

ping @icecrime

**Comment by calavera** [comment]
I'm pretty sure it's too late. But I'll leave it up to others.

Change LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
if it's not strictly needed, I prefer to skip this for 1.11.0 indeed; we may reconsider for a patch release, but also if needed

**Comment by thaJeztah** [comment]
ping @mlaventure @tiborvass think we can include this into 1.11.1?

**Comment by mlaventure** [comment]
I'd say it's a good candidate, yes.

**Comment by thaJeztah** [comment]
let me add it; we can go through the milestone if we decide to do a 1.11.1

**Pull request merged**
