### PR TITLE
Fix checkpoint's exiting semantics.

### PR DESCRIPTION
**Pull request by bjbroder**
Previously, dockerd would always ask containerd to pass --leave-running
to runc/runsc, ignoring the exit boolean value. Hence, even `docker
checkpoint create --leave-running=false ...` would not stop the
container.

Signed-off-by: Brielle Broder <bbroder@google.com>

### CODE REVIEW

**Comment by hugelgupf** [comment]
cc @hugelgupf @nlacasse

**Comment by hugelgupf** [comment]
The docker jenkins seems to be failing for now good reason?

```
01:07:11 W: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/stretch/InRelease  Could not resolve 'cdn-fastly.deb.debian.org'
```

**Comment by hugelgupf** [comment]
friendly ping

**Comment by hugelgupf** [comment]
cc @cpuguy83 maybe?

**Comment by cpuguy83** [comment]
Can we add an integration test for this?

**Comment by hugelgupf** [comment]
@cpuguy83 I'd like to, but we've actually had trouble getting this to work with runc (we're using runsc instead). Are there existing integration tests somewhere that we can build off of?

**Comment by avagin** [comment]
Actually, there is one more problem. Docker (containerd) has to call "runc checkpoint" with "--empty-ns network" to dump a docker container.

I have a patch which fixes both these issues:

https://github.com/avagin/docker-ce/commit/911c89fcae200ae1df56b2f8d4ed300e62df334a#diff-e1f8834158a9117cafe1744dc2c7adb2

But it depends on containerd changes:
https://github.com/containerd/containerd/pull/2425

**Comment by kolyshkin** [comment]
I like @avagin approach better (i.e. appending to options if necessary).

**Comment by hugelgupf** [comment]
Sure, we can append to options.

Having to call with an empty NS is specific to runc. runsc does not need to be called with that. Can this be part of something runc-specific?

**Comment by avagin** [comment]
@hugelgupf Here are changes which resolve the issue with an empty NS .
https://github.com/opencontainers/runc/pull/1840

**Comment by bjbroder** [comment]
@kolyshkin @avagin cpuguy wanted an integration test, but it seems like there are none for moby checkpoint/restore already? Is there anything y'all have we can contribute to?

**Comment by hugelgupf** [comment]
Ping

**Comment by avagin** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :frog: 
cc @mlaventure @thaJeztah

**Review by mlaventure — APPROVED** [review]
LGTM

z failure is unrelated

**Comment by tswift242** [comment]
@bjbroder This restores the behavior of making --leave-running configurable, but is the default still true? The default used to be false.

**Comment by bjbroder** [comment]
@tswift242 The default for leave running was, and still is, false. Previously, both the default (false) and explicitly setting the flag to false would incorrectly continue running after checkpointing because "exit" had not been implemented appropriately, even though the leave-running flag is correctly set. 

The leave-running flag's behavior can be seen in:  docker-ce/components/cli/cli/command/checkpoint/create.go

**Comment by tswift242** [comment]
Gotcha. Thanks for the reply and the fix to this issue!

**Pull request merged**
