### PR TITLE
Downgrade to Go 1.5.3.

### LINKED ISSUE #20865: Pre-golang 1.6 Dockers can't talk to golang 1.6 Docker
When Docker v1.9 (and before) talks to Docker v1.11 (master) via a unix socket the daemon will reject the request with this error:
```
Error response from daemon: 400 Bad Request: malformed Host header
```

I believe this is because the HTTP Host header will have a value of: `/var/run/docker.sock` which isn't a valid hostname and I believe golang 1.6 is now checking the value in validHostHeader() (in https://golang.org/src/net/http/request.go) and "/" isn't a valid char.

In Docker v1.11 (master) we now set the HTTP Host header to "", which is why we don't see this on master.

I've been looking into a way to avoid having golang perform this check but haven't found a way yet.

Net is that this may force all clients that want to talk to a daemon via a unix docker to be upgraded at the same time as the daemon. Not an ideal UX situation.

The only other option I can think of, and its not great, is to postpone upgrading to golang 1.6 until v1.12 so that we can make v1.11 send a Host header with a value of "" for one release before we turn on this check in the daemon.  Then during the v1.12 upgrade process clients can upgrade later then the daemon, as long as they're at least on v1.11.

Anyway, wanted to open an issue so we could have a discussion and brainstorm on ideas.

### PR DESCRIPTION
**Pull request by calavera**
To not hit the issue with the request Host header.

Fixes #20865

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by calavera** [comment]
Is this a flacky error on experimental, or different Go versions output different messages?

```
00:02:50 FAIL: docker_experimental_network_test.go:326: DockerNetworkSuite.TestDockerNetworkIpvlanAddressing
00:02:50 
00:02:50 docker_experimental_network_test.go:340:
00:02:50     c.Assert(out, checker.Contains, "default via 2001:db8:abca::254 dev eth0")
00:02:50 ... obtained string = "" +
00:02:50 ...     "fe80::/64 dev eth0  metric 256 \n" +
00:02:50 ...     "unreachable default dev lo  metric -1  error -101\n" +
00:02:50 ...     "ff00::/8 dev eth0  metric 256 \n" +
00:02:50 ...     "unreachable default dev lo  metric -1  error -101\n"
00:02:50 ... substring string = "default via 2001:db8:abca::254 dev eth0"
```

**Comment by calavera** [comment]
it looks like it was

**Comment by thaJeztah** [comment]
Test will be fixed by https://github.com/docker/docker/pull/21492, and only fails on kernel 4.2+

**Comment by estesp** [comment]
Probably needs to be a follow-on PR for `Dockerfile.ppc64le` since it was switched to use native Go compiler, which exists in 1.6, but not 1.5.3.  So, it will have to go back to gccgo I guess.

**Comment by thaJeztah** [comment]
Good catch, @estesp

**Comment by icecrime** [comment]
@calavera I think this lacks a bunch of changes in `contrib/builder/` Dockerfiles.

**Comment by thaJeztah** [comment]
I checked, and I think all 1.6 references are covered here

**Comment by icecrime** [comment]
I triggered an `arm` build: let's wait for this one to complete before merging.

**Pull request merged**
