### PR TITLE
windows: Better error message on failed commit

### PR DESCRIPTION
**Pull request by jstarks**
When importing a layer, prefer the error message from the
layer reader to that of the layer writer, since this is
more likely to be a useful message. This is achieved by
always returning a zero exit code from re-exec, even on error.
This makes cmd.Wait() return the result of the io.Copy used
to copy in the layer data rather than the ExitError from
the process returning a non-zero exit code.

Signed-off-by: John Starks <jostarks@microsoft.com>

@jhowardmsft @darrenstahlmsft PTAL

### CODE REVIEW

**Comment by jstarks** [comment]
Please hold merging this.

**Comment by jstarks** [comment]
This doesn't quite work as expected because if export succeeds but import fails, this will return ERROR_NO_DATA instead of the import failure string. This is due to golang/go#20445. I'll need to push another change to work around this.

**Comment by thaJeztah** [comment]
@jstarks should I close this in the meantime, or were you planning to update _this_ PR?

**Comment by cpuguy83** [comment]
Ping

**Comment by AkihiroSuda** [comment]
ping @jstarks

**Comment by LK4D4** [comment]
I'm going to close this for now. We always can reopen :)

**Pull request closed without merging**
