### PR TITLE
vendor: libcontainer: update libcontainer

### PR DESCRIPTION
**Pull request by cyphar**
Update the vendor'd version of libcontainer to include path sanitisation
fixes and some other cgroup fixes.

Signed-off-by: Aleksa Sarai asarai@suse.com

This is the same as #19024, except GitHub won't let me push to it.

/cc @icecrime @runcom

### CODE REVIEW

**Comment by thaJeztah** [comment]
Moving to merge as the original PR already got LGTM'd

**Comment by cyphar** [comment]
I'm not sure why the tests are failing, but the fact that I haven't changed any code *in Docker* other than the code vendored in tells me something is broken upstream.

/cc @crosbymichael @mrunalp

**Comment by estesp** [comment]
Seems there really is an issue with the new vendored runc (libcontainer specifically) with container stop/destroy? Don't have enough data yet, but clearly the tests that are failing are failing because there are containers still running affecting expected ps output, for example.  One container that is all over the output (because it can be matched up to a specific test) is from here: https://github.com/docker/docker/blob/master/integration-cli/docker_cli_commit_test.go#L154-L159

**Comment by LK4D4** [comment]
Yup, and I have some of those failures locally :(

**Comment by cyphar** [comment]
@estesp Yeah, that's what I was thinking. The problem is that I can't effectively bisect on my machine (I don't get the errors). Since #19182 has the same error, it look like the bad commit occurs before opencontainers/runc@c0ad40c5e606157d6adc1955e5de1d724947c20c. I'll try pushing to this PR to do the bisecting.

**Comment by cyphar** [comment]
Okay, I've confirmed that @crosbymichael's commit opencontainers/runc@4415446c321ed9e31facfe25c9e230f5257bb872 causes this build issue (after bisecting, using this PR as a testbed). I'll open up an issue about this later.

**Comment by cyphar** [comment]
**DO NOT MERGE YET**

**Comment by tiborvass** [comment]
@cyphar whats up with this?

**Comment by LK4D4** [comment]
@tiborvass we need opencontainers/runc#470 or fix from @crosbymichael

**Comment by crosbymichael** [comment]
I'm looking into the state changes and any bugs associated.  we can close this for now until the bugs are fixed and we determine if we even need to bump libcontainer at this time.

**Comment by cyphar** [comment]
@crosbymichael There are security fixes to the Docker daemon in this libcontainer bump.

**Pull request closed without merging**
