### PR TITLE
use lxc.auto.mount to ensure proc and sys are readonly

### PR DESCRIPTION
**Pull request by ashahab-altiscale**
Set lxc.auto.mount = proc:mixed in unprivilged mode. This ensures that lxc mounts sys and proc/sysrq-trigger as readonly.

Merge after #10190

### CODE REVIEW

**Comment by SvenDowideit** [comment]
this needs documenation - and please, include any contrasts bewteen the lxc driver and the libcontainer one.

**Comment by jfrazelle** [comment]
I'm running this on jenkins here https://jenkins.dockerproject.com/job/LXC%20PR%20Test/label=ubuntu-aufs-lxc/4/console

**Comment by crosbymichael** [comment]
@ashahab-altiscale you will have to rebase now that your other PR is merged

**Comment by ashahab-altiscale** [comment]
@SvenDowideit  @dineshs-altiscale @crosbymichael rebased and documented. 
@jfrazelle Can you launch a new jenkins build?

**Comment by jfrazelle** [comment]
it's building here https://jenkins.dockerproject.com/job/LXC%20PR%20Test/label=ubuntu-aufs-lxc/4/console :)

**Comment by jfrazelle** [comment]
wrong link sorry, here: https://jenkins.dockerproject.com/job/LXC%20PR%20Test/5/console

**Comment by jfrazelle** [comment]
LGTM

**Comment by dineshs-altiscale** [comment]
LGTM

@ashahab-altiscale is having a productive week! : )

**Comment by jfrazelle** [comment]
:+1: ping @crosbymichael

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
