### PR TITLE
Swagger: fix definition of IPAM driver options

### LINKED ISSUE #38353: Swagger spec for IPAM type's Options field has wrong type
**Description**

The `/networks` API returns an array of `Network` objects, each of which contains an `IPAM` field of type `IPAM`.

The swagger spec describes the IPAM struct's [`Options` field](https://github.com/moby/moby/blob/62d80835abe3f7bc54c70f5e7bad638eaf3596be/api/swagger.yaml#L1487-L1489) to be an array of objects. However, the corresponding golang struct defines it to be [a golang map,](https://github.com/moby/moby/blob/62d80835abe3f7bc54c70f5e7bad638eaf3596be/api/types/network/network.go#L16) and indeed it gets serialized as an object, not an array.

This causes clients generated using the swagger spec to fail to deserialize the response.

This only appears to happen with networks created manually using the `docker network create` command, since these networks have at least an empty `{}` object for the `Options` key. The default networks created by docker (host, bridge, none) have `null` instead, so there is no problem deserializing them.

**Steps to reproduce the issue:**

1. Create a network

    ```sh
    $ docker network create foo --subnet 172.18.0.0/16 --gateway 172.18.0.1
    ```

1. Invoke the `/networks` API and inspect the result. The `IPAM` value's `Options` key is an empty object, not an array.

    ```sh
    $ curl --unix-socket /var/run/docker.sock http://foo/networks | jq

    ...

      {
        "Name": "foo",
    ...
        "IPAM": {
          "Driver": "default",
          "Options": {},
          "Config": [
            {
              "Subnet": "172.18.0.0/16",
              "Gateway": "172.18.0.1"
            }
          ]
        },
    ...
    ```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a215d7
 Built:             Mon Oct  8 12:00:00 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a215d7
  Built:            Mon Oct  8 12:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.17.1 
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc oci
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: v0.1.3_catatonit (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.5-1-default
Operating System: openSUSE Tumbleweed
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.29GiB
Name: arsing
ID: 47O2:JQSD:UJC6:PMG2:6QRT:VK7O:DAJV:LPPJ:QHV3:RUB3:YPV4:LWRO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$ uname -a

Linux arsing 4.19.5-1-default #1 SMP PREEMPT Tue Nov 27 19:56:09 UTC 2018 (6210279) x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 

NAME="openSUSE Tumbleweed"
# VERSION="20181204"
ID="opensuse-tumbleweed"
```

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/38353

### CODE REVIEW

**Comment by thaJeztah** [comment]
Arf... think a PR got merged with CI out of date

https://jenkins.dockerproject.org/job/Docker-PRs/52011/console

```
16:15:03 container/container_unix.go:1::warning: file is not goimported (goimports)
16:15:03 container/container_unix.go:394:6:warning: undeclared name: errors (gosimple)
16:15:03 container/container_unix.go:394:6:warning: undeclared name: errors (interfacer)
16:15:03 container/container_unix.go:394:6:warning: undeclared name: errors (unconvert)
```

s390x https://jenkins.dockerproject.org/job/Docker-PRs-s390x/12263/console

```
16:16:28 # github.com/docker/docker/container
16:16:28 container/container_unix.go:394:6: undefined: errors
```

**Comment by thaJeztah** [comment]
Fix for the missing import; https://github.com/moby/moby/pull/38360

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by thaJeztah** [comment]
ping @cpuguy83 @vdemeester PTAL 🤗

**Review by vdemeester — APPROVED** [review]
LGTM :lion:

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
