### PR TITLE
Remove the experimental flag requirement for checkpoint/restore.

### PR DESCRIPTION
**Pull request by boucher**
This is more of a placeholder than anything else. Merging this would remove the need to pass the experimental flag to the daemon in order to use checkpoint/restore. I'm hoping to get some feedback on what pre-requisites we need to accomplish in order to eventually make this change.

### CODE REVIEW

**Comment by tophj-ibm** [comment]
failure is related: 
```sh
15:32:25 ----------------------------------------------------------------------
15:32:25 FAIL: docker_cli_help_test.go:16: DockerSuite.TestHelpTextVerify
15:32:25 
15:32:25 docker_cli_help_test.go:139:
15:32:25     c.Fatal(err)
15:32:25 ... Error: All commands should mention '--help'. Command 'checkpoint rm' did not.
15:32:25 
15:32:25 
15:32:25 
15:32:25 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
I still have some concerns about the UX for this feature (e.g. storage paths); we can discuss those and tweak, but I prefer to keep it experimental until we're all confident on the design

**Comment by boucher** [comment]
Agreed, but was hoping to spark a discussion about the design.

**Comment by tswift242** [comment]
Big +1 for this.

I think the main thing docker needs to improve about the design is to provide better support for managing a container's filesystem alongside its checkpoint. Right now these things are decoupled and I think docker needs a way to couple them in order to provide a good experience for all but the trivial use case (checkpointing and restoring the same container). I've seen a lot of issues to either criu or docker in this space. The proposal in https://github.com/moby/moby/issues/30507 may be a good starting point for this discussion.

I think docker also needs to work with criu to come up with a solution to keep a container's networking details in sync with what's in a criu checkpoint. Right now for all but the trivial use case of checkpointing and restoring the same container, a user might have to manually muck with the criu image files to keep the IP addresses referenced within in line with the IP address of the container being restored. See https://github.com/xemul/criu/issues/167. Since docker manages everything about a container's networking, it feels like docker should naturally also take on this responsibility, with the help of any necessary support from criu.

**Comment by boucher** [comment]
My suggestion would be that we make checkpoints a global resource (making names an optional thing, like container names), and include with the checkpoint the image id needed to restore. At the same time, automatically doing a `commit` on the container whenever a checkpoint is created.

**Comment by cpuguy83** [comment]
I'm a bit worried about this.
It doesn't seem like the functionality has been particularly stable, and I'm not sure we've spent enough time on the UX for it.

**Comment by thaJeztah** [comment]
@boucher can you open an issue to discuss the design changes? Thinking of;

- should snapshots be combined with a snapshot of the rootfs?
- should they be a _global_ list instead of per-container?
- storage location

Let's close this PR for now, and have a discussion separately from this 👍

**Pull request closed without merging**
