### PR TITLE
pkg/ioutils: fix multireader SEEK_CUR branch

### PR DESCRIPTION
**Pull request by LK4D4**
Before getReaderForOffset returned always nil.

ping @cpuguy83

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM 😵  🌴

**Comment by tonistiigi** [comment]
@LK4D4 Can we have a test for this?

**Comment by LK4D4** [comment]
@cpuguy83 @tonistiigi added test. Also, a test revealed other problem with getReaderOffset.

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
