### PR TITLE
Corrected int16 overflow and buffer sizes

### PR DESCRIPTION
**Pull request by brendandixon**
Signed-off-by: Brendan Dixon brendand@microsoft.com

### CODE REVIEW

**Comment by icecrime** [comment]
Thanks @brendandixon! Adding 1.6.0 Milestone, ping @jfrazelle.

**Comment by icecrime** [comment]
Oh, one issue with formatting though (breaks CI):

```
These files are not properly gofmt'd:
 - pkg/term/winconsole/console_windows.go

Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by brendandixon** [comment]
Done. Sorry about that.

**Comment by brendandixon** [comment]
By the way, this change should also eliminate the panics during window resizing.

**Comment by jfrazelle** [comment]
cool thanks @brendandixon !

**Comment by jfrazelle** [comment]
doesnt this close certain issue #'s too :)

**Comment by brendandixon** [comment]
Likely. I don't recall the issue #'s.

**Comment by thaJeztah** [comment]
Are these the issues? https://github.com/docker/docker/issues/12153 and https://github.com/docker/docker/issues/12158?

**Comment by icecrime** [comment]
First feedback for this PR is that I don't see much improvement (and one degradation actually :sad:):

* Line wrapping doesn't seem to be better (I still get an empty line after filling a whole line)
* Output from `docker pull busybox` just spammed by term, and handed control back with a prompt somewhere in the middle of the output

screen shot 2015-04-10 at 09 03 46

**Comment by tiborvass** [comment]
@brendandixon it WORKS!

But I found two other things:
* Ctrl+C is not caught and exits the container (should depend on `-t` and `--sig-proxy` ). It's weird coz this should be handled by Go already. So I'm suspecting that cmd.exe does not forward Ctrl+C by default to the process in the foreground? If this could be changed for Ctrl+C and Ctrl+\ that'd be fantastic.
* I got a `FATA[0031] strconv.ParseInt: parsing "86\x1b[86": invalid syntax` by opening `vi`, hitting `i` to get in insert mode, and then keep hitting a letter e.g. `a` until it tries to wrap the line.

**Comment by tiborvass** [comment]
@icecrime it doesn't panic when you used a lot of buffers, and then resize the screen, which is what this PR is supposed to fix.

**Comment by icecrime** [comment]
Ok then, it wasn't clear what issue was being solved, my bad.

**Comment by brendandixon** [comment]
The change corrected an int16 overflow that definitely allowed residual characters to remain on the screen. It also corrected the values used when clearing the screen (to ensure the entire backing buffer is emptied). That is all the changes do. I did not want to drop you folks a large PR so close to release.

I am continuing my rewrite work on another branch. That branch is intended address may other issues (property interrupt handling, richer ANSI support, correct line-wrapping, etc.).

**Comment by brendandixon** [comment]
@tiborvass BTW: Please send me any issues you find. I'll ensure to address / fix them. Having said that, the rewrite will not be ready for 1.6.0.

**Comment by tiborvass** [comment]
I confirm what @icecrime is seeing in two ways:
* opening a normal cmd.exe window with its default size, and doing a docker pull busybox I get the screen he shared.
* By maximizing the cmd.exe first, and pulling a fresh busybox I get this:

**Comment by tiborvass** [comment]
@brendandixon do you think you could fix the `vi` line-wrap bug and the weirdness in `docker pull` for 1.6 ? I think those are higher priorities than say Ctrl+C not being forwarded.

**Comment by thaJeztah** [comment]
@tibor the CTRL-C was already reported in https://github.com/docker/docker/issues/12158

**Comment by tiborvass** [comment]
This PR makes sense and fixes the panic it was meant to fix so LGTM

**Comment by icecrime** [comment]
+1 Fixes one issue LGTM

**Comment by jfrazelle** [comment]
did we close the appropriate issues :)

**Comment by brendandixon** [comment]
@tiborvass I'll take a look and see what I can do.

**Comment by tiborvass** [comment]
@brendandixon thanks, do you know of any issue that this PR would close?

**Comment by brendandixon** [comment]
@tiborvass In reviewing the open issues, none directly apply. I did find we were setting a bit that causes the Windows shell to consume Ctrl+C. I've coded a version with that bit cleared and I cannot, under cmd.exe, reproduce the problems you saw. Powershell, for reasons unknown, seems to still have problems. I believe there are issues with ANSI to Windows and Windows to ANSI translation. I also believe there are ANSI sequences that can cause the parsing, which is pretty simple, to get confused.

**Comment by jfrazelle** [comment]
thanks for clear-ing this up :) see what I did there

**Pull request merged**
