### PR TITLE
Add Ubuntu 17.04 Zesty Zapus

### LINKED ISSUE #32423: get.docker.com install fails on Ubuntu 17.04
Trying to install docker on a fresh install of Ubuntu 17.04 fails:

```
# curl -sSL https://get.docker.com/ | sh
apparmor is enabled in the kernel and apparmor utils were already installed
+ apt-key add -
+ echo -----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFWln24BEADrBl5p99uKh8+rpvqJ48u4eTtjeXAWbslJotmC/CakbNSqOb9o
ddfzRvGVeJVERt/Q/mlvEqgnyTQy+e6oEYN2Y2kqXceUhXagThnqCoxcEJ3+KM4R
mYdoe/BJ/J/6rHOjq7Omk24z2qB3RU1uAv57iY5VGw5p45uZB4C4pNNsBJXoCvPn
TGAs/7IrekFZDDgVraPx/hdiwopQ8NltSfZCyu/jPpWFK28TR8yfVlzYFwibj5WK
dHM7ZTqlA1tHIG+agyPf3Rae0jPMsHR6q+arXVwMccyOi+ULU0z8mHUJ3iEMIrpT
X+80KaN/ZjibfsBOCjcfiJSB/acn4nxQQgNZigna32velafhQivsNREFeJpzENiG
HOoyC6qVeOgKrRiKxzymj0FIMLru/iFF5pSWcBQB7PYlt8J0G80lAcPr6VCiN+4c
NKv03SdvA69dCOj79PuO9IIvQsJXsSq96HB+TeEmmL+xSdpGtGdCJHHM1fDeCqkZ
hT+RtBGQL2SEdWjxbF43oQopocT8cHvyX6Zaltn0svoGs+wX3Z/H6/8P5anog43U
65c0A+64Jj00rNDr8j31izhtQMRo892kGeQAaaxg4Pz6HnS7hRC+cOMHUU4HA7iM
zHrouAdYeTZeZEQOA7SxtCME9ZnGwe2grxPXh/U/80WJGkzLFNcTKdv+rwARAQAB
tDdEb2NrZXIgUmVsZWFzZSBUb29sIChyZWxlYXNlZG9ja2VyKSA8ZG9ja2VyQGRv
Y2tlci5jb20+iQIcBBABCgAGBQJWw7vdAAoJEFyzYeVS+w0QHysP/i37m4SyoOCV
cnybl18vzwBEcp4VCRbXvHvOXty1gccVIV8/aJqNKgBV97lY3vrpOyiIeB8ETQeg
srxFE7t/Gz0rsLObqfLEHdmn5iBJRkhLfCpzjeOnyB3Z0IJB6UogO/msQVYe5CXJ
l6uwr0AmoiCBLrVlDAktxVh9RWch0l0KZRX2FpHu8h+uM0/zySqIidlYfLa3y5oH
scU+nGU1i6ImwDTD3ysZC5jp9aVfvUmcESyAb4vvdcAHR+bXhA/RW8QHeeMFliWw
7Z2jYHyuHmDnWG2yUrnCqAJTrWV+OfKRIzzJFBs4e88ru5h2ZIXdRepw/+COYj34
LyzxR2cxr2u/xvxwXCkSMe7F4KZAphD+1ws61FhnUMi/PERMYfTFuvPrCkq4gyBj
t3fFpZ2NR/fKW87QOeVcn1ivXl9id3MMs9KXJsg7QasT7mCsee2VIFsxrkFQ2jNp
D+JAERRn9Fj4ArHL5TbwkkFbZZvSi6fr5h2GbCAXIGhIXKnjjorPY/YDX6X8AaHO
W1zblWy/CFr6VFl963jrjJgag0G6tNtBZLrclZgWhOQpeZZ5Lbvz2ZA5CqRrfAVc
wPNW1fObFIRtqV6vuVluFOPCMAAnOnqR02w9t17iVQjO3oVN0mbQi9vjuExXh1Yo
ScVetiO6LSmlQfVEVRTqHLMgXyR/EMo7iQIcBBABCgAGBQJXSWBlAAoJEFyzYeVS
+w0QeH0QAI6btAfYwYPuAjfRUy9qlnPhZ+xt1rnwsUzsbmo8K3XTNh+l/R08nu0d
sczw30Q1wju28fh1N8ay223+69f0+yICaXqR18AbGgFGKX7vo0gfEVaxdItUN3eH
NydGFzmeOKbAlrxIMECnSTG/TkFVYO9Ntlv9vSN2BupmTagTRErxLZKnVsWRzp+X
elwlgU5BCZ6U6Ze8+bIc6F1bZstf17X8i6XNV/rOCLx2yP0hn1osoljoLPpW8nzk
wvqYsYbCA28lMt1aqe0UWvRCqR0zxlKn17NZQqjbxcajEMCajoQ01MshmO5GWePV
iv2abCZ/iaC5zKqVT3deMJHLq7lum6qhA41E9gJH9QoqT+qgadheeFfoC1QP7cke
+tXmYg2R39p3l5Hmm+JQbP4f9V5mpWExvHGCSbcatr35tnakIJZugq2ogzsm1djC
Sz9222RXl9OoFqsm1bNzA78+/cOt5N2cyhU0bM2T/zgh42YbDD+JDU/HSmxUIpU+
wrGvZGM2FU/up0DRxOC4U1fL6HHlj8liNJWfEg3vhougOh66gGF9ik5j4eIlNoz6
lst+gmvlZQ9/9hRDeoG+AbhZeIlQ4CCw+Y1j/+fUxIzKHPVK+aFJd+oJVNvbojJW
/SgDdSMtFwqOvXyYcHl30Ws0gZUeDyAmNGZeJ3kFklnApDmeKK+OiQIiBBABCgAM
BQJXe5zTBYMHhh+AAAoJEDG4FaMBBnSp7YMQAJqrXoBonZAq07B6qUaT3aBCgnY4
JshbXmFb/XrrS75f7YJDPx2fJJdqrbYDIHHgOjzxvp3ngPpOpJzI5sYmkaugeoCO
/KHu/+39XqgTB7fguzapRfbvuWp+qzPcHSdb9opnagfzKAze3DQnnLiwCPlsyvGp
zC4KzXgV2ze/4raaOye1kK7O0cHyapmn/q/TR3S8YapyXq5VpLThwJAw1SRDu0Yx
eXIAQiIfaSxT79EktoioW2CSV8/djt+gBjXnKYJJA8P1zzX7GNt/Rc2YG0Ot4v6t
BW16xqFTg+n5JzbeK5cZ1jbIXXfCcaZJyiM2MzYGhSJ9+EV7JYF05OAIWE4SGTRj
XMquQ2oMLSwMCPQHm+FCD9PXQ0tHYx6tKT34wksdmoWsdejl/n3NS+178mG1WI/l
N079h3im2gRwOykMou/QWs3vGw/xDoOYHPV2gJ7To9BLVnVK/hROgdFLZFeyRScN
zwKm57HmYMFA74tX601OiHhk1ymP2UUc25oDWpLXlfcRULJJlo/KfZZF3pmKwIq3
CilGayFUi1NNwuavG76EcAVtVFUVFFIITwkhkuRbBHIytzEHYosFgD5/acK0Pauq
JnwrwKv0nWq3aK7nKiALAD+iZvPNjFZau3/APqLEmvmRnAElmugcHsWREFxMMjMM
VgYFiYKUAJO8u46eiQI4BBMBAgAiBQJVpZ9uAhsvBgsJCAcDAgYVCAIJCgsEFgID
AQIeAQIXgAAKCRD3YiFXLFJgnbRfEAC9Uai7Rv20QIDlDogRzd+Vebg4ahyoUdj0
CH+nAk40RIoq6G26u1e+sdgjpCa8jF6vrx+smpgd1HeJdmpahUX0XN3X9f9qU9oj
9A4I1WDalRWJh+tP5WNv2ySy6AwcP9QnjuBMRTnTK27pk1sEMg9oJHK5p+ts8hlS
C4SluyMKH5NMVy9c+A9yqq9NF6M6d6/ehKfBFFLG9BX+XLBATvf1ZemGVHQusCQe
bTGv0C0V9yqtdPdRWVIEhHxyNHATaVYOafTj/EF0lDxLl6zDT6trRV5n9F1VCEh4
Aal8L5MxVPcIZVO7NHT2EkQgn8CvWjV3oKl2GopZF8V4XdJRl90U/WDv/6cmfI08
GkzDYBHhS8ULWRFwGKobsSTyIvnbk4NtKdnTGyTJCQ8+6i52s+C54PiNgfj2ieNn
6oOR7d+bNCcG1CdOYY+ZXVOcsjl73UYvtJrO0Rl/NpYERkZ5d/tzw4jZ6FCXgggA
/Zxcjk6Y1ZvIm8Mt8wLRFH9Nww+FVsCtaCXJLP8DlJLASMD9rl5QS9Ku3u7ZNrr5
HWXPHXITX660jglyshch6CWeiUATqjIAzkEQom/kEnOrvJAtkypRJ59vYQOedZ1s
FVELMXg2UCkD/FwojfnVtjzYaTCeGwFQeqzHmM241iuOmBYPeyTY5veF49aBJA1g
EJOQTvBR8Q==
=Yhur
-----END PGP PUBLIC KEY BLOCK-----

OK
+ sh -c mkdir -p /etc/apt/sources.list.d
+ dpkg --print-architecture
+ sh -c echo deb \[arch=amd64\] https://apt.dockerproject.org/repo ubuntu-zesty main > /etc/apt/sources.list.d/docker.list
+ sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                                  
Hit:4 http://security.ubuntu.com/ubuntu zesty-security InRelease                            
Get:5 http://us.archive.ubuntu.com/ubuntu zesty InRelease [243 kB]                
Hit:6 http://us.archive.ubuntu.com/ubuntu zesty-updates InRelease
Ign:7 https://apt.dockerproject.org/repo ubuntu-zesty InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu zesty-backports InRelease
Ign:9 https://apt.dockerproject.org/repo ubuntu-zesty Release
Ign:10 https://apt.dockerproject.org/repo ubuntu-zesty/main all Packages
Ign:11 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 Packages
Ign:12 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en
Ign:13 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en_US
Ign:14 https://apt.dockerproject.org/repo ubuntu-zesty/main all DEP-11 Metadata
Ign:15 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 DEP-11 Metadata
Ign:16 https://apt.dockerproject.org/repo ubuntu-zesty/main DEP-11 64x64 Icons
Ign:10 https://apt.dockerproject.org/repo ubuntu-zesty/main all Packages
Ign:11 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 Packages
Ign:12 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en
Ign:13 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en_US
Ign:14 https://apt.dockerproject.org/repo ubuntu-zesty/main all DEP-11 Metadata
Ign:15 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 DEP-11 Metadata
Ign:16 https://apt.dockerproject.org/repo ubuntu-zesty/main DEP-11 64x64 Icons
Ign:10 https://apt.dockerproject.org/repo ubuntu-zesty/main all Packages
Ign:11 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 Packages
Ign:12 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en
Ign:13 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en_US
Ign:14 https://apt.dockerproject.org/repo ubuntu-zesty/main all DEP-11 Metadata
Ign:15 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 DEP-11 Metadata
Ign:16 https://apt.dockerproject.org/repo ubuntu-zesty/main DEP-11 64x64 Icons
Ign:10 https://apt.dockerproject.org/repo ubuntu-zesty/main all Packages
Ign:11 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 Packages
Ign:12 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en
Ign:13 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en_US
Ign:14 https://apt.dockerproject.org/repo ubuntu-zesty/main all DEP-11 Metadata
Ign:15 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 DEP-11 Metadata
Ign:16 https://apt.dockerproject.org/repo ubuntu-zesty/main DEP-11 64x64 Icons
Ign:10 https://apt.dockerproject.org/repo ubuntu-zesty/main all Packages
Ign:11 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 Packages
Ign:12 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en
Ign:13 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en_US
Ign:14 https://apt.dockerproject.org/repo ubuntu-zesty/main all DEP-11 Metadata
Ign:15 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 DEP-11 Metadata
Ign:16 https://apt.dockerproject.org/repo ubuntu-zesty/main DEP-11 64x64 Icons                                                                             
Ign:10 https://apt.dockerproject.org/repo ubuntu-zesty/main all Packages                                                                                   
Err:11 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 Packages                                                                                 
  403  Forbidden
Ign:12 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en                                                                                 
Ign:13 https://apt.dockerproject.org/repo ubuntu-zesty/main Translation-en_US                                                                              
Ign:14 https://apt.dockerproject.org/repo ubuntu-zesty/main all DEP-11 Metadata                                                                            
Ign:15 https://apt.dockerproject.org/repo ubuntu-zesty/main amd64 DEP-11 Metadata                                                                          
Ign:16 https://apt.dockerproject.org/repo ubuntu-zesty/main DEP-11 64x64 Icons                                                                             
Fetched 243 kB in 6s (35.6 kB/s)                                                                                                                           
Reading package lists... Done
W: The repository 'https://apt.dockerproject.org/repo ubuntu-zesty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-zesty/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package docker-engine is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-engine' has no installation candidate
```

### PR DESCRIPTION
**Pull request by thaJeztah**
Ubuntu 17.04 will be released soon https://wiki.ubuntu.com/ZestyZapus/ReleaseSchedule (13 April- stable release)

Note that this is a short-term release, so will EOL (and removed again) in 9 months

fixes https://github.com/docker/docker/issues/32423

**- What I did**

Added ubuntu-zesty

**- How I did it**

**- How to verify it**

Build the `.deb`

```
make BIND_DIR=. DOCKER_BUILD_PKGS=ubuntu-zesty deb
```

Run a zesty container

```
docker run -it --rm -v /var/lib/docker --privileged -v $(pwd)/bundles/latest/build-deb/ubuntu-zesty/:/install ubuntu:zesty bash
```

Install dependencies and docker;
```
apt-get update && apt-get install -y iptables libapparmor1 libdevmapper-dev libseccomp-dev libltdl7

dpkg -i /install/docker-engine_17.05.0~dev~git20170407.115844.0.a8c714a-0~ubuntu-zesty_amd64.deb
```

And run the daemon

```
dockerd --debug &
```

```
Client:
 Version:      17.05.0-dev
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   a8c714a7c
 Built:        Fri Apr  7 12:14:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-dev
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   a8c714a7c
 Built:        Fri Apr  7 12:14:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Client:
 Version:      17.05.0-dev
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   a8c714a7c
 Built:        Fri Apr  7 12:14:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-dev
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   a8c714a7c
 Built:        Fri Apr  7 12:14:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@5d63dc01f45c:/# docker into
docker: 'into' is not a docker command.
See 'docker --help'
root@5d63dc01f45c:/# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.19-moby
Operating System: Ubuntu Zesty Zapus (development branch) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: 5d63dc01f45c
ID: 53DK:EA5P:Y3M5:D3JL:KBEV:7V3I:Q3AH:NVCQ:YXXM:DAAX:KWLA:AENB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 21
 System Time: 2017-04-07T12:43:53.610460918Z
 EventsListeners: 0
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**- Description for the changelog**

Add support for building docker debs for Ubuntu 17.04 Zesty on amd64

**- A picture of a cute animal (not mandatory but encouraged)**

ubuntu-17 04-zesty-zapus

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by thaJeztah** [comment]
ping @vieux @andrewhsu

**Comment by vieux** [comment]
LGTM

**Comment by andrewhsu** [comment]
Sweet! The packages will be available for docker 17.05.0 rc2.

**Pull request merged**
