### PR TITLE
Updated legacy_plugins.md to include BeeGFS plugin

### PR DESCRIPTION
**Pull request by breuner**
**- What I did**
Updated legacy_plugins.md to include BeeGFS plugin

**- A picture of a cute animal (not mandatory but encouraged)**
```
    /\___/\
   (  o o  )
   /   *   \
   \__\_/__/ meow!
     /   \
    / ___ \
    \/___\/
```
(http://www.asciiworld.com)

### CODE REVIEW

**Comment by breuner** [comment]
@GordonTheTurtle sorry for my mistake and thanks a lot for your kind help

**Review by vdemeester — APPROVED** [review]
LGTM 👼

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by breuner** [comment]
@thaJeztah thanks, just to make sure I did the right thing: Was it ok to request the pull for branch docker:17.03.x only (that branch was automatically selected when I hit the "edit page" link at docs.docker.com) or should I have also requested a pull for the master branch?

**Comment by thaJeztah** [comment]
thanks @breuner, yes, we usually merge into master and from master cherry-pick to the relevant release branch(es). I'll discuss with the docs team to have the "edit" links updated, perhaps with an extra note that the "master" version may be different than what's published

/cc @johndmulhausen @mstanleyjones 

I opened https://github.com/docker/docker/pull/32304 to cherry-pick this PR into master, to prevent it from getting lost on the next release :smile:

**Pull request merged**
