### PR TITLE
Re-vendor swarmkit

### PR DESCRIPTION
**Pull request by cyli**
This re-vendors swarmkit to the latest version.  This is the master version of https://github.com/docker/docker/pull/32581, which in addition adds tests to ensure backwards compatibility with older clients.

cute

cc ~~@vieux~~ @aaronlehmann 

This particular PR does not need cherry-picking, https://github.com/docker/docker/pull/32581 does.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
I know I asked you earlier to open PRs against master, but... :)

It gets a little more complicated when revendoring is involved. Only the master version of swarmkit should be vendored in docker master, and only the `bump_v17.05.x` branches should be vendored on the 17.05.x branch.

So I'd appreciate if you could open two PRs for the separate branches, each with the corresponding version of swarmkit.

Sorry for the confusion and extra complexity!

**Comment by cyli** [comment]
@aaronlehmann No worries!  I can just reopen the previous one and push all the changes.

**Comment by cyli** [comment]
Oop never mind, I can't re-open PRs, so I'll just open a new one.  https://github.com/docker/docker/pull/32581

**Comment by aaronlehmann** [comment]
LGTM if green

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Pull request merged**
