### PR TITLE
environment: Error when t.Parallel was called before Protect

### PR DESCRIPTION
**Pull request by vvoland**
- related to: https://github.com/moby/moby/pull/47082

Protecting the environment relies on the shared state (containers, images, etc) which might already be mutated by other tests if the test opted in into the Parallel execution before Protect was called.

It uses reflection because there's no public API to check this, but considering that this is only used in tests - worst case scenario is that it won't work when upgrading to a new Golang version and we'll need to adjust the check or revert it.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
LOL, and just when I commented, I saw you pushed a change for exactly that test 😂

**Comment by vvoland** [comment]
`TestVolumesRemoveSwarmEnabled` is the only parallel test in that package so practically the blast area was pretty small and would probably only impact itself or test that's directly after it (`TestVolumesInspect`).

I think these didn't have much flakiness. But let's see if it makes things better 😄

**Comment by thaJeztah** [comment]
Whoop! It's green 👍 Time to move it out of draft?

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
