### PR TITLE
Adds a correct error string for network validation

### PR DESCRIPTION
**Pull request by jterry75**
**\- What I did**
Updated the test to pass with recent Windows error strings.
**\- How I did it**
Wrote some Go code.
**\- How to verify it**
Docker CI will run this test.
**\- Description for the changelog**

Adds a correct error string for network validation

**\- A picture of a cute animal (not mandatory but encouraged)**
[Pygmy Seahorse](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwi_i-K4lc7MAhVC_mMKHcGHD3cQjRwIBw&url=http%3A%2F%2Fmission-blue.org%2F2012%2F12%2Fphoto-of-the-day-pygmy-seahorse%2F&psig=AFQjCNE8-_IelLbmPk_8t5bWFZS0nOT0Bw&ust=1462923654019401)

Fixes the negative networking test to include the new error string
from recent Windows builds.

Signed-off-by: Justin Terry juterry@microsoft.com

### CODE REVIEW

**Comment by jterry75** [comment]
@jhowardmsft - FYI

**Comment by swernli** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by jhowardmsft** [comment]
LGTM

**Pull request merged**
