### PR TITLE
Fix a few code rendering errors in docs

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
Fixes the following errors:
- https://docs.docker.com/articles/networking/
  screenshot 2015-03-08 16 10 30
  screenshot 2015-03-08 16 06 39
- https://docs.docker.com/reference/run/

screenshot 2015-03-08 16 23 48
Signed-off-by: ChristoperBiscardi chris@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM (not a maintainer) 

If this is merged, give me a "ping", because https://github.com/docker/docker/pull/11239/files will  probably need a rebase then (the fix in "reference/run.md" is included in that PR as well)

**Comment by estesp** [comment]
Would you mind correcting the "echo" and "cat" of `/proc/sys/net` values to the sysctl used in the IPv6 docs a bit later?  It should be:
```
$ sysctl net.ipv4.conf.all.forwarding
net.ipv4.conf.all.forwarding = 0
$ sysctl net.ipv4.conf.all.forwarding=1
$ sysctl net.ipv4.conf.all.forwarding
net.ipv4.conf.all.forwarding = 1
```

**Comment by jfrazelle** [comment]
you rule @ChristopherBiscardi

**Comment by ChristopherBiscardi** [comment]
@estesp Should be fixed

**Comment by SvenDowideit** [comment]
LGTM @docker/docs-owners

**Comment by estesp** [comment]
thanks! LGTM

**Pull request merged**
