### PR TITLE
Correct IP/MAC address generation docs

### PR DESCRIPTION
**Pull request by jstangroome**
The MAC address is generated from the IP address, not the other way.

### CODE REVIEW

**Comment by jfrazelle** [comment]
I thought we generate from MAC iirc, @LK4D4

**Comment by SvenDowideit** [comment]
`func generateMacAddr(ip net.IP) net.HardwareAddr`

in `daemon/networkdriver/bridge/driver.go` ?

though that seems to be coded for IPv4 - what happens if we're IPv6 only?

**Comment by jstangroome** [comment]
In Docker 1.5, specifying the MAC address has no impact on the IP address as demonstrated by running a container with a MAC address specified, checking its IP, then repeating with the same MAC address, eg:

```
$ docker run --rm -ti --mac-address=02:5e:89:89:89:89 ubuntu:trusty /sbin/ifconfig
eth0      Link encap:Ethernet  HWaddr 02:5e:89:89:89:89
          inet addr:172.17.0.33

$ docker run --rm -ti --mac-address=02:5e:89:89:89:89 ubuntu:trusty /sbin/ifconfig
eth0      Link encap:Ethernet  HWaddr 02:5e:89:89:89:89
          inet addr:172.17.0.34
```

However, running a container without specifying the MAC address shows that the MAC is generated from the IP, eg:

```
$ docker run --rm -ti ubuntu:trusty /sbin/ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:24
          inet addr:172.17.0.36
```

**Comment by jfrazelle** [comment]
ping @LK4D4 is this correct?

**Comment by LK4D4** [comment]
@jfrazelle Yes, we generate mac from IP and LinkLocalIPv6 from Mac if there is `--ipv6-fixed-cidr` :) Actually I'm pretty bad at those stuff too.

**Comment by SvenDowideit** [comment]
and so - LGTM - @fredlf @jamtur01 @spf13 @moxiegirl

**Pull request merged**
