### PR TITLE
Set permission on atomic file write

### PR DESCRIPTION
**Pull request by dmcgowan**
Perform chmod before rename with the atomic file writer.

Ping @tonistiigi

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by dmcgowan** [comment]
Update to call `(*os.File).Chmod` right when file opens. This uses the file descriptor so can be done safely right after open.

**Comment by cpuguy83** [comment]
Error starting daemon: Couldn't create Tag store repositories: chmod D:\\CI\\CI-726b8fc\\daemon\\image\\windowsfilter\\.tmp-repositories.json584666515: not supported by windows"

**Comment by dmcgowan** [comment]
@cpuguy83 thanks for pointing that out. The error message is slightly misleading, it is "fchmod" which is not supported, so I switched it back to use `os.Chmod` instead of `(*os.File).Chmod`.

**Comment by tonistiigi** [comment]
@dmcgowan tp5 doesn't like that testcase

**Comment by dmcgowan** [comment]
ping @jhowardmsft  do you have any insight to how I am setting or testing file mode incorrectly?

**Comment by jhowardmsft** [comment]
Windows doesn't have a concept of an execute bit.

**Comment by dmcgowan** [comment]
Thanks John, changed permission test to 0644, The "other" bit didn't get set either so set it to the same as the group for the test.

**Comment by cpuguy83** [comment]
fswriters_test.go:37: Mode mismatched, expected 644, got 666

**Comment by dmcgowan** [comment]
Ugh, ok, so Windows doesn't have group or other bits. Guess will just have to change to 666 since writing separate tests is not worth it. Temp files are initialized to 0600 anyway.

**Comment by cpuguy83** [comment]
LGTM

**Comment by tonistiigi** [comment]
Still LGTM

**Comment by thaJeztah** [comment]
all green, merging

**Comment by thaJeztah** [comment]
@cpuguy83 @dmcgowan @tonistiigi do we need this for 1.12?

**Pull request merged**
