### PR TITLE
use unique names for resources in integration tests of secret package

### PR DESCRIPTION
**Pull request by adshmh**
Use unique names for resources in integration tests of secret package. Part of work on #36583

**- What I did**
Resource names in integration tests of the package `integration/secret` are now unique

**- How I did it**
used t.Name() to make unique resource names for the integration tests.

**- How to verify it**

**- Description for the changelog**
Unique resource names for integration tests of package integration/secret
**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by yongtang — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Interesting failure on experimental (should not be related); https://jenkins.dockerproject.org/job/Docker-PRs-experimental/40898/console

```
18:47:07 FAIL: docker_cli_daemon_test.go:1490: DockerDaemonSuite.TestRunContainerWithBridgeNone
18:47:07 
18:47:07 [de17474bbd746] waiting for daemon to start
18:47:07 [de17474bbd746] daemon started
18:47:07 
18:47:07 docker_cli_daemon_test.go:1514:
18:47:07     c.Assert(out, check.Equals, fmt.Sprintf("%s", stdout),
18:47:07         check.Commentf("The network interfaces in container should be the same with host when --net=host when bridge network is disabled: %s", out))
18:47:07 ... obtained string = "" +
18:47:07 ...     "1: lo\n" +
18:47:07 ...     "3842: br-89df27d367f7\n" +
18:47:07 ...     "260: vethac289b2@if259\n" +
18:47:07 ...     "7: docker_gwbridge\n" +
18:47:07 ...     "100: br-e33440d8a7ce\n" +
18:47:07 ...     "101: eth0@br-b065b28a02c0\n" +
18:47:07 ...     "102: br-b065b28a02c0\n" +
18:47:07 ...     "104: br-94df0fcbf877\n" +
18:47:07 ...     "107: br-3943960c1e78\n" +
18:47:07 ...     "108: br-0de605bebf45\n" +
18:47:07 ...     "110: br-b3666262abed\n" +
18:47:07 ...     "131: dm-d06f7d55ee25\n" +
18:47:07 ...     "134: dm-40b8757dd5c5\n" +
18:47:07 ...     "137: dm-59392aff0a4b\n" +
18:47:07 ...     "145: di-89dea9275e25\n" +
18:47:07 ...     "148: di-a26c3794986a\n" +
18:47:07 ...     "151: di-1784797bf629\n" +
18:47:07 ...     "154: di-67bd5a4f508b\n" +
18:47:07 ...     "157: di-f13eb0a9a3bf\n" +
18:47:07 ...     "162: di-4f8e8a6ef498\n" +
18:47:07 ...     "167: di-4a1bda197b82\n" +
18:47:07 ...     "169: di-5f3e0b4700d6\n"
18:47:07 ... expected string = "" +
18:47:07 ...     "1: lo\n" +
18:47:07 ...     "3842: br-89df27d367f7\n" +
18:47:07 ...     "260: vethac289b2@if259\n" +
18:47:07 ...     "7: docker_gwbridge\n" +
18:47:07 ...     "100: br-e33440d8a7ce\n" +
18:47:07 ...     "101: eth0@if102\n" +
18:47:07 ...     "102: br-b065b28a02c0\n" +
18:47:07 ...     "104: br-94df0fcbf877\n" +
18:47:07 ...     "107: br-3943960c1e78\n" +
18:47:07 ...     "108: br-0de605bebf45\n" +
18:47:07 ...     "110: br-b3666262abed\n" +
18:47:07 ...     "131: dm-d06f7d55ee25\n" +
18:47:07 ...     "134: dm-40b8757dd5c5\n" +
18:47:07 ...     "137: dm-59392aff0a4b\n" +
18:47:07 ...     "145: di-89dea9275e25\n" +
18:47:07 ...     "148: di-a26c3794986a\n" +
18:47:07 ...     "151: di-1784797bf629\n" +
18:47:07 ...     "154: di-67bd5a4f508b\n" +
18:47:07 ...     "157: di-f13eb0a9a3bf\n" +
18:47:07 ...     "162: di-4f8e8a6ef498\n" +
18:47:07 ...     "167: di-4a1bda197b82\n" +
18:47:07 ...     "169: di-5f3e0b4700d6\n"
18:47:07 ... The network interfaces in container should be the same with host when --net=host when bridge network is disabled: 1: lo
18:47:07 3842: br-89df27d367f7
18:47:07 260: vethac289b2@if259
18:47:07 7: docker_gwbridge
18:47:07 100: br-e33440d8a7ce
18:47:07 101: eth0@br-b065b28a02c0
18:47:07 102: br-b065b28a02c0
18:47:07 104: br-94df0fcbf877
18:47:07 107: br-3943960c1e78
18:47:07 108: br-0de605bebf45
18:47:07 110: br-b3666262abed
18:47:07 131: dm-d06f7d55ee25
18:47:07 134: dm-40b8757dd5c5
18:47:07 137: dm-59392aff0a4b
18:47:07 145: di-89dea9275e25
18:47:07 148: di-a26c3794986a
18:47:07 151: di-1784797bf629
18:47:07 154: di-67bd5a4f508b
18:47:07 157: di-f13eb0a9a3bf
18:47:07 162: di-4f8e8a6ef498
18:47:07 167: di-4a1bda197b82
18:47:07 169: di-5f3e0b4700d6
18:47:07 
18:47:07 
18:47:07 [de17474bbd746] exiting daemon
```

**Pull request merged**
