### PR TITLE
 Vendoring libnetwork v0.5.6

### LINKED ISSUE #19354: Embedded DNS is not setup when a container restarts because of restart policy
see related libnetwork issue; https://github.com/docker/libnetwork/issues/876

### PR DESCRIPTION
**Pull request by sanimej**
- Setup embedded DNS server correctly on container restart
- IT case in docker

Fixes #19354

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by mavenugo** [comment]
thanks @sanimej .
libnetwork vendor-in LGTM.

**Comment by thaJeztah** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
