### PR TITLE
Modify IPAMConfig structure json tags

### PR DESCRIPTION
**Pull request by aboch**
- So that it complies with docker convention for inspect
  I missed this inner struct in #17536

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by aboch** [comment]
@ping abronan
Thanks for finding this.
Sorry I missed the inner struct in my previous PR.

**Comment by abronan** [comment]
Thanks @aboch. Will test it :+1: 

/cc @dnephin @vieux

**Comment by dnephin** [comment]
Compose is not affected by this change

**Comment by abronan** [comment]
Tested and works for Swarm, LGTM.

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
Ping @moxiegirl for out-of-band docs check

**Comment by moxiegirl** [comment]
@tiborvass I'll check this and add any changes to #17340

**Comment by abronan** [comment]
@moxiegirl :+1:

**Pull request merged**
