### PR TITLE
Replace the vendored aanand/compose-file with a local copy

### PR DESCRIPTION
**Pull request by dnephin**
We need to use code from `docker/docker` to parse ports, and avoiding cyclical dependencies is nice, so I guess we have to bring this code in to the repo.

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
@dnephin should we have a validation script for the generated schema go file using `bindata`

Otherwise seems good to me :)

**Comment by dnephin** [comment]
@vdemeester I'm not sure what you mean. What would we validate?

**Comment by vdemeester** [comment]
If someone change the `schema.json` but does not update the `schema.go` file.

**Comment by dnephin** [comment]
Ah, the problem is that bindata includes a timestamp, so we can't just re-run `go generate` like we do for others and check to see if the file changed. Every time we run it it makes changes to the file.

I'll see if there is some way to prevent the timestamp.

**Comment by dnephin** [comment]
Ok, I've removed the metadata and added a hack/validate

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
