### PR TITLE
Add bash completion for new prune commands

### PR DESCRIPTION
**Pull request by albers**
This adds bash completion for

* `docker system prune`
* `docker container prune`
* `docker image prune`
* `docker volume prune`
* `docker network prune`

Ref: #26108, #27525

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐶
/cc @AkihiroSuda @thaJeztah @justincormack

**Review by AkihiroSuda — APPROVED** [review]
Tested locally and LGTM

**Comment by albers** [comment]
@vdemeester Please schedule for 1.13.0

**Comment by thaJeztah** [comment]
@albers I added the PR's to the milestone. Note that the initial RC for 1.13 will be branched from master, so cherry-picking is only needed for changes after the code freeze (after 1.13.0-rc1 is released)

**Comment by albers** [comment]
@thaJeztah Thanks!
I took the omnipresence of 1.13.0 labels for a sign that the release branch already exists.

**Comment by thaJeztah** [comment]
@albers adding the milestones never hurts, I regularly add them also for easier tracking in future :-) (e.g. to find out which release a PR was included in)

**Pull request merged**
