### PR TITLE
Fix check code for --cluster-store and --cluster-advertise in config_…

### PR DESCRIPTION
**Pull request by ncoolz**
**\- What I did**
I fixed the issue which was brought up from https://github.com/docker/docker/pull/23524#discussion_r68729838 .

**\- How I did it**
I just changed(in fact, 'restored') code to `config.ClusterStore != "" || config.ClusterAdvertise != ""`. 

**\- How to verify it**
On swarm mode, it should throw an error when restarting a docker daemon with added --cluster-store option and --cluster-advertise. I tested it and that worked.

```
FATA[0001] Error creating cluster component: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode
```

**\- Description for the changelog**
Fixed https://github.com/docker/docker/pull/23524#discussion_r68729838

**\- A picture of a cute animal (not mandatory but encouraged)**
331757576t06140236068054

Signed-off-by: Wonjun Kim wonjun.kim@navercorp.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Can you add a test to the swarm integration tests to make sure this errors out?

**Comment by ncoolz** [comment]
@cpuguy83 I added a test. Please review my commits. Thank you.

**Comment by aboch** [comment]
Thanks @ncoolz for finding and fixing this.

change looks good to me

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Pull request merged**
