### PR TITLE
[17.03] finish updating binaries-commits containerd to commit 6c46389

### PR DESCRIPTION
**Pull request by andrewhsu**
This PR finishes what was started in PR #33528 [17.03] Update containerd to version 6c463891b1ad274d505ae3bb738e530d1df2b3c7

Both the `vendor.conf` and `hack/dockerfile/binaries-commits` files should have been updated at the same time. ♊️ 

cc @mlaventure

### CODE REVIEW

**Comment by thaJeztah** [comment]
I think this is correct, but prefer to have it double checked by @mlaventure @crosbymichael 

diff is; https://github.com/docker/containerd/compare/4ab9917febca54791c5f071a9d1f404867857fcc...6c463891b1ad274d505ae3bb738e530d1df2b3c7

**Comment by mlaventure** [comment]
Yes, it's correct, my bad for forgetting about it.

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
