### PR TITLE
Adding a README.md for the hack folder.

### PR DESCRIPTION
**Pull request by sh-abhi**
Signed-off-by: Abhishek Sharma <abhishek@asharma.me>

- What I did
Added a README.md for the hack folder

- How I did it
Went through the shell scripts already provided. I did notice there is a fair bit of documentation contained within the scripts, so I used that as a reference when writing the README. Please note that there are other folders in hack, not too sure if we want to document that in this README? Open to suggestions on this!

- How to verify it
I accidentally committed the README without signing it, but revert and committed again with my signature. Please let me know if this is an issue; happy to fix this until it satisfies the requirements.

- Description for the changelog
Adding in a README file within the hack folder to provide some insight on the scripts within.

- A picture of a cute animal (not mandatory but encouraged)
Next PR :)

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I think we need to clarify that these files are not intended be run manually.

Also, we need a link to https://docs.docker.com/opensource/project/test-and-docs/

**Comment by abhishek7** [comment]
@AkihiroSuda agreed, will clarify that none are intended to be run manually.

A bit confused on the second part, are we saying that we want to just reference that URL in the README itself? Or are we saying that we need to build the docs as suggested within the mentioned page?

**Comment by AkihiroSuda** [comment]
I think just reference is ok so as to clarify how developers can invoke hack scripts via `make`

**Comment by abhishek7** [comment]
Just updated my branch, the PR should update as well.

**Comment by abhishek7** [comment]
Going to close and reopen this; has not updated with my new commits for some reason?

**Comment by abhishek7** [comment]
@AkihiroSuda reopened this: https://github.com/moby/moby/pull/32730

**Pull request closed without merging**
