### PR TITLE
fix docker-proxy not statically linked

### PR DESCRIPTION
**Pull request by thaJeztah**
Partial carry of https://github.com/moby/moby/pull/43492, but only taking the first 2 commits

### CODE REVIEW

**Comment by thaJeztah** [comment]
No segfaults now I think, but one failure that _could_ still be genuine;

```
 === FAIL: libnetwork/drivers/bridge TestQueryEndpointInfo (0.39s)
[2022-05-20T08:50:20.869Z] time="2022-05-20T08:47:47Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge/net1/ is not added to the store"
[2022-05-20T08:50:20.869Z] time="2022-05-20T08:47:47Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/ep1/ is not added to the store"
[2022-05-20T08:50:20.869Z] time="2022-05-20T08:47:47Z" level=warning msg="Failed to allocate and map port 23000-23000: Error starting userland proxy: "
[2022-05-20T08:50:20.869Z]     bridge_test.go:665: Failed to program external connectivity: Error starting userland proxy: 
```

**Comment by thaJeztah** [comment]
The other failure is a known flaky;

```
=== RUN   TestDockerSwarmSuite/TestSwarmLockUnlockCluster
    docker_cli_swarm_test.go:1112: [deafd89436346] joining swarm manager [d98c044a4dea8]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2478
    docker_cli_swarm_test.go:1113: [d1f5c6938d03f] joining swarm manager [d98c044a4dea8]@0.0.0.0:2477, swarm listen addr 0.0.0.0:2479
    docker_cli_swarm_test.go:1001: timeout hit after 1s: first check never completed
    daemon_swarm.go:162: assertion failed: error is not nil: error during connect: Get "http://%2Ftmp%2Fdocker-integration%2Fd98c044a4dea8.sock/v1.42/info": EOF: get swarm info
    --- FAIL: TestDockerSwarmSuite/TestSwarmLockUnlockCluster (66.10s)
```

**Comment by thaJeztah** [comment]
Linux tests completed, I kicked off another run to check if the first one was just a flaky, or an actual issue https://github.com/moby/moby/pull/43621#issuecomment-1132663482

**Review by crazy-max — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
thx! I'll merge this so that we have at least a static binary that runs on alpine, and doesn't SEGFAULT 😂 

We'll do further improvements later

**Pull request merged**
