### PR TITLE
fix: container name leading with slash issue

### PR DESCRIPTION
**Pull request by moypray**
Signed-off-by: Zhang Wentao zhangwentao234@huawei.com

### CODE REVIEW

**Comment by moypray** [comment]
fix issue:  https://github.com/docker/docker/issues/10996
As graphdb.Set() function will add '/' to 'name' if the fullname is not leading with slash.
So we do not need to save '/' in container.Name.

**Comment by thaJeztah** [comment]
Not entirely sure, but according to https://github.com/docker/docker/issues/7519#issuecomment-51863974, the leading slash is intentional. 

Also, there's another PR open to resolve #10996 here: https://github.com/docker/docker/pull/11003

**Comment by moypray** [comment]
hi @thaJeztah  I saw the fix you referred. That PR is different from mine, that PR just fix the "docker rename xxx" issue.
this PR fix:
docker run --ti --name=bar xxx
docker inspect bar  ==> Name: /bar     ## leading with '/'

but, after rename (using docker rename bar foo)  
docker inspect foo  ==> Name: foo    ## no '/' here!

It is very strange behavior.  
the reason is when handing Name segment of struct container, it will add '/' for the first time.
But I think it needn't to do so.

**Comment by thaJeztah** [comment]
Well both PRs mention they fix #10996, so that's confusing. I don't know if removing the `/` will have side effects (also see my earlier comment), perhaps someone else has more insight in this.

**Comment by moypray** [comment]
Yes, there is some other side effects. i will close this one.

Maybe fix them need to change some files.

**Pull request closed without merging**
