### PR TITLE
rename desired_state filter to desired-state

### PR DESCRIPTION
**Pull request by thaJeztah**
For consistency with other filters (such as "is-official"), this renames the desired_state filter to "desired-state".

as noted in https://github.com/docker/docker/pull/24120#issuecomment-229407458

this will conflict with https://github.com/docker/docker/pull/24125, once merged

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @docker/core-engine-maintainers PTAL

**Comment by vdemeester** [comment]
SGTM :angel:

**Comment by tianon** [comment]
+1!

**Comment by cpuguy83** [comment]
SGTM

**Comment by thaJeztah** [comment]
added "changelog" label, so that we can include it in the RC2 -> RC3 changelog

**Comment by thaJeztah** [comment]
rebased, PTAL

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
