### PR TITLE
Small fix and new option for contrib/mkimage_alpine.sh

### PR DESCRIPTION
**Pull request by shakeme**
With contrib/mkimage-alpine.sh it is now possible to:

1. Use the fixed parameter "-c" to set another additional repository.
2. Set the architecture manually if "uname -m" results in a different architecture string.

### CODE REVIEW

**Comment by shakeme** [comment]
Can someone help me getting forward with this pull request?

**Comment by cpuguy83** [comment]
@shakeme Can you squash and sign your commit? We can't really review until it's at least signed.

**Comment by shakeme** [comment]
@cpuguy83 I think i did it now. Can you please double check?

**Comment by cpuguy83** [comment]
Looks like there's still one extra commit.
This looks like it can be just one commit.
But yep, looks like it's got all the signatures it needs.

**Comment by cpuguy83** [comment]
ping @tianon

**Comment by tianon** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
