### PR TITLE
Windows:Bump HCSShim to v0.8.3

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Bumps Microsoft/hcsshim to v0.8.3.  The majority of changes in v0.8.3 are for cri/containerd, but this keeps moby in lock-step. In particular for moby, it solves an issue for IOT (@jiria FYI)

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@thaJeztah  @vdemeester PTAL.  @jterry75 FYI

**Review by thaJeztah — APPROVED** [review]
SGTM

@jhowardmsft following the discussion on https://github.com/moby/moby/pull/37638#discussion_r236893016, I assume none of the breaking changes were in code we currently use, so not a problem?

**Comment by jhowardmsft** [comment]
@thaJeztah No, we're being extremely careful not to break HCS v1 API compatibility as used by mody - almost all the churn in hcsshim relates to v2 API used by cri/containerd, or internal code refactoring.

**Comment by thaJeztah** [comment]
Thanks, all good then!

ping @vdemeester @cpuguy83 ptal

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
