### PR TITLE
Remove duplicated document

### PR DESCRIPTION
**Pull request by yuexiao-wang**
**- What I did**
Remove  docs/reference/commandline/deploy.md 

**- How I did it**

**- How to verify it**

**- Description for the changelog**
The docs/reference/commandline/deploy.md is duplicated document for docs/reference/commandline/stack_deploy.md 
which makes me confused

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @dnephin

**Comment by thaJeztah** [comment]
Both `docker deploy` and `docker stack deploy` exist (they're an alias), but I'm not sure which one should be documented, or both

**Comment by dnephin** [comment]
I think they should both exist, but one shsould just say "alias for ..."

**Comment by yuexiao-wang** [comment]
@dnephin @thaJeztah  PTAL
Updated this PR.

**Review by dnephin — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

but we may want to consider removing the actual content of this page, and to refer people to the `stack deploy` page for details.

/cc @mstanleyjones

**Pull request merged**
