### PR TITLE
testing: pkg/signal; remove redundant fmt.Sprintf()

### PR DESCRIPTION
**Pull request by thaJeztah**
just a minor nit 🤗

### CODE REVIEW

**Comment by thaJeztah** [comment]
whoops. forgot to remove the `%s` from the format string 😇 

actually; let me do a small rewrite to make this a subtest

**Review by fntlnz — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@yongtang @vdemeester ptal 🤗

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
