### PR TITLE
Don't invoke HCS shutdown if terminate called; removes unused vars and no-op calls

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

(Found while investigating #37562, although I have noticed it in the past)

Docker is erroneously calling HCS shutdown container if a terminate has already been called. While it doesn't cause any explicit errors in docker or the platform, it is semantically incorrect in terms of platform APIs, and causes various misleading red-herring errors in the docker debug log, the HCS analytic logs, and VMCompute ETW traces, thus making debugging harder when looking for real issues. 

To ensure thread safety, `terminateInvoked` is protected during reads and writes. To achieve that cleanly, it is necessary to modify the contract on both `shutdownContainer()` and `terminateContainer()` to ensure the libcontainerds-containers-mutex is held.  (This also makes the code far more consistent and less prone to someone accidentally introducing a deadlock in the future.)

It also cleans up two completely unused variables which are hang-overs from previous iterations of this code - `updatePending and  `manualStopRequested` which were in the internal container structure.

Finally it removes two unnecessary `DebugGCS()` calls in the WCOW create path. These are only meaningful for LCOW. Just code cleanup there - I think these were introduced incorrectly some time back when @mlaventure was refactoring this code circa 9 or 10 months back.

@johnstep @dmcgowan PTAL.

PS For a followup, it's probably worth renaming terminateContainer() to something more meaningful at a future point in time. It's actually only called during error paths for start and shutdown, and the "real" terminate is invoked asynchronously through `SignalProcess()` in the normal path. I found it somewhat confusing until I realised that nuance, not having looked at this code for some time. But I digress.... `takeOutBackAndShootContainerSynchronouslyDueToPreviousErrorDuringStartupOrShutdown()`? :innocent:

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@carlfischer1 This might be a good candidate for EE 18.03. It's not applicable to 17.06 as the libcontainerd codebase is quite different there.

**Review by mlaventure — APPROVED** [review]

**Comment by jhowardmsft** [comment]
Experimental failure is unrelated - this change is in Windows-only code. Restarted anyway.

**Comment by carlfischer1** [comment]
@jhowardmsft I've opened a backport request for EE 18.03

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
