### PR TITLE
Add zsh completion for 'docker build' multi tags

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #15780

In addition: Fix some others repeatable option

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks again @sdurrheimer, @vi PTAL

to maintainers: don't merge yet, because this should go in after https://github.com/docker/docker/pull/15780

**Comment by sdurrheimer** [comment]
Rebased and ready to be merged.

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
@sdurrheimer quick thinking here; the "fixes" in this PR probably should be in the 1.9 release (if possible), but the "multiple tag" feature will be part of 1.10

Can you move the *fixes* to a separate PR? that enables us to cherry pick the fixes in the 1.9 release without cherry-picking the new feature

(hope I'm making sense here :smile:)

**Comment by sdurrheimer** [comment]
@thaJeztah Done #17333 :)

**Comment by thaJeztah** [comment]
Thanks @sdurrheimer !

**Comment by thaJeztah** [comment]
LGTM, thanks @sdurrheimer !

**Pull request merged**
