### PR TITLE
Add zsh completion for 'docker inspect --type=plugin' and other missing ones

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #28967

Signed-off-by: Steve Durrheimer <s.durrheimer@gmail.com>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

/cc @vdemeester

**Review by vdemeester — CHANGES_REQUESTED** [review]
Could you add `--type=volume` too ? 👼

**Comment by sdurrheimer** [comment]
@vdemeester Done

**Review by vdemeester — APPROVED** [review]
LGTM 🐮
Thx @sdurrheimer 👼

**Pull request merged**
