### PR TITLE
Enable embedded DNS server to listen on IPv6

### LINKED ISSUE #41651: Feature request: IPv6-enabled embedded DNS server
**Feature request**: Docker's embedded DNS server is available over IPv6 in addition to the already-existing IPv4. Docker includes the IPv6 address of its embedded DNS name server when generating a containers `/etc/resolv.conf`.
Following the running example from below, the file's contents would be:
```
nameserver 127.0.0.11      # Docker's embedded DNS server, accessible over IPv4
nameserver fedc::1         # Docker's embedded DNS server, accessible over IPv6
options ndots:0
```
Of course, the actual local IPv6 address needs determining.

**Background**: Docker's embedded DNS server is hard-coded to be available at `127.0.0.11` over IPv4 only. This fact is encoded into containers' generated `/etc/resolv.conf` files. In our environments, the Docker daemon is configured in `/etc/docker/daemon.json` with the ISP's upstream IPv4 and IPv6 nameserver addresses. When Docker generates `/etc/resolv.conf` for a new container, the contents becomes:
```
nameserver 127.0.0.11      # Docker's embedded DNS server, accessible over IPv4
nameserver 2a00:0123::1    # Upstream ISP name server, accessible over IPv6
options ndots:0
```
Crucially, notice that the IPv4 nameserver is Docker's embedded DNS server, and that the IPv6 nameserver points to the ISP's upstream server. (Clarifying commentary trailing the `nameserver` directives was added by me.) _This state of affairs causes sporadic run-time faults when resolving the IP addresses of peer containers by their names._

**Discussion**: When an Alpine container attempts to resolve the IP address by the name of one of its peer containers, Alpine's MUSL performs parallel requests, sending A and AAAA queries over UDP to each of the configured nameservers all at once, and taking the first response.

Thus, when for example Alpine container `logic` attempts to connect to container `db`, the software first attempts to resolve the hostname `db` into an IP address in order to connect to it. MUSL does this by sending out a total of 4 queries in parallel, based on the above `/etc/resolv.conf`:

1. UDP request over IPv4 to Docker's embedded DNS server for the A record for `db.`. The Docker daemon is of course authoritative for `db.` and responds with its IP address.
1. UDP request over IPv4 to Docker's embedded DNS server for the AAAA record for `db.`. Again, Docker responds affirmatively.
1. UDP request over IPv6 to the ISP's nameserver for the A record for `db.`. Obviously the ISP is oblivious as to a host named `db.` run by one of its customers in a privacy-concealing environment; it returns `NXDOMAIN`.
1. UDP request over IPv6 to the ISP's nameserver for the AAAA record for `db.`. Again, the ISP returns `NXDOMAIN`.

You can observe this using `tcpdump -i any -n port 53 &` followed by `ping db -c 1` in a container setup on a bridge network with IPv6 enabled.

Now, due to network latency and myriad other reasons, the `logic` container receives Docker's IPv4-based embedded DNS responses generally before those of the ISP's IPv6 responses. Name resolution succeeds according to MUSL, and processing continues down its happy path. But every now and then the ISP's response packets arrive before those of Docker, and MUSL blissfully accepts the `NXDOMAIN` responses and reports name resolution failure back up to the software, ultimately causing a processing fault.

If Docker offered it's embedded DNS server over IPv6 as a first-class citizen alongside IPv4, name resolution would function properly.

**Our usage environment**:
- Docker version 19.03.13.
- Containers connected to custom bridge network with IPv6 enabled.
- Plenty of containers are based on Alpine Linux, whose MUSL performs DNS name resolutions by making parallel requests, one to each configured nameserver; this is MUSLs only mode of operation.
- Some services are at various stages of being IPv6 native (can only be resolved and accessed using IPv6).
- `/etc/docker/daemon.json` specifically configures the Docker daemon with the ISP's upstream DNS servers according to location:
```
{
  "dns": [
    "123.4.5.6",    # IPv4 address of the ISP's DNS server
    "2a00:0123::1"  # IPv6 address of the ISP's DNS server
  ],
  ...
}
```

Cheers!

### PR DESCRIPTION
**Pull request by TheBeeZee**
This change sets up the embedded DNS proxy on the IPv6 loopback address (::1). The requests are proxied to the same set of DNS servers (both IPv4 and IPv6), obtained from the host resolv.conf. The IPv6 DNS proxy is enabled even in IPv4-only containers as there doesn't seem to be any harm in doing so.

Currently when using custom networks, the resolv.conf created within a container will have a mix of the internal embedded DNS (127.0.0.11) and external IPv6 DNS servers (Google DNS by default). This frequently breaks resolution of internal names, because external DNS servers can't resolve intra-container names. It is particularly bad with containers using musl C library (i.e. Alpine Linux), because it parallelizes DNS queries to all available DNS servers. With this change the external IPv6 DNS servers are replaced by the IPv6 address of the DNS proxy (::1), which can resolve internal names.

fixes #41651 

```markdown changelog
Enable embedded DNS server to listen on IPv6
```

### CODE REVIEW

**Comment by robmry** [comment]
Hi @TheBeeZee ... thank you for taking a look at this. Getting those IPv6 addresses out of the container's `resolv.conf` is certainly something we need to do.

However, I don't think we can safely put our internal nameserver on the `::1` loopback address, in case someone wants to run their own DNS server in a container on that address. (With only one IPv6 loopback address, we don't have the option of putting our nameserver on a nonstandard address, like IPv4's `127.0.0.11`.)

Instead, the plan is to add IPv6 addresses from the host's `resolv.conf` (or the command line) to our internal nameserver's list of upstream servers - but leave it running on the IPv4 address. So, there won't be any IPv6 in `resolv.conf`, avoiding the race in musl-libc's resolver.

That's high on the todo list now - I hope to get a chance to look at it in the next week or two, and I think @akerouanton may already have a draft change for it.

**Comment by corhere** [comment]
> If the internal resolver is only available on an IPv4 address, that means that users have to deploy dual stack even though they don't have/want to otherwise.

The internal resolver listens on an IPv4 _loopback_ address. If the internal resolver is only available on an IPv4 loopback address, containers will have to have a loopback interface with an IPv4 address to reach the resolver. Linux's IPv6 stack depends on its IPv4 stack; you cannot disable IPv4 without disabling IP connectivity as a whole. Furthermore, the kernel automatically adds the 127.0.0.1 address to the loopback interface. You would have to remove it manually, and a lot of software would break if you did.

"Dual stack" is a property of the network, not the host. A host (or container) can be connected to a mix of networks with IPv4 connectivity, IPv6 connectivity, or both. Having the internal resolver listen on an IPv4 loopback address imposes no constraints on whether or not a container can be attached to an IPv6-only container network, therefore users will not have to deploy dual-stack if they don't want to.

**Comment by TheBeeZee** [comment]
While it is not possible today to create an IPv6-only Docker network and Linux always assigns 127.0.0.1 to the loopback interface, that doesn't mean it will always be like this in the future. Even today it is entirely possible to delete all IPv4 addresses from all interfaces within a container (just to simulate what would happen in a true IPv6-only environment).

Here's an example. First, create a Docker network with IPv6 enabled and create a container. Then, from the host, delete all IPv4 addresses from the container (can't do that from within the container):

sudo nsenter --all -t 357773
***@***.***:/# ip -4 addr flush dev eth0
***@***.***:/# ip -4 addr flush dev lo
***@***.***:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
51: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:10:01:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fd98:d03f:9e21::2/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe10:102/64 scope link 
       valid_lft forever preferred_lft forever

Then within the container:

***@***.***:/etc# echo >resolv.conf nameserver 127.0.0.11
***@***.***:/etc# cat resolv.conf
nameserver 127.0.0.11
***@***.***:/etc# dig www.google.com
;; UDP setup with 127.0.0.11#53(127.0.0.11) for www.google.com failed: network unreachable.
;; no servers could be reached

;; UDP setup with 127.0.0.11#53(127.0.0.11) for www.google.com failed: network unreachable.
;; no servers could be reached

;; UDP setup with 127.0.0.11#53(127.0.0.11) for www.google.com failed: network unreachable.
;; no servers could be reached

**Comment by TheBeeZee** [comment]
On Mon, Feb 26, 2024, at 11:02 AM, Cory Snider wrote:
> 
> 
>> Even today it is entirely possible to delete all IPv4 addresses from all interfaces within a container
>> 
> Yes, but why would you want to?
> 

To simulate an environment that can't be created with today's tools (i.e. a Docker network without IPv4) and demonstrate what happens with DNS resolution (if there's any doubt).

>> (just to simulate what would happen in a true IPv6-only environment).
>> 
> What is a *true* IPv6-only environment, exactly? <https://en.wikipedia.org/wiki/No_true_Scotsman> Do you have an example of one in the wild?
> 

A true IPv6-only environment is one in which no IPv4 addresses are present, including the loopback address.

While the Linux kernel might make it impossible to remove the IPv4 stack today, it might not be this way in the future. The reasons for that could be security (keeping unused code in the kernel unnecessarily increases the attack surface) and memory utilization (matters in embedded environments).

Again, I'm not arguing that any of this is true today, but being a little bit forward thinking here might save work later.

**Comment by robmry** [comment]
> Again, I'm not arguing that any of this is true today, but being a little bit forward thinking here might save work later.

It would increase the work now by adding something that we'd need to cover in regression testing, for no clear benefit.

Also - the musl's resolver's parallel lookups are based on the expectation that they point at [diverse nameservers](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS). Listing the internal nameserver twice would result in every request being duplicated. So, we'd need some way to determine whether to add the resolver's IPv4 or IPv6 address - and we don't currently have a way to determine whether IPv4 is available, because it always is.

So, I think the absence of IPv4 is something we'll need to deal with when it's a concrete issue.

**Comment by TheBeeZee** [comment]
Good point about the duplication of DNS requests. While that will not be a problem in majority of cases, it could cause issues in an environment with high load on the DNS servers.

A potential fix would be to only forward to IPv4 servers from the IPv4 loopback and the IPv6 servers from the IPv6 loopback.

Anyway, fair enough about IPv6-only. I'll be happy with whatever solution there is for the current musl-libc issue.

**Pull request closed without merging**
