### PR TITLE
Docker Registry Server > Docker Registry

### LINKED ISSUE #12516: Fix registry doc top level and also the redirect issue
- Distribution team wants the top level to be docs.docker.com/registry
- Also need a redirect from docs.docker.com/registry/overview > docs.docker.com/registry

### PR DESCRIPTION
**Pull request by moxiegirl**
Fixing registry index Fixes #12516 
Tested on beta and this redirect works

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @thaJeztah @docker/docs-owners 

/cc @dmp42 @stevvooe @bfirsh 

http://beta-docs.docker.io/registry/overview should redirect to http://beta-docs.docker.io/registry

**Comment by thaJeztah** [comment]
Confirmed that the test docs redirect correctly. LGTM

thanks, @moxiegirl !

**Comment by moxiegirl** [comment]
Thank you sir! Author LGTM

**Comment by fredlf** [comment]
Have we changed the rules so that docs changes no longer require two maintainer LGTMs?

**Comment by moxiegirl** [comment]
As I understand it from @icecrime @thaJeztah can LGTM issues including docs.

**Comment by thaJeztah** [comment]
@fredlf no, and you're right, this should have waited for a docs LGTM. I'm happy to check for possible issues, but perhaps I shouldn't include "LGTM", just a "looks good", to prevent this confusion.

Let me know what you think.

**Comment by thaJeztah** [comment]
@moxiegirl I'm not 100% sure, perhaps we should discuss this, I don't want want to cause trouble because of this :)

**Comment by moxiegirl** [comment]
@thaJeztah No worries. I'm gonna double check but I'm pretty certain he said yes; I had meant to see that you got added to doc maintainers list too but things got busy.

**Comment by thaJeztah** [comment]
@moxiegirl alright. Thanks for checking, I'm all for clear procedures, so thanks @fredlf for paying attention!

**Comment by fredlf** [comment]
I'm not fussed about this PR, or anything, really. Just making sure we adhere to our own rules and that I didn't miss a change somehow. 
I do believe that in order to maintain quality and transparency we should continue to require two docs maintainer LGTMs (or one, if the author of the PR is a docs maintainer).

**Comment by thaJeztah** [comment]
@fredlf agreed; especially large textual changes; I can help spotting typos and small mistakes, but proper form / writing style should definitely be checked by a docs maintainer.

I'm open for suggestions, though. If there are ways for me to smoothen the process, I'm all ears.

**Comment by fredlf** [comment]
I should add, I'm *more than* happy to add more docs maintainers, too!

**Comment by thaJeztah** [comment]
@fredlf yes, I think it's needed; even then, (if I'm on the list), I know my limitations :)

**Pull request merged**
