### PR TITLE
cli: remove unnecessary initErr type

### PR DESCRIPTION
**Pull request by LK4D4**
**\- What I did**
Removed unnecessary initErr type. It closes #22754 
**\- How I did it**
Took @runcom suggestion from #22754 and applied it
**\- How to verify it**
Compile docker and try commands
**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**
cat

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @aaronlehmann @runcom @vdemeester

**Comment by LK4D4** [comment]
Ok, it doesn't work :D

**Comment by runcom** [comment]
LGTM (assuming the other way @aaronlehmann isn't feasible)

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
