### PR TITLE
Vendoring libnetwork 3e31cead05cba8ec20241630d051e6d73765b3a2

### PR DESCRIPTION
**Pull request by aboch**
- Fix a couple of bugs introduced by previous libnetwork vendoring:
  - in bitseq which prevents to use experimental overlay networking
  - in docker service ls cli o/p
- Add missing http subrouter for newly introduced sandboxes
- Fix fragmentation issue on vxlan header addition for overlay network driver
- Remove libnetwork test code utilities from vendoring

Relevant PRs:
[Move test specific functions to a testutils package. #499](https://github.com/docker/libnetwork/pull/499)
[Fix bug for docker service ls #498](https://github.com/docker/libnetwork/pull/498)
[Fix bitsequence set() #496](https://github.com/docker/libnetwork/pull/496)
[For the endpoints on overlay network set the MTU to 1450 to avoid fra… #491](https://github.com/docker/libnetwork/pull/491)
[Do not import testing in the main binary. #484](https://github.com/docker/libnetwork/pull/484)

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by mavenugo** [comment]
@aboch as suggested in https://github.com/docker/libnetwork/pull/501, can you please add a sub-router hook for the newly added sandboxes api in https://github.com/docker/docker/blob/master/api/server/server_experimental_unix.go ?
There is a few changes coming to these shortly. But in order to keep the existing experimental features working, i think we should have this fixed now.

**Comment by aboch** [comment]
@mavenugo Thanks, I will add it shortly.

**Comment by aboch** [comment]
Taken care of adding sandboxes route to http sub-router. 
PTAL when you get a chance. Thanks.

**Comment by jfrazelle** [comment]
LGTM @mavenugo feel free to merge if you approve

**Comment by mavenugo** [comment]
Thanks @aboch. LGTM.

**Pull request merged**
