### PR TITLE
Sync with Dockerfile

### PR DESCRIPTION
**Pull request by hqhq**
Add support for seccomp, and updated some commit numbers.

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Can you please bring the registry bits up to date with this: https://github.com/docker/docker/blob/master/Dockerfile#L152

Otherwise, `DockerSchema1RegistrySuite` won't work.

**Comment by hqhq** [comment]
@aaronlehmann Commit ec87e9b6971d831f0eff752ddb54fb64693e51cd in https://github.com/docker/docker/blob/master/Dockerfile#L156 seems not in master, but buildable distribution should be after:
```
commit 5b550f919ff72fa7e3b0ad355d81154fc50af26c
Author: Liu Hua <sdu.liu@huawei.com>
Date:   Sat Dec 26 18:31:50 2015 +0000

    update panicwrap package to fix building error on aarch64 platform

    Linux on aarch64 lacks of dup2, uses dup3 instead

    Signed-off-by: Liu Hua <sdu.liu@huawei.com>
```
Is that still a schema1 version?

**Comment by aaronlehmann** [comment]
Yes, 5b550f919ff72fa7e3b0ad355d81154fc50af26c should work.

Feel free to update the other Dockerfiles to use that revision for consistency.

**Comment by hqhq** [comment]
@aaronlehmann Thanks, updated.

**Comment by hqhq** [comment]
@aaronlehmann According to Jenkins failure, is that because 5b550f919ff72fa7e3b0ad355d81154fc50af26c is not working on schema1?

**Comment by aaronlehmann** [comment]
Apparently so. I think you need a commit that's older than cb6f0023500c3d2afb8c9f3ee4a0097526192156.

**Comment by hqhq** [comment]
@aaronlehmann Too bad looks like old version which support schema1 manifests is not working on ARM64, we should probably skip these integration-cli tests for schema1 manifests on ARM64.
Updated this PR.

**Comment by hqhq** [comment]
ping @tianon @jfrazelle

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
