### PR TITLE
Vendoring libnetwork for 1.12.3

### PR DESCRIPTION
**Pull request by aboch**
- It includes few bug fixes which prevent
  a deadlock, a panic, a couple of races,
  and a regression.

The related docker issues are: #27323, #27486
The other libnetwork PR are: https://github.com/docker/libnetwork/pull/1495, https://github.com/docker/libnetwork/pull/1503, https://github.com/docker/libnetwork/pull/1504

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by mavenugo** [comment]
@aboch thanks. can u pls point to the corresponding docker issues that this fixes ? We need that for release-notes

**Comment by aboch** [comment]
@mavenugo done

**Comment by mrjana** [comment]
LGTM

**Comment by mavenugo** [comment]
LGTM

**Comment by mavenugo** [comment]
@mrjana do you know if the IT failure in powerpc is genuine ? I couldnt think of a reason how it will succeed in janky and experimental but fail in powerpc.

@thaJeztah is this a new CI addition ?

**Comment by tophj-ibm** [comment]
@mavenugo the power job was started manually (just like arm or z). Test failure is a known flaky test on non-x86 arches #26601, I'll rebuild it just to make sure.

**Review by vdemeester — APPROVED** [review]
LGTM 🐸 assuming it's green :stuck_out_tongue_closed_eyes:

**Comment by mavenugo** [comment]
@tophj-ibm thanks for the confirmation. Is the test started manually for all the open PRs ?

Given that it is tracked by https://github.com/docker/docker/issues/26601 , am fine with merging this.

**Comment by tophj-ibm** [comment]
@mavenugo it's not started for all open PRs, no. My colleague @clnperez, or myself will normally start one on any big-pr, a vendor, or anything that touches multi-arch, just to make sure that they don't accidentally break something. 

Also feel free to merge, only the flaky test is failing.

**Pull request merged**
