### PR TITLE
add fedora 23 

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @tianon

**Comment by jfrazelle** [comment]
and I'll let @tiborvass decide if this is 1.9.1 worthy

**Comment by runcom** [comment]
me wants dis :smile:

**Comment by tianon** [comment]
LGTM

**Comment by pwnall** [comment]
I would appreciate a 1.9 release for fedora-23 as well!

**Pull request merged**
