### PR TITLE
Fix response hijacking with TLS enabled.

### LINKED ISSUE #19280: run/exec with -it fails on remote 1.10 client with TLS
Using a top-of-tree daemon, and a remote client, it appears the `-it` flag is broken on the new client.  If you use an old 1.9.X client against the same daemon, it works.

`docker run --rm -it busybox sh` - appears to hang

`docker run -d busybox sleep 1h` works, and if you then `docker exec -it ...` into that container using an older client, you see it started correctly.

My server build:

```
Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   09510c7
 Built:        2016-01-12T22:29:53.703167060+00:00
 OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by calavera**
- Vendors engine-api 0.2.2
- Fixes #19280

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tiibor @cpuguy83 for review :+1:

**Comment by tiborvass** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by cpuguy83** [comment]
Merging, failures are unrelated.

**Pull request merged**
