### PR TITLE
migrate service update integration tests from integration-cli to integration/service package

### PR DESCRIPTION
**Pull request by adshmh**
This is a follow up PR on #37492 (closed and reverted due to 2 flaky tests). This PR attempts to fix that by polling the update state of the service.

**- What I did**
Refactored and moved service update integration tests from the `integration-cli` package to `integration/service`

**- How I did it**
Removed the integration test file `integration-cli//docker_cli_service_update_test.go` and added new test file `integration/service/update_test.go` with corresponding tests.

**- How to verify it**

**- Description for the changelog**
Service update integration tests have been moved from integration-cli to integration/service package.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by boaz0 — COMMENTED** [review]
LGTM :100:

**Comment by ripcurld** [comment]
CI failed on `TestServiceUpdateConfigs` and `TestServiceUpdateSecrets` which are related to this change.

**Comment by adshmh** [comment]
Thank you for the reviews, I will look into failures.

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by vdemeester** [comment]
@adshmh needs a rebase though :angel:

**Review by AkihiroSuda — APPROVED** [review]
LGTM but needs rebase

**Review by yongtang — APPROVED** [review]
LGTM. @adshmh Can you do a rebase?

**Comment by adshmh** [comment]
@yongtang thank you for the review. I think 2 of the tests are flaky and it is not clear why yet, so I am looking into the cause. So far the test failures have not happened on my local builds over several re-runs.

**Comment by olljanat** [comment]
@adshmh this one needs to be rebased

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Review by thaJeztah — APPROVED** [review]
rebased; changes LGTM

let's merge on green 👍

**Comment by olljanat** [comment]
z looks to be failed to:
```
07:40:41 --- FAIL: TestServiceUpdateConfigs (2.90s)
07:40:41     daemon.go:296: [d954a5785d31c] waiting for daemon to start
07:40:41     daemon.go:328: [d954a5785d31c] daemon started
07:40:41     update_test.go:188: assertion failed: error is not nil: Error response from daemon: rpc error: code = Unknown desc = update out of sequence
07:40:41     daemon.go:283: [d954a5785d31c] exiting daemon
07:40:41 FAIL
07:40:41 ---> Making bundle: .integration-daemon-stop (in bundles/test-integration)
07:40:44 Clearing AppArmor profiles cache:.
``´
which I have not seen earlier but let's see if rebuild helps

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by thaJeztah** [comment]
Same failure again; odd 🤔

**Comment by adshmh** [comment]
Sorry for the delay in response. The service update tests still seem flaky, even though I have added a polling function to check on the status of the service.  This time, `TestServiceUpdateConfigs` passed, but `TestServiceUpdateSecrets` failed, both of which use the same polling function to verify service status, before issuing subsequent update calls. 

Currently looking at the service update command on docker CLI repo, as well as swarmkit repo, to find out if there are any other conditions to check after a service update API call before issuing the next one.

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by olljanat** [comment]
These have not been flaky earlier. Maybe some temporary issue on server. Let's try once more...

**Comment by AkihiroSuda** [comment]
ready to merge?

**Comment by olljanat** [comment]
@AkihiroSuda afaik, yes.
@thaJeztah said week ago
> let's merge on green +1

**Pull request merged**
