### PR TITLE
Enable Go Modules

### PR DESCRIPTION
**Pull request by slonopotamus**
**- What I did**

Enabled Go Modules support. The reason why this was not possible before ("Moby uses CalVer instead of SemVer") is no longer valid since v23.0.0

**- How I did it**

Renamed `vendor.mod` to `go.mod` and `vendor.sum` to `go.sum`.

**- How to verify it**

Everything should continue to work and build as before. IDEs and other tooling now properly understand Moby dependencies.

This change also allows to enable Dependabot for Moby repository.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by slonopotamus** [comment]
I'm not sure where [`make -o build validate-no-module`](https://github.com/moby/moby/actions/runs/5756011599/job/15614853243?pr=46153) CI job comes from. Possibly it just needs to be deleted (because we _are_ a Go module now)?

**Comment by vvoland** [comment]
Each script from `hack/validate` is picked up as a `validate-` step by `validate-prepare`:
https://github.com/moby/moby/blob/eb3ace962d4dbbc485ffdaee8aa589de1c88c094/.github/workflows/test.yml#L76

https://github.com/moby/moby/blob/eb3ace962d4dbbc485ffdaee8aa589de1c88c094/.github/workflows/test.yml#L115


So yes, in this case deleting it is a correct thing to do.

**Comment by slonopotamus** [comment]
WRT `TestPluginAddHandler`/`TestPluginWithNoManifest` CI failures: I believe they are unrelated to current PR. Both those tests claim to be able to run in parallel, however they mutate global `storage` variable without any mutexes. This doesn't look safe.

**Comment by slonopotamus** [comment]
[This failure](https://github.com/moby/moby/actions/runs/5760090676/job/15615796298?pr=46153) also doesn't look related, possibly just flaky test. Unfortunately I do not have permissions to return CI.

**Review by crazy-max — CHANGES_REQUESTED** [review]
Thanks but there are more things to do to be compliant than just renaming few files. See https://github.com/docker/cli/pull/4116/files.

We also need to handle circular dependencies as we need to change the imports. See the extended explanation of @thaJeztah about this: https://github.com/docker/cli/pull/4116#issuecomment-1492980108

**Comment by metux** [comment]
In my PR #42429, I'm generating go.mod from vendor/modules.txt by a little grep/sed magic.

**Pull request closed without merging**
