### PR TITLE
Adding Jim Weirich

### PR DESCRIPTION
**Pull request by purp**
**- What I did**
Added Jim Weirich's surname to the name generator

**- How I did it**
Modified `names-generator.go` to add a properly formatted additional entry to the `right` array.

**- How to verify it**

**- Description for the changelog**

Added Jim Weirich's surname to the name generator.

**- A picture of a cute animal (not mandatory but encouraged)**
Will this do?

The Real Yoshi

_source: https://twitter.com/jimweirich/status/262425624281505793/photo/1_

### CODE REVIEW

**Comment by purp** [comment]
p.s. I feel certain that @jamesgolick (noted [here](https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go#L386-L387)) would have approved.

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Looks like the commits miss a DCO sign-off, which makes CI fail. 

Could you;

- squash the commits and fix the DCO sign-off in the commit message? Using your real name (not your github alias); https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
- also add a woman to this list; https://github.com/moby/moby/blob/06ca1606e1a09c36bd12ed503b4c99d8a17ca230/pkg/namesgenerator/names-generator.go#L121

**Comment by cpuguy83** [comment]
❤️  Jim.

**Comment by tianon** [comment]
Thank you so much for taking the time to make this contribution!  We're very sorry for how long it has taken us to come to a decision on it, but as of https://github.com/moby/moby/pull/43210 the `namesgenerator` package is now officially "frozen" against new additions.  There is some explanation there as to why it is frozen (and why it has taken us so long to come to a decision on PRs like yours 🙈), but https://github.com/moby/moby/pull/43210#issuecomment-1029934277 is especially good for a longer explanation. :heart:

**Pull request closed without merging**
