### PR TITLE
Update volumes userguide

### LINKED ISSUE #15644: API/inspect container no longer returns path in Volumes map
As of 1.8.x, inspecting a container no longer returns the path to the persistent volume under the `Volumes` map, but instead in the `Mounts` slice (therefore unkeyed!) entries. For example:

```json
 "Volumes": {
            "/etc/nginx/certs": {},
            "/var/cache/nginx": {}
        },
```
...
```json
"Mounts": [
         {
            "Name": "bb9d6cf96309ae1c15984764a148022395edf1fa3f9399a8a99c3763be2fa612",
            "Source": "/var/lib/docker/volumes/bb9d6cf96309ae1c15984764a148022395edf1fa3f9399a8a99c3763be2fa612/_data",
            "Destination": "/var/cache/nginx",
            "Driver": "local",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "ec61b53e4faf593997241230429e19a3b2d956dfb56ee87eacf80e5fd5773b99",
            "Source": "/var/lib/docker/volumes/ec61b53e4faf593997241230429e19a3b2d956dfb56ee87eacf80e5fd5773b99/_data",
            "Destination": "/etc/nginx/certs",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
```

Note that the documentation still states that the `Volumes` map contains the host path and r/w status.

### PR DESCRIPTION
**Pull request by tonistiigi**
Fixes #15644 

Original change for reference: #13711

cc @moxiegirl 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks Toni!

I'm adding this to the 1.8.2 milestone if docs will be cherry-picked there

**Comment by moxiegirl** [comment]
LGTM --- @thaJeztah good point I don't have a milestone for the cp  @tonistiigi Thank you for the contribution it will get in in the cp.

**Comment by jamtur01** [comment]
A lot of folks use:

    docker inspect -f {{ .Volumes }}

And now it's an array/map it might be worth mentioning how to replaced this?

**Comment by thaJeztah** [comment]
@jamtur01 good point, not sure what the best place for that would be, the release notes itself? (I suggested creating a "migration guide" in another issue, maybe we should have one).

**Comment by jamtur01** [comment]
@thaJeztah Throw a paragraph and an example in this document? My Go templating is shite but maybe?

```go
    docker inspect -f "{{range .Mounts}}{{.}}{{end}}" $INSTANCE_ID
```

**Comment by thaJeztah** [comment]
@jamtur01 yeah, think that could work. Will see if I can find some time tomorrow for a PR. Thanks!

**Comment by md5** [comment]
I'd suggest this:

```console
$  docker inspect -f "{{json .Mounts}}" $INSTANCE_ID
```

**Comment by jamtur01** [comment]
Is there a prettyprint for Go JSON in a template? Google fails me.

**Comment by md5** [comment]
@jamtur01 No, but since the `json` function is being added in the Docker code [here](https://github.com/docker/docker/blob/7674f2168642f0c9012e20db8ac27ce09ecb2983/api/client/inspect.go#L17), it would be pretty straightforward to have a function like `prettyJson` that calls [`json.MarshalIndent`](http://golang.org/pkg/encoding/json/#MarshalIndent) in addition to the current `json` function.

**Comment by cpuguy83** [comment]
@md5 Or just use MarshalIndent anyway. I don't think there's a reason not to do this. It shouldn't affect any parsing by 3rd parties.

**Comment by md5** [comment]
@cpuguy83 The current output using the “json' function always comes out
with one container per line if multiple containers are inspected, so that
could be a breaking change for some users.

**Comment by cpuguy83** [comment]
Ugh, improper json....

**Comment by md5** [comment]
@cpuguy83 Since there's no reasonable way to get valid JSON in the multiple argument case, I think a bit of invalidity should be forgiven.

"Line-delimited" JSON is pretty common for log files, etc, so stuff like `docker inspect -f '{ "Name": {{ json .Name }}, "NetworkSettings": {{ json .NetworkSettigns }} }' $CONTAINER1 $CONTAINER2` seems reasonable to me.

**Comment by calavera** [comment]
Cherry picked into #15809

**Pull request merged**
