### PR TITLE
Fixing issue of "docker logs" stuck failure with bad command format

### LINKED ISSUE #31373: Container stops after logs are piped to failing command
**Description**

When `docker logs <container>` is piped to a command that fails the container hangs, and docker has to be restarted to recover. 

**Steps to reproduce the issue:**
```
$ docker run -d --name=failure alpine /bin/sh -c "while true; do date; done"
642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
59247
```
--- wait ?30+ seconds?
```
$ docker logs failure --tail 10
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017
Mon Feb 27 03:27:10 UTC 2017

$ docker logs failure |grep -10
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

$ docker logs failure --tail 10
```
....nothing.... 
ctrl+c
```
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
165360
$ cat /var/lib/docker/containers/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f/642305b0dc0d36553362b3d48fd6e06919d475e91545625ac4dc47a22d0f9e1f-json.log | wc -l
165360

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
642305b0dc0        alpine              "/bin/sh -c 'while..."   52 seconds ago      Up 51 seconds                           failure

$ docker stop failure
failure

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
642305b0dc0        alpine              "/bin/sh -c 'while..."   About a minute ago   Up About a minute                       failure

$ systemctl restart docker
$ docker ps --all |grep failure
642305b0dc0        alpine                  "/bin/sh -c 'while..."    2 minutes ago       Exited (137) 22 seconds ago                                    failure
```

**Describe the results you received:**
When `docker logs <container>` is piped "|" to a command that fails... the container fails and the docker service must be restarted.

**Describe the results you expected:**
The command should fail, but the container should not be effected. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 19
 Running: 1
 Paused: 0
 Stopped: 18
Images: 39
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.678 GiB
Name: x1
ID: YY5M:Q3IW:GK7S:C3F2:JGQN:UZ7F:BP2F:MC4T:5U7J:6QAT:VVQC:DCCF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04, Physical Host, 8GB Ram, 4CPU

### PR DESCRIPTION
**Pull request by catinthesky**
Refining l.mu.Unlock() statements in method readLogs of file
daemon/logger/jsonfilelog/read.go to more reasonable position to fix the issue exposed problem. 

fixes :#31373

(The issue exposed  can also be fixed  by commit fb2bb36)

Signed-off-by: Yao Zaiyong <yaozaiyong@hotmail.com>

**- What I did**
Fixing the problem of "docker logs cid --tail number" stuck when its previous command with bad format
**- How I did it**
Refining "l.mu.Unlock()" statement in method "readLogs" of file "daemon/logger/jsonfilelog/read.go" to make the lock released under abnormal scenario like in this issue reported case. 

**- How to verify it**
Before fix, following command failed (make sure the docker code doesn't include   commit fb2bb36 which happens to fix this problem also):

1. execute "docker run -d --name=failure alpine /bin/sh -c "while true; do date; done"" and wait 30 seconds longer to ensure enough log information collected.
2.  docker logs failure |grep -10  
3. docker logs failure --tail 10 , this command would stuck due to command in step 2 not having the lock released.
After fix, the above problem disappeared.

**- Description for the changelog**
Fixing "docker logs cid --tail number" stuck failure if its previous command (like:  docker logs failure |grep -10 ) with bad format.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by allencloud** [comment]
inegration ci fails 
```
07:05:43 ++ go test -c -o /go/src/github.com/docker/docker/bundles/17.05.0-dev/test-integration-cli/test.main -ldflags -w -tags 'autogen netgo static_build apparmor pkcs11 seccomp selinux daemon journald libdm_no_deferred_remove' -installsuffix netgo -a
07:06:41 # github.com/docker/docker/integration-cli
07:06:41 ./docker_cli_build_test.go:4786: undefined: withDockerfile
07:06:41 ./docker_cli_build_test.go:4817: undefined: withDockerfile
07:06:41 ./docker_cli_build_test.go:4817: undefined: withBuildFlags
07:06:41 ./docker_cli_build_test.go:5648: undefined: withBuildFlags
```

PR #32070 tries to fix this.

**Comment by catinthesky** [comment]
@allencloud , thanks a lot for your information :+1:

**Comment by vdemeester** [comment]
@catinthesky you need to rebase against master for it to work (that's my bad 👼 )

**Comment by catinthesky** [comment]
@vdemeester , thanks a lot for your notification,  I tried rebase in branch issue31373fix, and committed, not sure if OK, much appreciated if sharing some git commands about how to rebase against master from forked branch, thank

**Comment by cpuguy83** [comment]
I don't think we can just release the lock early like this.

**Comment by cpuguy83** [comment]
Going to close this because we can't unlock like this.

I have opened #33897 to address other issues that I think will also address the referenced issue.
Thanks!

**Pull request closed without merging**
