### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by moxiegirl**
Update Quickstart which is out-of-date.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
frickin edit on GitHub thing

**Comment by thaJeztah** [comment]
LOL, you *can* actually do this, if you add the sign-off in the description.

@moxiegirl I think this branch can be deleted?

**Comment by moxiegirl** [comment]
@thaJeztah I was full of disgust and I did add the sig to the description but it didn't satisfy Gordon did it?

**Comment by thaJeztah** [comment]
Yeah, it looks like it wasn't in the *commit message*, which Gordon looks at https://github.com/docker/docker/commit/bca90f4985d8dc2e06059a5e137b515205e115e0

GitHub s*cks for this though, would've made life so much easier for people providing small fixes/changes if it supported amending through the web interface :(

**Pull request closed without merging**
