### PR TITLE
docs: fix storage driver options list

### LINKED ISSUE #17140: Correct List tagging in docker daemon command
image

### PR DESCRIPTION
**Pull request by thaJeztah**
This fixes the indentation of the storage driver options list.

Also wraps/reformats some examples to prevent horizontal scrollbars on the rendered HTML

Fixes #17140

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @moxiegirl @SvenDowideit :)

**Comment by thaJeztah** [comment]
hold on, looks like there's tabs in there, fixing now

**Comment by thaJeztah** [comment]
Updated, should be ready to go :smile:

**Comment by moxiegirl** [comment]
LGTM thanks @thaJeztah

**Comment by moxiegirl** [comment]
cp please

**Pull request merged**
