### PR TITLE
Vendoring libnetwork to 1.12.0-bump branch to avoid a deadlock

### PR DESCRIPTION
**Pull request by mavenugo**
Introduced by a RC5 fix : https://github.com/docker/libnetwork/pull/1346 to solve docker/docker#24778

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM ping @cpuguy83 @vikstrous i know it's a race, but if you can try to test this PR that'd be greatly appreciated.

**Comment by jhowardmsft** [comment]
LGTM. Yes, I hit this yesterday on a Windows run.

**Comment by tiborvass** [comment]
Ignoring Janky failure on TestApiSwarmRestartCluster (fixed by #25077).

**Comment by cpuguy83** [comment]
Can't seem to trigger this locally, but this change LGTM.

For 1.12.1 we should make sure all the calls to the two new lock points added in https://github.com/docker/docker/pull/24990 are definitely ok.

**Comment by tiborvass** [comment]
Experimental is hitting unrelated issue #24803

**Comment by justincormack** [comment]
@tiborvass I don't know that issue is *necessarily* unrelated. That test starts five containers simultaneously, which is one of the cases that was supposed to trigger the bug we are trying to fix.

**Comment by tiborvass** [comment]
@justincormack hmm good point. cc @mavenugo @cpuguy83

**Comment by mavenugo** [comment]
@tiborvass @justincormack am not aware of how this fix is trying to address any particular test. this fix is only to avoid the deadlock which causes the daemon to freeze.

**Comment by justincormack** [comment]
@mavenugo ah ok, well this test never caused a freeze so probably unrelated.

**Comment by vieux** [comment]
LGTM

**Pull request merged**
