### PR TITLE
provide the complete mounts name under practice

### PR DESCRIPTION
**Pull request by lixiaobing1**
provide the complete mounts name under practice.

### CODE REVIEW

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
These are all binds, and as such would not have a "Driver" set, or a "Name" set.
These docs are incorrect.

**Comment by thaJeztah** [comment]
@cpuguy83 looks, like that was introduced in https://github.com/docker/docker/pull/19252

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Even though the content itself is correct, I think this PR just decreases readability.

PTAL @vdemeester

**Comment by thaJeztah** [comment]
I have to agree with @AkihiroSuda that this may not make the example easier to read. Also, for 1.13, we're switching to generated API docs using Swagger, so this PR would have to be updated for that.

I'll close this PR for now

**Pull request closed without merging**
