### PR TITLE
add install support to elementary OS

### PR DESCRIPTION
**Pull request by diegomarangoni**
elementary OS is based on Ubuntu, take a look at https://elementary.io

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like this is a duplicate of https://github.com/docker/docker/pull/12416 and https://github.com/docker/docker/pull/11857

**Comment by diegomarangoni** [comment]
oops, my bad...
thanks!

**Comment by thaJeztah** [comment]
No problem, I'll leave it open for now, because @tianon is currently deciding which out of the four to merge.

Thanks for your contribution, even if it is not picked, much appreciated!

**Comment by jfrazelle** [comment]
closed by #12416 thanks

**Pull request closed without merging**
