### PR TITLE
Make it clear that env vars must be simple

### LINKED ISSUE #20169: Environment variable type of array not working
I try to set an environment variable as array but it's seem not working.
I tried with -e, --env and --env-file arguments of run command.

I didn't find anything about this case, so I open this issue.

`docker version`: Docker version 1.10.0, build 590d5108

I set a variable like this: `ARRAY=("foo" "bar" "foobar")`

My Dockerfile:
```
FROM debian:jessie

COPY display-array.sh /display-array
ENTRYPOINT ["/display-array"]
```

Entrypoint's script:
```
#!/bin/bash

echo "Test with an environment variable as array passed to run command"
echo "Count elements in ARRAY: "${#ARRAY[*]}
echo "List of elements: "${ARRAY[@]}
if [ ! ${#ARRAY[*]} = 0 ]; then
	cnt_elmt=$((${#ARRAY[*]} - 1))
	for i in `seq 0 $cnt_elmt`
	do
		echo "Element $i = "${ARRAY[$i]}
	done
fi

printf "\nTest with the same environment variable as array assigned directly in bash script\n"
ARRAY=("foo" "bar" "foobar")
echo "Count elements in ARRAY: "${#ARRAY[*]}
echo "List of elements: "${ARRAY[@]}
if [ ! ${#ARRAY[*]} = 0 ]; then
	cnt_elmt=$((${#ARRAY[*]} - 1))
	for i in `seq 0 $cnt_elmt`
	do
		echo "Element $i = "${ARRAY[$i]}
	done
fi

exec "$@"
```

Build command: `docker build -t jessie .`

Run commands tried:
`docker run -it --rm -e "ARRAY=("foo" "bar" "foobar")"  jessie`

`docker run -it --rm --env "ARRAY=("foo" "bar" "foobar")"  jessie`

`docker run -it --rm --env-file ./array.env jessie`

With this content in array.env file:
`ARRAY=("foo" "bar" "foobar")`

Result:

```
Test with an environment variable as array passed to run command
Count elements in ARRAY: 1
List of elements: ("foo" "bar" "foobar")
Element 0 = ("foo" "bar" "foobar")

Test with the same environment variable as array assigned directly in bash script
Count elements in ARRAY: 3
List of elements: foo bar foobar
Element 0 = foo
Element 1 = bar
Element 2 = foobar
```

The variable value has been treated like a string not an array.
I don't understand this behavior.

Note: 
For the moment, I assign a value separated by a comma like this: `ARRAY=foo,bar,foo bar`
And i transform it with this code: `IFS=',' read -r -a ARRAY <<< "$ARRAY"`

Thanks for the help.

### PR DESCRIPTION
**Pull request by duglin**
Closes #20169

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by MHBauer** [comment]
LGTM. It is not worth reformatting the paragraph just to add some words.

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by thaJeztah** [comment]
LGTM, thx

**Pull request merged**
