### PR TITLE
API Cleanup: Removing unused restful endpoint /containers/ps

### LINKED ISSUE #12541: API Cleanup proposal: remove /containers/ps endpoint
Description of problem:
API Cleanup proposal: 

In the docker\api\server\server.go the **/containers/json** and the **/containers/ps** are pointing to the same function: getContainersJSON.
I suggest the removal of **/containers/ps** endpoint, because it not used anymore.

`docker version`:
since 1.0.0++

`docker info`:

Not relevant but:
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2

`uname -a`:
Linux docker 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Tested on AWS and VMWare based servers.

How reproducible:
Check in browser: http://<docker_host>:<docker_host_port>/containers/json , then http://<docker_host>:<docker_host_port>/containers/ps

Steps to Reproduce:
1. Start docker with "-d -H=0.0.0.0:2375"
2. query /containers/json
3. query /containers/ps

Actual Results:
Both query producing same results

Expected Results:
/containers/ps not is obsolete. Should return 404

Additional info:
N/A

### PR DESCRIPTION
**Pull request by lexandro**
Pull request as solution of https://github.com/docker/docker/issues/12541 issue

Closes: #12541

### CODE REVIEW

**Comment by duglin** [comment]
Please add:
```
Closes: #12541
```
to your top-most comment.

**Comment by duglin** [comment]
LGTM

**Comment by lexandro** [comment]
Closes: #12541

**Comment by cpuguy83** [comment]
I don't think we can just remove this. What if people are using it? The endpoint works.

**Comment by lexandro** [comment]
This endpoint is undocumented and the internal usage changed in the 1.0.0 release. I tried ti find any reference to it via google, but I failed.

**Comment by duglin** [comment]
If that's true, then perhaps @lexandro could morph this PR into one that adds a testcase for it?
I believe it was @tianon who once said "if there isn't a testcase for it then it doesn't exist" :-)  I like that.

**Comment by lexandro** [comment]
What is the verdict? Keep it or clean it? :)

**Comment by jfrazelle** [comment]
NO, old clients need to still work

**Comment by lexandro** [comment]
Sorry for writing again, but I found this in the API v1.12 documentation: "Removed Insert Endpoint The insert endpoint has been removed."  (https://docs.docker.com/reference/api/docker_remote_api/) 

This one is more outdated, so please consider again the removal, because this is endpoint was neverdocumented officially and the docker client is not using it since at least the first 1.0.0.0 release.

This is almost a two years old undocumented stuff.

Otherwise is there any official process/documentation for depreciation of an api endpoint?

**Comment by duglin** [comment]
@lexandro FYI - this endpoint has been removed - not sure in which release, but in 1.9 its gone.

**Comment by lexandro** [comment]
Good to know :) 
Thanks!

**Pull request closed without merging**
