### PR TITLE
vendor: bump etcd to v3.3.9

### PR DESCRIPTION
**Pull request by kolyshkin**
...and use ugorji/go 1.1.1

While at it, update etcd deps.

Fixes https://github.com/moby/moby/issues/37804

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
```
06:43:55 ---> Making bundle: binary-daemon (in bundles/binary-daemon)
06:43:55 Building: bundles/binary-daemon/dockerd-dev
06:44:31 # github.com/docker/docker/vendor/github.com/ugorji/go/codec
06:44:31 vendor/github.com/ugorji/go/codec/decode.go:1026:7: undefined: reflectArrayOfSupported
06:44:31 vendor/github.com/ugorji/go/codec/decode.go:1027:25: undefined: reflectArrayOf
06:44:31 vendor/github.com/ugorji/go/codec/decode.go:1478:10: undefined: makeMapReflect
06:44:31 vendor/github.com/ugorji/go/codec/helper.go:1300:40: undefined: allowSetUnexportedEmbeddedPtr
06:44:55 Build step 'Execute shell' marked build as failure
```

**Comment by kolyshkin** [comment]
forgot to do `git add` after `vndr` -- fixed

**Comment by kolyshkin** [comment]
rebased (mostly to re-run CI)

**Comment by kolyshkin** [comment]
TestAPISwarmLeaderElection failure on janky and experimental CI (context deadline exceeded). This is a well known flaky test (https://github.com/moby/moby/issues/32673).

**Comment by kolyshkin** [comment]
temporary included https://github.com/moby/moby/pull/37833 to investigate TestAPISwarmLeaderElection failure.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
oh, we should probably remove that other commit before merging 😅

**Comment by kolyshkin** [comment]
> oh, we should probably remove that other commit before merging ￼

:wastebasket: done

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Pull request merged**
