### PR TITLE
Bump version to v1.9.0

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

### CODE REVIEW

**Comment by icecrime** [comment]
Nice round number.

**Comment by tiborvass** [comment]
Please test!

Ubuntu/Debian/CentOS/Fedora: curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.9.0
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.9.0
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0.tgz

**Comment by feiskyer** [comment]
```
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: CFB7658612C0CD45
HostId: yCMMGWJuWs3PUyqwzGDiUgNlJVlEIw11nuOZm6YqMO1eXBr+c0ga8tv4iEwugQSCDr5FN3MNkC8=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: AccessDenied
Message: Access Denied
```

**Comment by tiborvass** [comment]
@abronan updated the comment above with the right URLs sorry about that

**Comment by pandrew** [comment]
``` docker run -it --rm -v ~:/test ubuntu``` seems to expand to home path properly, however ```docker run -it --rm -v .:/test ubuntu``` does not while in your home directory. ```docker run -it --rm -v ..:/test ubuntu``` seems to create a volume named ".." that i can't remove.

```
paul@ubuntu:~$ docker volume rm ..
..
paul@ubuntu:~$ docker volume ls
DRIVER              VOLUME NAME
local               ..
local               22267aaff295853e5f2bb6ac711d7c45e7c36054968b5e06079fd42367e79325
local               dae5e64310ec16150e37f7dee76e6b2f24d79c0235f68743da5b11dbdb357c35
```

**Comment by cpuguy83** [comment]
@pandrew `~` is expanded by the shell.

Curious why `..` is not being deleted. It looks like the client is not making an API call at all.
I think there is a PR to restrict names that begin with `./` or `..` this behavior... let me check.

**Comment by thaJeztah** [comment]
@pandrew @cpuguy83 yup, I created an issue for the restriction here; https://github.com/docker/docker/issues/16132, and there's a pull-request here https://github.com/docker/docker/pull/16140. It was discussed briefly yesterday, and we'll add it to the milestone, so it can be included in -rc2

**Comment by eolamey** [comment]
This release sounds great! 2 nitpicks on the changelog though.

Aren't those 2 lines redundant (in the Runtime section)?

```
+ Add `--message` flag to `docker import` allowing to specify an optional message (#15711)
...
+ Add `-m`/`--message` flags to `docker import` to set a commit message (#15711)
```

And the Logging section seems to be missing the awesome new `labels` and `env` generic options (merged in https://github.com/docker/docker/pull/16961).

**Comment by tiborvass** [comment]
@eolamey thanks for the feedback, will update it for rc2!

**Comment by ibuildthecloud** [comment]
Just a heads up, we are actively testing 1.9.  So far issues, we are slowly working through them and filing bugs.

**Comment by thaJeztah** [comment]
@ibuildthecloud thanks Darren!

**Comment by tiborvass** [comment]
We have just pushed v1.9.0-rc2 to https://test.docker.com. You can download it with the following:

Ubuntu/Debian/CentOS/Fedora: curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0-rc2
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.9.0-rc2
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.9.0-rc2
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0-rc2.tgz

Please test!

**Comment by tiborvass** [comment]
RC3 released:

Ubuntu/Debian: curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0-rc3
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.9.0-rc3
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.9.0-rc3
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0-rc3.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.9.0-rc3.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.9.0-rc3.exe

**Comment by tiborvass** [comment]
1.9.0-rc4 is up

Ubuntu/Debian: curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0-rc4
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.9.0-rc4
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.9.0-rc4
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.9.0-rc4.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.9.0-rc4.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.9.0-rc4.exe

**Comment by icecrime** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
just so we have a reference here of the things we will fix in 1.9.1 https://github.com/docker/docker/milestones/1.9.1

and lets FIRE ZE MISSLES, LGTM

**Comment by abronan** [comment]
LGTM :rocket:

**Comment by runcom** [comment]
:tada:

**Comment by gesellix** [comment]
:whale:

**Comment by cpuguy83** [comment]
:candy: Congrats all, great job!

**Comment by hosh** [comment]
Gratz!

**Comment by Geoffrey0247** [comment]
great!

**Pull request merged**
