### PR TITLE
integration-cli: test load/import with authz plugins

### PR DESCRIPTION
**Pull request by runcom**
integration-cli tests for https://github.com/docker/docker/pull/20602

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
Ping @vdemeester @estesp

**Comment by vdemeester** [comment]
@runcom seems good to me, but shouldn't we try that it did reimport correctly the image (by removing busybox in the first part of the test, and by using a new image name in the 2nd). I would also split the tests into 2 (just to make it smaller) : one for save/load, one for export/import.

But other than that, it looks good :+1:

**Comment by runcom** [comment]
There's no need for that because the bug that PR fixed was just that it failed to import at all so this test cover just this case :)

**Comment by estesp** [comment]
thx @runcom! LGTM

**Comment by cpuguy83** [comment]
Certainly not going to reject a test because it's not testing everything, but I agree with @vdemeester we should be testing the whole cycle, not just what was broken.

**Comment by runcom** [comment]
well, I agree with that but this is just adding a *regression* test for a bug already fixed in a PR - what you're proposing is broader to me and yes it can be done (in another PR)

**Comment by cpuguy83** [comment]
LGTM

**Comment by estesp** [comment]
This is `docker_cli_authz_unix_test.go` and as @runcom said, a specific regression being tested; the full capabilities of save/load/export/import are already well tested in `docker_cli_save_load_test.go` and `docker_cli_import_test.go` IMO

**Comment by estesp** [comment]
oh man..my *well, actually..* didn't even make pre-merge =)

**Comment by runcom** [comment]
:smile:

**Pull request merged**
