### PR TITLE
updates to release checklist

### PR DESCRIPTION
**Pull request by jessfraz**
these are my proposed changes, but @tiborvass and I are going to do this together the next few times so we will be making updates, this is a WIP :)

### CODE REVIEW

**Comment by tiborvass** [comment]
thanks @jfrazelle

**Comment by MHBauer** [comment]
I :heartbeat: checklists.

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
> but @tiborvass and I are going to do this together the next few times so we will be making updates, this is a WIP

check!

LGTM

**Pull request merged**
