### PR TITLE
Fix: docker info not list all the volume drivers on daemon fresh start.

### LINKED ISSUE #26272: docker info not list all the volume drivers when newly restart the docker daemon
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local vmdk
 Network: host bridge overlay null
Swarm: active
 NodeID: eemy7koosp652p89f8u6hki0j
 Is Manager: true
 ClusterID: c9dzw4c483ctfbw4chgk7bewt
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.1.9.111
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993 MiB
Name: ubuntu
ID: H5YC:TKIN:3NGH:B7CF:RC6N:PYN6:CF6O:5NAC:VH27:DKHQ:AQK2:T5AJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMware VM

```
uname -a
Linux ubuntu 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
1.  In stall any volume driver and make sure it runs well (mine is [vmdk](https://github.com/vmware/docker-volume-vsphere))
2. restart the docker daemon
3. docker info see if the driver is in "Plugins: Volume" list
4. run docker volume ls see if the driver is in "Plugins: Volume" list
5. do step 3 again

**Describe the results you received:**

 If the driver is in "Plugins: Volume" list:?
- step 3: No
- step 4: Yes
- step 5: Yes

**Describe the results you expected:**

All yes above

### PR DESCRIPTION
**Pull request by Revolution1**
**\- What I did**

make sure every time we get list of volume drivers we get the correct result

Fix: #26272

**\- How I did it**

change the GetDriverList() to use the GetAllDrivers(), which will add plugin to storage which are not in drivers.extensions

**\- How to verify it**

I compile it, run it, and the result is exactly as I expected

**\- Description for the changelog**

Fix: docker info not list all the volume drivers on fresh start.

**\- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by cpuguy83** [comment]
Not so sure about this as it could slow down `docker info` a ton.

**Comment by cpuguy83** [comment]
Also note we are working on a new plugin system (currently in experimental) which does not lazily load plugins.

**Comment by Revolution1** [comment]
That's a good news

**Comment by thaJeztah** [comment]
I'll go ahead and close this, since this is changing in the new plugin system

**Pull request closed without merging**
