### PR TITLE
Bump go-units

### PR DESCRIPTION
**Pull request by wernight**
Bump for https://github.com/docker/go-units/pull/23

### CODE REVIEW

**Comment by LK4D4** [comment]
@wernight you also need to run `vndr github.com/docker/go-units` for real update. You can get vndr from `github.com/LK4D4/vndr`.
Thanks!

**Comment by wernight** [comment]
Wow! That looks a bit complex. Wouldn't it get picked up automatically actually?

**Comment by LK4D4** [comment]
@wernight yeah, it should be simpler, but that's what we have for now.
For vndr to work your `somewhere` should be in your GOPATH. It is pain indeed. Gladly we don't need to use it often.

**Comment by thaJeztah** [comment]
You can also assuming you're in your local git checkout of docker;

```
make BIND_DIR=. shell
```

which starts a shell in a development container, with your source code bind-mounted in.
Inside that container, `vndr` is already installed, so you can `vndr github.com/docker/go-units` there

**Comment by yongtang** [comment]
@wernight You could also try with running go inside a container:
```
ubuntu@ubuntu:~/docker$ docker run -i -t -v $PWD:/go/src/github.com/docker/docker -w /go/src/github.com/docker/docker golang:1.7.0
root@5721fa1f08e3:/go/src/github.com/docker/docker# go get -u github.com/LK4D4/vndr
root@5721fa1f08e3:/go/src/github.com/docker/docker# vndr github.com/docker/swarmkit
2017/02/02 16:32:29 Collecting initial packages
...
...
2017/02/02 16:32:41 Success
2017/02/02 16:32:41 Running time: 11.217918406s
root@5721fa1f08e3:/go/src/github.com/docker/docker# 
```

It is a lot easier as it does not depends on your local golang setup.

**Comment by vdemeester** [comment]
Carrying in #30790

**Pull request closed without merging**
