### PR TITLE
Add --device flag to allow additional host devices in container

### PR DESCRIPTION
**Pull request by timthelion**
I know I said I was out for the weekend, but I got up **early** this morning, and with a bit of repasting(it's like rebasing, but for the unenlightened), I bring you:

We add a --device flag which can be used like:

```
$ docker run --device /dev/sda:/dev/xvda:rwm ubuntu /bin/bash
```

To allow the container to have read write permissions to access the host's /dev/sda via a node named /dev/xvda in the container.

Docker-DCO-1.1-Signed-off-by: Timothy timothyhobbs@seznam.cz (github: https://github.com/timthelion)

Big thanks to @dineshs-altiscale !

### CODE REVIEW

**Comment by drngsl** [comment]
Hi, @calfonso , I install docker in my host with docker info
root@ubuntu:/# docker info
Containers: 52
Images: 62
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 166
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 16
Total Memory: 47.16 GiB
Name: ubuntu
ID: LZTA:AOAG:2X7V:SPXR:FFUP:VEFO:GIAM:3NCV:ISSG:VZVE:B4SB:KAD6
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

in this verson, device modifying is not supported, so what should I do, if I want to add/remove a device to the running container?

**Comment by thaJeztah** [comment]
@drngsl this PR is for adding a device when *starting* a container, there's a proposal to allow this on running containers, but it's not been decided on yet; https://github.com/docker/docker/pull/8826

**Comment by drngsl** [comment]
@thaJeztah , so can you tell me how can i deploy docker with source code which contains device-modifying function?

**Comment by thaJeztah** [comment]
@drngsl you'd have to write that, because that PR was still in a "proposal" stage, no code was written yet, afaik

**Comment by drngsl** [comment]
@thaJeztah, so the code from https://github.com/imain/docker/tree/modify or https://github.com/calfonso/docker/tree/docker_modify,
I can't deploy docker with them?

**Comment by thaJeztah** [comment]
@drngsl that's not something I can answer for you; if you can build that, and you are comfortable running that code, then it's up to you to decide if you want to run it. But it won't be an official docker build, and it's not "supported".

**Comment by thaJeztah** [comment]
But I'd seriously discourage running it, I just looked at those branches, and the last modifications are over a year ago, so you'd be running a really old version of docker, that doesn't have security updates, and chances are that it will no longer work with Docker Hub when registry v1 support is removed.

**Comment by drngsl** [comment]
@thaJeztah , thanks !

**Pull request closed without merging**
