### PR TITLE
update to github.com/sirupsen/logrus v1.0.0

### PR DESCRIPTION
**Pull request by mcandre**
Fix some broken dependencies by using latest github.com/sirupsen/logrus.

### CODE REVIEW

**Comment by mcandre** [comment]
Looks like logrus casing needs to be fixed in moby's dependencies' source as well.

Opened a pull request to fix containerd: https://github.com/containerd/containerd/pull/1136

**Comment by justincormack** [comment]
Yes @stevvooe was looking at doing a coordinated case change for logrus.

**Comment by mcandre** [comment]
Looks like some of these CI builds are failing due to yaml.h (libyaml?) not being installed

**Comment by darrenstahlmsft** [comment]
Microsoft/hcsshim v0.6.1 contains the changed logrus casing.

**Comment by dmcgowan** [comment]
@mcandre containerd has been merged. You might need to update the 0.2.x branch as well though.

**Comment by AkihiroSuda** [comment]
Can we close this PR and adopt https://github.com/moby/moby/issues/34272 ?

**Comment by thaJeztah** [comment]
Closing this in favour of https://github.com/moby/moby/pull/34272, which is working on all the dependencies. Thanks so much for starting the work on this @mcandre !

**Pull request closed without merging**
