### PR TITLE
Remove checkpoint methods from builder backend

### PR DESCRIPTION
**Pull request by tonistiigi**
cc @boucher 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by boucher** [comment]
@tonistiigi Thanks for the ping. Can you explain this for me?

**Comment by tonistiigi** [comment]
@boucher These methods are not used by the builder so they shouldn't be part of the required interface needed for the builder to run.

**Comment by boucher** [comment]
Of course, thanks.

**Comment by justincormack** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
