### PR TITLE
Add CMD and EXPOSE instruction example

### PR DESCRIPTION
**Pull request by physicalit**
After I had some issues using `commit`, I decided to add it to the docs. I believe this should also be merged with the branch `docs`.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks @physicalit. Don't worry about merging to the docs branch for now, we'll be updating docs soon.

ping @moxiegirl @SvenDowideit

**Comment by moxiegirl** [comment]
LGTM Thank you @physicalit

**Comment by thaJeztah** [comment]
Merging! \o/ :dancer:

**Pull request merged**
