### PR TITLE
Replacing -d/--daemon with daemon command. Implementation of 'docker daemon' command

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Following up on PR #6055  which was initiated by Dan Walsh (rhatdan).

### CODE REVIEW

**Comment by aidanhs** [comment]
It's a bit frustrating to be able to run `docker --dns 1.2.3.4 run --dns 1.2.3.5 -it ubuntu:14.04 bash` and have no indication that one of these will just silently not work.

**Comment by thaJeztah** [comment]
I'm still in favor of this; it makes it *much* clearer which flags are meant for the daemon, and the output of help/usage on the command line will be a lot less messy.

**Comment by SvenDowideit** [comment]
Docs LGTM, though I presume they might be a little out of date

**Comment by aidanhs** [comment]
Should `-d` really be changed to `daemon` in the changelog for old versions?

**Pull request closed without merging**
