### PR TITLE
[Carry 17869] Add docs and man page entry for --volume-driver

### PR DESCRIPTION
**Pull request by thaJeztah**
Carry of #17869, addressing @moxiegirl's review comments

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @moxiegirl @SvenDowideit for review/merge

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
Author LGTM (and it already got reviewed in the original PR)

**Comment by bfirsh** [comment]
Thanks, @thaJeztah!

**Pull request merged**
