### PR TITLE
Proposal: Make Room for Registry

### PR DESCRIPTION
**Pull request by moxiegirl**
In attempting to add the registry documentation to docs.docker.com I found that we really are hitting the outer limit of what is possible with the Mkdocs / site design.  Especially the Reference page became pretty much unusable.

@fredlf has been working on a tree overhaul but the coming release doesn't allow time to implement and test anything.  I'm proposing an interim solution which you can build from this PR or view online here http://52.10.125.146:8000/.

There are changes to:
- _About_ where I moved some things like FAQ and Glossary out of refernece
- Created an _Orchestrate_ tree to hold all the Swarm/Machine/Compose material which was lost in the wash of the larger Docker material. 
- Added a registry "tree" to the  _Reference_ section which is essentially an expanded tree

This is an interim solution and a proposal but we do need to decide before the release which is upon us.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @fredlf @SvenDowideit @jamtur01 @spf13 

For their input regarding positioning of registry 2.0 docs; gents look in "Reference"

ping @bfirsh @stevvooe @dmp42

**Comment by bfirsh** [comment]
Looks good. I wonder if we can bundle all the old registry stuff under a "Docker Registry 1.0" or something like that to make it clear that it's old, like the new registry stuff is under "Docker Registry 2.0".

**Comment by moxiegirl** [comment]
@bfirsh I can do that.

**Comment by fredlf** [comment]
+1 to @bfirsh 's suggestion. The other changes I'm okay with. However, one big potential problem is we need to add "Docker Hub Enterprise" as a top level menu item next week (as we did here, https://github.com/docker/docker/pull/10435, until they changed their mind and we pulled it out again). 

I'm not sure there's room to add that and the new Orchestrate menu. That's why that stuff got distributed in that crappy way before. We could shorten "Installation" to "Install" and "Contributor Guide" to "Contribute", which would win some real-estate back. Not sure it's enough, though.

**Comment by moxiegirl** [comment]
@fredlf Is it possible just to go with *Docker Hub Enterprise* where *Docker Hub* is? Doesn't one naturally lead into the other.

I don't believe I have the bandwidth to play around with the menu tonight.  Since you are not releasing until next week and I am trying to hit a deadline tomorrow, can we look at solving the "Docker Hub Enterprise" issue after the release tomorrow?  If that's cool, can I get an LGTM? :-D

**Comment by jamtur01** [comment]
LGTM.

**Comment by fredlf** [comment]
No, while they do interact, Hub and DHE are discreet products with different docs, customers, etc. My deadline is actually Friday morning, when we need to have an instance of the docs up for user testing. Sven is working tonight on getting that instance ready to go this evening, while he has a window, which will close tomorrow as more docs need to get written/finalized as the software builds. So, this needs to get solved now, basically.

**Comment by SvenDowideit** [comment]
i :heart: the `&nbsp;&nbsp;&nbsp;&nbsp;&blacksquare;&nbsp;` - idea - i presume its less effective using just the spaces indenting?

**Comment by moxiegirl** [comment]
@fredlf There were several other solutions that I tried including subsuming the About under User guide or combining **Articles** and **Examples**. I would suggest that y'all try that.  

Moving the MSC out back where it was is not a solution. It was that material under **Reference** which was causing the bloat.

**Comment by fredlf** [comment]
I cannot, and will not, re-start work that was resolved, and has been in place, since January. I have neither time nor personnel to do that. I suggest, again, that we solve the bloat problem after our respective releases.

**Comment by moxiegirl** [comment]
Ok. It sounds like we can't come to an agreement. Since y'all are doing user testing on what you come up with for your Friday deadline, who knows it might solve everything.

**Pull request closed without merging**
