### PR TITLE
close http response body when attaching

### PR DESCRIPTION
**Pull request by allencloud**
close http response body when attaching

### CODE REVIEW

**Comment by cpuguy83** [comment]
I'm not sure this is correct.
We're already passing `resp` to `holdHijackedConnection`, at which point the caller should not be calling close on it anymore.

Beyond that, this would need to be done from inside the promise otherwise you risk closing before the goroutine is ready to yield control of it.

**Comment by allencloud** [comment]
@cpuguy83 
After I read what you said, I am not sure, either.
But what still confuse me is that if no one close this, there must be possibility to have memory leak, and can not reuse that fd resource.

While, in both places calling `ContainerAttach`:
https://github.com/docker/docker/blob/master/api/client/attach.go#L71-96
https://github.com/docker/docker/blob/master/api/client/start.go#L97-112

,Close added to resource leak.

**Comment by allencloud** [comment]
any update?

**Comment by LK4D4** [comment]
I don't think that it creates memory leak, but I don't see harm in closing as well. Goroutine must be long dead by time when this function ends.
LGTM

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL if you still have objections

**Comment by icecrime** [comment]
I don't see any risk there (famous last words). LGTM, thanks!

**Pull request merged**
