### PR TITLE
Cherry picks 1.11.0 rc4

### PR DESCRIPTION
**Pull request by tiborvass**
Cherrypicking:
#18747
#21712
#21723
#21730
#21751
#21768
#21780
#21787
#21790
#21799
#21802
#21810

Noteworthy:
- https://github.com/docker/docker/pull/21802/commits/ce87de21a7594f5d49987a7333f1f0e77984f117 was not cherrypicked since it modified tests that are not in the 1.11 branch.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by mlaventure** [comment]
LGTM, NAM

**Comment by vieux** [comment]
SGTM

**Pull request merged**
