### PR TITLE
Update libcontainer to last version

### PR DESCRIPTION
**Pull request by kvasdopil**

### CODE REVIEW

**Comment by LK4D4** [comment]
We already have PR about updating #13482 
Also, you did something wrong, you should use hack/vendor.sh script for updating

**Comment by kvasdopil** [comment]
@LK4D4 dunno what I did wrong, I've updated vendor.sh to last version, added new dependencies and used it to update the vendor directory, is it correct?

**Comment by LK4D4** [comment]
@kvasdopil `codegangsta/cli` isn't dependency of libcontainer, but of libcontainer/nsinit which isn't necessary for docker. Also you downgraded `gocapability`. Other things were right, but this is duplicate anyway :)

**Comment by kvasdopil** [comment]
@lk4d4 yeah, but my patch https://github.com/docker/libcontainer/pull/606 isnt included :( this means I'll have to create another pr anyway

**Pull request closed without merging**
