### PR TITLE
Update copyright dates

### PR DESCRIPTION
**Pull request by Phineas**
Signed-off-by: phineas <phin@phineas.io>

Updating copyright dates to 2017
meow

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thank you!

**Comment by Phineas** [comment]
@thaJeztah Ignored check error? I think it's because another build is also in progress and using a resource which can only be used at the same time, according to the error.

**Comment by thaJeztah** [comment]
Yes, looks like it's safe to ignore that error :smile:

ping @vdemeester for review/merge

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by ItsPugle** [comment]
LGTM

Just testing don't mind me lOl

**Pull request merged**
