### PR TITLE
Re-run vndr

### PR DESCRIPTION
**Pull request by cpuguy83**
Now that the CLI is gone there are lots of packages that need to be
pruned from vendor.

This cleans up some other PR's trying to re-vendor some specific package.

### CODE REVIEW

**Review by justincormack — APPROVED** [review]

**Comment by justincormack** [comment]
disappointingly only 36k lines of code...

**Review by thaJeztah — APPROVED** [review]
LGTM (if green)

**Review by vdemeester — APPROVED** [review]
LGTM 🎉

**Comment by cpuguy83** [comment]
merging, janky failed with that netns issue.

**Pull request merged**
