### PR TITLE
syntax highlighting: support FROM...AS for multi stage build

### PR DESCRIPTION
**Pull request by chrisdias**
**- What I did**
Added support for `AS` for multi stage builds, as in `FROM node AS base`

**- How I did it**
Added new a capture to the `dockerfile.tmLanguage` file

**- How to verify it**
I tested that this works in VS Code. I added the `tmLanguage` file to the `vscode-docker` extension and it looks good.

**- Description for the changelog**
Add a new capture group to support `FROM...AS` in the Dockerfile syntax

### CODE REVIEW

**Comment by tonistiigi** [comment]
Can we have it so that it matches `AS` only as part of `FROM` command, not anywhere in the file?

**Comment by cpuguy83** [comment]
We also need you to sign the commit or we can't review.

`git commit --amend -s --no-edit && git push -f origin multistagebuild` ought to do the trick.

**Comment by chrisdias** [comment]
Ok, I think I've got it right now, along with the signing. Sorry for the confusion.

**Comment by alexellis** [comment]
(Firing off the Windows build again.)

**Comment by tonistiigi** [comment]
LGTM but please squash the commits

**Comment by chrisdias** [comment]
squashed. i hope the signing of the commit is still ok.

**Comment by tonistiigi** [comment]
cc @asbjornenge

**Review by tonistiigi — APPROVED** [review]

**Comment by asbjornenge** [comment]
LGTM 🎉  People have been asking for this over at https://github.com/asbjornenge/Docker.tmbundle too, I just haven't had the time. I'll be sure to bring this in and keep in sync 👍

**Review by vdemeester — APPROVED** [review]
LGTM 👼

**Pull request merged**
