### PR TITLE
putting in support for rmi id for legacy docker.io/name images in loc…

### PR DESCRIPTION
**Pull request by mikebrow**
Added support for docker rmi id of docker.io/name repository images stored locally - fixes issue #16936
Rebased to avoid merge conflicts for issue #17133

Signed-off-by: Mike Brown brownwm@us.ibm.com

### CODE REVIEW

**Comment by mikebrow** [comment]
@dmcgowan I've reduced the PR to just fixing rmi id..  Cheers.

**Comment by dmcgowan** [comment]
This change is working around the normalizes, however I really don't think the normalization on Delete is necessary in the first place.

See https://github.com/docker/docker/pull/17503/files#diff-9459cc42eeb37e6b37bcb473ce0b3d21R256

Removing that line would have the same effect but be generally useful for removing tags. Normalization really should not happen at this point anyway.

**Comment by mikebrow** [comment]
The same effect for this scenario, yes.  I was trying to fix the issue without introducing possible regressions.  I noted some registry testcases when I was doing the investigation.  If you want to delete that line... do you also want to change the testcase to reflect?

**Comment by dmcgowan** [comment]
My opinion is that deleting of the tag should work no matter what the format of the tag is. If the tag format is not accepted by the API, that should be handled at the API level. If the test cases are attempting to reflect `docker rmi` on an invalid tag, then those tests should continue to pass, this normalization just needs to be moved. Which tests are you having trouble with, I can offer advice the best way forward.

**Comment by mikebrow** [comment]
Sounds good to me, and nothing needs to be moved.  The tests I was having trouble with the other day were the ones that test the normalization code itself not specifically for an rmi.  But that was only an issue if we wanted to clean up the normalization code around docker.io/* issues.  Since we're not and not even going to call the normalization api for this code path... that's no longer an issue.  I'll delete the line of code per your suggestion and give it a go.

**Comment by mikebrow** [comment]
@dmcgowan, deleting the normalization tests out fine.

**Comment by LK4D4** [comment]
LGTM
userns fail is some time race

**Comment by dmcgowan** [comment]
LGTM

**Comment by LK4D4** [comment]
whatever

**Pull request merged**
