### PR TITLE
Fix swarm leave hanging

### PR DESCRIPTION
**Pull request by kylewuolle**
**- What I did**
This fixes a problem where if a node is removed on one leader and a ```docker swarm leave --force``` command is issued on the node the client hangs. The reason for this is the agent has been stopped thanks to the previous node removal command from the swarm leader and then in the DaemonLeavesCluster method in daemon.go it waits for the agent to stop. Since the agent is already stopped this hangs forever. 

This PR fixes the following issue: https://github.com/docker/for-linux/issues/499

**- How I did it**
To fix this I added a call to send the EventNodeLeave event which handles any cleanup when a node leaves. This ensures the agent stopped message is received in DaemonLeavesCluster.

**- How to verify it**
Execute ```docker node rm -f``` on a node in a cluster and then execute ```docker swarm leave -f``` on the node which was removed.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by olljanat** [comment]
Derek add label: rebuild/experimental

**Comment by olljanat** [comment]
@yongtang ping this one looks passing builds

**Comment by thaJeztah** [comment]
@kylewuolle could you squash your commits so that there's only a single commit in this PR? (let me know if you need a hand doing so)

**Comment by thaJeztah** [comment]
ping @dperny PTAL

**Comment by dperny** [comment]
amazing, would have taken me hours to figure this bug out.

LGTM, thanks.

**Comment by thaJeztah** [comment]
carrying in https://github.com/moby/moby/pull/38906, where I rebased and squashed your commits

**Pull request closed without merging**
