### PR TITLE
Fix race between two ContainerRm

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by duglin** [comment]
Doesn't this fix highlight a bigger issue?  If I'm following, you've changed a call from daemon.rm() to daemon.ContainerRm() so that all of the concurrency checks can be done in daemon.ContainerRm().  However, there's still nothing stopping someone, later on, from making the same mistake and calling daemon.rm() when it seems like we're saying all deletes should go thru daemon.ContainerRm().  Do I have that right?  If so, its like we're waiting for someone to mess up.

I would much prefer if we moved all concurrency checks down as far as possible (meaning into daemon.rm() ) so that regardless of which method people call we'd catch it because daemon.ContainerRm() is really nothing more than a wrapper for daemon.rm(), or remove one of the two funcs and merge all of the logic into one so that there's no chance of someone calling the wrong one.

At one point I thought we were headed towards the daemon funcs being wrappers (converting things like name/string into IDs) and then they would call the real funcs to actually do the work.  Is that no longer the case? Perhaps I was mistaken.

**Comment by LK4D4** [comment]
@duglin Dunno, it's problem with programming overall. Someone can call wrong function. You can find million functions in docker which just locking wrapper and people can cause deadlock or race by choosing wrong. `daemon.rm` is just logical split of function now to avoid over-complicating `ContainerRm`. I don't think that it's necessary to remove every function which can be used wrong.

**Comment by duglin** [comment]
I'm not suggesting a major overhaul, but having ContainerRm() and rm() not only on the same struct, but even within the same file right next to each other when their descriptions and names imply they both do the same thing (ignoring the obvious typo in rm()'s description ) is begging for someone to call the wrong one.  If merging the two func doesn't feel right, can we at least rename rm() to something else that implies its more like a util func for ContainerRm()?  Perhaps "cleanupContainer" or something like that?

**Comment by LK4D4** [comment]
@duglin Yup, no problem, let's do it in next PR.

**Comment by cpuguy83** [comment]
Got a panic on `TestContainerDoubleDelete`

**Comment by LK4D4** [comment]
@cpuguy83 Thanks! Fixed!

**Comment by estesp** [comment]
@LK4D4 sorry, needs rebase

**Comment by estesp** [comment]
actually, after experiencing this today on my own PR, I'm pretty sure you **don't** need a rebase, but GH seems to be requiring it now even if other changes are merged which have no conflict?

**Comment by duglin** [comment]
I've been wondering about this too - I **think* it just means that master changed, not that there's a conflict. Notice it doesn't say "conflict" just "out-of-date".  Kind of misleading if so.

**Comment by estesp** [comment]
@duglin, correct, but the old behavior was that is always was checking "merge-ability" and if it could still be auto-merged with no conflict resolution you could still click "Merge pull request".  Now you cannot until you fast-forward the underlying branch to be exactly master-current apparently?

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
