### PR TITLE
Bug/9350

### LINKED ISSUE #9350: Feature request: docker ps -f "with_volumes=false"
I only care about containers with volumes most of the time.

### PR DESCRIPTION
**Pull request by aislingnorris**
Fixes #9350

### CODE REVIEW

**Comment by thaJeztah** [comment]
@aislingnorris can you make sure to sign-off your commits, otherwise we cannot review or merge your PR. Also, I'm not sure you're referencing the correct issue, because this change does not look related to that issue?

**Comment by aislingnorris** [comment]
Sorry about the missing sign off.
It seems my team have labelled this wrongly as well, I will have to edit it further, please ignore the pull request.

**Comment by thaJeztah** [comment]
Is it ok to close this PR while you're working on it?

**Comment by aislingnorris** [comment]
Yup that's fine!

**Pull request closed without merging**
