### PR TITLE
Capitalizes the first letter in notes of dockerfile

### PR DESCRIPTION
**Pull request by yu8833**
Signed-off-by: YuPengZTE yu.peng36@zte.com.cn

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can you also include the other Dockerfiles (e.g., https://github.com/docker/docker/blob/master/Dockerfile.aarch64#L83) in this PR, looks like they need the same changes?

**Comment by YuPengZTE** [comment]
Thanks @thaJeztah,  the other Dockerfiles have changed, PTAL.

**Comment by thaJeztah** [comment]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Pull request merged**
