### PR TITLE
1.13.x: Revendor swarmkit to 3076318ec0327e22c837c2bfdfacea08124dc755

### PR DESCRIPTION
**Pull request by aluzzardi**
This includes:

- https://github.com/docker/swarmkit/pull/1693 (/cc @mavenugo)
- https://github.com/docker/swarmkit/pull/1747 (/cc @diogomonica)

/cc @aaronlehmann @vieux @thaJeztah

### CODE REVIEW

**Comment by mavenugo** [comment]
Thanks @aluzzardi LGTM

**Comment by aaronlehmann** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @aluzzardi, do we need to have this cherry-picked back to master, or will you open a separate PR?

**Comment by thaJeztah** [comment]
@mavenugo based on the description of https://github.com/docker/swarmkit/pull/1693, and it being linked to https://github.com/docker/docker/issues/25016, I think this has user-facing changes? If so, this may need changes in the documentation, and changelog.

Also, does this fix https://github.com/docker/docker/issues/25016 ?

**Comment by aluzzardi** [comment]
Thanks Sebastiaan - I think we'll open a PR to sync SwarmKit master into
docker master (everything - not just the cherry picks).

We basically have a 1.13 branch in SwarmKit in which we cherry pick stuff
from SwarmKit master and revendor the 1.13 docker branch from it.

Then docker master in which we just revendor SwarmKit master.

Makes sense?

**Comment by mavenugo** [comment]
@thaJeztah This doesn't fix https://github.com/docker/docker/issues/25016. It merely an add-on change to the recently introduced `--port` functionality with `PublihMode=host`. The docs needs an update for the new `--port` changes and we can add this behaviour along with it.

**Pull request merged**
