### PR TITLE
Add docker-update description ommitted in docker.1.md

### PR DESCRIPTION
**Pull request by lixiaobing1**
In docker.1.md, docker-update description ommitted, add it.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
this change LGTM but we may want to do a complete overhaul of this file, because so many other commands were added. Some options;

- list all commands, but group them logically (like we do in https://github.com/docker/docker/blob/master/docs/reference/commandline/index.md)
- mention `docker help` / `docker --help` to get an overview of available commands
- only list the "top" level commands (`docker container`, `docker image`, etc.)

**Comment by lixiaobing10051267** [comment]
modify with the option:
    mention docker help / docker --help to get an overview of available commands

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
