### PR TITLE
Fix racy tests in pkg/authorization

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**\- What I did**
Fix racy tests in pkg/authorization #23012

**\- How I did it**
`http.(*Server).Serve()` is a blocking function and hence it can lead to a race condition.
So I used `httptest.(*Server).Start()` instead.

**\- How to verify it**

```
$ TESTDIRS=pkg/authorization BUILDFLAGS=-race TESTFLAGS="-test.count 1000" make test-unit
```

Signed-off-by: Akihiro Suda suda.akihiro@lab.ntt.co.jp

### CODE REVIEW

**Comment by icecrime** [comment]
```

19:54:55 ---> Making bundle: validate-vet (in bundles/1.12.0-dev/validate-vet)
19:54:55 pkg/authorization/authz_unix_test.go:238: assignment copies lock value to t.server: net/http/httptest.Server contains sync.Mutex
```

**Comment by AkihiroSuda** [comment]
@icecrime Thank you for pointing out. Updated PR.

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
