### PR TITLE
ZFS driver: raise better errors during init

### PR DESCRIPTION
**Pull request by flavio**
The ZFS driver should raise proper errors when the ZFS utility is missing or when there's no zfs device active on the system. Raising the proper errors make possible to silently ignore the ZFS storage driver when no default storage driver is specified.

Previous to this commit it was no longer possible to start the docker daemon in that way:

```
  docker -d --storage-opt dm.loopdatasize=2GB
```

The above command resulted in an exit error because the ZFS driver tried to use the storage options.

I acknowledge it's better to be explicit about the storage backend to use, however the ZFS driver should follow the same conventions adopted by the other drivers in terms of error handling.

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @Mic92 @baloose, thanks :)

**Comment by jfrazelle** [comment]
hmmm did his nick change? https://github.com/docker/docker/blob/master/daemon/graphdriver/zfs/MAINTAINERS

**Comment by Mic92** [comment]
The pull request looks reasonable to me.

@jfrazelle I am not sure, if he still wants to maintain this. He wrote the initial libzfs-based implementation, but a lot things has changed since then.

**Comment by jfrazelle** [comment]
ah I see thanks for the review!

LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
