### PR TITLE
Vendoring miekg/dns @ 75e6e86cc601825c5dbcd4e0c209eab180997cd7

### PR DESCRIPTION
**Pull request by sanimej**
- Fixes the issue of Shutdown() not working, resulting in hung
  goroutines
- Fixes [libnetwork #878](https://github.com/docker/libnetwork/issues/878)

Signed-off-by: Santhosh Manohar santhosh@docker.com

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

Ping @tiborvass @thaJeztah

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks!

**Comment by mavenugo** [comment]
@icecrime @thaJeztah  sorry... wrong label at the wrong phase :). thanks for fixing it.

**Comment by thaJeztah** [comment]
Flaky test?
```
02:18:17 FAIL: docker_cli_run_test.go:2258: DockerSuite.TestRunSlowStdoutConsumer
02:18:17 
02:18:17 docker_cli_run_test.go:2279:
02:18:17     c.Fatalf("Expected %d, got %d", expected, n)
02:18:17 ... Error: Expected 4096000, got 3712692
```

**Pull request merged**
