### PR TITLE
Added tianon's info and changed a typo.

### PR DESCRIPTION
**Pull request by jessfraz**
realphabetized, added @tianon, fixed typo :D

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM
ping @tianon , maybe you want use your OTHER e-mail

**Comment by tianon** [comment]
Do you want to fix the `Github` vs `GitHub` while you're there? :innocent:

**Comment by jfrazelle** [comment]
sure thing

**Comment by jfrazelle** [comment]
updated

**Comment by tianon** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @crosbymichael

**Comment by crosbymichael** [comment]
Why does it have to be GitHub and not Github?

**Comment by jfrazelle** [comment]
consistency?

**Comment by crosbymichael** [comment]
ok, i didn't know

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
