### PR TITLE
Add a note that remote and Boot2Docker users should not type sudo

### LINKED ISSUE #9808: use of sudo on docker commands in boot2docker
I've been working through the docker guide on OSX, and I hit a snag with using sudo.  I'm using boot2docker, and using sudo to run docker commands causes a TLS error as documented [here](http://stackoverflow.com/questions/27528337/am-i-trying-to-connect-to-a-tls-enabled-daemon-without-tls)

Apparently sudo is required in linux, but it throws this error in boot2docker:

    FATA[0000] Post http:///var/run/docker.sock/v1.16/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

It would have saved me some head scratching and a couple searches to add a note about that difference in the guides.

### PR DESCRIPTION
**Pull request by SvenDowideit**
Docker-DCO-1.1-Signed-off-by: Sven Dowideit SvenDowideit@docker.com (github: SvenDowideit)

Closes #9808

and I've implemented a quick transclusion so `{{ include "filename" }}` will be replaced by that content.

### CODE REVIEW

**Comment by crosbymichael** [comment]
@SvenDowideit ping pong

**Comment by SvenDowideit** [comment]
updated - @fredlf  @jamtur01

**Comment by jamtur01** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks Sven!

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
