### PR TITLE
Update go-winio package to latest version

### PR DESCRIPTION
**Pull request by awmirantis**
Signed-off-by: Adam Williams <awilliams@mirantis.com>

Update Microsoft/go-winio to latest version.  A change in this version is needed for a future fix to using docker data root on a VHDX.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Heads up; this will conflict with https://github.com/moby/moby/pull/42270 (once merged)

**Comment by thaJeztah** [comment]
Looks like there's a breaking change in this version of go-winio

```
..\..\vendor\github.com\containerd\containerd\archive\tar_windows.go:234:3: cannot use syscall.NsecToFiletime(hdr.AccessTime.UnixNano()) (type syscall.Filetime) as type
"github.com/docker/docker/vendor/golang.org/x/sys/windows".Filetime in field value
..\..\vendor\github.com\containerd\containerd\archive\tar_windows.go:235:3: cannot use syscall.NsecToFiletime(hdr.ModTime.UnixNano()) (type syscall.Filetime) as type
"github.com/docker/docker/vendor/golang.org/x/sys/windows".Filetime in field value
..\..\vendor\github.com\containerd\containerd\archive\tar_windows.go:236:3: cannot use syscall.NsecToFiletime(hdr.ChangeTime.UnixNano()) (type syscall.Filetime) as type
"github.com/docker/docker/vendor/golang.org/x/sys/windows".Filetime in field value
..\..\vendor\github.com\containerd\containerd\archive\tar_windows.go:239:3: cannot use syscall.NsecToFiletime(hdr.ModTime.UnixNano()) (type syscall.Filetime) as type
"github.com/docker/docker/vendor/golang.org/x/sys/windows".Filetime in field value
..\..\vendor\github.com\containerd\containerd\archive\tar_windows.go:257:25: cannot use syscall.NsecToFiletime(createTime.UnixNano()) (type syscall.Filetime) as type
"github.com/docker/docker/vendor/golang.org/x/sys/windows".Filetime in assignment
```

Looking at the diff since v0.4.16 (which is green in https://github.com/moby/moby/pull/42270); https://github.com/microsoft/go-winio/compare/v0.4.16...v0.4.18

I think this is the one that causes the failure; https://github.com/microsoft/go-winio/pull/185
There actually was a discussion on that in https://github.com/microsoft/go-winio/pull/197#issuecomment-795676667, but looks like this one already went into v0.4.x (instead of v0.5.x)

/cc @kevpar @TBBle

Looks like that change requires an updated version of hcsshim (with https://github.com/microsoft/hcsshim/pull/947) and containerd as well

**Comment by thaJeztah** [comment]
> Heads up; this will conflict with #42270 (once merged)

#42270 was merged, so this needs a rebase now 🤗

**Comment by TBBle** [comment]
Hmm, this one's going to be a little tricky to unwind: The removal of the forked go-winio/backuptar (in containerd) where this compile failure is happening (https://github.com/containerd/containerd/pull/4395) is only in containerd 1.5.0.

The API change in question is in go-winio 0.4.17, (https://github.com/microsoft/go-winio/commit/bfd546865c984c87c6f60e8f41aec2c0c3aac9a2) which is also where the fix I assume we're trying to get (https://github.com/microsoft/go-winio/commit/83fd17628fd571626fa6f4cf74b8f5594c8077d4) shipped.

hcsshim itself hit this problem in its integration test suite (https://github.com/microsoft/hcsshim/pull/946) and ended up pulling containerd 1.5 beta in order to unblock go-winio upgrades: https://github.com/microsoft/hcsshim/pull/946
> [A structure type used by that deduplicated has changed in go-winio recently](https://github.com/microsoft/go-winio/commit/bfd546865c984c87c6f60e8f41aec2c0c3aac9a2#diff-b5e094cc0d645b5aa8557238b54f9e16ed61d07f5136596a41684344bfee23bbL22-R15), and so pulling in both older containerd and newer go-winio leads to compile failures.

where "that deduplicated" (sic) means https://github.com/containerd/containerd/pull/4395.

hcsshim itself isn't using these APIs, but newer containerd will require newer hcsshim due to https://github.com/containerd/containerd/pull/4399/commits/a64a76846c41d4c8a185b228df51168fa0cd65e4.

I'm actually somewhat surprised this has occurred, because I thought moby/moby didn't use this code, providing its own GraphDriver instead, but I guess Go can't avoid _compiling_ it, even if it's never run.

Anyway, some options:
* Fork go-winio for moby/moby with reverted https://github.com/microsoft/go-winio/pull/185. The PR that prompted that PR hasn't landed yet, so it (or just the two commits regarding FileInfo) should be safe to revert.
* Fork containerd 1.4 for moby/moby with https://github.com/containerd/containerd/pull/4395 backported.
* Backport https://github.com/containerd/containerd/pull/4395 to containerd 1.4 and release a new patch version.

**Comment by katiewasnothere** [comment]
@TBBle I'll be working on option 3 (Revert the two FileInfo commits in go-winio, release a new 0.4.x version, and then unrevert them to start the 0.5 series) today.

**Comment by thaJeztah** [comment]
for easier finding: pull request for the above is https://github.com/microsoft/go-winio/pull/204

**Review by tianon — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@awmirantis could you squash the commits?

**Comment by thaJeztah** [comment]
continued in https://github.com/moby/moby/pull/42327

**Pull request closed without merging**
