### PR TITLE
vendor.conf: replace vanity URL for code.cloudfoundry.org/clock (broken)

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/moby/moby/pull/42796#issuecomment-907352925

Looks like the vanity URL is currently / no longer functional:

    [2021-08-27T13:56:30.466Z] 2021/08/27 13:56:30 unrecognized import path "code.cloudfoundry.org/clock"
    (https fetch: Get "https://code.cloudfoundry.org/clock?go-get=1": x509: certificate signed by unknown authority)

Checking with cURL, it looks like it's now hosting a HTML page to redirect to godoc.org:

    curl -v 'https://code.cloudfoundry.org/clock?go-get=1'
    *   Trying 18.158.32.60:443...
    * TCP_NODELAY set
    * Connected to code.cloudfoundry.org (18.158.32.60) port 443 (#0)
    * ALPN, offering http/1.1
    * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    * Server certificate: *.cloudfoundry.org
    * Server certificate: R3
    * Server certificate: DST Root CA X3
    > GET /clock?go-get=1 HTTP/1.1
    > Host: code.cloudfoundry.org
    > User-Agent: curl/7.65.3
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 200 OK
    < Server: nginx
    < Date: Fri, 27 Aug 2021 23:32:12 GMT
    < Content-Type: text/html; charset=utf-8
    < Content-Length: 90
    < Connection: keep-alive
    < Keep-Alive: timeout=20
    < X-Vcap-Request-Id: 6f5ff149-5d63-4294-4155-63a4d251e203
    <
    * Connection #0 to host code.cloudfoundry.org left intact
    <meta http-equiv="refresh" content="0; url=https://godoc.org/code.cloudfoundry.org/clock">

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tianon @AkihiroSuda PTAL

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Wait.. why is this still failing?

```
[2021-08-28T10:16:56.993Z] + docker run --rm -t --privileged -v /home/ubuntu/workspace/moby_PR-42798/.git:/go/src/github.com/docker/docker/.git --name docker-pr3 -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT=316f00be85d959c27673c855a591182948123c38 -e DOCKER_GRAPHDRIVER -e TEST_FORCE_VALIDATE -e VALIDATE_REPO=https://github.com/moby/moby.git -e VALIDATE_BRANCH=master docker:316f00be85d959c27673c855a591182948123c38 hack/validate/vendor
[2021-08-28T10:16:57.563Z] update vendored copy of archive/tar
[2021-08-28T10:16:57.563Z] downloading: https://golang.org/dl/go1.17.src.tar.gz
[2021-08-28T10:16:58.942Z] patching file stat_unix.go
[2021-08-28T10:16:58.942Z] Hunk #1 succeeded at 9 (offset 1 line).
[2021-08-28T10:16:58.942Z] Hunk #2 succeeded at 17 (offset 1 line).
[2021-08-28T10:16:58.942Z] Hunk #3 succeeded at 25 (offset 1 line).
[2021-08-28T10:16:58.942Z] 2021/08/28 10:16:58 Collecting initial packages
[2021-08-28T10:16:58.942Z] 2021/08/28 10:16:58 Download dependencies
[2021-08-28T10:17:02.216Z] 2021/08/28 10:17:02 unrecognized import path "code.cloudfoundry.org/clock" (https fetch: Get "https://code.cloudfoundry.org/clock?go-get=1": x509: certificate signed by unknown authority)
script returned exit code 1[2021-08-28T10:17:02.786Z] + echo Ensuring container killed.
[2021-08-28T10:17:02.786Z] Ensuring container killed.
[2021-08-28T10:17:02.786Z] + docker rm -vf docker-pr3
[2021-08-28T10:17:02.786Z] Error: No such container: docker-pr3
[2021-08-28T10:17:03.068Z] + echo Chowning /workspace to jenkins user
[2021-08-28T10:17:03.068Z] Chowning /workspace to jenkins user
[2021-08-28T10:17:03.068Z] + id -u
[2021-08-28T10:17:03.068Z] + id -g
[2021-08-28T10:17:03.068Z] + docker run --rm -v /home/ubuntu/workspace/moby_PR-42798:/workspace busybox chown -R 1000:1000 /workspace
[2021-08-28T10:17:03.929Z] + bundleName=unit
[2021-08-28T10:17:03.929Z] + echo Creating unit-bundles.tar.gz
[2021-08-28T10:17:03.929Z] Creating unit-bundles.tar.gz
[2021-08-28T10:17:03.929Z] + tar -czvf unit-bundles.tar.gz bundles/junit-report-libnetwork.xml bundles/junit-report.xml bundles/go-test-report-libnetwork.json bundles/go-test-report.json bundles/profile-libnetwork.out bundles/profile.out
[2021-08-28T10:17:03.929Z] bundles/junit-report-libnetwork.xml
[2021-08-28T10:17:03.929Z] bundles/junit-report.xml
[2021-08-28T10:17:03.929Z] bundles/go-test-report-libnetwork.json
[2021-08-28T10:17:03.929Z] bundles/go-test-report.json
[2021-08-28T10:17:03.929Z] bundles/profile-libnetwork.out
[2021-08-28T10:17:03.929Z] bundles/profile.out
[2021-08-28T10:17:03.939Z] Archiving artifacts
[2021-08-28T10:17:04.413Z] Uploaded 2 artifact(s) to https://docker-ci-jenkins-artifacts.s3.amazonaws.com/public/moby/PR-42798/3/artifacts/
[2021-08-28T10:17:04.728Z] + make clean
[2021-08-28T10:17:04.986Z] docker volume rm -f docker-dev-cache
[2021-08-28T10:17:04.986Z] docker-dev-cache
script returned exit code 1
```

**Comment by thaJeztah** [comment]
Temporarily moved to draft until https://github.com/LK4D4/vndr/pull/95 has been merged and released

**Comment by thaJeztah** [comment]
Dang. Looks like it's hitting a different code-path in vndr (perhaps because it's a full vendor cycle?)

**Comment by thaJeztah** [comment]
Closing this, because it was fixed; https://github.com/cloudfoundry/diego-release/issues/589

**Pull request closed without merging**
