### PR TITLE
Upgrade libcontainer to 1d3b2589d734dc94a1719a3af4

### LINKED ISSUE #9979: `docker wait` can return invalid exit codes
POSIX defines process exit codes to be an unsigned 8 bit integer (0-255)
Certain cases can cause `docker wait` to return values out of that range.  For example, by intentionally invoking the OOM killer.  This can cause problems with inspecting the exit code in some shells:

```
root@ip-10-30-38-29:~# docker run -m 4m --name wat -it myjavacontainer java
root@ip-10-30-38-29:~# echo $?
255
root@ip-10-30-38-29:~# docker wait wat
-1
root@ip-10-30-38-29:~# /bin/dash -c 'exit $(docker wait wat)'
/bin/dash: 1: exit: Illegal number: -1
```
I expect `docker wait wat` to return 255, same as the exit code of `docker run`.

### PR DESCRIPTION
**Pull request by icecrime**
Correct exit code when dying on signal (fixes #9979).

### CODE REVIEW

**Comment by icecrime** [comment]
Related PR#10013 can be merged after that one.

**Comment by mrunalp** [comment]
:+1:

**Comment by LK4D4** [comment]
I wonder where is drone badge :E

**Comment by icecrime** [comment]
Lost Drone

**Comment by jfrazelle** [comment]
can you like rebase and force push or something eff idk how to triggger

**Comment by jfrazelle** [comment]
ugh closing and repoening didn't work

**Comment by tianon** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
