### PR TITLE
Vendoring libnetwork

### LINKED ISSUE #14372: --kv-store: failed to initialize bit sequence handler: Key not found in store
Description of problem:
Since today or yesterday, I am unable to use --kv-store with consul when starting the daemon on the experimental branch. This breaks the overlay networking experimental for me.

`docker version`:
```
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   71f8ca3
 Built:        Thu Jul  2 20:43:59 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   71f8ca3
 Built:        Thu Jul  2 20:43:59 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```
`docker info`:
```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 3.66 GiB
Name: mechjeb.vpc.cloudera.com
ID: OE35:VSJZ:EU2H:OCS5:ZRY6:FIFT:KN2Y:J3WA:FMHT:7CA4:NZJ4:ZZ2D
WARNING: No swap limit support
Experimental: true
```

`uname -a`:
`Linux mechjeb.vpc.cloudera.com 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
AWS, Ubuntu 14.04 with vivid kernel.

How reproducible:
Always

Steps to Reproduce:
1. Start 14.04 machine, update kernel to 3.19
2. Start a consul server on localhost/remotely, as described [here](https://github.com/docker/docker/blob/master/experimental/compose_swarm_networking.md)

Actual Results:
Error, daemon dosent start

Expected Results:
Daemon starts.

Additional info:
I'm not sure what subcomponent this is a problem with, so i'm reporting it here. If this is a problem with libkv or libnetwork, i'll move it there if you ask :smile:.  I last tried this on tuesday, with the dev client, and everything worked then.

Daemon logs
```
root@mechjeb:~# docker -d --kv-store consul:172.16.3.211:8500
WARN[0000] Running experimental build                   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Option DefaultDriver: bridge                 
INFO[0000] Option DefaultNetwork: bridge                
INFO[0000] Option OptionKVProvider: consul              
INFO[0000] Option OptionKVProviderURL: 172.16.3.211:8500 
INFO[0000] Firewalld running: false                     
FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to initialize vxlan id manager: failed to initialize bit sequence handler: Key not found in store
```

### PR DESCRIPTION
**Pull request by mrjana**
Vendoring libnetwork commit: 8fb0a8bc9e3166216ca3da2d0bb15332f6685745
    - Fixes breakage in k/v store handling logic in experimental
    - Adds back all the fixes that went in 1.7.1 to master
    - Change VXLAN port in overlay driver to IANA assigned port

Fixes #14372 

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
@mrjana Janky is failing https://jenkins.dockerproject.org/job/Docker-PRs/10814/console

**Comment by vdemeester** [comment]
@thaJeztah Yeah, failing the same on lot's of jobs (like for #13694 http://jenkins.dockerproject.org/job/Docker-PRs/10815/console )

**Comment by thaJeztah** [comment]
@vdemeester ah, thanks. I saw `http/transport` so thought it could be related, but if not, I'll try to restart the builds and see if they complete succesfully.

**Comment by mountkin** [comment]
I applied this patch and found it worked at first.
But when I tried to restart the docker daemon it always fails with the following error message:
```
INFO[0476] GET /v1.20/containers/449d2fd995224278e6b34c51a2afac22b1d5af958084d62d42848b443abe6450/json 
INFO[0476] DELETE /v1.20/containers/449d2fd995224278e6b34c51a2afac22b1d5af958084d62d42848b443abe6450?v=1 
2015/07/06 19:00:44 [DEBUG] serf: messageUserEventType: jl 10.60.45.23 44b2c8d73ec3d9258eca4122da1202d83a4baa9a8b612706080a7c973c46cc3f da69838e75480b74f99831a213b170d6f68d0d58c886609f45705aecb09f80d8
2015/07/06 19:00:44 [DEBUG] serf: messageUserEventType: jl 10.60.45.23 44b2c8d73ec3d9258eca4122da1202d83a4baa9a8b612706080a7c973c46cc3f da69838e75480b74f99831a213b170d6f68d0d58c886609f45705aecb09f80d8
2015/07/06 19:00:44 [DEBUG] serf: messageUserEventType: jl 10.60.45.23 44b2c8d73ec3d9258eca4122da1202d83a4baa9a8b612706080a7c973c46cc3f da69838e75480b74f99831a213b170d6f68d0d58c886609f45705aecb09f80d8
2015/07/06 19:00:44 [DEBUG] serf: messageUserEventType: jl 10.60.45.23 44b2c8d73ec3d9258eca4122da1202d83a4baa9a8b612706080a7c973c46cc3f da69838e75480b74f99831a213b170d6f68d0d58c886609f45705aecb09f80d8
2015/07/06 19:00:46 [DEBUG] memberlist: Initiating push/pull sync with: 10.60.43.80:7946
INFO[0481] Processing signal 'terminated'               
Waiting for /var/run/docker.sock
WARN[0000] Running experimental build                   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Option DefaultDriver: overlay                
INFO[0000] Option DefaultNetwork: multihost             
INFO[0000] Option OptionKVProvider: consul              
INFO[0000] Option OptionKVProviderURL: localhost:8500   
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
, error: exit status 1 
INFO[0000] Firewalld running: false                     
FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to initialize vxlan id manager: failed to initialize bit sequence handler: failed to deserialize head: cannot deserialize byte sequence of lenght 26 ([65 65 65 67 65 65 65 65 65 65 65 65 65 65 81 65 65 65 65 65 65 65 65 65 88 34])
```

**Comment by LK4D4** [comment]
@mrjana Also tests failing with panic :/

**Comment by vdemeester** [comment]
@LK4D4 it seems to be ``DockerSuite.TestApiImagesDelete`` and it's failing on other PR (or even on my laptop & server.. :cry:)

**Comment by LK4D4** [comment]
@vdemeester Is it like race or consistent?

**Comment by vdemeester** [comment]
@LK4D4 well, it's pretty consistent on my server & laptop, it like an infinite loop or something, and it's also doing this on ``DockerSuite.TestApiImagesHistory`` for example.

**Comment by mrjana** [comment]
@mountkin I saw the same issue after I pushed the PR. Working on fixing it

**Comment by thaJeztah** [comment]
For the failing builds, see https://github.com/docker/docker/pull/14409 (thanks, @vdemeester)

**Comment by jgkamat** [comment]
c6dc6bc looks like its working well for me

**Comment by LK4D4** [comment]
LGTM

**Comment by tomdee** [comment]
+1 Builds from this branch are working well for me in manual testing.

**Comment by estesp** [comment]
LGTM

**Pull request merged**
