### PR TITLE
Darn it, I broke CI due to multiple declarations

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Darn, darn, darn. Yes, I broke it. Each of my previous PRs was good on its own, just not all together as each declared the same variable. Sorry! Please merge quickly.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM if janky is happy

**Comment by thaJeztah** [comment]
LGTM :smile:

**Comment by icecrime** [comment]
Just realized the same ;-) I'm fixing this in a branch to refactors the usage of sleeping containers.

Of course LGTM.

**Comment by jhowardmsft** [comment]
#IAmStupid :sob: Yes, this fixes the multiple declarations and gets past the failure. I've taken all the WindowsTP4 CI nodes offline temporarily to avoid false failures until this is merged. Ugh, head bowed in shame. Sorry everyone. I'll sleep in the dog crate tonight, and they can have my bed. Think I deserve it!

stupid

**Comment by jhowardmsft** [comment]
yay

**Comment by jhowardmsft** [comment]
@vdemeester As I'm sure you'll be up soon. This fixes CI on master. My bad :cry:

**Comment by icecrime** [comment]
We don't expect any surprise with gccgo: merging.

**Comment by jhowardmsft** [comment]
Yes, back to green. Please, please, please merge.

**Comment by thaJeztah** [comment]
@jhowardmsft no harm done, sh*t happens, thanks! Now, let that poor dog back in its crate :smile:

**Comment by StefanScherer** [comment]
Seems to happen in "real" world, too - https://twitter.com/thepracticaldev/status/687672086152753152
:smile:

**Pull request merged**
