### PR TITLE
integration: wait for service update to be completed

### PR DESCRIPTION
**Pull request by thaJeztah**
Wondering if this is the cause for `TestServiceUpdateConfigs` to be flaky; this code was added as part of https://github.com/moby/moby/pull/37564, and appeared to be flaky on the PR itself https://github.com/moby/moby/pull/37564#issuecomment-449941135

```
07:40:41 --- FAIL: TestServiceUpdateConfigs (2.90s)
07:40:41     daemon.go:296: [d954a5785d31c] waiting for daemon to start
07:40:41     daemon.go:328: [d954a5785d31c] daemon started
07:40:41     update_test.go:188: assertion failed: error is not nil: Error response from daemon: rpc error: code = Unknown desc = update out of sequence
07:40:41     daemon.go:283: [d954a5785d31c] exiting daemon
07:40:41 FAIL
07:40:41 ---> Making bundle: .integration-daemon-stop (in bundles/test-integration)
07:40:44 Clearing AppArmor profiles cache:.
```

relates to https://github.com/moby/moby/issues/37547

### CODE REVIEW

**Comment by thaJeztah** [comment]
/cc @adshmh @kolyshkin @vdemeester 

I couldn't find a reference why `nil` was also considered "service is converged", so perhaps this is not the right change; it just stood out a bit, so wondering if this was correct.

**Review by vdemeester — DISMISSED** [review]
LGTM :tiger:

**Comment by vdemeester** [comment]
Looking at the failure

```
14:36:48 === RUN   TestServiceUpdateLabel
14:37:20 --- FAIL: TestServiceUpdateLabel (31.93s)
14:37:20     daemon.go:296: [d78c00ad8edaf] waiting for daemon to start
14:37:20     daemon.go:328: [d78c00ad8edaf] daemon started
14:37:20     update_test.go:35: timeout hit after 30s: waiting for service l8u8xz2frkylmuzwyrlf0wjnx to be updated
14:37:20     daemon.go:283: [d78c00ad8edaf] exiting daemon
```

Maybe, `UpdateStatus` is not updated in some cases (like updating labels as it might only update the spec and no desired state change)

**Comment by thaJeztah** [comment]
> Maybe, UpdateStatus is not updated in some cases (like updating labels as it might only update the spec and no desired state change)

@vdemeester Yes, that's what I was thinking as well. I'd have to check with the SwarmKit people; I think that may be troublesome if for _some_ updates we have to wait for it to reach `UpdateStateCompleted`, and for _other_ updates we're ok with it being `nil`.

(Without having dug into it); wondering if the flakiness in the `TestServiceUpdateConfigs` case is that for that test we actually want it to reach `UpdateStateCompleted` and it goes something like;

- (A) Service status becomes `UpdateStatus = nil`
  - we think it completed (but it's actually still in the process of updating)
- (B) Service status becomes `UpdateStatus = TestServiceUpdateConfigs`
  - it _actually_ completed, and `version` is incremented
- (C) we update the service again (using the old `version` from (A))
- (D) test fails ("update out of sequence"), because `version` from (A) was not the last version; we should've used the `version` from (B).

**Comment by thaJeztah** [comment]
ping @aaronlehmann @dperny @anshulpundir could you have a look at this? Wondering if you know if my suspicion above could be right 🤗

**Comment by olljanat** [comment]
@thaJeztah afaik, updating only service specs does no actually generate update tasks. 
How about if we also update/add some container labels with it?

Another thing which I was thinking that how much of these tests actually should be on here and how much on Swarmkit side?

**Comment by thaJeztah** [comment]
Perhaps the issue is that ServiceCreate is asynchronous, so will return immediately, however, the service's tasks are not yet running/converged. Once they converge, the `Version` may be updated 🤔 

Do we need something like is done on the CLI; https://github.com/docker/cli/blob/ae1618713f83e7da07317d579d0675f578de22fa/cli/command/service/progress/progress.go#L75-L205 and https://github.com/docker/cli/blob/ae1618713f83e7da07317d579d0675f578de22fa/cli/command/service/progress/progress.go#L273-L330 ?

**Comment by thaJeztah** [comment]
> Another thing which I was thinking that how much of these tests actually should be on here and how much on Swarmkit side?

That's a good question; I _do_ think we need some integration tests here (as this is the integration point of swarmkit into docker); not sure we need all of them

**Pull request closed without merging**
