### PR TITLE
Fix version comparison when negotiating the the API version

### PR DESCRIPTION
**Pull request by yujuhong**
**- What I did**
Fix version comparison when negotiating the the API version.

**- How I did it**

**- How to verify it**
Unit test.

**- Description for the changelog**

Fix version comparison when negotiating the the API version.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by yujuhong** [comment]
The original behavior was introduced in #33888. /cc @thaJeztah

**Review by dnephin — APPROVED** [review]
LGTM

I think this is correct

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
oh! looks like this is the same as https://github.com/moby/moby/pull/34511, but completely forgot about that one 😞

**Pull request merged**
