### PR TITLE
Allow to change the path where the plugins are loaded from.

### PR DESCRIPTION
**Pull request by calavera**
This patch allows to set the plugins root at the deamon level.

I'm not super happy about the implementation, so all your feedback will be very welcome.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
oh man... I'd punt on this. Don't see why anyone would really _need_ to customize this other than "look ma, I can customize things".

**Comment by calavera** [comment]
@cpuguy83 I totally agree with you, but I'm sure if we don't do it someone else will. To be clear, I'm okay with closing this PR and forget about it.

**Comment by calavera** [comment]
@cpuguy83 I just thought about a case where we'll want to change this, windows :wink: 

Moving forward with this after a rebase.

**Comment by cpuguy83** [comment]
@calavera In that case it's just a constant set in an _windows.go file :)

**Comment by calavera** [comment]
that's very true.

**Comment by thaJeztah** [comment]
Not sure about this either; is there an actual use case already? If not, then I wonder if we should add it just because it *may* become handy.

Just my 0.02

**Comment by calavera** [comment]
Okay, I'm sold, closing this PR.

**Comment by calavera** [comment]
Reopening this because of #13859

**Comment by LK4D4** [comment]
Maybe we should make /var/lib/docker default? :)

**Comment by SvenDowideit** [comment]
For my normal testing, I start the Docker daemon with `docker -d -D -g /data/docker` - which is really its own mounted partition.

rather than hard coding the default to `/var/lib/docker`, perhaps it would be useful to default to `{graphdir}/plugins`.

however, I then note another pain point - the plugin API does not communicate daemon settings to it - so it doesn't know that in this case, it should probably make the the mounts in `/data/docker`.

tbh, I'm hoping the daemon can pass on some more client oriented info too, but that may be pushing it :)

**Comment by calavera** [comment]
@SvenDowideit it cannot go into `{graphdir}/plugins`. We already had that discussion, as @tianon pointed out, the drivers expect a defined structure.

**Comment by calavera** [comment]
Also, keep in mind that `/var/lib/docker` is meant to be ephemeral. You can always wipe out the directory, run `docker run container` and everything works. If we put the plugins directory there, that directory stops being ephemeral, because you'll want to save the plugins configuration.

**Comment by philips** [comment]
Based on the [plugins docs](https://github.com/docker/docker/blob/master/experimental/plugin_api.md) it seems that the plugins are either a unix socket or a spec file pointing to a unix socket (why not a symlink?). The accepted pattern for IPC unix sockets is to put them into /run/<namespace>. So, I would suggest that the plugins be a combination of three locations:

/run/docker/plugins
/etc/docker/plugins
/usr/lib/docker/plugins

And have an inheritance order where /run overrides /etc and /etc overrides /usr on name collision. I would also suggest that both /etc and /usr only be allowed to contain spec files.

**Comment by philips** [comment]
cc @icecrime

**Comment by cpuguy83** [comment]
Sounds legit to me.
I don't like configurable plugin paths at all.

**Comment by calavera** [comment]
Sounds like a good idea to me too, I'll make the changes here and update the title to reflect that.

**Comment by calavera** [comment]
Closing. I'm going to start over in a new pull request.

**Pull request closed without merging**
