### PR TITLE
gofmt 1.4.2  src directory

### PR DESCRIPTION
**Pull request by ankushagarwal**
Run gofmt -s -w on entire source except vendor/ directory
Signed-off-by: Ankush Agarwal ankushagarwal11@gmail.com

### CODE REVIEW

**Comment by ankushagarwal** [comment]
ping @thaJeztah for review

**Comment by unclejack** [comment]
No, this isn't OK as it breaks Go 1.3.

**Comment by duglin** [comment]
We should probably get an "official" ruling on this but I was told that support for 1.3 is on the way out: https://github.com/docker/docker/pull/12009#discussion_r28611257

**Comment by cpuguy83** [comment]
I'm going to close this for now, as @unclejack said we need to keep 1.3 compatibility for now.
If/when we merge userns support is merged we will be forced to change, but that hasn't happened yet.

Thanks for looking at this @ankushagarwal!  We'll probably need to do this again once we make the cut to 1.4.
If you want to discuss feel free to ping me on IRC in #docker-dev.

Thanks again!

**Comment by ankushagarwal** [comment]
My bad, I assumed docker was on go 1.4.2 as I saw `ENV GO_VERSION 1.4.2` in the main Dockerfile

**Comment by cpuguy83** [comment]
@ankushagarwal Indeed, the dev env uses go 1.4, and the binaries that we create are built with 1.4, however downstream also needs to be able to build.

**Comment by ankushagarwal** [comment]
Got it, Thanks!

**Comment by tiborvass** [comment]
@unclejack @cpuguy83 sorry for the confusion but I was told by both @tianon and @vbatts that we're dropping support for go 1.3. So from my point of view, this PR is welcome.

**Comment by tiborvass** [comment]
Source: https://botbot.me/freenode/docker-maintainers/2015-04-17/?msg=36876505&page=2

**Comment by tiborvass** [comment]
@unclejack @cpuguy83 Let me know quickly if you still have concerns. Otherwise I'll reopen this PR.

**Comment by cpuguy83** [comment]
SGTM

**Comment by cpuguy83** [comment]
Do we need to disable the gofmt 1.3 checking on janky?

**Comment by tianon** [comment]
Yes, if we're committed to this, and also update project/PACKAGERS.md
appropriately.

**Comment by jfrazelle** [comment]
LGTM since project Pacakgers was updated in https://github.com/docker/docker/commit/e1fd7e25de4574b78cce41becd8ee50bdff23f0c

**Pull request merged**
