### PR TITLE
docs: fix file's permissions

### PR DESCRIPTION
**Pull request by laijs**
The README.md and the *.png should not have the executable
permissions, remove them.

Signed-off-by: Lai Jiangshan jiangshanlai@gmail.com

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM

**Comment by laijs** [comment]
ping

**Comment by LK4D4** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
LGTM -- Nice catch.

**Pull request merged**
