### PR TITLE
Sync with remote API

### PR DESCRIPTION
**Pull request by luca3m**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh, thanks @luca3m, well spotted!

! I noticed the man-page also isn't updated with the newer events, could you update that as well?

https://github.com/docker/docker/blob/master/man/docker-events.1.md 

Also could you squash your commits? We have instructions for that in our contribution guide; https://docs.docker.com/project/work-issue/#pull-and-rebase-frequently, but feel free to ask for help in the #docker-dev IRC channel on freenode :+1:

**Comment by luca3m** [comment]
thanks @thaJeztah for the review. I've updated also the man page

**Comment by thaJeztah** [comment]
Great! Thanks so much for contributing :-)

LGTM

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit for the merge :-)

**Comment by moxiegirl** [comment]
@luca3m Thank you for the contribution! LGTM!

**Pull request merged**
