### PR TITLE
AppArmor Engine Policy complain-only & improve ruleset

### PR DESCRIPTION
**Pull request by ewindisch**
To prevent breakages for users and to assess the
impact of the engine policy for users (especially those
on less common graph drivers), mark the policy as
complain-only until we are comfortable removing this
tag.

Implements the policies for the remaining binaries
called by the Docker engine and eliminates the
giant whitelisted 'all files' permission in favor
of granular whitelisting and child-specific policies.

Signed-off-by: Eric Windisch eric@windisch.us

### CODE REVIEW

**Comment by ewindisch** [comment]
This should unbreak Ubuntu/Debian packages. /cc @duglin @jhowardmsft @runcom

**Comment by jhowardmsft** [comment]
@ewindisch - Hmmm. I just tried compiling this branch (this time using a 1.7.1 daemon), and then re-compiling again, but with the previously built daemon running. Unfortunately I'm seeing the same symptoms as before still (as in won't compile).
won t compile

**Comment by jhowardmsft** [comment]
NM, rebased off master and re-verified. Can now compile using the latest daemon. LGTM, solved my issues.

**Comment by dweomer** [comment]
As per [this comment on #14985] (https://github.com/docker/docker/issues/14985#issuecomment-125396849) I have leveraged the changes in this apparmor.d entry. Now, however, I am unable to successfully invoke `docker stop`.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
I think we should just warn for now then next release we can error out, otherwise its super scary for users of just the static binary

**Comment by ewindisch** [comment]
@jfrazelle this PR was making the apparmor *engine* policy soft, such that there would be no hard errors. To help defuse the confusion, I've combined my PRs into #15099

**Comment by calavera** [comment]
Thanks @ewindisch. I'm going to close this PR in favor of #15099.

**Pull request closed without merging**
