### PR TITLE
Modify the comment of Makefile

### PR DESCRIPTION
**Pull request by miaoyq**
`docs/sources/contributing/devenvironment.md`  can not be find in the project. I will delete it.

Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

### CODE REVIEW

**Comment by miaoyq** [comment]
Very sorry!  I made a mistake. I mean, I will delete the corresponding comment from the `Makefile`.

**Comment by miaoyq** [comment]
Very sorry!  I made a mistake. I mean, I will delete the corresponding comment from the `Makefile`.

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
please squash your commits and sign them

**Comment by miaoyq** [comment]
Squashed. PTAL @duglin Thanks a lot!

**Comment by duglin** [comment]
LGTM
ping @vdemeester for the merge

**Comment by runcom** [comment]
LGTM

**Pull request merged**
