### PR TITLE
Revert "migrated service integration tests from integration-cli/docke…

### PR DESCRIPTION
**Pull request by vdemeester**
…r_cli_service_update_test.go to integration/service"

This reverts commit fbaef1b0d3c5656a8aa5f0424b89c118ca277427.

Those tests are a bit too much flakey, let's revert and re-work on the migration.

cc @adshmh 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM; let's open a new PR with this change and see if we can find out where the flakiness comes from

**Review by yongtang — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Failure on janky is due to

```
09:14:56 The following new tests were added to integration-cli:
09:14:56 
09:14:56 +func (s *DockerSwarmSuite) TestServiceUpdateLabel(c *check.C) {
09:14:56 +func (s *DockerSwarmSuite) TestServiceUpdateSecrets(c *check.C) {
09:14:56 +func (s *DockerSwarmSuite) TestServiceUpdateConfigs(c *check.C) {
09:14:56 
09:14:56 integration-cli is deprecated. Please add an API integration test to
09:14:56 ./integration/COMPONENT/. See ./TESTING.md for more details.
09:14:56

**Comment by thaJeztah** [comment]
merging because everything else is green, and to unblock CI on other Prs

**Pull request merged**
