### PR TITLE
fix flaky TestRunContainerWithRmFlag tests

### LINKED ISSUE #43679: Flaky test: TestRunContainerWithRmFlagCannotStartContainer (on windows)
This test has failed frequently recently; https://github.com/moby/moby/search?q=TestRunContainerWithRmFlagCannotStartContainer&type=issues

- was once marked as racy/flaky a long time ago: https://github.com/moby/moby/issues/11966
- originally fixed in: https://github.com/moby/moby/pull/12206

```
=== FAIL: github.com/docker/docker/integration-cli TestDockerSuite/TestRunContainerWithRmFlagCannotStartContainer (2.17s)
    docker_cli_run_test.go:2770: Expected not to have containers 357547ca53b5
        
    --- FAIL: TestDockerSuite/TestRunContainerWithRmFlagCannotStartContainer (2.17s)

=== FAIL: github.com/docker/docker/integration-cli TestDockerSuite (3440.51s)
```

### PR DESCRIPTION
**Pull request by thaJeztah**
- fixes https://github.com/moby/moby/issues/43679

This attempts to fix CI flakiness on the TestRunContainerWithRmFlagCannotStartContainer
and TestRunContainerWithRmFlagExitCodeNotEqualToZero tests.

These tests;

- get a list of all container ID's
- run a container with `--rm`
- wait for it to exit
- checks that the list of all container IDs is empty

The last step assumes that no other tests are running on the same daemon; if
another test is running, there may be other containers present (unrelated to
the test).

This patch updates the tests to use a `docker inspect` to verify the container
no longer exists afterwards.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
And of course it failed on two other flaky tests, but not the one I fixed 🥳

**Comment by thaJeztah** [comment]
Ah, boo; CRIU repo is down indeed;

```
executor failed running [/bin/sh -c echo 'deb https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_11/ /' > /etc/apt/sources.list.d/criu.list         && apt-get update         && apt-get install -y --no-install-recommends criu         && install -D /usr/sbin/criu /build/criu]: exit code: 100
script returned exit code 1
```

**Comment by thaJeztah** [comment]
@rumpl @tianon @crazy-max ptal

**Review by crazy-max — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Comment by crazy-max** [comment]
@thaJeztah Looks like it's still flaky: https://github.com/moby/moby/runs/6728287370?check_suite_focus=true#step:15:1974

**Comment by thaJeztah** [comment]
Ah, dang.

I guess it's just slowness on Windows then; thinking of it; the `--rm` was moved to the daemon at some point (before, it was done by the CLI, and synchronous); since it was moved to the daemon, the `--rm` is asynchronous, so I guess the removal may not have taken place the moment it does the `docker inspect` 😞 

Some possible options;

- add a `time.Sleep()` (yuk!)
- do the inspect in a loop (yuk?)
- listen for `remove` events? (yuk?)

**Pull request merged**
