### PR TITLE
Remove obsolete libcontainerd flags.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <shishirm@nvidia.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
I can see this behaviour on my fedora rawhide AWS instance:
`Fedora release 27 (Rawhide)`

NOTE: All the binaries are compiled from the upstream source: dockerd, containerd, containerd-shim and runc.

When I start my `/usr/bin/dockerd` it goes into `libcontainerd/remote_unix.go` and reads `/var/run/docker/libcontainerd/docker-container.pid`. It takes that PID and calls `IsProcessAlive` to check if there is already a previously running instance of `containerd`.

If there is not, it starts a fresh instance of `containerd` and since all these flags don't exist in `containerd` anymore it start to throw errors.

Shishir

**Comment by thaJeztah** [comment]
@shishir-a412ed build looks to be failing.

> NOTE: All the binaries are compiled from the upstream source: dockerd, containerd, containerd-shim and runc.

Are those "master" versions of `containerd` upstream? If so, that won't work currently; this repository still uses a specific commit for those (see https://github.com/moby/moby/blob/cd35e4beee13a7c193e2a89008cd87d38fcd0161/hack/dockerfile/binaries-commits#L7)

**Comment by shishir-a412ed** [comment]
@thaJeztah Strange but I don't see that commit in the `containerd` source tree :)

````
[fedora@ip-172-31-7-223 containerd]$ git remote -v
origin	git@github.com:containerd/containerd.git (fetch)
origin	git@github.com:containerd/containerd.git (push)
[fedora@ip-172-31-7-223 containerd]$ git diff origin/master
[fedora@ip-172-31-7-223 containerd]$ git log --pretty=oneline|grep 3addd840653146c
[fedora@ip-172-31-7-223 containerd]$ 
````

**Comment by thaJeztah** [comment]
hm, odd, I do see it on GitHub; https://github.com/containerd/containerd/commit/3addd840653146c90a254301d6c3a663c7fd6429, but it's in the 0.2.x branch, could that be the reason it doesn't show?

**Comment by shishir-a412ed** [comment]
@thaJeztah Interesting ! I was checking against `master` branch. I will check into `0.2.x` branch.

**Comment by thaJeztah** [comment]
Master branch containerd is the work-in-progress next version of containerd and is a _huge_ change. Moby project will eventually switch to that, but it's not stable/mature enough to make that change now

**Comment by shishir-a412ed** [comment]
@thaJeztah One last question !

Which version (commit) of `runc` should I use ?
The one mentioned here https://github.com/moby/moby/blob/cd35e4beee13a7c193e2a89008cd87d38fcd0161/hack/dockerfile/binaries-commits#L7

I didn't find this commit in any of the branches, including master of runc.
https://github.com/opencontainers/runc

Shishir

**Comment by thaJeztah** [comment]
For Runc we (temporarily) had to switch to a fork, because there was a breaking change in Runc that caused issues (see https://github.com/moby/moby/pull/33577); you can find that commit in https://github.com/docker/runc

**Comment by thaJeztah** [comment]
Probably that repo could be put in the moby org, guess this was faster

**Comment by shishir-a412ed** [comment]
@thaJeztah Should I open a PR to update this file
https://github.com/moby/moby/blob/cd35e4beee13a7c193e2a89008cd87d38fcd0161/hack/dockerfile/binaries-commits#L7 ?

To reflect the right commits and branches. This would help contributors outside of docker who are trying to compile all these binaries with the right commits.

**Comment by thaJeztah** [comment]
@shishir-a412ed the commits are right; the containerd 0.2 branch is used, because containerd master is a complete rewrite of containerd, so not something that can just be used. The moby repository pins to specific commits (just as with other vendored dependencies) to make sure all code matches, and builds are reproducible.

Similar for Runc; a fork is used because we had to patch runc for a backward breaking change

**Pull request closed without merging**
