### PR TITLE
Update dockernetworks.md

### PR DESCRIPTION
**Pull request by cloojure**
Please provide the following information:
- What did you do?
- How did you do it?
- How do I see it or verify it?
- A picture of a cute animal (not mandatory but encouraged)

Make command line prompts consistent for both host and container shells.

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by cloojure** [comment]
Forgot my cute animal photo!  Doh!

![boyds]
(http://en.bcdn.biz/Images/2014/4/22/96ac151e-be6d-4d50-b54c-d2267e094c2f.jpg)

**Comment by SvenDowideit** [comment]
LGTM

**Comment by SvenDowideit** [comment]
@thaJeztah @moxiegirl

**Comment by thaJeztah** [comment]
oh! yes looked at this one and wondered if anyone would notice that the hostnames were all the same (for various containers) :innocent: 

Probably nobody will notice, so LGTM

thanks @cloojure!

**Pull request merged**
