### PR TITLE
ci: print Windows daemon event log timestamps

### PR DESCRIPTION
**Pull request by corhere**
**- What I did**
Added timestamps and the log level to the daemon log entries scraped from the Windows event log so they can be correlated with containerd and integration test logs.

**- How I did it**
⚡ Power ⚡ Shell ⚡ 

**- How to verify it**
Run the workflow and [inspect the output manually.](https://github.com/moby/moby/runs/7979686086?check_suite_focus=true#step:21:24)

**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by corhere** [comment]
@thaJeztah @crazy-max PTAL

**Review by crazy-max — APPROVED** [review]

**Comment by thaJeztah** [comment]
The timestamps seem useful, but looking at the example run you linked, I wonder if there's something we need to change;

- The default `LevelDisplayName` looks to be `[Information]`, but the log-level of the daemon (?) for most of those appears to be `debug:`
- For Errors and Warnings, the `LevelDisplayName` are `[Error]` and `[Warning]`, however (see below), it looks like there's also an `Error:` and `Warning:` printed at the start it the line, so the timestamp is no longer the first column in that case.

Do we know what prints the `Warning:` and `Error:` prefixes?


```
2022-08-23T17:56:48.6999645Z [Information] debug: accept [module=libcontainerd namespace=moby stderr=\\.\pipe\containerd-01b5aad4cfdb18f0ab1f6d17cc5e05e913d04106814e1595797e44fce3f5aa77-init-stderr]
2022-08-23T17:56:48.7016605Z [Information] debug: connected [module=libcontainerd namespace=moby stdout=\\.\pipe\containerd-7c8c0a05c16e4c48f3d30f50a797cf2b50d6530c290a0497356cace4f94f83bc-init-stdout]
...
2022-08-23T18:03:11.6752479Z [Information] debug: WindowsGraphDriver Put() id bf2a0b6a50d65aa68c0354b420835f08486ef9bf90279741e6de329d3b44645f
Error: 2022-08-23T18:03:11.7580259Z [Error] Handler for GET /v1.43/containers/bf2a0b6a50d65aa68c0354b420835f08486ef9bf90279741e6de329d3b44645f/archive returned error: CreateFile \\?\Volume{b94df29d-3f2a-4770-b97c-c00178c15e69}\windows\system32\drivers\etc\hosts\: The filename, directory name, or volume label syntax is incorrect.
...
2022-08-23T18:04:02.9711291Z [Information] debug: Calling DELETE /v1.43/containers/ba7c105dd794879a8551bd029e1f8543c67cc45bbeaedb74643238a0a4cd9899?force=1&v=1
2022-08-23T18:04:02.9716399Z [Information] debug: Sending kill signal 9 to container ba7c105dd794879a8551bd029e1f8543c67cc45bbeaedb74643238a0a4cd9899
Warning: 2022-08-23T18:04:03.8983889Z [Warning] Health check for container c5518b9bd2895e9c24b5b491f016296470ff6b9edb73179c46c2896e7cb06909 error: timed out starting health check for container c5518b9bd2895e9c24b5b491f016296470ff6b9edb73179c46c2896e7cb06909
2022-08-23T18:04:03.9510174Z [Information] debug: event [module=libcontainerd namespace=moby topic=/tasks/exit]
```


w.r.t. the timestamps; I guess this whole formatting is because we run dockerd as a service, so we don't get the output from logrus but through Window's logs (was thinking; would it make life easier to get the output as-is from logrus, but I guess that's not an option);

```
/ # dockerd --debug
INFO[2022-08-23T21:42:25.047162760Z] Starting up
WARN[2022-08-23T21:42:25.059892962Z] could not change group /var/run/docker.sock to docker: group docker not found
DEBU[2022-08-23T21:42:25.061180229Z] Listener created for HTTP on unix (/var/run/docker.sock)
DEBU[2022-08-23T21:42:25.062286572Z] Containerd not running, starting daemon managed containerd
INFO[2022-08-23T21:42:25.076544807Z] libcontainerd: started new containerd process  pid=27
...
```

**Comment by corhere** [comment]
> * The default `LevelDisplayName` looks to be `[Information]`, but the log-level of the daemon (?) for most of those appears to be `debug:`

There are fewer levels in Windows events than Logrus.
https://github.com/moby/moby/blob/6b7974cf1662d56a9aadc2b5c2ad12a80b448671/cmd/dockerd/service_windows.go#L84-L105
The `debug:` prefix comes from the string interpolation of the event message.
https://github.com/moby/moby/blob/6b7974cf1662d56a9aadc2b5c2ad12a80b448671/cli/winresources/event_messages.mc#L6-L9

> * For Errors and Warnings, the `LevelDisplayName` are `[Error]` and `[Warning]`, however (see below), it looks like there's also an `Error:` and `Warning:` printed at the start it the line, so the timestamp is no longer the first column in that case.
> 
> Do we know what prints the `Warning:` and `Error:` prefixes?

As far as I can tell it's an undocumented feature of GitHub Actions. My best guess is that it's grepping log lines for `Error` or `Warning` tokens and prefixing+colouring the lines. It certainly isn't the PowerShell script; the prefixes are not present in the raw action logs.
 
> w.r.t. the timestamps; I guess this whole formatting is because we run dockerd as a service, so we don't get the output from logrus but through Window's logs (was thinking; would it make life easier to get the output as-is from logrus, but I guess that's not an option);

The Windows logs _are_ the output from logrus. It's Just Another Formatter, analogous to `TextFormatter` or `JSONFormatter`. (Technically it's implemented as a hook as the output is not an `io.Writer`, but it doesn't really matter.) Being able to slice, dice, filter and format log entries as rich objects _without parsing_ makes life easy! Look at how straightforward it is to customize exactly how the timestamps are formatted, including the fiddly timezone stuff.

The daemon registers another logrus hook, [`etwlogrus`](https://pkg.go.dev/github.com/microsoft/go-winio/pkg/etwlogrus), which leverages the modern [TraceLogging](https://docs.microsoft.com/en-us/windows/win32/tracelogging/trace-logging-portal) infrastructure to log each entry as a rich object with full fidelity, including all fields as structured K-V pairs [and the precise logrus level.](https://github.com/microsoft/go-winio/blob/1a8911d1ed007260465c3bfbbc785ac6915a0bb8/pkg/etwlogrus/hook.go#L59-L65) Furthermore, _containerd and containerd-shim-runhcs-v2 also register `etwlogrus` hooks on their respective loggers._ It is therefore possible to capture daemon, containerd and shim logs in a single combined trace! And because each log entry is a rich object, they could still be split out after the fact if desired. The only catch is that these `TraceLogging` logs don't get written to the Windows Event Log out of the box, unlike the legacy `windows.ReportEvent` API the other hook uses. A [little bit of scripting](https://docs.microsoft.com/en-us/powershell/module/eventtracingmanagement/start-etwtracesession?view=windowsserver2022-ps) is required to start and stop capturing those logs, and to export the captured logs into text and/or structured formats so non-Windows tools can be used to view, slice & dice the logs. That's the direction I think we should go for capturing logs on Windows in CI, not logrus-formatted text streams. A bit more up-front work is needed to make this happen, but I think it would make life so much easier when actually digging into the logs for a failed CI run. Imagine having all the power of Kibana! This PR is merely a stopgap until I get in front of a Windows box to write and test the tooling to leverage the `etwlogrus` infrastructure.

**Comment by thaJeztah** [comment]
> The debug: prefix comes from the string interpolation of the event message.

Hm.. interesting; given that the Windows event logs containers the information in more structured format, perhaps we should consider removing that (as it's just duplicating the metadata).

Either way; that's definitely for a separate PR.

> As far as I can tell it's an undocumented feature of GitHub Actions. My best guess is that it's grepping log lines for Error or Warning tokens and prefixing+colouring the lines. It certainly isn't the PowerShell script; the prefixes are not present in the raw action logs.

Hmm... sigh.. that's a bit unfortunate. Perhaps I should ask around if there's an option to disable that somehow 🤔

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by corhere** [comment]
> > The debug: prefix comes from the string interpolation of the event message.
> 
> Hm.. interesting; given that the Windows event logs containers the information in more structured format, perhaps we should consider removing that (as it's just duplicating the metadata).

There is no duplication of metadata to remove. The `debug:` string _is not prepended_ to any log entry string as logged by the daemon. Each log entry consists of an integer message ID and an array of strings to interpolate into it. It is the log reading tooling which looks up the message string for the message ID for the given language and locale and interpolates the string arguments into it. (Think `gettext()`, but from the 16-bit era.) Another way to look at it is we are effectively using the message ID as a way to encode the logrus level at full fidelity in Windows Event Log format. I'm pretty sure you can filter logs by message ID so it's possible to filter out debug logs after the fact, without grepping.

**Pull request merged**
