### PR TITLE
Remove -h flag from completion and daemon reference

### PR DESCRIPTION
**Pull request by albers**
All docker subcommands support `-h` as an alias for `--help` unless they have `-h` aliased to something else like `docker run`, which uses `-h` for `--hostname`.

`-h` is not included in the help messages of the commands, though.
The only place where it is visible is the docker daemon reference, see output of `grep -Rs -e --help=false .`

For consistency reasons, this PR removes `-h` as an alias for `--help` from the reference page and the bash completion.

edit: `-h` also appears in `docker` man page, PR amended to remove it there too.

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by albers** [comment]
@tiborvass found another occrurrance, will update soon.

**Comment by albers** [comment]
@tiborvass pushed update.

**Comment by thaJeztah** [comment]
Should we actually *remove* the `-h` shorthand, if it's referenced nowhere? If we do, we should add it to the deprecation list

**Comment by jfrazelle** [comment]
LGTM but we should add to change log in release cause people might complain

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
Cherry picked into #15809

**Pull request merged**
