### PR TITLE
integ-cli: Fix path issues in docker cp tests

### PR DESCRIPTION
**Pull request by ahmetb**
Some of the `docker cp` tests were using `path/filepath` to
craft unix paths. This wouldn't work on Windows since filepath
is platform-dependent.

Moved code to `path` as much as possible and hacked away some
`path/filepath` functionality that doesn't exist in `path` pkg.

This fixes the following test cases:
- `TestCpGarbagePath`
- `TestCpRelativePath`
- `TestCpAbsoluteSymlink`
- `TestCpSymlinkComponent`

Signed-off-by: Ahmet Alp Balkan ahmetalpbalkan@gmail.com
cc: @cyphar @unclejack @duglin @jfrazelle @tianon

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
> https://jenkins.dockerproject.com/job/Windows-PRs/56/console
=== RUN TestCpGarbagePath
[PASSED]: cp - garbage paths relative to container's rootfs
--- PASS: TestCpGarbagePath (1.10s)
=== RUN TestCpRelativePath
[PASSED]: cp - relative paths relative to container's rootfs
--- PASS: TestCpRelativePath (1.16s)
[...]
=== RUN TestCpAbsoluteSymlink
[PASSED]: cp - absolute symlink relative to container's rootfs
--- PASS: TestCpAbsoluteSymlink (1.12s)
=== RUN TestCpSymlinkComponent
[PASSED]: cp - symlink path components relative to container's rootfs
--- PASS: TestCpSymlinkComponent (1.14s) 

:+1: happy CI is happy.

**Comment by duglin** [comment]
LGTM

**Comment by cyphar** [comment]
IANAM, but yeah it should've used `path` from the outset.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
thanks @cyphar we always value your opinion :)

**Pull request merged**
