### PR TITLE
Fix for zero-sized layers

### LINKED ISSUE #18170: Regression in docker load
I did a `docker save` of library/centos:6 back in March of 2015.  I have been able to successfully `docker load` that tarball across many versions of Docker.

Starting with *at least* version 1.9.0, I get the following when trying to run docker load:

```
› docker load < image.tar
Error response from daemon: EOF
```
Same error whether I use the other variants of the load command:
```
> cat image.tar | docker load
> docker load -i image.tar
```
Here is the history of the base image:
```
docker history --no-trunc=true library/centos:6-2015.03.20
IMAGE                                                              CREATED             CREATED BY                                                                                         SIZE                COMMENT
f6808a3e4d9e80a655ec625e38b869ed8a614611e4d0073aeff23be841c9fcff   8 months ago        /bin/sh -c #(nop) ADD file:2b2b26209d285cd1a96e8168dfb25338aa09155d0a9a6ed54a94be0bd9914461 in /   215.7 MB
5b12ef8fd57065237a6833039acc0e7f68e363c15d8abb5cacce7143a1f7de8a   13 months ago       /bin/sh -c #(nop) MAINTAINER The CentOS Project <cloud-ops@centos.org> - ami_creator               0 B
511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158   2 years ago                                                                                                            0 B                 Imported from -
```
Looking at `docker.log`, it appears to be choking on the MAINTAINER layer:
```
time="2015-11-23T16:09:33.163005791Z" level=debug msg="Loading 5b12ef8fd57065237a6833039acc0e7f68e363c15d8abb5cacce7143a1f7de8a"
time="2015-11-23T16:09:33.181494348Z" level=error msg="Handler for POST /v1.21/images/load returned error: EOF"
time="2015-11-23T16:09:33.181535527Z" level=error msg="HTTP Error" err=EOF statusCode=500
```

Every image I've been has ultimately depended on this image and now they are all unloadable.

### PR DESCRIPTION
**Pull request by duglin**
Closes #18170 

Add support for loading an image where one layer is empty - literally zero bytes in the tar file, no padding or anything.  Not sure how we got into this state, I can't reproduce it, but nevertheless there's an image in Dockerhub like this ( matthughes/library-centos:6-2015.03.20 ) so this makes sure we can load it.

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
ping @vbatts

**Comment by LK4D4** [comment]
LGTM

**Comment by duglin** [comment]
moved a defer up a little to a better spot - thanks to @MHBauer for noticing.

**Comment by vbatts** [comment]
So interesting. It seems like we hardly need to do more than just return as if the read is done, but this seems fine.
LGTM

**Comment by thaJeztah** [comment]
counting two LGTM's so moved to "merge"

**Comment by duglin** [comment]
let's wait for the tests to finish first, just want to make sure the move of the defer doesn't break something

**Comment by thaJeztah** [comment]
@duglin that's why I applied the label, and didn't press the button :+1:

**Comment by tonistiigi** [comment]
Why do we do this is tar loading? If such images exist wouldn't they fail on pulls also?

**Comment by MHBauer** [comment]
Pulls fine for me:
```
λ docker pull matthughes/library-centos:6-2015.03.20
6-2015.03.20: Pulling from matthughes/library-centos
17d1436ef796: Pull complete
9c7cb910d843: Pull complete
25445a0fc502: Pull complete
Digest: sha256:aaba82794dff22b95c649cdd03fcdf3929ce5ecc953403718e713336bc6f9a85
Status: Downloaded newer image for matthughes/library-centos:6-2015.03.20

λ docker images matthughes/library-centos:6-2015.03.20
REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
matthughes/library-centos   6-2015.03.20        25445a0fc502        8 months ago        215.7 MB

λ docker history matthughes/library-centos:6-2015.03.20
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
25445a0fc502        8 months ago        /bin/sh -c #(nop) ADD file:2b2b26209d285cd1a9   215.7 MB
9c7cb910d843        13 months ago       /bin/sh -c #(nop) MAINTAINER The CentOS Proje   0 B
17d1436ef796        2 years ago                                                         0 B                 Imported from -
```

**Comment by duglin** [comment]
@tonistiigi I originally had this fix in that func but then the unit tests failed because there are cases where EOF is a valid return value (error cases) and the unit tests were looking for them. So I moved this logic up a level.  Not 100% sure this is still the right spot but it did seem to fix it.

**Comment by tonistiigi** [comment]
This change is better to understand now with all the pools gone but I still doubt it's the correct approach.

First, this isn't specific to `load`. The problem appears when you point empty file to `DecompressStream` and for this image, in the registry, the blob is compressed so the error doesn't appear. I pushed the same image uncompressed as `tonistiigi/library-centos:6-2015.03.20` and it fails on pull just like load does.

Other problem is that if the tar was some random garbage less than 10 bytes, then with this fix we would completely ignore the error.

My suggestion would be that if `DecompressStream` cannot detect the compression because of an error on `Peek()` it should just redirect the data as uncompressed and not error by itself. This breaks a unit test `TestUntarPathWithInvalidDest` but if you look at what the test does, it should really be named `TestUnpackingEmptyFileShouldFail`, so I'm not sure which behavior we want.

If for some reason we want to have exceptions for pull/load etc. but not change the function we should define `DecompressStreamAllowEmpty()` or `IsEmptyReader()` and call that instead in pull/load code.

Also, I'm not sure if we should count empty file as a valid tar's at all. Maybe it's ok to error. Not sure what has caused them in this image.

**Comment by duglin** [comment]
Removed the "merge" status for now - needs more reviews/work.

**Comment by duglin** [comment]
@tonistiigi you were correct to push on the validity of the unit testcase. It was passing for the wrong reasons.  Once I fixed that ignoring EOF in DecompressStream does seem to work. The test now, correctly, uses an invalid destination and will fail for that reason, not due to the source tar being empty.
See what you think.

**Comment by tonistiigi** [comment]
LGTM

**Comment by duglin** [comment]
@vbatts and @LK4D4 can you guys re-review it, just to be sure? thanks.

**Comment by duglin** [comment]
@tonistiigi thanks for the help

**Comment by estesp** [comment]
LGTM on the updated fix

**Comment by vbatts** [comment]
LGTM

**Comment by matthughes** [comment]
Thanks so much @duglin !

**Comment by duglin** [comment]
@matthughes you're welcome - let me know if it doesn't fix it  :-)

**Pull request merged**
