### PR TITLE
[25.0 backport] image/save: Fix untagged images not present in index.json

### PR DESCRIPTION
**Pull request by vvoland**
- backport: https://github.com/moby/moby/pull/47232
- fixes: https://github.com/moby/moby/issues/47210
- closes: https://github.com/moby/moby/issues/47165

Saving an image via digested reference, ID or truncated ID doesn't store the image reference in the archive. This also causes the save code to not add the image's manifest to the index.json.
This PR explicitly adds the untagged manifests to the index.json if no tagged manifests were added.

**- How to verify it**

- TestSaveOCI integration test

#### By digest
```bash
$ docker save hello-world@sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6 | tar xO index.json | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}

```

#### By tag
```bash
$ docker save hello-world | tar xO index.json | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/hello-world:latest",
        "org.opencontainers.image.ref.name": "latest"
      },
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}

```

#### Tag and digest
```bash
$ docker tag hello-world my:hello
$ docker save hello-world my:hello \
   hello-world@sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6 | \
   tar xO index.json | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/hello-world:latest",
        "org.opencontainers.image.ref.name": "latest"
      },
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:411caf340c828657e915a83ed561a79d2b8150dabad4dc079d881cbfe6f86afe",
      "size": 447,
      "annotations": {
        "io.containerd.image.name": "docker.io/library/my:hello",
        "org.opencontainers.image.ref.name": "hello"
      },
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}

```

**- Description for the changelog**
```release-note
- Fix `docker save <image>@<digest>` producing an OCI archive with index without manifests
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vvoland** [comment]
Huh, looks like the one test case is failing here, but doesn't in the master PR:

```
=== Failed
=== FAIL: amd64.integration.image TestSaveOCI/sha256:1c35c441208254cb7c3844ba95a96485388cef9ccc0646d562c7fc026e04c807 (0.01s)
    save_test.go:154: assertion failed: expected [] (length 0) to have length 1
    --- FAIL: TestSaveOCI/sha256:1c35c441208254cb7c3844ba95a96485388cef9ccc0646d562c7fc026e04c807 (0.01s)

=== FAIL: amd64.integration.image TestSaveOCI (0.06s)

```

**Comment by thaJeztah** [comment]
Let me move this to draft temporarily until master has been reviewed (I'll ask others to review the queue for 25.0.3 - want to prevent trigger-happy merges 😂 )

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]

**Comment by thaJeztah** [comment]
failures are the expected ones; so we can bring this one in; thanks!

**Pull request merged**
