### PR TITLE
man docker-tag minor fixup

### PR DESCRIPTION
**Pull request by sallyom**
Signed-off-by: Sally O'Malley somalley@redhat.com

### CODE REVIEW

**Comment by sallyom** [comment]
thanks to Robert Day for finding these glitches :)

**Comment by SvenDowideit** [comment]
LGTM - @thaJeztah @moxiegirl

**Comment by thaJeztah** [comment]
Thanks @sallyom! changes LGTM, however, recently there was a discussion about the `-h` shorthand for help; https://github.com/docker/docker/pull/15449.


ping @tiborvass @jfrazelle wdyt, should we deprecated the `-h` shorthand for all commands?

**Comment by sallyom** [comment]
I see now that all other commands do not show the -h shorthand,  I've edited to keep consistent. ( I missed that issue)

**Comment by tiborvass** [comment]
@thaJeztah not sure. If anything I would have loved to not have `-h` mean `--hostname`.

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
`-h` is pretty much industry standard for help.  Why would we want to change that?

**Comment by thaJeztah** [comment]
@moxiegirl `-h` is used as shorthand for `--hostname` for docker run (https://github.com/docker/docker/pull/15449#issue-100082706), but you're right, would be better if we could get rid of that instead of dropping `-h` for help.

re-LGTM, because this is consistent with the other documents. We can use a separate issue/PR to consistently add `-h` to all docs/man pages if we want

Thanks for all these touch-up PRs, @sallyom, very much appreciated!

**Comment by sallyom** [comment]
I love it!  Thanks to Robert PJ Day for finding them.  :)

**Pull request merged**
