### PR TITLE
Update fluent-logger-golang to v1.2.0.

### PR DESCRIPTION
**Pull request by tagomoris**
**\- What I did**
This change fixes the problem of "panic: runtime error: invalid memory address or nil pointer dereference", described in #20960.

**\- How I did it**
fluent-logger-golang has been fixed to solve race condition of internal buffers, and this change will use the fixed version `v1.2.0` to send logs to Fluentd nodes.
https://github.com/fluent/fluent-logger-golang/pull/30

**\- How to verify it**
We made a short golang code to generate the same error with one from Docker, and confirmed that fixed fluent-logger-golang doesn't crash with just same program.
https://github.com/fluent/fluent-logger-golang/issues/29

**\- Description for the changelog**
Update fluent-logger-golang dependency to v1.2.0.

**\- A picture of a cute animal (not mandatory but encouraged)**
latest fluentd logo

Fix race condition issue to solve an issue about "panic: runtime error: invalid memory address or nil pointer dereference".
This fix stabilize Docker daemon under the situation of communication problem with Fluentd processes.

Signed-off-by: Satoshi Tagomori tagomoris@gmail.com

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by LK4D4 — APPROVED** [review]
LGTM

**Comment by tagomoris** [comment]
Thank you!

**Comment by thaJeztah** [comment]
@LK4D4 this PR fixes a panic, but it's not a regression in 1.12 (it was reported in an older version); for that reason I put it on the 1.13 milestone, but if you think it's important enough to include in a possible 1.12.2 release, let me know

**Comment by kouhin** [comment]
@thaJeztah I met this problem in our production environment. 
When high amount of requests came, it causes fluentd down =>  docker daemon / containers down => fluentd recovered => docker daemon / containers recovered => fluentd down again ... 

It's really a serious panic and I think it's very important to be included in a possible nearest release.

**Pull request merged**
