### PR TITLE
Rename Daemon.Destroy to Daemon.Rm to be consistent with CLI command.

### PR DESCRIPTION
**Pull request by gewoonrik**
Signed-off-by: Rik Nijessen riknijessen@gmail.com

Hi,

@MartijnDwars, @RickWieman, @wrvangeest and I are students from the Delft University of Technology in the Netherlands and are currently working on a project for our Software Architecture course (http://avandeursen.com/2013/12/30/teaching-software-architecture-with-github/).

During this course we will analyze the architecture an open-source project (in our case Docker, because we think Docker is awesome!). Our findings will be published in a chapter of a collaborative book, which will be published online. Last year's book can be found here http://delftswa2014.github.io/.

We'd love to contribute to Docker, so to get a little bit more familiar with the system we have fixed a simple FIXME.

We have renamed the Daemon.Destroy method to Daemon.Rm to be consistent with the corresponding CLI command.

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

Thanks!

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks! Looking forward to the book once it's published/available

**Comment by gewoonrik** [comment]
We'll let you know!

**Pull request merged**
