### PR TITLE
Remove sqlite

### LINKED ISSUE #22146: RFC: deprecate old graphdb migration / move to an external tool?
Just some thought; the mattn/go-sqlite3 package is a big vendored package, and only used [to migrate the legacy graphdb](https://github.com/docker/docker/blob/19a453e6b40177af31703f107131aae5ca81adf2/daemon/daemon.go#L321-L341) links (Docker 1.9 and older) to the new "runtime" links (https://github.com/docker/docker/pull/16032)

Should we;
- mark the option to migrate from 1.9 versions as "deprecated" (to be removed in 1.14)?
- move the migration to an external tool?

### PR DESCRIPTION
**Pull request by LK4D4**
fixes https://github.com/docker/docker/issues/22146
relates to https://github.com/moby/moby/pull/16032

**\- What I did**
Removed sqlite dependency.
**\- How I did it**
Removed every usage of graphdb.
**\- How to verify it**
Compile daemon
**\- Description for the changelog**

Dependency from sqlite removed, so links upgrade from 1.9 does not work. External migration tool should be used if necessary.

**\- A picture of a cute animal (not mandatory but encouraged)**
cat

I also wrote tool for migration: https://github.com/LK4D4/linksmigrator

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Shortly after we moved to Go 1.5, I looked into why compiles too so long. I found that a significant amount of the time was spent building sqlite. The Go compilation was parallelized, but the C compilation was not since sqlite is one big file.

Removing sqlite will probably have a beneficial impact on build times.

**Comment by aaronlehmann** [comment]
(That is, the time to build Docker, not the `build` subcommand.)

**Comment by justincormack** [comment]
I remember we discussed this before, and there was some reluctance, but
definitely worth discussing again...

**Comment by thaJeztah** [comment]
See this issue https://github.com/docker/docker/issues/22146

**Comment by thaJeztah** [comment]
ping @cpuguy83 ptal

**Comment by cpuguy83** [comment]
Oh man, major +1 here.
Thanks for writing the migration tool.

**Comment by thaJeztah** [comment]
oh! I miss the migration tool, that is really awesome! Would be great if we had that under the "docker" organization - but guess we won't be able to ship it as an image (like the v1.10 migration tool). FWIW, once we're in docs review, I think we should have it added to https://github.com/docker/docker/blob/master/docs/migration.md

**Comment by LK4D4** [comment]
@thaJeztah I think we can incorporate that to migrator tool.

**Comment by vdemeester** [comment]
I'm also definitely +1 on that :heart_eyes_cat:

**Comment by LK4D4** [comment]
@tonistiigi also pointed that we should notify people that they should run migration tool. Not sure how to make that behavior opt-out though.

**Comment by jhowardmsft** [comment]
Nice! @jstarks FYI

**Comment by LK4D4** [comment]
btw compile time goes from 50s to 40s on my machine without sqlite.

**Comment by cpuguy83** [comment]
I guess my only real concern is that there is still a large contingent of people running docker 1.9 due to build caching issues in >= 1.10.
How many of those people are using `--link` that would be affected by this?

**Comment by thaJeztah** [comment]
@cpuguy83 what do you think? Should we move this to 1.14? Or don't do it at all?

**Comment by thaJeztah** [comment]
@cpuguy83 or shall we document that people from 1.9 should always use 1.10, perhaps we should check if we document that we support upgrading and skipping versions?

**Comment by cpuguy83** [comment]
@thaJeztah Do people read docs before upgrading?
I'm just worried we are going to break people, especially when there are so many on 1.9 still.

**Comment by LK4D4** [comment]
@thaJeztah @cpuguy83 yeah, let's wait for a release with caching improvements, so people can upgrade. I'll close this for now.

**Comment by thaJeztah** [comment]
Thanks!

**Pull request closed without merging**
