### PR TITLE
Move api/client -> cli/command

### PR DESCRIPTION
**Pull request by dnephin**
The contents of this package are not really an api client. They are the command structs used to build the cli, and the functionality of the commands, so I've moved them into a package that I feel better suits the functionality.

``` sh
      gomvpkg \
         -from github.com/docker/docker/api/client \
         -to github.com/docker/docker/cli/command \
         -vcs_mv_cmd 'git mv {{.Src}} {{.Dst}}'
```

### CODE REVIEW

**Comment by dnephin** [comment]
oh, I guess it didn't get experimental , maybe missed windows as well

**Comment by vdemeester** [comment]
SGTM 🐸

**Comment by dnephin** [comment]
rebased and CI is green

**Comment by justincormack** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
