### PR TITLE
Update docker-py to 4d8e5eb2ada3dfbffd5721271c1c7c

### PR DESCRIPTION
**Pull request by crosbymichael**
closes https://github.com/moby/moby/pull/39239

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
kicked Janky because it failed before docker-py ran.

I had another PR to bump docker-py, but it was failing on some other tests; https://github.com/moby/moby/pull/39239

it's slightly behind this version though, so 🤞 https://github.com/docker/docker-py/compare/0f368939def31bfd44218f54a5eff0a599ab8139...4d8e5eb2ada3dfbffd5721271c1c7c

**Comment by thaJeztah** [comment]
looks like it's still failing (same failures as in my PR https://github.com/moby/moby/pull/39239)

**Comment by dmcgowan** [comment]
I don't think I understand the logic here. You can't add a new health check fix unless you add a health check test, but you can't add a health check test unless you also take the responsibility of porting ALL the health check tests to a new test framework?

**Comment by thaJeztah** [comment]
closing in favor of https://github.com/moby/moby/pull/39068, which was just merged (thanks!)

**Pull request closed without merging**
