### PR TITLE
Check the length of the correct variable #42039

### LINKED ISSUE #42039: ExtraAttributes checking the wrong length for labels-regex
**Description**

This line is checking the length of the wrong variable https://github.com/moby/moby/blob/master/daemon/logger/loginfo.go#L45 . This is likely a copy paste error, I assume `len(labels)` should be `len(labelsRegex)`. 

**Steps to reproduce the issue:**
1. Try to specify `labelsRegex` but not `labels` for a log driver and the regex you specified will be ignored.

**Describe the results you received:**
My labelsRegex is being ignored.

**Describe the results you expected:**
I'd expect to see the matching labels.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
not relevant
```

### PR DESCRIPTION
**Pull request by nathanlcarlson**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Closes #42039

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Looks like your commit message is missing a `signed-off-by` line; https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

If you have your name and e-mail configured in your git configuration (see https://github.com/moby/moby/blob/master/docs/contributing/set-up-git.md#task-2-set-your-signature-and-an-upstream-remote)

You can amend your commit, and force-push to update the PR; assuming the remote pointing to your fork is named `origin`;


```
git commit -s --amend --no-edit
git push -f origin
```

Let me know if you need help 👍

**Comment by nathanlcarlson** [comment]
Got it signed.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

thanks!!

**Comment by thaJeztah** [comment]
CI failure is unrelated

**Pull request merged**
