### PR TITLE
Add warning log when high priority graphdriver used before

### PR DESCRIPTION
**Pull request by crosbymichael**
This is a carry of #9184

Closes #9184
Fixes #8270

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

Tested by doing: `docker -d -s devicemapper`, ^C, `docker -d`.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
drone is failing bc hub is down

**Comment by crosbymichael** [comment]
I'll merge after we can verify with drone

**Pull request merged**
