### PR TITLE
Fix liverestore/restartmanager conflict in v1.12

### LINKED ISSUE #29598: dockerd crash with nil pointer error
**Description**
Docker daemon 1.12.4 crashed with nil pointer error

**Steps to reproduce the issue:**
Running on ubuntu 16.04 on AWS on x1.32xlarge

**Describe the results you received:**
```
Dec 20 14:33:47 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:33:47.456073207Z" level=info msg="Container 1e494db42a1cf22d4ba72f73201bc8791192166eb73d6c536e92fa37c9b1ac05 failed to exit within 10 seconds of signal 15 - using the force"
Dec 20 14:33:47 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:33:47.767456469Z" level=warning msg="libcontainerd: container 1e494db42a1cf22d4ba72f73201bc8791192166eb73d6c536e92fa37c9b1ac05 restart canceled"
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:34:04.776606196Z" level=error msg="failed to close stdin: rpc error: code = 2 desc = containerd: container not found"
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:34:04.880619893Z" level=error msg="Handler for GET /v1.24/exec/7456091f2e588e028b90c4dc16b32b72f6141b206845733e99dad543b348520b/json returned error: Container 529b294762d5692a7419166ddfe9433321d793d72d3a2d441f0125057064f048 is restarting, wait until the container is running"
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: [signal 0xb code=0x1 addr=0x0 pc=0x601668]
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: goroutine 35252 [running]:
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: panic(0x1aa2760, 0xc82000c090)
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/local/go/src/runtime/panic.go:481 +0x3e6
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: github.com/docker/docker/libcontainerd.(*container).start(0xc821093140, 0x0, 0x0, 0x0)
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:143 +0x708
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: github.com/docker/docker/libcontainerd.(*container).handleEvent.func1.1(0xc8260d2900, 0xc821093140, 0xc828b20ff0, 0xc8281d29c0)
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:227 +0x11a
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: created by github.com/docker/docker/libcontainerd.(*container).handleEvent.func1
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:243 +0x226
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Never happened with 1.12.3

**Output of `docker version`:**

```
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 430
 Running: 358
 Paused: 0
 Stopped: 72
Images: 1328
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /opt/io1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3794
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 128
Total Memory: 1.876 TiB
Name: ip-10-69-11-89
ID: UGZS:UFD3:GB4C:W5MX:JU2L:K7PH:6ZWS:4GPM:27Q5:UNNN:X3DC:YDT7
Docker Root Dir: /opt/io1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #29598

@mlaventure

### CODE REVIEW

**Comment by mlaventure** [comment]
LGTM

**Comment by cpuguy83** [comment]
The added test is not failing for me on 1.12.x head

**Comment by tonistiigi** [comment]
@cpuguy83 That's strange

```
+ go test -check.v -check.f TestRestartPolicyWithLiveRestore -check.v -check.timeout=5m -test.timeout=360m github.com/docker/docker/integration-cli
INFO: Testing against a local daemon

----------------------------------------------------------------------
FAIL: docker_cli_daemon_test.go:2722: DockerDaemonSuite.TestRestartPolicyWithLiveRestore

[d69675217] waiting for daemon to start
[d69675217] daemon started
[d69675217] exiting daemon
[d69675217] waiting for daemon to start
[d69675217] daemon started
docker_cli_daemon_test.go:2741:
    c.Assert(s.d.waitRun(id), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"error executing docker inspect: exit status 1\n\nCannot connect to the Docker daemon. Is the docker daemon running on this host?\n"} ("error executing docker inspect: exit status 1\n\nCannot connect to the Docker daemon. Is the docker daemon running on this host?\n")

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (2.02s)
FAIL
coverage: 17.0% of statements
```

Maybe the sleep constant is too small?

**Comment by cpuguy83** [comment]
Yes maybe.
I just now got it to pass 1 out of 3 times.

**Comment by mlaventure** [comment]
Should we raise the timeout to a second in both this PR and #29739?

**Comment by tonistiigi** [comment]
@cpuguy83 Can you check if the timeout value is the problem as I have no way to confirm that.

**Comment by cpuguy83** [comment]
This seems to fix it for me:


```go
	ticker := time.NewTicker(50 * time.Millisecond)
	timeout := time.After(10 * time.Second)

	for range ticker.C {
		select {
		case <-timeout:
			c.Fatal("timeout waiting for container restart")
		default:
		}

		out, err := s.d.inspectFilter(id, "json .State")
		c.Assert(err, checker.IsNil, check.Commentf(out))

		var newState state
		err = json.Unmarshal([]byte(strings.TrimSpace(out)), &newState)
		c.Assert(err, checker.IsNil)

		if !newState.Running {
			continue
		}
		if newState.StartedAt.After(origState.StartedAt) {
			break
		}
	}
```

**Comment by cpuguy83** [comment]
Sorry, here's the full diff from 1.12
```go
diff --git a/integration-cli/docker_cli_daemon_test.go b/integration-cli/docker_cli_daemon_test.go
index 7508f9f..e72370d 100644
--- a/integration-cli/docker_cli_daemon_test.go
+++ b/integration-cli/docker_cli_daemon_test.go
@@ -2717,3 +2717,59 @@ func (s *DockerDaemonSuite) TestRunWithRuntimeFromCommandLine(c *check.C) {
 	out, err = s.d.Cmd("run", "--rm", "--runtime=runc", "busybox", "ls")
 	c.Assert(err, check.IsNil, check.Commentf(out))
 }
+
+func (s *DockerDaemonSuite) TestRestartPolicyWithLiveRestore(c *check.C) {
+	testRequires(c, DaemonIsLinux)
+	c.Assert(s.d.StartWithBusybox("--live-restore"), check.IsNil)
+
+	out, err := s.d.Cmd("run", "-d", "--restart", "always", "busybox", "top")
+	c.Assert(err, check.IsNil, check.Commentf("Output: %s", out))
+	id := strings.TrimSpace(out)
+
+	type state struct {
+		Running   bool
+		StartedAt time.Time
+	}
+	out, err = s.d.inspectFilter(id, "json .State")
+	c.Assert(err, checker.IsNil, check.Commentf(out))
+
+	var origState state
+	err = json.Unmarshal([]byte(strings.TrimSpace(out)), &origState)
+	c.Assert(err, checker.IsNil)
+
+	c.Assert(s.d.Restart("--live-restore"), check.IsNil)
+
+	c.Assert(s.d.waitRun(id), check.IsNil)
+
+	pid, err := s.d.Cmd("inspect", "-f", "{{.State.Pid}}", id)
+	c.Assert(err, check.IsNil)
+	pidint, err := strconv.Atoi(strings.TrimSpace(pid))
+	c.Assert(err, check.IsNil)
+	c.Assert(syscall.Kill(pidint, syscall.SIGKILL), check.IsNil)
+
+	ticker := time.NewTicker(50 * time.Millisecond)
+	timeout := time.After(10 * time.Second)
+
+	for range ticker.C {
+		select {
+		case <-timeout:
+			c.Fatal("timeout waiting for container restart")
+		default:
+		}
+
+		out, err := s.d.inspectFilter(id, "json .State")
+		c.Assert(err, checker.IsNil, check.Commentf(out))
+
+		var newState state
+		err = json.Unmarshal([]byte(strings.TrimSpace(out)), &newState)
+		c.Assert(err, checker.IsNil)
+
+		if !newState.Running {
+			continue
+		}
+		if newState.StartedAt.After(origState.StartedAt) {
+			break
+		}
+
+	}
+}
```

**Comment by tonistiigi** [comment]
Unfortunately, it turns out that there is a separate networking issue that causes the restartmanager to still not work properly. It has been fixed in `v1.13` and backporting it would be too big of a change for `v1.12`. So this PR only fixes the panic case. As it is not possible to test for the functionality I've modified the test to just wait for the daemon not to crash for 5 seconds. #29739 has the proper testcase for master branch that actually checks the functionality and doesn't use sleep constant.

PTAL @cpuguy83 @mlaventure

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by mlaventure** [comment]
LGTM

@cpuguy83 RS1 CI won't work with 1.12.x :)

**Comment by cpuguy83** [comment]
Ah, of course!

**Pull request merged**
