### PR TITLE
11558 - Documentation fixes and improvements for Riak Dockerfile

### LINKED ISSUE #11558: Test the Dockerizing a Riak Service example
Test the example and ensure it works as documented. File any issues a `writing` issues.

http://docs.docker.com/examples/running_riak_service/

### PR DESCRIPTION
**Pull request by dekobon**
Fixes https://github.com/docker/docker/issues/11558

After testing the documentation in https://github.com/docker/docker/issues/11558 and finding that it no longer worked for updated Riak instances, I wrote new documentation and a new Dockerfile.

Please review and if you find it acceptable - merge.

I just realized that I didn't sign all of my commits with:

Signed-off-by: Elijah Zupancic elijah@zupancic.name

Please accept this pull request as signed for all bundled commits.

### CODE REVIEW

**Comment by rrarunan** [comment]
@dekobon Can you please also add a `closes` or `fixes` keyword so its easy to track the fix? Thanks!

**Comment by dekobon** [comment]
Attempt #2 with signed commits.

**Comment by dekobon** [comment]
@rrarunan How do I resubmit the pull request to the build server?

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
LGTM

**Pull request merged**
