### PR TITLE
bump libnetwork to 5ab4ab830062fe8a30a44b75b0bda6b1f4f166a4

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/docker/libnetwork/compare/fcf1c3b5e57833aaaa756ae3c4140ea54da00319...5ab4ab830062fe8a30a44b75b0bda6b1f4f166a4

includes:

- https://github.com/docker/libnetwork/pull/2010 - Fix to use ContainerID for windows instead of SanbdoxID

### CODE REVIEW

**Comment by thaJeztah** [comment]
First two commits are actually already in https://github.com/moby/moby/pull/36004, so I can rebase after that one is merged

ping @fcrisciani @cpuguy83

**Comment by thaJeztah** [comment]
Rebased

**Comment by fcrisciani** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @pradipd @johnstep as well

**Comment by pradipd** [comment]
ping @madhanrm as well

**Comment by madhanrm** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by johnstep — APPROVED** [review]
LGTM

**Pull request merged**
