### PR TITLE
No need for the old project/ROADMAP.md

### PR DESCRIPTION
**Pull request by estesp**
Now that we have ROADMAP.md in the root of the project, the outdated and
non-specific ROADMAP.md in project/ can be removed.

Docker-DCO-1.1-Signed-off-by: Phil Estes estesp@linux.vnet.ibm.com (github: estesp)

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
did anything link to this i wonder, did you do a grep

**Comment by estesp** [comment]
There wasn't a link, but the filename was mentioned in `project/README.md` without any context of where it might be, so I added a GitHub relative link to the (new) root directory-located ROADMAP.md.

**Comment by jfrazelle** [comment]
cool

**Pull request merged**
