### PR TITLE
Remove "appropriate/nc" image from integration test

### PR DESCRIPTION
**Pull request by thaJeztah**
The image used is 3rd party, and hasn't been updated
in over two years. Replacing with a plain Alpine image,
and manually installing the software.

relates to https://github.com/moby/moby/pull/32505#discussion_r136242314

ping @fcrisciani @seemethere @vieux 

(let's see if this works :smile:)

### CODE REVIEW

**Comment by dnephin** [comment]
I think the correct fix here is to delete this test. This is not the appropriate place to be testing this behaviour. Looking at #32505 (the PR which introduced this test) the only change was to update vendor. This case should be tested in libnetwork.

**Comment by thaJeztah** [comment]
Doesn't seem to work as well; already had my doubt because I suspect there will be a race due to the time it takes for the package to be installed (didn't want to build an image first)

**Comment by fcrisciani** [comment]
@dnephin libnetwork does not have the infra to create tests using the moby code, so this was the best way to have coverage for this case.

**Comment by dnephin** [comment]
The fix did not change any moby code (only vendor), so I don't see why the moby code would be required to test this case.

**Comment by fcrisciani** [comment]
@dnephin does not change anything because the code that handle the container disconnection from a network is already there

**Comment by dnephin** [comment]
My point is that the test should exercise the bug. If the bug was fixed without touching the moby code, then it must be possible to exercise the bug (and the fix) without the moby code.

**Comment by fcrisciani** [comment]
@dnephin true but the real use case that we want to cover is a container that create flows during itsl lifecycle and once destroyed has to cleanup its status.
The netlink primitives are already covered by unit tests in the repo of the library: https://github.com/vishvananda/netlink/pull/213/commits/2d3d0f81ae7eb890852279c354efe3251287b82b
The test that we can create in libnetwork today would be farther from what is being created here that is pretty close from the actual real use.

**Comment by dnephin** [comment]
> The test that we can create in libnetwork today would be farther from what is being created here 

Why can't we create a test that makes the same libnetwork API calls as you'd expect from container create/remove? That should exercise the bug.

**Comment by fcrisciani** [comment]
@dnephin you still need to create a network namespace to simulate a container and create flow inside it that subsequently are going to be flushed. But at the same time you will have to use the same contract that moby is sharing with libnetwork so fake endpoints etc etc.

**Comment by dnephin** [comment]
If libnetwork can't be tested in isolation I think that suggests a problem with the interface or the design of the library. There's no reason that a library should be tested from a consumer of the library.

I still think we should remove this test.

**Comment by fcrisciani** [comment]
As I said at the beginning, it's not that is impossible there is only a lack of infra at the moment

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
👍 to removing this test

**Comment by vdemeester** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
Let me close this for now; as I didn't have time to look at fixing this approach, and there's no other infra (yet) to test this in libnetwork directly

**Pull request closed without merging**
