### PR TITLE
Mount rootfs PRIVATE but volume mounts shared

### PR DESCRIPTION
**Pull request by rhatdan**
Currently we are remounting the entire OS as PRIVATE which breaks
shared volume mounts.  This patch only mounts the rootfs as PRIVATE
which allows the volume mounts to be shared.

Docker-DCO-1.1-Signed-off-by: Dan Walsh dwalsh@redhat.com (github: rhatdan)

### CODE REVIEW

**Comment by estesp** [comment]
The libcontainer changes need to go over as a PR in **docker/libcontainer** repo and then the other change can be PR'ed here after libcontainer gets updated.

**Comment by rhatdan** [comment]
I just want to setup a discussion of this based on this pull request.  To see if this fixes the problem @crosbymichael   Then I will take it through proper channels.

https://github.com/docker/docker/pull/13854

**Comment by crosbymichael** [comment]
There are so many of these PRs about this issue open and now one really knows what is going on or what the use cases are.  From what I can gather you are running a container with a volume, and then mounting things inside that volume.  Am I correct?

**Comment by rhatdan** [comment]
@crosbymichael Who are you directing the question at?  If me the answer is yes.  I want to mount
/home into a container and have autofs work.  Or I want to mount /var/lib/foobar and have other process mount content into the mount point that my container could then work on.  Or I want to allow a SPC container to be able to mount content onto the host OS.

**Comment by mrjana** [comment]
+1 on the design and on the use case it's trying to solve

**Comment by icecrime** [comment]
Duplicate of #14097.

**Pull request closed without merging**
