### PR TITLE
LCOW: VHDX boot to readonly.

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Fixes internal VSO bug 12969254. Makes the VHDX boot read-only to avoid file sharing violation running 2nd container.  @beweedon, @jstarks @patricklang  FYI.

@johnstep PTAL.

### CODE REVIEW

**Review by johnstep — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
I think the PR makes sense. LGTM if Jenkins passes.

**Comment by jhowardmsft** [comment]
Jenkins & GH are out-of-sync. RS1 completed successfully here: https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/16941/console

OK to merge?

**Comment by yongtang** [comment]
All test passes now. Thanks! 👍

**Pull request merged**
