### PR TITLE
vendor: bump libcontainer to 3317785f562b363eb386a2fa4909a55f267088c8

### PR DESCRIPTION
**Pull request by runcom**
I honestly don't know why blanks are seen in the diff....

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
this also allows to cross-compile #17021 (with a patch to that PR as well)

**Comment by LK4D4** [comment]
@runcom let's collect some more changes for next version of libcontainer. You can just revendor stuff now to put everything in place.

**Comment by runcom** [comment]
@LK4D4 fine :)

**Comment by tiborvass** [comment]
@runcom so can we temporarily close this?

**Comment by runcom** [comment]
@tiborvass I think so..

**Pull request closed without merging**
