### PR TITLE
actually depreciate -rm insteam of --rm.. and a few others

### PR DESCRIPTION
**Pull request by jessfraz**
seriously its been forever

should it stay forever.... bleh no

### CODE REVIEW

**Comment by jfrazelle** [comment]
can i do name too or is that overkill

**Comment by LK4D4** [comment]
Forgot to write comment :)
I'm +1 for any deprecations.

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
ping @tiborvass

**Comment by jfrazelle** [comment]
ping @icecrime :angel:

**Comment by calavera** [comment]
:fire: LGTM :fire:

**Comment by icecrime** [comment]
LGTM :smiling_imp:

**Comment by icecrime** [comment]
I looked around: I can't find any docs impact.

**Pull request merged**
