### PR TITLE
Remove blanket "supported" language.

### PR DESCRIPTION
**Pull request by psftw**
Signed-off-by: Peter Salvatore peter@psftw.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
@psftw Thanks for the quick response Peter. LGTM

ping @docker/docs-owners

**Comment by thaJeztah** [comment]
LGTM. Thanks!

**Comment by thaJeztah** [comment]
ping @moxiegirl (if you were waiting for this to publish)

**Comment by moxiegirl** [comment]
thanks @thaJeztah  I was!

**Pull request merged**
