### PR TITLE
make engine support cluster config event

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

I found that docker-ce 17.06.0-ce has already supported cluster events, such as node, service, secret and so on. While I think there is still config events missing.

ping @dongluochen @aaronlehmann 

**- What I did**
1. make engine support cluster config event
2. add a test case for config event
3. update swagger.yml to add configs event

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by allencloud** [comment]
I think both the CI failure is unrelated, and could anyone help to re-trigger them? @cpuguy83 @vdemeester

**Comment by vieux** [comment]
LGTM ping @aaronlehmann @aluzzardi

**Comment by allencloud** [comment]
Since this change will affect the event,  I think swagger.yml needs updated. And I hope to add this in PR https://github.com/moby/moby/pull/34035. Because there are more things missing related to cluster events.
Please remind me if I miss something. @thaJeztah

**Comment by allencloud** [comment]
Since https://github.com/moby/moby/pull/34035 has been merged, I started to add doc update for config events in swagger.yml. PTAL @aaronlehmann @thaJeztah

**Comment by aaronlehmann** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
oh, actually; can you add a line to https://github.com/moby/moby/blob/master/docs/api/version-history.md ?

**Comment by thaJeztah** [comment]
hmm, flakiness? https://jenkins.dockerproject.org/job/Docker-PRs-experimental/35595/console

```
10:27:50 ----------------------------------------------------------------------
10:27:50 FAIL: docker_api_swarm_test.go:281: DockerSwarmSuite.TestAPISwarmLeaderElection
10:27:50 
10:27:50 [d44619f297605] waiting for daemon to start
10:27:50 [d44619f297605] daemon started
10:27:50 
10:27:50 [d2a7f9c3887d5] waiting for daemon to start
10:27:50 [d2a7f9c3887d5] daemon started
10:27:50 
10:27:50 [d7c4c91a9d93d] waiting for daemon to start
10:27:50 [d7c4c91a9d93d] daemon started
10:27:50 
10:27:50 [d44619f297605] exiting daemon
10:27:50 [d44619f297605] waiting for daemon to start
10:27:50 [d44619f297605] daemon started
10:27:50 
10:27:50 docker_api_swarm_test.go:341:
10:27:50     // and that after we added d1 back, the leader hasn't changed
10:27:50     c.Assert(leader.NodeID, checker.Equals, stableleader.NodeID)
10:27:50 ... obtained string = "40kbahq4jhfxfsevo4kfzavjl"
10:27:50 ... expected string = "acz541uxpwsb9820dwu6b8qt5"
10:27:50 
10:27:50 [d44619f297605] exiting daemon
10:27:50 [d2a7f9c3887d5] exiting daemon
10:27:50 [d7c4c91a9d93d] exiting daemon
10:28:25 
```

**Comment by allencloud** [comment]
Oh, I missed version_history.md. @thaJeztah 
In this PR, I will add version change of config events in api version 1.31.
However, I also find that service, node and secret events are also missing in api version 1.30. 
And I will do a follow-up to add these.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by allencloud** [comment]
Oh, it is great to see all green, since recently we have experienced lot of test failure. 😄

**Comment by thaJeztah** [comment]
> Oh, it is great to see all green, since recently we have experienced lot of test failure

This PR should resolve some of the test failures / flakyness we saw; https://github.com/moby/moby/pull/34061

**Comment by thaJeztah** [comment]
And, yes, all green 💚 Thanks!

**Pull request merged**
