### PR TITLE
Fix the typo url and info

### PR DESCRIPTION
**Pull request by HackToday**
Some info is not consistent between context and word.

Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
ping @thaJeztah  :)

**Comment by HackToday** [comment]
also @nerdalert

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by coolljt0725** [comment]
LGTM

**Comment by nerdalert** [comment]
LGTM Thanks!

**Pull request merged**
