### PR TITLE
Add zsh completion for 'docker ps --filter=network'

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #23300

@albers thx for the ping
@vincentbernat 
Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vincentbernat** [comment]
LGTM

**Comment by thaJeztah** [comment]
nice! thanks! LGTM

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by vdemeester** [comment]
LGTM 🐮

**Pull request merged**
