### PR TITLE
Readme grammer fix

### PR DESCRIPTION
**Pull request by jonisar**
"Giving THE developer...." -> "to express all THEIR application's.."
A developer is single so it can't be followed by "their" which refers to plural (developers).

So, adjusted to plural ("developers") so that the two will match.
 * The alternative would be to use "the developer....his / her application's" but that leads to gender reference issues, so the former alternative works better

**- What I did**
Changed "the developer" to "developers"

**- How I did it**
Plural / singular matching with gender consideration

**- How to verify it**
http://www.ef.com/english-resources/english-grammar/singular-and-plural-nouns/
**- Description for the changelog**
 Changed "the developer" to "developers" to match plural / singular grammer

**- A picture of a cute animal (not mandatory but encouraged)**
https://s-media-cache-ak0.pinimg.com/originals/1a/f3/37/1af33760a821e18bb6e7bd3457c55aa2.jpg
Wierd, but cute :)

Signed-off-by: Jonathan Saring (Joni Sar) <yoni@cocycles.com>

### CODE REVIEW

**Comment by jonisar** [comment]
K added manually to the above

**Comment by unclejack** [comment]
Thank you for sending the PR.

`Their` is used to be gender neutral, not as a plural. Please take a look at https://en.wikipedia.org/wiki/Singular_they

**Comment by thaJeztah** [comment]
Yes, the original version is correct; but I'm not against changing because both works in this context.

The sign off needs to be fixed though, otherwise CI keeps failing

**Comment by jonisar** [comment]
Yes you are right - however "their" refers to plural.
The problem is "the developer" is the singular form of the word developer.
So "the developer" can't be followed by "their". That is why it should be changed to "developers".

**Comment by vdemeester** [comment]
ping @jonisar : could you sign-off your commit 👼 🙏 ?

**Comment by jonisar** [comment]
Jenkins failed?

**Review by thaJeztah — APPROVED** [review]
LGTM

test failures are not related, but ping @vdemeester in case there's some of those we need to look at in general

**Review by vdemeester — APPROVED** [review]
LGTM 🐯 
I think failure we already know this failures 👼

**Pull request merged**
