### PR TITLE
awslogs: Update aws-sdk-go to support IMDSv2

### LINKED ISSUE #40422: Enable support for AWS imdsv2 by upgrading aws-sdk version
**Description**

Hi,

In November 2019 AWS announced their "version 2" of the metadata service, to protect users against SSRF attacks leading to credential compromises:
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

Amazon updated all of their SDKs to make this transparent to users.

However, I'm unable to opt into this protection because the docker awslogs driver is running an old version of the aws-sdk. I'd like to request that the awslogs driver be updated to use any version of the aws-sdk 1.25.38 or higher, which is when support was added:
https://github.com/aws/aws-sdk-go/releases/tag/v1.25.38

More details on this issue: https://github.com/aws/containers-roadmap/issues/670

Thanks very much!

### PR DESCRIPTION
**Pull request by samuelkarp**
**- What I did**
AWS recently launched a new version of the EC2 Instance Metadata Service, which is used to provide credentials to the awslogs driver when running on Amazon EC2.  This new version of the IMDS adds defense-in-depth mechanisms against open firewalls, reverse proxies, and SSRF vulnerabilities and is generally an improvement over the previous version.  An updated version of the AWS SDK is able to handle the both the previous version and the new version of the IMDS and functions when either is enabled.

More information about IMDSv2 is available at the following links:

* https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

Closes https://github.com/moby/moby/issues/40422

**- How I did it**
* Updated the dependency on github.com/aws/aws-sdk/go
* Updated the transitive dependency on github.com/jmespath/go-jmespath
* Removed unused dependency github.com/go-ini/ini

**- How to verify it**
1. Run an EC2 instance with IMDSv1 disabled.  This can be set at launch time via a parameter to the RunInstances API, or can be set after an instance has already launched via the ModifyInstanceMetadataOptions API.
1. Ensure that the instance has an IAM profile allowing it to write to CloudWatch Logs.
1. Install this updated version of Docker
1. Run a container with the `awslogs` driver and ensure that it writes to CloudWatch Logs successfully

**- Description for the changelog**

awslogs: Update aws-sdk-go to support IMDSv2

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
@samuelkarp Does this introduce user-facing changes? (new log-driver options to be documented in https://github.com/docker/docker.github.io/blob/629a147a65494cee7172072889dfffebc46071d2/config/containers/logging/awslogs.md)?

**Comment by samuelkarp** [comment]
@thaJeztah There are no new log-driver options.  This change makes automatic credential retrieval on EC2 work in more situations, without requiring the user to do anything.  The existing Credentials section of that doc is not very detailed; unless we want to rewrite it entirely I don't believe it needs to be updated.

**Comment by thaJeztah** [comment]
Great, thanks!

**Pull request merged**
