### PR TITLE
Windows: make.ps1 fix DCO check

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Fixes the DCO checkout as per https://github.com/docker/docker/pull/29229#issuecomment-265627433. .pngs for example show as `-` for lines added/deleted rather than numbers. 

@vieux

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@friism

**Comment by friism** [comment]
+1, thanks John!

**Review by johnstep — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐻

**Pull request merged**
