### PR TITLE
image/cache: fix isValidParent logic

### PR DESCRIPTION
**Pull request by runcom**
Fix https://github.com/docker/docker/issues/31186

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
I'll add a test asap, in the middle of something else now.

**Comment by tonistiigi** [comment]
LGTM, but needs a test

**Comment by runcom** [comment]
Yes, as noted above, I'll need to add one.

**Comment by aaronlehmann** [comment]
I think `isValidParent` should be renamed, since it's no longer checking for a parent/child relationship.

**Comment by runcom** [comment]
> I think isValidParent should be renamed, since it's no longer checking for a parent/child relationship.

I'll add another commit to change that or follow up (do you have any suggestion on the new name?)

**Comment by aaronlehmann** [comment]
> I'll add another commit to change that or follow up (do you have any suggestion on the new name?)

Actually, I might have misunderstood the fix.

I see that `isValidParent` still checks `if len(parent.History) >= len(img.History) {` (not `>`).

So it seems like it still is checking for a parent, but you fixed a problem that happens if the parent has the same number of filesystem layers. If this is the case, the name doesn't need to change.

LGTM

**Review by tonistiigi — APPROVED** [review]

**Review by LK4D4 — APPROVED** [review]
LGTM

**Pull request merged**
