### PR TITLE
fix infinite recursion

### PR DESCRIPTION
**Pull request by felipeweb**
**- What I did**
remove a infinite recursion  in PingResponseError`s  Error method.
**- How I did it**
Calling a field's Error method
**- Description for the changelog**
Fix PingResponseError infinite recursion

Signed-off-by: Felipe Oliveira <felipeweb.programador@gmail.com>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by duglin** [comment]
I'm a bit confused, why is this recursive?
I don't see it in:
```
package main

import "fmt"

type myerr struct {
    err error
}

func (e myerr) Error() string {
    return e.err.Error()
}

func main() {
    err := myerr{err: fmt.Errorf("hello")}
    fmt.Printf("Err: %q\n", err.Error())
}
```

**Comment by cpuguy83** [comment]
@duglin `err.Error()` is calling itself.

**Comment by cpuguy83** [comment]
In your version, there is no recursion because you are calling `e.err.Error()`

**Comment by duglin** [comment]
ah doit - missed that - thanks!

**Comment by duglin** [comment]
LGTM once janky is ok

**Pull request merged**
