### PR TITLE
Proposal: Registry v2 authorization service

### PR DESCRIPTION
**Pull request by jlhawn**
Outlines usage for endpoints which will be used by the
docker registry client for registry v2 non-standalone.

Docker-DCO-1.1-Signed-off-by: Josh Hawn josh.hawn@docker.com (github: jlhawn)

### CODE REVIEW

**Comment by t5unamie** [comment]
Do you know when this will be included into a stable release of docker?

**Comment by jfrazelle** [comment]
@jlhawn do we need these docs now that #9784 is in?

**Comment by mmdriley** [comment]
Why was the implementation checked in before the spec?

**Comment by dmp42** [comment]
@mmdriley it's not clear yet what the process should be to merge such proposals (eg: before or after implementation) - for example: should documentation be merged before a feature lands?
Either way, this should be merged indeed.

**Comment by SvenDowideit** [comment]
@dmp42 generally the documentation and the code should to be merged at the same time. In 1.6, We'd like to make this simpler, by moving the registry documentation into the registry repository, and importing it into the docs from there.

**Comment by jlhawn** [comment]
@jfrazelle @icecrime do you think it's best to move this to the https://github.com/docker/distribution repo? It may be more relevant here: https://github.com/docker/distribution/tree/master/auth/token

**Comment by jfrazelle** [comment]
yep that makes sense :)

**Comment by dmp42** [comment]
@jlhawn +1

**Comment by jlhawn** [comment]
Reopened as https://github.com/docker/distribution/pull/110

**Pull request closed without merging**
