### PR TITLE
Add a "Created" state for new containers that haven't been run yet

### LINKED ISSUE #13353: Non-started containers should not be treated as exited
If I use `docker create` to create a container, then `docker ps -a -f status=exited` shows that container.

This is conceptually problematic because the container was never started, hence it cannot ever have truly "exited.". It's a practical problem too, because it means that such a container is removed by `docker rm $(docker ps -aq -f status=exited)` performed as part of routine hygiene.

As a result of this, I'm forced to run something in a container whose sole purpose is to host shared data for other containers - or give up using an otherwise harmless hygiene step.

It would seem that some other status, e.g. "created", would be preferable for a created container that has not yet been started. Unfortunately, this proposed change could be a breaking change, so it may be dead on arrival.

### PR DESCRIPTION
**Pull request by duglin**
Closes #13353

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice!

@moxiegirl keep an eye on this one, because the state diagram in https://github.com/docker/docker/issues/12164 will need to be updated if this gets merged

**Comment by duglin** [comment]
Added a few more variants to the testcase just to be really anal.
And rebased.

**Comment by thaJeztah** [comment]
Do we need to test if `docker rm <createdcontainer>` works? I don't know (haven't checked) if rm tests the state before deleting

**Comment by duglin** [comment]
@thaJeztah I couldn't find one but I'll add it under a different PR since I think that's a different enough topic.

**Comment by thaJeztah** [comment]
> since I think that's a different enough topic.

It "felt" like the same topic, because a new state is introduced here, if would be a regression if `docker create`, then `docker rm` would no longer work.

(I noticed that none of the tests in [`docker_cli_rm_test`](https://github.com/docker/docker/blob/5a6db4fd44c0e05c8b185174a9aa380c9cc4f719/integration-cli/docker_cli_rm_test.go) are performed on a "created" container, all seem to be using "docker run")

**Comment by duglin** [comment]
My "same topic" thought process was... should the new tests go in irrespective of this PR?  Meaning, if this PR were killed would we still want those tests?  I think so.  You never know which PR might set off a firestorm of bike-shedding  :-)

**Comment by thaJeztah** [comment]
> My "same topic" thought process was... should the new tests go in irrespective of this PR? Meaning, if this PR were killed would we still want those tests? I think so.

I soooo mis-interpreted that your first comment. Yes, I fully agree (and noticed you created the PR for that as well) :)

**Comment by duglin** [comment]
ping @LK4D4 @crosbymichael @jfrazelle

**Comment by calavera** [comment]
Design looks good to me. Moved to code review, which LGTM too.

**Comment by thaJeztah** [comment]
LGTM, I don't think the docs currently mention container states other than the filter flags, so that LGTM too. (And my earlier comment https://github.com/docker/docker/pull/13367#issuecomment-104063004)

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Just thought of something; I think this needs a short note for people that expect the old behavior, and **do** expect those containers to have status `exited` in cleanup scripts (see the related use case https://github.com/docker/docker/issues/13353#issue-78562138)

Sorry, wanted to have this merged too, but think it should be added. I'll move to docs review, will have a look for where that note can be added.

**Comment by SvenDowideit** [comment]
nice catch

**Comment by thaJeztah** [comment]
@SvenDowideit if you have a suggestion on where to put that note, feel free to add here, as I'm tied up a bit right now :smile:

**Comment by thaJeztah** [comment]
The diagram I referred to is about to be merged as well in https://github.com/docker/docker/pull/13427

**Comment by moxiegirl** [comment]
@duglin If you want to take a look at the diagram and the doc I merged, I can update it. Or I can send you the SVG or GLIFFY file and you can do it.  Duglin's choice.

**Comment by duglin** [comment]
@moxiegirl sure - send me the image or a link to it.  thanks.

**Comment by thaJeztah** [comment]
@duglin it's part of https://github.com/docker/docker/pull/13427 (it's a JSON file)

**Comment by duglin** [comment]
If you mean docs/sources/reference/api/images/event_state.png then where is the "Created" state?

**Comment by moxiegirl** [comment]
@duglin We probably need to add it.  If you want to mark where it goes, here is an svg file  https://gist.github.com/moxiegirl/0d07ef0589a04f2421c4 

or just email me a marked up copy of the png --- or you can maybe talk me through adding it

**Comment by duglin** [comment]
@moxiegirl 
right now on the "docker-create" flow, it goes to a "create" box and then to the "stopped" state. I think all you need to do is add a "created" circle/state that's a sibling to the "stopped" circle/state.  All outbound actions from the "created" state should be the same as the "stopped" state (rm, start).  But there should only be the one inbound action, "create".

**Comment by moxiegirl** [comment]
@duglin is this what you mean?
event_state 1

**Comment by duglin** [comment]
@moxiegirl 
(xx) == xx circle/state
[xx] == xx box/action

Don't change the "docker run" flow. You didn't have that going through any states/circles until it got to (running), which I assume is correct. So, it should be what you had before:
  "docker run"->[create]->[start]->(running)
The "docker create" flow looks right ( "docker create"->[create]->(created) ), but remove all incoming arrows/flows on (created) except for the one from [create].  There's no way to get to this state except via the [create] action. The outbound arrows/flows from (created) should be the same as (stopped), which means remove the arrow from (created) to (stopped), there is no action to do that. The only outbound arrows/flows from (created) should be whatever you had before on (stopped), meaning "docker start" and "docker rm".
Also (Created) should be (created) to match the other states.

**Comment by moxiegirl** [comment]
@duglin Thanks for the info. Here is it revised. Did I go too far with stopped? Is there a way to get to start from here?

event_state

**Comment by duglin** [comment]
@moxiegirl looks good. I think the only think missing is the line from (stopped) to [start] via a "docker start", like you have from (created).

**Comment by moxiegirl** [comment]
This should do it.

event_state

**Comment by duglin** [comment]
@moxiegirl I only checked the (created) and (stopped) areas but they look correct.  Thanks!

**Comment by moxiegirl** [comment]
Cool. I'll merge it when this ticket closes.

**Comment by duglin** [comment]
any other doc review comments?

**Comment by thaJeztah** [comment]
Oh, I still had https://github.com/docker/docker/pull/13367#issuecomment-104541872. Haven't given it a proper thought yet (where to put a note). Just release notes? Docker Create in cli.md?

Sorry, bit lagging :blush:

**Comment by moxiegirl** [comment]
LGTM

**Comment by jfrazelle** [comment]
oh man needs rebase

**Comment by duglin** [comment]
rebased

**Comment by cpuguy83** [comment]
Is this ready to merge?

**Comment by duglin** [comment]
not sure if @thaJeztah was planning on proposing some additional docs edits...

**Comment by thaJeztah** [comment]
@duglin will make a suggestion later on, think I had something written up already :smile:

**Comment by thaJeztah** [comment]
@duglin I'm thinking something along the lines below. Assuming this will be in docker 1.8, feel free to adjust slightly if you have improvements.

Can you add this juse above the https://github.com/docker/docker/blob/master/docs/sources/reference/commandline/cli.md#examples-2

```Markdown
> **Note:** the behavior of `docker create` changed in Docker 1.8.
> Containers created with `docker create` now get an initial status
> of `created` whereas previously the initial status was `exited`.
```



And add this above the https://github.com/docker/docker/blob/f1fed87fc01c31114b78a6ca9f7060fc93480957/docs/man/docker-create.1.md#options
section?

```Markdown
# DESCRIPTION

Creates a writeable container layer over the specified image and prepares it for
running the specified command. The container ID is then printed to STDOUT. This
is similar to **docker run -d** except the container is never started. You can 
then use the **docker start <container_id>** command to start the container at
any point.

Note: the behavior of **docker create** changed in Docker 1.8.
Containers created with **docker create** now get an initial status
of 'created' whereas previously the initial status was 'exited'.
```

**Comment by duglin** [comment]
@thaJeztah I added the docs you suggested but left out the reference to "what's new for v1.8" because I'm afraid people will forget to go back and remove the "what's new" text.

**Comment by thaJeztah** [comment]
> because I'm afraid people will forget to go back and remove the "what's new" text.

I wasn't too afraid it wasn't removed, because it just marked the point at which the behavior changed (I.e., before 1.8 it's 'exited', after 1.8, it's 'created').

Anyway, I think it's good like this. Remind me to check if it is included in the actual release notes for 1.8 :smile:

LGTM

**Comment by moxiegirl** [comment]
@duglin Thanks for the reming the note.  @thaJeztah Thanks for doing a gist-like style comment.  In formal documentation, we document what is; the note actually documented the what changed and that is done in release notes.  

A really great reference for technical writing is: http://amzn.com/0137058268  Written by 25 editors from Sun .... which that many editors in a room arguing technical writing is my idea of hell. However, the book that resulted is incredibly easy to read, follow, and has some timeless material.

**Comment by thaJeztah** [comment]
@moxiegirl thanks for the link, will check it out. We currently (afaik) don't have a document to collect general "what's new" changes, apart from the ones documented in the API reference.

I think we should create one or find some other way to collect these notes. Right now, the changelog/what's new is written after the fact, with the chance that changes are forgotten and go undocumented.

I'm (and don't go barf all over me, LOL) familiar with the approach taken by the PHP documentation, for example: http://php.net/manual/en/function.json-encode.php

This approach is targeted towards readers using various versions of the software. Each page/feature documents;
- the version that the feature was introduced in (at the top)
- a changelog for *that* feature

This saves readers from having to check a global changelog to see if there's possibly a change in that feature. The [MDN documentation](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) takes a similar approach, with changes / links to specs and changes in browser compatibility at the bottom.

(Not really bike-shedding here, but wanted to show other approaches that I'm familiar with and work well in my daily use)

**Comment by moxiegirl** [comment]
@thaJeztah The general document to collect "what's new" changes is typically the Release Notes.  We currently don't have very detailed ones of course.  So, for example, most companies have very release notes that show every issue closed in a release --- they would contain the level of detail you have in your note.  Drupal's comes pretty close: https://www.drupal.org/drupal-7.36-release-notes

Including the release information in notes throughout text becomes a document management problem and a document usability.  You can imagine documenting every minor change in the product with a note would, over time, result in a proliferation of notes. What kind of change do you note? When do you remove a note?  Also, of course, notes have particular functions in documentation:

image

So, we need to apply them consistently within our docs and follow somewhat of the industry standard; so new readers to our site have an understanding of how notes function.  If we put for example, exceptions in our notes and release information users  can begin to ignore the notes --- oh this just is a release note imbedded in the text. Then, of course, lots of notes in text disrupt the flow of information --- generally too many means you have structural problems in your content.

Document management comes into maintenance issues --- when do I pull the notes out? How long do they remain in text?  How do we ensure they clean up over time.

As for APIs, I'm not a huge fan of the changelog at the end of the API. I think anything manual when it comes to an API is just error prone and an indication of lack of documentation/CI tooling.  The best thing to do would be to have tooling that reports to the user changes.  I haven't dug around for tools yet. Java has Clirr which we used at Atlassian.

BTW, I don't consider it bike shedding on a closed PR (correct me if I"m wrong).  Lately, the term "bike shedding" seems to come up on PRs where there is discussion on docs.  I'm sure to maintainers not charged with maintaining and improving the documentation that such a discussion seems "trivial." But our documentation needs a lot of improvement; as the only writer on open source, I hear complaints all the time. So, I don't consider it trivial.  

Also, technical documentation is a profession, they give degrees in it.  It has methodologies, techniques, and conventions that were developed over decades by people interested in teaching others and conveying information in written form.  I'm not so hidebound to believe that we "have to follow the rules" but I am experienced enough to know that Pablo Picasso was correct "Learn the rules like a pro, so you can break them like an artist."

BTW, there is an easy enough way to eliminate all documentation discussion from the PRs. We can decouple the documentation from the code into its own repo.  See, that is the way it used to be done. Since the development of tools like GitHub and Bitbucket there has been this huge surge in coupling the documentation in with the code base and releasing in tandem.  (Version control is not new to documentation, my first was RCS.)   Like any other change it has its tradeoffs. Happy to discuss those as well.

**Pull request merged**
