### PR TITLE
Remove unused Dockerfile instruction INSERT

### PR DESCRIPTION
**Pull request by icecrime**
There might be some history I'm missing for the rationale behind this entry, but it seems unnecessary to me.

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM idk what that was

**Comment by duglin** [comment]
I think you should remove the insert() func in dispatcher.go too

**Comment by icecrime** [comment]
@duglin Good catch: updated.

**Comment by duglin** [comment]
LGTM

**Pull request merged**
