### PR TITLE
Update gotestyourself to gotest.tools

### PR DESCRIPTION
**Pull request by vdemeester**
github.com/gotestyourself/gotestyourself moved to gotest.tools with version 2.0.0. Moving to that one, bumping it to v2.1.0.

most-beautiful-cats-world-3

### CODE REVIEW

**Review by dnephin — APPROVED** [review]

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
PowerPC looks like a flaky https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/10151/console

```
18:05:31 FAIL: check_test.go:347: DockerSwarmSuite.TearDownTest
18:05:31 
18:05:31 unmount of /tmp/docker-execroot/d29a48e026ecc/netns failed: invalid argument
18:05:31 unmount of /tmp/docker-execroot/db2a69f06c7ab/netns failed: no such file or directory
18:05:31 check_test.go:352:
18:05:31     d.Stop(c)
18:05:31 /go/src/github.com/docker/docker/internal/test/daemon/daemon.go:401:
18:05:31     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
18:05:31 ... Error: Error while stopping the daemon d8b1b92b3cf89 : exit status 130
18:05:31 
18:05:31 
18:05:31 ----------------------------------------------------------------------
18:05:31 PANIC: docker_api_swarm_test.go:780: DockerSwarmSuite.TestAPISwarmRestartCluster
18:05:31 
18:05:31 [d29a48e026ecc] waiting for daemon to start
18:05:31 [d29a48e026ecc] daemon started
18:05:31 
18:05:31 [db2a69f06c7ab] waiting for daemon to start
18:05:31 [db2a69f06c7ab] daemon started
18:05:31 
18:05:31 [d8b1b92b3cf89] waiting for daemon to start
18:05:31 [d8b1b92b3cf89] daemon started
18:05:31 
18:05:31 [dc0f6b4444a93] waiting for daemon to start
18:05:31 [dc0f6b4444a93] daemon started
18:05:31 
18:05:31 [d862c182dbb7e] waiting for daemon to start
18:05:31 [d862c182dbb7e] daemon started
18:05:31 
18:05:31 [db4667e08d5f0] waiting for daemon to start
18:05:31 [db4667e08d5f0] daemon started
18:05:31 
18:05:31 [d29a48e026ecc] exiting daemon
18:05:31 [db4667e08d5f0] exiting daemon
18:05:31 [d8b1b92b3cf89] exiting daemon
18:05:31 [db2a69f06c7ab] exiting daemon
18:05:31 [d862c182dbb7e] exiting daemon
18:05:31 [dc0f6b4444a93] exiting daemon
18:05:31 [dc0f6b4444a93] waiting for daemon to start
18:05:31 [db4667e08d5f0] waiting for daemon to start
18:05:31 [d8b1b92b3cf89] waiting for daemon to start
18:05:31 [d862c182dbb7e] waiting for daemon to start
18:05:31 [db2a69f06c7ab] waiting for daemon to start
18:05:31 [d29a48e026ecc] waiting for daemon to start
18:05:31 [d8b1b92b3cf89] daemon started
18:05:31 
18:05:31 [db4667e08d5f0] daemon started
18:05:31 
18:05:31 [dc0f6b4444a93] daemon started
18:05:31 
18:05:31 [d29a48e026ecc] daemon started
18:05:31 
18:05:31 [d862c182dbb7e] daemon started
18:05:31 
18:05:31 [db2a69f06c7ab] daemon started
18:05:31 
18:05:31 [d29a48e026ecc] exiting daemon
18:05:31 [db2a69f06c7ab] exiting daemon
18:05:31 [d8b1b92b3cf89] daemon started
18:05:31 Attempt #2: daemon is still running with pid 6069
18:05:31 Attempt #3: daemon is still running with pid 6069
18:05:31 Attempt #4: daemon is still running with pid 6069
18:05:31 [d8b1b92b3cf89] exiting daemon
18:05:31 ... Panic: Fixture has panicked (see related PANIC)
18:05:31 
```

Timeout / hang on Experimental https://jenkins.dockerproject.org/job/Docker-PRs-experimental/40985/console

```
18:30:48 --- FAIL: Test (5216.96s)
18:30:48 panic: DockerNetworkSuite.TestDockerNetworkCustomIPAM test timed out after 5m0s [recovered]
18:30:48 	panic: DockerNetworkSuite.TestDockerNetworkCustomIPAM test timed out after 5m0s
18:30:48 
```

**Review by thaJeztah — APPROVED** [review]
LGTM if green, but let's check if it doesn't conflict with some other big PR's that are currently pending before we merge

We should also backport this to current release branches

**Comment by vdemeester** [comment]
Ah also, hold on to merge this one, I'm gonna need to update `TESTING.md` too :angel:

**Pull request merged**
