### PR TITLE
Add an option to skip create log stream for awslogs driver

### PR DESCRIPTION
**Pull request by xia-wu**
Added an option `awslogs-create-stream` to allow skipping log stream creation for `awslogs` log driver. The default value is still `true` to keep the behavior be consistent with before.

Signed-off-by: Xia Wu <xwumzn@amazon.com>

**- What I did**
Added a new option `awslogs-create-stream` to `awslogs` log driver to allow skipping log stream creation in AWS CloudWatch Logs. It's very similar to `awslogs-create-group` but used for log stream creation.

**- How I did it**
Added a new option in `awslogs` log config map.

**- How to verify it**
1. Built Docker locally and ran a Docker container with `awslogs-create-stream=false` with an existed log stream name in AWS CloudWatch Logs, the log stream creation was skipped and container started to run successfully. 
```
docker run -d --command "echo hello" \
   --env xxx (credentials) \
   --log-driver=awslogs  \
   --log-opt awslogs-group=test-group \
   --log-opt awslogs-group=test-stream \
   --log-opt awslogs-region=us-west-2 \
   --log-opt awslogs-create-stream=false \
   busybox:latest 
```
2. Also ran a Docker container without log option `awslogs-create-stream` and the log stream created in CloudWatch Logs successfully.
3. Modified existing unit tests and added a unit test for skipped log stream creation.

**- Description for the changelog**
Added a new option to `awslogs` log driver to allow skipping log stream creation in AWS CloudWatch Logs.

**- A picture of a cute animal (not mandatory but encouraged)**
rabbit

### CODE REVIEW

**Review by kzys — APPROVED** [review]

**Review by estesp — APPROVED** [review]
LGTM

**Review by samuelkarp — APPROVED** [review]
LGTM

**Comment by samuelkarp** [comment]
Close/reopen to see if I can trigger Jenkins again (old run is now a 404).

**Comment by thaJeztah** [comment]
Looks like we also need a documentation change to document the new option.
Given that it hasn't shipped yet, probably should be a "draft" PR to update this file in the documentation repository; https://github.com/docker/docker.github.io/blob/7238e69b20872d20c9211e0d1dfd634b21db6dbb/config/containers/logging/awslogs.md#awslogs-create-group


@xia-wu are you interested in opening a draft PR for that?

**Pull request merged**
