### PR TITLE
[19.03] vendor: bump swarmkit 062b694b46c0744d601eebef79f3f7433d808a04

### PR DESCRIPTION
**Pull request by thaJeztah**
equivalent of https://github.com/moby/moby/pull/40431 / https://github.com/moby/moby/pull/40426 but for the 19.03 branch

full diff: https://github.com/docker/swarmkit/compare/f35d9100f2c6ac810cc8d7de6e8f93dcc7a42d29...062b694b46c0744d601eebef79f3f7433d808a04

changes:

- docker/swarmkit#2927 [19.03 backport] Fix leaking subscription contexts
    - backport of docker/swarmkit#2926 Fix leaking log subscription contexts
    - fixes moby/moby#39916 Dockerd eats too much RAM

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@dperny @cpuguy83 ptal

@arkodg @tiborvass not sure if we're still merging things for 19.03.6, so I opened as "draft" for now

**Review by arkodg — APPROVED** [review]

**Comment by thaJeztah** [comment]
(moved out of draft per discussion on slack)

**Comment by thaJeztah** [comment]
note: after this is merged, the `docker/engine 19.03` branch will have to be synced manually

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]

**Comment by tiborvass** [comment]
🚨🚨🚨 After force push, new merge commit is 3ba45ce.

**Pull request merged**
