### PR TITLE
Simplfy the sidebar html and css, and then allow the text to wrap

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit SvenDowideit@home.org.au

http://dowideit-docs.s3-website-ap-southeast-2.amazonaws.com/contributing/docs_style-guide/

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@moxiegirl, @fredlf @jamtur01 


I have some other fixes that will be based off this - the hack upon hack upon hack that this is built on became awful while I was focused on b2d

**Comment by jamtur01** [comment]
LGTM

**Comment by moxiegirl** [comment]
Hi Sven,

Thanks for doing this.  I'm wasn't sure about the hanging indent on the lines. That and the discrepancy between the font sizes on the main and sub menus.  I'm sitting next to a visual designer, Sean.  So, I just asked him what he would recommend.  He had trouble with the hanging indent --- it actually confused him for a moment as he thought maybe the indented second line was a new menu entry and not a continuation.

Anyway, I did a tweak of the docs.css to match with his suggestions. Here is what it looked like in practice:

image

The font size dropped to 15px on the top level.  The actual css:

```
#top-header {
  margin-top: 26px;
  margin-bottom: 10px;
}

#top-header .header2 {
  font-weight: 400;
}

#usernav > ul {
  margin-top: 10px;
  z-index: 99999;
}

.menu-caption {
  padding-bottom: 10px;
}

#toc_table {
  margin-top: 10px;
}

#leftnav {
  height: 100%;
  overflow: hidden;
}

#leftnav .nav ul {
  line-height: 1;
  margin: 10px 10px 0px 16px;
  padding: 0;
  list-style: none;
}
#leftnav .nav li ul a,
#leftnav .nav li ul a:hover {
  margin: 0 !important;
  padding: 0 !important;
  font-size: 13px;
  font-weight: 400;
  color: #394d54;
}
#leftnav .nav li ul a:hover {
  color: #24b8eb;
}

#leftnav .nav.nav-tabs li a,
#leftnav .nav.nav-tabs li li {
  line-height: 1.1 !important;
}

#leftnav li {
  margin-top: 20px;
 // text-indent: -16px;
  padding-left: 10px;
}
#leftnav .nav-tabs.nav ul li {
  margin-top: 5px;
}

.content-body {
  padding: 0px 0px 0px 20px;
}

ol {
  padding-left: 22px;
}

ol li {
  margin: 8px;
}

pre {
  font-size: 12px;
  line-height: 1.5;
}

/* Main Navigation */
#nav_menu > #docsnav {
  max-width: 940px;
  width: 940px;
  margin: 0 auto;
}
#nav_menu > #docsnav > #nav_search {
  margin-top: 10px;
}
.search_input:focus {
  background: #fff;
  outline: none;
}
#nav_menu > #docsnav > #main-nav {
  height: 50px;
  margin: 0px;
  padding: 0em;
}
#nav_menu > #docsnav > #main-nav > li > a {
  color: #253237;
}
#nav_menu > #docsnav > #main-nav > li.dd_on_hover {
  background: #d3f1fb;
  color: #253237;
}
#nav_menu > #docsnav > #main-nav > li > span > b {
  border-top-color: #b1d5df !important;
}
#nav_menu > #docsnav > #main-nav > li.dd_on_hover > span > b {
  border-top-color: #71afc0 !important;
}
#nav_menu > #docsnav > #main-nav > li form {
  margin-top: -12px;
}
#nav_menu > #docsnav > #main-nav > li.home > a {
  color: #fff;
}
#nav_menu > #docsnav > #main-nav > li.home:hover {
  background: #b1d5df;
}
#nav_menu > #docsnav > #main-nav > li.home:hover > a {
  color: #5992a3;
}
#nav_menu {
  background: #E8E8E8;
  position: relative;
  width: 100%;
  height: 54px;
  z-index: 1000;
  top: auto;
  padding: 0px 15px;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
#nav_menu #docsnav #main-nav > li {
  font-size: 15px;
  font-weight: 400;
  color: #253237;
  line-height: 2em;
  display: block;
  padding: 0 12px 0 12px;
  line-height: 54px;
  height: 54px;
}
#nav_menu #docsnav #main-nav > li.active {
  background: #ade5f9; /* url("../img/nav/caret-down-subnav-icon.svg") no-repeat 87% 50%;*/
}
#nav_menu #docsnav #main-nav > li.dd_on_hover {
  /*background: #ade5f9 url("../img/nav/caret-down-subnav-icon.svg") no-repeat 87% 50%;*/
}
#nav_search {
  padding-top: 2px;
}
#nav_search input[type="text"] {
  width: 220px;
  height: 30px;
  margin: 0;
  background: #ffffff url("../img/nav/search-icon.svg") no-repeat 95% 50%;
}
/* Navigation Submenu */
.dd_menu {
  cursor: pointer;
}
.dd_menu .dd_submenu {
  display: none;
  position: absolute;
  top: 54px;
  list-style: none;
  margin: 0px;
  margin-left: -12px;
  overflow: hidden;
  overflow-y: auto;
  background: #fff;
  border: 1px solid #ccc;
  border-top: none;
  border-bottom: 3px solid #ccc;
  -webkit-border-radius: 0px 0px 4px 4px;
  -moz-border-radius: 0px 0px 4px 4px;
  border-radius: 0px 0px 4px 4px;
  padding: 0px;
}
.dd_menu.dd_on_hover .dd_submenu {
  display: block;
}
.dd_menu.dd_on_hover .dd_submenu > li:first-child {
  border: none;
}
.dd_menu.dd_on_hover .dd_submenu > li {
  border-top: 1px solid #ddd;
}
.dd_menu.dd_on_hover .dd_submenu > li.active > a {
  border-color: #b1d5df;
  color: #FF8100 !important;
}
.dd_menu.dd_on_hover .dd_submenu > li > a {
  padding: 0.6em 0.8em 0.4em 0.8em;
  width: 100%;
  display: block;
}
.dd_menu li a {
  font-size: 15px;
  font-weight: 400;
  color: #005976;
}
.dd_menu li a:hover {
  text-decoration: none;
  font-size: 15px;
  font-weight: 400;
  color: #24b8eb;
}

/* Search Page */
#tipue_search_input {
  height: 30px;
  margin: 0;
  background: #ffffff url("../img/nav/search-icon.svg") no-repeat 95% 50%;
}

.alert-red-block {
  margin: 10px 0px;
  background: #edd3d7;
  border: none;
  margin-bottom: 20px;
}

.content-body ul {
  padding: 10px 0px 10px 20px;
  list-style-position: inherit;
  list-style: circle;
}

.content-body ul li {
  padding-bottom: 5px;
}

.content-body ul ul {
  padding: 10px 0px 10px 40px;
}

.content-body h1 {
  display: block !important;
  font-size: 27px;
  font-weight: 400;
  color: #394d54;
  line-height: 1.33;
  margin-bottom: 8px;
  margin-top: 6px;
}

.content-body h2 {
  font-size: 21px;
  font-weight: 400;
  color: #394d54;
  line-height: 1.7;
  margin-bottom: 4px;
  margin-top: 10px;
}

.content-body h3 {
  font-size: 18px;
  font-weight: 400;
  color: #394d54;
  line-height: 1.7;
  margin-bottom: 4px;
  margin-top: 10px;
}

.content-body h4 {
  font-size: 16px;
  font-weight: 400;
  color: #394d54;
  line-height: 1.7;
  margin-bottom: 4px;
  margin-top: 10px;
}

.content-body p {
  font-size: 14px;
  font-weight: 400;
  color: #394d54;
  line-height: 1.7;
}

.content-body p code {
  background-color: #FCFCFC;
  border-radius: 4px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border: 1px solid #dbdde0;
  color: #394d54;
  padding-left: 6px;
  padding-right: 6px;
  margin-bottom: 2px;
}

.content-body blockquote {
  margin: 0px !important;
  margin-bottom: 20px !important;
  margin-top: 20px !important;
  font-size: 14px;
  font-weight: 400;
  color: #394d54;
  line-height: 1.7;
  font-style: italic;
  border: none;
  border-left: 4px solid #ade5f9;
  padding: 10px;
  padding-left: 15px;
}

.content-body ul {
  margin-top: 0px !important;
}

.content-body blockquote a {
  color: #24b8eb;
}

.content-body blockquote a:hover {
  color: #008bb8;
}

.content-body ul {
  margin-top: 0px !important;
}

.content-body pre {
  font-family: Monaco, Consolas, "Lucida Console", monospace;
  background-color: #FCFCFC;
  margin-bottom: 20px;
  border-radius: 4px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  overflow-x: auto;
}
.content-body pre code {
  overflow-wrap: normal;
  white-space: pre;
}

.content-body strong {
  font-weight: bold;
}

/* Logged-in/out header */
.topmostnav_loggedin {
  display: none;
}
#topmostnav.public .brand {
  padding-left: 0px !important;
}
.navbar #usernav .nav li {
  padding-top: 0px !important;
}
table.table tr td img {
    width:100%;
}
#versionnav ul {
    list-style: none outside none;
}
#versionnav ul ul {
    padding: 0;
}

/* over-ride the prettyPrint colouring */

.str, .atv { color: #48484C; }
```

**Comment by SvenDowideit** [comment]
One of the reasons I added the hanging indent was the faq page, where the vertical spacing wasn't quite enough differentiation. I wonder if making the indent very small (rather than eliminating it entirely) would work better

I'll look further on Monday

**Comment by SvenDowideit** [comment]
ok, one last try for the indent :) - 4px 
faq docker documentation
run a local registry mirror docker documentation

**Comment by moxiegirl** [comment]
Well, I'm not sure. It looks a bit like a pixel problem...  I can run it by Sean for his eye if you want but I would bet some big $$ he won't like it. Can't we just assign a line height to the second level items in the nav? It might make more sense to do that if the vertical spacing is the issue prompting this.

**Comment by SvenDowideit** [comment]
ok, I've backed out the text-indent, its a pretty major improvement to readability

**Comment by fredlf** [comment]
LGTM

**Comment by moxiegirl** [comment]
Yay @SvenDowideit!

**Pull request merged**
