### PR TITLE
Normalized, ungrouped, and sorted names

### PR DESCRIPTION
**Pull request by toddjcrane**
Signed-off-by: Todd Crane todd@toddcrane.com

### CODE REVIEW

**Comment by runcom** [comment]
Why Gordon didn't tag this pr :confused:

**Comment by calavera** [comment]
No idea, it might be down.

LGTM

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
Great job, @toddjcrane, thanks !

**Pull request merged**
