### PR TITLE
resolve service container hostname

### PR DESCRIPTION
**Pull request by RekGRpth**
**- What I did**
resolve service container hostname

**- How I did it**
add one string into corresponding function

**- How to verify it**
build whole docker deb, install it on docker swarm and verify that resolving works with templating hostname as {{.Service.Name}}-{{.Task.Slot}} for replicated service or {{.Service.Name}}-{{.Node.Hostname}} for global service

**- Description for the changelog**
resolve service container hostname

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Curious; Isn't this already handled by the changes from https://github.com/moby/moby/pull/39204 ?

**Comment by RekGRpth** [comment]
No! That PR does not work at services in swarm! But my - does!

**Comment by olljanat** [comment]
@RekGRpth have you tested with latest binaries from https://master.dockerproject.org ?

I'm quite sure that this was already fixed by #39204 those changes just have not been released yet.


But if this change is needed then it must be implemented to https://github.com/moby/libnetwork and vendored to here + integration test which I included need to be updated.

**Comment by RekGRpth** [comment]
Yes, in 20.10.0 all works fine

**Pull request closed without merging**
