### PR TITLE
Add support for volume consistency in compose format

### PR DESCRIPTION
**Pull request by dnephin**
cc @shin-

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by vdemeester** [comment]
@dnephin small build failure though

```
14:13:44 The result of `go generate github.com/docker/docker/cli/compose/schema` differs
14:13:44 
14:13:44  M cli/compose/schema/bindata.go
14:13:44 
14:13:44 Please run `go generate github.com/docker/docker/cli/compose/schema`
```

**Comment by dnephin** [comment]
Oops, I did forget to generate bindata. rebased and fixed that

**Comment by vieux** [comment]
LGTM

**Comment by shin-** [comment]
@dnephin I thought v3 formats were frozen after making it into a GA release, but this introduces a new option in v3.2 for the 17.05 release? Or does that format freeze only happen for stable releases, not edge?

**Comment by dnephin** [comment]
@shin- I was going to do what I did for the last release, which is create the new version right right before freeze. It should get moved into v3.3 I think

**Comment by thaJeztah** [comment]
@dnephin can you take care of moving it?

**Comment by dnephin** [comment]
Yes, I will do that today

**Pull request merged**
