### PR TITLE
CI: use dockerCmd in integration-cli when possible

### PR DESCRIPTION
**Pull request by HuKeping**
Parts of #14603
Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by runcom** [comment]
@HuKeping there's an unused `os/exec` that should be removed

**Comment by HuKeping** [comment]
@cpuguy83 fixed.

**Comment by cpuguy83** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
