### PR TITLE
fix race in events test

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by LK4D4** [comment]
I wonder how it was racy because of this :)
LGTM

**Comment by jfrazelle** [comment]
i dunno jenkins was freaking out but locally this works for me, jenkins will be the true test

**Comment by jfrazelle** [comment]
ugh hang on doing a bisect

**Comment by jfrazelle** [comment]
not proud of this changed the order and its all good

also removed a bad log

**Comment by jfrazelle** [comment]
ping @LK4D4

**Comment by jfrazelle** [comment]
also @crosbymichael because we need this so prs stop failing uggghhh

**Comment by tiborvass** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM again :)

**Pull request merged**
