### PR TITLE
ServiceCreate/ServiceUpdate: refactor and fix potential NPE

### PR DESCRIPTION
**Pull request by thaJeztah**
- `ContainerSpec` and `PluginSpec` are mutually exclusive, so instead of using two separate if-statements, combine them in a switch.
- Use local variables (at cost of some slight duplication)
- Fix a potential NPE if image-digest resolution failed for a `PluginSpec`.  The code was always using `ContainerSpec.Image` to create a `digestWarning`,  but in case we're resoling the digest for a `PluginSpec`, `ContainerSpec`  will be `nil` (as they're mutually exclusive). This issue was introduced in  https://github.com/moby/moby/commit/72c3bcf2a533a827402945e3a55872e2db4fb024 (https://github.com/moby/moby/pull/33575), where the new `PluginSpec` path  was added.
- imageWithDigestString: return image unmodified if there are no changes
  Instead of returning an empty string, return the image unmodified
- extract logic for resolving image/plugin digest and platform

### CODE REVIEW

**Comment by thaJeztah** [comment]
🤦 made a whoopsie; fixed now

@cpuguy83 ptal

**Comment by thaJeztah** [comment]
Did this one become flaky again? (it was in the past)

```
=== RUN   TestDockerSuite/TestLogsFollowSlowStdoutConsumer
    --- FAIL: TestDockerSuite/TestLogsFollowSlowStdoutConsumer (1.81s)
        docker_cli_logs_test.go:243: assertion failed: error is not nil: exit status 1
```

**Comment by thaJeztah** [comment]
@tonistiigi @cpuguy83 PTAL 🤗

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
