### PR TITLE
[1.13.x] depend on docker-selinux for fedora-25+ and centos-7

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Same changes as PR #29114 "depend on docker-selinux for fedora-25+ and centos-7".

**- How I did it**

bash$ git cherry-pick 58b02b7
bsah$ git cherry-pick 2b04b92
bash$ git cherry-pick 8581402

**- How to verify it**

same same

**- Description for the changelog**

Use the selinux policy provided by `docker-selinux` on Fedora 25+ and CentOS 7.3.

**- A picture of a cute animal (not mandatory but encouraged)**

🐮

### CODE REVIEW

**Comment by runcom** [comment]
LGTM will ease all the troubles going forward, ping @crosbymichael

**Comment by vdemeester** [comment]
ping @cpuguy83 @andrewhsu @crosbymichael @runcom

**Comment by cpuguy83** [comment]
Ok, the reason this doesn't work is because docker-selinux is built for 1.10 (at least in centos). This was before the client/daemon split, so the policy does not account for `dockerd`, so it never gets labeled correctly.

**Comment by andrewhsu** [comment]
Closing. Talked with @cpuguy83 about different tactic to take to get selinux working.

**Pull request closed without merging**
