### PR TITLE
fix tls verify false

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tiborvass @icecrime 

had a daemon w tlsverify false, failing with that foobar line

### CODE REVIEW

**Comment by cpuguy83** [comment]
That doesn't seem right because we need to set the tlsconfig whether or not tlsverify is set.
And the check InsecureSkipVerify should be sufficient to check the client auth, see: https://github.com/docker/docker/blob/master/docker/common.go#L86

What does the error look like?

**Comment by jfrazelle** [comment]
```

**Comment by jfrazelle** [comment]
```
time="2015-07-30T00:36:39.503494200Z" level=fatal msg="foobar: Could not load X509 key pair (, ): open : no such file or directory" 
```

**Comment by jfrazelle** [comment]
honestly i didnt put my full brain innto this patch... been a long day someone can cary

**Comment by jfrazelle** [comment]
actually i can fix

**Comment by jfrazelle** [comment]
if I pass tlsvery=false I dont need a key or cert which is what 
```
tlsConfig, err := tlsconfig.Server(*commonFlags.TLSOptions)		 		tlsConfig, err := tlsconfig.Server(*commonFlags.TLSOptions)
 		if err != nil {		 		if err != nil {
-			logrus.Fatalf("foobar: %v", err)		+			logrus.Fatal(err)
 		}
```
is doing

**Comment by cpuguy83** [comment]
Ok, I see the issue here.
If `--tlsverify` is set at all, it is setting things up as if `--tls` is true.
So basically, `docker daemon --tlsverify=false` is the same thing as `docker daemon --tls`

**Comment by calavera** [comment]
@jfrazelle do we need this for 1.8?

**Comment by tiborvass** [comment]
Coming up with a fix, sorry about that

**Comment by tiborvass** [comment]
@cpuguy83 right and that's "expected behavior", there is even a comment in the code for that.

**Comment by jfrazelle** [comment]
Yes we def need a fix for it maybe not mine lol

**Comment by jfrazelle** [comment]
closing this one because its not that great and @duglin is on the case ;)

**Pull request closed without merging**
