### PR TITLE
Move more api types to api/types package

### PR DESCRIPTION
**Pull request by dnephin**
Moves `AuthConfig` to `api/types` and removes the build and api/types dependency on `cliconfig`.

Moves a few registry types to `api/types/registry` which removes the api/types dependency on `registry`.

I had to do this together because after moving `AuthConfig` there was a circular import.

Some methods were turned into package level functions as a result of the types being moved.

cc @calavera

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐶

**Comment by thaJeztah** [comment]
Thanks for doing these @dnephin!

**Pull request merged**
