### PR TITLE
Remove mkimage-unittest.sh

### LINKED ISSUE #11559: Test the Link via an Ambassador Container article
Test the article and ensure the process works as documented. File any issues a `writing` issues.

http://docs.docker.com/articles/ambassador_pattern_linking/

### PR DESCRIPTION
**Pull request by cellpjs**
make docker-ut image work with svendowideit/ambassador image
currently
docker pull docker-ut
gives error image ID 'e9aa60c60128cad1' is invalid
probably need to rebuild docker-ut

fix #11559

### CODE REVIEW

**Comment by rrarunan** [comment]
@cellpjs Can you please add a `closes` or `fixes` keyword so its easy to track the fix? Thanks!

**Comment by cellpjs** [comment]
this fixes the issue faced while testing the doc https://docs.docker.com/articles/ambassador_pattern_linking/
as per
https://github.com/docker/docker/issues/11559
@SvenDowideit

**Comment by vieux** [comment]
@tianon can you please take a look ? Thanks!

**Comment by jfrazelle** [comment]
hmmm im not that familiar with this script ping @tianon :/

**Comment by tianon** [comment]
I don't know why this script exists anymore.  We used to use the image it creates in our tests, but haven't for quite some time.

**Comment by tianon** [comment]
More examples of images that I'm not sure should even exist anymore:
- https://registry.hub.docker.com/_/docker-test-image/
- https://registry.hub.docker.com/_/docker-unit-tests/
- https://registry.hub.docker.com/_/docker-ut/

**Comment by jfrazelle** [comment]
so should we remove?

**Comment by tianon** [comment]
IMO yes, unless someone has a good reason not to

**Comment by jfrazelle** [comment]
can you change your PR to remove it instead :)

**Comment by cellpjs** [comment]
svendowideit/ambassador images is based on this. The script must have worked to create docker-ut at some time under some setting. I was trying to reproduce the steps based on the https://docs.docker.com/articles/ambassador_pattern_linking/
Q: should we worry about being able to recreate an image once it is created?

**Comment by tianon** [comment]
I think this purpose is probably better served with the still-somewhat-new `alpine` image:
```Dockerfile
FROM alpine
RUN apk add --update socat && rm -rf /var/cache/apk/*
```

**Comment by cellpjs** [comment]
Changed PR to remove mkimage-unittest.sh
@tianon Thanks for the pointer. It seems there is a trend to create minimalist images.

**Comment by calavera** [comment]
This LGTM. Ping @tianon, @jfrazelle

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
