### PR TITLE
fix up engine labels conflicting in 'daemon/config.go and cli/command/system/info.go '

### PR DESCRIPTION
**Pull request by zhukj**
**- What I did**
Fix up engine labels conflicting when running `dockerd` cmd with duplicate key-value pairs(such as --lable x=y --label x=y) and `docker info`.
**- How I did it**
I just modify two files daemon/config.go and cli/command/system/info.go,and change "if v, ok := labelMap[stringSlice[0]]; ok && v != stringSlice[1]" to "if v, ok := labelMap[stringSlice[0]]; ok && v == stringSlice[1]".
**- How to verify it**
Run command `dockerd --label x=y --label x=y --label x=y` and `docker info`,it will print warning information.
**- Description for the changelog**
Fix up engine labels conflicting in 'daemon/config.go and cli/command/system/info.go '
Signed-off-by: zhukj <zhu.kunjia@zte.com.cn>

### CODE REVIEW

**Comment by allencloud** [comment]
Can you squash the two commits into a single one? @zhukj

**Comment by zhukj** [comment]
Does it mater? And can you tell how to squash the two commits into a single one? @allencloud

**Comment by zhukj** [comment]
Does it mater? And can you tell me how to squash the two commits into a single one? @allencloud

**Comment by ehazlett** [comment]
@zhukj yes it makes it easier to review.  you can squash by using `git rebase -i` and then `git push -f` to your branch.

**Comment by yongtang** [comment]
@zhukj In the current implementation, a warning will be returned if there are conflicting values with duplicate keys. In other words, `--label x=y --label x=z` will result in a warning. 
For duplicate key=value pairs (no conflict), no warning is shown. For example, `--label x=y --label x=y` will not be a warning.

**Comment by zhukj** [comment]
For duplicate key=value pairs (no conflict), I think they should be integrated into a single one. For example, when we use --label x=y --label x=y to start docker daemon , the command `docker info` should show only one label, no all duplicate key=value pairs. I think it remains to perfect further. Thanks!

**Comment by zhukj** [comment]
For duplicate key=value pairs (no conflict), I think they should be integrated into a single one. For example, when we use --label x=y --label x=y to start docker daemon , the command docker info should show only one label, no all duplicate key=value pairs. I think it remains to perfect further. Thanks! @yongtang

**Comment by thaJeztah** [comment]
@zhukj the reason we did not change that behavior is because it would break backward compatibility. See the discussion on https://github.com/docker/docker/pull/24533#issuecomment-232051907. Instead, we deprecated the option, so that we can change it in docker 1.16

**Pull request closed without merging**
