### PR TITLE
Updated docker-engine.spec to build on Oracle Linux 6.

### LINKED ISSUE #14544: Build docker-engine RPMs for Oracle Linux 6
Identical to issue #14481 but for Oracle Linux 6.

### PR DESCRIPTION
**Pull request by Djelibeybi**
This adds support for building docker-engine on Oracle Linux 6. The spec file is updated to ensure that the Oracle Unbreakable Enterprise Kernel Release 3 and updated device-mapper is installed to support the latest Docker builds.

Resolves #14544 

Signed-off-by: Avi Miller avi.miller@oracle.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
Is there a way I can test this how do I get an oracle linux iso

**Comment by Djelibeybi** [comment]
You don't need one: this pulls oraclelinux:6 from the Docker Hub Registry and builds inside the container. However, if do want do download Oracle Linux, the official download source is http://edelivery.oracle.com/linux (requires a free Oracle SSO account) or you can grab the ISO from one of our mirrors: https://community.oracle.com/docs/DOC-917963

**Comment by Djelibeybi** [comment]
Note that the container image on the Hub has been updated to include the RPM macro required for the spec file. This update will ship with Oracle Linux 6.7, so it's not available on an ISO or via our update service yet. I specifically updated the Docker image first, so that this would work, i.e. because the RPM is built inside a container.

**Comment by jfrazelle** [comment]
No I meant to test the rpm on

**Comment by Djelibeybi** [comment]
Oh, right. :) Then yeah, grab the latest OL6U6 and OL7U1 ISOs from one of the mirrors (much easier than the Oracle download service). On install, they're automatically configured to use our free update service, so you can install the RPM immediately with yum and it'll pull in any dependencies required.

**Comment by jfrazelle** [comment]
Great thanks :)

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
