### PR TITLE
Support for upgrading to docker-ce channels

### PR DESCRIPTION
**Pull request by guessi**
package name renamed after Docker Community Edition announced, and              
according to the setup guide, repositories have changed as well, but            
the helper scripts didn't reflect these changes.                                
                                                                                
if user setup his/her Docker environment with __https://get.docker.com__,       
it was originally to have "docker-engine" releases during upgrade,              
v1.12.6 -> v1.13.0 -> v1.13.1                                                   
                                                                                
but with "docker-ce" announced, it will now getting alised "docker-ce",         
1.12.6 -> 1.13.0 -> 1.13.1 -> 17.03.0 -> 17.03.1 -> 17.04.0,                    
which is **Docker-CE Edge** release                                             
                                                                                
but it was expected to have **Docker-CE Stable** release                        
                                                                                
with this commit,                                                               
it is possible to switch between channels via corresponding URLs                
- https://experimental.docker.com for edge channel releases                     
- https://get.docker.com for stable channel releases                            
- https://test.docker.com for test channel releases                             
                                                                                
References:                                                                     
- https://www.docker.com/community-edition                                      
- https://download.docker.com/linux/

**- What I did**

partial rewrite hack/install.sh for setting up different channal of docker-ce build
- docker-ce[stable] via get.docker.com
- docker-ce[edge] via experimental.docker.com
- docker-ce[test] via test.docker.com

**- How I did it**

partial rewrite hack/install.sh

**- How to verify it**

verify if the /etc/apt/sources.list.d/docker.list or /etc/yum.repos.d/docker-ce-${channel}.repo is pointed to correct channel

**- Description for the changelog**

enable support for docker-ce installation

### CODE REVIEW

**Comment by vieux** [comment]
@guessi legacy "docker-engine" packages are still being updated to day, we are putting the edge releases on get.docker.com as well. so 
1.12.6 -> 1.13.0 -> 1.13.1 -> 17.03.0 -> 17.03.1 -> 17.04.0 should work as expected

/cc @andrewhsu

**Comment by guessi** [comment]
@vieux okay, I'll try to describe more in detail,

before this PR, I'm staying on 17.03.0, and expected to have "stable" 17.03.1 release after a version upgrade, since I thought "get.docker.com" is mapping to "stable" release in docker-ce lifecycle, but what I really get is jumping from 17.03.0 to 17.04.0, noted that 17.03.1 was skipped.

if "get.docker.com" is mapping to "edge" release in docker-ce,
I would expected to have "docker-ce" and legacy "docker-engine" at the same time,

- docker-engine for 1.10.x, 1.11.x, 1.12.x, 1.13.x
- docker-ce 17.03.x, 17.06.x, 17.09.x

aliasing legacy docker-engine to docker-ce "edge" would be misleading,
they are totally difference life cycle

shouldn't "get.docker.com" to be stopped at docker-engine 1.13.1 ?

reference:
- https://docs.docker.com/engine/installation/#time-based-release-schedule

**Comment by guessi** [comment]
@vieux my opinion in short,
it would be better to have separated scripts for "docker-engine" and "docker-ce"

or people like me would ask about
- what's the different between (experimental|test|get).docker.com in docker-ce lifecycle ?
- how can I get stable docker-ce with these helper scripts?

**Comment by thaJeztah** [comment]
Adding a script to download.docker.com (to install the docker-ce packages), is being discussed. But this change is not correct, because it would break people that are on a platform that's no longer supported (older distros, e.g.), and use these scripts to setup those

> how can I get stable docker-ce with these helper scripts?

The recommended approach is to use the installation instructions as provided in the docs (e.g. https://docs.docker.com/engine/installation/linux/ubuntu/), and not use the script. This script is just a "express install" to get people going, not intended for production setup, where (in most cases); specific configuration changes are needed, or versions need to be "pinned"

**Comment by guessi** [comment]
okay, I found small discussion at #32432, and it's merged.

and you're right, get.docker.com is just "express install",
I will modify my personal installation script for getting stable channel releases.

**Comment by thaJeztah** [comment]
Let me go ahead and close this PR, per the discussion above, but feel free to continue the conversation, and thanks for contributing!

**Pull request closed without merging**
