### PR TITLE
vendor: update tar-split

### LINKED ISSUE #37581: Error processing tar file(exit status 1): unexpected EOF adding an 8G file (8G - 1 byte is ok)
**Description**

This was first reported on Mac by @flagbug: https://github.com/docker/for-mac/issues/2388#issuecomment-409532891 but I believe it is a generic problem with the engine, not something specific to Mac.

To reproduce:

```
/tmp/test # cat Dockerfile
FROM ubuntu:18.04

RUN head -c 8G </dev/urandom >file

/tmp/test # docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu:18.04
 ---> 735f80812f90
Step 2/2 : RUN head -c 8G </dev/urandom >file
 ---> Running in 4debf740eb97
Error processing tar file(exit status 1): unexpected EOF
```

**Describe the results you received:**

The error "Error processing tar file(exit status 1): unexpected EOF"

**Describe the results you expected:**

The build should complete successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

The logs have:
```
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.598573889Z" level=debug msg="Tar with options on /var/lib/docker/overlay2/f89859e8af0b77222f209807333da05295ee03d1a9e2255895cf10ec57cce417/diff" storage-driver=overlay2
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.602482132Z" level=debug msg="Applying tar in /var/lib/docker/overlay2/278e40f6fc45ea9828cb090bf339b4f85561fa03dd2446626c3d9b6a272d8f5b/diff" storage-driver=overlay2
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.750205351Z" level=debug msg="Cleaning up layer 278e40f6fc45ea9828cb090bf339b4f85561fa03dd2446626c3d9b6a272d8f5b: Error processing tar file(exit status 1): unexpected EOF"
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.751542982Z" level=error msg="Can't add file /var/lib/docker/overlay2/f89859e8af0b77222f209807333da05295ee03d1a9e2255895cf10ec57cce417/diff/file to tar: io: read/write on closed pipe"
2018-08-02T14:16:35Z docker-ce time="2018-08-02T14:16:35.751599637Z" level=error msg="Can't close tar writer: io: read/write on closed pipe"
```

If I switch the command to `head -c 8589934591 </dev/urandom >file` i.e. 8GiB - 1 byte then it succeeds correctly. 

I suspect this is same underlying issue as https://github.com/moby/moby/issues/37305 where a `microsoft/mssql-server-linux` database backup is restored and then `docker commit`ted. I suspect the root cause is that an individual file exceeds 8GiB, which is a limit in the tar header. According to [wikipedia](https://en.wikipedia.org/wiki/Tar_(computing)):

> Thus although there are 12 bytes reserved for storing the file size, only 11 octal digits can be stored. This gives a maximum file size of 8 gigabytes on archived files. To overcome this limitation, star in 2001 introduced a base-256 coding that is indicated by setting the high-order bit of the leftmost byte of a numeric field. GNU-tar and BSD-tar followed this idea. Additionally, versions of tar from before the first POSIX standard from 1988 pad the values with spaces instead of zeroes.

**Output of `docker version`:**

```
/tmp/test # docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:04:40 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
/tmp/test # docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: UFJG:WKJW:OBVN:JP4C:NXIX:YJ7Z:JHQS:AT4L:RO2C:MN7I:YMUW:EQN7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 68
 System Time: 2018-08-02T14:49:58.963009758Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by kolyshkin**
..to include https://github.com/vbatts/tar-split/pull/48

In addition, an integration test case for #37581 is added.

Fixes https://github.com/moby/moby/issues/37581.

sobaka ulybaka
_image source: https://github.com/sdfsdhgjkbmnmxc/dogola_

### CODE REVIEW

**Comment by kolyshkin** [comment]
Yes, the test case (that was failing in #37772) is now passing, meaning the fix is working. This is in addition to some manual testing I've done.

**Comment by kolyshkin** [comment]
TODO: merge https://github.com/vbatts/tar-split/pull/48; do a proper revendor (w/o my fork).

**Comment by kolyshkin** [comment]
ppc failure is unrelated (https://github.com/moby/moby/issues/32673)
> 01:32:13.399 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection

**Review by vdemeester — APPROVED** [review]
SGTM :taco: 
cc @dgageot

**Comment by dgageot** [comment]
Thank you! SGTM too

**Comment by vbatts** [comment]
cc self

**Comment by vbatts** [comment]
I've merged the PR and tagged [v0.11.0](https://github.com/vbatts/tar-split/releases/tag/v0.11.0)
Big thanks @kolyshkin for the fix. Thanks @dgageot for the report reproducer. 
And thanks to @vdemeester for being another cool Vincent ;-)

**Comment by kolyshkin** [comment]
> I've merged the PR and tagged v0.11.0

Rebased to use it, added a test case. This one is ready to be merged.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by kolyshkin** [comment]
exp CI failure is def unrelated (see https://github.com/moby/moby/issues/34988):
> 01:09:47.681 FAIL: check_test.go:347: DockerSwarmSuite.TearDownTest
> ...
> 01:09:47.686 PANIC: docker_api_swarm_test.go:359: DockerSwarmSuite.TestAPISwarmRaftQuorum

**Comment by shilpikm** [comment]
Hi, We are using Docker 18.09.6 and we are seeing this error randomly but quite often with image sizes much smaller than 8GB.

**Comment by thaJeztah** [comment]
please open a new ticket with details and steps to reproduce. Does it also reproduce on docker 19.03? (18.09 reached eol)

**Comment by dskvr** [comment]
@thaJeztah This bug was reintroduced in docker `19.xx`

**Pull request merged**
