### PR TITLE
Update docker.fish

### PR DESCRIPTION
**Pull request by dagelf**
Signed-off-by: Coenraad Loubser coenraad@wish.org.za

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by dagelf** [comment]
I'm testing doing it straight from Github, I've not done this on Github before. Will putting it in the comment box on the commit have the same effect? Or is there another way? Or can I just put it here?
Signed-off-by: Coenraad Loubser <coenraad@wish.org.za>

**Comment by jfrazelle** [comment]
If you fork the repo, then clone your fork and checkout that branch, then
you can follow the sign off instructions above. Let me know if you need any
help.

**Comment by jfrazelle** [comment]
How is it going? I am happy to help.

**Comment by jfrazelle** [comment]
Hey @dagelf I am going to sign your commit with my sig and reopen :) thanks for the patch, it will still be your commit that gets added :D

**Pull request closed without merging**
