### PR TITLE
validate CHANGELOG.md dates are in descending order

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Added validation script to check `CHANGELOG.md` has descending order of dates so RPM builds can process the changelog.

Fixed one line in `CHANGELOG.md` so the check succeeds.

Without this fix, builds of RPM packages will fail with error:
```
error: %changelog not in descending chronological order
```

**- How I did it**

Using `grep`, `awk`, and `sort`.

**- How to verify it**

```
$ hack/validate/default
Congratulations!  All commits are properly signed with the DCO!
Congratulations!  All Go source files are properly formatted.
Congratulations!  All Go source files have been linted.
Congratulations!  "./pkg/..." is safely isolated from internal code.
No api/types/ or api/swagger.yaml changes in diff.
Congratulations!  No testing.T found.
Congratulations!  All toml source files changed here have valid syntax.
Congratulations!  All Go source files have been vetted.
Congratulations!  Changelog CHANGELOG.md is well-formed.
Congratulations!  Changelog CHANGELOG.md dates are in descending order.
```

The validation script also accepts on argument to allow you to override the filename to validate, e.g.

```
$ hack/validate/changelog-date-descending MALFORMED-CHANGELOG.md
sort: -:2: disorder: (2017-01-10)
$ echo $?
2
```

**- Description for the changelog**

N/A

**- A picture of a cute animal (not mandatory but encouraged)**

ʕ ᵔᴥᵔ ʔ

### CODE REVIEW

**Comment by andrewhsu** [comment]
@mlaventure @vdemeester @thaJeztah @vieux 

Need this to get the RPM builds on `master` branch going again.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by andrewhsu** [comment]
@vieux @thaJeztah may be desirable to have this PR cherry picked to release branches

**Pull request merged**
