### PR TITLE
Convert libnetwork stats directly to api types 

### PR DESCRIPTION
**Pull request by tonistiigi**
Network stats types were the last things still using types from `runc/libcontainer`. By converting them directly we don't need to vendor that package any more.

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
CI is failing;

```
20:26:02 ---> Making bundle: test-unit (in bundles/1.11.0-dev/test-unit)
20:26:02 Sat Mar 19 20:26:02 UTC 2016
20:26:03 profiles/seccomp/seccomp.go:11:2: cannot find package "github.com/opencontainers/runc/libcontainer/seccomp" in any of:
20:26:03 	/go/src/github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/seccomp (vendor tree)
20:26:03 	/usr/local/go/src/github.com/opencontainers/runc/libcontainer/seccomp (from $GOROOT)
20:26:03 	/go/src/github.com/opencontainers/runc/libcontainer/seccomp (from $GOPATH)
20:26:03 	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/seccomp
```

**Comment by jfrazelle** [comment]
vendoring script remved too much

**Comment by jfrazelle** [comment]
oh crap its because there are no exec drivers

**Comment by tonistiigi** [comment]
@jfrazelle yes, I noticed problem with seccomp as well. The old code moved and now there are duplicates for seccomp loading. Fill fix so it only uses `profiles/seccomp`.

**Comment by jfrazelle** [comment]
ya the daefault profile in daemon is using the wrong seccomp type, it should be using the type in engine-api

**Comment by tonistiigi** [comment]
#21344 should fix the ci errors

**Comment by jfrazelle** [comment]
this is so cool  LGTM

**Comment by icecrime** [comment]
Amazing :open_mouth:

**Comment by thaJeztah** [comment]
@runcom PTAL - tests are green now :green_heart:

**Comment by icecrime** [comment]
I think we're good to merge, thanks :+1: LGTM

**Pull request merged**
