### PR TITLE
Bump hcsshim to get some fixes.

### PR DESCRIPTION
**Pull request by cpuguy83**
closes https://github.com/moby/moby/pull/42269

This also requires bumping winio.

This addresses some customer issues for us.

### CODE REVIEW

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
Heh, looks like you lost a small race with @katiewasnothere / #42269, although you've also updated go-winio here (but that's the only difference I see).

**Review by thaJeztah — APPROVED** [review]
LGTM if CI is running again; windows CI is currently failing (is being worked on)

**Comment by thaJeztah** [comment]
@cpuguy83 does this need backporting? (if so, also needs https://github.com/moby/moby/pull/41689)

**Comment by olljanat** [comment]
> This addresses some customer issues for us.

@cpuguy83 @katiewasnothere any possibility to open up about which kind of which kind of issue(s) are expected to be fixed by this?

**Comment by cpuguy83** [comment]
@olljanat Specific case is too much logging in errors.

**Comment by thaJeztah** [comment]
Ok this looks like a regression / change in behavior:

```
=== RUN   TestDockerSuite/TestExecAPIStartInvalidCommand
    --- FAIL: TestDockerSuite/TestExecAPIStartInvalidCommand (1.97s)
        docker_api_exec_test.go:270: assertion failed: 500 (resp.StatusCode int) != 400 (code int): response body: {"message":"container 163342b8273daefbf14ee3cae8f02bdc53ca085e76684c15c0c64bccc07b7fcb encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)"}
```

Does hcsshim return a `NotFound` error, and do we translate that to `HTTP 400` ?
I _think_ 400 is the correct code for this case, so we should updated the test to
check for `400` or `500` errors

But we should update our API docs to reflect that a 400 error can be returned;
it currently only shows 404 or 500, no other errors.

Screenshot 2021-04-09 at 14 36 41

**Comment by thaJeztah** [comment]
Ok this looks like a regression / change in behavior:

```
=== RUN   TestDockerSuite/TestExecAPIStartInvalidCommand
    --- FAIL: TestDockerSuite/TestExecAPIStartInvalidCommand (1.97s)
        docker_api_exec_test.go:270: assertion failed: 500 (resp.StatusCode int) != 400 (code int): response body: {"message":"container 163342b8273daefbf14ee3cae8f02bdc53ca085e76684c15c0c64bccc07b7fcb encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)"}
```

Does hcsshim return a `NotFound` error, and do we translate that to `HTTP 400` ?
I _think_ 400 is the correct code for this case, so we should updated the test to
check for `400` or `500` errors

But we should update our API docs to reflect that a 400 error can be returned;
it currently only shows 404 or 500, no other errors.

Screenshot 2021-04-09 at 14 36 41

**Comment by thaJeztah** [comment]
Hmm... funny, so looking at the test, older API versions could return a `404` in the test (that _definitely_ was a bug: "command not found" !== "container not found"); https://github.com/moby/moby/blob/08e67904c9f7f7e70d4c3bb688d05301f5fdf7e4/integration-cli/docker_api_exec_test.go#L195-L199

**Comment by thaJeztah** [comment]
Actually thinking now if 400 _is_ correct; the request itself for this case (_start_ a container) is valid, but the container configuration is invalid, so 🤷‍♂️ depends on how you look at it I guess.

**Comment by thaJeztah** [comment]
I suspect the problem is here; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/daemon/errors.go#L141-L147


Looking at the error message returned (wrapped for readability);

```
container 163342b8273daefbf14ee3cae8f02bdc53ca085e76684c15c0c64bccc07b7fcb
encountered an error during hcsshim::System::CreateProcess:
failure in a Windows system call:
The system cannot find the file specified. (0x2)
```

✅  The string _does_ contain `system cannot find the file specified`, which we match in that function: https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/daemon/errors.go#L147
❌ The string does _not_ contain `cmd` ([`invalid`](https://github.com/moby/moby/blob/08e67904c9f7f7e70d4c3bb688d05301f5fdf7e4/integration-cli/docker_api_exec_test.go#L194)), and because of that, ` contains(errDesc, cmd)` won't match; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/daemon/errors.go#L144

Erm... so actually that second is not true (for some reason); it _does_ match; it looks for _entrypoint_ (perhaps that's an empty string, so will result in "match anything"; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/daemon/exec.go#L270). Possibly we can find what it has set for `Entrypoint` and `Argss`, because we trigger an event; https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/daemon/exec.go#L183

And when we _do_ match, we return a `startInvalidConfigError(errDesc)` error, which is an `errdefs.InvalidParameter()` ( -> 400). https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/daemon/errors.go#L150


So was it previously broken? Is it broken on Linux (if we return a 500 there)?

**Comment by thaJeztah** [comment]
@cpuguy83 could you have a peek at the failures? (I tried finding what's causing it in my comment above)

**Comment by cpuguy83** [comment]
It seems like specifically because we took out the extra error details the error check does not match anymore.

**Comment by thaJeztah** [comment]
Wait.. why is this failing? Broken package? https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-42270/3/pipeline/224

```
[2021-04-14T23:12:37.016Z] #22 43.99       copying Cython/Utility/CppSupport.cpp -> build/lib.linux-aarch64-3.7/Cython/Utility
[2021-04-14T23:12:37.016Z] #22 43.99       running build_ext
[2021-04-14T23:12:37.016Z] #22 43.99       building 'Cython.Plex.Scanners' extension
[2021-04-14T23:12:37.016Z] #22 43.99       creating build/temp.linux-aarch64-3.7
[2021-04-14T23:12:37.016Z] #22 43.99       creating build/temp.linux-aarch64-3.7/tmp
[2021-04-14T23:12:37.016Z] #22 43.99       creating build/temp.linux-aarch64-3.7/tmp/pip-install-jasgbmp7
[2021-04-14T23:12:37.016Z] #22 43.99       creating build/temp.linux-aarch64-3.7/tmp/pip-install-jasgbmp7/Cython
[2021-04-14T23:12:37.016Z] #22 43.99       creating build/temp.linux-aarch64-3.7/tmp/pip-install-jasgbmp7/Cython/Cython
[2021-04-14T23:12:37.016Z] #22 43.99       creating build/temp.linux-aarch64-3.7/tmp/pip-install-jasgbmp7/Cython/Cython/Plex
[2021-04-14T23:12:37.016Z] #22 43.99       aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c /tmp/pip-install-jasgbmp7/Cython/Cython/Plex/Scanners.c -o build/temp.linux-aarch64-3.7/tmp/pip-install-jasgbmp7/Cython/Cython/Plex/Scanners.o
[2021-04-14T23:12:37.016Z] #22 43.99       /tmp/pip-install-jasgbmp7/Cython/Cython/Plex/Scanners.c:21:10: fatal error: Python.h: No such file or directory
[2021-04-14T23:12:37.016Z] #22 43.99        #include "Python.h"
[2021-04-14T23:12:37.016Z] #22 43.99                 ^~~~~~~~~~
[2021-04-14T23:12:37.016Z] #22 43.99       compilation terminated.
[2021-04-14T23:12:37.016Z] #22 43.99       error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
[2021-04-14T23:12:37.016Z] #22 43.99
[2021-04-14T23:12:37.016Z] #22 43.99       ----------------------------------------
[2021-04-14T23:12:37.016Z] #22 43.99   Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jasgbmp7/Cython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-if5qclwe/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-_dtiuyfw --compile" failed with error code 1 in /tmp/pip-install-jasgbmp7/Cython/
[2021-04-14T23:12:37.016Z] #22 43.99
[2021-04-14T23:12:37.016Z] #22 43.99   ----------------------------------------
[2021-04-14T23:12:37.016Z] #22 44.08 Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_dtiuyfw --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython" failed with error code 1 in None
[2021-04-14T23:12:37.592Z] #22 ERROR: executor failed running [/bin/sh -c pip3 install yamllint==1.16.0]: exit code: 1
```


Let me restart

**Comment by cpuguy83** [comment]
This one I've seen a couple of time srecently, but seems like a newly introduced problem (just not on this PR, I think?)

```
--- FAIL: TestContainerKillOnDaemonStart (14.48s)
    daemon_test.go:46: [dab2d17437a7d] failed to start daemon with arguments [--data-root /go/src/github.com/docker/docker/bundles/test-integration/TestContainerKillOnDaemonStart/dab2d17437a7d/root --exec-root /tmp/dxr/dab2d17437a7d --pidfile /go/src/github.com/docker/docker/bundles/test-integration/TestContainerKillOnDaemonStart/dab2d17437a7d/docker.pid --userland-proxy=true --containerd-namespace dab2d17437a7d --containerd-plugins-namespace dab2d17437a7dp --containerd /var/run/docker/containerd/containerd.sock --host unix:///tmp/docker-integration/dab2d17437a7d.sock --debug --storage-driver overlay2] : [dab2d17437a7d] daemon exited during startup: exit status 1
    daemon_test.go:38: assertion failed: error is not nil: Cannot connect to the Docker daemon at unix:///tmp/docker-integration/dab2d17437a7d.sock. Is the docker daemon running?
```


This one looks legit, I don't think I've seen that.
```
=== RUN   TestDockerSuite/TestRunTwoConcurrentContainers
    --- FAIL: TestDockerSuite/TestRunTwoConcurrentContainers (64.13s)
        docker_cli_run_test.go:811: assertion failed: error is not nil: 
            Command:  d:\CI\PR-42270\4\binary\docker.exe run busybox sleep 2
            ExitCode: 125
            Error:    exit status 125
            Stdout:   
            Stderr:   d:\CI\PR-42270\4\binary\docker.exe: Error response from daemon: hcsshim::PrepareLayer - failed failed in Win32: The device is not ready. (0x15).
            
            
            Failures:
            ExitCode was 125 expected 0
            Expected no error
```

**Comment by cpuguy83** [comment]
`TestContainerKillOnDaemoNStart` looks like a libnetwork issue:


```
time="2021-04-15T13:05:15.796975427Z" level=debug msg="Cleaning up old mountid : done."
failed to start daemon: Error initializing network controller: error obtaining controller instance: unable to add return rule in DOCKER-ISOLATION-STAGE-2 chain:  (iptables failed: iptables --wait -A DOCKER-ISOLATION-STAGE-2 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tianon - good to go?

**Review by tianon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
