### PR TITLE
Fix typos: remove duplicated "the"

### PR DESCRIPTION
**Pull request by ohbarye**
**- What I did**

I just fixed typos of duplicated "the", which commonly happen. 

**- How I did it**

`s/the the /the /g`

**- How to verify it**

I believe the diff looks enough clear.

**- Description for the changelog**

None.

**- A picture of a cute animal (not mandatory but encouraged)**

image

<image src="https://user-images.githubusercontent.com/1811616/40176639-0ce88822-5a17-11e8-8ae7-244364e84b4f.png" width="400px">

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Please sign the commit with your real name

**Comment by ohbarye** [comment]
@AkihiroSuda 
Updated my sign with my real name.

**Comment by thaJeztah** [comment]
@AkihiroSuda looks updated now (thanks!)

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
```
15:26:57 Wiping out workspace first.
15:27:21 java.nio.file.FileSystemException: \gopath\src\github.com\docker\docker\integration-cli: The process cannot access the file because it is being used by another process.
```

**Comment by thaJeztah** [comment]
Ah, yes, that generator is non-deterministic 😞 

```
09:35:25 The swagger spec at "api/swagger.yaml" is valid against swagger specification 2.0
09:35:27 The result of hack/generate-swagger-api.sh differs
09:35:27 
```

```patch
diff --git a/api/types/container/container_wait.go b/api/types/container/container_wait.go
index 9e3910a6b..06b0f0207 100644
--- a/api/types/container/container_wait.go
+++ b/api/types/container/container_wait.go
@@ -7,14 +7,6 @@ package container
 // See hack/generate-swagger-api.sh
 // ----------------------------------------------------------------------------
 
-// ContainerWaitOKBodyError container waiting error, if any
-// swagger:model ContainerWaitOKBodyError
-type ContainerWaitOKBodyError struct {
-
-	// Details of an error
-	Message string `json:"Message,omitempty"`
-}
-
 // ContainerWaitOKBody OK response to ContainerWait operation
 // swagger:model ContainerWaitOKBody
 type ContainerWaitOKBody struct {
@@ -27,3 +19,11 @@ type ContainerWaitOKBody struct {
 	// Required: true
 	StatusCode int64 `json:"StatusCode"`
 }
+
+// ContainerWaitOKBodyError container waiting error, if any
+// swagger:model ContainerWaitOKBodyError
+type ContainerWaitOKBodyError struct {
+
+	// Details of an error
+	Message string `json:"Message,omitempty"`
+}
```

```
09:35:27 Please update api/swagger.yaml with any api changes, then 
09:35:27 run `hack/generate-swagger-api.sh`.
```

**Comment by thaJeztah** [comment]
Ran the swagger-gen locally, and everything looks to be ok

**Pull request merged**
