### PR TITLE
[DO NOT MERGE] Swarm tests debug

### PR DESCRIPTION
**Pull request by kolyshkin**
Just playing with TestSwarmClusterRotateUnlockKey a bit

### CODE REVIEW

**Comment by kolyshkin** [comment]
Found a possible cause. Testing a fix (which makes sense for other tests, too, and will be applied if proved usable).

**Comment by kolyshkin** [comment]
Out of 5 runs, got a TestAPISwarmLeaderElection failure on z (I haven't patched this test yet). Guess it makes sense to patch all the swarm tests.

**Comment by kolyshkin** [comment]
Runs 1-5, no failures.

Run 6, failure in TestSwarmLockUnlockCluster:
```
00:25:37.850 START: docker_cli_swarm_test.go:1143: DockerSwarmSuite.TestSwarmLockUnlockCluster
00:25:37.850 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:25:37.851 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:25:37.851 
00:25:37.851 [d67a16aac9c2d] waiting for daemon to start
00:25:38.353 [d67a16aac9c2d] daemon started
00:25:38.353 
00:25:39.153 [d598c4764df87] waiting for daemon to start
00:25:39.655 [d598c4764df87] daemon started
00:25:39.655 
00:25:40.440 [d53d8f36873f9] waiting for daemon to start
00:25:40.941 [d53d8f36873f9] daemon started
00:25:40.941 
00:25:46.731 [d598c4764df87] exiting daemon
00:25:46.731 [d598c4764df87] waiting for daemon to start
00:25:47.233 [d598c4764df87] daemon started
00:25:47.233 
00:25:56.355 [d598c4764df87] exiting daemon
00:25:56.698 [d67a16aac9c2d] exiting daemon
00:25:56.698 [d67a16aac9c2d] waiting for daemon to start
00:25:57.200 [d67a16aac9c2d] daemon started
00:25:57.200 
00:26:13.697 [d53d8f36873f9] exiting daemon
00:26:13.697 [d53d8f36873f9] waiting for daemon to start
00:26:14.200 [d53d8f36873f9] daemon started
00:26:14.200 
00:26:18.372 [d598c4764df87] waiting for daemon to start
00:26:18.874 [d598c4764df87] daemon started
00:26:18.874 
00:26:24.997 [d598c4764df87] exiting daemon
00:26:24.998 [d598c4764df87] waiting for daemon to start
00:26:25.499 [d598c4764df87] daemon started
00:26:25.499 
00:26:26.037 [d67a16aac9c2d] exiting daemon
00:26:26.038 [d67a16aac9c2d] waiting for daemon to start
00:26:46.129 [d67a16aac9c2d] daemon started
00:26:46.130 
00:26:46.240 docker_cli_swarm_test.go:1198:
00:26:46.246     checkSwarmLockedToUnlocked(c, d)
00:26:46.246 docker_cli_swarm_test.go:1017:
00:26:46.254     c.Assert(getNodeStatus(c, d), checker.Equals, swarm.LocalNodeStateActive)
00:26:46.255 ... obtained swarm.LocalNodeState = "pending"
00:26:46.255 ... expected swarm.LocalNodeState = "active"
00:26:46.255 
00:26:46.260 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:26:46.272 [d67a16aac9c2d] exiting daemon
00:26:46.276 [d598c4764df87] exiting daemon
00:26:51.285 [d53d8f36873f9] exiting daemon
00:26:51.289 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	5.028s
00:26:51.289 
00:26:51.289 FAIL: docker_cli_swarm_test.go:1143: DockerSwarmSuite.TestSwarmLockUnlockCluster
00:26:51.289 
```

**Comment by kolyshkin** [comment]
Runs 7-9: no failures.

Run 10/60 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

Failure in `TestAPISwarmLeaderElection` on power:
```
00:20:07.222 
00:20:07.223 START: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:20:07.223 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:20:07.223 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:20:07.223 
00:20:07.292 [d88e13dd68846] waiting for daemon to start
00:20:07.727 [d88e13dd68846] daemon started
00:20:07.727 
00:20:08.300 [d29173e92c51e] waiting for daemon to start
00:20:08.803 [d29173e92c51e] daemon started
00:20:08.803 
00:20:10.963 [dbef89344f8cd] waiting for daemon to start
00:20:11.466 [dbef89344f8cd] daemon started
00:20:11.466 
00:20:12.854 [d88e13dd68846] exiting daemon
00:20:32.857 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
00:20:32.857 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:20:32.858 Daemon d88e13dd68846 is not started
00:20:34.028 [d29173e92c51e] exiting daemon
00:20:35.272 [dbef89344f8cd] exiting daemon
00:20:35.279 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	2.423s
00:20:35.280 
00:20:35.280 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:20:35.280 
```

**Comment by kolyshkin** [comment]
Run 11 -- no failures.

Run 12/60 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

Failure on experimental in `TestAPISwarmLeaderElection`:

00:13:08.317 
00:13:08.317 START: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:13:08.317 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:13:08.317 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:13:08.317 
00:13:08.318 [d9f72f66fb991] waiting for daemon to start
00:13:08.821 [d9f72f66fb991] daemon started
00:13:08.821 
00:13:09.697 [ddbcc5ef647f4] waiting for daemon to start
00:13:10.198 [ddbcc5ef647f4] daemon started
00:13:10.199 
00:13:10.980 [d7099eab3e0b0] waiting for daemon to start
00:13:11.487 [d7099eab3e0b0] daemon started
00:13:11.487 
00:13:12.569 [d9f72f66fb991] exiting daemon
00:13:32.571 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
00:13:32.571 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:13:32.572 Daemon d9f72f66fb991 is not started
00:13:37.578 [ddbcc5ef647f4] exiting daemon
00:13:42.586 [d7099eab3e0b0] exiting daemon
00:13:42.590 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	10.019s
00:13:42.590 
00:13:42.590 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:13:42.591

**Comment by kolyshkin** [comment]
Run 15/60 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

Got a _very_ different failure in `TestSwarmClusterRotateUnlockKey` on power, which I have never ever seen before (meaning at least my change is worth something):

00:33:54.689 
00:33:54.689 START: docker_cli_swarm_test.go:1376: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:33:54.689 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:33:54.689 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:33:54.689 
00:33:54.691 [ddf250c0e5961] waiting for daemon to start
00:33:55.194 [ddf250c0e5961] daemon started
00:33:55.194 
00:33:55.774 [d98a6bc2bdfa5] waiting for daemon to start
00:33:56.274 [d98a6bc2bdfa5] daemon started
00:33:56.274 
00:33:57.415 [d9345e9fd6025] waiting for daemon to start
00:33:57.916 [d9345e9fd6025] daemon started
00:33:57.916 
00:34:04.189 [d98a6bc2bdfa5] exiting daemon
00:34:04.191 [d98a6bc2bdfa5] waiting for daemon to start
00:34:04.701 [d98a6bc2bdfa5] daemon started
00:34:04.702 
00:34:09.914 [d9345e9fd6025] exiting daemon
00:34:09.915 [d9345e9fd6025] waiting for daemon to start
00:34:10.417 [d9345e9fd6025] daemon started
00:34:10.417 
00:34:28.641 [d98a6bc2bdfa5] exiting daemon
00:34:28.642 [d98a6bc2bdfa5] waiting for daemon to start
00:34:29.145 [d98a6bc2bdfa5] daemon started
00:34:29.145 
00:34:42.851 assertion failed: 
00:34:42.851 Command:  /usr/local/cli/docker --host unix:///tmp/docker-integration/d98a6bc2bdfa5.sock swarm unlock
00:34:42.851 ExitCode: 0
00:34:42.851 Error:    <nil>
00:34:42.851 Stdout:   
00:34:42.851 Stderr:   
00:34:42.851 
00:34:42.851 Failures:
00:34:42.851 ExitCode was 0 expected 1
00:34:42.851 Expected stderr to contain "invalid key"
00:34:42.851 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:34:43.199 [ddf250c0e5961] exiting daemon
00:34:49.388 [d98a6bc2bdfa5] exiting daemon
00:34:49.395 [d9345e9fd6025] exiting daemon
00:34:49.402 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	6.551s
00:34:49.402 
00:34:49.402 FAIL: docker_cli_swarm_test.go:1376: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:34:49.402 

Taking a look...

**Comment by kolyshkin** [comment]
> Got a very different failure <...> Taking a look

OK, so d2 (aka d98a6bc2bdfa5) was super slow to rotate the log, it took it 44 seconds:

d1.log:time="2018-10-27T06:18:49.680102306Z" level=debug msg="successfully rotated KEK" module=node node.id=24lhcu8vugj7z6bg0catnlg36 node.role=swarm-manager
d1.log:time="2018-10-27T06:18:49.858709421Z" level=debug msg="successfully rotated KEK" module=node node.id=24lhcu8vugj7z6bg0catnlg36 node.role=swarm-manager
d2.log:time="2018-10-27T06:18:49.673122322Z" level=debug msg="successfully rotated KEK" module=node node.id=uol4y3uzb2svs4qb8a81f5dl6 node.role=swarm-manager
**d2.log:time="2018-10-27T06:19:33.352306142Z" level=debug msg="successfully rotated KEK" module=node node.id=uol4y3uzb2svs4qb8a81f5dl6 node.role=swarm-manager** <<< THIS
d3.log:time="2018-10-27T06:18:49.674384323Z" level=debug msg="successfully rotated KEK" module=node node.id=i4q30y0qd01230auxt5q9wt0t node.role=swarm-manager
d3.log:time="2018-10-27T06:18:49.854673880Z" level=debug msg="successfully rotated KEK" module=node node.id=i4q30y0qd01230auxt5q9wt0t node.role=swarm-manager

The timeout in the test is 3 seconds. Swarm docs say it can take up to a few minutes to rotate the unlock key in a cluster.

**Comment by kolyshkin** [comment]
So, it looks like my fix is helping, but not ultimately fixes issues with swarm tests, of which we frequently have false positives. Out of 15 runs, with fixes from this PR, we have
```
Failures so far:
* TestSwarmLockUnlockCluster      ▓▓ 
* TestAPISwarmLeaderElection      ▓▓
* TestSwarmClusterRotateUnlockKey ▓
```
 Now the question is: do we need those tests in Moby? // cc @thaJeztah

**Comment by kolyshkin** [comment]
I kinda know how to fix that other (new) failure in `TestSwarmClusterRotateUnlockKey` -- instead of the timeout, we need to wait for the key to be rotated. The question is, how do we know the key is rotated, without unlocking the cluster first. My only idea is to sniff the daemon logs, which looks ugly.

**Comment by thaJeztah** [comment]
> Now the question is: do we need those tests in Moby?

This repository is the integration point of the dockerd daemon with the swarmkit code, so I think it's logical to test swarmkit functionality here. That said, if these make more sense as an e2e test, perhaps that's an option as well.

**Comment by kolyshkin** [comment]
Run 16/60 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
    
Failure on powerpc, test case `TestSwarmClusterRotateUnlockKey` (the one I was hunting for):

00:35:48.261 
00:35:48.261 START: docker_cli_swarm_test.go:1376: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:35:48.262 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:35:48.262 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:35:48.262 
00:35:48.264 [de7fa33178138] waiting for daemon to start
00:35:48.770 [de7fa33178138] daemon started
00:35:48.770 
00:35:49.364 [d86cf8f03ead0] waiting for daemon to start
00:35:49.867 [d86cf8f03ead0] daemon started
00:35:49.867 
00:35:51.055 [d3e78d11a106e] waiting for daemon to start
00:35:51.557 [d3e78d11a106e] daemon started
00:35:51.557 
00:35:58.025 [d86cf8f03ead0] exiting daemon
00:35:58.028 [d86cf8f03ead0] waiting for daemon to start
00:35:58.517 [d86cf8f03ead0] daemon started
00:35:58.517 
00:36:03.751 [d3e78d11a106e] exiting daemon
00:36:03.753 [d3e78d11a106e] waiting for daemon to start
00:36:04.256 [d3e78d11a106e] daemon started
00:36:04.256 
00:36:29.264 docker_cli_swarm_test.go:1454:
00:36:29.278     c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
00:36:29.279 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000b6b8c0), Stderr:[]uint8(nil)} ("exit status 1")
00:36:29.279 ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
00:36:29.280 
00:36:29.280 
00:36:29.280 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:36:29.622 [de7fa33178138] exiting daemon
00:36:34.656 [d86cf8f03ead0] exiting daemon
00:36:34.657 [d3e78d11a106e] exiting daemon
00:36:34.658 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	5.368s
00:36:34.659 
00:36:34.659 FAIL: docker_cli_swarm_test.go:1376: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:36:34.659

**Comment by kolyshkin** [comment]
> This repository is the integration point

Make sense. If these tests were working. They do not, unfortunately. I am trying to fix that, with not much luck so far.

**Comment by kolyshkin** [comment]
Run 18/60 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

Failure on power, `TestAPISwarmLeaderElection`

00:11:55.420 
00:11:55.420 START: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:11:55.421 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:11:55.421 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:11:55.421 
00:11:55.489 [d38e3c8be7c55] waiting for daemon to start
00:11:55.925 [d38e3c8be7c55] daemon started
00:11:55.925 
00:11:56.528 [d79776d753327] waiting for daemon to start
00:11:57.031 [d79776d753327] daemon started
00:11:57.032 
00:11:59.193 [d3223dbf271f8] waiting for daemon to start
00:11:59.699 [d3223dbf271f8] daemon started
00:11:59.699 
00:12:01.074 [d38e3c8be7c55] exiting daemon
00:12:21.076 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
00:12:21.077 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:12:21.077 Daemon d38e3c8be7c55 is not started
00:12:22.245 [d79776d753327] exiting daemon
00:12:28.418 [d3223dbf271f8] exiting daemon
00:12:28.423 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	7.347s
00:12:28.424 
00:12:28.424 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:12:28.424

**Comment by kolyshkin** [comment]
Run 19/60 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

Two faiures, one on power in `TestAPISwarmLeaderElection`:

00:19:42.491 
00:19:42.491 START: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:19:42.491 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:19:42.491 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:19:42.491 
00:19:42.493 [d724a4bdcf700] waiting for daemon to start
00:19:42.996 [d724a4bdcf700] daemon started
00:19:42.996 
00:19:43.615 [dd109cf60cb89] waiting for daemon to start
00:19:44.118 [dd109cf60cb89] daemon started
00:19:44.118 
00:19:45.293 [d82deaefcb384] waiting for daemon to start
00:19:45.795 [d82deaefcb384] daemon started
00:19:45.795 
00:19:47.188 [d724a4bdcf700] exiting daemon
00:20:07.191 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
00:20:07.191 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:20:07.191 Daemon d724a4bdcf700 is not started
00:20:12.201 [dd109cf60cb89] exiting daemon
00:20:13.405 [d82deaefcb384] exiting daemon
00:20:13.412 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	6.221s
00:20:13.412 
00:20:13.412 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
00:20:13.412 

and a new failure on z, `TestSwarmPublishAdd`:

00:35:47.832 
00:35:47.832 START: docker_cli_swarm_test.go:274: DockerSwarmSuite.TestSwarmPublishAdd
00:35:47.832 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:35:47.832 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:35:47.832 
00:35:47.834 [d3f9f547e33bb] waiting for daemon to start
00:35:48.346 [d3f9f547e33bb] daemon started
00:35:48.346 
00:35:49.973 docker_cli_swarm_test.go:286:
00:35:49.981     c.Assert(err, checker.IsNil, check.Commentf("%s", out))
00:35:49.985 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000617da0), Stderr:[]uint8(nil)} ("exit status 1")
00:35:49.986 ... Error response from daemon: rpc error: code = Unknown desc = update out of sequence
00:35:49.986 
00:35:49.986 
00:35:49.986 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:35:51.903 [d3f9f547e33bb] exiting daemon
00:35:51.911 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	1.928s
00:35:51.911 
00:35:51.911 FAIL: docker_cli_swarm_test.go:274: DockerSwarmSuite.TestSwarmPublishAdd
00:35:51.912

**Comment by kolyshkin** [comment]
Some previous findings on `TestAPISwarmLeaderElection` are in https://github.com/moby/moby/pull/37833

**Comment by kolyshkin** [comment]
Run 21/60 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

Failure on power in `TestSwarmClusterRotateUnlockKey`:

00:33:55.218 
00:33:55.218 START: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:33:55.218 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:33:55.218 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:33:55.218 
00:33:55.223 [db8afafbf2e95] waiting for daemon to start
00:33:55.726 [db8afafbf2e95] daemon started
00:33:55.726 
00:33:56.313 [d178b2e905cdf] waiting for daemon to start
00:33:56.833 [d178b2e905cdf] daemon started
00:33:56.833 
00:33:57.985 [db1bfab8e751e] waiting for daemon to start
00:33:58.488 [db1bfab8e751e] daemon started
00:33:58.488 
00:34:04.759 [d178b2e905cdf] exiting daemon
00:34:04.761 [d178b2e905cdf] waiting for daemon to start
00:34:05.266 [d178b2e905cdf] daemon started
00:34:05.266 
00:34:10.502 [db1bfab8e751e] exiting daemon
00:34:10.503 [db1bfab8e751e] waiting for daemon to start
00:34:11.006 [db1bfab8e751e] daemon started
00:34:11.006 
00:34:36.221 docker_cli_swarm_test.go:1379:
00:34:36.235     c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
00:34:36.236 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000627e60), Stderr:[]uint8(nil)} ("exit status 1")
00:34:36.236 ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
00:34:36.236 
00:34:36.236 
00:34:36.237 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:34:36.590 [db8afafbf2e95] exiting daemon
00:34:41.603 [d178b2e905cdf] exiting daemon
00:34:41.612 [db1bfab8e751e] exiting daemon
00:34:41.618 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	5.382s
00:34:41.618 
00:34:41.618 FAIL: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:34:41.619

**Comment by kolyshkin** [comment]
Failure on power, `TestSwarmClusterRotateUnlockKey`:

00:33:55.218 
00:33:55.218 PASS: docker_cli_swarm_test.go:1834: DockerSwarmSuite.TestSwarmClusterEventsType	7.332s
00:33:55.218 
00:33:55.218 START: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:33:55.218 START: check_test.go:320: DockerSwarmSuite.SetUpTest
00:33:55.218 PASS: check_test.go:320: DockerSwarmSuite.SetUpTest	0.000s
00:33:55.218 
00:33:55.223 [db8afafbf2e95] waiting for daemon to start
00:33:55.726 [db8afafbf2e95] daemon started
00:33:55.726 
00:33:56.313 [d178b2e905cdf] waiting for daemon to start
00:33:56.833 [d178b2e905cdf] daemon started
00:33:56.833 
00:33:57.985 [db1bfab8e751e] waiting for daemon to start
00:33:58.488 [db1bfab8e751e] daemon started
00:33:58.488 
00:34:04.759 [d178b2e905cdf] exiting daemon
00:34:04.761 [d178b2e905cdf] waiting for daemon to start
00:34:05.266 [d178b2e905cdf] daemon started
00:34:05.266 
00:34:10.502 [db1bfab8e751e] exiting daemon
00:34:10.503 [db1bfab8e751e] waiting for daemon to start
00:34:11.006 [db1bfab8e751e] daemon started
00:34:11.006 
00:34:36.221 docker_cli_swarm_test.go:1379:
00:34:36.235     c.Assert(err, checker.IsNil, check.Commentf("%s", outs))
00:34:36.236 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc000627e60), Stderr:[]uint8(nil)} ("exit status 1")
00:34:36.236 ... Error response from daemon: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
00:34:36.236 
00:34:36.236 
00:34:36.237 START: check_test.go:347: DockerSwarmSuite.TearDownTest
00:34:36.590 [db8afafbf2e95] exiting daemon
00:34:41.603 [d178b2e905cdf] exiting daemon
00:34:41.612 [db1bfab8e751e] exiting daemon
00:34:41.618 PASS: check_test.go:347: DockerSwarmSuite.TearDownTest	5.382s
00:34:41.618 
00:34:41.618 FAIL: docker_cli_swarm_test.go:1316: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
00:34:41.619

**Comment by olljanat** [comment]
Derek add label: invalid

**Comment by vdemeester** [comment]
@kolyshkin giving the "status" and the time without activity on this PR, I'm gonna close it :angel:

**Comment by kolyshkin** [comment]
Right, thanks. The good part of it is already merged in #38127, the rest is just [futile] attempts to figure out what's going on with flaky swarm tests.

**Comment by thaJeztah** [comment]
Perhaps we could use `testing.Verbose()` to enable additional debugging on some tests (https://splice.com/blog/lesser-known-features-go-test/)

**Pull request closed without merging**
