### PR TITLE
1.12.1 docs cherry picks

### PR DESCRIPTION
**Pull request by thaJeztah**
docs cherry picks of:

https://github.com/docker/docker/pull/25135 (cc5debcb2e8621358721eb860c07f33f8b83d684)
https://github.com/docker/docker/pull/25420 (e56dd0e0e7d2eb921390c7aaff091b8b613c4c6b)
https://github.com/docker/docker/pull/25614 (e715ca506f41b22cde21187328fcb416cec5e6a2)
https://github.com/docker/docker/pull/25669 (43c8cc7bb4dd42bebabf68e509a3596ef7a642cd)
https://github.com/docker/docker/pull/25673 (a9b08f3102e946df44337deb65c99b41570754d1)
https://github.com/docker/docker/pull/25700 (078e2aa1571ad402f0a9599e6fac2286a3d35f54)
https://github.com/docker/docker/pull/25705 (aab101a770a88cdbde5012dc7eb5b4439cf57192)
https://github.com/docker/docker/pull/25706 (bde35ef18a408a297b960c439dc029cfb5e15464)
https://github.com/docker/docker/pull/25707 (7cdd693d5d2094f73383145eb74d81c6b9bb9b24)
https://github.com/docker/docker/pull/25710 (8d5818a6931db9d0acd4a6663815cd317da1bb6b)
https://github.com/docker/docker/pull/25712 (75e60fbe09f6065ed095671f98713d862c466858)
https://github.com/docker/docker/pull/25753 (c59bc537274aa7f4dc9702ea08c349c71a024b39)
https://github.com/docker/docker/pull/25757 (9eb2ec799eb37210dee5183ace375e480bbfd8aa)
https://github.com/docker/docker/pull/25758 (69e481af4e1fec65629c6ea4eb74fc58f5abc932)

ping @sfsmithcha PTAL

### CODE REVIEW

**Comment by sfsmithcha** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :angel:

**Comment by thaJeztah** [comment]
ping @tiborvass please merge whenever you're ready for this :smile:

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
