### PR TITLE
adding message option to the import subcommand

### LINKED ISSUE #15710: Import command does not allow messages
We are using Docker to preserve the state of an existing application, so we don't use Dockerfiles exactly. When a running container is in a state we are satisfied with, we commit the container using `docker commit`. However, due to the 127 layer limit imposed by AUFS, we can't do this indefinitely. It is possible to squash the image by exporting/importing, but we lose the commit history that way.

When importing an image from disk, it would be nice to be able to specify a commit message. That way, we could set the message on the imported single layer to contain the commit messages from the squashed layers. 

The easiest way to do this is to simply make an option for a message, similar to `docker commit`:

```
cat test.tar | docker import -m 'Release 0.2
    Installing new plugins
    Updating dependencies for user plugin
    Creating new home directory' -  newimage
```

### PR DESCRIPTION
**Pull request by monitorjbl**
Fixes #15710

### CODE REVIEW

**Comment by calavera** [comment]
@monitorjbl this is going to need integration tests under `integration-cli` and documentation.

**Comment by monitorjbl** [comment]
Sure thing, I just wanted to see verification jobs passed. They didn't, but I'm not sure if it was something I added or not.

**Comment by cpuguy83** [comment]
+1 test and we can get this in quickly.
Thanks!

**Comment by monitorjbl** [comment]
Sorry, I was at a conference this past weekend. I'll get tests added as soon as I can!

**Comment by calavera** [comment]
Thanks @monitorjbl, changes LGTM. I think you still need to add this flag to the man pages under `man`. But we should move this forward to docs review as soon as other maintainers give their lgtm.

**Comment by monitorjbl** [comment]
Whoops, forgot about the man page. I'll get that updated too.

**Comment by monitorjbl** [comment]
Added this option to the manpage for docker-import

**Comment by cpuguy83** [comment]
LGTM, failures are unrelated.
Moving to docs review.

**Comment by thaJeztah** [comment]
docs LGTM, thanks!

**Comment by SvenDowideit** [comment]
Docs LGTM - @calavera are you doing the merging?

**Comment by monitorjbl** [comment]
Awesome, thanks guys!

**Pull request merged**
