### PR TITLE
Bump v1.7.1

### PR DESCRIPTION
**Pull request by calavera**
Scheduled to be released Tuesday, July 7th.

RC1 will be pushed to test.docker.com momentarily along with rpms.

Please help with testing as this will be the official RC.

### CODE REVIEW

**Comment by tianon** [comment]
Shouldn't this have a few more of the commits from the milestone in it? (https://github.com/docker/docker/pulls?q=is%3Apr+milestone%3A1.7.1, especially the merged ones?)

**Comment by calavera** [comment]
@tianon yes, working on it. I wasn't sure if we opened this PR before or after having all the commits that go in the release, so I opened it already.

**Comment by tianon** [comment]
Fair enough, just checking! :+1: :heart:

**Comment by thaJeztah** [comment]
@calavera you'll mention when the RC is built and available for testing? (because I'm pointing people to this PR to watch)

**Comment by calavera** [comment]
@thaJeztah yes, still waiting for a few more PRs in the milestone before cutting the RC.

**Comment by lesgrossman** [comment]
getting eager to test.  is the RC ready?

**Comment by calavera** [comment]
@lesgrossman there are still a couple if remaining issues in the milestone.

**Comment by lesgrossman** [comment]
thanks for the update, continuing to wait patiently.

**Comment by calavera** [comment]
We have just pushed 1.7.1-rc1 to test.docker.com you can download with the following:

Ubuntu/Debian: curl -sSL https://test.docker.com/ubuntu | sh or curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.7.1-rc1
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.7.1-rc1
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.7.1-rc1
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.7.1-rc1.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.7.1-rc1.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.7.1-rc1.exe

Please test and make sure all links are working.

**Comment by lesgrossman** [comment]
Do we have rpms specific for centos 6.6 and redhat 6.6?

**Comment by calavera** [comment]
@lesgrossman the rpms take slightly longer to generate, but we'll post the links here as soon as they are ready

**Comment by lesgrossman** [comment]
@calavera  roger that, LMK  thanks again.

**Comment by tianon** [comment]
boot2docker 1.7.1-rc1 is at https://github.com/tianon/boot2docker/releases/tag/v1.7.1-rc1 :+1:

**Comment by jamshid** [comment]
What am I doing wrong? This works: `docker-machine upgrade dev` but fails with `--virtualbox-boot2docker-url`:

```
$ docker-machine -v
docker-machine version 0.3.0 (HEAD)

$ docker-machine upgrade --virtualbox-boot2docker-url https://github.com/tianon/boot2docker/releases/tag/v1.7.1-rc1 dev
Incorrect Usage.

Usage: docker-machine upgrade [arg...]

Upgrade a machine to the latest version of Docker

Description:
   Argument(s) are one or more machine names.
```

**Comment by thaJeztah** [comment]
@jamshid perhaps you could open an issue in the Machine repository to improve the docs? :+1:

**Comment by jfrazelle** [comment]
This is why we can't have nice things like RPMs .... https://github.com/CentOS/sig-cloud-instance-images/issues/24

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.1-rc1/centos-6/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc1/centos-6/SRPMS/docker-engine-1.7.1-0.1.rc1.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.1-rc1/centos-7/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc1/centos-7/SRPMS/docker-engine-1.7.1-0.1.rc1.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.1-rc1/fedora-20/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc1/fedora-20/SRPMS/docker-engine-1.7.1-0.1.rc1.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.1-rc1/fedora-21/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc1/fedora-21/SRPMS/docker-engine-1.7.1-0.1.rc1.fc21.src.rpm

**Fedora 22**
https://test.docker.com/rpm/1.7.1-rc1/fedora-22/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.fc22.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc1/fedora-22/SRPMS/docker-engine-1.7.1-0.1.rc1.fc22.src.rpm

**Comment by ssadams11** [comment]
RE: https://test.docker.com/rpm/1.7.1-rc1/centos-6/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.el6.x86_64.rpm

Install worked, but when I tried a dockerized meteor application, it failed to connect to the mongo container on the same host.  I ran the exact same experiment on ubuntu and it connects fine as usual using the same docker containers and commands. Mongo container reachable via curl on host and remote.

**Comment by Hebime** [comment]
RE: https://test.docker.com/rpm/1.7.1-rc1/centos-6/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.el6.x86_64.rpm

Uname -a: `2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Mar 10 17:01:00 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux`

I'm having the same issue as @ssadams11 
It would seem as if inter-container networking is not working. I set up a listening netcat on one container and from another I could not connect. Host to container works perfectly however.

**Comment by mavenugo** [comment]
@Hebime @ssadams11 I just tried it in CentOS 6.6, and inter-container connectivity is working fine.

```
$ wget https://test.docker.com/rpm/1.7.1-rc1/centos-6/RPMS/x86_64/docker-engine-1.7.1-0.1.rc1.el6.x86_64.rpm
$ sudo rpm -Uvh docker-engine-1.7.1-0.1.rc1.el6.x86_64.rpm
$ sudo docker version
Client version: 1.7.1-rc1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): fed8c39
OS/Arch (client): linux/amd64
Server version: 1.7.1-rc1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): fed8c39
OS/Arch (server): linux/amd64
$ uname -a
Linux localhost.localdomain 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Kindly note that my kernel version `2.6.32-504.8.1.el6.x86_64`. 
I had downgraded to this version earlier due to another issue (which I dont recall atm). @mrjana do you remember the specific issue that forced us to try this kernel version ?
`$ sudo yum install kernel*2.6.32-504.8*`

**Comment by mrjana** [comment]
@mavenugo Kernel panics in later RHEL 6.6 kernels when the container is stopped

**Comment by calavera** [comment]
We have just pushed 1.7.1-rc2 to test.docker.com you can download with the following:

Ubuntu/Debian: curl -sSL https://test.docker.com/ubuntu | sh or curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.7.1-rc2
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.7.1-rc2
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.7.1-rc2
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.7.1-rc2.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.7.1-rc2.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.7.1-rc2.exe

Please test and make sure all links are working.

*RPMs coming out soon.*

**Comment by tianon** [comment]
boot2docker: https://github.com/tianon/boot2docker/releases/tag/v1.7.1-rc2
(now including both XenServer Tools and Parallels Tools in addition to
VMware Tools and VirtualBox Guest Additions!)

**Comment by ekristen** [comment]
FWIW I can confirm that the commit https://github.com/calavera/docker/commit/6906fb0693eabb2cb7b84b9cfbaf203b9f8e2b59 has seemed to fix the registry authentication issue for private registries introduced in the 1.7.0 release.

**Comment by lesgrossman** [comment]
@calavera Unitil the RPMs are release.  should I use the binary?

@ekristen Interesting.  Can you point me to the documentation you used to stand up your private registry (assuming v2).  The docs at docker.com seem to be missing something.  Thanks in advance

**Comment by ekristen** [comment]
@lesgrossman I'm still using registry v1 and I wrote https://github.com/ekristen/docker-index, I'm still working on v2. Basically @lesgrossman on build you need to be sure that X-Registry-Config (not X-Registry-Auth, which is used elsewhere) is being set to the base64 encoding of the contents of `.dockercfg` 1.7.0 broke this, 1.7.1-rc2 has it fixed.

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.1-rc2/centos-6/RPMS/x86_64/docker-engine-1.7.1-0.2.rc2.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc2/centos-6/SRPMS/docker-engine-1.7.1-0.2.rc2.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.1-rc2/centos-7/RPMS/x86_64/docker-engine-1.7.1-0.2.rc2.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc2/centos-7/SRPMS/docker-engine-1.7.1-0.2.rc2.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.1-rc2/fedora-20/RPMS/x86_64/docker-engine-1.7.1-0.2.rc2.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc2/fedora-20/SRPMS/docker-engine-1.7.1-0.2.rc2.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.1-rc2/fedora-21/RPMS/x86_64/docker-engine-1.7.1-0.2.rc2.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc2/fedora-21/SRPMS/docker-engine-1.7.1-0.2.rc2.fc21.src.rpm

**Fedora 22**
https://test.docker.com/rpm/1.7.1-rc2/fedora-22/RPMS/x86_64/docker-engine-1.7.1-0.2.rc2.fc22.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc2/fedora-22/SRPMS/docker-engine-1.7.1-0.2.rc2.fc22.src.rpm

**Comment by lesgrossman** [comment]
@calavera Not sure if this matters, but after running the "curl -sSL https://test.docker.com/ubuntu | sh" on ubuntu 15.04 I needed to run "systemctl enable docker".  it'd be nice if this was done in the curl script.  just a  thought, I know trivial

**Comment by jfrazelle** [comment]
that is expected

**Comment by jfrazelle** [comment]
and will be fixed by the new debs in 1.8 its not possible now with our
universal debs

**Comment by lesgrossman** [comment]
@calavera let's see.   
1. fresh install cecntos 6.6 DVD selected minimal
2. enabled networking
3. yum update -y
4. curl download of 1.7.1 rc2
5. yum localinstall --nogpgcheck <rc2>
6. service docker start
7 reboot
8. docker version OK
9. docker info OK
10  docker run hello-world outputted as expected crashed VM

What else do you need if anything.  VM was in vbox.

**Comment by dmcgowan** [comment]
@lesgrossman looks like a file might have gotten corrupted in /var/lib/docker/trust (probably /var/lib/docker/trust/official.json), can you remove any files in that directory.

**Comment by lesgrossman** [comment]
@calavera seem for fix the "built" system.  rebuilt it with my procedures and there was no core dump.  continuing testing

**Comment by calavera** [comment]
thanks @lesgrossman, I really appreciate it.

Heads up, I just tagged RC3 that will be promoted to final release if everything goes as expected :scream_cat:

**Comment by calavera** [comment]
We have just pushed 1.7.1-rc3 to test.docker.com. You can download it with the following:

Ubuntu/Debian: curl -sSL https://test.docker.com | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.7.1-rc3
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.7.1-rc3
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.7.1-rc3
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.7.1-rc3.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.7.1-rc3.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.7.1-rc3.exe

Please test and make sure all links are working.

**Comment by tianon** [comment]
https://github.com/tianon/boot2docker/releases/tag/v1.7.1-rc3 :+1:

**Comment by lesgrossman** [comment]
@calavera Your welcome.  just trying to do my part, slowly getting more involved. LMK when the RPMs are available.  testing on ubuntu 15.04 now

**Comment by jfrazelle** [comment]
**RPMs**

**Centos 6/RHEL6**
https://test.docker.com/rpm/1.7.1-rc3/centos-6/RPMS/x86_64/docker-engine-1.7.1-0.3.rc3.el6.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc3/centos-6/SRPMS/docker-engine-1.7.1-0.3.rc3.el6.src.rpm

**Centos 7/RHEL7**
https://test.docker.com/rpm/1.7.1-rc3/centos-7/RPMS/x86_64/docker-engine-1.7.1-0.3.rc3.el7.centos.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc3/centos-7/SRPMS/docker-engine-1.7.1-0.3.rc3.el7.centos.src.rpm

**Fedora 20**
https://test.docker.com/rpm/1.7.1-rc3/fedora-20/RPMS/x86_64/docker-engine-1.7.1-0.3.rc3.fc20.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc3/fedora-20/SRPMS/docker-engine-1.7.1-0.3.rc3.fc20.src.rpm

**Fedora 21**
https://test.docker.com/rpm/1.7.1-rc3/fedora-21/RPMS/x86_64/docker-engine-1.7.1-0.3.rc3.fc21.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc3/fedora-21/SRPMS/docker-engine-1.7.1-0.3.rc3.fc21.src.rpm

**Fedora 22**
https://test.docker.com/rpm/1.7.1-rc3/fedora-22/RPMS/x86_64/docker-engine-1.7.1-0.3.rc3.fc22.x86_64.rpm
https://test.docker.com/rpm/1.7.1-rc3/fedora-22/SRPMS/docker-engine-1.7.1-0.3.rc3.fc22.src.rpm

**Comment by thaJeztah** [comment]
@calavera was https://github.com/docker/docker/pull/14456 cherry-picked?

**Comment by calavera** [comment]
@thaJeztah I did not :crying_cat_face: thanks for the ping, adding that commit now.

@jfrazelle do you think we need an RC4 for that or we can test the rpms without it? I'm guessing it should be good as long as we use it to create the final packages.

**Comment by ssadams11** [comment]
Tried the latest (rc3) but no joy.  Still failing to connect across containers.

Failed Environment:
>>uname -a
Linux tinkertools.rlse.cloud9.ibm.com 2.6.32-504.23.4.el6.x86_64 #1 SMP Fri May 29 10:16:43 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

>>docker version
Client version: 1.7.1-rc3
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): c2e658d
OS/Arch (client): linux/amd64
Server version: 1.7.1-rc3
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): c2e658d
OS/Arch (server): linux/amd64

Steps taken:
1) wget https://test.docker.com/rpm/1.7.1-rc3/centos-6/RPMS/x86_64/docker-engine-1.7.1-0.3.rc3.el6.x86_64.rpm
2) yum localinstall --nogpgcheck docker-engine-1.7.1-0.3.rc3.el6.x86_64.rpm
3) service docker start
4) docker run hello-world   
       succeeds
5) run mongo container
       succeeds
6) run meteord container connecting to mongo container over port 27017
      restarts in loop until max retries
7) docker logs myMeteor
         Error: failed to connect to [tinkertools.rlse.cloud9.ibm.com:27017]

As before the same setup and containers connect and run fine on ubuntu:

Successful Environment:
>>uname -a
Linux tinkertools2 3.13.0-51-generic #84-Ubuntu SMP Wed Apr 15 12:08:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

>>docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

**Comment by jfrazelle** [comment]
Is that rhel 6 what arguments are you passing to the daemon

**Comment by mavenugo** [comment]
@ssadams11 just to confirm can you please check if my earlier comment has any impact for your use-case ? https://github.com/docker/docker/pull/14264#issuecomment-119400753

**Comment by Hebime** [comment]
@jfrazelle I'm having the same issue as well.
I'm running rhel 6. I even downgraded the kernel as @mavenugo suggested in the previous comment. I started the daemon with no extra arguments.

**Comment by ssadams11** [comment]
yes, RHEL 6.6.  2.6.32-504.23.4.el6.x86_64
I did not downgrade kernel as suggested.  I'll try that next.

containers launched using the following:

docker run --name myMongo --restart=always -d -p 27017:27017 mongo

docker run -d \
	-e ROOT_URL=http://tinkertools2.sl.cloud9.ibm.com \
	-e MONGO_URL=mongodb://tinkertools2.sl.cloud9.ibm.com:27017/local \
	-v ~/:/bundle \
	-p 80:80 \
	--restart=always \
	--name=myMeteor \
	meteorhacks/meteord:base

**Comment by ssadams11** [comment]
@mavenugo 
I downgraded the kernel as you suggested but still same results.

**Comment by mavenugo** [comment]
@ssadams11 looking at your use-case, it seems similar to https://github.com/docker/docker/issues/13873 which we resolved in 1.7.0. Essentially the issue was about trying to reach a container running in the same host via the Host-IP and mapped port (instead of using the container-ip or container-linking).

Tried a simple case in Centos6.6 with the the kernel that I mentioned above -

* start a container exposing port 8000 & run nc server
```
$ sudo docker run --rm -p 8000:8000 busybox sh -c "echo hello | nc -lp 8000"
```

* check the host ip-address (eth0)
```
$ ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 08:00:27:6B:1C:DD
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe6b:1cdd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7083 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4119 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5234165 (4.9 MiB)  TX bytes:313561 (306.2 KiB)
```

* Start another container connecting to the container via host-eth0 ip and exposed port 

```
$ sudo docker run -it  busybox nc 10.0.2.15 8000
hello
```

* If it works, the 2nd container must output `hello` as echoed by the server container.

Can you please confirm if that works for you ?

**Comment by icecrime** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
Just FYI; I pinged @ibuildthecloud to check if they have discovered issues, he's testing now

**Comment by jfrazelle** [comment]
oh nice

**Comment by ibuildthecloud** [comment]
LGTM.  Tried basic integration tests, not full suite, but I assume it will be good :)

**Comment by thaJeztah** [comment]
Thanks @ibuildthecloud sorry I was a bit late pinging you, but glad you were able to do the basic testing.

**Comment by lesgrossman** [comment]
accidentally updated centOS 6.6 and a new kernel came down.  docker 1.7.1 appear very
unstable with this new kernel.  my VM has panic'd twice while working with docker.  It is possible 
this would happened on the kernel - 1.   Trying to figure out how to roll back a kernel and test 
same stuff, sorry not really a centOS guy.

in either case, may need a 1.7.2 release?

**Pull request merged**
