### PR TITLE
Remove pkg/integration and move it to testutil or integration-cli

### PR DESCRIPTION
**Pull request by vdemeester**
The more I was thinking about, the less `pkg/integration` package made sence. It's either

- some helper for tests (but general, could be used outside of the integration test), and that could go to the, already existing, `pkg/testutil` package
- some `go-check` (or only-integration) helpers, and thus could go directly in a sub package of `integratiion-cli`

It changes a lot of files but does not much 🐻

/cc @thaJeztah @icecrime @dnephin @cpuguy83 @AkihiroSuda @tiborvass 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
generally "LGTM", although we should cleanup that `testutil` package. I don't like the name, and for example, [`RandomTmpDirPath()`](https://github.com/vdemeester/docker/blob/33968e6c7df164fff0a882c50ae7f4f7e6190e4b/pkg/testutil/utils.go#L139) looks very similar to [`ioutil.TempDir()`](https://golang.org/pkg/io/ioutil/#example_TempDir), so if possible we should get rid of those

**Comment by vdemeester** [comment]
@thaJeztah there is definitely some cleaning to do, but baby steps, baby steps 👼

**Comment by thaJeztah** [comment]
Agreed, no need to do in this PR

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Pull request merged**
