### PR TITLE
doc: Standardise JSON examples

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
This is mostly whitespace. Fixed:
- [Invalid JSON](https://github.com/flowlo/docker/commit/e583cc1eb47c29d7473f1dac7d4f39ddeb8ae1e6#diff-0ce150101f644b5b72bf5433202ad617R329)
- Inconsistent spacing at colon

Expressions for binary data streams (line 468 vs. 1474) remain inconsistent. Could fix that too, if you like.

I can also look at v1.16 if requested.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@flowlo nice! - can you see how far you get by applying the diff to all the other API docs (ie, make patch using `git diff` then apply to the other using `patch -p1` ?

Docs LGTM @fredlf @jamtur01

**Comment by jamtur01** [comment]
LGTM

**Comment by flowlo** [comment]
@SvenDowideit I used my changes to patch the other files too. Some hunks could not be applied though. My guess would be that's because the docs evolved with the API over time and therefore do not match perfectly. Still the case of invalid JSON was fixed a few times over.

**Comment by jfrazelle** [comment]
pretty!!

**Comment by jamtur01** [comment]
Ping @fredlf

**Comment by SvenDowideit** [comment]
@flowlo awesome! merci-much

**Pull request merged**
