### PR TITLE
Split daemon service code to _windows file

### PR DESCRIPTION
**Pull request by thaJeztah**
Just a minor refactor: this moves some of the code that was conditionally executed on Windows to a separate, windows-only file.

ping @jhowardmsft @vdemeester PTAL

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :space_invader:

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Comment by jhowardmsft** [comment]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
