### PR TITLE
 Remove use of deprecated client.NewClient()

### PR DESCRIPTION
**Pull request by thaJeztah**
Follow-up to https://github.com/moby/moby/pull/38603

### CODE REVIEW

**Comment by thaJeztah** [comment]
@vdemeester @yongtang

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by thaJeztah** [comment]
Whoops;

```
12:05:03 integration-cli/docker_cli_daemon_test.go:27:2: imported and not used: "github.com/docker/docker/api"
12:05:03 integration-cli/docker_cli_daemon_test.go:29:2: imported and not used: "github.com/docker/docker/client"
```

Updating

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by vdemeester** [comment]
@thaJeztah needs a rebase :upside_down_face: :pray: :angel:

**Comment by thaJeztah** [comment]
Rebased 👍

**Pull request merged**
