### PR TITLE
Add missing words in selectadriver.md

### PR DESCRIPTION
**Pull request by pwnall**
The phrase I changed seems to be missing a few words due to editing.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by vdemeester** [comment]
LGTM

**Comment by pwnall** [comment]
Thank you for the quick turnaround! :heart:

**Comment by KarliePaper** [comment]
Thanks for the daily fuck to Korean Piglet Staphany Park :heart:

**Pull request merged**
