### PR TITLE
Fix s390x build failure by removing golang.org/x/sys/unix

### LINKED ISSUE #24168: s390x broken by: Revendor golang.org/x/sys/ to have unix package included
Commit 33badc189c4db37ec5e0bc87e2a79332254ec474 "Revendor golang.org/x/sys/ to have unix package included" breaks s390x build because s390x files are missing in golang.org/x/sys/unix:

```
19:01:19 ---> Making bundle: gccgo (in bundles/1.12.0-dev/gccgo)
19:03:04 # golang.org/x/sys/unix
19:03:04 vendor/src/golang.org/x/sys/unix/flock.go:15:30: error: reference to undefined name 'SYS_FCNTL'
19:03:04  var fcntl64Syscall uintptr = SYS_FCNTL
19:03:04                               ^
19:03:04 vendor/src/golang.org/x/sys/unix/sockcmsg_linux.go:15:30: error: reference to undefined name 'SizeofUcred'
19:03:04   b := make([]byte, CmsgSpace(SizeofUcred))
```

See https://jenkins.dockerproject.org/job/Docker%20Master%20(z)%20Binaries/779/console

ping @yongtang

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to fix the issue raised in #24168 where golang.org/x/sys causes s390x build failure.

This fix removed the import of "golang.org/x/sys/unix" in the first commit, and revendored golang.org/x/sys to remove the golang.org/x/sys/unix for s390x in the second commit.

This fix fixes #24168.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by michael-holzheu** [comment]
The commit golang/sys@33267e036fd93fcd26ea95b7bdaf2d8306cb743c introduced s390x support to golang.org/x/sys. Using this commit or a later could be an alternative to fix this issue.

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
I'm a bit confused, don't we need this for https://github.com/docker/docker/pull/23955 ?

**Comment by yongtang** [comment]
Thanks @michael-holzheu @LK4D4 @thaJeztah for the review.

@thaJeztah I realized that syscall package in golang has the required definitions as well. Since syscall package is available in golang without additional vendor packages, I made the change so that syscall package is used for #23955.

An alternative way is to update golang.org/x/sys, as was suggested by @michael-holzheu

Let me know if the other approach is preferred and I will update the PR accordingly.

**Comment by thaJeztah** [comment]
If this works, then this:
screen shot 2016-06-30 at 15 17 25

is reason for me to say, let's use the sys call package :smile:

**Comment by thaJeztah** [comment]
LGTM

**Comment by michael-holzheu** [comment]
@yongtang s390x builds again: 

Thanks!

**Pull request merged**
