### PR TITLE
Fix error message in container creation

### LINKED ISSUE #19652: Engine 1.10.0-rc1 returns different error string on image not found, breaks existing clients
Clients that leverage https://github.com/samalba/dockerclient/blob/master/dockerclient.go#L117  expect the error string coming back from the engine to contain  "No such image" when specifying an invalid image.  It appears that invalid image IDs in 1.10.0-rc1 are now returning errors that look like this:

```
time="2016-01-25T04:04:03.277926426Z" level=error msg="Handler for POST /v1.15/containers/create returned error: open /mnt/sda1/var/lib/docker/image/aufs/imagedb/content/sha256/c23997c23be934d8d7b8ec72436ae734588a0cba8f07995d9317c5aee1d60576: no such file or directory"
```

This appears to break swarm 1.1.0-rc1 which is no longer able to detect a missing image on a node and fall back to image affinity scheduling decisions.  See https://github.com/docker/swarm/blob/master/cluster/engine.go#L700 and https://github.com/docker/swarm/blob/master/cluster/swarm/cluster.go#L134

While the code in swarm could be hardened to look for the new strings, since there are many clients out there that leverage https://github.com/samalba/dockerclient which may not ship a new version aligned with the 1.10 release, it seems like engine should make sure "No such image" shows up in the error message someplace to prevent breaking them.

### PR DESCRIPTION
**Pull request by tonistiigi**
Error message was different if image was specified with the full ID.

Fixes #19652

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

cc @dhiltgen

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by aaronlehmann** [comment]
The code path involved here involves `GetImage` right? If so, I think it would be better to return the error from there. `GetImageID` is just responsible for resolving the ID, and it doesn't always check that the image exists. For example, if it finds the reference in the reference store, it will return a successful result, even if somehow the referenced ID doesn't actually exist in the image store.

**Comment by tonistiigi** [comment]
@aaronlehmann Why do we want to allow tagging images that don't exists? This works in rc1 btw.

**Comment by dhiltgen** [comment]
I've tested 8a68315 and can confirm that it resolves the issue.  Swarm correctly detects the image missing on a node, and falls back to image based affinity which then successfully starts the container on the correct node.

**Comment by tiborvass** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
