### PR TITLE
Add support for forwarding Docker client through SOCKS proxy

### PR DESCRIPTION
**Pull request by LK4D4**
Closes #18373 
ping @nathanleclaire

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by nathanleclaire** [comment]
This is very cool.  Nice job @LK4D4.  Will give it a spin soon.

**Comment by estesp** [comment]
LGTM

**Comment by nathanleclaire** [comment]
:+1: :tada: :balloon: :confetti_ball:

**Comment by qdk0901** [comment]
when I do `export ALL_PROXY=socks5://192.168.1.104:1080`, the docker still failed to pull tensorflow image from gcr.io,
```
abc@abc:~/source$ sudo docker run -it -p 8888:8888 b.gcr.io/tensorflow/tensorflow
Unable to find image 'b.gcr.io/tensorflow/tensorflow:latest' locally
docker: Error response from daemon: unable to ping registry endpoint https://b.gcr.io/v0/
v2 ping attempt failed with error: Get https://b.gcr.io/v2/: dial tcp 74.125.204.82:443: i/o timeout
 v1 ping attempt failed with error: Get https://b.gcr.io/v1/_ping: dial tcp 74.125.204.82:443: i/o timeout.
See 'docker run --help'.

```
 is this commit enabling docker to pull image behind a socks5 proxy?

**Pull request merged**
