### PR TITLE
bump google.golang.org/grpc v1.20.1

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/grpc/grpc-go/compare/v1.12.2...v1.20.1

includes  grpc/grpc-go#2695 transport: do not close channel that can lead to panic
relates to moby/moby#39053 (need to update docker/cli with this version)

depends on https://github.com/moby/buildkit/pull/936

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Seems to break something on BuildKit: https://github.com/moby/buildkit/pull/936

**Comment by thaJeztah** [comment]
😞 dang; any idea what's causing it?

**Comment by h-vetinari** [comment]
Since moby/buildkit#936 mentions race conditions, it might be relevant that gprc-go 1.20.1 has been released after the last comment here with a fix for race conditions (not sure if applicable though):
https://github.com/grpc/grpc-go/releases

**Comment by AkihiroSuda** [comment]
tried 1.20.1, still failing

**Comment by thaJeztah** [comment]
updated to v1.20.1 anyway (thanks for the ping)

**Comment by AkihiroSuda** [comment]
BuildKit failure was analyzed: https://github.com/moby/buildkit/pull/936/files#r283134768

Could you update bump up BuildKit as well after moby/buildkit#936 gets merged?
Then LGTM

**Review by tonistiigi — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
