### PR TITLE
Switch to google/uuid

### PR DESCRIPTION
**Pull request by justincormack**
pborman/uuid and google/uuid used to be different versions of
the same package, but now pborman/uuid is a compatibility wrapper
around google/uuid, maintained by the same person.

Clean up some of the usage as the functions differ slightly.

Not yet removed some uses of pborman/uuid in vendored code but
I have PRs in process for these.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

barcode-zebra

### CODE REVIEW

**Comment by thaJeztah** [comment]
I see you opened https://github.com/mistifyio/go-zfs/pull/72 as well; should we wait for that to get merged? (otherwise we'd still have both dependencies)

**Comment by justincormack** [comment]
@thajeztah I have opened PRs all over the place, I don't think we need to wait for the end of my quest to fix all uuids...

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
