### PR TITLE
Libnetwork vendoring & overlay networking fixes

### LINKED ISSUE #17449: [1.9.0-rc3] DEBUG serf messages displayed on daemon stdout
While the daemon is running without the debug flag, I keep getting serf(?) debug messages from the daemon's stdout:

```
2015/10/28 19:26:12 [DEBUG] memberlist: Initiating push/pull sync with: 172.17.0.3:7946
2015/10/28 19:26:20 [DEBUG] memberlist: Responding to push/pull sync with: 172.17.0.3:47065
```

### LINKED ISSUE #17465: [1.9.0-rc3] /etc/hosts with overlay net not updating properly
2 nodes, N1 and N2
N1 has containers `test`, `test2`, and `test4`
N2 has container `test3`

If I restart any container on N1, the `test3` container's `/etc/hosts` file will only contain entries for that one container that was restarted. Same with restarting another container again.

If I add a `test5` to N2, then the `/etc/hosts` files on containers in N1 will only have entries for containers local to N1, and `test5`, no test3.
If I remove `test5`, all entries from N2 (where `test5` lives) are removed from containers in N1.

### PR DESCRIPTION
**Pull request by aboch**
This brings in two fixes for overlay networking:
1. External connectivity tracked by the port-mapping issue in [ibnetwork](https://github.com/docker/libnetwork/issues/716)
2. /etc/hosts issue, #17465

Fixes #17465 
Vendoring also Fixes  #17449

### CODE REVIEW

**Comment by LK4D4** [comment]
Is it possible to write some tests for this?

**Comment by jfrazelle** [comment]
@LK4D4 jynx! i was typing that

**Comment by aboch** [comment]
@LK4D4 @jfrazelle 
Proper integration test with cluster was already added by @mrjana in libnetwork.
The most I can do in docker integration cli is to write a mock driver which mimic overlay driver behavior in regards to the portmap info and mac address retrieval.

Will work at that.

**Comment by aboch** [comment]
@LK4D4 @jfrazelle I added a couple of integration tests. 
PTAL when you get a chance.

Thanks

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
