### PR TITLE
Added `dead` to docs for docker ps -f status=...

### PR DESCRIPTION
**Pull request by karkhaz**
It is possible to invoke `docker ps -f status=dead`, but the
documentation for docker-ps does not mention `dead` as a valid option.
This commit fixes that.

### CODE REVIEW

**Comment by vdemeester** [comment]
@karkhaz Thanks, you are right it is not listed :sweat_smile:. Could you also update `man/docker-ps.1.md` as the list is present there ?

**Comment by karkhaz** [comment]
Will do. Do you prefer that I use --amend to squash that into the same commit, or shall I make two separate commits for this pull request?

thanks

**Comment by vdemeester** [comment]
@karkhaz `--amend` :wink:

**Comment by karkhaz** [comment]
Not sure why there are conflicts :S sorry

**Comment by calavera** [comment]
@karkhaz :

```
$ git checkout master
$ git pull --rebase
$ git checkout -
$ git rebase master
```

That will give you the conflicts

**Comment by karkhaz** [comment]
oh shoot. That was wrong. Shall I start over and submit a new pull request?

Sorry for the trouble, just for some documentation changes...

**Comment by thaJeztah** [comment]
@karkhaz you can rebase this PR, and do a force push to update this PR

**Comment by tiborvass** [comment]
Carried in #19557

**Pull request closed without merging**
