### PR TITLE
change url for jfrazelle/go

### PR DESCRIPTION
**Pull request by jessfraz**
Signed-off-by: Jessica Frazelle acidburn@docker.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
wait i need to PR notary first

**Comment by jfrazelle** [comment]
https://github.com/docker/notary/pull/499

**Comment by jfrazelle** [comment]
this is ready now

**Comment by calavera** [comment]
It looks like this PR and #19760 are duplicated. That other one also changes Dockerfile SHAs. Should we close this one? @jfrazelle, @cyli?

**Comment by jfrazelle** [comment]
Yup closing mine!

**Pull request closed without merging**
