### PR TITLE
'docker daemon' deprecation message doesn't use the new version

### LINKED ISSUE #31397: "docker daemon" deprecation message doesn't use the new versioning scheme
https://github.com/docker/docker/blob/17.03.x/cmd/docker/daemon_unix.go#L27
Mentions docker `1.16`, should instead be `17.XX`.

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

fixes #31397

**- What I did**
Use the new version for 'docker daemon' deprecation message

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by coolljt0725** [comment]
From the feature deprecation policy(https://docs.docker.com/engine/#feature-deprecation-policy), I don't think remove this in `17.04` is correct.
ping @thaJeztah  I think we should update the deprecated docs after switching to new version schema.

**Comment by thaJeztah** [comment]
> I think we should update the deprecated docs after switching to new version schema

Yes, it's on my list :smile:


17.04 is indeed not correct, because we want to keep _at least_ the current duration for things to be deprecated.

**Comment by yuexiao-wang** [comment]
@thaJeztah  OK, i will update this PR until you modify the deprecated docs

**Comment by thaJeztah** [comment]
ping @yuexiao-wang here's the pull request that updates the versions https://github.com/docker/docker/pull/31496

**Comment by yuexiao-wang** [comment]
@thaJeztah PTAL
It has done to update this PR and thanks!

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
cherry-picked into 17.03.1 through https://github.com/docker/docker/pull/31754

**Pull request merged**
