### PR TITLE
Fix log

### PR DESCRIPTION
**Pull request by charlesh001**
Signed-off-by: maxwell <csuhp007@gmail.com>

**- What I did**
Fix log

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks; the change itself looks good, but could you fix your sign-off to [use your real first, and last name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work);

> Use your real name (sorry, no pseudonyms or anonymous contributions.)

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
@runcom ping. This one look passing build

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Change looks good, but please sign with your real first and last name

**Pull request merged**
