### PR TITLE
Cleanup: new project docs fix-ups (alternative)

### PR DESCRIPTION
**Pull request by thaJeztah**
NOTE:
This is an alternative commit/PR to https://github.com/docker/docker/pull/11229 that re-introduces some inline
styles because the docs/base image has not yet been updated for the current docs.

Either this PR or #11229 can be merged. Differences between this PR and 11229 can be seen below 

This cleans up the recently added project docs and fixes some minor issues.
- remove inline styles where possible
- add redirects for renamed/replaced documents
- add styles for GitHub labels to match the style on GitHub
- fix minor markdown issues causing some code-blocks
  to be shown as text
- wrap the documents to 80-chars
- use 4 spaces in stead of tabs for identing and remove
  trailing whitespace/redundant blank lines
- optimized 'gordon' image

Differences between this PR and 11229
(also as gist here; https://gist.github.com/thaJeztah/89594c820fa6aa092379)

``` diff
diff --git a/docs/sources/project/get-help.md b/docs/sources/project/get-help.md
index 94bdeac..38daf09 100644
--- a/docs/sources/project/get-help.md
+++ b/docs/sources/project/get-help.md
@@ -15,7 +15,13 @@ page_keywords: IRC, Google group, Twitter, blog, Stackoverflow
 There are several communications channels you can use to chat with Docker
 community members and developers.

-<table>
+<!-- TODO (@thaJeztah) remove after docs/base is updated -->
+<style type="text/css">
+.tg  {border-collapse:collapse;border-spacing:0;text-align: left;}
+.tg td{padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;vertical-align:top;}
+.tg th{font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
+</style>
+<table class="tg">
   <col width="25%">
   <col width="75%">
   <tr>
@@ -73,7 +79,13 @@ the easiest way to connect to IRC.

 2. Fill out the form.

-    <table class="no-zebra" style="width: auto">
+    <!-- TODO (@thaJeztah) remove after docs/base is updated -->
+    <style type="text/css">
+    .tg   {border-collapse:collapse;border-spacing:0;}
+    .tg td{padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
+    .tg th{font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
+    </style>
+    <table class="tg no-zebra" style="width: auto">
       <tr>
         <td><b>Nickname</b></td>
         <td>The short name you want to be known as in IRC.</td>
diff --git a/docs/sources/project/make-a-contribution.md b/docs/sources/project/make-a-contribution.md
index 6a3bbd9..8a89ac0 100644
--- a/docs/sources/project/make-a-contribution.md
+++ b/docs/sources/project/make-a-contribution.md
@@ -3,6 +3,14 @@ page_description: Basic workflow for Docker contributions
 page_keywords: contribute, pull request, review, workflow, white-belt, black-belt, squash, commit


+<!-- TODO (@thaJeztah) remove after docs/base is updated -->
+<style type="text/css">
+.tg    {border-collapse:collapse;border-spacing:0;margin-bottom:15px;}
+.tg td {background-color: #fff;padding:5px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;vertical-align:top;}
+.tg th {font-weight:bold;padding:5px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;text-align:left;}
+.tg .tg-e3zv{width:150px;}
+</style>
+
 <style>

 /* GitHub label styles */
@@ -258,16 +266,16 @@ Follow this workflow as you work:

 5. Format your source files correctly.

-    <table>
+    <table class="tg">
       <thead>
       <tr>
-        <th>File type</th>
+        <th class="tg-e3zv">File type</th>
         <th>How to format</th>
       </tr>
       </thead>
       <tbody>
       <tr>
-        <td><code>.go</code></td>
+        <td class="tg-e3zv"><code>.go</code></td>
         <td>
             <p>
             Format <code>.go</code> files using the <code>gofmt</code> command.
@@ -282,7 +290,7 @@ Follow this workflow as you work:
         </td>
       </tr>
       <tr>
-        <td style="white-space: nowrap"><code>.md</code> and non-<code>.go</code> files</td>
+        <td  class="tg-e3zv" style="white-space: nowrap"><code>.md</code> and non-<code>.go</code> files</td>
         <td>Wrap lines to 80 characters.</td>
       </tr>
       </tbody>
diff --git a/docs/sources/project/set-up-dev-env.md b/docs/sources/project/set-up-dev-env.md
index f9bca6d..2a30f2b 100644
--- a/docs/sources/project/set-up-dev-env.md
+++ b/docs/sources/project/set-up-dev-env.md
@@ -2,6 +2,14 @@ page_title: Work with a development container
 page_description: How to use Docker's development environment
 page_keywords: development, inception, container, image Dockerfile, dependencies, Go, artifacts

+
+<!-- TODO (@thaJeztah) remove after docs/base is updated -->
+<style type="text/css">
+.tg   {border-collapse:collapse;border-spacing:0;}
+.tg td{font-family:monospace, serif;font-size:11px;padding:10px 5px;border-style:solid;border-width:0px;overflow:hidden;word-break:normal;}
+.tg th{font-family:monospace, sans-serif;font-size:11px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:0px;overflow:hidden;word-break:normal;}
+</style>
+
 # Work with a development container

 In this section, you learn to develop like a member of Docker's core team.
@@ -36,7 +44,7 @@ To remove unnecessary artifacts.

     You should see something similar to the following:

-    <table class="code">
+    <table class="tg code">
       <tr>
         <th>CONTAINER ID</th>
         <th>IMAGE</th>
@@ -58,7 +66,7 @@ To remove unnecessary artifacts.

     You should see something similar to the following:

-    <table class="code">
+    <table class="tg code">
       <tr>
         <th>REPOSITORY</th>
         <th>TAG</th>
@@ -120,7 +128,7 @@ environment.

     You should see something similar to this:

-    <table class="code">
+    <table class="tg code">
       <tr>
         <th>REPOSTITORY</th>
         <th>TAG</th>
@@ -284,7 +292,7 @@ build and run a `docker` binary in your container.

         $ docker ps

-    <table class="code">
+    <table class="tg code">
       <tr>
         <th>CONTAINER ID</th>
         <th>IMAGE</th>
diff --git a/docs/sources/project/test-and-docs.md b/docs/sources/project/test-and-docs.md
index 3fee820..7e725d2 100644
--- a/docs/sources/project/test-and-docs.md
+++ b/docs/sources/project/test-and-docs.md
@@ -2,6 +2,13 @@ page_title: Run tests and test documentation
 page_description: Describes Docker's testing infrastructure
 page_keywords: make test, make docs, Go tests, gofmt, contributing, running tests

+<!-- TODO (@thaJeztah) remove after docs/base is updated -->
+<style type="text/css">
+.tg  {border-collapse:collapse;border-spacing:0;margin-bottom:15px;}
+.tg td{padding:5px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
+.tg th{padding:5px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;text-align:left;}
+</style>
+
 # Run tests and test documentation

 Contributing includes testing your changes. If you change the Docker code, you
@@ -54,7 +61,7 @@ is simply `test`. The make file contains several targets for testing:
 <style type="text/css">
 .make-target {font-family:"Courier New", Courier, monospace !important;}
 </style>
-<table>
+<table class="tg">
   <tr>
     <th>Target</th>
     <th>What this target does</th>
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
For info as to *why* this PR was created, see https://github.com/docker/docker/pull/11229#issuecomment-77698868

**Comment by moxiegirl** [comment]
@thaJeztah I'm going to use this one for now.  @SvenDowideit just recently handed his infrastructure changes. I'll need to check with the larger team as I am still learning the build system.  We will do this one for now.  I do apologize for not being able to get your hard work on the table fixes.

**Comment by moxiegirl** [comment]
LGTM

**Comment by thaJeztah** [comment]
:+1: great, no reason to fuss about it now, you need to get things moving. I'll create a follow-up PR to remove the temporary styles once the docs/base issue is fixed.

**Pull request merged**
