### PR TITLE
Add the ability to get events using WebSockets

### PR DESCRIPTION
**Pull request by boaz0**
**- What I did**

Add a second endpoint to receive Docker events. This endpoint sends the events via `WebSockets`.

**- How I did it**

* Add `events/ws` route in `api/server/router/system/system.go`
* Add `wsEvents` to `api/server/router/system/system_routes.go`
* Use `golang/x/net/websocket` to hijack the connection to a `WebSocket` connection

**- How to verify it**
* I have added unit-tests to `/api/server/router/system`.
* You can also follow these instructions in order to see how it works and test it:

Create a new file called websocket.html
```
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Websocket</title>
      <script type="text/javascript">
        function DockerWebSocket() {
          if ("WebSocket" in window) {
            console.log("WebSocket is supported by Browser...")
            // Remove '?url=' prefix
            url = window.location.search.replace(/^(\?url=)/,"");
            console.log("URL ["+url+"]...");
            var ws = new WebSocket(url);
            ws.onopen = function() {
              console.log("Connection is opened...");
            };
            ws.onclose = function() {
              console.log("Connection is closed...");
            };
            ws.onmessage = function (e) {
              if (typeof e.data === "string") {
                alert("WebSocket received text message ["+e.data+"]!")
              } else {
                console.log("Message is received...")
                var blobReader = new FileReader();
                blobReader.onload = function(event) {
                  console.log(JSON.stringify(blobReader.result))
                };
                blobReader.readAsText(e.data)
                console.log("Message complete...")
              }
            };
          } else {
            alert("WebSocket is not supported by Browser!");
          }
        }
      </script>
    </head>
    <body>
      <div>
        <a href="javascript:DockerWebSocket()">Run DockerWebSocket</a>
      </div>
    </body>
    </html>
```

Open the file with the following params:
```
websocket.html?url=ws://172.16.66.128:2375/events/ws
```

Open the console and see the events (you can create a container or pull an image to see this in real-time)

### CODE REVIEW

**Comment by ripcurld0** [comment]
@yongtang @dnephin @cpuguy83 @vdemeester 

Do you have any idea how can I test it? There are no unit-tests in `api/server/router/system` and creating new tests in `integration-cli` is out of the question.

Thanks.

**Comment by dnephin** [comment]
We should start adding unit tests to `api/server/router/system`, now is a great time.

I would suggest this:
* add an API integration test to `integration/system/events_test.go`. You'll need to copy the `main_test.go` from `integration/container`. If you encounter problems feel free to reach out on slack, or ping me here. An  alternative is to add an API test in `integration-cli/docker_api_system_test.go`, but we'd really like to move away from that suite.
* split up `wsEvents` into 3 or more functions, each of which can be easily unit tested
  * a function to parse arguments from the request into an `options` struct, and returns bad request errors on bad arguments
  * a function for setting up and running the websocket server
  * a function for feeding events into the channel

You may end up with even more functions, but I would guess those 3 are pretty likely from a quick look at the code.

By splitting up this function you should be able to share a lot more code with the existing `getEvents()` as well. These two pieces of code are very similar, but right now share very little. I believe the argument parsing function and options struct would both be re-used. The "feeding events into channel" is also quite similar and could probably be paramaterized and re-used as well.

**Comment by ripcurld0** [comment]
@dnephin thanks a bunch! working on this! 😄 🍺

**Comment by thaJeztah** [comment]
ping @ripcurld0 have you had time to look at integration tests?

**Comment by ripcurld0** [comment]
yep. actually, i have no idea how to use `APIClient` here because i need to use websocket client in some point. 🤔 💭

**Comment by ripcurld0** [comment]
Great, I will be working on this in the next days.

**Comment by thaJeztah** [comment]
Wondering; is there an actual issue this is resolving? IIUC, WebSockets mainly resolve overhead when working with interactive sessions, but advantages over a chunked response should be none, or very minimal (after the initial response's header, chunks don't send new headers).

If the problem is to consume the events API with JavaScript; doing a quick search for an example XHR request for an endpoint using chunked encoding (lol, my JavaScript has become a bit rusty), that doesn't seem to be very problematic either; I tried the following, and that seemed to work fine;

```html
<html>
<script>
var last_index = 0;
var xhr = new XMLHttpRequest();
xhr.open("GET", "http://test-docker-host:2375/v1.31/events");
xhr.onprogress = function () {
    var curr_index = xhr.responseText.length;
    if (last_index == curr_index) return; 
    var s = xhr.responseText.substring(last_index, curr_index);
    last_index = curr_index;
    console.log(s);
};
xhr.send();
</script>
</html>
```

Perhaps there's a specific reading that I'm not aware of, so just curious if this change resolves a particular situation/issue. 😅

**Comment by ripcurld0** [comment]
Yes, the main reason for this PR is that I want to get the events to a JavaScript UI and since `docker events` is blocking, I thought adding a web-socket endpoint will fix it.

Of course, I can also implement a backend/proxy that sends webhooks or exposes API for the events but it adds some overhead and complication to my web UI.

I am using the `fetch` API (actually the [`isomorphic-fetch`](https://www.npmjs.com/package/isomorphic-fetch) module).
I guess I will see how `onprogress` is done there and report if it is feasible.

Is that OK?

**Comment by ripcurld0** [comment]
@thaJeztah OK, unfortunately `fetch` has limitations and one of them is it can't be used to process a response by chunks.
I think a good workaround is using `since` and `until` every time I call `events`.
I am closing this.
Thanks.

**Pull request closed without merging**
