### PR TITLE
pkg: mflag: exit on help with -h

### LINKED ISSUE #20093: `docker volume -h` emits help message twice
Description of problem:
    `docker volume -h` emits help message twice.

`docker version`:

```
$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

`docker info`:

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 113
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 115
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 996.1 MiB
Name: default
ID: RLM2:AUEA:NZ33:CNQQ:3TN3:XRXE:KSAM:SS4S:BFSS:A6H2:V24A:MLSG
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 23
 System Time: 2016-02-07T23:40:36.778891002Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: micahhausler
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

`uname -a`:

```
Darwin ip-10-101-71-37.ec2.internal 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox on OS X

How reproducible:
100%

Steps to Reproduce:
1. `docker volume -h`
2. Enjoy

Actual Results:

```
$ docker volume -h 

Usage:  docker volume [OPTIONS] [COMMAND]

Manage Docker volumes

Commands:
  create                   Create a volume
  inspect                  Return low-level information on a volume
  ls                       List volumes
  rm                       Remove a volume

Run 'docker volume COMMAND --help' for more information on a command

  --help             Print usage

Usage:  docker volume [OPTIONS] [COMMAND]

Manage Docker volumes

Commands:
  create                   Create a volume
  inspect                  Return low-level information on a volume
  ls                       List volumes
  rm                       Remove a volume

Run 'docker volume COMMAND --help' for more information on a command

  --help             Print usage
flag: help requested
```

Expected Results:
It should be the same as `docker volume --help`

Additional info:

### PR DESCRIPTION
**Pull request by runcom**
Fix #20093

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
This will also get rid of the last `flag: help requested` line which comes from `ErrHelp` when `h` isn't in the flags with `withHelp` (and do not exit with `125` anymore on normal commands, e.g. `docker start -h && echo $?` -> `125`, now just `0` as `--help` does)

**Comment by thaJeztah** [comment]
hm... commit message :innocent: ?

LGTM (if janky is green)

**Comment by runcom** [comment]
mmm janky, it isn't on my machine and `docker run` panics because `-h` is redefined, looking into it

**Comment by runcom** [comment]
w/o this patch:
```
docker run -h
flag needs an argument: -h
See 'docker run --help'.
```
because `-h` is binded to `--hostname`, this is tricky, shall we remove `-h` at all :smile:

**Comment by thaJeztah** [comment]
oh, darn, yes, I think we had some discussion around that; I think it was even removed from the docs in some places, because `-h (help)`/`-h (hostname)`/`-H` was also confusing as hell

**Comment by albers** [comment]
IIRC, `-h` as a synonym for `--help` was removed completely. I remember that I removed it from bash completion.

**Comment by thaJeztah** [comment]
@albers ah, good call, I wasn't sure anymore what we ended up doing. In that case it should just show an error (unknown option), and show usage, I guess

**Comment by albers** [comment]
See #15449 for removal of `-h` from completion and documentation

**Comment by runcom** [comment]
Thanks will update the patch accordingly

**Comment by albers** [comment]
So it looks like `-h` was removed from completion because it was missing in documentation and help output. The intent was to not encourage people to use an undocumented (and inconsitent) option.
 `-h` was not removed from the code, though.

**Comment by runcom** [comment]
@albers that's my understanding as well

**Comment by albers** [comment]
I propose `-h` should remain undocumented but functional.

**Comment by runcom** [comment]
> I propose -h should remain undocumented but functional.

why this? can't we just get rid of it? :angel:

**Comment by runcom** [comment]
removing it from the commands help output we basically _deprecated_ it (long time ago), we could just remove it to avoid further incomprehension :)

**Comment by tiborvass** [comment]
@runcom was this bug introduced in 1.10 ? If not, I would remove it from the milestone.

I am fine removing `-h` in 1.12, but I am not sure about reusing it for `--help`.

**Comment by calavera** [comment]
Removed from 1.10.1 since it was a bug in 1.9 already.

**Comment by icecrime** [comment]
@runcom Can you please look into the failures?

**Comment by runcom** [comment]
@icecrime sure, was just waiting for consensus about what to do here. Can we get rid of `-h` altogether cause it conflicts with `run|create` also?

**Comment by icecrime** [comment]
@runcom I think we should remove. Any opinion @calavera?

**Comment by tiborvass** [comment]
+1 for remove `-h`

**Comment by runcom** [comment]
I'm for removing it as well

**Comment by runcom** [comment]
I'll open another PR which will address the removal of `-h`

**Pull request closed without merging**
