### PR TITLE
add a new sub-section to each volume page

### PR DESCRIPTION
**Pull request by ozlerhakan**
Signed-off-by: ozlerhakan hakan.ozler@kodcu.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
I like this; only concern currently is that the linked "dockervolumes.md" needs a serious overhaul, because it's still suggesting using data-only containers, which may no longer be needed now we have volume management commands.

@cpuguy83 wdyt?

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM as well; tracking issue for the linked document created here; https://github.com/docker/docker/issues/20465

**Comment by thaJeztah** [comment]
Thanks @ozlerhakan!

**Comment by ozlerhakan** [comment]
you're welcome @thaJeztah

**Pull request merged**
