### PR TITLE
rewording and changes in 1.12.1 changelog for 1.12.1-GA

### PR DESCRIPTION
**Pull request by thaJeztah**
- Repeats the warning about the systemd unit file
- Move the `/proc/timer_list` change to the "security" section
- Some minor rewording / changes

I titled this "WIP" so that we can update this if we find other changes that need to be included

/cc @tiborvass

### CODE REVIEW

**Comment by IndeedPlusPlus** [comment]
May I suggest the following minor patch.
```patch
From 2e7dcac67e88cfc80d38acf078bd58ad6568ffbb Mon Sep 17 00:00:00 2001
From: Indeed <indeed@indeed.moe>
Date: Sat, 13 Aug 2016 00:10:32 +0800
Subject: [PATCH] join -> joined

---
 CHANGELOG.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/CHANGELOG.md b/CHANGELOG.md
index c1dca64..e21d6ed 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -37,7 +37,7 @@ systemctl restart docker` to reload changes and (re)start the docker daemon.
 
 ### Client
 
-* Add `Join at` information in `node inspect --pretty` [#25512](https://github.com/docker/docker/pull/25512)
+* Add `Joined at` information in `node inspect --pretty` [#25512](https://github.com/docker/docker/pull/25512)
 - Fix a crash on `service inspect` [#25454](https://github.com/docker/docker/pull/25454)
 - Fix issue preventing `service update --env-add` to work as intended [#25427](https://github.com/docker/docker/pull/25427)
 - Fix issue preventing `service update --publish-add` to work as intended [#25428](https://github.com/docker/docker/pull/25428)
-- 
2.6.4 (Apple Git-63)


```

**Comment by thaJeztah** [comment]
@IndeedPlusPlus nice catch, thanks! pushed an update

**Comment by SvenDowideit** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
