### PR TITLE
Fix target reference secrets

### PR DESCRIPTION
**Pull request by ehazlett**
This addresses the [comment](https://github.com/docker/docker/pull/27794#discussion_r88158137) in #27794  regarding secret reference targets.

Refs #28516

### CODE REVIEW

**Comment by diogomonica** [comment]
This was the change I was looking for. LGTM

**Comment by ehazlett** [comment]
sweet thx

**Comment by stevvooe** [comment]
LGTM

**Comment by ehazlett** [comment]
Merging this PR into another change related here: https://github.com/docker/docker/pull/28556

Closing this one.

**Pull request closed without merging**
