### PR TITLE
don't try to use aufs in a user namespace

### PR DESCRIPTION
**Pull request by hallyn**
If aufs is already modprobe'd but we are in a user namespace, the
aufs driver will happily load but then get eperm when it actually tries
to do something.  So detect that condition.

Signed-off-by: Serge Hallyn serge.hallyn@ubuntu.com

### CODE REVIEW

**Comment by icecrime** [comment]
Thanks! Small formatting issue here:

```
20:02:36 ---> Making bundle: validate-gofmt (in bundles/1.11.0-dev/validate-gofmt)
20:02:36 These files are not properly gofmt'd:
20:02:36  - daemon/graphdriver/aufs/aufs.go
20:02:36 
20:02:36 Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by estesp** [comment]
LGTM. (and of course the fix needed for `gofmt`)

Talking with @thaJeztah yesterday, I think this nested Docker-in-a-userns probably needs a mention somewhere in daemon admin/install/setup docs just to mention the restrictions and that it is possible (once these PRs are complete--so I assume for Docker 1.12)

**Comment by calavera** [comment]
@hallyn can you fix the formatting error mentioned above?

**Comment by hallyn** [comment]
hi @calavera - I think I did.  Or are you referring to something beside 'go fmt' for aufs.go?

**Comment by cpuguy83** [comment]
```
Errors from golint:
02:07:05 daemon/graphdriver/aufs/aufs.go:55:2: exported var ErrAufsNested should have comment or be unexported
```

**Comment by cpuguy83** [comment]
The error probably doesn't need to be exported

**Comment by hallyn** [comment]
Quoting Brian Goff (notifications@github.com):
> ```
> Errors from golint:
> 02:07:05 daemon/graphdriver/aufs/aufs.go:55:2: exported var ErrAufsNested should have comment or be unexported
> ```

thanks

**Comment by calavera** [comment]
LGTM

**Pull request merged**
