### PR TITLE
Vendoring libnetwork @ab62dd6bf06bf0

### PR DESCRIPTION
**Pull request by mrjana**
Fixes issues in LB backend and SD records cleanup
Also fixes a panic during DNS lookup

Signed-off-by: Jana Radhakrishnan mrjana@docker.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by thaJeztah** [comment]
WindowsTP5 is a known flaky test; https://github.com/docker/docker/issues/22702

win2lin is not related, but let me start again;

```
03:17:21 ----------------------------------------------------------------------
03:17:21 FAIL: docker_cli_save_load_test.go:250: DockerSuite.TestSaveDirectoryPermissions
03:17:21 
03:17:21 docker_cli_save_load_test.go:267:
03:17:21     c.Assert(err, checker.IsNil, check.Commentf("%v", err))
03:17:21 ... value *errors.errorString = &errors.errorString{s:"failed to build the image: Sending build context to Docker daemon 2.048 kB\r\r\nStep 1 : FROM busybox\n ---> d9551b4026f0\nStep 2 : RUN adduser -D user && mkdir -p /opt/a/b && chown -R user:user /opt/a\n ---> Running in 552f44162121\nThe command '/bin/sh -c adduser -D user && mkdir -p /opt/a/b && chown -R user:user /opt/a' returned a non-zero code: 137\n"} ("failed to build the image: Sending build context to Docker daemon 2.048 kB\r\r\nStep 1 : FROM busybox\n ---> d9551b4026f0\nStep 2 : RUN adduser -D user && mkdir -p /opt/a/b && chown -R user:user /opt/a\n ---> Running in 552f44162121\nThe command '/bin/sh -c adduser -D user && mkdir -p /opt/a/b && chown -R user:user /opt/a' returned a non-zero code: 137\n")
03:17:21 ... failed to build the image: Sending build context to Docker daemon 2.048 kB

03:17:21 Step 1 : FROM busybox
03:17:21  ---> d9551b4026f0
03:17:21 Step 2 : RUN adduser -D user && mkdir -p /opt/a/b && chown -R user:user /opt/a
03:17:21  ---> Running in 552f44162121
03:17:21 The command '/bin/sh -c adduser -D user && mkdir -p /opt/a/b && chown -R user:user /opt/a' returned a non-zero code: 137
```

**Comment by vdemeester** [comment]
LGTM 🐯

**Pull request merged**
