### PR TITLE
Vendor swarmkit d60ccf3

### PR DESCRIPTION
**Pull request by aaronlehmann**
This brings in the latest fixes from swarmkit, including the following:

- Fix logs hanging: https://github.com/docker/swarmkit/pull/1973
- node: Try to force TLS certificate renewal if role doesn't change after demotion: https://github.com/docker/swarmkit/pull/1992

There is one change to an integration test to prevent it from timing out. swarmkit is now more conservative about restarting the manager during a rapid demote/promote cycle. The test now waits for the node to become demoted before promoting it again, which avoids a slow timeout in swarmkit.

cc @cyli @dperny @tonistiigi

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
probably CI failure is real

**Comment by aaronlehmann** [comment]
@AkihiroSuda: Thanks for pointing it out. There appears to be a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xff5269]

goroutine 185 [running]:
panic(0x1667360, 0xc420016050)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.defaultClusterObject(0xc4208c3d80, 0x19, 0xc4209e8cf0, 0x0, 0x0, 0x0, 0x2710, 0x0, 0x1f4, 0x300000001, ...)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1053 +0x1f9
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader.func1(0x240f7a0, 0xc4209dbc20, 0xc420987d00, 0xc420117770)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:892 +0xee
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.(*MemoryStore).update(0xc4208e6f90, 0x23fcb80, 0xc42039e280, 0xc42021ee08, 0x19b5401, 0xc4209e8cf0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/memory.go:235 +0x134
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store.(*MemoryStore).Update(0xc4208e6f90, 0xc42021ee08, 0x19, 0x1b00000000)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/state/store/memory.go:277 +0x47
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader(0xc420827340, 0x7ff1c20b00c0, 0xc4208e3ec0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:897 +0x311
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:897 +0x311
github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).handleLeadershipEvents(0xc420827340, 0x7ff1c20b00c0, 0xc4208e3ec0, 0xc4208f4600)
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:821 +0x1b3
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).Run
        /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:366 +0x180
```

I'll investigate.

**Comment by aaronlehmann** [comment]
Updated to swarmkit ac35889db0ae0022cad3d173dd00d8659d38f78e. This should fix the problems that showed up in CI.

**Comment by aaronlehmann** [comment]
Updated again to d60ccf366a6758c7857db968857b72202cb2f902. This fixes a data race (https://github.com/docker/swarmkit/pull/2013), hanging service logs (https://github.com/docker/swarmkit/pull/1995), and improper Raft snapshot handling (https://github.com/docker/swarmkit/pull/1989).

PTAL

**Comment by dperny** [comment]
#31500 is blocked until swarmkit is revendored.

**Comment by aaronlehmann** [comment]
Added one more test fix: `DockerSwarmSuite.TestServiceLogs` needs to wait for the swarm manager to become aware that the tasks are running, not just check that the containers have started. This should fix experimental CI.

Merging this will unblock #31500 and #31144.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]
LGTM

**Pull request merged**
