### PR TITLE
bash completion for `docker ps --filter status=dead`

### PR DESCRIPTION
**Pull request by albers**
Ref #17908
Also added missing value `created`.
Please include in 1.10 as this feature is present in that release.

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by runcom** [comment]
LGTM

**Comment by tiborvass** [comment]
@vdemeester you misclicked the milestone, not good! ;)

**Comment by vdemeester** [comment]
@tiborvass ohh :sweat:

**Pull request merged**
