### PR TITLE
Remove hardcoded error from builder/evaluator.go

### LINKED ISSUE #11611: Remove ErrDockerfileEmpty from builder/evaluator.go
**Problem**
 
Remove `ErrDockerfileEmpty` from `builder/evaluator.go`.
 
**Solution**
 
We return non-hardcoded errors all over the package, so it makes sense instead of `ErrDockerfileEmpty` return error with file name/path like in other places.

### PR DESCRIPTION
**Pull request by runcom**
Fixes: #11611

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by LK4D4** [comment]
@runcom You need to fix `TestBuildFailsDockerfileEmpty` too, because it relies on old message.

**Comment by runcom** [comment]
@LK4D4 yes I'm fixing it :+1:

**Comment by LK4D4** [comment]
@runcom Tests passed. Are you confirming that you finished work on this?

**Comment by runcom** [comment]
@LK4D4 Yup! :+1:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
