### PR TITLE
hack: no need to git fetch in CI

### PR DESCRIPTION
**Pull request by tiborvass**
CIs are assumed to do a git fetch and git merge before running tests.
Therefore, no need for a git fetch inside our validate scripts in CI.

If VALIDATE_ORIGIN_BRANCH is set, then git fetch is skipped and
VALIDATE_ORIGIN_BRANCH is used in validate scripts.

Otherwise, behavior is unchanged.

Signed-off-by: Tibor Vass <tibor@docker.com>

Related to #38655

### CODE REVIEW

**Comment by tiborvass** [comment]
@tianon do you agree ? This is a followup to https://github.com/moby/moby/pull/38655

**Review by seemethere — APPROVED** [review]

**Comment by tianon** [comment]
We did the fetch originally both to be explicit about what we're comparing against (since it was _way_ more reliable for getting the explicit list of commits in the PR for the purpose of checking DCO) and so that it could be easily run without CI, like on a developer machine, or via CI but on a fork.  If those use cases aren't important anymore, this seems OK (although I'm not sure I understand the harm that the `git fetch` is causing in CI?).

**Comment by tiborvass** [comment]
@tianon it would still run the same on dev machine. We do git fetch and git merge in CI before running anything, so it is redundant in CI. The reason I need this is because I needed ssh credentials to git fetch the downstream private EE fork, and I thought it was fine to just remove the redundancy instead.

**Review by andrewhsu — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tiborvass could you answer @tianon's question?

**Comment by tiborvass** [comment]
@thaJeztah which part specifically didn't I answer in https://github.com/moby/moby/pull/38677#issuecomment-460471070 ? This PR is not changing anything by default, it adds the possibility to remove git fetch redundancy (when done outside) instead of messing with credentials for private repos.

**Comment by thaJeztah** [comment]
> which part specifically didn't I answer in [#38677 (comment)](https://github.com/moby/moby/pull/38677#issuecomment-460471070) ?

I guess this part wasn't mentioned (but can't answer for @tianon what exactly wasn't clear to him 🤗);

> instead of messing with credentials for private repos.

**Review by thaJeztah — APPROVED** [review]
change LGTM

**Comment by tianon** [comment]
Fair enough, LGTM too

**Comment by tiborvass** [comment]
@tianon @thaJeztah thank you guys!

**Pull request merged**
