### PR TITLE
Allow partial name match for service ls --filter, node ls --filter, node tasks --filter

### LINKED ISSUE #24112: `docker service tasks --filter name=` filters on `service`
Related issue: #24108

According to https://github.com/docker/docker/blob/master/docs/reference/commandline/service_tasks.md#name 
>The name filter matches on task names.

This is not true: It filters on **exact service names**, which does not make sense because you also have to specify the service name as a mandatory argument.

```bash
# we have a service "top" with 3 tasks.
$ docker service tasks top
ID                         NAME   SERVICE  IMAGE    LAST STATE          DESIRED STATE  NODE
brscnd76m5eh8l3cvmpt5lkj4  top.1  top      busybox  Running 26 minutes  Running        bd4242800842
c4id3nmv05ivk1brv7qk5ik3e  top.2  top      busybox  Running 26 minutes  Running        04f850c4a3db
8t2qoxgr0e95w7bs0gwunf0az  top.3  top      busybox  Running 26 minutes  Running        04f850c4a3db

# This should find "top.2" but does not.
$ docker service tasks --filter name=top.2 top
ID  NAME  SERVICE  IMAGE  LAST STATE  DESIRED STATE  NODE

# Filtering on a substring won't do:
$ docker service tasks --filter name=to top
ID  NAME  SERVICE  IMAGE  LAST STATE  DESIRED STATE  NODE

# You have to specify the EXACT SERVICE name to find something.
$ docker service tasks --filter name=top top
ID                         NAME   SERVICE  IMAGE    LAST STATE          DESIRED STATE  NODE
brscnd76m5eh8l3cvmpt5lkj4  top.1  top      busybox  Running 27 minutes  Running        bd4242800842
c4id3nmv05ivk1brv7qk5ik3e  top.2  top      busybox  Running 27 minutes  Running        04f850c4a3db
8t2qoxgr0e95w7bs0gwunf0az  top.3  top      busybox  Running 27 minutes  Running        04f850c4a3db
```

### LINKED ISSUE #24270: service ls -filter by part of name not working
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 56bcl8mjs61eqh8o07ga55gve
 IsManager: Yes
 Managers: 1
 Nodes: 5
 CACertHash: sha256:3ee4c89065a92aa3a8e813ccd279cddf17b0bd0e6cf8c938ecd00434c6e3c7e6
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.625 GiB
Name: redis-cluster-us-c1-c-1
ID: YGQV:RK6L:UQ6G:CZT7:H24B:5EOK:7I2E:5DCB:QQP5:HCUL:254F:CMY7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

##### docker service ls
```
ID            NAME              REPLICAS  IMAGE                                  COMMAND
0b1mghudes95  redis-cluster-m5  1/1       jamespedwards42/alpine-redis:unstable  --protected-mode no --port 7005 --cluster-enabled yes --cluster-node-timeout 60000 --cluster-require-full-coverage no --lazyfree-lazy-expire yes --lazyfree-lazy-server-del yes --save "" --repl-diskless-sync yes --appendonly yes --appendfsync everysec --auto-aof-rewrite-percentage 20
0zt74ab9auq9  redis-cluster-m4  1/1       jamespedwards42/alpine-redis:unstable  --protected-mode no --port 7004 --cluster-enabled yes --cluster-node-timeout 60000 --cluster-require-full-coverage no --lazyfree-lazy-expire yes --lazyfree-lazy-server-del yes --save "" --repl-diskless-sync yes --appendonly yes --appendfsync everysec --auto-aof-rewrite-percentage 20
```

##### docker service ls --filter name=redis-cluster-m5 (works as expected)

```
ID            NAME              REPLICAS  IMAGE                                  COMMAND
0b1mghudes95  redis-cluster-m5  1/1       jamespedwards42/alpine-redis:unstable  --protected-mode no --port 7005 --cluster-enabled yes --cluster-node-timeout 60000 --cluster-require-full-coverage no --lazyfree-lazy-expire yes --lazyfree-lazy-server-del yes --save "" --repl-diskless-sync yes --appendonly yes --appendfsync everysec --auto-aof-rewrite-percentage 20
```

##### docker service ls --filter name=redis-cluster (unexpected 0 results)

```
ID  NAME  REPLICAS  IMAGE  COMMAND
```

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #24270 where it was not possible to have a partial name match when list services with name filter.

**\- How I did it**

This fix updates swarmkit and allows prefix search when name is provided as the filter for listing services.

**\- How to verify it**

An additional integration test is added to cover the changes.

**\- Description for the changelog**

Allow partial name match for `service ls --filter`.

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #24270.
This fix fixes #24112.

**Note: A separate pull request has been opened on swarmkit:**
**https://github.com/docker/swarmkit/pull/1168**

**NOTE: this fix also includes partial filters for nodes and tasks.**

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! design LGTM, but let's wait for review in SwarmKit

/cc @stevvooe

**Comment by yongtang** [comment]
@thaJeztah I updated the PR to address the additional feedbacks from SwarmKit repo. As part of the update, I think #24112 will be fixed by this PR as well.

Please let me know if there are any issues.

**Comment by yongtang** [comment]
@thaJeztah I think this PR should fix #24108 as well.

**Comment by vdemeester** [comment]
Waiting for the PR in swarmkit, but design LGTM 🐹

**Comment by yongtang** [comment]
@thaJeztah @vdemeester The pull request has been updated with swarm kit re-vendored to `9ee5fc3b8db5de8c8593a57bc45fc178f74ceee1`.

Please let me know if there are any issues.

**Comment by vdemeester** [comment]
LGTM 🐸
/cc @thaJeztah @aaronlehmann @stevvooe @tiborvass

**Comment by aaronlehmann** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks! However, it looks like there's an issue with the `docker service tasks` filter;

Given the following:

```
docker service tasks web
ID                         NAME   SERVICE  IMAGE         LAST STATE                  DESIRED STATE  NODE
7x9ge2a191s2wzzftmkdhu6pe  web.1  web      nginx:latest  Running 3 minutes ago       Running        4dd854eb9e86
7rmuw5ikpxsuuuim24630v2sb  web.2  web      nginx:latest  Running about a minute ago  Running        4dd854eb9e86
2y5s1hrdi6ahdeuxkil7jotn4  web.3  web      nginx:latest  Running about a minute ago  Running        4dd854eb9e86
0cap892rvl8byr8ikte8o1p3c  web.4  web      nginx:latest  Running about a minute ago  Running        4dd854eb9e86
```

Using a `--filter name=whatever` doesn't actually do anything, because it's filtering on the `service` name, but `docker service tasks` already requires `[service]` so only shows tasks for a single service. For example:

```
docker service tasks --filter name=web web
ID                         NAME   SERVICE  IMAGE         LAST STATE             DESIRED STATE  NODE
7x9ge2a191s2wzzftmkdhu6pe  web.1  web      nginx:latest  Running 7 minutes ago  Running        4dd854eb9e86
7rmuw5ikpxsuuuim24630v2sb  web.2  web      nginx:latest  Running 5 minutes ago  Running        4dd854eb9e86
2y5s1hrdi6ahdeuxkil7jotn4  web.3  web      nginx:latest  Running 5 minutes ago  Running        4dd854eb9e86
0cap892rvl8byr8ikte8o1p3c  web.4  web      nginx:latest  Running 5 minutes ago  Running        4dd854eb9e86
```

Shows all tasks, because the filter matches the service name, not the name of individual tasks, as can be seen by:

```
docker service tasks --filter name=web.2 web
ID  NAME  SERVICE  IMAGE  LAST STATE  DESIRED STATE  NODE
```

Which doesn't show the `web.2` task

**Comment by yongtang** [comment]
Thanks @thaJeztah @aaronlehmann @vdemeester for the review.

It seems that at the moment, Tasks are only indexed by Service names (`e.ServiceAnnotations.Name`) and task names are not actually stored in the memdb. When tasks are ready to be print out, the service name is only concatenated with the slot ID (`e.Slot`) to get the task names (e.g. `web.2` task).

I think it might be possible to index `e.ServiceAnnotations.Name`+`.`+`e.Slot` in memdb. Let me do some investigation to see if I could create a pull request in swarmkit.

**Comment by yongtang** [comment]
@aaronlehmann @thaJeztah @vdemeester A pull request on swarmkit has been created:
https://github.com/docker/swarmkit/pull/1193

Please let me know if there are any issues.

**Comment by thaJeztah** [comment]
@yongtang I suggest to remove the `docker service tasks` filter from this PR, and open a separate PR for that, also given that PR https://github.com/docker/docker/pull/24816 was opened. We'll have to remove the "fixes xyz" for https://github.com/docker/docker/issues/24108, and https://github.com/docker/docker/issues/24790 from the description then.

Would that work for you?

**Comment by yongtang** [comment]
@thaJeztah Sure let me update the pull request shortly.

**Comment by yongtang** [comment]
Thanks @thaJeztah the pull request has been updated. Will open another pull request to cover the `service tasks --filter` case shortly.

**Comment by yongtang** [comment]
@thaJeztah Another PR #24850 has been opened for `service tasks --filter`. Please let me know if there are any issues.

**Comment by thaJeztah** [comment]
Thanks @yongtang, that's great! I'll review this PR shortly, as I think it's ready to merge now

**Comment by thaJeztah** [comment]
I tested this locally for;

- `docker node ls --filter name=..`,
- `docker node tasks --filter name=... self`
- `docker service ls --filter name=...`

and all works as expected, thank you @yongtang!

Documentation was already describing this behavior, so no changes are needed there

LGTM :tada:

**Comment by albers** [comment]
Thanks for fixing!

**Comment by cazacugmihai** [comment]
This patch works only when using a prefix for the service name. It is not searching inside the string.

E.g.:

Service name: `some_service_name`
Filter 1 (it works): `docker service ls --filter name=some`
Filter 2 (doesn't work): `docker service ls --filter name=_service`
Filter 3 (doesn't work): `docker service ls --filter name=name`

**Pull request merged**
