### PR TITLE
vendor: update golang/net to c427ad74c

### PR DESCRIPTION
**Pull request by tonistiigi**
Our patches were merged to upstream. No reason to vendor a fork anymore.

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
CI failures @tonistiigi

**Comment by AkihiroSuda** [comment]
Failures in arm https://jenkins.dockerproject.org/job/Docker-PRs-arm/357/console

```
02:12:56.174 FAIL: docker_cli_logs_test.go:221: DockerSuite.TestLogsFollowSlowStdoutConsumer
02:12:56.174 
02:12:56.174 docker_cli_logs_test.go:250:
02:12:56.174     c.Assert(actual, checker.Equals, expected)
02:12:56.174 ... obtained int = 128976
02:12:56.174 ... expected int = 200000
```

```
03:48:10.303 FAIL: check_test.go:371: DockerSwarmSuite.TearDownTest
03:48:10.303 
03:48:10.303 unmount of /tmp/docker-execroot/d34cd89de1724/netns failed: invalid argument
03:48:10.303 unmount of /tmp/docker-execroot/d34cd89de1724/netns failed: no such file or directory
03:48:10.303 check_test.go:376:
03:48:10.303     d.Stop(c)
03:48:10.303 daemon/daemon.go:389:
03:48:10.303     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
03:48:10.304 ... Error: Error while stopping the daemon d58a942127fa9 : exit status 130
03:48:10.304 
```

```
03:48:10.311 PANIC: docker_api_swarm_test.go:683: DockerSwarmSuite.TestAPISwarmRaftQuorum
03:48:10.311 
03:48:10.311 [d34cd89de1724] waiting for daemon to start
03:48:10.311 [d34cd89de1724] daemon started
03:48:10.311 
03:48:10.311 [d58a942127fa9] waiting for daemon to start
03:48:10.311 [d58a942127fa9] daemon started
03:48:10.311 
03:48:10.311 [d7c3ce85db803] waiting for daemon to start
03:48:10.311 [d7c3ce85db803] daemon started
03:48:10.311 
03:48:10.311 [d58a942127fa9] exiting daemon
03:48:10.311 [d7c3ce85db803] exiting daemon
03:48:10.311 [d58a942127fa9] waiting for daemon to start
03:48:10.311 [d58a942127fa9] daemon started
03:48:10.311 
03:48:10.311 [d34cd89de1724] exiting daemon
03:48:10.311 [d58a942127fa9] daemon started
03:48:10.311 Attempt #2: daemon is still running with pid 19236
03:48:10.311 Attempt #3: daemon is still running with pid 19236
03:48:10.311 Attempt #4: daemon is still running with pid 19236
03:48:10.311 [d58a942127fa9] exiting daemon
03:48:10.311 ... Panic: Fixture has panicked (see related PANIC)
```

**Comment by LK4D4** [comment]
Looks like something became slower :/

**Comment by AkihiroSuda** [comment]
arm seems deterministically failing.. can we somehow bisect?

**Comment by tonistiigi** [comment]
That test has been flaky in other PRs as well. #30489 29030 Giving it another go.

**Comment by LK4D4** [comment]
Maybe new context is slower, I dunno :/

**Comment by LK4D4** [comment]
Or maybe our arm machines became slower.
Anyway, this PR LGTM

**Comment by tonistiigi** [comment]
Now it is failing in master as well
https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/4658/console
https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/4660/console

So not related to this PR but either we had a regression or this is a bad test and timing changed in arm machines.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
