### PR TITLE
vendor: bump github.com/aws/aws-sdk-go-v2 to v1.24.1

### PR DESCRIPTION
**Pull request by vvoland**
- unblocks: https://github.com/moby/moby/pull/47364

In preparation for buildkit v0.13

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vvoland** [comment]
```
=== Failed
=== FAIL: daemon/logger/awslogs TestNewAWSLogsClientUserAgentHandler (0.00s)
    cloudwatchlogs_test.go:146: assertion failed: error is not nil: not found, ResolveEndpointV2

=== FAIL: daemon/logger/awslogs TestNewAWSLogsClientLogFormatHeaderHandler/json/emf (0.00s)
    cloudwatchlogs_test.go:189: assertion failed: error is not nil: not found, ResolveEndpointV2

=== FAIL: daemon/logger/awslogs TestNewAWSLogsClientLogFormatHeaderHandler/#00 (0.00s)
    cloudwatchlogs_test.go:189: assertion failed: error is not nil: not found, ResolveEndpointV2

=== FAIL: daemon/logger/awslogs TestNewAWSLogsClientLogFormatHeaderHandler (0.00s)

=== FAIL: daemon/logger/awslogs TestNewAWSLogsClientAWSLogsEndpoint (0.00s)
    cloudwatchlogs_test.go:220: assertion failed: error is not nil: not found, ResolveEndpointV2

=== FAIL: daemon/logger/awslogs TestNewAWSLogsClientCredentialEndpointDetect (0.00s)
    cloudwatchlogs_test.go:1688: assertion failed: error is not nil: not found, ResolveEndpointV2
```

@stewartsmith @PeterCai7 are you able to help with these failures? 👀

**Comment by crazy-max** [comment]
Argh didn't recall the aws sdk was used on moby sorry for that. Will be keep that in mind next time we bump these dependencies on buildkit.

About tests issue it seems related to https://github.com/aws/aws-sdk-go-v2/issues/2370#issuecomment-1814903382 so I guess you need to bump `github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs` to a more recent version.

**Comment by crazy-max** [comment]
https://github.com/moby/moby/actions/runs/7904361943/job/21576367616#step:6:20

```
daemon/logger/awslogs/cloudwatchlogs.go:412:35: SA1019: cloudwatchlogs.WithEndpointResolver is deprecated: EndpointResolver and WithEndpointResolver. Providing a value for this field will likely prevent you from using any endpoint-related service features released after the introduction of EndpointResolverV2 and BaseEndpoint. To migrate an EndpointResolver implementation that uses a custom endpoint, set the client option BaseEndpoint instead. (staticcheck)
```

Looks similar to https://github.com/moby/buildkit/pull/4160/commits/ba7b9497849d1ec362ab0daa1bf444149773ac52

**Comment by vvoland** [comment]
Thanks!

**Review by crazy-max — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM, thank you! And massive thank you to @crazy-max !

**Pull request merged**
