### PR TITLE
devmapper: recognize vxfs

### PR DESCRIPTION
**Pull request by runcom**
Should recognize vxfs as highlighted in #22936

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
ping @rhvgoyal

**Comment by thaJeztah** [comment]
failure could be genuine 

```
6:50:29 --- FAIL: TestDevmapperCreateBase (0.06s)
16:50:29 	graphtest_unix.go:122: stat /tmp/docker-graphtest-079240530/devicemapper/mnt/Base/rootfs/a subdir: no such file or directory
16:50:29 --- FAIL: TestDevmapperCreateSnap (0.00s)
16:50:29 	graphtest_unix.go:219: devmapper: device Base already exists. 
```

**Comment by runcom** [comment]
Yeah failure is genuine, waiting for Vivek to chime in - otherwise I'll just remove the last commit

**Comment by thaJeztah** [comment]
Would be really nice if we could though - less code to maintain and keep in sync

**Comment by runcom** [comment]
@thaJeztah the second commit now fix the second test you highlighted in https://github.com/docker/docker/pull/23080#issuecomment-222322463 (because cleanups were flacky..)

**Comment by thaJeztah** [comment]
LGTM (but would still be in favor of having https://github.com/docker/docker/pull/23080#issuecomment-222315382 some day, if possible)

**Comment by runcom** [comment]
@amoalsale could you test this out by any chance?

**Comment by rhvgoyal** [comment]
I put the comment in original issue. Here devicemapper seems to be reporting the filesystem of thin device and not filesytem of /var/lib/docker. And that sounds like right thing to do.

**Comment by runcom** [comment]
@rhvgoyal yeah, this is just making sure we recognize vxfs though. This PR should definitely fix https://github.com/docker/docker/issues/14847 (which hadn't)

**Comment by rhvgoyal** [comment]
@runcom, I don't think this is needed. There will not be vxfs filesystem on top of thin devices to begin with. So what's the point in allowing that in probe function. 

Look at dm.fs, we allow either ext4 or xfs as valid file systems on top of thin devices.

**Comment by runcom** [comment]
@rhygoyal alright, how does https://github.com/docker/docker/issues/14847 run devicemapper and vxfs and got "Backing Fs: unknown" ?

**Comment by rhvgoyal** [comment]
@runcom, It must be old docker. They seem to be running docker 1.6, Is it happening with latest docker too?

**Comment by thaJeztah** [comment]
@rhvgoyal see https://github.com/docker/docker/issues/22936

**Comment by rhvgoyal** [comment]
@thaJeztah I looked at that issue. BackingFilesystem being reported is xfs and that's right. Filesystem backing imags/containers is xfs (and not vxfs). 

vxfs is on host which is being used to store container metadata. This is like having ext4 as your rootfs on host and using xfs on top of thin devices. In that case also BackingFilesystem will be reported as "xfs" and not "ext4".

So I am failing to understand what problem we are trying to solve.

**Comment by thaJeztah** [comment]
looks like we should close this, @runcom?

**Comment by runcom** [comment]
Right

**Pull request closed without merging**
