### PR TITLE
Return of the Ring: Metadata Labels Doc Tweaks

### PR DESCRIPTION
**Pull request by moxiegirl**
Updating with Sven's comments and other tweaks; minor but cleanup things we didn't want to tie the original PR down with.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @SvenDowideit @jamtur01 @fredlf @spf13

**Comment by jamtur01** [comment]
LGTM

**Comment by moxiegirl** [comment]
LGTM on my end too.  Thanks James

**Comment by thaJeztah** [comment]
@moxiegirl thanks for this, it's looking a lot better. I originally started writing this, but ran out of time (and steam), so submitted this as a "draft". Happy that it's corrected, much appreciated!

**Comment by moxiegirl** [comment]
@thaJeztah Happy to help. :-)

**Pull request merged**
