### PR TITLE
Clarifying structure in light of Kitematic

### PR DESCRIPTION
**Pull request by moxiegirl**
Restructure to eliminate unnecessary head.
Clarify use of command-line for project contribution in light of Bday.
Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
@jamtur01 @SvenDowideit @fredlf @spf13

**Comment by jamtur01** [comment]
Seems reasonable. LGTM

**Comment by SvenDowideit** [comment]
LGTM

**Comment by thaJeztah** [comment]
Really minor nit; missing newline at end of file; just noticed that and no reason to prevent merging (IMO)

**Pull request merged**
