### PR TITLE
Add bash symbol for sudo

### PR DESCRIPTION
**Pull request by yu8833**
Signed-off-by: YuPengZTE yu.peng36@zte.com.cn

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Change LGTM, but I don't understand the PR title. Can you revise please? Thanks.

**Comment by YuPengZTE** [comment]
Thanks @jhowardmsft, the PR title is changed.

**Comment by jhowardmsft** [comment]
LGTM. @thajeztah

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Pull request merged**
