### PR TITLE
Update ubuntulinux.md add a note to user

### PR DESCRIPTION
**Pull request by tracylihui**
Remind user to exclude /var/lib/docker from backup software to avoid running out of your space.
Signed-off-by: tracylihui 793912329@qq.com
related issure #17795

### CODE REVIEW

**Comment by calavera** [comment]
I don't think that document is the best place to put a not like that.

**Comment by HackToday** [comment]
I agree with @calavera   seems that docment is not needed to have note like that.  it seems some user practice cases.

**Comment by HackToday** [comment]
@thaJeztah  may have more options about this

**Comment by thaJeztah** [comment]
Hm, I'm not sure either. At *least* not in this section. The linked issue feels very specific to me, and we only had *one* report of a user running into this (and with this particular software), so I'm inclined to say we shouldn't document it (we cannot document all possible combinations of software).

If we *do* want to add this information, we should probably be very specific about it (which software), possibly in a "known issues" section, just as here https://github.com/docker/docker/blob/eb729a0cb0be1f2d2ba5c616fcd4e585289f6dfc/docs/installation/linux/oracle.md#known-issues

But my first thought is to not document it.

**Comment by calavera** [comment]
Thanks for putting this together @tracylihui. Following other contributors' opinions, I'm going to close this PR as won't fix.

**Pull request closed without merging**
