### PR TITLE
Windows [TP4]: Adds support for Hyper-V Containers

### PR DESCRIPTION
**Pull request by lowenna**
@jstarks This adds the --isolated flag to allow a container to be run as a Hyper-V Container rather than a Windows Server Container.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Do you see a need for a mixed-mode daemon?
Personally I would rather see this as an exec-opt on the daemon rather than changing this on run.

**Comment by jhowardmsft** [comment]
@cpuguy83 Oh yes, definitely - fully expect to run containers of both types simultaneously.

**Comment by jasonwilliams200OK** [comment]
@jhowardmsft, 

[sorry for the buzz. I know this is a very busy & restrictive repository and people don't appreciate getting pinged etc. but I would like to take my chances (o|o)]

I have learned this much that docker is not a Virtual Machine, but with Windows in the mix along with FreeBSD, what is and isn't offered by docker for software release automation. That is the real concern.

Can you please point me to some documentation / issue / blog post etc. which shed some light on "Docker support for Windows [Nano] Server" <- and what does it really mean? 

I have found https://dscottraynsford.wordpress.com/2015/08/27/docker-and-containers-on-nano-server-continued/, but the guy seems to be experimenting on his own without any clue what is the roadmap here.. 

Does this mean at some point in future, we will be able to launch Docker running Windows Nano Server from Linux as well as from Windows clients (8x,10) etc.? So, for example, if I want to frequently build a binary with MSVCR, I would spin up a Windows docker (step-wise recipe in Dockerfile), build a binary, copy it to local and dispose off? -- all on the fly, without GUI, just CLI, slimmest OS+buildtools size possible.. {now i am dreaming}

```bash
# My ultimate objective:
#
# this is Linux
# cd into some dir, where Dockerfile resides

docker build --tag make-machine .
docker run make-machine cat /me-lib/bin/bins.tar.gz > bins.tar.gz
tar -zxvf bins.tar.gz

# ^ I use this workflow to obtain release binaries for Linux, built on old CentOS5 in docker,
# running on top of latest Ubuntu, to keep the backward compatibility with oldest possible Linux.
# it takes 27 steps and 20-30 minutes to download OS+buildtools and building of all binaries flavors.

# My aim is to have this workflow for more / all target operating systems of our software 
```

**Comment by taylorb-microsoft** [comment]
@jasonwilliams200OK,
We are building support into the Windows operating system for the underlying container primitives (things like namespaces and file/registry virtualization) that are enabling the docker engine to be-cross complied for Windows (by virtue of all the hard work folks like @jhowardmsft are doing...).  What this means is that on Windows Server 2016 you will be able to create a Windows container in the same way that on Linux you can create a Linux container (both via Docker Run).  Containers share the same kernel as there host so you can't take a Linux container and run it on Windows or vice-verse.

Also specifically on Nano Server, this is a new installation option for Windows Server being introduced in Windows Server 2016.  Containers will support both Nano Server and Server Core as the container OS (what the container sees) as well as running on both Nano Server and Server Core host os's.

If you want to read up more I would recommend our documentation landing page:  http://aka.ms/windowscontainers and or Chad (from Docker) and myself did a container 101 video that might be helpful https://channel9.msdn.com/Blogs/containers/Containers-101-with-Microsoft-and-Docker.  

-Taylor

**Comment by tiborvass** [comment]
I'm not sure I'm fond of `--isolated`. We could maybe try it for the experimental channel.

**Comment by jhowardmsft** [comment]
Urrrm - Windows doesn't build experimental, and we need something like this to allow Hyper-V Containers to be launched for TP4. Open to suggestions....

**Comment by cpuguy83** [comment]
Anyone else thoughts on this flag?
IMO, this is seems like a daemon-level opt.

**Comment by bboreham** [comment]
I may not understand all the background here, but it seems to me that a similar feature is being implemented by other platforms - "Clear Containers", "vSphere Integrated Containers", etc., so if you add some UX for it in the Docker CLI it should be generic enough to target all of them and not be coded as a Hyper-V-specific feature.

Then, I wouldn't make it a binary choice - isolated or all-together.  You might also have a group of containers that run in the same isolation boundary, but separate from other containers.

**Comment by jhowardmsft** [comment]
@bboreham I've no idea what other platforms are doing. However, in Windows Server, it really is a binary choice, and there has to be something in docker for support of Hyper-V containers as well as Windows Server Containers in TP4. There are no currently plans for a third type of container.

@cpuguy83 This absolutely should not be a daemon parameter. We are fully expecting users to be able to run Hyper-V Containers and Windows Server Containers simultaneously on the same container host.

**Comment by bboreham** [comment]
@jhowardmsft if your intention is to contribute a hook to a feature of one specific platform, wouldn't it be better to name it more specifically, e.g. `--hyperv-isolated`?

An alternative idea would be to indirect via the label mechanism, i.e. `--label com.microsoft.isolation=hyperv`.  That way you wouldn't need to change the cross-platform code and would get an added feature that users could filter on this attribute.

**Comment by jhowardmsft** [comment]
Is it not the case that there are already multiple Unix-specific run settings which (at least in the case of NS settings will never be applicable to Windows)? For example `ipc`; `lxc-conf`; `memory-swappiness`; `oom-kill-disable`; `ulimit`; `uts`; `cpuset-mems`; `cgroup-parent`. I don't understand why the pushback.

Remember we need to make this **easy** for users to use. Less is more in terms of input. 

@taylorb-microsoft Please can you advise what should be done....

**Comment by jhowardmsft** [comment]
Rebased.

**Comment by bboreham** [comment]
Well, that's an illustration of why it's worth debating and trying to get right: once you put an option into the mainline and people start to rely on it, you can never take it out again.  That said, all the examples you cite are rather cryptic, not a standard English word like "isolated".

Personally I don't think you can take a subject like kernel-isolation versus hypervisor-isolation and make it "easy" by picking a shorter word to name the option.

**Comment by jhowardmsft** [comment]
Then again, you could argue that the Linux args are incomprehensible, which is somewhat defeatist when a regular Joe user attempts to use the system. Common English wins every time IMO.

**Comment by bboreham** [comment]
All containers are isolated, in some sense.  How about:

    --isolation=hyperv      - this is the option you want to implement
    --isolation=namespaces  - Docker current default on Linux
    --isolation=vic         - imaginary future option for vSphere Integrated Containers

**Comment by jhowardmsft** [comment]
That's not too bad. But would probably have `--isolation=default` rather than `--isolation=namespaces` which would mean the default on Linux (LXC) or Windows (Windows Server Containers). I can prototype that up.

**Comment by jhowardmsft** [comment]
@bboreham @cpuguy83 @taylorb-microsoft 

Updated to `--isolation=default` (LXC on Linux, Windows Server Container on Windows) and `--isolation=hyperv` (Only valid on Windows, means Hyper-V Container). PTAL.

**Comment by calavera** [comment]
I don't see linux using this flag any time soon, but I like the `option=value` better than the boolean flag. Let's move it forward. Moving to code review.

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
I would prefer moving `--exec-driver` to `run` and `create` and use that instead of `--isolation`.

**Comment by jhowardmsft** [comment]
@tiborvass Not sure I understand that comment, sorry. This doesn't relate to a choice of exec driver...

**Comment by thaJeztah** [comment]
I think what @tiborvass means, is that "Hyper-V" and "Windows Server Containers" could really be seen as different exec drivers, just as "LXC" and "Native" are different drivers (but both using namespaces under the hood).

By allowing `--exec-driver` to be specified on `docker run` and `docker create`, it would be possible to specify the exec-driver to use *per container*, instead of globally, and thus run containers using different exec-drivers simultaneously.

In future, the same could be implemented on Linux if new/more exec-drivers are added.

Implementing "Hyper-V" and "Windows Server Containers" as separate "drivers" (possibly just being a wrapper for the same driver under the hood), gives a cleaner separation IMO

Just thinking out loud here :)

**Comment by jhowardmsft** [comment]
Oh I see. In some ways, I'd tend to see that as being a case of UX being driven by internals of the docker codebase (even though it's strictly not two exec drivers). Whereas I think from an end user perspective, Hyper-V vs Windows Server container is more aligned to being a property of the container at runtime. I did want to clarify though what is currently in the PR isn't global - it is "per container".

I don't have a strong preference either way, but felt having something aligned to user UX was slightly easier. I understand that should Linux ever introduce something like Hyper-V containers, it may well be a different exec driver under the covers though, while as on Windows it is just a mode-switch.

Happy to go any way you guys want with the choice of word.

**Comment by crosbymichael** [comment]
@jhowardmsft once question.  How does the networking stack work with hyperv and regular windows containers?  Is it the same to the user?

**Comment by jhowardmsft** [comment]
Yes, it's the same. We aren't aware of anything we need to differentiate currently.

**Comment by crosbymichael** [comment]
Ok, this change seems ok to me.  We just need to decided if this should be a separate exec driver or an attribute of a container.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
