### PR TITLE
Jenkinsfile: fix typo buidx -> buildx

### PR DESCRIPTION
**Pull request by CoRfr**
**- What I did**
I noticed a typo when looking at past commits (c04ea1133d / #39340 )

**- How I did it**
N/A

**- How to verify it**
I didn't.

**- Description for the changelog**

Fix Jenkinsfile buidx typo

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by CoRfr** [comment]
@cpuguy83

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
For reference, this is an issue on the master builds: https://ci.docker.com/public/blue/organizations/jenkins/moby/detail/master/205/pipeline

Just going to merge because it's obviously broken and this is a simple fix.

Thanks @CoRfr

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
