### PR TITLE
Test that non root user cannot use default capabilities

### PR DESCRIPTION
**Pull request by justincormack**
Test for #27590 for 1.12.3

puppy-broken

### CODE REVIEW

**Comment by justincormack** [comment]
cc @vieux

**Comment by NathanMcCauley** [comment]
Would it make sense to have additional tests for file read, file write, file create, etc?

**Comment by justincormack** [comment]
@NathanMcCauley I guess it makes sense to have one test for each of the capabilities we grant to root by default, yes, will add.

**Comment by riyazdf** [comment]
current tests LGTM, @justincormack did you have ideas for testing the other capabilities?  I know we were trying to brainstorm -- I'm good with addressing those in a follow-up if we'd like to fast-track this PR.

**Comment by justincormack** [comment]
@riyazdf waiting for https://github.com/docker/docker/pull/27610 to be merged before the tests will actually pass. Happy to do the rest in a second PR, some of them are a bit more complicated.

**Comment by vieux** [comment]
@justincormack I just merged #27610

**Comment by vieux** [comment]
@justincormack looks legit:

```
FAIL: docker_cli_run_unix_test.go:1141: DockerSuite.TestUserNoEffectiveCapabilities
16:25:31 
16:25:31 docker_cli_run_unix_test.go:1186:
16:25:31     c.Assert(err, check.IsNil)
16:25:31 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc822baeae0), Stderr:[]uint8(nil)} ("exit status 127")
```

**Comment by justincormack** [comment]
@vieux yes, I missed the fact that `syscall-test` needs to be updated in two places. Split into multiple tests and fixed some minor issues, its passing locally now.

**Comment by vieux** [comment]
@justincormack should I merge or wait for more test ?

**Comment by riyazdf** [comment]
@justincormack: thanks for refactoring the tests and adding more cases for root dropping them!

These additions LGTM, and I'm fine with a followup PR on the remaining TODOs depending on how complicated you think they'll be.

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
Checked with @justincormack, and this is already present in master, so removing the "merge-to-master" label

**Pull request merged**
