### PR TITLE
Cherry picks for 1.12.0 rc5

### PR DESCRIPTION
**Pull request by tiborvass**
- [#23657](https://github.com/docker/docker/pull/23657)
  - 8352089 Added daemon.json Windows example
- [#23862](https://github.com/docker/docker/pull/23862)
  - 57e1471 all: fix usage of some variables
- [#24566](https://github.com/docker/docker/pull/24566)
  - acbe38a fix the docker run --readonly example. rename '/icanwrite here' to '/icanwrite/here'
- [#24560](https://github.com/docker/docker/pull/24560)
  - 3c6ef4c docs: remove executiondriver from API 1.24 docs
- [#24579](https://github.com/docker/docker/pull/24579)
  - a44e71c bash completion for `docker service {create,update} --registry-auth`
- [#24581](https://github.com/docker/docker/pull/24581)
  - a394490 Update bash completion for `docker service {create,update} {--mode,--endpoint-mode}`
- [#24301](https://github.com/docker/docker/pull/24301)
  - f5940ef Add IPVLAN and DUMMY to check-config.sh
- [#24583](https://github.com/docker/docker/pull/24583)
  - c4846f6 Change bash completion for `docker run --net*` to `--network*`
- [#24562](https://github.com/docker/docker/pull/24562)
  - c6b7bd1 Remove "Yes"/"No" and use "true"/"false" consistently in `docker info`
  - ea365e4 Make labels human readable
- [#24573](https://github.com/docker/docker/pull/24573)
  - cabc5b2 Vendoring libnetwork 905d374
  - ed6641a Handle ingress sbox creation gracefully
- [#24525](https://github.com/docker/docker/pull/24525)
  - e4a024d Remove --command flag for service update
- [#24565](https://github.com/docker/docker/pull/24565)
  - 477a5f8 docs: fix output of node inspect
- [#24516](https://github.com/docker/docker/pull/24516)
  - a894aec Add --oom-score-adjust to daemon
- [#24591](https://github.com/docker/docker/pull/24591)
  - 7bf0faf Remove shorthand flags for "mount", "pretty", and "no-resolve"
- [#24195](https://github.com/docker/docker/pull/24195)
  - 3464589 Vendor go-shlex.
  - 674d227 Merge service command and args as a string.
- [#24598](https://github.com/docker/docker/pull/24598)
  - e1e310e bash completion for `docker daemon --oom-score-adjust`
- [#24592](https://github.com/docker/docker/pull/24592)
  - 4d87f90 Remove dead code for "inspect --pretty"
- [#24607](https://github.com/docker/docker/pull/24607)
  - 08ae4e5 Fix service inspect --pretty.
- [#24615](https://github.com/docker/docker/pull/24615)
  - 6de8fcb Use spaces, not tabs, to format sample "swarm join" command
- [#23773](https://github.com/docker/docker/pull/23773)
  - dc33fc1 Add remove flags for service update
  - ead1f62 PR feedback
  - 4c6faa4 Change the add/update flags to include 'add'
  - 3249c1d Fix multi-remove during service update.
- [#24588](https://github.com/docker/docker/pull/24588)
  - 3050d9a Expand the documentation of "no-new-privileges"
- [#24628](https://github.com/docker/docker/pull/24628)
  - dbe310e Update service update commandline reference docs
  - cc651bc Update service inspect --pretty reference docs
- [#24630](https://github.com/docker/docker/pull/24630)
  - 5bf46cc Status code 409 received when conflicting name when creating container
- [#24593](https://github.com/docker/docker/pull/24593)
  - 8e9fbc8 Fix data race in libcontainerd
- [#24568](https://github.com/docker/docker/pull/24568)
  - 1e0b753 Vendor distribution changes
  - 19d48f0 Allow v1 search to use v2 auth with identity token
- [#24640](https://github.com/docker/docker/pull/24640)
  - c37da17 docs: correct the placement constraints `docker service` example
- [#24654](https://github.com/docker/docker/pull/24654)
  - 7a93a87 Enable docker socket and service on fedora
  - 6780bdc State that docker supports fedora 24
- [#24147](https://github.com/docker/docker/pull/24147)
  - acb41dd Change $prog back to docker in sysvinit-redhat
- [#24665](https://github.com/docker/docker/pull/24665)
  - ba5d9f6 Rename zsh completion for 'docker {create,run} --net --net-alias' to '--network --network-alias'
- [#24667](https://github.com/docker/docker/pull/24667)
  - 64f0890 Add zsh completion for 'docker service {create,update} --registry-auth'
- [#24655](https://github.com/docker/docker/pull/24655)
  - f5fb3c6 Fix panic in stats test
- [#24669](https://github.com/docker/docker/pull/24669)
  - 92dfbc1 Fix aufs docs
- [#24666](https://github.com/docker/docker/pull/24666)
  - 5d29732 Add zsh completion for 'dockerd --oom-score-adjust'
- [#24668](https://github.com/docker/docker/pull/24668)
  - 2e6922a Update zsh completion for 'docker service {create,update} {--endpoint-mode,--mode}'
- [#24638](https://github.com/docker/docker/pull/24638)
  - cfe9d2f Delete  redundant content of 'docs/extend/plugins.md'
- [#24642](https://github.com/docker/docker/pull/24642)
  - 0b20231 Wait for the reader fifo opening to block
- [#24676](https://github.com/docker/docker/pull/24676)
  - d9e8cea Fix daemon panic use wrong graphdriver with --live-restore flag
- [#24610](https://github.com/docker/docker/pull/24610)
  - fec803f update create swarm and add nodes to use the auto-generated join command
- [#24702](https://github.com/docker/docker/pull/24702)
  - 6f9e310 fixed cut-and-paste error on description of Docker Toolbox
- [#24699](https://github.com/docker/docker/pull/24699)
  - 909c596 Only show port name if set.
- [#24599](https://github.com/docker/docker/pull/24599)
  - 698bd5a Small zsh completion fix on --pretty & --no-resolve
- [#24682](https://github.com/docker/docker/pull/24682)
  - 6ba6265 Document --oom-score-adj flag in docker run
- [#24718](https://github.com/docker/docker/pull/24718)
  - c15144c docs: update Oracle support link
- [#24714](https://github.com/docker/docker/pull/24714)
  - d0081a0 better command `docker network create -h` output
- [#24705](https://github.com/docker/docker/pull/24705)
  - 64a8317 Improve flag help consistency, and update docs
- [#24694](https://github.com/docker/docker/pull/24694)
  - 85b1fdf Increase timeout for swarm requests
- [#24646](https://github.com/docker/docker/pull/24646)
  - 21ecd5a Remove use of exec-root in plugins due to socket pathname limits.
- [#24659](https://github.com/docker/docker/pull/24659)
  - b74b46b suggested improvements for Debian install doc issue #23884
- [#24764](https://github.com/docker/docker/pull/24764)
  - db9bc51 Update vendored go-events
- [#24692](https://github.com/docker/docker/pull/24692)
  - 6dca1e6 Print plugin name on successful install, enable and disable.
- [#23878](https://github.com/docker/docker/pull/23878)
  - 4acc2c7 Windows: Always enable VT emulation
- [#24476](https://github.com/docker/docker/pull/24476)
  - e778ba2 swarm: add log driver support for services
- [#24397](https://github.com/docker/docker/pull/24397)
  - e1165cd Support node label update.
- [#24782](https://github.com/docker/docker/pull/24782)
  - f17469e Update docker load security docs
- [#24741](https://github.com/docker/docker/pull/24741)
  - 205bc6f Create zfs directory if it doesn't exist at startup.
- [#24792](https://github.com/docker/docker/pull/24792)
  - 823e161 bash completion for `docker service {create,update} --log-{driver,opt}`
- [#24791](https://github.com/docker/docker/pull/24791)
  - bc6e3c0 bash completion for `docker node update --label-{add,rm}`
- [#24722](https://github.com/docker/docker/pull/24722)
  - 4f0b510 Don't automagically add "[OPTIONS]" to usage
- [#24776](https://github.com/docker/docker/pull/24776)
  - 8fd779d Add only legacy plugins to the legacy lookup map.
- [#24804](https://github.com/docker/docker/pull/24804)
  - 04104c3 Remove docker.socket from rpm based systems
- [#23825](https://github.com/docker/docker/pull/23825)
  - 00a8a40 Add a script to generate man pages from cobra commands.
  - 25e9b06 Set Long text for volume commands so they can be used to generate man pages.
  - 47cca88 Dont run man generation as part of test-unit.
- [#24648](https://github.com/docker/docker/pull/24648)
  - 29b2714 Vendor in new containerd
  - 64483c3 Do not rely on "live" event anymore
  - c02f827 Update libcontainerd.AddProcess to accept a context
- [#24802](https://github.com/docker/docker/pull/24802)
  - 10919e8 Add documentation for stack commands
- [#24801](https://github.com/docker/docker/pull/24801)
  - 5d46273 Remove extra map lookup for volume drivers.
- [#24653](https://github.com/docker/docker/pull/24653)
  - d327765 Test rolling update.
- [#24507](https://github.com/docker/docker/pull/24507)
  - 9594ac9 add ref docs for node label
- [#24829](https://github.com/docker/docker/pull/24829)
  - 45484f5 Add zsh completion for 'docker service {create,update} --log-{driver,opt}'
- [#24828](https://github.com/docker/docker/pull/24828)
  - cdb8383 Add zsh completion for 'docker node update --label-{add,rm}'
- [#24832](https://github.com/docker/docker/pull/24832)
  - cf61cd3 Fix the usage for `service rm` command
- [#24839](https://github.com/docker/docker/pull/24839)
  - effbd2b fix duplicated usage in docs
- [#24843](https://github.com/docker/docker/pull/24843)
  - 78a5480 Fix nits in deprecated
- [#24841](https://github.com/docker/docker/pull/24841)
  - 06f3526 Rename --bundle to --file
- [#24852](https://github.com/docker/docker/pull/24852)
  - f49dc52 docs: add initial reference for "stack services"
- [#24523](https://github.com/docker/docker/pull/24523)
  - 68a9224 clarify update-delay and rolling update behavior
- [#24620](https://github.com/docker/docker/pull/24620)
  - 1d600eb Allow partial name match for `service ls --filter`
  - e734fa5 Allow partial name match for `node ls`, and `node tasks`
  - 467107c Vendor swarmkit to 9ee5fc3b8db5de8c8593a57bc45fc178f74ceee1
- [#24859](https://github.com/docker/docker/pull/24859)
  - 492fdf1 Update completions for syslog log driver options
- [#24820](https://github.com/docker/docker/pull/24820)
  - 137261f add how nodes work to how swarm works guide
- [#24864](https://github.com/docker/docker/pull/24864)
  - 9d532b5 docs: update reference docs for plugins
- [#24842](https://github.com/docker/docker/pull/24842)
  - b5503ef docs: add code-hints to builder page
- [#24563](https://github.com/docker/docker/pull/24563)
  - 3489e76 Added leader election test
- [#24866](https://github.com/docker/docker/pull/24866)
  - 83b12c0 docs: fix copy/pasta error
- [#24861](https://github.com/docker/docker/pull/24861)
  - 6c98d5b Add manual support for macvlan networks to bash completion
- [#24870](https://github.com/docker/docker/pull/24870)
  - a40b582 api/client/service: shorten to volume-opt
- [#24888](https://github.com/docker/docker/pull/24888)
  - f62e24f Clarify API behavior when older versions are called.
- [#24700](https://github.com/docker/docker/pull/24700)
  - a26bdd8 Send registry auth token for service deploy
- [#24892](https://github.com/docker/docker/pull/24892)
  - 07ef0a3 docs: improve formatting and highlighting of docker ps reference
- [#24874](https://github.com/docker/docker/pull/24874)
  - 5189e3d update libkv, fix wrong error check on zookeeper list
- [#24572](https://github.com/docker/docker/pull/24572)
  - 9414955 Extend deprecation cycle to 3 releases by default
- [#24904](https://github.com/docker/docker/pull/24904)
  - d5cbc57 Harmonize containerd commit used by all Dockerfile
- [#24925](https://github.com/docker/docker/pull/24925)
  - b2ad59e Make README less scabious
- [#24924](https://github.com/docker/docker/pull/24924)
  - 3d30155 Update the errNoManager() to conform to `swarm join-token`
- [#24930](https://github.com/docker/docker/pull/24930)
  - c4ab20c remove "secrets" from completion scripts
- [#24915](https://github.com/docker/docker/pull/24915)
  - 58ba4c3 Reorder swarm commands
- [#24885](https://github.com/docker/docker/pull/24885)
  - 8426f72 Append --registry-auth with with
- [#24907](https://github.com/docker/docker/pull/24907)
  - 9ac145d updates get started with swarm to use join-token
- [#24934](https://github.com/docker/docker/pull/24934)
  - 42b4d6e bash completion for `docker swarm join-token`
- [#24952](https://github.com/docker/docker/pull/24952)
  - 67246af api/client/service: default update parallelism to 1
- [#24960](https://github.com/docker/docker/pull/24960)
  - 933ba8d Update --update-parallelism docs
- [#24954](https://github.com/docker/docker/pull/24954)
  - 3a3f800 Fix regression on --link on bridge network
- [#24872](https://github.com/docker/docker/pull/24872)
  - 634f54a api/client/service: mount option defaults and aliases
- [#24932](https://github.com/docker/docker/pull/24932)
  - bd81df1 Change "rotate_worker_token" to "rotateWorkerToken"
  - 9a3e475 bump engine-api to ebb728a1346926edc2ad9418f9b6045901810b20
- [#24957](https://github.com/docker/docker/pull/24957)
  - d97c0a1 CLI: Change default Swarm task history retention limit.
- [#24979](https://github.com/docker/docker/pull/24979)
  - 180f8c6 Update swarm init task-history-limit docs
- [#24237](https://github.com/docker/docker/pull/24237)
  - d626875 Revendor swarmkit
  - 24d2d53 Vendor libnetwork and github.com/vishvananda/netlink
  - a0ccd0d Split advertised address from listen address
  - fca0b18 Require listen address and advertise address to be an IP address or an interface name
  - d3af5e3 Daemon changes to pass exec-root to libnetwork
- [#24994](https://github.com/docker/docker/pull/24994)
  - a04bba8 Add zsh completion for 'docker swarm join-token' command
- [#24963](https://github.com/docker/docker/pull/24963)
  - 4e959ef fix typos
- [#24961](https://github.com/docker/docker/pull/24961)
  - 83c186f Windows: Restore console mode on set mode failure
- [#24991](https://github.com/docker/docker/pull/24991)
  - c42fbc6 Fix AuthzPlugin URL fragment in docs
- [#24988](https://github.com/docker/docker/pull/24988)
  - 8f9066c Prevent network connect/disconnect on swarm scoped networks
- [#24990](https://github.com/docker/docker/pull/24990)
  - 56b78ab Vendoring libnetwork for rc5
- [#23844](https://github.com/docker/docker/pull/23844)
  - c8a99a5 Expand instructions on using systemd to manage containers
- [#23908](https://github.com/docker/docker/pull/23908)
  - 54e8bee Fix high cpu usage caused by docker stats.
- [#24997](https://github.com/docker/docker/pull/24997)
  - af83595 small nit: fix unmeaningful log
- [#25003](https://github.com/docker/docker/pull/25003)
  - 3fa9d77 make network errors less DRY
- [#24917](https://github.com/docker/docker/pull/24917)
  - edd67fd service tasks: Improve error reporting
- [#24984](https://github.com/docker/docker/pull/24984)
  - 5231c55 Prepend libcontainerd log message with "libcontainerd:"
  - ac068a1 Fix missing unlock in libcontainerd.Restore()
- [#24942](https://github.com/docker/docker/pull/24942)
  - 4a44cf1 Handle plugin shutdown when liveRestore is set.
- [#25012](https://github.com/docker/docker/pull/25012)
  - 2b7548f Add note about --entrypoint overriding default command
- [#24908](https://github.com/docker/docker/pull/24908)
  - 4016038 Treat HEALTHCHECK NONE the same as not setting a healthcheck
- [#24943](https://github.com/docker/docker/pull/24943)
  - 3585026 Revendor engine-api
  - 57ae29a Add failure action for rolling updates
- [#24207](https://github.com/docker/docker/pull/24207)
  - c406711 add run swarm mode guide
- [#24857](https://github.com/docker/docker/pull/24857)
  - 24f87f2 swarm docs: add administration guide for Managers and Raft
- [#25018](https://github.com/docker/docker/pull/25018)
  - 227c7e4 Sort plugin names in node description
- [#24856](https://github.com/docker/docker/pull/24856)
  - 91e9f38 healthcheck: do not interpret exit code 2 as "starting"
- [#24545](https://github.com/docker/docker/pull/24545)
  - a99db84 extend health check to start service
- [#25023](https://github.com/docker/docker/pull/25023)
  - 85bc319 fix panic on --label-add
- [#24967](https://github.com/docker/docker/pull/24967)
  - 40c88b8 improve error message when using ineligible network with service create

### CODE REVIEW

**Comment by tiborvass** [comment]
Hitting #25029

**Comment by thaJeztah** [comment]
LGTM, failures are unrelated

**Comment by tiborvass** [comment]
LGTM

**Comment by alexellis** [comment]
@tiborvass Hi - what's the best way to get RC4 or 'RC5' to build from docker/docker repo? Is there a tag I can checkout? I want to build on ARM.

**Comment by tiborvass** [comment]
@alexellis you can checkout the `v1.12.0-rc5` tag, but there is an ARM issue if you want to build the deb packages #25124

**Pull request merged**
