### PR TITLE
Fix TestBuildWithSession, TestBuildSquashParent using wrong daemon during test

### PR DESCRIPTION
**Pull request by thaJeztah**
These tests were spinning up a new daemon, but after the daemon was spun up, the default test-daemon was used by the client.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@vdemeester @olljanat @tiborvass PTAL 🤗

**Comment by thaJeztah** [comment]
Relates to https://github.com/moby/moby/pull/38415 / https://github.com/moby/moby/pull/37513
I found a couple more issues like this, will to a follow up.

**Comment by olljanat** [comment]
Good catch. Let's see if passes tests.... :wink:

**Comment by olljanat** [comment]
RS5 probably needs reboot once again...

**Comment by thaJeztah** [comment]
This test doesn't run on Windows, so I'd be ok with ignoring RS5 (but it's a PITA 😓)

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by thaJeztah** [comment]
Yay, 💚

**Comment by vdemeester** [comment]
@thaJeztah Sounds good :+1:

**Comment by thaJeztah** [comment]
Ok, made those changes as a follow-up (thought that would be better, as it may take longer to review, and to not block this PR if not  needed); https://github.com/moby/moby/pull/38428

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by thaJeztah** [comment]
ping @yongtang @AkihiroSuda PTAL 🤗

**Review by yongtang — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
