### PR TITLE
[ppc64le] add debian:jessie to make deb

### PR DESCRIPTION
**Pull request by tophj-ibm**
Adds debian:jessie to the list of debs we can make via
'make deb' on ppc64le.

Note: debian:jessie doesn't have any libseccomp packages at all on ppc64le, so seccomp isn't enabled. This is comparable to x86_64 debian:jessie, which doesn't have seccomp enabled because the package is too old.

Tested by running running 'make deb', and installing the resulting deb in a ppc64le/debian:jessie container.

Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>

owl delivering package

### CODE REVIEW

**Comment by tophj-ibm** [comment]
cc @justincormack

**Comment by justincormack** [comment]
Is there seccomp in backports for jessie ppc64le? I am very reluctant to add any more non seccomp builds....

Now a PR for `stretch`, that would be nice. Everyone should be using `stretch` now....

**Comment by tophj-ibm** [comment]
Oh hey, not only is there a libseccomp-dev 2.2.3 backport for jessie, but trusty as well. I'll go ahead and add both of those unless you think it should be in a separate pr.

I don't know anyone who has tested docker on stretch ppc64le which is why I did this, but I can take a look at it.

**Comment by justincormack** [comment]
Yes I think we had a discussion about adding the backports to amd64 too, and eventually didnt, although I think that was probably a bad decision...

cc @ijc25

**Comment by tophj-ibm** [comment]
@justincormack this should be updated now. 

One downside is that when installing the dependencies you will have to have backports added or the installation will fail, I don't see any way around this, but this is at least consistent with the way it's done for wheezy. 

I haven't checked 14.04.0 yet, but at least for 14.04.5, apt sources has backports enabled by default so that shouldn't be an issue for trusty as far as I can tell (still testing that one)

**Comment by tophj-ibm** [comment]
Going to close this. I probably should test this more, and I haven't heard anyone say anything about wanting a jessie deb anyway.

**Pull request closed without merging**
