### PR TITLE
Move buildkit client opts to new package

### PR DESCRIPTION
**Pull request by cpuguy83**
- updates https://github.com/moby/moby/pull/45203

Not everyone who imports the client wants to pull in all of buildkit, so move it to a separate package.

mr-ray

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Review by tonistiigi — COMMENTED** [review]
I would just call this pkg `client/buildkit` (and then `BuildkitClientOpts ` -> `ClientOpts`) but not a blocker.

**Comment by thaJeztah** [comment]
FWIW, I like @tonistiigi suggestion (I know ... bikeshed)

**Comment by cpuguy83** [comment]
It's all good.
I tend to try and stay away from having the package base name be the same as the package name of the main package its interacting with because it just makes imports annoying.
But this works.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
