### PR TITLE
vendor docker/distribution 4e17ab5d319ac5b70b2769442947567a83386fbc

### LINKED ISSUE #24360: Wrong digests on cross-repo mount and normal push
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   ad44f49
 Built:        Wed Jul  6 10:26:37 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   ad44f49
 Built:        Wed Jul  6 10:26:37 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 54
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.3-300.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44 GiB
Name: localhost.localdomain
ID: JQDM:ZDU3:BYSR:SIMJ:QGDH:GBGW:MF7Q:VYLQ:UYFD:W5KY:H4WG:PIMF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 26
 System Time: 2016-07-06T10:30:21.685332117+02:00
 EventsListeners: 0
Username: runcom
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
```bash
$ docker pull alpine

# Tag the image so when you push you'll trigger the cross-repo mount feature, I've used alpine so it will be mounted from library/alpine:
$ docker tag alpine runcom/alpine

# Now push the image and notice the Mounted from library/alpine and notice the digest
$ docker push runcom/alpine
The push refers to a repository [docker.io/runcom/alpine]
4fe15f8d0ae6: Mounted from library/alpine 
latest: digest: sha256:dc89ce8401da81f24f7ba3f0ab2914ed9013608bdba0b7e7e5d964817067dc06 size: 528

# Now repush and notice the Layer already exists (pushed twice so you can see the digest is the same)
$ docker push runcom/alpine
The push refers to a repository [docker.io/runcom/alpine]
4fe15f8d0ae6: Layer already exists 
latest: digest: sha256:3dcdb92d7432d56604d4545cbd324b14e647b313626d99b889d0626de158f73a size: 506

$ docker push runcom/alpine
The push refers to a repository [docker.io/runcom/alpine]
4fe15f8d0ae6: Layer already exists 
latest: digest: sha256:3dcdb92d7432d56604d4545cbd324b14e647b313626d99b889d0626de158f73a size: 506
```

**Describe the results you received:**
Digests are different between the first push with cross-repo mount and subsequent push with layer already exists

**Describe the results you expected:**
Digests would have been the same

**Additional information you deem important (e.g. issue happens only occasionally):**
Probably a regression because I don't see this in 1.10.3 but I can see this in 1.11.2 also

ping @aaronlehmann

### PR DESCRIPTION
**Pull request by runcom**
- Fix https://github.com/docker/docker/issues/24360
- Add a regression test (which fails w/o this vendoring of course)

This vendoring brings in https://github.com/docker/distribution/pull/1812 which is the commit needed to fix #24360 

/cc @aaronlehmann 

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
Please consider including this into 1.12 since it's breaking applications relying on 1.10.3 behavior (correct somehow) and when upgrading to 1.12 (or 1.11.2 for the matter) it fails

**Comment by runcom** [comment]
not sure what's happening with all Janky's checks here though /cc @thaJeztah

**Comment by aaronlehmann** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
