### PR TITLE
Extract $HOME usages into utils.GetHomeDir() (reopen #10358)

### PR DESCRIPTION
**Pull request by ahmetb**
Refactored getHomeDir in docker/docker to GetHomeDir in utils Currently covers all use cases on the client-side.

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by tiborvass** [comment]
Can we create a new package for this? not sure how to call it... `osutil`?

**Comment by ahmetalpbalkan** [comment]
I'll see if I can vendor that package but it will just add one more trivial dependency. Are we sure we want to do that? It seems pretty harmless to have this in "util" since the pkg already exists.

**Comment by tianon** [comment]
I'm definitely -1 on vendoring such a trivial dependency.

**Comment by tiborvass** [comment]
My position is that it's not because we have a utils package that we want to continue adding to it :)

**Comment by phemmer** [comment]
Also, `$HOME` can't be relied upon. There are many cases where the `HOME` environment variable is unset.
It's safest to use the `os/user` package.

```
package main
import (
	"fmt"
	"os"
	"os/user"
)

func main() {
	fmt.Printf("HOME: %#v\n", os.Getenv("HOME"))
	u, _ := user.Current()
	fmt.Printf("user.HomeDir: %#v\n", u.HomeDir)
}
```

```
# env -i go run test.go  
HOME: ""
user.HomeDir: "/home/phemmer"
```

**Comment by ahmetalpbalkan** [comment]
@phemmer that's actually a cleaner solution. Is there a reason why this hasn't been used in the first place? e.g. mitchellh/go-homedir mentions:

> **Why not just use `os/user`?** The built-in `os/user` package requires cgo on Darwin systems. This means that any Go code that uses that package cannot cross compile. But 99% of the time the use for `os/user` is just to retrieve the home directory, which we can do for the current user without cgo. This library does that, enabling cross-compilation.

**Comment by tianon** [comment]
We cross-compile for our official releases. :wink:

**Comment by ahmetalpbalkan** [comment]
@tianon yeah makes sense stick with this change then.

**Comment by tiborvass** [comment]
@ahmetalpbalkan @tianon I'm still voting for `pkg/home` or `pkg/homedir`. I don't want to add more stuff to utils, only remove.

**Comment by tianon** [comment]
+1 @tiborvass

**Comment by ahmetalpbalkan** [comment]
I'll work on creating pkg/homedir.

**Comment by ahmetalpbalkan** [comment]
@tiborvass @tianon so there's a possibility that @phemmer brought up, where environment variables are not set. I'm making my changes by ignoring that fact because all the code currently depends on that.

**Comment by tiborvass** [comment]
@ahmetalpbalkan fair enough!

**Comment by tianon** [comment]
Yeah, IMO that's fair.  Later on we can look to add some fallback logic
that uses "github.com/docker/libcontainer/user", if it's a concern. :+1:

**Comment by duglin** [comment]
Is there a process or set of tests someplace in our build that we could modify to grep all of our code to make sure people don't use $HOME ?  Just looking for a way to make sure something doesn't slip by our reviews.

**Comment by ahmetalpbalkan** [comment]
I just added another commit to export this to `pkg/homedir`. I'll squash into one before submitting. PTAL.

**Comment by ahmetalpbalkan** [comment]
@duglin I believe we don't have any test in place. there's some code in certain test cases and daemon-referenced packages using `os.Getenv("HOME")` or `$PATH`. I guess a validation step can be added using grep by whitelisting this file in the makefiles.

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
@mattmoor discussion about this is at #10602. https://github.com/docker/docker/pull/10602#issuecomment-73186712

**Comment by ahmetalpbalkan** [comment]
> You should also fixup the python client library to read this from the correct location:
> https://github.com/docker/docker-py/blob/40770878ad5b6fccc1b5f5866fa1167bb990f3d3/docker/auth/auth.py#L128

Umm, feel free to change it. :wink:

**Pull request merged**
