### PR TITLE
tests: Move libnetwork/testutils to internal/testutils/netnsutils

### PR DESCRIPTION
**Pull request by akerouanton**
**- What I did**

As requested by @corhere here: https://github.com/moby/moby/pull/45850#issuecomment-1648491789

**- How to verify it**

CI is green

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Whooo! The reverse of this one;

- https://github.com/moby/moby/pull/39829

So... to some extent I'm still hoping to move that other package back to `internal/`. From that perspective, slightly thinking if naming this `testutils` would paint shut some of that; wondering if we need something in the package name to make it more specific that it's "for networking" / "libnetwork", so that (if we are able to move the other testutils back to become internal) allow both to be living in `internal` without becoming _too_ confusing.

Really haven't given it a lot of thought though yet!! Any input / suggestion welcome!

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
This is probably gonna be painful for https://github.com/moby/moby/pull/45652 - perhaps we should decide in which order to merge those 🙈 (looks like https://github.com/moby/moby/pull/45652 already needs a minor rebase)

/cc @cpuguy83

**Comment by akerouanton** [comment]
> Really haven't given it a lot of thought though yet!! Any input / suggestion welcome!

This package is really about netns right now. Thus, I'm wondering if we could just name it `netnsutils` to not conflict with `github.com/vishvananda/netns`, and create a new pkg named `networking` for all the testutils I'm adding in #45850. WDYT?

**Comment by thaJeztah** [comment]
I'm good with netnsutils (it's all for testing, so doesn't have to be a pretty name)

**Comment by akerouanton** [comment]
I added a 2nd commit to put the `Logger` interface into `internal/testutils`.

**Review by neersighted — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
