### PR TITLE
runc install path changed from /usr/local/bin to /usr/local/sbin

### PR DESCRIPTION
**Pull request by tiborvass**
This is due to https://github.com/opencontainers/runc/pull/702

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by vdemeester** [comment]
LGTM 🐯
Question though : shouldn't we do the same (put things into `sbin` instead of `bin`) ?

**Comment by cpuguy83** [comment]
LGTM

Merging since CI won't test this change.

**Comment by thaJeztah** [comment]
@vdemeester possibly, but don't want to risk changing things so close to the release

**Comment by vdemeester** [comment]
@thaJeztah completely understandable :stuck_out_tongue_closed_eyes:

**Comment by tiborvass** [comment]
For reference #21941

**Pull request merged**
