### PR TITLE
Change SCALE to REPLICAS.

### LINKED ISSUE #23600: 'docker service' accepts '--replicas' but displays 'SCALE' heading
version: 1.12.0-rc1
expected:

```console
$ docker service update myservers --replicas 3
myservers
$ docker service ls
ID            NAME       REPLICAS  IMAGE  COMMAND
8uorjbjnskem  myservers  3         nginx
```

actual:

```console
$ docker service update myservers --replicas 3
myservers
$ docker service ls
ID            NAME       SCALE  IMAGE  COMMAND
8uorjbjnskem  myservers  3      nginx
```

@dnephin

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #23600

cc @nathanleclaire @icecrime

### CODE REVIEW

**Comment by icecrime** [comment]
Indeed :wink: LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by stevvooe** [comment]
I will miss the following joke:

```
ID            NAME        SCALE  IMAGE   COMMAND
2zs4helqu64f  helloworld  🍌      alpine  ping docker.com		 
2zs4helqu64f  train       🚋      alpine  ping docker.com
```

**Comment by justincormack** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by diogomonica** [comment]
banana :(

**Pull request merged**
