### PR TITLE
Make debugs logs suck less.

### LINKED ISSUE #10245: Noisy registry debug logs
ping @dmcgowan @jlhawn 

can we do something about this, its not even giving what you would think would be helpful between the first `()`
```
DEBU[0060] () does not match 14.10 (id: 809ed259f8454b9946e5ce642673a6d59e35a734e339bc5691b1de7482edc060), skipping 
DEBU[0060] () does not match 14.10 (id: b4c0cca588ccbee9a52067cf8843c0b56678885888252b8aebc0e2cd46e05128), skipping 
DEBU[0060] (13.10) does not match 14.10 (id: 195eb90b534950d334188c3627f860fbdf898e224d8a0a11ec54ff453175e081), skipping 
DEBU[0060] () does not match 14.10 (id: 45753d623bccb0e1ca71937f14c36542b97106f9fc7e313a4ecfa78ccf77d9d8), skipping 
DEBU[0060] () does not match 14.10 (id: 8f118367086c581e2cc93f7a680ebc1195be66ed311014a044a9908ab9832a35), skipping 
DEBU[0060] () does not match 14.10 (id: 3fce8fa143a0581f97aaee54e0eb2cd03abe909b7f18a843d8a96949cd85b92d), skipping 
DEBU[0060] () does not match 14.10 (id: 6ef6f1a66de1aadc8dea6af7d4d5fbdea74f70126bdcbfe70baa5514ed8fff3d), skipping 
DEBU[0060] () does not match 14.10 (id: 962c031a986e6938fc7aa1e945b0a9f546fe75a0d7691aef1a9ad14cc92cba58), skipping 
DEBU[0060] () does not match 14.10 (id: 3327dfd9dc7da6d912cb53a56b4965a6b6bf4089124b94ac3a5c617fe02fb743), skipping 
DEBU[0060] () does not match 14.10 (id: e465fff03bce5ff2bf82513e5e489adbd3899b9f56bd2c7addd3d3cc3e64f63b), skipping 
DEBU[0060] () does not match 14.10 (id: 397ba487c4d88f1a99abc4f9f842da21dcf881f4920eedaf80eab81338f9f458), skipping 
DEBU[0060] () does not match 14.10 (id: 7ade93564ef7b5b841470159a57c21bf1c6b8d3d2cbb5c2dc9b58bc2733e905b), skipping 
DEBU[0060] () does not match 14.10 (id: 5e47ac691989afcd10285ea4e67b46bc0fdc98d90844e57a6d4221c1e3ab4388), skipping 
DEBU[0060] () does not match 14.10 (id: 7c4b0d0eb4025e1fc984426be88a9e4f70e4eed1aea6a6ae758b7ca4b2b74542), skipping 
DEBU[0060] () does not match 14.10 (id: 0f4aac48388f5d65a725ccf8e7caada42f136026c566528a5ee9b02467dac90a), skipping 
DEBU[0060] () does not match 14.10 (id: e12c576ad8a10e77c2941b3155636e934a28f886aa252cdafb6e9ddc3d73fffe), skipping 
DEBU[0060] () does not match 14.10 (id: 6b96a63dc77d2d4288a690d731079e60d9db7c35affe585cb7c15da36e2e61a3), skipping 
DEBU[0060] () does not match 14.10 (id: 8cbdf71a8e7fc45394ef8915da4af12a2a7ecb4e7a95f8bfea9a9614fe984235), skipping 
DEBU[0060] () does not match 14.10 (id: f8325a06a5bed2486e87c525a92468b07552688958589e4db30acd8d4641f958), skipping 
DEBU[0060] () does not match 14.10 (id: 84e884bae354df63e904cff7736496fa598f0b6c53d59976acbafae4fe1f7789), skipping 
DEBU[0060] () does not match 14.10 (id: 5bc37dc2dfba434d7551fa17ee9d3ebba6adab648cebc2f962e612855c4c580c), skipping 
DEBU[0060] () does not match 14.10 (id: 102eb2a101b86d72b71930b6603371949b77bfdecf38b77ea69bdfe6308bf24c), skipping 
DEBU[0060] () does not match 14.10 (id: 9f045ea36057dc4a5be9922631c70702c4aafca77c5b5d19bf517506a9551292), skipping 
DEBU[0060] () does not match 14.10 (id: ae7818fad1bcf8d46dc974dbe2c65f0bf67ec52f09b10bb48f6
```

### PR DESCRIPTION
**Pull request by jessfraz**
closes #10245
ping @crosbymichael

### CODE REVIEW

**Comment by jfrazelle** [comment]
there are also a line in [archive/archive.go](https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L104) where the byte gets put in the logs like:
`"[tar autodetect] n: [31 139 8 0 0 9 110 136 0 255]` <--- idk who this is helping
but I know that is @unclejack's territory so I didn't touch it :)

**Comment by jfrazelle** [comment]
@dmcgowan @jlhawn how do you guys feel about is not logging this json string

**Comment by vieux** [comment]
`"[tar autodetect] n: [31 139 8 0 0 9 110 136 0 255]` is definitely not helping me.

LGTM

**Comment by jfrazelle** [comment]
@vieux I figured you could read bytes :smile:

**Comment by crosbymichael** [comment]
LGTM

**Comment by unclejack** [comment]
@jfrazelle @vieux Thanks, I'll take care of that now.

**Pull request merged**
