### PR TITLE
Zsh completion for 'docker network inspect' multiple networks

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #17218, #17023

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Awesome! LGTM

/cc @vincentbernat

**Comment by vincentbernat** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐭

**Comment by vdemeester** [comment]
/ping @tiborvass for cherry-picking in rc3 :wink:

**Pull request merged**
