### PR TITLE
update Blkio Tests name

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by MHBauer** [comment]
Maybe this test could use a small comment. Which part is _invalid_ here? The device? The weight? Something else? It is not immediately clear to me. Might be good to update it while we're editing it.

**Comment by Mashimiao** [comment]
I think /dev/sdX is clearly a invalid device name.

**Comment by vdemeester** [comment]
@Mashimiao @MHBauer it's a follow-up from #18716 right ?

LGTM :wink:

**Comment by runcom** [comment]
I think @MHBauer is right, and wouldn't hurt to have an assert fail even when the *weight* is invalid (in the same test should be ok)

**Comment by thaJeztah** [comment]
Alright, so it looks like I'm not the only person being confused if the "device" or the "rate"
being invalid is tested (https://github.com/docker/docker/pull/18716#issuecomment-165190475).

@Mashimiao can you add a comment what is being tested? (also in the tests modified in https://github.com/docker/docker/pull/18716)
to prevent future confusion

**Comment by tophj-ibm** [comment]
@MHBauer @runcom actually the weight is also invalid in this test (should be 10-1000)

**Comment by runcom** [comment]
current test shouldn't be updated cause `5` is an invalid value and test is called `InvalidWeightDevice` so it's testing an invalid weight (as I see it)

So, why are we changing `sda` to `sdX` here? `sda` could be a valid device so here we're interested in an invalid weight, which `5` is.

I don't understand the PR now, test is clearly green on master

**Comment by Mashimiao** [comment]
@runcom, @thaJeztah, @MHBauer and @tophj-ibm  At first, I really wanted to test invalid weight for blkioweightdevice. But according to #18716, I find /dev/sda is not always a right path for test in different test environment. So I decide to change case names, after that I think we will clearly know what we are testing.

**Comment by tophj-ibm** [comment]
I think this is a lot clearer. LGTM (for what it's worth)

We should also (not necessarily in this PR) add a test for an invalid weight for blkio weight-device, because it's a slightly different case than invalid blkio weight.

**Comment by Mashimiao** [comment]
@tophj-ibm   yes, we should. I used to try, but it seems we can't find out and promise a device is valid in all of test environment.

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
