### PR TITLE
fix proc regex

### PR DESCRIPTION
**Pull request by jessfraz**
ping @cboltz, added integration-test as well, thanks!

### CODE REVIEW

**Comment by jfrazelle** [comment]
the tesst passes with and without the change... so looking into it more

**Comment by jfrazelle** [comment]
ping @ewindisch I don't know if this is a rule we actually want... because changing it actually broke my container as `can't SetGroups`... I should be able to modify my own process

**Comment by jfrazelle** [comment]
I think we should remove it

**Comment by ewindisch** [comment]
The updated rule doesn't make sense? It denies writes to /proc/[0-9] but allows writes to /proc/[0-9][0-9]+; I think it should be:

deny @{PROC}/{*,**[^0-9]+,sys/kernel/shm*} wkx,

This should deny writes to all files in proc *except* sys/kernel/shm* and /proc/[0-9]+?

**Comment by jfrazelle** [comment]
Ya but I think I should be able to modify my own process no, I mean after doing this I already broke a container

**Comment by jfrazelle** [comment]
ok ok ok ok it would be really hard to have a regex to just allow uid_map, gid_map and setgroups so im conceeding...

**Comment by ewindisch** [comment]
To clarify, the shm* files should also be writable (sys/kernel/shm*)

**Comment by jfrazelle** [comment]
ah updated missed that comment

**Comment by ewindisch** [comment]
The current rule would deny everything in proc. It seems from @cboltz's comments that the {**^} syntax is documented but might not work... if that's true, I'm hard-pressed to identify a way to write this rule in a way that actually works. The problem is that if {**^} doesn't work then there is no easy way to write a negated clause without doing per-character tests as such:

Perhaps something like:
deny ${PROC}/* wkx, # deny /proc/*
deny ${PROC}/[^0-9]*/{*,*/*},  # deny the files /proc/*/* and /proc/*/*/* except /proc/$pid/*
deny ${PROC}/[^s][^y][^s]*/[^k][^e][^r][^n][^e][^l]*/[^s][^h][^m]** wkx,  # deny the files /proc/*/*/** except sys/kernel/shm

Horribly confusing. It's worth checking to see if {**^} works, as it's far more simple.

**Comment by cboltz** [comment]
See issue #17783 for a set of working regexes. Some Aspirin might be needed ;-)

**Comment by jfrazelle** [comment]
thanks so much for your help

**Comment by jfrazelle** [comment]
ok i have updated

**Comment by cboltz** [comment]
Nitpicking - the two added tests come with a wrong command in the error message ;-)

**Comment by calavera** [comment]
yeah, the error messages should be consistent with the tests. Otherwise, they're very misleading :)

**Comment by jfrazelle** [comment]
whoops sorry my bad

**Comment by jfrazelle** [comment]
ok so I am thinking in a different PR because before code freeze I don't want to totally refactor this, I am going to open integration tests for all the rules in the default profile AND remove the `file` rule and add different file riles as @cboltz suggested, just FYI, this is coming, brace yourselves :)

**Comment by thaJeztah** [comment]
ping @ewindisch @calavera does this LGTY now?

**Comment by calavera** [comment]
LGTM

**Comment by ewindisch** [comment]
LGTM? There is a special place in hell for regular expressions.

**Comment by jfrazelle** [comment]
:see_no_evil:

**Comment by cboltz** [comment]
@ewindisch: you have been warned, see my first comment in this pull request (also, a backup on the relevant part is on twitter ;-)

**Comment by thaJeztah** [comment]
Regexes are always fun :)

**Pull request merged**
