### PR TITLE
Ensured -t flag was passed to mini script execution of the Hello World d...

### PR DESCRIPTION
**Pull request by lhazlewood**
...aemon

The tutorial assumes detaching after attaching is possible, such that you can run `sudo docker ps` and see that the container is still running.  

Prior to this edit, the tutorial instructed the reader to press Control-C to detach.  As of Docker 0.6.5, this actually terminates the container.  Running `sudo docker ps` next in the tutorial showed nothing and was confusing - it 'broke' the remainder of the tutorial.

Adding `-t` to `docker run`, the reader can exit via ctl-c and the remainder of the tutorial is possible.

### CODE REVIEW

**Comment by urbandroid** [comment]
This should be default behaviour

**Comment by thaJeztah** [comment]
@urbandroid please don't comment on pull requests that were closed 4 years ago, if you want to open a feature request; open an issue for it, but don't revive a 4 years old pull request. If you want to customize the key-combination for detaching, you can now do so in the CLI configuration file

**Comment by urbandroid** [comment]
@thaJeztah "but don't revive a 4 years old pull request" why is there any law against this? you guys love to repeat yourselves ? What is wrong with old? Calm the f down I just googled after weird unexpected behaviour appeared on my cli this thread was on top and i write a comment that is all. if you really like multi copies of same issue create on your spare time.

**Comment by vdemeester** [comment]
@urbandroid please watch you language a bit. Commenting on closed pull-request is usually not the way forward, as most of people won't read closed pull-request and even if they do, it's a pull request that's against some piece of code that probably doesn't exists anymore. Pull-requests are not issues, they are a way to propose code change and discuss about these code changes. You could definitely open an issue, but it would just duplicate https://github.com/docker/docker/issues/2855. On the `default`, it really is just a matter of "point of view". Some people would argue the current behavior is a sane default, some wont — that's why it's configurable, to let user set their own default.

> I'm locking this issue; the default key-combination is not going to change, and you can now set your own default using a configuration file #15666. I understand that for some people ^C is the preferred combination and they are now able to do so.

**Pull request closed without merging**
