### PR TITLE
change hard code: add some overlay2 constant to replace the hard code.

### PR DESCRIPTION
**Pull request by imxyb**
Signed-off-by: Xiao YongBiao <xyb4638@gmail.com>

**- What I did**
I added some few constants for overlay2 and change the hard code。
**- How I did it**
Define constants in the overlay.go file.
**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! Code changes look good to me, but could you use your real name in the DCO sign-off (instead of your GitHub handle)?; https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work


```
Signed-off-by: imxyb <xyb4638@gmail.com>
```

**Comment by imxyb** [comment]
> Thanks! Code changes look good to me, but could you use your real name in the DCO sign-off (instead of your GitHub handle)?; https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
> 
> ```
> Signed-off-by: imxyb <xyb4638@gmail.com>
> ```

Done.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

ping @kolyshkin ptal

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
