### PR TITLE
Move OomKillDisable to resource

### PR DESCRIPTION
**Pull request by hqhq**
1. It's a cgroup api, fit the general defination that we take
   cgroup options as kind of resource options.
2. It's common usage and very helpful as explained here:
   https://github.com/docker/docker/pull/18270#issuecomment-160561316
3. It's already in `Resource` struct in
   daemon/execdriver/driver_unix.go

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by hqhq** [comment]
ping @runcom @tiborvass as you already involved in this discussion in #18270 :wink:

**Comment by jfrazelle** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by thaJeztah** [comment]
Is this an API change?

**Comment by hqhq** [comment]
@thaJeztah Not really, `Resources` is embedded, users can still use
```
HostConfig: {
    OomKillDisable: false
}
```

So no API change.

**Comment by thaJeztah** [comment]
@hqhq ah, thanks. Wasn't sure, so thought it'd better check :smile:

**Pull request merged**
