### PR TITLE
Fix timeout issue of `TestCreateWithDuplicateNetworkNames`

### PR DESCRIPTION
**Pull request by arm64b**
The `TestCreateWithDuplicateNetworkNames` case can't finished in
the default 10s on ARM platforms, so we need to adjust the timeout
value to avoid broke our local CI pipeline with below failure message:

> --- FAIL: TestCreateWithDuplicateNetworkNames (21.61s)
> 	daemon.go:283: [d34836e14f32a] waiting for daemon to start
>	daemon.go:315: [d34836e14f32a] daemon started
>	create_test.go:119: timeout hit after 10s: waiting for tasks to enter run state
>	daemon.go:273: [d34836e14f32a] exiting daemon

Signed-off-by: Dennis Chen <dennis.chen@arm.com>

**- What I did**
Fix the timeout issue for `TestCreateWithDuplicateNetworkNames`
**- How I did it**
Adjust the timeout value on arm{32,64} architecture
**- How to verify it**
`make integration`
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by arm64b** [comment]
@vdemeester , @dnephin , I am wondering if we have a default timeout value setup in one place, thus we can adjust that value on arm platform, thus we don't need to make such changes case by case. Timeout doesn't mean the function being tested is broken, it only indicates that the functionality doesn't complete in the time range specified, so this can't be regarded as a real issue.

**Review by vdemeester — COMMENTED** [review]
SGTM

**Comment by dnephin** [comment]
I agree we should setup some defaults for `pollSettings`. Somewhere under `integration/internal`. maybe in the `swarm` package ?

We should name them based on the type or resource we're waiting on, so something like this:

```go
func servicePoll(config *poll.Settings) {
...
}

func networkPoll(config *poll.Settings) {
...
}
```

That way we have defaults, but we don't have to use the same value for every type of resource (some may be slower than others).

**Comment by kolyshkin** [comment]
> 20:31:21 --- FAIL: TestServiceWithPredefinedNetwork (31.81s)
this failure on powerpc is the subject of https://github.com/moby/moby/issues/36547

**Comment by arm64b** [comment]
@dnephin I noticed that the error message shows that the timeout after `10s`, so I am wondering if that value is in-tree of Moby code or from the imported testing pkgs outside, I can keep use current solution if we haven't a easier way available now to adjust the timeout value on ARM. I think `30s` is enough as an indicator if something wrong will happen on ARM platforms, that doesn't mean ARM arch is born for poor performance, but somehow heads up if some kinds of optimization we can do to mitigate that...

@kolyshkin  Right, will ping you guys after those flaky tests fixed 🐅

**Comment by dnephin** [comment]
My understanding was that you were going to create a PollOp function and re-use it where it's needed. Are you not planning on making that change?

**Comment by arm64b** [comment]
> My understanding was that you were going to create a PollOp function and re-use it where it's needed. Are you not planning on making that change?

Hello @dnephin , thanks for the remind 👍! Yes, you understanding is correct, I must confess that I have a little bit misunderstanding for your previous comment, now it should be clear: we will create a PollOp function and re-use it where it's needed. The change is on going, will submit a new PR to embrace this one(also plus some clear-up for earlier timeout adjustment on arm) after I have some testings locally 🥇

**Comment by arm64b** [comment]
Close this PR since it has already evolved to PR #36706 🐯

**Pull request closed without merging**
