### PR TITLE
Add option --manager for docker swarm join command

### PR DESCRIPTION
**Pull request by lixiaobing1**
Two locations:
first, add "worker" to node.
second, add option --manager for docker swarm join command because there is --manager description at the following:

```
### `--manager`

Joins the node as a manager

### `--token string`

Secret value required for nodes to join the swarm
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
This option is no longer present in 1.12.0, it was removed in https://github.com/docker/docker/pull/24823, where the join process changed to use a join-token instead of a secret. The type of join-token determines if a node joins as manager or as worker, and is a more secure approach than reusing the same secret (both for managers and workers).

I'll close this PR because it's not correct, but thanks again for contributing!

**Comment by lixiaobing10051267** [comment]
so can "--manager" description be removed?

### `--manager`

Joins the node as a manager

### `--token string`

Secret value required for nodes to join the swarm

**Comment by thaJeztah** [comment]
@lixiaobing10051267 where are you seeing that description? Are you perhaps running an older release candidate of docker?

**Comment by lixiaobing10051267** [comment]
@thaJeztah line 88 of docs/reference/commandline/swarm_join.md

**Pull request closed without merging**
