### PR TITLE
Moving experimental

### PR DESCRIPTION
**Pull request by moxiegirl**
This is the much talked about docs.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
So I understand correctly; the experimental documentation won't be published on the docs-site(s), only available through GitHub?

**Comment by moxiegirl** [comment]
@thaJeztah That is correct. The team plans on updating the experimental features quite frequently; there is overhead in publishing to the docs.docker.com site.  Also, these are _experimental_ features --- we will keep a mention in the release notes of the program but no reason to confuse readers.

**Comment by SvenDowideit** [comment]
LGTM

**Comment by thaJeztah** [comment]
@moxiegirl Thanks for explaining, I expected that was the reason.

We need to pay attention that the meta-data is added back-in if experimental features are no longer "experimental" and these documents are added to the docs.

Perhaps we need a check on Janky to check if documents in the docs contains meta-headers.

LGTM ("experimental" build is still being scheduled)

**Comment by moxiegirl** [comment]
@thaJeztah Adding the material into the official documentation will necessitate a new PR and a documentation build.  Hugo actually uses the META data unlike Mkdocs. Also, not all of the material goes into new documents but merged into existing. IOW, the risk that the Meta data is not included on re-entry is very low.

**Comment by thaJeztah** [comment]
@moxiegirl true, just a friendly reminder :)

I don't know what's up with the experimental builds. I checked this morning and all build servers were "idle", but no experimental builds were being run :(

triggering a rebuild didn't help also

@jfrazelle should we just merge, or are you working on this?

**Comment by jfrazelle** [comment]
Merge it

**Comment by thaJeztah** [comment]
Oh LOL:

> Pull requests that have a failing status can't be merged from a phone.

@moxiegirl feel free to push the button as I'm not allowed to :smile:

**Pull request merged**
