### PR TITLE
fix lxc

### LINKED ISSUE #14475: skip DockerSuite.TestRunCapAddCHOWN on lxc
create a patch to skip that test on lxc

### PR DESCRIPTION
**Pull request by jessfraz**
close #14860
close #14475
fix lxc on master by fixing memory swappiness

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @calavera @icecrime

**Comment by icecrime** [comment]
LGTM :+1:

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
it passed! merging!

**Pull request merged**
