### PR TITLE
daemon: inspect: empty out StartedAt/FinishedAt if they are zero

### PR DESCRIPTION
**Pull request by runcom**
Before:

```
$ docker create busybox
2196a3e4d474c332b055a30de7e17637baf8b05937f6e7091eca9daa204e9110
$ docker inspect 219
[{
    [...]
    "State": {
        "Status": "created",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "0001-01-01T00:00:00Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },

$ docker run -d busybox top
0106b881e7df107bcbbc929f9d782372773b54bafe37fe2f44e1324df8ecde2f
$ docker inspect 010
[{
    [...]
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 30197,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-11-02T12:27:14.887421621Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },

```

Notice `0001-01-01T00:00:00Z` which means time is formatted but it was zero
After this patch `StartedAt` and `FinishedAt` will be an empty string if the time is zero
Can make sense to version this change as it may be seen as a breaking change, let me know what do you think. I don't know how people feel about this patch, to me it makes sense not to show anything if the value actually doesn't make sense (even if it's zero, it shouldn't be populated at all, I think `null` can be even better)

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by estesp** [comment]
`ExecInspect` in the remote API docs (http://docs.docker.com/reference/api/docker_remote_api_v1.20/) shows an example with the zero-formatted time string.  The `inspect` example shows valid times for start/finish.

I assume at least the `ExecInspect` should be changed to empty string, and not sure if there needs to be any docs about the fact it may be empty (currently there are no docs at all about these fields, so maybe not?)

**Comment by runcom** [comment]
@estesp true, that should be changed as well, I just want to see if everyone agree with this, I personally don't like the zero time there

**Comment by thaJeztah** [comment]
I think it'd make sense to version, because it's a change in API behavior. I'm +1 for this (nightmares of MySQL doing similar `0000-00-00` dates, yuk!)

**Comment by runcom** [comment]
I've rebased this (even if it's in design-review :P)

**Comment by LK4D4** [comment]
@runcom I wonder how deserialization stuff will work with this, like will `json.Unmarshal` still able to get `time.Time` field from there? If not, then we probably need versioning :/

**Comment by runcom** [comment]
@LK4D4 those fields are `string` in `types.ContainerState` so they will eventually be unmarshaled in strings. However there's no code unmarshaling `ContainerState`. Just in case, however again, `time.Parse(time.RFC3339Nano, "")` will return the zero time.
But I still think this needs versioning cause we won't return zero time anymore, I'll update this

**Comment by crosbymichael** [comment]
@runcom is this good to go?

**Comment by runcom** [comment]
@crosbymichael not yet, finding 10 minutes to adapt it to be versioned :/ I'll update it asap!

**Comment by thaJeztah** [comment]
@runcom looks like you did a whoopsie with a rebase

**Comment by runcom** [comment]
@thaJeztah yeah I did, fixing

**Comment by thaJeztah** [comment]
ping @runcom looks like you forgot to fix the rebase :smile:

**Comment by thaJeztah** [comment]
@runcom I'll close this for now, because we cannot merge this in this state, but please reopen after rebasing :innocent:

**Pull request closed without merging**
