### PR TITLE
Hugo final 1.7 Documentation PR -- please read carefully

### PR DESCRIPTION
**Pull request by moxiegirl**
This PR fixes problems found in review today/yesterday.  Review so you understand, then, do the following:
1. Merge into `master` branch.
2. Cherry-pick merge commit into the branch where you want me to release docs from.
3.  Send me an email with titled _Release docker/docker Docs from BRANCHNAME_

Unfortunately, while I fixed the majority of problems with your content there
are a few remaining ones that  we **must address after the release** these are:

  -most  # links are not working; confirmed sed scripts not the problem
- some broken links found to external locations

To see for yourself, `make docs` in `docs` directory then manually check or
using a Chrome extension like Check My LInks.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @jfrazelle for the merge/cherry pick .  Jess, you might want to just do both.  The output is what is...any problems anyone notices will need to be filed as issues and then fixed later.

**Comment by jfrazelle** [comment]
well shit then i need to rebuild the rpms because the sha will change is this the last one?

**Comment by moxiegirl** [comment]
Yes. Damn, very sorry, I was hoping to get this out before you built.

**Comment by jfrazelle** [comment]
no worries lets merge it tho ;) LGTM

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
