### PR TITLE
Bump Microsoft/opengcs to v0.3.9

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Moves to latest opengcs

### CODE REVIEW

**Review by yongtang — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
For future reference; full diff: https://github.com/Microsoft/opengcs/compare/v0.3.8...v0.3.9

Relevant changes;

- https://github.com/Microsoft/opengcs/pull/251 Fixing time.Duration casts
- https://github.com/Microsoft/opengcs/pull/209 vsockexec: Tool for execing with vsock handles
- https://github.com/Microsoft/opengcs/pull/213 vsockexec: Don't reorder getopt args

**Pull request merged**
