### PR TITLE
Rename DCO check param in Jenkinsfile

### PR DESCRIPTION
**Pull request by SamWhited**
Previously it was a negative parameter for skiping the DCO check, but
this is different from other checks. It was requested that I change this
in #40023 by @thaJeztah but I'm factoring it out into a new PR to reduce the diff size since this is an unrelated change.

**EDIT:** left off the DCO to check that this works (and it does). Definitely not just because I forgot it as usual.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

but I think Jenkins won't test/pick-up the change because the PR was opened by someone who isn't whitelisted 😂 😞 🤷‍♂

**Comment by SamWhited** [comment]
> but I think Jenkins won't test/pick-up the change because the PR was opened by someone who isn't whitelisted

ah, right. It worked in #40023 anyways :)

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by SamWhited** [comment]
CI failures appear to be unrelated.

**Pull request merged**
