### PR TITLE
Add Bjorn Neergaard to maintainers

### PR DESCRIPTION
**Pull request by thaJeztah**
I nominated Bjorn as maintainer, and votes passed; welcome Bjorn!

**- A picture of a cute animal (not mandatory but encouraged)**

mouse

[image source:](https://www.facebook.com/512564359080342/photos/a.512564932413618/512564935746951/?type=3)

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by yongtang — APPROVED** [review]
LGTM ❤️

**Review by corhere — APPROVED** [review]

**Review by samuelkarp — COMMENTED** [review]
I missed this PR, but LGTM! Welcome!

**Pull request merged**
