### PR TITLE
Rearrange layerstore locking

### PR DESCRIPTION
**Pull request by aidanhs**
Continuation of https://github.com/aaronlehmann/docker/pull/2

Ping @aaronlehmann @dmcgowan

### CODE REVIEW

**Comment by dmcgowan** [comment]
LGTM

Not a fan of the name `getNoSync`,would prefer either have `get` be `getWithLock` or `getNoSync` be `getWithoutLock`. Not sure we have a convention for these names.

**Comment by aidanhs** [comment]
I don't have preference for the names, I just want to make sure people reach for something that sorts locking out for them by default, i.e. make sure `get` locks.

I've changed it to `getWithoutLock`.

**Comment by dmcgowan** [comment]
thanks, update LGTM

**Comment by calavera** [comment]
there is a compilation error on windows. There is still a reference to `getAndRetainLayer`.

**Comment by aidanhs** [comment]
Ah thanks, fixed.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
