### PR TITLE
Adds a unit test for plugin request timeout

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
relates to https://github.com/moby/moby/pull/35441

**Review by boaz0 — APPROVED** [review]
LGTM :1st_place_medal:

**Comment by ripcurld** [comment]
CI failed in `powerpc`: DockerSuite.TestLogsContainerBiggerThanPage
```
01:47:37 docker_cli_logs_test.go:25:
01:47:37     testLogsContainerPagination(c, 32768)
01:47:37 docker_cli_logs_test.go:38:
01:47:37     c.Assert(out, checker.HasLen, testLen+1)
01:47:37 ... obtained string = ""
01:47:37 ... n int = 32769
```

Is it a flaky test?

**Comment by thaJeztah** [comment]
`TestLogsContainerBiggerThanPage`, hm, not sure I've seen that one before, but it cannot really be related to this PR; let me restart (perhaps we need a tracking issue for that test)

**Review by vdemeester — APPROVED** [review]
LGTM :heart_eyes_cat:

**Comment by ddebroy** [comment]
@cpuguy83 Looks like this test failed. Did the plugin not initialize correctly?
https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS5-Process/2930/console
```
15:22:45 2019/07/11 22:22:11 http: panic serving 127.0.0.1:49224: Plugin not ready
15:22:45 goroutine 23 [running]:
15:22:45 net/http.(*conn).serve.func1(0xc000052a00)
15:22:45 	c:/go/src/net/http/server.go:1769 +0x140
15:22:45 panic(0x831fc0, 0x95da50)
15:22:45 	c:/go/src/runtime/panic.go:522 +0x1c3
15:22:45 github.com/docker/docker/pkg/plugins.TestFailOnce.func1(0x9714a0, 0xc00013e000, 0xc0000f8300)
15:22:45 	c:/go/src/github.com/docker/docker/pkg/plugins/client_test.go:55 +0x56
15:22:45 net/http.HandlerFunc.ServeHTTP(0xc00003e030, 0x9714a0, 0xc00013e000, 0xc0000f8300)
15:22:45 	c:/go/src/net/http/server.go:1995 +0x4b
15:22:45 net/http.(*ServeMux).ServeHTTP(0xc000040040, 0x9714a0, 0xc00013e000, 0xc0000f8300)
15:22:45 	c:/go/src/net/http/server.go:2375 +0x1dd
15:22:45 net/http.serverHandler.ServeHTTP(0xc000110000, 0x9714a0, 0xc00013e000, 0xc0000f8300)
15:22:45 	c:/go/src/net/http/server.go:2774 +0xaf
15:22:45 net/http.(*conn).serve(0xc000052a00, 0x972060, 0xc000056b00)
15:22:45 	c:/go/src/net/http/server.go:1878 +0x858
15:22:45 created by net/http.(*Server).Serve
15:22:45 	c:/go/src/net/http/server.go:2884 +0x2fb
15:22:45 time="2019-07-11T22:22:11Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49223/Test.FailOnce: Post http://127.0.0.1:49223/Test.FailOnce: EOF, retrying in 1s"
15:22:45 time="2019-07-11T22:22:12Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49228/Test.Echo: Post http://127.0.0.1:49228/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 1s"
15:22:45 time="2019-07-11T22:22:14Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49228/Test.Echo: Post http://127.0.0.1:49228/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 2s"
15:22:45 time="2019-07-11T22:22:16Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49228/Test.Echo: Post http://127.0.0.1:49228/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 4s"
15:22:45 time="2019-07-11T22:22:21Z" level=warning msg="Unable to connect to plugin: 127.0.0.1:49228/Test.Echo: Post http://127.0.0.1:49228/Test.Echo: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying in 8s"
15:22:45 --- FAIL: TestClientWithRequestTimeout (0.00s)
15:22:45     client_test.go:259: assertion failed: 
15:22:45         --- context.DeadlineExceeded
15:22:45         +++ err
15:22:45         :
15:22:45         	-: context.deadlineExceededError{}
15:22:45         	+: &net.OpError{Op: "dial", Net: "tcp", Addr: s"127.0.0.1:49298", Err: &poll.TimeoutError{}}
15:22:45  
```

**Comment by cpuguy83** [comment]
Saw it fail in a different way on another run. Haven't seen it fail before today.

**Comment by thaJeztah** [comment]
@ddebroy I was working on a fix for that in https://github.com/moby/moby/pull/39168 (but didn't come round to address the review comments yet)

**Pull request merged**
