### PR TITLE
vendor: github.com/moby/swarmkit/v2 v2.0.0-20230302163403-80a528a86877

### LINKED ISSUE #44312: `docker service rm` for `replicated-job` service leaves orphaned task
### Description

When removing a `replicated-job` service inside a stack with `docker service rm`, service is removed but the task is still listed with `docker stack ps`.

### Reproduce

Put Docker in Swarm mode:
```
docker swarm init
```

Create a `replicated-job` service inside a new `test_stack`:
```
docker service create -l com.docker.stack.namespace=test_stack --name test_service --mode replicated-job php:8.1-fpm-alpine date
```

Verify that service is completed along its task:
```
➜ docker service ls
ID             NAME           MODE             REPLICAS              IMAGE                PORTS
7oznyuuqunrq   test_service   replicated job   0/1 (1/1 completed)   php:8.1-fpm-alpine

➜ docker stack ps test_stack
ID             NAME                                     IMAGE                NODE             DESIRED STATE   CURRENT STATE             ERROR     PORTS
3spgqd4kufbx   test_service.vt5bh0py0bucsq1mdafzg22hd   php:8.1-fpm-alpine   docker-desktop   Complete        Complete 54 seconds ago
```

Remove the `test_service` service:
```
docker service rm test_service
```

Verify that the service has been removed:
```
➜ docker service ls
ID        NAME      MODE      REPLICAS   IMAGE     PORTS
```

But the task is still listed and the only way to remove it is to leave the swarm:
```
➜ docker stack ps test_stack
ID             NAME                                                  IMAGE                NODE             DESIRED STATE   CURRENT STATE            ERROR     PORTS
3spgqd4kufbx   7oznyuuqunrqieagtuyzej151.vt5bh0py0bucsq1mdafzg22hd   php:8.1-fpm-alpine   docker-desktop   Complete        Complete 4 minutes ago
```

### Expected behavior

`docker stack ps test_stack` should not list any task for the removed service or at least there should be a way to remove those "orphaned" tasks.

### docker version

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 26
  Running: 0
  Paused: 0
  Stopped: 26
 Images: 115
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: vt5bh0py0bucsq1mdafzg22hd
  Is Manager: true
  ClusterID: a2xuru36gnlnayko2v8mqvxd3
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.124-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.75GiB
 Name: docker-desktop
 ID: NB7Q:BIXT:7RC4:UYMH:5GFF:DPKN:RSTV:GGRF:MSTE:DXG4:J27U:CHBR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### LINKED ISSUE #44378: docker service create doesn't work when network and generic-resource are both attached
## Issue
In docker swarm, `--generic-resource` does not work when it is used alongside `--network`. This is due to an incorrect condition, `if genericresource.HasResource(ta, available.Generic)`, in the `constraint_enforcer.go` code when the service is brought up.

```lang=go
for _, ta := range t.AssignedGenericResources {
	// Type change or no longer available
	if genericresource.HasResource(ta, available.Generic) {
		removeTasks[t.ID] = t
		break loop
	}
}
```
The code should read `if !genericresource.HasResource(ta, available.Generic) {` so that the task which has an assigned and available GenericResource is not removed.

This is bug is important as it prevents the usage of generic resources in Docker Swarm; this is particularly relevant for assigning services to nodes based on GPU availability.

The generic-resources feature used to work properly in swarm in version `18.06.1`.

## Bug Investigation + Reproduction steps
This functionality was working in version `18.06.1` but not in any version afterwards.

Each release was tested through these steps. An additional condition that is required for the bug to occur is that the service must be being brought up on a non-manager swarm node:

1. Initialize the swarm
```
docker swarm init --advertise-addr <host_ip>
```

2. Create an overlay network.
```
docker network create -d overlay --scope swarm test-network
```

3. Modify `/etc/docker/daemon.json` on the worker to add an item to `node-generic-resources`. Restart the docker service

```
{
  ...
  "node-generic-resources": [
      "gpu_<type>=GPU-sample-id",
  ]
}
```

4. Add a worker node to the swarm.

5. Create a service that with the network attached as well as a generic-resource. This step will fail and the service will never get to the running state.
```
docker service create --network test-network --generic-resource "gpu_<type>=1" --name test-service quay.io/centos/centos:stream8 bash -c "env && sleep infinity"
```

6. Observe the error by running `docker service ps`. These errors continue in a loop where a new task is created and subsequently rejected. This error does not resolve by itself and the service never reaches the `Running` state.
```
docker service ps --no-trunc test-service

# Example output

ID                          NAME                 IMAGE                                  NODE                     DESIRED STATE   CURRENT STATE             ERROR                                              PORTS
4tqh3odt54qhp3mzumwjt3mpj   test-service.1       quay.io/centos/centos:stream8@<hash>   <worker_node_hostname>   Ready           Rejected 4 seconds ago    "assigned node no longer meets constraints"
j6d0qwxv2kglyzugpgd98qx1f    \_ test-service.1   quay.io/centos/centos:stream8@<hash>   <worker_node_hostname>   Shutdown        Rejected 9 seconds ago    "assigned node no longer meets constraints"
etrnb3per1lgej9wgp9az2u4d    \_ test-service.1   quay.io/centos/centos:stream8@<hash>   <worker_node_hostname>   Shutdown        Rejected 9 seconds ago    "assigned node no longer meets constraints"
inyz4ez2i95rd5vyxggo0mgbk    \_ test-service.1   quay.io/centos/centos:stream8@<hash>   <worker_node_hostname>   Shutdown        Rejected 14 seconds ago   "assigned node no longer meets constraints"
ymy14a55fbv6cgdaxl4nzy06h    \_ test-service.1   quay.io/centos/centos:stream8@<hash>   <worker_node_hostname>   Shutdown        Rejected 19 seconds ago   "assigned node no longer meets constraints"
```

7. Remove the worker node from the swarm and repeat steps 4-6 for different versions of docker-ce

### Expected behavior

`docker service create` should create a service with a `network` and `generic-resource` attached.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:11 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:29 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 28
  Running: 6
  Paused: 0
  Stopped: 22
 Images: 91
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: <node_id>
  Is Manager: false
  Node Address: <node_address>
  Manager Addresses:
   <manager_1_address>
   <manager_2_address>
   <manager_3_address>
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: de40ad0
 Kernel Version: <redacted>
 Operating System: <redacted>
 OSType: linux
 Architecture: x86_64
 CPUs: <redacted>
 Total Memory: <redacted>
 Name: <node_name>
 ID: <redacted>
 Debug Mode: false
 Experimental: false
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by thaJeztah**
- fix docker service create doesn't work when network and generic-resource are both attached
- Fix removing tasks when a jobs service is removed
- CSI: Allow NodePublishVolume even when plugin does not support staging
- fixes https://github.com/moby/moby/issues/44378
- fixes https://github.com/moby/moby/issues/44312

full diff: https://github.com/moby/swarmkit/compare/904c221ac281...80a528a86877fa46da4b9e96a059bf8646ecdb21

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
rebased to address minor conflict (`vendor.sum`)

**Comment by thaJeztah** [comment]
@vvoland @rumpl ptal

**Comment by thaJeztah** [comment]
Flaky test (on Windows); https://github.com/moby/moby/issues/38587

```
=== FAIL: github.com/docker/docker/pkg/plugins TestClientWithRequestTimeout (0.01s)
    client_test.go:254: assertion failed: expected an error, got nil: expected error
```

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
Let me bring this one in, and move https://github.com/moby/moby/pull/45107 out of draft

**Pull request merged**
