### PR TITLE
Upgrade logrus to v0.7.2

### LINKED ISSUE #11563: docker daemon log - timestamp missing milli/nano seconds
The docker daemon (default /var/log/docker) is missing the trailing milli/nano seconds that exist in the "docker logs" command.

daemon:
time="2015-03-22T09:03:20Z" level="info" msg="-job container_inspect(c838886a2e3d) = OK (0)"

docker logs:
2015-03-18T15:47:55.649048237Z Wed, 18 Mar 2015 15:47:55 GMT

### PR DESCRIPTION
**Pull request by scarletmeow**
- Daemon logs now report to millisecond resolution

Signed-off-by: Tiffany Low the.second.angel@gmail.com

Fixes #11563

### CODE REVIEW

**Comment by scarletmeow** [comment]
Fixes https://github.com/docker/docker/issues/11563

New log format example:
```
root@5d37744f91a7:/go/src/github.com/docker/docker# ./bundles/1.5.0-dev/binary/docker -d -D -H unix:// -H tcp://0.0.0.0:2375 >> "docker.log" 2>&1 &
[1] 31809
root@5d37744f91a7:/go/src/github.com/docker/docker# tail -f docker.log
time="2015-03-30T19:24:16.908003775Z" level=info msg="docker daemon: 1.5.0-dev cdcfcbd; execdriver: native-0.2; graphdriver: aufs"
time="2015-03-30T19:24:16.908063995Z" level=info msg="+job acceptconnections()"
time="2015-03-30T19:24:16.908085203Z" level=info msg="-job acceptconnections()%!s(<nil>)"
time="2015-03-30T19:24:16.912444711Z" level=info msg="Daemon has completed initialization"
```

**Comment by Sirupsen** [comment]
LGTM

**Comment by LK4D4** [comment]
@scarletmeow Thanks!

**Comment by tianon** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
thanks!

**Pull request merged**
