### PR TITLE
Add "builder-deb" base images for building ".deb" packages properly

### PR DESCRIPTION
**Pull request by tianon**
Here's how I've been testing this (without DinD):

``` console
$ ./contrib/builder/deb/build.sh
$ AUTO_GOPATH=1 DOCKER_TEST_HOST=unix:///var/run/docker.sock ./hack/make.sh build-deb
```

This can also be tested "properly" with something like:

``` console
$ make shell
# ./hack/make.sh binary build-deb
```

We can also use "frozen images" later to make this build _much_ faster (and work without internet access, assuming an up-to-date `Dockerfile` build, as per our usual flow).

### CODE REVIEW

**Comment by tianon** [comment]
Here's an example of what this produces:
```console
$ find bundles -name '*.deb' | sort
bundles/1.5.0-dev/build-deb/debian-jessie/docker-core_1.5.0~dev~git20150403.013846.0.22cb318-0~jessie_amd64.deb
bundles/1.5.0-dev/build-deb/debian-wheezy/docker-core_1.5.0~dev~git20150403.013846.0.22cb318-0~wheezy_amd64.deb
bundles/1.5.0-dev/build-deb/ubuntu-debootstrap-trusty/docker-core_1.5.0~dev~git20150403.013846.0.22cb318-0~trusty_amd64.deb
bundles/1.5.0-dev/build-deb/ubuntu-debootstrap-utopic/docker-core_1.5.0~dev~git20150403.013846.0.22cb318-0~utopic_amd64.deb
bundles/1.5.0-dev/build-deb/ubuntu-debootstrap-vivid/docker-core_1.5.0~dev~git20150403.013846.0.22cb318-0~vivid_amd64.deb
```

**Comment by tianon** [comment]
I tried to include precise here too (12.04), but it's way too ancient. :cry:

**Comment by tianon** [comment]
The end goal of this change is to deprecate `hack/make/ubuntu` and https://get.docker.com/ubuntu in favor of having a separate repository for each suite we officially target and support, which allows us to have a dynamic binary and allows us to let `debhelper` do the things it's good at, instead of trying to replicate them ourselves (like _properly_ managing service startup).

**Comment by jfrazelle** [comment]
awesome!!!!!

**Comment by jfrazelle** [comment]
me like!!! can we move to code review, ping @crosbymichael

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
yup yup looks like shell to me

LGTM

**Pull request merged**
