### PR TITLE
Make TestServiceCreateCompatiblePlatforms use actual API response

### PR DESCRIPTION
**Pull request by thaJeztah**
The `TestServiceCreateCompatiblePlatforms()` test was confusing, because it did not actually use the mocked API response, but used a local `distributionInspectBody` variable to verify that the `/distribution/` endpoint was called.

This flow was especially confusing, because a comment in the test describes;

    "check if the /distribution endpoint returned correct output"

If (for whatever reason), the endpoint was not called, the test would panic, because the `distributionInspectBody` would not be set.

This patch rewrites the test to use the actual API response that is returned by the mock, and verifies that the information returned by the `/distribution/` endpoint is properly used in the service's definition.

I discovered this situation while working on https://github.com/moby/moby/pull/33571, when I got a panic in the test (https://github.com/moby/moby/pull/33571#issuecomment-307396191). I wrote this patch, but didn't include it in that PR, because it was not strictly needed to make the change that PR was opened for.

ping @vdemeester @nishanttotla PTAL

### CODE REVIEW

**Comment by thaJeztah** [comment]
rebased :)

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by nishanttotla — APPROVED** [review]
LGTM (IANAM)

@thaJeztah good catch, sorry this should have been caught earlier :(

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
