### PR TITLE
Cherry-pick : Add the missing experimental ipvlan network driver

### PR DESCRIPTION
**Pull request by mavenugo**
Cherry-picking #29374 into 1.13.x branch

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @vieux

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
plugins test failure unrelated, will be fixed by https://github.com/docker/docker/pull/29229 LGTM

**Comment by justincormack** [comment]
Tests passed after the other PR was merged.

**Pull request merged**
