### PR TITLE
Revert docker/swarmkit#2804

### LINKED ISSUE #39023: 19.03.0-beta1: docker service scale does not always wait to converge
**Description**

I tested Docker CE 19.03.0-beta1 in swarm mode and `docker service scale` does not always wait until the service has converged. I also tried different version of Docker CLI 18.09.2 and 19.03.0-beta1, but both show the same behaviour.

**Steps to reproduce the issue:**
1. `docker swarm init`
2. `docker service scale --name whoami -p 8080:8080 stefanscherer/whoami`
3. `docker service scale whoami=8`
4. `docker service scale whoami=1`
5. repeat 3 and 4

**Describe the results you received:**

**Describe the results you expected:**

[asciicast](https://asciinema.org/a/NujZowdrbeZ7EV2EeK88UPM7i)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.0-beta1
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        62240a9
 Built:             Thu Apr  4 19:15:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       62240a9
  Built:            Thu Apr  4 19:22:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.0-beta1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ld0yhhwtiw3r4rtk58xctd01w
  Is Manager: true
  ClusterID: ezhecyk9ipzrwfiazcw58kmfb
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.99.100
  Manager Addresses:
   192.168.99.100:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.111-boot2docker
 Operating System: Boot2Docker 19.03.0-beta1 (TCL 8.2.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 989.4MiB
 Name: v19.03.0-beta1
 ID: 8b0c44ac-8def-47d2-a120-5fc4a16beabc
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
docker-machine create -d virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v19.03.0-beta1/boot2docker.iso v19.03.0-beta1
```

### PR DESCRIPTION
**Pull request by dperny**
**- What I did**

Reverts the change to swarmkit that made all updates set UpdateStatus to Completed.

See docker/swarmkit#2861

related: https://github.com/docker/swarmkit/pull/2804, https://github.com/moby/moby/pull/38520

fixes https://github.com/docker/swarmkit/issues/2861
fixes https://github.com/moby/moby/issues/39023

**- How I did it**

Returned the integration test to the way it was before

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM (if green)

**Comment by olljanat** [comment]
Yea we need to do this for get 19.03 working correctly but this will add some flakiness back to moby integration tests which need to be fixed on some other way.

@dperny I also think that we probably should add some integration test case to swarmkit side which prevents same issue coming back on future?

Janky have now failed to #32673 and #38885 
Let see what happens on next run...

**Comment by olljanat** [comment]
Derek add label: rebuild/janky

**Comment by dperny** [comment]
we can try again later, but we have to be careful. in my opinion, what the CLI is doing that's causing this to be a problem is Wrong, but it's far too late to change it.

**Comment by olljanat** [comment]
Yea. Btw. On RS1 build servers looks to have some generic issue so it can be ignored here.

**Comment by thaJeztah** [comment]
@dperny and I were discussing this revert, and (temporarily) reverting this change seemed the best / safest option for now; we can redo the change if we find an approach tp make the cli work with it (in a backward compatible way)

**Comment by dperny** [comment]
everything but the known bad windows test is passing.

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
