### PR TITLE
Use commit-sha instead of tag for containerd

### PR DESCRIPTION
**Pull request by thaJeztah**
The `docker info` command compares the installed version
of containerd using a Git-sha. We currently use a tag for
this, but that tag is not returned by the version-API of
containerd, resulting in the `docker info` output to show:

    containerd version: 89623f28b87a6004d4b785663257362d1658a729 (expected: v1.0.0)

This patch changes the `v1.0.0` tag to the commit that
corresponds with the tag, so that the `docker info` output
does not show the `expected:` string.

This should be considered a temporary workaround; the check
for the exact version of containerd that's installed was needed
when we still used the 0.2.x branch, because it did not have
stable releases yet.

With containerd reaching 1.0, and using SemVer, we can likely
do a comparison for "Major" version, or make this a "packaging"
issue, and remove the check entirely (we can still _print_ the
version that's installed if we think it's usefule).

I can add a test for this

**- How to verify it**

run `docker info` and check that the `expected:` string is not present

**- Description for the changelog**

```Markdown
* Fix `docker info` showing "expected: v1.0.0" for containerd [moby/moby#35770](https://github.com/moby/moby/pull/35770)
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tianon** [comment]
IMO the tag is superior, and this would be a good case for fixing the version comparison code, but I could be convinced. :innocent:

**Comment by thaJeztah** [comment]
Yes the tag is certainly more readable (although _mutable_). The reason I chose this solution for now, is that fixing the version-comparison is only half the problem; the CLI would need an update as well, in which case it won't be resolved for older versions (was thinking of _comparing_ by SHA, but _printing_ a user-friendly version).

We need to have a look at it in a wider context though; as I mentioned, with containerd reaching 1.0, there may no longer be a need to do this strict comparison.

FWIW, `vendor` check is failing, due to https://github.com/moby/moby/pull/34758#discussion_r156153419 :joy:

**Review by vdemeester — APPROVED** [review]
LGTM :angel:

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by dnephin** [comment]
I guess #27859 will fix the vendor suite

**Comment by thaJeztah** [comment]
hmf

```
17:35:40 golang.org/x/oauth2: Err: exit status 128, out: Cloning into '/go/src/github.com/docker/docker/vendor/golang.org/x/oauth2'...
17:35:40 fatal: remote error: internal server error
17:35:40 Build step 'Execute shell' marked build as failure
```

**Comment by yongtang** [comment]
All tests passed. Merging..

**Pull request merged**
