### PR TITLE
fix regression

### PR DESCRIPTION
**Pull request by jessfraz**
ping @calavera

### CODE REVIEW

**Comment by jfrazelle** [comment]
hang on adding sommething else too

**Comment by jfrazelle** [comment]
ok ready

**Comment by tiborvass** [comment]
LGTM

**Comment by estesp** [comment]
LGTM

**Comment by calavera** [comment]
thanks @jfrazelle! :raised_hands:

**Comment by calavera** [comment]
cherry picked into #15091

**Pull request merged**
