### PR TITLE
Removing the tests. 

### PR DESCRIPTION
**Pull request by moxiegirl**
We have training site now which is more appropriate than this.

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @docker/docs-owners

**Comment by vdemeester** [comment]
@moxiegirl the test scared me to death :scream_cat: :stuck_out_tongue_closed_eyes: 

Anyway, I do agree (even though I'm no docs-owners :cat:).

**Comment by moxiegirl** [comment]
@vdemeester see we were scaring people! Not good.

**Comment by moxiegirl** [comment]
ping @thaJeztah @SvenDowideit

**Comment by thaJeztah** [comment]
LGTM

@moxiegirl If we still want interactive tutorials, perhaps this is nice; http://www.katacoda.com (docker tutorials here: http://www.katacoda.com/courses/docker), created by one of our contributors, @BenHall

**Pull request merged**
