### PR TITLE
Docker is calling cont.Destroy twice on success

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
Docker should not call cont.Destroy more then once. This is causing hooks to be called multiple times, and could potentially cause other problems.

**Comment by duglin** [comment]
Could we just remove the `cont.Destroy()` at the end and let the defer'd func call it?

**Comment by rhatdan** [comment]
@duglin I was not sure of this  But it would probably be fine.

**Comment by rhatdan** [comment]
I was a little worried about whether that would effect.

```
	return execdriver.ExitStatus{ExitCode: utils.ExitStatus(ps.Sys().(syscall.WaitStatus)), OOMKilled: oomKill}, nil
```

**Comment by duglin** [comment]
@rhatdan from looking at the code I think it'd be ok - might be worth a try

**Comment by rhatdan** [comment]
@mrunalp @crosbymichael Any reason to call container.Destroy before calling. 

```
return execdriver.ExitStatus{ExitCode: utils.ExitStatus(ps.Sys().(syscall.WaitStatus)), OOMKilled: oomKill}, nil
```

**Comment by mrunalp** [comment]
@LK4D4 might know

**Comment by icecrime** [comment]
@LK4D4 knows everything

**Comment by rhatdan** [comment]
Can we move this one forward?

**Comment by duglin** [comment]
ping @LK4D4 on whether we can just call `cont.Destroy()` from the defer.

**Comment by LK4D4** [comment]
I think oom will block forever if there was no oom without destroy there.
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
