### PR TITLE
Edit "Working with Containers" page for readability

### PR DESCRIPTION
**Pull request by airandfingers**
Fix some wording/grammar issues

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @airandfingers, changes LGTM

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by fredlf** [comment]
LGTM

**Comment by thaJeztah** [comment]
@airandfingers could you rebase this PR? (the docs were moved from `/docs/sources/..` to `/docs/`).

If you need help, or want us to carry it for you, please let us know!

**Comment by airandfingers** [comment]
I wasn't sure how to rebase, so I pulled down docker/master and made a new branch and new commit. New pull request here: https://github.com/docker/docker/pull/14378

**Comment by thaJeztah** [comment]
@airandfingers no worries. In case you need it for a future PR, instructions for rebasing can be found here: https://docs.docker.com/project/work-issue/#pull-and-rebase-frequently

**Pull request closed without merging**
