### PR TITLE
remove tasksmax, people on newer kernels can add it themselves

### LINKED ISSUE #20036: On RHEL/CentOS 7, version 1.10.0 results in systemd complaints about TasksMax
As noted in my comment on 1057783, on RHEL/CentOS 7, as of version 1.10.0, systemd starts complaining about the `docker.service` unit file:

   [/usr/lib/systemd/system/docker.service:14] Unknown lvalue 'TasksMax' in section 'Service'

This is because systemd appears to have introduced this setting in version 226, while RHEL/CentOS7 still have systemd 219.  Similarly, Debian 8 has systemd 215, so I assume the same error can appear there (I haven't tested that).

The above message appears when installing the official (I assume) RPMs from https://yum.dockerproject.org/repo/main/centos/7.

The solution is probably to maintain different systemd unit files for different distros.

### PR DESCRIPTION
**Pull request by jessfraz**
fix #20036

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
for future reference this was only added for kernels > 4.3, so they can add it in a systemd drop in file if they so choose, those like 5 people running that kernel :P

**Comment by calavera** [comment]
LGTM

**Comment by cyphar** [comment]
@jfrazelle openSUSE Tumbleweed, Arch Linux and a few other distros have >4.3 kernels. :P

**Pull request merged**
