### PR TITLE
remove cli/command/secrets/utils.go

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

Since #29218 was merged, I think file  https://github.com/docker/docker/blob/master/cli/command/secret/utils.go is not necessary any more.

While in cli/command/stack/deploy.go, there is still something should be changed. 
https://github.com/docker/docker/blob/master/cli/command/stack/deploy.go#L231-L250 should be changed with `secret, _, err := client.SecretInspectWithRaw(ctx, secretSpec.Name)`.

ping @ehazlett @thaJeztah @yongtang 

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ehazlett** [comment]
LGTM (nam)

/cc @dnephin

**Comment by yongtang** [comment]
Looks good to me as well (NAM)

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Review by dnephin — APPROVED** [review]
LGTM!

**Pull request merged**
