### PR TITLE
Fix reset timeout for buffer readers.

### PR DESCRIPTION
**Pull request by calavera**
Use our goroutine-safe rand source.

/cc @icecrime, @unclejack

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by endophage** [comment]
I can only guess that the random timeout is to stop clients getting in lock step and all simultaneously hammering a server that's trying to come back up (or another server in the cluster). This may not be a concern in this instance, but I remember it happened to some service in the last couple of years.

That requirement could be easily satisfied with a non-cryptographically secure source of randomness.

**Comment by tiborvass** [comment]
@calavera 

Try
```Go
import "math/rand"

r := rand.New(rand.NewSource(time.Now().UnixNano()))
randVal := r.Intn(120)
// ...
```

**Comment by calavera** [comment]
I changed the initialization to use our goroutine-safe random source. Let me know what you think.

**Comment by LK4D4** [comment]
Looks cool.

**Comment by tiborvass** [comment]
LGTM

**Comment by endophage** [comment]
LGTM

**Comment by unclejack** [comment]
@calavera Can you do a single read from the real rand to seed the pseudo-random number generator, please?

**Comment by calavera** [comment]
> Can you do a single read from the real rand to seed the pseudo-random number generator, please?

why? I don't think we need to be cryptographically secure here, as @endophage comments.

**Comment by unclejack** [comment]
@calavera There's no need to be cryptographically secure, but I also don't think we should rely on time/timestamps for the initial seeding of the pseudo-rng, just like the other PR on which @ewindisch commented on.

**Comment by unclejack** [comment]
Ok, #15123 will make the change with the seeding, no need to make these changes here.

**Comment by LK4D4** [comment]
@calavera Now you can use `random.Rand.Intn` directly :)

**Pull request merged**
