### PR TITLE
[carry 39605] daemon/listeners: use chgrp binary for docker.sock

### PR DESCRIPTION
**Pull request by thaJeztah**
carries https://github.com/moby/moby/pull/39605
closes https://github.com/moby/moby/pull/39605

In case the daemon is compiled statically, it is not using glibc's
uid/gid to name resolving functions (because of `osusergo` build tag),
and so users who

1. use LDAP, NIS, or similar stuff, and
2. not relyingon systemd creating the docker.sock file

will suffer from the issue described in https://github.com/docker/for-linux/issues/186.

Commit a2e384682b8d2b299 (PR #38126) fixed that, but not for the static build case.

So, instead of relying on golang os/user doing a lookup, let's just call
chgrp binary and have it do a group name to gid conversion.

PS Commit messages from c7c2cd4e8e9c0 and 169c013911c helped me to
figure out why the code is the way it is.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@kolyshkin @tonistiigi 

may need some changes in packaging, per https://github.com/moby/moby/pull/39605#issuecomment-515061246

> We need to add this to the list of requirements for running Docker if we are shelling out.

**Comment by tianon** [comment]
What if we shell out conditionally instead? It makes the code a little more complicated, but avoids requiring `chgrp` explicitly (I bet users with things like LDAP will already have it).

We could also consider shelling out to `getent group` instead, which would give a similar end result (although imo still worth considering making conditional).

**Comment by thaJeztah** [comment]
> We could also consider shelling out to `getent group` instead, which would give a similar end result (although imo still worth considering making conditional).

Do you know how to use `getent group` to get just the group ID? Trying to [read `GETENT(1)`](https://man7.org/linux/man-pages/man1/getent.1.html), which describes;

```markdown
group  When no key is provided, use setgrent(3), getgrent(3),
       and endgrent(3) to enumerate the group database.  When
       one or more key arguments are provided, pass each
       numeric key to getgrgid(3) and each nonnumeric key to
       getgrnam(3) and display the result.
```

**Comment by thaJeztah** [comment]
Ah, never mind, I guess I was reading `key` wrong; and `key` (in this case) means "group name(s) or id(s)" to look up, and not "field" in the result;

```bash
getent group systemd-journal docker
systemd-journal:x:101:
docker:x:999:sebastiaan
```

**Comment by thaJeztah** [comment]
I'm actually wondering if this PR is still needed; https://github.com/moby/moby/pull/38126 changed the `lookupGID()` function to use `idtools.LookupGroup(name)`, which uses runc's group lookup function (parsing `/etc/groups`), and falls back to using `getent group`; https://github.com/moby/moby/blob/686be57d0a6e514c0cddb2f3ac9cbb3cbef87f5f/pkg/idtools/idtools_unix.go#L153-L161


https://github.com/moby/moby/blob/686be57d0a6e514c0cddb2f3ac9cbb3cbef87f5f/pkg/idtools/idtools_unix.go#L175-L188

**Comment by thaJeztah** [comment]
Perhaps we no longer need this patch, or am I missing a reason we'd still need it? @kolyshkin @tianon

**Comment by tianon** [comment]
Aha, yeah, IMO this is a non-issue now 😀

**Comment by thaJeztah** [comment]
👍 let's close this one

**Comment by kolyshkin** [comment]
I am very sorry that I somehow managed to totally miss the fact that idtools do fallback to calling `getent` binary. 😞

**Comment by thaJeztah** [comment]
> I am very sorry that I somehow managed to totally miss the fact that idtools do fallback to calling `getent` binary. 😞

No worries, I forgot about the other change as well; I came on this carry, because I was cleaning up some of my branches, and then found https://github.com/moby/moby/pull/39605#issuecomment-692969342, and thought: "oh! I never pushed that branch" 😂

**Pull request closed without merging**
