### PR TITLE
Fix Windows support in .vendor-helpers.sh

### PR DESCRIPTION
**Pull request by tianon**
@jhowardmsft I tested this on Win7 with Go 1.5.1 through msysGit Bash, and I come back with no changes -- can you give it a go and let me know whether we're any closer? :innocent:

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Thx @tianon I have to say I'm somewhat doubtful based on my investiagtions into exactly this earlier this week. Hoping i get time this weekend to try your solution out. My findings showed the I initial on failing on Windows. Once fixed that, the nested go list was the next failure

**Comment by jhowardmsft** [comment]
Initial ln. I fixed it using it inbox mklink and ensuring elevated.

**Comment by thaJeztah** [comment]
@jhowardmsft have you been able to test this?

**Comment by jhowardmsft** [comment]
Not yet. Every day I come in with this at the top of the list. Then open my email and find 20 other pressing TP4 things...

**Comment by LK4D4** [comment]
@jhowardmsft Maybe we can merge it and test in master? :)

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
