### PR TITLE
docs: delete draft container-basics.md

### PR DESCRIPTION
**Pull request by wenchma**
Remove this document, if needed, we can refer to http://docs.docker.com/engine/userguide/networking/dockernetworks/

Signed-off-by: Wen Cheng Ma wenchma@cn.ibm.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thank you @wenchma, actually this document is a draft / temporary document that is pending removal; see https://github.com/docker/docker/pull/18389/files#diff-9d98588b89ff5669403b74301ae0c263R13 and https://github.com/docker/docker/pull/18389/files#diff-9d98588b89ff5669403b74301ae0c263R3

I think the final document that handles this is here; http://docs.docker.com/engine/userguide/networking/dockernetworks/

ping @moxiegirl perhaps we can remove this document now?

**Comment by wenchma** [comment]
@thaJeztah do you mean removing this doc file container-basics.md or this section ?  if need removal, I also like to do :smile:

**Comment by thaJeztah** [comment]
I think this whole document was meant to be deleted, but based on that note, @moxiegirl wanted to keep it around for a short while.

If you can update this PR to *remove* the document, then we can have @moxiegirl decide if it's the right time to merge it :+1:

**Comment by wenchma** [comment]
@thaJeztah updated this PR.

**Comment by thaJeztah** [comment]
Thanks!

**Comment by moxiegirl** [comment]
@thaJeztah my understanding from the networking team was the material on the bridge stuff still applies. That's why the file remains.  

@mavenugo Do we want to remove this information on the default bridge network for 1.10?

**Comment by wenchma** [comment]
@mavenugo  PTAL :smile:

**Comment by mavenugo** [comment]
@moxiegirl am fine with removing this for 1.10.

**Comment by thaJeztah** [comment]
Thanks @mavenugo 

LGTM

**Comment by moxiegirl** [comment]
@wenchma Thank you. Took me a bit to get my head out of other work and focus.  I'm cool with removing the draft.

**Comment by thaJeztah** [comment]
Thanks @wenchma!

**Pull request merged**
