### PR TITLE
Handled escaped characters sent by a client

### PR DESCRIPTION
**Pull request by shiroyuki**
Originally discussed in https://github.com/docker/docker/pull/17204 (CLOSED)

When the request was sent from a HTTP client, the tag value may be escaped. This is to unescape the value first before parse the tag value.

**How to reproduce:**
1. Use docker-py's Client to build an image with a tag like "john/doe".
2. When you run `docker images -a`, you will notice that the new image does not have the tag "john/doe".

Signed-off-by: Juti Noppornpitak jnopporn@shiroyuki.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@shiroyuki Seems like CI failures are related.

**Comment by shiroyuki** [comment]
I will try to take a look after work today.

**Comment by shiroyuki** [comment]
@LK4D4 Is there a way to run a particular test case?

**Comment by LK4D4** [comment]
@shiroyuki Yes. For example:
```
 TESTFLAGS="-check.f DockerSuite.TestRunResolvconfUpdate" make test-integration-cli
```

**Comment by shiroyuki** [comment]
@LK4D4 Thanks. :smile:

**Comment by shiroyuki** [comment]
Just for the record. This is supposed to be a simple PR by just moving the unescaping code from `parsers.ParseRepositoryTag` (PR #17204) to `postImageCreate`. For some unknown reasons, the tests which are doing just fine when the unescaping code is in `parsers.ParseRepositoryTag` but they keep breaking the tests.

I believe that the impact due to the change in `parsers.ParseRepositoryTag` is much wider and these failed tests should appear when I made PR #17204. However, I clearly miss something here. I have been debugging for days now and I still see no clear indicator or feedback why these tests are failing. Could anyone tell me why the changes in the request handler has more visible impact?

**Comment by thaJeztah** [comment]
Moved to code review, because that's where the previous PR was

**Comment by thaJeztah** [comment]
@shiroyuki looks like this needs a rebase; can you rebase your PR, and squash your commits, so that there's only one commit in this PR?

**Comment by thaJeztah** [comment]
ping @shiroyuki looks like something went wrong with your rebase, because there are some non-related commits in here. Can you try to fix those?

**Comment by icecrime** [comment]
I'm going to close this as we haven't heard back from the authors, but please (please!) feel free to reopen a PR when ready.!

**Pull request closed without merging**
