### PR TITLE
fix bash completion for `docker service` subcommands

### PR DESCRIPTION
**Pull request by albers**
This addresses some problems in #23476:
- all options were treated as boolean
- missing one letter options
- missing and undefined options
- aliases for `ls` and `rm`

This only fixes problems. There are several options that need individual completions. I will cover this in a second pass after fixing the other commands. 
Therefore: please merge quickly so that I do not run into merge problems.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @mgoelzer @tianon PTAL

**Comment by albers** [comment]
@mgoelzer Please take a look at this change. Would you like to update the completions for `docker swarm` and `docker node` accordingly?
Please let me know quickly. If I do not hear from you until the, I'l work on these on Saturday.

**Comment by mgoelzer** [comment]
@albers I am leaving for the airport in a few hours and will be traveling for the next week.  I think I am not the one to make these corrections.

**Comment by albers** [comment]
@mgoelzer 
> I am leaving for the airport in a few hours and will be traveling for the next week. I think I am not the one to make these corrections.

That's a pity! I would have liked to work on the remaining issues together with you.

By the way: Thanks very much for your contribution. The issues I spotted are small ones and they would have been easy to fix in your PR with a small amount of mentoring. I'm sorry that I was not quick enough.

**Comment by thaJeztah** [comment]
LGTM

**Comment by tianon** [comment]
As always, excellent work @albers :+1:

LGTM

**Comment by thaJeztah** [comment]
thanks for reviewing @tianon

and, indeed, thanks so much again @albers

**Pull request merged**
