### PR TITLE
Use service alias and configure service VIP or dns-rr

### PR DESCRIPTION
**Pull request by mavenugo**
~~This depends on https://github.com/docker/swarmkit/pull/974 & https://github.com/docker/libnetwork/pull/1263 to be merged & vendored in.~~

### CODE REVIEW

**Comment by tiborvass** [comment]
needs a rebase

**Comment by mavenugo** [comment]
Pulled in appropriate fixes from libnetwork and swarmkit as well.

**Comment by mavenugo** [comment]
All the tests passed. But the CI failed for unrelated reasons.

This PR is required for `docker deploy` functionality to work.

ping @tiborvass @icecrime

**Comment by dnephin** [comment]
I tested this with `docker stack deploy` and it worked as expected. I was able to connect to the network alias that was added.

**Comment by icecrime** [comment]
LGTM! Thanks

**Comment by icecrime** [comment]
Both experimental and janky tests have PASSED, but have timed out: there is most likely tests not cleaning up after themselves (cc @crosbymichael).

**Comment by cpuguy83** [comment]
LGTM

**Comment by icecrime** [comment]
@cpuguy83 Added `process/cherry-pick` :wink:

**Pull request merged**
