### PR TITLE
Update hcsshim to v0.6.5

### PR DESCRIPTION
**Pull request by darstahl**
This update fixes a Windows container leak found in internal testing.

Signed-off-by: Darren Stahl <darst@microsoft.com>

@jhowardmsft

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM. Ping @johnstep

**Comment by jhowardmsft** [comment]
The CI failures are due to the Ubuntu image change to multi-arch earlier today - all CI jobs will fail due to it (@Tianon @johnstep). The test fix is in https://github.com/moby/moby/pull/34829, so will need rebasing after that, or a leap-of-faith by another maintainer merging with ^^ in mind.

**Review by johnstep — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

I restarted CI, I think that will do a rebase first, so should go green now

**Comment by jhowardmsft** [comment]
Yeah the z and ppc errors are the expected ones with known ci fails across the board. Otherwise good so merging (also this only affects Windows which is green)

**Comment by andrewhsu** [comment]
In the future, if possible with a fix like this, would be good to have an associated test.

Also, a description of the impact of not having the fix would help with assessing the significance. Would containers leak all the time? Only on Tuesdays at the top of the hour?

**Comment by darrenstahlmsft** [comment]
This particular one is not possible to have a test for given the current codebase, as this is an error path taken due to platform bugs. It might be possible with some refactoring of hcsshim to make it more testable, which is on my list of things to do. I'll make sure to add test cases when possible, and make hcsshim more testable.

You are correct, I should have explained the leak better. For the record, I'll do that here. The leak is triggered by a platform bug. The contract of hcsshim CreateContainer is that if it returns an error, the container should not exist. The bug is that if the platform function in HCS, HcsCreateComputeSystem succeeds, but either the async callback is never fired, or the caller fails to register for the async notification, the container may still exist at the platform level. This causes the expected state of the system to be out of sync with what the caller expects, as hcsshim CreateContainer call has failed, but the container was created and not destroyed. hcsshim now correctly cleans up the container in this case.

The bug that triggers this does not exist in publically released versions of Windows, and has been fixed in internal versions (with proper testing to prevent regression at the platform level), this is mostly a change to ensure hcsshim follows the correct contract with HCS in the potential case of future similar bugs.

**Pull request merged**
