### PR TITLE
New libcontainer api

### PR DESCRIPTION
**Pull request by LK4D4**
This is not fully finished integration(there are a lot ugly places, which can be much nicer), but this code contains new libcontainer API, so we can test it and find some bugs.
ping @crosbymichael

### CODE REVIEW

**Comment by jfrazelle** [comment]
Whoa nice, so @icecrime does this mean we can make the hairpin nat PR after?

**Comment by LK4D4** [comment]
@jfrazelle Yup, indeed. And probably we can remove userland-proxy :)

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
ping @tiborvass @jfrazelle @icecrime 
Review pls :) There is a lot of further work on this before release.

**Comment by estesp** [comment]
I made a few minor comments; but I've reviewed the Docker integration code (not the libcontainer vendor update) and **LGTM**

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
shit this broke lxc https://jenkins.dockerproject.com/job/Docker%20Master%20(lxc)/3/console

**Comment by LK4D4** [comment]
@jfrazelle haha, that's expected :)

**Pull request merged**
