### PR TITLE
[WIP] Docker stats all

### LINKED ISSUE #10772: Request: docker stats without any container should display all running containers
Similar to the behavior of the `top` utility, if no container is passed, it should show all containers. Since stopped containers are likely of no interest, I think it would be best to just show running containers.

### PR DESCRIPTION
**Pull request by runcom**
~~Carry and~~ fixes #10772

I think this can also be further discussed btw and so docs still missing

### CODE REVIEW

**Comment by cpuguy83** [comment]
I think with something like this wouldn't we want new containers to be automatically added?
Otherwise someone could just do `docker stats $(docker ps -aq)`

**Comment by runcom** [comment]
Yup I just carried a commit and added a test, I can go with what you suggested as well, just need to discuss because I've noticed people commenting and no pr yet made

**Comment by runcom** [comment]
ping @duglin I'm sure you have a point for this

**Comment by duglin** [comment]
this sounds like a useful feature for those who use 'docker stats' today.
Some comments (from our irc chat)
- default should show just running containers
- add a "-a" type of flag to show all (like 'docker ps')
- would be good if it didn't wrap - so stop at 80 columns if we can't determine the tty width
- extra bonus points if people can choose the columns to display  :-)

**Comment by icecrime** [comment]
Agree to all @duglin points above. If that's ok I'll close this until you update it (also as you can reopen yourself :p)

**Comment by runcom** [comment]
@icecrime sure, I'm on it

**Comment by aanm** [comment]
@runcom In case you're interested https://github.com/noironetworks/docker-statis

**Pull request closed without merging**
