### PR TITLE
Update docs and test of exec create api return codes

### PR DESCRIPTION
**Pull request by wenchma**
Fixes issue #18054

Signed-off-by: Wen Cheng Ma wenchma@cn.ibm.com

### CODE REVIEW

**Comment by vdemeester** [comment]
@wenchma compilation error on integration test :sweat:.

```bash
./docker_api_exec_test.go:62: undefined: exec_test
```

**Comment by wenchma** [comment]
@vdemeester sorry for the typo error, :wink:

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
