### PR TITLE
Create build router separate from image router.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Image router should deal only with "image" endpoints. However, it was managing the "build" endpoint as well. This commit creates separate build router.

### CODE REVIEW

**Comment by calavera** [comment]
Nice!

It looks like go-lint is not super happy:

```
Errors from golint:
api/server/router/build/backend.go:3:1: comment on exported type Backend should be of the form "Backend ..." (with optional leading article)
```

**Comment by MHBauer** [comment]
I could argue that the output of a `build` is an image, but I won't because the build endpoint is kind of nasty. It is probably best to separate it. Plus it pulls a lot of imports and code out of image. I like it.

**Comment by anusha-ragunathan** [comment]
@MHBauer : The routers are split based on the remote API endpoints. So although a build outputs an image, it has its own "build" endpoint and hence the reorg.

**Comment by calavera** [comment]
LGTM. I restarted janky to remove that flacky error.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
