### PR TITLE
Fix MkdirAll* and its usage

### PR DESCRIPTION
**Pull request by kolyshkin**
**- What I did**

1. Fixed `idtools.Mkdir*` functions to return an error if a directory to be created already exists but is not a directory.
2. Fixed using `MkdirAll*` functions to not ignore `IsExist` errors.

Please see commit messages for details.

**- How I did it**
Manually checked all the code paths using MkdirAll and idtools.Mkdir functions.

**- How to verify it**
For idtools.Mkdir*, there is a test case included.

**- Description for the changelog**
- not required

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Also /cc @salah-khan (because the same changes may be needed for the Windows side as well if we start supporting actual `chown` / `chmod`?) https://github.com/moby/moby/pull/35521

**Comment by thaJeztah** [comment]
@kolyshkin looks like there's some lint errors; 

```
22:14:46 Congratulations!  All commits are properly signed with the DCO!
22:17:09 daemon/daemon_windows.go:1::warning: file is not goimported (goimports)
22:17:09 volume/local/local.go:142:1:warning: alreadyExistsError is unused (deadcode)
22:17:09 pkg/idtools/idtools_unix.go:34::error: os.PathError composite literal uses unkeyed fields (vet)
```

**Review by boaz0 — COMMENTED** [review]
LGTM if all green 🍏

**Comment by crosbymichael** [comment]
LGMT

**Pull request merged**
