### PR TITLE
Support running 'docker help daemon' with split binaries

### LINKED ISSUE #23102: `docker help daemon` does not work
With current master, `docker daemon --help` works, but `docker help daemon` fails:

```bash
root@85796c413084:~# docker help daemon
dockerd: "dockerd" requires 0 arguments.

Usage:  dockerd [OPTIONS]

root@85796c413084:~# docker --version
Docker version 1.12.0-dev, build d305b03
```

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #23102

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

(experimental is green, but didn't notify GitHub)

**Comment by thaJeztah** [comment]
ping @vdemeester PTAL

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by albers** [comment]
Thanks @vdemeester!

**Pull request merged**
