### PR TITLE
[WIP] Cherry picks 1.12.0 rc4

### LINKED ISSUE #23983: `docker network create -d bridge test` works if there is already an overlay network named test?
**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 380
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: active
 NodeID: 4b1et52uyr6nquyj7js30fgcu
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:9ebab8ad017aa10bd8eee00ba34f7e22932deeee38adf6e864786fb643668caf
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.`docker network create -d overlay test` to create an overlay network named test
2.`docker network create -d bridge test` to create a bridge network named test

Above steps can work. Actually they own the same name. It is a **CONFLICT** in the network naming.

While if I create bridge network named test, then create overlay network named test, daemon will report an error named:
```
Error response from daemon: network with name test already exists
```

In addition, This bug will result in `docker network inspect test` works if two networks with same name on a single daemon.

### PR DESCRIPTION
**Pull request by tiborvass**
Cherrypicks for rc4:
- [#24179](https://github.com/docker/docker/pull/24179)
  - 841f985 [Docs] clarified local volume driver docs
- [#24217](https://github.com/docker/docker/pull/24217)
  - 48744e0 Improve systemd service unit in _Automatically start containers_
- [#24128](https://github.com/docker/docker/pull/24128)
  - d761719 rename desired_state filter to desired-state
- [#24059](https://github.com/docker/docker/pull/24059)
  - f98f596 add menu.md, make index.md command line reference, update typos/minor errors in cli docs
- [#23947](https://github.com/docker/docker/pull/23947)
  - 2bc2165 Volume mounts need to use "Binds" API field
- [#24248](https://github.com/docker/docker/pull/24248)
  - 9aed7d1 Fix --auto-accept documentation
- [#24254](https://github.com/docker/docker/pull/24254)
  - 04c94a0 Improve timestamp formatting
- [#24245](https://github.com/docker/docker/pull/24245)
  - 68b8cc9 Update network_create.md
- [#24251](https://github.com/docker/docker/pull/24251)
  - ac12696 fix typo in "readonly" flag in documentation
- [#24279](https://github.com/docker/docker/pull/24279)
  - 0244174 [doc] add missing whitespace
- [#24281](https://github.com/docker/docker/pull/24281)
  - 76b09be Fix typo
- [#24264](https://github.com/docker/docker/pull/24264)
  - 585332d man: add missing --add-runtime
- [#23871](https://github.com/docker/docker/pull/23871)
  - 256edc2 23837 Added long flag to docker ps for checking latest n containers. Updated to "--last"
- [#24257](https://github.com/docker/docker/pull/24257)
  - a268522 remove incorrect L3 recommendation
- [#24287](https://github.com/docker/docker/pull/24287)
  - 644a742 Fix spelling in comments, strings and documentation
- [#24272](https://github.com/docker/docker/pull/24272)
  - 0246987 Add zsh completion for 'docker node' commands
- [#24275](https://github.com/docker/docker/pull/24275)
  - 2086663 Add zsh completion for 'docker swarm' commands
- [#24293](https://github.com/docker/docker/pull/24293)
  - 97c77b7 add a whitespace in plugin's logging
- [#24299](https://github.com/docker/docker/pull/24299)
  - 8c17934 Add fchmod and fchmodat to TestRunSeccompProfileDenyChmod
- [#24276](https://github.com/docker/docker/pull/24276)
  - a5c7eb6 Add zsh completion for 'docker daemon --runtimes' and 'docker run --runtime'
- [#24274](https://github.com/docker/docker/pull/24274)
  - f5d768e Add zsh completion for 'docker service' commands
- [#24312](https://github.com/docker/docker/pull/24312)
  - 88da491 Fix typo - stacks being managed, not tasks?
- [#24300](https://github.com/docker/docker/pull/24300)
  - 9c1566a Add NoArm64 testRequires and skip Schema1RegistrySuite on arm64
- [#24321](https://github.com/docker/docker/pull/24321)
  - 1205a55 Fix a grammatical error in errClusterNetworkOnRun()'s error message.
- [#24332](https://github.com/docker/docker/pull/24332)
  - edc307c fix typos
- [#24191](https://github.com/docker/docker/pull/24191)
  - 8b8f86a Mask swarm secrets from daemon logs
- [#23996](https://github.com/docker/docker/pull/23996)
  - 33984f2 Always store the image digest when pulling and pushing an image.
  - 8906f83 Treat digest only images as dangling
- [#24298](https://github.com/docker/docker/pull/24298)
  - 533bd82 fix stdout and stderr in api client Signed-off-by: allencloud allen.sun@daocloud.io
- [#24173](https://github.com/docker/docker/pull/24173)
  - b0fc5a2 Allow service and node filter to be name…
- [#24013](https://github.com/docker/docker/pull/24013)
  - 9836162 Atomically save libtrust key file
- [#24307](https://github.com/docker/docker/pull/24307)
  - 8db6109 contrib: systemd: set Limit\* to infinity
- [#24158](https://github.com/docker/docker/pull/24158)
  - 0ce5158 Fixed a few network UI issues in swarm-mode
- [#24339](https://github.com/docker/docker/pull/24339)
  - 2f19e91 image spec: Correct set of acceptable characters in tags
- [#24351](https://github.com/docker/docker/pull/24351)
  - 0af04b6 fix severe fd leak in stack
- [#23740](https://github.com/docker/docker/pull/23740)
  - 6daf3d2 Validate hostname starting from 1.24 API.
- [#24323](https://github.com/docker/docker/pull/24323)
  - 22a3d1f Improve the warning messages when leaving a Swarm cluster
- [#24363](https://github.com/docker/docker/pull/24363)
  - 8aa37bd vendor docker/distribution 4e17ab5d319ac5b70b2769442947567a83386fbc
  - a0c8970 integration-cli: ensure digest is the same after cross-repo push
- [#24133](https://github.com/docker/docker/pull/24133)
  - e5ec575 Implement service integration tests
- [#24373](https://github.com/docker/docker/pull/24373)
  - 7631dc8 Remove unmatched bracket from _docker for zsh
- [#24401](https://github.com/docker/docker/pull/24401)
  - 668b8a9 Change NAME to HOSTNAME in docs for `docker node ls`
- [#24330](https://github.com/docker/docker/pull/24330)
  - 2de9585 make `docker service --help` text for `--endpoint-mode` more consistent
- [#24053](https://github.com/docker/docker/pull/24053)
  - 140ec59 re-vendor engine-api
  - db271b8 re-vendor swarmkit
  - 56f3422 Use newer default values for mounts CLI
- [#24383](https://github.com/docker/docker/pull/24383)
  - d32df6d Detect non-plugin content during install and error out.
- [#24369](https://github.com/docker/docker/pull/24369)
  - 6ec4a64 Vendor engine-api 1d247454d4307fb1ddf10d09fd2996394b085904
  - a859a33 Use "on-failure" for both containers and services
- [#24349](https://github.com/docker/docker/pull/24349)
  - 7342e42 Generate a swarm joining secret if none is specified
- [#24291](https://github.com/docker/docker/pull/24291)
  - f4cfc6b Updates on cli reference documentation
- [#24156](https://github.com/docker/docker/pull/24156)
  - fd4f5c2 Windows: Ensure VolumePath is not set for Hyper-V containers
- [#23312](https://github.com/docker/docker/pull/23312)
  - 0682468 Make the docker proxy a standalone binary not a re-exec
  - 3ae0c66 Update libnetwork vendoring
  - d428a7a Update swarmkit vendoring
  - 6dfba78 Fix test case for docker_api_swarm_test.go
- [#24426](https://github.com/docker/docker/pull/24426)
  - 1255e53 add iptables=false to docs for multiple daemons
- [#24432](https://github.com/docker/docker/pull/24432)
  - 0938170 add constraint to service create ref
- [#24448](https://github.com/docker/docker/pull/24448)
  - 7102e09 Update binary install docs with new contents of tgz
- [#24450](https://github.com/docker/docker/pull/24450)
  - 5916264 daemon: ensure we set default options to stock runtime
- [#24449](https://github.com/docker/docker/pull/24449)
  - 47ace5c Add missing docker-proxy into managed files in rpm spec
- [#24431](https://github.com/docker/docker/pull/24431)
  - 4623276 Revert "Fixed a few network UI issues in swarm-mode"
  - 6a4b21b fixes #23983
- [#24435](https://github.com/docker/docker/pull/24435)
  - 2d5dc94 Fix daemon not cleaned up w/ live restore enabled
- [#24358](https://github.com/docker/docker/pull/24358)
  - 2539332 Validate arguments for `ps` in `docker top`
- [#24119](https://github.com/docker/docker/pull/24119)
  - 2b34fa0 bash completion for `docker {service,node}` filters
  - 715754e bash completion can be configured to show node and service IDs
  - 009d50e bash completion for default port on `docker swarm {init,join}`
- [#24412](https://github.com/docker/docker/pull/24412)
  - d37a739 Add ltdl dependencies for aarch64
- [#23734](https://github.com/docker/docker/pull/23734)
  - bc20354 Add release tag reference links in deprecated.md
- [#24459](https://github.com/docker/docker/pull/24459)
  - 4d12e64 vendor: update swarmkit to 6478bc19
  - 6586f4f Update executor volumes from swarmkit
  - 8a50315 Add logdrivers to executor from swarmkit
  - a3f1577 Add more complicated demotion testcases
- [#24468](https://github.com/docker/docker/pull/24468)
  - a3b9dd8 Fix seccomp output in `docker info`
- [#24490](https://github.com/docker/docker/pull/24490)
  - 9fadb8f integration-cli: fix --net=none tests
- [#24139](https://github.com/docker/docker/pull/24139)
  - 1ded1f2 add health check in docker cluster
- [#24488](https://github.com/docker/docker/pull/24488)
  - 7b3ac47 Fix grammar in docker volumes tutorial
- [#24239](https://github.com/docker/docker/pull/24239)
  - d0737e9 Add blanks lines in docs for clarity
- [#24471](https://github.com/docker/docker/pull/24471)
  - 6c9b5da Fixes broken link in docs.
- [#24051](https://github.com/docker/docker/pull/24051)
  - 416613f return err when stack name does not exist
- [#24474](https://github.com/docker/docker/pull/24474)
  - b32cfb3 swarmkit expects network-id for as target
- [#23513](https://github.com/docker/docker/pull/23513)
  - 82d70f4 Change content-trust doc to not point to images that don't exist #22730
- [#24501](https://github.com/docker/docker/pull/24501)
  - 1fb1136 Remove execution driver
- [#24229](https://github.com/docker/docker/pull/24229)
  - 863ab9a Shutdown plugins during daemon shutdown.
- [#24464](https://github.com/docker/docker/pull/24464)
  - f02ec39 Use waitAndAssert to test node state changes
- [#24522](https://github.com/docker/docker/pull/24522)
  - 9af24ba Clarify warning against using build-time variables for secrets
- [#24519](https://github.com/docker/docker/pull/24519)
  - 2c9b5ad Add missing API docs for HostConfig.PidMode
- [#24532](https://github.com/docker/docker/pull/24532)
  - 93fa7e7 Fix a minor typo in swarm tutorial docs
- [#24146](https://github.com/docker/docker/pull/24146)
  - 8e14882 Add support for comma-separated --auto-accept syntax. Signed-off-by: John Harris john@johnharris.io
- [#24520](https://github.com/docker/docker/pull/24520)
  - a12ab28 Don't retry push on an unknown repository
- [#24518](https://github.com/docker/docker/pull/24518)
  - ff98da0 Allow option to override kernel check in overlay2
- [#24528](https://github.com/docker/docker/pull/24528)
  - c8e4e95 Return an empty services list if no services are running
  - 65e7213 Add API test for empty services list
- [#24544](https://github.com/docker/docker/pull/24544)
  - 9ae64de add caveat for network plugins in swarm mode
- [#24465](https://github.com/docker/docker/pull/24465)
  - ae4137a integration-cli: add test for restarting entire swarm cluster
- [#24552](https://github.com/docker/docker/pull/24552)
  - 0651775 Add "auto-accept=none" to documentation
- [#24550](https://github.com/docker/docker/pull/24550)
  - 0e7a107 Fix some broken sourceforge.net links
- [#24546](https://github.com/docker/docker/pull/24546)
  - 92c40f9 Vendoring libnetwork
  - a4926a4 Fixing a stale endpoint issue that blocks ingress network cleanup
- [#24549](https://github.com/docker/docker/pull/24549)
  - 5f7b1b6 Fix panic when meminfo couldn't be read
- [#24548](https://github.com/docker/docker/pull/24548)
  - 7dff310 Fix panic while merging log configs to nil map
- [#23324](https://github.com/docker/docker/pull/23324)
  - 5b21c8a Organize run flags into categories
  - c0c7d5e Rename `--net` to `--network`
- [#24558](https://github.com/docker/docker/pull/24558)
  - dab2878 Uncomment the TasksMax val later in the deb build

### CODE REVIEW

**Comment by justincormack** [comment]
(feel free to ignore the arm and power test failures for rc4, will take a look though as they oddly fail in pretty much the same place).

**Comment by tophj-ibm** [comment]
@justincormack the power and at least 7/8 of the arm test failures are because of an issue with the swarm testing daemon itself, that's been fixed upstream #23790, but due to it adding in another env variable they decided not to add it to 1.12. Follow up issue is here #23909

I'm not sure about the arm test TestApiSwarmManagerRestore. It looks like the same issue but I have no idea why it wouldn't also fail on power if it was, maybe it's timing out. Also it seems fixed on master. @StefanScherer not sure if you know anything about that one.

**Comment by runcom** [comment]
> I'm not sure about the arm test TestApiSwarmManagerRestore. It looks like the same issue but I have no idea why it wouldn't also fail on power if it was, maybe it's timing out. Also it seems fixed on master. @StefanScherer not sure if you know anything about that one.

I've changed that test in master here https://github.com/docker/docker/pull/24490/files#diff-b0704fa50ffe4affbda6f7f889152ad3R683 to require network connectivity - I doubt it have anything to do with the failure here but I believe no other changed it :/

**Comment by StefanScherer** [comment]
@tophj-ibm I've just started an ARM test-integration-cli to check master. This takes some time.
I also think there might be too small timeout values for ARM and/or pulling busybox from hub as an Intel image.

**Comment by tiborvass** [comment]
LGTM waiting for CI

**Pull request merged**
