### PR TITLE
[WIP] docker-py: use pip to install dependencies

### PR DESCRIPTION
**Pull request by thaJeztah**
follow-up to https://github.com/moby/moby/pull/38524

This makes sure that we have all the requirements installed and that they have the right version.
    
Moved the installation earlier in the Dockerfile, as docker-py is not so frequently updated in this repository, so optimizing for caching.
    
Removed all the apt-packages that are not needed.

### CODE REVIEW

**Comment by olljanat** [comment]
PowerPC failure looks like related.

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by cpuguy83** [comment]
Nice, I wonder if we can go even further and install docker-py deps into their own image and then `COPY` them in at the end.

`pip install --target` would allow us to customize the path at least or can just use the default path.

**Comment by kolyshkin** [comment]
I would argue that using distro packages should be preferred to using pip -- distro packages are faster to install and (supposedly?) better maintained so more stable. The current approach is to install as much as we can from the distro packages, and use pip for the rest.

The only downside I see is packages to be installed are spread between two places in Dockerfile, and it's not bad enough per se to switch to pip entirely. @thaJeztah perhaps I'm missing something -- what is your motivation to prefer pip to apt install?

**Comment by thaJeztah** [comment]
Closing this in favour of https://github.com/moby/moby/pull/39068

**Pull request closed without merging**
