### PR TITLE
Add proper refcounting to zfs graphdriver

### LINKED ISSUE #20153: docker 1.10, zfs, device or resource busy
This worked in 1.9.1 with zfs driver.  Works fine with devicemapper on 1.10. Have not tried other storage drivers.

# docker run -d -it busybox /bin/sh
5371c4f7e4ba111e3c16797cec60bb3607c31cd289358c2baf37c5913e4f1d64

# docker cp setupNode.sh 5371c4f7e4ba:/tmp/setupANode.sh
Error response from daemon: error creating zfs mount of rock/docker/1d666677f540ca4cc7a1498dabf1f80785cf08d2583fdcc783d0b6dd8025cf1c to /var/lib/docker/zfs/graph/1d666677f540ca4cc7a1498dabf1f80785cf08d2583fdcc783d0b6dd8025cf1c: device or resource busy

# docker stop 5371c4f7e4ba
5371c4f7e4ba
# docker rm 5371c4f7e4ba
Failed to remove container (5371c4f7e4ba): Error response from daemon: Driver zfs failed to remove root filesystem 5371c4f7e4ba111e3c16797cec60bb3607c31cd289358c2baf37c5913e4f1d64: mount still active
# docker rm -f 5371c4f7e4ba
Failed to remove container (5371c4f7e4ba): Error response from daemon: Driver zfs failed to remove root filesystem 5371c4f7e4ba111e3c16797cec60bb3607c31cd289358c2baf37c5913e4f1d64: mount still active
# docker rm -f 5371c4f7e4ba
Failed to remove container (5371c4f7e4ba): Error response from daemon: No such container: 5371c4f7e4ba

Bare metal (Fedora, Archlinux -- happens on both

# docker info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 289
Server Version: 1.10.0
Storage Driver: zfs
 Zpool: rock
 Zpool Health: ONLINE
 Parent Dataset: rock/docker
 Space Used By Parent: 4182804992
 Space Available: 11007375059456
 Parent Quota: no
 Compression: lz4
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: null host macvlan bridge
Kernel Version: 4.3.4-300.fc23.x86_64
Operating System: Fedora 23 (Server Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 24
Total Memory: 125.9 GiB
Name: XXXXXXXXXX
ID: TSX3:TGZ6:FTMX:CPF3:FZA5:OTIM:I4VM:MLG3:2A25:6XJD:NMZ6:W72S
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

# docker version
Client:
 Version:         1.10.0
 API version:     1.22
 Package version: docker-1.10.0-28.gitf392451.fc24.x86_64
 Go version:      go1.6rc1
 Git commit:      3465b10
 Built:           Sun Feb  7 10:34:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.0
 API version:     1.22
 Package version: docker-1.10.0-28.gitf392451.fc24.x86_64
 Go version:      go1.6rc1
 Git commit:      3465b10
 Built:           Sun Feb  7 10:34:25 2016
 OS/Arch:         linux/amd64

# uname -a
Linux XXXXXX  4.3.4-300.fc23.x86_64 #1 SMP Mon Jan 25 13:39:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# dnf list installed zfs
Last metadata expiration check performed 0:07:09 ago on Tue Feb  9 11:46:59 2016.
Installed Packages
zfs.x86_64                                 0.6.5.4-1.fc23                                  @zfs

### PR DESCRIPTION
**Pull request by estesp**
Fixes #20153 

Fixes issues with layer remounting (e.g. a running container which then
has `docker cp` used to copy files in or out) by applying the same
refcounting implementation that exists in other graphdrivers like
overlay and aufs.

Docker-DCO-1.1-Signed-off-by: Phil Estes estesp@linux.vnet.ibm.com (github: estesp)

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
What's weird about this is the layer store already does refcounting for RWLayers.

**Comment by estesp** [comment]
but not to determine whether to call layer.Mount or layer.Unmount (https://github.com/docker/docker/blob/master/layer/mounted_layer.go#L126-L151) which ends up calling `driver.Put()` and `driver.Get()`; so the driver has to determine whether a physical mount/unmount is required.

**Comment by grexe** [comment]
also running into this on Linux 4.4.6-1-MANJARO x64 with docker 1.10.3, build 20f81dd and /var/lib/docker mounted on a ZFS partition.
Is there any fix version I can try?

**Comment by thaJeztah** [comment]
@grexe is `/var/lib/docker` only mounted on a ZFS partition, or are you using the `zfs` graphdriver

**Comment by estesp** [comment]
It would also be helpful to have a debug log (from running the daemon with "`-D`") during the errors you are getting to confirm it is the same issue or a different one than the issue fixed under this PR.

Also, if you want something else to try if we do find a bug, the Docker 1.11-rc5 release candidate is out, and I believe the refcounting/layer mounting changed from the design in 1.10 and prior.  Anything we do find will probably need to be fixed on that codebase.

**Pull request merged**
