### PR TITLE
No options to tmpfs is valid

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
This fixes at least part of https://github.com/docker/docker/issues/18853

**Comment by LK4D4** [comment]
@rhatdan Can we have test for this?

**Comment by rhatdan** [comment]
Nevermind I found the script.  On my Fedora Rawhide box with the fix above the script runs successfully.

```
# sh /tmp/testtmpfs.sh
\n*:: Mount a tmpfs to verify basic tmpfs works*
mount: none mounted on /tmp/tmpfstest.
none on /tmp/tmpfstest type tmpfs (rw,relatime,seclabel,size=1048576k)
WORKS.
\n*:: Create a testfile in the tmpfs*
-rw-r--r--. 1 root root 29 Dec 22 14:07 /tmp/tmpfstest/pewpew
Tue Dec 22 19:07:14 UTC 2015
\n*:: debian*::wheezy container uname*
Linux eb38f01844bd 4.4.0-0.rc5.git3.1.fc24.x86_64 #1 SMP Fri Dec 18 16:47:01 UTC 2015 x86_64 GNU/Linux
WORKS.
\n*:: debian*::wheezy container uname w readonly filesystem*
Linux 6278db9ea592 4.4.0-0.rc5.git3.1.fc24.x86_64 #1 SMP Fri Dec 18 16:47:01 UTC 2015 x86_64 GNU/Linux
WORKS.
\n*:: debian*::wheezy container uname with --tmpfs /etc*
Linux be2094aad3b9 4.4.0-0.rc5.git3.1.fc24.x86_64 #1 SMP Fri Dec 18 16:47:01 UTC 2015 x86_64 GNU/Linux
WORKS.
\n*:: debian*::wheezy container uname with --tmpfs /etc:noexec*
Linux f74aedc640f8 4.4.0-0.rc5.git3.1.fc24.x86_64 #1 SMP Fri Dec 18 16:47:01 UTC 2015 x86_64 GNU/Linux
WORKS.
\n*:: debian*::wheezy container uname with --tmpfs /etc:rw,nosuid using sudo*
Linux 97b3e3c2df94 4.4.0-0.rc5.git3.1.fc24.x86_64 #1 SMP Fri Dec 18 16:47:01 UTC 2015 x86_64 GNU/Linux
WORKS.
\n*:: busybox touch /run/somefile (from tests)*
WORKS.
\n*:: busybox fs options touch /run/somefile (from tests)*
WORKS.
\n*:: busybox fs --tmpfs /etc*
WORKS.
\n*:: busybox --tmpfs /etc:noexec
WORKS.
\n*:: Docker version*
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   81c8e4d-dirty
 Built:        Tue Dec 22 13:56:05 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   81c8e4d-dirty
 Built:        Tue Dec 22 13:56:05 2015
 OS/Arch:      linux/amd64
\n*:: Docker info*
Containers: 15
Images: 44
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:2-3014703-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.026 GB
 Data Space Total: 107.4 GB
 Data Space Available: 72.76 GB
 Metadata Space Used: 1.987 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.113 (2015-12-05)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-0.rc5.git3.1.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.478 GiB
Name: dhcp-10-19-62-196.boston.devel.redhat.com
ID: QCJD:BQVE:IUG3:CFBA:4EKW:A3RD:JUR2:7VOG:XWP6:2ELL:KMIY:E5JM
\n*:: Docker group*
docker:x:975:
\n*:: Host information*
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 24 (Rawhide)
Release:	24
Codename:	Rawhide
Linux dhcp-10-19-62-196.boston.devel.redhat.com 4.4.0-0.rc5.git3.1.fc24.x86_64 #1 SMP Fri Dec 18 16:47:01 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
Added a test for 

```
docker run --tmpfs /run:noexec ...
```

Which was causing issues.

**Comment by LK4D4** [comment]
@rhatdan Thanks

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
