### PR TITLE
Remove pkg/systemd/booted.go

### PR DESCRIPTION
**Pull request by runcom**
It's not used anywhere

Plus coreos/go-systemd has already implemented the same function (`IsRunningSystemd` in v3, also `SdNotify` in `pkg/systemd/sd_notify.go` is implemented in v3 the same way, so when we update `runc` we can update go-systemd to v3 here in docker as well and have the methods proxied, I have a pr ready for this also)

Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
good find LGTM

**Comment by rhatdan** [comment]
We are using this in one of our patch sets.  --init=systemd  When is runc going to be updated so we can switch to using this interface?

**Comment by runcom** [comment]
@rhatdan https://github.com/opencontainers/runc/pull/150 needs to be merged before having go systemd v3 here as well

**Comment by rhatdan** [comment]
Ok I added a patch to our code for now, until this gets merged to check if systemd is enabled.

**Pull request merged**
