### PR TITLE
Add Aaron Swartz to the names generator.

### PR DESCRIPTION
**Pull request by jessfraz**
https://en.wikiquote.org/wiki/Aaron_Swartz

Docker-DCO-1.1-Signed-off-by: Jessica Frazelle jess@docker.com (github: jfrazelle)

### CODE REVIEW

**Comment by paultag** [comment]
:+1: this would really mean a lot.

**Comment by jfrazelle** [comment]
:D

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
:heart: actually surprised he wasn't in there yet.

**Comment by duglin** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by tianon** [comment]
Oh man so much this :heart: :heart:

**Comment by hammerdr** [comment]
<3

**Comment by jlmitch5** [comment]
+100000

**Pull request merged**
