### PR TITLE
Fix rm container error in aufs and devicemapper after daemon crash

### PR DESCRIPTION
**Pull request by liusdu**
This patchset is simaler to 3916561619d45a3d8ca17dfa467149824111023a(Fix Put without Get in overlay).

If there are running containers when daemon crash. After daemon restarts. We can not remove containers due to "device is busy"  in aufs and devicemapper.
#### Take devicemapper as an example.
-  Run a container

``` bash
# docker run -tid busybox sh
fdca994bec2100335c912d56540acc6df271b36b2554270c606836277e159e15
```
-  kill daemon and restart

``` bash
# killall  -9 docker
# docker daemon -s devicemapper 
ERRO[0001] Error unmounting container fdca994bec2100335c912d56540acc6df271b36b2554270c606836277e159e15: UnmountDevice: device not-mounted id 780117718cc91335dc4c7fb4e3246f9b06fbeff654782c9ff0277555c21d437e
```
- Then I can not remove container `fdca994bec21`

``` bash
 docker rm -f fdca994bec21
Error response from daemon: Driver devicemapper failed to remove root filesystem fdca994bec2100335c912d56540acc6df271b36b2554270c606836277e159e15: Device is Busy
Error: failed to remove containers: [fdca994bec21]
```

Guys in issue #4036 has encountered this problem.

### CODE REVIEW

**Comment by tiborvass** [comment]
Unless I'm missing something, this makes sense to me

**Comment by estesp** [comment]
ping @rhvgoyal for any comments on the devicemapper changes..

**Comment by rhvgoyal** [comment]
Can patch author please explain what's the core issue and how this patch fixes the issue.

**Comment by rhvgoyal** [comment]
Instead of putting hacks in graph driver, why don't we extend the graph driver api and introduce another parameter to Put() that will tell graph driver that we are doing a Put() after an unclean shutdown(). so don't try to do any error checking on state of various paremters.

Put(id string, forced bool)

If it is forced killing of old container, forced can be true and then graph driver will not do error checking. Simply do the lazy unmount and return.

Point being that  top layer knows that a container is running when it should not have been. So docker most likely is running after an unclean shutdown. And it should communicate that information to graph driver instead of graph driver trying to guess it.

**Comment by rhvgoyal** [comment]
@liusdu, if we find that changing graph driver api is too much for this problem, then let us cleanup the code a bit as per the comments.

**Comment by liusdu** [comment]
@rhvgoyal  @estesp  @thaJeztah  @tiborvass  Thanks for your replies.

@rhvgoyal  If there are running containers when daemon crashes.,docker daemon has no chance to do the nesessary cleanups. So the containers' state is still running(but interactive mode containers will exit becasue of pipes broken.).

And when we restart docker daemon, it will stop all running containers. One of steps is to call the "Put" method to do the unmount.

**Comment by liusdu** [comment]
@rhvgoyal 

The "Put" process:
-->func NewDaemon                                 `daemon/daemon.go:617`
    -->func (daemon *Daemon) restore()   `daemon/daemon.go:280`
       -->func (daemon *Daemon) Register(container *Container) `daemon/daemon.go:280`
            -->daemon.Unmount(container)  `daemon/daemon.go:252`
               -->func (d *Driver) Put(id string) error  `devmapper/driver.go:207`

**Comment by liusdu** [comment]
@rhvgoyal  Updated! 

I add some more comments in code to explain why the mountCount may be negative. And remove the unnecessary  mounting status check.

**Comment by liusdu** [comment]
@rhvgoyal Updated!

**Comment by liusdu** [comment]
@rhvgoyal  Done, please take a look!

**Comment by rhvgoyal** [comment]
devicemapper specific changes LGTM. Somebody needs to review aufs related changes.

**Comment by liusdu** [comment]
Thanks @rhvgoyal !
 ping @LK4D4  @crosbymichael , I fix an issue very similar to  #13325. So can you please review aufs part?

**Comment by estesp** [comment]
I'm changing to code review as I don't think there are any design elements here at this point--just determining the right way to fix, and I believe devicemapper is now acceptable and I've looked over the aufs changes and compared to the overlay fix from @LK4D4 

My only disappointment is that the added test in #13325 (https://github.com/docker/docker/commit/3916561619d45a3d8ca17dfa467149824111023a#diff-6d9e7586edc05102d4ad66e54659c8c5R1174) cannot catch the aufs and devicemapper problems because they don't name their mount dirs with the container ID.  For devicemapper it can be gotten from an `inspect` (as the deviceset info is placed there), and I have yet to see how a caller can (easily) associated a container ID with an aufs mount point.

Regardless, I'm testing the fix locally now--have already verified the current behavior (of "dead" mounts causing busy errors on both devicemapper and aufs cleanup) and as soon as my build is done will verify the fix.

**Comment by rhvgoyal** [comment]
@estesp devicemapper used to name everything based on container id. Something has recently changed and I have not looked enough to figure out who changed what.

**Comment by estesp** [comment]
Well, actually, none of the graphdrivers use ID anymore, but it's not their fault :) Based on the (new) layer store code, it now uses a randomly generated `cacheID` as the ID sent to the graphdriver, so that test is now invalid (as of 15 days ago when that implementation came into docker) for all graphdrivers anyway :(  (ping @LK4D4)

Code here: https://github.com/docker/docker/blob/master/layer/layer_store.go#L226-L234

**Comment by estesp** [comment]
code LGTM, testing locally verified fixes the dangling mounts on both devicemapper and aufs.  Open question about whether we can/should fix the test, but that may be a separate PR?

**Comment by liusdu** [comment]
@estesp  Thanks for your testing and reviewing.

**Comment by tiborvass** [comment]
@liusdu if the inspect change is just a nice-to-have that's not helping in fixing the issue this PR was set to fix, I'd leave it out and send another PR specific to that.

**Comment by tiborvass** [comment]
LGTM

**Comment by mYmNeo** [comment]
I think this problem comes back in 1.10.3
```
$ uname -a
Linux thomassong-pc2 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 102
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:6-3540058-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 14.65 GB
 Data Space Total: 95.7 GB
 Data Space Available: 81.05 GB
 Metadata Space Used: 20.69 MB
 Metadata Space Total: 4.295 GB
 Metadata Space Available: 4.274 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56 GiB
Name: thomassong-pc2
ID: AF3J:426M:H674:HOCE:R7JA:FBZY:KOBS:TQMQ:FJGK:KP2F:GEEF:LBTZ
Debug mode (server): true
 File Descriptors: 23
 Goroutines: 40
 System Time: 2016-03-17T16:16:12.50414171+08:00
 EventsListeners: 0
 Init SHA1: 14bbd54b64d2a737269118ce4f1613787e2d0ce8
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```
* Run a container
```
$ docker run -d busybox top
c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56
```
* Kill daemon
```
$ sudo kill -9 $(pidof docker)
```
* Restart daemon
```
$ sudo service docker start
```
I found an error `ERRO[0000] Error unmounting container c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56: not mounted ` in docker.log
* Remove Container
```
docker rm -vf c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56
Failed to remove container (c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56): Error response from daemon: Driver devicemapper failed to remove root filesystem c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56: Device is Busy
```
And I found error message`ERRO[0086] Error removing mounted layer c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56: Device is Busy 
ERRO[0086] Handler for DELETE /v1.22/containers/c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56 returned error: Driver devicemapper failed to remove root filesystem c9cd16f5dcf61542d7d3bd6235dbb45bed0eca0aab50232892f2cf3d30d5ed56: Device is Busy `

**Pull request merged**
