### PR TITLE
Vendoring in libnetwork 22dc04d06067b40a9e7ef575aee6d1bb69d4dcc3

### PR DESCRIPTION
**Pull request by mavenugo**
Notable changes include :
- https://github.com/docker/libnetwork/pull/285 : Fix required for https://github.com/docker/docker/pull/12927
- https://github.com/docker/libnetwork/pull/283 : Code re-architecture/tech-debt in bridge driver
- Upgraded to latest Netlink library
- Fixed certain race-conditions

Most of these changes are component specific and all the Unit-Tests are covered in these individual PRs in libnetwork. No additional Integration-CLI tests required. The existing ones should suffice.

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@mavenugo I wonder why don't you use tags with short changelogs.

**Comment by mavenugo** [comment]
@LK4D4 yes. we could.

as a FYI, we are planning on vendoring in often from libnetwork to help the reviewers with smaller diffs
and also not wait for long & hinder release schedules. If we get to the model of vendoring in often,
then the tags may not have any particular significance and will act as a pure marker, which
am personally okay with.

**Comment by LK4D4** [comment]
@mavenugo I think they're ok as marker.

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
but I expect next update as tag

**Comment by mavenugo** [comment]
sure @LK4D4. its a good idea.

**Pull request merged**
