### PR TITLE
Update 1.12.1 changelog for networking fixes

### PR DESCRIPTION
**Pull request by thaJeztah**
Add https://github.com/docker/docker/pull/25550 to changelog

ping @mrjana PTAL if the description is correct

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM :cat:

**Comment by thaJeztah** [comment]
don't merge yet; let me add https://github.com/docker/docker/pull/25739 to the changelog as well

**Comment by thaJeztah** [comment]
Added https://github.com/docker/docker/pull/25739, but not sure if "Fixes a SNAT issue in loadbalancer when multiple networks are involved" also has to be mentioned. @mrjana if you have suggestion let me know

**Comment by mrjana** [comment]
LGTM. No need to add "Fixes a SNAT issue in loadbalancer when multiple networks are involved" because it was a regression introduced in 1.12.1-rc1 so I think we are good.

**Comment by thaJeztah** [comment]
cool, thanks @mrjana 

docs CI is green, so we can merge 

author LGTM

**Comment by tiborvass** [comment]
#25844

**Pull request merged**
