### PR TITLE
Cherry pick from 14243

### PR DESCRIPTION
**Pull request by moxiegirl**
Cherry-pick https://github.com/docker/docker/pull/14243.

Signed-off-by: Mary Anthony mary@docker.com
(cherry picked from commit 078b23a37daf95101bf31bafc7f8396af7ad7d98)

Conflicts:
    daemon/graphdriver/devmapper/README.md
    docs/reference/commandline/daemon.md

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
LGTM

**Comment by moxiegirl** [comment]
Author LGTM.  Substansive review on original context.

**Comment by thaJeztah** [comment]
I'll merge, ignoring the Windows build, these are only docs changes

**Pull request merged**
