### PR TITLE
Clean up explanation of doc branches.

### PR DESCRIPTION
**Pull request by psftw**
Added a table with links and simplified some of the wording.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM - really, I'd love to get rid of the `docs` branch and use the `release` branch :)

**Comment by psftw** [comment]
What spawned this was the ambiguity in the original version.  There are currently `docs` and `release` branches that are both pointing to the same commit.  I don't mind updating `doc` to `release` in this PR if that's the process that will be followed and `doc` will be deprecated (and force-push killed for good measure?).

**Comment by SvenDowideit** [comment]
that would be my preference, but at this point, team meta isn't comfortable with docs updates being cherry-picked into the `release` branch outside of their releases.

lets merge this, and then discuss the branching when I'm in SF for the first week of March :)

@fredlf @jamtur01

**Comment by fredlf** [comment]
LGTM

**Pull request merged**
