### PR TITLE
Add a README to the client's package…

### LINKED ISSUE #26450: Docs: Add README.md to docker/client
Since the Docker API client and types have been moved form [docker/engine-api](https://github.com/docker/engine-api) to the main docker repo [docker/client](https://github.com/docker/docker/tree/master/client), no README.md with a simple usage example is available anymore.
It would be helpful to add a simple README.md file with at least the same usage example from the old [README.md](https://github.com/docker/engine-api/tree/6c72c24563a7a266e91c8445811f74f138973457).
I'll be glad to send a PR for this.

### PR DESCRIPTION
**Pull request by vdemeester**
… taken from the old engine-api project. 🐯

Closes #26450 👼

/cc @icecrime @thaJeztah @SvenDowideit 

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @LK4D4 Looks like we've got a swarm deadlock here.

**Comment by cpuguy83** [comment]
stack trace from the daemon: https://gist.github.com/cpuguy83/c373497ef0c52cbf53b8fcde752e8751

**Comment by cpuguy83** [comment]
Oh wait, sorry I saw the 'context deadline exceeded' and went straight to swarm, may not be swarm.

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by mstanleyjones** [comment]
Should this be cherry-picked to 1.12x?

**Comment by thaJeztah** [comment]
@mstanleyjones no, no need to, it's only a README, so only visible on GitHub (and relates to code changes for 1.13)

**Pull request merged**
