### PR TITLE
Remove Steve Francia from maintainers.

### PR DESCRIPTION
**Pull request by calavera**
@crosbymichael do you mind to verify that this is correct. Please, feel free to close it if it's not.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
If the role no longer exists, shouldn't these tasks/responsibilities be re-assigned to another role? I think at least some of them are still relevant

**Comment by jfrazelle** [comment]
it's weird though because we have lived so long without them being done by one person :p but more by all maintainers as a whole

**Comment by cpuguy83** [comment]
There still ought to be a single owner, whether or not multiple people do the work is an implementation detail :)

**Comment by jfrazelle** [comment]
okk should we move these tasks to under core maintainers , then can we move this along

**Comment by thaJeztah** [comment]
Or to the "operators" role? Given that it were tasks for "chief operator"; idk

**Comment by jfrazelle** [comment]
ya but the operators are more specific roles, unless we add it to one in particular

**Comment by thaJeztah** [comment]
hm yes. maintainers sgtm then, we can always move them :+1:

**Pull request merged**
