### PR TITLE
Don’t hold container lock for size calculation

### LINKED ISSUE #31158: `system df` and `ps --size` block all other `ps` requests
While a size for a single container is being calculated for `docker system df` or `docker ps --size` the main container lock is blocked. This means that no other `docker ps` request returns until the size calculation has been finished. In the case of big images/containers and slow drivers(devicemapper) the wait time can be >30s.

related #30225

cc @mlaventure

### PR DESCRIPTION
**Pull request by tonistiigi**
- fixes #31158

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Review by LK4D4 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by trapier** [comment]
Somewhat the opposite of an expert in these matters, but what are the chances of failure to stop or remove containers due to "device is busy" due to a size calculation in progress?

**Comment by tonistiigi** [comment]
@trapier Layerstore has an internal reference counter for every layer. So when container is deleted in  https://github.com/docker/docker/blob/91cffdbedb89e6164fe2ceca3d68ec039c1acc34/daemon/delete.go#L131 that function wouldn't actually delete the layer but only lower the reference count. When the size calculation completes and last reference is released the data is actually cleaned up.

**Pull request merged**
