### PR TITLE
ci: update buildkit to fix integration tests

### PR DESCRIPTION
**Pull request by crazy-max**
full diff: https://github.com/moby/buildkit/compare/d77361423c88cc2a0d19e285ec3599022e92571f...3a391492c9d0b7428b6dcaa18c5aa3b5951fdacd

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by crazy-max** [comment]
https://github.com/moby/moby/actions/runs/3876968182/jobs/6611490483#step:9:6107

```
    sandbox.go:238: Illegal instruction (core dumped)
    sandbox.go:238: Illegal instruction (core dumped)
```

Hum we still have the issue :thinking:

**Comment by crazy-max** [comment]
It sill fetches `busybox:latest`: https://github.com/moby/moby/actions/runs/3876968182/jobs/6611490483#step:9:3142

```
sandbox.go:238: time="2023-01-09T19:33:31.812422400Z" level=debug msg="do request" host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=buildkit/0.0.0+unknown request.method=HEAD url="https://registry-1.docker.io/v2/library/busybox/manifests/latest"
    sandbox.go:238: time="2023-01-09T19:33:32.062748922Z" level=debug msg="fetch response received" host=registry-1.docker.io response.header.content-length=158 response.header.content-type=application/json response.header.date="Mon, 09 Jan 2023 19:33:32 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=13.83.10.160 response.header.strict-transport-security="max-age=31536000" response.header.www-authenticate="***"[https://auth.docker.io/token\](https://auth.docker.io/token/)",service=\"registry.docker.io\",scope=\"repository:library/busybox:pull\"" response.status="401 Unauthorized" url="https://registry-1.docker.io/v2/library/busybox/manifests/latest"
    sandbox.go:238: time="2023-01-09T19:33:32.062838124Z" level=debug msg=Unauthorized header="***"[https://auth.docker.io/token\](https://auth.docker.io/token/)",service=\"registry.docker.io\",scope=\"repository:library/busybox:pull\"" host=registry-1.docker.io
    sandbox.go:238: time="2023-01-09T19:33:32.065687188Z" level=debug msg="do request" host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=buildkit/0.0.0+unknown request.method=HEAD url="https://registry-1.docker.io/v2/library/busybox/manifests/latest"
    sandbox.go:238: time="2023-01-09T19:33:32.426294187Z" level=debug msg="fetch response received" host=registry-1.docker.io response.header.content-length=2295 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Mon, 09 Jan 2023 19:33:32 GMT" response.header.docker-content-digest="sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c" response.header.docker-distribution-api-version=registry/2.0 response.header.docker-ratelimit-source=13.83.10.160 response.header.etag="\"sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c\"" response.header.strict-transport-security="max-age=31536000" response.status="200 OK" url="https://registry-1.docker.io/v2/library/busybox/manifests/latest"
```

**Comment by crazy-max** [comment]
As discussed with @tonistiigi we don't use buildkitd here but dockerd so we need to update dockerd config to set up the registry mirror to make this works.

**Review by thaJeztah — APPROVED** [review]
still LGTM

**Pull request merged**
