### PR TITLE
Update docs for enableipv6

### LINKED ISSUE #20455: Complete network options information table
As a follow up of #17513, we should complete the network options table:

https://github.com/aidanhs/docker/blob/d736a9d2c3758fcc4eac0b62e9c7b128388021c1/docs/reference/commandline/network_create.md#bridge-driver-options

/cc @aidanhs

### PR DESCRIPTION
**Pull request by aidanhs**
Completes the ipv6 docs. Followup to #17513, fixes #20455. Ping @mavenugo @calavera @thaJeztah @vdemeester 
- What did you do? - Added docs.
- How did you do it? - Wrote them.
- How do I see it or verify it? - Read them.
- A picture of a cute animal (not mandatory but encouraged) - http://imgur.com/dzTqf

### CODE REVIEW

**Comment by thaJeztah** [comment]
Yay, bonus-points granted for the cute animal image!

**Comment by calavera** [comment]
LGTM

**Comment by mavenugo** [comment]
Thanks @aidanhs . LGTM

**Comment by vdemeester** [comment]
LGTM 🐶

**Pull request merged**
