### PR TITLE
[1.13.x] Add support for dns and dns_search in deploy using composefile

### PR DESCRIPTION
**Pull request by vdemeester**
Related to #29685.

The changes is small but this would need a change in `anaand/compose-file` and needs vendoring. If we are ok to do this in 1.13.x I will make a PR in `anaand/compose-file` and update this PR. I will also make a PR against master afterwards.

/cc @thaJeztah @dnephin @icecrime 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by thaJeztah** [comment]
design LGTM, but not sure we can still take this for 1.13.0

**Comment by dnephin** [comment]
I don't think we should make this change for 1.13

**Comment by vdemeester** [comment]
Sounds fair 👼 
I'll close that and add support on master a little bit later 😝

**Comment by seriousben** [comment]
I created https://github.com/docker/docker/pull/32059 for the same bug. Would be nice to get this bug fixed soon.

**Pull request closed without merging**
