### PR TITLE
added documentation for functions

### LINKED ISSUE #11592: pkg/networkfs/etchosts - Document exported functions and types
**Problem**
 
pkg/networkfs/etchosts - Document exported functions and types
 
**Solution**
 
The `pkg/networkfs/etchosts` package is used for `/etc/hosts` file manipulation in Docker networking code. It is meant to be reused by other applications, however it lacks documentation.
 
Add a README.md to the package, and code comments to the package's exported symbols.

### PR DESCRIPTION
**Pull request by jasonrichardsmith**
Fixes #11592

Added function documentation for /etc/hosts

Signed-off-by: Jason Smith jasonrichardsmith@gmail.com

### CODE REVIEW

**Comment by estesp** [comment]
Due to the `pkg/networkfs` rework from another PR, this needs a rebase.  Should be straightforward as the file didn't change, just its location!

**Comment by ehazlett** [comment]
@jasonrichardsmith were you able to get this rebased?  do you need any help?

**Comment by icecrime** [comment]
Thanks @jasonrichardsmith! I'm going to carry this for the rebase (which means you'll still get credit for the original change).

**Comment by icecrime** [comment]
Closed by #12428.

**Pull request closed without merging**
