### PR TITLE
Support for beginning of time --since in event

### LINKED ISSUE #11555: events --since"Beginning of Unix Time doesn't work"
```bash
[aanm@localhost ~]$ sudo docker events --since='1970-01-01' --until='2015-03-22 03:15'
[aanm@localhost ~]$ sudo docker events --since='1970-01-02' --until='2015-03-22 03:15'
2015-03-22T03:14:01.000000000Z 0b1fc3ce7efcac2984c00e3e822c19036bcf6d2f0c63d451246ab0cd2b198682: (from docker:10501-Docker-events-docs-not-accordingly-with-rfc3339) create
2015-03-22T03:14:01.000000000Z 0b1fc3ce7efcac2984c00e3e822c19036bcf6d2f0c63d451246ab0cd2b198682: (from docker:10501-Docker-events-docs-not-accordingly-with-rfc3339) start
2015-03-22T03:14:42.000000000Z 0b1fc3ce7efcac2984c00e3e822c19036bcf6d2f0c63d451246ab0cd2b198682: (from docker:10501-Docker-events-docs-not-accordingly-with-rfc3339) die
2015-03-22T03:14:52.000000000Z 0b1fc3ce7efcac2984c00e3e822c19036bcf6d2f0c63d451246ab0cd2b198682: (from docker:10501-Docker-events-docs-not-accordingly-with-rfc3339) destro
```

I believe the fault is this line, why is this particular line there? https://github.com/docker/docker/blob/master/events/events.go#L72

### PR DESCRIPTION
**Pull request by agtorre**
Fixes #11555. This is part of the docker
second birthday courtesy of Seattle.

Signed-off-by: Aaron Torres tcboox@gmail.com

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
LGTM

**Comment by duglin** [comment]
Dup of https://github.com/docker/docker/issues/11736  ?

**Comment by duglin** [comment]
Dup of https://github.com/docker/docker/pull/11571 ?

**Comment by agtorre** [comment]
It looks like it is a dupe unfortunately.

**Comment by icecrime** [comment]
Sorry for this @agtorre :-( We're gonna go with #11571 for the extra catch and test implementation.

**Pull request closed without merging**
