### PR TITLE
Various code-cleanup

### PR DESCRIPTION
**Pull request by thaJeztah**
Remove unnescessary import aliases, brackets, and so on.

started doing this manually (found some unneeded import aliases), but GoLand did a better job (and found quite a few more)

### CODE REVIEW

**Review by dnephin — APPROVED** [review]

**Comment by thaJeztah** [comment]
```
09:06:11 Step 1/93 : FROM golang:1.10.2 AS base
09:06:22 Get https://registry-1.docker.io/v2/library/golang/manifests/1.10.2: Get https://auth.docker.io/token?account=dockerbuildbot&scope=repository%3Alibrary%2Fgolang%3Apull&service=registry.docker.io: net/http: TLS handshake timeout
09:06:22 Unable to find image 'docker-s390x:0db7e5f' locally
09:06:23 docker: Error response from daemon: pull access denied for docker-s390x, repository does not exist or may require 'docker login'.

**Review by vdemeester — APPROVED** [review]
LGTM :frog:

**Comment by thaJeztah** [comment]
Janky https://jenkins.dockerproject.org/job/Docker-PRs/49519/console failing on a flaky (https://github.com/moby/moby/issues/33041)

```
09:42:18 FAIL: docker_cli_swarm_test.go:1372: DockerSwarmSuite.TestSwarmClusterRotateUnlockKey
09:42:18 
09:42:18 [ddffae60d0f75] waiting for daemon to start
09:42:18 [ddffae60d0f75] daemon started
09:42:18 
09:42:18 [d7a4b733fd762] waiting for daemon to start
09:42:18 [d7a4b733fd762] daemon started
09:42:18 
09:42:18 [d6ca4f02d7cec] waiting for daemon to start
09:42:18 [d6ca4f02d7cec] daemon started
09:42:18 
09:42:18 [d7a4b733fd762] exiting daemon
09:42:18 [d7a4b733fd762] waiting for daemon to start
09:42:18 [d7a4b733fd762] daemon started
09:42:18 
09:42:18 [d6ca4f02d7cec] exiting daemon
09:42:18 [d6ca4f02d7cec] waiting for daemon to start
09:42:18 [d6ca4f02d7cec] daemon started
09:42:18 
09:42:18 [d7a4b733fd762] exiting daemon
09:42:18 [d7a4b733fd762] waiting for daemon to start
09:42:18 [d7a4b733fd762] daemon started
09:42:18 
09:42:18 [d7a4b733fd762] exiting daemon
09:42:18 [d7a4b733fd762] waiting for daemon to start
09:42:18 [d7a4b733fd762] daemon started
09:42:18 
09:42:18 [d6ca4f02d7cec] exiting daemon
09:42:18 [d6ca4f02d7cec] waiting for daemon to start
09:42:18 [d6ca4f02d7cec] daemon started
09:42:18 
09:42:18 [d7a4b733fd762] exiting daemon
09:42:18 [d7a4b733fd762] waiting for daemon to start
09:42:18 [d7a4b733fd762] daemon started
09:42:18 
09:42:18 [d6ca4f02d7cec] exiting daemon
09:42:18 [d6ca4f02d7cec] waiting for daemon to start
09:42:18 [d6ca4f02d7cec] daemon started
09:42:18 
09:42:18 docker_cli_swarm_test.go:1449:
09:42:18     c.Assert(err, checker.IsNil)
09:42:18 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc42058d260), Stderr:[]uint8(nil)} ("exit status 1")
09:42:18 
09:42:18 [ddffae60d0f75] exiting daemon
09:42:18 [d7a4b733fd762] exiting daemon
09:42:18 [d6ca4f02d7cec] exiting daemon
```

z (s390x) https://jenkins.dockerproject.org/job/Docker-PRs-s390x/9858/console also failing on a flaky (https://github.com/moby/moby/issues/32673)


```
09:12:34 FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
09:12:34 
09:12:34 [db906a0aa2267] waiting for daemon to start
09:12:34 [db906a0aa2267] daemon started
09:12:34 
09:12:34 [d2f3b3474d897] waiting for daemon to start
09:12:34 [d2f3b3474d897] daemon started
09:12:34 
09:12:34 [dc0a5aafd3997] waiting for daemon to start
09:12:34 [dc0a5aafd3997] daemon started
09:12:34 
09:12:34 [db906a0aa2267] exiting daemon
09:12:34 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
09:12:34 [d2f3b3474d897] exiting daemon
09:12:34 [dc0a5aafd3997] exiting daemon
09:12:55 
```

**Review by arm64b — APPROVED** [review]

**Comment by arm64b** [comment]
I found that the `TestAPIServiceUpdatePort` and `TestSwarmPublishDuplicatePorts` failed with very high frequency in `janky` node 💢

**Comment by thaJeztah** [comment]
Yes, those are very flaky currenty; https://github.com/moby/moby/issues/36501

**Pull request merged**
