### PR TITLE
fix deb packaging systemd files

### LINKED ISSUE #14995: Systemd units missing from 1.8.0-rc1 packages for Vivid and Wily
It seems like the systemd units that were part of the Ubuntu packages (>= 15.04), `/lib/systemd/system/docker.socket` and `/lib/systemd/system/docker.service`, are missing from the just released 1.8.0-rc1 packages, as found on http://apt.dockerproject.org.

### PR DESCRIPTION
**Pull request by jessfraz**
fix #14995

### CODE REVIEW

**Comment by tianon** [comment]
Gah good catch, LGTM

**Comment by thaJeztah** [comment]
@tianon I think @eolamey really gets all the credits here!  Perhaps we should send out MobyDock plushies :+1:

**Comment by eolamey** [comment]
Hahaha, actually, you all deserve credits :) Less than 30 minutes from bug report to fix, on a saturday... <3

**Comment by jfrazelle** [comment]
ping @calavera to cherry-pick into release branch

**Comment by calavera** [comment]
cherry-picked

**Pull request merged**
