### PR TITLE
don't use underscores in Go names

### PR DESCRIPTION
**Pull request by yu8833**
Signed-off-by: yupengzte <yupeng36@zte.com.cn>

**- What I did**
var _dataConfig_schema_v30Json change into _dataConfigSchemaV30Json
func dataConfig_schema_v30JsonBytes change into dataConfigSchemaV30JsonBytes
func dataConfig_schema_v30Json change into dataConfigSchemaV30Json

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
```
// Code generated by go-bindata.
// sources:
// data/config_schema_v3.0.json
// DO NOT EDIT!
```

**Comment by YuPengZTE** [comment]
@AkihiroSuda , thanks.

I think that cli/compose/schema/bindata.go  is to generate new data with data/config_schema_v3.0.json.
The code of cli/compose/schema/bindata.go is not generated by go-bindata.
"DO NOT EDIT!" means “DO NOT CHANGE THE DATA OF LINE 71”.

Is my understanding correct?

**Comment by AkihiroSuda** [comment]
no
https://github.com/jteeuwen/go-bindata/blob/a0ff2567cfb70903282db057e799fd826784d41d/convert.go#L71

**Comment by YuPengZTE** [comment]
@AkihiroSuda ,OK, thanks.
Close this PR.

**Pull request closed without merging**
