### PR TITLE
Windows: fix various npipe bugs

### PR DESCRIPTION
**Pull request by jstarks**
The Windows npipe transport had a few issues:
1. Container stdin was not getting closed when the docker client was done. This was because the hijack code relies on CloseWrite() to signal the termination of the pipe, but this was not supported in go-winio's implementation of the npipe transport.
2. Npipe performance on go 1.6 was terrible. This was because go 1.6 regressed syscall performance in some scenarios. A workaround is necessary to fall back to the go 1.5.3 behavior. See golang/go#14790.
3. Npipe performance was limited by the small amount of buffering done in the named pipe.

This PR fixes all three of these issues by revendoring go-winio and updating the way we configure the named pipe.

tired

cc/@jhowardmsft

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM. @calavera - this also fixes the golang 1.6 perf issue mentioned the other day. This is one we're going to need for 1.11

**Comment by thaJeztah** [comment]
ping @runcom @unclejack @vdemeester - Europe PTAL :heart:

**Comment by vdemeester** [comment]
LGTM 🐶

**Comment by calavera** [comment]
LGTM

**Pull request merged**
