### PR TITLE
zsh: remove Vincent Bernat from reviewers for ZSH completion

### PR DESCRIPTION
**Pull request by vincentbernat**
There have been some pretty invasive changes and I am not comfortable anymore to be considered as a reviewer for the current code.

### CODE REVIEW

**Comment by icecrime** [comment]
@vdemeester Did we make a mistake with some past merge? I'd rather discuss this than LGTM this PR :crying_cat_face:

**Comment by vdemeester** [comment]
@icecrime you probably meant @vincentbernat, didn't you ? but yeah that's sad :sob:.

**Comment by jfrazelle** [comment]
can we change it to make it better

**Comment by jfrazelle** [comment]
it honestly helps us a lot to have more maintainers, the project sees over 100 pull requests per week, so I am very sorry if one got through that was not good, we are trying our hardest but we could really use your help to make sure it doesnt happen again.

**Comment by vincentbernat** [comment]
It is just reflecting the reality: I don't review most changes. I am not quitting on contributing in this area and I am likely to push some PR in the future. I don't think that a contributed completion plugin is worth any kind of drama.

And, just for the record, there was no bad commit, just a messy one. Most changes in it made sense. I absolutely don't want to belittle others' work because I have different expectations.

**Comment by thaJeztah** [comment]
> It is just reflecting the reality: I don't review most changes.

I think this is where "we" went wrong here. Given the large number of pull-requests in this repository, we cannot expect you to check (on a daily basis) if changes are made to the zsh completion scripts. I *try* to ping relevant people whenever I see a PR in specific areas but, looking at the history of those file(s), I missed a number of PR's and you were not involved in the reviewing because of that.

Would you still be interested / able to assist in reviewing if we more consistently pinged/involved you in reviewing?

**Comment by vincentbernat** [comment]
I will still be happy to do reviews if pinged.

**Comment by icecrime** [comment]
Thanks :+1:

**Comment by thaJeztah** [comment]
Thanks, Vincent. Sad to see this merged, but understandable!

**Pull request merged**
