### PR TITLE
Un-fork coreos/etcd - bump to v3.2.1

### PR DESCRIPTION
**Pull request by thaJeztah**
Commit 077f08bf54dc89d382cbcbd797b2bd7c4867151d temporarily switch etcd to a fork, pending a pull-request to be merged, and a new release of etcd that contains the change.

The pull request was merged, and included in etcd v3.2.0

This patch bumps etcd to v3.2.1, which contains some bug-fixes on top of v3.2.0

Follow-up to https://github.com/docker/swarmkit/pull/2296

ping @aaronlehmann @tonistiigi PTAL

### CODE REVIEW

**Comment by tonistiigi** [comment]
@thaJeztah It seems some dependencies have changed and need to be updated in `vendor.conf` as well.

**Comment by thaJeztah** [comment]
Thanks for the ping; yes, I expected more would be needed 😅

**Comment by aaronlehmann** [comment]
Looks like the dependency comes from `etcd/client`, not `etcd/raft`. This is why it didn't come up when vendoring this version of etcd into swarmkit.

**Comment by thaJeztah** [comment]
Ah, yes, I was indeed looking at SwarmKit yesterday, and scratching my head why it wasn't vendored there. I'll try to look at this again today; got held up on other things 😅

**Comment by aaronlehmann** [comment]
I've pushed a commit that adds the go-semver dependency.

**Review by thaJeztah — COMMENTED** [review]
oh thanks! LGTM, if green

**Comment by thaJeztah** [comment]
All green now ping @aaronlehmann @tonistiigi PTAL

**Review by justincormack — APPROVED** [review]

**Pull request merged**
