### PR TITLE
Windows: OCI runtime spec compliance

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This removes the hacked version of the runtime spec which has been used on Windows since the libcontainerd introduction/removal of the exec driver model.

This revendors the runtime-spec to 1c7c27d043c2a5e513a44084d2b10d77d1402b8c (no, there is no tag for this currently) - it will be in a post `v1.0.0-rc1` version, in the first commit. The second commit is all the compile fixups necessary to remove the `windowsoci` package and point everything to `runtime-specs/specs-go` instead.

@mlaventure @tonistiigi.

(This replaces https://github.com/docker/docker/pull/26832)

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@thaJeztah It would be really good if this one could get moved forward :smile: Thanks!

**Comment by thaJeztah** [comment]
ping @mlaventure @crosbymichael PTAL!

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
