### PR TITLE
Add containerd static compile

### LINKED ISSUE #35349: containerd binaries no longer static
Looks like the switch to containerd 1.0 https://github.com/moby/moby/pull/34895 did not add static builds for the containerd binaries; static binaries are used for the official docker images, so we should have those again :smile:

```
docker:
	not a dynamic executable
docker-containerd:
	linux-vdso.so.1 (0x00007ffca46f6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f091b912000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f091b70e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f091b36f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f091bb2f000)
docker-containerd-ctr:
	linux-vdso.so.1 (0x00007ffc59db2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0683623000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f068341f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0683080000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0683840000)
docker-containerd-shim:
	linux-vdso.so.1 (0x00007fff7e1ec000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7121aca000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f71218c6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7121527000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7121ce7000)
docker-init:
	not a dynamic executable
docker-proxy:
	not a dynamic executable
docker-runc:
	not a dynamic executable
dockerd:
	not a dynamic executable
```

ping @crosbymichael @mlaventure

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #35349

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Review by tianon — APPROVED** [review]
Nice :+1:

**Review by justincormack — APPROVED** [review]

**Comment by seemethere** [comment]
In the process of confirming this fixes our issues with static binaries for Docker CE

**Comment by thaJeztah** [comment]
```
18:03:46 ---> Making bundle: .integration-daemon-setup (in bundles/test-integration)
18:03:46 ---> Making bundle: .ensure-emptyfs (in bundles/test-integration)
18:03:46 Error: No such image: emptyfs
18:03:46 Running integration-test (iteration 1)
18:03:46 Running /go/src/github.com/docker/docker/integration/container
18:04:02 Loaded image: s390x/buildpack-deps:jessie
18:04:03 Loaded image: s390x/busybox:latest
18:04:04 error loading frozen images: ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
```

not sure what this issue is on s390x @tophj-ibm ?

**Review by seemethere — APPROVED** [review]
LGTM, can confirm this works for static binaries.

<details>
<summary> Console output </summary>

```
vagrant@ubuntu-artful:/vagrant/docker$ docker version
Client:
 Version:      test_containerd_static
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   1dc89aa9
 Built:        Tue Oct 31 18:02:24 2017
 OS/Arch:      linux/amd64

Server:
 Version:      test_containerd_static
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   007db062f
 Built:        Tue Oct 31 18:02:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
vagrant@ubuntu-artful:/vagrant/docker$ docker run --rm hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

</details>

**Comment by tophj-ibm** [comment]
@thaJeztah I don't know, but it only happens on certain nodes. I messaged the z folks about it yesterday but they haven't figured it out yet. All I can do is remove it from the pool as I don't have access to those machines, and I can't replicate it on my z-vms.

**Comment by thaJeztah** [comment]
Let me roll the 🎲 and see if it lands on another node

**Comment by yongtang** [comment]
All tests passed 🎲 🙌

**Pull request merged**
