### PR TITLE
TestDaemonNoSpaceLeftOnDeviceError: Adjust to snapshotters

### PR DESCRIPTION
**Pull request by vvoland**
**- What I did**
Made `TestDaemonNoSpaceLeftOnDeviceError` pass with containerd integration enabled.

**- How I did it**
- Pass empty containerd socket which forces the daemon to create a new supervised containerd. Otherwise a global containerd daemon will be used and the pulled image data will be stored in its data directory, instead of the the newly specified `data-root` that has a limited storage capacity.

- Don't try to use `vfs` snapshotter, instead use `native` which is containerd's equivalent for `vfs`.

**- How to verify it**
```diff
$ make TEST_FILTER=TestDaemonNoSpaceLeftOnDeviceError TEST_IGNORE_CGROUP_CHECK=1 DOCKER_GRAPHDRIVER=overlayfs TEST_INTEGRATION_USE_SNAPSHOTTER=1 \
    test-integration
-=== FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonNoSpaceLeftOnDeviceError (4.11s)
-    docker_cli_daemon_test.go:1641: assertion failed: expression is false: strings.Contains(pullOut, "no space left on device")
-    check_test.go:589: [d39a69b3940cb] daemon is not started
-    --- FAIL: TestDockerDaemonSuite/TestDaemonNoSpaceLeftOnDeviceError (4.11s)
+=== RUN   TestDockerDaemonSuite/TestDaemonNoSpaceLeftOnDeviceError
+    check_test.go:589: [d17531973e45d] daemon is not started
+--- PASS: TestDockerDaemonSuite (7.14s)
+    --- PASS: TestDockerDaemonSuite/TestDaemonNoSpaceLeftOnDeviceError (7.14s)
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by rumpl — APPROVED** [review]

**Comment by thaJeztah** [comment]
CI failure looks unrelated, but wondering why it fails 🤔

```
=== FAIL: amd64.integration-cli TestDockerHubPullSuite/TestPullNonExistingImage (2.79s)
    docker_cli_pull_test.go:120: assertion failed: expression is false: strings.Contains(record.out, fmt.Sprintf("pull access denied for %s, repository does not exist or may require 'docker login'", record.e.repo)): expected image not found error messages
    --- FAIL: TestDockerHubPullSuite/TestPullNonExistingImage (2.79s)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vvoland** [comment]
The failure is caused by Hub randomly returning 500 when requesting an auth token for a non-existing registry. Already reported it and should be fixed soon.

**Comment by thaJeztah** [comment]
saw the thread on our slack; thanks for raising it! <3

**Pull request merged**
