### PR TITLE
Bump libnetwork to fix panic on concurrent read/write to a map

### PR DESCRIPTION
**Pull request by cpuguy83**
Full diff
https://github.com/docker/libnetwork/compare/5c1218c956c99f3365711974e300087810c31379...c15b372ef22125880d378167dde44f4b134e1a77

Fixes ##36814 -- panic on concurrent read/write to a map.

Changes included:

- https://github.com/docker/libnetwork/pull/2124 Allow for larger preset property values, do not override
- https://github.com/docker/libnetwork/pull/2136 networkdb: Use write lock in handleNodeEvent

### CODE REVIEW

**Comment by yongtang** [comment]
@cpuguy83 Title `libcontainerd` -> `libnetwork`?

**Comment by cpuguy83** [comment]
lol yes.

**Comment by cpuguy83** [comment]
Fixed the commit message.

**Review by yongtang — APPROVED** [review]
LGTM, Thanks!

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Pull request merged**
