### PR TITLE
remove description of Google Docs Folder in GOVERNANCE.md

### PR DESCRIPTION
**Pull request by lixiaobing1**
the url "https://goo.gl/Alfj8r" is already invalid, so remove the description.

### CODE REVIEW

**Comment by vdemeester** [comment]
@lixiaobing10051267 it's definitely still valid url (and I see the folders there)

**Comment by thaJeztah** [comment]
It still works for me as well, and redirects to https://drive.google.com/drive/folders/0B4016P0_3PSqQ3YzYmtFc3JfVlk as full URL. Perhaps we should change to the non-short URL instead?

**Comment by lixiaobing10051267** [comment]
oh, for me, I can't access both "https://goo.gl/Alfj8r" and "https://drive.google.com/drive/folders/0B4016P0_3PSqQ3YzYmtFc3JfVlk", but I can access "www.google.com", is it my authorization problem?

**Comment by thaJeztah** [comment]
I tried in an "incognito" window, so it's not an authorisation problem. Possibly the GFW playing a role?

**Comment by lixiaobing10051267** [comment]
ok.

**Pull request closed without merging**
