### PR TITLE
Fix panic when meminfo couldn't be read

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes panic reported by @abronan in https://github.com/docker/docker/pull/24516#issuecomment-232125090

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Comment by aaronlehmann** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Comment by vdemeester** [comment]
Ah experimental hitting https://github.com/docker/docker/issues/23401
Merging anyway…

**Pull request merged**
