### PR TITLE
Remove *_solaris.go files

### PR DESCRIPTION
**Pull request by tklauser**
**- What I did**

Removed two leftover `*_solaris.go` files missed in PR #35373.

**- How I did it**

`git rm ./pkg/parsers/kernel/uname_solaris.go ./pkg/system/stat_solaris.go`

**- How to verify it**

`find -name *_solaris.*` should only yield results in `vendor/`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Pied kingfisher

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
ping @kolyshkin ptal

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
This docker-py test probably should be skipped as "flaky"

```
[2019-09-02T08:40:15.796Z] =================================== FAILURES ===================================
[2019-09-02T08:40:15.796Z] __________________ AttachContainerTest.test_attach_no_stream ___________________
[2019-09-02T08:40:15.796Z] tests/integration/api_container_test.py:1250: in test_attach_no_stream
[2019-09-02T08:40:15.796Z]     assert output == 'hello\n'.encode(encoding='ascii')
[2019-09-02T08:40:15.796Z] E   AssertionError: assert b'' == b'hello\n'
[2019-09-02T08:40:15.796Z] E     Right contains more items, first extra item: 104
[2019-09-02T08:40:15.796Z] E     Use -v to get the full diff
[2019-09-02T08:40:15.796Z] ------- generated xml file: /src/bundles/test-docker-py/junit-report.xml -------
[2019-09-02T08:40:15.796Z] =========================== short test summary info ============================
```

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
