### PR TITLE
pkg/devicemapper: external device activation

### PR DESCRIPTION
**Pull request by vbatts**
cc @rhvgoyal @yasker

Reported-by: Sheng Yang shend.yang@rancher.com
Signed-off-by: Vincent Batts vbatts@redhat.com

### CODE REVIEW

**Comment by yasker** [comment]
Hi @rhvgoyal,

This is a feature that device-mapper supported, to create external snapshot based on a image. The document can be find at: https://github.com/torvalds/linux/blob/master/Documentation/device-mapper/thin-provisioning.txt#L229

I am using pkg/device-mapper for https://github.com/rancherio/volmgr , which has ability to create a volume from an shared read-only base image, as well as take snapshot of it and backup/restore the snapshot. Currently volmgr is backed by device mapper only, and I used go binding of docker to implement all the features. I created an separate patch for pkg/device-mapper in my own tree, at https://github.com/yasker/docker/commit/f06dc8e9e10ff654e41dddae93a15a2a99e5ebc0 , but hopeful the feature can make it upstream.

I met @vbatts yesterday at Dockercon, and talked with him about it. And thanks @vbatts for this patch!

I've tested it and it works well with volmgr(rancher-volume).

Probably we can eliminate one "if" by using trim for the trailing space? Or does it matter at all for API?

**Comment by rhvgoyal** [comment]
Ok, got it.

I did not know that devicemapper package is being used external to docker as well. Now this is interesting. Changing anything in that package has potential to break other dependent applications. Is this common practice or just an exception for device mapper. IOW, is docker expecting this?

**Comment by yasker** [comment]
@rhvgoyal 

I've talked with @crosbymichael and @jlhawn , they're fine with the approach. In fact I think Docker is encouraging using the code outside of docker now.

Also this change is pretty minimal, and no API change for docker at all. Shouldn't have much impact on docker.

**Comment by vbatts** [comment]
Also this doesn't break existing api. Only adds a function.

**Comment by rhvgoyal** [comment]
LGTM

**Comment by yasker** [comment]
Not sure why test failed.

**Comment by LK4D4** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
