### PR TITLE
The DHE documentation will not be published with 1.5.0

### PR DESCRIPTION
**Pull request by SvenDowideit**
more timeline based churn - these problems will be removed when we re-develop the non-docker-engine docs tooling.

@fredlf @jamtur01 

Signed-off-by: Sven Dowideit SvenDowideit@home.org.au

### CODE REVIEW

**Comment by jfrazelle** [comment]
the suits :smiling_imp:

**Comment by fredlf** [comment]
LGTM

**Comment by SvenDowideit** [comment]
@jamtur01

**Comment by fredlf** [comment]
It's your PR, so we can merge. And will. :-)

**Pull request merged**
