### PR TITLE
Add a test to make sure that --tlsverify=false turns on tls in daemon

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
ping @tiborvass

**Comment by tiborvass** [comment]
Thank you very much! LGTM

**Comment by icecrime** [comment]
That's 1.8.0 right?

**Comment by tiborvass** [comment]
This is just a test, so doesn't impact code. Not a problem if cherry-picked, but wouldn't call it necessary.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
