### PR TITLE
Fix panic on error looking up volume driver

### PR DESCRIPTION
**Pull request by cpuguy83**
Signed-off-by: Brian Goff <cpuguy83@gmail.com>

**- What I did**

```
............................................________ 
....................................,.-'"...................``~., 
.............................,.-"..................................."-., 
.........................,/...............................................":, 
.....................,?......................................................, 
.................../...........................................................,} 
................./......................................................,:`^`..} 
.............../...................................................,:"........./ 
..............?.....__.........................................:`.........../ 
............./__.(....."~-,_..............................,:`........../ 
.........../(_...."~,_........"~,_....................,:`........_/ 
..........{.._$;_......"=,_......."-,_.......,.-~-,},.~";/....} 
...........((.....*~_......."=-._......";,,./`..../"............../ 
...,,,___.`~,......"~.,....................`.....}............../ 
............(....`=-,,.......`........................(......;_,,-" 
............/.`~,......`-...................................../ 
.............`~.*-,.....................................|,./.....,__ 
,,_..........}.>-._...................................|..............`=~-, 
.....`=~-,__......`,................................. 
...................`=~-,,.,............................... 
................................`:,,...........................`..............__ 
.....................................`=-,...................,%`>--==`` 
........................................_..........._,-%.......` 
..................................., 
```

**- How I did it**
http://www.asciifacepalm.com/
**- How to verify it**

**- Description for the changelog**
(－‸ლ)

**- A picture of a cute animal (not mandatory but encouraged)**

download

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
is this issue in a release already?

**Comment by cpuguy83** [comment]
Yes, though likely uncommon.

**Pull request merged**
