### PR TITLE
seccomp: Support PKU in docker by default

### LINKED ISSUE #43481: Can we support PKU in docker by default? (`pkey_mprotect(2), pkey_alloc(2), pkey_free(2)`)
## Description

**PKU** (Protection Keys for Userspace) (aka. **MPK**: Memory Protection Keys) has been introduced into Linux since 2015 (details can be found in the [lwn page](https://lwn.net/Articles/643797/)). It provides lightweight and flexible thread-level permission control. Application can leverage such hardware feature to enforce their robustness.

The related syscalls in Linux are shown below (More details can be found in [man page](https://man7.org/linux/man-pages/man7/pkeys.7.html)):
- `pkey_alloc()`
- `pkey_mprotect()`
- `pkey_free()`

These syscalls are invoked by applications for address space configuration. **But** we discover that the default `seccomp` profile (can be found [here](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json)) has not added these syscall to the whitlist, which makes their invocation failed.
If we want to use PKU in docker, we can use our customized profile by `--secomp-profile` flag, which is redundant to developer. Another choice is to add `--privileged` flag in `docker run` command, which may bring other security issues.

**Our question is**:
Can we add **PKU** related syscalls to the white list in the default `seccomp` profile?
Similar to `mprotect()`, these syscalls can only configure its own virtual memory in a process, and they brings no extral security issues as far as I know.
If we cannot added them to whitelist, why?

## Steps to reproduce the issue:
1. Here is the sample code in `test.c`:
```
#define _GNU_SOURCE
#include <stdio.h>
#include <sys/mman.h>

int main() {
    int pkey = pkey_alloc(0, 0);
    if (pkey < 0) {
        printf("pkey_alloc() return error: %d\n", pkey);
        perror("Cannot invoke pkey_alloc()");
    } else {
        printf("Successfully alloc pkey, pkey=%d\n", pkey);
        pkey_free(pkey);
    }
    return 0;
}
```
1. Compile it, copy it to the docker and run:
```
$ gcc -o test test.c
$ docker run -it -v ${PWD}:/root/test_pku ubuntu:18.04 
$ /root/test_pku/test
```
3. Then get the output

## Describe the results you received:
The results show that `pkey_alloc()` failed:
```
pkey_alloc() return error: -1
Cannot invoke pkey_alloc(): Operation not permitted
```

## Describe the results you expected:
The output should be as same as that in native Linux:
```
Successfully alloc pkey, pkey=1
```

## Additional information you deem important:
These test must be performed on the particular hardware and kernel which support **PKU**.
We can use `lscpu | grep pku` to detect whether our machine support **PKU**.

## Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 74
  Running: 21
  Paused: 0
  Stopped: 53
 Images: 468
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-27-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 188.4GiB
 Name: xxx
 ID: xxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: xxx
 HTTPS Proxy: xxx
 No Proxy: localhost,127.0.0.1,xxx
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
Note: I change some sentitive information to `xxx`

## Additional environment details (AWS, VirtualBox, physical, etc.):
None

### PR DESCRIPTION
**Pull request by Bonjourz**
Closes #43481 

Add `pkey_alloc(2)`, `pkey_free(2)` and `pkey_mprotect(2)` in seccomp default profile.
Similar to  `mprotect()`, `pkey_alloc(2)`, `pkey_free(2)` and `pkey_mprotect(2)` can only configure its own memory of the process, so they are existing "safe for everyone" syscalls.

Such syscalls were added  to Linux in kernel 4.9
More details can be found in the [man page](https://man7.org/linux/man-pages/man7/pkeys.7.html)

- What I did
I add `pkey_alloc()`, pkey_free()` and `pkey_mprotect()` into the default syscall's white list.

- How I did it
Modify `profiles/seccomp/default.json` and `profiles/seccomp/default_linux.go`, append `pkey_alloc()`, pkey_free()` and pkey_mprotect()` to the default syscall list.

- How to verify it

  Here is the sample code (test.c):
    ```
    #define _GNU_SOURCE
    #include <stdlib.h>
    #include <stdio.h>
    #include <sys/mman.h>
    #define BUF_SIZE    (0x1000)
    int main() {
        int ret = -1, pkey = -1;
        ret = pkey_alloc(0, 0);
        if (ret < 0) {
            perror("Cannot invoke pkey_alloc() successfully");
            exit(-1);
        } else {
            pkey = ret;
            char *buf = (char *)mmap(NULL, BUF_SIZE, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
            if (buf == MAP_FAILED) {
                perror("Cannot invoke mmap() successfully");
                exit(-1);
            }
            ret = pkey_mprotect(buf, BUF_SIZE, PROT_READ | PROT_WRITE, pkey);
            if (ret < 0) {
                perror("Cannot invoke pkey_mprotect() successfully");
                exit(-1);
            }
            ret = munmap(buf, BUF_SIZE);
            if (ret < 0) {
                perror("Cannot invoke munmap() successfully");
                exit(-1);
            }
            ret = pkey_free(pkey);
            if (ret < 0) {
                perror("Cannot invoke pkey_free() successfully");
                exit(-1);
            }
        }
        printf("PKU related syscalls are allowed in container environment!\n");
        return 0;
    }
    ```

    Compile it first:
    ```
    gcc -o test test.c
    ```
    
    ```
    docker run -it -v ${PWD}:/root/test --security-opt seccomp=${PWD}/profiles/seccomp/default.json ubuntu::20.04
    ```
    
    Run `test` in docker:
    ```
    /root/test/test
    ```
    
    and will get the output:
    ```
    PKU related syscalls are allowed in container environment!
    ```

- Description for the changelog
`profiles/seccomp/default.json` and `profiles/seccomp/default_linux.go`: Add `pkey_alloc()`, `pkey_free()` and `pkey_mprotect()` to the default white list.

- A picture of a cute animal (not mandatory but encouraged)

### CODE REVIEW

**Comment by tianon** [comment]
cc @justincormack

**Comment by cpuguy83** [comment]
This seems like it would be ok.
I would say this paragraph seems a bit ambiguous to me if the limit is per process.

       To use the pkeys feature, the processor must support it, and the
       kernel must contain support for the feature on a given processor.
       As of early 2016 only future Intel x86 processors are supported,
       and this hardware supports 16 protection keys in each process.
       However, pkey 0 is used as the default key, so a maximum of 15
       are available for actual application use.

If it is indeed per process this seems OK.
That said you can change the default seccomp profile of a daemon  by setting the `--secomp-profile` flag on dockerd.

**Comment by Bonjourz** [comment]
Hi @cpuguy83 , can you provide more details to show which statement confuse you?
As mentioned in https://github.com/moby/moby/pull/43490#issue-1205226981, `pkey_alloc()`, `pkey_free()` and `pkey_mprotect()` can only takes effect on its process's own memory, they do nothing with other processes.


You also mentioned:
> That said you can change the default seccomp profile of a daemon by setting the --secomp-profile flag on dockerd.

Add `--seccomp` works for us, but such solution is seems not to be elegant, since developer may need to update legacy command in some production environments. My propose is to support `pkey_alloc()`, `pkey_free()` and `pkey_mprotect()` syscalls  in seccomp default profile, similar to `mprotect()`.

**Comment by Bonjourz** [comment]
Hi, is there anyone help me review this PR? Thanks for your time!

**Review by justincormack — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Pull request merged**
