### PR TITLE
Run imageservice.Cleanup() also before daemon start

### PR DESCRIPTION
**Pull request by olljanat**
**- What I did**
Added image cleanup for Windows which run just before Docker daemon start.

**- How to verify it**
- Create folder under *C:\ProgramData\docker\windowsfilter* which contains suffix *-removing*
- Start dockerd on debug mode and look that you see messages like these:
```
time="2018-12-20T14:56:46.714139100+01:00" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"
time="2018-12-20T14:56:46.728139900+01:00" level=info msg="Windows default isolation mode: process"
time="2018-12-20T14:56:46.728139900+01:00" level=debug msg="Stackdump - waiting signal at Global\\docker-daemon-2652"
time="2018-12-20T14:56:46.728139900+01:00" level=debug msg="Using default logging driver json-file"
time="2018-12-20T14:56:46.728139900+01:00" level=debug msg="[graphdriver] trying provided driver: windowsfilter"
time="2018-12-20T14:56:46.728139900+01:00" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\docker\\windowsfilter"
time="2018-12-20T14:56:46.729139000+01:00" level=debug msg="Initialized graph driver windowsfilter"
time="2018-12-20T14:56:46.907151800+01:00" level=debug msg="Max Concurrent Downloads: 3"
time="2018-12-20T14:56:46.907151800+01:00" level=debug msg="Max Concurrent Uploads: 5"
time="2018-12-20T14:56:46.909157500+01:00" level=debug msg="hcsshim::DestroyLayer path C:\\ProgramData\\docker\\windowsfilter\\ff12aee57608aa51015d317f49f1d795a334920b732d7be91e26fc9c2407e279-removing"
time="2018-12-20T14:56:47.101257900+01:00" level=debug msg="hcsshim::DestroyLayer succeeded path=C:\\ProgramData\\docker\\windowsfilter\\ff12aee57608aa51015d317f49f1d795a334920b732d7be91e26fc9c2407e279-removing"
time="2018-12-20T14:56:47.101257900+01:00" level=info msg="Cleaned up ff12aee57608aa51015d317f49f1d795a334920b732d7be91e26fc9c2407e279-removing"
time="2018-12-20T14:56:47.101257900+01:00" level=info msg="Loading containers: start."
```

Partly solves docker/for-win#745

Layers which misses *-removing* suffix still need to be find using https://github.com/jhowardmsft/docker-leak-check or https://gist.github.com/olljanat/340b4033eb24d8d33ec75f2c3c3b6b3d

### CODE REVIEW

**Comment by thaJeztah** [comment]
@johnstep @jhowardmsft PTAL

**Comment by olljanat** [comment]
Derek add label: rebuild/janky

**Comment by thaJeztah** [comment]
@cpuguy83 as well 😅

**Comment by cpuguy83** [comment]
Perhaps instead we can run whatever cleanup is necessary on driver init instead.
Note that other drivers have similar logic, such as: https://github.com/moby/moby/blob/92b34ec9c6a6be8c1b5751b1572b6293c7708423/daemon/graphdriver/aufs/aufs.go#L149-L167

**Comment by olljanat** [comment]
Good idea but looks that *windowsfilter* even contain **Init** function with capital **I** like Linux drivers looks to do.

So this will then need more work to get Windows use similar driver initialization logic.

**Comment by olljanat** [comment]
Derek add label: rebuild/powerpc

**Comment by olljanat** [comment]
Derek remove label: platform/windows

**Comment by olljanat** [comment]
> Perhaps instead we can run whatever cleanup is necessary on driver init instead.

@cpuguy83 actually I noticed that same problem can occur with any platform and with any graph driver when there is enough data which is waiting for delete or when running on slower platform like ARM so 15 second shutdown timeout is not enough for cleanup.

That why I now moved global Cleanup() to run just before daemon start instead of on daemon shutdown. WDYT is this OK way to handle this?

**Comment by olljanat** [comment]
Derek add label: rebuild/janky

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by olljanat** [comment]
Derek add label: rebuild/powerpc

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by olljanat** [comment]
@jhowardmsft btw. Can you tell your thoughts about this one? It looks to be needed by all our Windows containers hosts.

**Comment by jhowardmsft** [comment]
I don't have a particularly strong opinion about whether to do this in the graphdriver init, or via the `daemon.imageservice.Cleanup()` code (which enumerates through all layer stores - remember there may be multiple with LCOW) and calls into the appropriate graphdrivers cleanup code. I think it's simpler though doing this at startup as per this change.

The one downside to this approach is it potentially could be a significant amount of time between starting the daemon and it being available to respond to API requests. (I can see at least on internal large-scale use case which might start causing them timeouts). Extending the timeout on shutdown might also be problematic, especially when running as a Windows service under SCM as that has a time limit itself before SCM will shoot dockerd.exe regardless. On balance, I would say the approach in this PR seems sane and keeps the call-sites as-is.

**Comment by thaJeztah** [comment]
> The one downside to this approach is it potentially could be a significant amount of time between starting the daemon and it being available to respond to API requests.

Should we run it both on shutdown and startup? 

Also, if it takes a considerable amount of time; we should make sure that it's properly logged (to inform users what the time is spent on)

**Comment by olljanat** [comment]
> Should we run it both on shutdown and startup?

Sure we can. For all graphdrivers like it now or just for Windows like it is earlier?

> Also, if it takes a considerable amount of time; we should make sure that it's properly logged (to inform users what the time is spent on)

Sure, info message when cleanup is started and ended?

**Comment by jhowardmsft** [comment]
@olljanay could you update? Would be good to hit 1903 cutoff. Thx.

**Comment by olljanat** [comment]
@jhowardmsft sure but I didn't got any response yet to these questions so I'm not sure how this should be updated.

@thaJeztah PTAL these:
> Should we run it both on shutdown and startup?

Sure we can. For all graphdrivers like it now or just for Windows like it is earlier?

> Also, if it takes a considerable amount of time; we should make sure that it's properly logged (to inform users what the time is spent on)

Sure, info message when cleanup is started and ended?

**Comment by thaJeztah** [comment]
> For all graphdrivers like it now or just for Windows like it is earlier?

We should probably do the same on all platforms. If cleaning up during shutdown at least cleans _some_ things cleaned up during shutdown, that'll still be a benefit

@cpuguy83 @jhowardmsft wdyt?

> Sure, info message when cleanup is started and ended?

Yes, perhaps similar to what we had for the "migration to content-addressable store" (removed in https://github.com/moby/moby/pull/38265), and include how long it took (`took %.2f seconds`); or would that be too much information?

**Comment by cpuguy83** [comment]
We should still run cleanup on shutdown, we don't want mounts and other resources to be left behind on shutdown if it can be helped.

Should also be very careful about running `Cleanup()` as such because there may be assumptions in the graph drivers about when `Cleanup()` is called.

e.g., what about live restore?

**Comment by olljanat** [comment]
> We should probably do the same on all platforms. If cleaning up during shutdown at least cleans _some_ things cleaned up during shutdown, that'll still be a benefit

Ok. So now cleanup is running on both startup and shutdown for all the platforms.

> Yes, perhaps similar to what we had for the "migration to content-addressable store" (removed in #38265), and include how long it took (`took %.2f seconds`); or would that be too much information?

Added logging with duration.

> Should also be very careful about running `Cleanup()` as such because there may be assumptions in the graph drivers about when `Cleanup()` is called.
> 
> e.g., what about live restore?

Now cleanup on startup will only run if live restore is not enabled as it is not supported by Windows anyway so it does not matter.

@thaJeztah @cpuguy83 PTAL

**Comment by olljanat** [comment]
Those build failures looks related but I don't fully understand how it works:
```
23:22:00 Running /go/src/github.com/docker/docker/integration/plugin/graphdriver
23:22:01 INFO: Testing against a local daemon
23:22:01 === RUN   TestExternalGraphDriver
23:22:02 === RUN   TestExternalGraphDriver/json
23:22:04 === RUN   TestExternalGraphDriver/spec
23:22:05 === RUN   TestExternalGraphDriver/pull
23:22:08 --- FAIL: TestExternalGraphDriver (7.53s)
23:22:08     external_test.go:57: Creating a new daemon
23:22:08     daemon.go:288: [dd90bb4e22fda] waiting for daemon to start
23:22:08     daemon.go:320: [dd90bb4e22fda] daemon started
23:22:08     daemon.go:275: [dd90bb4e22fda] exiting daemon
23:22:08     daemon.go:288: [dd90bb4e22fda] waiting for daemon to start
23:22:08     daemon.go:320: [dd90bb4e22fda] daemon started
23:22:08     daemon.go:275: [dd90bb4e22fda] exiting daemon
23:22:08     --- FAIL: TestExternalGraphDriver/json (1.71s)
23:22:08         external_test.go:381: assertion failed: 4 (ec[ext].cleanups int) != 2 (int)
23:22:08     daemon.go:288: [dd90bb4e22fda] waiting for daemon to start
23:22:08     daemon.go:320: [dd90bb4e22fda] daemon started
23:22:08     daemon.go:275: [dd90bb4e22fda] exiting daemon
23:22:08     daemon.go:288: [dd90bb4e22fda] waiting for daemon to start
23:22:08     daemon.go:320: [dd90bb4e22fda] daemon started
23:22:08     daemon.go:275: [dd90bb4e22fda] exiting daemon
23:22:08     --- FAIL: TestExternalGraphDriver/spec (1.68s)
23:22:08         external_test.go:381: assertion failed: 4 (ec[ext].cleanups int) != 2 (int)
```

is it actually listening number of messages coming back from Cleanup() and fails because there is now also those info messages?

**Comment by thaJeztah** [comment]
@olljanat could you rebase this one? See if we can get this moving again 🤗

**Comment by thaJeztah** [comment]
ping @vikramhh @ddebroy PTAL

**Comment by vikramhh** [comment]
@olleolleolle - just asking for my own understanding of the problem:

1. Would it be feasible to cleanup at a more regular/predictable cadence [using goroutines etc.]? In production systems where cleanup may run infrequently, we could possibly be carrying a large debt of orphaned layers to cleanup. Trying to see if we can avoid situations where cleanup needs long time to run.

2. Why do the orphaned layers arise in the first place and what could we do to prevent it.

**Comment by olljanat** [comment]
@vikramhh 
1. On Windows that probably would be option but about Linux I'm not sure as I have not investigated very deeply what all those graph drivers do on Cleanup() function.

2. Orphan layers is not problem on Linux because Docker is running using *root* access rights which is highest permissions level on system and it always have permissions to remove any file or folder it want. No matter if those are used by other processes.

However on Windows Docker is running using *NT AUTHORITY\SYSTEM* access rights which only have permissions to do operations which are not prevented by NTFS file system.

Unfortunately only way certainly unlock those files is reboot Windows. I think that everyone who have been working longer time with Windows Servers have noticed that it just easiest to have scheduled reboots on those often enough (we use once of week on most of the servers) and actually Docker makes that simpler as we can just have multiple hosts to running copy of same container so application(s) can stay up even during host machine reboots.

**Pull request closed without merging**
