### PR TITLE
add Evan Hazlett to maintainers

### PR DESCRIPTION
**Pull request by thaJeztah**
Adding @ehazlett to maintainers 🎉 👍 

ping @docker/core-engine-maintainers

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
self-five :) Jenkins is not testing this file

**Comment by ehazlett** [comment]
yay thanks! :tada:

**Comment by vdemeester** [comment]
🎉

**Pull request merged**
