### PR TITLE
Fix issue where TmpfsOptions are not sent to swarm

### LINKED ISSUE #29070: [1.13] Tmpfs options not working for services
While discussing https://github.com/docker/docker/issues/26714, it was reported that tmpfs options are not working for services.

https://github.com/docker/docker/pull/26837 added these options to the "Mount" type, https://github.com/docker/docker/pull/26833 changed the service API to use these types, and https://github.com/docker/docker/pull/28150 added tmpfs specific options (for docker run)

It looks like something was not wired through, though;

Running this on https://github.com/docker/docker/commit/45ed6a75795918d466054e63c462a1a8b553c8c0 (https://github.com/docker/docker/pull/28150)

    docker service create --name test --mount type=tmpfs,target=/foo,tmpfs-size=4194304 nginx:alpine

The container has;

`HostConfig`:

  "Tmpfs": {
      "/foo": ""
  },

`Mounts`:

    "Mounts": [],

Running from https://github.com/docker/docker/commit/821aeb6a6f72f070ae045cb7813759cbbaba7bda (https://github.com/docker/docker/pull/26833)

    docker service create --name test --mount type=tmpfs,target=/foo,tmpfs-size=4194304 nginx:alpine

The container has;

`HostConfig`:

    "Tmpfs": {
        "/foo": ""
    },
    "Mounts": [
        {
            "Type": "tmpfs",
            "Target": "/foo"
        }
    ]

`Mounts`:

    "Mounts": [
        {
            "Type": "tmpfs",
            "Source": "",
            "Destination": "/foo",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        }
    ],

Running on master (a756c1ac659468bb8d6ec9ee2e1182fc6cae4002)

    docker service create --name test --mount type=tmpfs,target=/foo,tmpfs-size=4194304 nginx:alpine

This request is sent (looks good);

```json
{
  "EndpointSpec": {},
  "Mode": {
    "Replicated": {}
  },
  "Name": "test",
  "TaskTemplate": {
    "ContainerSpec": {
      "DNSConfig": {},
      "Image": "nginx:alpine",
      "Mounts": [
        {
          "Target": "/foo",
          "TmpfsOptions": {
            "SizeBytes": 4194304
          },
          "Type": "tmpfs"
        }
      ]
    },
    "ForceUpdate": 0,
    "Placement": {},
    "Resources": {
      "Limits": {},
      "Reservations": {}
    },
    "RestartPolicy": {}
  },
  "UpdateConfig": {
    "FailureAction": "pause",
    "MaxFailureRatio": 0,
    "Parallelism": 1
  }
}
```

However, `docker service inspect` does not show that;

```JSON
[
    {
        "ID": "oao6qenv51cdid1y7ookqe5ql",
        "Version": {
            "Index": 11
        },
        "CreatedAt": "2016-12-02T13:22:29.706211456Z",
        "UpdatedAt": "2016-12-02T13:22:29.706211456Z",
        "Spec": {
            "Name": "test",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:alpine@sha256:aee97412fee873bd3d8fc2331b80862d7bd58913f7b12740cae8515edc1a66e4",
                    "Mounts": [
                        {
                            "Type": "tmpfs",
                            "Target": "/foo"
                        }
                    ],
                    "DNSConfig": {}
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "MaxFailureRatio": 0
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]
```

And the backing container also doesn't show;

```JSON
[
    {
        "Id": "65d6a139685f0467194bb7ac3a2c404f42595d0285522a425c3ed9916435d02b",
        "Created": "2016-12-02T13:22:38.009036877Z",
        "Path": "nginx",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 561,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-12-02T13:22:38.958195446Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:d964ab5d0abe650e824c6b5fdfdf33df306ca6d4d59b1f9ca2c494324d6d37f3",
        "ResolvConfPath": "/var/lib/docker/containers/65d6a139685f0467194bb7ac3a2c404f42595d0285522a425c3ed9916435d02b/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/65d6a139685f0467194bb7ac3a2c404f42595d0285522a425c3ed9916435d02b/hostname",
        "HostsPath": "/var/lib/docker/containers/65d6a139685f0467194bb7ac3a2c404f42595d0285522a425c3ed9916435d02b/hosts",
        "LogPath": "/var/lib/docker/containers/65d6a139685f0467194bb7ac3a2c404f42595d0285522a425c3ed9916435d02b/65d6a139685f0467194bb7ac3a2c404f42595d0285522a425c3ed9916435d02b-json.log",
        "Name": "/test.1.nv0cc9h0rxz4n6kep9ar0fwon",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "tmpfs",
                    "Target": "/foo"
                }
            ]
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Type": "tmpfs",
                "Source": "",
                "Destination": "/foo",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "65d6a139685f",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.11.6"
            ],
            "Cmd": [
                "nginx",
                "-g",
                "daemon off;"
            ],
            "ArgsEscaped": true,
            "Image": "nginx@sha256:aee97412fee873bd3d8fc2331b80862d7bd58913f7b12740cae8515edc1a66e4",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.swarm.node.id": "nu0ip7usli91dikmeclsum063",
                "com.docker.swarm.service.id": "oao6qenv51cdid1y7ookqe5ql",
                "com.docker.swarm.service.name": "test",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "nv0cc9h0rxz4n6kep9ar0fwon",
                "com.docker.swarm.task.name": "test.1.nv0cc9h0rxz4n6kep9ar0fwon"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a35107b0b1cbf27f63669328d5c8ca3bccedeac7d9dc0ec8a43af10f1fc14522",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "443/tcp": null,
                "80/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/a35107b0b1cb",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "c6c4250db69a4516e5e23aa4567e5fbfaa640ff6e8d16505008bf3b1933e6592",
            "Gateway": "172.18.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.18.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:12:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "29ebdfc034bf747d22b4b5bf19149c2a3bfb8f177de46c7d53c923a6a791b2f7",
                    "EndpointID": "c6c4250db69a4516e5e23aa4567e5fbfaa640ff6e8d16505008bf3b1933e6592",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02"
                }
            }
        }
    }
]
```

Note that on 1.13.0-rc2, this works (`--mount` is still present on `docker run`, but removed in https://github.com/docker/docker/pull/28838);

    docker run -dit --rm --mount type=tmpfs,target=/foo,tmpfs-size=1m busybox

`HostConfig.Mounts`:

```
"Mounts": [
    {
        "Type": "tmpfs",
        "Target": "/foo",
        "TmpfsOptions": {
            "SizeBytes": 1048576
        }
    }
]
```

`Mounts`:

```
"Mounts": [
    {
        "Type": "tmpfs",
        "Source": "",
        "Destination": "/foo",
        "Mode": "",
        "RW": true,
        "Propagation": ""
    }
],
```

So, it looks like there's an issue in SwarmKit, or integration of SwarmKit into docker

/cc @cpuguy83 @AkihiroSuda

### PR DESCRIPTION
**Pull request by cpuguy83**
ping @thaJeztah @AkihiroSuda 

Fixes #29070

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @cpuguy83 !

**Comment by AkihiroSuda** [comment]
Thank you!

**Pull request merged**
