### PR TITLE
Rename graph drivers to storage drivers

### PR DESCRIPTION
**Pull request by samoht**
**\- What I did**

I've renamed the occurrences of `GraphDriver` by `StorageDriver` in the code base to be more consistent with the [docs](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/).

The only externally-visible change of that PR is a direct API translation of the [experimental storage driver plugins API](https://github.com/docker/docker/blob/master/experimental/plugins_graphdriver.md)

**\- How I did it**

I've renamed things via grep/replace but I tried to do that carefully, so variable names and comments are also kept consistent.

**\- How to verify it**

I've run `make` and `make test` and it seems to work. I need to update https://github.com/docker/go-plugins-helpers/pull/42 to use the new StorageDriver naming scheme, I'll do that once/if that PR is merged.

I've tried to run the integration tests for the CLI. The experimental storage driver plugins seem broken (see below).

**\- A picture of a cute animal (not mandatory but encouraged)**

cute camel

### CODE REVIEW

**Comment by samoht** [comment]
Hum I seem to have broken the integration-cli tests for experimental storage drivers. I'll investigate that next week:

```
----------------------------------------------------------------------
14:16:58 FAIL: docker_cli_external_storage_driver_unix_test.go:340: DockerExternalStorageDriverSuite.TestExternalStorageDriver
14:16:58 
14:16:58 [d51499870] waiting for daemon to start
14:16:58 [d51499870] exiting daemon
14:16:58 docker_cli_external_storage_driver_unix_test.go:341:
14:16:58     s.testExternalStorageDriver("test-external-storage-driver", "spec", c)
14:16:58 docker_cli_external_storage_driver_unix_test.go:348:
14:16:58     c.Assert(err, check.IsNil, check.Commentf("\n%s", string(b)))
14:16:58 ... value *errors.errorString = &errors.errorString{s:"[d51499870] Daemon exited during startup"} ("[d51499870] Daemon exited during startup")
14:16:58 ... 
14:16:58 time="2016-04-23T14:16:58Z" level=warning msg="Running experimental build" 
14:16:58 time="2016-04-23T14:16:58.364985085Z" level=debug msg="docker group found. gid: 999" 
14:16:58 time="2016-04-23T14:16:58.365020773Z" level=debug msg="Listener created for HTTP on unix (/go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/d51499870/docker.sock)" 
14:16:58 time="2016-04-23T14:16:58.366134145Z" level=debug msg="Using default logging driver json-file" 
14:16:58 time="2016-04-23T14:16:58.366173315Z" level=debug msg="Golang's threads limit set to 114570" 
14:16:58 time="2016-04-23T14:16:58.367042471Z" level=debug msg="containerd connection state change: READY" 
14:16:58 time="2016-04-23T14:16:58.367453406Z" level=debug msg="received past containerd event: &types.Event{Type:\"live\", Id:\"\", Status:0x0, Pid:\"\", Timestamp:0x571b83da}" 
14:16:58 time="2016-04-23T14:16:58.419219301Z" level=debug msg="[storage] trying provided driver \"test-external-storage-driver\"" 
14:16:58 time="2016-04-23T14:16:58.419982126Z" level=error msg="Failed to GetDriver storage test-external-storage-driver /go/src/github.com/docker/docker/bundles/1.12.0-dev/test-integration-cli/d51499870/root" 
14:16:58 time="2016-04-23T14:16:58.420009911Z" level=debug msg="Cleaning up old mountid : start." 
14:16:58 time="2016-04-23T14:16:58.420061568Z" level=fatal msg="Error starting daemon: error initializing storage: driver not supported" 
14:16:58 
```

**Comment by thaJeztah** [comment]
ping @samoht have you had time to look into those failing tests?

**Comment by samoht** [comment]
I plan to look at that again in the following days. Do you think that renaming is worth continuing?

**Comment by thaJeztah** [comment]
Hm, not sure, I know @tiborvass proposed doing so in the past, but not sure if it's really important (well, it's more consistent probably)

**Comment by samoht** [comment]
ok, so I'll rebase and see what I can do with the failing tests.

**Comment by thaJeztah** [comment]
ok! We discussed this, and we like it, so moving to code review. Would be nice if we could give the graph driver plugin maintainers a notice :)

**Comment by cpuguy83** [comment]
ping @kolyshkin

**Comment by samoht** [comment]
I think I've fixed the `docker_cli_external_storage_driver_unix_test` issue.

Normally, all my changes are not visible from the user, apart the changes to the experimental storage driver plugins. The remaining bits where `GraphDriver` still appears are:
- in [docker/engine-api](https://github.com/docker/engine-api/blob/009426d98aa84d199210a897dbb60bfee541877d/types/types.go#L131)
- and in `docker inspect`

I don't plan to change theses. Next step for me is to update https://github.com/docker/go-plugins-helpers/pull/42

**Comment by kolyshkin** [comment]
LGTM

**Comment by samoht** [comment]
A interesting new error for `wind2lin`:
```
19:22:28 + git clone https://github.com/docker/notary.git /tmp/tmp.vCngyuJWWd/src/github.com/docker/notary
19:22:28 Cloning into '/tmp/tmp.vCngyuJWWd/src/github.com/docker/notary'...
19:32:30 error: RPC failed; result=56, HTTP code = 200
19:32:30 fatal: The remote end hung up unexpectedly
19:32:30 fatal: early EOF
19:32:30 fatal: index-pack failed
```

For TP5, I'm not sure where this comes from...
```
17:42:03 ---> Making bundle: .ensure-frozen-images-windows (in bundles/1.12.0-dev/test-integration-cli)
17:42:03 ERROR: Could not find windowsservercore images
```

**Comment by tiborvass** [comment]
LGTM

**Comment by samoht** [comment]
Rebased on master, and got new funky errors (yay):

```
23:14:23 docker: Error response from daemon: devmapper: Error mounting '/dev/mapper/docker-202:1-75497728-1220c22c26ac33994ddca2ef67a0e6d2abb2f46ef1b6069e92e32469063ddd87-init' on '/var/lib/docker/devicemapper/mnt/1220c22c26ac33994ddca2ef67a0e6d2abb2f46ef1b6069e92e32469063ddd87-init': no space left on device.
```

**Comment by samoht** [comment]
Still an issue with TP5: 

```
ERROR: Could not find windowsservercore images
```

Is that something expected?

**Comment by thaJeztah** [comment]
Restarted the Windows build, doesn't look like its related

**Comment by thaJeztah** [comment]
oh boy; this needs a rebase now

**Comment by thaJeztah** [comment]
let me close this for now, because it's carried in https://github.com/docker/docker/issues/23237, but we still need to figure out the Windows issue :cry:

**Pull request closed without merging**
