### PR TITLE
[1.13.x] Vendor libnetwork, netlink and libkv

### PR DESCRIPTION
**Pull request by aboch**
This brings to the release branch the content of #28562, #28681 and #28673

### CODE REVIEW

**Comment by mavenugo** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by mavenugo** [comment]
The windowsRS1 CI seems to be stuck. Given that this is a cherry-pick from master, I dont see a problem in merging this while the CI is not turning green. 
WDYT @tiborvass @vieux @jhowardmsft ?

**Comment by jhowardmsft** [comment]
It will run. Soon.

**Comment by jhowardmsft** [comment]
Actually - looks like it really is stuck somewhere in Jenkins. It's just not actually getting scheduled on a node. No idea why. I thought it was in the queue, but it's not. But yes, agree with @mavenugo 

LGTM.

**Pull request merged**
