### PR TITLE
integration: download busybox-w32 from GitHub Release

### LINKED ISSUE #44298: Workflows for testing on Microsoft Windows
### Description

I see that moby uses [busybox-w32](https://github.com/rmyorston/busybox-w32) to perform tests on Microsoft Windows. Downloads of the required busybox-w32 binaries from my [website](https://frippery.org/files/busybox) have increased substantially over the past few months. They now account for over 75% of download bandwidth, with most of that occurring between 10:00-11:00 UTC when the windows-2019 workflow is scheduled to run.

Some suggestions:
- Don't ship the windows-2019 workflow with the scheduled run enabled. Although GitHub ask users to understand the consequences of enabling workflows I'm sure many don't realise that windows-2019 will be run every day.
- Review the workflows to determine if it's really necessary to download busybox-w32 fourteen times on every run.
- Bundle the BusyBox binary.
- Use a caching server. The [Julia](https://github.com/JuliaLang/julia) project also uses busybox-w32 for testing. They direct their downloads to a caching server on their own infrastructure, only falling back to my website if that fails.
- Use something other than busybox-w32 to provide Unix-like utilities on Microsoft Windows.

Also, please note that [contrib/busybox/Dockerfile](https://github.com/moby/moby/blob/master/contrib/busybox/Dockerfile) is configured to use version FRP-3329-gcf0fa4d13 of busybox-w32. This is now the oldest binary on the website. It will be removed when it turns three years old on 9th January 2023. Switching to a more recent version before then is recommended.

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #44298

**- What I did**

Download busybox-w32 through ~a docker image~ GitHub Release to avoid making too much requests to https://frippery.org/files/busybox.

**- How I did it**

Published GitHub Release with busybox-w32 binaries: https://github.com/moby/busybox/releases/tag/FRP-3329-gcf0fa4d13

Didn't updated to latest `FRP-4716-g31467ddfc` as it seems there are some issues with it: #44000

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by crazy-max** [comment]
Argh guess we need a proper Windows base image after all: https://github.com/moby/moby/actions/runs/3249933557/jobs/5333050380#step:11:33

```
Step 4/14 : FROM crazymax/busybox-w32:${BUSYBOX_VERSION} AS busybox
FRP-3329-gcf0fa4d13: Pulling from crazymax/busybox-w32
9e578c36694c: Pulling fs layer
9e578c36694c: Download complete
failed to register layer: re-exec error: exit status 1: output: hcsshim::ProcessBaseLayer \\?\C:\Users\runneradmin\AppData\Local\Temp\moby-root\windowsfilter\89dfa268f77584818e42f740f9e113dc477c6735c2e31aebac56b1e159ead111: The system cannot find the path specified.
```

So instead we might just build and push https://github.com/moby/moby/blob/master/contrib/busybox/Dockerfile in our pipeline. Maybe ghcr would be enough for this?

**Comment by tianon** [comment]
I don't have a problem with this approach (to be clear), but a few alternative ideas:

- since the compressed downloads are relatively small, we could commit them directly to a new Git repo
- we could make a new Git repo that includes a mirror of the downloads as GitHub Releases artifacts
- we could make an S3 bucket that we mirror downloads into

(For any of these, I imagine we'd only go through the effort for versions we actually use, but if we were to automate it to make sure the "muscle is exercised" so to speak, that'd be fine too for all but my first option :sweat_smile:)

**Comment by neersighted** [comment]
Another alternate approach could be using GHCR + ORAS (I think OCI Artifacts isn't fully baked yet?), but that would require more tooling than the other alternatives.

**Comment by crazy-max** [comment]
As suggested created a GitHub repository https://github.com/crazy-max/busybox-w32 (should be moved to moby org) and pushed binaries to GitHub Release: https://github.com/crazy-max/busybox-w32/releases/tag/FRP-3329-gcf0fa4d13. cc @sam-thibault

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by sam-thibault — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
Opened backports for 20.10 and 22.06;

- https://github.com/moby/moby/pull/44358
- https://github.com/moby/moby/pull/44357

**Pull request merged**
