### PR TITLE
Revendor go-winio to v0.3.7

### PR DESCRIPTION
**Pull request by darstahl**
Revendor go-winio to v0.3.7

/cc @jhowardmsft @jstarks 

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@thaJeztah Another 1.13 - it has the new DLL loading in this change too.

**Comment by jhowardmsft** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vdemeester** [comment]
Ah, already need a rebase :sweat:

**Comment by darrenstahlmsft** [comment]
Rebased.

**Comment by thaJeztah** [comment]
all 💚

**Pull request merged**
