### PR TITLE
Prevent transparent decompression of 'x-gzip' content

### LINKED ISSUE #17595: docker doesn't understand 'x-gzip' encoding and thus fails to pull images
If we have a docker v2 registry service (not distribution but pulp) behind httpd, httpd sends blobs with header specifying "x-gzip". Unfortunately docker engine doesn't understands this and fails to verify the blobs:

http://pastebin.com/SxLLfR9V

Relevant line from /etc/httpd/conf/magic
0       string          \037\213        application/octet-stream        x-gzip

With curl, this works just fine and one can download and verify all blobs.

Version-Release number of selected component (if applicable):

docker-1.9.0-5.git11b81f9.fc24.x86_64

it also fails with 1.8 docker
This is the response from server:

HTTP/1.1 200 OK
Date: Mon, 26 Oct 2015 13:30:22 GMT
Server: Apache/2.2.15 (Red Hat)
Last-Modified: Fri, 23 Oct 2015 12:13:20 GMT
ETag: \"43c38-11736-522c48997e618\"
Accept-Ranges: bytes
Content-Length: 71478
Docker-Distribution-API-Version: registry/2.0
Connection: close
Content-Type: application/x-tar
Content-Encoding: x-gzip

When getting rid of the "x-gzip", docker succeeds to pull the image.

### PR DESCRIPTION
**Pull request by twaugh**
When fetching layer content, we want to ensure that we get back the content as-is with no modification in order to verify its checksum.

Go's http.Transport provides transparent decompression by adding 'x-gzip' to the list of accepted encodings, then decompressing it before returning it to the caller.

This can be turned off using the DisableCompression flag.

Doing so fixes #17595.

To verify this, store V2 API responses on e.g. an Apache httpd web server with default configuration, and try 'docker pull' from it.

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks!

ping @aaronlehmann @stevvooe ptal

**Comment by aaronlehmann** [comment]
Took a look at the linked issue to refresh my memory. In that issue, I said:

> I think it's fundamentally wrong for the HTTP server to be adding this header. It tells the client that the HTTP stream is compressed. In this case, it's not the HTTP stream that's compressed, but the actual payload. The distinction matters a lot.

But I also said:

> It seems like turning on DisableCompression wouldn't hurt. Feel free to submit a PR to do this.

So I guess this looks good to me :)

The tradeoff is that this flag will disable compression in a few cases where it's not harmful, like transparent compression of manifests. I don't think there are any situations where this makes a significant difference, so it seems okay to disable compression since it works around a fairly common misconfiguration.

I'd like to hear what @stevvooe and @dmcgowan think, though.

**Comment by stevvooe** [comment]
Apache HTTPd's behavior here is broken and simply incorrect. It assumes that the client will immediately decompress compressed data, which isn't always true, especially in the case of layers. 

Disabling inline transport compression for _everyone_ because of Apache's configuration isn't right. Note that this can be disabled in the Apache configuration.

If we must, we can probably hide this behind an environment variable.

**Comment by cgwalters** [comment]
But since the layers are already compressed, it's not useful for the webserver to try to compress them again regardless, right?

**Comment by stevvooe** [comment]
> But since the layers are already compressed, it's not useful for the webserver to try to compress them again regardless, right?

No, it is not. It can be useful to compress manifests but I'm not sure about the affect on performance.

My big worry in doing this is that in the future we _do_ need compression but enabling will break misconfigured proxies. Should we take on technical debt due to an inflexible proxy configuration?

Apache's behavior is tampering with content by instructing the client to decompress before it can be verified. I can see if this was from a file on disk, but this is a response, sent over a proxy connection. 

It makes total sense to compress uncompressed content inline but detecting compressed content and then adding a header pretending that transport compression is in use is simply wrong. If the upstream meant to use transport compression, it would set the header itself. The feature should be disabled when proxying registry responses.

__Is there a header we can add to registry responses to disable this behavior in Apache?__

**Comment by RalphCorderoy** [comment]
(AIUI if an explicit Accept-Encoding header is added by net/http's user then net/http doesn't add its own one requesting gzip, and it also stops its unwanted-initiative decompression. If it would be useful, this means the client could still get the benefit of compression if there are any non-compressed resources by adding its own "Accept-Encoding: gzip" rather than setting DisableCompression.)

**Comment by stevvooe** [comment]
@RalphCorderoy Thanks for the pointer!

That led me to find `Accept-Encoding: identity`.

@twaugh @cgwalters Could we set this on requests for layers? Will Apache honor this?

**Comment by cpuguy83** [comment]
ping @twaugh @cgwalters

**Pull request closed without merging**
