### PR TITLE
Correct Lise Meitner's name, add Euler and Noether

### PR DESCRIPTION
**Pull request by janten**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Actually, looks like "meitner" is now in the list twice; https://github.com/docker/docker/pull/17155/files#diff-a461eecf31e5c471572678b08330893aR329. Possibly a bad rebase somewhere.

Can you fix that, and remove the duplicate? Thanks!

Also, we like this list to be balanced and like to have both a [man and woman added in each change](https://github.com/docker/docker/pull/17155/files#diff-a461eecf31e5c471572678b08330893aR329), could you come up with one?

**Comment by janten** [comment]
I've added Emmy Noether, too.

**Comment by thaJeztah** [comment]
Thanks, excellent choice! Oh (apologies, I overlooked that); can you squash your commits? We like to have changes grouped in logical commits; for most PR's that means only a single commit.

If you need help with squashing, please refer to the contribution guide, which contains some examples on that; https://docs.docker.com/project/work-issue/#pull-and-rebase-frequently

LGTM after the commits are squashed

**Comment by estesp** [comment]
LGTM

**Pull request merged**
