### PR TITLE
add environment configs to systemd init file

### LINKED ISSUE #31589: Report: add default environment configs to systemd init file
Description of problem:
default systemd init file do not include environment configs. 

`docker version`:
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb2265
 Built:        Thu Feb 23 10:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb2265
 Built:        Thu Feb 23 10:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

`docker info`:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.03.0-ce
Storage Driver: devicemapper
 Pool Name: docker-8:18-2752568-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.514 GB
 Data Space Total: 107.4 GB
 Data Space Available: 41.75 GB
 Metadata Space Used: 4.018 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.41 GiB
Name: concurrent.work
ID: D25D:FPXH:PDMX:DCVS:SLVC:HXRI:2U6X:FUNC:UI3M:IPXZ:PIOQ:DG2S
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 21
 System Time: 2017-03-07T10:35:15.648413694+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.0.0/16
 127.0.0.0/8
Live Restore Enabled: false

`uname -a`:
Linux concurrent.work 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

thinkpad laptop T450

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:
if someone want to customize docker opts, there will be at least two files need to be changed. 
For my example, using debian,
i want my dockerd use options: 
`DOCKER_OPTS="-D --bip 10.255.255.1/24 --insecure-registry 192.168.0.0/16 -s devicemapper"`

The file  `/etc/default/docker` and `/lib/systemd/system/docker.service` need to be modified.

Expected Results:
i think just change `/etc/default/docker` would be better.

Additional info:

### PR DESCRIPTION
**Pull request by qudongfang**
Signed-off-by: qudongfang <qudongfang@gmail.com>

fixes #31589 

**- What I did**
    add environment configs to systemd init file

**- How I did it**

**- How to verify it**

**- Description for the changelog**
    add environment configs to systemd init file

### CODE REVIEW

**Comment by philips** [comment]
These are CentOS specific files. This should not be merged.

If you want to do this sort of stuff use systemd drop-ins.

I think this PR should be closed.

**Comment by lsm5** [comment]
@qudongfang centos/rhel rpm sources include this already. There's no need to have them here.

**Comment by vdemeester** [comment]
Agreeing with @philips, this should be done in systemd drop-ins or downstream packagers, closing 👼

**Comment by qudongfang** [comment]
i see, thank you guys for the review. i have closed the related issue too.
@philips @lsm5 @vdemeester

**Pull request closed without merging**
