### PR TITLE
Do not overwrite already published deb files when releasing

### PR DESCRIPTION
**Pull request by mlaventure**

### CODE REVIEW

**Comment by mlaventure** [comment]
ping @tianon 

You may have a more elegant way in mind :)

**Comment by tianon** [comment]
Would "cp --no-clobber" be enough?

**Comment by mlaventure** [comment]
I did not not about `--no-clobber`, nice!

But we would also like to keep the original unsigned deb around if possible (hence the extra copy)

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
@tianon can we merge it as-is ? I would like to be able to keep the unsigned debs.

**Comment by tianon** [comment]
Lol sure, LGTM

**Pull request merged**
