### PR TITLE
fixed bug: r.Body did not closed after use

### PR DESCRIPTION
**Pull request by gorilla001**
**r.Body did not closed**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: mgniu mgniu@dataman-inc.com

### CODE REVIEW

**Comment by allencloud** [comment]
Why does request.Body need to Close? @pwnall Could you give us more background?

**Comment by pwnall** [comment]
@allencloud Can you please remind me the context in which I got the knowledge to answer this?

I vaguely remember seeing a bug in Swarm where a missing Close caused  a hang, but I forgot the details.

Thank you!

**Comment by pwzgorilla** [comment]
sorry, my mistake. The Server will close the request body. :)

**Comment by allencloud** [comment]
Oh, @pwnall Really sorry about that. I am afraid your Github ID and the PR author have the same prefix. I think I made a mistake to @ you accidentally.

Back to the question, since I only see `The client must close the response body when finished with it`, while never see request.Body.Close() ever, so hope to share more knowledge about that.

**Pull request closed without merging**
