### PR TITLE
Use bitmask for conflict checking

### PR DESCRIPTION
**Pull request by tonistiigi**
Rather than using 2 different functions for different
types of conflicts use a bitmask to specify what
conflicts need to be checked. This allows a better way
to make exceptions.

depending on: #19266

cc @aaronlehmann 

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
In the places where we check a masking operation against 0, I think it's better to use `!= 0` instead of `> 0`, in case one day we end up using the sign bit for one of the flags. Changing the type from `int` to `uint` would also work around this issue.

**Comment by tonistiigi** [comment]
@aaronlehmann updated

**Comment by jfrazelle** [comment]
sweet LGTM i love `|`

**Comment by aaronlehmann** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
