### PR TITLE
Add '--address-space' option to 'network create' options

### LINKED ISSUE #23076: Add '--address-space' option to 'network create' options

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Closes #23076

Signed-off-by: vikaschoudhary16 choudharyvikas16@gmail.com

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
Cc @mavenugo

**Comment by vikaschoudhary16** [comment]
Hi Folks,
I am new to docker contribution/development workflow. I can see some checks are failing and some are pending. Not sure if I should be worried about these or how to fix them. Any help/support/guidance in moving these changes forward will be much appreciated.

Thanks
Vikas

**Comment by vdemeester** [comment]
@vikaschoudhary16 thanks for the contribution. The `vendor` check is failing because any change in vendor needs to be changed upstream. This mean, in this case, a PR has to be done and merge into libnetwork. It doesn't stop maintainers to review the design and code thoigh :wink:

**Comment by vikaschoudhary16** [comment]
@vdemeester ,
Many thanks for response. So the changes in vendor need not to be pushed in this repo? Rather only in libnetwork(in case vendor is libnet repo) ?

**Comment by vikaschoudhary16** [comment]
@vdemeester,

Moved engine-api repo changes to this PR , https://github.com/docker/engine-api/pull/249
Please let me know if i my steps are too absurd and incorrect. :)

**Comment by thaJeztah** [comment]
ping @mavenugo @mrjana @aboch PTAL

**Comment by thaJeztah** [comment]
ping @mavenugo @mrjana @aboch PTAL

**Comment by mrjana** [comment]
@vikaschoudhary16 The `address-space` abstraction that added in IPAM is to accommodate a future multi-tenancy use case in docker which is not there yet. When we define such an abstraction at docker level we will have a clear idea of whether we need a separate config option in `network create` or is it going to be derived from which tenant this network belongs to. So adding this option to `network create` looks premature so this PR is **not** LGTM for me.

**Comment by thaJeztah** [comment]
Thanks @mrjana I briefly discussed this with @aboch yesterday, and he said something similar. For that reason, I'll close this PR, but thanks for contributing @vikaschoudhary16, hope you understand

**Pull request closed without merging**
