### PR TITLE
Ensure that a device mapper task is referenced until task is complete

### PR DESCRIPTION
**Pull request by nhorman**
DeviceMapper tasks in go use SetFinalizer to clean up C construct
counterparts in the C LVM library.  While thats well and good, it relies
heavily on the exact interpretation of when the golang garbage collector
determines that an object is unreachable is subject to reclaimation.
While common sense would assert that for stack variables (which these DM
tasks always are), are unreachable when the stack frame in which they
are declared returns, thats not the case.  According to this:

https://golang.org/pkg/runtime/#SetFinalizer

The garbage collector decides that, if a function calls into a
systemcall (which task.run() always will in LVM), and there are no
subsequent references to the task variable within that stack frame, then
it can be reclaimed.  Those conditions are met in several devmapper.go
routines, and if the garbage collector runs in the middle of a
deviceMapper operation, then the task can be destroyed while the
operation is in progress, leading to crashes, failed operations and
other unpredictable behavior.

The fix is to use the KeepAlive interface:

https://golang.org/pkg/runtime/#KeepAlive

The KeepAlive method is effectively an empy reference that fools the
garbage collector into thinking that a variable is still reachable.  By
adding a call to KeepAlive in the task.run() method, we can ensure that
the garbage collector won't reclaim a task object until its execution
within the deviceMapper C library is complete.

Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by nhorman** [comment]
sorry, forgot to fill out the rest of the information.  This pull is based of code review that I preformed while fixing issue #33050.  I noticed that the use of SetFinalizer was in voliation of the early reclamation examples provided by the runtime documentation for golang, and the addition of the use of KeepAlive just made sense, as it fit exactly with the provided examples.

**Comment by rhvgoyal** [comment]
@nhorman thanks for the analysis. This makes sense to me.  We ran into a crash which very well could happen due to this. 

LGTM

**Comment by runcom** [comment]
LGTM

**Comment by cpuguy83** [comment]
It seems like this would mainly be an issue on go 1.8? I've added to the 17.06 milestone.

**Comment by rhvgoyal** [comment]
@cpuguy83  Don't know. Is this behavior new to 1.8 and older version don't have it?

**Comment by cpuguy83** [comment]
https://golang.org/doc/go1.8#liveness

**Comment by rhvgoyal** [comment]
@cpuguy83 thanks for the pointer. So this is new to 1.8.

I am surprised that how can newer versions can break existing programs. If this is an optimization, then there should be an option to opt-in. 

Now all the programs which have been running fine with older versions, have potential to be broken?

**Comment by cpuguy83** [comment]
Actually reading https://forum.golangbridge.org/t/curious-about-runtime-keepalive-usage/3530 is a little scary.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by nhorman** [comment]
FWIW, I agree that the addition of this liveness limitation added to the garbage collector in go 1.8 is quite shocking.  I would have thought the golang devs would have been more conservative at this point.  Thanks all for the quick review

**Pull request merged**
