### PR TITLE
Remove unused opts (moved to docker/cli)

### PR DESCRIPTION
**Pull request by vdemeester**
Part of moby/moby#33150 👼. This removes opts imported in `docker/cli` here https://github.com/docker/cli/pull/82/ and completely not used in `moby/moby`.

Next step will be to move the others elsewhere (in `cmd/dockerd`) and removing `opts` alltogether.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM (if green)

**Comment by vdemeester** [comment]
Also, we should wait for docker/cli#82 to be merge before merging this one 👼

**Review by dnephin — APPROVED** [review]
There's a lot more code left over here than I expected, but I guess a lot of this will be cleaned up when we figure out what to do with cmd/dockerd/

**Comment by mlaventure** [comment]
@vdemeester, I just merged the `cli` counterpart, wanna update the cli used by integration-cli here too, or just go ahead an merge (since no functionality is changed)?

**Comment by vdemeester** [comment]
@mlaventure should be good to merge as is because this just remove code that wasn't called in this repository. I'll update the `cli` a little bit later (if nobody did it before 😉)

**Comment by mlaventure** [comment]
:green_heart:

**Pull request merged**
