### PR TITLE
refactor cluster/helper.go and split cluster.go into multiple files

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

This PR did two things: 

1. split cluster/cluster.go into multiple files `services.go`, `nodes.go`, `networks.go`, `swarm.go`, `tasks.go`
2. refactor cluster/helper.go to make it more efficient.

I found that when docker is in Swarm Mode, all the handlers about swarm cluster is located in cluster/cluster.go except secret handlers. We could split cluster/cluster.go into several parts like `secrets.go`, `services.go`, `swarm.go`, `nodes.go`, `network.go`, `task.go` and so on. This explains the purpose of my first part of work.

For second part of this pr's work, I refactor the cluster/helper.go, I think I did not change the original logic, while I changed to a more reasonable way, like return fast, like avoid a long block and so on. 

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — CHANGES_REQUESTED** [review]
I definitely dont want to `cluster.go` to grow.

**Comment by vieux** [comment]
I agree with @vdemeester, I'd prefer to see `cluster.go` getting split into multiple files.

**Comment by allencloud** [comment]
Thanks for your feedback. @vieux @vdemeester 
I agree with splitting cluster.go into multiple files. Now I updated the PR to finish the split. PTAL.

**Comment by aaronlehmann** [comment]
Unfortunately this is very hard to review. I think it would be helpful to split the code movement into separate commits from actual changes to the functions.

**Comment by allencloud** [comment]
Thanks for your feedback, @aaronlehmann . The original way is indeed hard to review. And I try to split this PR into 6 commits which makes review a little bit easy. PTAL, thanks a lot.

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by aaronlehmann** [comment]
LGTM

Thanks, this is a worthy cleanup.

@tonistiigi: Are you okay with the reorganization?

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
