### PR TITLE
Remove unused engine-api packages

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by stevvooe** [comment]
What are we supposed to use instead?

**Comment by tonistiigi** [comment]
@stevvooe `github.com/docker/docker/api/types` `github.com/docker/docker/client`

**Comment by stevvooe** [comment]
@tonistiigi Not to be confused with `github.com/docker/docker/api/client`. Shouldn't we move that package to `cli` or something?

**Comment by tonistiigi** [comment]
@stevvooe I think that was the plan (cc @dnephin)

**Comment by vieux** [comment]
LGTM

**Comment by dnephin** [comment]
Yes, I would like to move `api/client` to `cli/commands` which I think is a more appropriate name for the package. I was experimenting with [gomvpkg](https://godoc.org/golang.org/x/tools/cmd/gomvpkg) yesterday, but it fails with a bunch of import errors. I'm going to try again today. Might just use `git mv` and `sed`.

**Comment by crosbymichael** [comment]
@dnephin I use:

`pt -l "github.com/docker/engine-api/types" | xargs perl -pi -E "s/docker\/engine-api\/types/docker\/docker\/api\/types/g"`

**Comment by dnephin** [comment]
LGTM

**Pull request merged**
