### PR TITLE
Use buildkit session package

### PR DESCRIPTION
**Pull request by tiborvass**
Ping @tonistiigi @AkihiroSuda

### CODE REVIEW

**Comment by tiborvass** [comment]
@tonistiigi sorry I didn't make the changes to update to latest of buildkit/session package. Took moby/buildkit@fed5c1d9cee6f734f58f3addca6e8d1750df48a6

**Review by dnephin — COMMENTED** [review]
I think we need a PR on the cli as well, it seems to be imported there

**Comment by tonistiigi** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
> I think we need a PR on the cli as well, it seems to be imported there

@tiborvass can you take care of opening a PR for the CLI? Probably good to add a comment to the vendor.conf there to mention which dependencies should be kept in sync with moby/moby (if moby/moby is bumped)

**Comment by thaJeztah** [comment]
all green

**Pull request merged**
