### PR TITLE
Explicitly mention that '-P' maps to random ports

### PR DESCRIPTION
**Pull request by SvenDowideit**
as noted in https://github.com/boot2docker/boot2docker/issues/690

Signed-off-by: Sven Dowideit SvenDowideit@docker.com

Docker-DCO-1.1-Signed-off-by: Sven Dowideit SvenDowideit@docker.com (github: SvenDowideit)

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@tianon @fredlf @jamtur01

**Comment by jamtur01** [comment]
LGTM

**Comment by tianon** [comment]
LGTM cc @jfrazelle

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
