### PR TITLE
Fix volumes-from mount references.

### LINKED ISSUE #14108: 1.7.0 Broken legacy containers that used the `--volumes-from` option
Did upgrade today one of our servers  to docker `v1.7.0` (running Ubuntu 14.04LTS), and discovered that all our legacy containers started with the `--volumes-from` flag would not start anymore:

```
# docker start foo_backend.production
Error response from daemon: Cannot start container foo.backend.production: Unable to setup mount point, neither source nor volume defined
Error: failed to start containers: [foo_backend.production]
```

```
# docker inspect foo_backend.production | jq .[0].Volumes
{
  "/srv/data": ""
}
```

---

```
# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```
# docker info
Containers: 13
Images: 110
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 62.89 GiB
Name: fr-6f6e
ID: SUBT:ZILY:FYIX:KZQL:UMLN:HYYG:4X75:BA3J:346R:XSDJ:U5HR:2L63
WARNING: No swap limit support
```

```
# uname -a
Linux fr-6f6e 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### LINKED ISSUE #14347: Docker 1.7.0 volumes set to false on upgrade
Hi, 

We have recently upgraded the components of out multi-container logging service to the latest version. In doing so, we decided to upgrade to docker version: 1.7.0. 

This all seemed to go smoothly until I tested the restart policies for our containers by rebooting the lab box. All the containers restarted successfully except for Elasticsearch, which would unsuccessfully attempt to restart over and over.

We began by rolling back the version of Elasticsearch but the problem persisted, so started to rule out other components of the service. In the end the problem was with Docker 1.7.0, we discovered this by downgraded to 1.6.2 and the restart policies began to work again after reboot. 

Our current set-up consists of the following:
ELK stack with Supervisor running and monitoring the processes in each container
A Data-Only container which is a volume mounted on the host for ES data

I am wondering has anyone else encountered this problem?

### PR DESCRIPTION
**Pull request by calavera**
Fixes #14108
Fixes #14347

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
Many thanks to @zergin for the reproducible case:

```
Inspecting volumes...
docker inspect di-14347-user1 | jq -C .[0].VolumesRW # should give "/data": false
{
  "/data": false
}
Expected false.
docker inspect di-14347-user2 | jq -C .[0].VolumesRW # should give "/data": true
{
  "/data": true
}
Expected true.
make clean
make[1]: Entering directory `/tmp'
Cleaning...
docker rm -f di-14347-user1
di-14347-user1
docker rm -f di-14347-user2
di-14347-user2
make[1]: Leaving directory `/tmp'
Running reverse...
docker run --name di-14347-user1 --volumes-from di-14347-data:rw "tests/docker-issue-14347"
docker run --name di-14347-user2 --volumes-from di-14347-data:ro "tests/docker-issue-14347"
Inspecting volumes...
docker inspect di-14347-user1 | jq -C .[0].VolumesRW # should give "/data": true
{
  "/data": true
}
Expected true.
docker inspect di-14347-user2 | jq -C .[0].VolumesRW # should give "/data": false
{
  "/data": false
}
Expected false.
```

**Comment by calavera** [comment]
Adding a test to avoid regressions now.

**Comment by zergin** [comment]
@calavera - Looking good, thanks. Any ETA for public release?

**Comment by calavera** [comment]
@zergin we'll probably build RC3 today and that will be promoted to final release if everything goes well.

**Comment by LK4D4** [comment]
Haha
LGTM

**Comment by zergin** [comment]
Swell :grinning: 
Out of curiosity - what are the "z"-modes (found in rwModes/roModes maps)?

**Comment by LK4D4** [comment]
@zergin it's labels for SELinux

**Comment by estesp** [comment]
LGTM

**Comment by calavera** [comment]
:dancer:

**Comment by calavera** [comment]
Cherry picked into #14264

**Comment by zergin** [comment]
@LK4D4 I see, thanks. Found it libcontainer with explanation now that I knew what to look for.

**Pull request merged**
