### PR TITLE
Make sure tags and digests don’t collide

### PR DESCRIPTION
**Pull request by tonistiigi**
Reverts #14664

Signed-off-by: Tonis Tiigi tonistiigi@gmail.com

### CODE REVIEW

**Comment by tiborvass** [comment]
@tonistiigi would be great if you could explain in the commit message (and the PR description) why this is needed.

**Comment by tonistiigi** [comment]
@tiborvass Tags an digests are kept in the same storage. We want to make sure that they are completely separated - tags are something users set and digests can only be set by pull-by-digest code path.

**Comment by icecrime** [comment]
Code LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
