### PR TITLE
Don't hold lock around volume driver for volume create.

### PR DESCRIPTION
**Pull request by srust**
Hi Brian @cpuguy83,

Unfortunately the commit for #14242 broke the behavior introduced in #15684, namely that a volume plugin can run in a container across docker restart. #15684 allowed this by not holding a lock across volume driver initialization.

This PR fixes and allows that again, by not holding a lock in the new volume create code path introduced in #14242 across the volume driver initialization.

With this fix, plugins are allowed to initialize and start in parallel with containers that depend on them, and allow a volume plugin in a container across docker restart.

Thanks!

Signed-off-by: Stephen Rust srust@blockbridge.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Can you add this test to make sure we don't do this again?

```diff
diff --git a/integration-cli/docker_cli_start_volume_driver_unix_test.go b/integration-cli/docker_cli_start_volume_driver_unix_test.go
index 0cc5192..b29c09e 100644
--- a/integration-cli/docker_cli_start_volume_driver_unix_test.go
+++ b/integration-cli/docker_cli_start_volume_driver_unix_test.go
@@ -9,8 +9,10 @@ import (
 	"net/http"
 	"net/http/httptest"
 	"os"
+	"os/exec"
 	"path/filepath"
 	"strings"
+	"time"
 
 	"github.com/go-check/check"
 )
@@ -271,3 +273,40 @@ func (s *DockerExternalVolumeSuite) TestStartExternalNamedVolumeDriverCheckBindL
 	c.Assert(s.ec.mounts, check.Equals, 1)
 	c.Assert(s.ec.unmounts, check.Equals, 1)
 }
+
+// Make sure a request to use a down driver doesn't block other requests
+func (s *DockerExternalVolumeSuite) TestStartExternalVolumeDriverLookupNotBlocked(c *check.C) {
+	specPath := "/etc/docker/plugins/down-driver.spec"
+	err := ioutil.WriteFile("/etc/docker/plugins/down-driver.spec", []byte("tcp://127.0.0.7:9999"), 0644)
+	c.Assert(err, check.IsNil)
+	defer os.RemoveAll(specPath)
+
+	chCmd1 := make(chan struct{})
+	chCmd2 := make(chan error)
+	cmd1 := exec.Command(dockerBinary, "volume", "create", "-d", "down-driver")
+	cmd2 := exec.Command(dockerBinary, "volume", "create")
+
+	c.Assert(cmd1.Start(), check.IsNil)
+	defer cmd1.Process.Kill()
+	time.Sleep(100 * time.Millisecond) // ensure API has been called
+	c.Assert(cmd2.Start(), check.IsNil)
+
+	go func() {
+		cmd1.Wait()
+		close(chCmd1)
+	}()
+	go func() {
+		chCmd2 <- cmd2.Wait()
+	}()
+
+	select {
+	case <-chCmd1:
+		cmd2.Process.Kill()
+		c.Fatalf("volume create with down driver finished unexpectedly")
+	case err := <-chCmd2:
+		c.Assert(err, check.IsNil, check.Commentf("error creating volume"))
+	case <-time.After(5 * time.Second):
+		c.Fatal("volume creates are blocked by previous create requests when previous driver is down")
+		cmd2.Process.Kill()
+	}
+}
```

**Comment by srust** [comment]
Sure. Thanks for the test case!

Passed for me:

PASS: docker_cli_start_volume_driver_unix_test.go:278: DockerExternalVolumeSuite.TestStartExternalVolumeDriverLookupNotBlocked	0.128s


Pushed new commit.

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
