### PR TITLE
Add stream format details for attach/logs endpoint

### LINKED ISSUE #33486: client.ContainerLogs() documentation says nothing about the in-band data in the io.Reader
The [documentation on godoc for client.ContainerLogs()](https://godoc.org/github.com/moby/moby/client#Client.ContainerLogs) doesn't include any information, not even a warning, about the 8-byte tokens included in the bytes returned by the io.Reader.

This log format utterly violates the principle of least surprise, which makes the lack of documentation particularly bad.  Since Go was specifically designed with channels and multiple return values to avoid this kind of in-band signalling, I really don't understand why this is designed this way.  But it's probably too late to change without significant backwards compatibility breakage, so I guess the most I can ask is for the documentation to be updated to give developers a heads-up about this misfeature.

Whenever documentation does get written, it's important to note that you don't get one header + data per call to Read(), you get a buffer that has _one or more_ header+data chunks.  So you have to fully parse the buffers the io.Reader serves up, not just the first 8 bytes.

And if anyone stumbles across this issue and wants to wrap the docker not-quite-an-io.Reader io.Reader, here's my quick hack of a solution:

```
type dockerLogWrapper struct {
    stream io.Reader
}

func (w dockerLogWrapper) Read(b []byte) (n int, err error) {
    buf := make([]byte, len(b))
    m, err := w.stream.Read(buf)
    switch {
        case m == 0 : return
        case m > 0 && m < 8:
            return 0, fmt.Errorf("malformed header in docker stream")
        default:
            cur := 0
            for {
                if cur >= m {  break  }
                i := int(binary.BigEndian.Uint32(buf[cur+4:cur+8]))
                copy(b[n:], buf[cur+8:cur+8+i])
                cur += i+8
                n += i
            }
    }
    return
}
```

Use it like so:

```
    out, err = cli.ContainerLogs(ctx, r.ID, types.ContainerLogsOptions{ShowStdout: true})
    safe_reader := dockerLogWrapper{stream:out}
    // and now you can Read() from safe_reader normally
```

keywords: log, corrupt, stdout, stderr, unicode, binary, extra bytes

### PR DESCRIPTION
**Pull request by cpuguy83**
closes #33486

### CODE REVIEW

**Comment by cpuguy83** [comment]
Tried to make this look as good as possible, unfortunately godoc can be a bit limited.

screen shot 2017-06-02 at 12 34 19 pm

**Review by boaz0 — APPROVED** [review]
👍

**Comment by cpuguy83** [comment]
Ping

**Comment by stevvooe** [comment]
LGTM

cc @ahmetb

**Comment by ahmetb** [comment]
I don't remember where I asked about this. But please make sure the same information is present on the /logs endpoint documentation on the API reference web page as well.

**Comment by cpuguy83** [comment]
@ahmetb It's there... or rather linked to.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
This test is really flaky; https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/15393/console

```
20:12:20 ----------------------------------------------------------------------
20:12:20 FAIL: check_test.go:97: DockerSuite.TearDownTest
20:12:20 
20:12:20 check_test.go:98:
20:12:20     testEnv.Clean(c, dockerBinary)
20:12:20 environment/clean.go:67:
20:12:20     t.Fatalf("error removing containers %v : %v (%s)", containers, result.Error, result.Combined())
20:12:20 ... Error: error removing containers [cca42f72dd85] : exit status 1 (Error response from daemon: Could not kill running container cca42f72dd85f3922ba5836203ee7744f5d9237765840743fdd91b3f63d57149, cannot remove - Cannot kill container cca42f72dd85f3922ba5836203ee7744f5d9237765840743fdd91b3f63d57149: invalid container: cca42f72dd85f3922ba5836203ee7744f5d9237765840743fdd91b3f63d57149
20:12:20 )
20:12:20 
20:12:20 
20:12:20 ----------------------------------------------------------------------
20:12:20 PANIC: docker_cli_attach_test.go:90: DockerSuite.TestAttachTTYWithoutStdin
20:12:20 
20:12:20 ... Panic: Fixture has panicked (see related PANIC)
20:12:20 
```

**Pull request merged**
