### PR TITLE
Send resp immediately on GET /events

### LINKED ISSUE #14354: Remote API behaviour - Is this normal?
I'm writing an event listener and faced problem with older version of docker so switched from Docker v1.4 to v1.7.

In previous version if connecting to socket and sending command ```GET /events HTTP/1.0\r\n\r\n``` I was getting the HTTP response immediately after sending the command but in v1.7 I have to wait till any event is triggered.

My question is is this the normal behaviour of the API or this is a bug?

Testing this in Perl and Python both had the same result.
Any clue?

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #14354

### CODE REVIEW

**Comment by calavera** [comment]
@cpuguy83 the test failing might be legit. Do you mind to check?

**Comment by cpuguy83** [comment]
Yeah, this is a racey test, I've seen it fail in other cases randomly as well.

**Comment by LK4D4** [comment]
LGTM
Not sure why we including this to 1.7.1, but ok.

**Comment by cpuguy83** [comment]
@LK4D4 I didn't test against 1.6, but it was reported as a regression is all.

**Comment by cpuguy83** [comment]
Yeah, confirmed 1.6.2 has this behavior.

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
Cherry picked into #14264

**Comment by calavera** [comment]
@icecrime, @cpuguy83 I've removed this PR from the release. Tests were failing intermittently and it's not a regression. We can consider adding it later if we strongly feel like it must go into the release.

**Comment by cpuguy83** [comment]
Curious, this test is failing intermittently or something else?

**Comment by calavera** [comment]
yes, this test.

**Pull request merged**
