### PR TITLE
Fix login

### PR DESCRIPTION
**Pull request by duglin**
Right now it returns:

```
FATA[0001] json: Unmarshal(non-pointer types.AuthResponse)
```

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
is there a test ID we can use to write a login testcase?

**Comment by tiborvass** [comment]
Tested, it indeed fixes the issue.

LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by jfrazelle** [comment]
Do we need this in 1.6.0

**Comment by duglin** [comment]
only if #11670 is in 1.6  and I don't think it is, but can you check?

**Comment by jfrazelle** [comment]
It's not so we good ;)

**Pull request merged**
