### PR TITLE
new storage driver: fuse-overlayfs

### LINKED ISSUE #40218: new storage driver: fuse-overlayfs
Currently, rootless `overlay2` storage driver works only on Ubuntu and Debian 10 hosts.

Supporting [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) would be highly useful for the users of other distros.

## System requirement

* [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) needs to be installed
* Kernel needs to be >= 4.18

## Implementation

Podman already implements fuse-overlayfs, but it is implemented as a storage opt ("overlay.mount_program") rather than an independent storage driver: https://github.com/containers/storage/blob/01ea27db516e1ea8dd22b63b69d3a66c571effa7/drivers/overlay/overlay.go#L307

For Moby, I suggest implementing it as a new independent storage driver "fuse-overlayfs".

My first plan was to wait until Moby migrates to containerd snapshotters and use [containerd fuse-overlayfs plugin](https://github.com/AkihiroSuda/containerd-fuse-overlayfs), but it is not likely to happen in foreseeable future.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**
Added a new storage driver: `fuse-overlayfs`.

`fuse-overlayfs` provides rootless overlayfs functionality without depending on any kernel patch.

Aside from rootless, `fuse-overlayfs` could be potentially used for eliminating `chown()` calls that happen in userns-remap mode, because `fuse-overlayfs` also provides shiftfs functionality.

System requirements:
* [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) needs to be installed. Tested with 0.7.6.
* kernel >= 4.18

Fix #40218

**- How I did it**

The implementation is based on Podman's `overlay` driver which supports both kernel-mode overlayfs and fuse-overlayfs in the single driver instance:
https://github.com/containers/storage/blob/39a8d5ed/drivers/overlay/overlay.go

However, Moby's implementation aims to decouple `fuse-overlayfs` driver from the kernel-mode driver (`overlay2`) for simplicity.

**- How to verify it**

```console
$ go test -exec sudo -v ./daemon/graphdriver/fuse-overlayfs
=== RUN   TestFUSEOverlayFSSetup
--- PASS: TestFUSEOverlayFSSetup (0.00s)
=== RUN   TestFUSEOverlayFSCreateEmpty
--- PASS: TestFUSEOverlayFSCreateEmpty (0.00s)
=== RUN   TestFUSEOverlayFSCreateBase
--- PASS: TestFUSEOverlayFSCreateBase (0.00s)
=== RUN   TestFUSEOverlayFSCreateSnap
--- PASS: TestFUSEOverlayFSCreateSnap (0.02s)
=== RUN   TestFUSEOverlayFS128LayerRead
--- PASS: TestFUSEOverlayFS128LayerRead (4.32s)
=== RUN   TestFUSEOverlayFSTeardown
--- PASS: TestFUSEOverlayFSTeardown (0.09s)
PASS
ok      github.com/docker/docker/daemon/graphdriver/fuse-overlayfs      4.450s
```

**- Description for the changelog**

new storage driver: fuse-overlayfs

**- A picture of a cute animal (not mandatory but encouraged)**

:penguin:

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @dmcgowan PTAL

**Comment by cpuguy83** [comment]
SGTM

Even though we are moving to containerd, I think this is good to bring in.
As @tonistiigi pointed out on the maintainers call, this doesn't pose any new problems for that migration.

**Comment by thaJeztah** [comment]
Agreed, I'm ok with moving this forward (did not review the code changes other than glancing over it)

**Comment by AkihiroSuda** [comment]
@cpuguy83 @tonistiigi @tiborvass PTAL?

**Comment by thaJeztah** [comment]
@dmcgowan @kolyshkin would you be able to have a look?

**Review by kolyshkin — APPROVED** [review]
SGTM

**Comment by AkihiroSuda** [comment]
@cpuguy83 @kolyshkin LGTY?

**Comment by kolyshkin** [comment]
So, I see that in https://github.com/containers/storage/ they use the same overlay driver for in-kernel mounting and fuse-overlayfs, by supplying one additional parameter to overlay driver (see for example https://github.com/containers/storage/blob/master/drivers/overlay/overlay.go#L952).

Is this something we'd want to do here as well, or is a separate driver a better option? @AkihiroSuda @thaJeztah @dmcgowan

**Comment by AkihiroSuda** [comment]
Let's avoid mixing up different drivers

**Comment by kolyshkin** [comment]
LGTM then

**Comment by kolyshkin** [comment]
We got SGTM from @cpuguy83 and LGTM from myself, so I think @thaJeztah you can merge it now

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
