### PR TITLE
overlayfs added to FsNames

### PR DESCRIPTION
**Pull request by p4l1ly**
**\- What I did**
I added overlayfs to FsNames (I think you have missed it)

**\- How I did it**
Only added a line

**\- How to verify it**
Run your tests if you want, but the change is trivial

**\- Description for the changelog**

overlayfs added to FsNames

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by estesp** [comment]
Reasonable.. turns out the strings were initially only meant for "real" filesystems during the graphdriver bringup (so an error could report thing like *overlay {type} not supported on underlying fs {type}*), but the magic values are now also used for also testing mounts being of specific real and overlay types, so the magic list and string list got out of sync.

No problem to make them match, even though those strings aren't used today.

LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by p4l1ly** [comment]
I wanted to use overlay2 driver on the overlayfs filesystem and I got the error message: overlay2 is not supported over <unknown>

I thought that Docker has some problems with identifying the underlying filesystem, it took me a while of digging in the code to find out that it has no problem with it, it just does not support overlayfs as underlying filesystem.

**Pull request merged**
