### PR TITLE
Registry redirect fix

### PR DESCRIPTION
**Pull request by moxiegirl**
Updates to docs post-release.  Also picked up some build changes to fix the registry issue.

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @thaJeztah @docker/docs-owners 

/cc @bfirsh @stevvooe @dmp42  Closing in the fix.  In need to get the PR merged on the docker/distribution repo and we'll be good.

**Comment by thaJeztah** [comment]
LGTM after the distribution PR (think it's this one: https://github.com/docker/distribution/pull/392) is merged (missed that in https://github.com/docker/docker/pull/12518, is that a problem right now?)

**Comment by moxiegirl** [comment]
@thaJeztah Yep.  The downstream repo needs a tweak.

**Comment by thaJeztah** [comment]
:'(

As a quick fix, you could try;

```Dockerfile
ADD https://raw.githubusercontent.com/docker/distribution/${DISTRIB_BRANCH}/docs/index.md /docs/sources/registry/index.md
```

But merging in distribution is of course the right solution.

Sorry I missed that the changes in the docker/distribution weren't there yet, I just verified the redirect.

**Comment by moxiegirl** [comment]
@thaJeztah yes, I know about the "cheat" way --- that's how I got beta running. ;-P

**Comment by moxiegirl** [comment]
author LGTM

**Pull request merged**
