### PR TITLE
Enable auto-creation of host-path on Windows

### PR DESCRIPTION
**Pull request by thaJeztah**
Auto-creation of host-paths has been un-deprecated,
so to have feature-parity between Linux and Windows,
this feature should also be present on Windows.

This enables auto-creation on Windows, and cleans up
the logic, by reducing nested "if"s, and removing an
unnecessary os.Stat() (already handled my os.MkdirAll() / system.MkdirAll()).

probably best to merge this after https://github.com/docker/docker/pull/22065 :-)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oops, my mistake; fixing now

**Comment by icecrime** [comment]
```
09:30:26 # github.com/docker/docker/volume
09:30:26 volume/volume.go:5: imported and not used: "os"
09:30:26 volume/volume.go:6: imported and not used: "runtime"
```

**Comment by thaJeztah** [comment]
thanks @icecrime, just noticed, was too fast pushing :+1:

**Comment by jhowardmsft** [comment]
@swernli Hmm. I think this might need, at least for TP5, a conditional check to not do this for Hyper-V containers.

**Comment by jhowardmsft** [comment]
LGTM. Ignore my comment above. I was being :confused:

**Comment by LK4D4** [comment]
@thaJeztah it's rebase time!

**Comment by thaJeztah** [comment]
Oh again, will do!

**Comment by thaJeztah** [comment]
rebased

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
