### PR TITLE
Bump v1.12.0 docs

### PR DESCRIPTION
**Pull request by SvenDowideit**
These are the few PR's that I found that we'd like to include in v1.12.0

if merging to the bump_v1.12.0 branch is an issue, we can do it separately.

@tiborvass @thaJeztah @sfsmithcha 

commits come from:
- PR #23977 (1a0bca5) Jul  2 09:19:48 from Morsicus/master
- 1.10.0 process/cherry-pick status/3-docs-review
  - docs/ changes in 166928a24bf5f3b23103b8ad09f134e277c00d6a Update docker_remote_api_v1.22.md Update docker_remote_  
- PR #24460 (ad969f1) Jul  8 19:37:32 from thaJeztah/make-archive-link-absolute
- 1.6.0 process/cherry-pick status/3-docs-review
  - docs/ changes in 4b090ae5f259dcedb946463a8512b2416a971fcb Make archive links absolute
- PR #24970 (d8c9fd0) Jul 27 09:00:15 from sfsmithcha/daemonless_containers
- 1.12.0 process/cherry-pick status/3-docs-review
  - docs/ changes in cbd07495a3c5b49a47ea288a9e6ee9b24800cace add doc for live-restore setting and daemonless contain              ers, fix admin guide menu
- PR #25076 (08d1995) Jul 26 18:33:46 from sfsmithcha/add_manage_nodes_guide
- 1.12.0 area/swarm kind/docs process/cherry-pick status/4-merge
  - docs/ changes in 704facbbab0af520e0429eb75a6f875b6015a77c add swarm manage nodes guide
- PR #24955 (59e3416) Jul 27 08:59:08 from sfsmithcha/add_how_services_work
- 1.12.0 process/cherry-pick status/3-docs-review
  - docs/ changes in bef36fba4022e1c37f1f21e9e265e7f98e2f7f65 add how services work to how swarm mode works guide
- PR #25083 (3b8ef03) Jul 26 20:07:51 from mapk0y/fix-doc-ipaddress
- 1.6.0 process/docs-cherry-pick status/3-docs-review
  - docs/ changes in a94b48923e8ec7a5e9ebe6101f0ccac208fb4f25 fix the ipaddress of an explanation.
- PR #25118 (fb7edde) Jul 27 09:27:34 from thaJeztah/various-docs-fixes
-  process/cherry-pick status/3-docs-review
  - docs/ changes in d8434eba462752327d4c7769d3ce2c85013c211e fix minor docs issues
- PR #25119 (415ef83) Jul 27 11:43:37 from thaJeztah/pre-1.12-ga-fixes
- 1.12.0 process/cherry-pick status/3-docs-review
  - docs/ changes in 053ac127ab0f784bebeda38f29f2d7615d2ffcb8 Remove release-candidate advisories
- PR #25120 (296378d) Jul 27 11:48:10 from thaJeztah/put-back-1.12-links
- 1.12.0 process/cherry-pick status/3-docs-review
  - docs/ changes in cd69b94241b94d16ac6dfad6e6bc7fc981dc2cca Add back links to 1.12 release in deprecated.md

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, but waiting  on @tiborvass for the merge (re: the `-x m1`)

**Comment by tiborvass** [comment]
@SvenDowideit I would prefer cherrypicking each commit instead with `-x -s`. Not that one is better over the other, but I'd like to stay consistent at least for 1.12.0.

**Comment by SvenDowideit** [comment]
@tiborvass roger, I'll update this PR after dinner :)

but no, i dissagree :D `-x -m1 <merge commit>` _is_ superior >much giggling in the cheap seats<

**Comment by thaJeztah** [comment]
note: docs CI is expected to fail on some broken links due to: https://github.com/docker/docker/pull/25114/commits/441b660dd17a209b9bdcaf24518d5ad35965f0d3

**Comment by tiborvass** [comment]
LGTM ignoring expected documentation CI failure

**Pull request merged**
