### PR TITLE
remove fallback for Go 1.4

### PR DESCRIPTION
**Pull request by thaJeztah**
Windows is now built using Go 1.6, so we no longer need to have a fallback for Go 1.4.

This removes the fallback that was introduced in
6df3fc51759a6219e965a30c413cb43ddbc897c9 (https://github.com/docker/docker/pull/18553)

### CODE REVIEW

**Comment by vdemeester** [comment]
@thaJeztah if we do that we might add somewhere that building docker with Go 1.4 is not supported anymore, right ?

**Comment by thaJeztah** [comment]
Oh, I thought we did (it came up recently), because (IIRC) there are some other changes that now required Go 1.5 or 1.6; looks like we didn't update yet [PACKAGERS.md](https://github.com/docker/docker/blob/master/project/PACKAGERS.md#build-dependencies).

Let me try and find it; no hurry, it's just something I stumbled on, and thought to clean up

**Comment by justincormack** [comment]
The swarmkit README says it requires Go 1.6.

**Comment by crosbymichael** [comment]
The change as what it is looks good

LGTM

**Comment by cyphar** [comment]
*cough* Isn't gccgo still Go 1.4? :P

**Comment by justincormack** [comment]
No I don't think so any more, it was upgraded.

**Comment by thaJeztah** [comment]
Yup, it was updated to 1.6.2; https://github.com/docker/docker/blame/d17b9f3da064f4c7e70867be5e64d06b127df301/Dockerfile.gccgo#L9

**Comment by vdemeester** [comment]
This is all green :green_heart: 
LGTM 🐹

**Comment by justincormack** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
