### PR TITLE
update RootlessKit to 2.0.2

### LINKED ISSUE #47480: rootless (non-dpkg): update docs and `dockerd-rootless-setuptool.sh check` for Ubuntu 24.04  (`kernel.apparmor_restrict_unprivileged_userns`)
### Description

Ubuntu 24.04 will enable [`kernel.apparmor_restrict_unprivileged_userns`](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces) by default ([LP 2046477](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046477), [LP 2046844](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844)), so rootless setup with `https://get.docker.com/rootless` (non-dpkg) needs the following steps:
```bash
if [ ! -e "/etc/apparmor.d/usr.local.bin.rootlesskit" ] && [ -e "/etc/apparmor.d/abi/4.0" ] && [ -e "/proc/sys/kernel/apparmor_restrict_unprivileged_userns" ]; then
  cat >"/etc/apparmor.d/usr.local.bin.rootlesskit" <<EOF
# Ubuntu 23.10 introduced kernel.apparmor_restrict_unprivileged_userns
# to restrict unsharing user namespaces:
# https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
#
# kernel.apparmor_restrict_unprivileged_userns is still opt-in in Ubuntu 23.10,
# but it is expected to be enabled in future releases of Ubuntu.
abi <abi/4.0>,
include <tunables/global>

/usr/local/bin/rootlesskit flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/usr.local.bin.rootlesskit>
}
EOF
  systemctl restart apparmor.service
```

This additional step is *not* needed for dpkg setup (`apt-get install docker-ce-rootless-extras`), as the `apparmor` package is shipped with the profile for `/usr/bin/rootlesskit`:
https://packages.ubuntu.com/noble/amd64/apparmor/filelist

<details><summary><code>/etc/apparmor.d/rootlesskit</code></summary><p>

```
# This profile allows everything and only exists to give the
# application a name instead of having the label "unconfined"

abi <abi/4.0>,
include <tunables/global>

profile rootlesskit /usr/bin/rootlesskit flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/rootlesskit>
}
```

</p></details>

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**- What I did**

Fix https://github.com/moby/moby/issues/47480 (except docs) via:
- https://github.com/rootless-containers/rootlesskit/pull/421

**- How I did it**
Updated RootlessKit
https://github.com/rootless-containers/rootlesskit/compare/v2.0.1...v2.0.2

**- How to verify it**

`dockerd-rootless-setuptool.sh` will print the following error if the apparmor constraint is not satisfied
```
WARN[0000] [rootlesskit:parent] This error might have happened because /proc/sys/kernel/apparmor_restrict_unprivileged_userns is set to 1  error="fork/exec /proc/self/exe: permission denied"
WARN[0000] [rootlesskit:parent] Hint: try running the following commands:


########## BEGIN ##########
cat <<EOT | sudo tee "/etc/apparmor.d/home.suda.bin.rootlesskit"
# ref: https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
abi <abi/4.0>,
include <tunables/global>

/home/suda/bin/rootlesskit flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/home.suda.bin.rootlesskit>
}
EOT
sudo systemctl restart apparmor.service
########## END ##########
 
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: permission denied
```

**- Description for the changelog**

```markdown changelog
update RootlessKit to [v2.0.2](https://github.com/rootless-containers/rootlesskit/releases/tag/v2.0.2)
```

**- A picture of a cute animal (not mandatory but encouraged)**

🐧

### CODE REVIEW

**Comment by thaJeztah** [comment]
Curious;

- should we also consider adding some of these (rootless-specific) checks to `contrib/check-config.sh`? (if apparmor is available, also check for the `apparmor_restrict_unprivileged_userns` feature?
- Somewhat orthogonal; I notice the _only_ place we use the rootlesskit vendoring is to include information to `docker info`, but we also (have to) do a bunch of local work to collect additional information; https://github.com/moby/moby/blob/460b4aebdf81512a3ea37c2a65826b890427537d/daemon/info_unix.go#L264-L313 wondering if those are parts that should eventually be handled by rootlesskit (and returned by the `Info` it returns) 🤔

**Comment by thaJeztah** [comment]
☝️ TBH; still a bit looking at the best direction to take there; the rootlesskit case is a bit "weird" because it's rootlesskit running the engine, and the engine itself doesn't "call" rootlesskit here. Still somewhat wondering what it would take to integrate the rootlesskit functionality in the daemon itself.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
cc @vvoland (for back porting); I _THINK_ we only need the last two commits (vendoring changes are effectively a "no-op" from a rootlesskit perspective.

**Comment by vvoland** [comment]
Opened a v25 backport.
Also wanted to open backports for v23/v24, but they're still on rootlesskit `v1.`: https://github.com/moby/moby/blob/c59307445500f3ccabeb39e85f4150bb2ff8269c/Dockerfile#L348

**Comment by thaJeztah** [comment]
Three's a pending one for v23.0, but it's "on hold";

- https://github.com/moby/moby/pull/47258

**Pull request merged**
