### PR TITLE
[19.03 backport] vendor: update opencontainers/selinux v1.3.1

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/moby/moby/pull/40546

full diff: https://github.com/opencontainers/selinux/compare/5215b1806f52b1fcc2070a8826c542c9d33cd3cf...v1.3.1

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by RobbKistler** [comment]
@thaJeztah I'm tracking down an SELinux issue in moby/moby somewhere between 19.03.5 and 19.03.8.  The full diff of the opencontainers is much larger than this vendoring change -- is that just because the vendoring only only pulling in a subset of the files?

**Comment by thaJeztah** [comment]
@robbkistler correct; `vndr` pulls in only the parts of a dependency that we use (granularity is per "directory" / "package"). Any part that's not pulled in, is not used in our code base

**Comment by thaJeztah** [comment]
if you install an older version of the engine (and/or containerd+runc) the issue doesn't reproduce? It's also possible things changed in the containers-selinux package (we've had issues with that in the past)

**Comment by thaJeztah** [comment]
@RobbKistler I think your question relates to https://github.com/moby/moby/issues/40944, let's continue there

**Pull request merged**
