### PR TITLE
Windows: Refactor execdriver.Command

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This refactors the execdriver Command structure into common and platform specific pieces (and also gets rid of a number of TODO Windows as a result).

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Rebased

**Comment by jhowardmsft** [comment]
@LK4D4 @crosbymichael Guys - are you OK with this design?

**Comment by jhowardmsft** [comment]
Rebased.

**Comment by thaJeztah** [comment]
ping @LK4D4 @crosbymichael PTAL

**Comment by jhowardmsft** [comment]
Rebased

**Comment by jhowardmsft** [comment]
Rebased

**Comment by calavera** [comment]
This looks much better structured to me. I'm going to move it to code review. :+1:

**Comment by LK4D4** [comment]
LGTM

**Comment by calavera** [comment]
LGTM. Waiting on CI to merge.

**Pull request merged**
