### PR TITLE
Resolve image

### PR DESCRIPTION
**Pull request by sudohikumar**
**- Create container doesn't take care of the image id. Hence, if we pass image id, it will fail to fetch (after trying to fetch from docker hub) and then will error out. **

**- If we pass image id, we resolve that to the image name and then pass it to function.**

**- Description for the changelog**
It's basically the fix for this command
`docker run -d a123456`
where, `a123456` is the image id which is locally present. This code will now resolve this image id and return the image name. 

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by cpuguy83** [comment]
I would expect this to be done on the daemon rather than the client.

**Comment by justsimplify** [comment]
> I would expect this to be done on the daemon rather than the client.

@cpuguy83 : 

You mean docker daemon.

Context to issue: 

We got this issue when I was working on this library. I was trying to pass `image id` and it was trying to fetch the same as the library treated the `id` as `image name`. So, it was trying to fetch this from `docker hub` eventually erroring out.

**Comment by thaJeztah** [comment]
I think this is expected, because we don't match on ID _prefixes_ for images; matching by prefix could lead to (e.g.) matching `db` prefix with a `dbeabc12345` ID, if there's also a `db` image, which would make it ambiguous.


You can run with the full ID though;

```bash
docker image ls --no-trunc

REPOSITORY                                 TAG                    IMAGE ID            CREATED             SIZE
busybox                                    latest                 sha256:be5888e67be651f1fbb59006f0fd791b44ed3fceaa6323ab4e37d5928874345a   3 weeks ago         1.22MB
```

```bash
docker run -it --rm sha256:be5888e67be651f1fbb59006f0fd791b44ed3fceaa6323ab4e37d5928874345a sh -c 'echo foo'
foo

# or, without sha256
docker run -it --rm be5888e67be651f1fbb59006f0fd791b44ed3fceaa6323ab4e37d5928874345a sh -c 'echo foo'
foo
```

We should definitely _not_ combine image ID with `:tag`, as they're different things

**Comment by justsimplify** [comment]
@thaJeztah :



> I think this is expected, because we don't match on ID _prefixes_ for images; matching by prefix could lead to (e.g.) matching `db` prefix with a `dbeabc12345` ID, if there's also a `db` image, which would make it ambiguous.

> We should definitely _not_ combine image ID with `:tag`, as they're different things

Valid points.
- This PR was intended for the use case to create container with `image id`. So, we need some identifier to tell the function that it's an image. Will try to fix that.
- `tag` is incorporated because I thought of following scenarios if we use to create containers.
  - `<image-id>:<custom-tag>`
  - `<image-id>` by default it should fetch latest.
  - `<image-name>` same here and should fetch latest.
  - `<image-name>:<custom-tag>`

I can work on this separation though.

**Comment by thaJeztah** [comment]
> tag is incorporated because I thought of following scenarios if we use to create containers.

No, a `tag` cannot be used separate from the full image reference that it was created for.  For example;

When you;

```bash
docker pull busybox
```

"behind the scenes", this is translated to a fully qualified image reference (for historic reasons, the default registry is `docker.io/library`, because Docker Hub used to be the only registry that existed); you can see that reference if you pull the image;

```bash
docker pull busybox

Using default tag: latest
latest: Pulling from library/busybox
Digest: sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
```

If tags would be used separately, the following could happen;

Tag the busybox image under two different image names, with tags:

```bash
docker tag busybox somename:one
docker tag busybox someothername:two
```

The busybox image now has three images/tags associated:

```bash
docker image inspect --format '{{ json .RepoTags }}'  busybox | jq .

[
  "busybox:latest",
  "somename:one",
  "someothername:two"
]
```

- tag `one` is only applicable to image `somename`
- tag `two` is only applicable to image `someothername`
- tag `latest` only to image `busybox`

You wouldn't want `docker run busybox:two` to work, or `someothername:one`

**Comment by justsimplify** [comment]
So, I guess I need to put in more detailed info.

So, we have made a cli tool which provides a simulation feature like a deployment environment.

This simulation feature is provided using this library.

So, what users do is they can do docker build locally and using that image, they start the container using our cli tool.

But sometimes, people tend to give image id rather than image name because they are used to `docker run <image id>` command as well. 

Hence, when we pass those parameters to `ContainerCreate` function which is the image id, it first checks the existence of local image name which is equal to the image id provided.

Assuming non-collision scenario, as the image name is invalid (because it was image id), it will try to fetch from docker hub and if that also fails, it will throw error as failed to fetch that image.

So, in gist, the issue is referencing to local images. If we provide local image id rather than image name, it errors out.

I guess that clarifies the issue.

**Comment by cpuguy83** [comment]
What I mean here is that the container create endpoint in dockerd should be able to check if an image ID was used.

@thaJeztah re: prefix matching, in this case we would need to error out if the results are ambiguous (ie. more than 1 match).

**Comment by justsimplify** [comment]
> What I mean here is that the container create endpoint in dockerd should be able to check if an image ID was used.

Let me check on this as when we using this library, it was erroring out and not resolving the image IDs.

**Comment by justsimplify** [comment]
Ok yeah. More debugging in our code says this was our fault. 
Apologies. :)

**Pull request closed without merging**
