### PR TITLE
WIP depend on docker-selinux for centos-7+ for docker-engine-1.12.x

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Changed the dependency in the docker-engine RPM built for CentOS to depend on `docker-selinux`. This PR fixes issue #28406.

**- How I did it**

Added a conditional `Requires` in the spec file. Also refactored the `hack/make/build-rpm` to only build a `docker-engine-selinux` package if there exists a specific selinux policy directory in the `contrib` dir. In doing so, found that the `contrib/selinux` policy dir is only used by `fedora-23` so renamed that policy dir.

Note: this changes the default behaviour of building RPMs from using a generic selinux policy to only using one for the specificy distro version.

**- How to verify it**

Build a docker-engine-selinux centos-7 RPM package and install on RHEL7.3 with selinux enabled:
```
$ make DOCKER_BUILD_PKGS=centos-7 rpm
```

Should also make sure this works on CentOS7.2 with selinux enabled because CentOS7.3 is not released yet.

**- Description for the changelog**

Use the selinux policy provided by `docker-selinux` on CentOS.

**- A picture of a cute animal (not mandatory but encouraged)**

🐀

### CODE REVIEW

**Comment by runcom** [comment]
SGTM (I'll fully test this out tomorrow probably)

**Comment by andrewhsu** [comment]
The good thing is I can get this RPM built and installed on centos-7. The not-so-good is I cannot install on rhel-7.3 because `docker-selinux` is not provided by the repos enabled by default. Have to enable all repos to get this installed on rhel-7.3:
```
$ sudo yum -y --enablerepo='*' install docker-engine-1.12.*
```

**Comment by runcom** [comment]
@andrewhsu I believe only the `extras` repo is needed (or was it the `optional`?) - well either of those

**Comment by andrewhsu** [comment]
Looks like centos-7 has extras enabled by default so the `docker-selinux` dep can be satisfied:
```
$ docker run --rm --entrypoint=/usr/bin/yum centos:7 repolist
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirrors.evowise.com
 * extras: mirror.tocici.com
 * updates: mirror.team-cymru.org
repo id                             repo name                             status
base/7/x86_64                       CentOS-7 - Base                       9007
extras/7/x86_64                     CentOS-7 - Extras                      393
updates/7/x86_64                    CentOS-7 - Updates                    2560
repolist: 11960
```

However, default repo setup of AWS EC2 of RHEL7.3 does not have extras:
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
$ sudo yum repolist
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
repo id                                                                                                repo name                                                                                                             status
rhui-REGION-client-config-server-7/x86_64                                                              Red Hat Update Infrastructure 2.0 Client Configuration Server 7                                                            6
rhui-REGION-rhel-server-releases/7Server/x86_64                                                        Red Hat Enterprise Linux Server 7 (RPMs)                                                                              13,307
rhui-REGION-rhel-server-rh-common/7Server/x86_64                                                       Red Hat Enterprise Linux Server 7 RH Common (RPMs)                                                                       209
repolist: 13,522
```

**Comment by andrewhsu** [comment]
Went with the lesser of the two.

**Pull request closed without merging**
