### PR TITLE
Dockerfile*: bump Go to 1.7.5

### PR DESCRIPTION
**Pull request by unclejack**
**- What I did**
I've bumped the Go version to 1.7.5.

**- How I did it**
I've edited all the relevant files.

**- How to verify it**
This can be done by taking a look at the changelog.

**- Description for the changelog**
Dockerfile*: bump Go to 1.7.5

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Review by justincormack — APPROVED** [review]

**Comment by unclejack** [comment]
https://jenkins.dockerproject.org/job/Docker-PRs-arm/358/console seems to have run into errors.

**Comment by tonistiigi** [comment]
Looked at some failed builds for arm-master. Found `TestSwarmPublishDuplicatePorts` also failing in https://jenkins.dockerproject.org/job/Docker-PRs-arm/359/console . Didn't see `TestLogsFollowSlowStdoutConsumer` but we've had trouble with this test before in #29030

**Comment by tiborvass** [comment]
@tonistiigi is the issue with master or with this PR ? If it is only with master I think we should merge this.

**Comment by tonistiigi** [comment]
@tiborvass As I wrote I found one case where one of the failed tests failed in master and the other test failed in another PR(although that pr also updates go). I would say it is likely that the problem is not in this PR but hard to be 100% certain.

**Pull request merged**
