### PR TITLE
Forbid client piping to tty enabled container

### PR DESCRIPTION
**Pull request by icecrime**
When a container is launched with `-t`, it is meaningless to connect its input to a client side pipe. This patch explicitly forbids:
- `docker run -t` with a redirected stdin (`echo test | docker run -ti busybox cat`)
- `docker exec -t` with a redirected stdin (`docker exec -ti container psql) < script.sql`)
- `docker attach` with a redirect stdin toward a tty enabled container

**Open question**: should this patch make it in a point release? As broken as it may be, I'm wondering if some people actual rely on this feature today.

Fixes #8015
Fixes #9476
Fixes #9545
Replaces #9492

### CODE REVIEW

**Comment by jeffbaier** [comment]
This patch has caused problems in my use case. I have a CoreOS cluster that I use for testing. I launch multiple docker containers using Fleet. Then I use the Docker API to send commands and read the output. https://docs.docker.com/reference/api/docker_remote_api_v1.14/#attach-to-a-container

This used to work fine, but now in Docker 1.4.1 the fleet service fails with the error `cannot enable tty mode on non tty input`. Below is an example service file that illustrates the issue.

```
[Unit]
Description=TestNode1

[Service]
TimeoutStartSec=5m
EnvironmentFile=/etc/environment
ExecStart=/usr/bin/docker run -it --name test1 --rm ubuntu:14.04 /bin/bash
ExecStop=/usr/bin/docker kill test1
```

The docker run command works fine if I run it manually, the problem is when trying to use Fleet. I am assuming systemd doesn't have a TTY or something and trips this error message.

**Comment by icecrime** [comment]
Sorry to hear that @jeffbaier. Can you tell us more about the use case? I don't really understand the meaning of launching `/bin/bash` without a tty.

**Comment by crosbymichael** [comment]
@icecrime lets open a new issue and make sure that we look into it before 1.5

**Comment by crosbymichael** [comment]
I opened #10121

**Pull request merged**
