### PR TITLE
Enhancements and improved consistency for various completions

### PR DESCRIPTION
**Pull request by albers**
### docker inspect changes
- #23614 enhances `docker inspect` to complete images, containers, networks, nodes, services, tasks, and volumes. 
- In #24119 I introduced enhanced completion functions for the new `swarm` commands. The existing completions for other items have not yet been adjusted.

In order to efficiently update bash completion for `docker inspect`, a preparing refactoring is required.
### Performance problems

Completion of containers currently works by enumarating **all** container IDs, then inspecting all corresponding containers and conditionally outputting some stuff. With `--format` and `--filter`, this can be done more efficiently.
## Changes
- make use of new CLI features, e.g. `--format` and `--filter`
- less completion functions that are customizable with options and environment variables
- move some low-level completion logic into the helper functions so that the primary completion functions are easier to understand
- do not modify global state: get rid of `cur="${cur##*=}` idioms
- easy debugging and development by introducing companion `__docker_<items>` functions for the `__docker_complete_<items>` functions

I did not apply all concepts to all functions, only in cases where they paid off.

@tianon , @jfrazelle PTAL. This one's a bit more complex.

### CODE REVIEW

**Comment by tianon** [comment]
I haven't tested it (and I think before merging it'd be good to have 1-2 people besides @albers test this a bit too), but I looked over the changes and they all look like improvements to me! :+1: :heart:

**Comment by albers** [comment]
ping @jessfraz Would you mind taking a look at this? It's a bit more complex and I fear nobody's gonna dare to accept it.

**Comment by albers** [comment]
rebased.

**Comment by albers** [comment]
This seems to be too big to review. I'll replace this with a series of smaller PRs.

**Pull request closed without merging**
