### PR TITLE
Fixed:go vetting warning unkeyed fields

### PR DESCRIPTION
**Pull request by lkml-likexu**
Signed-off-by: Aaron.L.Xu <liker.xu@foxmail.com>

**- What I did**

**- How I did it**

Introducing "go tool vet"

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Why didn't​ we detect them on CI?

**Comment by vdemeester** [comment]
@AkihiroSuda because we skip `*_test.go` files for `go vet` and `golint` 👼

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
Nice to have so LGTM 🐸

**Pull request merged**
