### PR TITLE
Add pids max in stats

### PR DESCRIPTION
**Pull request by cyphar**
This allows clients to display the current PIDs usage as a percentage
of total allocated resources in a container.

This depends on docker/engine-api#145.

bunni

/cc @jfrazelle @calavera

### CODE REVIEW

**Comment by calavera** [comment]
As I just mentioned in #21185, I'd rather not add more fields by default tbh. The stats output is looking more and more clogged every day.

**Comment by cyphar** [comment]
@calavera I'd be happy to write a PR for it if you like (I'm not sure how to make the column names nice though). Although, maybe we should model it after how `lsblk --output` does output formatting (you just list the names of the columns you want -- although this would mean we'd have to parse it manually).

**Comment by cyphar** [comment]
@calavera I've removed the update to the client, I've just added the daemon-side code. Still waiting on a bunch of vendors.

**Comment by cyphar** [comment]
/me is confused how this will work with all of the containerd integration. Specifically, I'm not sure how we'll know we can consume all of the JSON stuff we want to that comes in from runC.

**Comment by tonistiigi** [comment]
@cyphar You first need to add this support to containerd https://github.com/docker/containerd/blob/master/api/grpc/types/api.pb.go#L535 and then vendor in the modified api.

**Comment by thaJeztah** [comment]
@cyphar should we close this in the meantime?

**Comment by cyphar** [comment]
@thaJeztah Well, it's waiting on two open PRs in the other projects and vendor bumps. I'm not sure if we should close it (mainly because we'll forget about the PR in a week or two). :P

**Comment by thaJeztah** [comment]
ping @cyphar I see https://github.com/docker/docker/pull/21178 was merged :+1:

**Comment by cyphar** [comment]
I'm working on rebasing this, but it looks like I'll have to reimplement it.

**Comment by thaJeztah** [comment]
@cyphar yes, I think the current thought is to implement a `--format` option for `docker stats` and make the extra columns optional

**Comment by cyphar** [comment]
Yeah, I know. It's in my backlog of things to work on. But really, we can do API updates without changing the CLI -- the `--format` stuff can be done completely separately.

**Comment by thaJeztah** [comment]
@cyphar I'll close this for now as it's not mergable currently; happy to reopen once we have a `--format` flag and you reimplemnted this.

**Pull request closed without merging**
