### PR TITLE
Update docker/cli to 4c224a778638da8664b963d95948f0de8149a988

### PR DESCRIPTION
**Pull request by yongtang**
This fix update docker/cli to 4c224a778638da8664b963d95948f0de8149a988

This fix brings change of docker/cli#184 to docker, which is needed by moby/moby#30897

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Please hold merging - new integration tests should not depend on new  CLI features in docker, can we address this by using the API for tests?

**Comment by yongtang** [comment]
@thaJeztah @AkihiroSuda #30897 has been updated without the need to change the cmd (it uses the API for testing). Please take a look.

**Comment by cpuguy83** [comment]
Ok, let's close this since it's not what we want to do with the CLI.
Ultimately we want to provide a static client binary from the 17.06 docker release since we cannot build a client binary representing the 17.06 docker CLI (which is where we want to freeze it at) from the docker/cli repo.

**Pull request closed without merging**
