### PR TITLE
Add new maintainers

### PR DESCRIPTION
**Pull request by thaJeztah**
As voted on per e-mail, adding
new maintainers to the list

Welcome!

**\- A picture of a cute animal (not mandatory but encouraged)**

group-of-squid-audience

ping @docker/core-engine-maintainers, @dnephin @mlaventure @stevvooe @aluzzardi @vieux

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 👼

**Comment by jhowardmsft** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM :tada:

**Comment by vieux** [comment]
🎉

**Comment by stevvooe** [comment]
❤️

**Pull request merged**
