### PR TITLE
api/client: Allow for multi-line usage help

### PR DESCRIPTION
**Pull request by jlhawn**
Subcommands can provide multiple usage synopses.

### CODE REVIEW

**Comment by dmcgowan** [comment]
I don't see how this is used in the current code.

Maybe justify it more by linking to your use case https://github.com/docker/docker/pull/13171/files#diff-c943834b9f6589e94e6f3d2df975fd45R41 ?

**Comment by jlhawn** [comment]
@dmcgowan thanks. I'm looking to add this functionality for exactly that reason:

```
$ docker cp --help

Usage:  docker cp [OPTIONS] CONTAINER:PATH LOCALPATH|-
        docker cp [OPTIONS] LOCALPATH|- CONTAINER:PATH

Copy files/folders between a container and the local filesystem.

  --help=false       Print usage
```

**Comment by dmcgowan** [comment]
LGTM

ping @tibor @RichardScothern

**Comment by duglin** [comment]
Would love to get a testcase added but couldn't figure out what you'd test :-)
So, in the meantime, LGTM

**Comment by RichardScothern** [comment]
LGTM

**Comment by jlhawn** [comment]
ping @tiborvass @icecrime @jfrazelle @LK4D4 please review!

**Comment by icecrime** [comment]
Why? You have 3 LGTM already, just merge it.

**Comment by jlhawn** [comment]
@icecrime sorry, I wasn't sure how many I needed. Usually other people press the button for me :shipit:

**Pull request merged**
