### PR TITLE
ci: quote bash variable

### PR DESCRIPTION
**Pull request by tiborvass**
cc @vdemeester @tonistiigi

### CODE REVIEW

**Comment by vdemeester** [comment]
@tiborvass master and the `PRs` do not really execute the same script. I miss-configured master a tad yesterday, that's why it failed.. it should be back in order.

**Comment by tiborvass** [comment]
@vdemeester should be good now

**Comment by tiborvass** [comment]
OK just saw you changed the master jenkins config to fix it. So this PR is not fixing anything, just doing better quoting.

**Review by vdemeester — APPROVED** [review]
LGTM :taco:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
failures are flaky tests, and being tracked through https://github.com/moby/moby/issues/36501

```
21:32:45 ----------------------------------------------------------------------
21:32:45 FAIL: docker_api_swarm_service_test.go:32: DockerSwarmSuite.TestAPIServiceUpdatePort
21:32:45 
21:32:45 [d00845a694f6d] waiting for daemon to start
21:32:45 [d00845a694f6d] daemon started
21:32:45 
21:32:45 docker_api_swarm_service_test.go:38:
21:32:45     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
21:32:45 docker_utils_test.go:452:
21:32:45     c.Assert(v, checker, args...)
21:32:45 ... obtained int = 0
21:32:45 ... expected int = 1
21:32:45 
21:32:45 [d00845a694f6d] exiting daemon
21:32:57 
```

```
21:32:45 ----------------------------------------------------------------------
21:32:45 FAIL: docker_api_swarm_service_test.go:32: DockerSwarmSuite.TestAPIServiceUpdatePort
21:32:45 
21:32:45 [d00845a694f6d] waiting for daemon to start
21:32:45 [d00845a694f6d] daemon started
21:32:45 
21:32:45 docker_api_swarm_service_test.go:38:
21:32:45     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
21:32:45 docker_utils_test.go:452:
21:32:45     c.Assert(v, checker, args...)
21:32:45 ... obtained int = 0
21:32:45 ... expected int = 1
21:32:45 
21:32:45 [d00845a694f6d] exiting daemon
21:32:57 
```

**Pull request merged**
