### PR TITLE
Docker-engine-selinux should only relabel /var/lib/docker on initial …

### PR DESCRIPTION
**Pull request by rhatdan**
…install

Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
:heart: thanks @rhatdan!

ping @jfrazelle @ewindisch ptal

**Comment by cyphar** [comment]
@rhatdan I'm confused. Isn't this identical to #20333?

**Comment by thaJeztah** [comment]
hm, looks like a wrong push yes; I think there was different code in this PR previously

**Comment by rhatdan** [comment]
Oops looks like I hammered my previous push.  

Opened new pull  request here. https://github.com/docker/docker/pull/20353

**Comment by thaJeztah** [comment]
Haha, happens to the best of us (as proven above). Thanks!

**Pull request closed without merging**
