### PR TITLE
Add debug mode support for client

### PR DESCRIPTION
**Pull request by hqhq**
We actually have logrus.Debug usage on client side for a long time,
they seem never worked.

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Moving to design review, because this is not only a documentation change, it also contains changes to [pkg/mflag/flag.go](https://github.com/hqhq/docker/blob/hq_add_debug_for_client/pkg/mflag/flag.go)

IIRC, there has been a debate in the past to remove the `-D` flag, and use `--log-level=debug`, but not sure if that's the same thing that's proposed here?

For reference: https://github.com/docker/docker/pull/13221 and https://github.com/docker/docker/pull/11965

ping @duglin for removal of `-D` / `--debug`

and ping @calavera and @jfrazelle because Janky won't run because it thinks this is a docs-only PR!

**Comment by thaJeztah** [comment]
Manually starting Janky seemed to have worked for now

**Comment by duglin** [comment]
We may not need the code changes since -D and --debug do seem to work on the master.  Granted it could be due to @tiborvass's latest changes.  If so, I think just the doc edits would remain.

**Comment by hqhq** [comment]
@duglin What do you mean **-D and --debug do seem to work on the master**? I'm trying to enable it on client side, but now if I use it, I got error:
```
$ docker run -ti --rm -D ubuntu bash
flag provided but not defined: -D
See 'docker run --help'.
```

I know it's work on daemon side. Is the former approach supposed to support this flag on both daemon and client side, and was somehow broken now? I didn't dig the history.

**Comment by duglin** [comment]
@hqhq try `docker -D run ...`

**Comment by hqhq** [comment]
@duglin I see... then I think we don't need these docs changed either, because `-D` is in the common options which is already in `man docker`, so close it, thanks all.

**Pull request closed without merging**
