### PR TITLE
Container router

### PR DESCRIPTION
**Pull request by dongluochen**
Group container APIs and move them out of local.

### CODE REVIEW

**Comment by calavera** [comment]
This looks like the most pragmatic solution, but I keep coming back to this interface thinking that it has too many responsibilities. I know the underlying object has all those methods, but it might be a good oportunity to chop this interface down.

/cc @tiborvass because he's very interested in having a clear definition of this backend.

**Comment by MHBauer** [comment]
I have the same code in one of my branches. This doesn't really help anything because we still have a bunch of dependencies on daemon and builder to remove.

If I were to split it up by unix/windows, I would make a third BackendBase interface that has the common methods in it.

**Comment by dongluochen** [comment]
@MHBauer Right we still have dependencies on daemon, especially configuration. David suggests doing it in another step. It'd require more refactoring effort. 

We may also further divide the interfaces to make it more cohesive. /cc @tiborvass

**Comment by LK4D4** [comment]
Two almost identical interfaces look weird indeed.

**Comment by dongluochen** [comment]
@MHBauer, @LK4D4, @calavera I group Exec and Inspect functions into interfaces. Does this sound right to you? If yes I'll continue with other container functions.

**Comment by LK4D4** [comment]
Hmm, I'd prefer to keep them in same package. Also I'd prefer to keep one combined interface now, like
```
type Backend interface {
    ExecBackend
...
```
Also splitting routers doesn't sound like good plan for me.

**Comment by calavera** [comment]
> Also splitting routers doesn't sound like good plan for me.

It's a good plan for the long term, and it has very little implications in the code, you only need to add one like to add it to the server.

**Comment by MHBauer** [comment]
Agree with @LK4D4 on a combined interface of interfaces that are all in the same package. I might be able to give that a go tomorrow, but probably on Thursday.

**Comment by calavera** [comment]
I'm carrying this PR in https://github.com/docker/docker/pull/18201.

Please, take a look there. I'm closing this.

**Pull request closed without merging**
