### PR TITLE
logger: fix follow logs for max-file=1

### LINKED ISSUE #39235: 'docker logs -f' hangs on logfile rotation with --max-file=1
**Description**
`docker logs -f` stops/hangs when the logfile rotates and `max-file` is configured to 1.  
Increasing the `max-file` fixes this problem.

**Steps to reproduce the issue:**
1. Start a container with a low `max-size` and `max-file=1` that prints a lot of output:
```
docker run -d --name hello_loop --log-driver=json-file --log-opt max-size=1k --log-opt max-file=1 alpine /bin/ash -c 'while true; do echo "Hello"; sleep 1; done'
```
2. Follow the output of the container:
```
docker logs -f hello_loop
```

**Describe the results you received:**

The `docker logs -f hello_loop` command stops showing the container output (hangs), even if the actual container is still outputting lines (can be seen by accessing the .log file directly)

**Describe the results you expected:**

The `docker logs -f hello_loop` command shows `Hello` messages until the command is interrupted or the container is stopped.

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: WOLF-SERVER
ID: ENWT:3OUT:IXB6:VWQW:GRTZ:AOWZ:PKJN:2GAN:RLGK:UGO5:IBWU:USW7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Related Issues**

Amongst others:
#35332
#32038

Although in one of the linked issues it was mentioned that setting `max-file` to 1 
> is a bit of an edge case since it's weird to not retain some of the logs.

this is a bug in my eyes as this behavior is not documented anywhere (that I could find).  
If this behavior is to be expected, this should be documented accordingly.

### PR DESCRIPTION
**Pull request by kolyshkin**
In case jsonlogfile is used with `max-file=1` and `max-size` set,
the log rotation is not performed; instead, the log file is closed
and re-opened with `O_TRUNC`.

This situation is not handled by the log reader in follow mode,
leading to an issue of log reader being stuck forever.

This situation (file close/reopen) could be handled in `waitRead()`,
but fsnotify library chose to not listen to or deliver this event
(`IN_CLOSE_WRITE` in inotify lingo) as it's not portable,
see https://github.com/fsnotify/fsnotify/pull/252.

So, we have to handle this by checking the file size upon receiving
`io.EOF` from the log reader, and comparing the size with the one received
earlier. In case the new size is less than the old one, the file was
truncated and we need to seek to its beginning.

Fixes #39235. See the steps to verify in that issue.

### Description for the changelog
jsonfile logger: Fix lollow logs stuck when max-size is set and max-file=1

### CODE REVIEW

**Comment by kolyshkin** [comment]
Did some manual checking using
`cd integration-cli; go test -v -run TestDockerSuite/TestLogs .`

Got the same failures before and after the commit, meaning this PR is not breaking anything (still looking at those failures...)

**Comment by kolyshkin** [comment]
```
kir@kd:~/go/src/github.com/docker/docker/integration-cli$ go test -v -run TestDockerSuite/TestLogs .
INFO: Testing against a local daemon
=== RUN   TestDockerSuite
=== RUN   TestDockerSuite/TestLogsAPIContainerNotFound
=== RUN   TestDockerSuite/TestLogsAPIFollowEmptyOutput
=== RUN   TestDockerSuite/TestLogsAPINoStdoutNorStderr
=== RUN   TestDockerSuite/TestLogsAPIUntil
=== RUN   TestDockerSuite/TestLogsAPIUntilDefaultValue
=== RUN   TestDockerSuite/TestLogsAPIUntilFutureFollow
=== RUN   TestDockerSuite/TestLogsAPIWithStdout
=== RUN   TestDockerSuite/TestLogsCLIContainerNotFound
=== RUN   TestDockerSuite/TestLogsContainerBiggerThanPage
=== RUN   TestDockerSuite/TestLogsContainerMuchBiggerThanPage
=== RUN   TestDockerSuite/TestLogsContainerSmallerThanPage
=== RUN   TestDockerSuite/TestLogsFollowGoroutinesNoOutput
=== RUN   TestDockerSuite/TestLogsFollowGoroutinesWithStdout
=== RUN   TestDockerSuite/TestLogsFollowSlowStdoutConsumer
=== RUN   TestDockerSuite/TestLogsFollowStopped
=== RUN   TestDockerSuite/TestLogsSeparateStderr
=== RUN   TestDockerSuite/TestLogsSince
=== RUN   TestDockerSuite/TestLogsSinceFutureFollow
=== RUN   TestDockerSuite/TestLogsStderrInStdout
=== RUN   TestDockerSuite/TestLogsTail
=== RUN   TestDockerSuite/TestLogsTimestamps
=== RUN   TestDockerSuite/TestLogsWithDetails
--- PASS: TestDockerSuite (48.19s)
    --- PASS: TestDockerSuite/TestLogsAPIContainerNotFound (0.21s)
    --- PASS: TestDockerSuite/TestLogsAPIFollowEmptyOutput (1.17s)
    --- PASS: TestDockerSuite/TestLogsAPINoStdoutNorStderr (0.99s)
    --- PASS: TestDockerSuite/TestLogsAPIUntil (4.16s)
    --- PASS: TestDockerSuite/TestLogsAPIUntilDefaultValue (1.16s)
    --- PASS: TestDockerSuite/TestLogsAPIUntilFutureFollow (5.09s)
    --- PASS: TestDockerSuite/TestLogsAPIWithStdout (1.15s)
    --- PASS: TestDockerSuite/TestLogsCLIContainerNotFound (0.22s)
    --- PASS: TestDockerSuite/TestLogsContainerBiggerThanPage (1.14s)
    --- PASS: TestDockerSuite/TestLogsContainerMuchBiggerThanPage (1.33s)
    --- PASS: TestDockerSuite/TestLogsContainerSmallerThanPage (1.19s)
    --- PASS: TestDockerSuite/TestLogsFollowGoroutinesNoOutput (1.48s)
    --- PASS: TestDockerSuite/TestLogsFollowGoroutinesWithStdout (1.38s)
    --- PASS: TestDockerSuite/TestLogsFollowSlowStdoutConsumer (1.98s)
    --- PASS: TestDockerSuite/TestLogsFollowStopped (1.12s)
    --- PASS: TestDockerSuite/TestLogsSeparateStderr (1.10s)
    --- PASS: TestDockerSuite/TestLogsSince (7.13s)
    --- PASS: TestDockerSuite/TestLogsSinceFutureFollow (5.99s)
    --- PASS: TestDockerSuite/TestLogsStderrInStdout (1.13s)
    --- PASS: TestDockerSuite/TestLogsTail (1.36s)
    --- PASS: TestDockerSuite/TestLogsTimestamps (6.46s)
    --- PASS: TestDockerSuite/TestLogsWithDetails (1.03s)
PASS
ok  	github.com/docker/docker/integration-cli	48.238s
```

**Review by thaJeztah — APPROVED** [review]
SGTM

should we have a test for this?

**Comment by thaJeztah** [comment]
ah, I see your comment above; guess that means we can't add a test?

**Comment by thaJeztah** [comment]
@cpuguy83 ptal

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
I think a test that's actually testing the problem would be rather difficult.
Maybe if the logger code was instrumented for the test it could work but even then it still seems like it would be flaky.

**Pull request merged**
