### PR TITLE
Cleanup driver and graph db after stopping containers.

### LINKED ISSUE #13850: docker 1.7.0-rc2 cannot restart due to graph storage driver failed at Cleanup sometimes
Restart docker 1.7.0-rc2 has much higher failure rate comparing to previous version:

```
# docker version
Client version: 1.7.0-rc2
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 7ddecf7
OS/Arch (client): linux/amd64
Server version: 1.7.0-rc2
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 7ddecf7
OS/Arch (server): linux/amd64
```
```
# service docker restart
[ ok ] Stopping Docker: docker.
[FAIL] Starting Docker: docker failed!
```

The below is the output of 'docker info'
```
# docker info
Containers: 97
Images: 75
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 269
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy) (containerized)
CPUs: 1
Total Memory: 1.664 GiB
Name: e2e-test-dawnchen-minion-m6xr
ID: M5AZ:UIJ2:NYHP:XJYO:V6A7:6L5V:A6UE:7SOW:QZM3:PRSK:DQAG:AXBF
WARNING: No swap limit support
```

Checking docker.log, the failure is always caused by graph storage driver Cleanup(): device or resource busy, but every time, it complains a different container. 

```
time="2015-06-10T16:24:40.919554895Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.025876655Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.131932989Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.238114302Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.344047471Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.450212953Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.557326359Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.663467855Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.769463995Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.878903370Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:41.985180657Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.091416327Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.198276427Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.307627502Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.413813792Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.520339799Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.627273325Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.733724209Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.839447508Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:42.976536547Z" level=info msg="GET /containers/json"
time="2015-06-10T16:24:45.843043001Z" level=info msg="GET /version"
time="2015-06-10T16:24:50.094241684Z" level=info msg="Processing signal 'terminated'"
/usr/bin/docker already running.
time="2015-06-10T16:24:51.225044956Z" level=error msg="Error during graph storage driver.Cleanup(): device or resource busy"
time="2015-06-10T16:25:01.225632711Z" level=info msg="Container 531c6a22ec40f075cc135e846d88d556982974e5a1873c6eb07fb1a051086852 failed to exit within 10 seconds of SIGTERM - using the force"
```

### PR DESCRIPTION
**Pull request by calavera**
Fixes #13850

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by icecrime** [comment]
I'm giving this a quick, but partial, LGTM as we were discussing the fix together.

FYI this was a regression introduced by https://github.com/docker/docker/commit/531f4122bdcd4de289f613a5ef010f4c1989f098.

**Comment by calavera** [comment]
@icecrime I changed the order to be:

--> Containers --> Graph DB --> Driver

But I din't think it really matters. This is the clean output after killing the daemon:

```
INFO[0003] POST /v1.20/containers/63ecc23a6821acefd1fef381c73e1eab30bbd3c7290ebc65ed56ef9497319546/resize?h=22&w=252
^CINFO[0004] Processing signal 'interrupt'
INFO[0004] GET /v1.20/containers/63ecc23a6821acefd1fef381c73e1eab30bbd3c7290ebc65ed56ef9497319546/json
root@vagrant:/vagrant#
```

**Comment by jfrazelle** [comment]
im going to be this person but is there a way to have a daemon restart test

**Comment by jfrazelle** [comment]
so we can make sure it stays in the correct shutdown order to prevent regressions

**Comment by icecrime** [comment]
I'm afraid a test might be tricky: eventually both the daemon and containers properly stop, we just have a spurious log, which on my host happens with aufs but not with overlay :-/

**Comment by jfrazelle** [comment]
ah ya gotcha

**Comment by jfrazelle** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by icecrime** [comment]
Waiting on CI.

**Comment by jfrazelle** [comment]
cherry-picked

**Comment by jfrazelle** [comment]
cherrypicked

**Pull request merged**
