### PR TITLE
add insecure registry

### PR DESCRIPTION
**Pull request by azurezk**
Signed-off-by: Kun Zhang zkazure@gmail.com
#16578

Add a command to manage registry configuration without restart daemon.
Here I just implement add insecure registry. 
Example:  docker registry add --insecure-registry 172.10.0.3:5000
I can implement remove  insecure registry and also mirror registry management if this design is ok

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @NathanMcCauley @ewindisch @diogomonica ptal, looks like this is an alternative to https://github.com/docker/docker/issues/8887

**Comment by NathanMcCauley** [comment]
How is this better than #8887? This just seems like a less usable way to do the same thing.

**Comment by NathanMcCauley** [comment]
We could possibly reconsider --insecure-registry after the daemon has authn/authz from something like #15365. That would allow administrators to disable the feature if they didn't like it.

**Comment by NathanMcCauley** [comment]
I'm -1 on this for now.

**Comment by jfrazelle** [comment]
I'm going to go ahead and close then, thanks @azurezk for your contribution we hope you come back again after #15365 and thanks @NathanMcCauley for the review

**Pull request closed without merging**
