### PR TITLE
integration: get tests to compile again

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <tibor@docker.com>

https://github.com/moby/moby/pull/39137#issuecomment-501443309
relates to https://github.com/moby/moby/pull/39332

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Comment by tiborvass** [comment]
Ping @thaJeztah @arkodg

**Review by arkodg — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
argh, my bad

LGTM, thanks!

**Comment by thaJeztah** [comment]
test passed on experimental;

```
20:49:48 === RUN   TestDockerNetworkReConnect
20:49:52 --- PASS: TestDockerNetworkReConnect (3.28s)
```

I'm bringing this in

**Pull request merged**
