### PR TITLE
Tar up contents of --tmpfs dir ontop of tmpfs

### PR DESCRIPTION
**Pull request by rhatdan**
If I tmpfs mount over /etc, we want all of the contents in /etc to show up in
the container on the tmpfs.

Signed-off-by: Dan Walsh dwalsh@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
Not sure if this got dropped from the original pull request or accidently dropped.  Without it, the --tmpfs patch becomes a lot less attractive.

I can run an apache package in --read-only mode with --tmpfs /run with this patch, if I don't have this patch the /run/httpd will not exist in the tmpfs and the httpd will blow up.

**Comment by thaJeztah** [comment]
I think this was reverted in https://github.com/docker/docker/pull/19688

/cc @crosbymichael

**Comment by rhatdan** [comment]
It would have been nice if I was notified.

This is definitely a problem. As I stated in the other pull request, this breaks --read-only feature for running containers like httpd which depend on having a writable /run. Since the underlying image will have /run/httpd and httpd will blow up without it.

If the distribution does not have tar, the commands will not run. And do we have an example of a tar command that does not support these options?

Could we ship a gotar version in docker for this support?

@cpuguy83 Does docker volumes do something similar to this?

**Comment by cpuguy83** [comment]
Yes, volumes already do this. It just copies content from the container fs into the the mounted dir... but it does not use the hooks you have here.

**Comment by rhatdan** [comment]
What tool is it using?  Built-in Tar?

**Comment by cpuguy83** [comment]
https://github.com/docker/docker/blob/master/container/container_unix.go#L685

**Comment by rhatdan** [comment]
@cpuguy83 Sadly I can not use this with the plugins.

**Comment by rhatdan** [comment]
@crosbymichael what distro had a problem with the tar command?

**Comment by justincormack** [comment]
I am not clear about the security implications. It very much looks to me like the commands in the container are called with enough privileges to mount, so the tar command could remount without nosuid for example, by just running a container with a malicious tar binary. I havent tested this yet, but the exec is called immediately before and after the mount command without explicitly dropping caps, so it looks to me likely it has `cap_mount` although it is possible it doesn't.

**Comment by rhatdan** [comment]
This is docker executing the tar command from the host, not from inside of the container.  It is happening while docker is mounting up the containers images, so it needs SYS_ADMIN cap, if the tar on the host has been hacked, then your system is already done for.

docker is executing other host based commands to set the system up, as well as using glibc and other features.  I don't see how using the hosts tar is a security problem, anymore then using the hosts docker daemon.

**Comment by justincormack** [comment]
@rhatdan sorry I misunderstood it was the container's tar.

**Comment by rhatdan** [comment]
@crosbymichael Can we talk about this?  Do you see any way forward?

**Comment by icecrime** [comment]
Win2lin job is hitting the known race condition fixed in #20753.

**Comment by rhatdan** [comment]
@icecrime How does your comment relate to this pull request?

**Comment by icecrime** [comment]
@rhatdan Because the win2lin CI job was hitting a known race condition.

**Comment by rhatdan** [comment]
@icecrime caused by this patch?

**Comment by icecrime** [comment]
@rhatdan Nope :-)

**Comment by crosbymichael** [comment]
https://github.com/docker/docker/issues/15799
https://github.com/docker/docker/issues/339
https://github.com/docker/docker/issues/355
https://github.com/docker/docker/pull/934
https://github.com/docker/docker/issues/791

Those are a few of the issues in the past that we had to deal with whenever we shelled out to the tar binary.  bsdtar was one of the worse but also different flag compatibility and xattr support caused alot of inconsistencies for users.  This is why everything in docker uses the go tar package for tar based operations.  

Because this change is in the main code path for every container using tmpfs there is no way we are going to shell out to tar and risk issues popping up again.  

If there is a problem with RO and /run going RO then we should look into that issue.  tmpfs mounts should probably not be switched to RO if the rootfs is RO, that wouldn't make sense to me so maybe there is a bug or we overlooked something.   

But checking your example I have no problem with it, it works just fine:

```bash
docker run -ti --read-only --tmpfs /run alpine sh
/ # cd /run/
/run # touch hi
/run # ls
hi
```

**Comment by rhatdan** [comment]
The problem is if you are running httpd inside of a container it expects there to be an /run/httpd, If this does not exist httpd blows up.  So most people just do mkdir /run/httpd in the Dockerfile and everything works fine.  But if you later run 

docker run -d --tmpfs /run -v /var/log/myhttpd:/var/log/httpd:Z --read-only httpd
httpd will fail.

docker run -v /run  -v /var/log/myhttpd:/var/log/httpd:Z --read-only httpd

Works because docker volumes automatically tar up the contents of the underlying /run on the image into the volume.

Would you guys consider using a gotar executable that we could ship with docker?

**Comment by rhatdan** [comment]
I think the use of the system tar also is not the same as the bugs you show here.  I believe most of these are caused by using different tar executables for the import and export of content.  In the case of this patch we were using the system patch to tar up content off of an image stored on the system.  Then the system mounts a tmpfs for the system. Finally is uses the same tar to extract the content onto the tmpfs that it created.  

There is not a case where tar on the host creates content that is then explode by the tar in the container.  Or the tar on a different system then created the container.

**Comment by crosbymichael** [comment]
For the httpd image the fix is effortless and there is already a change in its init to clean up the pid file.  You just add a `mkdir -p /run/http` after this line.

https://github.com/docker-library/httpd/blob/bc72e42914f671e725d85a01ff037ce87c827f46/2.4/httpd-foreground#L5

This is the same contract that everything using /run fulfills.

**Comment by crwd-mivanov** [comment]
This change is not about `httpd`, but about easy way to have immutable containers

**Comment by justincormack** [comment]
@crwd-mivanov it is really easy to have immutable containers, just set them to be read only, and set up tmpfs mounts where needed. This clearly works but there is a question of whether it is enough or whether some files or directories need to be easily able to be fixed by bind mounting a mutable-but-not-persistent tmpfs over them. Back in the day it used to be quite hard to ru Linux distros from read only media, although for embedded cases and CD distros we have been for decades so most of the issues have actually been fixed now, and as @crosbymichael says there are few changes needed.

The issue seems to come down to the interface for hooks wants command line tools and it would be better if we could just use a code hook not an executable, hence the question about making a "go tar" just for this.

Personally I was happy with this without the tar functionality when it was merged, and having extra executables (or a `docker tar` use of docker) seems overkill, and as an ex embedded systems person I would tend to fix the images...

**Comment by rhatdan** [comment]
The idea is to allow someone (Admin) to do this without having to modify the container image itself.  Obviously you could modify any of the start up scripts to do this.  But in general you are causing a hacking problem where it is simple if the underlying directory just shows up in the tmpfs, (Like it does when you use builtin volumes).

In the example above I attempted to save the logs but I just as easily could have done

```
docker run --tmfs /run --tmpfs /var/log --read-only httpd
```

Or even

```
docker create --tmfs /run --tmpfs /var --read-only -t httpd1 httpd
docker start httpd1
```

Which would give me a container that every time I start it would have fresh content on it.  If I was concerned about my web service being hacked, I could simply restart the container.

I could setup even setup slightly different containers for each httpd and slightly modify the /etc content in memory.

```
docker create --tmfs /run --tmpfs /var --read-only --tmpfs /etc/httpd -t httpd1 httpd
docker start httpd1
```

The main thing here is I could take any container image off of docker.io and run it with tmpfs in readonly mode without me having to analyze what the application needs to run.

**Comment by thaJeztah** [comment]
> Which would give me a container that every time I start it would have fresh content on it. 

Why not start a fresh container if you want to start fresh?

>  If I was concerned about my web service being hacked, I could simply restart the container.

Wouldn't you want to analyze the logs in case of a hack instead of restarting it and wiping what happened? (note that httpd is logging to stderr/stdout so that logs are handled by the standard Docker logging mechanisms https://github.com/docker-library/httpd/blob/bc72e42914f671e725d85a01ff037ce87c827f46/2.4/Dockerfile#L56-L58)

**Comment by justincormack** [comment]
I don't quite understand, you always get a fresh container with the content if you run a new one. The main point of `--read-only` is to make sure you are not relying on unplanned mutability, and to give some protection against say malicious hacks modifying the container content. Any scheme that modified the `/etc/httpd` is already a customisation and can copy it from a bundled master copy somewhere else to set it up, it is not a normal use.

The main point of tmpfs mounts in read only systems was to get around systems trying to write various status files into `/etc` but nothing does that any more, those distro issues were fixed ages ago and things write in places they are supposed to.

**Comment by rhatdan** [comment]
There is costs to starting fresh containers, with tmpfs I don't have to start new ones and clean them up, I can always use the same one.  

@thaJeztah You talk like there is one httpd container image in the world.  I have seen lots of httpd containers that still write content to /var/log and /dev/log.  And I am just using httpd as my example, the same could be said about thousands of other images.   

The main goal of tmpfs in my opinion was for /run and /tmp, which most services are going to need to write to.  I am just using examples of other things you can play with using tmpfs if it tar's up the content underneath.

I believe that --read-only should be the default for containers in production, and --tmpfs is a great mechanism for us to handle this using --tmfs /run --tmpfs /tmp and maybe --tmpfs /var/tmp (Although in a container we should tell people to make /var/tmp and /tmp be the same thing). Without it copying up the undelying content, admins will not be able to run containers in this mode, and will just run in a less secure method without --read-only.

I also have a goal to get the same support that was added to "Local" volumes to work on tmpfs, if you don't think it should work on tmpfs then why do we have it for "local" volumes.

**Comment by cpuguy83** [comment]
The problem here with shelling out, imo, is:
1) relying on the host's userspace
2) allowing injection of unexpected behavior into the container startup (e.g. by replacing `tar` with a custom executable).

**Comment by rhatdan** [comment]
Well we do this with shelling out to other commands like lvm and devicemapper.

**Comment by rhatdan** [comment]
Also if someone is hacking the tar on the system they could just as simply hack the docker or hack into /var/lib/docker.

**Comment by thaJeztah** [comment]
Looks like this needs to be re-implemented now that containterd integrated; I'll close this because this cannot be merged

**Comment by rhatdan** [comment]
That is fine, since we now have a pull request to do this in runc, using native go code, which is probably where this belongs anyways.

**Comment by teohhanhui** [comment]
Just to provide an actual use case for this:

If I use a volume e.g. `/root` because I need to modify `.bashrc` at runtime, when I rebuild the image and recreate the container:

```shell
docker-compose build
docker-compose up -d
```

the old volume sticks around, and nothing is being copied over because the volume already exists. `tmpfs` would be perfect for this, if only it would retain the directory contents from the image...

**Comment by cpuguy83** [comment]
@teohhanhui 
```
$ docker volume create --opt device=tmpfs --opt type=tmpfs --opt o=size=10m --name tmpfstest
$ docker run -it --name test -v tmpfstest:/foo busybox
```

**Comment by teohhanhui** [comment]
@cpuguy83 What do you want me to test?

**Comment by cpuguy83** [comment]
@teohhanhui This covers your use-case in Docker 1.11.

**Comment by teohhanhui** [comment]
If anyone's looking this is now at opencontainers/runc#707

**Comment by teohhanhui** [comment]
@cpuguy83 Sorry, but I really do not understand how that covers my use case... My use case involves having all the contents of said directory from the image, every single time (which means changes should never be persisted).

**Comment by cpuguy83** [comment]
@teohhanhui Right, but tmpfs data is not persisted. The volume is still there, but once the tmpfs is unmounted the data is gone.

**Comment by teohhanhui** [comment]
@cpuguy83 I know that, but I cannot use a tmpfs volume because the original directory contents (from the image) are not copied over, which is what this PR is about...

**Comment by thaJeztah** [comment]
@teohhanhui this PR is about `--tmpfs`, the example @cpuguy83 gave is by using a regular *volume*, but passing it some options to use `tmpfs` (see `docker volume create ...`), in his example, the `--tmpfs` option is not used on `docker run`, so the contents of the container will be copied to the volume when the container is started (and the volume is empty)

**Comment by teohhanhui** [comment]
@thaJeztah Thanks for the explanation. Now I'm curious why `--tmpfs` can't just behave in the same intuitive way (transparently being translated into the `docker volume create ...` above, if I may call it that). But I'm sure there are technical reasons that I don't yet understand...

**Comment by crosbymichael** [comment]
@teohhanhui Hi!

The main reason is that we do not see `--tmpfs` as a volume.  From the beginning volumes in docker have been a way for people to decouple important data from their container.  If I run a database, that database should be writing data into a volume because it is important to me.

With `tmpfs`, if we say that it is a `volume` then it gives people a false sense of security that their data will actually be persisted and this is not true.  Its a different tool for a different usecase and actually a totally opposite usecase for volumes.  You use `tmpfs` when you DON'T want the data to be persisted between container starts and restarts and definitely not decoupled from the container and persisted independently like volumes are.

That is basically the reasoning behind why it is different and the semantics between volumes and tmpfs are there.  Its great for its usecases but shouldn't be used everywhere.

**Comment by rhatdan** [comment]
If we can get https://github.com/opencontainers/runc/pull/707 merged we get the behaviour you need.

**Comment by teohhanhui** [comment]
@crosbymichael Does following the instructions above from @cpuguy83 get any data persisted? I thought the data would be lost anyway since its tmpfs. If it results in no persistence of data then I don't see why it can't be an implementation detail that `--tmpfs` uses the "local" volume driver under the hood.

**Comment by cpuguy83** [comment]
@teohhanhui One thing, it still won't re-populate when the container using it is restarted.

**Comment by teohhanhui** [comment]
@cpuguy83 So if we can get it re-populated on every container startup then we don't need  the `tar` way,  is that correct? :smiley:

**Comment by cpuguy83** [comment]
@teohhanhui We aren't going to do that.
See @rhatdan's comment above about getting the behavior in runc.

**Comment by teohhanhui** [comment]
Now it's been moved to opencontainers/runc#845

**Comment by bsod90** [comment]
Is it possible to achieve similar behavior in 1.12, without waiting for runc patch to be merged?
Currently, if I run it with --tmpfs flag, content of my target directory is simply being wiped out and I'm getting empty tmpfs inside container.

**Pull request closed without merging**
