### PR TITLE
Clean redundant error message for export

### PR DESCRIPTION
**Pull request by WeiZhang555**
When execute `docker export -o path xxx` and path is a directory docker
has no privilege to write to, daemon will print lots of error logs that
most of them are duplicated and redundant.

This will remove unnecessary error logs and print only once.

For example, execute:

```
/$ docker export -o busybox.tar c31c528f50fb
open .docker_temp_504557079: permission denied
```

Before this, daemon log is follows:

```
ERRO[0022] Handler for GET /v1.23/containers/e525a395460c/export returned error: e525a395460c: write unix /var/run/docker.sock->@: write: broken pipe 
2016/02/19 17:12:28 http: multiple response.WriteHeader calls
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/bin/[ to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/bin/[[ to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/bin/acpid to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/bin/add-shell to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/bin/addgroup to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/bin/adduser to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/bin/adjtimex to tar: io: read/write on closed pipe 

<soooooo long logs>...

DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/var to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/var/spool to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/var/spool/mail to tar: io: read/write on closed pipe 
DEBU[0022] Can't add file /var/lib/docker/aufs/mnt/3d3ff60141efcf70dd7b96b0bba5b6a8852629a72858e8b1e894955536500ff1/var/www to tar: io: read/write on closed pipe 
DEBU[0022] Can't close tar writer: io: read/write on closed pipe
```

After:

```
ERRO[0017] Handler for GET /v1.23/containers/c31c528f50fb/export returned error: c31c528f50fb: write unix /var/run/docker.sock->@: write: broken pipe 
2016/02/19 18:49:59 http: multiple response.WriteHeader calls
ERRO[0017] Can't add file /var/lib/docker/aufs/mnt/e1508b07b7d57db0e86a9b2e7ac74e1e8774385683b6dc55a27bc85a29db11b5/bin/[ to tar: io: read/write on closed pipe 
ERRO[0017] Can't close tar writer: io: read/write on closed pipe
```

And this will stop writing tar streams to a closed pipe very early which will bring some performance benefits.

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can we make the logged error more descriptive? (Just wondering). ".... permission denied" is more descriptive to me (in logs as well) than "write: broken pipe" and "to tar: io: read/write on closed pipe"

**Comment by WeiZhang555** [comment]
@thaJeztah I think we can't, the `permission denied` error only happens on client side.
 The daemon will tar the container files and send the tar stream to client through http connection concurrently, then client will write the tar stream to a local postion. If client has no write permission, client wil report "...permission denied" and close the http connection; For the daemon, the error is "io failed because the pipe is broken", daemon won't have permission problem. 
So the "write: broke pipe" is real though it looks a little bit confusing on first sight. 

The idea behind this log change is that if the pipe/http connection is broken, the tar operation will lost its writing tunnel and there's no need to go on this operation, so we can stop this operation right now and no need to output more error logs.

:smile:

**Comment by thaJeztah** [comment]
@WeiZhang555 thanks for the clear explanation! Then this looks like the best we can do; I agree that cancelling the process is the right approach, so design +1 for me.

I'm moving this to code review

**Comment by WeiZhang555** [comment]
ping @vdemeester @cpuguy83 @calavera

**Comment by calavera** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Pull request merged**
