### PR TITLE
Vendor libnetwork v0.5.4

### LINKED ISSUE #19080: Incorrect entry in /etc/hosts updated when linked container is restarted
When /etc/hosts is updated after a linked container’s been restarted, entries prefixed with the restarted container name are updated with incorrect location.

How reproducible:
```
docker run \
    --name child \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker run \
    --name child-another \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker run \
    --name yet-another-child \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker run \
    --name parent \
    --link child \
    --link child-another \
    --link yet-another-child \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker exec -it parent cat /etc/hosts

docker restart child

docker exec -it parent cat /etc/hosts
```

Results:
```
> docker exec -it parent cat /etc/hosts
172.17.0.5	3140a59b2c38
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	child 87af5283f0ac
172.17.0.3	child-another a0b99361ea1d
172.17.0.4	yet-another-child b0b1f9c509a7
> docker restart child
child
> docker exec -it parent cat /etc/hosts
172.17.0.5	3140a59b2c38
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	child 87af5283f0ac
172.17.0.2	child-another a0b99361ea1d
172.17.0.4	yet-another-child b0b1f9c509a7
```

Expected: 
`172.17.0.3	child-another a0b99361ea1d` instead of `172.17.0.2	child-another a0b99361ea1d` after 'child' container has been restarted.

```
docker version: 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```
```
docker info:
Containers: 5
Images: 896
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-263518-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 32.6 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.79 GB
 Metadata Space Used: 54.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.093 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.861 GiB
Name: vagrant-ubuntu-trusty-64
ID: 7NIY:ZE4D:6CA5:HYJX:PWO6:OKVV:C4KT:ZDL4:ZZU4:BX5V:RZZP:AOOH
WARNING: No swap limit support
```

Running on VirtualBox

### PR DESCRIPTION
**Pull request by mavenugo**
## 0.5.4
- Removed the isNodeAlive protection when user forces an endpoint delete
## 0.5.3
- Bridge driver supporting internal network option
- Backend implementation to support "force" option to network disconnect
- Fixing a regex in etchosts package to fix docker/docker#19080

### CODE REVIEW

**Comment by LK4D4** [comment]
How about https://github.com/docker/docker/blob/master/VENDORING.md ? :)

**Comment by mavenugo** [comment]
> https://github.com/docker/docker/blob/master/VENDORING.md

@LK4D4 didnt see that one getting added :) ... will push a tag and get this in. thanks for the pointer.

**Comment by jfrazelle** [comment]
LGTM after tag is added :)

**Comment by mavenugo** [comment]
@LK4D4 @jfrazelle retroactively added CHANGELOG :) and updated the tags.
libnetwork will follow the process henceforth.

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
you rock LGTM

**Comment by vieux** [comment]
LGTM

**Comment by mavenugo** [comment]
thanks @calavera @jfrazelle. 
we have a small patch to be included to the vendor-in. Since this is not merged yet, I will update this PR with v0.5.4.

**Comment by vieux** [comment]
@mavenugo thanks :)

**Comment by mavenugo** [comment]
@vieux thanks for raising the flag. 
Updated to v0.5.4 now. We dont use `isNodeAlive()` any more when endpoint is force deleted.

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
