### PR TITLE
Support Docker Content Trust for plugins

### PR DESCRIPTION
**Pull request by dmcgowan**
Adds support for pushing and installing images using Docker Content Trust.

### CODE REVIEW

**Comment by dmcgowan** [comment]
Ping @cyli @riyazdf @tonistiigi

**Comment by tonistiigi** [comment]
Testing against hub+default notary doesn't seem successful. I keep getting 
```
DEBU[0013] received HTTP status 401 when requesting root.
you are not authorized to perform this operation: server returned 401.
```

It did look like I managed to push a plugin once and then couldn't pull it back, but now I can't even reproduce that. Wondering if it related to the scoping changes in auth service.

cc @riyazdf

**Comment by dmcgowan** [comment]
The request scope appears wrong to me, fixing now and can retry. Checked Notary code and I don't think it should require any changes to work.

**Comment by dmcgowan** [comment]
Pushed up fix, should be working now with Hub. There is still some duplication of code between Notary's setup and the image push/pull logic, for now I just made sure notary is doing the same thing, this could probably be cleaned up though.

**Comment by tonistiigi** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
