### PR TITLE
Migrate TestSecretInspect from integration-cli to api tests

### PR DESCRIPTION
**Pull request by yongtang**
This fix migrates TestSecretInspect from integration-cli to api tests

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by vdemeester — CHANGES_REQUESTED** [review]
Shouldn't this be in `integration/secret` ?

**Comment by yongtang** [comment]
@vdemeester Thanks for the review. As secret requires that swarm is up, I placed the secret test inside service directory so that the `newSwarm(t)` could be reused. It is possible to move secret test to a different directory though the `newSwarm(t)` may need to be copied as well.

**Comment by dnephin** [comment]
We could move `newSwarm` to an `integration/internal/swarm` package

**Comment by yongtang** [comment]
Thanks @vdemeester @dnephin for the review. The PR has been updated, with newSwarm moved to `integration/util/swarm/service.go`. The other usages of newSwarm in `integration/service` has also been updated. Please take a look and let me know if there are any issues.

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
Ping @vdemeester to take a look at the PR update.

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Pull request merged**
