### PR TITLE
Documenation update - articles/chef

### PR DESCRIPTION
**Pull request by someara**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Sorry for the delay @someara, thanks for contributing!

I've read through the changes here, and I'm wondering if we should include the examples at all; basically the examples repeat what's written on the cookbook page itself (and a bit more in-depth). Perhaps we should only mention that it's possible to use chef, and that there's a cookbook available (with a link)

@moxiegirl wdyt?

**Comment by someara** [comment]
In my experience, people are lazy about documentation and a short blurb goes a long way.
The current PR makes the Chef and Puppet articles roughly on par with each other.

PS: if you're worried about this getting out of sync with reality..  I can commit to making sure this stays up to date as the maintainer.

-s

**Comment by moxiegirl** [comment]
@someara  Thank you for the contribution. @thaJeztah Since we are short staffed in docs, these articles are kinda in the orphaned state. I'm not certain in the log run if they will continue to live here.  In the mean time,  I'm happy to take @someara up on his offer to maintain it.  

LGTM

**Comment by thaJeztah** [comment]
Thanks for looking, @moxiegirl 

> PS: if you're worried about this getting out of sync with reality.. I can commit to making sure this stays up to date as the maintainer.

works for me :smile: 

LGTM, and thanks @someara !

**Pull request merged**
