### PR TITLE
update urls for rpms

### PR DESCRIPTION
**Pull request by jessfraz**
ping @moxiegirl @thaJeztah

### CODE REVIEW

**Comment by jfrazelle** [comment]
once we get in https://github.com/docker/docker/pull/13680 we will never have to do this again lol

**Comment by calavera** [comment]
LGTM!

**Comment by thaJeztah** [comment]
LGTM (but haven't tested them)

> we will never have to do this again lol

:100:

**Comment by moxiegirl** [comment]
Tested. LGLTM

**Pull request merged**
