### PR TITLE
Version exec json check.

### LINKED ISSUE #17288: using docker client 1.8.3 to run `exec` against a docker daemon built from master fails
Client: 1.8.3

Daemon built from: 37da495d4cf30bebb17397dd9e103e6d3e74fe08

Command: `docker exec -it name bash`

Error:
```
Content-Type specified (text/plain) must be 'application/json'
```

### PR DESCRIPTION
**Pull request by calavera**
- Fixes #17288

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by calavera** [comment]
I added this to the milestone because it's a bug we introduced in master recently.

**Comment by cpuguy83** [comment]
I don't think this bug was in 1.9.0 unless we do indeed want to check for json in 1.9.

**Comment by runcom** [comment]
I remember the pr which introduced this check

**Comment by calavera** [comment]
@cpuguy83 you're right, this is not in 1.9.

**Comment by thaJeztah** [comment]
LGTM, thanks @calavera

**Comment by cpuguy83** [comment]
Need to bump the API version in the version check.

**Comment by thaJeztah** [comment]
oh cr*p you're right #etoomanyversions

**Comment by calavera** [comment]
fixed, thanks!

**Comment by cpuguy83** [comment]
Sorry, one more thing... Test for pre 1.22 behavior?
Also seems like there probably isn't any test ensuring json is The only content-type supported here going forward either.

**Comment by calavera** [comment]
I added a test to check that we keep backwards compatibility. 

> Also seems like there probably isn't any test ensuring json

@cpuguy83 it looks like we had already a test sending "application/json" content types to the start endpoint. It didn't fail before because the didn't check the content type, and it didn't fail when we forced it with `CheckJSON` because it was the expected content type.

All in all, this ensures we keep backwards compatibility and adds a test to verify it. We already have a test that checks the current valid behavior.

**Comment by cpuguy83** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
