### PR TITLE
Builder counts from 1

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Minor annoyance - the real world dev-ops guys isn't necessarily a computer programmer and generally counts from 1.

### CODE REVIEW

**Comment by icecrime** [comment]
Let the bikeshed begin! :-D LGTM

**Comment by jhowardmsft** [comment]
I'm wearing my tin foil hat for this one ;)

**Comment by duglin** [comment]
LGTM

To me when using the word "step", "step 0" is usually meant as a "prerequisite" type of thing, so that's why I think "step 1" as the first step in the Dockerfile makes more sense.

**Comment by thaJeztah** [comment]
Does this mean we can use one more layer on AUFS? :smile:

This will probably need docs changes btw, updating example output in some locations

**Comment by jhowardmsft** [comment]
Docs updated. They were inconsistent before - see reference\commandline\build.md L129 for example. Updated all to start from 1.

**Comment by duglin** [comment]
@jhowardmsft would you be willing to add a test to make sure no one moves it back to '0' w/o realizing that we purposely want it to start at '1'? I know we have existing tests that indirectly test for this but I'd prefer an explicit one.

**Comment by jhowardmsft** [comment]
Sure. I'll try to get to that tomorrow morning. On my list. Out of office for most of the rest of today.

**Comment by jhowardmsft** [comment]
@duglin - Added 'TestBuildStartsFromOne'

**Comment by duglin** [comment]
@jhowardmsft thanks!  still LGTM
ping @crosbymichael to make sure we're ok with this UX change.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
