### PR TITLE
Add `--initial-retries` for `HEALTHCHECK`

### LINKED ISSUE #26664: No possibility to specify grace period in the Healthcheck for service startup
This is follow up of these issues and changes:
https://github.com/docker/docker/issues/21142
https://github.com/docker/docker/pull/23218
https://github.com/docker/docker/issues/24396
https://github.com/docker/docker/pull/24856

So following the changes, in the original request 21142 there was a grace-period mentioned to let service startup longer. There was a workaround implemented using exit code 2 in 23218 pull-request. Later to simplify structure of the healthcheck the exit code 2 support was dropped. Now we end up in a situation that we can't have different timeout period for healthcheck during startup and during running state. 

Why this is critical: 
- In a swarm mode if a service reports unhealthy certain amount of time,  it will be killed and restarted.
- On the other hand if a service reports healthy while it is being unhealthy it could cause crashes of dependent services (they discover the main service is healthy and start loading).

There is another reason why this is a generic healthcheck problem. Let's put have an imaginary container that on startup loads 1TB from hard drive into the RAM, so we know that it could take up to 20 minutes initial load, though the proper healthcheck should be responding in 1 seconds and we would like to restart service after 30 seconds it's being unhealthy.

What's tried: 
- Obviously returning exit code 2 doesn't work 
- The solution mentioned in this comment https://github.com/docker/docker/issues/24396#issuecomment-233073059 definitely doesn't work, it hangs the whole docker service on the host machine. 

Solutions:
- I don't insist that exit-code 2 was a good solution, I would say better solution is to specify different number of retries count initial and after successful run. Let's say

```
HEALTHCHECK --interval=10s --startup-retries=60 --retries=3 --timeout=10s CMD /bin/bash -x /healthcheck.sh
```

That would allow service to startup for 10 minutes and be unhealthy for 30 seconds which is a valid case. Of course proper healthcheck to handle that situation is needed.

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raised in #26664 where it was not possible to have a grace period at the startup of the container.

**\- How I did it**

This fix adds `--initial-retries` for `HEALTHCHECK` so that container startup and normal running might have different grace period (retries).

**\- How to verify it**

This fix adds an integration test to cover the changes.

**\- Description for the changelog**

Add `--initial-retries` for `HEALTHCHECK`, so that it is possible to specify an initial grace period that is different from the normal grace period (`--retries`).

**\- A picture of a cute animal (not mandatory but encouraged)**

This fix fixes #26664.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Review by sebglon — COMMENTED** [review]
Why not add initial Timeout rather than initial-retries?

**Comment by thaJeztah** [comment]
We discussed this in the maintainers meeting, and while we think the health checks may need improvement, we are not sure about the right approach (yet). We prefer to wait one release to see what use cases people have, and issues they run into.

For that reason I close this _for now_

**Comment by sylvainmouquet** [comment]
Has the option --initial-retries been merged in docker release yet ?
It's not listed in the documentation.

One solution could be to define 2 differents kind of healthchecks : 
- one that would run until the container is healthy for the first time
- the other that would run after that.
It would allow us to fine-tune the healthchecks to our needs

**Comment by thaJeztah** [comment]
@sylvainmouquet docker 17.05 aded a ` --health-start-period` option, which allows you to specify a grace period for the service to start. This can be used (for example) if a service or container needs an initialisation period the first time it's started.

During this period, health checks still run (so you can monitor them), but they are not "counted" as failures, hence, the service/container is not marked "unhealthy", and not restarted/tasks are not re-created if health check fails. See the pull request that implemented it https://github.com/moby/moby/pull/28938, and the associated issues (https://github.com/moby/moby/issues/26498 and https://github.com/moby/moby/issues/26664) for more information.

**Pull request closed without merging**
