### PR TITLE
Carry #30602 : Bump go-units

### PR DESCRIPTION
**Pull request by vdemeester**
Carry #30602

/cc @thaJeztah @LK4D4 @cpuguy83 @tiborvass @icecrime 

---

To include  https://github.com/docker/go-units/pull/23

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM, I guess.
Hopefully this doesn't make the world burn for anyone 😈

**Comment by cpuguy83** [comment]
Haha, legit test failures.

**Comment by vdemeester** [comment]
Oh noooeess 😒

**Comment by vdemeester** [comment]
@cpuguy83 updated with a fix for the test :sweat_smile:

**Review by cpuguy83 — APPROVED** [review]
LGTM

I guess the world will burn a little.

**Comment by LK4D4** [comment]
@vdemeester 
```
17:09:17 
17:09:17 ----------------------------------------------------------------------
17:09:17 FAIL: docker_cli_ps_test.go:145: DockerSuite.TestPsListContainersSize
17:09:17 
17:09:17 docker_cli_ps_test.go:155:
17:09:17     c.Assert(err, checker.IsNil)
17:09:17 ... value *strconv.NumError = &strconv.NumError{Func:"ParseInt", Num:"0B", Err:(*errors.errorString)(0xc420014150)} ("strconv.ParseInt: parsing \"0B\": invalid syntax")
17:09:17 
17:09:18 
17:09:18 ----------------------------------------------------------------------
```

**Comment by vdemeester** [comment]
@LK4D4 arf, one last test failure :joy: :sweat_smile:

**Comment by vdemeester** [comment]
Updated 👼

**Review by thaJeztah — APPROVED** [review]
LGTM

if the world turns green

**Comment by AkihiroSuda** [comment]
LGTM and merging

**Pull request merged**
