### PR TITLE
Allow dev/shm size to be configurable in the native driver

### LINKED ISSUE #2606: bigger /dev/shm
I need to increase the size of /dev/shm which seems to be hardcoded to 64Mbyte 
in
lxc_template.go 

Is it correct that I have to change the value there and recompile docker to get a different value?
It would be helpful to be able to configure it per instnace, e.g some Databasesdo not install without enough shared memory.

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #2606

Right now it's hard coded to a -o option.  I don't know if this is the
best way to do it because the hard coding fs.system.shm.size=512m could
lead to duplication but I like being explicit and with this way we can
easily see all the commands that are supported by the drivers.

I'm up to suggestions on how to handle this?

Can be configured by `docker run -o native.fs.system.shm.size=512m busybox mount`

Docker-DCO-1.1-Signed-off-by: Michael Crosby michael@crosbymichael.com (github: crosbymichael)

### CODE REVIEW

**Comment by sridharlreddy** [comment]
Hello, is there any other way available to change the size of /dev/shm? Is there any changed planned in docker master branch?

**Comment by rhatdan** [comment]
Was there any movement on this?  Being discussed on a different github issue?  Our performance guys are running into this problem now with some of their tests.  And volume mounting in /dev/shm into the container basically breaks the security separation.

**Comment by jeremyeder** [comment]
The specific test is Linpack MPI which wants to shove a very large dataset into shared memory.

```
open("/dev/shm/Intel_MPI_LECnRQ", O_RDWR|O_CREAT|O_EXCL, 0600) = 12
lseek(12, 262847, SEEK_SET)             = 262847
write(12, "\0", 1)                      = -1 ENOSPC (No space left on device)
close(12)                               = 0
write(2, "Fatal error in MPI_Recv: Other M"..., 506) = 506
```

**Comment by rhatdan** [comment]
Sadly this seems to have fallen in importance.  We now are looking at adding additional tmpfs to the 
container (/run, /tmp, /dev/shm, /dev, /sys/fs/cgroup and /proc/kcore)

# docker run -ti -v /etc/localtime:/etc/localtime:rw -ti --rm fedora mount | grep tmpfs
tmpfs on /dev type tmpfs (rw,nosuid,context="system_u:object_r:svirt_sandbox_file_t:s0:c785,c819",mode=755)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c785,c819",size=65536k)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c785,c819")
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c785,c819")
tmpfs on /sys/fs/cgroup type tmpfs (rw,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c785,c819")
tmpfs on /proc/kcore type tmpfs (rw,nosuid,context="system_u:object_r:svirt_sandbox_file_t:s0:c785,c819",mode=755)

If we want to control the amount of memory available on these tmfs we need a mechansm to specify this per mount point from the CLI, or from the daemon config.

**Pull request closed without merging**
