### PR TITLE
Update "download-frozen-image.sh" with Bash 3 support for msysGit

### PR DESCRIPTION
**Pull request by tianon**
This uses a bit of on-disk state in our export directory to emulate our associative array for generating the "repositories" JSON file.

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
@jfrazelle we finally got it _working_?? :dancer:

**Comment by jfrazelle** [comment]
i took out the pulls to test https://jenkins.dockerproject.com/job/Windows-PRs/241/console

**Comment by jfrazelle** [comment]
seems to work to me :D

**Pull request merged**
