### PR TITLE
Fuxpavel docs typo fix

### PR DESCRIPTION
**Pull request by fuxpavel**

### CODE REVIEW

**Comment by SvenDowideit** [comment]
and could you please squash this into a single commit?

otherwise, LGTM

**Comment by ahmetalpbalkan** [comment]
@fuxpavel is it worth backporting this to older versions of the docs as well (I'm assuming they're not frozen forever for typo fixes)?

**Comment by moxiegirl** [comment]
@fuxpavel If you are willing to go further, let us know. Otherwise I'm happy to close and carry this work for you.

**Comment by fuxpavel** [comment]
I will fix it today, sorry didn't see the message.

**Comment by LK4D4** [comment]
@moxiegirl I don't know if it was fixed, but makes sense to carry.

**Comment by moxiegirl** [comment]
@fuxpavel this was fixed in the docker_remote_api_v1.19.md file on master a few days ago. The .17 problem still exists.  I'll carry it in a another PR.

**Pull request closed without merging**
