### PR TITLE
fix daemon won't start bug caused by daemon.json and cli flags duplications

### PR DESCRIPTION
**Pull request by AntaresS**
**- What I did**
- bug fix for daemon refusing to start when `runtimes` field defined in `daemon.json` file as well as
`
--containerd=<containerd address> --default-runtime=<name> --add-runtime=<runtime>
`
passed from dockerd cli flag.
- add `skipDuplicates` in `daemon.go` in order to allow some duplicated configurations defined in both config file and cli flag to be merged 

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Signed-off-by: Anda Xu <anda.xu@docker.com>

### CODE REVIEW

**Comment by AntaresS** [comment]
cc @crosbymichael @andrewhsu

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
This error message was added at the time to prevent conflicting options; with this change; if both a cli-option is set, and a `daemon.json` is present, which configuration will be used? Does one override the other, or are configurations merged?

**Comment by AntaresS** [comment]
@thaJeztah They will be merged together if both passed form cli and config file. this pr is just trying to resolve the conflict of `runtimes` option which is a map of slice. For other conflicts the error will still be returned.

**Review by thaJeztah — APPROVED** [review]
LGTM

@AntaresS would be good to have a test in a follow-up

**Pull request merged**
