### PR TITLE
Improve test daemon logging

### PR DESCRIPTION
**Pull request by cpuguy83**
1. On failed start tail the daemon logs
2. Exposes generic tailing functions to make test debugging simpler

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
close/reopen to trigger CI (logs were pruned)

**Comment by cpuguy83** [comment]
Rebased this.

**Review by thaJeztah — APPROVED** [review]
still LGTM

@neersighted @corhere ptal

**Review by neersighted — APPROVED** [review]

**Pull request merged**
