### PR TITLE
Remove PortSpecs from Config

### PR DESCRIPTION
**Pull request by runcom**
Given it's deprecated since almost a year, but I'm not totally sure not knowing the entire history

ping @tiborvass @LK4D4 @duglin @cpuguy83 

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by thaJeztah** [comment]
The "deprecated" comment looks to be added as part of https://github.com/docker/docker/commit/6393c38339e11b4a099a460ecf46bb5cafc4283b, which is pre 1.0 release, but that's all I know :)

**Comment by LK4D4** [comment]
Lol, LGTM

**Comment by calavera** [comment]
LGTM. Moving to docs review.

**Comment by thaJeztah** [comment]
docs LGTM

HOWEVER, depending on if this will be in 1.7 or 1.8, the docs may need to be moved to the v1.20 API

If this **does** go into 1.7, the "bump API to v1.20 PR will need to be updated

**Comment by thaJeztah** [comment]
ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by jamtur01** [comment]
LGTM

**Comment by runcom** [comment]
ping @calavera I've rebased this one as well :)

**Pull request merged**
