### PR TITLE
Simplify and fix MkdirAll usage

### PR DESCRIPTION
**Pull request by kolyshkin**
Please review, this looks somewhat important to me as it the bug can cover some non-trivial later errors.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Here's an example
http://play.golang.org/p/xcuYZ1YtyZ

**Comment by duglin** [comment]
please squash your commits down to one

**Comment by kolyshkin** [comment]
@duglin I did a separate commit for the specific aufs case as it's not as trivial as others and deserves a separate changelog (as I presumably change the code logic, unlike in all other cases).

**Comment by LK4D4** [comment]
I think aufs code is ok with removed check.
LGTM

**Comment by calavera** [comment]
I don't think the aufs case is much more special than the other ones. We always want to fail if there is an error, and as you say, checking if it already exists is not correct. We don't need to check if the path is a directory either, in that case, MkdirAll doesn't fail.

Can you please squash those commits?

**Comment by kolyshkin** [comment]
@calavera done

**Comment by duglin** [comment]
LGTM just waiting on janky

**Comment by tiborvass** [comment]
LGTM

**Comment by kolyshkin** [comment]
Seems like some internal error with janky, I heard there were some problems with CI lately, maybe @jfrazelle can take a look?

**Comment by tiborvass** [comment]
@kolyshkin she is already, no need to ping her too much :) (guilty too)

**Pull request merged**
