### PR TITLE
Allow mount type npipe on service/stack

### PR DESCRIPTION
**Pull request by olljanat**
**- What I did**
Added support named pipes support to cluster executor.

**- How I did it**
Added npipe type same way than it is added to engine on https://github.com/moby/moby/pull/33852

**- How to verify it**
1. Create service to Windows using Windows mounting format:
```
docker service create --name windows --mount 'type=npipe,source=\\.\pipe\docker_engine,destination=\\.\pipe\docker_engine' microsoft/nanoserver:1803
```

2. Deploy test stack using type=npipe:
```
version: "3.3"
services:
  web:
    image: ollijanatuinen/portainer:windows1803-amd64-npipe-3
    ports:
      - "9000:9000"
    networks:
      - test
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine

networks:
  test:
    driver: overlay
```

**- Description for the changelog**
- Added npipe protocol to SwarmKit side on: https://github.com/docker/swarmkit/pull/2691
- Added MountTypeNamedPipe cluster executor on 1b03440 (that makes docker service create command working)
- Added type=npipe support to stack files on https://github.com/docker/cli/pull/1195

Fixes: #34795

### CODE REVIEW

**Comment by thaJeztah** [comment]
The DNS lookup failures on s390x are known, and are being investigated; may be something with the kernel configuration on the s390x and powerpc machines (a reboot of those machines will fix that) 

```
07:55:14 W: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/stretch/InRelease  Could not resolve 'cdn-fastly.deb.debian.org'
07:55:14 W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Could not resolve 'security.debian.org'
07:55:14 W: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/stretch-updates/InRelease  Could not resolve 'cdn-fastly.deb.debian.org'
07:55:14 W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by thaJeztah** [comment]
Haven't seen this one before I think; https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/21347/console, could be related to the changes in this PR?

```
08:31:49 PANIC: docker_api_containers_test.go:1705: DockerSuite.TestContainersAPICreateMountsValidation
08:31:49 
08:31:49 case 0
08:31:49 case 1
08:31:49 case 2
08:31:49 case 3
08:31:49 case 4
08:31:49 case 5
08:31:49 case 6
08:31:49 case 7
08:31:49 case 8
08:31:49 ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x458341)
08:31:49 
08:31:49 d:/CI/CI-1e14ec04c/go/src/runtime/asm_amd64.s:573
08:31:49   in call32
08:31:49 d:/CI/CI-1e14ec04c/go/src/runtime/panic.go:502
08:31:49   in gopanic
08:31:49 d:/CI/CI-1e14ec04c/go/src/runtime/panic.go:63
08:31:49   in panicmem
08:31:49 d:/CI/CI-1e14ec04c/go/src/runtime/signal_windows.go:167
08:31:49   in sigpanic
08:31:49 docker_api_containers_test.go:1894
08:31:49   in DockerSuite.TestContainersAPICreateMountsValidation
08:31:49 d:/CI/CI-1e14ec04c/go/src/runtime/asm_amd64.s:573
08:31:49   in call32
08:31:49 d:/CI/CI-1e14ec04c/go/src/reflect/value.go:447
08:31:49   in Value.call
08:31:49 d:/CI/CI-1e14ec04c/go/src/reflect/value.go:308
08:31:49   in Value.Call
08:31:49 c:/gopath/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:816
08:31:49   in suiteRunner.forkTest.func1
08:31:49 c:/gopath/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:672
08:31:49   in suiteRunner.forkCall.func1
08:31:49 d:/CI/CI-1e14ec04c/go/src/runtime/asm_amd64.s:2361
08:31:49
```

**Comment by olljanat** [comment]
@thaJeztah ok. thanks, now I know which ones to focus and which not.

**Comment by cpuguy83** [comment]
I think I would prefer having a proper type for this, support for this is already in the moby API's at least. Just need to add to swarmkit.

For reference https://github.com/moby/moby/blob/master/api/types/mount/mount.go#L19

**Comment by olljanat** [comment]
@cpuguy83 true. I noticed same and commented to original issue https://github.com/moby/moby/issues/34795#issuecomment-403043559

I'm just looking for it :)

**Comment by olljanat** [comment]
Modified solution to use MountTypeNamedPipe.

Now all envs gives error
```
daemon/cluster/executor/container/validate.go:35:8: undefined: api.MountTypeNamedPipe
```
which is valid until https://github.com/docker/swarmkit/pull/2691 is merged.

**Comment by olljanat** [comment]
@thaJeztah how I can actually test to build this one with https://github.com/docker/swarmkit/pull/2691 ?
I can see that there is lot of "bump vendor" messages on git history but I didn't find guide how to do that on my local env.

**Comment by olljanat** [comment]
@cpuguy83 can you look that this now is implemented like you wanted and maybe help to get someone to review swarmkit and cli sides too?

**Comment by olljanat** [comment]
@cpuguy83 now PR to swarmkit have been merged and I included vendor update for it to this PR.

@vdemeester I also tried to include cli tests on

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
SGTM :tiger: 
cc @johnstep @jhowardmsft

**Comment by olljanat** [comment]
I noticed that swarmkit was updated to needed level on PR #3790 so I dropped it from this PR.

@thaJeztah / @johnstep / @jhowardmsft can you trigger rebuild for these failing builds (they looks failing to some some issue which is not caused by this PR) and review / do merging (or what actually are next step) ?

**Comment by yongtang** [comment]
Looks like all test passed so merge.

**Pull request merged**
