### PR TITLE
daemon/logger: refactor followLogs and replace flaky TestFollowLogsHandleDecodeErr

### PR DESCRIPTION
**Pull request by kzys**
**- What I did**

This PR refactors followLogs and replaces flaky TestFollowLogsHandleDecodeErr by adding a small more focused test.

**- How I did it**

The first commit is refactoring. The second commit is removing the flaky test and adding a new one.

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
p05qznn1

(from https://www.bbc.co.uk/programmes/p05rkdmp)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Failure on windows looks like a flaky test; https://github.com/moby/moby/issues/38521 (I'll kick ci)

```
 === FAIL: github.com/docker/docker/integration-cli TestDockerSuite/TestStartReturnCorrectExitCode (4.97s)
[2021-12-27T18:43:44.681Z]     docker_cli_start_test.go:209: assertion failed: expected an error, got nil
[2021-12-27T18:43:44.681Z]     --- FAIL: TestDockerSuite/TestStartReturnCorrectExitCode (4.97s)
```

**Review by thaJeztah — APPROVED** [review]
LGTM

@cpuguy83 @samuelkarp ptal

**Comment by thaJeztah** [comment]
(added cherry-pick label, as this is a follow-up / fix for changes in https://github.com/moby/moby/pull/43043)

**Comment by thaJeztah** [comment]
@cpuguy83 ptal 🤗

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
