### PR TITLE
Fix RefCounter count return

### PR DESCRIPTION
**Pull request by alfred-landrum**
Signed-off-by: Alfred Landrum <alfred.landrum@docker.com>

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
Nice catch! LGTM!

**Comment by LK4D4** [comment]
LGTM

**Comment by endophage** [comment]
Good catch. Idiomatic go would suggest moving the Unlock to immediately after the Lock and deferring it. That would also have solved the data race.

**Comment by thaJeztah** [comment]
@endophage depends on the code path; it can be cleaner, but there's a performance penalty for `defer`

**Comment by endophage** [comment]
And yet if we'd stuck with idiomatic go we wouldn't have had a race condition. They're also making continued improvements to its performance ("doubled in 1.8") https://github.com/golang/go/issues/14939

**Pull request merged**
