### PR TITLE
[carry 24499] Remove "Yes"/"No" and use "true"/"false" consistently in `docker info`

### PR DESCRIPTION
**Pull request by thaJeztah**
carry of #24499; makes labels more human readable, as suggested in https://github.com/docker/docker/pull/24499#issuecomment-231799725

closes #24499

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

**Comment by thaJeztah** [comment]
hold on; have to update docs

**Comment by thaJeztah** [comment]
done

**Comment by AkihiroSuda** [comment]
Thank you a lot for carrying this, lgtm (non-binding)

**Comment by vdemeester** [comment]
LGTM 🐹

**Comment by thaJeztah** [comment]
You're welcome @AkihiroSuda!

**Pull request merged**
