### PR TITLE
Add docker-py tests to drone.

### PR DESCRIPTION
**Pull request by jessfraz**
because yolo

### CODE REVIEW

**Comment by tianon** [comment]
:+1:

(although, at this point, why not just drop the whole list and run `hack/make.sh` by itself, which should run everything? https://github.com/docker/docker/blob/25f8c2664066a523f3f59f4cc5cdc8cf81c8a7c8/project/make.sh#L43-L63)

**Comment by jfrazelle** [comment]
ok ok i updated

**Comment by LK4D4** [comment]
@tianon isn't dyntest-unit will be pretty slow? Cause even now it takes enormous time to test one PR.

**Comment by tianon** [comment]
True, but it runs _everything_, which is strictly better than what we do now, right?  This will even build-test creating the tarballs and the debs, so that if Drone's happy, we can be reasonably assured that the PR doesn't break the build.

**Comment by jfrazelle** [comment]
nice ya, the more the merrier

**Comment by jfrazelle** [comment]
lets see how long it takes

**Comment by jfrazelle** [comment]
that's the hardest part

**Comment by thaJeztah** [comment]
Not sure if it makes sense, but would it be possible to check if only "doc" changes are made? (Ie only changes inside `/docs` or only `*.md` files? Would save a lot of time and perhaps some trees. :deciduous_tree:.

**Comment by LK4D4** [comment]
Haha, failed. And there is no logs in webui too.

**Comment by jfrazelle** [comment]
ugh gross im going back to the other thing bc that succeeded

**Comment by jfrazelle** [comment]
ok updated... i also have jenkins doing everything so at least theres that .. https://jenkins.dockerproject.com/job/Docker%20Master/label=debian-devmapper-lxc/128/console

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by tianon** [comment]
/me sheds another tear for drone :poo:

**Pull request merged**
