### PR TITLE
Cherry pick latest 752015

### PR DESCRIPTION
**Pull request by moxiegirl**
Cherry picks from latest changes

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by moxiegirl** [comment]
Author LGTM

**Comment by moxiegirl** [comment]
@jfrazelle Hey Jess can you tell me if they broken Windows is something I need to worry about here on this PR?

**Comment by icecrime** [comment]
@moxiegirl Let's wait for the last run of Windows tests, but janky is green so I think we're safe.

**Comment by moxiegirl** [comment]
@icecrime Will do --- janky is usually cranky after all. :D

**Pull request merged**
