### PR TITLE
Windows: Implement parsers:kernel+os

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com
@swernli

This PR is part of the proposal described in issue 10662 to port the docker daemon to Windows. This provides implementation of kernel_windows and operatingsystem_windows.go in the parsers package so that daemon can return the correct version information.

### CODE REVIEW

**Comment by unclejack** [comment]
It's currently erroring out with this: `registry/httpfactory.go:17: undefined: kernel.GetKernelVersion`

**Comment by jhowardmsft** [comment]
Ah yes, it was on the cross-platform Darwin which also calls this API. Fixed my moving kernel_linux.go back to kernel.go and adding a //build !windows on it.

**Comment by unclejack** [comment]
The Windows code looks good.

LGTM

**Comment by jfrazelle** [comment]
this is pretty cool :) LGTM

**Pull request merged**
