### PR TITLE
Update cloudflare/cfssl to 1.3.2

### PR DESCRIPTION
**Pull request by thaJeztah**
Matching the version that is used in SwarmKit; the equivalent SwarmKit PR is https://github.com/docker/swarmkit/pull/2644

- github.com/cloudflare/cfssl updated to 1.3.2; https://github.com/cloudflare/cfssl/compare/7fb22c8cba7ecaf98e4082d22d65800cf45e042a...1.3.2
- github.com/google/certificate-transparency moved to github.com/google/certificate-transparency-go, and updated to 5ab67e519c93568ac3ee50fd6772a5bcf8aa460d (matching SwarmKit)
- golang.org/x/crypto not updated; was already ahead; https://github.com/golang/crypto/compare/650f4a345ab4e5b245a3034b110ebc7299e68186...1a580b3eff7814fc9b40602fd35256c63b50f491

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @cyli @justincormack @dperny PTAL

**Comment by thaJeztah** [comment]
Janky https://jenkins.dockerproject.org/job/Docker-PRs/49958/console failing on https://github.com/moby/moby/issues/36501

```
17:13:01 FAIL: docker_api_swarm_service_test.go:33: DockerSwarmSuite.TestAPIServiceUpdatePort
17:13:01 
17:13:01 [dde612639de8b] waiting for daemon to start
17:13:01 [dde612639de8b] daemon started
17:13:01 
17:13:01 docker_api_swarm_service_test.go:39:
17:13:01     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
17:13:01 docker_utils_test.go:435:
17:13:01     c.Assert(v, checker, args...)
17:13:01 ... obtained int = 0
17:13:01 ... expected int = 1
17:13:01 
17:13:01 [dde612639de8b] exiting daemon

17:38:00 FAIL: docker_cli_swarm_test.go:1605: DockerSwarmSuite.TestSwarmPublishDuplicatePorts
17:38:00 
17:38:00 [de37804d7b874] waiting for daemon to start
17:38:00 [de37804d7b874] daemon started
17:38:00 
17:38:00 docker_cli_swarm_test.go:1613:
17:38:00     // make sure task has been deployed.
17:38:00     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
17:38:00 docker_utils_test.go:435:
17:38:00     c.Assert(v, checker, args...)
17:38:00 ... obtained int = 0
17:38:00 ... expected int = 1
17:38:00 
17:38:00 [de37804d7b874] exiting daemon
```

**Comment by thaJeztah** [comment]
s390x/z https://jenkins.dockerproject.org/job/Docker-PRs-s390x/10279/console is failing on https://github.com/moby/moby/issues/34988 / https://github.com/moby/moby/issues/35039;

```
17:03:05 FAIL: docker_api_swarm_test.go:359: DockerSwarmSuite.TestAPISwarmRaftQuorum
17:03:05 
17:03:05 [d7c1f9b6ad9b7] waiting for daemon to start
17:03:05 [d7c1f9b6ad9b7] daemon started
17:03:05 
17:03:05 [de70d7c6dc1b9] waiting for daemon to start
17:03:05 [de70d7c6dc1b9] daemon started
17:03:05 
17:03:05 [d6ae2c869805f] waiting for daemon to start
17:03:05 [d6ae2c869805f] daemon started
17:03:05 
17:03:05 [de70d7c6dc1b9] exiting daemon
17:03:05 [d6ae2c869805f] exiting daemon
17:03:05 docker_api_swarm_test.go:385:
17:03:05     // d1 will eventually step down from leader because there is no longer an active quorum, wait for that to happen
17:03:05     waitAndAssert(c, defaultReconciliationTimeout, func(c *check.C) (interface{}, check.CommentInterface) {
17:03:05         _, err = cli.ServiceCreate(context.Background(), service.Spec, types.ServiceCreateOptions{})
17:03:05         return err.Error(), nil
17:03:05     }, checker.Contains, "Make sure more than half of the managers are online.")
17:03:05 docker_utils_test.go:435:
17:03:05     c.Assert(v, checker, args...)
17:03:05 ... obtained string = "Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
17:03:05 ... substring string = "Make sure more than half of the managers are online."
17:03:05 
17:03:05 [d7c1f9b6ad9b7] exiting daemon
```

**Review by yongtang — APPROVED** [review]
LGTM

**Review by boaz0 — COMMENTED** [review]
LGTM :rocket:

**Review by vdemeester — APPROVED** [review]
LGTM :foggy:

**Pull request merged**
