### PR TITLE
Remove deadcode from `service/opts.go` : `SecretOpt`

### PR DESCRIPTION
**Pull request by vdemeester**
`SecretOpt` is in the `opts` package, this one is never used, so it's
dead code, removing it 👼.

/cc @thaJeztah @AkihiroSuda @dnephin @cpuguy83 @ehazlett @runcom 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM (if green)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vdemeester** [comment]
Green 💚

**Comment by thaJeztah** [comment]
merge 💜

**Pull request merged**
