### PR TITLE
use unique names for test containers of container/nat integration tests 

### PR DESCRIPTION
**Pull request by adshmh**
Modify integration tests in `container/nat_test.go` to use unique names for test containers. Part of work on #36583 

Signed-off-by: Arash Deshmeh <adeshmeh@ca.ibm.com>

**- What I did**
Changed integration tests of `container/nat_test.go` to use unique names for test containers.

**- How I did it**
Changed the implementation of `startServerContainer` to generate a container name unique to the test. 

**- How to verify it**

**- Description for the changelog**
Integration tests in container/nat_test.go use unique names for test containers

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by adshmh** [comment]
Thank you for the quick reviews.

**Comment by thaJeztah** [comment]
Experimental and z failed on TestPostContainersAttach, which is unrelated (see https://github.com/moby/moby/issues/36611), but green otherwise

**Pull request merged**
