### PR TITLE
Add “” for String

### PR DESCRIPTION
**Pull request by yu8833**
**- What I did**
Add “” for String to align default description
**- How I did it**
Add “” for String
**- A picture of a cute animal (not mandatory but encouraged)**
Before
image
After
image

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Please update:
- contrib/completion/fish/docker.fish
- docs/reference/commandline/cli.md
- docs/reference/commandline/dockerd.md

**Comment by YuPengZTE** [comment]
Thanks @AkihiroSuda , PTAL

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
