### PR TITLE
Expose old config field for api < 1.19

### LINKED ISSUE #13663: Resource options are missing from Config JSON
As of https://github.com/docker/docker/pull/10298, resource options (`Cpuset`, `Memory` etc) are no longer in the `Config` section of a container's JSON, but in `HostConfig`. Unfortunately, that appears to be the case across all API versions, which I believe is a regression.

Test script:

```python
from docker.client import Client
from docker.utils import kwargs_from_env

kwargs = kwargs_from_env()
kwargs['tls'].assert_hostname = False

for minor_version in range(1, 19):
    version = '{}.{}'.format(1, minor_version)
    client = Client(version=version, **kwargs)
    container = client.create_container('busybox', 'true', cpu_shares=1)
    container_info = client.inspect_container(container)

    print '{}: CpuShares = {}'.format(version, container_info['Config'].get('CpuShares'))
```

Output when run against a Docker 1.6.2 daemon:

```
$ python test.py
1.1: CpuShares = 1
1.2: CpuShares = 1
1.3: CpuShares = 1
1.4: CpuShares = 1
1.5: CpuShares = 1
1.6: CpuShares = 1
1.7: CpuShares = 1
1.8: CpuShares = 1
1.9: CpuShares = 1
1.10: CpuShares = 1
1.11: CpuShares = 1
1.12: CpuShares = 1
1.13: CpuShares = 1
1.14: CpuShares = 1
1.15: CpuShares = 1
1.16: CpuShares = 1
1.17: CpuShares = 1
1.18: CpuShares = 1
```

Output when run against a Docker 1.7.0 RC1 daemon:

```
$ python test.py
1.1: CpuShares = None
1.2: CpuShares = None
1.3: CpuShares = None
1.4: CpuShares = None
1.5: CpuShares = None
1.6: CpuShares = None
1.7: CpuShares = None
1.8: CpuShares = None
1.9: CpuShares = None
1.10: CpuShares = None
1.11: CpuShares = None
1.12: CpuShares = None
1.13: CpuShares = None
1.14: CpuShares = None
1.15: CpuShares = None
1.16: CpuShares = None
1.17: CpuShares = None
1.18: CpuShares = None
```

### PR DESCRIPTION
**Pull request by runcom**
/cc @icecrime @calavera @aanand

I tried everything (99.9999% sure) before going with a second function just for < 1.19 code path :angel: 
fixes #13663

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by vieux** [comment]
One comment, it's not really an issue for me, but I know some people will complain.

When talking to the daemon using the API 1.18, you the the resources both in `Config` **AND** `HostConfig` 


Using `docker-1.6.1` against this branch, I did a `docker run -d --name test -m 20m busybox ping google.com`

This is the inspect:

```
{
    "Id": "65080757ba6b435a3a295e7175afa4824e227729289d0069458bc837dee0a242",
    "Created": "2015-06-02T22:02:01.844734237Z",
    "Path": "ping",
    "Args": [
        "google.com"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 27140,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-06-02T22:02:01.981596487Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "2e0c684e6ce05f1db40215852634eee669d06db054d6babbf5759f552dcdc092",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.1",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:5f:fa:8a:df",
        "NetworkID": "151b1ecce18213df39aba6e511fb766f62ebd36fb166a8653f2fcf2c299e6bde",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/65080757ba6b",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/65080757ba6b435a3a295e7175afa4824e227729289d0069458bc837dee0a242/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/65080757ba6b435a3a295e7175afa4824e227729289d0069458bc837dee0a242/hostname",
    "HostsPath": "/var/lib/docker/containers/65080757ba6b435a3a295e7175afa4824e227729289d0069458bc837dee0a242/hosts",
    "LogPath": "/var/lib/docker/containers/65080757ba6b435a3a295e7175afa4824e227729289d0069458bc837dee0a242/65080757ba6b435a3a295e7175afa4824e227729289d0069458bc837dee0a242-json.log",
    "Name": "/test",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {},
    "VolumesRW": {},
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 20971520,
        "MemorySwap": -1,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "65080757ba6b",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": null,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": null,
        "Cmd": [
            "ping",
            "google.com"
        ],
        "Image": "busybox",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {},
        "Memory": 20971520,
        "MemorySwap": -1,
        "CpuShares": 0,
        "Cpuset": ""
    }
}
```

As you can see `20971520` is displayed twice.

**Comment by runcom** [comment]
@vieux I'm aware of this (while testing I came with your extact situation) but I think new fields are always exposed to older api so I didn't care. Is this really a problem? (I can find a way to fix this but as per what I just said I don't think we should care)

**Comment by vieux** [comment]
@runcom it's fine by me, I juste wanted to make sure you were aware.

LGTM

**Comment by calavera** [comment]
@vieux that happens with docker 1.6.1 too because those fields where duplicated:

```
[{
    "AppArmorProfile": "",
    "Args": [
        "google.com"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "ping",
            "google.com"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": null,
        "ExposedPorts": null,
        "Hostname": "bfad39cd32f5",
        "Image": "busybox",
        "Labels": {},
        "MacAddress": "",
        "Memory": 20971520,
        "MemorySwap": -1,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-06-02T22:20:48.616028128Z",
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": [],
        "Memory": 20971520,
        "MemorySwap": -1,
        "NetworkMode": "bridge",
        "PidMode": "",
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/bfad39cd32f577bf7853028cb0dfaeb2c4230e4aba14cf346541e04d0507d859/hostname",
    "HostsPath": "/var/lib/docker/containers/bfad39cd32f577bf7853028cb0dfaeb2c4230e4aba14cf346541e04d0507d859/hosts",
    "Id": "bfad39cd32f577bf7853028cb0dfaeb2c4230e4aba14cf346541e04d0507d859",
    "Image": "8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55",
    "LogPath": "/var/lib/docker/containers/bfad39cd32f577bf7853028cb0dfaeb2c4230e4aba14cf346541e04d0507d859/bfad39cd32f577bf7853028cb0dfaeb2c4230e4aba14cf346541e04d0507d859-json.log",
    "MountLabel": "",
    "Name": "/test1",
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.6",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "fe80::42:acff:fe11:6",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:42:ac:11:00:06",
        "PortMapping": null,
        "Ports": {}
    },
    "Path": "ping",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/bfad39cd32f577bf7853028cb0dfaeb2c4230e4aba14cf346541e04d0507d859/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 10572,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-06-02T22:20:48.719311857Z"
    },
    "Volumes": {},
    "VolumesRW": {}
}
]
```

**Comment by vieux** [comment]
@calavera ok thanks!

**Comment by aanand** [comment]
:cake:

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
