### PR TITLE
Cleanup duplicated and split checks

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com
parameter networking is deprecated.
Using NetworkMode to replace NetworkDisabled for determining where print warning or not when IPv4Forwarding is disabled.
verifyHostConfig can totally replace verifyDaemonSettings

### CODE REVIEW

**Comment by hqhq** [comment]
Hi, check at start time is necessary, we can think about call `verifyHostConfig` instead but not remove the verify, you can take a look at this one: https://github.com/docker/docker/pull/12619

**Comment by Mashimiao** [comment]
Hi @hqhq,
I have a different opinion with you.
As I said in #12619 
ContainerStart() already calls verifyHostConfig do it before calling container.Start().
So, there is not necessary to do double check.  We just need to enforce verifyHostConfig()

**Comment by Mashimiao** [comment]
ping @icecrime , @LK4D4 , @duglin , @jfrazelle

**Comment by duglin** [comment]
This seems reasonable but as I was looking at the code around this I started to wonder about the split between the daemon.ContainerStart() and container.Start().  While not all of the checks are the same, there are some duplicated (like checking to see if its already running).  Should we be looking to move more of these checks into one layer and not duplicate or split them? By having some in daemon and some in container we run the risk of missing some (or getting inconsistent results) if people call the wrong layer.   Would it make sense to have the daemon code do the minimum (look up the container, set hostConfig) and then defer the rest of the logic to the container layer?

**Comment by duglin** [comment]
And, of course, if that does make sense we could do that for all of the various daemon/container methods that overlap.  Another round of daemon clean-up/reorg!

**Comment by Mashimiao** [comment]
@duglin , Moving checks to one layer is great!
This must can avoid duplicate or split.
But in my opinion, the daemon code should do these checks. We should apply these configure before making sure they are all OK.
After setting up correct conditions, container layer can just do basic logic to realize the function.
How do you think about it?

**Comment by Mashimiao** [comment]
@duglin , Moving checks to one layer is great!
This must can avoid duplicate or split.
But in my opinion, the daemon code should do these checks. We should apply these configure before making sure they are all OK. And we should find out error as soon as possible.
After setting up correct conditions, container layer can just do basic logic to realize its function.
How do you think about it?

**Comment by duglin** [comment]
@Mashimiao I think it depends on which type of check we're talking about.
In my quick scan of the code I saw three types of checks:
1 - e.g. in Start(), is the container already running?  I think this should be done within the container because doing it in the daemon doesn't remove the need to do it in container.Start().
2 - e.g. is some **new** config value correct? I think doing this in the daemon is correct as long as the container itself doesn't do the same check.
3 - e.g. in Start(), is the container's current config ok? I think this should be in the container because it will need to be checked prior to running starting the container.

I guess the rule I'm following is.... if the function container.foo() does some check then equivalent daemon.foo() should not perform the same check.  Of course, it does beg the question of why we have foo() in daemon and container  :-)    

In the case of daemon.ContainerStart() vs container.Start(), it appears that the daemon code is just there to convert name->id and verify/set hostConfig.  Its not clear to me why daemon.setHostConfig() doesn't call verifyHostConfig() itself, assuming setHostConfig() is modified to throw an error when trying to update the config on a paused/running container.  IMO the LogEvent("die") should be moved into container.Start() too, then the err from Start() could just be returned as-is.Then the func just becomes:
```
func (daemon *Daemon) ContainerStart(name string, hostConfig *runconfig.HostConfig) error {
    container, err := daemon.Get(name)
    if err != nil {
        return err
    }

    // This is kept for backward compatibility - hostconfig should be passed when
    // creating a container, not during start.
    if hostConfig != nil {
        if err := daemon.setHostConfig(container, hostConfig); err != nil {
            return err
        }
    }

    if err := container.Start(); err != nil {
        return err
    }

    return nil
}
```
Which reduces it down to what it really is, just a thin layer to convert user-provided data.
Ideally, I think it should be container.SetHostConfig(hostConfig) but I might be missing something.

**Comment by Mashimiao** [comment]
@duglin  Your logic seems very reasonable. I agree with you.
If nobody objected to this, I would update this PR tomorrow according to your opinion.
Thanks a lot.

**Comment by duglin** [comment]
Please wait for others, like @LK4D4 , to speak-up first because I could be missing something and I don't want you to waste your time doing a re-org if its not the correct approach.

**Comment by LK4D4** [comment]
@duglin @Mashimiao I think it is pretty good suggestion.

**Comment by Mashimiao** [comment]
@duglin  I think I need some help.
I'm not sure what cause testcase failed.

**Comment by Mashimiao** [comment]
@duglin , I think I need your help. 
I'm not sure why testcase always marked as failed.
I have worked on this for several day, but can't find out why.

**Comment by duglin** [comment]
@Mashimiao can you please rebase?

**Comment by Mashimiao** [comment]
Hi @duglin  rebased. But `Build timed out (after 60 minutes). Marking the build as failed.` still exists.

**Comment by duglin** [comment]
@Mashimiao I think another rebase is needed.  But, first, with all of the changes that have been made in these areas, are these changes still needed?  If so, that's fine- I just wasn't sure.

**Comment by LK4D4** [comment]
@Mashimiao Need rebase :/

**Comment by duglin** [comment]
@Mashimiao please let us know what you want to do with this otherwise we may close it.

**Comment by Mashimiao** [comment]
Hi @duglin, @LK4D4 
I think it's a little complicated to rebase it.
I want to close this one and submit a new PR to fix the similar problem
WDYT?

**Comment by LK4D4** [comment]
@Mashimiao Of course, if you think it would be simpler. Sorry for this, we had so big merges recently :(

**Comment by Mashimiao** [comment]
OK, I will close this one and

**Pull request closed without merging**
