### PR TITLE
Reexport exitcode

### LINKED ISSUE #26143: Incorrect Exit Status When Stopping Docker Daemon
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613 GiB
Name: test-instance
ID: EZVW:ZB3Z:63X2:UZD5:W7QG:KXFX:VYGB:JVTR:ABZK:NG5S:NFBN:NSUU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=google
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
GCE

**Steps to reproduce the issue:**
1. Start a long running container (e.g., sleep 10000s)
2. Run "sudo service docker stop"
3. Run "sudo service docker start"
4. Run "docker ps -a"

```
docker-user@test-instance:~$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
ddaf1026f67f        ubuntu              "sleep 10000s"      About a minute ago   Up About a minute                       stupefied_davinci
docker-user@test-instance:~$ sudo service docker stop
docker stop/waiting
docker-user@test-instance:~$ sudo service docker start
docker start/running, process 3823
docker-user@test-instance:~$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
ddaf1026f67f        ubuntu              "sleep 10000s"      2 minutes ago       Exited (0) 18 seconds ago                       stupefied_davinci
```

**Describe the results you received:**
The status of containers that are running when daemon is stopped shows "Exited (0)"

**Describe the results you expected:**
I would expect the status to display "Exited (137)" or some other non-zero code.

**Additional information you deem important (e.g. issue happens only occasionally):**
This also happens on my default boot2docker machine. This was not happening with version 1.11.1 on my default machine. Not only did this issue start happening after upgrading my default machine to version 1.12.1,  but old exit statuses from stopped containers turned from non-zero to zero after upgrading.

### PR DESCRIPTION
**Pull request by mlaventure**
Fixes #26143 
##

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by dionjwa** [comment]
This fix does not work:

Running AMI ami-4f72382f (CoreOS Alpha Channel, CoreOS 1221.0.0.) on AWS:

    docker run -d busybox sleep 20000

In another terminal (correct for your container id):

    curl -X POST  http://localhost:2375/containers/1a0d46921bb4/wait

In another terminal:

    sudo systemctl stop docker

The terminal with the `wait` POST request returns:

    {"StatusCode":137}

But then if you do:

    docker inspect 1a0d46921bb4

You see:

    "ExitCode": 0

If the docker daemon restart resulting from e.g. a crash, you might not ever see the first correct exitCode. 

```
docker info
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: selinux
Kernel Version: 4.8.6-coreos
Operating System: CoreOS 1221.0.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.862 GiB
Name: ip-10-0-0-131.us-west-1.compute.internal
ID: GOGS:PIUQ:3FH6:LKQV:KDQD:FHWY:HRMU:NJT5:J74Y:ZZKF:S7N5:6FWZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
```

**Pull request merged**
