### PR TITLE
use terminfo in pkg/jsonmessage

### PR DESCRIPTION
**Pull request by ijc**
**- What I did**

Switched `pkg/jsonmessage` to use the terminfo database for terminal control codes instead of hardcoding. This should be more portable to a wider variety of terminals etc

**- How I did it**

I vendored https://github.com/Nvveen/Gotty and ported `jsonmessage` to use it. For cases where no terminfo is available for $TERM or the terminfo entry is missing capabilities we use using I retained a fallback to the existing control codes.

I made a couple of improvements to the test's while doing this work and those are also included in this PR.

_concerns/caveats_:
* Surprisingly there is no obvious widely used/supported Go terminfo library. https://github.com/Nvveen/Gotty/ looks to be correct to me (and the best of the ones I looked at and is preferable to writing my own) but has not been touched for many years and only had one contributor (the original author).
* systems with broken terminfo may now misbehave where they may have gotten away with it before. systems with non-existent terminfo should see no change due to the fallbacks.
* the escape codes `jsonmessage` uses are pretty basic and well established ones, although as #28111 there is scope for differences even there (full-disclosure: terminfo would not actually have directly helped with #28111, see the fix in #28238), so it might be valid to say that this PR is not really warranted.

**- How to verify it**

Run a docker pull under a variety of terminals (I used rxvt-unicode, xterm, mlterm and aterm) and observe that the perceived output has not changed. Note that the actual control characters may now differ between terminals, this can be observed by using `script -c 'docker pull alpine' pull-alpine.script` and inspecting `pull-alpine.script`.

**- Description for the changelog**

Use terminfo database for control codes in docker pull et al.

**- A picture of a cute animal (not mandatory but encouraged)**
Davy Jones, The Monkees

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by justincormack** [comment]
Are there any significant differences in actually used terminal types? I am
very marginal on this, especially as I don't install terminfo files
myself...

**Comment by ijc25** [comment]
```
$ for i in el el1 cuu cud ; do echo -en "$i\t" ; for j in /lib/terminfo/*/* /usr/share/terminfo/*/* ; do infocmp $(basename $j); done | sed -n -e "s/.*\b\($i=[^,]*\),.*/\1/p" | sort -u | wc -l ; done
el	93
el1	11
cuu	8
cud	9
```

`el` appears to vary a great deal. For the others:
```
$ for i in el1 cuu cud ; do echo -en "$i\n" ; for j in /lib/terminfo/*/* /usr/share/terminfo/*/* ; do infocmp $(basename $j); done | sed -n -e "s/.*\b\($i=[^,]*\),.*/\1/p" | sort | uniq -c ; done
el1
     14 el1=\2331K
    500 el1=\E[1K
      2 el1=\E[1K$<1>
     10 el1=\E[1K$<12>
     99 el1=\E[1K$<3>
      5 el1=\E[1K$<30>
     21 el1=\E[1K$<5>
      5 el1=\E[1K\E[X
     14 el1=\E[2K
      1 el1=\EL
     16 el1=\Eo
cuu
      1 cuu=\035up %p1%d;
     10 cuu=\037up %p1%d\r
     18 cuu=\233%p1%dA
     30 cuu=\E&a-%p1%dR
   1022 cuu=\E[%p1%dA
      5 cuu=\E[%p1%dA$<30>
     29 cuu=\E[%p1%dA$<5>
      1 cuu=\Ep-%p1%d;
cud
      1 cud=\035dow %p1%d;
     10 cud=\037dow %p1%d\r
     18 cud=\233%p1%dB
     30 cud=\E&a+%p1%dR
   1022 cud=\E[%p1%dB
      5 cud=\E[%p1%dB$<30>
     29 cud=\E[%p1%dB$<5>
      2 cud=\E[%p1%de
      1 cud=\Ep%p1%d;
```
The clusters are probably families of terminals, I've not tried to analyse how popular each set might be.

If you don't install termcap then you will get exactly the same behaviour as today.

**Comment by tiborvass** [comment]
Lol, I like the picture of a cute animal 😂

**Comment by tianon** [comment]
I don't love new dependencies, but this one looks small and sane, and terminfo is generally the right way to handle this.  Also, it's got fallbacks, so folks like @justincormack who don't install terminfo still get a good experience too, so I'm +1. :+1:

LGTM

**Comment by LK4D4** [comment]
Ok, this dependency looks okay for me.
LGTM

**Pull request merged**
