### PR TITLE
Add check for CONFIG_IP_NF_NAT to kernel check

### PR DESCRIPTION
**Pull request by cdrage**
This appears to be missing. NAT (via iptables) is required in order to
setup Docker networking.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @justincormack @mavenugo PTAL

**Comment by thaJeztah** [comment]
(Commit is signed off, but CI got confused)

**Comment by cdrage** [comment]
Haha yeah, no idea why it did that, I simply did an ammend and `git push -f`.

**Comment by cdrage** [comment]
Btw, the background to this is me installing 4.7.4 of the linux kernel and docker bugging out when starting the docker daemon.

We should be checking that IP_NAT is fully enabled / added since the docker daemon will bug out not being able to create the NAT entries.

**Comment by cdrage** [comment]
There we go, had a minor commit conflict

Rebased ^^

**Comment by LK4D4** [comment]
ping @mrjana @aboch @sanimej

**Comment by justincormack** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
