### PR TITLE
Fix nat integration tests

### LINKED ISSUE #13556: libnetwork: TestDaemonICCPing
on certain machines these are super unstable and fail all the time

### PR DESCRIPTION
**Pull request by crosbymichael**
This removes complexity of current implementation and makes the test
correct and assert the right things.

Fixes #13556

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
trying on my machine for the ultime test, brace yoself

**Comment by icecrime** [comment]
Used to fail consistently, now green both with and without `--userland-proxy`.

LGTM!

**Comment by mrjana** [comment]
@crosbymichael This is what the test was doing before somebody changed the test to echo `bye`. But this method of testing was also flaky because once in a while `nc` will accept the connection and will just exit without printing the message. I believe the only consistent way of testing with `nc` is to make sure that connection gets established and then assert if it fails. We can't rely on the message being printed.

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
@mrjana i changed it so the nc outputs like before so it's robust and we don't have to worry about it dropping bytes.  I made sure that was addressed

**Comment by mrjana** [comment]
@crosbymichael cool. I just realized that your piping in the actual message in the server side to `nc` so that it gets served to the client all the time. I think that should work. Nice job :-) LGTM

**Comment by crosbymichael** [comment]
No problem, thanks for taking a look

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
