### PR TITLE
Allow engine to run inside a user namespace

### PR DESCRIPTION
**Pull request by estesp**
Carry of PR #20902 

Allow the Docker daemon to run inside a user namespaced parent process.  Original patch by @hallyn; I've added a change to revert to "real" chroot when inside a userns that came about since the original patch.

I have tested this capability inside lxc running an ubuntu:xenial image with a binary built from this PR patchset.  To successfully run the Docker daemon I used the following command line:

```
dockerd -D -s vfs --oom-score-adjust=0
```

Inside a user namespace, writing to the oom_score_adj special proc file fails, and I can't get any backend driver to work outside of vfs.

I cannot run the Docker engine inside of a runc container with user namespaces enabled due to how the `/sys/fs/cgroups` mount is handled under runc. Therefore it is hard to write a test that integrates well with our CI system without requiring a working LXC setup until we solve this problem in runc.

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM but I think we should document the cant-create-devices restriction somewhere (probably dont need to mention the chroot) as it is not something people would necessarily realise.

**Comment by kimh** [comment]
@estesp Thanks for the PR. I also could run docker without an issue with this PR.

**Comment by estesp** [comment]
@justincormack agree on the docs need..but where? Is that the same section as user namespaces support in the daemon, or some other place that talks about environment in which you run the daemon?  Seems like it should be the latter, but that points to less clear locations as there are lots of various bits about running/configuring the engine.. any guidance appreciated! /cc @thaJeztah

**Comment by thaJeztah** [comment]
I think we could think of moving user namespaces to a separate document, instead of cramming it all in the `dockerd` reference; that way we can provide a bit more context, tips/tricks and explain when it's useful (and when not).

ping @sfsmithcha wdyt?

**Comment by justincormack** [comment]
@thaJeztah but this is about running docker inside a user namespace, really goes in the how to install/run docker section.

**Comment by thaJeztah** [comment]
@justincormack oh, darn, was too quick answering. erm, yes, good question not sure where to put that; it's not a regular install, same as we don't document "docker in docker"

**Comment by justincormack** [comment]
Yes, lets maybe leave the docs for now...

LGTM

**Comment by vdemeester** [comment]
LGTM :cat:

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
