### PR TITLE
Check oom status after container stopped in lxc driver

### PR DESCRIPTION
**Pull request by LK4D4**
ping @crosbymichael

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @jfrazelle @tiborvass

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
passed lxc and normal shall we try windows lol

**Comment by LK4D4** [comment]
There was race because of which sometimes lxc failed

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
