### PR TITLE
Use docker daemon for intergation test daemon start

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

@jfrazelle Is there anything we need to do before merging?

**Comment by jfrazelle** [comment]
nice LGTM, cooollll

**Comment by jfrazelle** [comment]
thanks for checking, bc ya never know haha

**Pull request merged**
