### PR TITLE
Update libnetwork to 96d45528599c32354230480a1ebc0

### LINKED ISSUE #23560: Do not allow host and null network creation
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Daemon allows user to create an extra host and null network

**Output of `docker version`:**

```
docker version 
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   9246b7b-unsupported
 Built:        Tue Jun 14 06:15:45 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   47d24fe
 Built:        Tue Jun 14 23:29:24 2016

```

**Output of `docker info`:**

```
$ docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 811
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 991
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host overlay null
Swarm: active
 NodeID: 1cooimghva67k
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:8e387bf60d8e98d6b36a0d6ef4c973fd9767dbed133a82563fd2b607dbdc394d
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Name: aboch-W540
ID: PCG6:A73V:2MEX:CY4J:ZRQC:ZA4L:Y6MT:UJOK:2YDL:DSEI:4UU3:LZOX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 47
 Goroutines: 122
 System Time: 2016-06-14T19:40:42.606317006-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a `null` or `host` type network

**Describe the results you received:**
Creation suceeds

$ docker network create -d null nooone
bd656f852fb29e61e9acd6ca5f2280e9539f9afe68adb02c0a0468f35f55fa56

**Describe the results you expected:**
Should fail because the daemon predefined already provisioned `host` and `none` networks are already present and only one instance of this type of networks is allowed.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is a breakage from the bigger change for docker networking to support daemon reload, #23524

### PR DESCRIPTION
**Pull request by crosbymichael**
This fixes an issue with a dockerpy error in the tests.

Fixes #23560

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
@crosbymichael This should fix this docker-py error not the hang:
```
21:37:06 =================================== FAILURES ===================================
21:37:06 ___________ TestNetworks.test_create_network_with_host_driver_fails ____________
21:37:06 /docker-py/tests/integration/network_test.py:91: in test_create_network_with_host_driver_fails
21:37:06     self.client.create_network(net_name, driver='host')
21:37:06 E   Failed: DID NOT RAISE
```

LGTM if green

**Comment by icecrime** [comment]
LGTM if green! Thanks

**Comment by icecrime** [comment]
Failures on experimental:

```
15:38:26 FAIL: docker_cli_exec_test.go:381: DockerSuite.TestRunMutableNetworkFiles
15:38:26 
15:38:26 docker_cli_exec_test.go:415:
15:38:26     res, _ := dockerCmd(c, "exec", contID, "cat", "/etc/"+fn)
15:38:26 /go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
15:38:26     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
15:38:26 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc822a63ba0), Stderr:[]uint8(nil)} ("exit status 1")
15:38:26 ... "exec 6f9c0ffbb2cb1c22e48e4c4a871ee61620299eb03017a8578cf45b15651caf70 cat /etc/resolv.conf" failed with errors: rpc error: code = 2 desc = oci runtime error: exec failed: open /run/runc/6f9c0ffbb2cb1c22e48e4c4a871ee61620299eb03017a8578cf45b15651caf70/state.json: no such file or directory

15:38:26 Error response from daemon: Container 6f9c0ffbb2cb1c22e48e4c4a871ee61620299eb03017a8578cf45b15651caf70 is not running: Exited (137) Less than a second ago
15:38:26 , exit status 1
```

```
15:58:01 FAIL: docker_cli_network_unix_test.go:1339: DockerNetworkSuite.TestDockerNetworkConnectLinkLocalIP
15:58:01 
15:58:01 docker_cli_network_unix_test.go:1363:
15:58:01     c.Assert(err, check.IsNil)
15:58:01 ... value *errors.errorString = &errors.errorString{s:"exit status 1: PING 169.254.8.8 (169.254.8.8): 56 data bytes\n\n--- 169.254.8.8 ping statistics ---\n1 packets transmitted, 0 packets received, 100% packet loss\n"} ("exit status 1: PING 169.254.8.8 (169.254.8.8): 56 data bytes\n\n--- 169.254.8.8 ping statistics ---\n1 packets transmitted, 0 packets received, 100% packet loss\n")
```

**Comment by tonistiigi** [comment]
flaky test #22601 in tp5, merging

**Pull request merged**
