### PR TITLE
Remove CmdWithArgs from integration-cli

### PR DESCRIPTION
**Pull request by dnephin**
Small cleanup to an integration test helper function.  There is a proliferation of different ways to run a docker command during integration testing. I'd like to clean this up by reducing this to as few functions as possible.  `CmdWithArgs()` is unnecessary, we can accomplish the same thing with the existing `Cmd()` method, so this PR removes it.

Also moves a test file to remove the `hack` in the name.

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐸 :heart_eyes_cat:

**Comment by thaJeztah** [comment]
LGTM, but we should probably wait with merging until cherry-picking for the release is completed

**Comment by justincormack** [comment]
Needs a rebase.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
