### PR TITLE
PowerShell: various cleanups / fixes

### PR DESCRIPTION
**Pull request by thaJeztah**
#### PowerShell: fix mixed tabs/spaces

Fixed some mixed/tabs spaces for indentation, and used
tabs for auto-generated Go code.

#### PowerShell: move $null to left-hand for comparisons

see https://rencore.com/blog/powershell-null-comparison/

#### PowerShell: remove aliases, use their real commands instead

This patch replaces PowerShell aliases for their real commands, see https://blogs.technet.microsoft.com/heyscriptingguy/2012/04/21/when-you-should-use-powershell-aliases/

For example;

- use `Get-Location` instead of `pwd`
- use `Set-Location` instead of `cd`
- use `ForEach-Object` instead of the `%` shorthand
- use `Write-Output` instead of `echo`

### CODE REVIEW

**Comment by thaJeztah** [comment]
Making my IDE a bit more happy 😄 

@olljanat @tianon ptal

**Comment by thaJeztah** [comment]
> Using Set-Location instead of cd feels bit overdoing but I can live with it.

I'm ok with changing it back if it's an odd thing to do. My IDE was complaining about it; then I looked it up on the internets, and apparently it was a "thing" (not best practice to use aliases), but I'm not attached to it, so happy to change it haha

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Review by vdemeester — APPROVED** [review]
LGTM :tiger: 
/cc @simonferquel @johnstep @jhowardmsft

**Review by lowenna — APPROVED** [review]

**Comment by jhowardmsft** [comment]
LGTM

**Pull request merged**
