### PR TITLE
added better Docker Machine links to Swarm tutorial d4mac, d4win, cop…

### PR DESCRIPTION
**Pull request by londoncalling**
**\- What I did**
In Swarm tutorial getting started, under the Docker for Mac / Docker for Windows notes, added another Docker Machine link to a topic specific to using Machine to create local VM's.

Also copy-edited a page in the Getting Started tutorial (beginner Docker) to include a "Where to go next" topic, like all the others in that tutorial.

**\- How to verify it**
Review the changed files.

**\- Description for the changelog**
Updated Swarm getting started tutorial to help Docker for Mac and Windows users.

**\- picture of a cute animal**
elephant

Signed-off-by: Victoria Bialas victoria.bialas@docker.com

### CODE REVIEW

**Comment by londoncalling** [comment]
@mstanleyjones @ManoMarks @nathanleclaire @johndmulhausen please review (this supports d4mac, d4win explanations of relationship w/Docker Machine and creating Swarm nodes on local systems)

**Comment by nathanleclaire** [comment]
🐘 👍

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by mdlinville — APPROVED** [review]
LGTM

**Pull request merged**
