### PR TITLE
We don't need image layer stream when create the rootfs

### PR DESCRIPTION
**Pull request by HuKeping**
Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM assuming jank's happy

**Comment by duglin** [comment]
Nice catch - LGTM after janky is done

**Comment by HuKeping** [comment]
lol

**Comment by vdemeester** [comment]
Lot's of pression on janky :sweat_smile: :stuck_out_tongue_closed_eyes:

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
