### PR TITLE
Yet better mountinfo parser

### PR DESCRIPTION
**Pull request by kolyshkin**
* Speed up mountinfo parser a little bit further
* Change the separator field search logic
* Add FstypeFilter and use it in zfs gd
* Add some tests and benchmarks

See individual commits for details.

WRT performance -- it's hard to do a clean test but there is an improvement up to 20% depending on the scenario.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Was just looking at this earlier this week, finding slightly different implementations in at least 4 repositories; https://github.com/rootless-containers/rootlesskit/pull/122#discussion_r389248942

Would it make sense to have this in a separate package (separate from the other mount stuff (not sure if all of those are generic enough for other projects)); or evening a separate repo, or included in golang.org/x/sys/unix ?

**Comment by kolyshkin** [comment]
Yeah, I guess we should separate this out to two packages: `mount` and `mountinfo`. Not sure which repo to use for it -- maybe we could create something like `opencontainers/common` (and set very strict rules as to what goes in there, to avoid vendor hell).

Such a repo would be a great place for other stuff used from many places. I can immediately think of
* xattr stuff (which I recently fixed across 3 or 4 repos!)
* parallelized filepath.Walk (recently landed to opencontainers/selinux to which it does not really belong, and use from 2 places)

I know that once you create something you call "utils", 80% of your code will end up in there, but copy-pasting the code and later having to fix in across 5 places is not good either.

I'm not sure how opencontainers is governed -- anyone we can ask about creation of such a repo?

**Comment by AkihiroSuda** [comment]
> maybe we could create something like opencontainers/common (and set very strict rules as to what goes in there, to avoid vendor hell).

Maybe we can start with `moby/mount` first.
We recently created `moby/term` and `moby/ipvs` as well.

**Comment by thaJeztah** [comment]
Yes, I think something in the moby/ org should also be ok. As long as the package has a clear scope, is testable on its own, and doesn't update often (IOW, not having to go through update upstream -> tag/release -> revendor cycles), it shouldn't be a big burden to have it separate.

(my 0.02c)

**Comment by kolyshkin** [comment]
OK let me try to split out mountinfo part.

**Comment by AkihiroSuda** [comment]
Can we close this?

**Comment by kolyshkin** [comment]
Yes (the only commit that makes sense is the last one, but it needs to be redone).

Closed in favor of https://github.com/moby/moby/pull/40694

**Pull request closed without merging**
