### PR TITLE
volume/store: fix couple of races with accessing maps

### PR DESCRIPTION
**Pull request by LK4D4**
**\- What I did**
Fixed races in volume/store
**\- How I did it**
Added locks around maps access
**\- How to verify it**
Build docker with -race and try to play with volumes
**\- A picture of a cute animal (not mandatory but encouraged)**
cat

### CODE REVIEW

**Comment by cpuguy83** [comment]
Ooo, this might need to go into 1.11.


LGTM

**Comment by thaJeztah** [comment]
@cpuguy83 if you think it's safe to add, please do

**Comment by icecrime** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐰

**Pull request merged**
