### PR TITLE
Double check 401 responses in case proxy intercepts authorization headers

### PR DESCRIPTION
**Pull request by jongiddy**
**\- What I did**

I modified the v1 pull code to retry if it receives a 401 Unauthorized error. This deals with proxies that expect authorization to follow the typical browser pattern of request with no Authorization header, response with 401, and subsequent request containing an Authorization header.  See https://github.com/docker/docker/issues/22503

**\- How I did it**

Initially, I modified the `GetRemoteTag` and `GetRemoteTags` functions to check if any 401 response includes a `Set-Cookie` header, and re-try in that case, to get past a proxy that intercepts Authorization headers unless a cookie is set.  The prescence of the cookie is how the proxy determines that the authorization request is a follow-up to a 401 error.

This added a lot more commonality to the `GetRemoteTag` and `GetRemoteTags` functions, so I then refactored the common code into a separate function.  This change highlighted that the functions were deferring closes inside a loop, which is not really a good idea. So, I also modified the code to close the body inside each iteration.

Things I didn't do:
- figure out how to make this work for v2 pull.
- emit a message advising the user that, for better performance, they might consider modifying their proxy rules.
- provide a test that mocks the described proxy pattern.

**\- How to verify it**

First, run a proxy that strips Authorization headers from requests, unless a cookie is set. The proxy sets a suitable cookie in any 401 responses.

In this case, `docker pull docker/whalesay` or `docker pull -a docker/whalesay` will fail with the message `Could not reach any registry endpoint`.

With this change, both commands will succeed, although warning that `this image was pulled from a legacy registry`.

Logs will show that requests were retried:

```
Jun 10 10:31:54 localhost docker: time="2016-06-10T10:31:54.032176288Z" level=de
bug msg="Got status code 401 from https://registry-1.docker.io/v1/repositories/d
ocker/whalesay/tags, retrying..."
Jun 10 10:31:54 localhost docker: time="2016-06-10T10:31:54.615268091Z" level=de
bug msg="Got status code 200 from https://registry-1.docker.io/v1/repositories/d
ocker/whalesay/tags"
```

**\- Description for the changelog**
Retry a request that returns 401, in case a proxy expects cookies with authorization requests

**\- A picture of a cute animal (not mandatory but encouraged)**

```
 ^..^
( oo )  )~
  ,,  ,,
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @jongiddy! Looks like there's a golint issue;

```
11:20:18 ---> Making bundle: validate-lint (in bundles/1.12.0-dev/validate-lint)
11:20:18 Errors from golint:
11:20:18 registry/session.go:312:19: don't use underscores in Go names; method get_response_body should be getResponseBody
11:20:18 
11:20:18 Please fix the above errors. You can test via "golint" and commit the result.
```

**Comment by thaJeztah** [comment]
also /cc @aaronlehmann @dmcgowan PTAL

**Comment by dmcgowan** [comment]
@jongiddy this change is very specific to a single network configuration and involves interacting with cookies unused by Docker. I think I understand the problem but don't see it justifying adding a second attempt at a request for all 401 scenarios where a cookie set header exists.

Currently proxies are supported by setting the `HTTPS_PROXY` environment variable on the engine. Most proxies should support the `CONNECT` used to get around awkward flows like you described. If I am missing something please let me know, otherwise it is probably better to close this PR.

V1 registry support has been deprecated and we do encourage upgrading to V2. We normally don't accept behavioral changes that only effect v1 unless it addresses a critical bug.

**Comment by jongiddy** [comment]
@dmcgowan I'm very sympathetic to your view. The issue clearly lies with the proxy configuration which prevents Authorization headers in an initial request. It's completely valid to add Authorization headers up front when you know that they are needed.

However, the company that makes this proxy claim to be used by over 70% of the Fortune Global 500, and this appears to be their default configuration. So, potentially, there are people trying to introduce Docker into large companies and finding that it just doesn't work.

As indicated by my "things I didn't do", I definitely don't think this is the best fix. I did look at the V2 code, but couldn't figure out how to change that code to make it work. I can't see how any setting of `HTTPS_PROXY` would make this work. As suggested in #22503 an alternative solution might be to allow the Docker daemon to supply admin-configured cookies other than the `X-Meta` cookies passed now.  However, the actual cookie to be sent from a particular machine would have to be obtained and added manually.

**Comment by dmcgowan** [comment]
@jongiddy Ok, I understand now why `HTTPS_PROXY` will not work since it will still alter the request. Is the proxy adding the `Set-Cookie` or is it expected that the registry would?  Also what is occurring right now when you pull from a v2 registry? With v2 there is an initial 401 response from the registry however it will send credentials immediately to the token server an wondering if that is where it would fail. If you are using basic auth directly with a private v2 registry though then the interaction would match the proxies expectation, minus the registry setting a cookie.

**Comment by jongiddy** [comment]
The registry is not aware of any of this. The fundamental problem is that the proxy is configured to remove any `Authorization` header from a request, unless a client-host-specific cookie is also present. The proxy returns the required cookie to the client in any 401 response.

The value of the cookie is specific to the client host, but is always the same for that host. This means one way to fix it is to set the cookie in the request, if this is supported.

The more automatic way is to perform a request, receive the 401, and perform the request again with the authorization and cookie set (i.e. the typical behavior of web browsers).

I'm not really clear on how the V2 call is failing, as the log file is not particularly clear on which URLs it is calling. You can see the log in https://github.com/docker/docker/issues/22503#issuecomment-217855884.

**Comment by thaJeztah** [comment]
ping @dmcgowan what's the status on this one?

**Comment by dmcgowan** [comment]
Closing this issue as it only relates to V1 interactions which we have deprecated and do not want to continue to support behavioral changes. 

@jongiddy we are interested in adding cookie support for the V2 protocol to address issues with proxies. We are also open to discussing a method for retrying after cookies are set. Let's move this work over the [distribution project](https://github.com/docker/distribution) where the v2 client code is. Feel free to join the discussion on https://github.com/docker/distribution/issues/1818.

**Pull request closed without merging**
