### PR TITLE
Make manpages in a container when creating deb/rpm

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Comment by justincormack** [comment]
Yes, I noticed this this morning, but didnt test it was actually an issue.

LGTM.

**Comment by thaJeztah** [comment]
LGTM

**Comment by StefanScherer** [comment]
Just found out that this breaks `make deb` on ARM. 😁  I thought that hack/make/build-deb is already running inside a container and this calls make manpages. This step pulls `golang:1.6.3-alpine` from Docker Hub which is amd64 only(?) right now.

**Comment by thaJeztah** [comment]
@StefanScherer can you open an issue for that? Do we have a workaround for that (other base image?)

**Comment by StefanScherer** [comment]
@theJeztah Will do and also have a look how to fix it. What was wrong with man/generate.sh? Haven't followed the discussion.

**Comment by thaJeztah** [comment]
@StefanScherer see https://github.com/docker/docker/pull/23825

**Pull request merged**
