### PR TITLE
17.03.x

### PR DESCRIPTION
**Pull request by henryhqhuang**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks to be opened accidentally; closing

**Comment by inosgun** [comment]
[](url)155435b6ceeb05b2927ecc726216666b898b6459

**Comment by inosgun** [comment]
[Uploading CDJ-TOUR1_UpdateGuide100-En (2).pdf…]()

**Comment by cpuguy83** [comment]
Deleted 2 comments which contained links (looked like they uploaded some files) without any context or anything which looked super suspicious.
Sorry if this was a real post, but it definitely did not look like it.

**Comment by thaJeztah** [comment]
Yeah, looks like another spam account; I reported the account for abuse/spam

**Pull request closed without merging**
