### PR TITLE
Windows: Remove TP5 hack from graphdriver

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Removes the TP5 hacks which were present in the graphdriver for Windows.

cc @swernli @jstarks

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Ok, github....

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
