### PR TITLE
[WIP] Fix runconfig Config/HostConfig regressions from engine removal

### LINKED ISSUE #14338: Config/HostConfig regressions
Similar to #14318 and #14170. Some Config/HostConfig options suffer from a regression where previously (<1.7.0) it was possible to just pass a string in json and  be adapted to be a strings slice (old engine `GetenvList`) while now it isn't possible anymore cause we are directly decoding in `[]string`

`Dns` and `DnsSearch` are suffering the same issue (compose moves a single string to a list if there's only one element https://github.com/docker/compose/blob/77c939b256dbed699fdc4643114bea543208a660/compose/service.py#L570 so this could have been missed)
I'm fixing `Dns` and `DnsSearch` though, and I still haven't looked at all the options

/cc @aanand @calavera @LK4D4

### PR DESCRIPTION
**Pull request by runcom**
Some Config/HostConfig fields suffer from a regression where previously
(<1.7.0) it was possible to just pass a string (via remote API) in json
and be adapted to be a string's slice (old engine `GetenvList` behavior).
As of now it isn't possible anymore cause we are directly decoding into `[]string`.
This patch fixes these regressions and add a deprecation notice on
affected fields for this behavior.

close #14338
- [x] Add docs
- [ ] Fix tests
- [x] Fix panic on win janky

Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by runcom** [comment]
As this patch is using `stringutils.StrSlice`, two tests are failing because of this
#15567 was opened to fix this behavior I suppose
ping @duglin @cpuguy83 @shishir-a412ed

**Comment by runcom** [comment]
Tests are green locally by applying diff from #15567 from @shishir-a412ed tho

**Comment by duglin** [comment]
@runcom as I mentioned in irc, I might be missing some aspects of this but here's my current thinking...
- I'm not thrilled with the new StrSlice stuff - it feels like a hack
- the api/types/types.go structs should be exactly what we want people to see in the json - likewise, since those structs are used by the `--format` code for things like `docker inspect` the JSON and the structs need to match, exactly - meaning no special serialization code and no mapping of field names.  See #15567
- the internal structs (like runconfig stuff) should be exactly what we want to store on disk - if they're saved. IOW, we shouldn't do anything special in there just because of the on-the-wire JSON serialization.
- the two structs (api/types vs internal) should (obviously) be related but its ok if they don't match exactly - we should have mapping code that moves data between the two structs - giving each the freedom to "do what's right" w/o worrying about the other.  I think #15567 is headed this way for some of this.

Now, that's all nice but then how do we solve this issue - meaning, how do we allow for a string when the struct is expecting a []string ?

One option is to have the code that deserializes the JSON examine the []string fields afterwards and see if they're empty. If they are then it could be due to the JSON having a string instead.  For each empty []string we could look at the `interface{}` version of the JSON and see if there's a string for that field - and if so, convert it to a []string.  By `interface{}` version of the JSON I mean, use something like:
```
var m interface{}
dec := json.NewDecoder(reader)
dec.Decode(&m)
```

**Comment by runcom** [comment]
> I'm not thrilled with the new StrSlice stuff - it feels like a hack

me neither, it seems to be so invasive

> the api/types/types.go structs should be exactly what we want people to see in the json - likewise, since those structs are used by the --format code for things like docker inspect the JSON and the structs need to match, exactly - meaning no special serialization code and no mapping of field names. See #15567

> the internal structs (like runconfig stuff) should be exactly what we want to store on disk - if they're saved. IOW, we shouldn't do anything special in there just because of the on-the-wire JSON serialization.

Totally agree, we should do exactly what we're doing with `types.ContainerJSON`  and `daemon.Container` so the behavior here is consistent with the container one - `--format` flag is formatting `types.ContainerJSON` not `daemon.Container` 

> the two structs (api/types vs internal) should (obviously) be related but its ok if they don't match exactly - we should have mapping code that moves data between the two structs - giving each the freedom to "do what's right" w/o worrying about the other. I think #15567 is headed this way for some of this.

We already have code mapping internal to external struct in `daemon/inspect.go` iirc so this will be needed for sure.

That said, while I like the interface thinghie cause it will eventually be supported for just two releases (as per deprecation policy), it still sounds hacky but if it's the only thing left to do I'll go for it.

**Comment by icecrime** [comment]
Ping @runcom: what do we do with that?

**Comment by runcom** [comment]
@icecrime this patch depends on https://github.com/docker/docker/pull/15567 so that should be merged first (maybe) but it still needs some eyes to be merged. After that, this is free to be reviewed.

**Comment by shishir-a412ed** [comment]
@icecrime @runcom For #15567 I am waiting on maintainers to agree on the solution. (Possibly a versioned API to solve that). Once we have an agreement, I ll be happy to make the changes.

**Comment by runcom** [comment]
@shishir-a412ed thanks, I left a comment there with a possible solution and some thoughts, @icecrime if you have some time/thoughts you may want to have a look there

**Comment by runcom** [comment]
I'm gonna rework this and resubmit because too many things have changed in master and it's a mess to rebase

**Pull request closed without merging**
