### PR TITLE
Convert script shebangs from "#!/bin/bash" to "#!/usr/bin/env bash"

### PR DESCRIPTION
**Pull request by tianon**
This is especially important for distributions like NixOS where `/bin/bash` doesn't exist, or for MacOS users who've installed a newer version of Bash than the one that comes with their OS.

**- What I did**

Swapped `#!/bin/bash` for `#!/usr/bin/env bash`.

**- How I did it**

I used `grep` + `sed`, then manually verified each change as I added it.

**- How to verify it**

Run the scripts and make sure `bash` is still invoked? :smile:

**- Description for the changelog**

- Updated shell script shebangs to use `/usr/bin/env bash` instead of hard-coding `/bin/bash`

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by tianon** [comment]
As discussed with @vdemeester over in https://github.com/docker/docker/pull/29864#discussion_r100864359. :+1:

cc @albers

**Comment by albers** [comment]
@tianon :heart: for the pic!
I didn't know about `/usr/bin/env` before.
As far as bash completion is concerned, the hash bang has no effect because the completion scripts get sourced. So :+1: from me.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸 ❤️

**Comment by lai-nam** [comment]
@tianon : could I see your command use "grep + sed".

**Pull request merged**
