### PR TITLE
fix docker swarm init/update --secret

### LINKED ISSUE #23592: [1.12.0-RC1] Breaking change in API handling of StorageOpts
See docker/engine-api#279

> #151 broke backward compat, since StorageOpt is unused most of a time, let's put an omitempty to prevent unmarshalling error.

We need to bump docker/engine-api for 1.12.0-RC2 and fix this issue.

### LINKED ISSUE #23595: [1.12.0-RC1] Updating Swarm secret is broken
It seems `docker swarm update --secret` doesn't register into the backend.

Cc @vieux.

### PR DESCRIPTION
**Pull request by vieux**
scenario1:
`docker swarm init`
`docker swarm inspect` -> no secret
`docker swarm update --secret XXX`
`docker swarm inspect` -> you see the hashs

scenario2:
`docker swarm init  --secret XXX`
`docker swarm inspect` -> you see the hashs

then

`docker swarm update --auto-accept manager` 
`docker swarm inspect` -> you still see the hashs
`docker swarm update --secret ""`
`docker swarm inspect` -> no secret

fix #23595 
fix #23592

### CODE REVIEW

**Comment by vieux** [comment]
ping @diogomonica @tonistiigi

**Comment by diogomonica** [comment]
LGTM. Would love to have an integration test for the update component of secret (to make sure this doesn't happen in the future)

**Comment by vieux** [comment]
a test was contributed by @tonistiigi

**Comment by tonistiigi** [comment]
LGTM

**Comment by tonistiigi** [comment]
Merging to unblock people blocked on the `engine-api` bump. This was green before and added test has passed as well.

**Pull request merged**
