### PR TITLE
Revert "Add -a option to service/node ps"

### LINKED ISSUE #28507: [1.13 UX] docker service ps -a
As of #25983, `docker service ps` now needs the `-a` option to show tasks that failed or completed. This seems okay in cases where the service has running tasks and we simply don't show the historic tasks, but it seems confusing when nothing is running and you're trying to figure out why. It's a big UX change from 1.12 to need to run `docker service ps -a` in this situation.

As a compromise, I would suggest showing completed/failed tasks by default only if there is no running task in that slot. With the present (new) behavior, information about those slots doesn't show up at all unless you use `-a`.

cc @aluzzardi @thaJeztah

### PR DESCRIPTION
**Pull request by vdemeester**
Fixes #28507. This reverts commit 139fff2bf0ebe12b61871ba8ec8be8d51c2338db and thus `service ps -a`.

/cc @thaJeztah @icecrime @aaronlehmann @cpuguy83 

:frog: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by icecrime** [comment]
Cc @aluzzardi @vieux.

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by tiborvass** [comment]
Added impact/changelog in case we have to remove a line from the changelog.

**Comment by vieux** [comment]
LGTM ping @aluzzardi

**Comment by AkihiroSuda** [comment]
we need to revert completion as well
https://github.com/docker/docker/pull/28360/

**Comment by vdemeester** [comment]
@AkihiroSuda Good point, I'll update :angel:

**Comment by LK4D4** [comment]
two lgtms, green

**Pull request merged**
