### PR TITLE
Remove Jess from Maintainers

### PR DESCRIPTION
**Pull request by jessfraz**
Thanks.

### CODE REVIEW

**Comment by thaJeztah** [comment]
not lgtm :cry: want to be on the alumni list?

**Comment by duglin** [comment]
Why remove yourself?  Not being a docker employee doesn't change your status in the community.

**Comment by jfrazelle** [comment]
I have other reasons. It doesn't matter that I'm no longer employed by
docker.

On Wednesday, April 20, 2016, Doug Davis <notifications@github.com> wrote:

> Why remove yourself? Not being a docker employee doesn't change your
> status in the community.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/22200#issuecomment-212489616>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by vdemeester** [comment]
@jfrazelle oh nooeeesss :sob:

**Comment by icecrime** [comment]
Very much not LGTM.

**Comment by runcom** [comment]
:cry:

**Comment by tianon** [comment]
image
:heart:

**Comment by icecrime** [comment]
See? Even CI is red. We can't merge this ¯\_(ツ)_/¯

**Comment by vieux** [comment]
z3wa3c3

**Comment by jfrazelle** [comment]
The gifs are cute and I honestly love you all, but please remove me. I
don't want to be a part of a project that elects into positions of false
power & governance people who have treated me personally with extreme
levels of disrespect. I hope you all can understand that.

On Wednesday, April 20, 2016, Victor Vieux <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> [image: z3wa3c3]
> <https://cloud.githubusercontent.com/assets/1032519/14692213/8ae99eb2-070a-11e6-9968-b45d2f904303.gif>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/22200#issuecomment-212633336>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
LGTM (taking Jess's request as second LGTM)

my most painful merge ever

**Pull request merged**
