### PR TITLE
Properly fix "daemon kill" on test failure

### LINKED ISSUE #10074: Tests are hanging if failing
In #10014 was returned behavior which was hacked in #5890
We need to figure out how to fix it right way
ping @tianon and all bash-gods

### PR DESCRIPTION
**Pull request by tianon**
Fixes #10074

### CODE REVIEW

**Comment by tianon** [comment]
Wait!  This can be even slightly simpler.

**Comment by tianon** [comment]
Updated!

**Comment by tianon** [comment]
I figured we were hiding an issue with the previous fix. :+1:

So, to unwrap this a little, when we had a failure before, it wasn't running `.integration-daemon-stop`, so the daemon wasn't actually getting killed.  In our usual case, that was fine because it was backgrounded, so as soon as pid1 died (ie, our test run finished and our script exited and the container finished) the test daemon was killed by Docker for us, which isn't exactly how that ought to work. :smile:

We fix it by actually capturing the failure when it happens (in an `if` block), recording that we failed (so we can bubble that up after cleanup), killing the daemon(s) appropriately, and then bubbling up our failure.  If only, if only bash had `defer` (without resorting to funky `trap` hacks). :rocket:

**Comment by LK4D4** [comment]
```Wait! This can be even slightly simpler.```
I don't want to know what was hard way.

**Comment by tianon** [comment]
Here's my testing notes:
```console
$ cat integration-cli/fail_test.go
package main

import "testing"

func TestFail(t *testing.T) {
	t.Fatal("lolol")
}
$ make TESTFLAGS='-test.run TestFail' test-integration-cli
...
< hangs >
^C
$ # apply PR
$ make TESTFLAGS='-test.run TestFail' test-integration-cli
...
+ go test -test.run TestFail -test.timeout=30m github.com/docker/docker/integration-cli
--- FAIL: TestFail (0.00s)
	fail_test.go:6: lolol
FAIL
coverage: 1.0% of statements
exit status 1
FAIL	github.com/docker/docker/integration-cli	0.007s
++++ cat /go/src/github.com/docker/docker/bundles/1.4.1-dev/test-integration-cli/docker.pid
+++ kill 454
Makefile:71: recipe for target 'test-integration-cli' failed
make: *** [test-integration-cli] Error 1
$ 
```

**Comment by LK4D4** [comment]
I tested locally, all okay, but I still want to see what drone think about all this.
@jfrazelle I'm going to ask you to teach me drone-fu.

**Comment by LK4D4** [comment]
Drone is okay with this - LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
