### PR TITLE
Update jessfraz's github handle after she decided to break the internet

### PR DESCRIPTION
**Pull request by jphuynh**
**\- What I did**
Just updated Jess' github handle in the Org.Alumni section.

**\- How I did it**
I edited the file...

**\- How to verify it**
N/A?

**\- Description for the changelog**
Updated jessfraz's github handle in the Org.Alumni section.

**\- A picture of a cute animal (not mandatory but encouraged)**
babyotter

Signed-off-by: Jean-Pierre Huynh jean-pierre.huynh@ounet.fr

### CODE REVIEW

**Comment by justincormack** [comment]
cc @jessfraz aftershocks still coming....

**Review by justincormack — APPROVED** [review]

**Comment by jessfraz** [comment]
Lol thanks

**Comment by tiborvass** [comment]
LGTM :)

**Comment by thaJeztah** [comment]
LOL

**Pull request merged**
