### PR TITLE
Remove now unused multireader.

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM if green 🦁

**Review by thaJeztah — APPROVED** [review]
LGTM, nice cleanup 🥇

**Comment by thaJeztah** [comment]
Windows timed out;

```
20:05:04 PASS: docker_cli_volume_test.go:94: DockerSuite.TestVolumeLsFormatDefaultFormat	0.525s
20:05:34 Build timed out (after 200 minutes). Marking the build as failed.

**Comment by cpuguy83** [comment]
Definitely unrelated, merging.

**Comment by cpuguy83** [comment]
Oh, never mind I see you re-ran the test :)
Will wait.

**Comment by thaJeztah** [comment]
looks like it's still queued; yeah, let's merge

**Pull request merged**
