### PR TITLE
Bump API version to 1.33

### PR DESCRIPTION
**Pull request by thaJeztah**
creating this to unblock https://github.com/moby/moby/pull/34424

ping @simonferquel @vdemeester @dnephin PTAL

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by thaJeztah** [comment]
Looks like https://github.com/moby/moby/pull/34424 still depends on changes in swarm kit, so we should not merge in a hurry (i.e., if there's no changes to the API, the next Docker release just will use the same API version as 17.09)

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
temporarily renaming to [WIP] because 17.10 will be cut off soon, and I don't want to bump the version if there are no changes

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/issues/34988 for the flaky test

**Review by thaJeztah — COMMENTED** [review]
I'll merge this one to unblock other PR's

**Pull request merged**
