### PR TITLE
Check if the container is running if no event

### PR DESCRIPTION
**Pull request by crosbymichael**
When there is no event for the container it can happen because of a
crash and the container state on the persistent disk will have a
mismatch between what was in `/run` ( machine crash ).

This situation will create an unkillable container in docker because
containerd does not see it and it is not running but docker thinks it is
and you cannot tell it anything different.

This fixes the issue by checking if containerd has the container running
if we do not have an event instead of just returning.

Fixes the other half of #25109

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
is this doing the same / similar to https://github.com/docker/docker/pull/25072 ? @mlaventure ?

**Comment by mlaventure** [comment]
@thaJeztah  They're solving different issues.

**Comment by thaJeztah** [comment]
Is this needed for 1.12? Or should it go into 1.12.1 / 1.13?

**Comment by crosbymichael** [comment]
idk, its for an edge case

**Comment by mlaventure** [comment]
i'd say it could wait for 1.12.1

**Pull request closed without merging**
