### PR TITLE
gha: update buildkit to v0.10.5-6-ge27c8e24 to skip some tests

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/moby/buildkit/compare/v0.10.5...v0.10.5-6-ge27c8e24

- https://github.com/moby/buildkit/pull/3205

### CODE REVIEW

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
Ah, dang. It doesn't understand the `git describe` output; let me update to use the full commit 😞

**Comment by thaJeztah** [comment]
fixed 👍 🍿

**Comment by thaJeztah** [comment]
(this was the failure);

```
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/v0.10.5-6-ge27c8e24*:refs/remotes/origin/v0.10.5-6-ge27c8e24* +refs/tags/v0.10.5-6-ge27c8e24*:refs/tags/v0.10.5-6-ge27c8e24*
The process '/usr/bin/git' failed with exit code 1
```

**Comment by thaJeztah** [comment]
Bringing this one in to unblock the other PRs

**Pull request merged**
