### PR TITLE
[23.0] vendor: github.com/containerd/containerd v1.6.17

### PR DESCRIPTION
**Pull request by thaJeztah**
no changes in vendored code, other than the version bump

full diff: https://github.com/containerd/containerd/compare/v1.6.16...v1.6.17

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like the apparmor changes did not make it into the v1.6.17 release yet, and currently only in the release/1.6 branch (not yet in a tagged release); https://github.com/containerd/containerd/compare/v1.6.17...4d724f66eb8733b2391becdfaf41360a03b6368c

**Comment by neersighted** [comment]
I have #44982 open as a draft for the apparmor fix.

**Review by neersighted — APPROVED** [review]

**Comment by thaJeztah** [comment]
Oh! Hm.. actually, that made me realise that `master` is still on containerd 1.16 as well; I thought we were already on 1.17, but that's only the binary, not the vendor code.

https://github.com/moby/moby/blob/3ba527d82af53cf752aa6ec39daac14626c41b0f/vendor.mod#L28


I should probably move this one to draft, and open against master first

**Comment by neersighted** [comment]
Would it be better to just wait for 1.6.18 and take it then?

**Comment by thaJeztah** [comment]
Yeah, we can wait for that. I saw 1.6.17 was released, and I assumed that would include the fixes we needed, but looks like it was tagged before those were merged

**Comment by neersighted** [comment]
Okay, I'll close this in favor of my PR against master (waiting on a tagged 1.6.18), and then backport it to 23.0 once it's ready. After that, I think it makes sense to decide if we want 1.7 on the master branch.

**Pull request closed without merging**
