### PR TITLE
(carry 19668) don't try to install journald driver on wheezy

### PR DESCRIPTION
**Pull request by thaJeztah**
Carry of https://github.com/docker/docker/pull/19668

Fixes https://github.com/docker/docker/issues/19989

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jfrazelle @tianon for review / testing (don't have access to wheezy with the right kernel)

**Comment by jfrazelle** [comment]
LGTM thanks

**Comment by tianon** [comment]
This one's strange because our version is new enough in backports (https://packages.debian.org/wheezy-backports/libsystemd-journal0), but APT doesn't like installing it. :disappointed:

LGTM

**Comment by tianon** [comment]
(using `systemd` on wheezy probably isn't the _best_ experience anyhow, so I think this is probably just fine)

**Pull request merged**
