### PR TITLE
zfs: correctly apply selinux context

### LINKED ISSUE #13858: --selinux-enabled doesn't work with graphdriver zfs
@Mic92 

See: https://bugzilla.redhat.com/show_bug.cgi?id=1230404

It seems docker doesn't set the context when mounting the volume into the container.

### PR DESCRIPTION
**Pull request by Mic92**
fixes #13858

Signed-off-by: Jörg Thalheim joerg@higgsboson.tk

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @rhatdan

**Comment by rhatdan** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
cherrypicked

**Pull request merged**
