### PR TITLE
Update vendored go-ansiterm for Windows console

### PR DESCRIPTION
**Pull request by jstarks**
This update fixes Windows client console bugs and increases VT100 compatibility. With this change, nano and emacs become usable, and bash works better.

Nyan cat now also works pretty well if you specify -e TERM=linux :)

@jhowardmsft

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Yay! LGTM :)

**Comment by LK4D4** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
> Nyan cat now also works pretty well 

pics or didnt happen :cat:

**Comment by jhowardmsft** [comment]
nyan :)

**Comment by icecrime** [comment]
*Now* this is production ready :wink:

**Comment by icecrime** [comment]
We'll trust you with the test, plus it's only vendored code: LGTM.

**Pull request merged**
