### PR TITLE
integration-cli: move goroutines info helpers to separate funcs

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Comment by thaJeztah** [comment]
Looks like a flaky test on WindowsTP4 https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2759/console

```
DockerSuite.TestRestartRunningContainer	28.710s
02:53:45 
02:53:45 ----------------------------------------------------------------------
02:53:45 FAIL: docker_cli_restart_test.go:13: DockerSuite.TestRestartStoppedContainer
02:53:45 
02:53:45 docker_cli_restart_test.go:24:
02:53:45     c.Assert(out, checker.Equals, "foobar\nfoobar\n")
02:53:45 ... obtained string = "foobar\n"
02:53:45 ... expected string = "" +
02:53:45 ...     "foobar\n" +
02:53:45 ...     "foobar\n"
02:53:45 
02:53:45 
02:53:45 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
All green, merging \o/

**Pull request merged**
