### PR TITLE
Check if the container is running if no event

### PR DESCRIPTION
**Pull request by crosbymichael**
When there is no event for the container it can happen because of a
crash and the container state on the persistent disk will have a
mismatch between what was in `/run` ( machine crash ).

This situation will create an unkillable container in docker because
containerd does not see it and it is not running but docker thinks it is
and you cannot tell it anything different.

This fixes the issue by checking if containerd has the container running
if we do not have an event instead of just returning.

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by icecrime** [comment]
Adding this as a P0 to the 1.12.0 milestone: the impact was overlooked, as it's relatively easy to hit this issue when the daemon gets killed while it's shutting down (e.g., init script's timeout).

LGTM!

**Comment by mlaventure** [comment]
LGTM.

**Comment by crosbymichael** [comment]
@justincormack 

[docker.tar.gz](https://github.com/docker/docker/files/388850/docker.tar.gz)

**Comment by icecrime** [comment]
Ignoring Janky failure on `TestApiSwarmRestartCluster`(fixed by #25077).

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
I would like @justincormack to confirm as well before merging

**Comment by justincormack** [comment]
LGTM

**Pull request merged**
