### PR TITLE
Fix race in FirewalldInit

### PR DESCRIPTION
**Pull request by LK4D4**
It was possible that signalHandler won't start because connections is
not assigned.

### CODE REVIEW

**Comment by jfrazelle** [comment]
do you use firewalld, how did you find this :)

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
Yeah, I use firewalld since merge. But I think that race detector doesn't mind :) He just finding races in code.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
