### PR TITLE
Adding back in Glossary

### PR DESCRIPTION
**Pull request by moxiegirl**
Accidentally removed by #11897

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
Ah, great!

LGTM (waiting on lights to go green)

**Comment by thaJeztah** [comment]
Oh, janky! Kicking..

**Comment by moxiegirl** [comment]
@thaJeztah thanks for the kick!

**Comment by thaJeztah** [comment]
@moxiegirl my pleasure, it felt gooood! 💫

*(No jankies were harmed in this contribution)*

**Pull request merged**
