### PR TITLE
Use global random *rand.Rand instance in pkg

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
Docker-py error in experimental: https://jenkins.dockerproject.org/job/Docker-PRs-experimental/4215/console

```
======================================================================
ERROR: runTest (__main__.TestCreateContainerWithLinks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/docker-py/tests/integration_test.py", line 72, in tearDown
    self.client.remove_container(container)
  File "/docker-py/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/docker-py/docker/client.py", line 690, in remove_container
    params=params)
  File "/docker-py/docker/clientbase.py", line 89, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 526, in delete
    return self.request('DELETE', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
    raise Timeout(e)
Timeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=5)

```

**Pull request merged**
