### PR TITLE
do not stop health check before sending signal

### PR DESCRIPTION
**Pull request by ghost**
Docker daemon always stops healthcheck now before sending signal
to a container now. However, when we use "docker kill" to send
signals other than SIGTERM or SIGKILL to a container, such as SIGINT, 
daemon still stops container health check though container process 
handles the signal normally and continues to work.

**- What I did**
Fix that container health check stops working when sending signals to a container by `docker kill`.
**- How I did it**
Do not stop health check before sending signal to a container.
Daemon state monitor can stop health check when container state changes to exit.
**- How to verify it**
Run a container with health check.
Send signal other than SIGTERM or SIGKILL to container by `docker kill`.
Check container health status by `docker inspect`.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Kazero0** [comment]
Do i need to start an issue to describe the bug?

**Comment by WeiZhang555** [comment]
ping docker maintainers @cpuguy83 @vdemeester @thaJeztah 
I think this is a bug fix.

**Review by thaJeztah — APPROVED** [review]
SGTM, but would like some other maintainers to have a look as well, in case I overlook something 

ping @mlaventure @vdemeester @tonistiigi PTAL

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
Can you add a test case for this?

**Comment by mlaventure** [comment]
Thanks for the PR @Kazero0, the change makes sense to me, I would indeed consider it a bug fix, but a test would be useful indeed :)

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by Kazero0** [comment]
Sorry that I've forgotten this patch. :(
Testcase updated.

**Pull request closed without merging**
