### PR TITLE
Zsh completion for '--alias --net-alias --ip --ip6 --link'

### PR DESCRIPTION
**Pull request by sdurrheimer**
- `docker network connect --alias` and `docker {run,create} --net-alias` ref. #19242
- `docker network connect --ip --ip6` and `docker {run,create} --ip --ip6` ref. #19001
- `docker network connect --link` ref. #19229

@vincentbernat

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by vincentbernat** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, thanks @sdurrheimer, awesome to see you picking up all the completions, apologies if I forgot to "ping" you on PR's :heart:

**Comment by thaJeztah** [comment]
Ignoring windows CI, completion scripts are not tested during CI

**Comment by sdurrheimer** [comment]
@thaJeztah You're welcome :)

**Pull request merged**
