### PR TITLE
Restoring the RPM build process for Oracle Linux 6

### LINKED ISSUE #18688: building oracle linux 6 rpm fails on master
error:
```
bundles/1.10.0-dev already exists. Removing.

---> Making bundle: dynbinary (in bundles/1.10.0-dev/dynbinary)
# github.com/opencontainers/runc/libcontainer/nsenter
In file included from vendor/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:20:
/usr/include/linux/netlink.h:35: error: expected specifier-qualifier-list before 'sa_family_t'
error: Bad exit status from /var/tmp/rpm-tmp.GmZ0bL (%build)
    Bad exit status from /var/tmp/rpm-tmp.GmZ0bL (%build)
```

@Djelibeybi do you know if the version of C in that image would need something specific

### PR DESCRIPTION
**Pull request by Djelibeybi**
Also, update the docker-engine.spec file to require the Unbreakable Enterprise Kernel Release 4 on both Oracle Linux 6 and Oracle Linux 7.

The UEK R4 provides the required kernel functionality for VxLAN support required by Docker 1.9 and user namespace support required for 1.10+.

The build of Docker on Oracle Linux 6 requires some manipulation of the build environment so that the CGO compiler uses the UEK R4 headers instead of the old default kernel headers.

This resolves #18688 as well.

Signed-off-by: Avi Miller avi.miller@oracle.com

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Ping @jfrazelle and @thaJeztah for review. Hopefully this makes it before the code freeze for 1.10.

**Comment by jfrazelle** [comment]
cool i will try this out thanks

**Comment by jfrazelle** [comment]
```

**Comment by Djelibeybi** [comment]
Weird, the RPM build process worked fine on my test rig. Let me check that line again.

**Comment by Djelibeybi** [comment]
I hit stage 5 in debugging: "How did this ever work?" :) Should be good now.

**Comment by jfrazelle** [comment]
LGTM

**Comment by Djelibeybi** [comment]
Is there a particular reason why this didn't get merged for 1.10? I did a bunch of stuff internally to get this working before the code freeze.

**Comment by jfrazelle** [comment]
we can cherry pick it in to the next rc

**Comment by thaJeztah** [comment]
Apologies @Djelibeybi I think this one dropped of our radar; we'll make sure it's in the next rc

**Comment by Djelibeybi** [comment]
Thanks guys! Glad that 1.10 will be released for OL6 too. :)

**Pull request merged**
