### PR TITLE
Replace deprecated grpc.ErrorDesc() and grpc.Code() calls

### PR DESCRIPTION
**Pull request by thaJeztah**
@cpuguy83 @vdemeester

### CODE REVIEW

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
PowerPC and Z failed to #38460

**Comment by olljanat** [comment]
Derek add label: rebuild/z

**Comment by olljanat** [comment]
Derek add label: rebuild/powerpc

**Comment by olljanat** [comment]
Derek add label: rebuild/powerpc

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
