### PR TITLE
testing: bump docker-py to 4.2.0

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/docker/docker-py/compare/4.1.0...4.2.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
@stefanscherer any idea what this failure is?

https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-40467/runs/1/log/?start=0

```
Creating placeholder flownodes because failed loading originals.

GitHub has been notified of this commit’s build result

java.io.IOException: Tried to load head FlowNodes for execution Owner[moby/PR-40467/1:moby/PR-40467 #1] but FlowNode was not found in storage for head id:FlowNodeId 1:283
```

**Comment by StefanScherer** [comment]
@thaJeztah I have no idea. Looked into Jenkins issues with the same error message. The best would be to re-run the build.

**Comment by thaJeztah** [comment]
yup, kicked it, and looks to be running ok now 🤷‍♂

**Review by AkihiroSuda — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
