### PR TITLE
Improve consistency in skipping tests

### PR DESCRIPTION
**Pull request by thaJeztah**
Just some nits; see the individual commits for details

### CODE REVIEW

**Review by fntlnz — APPROVED** [review]
LGTM

**Comment by fntlnz** [comment]
Test failing for windowsRS5-process:

```
12:59:11 
12:59:11 ----------------------------------------------------------------------
12:59:11 FAIL: check_test.go:107: DockerSuite.TearDownTest
12:59:11 
12:59:11 assertion failed: error is not nil: error during connect: Get http://127.0.0.1:2357/v1.40/containers/json?all=1&limit=0: dial tcp 127.0.0.1:2357: connectex: No connection could be made because the target machine actively refused it.: failed to list containers
```

I'm not sure it's related to your changes.

**Comment by thaJeztah** [comment]
Hm, failing again, so perhaps it _is_ related 🤔 

```
12:59:11 FAIL: check_test.go:107: DockerSuite.TearDownTest
12:59:11 
12:59:11 assertion failed: error is not nil: error during connect: Get http://127.0.0.1:2357/v1.40/containers/json?all=1&limit=0: dial tcp 127.0.0.1:2357: connectex: No connection could be made because the target machine actively refused it.: failed to list containers
12:59:11 assertion failed: error is not nil: error during connect: Get http://127.0.0.1:2357/v1.40/images/json: dial tcp 127.0.0.1:2357: connectex: No connection could be made because the target machine actively refused it.: failed to list images
12:59:11 assertion failed: error is not nil: error during connect: Get http://127.0.0.1:2357/v1.40/volumes: dial tcp 127.0.0.1:2357: connectex: No connection could be made because the target machine actively refused it.: failed to list volumes
12:59:11 assertion failed: error is not nil: error during connect: Get http://127.0.0.1:2357/v1.40/networks: dial tcp 127.0.0.1:2357: connectex: No connection could be made because the target machine actively refused it.: failed to list networks
12:59:11 
12:59:11 ----------------------------------------------------------------------
12:59:11 PANIC: docker_cli_run_test.go:1791: DockerSuite.TestRunInteractiveWithRestartPolicy
12:59:11 
12:59:11 assertion failed: 
12:59:11 Command:  d:\CI\CI-cc99654c7e\binary\docker.exe stop test-inter-restart
12:59:11 ExitCode: 1
12:59:11 Error:    exit status 1
12:59:11 Stdout:   
12:59:11 Stderr:   error during connect: Post http://127.0.0.1:2357/v1.30/containers/test-inter-restart/stop: read tcp 127.0.0.1:64033->127.0.0.1:2357: wsarecv: An existing connection was forcibly closed by the remote host.
12:59:11 
12:59:11 
12:59:11 Failures:
12:59:11 ExitCode was 1 expected 0
12:59:11 Expected no error
12:59:11 ... Panic: Fixture has panicked (see related PANIC)
12:59:11 
```

**Comment by thaJeztah** [comment]
hm, I didn't touch that file, wondering if it failed to cleanup a daemon (e.g.)

**Comment by thaJeztah** [comment]
ah, never mind; it wasn't restarted the first time; used `rebuild/*` this time, and looks to be running again now; 🤞

**Review by AkihiroSuda — APPROVED** [review]

**Comment by olljanat** [comment]
@thaJeztah needs a rebase

**Comment by thaJeztah** [comment]
rebased 👍

**Comment by thaJeztah** [comment]
merging; powerpc failure is a known flaky test (`TestSwarmLockUnlockCluster`) and not related

**Pull request merged**
