### PR TITLE
Fixing a case of dangling endpoint during ungraceful daemon restart

### LINKED ISSUE #17413: Container attached to an overlay network does not restart after reboot.
Description of problem:

A container that was created, attached only to an overlay network, cannot be started after reboot.

`docker version`: 

Client:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   60d36f7
 Built:        Fri Oct 23 02:14:44 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   60d36f7
 Built:        Fri Oct 23 02:14:44 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:

Containers: 22
Images: 117
Server Version: 1.9.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-253:33-2359299-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.314 GB
 Data Space Total: 107.4 GB
 Data Space Available: 34.65 GB
 Metadata Space Used: 11.16 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.797 GiB
Name: hcf-core
ID: <omitted>
Labels:
 com.docker.network.driver.overlay.bind_interface=eth0
Cluster store: etcd://10.0.0.15:3379

`uname -a`:

Linux hcf-core 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

HP Public Cloud (OpenStack)

How reproducible:

Every time.

Steps to Reproduce:
1. Create overlay network
2. Run container as a member of the overlay network *only* with --restart=always.
3. Reboot container host

Actual Results:

Container will not be running. If started manually via `docker start testhttp`, will receive: "Error response from daemon: Cannot start container 1a16b63844777e5adb61cd2408e5de72012d58fbd4c4bd340ccee5750219012c: container already connected to network hcf"

Expected Results:

Container should be running, connected to expected network.

Additional info:

Created the overlay network as:

    docker network create -d overlay --subnet="192.168.252.0/16" --gateway="192.168.252.1" hcf 

Ran the container as:

    docker run -d --restart=always --net=hcf -p=8000:80 --name=testhttp -t nginx

### PR DESCRIPTION
**Pull request by mavenugo**
fixes #17413

As described in #17413 , its a tricky reproduction case & writing an IT for this case is a bit more involved.
We rely on the e2e libnetwork IT for any overlay related cases (also some of the ungraceful restart scenarios).

### CODE REVIEW

**Comment by tiborvass** [comment]
@mavenugo TestLinksHostsFilesInject is failing on userns, can you doublecheck?

**Comment by mavenugo** [comment]
@tiborvass I dont think this is related to this PR. I will try to retrigger the userns for now. But I will try to reproduce it to see whats going on.

**Comment by mavenugo** [comment]
@tiborvass seems like a flaky one. it finished fine this time. PTAL

**Comment by LK4D4** [comment]
Maybe it fixes #15857 as well? I'm pretty tired to remove hundreds of namespaces and veth pairs :)

**Comment by mavenugo** [comment]
@LK4D4 we do a cleanup of leaked network resources (caused by ungraceful restart) during daemon start. this was addressed few days back in another PR.
This PR addresses a special case of ungraceful daemon restart as described in the commit message.

**Comment by tiborvass** [comment]
LGTM

**Comment by vdemeester** [comment]
Would there be a way to write a test on that ? Like killing a daemon & such :sweat_smile:

**Comment by LK4D4** [comment]
@vdemeester Indeed, and we already have similar test for mounts.

**Comment by mavenugo** [comment]
@vdemeester @LK4D4 yes we could. But the trouble here is the rest of the entourage for testing it e2e. like a KV-Store and a valid remote network driver with the valid driver making use of this KV-Store. All these tests are in libnetwork though, where we use BATS. We have plans of porting all of them to docker/docker.

**Comment by tiborvass** [comment]
@LK4D4 @vdemeester as much as I want to have a test too, this one apparently was very hard to reproduce reliably. I'm fine with this PR as-is.

**Comment by cpuguy83** [comment]
Confirmed this fixes the behavior.
LGTM

**Comment by tiborvass** [comment]
Thanks @cpuguy83

**Comment by vdemeester** [comment]
@tiborvass yeah no problemo, was just thinking out loud :stuck_out_tongue_closed_eyes:

**Pull request merged**
