### PR TITLE
Update local capital package name

### PR DESCRIPTION
**Pull request by zhengguoyong**
local package name should not coatain capital, kill them.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@zhengguoyong can you sign-off your commits? Thanks!

**Comment by zhengguoyong** [comment]
Done,  please review, thanks.

**Comment by LK4D4** [comment]
@zhengguoyong Need rebase

**Comment by LK4D4** [comment]
There is no lxc package anymore, so we can say that it's fixed.
@zhengguoyong Thanks!

**Pull request closed without merging**
