### PR TITLE
Researching Docker Hub account linking and automated builds details

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit SvenDowideit@home.org.au

I'm thinking of moving the over-load of detail in the 'Linking your GitHub account' into a separate document - any opinions?

### CODE REVIEW

**Comment by thaJeztah** [comment]
> I'm thinking of moving the over-load of detail in the 'Linking your GitHub account' into a separate document - any opinions?

In general, I like shorter, to-the-point documents. However, is the "linking your account" also used for anything else than automated builds? Is it useful as a stand-alone document?

I think it could be useful if the main drop-down menu would have sub menus, (ie "automated builds" -> step 1 step 2) and all main sections would be a separate document


Question; have you optimized the new images? If you're running on OS X, this is a handy tool to do this;
https://imageoptim.com

**Comment by SvenDowideit** [comment]
no, I haven't optimized them, and no, I don't run OSX :) I guess we really need a containerized tool to do it. :/

Y, I'm concerned that the "linking your account" section, which only needs to be done once (per GH/BitBucket user, and once per GH org) is totally over-powering the more important meat of the page.

and no, the link is only used for automated builds :/

**Comment by fredlf** [comment]
Yes, I think moving the Linking section makes a ton of sense. Maybe it should get moved to the "http://docs.docker.com/docker-hub/accounts/#docker-hub-accounts" page. That page, in turn, should get repurposed/revised to "Setting up your Account". That way, all the one-time set-up and config stuff will live on one page. And then I think we should move the users and groups info on the account page to a separate page of its own (since that info is inadequate and we need to expand it).

Does that make sense?

**Comment by SvenDowideit** [comment]
I'll do the move in a later PR, as that will go with some other changes I'm working on there (which need more research)

@docker/docs-owners

**Comment by thaJeztah** [comment]
> no, I haven't optimized them, and no, I don't run OSX :) I guess we really need a containerized tool to do it. :/

Yes, I was already playing with that thought (the tool is just a wrapper for some CLI utilities); also to integrate it with "Gordon" to automatically check if images need optimization. Will create an issue for that; could be a nice "Hack" for someone to contribute.

**Comment by kencochrane** [comment]
LGTM

**Comment by jamtur01** [comment]
LGTM

**Comment by thaJeztah** [comment]
I've created a pull request against @SvenDowideit s repo to optimize the images;
https://github.com/SvenDowideit/docker/pull/10

However, I think he's busy this week so I hope he's able to merge that before this is merged here

**Comment by jfrazelle** [comment]
@SvenDowideit can you get rid of the merge commit

**Comment by jfrazelle** [comment]
please @SvenDowideit :) merge commit removal :)

**Comment by moxiegirl** [comment]
@jfrazelle Sven's out on PTO this week.  Earliest you can hope for is Sunday.

**Pull request merged**
