### PR TITLE
Update engine-api

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @vdemeester 

```
19:44:23 FAIL: docker_cli_pull_test.go:201: DockerHubPullSuite.TestPullAllTagsFromCentralRegistry
19:44:23 
19:44:23 docker_cli_pull_test.go:211:
19:44:23     c.Assert(linesCount, checker.GreaterThan, 2, check.Commentf("pulling all tags should provide more than two images, got %s", outImageAllTagCmd))
19:44:23 ... obtained int = 2
19:44:23 ... expected int = 2
19:44:23 ... pulling all tags should provide more than two images, got REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
19:44:23 busybox             latest              47bcc53f74dc        6 weeks ago         1.113 MB
19:44:23 
19:44:23 
19:44:56 
19:44:56 ----------------------------------------------------------------------
19:44:56 PASS: docker_cli_pull_test.go:244: DockerHubPullSuite.TestPullClientDisconnect	3.214s
19:45:29 PASS: docker_cli_pull_test.go:17: DockerHubPullSuite.TestPullFromCentralRegistry	1.835s
19:46:08 PASS: docker_cli_pull_test.go:123: DockerHubPullSuite.TestPullFromCentralRegistryImplicitRefParts	8.759s
19:46:40 
19:46:40 ----------------------------------------------------------------------
19:46:40 FAIL: docker_cli_pull_test.go:41: DockerHubPullSuite.TestPullNonExistingImage
19:46:40 
19:46:40 docker_cli_pull_test.go:112:
19:46:40     c.Assert(record.out, checker.Contains, fmt.Sprintf("Error: image %s not found", record.e.repo), check.Commentf("expected image not found error messages"))
19:46:40 ... obtained string = "" +
19:46:40 ...     "Pulling repository docker.io/library/asdfasdf\n" +
19:46:40 ...     "Error: image library/asdfasdf:latest not found\n"
19:46:40 ... substring string = "Error: image library/asdfasdf not found"
19:46:40 ... expected image not found error messages
19:46:40 
```

**Comment by vdemeester** [comment]
@cpuguy83 yes, #22247 is fixing it

**Comment by LK4D4** [comment]
@cpuguy83 #22247 seems to be merged

**Comment by cpuguy83** [comment]
Updated

**Comment by vdemeester** [comment]
LGTM 🐹

**Comment by runcom** [comment]
LGTM

**Comment by cpuguy83** [comment]
All 💚  merging.

**Pull request merged**
