### PR TITLE
Vendor hcsshim to v0.4.2

### PR DESCRIPTION
**Pull request by darstahl**
This updates hcsshim to v0.4.2 which adds the necessary support for docker top.

@jhowardmsft 

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM. Thanks! :smile:

**Comment by darrenstahlmsft** [comment]
I recreated the commit to associate with my account correctly (created the initial commit on my vendoring machine), CI was green. (see attached)
image

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
