### PR TITLE
[20.10 backport] update containerd binary v1.5.9, runc v1.0.3, and some script changes

### PR DESCRIPTION
**Pull request by thaJeztah**
Per discussion on https://github.com/moby/moby/pull/43138 https://github.com/moby/moby/pull/43138#issuecomment-1009518557;

> Can we backport this to 20.10?
>
> containerd v1.4 EOL is very soon (February 3, 2022) https://github.com/containerd/containerd/blob/main/RELEASES.md#support-horizon

This backports the containerd binary changes to the 20.10 branch for testing, first roling back / reverting the 20.10-only commits, then cherry-picking the updates from master (to preserve history of those commits)

- revert https://github.com/moby/moby/pull/43024
- revert https://github.com/moby/moby/pull/42901
- revert https://github.com/moby/moby/pull/42695
- revert https://github.com/moby/moby/pull/42657
- revert https://github.com/moby/moby/pull/42637
- revert https://github.com/moby/moby/pull/42398
- revert https://github.com/moby/moby/pull/42372

- cherry-pick https://github.com/moby/moby/pull/42149
- cherry-pick https://github.com/moby/moby/pull/42383
- cherry-pick https://github.com/moby/moby/pull/42399
- cherry-pick https://github.com/moby/moby/pull/42636
    - only the first commit (containerd binary), not the vendoring changes
- cherry-pick https://github.com/moby/moby/pull/42656
    - only the first commit (containerd binary), not the vendoring changes
- cherry-pick https://github.com/moby/moby/pull/42697
    - only the first commit (containerd binary), not the vendoring changes
- cherry-pick https://github.com/moby/moby/pull/42776
- cherry-pick https://github.com/moby/moby/pull/42674
- cherry-pick https://github.com/moby/moby/pull/42902
- cherry-pick https://github.com/moby/moby/pull/43025
    - only the first commit (containerd binary), not the vendoring changes
- cherry-pick https://github.com/moby/moby/pull/43062
    - only the first commit (runc binary), not the vendoring changes
- cherry-pick https://github.com/moby/moby/pull/43138

details below:

<details>

```bash
# https://github.com/moby/moby/pull/43024
git revert -s -S d47de2a4c7f9638ab4db17ad8c4d149e771954b9

# https://github.com/moby/moby/pull/42901
git revert -s -S 129a2000cf752e0afbe935d9e258f916becf8367
git revert -s -S 6835d15f5523063f0a04a86d4810a637c6010d62

# https://github.com/moby/moby/pull/42695
git revert -s -S e8fb8f7acd461db932bce5d7752c33fc9d75020d

# https://github.com/moby/moby/pull/42657
git revert -s -S 067918a8c3018580c86e6c6e6326f68add162876

# https://github.com/moby/moby/pull/42637
git revert -s -S 793340a33a33088f9d5f76031a59062e7e290eba

# https://github.com/moby/moby/pull/42398
git revert -s -S 56541eca9a9ec79fefb750605285d3d88899fb00

# https://github.com/moby/moby/pull/42372
git revert -s -S 01f734cb4f432760fc94a0fb6f64207628ca0662

# https://github.com/moby/moby/pull/42149
git cherry-pick -s -S -x 9b2f55bc1ca1544e407082bbfc626c4bf1745d7c

# https://github.com/moby/moby/pull/42383
git cherry-pick -s -S -x 22c0291333281e2b5d3f39b3c7bf5a31db829522

# https://github.com/moby/moby/pull/42399
git cherry-pick -s -S -x 8e3186fc8f05569200129ee5fd055eb6f25bba20

# https://github.com/moby/moby/pull/42636
git cherry-pick -s -S -x 5ae2af41eebab4e54c730d2b987bd6889dde432c

# https://github.com/moby/moby/pull/42656
git cherry-pick -s -S -x cf1328cd46987b07285fdb9f60b1b7da631f672d

# https://github.com/moby/moby/pull/42697
git cherry-pick -s -S -x 4a07b89e9a23f61de06a9390e49a3e16283f3672

# https://github.com/moby/moby/pull/42776
git cherry-pick -s -S -x b585c64e2b01f924fc358fe059871baa469bb460

# https://github.com/moby/moby/pull/42674 - see if this works
git cherry-pick -s -S -x 3c7c18a4992138ccd6e1d2a63b5ca44327f663bd
git cherry-pick -s -S -x 3cec4b8cd42179e67dcfdda2adce03516c6a5cd1
# conflict in Dockerfile.windows not yet having CONTAINERD_VERSION in it (see below)
git cherry-pick -s -S -x a7a7c732c0dc02ee5b5515f4ca868ef50cafa4a1
# conflict because hack/dockerfile/install/tomll.installer is not in this branch
git cherry-pick -s -S -x 14ff070469d8a1e1f1ea61df9593281f3147e238
# conflict in Dockerfile.windows not yet having CONTAINERD_VERSION in it
git cherry-pick -s -S -x 1b8db067856387b4cc80bd5813993475382993b6

# https://github.com/moby/moby/pull/42902
# conflict in Dockerfile.windows not yet having CONTAINERD_VERSION in it (see below)
git cherry-pick -s -S -x b746a2bf9b2a86a1072e7be719f1207a64a576fb
git cherry-pick -s -S -x fa4a9702be2a2707e7d7345272d58ff9e381f393

# https://github.com/moby/moby/pull/43025
git cherry-pick -s -S -x aef782f34844e70c79481cbecd35b01c9bb25ffa

# https://github.com/moby/moby/pull/43062
git cherry-pick -s -S -x 53397ac5391c49ebd534d06cc57b6a2a12a739d3

# https://github.com/moby/moby/pull/43138
# conflict in Dockerfile.windows not yet having CONTAINERD_VERSION in it (see below)
git cherry-pick -s -S -x df3ea5da03fcff55a47277a8190967e91b7363fa
```

Conflicts in `a7a7c732c0dc02ee5b5515f4ca868ef50cafa4a1`, and cherry-picks after that due to Dockerfile.windows not yet having CONTAINERD_VERSION in it in the 20.10 branch;

```patch
diff --cc Dockerfile.windows
index 00de2b0941,d56fce719a..0000000000
--- a/Dockerfile.windows
+++ b/Dockerfile.windows
@@@ -165,8 -165,9 +165,14 @@@ FROM microsoft/windowsservercor
  # Use PowerShell as the default shell
  SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

++<<<<<<< HEAD
 +ARG GO_VERSION=1.16.12
 +ARG GOTESTSUM_COMMIT=v0.5.3
++=======
+ ARG GO_VERSION=1.17.0
+ ARG CONTAINERD_VERSION=1.5.5
+ ARG GOTESTSUM_VERSION=v0.5.3
++>>>>>>> a7a7c732c0 (Dockerfile: use version for some utilities instead of commit-sha)

  # Environment variable notes:
  #  - GO_VERSION must be consistent with 'Dockerfile' used by Linux.
```

</details>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like we still have some test for the binary commits; need to check

```
=== RUN   TestInfoBinaryCommits
    info_linux_test.go:30: assertion failed:  (info.InitCommit.Expected string) != de40ad0 (info.InitCommit.ID string)
--- FAIL: TestInfoBinaryCommits (0.02s)
```

**Comment by thaJeztah** [comment]
whoop; CI is green now. I'm moving this out of draft, but we can discuss further

**Review by AkihiroSuda — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
containerd v1.4 reached EOL: https://github.com/containerd/containerd/pull/6614/files

Can we have Docker 20.10.13 with containerd v1.5 rpms/debs soon?

**Comment by thaJeztah** [comment]
Yes, working on that; I'll push some final packages of containerd.io 1.4, and doing test-builds of 20.10.13 (and containerd.io 1.5)

**Pull request merged**
