### PR TITLE
Restrict domain name to 255 characters

### PR DESCRIPTION
**Pull request by humaton**
Restrict domain name to 255 characters

Signed-off-by: Tomáš Hrčka thrcka@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
This one seems to have gotten lost.  Here is the bugzilla on this.

https://bugzilla.redhat.com/show_bug.cgi?id=1156308

This is just about validating input, we should check to make sure the dns specified is valid.

**Comment by tianon** [comment]
Looks like it boils down to RFC1123, which would've been helpful
information to include in this PR (not just the "what", but also the
"why"):

>      Host software MUST handle host names of up to 63 characters and
>      SHOULD handle host names of up to 255 characters.

**Comment by tianon** [comment]
Also, what's the harm caused here by allowing longer or invalid
domains besides software inside the container getting confused by the
entry in resolv.conf?

**Comment by rhatdan** [comment]
Just breakage in the app, it would be better to tell the user running the docker container that he has a typo rather then the apps running within the container blowing up at a later time for some strange reason, like can not resolve xyz.

Bottom line this is just QE guys doing due diligence on testing option parsing.

**Comment by rhatdan** [comment]
How do I reopen this one?  Seems like a simple patch, @tianon @jfrazelle @crosbymichael

**Comment by jfrazelle** [comment]
reopened

**Comment by jfrazelle** [comment]
actually I will just carry this one

**Pull request closed without merging**
