### PR TITLE
Coding style applied to `version` package

### PR DESCRIPTION
**Pull request by vdemeester**
Follow-up on #17350 to add coding-style to `version` package :wink: (`golint` all the things) 🐙.

/cc @stevvooe @tianon 

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by aaronlehmann** [comment]
:+1:

**Comment by dmcgowan** [comment]
Looks like a few cases may have been missing.  While touching this code again it is also worth pointing out the last patch moved this code to a directory called `version`, while there is also a `VERSION` file.

**Comment by thaJeztah** [comment]
Heads up: please check https://github.com/docker/docker/pull/17421

**Comment by ibuildthecloud** [comment]
I'd don't get why all cap constants are considered bad, especially since golint doesn't complain.

**Comment by vdemeester** [comment]
Closing this one, I'll redo the other one without breaking everything I hope :wink:

**Comment by stevvooe** [comment]
@ibuildthecloud This is from the coding guidelines for the Docker project and Go. Please see the section on [Mixed Caps](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps). We use common guidelines to keep the code base consistent, familiar and readable.

I don't necessarily agree that we should not use all caps, but it is more important to strive to the same coding standards as the Go project and community.

**Pull request closed without merging**
