### PR TITLE
The logName is confused here, it's a localName actually.

### PR DESCRIPTION
**Pull request by zhanghuanzhong**
As the title said.
Signed-off-by: huanzhong zhang zhanghuanzhong90@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
I suspect this was named `logName`, because it's the name used in the log-message. Guess this works as well, so

LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐻
Windows build are failing for nothing :sweat_smile: merging :wink:

**Comment by zhanghuanzhong** [comment]
Thanks for your review :)

**Comment by zhanghuanzhong** [comment]
Thanks for your review :)

**Pull request merged**
