### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by yuexiao-wang**
**\- What I did**
Fix some typos

**\- How I did it**
**\- How to verify it**
**\- Description for the changelog**
Modify it's to its

Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

### CODE REVIEW

**Comment by coolljt0725** [comment]
@yuexiao-wang  vendor's change should not be here, you should open a pr in it's own repo. :)

**Comment by yuexiao-wang** [comment]
@coolljt0725  Got it and thanks!

**Comment by yuexiao-wang** [comment]
@coolljt0725  PTAL
Done

**Comment by duglin** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
