### PR TITLE
Add zsh completion for new 'docker image' subcommands

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #26025

Same logic as @albers #27719 PR, splitting commits for better review session.

The new prune subcommand will be added in a different PR.

@vincentbernat

### CODE REVIEW

**Comment by vincentbernat** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by thaJeztah — APPROVED** [review]
LGTM

@sdurrheimer would you be okay with squashing these, now that it's reviewed?

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
