### PR TITLE
Add curators rights for olljanat

### PR DESCRIPTION
**Pull request by olljanat**
I would like to be able to rebuild these failing PR builds so maintainers don't need to worry about them.

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by olljanat** [comment]
>   you might want to add yourself to the curators list in the MAINTAINERS file;

Thanks for proposal. Did that too :sunglasses:

**Review by estesp — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Review by coolljt0725 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM 🎉

**Pull request merged**
