### PR TITLE
[1.12.x] Revert depend on docker-selinux for centos-7.3+

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Revert changes added to 1.12.5rc1 in PR #29377 "[1.12.x] depend on docker-selinux for centos-7.3+" 

**- How I did it**

$ git revert f9bc320 # only build selinux rpm if we have policy dir
$ git revert c80d82a # change dep for docker-selinux in centos-7+

**- How to verify it**

```
$ make DOCKER_BUILD_PKGS=centos-7 rpm
```

**- Description for the changelog**

(remove previous changelog line)

**- A picture of a cute animal (not mandatory but encouraged)**

😿

### CODE REVIEW

**Comment by vieux** [comment]
🏳️

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
