### PR TITLE
Add bash completion for `--cluster-store-opt` (#16644)

### PR DESCRIPTION
**Pull request by albers**
This adds bash completion for `docker daemon --cluster-store-opt`,
ref. #16644

### CODE REVIEW

**Comment by albers** [comment]
@jfrazelle @tianon Please review.

**Comment by thaJeztah** [comment]
:+1: :100: :-)

**Comment by vdemeester** [comment]
LGTM 🐅

**Comment by LK4D4** [comment]
LGTM

**Comment by albers** [comment]
@tiborvass Please include this in 1.9 as the feature is present in that release.

**Comment by albers** [comment]
@tiborvass I just noticed that this is already present in the release branch: https://github.com/docker/docker/blob/release/v1.9/contrib/completion/bash/docker#L573
Sorry, I still don't fully understand the release process and was confused by the lack of a 1.9 tag.

**Comment by thaJeztah** [comment]
@albers the release branch is branched from master at point 'X' and this was merged before the branch was created, so automatically included in the release branch.

After the release branch is created (i.e. `rc1` is out the door), fixes for that release candidate are still created against "master", but cherry-picked into the release branch.

Historically, we only add PR's to the milestone if they are an absolute requirement for a milestone, or are fixes that need to be cherry-picked into the release branch. However, I sometimes add PR's to the milestone for future reference (people asking "which release was this in")

**Pull request merged**
