### PR TITLE
router: Return explicit error rather than 404 for experimental.

### PR DESCRIPTION
**Pull request by aluzzardi**
Instead of not adding experimental routes at all, fail with an explicit
message if the daemon is not running in experimental mode.

Added the `router.Experimental` which does this automatically.

/cc @vieux @thaJeztah @icecrime @mstanleyjones

### CODE REVIEW

**Comment by aluzzardi** [comment]
```
root@0670cd012822:/go/src/github.com/docker/docker# docker service logs -f redis
Error response from daemon: This experimental feature is disabled by default. Start the Docker daemon with --experimental in order to enable it.
```

**Comment by vdemeester** [comment]
Should we do this for other `experiment` endpoint ? (like checkpoints, …)

**Comment by aluzzardi** [comment]
The only other one I could find is checkpoint.

But checkpoint is not a route, it's an entire router...

Should we mark every single route in that router as experimental?

**Comment by vdemeester** [comment]
@aluzzardi to keep things consistent I would say yes :angel:

**Comment by thaJeztah** [comment]
I like this, much cleaner!

> Should we do this for other experiment endpoint ? (like checkpoints, …)

Yes, we should, I think those were missed when making the endpoints conditional

**Comment by thaJeztah** [comment]
Also, I noticed that we did not add a note to the service-logs endpoint that it's experimental. For those endpoints we should also document the `501` status code; https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.25.md#get-service-logs

**Comment by aluzzardi** [comment]
Updated. PTAL

**Comment by aluzzardi** [comment]
The major downside is we have to pass the daemon to routers in addition to the backend.

There's another (cleaner but more complex) proposal, tell me what you think @vieux @mlaventure:
- We add an `ExperimentalRoute` interface, which inherits `Route` and adds `Enable` / `Disable`
- in `daemon.initRouter`, after creating all routers, **if** we are running in experimental, we iterate over all routers' routes, and if they match the `ExperimentalRoute` interface, we call `Enable` on them
- Done

In that scenario, we don't need to pass the daemon around.

Thoughts?

**Comment by mlaventure** [comment]
@aluzzardi the new interface sgtm

**Comment by aluzzardi** [comment]
@mlaventure Okay, taking a stab at that

**Comment by aluzzardi** [comment]
PTAL

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
