### PR TITLE
Update init scripts to use `docker daemon`.

### PR DESCRIPTION
**Pull request by calavera**
This needs to be merged after #13771.

/cc @jfrazelle, @tianon, @thaJeztah

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @calavera! LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @tianon

**Comment by icecrime** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
