### PR TITLE
should use bytes.Equal() instead of bytes.Compare()

### PR DESCRIPTION
**Pull request by wgliang**
**- What I did**
use bytes.Equal() instead of bytes.Compare()
**- How I did it**
NONE
**- How to verify it**
NONE
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
See https://github.com/moby/moby/pull/34741#pullrequestreview-60853673

**Comment by wgliang** [comment]
But that PR has been merged,I just saw this issue.

**Comment by tophj-ibm** [comment]
@wgliang you are correct #34738 was merged. He is saying here https://github.com/moby/moby/pull/34741#pullrequestreview-60853673  instead of using !bytes.Equal(value1, value2) in this file, and all of the other go test files, we should be switching to using assert.NotEqual(value1, value2) (or assert.Equal() in that case) from the already imported "github.com/stretchr/testify/assert". 

This helps keep the code consistent; you can see many examples of this already in the image/fs_test.go file

**Comment by AkihiroSuda** [comment]
Closing in favor of https://github.com/moby/moby/pull/34809/files#diff-c7ff965fd62df7c16fa6660b321def36R114

**Pull request closed without merging**
