### PR TITLE
update containerd binary to v1.7.0

### PR DESCRIPTION
**Pull request by thaJeztah**
- release notes: https://github.com/containerd/containerd/releases/tag/v1.7.0
- full diff: https://github.com/containerd/containerd/compare/v1.7.0-beta.4...v1.7.0

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```
update containerd binary to [v1.7.0](https://github.com/containerd/containerd/releases/tag/v1.7.0)
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tianon** [comment]
Heh, just a few hours off from the v1.7.0 GA - should this just go all the way? :sweat_smile:

**Comment by thaJeztah** [comment]
Yes, I can update these to v1.7.0.

Containerd maintainers were asking for my LGTM to kick off the release, and I realized we were a couple of rc's behind in our CI, so I quickly opened some (draft) PRs in all branches to verify it didn't explode

**Comment by thaJeztah** [comment]
Updated to 1.7.0 👍

**Review by rumpl — APPROVED** [review]

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
Let me bring this one in 👍

**Pull request merged**
