### PR TITLE
remove experimental guard for buildkit

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Allow buildkit builds to run without experimental mode enabled. Buildkit can now be twiddled with a specific flag https://github.com/moby/moby/pull/37593

**- How I did it**

**- How to verify it**

**- Description for the changelog**

+ Bring buildkit builds out of experimental.

**- A picture of a cute animal (not mandatory but encouraged)**

🐈

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

twiddle-dee-twiddle-dom

**Review by AntaresS — APPROVED** [review]
LGTM

**Review by tiborvass — CHANGES_REQUESTED** [review]
`experimentalProvider` could be removed in a followup. 

But since buildkit relies on `/session` endpoint, that would also need to graduate out of experimental (remove router.Experimental in api/router/session)

**Comment by AntaresS** [comment]
@tiborvass I think Andrew has updated the PR. Can we get this one in first to avoid conflicts?

**Review by tiborvass — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Looks like I forgot to follow-up on this one to update the docs; so, with some delay: https://github.com/moby/moby/pull/40028

**Pull request merged**
