### PR TITLE
Added entry for Sir M.Visvesvaraya

### PR DESCRIPTION
**Pull request by sagarhani**
Signed-off-by: Sagar Hani sagarhani33@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by rghv** [comment]
@sagarhani you might want to add this to https://github.com/cpuguy83/docker-who as well

**Comment by sagarhani** [comment]
@rghv  I checked it. :+1:

**Comment by cpuguy83** [comment]
I added, thanks.

**Comment by sagarhani** [comment]
Cool. :sunglasses:

**Pull request merged**
