### PR TITLE
Replace "kickass" in name generator with "vigorous"

### LINKED ISSUE #30374: remove "kickass" from name generator adjectives
As fun as "kickass" is, it's uncomfortable to be presented with it - or other curse words - in some settings, such as at work. (Admittedly depending on the work environment.) I don't want to have to put something like "kickass_thompson" into documentation. (I could use the container ID, but still.)

### PR DESCRIPTION
**Pull request by Thynix**
Having curse words in container names can get awkward.

Closes #30374.

Signed-off-by: Steve Dougherty <steve@asksteved.com>

**- Description for the changelog**

Replace "kickass" in name generator with "vigorous"

**- A picture of a cute animal (not mandatory but encouraged)**

The Good King Snugglewumps

### CODE REVIEW

**Comment by justincormack** [comment]
I think it might be good to add a replacement.

**Comment by Thynix** [comment]
How about "knowledgeable?"

**Comment by LK4D4** [comment]
google translate suggests `vigorous` which is also quite funny.

**Comment by Thynix** [comment]
That works. I'll change this to replace it.

**Comment by Thynix** [comment]
Done.

**Review by justincormack — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
