### PR TITLE
Revert aufs fine locks

### LINKED ISSUE #20738: Fine-grained aufs graphdriver locks cause aufs failures
Not sure why yet, but worth reporting that since commit 2f797bb1d9826f1aba242965b611b71b81fd152e the aufs graphdriver fails in most cases to properly mount all layers.  This usually manifests itself with a "can't find binary" from the `stat` calls trying to find the CMD/ENTRYPOINT and finding empty layers:
```
docker run busybox ls
exec: "ls": executable file not found in $PATH
docker: Error response from daemon: Container command not found or does not exist..
```

I tested master on Ubuntu 14.04.4 and Ubuntu 15.10 and both fail in the same way.  Switching graph drivers gets rid of the failures.  Building a binary one commit prior to 2f797bb1d9826f1aba242965b611b71b81fd152e works fine with the aufs graphdriver.

ping @cpuguy83 re #20275 as this probably needs further research as I assume you didn't see this in your setup.

The CI doesn't exhibit any failures I believe because vfs is the graphdriver in use, and the CI host systems are probably not on latest master; and this was just merged today 2/26/2016.  @crosbymichael this was the failure I was getting earlier.

### PR DESCRIPTION
**Pull request by cpuguy83**
Reverts f31014197cbe9438cc956ed12c47093a0324c82d from #20275

Why? Layers are not being mounted properly.
Why didn't we see this before merge? CI is using vfs... I use vfs when running integration tests as well due to issues with many tests in dind running aufs-over-aufs.

Fixes #20738

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM :sweat:

**Comment by thaJeztah** [comment]
:cry:

>  due to issues with many tests in dind running aufs-over-aufs.

Possibly I don't understand, but if `/var/lib/docker` is marked a volume in the dind container, we wouldn't be running aufs-on-aufs?

**Comment by thaJeztah** [comment]
but LGTM

**Comment by cpuguy83** [comment]
Yes, but the daemon suite spins up data dirs elsewhere.

**Comment by thaJeztah** [comment]
What if we made `/tmp` a volume, and have those all create a tmpdir and use that? IIRC, using vfs had a massive impact on the duration of the tests, so sounds like a win to me

**Comment by cpuguy83** [comment]
Updated to not revert the extra log info in from the unmount command.

**Comment by icecrime** [comment]
LGTM

**Comment by icecrime** [comment]
The `experimental` is currently failing on #20543.

**Pull request merged**
