### PR TITLE
hack/make: remove autogen resources for Docker CLI

### PR DESCRIPTION
**Pull request by thaJeztah**
the files used by the docker cli were moved to the docker/cli repository, so are no longer needed here

relates to https://github.com/moby/moby/issues/36652

### CODE REVIEW

**Comment by thaJeztah** [comment]
@vikramhh @StefanScherer @vdemeester @kolyshkin PTAL

**Comment by thaJeztah** [comment]
let me rename the icon files as well; hold on

**Comment by thaJeztah** [comment]
done 👍

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Asking on our internal slack if someone knows if the icon is _required_ or _optional_; the icons here are quite outdated, and I don't expect many users to have `dockerd.exe` in a "visible" location. If so, I can remove the icons altogether (perhaps in a follow-up)

**Review by vdemeester — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
OK, so the `ICON` is optional; I'll open a follow-up PR (in case there's still discussion) based on this one

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/39903 to remove the icon

**Comment by thaJeztah** [comment]
Ah, looks like there's still a reference to a file somewhere; fixing

```
[2019-09-11T09:03:46.522Z] x86_64-w64-mingw32-gcc: error: hack/make/.resources-windows/docker.rc: No such file or directory
```

**Comment by thaJeztah** [comment]
Should be fixed now

**Comment by thaJeztah** [comment]
Failure on RS1 is https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39901/runs/4/nodes/50/log/?start=0

which is tracked through https://github.com/moby/moby/issues/39909, and I opened a PR to skip it on Windows RS1 in https://github.com/moby/moby/pull/39910

```
[2019-09-11T14:49:57.316Z]     --- FAIL: Test/DockerSuite/TestAPIImagesSaveAndLoad (553.89s)
[2019-09-11T14:49:57.316Z]         cli.go:45: assertion failed: 
[2019-09-11T14:49:57.316Z]             Command:  d:\CI-4\CI-a9aeda834\binary\docker.exe inspect --format {{.Id}} sha256:566b7e32ff8581a6e8dd106c48304f4c59167a6bb6092eedb0c7f01a7631b2c8
[2019-09-11T14:49:57.316Z]             ExitCode: 1
[2019-09-11T14:49:57.316Z]             Error:    exit status 1
[2019-09-11T14:49:57.316Z]             Stdout:   
[2019-09-11T14:49:57.316Z]             
[2019-09-11T14:49:57.316Z]             Stderr:   Error: No such object: sha256:566b7e32ff8581a6e8dd106c48304f4c59167a6bb6092eedb0c7f01a7631b2c8
[2019-09-11T14:49:57.316Z]             
[2019-09-11T14:49:57.316Z]             
[2019-09-11T14:49:57.316Z]             Failures:
[2019-09-11T14:49:57.316Z]             ExitCode was 1 expected 0
[2019-09-11T14:49:57.316Z]             Expected no error
```

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
