### PR TITLE
Remove word "fail" from tests

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

Ping @unclejack 

@tianon's gonna be happy? One catch though: I couldn't remove `logDone("restart - recording restart policy name for --restart=on-failure")`.

### CODE REVIEW

**Comment by tianon** [comment]
+++ Ctrl-F "fail" is amazing, and this will cut down on the false positives immensely :heart:

**Comment by SvenDowideit** [comment]
gosh, i wish there was a standard for annotating tests.......






[don't read this](http://en.wikipedia.org/wiki/Test_Anything_Protocol)

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
