### PR TITLE
AppArmor: add missing rules for running in userns

### PR DESCRIPTION
**Pull request by thaJeztah**
~built on top of https://github.com/moby/moby/pull/39991 (I'll rebase once that's merged)~ rebased

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @justincormack @AkihiroSuda @estesp PTAL

**Comment by thaJeztah** [comment]
rebased, because https://github.com/moby/moby/pull/39991 was merged

**Comment by thaJeztah** [comment]
Probably not, but I recalled there were issues with networking and userns, so wondered if there was a relation with https://github.com/moby/moby/issues/26106. Mentioning it, just in case there _is_ a relation 😅

**Comment by crosbymichael** [comment]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
