### PR TITLE
Avoid a HEAD request for each layer in a v2 pull

### PR DESCRIPTION
**Pull request by aaronlehmann**
We were calling Stat for each layer to get the size so we could indicate
progress, but https://github.com/docker/distribution/pull/1226 made it
possible to get the length from the GET request that Open initiates.

Saving one round-trip per layer should make pull operations slightly
faster and more robust.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Note that the diff is a bit deceptive. This is simply removing:

```go
	desc, err := blobs.Stat(context.Background(), di.digest)
 	if err != nil {
		logrus.Debugf("Error statting layer: %v", err)
 		di.err <- err
 		return
 	}
 	di.size = desc.Size
```

and adding, after the `Open`:

```go
	di.size, err = layerDownload.Seek(0, os.SEEK_END)
 	if err != nil {
 		di.err <- err
 		return
 	}
	_, err = layerDownload.Seek(0, os.SEEK_SET)
 	if err != nil {
 		di.err <- err
 		return
 	}
```

The diff captures the change in a more confusing way.

**Comment by thaJeztah** [comment]
Nice!

**Comment by cpuguy83** [comment]
LGTM

**Comment by aaronlehmann** [comment]
It just occurred to me that the first seek failing (presumably because there's no Content-Length header) shouldn't fail the whole download. It can still continue, but the progress output won't show a progress bar. I'm not sure if this will ever happen in practice, but it seems like a good idea to be robust to this situation.

Sorry for changing the commit after a LGTM.

**Comment by aaronlehmann** [comment]
As a side effect, this tweak made the diff a lot easier to read ;)

**Comment by tonistiigi** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
