### PR TITLE
Carry 11441: fix docker ps help message

### PR DESCRIPTION
**Pull request by tiborvass**
Closes #11441

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by tiborvass** [comment]
Thanks for your contribution @jimmyxian !

**Comment by moxiegirl** [comment]
@LK4D4 that is a possessive --- yay @jimmyxian thank you for being so precise! LGTM

**Comment by jimmyxian** [comment]
OK, it's my first contribution. Thanks all the people who help me to known the contribution guidelines.I will continue to focus on the docker community.

**Comment by LK4D4** [comment]
@jimmyxian Congrats!

**Pull request merged**
