### PR TITLE
Windows: So long TP4, so long...

### PR DESCRIPTION
**Pull request by lowenna**
tp4

Signed-off-by: John Howard jhoward@microsoft.com

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@tibor @icecrime

**Comment by thaJeztah** [comment]
:heart: and it's :green_heart: on WindowsTP5!

**Comment by thaJeztah** [comment]
Guess we need this in the 1.11 branch?

**Comment by jhowardmsft** [comment]
@thaJeztah No, no, no, no, no. This must NOT be cherry-picked for 1.11!

**Comment by icecrime** [comment]
Yeesssssssssss! :+1: What about the boilerplate code to retry on "object not found" errors and such?

**Comment by thaJeztah** [comment]
@jhowardmsft oh! sorry for the confusion; I thought the TP4 CI would be replaced with TP5, so this was needed to have it run on the bump branch

**Comment by jhowardmsft** [comment]
@icecrime some will still be needed until we have some servicing fixes for TP5. There's a lot more tidying to do yet, this predominantly is just the initial block to stop master on TP4.

**Comment by thaJeztah** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
