### PR TITLE
Windows CI: Fix test-unit for daemon

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Anyone who's looked closely at the windowsTP4 output will notice a bunch of errors for test-unit which are currently ignored. Starting to fix them up. This is for daemon.  Local unit testing on Windows below:

```
c:/go/bin/go.exe test -v -tags daemon [E:/go/src/github.com/docker/docker/daemon]
=== RUN   TestDaemonConfigurationMerge
--- PASS: TestDaemonConfigurationMerge (0.00s)
=== RUN   TestDaemonConfigurationNotFound
--- PASS: TestDaemonConfigurationNotFound (0.00s)
=== RUN   TestDaemonBrokenConfiguration
--- PASS: TestDaemonBrokenConfiguration (0.00s)
=== RUN   TestParseClusterAdvertiseSettings
--- PASS: TestParseClusterAdvertiseSettings (0.00s)
=== RUN   TestFindConfigurationConflicts
--- PASS: TestFindConfigurationConflicts (0.00s)
=== RUN   TestFindConfigurationConflictsWithNamedOptions
--- PASS: TestFindConfigurationConflictsWithNamedOptions (0.00s)
=== RUN   TestDaemonConfigurationMergeConflicts
--- PASS: TestDaemonConfigurationMergeConflicts (0.00s)
=== RUN   TestDaemonConfigurationMergeConflictsWithInnerStructs
--- PASS: TestDaemonConfigurationMergeConflictsWithInnerStructs (0.00s)
=== RUN   TestFindConfigurationConflictsWithUnknownKeys
--- PASS: TestFindConfigurationConflictsWithUnknownKeys (0.00s)
=== RUN   TestFindConfigurationConflictsWithMergedValues
--- PASS: TestFindConfigurationConflictsWithMergedValues (0.00s)
=== RUN   TestGetContainer
--- PASS: TestGetContainer (0.00s)
=== RUN   TestValidContainerNames
--- PASS: TestValidContainerNames (0.00s)
=== RUN   TestContainerInitDNS
--- PASS: TestContainerInitDNS (0.01s)
=== RUN   TestMerge
--- PASS: TestMerge (0.00s)
=== RUN   TestDaemonReloadLabels
--- PASS: TestDaemonReloadLabels (0.00s)
=== RUN   TestDaemonDiscoveryReload
--- PASS: TestDaemonDiscoveryReload (0.00s)
=== RUN   TestDaemonDiscoveryReloadFromEmptyDiscovery
--- PASS: TestDaemonDiscoveryReloadFromEmptyDiscovery (0.00s)
=== RUN   TestContainerDoubleDelete
--- PASS: TestContainerDoubleDelete (0.00s)
=== RUN   TestDiscoveryOpts
--- PASS: TestDiscoveryOpts (0.00s)
=== RUN   TestModifiedDiscoverySettings
--- PASS: TestModifiedDiscoverySettings (0.00s)
=== RUN   TestLogContainerEventCopyLabels
--- PASS: TestLogContainerEventCopyLabels (0.00s)
=== RUN   TestLogContainerEventWithAttributes
--- PASS: TestLogContainerEventWithAttributes (0.00s)
=== RUN   TestMigrateLegacySqliteLinks
--- PASS: TestMigrateLegacySqliteLinks (0.10s)
=== RUN   TestParseVolumesFrom
--- PASS: TestParseVolumesFrom (0.00s)
PASS
ok      github.com/docker/docker/daemon 0.218s
Success: process exited with code 0.
```

### CODE REVIEW

**Comment by cpuguy83** [comment]
```
02:33:26 # github.com/docker/docker/daemon
02:33:26 daemon/daemon_unix_test.go:11: container redeclared as imported package name
02:33:26 	previous declaration at daemon/daemon_unix_test.go:10
02:33:26 daemon/daemon_unix_test.go:91: undefined: "github.com/docker/engine-api/types/container".Container
02:33:26 daemon/daemon_unix_test.go:92: undefined: containertypes in containertypes.HostConfig
```

**Comment by jhowardmsft** [comment]
@cpuguy83 Ugh. Yeah, figured I'd break something on Linux. Will fix...

**Comment by jhowardmsft** [comment]
@cpuguy83 Fixed that bit - waiting for Jenkins runs to finish.

**Comment by thaJeztah** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐙

**Pull request merged**
