### PR TITLE
Provide an option to specify per container root mount propagation flag

### PR DESCRIPTION
**Pull request by rhvgoyal**
Recently runc patches got merged where one can specify per container / (root) propagation flags. Backport these patches in docker and add an option --root-propagation to allow per container root
propagation flags. Valid values are [r]private, [r]shared, [r]slave. These are useful when one wants certain volumes to be slave/shared inside containers.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
CC @LK4D4 @mrunalp @rhatdan @rootfs @vbatts

**Comment by rhatdan** [comment]
iff is a shorthand way of writing `if and only if`

https://en.wikipedia.org/wiki/If_and_only_if

**Comment by phemmer** [comment]
This looks like a dup of #15648

**Comment by rhvgoyal** [comment]
@phemer It is. Difference is different implementation. This implementation is based on what has been merged in runc.

**Comment by phemmer** [comment]
@rhvgoyal sorry, deleted comment as I saw you even commented over there. Didn't notice as I unsubscribed from it a while ago due to "+1" spam.

**Comment by mrunalp** [comment]
We will need to bump up the version of runc in docker.

**Comment by rhvgoyal** [comment]
@mrunalp What's the process for bumping runc version. For now I have just taken the relevant pieces from runc and put in first patch.

**Comment by mrunalp** [comment]
@rhvgoyal Change commit id in hack/vendor.sh and run it. Adjust docker code to account for the changes and then make a PR. See for e.g. https://github.com/docker/docker/commit/b7a009cc1c9747cab4ebf40e609068c86f34d19d

**Comment by rhvgoyal** [comment]
@mrunalp ok, thanks. I will look into it. Possibly create a separate PR to pull in newer runc and rebase this PR on top of that.

**Comment by cpuguy83** [comment]
Definitely makes this a bit easier!
I do not like this flag name as I will _always_ misspell it.

**Comment by cpuguy83** [comment]
Also, force pushing to the old PR would have been better... I think this is the 3rd implementation? It's really fragmented the conversation.

**Comment by peter-edge** [comment]
@rhvgoyal I may be missing something, but by making `RootPropogation` an int on the `HostConfig` struct, this seems to make an issue for the Docker API, specifically https://github.com/docker/docker/blob/master/pkg/mount/flags_unsupported.go. I was going to go add `RootPropogation` to https://github.com/fsouza/go-dockerclient/blob/master/container.go#L456, but then realized this. Should it be back to a string, and then parse further down?

**Comment by peter-edge** [comment]
Further explanation: assuming `RootPropogation` is an int on go-dockerclient's `HostConfig,`, I would have done:

```go
import (
  "github.com/docker/docker/pkg/mount"
)
...
hostConfig.RootPropogation = mount.RSHARED
...
```

Which from a non-linux/freebsd box, will translate to 0...or more to the point, mount flags are platform-specific which is why they're hidden behind `_linux.go, _freebsd.go` build directives as it is.

**Comment by runcom** [comment]
@rhvgoyal @mrunalp I'm taking care of bumping libcontainer version here https://github.com/docker/docker/pull/16795

**Comment by rhvgoyal** [comment]
@runcom Thanks for taking care of moving to newer libcontainer version.

**Comment by rhvgoyal** [comment]
@cpuguy83 Agreed that name is not simple. (--root-propagation). Do you have other ideas on names? In last proposal @rootfs named it `--root-mount`. Do you like that one better?

**Comment by rhvgoyal** [comment]
@cpuguy83 Last PR was created by @rootfs and I don't have rights to push to that. That's primary reason I created a separate PR. Also I wanted to keep other implementation around so that we could compare the two, if need be.

But if you are particular about it, I can talk to @rootfs, give him my patch and ask him to force push. Do let me know.

**Comment by rhatdan** [comment]
```
--propogation
--volume-propogation
--vol-propogation
--mount-propogation
--mnt-propogation
```

**Comment by rhvgoyal** [comment]
@rhatdan, I suspect @cpuguy83 finds `propagation` hard to spell (like `--privileged`). so may be we need to get rid of `propagation` instead from proposed solution`

**Comment by rhvgoyal** [comment]
@peter-edge You make a very good point. So if client is running on non-linux system and daemon is running on a linux system then there is no easy way to ask daemon to run container with a particular propagation mode.  I think I should change RootPropagation field in HostConfig to string and parse it on daemon and convert into integer. Will rework my patches. Thanks.

**Comment by rhvgoyal** [comment]
@peter-edge  Changed patches to keep RootPropagation in Hostconfig as string so that a non-linux based client can specify propagation mode for a linux based daemon.

**Comment by rhvgoyal** [comment]
Now that runc version has been bumped in separate PR, dropped those patches from this PR.

**Comment by mrunalp** [comment]
@LK4D4 ping :)

**Comment by rhvgoyal** [comment]
How to Test:

1. To have slave volumes inside containers do following.

   docker run -ti -v /root/mnt-source:/root/mnt-dest --root-propagation=rslave fedora bash
 
  Note: This assumes that / on host is either "shared" or "slave". If it is
  not, convert it using "mount --make-slave /"

2. To have shared volumes inside container, do following.

   docker run -ti -v /root/mnt-source:/root/mnt-dest --root-propagation=shared --cap-add=SYS_ADMIN fedora bash

   Note: This assumes that "/" on host is shared. I have added SYS_ADMIN to
   container so that it can be allowed to do mounts inside container.

**Comment by rhvgoyal** [comment]
Rebased to latest upstream.

**Comment by cpuguy83** [comment]
I'd be ok with `--mnt` here, although the semantics are certainly different than other more namespacey flags.

**Comment by cpuguy83** [comment]
Maybe even `--mounts`

**Comment by rhvgoyal** [comment]
@cpuguy83 Ok, I will change it to `--mounts`. Not exact fit but should do.

**Comment by rhvgoyal** [comment]
@cpuguy83 Changed `--root-propagation` to `--mounts`. PTAL.

**Comment by rhvgoyal** [comment]
Rebased again to resolve conflicts.

**Comment by rhvgoyal** [comment]
Ping @cpuguy83 @LK4D4 

How can I make progress on this PR.

**Comment by crosbymichael** [comment]
Last time we talked I though these would be confined to individual volumes and not the entire container's rootfs?

**Comment by rhvgoyal** [comment]
@crosbymichael 

This primarily applies to / and not container rootfs. Propagation properties of  / further determines the propagation properties of further mounts (including rootfs).

If rootfs is a concern, that should not be a problem. Docker just have to mount rootfs as private and when runc does a bind mount that will be private too (as root is private to begin with).

W.r.t whether it should be a per volume property or a global per container switch, I think we need both. A global switch like --mounts is helpful when we don't want different properties for different bind mounts. But if we want some of the volumes to be private and others to be slave and rest shared, then
per volume property will help.

Our current use cases seem to be satisfied with global switch and it is easy to implement that, hence I implemented it. But implementing a per volume switch is entirely reasonable too and can be implemented as soon as somebody needs it.

**Comment by tiborvass** [comment]
Sorry we had to move this to 1.10

**Comment by peter-edge** [comment]
Is this going to be merged soon? There are a lot of people waiting on this,
it seems like the author has done all he can

**Comment by apatil** [comment]
The single flag per container covers our use case as well.

**Comment by SamYaple** [comment]
I am also looking forward to this change merging

**Comment by rhvgoyal** [comment]
@crosbymichael 

Ok, I generated another PR #17034 which allows specifying per volume mount propagation flags. PTAL.

**Comment by crosbymichael** [comment]
@rhvgoyal i was just asking a question, no need to open another PR ;)

**Comment by rhvgoyal** [comment]
@crosbymichael I am just trying to make it as simple as possible. So I thought having two implementations will help in make a fair comparison. :-)

**Comment by peter-edge** [comment]
I will personally buy a case of beer for whoever gets this the LGTM
and merge, today - I'll walk over to docker HQ and deliver it, your choice
:)

**Comment by crosbymichael** [comment]
@peter-edge my opensouce oath prevents me from accepting bribes ;) i'm reviewing this today anyways

**Comment by peter-edge** [comment]
<3

**Comment by calavera** [comment]
`--mounts` is a very misleading name for this flag. Even if it's harder to type, I think the original `--rootfs-propagation` was better.

Is there a way to add integration tests for this?
We're also going to need changes in the documentation for the api and the completion scripts before we merge it in.

**Comment by rhvgoyal** [comment]
@calavera I personally like --root-propagation better. So first thing is we need to have a consensus on the name and I can change it again, not a problem at all.

I think adding integration tests should be doable. I had added couple of tests to runc. I will look into adding some tests here too.

What are "completion" scripts? 

Also please have a look at other PR which introduces per volume propagation flag. I think that one is little more restrictive but is easier to understand.

**Comment by rhatdan** [comment]
@rhvgoyal ./contrib/completion/...

**Comment by crosbymichael** [comment]
@rhvgoyal lets go with `--root-mount-propagation`  

sorry for it changing on you.

**Comment by rhvgoyal** [comment]
@crosbymichael ok, will change it to --root-mount-propagation.

**Comment by rhatdan** [comment]
Yeesh @crosbymichael is a better typist then I am.

**Comment by rhvgoyal** [comment]
- Changed option name to --root-mount-propagation from --mounts
- Fixed completion scripts
- Fixed API and commandline documentation.

Will look into writing integration tests now.

**Comment by rhatdan** [comment]
I actually like the other patch better, but I am willing to take either.

**Comment by calavera** [comment]
@rhvgoyal please, stop adding `docker:` as a prefix to your commit messages.

**Comment by rhvgoyal** [comment]
@rhatdan Now I am also little more inclined towards per volume propagation switch. That seems little easier to understand and will be little easy to explain to users.

**Comment by rhvgoyal** [comment]
@calavera ok, will drop the `docker` prefix.

**Comment by crosbymichael** [comment]
@rhvgoyal @rhatdan I thought when we originally talked about this change we all agreed on this being a per volume setting.  That is why it was weird seeing this PR.  Can we close this one and go with the per volume setting?

**Comment by rhatdan** [comment]
@crosbymichael Fine with me.

**Comment by rhvgoyal** [comment]
Ok, I will close this PR and let us track this in other PR #17034  where per volume propagation properties are specified.

**Pull request closed without merging**
