### PR TITLE
Switch to using opencontainers/selinux for selinux bindings

### PR DESCRIPTION
**Pull request by rhatdan**
We have moved selinux bindings out of opencontainers/runc into its
own repository opencontainers/selinux.  This patch converts to the
new bindings.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! Looks like this needs a change to the vendored files https://github.com/docker/docker/blob/master/vendor.conf

Some instructions are here; https://github.com/docker/docker/blob/master/hack/vendor.sh, but let me know if you need help 👍

**Comment by thaJeztah** [comment]
also /cc @cpuguy83

**Comment by cpuguy83** [comment]
LGTM once vendored

**Comment by cpuguy83** [comment]
Thanks @rhatdan!

**Comment by vdemeester** [comment]
@rhatdan weird failures happening 

```
20:38:17 ----------------------------------------------------------------------
20:38:17 FAIL: docker_cli_run_test.go:2422: DockerSuite.TestRunMountShmMqueueFromHost
20:38:17 
20:38:17 docker_cli_run_test.go:2435:
20:38:17     out, _ := dockerCmd(c, "run", "--name", "ipchost", "--ipc", "host", "busybox", "cat", "/dev/shm/test")
20:38:17 docker_utils_test.go:106:
20:38:17     c.Assert(result, icmd.Matches, icmd.Success)
20:38:17 ... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc4201b62c0), ExitCode:125, Error:(*exec.ExitError)(0xc4237124e0), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc420095200), errBuffer:(*cmd.lockedBuffer)(0xc420095290)} ("\nCommand:  /go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker run --name ipchost --ipc host busybox cat /dev/shm/test\nExitCode: 125\nError:    exit status 125\nStdout:   \nStderr:   /go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker: Error response from daemon: invalid --security-opt 1: \"disable\".\nSee '/go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker run --help'.\n\n")
20:38:17 ... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
20:38:17 ... 
20:38:17 Command:  /go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker run --name ipchost --ipc host busybox cat /dev/shm/test
20:38:17 ExitCode: 125
20:38:17 Error:    exit status 125
20:38:17 Stdout:   
20:38:17 Stderr:   /go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker: Error response from daemon: invalid --security-opt 1: "disable".
20:38:17 See '/go/src/github.com/docker/docker/bundles/17.05.0-dev/binary-client/docker run --help'.
20:38:17 
20:38:17 
20:38:17 Failures:
20:38:17 ExitCode was 125 expected 0
20:38:17 Expected no error
20:38:17 
20:38:17 
20:38:18 
20:38:18 ----------------------------------------------------------------------
```

**Comment by vdemeester** [comment]
ping @rhatdan @runcom 👼

**Comment by runcom** [comment]
I can carry this PR if @rhatdan is ok

**Comment by rhatdan** [comment]
@runcom Sure carry it.

**Comment by runcom** [comment]
Closing in favor of https://github.com/docker/docker/pull/32687 where tests should pass

**Pull request closed without merging**
