### PR TITLE
Fix panic in hijack

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <tibor@docker.com>

Related to docker/cli#380 (needs vendoring in cli)

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by dnephin — COMMENTED** [review]
It's strange the docs (https://golang.org/pkg/net/http/httputil/#pkg-variables) suggest `ErrPersistEOF` is deprecated and not used, even though other docs on that same page still reference it.

**Comment by thaJeztah** [comment]
Should we open an issue for that?

**Comment by aaronlehmann** [comment]
If the panic is in the CLI, don't we need a fix there?

**Comment by thaJeztah** [comment]
yes;

> Related to docker/cli#380 (needs vendoring in cli)

**Pull request merged**
