### PR TITLE
More integration-cli/integration refactoring + request package

### PR DESCRIPTION
**Pull request by vdemeester**
- Merge few helper function from `integration-cli/daemon.Daemon` to `internal/test/daemon.Daemon`.
- Move most of the fuctions from `integration-cli/request` to `internal/test/request`

:lion:

### CODE REVIEW

**Comment by cpuguy83** [comment]
```
17:18:36 internal/test/request/ops.go:12:6:warning: exported type Options should have comment or be unexported (golint)
17:18:36 internal/test/request/request.go:105:2:warning: var hostUrl should be hostURL (golint)
17:18:36 internal/test/request/request.go:134:2:warning: var hostUrl should be hostURL (golint)
17:18:36 internal/test/daemon/container.go:26:34:warning: t can be github.com/docker/docker/vendor/github.com/gotestyourself/gotestyourself/assert.TestingT (interfacer)
17:18:36 internal/test/daemon/container.go:11:35:warning: t can be github.com/docker/docker/vendor/github.com/gotestyourself/gotestyourself/assert.TestingT (interfacer)
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by anusha-ragunathan** [comment]
Needs rebase

**Comment by thaJeztah** [comment]
@anusha-ragunathan this was rebase; PTAL

**Comment by vdemeester** [comment]
cc @cpuguy83

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
