### PR TITLE
add TestDaemonwithwrongkey test case

### PR DESCRIPTION
**Pull request by sunyuan3**
add TestDaemonwithwrongkey test case
Make sure that daemon can't start with a wrong key.json file.

### CODE REVIEW

**Comment by sunyuan3** [comment]
Hi Gordon,
  Thanks for your reminding. The following has been added.
Signed-off-by: Yuan Sun <sunyuan3@huawei.com>

**Comment by estesp** [comment]
you need to `gofmt` your code; it failed the **gofmt** check in CI.

**Comment by sunyuan3** [comment]
Hi estesp,
Thanks for your reminding. I create a new pull request. Please help me to review it.
https://github.com/docker/docker/pull/11324

**Comment by cpuguy83** [comment]
Closing this one since it seems to be that #11324 was also created.

In the future you can just force push to your branch and it will update the existing PR.

**Pull request closed without merging**
