### PR TITLE
IPAM driver name should not be required in network create

### LINKED ISSUE #25735: IPAM Driver name shouldn't be required in network create
I'm opening an issue here as well as on engine-api: https://github.com/docker/engine-api/issues/368

There seems to be a disagreement between engine-api and docker about whether the IPAM driver name is required in the network create api. engine-api doesn't set it by default and docker requires it by default. This breaks existing applications that use engine-api to create overlay networks.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 153
 Running: 13
 Paused: 0
 Stopped: 140
Images: 743
Server Version: 1.12.0
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: active
 NodeID: 0jnlg1wjfbomj3vpagxqcjied
 Is Manager: true
 ClusterID: 7npas0qe6x670sbnzawyulo5y
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 172.17.0.1
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: compooter
ID: GKSI:YHZC:YPNI:PAGO:EYPD:AYME:K6BY:BAIH:EBKQ:SOAK:WUFP:6MJM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 1966
 Goroutines: 1943
 System Time: 2016-08-15T15:22:58.960604046-07:00
 EventsListeners: 2
Username: viktorstanchev
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 172.17.0.1
 192.168.0.106
 dtr2-2061409770.us-west-2.elb.amazonaws.com
 new-1428125395.us-west-2.elb.amazonaws.com
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. See https://github.com/docker/engine-api/issues/368
2.
3.

**Describe the results you received:**
error

**Describe the results you expected:**
no error

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by yongtang**
**\- What I did**

This fix tries to address the issue raise in #25735 and https://github.com/docker/engine-api/issues/368
where currently IPAM driver name is required in NetworkCreate ('/networks/create').

**\- How I did it**

This fix (together with engine-api update) changes the type of IPAM in NetworkCreate
to be a pointer so that by default IPAM driver name is not needed.

**\- How to verify it**

This fix has been tested manually, as is specified in https://github.com/docker/engine-api/issues/368.

**\- Description for the changelog**

This fix fixes #25735.

This fix is related to #25735 and https://github.com/docker/engine-api/issues/368.

A pull request in engine-api has been created separately:
https://github.com/docker/engine-api/pull/372

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by stevvooe** [comment]
PTAL @mrjana 

First pass on the code looks good. Will take a second pass after @mrjana approves.

**Comment by cpuguy83** [comment]
ping @mrjana

**Comment by mrjana** [comment]
@yongtang Can you please rebase?

**Comment by mrjana** [comment]
@yongtang engine-api moved into `docker/api` . You may have to fix adjust this PR accordingly.

**Comment by yongtang** [comment]
Thanks @mrjana. I tried to rebase and found out that this PR has been completely covered in #26200 and there is no further change needed. So I will just close this PR for now. Again, thanks for the help!

**Pull request closed without merging**
