### PR TITLE
Swap "ubuntu-debootstrap" for just "ubuntu"

### PR DESCRIPTION
**Pull request by tianon**
See https://github.com/docker-library/official-images/pull/982#issuecomment-133207587.

@jfrazelle this is what I meant in https://github.com/docker/docker/pull/15979#issuecomment-136813735 :wink:

### CODE REVIEW

**Comment by jfrazelle** [comment]
ooooooo my b

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
Any way we could run the deb builder on this PR?

**Comment by jfrazelle** [comment]
https://jenkins.dockerproject.org/job/Docker%20Master%20(build%20deb..rpms)/158/consoleFull

**Comment by jfrazelle** [comment]
failed

**Comment by tianon** [comment]
Prefect, on my way back to the office now; will update the base image and
we can try again! :+1:

**Comment by tianon** [comment]
@jfrazelle updated images are pushed -- if the build is restarted, it will pull fresh copies of the base images too, right?

**Comment by jfrazelle** [comment]
totallyyy

**Comment by tianon** [comment]
ohman
I screwed up the PR.  One sec.

**Comment by tianon** [comment]
(that's what I get for making it in a rush from the car)

**Comment by tianon** [comment]
Updated...  :sheep: :disappointed:

**Comment by tianon** [comment]
Looks like it was green this time, even though janky is being janky. :smile:

https://jenkins.dockerproject.org/job/Docker%20Master%20(build%20deb..rpms)/163/

**Comment by thaJeztah** [comment]
Must've been @tianon creating the PR from his car; traffic lights🚦 going from green to red half-way 👻

**Comment by jfrazelle** [comment]
\o/

**Comment by jfrazelle** [comment]
btw @calavera this should be cherry-picked into your bump branch :) you da best

**Comment by calavera** [comment]
cherry picked into #15809

**Pull request merged**
