### PR TITLE
revendor logrus and x/crypto

### PR DESCRIPTION
**Pull request by clnperez**
More toward my goal of getting the ~~container~~ world moved over to the new and maintained x/sys library instead of the old, unmaintained syscall lib (built into the language).

logrus has now also been moved! 🎉 

This PR revendors logrus to 1.0.3. It also takes out the `NotPpc64le` test requirement for the console colors tests, since a bad syscall value was the reason they were failing. ❣️ 🍾 

**===**

**- Description for the changelog**

this fixes the issue that was blocking a test from running on ppc64le.
the logrus revendor changes the color code used in that same test, so
that breaks the test for all platforms (updated in this pr)

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by clnperez** [comment]
I don't think this crypto issue will be resolved in enough time to conflict with pull/34272, so I'm not worried about conflicts there.

**Comment by AkihiroSuda** [comment]
We vendored latest sirupsen/logrus.
I guess this is closable?

**Comment by thaJeztah** [comment]
Perhaps the `NotPpc64le` could still be good to have?

**Comment by clnperez** [comment]
Yes, I wanted to revendor and change the tests to enable ppc64le -- but then the logrus revendor pulled in things that broke ppc64le again (the same issue that broke logrus has now resurfaced in the go crypo code). 

So, there are three parts to this PR (logrus + crpyto + tests). The crypo fixes would not stay, obviously. I will try and get that fixed upstream. Can we keep this open until then? The end PR will only be the test changes.

**Comment by thaJeztah** [comment]
Sure, no problem with leaving it open for now 👍

**Comment by clnperez** [comment]
@thaJeztah do you know what is going on with this vendor job? It's not just the job. My local `make validate` fails too.  I've tried everything I can think of to get a correct vendor dir. Seen this before?

**Comment by thaJeztah** [comment]
interesting; is it possible you're using a different version of `vndr` than is used in CI?

**Comment by clnperez** [comment]
That was all it was. Thank you @thaJeztah! 😻😻
This should be ready now thanks to some speedy go devs.
PTAL

**Comment by thaJeztah** [comment]
Nice, thanks!!

**Comment by clnperez** [comment]
hey can we merge this one? :D 

i updated the logrus commit to a release branch since by now 1.0.3 has my change. that didn't end up changing anything in the vendor dir after running `make vendor` so, should still be g2g. 

ping @dnephin @vdemeester

**Review by dnephin — APPROVED** [review]
LGTM when green

**Review by vdemeester — APPROVED** [review]
LGTM on green 🐮

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
