### PR TITLE
Windows: support Windows servicing layers

### PR DESCRIPTION
**Pull request by jstarks**
**\- What I did**
Added support for diff layers distributed by Microsoft to provide security and functionality updates. These layers require some capabilities that are not currently available in Docker.

**\- How I did it**
1. I added support for taking the utility VM (used for running as a Hyper-V isolated container) from the non-base layer. It is now taken from the highest layer that contains a utility VM image.
2. I revendored hcsshim with changes to support utility VM diffs in diff layers, and with support for hard links in the diff layer tars (this is necessary because Windows servicing uses hard links heavily, and without this the diff layers would be very large).

**\- How to verify it**
Verifying this requires a diff layer with utility VM changes and hard links. Microsoft has not released such a layer yet. We have verified this with internally-built layers.

**\- Description for the changelog**

Support for Windows servicing layers

**\- A picture of a cute animal (not mandatory but encouraged)**
image

cc @jhowardmsft

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@friism @dmp42 @mavenugo FYI

**Comment by jhowardmsft** [comment]
LGTM. And I fully approve of the cute animal picture 🐶

**Comment by jstarks** [comment]
I think the CI break is due to machine issues... But please hold merging for a fix to hcsshim...

**Comment by jstarks** [comment]
@jhowardmsft Do either of these failures look familiar?

**Comment by jhowardmsft** [comment]
Yes the restart failure I believe is due to a data race. I have a PR in to fix that. Can't restart Jenkins though from my phone.

**Comment by jhowardmsft** [comment]
@friism @mavenugo @dmp42 @icecrime FYI.

**Comment by jhowardmsft** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
