### PR TITLE
1.13.0 rc6 cherrypicks

### PR DESCRIPTION
**Pull request by vieux**
docs:
* Fix wrong command in changelog #29949
* Fix completion for zsh #29907
* Add bash completion for plugin names #29888

P0:
* Set plugins used in tests back to original names #29923
* Fix workdir cache invalidation #29956
* remove -f on secret create and unify usage with other commands #29955

misc, no code change but will help for the future
* un-fork go-memdb #29996
* Unfork logrus dependency #29924

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM :ok_hand:

**Comment by thaJeztah** [comment]
can we include https://github.com/docker/docker/pull/29924 ?

**Comment by thaJeztah** [comment]
also https://github.com/docker/docker/pull/29996 would be good to include (same as the previous I mentioned; no actual code changes)

**Comment by runcom** [comment]
Can we also include https://github.com/docker/docker/pull/29995 as it's unlikely to cause any regression?

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by justincormack** [comment]
LGTM

**Pull request merged**
