### PR TITLE
replace pkg/fileutils Matching funcs with github.com/moby/patternmatcher

### PR DESCRIPTION
**Pull request by thaJeztah**
- supersedes https://github.com/moby/moby/pull/42491
- closes https://github.com/moby/moby/pull/42491
- relates to https://github.com/tonistiigi/fsutil/pull/105
- relates to https://github.com/tonistiigi/fsutil/pull/136
- relates to https://github.com/moby/buildkit/pull/2150#issuecomment-857253756

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tonistiigi @aaronlehmann @cpuguy83 PTAL (I haven't tagged a release yet, but can do if we're all happy with the current state)

**Review by cpuguy83 — APPROVED** [review]
Naming is hard, but LGTM

I feel like someone must be watching me because I just had to import buildkit to test some things out and ran into the go.mod replacement for docker/docker.

**Comment by thaJeztah** [comment]
Yes, it was a pretty hairy one, and this one kept dropping off my list, thought I'd spend a bit of time to finally have it done.

Also not super happy with the name, but couldn't come up with a better one 😂 (and didn't want to waste time bike-shedding)

**Review by aaronlehmann — APPROVED** [review]

**Comment by thaJeztah** [comment]
This needs a rebase now; as https://github.com/moby/moby/pull/44221 was merged, but I'll wait for CI to be happy here (and in https://github.com/tonistiigi/fsutil/pull/136, then tag a `v0.5.0` (there's some functions marked "deprecated", and maybe we want to / can remove those before v1.0.0), then update my PRs

**Comment by thaJeztah** [comment]
Tagged it as `v0.5.0` and rebase; should be all good now 👍

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
