### PR TITLE
[1.13.x] Fix buildIpamResources()

### PR DESCRIPTION
**Pull request by aboch**
This ports #29416 to 1.13.x

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@aboch will you be opening a separate PR on master, or should I mark this for cherry-picking into master?

**Comment by aboch** [comment]
Thanks @thaJeztah let's mark it for cherry-pick to master

**Comment by mavenugo** [comment]
LGTM

**Comment by mavenugo** [comment]
@vieux are the plugin test failures expected ?

**Comment by vieux** [comment]
@mavenugo yes, they are fixed in https://github.com/docker/docker/pull/29229

**Pull request merged**
