### PR TITLE
vendor: github.com/containerd/containerd v1.7.19, migrate to github.com/containerd/platforms module

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on / stacked on https://github.com/moby/moby/pull/47141
- [x] depends on / stacked on https://github.com/moby/moby/pull/47143
- [x] depends on / stacked on https://github.com/moby/moby/pull/47147
- [x] relates to / depends on https://github.com/containerd/containerd/pull/9662
- [x] depends on above being backported https://github.com/containerd/containerd/pull/10292
- [x] depends on https://github.com/moby/moby/pull/47863
- [x] depends on (ideally) module requirements to be lowered: https://github.com/containerd/platforms/pull/5
- [x] depends on https://github.com/moby/moby/pull/47909
- [x] depends on https://github.com/containerd/containerd/pull/10386
- [x] depends on / stacked on https://github.com/moby/moby/pull/47946
- [x] depends on / stacked on https://github.com/moby/moby/pull/48091
- [x] depends on https://github.com/containerd/containerd/pull/10391 🎉 

### Migrate to github.com/containerd/platforms module

Containerd's "platforms" package is being moved to a separate module. This
allows updating the platforms parsing independent of the containerd module
itself.

For existing containerd versions (1.6, 1.7), the package in containerd will
be an alias for the new module.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ah, looks like some updates are needed;

```
# github.com/docker/docker/libcontainerd/local
libcontainerd/local/local_windows.go:944:34: cannot use p[i].CreateTimestamp (variable of type time.Time) as *timestamppb.Timestamp value in struct literal
```

**Comment by thaJeztah** [comment]
- opened https://github.com/containerd/platforms/pull/5 to prevent having to upgrade hcsshim

**Comment by thaJeztah** [comment]
Two tests failing that look related, looks like there's some change in behavior in the package;


```
=== FAIL: github.com/docker/docker/integration/build TestBuildPlatformInvalid (0.06s)
    build_test.go:685: assertion failed: expression is false: errdefs.IsInvalidParameter(err)
```

https://github.com/moby/moby/blob/27e85c7b6885c2d21ae90791136d9aba78b83d01/integration/build/build_test.go#L680-L685


```
=== FAIL: amd64.integration.image TestImagePullPlatformInvalid (0.01s)
    pull_test.go:37: assertion failed: expression is false: errdefs.IsInvalidParameter(err)
```

https://github.com/moby/moby/blob/27e85c7b6885c2d21ae90791136d9aba78b83d01/integration/image/pull_test.go#L34-L37

**Comment by thaJeztah** [comment]
Improved the test-assert a bit, and it looks like it's returning a 500 /  internal server error;

```
=== RUN   TestImagePullPlatformInvalid
    pull_test.go:37: assertion failed: invalid type for expected: func(error) error: errdefs.errSystem: Error response from daemon: "foobar": unknown operating system or architecture: invalid argument
--- FAIL: TestImagePullPlatformInvalid (0.01s)
```

**Comment by thaJeztah** [comment]
Daemon logs show that it returns an untyped error, hence using the default (`500` / Internal Server error);

```console
time="2024-01-21T00:18:31.260074294Z" level=debug msg="Calling POST /v1.45/images/create?fromImage=hello-world&platform=foobar&tag=latest"
time="2024-01-21T00:18:31.260220544Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!" error="\"foobar\": unknown operating system or architecture: invalid argument" error_type="*fmt.wrapError" module=api
time="2024-01-21T00:18:31.260320336Z" level=error msg="Handler for POST /v1.45/images/create returned error: \"foobar\": unknown operating system or architecture: invalid argument"
time="2024-01-21T00:18:31.260407169Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!" error="\"foobar\": unknown operating system or architecture: invalid argument" error_type="*fmt.wrapError" module=api
```

**Comment by thaJeztah** [comment]
Found the likely cause; the new module doesn't use containerd errdefs;

Screenshot 2024-01-21 at 01 25 19

**Comment by thaJeztah** [comment]
Some error messages need to be updated in tests;

```
=== Failed
=== FAIL: amd64.integration.image TestImportWithCustomPlatformReject/_______ (0.00s)
    import_test.go:182: assertion failed: expected error to contain "is an invalid component", got "Error response from daemon: \"       \" is an invalid OS component of \"       \": OSAndVersion specifier component must match \"^([A-Za-z0-9_-]+)(?:\\\\(([A-Za-z0-9_.-]*)\\\\))?$\": invalid argument"
        Error response from daemon: "       " is an invalid OS component of "       ": OSAndVersion specifier component must match "^([A-Za-z0-9_-]+)(?:\\(([A-Za-z0-9_.-]*)\\))?$": invalid argument
    --- FAIL: TestImportWithCustomPlatformReject/_______ (0.00s)

=== FAIL: amd64.integration.image TestImportWithCustomPlatformReject// (0.00s)
    import_test.go:182: assertion failed: expected error to contain "is an invalid component", got "Error response from daemon: \"\" is an invalid OS component of \"/\": OSAndVersion specifier component must match \"^([A-Za-z0-9_-]+)(?:\\\\(([A-Za-z0-9_.-]*)\\\\))?$\": invalid argument"
        Error response from daemon: "" is an invalid OS component of "/": OSAndVersion specifier component must match "^([A-Za-z0-9_-]+)(?:\\(([A-Za-z0-9_.-]*)\\))?$": invalid argument
    --- FAIL: TestImportWithCustomPlatformReject// (0.00s)

=== FAIL: amd64.integration.image TestImportWithCustomPlatformReject (0.01s)

**Comment by thaJeztah** [comment]
Testing update with https://github.com/containerd/containerd/pull/10189 included, but we may have issues with go1.22 being enforced by the containerd api module

**Comment by thaJeztah** [comment]
Yay!  CodeCov action is having a bad day on Windows;

Screenshot 2024-06-13 at 12 34 25

**Comment by thaJeztah** [comment]
@vvoland @dmcgowan PTAL

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
