### PR TITLE
[bump_v1.12.0] Additional cherrypicks for 1.12.0 rc5

### PR DESCRIPTION
**Pull request by tiborvass**
Cherrypicking:
- https://github.com/docker/docker/pull/25047
  - f9c920a service update: Don't assume existing pointers in spec are valid
- https://github.com/docker/docker/pull/25042
  - e6923f6 Remove swarm inspect and use info instead
  - e3c150b vendor engine-api to a52656d77f09d394104c1639824eada038bfdb89
  - 8ad9438 Address some displaying issues in docker info
- https://github.com/docker/docker/pull/25043
  - d8d71ad container/controller: avoid cancellation with forked pull context
- https://github.com/docker/docker/pull/25038
  - 4031d70 Add container labels to service create/update 
  - e462b45 Prevent panic on update --container-label-add 
- https://github.com/docker/docker/pull/25041
  - 6a754a4 Vendoring libnetwork to remove stale xfrm states

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by justincormack** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐳 👼

**Comment by thaJeztah** [comment]
fyi; we're merging this so that the piñata team can build/run tests; we'll do another WIP cherry-pick with (e.g.) some completion scripts, and have CI run a full cycle on that one

**Pull request merged**
