### PR TITLE
Creates a new filesystem integrity check.

### PR DESCRIPTION
**Pull request by sul3n3t**
This is experimental and requires an opt-in flag (`--checksumfs`).

Signed-off-by: Justin Cummins <sul3n3t@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @riyazdf @stevvooe PTAL

**Comment by stevvooe** [comment]
@endophage What are the ongoing plans for this?

**Comment by endophage** [comment]
@stevvooe I think we last talked about working out how to get something more officially integrated in to containerd?

**Comment by stevvooe** [comment]
@endophage Sounds good!

**Comment by thaJeztah** [comment]
Should we close this one then?

**Comment by endophage** [comment]
@thaJeztah at this point I think that's probably OK

**Comment by thaJeztah** [comment]
Thanks, closing for now :+1:

**Pull request closed without merging**
