### PR TITLE
Vendoring libnetwork 905d374 and other fix

### LINKED ISSUE #24463: swarm: Invalid broadcastQ encountered while gossiping for network
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   a34534f
 Built:        Fri Jul  8 17:52:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   a34534f
 Built:        Fri Jul  8 17:52:51 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 99xfpznq2d6o6ukkc8sm0chbs
 IsManager: Yes
 Managers: 1
 Nodes: 5
 CACertHash: sha256:f2597dd1d42b548f0e0e1ad2022237c552ca893ab451f7b77dd9acdbf05ca39d
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: node01
ID: ZTNM:55LA:E6YV:QC3Y:5QNC:LFMK:L4IE:MQ3Q:S43M:D45D:H4P7:HPLC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Digital Ocean VMs:

1 Manager: 2 GB Memory / 40 GB Disk / Ubuntu 16.04 x64
2 Agents: 1 GB Memory / 30 GB Disk / Ubuntu 16.04 x64

**Steps to reproduce the issue:**
1. Start a cluster (in this example: 1 manager and 2 workers)
2. Run a service
2. `docker swarm leave` on one of the workers
3. Join this worker back to the swarm

**Describe the results you received:**

On the node that left then joined the swarm again, I get an infinite round of error logs with:

```
ERRO[XXXX] Invalid broadcastQ encountered while gossiping for network 5oqb1ga4dkn0ygqzx98aeadnz
```

**Describe the results you expected:**

No error.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens systematically when doing a `docker swarm leave` and then `docker swarm join` of a worker. I'm not sure this is related to the advertised address as this works fine on the first try, seems like a cleanup problem on `docker swarm leave`.

/cc @mrjana @sanimej @aboch

### PR DESCRIPTION
**Pull request by aboch**
Fixes  #24463, #24346, #24201, #24377

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮
/cc @mavenugo

**Comment by mavenugo** [comment]
LGTM

**Comment by mavenugo** [comment]
experimental and win2in failures are unrelated. restarting them again.

**Comment by justincormack** [comment]
win2lin has memory issues at present, unrelated.

LGTM.

**Comment by thaJeztah** [comment]
all other CI is green, so guess this is ready to merge?

**Pull request merged**
