### PR TITLE
Updating call sequence for servicing Windows containers

### PR DESCRIPTION
**Pull request by swernli**
This change adjusts the calling pattern for servcing containers to use waiting on the process instead of expecting start to block.  This is safer, as it avoids timeouts in the start code path for the potentially expensive update operation.

### CODE REVIEW

**Comment by swernli** [comment]
@jhowardmsft @brian-young This is the servicing change we've been working on.

**Comment by jhowardmsft** [comment]
LGTM. Has Brian confirmed this works for his purposes?

**Comment by swernli** [comment]
Yup, we confirmed that this performs the right sequence with the updated servicing APIs.

**Comment by swernli** [comment]
Looks like this passed CI.  Can I get another review so this can be ready for check-in. @brian-young or @darrenstahlmsft perhaps?

**Comment by brian-young** [comment]
Oops, sorry, LGTM!

**Comment by thaJeztah** [comment]
Thanks for looking @brian-young.

LGTM

**Pull request merged**
