### PR TITLE
builder: fix layer leak on multi-stage wildcard copy

### LINKED ISSUE #37077: inodes not freed after repeated builds - overlay
This seems to be a regression of #9755.
I'm seeing this issue on a Docker build server with docker 18.03.0-ce.

**Description**
The error we get during a build: "no space left on device". This is due to the number of inodes 100% in use.

**Steps to reproduce the issue:**
1. Build in Jenkins with jenkinsfile using docker agents 
2. Daily clean all unused images and containers
3. After a while all inodes are in use

**Describe the results you received:**
```
root@nldt-17836:/data/docker# df -i
Filesystem                           Inodes    IUsed   IFree IUse% Mounted on
udev                                4098065      504 4097561    1% /dev
tmpfs                               4103142      697 4102445    1% /run
/dev/mapper/ccv360--yoda2--vg-root 30736384 30484641  251743  100% /
tmpfs                               4103142        1 4103141    1% /dev/shm
tmpfs                               4103142        3 4103139    1% /run/lock
tmpfs                               4103142       16 4103126    1% /sys/fs/cgroup
/dev/sda2                            124928      309  124619    1% /boot
/dev/sda1                                 0        0       0     - /boot/efi
tmpfs                               4103142        4 4103138    1% /run/user/1001

```
I tried cleaning everything after stopping all containers:
```
$ docker container prune 
$ docker image prune --all
$ docker volume prune
```
There were still 64708689 files in /var/lib/docker/overlay. There are 6786 folders inside /var/lib/docker/overlay. A lot of those folders only contain 6 files. Some contain over 60000 files (a complete filesystem).
I need to:
```
# rm -fr /var/lib/docker 
```
And redeploy the environment again to solve the issue.

**Describe the results you expected:**
All files in /var/lib/docker/overlay would be have been removed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issues happens only on buildservers that use jenkinsfile and build on docker nodes

**Output of `docker version`:**

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:01 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:31 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.03.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-124-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3GiB
Name: nldt-17836.ccveu.local
ID: SOVT:HYKE:SNF4:E6QV:DYH3:C7YL:COGM:X54D:WAMK:2S3A:MCCU:5HUZ
Docker Root Dir: /data/docker/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 debops.ccv.architecture=Ubuntu 16.04
 debops.ccv.environment=production
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server, Ubuntu 16.04
We are using storage-driver: "overlay".
I will switch now to "overlay2" and see if this makes a difference, but it may take a while to find out..

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #37077

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hm.. running into an issue with my test-script;

```
root@814acbff37c0:/go/src/github.com/docker/docker# ./repro-37077.sh 
Running ok case:
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM busybox AS build
 ---> 8c811b4aec35
Step 2/4 : RUN touch /vraag.html
 ---> Running in cc9f26ed0a85
Removing intermediate container cc9f26ed0a85
 ---> 443a073a7940
Step 3/4 : FROM scratch
 ---> 
Step 4/4 : COPY --from=build /vraag.html ./
COPY failed: stat /var/lib/docker/tmp/docker-builder602775229/vraag.html: no such file or directory
```

Or, without the script;

```bash
docker image build --quiet --no-cache -t my_app -<<EOF
FROM busybox AS build
RUN touch /vraag.html
FROM scratch
COPY --from=build /vraag.html ./
EOF
``

**Comment by thaJeztah** [comment]
And the "wildcard" case;

```bash
docker image build --quiet --no-cache -t my_app -<<EOF
FROM busybox AS build
RUN touch /vraag.html
FROM scratch
COPY --from=build /*.html ./
EOF
```

```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM busybox AS build
 ---> 8c811b4aec35
Step 2/4 : RUN touch /vraag.html
 ---> Running in 830f2f80c16d
Removing intermediate container 830f2f80c16d
 ---> b7c98bf6a1f4
Step 3/4 : FROM scratch
 ---> 
Step 4/4 : COPY --from=build /*.html ./
COPY failed: no source files were specified
```

**Comment by thaJeztah** [comment]
Looking good now:

Build, and start development container;

```
make BIND_DIR=. binary shell
```

Start daemon in the container;

```
make install
dockerd --debug &> /var/log/dockerd.log &
```

Create the test-script;

```bash
#!/bin/sh
set -e

build_image_ok() {
	docker image build --quiet --no-cache -t my_app:$1 -<<-EOF 1> /dev/null
		FROM busybox AS build
		RUN touch /vraag.html
		FROM scratch
		COPY --from=build /vraag.html ./
	EOF

	docker image prune -af | tail -1

	printf "Directories in /var/lib/docker/overlay2: "
	find /var/lib/docker/overlay2 -maxdepth 1 -type d | wc -l
}

build_image_faulty() {
	docker image build --quiet --no-cache -t my_app:$1 -<<-EOF 1> /dev/null
		FROM busybox AS build
		RUN touch /vraag.html
		FROM scratch
		COPY --from=build /*.html ./
	EOF

	docker image prune -af | tail -1

	printf "Directories in /var/lib/docker/overlay2: "
	find /var/lib/docker/overlay2 -maxdepth 1 -type d | wc -l
}

run_test() {
	echo "Running ok case:"
	i=1
	while [ $i -le 3 ]; do
		build_image_ok $i
		i=$(( i+1 ))
	done

	echo ""
	echo "Running faulty case:"
	i=1
	while [ $i -le 3 ]; do
		build_image_faulty $i
		i=$(( i+1 ))
	done
}

run_test
```

Run the test;

```
chmod +x ./repro-37077.sh
./repro-37077.sh 

Running ok case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2

Running faulty case:
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
Total reclaimed space: 1.146MB
Directories in /var/lib/docker/overlay2: 2
```

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by selansen** [comment]
LGTM

**Review by tiborvass — APPROVED** [review]
LGTM

**Pull request merged**
