### PR TITLE
Upgrade imdario/mergo to v0.3.5

### PR DESCRIPTION
**Pull request by vdemeester**
Mainly to get inline with `docker/cli` version of that dependency

Diff https://github.com/imdario/mergo/compare/0.2.1...v0.3.5

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
Upstream fix here : https://github.com/imdario/mergo/pull/82

**Comment by thaJeztah** [comment]
This one may be legit (see it fail in two places)

```
09:18:39 --- FAIL: TestLoadDaemonConfigWithNetwork (0.00s)
09:18:39 	daemon_unix_test.go:46: assertion failed: 127.0.0.1 (string) != ?00000000000000000000ffff7f00000100000000000000000000ffff00000000 (string)
09:18:39 time="2018-06-08T09:18:39Z" level=info msg="Got signal to reload configuration, reloading from: /tmp/config-854461364"
09:18:39 FAIL

**Comment by thaJeztah** [comment]
There's some more failures that may be new (but could be flaky/racy)

**Comment by vdemeester** [comment]
@thaJeztah it's legit, see my fix (that is not a fix yet :sweat:)

**Comment by vdemeester** [comment]
upstream fix merged (thanks so much @imdario :heart_eyes_cat:), should be good to go now

**Comment by imdario** [comment]
@vdemeester, how can I help?

**Comment by vdemeester** [comment]
@imdario :hugs: I'm not sure yet, I think it used to return `cluster-store={}` and now it returns `cluster-stor=`.. I wonder why :stuck_out_tongue:

**Comment by vdemeester** [comment]
Should be fixed :sweat_smile:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @AkihiroSuda ptal

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
