### PR TITLE
add docs for package repo maintenance

### PR DESCRIPTION
**Pull request by jessfraz**
ping @calavera @tiborvass @tianon

### CODE REVIEW

**Comment by tianon** [comment]
Hahaha, nice. :+1:

**Comment by MHBauer** [comment]
You may have forgotten to purge the cache. :wink:

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
it has :poo: happens, and "CELEBRATE", so LGTM

thanks @jfrazelle :smile:

**Pull request merged**
