### PR TITLE
pkg: plugins: fix and better handle errors

### PR DESCRIPTION
**Pull request by runcom**
When a plugin is returning an error cli will print:

```
docker: Error response from daemon: Plugin Error: AuthZPlugin.AuthZReq, {"Allow":false,"Err":"Cannot connect to the Docker daemon. Is the docker daemon running on this host?"}
```

First, code has an error and values were assigned to type `remoteError` w/o using struct keys and this resulted in wrong `Error()` ordering. The example above should have been, at least from the `remoteError.Error()` method:

```
docker: Error response from daemon: Plugin Error: {"Allow":false,"Err":"Cannot connect to the Docker daemon. Is the docker daemon running on this host?"}, AuthZPlugin.AuthZReq
```

This is fixing this.

Also, as pointed out in https://github.com/docker/docker/pull/18662, this patch is trying to decode the json in order to get an `Err` field which will be used on http status code != 200 (as in this case). The other PR just add an `Err` field to the plugin Response in case something goes wrong (as opposed to just returning allow/noallow)
The above error will result in

```
docker: Error response from daemon: Plugin Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?, AuthZPlugin.AuthZReq
```

ping @cpuguy83 @calavera @tiborvass 
/cc @rhatdan this should fix the error you were seeing

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by calavera** [comment]
This needs to be documented since it's part of the plugin spec :stuck_out_tongue_winking_eye:

**Comment by runcom** [comment]
@calavera what should I document here? The fact that an `Err string` field is meant for errors maybe, could you have a fast look at #18662?

**Comment by calavera** [comment]
Nevermind, I just double checked and we're already documenting the responses properly:

https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md#volumedrivercreate

**Pull request merged**
