### PR TITLE
CLI: Change default Swarm task history retention limit.

### PR DESCRIPTION
**Pull request by aluzzardi**
/cc @aaronlehmann @tiborvass

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

Filed #24958 to avoid the need for stuff like this in the future.

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by aaronlehmann** [comment]
`docs/reference/commandline/swarm_init.md` needs to be updated to include the new default, but this could be a separate PR.

**Comment by vdemeester** [comment]
I'll do the follow-up, merging this 👼

**Pull request merged**
