### PR TITLE
Introduce the new engine-api library.

### PR DESCRIPTION
**Pull request by calavera**
engine-api is a drop in replacement of the api library and types. It lives in https://github.com/docker/engine-api now.

This pull request replaces our packages with the new engine-api package. There is no change in functionality, the new library was designed to be a 1 to 1 match of what we have in master right now.

The real changes have been isolated to 44afd68 if you want to skip the other two commits in the review.

### CODE REVIEW

**Comment by LK4D4** [comment]
Not sure if we need design here :) it just moving code
design ok for me

**Comment by runcom** [comment]
design super ok :)

**Comment by icecrime** [comment]
LGTM

**Comment by tianon** [comment]
Fully-preserved Git history _and_ an explicit version number?? :heart_eyes: :heart: :heart: 

LGTM

**Comment by MHBauer** [comment]
Nice git work.

waterfront == engine-api?

**Comment by vdemeester** [comment]
**I like this a lot** *but* (there is always a but :stuck_out_tongue_closed_eyes:) I'm wondering something :

Let say I want to add a new command to the docker engine (or even just update an existing one somehow), I now have to split my work in two PRs right ? (one for `docker/docker` and one for `docker/engine-api`). What would be the *flow of work* ?

- Make a proposal/PR in `docker/docker` project *and temporarly modify vendored part of the `engine-api` to make it compile ? or vendor a fork code for the time being ?*
- Once design-review is ok on `docker/docker`, make a PR on the `docker/engine-api` project.
- Once it's merged on the `docker/engine-api`, vendoring it in the PR (probably without a git tag) and proceed to code review.

Maybe it would be the other way around : first a proposal in `docker/engine-api`, once it's there, a PR to vendor and add the feature to `docker/docker`. That would also mean there is some tight timing to take care of : feature A has to be in 1.10, and feature B is just a nice to have and will be longer to review and probably won't make it. When looking at the PR for those feature in `docker/engine-api`, merging feature A prior to feature B is an required.

Either way, it will probably make it a little trickier (or harder, or longer) to push some changes into `docker/docker` and will split the work a little bit. It is not necessarily a bad thing though :stuck_out_tongue:. Maybe I'm missing something too though :sweat_smile:.

Other question (maybe out of context but it's one the top of my head so…), does it make sence that maintainers of `docker/docker` are not maintainer of `docker/engine-api` — even though it is exported outside the `docker/docker` project it feels like it is still an important part to the engine. Maintainers "are ultimately responsible for quality in all its forms" on the `docker/docker` project, the `API` is one of these forms/aspect.

My questions are probably more about how does it change the way we currently work and is it going to be smooth, it probably has been thinking through and it's probably no big deal but I felt like asking :wink:.

**Comment by thaJeztah** [comment]
Although I like "lean" repositories, I share some of the concerns that @vdemeester mentioned, and think that we should at least describe the procedure (e.g. in the CONTRIBUTING.md of the engine-api repository).

Some thoughts;

- I think the main issue is that the API and the Engine are very much "tied together"; many changes in features in docker/docker also leads to a change in the API.
- Because the maintainers for the API are not the same people as the maintainers for docker/docker, it's *possible* that (for example) a new endpoint is added to the API, but rejected in docker/docker (or vice-versa)
- Where should the documentation for the API reside? Should that be moved to the engine-api repository?
- Should the version of the API be changed to `v1.22-dev` or `v1.22.0` to match the API version?


I think we should (at least) write up a clear procedure, for example:

- The docker/engine-api does *not* accept pull-requests for changes in the API, unless an accompanying  proposal is present in the docker/docker repository, and the design for that was approved (?). Bug fixes and code optimizations are of course always welcome.
- Because changes to the API and Engine are often closely related, we should prevent that code-changes in the API are reviewed twice (i.e. once in the PR in docker-engine, once in engine-api)

If moving the API to a separate repository is to make it easier to "vendor" the API in other projects, would an automatic "sync" to a separate repository satisfy that need? `</devils advocate>`

**Comment by duglin** [comment]
I was assuming it would be like runc, where docker engine is now a consumer of engine-api. So, changes start in engine-api and once proven to be safe/good, then we can vendor in a new engine-api into docker.

Whether this is easier/better than just moving the engine-api's into its own pkg dir under docker engine remains to be seen. I have to admit, I have a slight preference for a pkg dir mainly because this added level of indirection/work/coordination, and because we now reduced the number of maintainers (reviewers) down dramatically which can only slow down PR processing.

**Comment by MHBauer** [comment]
It looks like a clean cut. I see no `docker/docker` references. Good to have the three commits split as they are.

As @vdemeester & @thaJeztah say, it would be good to have a written down policy. `docker/engine-api` does need to stay in sync with the needs of `docker/docker`. I don't have any suggestions. I can see the issue with the maintainers, and it complicating the bureaucracy and increasing the communication involved. Maybe @dug is right.

I can see there being a divergence with the client providing compound-actions which abstract multiple server calls into a single binary golang call.

**Comment by calavera** [comment]
@duglin 

> because we now reduced the number of maintainers (reviewers) down dramatically which can only slow down PR processing.

we have guidelines to add new maintainers now, nothing says that the engine maintainers should not be maintainers of the api, we all should probably be. There is nothing stopping you from reviewing changes there.

Yes, there will be an increase of bureaucracy, because it has happened in the past already, but having the client outside the main repo makes much more sense for integrations that keeping it inside. The docker cli at the end, is just another consumer.

@thaJeztah 

> Because the maintainers for the API are not the same people as the maintainers for docker/docker, it's possible that (for example) a new endpoint is added to the API, but rejected in docker/docker (or vice-versa)

why would we want a new endpoint in the API that doesn't have a backend implementation?

> Where should the documentation for the API reside? Should that be moved to the engine-api repository?

It should live with the API, but I rather not move our current documentation yet. This is a good opportunity to start fresh with something like swagger or any other automatic generated documentation.

> The docker/engine-api does not accept pull-requests for changes in the API, unless an accompanying proposal is present in the docker/docker repository, and the design for that was approved (?). Bug fixes and code optimizations are of course always welcome.

As I said before, there is no point in accepting changes in the API that are not backed by an implementation.

> Because changes to the API and Engine are often closely related, we should prevent that code-changes in the API are reviewed twice (i.e. once in the PR in docker-engine, once in engine-api)

Up to everyone to review changes as many times as they'd like. I personally got two LGTMs from Jessie in the same PR yesterday, which obviously meant that it was **super** good.

@docker/engine-maintainers 

I know this change looks scary, you all raise completely valid concerns.  I'm still trying to figure out its full impact too, but I think the advantages of having a separated repo will be more than the disadvantages for the long run. As usual, this change is not written in stone. If we do this and we don't like it, we can always vendor it back under `pkg` like @duglin suggests.

**Comment by thaJeztah** [comment]
I'm not against this change; but we should write up how the process works / have better docs for that, otherwise it'll be super-hard for people to contribute, so LGTM, given that we work on that :)

**Comment by vdemeester** [comment]
@calavera I like the answer too `\o/`

> Yes, there will be an increase of bureaucracy, because it has happened in the past already, but having the client outside the main repo makes much more sense for integrations that keeping it inside. The docker cli at the end, is just another consumer.

True. In that matter, the `cli` could even be, at some point in another repository. The only *weird* think that I felt is that, (to simplify at maximum) the api is in the think in the middle of the cli and the engine (that both lives in this repository) — I was thinking the cli would go with it somehow. But that's not biggies.

> It should live with the API, but I rather not move our current documentation yet. This is a good opportunity to start fresh with something like swagger or any other automatic generated documentation.

:heart_eyes_cat: 

> I know this change looks scary, you all raise completely valid concerns. I'm still trying to figure out its full impact too, but I think the advantages of having a separated repo will be more than the disadvantages for the long run. As usual, this change is not written in stone. If we do this and we don't like it, we can always vendor it back under pkg like @duglin suggests.

True and good to here :stuck_out_tongue_closed_eyes:. I'm just like @thaJeztah, LGTM with some docs on how to contribute on both projects :wink:.

:+1:

**Comment by duglin** [comment]
given the overhead involved with a new repo, I'd prefer if we moved it to a pkg now and then moved to a new repo once we had a real need for it.   But I'm not -1 to the PR if others see the benefits, but I don't see them yet.

**Comment by jfrazelle** [comment]
ah rebase but LGTM

**Comment by cr7pt0gr4ph7** [comment]
One problem I see is: How do breaking changes to the internal API work without vendoring?
i.e. how do we ensure that even after changes like #19054 (where the type of a field changed from `version.Version` to `string`) both old and new checkouts of Docker can be built without problems?

**Comment by icecrime** [comment]
All the concerns voiced here are valid, but I think the pros vastly overwhelm the cons.

The API doesn't belong to the Engine alone anymore. The Docker CLI, Compose, Swarm, and many others, are API clients. Engine, Swarm, and many others, are API servers. I think it's better to think of this API as an upstream component, and the Engine be the "single-node" implementation of it. What might appear as an extra complication for Engine is also great news for many others, which now stand on equal footing with regard to the API.

I agree that we shouldn't have _less_ eyes on API PR now. If we do this right, we should also have more diversity on the API repo than Engine maintainers alone: changes to the API _should_ be reviewed with the point of view of other consumers. So in the end, I don't think we'll ever have a change to the API that ultimately Engine would reject, because API maintainers with Engine background would have had an opportunity to block problematic changes upstream.

I think that's a huge win, and that all the drawbacks I read here are valid but already lurk today in more subtle ways by putting the burden on other groups.

**Comment by cr7pt0gr4ph7** [comment]
My main concern is that this makes cross-package refactorings like #19133 and #19054 more difficult.
The main problem here is [`types/config.go`](https://github.com/docker/engine-api/blob/master/types/configs.go), which is part of the (currently internal) contract between the `api/server/router` and `daemon` packages, which currently both sit in the `docker/docker` repository.

**Comment by calavera** [comment]
@cr7pt0gr4ph7 hopefully we won't perform many more of those aggressive refactors once the packages are in the right place. It looks like a mess now because there is no easy way, but I'm paying attention to make sure everything is ported properly.

I have the feeling that we'll be more cautious with what we export/share once we have that clear separation in place.

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
