### PR TITLE
fix #12188 integration-cli: use "top" instead of "sleep" to avoid timeout

### LINKED ISSUE #12188: integration-cli: Tests using sleep can timeout too early - change to "top" instead
There is a lot of testing code that is using "docker run busybox sleep N", where N is usually one of (2, 10, 20), with a subsequent docker call to test something on this container (like docker ps or docker exec .. ping).

The problem with this is that in certain environments, the docker sleep process may have ended before the test can finish, resulting in a test failure (unexpected output).

I'd like to increase the sleep time (perhaps to 1000 - and perhaps storing it as a constant somewhere), so that it avoids the slow environment situation and runs the tests correctly.

Does anyone have an issue with such a change?

### PR DESCRIPTION
**Pull request by twhiteman**
Attempt 2 - Updated most of the sleep tests (there's still a few left where sleep is applicable).

Fix #12188

Signed-off-by: Todd Whiteman todd.whiteman@joyent.com

### CODE REVIEW

**Comment by estesp** [comment]
I think you have gotten one change in the pause tests to cause an unending wait because of this wait call: https://github.com/docker/docker/blob/master/integration-cli/docker_cli_pause_test.go#L47

When it was a limited sleep, then wait probably returned immediately.  The wait doesn't seem to be important to the test, so maybe it can be replaced by a kill of the container.

**Comment by LK4D4** [comment]
@estesp Yup, you're right. Thanks!

**Comment by LK4D4** [comment]
@twhiteman Also, you don't need to create new PR for each change. You can use `push -f` for updating.

**Comment by twhiteman** [comment]
Thanks for the help - I had mucked up my forked docker repo (spent too much time trying to fix it and gave up) - so created second PR... I'll learn eventually :)

This last commit drops the "docker wait" at the end of the ^TestPause test cases - so we'll see how jenkins fares this time.

**Comment by estesp** [comment]
You are past the pause tests, so I think it should be fine this time :+1: 

LGTM after CI pass.

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
