### PR TITLE
Move scripts back to hack/, leave docs in project/

### LINKED ISSUE #10741: Proposal: Remove the hack/ directory and just use project/
## Issue: hack/ symbolic link to project/ causes issues on Windows

When cloning the repo on Windows, as (for historical reasons) hack/ is now a symbolic link to project/, the symlink doesn’t get setup correctly. Windows git ends up treating hack as a 7 character file containing the word ‘project’, so it all starts going wrong quickly... In reality the hack/ directory (or symlink) is redundant.

There is a pretty messy workaround for git which is still error prone at http://stackoverflow.com/questions/5917249/git-symlinks-in-windows/16754068#16754068.

## Proposal

Looking at the build scripts, it seems just about everything is still referring to hack/. I think to make things easier going forward for supporting both Linux and Windows, the hack directory (or link as it is now) can be removed after files referring to hack/* are modified to their project/* equivalent.

I believe the list of files involved here from a first-pass scan is:

Docker/CHANGELOG.MD: 
Docker/Dockerfile
Docker/Makefile
Docker/builder/parser/testfiles/docker/Dockerfile
Docker/builder/parser/testfiles/docker/result
Docker/contrib/mkimage-debootstrap.sh
Docker/dockerversion/dockerversion.go
Docker/project/README.md
Docker/project/RELEASE-CHECKLIST.md
docker/project/dind
Docker/project/install.sh
Docker/project/make.sh
Docker/project/make/README.md
Docker/project/make/test-unit
Docker/project/release.sh
Docker/vendor/MAINTAINERS
Docker/vendor/src/github.com/docker/docker/hack/make/.validate

### PR DESCRIPTION
**Pull request by tianon**
This also removes the now-defunct `*maintainer*.sh` scripts that don't work with the new TOML format, and moves a couple not-build-or-release-related scripts to `contrib/` instead.

Implementing @jfrazelle's idea from https://github.com/docker/docker/issues/10741#issuecomment-74130222. :+1:

Closes #10741

### CODE REVIEW

**Comment by tianon** [comment]
Actually, moving to design review so we can make sure everyone's OK with this. :+1:

**Comment by icecrime** [comment]
Yes! So much better <3

**Comment by jfrazelle** [comment]
I am obviously +1 as well ;)

**Comment by jfrazelle** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
+1 definitely

**Comment by jfrazelle** [comment]
windows will fail but thats because its pointing to project, just heads up

**Comment by thaJeztah** [comment]
I think this will need changes to the new [contributor guide](https://docs.docker.com/project/test-and-docs/) as well? Because it mentions using `project/make.sh`

**Comment by tianon** [comment]
WHO PUT THAT THERE

**Comment by tianon** [comment]
(jk, fixing :heart:)

**Comment by tianon** [comment]
... but for the record, this is exactly why I mentioned time and again that script references should've stayed pointing to `hack` until we sorted this debate out. :wink:

**Comment by tianon** [comment]
Ok, docs fixes in, too.

**Comment by thaJeztah** [comment]
thanks!

ping @moxiegirl

**Comment by moxiegirl** [comment]
@tianon What do you think about holding off doing this until after the Birthday? Will that cause problems for people who want to dev in Windows? :-( why why why?)

I did test all the procedures out on Ubuntu and Mac...

**Comment by tianon** [comment]
This will actually _fix_ problems with folks on Windows, so I actually
think we should fast-track this for the birthday.

**Comment by moxiegirl** [comment]
@tianon Yeah, I was afraid you were going to say that. LGTM

**Comment by tianon** [comment]
@moxiegirl not sure what you mean?  The docs changes here are just fixing the paths to be what they should've been to begin with.  The code change is just moving a few files around back to where they used to live.

**Comment by moxiegirl** [comment]
@tianon  Aren't the Birthday people using 1.50? That is definitely what I am guiding them to do --- use the latest official release.  So, they won't get your changes if you don't update 1.50 right?

Then, I'll need to pick your changes to the .md files into docs and publish them too.

**Comment by jfrazelle** [comment]
almost everything should refer to hack, because it was always a symlink

**Comment by moxiegirl** [comment]
@tianon @jfrazelle Tibor sorted me out in chat.

**Comment by jhowardmsft** [comment]
LGTM. Should make my life a lot easier in Windows land :)

**Pull request merged**
