### PR TITLE
Add some new graphics for mac installation with boot2docker

### LINKED ISSUE #11552: Ensure graphics around docker and daemon have same basic look n feel
See images on these pages and make them all similar

* http://goo.gl/PkzAfP
  * http://docs.docker.com/installation/images/linux_docker_host.png
  * http://docs.docker.com/installation/images/mac_docker_host.png

* http://goo.gl/wxR2UL
  * http://docs.docker.com/article-img/architecture.svg

### PR DESCRIPTION
**Pull request by nfirvine**
- scalable SVG
- uses colours from the rest of the page
- emphasizes that boot2docker is the ordinary Linux setup in a VM

Fixes #11552

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice! I think the original `.png` should also be removed as part of this PR if they are no longer used (and a redirect added to https://github.com/docker/docker/blob/master/docs/s3_website.json#L19)

**Comment by moxiegirl** [comment]
@nfirvine this is really cool.  Since someone has to fork and pull to see these images built. I'm going to paste them here so folks can see what they are approving without having to build.  Architecture diagram:
image

Mac OSX Installation

image

image

**Comment by SvenDowideit** [comment]
LGTM - we could do with another for Windows - exactly the same as the OSX one ;)

**Comment by nfirvine** [comment]
@SvenDowideit: Done!

@thaJeztah Done, except for the redirect part. Not really sure what the deal with those redirects are?

**Comment by thaJeztah** [comment]
@nfirvine not a big issue, they can be used to redirect from the old .png to the new .svg files. I can create a gist with the changes if I have time, otherwise I think it can be done in a follow up PR

I think you will have to "squash" your commits to a single commit now. If you don't know how; I think there are some instructions somewhere (but I'm typing on my iPhone right now)

Graphics are looking really great; thanks a lot for this contribution!

**Comment by jamtur01** [comment]
LGTM

**Comment by moxiegirl** [comment]
I haven't merged this because of the architecture diagram.  I wanted our technical folks to give some feedback.  Please be patient.

**Comment by nfirvine** [comment]
@thaJeztah I've added what I think the redirect should be in a new commit. Please review.

Regarding squashing commits, I've done so, but am wondering why?

**Comment by thaJeztah** [comment]
> I've added what I think the redirect should be in a new commit. Please review.

Oh! Sorry for not creating the gist, it slipped my mind. Thanks! I think they look good

> Regarding squashing commits, I've done so, but am wondering why?

It's a convention used here; I understand that it might be different than you're used to (as am I in my daily work), but for Docker it's something that (currently) works best. Some reasons why are explained here: [CONTRIBUTING.md#conventions](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#conventions) 

Thanks again for this contribution!

**Comment by icecrime** [comment]
@moxiegirl LGTM

**Comment by nfirvine** [comment]
So how does this actually get published on the website?

**Comment by thaJeztah** [comment]
It should appear shortly on http://docs.master.dockerproject.com

The live docs are updated periodically by "cherry picking" documentation pull-requests in the "docs" branch. That's needed because the docs may contain features that are not yet implemented in the current docker release.

**Comment by ahmetalpbalkan** [comment]
OMG this messed up the windows video

**Comment by ahmetalpbalkan** [comment]
@nfirvine this is cool. thanks for the gfx.

**Comment by nfirvine** [comment]
Having not looked for a while, I checked yesterday and don't see the changes live on the site yet. What's up?

**Comment by thaJeztah** [comment]
Hm, I think it wasn't picked yet, and might be planned to go with the next release or just before DockerCon. There's a lot of work going on in preparation of DockerCon :)

**Comment by moxiegirl** [comment]
@nfirvine This is live on master but won't go out live on the site until the next release.  Very sorry for the delay look for it live around Dockercon in mid-June.

**Pull request merged**
