### PR TITLE
vendor: update swarmkit for 1.12.2

### PR DESCRIPTION
**Pull request by LK4D4**
This includes:
docker/swarmkit#1588
docker/swarmkit#1592
docker/swarmkit#1594

Fixes https://github.com/docker/docker/issues/24132

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Review by vieux — APPROVED** [review]
LGTM

**Comment by mavenugo** [comment]
Thanks @LK4D4 . Is any of the 3 patch here is applicable to master as well ? If yes, can you please also vendor in swarmkit master to docker master ? It is better to keep master upto-date.

**Comment by LK4D4** [comment]
@mavenugo Will open at monday. Just updated docker in swarmkit.

**Pull request merged**
