### PR TITLE
Rename BINDDIR to BIND_DIR

### LINKED ISSUE #10718: make targets don't run for Mac Users Out-of-the-box
I ran into a problem as did @jeffdm with the Makefile in a Mac OS X environment.  Running make binary or make cross did not actually output into the `bundles` directory.  The work around is to change the Makefile 

```
BINDDIR := $(if $(DOCKER_HOST),,bundles)
```
to

```
BINDDIR := bundles
```

Absent this, the Makefile seems to work but actually does nothing.  It might be dumping to the VM but even so painful when it can go locally (presumably) to the bundles subdir.  Any reason not to fix this?

### PR DESCRIPTION
**Pull request by tianon**
It turns out the back-to-back `D`s here were tripping people up because visually, it looks like a typo.  This renames the variable to `BIND_DIR`, but allows `BINDDIR` to continue working for backwards-compatibility.

Fixes #10718

### CODE REVIEW

**Comment by tianon** [comment]
cc @jfrazelle @moxiegirl

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
