### PR TITLE
Enable docker.socket and docker.service in fedora install docs

### PR DESCRIPTION
**Pull request by crosbymichael**
This makes sure both the systemd services are enabled by default in the install instructions because the rpm packages do not do this, unlike the deb packages.

If docker is not enabled then it will not restart on system boot allowing containers with restart policies to be started.  Again, this is not an issue for deb based systems because they do this in the install scripts but it is a general expectation that rpm based systems require the user to manually enable these services.

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, do we need this for the RHEL, and CentOS pages as well?

**Comment by crosbymichael** [comment]
@thaJeztah they don't have the systemctl install docs in those pages

**Comment by thaJeztah** [comment]
Oh, alright, I'll do a follow up to bring them in sync

**Pull request merged**
