### PR TITLE
Use Mkdev, Major and Minor functions from golang.org/x/sys/unix

### PR DESCRIPTION
**Pull request by tklauser**
**- What I did**

Re-vendor golang.org/x/sys and use Mkdev, Major and Minor functions from there  instead of the locally defined versions which use the Linux specific device major/minor encoding.

This also means that the device number should now be properly encoded on e.g. Darwin, FreeBSD or Solaris.

**- How I did it**

See above.

**- How to verify it**

All relevant tests still pass.

### CODE REVIEW

**Comment by fntlnz** [comment]
Changes LGTM when `experimental` completes, worth mentioning for other reviewers that since `8dbc5d05d6edcc104950cc299a1ce6641235bc86`, `SIGUNUSED` is not present anymore in `golang.org/x/sys`

**Comment by tklauser** [comment]
@fntlnz not quite sure what you mean. Should I squash all 3 commits (re-vendor, SIGUNUSED removal and Major/Minor/Mkdev usage) into a single one and re-push?

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tophj-ibm** [comment]
I am not a maintainer, but IMO this is a case where squashing isn't necessary. It's useful to have separate commits in case something breaks that isn't initially caught by the CI and you have to revert. Not to mention, all of these commits are actually different, and not just random fixes on top of one another.

experimental swarm panic could be serious. Restarted the tests as I'm not sure if it's flaky or related to this pr. (old failure log for ref: https://jenkins.dockerproject.org/job/Docker-PRs-experimental/37429/consoleFull )

**Comment by fntlnz** [comment]
@tklauser sorry for not being clear. 

@tophj-ibm - the [CONTRIBUTING](https://github.com/moby/moby/blob/master/CONTRIBUTING.md) states: 

> Before you make a pull request, squash your commits into logical units of work using git rebase -i and git push -f. A logical unit of work is a consistent set of patches that should be reviewed together: for example, upgrading the version of a vendored dependency and taking advantage of its now available new feature constitute two separate units of work. Implementing a new function and calling it in another file constitute a single logical unit of work. The very high majority of submissions should have a single commit, so if in doubt: squash down to one.


This is indeed the second case,  @tklauser updated the dependency, then he adapted the codebase to that change by removing the unneeded signal and using the dependency in a few places. For this I think that the three commits are tight coupled, if it was not the case I would have suggested to open different PRs.

**Comment by fntlnz** [comment]
LGTM

**Review by fntlnz — APPROVED** [review]

**Comment by tklauser** [comment]
@fntlnz thanks for clarifying! This change rather sounded like the first case to me:

> for example, upgrading the version of a vendored dependency and taking advantage of its now available new feature constitute two separate units of work

That's why I submitted it as three separate commits. I will squash them now as per your request.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
