### PR TITLE
fix typo: transtions -> transitions

### PR DESCRIPTION
**Pull request by max8899**
**- What I did**
fix typo
**- How I did it**
transtions -> transitions
**- How to verify it**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
https://github.com/moby/moby/pull/37790#issuecomment-419321323

**Comment by max8899** [comment]
@AkihiroSuda which pr did't squash?

**Comment by AkihiroSuda** [comment]
Please squash all your typo-fix PRs to a single PR.

You could also collaborate your colleagues to squash all typo-fix PRs from your company.

**Comment by max8899** [comment]
@Akasurde did you ever looked into this? This all my typo pr for moby.

**Comment by Akasurde** [comment]
@max8899 I am not sure I am connected to this.

**Comment by max8899** [comment]
@Akasurde sorry for that

**Pull request closed without merging**
