### PR TITLE
Disable built-in SD on default bridge network

### LINKED ISSUE #16619: Docker updates /etc/hosts for all containers, I don't want it to
I swear this is recent - I have never seen it before 1.8 (but maybe I am nuts).  It used to be that if you used docker links, the /etc/hosts file would be updated.  Now it seems that ALL containers (even those without links) have their /etc/hosts files updated to know about all containers on the local machine.

Sniffing around this look like it might be libnetwork related, but I am not 100% sure.

How do I turn this off?  Container names are not what we want to be exposing to users.

@mavenugo

### LINKED ISSUE #17190: Docker 1.8 corrupts /etc/hosts files in containers
related: #16619

@mavenugo  - We have a problem.

We've been experiencing periodic end-to-end test failures where some containers can not resolve "localhost".  Killing the container and letting it restart usually fixes the problem.  Today we got it into this state and pinned down the following:

The container in question has a /etc/hosts file that is several hundred lines long.  That /etc/hosts file does NOT have localhost or the container's own IP.  If I add those 2 lines the tests pass.

Of course I thought of #16619 .  So we looked at /etc/hosts of every container on this machine - 84 in total.  Those files range in size from 175 lines (correct: 7 boilerplate + 2 per container) to 1700+ lines.  Looking at the offending files, there are a lot of duplicate IPs.  It looks like old containers have not been removed, but localhost, "self", and the ipv6 boilerplate has been removed.

Even looking at my local test machine (far less churn) I see the same.  I have 4 containers with network namespace running, I should have 8+7=15 lines, right?

```
# wc -l /var/lib/docker/containers/*/hosts
  15 /var/lib/docker/containers/3fc23782814513d1934ce21c0f1b096263df1fcacee6787208c3cda715822356/hosts
  15 /var/lib/docker/containers/4b7e8432a368eeb7f1dc49230f16c1d7c788b471e4dfa7d8fbf709c3495f430f/hosts
  19 /var/lib/docker/containers/5715aa09fc091ee0ff3d4dcf2ee300d8e52603dafcde8f24aaf1def960cf4a28/hosts
  15 /var/lib/docker/containers/6e7fe564dece829de3c335400357b2ef327a1a44c638045350f0b49e5324a189/hosts
  15 /var/lib/docker/containers/7845351acbacf0588142a1ebfa3fa481c3191da48a188b20c5d5fdae689cef1e/hosts
  17 /var/lib/docker/containers/ba23cbabfa90700f4d9ba80c5723afb1d7479a08b12efdded74e5874991ce76b/hosts
  17 /var/lib/docker/containers/c1e64038b35a0527b6aef911dad002278569724263cc922efd8e715747e83538/hosts
  19 /var/lib/docker/containers/fc7c5475fd923b75a0595431dcaf6b6db5fa8a18409d0df4e6282e3c0bd8aedf/hosts
```

Diffing a 15 and 19 line file shows:

```
# diff -u -U 100 <(sort -n /var/lib/docker/containers/3fc23782814513d1934ce21c0f1b096263df1fcacee6787208c3cda715822356/hosts) <(sort -n /var/lib/docker/containers/5715aa09fc091ee0ff3d4dcf2ee300d8e52603dafcde8f24aaf1def960cf4a28/hosts)
--- /dev/fd/63	2015-10-19 23:59:20.618879795 +0000
+++ /dev/fd/62	2015-10-19 23:59:20.618879795 +0000
@@ -1,15 +1,19 @@
 ::1	localhost ip6-localhost ip6-loopback
 fe00::0	ip6-localnet
 ff00::0	ip6-mcastprefix
 ff02::1	ip6-allnodes
 ff02::2	ip6-allrouters
+10.244.0.10	distracted_ritchie
+10.244.0.10	distracted_ritchie.bridge
 10.244.0.2	k8s_POD-7be6d81d_fluentd-cloud-logging-kubernetes-minion-isfq_kube-system_dcfde077753b8b6908952cfea6a14200_c4f00d1d
 10.244.0.2	k8s_POD-7be6d81d_fluentd-cloud-logging-kubernetes-minion-isfq_kube-system_dcfde077753b8b6908952cfea6a14200_c4f00d1d.bridge
 10.244.0.3	k8s_POD-7be6d81d_heapster-v10-lx8q7_kube-system_2a3fc6d6-6ddb-11e5-9249-42010af00002_cbe79e10
 10.244.0.3	k8s_POD-7be6d81d_heapster-v10-lx8q7_kube-system_2a3fc6d6-6ddb-11e5-9249-42010af00002_cbe79e10.bridge
 10.244.0.4	k8s_POD-c5371ceb_monitoring-influxdb-grafana-v2-koh3j_kube-system_2a43f315-6ddb-11e5-9249-42010af00002_76d3cb92
 10.244.0.4	k8s_POD-c5371ceb_monitoring-influxdb-grafana-v2-koh3j_kube-system_2a43f315-6ddb-11e5-9249-42010af00002_76d3cb92.bridge
 10.244.0.5	k8s_POD-9db2f941_kube-ui-v2-v4yd6_kube-system_2a42e6da-6ddb-11e5-9249-42010af00002_69a0a0c7
 10.244.0.5	k8s_POD-9db2f941_kube-ui-v2-v4yd6_kube-system_2a42e6da-6ddb-11e5-9249-42010af00002_69a0a0c7.bridge
-10.244.0.5	kube-ui-v2-v4yd6
+10.244.0.6	k8s_POD-6e934112_kube-dns-v9-ee38a_kube-system_2a4c2763-6ddb-11e5-9249-42010af00002_86e49fbc
+10.244.0.6	k8s_POD-6e934112_kube-dns-v9-ee38a_kube-system_2a4c2763-6ddb-11e5-9249-42010af00002_86e49fbc.bridge
+10.244.0.6	kube-dns-v9-ee38a
 127.0.0.1	localhost
```

Is there any reason the hosts files would be different for different containers on the same node?

I know docker is live-editing the hosts file (which is absolutely unsafe, but should only be unsafe for the users in the container).  Any clues on what's going on?

@artfulcoder

### PR DESCRIPTION
**Pull request by aboch**
fixes #17190 as per  [comment](https://github.com/docker/docker/issues/17190#issuecomment-150743021)

Signed-off-by: Alessandro Boch aboch@docker.com

Also fixes #16619 #16445

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @aboch !

**Comment by cpuguy83** [comment]
LGTM

**Comment by phemmer** [comment]
> fixes #17190

This does not fix #17190. It just makes the corruption less likely. There are still several race conditions.

**Comment by mavenugo** [comment]
@phemmer the corruption issue is addressed via https://github.com/docker/docker/pull/17278. by turning off the /etc/hosts update for the default bridge, it addresses #17190, which is reported for the default bridge and it is exactly the same as before and hence it does fix that issue.

Now, your proposal (which I like a lot) : https://github.com/docker/docker/issues/17195 will solve the general /etc/hosts update issue. That is the rationale behind the `fixes` assertion here.

**Comment by mavenugo** [comment]
LGTM

**Comment by mavenugo** [comment]
This also addresses #16619 and #16445

**Comment by tiborvass** [comment]
Updated PR description with *"fixes"* for the two issues @mavenugo mentioned above.

LGTM

**Comment by aidanhs** [comment]
Just want to briefly re-state what I said on https://github.com/docker/docker/issues/17190#issuecomment-151136951 - this is a change that breaks behaviour observable in three releases (1.8.X) and offers no alternative for people who need it to permit previously impossible use-cases.

(I particularly object to this breaking change being added during the 1.9 RC process)

**Comment by thaJeztah** [comment]
@aidanhs that behavior should never have found its way into the a regular release; it was part of the "experimental" builds, but leaked into the regular builds, which is the bug being fixed here. If you need "service discovery", create a network and attach containers to that.

**Comment by aidanhs** [comment]
@thaJeztah I appreciate it was unintentional, but it did happen, has been present for two months and people now rely on the behaviour!

As mentioned in the [blog post](http://aidanhs.com/blog/post/2015-10-07-dockerfiles-reproducibility-trickery/) (from the comment I linked to above), it lets docker build do a number of helpful new things, like retrieve files over SSH without baking in credentials and perform nested docker build. These are things people really do want (there are links to issues in that post). Attaching to a network is not possible for docker build.

If there was a way to set a different default network (and therefore get back to service discovery) I'd have no problem - does a change like this have any chance of getting into 1.9 to help alleviate the breakage of this PR?

**Comment by thaJeztah** [comment]
@aidanhs relying on external services during build is not something we advocate, because it makes a build not reproducible in different environments. I'm not aware of a `--default-network` (e.g.) flag for the daemon being worked on. I know it has been discussed at some point, but don't think it reached consensus.

**Comment by aidanhs** [comment]
@thaJeztah it's a nuanced discussion...but from that point of view our builds aren't reproducible anyway because they have HTTP requests to `.internal` addresses - people would also object if this got broken! Anyway, the only reason we need this service discovery is because the necessary features aren't in dockerfiles (and never will be, due to the freeze). The alternative (restarting the daemon and adding `--dns $BRIDGE_IP`) is really painful in comparison.

Manually adding containers to a network isn't exactly delightful either.

I was more thinking of something like `docker network create --set-as-default newbridge`.

**Comment by cpuguy83** [comment]
@aidanhs Why not use `--dns` on the daemon and then register your containers with a DNS service?

**Comment by mavenugo** [comment]
@aidanhs also one can launch a container in a user-created network using the `--net=<network>` option (which automatically connects to the network and SD in-built).
If your service that uses Docker API (instead of CLI), then you could make `--net=<network>` as default and your users wont know the difference. Will that work ?
I would like to understand your service better. am available in IRC (@madhu) and we can discuss more in detail.

**Comment by aidanhs** [comment]
@cpuguy83 

> The alternative (restarting the daemon and adding --dns $BRIDGE_IP) is really painful in comparison.

Because it's really painful :)

To put this into context, I'm sharing images and dockerfiles with people who have no idea how docker works behind the scenes and don't even have root access on their machines (yes, they can run containers so could get root, but they're not at that skill level). Getting them to find the bridge IP, change their daemon arguments to have dns pointing at the bridge IP, restart their daemon, start a DNS service container listening on the bridge IP, *then* do their build...they're just not going to bother. This also wouldn't be so bad if restarting the daemon didn't kill all containers!

Right now I can just say "run this command (to start a container), then do docker build". If I could set a default network for all future container startups, that's three commands. If it were possible to pass --net to docker build, that's two commands. If it were possible to intercept the API calls the builder makes (i.e. when #14298 happens) to alter --net myself, that's two commands. If it were possible to enable service discovery on the default bridge, that's also two commands. But none of these are available right now!

Any of the above would be great.

@tiborvass suggested an interesting approach on IRC:
```
docker run --net=<network> $OTHER_RUN_OPTIONS builder-image | docker build -t finalimage -
```
This is pretty cool, but requires splitting a build into two parts (the pre build to gather resources, the actual build with the gathered resources) and doesn't cover some use-cases, like nested builds.

**Comment by mitar** [comment]
> as of 1.9.0 (planned) the feature from 1.8.0 will be disabled on the default bridge, and will only be available on networks you create yourself 

Could this be made a configuration option for Docker instead? So should the default bridge have this feature or not? And then the host can decide? In this way it can be made backwards compatible, with Docker 1.9 hosts just have to enable it, while the new default would be that it is disabled?

**Comment by aidanhs** [comment]
@mitar see #17375

However I think in the long run https://github.com/docker/libnetwork/pull/722 is more promising, as changing things for an existing network is something people are going to want to do at some point anyway.

**Comment by mitar** [comment]
@aidanhs: That looks great! We really have a problem because without a way to turn on the 1.8 behavior for the whole Docker daemon we will have issues migrating to 1.9 all our infrastructure. It is really sad that a feature is being removed just so, without any easy backwards compatibility in mind.

**Pull request merged**
