### PR TITLE
[WIP] testing buildkit 0.12 fixes

### PR DESCRIPTION
**Pull request by thaJeztah**
- quick attempt to fix https://github.com/moby/moby/pull/45966#issuecomment-1643548223

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
vendor validation will fail on this one, as I manually modified the vendored files

**Comment by thaJeztah** [comment]
Linter found some issues;

```
libcontainerd/remote/client.go:212:13: copylocks: assignment copies lock value to opts: github.com/docker/docker/vendor/github.com/containerd/containerd/runtime/v2/runc/options.Options contains github.com/docker/docker/vendor/google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
				opts := *c.v2runcoptions
				        ^
daemon/runtime_unix_test.go:246:17: copylocks: assignment copies lock value to configdOpts: github.com/docker/docker/vendor/github.com/containerd/containerd/runtime/v2/runc/options.Options contains github.com/docker/docker/vendor/google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
	configdOpts := *stockRuntime.Opts.(*v2runcoptions.Options)
	               ^
builder/builder-next/adapters/containerimage/pull.go:22:2: SA1019: "github.com/containerd/containerd/remotes/docker/schema1" is deprecated: use images formatted in Docker Image Manifest v2, Schema 2, or OCI Image Spec v1. (staticcheck)
	"github.com/containerd/containerd/remotes/docker/schema1"
	^
```

**Comment by thaJeztah** [comment]
Two flaky test failures;

```
=== Failed
=== FAIL: github.com/docker/docker/integration/container TestExecWithCloseStdin (6.03s)
    exec_test.go:77: failed to read the content in time

=== FAIL: github.com/docker/docker/integration/container TestRenameStoppedContainer (13.11s)
    rename_test.go:58: timeout hit after 10s: waiting for container to be one of (exited), currently running
```


Some failures on Windows that I _THINK_ are unrelated, but I'll kick those again after

```
=== Failed
=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate/0_config:_{volume__c:\foo_false__<nil>_<nil>_<nil>_<nil>} (12.30s)
    docker_api_containers_test.go:2157: timeout hit after 10s: container d8899eaa18c06679eb8f5d836861b00ce887613d7e29b38a5c79a354f45c4c09 is running, waiting for exit

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate/1_config:_{volume__c:\foo\_false__<nil>_<nil>_<nil>_<nil>} (12.18s)
    docker_api_containers_test.go:2157: timeout hit after 10s: container 1f98febef0ed3bba3f2c8cc964dfd56e7af160e3b307c4f90716aaf36b634dd1 is running, waiting for exit

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate/2_config:_{volume_test1_c:\foo_false__<nil>_<nil>_<nil>_<nil>} (12.13s)
    docker_api_containers_test.go:2157: timeout hit after 10s: container 2e22f8b3d0229272ca4a581872afaa1f895e88ab681cdf9d2c947db5971dbbd7 is running, waiting for exit

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate/3_config:_{volume_test2_c:\foo_true__<nil>_<nil>_<nil>_<nil>} (12.29s)
    docker_api_containers_test.go:2157: timeout hit after 10s: container f7bbe4731a3b4b9e886c8bf256492305c71e91152b228e6fe5fed212dd2fba89 is running, waiting for exit

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate/4_config:_{volume_test3_c:\foo_false__<nil>_0xc000cb4018_<nil>_<nil>} (12.15s)
    docker_api_containers_test.go:2157: timeout hit after 10s: container 39cd582a0cbeeaba949d0b92c42bea47660a74a6d4d85286abbe06f40b2fdb2c is running, waiting for exit

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate/5_config:_{bind_C:\Users\RUNNER~1\AppData\Local\Temp\test-mounts-api-13699587998_c:\foo_false__<nil>_<nil>_<nil>_<nil>} (12.21s)
    docker_api_containers_test.go:2157: timeout hit after 10s: container d599fca52be8409f25433e5d64957e39a97cc61cd528586e3dd476aade4fd57b is running, waiting for exit

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate/6_config:_{bind_C:\Users\RUNNER~1\AppData\Local\Temp\test-mounts-api-13699587998_c:\foo_true__<nil>_<nil>_<nil>_<nil>} (13.08s)
    docker_api_containers_test.go:2157: timeout hit after 10s: container 67863418730b3320bb297b492d79b5d66a3d00109be881811bf3f97dc0fb571d is running, waiting for exit

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite/TestContainersAPICreateMountsCreate (89.19s)

=== FAIL: github.com/docker/docker/integration-cli TestDockerAPISuite (857.05s)
```

Not sure what's happening with `docker-py` would have to check;

```
---> Making bundle: test-docker-py (in bundles/test-docker-py)
---> Making bundle: .integration-daemon-start (in bundles/test-docker-py)
Using test binary /usr/local/cli-integration/docker
# DOCKER_EXPERIMENTAL is set: starting daemon with experimental features enabled! 
Not: starting.
Starting dockerd
INFO: Waiting for daemon to start...
.
---> Making bundle: .build-empty-images (in bundles/test-docker-py)
Loaded image: emptyfs:latest
Loaded image ID: sha256:0df1207206e5288f4a989a2f13d1f5b3c4e70467702c1d5d21dfc9f002b7bd43
INFO: Building docker-sdk-python3:5.0.3...
ERROR: failed to solve: Unavailable: error reading from server: EOF
make: *** [Makefile:198: test-docker-py] Error 1
Error: Process completed with exit code 2.
```

**Comment by thaJeztah** [comment]
Some buildkit CI failures;

```
=== FAIL: frontend TestFrontendIntegration/TestRefEvaluate/worker=dockerd (1.27s)
    frontend_test.go:341: 
        	Error Trace:	/src/frontend/frontend_test.go:341
        	            				/src/util/testutil/integration/run.go:90
        	            				/src/util/testutil/integration/run.go:204
        	Error:      	Received unexpected error:
        	            	lease does not exist: not found
```

**Comment by crazy-max** [comment]
Ok no fix in protobuf repo after all but recall this one https://github.com/moby/buildkit/issues/3187#issuecomment-1280811885 with same lint issues but don't remember how I fixed this in BuildKit...

**Comment by neersighted** [comment]
Closing as the relevant changes are in BK/the original PR now.

**Pull request closed without merging**
