### PR TITLE
Update link title

### PR DESCRIPTION
**Pull request by yitznewton**
Signed-off-by: Benjamin Schaffer yitznewton@hotmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for contributing @yitznewton, but I don't think this is the right change, because then it won't match the title of the document it's linking to; https://github.com/docker/docker/blob/master/docs/userguide/containers/networkingcontainers.md

Also, it like this needs a rebase now :cry:

I'm going to close this PR, but feel free to comment here, thanks for contributing!! :heart:

**Comment by yitznewton** [comment]
I see; I was going off the title on https://docs.docker.com/engine/userguide/networkingcontainers/

**Comment by yitznewton** [comment]
That link/title is mismatched - how would I go about fixing that?

**Comment by yitznewton** [comment]
Oh I see again; it seems to have been fixed a few days ago in GitHub and not made its way to the public site yet. :+1:

**Comment by thaJeztah** [comment]
Ah, that would explain it, :+1: thanks!

**Pull request closed without merging**
