### PR TITLE
Bump notary version to 0.4.2

### PR DESCRIPTION
**Pull request by cyli**
This bumps the notary dependency up to 0.4.2 (full changelogs [here](https://github.com/docker/notary/releases/tag/v0.4.2)).

The docker-client-relevant behavior changes are:
- Will now compile under windows [#970](https://github.com/docker/notary/pull/970)
- Improved error messages for client authentication errors [#972](https://github.com/docker/notary/pull/972)
- Support for finding keys that are anywhere in the `~/.docker/trust/private` directory, not just under `~/.docker/trust/private/root_keys` or ``~/.docker/trust/private/tuf_keys` [#981](https://github.com/docker/notary/pull/981)
- Previously, on any error updating, the client would fall back on the cache.  Now we only do so if there is a network error or if the server is unavailable or missing the TUF data. Invalid TUF data will cause the update to fail - for example if there was an invalid root rotation. [#982](https://github.com/docker/notary/pull/982)
- Improve root validation and yubikey debug logging [#858](https://github.com/docker/notary/pull/858) [#891](https://github.com/docker/notary/pull/891)
- Warn if certificates for root or delegations are near expiry [#802](https://github.com/docker/notary/pull/802)
- Warn if role metadata is near expiry [#786](https://github.com/docker/notary/pull/786)
- Fix passphrase retrieval attempt counting and terminal detection [#906](https://github.com/docker/notary/pull/906)

cc @riyazdf @endophage

### CODE REVIEW

**Comment by vieux** [comment]
ping @riyazdf @endophage

**Comment by vieux** [comment]
SGTM

**Comment by endophage** [comment]
LGTM!

**Comment by cyli** [comment]
^sorry, fixed an error message typo in two of the tests

**Comment by justincormack** [comment]
LGTM

**Comment by riyazdf** [comment]
LGTM

**Comment by cyli** [comment]
bump. :)  can this be merged?

**Comment by thaJeztah** [comment]
Looks like some related commits could be squashed, or are we good with having them all separate?

**Comment by cyli** [comment]
@thaJeztah I have no strong feelings.  I can squash them if you like.

**Comment by thaJeztah** [comment]
@cyli perhaps split in "bump" commits  and "fix" commits

**Comment by thaJeztah** [comment]
oh! done already, haha

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
