### PR TITLE
[23.0 backport] Update Go to go1.20.5

### PR DESCRIPTION
**Pull request by corhere**
- Closes #45069

23.0 backports of:
- #44620
- #45135
- #45275
- #45456 
- #45745

I also upgraded 1.20.4->1.20.5 in Dockerfile.e2e, which was overlooked in #45745 due to the file no longer existing in master.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
(Looking from my phone) https://github.com/moby/moby/pull/44620 also has some other PRs linked; have those been backported already to 23.0?

**Comment by corhere** [comment]
@thaJeztah 
- https://github.com/moby/moby/pull/45009

**Comment by cpuguy83** [comment]
```
[2023-06-23T21:20:37.680Z] === FAIL: libnetwork/networkdb TestNetworkDBCRUDTableEntries (7.83s)
[2023-06-23T21:20:37.680Z]     networkdb_test.go:310: Entry existence verification test failed for node2(2c7599b2d027)
```

Retriggering this.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks for checking 👍

**Review by neersighted — APPROVED** [review]

**Pull request merged**
