### PR TITLE
Updates to bash completion for docker run and docker daemon.

### PR DESCRIPTION
**Pull request by albers**
See individual commit messages for details.
5c1ad6f refers to #15520, #15521

ping @jfrazelle @tianon

### CODE REVIEW

**Comment by jfrazelle** [comment]
awesome @albers you rock LGTM

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @calavera for cherry-pick in 1.8.2?

**Comment by calavera** [comment]
It looks like these are just missing options, nothing broken. I don't think we should cherry pick.

**Comment by thaJeztah** [comment]
@calavera hm, I get your thinking, otoh, that means we will never ship an 1.8 release with working (complete) completion scripts for the features that were added in 1.8. I know they got excluded from the original release, because they were added after code-freeze, but thought that adding them now could work.

**Comment by calavera** [comment]
code-freeze means that it won't be added in in the whole 1.x series unless it's ready before the due date. So, yes, this won't ever be in a 1.8.x release.

**Comment by albers** [comment]
I respect your point of view, but the completions are somewhat special:
Even a completely broken completion would not impact the docker stabiltiy. They are kind of tooling.
So there is not very much risk in pulling them in.

The point hat @thaJeztah made is not only valid for 1.8.x, it applies to any major release:
For me as a main contributor to the bash completion it is very hard to spot changes that are relevant. It gets complicated by the fact that it's not easy to tell the features that really end up in a specific release from those that are just merged into master.

In practice I _always_ end up finding overseen changes in the release notes and completion is _never_ up to date.
This is quite frustrating and I really would like to see a loosend code freeze policy here.

**Comment by calavera** [comment]
Thanks for your comment @albers. After further consideration, I agree with you, and I'll cherry pick this change, and others regarding cli completion, into the bump PR asap.

Going further, I think we should consider missing completion options as bugs in every major release, and therefore, cherry pick fixes into patch releases as a rule of thumb.

**Comment by calavera** [comment]
Cherry picked into #15809

**Comment by thaJeztah** [comment]
Thanks so much, @calavera :+1:

**Comment by albers** [comment]
> Going further, I think we should consider missing completion options as bugs in every major release, and therefore, cherry pick fixes into patch releases as a rule of thumb.

That's good news, thanks very much!

**Pull request merged**
