### PR TITLE
seccomp: add support for Landlock syscalls in default policy 

### PR DESCRIPTION
**Pull request by Xyene**
This commit allows the `landlock` system call in the default seccomp
policy.

[Landlock](https://www.kernel.org/doc/html/latest/userspace-api/landlock.html) was introduced in kernel 5.13, to fill the gap that
inspecting filepaths passed as arguments to filesystem system calls is
not really possible with pure `seccomp` (unless involving `ptrace`).

Allowing `landlock` by default fits in with allowing `seccomp`, for
containerized applications to voluntarily restrict their access rights
to files within the container.

### CODE REVIEW

**Comment by Xyene** [comment]
(CI failure appears unrelated, please correct me if wrong.)

**Review by AkihiroSuda — APPROVED** [review]

**Review by tonistiigi — DISMISSED** [review]
`landlock` is not a syscall afaics https://github.com/torvalds/linux/blob/v5.16/include/linux/syscalls.h#L1054-L1058

**Comment by AkihiroSuda** [comment]
Maybe we should add all recent syscalls in a single PR?
- https://github.com/containerd/containerd/pull/6494

**Comment by Xyene** [comment]
Whoops, forgot that they're not multiplexed from one syscall.

Allowing more recent syscalls sounds good to me; I just didn't want to rock the boat too much in this PR.

**Review by justincormack — APPROVED** [review]

**Comment by tianon** [comment]
We need to also verify there aren't any system calls in between these ones' numbers and what's already in the profile, right?
(For the `ENOSYS` vs `EPERM` workarounds/logic)

**Comment by mwhudson** [comment]
thanks @tianon for the ping. I adapted a script I'd written a while ago into this: https://gist.github.com/mwhudson/d28706022141a0cb631328c3a1adad50 (using this handy python packge: https://github.com/hrw/python-syscalls).

Running it on this PR produced this output:

```
(master)mwhudson@anduril:~/src/upstream/moby$ PYTHONPATH=~/src/upstream/python-syscalls/ python3 ~/tmp/diff-seccomp-profiles.py master allow-landlock
REMOVED from the implicit ENOSYS set:
 ['landlock_add_rule', 'landlock_create_ruleset', 'landlock_restrict_self', 'mount_setattr', 'quotactl_fd']
ADDED to the implicit EPERM set:
 ['mount_setattr', 'quotactl_fd']
```

The removal of the landlock_* syscalls from the ENOSYS set is the point. Someone should thing about the mount_setattr and quotactl_fd changes though!

(I think it would be awesome if someone could wrap up this script as a github action that posted to all PRs touching profiles/seccomp/default.json! I don't really know how to do that though)

**Comment by thaJeztah** [comment]
Looks like we have approval on the seccomp changes itself; we can looks at automating the check separately 👍

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
