### PR TITLE
Fix typo in the api remote reference for links

### PR DESCRIPTION
**Pull request by runcom**
/cc @thaJeztah @moxiegirl

Spotted this double **of** (not sure though, I've also fixed where this was needed as well)

Signed-off-by: Antonio Murdaca me@runcom.ninja

### CODE REVIEW

**Comment by thaJeztah** [comment]
Good catch on the double "of". Reading it, I think it should actually be;

> Each link entry should be in the form of "container_name:alias".

**Comment by runcom** [comment]
@thaJeztah I can change what you highlight in this pr or open other to carry that if you are more comfortable

**Comment by thaJeztah** [comment]
Not a native English speaker myself, but I'm fairly sure on this one. If you could update this PR, that would be great. @moxiegirl can check if I was right :)

**Comment by runcom** [comment]
@thaJeztah updated

**Comment by thaJeztah** [comment]
Great! LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
thanks @runcom!

**Pull request merged**
