### PR TITLE
Add intelligent vendor pruning (via "go list")

### PR DESCRIPTION
**Pull request by tianon**
This moves helper functions from `hack/vendor.sh` into the separate `hack/.vendor-helpers.sh` so that `hack/vendor.sh` becomes even more simple and readable, and adds a new `clean` function that prunes anything from `vendor/` that isn't imported within `docker/`, `dockerinit/`, or `test-integration-cli/`.

One caveat is that it uses `go list`'s native `.Deps` for this, which doesn't capture test-only dependencies.  I think we've got those imported outside the tests right now, but if that becomes a problem in the future, it'll be really easy to expand this to check `.TestImports` too (which I only don't do here because it's not recursive like `.Deps` is, so I want to stick to just the simple one for now until/unless we actually have a need to go beyond that).

cc @jfrazelle @icecrime (as my proposed fix for #13756 without any new tools beyond Bash and Go :smile:)

### CODE REVIEW

**Comment by tianon** [comment]
(first commit is the script changes, second is the `vendor/` update)

**Comment by tianon** [comment]
Bahahahaha it fails because we need `html` from `go.net` in the `Dockerfile`, but not anywhere in Docker itself.  Adorbs.

**Comment by tianon** [comment]
53a6327550a4410d63b3d7e11940d2436b347aca to fix the build failure :+1:

**Comment by jfrazelle** [comment]
whoa +110 −39,863

**Comment by jfrazelle** [comment]
:bomb: . com

**Comment by tianon** [comment]
That build fix also has the nice side effect of making `/go` in our container only contain `github.com/docker/docker` and `golang.org/x/tools`, so there's less chance of potential pollution from our `Dockerfile` dependencies (where we really only needed the tools built from those libraries, not their code).

**Comment by icecrime** [comment]
Seriously though why not asking me to change instead of doing something entirely separate... :cry:

**Comment by tianon** [comment]
I wasn't sure it'd even work, but by the time I figured out it would it was
basically done since there's not a lot to it -- sorry :disappointed:.

**Comment by tianon** [comment]
It just seemed so different from adding two separate tools that I
thought it'd be more mean to make you go implement my crazy ideas to
see if they work.

**Comment by thaJeztah** [comment]
Hey! No fights in this repo! :angry: 

image

**Comment by LK4D4** [comment]
Lol, I couldn't even imagine that `go list` can do this.

**Comment by icecrime** [comment]
Right, who would have thought (https://github.com/docker/docker/pull/13756#issuecomment-109332170).

**Comment by tianon** [comment]
I really am sorry and didn't mean to offend :disappointed:.

I'll close this so we can continue with proper review on your PR instead.

**Comment by tiborvass** [comment]
Reopened per https://github.com/docker/docker/pull/13756#issuecomment-111170010

**Comment by tiborvass** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by cpuguy83** [comment]
> I felt a great disturbance in the Force, as if thounsands of lines of unused code suddenly cried out in terror, and were suddenly silenced

**Pull request merged**
