### PR TITLE
typofix - https://github.com/vlajos/misspell_fixer

### PR DESCRIPTION
**Pull request by vlajos**
Signed-off-by: Veres Lajos vlajos@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM thanks again!

**Comment by icecrime** [comment]
Oh my... :smile: Nice one!

**Comment by icecrime** [comment]
LGTM

**Comment by duglin** [comment]
I wonder if this is something we could add to our validation step.

**Comment by thaJeztah** [comment]
@duglin yup, had the same idea, would be nice :-) wondering if it would produce false positives though?

**Comment by vlajos** [comment]
There was a one false positive in the AUTHORS and I had to revert the changes in the vendor folder.
(And I reverted a -halp to -help in the example.go when I sent the PR.. But I think the only reason was my fatigue... At least it seems to be a real typo now...)

**Pull request merged**
