### PR TITLE
Added the naming of container veth's

### PR DESCRIPTION
**Pull request by mattmarich**
If a container name is supplied it names the veth after this, if one is not applied it calls the veth after the auto generated container name. Make's tracking container eths a lot easier if you need to monitor container traffic via devops tools.

### CODE REVIEW

**Comment by jfrazelle** [comment]
im pretty sure @mavenugo has some opinions on veth naming

**Comment by mattmarich** [comment]
Sorry about not signing, first pull request on github. If there's opinions on veth naming feel free to make changes. This worked for my specific application as we needed to add containers to our system graphs and bandwidth limit specific containers to varying speeds.

**Comment by phemmer** [comment]
I think it would be more useful to have the interface name in the `docker inspect` output. We provide the PID of the main process, why not the interface name?
The reason why I might suggest this over naming the interface after the container name is in case one uses container IDs as the primary source of identification. `docker inspect --format '{{.State.InterfaceName}}' $foo` would work if using both IDs & names.

But, there's no reason we can't have both.

**Comment by LK4D4** [comment]
ping @mrjana @mavenugo for design desicion

**Comment by cpuguy83** [comment]
There's no DCO here, so shouldn't be reviewing yet.

**Comment by shishir-a412ed** [comment]
@mattmarich any updates on this one ?

**Comment by icecrime** [comment]
It's been 1 month, the commit is not signed: closing this.

**Comment by mattmarich** [comment]
This was signed soon after there was a complaint. If you see I merged the commits under my github user once I realized I had accidentally pushed as my gitlab user.

**Comment by thaJeztah** [comment]
@mattmarich feel free to open a new PR, we can continue the design discussion there. Any thoughts on the comments so far? I.e., would https://github.com/docker/docker/pull/16729#issuecomment-145259919 work for you?

**Pull request closed without merging**
