### PR TITLE
update containerd binary to v1.5.9

### PR DESCRIPTION
**Pull request by thaJeztah**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by tianon** [comment]
:weary:

```console
=== FAIL: daemon/logger/loggerutils TestFollowLogsHandleDecodeErr (0.02s)
time="2022-01-10T16:10:50Z" level=error msg="Log reader notified that it must re-open log file, some log data may not be streamed to the client." file=/tmp/TestFollowLogsHandleDecodeErr3236554872
    logfile_test.go:317: assertion failed: 5 (int) != 6 (dec.resetCount int)
```

**Comment by thaJeztah** [comment]
Yeah, there's a fix for that one, but not merged yet; https://github.com/moby/moby/pull/43105

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Can we backport this to 20.10?

containerd v1.4 EOL is very soon (February 3, 2022) https://github.com/containerd/containerd/blob/main/RELEASES.md#support-horizon

**Comment by thaJeztah** [comment]
Yeah, we should probably at least have a draft PR to verify it works ok

**Comment by thaJeztah** [comment]
More failures on Windows 2022 with renaming. Not related, but CI is flaky on Windows 😞 

```
`=== FAIL: github.com/docker/docker/integration-cli TestDockerSuite/TestContainerAPIChunkedEncoding (0.12s)
    check_test.go:170: assertion failed: error is not nil: Error response from daemon: container 7819ec9f095a635eeb94806db9cbc767eef82837785085a202548c3e809b93c0: driver "windowsfilter" failed to remove root filesystem: failed to detach VHD: failed to detach virtual disk: The device is not ready.: rename D:\CI\PR-43138\2\daemon\windowsfilter\7819ec9f095a635eeb94806db9cbc767eef82837785085a202548c3e809b93c0 D:\CI\PR-43138\2\daemon\windowsfilter\7819ec9f095a635eeb94806db9cbc767eef82837785085a202548c3e809b93c0-removing: Access is denied.: failed to remove 7819ec9f095a635eeb94806db9cbc767eef82837785085a202548c3e809b93c0
    --- FAIL: TestDockerSuite/TestContainerAPIChunkedEncoding (0.12s)
```

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
