### PR TITLE
Port test from integration tests to integration-cli

### PR DESCRIPTION
**Pull request by brahmaroutu**
Addresses #12255
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
Closing this one since it already exists from #12282

**Comment by brahmaroutu** [comment]
@cpuguy83   This PR is for create command.

**Comment by brahmaroutu** [comment]
Can we re-open, since this is for Create Container.

**Comment by cpuguy83** [comment]
Can we instead add the create step as a sanity check in the `run` test?
I don't like having the almost exact test in two places.

**Comment by brahmaroutu** [comment]
@cpuguy83 It is not a duplication, I believe create and run should be tested separately as they are two different entry points.

**Comment by cpuguy83** [comment]
@brahmaroutu Correct, but it's the same test. I'd prefer to keep this in one spot.

**Comment by cpuguy83** [comment]
What might be good is this... since this test isn't really about testing run/create, it's about making sure the server rejects requests for a container with not enough memory.

So maybe we just move the existing test to a container API test, check by passing in too low memory on create and start API's rather than doing just the CLI (which sends everything on create and nothing on start).

**Comment by brahmaroutu** [comment]
Opened https://github.com/docker/docker/pull/12450 with your suggestion.

**Pull request closed without merging**
