### PR TITLE
Fix loading with containerized plugins

### PR DESCRIPTION
**Pull request by cpuguy83**
During daemon startup, all containers are registered before any are
started.
During container registration it was calling out to initialize volumes.
If the volume uses a plugin that is running in a container, this will
cause the restart of that container to fail since the plugin is not yet
running.
This also slowed down daemon startup since volume initialization was
happening sequentially, which can be slow (and is flat out slow since
initialization would fail but take 8 seconds for each volume to do it).

This fix holds off on volume initialization until after containers are
restarted and does the initialization in parallel.

The containers that are restarted will have thier volumes initialized
because they are being started. If any of these containers are using a
plugin they will just keep retrying to reach the plugin (up to the
timeout, which is 8seconds) until the container with the plugin is up
and running.

### CODE REVIEW

**Comment by thaJeztah** [comment]
```
 ---> Making bundle: validate-vet (in bundles/1.10.0-dev/validate-vet)
17:18:55 daemon/daemon.go:416: range variable c captured by fund literal
```

**Comment by cpuguy83** [comment]
All fixed

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
Added changelog; could be a good improvement for people that ran into this in 1.9

**Pull request merged**
