### PR TITLE
Revert "Block obsolete socket families in the default seccomp profile"

### PR DESCRIPTION
**Pull request by justincormack**
This reverts commit 7e3a596a63fd8d0ab958132901b6ded81f8b44c0.

Unfortunately, it was pointed out in https://github.com/moby/moby/pull/29076#commitcomment-21831387
that the `socketcall` syscall takes a pointer to a struct so it is not possible to
use seccomp profiles to filter it. This means these cannot be blocked as you can
use `socketcall` to call them regardless, as we currently allow 32 bit syscalls.

Users who wish to block these should use a seccomp profile that blocks all
32 bit syscalls and then just block the non socketcall versions.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

heron

### CODE REVIEW

**Comment by thaJeztah** [comment]
Should we add an example to the docs to show how to block these using a custom profile?

**Comment by justincormack** [comment]
@thaJeztah I guess we could. Its just a pity seccomp profiles are so long that examples are a bit annoying...

**Review by mlaventure — APPROVED** [review]
LGTM

The doc can come in a follow up ;-)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@justincormack @mstanleyjones looks like this needs a change in the docs here as well; https://github.com/docker/docker.github.io/pull/776

**Pull request merged**
