### PR TITLE
fix git checkout command in setting up dev env

### PR DESCRIPTION
**Pull request by ghost**
Spoke with one of the mentors at Docker's 2nd Birthday Party at Mountain View and he confirmed that you should be checking out a new branch with that name.

I originally thought that there was a branch by that name :confused:

### CODE REVIEW

**Comment by moxiegirl** [comment]
The -b flag creates the branch and checks it out. At this point in the guide, you were supposed to have **already** created the branch in the previous page: http://docs.docker.com/project/set-up-git/  

So issuing the command at this  point, assuming you had followed set-up-git, you would receive an error:

$ git checkout -b dry-run-test
fatal: A branch named 'dry-run-test' already exists.

So, rather than tell them to do something that will report an error if they are following the guide. I give the them the correct command --- which checks out an **existing** branch.

**Comment by moxiegirl** [comment]
If you want to suggest a work around for the situation I described, feel free. For example, you must have gotten this error at this point:

git checkout dry-run-test
error: pathspec 'dry-run-test' did not match any file(s) known to git.

**Comment by khoomeister** [comment]
Whoopsies :smiley: sorry bout hat!

**Comment by moxiegirl** [comment]
Hey no worries...it happens.  Have fun out there!

**Pull request closed without merging**
