### PR TITLE
Proposal: use a bot to check PRs & help maintainer

### PR DESCRIPTION
**Pull request by endersonmaia**
## Problem

Docker is getting bigger, and the number os PRs just grows and a lot of PRs are not following the contributing guidelines. The talk inside a PR can help solve the problems of the PR itself, but a lot of energy is lost talking about the PR adherence problems, when maintainers should be talking about the problem that PRs is trying to solve.
## Types of checks

Bellow is a list of types of checks a bot could make on every new PR or changes to the PR commits.
- Branching name convention for bug/feature branches;
- PR's title length and prefix;
- Check commit's changed files, and ping maintainers based on subsystem X maintainers;
- Asks/suggest tagging for better issue triage;
- Check if commits are signed;
## Talking to the bot

Bellow is a list of commands the bot could get from maintainers.
- Listens to LGTM from subsystem maintainers and check if it has the majority, and auto-merge if it applies;
- Accept release commands from release maintainers;

---

I'd like to focus on defining what more (or fewer) command and checks this bot cold have, before detailing the behavior of each command and check on the docs.

I'm in doubt if /CONTRIBUTING.md is the best place for it, or if it should be /MAINTAINERS or even another file.

When you (project maitainers ?) think we have enough commands and checks, alert here, so I can think in working on the bot implementation.

Suggestions about implementation are welcome!

Signed-off-by: Enderson Maia endersonmaia@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
if you would like you should contribute to github.com/jfrazelle/gh-patch-parser, its a bot we are currently using ;)

**Comment by thaJeztah** [comment]
Just FYI, docker already uses a bot to check if PRs are signed-off properly and automatically labels PRs (see this proposal has been automatically tagged "proposal" and "docs-only").

Source can be found here; https://github.com/jfrazelle/gh-patch-parser

**Comment by jfrazelle** [comment]
it currently does 
- Check if commits are signed.
- labels

**Comment by endersonmaia** [comment]
I suspected there was a bot just now, with that fast reply from @jfrazelle with tagging!

I didn't find nothing in the docs about it.

**Comment by jfrazelle** [comment]
its a WIP as of now

**Comment by cpuguy83** [comment]
And there's also github.com/docker/gordon

**Comment by jfrazelle** [comment]
Hey @endersonmaia we love he intention here :) we are currently working on opening a new repository for all of our infrastructure. The bot would be included in that as well as a few other cool tools so people can contribute in making these things even more awesome. So I am going to close this for now, but we welcome you to help us with our tools in any way :) hope you can understand.

**Pull request closed without merging**
