### PR TITLE
`docker version` supports `--json` and returns version info in JSON

### PR DESCRIPTION
**Pull request by kevinjqiu**
**\- What I did**
Make `docker version` accept `--json` flag and when specified, returns the version information in JSON.

**\- How I did it**
Add a `json` flag in `api/client/version.go` and use `encoding/json.Marshal` to output the version response in JSON format.

**\- How to verify it**
- Build the binaries
- run `docker version --json` or `docker version -j`

**\- A picture of a cute animal (not mandatory but encouraged)**

qzmn9ogm

### CODE REVIEW

**Comment by justincormack** [comment]
Sorry, what is the use case for this and why is the currently documented `docker version --format '{{json .}}'` not sufficient?

**Comment by thaJeztah** [comment]
Hm, yeah, I also don't see what this adds; could you explain why this is needed @kevinjqiu ?

**Comment by kevinjqiu** [comment]
@thaJeztah @justincormack Fair enough. I did not know the `{{json .}}` template format.

**Comment by thaJeztah** [comment]
No problem; thanks for contributing!

Perhaps a "prettyjson" option for `--format` would be a nice addition (perhaps it's already possible somehow, don't know)

**Pull request closed without merging**
