### PR TITLE
Bump v1.10.1

### PR DESCRIPTION
**Pull request by tiborvass**

### CODE REVIEW

**Comment by tiborvass** [comment]
@GordonTheTurtle why do you hate me during a release?? I want to talk to your manager.

**Comment by tiborvass** [comment]
We have just pushed 1.10.1-rc1 to https://test.docker.com. You can download it with the following:

deb/rpm packages: `curl -fsSL https://test.docker.com/ | sh`

Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.10.1-rc1
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.10.1-rc1
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.10.1-rc1.tgz
Windows 64bit client binary: https://test.docker.com/builds/Windows/x86_64/docker-1.10.1-rc1.exe
Windows 32bit client binary: https://test.docker.com/builds/Windows/i386/docker-1.10.1-rc1.exe

**Comment by tiborvass** [comment]
Windows failure is expected, Experimental failure is unexpected but we don't care about experimental since this is a release.

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Pull request merged**
