### PR TITLE
Dockerfile: apt-get update once and for all

### PR DESCRIPTION
**Pull request by kolyshkin**
Many stages derived from base (6 out of 13 to be precise, one
being a mistake) run apt-get update, which takes 15s in my env.

Let's do it once, in the base-apt image.

In case buildkit is not enabled (i.e. sequential build), it
should save about a minute of time.

In case buildkit is enabled, stages that do not use apt-get
will be started faster.

In both cases, it will save some CPU time, I/O, and network
traffic.

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
This does not work well with cache

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Agree with @akihirosuda - It's best practice to combine `apt get update` with `apt get install`. Doing so forces a cache bust of the apt cache when changing (adding/removing) a package from the list.

If `apt get update` is in its own `RUN`, that cache would never be busted, causing an outdated index to be used.

**Comment by thaJeztah** [comment]
Closing this one per the above 🤗

**Comment by kolyshkin** [comment]
Hmm, can we make it work with cache? Say by adding an intermediate image and a `COPY --from`  statement?

**Comment by kolyshkin** [comment]
My idea was to do apt-get update twice -- once in the base-apt and then one more time right before `apt-get install`. The subsequent run is about twice faster, but the overall time increases (for the first run), so it's probably not worth it.

Keeping this one closed.

**Comment by thaJeztah** [comment]
Yeah, the problem with that is that, e.g. in the following simplified example:

```Dockerfile
FROM foo
RUN apt-get update
RUN apt-get install \
  package1 \
  package2


RUN apt-get update
RUN apt-get install \
  packageA \
  packageB
```


- Adding `package3` to the first `apt-get install` won't bust the cache for the `apt-get update` (so you'd possibly be adding an outdated package)
- Similarly, adding `packageC` to the second `apt-get install` won't bust the cache for the `apt-get update` (so you'd possibly be adding an outdated package)
- But... adding `package3` _will_ bust the cache for the _second_ `apt-get install`, so _will_ potentially update packages `packageA` and `packageB`.

Whereas;

```Dockerfile
FROM foo
RUN apt-get update && apt-get install \
  package1 \
  package2


RUN apt-get update && apt-get install \
  packageA \
  packageB
```

Will bust the cache whenever there's a change made to either of those lists of packages; forcing `apt-get update` to be re-run as well (so being sure that the packages are not outdated).

**Pull request closed without merging**
