### PR TITLE
[1.13.x] swagger cherry-picks

### PR DESCRIPTION
**Pull request by thaJeztah**
This cherry picks the following PR's / commits;

https://github.com/docker/docker/pull/26576 (a58b5830b175860e71174c93c6f3ec1cefcd5e0d)
https://github.com/docker/docker/pull/29808 (86f962a4a81d9168fccb6a92299e88e560de49f1)
https://github.com/docker/docker/pull/29906 (dea528e8cd044de6ca08f7c9bb2e7581774743d6)
https://github.com/docker/docker/pull/30701 (0113128b2a79a9cef9950e71e0681380b240faf4)
https://github.com/docker/docker/pull/30702 (da1f05d66de409294e535fbefb968ce040248e3e)
https://github.com/docker/docker/pull/30734 (f3da980a459c11a35248daa8a6be9919bf65fda2)
https://github.com/docker/docker/pull/30952 (0464441fb152564f90340d4806b77ca7821aa1ef)

I tried to cherry-pick 17f9f5abf4cdf72ce6b5f8f2f69e5a872c6a3b56 from  https://github.com/docker/docker/pull/28409, but it didn't apply easily, so decided to skip that for now. We may want to do a separate PR for that, or take whole of https://github.com/docker/docker/pull/28409 (/cc @dnephin)

ping @stevvooe as well for the changes in status code 😅 

(note that https://github.com/docker/docker/pull/26576 was labeled as cherry-picked, but apparently was missed, and not actually cherry-picked into 1.13.x)

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
LGTM

**Comment by thaJeztah** [comment]
build is failing, looks like another cherry pick is needed, looking

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
Windows failure (`DockerSuite.TestBuildLastModified`) is unrelated

**Pull request merged**
