### PR TITLE
Delete duplicate words

### PR DESCRIPTION
**Pull request by xichengliudui**
Signed-off-by: xichengliudui <1693291525@qq.com>

**- What I did**
Delete duplicate words

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

IMG_0050

### CODE REVIEW

**Comment by tianon** [comment]
Definitely LGTM 👍

**Comment by xichengliudui** [comment]
May I ask how do I solve the DCO sign-off?

**Comment by tianon** [comment]
You need to amend and force push your commit, just as the bot pointed out (and described) above: https://github.com/moby/moby/pull/38860#issuecomment-472329555

**Comment by xichengliudui** [comment]
@tianon modified

**Review by tianon — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
