### PR TITLE
Clear Containers for Docker Engine

### PR DESCRIPTION
**Pull request by xnox**
This is initial release of Clear Containers execution driver for Docker Engine.

It is available today, as default, on clearlinux.org however we are also preparing binary distribution for common distributions.

Most of the changes are contained in the clr execution driver, however a few additional details had to be made public - specifically options relating to the network bridge the execution driver should connect to, and addition of the tuntap device support in libnetwork, and up the stack to daemon/execdriver.

This makes clear containers driver the default, and when this execution driver is enabled, the default network driver is flipped to tuntap, as that's the only one that is currently supported by this execution driver. If incompatible network is used, the container will fail to start.

In addition to this code, one also needs compatible kvmtool & vmlinux.container image on the host. All three are in progress to be compiled and made available for download for multiple common distributions.

This is more of an RFC - comments and reviews would be highly appreciated.

### CODE REVIEW

**Comment by xnox** [comment]
Pushing older code, without tuntap libnetwork driver as it is actually very broken still. The code now, does very strange thing (a) delete created veth pair (b) create tap interface it its place (c) mimic/pretend to be the previous veth pair. Architecturally, I think execdriver should be passing endpointoption all the way back to the exec driver to e.g. specify interfacetype and get a tap interface created instead of a veth pair. That should be clean, and logical. Please advice, i'll try to work on that now.

**Comment by calavera** [comment]
If I'm correct, we decided to not accept more execution drivers that are not provided by runC/libcontainer.  All the execution driver logic is going to be replaced in the future by runC and we don't want other dependencies to stop that from happening.

/cc @crosbymichael

**Comment by icecrime** [comment]
@calavera Indeed, but we had discussions with the Clear Containers team from Intel and both agreed that the PR was worth submitting for educational and testing purpose. You are however right that, with their agreement, this will **not be merged**.

**Comment by jfrazelle** [comment]
hi sorry seeing as this is not going to be merged and i am trying to clean up the repo I am going to close but thank you!!

**Comment by xnox** [comment]
We now have OCI compatible binary, where is the docker code that calls out to OCI binaries instead of using execution drivers? As we are ready to be merged with that implementation of docker. And in addition to that, we still want to have an exec-driver merged, whilst the exec-driver based docker is the stable/production version in operation.

**Pull request closed without merging**
