### PR TITLE
Update seccomp.md

### PR DESCRIPTION
**Pull request by sjiveson**
Please provide the following information:
- What did you do? Edited, corrected and updated the seccomp.md file. "Corrected titles to use title case. Added link to default.json and some numerical detail. Changed example JSON to a portion of the actual default file, with the correct defaultAction."
- How did you do it? Manually, online.
- How do I see it or verify it? Perform/view a diff.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Can you sign off your commit using the instructions above?

Also, our style guide describes that we use sentence capitalization in our headings, so if you can stick to that https://docs.docker.com/opensource/doc-style/#capitalization :+1:

**Comment by itsthenetwork** [comment]
Apologies gents. Both mistakes now corrected.

**Comment by thaJeztah** [comment]
Did you stage your changes? Looks like the headings are still updated :smile:

**Comment by itsthenetwork** [comment]
Aargg. Apologies again, now fixed.

**Comment by thaJeztah** [comment]
hehe, no worries :-)

LGTM

**Comment by calavera** [comment]
LGTM

**Pull request merged**
