### PR TITLE
profiles: seccomp: update to Linux 5.11 syscall list

### PR DESCRIPTION
**Pull request by cyphar**
These syscalls (some of which have been in Linux for a while but were
missing from the profile) fall into a few buckets:

 * close_range(2), epoll_wait2(2) are just extensions of existing "safe
   for everyone" syscalls.

 * The mountv2 API syscalls (fs*(2), move_mount(2), open_tree(2)) are
   all equivalent to aspects of mount(2) and thus go into the
   CAP_SYS_ADMIN category.

 * process_madvise(2) is similar to the other process_*(2) syscalls and
   thus goes in the CAP_SYS_PTRACE category.

belly-cat

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cyphar** [comment]
I just noticed some other syscalls were missing (all of the v2 mount API syscalls, and `close_range`) so I've added those too.

**Review by AkihiroSuda — APPROVED** [review]

**Review by justincormack — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]

**Comment by thaJeztah** [comment]
opened https://github.com/containerd/containerd/pull/4957 to make the same changes in the containerd seccomp profile

**Comment by cyphar** [comment]
I can't reproduce the test failure locally -- it might be a flaky test?

**Comment by thaJeztah** [comment]
> I can't reproduce the test failure locally -- it might be a flaky test?

Yes, there's some oddness currently with the s390x and ppc64le nodes. s390x looks to be https://github.com/moby/moby/issues/41933, for ppc64le, and I'm hoping https://github.com/moby/moby/pull/41932 will improve ppc64le (or at least gives us more useful errors).

Sorry this is taking long to get merged; while those failures are not related, I'd love to see CI pass for those architectures, just in case there's some issue with seccomp on them, so I've been kicking CI many times.

Thanks for rebasing the PR, I was considering doing a rebase, to see if it helped (but didn't want to push to your branch); I'll check if the s390x issue was fixed, and continue trying 🤞 (might give you a ping to do a rebase after https://github.com/moby/moby/pull/41932 is merged)

**Comment by cyphar** [comment]
I mean there was a non s390x/ppc64le failure (`TestLogsFollowSlowStdoutConsumer`) which I cannot reproduce locally. But it appears to have gone away after the rebase (so it was probably just flaky).

**Comment by AkihiroSuda** [comment]
Tests are passing on amd64. Merging. https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41889/18/

**Pull request merged**
