### PR TITLE
integration-cli: fix TestAttachDetach, rm TestAttachDetachTruncatedID

### PR DESCRIPTION
**Pull request by kolyshkin**
_(this is a continuation of https://github.com/moby/moby/pull/37711)_

It looks like the logic of the test became wrong after commit ae0883c (PR #12292).

The original logic was:
* (a few first steps skipped for clarity)
* send escape sequence to "attach";
* check "attach" is exiting (i.e. escape sequence works);
* check the container is still alive;
* kill the container.

Also, timeouts were big at that time, in the order of seconds.

The logic after the above mentioned commit and until now is:
* ...
* send escape sequence to "attach";
* check the container is running (why shouldn't it?);
* kill the container;
* checks that the "attach" has exited.

So, from the "let's check detach using escape sequence is working"
the test became something like "let's check that attach is gone
once we kill the container".

Let's fix the above test, also increasing the timeout waiting
for attach to exit (which fails from time to time on power CI).

Now, the second test, TestAttachDetachTruncatedID, does the exact
same thing, except it uses a truncated container ID. It does not
seem to be of much value, so let's remove it.

### CODE REVIEW

**Comment by kolyshkin** [comment]
@arm64b PTAL

**Review by arm64b — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
