### PR TITLE
pkg/mount/TestMount: fix wrt selinux

### PR DESCRIPTION
**Pull request by kolyshkin**
Sometimes docker-master CI fails on rhel4+selinux configuration, like this:

```
--- FAIL: TestMount (0.12s)
    --- FAIL: TestMount/none-remount,size=128k (0.01s)
    	mounter_linux_test.go:209: unexpected mount option "seclabel" expected "rw,size=128k"
    --- FAIL: TestMount/none-remount,ro,size=128k (0.01s)
    	mounter_linux_test.go:209: unexpected mount option "seclabel" expected "ro,size=128k"
```

Earlier, commit 8bebd42df2 (PR #34965) fixed this failure, but not entirely (i.e. the test is now flaky). It looks like selinux detection code is not always working.

As the subject of this test case is definitely not selinux, it can just ignore the option added by it.

While at it, fix error messages -- add missing commas, fix a typo, and allow for clear distinction between mount and vfs (per-superblock) options.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Do we know what makes selinux detection flaky? I agree we can ignore that option, but curious why we fail to properly detect selinux

**Comment by tonistiigi** [comment]
alternative #36740

**Comment by kolyshkin** [comment]
> Do we know what makes selinux detection flaky?

Most probably dind (selinux is detected by checking /sys/fs/selinux mount point which is not there by default). That does not explain flakiness though.

**Comment by kolyshkin** [comment]
closing this one in favor of #36740; will create a new one to fix error messages on top of #36740

**Comment by tonistiigi** [comment]
The flakiness is likely from new rhel nodes in CI. I never saw it fail on old nodes and never seen it pass on new ones. 

The difference between this and #36740 is that  #36740 still requires seclabel when selinuxfs is mounted.

**Comment by kolyshkin** [comment]
Reopening; I think this test should not check for seclabel at all

**Comment by kolyshkin** [comment]
A different failure on experimental now:
```
00:49:31 === RUN   TestServicePlugin
00:50:30 --- FAIL: TestServicePlugin (59.53s)
00:50:30 	daemon.go:285: [d1e7868f8b0ee] waiting for daemon to start
00:50:30 	daemon.go:317: [d1e7868f8b0ee] daemon started
00:50:30 	daemon.go:275: [d1e7868f8b0ee] exiting daemon
00:50:30 	daemon.go:285: [d828dcf4073c4] waiting for daemon to start
00:50:30 	daemon.go:317: [d828dcf4073c4] daemon started
00:50:30 	daemon.go:285: [d409f87ad25cc] waiting for daemon to start
00:50:30 	daemon.go:317: [d409f87ad25cc] daemon started
00:50:30 	daemon.go:285: [d3b90e73c9588] waiting for daemon to start
00:50:30 	daemon.go:317: [d3b90e73c9588] daemon started
00:50:30 	plugin_test.go:92: timeout hit after 30s: plugin "test" exists
00:50:30 	daemon.go:275: [d3b90e73c9588] exiting daemon
00:50:30 	daemon.go:275: [d409f87ad25cc] exiting daemon
00:50:30 	daemon.go:275: [d828dcf4073c4] exiting daemon
00:50:30 FAIL
```

haven't seen it before.

Rebased.

**Comment by thaJeztah** [comment]
I think I've seen `TestServicePlugin` fail a couple of times; https://github.com/moby/moby/search?q=TestServicePlugin&type=Issues, but looks like we didn't open an issue for it. t.b.h. all those failures seem to relate to "timeouts"; could be a common cause (actual issue) somewhere.

https://github.com/moby/moby/pull/37086 was actually increasing the timeout for swarm tests to address the flakiness, but that was removed in favor of changing the timeout on a test-by-test base (https://github.com/moby/moby/pull/37086#discussion_r189062007)

Opened https://github.com/moby/moby/issues/37132 for the flaky test

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
