### PR TITLE
Generate distribution-specific Dockerfile

### PR DESCRIPTION
**Pull request by sallyom**
This PR will generate a Dockerfile specific to a distribution (RHEL, Centos and Fedora with this change but provides a pattern to follow for other distributions).  This will allow distro-specific Dockerfile to be used in build for 'make test'.  It reads from /etc/redhat-release and generates a new Dockerfile for that distribution.

Signed-off-by: Sally O'Malley somalley@redhat.com

Docker-DCO-1.1-Signed-off-by: Regan McCooey rmccooey27@aol.com (github:
rhatdan)

### CODE REVIEW

**Comment by sallyom** [comment]
I am an intern working with @rhatdan

**Comment by thaJeztah** [comment]
ping @tianon for generated Dockerfiles :)

**Comment by tianon** [comment]
This is a duplicate of #10990, of which https://github.com/docker/docker/pull/10990#issuecomment-97913262 summarizes where this initiative is currently at.

**Comment by thaJeztah** [comment]
Thanks, @tianon

**Comment by rhatdan** [comment]
@tianon I don't see the relationship between the two pulls, this one is just trying to allow alternate test docker images based on the host that you are running the test on.  The one you referred to is about changing the way you build docker images.

**Comment by sallyom** [comment]
Any word on this?

**Comment by calavera** [comment]
@jfrazelle what do you think?

**Comment by jfrazelle** [comment]
i believe #10990 was closed and being worked on in a way we all agreed upon so i too believe this is a dup

**Comment by rhatdan** [comment]
So we are closing this pull request based on a closed pull request?  I don't really see where https://github.com/docker/docker/pull/10990 addresses this issue?  We just want testing of docker to happen specific to the host OS that you are running the test on.

**Pull request closed without merging**
