### PR TITLE
Add Jess to alumni

### PR DESCRIPTION
**Pull request by thaJeztah**
Because this was still missing :heart:

ping @docker/core-engine-maintainers @jfrazelle

### CODE REVIEW

**Comment by runcom** [comment]
sadly LGTM :cry:

**Comment by icecrime** [comment]
LGTM :crying_cat_face:

**Comment by estesp** [comment]
thanks @thaJeztah! :heart:

LGTM

**Comment by tianon** [comment]
LGTM :heart:

**Comment by vdemeester** [comment]
LGTM 💓

**Comment by jfrazelle** [comment]
Thanks <3

On Tue, May 10, 2016 at 11:34 AM, Vincent Demeester <
notifications@github.com> wrote:

> LGTM 💓
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/22634#issuecomment-218248705>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
Thank *you*, Jess

**Pull request merged**
