### PR TITLE
docs: fix description of `filters` param for /volumes and /networks.

### PR DESCRIPTION
**Pull request by gesellix**
see #17091

Signed-off-by: Tobias Gesellchen tobias@gesellix.de

### CODE REVIEW

**Comment by vdemeester** [comment]
Added 1.9.0 milestone as the related issue is on it too.
@gesellix could you edit the content of your PR to add "Fixes #17091" so that once merged, the issue is closed automagically :wink:

**Comment by gesellix** [comment]
@vdemeester I did already :-)

**Comment by vdemeester** [comment]
@gesellix oh in the commit message, didn't see it :sweat_smile:. Good then, nvm :+1:

**Comment by thaJeztah** [comment]
Good catch! LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
