### PR TITLE
Remove duplicated words in pkg files

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: mooncake <xcoder@tenxcloud.com>

**- What I did**
Remove duplicated words in pkg files

**- How I did it**
Remove duplicated words in pkg files:
1. pkg/fileutils/fileutils.go
2. pkg/plugins/plugins.go
3. pkg/streamformatter/streamformatter.go

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :frog: 
@mooncak `moby/moby` do not have `prow` like abilities (so `/assign`, `/retest` won't have any effect :stuck_out_tongue_closed_eyes:)

**Comment by thaJeztah** [comment]
Whoops, too late, as it was merged already; @mooncak for future contributions, could you [use your real name](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work) ("Billy Zhang") in your sign-offs, instead of your "mooncake" GitHub Handle?

```
Signed-off-by: mooncake <xcoder@tenxcloud.com>
```

**Pull request merged**
