### PR TITLE
add send, recv, and x32 so we can install i386 pkgs on amd64

### PR DESCRIPTION
**Pull request by jessfraz**
makes sure this works:

```
docker run --rm -it debian:jessie bash
# dpkg --add-architecture i386
# apt-get update && apt-get install curl:i386
# curl -sSL ifconfig.co

before patch
curl: (55) Send failure: Operation not permitted

after patch
WORKS!
```

### CODE REVIEW

**Comment by justincormack** [comment]
Ah send, recv: have checked the other socketcalls again, these are not present on x86_64, but they are present as socketcalls on x86, but probably werent being used as they are legacy. I can't see anything else in that situation.

Congratulations on trying x32, Linux's least useful architecture.

LGTM.

**Comment by unclejack** [comment]
@jfrazelle Last time I've looked, we were able to cross-compile binaries for i386. Would you like to add an integration-cli test which tries to run a i386 binary on amd64?

**Comment by justincormack** [comment]
@unclejack to be fair, almost all i386 binaries did run before this change, just not Debian's version of curl, so that would not have caught this. I am looking at further tests for seccomp changes for the next release. Not that having a test would do any harm.

**Comment by cpuguy83** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
