### PR TITLE
Allow one character repository names

### LINKED ISSUE #14485: [master]: cannot pull docker image where repo name is 1 letter
```
Unable to find image 'jess/t:latest' locally
repository name component must be 2 or more characters
```

NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

### PR DESCRIPTION
**Pull request by stevvooe**
Closes  #14485

cc @dmcgowan @jfrazelle @tiborvass

### CODE REVIEW

**Comment by estesp** [comment]
Are there any infrastructure remnants (private or public) where this would cause a problem once 1.8 is out and people connect to various repos of various flavors?  The code looks simple and straightforward enough..

**Comment by jfrazelle** [comment]
LGTMMMMMMM

**Comment by jfrazelle** [comment]
I need dis

**Comment by jfrazelle** [comment]
@estesp this was only on master

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
@estesp @stevvooe the restriction on the length on the Hub account name should still be enforced, but that's a Hub thing.

**Pull request merged**
