### PR TITLE
log: Add restart policy name to the inspect information of container

### PR DESCRIPTION
**Pull request by HuKeping**
Under the restart policy "--restart=no", there is no record about it
in the information from docker inspect.

To keep it consistent around the three(maybe more in the future) restart
policies and distinguish with no restart policy specified cases, it's
worth to record it even though it is the default restart policy which
will not restart the container.
## Example

case 1: no restart policy
"RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },

case 2:--restart=on-failure:2
"RestartPolicy": {
            "MaximumRetryCount": 2,
            "Name": "on-failure"
        }

case3:--restart=always
"RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },

case4:--restart=no
"RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },

### CODE REVIEW

**Comment by HuKeping** [comment]
case 1: no restart policy
"RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },

case 2:--restart=on-failure
"RestartPolicy": {
            "MaximumRetryCount": 2,
            "Name": "on-failure"
        }

case3:--restart=always
"RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },

case4:--restart=no
"RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },

**Comment by thaJeztah** [comment]
I think the new output should be added to the API docs as well: https://github.com/docker/docker/blob/master/docs/sources/reference/api/docker_remote_api_v1.17.md#inspect-a-container

Reading that, I noticed that `RestartPolicy` is completely missing in the example outputs in docs? Unless I overlooked them, older versions of the API docs should be updated as well to show what the output *before* this change looked like.

Restart policies were added in docker 1.2.0, But `HostConfig` wasn't included in the output until API 1.8, So docs for API version 1.8 and up should probably be changed to include restart policy

/cc @SvenDowideit (I think)?

**Comment by HuKeping** [comment]
nice catch @thaJeztah , i also find that the inspect info in docs is quite different with what i actually get from `docker inspect <container_id>`, @SvenDowideit is this needs to be fixed?

**Comment by thaJeztah** [comment]
Thanks @HuKeping I don't know If the *entire* output has to be update as part of *this* PR, but it should be okay for now so that it can be discussed :)

Also note that the example in the docs is the response of the remote API (not the CLI); don't know if there's a difference in the output (haven't checked)

**Comment by HuKeping** [comment]
hi @thaJeztah, i got the output  from the response body which i think may have not been manipulated by CLI yet.

```
resp, err := cli.HTTPClient().Do(req)
body, err := ioutil.ReadAll(resp.Body)
```

**Comment by thaJeztah** [comment]
Great! Thanks for confirming.

**Comment by crosbymichael** [comment]
Can you redo this PR only containing the commit cc47e948fc57f12523965fc2b68fb65c7deae96d ? 

Also, please rebase this commit on master and not merge upstream changes into your branch.

**Comment by HuKeping** [comment]
Thanks @crosbymichael  and already fixed it :)

**Comment by LK4D4** [comment]
@HuKeping cool! could you add integration-cli tests for this?

**Comment by HuKeping** [comment]
@LK4D4 OK

**Comment by LK4D4** [comment]
@HuKeping Thank you!

**Comment by crosbymichael** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
^ once test is added

**Comment by HuKeping** [comment]
yes,,,i'm working on it , a little slow

**Comment by jfrazelle** [comment]
take your time :)

**Comment by SvenDowideit** [comment]
I'm assuming that the added verbosity for the API response on default will have a tiny entry in the 1.17 API doc (and thus won't be identical to the 1.16 API)

**Comment by HuKeping** [comment]
Updated to add a test for policy --restart=no

**Comment by HuKeping** [comment]
any other things need to do?

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
