### PR TITLE
Docs: update docs for API stats

### PR DESCRIPTION
**Pull request by HuKeping**
As @twhiteman mentioned https://github.com/docker/docker/pull/15786#issuecomment-149292205

Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, good catch!

**Comment by thaJeztah** [comment]
ping @moxiegirl @SvenDowideit

**Comment by moxiegirl** [comment]
LGTM thank you @HuKeping

**Comment by moxiegirl** [comment]
cp please

**Pull request merged**
