### PR TITLE
Remove duplicated code parsing parameters for the archiving handlers.

### PR DESCRIPTION
**Pull request by calavera**
/cc @jlhawn

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@calavera compile error :)

**Comment by calavera** [comment]
it should be fixed now, thanks!

**Comment by jlhawn** [comment]
nice! LGTM after janky passes.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
