### PR TITLE
Service logs formatting

### PR DESCRIPTION
**Pull request by dperny**
This PR updates #29197 to address the concerns with that PR. 

- Removed the `--details` flag which isn't supported in the swarmkit API at this time. It may return later.
- Fixed a possible issue with setting the `padding` variable on recommendation of @aaronlehmann. 
- Declined to implement a go template formatter. It's a lot of work and too much control; it may return later.
- Changed `no-ids` to `no-task-ids`

Does this look good @aaronlehmann @cpuguy83 @vdemeester ?
/cc @aluzzardi

### CODE REVIEW

**Comment by dperny** [comment]
This PR supersedes #29197 and that PR can be closed.

**Comment by dperny** [comment]
I don't believe the test failure is my fault.

**Comment by aluzzardi** [comment]
Tentatively targeting 17.04.0

**Review by vdemeester — APPROVED** [review]
LGTM 🦁
Experimental failure is a flaky test yeah 😓

**Comment by aluzzardi** [comment]
@cpuguy83 any feedback?

**Comment by aluzzardi** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Damnit, hit the wrong button, no confirmations or anything...
@dperny You can just remove the last commit.

**Comment by cpuguy83** [comment]
Ok, I fixed it.

**Pull request merged**
