### PR TITLE
return status code http.StatusNoContent in deleting network when OK

### LINKED ISSUE #20976: API: DELETE network/:id should return a response with code StatusNoContent if successful
Hi, all,

Today, I found that when I deleted a network from docker daemon via API,  API returned a response with status code 200 if successful. And I think it is better to return 204 (no content). 
While I search other delete apis, below is the result.
```
204: DELETE volumes;
204: DELETE containers; 
200: DELETE networks;
200: DELETE images;
```

[https://github.com/docker/docker/blob/master/api/server/router/network/network_routes.go#L149-L151](https://github.com/docker/docker/blob/master/api/server/router/network/network_routes.go#L149-L151)

while `DELETE images` returns a list, so 200 not 204 seems reasonable.

And `DELETE networks` should return 204 , i think.

### PR DESCRIPTION
**Pull request by allencloud**
1.return status code http.StatusNoContent in deleting network when successful
2.modify docker_api_network_test.go

fixes #20976

### CODE REVIEW

**Comment by cpuguy83** [comment]
This would need an update to the API docs.

ping @mavenugo

**Comment by allencloud** [comment]
@cpuguy83 
I made a little change to the docker_remote_api_v1.23.md.

**Comment by allencloud** [comment]
@cpuguy83 
I made some change in api v1.23. However , for now with docker 1.10.2 docker api version is v1.22. Do I need to modify docker_remote_api_v1.22.md?

And may I ask the relationship of docker api version and docker version? 
Or is there some place to find details with this information about relationship?

**Comment by cpuguy83** [comment]
No need to modify the API for the current released version since we will not change that.

There's a chart in the docs relating API version to release version.

**Comment by calavera** [comment]
LGTM

**Comment by mavenugo** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
