### PR TITLE
adding ability to copy just a file from container to host

### PR DESCRIPTION
**Pull request by brahmaroutu**
Addresses #4272

Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by jlhawn** [comment]
Here's a summary of the current work I have at the [other PR](https://github.com/docker/docker/pull/9871) with general improvements to `docker cp`:

# Improve `docker cp`

This command currently uses the following HTTP API endpoint:

	POST /containers/(id)/copy

This endpoint only supports copying files/directories from a container to the
client. Its behavior is also odd in that `DEST` is always treated as a
directory. It would be preferrable to have the same behavior as standard Unix
utilities like `cp` and `scp`.

## New API Endpoints

This endpoint may be split into two separate API endpoints to handle copying
files or directories to and from a container:

	GET /containers/(id)/copy?path=/container/path

This endpoint has similar behavior to the current `copy` endpoint and is used
to copy data from the container to the client. The difference is that it will
correctly handle the case when the source is a file or is a directory and ends
with a trailing path separator, including the directory or only its contents.

	PUT /containers/(id)/copy?srcPath=/local/path&dstPath=/container/path

This endpoint may be used for copying data from the client to a destination
path inside a container.

Use of these 2 endpoints together would allow for a client to copy files or
directories from one container to another, but this would require transfering
an archive through the client. For this purpose, a 3rd endpoint can be used:

	PUT /containers/(id)/copy-across?dstContainer=id&srcPath=/path1&dstPath=/path2

Any container paths which are not absolute are considered relative to the
container's working directory.

## CLI Usage

### copy from a container to the client

	docker cp CONTAINER:PATH LOCALPATH

Copies a file or directory at PATH in the specified `CONTAINER` to a
`LOCALPATH` on the client.

### copy from the client to a container

    docker cp LOCALPATH CONTAINER:PATH

Copies a file or directory at `LOCALPATH` to `PATH` in the specified
`CONTAINER`.

### copy from one container to another

    docker cp SRC_CONTAINER:SRC_PATH DST_CONTAINER:DST_PATH

Copies a file or directory at `SRC_PATH` in `SRC_CONTAINER` to `DST_PATH` in
the `DST_CONTAINER`.

## Behavior of `docker cp SOURCE DEST`

The behavior has been changed to be similar to a combination of `mkdir -p` and
`cp -r`:

- `SOURCE` specifies a file
    - `DEST` does not exist
        - the file is saved to a file created at `DEST`
    - `DEST` exists and is a file
        - the file is overwritten with the contents of the source file
    - `DEST` exists and is a directory
        - the file is saved to this directory using the basename from `PATH`
- `SOURCE` specifies a directory (no trailing path separator)
    - `DEST` does not exist
        - `DEST` is created as a directory and the source directory is copied
          into this directory
    - `DEST` exists and is a file
        - Error condition: cannot copy a directory to a file
    - `DEST` exists and is a directory
        - the source directory is copied into this directory
- `SOURCE` specifies a directory (with trailing path separator)
    - `DEST` does not exist
        - `DEST` is created as a directory and the source directory's contents
          are copied into this directory
    - `DEST` exists and is a file
        - Error condition: cannot copy a directory to a file
    - `DEST` exists and is a directory
        - the source directory's contents are copied into this directory

**Comment by jfrazelle** [comment]
@brahmaroutu would you mind checking if #9871 fixes the issue. Then I think we can close this. Sorry for letting this linger for so long.

**Comment by brahmaroutu** [comment]
@jfrazelle Yes, we should close this issue. I see #9871 is a complete solution, addresses many more missing pieces from the copy command. Great Job from @jlhawn. 
I will post any concerns I have into #9871.

**Comment by jfrazelle** [comment]
thanks so much :)

**Pull request closed without merging**
