### PR TITLE
Remove erroneous ENTRYPOINT note

### PR DESCRIPTION
**Pull request by ddgenome**
**\- What I did**

I removed a confusing and inaccurate note about the behavior of ENV variable substitution in the ENTRYPOINT command documentation.

**\- How I did it**

I edited the markdown with a text editor.

**\- How to verify it**

Use an ENV variable in an ENTRYPOINT command and inspect the resulting image. See that in the image the literal `$ENV_VAR` is in the image, not its value. Therefore, it is clear that the Dockerfile parser does not do any substitution.

**\- Description for the changelog**

Correct ENTRYPOINT documentation

**\- A picture of a cute animal (not mandatory but encouraged)**

Two Words

The Dockerfile parser does not subsitute ENV variables in any form of
the ENTRYPOINT command.  Any substitution, if done, is done by the shell
when the command is executed.

Signed-off-by: David Dooling dooling@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by ddgenome** [comment]
@cpuguy83 I've added a sentence to make it clearer what is doing the variable expansion. I also added it to the similar note on the RUN and CMD exec sections.

**Comment by cpuguy83** [comment]
LGTM, thanks for adding the extra detail!

**Comment by vdemeester** [comment]
LGTM 👼

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
