### PR TITLE
WIP: Dump daemon stacks when getting close to test timeout

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure mickael.laventure@gmail.com

---

Trying to get more details on the random timeouts we had on integration tests lately (mainly on userns but not only).

I haven't been able to reproduce those locally, and assuming it is due to a deadlock, this should help pinpointing its origin.

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @tianon

**Comment by jhowardmsft** [comment]
windowsTP4 failure is real - compile error in tests:

```
16:47:07 ---> Making bundle: test-integration-cli (in bundles/1.11.0-dev/test-integration-cli)
16:47:07 ---> Making bundle: .integration-daemon-start (in bundles/1.11.0-dev/test-integration-cli)
16:47:07 INFO: Waiting for daemon to start...
16:47:07 
16:47:07 +++ bridge link show
16:47:07 /c/gopath/src/github.com/docker/docker/hack/make/.integration-daemon-start: line 106: bridge: command not found
16:47:07 + ec=1
16:47:07 + set +x
16:47:07 
```

**Comment by mlaventure** [comment]
@jhowardmsft thanks, this is not meant to be merged in that state, I'll add a WIP to the title.

**Comment by jhowardmsft** [comment]
@mlaventure Understood. Thanks :smiley:

**Comment by mlaventure** [comment]
Deadlock hasn't happened again, closing this now.

**Pull request closed without merging**
