### PR TITLE
Documentation - smallest typo correction ever

### PR DESCRIPTION
**Pull request by cyrilf**
From the contribution guidelines

> Not sure if that typo is worth a pull request? Do it! We will appreciate it.

Ok, so here it is.

### CODE REVIEW

**Comment by cyrilf** [comment]
**Done**. I was unsure about the necessity for such a small change, but that's fine now.

(please tell me that you're usin an automated tool to detect this, you can't be that quick :wink: )

**Comment by duglin** [comment]
Contrary to popular belief, turtles can be really quick when they want to be  :-)

**Comment by cyrilf** [comment]
Ahah, that's impressive indeed.
It makes me want to do another PR later on, to see if this applies anytime.
But I guess that there is things which are best to keep as mysteries.

**Comment by SvenDowideit** [comment]
LGTM - @fredlf @jamtur01 

nice catch, thank you!

**Pull request merged**
