### PR TITLE
Updating event diagram with the created state

### PR DESCRIPTION
**Pull request by moxiegirl**
Merge this when #13367 is complete

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**DO NOT MERGE** depends on https://github.com/docker/docker/pull/13367

**Comment by moxiegirl** [comment]
@thaJeztah no one will merge, I put a next on it.  I can lift it whenever

**Comment by thaJeztah** [comment]
ping @moxiegirl the related PR (https://github.com/docker/docker/pull/13367) was merged, so feel free to merge this

**Pull request merged**
