### PR TITLE
chore: update supported go version to 1.18+

### PR DESCRIPTION
**Pull request by neersighted**
**- What I did**
The 1.16 `io/fs` compatibility code was being built on 1.18 and 1.19. Drop it completely as 1.16 is long EOL, and additionally drop 1.17 as it has been EOL for a month and 1.18 is both the minimum Go supported by the 20.10 branch, as well as a very easy jump from 1.17.

**- How to verify it**
CI

**- Description for the changelog**
- Update the minimum supported Go version to 1.18 to align with upstream and the 20.10 branch.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
yup; for "master" and 22.06 this should definitely be ok to take

**Review by aahmed7 — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Actually, let me remove the "cherry-pick" - don't think we need this for 22.06 as its only a minor cleanup

**Comment by neersighted** [comment]
@thaJeztah I'd prefer to bring it in for 22.06 as building the compatibility code on all supported Go versions seems like a step back from just using the stdlib.

**Comment by thaJeztah** [comment]
Ah, sure; feel free to open a backport

**Pull request merged**
