### PR TITLE
libnetwork: ServeDNS(): don't panic on unsupported query types

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/42929

This was added in b3c883bb2f560fc935315102983092438f76be25 (https://github.com/moby/moby/pull/42262), but resulted in a panic if the embedded DNS had to handle an unsupported query-type, such as ANY.

This patch adds a debug log for this case (to better describe how it's handled.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by tao12345666333 — APPROVED** [review]
Thanks!

**Review by samuelkarp — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
😲

**Comment by tao12345666333** [comment]
HI @thaJeztah  can you please re-run CI?  So that this PR can be merged :heart:

**Comment by thaJeztah** [comment]
Started it again, but I hope it helps; the CRIU packages we install from the openSUSE package repositories where broken because their signing key expired

**Comment by thaJeztah** [comment]
Nope, looks to be still broken;

```
#46 [criu 1/2] ADD --chmod=0644 https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10/Release.key /etc/apt/trusted.gpg.d/criu.gpg.asc
#46 sha256:ee6cfbe8dc560f6a16a48cfbd0bdcd49ee966236f38ee3a23e4715245b406323
#46 CACHED
#47 [criu 2/2] RUN --mount=type=cache,sharing=locked,id=moby-criu-aptlib,target=/var/lib/apt     --mount=type=cache,sharing=locked,id=moby-criu-aptcache,target=/var/cache/apt         echo 'deb https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10/ /' > /etc/apt/sources.list.d/criu.list         && apt-get update         && apt-get install -y --no-install-recommends criu         && install -D /usr/sbin/criu /build/criu
#47 sha256:f4e31d46f0e06f1386ef6304efac440ca5b23c7b1858aa7e80a04275c7b3c248
#47 5.595 Hit:1 http://cdn-fastly.deb.debian.org/debian bullseye InRelease
#47 5.595 Hit:2 http://cdn-fastly.deb.debian.org/debian-security bullseye-security InRelease
#47 5.595 Hit:3 http://cdn-fastly.deb.debian.org/debian bullseye-updates InRelease
#47 6.443 Get:4 https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease [1540 B]
#47 10.39 Err:4 https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease
#47 10.39   The following signatures were invalid: EXPKEYSIG 30A8343A498D5A23 devel:tools OBS Project <devel:tools@build.opensuse.org>
#47 10.42 Reading package lists...
#47 18.92 W: GPG error: https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 30A8343A498D5A23 devel:tools OBS Project <devel:tools@build.opensuse.org>
#47 18.92 E: The repository 'https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease' is not signed.
#47 ERROR: executor failed running [/bin/sh -c echo 'deb https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10/ /' > /etc/apt/sources.list.d/criu.list         && apt-get update         && apt-get install -y --no-install-recommends criu         && install -D /usr/sbin/criu /build/criu]: exit code: 100
```

```dockerfile
ADD --chmod=0644 https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10/Release.key /etc/apt/trusted.gpg.d/criu.gpg.asc
RUN --mount=type=cache,sharing=locked,id=moby-criu-aptlib,target=/var/lib/apt \
    --mount=type=cache,sharing=locked,id=moby-criu-aptcache,target=/var/cache/apt \
         echo 'deb https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10/ /' > /etc/apt/sources.list.d/criu.list \
         && apt-get update \
         && apt-get install -y --no-install-recommends criu \
         && install -D /usr/sbin/criu /build/criu
```

```
Hit:1 http://cdn-fastly.deb.debian.org/debian bullseye InRelease
Hit:2 http://cdn-fastly.deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://cdn-fastly.deb.debian.org/debian bullseye-updates InRelease
Get:4 https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease [1540 B]
Err:4 https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease
  The following signatures were invalid: EXPKEYSIG 30A8343A498D5A23 devel:tools OBS Project <devel:tools@build.opensuse.org>
Reading package lists...
W: GPG error: https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 30A8343A498D5A23 devel:tools OBS Project <devel:tools@build.opensuse.org>
E: The repository 'https://download.opensuse.org/repositories/devel:/tools:/criu/Debian_10  InRelease' is not signed.
```


/cc @kolyshkin @cyphar @adrianreber

**Comment by thaJeztah** [comment]
> Perhaps we need changes similar to [opencontainers/runc#3222](https://github.com/opencontainers/runc/pull/3222) (need to look at what exactly the differences are)

Nope, no difference (I was wondering if the `gpg --dearmor`, the different file path, and the addition of `[signed-by=xxxx]` would make a difference (perhaps the `EXPKEYSIG` was some false positive, but getting the same error with the code from runc)

**Comment by kolyshkin** [comment]
I am not sure how to report bugs to that system, so I left a comment:
https://build.opensuse.org/project/show/devel:tools#comment-1529333

**Comment by thaJeztah** [comment]
@adrianreber ah, cool. Yes, I just tried, and it seems to work again 👍 That means I can move https://github.com/moby/moby/pull/42936 out of draft

**Comment by cyphar** [comment]
@adrianreber 

> @thaJeztah not sure if that was the best solution, but I triggered a rebuild and now it might be fixed. I was not aware that I have to do this manually.

It seems that while the keys are rotated automatically for OBS projects, they don't re-sign all of the packages when they rotate them? I'll ping the OBS guys internally for them to take a look at why this happened.

**Comment by thaJeztah** [comment]
Thanks for checking, Aleksa!

**Comment by cyphar** [comment]
It seems that automatic key rotation not being enabled is seen as some kind of safety feature(?), still discussing this with them but the correct way of rotating the keys is `osc signkey --extend devel:tools`.

**Pull request merged**
