### PR TITLE
fix secret update from the docker swarm update

### PR DESCRIPTION
**Pull request by vieux**
@tonistiigi @diogomonica I think now isn't the right time to update engine-api, let's do this for now and update in RC2

### CODE REVIEW

**Comment by icecrime** [comment]
```
12:42:02 ---> Making bundle: validate-gofmt (in bundles/1.12.0-dev/validate-gofmt)
12:42:02 These files are not properly gofmt'd:
12:42:02  - api/client/swarm/update.go
```

**Comment by vieux** [comment]
@icecrime updated.

**Comment by diogomonica** [comment]
This is a really ugly hack. We should probably just do what we talked about and use the nil as the "don't touch this distinguisher.

**Comment by vieux** [comment]
@diogomonica ok, let's to that in rc2

**Pull request closed without merging**
