### PR TITLE
Added pride month to namegenerator 🏳️‍🌈

### PR DESCRIPTION
**Pull request by SharkyRawr**
**- What I did**
Added a few LGBTQI+ orientations to pkg/namegenerator https://github.com/SharkyRawr/moby/commit/0fad8b215cf3add6bba7d615a3b472ad46f04232

**- How I did it**
Wrote a bit of code that shouldn't be problematic.

**- How to verify it**
For testing, change the following line in file https://github.com/SharkyRawr/moby/blob/pridemonth/pkg/namesgenerator/names-generator.go: 
```
if time.Now().Month() == 6 {
		// It's pride month! 🏳️‍🌈
```

to your current month and then `go run pkg/namesgenerator/cmd/names-generator/main.go`

**- Description for the changelog**
Added easter egg to the namegenerator which creates container names with LGBTQI+ terms every year on June for Pride Month.

**- A picture of a cute animal (not mandatory but encouraged)**

IMG_2642
(sharks are cute! 🦈))

### CODE REVIEW

**Comment by thaJeztah** [comment]
I love the idea 🏳️‍🌈 🎉😍

Also gonna be honest that I'm not sure _if_ we can include this. From a technical perspective, we'll need to check if the overhead of the month check can be avoided. We'll also have to take into account that we have a global user-base, and (unfortunately) not all of those are equally "forward thinking" 😞  (I recall "kickass" in the names generator already being a reason for various users to complain 🙄 🤷‍♂️).

That said, perhaps we should bring back the discussion on making the names-generator pluggable somehow (this idea came up on a couple of occasions where "yet-another request for removing a possibly offensive word came in"

**Comment by thaJeztah** [comment]
We discussed this pull request in the maintainers meeting, and decided not to merge this change for reasons above, but thanks again for contributing, it's appreciated!

**Comment by Owlor** [comment]
I just want to point out that "global user-base" here is code for "some of our users are bigots" and that what's deemed too "forward-thinking" to include is the idea that LGBTQI+ identities exist.

**Comment by ioistired** [comment]
Yep, had ICANN listened to their global constituents, we would not have .gay and .lgbt, because Saudi Arabia is a member. Bit of an extreme comparison but still :P

**Pull request closed without merging**
