### PR TITLE
1.13.x: Cherrypick 28538

### PR DESCRIPTION
**Pull request by aluzzardi**
Cherry pick `go vet` / `go fmt` issue fixes (#28538)

/cc @vieux @aaronlehmann @LK4D4 @mlaventure

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by crosbymichael** [comment]
Still more errors:

```
Errors from golint:
23:05:46 cmd/docker/docker.go:82:3: error strings should not end with punctuation
23:05:46 daemon/info_unix.go:16:1: exported method Daemon.FillPlatformInfo should have comment or be unexported
23:05:46 daemon/info_windows.go:8:1: exported method Daemon.FillPlatformInfo should have comment or be unexported
23:05:46 volume/local/local.go:272:37: error strings should not end with punctuation
```

**Comment by justincormack** [comment]
lint still complaining
```
23:05:46 cmd/docker/docker.go:82:3: error strings should not end with punctuation
23:05:46 daemon/info_unix.go:16:1: exported method Daemon.FillPlatformInfo should have comment or be unexported
23:05:46 daemon/info_windows.go:8:1: exported method Daemon.FillPlatformInfo should have comment or be unexported
23:05:46 volume/local/local.go:272:37: error strings should not end with punctuation
```

**Comment by aluzzardi** [comment]
I'm trying to locate the commits that fixed master so we can cherry pick them (assuming master builds fine)

Any idea?

**Comment by aluzzardi** [comment]
Closing in favor of #28489 /cc @vieux

**Comment by mlaventure** [comment]
They're not fixed in master. The lint script only validate changed files.

**Pull request closed without merging**
