### PR TITLE
Use newer x/sys/windows SecurityAttributes struct (carry 40017)

### PR DESCRIPTION
**Pull request by thaJeztah**
carries https://github.com/moby/moby/pull/40017
closes https://github.com/moby/moby/pull/40017

changes since https://github.com/moby/moby/pull/40017:

- split the vendor bump in a separate commit ()
    - full diff of x/sys upstream: full diff: https://github.com/golang/sys/compare/9eafafc0a87e0fd0aeeba439a4573537970c44c7...c990c680b611ac1aeb7d8f2af94a825f98d69720
- fixed the remaining stray import; https://github.com/moby/moby/pull/40017#issuecomment-536696709

This struct now has a properly typed member, so use the properly typed functions with it.

### CODE REVIEW

**Comment by zx2c4** [comment]
LGTM. :+1:

**Comment by thaJeztah** [comment]
@tklauser @vikramhh @kolyshkin PTAL

**Comment by tklauser** [comment]
LGTM, but I'd wait for the outcome of the discussion on golang/go#34610 where the decision might be to revert the change to `SecurityAttributes` and introduce a new struct type with a different name.

**Comment by ArmandGrillet** [comment]
According to https://github.com/golang/go/issues/34610#issuecomment-537893873 and the status of the issue (i.e. stale), the change will not be reverted.

**Comment by tklauser** [comment]
@thaJeztah This is good to go now that golang/go#34610 has been closed and it was decided there will be no revert (https://github.com/golang/go/issues/34610#issuecomment-551225468)

**Comment by thaJeztah** [comment]
@ArmandGrillet @tklauser thanks for the heads-up; I removed "do not merge" from the title, and triggered CI

**Comment by ArmandGrillet** [comment]
CI looks green 🎉, @tonistiigi can you please review this PR?

**Review by tiborvass — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
