### PR TITLE
Fix F24 rpm build

### LINKED ISSUE #24235: Cannot build rpm for Fedora 24
**Steps to reproduce the issue:**
1. `docker build -t docker .`
2. `docker run -it --privileged -v $(pwd)/bundles:/go/src/github.com/docker/docker/bundles -e DOCKER_BUILD_PKGS=fedora-24 -e DOCKER_GRAPHDRIVER=aufs docker hack/make.sh binary build-rpm`

**Describe the results you received:**
A built rpm in bundles/

**Describe the results you expected:**
At step:
```
RUN rpmbuild -ba \
        --define '_gitcommit 4949c95' \
        --define '_release 0.3.rc3' \
        --define '_version 1.12.0' \
        --define '_origversion 1.12.0-rc3' \
        docker-engine.spec
```
the following error:
```
error: line 89: Invalid version (epoch must be unsigned integer): %{epoch}:1.12.0-0.3.rc3.fc24: Requires(pre): docker-engine-selinux >= %{epoch}:1.12.0-0.3.rc3.fc24
```

Related to #23896

### PR DESCRIPTION
**Pull request by runcom**
fix https://github.com/docker/docker/issues/24235

/cc @tiborvass

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jfrazelle perhaps you had a specific reason to add `%{epoch}`? https://github.com/docker/docker/commit/df6d92837029411bd06c4541c08c20127ce8327e

**Comment by thaJeztah** [comment]
(thanks @runcom)

LGTM

**Comment by runcom** [comment]
> ping @jfrazelle perhaps you had a specific reason to add %{epoch}? df6d928

just for reference https://github.com/docker/docker/issues/24235#issuecomment-230052748

**Comment by jfrazelle** [comment]
i can't remember a specific reason tbh so seems good to me

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
