### PR TITLE
Bump runc to f59ba3cdd76fdc08c004f42aa915996f6f420899

### LINKED ISSUE #27540: exec not running
**Description**
`docker exec -i -t <container_id> bash`
the above command giving me error that the image has run and stopped, but my image is still running.

Error:
`rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"`

I am running the Airflow Image from [this place](https://github.com/puckel/docker-airflow)
`docker pull puckel/docker-airflow`

I ran the Image with below command from [simple-docker-ui-app](https://github.com/felixgborrego/docker-ui-chrome-app)
`docker run -i -t -P --name airflow puckel/docker-airflow:latest docker-compose -f docker-compose-LocalExecutor.yml up -d`

**Steps to reproduce the issue:**
1. start the docker image 
2. run below command
`docker exec -i -t <container_id> bash`

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### LINKED ISSUE #27590: Possible container privilege escalation: Docker 1.12.2 does not correctly apply user permissions in containers.
**Description**
Docker 1.12.2 does not correctly apply user permissions in containers.

**Steps to reproduce the issue:**

1. Create a Dockerfile as follows:
```
FROM debian
RUN useradd example
RUN id
USER example
RUN id
RUN cat /etc/shadow
CMD /bin/bash
```
2. docker build --no-cache -t example .
```
Sending build context to Docker daemon 155.1 MB
Step 1 : FROM debian
 ---> ddf73f48a05d
Step 2 : RUN useradd example
 ---> Running in 1791589193df
 ---> 8b03b79855a4
Removing intermediate container 1791589193df
Step 3 : RUN id
 ---> Running in b2ff8d1cad96
uid=0(root) gid=0(root) groups=0(root)
 ---> 3a17be9d5e6f
Removing intermediate container b2ff8d1cad96
Step 4 : USER example
 ---> Running in 7d07637c4492
 ---> 946266261780
Removing intermediate container 7d07637c4492
Step 5 : RUN id
 ---> Running in 22ae65564b94
uid=1000(example) gid=1000(example) groups=1000(example)
 ---> 6486bfff2351
Removing intermediate container 22ae65564b94
Step 6 : RUN cat /etc/shadow
 ---> Running in 545e009f4250
root:*:17067:0:99999:7:::
daemon:*:17067:0:99999:7:::
bin:*:17067:0:99999:7:::
sys:*:17067:0:99999:7:::
sync:*:17067:0:99999:7:::
games:*:17067:0:99999:7:::
man:*:17067:0:99999:7:::
lp:*:17067:0:99999:7:::
mail:*:17067:0:99999:7:::
news:*:17067:0:99999:7:::
uucp:*:17067:0:99999:7:::
proxy:*:17067:0:99999:7:::
www-data:*:17067:0:99999:7:::
backup:*:17067:0:99999:7:::
list:*:17067:0:99999:7:::
irc:*:17067:0:99999:7:::
gnats:*:17067:0:99999:7:::
nobody:*:17067:0:99999:7:::
systemd-timesync:*:17067:0:99999:7:::
systemd-network:*:17067:0:99999:7:::
systemd-resolve:*:17067:0:99999:7:::
systemd-bus-proxy:*:17067:0:99999:7:::
example:!:17094:0:99999:7:::
 ---> a20eb2ad353a
Removing intermediate container 545e009f4250
Step 7 : CMD /bin/bash
 ---> Running in 3bc78e8b7617
 ---> 7cd3b55873c7
Removing intermediate container 3bc78e8b7617
Successfully built 7cd3b55873c7
```
3. docker run -u example -it example
```
example@2fdde3bace94:/$ id
uid=1000(example) gid=1000(example) groups=1000(example)
example@2fdde3bace94:/$ whoami
example
example@2fdde3bace94:/$ chmod +s /bin/sh
example@2fdde3bace94:/$ /bin/sh
# whoami
root
# 
 ```
**Describe the results you received:**
When a non privileged user is defined in the Dockerfile, the container, as expected, starts as a non privileged user. Even if a non-privileged user is enforced, privileged commands can be executed.
This behavior only happens with Docker version 1.12.2, build bb80604 and and has been tested both with and without setting the -u modifier. 

I have also tested Docker 1.12.1 and this issue does not occur:
```
docker build -t newversion . --no-cache
Sending build context to Docker daemon 155.1 MB
Step 1 : FROM registry.access.redhat.com/rhel7.2:latest
 ---> 98a88a8b722a
Step 2 : RUN useradd example
 ---> Running in a634c08405f8
 ---> 060c945c7f30
Removing intermediate container a634c08405f8
Step 3 : RUN id
 ---> Running in 8aaad2d0cabe
uid=0(root) gid=0(root) groups=0(root)
 ---> 599f75c31f64
Removing intermediate container 8aaad2d0cabe
Step 4 : USER example
 ---> Running in 97356bf6dc19
 ---> 9d57a913b64a
Removing intermediate container 97356bf6dc19
Step 5 : RUN id
 ---> Running in 5d49b3a7c03d
uid=1000(example) gid=1000(example) groups=1000(example)
 ---> fd1effd96c25
Removing intermediate container 5d49b3a7c03d
Step 6 : RUN cat /etc/shadow
 ---> Running in 42539688c8c1
cat: /etc/shadow: Permission denied
The command '/bin/sh -c cat /etc/shadow' returned a non-zero code: 1

docker -v
Docker version 1.12.1, build 23cf638
```

The issue is reproducible with various image defined in FROM : alpine, centos, rhel, debian...

**Describe the results you expected:**
Non privileged users inside containers should not be able to access privileged system functions. The following actions were possible as a non privileged user:
- Write to /
- Read and write to /etc/shadow
- Add SUID to sh
- Add users to the system

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:53:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:53:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 191
 Running: 2
 Paused: 0
 Stopped: 189
Images: 56
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 591
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.5.0-kali1-amd64
Operating System: Kali GNU/Linux Rolling
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.37 GiB
Name: Omega
ID: 3W4I:EJTU:52I3:PUB3:VS3R:UVZ7:PRLI:GE4D:A7TL:IQGA:Q3DO:V5V7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: *****
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested on Kali Linux, Fedora and Ubuntu LTS

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #27540
Fixes #27590

This includes fixes for exec when there is a space in the process name of the stat file and removing ambient capabilities. 

diff:

``` patch
diff --git a/Godeps/Godeps.json b/Godeps/Godeps.json
index 152246d..8e4d8ba 100644
--- a/Godeps/Godeps.json
+++ b/Godeps/Godeps.json
@@ -68,7 +68,7 @@
        },
        {
            "ImportPath": "github.com/syndtr/gocapability/capability",
-           "Rev": "e7cb7fa329f456b3855136a2642b197bad7366ba"
+           "Rev": "2c00daeb6c3b45114c80ac44119e7b8801fdd852"
        },
        {
            "ImportPath": "github.com/vishvananda/netlink",
diff --git a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go
index c07c557..c13f4e5 100644
--- a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go
+++ b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go
@@ -10,42 +10,42 @@ package capability
 type Capabilities interface {
    // Get check whether a capability present in the given
    // capabilities set. The 'which' value should be one of EFFECTIVE,
-   // PERMITTED, INHERITABLE, BOUNDING or AMBIENT.
+   // PERMITTED, INHERITABLE or BOUNDING.
    Get(which CapType, what Cap) bool

    // Empty check whether all capability bits of the given capabilities
    // set are zero. The 'which' value should be one of EFFECTIVE,
-   // PERMITTED, INHERITABLE, BOUNDING or AMBIENT.
+   // PERMITTED, INHERITABLE or BOUNDING.
    Empty(which CapType) bool

    // Full check whether all capability bits of the given capabilities
    // set are one. The 'which' value should be one of EFFECTIVE,
-   // PERMITTED, INHERITABLE, BOUNDING or AMBIENT.
+   // PERMITTED, INHERITABLE or BOUNDING.
    Full(which CapType) bool

    // Set sets capabilities of the given capabilities sets. The
    // 'which' value should be one or combination (OR'ed) of EFFECTIVE,
-   // PERMITTED, INHERITABLE, BOUNDING or AMBIENT.
+   // PERMITTED, INHERITABLE or BOUNDING.
    Set(which CapType, caps ...Cap)

    // Unset unsets capabilities of the given capabilities sets. The
    // 'which' value should be one or combination (OR'ed) of EFFECTIVE,
-   // PERMITTED, INHERITABLE, BOUNDING or AMBIENT.
+   // PERMITTED, INHERITABLE or BOUNDING.
    Unset(which CapType, caps ...Cap)

    // Fill sets all bits of the given capabilities kind to one. The
-   // 'kind' value should be one or combination (OR'ed) of CAPS,
-   // BOUNDS or AMBS.
+   // 'kind' value should be one or combination (OR'ed) of CAPS or
+   // BOUNDS.
    Fill(kind CapType)

    // Clear sets all bits of the given capabilities kind to zero. The
-   // 'kind' value should be one or combination (OR'ed) of CAPS,
-   // BOUNDS or AMBS.
+   // 'kind' value should be one or combination (OR'ed) of CAPS or
+   // BOUNDS.
    Clear(kind CapType)

    // String return current capabilities state of the given capabilities
    // set as string. The 'which' value should be one of EFFECTIVE,
-   // PERMITTED, INHERITABLE BOUNDING or AMBIENT
+   // PERMITTED, INHERITABLE or BOUNDING.
    StringCap(which CapType) string

    // String return current capabilities state as string.
diff --git a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go
index 6d2135a..3dfcd39 100644
--- a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go
+++ b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go
@@ -235,10 +235,9 @@ func (c *capsV1) Apply(kind CapType) error {
 }

 type capsV3 struct {
-   hdr     capHeader
-   data    [2]capData
-   bounds  [2]uint32
-   ambient [2]uint32
+   hdr    capHeader
+   data   [2]capData
+   bounds [2]uint32
 }

 func (c *capsV3) Get(which CapType, what Cap) bool {
@@ -257,8 +256,6 @@ func (c *capsV3) Get(which CapType, what Cap) bool {
        return (1<<uint(what))&c.data[i].inheritable != 0
    case BOUNDING:
        return (1<<uint(what))&c.bounds[i] != 0
-   case AMBIENT:
-       return (1<<uint(what))&c.ambient[i] != 0
    }

    return false
@@ -278,9 +275,6 @@ func (c *capsV3) getData(which CapType, dest []uint32) {
    case BOUNDING:
        dest[0] = c.bounds[0]
        dest[1] = c.bounds[1]
-   case AMBIENT:
-       dest[0] = c.ambient[0]
-       dest[1] = c.ambient[1]
    }
 }

@@ -319,9 +313,6 @@ func (c *capsV3) Set(which CapType, caps ...Cap) {
        if which&BOUNDING != 0 {
            c.bounds[i] |= 1 << uint(what)
        }
-       if which&AMBIENT != 0 {
-           c.ambient[i] |= 1 << uint(what)
-       }
    }
 }

@@ -345,9 +336,6 @@ func (c *capsV3) Unset(which CapType, caps ...Cap) {
        if which&BOUNDING != 0 {
            c.bounds[i] &= ^(1 << uint(what))
        }
-       if which&AMBIENT != 0 {
-           c.ambient[i] &= ^(1 << uint(what))
-       }
    }
 }

@@ -365,10 +353,6 @@ func (c *capsV3) Fill(kind CapType) {
        c.bounds[0] = 0xffffffff
        c.bounds[1] = 0xffffffff
    }
-   if kind&AMBS == AMBS {
-       c.ambient[0] = 0xffffffff
-       c.ambient[1] = 0xffffffff
-   }
 }

 func (c *capsV3) Clear(kind CapType) {
@@ -385,10 +369,6 @@ func (c *capsV3) Clear(kind CapType) {
        c.bounds[0] = 0
        c.bounds[1] = 0
    }
-   if kind&AMBS == AMBS {
-       c.ambient[0] = 0
-       c.ambient[1] = 0
-   }
 }

 func (c *capsV3) StringCap(which CapType) (ret string) {
@@ -430,10 +410,6 @@ func (c *capsV3) Load() (err error) {
            fmt.Sscanf(line[4:], "nd:  %08x%08x", &c.bounds[1], &c.bounds[0])
            break
        }
-       if strings.HasPrefix(line, "CapA") {
-           fmt.Sscanf(line[4:], "mb:  %08x%08x", &c.ambient[1], &c.ambient[0])
-           break
-       }
    }
    f.Close()

@@ -466,25 +442,7 @@ func (c *capsV3) Apply(kind CapType) (err error) {
    }

    if kind&CAPS == CAPS {
-       err = capset(&c.hdr, &c.data[0])
-       if err != nil {
-           return
-       }
-   }
-
-   if kind&AMBS == AMBS {
-       for i := Cap(0); i <= CAP_LAST_CAP; i++ {
-           action := pr_CAP_AMBIENT_LOWER
-           if c.Get(AMBIENT, i) {
-               action = pr_CAP_AMBIENT_RAISE
-           }
-           err := prctl(pr_CAP_AMBIENT, action, uintptr(i), 0, 0)
-           // Ignore EINVAL as not supported on kernels before 4.3
-           if errno, ok := err.(syscall.Errno); ok && errno == syscall.EINVAL {
-               err = nil
-               continue
-           }
-       }
+       return capset(&c.hdr, &c.data[0])
    }

    return
diff --git a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go
index 6938173..fd0ce7f 100644
--- a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go
+++ b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go
@@ -20,8 +20,6 @@ func (c CapType) String() string {
        return "bounding"
    case CAPS:
        return "caps"
-   case AMBIENT:
-       return "ambient"
    }
    return "unknown"
 }
@@ -31,11 +29,9 @@ const (
    PERMITTED
    INHERITABLE
    BOUNDING
-   AMBIENT

    CAPS   = EFFECTIVE | PERMITTED | INHERITABLE
    BOUNDS = BOUNDING
-   AMBS   = AMBIENT
 )

 //go:generate go run enumgen/gen.go
diff --git a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go
index eb71700..dd6f454 100644
--- a/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go
+++ b/Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go
@@ -38,15 +38,6 @@ func capset(hdr *capHeader, data *capData) (err error) {
    return
 }

-// not yet in syscall
-const (
-   pr_CAP_AMBIENT           = 47
-   pr_CAP_AMBIENT_IS_SET    = uintptr(1)
-   pr_CAP_AMBIENT_RAISE     = uintptr(2)
-   pr_CAP_AMBIENT_LOWER     = uintptr(3)
-   pr_CAP_AMBIENT_CLEAR_ALL = uintptr(4)
-)
-
 func prctl(option int, arg2, arg3, arg4, arg5 uintptr) (err error) {
    _, _, e1 := syscall.Syscall6(syscall.SYS_PRCTL, uintptr(option), arg2, arg3, arg4, arg5, 0)
    if e1 != 0 {
diff --git a/libcontainer/capabilities_linux.go b/libcontainer/capabilities_linux.go
index 48338a1..4eda56d 100644
--- a/libcontainer/capabilities_linux.go
+++ b/libcontainer/capabilities_linux.go
@@ -10,7 +10,7 @@ import (
    "github.com/syndtr/gocapability/capability"
 )

-const allCapabilityTypes = capability.CAPS | capability.BOUNDS | capability.AMBS
+const allCapabilityTypes = capability.CAPS | capability.BOUNDS

 var capabilityMap map[string]capability.Cap

diff --git a/libcontainer/system/proc.go b/libcontainer/system/proc.go
index 37808a2..a0e9637 100644
--- a/libcontainer/system/proc.go
+++ b/libcontainer/system/proc.go
@@ -14,8 +14,10 @@ func GetProcessStartTime(pid int) (string, error) {
    if err != nil {
        return "", err
    }
+   return parseStartTime(string(data))
+}

-   parts := strings.Split(string(data), " ")
+func parseStartTime(stat string) (string, error) {
    // the starttime is located at pos 22
    // from the man page
    //
@@ -23,5 +25,19 @@ func GetProcessStartTime(pid int) (string, error) {
    // (22)  The  time the process started after system boot.  In kernels before Linux 2.6, this
    // value was expressed in jiffies.  Since Linux 2.6, the value is expressed in  clock  ticks
    // (divide by sysconf(_SC_CLK_TCK)).
-   return parts[22-1], nil // starts at 1
+   //
+   // NOTE:
+   // pos 2 could contain space and is inside `(` and `)`:
+   // (2) comm  %s
+   // The filename of the executable, in parentheses.
+   // This is visible whether or not the executable is
+   // swapped out.
+   //
+   // the following is an example:
+   // 89653 (gunicorn: maste) S 89630 89653 89653 0 -1 4194560 29689 28896 0 3 146 32 76 19 20 0 1 0 2971844 52965376 3920 18446744073709551615 1 1 0 0 0 0 0 16781312 137447943 0 0 0 17 1 0 0 0 0 0 0 0 0 0 0 0 0 0
+
+   // get parts after last `)`:
+   s := strings.Split(stat, ")")
+   parts := strings.Split(strings.TrimSpace(s[len(s)-1]), " ")
+   return parts[22-3], nil // starts at 3 (after the filename pos `2`)
 }
diff --git a/libcontainer/system/proc_test.go b/libcontainer/system/proc_test.go
new file mode 100644
index 0000000..ba91029
--- /dev/null
+++ b/libcontainer/system/proc_test.go
@@ -0,0 +1,20 @@
+package system
+
+import "testing"
+
+func TestParseStartTime(t *testing.T) {
+   data := map[string]string{
+       "4902 (gunicorn: maste) S 4885 4902 4902 0 -1 4194560 29683 29929 61 83 78 16 96 17 20 0 1 0 9126532 52965376 1903 18446744073709551615 4194304 7461796 140733928751520 140733928698072 139816984959091 0 0 16781312 137447943 1 0 0 17 3 0 0 9 0 0 9559488 10071156 33050624 140733928758775 140733928758945 140733928758945 140733928759264 0": "9126532",
+       "9534 (cat) R 9323 9534 9323 34828 9534 4194304 95 0 0 0 0 0 0 0 20 0 1 0 9214966 7626752 168 18446744073709551615 4194304 4240332 140732237651568 140732237650920 140570710391216 0 0 0 0 0 0 0 17 1 0 0 0 0 0 6340112 6341364 21553152 140732237653865 140732237653885 140732237653885 140732237656047 0":                                      "9214966",
+       "24767 (irq/44-mei_me) S 2 0 0 0 -1 2129984 0 0 0 0 0 0 0 0 -51 0 1 0 8722075 0 0 18446744073709551615 0 0 0 0 0 0 0 2147483647 0 0 0 0 17 1 50 1 0 0 0 0 0 0 0 0 0 0 0":                                                                                                                                                                         "8722075",
+   }
+   for line, startTime := range data {
+       st, err := parseStartTime(line)
+       if err != nil {
+           t.Fatal(err)
+       }
+       if startTime != st {
+           t.Fatalf("expected start time %q but received %q", startTime, st)
+       }
+   }
+}
```

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Is there a corresponding PR for master?

**Comment by crosbymichael** [comment]
@aaronlehmann i will update master with master after this is tested.  I think @justincormack wants to keep the amb cap code in master to finish the policy work correct?

**Comment by vieux** [comment]
ping @justincormack

**Comment by justincormack** [comment]
Yes, working on how best to support on master.

**Comment by justincormack** [comment]
LGTM

**Comment by crosbymichael** [comment]
@LK4D4 what are those?

**Comment by crosbymichael** [comment]
omg, whyyyyyyyyy

**Comment by crosbymichael** [comment]
Updated from build-deb/rpm

**Comment by LK4D4** [comment]
LGTM

**Comment by mlaventure** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by justincormack** [comment]
Yes, working on best solution for master.

**Pull request merged**
