### PR TITLE
add trace in docker engine's pprof to show execution trace in binary form

### PR DESCRIPTION
**Pull request by allencloud**
add trace in docker engine's pprof to show execution trace in binary form

### CODE REVIEW

**Comment by LK4D4** [comment]
I suppose we don't support go1.4 anymore. ping @tianon

**Comment by tianon** [comment]
I think that's probably fine at this point, yeah.  We'll need to update `project/PACKAGERS.md` appropriately to reflect that. :smile:

**Comment by LK4D4** [comment]
Haha, we can see that gccgo failed to compile this :) Dunno who to ask about gccgo, maybe IBM guys @MHBauer @estesp

**Comment by MHBauer** [comment]
I think @brahmaroutu or @tophj-ibm might have more insight into gccgo.

**Comment by tophj-ibm** [comment]
I'm guessing pprof/trace wasn't added until after go1.4? Right now the gccgo (and z I think) dockerfiles build gccgo 5.3 which runs go1.4.2, so if 1.4 is unsupported those will have to be bumped to 6.1 (go1.6.1). I'll look at gccgo,  ping @michael-holzheu about z.

**Comment by tophj-ibm** [comment]
looks like the go1.6 / docker bug is still open via #22000 so we'll have to wait for that before we can bump up the gccgo version.

**Comment by michael-holzheu** [comment]
> Right now the gccgo (and z I think) dockerfiles build gccgo 5.3 which runs go1.4.2, so if 1.4 is unsupported those will have to be bumped to 6.1 (go1.6.1).

Correct. We already had to add a workaround for the notary server (issue #22007).

**Comment by thaJeztah** [comment]
@michael-holzheu @tophj-ibm is there a version of gccgo that compares to go 1.5.x? Not sure if we're already switching to go 1.6.x for the next release

**Comment by tophj-ibm** [comment]
@thaJeztah nope, gccgo jumps from 1.4.2 to 1.6.0 😞

**Comment by allencloud** [comment]
What a pity ！

**Comment by thaJeztah** [comment]
ping @tophj-ibm @michael-holzheu #22000 have been merged, and there's a PR to move to Go 1.6.2; could you assist there to get the gccgo and z Dockerfiles updated to the right version? see https://github.com/docker/docker/pull/22840

**Comment by michael-holzheu** [comment]
> could you assist there to get the gccgo and z Dockerfiles updated to the right version?

For gcc 6.1.0 they seem to use go 1.6.1:
```
# git checkout gcc-6_1_0-release
# cat libgo/VERSION
go1.6.1
```
Couldn't we use go 1.6.1 for PR #22840 ?
IMHO if want to switch to gcc 6.1 we would have to create a new base image "gcc:6.1".
ping @tianon

**Comment by michael-holzheu** [comment]
> IMHO if want to switch to gcc 6.1 we would have to create a new base image "gcc:6.1".

Oehm, looks like we already have gcc:6.1: https://hub.docker.com/r/s390x/gcc/tags

Let me check if everything works with that image.

**Comment by LK4D4** [comment]
1.6.2 was security release, so it would be really unfortunate to use 1.6.1

**Comment by cpuguy83** [comment]
LGTM

**Comment by justincormack** [comment]
Just building this on s390x to double check but LGTM.

**Comment by allencloud** [comment]
```
00:32:25 ok  	github.com/docker/docker/pkg/httputils	10.040s
00:32:26 ok  	github.com/docker/docker/pkg/idtools	0.037s
03:27:48 Build timed out (after 180 minutes). Marking the build as failed.
03:27:48 Build timed out (after 180 minutes). Marking the build as aborted.
```
Ping @justincormack

**Comment by justincormack** [comment]
Ok it built on Z, still have the expected timeout issue which is known but LGTM.

**Comment by thaJeztah** [comment]
@justincormack should we raise the timeout for `z`?

**Comment by thaJeztah** [comment]
Just discussed, and the timeout is a known issue and will be fixed in a Jessie upgrade, so merging!

**Pull request merged**
