### PR TITLE
clean some redundant else clauses

### PR DESCRIPTION
**Pull request by WeiZhang555**
related issue:  #13296

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by WeiZhang555** [comment]
DockerSuite.TestLogsFollowGoroutinesWithStdout seems failed, is that my problem?

**Comment by coolljt0725** [comment]
I think `TestLogsFollowGoroutinesWithStdout`  is unrelated, see #13233

**Comment by runcom** [comment]
@WeiZhang555 it's unrelated as already said, tests are running again. Besides this, LGTM

**Comment by duglin** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM
even if in units you can remove all else clauses :)

**Comment by runcom** [comment]
yeah maybe a `switch` would have worked there, thanks @WeiZhang555 btw!

**Pull request merged**
