### PR TITLE
Use unique names in integration/service/plugin_test.go

### PR DESCRIPTION
**Pull request by jmartin84**
- What I did
changed integration/service/plugin_test.go to use unique names.
Part of #36583

- How I did it
Added t.Name() to resources names.

- How to verify it

- Description for the changelog
Modified integration/service/plugin_test.go to use unique names.

- A picture of a cute animal (not mandatory but encouraged)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Windows RS1 failure is unrelated and can be ignored;

```
powershell.exe : failed to register layer: re-exec error: exit status 1: output: BackupWrite 
\\?\D:\CI-1\CI-89fc04535\daemon\windowsfilter\6b15d976e2cd6254193bcda9abf8cc0bb89e381b94a48b7872370a15f07a9276\Files\Windows\InputMethod\CHS\ChsPinyin.lex: There is not enough space on the 
[2019-09-12T00:28:33.657Z] disk.
```

**Review by thaJeztah — APPROVED** [review]
LGTM! thanks for contributing!

**Comment by thaJeztah** [comment]
@vdemeester ptal 🤗

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
