### PR TITLE
integration/service/network integration tests to use network package

### PR DESCRIPTION
**Pull request by adshmh**
**- What I did**
refactored integration/service/network integration tests to use network package for consistency

**- How I did it**
Modified integration tests under `integration/service/network_test.go` to use the network package

**- How to verify it**

**- Description for the changelog**
integration/service/network integration tests use the network package to create network test resources

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :fire:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM, would you mind to do a rebase @adshmh?

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
