### PR TITLE
fix code note when push all tags

### PR DESCRIPTION
**Pull request by zhipengzuo**
when i watch the code of push_v2,I see some node is not correct.The node shoud be
push not pull .

### CODE REVIEW

**Comment by zhipengzuo** [comment]
@thaJeztah Hi,I create a new pr with dco here.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

@AkihiroSuda ptal

**Comment by zhipengzuo** [comment]
LGTM

**Comment by zhipengzuo** [comment]
Hi ,how to retest ?

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
