### PR TITLE
Fix a parser error where an empty RUN statement would cause a panic

### PR DESCRIPTION
**Pull request by erikh**
/cc @tiborvass @duglin

### CODE REVIEW

**Comment by tonistiigi** [comment]
FYI, `RUN []` also panics.

**Comment by erikh** [comment]
interesting. I'll look into it.

**Comment by erikh** [comment]
let's do this in another patch though.

**Comment by unclejack** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
