### PR TITLE
vendor: update swarmkit to 8a761950f

### PR DESCRIPTION
**Pull request by tonistiigi**
This also brings in swarmkit root key size change that should help with arm ci.

Also updated some swarmkit dependencies to match swamkit versions.

### CODE REVIEW

**Comment by tonistiigi** [comment]
@aaronlehmann Any idea what happened in the experimental there? It is `TestSwarmInit` that inits the daemon, force leaves and then runs init again. Second init seems to block. In daemon logs there are failed attempts for the agent to connect for 5 min https://gist.github.com/tonistiigi/3e0fa78d6c5df07b7232c82976794344#file-daemon-log-L227 and in stacktrace `manager.Run` seems to be stuck at `handleLeadershipEvents ` https://gist.github.com/tonistiigi/3e0fa78d6c5df07b7232c82976794344#file-daemon-stack-L415 Not sure why it can't select leader if this is the only node. Force leave should have cleared all the state from disk.

**Comment by aaronlehmann** [comment]
@tonistiigi: Actually `manager.Run` is not running. There are two `handleLeadershipEvents` started by different `manager.Run` invocations which are left over. This is unexpected, because the channel they loop over should be closed by raft when it shuts down.

I wonder if this could be related to https://github.com/docker/swarmkit/pull/1369.

**Comment by tonistiigi** [comment]
@aaronlehmann `manager.Run` completing but not shutting down node can be explained by https://github.com/docker/swarmkit/pull/1283#issuecomment-237980007

**Comment by tonistiigi** [comment]
Experimental issue is tracked in docker/swarmkit#1421 and our test works around it atm. That case should not easily happen in real-world use-cases. PTAL @aaronlehmann @LK4D4

**Comment by aaronlehmann** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
