### PR TITLE
Add "gofmt" from Go 1.3.3

### PR DESCRIPTION
**Pull request by tianon**
See also #9993 and #9995 (which led up to this).

I made three separate PRs so we can discuss each change individually (and I'm of course happy to rebase/amend/close each according to the appropriate discussions and decisions).

### CODE REVIEW

**Comment by SvenDowideit** [comment]
makes sense to me, but what do i know :)

**Comment by LK4D4** [comment]
@tianon I know, you just wanted hit #10000

**Comment by LK4D4** [comment]
@tianon Maybe makes sense to remove hack from `api/client/utils.go` then, so when we deprecate 1.3 we'll see this issue.

**Comment by tianon** [comment]
Agreed!  Updated. :+1:

**Comment by LK4D4** [comment]
@tianon Hehe, we have race :) Drone image should be updated with your change to pass.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
im ready to do the update image, update drone song and dance :dancer:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
