### PR TITLE
Update libcontainer

### PR DESCRIPTION
**Pull request by LK4D4**
Replaced github.com/docker/libcontainer with
github.com/opencontainers/runc/libcontaier.
Also I moved AppArmor profile generation to docker.

Main idea of this update is to fix mounting cgroups inside containers.
After updating docker on CI we can even remove dind.

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @hqhq @mrunalp @docker/core-maintainers 
Also if you know issues which will be closed by this, feel free to add references here.

**Comment by mrunalp** [comment]
:+1:

**Comment by kelseyhightower** [comment]
@LK4D4 How often will libcontainer be updated? I'm hoping https://github.com/opencontainers/runc/pull/77 gets merged before Docker 1.8.

**Comment by LK4D4** [comment]
@kelseyhightower We can update even immediately. Just soon code freeze, so we have maybe time until tuesday to decide.

**Comment by jfrazelle** [comment]
LGTM

**Comment by icecrime** [comment]
Yes! LGTM :+1:

@kelseyhightower We update libcontainer very frequently, however as far as I can tell we'll need some chances on docker side to benefit from opencontainers/runc#77, and I'm not sure this can make it in time for 1.8 (code freeze Tuesday).

**Comment by kelseyhightower** [comment]
@icecrime If there is any way possible to make it happen let me know. I know RedHat is working hard to land the patch, and other storage based projects will benefit from that landing. The change in behavior from 1.6.x really caught people off guard and prevents a few use cases that where working until Docker 1.7 -- would that be considered a regression?

**Comment by mrunalp** [comment]
@icecrime Yes, it will be really good to get the mount propagation PR in. It is blocking a lot of use cases. I am here to help in any way I can to help get it in.

**Comment by icecrime** [comment]
@kelseyhightower Mmm I must be missing pieces of history here, I didn't know we had a behavior change in 1.6.x about this: I'm interested if you can point me to the PR number that introduced it.

**Comment by tiborvass** [comment]
LGTM

**Comment by icecrime** [comment]
Testing docker in docker before merging.

**Comment by icecrime** [comment]
So, I build docker in docker, and tried to run the integration tests in the container itself (so that's docker in docker in docker), and got:

```
FAIL: docker_cli_run_unix_test.go:99: DockerSuite.TestRunContainerWithCgroupParent

docker_cli_run_unix_test.go:130:
    c.Fatalf("unexpected cgroup paths. Expected at least one cgroup path to have prefix %q. Cgroup Paths: %v", expectedCgroupPrefix, cgroupPaths)
```

**Comment by LK4D4** [comment]
We found bug in libcontainer about cgroups setup. It never worked properly, but we didn't notice because of dind.

**Comment by icecrime** [comment]
@LK4D4 So not a blocker for this PR?

**Comment by LK4D4** [comment]
@icecrime dunno, merge won't make things worse than now, but fix definitely should be made.

**Comment by icecrime** [comment]
Alright let's go for it.

**Comment by pmorie** [comment]
@kelseyhightower @icecrime I think the situation Kelsey is referring to is a change to the propagation mode of containers' mnt namespace.  I had originally been under the impression that this was in upstream docker but, it was a patch the we carried that did not go in upstream.  So, there is no regression, but we would really like to be able to control the propagation mode of a container's mnt namespace to enable cases where a container makes a mount point that is visible to other containers on the system.

**Comment by rhatdan** [comment]
Actually the patch was originally merged into the test stream and then dropped just before docker shipped it.

**Comment by pmorie** [comment]
@rhatdan 

My bad, clearly I need to get my history straight.

**Comment by icecrime** [comment]
It still isn't a Docker regression, and we'd appreciate it not being advertised as such.

**Comment by rhatdan** [comment]
I agree this is not a Docker regression.  (Although it is a Docker Shortcoming.)

**Pull request merged**
