### PR TITLE
Make sure that ADD/COPY still populate the cache even if they don't use it

### LINKED ISSUE #9880: docker build --no-cache doesn't update the cache - maybe should?
I have a python-based app which does `pip install -r requirements.txt` and one of the packages has been updated (I'm sure there are lots of other cases where my issue would apply too).

Since the Dockerfile hasn't changed I have to do `docker build --no-cache` to actually get the updated requirement into my image.

That all works fine.  Having built the image once with `--no-cache` to get the updated requirement I would expect that subsequent builds would use this as the base.

But that's not the case... if I now do a `docker build` it reverts to using the old version of the requirement.  It seems that `--no-cache` flag means not only that Docker doesn't use the cached fs layers, but it _doesn't update them_ either.

This is a bit of a nuisance, because I'm now condemned to doing `--no-cache` builds (with lengthy download and compile steps etc) from now on.

I expect there is some workaround to 'clear the cache' etc but it seems to me that `--no-cache` builds should update the cache rather than bypassing it entirely.

### PR DESCRIPTION
**Pull request by duglin**
@anentropic please make sure my new test covers your scenario.
@erikh ping

Closes #9880

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by anentropic** [comment]
the third arg to `buildImageFromContext` is whether to use the cache? Go's not my language but I think I follow it, test logic looks ok to me. (`name2` is not used though?)

Should there be tests for other directives besides `ADD` ? ... just wondered because from your comments on the issue it sounds like maybe the cache logic is different for some directives - you're talking about `ADD`/`COPY` here but I specifically had a problem with `RUN pip install somepackage`

**Comment by erikh** [comment]
RUN uses a different caching strategy.

**Comment by erikh** [comment]
LGTM

**Comment by anentropic** [comment]
Well... it was `RUN` I had the problem with so this doesn't cover my scenario

**Comment by anentropic** [comment]
I.e. shouldn't be marked "Closes #9880" at least as it is at the moment

**Comment by duglin** [comment]
@anentropic I'm confused. In #9880 you said your scenario included a "change content" step - I assumed that was part of an ADD/COPY. If its part of a RUN step can you elaborate on that? I believe the RUN cache will just look at the cmd line to determine if its seen it before, nothing else.

**Comment by anentropic** [comment]
I think my issue is pretty clearly described in #9880

**Comment by duglin** [comment]
Well, I'm not seeing an issue around RUN. My steps are:
1) build with a RUN command
2) build --no-cache same Dockerfile from step 1
3) build again and I see it use the cache from step 2

Shouldn't this show the issue?

$ docker build .
Sending build context to Docker daemon 154.1 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu
 ---> 86ce37374f40
Step 1 : RUN pwd
 ---> Using cache
 ---> ca1e91969134
Successfully built ca1e91969134

$ docker build --no-cache .
Sending build context to Docker daemon 154.1 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu
 ---> 86ce37374f40
Step 1 : RUN pwd
 ---> Running in cc32855b83b0
/
 ---> c7d3513ab019
Removing intermediate container cc32855b83b0
Successfully built c7d3513ab019

$ docker build .
Sending build context to Docker daemon 154.1 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu
 ---> 86ce37374f40
Step 1 : RUN pwd
 ---> Using cache
 ---> c7d3513ab019
Successfully built c7d3513ab019

$ cat Dockerfile
FROM ubuntu
RUN pwd

Notice it used cache c7d3513ab019

**Comment by anentropic** [comment]
hmm, that's not what I'm seeing running under:

```
Boot2Docker version 1.4.1, build master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
Docker version 1.4.1, build 5bc2ff8
```


```
docker build -t myimage .
Step 9 : RUN /home/docker/venv/bin/pip install -r /home/docker/requirements.txt
 ---> Using cache
 ---> bb230588fbb7

docker build -t myimage --no-cache .
 Step 9 : RUN /home/docker/venv/bin/pip install -r /home/docker/requirements.txt
 ---> Running in 35bbdc155e64
 ...
 Cleaning up...
 ---> 4410e5630c81

docker build -t myimage .
Step 9 : RUN /home/docker/venv/bin/pip install -r /home/docker/requirements.txt
 ---> Using cache
 ---> bb230588fbb7
```

note it reverted to the original cache, not the refreshed one

**Comment by anentropic** [comment]
I have a `COPY` step immediately before the `RUN` one... just mentioning in case there could be some interaction there

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by duglin** [comment]
@anentropic what does the COPY step do w.r.t. the cache?

**Pull request merged**
