### PR TITLE
Add bash completion for `dockerd --init` and `docker run|create --init`

### LINKED ISSUE #30263: Missing bash completion for dockerd/docker run --init
1.13.0 release note:
> Add boolean flag --init on dockerd and on docker run to use tini a zombie-reaping init process as PID 1 #26061 #28037

But it looks like this option is missing from the bash completion script:
https://github.com/docker/docker/blob/e91dbba7ff62a92bd395bc419f522fa66618ae7b/contrib/completion/bash/docker#L1733-L1747
https://github.com/docker/docker/blob/e91dbba7ff62a92bd395bc419f522fa66618ae7b/contrib/completion/bash/docker#L1399-L1404

cc @albers

### PR DESCRIPTION
**Pull request by albers**
Fixes #30263 
Please schedule for 1.13.0
ping @sdurrheimer also missing in zsh completion

### CODE REVIEW

**Comment by chanwit** [comment]
thank you @albers :-)
@thaJeztah hopefully this PR will also land to the 1.13 branch :-) :-)

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by chanwit** [comment]
:tada: :tada:

**Pull request merged**
