### PR TITLE
Vendor swarmkit 998a47fb9c2b727c8a48d372309af0b3032051e2

### PR DESCRIPTION
**Pull request by nishanttotla**
Changes in this vendoring:

```
$ git log --no-merges --oneline ae29cf24355ef2106b63884d2f9b0a6406e5a144..998a47fb9c2b727c8a48d372309af0b3032051e2
ca59883 Set packed=false for repeated integer fields
c05903c Vendor gogoprotobuf v0.4
d127e0d dispatcher: Ensure processUpdatesLock is unlocked
f951de9 Add unit test for predefined and swarm node-local networks
6b16b5f Vendoring libnetwork @37e20af
44fa30f Support predefined node networks for services
5507383 Swarm to support node-local networks
9f69874 Better Architecture comparison for Platform filter
950b3d0 Grpc change for network options in service spec
```

### CODE REVIEW

**Comment by nishanttotla** [comment]
cc @aboch

**Comment by nishanttotla** [comment]
CI is failing because libnetwork vendoring needs to be updated first.

**Comment by aaronlehmann** [comment]
Should we close this one in favor of #32981? It vendors the same revision of swarmkit.

Or if #32981 will take awhile, should we pull the libnetwork and gogoprotobuf vendoring into this one?

**Comment by nishanttotla** [comment]
@aaronlehmann #32981 might take a while, though @aboch told me it's due before the freeze.

This current PR has the libnetwork and gogoproto, but CI will continue to fail without the libnetwork changes of #32981. I want to keep this one open just in case it's required at the last minute.

**Comment by nishanttotla** [comment]
Closing this because #32981 will be merged soon.

**Pull request closed without merging**
