### PR TITLE
netns: Update to latest for arm64

### PR DESCRIPTION
**Pull request by glevand**
Update to the latest netns to get build fixes for arm64.

@hqhq: please test

### CODE REVIEW

**Comment by LK4D4** [comment]
@glevand Did you sent PR to libnetwork as well?
LGTM

**Comment by glevand** [comment]
@LK4D4 I did not submit anything to libnetwork.  The problem I had was a build error with netns see: https://github.com/vishvananda/netns/pull/6.

**Comment by LK4D4** [comment]
@glevand Yeah, you should submit to libnetwork too. It's their dependency actually.

**Comment by hqhq** [comment]
@glevand thanks, but all vendor changes should be merged to vendor's own project, and for this problem, we already have a PR: https://github.com/vishvananda/netns/pull/4
And I think SYS_SETNS should be 375 pn ARM64 which in the original PR is right, WDYT?

**Comment by hqhq** [comment]
@glevand Now I see your PR at https://github.com/vishvananda/netns/pull/6, it's vendor of libnetwork, so you should merge to libnetwork first, then merge to Docker.

**Comment by glevand** [comment]
Created PR for libnetwork: https://github.com/docker/libnetwork/pull/335.  Will create new docker request when fix is merged to libnetwork.

**Comment by glevand** [comment]
@LK4D4 My fix was merged to libnetwork (https://github.com/docker/libnetwork/pull/335).  How do I get that into docker?

**Comment by LK4D4** [comment]
@glevand Same way as you wanted.

**Comment by thaJeztah** [comment]
Basically, by updating hack/vendor.sh, running it and creating a pull request. As an example, you can find a pull request that did this here; https://github.com/docker/docker/pull/13899

**Pull request closed without merging**
