### PR TITLE
Moving project to docker/opensource

### PR DESCRIPTION
**Pull request by moxiegirl**
These files will now live in docker/opensource

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by SvenDowideit** [comment]
combines with https://github.com/docker/opensource/pull/21

**Comment by SvenDowideit** [comment]
LGTM

**Comment by thaJeztah** [comment]
@moxiegirl @SvenDowideit should this be in the 1.9 release to prevent having the same content being added twice?

**Comment by moxiegirl** [comment]
@thaJeztah I'm not sure I follow. These files are being moved from `docker/docker` to `docker/opensource` they were deleted here.

**Comment by thaJeztah** [comment]
@moxiegirl if the docs are built from the release branch, they would still be here as well, and if the "docker/opensource" repo is included when building the docs, we may end up having the same files twice (once from the release branch, once from the opensource repo). (If I'm not mistaken)

**Pull request merged**
