### PR TITLE
Enhance 'network inspect' to show PoolID

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Closes-issue #23025 

Signed-off-by: vikaschoudhary16 choudharyvikas16@gmail.com

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
Cc @mavenugo @aboch @icecrime @mrjana @MoBani

**Comment by vikaschoudhary16** [comment]
Related changes in engine-api repo are here in seperate PR, https://github.com/docker/engine-api/pull/247

**Comment by thaJeztah** [comment]
Can you add a second commit that includes the changes you made to engine-api here? That way we can verify/review those changes here, before the engine-api changes are merged. Making those changes here will make the `vendor` check fail, but at least the other tests will pass.

Once the design is approved, and we go to code review, we can merge the engine-api and vendor those changes here.

**Comment by vikaschoudhary16** [comment]
@thaJeztah ,
Done. PTAL

**Comment by thaJeztah** [comment]
oh, looks like there's a test failing;

```
2:24:42 FAIL: docker_cli_network_unix_test.go:643: DockerNetworkSuite.TestDockerNetworkInspectCustomUnspecified
12:24:42 
12:24:42 docker_cli_network_unix_test.go:654:
12:24:42     c.Assert(len(nr.IPAM.Config), checker.Equals, 1)
12:24:42 ... obtained int = 0
12:24:42 ... expected int = 1
12:24:42 
12:25:12 
12:25:12 ----------------------------------------------------------------------
```

**Comment by vikaschoudhary16** [comment]
@thaJeztah ,
Thanks for the response.

It is failing because with these changes length of response has increased and assertion on length is failing. I am planning to adjust test cases, once design is approved by you guys. If your preference is otherwise, please let me know.

**Comment by vikaschoudhary16** [comment]
@aboch ping

**Comment by thaJeztah** [comment]
ping @mavenugo @aboch PTAL!

**Comment by thaJeztah** [comment]
Looking at the discussion in https://github.com/docker/docker/issues/23025, and https://github.com/docker/docker/issues/23025#issuecomment-222290876, I think we should close this; the PoolID is an internal detail, and should just be seen as that, and *ID*, and not to extract information from (the format may change in future)

**Pull request closed without merging**
