### PR TITLE
Support a proxy in splunk log driver

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
Can we check to see if `ProxyFromEnvironment` doesnt return err?

**Comment by thaJeztah** [comment]
I think this is the way it's supposed to be used (also see https://golang.org/pkg/net/http/#ProxyFromEnvironment, and the example on that page)

> A nil URL and nil error are returned if no proxy is defined in the environment, or a proxy should not be used for the given request, as defined by NO_PROXY.

> As a special case, if req.URL.Host is "localhost" (with or without a port number), then a nil URL and nil error will be returned.

So an error is only returned in situations where no proxy should be used (in which case `nil` is returned)

**Comment by thaJeztah** [comment]
PowerPC node has some issues; https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/8278/console

```
17:36:15 Step 6/31 : RUN curl -fsSL "https://golang.org/dl/go${GO_VERSION}.linux-ppc64le.tar.gz" 	| tar -xzC /usr/local
17:36:15  ---> Running in 4abd3531a716
17:36:16 curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
17:36:16 
17:36:16 gzip: stdin: unexpected end of file
17:36:16 tar: Unexpected EOF in archive
17:36:16 tar: Unexpected EOF in archive
17:36:16 tar: Error is not recoverable: exiting now
```

**Review by anusha-ragunathan — APPROVED** [review]

**Review by mavenugo — COMMENTED** [review]
@dnephin can you pls add a test-case ?

**Comment by dnephin** [comment]
Added a unit test.  

I tried adding an integration test using the `NewHTTPEventCollectorMock` mock in this package but that won't work because golang refuses to use a proxy for any localhost/127.x.x.x url (https://github.com/golang/go/blob/release-branch.go1.9/src/net/http/transport.go#L1218-L1225)

Since the rest of this code is part of the stdlib, all we really need to test is that the transport has the correct proxy factory, which is covered by this test.

**Review by thaJeztah — APPROVED** [review]
a unit test sounds sane to me

LGTM

**Review by mavenugo — APPROVED** [review]
Thanks @dnephin . LGTM

**Pull request merged**
