### PR TITLE
To impove friendly of the docs, Add note for Paragraph 'built Docker bin...

### PR DESCRIPTION
**Pull request by zenlint**
...ary' in devenvironment.md.

Add Note for ' <version>' to avoid mistaken using of the command 'sudo cp ./bundles/<version>-dev/binary/docker-<version>-dev $(which docker)'.

when some one use the command line straightforward but without the real version, the issuse should be met.

Acturally, I have worked with the content of docs ,and also use the command line provided in it, maybe some one have made the same mistake as me to use the <versio>  in the comand line directly.

Thus, I add one note to remind others to avoid the same trap, especially to the new hand.

### CODE REVIEW

**Comment by zenlinTechnofreak** [comment]
Thx to GordonTheTurtle , I have made the update according to your remind.
But I wonder should I need to do other jobs about update the pull&request?

**Comment by zenlinTechnofreak** [comment]
Thx to Gordon, my pull request have been tested by Jenkins.
Actrually, I am a new hand in open source work with deep interesting with opensourcework.
So, I have a new question to consult u:
what should I do next step, should I sent a email to the maintainer?
Thx very much for your hlep.

**Comment by estesp** [comment]
At this point you can wait for the documentation maintainers to take a look at your change and provide feedback.  They will use the labels and any tools they use to find all PRs waiting their review, but be patient as they have lots of PRs to review each day!  If it has been a week and you don't have any comments, then you can ping a maintainer to get their attention.

**Comment by zenlinTechnofreak** [comment]
OK，thx to estesp.

**Comment by zenlinTechnofreak** [comment]
@estesp I donnot know why the Jenkins build was failed, It looks like no sign cause the err.
But I have ever sign it again, and after signed, the jekins build sucessed, but it failed again, can u help me to find out what is wrong now? thanks.

**Comment by jfrazelle** [comment]
The first commit is not signed. If you squash all three commits into one and force push that will help.

**Comment by zenlinTechnofreak** [comment]
@jfrazelle OK,thx, I was just done it.thank you.

**Comment by icecrime** [comment]
Sorry @zenlinTechnofreak, your contribution is not yet quite good: we still see 2 commits (one of them being a merge) :-( And I'm afraid it also need rebase.

**Comment by jfrazelle** [comment]
can someone maybe carry this one?

**Comment by jfrazelle** [comment]
actually as I was seeing to carry this, the entire dev docs have been redone by @moxiegirl and are awesome so I think it addresses any questions that the old docs might have left

**Comment by icecrime** [comment]
Sorry, the contributing guide has been entirely rewritten, we're gonna gave to close this.

**Pull request closed without merging**
