### PR TITLE
Etwlogs

### PR DESCRIPTION
**Pull request by cednation**
Signed-off-by: Cedric Davies cedricda@microsoft.com
@jhowardmsft 

Adds an ETW logging driver to Docker on Windows. ETW stands for Event Tracing in Windows, and is the common framework for tracing Windows applications. This log driver forwards each container log message as an ETW event. A client can then create an ETW listener to listen for these events.

A client registers to listen to events from our ETW provider, by specifying our provider's GUID, which is: a3693192-9ed6-46d2-a981-f8226c8363bd. Here is an example of how to listen to these events using the logman utility available in any Windows installation:
1. logman start -ets DockerContainerLogs -p {a3693192-9ed6-46d2-a981-f8226c8363bd} 0 0 -o trace.etl
2. Run your container(s) with the etwlogs driver, by adding --log-driver=etwlogs to the Docker run command, and generate log messages
3. logman stop -ets DockerContainerLogs
4. You can then convert the generated etl file to XML using: tracerpt -y trace.etl

Each ETW event generated will contain a data string in this format:
container_name: %s, image_name: %s, container_id: %s, image_id: %s, source: [stdout | stderr], log: %s

Your ETW listener can then parse this string, to both get the log message generated, as well as its context information, such as which container emitted the log message. The Timestamp is also available within the ETW event.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cednation can you rebase your PR to get rid of the merge commit?

**Comment by cednation** [comment]
@thaJeztah Yes, thanks I will work on that.

**Comment by cednation** [comment]
@thaJeztah I rebased and pushed according to the instructions given by the turtle. Please let me know if I didn't do it correctly.

**Comment by cpuguy83** [comment]
Looks like we've got a bad rebase.

**Comment by cednation** [comment]
@cpuguy83 @thaJeztah Hmmm not sure what I did wrong then or how to fix it. When I try to rebase my branch now, it says it is up to date. I'm very new to Git, so there could be something obvious that I am missing. The easiest thing for me to do now, is probably to start over, close this pull request and open a new one.

**Pull request closed without merging**
