### PR TITLE
[25.0 backport] update to go1.22.6

### PR DESCRIPTION
**Pull request by austinvazquez**
**- What I did**
* Backported https://github.com/moby/moby/pull/48058 to 25.0 as a precursor for the golangci-lint update.
* Backported https://github.com/moby/moby/pull/47743 to 25.0 for Docker on Windows integration testing.
* Backported https://github.com/moby/moby/pull/48300 to 25.0.
* Backported https://github.com/moby/moby/pull/48359 to 25.0 for the golangci-lint update.
* Backported https://github.com/moby/moby/pull/46982 to 25.0.

**- How I did it**

For https://github.com/moby/moby/pull/48058:
```
git cherry-pick -xsS 04bf0e3d693478f8864adc0fd1577ecdbc53aaf1
git cherry-pick -xsS d4160d5aa75100eba75a6099f376ffdf9087e480
git cherry-pick -xsS 95fae036ae8da8a6f25b9cad1a8b192188750338
```

For https://github.com/moby/moby/pull/47743:
```
git cherry-pick -xsS 85c990037767d9556af033715bba57843b4a2e57
git cherry-pick -xsS 2140e7e0f5f47464445182cfa0fb2663ff63f6f8
git cherry-pick -xsS e3c59640d5d15acc54616790bdae5bf0974c505a
```

For https://github.com/moby/moby/pull/48300:
```
git cherry-pick -xsS b24c2e95e57c5927765fa1ff5820576dda6e6242
```

For https://github.com/moby/moby/pull/48359:
```
git cherry-pick -xsS 6bd7835cb6965d8a2a86b0e32d9b44e42f09c7b5
git cherry-pick -xsS c7b36f8953dccc852ba5ea75134d89617c2952aa
git cherry-pick -xsS 2b7a6875548197faf0494fda1029afc15a88e301
git cherry-pick -xsS 3ca38f0b5e4a88b67205003b678474e07ab727ed
git cherry-pick -xsS 6bbacbec269bef3ab39c7614494a9ff504d428a0
git cherry-pick -xsS b79a4696ee45e3f28a5b772cbf0cb33fda000d6c
git cherry-pick -xsS 6008c42ca2903467964c430c0030a29ae4cc858e
git cherry-pick -xsS 06bfe8bab3038b37733d515954301b651b70326e
git cherry-pick -xsS b56c58a8601ab78a940c7e1c8cf5570d142d8abb
git cherry-pick -xsS 81a1ca02175a82911559cc20424d825375eaae98
git cherry-pick -xsS f434cdd14a99c38dc47f55680f624b4bae44e196
git cherry-pick -xsS 068c1bf3be15a41ec79ca6eb822e142f1a9cdc12
git cherry-pick -xsS 4a93233b8830ad5448ed7c848555f9b379b90ed1
git cherry-pick -xsS 0fd3a53c12b703bc636f525fd6364c1e83b3083f
git cherry-pick -xsS 005b488506e7b86cc0ce7a8268a577cb507c7d59
git cherry-pick -xsS 1ad5b5abb2a2eb3525ad175b1b76b6a6aa6ce598
```

For https://github.com/moby/moby/pull/46982:
```
git cherry-pick -xsS e853c093bf8b9b614b187d4571588f30e08d605d
git cherry-pick -xsS 4cd5c2b6435a4cc1afd01c01b85f01dfe9aa4da3
git cherry-pick -xsS 3df59c9dcf0063d8d833215771d1a2c15d9fad03
git cherry-pick -xsS 9b11bb507b37416493ddad926340defbe371e338
git cherry-pick -xsS f5108e9c6bfde83b7774dafaa355b6a413201131
```
resolving conflicts along the way.

**- How to verify it**
Successful CI verification should be enough

**- Description for the changelog**
```markdown changelog
Update toolchain in CI to Go 1.22.6
```

**- A picture of a cute animal (not mandatory but encouraged)**
🐘

### CODE REVIEW

**Comment by austinvazquez** [comment]
Currently looking into if mainline has any change for this or if this is a flaky test in this branch.

```
=== Failed
=== FAIL: libnetwork/networkdb TestNetworkDBCRUDTableEntries (7.80s)
    networkdb_test.go:309: Entry existence verification test failed for node2(04cbb9a29343)
```

**Comment by austinvazquez** [comment]
Likewise for 
```
=== Failed
=== FAIL: amd64.integration.container TestCreateWithCDIDevices (0.91s)
    cdi_test.go:68: assertion failed: [] does not contain FOO=injected
```

**Comment by corhere** [comment]
@austinvazquez the `libnetwork/networkdb` tests are known to be flaky -- on all branches. Don't worry about that one.

The `amd64.integration.container TestCreateWithCDIDevices` failure needs to be looked into. The behaviour which that test covers is supposed to be fully deterministic.

**Comment by austinvazquez** [comment]
Looks like I was missing https://github.com/moby/moby/pull/48058. Also found https://github.com/opencontainers/runc/issues/4384 wrt to the integration test failure for TestCreateWithCDIDevices. I have been working on updating runc in 25.0 in a seperate thread.

**Review by corhere — APPROVED** [review]
LGTM! I'm not too worried about integration-test flakes where the root cause is a bug in runC.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
