### PR TITLE
Add some basic bash completion for seccomp values

### PR DESCRIPTION
**Pull request by tianon**
cc @albers @jfrazelle

### CODE REVIEW

**Comment by tianon** [comment]
My fingers can never spell "unconfined" right for some reason. :innocent:

**Comment by jfrazelle** [comment]
omg this is me and --privilegaskdjfhaslkjdfads

**Comment by jfrazelle** [comment]
LGTM

**Comment by icecrime** [comment]
I totally know what I'm doing, and LGTM.

**Comment by justincormack** [comment]
LGTM

**Pull request merged**
