### PR TITLE
Rename detachKeys queryparam to detach-keys

### PR DESCRIPTION
**Pull request by thaJeztah**
Per https://github.com/docker/docker/pull/19090#issue-124990149, but it's just something I like more so feel free to close

(is based on top of that PR, so I'll rebase if that's merged)

### CODE REVIEW

**Comment by vdemeester** [comment]
As I said in #19090, LGTM 🐹

**Comment by calavera** [comment]
better doing it before it's in a release.

**Comment by calavera** [comment]
what's our convention in other API parameters? we should not change this one if all other parameters are snake case.

**Comment by vdemeester** [comment]
@calavera well, they currently are *anything-case* :stuck_out_tongue_closed_eyes:.

**Comment by thaJeztah** [comment]
@calavera it's a bit of a mish-mash currently; https://github.com/docker/docker/pull/19090#issuecomment-169045833, so feel free to close or merge. We should have a style-guide though, to prevent that in future, and/or to deprecate/change existing ones if needed

**Comment by calavera** [comment]
So far, I cannot see any parameter name with dash, so I think we should not change it. I would not mind to change that ugly `ps_args` to `psArgs` though :laughing:

**Comment by thaJeztah** [comment]
:cry: fair, as said, just a personal preference (I dislike camelcase in URL's). I'll close this for now, we can optionally revisit and change all to be consistent ("in my dreams")

**Pull request closed without merging**
