### PR TITLE
DockerSwarmSuite lock portIndex to work around race

### PR DESCRIPTION
**Pull request by thaJeztah**
see https://github.com/moby/moby/issues/34051#issuecomment-511073471

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Maybe not related to the comment (I think memberlist is different), but seems like it should be locked anyway b/c everything else is.

**Comment by thaJeztah** [comment]
rebased to get the latest fixes in

**Comment by thaJeztah** [comment]
Failure on Windows RS1; haven't seen that one, but could be an issue with the machine being slow?

https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25858/console

```
11:30:09 --- FAIL: TestCopierSlow (0.36s)
11:30:09     copier_test.go:221: failed to exit in time after the copier is closed
11:30:09 FAIL
11:30:09 coverage: 43.0% of statements
```

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
