### PR TITLE
Work in progress commit for issue 1850

### PR DESCRIPTION
**Pull request by selansen**
Signed-off-by: selansen <elango.siva@docker.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like this needs a rebase

**Comment by thaJeztah** [comment]
@selansen looks like you opened this from your "master" branch, and probably changes got lost due to a rebase; is there a different PR for this?

**Comment by selansen** [comment]
Changes already went into main stream with different PR.  I suppose create
PR for Libnetwork and didnt know when I started working on issues.
Its already closed. so we are good , right ?

**Comment by thaJeztah** [comment]
Yup, all good then 👍

**Pull request closed without merging**
