### PR TITLE
Adding dockery as client lib to the docs

### PR DESCRIPTION
**Pull request by lexandro**
I'd like to add a new angular based client lib to the documentation also available as docker image and chrome app

### CODE REVIEW

**Comment by vdemeester** [comment]
@lexandro You have to squash both commit and sign off thes squashed commit :wink:

**Comment by lexandro** [comment]
I wish I could understand what are you talking about :) Could you give me a hint please?

**Comment by vdemeester** [comment]
@lexandro something like this https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/.

In your case probably :

```bash
$ git rebase --interactive HEAD~1
# use squash (see article) for one and edit for another one
$ git commit --ammend --signoff
# To make sure it's signed-off
$ git push -f origin add-dockery-to-client-libs
```

Something like that… :wink:

**Comment by lexandro** [comment]
Challenge accepted.... and done :) thank you for your help. I hope I did it well :)

**Comment by moxiegirl** [comment]
Glad you found it Robert. LGTM

ping @thaJeztah @docker/docs-owners

**Comment by thaJeztah** [comment]
Thanks @lexandro ! LGTM


Note to self; we should get rid of those even/odd css classes and go for `tr:nth-child(even)` selectors, this is too much hassle to maintain. Hm, looking at the new docs skin, I don't even think they are still used.

**Pull request merged**
