### PR TITLE
update containerd client and dependencies to v1.2.0

### PR DESCRIPTION
**Pull request by thaJeztah**
Alternative to https://github.com/moby/moby/pull/38062 / https://github.com/moby/moby/pull/37932

This PR only updates the containerd client to 1.2.0GA, but keeps the runtime (containerd, runc) untouched.

Update containerd client and dependencies to current1.2.0 GA;
Full diffs:

- github.com/containerd/containerd https://github.com/containerd/containerd/compare/0c5f8f63c3368856c320ae8a1c125e703b73b51d...v1.2.0
- github.com/Microsoft/hcsshim https://github.com/Microsoft/hcsshim/compare/v0.7.9…v0.7.12
- github.com/opencontainers/runc https://github.com/opencontainers/runc/compare/a00bf0190895aa465a5fbed0268888e2c8ddfe85...58592df56734acf62e574865fe40b9e53e967910
- github.com/opencontainers/runtime-spec https://github.com/opencontainers/runtime-spec/compare/eba862dc2470385a233c7507392675cbeadf7353...5684b8af48c1ac3b1451fa499724e30e3c20a294
- github.com/containerd/cri https://github.com/containerd/cri/compare/9f39e3289533fc228c5e5fcac0a6dbdd60c6047b...f913714917d2456d7e65a0be84962b1ce8acb487

**- Description for the changelog**

```markdown
* update containerd client and dependencies to v1.2.0
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Let's see if this part goes green, then we can worry about the failures in the other PR's later 😓

**Comment by denismakogon** [comment]
Can you please include the necessary changes for this PR? https://github.com/moby/moby/pull/36720

**Comment by thaJeztah** [comment]
@denismakogon unrelated to these changes; those changes are in SwarmKit, which is unrelated to the runtime

**Review by AkihiroSuda — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
