### PR TITLE
update libnetwork to improve scalabiltiy of bridge network isolation rules

### PR DESCRIPTION
**Pull request by AkihiroSuda**
* docker/libnetwork#2121: Retry other external DNS servers on ServFail
* docker/libnetwork#2125: Fix README flag and expose orphan network peers
* docker/libnetwork#2126: Adding goreport card
* docker/libnetwork#2130: Modify awk to use cut in check_ip_overlap
* docker/libnetwork#2117: [Carry 1534] Improve scalabiltiy of bridge network isolation rules

Full changes: https://github.com/docker/libnetwork/compare/2bf63300c52f5ea61989f85c732f00097d746530...5c1218c956c99f3365711974e300087810c31379

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :cactus:

**Comment by AkihiroSuda** [comment]
NOTE: probably https://github.com/docker/libnetwork/pull/2117 is worth adding to Docker changelog

**Comment by thaJeztah** [comment]
https://github.com/docker/libnetwork/pull/2121 is probably worth adding as well to the change log 👍

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!!

**Pull request merged**
