### PR TITLE
fix deadlock when more than 1 plugin is installed

### PR DESCRIPTION
**Pull request by vieux**
**\- What I did**
Fix plugins restore code when engine starts.

**\- A picture of a cute animal (not mandatory but encouraged)**
4--animal-selfies--151222

Signed-off-by: Victor Vieux vieux@docker.com

### CODE REVIEW

**Comment by vieux** [comment]
ping @tiborvass @anusha-ragunathan

**Comment by crosbymichael** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by anusha-ragunathan** [comment]
@vieux : How did you test the 2 plugin installed case?

**Pull request merged**
