### PR TITLE
[17.03] Update containerd to version 6c463891b1ad274d505ae3bb738e530d1df2b3c7

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

-- 

Cherry Pick of:
 - containerd/containerd#872
 - containerd/containerd#828

Diff:
```diff
diff --git a/supervisor/delete.go b/supervisor/delete.go
index a76ace6..26cf1bb 100644
--- a/supervisor/delete.go
+++ b/supervisor/delete.go
@@ -27,13 +27,14 @@ func (s *Supervisor) delete(t *DeleteTask) error {
                        t.Process.Wait()
                }
                if !t.NoEvent {
-                       execMap := s.getDeleteExecSyncMap(t.ID)
+                       execMap := s.getExecSyncMap(t.ID)
                        go func() {
                                // Wait for all exec processe events to be sent (we seem
                                // to sometimes receive them after the init event)
                                for _, ch := range execMap {
                                        <-ch
                                }
+                               s.deleteExecSyncMap(t.ID)
                                s.notifySubscribers(Event{
                                        Type:      StateExit,
                                        Timestamp: time.Now(),
diff --git a/supervisor/supervisor.go b/supervisor/supervisor.go
index a6700b1..8d8d9f0 100644
--- a/supervisor/supervisor.go
+++ b/supervisor/supervisor.go
@@ -333,8 +333,10 @@ func (s *Supervisor) restore() error {
                        continue
                }
                processes, err := container.Processes()
-               if err != nil {
-                       return err
+               if err != nil || len(processes) == 0 {
+                       logrus.WithFields(logrus.Fields{"error": err, "id": id}).Warnf("containerd: container has no process running,removing state directory.")
+                       os.RemoveAll(filepath.Join(s.stateDir, id))
+                       continue
                }
 
                ContainersCounter.Inc(1)
@@ -437,10 +439,14 @@ func (s *Supervisor) getExecSyncChannel(containerID, pid string) chan struct{} {
        return ch
 }
 
-func (s *Supervisor) getDeleteExecSyncMap(containerID string) map[string]chan struct{} {
+func (s *Supervisor) getExecSyncMap(containerID string) map[string]chan struct{} {
        s.containerExecSyncLock.Lock()
-       chs := s.containerExecSync[containerID]
+       defer s.containerExecSyncLock.Unlock()
+       return s.containerExecSync[containerID]
+}
+
+func (s *Supervisor) deleteExecSyncMap(containerID string) {
+       s.containerExecSyncLock.Lock()
+       defer s.containerExecSyncLock.Unlock()
        delete(s.containerExecSync, containerID)
-       s.containerExecSyncLock.Unlock()
-       return chs
 }
```

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by andrewhsu** [comment]
@mlaventure fyi need to also update `hack/dockerfile/binaries-commits`, #33971

**Comment by mlaventure** [comment]
@andrewhsu oups, true.Thanks, PR incoming!

**Pull request merged**
