### PR TITLE
Use function arguments for route setup.

### PR DESCRIPTION
**Pull request by cpuguy83**
So I was working with some of these routers, and couldn't stand reading `Cancellable` and ended up here.

download

### CODE REVIEW

**Comment by vdemeester** [comment]
@cpuguy83 build failure because of a conflict :sweat_smile:

**Comment by cpuguy83** [comment]
Fixed

**Review by vdemeester — APPROVED** [review]
LGTM 🦁 
/cc @dnephin @aaronlehmann

**Review by dnephin — APPROVED** [review]
LGTM

I like this, much better

**Pull request merged**
