### PR TITLE
Some minor tweaks/refactoring of local volumes

### PR DESCRIPTION
**Pull request by thaJeztah**
Follow-up to https://github.com/moby/moby/pull/34233; (the first commit is from that PR); see individual commits for a description of the changes

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @vdemeester PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by thaJeztah** [comment]
Arf; looks like I didn't use a `%q` somewhere, but a `%s`

```
07:43:44 docker_api_containers_test.go:1990:
07:43:44     c.Assert(err.Error(), checker.Contains, x.msg, check.Commentf("%v", cases[i].config))
07:43:44 ... obtained string = "Error response from daemon: create missing-device-opt: missing required option: device"
07:43:44 ... substring string = "missing required option: \"device\""
07:43:44 ... {   false false false map[] false false false [] [] <nil> false busybox map[]  [] false  [] map[]  <nil> []}
07:43:44 
```

**Comment by thaJeztah** [comment]
Fixed 😇

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
@thaJeztah still something to fix:
```
15:55:12 ----------------------------------------------------------------------
15:55:12 FAIL: docker_api_containers_test.go:1706: DockerSuite.TestContainersAPICreateMountsValidation
15:55:12 
15:55:12 case 0
15:55:12 case 1
15:55:12 case 2
15:55:12 case 3
15:55:12 case 4
15:55:12 case 5
15:55:12 case 6
15:55:12 case 7
15:55:12 case 8
15:55:12 case 9
15:55:12 case 10
15:55:12 docker_api_containers_test.go:1990:
15:55:12     c.Assert(err.Error(), checker.Contains, x.msg, check.Commentf("%v", cases[i].config))
15:55:12 ... obtained string = "Error response from daemon: create missing-device-opt: missing required option: device"
15:55:12 ... substring string = "missing required option: \"device\""
15:55:12 ... {   false false false map[] false false false [] [] <nil> false busybox map[]  [] false  [] map[]  <nil> []}
15:55:12 
15:55:14 
15:55:14 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
Agh. My bad, forgot to update the last commit after rebasing 😊

**Review by vdemeester — APPROVED** [review]
LGTM :tiger: 
/cct @cpuguy83

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
