### PR TITLE
Avoid iptables lock error for endpoint port mapping

### LINKED ISSUE #44331: Run failure due to iptables xtables lock contention
### Description

We're seeing contention in a CI environment where the following message is often encountered leading to failures:

```
Error response from daemon: driver failed programming
external connectivity on endpoint foo
(4ee313e3bf3f375e70c3ee5d00b9000523cb80e5fb29b9ccff565913c74ab6ec):
(iptables failed: iptables -t nat -A POSTROUTING -p tcp -s 172.16.128.7
-d 172.16.128.7 --dport 8081 -j MASQUERADE: Another app is currently
holding the xtables lock. Perhaps you want to use the -w option?
```

The source of that error message is endpoint.sbJoin in libnetwork/endpoint.go. It calls:

```
endpoint.sbJoin
driver.ProgramExternalConnectivity (libnetwork/drivers/bridge/bridge.go)
bridgeNetwork.allocatePorts
bridgeNetwork.allocatePortsInternal
bridgeNetwork.allocatePort
PortMapper.MapRange
PortMapper.AppendForwardingTableEntry
PortMapper.Forward
ChainInfo.Forward
iptable.ProgramRule
iptable.Exist
iptable.exists
iptable.existsRaw
```

`iptable.raw` calls `iptables` with `--wait` if supported, but `iptable.existsRaw` does not. The invocation of iptables in existsRaw has not changed since 2017 but how OSes behave has.

I've created a simple test to determine if iptables locking behavior has changed when calling `iptables -S` which is what is invoked in `iptable.existsRaw()` across several releases of Ubuntu (as we've updated from bionic to focal)

Here is the test file, it takes an exclusive lock and then invokes `iptables -S` with and without `--wait`
```
$ cat flock.test
#!/usr/bin/env bash
set -x

LOCK=/run/xtables.lock

iptables --version
flock --exclusive "${LOCK}" sleep 12 &
sleep 1
time iptables -S
echo Returned: $?
wait
flock --exclusive "${LOCK}" sleep 12 &
sleep 1
time iptables -S -w -W20
echo Returned: $?
```

We can build images for Ubuntu bionic, focal, and jammy to see how this behaves:
```
$ cat Dockerfile
ARG IMAGE
FROM $IMAGE

USER root
COPY flock.test /flock.test
RUN apt update
RUN apt install -y iptables
RUN apt clean

CMD /flock.test
```
```
$ IMAGE_TAGS=("bionic" "focal" "jammy")
$ for IMAGE_TAG in "${IMAGE_TAGS[@]}"; do
  docker build --quiet -t "flock-test:ubuntu-$IMAGE_TAG" \ 
               --build-arg IMAGE="ubuntu:$IMAGE_TAG" . 
  echo Testing flock-test:ubuntu-"$IMAGE_TAG"
  docker run --cap-add=NET_ADMIN  flock-test:ubuntu-"$IMAGE_TAG"
  echo
done
```

**Ubuntu Bionic Behavior**
Summary: iptables waits for the xtables lock without the `--wait` flag and is successful.  Adding `--wait` is also successful but is noisy as it waits for the lock.

```
Testing flock-test:ubuntu-bionic
+ LOCK=/run/xtables.lock
+ iptables --version
iptables v1.6.1
+ sleep 1
+ flock --exclusive /run/xtables.lock sleep 12
+ iptables -S
Another app is currently holding the xtables lock; still -9s 0us time ahead to have a chance to grab the lock...
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

real    0m11.012s
user    0m0.004s
sys     0m0.002s
+ echo Returned: 0
+ wait
Returned: 0
+ sleep 1
+ flock --exclusive /run/xtables.lock sleep 12
+ iptables -S -w -W20
Another app is currently holding the xtables lock; waiting for it to exit...
Another app is currently holding the xtables lock; waiting for it to exit...
Another app is currently holding the xtables lock; waiting for it to exit...

<Hundreds of lines of this>

Another app is currently holding the xtables lock; waiting for it to exit...
Another app is currently holding the xtables lock; waiting for it to exit...
Another app is currently holding the xtables lock; waiting for it to exit...
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

real    0m11.012s
user    0m0.120s
sys     0m0.540s
+ echo Returned: 0
Returned: 0
```

**Ubuntu Focal Behavior**
Summary: Without the `--wait` flag the command returns an error immediately, which is what we have observed.  Adding `--wait` makes this successful.

```
Testing flock-test:ubuntu-focal
+ LOCK=/run/xtables.lock
+ iptables --version
iptables v1.8.4 (legacy)
+ sleep 1
+ flock --exclusive /run/xtables.lock sleep 12
+ iptables -S
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?

real    0m0.003s
user    0m0.003s
sys     0m0.000s
Returned: 4
+ echo Returned: 4
+ wait
+ sleep 1
+ flock --exclusive /run/xtables.lock sleep 12
+ iptables -S -w -W20
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

real    0m11.004s
user    0m0.002s
sys     0m0.007s
Returned: 0
+ echo Returned: 0
```

**Ubuntu Jammy Behavior**
Summary: Without the `--wait` flag the call is successful and returns immediately.  Adding the `--wait` performs the same.

```
Testing flock-test:ubuntu-jammy
+ LOCK=/run/xtables.lock
+ iptables --version
iptables v1.8.7 (nf_tables)
+ sleep 1
+ flock --exclusive /run/xtables.lock sleep 12
+ iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

real    0m0.004s
user    0m0.000s
sys     0m0.004s
+ echo Returned: 0
+ wait
Returned: 0
+ sleep 1
+ flock --exclusive /run/xtables.lock sleep 12
+ iptables -S -w -W20
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

real    0m0.002s
user    0m0.002s
sys     0m0.000s
+ echo Returned: 0
Returned: 0
```

### Reproduce

Concurrent docker runs on Ubuntu Focal can result in failure due to iptables lock contention mapping container ports in the host OS depending on timing.

### Expected behavior

Docker should wait for the iptables lock when looking at the exiting rules to avoid this failure.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.19
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        d85ef84
 Built:             Thu Oct 13 16:46:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.19
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       c964641
  Built:            Thu Oct 13 16:44:47 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 46
  Running: 7
  Paused: 0
  Stopped: 39
 Images: 234
 Server Version: 20.10.19
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-50-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.26GiB
 Name: <redacted>
 ID: <redacted>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: <redacted>
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

The docker info is from my machine running Ubuntu Jammy, not CI where we're running Bionic and running into this issue, sorry.

### PR DESCRIPTION
**Pull request by rcj4747**
Fixes: #44331 Run failure due to iptables xtables lock contention

On Ubuntu Focal the iptables implementation returns immediately with an
error if the xtables lock is held.  This is a change in behavior that
has exposed a latent issue in Docker's implementation.

After moving to Focal hosts in our CI environment, contention on the
iptables xtable lock is leading to the following error message (these
failures are easy to trigger and frequent):

```
  Error response from daemon: driver failed programming
  external connectivity on endpoint foo
  (4ee313e3bf3f375e70c3ee5d00b9000523cb80e5fb29b9ccff565913c74ab6ec):
  (iptables failed: iptables -t nat -A POSTROUTING -p tcp -s 172.16.128.7
  -d 172.16.128.7 --dport 8081 -j MASQUERADE: Another app is currently
  holding the xtables lock. Perhaps you want to use the -w option?
```

The source of that error message is endpoint.sbJoin in
libnetwork/endpoint.go.  It calls:

```
  endpoint.sbJoin
   driver.ProgramExternalConnectivity (libnetwork/drivers/bridge/bridge.go)
    bridgeNetwork.allocatePorts
     bridgeNetwork.allocatePortsInternal
      bridgeNetwork.allocatePort
       PortMapper.MapRange
        PortMapper.AppendForwardingTableEntry
         PortMapper.Forward
          ChainInfo.Forward
           iptable.ProgramRule
            iptable.Exist
             iptable.exists
              iptable.existsRaw
```

`iptable.raw` calls iptables with `--wait` if supported, but
`iptable.existsRaw` does not.  The invocation of iptables in `existsRaw`
has not changed since 2017, but the OS behavior has.  In Ubuntu 20.04
(Focal) the call to `iptables -S` will fail immediately if the lock is
held by another process, this is not the case in earlier (Bionic) or
later (Jammy) releases.

This patch adds the `--wait` option to this invocation of iptable (or
if that is not supported the `bestEffortLock` is used) when listing
existing rules.

Signed-off-by: Robert C Jennings <rcj4747@gmail.com>

**- What I did**
Addressed the iptables lock contention

**- How I did it**
Added the same handling for `iptable.existsRaw` as is found in `iptable.raw`; specifically yhis patch adds the `--wait` option to this invocation of iptable (or if that is not supported the `bestEffortLock` is used) when listing existing rules.

**- How to verify it**
~~On Ubuntu 20.04 (Bionic) you can explicitly take the lock with `flock /run/xtables.lock sleep 60&` and run a container with port mappings.~~  (edit: running flock will block the other iptables calls which wait for the lock, you need contention and timing to recreate)

**- Description for the changelog**
Wait for iptables lock when listing existing rules with bridge networks

### CODE REVIEW

**Comment by rcj4747** [comment]
Local testing shows that this fix for #44331 is incomplete.  With the added `--wait` for `iptable.existsRaw` (which I do believe is needed) we still see failures.

Looking again at the error message I see that this is coming from `iptable.raw` which already had the logic to add the `--wait` arg if `supportsXlock` was true.  Our environment is new enough that this bool should be true and we've validated by running the same test used to set the variable (`iptables --wait -L -n`).  I think the problem is how this is initialized in `iptable.detectIptables`:

```
func detectIptables() {
	path, err := exec.LookPath("iptables")
	if err != nil {
		return
	}
	iptablesPath = path
	path, err = exec.LookPath("ip6tables")
	if err != nil {
		return
	}
	ip6tablesPath = path
	supportsXlock = exec.Command(iptablesPath, "--wait", "-L", "-n").Run() == nil
	mj, mn, mc, err := GetVersion()
	if err != nil {
		logrus.Warnf("Failed to read iptables version: %v", err)
		return
	}
	supportsCOpt = supportsCOption(mj, mn, mc)
```

The code to initialize `ip6tablesPath` was added and if `ip6tables` doesn't exist the rest of the checks for `iptables` command items, including setting `supportsXlock` are not run.  We can fix this by inverting the err check and only setting `ip6tablesPath` if err is nil and then continuing.  This doesn't address the fact that ip6tablesPath being unset will still cause issues if ipv6 rules are added, that should be addressed as a separate issue (to be clear that's not a regression but just a latent issue found by inspection while looking at this issue).

I will test this on Monday in our production environment to confirm my suspicion.

**Comment by thaJeztah** [comment]
Thanks for your PR! I had a quick glance, and changes in the PR looked good; I only wanted to double-check if the `bestEffortLock` could safely be used in this location (I know libnetwork has some fairly "complicated" code flows, so wanted to double check if there's no chance on a deadlock if the same lock is used in other places); from a first check on that, it looked fine though!

For the iptables init; ISTR there was another PR touching that part. Let me see if I can find that one (and why it wasn't merged yet, or perhaps it was, and it made another change).

**Comment by thaJeztah** [comment]
Ah! I think this was the one; https://github.com/moby/moby/pull/43060

It's been a while since I looked at that one, and if there were still remaining changes to be addressed (reviews are always welcome; more eyes never hurt!)

**Comment by thaJeztah** [comment]
@rcj4747 looks like your last two commits are missing a DCO sign-off (which makes CI fail) could you amend those commits? (let me know if you need help with "rebase" / "amend" instructions 👍 )

**Comment by rcj4747** [comment]
@thaJeztah I fixed the commits up with sign-offs but I had pushed them initially before I saw your comment about #43060.  That PR would also seemingly address the issue handled in these last 2 commits.  How would you like to proceed?

**Comment by rcj4747** [comment]
> Thanks for your PR! I had a quick glance, and changes in the PR looked good; I only wanted to double-check if the `bestEffortLock` could safely be used in this location (I know libnetwork has some fairly "complicated" code flows, so wanted to double check if there's no chance on a deadlock if the same lock is used in other places); from a first check on that, it looked fine though!

I did my best to search for this as well and I did not find any chances for deadlock.  It's taken just before the `exec.Command` call to `iptables` and I didn't find usage further up the call chain.

**Comment by thaJeztah** [comment]
No worries! Let's keep them in for now (we can always drop them if we decide  to go for the other PR). Let me try to get more eyes on both to see what direction we'll go.

Might not be Today, but I'll try to get back to this (in case I don't; don't hesitate to give me a `@` ping ❤️ 😂 )

**Comment by thaJeztah** [comment]
(close/reopen to re-trigger (and re-load) github actions)

**Comment by akerouanton** [comment]
Hey @rcj4747, as you discovered the real issue lies in Docker early exiting `detectIptables()` when ip6tables isn't available. Once this got fixed, `--wait` & `-C` flags are detected properly, even if ip6tables isn't available.

As mentioned in my PR (#43060), all distributions supported by Docker are now shipping iptables with `-C` flag. This flag is used in `exists` to check if a given rule exists, and `existsRaw` is used as a fallback (doing substring matching, which is buggy) when `-C` flag isn't available. In my PR I'm getting rid of `existsRaw` because it's now irrelavant.

Same applies to your PR: since you're fixing ip6tables detection in your PR, Docker doesn't enter `existsRaw` anymore :wink:

**Pull request closed without merging**
