### PR TITLE
Call "VolumeDriver.Unmount" during container stop.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
"VolumeDriver.Mount" is being called on container start.
Make the symmetric call on container stop.

Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
cc @cpuguy83 @jhowardmsft

**Comment by cpuguy83** [comment]
LGTM, but would be nice to reconcile these two functions. Not sure why everything in `daemon/archive` is using this "force syscall" option.

**Comment by jhowardmsft** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
@cpuguy83 : Not sure why forceSyscall is set in archive.go. It's been this way since the first version of the file.

**Pull request merged**
