### PR TITLE
[experimental compose/swarm] explain how to make it work on awazon ec2.

### PR DESCRIPTION
**Pull request by docteurklein**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@docteurklein could you sign your commit using the instructions above? Otherwise we won't be able to accept your contribution

**Comment by docteurklein** [comment]
@thaJeztah I just did' thanks for the reminder.

**Comment by thaJeztah** [comment]
@vieux @abronan could you check if this LGTY?

**Comment by thaJeztah** [comment]
ping @vieux @abronan could you have a look?

**Comment by abronan** [comment]
Thanks for the ping @thaJeztah 

LGTM

**Comment by mavenugo** [comment]
@alvinr is also working on exact configuration required to set it up end to end in AWS. He can contribute it here as well.

**Comment by alvinr** [comment]
Here's the port you need to open on EC2 for overlay network driver
Docker Engine / Swarm
- TCP / 2376 / 0.0.0.0
- TCP / 3376 / 0.0.0.0

Consul
- TCP / 8400 / 0.0.0.0
- TCP / 8500 / 0.0.0.0
- UDP / 8600 / 0.0.0.0

Serf
- TCP / 7946 / 0.0.0.0

VxLAN
- UDP / 46354 / 0.0.0.0
Once the following is resolved https://github.com/docker/libnetwork/issues/358#issuecomment-128160349 
- UDP / 4789 / 0.0.0.0

I'm working on a guide for the setup of the VPC on EC2, but if you use the VPC Wizard you are in good shape (don't use the "Create VPC" option unless you want to work out all the config details).

**Comment by thaJeztah** [comment]
@alvinr @abronan thanks for kicking in; if you think this can be merged as-is, feel free to do so. If you think this needs additional changes, could you help @docteurklein making those changes, or create a follow-up PR?

**Comment by thaJeztah** [comment]
ping @abronan @alvinr ^^ https://github.com/docker/docker/pull/14564#issuecomment-128949596

**Comment by cpuguy83** [comment]
@thaJeztah I think this is ok, this was a simple change. If we want to beef this up more we can do another PR.

**Comment by thaJeztah** [comment]
@cpuguy83 yup, agreed. 

LGTM, thanks for your contribution, @docteurklein!

**Pull request merged**
