### PR TITLE
Correct name (right) sort order

### PR DESCRIPTION
**Pull request by xrisfg**
Move "montalcini" to between "mirzakhani" and "moore"

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by tianon — APPROVED** [review]
Great catch, LGTM :+1:

**Comment by tianon** [comment]
(However, this does need a DCO)

**Comment by xrisfg** [comment]
My apologies. I created the PR directly on GitHub. I didn't use a client.

I reviewed the instructions at:
https://github.com/moby/moby/pull/42116/checks?check_run_id=2047631035
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

I'm baffled as to how to synch up with the PR and "fix" it.

I have git bash installed, but the command `gh pr checkout 42116` is invalid.
`$ gh pr checkout 42116`
`bash: gh: command not found`

**Comment by tianon** [comment]
Try something like this:

```console
$ git clone -b patch-1 git@github.com:xrisfg/moby.git # or "https://github.com/xrisfg/moby.git" if you don't have an SSH key configured and would rather type your credentials on the command line
$ cd moby
$ git commit --amend --no-edit --signoff
$ git push --force-with-lease
```

**Comment by xrisfg** [comment]
Thank you! Those were the magic incantations I needed. ;-)

I see at least one of the parallel steps in the Jenkins build failed: `ppc64le`. But that appears unrelated to my change.

https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-42116/2/pipeline/179

**Review by tianon — APPROVED** [review]
LGTM

(CI failures look like the normal ppc64le and s390x flakes)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
