### PR TITLE
Alias container and network packages to stop name clashes 

### LINKED ISSUE #36060: Namespace clash in client.CommonAPIClient interface
A very simple one. When using `gomock` to create a mock of `client.CommonAPIClient` you get the following errors when using the generated mock in a test.

```
// $ mockgen -package mocks -source vendor/github.com/moby/moby/client/interface.go APIClient > mocks/moby.go
// go test
../mocks/moby.go:377:30: container.ContainerUpdateOKBody undefined (type string has no field or method ContainerUpdateOKBody)
../mocks/moby.go:1688:30: container.ContainerUpdateOKBody undefined (type string has no field or method ContainerUpdateOKBody)
``` 

This is because of a namespace clash within `client/interface.go`. You import the name `container` as `"github.com/docker/docker/api/types/container"` and then reuse it as a string in the arguments.

```
==//==
type ContainerAPIClient interface {
	ContainerAttach(ctx context.Context, container string, options types.ContainerAttachOptions) (types.HijackedResponse, error)
==//==
```

Simply renaming `container string` to `containerID string` in all function definitions in this source file fixes the problem.

### PR DESCRIPTION
**Pull request by adampointer**
Fixes #36060 

**- What I did**

Renamed container to containerID in function signatures.

**- How I did it**

With Vim!

**- How to verify it**

Create a mock with mockgen and include in a test.

**- Description for the changelog**

Rename container to containerID to stop clashing when mocked with mockgen

**- A picture of a cute animal (not mandatory but encouraged)**

Denied

### CODE REVIEW

**Comment by adampointer** [comment]
Yes this makes more sense. I will submit a new commit.

**Review by thaJeztah — CHANGES_REQUESTED** [review]
thanks! yes, this change looks good to me: could you squash your commits?

**Comment by adampointer** [comment]
Done. Do I need to do anything else? Sorry its my first time contributing to this project...

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
nope, you should be all set for now: a second review is still needed (we require two "LGTM"s), so if the second reviewer also agrees with this change, we can merge.

The PowerPC CI is currently having some issues (failure is not related to your PR), I'll try if restarting it helps 👍

**Review by dnephin — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
And merged! Thanks for contributing!

**Pull request merged**
