### PR TITLE
[Needs carry for Linux fixes] Windows: Update to latest OCI runtime spec

### PR DESCRIPTION
**Pull request by lowenna**
Updates to the latest OCI runtime spec, moving all out-of-band fields to using the spec version.

Signed-off-by: John Howard <jhoward@microsoft.com>

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Ugh, the process spec has changed too. Need to fix up Linux.

**Comment by jhowardmsft** [comment]
@mlaventure @crosbymichael @tianon Could one of you help me find where what was vendored from `containerd\containerd\runtime` has moved to? It was removed from containerd\containerd via commit e115b52ce2516ead331522c965fab93b62d4041e back in November last year, and this is causing all the Linux compilation issues.. 

Or does someone else have a moby\moby branch in progress to update the docker engine to the latest spec?

**Comment by mlaventure** [comment]
@jhowardmsft that type is just an alias for the oci spec Process type. The version vendored in by `containerd` needs to be updated to use a compatible version of the one you're putting here.

**Comment by thaJeztah** [comment]
ping @mlaventure what's the status on this one?

**Comment by darrenstahlmsft** [comment]
This looks to be fairly out of date now. There have been more OCI changes that will be needed prior to the containerd execution integration for Windows.

I can open a more up-to-date OCI runtime-spec update for Windows if someone is willing to commit to carrying it and adding the Linux changes required.

**Comment by thaJeztah** [comment]
@crosbymichael you're able to assist?

**Comment by mlaventure** [comment]
@darrenstahlmsft I have a PR open to update the specs to the last version used by the`v0.2.x` branch: https://github.com/moby/moby/pull/34356

Would that be enough for you?

I've tried to rebase this branch on top of that, but for some of the changes, I'm not sure how to adapt them correctly for `LCOW`

**Comment by darrenstahlmsft** [comment]
So much has changed since this PR, I've got a new version I'm working on. I should have it ready by EOD. I'll ping you when it's ready.

**Comment by jhowardmsft** [comment]
Closing this as @darrenstahlmsft has a more up to date version

**Pull request closed without merging**
