### PR TITLE
Windows: Don't attempt detach VHD for R/O layers

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

A slightly more targeted than #39290 after debugging why RS1 CI has recently started failing with errors such as below:

```
PASS: docker_api_build_test.go:56: DockerSuite.TestBuildAPIRemoteTarballContext 0.006s

----------------------------------------------------------------------
FAIL: check_test.go:107: DockerSuite.TearDownTest

assertion failed: error is not nil: Error response from daemon: failed to detach VHD: invalid argument: rename D:\CI\CI-539e72f75b\daemon\windowsfilter\139a1ff3ca2768be069edab19e44fe65bd40e8d6fb21d582ab010bf1002b52c1 D:\CI\CI-539e72f75b\daemon\windowsfilter\139a1ff3ca2768be069edab19e44fe65bd40e8d6fb21d582ab010bf1002b52c1-removing: Access is denied.: failed to remove image sha256:97ca0940b5d1f8e41b69d57e5727d502ff222ca56ee6c3b5a5f281be0cd6812f

----------------------------------------------------------------------
PANIC: docker_api_build_test.go:83: DockerSuite.TestBuildAPIRemoteTarballContextWithCustomDockerfile

... Panic: Fixture has panicked (see related PANIC)

----------------------------------------------------------------------
MISS: docker_api_build_test.go:198: DockerSuite.TestBuildAPIUnnormalizedTarPaths
MISS: docker_cli_build_test.go:574: DockerSuite.TestBuildAddAndCopyFileWithWhitespace
MISS: docker_cli_build_test.go:927: DockerSuite.TestBuildAddBadLinks
MISS: docker_cli_build_test.go:1007: DockerSuite.TestBuildAddBadLinksVolume
MISS: docker_cli_build_test.go:2886: DockerSuite.TestBuildAddBrokenTar
```

While the invalid argument could have been ignored, it turns out that we're in a remove path for a read-only layer which is in-use. However, RO layers don't have a sandbox/scratch VHDX, so we shouldn't even be attempting the detach call.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
For completeness, here's the complete stack-trace at a point of failure (with an additional sleep put in for debugging)

```
 0  0x00000000004334e4 in runtime.gopark
    at c:/go/src/runtime/proc.go:302
 1  0x000000000044eace in runtime.goparkunlock
    at c:/go/src/runtime/proc.go:307
 2  0x000000000044eace in time.Sleep
    at c:/go/src/runtime/time.go:105
 3  0x00000000016bd8a2 in github.com/docker/docker/vendor/github.com/Microsoft/go-winio/vhd.DetachVhd
    at c:/go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/vhd/vhd.go:127
 4  0x00000000016f03d7 in github.com/docker/docker/daemon/graphdriver/windows.(*Driver).Remove
    at c:/go/src/github.com/docker/docker/daemon/graphdriver/windows/windows.go:341
 5  0x0000000001019d66 in github.com/docker/docker/layer.(*layerStore).deleteLayer
    at c:/go/src/github.com/docker/docker/layer/layer_store.go:418
 6  0x0000000001019fc5 in github.com/docker/docker/layer.(*layerStore).releaseLayer
    at c:/go/src/github.com/docker/docker/layer/layer_store.go:456
 7  0x000000000101a396 in github.com/docker/docker/layer.(*layerStore).Release
    at c:/go/src/github.com/docker/docker/layer/layer_store.go:485
 8  0x00000000010271af in github.com/docker/docker/image.(*store).Delete
    at c:/go/src/github.com/docker/docker/image/store.go:254
 9  0x000000000112d882 in github.com/docker/docker/daemon/images.(*ImageService).imageDeleteHelper
    at c:/go/src/github.com/docker/docker/daemon/images/image_delete.go:330
10  0x000000000112c241 in github.com/docker/docker/daemon/images.(*ImageService).ImageDelete
    at c:/go/src/github.com/docker/docker/daemon/images/image_delete.go:180
11  0x000000000157d76f in github.com/docker/docker/api/server/router/image.(*imageRouter).deleteImages
    at c:/go/src/github.com/docker/docker/api/server/router/image/image_routes.go:207
12  0x000000000157f2e0 in github.com/docker/docker/api/server/router/image.(*imageRouter).deleteImages-fm
    at c:/go/src/github.com/docker/docker/api/server/router/image/image_routes.go:193
13  0x0000000000f98110 in github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1
    at c:/go/src/github.com/docker/docker/api/server/middleware/experimental.go:26
14  0x0000000000f98772 in github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1
    at c:/go/src/github.com/docker/docker/api/server/middleware/version.go:62
15  0x0000000000aa0904 in github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1
    at c:/go/src/github.com/docker/docker/pkg/authorization/middleware.go:59
16  0x0000000000f977f6 in github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1
    at c:/go/src/github.com/docker/docker/api/server/middleware/debug.go:22
17  0x0000000000fb1b0a in github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1
    at c:/go/src/github.com/docker/docker/api/server/server.go:142
18  0x0000000000732d9b in net/http.HandlerFunc.ServeHTTP
    at c:/go/src/net/http/server.go:1995
19  0x0000000000aacbaa in github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
    at c:/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:212
20  0x0000000000fb0427 in github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP
    at c:/go/src/github.com/docker/docker/api/server/router_swapper.go:29
21  0x000000000073614f in net/http.serverHandler.ServeHTTP
    at c:/go/src/net/http/server.go:2774
22  0x0000000000731d38 in net/http.(*conn).serve
    at c:/go/src/net/http/server.go:1878
23  0x000000000045fa91 in runtime.goexit
    at c:/go/src/runtime/asm_amd64.s:1337
```

**Comment by thaJeztah** [comment]
Any idea what caused it to start failing recently?

**Comment by jhowardmsft** [comment]
@thaJeztah That I am still trying to figure out. However, this fix here is definitely a correct one and there was a genuine bug before. I've really idea why it's only started failing recently and there haven't been more reports of this. But regardless, CI is now green again 😸 

@olljanat FYI

**Comment by olljanat** [comment]
Cool so I got quite near even without possibility to see all debug logs :sunglasses: 

What comes to root cause can you see where that access denied error comes from which makes it ending up to detach logic?

**Comment by jhowardmsft** [comment]
The actual error was an EINVALIDPARAMETER from the virtdisk call into OpenVirtualDisk as the path (to the sandbox) was a non-existent file. I genuinely cannot see a specific PR in the past couple of months which reasonably could have changed the logic here. So I'm currently heading down a road that it's related to a buildkit revendor which has somehow changed timing, and we now end up attempting to remove a RO layer which is still in use when a container hasn't quite shut down. That logically kind of makes sense that it seems to most of the time fail in one of the TestBuild* tests.

**Comment by olljanat** [comment]
OK. Then you most probably want to look also #39193 where I changed the logic in way that layers are first marked as invalid and only then removed which avoid Docker trying to re-use broken layers. CI might still fail as it do not have registry where it can re-download layers (or maybe it even is?) but at least error should be like cannot find image instead of these.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by olljanat** [comment]
Experimental failure is unrelated as this PR only changes Windows graph driver.

**Comment by thaJeztah** [comment]
cool; merging!

**Pull request merged**
