### PR TITLE
Cascading sd_notify call from within the container to systemd

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
Problem: 
Since there is no `systemd` within the container, services using `sd_notify` protocol
for service start-up completion are not able to notify the init system once the service is up and running.

Use-case:
systemd needs to start two services.
a) a backend database like mongoDb, cassandra within a container.
b) an apache front end web server on the host.

systemd should not start apache webserver until the backend database is up and running.

Solution:
if the $NOTIFY_SOCKET is set, then systemd is using sd_notify protocol, and we run this patch.

Once the backend database (mongoDB, cassandra) is up and running, systemd is informed using the following:
a) sd_notify("READY=1",0) call from within the container.
b) "READY=1" is received by docker daemon.
c) "READY=1" is send as a HTTP Response to the docker client.
d) docker client makes the sd_notify("READY=1",0) call to systemd.

Now systemd can start the apache webserver.

**Comment by shishir-a412ed** [comment]
@calavera any updates on the design review ?

**Comment by crosbymichael** [comment]
This is too low level to put in the client at this time.  We are currently looking at alternate client implementations and don't want to hinder higher level concepts that user expect from the docker client.

This is something we cannot merge at this time because its low level and system specific.

**Comment by rhatdan** [comment]
@crosbymichael I have asked @shishir-a412ed to look at trying to implement this using the runc command line.  

IE Use docker create to create a container, and then use runc within the systemd unit file for running the container.  Is that what you are thinking of a way to implement this functionality.  

We also want to get socket activation from systemd unit files to work with containers and are considering a similar approach.

**Pull request closed without merging**
