### PR TITLE
graphdriver: promote overlay2 over aufs

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

**- What I did**
Promote `overlay2` over `aufs`, as `overlay2` recently became matured, although it is not perfect.

**- How I did it**
By updating `daemon/graphdriver/driver_linux.go`

**- How to verify it**

Make sure `overlay2` is preferred over `aufs` by default

**- Description for the changelog**

promote overlay2 over aufs

**- A picture of a cute animal (not mandatory but encouraged)**
penguins

TODO: update https://github.com/docker/docker.github.io/blob/b12ec60faa9612f2b37e09e34faf882e8c3efad7/engine/userguide/storagedriver/selectadriver.md

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@justincormack @dmcgowan @stevvooe @tianon @thaJeztah

**Comment by thaJeztah** [comment]
I think the reason `aufs` was still above `overlay(2)` was that `aufs` is an optional kernel module; on a clean install of, e.g. Ubuntu 16.04, overlay2 will be the default driver. Only if someone explicitly installs the aufs kernel module, aufs will be used instead of overlay 

We _should_ change the install script at get.docker.com to only install that module on older kernels (i.e., kernel 3.13 and ubuntu 14.04)

**Comment by justincormack** [comment]
@thaJeztah people may have that module installed for other reasons, it provides many other modules other than aufs. So I agree with this change, we should prefer the consistent choice of overlay2 where available.

**Comment by justincormack** [comment]
@AkihiroSuda I think I would put aufs above the legacy overlay though

**Comment by AkihiroSuda** [comment]
updated @justincormack

**Comment by tianon** [comment]
I'm definitely +1 -- in my own experience, AUFS has stayed pretty consistent, but `overlay2` has been improving (so much that I can't remember the last time I ran into one of the edge cases).

**Comment by thaJeztah** [comment]
I'm +1 to promoting it, just had my initial concerns over the change in behaviour. Existing installs should not be affected though, because it will detect the existing `aufs` directory, so stick with that driver; it will only switch to overlay if someone nukes `/var/lib/docker`, which should be ok

**Comment by dmcgowan** [comment]
>  we should prefer the consistent choice of overlay2 where available

agreed

+1

**Review by justincormack — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
looks like we're in agreement

LGTM

**Comment by thaJeztah** [comment]
ping @mstanleyjones for checking if the docs need to be updated

**Comment by mstanleyjones** [comment]
@thaJeztah they will, when this lands somewhere. Can you file a docs PR with the relevant version details?

**Comment by thaJeztah** [comment]
@mstanleyjones opened https://github.com/docker/docker.github.io/issues/4141

**Comment by thaJeztah** [comment]
All green - there we go!

**Comment by Silex** [comment]
I just upgraded to `17.09` and I see that overlay2 is the new default. My install still seems to use `aufs`:

```
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 504
 Dirperm1 Supported: true
```

Should I switch to overlay2? what are the pros/cons?

**Comment by thaJeztah** [comment]
@Silex for existing installations, the storage driver that was already in use is kept. Aufs overall is a good choice, and if it works for you, there's no need to switch.

Promoting overlay2 is done because;

- it's supported by default in the mainline kernel (no additional kernel modules are needed)
- on some distros/kernels, aufs is no longer available, which could result in users upgrading their kernel, and no longer being able to get access to their containers/images
- (because of the above); it's supported by (almost) all distributions/platforms that Docker runs on, thus less differences between distributions/platforms
- overlay2 is performant, and has relatively few issues

Downsides of overlay/overlay2: it's not (yet) fully POSIX compliant (see https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#limitations-on-overlayfs-compatibility). There are some corner-cases where this can cause issues; many of them have been resolved though.

Because of the above, we decided picking overlay2 as a _default_ was a good choice. Keep in mind that it's a _default_ - some use cases may be better addressed with a specific storage driver; that's not a decision that can be made automatically, and something that the user can configure (see [Select a storage driver](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/))

**Comment by Silex** [comment]
Thank you for the detailed explanation!

**Pull request merged**
