### PR TITLE
[19.03 backport] seccomp profile updates

### PR DESCRIPTION
**Pull request by thaJeztah**
Backports of:

- https://github.com/moby/moby/pull/39308 Fix seccomp profile for clone syscall
    - based on https://github.com/containerd/containerd/pull/3314
- https://github.com/moby/moby/pull/39936 profiles: Fix file permissions on json files
- https://github.com/moby/moby/pull/40731 seccomp: allow syscall membarrier 
- https://github.com/moby/moby/pull/40929 seccomp: Whitelist `clock_adjtime`
    - fixes https://github.com/moby/moby/issues/40919
- https://github.com/moby/moby/pull/41158 seccomp: allow 'rseq' syscall in default seccomp profile
- https://github.com/moby/moby/pull/41353 Add openat2 and faccessat2 to default seccomp profile

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by Hello71** [comment]
The next release of Alpine Linux includes musl 1.2.2 with faccessat2. Several users have reported issues running make, since it calls eaccess, which musl implements correctly with faccessat2 (glibc instead emulates it, providing inaccurate results). Therefore, we and our users would highly appreciate it if at least the faccessat2 part of this PR could be expedited. Thank you.

**Comment by thaJeztah** [comment]
@Hello71 this is a backport for the orevious release, but these changes are already included in the current docker version (20.10)

**Comment by Hello71** [comment]
yes, I understand. however, many distros and users are still on 19.03, and it would be preferable if we could tell them to upgrade to 19.03.16+ instead of 20.10.

**Comment by Hello71** [comment]
if you want more information on alpine issues and our recommendations for docker users, see https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0 and https://wiki.alpinelinux.org/wiki/Draft_Release_Notes_for_Alpine_3.14.0.

**Comment by stanhu** [comment]
We just ran into this issue. Can these changes be merged soon with a 19.03.16 tag?

**Comment by thaJeztah** [comment]
There are currently no plans to do additional 19.03 releases; if possible, I'd recommend upgrading to 20.10, but if you need the updated profile, you can download the JSON version (from the master branch, or from a specific tag; e.g. https://raw.githubusercontent.com/moby/moby/v20.10.7/profiles/seccomp/default.json, and configure your daemon to use that profile as default in the daemon configuration (`daemon.json` or `--seccomp-profile` flag)

**Comment by thaJeztah** [comment]
I'm closing this PR, as 19.03 has not been maintained for 2 Years, and there are no plans for more 19.03.x patch releases.

**Pull request closed without merging**
