### PR TITLE
add james golick to names generator

### PR DESCRIPTION
**Pull request by jessfraz**
ping @skottler @mrb I want to make sure the description does justice, and I need your help

### CODE REVIEW

**Comment by skottler** [comment]
> // James Golick, All around ganster.

Let's use his own bio :P

**Comment by skottler** [comment]
cc @ice799 @armandocanals @capotej

**Comment by mrb** [comment]
Love this.

**Comment by mrtazz** [comment]
❤️

**Comment by capotej** [comment]
:100:

**Comment by artgon** [comment]
:raised_hands:

**Comment by calavera** [comment]
Dope.

**Comment by thaJeztah** [comment]
looks like I need to update my "LGTM" aliases :innocent:

**Pull request merged**
