### PR TITLE
[Fix 15518] wrong feature description in changelog

### LINKED ISSUE #15518: 1.8.0 release notes document undefined option `--dangling`
In https://github.com/docker/docker/releases/tag/v1.8.0, section "Bug Fixes":

>Make `docker rmi --dangling` safe when pulling

```shell
$ docker rmi --dangling
flag provided but not defined: --dangling
See 'docker rmi --help'.
```

### PR DESCRIPTION
**Pull request by albers**
Fixes #15518

If this is accepted, someone should update the release notes.

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by moxiegirl** [comment]
Thanks @albers LGTM

**Comment by thaJeztah** [comment]
LGTM, thanks!

@moxiegirl do you know if there are "rules" for editing the release notes on the releases page? Was thinking of some other changes recently, but wasn't sure who is allowed to do so

**Comment by moxiegirl** [comment]
@thaJeztah  The engineer's own that page, ask on maintainers for that.  I don't know off the top of my head.

**Pull request merged**
