### PR TITLE
Extra v1.25 in API docs

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Not sure how they got in there. @thaJeztah & @vieux  Should this go into the 1.13 release too?

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Added cherry pick, not sure if this was needing to be pulled into the 1.13 branch.

**Comment by thaJeztah** [comment]
Thanks @jhowardmsft!

**Pull request merged**
