### PR TITLE
Remove the Require on the socket for the rpm

### PR DESCRIPTION
**Pull request by crosbymichael**
Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
LGTM. Before this fix, installing rpm on RHEL fails to start docker.service. After this fix, it starts fine.

**Comment by ernestgwilsonii** [comment]
Before this fix, installs on CentOS7 fail to start with error:
Failed to start docker.service: Unit docker.socket failed to load: No such file or directory

**Comment by crosbymichael** [comment]
@ernestgwilsonii yes, should be all good after this fix.  thanks for checking

**Comment by daikaixian** [comment]
same issue.
what should i do?

**Comment by justincormack** [comment]
@daikaixian this is merged for 1.12.0 which will be out on Thursday.

**Comment by bmoo** [comment]
docker-engine-1.12.0-1.el7.centos.x86_64 still has this issue in it. Could we get a fix?

**Comment by thaJeztah** [comment]
@bmoo did your unit file contain changes? In that case it's possible that yum/dnf didn't replace it with the unit-file from 1.12

**Comment by bmoo** [comment]
Oops. I was overwriting the file with an ansible script. The RPM is fine

**Comment by thaJeztah** [comment]
Thanks @bmoo !

**Comment by djleeam** [comment]
Sorry if this is the wrong place, but I notice that docker-machine (v0.8.0) create with the generic driver running against a Centos 7 host is adding back the "Requires=docker.socket" flag...

```
About to run SSH command:
printf %s "[Unit]
Description=Docker Application Container Engine
After=network.target docker.socket
Requires=docker.socket

[Service]
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic 
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=
" | sudo tee /etc/systemd/system/docker.service
```

**Comment by thaJeztah** [comment]
@djleeam can you open an issue in the docker machine issue tracker, and refer to this issue? https://github.com/docker/machine/issues

**Comment by nathanleclaire** [comment]
Might be best to just piggyback on https://github.com/docker/machine/issues/2795#issuecomment-236156423 which I think was originally a slightly different issue but is still open and where I've been tracking this.

**Pull request merged**
