### PR TITLE
Be explicit about github.com prefix being a legacy feature

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/moby/moby/issues/37173 and https://github.com/moby/moby/pull/30412

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @AkihiroSuda @vdemeester

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
Flaky test on experimental 

```
FAIL: docker_api_swarm_test.go:296: DockerSwarmSuite.TestAPISwarmLeaderElection
02:01:40 
02:01:40 [dd363de2111e3] waiting for daemon to start
02:01:40 [dd363de2111e3] daemon started
02:01:40 
02:01:40 [d00ce333c1554] waiting for daemon to start
02:01:40 [d00ce333c1554] daemon started
02:01:40 
02:01:40 [d921d05690125] waiting for daemon to start
02:01:40 [d921d05690125] daemon started
02:01:40 
02:01:40 [dd363de2111e3] exiting daemon
02:01:40 assertion failed: error is not nil: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded
02:01:40 [d00ce333c1554] exiting daemon
02:01:40 [d921d05690125] exiting daemon
02:02:04

**Comment by vdemeester** [comment]
Same flakyness, I'll go ahead and merge.

**Pull request merged**
