### PR TITLE
quota: Make package compile when `cgo` is disabled

### PR DESCRIPTION
**Pull request by pete-woods**
**- What I did**
Writing a plugin that imports the `overlay2` package.

**- How I did it**
Simply import the `overlay2` (or transitive `quota`) package on non-Linux or Linux without CGo.

**- How to verify it**
You will you get this error:
```
# github.com/docker/docker/quota
../.go_workspace/pkg/mod/github.com/docker/docker@v20.10.8+incompatible/quota/testhelpers.go:100:24: undefined: makeBackingFsDev
```

Backporting this to the `20.10.x` series would be very much appreciated, as we can't compile our plug-in any more without unpleasant hacks at the moment.

**- Description for the changelog**
Add missing `makeBackingFsDev` to "unsupported" functions in `quota` package.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
I actually now recalled there was another PR to fix this, which is on master only, so not in 20.10.8; https://github.com/moby/moby/pull/42172. @pete-woods do you see the same issue when using the code from master?

**Comment by pete-woods** [comment]
@thaJeztah - Ah yes, the fix on master works.

We're trying to use a stable / released version, however, so a backport of this fix would still be most appreciated 🙇

**Comment by thaJeztah** [comment]
ok, thanks! let me close this one, as the other fix already works for master 😅

**Comment by pete-woods** [comment]
`20.10` backport PR created here, instead: https://github.com/moby/moby/pull/42869

**Pull request closed without merging**
