### PR TITLE
Don't use init() to set unpigz path

### LINKED ISSUE #40927: How to check if pigz is used?
**Description**

I realize that docker should be using pigz by default if it exists, but I can't seem to figure out how to make sure that it is indeed being used. Verbose logging doesn't seem to log anythign either.

**Steps to reproduce the issue:**
1. Make sure you have pigz installed
2. `docker pull ubuntu`

**Describe the results you received:**

```
$ time docker --log-level debug pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
d51af753c3d3: Pull complete
fc878cd0a91c: Pull complete
6154df8ff988: Pull complete
fee5db0ff82f: Pull complete
Digest: sha256:747d2dbbaaee995098c9792d99bd333c6783ce56150d1b11e333bbceed5c54d7
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest

real	0m16.321s
user	0m0.088s
sys	0m0.177s
```

```
$ time MOBY_DISABLE_PIGZ=1 docker --log-level debug pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
d51af753c3d3: Pull complete
fc878cd0a91c: Pull complete
6154df8ff988: Pull complete
fee5db0ff82f: Pull complete
Digest: sha256:747d2dbbaaee995098c9792d99bd333c6783ce56150d1b11e333bbceed5c54d7
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest

real	0m16.537s
user	0m0.074s
sys	0m0.060s
```

**Describe the results you expected:**

The first command should be faster.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 983.5MiB
 Name: docker-desktop
 ID: PZJ6:QNT6:KC5D:TLAS:XJEX:QVKX:5DJ5:OCGG:RFUN:PUQA:AYXS:RXOU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 33
  Goroutines: 49
  System Time: 2020-05-07T20:24:48.641167554Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Macbook, Also tried in GCE

### PR DESCRIPTION
**Pull request by cpuguy83**
`func init()` is evil here, and the logrus calls are being made before
the logger is even setup.
It also means in order to use pigz you have to restart the daemon.

Instead this takes a small hit and resolves pigz on each extraction.
In the grand scheme of decompressing this is a very small hit.

Closes #40927

### CODE REVIEW

**Comment by cpuguy83** [comment]
Alternatively we could set the path lazily, but then we need to lock on each invocation, and have to restart the daemon to get the daemon to use/not use pigz.

**Comment by thaJeztah** [comment]
Could we re-run it on `SIGHUP`? We already use that to reload "live reloadable" configuration options.

Wondering though if that would update env vars 🤔if it's running as a systemd unit

**Review by AkihiroSuda — APPROVED** [review]

**Comment by cpuguy83** [comment]
We have to somehow tell it to reload which is painful.
Also no, you can't update a process's env vars except from inside the process.

**Comment by thaJeztah** [comment]
> Also no, you can't update a process's env vars except from inside the process.

Yes, so reason I asked was that we now check for the location each time, but also look for the `MOBY_DISABLE_PIGZ ` environment variable. Effectively, the location of the `unpigz` binary could change (and we would update accordingly), but changes to `MOBY_DISABLE_PIGZ` wouldn't be picked up, so we're only _partially_ updating the configuration.

Hence I was wondering if we could make it lookup on `SIGHUP` (which https://github.com/moby/moby/pull/22446 provides a way to do using `systemctl reload docker` when running as a systemd unit)

**Comment by cpuguy83** [comment]
The problem is `MOBY_DISABLE_PIGZ` can't be changed, there's no way to signal this to happen.

**Comment by cpuguy83** [comment]
Ping @thaJeztah

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
CI is gone; let me try if closing/reopening triggers it again

**Pull request merged**
