### PR TITLE
Vendor new swarmkit and etcd/raft

### PR DESCRIPTION
**Pull request by aaronlehmann**
This brings in a much newer version of etcd/raft.

An unrelated change in swarmkit should fix some problems with
integration tests on ARM.

cc @tonistiigi

### CODE REVIEW

**Comment by tonistiigi** [comment]
Comparing to https://github.com/coreos/etcd/blob/06e2338108fdc694349aed923f4a7e45cf0cec1f/cmd/Godeps/Godeps.json version for `github.com/coreos/pkg` seems to have been updated also.

**Comment by aaronlehmann** [comment]
Updated `pkg` as well.

**Comment by tonistiigi** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :cat:

**Pull request merged**
