### PR TITLE
update docker swarm cli

### PR DESCRIPTION
**Pull request by sfsmithcha**
Update `docker swarm` cli ref

Signed-off-by: Charles Smith charles.smith@docker.com

### CODE REVIEW

**Comment by sfsmithcha** [comment]
ping @thaJeztah @icecrime

**Comment by vieux** [comment]
SGTM but doc fail

**Comment by sfsmithcha** [comment]
doc fail unrelated to this commit. @londoncalling working on fix for

```
* link error: (in page engine/getstarted/last_page.md) /docker-for-mac/index.md
* link error: (in page engine/getstarted/step_one.md) /docker-for-mac/index.md
* link error: (in page engine/getstarted/last_page.md) /docker-for-mac/index.md
* link error: (in page engine/getstarted/step_one.md) /docker-for-windows/index.md
```

**Comment by thaJeztah** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐹

**Pull request merged**
