### PR TITLE
docs: add See Also for description of login/logout and start/stop

### PR DESCRIPTION
**Pull request by chenhanxiao**
make them reference to each other.

Signed-off-by: Chen Hanxiao chenhanxiao@cn.fujitsu.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Nice! I think we could use the same for `docker export/import` and `docker save/load`, because there are many people mixing those up.

(Not necessarily in this PR)

**Comment by chenhanxiao** [comment]
@thaJeztah 

Sure, I'll do that in another PR when not busy.

**Comment by thaJeztah** [comment]
great!

**Comment by SvenDowideit** [comment]
LGTM - @fredlf @jamtur01 @spf13 @moxiegirl

**Comment by fredlf** [comment]
LGTM

**Pull request merged**
