### PR TITLE
Move api/errors/ to errors/

### PR DESCRIPTION
**Pull request by duglin**
Per @calavera's suggestion: https://github.com/docker/docker/pull/16355#issuecomment-141139220

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
cannot unsee `derr` as `derp`
but LGTM as long as janky is happy !

**Comment by duglin** [comment]
LOL

**Comment by duglin** [comment]
ping @calavera

**Comment by mountkin** [comment]
Hello, @duglin  would it be better if we separate the multiple words in the `Value` field with  '_'?  
I think `NO_SUCH_CONTAINER` is more readable than `NOSUCHCONTAINER`. WDYT?

**Comment by HuKeping** [comment]
+1 for `NO_SUCH_CONTAINER`, it's more clear.

**Comment by duglin** [comment]
@mountkin its an interesting question... since its unrelated to this specific PR we won't hold it for it, but give me a little time to respond, just swamped right now.

**Comment by estesp** [comment]
LGTM

**Pull request merged**
