### PR TITLE
Updates to bash completion

### PR DESCRIPTION
**Pull request by albers**
This should update bash completion to the current state of the `docker` command - yeah!
ping @jfrazelle @tianon

### CODE REVIEW

**Comment by tianon** [comment]
You are a gem, @albers. :heart:

LGTM

**Comment by tianon** [comment]
(also, this is very large -- you've clearly spent a lot of time on it :+1:)

**Comment by albers** [comment]
@tianon Thanks, you are always so encouraging. I't fun to collaborate with you. And Jessie as well, of course!

**Comment by jfrazelle** [comment]
LGTM, thanks @albers

**Pull request merged**
