### PR TITLE
Adds Docker Image v1 Spec Documention

### PR DESCRIPTION
**Pull request by jlhawn**
Docker-DCO-1.1-Signed-off-by: Josh Hawn josh.hawn@docker.com (github: jlhawn)

### CODE REVIEW

**Comment by mmdriley** [comment]
lgtm. No doubt there are still nits to be picked, but this is a great step forward in unambiguously-described behavior. Thanks for your time and effort in compiling it.

**Comment by crosbymichael** [comment]
@jlhawn Any more edits remaining?

There is no reason for shykes to look at this if you are just documenting the reality of the current system.

**Comment by shykes** [comment]
Correct, if we're documenting today's design don't feel obligated to wait for my +1

**Comment by jlhawn** [comment]
@crosbymichael I think I just need to add in the `User` field description from @tianon and we're set!

**Comment by bfirsh** [comment]
This is brilliant. Thanks @jlhawn. I'm really glad we're taking steps towards specifying how Docker works.

Perhaps we could this in for Docker 1.5 and shout about it a bit. ^_^

**Comment by jfrazelle** [comment]
I don't know what we are waiting on @jlhawn

**Comment by jfrazelle** [comment]
Maybe just a squash of commits?

**Comment by jlhawn** [comment]
@jfrazelle All squashed!

**Comment by jfrazelle** [comment]
awesome!

**Comment by thaJeztah** [comment]
Thanks @jlhawn!

**Comment by odino** [comment]
I was talking to @shykes about this at the dockercon in amsterdam...great job guys!

**Pull request merged**
