### PR TITLE
Cherry-pick : Fixing a couple of network plugin life-cycle mgmt issues

### PR DESCRIPTION
**Pull request by mavenugo**
Cherry-picking https://github.com/docker/docker/pull/29556

### CODE REVIEW

**Comment by vieux** [comment]
@mavenugo doesn't compile

**Comment by mavenugo** [comment]
@vieux yes. we also need to cherry-pick https://github.com/docker/docker/pull/29665. I will take care of it.

**Comment by vieux** [comment]
@mavenugo windows error related ?

**Comment by vieux** [comment]
ping @tiborvass 

LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
@mavenugo looks like this was not a 1-on-1 cherry pick of https://github.com/docker/docker/pull/29556, but also contains changes that are in https://github.com/docker/docker/pull/29891/, correct?

**Comment by mavenugo** [comment]
@thaJeztah the cherry-pick for 1.13.0 branch in docker must come from libnetwork v0.9 branch and yes, by the time this vendoring happened we got 1 additional patch from #29891

**Pull request merged**
