### PR TITLE
[20.10] Backport fixes for kill/stop handling

### PR DESCRIPTION
**Pull request by cpuguy83**
bed624fdc9f117cf8d0dce58024f6304caf9bde9 - https://github.com/moby/moby/pull/41588 Fix infinite wait in kill behavior (fixes https://github.com/moby/moby/issues/41587)
a4bcd4c64f310e9eabdcb5df1e186529d730ffab - https://github.com/moby/moby/pull/41586 Fix stop hanging forever, including infinite wait (fixes https://github.com/moby/moby/issues/41579)
3285c275033a361f237148e0ce611cb72bebccd9 - https://github.com/moby/moby/pull/42488 Fix log statement

Opening this up for discussion.
It is kind of a big change that could get us into trouble.
I did have someone from MSFT request that this be fixed since we ran into it in some case.

/cc @sparrc

### CODE REVIEW

**Review by samuelkarp — APPROVED** [review]
LGTM

FWIW, we're shipping backports of https://github.com/moby/moby/pull/41586 and https://github.com/moby/moby/pull/41588 in the Amazon Linux package of Docker already, since those PRs were directly motivated by issues our customers ran into.

Somewhat related: we (Amazon Linux) ship a few more backports as well.  I'd be happy to open upstream PRs for these if we (Moby maintainers) are comfortable shipping them to everyone.  (If anyone is curious, you can grab the SRPM with `yumdownloader --source docker` to see what we ship for Amazon Linux.)

**Review by tianon — APPROVED** [review]
LGTM -- IMO any bugfixes that are affecting folks and aren't too intrusive to backport are totally reasonable :sweat_smile:

**Comment by thaJeztah** [comment]
> It is kind of a big change that could get us into trouble.

So, for 20.10.10, I at least would like to have https://github.com/moby/moby/pull/42836. If we consider this PR to be "too risky", we _could_ consider doing a 20.10.11 shortly after 20.10.10 (which would give a "fallback" in case 20.10.11 explodes).

> Somewhat related: we (Amazon Linux) ship a few more backports as well. I'd be happy to open upstream PRs for these if we (Moby maintainers) are comfortable shipping them to everyone

In general, I would (personally) say; yes, please do!

Slightly more detailed response: we should include important bugfixes in patch releases; what's "important" is of course a very grey area, but would partially be based on reports of _real life_ issues that users ran into. AWS, Azure, Docker may all get such reports individually, so if backports are done in this (upstream) repository, at least it helps each of us having to discover those issues (and maintaining our own set of patches). I don't think there's any benefit in "but it worked on _my_ `dockerd`" for any of us.

Of course, there may be cases where a particular bug hits AWS, or Azure, or Docker differently, and fixing the bug may not outweigh the risk involved, but that's where have code review for (and raising a :-1: "this is too risky!!" should be fine for these cases).

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
