### PR TITLE
test: Remove DOCKER_ENGINE_GOARCH from the tests

### PR DESCRIPTION
**Pull request by rumpl**
**- What I did**

Instead of looking at the `DOCKER_ENGINE_GOARCH` env var that's not even plumbed down to the tests we use the daemon version info from `testEnv`

**- How I did it**

...

**- How to verify it**

Run the `TestPluginLogDriver` test on an AMD64 machine, it should now run and not be skipped.

On the CI,

Before:

```
=== RUN   TestDockerCLIPluginLogDriverSuite
=== RUN   TestDockerCLIPluginLogDriverSuite/TestPluginLogDriver
    docker_cli_plugins_logdriver_test.go:25: unmatched requirement IsAmd64
=== RUN   TestDockerCLIPluginLogDriverSuite/TestPluginLogDriverInfoList
    docker_cli_plugins_logdriver_test.go:45: unmatched requirement IsAmd64
--- PASS: TestDockerCLIPluginLogDriverSuite (0.01s)
    --- SKIP: TestDockerCLIPluginLogDriverSuite/TestPluginLogDriver (0.00s)
    --- SKIP: TestDockerCLIPluginLogDriverSuite/TestPluginLogDriverInfoList (0.00s)
PASS
```

After:

```
=== RUN   TestDockerCLIPluginLogDriverSuite
=== RUN   TestDockerCLIPluginLogDriverSuite/TestPluginLogDriver
=== RUN   TestDockerCLIPluginLogDriverSuite/TestPluginLogDriverInfoList
--- PASS: TestDockerCLIPluginLogDriverSuite (10.64s)
    --- PASS: TestDockerCLIPluginLogDriverSuite/TestPluginLogDriver (5.65s)
    --- PASS: TestDockerCLIPluginLogDriverSuite/TestPluginLogDriverInfoList (4.99s)
PASS
```

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by rumpl** [comment]
> Wondering if we should fix these checks without the environment variable.

Ha! Even better, we just have to do a dance to convert x86_64 returned by `docker info` to `amd64` returned by `docker version`

**Comment by thaJeztah** [comment]
Oh... doesn't it return `amd64` already?

On x86

```bash
docker version -f '{{.Server.Arch}}'
amd64
```

On arm64

```bash
docker version -f '{{.Server.Arch}}'
arm64
```

**Comment by rumpl** [comment]
Yes but `testEnv.DaemonInfo.Architecture` contains the response from `docker info` which returns `x86_64` or `aarch64`

**Comment by thaJeztah** [comment]
DOH! Ah yes, forgot about that silly thing in `docker info`. I guess for our purpose, converting these values would still work (for now). We should revisit that field though. I recall we already had discussion about it at the time.

**Comment by rumpl** [comment]
@thaJeztah I updated this PR, I had to keep the `DOCKER_ENGINE_GOARCH` because it's used in some util scripts, but I removed its usage from our tests. There is one last piece where it's used:

https://github.com/moby/moby/blob/a74f1ab423146608230dce2c3538782aa2dc1725/testutil/fakestorage/fixtures.go#L42

But here it's passed to `go build` so we kinda need it, I guess?

**Comment by thaJeztah** [comment]
> But here it's passed to go build so we kinda need it, I guess?

Had a quick look it looks like that's building as part of a test-utility; (`ensureHTTPServerImage()`), which is called from `newRemoteFileServer()`, which gets passed the `testtEnv.Client()`.

So I _think_ we would be able to either use that client to get the daemon's platform, or pass it in.

**Comment by rumpl** [comment]
Thinking about this and I kinda want to revert all the “don’t use env var” commits. The env var is already used in shell scripts, might as well use the same in tests. 

I’ll look to remove it from that last go place tomorrow though but it will still need to be there for those shell scripts. 

Maybe there is a way to remove it from there too but I only wanted to make it so that some of the skipped tests are no longer skipped. Scope creep got me good here

**Comment by rumpl** [comment]
@thaJeztah I changed this PR a bit, it not only removes the env var from the tests, I'll open a second one to remove the env var and the by-platform timeout that doesn't seem to do anything

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
