### PR TITLE
Update field name

### PR DESCRIPTION
**Pull request by pradipd**
**- What I did**
1. vendor swarmkit 941a01844b89c56aa61086fecb167ab3af1de22b
2. Updated moby to correspond to API changes made in swarmkit.

**- How I did it**

**- How to verify it**
make test-unit
make test-integration

**- Description for the changelog**
Update moby to correspond to API name changes made in swarmkit.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by pradipd** [comment]
@stevvooe

**Comment by pradipd** [comment]
@stevvooe here are the corresponding moby changes for https://github.com/docker/swarmkit/commit/a3eac7370f744e4273bef620a357c6363dae3b5f

**Comment by thaJeztah** [comment]
z failure is unrelated (`DockerSuite.TestUpdateKernelMemoryUninitialized`) https://github.com/moby/moby/issues/34938

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
