### PR TITLE
Fix Windows support in .vendor-helpers.sh

### PR DESCRIPTION
**Pull request by tianon**
@jhowardmsft wanna test and see if this fixes your issue? :smile:

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@tianon - A lot closer - first part works now. 
vendor

**Comment by cpuguy83** [comment]
What's up with this one?

**Comment by LK4D4** [comment]
@tianon @jhowardmsft What's up?

**Comment by jhowardmsft** [comment]
It was an attempt to get vendor.sh running on Windows. It still needs more work - the pruning code doesn't work

**Comment by tiborvass** [comment]
Ping @jhowardmsft @tianon

**Comment by jhowardmsft** [comment]
Let's close this for now. I'll ping @tianon offline to see if I can get vendor.sh back working again on Windows.

**Comment by tiborvass** [comment]
@jhowardmsft you made my day: i wanted to go below 120 opened PRs, and by closing this I'll reach 119! <3

**Comment by jhowardmsft** [comment]
I'm aiming for commit 100 lol

**Pull request closed without merging**
