### PR TITLE
Improve build speed

### PR DESCRIPTION
**Pull request by anandkumarpatel**
adds speed improvement to all build steps following a build step that misses cache

Signed-off-by: Anandkumar Patel anandkumarpatel@gmail.com

### CODE REVIEW

**Comment by anandkumarpatel** [comment]
@GordonTheTurtle  done

**Comment by duglin** [comment]
I'm a bit tired so hopefully this will make sense :-)  but this makes me a little nervous.  While I agree that the net result should be the same, I'm not sure we want to modify this flag. I think there's value in knowing what the client specified w.r.t. the options they want used.  By modifying this flag 1/2 through our build process its possible that if we ever add code that is based on what the user originally set  then we've now lost this information.

In some ways I would almost prefer if there was a flag in the builder to indicate if we've busted the cache, and then skip the cache check if so.  Then we have the client's original intent as well as our current cache checking state.  But I need to ponder this more...

**Comment by LK4D4** [comment]
@duglin Also I noticed that in `runContextCommand` we use `hit && b.UtilizeCache` which is redundant because if `b.UtilizeCache == false` then `hit == false` too. Actually we can even skip `probeCache` if `b.UtilizeCache == false`.

**Comment by duglin** [comment]
@lk4d4 I agree, I noticed that too while I was reviewing the code.  There are some clean-up things we can do even if we don't twiddle the UtilizeCache flag.

**Comment by anandkumarpatel** [comment]
@duglin I can create a new flag called `cacheBusted` with no problem.  I reused `UtilizeCache` since it was already in the code. I think it would be better to save user input in a new flag something like `UserNoCache` (cant think of anything else atm) to keep track of if the user busted cache or not and use `UtilizeCache` as a flag to use cache or not

**Comment by anandkumarpatel** [comment]
@LK4D4 will make that change tomorrow as well

**Comment by cpuguy83** [comment]
So, I was just looking at this code the other day and implemented what I would have expected to be something that was at least a little faster.
Basically instead of mucking with `b.UtilizeCache`, on a cache miss we'd set a new field called `b.cacheBusted`, and check at the beginning of `probeCache` for `if !b.UtilizeCache || b.cacheBusted { return false, nil }`.

Totally expected a speedup here, but after several tests there was no real improvement (tested with go's Benchmark and just on the cli level with `time <make test cmd>`.... so I did not bother submitting.
Are you able to measure an actual difference with this?

**Comment by cpuguy83** [comment]
Here's the gist of what I'd done here: https://github.com/cpuguy83/docker/compare/docker:master...cpuguy83:set_cache_bust_field?expand=1

Tested with loading several images (probably 100+ layers or so loaded up).

**Comment by duglin** [comment]
@cpuguy83 yep - that's the exact type of new flag I was thinking we could look at adding.

**Comment by LK4D4** [comment]
@cpuguy83 Maybe our cache is superfast? :)

**Comment by cpuguy83** [comment]
@LK4D4 It's webscale, apparently.

**Comment by anandkumarpatel** [comment]
@cpuguy83  merged your changes in, will come back with numbers for speed improvement

**Comment by anandkumarpatel** [comment]
running 50 parallel builds
everything cached (fastest possible speed)
~21 s for each probeCache
~265 s avg time per build
~270 s to complete all builds

now if I break the cache at the `ADD` statement with fix
~1.5 us for each probCache
~518 s avg time per build
~537 s to complete all builds

now if I break the cache at the `ADD` statement no fix
~12 s for each probCache
~878 s avg time per build
~923 s to complete all builds

speedup = 386s (6 min)!
time saved can be calculated by so:
```timeSaved = timeToLookUpCache * stepsAfterCacheMiss```

dockerfile:
```
add . /
RUN /bin/true
RUN /bin/true
RUN /bin/true
RUN /bin/true
RUN /bin/true
RUN /bin/true
RUN /bin/true
RUN /bin/true
RUN /bin/true
RUN /bin/true
CMD /bin/true
```

**Comment by cpuguy83** [comment]
SGTM, I did not do parallel builds.

**Comment by anandkumarpatel** [comment]
@LK4D4 also applied your minor change

**Comment by anandkumarpatel** [comment]
@cpuguy83 @LK4D4 @duglin anything else needed here?

**Comment by podviaznikov** [comment]
+1

**Comment by duglin** [comment]
LGTM

**Comment by tjmehta** [comment]
+1

**Comment by LK4D4** [comment]
LGTM

**Comment by rsandor** [comment]
+1

**Pull request merged**
