### PR TITLE
fix rpms

### PR DESCRIPTION
**Pull request by jessfraz**
ping @calavera this will need to be included in the release, I'm building now but fingers crossed looks like its going to work, we should wait just in case to merge ;)

### CODE REVIEW

**Comment by tianon** [comment]
grosssss

LGTM

(for the curious, this comes from https://github.com/CentOS/sig-cloud-instance-images/issues/24)

**Comment by calavera** [comment]
Cool, thank you, LGTM too but I'll wait until you're sure this works.

**Comment by jfrazelle** [comment]
yayyyy it worked! we should have rpms now after the fedora ones finish building

**Comment by jfrazelle** [comment]
ok this can be merged

**Comment by calavera** [comment]
Cherry picked into #14264 :raised_hands:

**Pull request merged**
