### PR TITLE
Windows: Enable more create tests

### PR DESCRIPTION
**Pull request by darstahl**
Enable more create tests on Windows.

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
@darrenstahlmsft Usage of `getPrefixAndSlashFromDaemonPlatform` in `TestCreateVolumesCreated` seems wrong.

**Comment by darrenstahlmsft** [comment]
Yep, I didn't realize it needed the slash too. Fixed.

**Comment by tonistiigi** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Pull request merged**
