### PR TITLE
Add sigprocmask to default seccomp profile

### PR DESCRIPTION
**Pull request by crosbymichael**
### Description for the changelog
Seccomp: add sigprocmask (used by x86 glibc) to default seccomp profile

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]

**Review by tiborvass — CHANGES_REQUESTED** [review]
validate is failing, can you please run `go generate ./profiles/seccomp/` ?

**Comment by crosbymichael** [comment]
Thanks @tiborvass , i didn't know the command to run

**Review by tiborvass — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
we need to add a makefile target for those

**Comment by thaJeztah** [comment]
One failure; kicking Jenkins again

```
[2019-08-29T18:05:09.863Z] === CONT  TestStopContainerWithTimeout/1
[2019-08-29T18:05:10.796Z] --- FAIL: TestStopContainerWithTimeout (0.06s)
[2019-08-29T18:05:10.796Z]     --- PASS: TestStopContainerWithTimeout/0 (1.28s)
[2019-08-29T18:05:10.796Z]     --- PASS: TestStopContainerWithTimeout/3 (3.28s)
[2019-08-29T18:05:10.796Z]     --- FAIL: TestStopContainerWithTimeout/1 (0.76s)
[2019-08-29T18:05:10.796Z]         stop_linux_test.go:57: assertion failed: error is not nil: Error response from daemon: ttrpc: client shutting down: ttrpc: closed: unknown
[2019-08-29T18:05:10.796Z]     --- PASS: TestStopContainerWithTimeout/-1 (2.97s)
```

**Comment by thaJeztah** [comment]
Oh, looks like they're upgrading Jenkins
Screenshot 2019-08-29 at 21 58 53

**Comment by thaJeztah** [comment]
All green, except for Windows RS1, which took longer than 2 hours and was terminated

**Pull request merged**
