### PR TITLE
update docs for container exec

### PR DESCRIPTION
**Pull request by hqhq**
https://github.com/docker/docker/pull/11665 This PR changed container
exec API response, we need docs updated.

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
Thanks  @hqhq 

@crosbymichael on this kind of one liner do you want me to pass it through without a code review if it is passing tests? (I don't like to pull merge triggers on PRs with code changes unless a coder has an L-GTM on it)

**Comment by estesp** [comment]
I'll LGTM it :) This is good--the response changed, and this is correctly updating it

**Comment by moxiegirl** [comment]
Thanks @estesp !

**Pull request merged**
