### PR TITLE
Pass plugingetter as part of swarm node config.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
This is necessary for swarmkit to support cluster wide plugins, such as
globally scoped network plugins.

Signed-off-by: Anusha Ragunathan <anusha.ragunathan@docker.com>

cc @mavenugo @aaronlehmann

### CODE REVIEW

**Comment by vdemeester** [comment]
@anusha-ragunathan CI failures 👼 

```
23:46:21 These files are not properly gofmt'd:
23:46:21  - daemon/cluster/noderunner.go
```

**Comment by mavenugo** [comment]
Minor comment : can you pls move vendor/github.com/docker/swarmkit/node/node.go to the vendor commit ?

**Comment by anusha-ragunathan** [comment]
@mavenugo : done.

**Comment by mavenugo** [comment]
thanks @anusha-ragunathan .

LGTM

**Comment by tiborvass** [comment]
code LGTM

**Pull request merged**
