### PR TITLE
dont try to install journald driver on wheezy

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon 

this is breaking experimental builds

### CODE REVIEW

**Comment by tianon** [comment]
Arg, but it's included in wheezy _and_ wheezy-backports. :cry:

Code LGTM if we have to, but I think it warrants a little bit of digging to see what's going wrong -- do we at least have some logs we can link/include here for future reference?

**Comment by jfrazelle** [comment]
The C library is throwing errors that it can't find things... granted I
only tried to debug for like 2 min:
could not determine kind of name for C.sd_journal_set_data_threshold
could not determine kind of name for C.sd_journal_test_cur

**Comment by tianon** [comment]
During build, or during runtime?

**Comment by jfrazelle** [comment]
During building dynbinary :/

**Comment by jfrazelle** [comment]
I'm rebuilding to get the full output and debug :)

**Comment by tianon** [comment]
Ok cool, that's easier to mess with; I'm checking it out too -- feel free
to merge this if it's needed to unblock CI. :+1:

(Still would be great to get the output here in case I fail. :+1: :metal: )

**Comment by calavera** [comment]
LGTM

**Comment by tianon** [comment]
I figured it out: https://github.com/docker/docker/pull/19687 :smile:

**Pull request closed without merging**
