### PR TITLE
Update changelog with changes from 1.10.1 and .2

### PR DESCRIPTION
**Pull request by thaJeztah**
Please provide the following information:
- What did you do?
  cherry-pick changelog changes from 1.10.1 and 1.10.2 back to master
- How did you do it?
  `git cherry-pick -s -x ...`
- How do I see it or verify it?
  look at the diff
- A picture of a cute animal (not mandatory but encouraged)
  jumping-spider-waterdrop-hats-uda-dennie-2

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tiborvass perhaps there's more changes that still need to be cherry-picked into master

**Comment by vdemeester** [comment]
I wourld say LGTM but waiting for @tiborvass input :angel:

**Comment by tiborvass** [comment]
LGTM.
There were 4 PRs open against the bump branch, 3 of them are vendor updates so not needed to be back merged, and the remaining one is #20522 which was a simpler fix than #19498. Since #19498 is already merged, we probably don't need #20522 either. So only the changelog was missing.

@LK4D4 can you confirm?

Also, about that TestStatsAllNewContainersAdded test in win2lin, I think I'm going to just add SameHostDaemon requirement.

**Comment by thaJeztah** [comment]
Thanks, I'll merge this one, we can check the other PR's in a follow up

**Pull request merged**
