### PR TITLE
vendor: github.com/docker/distribution v2.8.3

### LINKED ISSUE #46006: Pushing blobs doesn't send content-type
### Description

Trying to push an image to a conformant registry yields an error:

```
$ docker push localhost:8080/alpine/alpine:latest
The push refers to repository [localhost:8080/alpine/alpine]
78a822fe2a2d: Pushing [==================================================>]  7.327MB/7.327MB
error parsing HTTP 400 response body: invalid character 'c' looking for beginning of value: "content-type must be 'application/octet-stream' but is \"\""
```

The distribution spec [mandates blob pushes](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-blobs) to send a `content-type: application/octet-stream` header when pushing blobs.

### Reproduce

1. `docker run -it --rm -p 8080:8080 ghcr.io/makkes/garage@sha256:07db64a5f721c4a99ba108e3fd62dd21a68ad1e0630eee7f5a8a3a58ef8f9e61` (this is an OCI-conformant registry)
2. `docker pull alpine@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70`
3. `docker tag alpine@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70 localhost:8080/alpine/alpine:latest`
4. `docker push localhost:8080/alpine/alpine:latest`

### Expected behavior

`docker push` should successfully push the image.

### docker version

```bash
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Mon May 29 15:50:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f9ee
  Built:            Mon May 29 15:50:06 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58.m
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.11.0
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.20.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.1
    Path:     /home/max/.docker/cli-plugins/docker-sbom

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.3.9-arch1-1
[... redacted ...]
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on https://github.com/moby/moby/pull/46555

opening as draft, as it's not tagged / released yet

- relates to https://github.com/moby/moby/issues/46006
- fixes https://github.com/moby/moby/issues/46006

----

- Fix storageDriver gcs not registered in binaries
- reference: replace uses of deprecated function SplitHostname
- Dont parse errors as JSON unless Content-Type is set to JSON
- update to go1.20.8
- Set Content-Type header in registry client ReadFrom
- deprecate reference package, migrate to github.com/distribution/reference
- digestset: deprecate package in favor of go-digest/digestset
- Do not close HTTP request body in HTTP handler

full diff: https://github.com/distribution/distribution/compare/v2.8.2...v2.8.3

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Wondering if this could be a legit failure 

```
=== FAIL: github.com/docker/docker/distribution TestPullSchema2Config/unauthorized (0.00s)
    pull_v2_test.go:282: HTTP GET /v2/
    pull_v2_test.go:282: HTTP GET /v2/docker.io/library/testremotename/blobs/sha256:66ad98165d38f53ee73868f82bd4eed60556ddfee824810a4062c4f777b20a5b
    pull_v2_test.go:312: expected error="download failed after attempts=1: unauthorized: " to contain "unauthorized: authentication required"

**Comment by thaJeztah** [comment]
Test looks to be failing indeed;

```
=== FAIL: github.com/docker/docker/distribution TestPullSchema2Config/unauthorized (0.00s)
    pull_v2_test.go:282: HTTP GET /v2/
    pull_v2_test.go:282: HTTP GET /v2/docker.io/library/testremotename/blobs/sha256:66ad98165d38f53ee73868f82bd4eed60556ddfee824810a4062c4f777b20a5b
    pull_v2_test.go:312: expected error="download failed after attempts=1: unauthorized: " to contain "unauthorized: authentication required"
```

I wonder though where the `authentication required` part came from before, because the tests is just setting a status-header; https://github.com/moby/moby/blob/605c8fb75dcfcd5d2d79dce5a58b330a6d5165dc/distribution/pull_v2_test.go#L268-L273

That would _probably_ come from https://github.com/moby/moby/blob/605c8fb75dcfcd5d2d79dce5a58b330a6d5165dc/vendor/github.com/docker/distribution/registry/api/errcode/register.go#L36-L46, but not sure how that got into the response in this test (perhaps client mapping?)

- Primary suspect would be https://github.com/distribution/distribution/pull/4054

**Comment by thaJeztah** [comment]
Fixed that one, but need to look at the integration-cli ones;

```
=== Failed
=== FAIL: amd64.integration-cli TestDockerRegistryAuthTokenSuite/TestPushMisconfiguredTokenServiceResponseError (5.17s)
    docker_cli_push_test.go:288: assertion failed: toomanyrequests: {"errors": [{"code":"TOOMANYREQUESTS","message":"out of tokens"}]} (split[len(split)-2] string) != toomanyrequests: out of tokens (string)
    check_test.go:559: [d8a98b9190c8a] daemon is not started
    --- FAIL: TestDockerRegistryAuthTokenSuite/TestPushMisconfiguredTokenServiceResponseError (5.17s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthTokenSuite/TestPushMisconfiguredTokenServiceResponseUnauthorized (0.16s)
    docker_cli_push_test.go:273: assertion failed: unauthorized: {"error": "unauthorized"} (split[len(split)-2] string) != unauthorized: authentication required (string)
    check_test.go:559: [df745bdd35c0a] daemon is not started
    --- FAIL: TestDockerRegistryAuthTokenSuite/TestPushMisconfiguredTokenServiceResponseUnauthorized (0.16s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthTokenSuite/TestPushMisconfiguredTokenServiceResponseUnparsable (0.16s)
    docker_cli_push_test.go:301: assertion failed: expression is false: strings.Contains(split[len(split)-2], "error parsing HTTP 403 response body: ")
    check_test.go:559: [d971a6903e6c6] daemon is not started
    --- FAIL: TestDockerRegistryAuthTokenSuite/TestPushMisconfiguredTokenServiceResponseUnparsable (0.16s)

=== FAIL: amd64.integration-cli TestDockerRegistryAuthTokenSuite/TestPushTokenServiceUnauthResponse (0.16s)
    docker_cli_push_test.go:260: assertion failed: expression is false: strings.Contains(out, "unauthorized: a message")
    check_test.go:559: [d78bb30ecd086] daemon is not started
    --- FAIL: TestDockerRegistryAuthTokenSuite/TestPushTokenServiceUnauthResponse (0.16s)
```

**Comment by thaJeztah** [comment]
@rumpl @vvoland ptal :)

**Review by rumpl — APPROVED** [review]

**Review by vvoland — APPROVED** [review]

**Pull request merged**
