### PR TITLE
Windows: Add npipe to vendor

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com
@swernli

This PR is part of the proposal described in issue 10662 to port the docker daemon to Windows. This PR adds natefinch\npipe to vendor - this is a library for Windows named pipes. Named pipes are (will in a PR coming soon) used in the Windows exec driver to pass stdin/out/err to Windows containers.

### CODE REVIEW

**Comment by tiborvass** [comment]
@jhowardmsft as an FYI we already have ./vendor/src/code.google.com/p/gosqlite/sqlite/ so I would prefer not vendoring two different implementations of the same thing. Either we manage to use the existing package, or we replace the old one with the new one.

**Comment by unclejack** [comment]
NOT LGTM - please use the same sqlite library.

**Comment by jhowardmsft** [comment]
@tiborvass @unclejack  - Let me check if the mattn version can be used by Linux. Some background info which explains why the Windows daemon cannot use the existing p/gosqlite/SQLite vendor package. There are countless issues of statically linking sqlite3.dll to go code on Windows. I could reel off dozens of web pages where people have had this problem. The only solution I have found that works -on windows- (and believe me I've spent a week of my life finding a solution) is to use the mattn library. Without dynamic linking, it creates a packaging problem as docker.exe would need sqlite3.dll to either sit along-side the binary, or be in \windows\system32. This would be true for both the daemon and the client. An alternate would have been to somehow have docker.exe and dockerd.exe which is quite frankly horrible IMO.

**Comment by jhowardmsft** [comment]
(To clarify - the existing p\gosqlite\sqlite3 doesn't include the amalgamation sources - the two libraries are actually quite different)

**Comment by unclejack** [comment]
@jhowardmsft Ok, this is easy. Windows is a new platform, so we're free to make new choices when it comes to data persistence as there are no previous installations with sqlite databases.

We've discussed switching to https://github.com/cznic/ql from sqlite. We can start migrating with Windows. Once we've got this going for Windows, we can set up the migration part so that we migrate away from sqlite on Linux as well to keep everything consistent on all platforms.

Here's my proposal:
1) implement https://github.com/cznic/ql for the windows persistence
2) set up the migration path for Linux (e.g. set up new installs with ql, migrate sqlite to ql on Linux)
3) after some releases, completely remove sqlite to ql migration and provide a separate tool for this

**Comment by jhowardmsft** [comment]
OK, I can look at using ql for Windows and open an issue for Linux migration. For now, if I were to contain this PR to just the named pipe library, I assume there would not be so much push back, correct?

**Comment by unclejack** [comment]
@jhowardmsft As far as I'm concerned, yes. The ql change would need to be done in a separate PR which handles both the introduction of ql and the code which migrates sqlite to ql.

**Comment by crosbymichael** [comment]
Thanks but I don't think we are conformable vendoring new dependencies before they are being used.  We are already getting alot of code merged in to support the Windows daemon that is not currently being used, which is ok, but vendoring new deps without them being used introduces other issues such as notifying packages and other fun stuff.

Lets just hold off on merging vendored code until it is being used.  Feel free to open issues to discuss any design or package selection issues if you need some help ;)

**Comment by jhowardmsft** [comment]
Understood, thanks @crosbymichael. Will bring in with the full Windows exec driver.

**Pull request closed without merging**
