### PR TITLE
Add "import" statement to generated API types

### PR DESCRIPTION
**Pull request by thaJeztah**
Update the template to add the import  comment

### CODE REVIEW

**Comment by thaJeztah** [comment]
@vdemeester @cpuguy83 ptal

**Comment by vdemeester** [comment]
@thaJeztah with this PR, that make https://github.com/moby/moby/pull/39050 not required, right ?

**Comment by thaJeztah** [comment]
Unfortunately it's required; these files use the template, but the files in https://github.com/moby/moby/pull/39050 use the "model" template; https://github.com/go-swagger/go-swagger/blob/df5b513aede5f5f7f39498bfcd4ea50a5194bb06/generator/templates/model.gotmpl

And you can't override that one 😞

**Comment by thaJeztah** [comment]
Well "required" as in; it modifies other files. I know that other PR is a bit "dirty", so not an absolute "must have" 😂

**Comment by thaJeztah** [comment]
Windows RS1 https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/24804/console

possibly needs to be cleaned up

```
15:47:29 panic: test timed out after 3h20m0s
15:47:29 
```

**Comment by thaJeztah** [comment]
@vdemeester @cpuguy83 LGTY?

**Review by vdemeester — APPROVED** [review]
LGTM 🙌🏼

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
