### PR TITLE
Add zsh completion for 'docker network create -o --opt'

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #17046

@albers Thanks for noticing me it has been merged.

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by albers** [comment]
Your're really fast! :smile:

**Comment by thaJeztah** [comment]
> Your're really fast! :smile:

LOL, I think you both are :-)

ping @vincentbernat in case you want to have a look as well

**Comment by cpuguy83** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
:+1: thanks to the completion team, good to see you both coordinating tasks!

**Pull request merged**
