### PR TITLE
service tasks: Improve error reporting

### PR DESCRIPTION
**Pull request by aluzzardi**
- Tasks will display all tasks (`-a` is the default and was removed)
- Nest tasks to help display history
- Display task errors inline

Example:

```
# docker service tasks vote
ID                         NAME        IMAGE           NODE          DESIRED STATE  CURRENT STATE            ERROR
bvojmk7wiwjswyb0ww1o8by9e  vote.1      instavote/vote  ce5a79de6642  Running        Running 15 minutes ago
amwhb0xwateq040lqwzu0qado   \_ vote.1  instavote/vote  ce5a79de6642  Shutdown       Complete 30 minutes ago
14hd2jrgta2378ndoya2ddgug   \_ vote.1  instavote/vote  ce5a79de6642  Shutdown       Complete 45 minutes ago
5kb6oq07oydo6i8oz50wtt7ir   \_ vote.1  instavote/vote  ce5a79de6642  Shutdown       Failed 45 minutes ago    "starting container failed: oc…"
613cgiw1ajc4bwxbwa5h033it   \_ vote.1  instavote/vote  ce5a79de6642  Shutdown       Shutdown 52 minutes ago
3vgj9c3ab7fphoughj041r144   \_ vote.1  instavote/vote  ce5a79de6642  Shutdown       Failed 54 minutes ago    "task: non-zero exit (137)"
612ik4x1sgkgwmoed9riwc3je   \_ vote.1  instavote/vote  ce5a79de6642  Shutdown       Failed 56 minutes ago    "task: non-zero exit (137)"
00oz0yso8xcjveycxpobh8afm   \_ vote.1  instavote/vote  ce5a79de6642  Shutdown       Failed 56 minutes ago    "task: non-zero exit (137)"
0hung96bc208fazmg19kuze6z  vote.2      instavote/vote  ce5a79de6642  Running        Running 15 minutes ago
d53beglz6wgp9rx4gz91sjr7c   \_ vote.2  instavote/vote  ce5a79de6642  Shutdown       Complete 30 minutes ago
e0sfqy2zrxi06xjizhhfr405h   \_ vote.2  instavote/vote  ce5a79de6642  Shutdown       Complete 45 minutes ago
ap2xcl5x2op6txl95zepntqno   \_ vote.2  instavote/vote  ce5a79de6642  Shutdown       Failed 45 minutes ago    "starting container failed: oc…"
8oiok9dfowzf2urglzggpzz9a   \_ vote.2  instavote/vote  ce5a79de6642  Shutdown       Shutdown 52 minutes ago
```

/cc @vieux @icecrime @stevvooe @aaronlehmann @mgoelzer

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

**Comment by thaJeztah** [comment]
wondering if this should be the default, or hidden behind a (e.g.) `--history` or `--whatever` flag. I can see this format being troublesome for people that want to parse it (in a script), or if we want to add a `--format` flag later on.

I like the idea though 👍

**Comment by tiborvass** [comment]
@aluzzardi so if a service continually fails to converge, how many tasks will there be?

**Comment by aluzzardi** [comment]
@tiborvass Right now the "history" is capped at 15 (it's a SwarmKit flag - `docker swarm update --task-history=N` AFAIK).

I'm making a case with @aaronlehmann to move it 5 by default.

@thaJeztah: I think we should display it by default. I've seen lots of confusion about grasping the model and troubleshooting a Swarm. Showing all tasks makes users understand the model (not many people were aware of `-a` and even less knew what it actually meant).

Example: Run `docker service create bad_image` and then `tasks` would always show a single task in `PREPARING` state which looks like it's stuck. In reality, the task goes from `PREPARING` to `REJECTED` (bad image), it gets hidden by `tasks` (because of no `-a`) and then a replacement is created and displayed as `PREPARING`.

With this PR, `tasks` would show an increasing list of stuff (up to 15 - maybe 5) with a `REJECTED` state and an error column complaining about `bad_image`which is a much better UX.

Regarding scripts - you can do what "no -a" was doing by using a filter (I believe `-f desired-state=running`?)

**Comment by vdemeester** [comment]
I like the it and do agree with @aluzzardi 👼
Design LGTM for me

**Comment by tiborvass** [comment]
@aluzzardi what happens if i do `--replicas 100` i still get only the last `5` that were scheduled?

**Comment by aluzzardi** [comment]
@tiborvass it's `5` per replica, so `500` total

**Comment by stevvooe** [comment]
LGTM with `docker service ps` PR.

**Comment by tiborvass** [comment]
@aluzzardi so i would see all 500 in `service tasks`, correct?

**Comment by aaronlehmann** [comment]
There would only be 500 if each replica had been restarted at least 5 times. But yes, in that case, you would see a total of 500.

**Comment by vieux** [comment]
I like this idea LGTM

**Comment by tiborvass** [comment]
+1 , moving to code review

**Comment by tiborvass** [comment]
@aluzzardi can you change this so that it only returns the last 5 tasks per replica?

**Comment by tiborvass** [comment]
Otherwise this looks good

**Comment by cpuguy83** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM we can change default number of tasks in other PR.

**Pull request merged**
