### PR TITLE
Update runc to 9c2d8d184e5da67c95d601382adf14862e4f2228

### LINKED ISSUE #30121: when docker use --cpu-quota and systemd daemon-reload, old container's cpu.cfs_quota_us become -1
hello ,I got a problem , But I am not sure it is systemd's problem or docker's problem, It is easy to reproduce. 

When I use ```docker run --cpu-quota=50000 --cpu-period=100000 -d docker.io/centos /sbin/init```to  start the first container A, and then execute ```systemctl daemon-reload``` ; then , I start the second docker container , the first docker container's  value ```cpu.cfs_quota_us``` will become ```-1```

Is systemd's logical or is docker's bug?
## docker version
```
[root@iZrj9cft0g87g90carlmnsZ ~]# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-401976-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 255.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 40.5 GB
 Metadata Space Used: 897 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.51 GiB
Name: iZrj9cft0g87g90carlmnsZ
ID: 2P26:F7ZL:RTPF:IYEM:RUK7:MGTF:J5IR:O66A:KF3I:RX66:USZB:4QUC
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

```
[root@iZrj9cft0g87g90carlmnsZ ~]# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

```

```
[root@iZrj9cft0g87g90carlmnsZ ~]# rpm -qa | grep systemd
systemd-libs-219-30.el7_3.6.x86_64
systemd-219-30.el7_3.6.x86_64
systemd-sysv-219-30.el7_3.6.x86_64
oci-systemd-hook-0.1.4-6.git337078c.el7.x86_64
```

```
[root@iZrj9cft0g87g90carlmnsZ ~]# uname -r
3.10.0-327.22.2.el7.x86_64
```

### 1. docker use  --cpu-quota start a container

```
[root@iZrj9cft0g87g90carlmnsZ ~]# docker run --cpu-quota=50000 --cpu-period=100000 -d docker.io/centos /sbin/init
19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20
[root@iZrj9cft0g87g90carlmnsZ ~]#
```

```
[root@iZrj9cft0g87g90carlmnsZ ~]# systemd-cgls  | grep 19d5b47bbedd
│     └─2959 grep --color=auto 19d5b47bbedd
  ├─docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope
  
```

```
[root@iZrj9cft0g87g90carlmnsZ ~]# systemctl cat docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope

# /run/systemd/system/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope.d/50-BlockIOAccounting.conf
[Scope]
BlockIOAccounting=yes
# /run/systemd/system/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope.d/50-CPUAccounting.conf
[Scope]
CPUAccounting=yes
# /run/systemd/system/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope.d/50-DefaultDependencies.conf
[Unit]
DefaultDependencies=no
# /run/systemd/system/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope.d/50-Delegate.conf
[Scope]
Delegate=yes
# /run/systemd/system/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope.d/50-Description.conf
[Unit]
Description=docker container 19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20
# /run/systemd/system/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope.d/50-MemoryAccounting.conf
[Scope]
MemoryAccounting=yes
# /run/systemd/system/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope.d/50-Slice.conf
[Scope]
Slice=system.slice
[root@iZrj9cft0g87g90carlmnsZ ~]#
```

### 2. systemctl daemon-reload
we can see cpu.cfs\_quota\_us

```
[root@iZrj9cft0g87g90carlmnsZ ~]# cat /sys/fs/cgroup/cpu/system.slice/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope/cpu.cfs_quota_us
50000
[root@iZrj9cft0g87g90carlmnsZ ~]# systemctl daemon-reload
[root@iZrj9cft0g87g90carlmnsZ ~]#

```

### 3. start another new container

```
[root@iZrj9cft0g87g90carlmnsZ ~]# docker run --cpu-quota=50000 --cpu-period=100000 -d docker.io/centos /sbin/init
bdf76c111116d60252cb9075bc69f22da9ac970551fc6a55a49d0f8cee163441
```

### 4. old docker container's cpu.cfs\_quota\_us value become -1
```
[root@iZrj9cft0g87g90carlmnsZ ~]# cat /sys/fs/cgroup/cpu/system.slice/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope/cpu.cfs_quota_us
-1
[root@iZrj9cft0g87g90carlmnsZ ~]#
```

### 5. My Analysis
BUt , If I do ```systemctl set-property xxx  CPUQuota=10%```  , and ```systemctl daemon-reload``` , I find , this value will not be changed , So I think if it is systemd's logic and it will likely to be a docker's bug ? 

```
[root@iZrj9cft0g87g90carlmnsZ ~]# systemctl set-property docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope CPUQuota=10%
[root@iZrj9cft0g87g90carlmnsZ ~]#
[root@iZrj9cft0g87g90carlmnsZ ~]# cat /sys/fs/cgroup/cpu/system.slice/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope/cpu.cfs_quota_us
10000
[root@iZrj9cft0g87g90carlmnsZ ~]#
[root@iZrj9cft0g87g90carlmnsZ ~]# systemctl daemon-reload
[root@iZrj9cft0g87g90carlmnsZ ~]#
[root@iZrj9cft0g87g90carlmnsZ ~]# cat /sys/fs/cgroup/cpu/system.slice/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope/cpu.cfs_quota_us
10000
[root@iZrj9cft0g87g90carlmnsZ ~]#
[root@iZrj9cft0g87g90carlmnsZ ~]# docker run --cpu-quota=50000 --cpu-period=100000 -d docker.io/centos /sbin/init
4c77256624b929b62494766062526f506da445585923374628e4a5c30d34159b
[root@iZrj9cft0g87g90carlmnsZ ~]#
[root@iZrj9cft0g87g90carlmnsZ ~]# cat /sys/fs/cgroup/cpu/system.slice/docker-19d5b47bbedd802ade53eee6a0a2d53a9639d47f67be5247c3a9f6b55b5cde20.scope/cpu.cfs_quota_us
10000
```

### PR DESCRIPTION
**Pull request by mlaventure**
This fix a conflict with systemd daemon-reload (see
https://github.com/opencontainers/runc/pull/1344)

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

--

Closes #30121 

```diff
diff --git a/libcontainer/cgroups/systemd/apply_systemd.go b/libcontainer/cgroups/systemd/apply_systemd.go
index fd428f9..7ce066c 100644
--- a/libcontainer/cgroups/systemd/apply_systemd.go
+++ b/libcontainer/cgroups/systemd/apply_systemd.go
@@ -269,6 +269,13 @@ func (m *Manager) Apply(pid int) error {
                        newProp("CPUShares", uint64(c.Resources.CpuShares)))
        }
 
+       // cpu.cfs_quota_us and cpu.cfs_period_us are controlled by systemd.
+       if c.Resources.CpuQuota != 0 && c.Resources.CpuPeriod != 0 {
+               cpuQuotaPerSecUSec := c.Resources.CpuQuota * 1000000 / c.Resources.CpuPeriod
+               properties = append(properties,
+                       newProp("CPUQuotaPerSecUSec", uint64(cpuQuotaPerSecUSec)))
+       }
+
        if c.Resources.BlkioWeight != 0 {
                properties = append(properties,
                        newProp("BlockIOWeight", uint64(c.Resources.BlkioWeight)))
```

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
rebased.

**Comment by mlaventure** [comment]
Thanks!

**Pull request merged**
