### PR TITLE
vendor: github.com/ishidawataru/sctp v0.0.0-20230406120618-7ff4192f6ff2

### PR DESCRIPTION
**Pull request by thaJeztah**
- addresses https://github.com/moby/moby/issues/42495

---

- Prevent from descriptor leak
- Fixes optlen in getsockopt() for s390x

full diff: https://github.com/ishidawataru/sctp/compare/9a39160e9062...7ff4192f6ff2b4b181ec7dce269bdf4076ff90a0

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Kicked a Jenkins run with s390x enabled; https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-45301/3/pipeline/

**Comment by thaJeztah** [comment]
Ah, I guess we no longer have those connected to our Jenkins here.

**Comment by thaJeztah** [comment]
Hmm. yes, I don't think we still have s390x nodes connected to this Jenkins

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thx! Let me bring this one in 👍

**Pull request merged**
