### PR TITLE
Auto restart containers based on restart policy

### PR DESCRIPTION
**Pull request by crosbymichael**
This implements the proposal in #7226

Closes #7226
Closes #7521
#### Restart Policies

Using the `--restart` flag on docker run you can specify a restart policy for
how a container should or should not be restarted on exit.

**no** - Do not restart the container when it exits.

**on-failure** - Restart the container only if it exits with a non zero exit status.

**always** - Always restart the container regardless of the exit status.

You can also specify the maximum amount of times docker will try to restart the
container when using the **on-failure** policy.  The default is that docker will try forever to restart the container.

```
$ sudo docker run --restart=always redis
```

This will run the redis container with a restart policy of **always** so that if
the container exits, docker will restart it.

```
$ sudo docker run --restart=on-failure:10 redis
```

This will run the redis container with a restart policy of **on-failure** and a
maximum restart count of 10.  If the redis container exits with a non-zero exit
status more than 10 times in a row docker will abort trying to restart the container.

### CODE REVIEW

**Comment by ostera** [comment]
LGTM

**Comment by WIZARD-CXY** [comment]
@crosbymichael @vieux 
I am wondering why you set 10s as the reset time.
If we have a container which runs this script:
#!/bin/bash

sleep 11
exit 1
 
This container  always restart  with no delay....
I just uses a similar container that uses 10s to init the server, but fails afterwards, it gets restarted every time without delay..... And I believe the document not mention this 10s stuff.

**Comment by thaJeztah** [comment]
@WIZARD-CXY please don't use a very old, merged PR to report issues. Open a new issue instead with your use case, and/or an issue to report possible enhancements to the documentation.

**Comment by WIZARD-CXY** [comment]
@thaJeztah sorry, I just use 1.10.3 and use git blame to find this pr from the code. I'm not quite sure if this still happens in the upstream.Maybe I will open a new issue later.

**Pull request merged**
