### PR TITLE
Fixed a few network UI issues in swarm-mode

### LINKED ISSUE #23983: `docker network create -d bridge test` works if there is already an overlay network named test?
**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 380
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: active
 NodeID: 4b1et52uyr6nquyj7js30fgcu
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:9ebab8ad017aa10bd8eee00ba34f7e22932deeee38adf6e864786fb643668caf
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.`docker network create -d overlay test` to create an overlay network named test
2.`docker network create -d bridge test` to create a bridge network named test

Above steps can work. Actually they own the same name. It is a **CONFLICT** in the network naming.

While if I create bridge network named test, then create overlay network named test, daemon will report an error named:
```
Error response from daemon: network with name test already exists
```

In addition, This bug will result in `docker network inspect test` works if two networks with same name on a single daemon.

### PR DESCRIPTION
**Pull request by mavenugo**
- fixes #23983
- Prevents network connect/disconnect for managed containers

### CODE REVIEW

**Comment by thaJeztah** [comment]
Are we sure we want to introduce a concept of "managed" and "unmanaged" containers?

How does this resolve creating a local network named "test", if there's an overlay network with the same name?

**Comment by mavenugo** [comment]
@thaJeztah we have a few cases where we have to differentiate managed and unmanaged containers (mostly due to the current limitations that we have with a few unsupported features). When we are feature parity, then we can relax these restrictions and maybe remove this differentiation as well.

>> How does this resolve creating a local network named "test", if there's an overlay network with the same name?

That's exactly this PR does with the changes in  api/server/router/network/network_routes.go.

**Comment by tonistiigi** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
