### PR TITLE
TestBuildUserNamespaceValidateCapabilitiesAreV2: cleanup daemon storage

### LINKED ISSUE #42974: TestBuildUserNamespaceValidateCapabilitiesAreV2 prevents Jenkins from cleaning up
Looks like we're (fairly consistently) hitting cleanup errors from arm64 and cgroup2. In both cases, Jenkins is complaining about files from `TestBuildUserNamespaceValidateCapabilitiesAreV2`;

Both `arm64` and `cgroup2` jobs in Jenkins are running on Jenkins agent with Kernel 5.11 (also see https://github.com/moby/moby/issues/42892), so it seems there's a relation with that update of the agents / kernel.

https://ci-next.docker.com/public/job/moby/job/PR-42835/19/execution/node/398/

```
Also:   java.nio.file.AccessDeniedException: /home/ubuntu/workspace/moby_PR-42835/bundles/test-integration/TestBuildUserNamespaceValidateCapabilitiesAreV2/de3b5140cc048/root/overlay2/9b312dec55e10fe243a5e0422a7f9375c0cc2880d41696ac19fd6d9c191f1f56-init/work/work
```

https://ci-next.docker.com/public/job/moby/job/PR-42835/19/execution/node/420/

```
Also:   java.nio.file.AccessDeniedException: /home/ubuntu/workspace/moby_PR-42835/bundles/test-integration/TestBuildUserNamespaceValidateCapabilitiesAreV2/d4b91bdaf46b5/root/165536.165536/overlay2/d6050e82750d178c5151ec1427a44ce8352d9aa6e9843d61483e0f54b4a3125f-init/work/work
```

Interesting case is that in the `arm64` case, the path looks to be a rootless / remapped path (`root/165536.165536`), whereas in the `overlay2` case, the path does _not_ have the remapped user.

I guess that could be explained because the test starts to separate daemons; one rootless, and one not;

https://github.com/moby/moby/blob/085c6a98d54720e70b28354ccec6da9b1b9e7fcf/integration/build/build_userns_linux_test.go#L39-L42

https://github.com/moby/moby/blob/085c6a98d54720e70b28354ccec6da9b1b9e7fcf/integration/build/build_userns_linux_test.go#L90-L92

Wondering if one of those daemons is not succesfully killed, and therefore causing the permission denied

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/moby/moby/issues/42974

### testutil: daemon.Cleanup(): cleanup more directories

The storage-driver directory caused Jenkins cleanup to fail. While at it, also
removing other directories that we do not include in the "bundles" that are
stored as Jenkins artifacts.

### TestBuildUserNamespaceValidateCapabilitiesAreV2: cleanup daemon storage

This should help with Jenkins failing to clean up the Workspace:

- make sure "cleanup" is also called in the defer for all daemons. keeping
  the daemon's storage around prevented Jenkins from cleaning up.
- close client connections and some readers (just to be sure)

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by samuelkarp** [comment]
> don't use t.Fatalf(), as defer is not called when using it

https://pkg.go.dev/testing#T.Fatalf
> Fatalf is equivalent to Logf followed by FailNow. 

https://pkg.go.dev/testing#T.FailNow
> FailNow marks the function as having failed and stops its execution by calling runtime.Goexit (which then runs all deferred calls in the current goroutine).

Though maybe we can use [`t.Cleanup`](https://pkg.go.dev/testing#T.Cleanup) here, since that's actually managed by the test runtime?

**Comment by thaJeztah** [comment]
> Fatalf is equivalent to Logf followed by FailNow.

Oh! Looks like I was mistaken; I guess I followed the code path to the logger interface.

In any case, it didn't solve the issue; currently just trying to disable code to see at what point it starts to fail. But it's a bit of a pain, because once it fails, the Jenkins agent can no longer be used (so I need to delete the agent before trying again😫)

**Comment by thaJeztah** [comment]
OK; looks like this is working now; the culprit was the `/var/lib/docker/<storage-driver>` directory (`/var/lib/docker` not "literally", but the test-daemon's `root` / storage location).

I updated the test-utility's `Cleanup()` function to remove those files; after this is merged, I also want to have a look at implementing `t.Cleanup()` for these utilities, so that cleaning up is handled automatically when test completes (we should be able to use that now that we dropped older Go versions)

**Review by tianon — APPROVED** [review]
:eyes:

**Comment by thaJeztah** [comment]
This is green, with the exception of `TestBuildWCOWSandboxSize` on RS5 (which will be addressed by https://github.com/moby/moby/pull/43009)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
