### PR TITLE
Update vendored engine-api to e37a82dfcea64559ca6a581776253c01d83357d9.

### PR DESCRIPTION
**Pull request by yongtang**
This PR updates vendored engine-api to e37a82dfcea64559ca6a581776253c01d83357d9 in order to support `SecurityOptions` in `Info`.

See #20909, #21172 for details related to `SecurityOptions`.

`SecurityOptions` was added in `Info` through pull request https://github.com/docker/engine-api/pull/157 in engine-api.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by yongtang** [comment]
cc @thaJeztah @justincormack as this PR of updating vendor/engine-api is the prerequisite to fix #20909 `Show "seccomp" in docker info`.

**Comment by thaJeztah** [comment]
LGTM, but do we know which PR these changes relate to? https://github.com/docker/docker/pull/21541/files#diff-1089f5ff51f8af5380780b7a12ee52f4R242, wondering if that should be documented

**Comment by yongtang** [comment]
Hi @thaJeztah `SecurityOptions` was added in `Info` through pull request https://github.com/docker/engine-api/pull/157 in engine-api. I updated the comment of this pull request to take note. Let me know if there are other issues.

**Comment by thaJeztah** [comment]
Oh, sorry, I meant the `MaximumIOps` options, but let me merge this one, then we can look for the PR that uses those changes :smile:

**Comment by darrenstahlmsft** [comment]
The PR that uses the IOps changes is https://github.com/docker/docker/pull/21384

**Comment by thaJeztah** [comment]
Oh, thanks @darrenstahlmsft !

**Pull request merged**
