### PR TITLE
Changed ArchLinux image maker script to support ARMV versions other than 7

### PR DESCRIPTION
**Pull request by ownaginatious**
Looks like the ArchLinux contrib script file `mkimage-arch.sh` only attempts to generate armv7h images, regardless of the ARM platform being used to build. If you're like me and trying to build ArchLinux images on a crusty old armv6 Raspberry Pi, then this isn't going to work.

This PR switches the generated image to the ARM architecture of the system being used to build instead, which [for `armv` is `armv6h` and `armv7h` for ArchLinux](http://co.us.mirror.archlinuxarm.org/).

Extras:
- The RPiv1 is... not very fast, so the timeout for `expect` was changed to 30 minutes for `armv6h` builds.
- Bad signatures can cause `expect` to hang for the duration of the timeout. Added a conditional to the `exact` block for handling those.
- Changed the generated image name from `archlinuxarm` to `armv<version>h/archlinux` to more appropriately match [Docker's multiplatform image system](https://integratedcode.us/2016/04/22/a-step-towards-multi-platform-docker-images/).

Signed-off-by: Dillon Dixon dillondixon@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon @justincormack PTAL

**Comment by cpuguy83** [comment]
ping

**Comment by tianon** [comment]
Seems sane; LGTM

**Comment by justincormack** [comment]
Sorry, this got missed. LGTM.

**Pull request merged**
