### PR TITLE
Windows CI: test-unit pkg\archive step 1

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Part 1 of fixing up test-unit for pkg\archive on Windows CI. This fixes the compilation issue on Windows by moving a Linux specific test to the _unix_test.go file.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
documentation Jenkins failure is erroneous. No docs changes in this PR. All other contexts passed.

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by thaJeztah** [comment]
LGTM, thanks @jhowardmsft

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
Hah! Beat you this time, Jess

**Comment by jfrazelle** [comment]
hahha it was super fast

On Fri, Feb 12, 2016 at 3:39 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> Hah! Beat you this time, Jess
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/20284#issuecomment-183530037>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Pull request merged**
