### PR TITLE
Add Mae Jemison to name generator

### PR DESCRIPTION
**Pull request by SoManyHs**
Signed-off-by: Hsing-Hui Hsu <hsinghui@amazon.com>

**- A picture of a cute animal (not mandatory but encouraged)**

peach_sleeping

### CODE REVIEW

**Comment by SoManyHs** [comment]
Done! Thanks for reviewing :)

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by thaJeztah** [comment]
@AkihiroSuda @cpuguy83 ptal

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
