### PR TITLE
add disk usage test for client package

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

I found that in moby/moby there is a package client. while in docker/cli, there is another package cli. And they are almost the same. Then for a contributor, what is the better choice to contribute, push 2 PRs, one for one repo? 

ping @thaJeztah @dnephin 

**- What I did**
1. add disk usage test for client package

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by dnephin** [comment]
It should only exist in a single repo, we need to make a decision about which repo

**Comment by allencloud** [comment]
Any update with which repo to consider? @dnephin

**Comment by dnephin** [comment]
I believe it will stay in this repo. The `docker/cli` extract was just finalized on friday, so I think it should be a topic in the slack standup today.

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by dnephin — APPROVED** [review]
LGTM

**Pull request merged**
