### PR TITLE
Optimize `TestRunSeccompDefaultProfile`

### PR DESCRIPTION
**Pull request by WeiZhang555**
Part of #19425

Optimize performance of `TestRunSeccompDefaultProfile`

Performance improvement is not as large as expected, only save about 60 seconds, 308.741s -> 241.215s.

My PC is not very powerful, maybe Docker integration machine can have better performance, so let's have a try.

Any better idea is welcome. 

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
are you trying to do them parallel what about t.Parallel?

**Comment by cyphar** [comment]
I'm not sure that this (or t.Parallel) will give us a very large speed improvement. IMO, the main issue here is that `syscall-test` is an **incredibly** slow image, and we need to work on improving the speed (#19504 is related, but I'm not sure if it's applicable here).

**Comment by WeiZhang555** [comment]
@jfrazelle Thank you for reminder, didn't know we have a so convenient tool, thank you! :smile: 

@cyphar Yes, I concur with you. `syscall-test` is really really slow, and we should focus on improving its speed, that would be a correct way. 

Also test result shows the improvement is not very large, I'm closing this since it's not good enough. Let us find a better way. 

Thank you @cyphar

**Comment by thaJeztah** [comment]
60 seconds on 300 seconds is still 20% improvement; @jfrazelle wdyt (haven't looked at the code)

**Comment by cyphar** [comment]
@thaJeztah Basically, this PR runs the tests in 4 goroutines. It still took `374.813s` in the janky run. IMO the root cause is that our `syscall-test` image is too bloated (as referenced in a few places, mainly in #19425), and we should be focusing on fixing _that_.

Actually, I just noticed that @WeiZhang555 didn't use `select`, so in the worst case it'll take as long as before! @WeiZhang555 can you please use `select` in this PR so we can test if there's a better speed improvement that way?

**Comment by WeiZhang555** [comment]
@cyphar I agree with you. 

I think `select {...}` can't apply to this test case because we need to wait all the error channel to return and can't only select one error. But it's still weird that 4 parallel go routine didn't bring improvement  on docker's integration machine, it should cost max execution time of 4 separate goroutines, at least it saves 60 seconds on my PC.

I'll try to find another way similar to `select{...}` for testing performance improvement in the best case.

**Comment by cyphar** [comment]
@WeiZhang555 I mean something like:

```
for {
  case ret := <-errChan1:
    c.Assert(...)
  case ret := <-errChan2:
    c.Assert(...)
  case ret := <-errChan3:
    c.Assert(...)
  case ret := <-errChan4:
    c.Assert(...)
  default:
    break
}
```

Or something.

**Comment by WeiZhang555** [comment]
@cyphar I think this won't work, for example, after the `errChan1` is closed, `case ret := <-errChan1:` will always be true because reading from a closed channel will get a nil pointer, then it will be a dead for loop.

**Comment by thaJeztah** [comment]
@cyphar @WeiZhang555 I agree fixing that should be done as well; just wanted to mention that, if the code in this is looking good, and we have one minute speedup; every bit helps, right?

I'm okay with closing if the code is becoming too messy (or less stable) just for a speedup though

**Comment by cyphar** [comment]
@WeiZhang555 Well, if you do `close(ch); ch = nil` in the defers, then it'll work as intended.

**Comment by WeiZhang555** [comment]
```
for {
select{
  case ret := <-errChan1:
    c.Assert(...)
    errChan1 = nil
  case ret := <-errChan2:
    c.Assert(...)
    errChan2 = nil
  case ret := <-errChan3:
    c.Assert(...)
    errChan3 = nil
  case ret := <-errChan4:
    c.Assert(...)
    errChan4 = nil
  default:
    break
} 
```
Unfortunately this doesn't work either. You see that if errChan is nil, read from it will block forever, and if goroutine doesn't finish and nobody writes the channel, the channel will also block, you can't classify which situation is it, so can't decide when to break the for loop.

I think reading from 4 errChan won't be a problem, for example if 4 goroutines each cost 10s, 2s, 5s, 15s, then reading from 4 errChan sequentially will cost about 15s, it won't be worse than using `select`.

-------------------------------------------------
However it's still strange parallel execution didn't bring improvement, maybe 4 goroutines are racing on the compute resources which leads to lower performance for each goroutine? I'm not sure...

**Comment by WeiZhang555** [comment]
Just had a struggle, pushed again for testing the execution time. Without more change, latest test result shows:
Janky:
```
16:26:42 PASS: docker_cli_run_unix_test.go:867: DockerSuite.TestRunSeccompDefaultProfile	121.129s
```
experimental:
```
16:21:22 PASS: docker_cli_run_unix_test.go:867: DockerSuite.TestRunSeccompDefaultProfile	234.704s
```

I'm satisfied with this result, but it's weird that last time the result is not very good.

I picked another PR, it shows:
Janky
```
08:39:24 PASS: docker_cli_run_unix_test.go:867: DockerSuite.TestRunSeccompDefaultProfile	307.831s
```

So it works though not perfect, should we move forward? Now I think it's worth a try, I shouldn't give up that early :laughing: 
What do you think of this? @thaJeztah @jfrazelle @cyphar

**Comment by cyphar** [comment]
> However it's still strange parallel execution didn't bring improvement, maybe 4 goroutines are racing on the compute resources which leads to lower performance for each goroutine? I'm not sure...

That shouldn't happen, since all the goroutines are doing is sending some JSON to the Docker daemon concurrently. Everything else is all happening inside Docker and not inside the tests.

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
`DockerSuite.TestRunSeccompDefaultProfile	408.928s`

**Comment by cpuguy83** [comment]
The asserts are the fast part, there is no need to send the errors on separate channels, we still have to wait for all of them to be done.

`PASS: docker_cli_run_unix_test.go:852: DockerSuite.TestRunSeccompDefaultProfile	37.231s`
```diff
diff --git a/integration-cli/docker_cli_run_unix_test.go b/integration-cli/docker_cli_run_unix_test.go
index 782a44b..428e21b 100644
--- a/integration-cli/docker_cli_run_unix_test.go
+++ b/integration-cli/docker_cli_run_unix_test.go
@@ -12,6 +12,7 @@ import (
 	"regexp"
 	"strconv"
 	"strings"
+	"sync"
 	"time"
 
 	"github.com/docker/docker/pkg/homedir"
@@ -851,54 +852,47 @@ func (s *DockerSuite) TestRunSeccompAllowAptKey(c *check.C) {
 func (s *DockerSuite) TestRunSeccompDefaultProfile(c *check.C) {
 	testRequires(c, SameHostDaemon, seccompEnabled, NotUserNamespace)
 
-	errChan1 := make(chan error, 1)
+	var group sync.WaitGroup
+	group.Add(4)
+	errChan := make(chan error, 4)
 	go func() {
-		defer close(errChan1)
 		out, _, err := dockerCmdWithError("run", "--cap-add", "ALL", "syscall-test", "acct-test")
 		if err == nil || !strings.Contains(out, "Operation not permitted") {
-			errChan1 <- fmt.Errorf("expected Operation not permitted, got: %s", out)
+			errChan <- fmt.Errorf("expected Operation not permitted, got: %s", out)
 		}
+		group.Done()
 	}()
 
-	errChan2 := make(chan error, 1)
 	go func() {
-		defer close(errChan2)
 		out, _, err := dockerCmdWithError("run", "--cap-add", "ALL", "syscall-test", "ns-test", "echo", "hello")
 		if err == nil || !strings.Contains(out, "Operation not permitted") {
-			errChan2 <- fmt.Errorf("expected Operation not permitted, got: %s", out)
+			errChan <- fmt.Errorf("expected Operation not permitted, got: %s", out)
 		}
+		group.Done()
 	}()
 
-	errChan3 := make(chan error, 1)
 	go func() {
-		defer close(errChan3)
 		out, _, err := dockerCmdWithError("run", "--cap-add", "ALL", "--security-opt", "seccomp:unconfined", "syscall-test", "acct-test")
 		if err == nil || !strings.Contains(out, "No such file or directory") {
-			errChan3 <- fmt.Errorf("expected No such file or directory, got: %s", out)
+			errChan <- fmt.Errorf("expected No such file or directory, got: %s", out)
 		}
+		group.Done()
 	}()
 
-	errChan4 := make(chan error, 1)
 	go func() {
-		defer close(errChan4)
 		out, _, err := dockerCmdWithError("run", "--cap-add", "ALL", "--security-opt", "seccomp:unconfined", "syscall-test", "ns-test", "echo", "hello")
 		if err != nil || !strings.Contains(out, "hello") {
-			errChan4 <- fmt.Errorf("expected hello, got: %s, %v", out, err)
+			errChan <- fmt.Errorf("expected hello, got: %s, %v", out, err)
 		}
+		group.Done()
 	}()
 
-	// error occurs when execute docker command:
-	// docker run --cap-add ALL syscall-test acct-test
-	c.Assert(<-errChan1, checker.Equals, nil)
-	// error occurs when execute docker command:
-	// docker run --cap-add ALL syscall-test ns-test echo hello
-	c.Assert(<-errChan2, checker.Equals, nil)
-	// error occurs when execute docker command:
-	// docker run --cap-add ALL --security-opt seccomp:unconfined syscall-test acct-test
-	c.Assert(<-errChan3, checker.Equals, nil)
-	// error occurs when execute docker command:
-	// docker run --cap-add ALL --security-opt seccomp:unconfined syscall-test ns-test echo hello
-	c.Assert(<-errChan4, checker.Equals, nil)
+	group.Wait()
+	close(errChan)
+
+	for err := range errChan {
+		c.Assert(err, checker.IsNil)
+	}
 }
 
 func (s *DockerSuite) TestRunApparmorProcDirectory(c *check.C) {
```

**Comment by WeiZhang555** [comment]
@cpuguy83 Yes, WaitGroup is more graceful, I've updated the code. :+1: 

Let's see the test result.

**Comment by WeiZhang555** [comment]
`Janky` takes 227.903s, `experimental` takes 346.915s, `gccgo` takes 272.350s.
So it improves a little, I was expecting a larger performance improvement.

Still I think it's worth a try.

**Comment by calavera** [comment]
still LGTM

**Comment by cpuguy83** [comment]
I suspect the real issue here is the size of the seccomp image and using vfs for these tests (which has to copy everything from the image into the rwlayer)... and I guess super slow disks on the CI servers.

But this LGTM as well.

**Pull request merged**
