### PR TITLE
Add non-experimental daemon as a test requirement.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
For test that should be exclusively run only in regular daemon builds
and not in the experimental version, add a requirement.

Verified using TestCleanupMountsAfterDaemonKill.
- On regular daemon, the test ran.
- On experimental daemon, the test skipped.

Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :+1:

**Comment by tonistiigi** [comment]
Why is the runtime check better?

**Comment by vdemeester** [comment]
@tonistiigi easier to *refactor* (you change the requirement) and also easier to read / manage (no build tags for integration).
@anusha-ragunathan I even feel we could update/add the test requirement to check the daemon version we're running the test against.

**Comment by anusha-ragunathan** [comment]
@vdemeester : It's better for a test to require a specific *feature* of the daemon, rather than a specific *version* of the daemon.

**Comment by vdemeester** [comment]
@anusha-ragunathan yeah by version, I meant *experimental or not*, so did not really use the right term indeed :sweat_smile:

**Comment by thaJeztah** [comment]
userns completed, but didn't notify GitHub;

```
22:16:06 Archiving artifacts
22:16:38 Notifying endpoint 'HTTP:https://leeroy.dockerproject.org/notification/jenkins'
22:16:39 Finished: SUCCESS
```

**Comment by thaJeztah** [comment]
all green, merging

**Pull request merged**
