### PR TITLE
Add more verbosity options to docker build

### LINKED ISSUE #13674: `docker build -q` should return only the final image id; API should return image ID
When automating builds it would be valuable to know the full image ID of the final image built.

### PR DESCRIPTION
**Pull request by vdemeester**
Adds a new flag `-v/--verbose` that can take the following values :
- `build` : hide RUN output (same as `-q/--quiet`)
- `run` : hide all but RUN output
- `none` : hide everything, and returns only the full image ID

The `-q/--quiet` option is kept and working as before, but `-v/--verbose`
takes precedence over it.

This is a _try_ that kinda follows @duglin comments on https://github.com/docker/docker/pull/10921#issuecomment-75325000. This would close #13674. 🐸

Few notes though :
- [ ] I don't really like `--verbose` as an option, but did not have inspiration :sweat:. Keeping only `--quiet` is hard though because changing it to a non-bool args would break current cli behaviour.
- [ ] Few behaviours needs to be define — e.g. what should it print if the build is run with `--verbose=none` and fails.
- [ ] Needs documentations updates.
- [ ] Needs completion updates for bash/zsh/… 

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by icecrime** [comment]
You're not gonna like this but... I'd rather wait until we pull out the builder (cc @tiborvass) :crying_cat_face:

**Comment by vdemeester** [comment]
@icecrime :sweat_smile: I was guessing you would say that :stuck_out_tongue_closed_eyes: and it feels coherent with the /pulling out/ :wink: .

**Comment by thaJeztah** [comment]
@vdemeester I think it's best to close this PR in the meantime. Please close yourself, because if I close it, you won't be able to re-open :-)

**Comment by thaJeztah** [comment]
Oh, unless @tiborvass doesn't think it has to be closed, that is :-)

**Comment by vdemeester** [comment]
@thaJeztah you're right, I'll close this for now :stuck_out_tongue:

**Pull request closed without merging**
