### PR TITLE
Windows: Disable VM cloning for TP5 image

### PR DESCRIPTION
**Pull request by jstarks**
The Windows TP5 image is not compatible with the Hyper-V isolated
container clone feature. Detect old images and pass a flag specifying that
clone should not be enabled.

cc @jhowardmsft @darrenstahlmsft

### CODE REVIEW

**Comment by jhowardmsft** [comment]
LGTM when Jenkins completes/passes

**Comment by jstarks** [comment]
This only changes Windows code, so janky test failure must be spurious.

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
all green, merging

**Comment by Zenexer** [comment]
@jstarks Although this PR doesn't apply to builds > 14350, Insider Preview build 14931 [does appear to be affected by this problem](https://github.com/Microsoft/Virtualization-Documentation/issues/358#issuecomment-249393233).  Either it was never fixed or there was a regression on Microsoft's end.

**Pull request merged**
