### PR TITLE
fixed typo, changed "perfectd to perfected"

### PR DESCRIPTION
**Pull request by trace-andreason**
**- What I did**
fixed typo, changed "perfectd to perfected"
**- How I did it**
N/A
**- How to verify it**
dictionary.com :)
**- Description for the changelog**

Fixed a typo in the comment describing Buckaroo Banzai

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
But this needs to be signed off with "git commit -s --amend --no-edit"

**Comment by trace-andreason** [comment]
Ok, I added a signature to my commit. Not sure if that should trigger the checks again automatically?

**Comment by cpuguy83** [comment]
Did you push? I don't see the updated commit.

**Comment by trace-andreason** [comment]
Ah, pushed to the wrong branch.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
