### PR TITLE
Remove TestEventsLimit(), and minor cleanups

### PR DESCRIPTION
**Pull request by thaJeztah**
This test was added a long time ago, and over the years has proven to be [flaky](https://github.com/moby/moby/search?q=TestEventsLimit&type=Issues&utf8=) (https://github.com/moby/moby/issues/28873, https://github.com/moby/moby/issues/22601, https://github.com/moby/moby/issues/25533, https://github.com/moby/moby/issues/21473, https://github.com/moby/moby/issues/13498), and slow (using [30 containers](https://github.com/moby/moby/blob/6b5b3250e8f63d2fcbbe132a02b7e4df9d1b60a5/integration-cli/docker_cli_events_test.go#L34-L46), and taking over a minute to run (https://github.com/moby/moby/issues/12675)).

To address those issues, it was modified to;

- cleanup containers afterwards (https://github.com/moby/moby/pull/9249)
- take clock-skew into account (https://github.com/moby/moby/pull/11330)
- improve performance by parallelizing the container runs (https://github.com/moby/moby/pull/12719)
- _reduce_ parallelization to address platform issues on Windows (twice..) https://github.com/moby/moby/pull/26968, https://github.com/moby/moby/pull/28968
- adjust the test to take new limits into account https://github.com/moby/moby/pull/32421
- adjust the test to account for more events being generated by containers (https://github.com/moby/moby/pull/34895)

The last change to this test (made in https://github.com/moby/moby/commit/ddae20c032058a0fd42c34c2e9750ee8f6296ac8#diff-9e07f7c1f4d16eb428d628f85ee1a6f1R125) actually broke the test, as it's now testing that all events sent by containers (`numContainers*eventPerContainer`) are received, but the number of events that is generated (17 containers * 7 events = 119) is less than the limit (256 events).

The limit is already covered by the [`TestLogEvents`](https://github.com/moby/moby/blob/8d056423f8c433927089bd7eb6bc97abbc1ed502/events/events_test.go#L97-L99) unit-test that was added in https://github.com/moby/moby/pull/7452, and tests that the number of events is limited to `eventsLimit`.

This patch removes the test, because it's not needed.

Two other changes were added;

- A small GoDoc change to document the correct limit
- A small update to the unit-test to not use deprecated fields

### CODE REVIEW

**Comment by thaJeztah** [comment]
Wow, what's this error?

```
12:06:18 Step 1/31 : FROM ppc64le/debian:stretch
12:06:18 Get https://registry-1.docker.io/v2/ppc64le/debian/manifests/stretch: EOF
12:06:18 Unable to find image 'docker-powerpc:d887622' locally
12:06:19 docker: Error response from daemon: repository docker-powerpc not found: does not exist or no pull access.
```

This is a bit odd; what's the reference `docker-powerpc` coming from?

```
Unable to find image 'docker-powerpc:d887622' locally
```

**Comment by thaJeztah** [comment]
ping @estesp @tianon - you are more familiar with manifests; perhaps you know what's with that error 😅

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Review by dnephin — APPROVED** [review]
LGTM

**Pull request merged**
