### PR TITLE
Update service_create.md

### PR DESCRIPTION
**Pull request by scjane**
A few minor changes.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vdemeester** [comment]
@scjane can you sign your commit ?

**Comment by scjane** [comment]
Sorry, I failed to amend the commit because my SourceTree client went wrong. I tried to fix it but nothing took effect.

**Comment by cpuguy83** [comment]
@scjane `git commit --amend --no-edit -s`

**Comment by cpuguy83** [comment]
Closing since this doc now lives in github.com/docker/cli.

**Pull request closed without merging**
