### PR TITLE
Remove aufs debugEBusy()

### PR DESCRIPTION
**Pull request by mlaventure**
Since it was introduced no reports were made and lsof seems to cause
issues on some systems.

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

--

Closes: #30782

### CODE REVIEW

**Comment by tonistiigi** [comment]
@anusha-ragunathan Have we got any useful reports with aufs debug data since this was added? Maybe we should just remove it?

Change LGTM but even with the extra goroutine this blocks for 500ms and keeps anything else from mounting. We should only take ID based locks for the long running processes.

**Comment by anusha-ragunathan** [comment]
@tonistiigi : No reports with the added debugEbusy so far.

**Comment by mlaventure** [comment]
Should I just update the PR to remove it altogether then?

**Comment by estesp** [comment]
If not being used, seems reasonable to just PR remove it and skip the added complexity of the goroutine.

**Comment by anusha-ragunathan** [comment]
@mlaventure : SGTM

**Comment by mlaventure** [comment]
Updated PR to remove `debugEBusy()`

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Not sure it's related; failure on experimental;

```
23:48:02 FAIL: docker_cli_plugins_test.go:302: DockerTrustSuite.TestPluginTrustedInstall
23:48:02 
23:48:02 docker_cli_plugins_test.go:320:
23:48:02     c.Assert(err, checker.IsNil)
23:48:02 ... value *errors.errorString = &errors.errorString{s:"\nCommand: /go/src/github.com/docker/docker/bundles/17.04.0-dev/binary-client/docker plugin enable 127.0.0.1:5000/dockercli/trusted-plugin-install:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: error setting up propagated mount dir: invalid argument\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n"} ("\nCommand: /go/src/github.com/docker/docker/bundles/17.04.0-dev/binary-client/docker plugin enable 127.0.0.1:5000/dockercli/trusted-plugin-install:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: error setting up propagated mount dir: invalid argument\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n")
```

**Comment by anusha-ragunathan** [comment]
Failure is unrelated. That test seems to be flaky on janky/experimental. https://github.com/docker/docker/issues/31724

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by allencloud** [comment]
Thanks for your guys to fix this.
Actually we are facing the issue some while. In addition, I think this change could ease the pain, and this change could also be applied to old versions of docker engine. 
Therefore, I suggest that we could back port this change into docker-ee 17.03. Then that action definitely brings much benefits for users.

**Comment by thaJeztah** [comment]
@allencloud this was already being considered for back porting 👍

**Pull request merged**
