### PR TITLE
Docker document translation for Chinese

### PR DESCRIPTION
**Pull request by heidsoft**

### CODE REVIEW

**Comment by heidsoft** [comment]
Docker document translation for Chinese

**Comment by heidsoft** [comment]
What docker is translated into Chinese

**Comment by thaJeztah** [comment]
@heidsoft thanks for opening this pull-request. We decided on *not* translating the documentation (and software) to other languages, for more information, read the discussion here; https://github.com/docker/docker/pull/9509#issuecomment-97877204.
So, for that reason, I will close this PR.

Feel free to comment here if you think I closed this by mistake

**Comment by heidsoft** [comment]
@thaJeztah Thank you, I'm sorry, but I'm not quite familiar with the process. I really like docker

**Comment by thaJeztah** [comment]
No problem! We realise that translating docker (or the documentation) could be helpful for some of our users, but at this moment we don't have the capacity (not enough people) to maintain and support this. We might be able to do this in the future, but not yet.

Thanks for contributing though, much appreciated!

**Pull request closed without merging**
