### PR TITLE
Update libcontainer to be02944484da197166020d6b3f0

### PR DESCRIPTION
**Pull request by crosbymichael**
This fixes the issues with docker exec on 2.6x kernels

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM
tested on RHEL6.6

**Comment by mrunalp** [comment]
:+1:

**Comment by LK4D4** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
@vbatts I wanna test on RHEL!

**Comment by vbatts** [comment]
:cold_sweat:

**Pull request merged**
