### PR TITLE
volume: evaluate symlinks before relabeling mount source

### PR DESCRIPTION
**Pull request by runcom**
Simple reproducer:

```sh
$ mkdir /var/foo
$ touch /var/foo/test
$ ln -s /var/foo /var/bar
$ docker run -ti -v /var/bar:/var/bar:Z fedora sh
sh-4.3# ls -lZ /var/bar/
ls: cannot open directory '/var/bar/': Permission denied
```

@cpuguy83 PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by odeke-em — COMMENTED** [review]
Thank you for the PR @runcom!

I have a couple of suggestions that might be useful or not.
1. Requesting we update the doc of that function
2. Perhaps we could collaborate on a test for this change. This is my first time diving into Docker's source code, so I could use your chaperoning. However, here is an idea for a test, based off the repro you provided
```go
package test

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"testing"
)

func TestSymlinkResolutionBeforeRelabeling(t *testing.T) {
	// Initial setup:
	// Our target repro on the commandline is:
	// 1. $ mkdir /var/foo
	// 2. $ touch /var/foo/test
	// 3. $ ln -s /var/foo /var/bar
	// 4. $ docker run -ti -v /var/bar:/var/bar:Z fedora sh

	// 1.
	scratchDir, err := ioutil.TempDir("", "foo")
	if err != nil {
		t.Fatalf("1. mkdir err: %v", err)
	}
	defer os.RemoveAll(scratchDir)

	// 2.
	f, err := os.Create(filepath.Join(scratchDir, "test"))
	if err != nil {
		t.Fatalf("2. creating test: %v", err)
	}
	f.Close()

	// 3.
	scratchParentDir := filepath.Base(scratchDir)
	symlinkPath := filepath.Join(scratchParentDir, "bar")
	if err := os.Symlink(scratchDir, symlinkPath); err != nil {
		t.Fatalf("3. symlink err: %v", err)
	}
	defer os.RemoveAll(symlinkPath)

	// 4.
	mPt, err := moby.ParseMountRaw(symlinkPath, "fedora")
	if err != nil {
		t.Fatalf("4. mount: %v", err)
	}
	mountPath := symlinkPath + ":Z"
	mountedPath, err := mPt.Setup(mountPath, "fedora", nil)
	if err != nil {
		t.Fatalf("4. expected a successful mount")
	}

	// Perhaps in here, add in the sh step
	if g, w := mountedPath, scratchDir; g != w {
		t.Fatalf("4. resolved paths don't match: got = %q want = %q", g, w)
	}
}
```
Please help me fill in the blanks with the respective code steps, but otherwise I think the general structure of it reflects a 1-to-1 structure in Shell-to-Go of the repro you provided.

**Comment by runcom** [comment]
Docker CI doesn't test with selinux, does it @cpuguy83?

**Comment by cpuguy83** [comment]
Not **this** CI, no.

**Review by cpuguy83 — APPROVED** [review]
Seems ok.
LGTM

**Comment by cpuguy83** [comment]
Needs a rebase, though.

**Comment by runcom** [comment]
rebased

**Comment by thaJeztah** [comment]
Janky failed; possibly due to:

```
13:02:55 volume/volume.go:162:4:warning: ineffectual assignment to err (ineffassign)
13:02:55 volume/volume.go:171:4:warning: ineffectual assignment to err (ineffassign)
```

(although it only prints "warning" if I see correctly)

**Comment by thaJeztah** [comment]
I guess it's confused by the named return variables (perhaps `// nolint: ineffassign`) ? @dnephin thoughts?

**Comment by dnephin** [comment]
I'm pretty sure the linter is correct, the code is wrong (https://play.golang.org/p/bKhOuWeynv). The assignment on line 159 is masking the named return value.

A unit test for `MountPoint.Setup()` would be good.

**Comment by thaJeztah** [comment]
doh, yes! I looked at that, but didn't test it, you're right

@runcom ^^

**Comment by runcom** [comment]
Should be fixed now

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by dnephin** [comment]
I'm not sure what you mean by thoughts on the test. The test should call `MountMount.Setup()` in a way that exercises the new code. If that's not trivial then the code needs to be refactored so that it is easy to unit test.

**Comment by thaJeztah** [comment]
Let me merge this one for now; if this needs a refactor, we can do a refactor + integration test in a follow-up. I opened https://github.com/moby/moby/issues/34998 for tracking this, and assigned it to @runcom

**Pull request merged**
