### PR TITLE
Fix race on cleaning endpoint data

### PR DESCRIPTION
**Pull request by LK4D4**
Race is with any endpoint data reading, for example /containers api.

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by LK4D4** [comment]
It sadly creates deadlock :)

**Comment by LK4D4** [comment]
ping @calavera

**Comment by calavera** [comment]
ouch.

CI is :green_heart: so LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
