### PR TITLE
TestRunDuplicateMount requires the same host

### PR DESCRIPTION
**Pull request by johnstep**
Signed-off-by: John Stephens <johnstep@docker.com>

@yongtang

### CODE REVIEW

**Comment by yongtang** [comment]
LGTM (not a maintainer). Thanks for taking care of it! ❤️

**Comment by vieux** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
Failure in windows should be unrelated (cc @jhowardmsft )
```
...
01:14:10.606 SKIP: docker_cli_ps_test.go:831: DockerSuite.TestPsFormatSize (Test requires a Linux daemon)
01:14:10.784 SKIP: docker_cli_ps_test.go:547: DockerSuite.TestPsGroupPortRange (Test requires a Linux daemon)
01:14:10.947 SKIP: docker_cli_ps_test.go:666: DockerSuite.TestPsImageIDAfterUpdate (Test requires a Linux daemon)
01:14:11.117 SKIP: docker_cli_ps_test.go:528: DockerSuite.TestPsLinkedWithNoTrunc (Test requires a Linux daemon)
01:14:42.205 PASS: docker_cli_ps_test.go:20: DockerSuite.TestPsListContainersBase	28.788s
01:15:26.409 PASS: docker_cli_ps_test.go:309: DockerSuite.TestPsListContainersFilterAncestorImage	43.876s
01:15:26.997 PASS: docker_cli_ps_test.go:568: DockerSuite.TestPsListContainersFilterCreated	0.318s
01:16:10.984 PASS: docker_cli_ps_test.go:449: DockerSuite.TestPsListContainersFilterExited	42.436s
03:20:31.926 Build timed out (after 200 minutes). Marking the build as failed.
```

**Review by AkihiroSuda — APPROVED** [review]
LGTM and merging

**Pull request merged**
