### PR TITLE
uppercase output in docker info related to swarm mode

### PR DESCRIPTION
**Pull request by allencloud**
**\- What I did**
Uppercase output in docker info related to swarm mode to keep consistency

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

/cc @tiborvass @kencochrane (not sure if you're parsing this output)

**Comment by kencochrane** [comment]
LGTM, thanks for checking

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by vdemeester** [comment]
Let's add this 1.12.1 so it's fixed quickly.
/cc @tiborvass

**Pull request merged**
