### PR TITLE
Make events test more deterministic in go1.5

### PR DESCRIPTION
**Pull request by LK4D4**
Now scheduler makes order of events pretty random, so I added little
sleeps to make order intact. Also I renamed to test so name better
describes its nature.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
The 5 ms sleeps scare me a bit. There's no guarantee that 5ms is enough on a heavily loaded system, so I think the test could still be flaky in rare cases, which is a bad situation to have. I'd much prefer changing the test to tolerate different orderings.

**Comment by cpuguy83** [comment]
@aaronlehmann Agreed, scary.

**Comment by LK4D4** [comment]
@cpuguy83 @aaronlehmann I changed test to test only events count, not their order.

**Comment by jfrazelle** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
