### PR TITLE
Restore --default-gateway{,-v6} daemon options.

### LINKED ISSUE #13755: The default-gateway{,-v6} feature was lost during the libnetwork merge
This feature was added by @lebauce in https://github.com/docker/docker/pull/9381, shortly before the libnetwork mega-merge. After the merge, only the CLI flags were left in `daemon/config_linux.go`, but the values were not set in the new bridge network driver.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #13755.

I could not find integration tests for IPv6, so I didn't add any, although I'm not quite comfortable with that. I'm not sure adding them would be easy, as the tests would depend on proper IPv6 configuration, and I couldn't get the `--bip` option to work anyway. If someone wants to help me with this, I would be glad to try it.

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @mrjana

**Comment by mrjana** [comment]
LGTM

**Comment by thaJeztah** [comment]
@mrjana @LK4D4 any suggestions on the integration test as well?

**Comment by mrjana** [comment]
@thaJeztah @eolamey already added the required integration tests

**Comment by thaJeztah** [comment]
@mrjana oh! sorry, I saw the question and didn't check further. Apologies for the noise :)

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @eolamey!

Ping @jfrazelle for cherry pick

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
