### PR TITLE
Do not enable kmem on RHEL7 kernels

### PR DESCRIPTION
**Pull request by kolyshkin**
### 1. bump runc
Changes: https://github.com/opencontainers/runc/compare/a00bf0190895...9f1e94488e5e4

This is primarily to pull in https://github.com/opencontainers/runc/pull/1921

### 2. runc.installer: add nokmem build tag for rhel7 kernel
    
In case we're running on RHEL7 kernel, which has non-working
and broken kernel memory controller, add 'nokmem' build tag
so that runc never enables kmem accounting.
    
For more info, see the following runc commit:
https://github.com/opencontainers/runc/commit/6a2c1559684
    
This behavior can be overriden by having `RUNC_NOKMEM` environment
variable set (e.g. to empty value to disable setting nokmem).

### CODE REVIEW

**Comment by kolyshkin** [comment]
CI failure in janky (probably unrelated but I haven't seen it before)
```
00:07:10.767 time="2018-11-01T23:17:43Z" level=info msg="Trying to get region from EC2 Metadata"
00:07:10.767 time="2018-11-01T23:17:43Z" level=info msg="Log stream already exists" errorCode=ResourceAlreadyExistsException logGroupName= logStreamName= message= origError="<nil>"
00:07:10.768 --- FAIL: TestLogBlocking (0.00s)
00:07:10.768     cloudwatchlogs_test.go:255: Expected to be able to read from stream.messages but was unable to
00:07:10.768 time="2018-11-01T23:17:43Z" level=error msg=Error
00:07:10.768 time="2018-11-01T23:17:43Z" level=error msg="Failed to put log events" errorCode=InvalidSequenceTokenException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
00:07:10.768 time="2018-11-01T23:17:43Z" level=error msg="Failed to put log events" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
00:07:10.769 time="2018-11-01T23:17:43Z" level=info msg="Data already accepted, ignoring error" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token"
00:07:10.769 FAIL
00:07:10.769 coverage: 71.7% of statements
00:07:10.769 FAIL	github.com/docker/docker/daemon/logger/awslogs	0.113s
00:07:11.627 Build step 'Execute shell' marked build as failure
```

**Review by AkihiroSuda — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
Should we update the Makefile to set the correct build-flag for the 3.10 kernels?

**Comment by kolyshkin** [comment]
> Should we update the Makefile and Dockerfile to set the correct build-flag for the 3.10 kernels?

I think this belongs to packaging -- specifically, when we create packages for RHEL7. I was looking at it (in https://github.com/docker/docker-ce-packaging) but got lost :(

Sure we can do it here instead.

**Comment by kolyshkin** [comment]
@thaJeztah makes sense. Please see added commit.

**Review by thaJeztah — APPROVED** [review]
SGTM

ping @tianon PTAL ❤️

**Comment by thaJeztah** [comment]
Let's merge this; looks good to me, but @tianon if there's anything to improve/address in the installer script, let me know 🤗

**Pull request merged**
