### PR TITLE
Vendor swarmkit f420c4b9e1535170fc229db97ee8ac32374020b1

### PR DESCRIPTION
**Pull request by nishanttotla**
Changes in this vendoring:

```
$ git log --no-merges --oneline 8f053c2030ebfc90f19f241fb7880e95b9761b7a..f420c4b9e1535170fc229db97ee8ac32374020b1
87d3730 orchestrator: Add test debugging
dccbce3 It's possible for a new session to start before the previous session has completely finished cleaning up in the fake dispatcher.  Therefore, in the cleanup, don't set the current open session to nil without checking if the current open session has changed.  This should prevent some false negative test assertions where it seems like a session has never been established even though it has.
ff551b0 agent: Resolve deadlock in run
8edbb92 Adding PlatformFilter for scheduling
8c72dcf trigger tick when resources could be freed up
5f8f5ac scheduler should re-evaluate pending tasks after any task removal
78f240e [protos] Adding Platforms field to TaskSpec.Placement
fde7e71 Fix bug where we could not cross-sign an RSA certificate with an ECDSA certificate and vice versa.
51309e8 Connections to a local dispatcher can’t really be closed, so a session can’t really be restarted because closing a session just closes the connection.  When this happens, it just starts up another session without closing the previous one.
c21a196 Add details field to log message proto
6b36068 Adding test case to verify vip allocation in ingress mode
54c7200 Fixing leak in Ingress VIP allocation on port publish/remove
dac5c30 ca: Delay between retries when retrieving certs
745e1ea Avoid writing to Network.Spec in allocatePools
a6e08a0 Watch API monitors local store for change
7a427bf rename storeapi to watchapi
```

### CODE REVIEW

**Comment by nishanttotla** [comment]
Test failure seems unrelated.

Ping @vdemeester

cc @dongluochen the Watch API is part of this vendor.

**Review by vdemeester — APPROVED** [review]
LGTM 👼
/cc @aaronlehmann

**Comment by aaronlehmann** [comment]
LGTM

**Comment by nishanttotla** [comment]
Ping @vdemeester can we merge this?

**Pull request merged**
