### PR TITLE
Bump Go to version 1.5.3

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

### CODE REVIEW

**Comment by tianon** [comment]
Mind including the files in `contrib/builder` too? :smile:

**Comment by tiborvass** [comment]
@tianon for you, I don't mind :)

I ran the generate.sh files, it changed a SECCOMP envvar. Hope thats fine

**Comment by tianon** [comment]
Oh hmm, that'll actually fail to build. :cry:

**Comment by tiborvass** [comment]
@tianon ok so i'll remove the seccomp change and will let you and/or @jfrazelle deal with that

**Comment by tianon** [comment]
Ok, sounds good. :+1:

**Comment by tianon** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by tiborvass** [comment]
windows seems to be red only because go version differs with the CI... weird

**Comment by jfrazelle** [comment]
i fixed for future til we update all servers :)

**Pull request merged**
