### PR TITLE
Clarify data volume init with existing data

### PR DESCRIPTION
**Pull request by kentoj**
Though I am not clear on the intent of the sentence if it means that existing data in the base image is copied into the new volume then the additions I propose make that more clear than the present language.

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by kentoj** [comment]
I just added my signature. What generally is the build ETA if all of the checks pass on a documentation PR?

**Comment by moxiegirl** [comment]
LGTM.

Documentation PRs merge into master.  Master rebuilds and you should see you work shortly on http://docs.master.dockerproject.com/.

ping @docker/docs-owners

**Comment by moxiegirl** [comment]
ping @jamtur01 @SvenDowideit @fredlf @thaJeztah

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
