### PR TITLE
Add missing fields for NetworkSettings

### PR DESCRIPTION
**Pull request by moxiegirl**
Dump from 1.10.1 has this fields.

Signed-off-by: Kanstantsin Shautsou kanstantsin.sha@gmail.com

Close and carry #20377
Include David's request

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
@calavera @thaJeztah review and merge at will

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @moxiegirl 

LGTM

**Comment by KostyaSha** [comment]
> Close and carry #20377

This doesn't close associated issue, probably should be "Carry and close #20377" to get magic GH actions.

**Comment by thaJeztah** [comment]
removing cherry-pick; this will go out with the 1.11 release

**Comment by moxiegirl** [comment]
Thanks @thaJeztah

**Pull request merged**
