### PR TITLE
setting device-mapper-libs version dependency for centos 7 rpm

### LINKED ISSUE #17379: centos-70 docker-engine dependency device-mapper version
I am running into the same issue that was previously resolved in #12108. yum update device-mapper resolves the issue. Looks like a dependency version issue with device-mapper.

```
[root@resources-183-centos-70 ~]# /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://127.0.0.1:2376 --label=environment="test" --label=foo="bar" --pidfile=/var/run/docker.pid --tlsverify=true --tlscacert=/tmp/kitchen/docker_service_default/ca.pem --tlscert=/tmp/kitchen/docker_service_default/server.pem --tlskey=/tmp/kitchen/docker_service_default/server-key.pem
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] Listening for HTTP on tcp (127.0.0.1:2376)
/usr/bin/docker: relocation error: /usr/bin/docker: symbol dm_task_get_info_with_deferred_remove, version Base not defined in file libdevmapper.so.1.02 with link time reference
[root@resources-183-centos-70 ~]# docker -v
Docker version 1.8.3, build f4bf5c7
[root@resources-183-centos-70 ~]# uname -an
Linux resources-183-centos-70 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@resources-183-centos-70 ~]# cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)
[root@resources-183-centos-70 ~]# yum info docker-engine
Installed Packages
Name        : docker-engine
Arch        : x86_64
Version     : 1.8.3
Release     : 1.el7.centos
Size        : 27 M
Repo        : installed
From repo   : docker-main-repo
Summary     : The open-source application container engine
URL         : https://dockerproject.org
License     : ASL 2.0
```

### PR DESCRIPTION
**Pull request by chasebolt**
resolves #17379

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @Djelibeybi  don't know if oracle linux needs this too

**Comment by Djelibeybi** [comment]
LGTM. We already pull in a new device-mapper via our kernel-uek RPM, but it can't hurt here either. You can go ahead and add `0%{?oraclelinux} >=7` to that if statement.

**Comment by chasebolt** [comment]
i went ahead and added `0%{?rhel} >= 7` along with `0%{?oraclelinux} >=7`

**Comment by thaJeztah** [comment]
LGTM

@jfrazelle PTAL for the last changes

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
