### PR TITLE
Install script rhel fix

### PR DESCRIPTION
**Pull request by adamjk-dev**
Fix for the following issue: https://github.com/docker/docker/issues/24039

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @adamjk-dev. Can you "squash" and sign-off your commits, so that there's only a single commit in your PR? you can find some additional information here; https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently

**Comment by kencochrane** [comment]
LGTM

**Comment by adamjk-dev** [comment]
To be honest, I am not sure if that fixed it or not. I still see 3 commits in my fork.

**Comment by thaJeztah** [comment]
Looks like you need to rebase, and squash those commits. To do so, first make sure your local fork is up to date;

```
git fetch --all
```

Then you can rebase your PR / branch interactively;

```
git rebase -i upstream/master
```

That opens an editor showing your commits;

```
pick c8248e4 updates to fix install script for RHEL
pick 67fbac8 updates to fix install script for RHEL
pick 290afda fixing install script for rhel7
pick 931bfb7 fixing install script for rhel7
```

Change those lines to;

```
pick c8248e4 updates to fix install script for RHEL
squash 67fbac8 updates to fix install script for RHEL
squash 290afda fixing install script for rhel7
squash 931bfb7 fixing install script for rhel7
```

Which basically says; combine ("squash") all the previous 3 commits with the last one ("pick")

After you save the file, the rebase continues, and another file is opened, showing the commit messages for all those commits.

You can there comment-out lines that are not needed in the final commit message (just put a `#` in front of those lines).

Then save the file to complete the rebase.

Once done, you need to *force* push your branch to github;

```
git push -f origin
```

And that should update the PR here on GitHub

Hope it helps, if not, let me know then I can carry it for you

**Comment by adamjk-dev** [comment]
Thanks a bunch. I haven't done that before, very useful. I swore I did that last time but I think I did a 'git pull' before that last 'git push' so I ended up with the same commits. Looks like I have one commit this time. Appreciate it.

**Comment by thaJeztah** [comment]
excellent!

LGTM

**Comment by thaJeztah** [comment]
merging, because CI doesn't run these

**Comment by adamjk-dev** [comment]
Great, thanks. I don't know why my commits don't link my github account or gravatar. I know this isn't the place, but any ideas?

**Comment by kencochrane** [comment]
@adamjk-dev if you go to the commit (https://github.com/docker/docker/pull/24069/commits/485c27e18680f5eaeefe5de7f7916ba23f66c8f0) and then click on the blue question mark next to your name, it will tell you what is wrong. It is usually an issue where the email address you have configured locally in git doesn't match what you have in github, and you need to add that email address to github, so it knows how to associate the commits to the right account.

**Comment by adamjk-dev** [comment]
Ah, I don't see a question mark by my name but I imagine it is my email. My local global git config uses my corporate email address to commit to an internal GitLab. But, i didn't set my local user and email when I cloned the repo. So, it likely picked up my corporate email and name, which aren't on my github account. Thanks.

**Comment by thaJeztah** [comment]
I think you can add multiple e-mail addresses on GitHub, possibly that fixes it

**Comment by adamjk-dev** [comment]
Yep, I will add it just in case. I guess I used to just set local options but if it picks this up that would be great. Thanks again.

**Comment by kencochrane** [comment]
@adamjk-dev question mark is gone, looks like it worked.

**Comment by adamjk-dev** [comment]
Cool, thank you both.

**Pull request merged**
