### PR TITLE
Windows: Bump RW layer size

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

@johnstep @darrenstahlmsft As mentioned offline... PTAL

This bumps the size of the RW layer (sandbox.vhdx) from the default (20GB, hard coded in the platform) to 127GB (purely as the default size of a VHD in Hyper-V) for the builder RUN scenario where users are adding a lot of data during a RUN statement (eg while debugging https://github.com/moby/moby/issues/32838).  Done local verification using diskmgmt.msc watching disk being attached/detached to verify it's operating as expected. 

image

It does not change the default size for a `docker run` (which can be controlled anyway through `--storage-opt`)

@friism FYI.

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by mikebolland** [comment]
Is this the first part of a fix for https://github.com/moby/moby/issues/33586?_pjax=%23js-repo-pjax-container ?

**Comment by jhowardmsft** [comment]
@mikebolland No, that is unrelated.

**Pull request merged**
