### PR TITLE
First batch of Windows-Windows TestBuild CI enabling

### PR DESCRIPTION
**Pull request by darstahl**
This re-enables some TestBuild\* tests for Windows-Windows CI that are currently working, and reworks those that need slight changes to work on Windows.

More incoming.

Signed-Off-By: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by calavera** [comment]
Nice, thanks!

LGTM

**Comment by darrenstahlmsft** [comment]
Please hold on merging this due to some Busybox for windows image changes that are needed. They should go in soon.

**Comment by jhowardmsft** [comment]
Have merged the busybox changes. This PR is ready for further review.

**Comment by thaJeztah** [comment]
LGTM nice!

**Pull request merged**
