### PR TITLE
hack: add script to regenerate certificates and update test-certs

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/moby/moby/pull/40353

Certificates were originally added in https://github.com/moby/moby/commit/c000cb64712349141596318dea2a8de2462c8f81 (https://github.com/moby/moby/pull/3068), but did not include a script to generate them. Current versions of Go expect certificates to use SAN instead of Common Name fields, so updating the script to include those;

    x509: certificate relies on legacy Common Name field, use SANs or temporarily
    enable Common Name matching with GODEBUG=x509ignoreCN=0

Some fields were updated to be a bit more descriptive (instead of "replaceme"), and the `-text` option was used to include a human-readable variant of the content.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
failure on arm is a known flaky test; https://github.com/moby/moby/issues/42357

```
[2021-05-18T08:05:56.917Z] --- FAIL: TestDaemonHostGatewayIP (5.39s)
[2021-05-18T08:05:56.917Z]     daemon_linux_test.go:161: [db2862c8d069f] failed to start daemon with arguments [--data-root /go/src/github.com/docker/docker/bundles/test-integration/TestDaemonHostGatewayIP/db2862c8d069f/root --exec-root /tmp/dxr/db2862c8d069f --pidfile /go/src/github.com/docker/docker/bundles/test-integration/TestDaemonHostGatewayIP/db2862c8d069f/docker.pid --userland-proxy=true --containerd-namespace db2862c8d069f --containerd-plugins-namespace db2862c8d069fp --containerd /var/run/docker/containerd/containerd.sock --host unix:///tmp/docker-integration/db2862c8d069f.sock --debug --storage-driver overlay2 --host-gateway-ip=6.7.8.9] : [db2862c8d069f] daemon exited during startup: exit status 1
```

**Review by tianon — APPROVED** [review]
Exactly the level of complexity and line count I expected when I saw the PR title :sob:

LG(enough)TM

**Comment by thaJeztah** [comment]
> Exactly the level of complexity and line count I expected when I saw the PR title 😭

Oh man, I went through multiple iterations; at first tried https://github.com/dmcgowan/quicktls (which if super handy), and even contributed a PR to it to add SAN support (https://github.com/dmcgowan/quicktls/pull/3) but that didn't set the "subject" (`CN`) that was used by the Authz plugin. Tried https://github.com/FiloSottile/mkcert, which was recommended as an easy tool (and created by one of Go's security people, so seemed like a good choice), however that one also didn't offer the ability to set the CN (fields were filled by some "dummy" data). It also refuses to use `*` as SAN (which could be "correct", or not.. ? `openssh` accepts it, but TBH not sure if it's valid.. tests pass, so 🤷‍♂️) 

So... time to dive into [the `openssh` man pages](https://www.openssl.org/docs/man1.1.1/man1/), which was "down the rabbit hole". `openssh` design really looks to be "security is important to us, so we make this as complicated as can be for you. We hope you mess things up, so that security teams won't be out of a job!".

- learned that [`openssh req`](https://www.openssl.org/docs/man1.1.1/man1/openssl-req.html) can _either_ produce a csr _or_ an actual certificate (if `-x509` is set) 🤯 (great! so we can do it all in a single step... right?)
- when using `openssh req -x509`, the `-addext` option can be used to set x509 options (awesome! I can pass the options on the command-line, that way I don't need to create some config file 🥳)
- So I just pass the `-CA` and `-CAkey` to sign... wait.. those flags are not present?
- ok, nevermind, two steps it is then; create the CSR with all the options set, and then create / sign the certificate in the second step with [`openssh x509`](https://www.openssl.org/docs/man1.1.1/man1/openssl-x509.html)
- ahm.. right, so while x509 options can be included in a CSR, they are not inherited by `openssh x509`
- no worries! I'll just move the `-addext` flag to the `openssh x509` step. oh.. right... that one doesn't support passing them on the command line
- back to creating a "config" file then 😞

**Comment by tianon** [comment]
Yepppp, it's a mess (slightly better in OpenSSL 3.0+ IIRC, but still pretty ugly).  [I can definitely relate.](https://github.com/docker-library/docker/pull/166) :sweat_smile:

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
