### PR TITLE
Allow system.MkDirAll() to be used as drop-in for os.MkDirAll()

### PR DESCRIPTION
**Pull request by thaJeztah**
also renamed the non-windows variant of this file to be consistent with other files in this package

### CODE REVIEW

**Comment by thaJeztah** [comment]
@ddebroy @kolyshkin ptal

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@cpuguy83 LGTY?

**Review by tiborvass — APPROVED** [review]

**Comment by thaJeztah** [comment]
ugh; looks like this PR was outdated, and broke master; opened https://github.com/moby/moby/pull/39809 to fix the build

**Pull request merged**
