### PR TITLE
overlay2: add redirect_dir=on

### PR DESCRIPTION
**Pull request by kolyshkin**
As reported in https://github.com/moby/moby/issues/39566, there are bad side effects in case overlayfs' `redirect_dir` parameter is not enabled, by setting an appropriate mount option.
    
Note that
    
1. We do not change a parameter globally as there may be others depending on its current value.
2. We do not check a parameter's current value, as it might change any time.

Tested locally, here's the effect of the change:
```
$ journalctl -u docker -b0 | grep -E 'indexOff|extraOpts'
Jul 29 16:36:23 kd dockerd[2881]: time="2019-07-29T16:36:23.459985932-07:00" level=debug msg="backingFs=extfs, projectQuotaSupported=false, indexOff=\"index=off,\"" storage-driver=overlay2
Jul 30 14:47:17 kd dockerd[19177]: time="2019-07-30T14:47:17.515083218-07:00" level=debug msg="backingFs=extfs, projectQuotaSupported=false, extraOpts=\"index=off,redirect_dir=on,\"" storage-driver=overlay2
```

### CODE REVIEW

**Comment by dmcgowan** [comment]
```
2. If the "redirect_dir" feature is enabled, then the directory will be
   copied up (but not the contents).  Then the "trusted.overlay.redirect"
   extended attribute is set to the path of the original location from the
   root of the overlay.  Finally the directory is moved to the new
   location.
```

Naive diff must be true to enable features like this. Not sure if it is already always true, but I don't see any conditional logic here.

**Comment by kolyshkin** [comment]
> Naive diff must be true to enable features like this

Wait, are you saying that the overlay2 should work for either value of `redirect_dir`? In this case I'm not sure why it was not working for @longquan7 (as per https://github.com/moby/moby/issues/39566)

Also, it looks like `doesSupportNativeDiff()` tries to figure out whether redirect_dir is enabled or not, while instead we can just change that to any way we like, on a per-mount basis...

**Comment by longquan7** [comment]
@kolyshkin The feature function corresponding to overlayfs can be used normally only when the redirect_dir feature switch is enabled.My problem is that the OS does not open the corresponding feature switch when using this feature.

**Comment by thaJeztah** [comment]
@kolyshkin this one needs a rebase

**Comment by thaJeztah** [comment]
ping @kolyshkin what's the status on this one?

**Comment by kolyshkin** [comment]
> ping @kolyshkin what's the status on this one?

Better late than never, I guess this one is not needed :)

**Pull request closed without merging**
