### PR TITLE
Remove some maintainers 👼

### PR DESCRIPTION
**Pull request by vdemeester**
@albers, @aluzzardi, @ehazlett, @icecrime, @lk4d4, @mavenugo 🤗 😽 😽 👼 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by icecrime** [comment]
giphy

**Review by thaJeztah — APPROVED** [review]
LGTM 🤗

**Comment by thaJeztah** [comment]
Looool

**Comment by albers** [comment]
LGTM 😢

**Comment by ripcurld0** [comment]
Thanks so much @albers, @aluzzardi, @ehazlett, @icecrime, @LK4D4, @mavenugo

**Comment by ehazlett** [comment]
LGTM

**Review by dnephin — APPROVED** [review]

**Comment by icecrime** [comment]
Betrayed by my own code, oh the irony! 😂 

image

**Pull request merged**
