### PR TITLE
Remove CLI doc entry related to API-only function

### LINKED ISSUE #10278: docker documentation incorrectly indicates ability to set volumes with start command
https://docs.docker.com/reference/commandline/cli/#create
"Note that volumes set by create may be over-ridden by options set with start."

It does not appear possible to set a volume option in the start command.

### PR DESCRIPTION
**Pull request by cpuguy83**
Closes #10278

### CODE REVIEW

**Comment by LK4D4** [comment]
@cpuguy83 It is because you can't specify volumes on `docker create`?

**Comment by cpuguy83** [comment]
@LK4D4 Because you can't specify volumes on `docker start`

**Comment by LK4D4** [comment]
LGTM then

**Comment by SvenDowideit** [comment]
LGTM - @fredlf @jamtur01 @spf13 @moxiegirl

**Comment by jamtur01** [comment]
LGTM

**Comment by fredlf** [comment]
LGTM

**Pull request merged**
