### PR TITLE
minor cosmetic change to client output on pull

### PR DESCRIPTION
**Pull request by jessfraz**
@calavera this should be added to the release, dont worry its just a log line

cc @diogomonica @NathanMcCauley

### CODE REVIEW

**Comment by diogomonica** [comment]
LGTM if janky is happy.

**Comment by NathanMcCauley** [comment]
LGTM

**Comment by LK4D4** [comment]
I personally always use debug.

**Comment by LK4D4** [comment]
LGTM

**Comment by calavera** [comment]
cherry picked into #15091

**Comment by jfrazelle** [comment]
You the besttttt

**Pull request merged**
