### PR TITLE
Bumping libnetwork to v0.7.2-rc1

### PR DESCRIPTION
**Pull request by mavenugo**
- Fixed a stale endpoint issue on overlay networks during ungraceful restart

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by thaJeztah** [comment]
this is already resolved in master, correct?

**Comment by tophj-ibm** [comment]
@thaJeztah the power job doesn't work on the bump v1.11.1 branch because the go fix hasn't been cherry-picked into that branch yet #22227, although I like the thought!

**Comment by thaJeztah** [comment]
@tophj-ibm ah! yes, I thought, let's start all jobs

**Comment by thaJeztah** [comment]
ping @jhowardmsft any idea what the WindowsTP5 issue is here?

**Comment by jhowardmsft** [comment]
That makes no sense at all. Will look closer when in the office. Restarted for now.

**Comment by jhowardmsft** [comment]
Huh. This is 1.11. The CI servers can no longer run that. I'll try and figure something out.

**Comment by thaJeztah** [comment]
@jhowardmsft ah, alright, we should probably just ignore then; given that these builds are not shipped on Windows

**Comment by mavenugo** [comment]
@thaJeztah yes. this is resolved in master already.

**Comment by LK4D4** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by cpuguy83** [comment]
windows CI just can't run this, and powerpc is obviously broken, but not by this.
Merging.

**Pull request merged**
