### PR TITLE
vendor: opencontainers/runtime-spec v1.0.2

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/opencontainers/runtime-spec/compare/29686dbc5559d93fb1ef402eeda3e35c38d75af4...v1.0.2

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
rebased to trigger CI

**Comment by thaJeztah** [comment]
This keeps failing on ppc64le; wondering if it's a legitimate issue;

```
[2020-05-06T12:12:44.681Z] + docker run --rm -t --privileged -v /home/docker/workspace/moby_PR-40908/bundles:/go/src/github.com/docker/docker/bundles --name docker-pr3 -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT=99c36798f8d86847d32116be9b0fef37746ff02f -e DOCKER_GRAPHDRIVER -e VALIDATE_REPO=https://github.com/moby/moby.git -e VALIDATE_BRANCH=master docker:99c36798f8d86847d32116be9b0fef37746ff02f hack/test/unit
[2020-05-06T12:12:44.681Z] Unable to find image 'docker:99c36798f8d86847d32116be9b0fef37746ff02f' locally
[2020-05-06T12:12:44.970Z] docker: Error response from daemon: manifest for docker:99c36798f8d86847d32116be9b0fef37746ff02f not found.
[2020-05-06T12:12:44.970Z] See 'docker run --help'.
script returned exit code 125
```

**Comment by thaJeztah** [comment]
Pushed a commit to see what images are present after building the dev image completes

**Comment by thaJeztah** [comment]
OK something looks wrong here; this is the last output from the "build DEV image"

https://ci-next.docker.com/public/job/moby/job/PR-40908/4/execution/node/219/log/?consoleFull

```
15:25:45  + make bundles/buildx
15:25:45  make: command: Command not found
15:25:45  make: command: Command not found
15:25:45  mkdir bundles
15:25:45  docker build -f ${BUILDX_DOCKERFILE:-Dockerfile.buildx} -t "moby-buildx:${BUILDX_COMMIT:-latest}" \
15:25:45  	--build-arg BUILDX_COMMIT \
15:25:45  	--build-arg BUILDX_REPO \
15:25:45  	--build-arg GOOS=$(if [ -n "" ]; then echo ; else go env GOHOSTOS || uname | awk '{print tolower($0)}' || true; fi) \
15:25:45  	--build-arg GOARCH=$(if [ -n "" ]; then echo ; else go env GOHOSTARCH || true; fi) \
15:25:45  	.
5:25:45  /bin/sh: 4: go: not found
15:25:45  /bin/sh: 5: go: not found
15:25:48  Sending build context to Docker daemon  57.72MB
...
...
15:35:47  #78 exporting to oci image format
15:35:47  #78 exporting layers
15:37:54  #78 exporting layers 118.6s done
15:37:54  #78 exporting manifest sha256:e76a62c7a4163a5a1f1195a163b3b326a77eef7abd19c68e1e648f07657cf65c done
15:37:54  #78 exporting config sha256:4493dded1cb4383f40f6acbb705a24c467935fd274edf0f2b27dbdb97fecabd4 done
15:37:54  #78 sending tarball
15:38:04  #78 sending tarball 19.1s done
15:38:04  #78 DONE 137.7s
15:38:04
15:38:04  #79 importing to docker
15:38:07  #79 DONE 3.0s
```

But the stap directly following that, I check if the image is there, and it's missing:
https://ci-next.docker.com/public/job/moby/job/PR-40908/4/execution/node/320/log/

```
15:38:08  + docker image ls -a
15:38:08  REPOSITORY          TAG                                        IMAGE ID            CREATED             SIZE
15:38:08  docker              0a5cec2833f82a6ad797d70acbf9cbbaf8956017   86b579e26368        47 hours ago        2.07GB
15:38:08  docker              fd784ce7c10376247c08dae2083c07ea6300588f   960bfb825c7a        5 days ago          2.07GB
15:38:08  <none>              <none>                                     86d83c334c4c        5 days ago          2.07GB
15:38:08  docker              7e9b4c746de99e0d9d735eee4afa5d7f6f138f06   86aec1508f59        6 days ago          2.07GB
15:38:08  <none>              <none>                                     3ee70f101c94        6 days ago          2.07GB
15:38:08  docker              f6163d3f7a10c5d01a92bc8b86e204d784b2f6d6   9d79b04c6734        6 days ago          2.07GB
15:38:08  docker              c3b3aedfa4ad51de0a2ebfd08a716f585390b512   5d0568e17220        6 days ago          2.07GB
15:38:08  <none>              <none>                                     2adffe201d47        6 days ago          2.07GB
15:38:08  docker              65bfb29603953d57806ea4c4def8d12cf3462ab8   aede9d1c967b        6 days ago          2.07GB
15:38:08  docker              cc0dfb6e7b22ad120c60a9ce770ea15415767cf9   4611ecc2cf8c        7 days ago          2.07GB
15:38:08  <none>              <none>                                     8d86d01a0a67        7 days ago          2.07GB
15:38:08  docker              45369c61a48c755f3baee416f117e47d0127a42d   82815152aada        8 days ago          2.07GB
15:38:08  docker              4839b27a1fb9abcfb2142d46a6afe40bdf9f150b   1d7eb6287117        11 days ago         2.07GB
15:38:08  <none>              <none>                                     0a7262c40924        11 days ago         2.07GB
15:38:08  docker              5e4dfaceed137cc1033410da785c62c8d72c1078   62937ee1eda0        12 days ago         2.07GB
15:38:08  docker              f6a5ccf492e8eab969ffad8404117806b4a15a35   1f66424e0bdb        2 weeks ago         2.07GB
15:38:08  docker              ba8129b28a23f8360005bb57054cd8815542eb67   ce2cae8b3f22        2 weeks ago         2.07GB
15:38:08  docker              71626b7bdf9bb0b2b4d5bcc256def14720eb9475   4a9c4faced84        2 weeks ago         2.07GB
15:38:08  docker              55e6d7d36fafcfbd5c97b019a1652f63231ebcf5   02cbcfc6a182        2 weeks ago         2.07GB
15:38:08  <none>              <none>                                     1fa34df51964        2 weeks ago         2.07GB
15:38:08  <none>              <none>                                     2e2feb19a798        2 weeks ago         823MB
15:38:08  moby-buildx         latest                                     d0e3b6e42eb3        2 weeks ago         823MB
15:38:08  <none>              <none>                                     63a8f53ac3a3        2 weeks ago         1.92GB
15:38:08  <none>              <none>                                     ee9bd48104ac        2 weeks ago         1.8GB
15:38:08  <none>              <none>                                     5be2a9f02b8d        2 weeks ago         1.8GB
15:38:08  <none>              <none>                                     dc28355b2aa2        2 weeks ago         1.8GB
15:38:08  <none>              <none>                                     4225facf5511        2 weeks ago         851MB
15:38:08  <none>              <none>                                     888416c7ed41        2 weeks ago         834MB
15:38:08  <none>              <none>                                     0198b2b36a1f        2 weeks ago         834MB
15:38:08  <none>              <none>                                     b64a722b17c7        2 weeks ago         834MB
15:38:08  <none>              <none>                                     49494feb27ed        2 weeks ago         787MB
15:38:08  moby/buildkit       buildx-stable-1                            f350ba335c4b        2 weeks ago         84.1MB
15:38:08  busybox             latest                                     c2e2aa84fd4b        3 weeks ago         5.92MB
15:38:08  golang              1.12.10-stretch                            ebd73b5ebd31        6 months ago        787MB
15:38:08  + docker image inspect docker:8afd4ca273959d22775a9504445c7bb29a31edcc
15:38:08  []
15:38:08  Error: No such image: docker:8afd4ca273959d22775a9504445c7bb29a31edcc
```

**Comment by thaJeztah** [comment]
So, no idea how that could be related to this PR; if I see correctly, those steps are done using the `docker` daemon that's running on the host, so unless building the image failed, it should not depend on the PR 🤔

**Comment by thaJeztah** [comment]
Possibly related to https://github.com/docker/buildx/issues/253

**Comment by thaJeztah** [comment]
```
15:25:03  Running on ppc64le-ubuntu-34 in /home/docker/workspace/moby_PR-40908
```

https://ci-next.docker.com/public/computer/ppc64le-ubuntu-34/

**Comment by thaJeztah** [comment]
New run, this time running on `20:56:49  Running on ppc64le-ubuntu-32 in /home/docker/workspace/moby_PR-40908`

**Comment by thaJeztah** [comment]
Looks to be green again, so could've been something on those nodes; rebased and removed my temporary debugging commit

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
