### PR TITLE
Carry 17329

### PR DESCRIPTION
**Pull request by cpuguy83**
carry of https://github.com/docker/docker/pull/17329

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by runcom** [comment]
This is not working anymore in 1.11 :|

**Comment by runcom** [comment]
ping @thaJeztah

**Comment by coolljt0725** [comment]
@runcom  it's work for me
<pre><code>[lei@fedora ~]$ docker load -i nginx.tar
78dbfa5b7cbc: Loading layer [==================================================>] 130.9 MB/130.9 MB
5f70bf18a086: Loading layer [==================================================>] 1.024 kB/1.024 kB
9d7c55c6d3f5: Loading layer [==================================================>] 10.12 MB/10.12 MB
65d087b2d4e1: Loading layer [==================================================>] 3.584 kB/3.584 kB
[lei@fedora ~]$ docker version
Client:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Apr  1 09:40:44 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Apr  1 09:40:44 2016
 OS/Arch:      linux/amd64
</code></pre>

**Comment by runcom** [comment]
:confused: 
```
11:37:03 amurdaca at localhost in ~ docker load -i busybox.tar
11:37:12 amurdaca at localhost in ~
```

**Comment by runcom** [comment]
```sh
11:39:21 amurdaca at localhost in ~ docker version
Client:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   4a7bd7e
 Built:        Fri Apr  1 11:38:39 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   4a7bd7e
 Built:        Fri Apr  1 11:38:39 2016
 OS/Arch:      linux/amd64
 Experimental: true
11:39:25 amurdaca at localhost in ~ docker load -i busybox.tar
# no output
```

**Comment by runcom** [comment]
nope, it's not working for me and no daemon logs :confused:

**Comment by thaJeztah** [comment]
@runcom are you running it in a small terminal? IIRC, the progress bars are automatically hidden if the terminal is not wide enough

**Comment by runcom** [comment]
Mmm weird cause I see the the bars for pull operation but really docker isn't display any progress bar for docker load

**Comment by thaJeztah** [comment]
No ideas then, but I'm afk, so can't check

**Pull request merged**
