### PR TITLE
Fix TestAPIDockerAPIVersion on windows

### PR DESCRIPTION
**Pull request by vdemeester**
Fixing my own mistake 😅. 
PS: this causes all windowsRS1 build to fail (master, PRs) so, should be merged quick 👼 🙏 

/cc @thaJeztah @AkihiroSuda @johnstep 

🦁

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM :-)

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green

**Comment by vdemeester** [comment]
windowsRS1 is green 💚

**Comment by vdemeester** [comment]
Janky failed on `09:16:10 FAIL: docker_cli_push_test.go:608: DockerRegistryAuthTokenSuite.TestPushMisconfiguredTokenServiceResponseError`, which is identified and being worked on 😉

**Comment by thaJeztah** [comment]
haha, you fix one, but got bitten by the other one

**Comment by vdemeester** [comment]
Let's merge are the failures are being worked on 👼

**Pull request merged**
