### PR TITLE
Update swagger.yaml with recent API changes

### PR DESCRIPTION
**Pull request by bfirsh**
I have gone through the past few months of changes to the API to ensure the definition in swagger.yaml is up-to-date. It should now be correct (hopefully!) up to and including 2d4203222574623b10d94817b9959a08698f516b.

This is part of the work to generate API documentation from a Swagger definition, which is going on here: https://github.com/docker/docker.github.io/pull/210

Any subsequent changes to `docs/reference/api/docker_remote_api_v1.25.md` will need to be reflected in this file until we move over to the generated API documentation. It would be nice to get pull request authors to start doing that now, but it's not essential. We can do one last sweep to ensure it's up-to-date before we switch over to the new documentation.

Eventually, [we will be generating the actual API server from this definition](https://github.com/docker/docker/issues/27919), so it will automatically be kept in sync because it _has_ to be kept up to date!

/cc @dnephin

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

but needs rebase

**Comment by bfirsh** [comment]
@dnephin done!

**Comment by vieux** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by vieux** [comment]
test failure unrelated

**Pull request merged**
