### PR TITLE
819 publish cherrypicks

### PR DESCRIPTION
**Pull request by moxiegirl**
cp PR #15671
cp PR #15690
cp PR #15482
cp PR #15677
cp PR #15676
cp PR #15672
cp Merge pull request #15510 from kblin/issue-14795
cp Merge pull request #15337 from phemmer/doc-builder-volume
cp Merge pull request #15605 from dharmit/15530-remove-the-terms-folder
cp Merge pull request #15613 from mgrauer/update_docs_installation_mac_docker_machine_name
cp Merge pull request #15430 from charleswhchan/patch-2
cp Merge pull request #15237 from charleswhchan/patch-3
cp Merge pull request #15428 from charleswhchan/patch-1
cp Merge pull request #15542 from MHBauer/rundoclink
cp Merge pull request #15574 from diogomonica/fixing-race-on-key-backup
cp Merge pull request #15560 from docker/patch-bad-formatting
cp Merge pull request #15451 from liubin/liubin/fix-broken-link
cp Merge pull request #15541 from thaJeztah/hashtag-space
cp Merge pull request #15450 from liubin/liubin/change-port-number-through-example

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
I'm on my phone now so "lgtm", but let me know if you want me to check if each one should be picked :smile:

**Comment by moxiegirl** [comment]
@thaJeztah I don't think it is necessary for you to check.  All I've done a check or two and a final just now.

**Comment by moxiegirl** [comment]
Author LGTM

**Pull request merged**
