### PR TITLE
[20.10 backport] vendor: docker/libnetwork b3507428be5b458cb0e2b4086b13531fb0706e46

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/moby/moby/pull/41908

also somewhat related to https://github.com/moby/moby/issues/28589, which discusses the "implicit" binding of IPv6

depends on:

- [x] https://github.com/moby/moby/pull/42021 Update rootlesskit to v0.13.1 to fix handling of IPv6 addresses
    - [x] https://github.com/rootless-containers/rootlesskit/pull/213 Refactor ParsePortSpec to handle IPv6 addresses, and improve validation
- [x] https://github.com/moby/moby/pull/42050 CI: update tests to be more resilient against CLI output format and for libnetwork changes
- [x] ~https://github.com/moby/moby/pull/42102~ https://github.com/moby/moby/pull/42179 update rootlesskit to v0.14.0
    - [x] https://github.com/rootless-containers/rootlesskit/pull/232 Port API: support specifying IP version explicitly ("tcp4", "tcp6")

full diff: https://github.com/docker/libnetwork/compare/fa125a3512ee0f6187721c88582bf8c4378bd4d7...b3507428be5b458cb0e2b4086b13531fb0706e46

- fixed IPv6 iptables rules for enabled firewalld (https://github.com/moby/libnetwork/pull/2609)
    - fixes https://github.com/moby/moby/issues/41861 "Docker uses 'iptables' instead of 'ip6tables' for IPv6 NAT rule, crashes" 
- Fix regression in https://github.com/moby/libnetwork/pull/2608
    - introduced in "Fix IPv6 Port Forwarding for the Bridge Driver" (https://github.com/moby/libnetwork/pull/2604)
    - fixes https://github.com/moby/libnetwork/issues/2607 "IPv4 and IPv6 addresses are not bound by default anymore"
    - fixes https://github.com/moby/moby/issues/41858 "IPv6 is no longer proxied by default anymore"
- Use hostIP to decide on Portmapper version (https://github.com/moby/libnetwork/pull/2616)
    - fixes docker-proxy not being stopped correctly

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]

**Comment by wget** [comment]
@thaJeztah Hello Sebastian! Could you properly tag the latest 20.10.6 release? https://github.com/moby/moby/releases
Because I was monitoring this page automatically and only realized the 20.10.6 was out. :)

**Comment by thaJeztah** [comment]
Looks like it's tagged; https://github.com/moby/moby/releases/tag/v20.10.6
But probably github releases not showing that as a release as it hides tags once a repository has done  "github release"

**Comment by thaJeztah** [comment]
ok; added a GitHub release https://github.com/moby/moby/releases/tag/v20.10.6

**Comment by alexandru-lazarev** [comment]
After update to 20.10.06 issue happened again on CentOS 7.9 with ipv6 disabled (I really do not need it) - any ideea how to fix it?

----
root@AlexL:~ # docker run -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:12.4
docker: Error response from daemon: driver failed programming external connectivity on endpoint sleepy_wilson (4c360a7cf5c62a8ee4199ebe623b20154e12a8b9902c796bf7009a3e742bb1ab): Error starting userland proxy: listen tcp6 [::]:5432: socket: address family not supported by protocol.
ERRO[0000] error waiting for container: context canceled 
----

**Pull request merged**
