### PR TITLE
change code to clarify logic

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by hqhq** [comment]
Seems not necessary if we have only one caller, I did the same thing in another PR:https://github.com/docker/docker/pull/11442 because we have two callers by then.

But +1 if this can be merged first.

**Comment by Mashimiao** [comment]
@hqhq  Ah... I did not know your PR has contained the similar changes.
That's so embarrassing.
Maybe this PR need to be revoked...

**Comment by crosbymichael** [comment]
LGTM

**Comment by Mashimiao** [comment]
ping @LK4D4 , @icecrime , @jfrazelle

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
