### PR TITLE
Replace NewTimer().C with After

### PR DESCRIPTION
**Pull request by LK4D4**
**- A picture of a cute animal (not mandatory but encouraged)**
cat

### CODE REVIEW

**Comment by thaJeztah** [comment]
SGTM

**Comment by vieux** [comment]
ping @tonistiigi

**Comment by tonistiigi** [comment]
If it was a public method I would not agree with this as it may swallow a context timeout from the caller, but as this is only a private request handler it is probably a bit more readable this way. LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by thaJeztah** [comment]
> If it was a public method I would not agree with this as it may swallow a context timeout from the caller, but as this is only a private request handler it is probably a bit more readable this way

@tonistiigi Would you prefer a GoDoc was added to `getEvents()` that mentions the timeout is overwritten (in case the function is ever exported by someone)?

**Comment by cpuguy83** [comment]
I'm not sure I follow why the parent context would be swallowed here.

**Comment by thaJeztah** [comment]
@cpuguy83 I think @tonistiigi means that if the original `ctx` had a timeout, that timeout is ignored and overwritten by;

```go
ctx, cancel = context.WithDeadline(ctx, until)
```

**Comment by cpuguy83** [comment]
It's not ignored in this case. The `ctx.Done()` channel is closed as soon as any parent context is cancled.

https://play.golang.org/p/kkzR-J5g7B

**Comment by tonistiigi** [comment]
@cpuguy83 What I meant was that it if the caller context timeouts one would expect this function to return with an error(or in this case with a debug log as this is the only way current function can distinguish between clean shutdown and cancellation) but with the update the caller timeout would finish cleanly, same way as if `until` value was reached.

**Comment by cpuguy83** [comment]
@tonistiigi In that case wouldn't it be up to the caller to handle logging?

**Comment by tonistiigi** [comment]
@cpuguy83 I'm not sure I understand. If caller cancels context with a timeout, https://github.com/moby/moby/pull/35064/files#diff-52cc21ba409894d9cd1951947d573edeR165 would skip the log because the generated error is not `context.Canceled` and client has no way to control that.

**Comment by cpuguy83** [comment]
If the caller sends a context with a timeout they should check `ctx.Err()`, no?

**Comment by tonistiigi** [comment]
@cpuguy83 No, only a function itself can determine how(if) it handles the context cancellation and return an error(this case a log) depending if it was canceled or not. Caller detecting it after function has returned does not give correct results as context could have timed out after the function returned.

**Comment by cpuguy83** [comment]
Ok, I agree.
Maybe we should just split this into two.

**Comment by LK4D4** [comment]
@cpuguy83 what is "two" in this context? :)
I agree that @tonistiigi concern is valid here, but handlers can never have timed out context. Also, I don't think that `Debug` log is so important.
Let me know if you think it's better just replace it with time.After.

**Comment by cpuguy83** [comment]
> what is "two" in this context?

@LK4D4 Create a new context without inheritance is what I meant. But a `time.After` would also work here. Originally I was thinking we were passing down this context in the lower level but realized we aren't.

**Comment by LK4D4** [comment]
@cpuguy83 @tonistiigi I just replaced `NewTimer().C` with `After()` to avoid controversy.

**Review by boaz0 — APPROVED** [review]
LGTM 👍

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
Thanks @LK4D4 🤗 LGTM

**Pull request merged**
