### PR TITLE
Vendor engine-api to 70d266e96080e3c3d63c55a4d8659e00ac1f7e6c

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like this depends on the changes in https://github.com/docker/docker/pull/20565

**Comment by hqhq** [comment]
@thaJeztah Thanks for the link, #20565 includes this PR, if it's merged, this PR will not be needed, if #20565 will be merged soon, this PR can be closed now. Or maybe we can merge engine-api part in this PR, then #20565 can be rebased and reviewed easier. Your call :)

**Comment by thaJeztah** [comment]
@hqhq I suggested to split that PR, because it's now doing multiple things. Not sure we'd be able to merge this PR without the related changes for the string stuff

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM if windows is green :+1:

**Comment by calavera** [comment]
:tada: :confetti_ball:

**Pull request merged**
