### PR TITLE
The comment for build in exec had a typo

### PR DESCRIPTION
**Pull request by jessfraz**
Pretty sure this needed `+build`

### CODE REVIEW

**Comment by tianon** [comment]
hah LGTM

**Comment by tianon** [comment]
Although, if we haven't noticed a problem with it yet, do we really need this at all? :wink:

(ie, maybe `+build daemon` would be more appropriate, or no build tag at all?)

**Comment by jfrazelle** [comment]
ok changed to daemon

**Comment by tianon** [comment]
LGTM FWIW

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
