### PR TITLE
progress: Rate limit progress bar output

### LINKED ISSUE #11971: docker push/pull output is really expensive over the wire
I was running `nethogs` while running `git pull` on a remote machine. It is eating up nearly 50K/s just to update the progress bar! That's pretty crazy. Can we please have the ability to specify a much lower refresh rate?

### PR DESCRIPTION
**Pull request by aaronlehmann**
ProgressReader outputs progress information every 500 KB. This could be
excessive if something is being transfered at a fast rate. Rate-limit
progress output to 10 per second.

Fixes #11971

### CODE REVIEW

**Review by LK4D4 — APPROVED** [review]

**Comment by tonistiigi** [comment]
@aaronlehmann unit-test failure in ci

**Comment by aaronlehmann** [comment]
Fixed

**Review by tonistiigi — APPROVED** [review]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by LK4D4** [comment]
experimental failure is unrelated

**Pull request merged**
