### PR TITLE
Fix issue of incorrect qgroup detection in #29835

### PR DESCRIPTION
**Pull request by yongtang**
In #29835 `BTRFS_IOC_INO_LOOKUP` was used for qgroup detection.
However, this is not necessarily true because it only indicates the existance of tree id in btrfs.

Overall, the way to test the qgroup is to use `btrfs qgroup show <path>` and see if it returns something. The following code offers insight in checking qgroup:

https://github.com/kdave/btrfs-progs/blob/v4.9/qgroup.c#L1035

This fix tries to fix the issue by using `BTRFS_IOC_TREE_SEARCH` with `BTRFS_QGROUP_STATUS_KEY` instead.

In case qgroup is enabled, the search for `BTRFS_QGROUP_STATUS_KEY` should be valid.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

/cc @cpuguy83 @tonistiigi @zhuguihua
Please take a look and sorry for the trouble and inconvenience the #29835  caused.

### CODE REVIEW

**Comment by yongtang** [comment]
Also, I am not familiar with Jenkins test setup for docker but it might make sense to add integration tests for storage drivers like btrfs. Not sure if it is possible though.

**Comment by yongtang** [comment]
This PR could be superseded by #29427.

**Comment by vdemeester** [comment]
@yongtang should we close this one ? 👼

**Comment by yongtang** [comment]
Thanks @vdemeester. I will close this PR for now. Ideally we want to make sure #29427 is merged before the release of `1.14.0`, so that the issue could be addressed.

**Pull request closed without merging**
