### PR TITLE
[WIP] Remove TestAPISwarmLeaderElection flaky test

### PR DESCRIPTION
**Pull request by crosbymichael**
Ref: #32673

This is a known flaky test that does not even run on ibm systems because
it is very sensitive to latency.  It was been flaky from april 2017,
it's time to remove this and re-add it later when time can be taken to
improve the test so that it is robust and can be trusted.

I've seen recent and open PRs with this thing failing.  

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
I recently noticed that all swarm failures show the same error (not just this one);

```
Err: listen tcp 0.0.0.0:7946: bind: address already in use
```

So I wonder if we should look at that issue instead

**Comment by thaJeztah** [comment]
for reference; https://github.com/moby/moby/issues/34051#issuecomment-511073471

**Comment by tonistiigi** [comment]
This test checks a very basic functionality of swarm. I haven't seen any analysis about what makes this test bad. It does not make sense to me to hide this error, if we do that, the likelihood of someone taking the time to figure out the issue becomes way lower. If we can't remove the functionality we can't remove the test as well.

**Comment by crosbymichael** [comment]
Lets hold off on merging this until Friday if we cannot find a fix

**Comment by andrewhsu** [comment]
@ddebroy is this a flaky test or a legit [error](https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/25893/console) for the windowsRS1 PR check?
```
--- FAIL: TestFrequency (0.53s)
    splunk_test.go:929: Unexpected number of requests 8
time="2019-07-15T18:54:46Z" level=warning msg="Error while sending logs" error="splunk: failed to send event - 500 Internal Server Error - " module=logger/splunk
```

**Comment by ddebroy** [comment]
@andrewhsu seems like a flaky test and not related to the changes in the PR. This test is sensitive to load on a machine at a given point and there is no guarantee that this would pass in either Linux or Windows. 

```
        // 1 to verify connection and 10 to verify that we have sent messages with required frequency,
	// but because frequency is too small (to keep test quick), instead of 11, use 9 if context switches will be slow
	if hec.numOfRequests < 9 {
		t.Fatalf("Unexpected number of requests %d", hec.numOfRequests)
	}
```

**Pull request closed without merging**
