### PR TITLE
Docs cherry picks 1.12.2

### PR DESCRIPTION
**Pull request by thaJeztah**
Cherry pick of the following PR's

https://github.com/docker/docker/pull/26360 (https://github.com/docker/docker/pull/26360/commits/2d1d4684f0fc752aae7e41af03a0f1589f11ee00)
https://github.com/docker/docker/pull/26216 (https://github.com/docker/docker/pull/26216/commits/44a16acff15b5da3103fd002ad5064cb7b375106)
https://github.com/docker/docker/pull/26570 (https://github.com/docker/docker/pull/26570/commits/9b8b6aa224d0e88bdd27e322ae1c922e3dfcbe12)
https://github.com/docker/docker/pull/26582 (https://github.com/docker/docker/pull/26582/commits/86de72fef244b3fe209e5793deb40fb26f5b318e)
https://github.com/docker/docker/pull/26581 (https://github.com/docker/docker/pull/26581/commits/1cd06fdd1ac5ce1f91291330d9f89679468ce393)
https://github.com/docker/docker/pull/26599 (https://github.com/docker/docker/pull/26599/commits/edbb8fb86d7d0b715adc15415f0cb187433092a5)
https://github.com/docker/docker/pull/26605 (https://github.com/docker/docker/pull/26605/commits/dddea689ab45ce146e6ac3a1199235e1f36ffe29)
https://github.com/docker/docker/pull/26620 (https://github.com/docker/docker/pull/26620/commits/03a8b6798d030a952e85f15208aeea1215e3f801)
https://github.com/docker/docker/pull/26629 (https://github.com/docker/docker/pull/26629/commits/7ca02f86de2ceef980cad98faefc15cbc628c91a)
https://github.com/docker/docker/pull/26637 (https://github.com/docker/docker/pull/26637/commits/87b174080bd8b1b9ea2bbfad8ef35a4c0dfe8ad4)
https://github.com/docker/docker/pull/26647 (https://github.com/docker/docker/pull/26647/commits/484fbe236dcab9fb5b8d48844a8cdc9d614e32e9)
https://github.com/docker/docker/pull/26266 (https://github.com/docker/docker/pull/26266/commits/bd914ff5a31b1b39bdd9c0fbacf76c65c2b1e842)
https://github.com/docker/docker/pull/26289 (https://github.com/docker/docker/pull/26289/commits/e74a937b00af567b655c93224cc6a514f54e2b38)
https://github.com/docker/docker/pull/26558 (https://github.com/docker/docker/pull/26558/commits/7c3a26db166bf4d618ae414470f6bed7160f1371)
https://github.com/docker/docker/pull/26634 (https://github.com/docker/docker/pull/26634/commits/d69409fd43e73829209315de79abf79000c4c720)
https://github.com/docker/docker/pull/26654 (https://github.com/docker/docker/pull/26654/commits/53b1dcb25ca937c61bd47a29ba7be6e68abc25a5)
https://github.com/docker/docker/pull/26675 (https://github.com/docker/docker/pull/26675/commits/191adcfb637ea1b52d2da9a75e4e1e4938d9550c)
https://github.com/docker/docker/pull/26678 (https://github.com/docker/docker/pull/26678/commits/ced272984157e277523a942505435aa392913ac4)
https://github.com/docker/docker/pull/25776 (https://github.com/docker/docker/pull/25776/commits/eb3a01eb432473beae968a0c9f3817af8b7a7d53, https://github.com/docker/docker/pull/25776/commits/5880d629533d9b8ad9889500fe841cb2e31a71c8) 
https://github.com/docker/docker/pull/26682 (https://github.com/docker/docker/pull/26682/commits/0f0b0db842e53c81191385395d6d040574eeb0d9)
https://github.com/docker/docker/pull/26699 (https://github.com/docker/docker/pull/26699/commits/b81d12e7a10abfb55f164105365ff175a95ae9e9)
https://github.com/docker/docker/pull/26701 (https://github.com/docker/docker/pull/26701/commits/533b00da8bed8336debf99a03f2fd2a0692fac6e)
https://github.com/docker/docker/pull/26704 (https://github.com/docker/docker/pull/26704/commits/f7af5cc780cb49b6115c726687dec5ef361ca5fb)
https://github.com/docker/docker/pull/26706 (https://github.com/docker/docker/pull/26706/commits/b2bb4e11aa656947e45b752aa4f5d5b5cdc693cd)
https://github.com/docker/docker/pull/26712 (https://github.com/docker/docker/pull/26712/commits/e9a9015e38fc0996a3dae61393885414b092103f)
https://github.com/docker/docker/pull/26598 (https://github.com/docker/docker/pull/26598/commits/708892c4037e9eef6f6c25b5a3551f7779fb8868)
https://github.com/docker/docker/pull/26732 (https://github.com/docker/docker/pull/26732/commits/0483d776130aa6b7add845bdab3d1d8ee67f7480)
https://github.com/docker/docker/pull/26741 (https://github.com/docker/docker/pull/26741/commits/36a25bdbe4d973aef308fa11b450264dae1bc0b4)
https://github.com/docker/docker/pull/26615 (https://github.com/docker/docker/pull/26615/commits/5c4c062ffcdb8d7b8c104fd667571279c51d2ffd)
https://github.com/docker/docker/pull/26769 (https://github.com/docker/docker/pull/26769/commits/da2159ea1c366ac64b0f498a8aca0ee595dae558)
https://github.com/docker/docker/pull/26813 (https://github.com/docker/docker/pull/26813/commits/838fe65e5332dd79f5cf8551d70906d9801f79fb)
https://github.com/docker/docker/pull/26836 (https://github.com/docker/docker/pull/26836/commits/c53efdf4c1f0b2e7f1fe04294d9d64401b8b09b8)
https://github.com/docker/docker/pull/26854 (https://github.com/docker/docker/pull/26854/commits/392aae44fd8ea5755305104e1c2a1c85f39d4a07)
https://github.com/docker/docker/pull/26907 (https://github.com/docker/docker/pull/26907/commits/bf9c6d3115dd388cf379ec1a80d29104521a7b42)
https://github.com/docker/docker/pull/26908 (https://github.com/docker/docker/pull/26908/commits/cfb07e642d23622412c5455ca70c42140268f9fe)
https://github.com/docker/docker/pull/26047 (https://github.com/docker/docker/pull/26047/commits/6e4ec046f4a267083b1bd07028d1b68eb248a950)
https://github.com/docker/docker/pull/26931 (https://github.com/docker/docker/pull/26931/commits/fd7161bb3061e2e2f56faed1a4ba1f7a887627bf)
https://github.com/docker/docker/pull/26963 (https://github.com/docker/docker/pull/26963/commits/0a76a4cb5bdb83c1c62832d084ae47a0c50646bc)
https://github.com/docker/docker/pull/27001 (https://github.com/docker/docker/pull/27001/commits/ca04f02d7655e7306c7c0cde6fa1895a14f0a673)

Two minor issues while cherry picking https://github.com/docker/docker/commit/c84d8b836010626ab8001fcc04b50cd1c8dee897, and https://github.com/docker/docker/pull/25776/commits/5880d629533d9b8ad9889500fe841cb2e31a71c8, due to those touching docs for 1.13

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @vdemeester @mstanleyjones @londoncalling PTAL; looks like we were behind with cherry picking into the 1.12.x branch, so you probably want this (at least the last commit)

**Comment by thaJeztah** [comment]
@vdemeester @vieux this contains one tiny code change in an integration test; I decided to keep that in (https://github.com/docker/docker/pull/27022/files#diff-401699de8561309143baebae1c3696e3R589)

**Review by mdlinville — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
author LGTM

ping @vieux is this ok to merge?

**Comment by thaJeztah** [comment]
@icecrime gave a "go ahead", and failing tests are known to be flaky (and unrelated), so I'll merge

**Pull request merged**
