### PR TITLE
Docs debian 8 installation

### PR DESCRIPTION
**Pull request by daithi-coombes**
This `PR` is to update the documentation for the installation of `docker` in `debian`

### CODE REVIEW

**Comment by daithi-coombes** [comment]
@GordonTheTurtle sorry, that `PR` isn't complete. I was trying to create a `pr` on my fork - sorry half asleep doing this.

I've heard wind that the `https://get.docker.com` bash installer might work for all debian releases - want to test this before submitting a final merge request. (https://github.com/docker/docker/issues/13029#issuecomment-100312281)

Also this commit doesn't include testing the `uninstallation` of docker in `debian 8` after installing using the bash installer.

**Comment by thaJeztah** [comment]
@daithi-coombes you're planning on updating this PR? If you do, perhaps you can change the title and add a `[WIP] ` prefix. Until it's ready for review

**Comment by daithi-coombes** [comment]
also confirming that `debian wheezy 7.0.0` also worsk using the `get.docker.com` installer.

From a fresh download of `wheezy 7.0.0` from debian's previous versions, I ran in a vbox vm:
```
# apt-get update
# apt-get upgrade
# apt-get install curl
# curl -sSL https://get.docker.com | sh
# usermod -aG docker $user
# reboot
$ docker run --rm hello-world
```
and it worked. So I'm presuming that the current mention of `Docker requires Kernel 3.8+` is no longer true?
```
$ uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux
```

**Comment by daithi-coombes** [comment]
think this is ready for review

**Comment by jfrazelle** [comment]
can you squash this into one commit

**Comment by daithi-coombes** [comment]
Not sure if I've `squashed` the previous commits properly... because now I can't sign my last merge with master. This is my 3rd attempt but lost as to why its not happening... tried just signing my last commit with `HEAD~1` but that didn't work either.

```
daithi@debian:/opt/foo/somewhere$ git rebase -i HEAD~6                                                                        [124/696]
Stopped at 80d73c838a279a3354713b56687e0c3f90c1efff... Test Cases for API - Container create with Hostname, DomainName and NetworkMode
You can amend the commit now, with

        git commit --amend 

Once you are satisfied with your changes, run

        git rebase --continue

daithi@debian:/opt/foo/somewhere$ git commit --amend -s --no-edit
[detached HEAD 766b1a7] Test Cases for API - Container create with Hostname, DomainName and NetworkMode
 Author: Rajdeep Dua <dua_rajdeep@yahoo.com>
 Date: Sat Apr 25 01:53:38 2015 -0700
 1 file changed, 74 insertions(+), 19 deletions(-)
daithi@debian:/opt/foo/somewhere$ git rebase --continue
Stopped at b919dee8347a47763d576136254bcbc922ef4c57... Update "hack/vendor.sh" to be more explicit
You can amend the commit now, with

        git commit --amend 

Once you are satisfied with your changes, run

        git rebase --continue

daithi@debian:/opt/foo/somewhere$ git commit --amend -s --no-edit
[detached HEAD 83ed9a8] Update "hack/vendor.sh" to be more explicit
 Author: Tianon Gravi <admwiggin@gmail.com>
 Date: Thu May 7 15:18:22 2015 -0600
 14 files changed, 105 insertions(+), 109 deletions(-)
daithi@debian:/opt/foo/somewhere$ git rebase --continue                                                                                
Stopped at e35b025aa61e7d8db04a9973967b7109f742593a... Windows: Split ContainerExecCreate
You can amend the commit now, with

                                                                                                                               [91/696]
        git commit --amend 

Once you are satisfied with your changes, run

        git rebase --continue

daithi@debian:/opt/foo/somewhere$ git commit --amend -s --no-edit
[detached HEAD 7c2d7aa] Windows: Split ContainerExecCreate
 Author: jhowardmsft <jhoward@microsoft.com>
 Date: Fri Apr 24 11:12:56 2015 -0700
 3 files changed, 30 insertions(+), 3 deletions(-)
 create mode 100644 daemon/exec_linux.go
 create mode 100644 daemon/exec_windows.go
daithi@debian:/opt/foo/somewhere$ git rebase --continue                                                                                
Stopped at dc1d7004e1b374bbf59c76f090f0948d465d78d7... debian 8 installation instructions using get.docker.com bash installer
You can amend the commit now, with

        git commit --amend 

Once you are satisfied with your changes, run

        git rebase --continue

daithi@debian:/opt/foo/somewhere$ git commit --amend -s --no-edit
[detached HEAD 0864ba4] debian 8 installation instructions using get.docker.com bash installer
 Author: Dáithí Coombes <webeire@gmail.com>
 Date: Fri May 8 23:11:27 2015 +0100
 1 file changed, 8 insertions(+), 6 deletions(-)
daithi@debian:/opt/foo/somewhere$ git rebase --continue                                                                                
Stopped at a3c7ac969a5ad62337e701f0f7f826cd715d53af... debian 8 installation instructions using get.docker.com bash installer
You can amend the commit now, with

                                                                                                                               [59/696]
        git commit --amend 

Once you are satisfied with your changes, run

        git rebase --continue

daithi@debian:/opt/foo/somewhere$ git commit --amend -s --no-edit
[detached HEAD a5eade5] debian 8 installation instructions using get.docker.com bash installer
 Author: Dáithí Coombes <webeire@gmail.com>
 Date: Fri May 8 23:14:30 2015 +0100
 1 file changed, 22 insertions(+), 65 deletions(-)
daithi@debian:/opt/foo/somewhere$ git rebase --continue                                                                                
error: could not apply 467b7b4... debian 8 installation instructions using get.docker.com bash installer

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply 467b7b48e62e7d32a396026e02eb3edd265e87a9... debian 8 installation instructions using get.docker.com bash installer
daithi@debian:/opt/foo/somewhere$ git commit --amend -s --no-edit
U       docs/sources/installation/debian.md
error: commit is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit, or use
hint: 'git commit -a'.
fatal: Exiting because of an unresolved conflict.
daithi@debian:/opt/foo/somewhere$ git rebase --continue                                                                                
docs/sources/installation/debian.md: needs merge
You must edit all merge conflicts and then
mark them as resolved using git add
daithi@debian:/opt/foo/somewhere$ git push -f
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message

and maintain the traditional behavior, use:                                                                                    [26/696]

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

daithi@debian:/opt/foo/somewhere$ git push -f
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

daithi@debian:/opt/foo/somewhere$ git push origin 
Display all 104 possibilities? (y or n)
daithi@debian:/opt/foo/somewhere$ git push origin master
error: src refspec master does not match any.
error: failed to push some refs to 'git@github.com:daithi-coombes/docker.git'
daithi@debian:/opt/foo/somewhere$
```

**Comment by thaJeztah** [comment]
@daithi-coombes I see your previous comment on the trouble you had doing the squash. Perhaps it's easier to ask for help in the #docker-dev IRC channel. I'm no git "master" myself, but there should be some people there that are able to talk you through.

**Comment by daithi-coombes** [comment]
cheers @thaJeztah for the advice. I will rebase this `pr` with master when I get home then try the `irc` channel for more help

**Comment by moxiegirl** [comment]
@daithi-coombes I'm happy to carry this for you if the rebase becomes too much.

**Comment by icecrime** [comment]
@daithi-coombes We don't think this PR is relevant anymore (@jfrazelle: "docker.io is in jessie backports now"). Thanks for the contribution, but we're closing this!

**Pull request closed without merging**
