### PR TITLE
add dynbinary in Makefile

### PR DESCRIPTION
**Pull request by hqhq**
We need dynbinary more offen because of issue:
https://github.com/docker/docker/issues/4036

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by estesp** [comment]
Seems reasonable to have this target floated up to the Makefile; @tianon any concerns?

**Comment by icecrime** [comment]
LGTM, but waiting for @tianon to approve.

**Comment by tianon** [comment]
Just that the resulting binary is very unlikely to work on your host unless
your host is Ubuntu Trusty, so I'm -1.

**Comment by jfrazelle** [comment]
-1 as well, I think maybe we could do something like this after tianons patch for ditro-specific builds is done but it would need to know the distro etc

**Comment by crosbymichael** [comment]
@hqhq what kernel are you running?  I would recommend overlayfs if you all are able to upgrade. The performance and stability are pretty awesome.

**Comment by hqhq** [comment]
@crosbymichael We are using devicemapper for some reasons:
1. We are using Docker on several Distro, Ubuntu 14.04, RHEL 7 etc, it's better to use the same graph driver, and the same graph driver between them is only devicemapper;
2. We need disk limit, seems only devicemapper can do this for now, other solutions like user quota is not suit for us, and btrfs is not stable enough for product, also has kernel version limit;

Is there any plan when we implement disk quota for all storage backends? Like https://github.com/docker/docker/issues/3804 discussed?

**Comment by hqhq** [comment]
@tianon @jfrazelle Actually I tried and the binary can work well on both Ubuntu 14.04 and RHEL 7, and I think it's easy to figure out why the binary can't work if someone mistakenly run it on some other distros.

Anyway I agree it's a little risky and I'll be glad to wait for tianon's patch, so feel free to close it or leave it waiting.

**Comment by jfrazelle** [comment]
Ok I think we should close in favor of per distro dynbinary, sorry

**Pull request closed without merging**
