### PR TITLE
Make sure the input reader is closed after loading an image from file.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
test failures :(

**Comment by vdemeester** [comment]
@runcom compilation problem you mean :stuck_out_tongue_closed_eyes:. Although it's not pretty, the `return` part probably should not be changed :wink:

**Comment by runcom** [comment]
yeah I meant compilation, sorry

**Comment by calavera** [comment]
I'm going to close this because it's going to conflict with #18472 and I don't think it's worth the rebase for now. I can reopen it if that PR doesn't ship.

**Pull request closed without merging**
