### PR TITLE
 Skip some tests requires root uid when run as user…

### PR DESCRIPTION
**Pull request by vdemeester**
… and fix a typo in idtools tests

:lion:

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM!

**Comment by thaJeztah** [comment]
Janky is failing on https://jenkins.dockerproject.org/job/Docker-PRs/49090/console (tracked through https://github.com/moby/moby/issues/30427 / https://github.com/moby/moby/issues/36501)


```
15:06:31 ----------------------------------------------------------------------
15:06:31 FAIL: docker_api_swarm_service_test.go:33: DockerSwarmSuite.TestAPIServiceUpdatePort
15:06:31 
15:06:31 [d0acdc02b8af0] waiting for daemon to start
15:06:31 [d0acdc02b8af0] daemon started
15:06:31 
15:06:31 docker_api_swarm_service_test.go:39:
15:06:31     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
15:06:31 docker_utils_test.go:435:
15:06:31     c.Assert(v, checker, args...)
15:06:31 ... obtained int = 0
15:06:31 ... expected int = 1
15:06:31 
15:06:31 [d0acdc02b8af0] exiting daemon
15:06:43 

15:31:31 FAIL: docker_cli_swarm_test.go:1605: DockerSwarmSuite.TestSwarmPublishDuplicatePorts
15:31:31 
15:31:31 [d78d8e5da9d38] waiting for daemon to start
15:31:31 [d78d8e5da9d38] daemon started
15:31:31 
15:31:31 docker_cli_swarm_test.go:1613:
15:31:31     // make sure task has been deployed.
15:31:31     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
15:31:31 docker_utils_test.go:435:
15:31:31     c.Assert(v, checker, args...)
15:31:31 ... obtained int = 0
15:31:31 ... expected int = 1
15:31:31 
15:31:31 [d78d8e5da9d38] exiting daemon
15:31:33 
```

**Comment by yongtang** [comment]
All tests finally passed 🎉

**Pull request merged**
