### PR TITLE
Add default PATH to 'scratch' images

### LINKED ISSUE #19012: PATH not set for images built from scratch
If you build an image from scratch, and don't use the ENV command in the Dockerfile, Env will be null for this image as shown in `docker inspect`.

If you then build another image that inherits from the first one, Env will contain `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

This is unintuitive and I didn't find any documentation about it. It makes it impossible to manipulate PATH in a Dockerfile that starts from scratch.

### PR DESCRIPTION
**Pull request by duglin**
Closes #19012

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
ping @tianon

**Comment by tianon** [comment]
Nice, thanks!  LGTM :+1:

**Comment by calavera** [comment]
LGTM. It needs to be rebased though.

**Comment by duglin** [comment]
rebased

**Comment by calavera** [comment]
NOOOOOOOOO!!!!!!!!!! :cry: :sob: :sob:

**Comment by duglin** [comment]
rebased - one more try...  :-)

**Comment by calavera** [comment]
Looks good, merging!! :tada: :space_invader:

**Pull request merged**
