### PR TITLE
added indian and bangladeshi scientists Jagdish Bose, Subrahmanyan Ch…

### PR DESCRIPTION
**Pull request by claymodel**
…andrasekhar Names

**- What I did**
Added names of famous Indian and Bangladeshi scientist
```
Subrahmanyan Chandrasekhar (Indian: 19 October 1910 – 21 August 1995) Astrophysicist won the Nobel Prize in 1983 for his research on the evolutionary stages of massive stars. https://en.wikipedia.org/wiki/Subrahmanyan_Chandrasekhar
		"chandrasekhar",

Jagadish Chandra Bose (Bangladeshi: 30 November 1858 – 23 November 1937) Physicist, biologist and archaeologist who pioneered the investigation of radio and microwave optics. https://en.wikipedia.org/wiki/Jagadish_Chandra_Bose
		"jagdishbose",
```

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by claymodel** [comment]
Corrected for alphabetization and already existing names.

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
Derek add label: rebuild/experimental

**Comment by tiborvass** [comment]
@claymodel thank you but please keep the gender balance by adding as many male scientists as female scientists.

**Comment by cpuguy83** [comment]
This has been sitting around for some time without updating, so I'm going to go ahead and close.
If someone wants to get this in, we just need to keep the gender balance in this list of names (same number of males as females).

Thanks!

**Pull request closed without merging**
