### PR TITLE
Adding biologist Christiane Nüsslein Volhard and AI pioneer Marvin Mi…

### PR DESCRIPTION
**Pull request by anujbahuguna**
…nsky
Signed-off-by: Anuj Bahuguna anujbahuguna.dev@gmail.com

### CODE REVIEW

**Comment by MHBauer** [comment]
Man, Minsky still makes me sad. Sign off on the commit and you'll be good to go.

**Comment by thaJeztah** [comment]
@anujbahuguna also commented on your old PR, but I think the sign-off is not recognized because it's missing `<` and `>` around your e-mail address.

**Comment by anujbahuguna** [comment]
@thaJeztah thanks for the help. (had moved to different development machine where config user.name and user.email was not setup up). Fixed it now

**Comment by thaJeztah** [comment]
Thanks @anujbahuguna!

LGTM

**Comment by vdemeester** [comment]
LGTM 🐼

**Comment by thaJeztah** [comment]
Janky's are having issues after the GitHub outage, so moved to "merge"

**Comment by calavera** [comment]
Works on my machine™.

**Pull request merged**
