### PR TITLE
Move graphdriver quota

### PR DESCRIPTION
**Pull request by dnephin**
Fixes https://github.com/docker/docker/pull/24771#issuecomment-254371766

rename was to make golint happy about the struct name

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM if green :smile:

**Comment by amir73il** [comment]
Nice :) Thanks for fixing

**Comment by thaJeztah** [comment]
ping @crosbymichael PTAL

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
/cc @crosbymichael @mlaventure

**Comment by mlaventure** [comment]
LGTM!

**Pull request merged**
