### PR TITLE
[WIP] Fix docs in 1.13.x branch

### PR DESCRIPTION
**Pull request by tiborvass**
Backporting docs fixes to 1.13.x branch, because it was missing too much important content.

Cherry-picks:
- #31242 (opened against 17.03)
- #31474 (opened against 17.03)
- #31767 (opened against master)
- #30514 (opened against master)

cc @thaJeztah @mstanleyjones

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM (at a glance)

**Comment by vieux** [comment]
@tiborvass looks like some of them should be against 17.03.x no ?

**Comment by tiborvass** [comment]
@vieux only https://github.com/docker/docker/pull/30514 should be cherrypicked against 17.03 the rest should already be there. But yes we should double check.

**Review by mdlinville — APPROVED** [review]
LGTM :bowing_woman:

**Comment by tiborvass** [comment]
Added WIP so we don't merge just yet, I need confirmation by having  https://github.com/docker/docker.github.io/pull/2360 tested

**Comment by thaJeztah** [comment]
@mstanleyjones @tiborvass what's the status on this one?

**Comment by tiborvass** [comment]
Closing for now, will get back to it later.

**Pull request closed without merging**
