### PR TITLE
Update logic of history

### PR DESCRIPTION
**Pull request by HuKeping**
After talking with @duglin and @thaJeztah , it's better to change the logic of history like this.

Signed-off-by: Hu Keping hukeping@huawei.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! LGTM :smile:

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
ping @runcom @vdemeester

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
