### PR TITLE
bug fix: wrong prompt when pull non-existent repo

### PR DESCRIPTION
**Pull request by WeiZhang555**
when we try to pull a non-existent repo, docker client will show us wrong format error prompt like this:
wrong1
and docker daemon will show log like this:
wrong2
1. The reason why docker client show wrong format error message is that docker daemon doesn't reply with correct json format error message; 
2. the reason why docker daemon print `http: Multiply response.WriteHeader calls` is that when daemon use out.Write() function to reply a message to client, it will call WriteHeader() to write a default status code of 200, then after error happens, it will call httpError() which tries to call WriteHeader() again to write a error StatusCode.

My patch is written based on those two reasons above. 
After fixing this bug, docker client will show errors like this:
correct1
and daemon show errors like:
correct2

Hope you will be satisfied with its final look. :)

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by WeiZhang555** [comment]
@jlhawn I just read your code in PR #12649, it seems I miss the scenario of `import`. But after this, problem `multiple response.WriteHeader calls` still exists because the httpError logic.
Though this is not a critical bug and seems won't cause serious problem, it seems go language is telling us we are using this in a wrong way.
Is this what you want and are you fine with this? 
@jfrazelle @jlhawn

**Comment by jfrazelle** [comment]
we need an integration test like the ones i wrote for the other PR

**Comment by jlhawn** [comment]
@WeiZhang555 @jfrazelle The `multiple response.WriteHeader` calls is probably not an issue that can be fixed because of the way we stream responses (many docker API endpoints behave this way). As you described above, we start writing the response before we know whether or not the operation failed and simply writing a response uses a default header/status of `200 OK`.

**Comment by jlhawn** [comment]
@WeiZhang555 @jfrazelle it looks like we meant to close this issue/PR with https://github.com/docker/docker/pull/12649#issuecomment-95321034 what do you think?

**Pull request closed without merging**
