### PR TITLE
add entries to lsb_dist from Amazon Linux

### PR DESCRIPTION
**Pull request by ismaelfernandezscmspain**
**- What I did**
I wanted install docker with hack/install.sh on Amazon Linux
**- How I did it**
I have modified the hack/install.sh
**- How to verify it**
I have installed on instance doing the changes in the script

**- Description for the changelog**

I have added a control sentences and case for lsb_dist == amazonlinux

```
if [ -z "$lsb_dist" ] && [-r /etc/system-release ];then
                       lsb_dist="$( cat /etc/system-release|cut -d " " -f1,2|tr -d " ")"

fi

...

               amazonlinux)
                       $sh_c 'sleep 3; yum -y -q install docker'
                       exit 0
                       ;;
```

alt tag

### CODE REVIEW

**Review by stealthizer — APPROVED** [review]
Thanks!

**Review by vdemeester — COMMENTED** [review]
/cc @thaJeztah @tianon

**Comment by thaJeztah** [comment]
ping @friism @andrewhsu

**Comment by friism** [comment]
On the one hand, there's no official release of Docker for Amazon Linux, so it's a little odd for the `install.sh` script to include it.

On the other hand, the install-script already handles other non-Docker-inc releases, so it seems unreasonable to not merge for that reason.

I'm not a maintainer, but from the standpoint of the Docker project I think merging this makes sense...

**Comment by cpuguy83** [comment]
Fairly 👎 
Everything we add we have to support forever.

**Comment by ismaelfernandezscmspain** [comment]
@cpuguy83 I need to deploy in amzn linux dst, what can I do if you don't merge it?

**Comment by friism** [comment]
@ismaelfernandezscmspain this PR is only concerned with adding Amazon Linux to the `install.sh` helper script. You can install with `sudo yum install -y docker` irrespective of this PR.

**Comment by thaJeztah** [comment]
ah, yes, this is adding just the install line, but not trying to install packages we ship.

I have to agree with @cpuguy83 there; adding this to the install script gives the impression that the packages are stalled from the official repositories, which they're not, and we cannot provide support or fix issues with packages that we don't ship. For the same reason, we removed other distros from this script; https://github.com/docker/docker/pull/23480

I'll go ahead and close this PR, but thanks for contributing 👍

**Pull request closed without merging**
