### PR TITLE
Rename integration/util to integration/internal

### PR DESCRIPTION
**Pull request by vdemeester**
Both names have no real sense, but one allows to make sure these packages
aren't used outside of `integration`.

😝 🌵 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
@vdemeester There seems to be one conflict:
```
22:05:17 integration/container/inspect_test.go:12:2:warning: could not import github.com/docker/docker/integration/util/request (cannot find package "github.com/docker/docker/integration/util/request" in any of: (gosimple)
22:05:17 Build step 'Execute shell' marked build as failure
```
Can you take a look?

**Review by thaJeztah — APPROVED** [review]
LGTM (if CI is fixed)

**Comment by vdemeester** [comment]
rebased 😉

**Pull request merged**
