### PR TITLE
Vendor updated distribution

### LINKED ISSUE #19476: [1.10]: Invalid auth for pull no longer sends meaningful error message
If I send that wrong credentials for a pull I now get ``Error response from daemon: Get https://registry-1.docker.io/v2/tianon/true/manifests/latest: <nil>`.  Obviously that error is not very helpful.  Previously the error message would say `Authentication is required`.

### PR DESCRIPTION
**Pull request by aaronlehmann**
The only changes are https://github.com/docker/distribution/pull/1379
and https://github.com/docker/distribution/pull/1380.

Fixes #19476

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by calavera** [comment]
I confirm that output matches with 1.9.1 after this change:

```
calavera@d ~ $ docker pull busybox
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password
calavera@d ~ $ ./docker-1.10.0-dev pull busybox
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password
calavera@d ~ $ docker -v
Docker version 1.9.1, build a34a1d5
calavera@d ~ $ ./docker-1.10.0-dev -v
Docker version 1.10.0-dev, build a160dd4
```

LGTM

**Comment by calavera** [comment]
This is the damon log in 1.9.1:

```
INFO[0018] POST /v1.21/images/create?fromImage=busybox%3Alatest
DEBU[0018] Trying to pull busybox from https://registry-1.docker.io v2
DEBU[0019] Pulling tag from V2 registry: "latest"
DEBU[0019] Error trying v2 registry: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: token auth attempt for registry: https://auth.docker.io/token?account=%EF%BF%BDg%EF%BF%BDavera&scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io request failed with status: 401 Unauthorized
DEBU[0019] Trying to pull busybox from https://index.docker.io v1
DEBU[0019] hostDir: /etc/docker/certs.d/docker.io
DEBU[0019] [registry] Calling GET https://index.docker.io/v1/repositories/library/busybox/images
DEBU[0019] Not continuing with error: Authentication is required.
```

but this is the log in 1.10:

```
DEBU[0201] POST /v1.23/images/create?fromImage=busybox%3Alatest
DEBU[0201] Trying to pull busybox from https://registry-1.docker.io v2
DEBU[0201] Error trying v2 registry: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password
DEBU[0201] Skipping v1 endpoint https://index.docker.io because v2 registry was detected
ERRO[0201] Handler for POST /v1.23/images/create returned error: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password
```

**Comment by aaronlehmann** [comment]
Makes sense. Docker 1.10 won't fall back to the v1 protocol because of a 401.

**Comment by tonistiigi** [comment]
@calavera I created another issue #19523 to track the error message/statuscode/prompt behavior change as we probably need to fix it in docker side instead. I think this can me merged as is.

**Comment by calavera** [comment]
@aaronlehmann I think we should remove the `Fixes...` from the description, since it doesn't completely fix the problem. Otherwise, I'm okay with fixing it in two steps.

**Comment by calavera** [comment]
LGTM

**Pull request merged**
