### PR TITLE
Modify the default value for network

### PR DESCRIPTION
**Pull request by yuexiao-wang**
**- What I did**
1. Modify the default value for network 
2. Update the documents and manuals

**- How I did it**

**- How to verify it**

**- Description for the changelog**
I found that the default value of "--network" is "default. However, supported standard  values of "--network" are: `bridge`, `host`, `none` and `container:<name|id>`.  So, I think that modify the default value of network from default to bridge.

Correct me if I misunderstand it. 
Thanks

Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

### CODE REVIEW

**Comment by thaJeztah** [comment]
I don't think we can change this, as it will break Windows; see https://github.com/docker/docker/issues/19421

**Comment by yuexiao-wang** [comment]
Got it and I will apply it to this PR.
Thanks

**Comment by vdemeester** [comment]
@yuexiao-wang `default` is a magic value, see https://github.com/docker/docker/issues/19421. This changes is not quite right as it will break windows.

> This value was needed because Windows does not have a "bridge" network, so requires some special handling to check if the default (type of) network is used, for example, in hostconfig_windows.go

I'll close for now, thanks though :angel:

**Comment by thaJeztah** [comment]
Thanks indeed; hopefully we can change it at some point.

**Pull request closed without merging**
