### PR TITLE
Remove Solaris support

### PR DESCRIPTION
**Pull request by justincormack**
If this were ever to be finished, the work would be in containerd 1.0
not in Docker, so remove here to make life easier.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

solaris

### CODE REVIEW

**Comment by thaJeztah** [comment]
I got a message that work on this may be started again, so let me at least notify @amitkris @puneetpruthi

**Comment by justincormack** [comment]
I think starting from `containerd` 1.0 support (which should be relatively easy, I have been fixing portability issues already) and then merging when we merge `containerd` 1.0 support would probably be the easiest route even so.

**Comment by justincormack** [comment]
cc @crosbymichael

**Comment by vdemeester** [comment]
I do agree with @justincormack. Let's start support of `containerd` first for solaris, then move downstream 👼

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by tophj-ibm** [comment]
@justincormack can probably remove this as well https://github.com/moby/moby/blob/master/hack/make.sh#L101

**Comment by justincormack** [comment]
@tophj-ibm added that

**Comment by puneetpruthi** [comment]
@thaJeztah thanks for tagging us in the PR.

I know our upstream activity went dead for a while and we apologize for that, but me and @epilatow here at Oracle Solaris are actively working on syncing with docker v17.03 and will be chasing tip thereafter.

While we were expecting this code to make its way out, we are still in process to add the required piece of functionality to containerd. Its our sincere request if you can hold off these changes till we file a PR to migrate this functionality to containerd.

**Comment by AkihiroSuda** [comment]
@puneetpruthi 
FYI: I implemented ZFS snapshotter plugin for containerd v1.0 (though unstable yet).
This might be useful for porting containerd v1.0 to Solaris.
 https://github.com/AkihiroSuda/containerd-zfs

**Comment by vdemeester** [comment]
Alright, let's close that for now as it is stall

**Comment by AkihiroSuda** [comment]
@puneetpruthi What's current status?

**Comment by thaJeztah** [comment]
I think the current status is "very unlikely" that Solaris support will reach completion before we switch to Containerd 1.0 (https://github.com/moby/moby/pull/34895), so I suggest to go ahead and remove (at least) the parts that will not be useful after the migration to containerd 1.0.

There were some concerns on https://github.com/moby/moby/pull/34861#issuecomment-329873862 that some packages could be useful in other contexts, so we can decide to leave those

/cc @justincormack @unclejack WDYT?

**Comment by puneetpruthi** [comment]
@AkihiroSuda, I agree with @thaJeztah. We can go ahead and remove dead code for migration to containerd 1.0.

**Pull request closed without merging**
