### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
Should this be 1.7.0-dev per the new checklist?

**Comment by thaJeztah** [comment]
This; https://github.com/docker/docker/commit/f07ac12791e4af7f199a893705204481588062ae#diff-2c916ac6fe12f749bf6c8bacfef6efd2

**Comment by jfrazelle** [comment]
lol hahahaa i will fix

**Comment by thaJeztah** [comment]
hehe, could have been a famous "release that never was"

**Comment by thaJeztah** [comment]
LGTM (albeit a confusing commit message LOLz)

**Comment by estesp** [comment]
LGTM

**Pull request merged**
