### PR TITLE
[24.0 backport] c8d/images: handle images without manifests for default platform

### PR DESCRIPTION
**Pull request by neersighted**
- Backport of https://github.com/moby/moby/pull/45816
- Backport of https://github.com/moby/moby/pull/45437
> **Warning**
> Slight conflicts due to a lack of:
> * https://github.com/moby/moby/pull/44598
> * https://github.com/moby/moby/pull/45504

---

**- What I did**
Fix https://github.com/moby/moby/issues/44578

**- How I did it**

For clarity: what was previously not working was the following block:

https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/daemon/containerd/image.go#L41-L50

passing 
```go
platform := platforms.AllPlatformsWithPreference(cplatforms.Default())
```
into
```go
containerdimages.Config(ctx, cs, desc, platform)
```
breaks because, after listing all the manifests in the index for the passed-in descriptor in:
https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/vendor/github.com/containerd/containerd/images/image.go#L215
they get sorted according to the `platform := platforms.AllPlatformsWithPreference(cplatforms.Default())` in:
https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/vendor/github.com/containerd/containerd/images/image.go#L221-L229
and then, in order of sorting, this block gets called:
https://github.com/moby/moby/blob/b1569b9c185b9d5371d30fb59c14f4694239a4f3/vendor/github.com/containerd/containerd/images/image.go#L150-L156

Which breaks since we don't have the manifests for the other platforms and the platform we do have isn't the first on the list.

**- How to verify it**
- `docker pull --platform=[non-default-platform] alpine`
- `docker inspect alpine`
- `docker history alpine`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by neersighted** [comment]
Whoops, when I re-did this I dropped a commit:

```
daemon/containerd/image.go:68:41: presentImages[i].Platform undefined (type "github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go/v1".Image has no field or method Platform)
daemon/containerd/image.go:68:68: presentImages[j].Platform undefined (type "github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go/v1".Image has no field or method Platform)
daemon/containerd/image_history.go:50:41: presentImages[i].Platform undefined (type "github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go/v1".Image has no field or method Platform)
daemon/containerd/image_history.go:50:68: presentImages[j].Platform undefined (type "github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go/v1".Image has no field or method Platform)

```

Added https://github.com/moby/moby/pull/45437 and things should build now :grinning:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by vvoland — APPROVED** [review]

**Review by laurazard — APPROVED** [review]
LGTM ❤️

**Comment by neersighted** [comment]
Bringing this one in, thanks!

**Pull request merged**
