### PR TITLE
Vendor containerd 1b3a81545ca79456086dc2aa424357be98b962ee

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure mickael.laventure@gmail.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐮
/cc @tiborvass what about #24231 though ? 😇

**Comment by tiborvass** [comment]
@vdemeester mine too :)

**Comment by vdemeester** [comment]
ah nevermind, didn't read righg the pr description :stuck_out_tongue_closed_eyes:

**Pull request merged**
