### PR TITLE
Update libcontainer to 6460fd79667466d2d9ec03f77f3

### PR DESCRIPTION
**Pull request by crosbymichael**

### CODE REVIEW

**Comment by crosbymichael** [comment]
Did drone miss this one?

**Comment by jfrazelle** [comment]
it's goinggggg it was just busy working on @vbatts PRs

**Comment by tianon** [comment]
LGTM although it still seems to me like `AdditionalGroups` should be a `[]string` so the interface is consistent :+1:

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
