### PR TITLE
Vendor engine-api 0.1.3

### PR DESCRIPTION
**Pull request by calavera**
Solves compatibility issues with the old docker interface.
Uses new structures for container create, update and network connect.

/cc @aboch, @jfrazelle, @vdemeester

### CODE REVIEW

**Comment by jfrazelle** [comment]
nice!

**Comment by jfrazelle** [comment]
LGTM as long as janky is happy

**Comment by icecrime** [comment]
LGTM

**Comment by vdemeester** [comment]
:tada:

**Pull request merged**
