### PR TITLE
Remove deprecated host-discovery and overlay networks with external k/v [step 1]

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to / addresses part of https://github.com/moby/moby/issues/40383

Taking https://github.com/moby/moby/pull/42247 in smaller steps, as there was some failure in CI on that PR.

This one is the first 2 commits (I may add more)

### CODE REVIEW

**Comment by thaJeztah** [comment]
... and now we're back at the tests that were failing on the original PR 😞 . It was hopeful in earlier pushes (only other tests failed) 🤔 

```
=== FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonICCLinkExpose (131.98s)
    docker_cli_daemon_test.go:909: assertion failed: error is not nil: exit status 1
    --- FAIL: TestDockerDaemonSuite/TestDaemonICCLinkExpose (131.98s)

=== FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonICCPing (6.02s)
    docker_cli_daemon_test.go:885: assertion failed: error is not nil: exit status 1: PING 192.171.1.1 (192.171.1.1): 56 data bytes
        
        --- 192.171.1.1 ping statistics ---
        1 packets transmitted, 0 packets received, 100% packet loss
        
    --- FAIL: TestDockerDaemonSuite/TestDaemonICCPing (6.02s)

=== FAIL: amd64.integration-cli TestDockerDaemonSuite (471.11s)
```

**Comment by thaJeztah** [comment]
Looks like that original PR / commit doesn't compile, so will need to add (some of) the commit after

```
# github.com/docker/docker/daemon
daemon/daemon.go:1437:29: undefined: "github.com/docker/docker/libnetwork/config".OptionKVProvider
daemon/daemon.go:1438:29: undefined: "github.com/docker/docker/libnetwork/config".OptionKVProviderURL
daemon/daemon.go:1441:29: undefined: "github.com/docker/docker/libnetwork/config".OptionKVOpts
daemon/daemon.go:1445:29: undefined: "github.com/docker/docker/libnetwork/config".OptionDiscoveryWatcher
daemon/daemon.go:1449:29: undefined: "github.com/docker/docker/libnetwork/config".OptionDiscoveryAddress
```

**Comment by thaJeztah** [comment]
And of course the test passes locally;


```bash
make DOCKER_GRAPHDRIVER=vfs TESTFLAGS='-test.run TestDockerDaemonSuite/TestDaemonICC*' test-integration-cli
...
Running /go/src/github.com/docker/docker/integration-cli (amd64.integration-cli) flags=-test.v -test.timeout=360m -test.run TestDockerDaemonSuite/TestDaemonICC*
INFO: Testing against a local daemon
=== RUN   TestDockerDaemonSuite
=== RUN   TestDockerDaemonSuite/TestDaemonICCLinkExpose
=== RUN   TestDockerDaemonSuite/TestDaemonICCPing
--- PASS: TestDockerDaemonSuite (45.86s)
    --- PASS: TestDockerDaemonSuite/TestDaemonICCLinkExpose (20.14s)
    --- PASS: TestDockerDaemonSuite/TestDaemonICCPing (25.71s)
PASS

DONE 3 tests in 45.956s
```

**Comment by thaJeztah** [comment]
So it looks like the problem is not in those tests, but in side-effect from tests that run before them. I was able to bisect what test(s) cause the issue;

This passes:

```bash
make DOCKER_GRAPHDRIVER=vfs TEST_SKIP_INTEGRATION=1 TESTFLAGS='-test.run TestDockerDaemonSuite/TestDaemon(DefaultGatewayIPv4Explicit|ICC)' test-integration-cli
...
--- PASS: TestDockerDaemonSuite (11.03s)
    --- PASS: TestDockerDaemonSuite/TestDaemonDefaultGatewayIPv4Explicit (2.17s)
    --- PASS: TestDockerDaemonSuite/TestDaemonDefaultGatewayIPv4ExplicitOutsideContainerSubnet (1.45s)
    --- PASS: TestDockerDaemonSuite/TestDaemonICCLinkExpose (2.86s)
    --- PASS: TestDockerDaemonSuite/TestDaemonICCPing (4.49s)
PASS

DONE 5 tests in 14.054s
...
```

This fails:

```
make DOCKER_GRAPHDRIVER=vfs TEST_SKIP_INTEGRATION=1 TESTFLAGS='-test.run TestDockerDaemonSuite/TestDaemon(DefaultGatewayIPv4Implicit|ICC)' test-integration-cli

--- FAIL: TestDockerDaemonSuite (140.31s)
    --- PASS: TestDockerDaemonSuite/TestDaemonDefaultGatewayIPv4Implicit (2.07s)
    --- FAIL: TestDockerDaemonSuite/TestDaemonICCLinkExpose (132.85s)
    --- FAIL: TestDockerDaemonSuite/TestDaemonICCPing (5.37s)
FAIL

=== Failed
=== FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonICCLinkExpose (132.85s)
    docker_cli_daemon_test.go:909: assertion failed: error is not nil: exit status 1
    --- FAIL: TestDockerDaemonSuite/TestDaemonICCLinkExpose (132.85s)

=== FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonICCPing (5.37s)
    docker_cli_daemon_test.go:885: assertion failed: error is not nil: exit status 1: PING 192.171.1.1 (192.171.1.1): 56 data bytes

        --- 192.171.1.1 ping statistics ---
        1 packets transmitted, 0 packets received, 100% packet loss

    --- FAIL: TestDockerDaemonSuite/TestDaemonICCPing (5.37s)

=== FAIL: amd64.integration-cli TestDockerDaemonSuite (140.31s)
```

So culprit looks to be `TestDockerDaemonSuite/TestDaemonDefaultGatewayIPv4Implicit`, which is quite similar to `TestDaemonDefaultGatewayIPv4Explicit`; here's the diff between the two;

```patch
diff --git a/explicit.txt b/implicit.txt
index 8b30312abe..0cfb8c6620 100644
--- a/explicit.txt
+++ b/implicit.txt
@@ -1,4 +1,4 @@
-func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4Explicit(c *testing.T) {
+func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4Implicit(c *testing.T) {
        defaultNetworkBridge := "docker0"
        deleteInterface(c, defaultNetworkBridge)

@@ -6,14 +6,13 @@ func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4Explicit(c *testing.T) {

        bridgeIP := "192.169.1.1"
        bridgeIPNet := fmt.Sprintf("%s/24", bridgeIP)
-       gatewayIP := "192.169.1.254"

-       d.StartWithBusybox(c, "--bip", bridgeIPNet, "--default-gateway", gatewayIP)
+       d.StartWithBusybox(c, "--bip", bridgeIPNet)
        defer d.Restart(c)

-       expectedMessage := fmt.Sprintf("default via %s dev", gatewayIP)
+       expectedMessage := fmt.Sprintf("default via %s dev", bridgeIP)
        out, err := d.Cmd("run", "busybox", "ip", "-4", "route", "list", "0/0")
        assert.NilError(c, err, out)
-       assert.Equal(c, strings.Contains(out, expectedMessage), true, fmt.Sprintf("Explicit default gateway should be %s, but default route was '%s'", gatewayIP, strings.TrimSpace(out)))
+       assert.Equal(c, strings.Contains(out, expectedMessage), true, fmt.Sprintf("Implicit default gateway should be bridge IP %s, but default route was '%s'", bridgeIP, strings.TrimSpace(out)))
        deleteInterface(c, defaultNetworkBridge)
 }
```

**Comment by errordeveloper** [comment]
@thaJeztah great find! I think next step would be to see how iptables rules evolves between `TestDaemonDefaultGatewayIPv4Implicit` and `TestDaemonDefaultGatewayIPv4Implicit`.

**Comment by thaJeztah** [comment]
No dice so far; saving iptables before/after those tests, and AFAICS, the both leave iptables in a similar state; here's my debugging code;

<details>

```patch
diff --git a/integration-cli/docker_cli_daemon_test.go b/integration-cli/docker_cli_daemon_test.go
index 92f2ed249b..9684af00d3 100644
--- a/integration-cli/docker_cli_daemon_test.go
+++ b/integration-cli/docker_cli_daemon_test.go
@@ -774,7 +774,15 @@ func (s *DockerDaemonSuite) TestDaemonBridgeFixedCIDREqualBridgeNetwork(c *testi
 	defer d.Cmd("stop", cid1)
 }
 
+func saveTables(c *testing.T, name string) {
+	c.Helper()
+	ipt := icmd.RunCommand("iptables-save").Assert(c, icmd.Success).Stdout()
+	err := os.WriteFile(path.Join("/go/src/github.com/docker/docker/bundles", path.Base(name)), []byte(ipt), 0644)
+	assert.NilError(c, err)
+}
+
 func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4Implicit(c *testing.T) {
+	saveTables(c, c.Name()+"-before")
 	defaultNetworkBridge := "docker0"
 	deleteInterface(c, defaultNetworkBridge)
 
@@ -791,9 +799,11 @@ func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4Implicit(c *testing.T) {
 	assert.NilError(c, err, out)
 	assert.Equal(c, strings.Contains(out, expectedMessage), true, fmt.Sprintf("Implicit default gateway should be bridge IP %s, but default route was '%s'", bridgeIP, strings.TrimSpace(out)))
 	deleteInterface(c, defaultNetworkBridge)
+	saveTables(c, c.Name()+"-after")
 }
 
 func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4Explicit(c *testing.T) {
+	saveTables(c, c.Name()+"-before")
 	defaultNetworkBridge := "docker0"
 	deleteInterface(c, defaultNetworkBridge)
 
@@ -811,6 +821,7 @@ func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4Explicit(c *testing.T) {
 	assert.NilError(c, err, out)
 	assert.Equal(c, strings.Contains(out, expectedMessage), true, fmt.Sprintf("Explicit default gateway should be %s, but default route was '%s'", gatewayIP, strings.TrimSpace(out)))
 	deleteInterface(c, defaultNetworkBridge)
+	saveTables(c, c.Name()+"-after")
 }
 
 func (s *DockerDaemonSuite) TestDaemonDefaultGatewayIPv4ExplicitOutsideContainerSubnet(c *testing.T) {
```

</details>

Which produced these (added `.txt` for github);

[TestDaemonDefaultGatewayIPv4Explicit-after.txt](https://github.com/moby/moby/files/7754222/TestDaemonDefaultGatewayIPv4Explicit-after.txt)
[TestDaemonDefaultGatewayIPv4Explicit-before.txt](https://github.com/moby/moby/files/7754230/TestDaemonDefaultGatewayIPv4Explicit-before.txt)
[TestDaemonDefaultGatewayIPv4Implicit-after.txt](https://github.com/moby/moby/files/7754231/TestDaemonDefaultGatewayIPv4Implicit-after.txt)
[TestDaemonDefaultGatewayIPv4Implicit-before.txt](https://github.com/moby/moby/files/7754235/TestDaemonDefaultGatewayIPv4Implicit-before.txt)

And diffs between both tests (ignoring comments) seem irrelevant; at least; the "after" state is identical.

<details>
<summary>Before</summary>

```patch
diff --git a/bundles/TestDaemonDefaultGatewayIPv4Explicit-before b/bundles/TestDaemonDefaultGatewayIPv4Implicit-before
index d517153a55..2c744b99a9 100644
--- a/bundles/TestDaemonDefaultGatewayIPv4Explicit-before
+++ b/bundles/TestDaemonDefaultGatewayIPv4Implicit-before
@@ -1,8 +1,8 @@
-# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:26 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:41 2021
 *filter
 :INPUT ACCEPT [0:0]
 :FORWARD ACCEPT [0:0]
-:OUTPUT ACCEPT [1:40]
+:OUTPUT ACCEPT [0:0]
 :DOCKER - [0:0]
 :DOCKER-ISOLATION-STAGE-1 - [0:0]
 :DOCKER-ISOLATION-STAGE-2 - [0:0]
@@ -19,17 +19,17 @@
 -A DOCKER-ISOLATION-STAGE-2 -j RETURN
 -A DOCKER-USER -j RETURN
 COMMIT
-# Completed on Tue Dec 21 11:14:26 2021
-# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:26 2021
+# Completed on Tue Dec 21 11:14:41 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:41 2021
 *nat
 :PREROUTING ACCEPT [0:0]
 :INPUT ACCEPT [0:0]
-:OUTPUT ACCEPT [1:40]
-:POSTROUTING ACCEPT [1:40]
+:OUTPUT ACCEPT [0:0]
+:POSTROUTING ACCEPT [0:0]
 :DOCKER - [0:0]
 -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
 -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
--A POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE
+-A POSTROUTING -s 172.16.0.0/16 ! -o docker0 -j MASQUERADE
 -A DOCKER -i docker0 -j RETURN
 COMMIT
-# Completed on Tue Dec 21 11:14:26 2021
+# Completed on Tue Dec 21 11:14:41 2021
```

</details>


<details>
<summary>After</summary>


```patch
diff --git a/bundles/TestDaemonDefaultGatewayIPv4Explicit-after b/bundles/TestDaemonDefaultGatewayIPv4Implicit-after
index 59e23b92f3..9ea01de163 100644
--- a/bundles/TestDaemonDefaultGatewayIPv4Explicit-after
+++ b/bundles/TestDaemonDefaultGatewayIPv4Implicit-after
@@ -1,4 +1,4 @@
-# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:36 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:53 2021
 *filter
 :INPUT ACCEPT [0:0]
 :FORWARD ACCEPT [0:0]
@@ -8,8 +8,8 @@
 :DOCKER-ISOLATION-STAGE-2 - [0:0]
 :DOCKER-USER - [0:0]
 COMMIT
-# Completed on Tue Dec 21 11:14:36 2021
-# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:36 2021
+# Completed on Tue Dec 21 11:14:53 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:14:53 2021
 *nat
 :PREROUTING ACCEPT [0:0]
 :INPUT ACCEPT [0:0]
@@ -17,4 +17,4 @@ COMMIT
 :POSTROUTING ACCEPT [0:0]
 :DOCKER - [0:0]
 COMMIT
-# Completed on Tue Dec 21 11:14:36 2021
+# Completed on Tue Dec 21 11:14:53 2021
```

</details>

**Comment by thaJeztah** [comment]
So, I think the next thing to look into is `docker0`. Perhaps something is left behind there? 🤔

**Comment by thaJeztah** [comment]
Actually, that wouldn't make sense either, because `TestDaemonICCPing` creates its own bridge? 🤔

**Comment by thaJeztah** [comment]
Oh, hm.. perhaps I should also check the iptables "before" (in the ICC tests) with and without running the "Implicit" test before, as it looks like something is set up before the tests run

**Comment by errordeveloper** [comment]
@thaJeztah let's look at `ip addr`, `ip route` & `ip rule` before and after each of the tests also...

**Comment by thaJeztah** [comment]
OK; here's the "before" state of iptables at the start of `TestDaemonICCLinkExpose` "without" first running `TestDaemonDefaultGatewayIPv4Implicit` and "with" running it first;
[TestDaemonICCLinkExpose-before-with.txt](https://github.com/moby/moby/files/7755130/TestDaemonICCLinkExpose-before-with.txt)
[TestDaemonICCLinkExpose-before-without.txt](https://github.com/moby/moby/files/7755131/TestDaemonICCLinkExpose-before-without.txt)

And the diff;

<details>

```patch
diff --git a/WithoutImplicit/TestDaemonICCLinkExpose-before b/WIthImplicit/TestDaemonICCLinkExpose-before
index 0adeb0559f..104bc93ab4 100644
--- a/WithoutImplicit/TestDaemonICCLinkExpose-before
+++ b/WIthImplicit/TestDaemonICCLinkExpose-before
@@ -1,8 +1,8 @@
-# Generated by iptables-save v1.8.7 on Tue Dec 21 11:47:59 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:42:46 2021
 *filter
 :INPUT ACCEPT [0:0]
 :FORWARD ACCEPT [0:0]
-:OUTPUT ACCEPT [1:40]
+:OUTPUT ACCEPT [0:0]
 :DOCKER - [0:0]
 :DOCKER-ISOLATION-STAGE-1 - [0:0]
 :DOCKER-ISOLATION-STAGE-2 - [0:0]
@@ -19,17 +19,17 @@
 -A DOCKER-ISOLATION-STAGE-2 -j RETURN
 -A DOCKER-USER -j RETURN
 COMMIT
-# Completed on Tue Dec 21 11:47:59 2021
-# Generated by iptables-save v1.8.7 on Tue Dec 21 11:47:59 2021
+# Completed on Tue Dec 21 11:42:46 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:42:46 2021
 *nat
 :PREROUTING ACCEPT [0:0]
 :INPUT ACCEPT [0:0]
-:OUTPUT ACCEPT [1:40]
-:POSTROUTING ACCEPT [1:40]
+:OUTPUT ACCEPT [0:0]
+:POSTROUTING ACCEPT [0:0]
 :DOCKER - [0:0]
 -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
 -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
--A POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE
+-A POSTROUTING -s 192.169.1.0/24 ! -o docker0 -j MASQUERADE
 -A DOCKER -i docker0 -j RETURN
 COMMIT
-# Completed on Tue Dec 21 11:47:59 2021
+# Completed on Tue Dec 21 11:42:46 2021
```

</details>


Difference there is the IP-range in `POSTROUTING`

**Comment by errordeveloper** [comment]
Looks like `TestDaemonICCPing` calls `createInterface` twice, and second call is not followed by `defer deleteInterface`... that might be something ;)


https://github.com/moby/moby/blob/085c6a98d54720e70b28354ccec6da9b1b9e7fcf/integration-cli/docker_cli_daemon_test.go#L895

**Comment by thaJeztah** [comment]
@errordeveloper yes, I was looking at that as well, and did add a defer for that locally (which didn't fix the issue). HOWEVER, due to the `defer d.Reload()`, and defers being executed in reverse order, it's possible that didn't fully work (so will do some testing there).

I also just did a diff between "first running the `TestDaemonDefaultGatewayIPv4Explicit*` test before the `TestDaemonICC*` tests, and that also produces a different IP range (although both in the `172.x.x.x` range), so likely(?) the IP-range is a red herring.

The fact that it _does_ pick a whole different range may indicate that something is not cleaned up though (docker does some checks to pick an "available" range)

<details>

```patch
diff --git a/bundles/TestDaemonICCLinkExpose-before b/WithoutImplicit/TestDaemonICCLinkExpose-before-without.txt
index 7281cf9337..0adeb0559f 100644
--- a/bundles/TestDaemonICCLinkExpose-before
+++ b/WithoutImplicit/TestDaemonICCLinkExpose-before-without.txt
@@ -1,8 +1,8 @@
-# Generated by iptables-save v1.8.7 on Tue Dec 21 12:06:27 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:47:59 2021
 *filter
 :INPUT ACCEPT [0:0]
 :FORWARD ACCEPT [0:0]
-:OUTPUT ACCEPT [0:0]
+:OUTPUT ACCEPT [1:40]
 :DOCKER - [0:0]
 :DOCKER-ISOLATION-STAGE-1 - [0:0]
 :DOCKER-ISOLATION-STAGE-2 - [0:0]
@@ -19,17 +19,17 @@
 -A DOCKER-ISOLATION-STAGE-2 -j RETURN
 -A DOCKER-USER -j RETURN
 COMMIT
-# Completed on Tue Dec 21 12:06:27 2021
-# Generated by iptables-save v1.8.7 on Tue Dec 21 12:06:27 2021
+# Completed on Tue Dec 21 11:47:59 2021
+# Generated by iptables-save v1.8.7 on Tue Dec 21 11:47:59 2021
 *nat
 :PREROUTING ACCEPT [0:0]
 :INPUT ACCEPT [0:0]
-:OUTPUT ACCEPT [0:0]
-:POSTROUTING ACCEPT [0:0]
+:OUTPUT ACCEPT [1:40]
+:POSTROUTING ACCEPT [1:40]
 :DOCKER - [0:0]
 -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
 -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
--A POSTROUTING -s 172.16.0.0/16 ! -o docker0 -j MASQUERADE
+-A POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE
 -A DOCKER -i docker0 -j RETURN
 COMMIT
-# Completed on Tue Dec 21 12:06:27 2021
+# Completed on Tue Dec 21 11:47:59 2021
```

</details>

**Comment by thaJeztah** [comment]
looks like https://github.com/moby/moby/pull/42247 is all green now, so we may as well rip off the band-aid in one go, and use that one instead

**Pull request closed without merging**
