### PR TITLE
[20.10 backport] Dockerfile: update golangci-lint v1.44.0

### PR DESCRIPTION
**Pull request by thaJeztah**
- backport of https://github.com/moby/moby/pull/42445
- backport of https://github.com/moby/moby/commit/4a52c46e37959a0a1b006304cc1c9a2812cc8d79
- backport of https://github.com/moby/moby/pull/43202
- backport of https://github.com/moby/moby/pull/43195

Some small changes needed;

- version is specified in the installer in this branch
- libnetwork commit is not needed in 20.10 branch
- some conflicts in golangci yaml config (but CI should show if it's correct)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Some linting issues to fix (or backport);

```
pkg/namesgenerator/names-generator.go:843:36: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
	name := fmt.Sprintf("%s_%s", left[rand.Intn(len(left))], right[rand.Intn(len(right))])
	                                  ^
pkg/namesgenerator/names-generator.go:849:36: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
		name = fmt.Sprintf("%s%d", name, rand.Intn(10))
		                                 ^
testutil/stringutils.go:11:18: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
		b[i] = letters[rand.Intn(len(letters))]
		               ^
pkg/archive/copy.go:357:16: G110: Potential DoS vulnerability via decompression bomb (gosec)
			if _, err = io.Copy(rebasedTar, srcTar); err != nil {
			            ^
plugin/v2/plugin.go:141:50: G601: Implicit memory aliasing in for loop. (gosec)
				updateSettingsEnv(&p.PluginObj.Settings.Env, &s)
				                                             ^
daemon/logger/splunk/splunk.go:173:16: G402: TLS MinVersion too low. (gosec)
	tlsConfig := &tls.Config{}
	              ^
libcontainerd/remote/client.go:572:13: G601: Implicit memory aliasing in for loop. (gosec)
			cpDesc = &m
			         ^
distribution/push_v2.go:405:34: G601: Implicit memory aliasing in for loop. (gosec)
			(metadata.CheckV2MetadataHMAC(&mountCandidate, pd.hmacKey) ||
			                              ^
integration/network/service_test.go:295:6: func `swarmIngressReady` is unused (unused)
func swarmIngressReady(client client.NetworkAPIClient) func(log poll.LogT) poll.Result {
     ^
integration/build/build_session_test.go:92:6: func `testBuildWithSession` is unused (unused)
func testBuildWithSession(t *testing.T, client dclient.APIClient, daemonHost string, dir, dockerfile string) (outStr string) {
     ^
integration/container/checkpoint_test.go:23:6: func `containerExec` is unused (unused)
func containerExec(t *testing.T, client client.APIClient, cID string, cmd []string) {
     ^
daemon/stats/collector.go:159:6: type `notFoundErr` is unused (unused)
type notFoundErr interface {
     ^
daemon/stats/collector.go:154:6: type `notRunningErr` is unused (unused)
type notRunningErr interface {
     ^
integration/plugin/graphdriver/external_test.go:132:4: S1038: should use fmt.Fprintf instead of fmt.Fprintln(fmt.Sprintf(...)) (but don't forget the newline) (gosimple)
			fmt.Fprintln(w, fmt.Sprintf(`{"Err": %q}`, t.Error()))
			^
registry/endpoint_v1.go:92:2: S1017: should replace this if statement with an unconditional strings.TrimSuffix (gosimple)
	if strings.HasSuffix(address, "/") {
	^
client/request.go:243:2: S1031: unnecessary nil check around range (gosimple)
	if headers != nil {
	^
pkg/devicemapper/devmapper.go:384:28: S1039: unnecessary use of fmt.Sprintf (gosimple)
	if err := task.setMessage(fmt.Sprintf("@cancel_deferred_remove")); err != nil {
	                          ^
integration/plugin/graphdriver/external_test.go:321:18: S1039: unnecessary use of fmt.Sprintf (gosimple)
			http.Error(w, fmt.Sprintf("missing id"), 409)
			              ^
integration-cli/docker_api_stats_test.go:70:31: S1039: unnecessary use of fmt.Sprintf (gosimple)
		_, body, err := request.Get(fmt.Sprintf("/info"))
		                            ^
daemon/graphdriver/graphtest/graphtest_unix.go:306:12: unsafeptr: possible misuse of reflect.SliceHeader (govet)
	header := *(*reflect.SliceHeader)(unsafe.Pointer(&buf))
	          ^
daemon/graphdriver/graphtest/graphtest_unix.go:309:36: unsafeptr: possible misuse of reflect.SliceHeader (govet)
	data := *(*[]byte)(unsafe.Pointer(&header))
	                                  ^
client/hijack.go:85:16: SA1019: httputil.NewClientConn has been deprecated since Go 1.0: Use the Client or Transport in package net/http instead. (staticcheck)
	clientconn := httputil.NewClientConn(conn, nil)
	              ^
integration/plugin/authz/authz_plugin_test.go:181:7: SA1019: httputil.NewClientConn has been deprecated since Go 1.0: Use the Client or Transport in package net/http instead. (staticcheck)
	c := httputil.NewClientConn(conn, nil)
	     ^
integration/plugin/authz/authz_plugin_test.go:480:12: SA1019: httputil.NewClientConn has been deprecated since Go 1.0: Use the Client or Transport in package net/http instead. (staticcheck)
	client := httputil.NewClientConn(conn, nil)
	          ^
daemon/volumes_unix_test.go:229:13: SA4001: &*x will be simplified to x. It will not copy x. (staticcheck)
			mp:      &(*c.MountPoints["/jambolan"]), // copy the mountpoint, expect no changes
			         ^
daemon/logger/local/local_test.go:214:22: SA4001: &*x will be simplified to x. It will not copy x. (staticcheck)
		dst.PLogMetaData = &(*src.PLogMetaData)
		                   ^
```

**Comment by thaJeztah** [comment]
Looks like I need https://github.com/moby/moby/pull/42445

**Comment by thaJeztah** [comment]
Almost there; one remaining;

```

 registry/endpoint_v1.go:92:2: S1017: should replace this if statement with an unconditional strings.TrimSuffix (gosimple)
 	if strings.HasSuffix(address, "/") {
 	^
```

**Comment by thaJeztah** [comment]
Looks like https://github.com/moby/moby/commit/4a52c46e37959a0a1b006304cc1c9a2812cc8d79 (part of https://github.com/moby/moby/pull/42915) fixed that

**Review by cpuguy83 — APPROVED** [review]

**Review by samuelkarp — APPROVED** [review]

**Pull request merged**
