### PR TITLE
Remove broken container check from image prune

### PR DESCRIPTION
**Pull request by dnephin**
Below is my understanding of the code, please correct me if this is wrong.

The `imageRefs` map was being populated with `container.ID`, and accessed with an `image.ID` which would never match. So as far as I can tell `imageRefs[hex]` would always be false, and would never skip the delete.

I have removed this code because at best this would be very racy. New containers could be created after getting the list, and existing containers could have been removed before getting  to the ID check.

`ImageDelete()` should already handle preventing of removal of used images, so we should be fine to remove it.

### CODE REVIEW

**Comment by dnephin** [comment]
Any thoughts on this?

**Comment by mlaventure** [comment]
uh, this look wrong indeed. I honestly don't remember why I even tried to do so manually.

This definitely look more correct, although it will output quite a few warnings to the log in some situation

**Comment by dnephin** [comment]
True, but I would expect the logs will already contain those errors now, since the filter isn't working as it was intended. So there shouldn't be an increase in the number of warnings.

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by tonistiigi** [comment]
Even if this was broken all the time there is no reason to show these warnings for images that shouldn't be removed anyway. It seems this was what the original code tried to achieve but just used a wrong ID in setting `imageRefs` values.

**Comment by dnephin** [comment]
Do you know what the warnings are? 

I think it would be better to ignore the errors from remove instead of attempting to filter images based on container ids, which is very racy.

**Comment by tonistiigi** [comment]
> Do you know what the warnings are?

things like `could not delete image f5b9ccf176447d43d73ffafee9cd273ca41f1f8e4a8cbaf8ed62e7a903ed4f57: conflict: unable to delete f5b9ccf17644 (must be forced) - image is being used by stopped container 756630f0ec5c` that have no context for prune.

> I think it would be better to ignore the errors from remove instead of attempting to filter images based on container ids, which is very racy.

Prune is always racy/best effort and no way to predict what was or wasn't deleted. This was discussed in the original PR, comparing daemon-side vs client-side approaches.

> I guess I can check the err returned by ImageDelete, and if it's an "in use" error then just don't print a warning.

Yes, returning typed errors would be fine to avoid the same issue.

**Comment by dnephin** [comment]
Sounds good. Updated to not warn when `IsConflict(err)`.

**Comment by dnephin** [comment]
ping @tonistiigi  LGTY with the change to not warn on conflict?

**Comment by thaJeztah** [comment]
@dnephin this fixes https://github.com/moby/moby/issues/36295, correct?

**Comment by pslacerda** [comment]
Hi folks,

@dnephin probably if you rebase your branch `docker image prune --all --force` wil delete images used by running containers. My fix at #36346 is based at current master and only has the `container.ID` or `image.ID` issue fixed because collect ignores at `imageRefs` (now `ingoredImageIDs`).

@tonistiigi This collect then do something approach is really prone to race conditions. But the prune can be tunned to win the race more times by moving the `ignoredImageIDs` collection to just before `daemon.ImageDelete()`. Sure it will be a bit more costly but is not that much. Another way to not even start a race condition is to create a prune lock to don't allow start or stop containers neither add or remove images whiling pruning, but this a lot more costly.

If my guess that if rebase this pull will cause #36295 is correct, I'd move the collection step to just before deletion.

Keep the good work!

**Comment by dnephin** [comment]
Yes, I believe so, adding fixes #36295

**Comment by tonistiigi** [comment]
@dnephin Could you look what is the issue behind #36295 before we go ahead with this refactoring.

@pslacerda 

> Another way to not even start a race condition is to create a prune lock to don't allow start or stop containers neither add or remove images while pruning, but this a lot more costly.

We can't control when containers stop neither can we control the order of requests from multiple clients. By races, I meant that there is no way to predict what will be deleted and that will still be true. Or if container died during prune or just after. Only way to avoid that if prune happens on daemon side is if we had API like `starttransaction/endtransaction` that adds locking between requests.

**Comment by dnephin** [comment]
Looking into this in https://github.com/moby/moby/issues/36295#issuecomment-367438543, it is an issue with `ImageDelete` I believe.

**Comment by dnephin** [comment]
Cross-posting here. #36295 seems to be the documented behaviour:

https://github.com/moby/moby/blob/8f6a40a3f126ae1dc0a74dc612a3f7b14de4e7f6/daemon/image_delete.go#L35-L39

So I don't think we should block this PR. `ImageDelete` can be fixed separately.

**Review by tonistiigi — APPROVED** [review]

**Comment by tonistiigi** [comment]
Let's make sure we address #36295 as well. This PR only fixes the logging, the issue caused by this wrong ID check is still there.

**Comment by githubsaturn** [comment]
Hi guys, any update on this PR?

**Comment by thaJeztah** [comment]
@githubsaturn can you elaborate; what update are you looking for? The PR was merged three months ago

**Comment by githubsaturn** [comment]
My apologies for not being clear. 

I was referring to this issue https://github.com/moby/moby/issues/36295 as it's still present and not fixed by this PR.

**Pull request merged**
