### PR TITLE
update docker deploy command according to deploy.go

### PR DESCRIPTION
**Pull request by lixiaobing1**
update docker deploy command according to deploy.go and deploy.md.

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
- `docker deploy vossibility-stack`  should be updated as well with `--bundle-file`
- "Managing stacks" section should not be mentioned in this file, since it is not an experimental feature
- Some notes about "1.12" should be updated

**Comment by AkihiroSuda** [comment]
ping @lixiaobing10051267

**Comment by LK4D4** [comment]
ping @lixiaobing10051267 or @thaJeztah for carry

**Comment by vdemeester** [comment]
Carrying into #30789

**Pull request closed without merging**
