### PR TITLE
Updating the DockerFile for build failure, when make build is done, f…

### PR DESCRIPTION
**Pull request by rojingeorge**
- What I did
  While building docker from source, to get the dependencies installed had done make build, then had got this error.
- How I did it
  In the DockerFIle, instead using space a tab was put, which when was done make build the next line was getting combined and was unable to install the package.
  image
  image

Refer the below Hex View of the earlier file.
image
- How to verify it
  After fixing, changing tab to space, built from source to install dependencies and was success
- Description for the changelog

Fixing Issue #27035

Signed-off-by: Rojin George itsmerojin@gmail.com

### CODE REVIEW

**Comment by tonistiigi** [comment]
SGTM for cleanup but don't understand why this causes actual failure for you and not for anyone else

**Comment by thaJeztah** [comment]
I'm interested as well how this could affect the build; if tabs are stripped from the Dockerfile, that sounds like a bug (but I never ran into this). @duglin any ideas?

**Comment by duglin** [comment]
hmmm how can I reproduce this?
```
FROM ubuntu
RUN echo hi \
    bye \
    good    \
    test
```
where its a tab before the \\ after "good" seems to parse ok for me.

**Comment by duglin** [comment]
And:
```
FROM ubuntu
RUN echo "hi \
bye \
good    \
test
```
Shows:
```
Step 2/2 : RUN echo "hi bye good	test"
 ---> Running in 1995922a7448
hi bye good	test
```
notice the tab between good and test

**Comment by rojingeorge** [comment]
@tonistiigi @thaJeztah  - Thanks for giving a look onto this. Its a strange funny problem that I had come across, while doing the build. Somehow the tabs where getting removed during the Dockerfile execution.

@duglin - Its happening for me, and once  I change it from tabs to spaces, the issue is resolved. Hence thought to give back using a PR.
image

**Comment by thaJeztah** [comment]
@rojingeorge to exclude the possibility there's something weird with your checkout; can you build the Dockerfile directly from GitHub? You can do so like this;

```
docker build -t test github.com/docker/docker
```

This will checkout the docker/docker repository in the background, so it takes a while before the actual build starts.

**Comment by rojingeorge** [comment]
@thaJeztah - I had cloned the master repository and had used its DockerFile. 

There were some changes from my end since I am behind a corporate proxy, so I had added mine proxy details to apts and curls inside it. While executing the steps in the Dockerfile, I encountered this problem of both lines getting combined, shown in the screenshot and apt was unable to locate this package. And as I mentioned, after changing the tab to space it worked for me.  Hence this PR to update that one line.

**Comment by duglin** [comment]
@rojingeorge even though I agree with this PR, we should replace the tab with a space, I would first like to figure out what's going on.  Can you take Docker's Dockerfile and shrink it down to the bare minimum to reproduce the issue? And in particular, replace the apt-get with just an echo - to make it easier to run.

**Comment by rojingeorge** [comment]
@duglin - I tried with echo, i am unable to reproduce this problem. 

image

Because of the tabs, may be my editor was stripping out the tabs/spaces, hence those got combined. You can see the output that I was getting in previous screenshots. Kindly process this changes.

**Comment by duglin** [comment]
@rojingeorge is your docker client on windows? And I assume the server is on linux, right? What distro?

**Comment by rojingeorge** [comment]
@duglin Both client and server on ubuntu 14.04, working on windows for other activities, editor was on windows.

**Comment by duglin** [comment]
and which version of docker are you using? client and server

**Comment by duglin** [comment]
can you provide me the exact git commit for both too?  (output from docker version)

**Comment by tonistiigi** [comment]
@duglin the issue #27035 has version info

**Comment by duglin** [comment]
ah ok thanks!

**Comment by duglin** [comment]
I give up :-)   I just can't reproduce this.
So LGTM

**Comment by rojingeorge** [comment]
@duglin - Thanks. Nice to see, that this PR helped to uncover more some improvements in other modules.

**Pull request merged**
