### PR TITLE
Contribute update to Project

### PR DESCRIPTION
**Pull request by moxiegirl**
This work was done in preparation for the birthday.  It improves on what we have but is not perfect...yet.  

Link to live demo; http://52.11.52.251:8000/project/who-written-for/

### CODE REVIEW

**Comment by thaJeztah** [comment]
Lot of writing and useful info!  :)

I'll give it a proper read later on, but (apart from some `tbd` placeholders) I see a couple of things that might need to be fixed before merging;

- Not a big issue, but I've learned earlier this week that *each commit* will trigger a new build on Jenkins, which can be time-consuming and uphold testing of other pull-requests. I think some of the commits in this PR could be "squashed" (combined). I'm not a "git guru" myself, but there should be people available to help on IRC if you need that
- To keep Google happy, redirects can be added for the renamed/deleted pages. Sven recently explained me where this could be done, so I can probably help with that if you have a list of "old page -> new page"
- My PR for table styling (https://github.com/docker/docs-base/pull/1) was merged. Perhaps this affects the styling of your tables. Also some inline `<style>` blocks could no longer be nescessary.
- Cropping and optimising of images :smile: 

I'm willing to spent some time to make these changes. If you want, I can create a pull-request on your repository with these changes to help you out so that they can be included in this PR

Let me know if your want me to spent some time on that this weekend :)

**Comment by spf13** [comment]
LGTM. 

@thaJeztah Thanks for the feedback and willingness to help. I think we should squash these into one commit, then merge (as this is already better than what's live today). Can you send a follow up Pull Request with your improvements?

**Comment by thaJeztah** [comment]
@spf13 sure I can do that; just thought that (e.g) optimising the images *before* merging could prevent ballooning the Git repo over time :smile:

If you prefer merging this ASAP, that's okay with me, the I'll create a follow-up PR

**Comment by spf13** [comment]
@thaJeztah, yeah, that's a valid point. My motivation is to get this to the public for feedback quickly as we are about to have hundreds of new contributors all at the same time.

**Comment by thaJeztah** [comment]
@spf13 Yup, good point as well and this is probably a bit of a "special" situation, in which case, just merge. I'm happy to create a follow-up after that.

**Comment by moxiegirl** [comment]
@spf13 @thaJeztah Unfortunately, I can't squash what I've already pushed according to GitHub. https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by spf13** [comment]
I don't think that's correct, but it's fine. Let's just merge.

**Comment by moxiegirl** [comment]
I sorted it.  Moving forward...

**Comment by thaJeztah** [comment]
Looks like there's merge conflicts in the PR https://github.com/docker/docker/pull/11209/files#diff-d5e65b9452cf766e18b4452241df3b66R173

**Comment by moxiegirl** [comment]
@thaJeztah thanks...I'm double checking everything -- caught that. But it sure is nice to have backup.

**Comment by thaJeztah** [comment]
@moxiegirl I'm quite new to Git myself, so I won't be of much help here..sorry!

**Comment by moxiegirl** [comment]
LGTM

**Pull request merged**
