### PR TITLE
contrib: builder: rpm: add Fedora 24

### LINKED ISSUE #23259: Fedora 24 yum packages
Fedora 24 is not on the `https://yum.dockerproject.org/repo/main/fedora/` repos. Subsequently trying to install docker-engine with yum is failing. Fedora 24 is currently in public beta and will be going for GA later this month.

### PR DESCRIPTION
**Pull request by runcom**
/cc @thaJeztah (following IRC conversation)

Fedora 24 image is on Docker Hub, so generate an rpm builder 

Signed-off-by: Antonio Murdaca runcom@redhat.com

closes https://github.com/docker/docker/issues/23259

### CODE REVIEW

**Comment by jfrazelle** [comment]
looks good to me

**Comment by thaJeztah** [comment]
LGTM, thanks! had it on my list to do this, so can "check" that one

I'll add this to the 1.12 milestone, since Fedora 24 will be the "current" release when we release 1.12

**Comment by vdemeester** [comment]
LGTM 🐭

**Comment by xasx** [comment]
Just for information spreading:

When is it expected to appear on the repos?

**Comment by thaJeztah** [comment]
This will be used for the next release candidate for 1.12 (no date yet)

**Comment by thaJeztah** [comment]
But note that it'll only be fore docker 1.12 and up, so not for docker 1.11

**Comment by Xerkus** [comment]
@thaJeztah i believe f24 repo should point to f23 packages for the time being as otherwise it results in frustrating experience for fedora users. 

`Failed to synchronize cache for repo 'dockerrepo', disabling.`

**Comment by thaJeztah** [comment]
@Xerkus if you use the manual installation, you can point to that repo, but we don't update the repository unless there's a patch release. Fedora 24 wasn't released when we released 1.11, so it's expected there's no package for it

**Comment by xasx** [comment]
I wonder which idea is behind the whole strategy.

Of course one wants to reduce efforts by clearly supporting new OS releases with new versions and eschew all the backporting mess.

On the other hand I am currently in the situation where I have the choice between an outdated fedora-repo docker (1.10) and an incompatible dockerrepo docker. I stick with having none since (un?)fortunately, we do not use docker in production yet. If we would, this would probably be more crucial.

**Comment by LukasBacigal** [comment]
So fedora has to wait until 1.12? 2 more weeks? I tried installing one from 23, but SELinux isnt permiting everything on clean Fedora installation, is it package problem? real inconvenience

**Comment by tiborvass** [comment]
@docker/core-maintainers Note for next time: let's make sure that when we modify release-related files, we test them before merging. You can also ping me. These are tricky sometimes.

**Comment by ksylvan** [comment]
@xasx Note that even using Fedora 23 packages on Fedora 24 will result in your docker server not starting up correctly, due to SELinux (see the discussion at https://github.com/docker/docker/issues/23981 )

**Comment by xasx** [comment]
@ksylvan That's why I don't have the
> incompatible dockerrepo docker. I stick with having none

Sorry for not having gotten into details when posting.

**Pull request merged**
