### PR TITLE
remove incorrect L3 recommendation

### LINKED ISSUE #24233: Remove the L3 constraint tip in the getting started Swarm docs
On the [Getting started with swarm mode](https://docs.docker.com/engine/swarm/swarm-tutorial/#/the-ip-address-of-the-manager-machine) page, we just need to remove `Tip: Docker recommends that every node in the cluster be on the same layer 3 (IP) subnet with all traffic permitted between nodes.` towards the bottom of the page since there is no broadcast domain constraint. Ping @thaJeztah 

Thanks!

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/docker/docker/issues/24233

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @nerdalert @mavenugo @mrjana PTAL

**Comment by nerdalert** [comment]
LGTM 👍 Tyvm!

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by thaJeztah** [comment]
Author LGTM

and ping @sfsmithcha, FYI

**Pull request merged**
