### PR TITLE
[19.03] Enable build on Dragonfly/NetBSD

### PR DESCRIPTION
**Pull request by roidelapluie**
**- What I did**

Enable build on Dragonfly/NetBSD as it is required by upcoming Swarm support in the prometheus monitoring system.

**- Description for the changelog**

Enable building the client for Dragonfly/NetBSD

**- A picture of a cute animal (not mandatory but encouraged)**

image([source](http://blog.usu.edu/behave/2014/10/20/barnyard-animal-furthers-cure-research-for-huntingtons-disease/))

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Review by tonistiigi — CHANGES_REQUESTED** [review]
This is against 19.03 . Wait for the change to be merged in master and then do a cherry-pick with -x so we can track the changes properly.

**Comment by roidelapluie** [comment]
Done @tonistiigi :)

**Review by tonistiigi — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Comment by roidelapluie** [comment]
@thaJeztah why did we miss the .12 target?

**Comment by thaJeztah** [comment]
> @thaJeztah why did we miss the .12 target?

I think the branch may already have been frozen for the .12 release at the time, and this wasn't a critical fix. 
Looks like we should be good to go now, so let me merge for .13 (no date set yet for that release)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by roidelapluie** [comment]
Thanks for merging. I have pinned Prometheus to this merged commit, so we depend on the stable branch. Very appreciated.

**Pull request merged**
