### PR TITLE
Windows: Fix windows to match linux after compile break

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com
@swernli

This PR is part of the proposal described in docker/docker issue 10662 to port the docker daemon to Windows. 

@lk4d4 This PR updates server_windows to match the change made to server_linux in #13559 which wasn't applied to the Windows variant causing Windows daemon compilation to break

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@icecrime @jfrazelle @tianon This is why we need a Windows daemon compilation verification in the build! Sooner, rather than later ;)

**Comment by jhowardmsft** [comment]
Please PR for 1.7. Thanks :)

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @jfrazelle @vieux to check if this should be in 1.7 (see https://github.com/docker/docker/pull/13609#issuecomment-106991861)

**Comment by jfrazelle** [comment]
when can we start compiling windows I can set up ci for that, can we add to hack/make.sh as a target

**Comment by jhowardmsft** [comment]
@jfrazelle Yup, I already have an unsubmitted PR waiting in the wings which will do exactly that on make cross - it will do an interim verification check that Windows builds with the daemon tag, but will still only make the client only binary at the end of it. (You can see the code change here: https://github.com/docker/docker/compare/master...Microsoft:10662-hackcross). However, the daemon won't compile on Windows quite yet as there are other PRs waiting to be merged still. Once those are in, I'm hoping we can get the compilation check PR merged ASAP to avoid future breaks.

**Comment by jfrazelle** [comment]
Ah cool super excited! You guys move super fast!! Also it's Saturday hahaha
you should stop working ;)

**Comment by jhowardmsft** [comment]
Ha, the weekend is the only time I can catch up with you guys - you move way too fast! ;)

**Comment by tianon** [comment]
Jess, the easy solution would be to modify the existing windows worker
build script to compile both in series -- I can take a look at doing that
later today if you'd like. :smile:

**Comment by icecrime** [comment]
LGTM. Not sure why the requirement for 1.7.0 though?

**Comment by jfrazelle** [comment]
i dont think we need in 1.7.0

**Comment by jhowardmsft** [comment]
Reason is I'm trying everything I can do to get the daemon to compile on Windows and match any Linux changes which break it. I think there's still 2, maybe 3 PRs outstanding before compilation will succeeds Reaching status quo and a reliable compiling Windows daemon would be a huge milestone for 1.7 IMO

**Comment by icecrime** [comment]
No question that there's value in a Windows compiling daemon, but what does having it in 1.7.0 adds to having it in master?

**Pull request merged**
