### PR TITLE
docker daemon requires windows version info while low build

### PR DESCRIPTION
**Pull request by lixiaobing1**
Specify the required version while the version not support daemon.
In addition, "windows daemon" should be "docker daemon"

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Agree over 'docker daemon', but the other change does not look good to me. Remember this is server and client, so putting 10 in there is meaningless to server users.

**Comment by lixiaobing10051267** [comment]
yes, perhaps version 10 info is no need, has been deleted :)

**Comment by jhowardmsft** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
