### PR TITLE
Label ARM issues through Poule #29644

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex <alexellis2@gmail.com>

**- What I did**

Label ARM issues in Github through poule (Gordon the turtle bot)

Reference bug #29644 

Label ARM issues with platform/arm.

**- How I did it**

Edited Pole.yml file from @icecrime 

**- How to verify it**

Run https://github.com/icecrime/poule against docker/docker (I assume this is done through web hooks which I don't have access for)

**- Description for the changelog**

Label ARM issues in Github through poule (Gordon the turtle bot)

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by alexellis** [comment]
Windows build fails with (unrelated):

> 21:55:05 Error response from daemon: write \\?\d:\temp\docker-builder029807283\.git\hooks\commit-msg.sample: There is not enough space on the disk.

@talex5 ?

**Comment by icecrime** [comment]
LGTM :+1:

**Comment by icecrime** [comment]
I really need to automate that, but in the meantime:

```bash
$ poule validate --repository-config poule.yml 
2016/12/21 14:57:51 repository configuration file is valid
```

**Review by thaJeztah — CHANGES_REQUESTED** [review]
could you squash your commits? If you need information  on how to do that; here's some information https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently

LGTM otherwise, thanks!!

**Comment by alexellis** [comment]
I didn't know how to do that.. I think it's squashed now? @thaJeztah

**Comment by alexellis** [comment]
While we're discussion this.. @icecrime is there a handler/config to try to guess what the issue is about (for common ones) and post a link to docs? I.e. about people trying to run 64-bit images on the wrong architecture?

**Comment by alexellis** [comment]
It looks like no.. I can't :-/ the squash lost the signature and fixing that with Gordon's instructions has resulted in two commits again.

**Comment by thaJeztah** [comment]
Yup, that worked! 
screen shot 2016-12-22 at 01 45 46

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Comment by AkihiroSuda** [comment]
Seems very prone to false-positive..

https://github.com/docker/docker/issues/29655#issuecomment-268771674 gets labeled as `platform/arm`, probably it contains `swarm` and `apparmor` in the text..

**Comment by AkihiroSuda** [comment]
opened https://github.com/docker/docker/pull/29656

**Pull request merged**
