### PR TITLE
Make graphdriver plugin use plugin BasePath

### PR DESCRIPTION
**Pull request by cpuguy83**
Also enables `PropagatedMount` for graphdrivers.

Verify by:

```
$ docker plugin install cpuguy83/docker-overlay2-graphdriver-plugin
# plugin is installed and enabled, restart the daemon with the new driver selected
$ pkill dockerd
$ dockerd -s cpuguy83/docker-overlay2-graphdriver-plugin
$ docker run -it --rm busybox sh
```

ping @tiborvass

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @anusha-ragunathan

**Comment by anusha-ragunathan** [comment]
Overall, the change looks good. I recommend adding integration test using `cpuguy83/docker-overlay2-graphdriver-plugin` and the verification steps outlined above.

**Comment by tiborvass** [comment]
Code LGTM. Agree would be great to have one simple test.

**Comment by cpuguy83** [comment]
+1 I'll have to make that plugin a minimal image, right now it's like 800MB because it's `FROM golang`

**Comment by tiborvass** [comment]
@cpuguy83 I see. Would you prefer to get this merged and have a follow up PR for the test?

**Comment by cpuguy83** [comment]
No worries, just added the test.
Plugin is now ~8MB

**Comment by cpuguy83** [comment]
And can't run overlay on the test host ;)

**Comment by cpuguy83** [comment]
This is ready. Note that the test is not likely to run in CI since the machine needs to support overlay.

**Comment by tiborvass** [comment]
@cpuguy83 needs rebase

**Comment by vieux** [comment]
LGTM

**Pull request merged**
