### PR TITLE
Docs: fix commandline doc create.md and run.md

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by LK4D4** [comment]
ping @moxiegirl

**Comment by thaJeztah** [comment]
changes so far look good; have you checked if the man-pages also need the same change? (sorry, typing on my phone now, otherwise I would have checked)

**Comment by hqhq** [comment]
@thaJeztah Yes man-pages need to be changed too, updated.

**Comment by moxiegirl** [comment]
LGTM Thanks @hqhq nice job. Back to @thaJeztah for the final check and merge

**Comment by thaJeztah** [comment]
LGTM! Thanks @hqhq (and all in alphabetical order; make the OCD side of me happy :smile:)!

**Pull request merged**
