### PR TITLE
Remove missed code path for api < 1.12

### PR DESCRIPTION
**Pull request by runcom**
Missed from #13160
ping @cpuguy83 

Signed-off-by: Antonio Murdaca runcom@linux.com

### CODE REVIEW

**Comment by duglin** [comment]
LGTM if janky is happy

**Comment by runcom** [comment]
@vbatts issue with this depreciation should also be discussed :/

**Comment by runcom** [comment]
Ping @icecrime

**Comment by tiborvass** [comment]
@runcom while you're at it, we should probably also do what @cpuguy83 mentioned here: https://botbot.me/freenode/docker-dev/2015-06-17/?msg=42103863&page=4

That is, error out if the API version is too low prompting to upgrade the client to use a more recent API version.

**Comment by thaJeztah** [comment]
@tiborvass sounds cleaner to do that in a separate PR (I agree with the idea though)

**Comment by runcom** [comment]
@tiborvass I'm on it then (I prefet to split the PR as @thaJeztah suggested if it's ok for everyone)

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
