### PR TITLE
Fix endpoint mode loading from Compose file in stack deploy

### LINKED ISSUE #32325: docker stack deploy ignores endpoint_mode
Hi, 

with a swarm on 
docker --version
Docker version 17.04.0-ce-rc1, build d2532c6

deploying this compose this way :
docker stack deploy consul -c docker-compose.consul.yml
 _____________________________________
version: '3.2'
services:
    consul-bootstrap:
      image: consul:0.7.5
      command:
      - consul
      - agent
      - -server
      - -bootstrap-expect=3
      - -data-dir
      - /consul/data
      - -client=0.0.0.0
      deploy:
       endpoint_mode: dnsrr

______________________________________

endpoint seems to be ignored :

docker inspect consul_consul-bootstrap
[
    {
        "ID": "vqpxdivub21tt5t34o6z9bb5g",
        "Version": {
            "Index": 15100
        },
        "CreatedAt": "2017-04-03T16:52:34.16098497Z",
        "UpdatedAt": "2017-04-03T16:52:34.169850555Z",
        "Spec": {
            "Name": "consul_consul-bootstrap",
            "Labels": {
                "com.docker.stack.namespace": "consul"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "consul:0.7.5@sha256:7fa3365242fca70d63e8e9737f4f1ac8687987d04bbdb7287bc80ea813e624ca",
                    "Labels": {
                        "com.docker.stack.namespace": "consul"
                    },
                    "Args": [
                        "consul",
                        "agent",
                        "-server",
                        "-bootstrap-expect=3",
                        "-data-dir",
                        "/consul/data",
                        "-client=0.0.0.0"
                    ]
                },
                "Resources": {},
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "Networks": [
                {
                    "Target": "v9ktszmecl76c3tqnr3gw9pbr",
                    "Aliases": [
                        "consul-bootstrap"
                    ]
                }
            ],
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip"
            },
            "VirtualIPs": [
                {
                    "NetworkID": "v9ktszmecl76c3tqnr3gw9pbr",
                    "Addr": "10.0.4.2/24"
                }
            ]
        }
    }
]

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #32325

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
@dnephin will go in 17.05

**Review by boaz0 — APPROVED** [review]
LGTM 👍

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Comment by thaJeztah** [comment]
relates to https://github.com/docker/docker/pull/31795

**Pull request merged**
