### PR TITLE
Added entries of a few ancient Indian mathematicians who did cool things centuries ago.

### PR DESCRIPTION
**Pull request by rghv**
[Aryabhata](https://en.wikipedia.org/wiki/Aryabhata) - Ancient Indian mathematician-astronomer during 476-550 CE.
[Bhaskara II](https://en.wikipedia.org/wiki/Bh%C4%81skara_II#Calculus) - Ancient Indian mathematician-astronomer whose work on calculus predates Newton and Leibniz by over half a millenium.
[Brahmagupta](https://en.wikipedia.org/wiki/Brahmagupta#Zero) - Ancient Indian mathematician during 598-670 CE who gave rules to compute with zero.
[Mahavira](https://en.wikipedia.org/wiki/Mah%C4%81v%C4%ABra_%28mathematician%29) - Ancient Indian mathematician during 9th century AD who discovered basic algebraic identities.
[Panini](https://en.wikipedia.org/wiki/P%C4%81%E1%B9%87ini#Comparison_with_modern_formal_systems) - Ancient Indian linguist and grammarian from 4th century CE who worked on the world's first formal system.
[Varahamihira](https://en.wikipedia.org/wiki/Var%C4%81hamihira#Contributions) - Ancient Indian mathematician who discovered trigonometric formulae during 505-587 CE.

_Tests run and checked that there are no failures._

```
$ go test -v  pkg/namesgenerator/names-generator.go  pkg/namesgenerator/names-generator_test.go 
=== RUN TestGenerateAwesomeNames
--- PASS: TestGenerateAwesomeNames (0.00s)
PASS
ok      command-line-arguments  0.002s
```

Not sure if there is any other criteria based on which the names are listed. Please let me know if there's any change necessary.

### CODE REVIEW

**Comment by rghv** [comment]
[janky — Jenkins build Docker-PRs 10307 has failed](https://jenkins.dockerproject.org/job/Docker-PRs/10307/console) mentions the failure as below

```
.....................................................EEEEEEEE....
======================================================================
ERROR: runTest (__main__.TestStartContainerWithDictInsteadOfId)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/docker-py/tests/integration_test.py", line 65, in tearDown
    self.client.remove_container(container)
  File "/docker-py/docker/client.py", line 786, in remove_container
    params=params)
  File "/docker-py/docker/client.py", line 85, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 526, in delete
    return self.request('DELETE', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
    raise Timeout(e)
Timeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=5)
```

Do I need to add a dummy commit to trigger these tests once more?

**Comment by calavera** [comment]
LGTM

**Comment by rghv** [comment]
So, anymore :+1:s or :-1:s?

**Comment by thaJeztah** [comment]
LGTM

ping @cpuguy83 for merge and docker-who ;-) (or do you prefer a PR?)

**Comment by rghv** [comment]
@cpuguy83 : pull request https://github.com/cpuguy83/docker-who/pull/1/files on https://github.com/cpuguy83/docker-who raised as well. 

Thanks @thaJeztah

**Comment by crosbymichael** [comment]
LGTM

**Comment by rghv** [comment]
thanks @crosbymichael

**Comment by clnperez** [comment]
Glad to see some new names (and learn something). :+1:

**Pull request merged**
