### PR TITLE
There should be English punctuations

### PR DESCRIPTION
**Pull request by wxb0521**
**- What I did**
change Chinese punctuations to English punctuations

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Backquote would be even better.
Also, please backquote `precpu_stats` as well?

**Comment by wxb0521** [comment]
I agree with your suggestion. Backquote is better. And I backquote `precpu_stats`.

**Comment by wxb0521** [comment]
All the requests have been modified. @AkihiroSuda

**Comment by AkihiroSuda** [comment]
Please update the commit message as well (`git commit -a --amend`), and please use the real name for signing?

**Comment by wxb0521** [comment]
I submit a new PR and sign real name #29637 . So I close this PR. @AkihiroSuda Thank you!

**Comment by thaJeztah** [comment]
@wxb0521 in future, please update your existing PR instead of opening a new one; you can amend your commit and do a force-push to update the pull request

Also some information on rebasing; https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently

**Comment by wxb0521** [comment]
Thank you very much! And I will do it correctly in future.

**Pull request closed without merging**
