### PR TITLE
Vendor swarmkit 8f053c2

### LINKED ISSUE #32916: On a single-node Swarm traffic ingress doesn't work, regression between v17.05.0-ce-rc1 and v17.05.0-rc2 for CentOS
**Description**

After I've updated from v17.05.0-ce-rc1 to v17.05.0-ce-rc2 my front-end reverse proxy became unavailable.

**Steps to reproduce the issue:**
1. install v17.05.0-ce-rc1
2. `docker stack up` my stack with a single 443 port published
3. check application availability, look at iptables:
```
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-INGRESS
-N DOCKER-ISOLATION
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 2376 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j DOCKER-INGRESS
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A DOCKER-INGRESS -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER-INGRESS -p tcp -m state --state RELATED,ESTABLISHED -m tcp --sport 443 -j ACCEPT
-A DOCKER-INGRESS -j RETURN
-A DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP
-A DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -j RETURN
```
4. (optional) tear down the stack
5. upgrade to v17.05.0-ce-rc2
6. (optional) if the stack has been torn down, re-deploy
7. look at iptables

**Describe the results you received:**
No ingress chain, therefore application is inaccessible
```$ sudo iptables --list-rules
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 2376 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP
-A DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -j RETURN
```

**Describe the results you expected:**
iptables are the same as before upgrade
My application is accessible

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc2
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   c57fdb2
 Built:        Thu Apr 27 03:18:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc2
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c57fdb2
 Built:        Thu Apr 27 03:18:37 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 75
Server Version: 17.05.0-ce-rc2
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ybq9xmfvtuw7e935bav9c5v72
 Is Manager: true
 ClusterID: tv5ojno8vnr3vx56g0wkyj0e7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 3
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.23.251.217
 Manager Addresses:
  172.23.251.217:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.798GiB
Name: estelle-maersk.sm.sw.ru
ID: UFC4:F3BH:CRZS:RMZ4:S3WC:3PRC:WJDP:KZSK:PHMQ:24UR:EXZL:FEKL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V Gen.2 on Windows 10

### LINKED ISSUE #32918: Accessing published service ports does not work with 17.05.0-ce-rc2
**Description**

I'm building a Vagrant test environment for a [mixed Linux and Windows Docker swarm](https://github.com/StefanScherer/docker-windows-box/tree/master/swarm-mode). After running it successfully today morning I normally do a `vagrant destroy -f` and rebuild it if it still works out of the box. Luckily with this habit I found a problem with the new release candidate 17.05.0-ce-rc2 as it worked with the rc1.

I then stripped it down to a single node swarm to try to reproduce it without the relatively new Windows overlay network involved.

**Steps to reproduce the issue:**
1. `vagrant up sw-lin-01`
2. `vagrant ssh sw-lin-01`
3. `docker service create --name=whoami -p 8000:8000 -e PORT=8000 stefanscherer/whoami:1.2.0`
4. Try to access the whoami service from host to the fixed IP address of the manager node with `open http://192.168.36.2:8000`
5. Try to open the visualizer that is running on port 8080 also does not work.

**Describe the results you received:**

```
$ curl http://192.168.36.2:8000
curl: (7) Failed to connect to 192.168.36.2 port 8000: Connection refused
```

**Describe the results you expected:**

```
$ curl http://192.168.36.2:8000
I'm ed8755e92c67 running on linux/amd64
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I can reproduce the problem with `vagrant destroy -f && vagrant up sw-lin-01`. I currently have a workaround in my provision script by downgrading the latest release candidate rc2 back to rc1:

```bash
#!/bin/bash
curl https://test.docker.com | sh
sudo apt-get install -y --allow-downgrades docker-engine=17.05.0~ce~rc1-0~ubuntu-xenial
sudo usermod -aG docker vagrant
```

With rc1 I can access the service from the host and as well setup the Linux / Windows swarm (there are other issues on Windows I want to look at as well). Manually downgrading after I have started the service I have to do this:

```
vagrant ssh sw-lin-01
sudo apt-get install -y --allow-downgrades docker-engine=17.05.0~ce~rc1-0~ubuntu-xenial
docker service rm whoami
docker service create --name=whoami -p 8000:8000 -e PORT=8000 stefanscherer/whoami:1.2.0
```

Then I can access the new created service from the host. A `docker service scale whoami=0` and `docker service scale whoami=1` is not enough after the downgrade.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce-rc2
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   c57fdb2a14cfba584686ddad909e3006284d10aa
 Built:        Wed Apr 26 23:00:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc2
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c57fdb2a14cfba584686ddad909e3006284d10aa
 Built:        Wed Apr 26 23:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.05.0-ce-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 2q9stf5gsi4szvlbrl0tlo8ex
 Is Manager: true
 ClusterID: wezryia21a96k30cs75s3a2m4
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.36.2
 Manager Addresses:
  192.168.36.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: sw-lin-01
ID: C3FR:Q6Z4:BZIS:4PQQ:AZVD:QEA5:YEJX:YSMT:NNXC:YUVD:YPHP:LWHD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware Fusion Pro 8.5.6, Vagrant 1.9.2, Vagrant box `boxcutter/ubuntu1604` (vmware_desktop, 2.0.26) with Ubuntu 16.04.1

### PR DESCRIPTION
**Pull request by aaronlehmann**
This is to keep master up to date with the fix going into 17.05: #32848

There is also a change to Raft that will cause the leader to give up its leadership if the swarm loses quorum. This was supposed to be already be the case since September, but there was a bug preventing it from worker. This should cause more consistent behavior - for example read-only swarm commands like `docker node ls` won't sometimes work in a swarm that does not have quorum. However, it may expose incorrect assumptions in tests, so keep an eye out.

Fixes #32916
Fixes #32918

### CODE REVIEW

**Comment by aaronlehmann** [comment]
The powerpc failure was real. I'm either going to address this upstream in `etcd/raft` or relax the test.

**Comment by aaronlehmann** [comment]
I've updated this to include a fix in etcd using a temporary fork. The PR has been submitted upstream. See https://github.com/docker/swarmkit/pull/2158

**Comment by thaJeztah** [comment]
ping @dongluochen @aluzzardi PTAL

**Comment by dongluochen** [comment]
looks good to me

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by thaJeztah — APPROVED** [review]
thanks for reviewing, LGTM

**Comment by thaJeztah** [comment]
PowerPC looks to fail on a test that's known to be flaky

```

**Pull request merged**
