### PR TITLE
New implementation of /run support

### PR DESCRIPTION
**Pull request by rhatdan**
```
This mounts a /run tmpfs into the container, with the initial contents
copies from the /run in the base image, unless NoRunFs is set in the
HostConfig.

Additionally NoRunFs is always set during a docker build, which means
any setup of /run in a Dockerfile is saved in the image to be copied
into the final /run tmpfs when a container is started.

Docker-DCO-1.1-Signed-off-by: Alexander Larsson <alexl@redhat.com> (github: alexlarsson)
```

Docker-DCO-1.1-Signed-off-by: Dan Walsh dwalsh@redhat.com (github: rhatdan)

Docker-DCO-1.1-Signed-off-by: Dan Walsh dwalsh@redhat.com (github: rhatdan)

### CODE REVIEW

**Comment by icecrime** [comment]
*Review session with @tiborvass @unclejack @crosbymichael*

@rhatdan Can you please explain why `--tmpfs /run` (as implemented by #9586) isn't sufficient? It seems that populating the content of `/run` could be achieved through a container entrypoint script.

**Comment by rhatdan** [comment]
/run on TMPFS is a standard.  Is there a distribution where this is not true.  

How do I see what is under the /run or the /tmp if something is mounted over them?

Forcing everyone that uses applications that expect /run to be tmpfs to satisfy this seems ass backwards.  We want to ship systemd based images, which expects /run to be on tmpfs by default as is the standard.

Lets not make running docker containers harder and more fragile by not accepting this patch.  At least allow us to customize the daemon to make this the default behaviour.   I see no reason to require /run to not be a tmpfs.

**Comment by crosbymichael** [comment]
@rhatdan If you are using systemd images, shouldn't the setup scripts populate `/run` for the daemons that you are executing?

**Comment by rhatdan** [comment]
I want to allow users to do a Dockerfile that does the following

FROM rhel7
RUN yum install httpd; systemctl enable httpd
CMD /sbin/init

This will run the httpd service the way it was designed, no special hacking of init scripts, as simple as can be.  You just install the service the way you would on bare metal and use its service script to manage it.

**Comment by rhatdan** [comment]
In this case systemd will populate the tmpfs if you run with the --tmpfs /run, but will blow up if the user forgets the command.
Systemd-tmpfiles will take care of populating /run

In other cases people using --tmpfs /run will blow up apps since there is no way to prepopulate /run and certain images expect it.  Having /run as the default, or allowing users to configure it to be default, solves all problems.

**Comment by rhatdan** [comment]
I would actually like to know what having /run as tmpfs actually breaks, considering the patch copies the contents of /run off the image.

**Comment by crosbymichael** [comment]
It would not break anything with the copy but I'm not a fan of the mount outside of the containers mount namespace and libcontainer is not the place to be copying files.  

I don't think it's too much to ask a user to add `--tmpfs /run` in order to run an advanced piece of software like systemd in their container.  For httpd they are still going to have to map ports or the like. 

Maybe we can make the argument that `TMPFS /run` should be allowed in the Dockerfile because it is portable and not machine specific.

**Comment by cgwalters** [comment]
WRT /var/run and read-only - for what it's worth, modern ostree will automatically make all of /var a tmpfs if / is readonly.  See https://git.gnome.org/browse/ostree/commit/?id=ff6883ca0655ac8844cd783caf6a7d8815515ba3

I think it's a pretty good default, as if you boot a read-only image, you wouldn't expect persistence, but it's nice if the system does boot out of the box.

**Comment by crosbymichael** [comment]
I'm not disagreeing that `/run` should not be in tmpfs by default, the problem is that for docker's entire lifetime it's not and so changing that now is a little harder.  Copy is the solution to that problem but it comes at a cost of performance and complexity

**Comment by rhatdan** [comment]
httpd was just an example.  Any system service provided by the distribution would work.  Is there another way we could copy the files off of /run to preserve it.  Your new patch is going to have the same problem,  If we had a standard way of preserving the underlying image content on top of the tmpfs, we could solve the problem.

**Comment by rhatdan** [comment]
TMPFS in dockerfile has the same problem

FROM rhel7
TMPFS /run
RUN touch /run/dan

Would not work.

**Comment by rhatdan** [comment]
I have no problem making /run-tmpfs optional as a daemon option.  Which should satisfy the people who expect /run not to be a tmpfs, we would choose to ship our docker daemon with --runtmpfs enabled.

**Comment by crosbymichael** [comment]
In your dockerfile example I would expect that to work because the user explicitly set to mount /run in tmpfs so it's their bug, not ours.  

Do you think a daemon option would be better than a Dockerfile instruction?

**Comment by SvenDowideit** [comment]
@rhatdan did you want to get this into docker? it needs documentation, including some information telling users when and why they would choose (or not)

**Comment by rhatdan** [comment]
Sure.  I am waiting for @crosbymichael to comment on patch I sent to libcontainer, to handle copying directory contents from the image to the tmpfs file system that is being mounted over it.

https://github.com/docker/libcontainer/pull/331

**Comment by LK4D4** [comment]
@crosbymichael @rhatdan Patch for libcontainer wasn't accepted. Should we just close this too and find consensus first?

**Comment by rhatdan** [comment]
I fixed up the calls to libcontainer to remove any archive use from it.  Patch submitted for libcontainer.

https://github.com/docker/libcontainer/pull/495

**Comment by rhatdan** [comment]
@crosbymichael We now pass down the tar/untar commands to libcontainer from docker.

**Comment by rhatdan** [comment]
@LK4D4 Reworked to hopefully match @crosbymichael requirements.

**Comment by LK4D4** [comment]
@crosbymichael Can I have your attention here?

**Comment by thaJeztah** [comment]
@rhatdan you forgot to sign of your last commit

**Comment by ibuildthecloud** [comment]
Something seems a bit off to me.  In general I don't like to assume anything about what is running in the container.  The default mounts that docker sets up today are all /proc and /sys, IIRC, and those are essential to linux.  Are we saying that /run as tmpfs is just absolutely fundamental to the behavior of Linux?  I don't know @crosbymichael latest opinion, but --tmpfs /run seems a bit more reasonable to me.

As a side question, is something broken if /run isn't a tmpfs?  Is there a basic assumption somewhere that /run must be ephemeral?

**Comment by rhatdan** [comment]
On 04/20/2015 01:30 PM, Darren Shepherd wrote:
>
> Something seems a bit off to me. In general I don't like to assume
> anything about what is running in the container. The default mounts
> that docker sets up today are all /proc and /sys, IIRC, and those are
> essential to linux. Are we saying that /run as tmpfs is just
> absolutely fundamental to the behavior of Linux? I don't know
> @crosbymichael <https://github.com/crosbymichael> latest opinion, but
> --tmpfs /run seems a bit more reasonable to me.
>
> As a side question, is something broken if /run isn't a tmpfs? Is
> there a basic assumption somewhere that /run must be ephemeral?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/8478#issuecomment-94516426>.
>
How come I don't see this on github?  The biggest problem we have with
/run not being on a tmpfs is that systemd will not run without
it on a tmpfs, actually it will but it will attempt to mount /run as a
tmpfs and will blow up. 

Secondly, I want to get both /run and /tmp as tmpfs by default so that
it is simple to do a

docker run --read-only fedora /bin/sh

And most apps will run.  Apps expect to be able write to /tmp and /run.

/run is a tmpfs on every modern Linux Distribution and /tmp is also on
most.  Having these be the same in containers makes sense.

**Comment by thaJeztah** [comment]
> How come I don't see this on github?

Interesting question, I just trashed the email, luckily you noticed it

**Comment by ibuildthecloud** [comment]
@rhatdan after reading over the thread, i deleted my comment, I didn't think it was valid.  I just struggle with how much we are assuming about the target env.  There's probably not a big harm in doing /run and /tmp but then I've seen other PR that talk about putting things in /etc and /var/run.  Where do we draw the line?  We draw this fine line between what systemd requires and what is "standard" in Linux because what major distro isn't influenced by systemd now.  Wasn't the notion of /run really introduced by systemd to begin with?  Not really important...

I feel the image should be able to specify this requirement and we shouldn't make this global.  So the TMPFS dockerfile command seem much more the right way to go.

If somebody used `TMPFS /run` then they are deciding to make /run ephemeral and then there is no need to prepopulate /run, right?  I'm in favor of making this a Dockerfile command and adding --tmpfs to `docker run`.  Then we could back out the change in libcontainer.

**Comment by rhatdan** [comment]
/var/run and /run are basically the same thing.  On modern systems /var/run is a symlink to /run.  I believe Ubuntu was the first to standardize on /run as a tmpfs and Fedora/systemd followed.

I actually like the idea of specifying in the base image or individual images where the TMPFS directories are.  So I have no problem moving to this model, but you still need to be able to store files/directories in the underlying directory and copying it into the TMPFS.

For example apache expects their to be a /run/httpd directory and will not work without it.  Putting this in the base image and allowing libcontainer/docker to preserve it onto the tmpfs is necessary.

> Where do we draw the line? 

I draw the line at matching what standard distros define.  /run and /tmp as tmpfs.  But if we go with putting it in the base images, I can go along with that.  The goal with /tmp is for --read-only, otherwise not that important.

> We draw this fine line between what systemd requires and what is "standard" in Linux because what major distro isn't influenced by systemd now. 

Not sure the answer to this question.  But trust me I am trying hard to get systemd to change some of its decisions.  Some times I feel like I am between a rock (systemd) and a hard place (docker).  :^)

> Wasn't the notion of /run really introduced by systemd to begin with? 

No I think it pre-existed systemd.


> If somebody used TMPFS /run then they are deciding to make /run ephemeral and then there is no need to prepopulate /run, right? I'm in favor of making this a Dockerfile command and adding --tmpfs to docker run.   

I would prefer a syntax like -v tmpfs:/tmp or -v /tmp:T

> Then we could back out the change in libcontainer.

No we need the Premount/Postmount behaviour in libcontainer to be able to get the content off of the image into the tmpfs.

I could see use cases where I would want to run different containers with different /etc/httpd or /var

docker run --read-only -v tmpfs:/var httpd 

Where httpd would be mounted as a tmpfs but the contents off of the image would be copied into it.

**Comment by ibuildthecloud** [comment]
@rhatdan How does httpd work on a normal Linux distro if /run is empty.  Prepopulating a tmpfs seems a bit dirty to me because I can't really find an analogy to a typical linux distro.  If I create a tmpfs mount then the folder is empty and if I want to populate it I must write script that runs on startup, or use systemd-tmpfiles(?).

Your use case of `docker run --read-only -v tmpfs:/var httpd ` while compelling and cool, is like a poor man's COW.  I'd personally opt to not support prepopulating a tmpfs.

The red flag to me is that when I see the libcontainer changes the hacker in me gets excited because you just gave me the ability to run arbitrary commands through libcontainer.  This is a blocking hook that I could abuse like crazy (granted it's not exposed through Docker, but don't worry I'll get creative :) )  I prefer a bit more of a focused implementation in libcontainer to support prepopulating a tmpfs, but then I can't think of a clean design.

I think Docker should be as opinionated about user space as Linux is.  This means while every major distro supports /run tmpfs, it is still just a defacto standard among distros and init systems.  But Docker should support the ability to do such a thing because if you are running a Ubuntu or Fedora based image you would expect /run to be tmpfs.  This reinforces in my mind that the right approach is to support it in the image.

I'd prefer `TMPFS/--tmpfs` over `-v`.  The reason being that if it's a volume then the Dockerfile would have to be something like `VOLUME tmpfs://:/run`.  That sort of breaks the design of VOLUME in Dockerfiles because current VOLUME does not allow specifying the left side of `:` (well you're not supposed to).  We would have to make an exception for `tmpfs://` which seems hacky.

**Comment by tianon** [comment]
> How does httpd work on a normal Linux distro if /run is empty.

Because it has an init script that does the `mkdir` (or the equivalent configuration for systemd).

In Docker, the Dockerfile is as close to an "init script" as we have, save entrypoint workarounds.

**Comment by rhatdan** [comment]
Content in /run is populated via the init script or systemd-tmpfiles.

We have gone back and forth on the PreMount/PostMount command, this is what the upstream wanted so we gave it to them.  Previous patches had the "tar" happening on the libcontainer side.

I think having premount/postmount could be handy for other functions like notifications of mounts.  Not looking at this from a Malicious point of view.  I guess if you think of libcontainer as a priv separation point of view, where libcontianer would have more privs then the caller, the execution of these commands could be risky.  But I don't believe that is the way it is used currently.

**Comment by calavera** [comment]
I agree with @crosbymichael that we should look for a more general solution here. I see the benefit of allowing to mount tmpfs directories and I understand that systemd requires /run to be mounted that way.

I don't think making this specific to /run is the way to go, though. A more general solution like Mike proposes with `--tmpfs` allows to fulfill systemd's requirements and is not coupled to it at the same time. Besides, this is a hard linux implementation, using --tmpfs would allow us to abstract the implementation by OS. Windows is coming.

So, I'm :+1: on allowing to mount tmpfs directories and I'll be glad to push it forward with a general solution.

**Comment by rhatdan** [comment]
Well I am now thinking of moving the systemd requirements into a different patch set and adding a --systemd switch.  There are lots of requirements that systemd and docker do not agree with, and I don't see getting either upstream to agree.  Therefore I think we need docker run to support --systemd flag which would tell it that the container will run with a systemd as an init program and set up the container correctly.
Then container that do not want to run in systemd mode can continue to run as they currently do.  Only problem with doing this would be users confusion in running systemd based containers failing because they forget to run with the --systemd flag.

**Comment by calavera** [comment]
@rhatdan docker already knows how to detect that systemd is running via libcontainer, see https://github.com/docker/docker/blob/53bef64804c6dae6662a7d55c3bb3e48b3e5dfdf/daemon/execdriver/native/driver.go#L62 for instance.

If we add `--tmpfs` as a flag, there is nothing stopping us to set `--tmpfs /run` by default when systemd is running. That way we get both, a generic implementation and a systemd sane default.

**Comment by rhatdan** [comment]
It can tell if systemd is running on the host ,but not if it will be running as PID 1 in the container.  systemd expects things like the SIGTERM to have different meaning then what docker expects.  It expects to have /run and /sys/fs/cgroup mounted in the container,  I want it to be able to write journal data to the host OS.  There are a few other features that are also required to fully support systemd as pid1 in a container.

**Comment by LK4D4** [comment]
Implementation makes sense for me. But tests failing hard.
Also this doing this by default, so I moving to design-review.
ping @docker/core-maintainers

**Comment by duglin** [comment]
Just coming up to speed on this issue, but I'm not following something. Based on what I've read so far (in this PR and http://thread.gmane.org/gmane.linux.redhat.fedora.devel/146976) it appears that `/run` mounted as `tmpfs` is standard, right? If so, why wouldn't Docker do the same thing by default? Why would we want to require people to add a flag to enable something that would be enabled by default if they were running natively, outside of Docker?  

Also, if we did end up with a flag, I'm not in favor of one on the daemon because if we think some people may not always want it then I'd prefer for it to be on a per-container basis. Or at least allow it for both so that a container can override what the daemon's default is.

**Comment by rhatdan** [comment]
After playing and shipping this patch for a while.  We are seeing other problems with it.  Biggest one being docker commit does not work the way one would expect.  docker commit only saves the underlying image, not anything mounted on top of the container image.  This means someone doing a 

docker run -ti -n myhttpd image /bin/sh; yum install httpd; mkdir /run/httpd; ^d
docker commit myhttpd httpd

Would not end up getting /run/httpd by default.

I am now thinking the best way to handle this is just to have a big --systemd flag.

docker run --systemd ...

Which would set the container up in the mode that systemd would expect and would mount /run and /sys/fc/cgroup the way systemd would want, as well as generate journald content on the host and send the proper signals to systemd when users do a docker stop ID.

But for rank and file containers, we leave /run on the image.

**Comment by alberts** [comment]
We've been running systemd in Docker in production for a few months and it mostly works and has helped us do many things where multiple Dockers wouldn't have made sense. Big +1 on --systemd. We still need --tmpfs to be able to use --read-only more widely, without breaking apps that need small scratch directories where -v or VOLUME would be overkill (or having the scratch disk on physical disk would be bad for performance).

**Comment by rhatdan** [comment]
I agree I like the idea of --tmpfs although I think -v tmpfs:/PATH would be more consistent.  If docker upstream would decide which to do, I could have a patch available in a couple of hours.

I will push to get --systemd pull request together by next week.

**Comment by rhatdan** [comment]
But remember with --systemd or --tmpfs, we need to document that docker commit will not save any content that is stored on tmpfs, or for that matter any volume mounted content onto the new image, which might surprise some users.

**Comment by rhatdan** [comment]
Closing this and replacing it with 

https://github.com/docker/docker/pull/13525

**Pull request closed without merging**
