### PR TITLE
If docker search with --starts=${negative number}, it would show the war...

### PR DESCRIPTION
**Pull request by sunyuan3**
...ning information.

Signed-off-by: Yuan Sun sunyuan3@huawei.com

### CODE REVIEW

**Comment by duglin** [comment]
Can you please add a testcase for this?

**Comment by sunyuan3** [comment]
Yes. In this PR or another PR for the testcase?

**Comment by duglin** [comment]
in this same PR/commit - then it can all go in at the same time.

**Comment by sunyuan3** [comment]
The testcase has been added. Please merge.

**Comment by icecrime** [comment]
@sunyuan3 Hello! Yes, there are good chances that your patch will be merged, but [our process](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#merge-approval) requires two core maintainers to approve it by reviewing, testing, and ultimately commenting "LGTM". Please be patient ;-)

**Comment by icecrime** [comment]
LGTM

**Comment by duglin** [comment]
thanks for the testcase. LGTM

**Comment by sunyuan3** [comment]
Ok. I understand. Thank you.;-)

**Pull request merged**
