### PR TITLE
Add myself as a curator

### PR DESCRIPTION
**Pull request by SamWhited**
Ping @thaJeztah

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@SamWhited can you add yourself under the "people" section as well? https://github.com/moby/moby/blob/3aba865/MAINTAINERS#L440-L443

**Comment by SamWhited** [comment]
@thaJeztah done, thanks.

**Review by thaJeztah — APPROVED** [review]
LGTM

ci doesn't test this, so merging

**Comment by SamWhited** [comment]
> ci doesn't test this, so merging

YOLO

**Pull request merged**
