### PR TITLE
Vendoring Libnetwork caf22bd9a6a53dfe91b0266274155bc69235e8ed

### LINKED ISSUE #23622: [1.12.0-RC1] default bridge network sometimes does not exist
Many reports in rc1 of seeing messages like:
```
docker: Error response from daemon: failed to create endpoint big_euler on network bridge: network 6faafb12e255d59a4c6a26396e01444caf8cb7668630aacb40144039ef3f94e7 does not exist.
```

Restarting the daemon does not work:
```
time="2016-06-16T00:46:14.268698114Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: cannot create network 819b4edbda5b06a7bd5f80c5898524f0953340f25838d3e47ffc10dd96490353 (docker0): conflicts with network 5fb1c1fb93bca5f8b558b090f1bcb0190372034d7c109bad4339e76da7dfb331 (docker0): networks have same bridge name"
```

@aboch is looking into it

### LINKED ISSUE #23630: Bug: docker daemon failing to start
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   6253c29
 Built:        Thu Jun 16 12:29:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   6253c29
 Built:        Thu Jun 16 12:29:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121929-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 271.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 757.8 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start the docker daemon (dockerd)
2.
3.

**Describe the results you received:**
Starting docker daemon give me this error message:
 FATA[0001] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: cannot create network c66222aba32575ef83c41187d5980d2f48129c37592915051cfd7b4611353e44 (docker0): conflicts with network a9d637c2a4994c3e19082046092910ba75a3700ce17f05cbc10f6141f565d066 (docker0): networks have same bridge name 

**Describe the results you expected:**
Docker daemon should start successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by mavenugo**
- fixes https://github.com/docker/docker/issues/23622
- fixes #23630
- fixes a memory leak issue with bulk sync
- fixes external DNS resolution issue after live restore

Signed-off-by: Madhu Venugopal madhu@docker.com

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Comment by vieux** [comment]
SGTM

**Comment by icecrime** [comment]
Weeeeeee LGTM

**Comment by justincormack** [comment]
LGTM

**Comment by justincormack** [comment]
fixes https://github.com/docker/docker/issues/23630 and https://github.com/docker/docker/issues/23622 (same issue)

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
