### PR TITLE
libnetwork: refactor networkdb test implementation

### PR DESCRIPTION
**Pull request by corhere**
- Follow-up to #42829 

cc: @zq-david-wang 

**- What I did**
DRY'ed the polling checks in TestNetworkDBNodeJoinLeaveIteration.

**- How I did it**
Higher-order functions.

**- How to verify it**
Visual inspection of equivalence to the prior code.

**- Description for the changelog**
N/A

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by zq-david-wang** [comment]
I am not sure, but if somehow a failure reported, would the test report log the line indicating which test step failed or just refer to the line within the function enclosure where poll called?

**Comment by thaJeztah** [comment]
> I run with expected value changed, the test only report the line within the enclosure, this may not be good for debug.

could we mark those helper functions as `t.Helper()` ?

**Comment by corhere** [comment]
`t.Helper()` does the trick:
```console
root@fbf8cd893314:/go/src/github.com/docker/docker# go test -run TestNetworkDBNodeJoinLeaveIteration ./libnetwork/networkdb/
--- FAIL: TestNetworkDBNodeJoinLeaveIteration (3.81s)
    networkdb_test.go:510: timeout hit after 3s: current number of nodes is 1, expect 42.
FAIL
FAIL	github.com/docker/docker/libnetwork/networkdb	3.820s
FAIL
```

**Comment by zq-david-wang** [comment]
> `t.Helper()` does the trick:
> 
> ```
> root@fbf8cd893314:/go/src/github.com/docker/docker# go test -run TestNetworkDBNodeJoinLeaveIteration ./libnetwork/networkdb/
> --- FAIL: TestNetworkDBNodeJoinLeaveIteration (3.81s)
>     networkdb_test.go:510: timeout hit after 3s: current number of nodes is 1, expect 42.
> FAIL
> FAIL	github.com/docker/docker/libnetwork/networkdb	3.820s
> FAIL
> ```

cool trick~

**Comment by corhere** [comment]
@thaJeztah PTAL

**Review by tianon — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
