### PR TITLE
volume/local: Fix CIFS urls with spaces, add tests

### PR DESCRIPTION
**Pull request by vvoland**
- follow up to: https://github.com/moby/moby/pull/47193
- relates to: https://github.com/docker/cli/issues/4816#issuecomment-1905935618
- supersedes / closes https://github.com/moby/moby/pull/47193

**- What I did**
Fixed spaces in CIFS address being escaped
Added tests

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vvoland** [comment]
Might want to just merge this one instead of https://github.com/moby/moby/pull/47193 (it's included in this PR).

**Comment by thaJeztah** [comment]
Yeah, I'd be fine with closing the other one.

**Comment by thaJeztah** [comment]
These buildkit tests are very flaky recently;

```
=== FAIL: client TestIntegration (5.59s)
time="2024-01-23T16:52:50Z" level=info msg="trying next host - response was http.StatusNotFound" host="localhost:36285"
    run.go:266: copied docker.io/amd64/alpine:latest@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70 to local mirror localhost:36285/library/alpine:latest
time="2024-01-23T16:52:50Z" level=info msg="trying next host - response was http.StatusNotFound" host="localhost:36285"
    run.go:266: copied docker.io/tonistiigi/test:nolayers to local mirror localhost:36285/tonistiigi/test:nolayers
time="2024-01-23T16:52:51Z" level=info msg="trying next host - response was http.StatusNotFound" host="localhost:36285"
time="2024-01-23T16:52:51Z" level=info msg=request digest="sha256:be691b1535726014cdf3b715ff39361b19e121ca34498a9ceea61ad776b9c215" mediatype=application/vnd.docker.image.rootfs.foreign.diff.tar size=10240 url="https://gist.github.com/cpuguy83/fcf3041e5d8fb1bb5c340915aabeebe0/raw/eebc59ee14939fc38067aa8b8dfbfba053d0af94/base.tar"
    run.go:266: copied docker.io/cpuguy83/buildkit-foreign:latest to local mirror localhost:36285/cpuguy83/buildkit-foreign:latest
```

**Review by rumpl — APPROVED** [review]

**Review by laurazard — APPROVED** [review]
LGTM

**Comment by vvoland** [comment]
Thanks! I'll go ahead and merge it.

**Pull request merged**
