### PR TITLE
Windows: Cleanup HCS on restore

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

@darrenstahlmsft 

This ensures that any compute processes in HCS are cleanedup
during daemon restore. Note Windows cannot (currently) reconnect
to containers on restore.

@friism @vieux Another one which should be considered for CS and servicing.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@johnstep PTAL

**Review by johnstep — APPROVED** [review]
LGTM

**Comment by darrenstahlmsft** [comment]
LGTM

**Comment by jhowardmsft** [comment]
@thaJeztah @vdemeester PTAL.

**Comment by jhowardmsft** [comment]
@thaJeztah Good to merge?

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
cherry-picked in https://github.com/docker/docker/pull/31754

**Pull request merged**
