### PR TITLE
fixed special character

### PR DESCRIPTION
**Pull request by sjeeva**
`scope`=<string> local or swarm had special character, which was breaking the Swagger UI

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @sjeeva - can you sign off your commit? Otherwise CI won't pass 😅

**Comment by AkihiroSuda** [comment]
LGTM except DCO

**Comment by sjeeva** [comment]
commit amended as suggested

**Comment by AkihiroSuda** [comment]
please use your real name for signing?

**Comment by sjeeva** [comment]
Using real name

**Review by AkihiroSuda — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

😂

**Review by thaJeztah — APPROVED** [review]
All green now, LGTM
thanks!!

**Pull request merged**
