### PR TITLE
Add comments to api/common constants

### LINKED ISSUE #11583: Document constants in api/common.go
**Problem**
 
Document constants in api/common.go
 
**Solution**
 
Short explanation why we need them here(used both by daemon and client) and short inline comment for each. Example: http://golang.org/src/math/const.go#L8

### PR DESCRIPTION
**Pull request by avidas**
Closes #11583

Signed-off-by: Avi Das andas222@gmail.com

### CODE REVIEW

**Comment by duglin** [comment]
You'll need to run your code changes through gofmt - that's why the test failed.  In the logs you'll see this:
```
These files are not properly gofmt'd:
 - api/common.go

Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by estesp** [comment]
@avidas I guided you wrong! :) `gofmt` was a necessary step on your added comments

**Comment by duglin** [comment]
LGTM

**Comment by LK4D4** [comment]
@avidas This actually not closes #11583 because there should be explanation for block of constants as in http://golang.org/src/math/const.go#L8
You can remove word closes from your commit or add block comment before `const` like:
```
// Common constants for daemon and client.
```

**Comment by avidas** [comment]
@LK4D4 added block comment

**Comment by estesp** [comment]
Thanks @avidas

**Comment by crosbymichael** [comment]
LGTM

Thanks @avidas !

**Comment by LK4D4** [comment]
@avidas Thank you!

**Pull request merged**
