### PR TITLE
overlay: skip superfluous metadata sets on commit

### PR DESCRIPTION
**Pull request by burke**
Hardlinked files share metadata. IME this makes `commit` 20-30% faster overall.

### CODE REVIEW

**Comment by LK4D4** [comment]
@burke Omg, you're so cool! Thank you.

**Comment by calavera** [comment]
Nice, LGTM!

**Comment by thaJeztah** [comment]
Pretty cool, thanks!

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
