### PR TITLE
Remove chain of engine passing from builder to loadManifest

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by runcom** [comment]
:wave: engine (at least from here)

**Comment by calavera** [comment]
:zap: one step closer!

There is test failing @LK4D4 ./runtime_test.go:141

**Comment by LK4D4** [comment]
@calavera Fixed, thanks!

**Comment by jfrazelle** [comment]
LGTM

**Comment by calavera** [comment]
LGTM :shipit:

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
