### PR TITLE
update docker_remote_api_v1.19.md

### PR DESCRIPTION
**Pull request by sunyuan3**
Signed-off-by: Yuan Sun sunyuan3@huawei.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
Nice catches! LGTM

**Comment by moxiegirl** [comment]
@SvenDowideit @fredlf @jamtur01

**Comment by thaJeztah** [comment]
Oh, good catch, can't believe I missed those; Looking at this; the same typos are also in the 1.18 API docs. Would be great to have them included as well, but if you can't, don't worry, it can also be done in a follow-up PR

**Comment by sunyuan3** [comment]
Hi @thaJeztah ,
No problem. They have been updated。^_^

sed -i 's/containg/containing/g' *.md
sed -i 's/othercontainers/other containers/g' *.md
sed -i 's/neworking/networking/g' *.md
sed -i 's/capabilties/capabilities/g' *.md
sed -i 's/byets/bytes/g' *.md
sed -i 's/exection/execution/g' *.md

**Comment by thaJeztah** [comment]
Oh, that's awesome @sunyuan3! :heart: (I was careful suggesting, because not all contributors are experienced Git users, which can be troublesome)

Thanks so much. LGTM (not a maintainer)

**Comment by jamtur01** [comment]
LGTM

**Pull request merged**
