### PR TITLE
support docker node ps multiNodes

### PR DESCRIPTION
**Pull request by allencloud**
Support `docker node ps node1 node2 node3...` Multi Nodes.

related to PR #25214 

@stevvooe 

Signed-off-by: allencloud allen.sun@daocloud.io

### CODE REVIEW

**Comment by cpuguy83** [comment]
SGTM

**Comment by stevvooe** [comment]
LGTM on design/code

Probably needs another look over for correctness.

**Comment by vdemeester** [comment]
Design and code LGTM 🐸
needs a rebase though
/cc @aaronlehmann

**Comment by allencloud** [comment]
Updated. PTAL
@cpuguy83 @stevvooe @vdemeester

**Comment by cpuguy83** [comment]
LGTM

Moving to docs

**Comment by allencloud** [comment]
Any Update?

**Comment by thaJeztah** [comment]
Oh! docs LGTM

ping @vdemeester 

ping @albers @sdurrheimer to check completion scripts

**Comment by vdemeester** [comment]
docs LGTM 🐸

**Comment by albers** [comment]
bash completion requires a change, I'll do that.

**Comment by allencloud** [comment]
Great, Thanks @albers

**Pull request merged**
