### PR TITLE
Adding Kitematic link to Mac OS X install instructions in docs

### PR DESCRIPTION
**Pull request by jmorganca**
Signed-off-by: Jeffrey Morgan jeff@kitematic.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
ping @jamtur01 @fredlf @SvenDowideit @spf13

**Comment by fredlf** [comment]
This feels a little too "marketing-ish" for tech docs. I think we should tone it down and stick to the facts. For example, 

## How do you want to work with Docker?

You can set up Docker using the command line with Boot2Docker and the guide below. Alternatively, you may want to try [Kitematic](https://kitematic.com/), an application that lets you set up Docker and run containers using a graphical user interface (GUI).

I also don't know why we've starting using HTML anchor tags for links instead of Markdown. Is there a benefit I don't know about?

**Comment by moxiegirl** [comment]
This "marketing" technique was used successfully at Atlassian. It is something Justen and I used at Bitbucket. Normally it wouldn't be done in the centra body but we are somewhat limited by the layout of the current docs. 

The benefit of an HTML anchor tag in this case is that it forces the link to open in a new window.  This allows the reader to "see" a new page without losing their place in the current document.

**Comment by fredlf** [comment]
I'm not suggesting we remove this entirely, I'm suggesting we change it's tone and wording to be more aligned with the rest of the docs and with appropriate tone and content for technical documentation. 

What really needs to happen is we revise the OSX docs to account for Kitematic at the outset. I will add that to the backlog.

I understand what the HTML tag does and what a target attribute is. I think that 
(a) opening new windows is as annoying to users as it is convenient. The back button works just as well. 
(b) Adding HTML sort of defeats the purpose of using markdown, now contributors need to know both "languages". 
(c) I'm concerned that mixing markup will have unintended consequences down the road if we migrate to different tool sets.

**Comment by spf13** [comment]
@fredlf 

(a) There's definitely a right place for opening in new windows. I'm sorry you find them annoying. I feel strongly that when you are following a tutorial that links should be in a new window so that the users don't lose their place in the tutorial.  

in response to (b) Html is valid markdown. It's the prescribed way to do things that require more than the simple set that markdown requires. 

(c) It shouldn't. HTML is valid markdown. Any tool that understands markdown also should understand HTML

**Comment by moxiegirl** [comment]
I should explain that both Justen and Kitematic team came to talk to me about doing this.  I purposely asked them to make the tone a Marketing tone.  It is to distinguish this content from the rest of the content which *is* instruction.  I've done this before in Atlassian documentation --- the only difference being I had more latitude in layout.  

So, I understand your concerns, Fred, I had them when I first started doing marketing in docs.  I didn't see any difference in page usage because of it.  My plan was to drop it in for Kitematic and watch the analytics.  The up side is Kitematic gets the leverage the traffic on that page and hopefully we could help Docker as a whole.

**Comment by fredlf** [comment]
(a) Okay. If we are going to have marketing copy in tech docs (which it appears we will no matter what), then I would ask that we set it apart not just by tone but also graphically (in a text box, by color/style/type, whatever). For me, putting myself in the user's shoes, an open source user in particular, it's an issue of trust. It's like asking my doctor his opinion on a mole and having him respond with a pitch for skin cream he sells on the side. (Sorry, just got back from doctor and couldn't avoid the metaphor.) Will I go back to that doctor? Probably, changing is a hassle. Will I trust her less? No doubt.

(b) The issue I have with new windows is not that *I* find them annoying. Many usability and design folk advise against it. Here is just one, I'm sure you can find more: http://www.coolfields.co.uk/2012/12/why-none-of-the-external-links-on-this-website-open-in-a-new-window/. I agree there may be applications, like pure tutorials, where a new window is desirable. I'm not sure this is one. It's a decision fork: method a or method b. That's why I think the best approach is to (slightly) re-write the page so that it makes clear at the outset that there are two methods for using Docker on OSX, then the user can choose the approach that works for them and follow that fork.

(c) Yes, I agree, most tools know markdown and HTML. The issue would arise from trying to do something like programmatically find all links, changing a heading level, or anything else that we are now marking up in two (or more) different ways. Plus there is the issue of ease for contributors, which I think would be a concern for you guys. 

Those are my thoughts. Do what you will with them. I'm not going to hold up this PR if other maintainers LGTM.

**Comment by jeffdm** [comment]
Updated the copy to @fredlf 's suggestion. Thanks Fred!

**Comment by fredlf** [comment]
LGTM, natch. Thank you Jeff.

**Pull request merged**
