### PR TITLE
Updated AUTHORS file

### PR DESCRIPTION
**Pull request by kaffarell**
Updated the list of AUTHORS using the generate-authors.sh script.

### CODE REVIEW

**Comment by kaffarell** [comment]
The last update of the AUTHORS file was about 8 months ago, so I figured out we should do an update...

**Comment by thaJeztah** [comment]
Thanks! It looks like the `.mailmap` needs some updates as well; I'll try to have a look soon with suggestions

**Comment by thaJeztah** [comment]
Sorry for the delay; I worked on the changes I wanted to suggest, and am carrying your commit in https://github.com/moby/moby/pull/43462 (I kept, but amended your original commit)

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/pull/43462 was merged; thanks for your contribution, @kaffarell !!

**Pull request closed without merging**
