### PR TITLE
pass DOCKER_CROSSPLATFORMS to the container in the Makefile

### PR DESCRIPTION
**Pull request by vieux**
can be useful to speed up builds

/cc @andrewhsu @tianon

### CODE REVIEW

**Review by tianon — APPROVED** [review]
LGTM :+1:

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
CI didn't run on this one; sign-off looks good;

```
Signed-off-by: Victor Vieux <victorvieux@gmail.com>
```

Is this safe to merge, or should we wait for CI to return?

**Comment by vieux** [comment]
@thaJeztah looks safe to me :)

**Comment by thaJeztah** [comment]
YOLO, here we go

**Comment by andrewhsu** [comment]
yes, pokes hole down to `hack/make/cross`
LGTM

**Comment by tiborvass** [comment]
@xylnao spot on! And I just got hit by it :(

**Pull request merged**
