### PR TITLE
Add CONFIG_IP_VS_PROTO_TCP, CONFIG_IP_VS_PROTO_UDP, IP_NF_TARGET_REDIRECT to check-config.sh

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/boot2docker/boot2docker/issues/1349

On kernels without this options set, publishing ports for swarm
services does not work, making the published port not accessible
("connection refused")

Thanks to Wenbo Wang (@supermanHub) for reporting, and @tianon for finding this.

**- Description for the changelog**

```markdown
* Add checks for `CONFIG_IP_VS_PROTO_TCP` and `CONFIG_IP_VS_PROTO_UDP ` to the `check-config.sh` utility script [moby/moby#38204](https://github.com/moby/moby/pull/38204)
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @fcrisciani @mavenugo @ctelfer PTAL

Also; please check if;

- there are other options that we need to check for (https://github.com/boot2docker/boot2docker/issues/1349#issuecomment-438481887)
- which PR / change made this a requirement? (should this only affect 18.09 or also earlier versions?)

**Comment by tianon** [comment]
Sorry for not being more clear in my digging over there; this has definitely been necessary for a while.

In the b2d issue, it turns out that "what changed" is the kernel config in b2d (much more minimal now), and it's still not totally working while passing `check-config.sh` with flying colors.

I'd wager these have probably been necessary since IPVS support was added, but I'm not sure if there are other Docker features I'm not testing that need more (I'm only testing TCP, since that's an easy test).

**Comment by thaJeztah** [comment]
So..... LGTY? 🤗 🍪

**Comment by tianon** [comment]
Definitely LGTM

Hopefully there aren't more, but if there are, hopefully someone knows more about the implementation so we can find them. :sweat_smile:

**Comment by tianon** [comment]
Looks like we need `CONFIG_IP_NF_TARGET_REDIRECT` too (https://github.com/boot2docker/boot2docker/issues/1349#issuecomment-438874235; thanks @alexivkin!!).

I'm building a new ISO to test now. :+1:

**Comment by thaJeztah** [comment]
Updated 👍

**Review by tiborvass — APPROVED** [review]
In @tianon / @thajeztah I trust

**Comment by thaJeztah** [comment]
YOLO! 😂

**Pull request merged**
