### PR TITLE
Align arg with other cli

### PR DESCRIPTION
**Pull request by yu8833**
**- What I did**
Align arg with other cli

**- How I did it**
Change arg to ARG

**- A picture of a cute animal (not mandatory but encouraged)**
image

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Please rebase

**Comment by AkihiroSuda** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Review by AkihiroSuda — APPROVED** [review]

**Comment by unclejack** [comment]
LGTM

**Review by unclejack — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Failures seems unrelated

windowsRS1 (cc @jhowardmsft 
```
08:31:38 ----------------------------------------------------------------------
08:31:38 FAIL: docker_cli_restart_test.go:31: DockerSuite.TestRestartRunningContainer
08:31:38 
08:31:38 docker_cli_restart_test.go:47:
08:31:38     c.Assert(out, checker.Equals, "foobar\nfoobar\n")
08:31:38 ... obtained string = "foobar\n"
08:31:38 ... expected string = "" +
08:31:38 ...     "foobar\n" +
08:31:38 ...     "foobar\n"
08:31:38 
08:31:46 
08:31:46 ----------------------------------------------------------------------
```

experimental
```
09:13:33 ---> Making bundle: tgz (in bundles/1.13.0-dev/tgz)
09:13:34 cp: cannot stat 'contrib/completion/powershell/*docker*': No such file or directory
```

**Comment by vdemeester** [comment]
@YuPengZTE could you rebase against master ? (to fix builds)

**Comment by YuPengZTE** [comment]
@vdemeester PTAL

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Seems you squashed unrelated commit (https://github.com/docker/docker/commit/da382044d3630bcdeb1eac64f2f7ad476e0cf007) 

https://github.com/docker/docker/pull/28020/files#diff-d29ab18bc1c80d073a65414c9c4977e7

**Comment by YuPengZTE** [comment]
Thanks @AkihiroSuda, PTAL.
Rollback the second rebase.

**Review by vdemeester — CHANGES_REQUESTED** [review]
@YuPengZTE something is wrong with the commit :sweat:

**Comment by YuPengZTE** [comment]
Is there wrong with man/docker.1.md？
@vdemeester

**Comment by vdemeester** [comment]
@YuPengZTE no no, but your commit is "Merge pull request #28046 from tophj-ibm/make-debs-1610" amended, which is not right :sweat: (and not mergeable as is)

**Comment by YuPengZTE** [comment]
@vdemeester 
I am so sorry for that, then how should I do with this PR？
Close it or ？

**Comment by vdemeester** [comment]
@YuPengZTE something like the following should work I think

```
git reset HEAD~1
git stash
git checkout master
git fetch -p --all
# The line below make the assumption the docker upstream remote is named upstream
git rebase upstream/master
git branch -D devArg
git checkout -b devArg
git stash pop
git add -u
git commit -s …
```

**Comment by YuPengZTE** [comment]
Thanks @vdemeester.
PTAL @AkihiroSuda .

**Comment by AkihiroSuda** [comment]
Please update the commit message

git commit -a --amend

**Comment by YuPengZTE** [comment]
Thanks @AkihiroSuda, PTAL.

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Pull request merged**
