### PR TITLE
fix dead lock in volume store dereference

### LINKED ISSUE #19777: volume store dereference return without release lock
Description of problem:
The early return cause deadlock.  #dibs

```go
func (s *VolumeStore) Dereference(v volume.Volume, ref string) {
        s.locks.Lock(v.Name())
        defer s.locks.Unlock(v.Name())

        s.globalLock.Lock()
        refs, exists := s.refs[v.Name()]
        if !exists {
                return
        }

        for i, r := range refs {
                if r == ref {
                        s.refs[v.Name()] = append(s.refs[v.Name()][:i], s.refs[v.Name()][i+1:]...)
                }
        }
        s.globalLock.Unlock()
}
```

`docker version`:

`docker info`:

`uname -a`:

Environment details (AWS, VirtualBox, physical, etc.):

How reproducible:

Steps to Reproduce:

Actual Results:

Expected Results:

Additional info:

### PR DESCRIPTION
**Pull request by patricksuo**
fix #19777

Signed-off-by: Pei Su sillyousu@gmail.com

### CODE REVIEW

**Comment by coolljt0725** [comment]
ping @cpuguy83

**Comment by runcom** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM
Nice catch!
Did you run into this deadlock? I can't imagine it actually being possible.

**Comment by sillyousu** [comment]
re @cpuguy83 ,
>Did you run into this deadlock? I can't imagine it actually being possible.

No, I don't. I found this when I read docker source code. 
Maybe this code snippets will never cause a dead lock. 
I send this PR just in case.

**Pull request merged**
