### PR TITLE
Update apparmor error message

### PR DESCRIPTION
**Pull request by decoursin**
Apparmor was missing on my machine, so this error appeared. Then, it failed to install apparmor (maybe because of failed to fetch packages?), so it failed to download docker which it left me confused why docker wasn't installed.

**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @decoursin! Could you sign-off your commit using the instructions that @GordonTheTurtle gave above?

**Comment by decoursin** [comment]
You're welcome, and thanks for your work on Docker and the helpful directions.

**Comment by thaJeztah** [comment]
LGTM

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
