### PR TITLE
Move container exit state to after cleanup.

### PR DESCRIPTION
**Pull request by cpuguy83**
Before this change, there is no way to know if container (runtime)
resources have been cleaned up unless you actually remove the container.

This change allows callers of the wait API or the events API to know
that all runtime resources for the container are released (e.g. IP
addresses).

### CODE REVIEW

**Comment by thaJeztah** [comment]
discussing in the maintainers meeting; putting this on hold for directly after 20.10.0, to give it some time for testing

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
LGTM :see_no_evil:

**Comment by thaJeztah** [comment]
Failures are unrelated

**Comment by thaJeztah** [comment]
Discussing in the maintainers meeting, and we'll keep this one for 21.xx, so removing the cherry-pick label for now

**Pull request merged**
