### PR TITLE
Move more 'daemon' errors to the new error package

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by tiborvass** [comment]
@duglin needs rebase

**Comment by duglin** [comment]
@tiborvass rebased

**Comment by duglin** [comment]
@tiborvass rebased and all green!

**Comment by duglin** [comment]
crud - not all green but the failures are unrelated

**Comment by jfrazelle** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
