### PR TITLE
Treat systemd listeners as all other

### LINKED ISSUE #13549: Docker 1.7.0-rc1 fails to shutdown cleanly using systemd
Using docker-engine-1.7.0-0.1.rc1.fc21.x86_64

```
$ sudo systemctl start docker
$ sudo systemctl stop docker
# hangs here for a while, ultimately times out and is killed
```

Here are the journald logs:
```
May 28 09:39:57 localhost.localdomain systemd[1]: docker.service stop-sigterm timed out. Killing.
May 28 09:39:57 localhost.localdomain systemd[1]: docker.service: main process exited, code=killed, status=9/KILL
```

Here's the output from SIGUSR1:

```
May 28 09:38:48 localhost.localdomain docker[32111]: time="2015-05-28T09:38:48.399283895-04:00" level=info msg="=== BEGIN goroutine stack dump ===
goroutine 10 [running]:
github.com/docker/docker/pkg/signal.DumpStacks()
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:60 +0x7a
github.com/docker/docker/daemon.funcÂ·021()
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/debugtrap.go:18 +0x6d
created by github.com/docker/docker/daemon.setupSigusr1Trap
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/debugtrap.go:20 +0x18e

goroutine 1 [chan receive]:
main.mainDaemon()
	/root/rpmbuild/BUILD/docker-engine/docker/daemon.go:179 +0x10ae
main.main()
	/root/rpmbuild/BUILD/docker-engine/docker/docker.go:92 +0x6b4

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.initÂ·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 25 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208193f40)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 9 [chan receive]:
github.com/docker/docker/api/server.(*Server).newServer(0xc2080dcf80, 0x7ffdbe375f7c, 0x2, 0x7ffdbe375f7c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server_linux.go:42 +0x3d3
github.com/docker/docker/api/server.(*Server).ServeApi(0xc2080dcf80, 0xc2080946f0, 0x1, 0x1, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server.go:96 +0x252
main.funcÂ·003()
	/root/rpmbuild/BUILD/docker-engine/docker/daemon.go:129 +0x5f
created by main.mainDaemon
	/root/rpmbuild/BUILD/docker-engine/docker/daemon.go:135 +0x6bc

goroutine 26 [IO wait]:
net.(*pollDesc).Wait(0xc20842b720, 0x72, 0x0, 0x0)
	/usr/lo
May 28 09:38:48 localhost.localdomain docker[32111]: cal/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20842b720, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc20842b6c0, 0xc208114850, 0x10, 0x10, 0xc208664420, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc208034af0, 0xc208114850, 0x10, 0x10, 0xc208664420, 0x1000, 0x1000, 0x50, 0xc208114464, 0x4, ...)
	/usr/local/go/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc208664400, 0xc208114850, 0x10, 0x10, 0xc208664400, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7f3e5ab1f960, 0xc208664400, 0xc208114850, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f3e5ab1f960, 0xc208664400, 0xc208114850, 0x10, 0x10, 0x50, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc2084c7e10, 0xc2083e9200, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc2083e67e0)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 27 [chan receive]:
github.com/godbus/dbus.(*Conn).outWorker(0xc2083e67e0)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 28 [chan receive]:
github.com/coreos/go-systemd/dbus.funcÂ·001()
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/go-systemd/dbus/subscription.go:70 +0x64
created by github.com/coreos/go-systemd/dbus.(*Conn).initDispatch
	/root/rpmbuild/BUILD/docker-engin
May 28 09:38:48 localhost.localdomain docker[32111]: e/vendor/src/github.com/coreos/go-systemd/dbus/subscription.go:94 +0x11c

goroutine 29 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc20865d5c0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/stats_collector.go:89 +0xb2
created by github.com/docker/docker/daemon.newStatsCollector
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/stats_collector.go:29 +0x116

goroutine 106 [chan receive]:
main.funcÂ·004()
	/root/rpmbuild/BUILD/docker-engine/docker/daemon.go:164 +0x6e
github.com/docker/docker/pkg/signal.funcÂ·001(0x7f3e5ab00f68, 0xc2081142b0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:38 +0x1b6
created by github.com/docker/docker/pkg/signal.funcÂ·002
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:53 +0x13a

goroutine 105 [IO wait]:
net.(*pollDesc).Wait(0xc20842bbf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20842bbf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20842bb90, 0x0, 0x7f3e5ab05160, 0xc208114210)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc2081b8300, 0xc2089f4e38, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc2081b8300, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:293 +0x4c
net/http.(*Server).Serve(0xc2087082a0, 0x7f3e5ab0cfb8, 0xc2081b8300, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.funcÂ·009()
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server_linux.go:38 +0xdb
created by github.com/docker/docker/api/server.(*Server).newServer
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server_linux.go:39 +0x35e

goroutine 103 [chan receive]:
github.com/docker/docker/pkg/signal.
May 28 09:38:48 localhost.localdomain docker[32111]: funcÂ·002()
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x8f
created by github.com/docker/docker/pkg/signal.Trap
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x250

=== END goroutine stack dump ==="
```

### PR DESCRIPTION
**Pull request by LK4D4**
Fix #13549

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
cherry picked :)

**Pull request merged**
