### PR TITLE
Replace zsh completion for 'docker volume create --name' by 'docker v…

### PR DESCRIPTION
**Pull request by sdurrheimer**
ref. #23830

ping @albers bash completion

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM :cat:

**Comment by cpuguy83** [comment]
LGTM

**Comment by sfsmithcha** [comment]
@tiborvass marked as `process/cherry-pick`

**Comment by thaJeztah** [comment]
This is for 1.13, so removed cherry pick label

**Pull request merged**
