### PR TITLE
Make install instruction consistent

### PR DESCRIPTION
**Pull request by HackToday**
Right now in ubuntu section, instruction is not consistent
for sudo, so it is better to keep it style same.

Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
hm, I think we added the first step for that;

"If you haven't already done so, log into your Ubuntu instance as a privileged user."

But I also see we're using sudo for some of these steps, so :+1: :-1: 

@vdemeester wdyt?

**Comment by HackToday** [comment]
Hi @thaJeztah  other distros seems maintain same context. except the ubuntu here.

I did not see a user case for 

first logn as a privileged user, it seems strange here to me, what's the  privileged user means here.
Someone with `sudo` can also means privileged user.  I did not think user would login as `root`

**Comment by thaJeztah** [comment]
Alright; if we're going to use `sudo`, I think we should remove the first step

**Comment by vdemeester** [comment]
Oh yeah, we're using `sudo` in other docs, so agreed with @thaJeztah to remove the first step and go to use `sudo`.

**Comment by HackToday** [comment]
hi @thaJeztah  and @vdemeester , per my understanding, the first sentence just means:

Log into your machine as a user with sudo or root privileges.


check this as a reference:
https://github.com/docker/docker/blob/master/docs/installation/linux/fedora.md
Section `Install with DNF`

Or https://github.com/docker/docker/blob/master/docs/installation/linux/centos.md
Section `Install with yum`

I think we can keep that, or change to as above

Wdyt ?  Thanks

**Comment by vdemeester** [comment]
@HackToday hum make sence :stuck_out_tongue:

**Comment by MHBauer** [comment]
@HackToday maybe that first sentence should also be changed to say that. It is better to be explicit.

**Comment by HackToday** [comment]
@MHBauer  I could change that look that ways if we think `privileged` not map to `sudo and root users`

@thaJeztah  WDYT ? I would change that to be same as centos etc.

**Comment by HackToday** [comment]
Let's get a consistent a option before I send another PR   :)

**Comment by HackToday** [comment]
@thaJeztah  Please check the comments above, I hope this is more consistent for all os

**Comment by HackToday** [comment]
New PR changes have been sent

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by vdemeester** [comment]
LGTM 🐹

**Pull request merged**
