### PR TITLE
Fix vet errors

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by jfrazelle** [comment]
we should add vet to the tests, i like vet

**Comment by LK4D4** [comment]
@jfrazelle Yup, I'm too, I wonder how to suppress:
```
pkg/devicemapper/devmapper_wrapper.go:230: possible misuse of unsafe.Pointer
```
Maybe @vbatts knows

**Comment by jfrazelle** [comment]
is there a way to misuse unsafe.Pointer, i figured that was the point of unsafe haha

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by vbatts** [comment]
late, but whateva.

I've researched this. I'm not sure there is a better way to do this.
unsafe.Pointer is the actual thing used for representing a void* in C.
There is an allusion to the runtime detecting the misuse of an
unsafe.Pointer and crashing itself, but this is proper use of it ...

On Wed, Jan 14, 2015 at 5:41 PM, Alexander Morozov <notifications@github.com

**Comment by LK4D4** [comment]
@vbatts Hmm, maybe we should post issue to golang tracker?

**Pull request merged**
