### PR TITLE
Add redis logging driver

### PR DESCRIPTION
**Pull request by lami02**
Adding a redis logging driver using redis.v3. The commit includes new docs describing how to use the logging driver. Feature #19804

Signed-off-by: Lennart Lamerz lennart.lamerz@pressrelations.de

### CODE REVIEW

**Comment by phemmer** [comment]
Was there agreement that this is a feature docker wants? I'm not part of the docker project, so this is just my opinion, but this doesn't seem like a good feature to include. Redis is not meant to be used as a log collection platform. Yes it can be done, but that doesn't mean it should be done, or supported.

Perhaps you can add your reasoning and use case?

**Comment by lami02** [comment]
@phemmer:  I agree, that redis should not be used as a collection platform, but I think redis is a very useful buffer for log messages. From my understanding redis is just a key/value store, so it is meant to store what ever you want or need.

I've tried to explain my reasons in the feature request. If you want to process your logs further, it is important to have a highly available store, where docker can send the logs initially. Redis has this high availability and it is much easier to handle than "syslog-like" log-files. In my opinion something like redis is especially needed, if you have dozens of containers, generating millions of logs and you want all logs in one logging system (like kibana from elastic).

I hope, that I made my intentions clear. I'm sorry, if I did something wrong in the whole contribution flow. It is my first time and I tried to hold on to the docs for contributing.

**Comment by calavera** [comment]
I agree with @phemmer. I don't think we should add this feature.

**Comment by runcom** [comment]
I'm in agreement with @phemmer and @calavera, I don't think Redis is a good candidate for logging

**Comment by cpuguy83** [comment]
Agreed, redis is not a good target, especially for adding 7k LOC.

@lami02 Nothing wrong with the contribution flow. It may help to check with maintainers before implementing a feature in the future so it's not a waste of time for you.
Sorry this one didn't pan out!

**Comment by lami02** [comment]
@calavera, @cpuguy83 @runcom @phemmer

Redis itself think it is a good candidate for logging:
https://redislabs.com/ebook/redis-in-action/part-2-core-concepts-2/chapter-5-using-redis-for-application-support/5-1-logging-to-redis

And so does Elastic/Logstash:
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html

It is ok, if you don't want this driver, but I think just saying redis is not for logging messages isn't such a good  argument.

**Comment by benjamincburns** [comment]
Have to agree with @lami02. It seems a bit overzealous for the docker project to enforce its views on best practices over how redis should or shouldn't be used, especially considering how generic of a tool redis is. For those of us using logstash & ElasticSearch, it's very common to set up redis to act as a buffer for logs flowing into ElasticSearch through logstash. We've done this in my organization with much success.

**Pull request closed without merging**
