### PR TITLE
Revendor Microsoft/hcsshim and vendor Microsoft/go-winio

### PR DESCRIPTION
**Pull request by jstarks**
This update changes the way hcsshim invokes Windows DLLs to avoid races
with the garbage collector. It also now uses go-winio to access the
pipes used for communication with processes running in the container;
this reduces the number of threads used by docker.exe, improving
scalability.

Signed-off-by: John Starks jostarks@microsoft.com

### CODE REVIEW

**Comment by jstarks** [comment]
@jhowardmsft

**Comment by calavera** [comment]
LGTM

**Comment by jhowardmsft** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
