### PR TITLE
Build docker-proxy from git checkout like other external binaries

### PR DESCRIPTION
**Pull request by justincormack**
This means we can vendor libnetwork without special casing, and
it is built the same way as the other external binaries.

Signed-off-by: Justin Cormack justin.cormack@docker.com

cc @LK4D4 @tonistiigi as you were discussing previously

husky

### CODE REVIEW

**Comment by tonistiigi** [comment]
Design LGTM

**Comment by justincormack** [comment]
Vendored.

Related #27556 - this PR needs to fix the rpm/deb builds too.

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by mlaventure** [comment]
LGTM, but need a rebase

**Comment by justincormack** [comment]
rebased

**Comment by LK4D4** [comment]
@justincormack can you change deb and rpm generators as well?

**Comment by justincormack** [comment]
Updated, but haven't had a chance to fully test the debs and rpms yet, will do.

**Comment by thaJeztah** [comment]
ping @mlaventure @andrewhsu ^^ :innocent:

**Comment by LK4D4** [comment]
@justincormack you need to update `hack/make/build-deb` and `hack/make/build-rpm` and change lines with
```
RUN ./hack/dockerfile/install-binaries.sh runc-dynamic containerd-dynamic
```

**Comment by justincormack** [comment]
@LK4D4 done. Also added `grimes` to the deb and rpms as was missing.

**Comment by LK4D4** [comment]
LGTM

**Comment by mlaventure** [comment]
Ah, too fast. Was about to comment on this.

`grimes` isn't included in the deb at least for `ubuntu-xenial`.

**Comment by mlaventure** [comment]
My bad, it worked must have been on a stalled branch :sweat_smile:

**Pull request merged**
