### PR TITLE
Minor comment fix

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — COMMENTED** [review]
Do we have it for 1.8?
(Seems not https://golang.org/dl/

**Comment by AkihiroSuda** [comment]
ok, 1.9beta2 seems to have arm64
 
so s/1.7/pre-1.9/ maybe?

**Comment by thaJeztah** [comment]
hm, should we update the Dockerfile in https://github.com/moby/moby/pull/33892 ?

**Comment by hqhq** [comment]
@AkihiroSuda I don't think there are any official ARM64 golang binaries for any version, so I suggest we remove the version number in comments so we don't have to update that every time we update go version. Once we have that official binary, we can rewrite that part of Dockerfile any remove these comments.

@thaJeztah Feel free to take this in #33892 and close this one.

**Comment by hqhq** [comment]
Wait, I just saw that in 1.9 rc2 as @AkihiroSuda said, let me check if that's the right version (little endian), if it is, we can update the Dockerfile after #33892 landed.

**Comment by hqhq** [comment]
@thaJeztah I think I can update Dockerfile.aarch for the go installation part after #33892 landed, it'll be better to be in a separate PR as it'll need extra tests on ARM64 server.

**Comment by thaJeztah** [comment]
@hqhq I opened https://github.com/moby/moby/pull/33892 to see what breaks; I don't personally have access to arm64, but if you know what needs to be changed, perhaps we should include it in the same PR (and work on that PR to make everything work)

**Pull request closed without merging**
