### PR TITLE
Remove some unused structs and fields

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by icecrime** [comment]
Known failure on win2lin (see #20817).

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (52/50 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:49380 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aarkG-00087l-Cl
	for fred@ventureacceleration.com; Tue, 01 Mar 2016 16:22:16 -0500
Date: Tue, 01 Mar 2016 10:56:09 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1456858569;
	bh=nq6nuo7zLLWf3cn6rBU8PUAN7ahbFzbGsYZh16KTOcE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=VivBae7rOV3BUDoKlxx6Of7Af1TqUVCi0D5KJkttRdV/2e5N1ELsEWEYVL+Qm05Uw
	 MoYOKA7kwMHaSDtx2AdulnbOCOHPxhgaqN3dASdh+NM3jsMbN/cWWp8rp28BFWRAv7
	 XyRN5PdMYVFWbYGlgT1Sh9JI+1v3LGaCIZlMXnwM=

**Pull request merged**
