### PR TITLE
Update --cgroup-parent cli integration test to use "memory" cgroup instead of "cpu"

### LINKED ISSUE #11509: --cgroup-parent fails on systemd
sorry ping @vish

```
unexpected file format for /proc/self/cgroup - ""--- FAIL: TestRunContainerWithCgroupParent (0.10s)
	docker_cli_run_unix_test.go:137: unable to find self cpu cgroup path. CgroupsPath: map[blkio:/system.slice/docker-cd49b1e38a0c32aeaae5139402dd2a5a1b8bf10c77a04de1f054c8c4829558cb.scope net_cls:/ freezer:/system.slice/docker-cd49b1e38a0c32aeaae5139402dd2a5a1b8bf10c77a04de1f054c8c4829558cb.scope devices:/system.slice cpuset:/system.slice/docker-cd49b1e38a0c32aeaae5139402dd2a5a1b8bf10c77a04de1f054c8c4829558cb.scope perf_event:/ memory:/system.slice/docker-cd49b1e38a0c32aeaae5139402dd2a5a1b8bf10c77a04de1f054c8c4829558cb.scope cpuacct,cpu:/system.slice/docker-cd49b1e38a0c32aeaae5139402dd2a5a1b8bf10c77a04de1f054c8c4829558cb.scope name=butts:/system.slice/docker-cd49b1e38a0c32aeaae5139402dd2a5a1b8bf10c77a04de1f054c8c4829558cb.scope hugetlb:/]
unexpected file format for /proc/self/cgroup - 
```

### PR DESCRIPTION
**Pull request by vishh**
This should make it pass on systemd machines.

closes #11509 
cc @jfrazelle

### CODE REVIEW

**Comment by jfrazelle** [comment]
oh damn you beat me to my fix lol, i will try now

**Comment by jfrazelle** [comment]
nice works locally for me w systemd LGTM ping @LK4D4

**Comment by jfrazelle** [comment]
can you add a closes #11509

**Comment by vishh** [comment]
@jfrazelle: Done. Thanks for the quick review :)

**Comment by jfrazelle** [comment]
actually would it be too much to ask for a `fmt.Printf("unexpected file format for /proc/self/cgroup - %q\n", line)` on line 117, it kinda is jarring on the same line right now :)

**Comment by vishh** [comment]
Done

**Comment by jfrazelle** [comment]
yayyy thanks :)

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
