### PR TITLE
Rely on container-selinux for centos/fedora25/rhel

### PR DESCRIPTION
**Pull request by cpuguy83**
RH now provides `container-selinux` which provides everything we need
for docker's selinux policy. Rely on `container-selinux` where
available, and `docker-engine-selinux` when not.

This still builds the `docker-engine-selinux` package and presumably
makes it available, but is no longer a requirement in the
`docker-engine` package preferring `container-selinux` instead.

`container-selinux` is available on fedora24, however the version that
is available does not set the correct types on the `dockerd` binary. We
can use `container-selinux` and just supplement that with some of our
own policy, but for now just keep using `docker-engine-selinux` as is.

ping @andrewhsu @rhatdan

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @runcom as well 👍

**Comment by runcom** [comment]
seems fine to me, I'll spin up a F25/F26 vm and test this out.

**Comment by rhatdan** [comment]
:+1:

**Comment by cpuguy83** [comment]
Ping

**Review by vdemeester — APPROVED** [review]
LGTM 🐢 
/cc @runcom

**Comment by andrewhsu** [comment]
LGTM

stuff works:
```
$ make KEEP_BUNDLE=1 DOCKER_BUILD_PKGS='centos-7' rpm
$ docker run --rm -it -v `pwd`:/v -w /v centos:7 yum -y install bundles/latest/build-rpm/centos-7/RPMS/x86_64/docker-engine-17.06.0-*.rpm
...
Complete!
```

**Comment by thaJeztah** [comment]
Just chatted with @runcom and he may have some time tomorrow to give it a spin, so I suggest to wait until tomorrow (thanks Antonio!)

**Comment by runcom** [comment]
LGTM!

**Review by runcom — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thank you @runcom 👍

**Comment by cpuguy83** [comment]
All green.

**Comment by cognitiaclaeves** [comment]
This looks like this has been built. Is the package released yet? I just hit this issue today, in Azure, with docker-ce-17.03.1.ce-1.el7.centos.x86_64.

**Comment by cpuguy83** [comment]
@cognitiaclaeves It'll be in the 17.06.

**Comment by cognitiaclaeves** [comment]
I see it now. Is there a work around until then?

**Comment by rhatdan** [comment]
Container-selinux is continuously released.  The latest package is in fedora-updates.

**Comment by cpuguy83** [comment]
@cognitiaclaeves Hit what issue, exactly?

**Comment by ericsysmin** [comment]
Please be aware this affects https://docs.docker.com/engine/installation/linux/docker-ce/centos/ where "Uninstall old version" causes previous up-to-date installations to be uninstalled due to changed dependency.

**Pull request merged**
