### PR TITLE
[20.10] Remove containerd "platform" dependency from client

### PR DESCRIPTION
**Pull request by dims**
Request to cherry pick https://github.com/moby/moby/pull/42623 to 20.10 branch

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Does this fix any important bug?
Otherwise not sure it's worth backporting.

**Comment by dims** [comment]
@AkihiroSuda it helps us break the dependency cycles between containerd <-> kubernetes <-> cadvisor <-> moby

**Review by AkihiroSuda — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
@dims as you may have seen, we're working on 20.10.14 for a (minor) security issue; so won't include it in that release, but I'll discuss doing a regular patch release soon after (and happy to include these)

**Comment by dims** [comment]
@thaJeztah that's totally fair! works!

**Pull request merged**
