### PR TITLE
Bump to version v1.5.0

### PR DESCRIPTION
**Pull request by icecrime**

### CODE REVIEW

**Comment by tiborvass** [comment]
In the past, we would not use `The` for bullet items in the Changelog.
/cc @tianon @crosbymichael

**Comment by icecrime** [comment]
Thanks @tibor! `CHANGELOG.md` updated.

**Comment by jfrazelle** [comment]
ping @bjaglin @Sirupsen @burke you all have been active in testing before. Can you please help us out again now :)

**Comment by jfrazelle** [comment]
Ubuntu/Debian: curl -sSL https://test.docker.com/ubuntu | sh or curl -sSL https://test.docker.com/ | sh
Linux 64bit binary: https://test.docker.com/builds/Linux/x86_64/docker-1.5.0
Darwin/OSX 64bit client binary: https://test.docker.com/builds/Darwin/x86_64/docker-1.5.0
Darwin/OSX 32bit client binary: https://test.docker.com/builds/Darwin/i386/docker-1.5.0
Linux 64bit tgz: https://test.docker.com/builds/Linux/x86_64/docker-1.5.0.tgz

**Comment by dlorenc** [comment]
Will there be boot2docker rc builds?

**Comment by proppy** [comment]
> Will there be boot2docker rc builds?
/cc @tianon

**Comment by LK4D4** [comment]
Also stat test failing if runned on systemd machine. There is just no stats in that cgroup, probably should look in other place :/

**Comment by jfrazelle** [comment]
But to clarify, stats works on the host, just not dind (with systemd).

**Comment by LK4D4** [comment]
@jfrazelle Yup, this affects docker in docker. I think we can find solution pretty fast, but this is not critical as @crosbymichael said.

**Comment by icecrime** [comment]
Ping @dlorenc: could you please let us know how things are working out with the release at Google? Do you know if Kubernetes was tested against rc1? Thanks!

**Comment by proppy** [comment]
@icecrime we have one breakage because some of the log format we get for build success from docker-py with no cache has changed, I'll dig more and open a new bug with more details.

**Comment by proppy** [comment]
@icecrime can we get another rc (rc2) with the fix for #10364?

**Comment by icecrime** [comment]
@proppy I'm finishing the cherry-picking, RC2 will happen today (hopefully before noon).

**Comment by proppy** [comment]
Thanks! /cc @dlorenc

**Comment by icecrime** [comment]
RC2 is available (see [the announcement](https://groups.google.com/d/msg/docker-dev/YM_UUkyM6hY/K3SfbAS4KbAJ) on groups).

> **Ubuntu/Debian:** https://test.docker.com/ubuntu or curl -sSL https://test.docker.com/ | sh
> **Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0-rc2
> **Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.5.0-rc2
> **Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.5.0-rc2
> **Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0-rc2.tgz

Tag is [`v1.5.0-rc2`](https://github.com/docker/docker/tree/v1.5.0-rc2).

**Comment by dlorenc** [comment]
This one LGTM for https://github.com/docker/docker/issues/10364

**Comment by crosbymichael** [comment]
@dlorenc awesome, thanks for testing this with us

**Comment by burke** [comment]
I'm installing rc2 on a few of our servers today. Everything looks good so far.

**Comment by icecrime** [comment]
Thanks for the feedback @burke!

Quick head-ups: we discovered one issue which will most likely call for an RC3 (I'm thinking sometime during the week-end if we want to hold our release date of February 3rd). Details are here: docker/distribution#112, related engine issue is #10432.

**Comment by burke** [comment]
Kind of a minor thing -- not even going to open an issue unless someone else thinks it's worth it -- but:

```
Jan 29 18:34:32.286:	+ docker inspect --format=. registry.chi.shopify.io:80/base:1.3.5
Jan 29 18:34:32.297:	time="2015-01-29T18:34:32Z" level="fatal" msg="mkdir /u/apps/locutus/.docker: permission denied" 
```

Docker probably shouldn't require write permission to the home directory for simple read operations.

**Comment by crosbymichael** [comment]
@burke ya, i think that is a bug I think it would be good to open an issue for that

**Comment by jfrazelle** [comment]
@burke that might be related to https://github.com/docker/docker/issues/10297 also thanks to much for continually testing the RC's, much appreciated

**Comment by burke** [comment]
I found another weirdness: https://github.com/docker/docker/issues/10444

Sorry I didn't get around to testing this earlier; we've had a busy week.

**Comment by crosbymichael** [comment]
@burke no problem at all,  this helps alot and we will work on fixes ASAP.

**Comment by burke** [comment]
I can't tell whether I'm doing something wrong or whether the published images on the apt repo are signed with the wrong key, but:

```
burke@sb4-perf.chi:/etc/sv 100$ apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.HCUjTwKZ1C --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
gpg: requesting key A88D21E9 from hkp server keyserver.ubuntu.com
gpg: key A88D21E9: "Docker Release Tool (releasedocker) <docker@dotcloud.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
burke@sb4-perf.chi:/etc/sv $ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.ppAKACHv7l --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
gpg: requesting key A88D21E9 from hkp server keyserver.ubuntu.com
gpg: key A88D21E9: "Docker Release Tool (releasedocker) <docker@dotcloud.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
burke@sb4-perf.chi:/etc/sv $ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 740B314AE3941731B942C66ADF4FD13717AAD7D6
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.OCWhcuJfgi --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 740B314AE3941731B942C66ADF4FD13717AAD7D6
gpg: requesting key 17AAD7D6 from hkp server keyserver.ubuntu.com
gpg: key 17AAD7D6: "Docker Release Tool (releasedocker) <docker@dotcloud.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
burke@sb4-perf.chi:/etc/sv $ sudo apt-get install lxc-docker=1.5.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-meld3 python-tornado supervisor
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  lxc-docker-1.5.0
The following packages will be REMOVED:
  lxc-docker-1.3.0
The following NEW packages will be installed:
  lxc-docker-1.5.0
The following packages will be upgraded:
  lxc-docker
1 upgraded, 1 newly installed, 1 to remove and 103 not upgraded.
Need to get 4,624 kB of archives.
After this operation, 834 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  lxc-docker lxc-docker-1.5.0
Install these packages without verification? [y/N]
```

I added the keys from both `test.docker.io/ubuntu` and `get.docker.io/ubuntu`, and it still can't authenticate the new `lxc-docker` on the test repo. I can ignore it easily enough if I run the install manually, so it's no big deal for me.

**Comment by vishh** [comment]
I tested rc2 with Kubernetes and I didn't notice any regressions :+1:

**Comment by bjaglin** [comment]
Thanks for the heads up - couldn't find any obvious regression for our scenarios with rc2. Added the minor https://github.com/docker/docker/pull/10500 after testing `--memory-swap`.

**Comment by icecrime** [comment]
I just forced pushed to build `1.5.0-rc3` (yes, release date will have to be delayed by most likely 2 days): [diff with `1.5.0-rc2`](https://gist.github.com/icecrime/5cd12ae81f8cf76b5e9f).

**Comment by thaJeztah** [comment]
Great! Will give it a spin tonight! type://test.docker.com?

Great job everyone 👏

**Comment by icecrime** [comment]
RC3 is available (see [the announcement](https://groups.google.com/d/msg/docker-dev/m_EZHGUjzQw/vEniEeZZSugJ) on groups).

> **Ubuntu/Debian:** https://test.docker.com/ubuntu or curl -sSL https://test.docker.com/ | sh
> **Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0-rc3
> **Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.5.0-rc3
> **Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.5.0-rc3
> **Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0-rc3.tgz

**Comment by dlorenc** [comment]
RC3 looks good in some manual testing for our (Google App Engine Managed VMs) workflows.

**Comment by icecrime** [comment]
RC4 is available (see [the announcement](https://groups.google.com/forum/#!topic/docker-dev/uXsaWFfYUgE) on groups).

> **Ubuntu/Debian:** https://test.docker.com/ubuntu or curl -sSL https://test.docker.com/ | sh
> **Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0-rc4
> **Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.5.0-rc4
> **Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.5.0-rc4
> **Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0-rc4.tgz

Tag is [`v1.5.0-rc4`](https://github.com/docker/docker/tree/v1.5.0-rc4).

**Comment by icecrime** [comment]
Branch is updated to include the docs commits (thanks @SvenDowideit!).

Differences with `v1.5.0-rc4` provided below for reference:

```
$ git log --oneline v1.5.0-rc4..HEAD
4ab370c Bump to version v1.5.0
d8381fa Update certificates.md
be37958 docs: fix a typo in Dockerfile.5.md
7ea8513 Fix example about ps and linked containers
3b2fe01 Documentation on boolean flags is wrong #10517
e8afc22 Do some major rearranging of the fedora/centos/rhel installation docs
4e407e6 update fedora docs to reflect latest rpm changes
23f1c2e docs/articles/systemd: correct --storage-driver
788047c Format `awsconfig` sample config correctly
0c0e7b1 Fix a small spelling error in the dm.blkdiscard docs
09d4152 Add an initial list of new features in Docker Engine 1.5.0
cb288fe remove swarm, machine and compose from the 1.5.0 release docs
f763679 The DHE documentation will not be published with 1.5.0
cb5af83 For now, docker stats appears to be libcontainer only
96feaf1 docs: fix typo
1f03944 Documents build API "remote" parameter
6060eed The Hub build webhooks now list the images that have been built
d217da8 Spelling mistake in dockerlinks
d74d6d9 add crosbymichael and Github -> GitHub
0205ac3 update MAINTAINERS file
dbb9d47 The reference menu is too big to list more than the latest API docs, so the others can be hidden - they're still linked from the API summary
ddd1d08 use the same paths as in the swarm repo, so that their links magically work
d6ac36d Docker attach documentation didn't make sense to me
715b94f Distinguish ENV from setting environment inline
16baca9 docs: change events --since to fit RFC3339Nano
627f8a6 Remove File List
a8a7df2 Fix broken link to project/MAINTAINERS.md
580cbce Update dockerfile_best-practices.md
d9c5ce6 Fix a tiny typo.
0fe9b95 fix project url in readme to point to the correct location, https://github.com/docker/docker/tree/master/project
41d0e42 Update events format in man page
26fe640 Add builder folks to the top-level maintainers file
198ca26 Added tianon's info and changed a typo.
d5365f6 Fix incorrect IPv6 addresses/subnet notations in docs
5f7e814 Update go-md2man
a84aca0 Fix docs so WORKDIR mentions it works for COPY and ADD too
68ec228 Proposal for an improved project structure.
0dcc355 Updated image spec docs to clarify image JSON
```

```
$ git diff v1.5.0-rc4 --stat
 CONTRIBUTING.md                                       |   2 +-
 Dockerfile                                            |   2 +-
 MAINTAINERS                                           | 514 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
 README.md                                             |   8 ++
 VERSION                                               |   2 +-
 daemon/graphdriver/devmapper/README.md                |   2 +-
 docs/Dockerfile                                       |  24 +++---
 docs/README.md                                        |   6 +-
 docs/man/Dockerfile.5.md                              |   4 +-
 docs/man/README.md                                    |  37 ---------
 docs/man/docker-attach.1.md                           |  20 ++---
 docs/man/docker-events.1.md                           |  26 +++---
 docs/man/docker-stats.1.md                            |   2 +
 docs/man/docker.1.md                                  |   2 +-
 docs/mkdocs-swarm.yml                                 |   2 +-
 docs/mkdocs.yml                                       |  16 ++--
 docs/sources/articles/certificates.md                 |   2 +-
 docs/sources/articles/dockerfile_best-practices.md    |   2 +-
 docs/sources/articles/networking.md                   |   6 +-
 docs/sources/articles/systemd.md                      |   2 +-
 docs/sources/docker-hub/builds.md                     |  20 +++--
 docs/sources/docker-hub/repos.md                      |   8 +-
 docs/sources/installation/centos.md                   |  99 +++++++++++------------
 docs/sources/installation/fedora.md                   |  71 +++++++++--------
 docs/sources/installation/rhel.md                     |  73 +++++++++--------
 docs/sources/reference/api/docker_remote_api.md       |   2 +
 docs/sources/reference/api/docker_remote_api_v1.10.md |   1 +
 docs/sources/reference/api/docker_remote_api_v1.11.md |   1 +
 docs/sources/reference/api/docker_remote_api_v1.12.md |   1 +
 docs/sources/reference/api/docker_remote_api_v1.13.md |   1 +
 docs/sources/reference/api/docker_remote_api_v1.14.md |   1 +
 docs/sources/reference/api/docker_remote_api_v1.15.md |   1 +
 docs/sources/reference/api/docker_remote_api_v1.16.md |   1 +
 docs/sources/reference/api/docker_remote_api_v1.17.md |   3 +
 docs/sources/reference/api/docker_remote_api_v1.3.md  |   1 +
 docs/sources/reference/api/docker_remote_api_v1.4.md  |   1 +
 docs/sources/reference/api/docker_remote_api_v1.5.md  |   1 +
 docs/sources/reference/api/docker_remote_api_v1.6.md  |   1 +
 docs/sources/reference/api/docker_remote_api_v1.7.md  |   1 +
 docs/sources/reference/api/docker_remote_api_v1.8.md  |   1 +
 docs/sources/reference/api/docker_remote_api_v1.9.md  |   1 +
 docs/sources/reference/builder.md                     |  18 ++---
 docs/sources/reference/commandline/cli.md             |  99 +++++++++++++++--------
 docs/sources/release-notes.md                         | 103 +++++++++---------------
 docs/sources/userguide/dockerimages.md                |   2 +-
 docs/sources/userguide/dockerlinks.md                 |   2 +-
 docs/sources/userguide/dockervolumes.md               |   2 +-
 image/spec/v1.md                                      |   2 +-
 project/MAINTAINERS.md                                | 147 ----------------------------------
 49 files changed, 859 insertions(+), 487 deletions(-)
```

**Comment by burke** [comment]
We've been running these RCs on several production nodes for over a week with no issues.

**Comment by Starefossen** [comment]
This was due a day ago. We want Docker 1.5 :whale: :rocket: 

screen shot 2015-02-10 at 16 16 50

**Comment by jfrazelle** [comment]
We are releasing today :)

**Comment by icecrime** [comment]
Final binaries are up:

> **Ubuntu/Debian:** https://test.docker.com/ubuntu or curl -sSL https://test.docker.com/ | sh
> **Linux 64bit binary:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0
> **Darwin/OSX 64bit client binary:** https://test.docker.com/builds/Darwin/x86_64/docker-1.5.0
> **Darwin/OSX 32bit client binary:** https://test.docker.com/builds/Darwin/i386/docker-1.5.0
> **Linux 64bit tgz:** https://test.docker.com/builds/Linux/x86_64/docker-1.5.0.tgz

Commit id should be `a8a31ef`. Please LGTM the PR and I'll push to https://get.docker.com.

**Comment by jfrazelle** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by thaJeztah** [comment]
W00t! Thanks, everyone. @icecrime you did a great job managing this release, much appreciated!

**Pull request merged**
