### PR TITLE
Dockerfile: make static binary target simpler to consume

### PR DESCRIPTION
**Pull request by tiborvass**
This way, one can build a static docker with this one-liner:

```
docker build -o bin/ --target binary --build-arg DOCKERCLI_VERSION=19.03.5 .
```

Signed-off-by: Tibor Vass <tibor@docker.com>

PTAL @cpuguy83 @seemethere @tonistiigi @arkodg if you think this would need pipeline script adjustments, let me know.

TODO: dynamic, and cross.

### CODE REVIEW

**Comment by cpuguy83** [comment]
SGTM

**Comment by cpuguy83** [comment]
Same for dynbinary.

**Review by seemethere — APPROVED** [review]

**Comment by tiborvass** [comment]
@cpuguy83 so dynbinary only had dynamic dockerd on master and no other binaries. Is that expected?

**Comment by cpuguy83** [comment]
Hmm, possibly it is expected since dockerd is the only thing that's dynamic.
Probably the dynbinary target is not very useful except for testing that `hack/make.sh dynbinary` works.

**Pull request closed without merging**
