### PR TITLE
add: best practice for security when sharing host directories.

### PR DESCRIPTION
**Pull request by moxiegirl**
Closes and carries PR #15210

Signed-off-by: Mary Anthony mary@docker.com

### CODE REVIEW

**Comment by SvenDowideit** [comment]
LGTM, though I'd love us to go back to using 80 char line wrapping, so that diffs work out better.

**Comment by thaJeztah** [comment]
Not LGTM; I think *"Sometimes actions on the host's source directory ..."* is too generic to understand what is meant here. I think this is an issue that's quite easy to get "bit" by, and only requires a user on the host to move a directory that happened to be in a (bind-)mount. (For example, anti-virus software that "quarantines" a directory would be sufficient to give a container full access to the hosts filesystem)

I'm not sure what wording we should use, but I'll draft up an example in a bit that may help to understand what we should warn for.

**Comment by thaJeztah** [comment]
Running out of time, I'll need to head off now, will add the example tonight :blush:

**Comment by thaJeztah** [comment]
Ok, here's the example I wanted to add. I hope it's clear enough to explain the problem we  need to describe to prevent people shooting themselves in the foot.

Prepare;

    mkdir -p ~/example/my-mount/subdir

    cd example

    touch this-is-outside-the-volume


You should now have this tree;

    ├── my-mount
    │   └── subdir
    └── this-is-outside-the-volume


In a *separate* shell; start a container, using "my-mount" as a bind-mounted volume

    cd ~/example

    docker run -it --rm -v $(pwd)/my-mount:/my-mount ubuntu

In the container, cd to the "subdir"

    root@5b9194731d0f:/# cd /my-mount/subdir/
    root@5b9194731d0f:/my-mount/subdir#


In the other shell, move "subdir" outside of "my-mount". *This* is what's causing the
problem; note that it's not a bug in "Docker", it's a known issue with the way
mounts work, but it's easy to get in this situation without knowing (just by moving a directory). Also see https://github.com/docker/docker/issues/12317#issuecomment-92692061, and http://lists.linuxfoundation.org/pipermail/containers/2015-April/035788.html

    mv my-mount/subdir/ ./

The tree (on the host) now looks like this;

    ├── my-mount
    ├── subdir
    └── this-is-outside-the-volume

*Inside the container*, move 1 directory "up";

    root@5b9194731d0f:/my-mount/subdir# cd ../

Look at the path(!)

    root@5b9194731d0f:/my-mount/home/sebastiaan/example#

We're now outside the mount-dir!

    root@5b9194731d0f:/my-mount/home/sebastiaan/example# ls
    my-mount  subdir  this-is-outside-the-volume


And we have full access the hosts filesystem

    root@5b9194731d0f:/my-mount/home/sebastiaan/example# cd ../../../
    root@5b9194731d0f:/my-mount# ls
    Users  boot  etc   initrd.img      lib    lost+found  mnt  proc  run   srv       sys   tmp  var      vmlinuz.old
    bin    dev   home  initrd.img.old  lib64  media       opt  root  sbin  swapfile  test  usr  vmlinuz

**Comment by moxiegirl** [comment]
@thaJeztah Seb this is a huge example to add for something that isn't technically a Docker issue.  And, from the way I read it @ewindisch on the original issue felt this was an edge case --- a user needs access to both the host and the container *and* have malicious intent.  Adding a large example implies this is somehow our issue rather than, as you say, a known problem with bind mount.  I'd rather just link to the bind mount patch discussion you provide.

Let me see what @NathanMcCauley another security guy says.

**Comment by thaJeztah** [comment]
@moxiegirl oh! not my intent to add the example; I provided the example to try and explain the problem to you; basically, the only thing needed to end up in this situation is to inadvertently move a directory on the host (either manually, e.g. by moving a directory to the trash, or by some software moving the directory (anti virus?)

It doesn't have to be bad intent; but, yes, it needs to happen on the host.

I think the description should be slightly clearer than "sometimes, actions on the host..."; because that doesn't give me (as a user) an indication *what* actions I should avoid (and on which files/directories)

**Comment by moxiegirl** [comment]
@thaJeztah ah, gotcha. Sorted. See if you like the result.

**Comment by thaJeztah** [comment]
Thanks @moxiegirl, already much better (you're gonna hate me :heart:); the user only needs access to the host and the mounted directories; root access and/or access to the docker socket is not required (also see https://github.com/docker/docker/pull/15210#issuecomment-128266134).

Apologies for that, I should've mentioned that more clearly; drinks on me next time we meet?

**Comment by moxiegirl** [comment]
@thaJeztah :person_frowning: darn...that should do it.

**Comment by thaJeztah** [comment]
Yeah!! LGTM thanks for bearing 🐻🐻 with me, Mary

🍷🍸🍼🍻🍺☕️🍹

**Pull request merged**
