### PR TITLE
content trust: add more robust DCT pull tests

### PR DESCRIPTION
**Pull request by riyazdf**
Adds a couple of cases to the Docker Content Trust pull tests:
- ensure `latest` is the default tag
- when pulling with DCT, ensure that we resolve the correct digest from notary and pull the signed image instead of any unsigned ones

cc @andrewhsu 

Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

### CODE REVIEW

**Comment by dnephin** [comment]
Could these be unit tests in `docker/cli` ?

**Comment by riyazdf** [comment]
@dnephin: as discussed, these would totally make sense as e2e tests in docker/cli and can be folded into docker/cli#607 once the framework is set up.

**Comment by riyazdf** [comment]
superseded by https://github.com/docker/cli/pull/607

**Comment by thaJeztah** [comment]
Are there any tests that we should remove here, and move to the docker/cli repository (to keep them in a single location?)

**Pull request closed without merging**
