### PR TITLE
Record PID of exec'd process.

### LINKED ISSUE #18635: How do I get PID of exec'd process?
Looking though [the code](https://github.com/docker/docker/blob/master/daemon/exec.go#L252), docker doesn't seem to store and return the PID of an exec'd process anywhere.  Is my reading of the code right?

Would it be possible to add this to the [exec.Config](https://github.com/docker/docker/blob/master/daemon/exec/exec.go#L16) struct?  I'm happy to put together a PR.

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #18635 

Example:

```
root@7b9cc5889e76:/go/src/github.com/docker/docker# echo -e "GET /exec/7cef454771d3771e5b10dea5644934611baf0d9d1d3a6d64039f72abcedd8f66/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Content-Type: application/json
Server: Docker/1.10.0-dev (linux)
Date: Tue, 05 Jan 2016 17:20:13 GMT
Content-Length: 377

{
    "CanRemove": false,
    "ContainerID": "ae0218d93d8b2a2003630e22ab2b464d5284897063b7212fb621b12e5c9e5366",
    "DetachKeys": "",
    "ExitCode": 0,
    "ID": "7cef454771d3771e5b10dea5644934611baf0d9d1d3a6d64039f72abcedd8f66",
    "OpenStderr": true,
    "OpenStdin": true,
    "OpenStdout": true,
    "PID": 1934,
    "ProcessConfig": {
        "arguments": [],
        "entrypoint": "/bin/sh",
        "privileged": false,
        "tty": true,
        "user": ""
    },
    "Running": true
}
root@7b9cc5889e76:/go/src/github.com/docker/docker# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      1940  0.0  0.1  18168  3368 ?        Ss   17:18   0:00 bash
root      1980  0.0  0.1  15568  2096 ?        R+   17:20   0:00  \_ ps auxf
root      1891  0.0  0.1  18168  3376 ?        Ss   17:16   0:00 bash
root      1924  0.0  1.3 291188 28388 ?        Sl+  17:17   0:00  \_ docker exec -ti ae0218d93d8b /bin/sh
root         1  0.0  0.1  18168  3364 pts/1    Ss   16:45   0:00 /bin/bash
root      1846  0.3  1.9 532364 40644 pts/1    Sl+  17:16   0:00 docker daemon -D
root      1915  0.0  0.0   1520     4 pts/0    Ss+  17:17   0:00  \_ /bin/sh
root      1934  0.0  0.0   1520     4 pts/1    Ss+  17:17   0:00  \_ /bin/sh
```

### CODE REVIEW

**Comment by tomwilkie** [comment]
@thaJeztah sorry this took so long - let me know what you think!

**Comment by tomwilkie** [comment]
(Added dco)

**Comment by thaJeztah** [comment]
Thanks @tomwilkie!

/cc @calavera, who wasn't entirely sure yet: https://github.com/docker/docker/issues/18635#issuecomment-166382620 :smile:

**Comment by tomwilkie** [comment]
(The jenkins failure seem unrelated)

ping @calavera?

**Comment by calavera** [comment]
changes LGTM, but can we have a test for the api? This will also require changes in documentation.

**Comment by tomwilkie** [comment]
Roger that, I'll get right on it.

**Comment by tomwilkie** [comment]
(I'm still working on the tests...)

**Comment by calavera** [comment]
It looks like that test case doesn't compile :pensive: 
```
03:49:40 # github.com/docker/docker/integration-cli
03:49:40 ./docker_api_exec_test.go:75: execJSON.ID undefined (type struct { PID int } has no field or method ID)
```

**Comment by tomwilkie** [comment]
Yes sorry I had to travel to sf at short notice. Will try and get this
fixed tomorrow!

**Comment by jfrazelle** [comment]
test is failing:
```
23:14:49 PASS: docker_cli_exec_test.go:22: DockerSuite.TestExec	0.405s
23:14:50 
23:14:50 ----------------------------------------------------------------------
23:14:50 FAIL: docker_api_exec_test.go:66: DockerSuite.TestExecAPIStart
23:14:50 
23:14:50 docker_api_exec_test.go:75:
23:14:50     c.Assert(execJSON.PID, checker.Not(checker.Equals), 0)
23:14:50 ... obtained int = 0
23:14:50 ... expected int = 0
23:14:50 
23:14:51 
23:14:51 ---------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
ping @tomwilkie I'm closing this PR for now, let us know when have time, then I can re-open before you push

**Pull request closed without merging**
