### PR TITLE
devmapper: Fix a bug and fix a comment and add one reliability check

### LINKED ISSUE #16682: devicemapper: Fix couple of bugs and code cleanup
Fix a bug where we are trying to load even transaction metadata file into hash map which is supposed to contain only devices.

Also couple of comments are wrong on externally visible functions. Fix those.

During device deletion, it is assumed that higher layers have done Get()/Put() properly. Put a check to ensure that. If that's not done, device deletion will fail. This will ensure that any higher level code errors are caught.

### PR DESCRIPTION
**Pull request by rhvgoyal**
Fixes #16682

### CODE REVIEW

**Comment by rhvgoyal** [comment]
CC @LK4D4 @calavera @vbatts @rhatdan

**Comment by LK4D4** [comment]
Code LGTM
waiting for CI

**Comment by LK4D4** [comment]
I saw that janky passed :D

**Comment by rhvgoyal** [comment]
@LK4D4 

So can I generate a PR without having created an issue?

Also I don't understand why janky and experimental have failed. Can't see anything obvious which points to my patches.

**Comment by LK4D4** [comment]
@rhvgoyal Yup, you can.
It's jenkins problems, seems like it's restarting now.

**Comment by calavera** [comment]
do we really need three commits to fix two things? :pensive:

**Comment by rhvgoyal** [comment]
@calavera Does this new title of PR sounds better?

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
Janky is failing with an unrelated error. Merging.

**Pull request merged**
