### PR TITLE
Windows CI: Unit Test move Unix specific struct field tests to _unix.go

### PR DESCRIPTION
**Pull request by darstahl**
Fixes daemon unit tests on Windows by moving stuff that doesn't compile to daemon_unix_test.go

Seal

Signed-off-by: Darren Stahl darst@microsoft.com

### CODE REVIEW

**Comment by icecrime** [comment]
Some compilation issues:

```
01:59:59 # github.com/docker/docker/docker
01:59:59 docker/daemon_unix_test.go:50: undefined: opts in opts.NewNamedMapOpts
01:59:59 docker/daemon_unix_test.go:51: undefined: opts in opts.NewNamedMapOpts
```

**Comment by darrenstahlmsft** [comment]
Yep, got em. I think.

**Comment by icecrime** [comment]
Ping @cpuguy83: failure in [win2lin](https://jenkins.dockerproject.org/job/Docker-PRs-Win2Lin/22533/console) _after_ #20792 was merged :cry: 

```
19:09:09 FAIL: docker_cli_stats_test.go:98: DockerSuite.TestStatsAllNewContainersAdded
19:09:09 
19:09:09 docker_cli_stats_test.go:132:
19:09:09     c.Fatal("failed to observe new container created added to stats")
19:09:09 ... Error: failed to observe new container created added to stats
```

Ping @tiborvass @thaJeztah: flaky test in [windowsTP4](https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/1819/console)?

```
03:56:16 docker_cli_ps_test.go:500:
03:56:16     c.Assert(ids, checker.HasLen, 2, check.Commentf("Should be 2 zero exited containers got %d: %s", len(ids), out))
03:56:16 ... obtained []string = []string{"cf4d23df9ffbd06b7007625c3a34833754d1d66d5e12545111f3450062ff333c", "3eb680c32e7a33355b08a018a3127b23515bbe12d4b09b2e849fd73f66eca871", "35c3130505c6930db84721e132780b331d1d81747e03932e57fd89185069c443"}
03:56:16 ... n int = 2
03:56:16 ... Should be 2 zero exited containers got 3: cf4d23df9ffbd06b7007625c3a34833754d1d66d5e12545111f3450062ff333c
03:56:16 3eb680c32e7a33355b08a018a3127b23515bbe12d4b09b2e849fd73f66eca871
03:56:16 35c3130505c6930db84721e132780b331d1d81747e03932e57fd89185069c443
```

**Comment by jhowardmsft** [comment]
@thaJeztah That TP4 error is unrelated - fails 1 in 7 or 8 runs, but never locally. Still investigating why. I don't think win2lin failure is related though. Can someone !rebuild - not in front of a computer where I can do that from.

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
