### PR TITLE
Update RHEL/Centos/Fedora installation docs

### LINKED ISSUE #14365: Drop support for RHEL6/CentOS6
# Description

Current state of things:

- Those distros are supported as per http://docs.docker.com/installation/rhel/and http://docs.docker.com/installation/centos/
- RedHat themselves only support Docker on RHEL7 (as stated by https://access.redhat.com/solutions/1378023, and confirmed by several people)
- 1.7.0 is broken on these (most notably because of libnetwork bridge creation code: https://github.com/docker/docker/issues/14024)

We shipped 1.7.0 without mentioning we would break compatibility, so this will be fixed in 1.7.1, but **we will drop support in 1.8.0**.

# How to

- [ ] Documentation update
- [ ] Consider making `--userland-proxy=false` a default?
- [ ] Drop older kernel compatibility code (cf. bridge creation fallback, there's probably more)

# References

- #14174
- RedHat [support ticket](https://access.redhat.com/solutions/1378023)

Ping @moxiegirl @thaJeztah to anticipate documentation change and spread the words on related issues / PRs!

### PR DESCRIPTION
**Pull request by icecrime**
Remove mentions of older systems.

Fixes #14365.

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ill rebase my other docs pr after ;)

**Comment by tiborvass** [comment]
LGTM

**Comment by calavera** [comment]
:metal: 

/cc @thaJeztah, @moxiegirl

**Comment by thaJeztah** [comment]
LGTM

ping @moxiegirl these documents will see a major rewrite in https://github.com/docker/docker/pull/14638; additional reviewing (if needed) can take place in that PR

**Comment by moxiegirl** [comment]
LGTM

**Pull request merged**
