### PR TITLE
Trim quotes from tls flag values

### LINKED ISSUE #29761: docker 1.13.0 CLI seems to break previous flag parsing behavior
```console
$ docker-machine config default
--tlsverify
--tlscacert="/Users/nathanleclaire/.docker/machine/certs/ca.pem"
--tlscert="/Users/nathanleclaire/.docker/machine/certs/cert.pem"
--tlskey="/Users/nathanleclaire/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.100:2376

$ docker $(docker-machine config default) version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

$ docker-machine config default
--tlsverify
--tlscacert="/Users/nathanleclaire/.docker/machine/certs/ca.pem"
--tlscert="/Users/nathanleclaire/.docker/machine/certs/cert.pem"
--tlskey="/Users/nathanleclaire/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.100:2376

$ docker $(docker-machine config default) version
could not read CA certificate "\"/Users/nathanleclaire/.docker/machine/certs/ca.pem\"": open "/Users/nathanleclaire/.docker/machine/certs/ca.pem": no such file or directory

$ docker --version
Docker version 1.13.0-rc4, build 88862e7
```

I'm not sure what's going on but this used to work before.  Any ideas @thaJeztah ?

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #29761

cc @thaJeztah , @nathanleclaire

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Nice.  Appreciate this Dan.  I will try it out with `docker-machine` to make sure it works OK.  For what it's worth you might want to add a comment somewhere in this code to link to the https://github.com/docker/docker/issues/29761 to explain the motivations for the new type.

**Comment by nathanleclaire** [comment]
Tested and LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
