### PR TITLE
Vendor libnetwork

### PR DESCRIPTION
**Pull request by fcrisciani**
Details:
- DSR support for linux https://github.com/docker/libnetwork/pull/2270
- increase max DNS pending query from 100->1024 https://github.com/docker/libnetwork/pull/2262
- DNs to handle NXDOMAIN, REFUSED https://github.com/docker/libnetwork/pull/2171

Full diff:
https://github.com/docker/libnetwork/compare/20461b8539336a4b5fcf551a86dd24ebae211984...d7b61745d16675c9f548b19f06fda80d422a74f0

Signed-off-by: Flavio Crisciani <flavio.crisciani@docker.com>

### CODE REVIEW

**Comment by fcrisciani** [comment]
cc @thaJeztah @ctelfer

**Review by ctelfer — APPROVED** [review]
LGTM fwiw

**Comment by fcrisciani** [comment]
ping @thaJeztah @vdemeester

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
fixes https://github.com/docker/libnetwork/issues/2214

**Pull request merged**
