### PR TITLE
Need -lpthread to compile Notary

### PR DESCRIPTION
**Pull request by brahmaroutu**
Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by duglin** [comment]
LGTM no need to wait for janky since this will only impact s390x builds.

**Comment by MHBauer** [comment]
LGTM GO GCCGO

**Comment by thaJeztah** [comment]
ping @duglin @brahmaroutu do you want this cherry-picked into the 1.10 release branch?

**Comment by duglin** [comment]
I think we just care about master at this point, but I'll let @brahmaroutu make the final decision.

**Comment by brahmaroutu** [comment]
@thaJeztah I am fine with master compilations as @duglin said, no need to pick it for 1.10.

**Comment by thaJeztah** [comment]
Alright, no cherry-pick then, thanks!

**Pull request merged**
