### PR TITLE
Fix cross compilation in Jenkinsfile

### PR DESCRIPTION
**Pull request by thaJeztah**
This is the first commit from https://github.com/moby/moby/pull/42524

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tianon @estesp ptal

had to carry that first commit, otherwise Jenkins wouldn't pick up the change

(failure is unrelated)

**Review by estesp — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Failures are `TestParallel1` / `TestParallel2` / `TestParallel3` looks like they became more flaky with Go 1.16; https://github.com/moby/moby/pull/40353#issuecomment-856312909. I opened https://github.com/moby/moby/issues/42553 to track

**Comment by thaJeztah** [comment]
I'll go ahead and merge this one, as it only changes the Jenkinsfile, not our code, the failure is unrelated, and this commit is a carry of one in https://github.com/moby/moby/pull/42524 (but can't LGTM my "own" PR's)

**Pull request merged**
