### PR TITLE
Add a 'docker create' + 'docker rm' testcase

### PR DESCRIPTION
**Pull request by duglin**
Per @thaJeztah's comment here: https://github.com/docker/docker/pull/13367#issuecomment-104286651
I couldn't find an existing test that covered this.

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
:heart: you were faster creating the test, than me finding what is currently there and commenting :D

**Comment by duglin** [comment]
When you have fairly nice testing infrastructure it makes it quick-n-easy.  :-)

**Comment by runcom** [comment]
LGTM if janky's happy

**Comment by calavera** [comment]
code LGTM, waiting for the windows build to pass before merging.

**Pull request merged**
