### PR TITLE
Fixes apparmor regression

### LINKED ISSUE #10363: master and lxc execdriver
This is a regression from 1.4.1

When using master docker and lxc I keep getting this error w apparmor:
```
libsqlite3-dev 	mercurial 	parallel 	python-mock 	python-pip 	python-websocket 	reprepro 	ruby1.9.1 	ruby1.9.1-dev 	s3cmd=1.1.0* 	--no-install-recommends
 ---> Running in 48b44d7ac610
[91mlxc-start: lsm/apparmor.c: apparmor_process_label_set: 153 Permission denied - failed to change apparmor profile to .AppArmorProfile
[0m[91mlxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 4
[0m[91mlxc-start: start.c: __lxc_start: 1080 failed to spawn '48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42'
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 518 call to cgmanager_remove_sync failed: invalid request
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 520 Error removing hugetlb:lxc/48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 518 call to cgmanager_remove_sync failed: invalid request
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 520 Error removing perf_event:lxc/48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 518 call to cgmanager_remove_sync failed: invalid request
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 520 Error removing name=butts:lxc/48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 518 call to cgmanager_remove_sync failed: invalid request
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 520 Error removing blkio:lxc/48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 518 call to cgmanager_remove_sync failed: invalid request
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 520 Error removing freezer:lxc/48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 518 call to cgmanager_remove_sync failed: invalid request
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 520 Error removing devices:lxc/48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 518 call to cgmanager_remove_sync failed: invalid request
[0m[91mlxc-start: cgmanager.c: cgm_remove_cgroup: 520 Error removing memory:lxc/48b44d7ac6102fc7831fa4c96e0521290d13ec5d64331a38ce208e4aefc08c42
[0m[91mlxc-start: lxc_start.c: main: 342 The container failed to start.
[0m[91mlxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options.
[0mRemoving intermediate container 48b44d7ac610
```
where as if I just swap out the binary with the 1.4.1 binary I have no error....

So did the apparmor config change? is it something with the lxc changes?

ping @ashahab-altiscale @crosbymichael

### PR DESCRIPTION
**Pull request by ashahab-altiscale**
Added nullcheck to appArmorProfile, and added test.

Signed-off-by: Abin Shahab ashahab@altiscale.com (github: ashahab-altiscale)

Fixes #10363

### CODE REVIEW

**Comment by jfrazelle** [comment]
Can you please sign your commits following these rules:

https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

The easiest way to do this is to amend the last commit:

`git commit --amend -s --no-edit && git push -f`

**Comment by jfrazelle** [comment]
weird the bot never likes your sig, but drone does sorry

**Comment by jfrazelle** [comment]
I'll try this out thanks!

**Comment by jfrazelle** [comment]
wooooohoo this fixes it and just to prove it I replaced the binary on the lxc jenkins server with one I build from this pr and ran the tests https://jenkins.dockerproject.com/job/LXC%20PR%20Test/label=ubuntu-aufs-lxc/18/console

LGTM
ping @crosbymichael

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
