### PR TITLE
Move package cliconfig to cli/config

### PR DESCRIPTION
**Pull request by vdemeester**
I felt it made more sence 👼. This is probably a completely useless change, but `cliconfig` just after `cli` package bothered me 😅.

/cc @thaJeztah @dnephin @icecrime @tiborvass @cpuguy83 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM, but perhaps best to wait with merge until 1.13 cherry picking has completed

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by tiborvass** [comment]
@vdemeester needs rebase

**Comment by vdemeester** [comment]
Rebased :angel:

**Comment by vdemeester** [comment]
re-rebased 😅

**Pull request merged**
