### PR TITLE
Fsync layer metadata on creation

### PR DESCRIPTION
**Pull request by mike-sul**
This is the band aid to address issue #42964.

Fsync the link and lower layer files immediately after writing to ensure that their content is stored on persistent storage. This helps to address the issue that arises when image layer downloads or extractions are interrupted due to a power cut.

The Docker daemon can recover if the interrupted layer is "broken," but it cannot recover if two or more lower layers to the interrupted layers are "broken." The suggested fix ensures that the lower layers, which have been fully downloaded and extracted, remain consistent even if the current top layer is broken.

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by corhere — CHANGES_REQUESTED** [review]
There is a lot more nuance to atomically writing a file than simply calling fsync. If the power is cut after the file is written but before it is `fsync`'ed, the file may exist as an empty file upon reboot. Please use [`ioutils.AtomicWriteFile`](https://pkg.go.dev/github.com/docker/docker/pkg/ioutils#AtomicWriteFile) or similar instead of rolling your own. As it looks like the files are being written to a newly-created directory, [`ioutils.AtomicWriteSet`](https://pkg.go.dev/github.com/docker/docker/pkg/ioutils#AtomicWriteSet) may be an even better choice as it ensures that the whole directory is created atomically with all its contents.

**Comment by mike-sul** [comment]
> There is a lot more nuance to atomically writing a file than simply calling fsync. If the power is cut after the file is written but before it is `fsync`'ed, the file may exist as an empty file upon reboot. Please use [`ioutils.AtomicWriteFile`](https://pkg.go.dev/github.com/docker/docker/pkg/ioutils#AtomicWriteFile) or similar instead of rolling your own. As it looks like the files are being written to a newly-created directory, [`ioutils.AtomicWriteSet`](https://pkg.go.dev/github.com/docker/docker/pkg/ioutils#AtomicWriteSet) may be an even better choice as it ensures that the whole directory is created atomically with all its contents.

Sure, that's the right way to persist file data safely.

I've just posted [the original patch](https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-base/recipes-containers/docker/files/0001-overlay2-fsync-layer-metadata-files.patch) for dockerd in this PR for [LmP](https://github.com/foundriesio/lmp-manifest) (meta-lmp). One of the requirements for the patch was to minimize interference with the Docker code, so the patch simply extends the original code. Additionally, the probability of a power cut occurring exactly between the two moments (write and sync) is very low, which is why the patch has been working for us all this time.

Since this is a pull request rather than just a patch, it makes sense to do it correctly, as you suggested.

It's great idea to make use of `AtomicWriteSet` for the overall directory.

Unfortunately, it doesn't allow setting permissions "atomically" as `AtomicWriteFile` does.
I suppose I can do something similar to what is done [here](https://github.com/moby/moby/blob/49b55b220ee76a5b4e03db138ea2ac74b3e5b74e/layer/filestore.go#L68). For example, create a tmp dir by a caller, set its permissions (setPermissions) and then invoke `NewAtomicWriteSet`.

In addition to that, there is another similar issue in the "overlay" part of the code that we [patched](https://github.com/foundriesio/meta-lmp/blob/2b48e5bc0922f03e8793ea3c97c3e02d61e0e8ba/meta-lmp-base/recipes-containers/docker/files/0001-Fsync-layer-once-extracted-to-file-system.patch#L33). I am wondering if it would be better to apply similar approach (write to tmp dir, then rename) around this [code](https://github.com/moby/moby/blob/49b55b220ee76a5b4e03db138ea2ac74b3e5b74e/daemon/graphdriver/overlay2/overlay.go#L681).

The question is whether it will help to make the [overall process of the layer unpacking](https://github.com/moby/moby/blob/49b55b220ee76a5b4e03db138ea2ac74b3e5b74e/layer/layer_store.go#L271) atomic. The `s.store.StartTransaction()` guarantees that the "image/overlay2/" part is written atomically, the changes that are being considered in this PR can assure that the "overlay2/<>" part is written atomically, but nothing ensures consistency between those two parts...

**Comment by corhere** [comment]
> It's great idea to make use of `AtomicWriteSet` for the overall directory.
> 
> Unfortunately, it doesn't allow setting permissions "atomically" as `AtomicWriteFile` does.

`AtomicWriteSet` allows you to set the mode of the files within the set just like `AtomicWriteFile` does, just not the file mode of the directory itself.

> I suppose I can do something similar to what is done [here](https://github.com/moby/moby/blob/49b55b220ee76a5b4e03db138ea2ac74b3e5b74e/layer/filestore.go#L68). For example, create a tmp dir by a caller, set its permissions (setPermissions) and then invoke `NewAtomicWriteSet`.

That isn't doing what you think it is. The directory passed to `NewAtomicWriteSet` is used as the _parent_ directory of the created temporary directory, so what you propose will not have any effect on the permissions of the committed directory.

What you could do is extend `ioutils.AtomicWriteSet` to allow the directory's file mode to be set before (or while) committing.

> In addition to that, there is another similar issue in the "overlay" part of the code that we [patched](https://github.com/foundriesio/meta-lmp/blob/2b48e5bc0922f03e8793ea3c97c3e02d61e0e8ba/meta-lmp-base/recipes-containers/docker/files/0001-Fsync-layer-once-extracted-to-file-system.patch#L33). I am wondering if it would be better to apply similar approach (write to tmp dir, sync, and rename) around this [code](https://github.com/moby/moby/blob/49b55b220ee76a5b4e03db138ea2ac74b3e5b74e/daemon/graphdriver/overlay2/overlay.go#L681).

Yes it would be better to apply a similar approach as `AtomicWriteSet` to unpacking a layer. We would not be able to accept a PR which uses `syscall.Sync()` as it is such a blunt instrument which could have a severe performance impact on workloads in production servers with big fs caches and uninterruptible power supplies, but a more targeted `fsync` of just the unpacked files and directories may be more palatable.

**Comment by mike-sul** [comment]
I am closing this PR in favor of https://github.com/moby/moby/pull/46471.

**Pull request closed without merging**
