### PR TITLE
Improve Dockerfile.e2e

### PR DESCRIPTION
**Pull request by thaJeztah**
follow-up to https://github.com/moby/moby/pull/39115 (first commit is from that PR)

See individual commits for details

To test (if you're running on Docker 18.09 (API v1.39)):

```bash
docker build -t moby-e2e-test -f Dockerfile.e2e .

docker run -it --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e DOCKER_API_VERSION=1.39 \
  moby-e2e-test
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @vdemeester @cpuguy83 PTAL

**Comment by thaJeztah** [comment]
Looking at some weirdness when running these tests; looks like there might be a bug somewhere (not introduced in this PR)

**Comment by thaJeztah** [comment]
Added various fixes/skips for situations where this image is run against an older daemon

**Review by andrewhsu — APPROVED** [review]
LGTM

**Review by seemethere — APPROVED** [review]

**Comment by seemethere** [comment]
This actually fails for me when I try to run it locally:
```
 => ERROR [builder 2/3] RUN hack/make.sh build-integration-test-binary                          0.6s
------
 > [builder 2/3] RUN hack/make.sh build-integration-test-binary:
#32 0.488
#32 0.505 error: .git directory missing and DOCKER_GITCOMMIT not specified
#32 0.505   Please either build with the .git directory accessible, or specify the
#32 0.505   exact (--short) commit hash you are building using DOCKER_GITCOMMIT for
#32 0.505   future accountability in diagnosing build issues.  Thanks!
------
executor failed running [/bin/sh -c hack/make.sh build-integration-test-binary]: exit code: 1
```

**Comment by kolyshkin** [comment]
```
--- FAIL: TestUpdatePidsLimit (4.45s)
    --- FAIL: TestUpdatePidsLimit/update_from_none (0.47s)
        update_linux_test.go:154: failed to parse source file: /go/src/github.com/docker/docker/integration/container/update_linux_test.go: open /go/src/github.com/docker/docker/integration/container/update_linux_test.go: no such file or directory
```

(most probably the failure comes because I don't run it as root, I don't care)

It looks like test case sources should be copied to the final image, because stuff like `assert.Equal()` etc tries to parse (reflect) the source file in case of failure to print info about what kind of variable and what value is expected and what is provided, stuff like that.

**Comment by thaJeztah** [comment]
> It looks like test case sources should be copied to the final image, because stuff like assert.Equal() etc tries to parse (reflect) the source file in case of failure to print info about what kind of variable and what value is expected and what is provided, stuff like that.

Yes, I actually had a branch that does so, but I was in doubt to include that;

- the image size actually doubles
- I wanted to have a look at the gotest.tools repository to see if there's a way to make that reflecting/parsing _optional_ (in situations where the source code is not available)

**Comment by thaJeztah** [comment]
@kolyshkin LGTY?

**Review by kolyshkin — APPROVED** [review]
Yes, LGTM (I guess I can followup with gotest.tools stuff later)

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
