### PR TITLE
vendor: github.com/containerd/containerd v1.7.23, hcsshim v0.12.8

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to;

- https://github.com/containerd/containerd/pull/10712
- https://github.com/containerd/containerd/pull/10792

---

- [x] depends on https://github.com/moby/moby/pull/48750
- [x] depends on https://github.com/moby/moby/pull/48751
- [x] depends on https://github.com/moby/moby/pull/48753
- [x] depends on https://github.com/moby/moby/pull/48752
- [x] depends on https://github.com/moby/moby/pull/48757
- [x] depends on https://github.com/moby/moby/pull/48790

###  vendor: github.com/containerd/containerd v1.7.23, hcsshim v0.12.8

full diff:

- https://github.com/containerd/containerd/compare/v1.7.22...v1.7.23
- https://github.com/microsoft/hcsshim/compare/v0.12.7...v0.12.8

**- Description for the changelog**

```markdown changelog

```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
I first tried only updating containerd to see how bad it was, and lots of failures;

```
=== Failed
=== FAIL: amd64.integration-cli TestDockerAPISuite/TestAPIImagesSaveAndLoad (0.60s)
    docker_api_images_test.go:29: assertion failed: 
        Command:  /usr/local/cli-integration/docker rmi sha256:2b969b1d2ed33aba9a51be0e4a2b52681f9e6c9fec4b54f0bbacbe8083106952
        ExitCode: 1
        Error:    exit status 1
        Stdout:   
        Stderr:   Error response from daemon: error deleting lease: NotFound: lease "moby-image-sha256:2b969b1d2ed33aba9a51be0e4a2b52681f9e6c9fec4b54f0bbacbe8083106952": not found
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    --- FAIL: TestDockerAPISuite/TestAPIImagesSaveAndLoad (0.60s)

=== FAIL: amd64.integration-cli TestDockerAPISuite (95.97s)
```

```
=== FAIL: amd64.integration-cli TestDockerCLIBuildSuite/TestBuildSymlinkBasename (0.53s)
    docker_cli_build_test.go:4847: assertion failed: 
        Command:  /usr/local/cli-integration/docker run --rm testbuildbrokensymlink cat asymlink
        ExitCode: 1
        Error:    exit status 1
        Stdout:   
        Stderr:   cat: can't open 'asymlink': No such file or directory
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    --- FAIL: TestDockerCLIBuildSuite/TestBuildSymlinkBasename (0.53s)

=== FAIL: amd64.integration-cli TestDockerCLIBuildSuite/TestBuildUsernamespaceValidateRemappedRoot (0.52s)
    docker_cli_build_test.go:576: assertion failed: 
        Command:  /usr/local/cli-integration/docker rmi testbuildusernamespacevalidateremappedroot
        ExitCode: 1
        Error:    exit status 1
        Stdout:   
        Stderr:   Error response from daemon: error deleting lease: NotFound: lease "moby-image-sha256:36cdba4dd38e737573d8479cf79623445d28cbd7fbac53e7865935efbf763e6f": not found
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
    --- FAIL: TestDockerCLIBuildSuite/TestBuildUsernamespaceValidateRemappedRoot (0.52s)
```

Now updating uses of the module to use the package again; this only changes uses locally, so not in (indirect) dependencies, so I expect those to no longer match the error-definitions, which can cause failures.

**Comment by thaJeztah** [comment]
Yeah, looks indeed that many tests are failing now, e.g.;

```
=== FAIL: frontend/dockerfile TestIntegration/TestFrontendDeduplicateSources/worker=dockerd/frontend=client (2.65s)
    dockerfile_provenance_test.go:1413: 
        	Error Trace:	/src/frontend/dockerfile/dockerfile_provenance_test.go:1413
        	            				/src/util/testutil/integration/run.go:97
        	            				/src/util/testutil/integration/run.go:211
        	Error:      	Received unexpected error:
        	            	NotFound: rpc error: code = NotFound desc = content digest sha256:09547cfe4df4ca03ddf33fa730d2d758140ca0f9b99f554a4004a4d08be146be: not found
        	Test:       	TestIntegration/TestFrontendDeduplicateSources/worker=dockerd/frontend=client

=== FAIL: frontend/dockerfile TestIntegration/TestFrontendDeduplicateSources/worker=dockerd/frontend=builtin (2.60s)
    dockerfile_provenance_test.go:1413: 
        	Error Trace:	/src/frontend/dockerfile/dockerfile_provenance_test.go:1413
        	            				/src/util/testutil/integration/run.go:97
        	            				/src/util/testutil/integration/run.go:211
        	Error:      	Received unexpected error:
        	            	NotFound: rpc error: code = NotFound desc = content digest sha256:2aae6c4bb997db2d6c37c859c97cd192c09a6e321b875456085b2fc58abe83c2: not found
        	Test:       	TestIntegration/TestFrontendDeduplicateSources/worker=dockerd/frontend=builtin
```

```
sandbox.go:138: time="2024-09-24T08:25:34.012163151Z" level=error msg=/moby.buildkit.v1.Control/Solve error="rpc error: code = Internal desc = commit failed: blob with expected digest sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 exists: already exists" spanID=ae1fcca9dda5faaa traceID=bca305682a9e1c79ea6b4dbe909709d1
sandbox.go:138: Internal: commit failed: blob with expected digest sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 exists: already exists
sandbox.go:138: 6825  /usr/bin/dockerd --data-root /tmp/integration3966967826/dgwoniebauqg2/root --exec-root /tmp/dxr/dgwoniebauqg2 --pidfile /tmp/integration3966967826/dgwoniebauqg2/docker.pid --containerd-namespace dgwoniebauqg2 --containerd-plugins-namespace dgwoniebauqg2p --host unix:///tmp/docker-integration/dgwoniebauqg2.sock --config-file /tmp/integration3966967826/daemon.json --userland-proxy=false --tls=false --debug
sandbox.go:138: github.com/docker/docker/api/server/router/grpc.unaryInterceptor
sandbox.go:138: 	/go/src/github.com/docker/docker/api/server/router/grpc/grpc.go:74
sandbox.go:138: google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1
sandbox.go:138: 	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/server.go:1194
sandbox.go:138: github.com/moby/buildkit/api/services/control._Control_Solve_Handler
sandbox.go:138: 	/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/api/services/control/control.pb.go:2493
sandbox.go:138: google.golang.org/grpc.(*Server).processUnaryRPC
sandbox.go:138: 	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/server.go:1383
sandbox.go:138: google.golang.org/grpc.(*Server).handleStream
sandbox.go:138: 	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/server.go:1794
sandbox.go:138: google.golang.org/grpc.(*Server).serveStreams.func2.1
sandbox.go:138: 	/go/src/github.com/docker/docker/vendor/google.golang.org/grpc/server.go:1027
sandbox.go:138: runtime.goexit
sandbox.go:138: 	/usr/local/go/src/runtime/asm_amd64.s:1695
sandbox.go:138: 
sandbox.go:138: time="2024-09-24T08:25:34.012624135Z" level=debug msg="session finished: <nil>" spanID=05991962f11b5ba3 traceID=958bfcaf0130249e36e8889b2ee79551
```

This one also failing, although not immediately sure where this ties in to errors (it's consistently failing though);

```
=== FAIL: amd64.integration.build TestBuildkitHistoryTracePropagation (30.04s)
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] Channel created" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] original dial target is: \"unix:///run/buildkit/buildkitd.sock\"" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] parsed dial target is: resolver.Target{URL:url.URL{Scheme:\"unix\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"\", Path:\"/run/buildkit/buildkitd.sock\", RawPath:\"\", OmitHost:false, ForceQuery:false, RawQuery:\"\", Fragment:\"\", RawFragment:\"\"}}" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] Channel authority set to \"localhost\"" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] Resolver state updated: {\n  \"Addresses\": [\n    {\n      \"Addr\": \"/run/buildkit/buildkitd.sock\",\n      \"ServerName\": \"\",\n      \"Attributes\": {\n        \"\\u003c%!p(networktype.keyType=grpc.internal.transport.networktype)\\u003e\": \"unix\"\n      },\n      \"BalancerAttributes\": null,\n      \"Metadata\": null\n    }\n  ],\n  \"Endpoints\": [\n    {\n      \"Addresses\": [\n        {\n          \"Addr\": \"/run/buildkit/buildkitd.sock\",\n          \"ServerName\": \"\",\n          \"Attributes\": {\n            \"\\u003c%!p(networktype.keyType=grpc.internal.transport.networktype)\\u003e\": \"unix\"\n          },\n          \"BalancerAttributes\": null,\n          \"Metadata\": null\n        }\n      ],\n      \"Attributes\": null\n    }\n  ],\n  \"ServiceConfig\": null,\n  \"Attributes\": null\n} (resolver returned new addresses)" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] Channel switches to new LB policy \"pick_first\"" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel created" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] Channel Connectivity change to CONNECTING" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] Channel exiting idle mode" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel picks a new address \"/run/buildkit/buildkitd.sock\" to connect" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to READY" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Channel #1] Channel Connectivity change to READY" module=grpc
time="2024-09-24T08:28:33Z" level=info msg="[core] [Server #4] Server created" module=grpc
    build_traces_test.go:87: Waiting for trace to be available
    build_traces_test.go:88: timeout hit after 30s: trace not available yet
time="2024-09-24T08:29:03Z" level=info msg="[core] [Channel #1] Channel Connectivity change to SHUTDOWN" module=grpc
time="2024-09-24T08:29:03Z" level=info msg="[core] [Channel #1] Closing the name resolver" module=grpc
time="2024-09-24T08:29:03Z" level=info msg="[core] [Channel #1] ccBalancerWrapper: closing" module=grpc
time="2024-09-24T08:29:03Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to SHUTDOWN" module=grpc
time="2024-09-24T08:29:03Z" level=info msg="[core] [Channel #1 SubChannel #2] Subchannel deleted" module=grpc
time="2024-09-24T08:29:03Z" level=info msg="[core] [Channel #1] Channel deleted" module=grpc

```

**Comment by thaJeztah** [comment]
cc @dmcgowan

**Comment by thaJeztah** [comment]
OK, looks like we have one thing to address in hcsshim, because it doesn't compile;

```
# github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/oc
..\..\vendor\github.com\Microsoft\hcsshim\internal\oc\errors.go:21:39: undefined: errdefs.ToGRPC
```


https://github.com/moby/moby/blob/c9619248d04439c29fc10c19031bd3754e39b323/vendor/github.com/Microsoft/hcsshim/internal/oc/errors.go#L21

**Review by dmcgowan — APPROVED** [review]

**Review by austinvazquez — APPROVED** [review]
/lgtm

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
Looks like this was merged from an outdated vendor state that didn't have the `remotes/docker/config` package, and that package didn't get updated to 1.7.23; fixing in;

- https://github.com/moby/moby/pull/48826

**Pull request merged**
