### PR TITLE
Sort entries in pkg/namesgenerator

### PR DESCRIPTION
**Pull request by tlgs**
**- What I did**

Alphabetically sorted the entries of `pkg/namesgenerator`.

**- How I did it**

Dumped all of the names in plain text files and used `sort` and `diff` to find misplaced entries. 

**- How to verify it**

Easy enough to eyeball it; If you wanna be a nerd you can use something like `diff words.txt <(sort words.txt)`.

**- Description for the changelog**

Alphabetically sorted the adjectives and surnames in pkg/namesgenerator.

**- A picture of a cute animal (not mandatory but encouraged)**

<div align="center">
  Sepia Alpaca
</div>

### CODE REVIEW

**Comment by cpuguy83** [comment]
Thanks for this change, unfortunately we have decided to freeze this package.
See https://github.com/moby/moby/blob/952e1e62c5d7b326bf68cca2bb014b98e444be40/pkg/namesgenerator/names-generator.go#L3 for details.

This is a benign change that can at least help those who would like to find a name a little easier, so I'll leave this open for other maintainers to discuss, but IMHO I think we should just leave it as is.

**Comment by tlgs** [comment]
Yeah, I saw the notice and skimmed through a couple of the linked issues; I was hesitant to create the PR but I was doing something with the wordlist and my OCD got the best of me. ;)

As I wasn't adding or removing any content I thought I'd give it a go.

**Review by tianon — APPROVED** [review]
Seems pretty reasonable to me -- it's not _adding_ any new names, so IMO still within the spirit of our freeze on the package, and makes us all feel good about things being sorted correctly :sweat_smile:

**Comment by cpuguy83** [comment]
Seems reasonable.

**Review by cpuguy83 — APPROVED** [review]

**Review by samuelkarp — APPROVED** [review]

**Pull request merged**
