### PR TITLE
Add bash completion for new `docker image` command family

### PR DESCRIPTION
**Pull request by albers**
This is the second part of adding bash completion for #26025 (#27579 being the first one): `docker image *`.

Like in #27579, I created one commit for the pricipal flow of logic and subsequent ones that move the completion logic to the new homes. This was done so that the changes can be easily reviewed (as all the changes were applied to the same file, the overall diff is not very helpful).

One of the commits is special. From the commit message:

> In #23614 `docker inspect` was semantically enhanced to inspect "everything".
> Therefore moving its logic to `_docker_container_inspect` in #27579 was not correct.
> 
> This commit moves it back to its original top-level location (`_docker_inspect`) so that it can be called by `_docker_{container,image}_inspect` and others (will be added in follow-up PRs).
> Parameterization was added in order to get caller-specific behavior.

For the new command `docker image prune` I just added a stub. I'll implement it in a follow-up PR.

ping @thaJeztah @mlaventure @tianon

### CODE REVIEW

**Comment by mlaventure** [comment]
Testing this atm and I've stumbled into the following issue:

```
# docker  image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              trusty              1e0c3dd64ccd        11 days ago         188 MB
busybox             latest              e02e811dd08f        2 weeks ago         1.09 MB
debian              wheezy              517034637339        5 weeks ago         84.9 MB
# docker image history <TAB>
busybox         busybox:latest  debian          debian:wheezy   ubuntu          ubuntu:trusty   
# docker image history 
```
`ubuntu` and `debian` shouldn't be part of the output since I don't have `ubuntu:latest` and `debian:latest` in my image list.

**Comment by albers** [comment]
@mlaventure I did not change behavior here, and I also think it's correct, see:

    Usage:  docker images [OPTIONS] [REPOSITORY[:TAG]]

`ubuntu` is not short for `ubuntu:latest`. It is the repository name and stands for all images in the `ubuntu` repository, think of `ubuntu:*`.
The completion is a combined list of repository names and tagged images.

**Comment by mlaventure** [comment]
@albers in my example `ubuntu:latest` doesn't exist, so if i accept this completion the command fails.

It can be changed in a later PR, but I'd say the current behavior is incorrect as it causes the command to fail.

**Comment by albers** [comment]
@mlaventure Sorry, I didn't read your post properly, thought the problem was in `docker images`. 

I agree that the completion is wrong. `docker image history` expects an image as its argument. Completion lists repositories and tagged images, like in `docker images`.

As this is an existing bug, I suggest to fix it in a separate PR.
I will file a bug for this.

**Comment by mlaventure** [comment]
LGTM in that case, all my other tests passed.

 Thanks @albers !

**Review by tianon — APPROVED** [review]
:heart: :heart_eyes: LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Pull request merged**
