### PR TITLE
Add link to master docs.

### PR DESCRIPTION
**Pull request by jessfraz**
Docker-DCO-1.1-Signed-off-by: Jessica Frazelle jess@docker.com (github: jfrazelle)

### CODE REVIEW

**Comment by tianon** [comment]
You didn't want to switch to either `docs-master.dockerproject.com` or `master-docs.dockerproject.com` for `https://`? :angel:

**Comment by jfrazelle** [comment]
i like the double subdomain better i think if we get docker.org we can get the cert for both so like if swarm wanted to build out tools they could have swarm.master.docker.org etc etc etc

**Comment by jfrazelle** [comment]
its more intuitive to figure out the url this way

**Comment by SvenDowideit** [comment]
LGTM :}

**Pull request merged**
