### PR TITLE
Windows: escape entrypoint before passing to libcontainerd

### PR DESCRIPTION
**Pull request by jstarks**
This fixes a TODO that I introduced in the 1.11 release. Windows has always been incorrectly breaking the entry point into separate arguments (e.g. "echo hello" becomes "echo" "hello" before the process is launched), which is inconsistent with Linux behavior. This set of changes fixes a few tests that were depending on this behavior and then fixes the behavior itself.

cc/@jhowardmsft, @darrenstahlmsft

### CODE REVIEW

**Comment by thaJeztah** [comment]
@jstarks this is a bug fix for the 1.11 milestone?

**Comment by jstarks** [comment]
No, we thought it was best to leave 1.11 with the old behavior and fix this for 1.12.

**Comment by thaJeztah** [comment]
Clear, thanks!

**Comment by icecrime** [comment]
Something's wrong in tests:

```
19:19:57 FAIL: docker_cli_run_test.go:1901: DockerSuite.TestRunEntrypoint
19:19:57 
19:19:57 docker_cli_run_test.go:1908:
19:19:57     c.Fatalf("Output should be %q, actual out: %q", expected, out)
19:19:57 ... Error: Output should be "foobar", actual out: "foobar\n"
```

**Comment by mlaventure** [comment]
For the failing test, the `out` just need to be trimmed of spaces

**Comment by jstarks** [comment]
Thanks @icecrime. There were some additional test failures in windowsTP4, too; the latest push (hopefully) addresses everything.

**Comment by jstarks** [comment]
@mlaventure I just restored the "-n" argument to echo that I accidentally removed when I merged the Linux and Windows implementations of the tests. This will strip the \n.

**Comment by thaJeztah** [comment]
@jstarks did you push your changes? Seeing this failure on TP4 (not sure if it's related);

https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/3861/console

```
17:56:23 FAIL: docker_cli_run_test.go:325: DockerSuite.TestRunWithVolumesFromExited
17:56:23 
17:56:23 docker_cli_run_test.go:344:
17:56:23     out, exitCode = dockerCmd(c, "run", "--volumes-from", "test-data", WindowsBaseImage, `cmd /c type c:\some\dir\file`)
17:56:23 C:/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
17:56:23     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
17:56:23 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0822bfa00), Stderr:[]uint8(nil)} ("exit status 127")
17:56:23 ... "run --volumes-from test-data windowsservercore cmd /c type c:\some\dir\file" failed with errors: D:\CI\CI-74dae4e\binary\docker.exe: Error response from daemon: Container command 'cmd /c type c:\some\dir\file' not found or does not exist.
17:56:23 , exit status 127
17:56:23 
17:56:27 
17:56:27 ----------------------------------------------------------------------
```

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
