### PR TITLE
Remove hack MalformedHostHeaderOverride

### LINKED ISSUE #38745: Docker errors if stdin is not fully read
**Description**

Docker exits with an error is stdin is not fully consumed.

**Steps to reproduce the issue:**

Run

```
head -c 500000 /dev/zero | docker run --rm -i alpine:3.9 echo
```

**Describe the results you received:**

Docker exits with 1 and prints on stderr.

```
read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Describe the results you expected:**

Docker exists with 0 and does not print on stderr.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 17
 Running: 1
 Paused: 0
 Stopped: 16
Images: 173
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.4GiB
Name: paul
ID: NPIE:SKNR:RFN7:JYOG:B63X:WVNA:5M67:HRRR:4N7N:M6WH:K6KJ:ZLDX
Docker Root Dir: /var/lib/docker/1000.1000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Host is Ubuntu 18.04.

### PR DESCRIPTION
**Pull request by thaJeztah**
- closes https://github.com/moby/moby/pull/38928
- closes https://github.com/moby/moby/pull/39046
- fixes https://github.com/moby/moby/issues/38745

This hack was added to fix a compatibility with clients
that were built using Go 1.5 and older (added in 3d6f5984f52802fe2f4af0dd2296c9e2e4a1e003)

This hack causes some problems with current clients; with Go 1.5 and older
no longer being supported for some time, and being several years old, it
should now be ok to remove this hack altogether.

People using tools that are built with those versions of Go wouldn't have
updated those for years, and are probably out of date anyway; that's not
something we can continue taking into account.

This will affect docker clients (the docker cli) for docker 1.12 and older.
Those versions have reached EOL a long time ago (and have known unpatched
vulnerabilities), so should no longer be used anyway, but We should add
a nebtuib in the release notes, just in case someone, somewhere, still
has such old tools.

For those affected, using a more recent client (and if needed, setting
the DOCKER_API_VERSION environment variable to the needed API version)
should provide a way out.

This reverts the changes originally made in; #22000 and #22888,
which were to address #20865.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @lifubang @cpuguy83 @kolyshkin 

@runcom @ibuildthecloud FYI

**Comment by thaJeztah** [comment]
Wondering if this is flaky, or if those tests were written with the wrong assumption; https://jenkins.dockerproject.org/job/Docker-PRs/53783/console

Kicking CI once more

```
15:04:10 ___________________ AttachContainerTest.test_detach_with_arg ___________________
15:04:10 /docker-py/tests/integration/api_container_test.py:1330: in test_detach_with_arg
15:04:10     assert_cat_socket_detached_with_keys(sock, [ctrl_with('x')])
15:04:10 /docker-py/tests/helpers.py:124: in assert_cat_socket_detached_with_keys
15:04:10     sock.sendall(b'make sure the socket is closed\n')
15:04:10 E   Failed: DID NOT RAISE <class 'socket.error'>
15:04:10 _______________ AttachContainerTest.test_detach_with_config_file _______________
15:04:10 /docker-py/tests/integration/api_container_test.py:1313: in test_detach_with_config_file
15:04:10     assert_cat_socket_detached_with_keys(sock, [ctrl_with('p')])
15:04:10 /docker-py/tests/helpers.py:124: in assert_cat_socket_detached_with_keys
15:04:10     sock.sendall(b'make sure the socket is closed\n')
15:04:10 E   Failed: DID NOT RAISE <class 'socket.error'>
15:04:10 _________________ AttachContainerTest.test_detach_with_default _________________
15:04:10 /docker-py/tests/integration/api_container_test.py:1295: in test_detach_with_default
15:04:10     sock, [ctrl_with('p'), ctrl_with('q')]
15:04:10 /docker-py/tests/helpers.py:124: in assert_cat_socket_detached_with_keys
15:04:10     sock.sendall(b'make sure the socket is closed\n')
15:04:10 E   Failed: DID NOT RAISE <class 'socket.error'>
15:04:10 ________________________ ExecTest.test_detach_with_arg _________________________
15:04:10 /docker-py/tests/integration/api_exec_test.py:315: in test_detach_with_arg
15:04:10     assert_cat_socket_detached_with_keys(sock, [ctrl_with('x')])
15:04:10 /docker-py/tests/helpers.py:124: in assert_cat_socket_detached_with_keys
15:04:10     sock.sendall(b'make sure the socket is closed\n')
15:04:10 E   Failed: DID NOT RAISE <class 'socket.error'>
15:04:10 ____________________ ExecTest.test_detach_with_config_file _____________________
15:04:10 /docker-py/tests/integration/api_exec_test.py:297: in test_detach_with_config_file
15:04:10     assert_cat_socket_detached_with_keys(sock, [ctrl_with('p')])
15:04:10 /docker-py/tests/helpers.py:124: in assert_cat_socket_detached_with_keys
15:04:10     sock.sendall(b'make sure the socket is closed\n')
15:04:10 E   Failed: DID NOT RAISE <class 'socket.error'>
15:04:10 ______________________ ExecTest.test_detach_with_default _______________________
15:04:10 /docker-py/tests/integration/api_exec_test.py:279: in test_detach_with_default
15:04:10     sock, [ctrl_with('p'), ctrl_with('q')]
15:04:10 /docker-py/tests/helpers.py:124: in assert_cat_socket_detached_with_keys
15:04:10     sock.sendall(b'make sure the socket is closed\n')
15:04:10 E   Failed: DID NOT RAISE <class 'socket.error'>
15:04:10 - generated xml file: /go/src/github.com/docker/docker/bundles/test-docker-py/results.xml -
15:04:10 =========================== short test summary info ============================
```

**Comment by thaJeztah** [comment]
Same failures again; looks related to this change https://jenkins.dockerproject.org/job/Docker-PRs/53854/console


@shin- @ulyssessouza I could use some help on this one; wondering why this causes docker-py to fail

**Comment by shin-** [comment]
Removing the first `if` clause would probably work, though we'll still need it for older versions of the server. Shouldn't be too hard - I can take a look by EOW.

**Comment by thaJeztah** [comment]
Thanks @shin- !

**Comment by shin-** [comment]
@thaJeztah can you try https://github.com/docker/docker-py/pull/2317 (commit: a16a2051a6a30e9a44e64ad2333c1a49b4f5b580) and let me know if that fixes it?

**Comment by thaJeztah** [comment]
Thanks! Added a temporary commit to switch to that commit 👍

**Comment by thaJeztah** [comment]
@shin- looks like it passed with your changes 👍

**Comment by thaJeztah** [comment]
rebased on top of https://github.com/moby/moby/pull/39239 to get the latest docker-py version

**Comment by olljanat** [comment]
Derek add label: rebuild/windowsRS1

**Comment by thaJeztah** [comment]
ugh we need to get rid of that search test using Docker Hub, as it's unpredictable;

```
15:47:30 ----------------------------------------------------------------------
15:47:30 FAIL: docker_cli_search_test.go:47: DockerSuite.TestSearchCmdOptions
15:47:30 
15:47:30 assertion failed: expression is false: strings.Count(outSearchCmdStars1, "[OK]") <= strings.Count(outSearchCmd, "[OK]"): The quantity of images with stars should be less than that of all images: NAME                        DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
15:47:30 busybox                     Busybox base image.                             1584      [OK]       
15:47:30 progrium/busybox                                                            69                   [OK]
```

**Comment by thaJeztah** [comment]
Janky failed on https://github.com/moby/moby/pull/39243

**Comment by thaJeztah** [comment]
temporarily rebased on top of https://github.com/moby/moby/pull/39068 (which has the docker-py bump)

**Comment by thaJeztah** [comment]
docker-py now failing because it can't find the Debian Jessie packages 😞 

```
14:09:45 Digest: sha256:1e428d8e87bcc9cd156539c5afeb60075a518b20d2d4657db962df90e6552fa5
14:09:45 Status: Downloaded newer image for python:3.6-jessie
14:09:45  ---> 890456b21ed5
14:09:45 Step 3/17 : RUN apt-get update && apt-get -y install     gnupg2     pass     curl
14:09:45  ---> Running in 889f2f287ae2
14:09:45 Err http://security.debian.org jessie/updates InRelease
14:09:45   
14:09:45 Err http://deb.debian.org jessie InRelease
14:09:45   
14:09:45 Err http://security.debian.org jessie/updates Release.gpg
14:09:45   Temporary failure resolving 'security.debian.org'
14:09:45 Err http://deb.debian.org jessie Release.gpg
14:09:45   Temporary failure resolving 'deb.debian.org'
14:09:45 Reading package lists...
14:09:45 W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  
14:09:45 
14:09:45 W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/InRelease  
14:09:45 
14:09:45 W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'
14:09:45 
14:09:45 W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'
14:09:45 
14:09:45 W: Some index files failed to download. They have been ignored, or old ones used instead.
14:09:45 Reading package lists...
14:09:45 Building dependency tree...
14:09:45 Reading state information...
14:09:45 Package gnupg2 is not available, but is referred to by another package.
14:09:45 This may mean that the package is missing, has been obsoleted, or
14:09:45 is only available from another source
14:09:45 
14:09:45 E: Package 'gnupg2' has no installation candidate
14:09:45 E: Unable to locate package pass
14:09:45 The command '/bin/sh -c apt-get update && apt-get -y install     gnupg2     pass     curl' returned a non-zero code: 100
15:22:21 Build timed out (after 200 minutes). Marking the build as failed.
15:22:21 Build timed out (after 200 minutes). Marking the build as aborted.
```

**Comment by thaJeztah** [comment]
Wow; lots of weird failures on s390x; https://jenkins.dockerproject.org/job/Docker-PRs-s390x/14838/console

```
12:40:08 java.nio.file.FileSystemException: /home/jenkins/workspace/Docker-PRs-s390x/bundles/test-integration/DockerDaemonSuite.TestCLIProxyProxyTCPSock/dab712fc04589: Operation not permitted
12:40:08 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
```

**Comment by thaJeztah** [comment]
I wonder what version of Docker is installed on those s390x machines

**Comment by thaJeztah** [comment]
Rebased, to get rid of https://github.com/moby/moby/pull/39068

This should be ready for review

**Review by tiborvass — APPROVED** [review]

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
