### PR TITLE
Fixed secret creation usage during service create in docs

### PR DESCRIPTION
**Pull request by mikesir87**
Using source, the following error is made:
invalid field in secret request: src

Signed-off-by: Michael Irwin <mikesir87@gmail.com>

**- What I did**
Documentation fix to align with outcome from running command

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM.

Considering that `--mount` accepts both `source` and `src`, maybe we should support `src` as well, but that can be another PR

https://github.com/docker/docker/blob/5e143b5f8d82537635a57f3d9eda8126caf68a6f/opts/secret.go
https://github.com/docker/docker/blob/5e143b5f8d82537635a57f3d9eda8126caf68a6f/opts/mount.go

**Review by thaJeztah — APPROVED** [review]
LGTM

wondered the same as @AkihiroSuda, but I think there may have been a reason (as "secrets" are not "mounts"); feel free to open an issue for it for discussion though

**Comment by AkihiroSuda** [comment]
@thaJeztah 

I found that `src` is discussed in https://github.com/docker/docker/issues/28527#issuecomment-262817805 :smile: 

> Secrets: accept src as a short name for the source argument

**Comment by thaJeztah** [comment]
@AkihiroSuda ah, looks like we should have a PR for that then 👍

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker/pull/30407

**Pull request merged**
