### PR TITLE
add grammar checking for docs

### PR DESCRIPTION
**Pull request by jessfraz**
adds a super small go tool so we can check grammar

for now this output will not actually error out, it will just give helpful feedback

and after trying it and seeing it is good we can add additional components, going to try to add to gordon bot as well to comment the feedback

just need to figure out how to ignore tech terms on the server

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @moxiegirl @fredlf @SvenDowideit 

you can try the tool youself by go getting github.com/jfrazelle/atd, I spun up an "after the deadline" api container for us

**Comment by fredlf** [comment]
I'm not a big fan of grammar checkers (I think they're based on a flawed premise), but I'm happy to take a look at this tool. I just don't get how to do that! Can you get me started?

**Comment by moxiegirl** [comment]
@jfrazelle  This will catch initial small things like word repeats and spelling. Like the iterative approach to start off easy and see how it goes.

Worked a trick. I like that we can extend the dictionary and the rules.

**Comment by moxiegirl** [comment]
@thaJeztah He would be interested in this also. :-D

**Comment by thaJeztah** [comment]
Sounds nice. Hope it's better than the autocorrect on my phone, which can be a real PITA when mixing "code" and "text".

Will give it a try later (SSH session on my iPad, always fun!)

thanks, @jfrazelle!

**Comment by calavera** [comment]
@jfrazelle I wonder if grammar errors in the docs should really block CI builds.

**Comment by fredlf** [comment]
If it's just checking spelling and doubles, that's a different animal altogether. I'm all for that. If someone could give me a hint as to how to access the tool, I would appreciate it.

**Comment by SvenDowideit** [comment]
@jfrazelle can we do a trade - turn this on, and turn off code build and tests for PR's that only contain docs/ changes?

**Comment by jfrazelle** [comment]
ya i was thinking that too ;)

**Comment by jfrazelle** [comment]
we already do it for windows :)

**Comment by jfrazelle** [comment]
closing will reopen when i have time, dont worry i have not given up on this

**Pull request closed without merging**
