### PR TITLE
1.13.0-rc2 cherry-picks : part 3

### PR DESCRIPTION
**Pull request by vieux**
- [#28026](https://github.com/docker/docker/pull/28026)
  - 786a95493d54d74fa3eef020c1ec03baa4fe91c4 Return an empty stats if the container is restarting
- [#28294](https://github.com/docker/docker/pull/28294)
  - 7c1b39923505adeb13512d6294855b31102963a6 3bd64de7a9c3eecbd57cb11d861a6fe94a5bb788 b0903c9db0e1fe0226102e3887b5c30474837e97 Add support for healthcheck in compose to swarm
- [#28466](https://github.com/docker/docker/pull/28466)
  - c44c542d95e62fa5e96c1542f2b8bb878a7976e8 The type of 'ExportdPorts' should be 'nat.PortSet'
- [#28539](https://github.com/docker/docker/pull/28539)
  - e7d83fdb9a17c384397e81d7b5a83245b4216f79 Suppressing digest for docker service ls/ps
- [#28607](https://github.com/docker/docker/pull/28607)
  - db3f06fd976d71a1d335278ecedf026aea6046c0 Clarify that ipmasq rules are not added when iptables is false
- [#28615](https://github.com/docker/docker/pull/28615)
  - c8f826f4077b15af30d8810f62abd517908bb712 Update deprecation notes about v1 registry
- [#28637](https://github.com/docker/docker/pull/28637)
  - 0d573a62f7e9b74621376cd5514462277bf341e9 Add bash completion for `dockerd --userland-proxy-path`
- [#28644](https://github.com/docker/docker/pull/28644)
  - cf3ef262b161f1c3dd61f5689e2853c2e8ec8b70 close the file
- [#28647](https://github.com/docker/docker/pull/28647)
  - 4d54d30477f2eb0f373fd2301cf4c3ecc1434d62 Bugfix: set cli.manualOverride when env var not empty
- [#28656](https://github.com/docker/docker/pull/28656)
  - 88cdfc512b0737f6dd9eb5ad207fb68f9acdf51e Update cli reference for docker {,stack} deploy 
- [#28663](https://github.com/docker/docker/pull/28663)
  - 158388ef8d66723ec1f8ee4770d7488948234d16 Do not panic if network is nil
- [#28328](https://github.com/docker/docker/pull/28328)
  - 32b12a28fcab98b79c9176fb78b5620a46906916 cli: Add valid suffixes for remaining duration options
- [#28504](https://github.com/docker/docker/pull/28504)
  - 514ca09426e5d023753101ffa6ac3a21b0e0efb5 api: types: do not remove old SecurityOptions struct
- [#28556](https://github.com/docker/docker/pull/28556)
  - bebd472e40cae91b548e983872a2665a5836ba43 eb036ea4db86c98d5b3f51e7d0d2424faaca0343 Fix target reference secrets and container secret store
- [#28649](https://github.com/docker/docker/pull/28649)
  - 89100c162b23791b4a64d142a11014257bf61fd0 judge manager if locked before parsing key
- [#28670](https://github.com/docker/docker/pull/28670)
  - 00caf03132a1bf1a2a7a389c5f23d6fc81f2bc0b re-vendor syslog log driver
- [#28677](https://github.com/docker/docker/pull/28677)
  - 6df5baf30f96e5af3338551b9e632748d7886ead Move `docker stack` out of experimental
- [#28664](https://github.com/docker/docker/pull/28664)
  - 90993640f0e21a45874a9efc6b6236b589945d6e Update service ps reference for "--no-trunc" 
- [#28486](https://github.com/docker/docker/pull/28486)
  - 4571ad05dba48eda9d138c4db20bd2a63022ff63 Add documentation about templating support on services creation/update.
- [#28628](https://github.com/docker/docker/pull/28628)
  - e84d62f6cb3d0e578c6b876385ca3c8aa2d23b41 Add bash completion for `docker images --filter reference`
- [#28640](https://github.com/docker/docker/pull/28640)
  - 060196ee4cdf2d60800faef67662989d74f5c03a allow replacing httpredir mirror for arm

- [#27625](https://github.com/docker/docker/pull/27625)
  - a532ff8cc387ba1d6d98eb2456dd53d97d3eca4b Add `make deb` support for aarch64
- [#27628](https://github.com/docker/docker/pull/27628)
  - 015e83a8da3ccf9f208f92d5d66e5dd159f75ad7 build debian package for armhf ubuntu-xenial
- [#28343](https://github.com/docker/docker/pull/28343)
  - d48e70843f2ea26c60b42165edbc9be8ace0d2d5 Add bash completion for `docker build --network`
- [#28445](https://github.com/docker/docker/pull/28445)
  - f4bb8c51de3a52bdbc3c3e7be426e6bb90feb421 Handle `run --rm` against older daemons on the cli
- [#28529](https://github.com/docker/docker/pull/28529)
  - 86d768284303665bf137ac4766a623167a605c76 fix secret create url for consistency
- [#28595](https://github.com/docker/docker/pull/28595)
  - 83ca993c154d56e03d6f95a3f8351c48b3ed3e29 Allow HTTP client timeout to be configurable on plugin enable.
- [#28659](https://github.com/docker/docker/pull/28659)
  - d5dc9b8b1f5e693cfb3aace06e08e7fc6eb798d7 bugfix: incorrect ErrConnectFailed Comparison
- [#28671](https://github.com/docker/docker/pull/28671)
  - baac0ef67f97e007db03b4edaaa756e4a89678fc Update hcsshim to v0.5.9
- [#28672](https://github.com/docker/docker/pull/28672)
  - b118056241430a28739128fdf7fc60b125a12c49 3b3cf87478cc478c79116ed1f281a95955264eff Add support for armhf ubuntu-xenial deb
- [#28682](https://github.com/docker/docker/pull/28682)
  - 4e262f63876018ca78d54a98eee3f533352b0ac9 Fix race on sending stdin close event
- [#28699](https://github.com/docker/docker/pull/28699)
  - 97e189292278de10f2590f52eaf9b382c54bc99b Add zsh completion for 'dockerd --userland-proxy-path'
- [#28700](https://github.com/docker/docker/pull/28700)
  - 15134b8d361895654b471a50c32f59ebc4a719ea Add zsh completion for 'docker image ls --filter reference'
- [#28709](https://github.com/docker/docker/pull/28709)
  - f60541069cca1a4c886f5c2198d2ccd07f4ee764 skip solaris and allow dry run control points 
- [#28711](https://github.com/docker/docker/pull/28711)
  - 01b70a95c93b8442276fd312bac44a45ec859460 Update aanand/compose-file to a3e58764f50597b6217fec07e9bff7225c4a1719
- [#28718](https://github.com/docker/docker/pull/28718)
  - 2e120556872ee3ecd7f3b5cd4698e4195220c2ff Fix typo in docs (Copmose)
- [#26833](https://github.com/docker/docker/pull/26833)
  - 821aeb6a6f72f070ae045cb7813759cbbaba7bda Use container Mounts API for Swarm containers.
- [#28598](https://github.com/docker/docker/pull/28598)
  - 000366f1a72a8fde2c25b4606821605780a55c02 Ensure vmcompute.dll exists during daemon start
- [#28601](https://github.com/docker/docker/pull/28601)
  - 84e58e2f89b3dea30738f92edcabef4336d0cff6 9f239281b1b02ed46f98af1eb39bc9b2165073fa 99124c055ac5d145737fe432ffc2e62e320d3d96 a08ffa0e934e5f8b95855cc5bd0cc2a6b3cf4091 e2e7ab655fa429d491096eea82952c4a6a1569d9 53b9b99e5cd19d9913c56c07276a2d4d83b9befd 6547609870b66f9dfb1894a4987c42608f856f3e Plugin miscellaneous fixes
- [#28685](https://github.com/docker/docker/pull/28685)
  - 873a26697de8e1dfdc31c7151a7c4fdfd30f519a Revendor go-winio to v0.3.7
- [#28691](https://github.com/docker/docker/pull/28691)
  - c2d435e4f05d262aaa3d4d5cc2fe8965377eebdf [experimental] service logs: Support no-follow mode
- [#28698](https://github.com/docker/docker/pull/28698)
  - fc11efa2dbf72bb493a24650860220a2d4b07c5e error strings should not be capitalized or end with punctuation
- [#28703](https://github.com/docker/docker/pull/28703)
  - fa15d5ed0f96592b49c2e25c06e92d51999fb29b hack/dockerfile/binaries-commits: use full commit hash for docker info 
- [#28715](https://github.com/docker/docker/pull/28715)
  - f885463b58f0608d9403a8b84d79320ffcce86a1 add note that windows does not support managed plugins
- [#28726](https://github.com/docker/docker/pull/28726)
  - b303381a4d679cad652c83f6b7d28cccbc06574c Document pull concurrent options
- [#28506](https://github.com/docker/docker/pull/28506)
  - 993854f58fa4132ff82c2e1ffe291d90b301db5a f0d55cd081c6e8ad2a8222c787d54f9aae15723f c97f67dbab50f0efbf3c1e6a2862d29c76c9aec1 44c50807c6eadcb2371cc6bf8ba5f66ba9dcbe97 109c54c481c7dafe88b622b87c0c7c172fed5ea1 
Edit
Prepare docs and Swagger definition for automatically generated API docs
- [#28727](https://github.com/docker/docker/pull/28727)
  - 2c0613540a25d45069d142542e572bb6338e4155 fe127b7eae427bde96b7852ac196825e1c9ea359 Do not display the digest or size of swarm secrets

- [#xxx](https://github.com/docker/docker/pull/xxx)
  - xxx xxx

### CODE REVIEW

**Comment by vieux** [comment]
ping @docker/core-engine-maintainers

**Comment by aluzzardi** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by aluzzardi** [comment]
CI 🐌 🐌 🐌

**Pull request merged**
