### PR TITLE
change hack/make.sh to automate auto restart the daemon  on every build

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: krasi georgiev <krasi@vip-consult.solutions>

**- What I did**
Added the manual steps in the make.sh script

**- How to verify it**
hack/make.sh binary
hack/make.sh binary-client
hack/make.sh binary-daemon

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
I looked through the logs , but can't understand why this fails.

**Comment by vdemeester** [comment]
@krasi-georgiev what is the use case for that change ?

**Comment by krasi-georgiev** [comment]
less manual steps to test your code changes.

at the moment I do this:

make some code changes -> kill the running daemon -> run hack/make.sh binary -> copy the new binaries -> start the daemon.

I thought it would be easier to integrate all this in the make.sh

so now I only run hack/make.sh binary

**Comment by vdemeester** [comment]
@krasi-georgiev there is a *bundle* to install binary (`install-binary` and one to run). Most of the time I run : `./hack/make.sh binary install-binary run` and when changing, `ctrl+c`, `up` and `enter`. Anyway, if we want to go there, I don't think it should be in `make.sh` but in a specific *bundle* (script).

/cc @tianon

**Comment by tianon** [comment]
Agreed with @vdemeester -- restarting the Docker daemon can have disastrous consequences for a running system, so I'd rather leave that as an explicit choice of the user of these scripts/tools.

**Comment by krasi-georgiev** [comment]
Thanks for the feedback.

Do you think it would be a good idea if I update the docs with 
./hack/make.sh binary install-binary run
as an alternative to automate the re run cycle.

it might be helpful for other devs that are just starting up with the contributions.

**Comment by vdemeester** [comment]
@krasi-georgiev yes I think that would be good ! /cc @thaJeztah

**Comment by thaJeztah** [comment]
Yes, we can certainly improve some bits there, so I welcome contributions 👍

**Comment by krasi-georgiev** [comment]
#1434

this should do

**Comment by krasi-georgiev** [comment]
this should do
https://github.com/docker/docker.github.io/pull/1434

**Comment by krasi-georgiev** [comment]
@vdemeester and how do you run the dockerd with --experimental enabled ?

I tried setting export DOCKER_EXPERIMENTAL=1
and then running 
./hack/make.sh binary install-binary run

but when I look inside the run script it seems that is doesn't use the env  $DOCKER_EXPERIMENTAL
shall I maybe add it there or there is another way ?

**Pull request closed without merging**
