### PR TITLE
Update containerd to 1.1

### PR DESCRIPTION
**Pull request by dmcgowan**
Updates containerd to 1.1. This is pulls in needed updates and client features to complete containerd image store and buildkit integration.

Currently blocked by Swarmkit:
~https://github.com/docker/swarmkit/pull/2610~
~https://github.com/docker/swarmkit/pull/2452~
~https://github.com/docker/swarmkit/pull/2631~
~#37059~
~https://github.com/docker/swarmkit/pull/2649~

### CODE REVIEW

**Comment by vdemeester** [comment]
@dmcgowan @thaJeztah still blocked (swarmkit PR is merged upstream)

**Comment by dmcgowan** [comment]
Updated GRPC to 1.12, which forced me to update everything else and vendor SwarmKit to https://github.com/docker/swarmkit/pull/2649

**Comment by dmcgowan** [comment]
Finally green tests, I am going to remove the blocked marker and update swarmkit the merged version

**Comment by thaJeztah** [comment]
Looks like you need to vendor with an older version of vndr (can do it inside the build container); 

```
The result of vndr differs
01:31:11 
01:31:11  D vendor/golang.org/x/crypto/otr/libotr_test_helper.c
01:31:11  D vendor/golang.org/x/crypto/otr/otr.go
01:31:11  D vendor/golang.org/x/crypto/otr/smp.go
01:31:11 
01:31:11 Please vendor your package with github.com/LK4D4/vndr.

**Comment by dmcgowan** [comment]
Green now

**Review by AkihiroSuda — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Looks like the bump of gRPC caused a regression, because grpc now adds a limit that was not previously set; As of https://github.com/grpc/grpc-go/commit/50d4175072941195bca4f18fedd25d04132185e0 / https://github.com/grpc/grpc-go/commit/6f8b55318ad2c3645b1096f11cd27996bad2add3  (https://github.com/grpc/grpc-go/pull/1165) a limit of 4MB is applied, which can cause issues with many tasks running.

See https://github.com/moby/moby/pull/38103 and https://github.com/moby/moby/issues/37997

**Pull request merged**
