### PR TITLE
Remove libcontainer state on terminate/Mount state in tmpfs

### PR DESCRIPTION
**Pull request by crosbymichael**
**tmpfs**
By doing this we don't have to worry about itterating over state after a
machine restart because non-running containers will not have information
because the tmpfs mount will not persist with the machine reboot.

**removal**
This ensures that the libcontainer state is fully removed for a
container after it is terminated.

### CODE REVIEW

**Comment by crosbymichael** [comment]
@tianon this fixes your restart issues

**Comment by LK4D4** [comment]
@crosbymichael I wonder now if it makes sense to move this to libcontainer. Also `LinuxFactory.Destroy` for removing old crap could be cool.
I'm LGTM for this patch though.

**Comment by crosbymichael** [comment]
@LK4D4 that maybe a better idea.  Should we do that?

**Comment by LK4D4** [comment]
@crosbymichael Let's do it tomorrow.

**Pull request closed without merging**
