### PR TITLE
Remote API documentation consistancy

### PR DESCRIPTION
**Pull request by deployable**
**\- What I did**

Updated the Remote API documentation to make it more consistent.

**\- How I did it**

Moved the **Stream details** sections in the API documentation from being a component of the **Status codes** list into their own section by reducing their indentation to the same as surrounding sections. 

Modified headings with `<params>` to use the `(param)` format that is most common. 

Remove query param from endpoint heading. 

**\- How to verify it**

View markdown.

**\- Description for the changelog**
Correct Remote API Docs "Stream Details" indentation.

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐸
/cc @sfsmithcha @SvenDowideit @thaJeztah

**Comment by sfsmithcha** [comment]
@deployable , please squash your commits.
After that LGTM

**Comment by deployable** [comment]
@sfsmithcha squashed

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
