### PR TITLE
Revert "Break big lock into some tiny locks"

### LINKED ISSUE #19335: Add back protection against starting a container twice
This issue is to track the follow-up questions in #18736. Either we should revert it or add a `starting` state. `starting` state would also need some special handling - if `running` state is expected but `starting` is found the action shouldn't error but wait for the state to change.

#19330 also has relevant discussion.

@WeiZhang555 @ibuildthecloud @LK4D4 @cpuguy83

### PR DESCRIPTION
**Pull request by cpuguy83**
Reverts docker/docker#18736

Closes #19335
Closes #19330

### CODE REVIEW

**Comment by calavera** [comment]
I guess we don't need #19330 if we revert this change, do we?

**Comment by cpuguy83** [comment]
Correct, updated the description so it closes it out.

**Comment by calavera** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
