### PR TITLE
hack/make/.go-autogen: fix LDFLAGS to accept values with spaces

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/docker/docker-ce-packaging/pull/415#issuecomment-574410473
relates to https://github.com/docker/docker-ce-packaging/pull/417
relates to https://github.com/moby/moby/pull/40180

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon @arkodg PTAL

**Review by tianon — APPROVED** [review]
If Go's `-ldflags` accepts inline `'` (single quotes), this could be made a little easier to read (ditching the `\`), but that's a pretty minor thing.

LGTM

**Review by arkodg — APPROVED** [review]

**Comment by thaJeztah** [comment]
I could give that another try perhaps. But I got crazy with all the quoting to get it working 😂

**Comment by tianon** [comment]
Yeah, IMO not a blocker by any means for merging this, just something we
could consider in the future if someone is bored and has a minute to test
it out. 😅

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
