### PR TITLE
Proposal: Per-container port range to use instead of the ephemeral range

### PR DESCRIPTION
**Pull request by bru7us**
A small extension to #12927 to allow specification of the host port range for all dynamically allocated ports of a container.

This addition allows the user to specify a default custom port range for all dynamically published ports on a container, without having to explicitly reference them all. e.g. `docker run --port-range=8000-9000 -P <image>`

### CODE REVIEW

**Comment by bru7us** [comment]
@mavenugo @mrjana @aboch rebased off master

**Comment by icecrime** [comment]
Ping @mavenugo @mrjana!

**Comment by bru7us** [comment]
Anyone?

**Comment by thaJeztah** [comment]
ping @mavenugo @mrjana could you have a look here please?

**Comment by icecrime** [comment]
I'm personally -1 on this: I don't see a significant use case for it, and the proposed UX looks very complicated to me (it makes the interactions between `-p`, `-P`, and `--port-range` event more complicated than they already are).

**Comment by thaJeztah** [comment]
I agree, from a UX perspective, interactions between those options are already confusing, and this will only add to the confusion.

I'm going to close this PR, but thanks so much for contributing @bru7us!

**Pull request closed without merging**
