### PR TITLE
17.03.2 cherry picks

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @mlaventure @thaJeztah 

This is all in the project except https://github.com/moby/moby/pull/31343
(ping @aboch)

**Comment by thaJeztah** [comment]
For reference this cherry-picks;

https://github.com/moby/moby/pull/32529
https://github.com/moby/moby/pull/29428
https://github.com/moby/moby/pull/32012
https://github.com/moby/moby/pull/32525
https://github.com/moby/moby/pull/32851
https://github.com/moby/moby/pull/32347
https://github.com/moby/moby/pull/32098
https://github.com/moby/moby/pull/31290

@cpuguy83 wondering didn't we usually cherry-pick the _merge_ commit?

**Comment by thaJeztah** [comment]
hm, never mind looks like we have done both in the past

**Review by mlaventure — APPROVED** [review]
code LGTM

Let's see if it's gonna be :green_heart:

**Review by thaJeztah — APPROVED** [review]
LGTM as well

ping @runcom PTAL

**Comment by runcom** [comment]
can we also cherry-pick https://github.com/moby/moby/pull/31966?

**Comment by runcom** [comment]
LGTM otherwise

**Comment by thaJeztah** [comment]
@runcom can you prepare a separate cherry-pick for that so that we can discuss?

**Comment by thaJeztah** [comment]
I'll merge this one, as it's all green (thanks for reviewing!)

**Pull request merged**
