### PR TITLE
Update libcontainer to 47e3f834d73e76bc2a6a585b48d

### LINKED ISSUE #19329: [1.10] cgroup panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb1a82f]

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer/cgroups/fs.(*Manager).Freeze(0xc820c418e0, 0x16cdfd8, 0x6, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go:205 +0x2bf
github.com/opencontainers/runc/libcontainer.killCgroupProcesses(0x7f5fe456fc30, 0xc820c418e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/init_linux.go:309 +0x8c
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Destroy(0xc820d88ea0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/container_linux.go:331 +0x238
github.com/docker/docker/daemon/execdriver/native.(*Driver).Terminate(0xc820717840, 0xc8207e5c00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:346 +0x2dd
github.com/docker/docker/daemon.(*Daemon).Register(0xc82000c840, 0xc820bfcfc0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:276 +0x4df
github.com/docker/docker/daemon.(*Daemon).restore(0xc82000c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:343 +0x11c5
github.com/docker/docker/daemon.NewDaemon(0xc820134c80, 0xc820028118, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:835 +0x335f
main.(*DaemonCli).CmdDaemon(0xc820648a30, 0xc82000a070, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/docker/daemon.go:227 +0x136a
reflect.callMethod(0xc820646d80, 0xc820d43c68)
	/usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a070, 0x3, 0x3, 0x1, 0xc820646d80, 0x0, 0x0, 0xc820646d80, 0x0, 0x473375, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc820646cf0, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:63 +0x43c
```

I had just upgraded a 1.9.1 environment to 1.10 and this panic was thrown on the first daemon start.  This is running off of 63525a6dc5f7be370736ec2905d40a8c8fdf1162

### PR DESCRIPTION
**Pull request by crosbymichael**
This adds a fix for the resource struct in the cgroups type and seccomp
IsEnabled function

Fixes #19329

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by cyphar** [comment]
I don't think it's a good idea to start vendoring a branch of libcontainer. opencontainers/runc#470 fixes master, and there's no reason not to merge it if we can't figure out why the state transition stuff is broken. There's no reason we can't re-merge a fixed version of the state transition stuff later.

However, if you're committed to us vendoring a branch, you *should* cherry-pick opencontainers/runc@bf899fef451956be4abd63de6d6141d9f9096a02. It fixes a security bug.

**Comment by thaJeztah** [comment]
Experimental failed on https://github.com/docker/docker/issues/19472, Janky on https://github.com/docker/docker/issues/19393 :cry:

**Comment by thaJeztah** [comment]
Hm Windows timeout (I think), but the first error looks weird;

```
05:24:01 INFO: Attempting curl to ping the DIND daemon
05:24:01 ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
05:24:01 Type "TIMEOUT /?" for usage.

….

05:24:01 -----------------------------------------------
05:24:01 Windows CI Timeout Detection - End of debugging
05:24:01 ———————————————————————
```

**Comment by crosbymichael** [comment]
Windows error is unrelated

**Comment by thaJeztah** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by cyphar** [comment]
@calavera @tiborvass @crosbymichael Can you please explain why you all LGTM'd and merged a vendor for a non-master branch of runc, when runc/opencontainers#470 patchset actually fixes the problems, passes all tests, has a vendor PR open that also passes all tests and merges cleanly on master, and has two LGTMs? More importantly, is there a reason why my comment **wasn't even addressed**?

The reason why I thought it was important to deal with this problem is not only because hot-fixes like this have tendency to stick around, but also because **I actually have to bisect docker quite regularly, and usually run `./hack/vendor.sh` in order to test some upstream changes to see if we should backport them**. Yes, I get it, you don't support any previous versions. But other people (like me) do. Why make it hard for those people?

For future reference to anyone who needed to run `hack/vendor.sh` after the branch has been removed (such as people in the future who are bisecting Docker), here is the relevant information about this patch:

The commit `opencontainers/runc@47e3f834d73e76bc2a6a585b48d2a93325b34979` was based on the commit `opencontainers/runc@d97d5e8b007e4657316eed76ea30bc0f690230cf`. The following commits were cherry-picked from `master`:

* opencontainers/runc@41edbeb25e73d0d2aad06941f637006b0e6aa6be
* opencontainers/runc@f048eaf87a55dc0ea5bc558c1256a097122c420a
* opencontainers/runc@9c41e8388cc2a5bda8f02e30e2a5bb4508bd1f51

**Comment by hqhq** [comment]
@cyphar Since Docker already released RC, we can't vendor runc master, so cherry-pick important bug fixes would be the way to go. After 1.10 released, we can vendor the whole runc mater again.

In this model, I think the path sanitation patch which fixes security problem can also be cherry-picked, we just need someone open the PR.

**Comment by tiborvass** [comment]
@cyphar we're still figuring out the process for vendoring and all suggestions to improve it are welcome.

Having said that, currently, the process does not prevent us from sending subsequent vendoring PRs if need be. It seems to me that opencontainers/runc#470 was not approved in time for this round of vendoring.

Your vendoring PR #19024 got indeed 2 LGTMs, but it was referencing your fork, which is not okay. We probably should make that clearer in the vendoring policy.

About vendoring commits that are not in upstream master, I don't directly see it as a problem and I don't quite understand the issue you have with bisecting, however I do see problems with our vendoring policy and I suggest we continue this discussion on the maintainers mailing list or in a PR to the vendoring policy.

Although we are in a release period, sorry for not addressing your issues in time.

**Comment by cyphar** [comment]
@tiborvass opencontainers/runc#470 got one LGTM and one tentative LGTM ("I'm okay with this but ..."). That's what I was referring to, and that counts as 2 IMO.

>About vendoring commits that are not in upstream master, I don't directly see it as a problem and I don't quite understand the issue you have with bisecting, however I do see problems with our vendoring policy and I suggest we continue this discussion on the maintainers mailing list or in a PR to the vendoring policy.

In SUSE, we backport fixes to bugs for 1.9.1 and (previously) 1.8.3. Quite a few bug fixes are in vendor commits (and sometimes bugs are caused by vendor commits). My workflow for such cases is something like:

* `git bisect` the night away until we hit the commit that broke it.
* If it's a vendor commit, test whether running `hack/vendor.sh` with different commits of the library fixes the problem (specifically if I'm trying to bisect a library that Docker depends on and Docker has a bug based on that library, this is quite important).
* Make a patch for SUSE distros.

Now, you could argue that it is possible to do the same thing without `hack/vendor.sh`. Yes I can. But it makes life significantly harder. The issue is that the `hotfix` branch is not going to be sticking around for the next few months, so when I eventually hit a bug in the window between this vendor and the next one, it's going to be a PITA to test.

I would appreciate it if the vendoring policy at least required some detailed decription of the non-`master` branch being vendored. I understand that hotfixes are necessary, and that sometimes it's unavoidable to vendor a branch, but the way it was done ("here's a cryptic commit hash, good luck understanding what patches we just pulled in, person debugging a problem 3 months from now") wasn't IMO how it should be done.

**Comment by hqhq** [comment]
I agree we should improve the process for cherry-picking patches of vendors in release period, I got the same problem sometimes, it's all for developers. What about we just backport patches without touching vendor ids, and keep these patch in separate?

**Comment by tiborvass** [comment]
@cyphar @hqhq thanks for your input, but please let's stop hijacking this merged PR. We can continue on  a PR changing the vendor policy file, or in a new GH issue.

**Pull request merged**
