### PR TITLE
Check the content type is json when calling exec start.

### PR DESCRIPTION
**Pull request by calavera**
Supersedes #16399.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐲 (assuming it's green :green_heart:)

**Comment by runcom** [comment]
@calavera build failure

**Comment by vdemeester** [comment]
`api/client/hijack.go:130: undefined: hijackWithContentType`

**Comment by calavera** [comment]
@runcom, @vdemeester I fixed that compilation error and everything is green, can you take another look?

**Comment by runcom** [comment]
reLGTM

**Pull request merged**
