### PR TITLE
Fix lint errors on master

### PR DESCRIPTION
**Pull request by dnephin**
A PR merged after adding new linters , which had some errors.

Also skip linting of `integration-cli` since we're ignoring errors in that package.

### CODE REVIEW

**Review by seemethere — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Does this allow us to remove the `testingT` type define in this package?

**Comment by dnephin** [comment]
It doesn't. It's still being used for the LogT and Fatalf

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
