### PR TITLE
Add ci info to docs

### PR DESCRIPTION
**Pull request by zelahi**
Added information regarding our new Jenkins ci on moby/moby

Signed-off-by: zelahi <elahi.zuhayr@gmail.com>

**- What I did**
Added notes regarding our ci.docker.com/public infra in the testing section

**- How I did it**
Added a section in the test.md section

**- How to verify it**
Looked through the documentation and provided the minimum info to understand the infrastructure

**- Description for the changelog**
No changelog description required

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Windows and non-x86 are no longer tested?

**Comment by zelahi** [comment]
As a default they aren't.  This is because we are waiting for windows machines to be set up with our Jenkins infra before having them as part of the test

**Comment by thaJeztah** [comment]
> Windows and non-x86 are no longer tested?

@AkihiroSuda they will be tested again; I think work is in progress to have Windows machines being spun up automatically (instead of using the "pet" machines that are currently used)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
oh! @zelahi I think you have your name not configured properly in your Git configuration;

```
Signed-off-by: zelahi <elahi.zuhayr@gmail.com>
```

Can you change your sign-off to use your real name?

**Comment by zelahi** [comment]
@thaJeztah done and I believed it's fixed! Ty for catching it

**Pull request merged**
