### PR TITLE
Fix ipc umount for old containers

### PR DESCRIPTION
**Pull request by chenchun**
Signed-off-by: Chun Chen ramichen@tencent.com

Relates to https://github.com/docker/docker/pull/18076

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @cpuguy83 
Why we needed configurable method?

**Comment by cpuguy83** [comment]
It was already configurable when I got to it. But really the point in register is to use force unmount otherwise there are errors. So I'm not sure what this is fixing.

**Comment by chenchun** [comment]
> register is to use force unmount otherwise there are errors

Tried it. Is it because `cleanupMounts` during daemon init cleaned up ipc mounts? Then why need to do it again in register?

**Comment by cpuguy83** [comment]
@chenchun In Register it's happening right after we kill any containers that happen to be running still (as would be the case with containers running and the daemon is improperly shutdown).
Honestly I don't know if it's needed -- it was there already and I changed to use force Unmount since we _shouldn't_ need to wait for anything else attached to that mount.

**Comment by chenchun** [comment]
Thanks for your explanation. I was careless and I instinctively thought the umount should be the same in these two places. 

> Honestly I don't know if it's needed

The suspicious dup umount doesn't hurt anything. I'll leave it to you.

**Pull request closed without merging**
