### PR TITLE
fix docker inspect upper

### PR DESCRIPTION
**Pull request by resouer**
Minor fix a nits during revising my Docker book.

Signed-off-by: Harry Zhang harryz@hyper.sh

### CODE REVIEW

**Comment by allencloud** [comment]
need a rebase @resouer 🐳

**Comment by thaJeztah** [comment]
Actually, this file was moved to the central docs repository. Could you reopen this PR in the docs repo? This file can now be found here; https://github.com/docker/docker.github.io/blob/master/engine/admin/formatting.md

**Comment by resouer** [comment]
@thaJeztah no need, has been fixed in new repo :)

**Comment by thaJeztah** [comment]
@resouer even better :+1:

**Pull request closed without merging**
