### PR TITLE
Remove engine.Table from docker search and fix missing field

### PR DESCRIPTION
**Pull request by duglin**
And registry/SearchResults was missing the "is_automated" field.
I added it back in.

Pulled this 'table' removal one from the others because it fixed
a bug too

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by LK4D4** [comment]
ping @dmcgowan @dmp42 for registry

**Comment by jfrazelle** [comment]
oooo cool LGTM

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
