### PR TITLE
Vendoring libnetwork @9ab6e13

### LINKED ISSUE #25497: Cannot ping the VIP of a container by its service name across multi-host in 1.12 swarm mode
I cannot ping the container on another docker host by its service name if the `--endpoint-mode` is `vip`.

To reproduce the problem, I create a 2-node swarm cluster by following commands:

``` bash
docker-machine create -d virtualbox node-1
docker-machine create -d virtualbox node-2

ManagerIP=`docker-machine ip node-1`

docker-machine ssh node-1 docker swarm init --advertise-addr ${ManagerIP}

WorkerToken=`docker-machine ssh node-1 docker swarm join-token worker | grep token | awk '{ print $2 }'`

docker-machine ssh node-2 "docker swarm join --token ${WorkerToken} ${ManagerIP}:2377 --advertise-addr $(docker-machine ip node-2)"
```

Then, I created an `overlay` network:

``` bash
eval "$(docker-machine env node-1)"
docker network create -d overlay frontend
```

Then, I created 4 services

``` bash
docker service create \
    --name s1 \
    --constraint 'node.hostname == node-1' \
    --network frontend \
    nginx:latest

docker service create \
    --name s2 \
    --constraint 'node.hostname == node-2' \
    --network frontend \
    nginx:latest

docker service create \
    --name s3 \
    --constraint 'node.hostname == node-1' \
    --network frontend \
    --endpoint-mode dnsrr \
    nginx:latest

docker service create \
    --name s4 \
    --constraint 'node.hostname == node-2' \
    --network frontend \
    --endpoint-mode dnsrr \
    nginx:latest
```

`s1` and `s2` are `--endpoint-mode=vip` by default,
`s3` and `s4` are specified `--endpoint-mode=dnsrr`.

As the constraints setting, `s1` and `s3` will run on `node-1`, and `s2` and `s4` will run on `node-2`. 

Then, `ping` test matrix are:

|  | s1 | s2 | s3 | s4 |
| --- | --- | --- | --- | --- |
| s1 | ok | x | ok | ok |
| s2 | x | ok | ok | ok |
| s3 | ok | x | ok | ok |
| s4 | x | ok | ok | ok |

All `vip`s acrossed multi-host are not pingable.

For the failed pings, it returned the error `Destination Host Unreachable`, such as,

``` bash
root@ab79b97007a6:/# ping s1
PING s1 (10.0.0.2): 56 data bytes
92 bytes from ab79b97007a6 (10.0.0.7): Destination Host Unreachable
92 bytes from ab79b97007a6 (10.0.0.7): Destination Host Unreachable
92 bytes from ab79b97007a6 (10.0.0.7): Destination Host Unreachable
^C--- s1 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```

I tried the command `ping tasks.{service-name}` mentioned in #24201, it's pingable in all cases.

### LINKED ISSUE #26724: Disabling ICC on internal network does not work
**Description**

I am trying to understand how to limit communication between Docker containers on the same network. Disabling ICC in the daemon, disabling IP forwarding, flushing the forward chain on the host's iptables and dropping all forwarded packets, and disabling ICC in the network doesn't prevent this. The issue that I see is that pings still propagate from one container to another when both containers are attached to a custom bridge network. 

**Steps to reproduce the issue:**
1. Flush forwarding chain of iptables on host and setting it to drop all packets
2. Start docker daemon with ICC set to false and IP forwarding set to false
3. Create custom bridge network with ICC disabled and which is an internal network
4. Spawn 2 containers attached to the custom network
5. Ping from one hostname to the other

**Describe the results you received:**
Pings are oddly successful between the containers. 

**Describe the results you expected:**
Pings should not go through because ICC is disabled on the network.

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm really just trying to understand what these different options should do and whether they are behaving as expected. In addition, I am trying to understand why the packets aren't hitting the host's iptables. 

I did see this issue:
https://github.com/docker/docker/issues/21990
but it only seemed to apply for the ICC flag in the daemon whereas I'm also considering the ICC flag in the network as well.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-394705729-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 460.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 88.94 GB
 Metadata Space Used: 958.5 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.797 GiB
Name: glenntest.novalocal
ID: G37T:BQMP:MOF5:NI5M:CEWW:XLFG:OWIX:5ZZN:QQXF:BTCX:PAZP:RO5D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Seen on openstack instance as well as a vSphere virtual machine

### LINKED ISSUE #27449: docker network name validation is not so strict
**Description**
As container name and volume name must be strict with regex `[a-zA-Z0-9][a-zA-Z0-9_.-]`. While network name is so casual that just not be empty. I think it is not so reasonable.

In addition, One confusion that why one character name for a container or volume is invalid. ping @vdemeester @vdemeester 

**Steps to reproduce the issue:**
1. `docker network create ^`, it works

**Describe the results you received:**
It works.

```
root@ubuntu:~# docker network create ^
eb995b6be7ef87ce0ed14c6a8143e7bef1aa7627ab027475df304ec96588f0fd
```

**Describe the results you expected:**

```
docker: Error response from daemon: Invalid network name (^), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 63
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 455
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: 4yghf0i19aa9a65dgsyitqns3
 Is Manager: true
 ClusterID: 7bgsisgkf388rd3fpz5i4k71s
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.59.103
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 118
 System Time: 2016-10-08T01:49:16.635764341+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 a=b
Insecure Registries:
 192.168.1.22:5500
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by sanimej**
Fixes #25497
Fixes #26724
also fixes https://github.com/docker/docker/issues/27449
Related to #26880

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by allencloud** [comment]
also fixes https://github.com/docker/docker/issues/27449

**Comment by thaJeztah** [comment]
@sanimej first issue https://github.com/docker/docker/pull/25794 looks to be the wrong one, can you check?

**Comment by AkihiroSuda** [comment]
CI failing
```
07:44:10 FAIL: docker_cli_network_unix_test.go:1659: DockerNetworkSuite.TestDockerNetworkCreateDeleteSpecialCharacters
07:44:10 
07:44:10 docker_cli_network_unix_test.go:1660:
07:44:10     dockerCmd(c, "network", "create", "test@#$")
07:44:10 docker_utils.go:505:
07:44:10     c.Assert(result, icmd.Matches, icmd.Success)
07:44:10 ... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc421103a20), ExitCode:1, Error:(*exec.ExitError)(0xc4234c0780), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc4208207e0), errBuffer:(*cmd.lockedBuffer)(0xc420820870)} ("\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker network create test@#$\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: invalid name: test@#$ includes invalid characters, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed\n\n")
07:44:10 ... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
07:44:10 ... 
07:44:10 Command: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker network create test@#$
07:44:10 ExitCode: 1, Error: exit status 1
07:44:10 Stdout: 
07:44:10 Stderr: Error response from daemon: invalid name: test@#$ includes invalid characters, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
07:44:10 
07:44:10 
07:44:10 Failures:
07:44:10 ExitCode was 1 expected 0
07:44:10 Expected no error
```

**Comment by allencloud** [comment]
yes @AkihiroSuda 
newly vendored libnetwork validates the network name more strictly. So maybe we need to update the test case as well. @sanimej

**Comment by cpuguy83** [comment]
```
07:32:20 FAIL: docker_cli_network_unix_test.go:1659: DockerNetworkSuite.TestDockerNetworkCreateDeleteSpecialCharacters
07:32:20 
07:32:20 docker_cli_network_unix_test.go:1660:
07:32:20     dockerCmd(c, "network", "create", "test@#$")
07:32:20 docker_utils.go:505:
07:32:20     c.Assert(result, icmd.Matches, icmd.Success)
07:32:20 ... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc420dc7080), ExitCode:1, Error:(*exec.ExitError)(0xc420593120), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc4201acea0), errBuffer:(*cmd.lockedBuffer)(0xc4201ad200)} ("\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker network create test@#$\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: invalid name: test@#$ includes invalid characters, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed\n\n")
07:32:20 ... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
07:32:20 ... 
07:32:20 Command: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker network create test@#$
07:32:20 ExitCode: 1, Error: exit status 1
07:32:20 Stdout: 
07:32:20 Stderr: Error response from daemon: invalid name: test@#$ includes invalid characters, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
07:32:20 
```

**Comment by sanimej** [comment]
@thaJeztah Corrected the issue number. Its #25497

**Comment by sanimej** [comment]
@allencloud Yes, I will update the test to avoid the invalid characters in the name.

**Comment by thaJeztah** [comment]
ping @mrjana @mavenugo PTAL

**Comment by mrjana** [comment]
LGTM

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
