### PR TITLE
Add SecretUpdate method to client

### LINKED ISSUE #28678: Add a `SecretUpdate` method to API client (not CLI)
There is an API endpoint which exists for updating metadata for a secret (i.e., labels) but there is not yet a method on the Go client in the `github.com/docker/docker/client` package.

Note: this issue is **not** requesting that we add a CLI command for updating a secret.

### PR DESCRIPTION
**Pull request by jlhawn**
closes #28678

### CODE REVIEW

**Comment by jlhawn** [comment]
@ehazlett PTAL

**Comment by tonistiigi** [comment]
LGTM

**Comment by ehazlett** [comment]
LGTM

**Comment by vdemeester** [comment]
Design SGTM to me too
ping @diogomonica 👼

**Comment by jlhawn** [comment]
Just spoke offline with @diogomonica - do you think it would be okay for the method clear out all fields of the secretSpec except for `Labels` before submitting the request? It would be a small update.

**Comment by tonistiigi** [comment]
@jlhawn For other objects that don't allow renaming we expect client to send the old name back and error out if they send something different. `Data` can remain as exception as it is very special to secrets but most important is to verify that we have proper validation on server side so we only allow modifications of labels.

**Comment by diogomonica** [comment]
Agreed with @tonistiigi . This should be: GET SecretSpec, modify SecretSpec, submit SecretSpec.

The fact that the SecretSpec that is returned in the get has `nil` Data is a detail.

**Comment by diogomonica** [comment]
LGTM

**Comment by thaJeztah** [comment]
Looks like the API for this endpoint is not documented; if this is officially part of the 1.25 API, it should probably be added to swagger.yml https://github.com/docker/docker/blob/master/api/swagger.yaml

**Comment by jlhawn** [comment]
@thaJeztah I think it was intentionally left undocumented cc @ehazlett

**Comment by jlhawn** [comment]
well, not intentionally left undocumented - it may have just been forgotten. But it is intentionally not exposed through the CLI

**Comment by diogomonica** [comment]
It should be documented, even though it's not exposed through the CLI. Arguably it should be better documented than the other ones, since it has the no-data no-name update quirks.

**Comment by thaJeztah** [comment]
Yup, I think there's more features in the API that we don't expose through the CLI, but if it's a stable API, then it should be documented

**Comment by jlhawn** [comment]
@thaJeztah okay, I've updated this PR. I had to rebase on master because at the time when I originally submitted this PR, there were no other documented `/secrets/...` API endpoints in the `swagger.yaml` file. Is this all that I need to do for documentation? It looks like that file is only for v1.26 of the API. I'm not sure what to do for 1.25.

**Comment by vdemeester** [comment]
@jlhawn depends if we want it to be there for 1.13 or not.

**Comment by jlhawn** [comment]
rebasing because my addition to the `api/swagger.yaml` file conflicts with recent changes from @bfirsh 

@vdemeester I don't really care whether this gets into 1.13 or not - I just want to be able to vendor this client package with the `SecretUpdate()` method.

**Comment by thaJeztah** [comment]
@jlhawn test is failing;

```
23:13:49 # github.com/docker/docker/cli/command/service
23:13:49 cli/command/service/update_test.go:434: cannot use apiClient (type secretAPIClientMock) as type "github.com/docker/docker/client".SecretAPIClient in argument to getUpdatedSecrets:
23:13:49 	secretAPIClientMock does not implement "github.com/docker/docker/client".SecretAPIClient (missing SecretUpdate method)
```

**Comment by thaJeztah** [comment]
This should fix it;

```patch
diff --git a/cli/command/service/update_test.go b/cli/command/service/update_test.go
index a6df6b9..bb93192 100644
--- a/cli/command/service/update_test.go
+++ b/cli/command/service/update_test.go
@@ -401,6 +401,9 @@ func (s secretAPIClientMock) SecretRemove(ctx context.Context, id string) error
 func (s secretAPIClientMock) SecretInspectWithRaw(ctx context.Context, name string) (swarm.Secret, []byte, error) {
        return swarm.Secret{}, []byte{}, nil
 }
+func (s secretAPIClientMock) SecretUpdate(ctx context.Context, id string, version swarm.Version, secret swarm.SecretSpec) error {
+       return nil
+}
```

**Review by thaJeztah — APPROVED** [review]
changes LGTM, but can you squash the test-commits? (for the record; CI is green)

**Comment by jlhawn** [comment]
@thaJeztah I've squashed the test file commit into the commit which adds the update method. The `swagger.yaml` file change is still a separate commit though.

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
