### PR TITLE
Reutrn immediately when inspect connection failed

### LINKED ISSUE #17708: Docker inspect returns [] when it has no permissions to docker.sock
```
$ docker inspect 2b81d178e32a
[]
# docker inspect 2b81d178e32a
[
{
    "Id": "2b81d178e32ad259b7fff5caca03b83111db452e0d6710....
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Fixes #17708

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by LK4D4** [comment]
@cpuguy83 is this for 1.9.1?

**Comment by thaJeztah** [comment]
Added it to the milestone because the related issue is on the milestone

**Pull request merged**
