### PR TITLE
convert map value from struct to bool

### PR DESCRIPTION
**Pull request by duglin**
Just for @calavera !! :-)
Per: https://github.com/docker/docker/pull/17789#discussion_r44333133

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by LK4D4** [comment]
I think some checking logic in code should be simplified too. like if `map[val]` instead of `if _, ok := map[val]; ok`

**Comment by duglin** [comment]
@LK4D4 oh, I like that!  Done

**Comment by calavera** [comment]
LGTM

**Comment by phemmer** [comment]
Just curious, but why? `map[string]struct{}` is a fairly common go technique when you want the behavior of a set.

**Comment by calavera** [comment]
@phemmer It's mostly personal taste, tbh. Empty structs don't provide any value, and the code resulting when used as a "Set" is more readable with booleans:

```go
if replaceEnvAllowed["foo"] {
}
```

VS

```go
if _, ok := replaceEnvAllowed["foo"]; ok {
}
```

**Comment by phemmer** [comment]
> Empty structs don't provide any value

They do have some value, in that they don't result in an allocation for the value (empty structs are size 0). But since this map never changes, that point is kinda moot.

**Comment by vdemeester** [comment]
LGTM 🐼 waiting for green :green_heart:

**Pull request merged**
