### PR TITLE
add note that windows does not support managed plugins

### PR DESCRIPTION
**Pull request by thaJeztah**
Adding a note, per https://github.com/docker/docker/pull/28457#issuecomment-261086091

ping @anusha-ragunathan @vieux

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by thaJeztah** [comment]
Was just thinking; should there be a note about plugins not being supported on other architectures (arm etc)?

**Comment by anusha-ragunathan** [comment]
Makes sense to add other unsupported archs.

**Comment by vieux** [comment]
I'm not sure, arm might work, there is no arm plugin.

**Comment by thaJeztah** [comment]
ok, let's merge this one, we can add more info if needed

**Pull request merged**
