### PR TITLE
Adds clarification to behavior of missing directories.

### LINKED ISSUE #20920: Docker cp does not create intermediate destination directories.
Output of `docker version`:

```
Docker version 1.8.0, build 0d03096
```

Output of `docker info`:

```
Containers: 1
Images: 5
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
CPUs: 8
Total Memory: 1.955 GiB
Name: boot2docker
ID: PVUD:7SAK:UKCM:SWAM:VO4D:HAVW:WJWE:L7J6:OKOY:EHOE:EOMP:ED3Y
Debug mode (server): true
File Descriptors: 11
Goroutines: 29
System Time: 2016-03-03T17:42:38.217741179Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
MacOS X

List the steps to reproduce the issue:
1. Create a docker image with a file at `/app/build/version.txt`
2. Start a container for that image with
`CONTAINER_ID=$(docker create foo:123)`
3. Attempt to copy the file out of the container to a path that doesn't exist with
`docker cp ${CONTAINER_ID}:/app/build/version.txt build/version.txt`
--> `lstat /path/to/working/directory/build: no such file or directory`
4. Try again with just a destination directory with
`docker cp ${CONTAINER_ID}:/app/build/version.txt build/`
--> `no such directory`
5. Create the directory with
`mkdir build`
6. Try again with either command.
--> Notice success.

Describe the results you received:

`no such file or directory`
`no such directory`

Describe the results you expected:

Successful copy of the file.

Provide additional info you think is important:
The documentation [here](https://docs.docker.com/engine/reference/commandline/cp/) is very explicit about the expected behavior in this situation.  In particular, `SRC_PATH` specifies a file and `DEST_PATH` does not exist, so the file should be created at `DEST_PATH`.  The documentation implies that the directory structure leading up to `DEST_PATH` will be created if necessary.

### PR DESCRIPTION
**Pull request by MicahZoltu**
Fixes #20920

### CODE REVIEW

**Comment by thaJeztah** [comment]
Awesome, thanks!

LGTM

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (51/50 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:59730 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1abctO-0000N5-KY
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:42:50 -0500
Date: Thu, 03 Mar 2016 15:42:10 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457048530;
	bh=aax3UGjWJ5gigTTAGCzu0q4HrZvybs3FKR+ACa7J8NU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Q1rj9PtOLgEy1bxZwXsoVUqp3/ui61/kXF8AG8xbZgH2YiNAAFbd32/aJiYd6W/o2
	 0R9edawpLf5fcqSJieWGckSBTiaA6UE1hjtIjKTWrX/RAb0e6xKobXjwPtLpF3jtTo
	 8WbxcV8SSctzdC7b+4CZHamFZlsEYi6TWqQkXilo=

**Comment by jlhawn** [comment]
LGTM

**Comment by thaJeztah** [comment]
removing cherry-pick; this will go out with the 1.11 release

**Pull request merged**
