### PR TITLE
Handle paused container when restoring without live-restore set

### LINKED ISSUE #31699: Unkillable container after pause and kill -9 dockerd
**Description**

**Steps to reproduce the issue:**
1. docker run -d --name test busybox top
2. docker pause test
3. pkill -9 dockerd
4. start dockerd

**Describe the results you received:**
In docker, container is marked as exited, but is still running (in paused state).

This causes some really nasty behavior as well if you shutdown the daemon again and restart it.
`Store.Cleanup()` fails with ebusy (because there's still a process running).
Daemon takes longer to start trying to sync up state:

```
DEBU[0001] Loaded container 951cc0a5d14df315cff3ab06f26df179c12bb834c2860446a2da3283b957fc06
DEBU[0001] Loaded container 95aee30e1454c724a181e69e3267e2458e46e483b05cbc3a332b7b2a5512d86a
WARN[0001] libcontainerd: client is out of sync, restore was called on a fully synced container (951cc0a5d14df315cff3ab06f26df179c12bb834c2860446a2da3283b957fc06).
ERRO[0013] state changed                                 container=951cc0a5d14df315cff3ab06f26df179c12bb834c2860446a2da3283b957fc06 state=exit
```

> **note**: the error log about "state changed" is something I put in for debugging
> **note**: it's getting an event from containerd on the paused container that the container exited, but it did not.
> **note**: the 12 second delay caused in this case.

```
$ docker-runc list
ID                                                                 PID         STATUS      BUNDLE                                                                                       CREATED
951cc0a5d14df315cff3ab06f26df179c12bb834c2860446a2da3283b957fc06   23684       paused      /run/docker/libcontainerd/951cc0a5d14df315cff3ab06f26df179c12bb834c2860446a2da3283b957fc06   2017-03-09T17:10:53.812306125Z
```

Calling `docker-runc resume` on the paused container triggers an event from containerd:

```
DEBU[0168] libcontainerd: received containerd event: &types.Event{Type:"exit", Id:"951cc0a5d14df315cff3ab06f26df179c12bb834c2860446a2da3283b957fc06", Status:0x89, Pid:"init", Timestamp:(*timestamp.Timestamp)(0xc42098b020)}
WARN[0168] libcontainerd: unknown container 951cc0a5d14df315cff3ab06f26df179c12bb834c2860446a2da3283b957fc06
```

**Describe the results you expected:**

State for a paused container should be correctly synced.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is really an edge case, but also had some really weird issues when dropping from a live-restore enabled daemon to disabled with all this pause stuff as well, but it's proven difficult to reproduce.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-dev
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   58562d7
 Built:        Thu Mar  9 17:05:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-dev
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   58562d7
 Built:        Thu Mar  9 17:05:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 17.04.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 665e84e6c28653a9c29a6db601636a92d46896f3
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: cf13527bdfae
ID: T4MV:VSAK:73VI:SAB5:3UYK:HYA3:RBNW:FCDT:V4LA:GV5W:IUOD:MRRN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 23
 System Time: 2017-03-09T17:57:26.097121608Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested in dind (on d4mac) trying to pinpoint an issue with #29554.

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

-- 

Fixes #31699

### CODE REVIEW

**Comment by crosbymichael** [comment]
Shouldn't we send the signal first then unpause?

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by mlaventure** [comment]
@crosbymichael `SIGTERM` is sent before the call to `Resume()`

**Review by cpuguy83 — CHANGES_REQUESTED** [review]
~~Somehow this is effecting restart policy on restore, in that containers with restart=always are not restarting when the resume is required.~~

nevermind, that doesn't make sense, it was paused ;)

**Review by cpuguy83 — APPROVED** [review]

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
