### PR TITLE
Explain the cool image in README.md

### PR DESCRIPTION
**Pull request by yecril71pl**
The cool image is displayed in a text-based browser as 

> Docker L

which is nonsense.  README.md should provide information, not impression.

### CODE REVIEW

**Comment by cpuguy83** [comment]
:-1: -1, logo is great.
Feel free to change the text from "Docker L" to "Docker Logo"

Also the commit needs to be signed. `git commit -a --amend -s --no-edit`

**Comment by yecril71pl** [comment]
The text ‘Docker Logo’ will not make sense as a separate paragraph either.  What information are you trying to convey with this logo?

**Comment by crosbymichael** [comment]
I think this should just be Docker Logo if we have to have any text at all.  All the information explaining docker is above so no need to add another sentence here, it's mostly because you have to have something for the markdown image as far as I know.

**Comment by calavera** [comment]
I agree with @crosbymichael. The new description is neither accurate nor represents what the link it goes with represents. Please, change it to `Docker logo`.

**Comment by yecril71pl** [comment]
The text ‘Docker L’ is not linked at all after processing the file README.md with markdown, so neither would be your suggestion ‘Docker Logo’ and the result would be confusing to the reader.  However, I can see that the image (and the text) linked in the GitHub rendering.  Can you advise me how to reproduce the link off line?

**Comment by yecril71pl** [comment]
@crosbymichael, the requirement that an image must be backed up with text can be technically satisfied by placing any text but the intention of the requirement is that the text should make sense in the context when it replaces the image.

**Comment by crosbymichael** [comment]
@yecril71pl we merge a PR remove the alt text all together.  Thanks for the suggestion to change this.

**Pull request closed without merging**
