### PR TITLE
Return old Config fields for API < v1.20

### LINKED ISSUE #16665: 1.9: Config.Cpuset (and probably others) are missing in inspect
I realize that `Config.Cpuset` has been replaced with `HostConfig.CpusetCpus` but this is a breaking change for API <= 1.20.  Only 1.21 should not return these fields if we really want to drop them.

### PR DESCRIPTION
**Pull request by runcom**
- Fix #16665

/cc @ibuildthecloud 

Signed-off-by: Antonio Murdaca amurdaca@redhat.com

### CODE REVIEW

**Comment by icecrime** [comment]
Thanks! LGTM assuming green.

**Comment by vdemeester** [comment]
It's green ! :wink: 

LGTM 🐰

**Comment by runcom** [comment]
Let's wait @ibuildthecloud for the  LGTM then :)

**Comment by ibuildthecloud** [comment]
I can't test until late tonight, but I glady will.

**Comment by thaJeztah** [comment]
Looks like this needs docs changes as well; IIU this brings back these fields below `Config`; I checked the docs and looks like the example output in these versions of the API docs need updating;

- https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.20.md#inspect-a-container
- https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.19.md#inspect-a-container
- https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.18.md#inspect-a-container

**Comment by runcom** [comment]
I don't think it's putting these fields back, iiu correctly from the issue,  the new api version 1.21 which will ship with docker 1.9 currently hides those fields. Those fields have been deprecated in 1.20 but probably they were directly removed and showed only for api minor or equal to 1.19 instead of 1.20. Please someone confirm my view :)

**Comment by icecrime** [comment]
Yeah I think we're good without docs updates too. I'll just keep this open in `4-merge` and give @ibuildthecloud some time to test.

**Comment by ibuildthecloud** [comment]
This didn't work for me, I'm investigating why.

**Comment by thaJeztah** [comment]
From the issue;

> Also, should have mentioned that I'm testing with 1.18 client.

Should this fix be in a `ContainerInspectPre121`?

**Comment by ibuildthecloud** [comment]
@runcom The 's' is supposed to be lower case, so `Cpuset`.  All params are 
```json
"Memory": 0,
"MemorySwap": 0,
"CpuShares": 0,
"Cpuset": ""
```

Also, these params were dropped in v1.20 (I just confirmed in Docker 1.8).  So these fields should be returned for <=1.19, with this patch they are returned for 1.20 too.

**Comment by runcom** [comment]
Fixing

**Comment by runcom** [comment]
Push forced, I see it was `Cpuset` with lowercase `s` https://github.com/calavera/docker/blob/c9207bc0aa57745876a3422d2cbc290be7c53da8/api/types/types.go#L268

@ibuildthecloud PTAL

**Comment by runcom** [comment]
1.19 and lower:
```
curl -s http://localhost:2375/v1.19/containers/7a/json | jq ".Config"
{

  "Cpuset": "",
  "CpuShares": 0,
  "MemorySwap": 0,
  "Memory": 0,

  "VolumeDriver": "",
  "StopSignal": "SIGTERM",
  "Labels": {},
  "OnBuild": null,
  "MacAddress": "",
  "NetworkDisabled": false,
  "Tty": false,
  "ExposedPorts": null,
  "AttachStderr": false,
  "AttachStdout": false,
  "AttachStdin": false,
  "User": "",
  "Domainname": "",
  "Hostname": "7a109e234350",
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": null,
  "Cmd": [
    "top"
  ],
  "Image": "busybox",
  "Volumes": null,
  "WorkingDir": "",
  "Entrypoint": null
}
```
1.20:
```
curl -s http://localhost:2375/v1.20/containers/7a/json | jq ".Config"
{
  "VolumeDriver": "",
  "StopSignal": "SIGTERM",
  "Labels": {},
  "OnBuild": null,
  "MacAddress": "",
  "NetworkDisabled": false,
  "Tty": false,
  "ExposedPorts": null,
  "AttachStderr": false,
  "AttachStdout": false,
  "AttachStdin": false,
  "User": "",
  "Domainname": "",
  "Hostname": "7a109e234350",
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": null,
  "Cmd": [
    "top"
  ],
  "Image": "busybox",
  "Volumes": null,
  "WorkingDir": "",
  "Entrypoint": null
}
```

**Comment by icecrime** [comment]
Thanks @runcom, LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by runcom** [comment]
@ibuildthecloud see if it's now working for you pls

**Pull request merged**
