### PR TITLE
change exportImage to top-level func

### PR DESCRIPTION
**Pull request by azurezk**
Signed-off-by: Kun Zhang zkazure@gmail.com

### CODE REVIEW

**Comment by duglin** [comment]
Do we know why?

**Comment by icecrime** [comment]
@azurezk I understand you did this to follow the `// FIXME` comment, unfortunately I'm afraid it is outdated / incorrect :-( I don't really see the need for this, we would probably be better off removing that comment.

**Comment by jlhawn** [comment]
Just removing the `FIXME`s then?
LGTM

**Comment by jfrazelle** [comment]
awesome removing the FIXME's LGTM

**Pull request merged**
