### PR TITLE
Add John Howard to our alumni

### PR DESCRIPTION
**Pull request by thaJeztah**
Follow-up to https://github.com/moby/moby/pull/42309 Thank you John!!

**- A picture of a cute animal (not mandatory but encouraged)**

golden-retriever-piano

[image: Melinda Hampton](https://www.pinterest.com/pin/458241330808898918/)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@lowenna @moby/moby-maintainers ptal

**Review by estesp — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM. Thanks John for his contribution over the years 👍

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
LGTM!

**Comment by lowenna** [comment]
Love it, and thank you 💛 I will (and do!) miss this community. You are all rock stars. 

LGTM.

**Review by lowenna — APPROVED** [review]

**Comment by lowenna** [comment]
I think I can merge this one still....  Thank you everyone.

**Pull request merged**
