### PR TITLE
[24.0 backport] Upstart & sysvinit cleanup

### PR DESCRIPTION
**Pull request by neersighted**
- Backport of https://github.com/moby/moby/pull/45548
- Backport of https://github.com/moby/moby/pull/45551

Despite https://github.com/moby/moby/pull/45551#issuecomment-1552266889; I'd like to backport this into 24.0, as we're using these scripts in Docker CE (https://github.com/docker/docker-ce-packaging/pull/914, https://github.com/docker/docker-ce-packaging/pull/926) and I'd rather leave things in a less-broken state.

I'm also happy to do this on 23.0 and 20.10 if @corhere / @cpuguy83 are open it it.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by neersighted** [comment]
It looks like GitHub Actions is not home...

**Comment by thaJeztah** [comment]
Let's try a close/reopen

**Comment by thaJeztah** [comment]
We have lift-off! 🚀

**Review by corhere — APPROVED** [review]
SGTM. I wouldn't mind 23.0 and 20.10 backports, either, so long as @ameyag is also okay with it.

**Comment by ameyag** [comment]
I'm okay with 20.10 and 23.0 backports.

**Comment by thaJeztah** [comment]
@ameyag backports are opened; feel free to review https://github.com/moby/moby/pull/46046 and https://github.com/moby/moby/pull/46047

**Pull request merged**
