### PR TITLE
Add initial new IRC administration cheat sheet of sorts

### PR DESCRIPTION
**Pull request by tianon**
cc @shykes 

(as requested :heart:)

### CODE REVIEW

**Comment by SvenDowideit** [comment]
i recon it'd be good to list all the channels we recognise

**Comment by jfrazelle** [comment]
Those are on dockerproject.com, easier to maintain... But we could add here
too

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
Oh! There's a homepage on dockerproject.com as well, was only aware of the master build downloads lolz

**Comment by jfrazelle** [comment]
thats a WIP :) but so far has some good details

**Comment by jfrazelle** [comment]
we are building out some tools and information pertaining to just the project, more to come...

**Comment by thaJeztah** [comment]
@jfrazelle while working on that, I think forums.docker.com should be included there too.

Perhaps you could bring this up as well; https://github.com/docker/docker/issues/9300 :smile:

**Pull request merged**
