### PR TITLE
Docker EE integration test fixes

### PR DESCRIPTION
**Pull request by chris-crone**
**- What I did**
Added Docker EE specific fixes/work arounds so that the moby integration tests can be used against it.

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by chris-crone** [comment]
I needed to do the same not found check for containers as for volumes so refactored the code into an `isErrNotFoundSwarmClassic`.

**Review by dnephin — APPROVED** [review]
LGTM

**Pull request merged**
