### PR TITLE
sysinfo: add IPv4Forwarding check

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by Mashimiao** [comment]
ping

**Comment by Mashimiao** [comment]
ping @icecrime , @duglin , @LK4D4 , @cpuguy83

**Comment by LK4D4** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
