### PR TITLE
integration-cli: support remote docker host that uses TLS - fixes #17952

### LINKED ISSUE #17952: integration-cli: can no longer run integration-cli tests using TLS against a remote docker host
In docker 1.8 I could run the integration-cli tests against a *remote* host - but this no longer works since docker 1.9, e.g.:
```
export DOCKER_HOST=tcp://remoteserver:2376
export DOCKER_CERT_PATH=/home/user/.docker/machine/machines/default
export DOCKER_TLS_VERIFY=1
$ go test -v -check.f TestInfo
panic: Init failed to get version: unexpected EOF. Res=<nil>

goroutine 1 [running]:
github.com/docker/docker/integration-cli.init.2()
	/Users/toddw/goroot/src/github.com/docker/docker/integration-cli/docker_utils.go:58 +0x467
github.com/docker/docker/integration-cli.init()
	/Users/toddw/goroot/src/github.com/docker/docker/integration-cli/docker_hub_pull_suite_test.go:90 +0x871
main.init()
	github.com/docker/docker/integration-cli/_test/_testmain.go:56 +0x4a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 19 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
exit status 2
FAIL	github.com/docker/docker/integration-cli	242.110s
```

The test above is getting an EOF error because the server in question is expecting a TLS handshake, but instead it's getting a straight HTTP request for the docker test code.

I'll submit a PR that fixes this problem (or, at least it works for me).

### PR DESCRIPTION
**Pull request by twhiteman**
Fixes #17952

Signed-off-by: Todd Whiteman todd.whiteman@joyent.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@twhiteman looks like you need to gofmt your changes.

**Comment by twhiteman** [comment]
I guess I should have first verified it in my own container... learning... will re-push once it's happy.

**Comment by LK4D4** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

wondering what caused this tho :/

**Comment by twhiteman** [comment]
I believe that most of the old (existing) tests use the docker binary, but some of the new code around 1.8 or 1.9 time frame was written to interact directly with the docker remote API, and since most docker test environments (jenkins, linux container builds) have a docker file socket (/var/sock/docker) then things just worked in that case.

**Pull request merged**
