### PR TITLE
Also generate "InRelease" files for newer APT clients

### LINKED ISSUE #21707: apt repo is missing files that would speed up updates
@dmp42 @kencochrane 

apt.dockerproject.org is missing `InRelease` and translation files in `main/i18n`. This causes apt-get to request many files before giving up. Logs example below. This could be 3 requests instead of 14.

InRelease is an inline-signed Release used by newer clients.
https://wiki.debian.org/RepositoryFormat#A.22Release.22_files

For translations, providing just "en" would fix this for the vast majority of clients, but we should also provide translations for all languages we support.

https://wiki.debian.org/RepositoryFormat#A.22Translation.22_indices

```
2016-03-31	21:49:04	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/InRelease	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	172	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:04	IAD53	579	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/Release.gpg	304	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Miss	apt.dockerproject.org	https	221	0.026	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Miss
2016-03-31	21:49:04	IAD53	579	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/Release	304	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Miss	apt.dockerproject.org	https	220	0.025	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Miss
2016-03-31	21:49:05	IAD53	579	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/binary-amd64/Packages.bz2	304	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Miss	apt.dockerproject.org	https	240	0.439	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Miss
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en_US.bz2	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	191	0.000	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en.bz2	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	188	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en_US.xz	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	190	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en.xz	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	187	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en_US.lzma	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	192	0.002	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en.lzma	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	189	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en_US.gz	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	190	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en.gz	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	187	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en_US	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	190	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
2016-03-31	21:49:05	IAD53	803	GET	d2iat6c11jl2jk.cloudfront.net	/repo/dists/ubuntu-wily/main/i18n/Translation-en	403	-	Debian%2520APT-CURL/1.0%2520(1.0.10.2ubuntu1)	-	-	Error	apt.dockerproject.org	https	187	0.001	-	TLSv1.2	ECDHE-RSA-AES128-GCM-SHA256	Error
```

### PR DESCRIPTION
**Pull request by tianon**
Fixes #21707

cc @jfrazelle @kencochrane

I don't have an easy setup ATM to test this, but this should do the trick for generating the newer `InRelease` files. :smile:

### CODE REVIEW

**Comment by thaJeztah** [comment]
nice, that was fast!

also /cc @tiborvass in case this is needed in the bump-branch

**Comment by tianon** [comment]
Someone should definitely test it before we commit to a cherry-pick though :sweat_smile:

**Comment by thaJeztah** [comment]
nah, testing is sooooo overrated :stuck_out_tongue_winking_eye:

**Comment by tianon** [comment]
Just noticed and fixed a bug where I had "basename" instead of "dirname"
:innocent:

**Comment by kencochrane** [comment]
Awesome, I'll see if I can test it in the morning.

**Comment by icecrime** [comment]
cc @joegross

**Comment by thaJeztah** [comment]
We just discussed this; we're not going to use this for the 1.11 release for now, because we really want to give it a proper testing to see it doesn't mess up things, but if we've been able to give it a proper test, we can implement it for the 1.12 release

**Comment by jfrazelle** [comment]
oooo shiny LGTM

On Fri, Apr 1, 2016 at 10:01 AM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> We just discussed this; we're not going to use this for the 1.11 release
> for now, because we really want to give it a proper testing to see it
> doesn't mess up things, but if we've been able to give it a proper test, we
> can implement it for the 1.12 release
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/21708#issuecomment-204470672>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
ping @tiborvass could you review this?

**Comment by thaJeztah** [comment]
ping @tiborvass @kencochrane any updates on this one? Can we merge this?

**Comment by kencochrane** [comment]
If it is good with @tiborvass I'm fine as well.

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
