### PR TITLE
Use -f for rm instead of kill before

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by LK4D4** [comment]
ping @cpuguy83 @duglin

**Comment by cpuguy83** [comment]
This seems to have caused a lot of issues.

**Comment by LK4D4** [comment]
@cpuguy83 Yup, sorry for that.

**Comment by duglin** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by jfrazelle** [comment]
We can get rid of that one defer I  had to add for overlay in overlay now

**Pull request merged**
