### PR TITLE
Remove LCOW: pkg/containerfs: drop ContainerFS abstraction

### PR DESCRIPTION
**Pull request by corhere**
* Relates to #39533

The `containerfs.ContainerFS` and `containerfs.Driver` interfaces were added in #34252 in order to support container root filesystems mounted in remote and foreign environments, specifically to support Linux Containers on Windows. LCOW support has been dropped from Moby, and with it the need to support container root filesystems mounted outside of the host's native filesystem hierarchy. The `containerfs` interfaces have served their purpose but are no longer needed. Retaining support for remote and foreign container filesystems is getting in the way of fixing bugs and making enhancements, so it is time to retire the abstraction.

**- What I did**
Reverted large parts of #34252 by replacing uses of the `containerfs.ContainerFS` and `containerfs.Driver` interfaces with native filesystem and path manipulation APIs.

**- How I did it**
golang.org/x/tools/cmd/eg, `gofmt -r` and manual search-and-replace.

**- How to verify it**
CI 🟢 

**- Description for the changelog**
N/A. Not a user-visible change.

**- A picture of a cute animal (not mandatory but encouraged)**

Cows on greener pastures (get it?)

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM! That's sooooo much cleaner ❤️

**Review by tianon — APPROVED** [review]
Looks good!

Reviewing commit-by-commit, it was a little weird to see it convert to a `string` type, then touch all the same lines to turn it into an alias, then remove it, but it made the progression of the removal really clear. :+1:

**Comment by thaJeztah** [comment]
> Reviewing commit-by-commit, it was a little weird to see it convert to a string type, then touch all the same lines to turn it into an alias, then remove it, but it made the progression of the removal really clear. 👍

Yes, was also considering if squashing was worth it, but it definitely makes the history more descriptive, so I think it's worth the trade-off of the extra code churn 👍

**Comment by thaJeztah** [comment]
Let me bring this one in 👍 

I did a quick check, and https://github.com/moby/moby/pull/44196 (which we may consider backporting) doesn't conflict with this one, so no issues on that front.

**Pull request merged**
