### PR TITLE
add --network option for docker build

### LINKED ISSUE #10324: Please add --add-host=[], --net options to docker build
This is a feature request to add the `--add-host=[]` (currently availble for `docker run`) to `docker build` also. This would be very handy.

### PR DESCRIPTION
**Pull request by tonistiigi**
carry #20987

fixes https://github.com/docker/docker/issues/10324

@vdemeester

### CODE REVIEW

**Comment by thaJeztah** [comment]
don't forget to update the reference docs, man pages, and API docs + changelog

**Review by vdemeester — APPROVED** [review]
LGTM 🐸
@tonistiigi Ah one question though, should we have a `--net` hidden flag or not ? (/cc @dnephin @thaJeztah on that question too)

**Comment by thaJeztah** [comment]
I don't think we should add `--net` as alias here. This is a new feature, and there's never been a `--net`, so no need to add it for backward compatibility. We can add it if there's a lot of requests, but let's keep it simple now

**Comment by mavenugo** [comment]
LGTM

**Comment by sandyskies** [comment]
I think just --network will be  fine.

**Comment by cpuguy83** [comment]
Seems to be missing `--add-host` from the referenced issue.

**Comment by cpuguy83** [comment]
But otherwise LGTM so moving to docs-review, we can follow-up with `add-host`

**Review by vdemeester — APPROVED** [review]
docs LGTM 🐸
/cc @thaJeztah

**Comment by thaJeztah** [comment]
Oh, looks like docs are missing for the CLI reference;

- https://github.com/docker/docker/blob/master/docs/reference/commandline/build.md

And man page;

- https://github.com/docker/docker/blob/master/man/docker-build.1.md

**Comment by icecrime** [comment]
Ping @justincormack @vikstrous FYI.

**Comment by vikstrous** [comment]
LGTM I don't think this will significantly decrease the reproducibility of builds since we really can't control the network during a build anyway.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by RoelVdP** [comment]
How does this fix #10324?

**Comment by thaJeztah** [comment]
@RoelVdP it adds --net to docker build

**Comment by ricardobranco777** [comment]
Does it fix https://github.com/docker/docker/issues/24824?

**Comment by RoelVdP** [comment]
@thaJeztah --add-host=[] was not added? If so, please re-open #10324

**Pull request merged**
