### PR TITLE
Don't turn off restart when sending some signals

### PR DESCRIPTION
**Pull request by ble**
Addressing #11065 

Be gentle? :)

### CODE REVIEW

**Comment by jfrazelle** [comment]
:santa:

**Comment by cpuguy83** [comment]
Can you add a test in integration-cli?

**Comment by ble** [comment]
@cpuguy83 

I was thinking maybe this should be a table-based test with 4+ cases:

1 each for SIGKILL, SIGINT, and SIGTERM
at least 1 for some other signals

but I really don't know what process I'd use for testing against.

The simplest case would be to just test signals that don't disable restarts:

1. start container
2. send non-terminating signal
3. somehow cause container's process to exit through another method
4. test that the container is still running after step 3.

**Comment by ble** [comment]
hmmm.  How about the old "echo foo | nc -l $SOMEPORTNUMBER" and I forward that port...

**Comment by tonistiigi** [comment]
`SIGTERM` and `SIGINT` can be ignored by the application and may not necessarily mean the container will be stopping.

**Comment by ble** [comment]
So should this be handled with an additional flag to ````docker kill````?

**Comment by icecrime** [comment]
*Pushing this back to design review as I don't think we're quite ready for code review.*

Thanks for the patch @ble, but I would agree with @tonistiigi here. If the application handles the signal as to trigger some kind of action (let's say: reload config) and *then* later on fails for some reason, it will not be restarted for a wrong reason.

I'll leave the discussion as per the proper fix to happen on #11065.

**Pull request closed without merging**
