### PR TITLE
optimize slow tests

### PR DESCRIPTION
**Pull request by mountkin**
**\- What I did**
Optimize 2 slow tests.

Before:

```
PASS: docker_cli_run_test.go:2751: DockerSuite.TestRunContainerWithReadonlyRootfs 16.561s
PASS: docker_cli_run_unix_test.go:910: DockerSuite.TestRunApparmorProcDirectory 19.075s
```

After:

```
PASS: docker_cli_run_test.go:2751: DockerSuite.TestRunContainerWithReadonlyRootfs   2.261s
PASS: docker_cli_run_unix_test.go:910: DockerSuite.TestRunApparmorProcDirectory 2.250s
```

**\- How I did it**
1. Merge multiple `docker run` command into one for `TestRunContainerWithReadonlyRootfs`
2. Change the image from `debian:jessie` to `busybox` for `TestRunApparmorProcDirectory`

**\- How to verify it**
`make test-integration-cli`

**\- A picture of a cute animal (not mandatory but encouraged)**
1c767db5c9ea15ce0f140dbcb5003af33b87b25e

Signed-off-by: Shijiang Wei mountkin@gmail.com

### CODE REVIEW

**Comment by cyphar** [comment]
I'm wondering whether this invalidates the test (since the old code was trying to make sure that *all* of them fail, but the current code only makes sure that at least *one* of them fails). For example, what happens if we have a regression with `/sys` becoming `rw` even with `--read-only`?

Maybe if you made it a `for` loop *in the shell script* then you could check the output for each file -- that should increase the speed without removing the validity of the test. Something like:

```
docker run --read-only sh -c 'for i in <list of files> { touch $i; echo "$? $i"; }'
```

Or similar (you could even use the error output from `touch`.

:+1: on switching from `debian:jessie` to `busybox`. Maybe we should look through the tests for more occurrences of that.

**Comment by mountkin** [comment]
> I'm wondering whether this invalidates the test (since the old code was trying to make sure that all of them fail, but the current code only makes sure that at least one of them fails). For example, what happens if we have a regression with /sys becoming rw even with --read-only?

Oh it's really a problem. 
Thanks for pointing out this @cyphar :+1: 
I'll update the code accordingly.

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
