### PR TITLE
Increase default connection timeout to 30s

### LINKED ISSUE #13307: Consider increasing (or allowing configuration of) connection timeout for registry related operations
At Mozilla we use Docker _mostly_ for CI on AWS ( at a fairly large scale so 1k~ or so machines running at a time if not more). Generally this works just fine but we hit some issues with the inflexibility of timeouts in docker when pull images in particular connection timeouts.

Can we increase the defaults to something like 30s or add config flags?

----

See:

https://github.com/docker/docker/blob/756b8f2fde210da5529e0a5480e149917ab25524/registry/registry.go#L53-L56

### PR DESCRIPTION
**Pull request by lightsofapollo**
Full context is in #13307
Closes: #13307

### CODE REVIEW

**Comment by LK4D4** [comment]
@lightsofapollo Hah, sorry :) You need to sign your commit.

**Comment by lightsofapollo** [comment]
@LK4D4 Magic incantation complete!

**Comment by duglin** [comment]
LGTM

**Comment by runcom** [comment]
LGTM if janky's happy

**Pull request merged**
