### PR TITLE
Bump containerd to 9dc2b3273db42c75368988a3885a3af

### PR DESCRIPTION
**Pull request by crosbymichael**
This bumps containerd's version to include a fix to memory stats and
making sure that the `Stats` field with the raw data is populated.

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by crosbymichael** [comment]
To make sure that we don't need anything else in this release I will take the containerd 0.2.2 release with the exact commit that is vendored in the docker release.

**Comment by thaJeztah** [comment]
Changes are https://github.com/docker/containerd/compare/021-fix...9dc2b3273db42c75368988a3885a3af

This fixes https://github.com/docker/docker/issues/22375 in the 1.11 bump-branch

**Comment by cpuguy83** [comment]
What, no tag?

**Comment by thaJeztah** [comment]
I think it'll get tagged once we're sure we have everything?

**Comment by tophj-ibm** [comment]
ignore the power check, I'm testing the jenkins config

**Comment by mlaventure** [comment]
@cpuguy83 @thaJeztah yes, we'll tag it before merging this.

**Comment by LK4D4** [comment]
Ignored power check
LGTM

**Comment by LK4D4** [comment]
Also I think this probably must be in sync with `hack/vendor.sh`

**Comment by crosbymichael** [comment]
Did ya not read my comment about tagging! ;)

**Comment by LK4D4** [comment]
@crosbymichael yeah, ignored together with powerpc build :D

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
