### PR TITLE
Removing unused getBoolParam func from api/server/server.go

### LINKED ISSUE #12199: Remove getBoolParam from api/server/server.go
It is unused. Also there is test for it in server_unit_test.go.

### PR DESCRIPTION
**Pull request by WiseTrem**
Closes #12199

### CODE REVIEW

**Comment by LK4D4** [comment]
@WiseTrem You forgot to remove test.
Also can you change top comment to `Fix #12199`? There are reserved words for github:
https://help.github.com/articles/closing-issues-via-commit-messages/
And I prefer Fix.

**Comment by WiseTrem** [comment]
@LK4D4 I just did everything as you said. Thanks.

**Comment by cpuguy83** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
