### PR TITLE
Close stdout/stderr fifo as soon as possible

### LINKED ISSUE #30063: dockerd leaks file descriptors after each 'docker exec -ti'
**Description**
Each 'docker exec -ti' creates stdin/stdout/stdin FIFO pipes with path /run/docker/libcontainerd/<container-id>/<other-id>-<stdout,stdin,stderr>.  Each pipe file is deleted exactly at the same time as 'docker exec' exits but file descriptors released only within 10-20 seconds delay. If you have a lot of small containers (around 100) and quickly execute a lot of small commands (like 'ansible -m setup' for all containers) through 'docker exec' it is easy to hit max number of open files limit for dockerd (which is 1024 by default) 

**Steps to reproduce the issue:**
1. from one console: sudo docker run --rm -ti --name leak ubuntu bash
2. from second console: while true; do sudo docker exec -ti leak bash -c 'echo 1'; done; 
3. from third console: sudo lsof -np $(pidof dockerd) | egrep '.\*?/[a-f0-9]\*?-(stdout|stdin|stderr)' |   awk '{print $9}' | sort | wc -l

**Describe the results you received:**
Number of open descriptor could reach 100-200

**Describe the results you expected:**
no more than 3 descriptors 

**Additional information you deem important (e.g. issue happens only occasionally):**

- If you hit max number of open files limit (
Error: Too many open files) during 'docker exec' is no longer possible to exec into the container. Even if you increase soft limit for dockerd.

- Can reproduce this on 1.12.3, 1.12.4, 1.12.5, 1.12.6

- **Occasionally descriptors remained open forever**(not in testcase provided above). I have found no way to reproduce yet but it constantly happens 1-2 day on one of my server.

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 30.87 GiB
Name: dshyshkin-thinkpad
ID: OD5W:DTUM:EXXT:62LW:OJ3C:4ART:CHQP:DWQK:TWRD:YSRD:SFSU:X37J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #30063

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by mlaventure** [comment]
Where were we closing those before?

**Comment by tonistiigi** [comment]
@mlaventure They were closed by the finalizer.

**Review by LK4D4 — APPROVED** [review]
LGTM

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by runcom** [comment]
should this go into 1.13 as well?

**Comment by tonistiigi** [comment]
@runcom I don't think this is very high priority. GC cleans up the fds, the pointers didn't leak.

**Comment by thaJeztah** [comment]
The linked issue was a combination of this, and a mis-configuration of the systemd unit file (the daemon had a `LimitNOFILE` of 1024, which is very low, causing this to produce issues. In a correctly configured daemon, I don't expect users to run into this

**Pull request merged**
