### PR TITLE
don't return error if can't delete non-existing container

### PR DESCRIPTION
**Pull request by sallyom**
Signed-off-by: Sally O'Malley somalley@redhat.com

### CODE REVIEW

**Comment by sallyom** [comment]
discovered this when a print statement was added before the return here: https://github.com/docker/docker/pull/18371/files#diff-56e050aac937f91b9152c08ee4f7517dL631
The statement printed in every test, ex)
PASS: docker_cli_attach_test.go:89: DockerSuite.TestAttachTtyWithoutStdin	0.422s
FAILED TO REMOVE
PASS: docker_cli_build_test.go:1575: DockerSuite.TestBuildAddBadLinks	0.446s
FAILED TO REMOVE
PASS: docker_cli_build_test.go:1662: DockerSuite.TestBuildAddBadLinksVolume	1.309s
FAILED TO REMOVE
PASS: docker_cli_build_test.go:2818: DockerSuite.TestBuildAddCurrentDirWithCache	1.885s
FAILED TO REMOVE
(Doesn't cause any problems, but could be misleading)

**Comment by calavera** [comment]
Nice catch! LGTM

**Comment by sallyom** [comment]
wow, that was really fast!  thanks

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @sallyom !

**Pull request merged**
