### PR TITLE
Added daemon.json Windows example

### LINKED ISSUE #22709: daemon.json documentation sample is not valid on Windows
The list of allowed configuration options in [this document](https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file) is not applicable to Windows. Several of the options do not work on Windows. I think this requires minor clarification, perhaps a sample that is applicable to Windows:

When used as is, the following is returned:

```none
PS C:\> dockerd
time="2016-05-12T15:40:59-07:00" level=fatal msg="unable to configure the Docker daemon with file C:\\ProgramData\\docker\\config\\daemon.json: the following directives don't match any configuration option: iptables, bip, icc, api-cors-headers, exec-root, default-gateway-v6, ipv6, cgroup-parent, ip-mask, ip, userland-proxy, default-gateway, ip-forward, selinux-enabled, userns-remap, fixed-cidr-v6\n"
```

Here is a working sample:

```json
{
    "authorization-plugins": [],
    "dns": [],
    "dns-opts": [],
    "dns-search": [],
    "exec-opts": [],
    "storage-driver": "",
    "storage-opts": [],
    "labels": [],
    "log-driver": "", 
    "mtu": 0,
    "pidfile": "",
    "graph": "",
    "cluster-store": "",
    "cluster-advertise": "",
    "debug": true,
    "hosts": ["tcp://0.0.0.0:2376", "npipe://"],
    "log-level": "",
    "tlsverify": true,
    "tlscacert": "C:\\ProgramData\\docker\\certs.d\\ca.pem",
    "tlscert": "C:\\ProgramData\\docker\\certs.d\\server-cert.pem",
    "tlskey": "C:\\ProgramData\\docker\\certs.d\\server-key.pem",
    "group": "",
    "default-ulimits": {},
    "bridge": "",
    "fixed-cidr": "",
    "raw-logs": false,
    "registry-mirrors": [],
    "insecure-registries": [],
    "disable-legacy-registry": false
}

```
If this makes sense, and is in line with the docs scope / purpose, I am happy write up and propose the changes.

neilp

### PR DESCRIPTION
**Pull request by neilpeterson**
**\- What I did**

Added a documentation example of the daemon.json file for Windows. This update "fixes #22709".

Signed-off-by: Neil Peterson neilpeterson@outlook.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by jhowardmsft** [comment]
LGTM

**Comment by jhowardmsft** [comment]
Retest this please

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
