### PR TITLE
[17.03.x] update frozen image script

### PR DESCRIPTION
**Pull request by thaJeztah**
cherry-picks the following changes to bring the script up-to-date;

a227ea62e6f4bc316e0ee14188fc54a3e517c3bc (https://github.com/moby/moby/pull/29027)
5870675ebc0db9fbe07736a59a6226b805ba00dc (https://github.com/moby/moby/pull/29864)
555bd548cacfbe02447ebb055d3efa5eeaabe972 (https://github.com/moby/moby/pull/33443)
d75eb735eee26521b76c732f8b07cfaf6c460d12 (https://github.com/moby/moby/pull/33707)

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @andrewhsu @tiborvass PTAL

**Comment by thaJeztah** [comment]
ping @andrewhsu @tiborvass PTAL

**Comment by andrewhsu** [comment]
LGTM

Stuff works:
```
./contrib/download-frozen-image-v2.sh ./docker-frozen-images buildpack-deps:jessie@sha256:85b379ec16065e4fe4127eb1c5fb1bcc03c559bd36dbb2e22ff496de55925fa6 busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f debian:jessie@sha256:72f784399fd2719b4cb4e16ef8e369a39dc67f53d978cd3e2e7bf4e502c7b793 hello-world:latest@sha256:c5515758d4c5e1e838e9cd307f6c6a0d620b5e07e6f927b07d05f6d12a1ac8d7
Downloading 'library/buildpack-deps:jessie@sha256:85b379ec16065e4fe4127eb1c5fb1bcc03c559bd36dbb2e22ff496de55925fa6' (4 layers)... 
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0% 
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%

Downloading 'library/busybox:latest@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f' (1 layers)...
######################################################################## 100.0%
######################################################################## 100.0%

Downloading 'library/debian:jessie@sha256:72f784399fd2719b4cb4e16ef8e369a39dc67f53d978cd3e2e7bf4e502c7b793' (1 layers)...
skipping existing b6e0d04482ff

Downloading 'library/hello-world:latest@sha256:c5515758d4c5e1e838e9cd307f6c6a0d620b5e07e6f927b07d05f6d12a1ac8d7' (1 layers)...
######################################################################## 100.0%
######################################################################## 100.0%

Download of images into './docker-frozen-images' complete.
Use something like the following to load the result into a Docker daemon:
  tar -cC './docker-frozen-images' . | docker load
```

**Comment by aaronlehmann** [comment]
LGTM

**Comment by vieux** [comment]
ok @thaJeztah @tiborvass you can merge when you're ready

**Pull request merged**
