### PR TITLE
fix invalid typo in error message

### PR DESCRIPTION
**Pull request by justincormack**
Just a little typo I noticed while testing

Signed-off-by: Justin Cormack justin.cormack@docker.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by icecrime** [comment]
Looks valud to me.

**Comment by thaJeztah** [comment]
GLMT!

**Comment by vdemeester** [comment]
Hum lot's of *typo fixing* on "invalid" (invalud, invald…), this is a difficult word :joy:

**Pull request merged**
