### PR TITLE
restrict filters server side in docker images

### PR DESCRIPTION
**Pull request by vieux**
Unlike `docker ps`, `docker images` filters are restricted.

Filters are a great way to extend the filtering of the cli.
This change would be extremely useful in Swarm.

### CODE REVIEW

**Comment by vieux** [comment]
See https://github.com/docker/swarm/pull/249 for an example

**Comment by SvenDowideit** [comment]
you just changed some restrictions to constraints on the cli - where is the documentation telling users of this? :)

**Comment by thaJeztah** [comment]
I understand the use case, but want to point to a reason that accepting *any* filter could be troublesome https://github.com/docker/docker/issues/8777.

For that reason; perhaps this should be given another thought [#928  Implement a 'clean' command](https://github.com/docker/docker/issues/928) so that uses can have a "safer" way to cleanup images and don't need to use the filters for that?

**Comment by thaJeztah** [comment]
Reading https://github.com/docker/swarm/pull/249; wouldn't that be something to use "meta-data" for? https://github.com/docker/docker/pull/9882, i.e. `docker images -f label=node=fedora-1`?

**Comment by vieux** [comment]
@SvenDowideit @thaJeztha I'll add the check back server side, so there will be no change for the user

**Comment by vieux** [comment]
Filters are already sent to the daemon, so it doesn't require any doc change

**Comment by thaJeztah** [comment]
> I'll add the check back server side, so there will be no change for the user

:+1:  thanks

**Comment by vieux** [comment]
@thaJeztah @SvenDowideit updated, I added back the test

@crosbymichael @jfrazelle can you please take a look ?

**Comment by jfrazelle** [comment]
LGTM

**Comment by thaJeztah** [comment]
I like this; having this check server-side makes more sense, so a nice improvement overall as well.

**Comment by jfrazelle** [comment]
@thaJeztah I agree :D

**Comment by crosbymichael** [comment]
@vieux why is this more useful as a server side check?  Are all filters done on the client or server?

**Comment by vieux** [comment]
@crosbymichael filters are done server side for `image`

**Comment by icecrime** [comment]
LGTM: server-side should be the source of truth for what's allowed.

**Pull request merged**
