### PR TITLE
c8d/prune: Default `dangling` to true, familiarize untagged images

### PR DESCRIPTION
**Pull request by vvoland**
- addresses https://github.com/moby/moby/issues/46760

**c8d/prune: Default dangling filter to true**

If no `dangling` filter is specified, prune should only delete dangling
images.

This wasn't visible by doing `docker image prune` because the CLI
explicitly sets this filter to true.

**c8d/prune: Familiarize image names that were untagged**

To align with the graphdriver implementation.

Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>

**- How to verify it**
docker-py  `tests.integration.api_image_test.PruneImagesTest` should pass now

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
> This wasn't visible by doing docker image prune because the CLI explicitly sets this filter to true.

Did this also fail with the graph-driver?  (from the above, it sounds like it's an existing bug, is that correct?)

**Comment by thaJeztah** [comment]
Ah, never mind I see the graph-driver implementation has the default set correctly already; https://github.com/moby/moby/blob/659e7b52df07d3854b23af3de7d59b09b94fe4b6/daemon/images/image_prune.go#L50

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@vvoland for a follow-up, should we remove that default from the CLI? (tempted to say that defaults should be _either_ on the CLI _or_ on the daemon, not "both"

**Comment by thaJeztah** [comment]
Guessing that this is the offending line https://github.com/docker/cli/blob/623d9b1f68171e3ff9899b21392ac4f102ba533b/cli/command/image/prune.go#L63

```go
	pruneFilters.Add("dangling", strconv.FormatBool(!options.all))
```

Which means we unconditionally set the `dangling` filter, but depending on `--all`, we set it to either `true` or `false`

**Comment by vvoland** [comment]
I think that the current CLI behavior is correct - if the `image prune` (without `--all`) is expected to only prune the dangling images, it should explicitly pass `dangling=true` instead of assuming that server will also default to true.

**Pull request merged**
