### PR TITLE
[20.10 backport] Upgrade containerd/fifo to v1.1.0

### PR DESCRIPTION
**Pull request by corhere**
- v20.10 backport of #45049 
- Fixes https://github.com/docker/for-linux/issues/1186
- Fixes https://github.com/moby/moby/issues/45002

**- What I did**
- Upgraded containerd/fifo to a tagged version containing https://github.com/containerd/fifo/pull/47

**- How I did it**

**- How to verify it**

**- Description for the changelog**

- Fixed an issue with the daemon crashing on startup during container restore

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by neersighted — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by corhere** [comment]
```
[2023-03-27T21:26:32.205Z] === RUN   TestHealthCheckProcessKilled
[2023-03-27T21:26:42.195Z]     health_test.go:112: timeout hit after 10s: waiting for container healthcheck logs
[2023-03-27T21:27:38.482Z] --- FAIL: TestHealthCheckProcessKilled (60.89s)
```

It's probably just a flake, but since container logs are very FIFO-adjacent I've kicked off another CI run to make sure it isn't actually a regression.

**Comment by corhere** [comment]
Integration tests passed the second time.

<details><summary>Though <tt>hack/generate-swagger-api.sh</tt> is non-deterministic?
</summary>

```
[2023-03-27T22:31:39.560Z] The result of hack/generate-swagger-api.sh differs
[2023-03-27T22:31:39.560Z] 
[2023-03-27T22:31:39.560Z] diff --git a/api/types/container/container_wait.go b/api/types/container/container_wait.go
[2023-03-27T22:31:39.560Z] index 49e05ae669..c2e69b5b25 100644
[2023-03-27T22:31:39.560Z] --- a/api/types/container/container_wait.go
[2023-03-27T22:31:39.560Z] +++ b/api/types/container/container_wait.go
[2023-03-27T22:31:39.560Z] @@ -6,14 +6,6 @@ package container // import "github.com/docker/docker/api/types/container"
[2023-03-27T22:31:39.560Z]  // See hack/generate-swagger-api.sh
[2023-03-27T22:31:39.560Z]  // ----------------------------------------------------------------------------
[2023-03-27T22:31:39.560Z]  
[2023-03-27T22:31:39.560Z] -// ContainerWaitOKBodyError container waiting error, if any
[2023-03-27T22:31:39.560Z] -// swagger:model ContainerWaitOKBodyError
[2023-03-27T22:31:39.560Z] -type ContainerWaitOKBodyError struct {
[2023-03-27T22:31:39.560Z] -
[2023-03-27T22:31:39.560Z] -	// Details of an error
[2023-03-27T22:31:39.560Z] -	Message string `json:"Message,omitempty"`
[2023-03-27T22:31:39.560Z] -}
[2023-03-27T22:31:39.560Z] -
[2023-03-27T22:31:39.560Z]  // ContainerWaitOKBody OK response to ContainerWait operation
[2023-03-27T22:31:39.560Z]  // swagger:model ContainerWaitOKBody
[2023-03-27T22:31:39.560Z]  type ContainerWaitOKBody struct {
[2023-03-27T22:31:39.560Z] @@ -26,3 +18,11 @@ type ContainerWaitOKBody struct {
[2023-03-27T22:31:39.560Z]  	// Required: true
[2023-03-27T22:31:39.560Z]  	StatusCode int64 `json:"StatusCode"`
[2023-03-27T22:31:39.560Z]  }
[2023-03-27T22:31:39.560Z] +
[2023-03-27T22:31:39.560Z] +// ContainerWaitOKBodyError container waiting error, if any
[2023-03-27T22:31:39.560Z] +// swagger:model ContainerWaitOKBodyError
[2023-03-27T22:31:39.560Z] +type ContainerWaitOKBodyError struct {
[2023-03-27T22:31:39.560Z] +
[2023-03-27T22:31:39.560Z] +	// Details of an error
[2023-03-27T22:31:39.560Z] +	Message string `json:"Message,omitempty"`
[2023-03-27T22:31:39.560Z] +}
[2023-03-27T22:31:39.560Z] 
[2023-03-27T22:31:39.560Z] Please update api/swagger.yaml with any API changes, then 
[2023-03-27T22:31:39.560Z] run hack/generate-swagger-api.sh.
```

</details>

**Comment by thaJeztah** [comment]
> 

Yup; it uses a map internally, which makes it sort results randomly. We worked around this on master and 23.0, but not in 20.10

See

- https://github.com/moby/moby/issues/42593

**Pull request merged**
