### PR TITLE
Add output of integer argument

### PR DESCRIPTION
**Pull request by icaoweiwei**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Cao Weiwei cao.weiwei30@zte.com.cn

### CODE REVIEW

**Comment by icaoweiwei** [comment]
Add output of integer argument

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by thaJeztah** [comment]
ping @vieux PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
thanks!

**Pull request merged**
