### PR TITLE
Update docker_cli_run_unix_test.go

### PR DESCRIPTION
**Pull request by jirawat050**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Rather these test should use different names (for parallelization)

**Comment by jirawat001** [comment]
cannot call outside variable in function?for reduce line.

**Review by vdemeester — CHANGES_REQUESTED** [review]
@jirawat001 agreeing with @AkihiroSuda, those `name` should be different for each of those tests.

Also, you need to sign-off your commit 👼 🙏

**Comment by thaJeztah** [comment]
Instead of using a name, just using the container's ID would work;

```go
out, _ := dockerCmd(c, "run", "-dit", "busybox", "top")  
cid := strings.TrimSpace(out)
```

**Comment by coolljt0725** [comment]
@jirawat001  Hi, please sign your commits   https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by coolljt0725** [comment]
@jirawat001 and please follow the suggestion of @thaJeztah . Use a global variable to reduce line is not a good idea.

**Comment by AkihiroSuda** [comment]
ping @jirawat001

**Comment by thaJeztah** [comment]
Closing this PR for now; it's missing a sign-off, and the current changes are not improving things much; @jirawat001 let us know if you want to work on this again, then I can reopen before you push changes

**Pull request closed without merging**
