### PR TITLE
api/types: migrate NetworkResource to api/types/network

### PR DESCRIPTION
**Pull request by thaJeztah**
**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Could use some input on this one;

- I'm not sure if `network.Info` is a good name for this; that said, `network.Resource` also isn't great
- I was considering `network.Inspect` or it could be `network.Network` - last one would be similar to `volume.Volume` (e.g.)
- This type `NetworkResource` / `network.Info` is used _BOTH_ for `docker network inspect` _AND_ (e.g.) `docker network ls`; that's the same as we have for `volume`, but I'm now wondering; SHOULD they share the same type? For _list_ operations we may want to return a struct that does not have all details, wheras on `inspect`, we likely want to show all details.
- :point_up: one option we'd have is to create separate types, but (for now) make them an alias for each other; once we need to diverge, we can remove the alias and make them concrete types (or perhaps already make them concrete types, but identical).

**Comment by thaJeztah** [comment]
Updated; 

- using `network.Inspect` for inspecting network
- `network.Summary` for listing networks; currently an alias


Unfortunately there's many backend operations that _list_ networks, but return the same type; this needs further detailing / cleaning up, as some parts are confusing (e.g. we collect all the network's data regardless, then either discard them, or use the same type to add optional details). The `Verbose` vs `Detailed` booleans are ... also really confusing (some are set depending on API version, but also gated by the other one.

**Review by robmry — APPROVED** [review]
LGTM

**Review by laurazard — APPROVED** [review]
I think the PR as a whole is fine for an intermediate step, and `Network.Summary` makes sense for listing operations and to lay the groundwork for having these types be separate.

The only thing I'm not 100% sold on is `Network.Inspect` vs `NetworkResource` or something similar, but also not really against it.

**Review by akerouanton — APPROVED** [review]

**Pull request merged**
