### PR TITLE
adding entry for Hugh Beaver

### PR DESCRIPTION
**Pull request by klinden**
British engineer, found of Guinness Book of World Records

### CODE REVIEW

**Comment by thaJeztah** [comment]
could you also add a woman to the list? See https://github.com/klinden/docker/blob/3236ce210f8ab3a8d33b2d210a89d4bc491ead19/pkg/namesgenerator/names-generator.go#L81

**Comment by thaJeztah** [comment]
Thanks! Almost there; can you squash your commits?

**Comment by klinden** [comment]
@thaJeztah Sure thing :)

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by justincormack** [comment]
LGTM

**Comment by thaJeztah** [comment]
win2lin failure is unrelated; merging

**Pull request merged**
