### PR TITLE
Sleep before restarting event processing

### PR DESCRIPTION
**Pull request by cpuguy83**
This prevents restarting event processing in a tight loop.
You can see this with the following steps:

```terminal
$ containerd &
$ dockerd --containerd=/run/containerd/containerd.sock &
$ pkill -9 containerd
```

At this point you will be spammed with logs such as:

```
ERRO[2019-07-12T22:29:37.318761400Z] failed to get event                           error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused\"" module=libcontainerd namespace=plugins.moby
```

Without this change you can quickly end up with gigabytes of log data.

### Description for the changelog

Sleep before attempting to restart event processing

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
SGTM

**Comment by thaJeztah** [comment]
ping @tonistiigi @crosbymichael PTAL

**Comment by kolyshkin** [comment]
@cpuguy83 Looks like this is not about logging rate limiting per se, but about rate limiting of trying to (re)subscribe to events? What is the downside of waiting a second before trying to re-subscribe?

Side note: I don't quite understand the logic of calling `go c.processEventStream(ctx, ns)` from itself. I traced it back to commit ddae20c0320 but unfortunately it's not clear why it was done that way. Is this a way to resume processing after an error? Seems like an overkill to me to spawn a whole new goroutine. Can't we just use something like `goto begin` (or another `for` loop) for that?

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
Opps, sorry I didn't see your comment until I refreshed the page @kolyshkin .

**Comment by cpuguy83** [comment]
> Looks like this is not about logging rate limiting per se, but about rate limiting of trying to (re)subscribe to events?

Yes

> What is the downside of waiting a second before trying to re-subscribe?

If there is a downside then we have racey behavior anyway.
So, worst case we miss some events, and the sleep means we could miss more events.

In this error case, it is most likely that containerd has been stopped.
Maybe we could check for the broken connection and only sleep in that case? May not be worth it, I'm not sure what other errors we would expect here.

> Can't we just use something like goto begin (or another for loop) for that?

Yes this could be refactored for sure.

**Pull request merged**
