### PR TITLE
Builder unit tests refactoring

### PR DESCRIPTION
**Pull request by tkopczynski**
**\- What I did**

I created couple unit test helpers and applied them to builder unit tests.

**\- How I did it**

By extracting common functionalities to helper functions.

**\- How to verify it**

Check builder/utils_test.go. Remaining changes are done by applying functions from this file to builder unit tests.

**\- A picture of a cute animal (not mandatory but encouraged)**
here you are:
image

Signed-off-by: Tomasz Kopczynski tomek@kopczynski.net.pl

### CODE REVIEW

**Comment by LK4D4** [comment]
@tkopczynski there is trivial vet error in CI

**Comment by tkopczynski** [comment]
@LK4D4 Yes, somehow it slipped through... It should be ok now

**Comment by LK4D4** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐰

**Pull request merged**
