### PR TITLE
Remove execution driver

### PR DESCRIPTION
**Pull request by hqhq**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

We use containerd and there is no execution driver anymore.

Addresses: https://github.com/docker/docker/issues/24461

Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by hqhq** [comment]
Engine-api change is in https://github.com/docker/engine-api/pull/309

**Comment by mlaventure** [comment]
LGTM (IANAM).

This was an omission from #20662

Funny it took so long to find.

/cc @tonistiigi

**Comment by vdemeester** [comment]
LGTM 🐸. Should be put this into `1.12.0` milestone ? (given the amount of changes I would say yes but it's not big deal)

**Comment by thaJeztah** [comment]
I think adding it would be ok; quick check with @tiborvass if he's okay with it too

**Comment by tonistiigi** [comment]
LGTM

**Comment by tiborvass** [comment]
Needs an update to api 1.24 since it gets cherrypicked.

**Comment by thaJeztah** [comment]
created a PR to fix the docs; https://github.com/docker/docker/issues/24560

**Pull request merged**
