### PR TITLE
plugins: Rename plugins_linux.go to plugins_unix.go and use build tags

### LINKED ISSUE #32192: Build is broken for authorization package
**Description**

Build is broken for Docker Auth package

**Steps to reproduce the issue:**
```
$ go get github.com/docker/docker/pkg/authorization
# github.com/docker/docker/pkg/authorization
github.com/docker/docker/pkg/authorization/plugin.go:108: cannot assign *plugins.Plugin to plugin (type plugingetter.CompatPlugin) in multiple assignment:
	*plugins.Plugin does not implement plugingetter.CompatPlugin (missing BasePath method)
```

### PR DESCRIPTION
**Pull request by aaronlehmann**
This allows pkg/authorization to build on OS X.

Fixes #32192

cc @anusha-ragunathan

### CODE REVIEW

**Comment by tiborvass** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by anusha-ragunathan** [comment]
Is there something we can do to catch such cross platform build broken-ness earlier? Especially for `docker/docker/pkg` packages? Maybe perform a `go get` of the list of `docker/docker/pkg/` packages as part of `make cross` to ensure that packages builds.

**Comment by anusha-ragunathan** [comment]
This change LGTM.

**Comment by anusha-ragunathan** [comment]
@vdemeester @tiborvass : Something like this should work. https://github.com/docker/docker/commit/c4d798e76eebfdaf587fc005725c3a9af248630c. It needs some TLC, since this will reveal build errors across the board and those need to be methodically fixed.

**Comment by tiborvass** [comment]
@anusha-ragunathan should be `go install`

**Comment by aaronlehmann** [comment]
I'm happy to add the `go install` command to `hack/make/cross` in this PR if people want.

**Comment by anusha-ragunathan** [comment]
@aaronlehmann : If you add it, it'll reveal a ton of build errors we need to fix alongside. Its probably better to do it in another PR.

**Comment by aaronlehmann** [comment]
The only errors I found were:

```
pkg/term/tc_other.go:12: undefined: Termios
pkg/term/tc_other.go:17: undefined: Termios
pkg/term/term.go:23: undefined: Termios
```

when trying to traget Solaris.

**Comment by aaronlehmann** [comment]
I think the build tags in `tc_other.go` just need to be fixed.

```
// +build !windows
// +build !linux !cgo
// +build !solaris !cgo
```

That's `!solaris OR !cgo`, which doesn't make sense. It should be `!solaris,!cgo` instead.

**Comment by aaronlehmann** [comment]
However, that package isn't cross-compilable when targeting Solaris anyway because the Solaris implementation needs cgo. So if we put the `go install ...` line in the `if [ "$GOOS" != "solaris" ]; then` section, we should be good.

**Comment by aaronlehmann** [comment]
I've added the check.

**Comment by anusha-ragunathan** [comment]
When I `export DOCKER_CROSSPLATFORMS="linux/386 linux/arm darwin/amd64"`, I got these errors during `make cross` 

github.com/docker/docker/pkg/devicemapper
pkg/devicemapper/devmapper.go:85: undefined: cdmTask
# github.com/docker/docker/pkg/loopback
pkg/loopback/attach_loopback.go:21: undefined: LoNameSize
pkg/loopback/attach_loopback.go:21: invalid array bound LoNameSize
pkg/loopback/attach_loopback.go:22: undefined: LoNameSize
pkg/loopback/attach_loopback.go:22: invalid array bound LoNameSize
pkg/loopback/ioctl.go:25: undefined: loopInfo64
pkg/loopback/ioctl.go:39: undefined: loopInfo64
Makefile:114: recipe for target 'cross' failed
make: *** [cross] Error 1
aragunathan@aragunathan-XPS-13-9343:~/code/src/github.com/docker/docker$ echo $DOCKER_CROSSPLATFORMS
linux/386 linux/arm darwin/amd64

**Comment by aaronlehmann** [comment]
These are both packages that depend on cgo but do not declare the dependency in their build tags. I've updated the PR to fix this.

**Comment by anusha-ragunathan** [comment]
LGTM (albeit after the merge)

**Comment by artsf** [comment]
Can we please port the fix to 1.13.* ? :)

**Pull request merged**
