### PR TITLE
update libnetwork to fix ARM tests

### LINKED ISSUE #28284: Panic on arm running swarm tests
Arm CI builds are failing https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/3771/console

Daemon logs for

```
04:21:59 ----------------------------------------------------------------------
04:21:59 FAIL: docker_api_service_update_test.go:20: DockerSwarmSuite.TestAPIServiceUpdatePort
04:21:59 
04:21:59 [d7e6d70e8a60c] waiting for daemon to start
04:21:59 [d7e6d70e8a60c] daemon started
04:21:59 docker_api_service_update_test.go:26:
04:21:59     waitAndAssert(c, defaultReconciliationTimeout, d.checkActiveContainerCount, checker.Equals, 1)
04:21:59 daemon.go:551:
04:21:59     c.Assert(err, checker.IsNil)
04:21:59 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0x12d751d0), Stderr:[]uint8(nil)} ("exit status 1")
04:21:59 
04:22:07 
```
https://gist.github.com/tonistiigi/c566c87c3f8b2a9511486ebe6a83784a

```
time="2016-11-11T04:21:57.982077103Z" level=debug msg="Root CA updated successfully" cluster.id=wap60eb167wyot2e7kkoa9k2a method="(*Server).updateCluster" module=ca 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x363cac]

goroutine 121 [running]:
panic(0x121adf8, 0x11e28008)
	/usr/local/go/src/runtime/panic.go:500 +0x33c
sync/atomic.addUint64(0x1259d45c, 0x1, 0x0, 0x1, 0x0)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x68
github.com/docker/docker/vendor/github.com/hashicorp/serf/serf.(*LamportClock).Increment(0x1259d45c, 0x45ab18, 0x121bcce0)
	/go/src/github.com/docker/docker/vendor/github.com/hashicorp/serf/serf/lamport.go:24 +0x40
github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).JoinNetwork(0x1259d420, 0x12313e00, 0x19, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/networkdb.go:413 +0x4c
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).joinCluster(0x123eea90, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:372 +0x90
github.com/docker/docker/vendor/github.com/docker/libnetwork.glob..func1(0x1af7508, 0x123eea90, 0x123eea90)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:725 +0x50
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).NewNetwork(0x1207fc80, 0x1291d440, 0x7, 0x1291d3b9, 0x7, 0x12313e00, 0x19, 0x1232e7e0, 0x7, 0x8, ...)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:715 +0x984
github.com/docker/docker/daemon.(*Daemon).createNetwork(0x12074780, 0x1, 0x1291d440, 0x7, 0x0, 0x12331980, 0x0, 0x12331920, 0x0, 0x1291d3b9, ...)
	/go/src/github.com/docker/docker/daemon/network.go:295 +0xc6c
github.com/docker/docker/daemon.(*Daemon).SetupIngress.func1(0x12074780, 0x12313e00, 0x19, 0x1, 0x1291d440, 0x7, 0x0, 0x12331980, 0x0, 0x12331920, ...)
	/go/src/github.com/docker/docker/daemon/network.go:149 +0x150
created by github.com/docker/docker/daemon.(*Daemon).SetupIngress
	/go/src/github.com/docker/docker/daemon/network.go:187 +0xa0

goroutine 1 [chan receive]:
```

Hard to say what is the first commit with this problem because we have limited history but I can bisect it out if needed.

@mrjana @mavenugo

### PR DESCRIPTION
**Pull request by vieux**
fixes https://github.com/docker/docker/issues/28284

got the inspiration from this issue: https://github.com/hashicorp/serf/issues/20 and this fix: https://github.com/hashicorp/serf/commit/7069fbc35d1e5b9e2276ba82ef1e5eebeb2a7b2a

### CODE REVIEW

**Comment by vieux** [comment]
depends on https://github.com/docker/libnetwork/pull/1549

**Comment by mavenugo** [comment]
@vieux thanks for the fix. docker/libnetwork#1549 is merged now. pls go ahead with vendoring.

**Comment by vieux** [comment]
@icecrime `poule` is great <3

**Comment by tonistiigi** [comment]
LGTM

**Comment by mavenugo** [comment]
LGTM

**Comment by thaJeztah** [comment]
Couple of failures 😞 (test is still running);

```
11:21:33 ----------------------------------------------------------------------
11:21:33 FAIL: docker_cli_logs_test.go:230: DockerSuite.TestLogsFollowSlowStdoutConsumer
11:21:33 
11:21:33 docker_cli_logs_test.go:259:
11:21:33     c.Assert(actual, checker.Equals, expected)
11:21:33 ... obtained int = 136052
11:21:33 ... expected int = 200000
11:21:33 
11:21:38 
11:21:38 ----------------------------------------------------------------------
```


```
11:24:42 ----------------------------------------------------------------------
11:24:42 FAIL: docker_cli_plugins_test.go:62: DockerSuite.TestPluginActive
11:24:42 
11:24:42 docker_cli_plugins_test.go:68:
11:24:42     c.Assert(err, checker.IsNil)
11:24:42 ... value *errors.errorString = &errors.errorString{s:"\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker volume create -d tiborvass/no-remove:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: create 0495a17bc5a32516e95e0485c789bd68a2177cc72266ef4ab92be8c72e75be41: Post http://%2Frun%2Fdocker%2F6a8e5d0b219b9d14f8309f5272353e1bcc11db404b763219559744b84c22a84e%2Fplugin.sock/VolumeDriver.Create: dial unix /run/docker/6a8e5d0b219b9d14f8309f5272353e1bcc11db404b763219559744b84c22a84e/plugin.sock: connect: no such file or directory\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n"} ("\nCommand: /go/src/github.com/docker/docker/bundles/1.13.0-dev/binary-client/docker volume create -d tiborvass/no-remove:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: create 0495a17bc5a32516e95e0485c789bd68a2177cc72266ef4ab92be8c72e75be41: Post http://%2Frun%2Fdocker%2F6a8e5d0b219b9d14f8309f5272353e1bcc11db404b763219559744b84c22a84e%2Fplugin.sock/VolumeDriver.Create: dial unix /run/docker/6a8e5d0b219b9d14f8309f5272353e1bcc11db404b763219559744b84c22a84e/plugin.sock: connect: no such file or directory\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n")
11:24:42 
```

```
12:38:14 ----------------------------------------------------------------------
12:38:14 FAIL: docker_cli_daemon_plugins_test.go:83: DockerDaemonSuite.TestDaemonKillLiveRestoreWithPlugins
12:38:14 
12:38:14 [d1398589fe039] waiting for daemon to start
12:38:14 [d1398589fe039] daemon started
12:38:14 docker_cli_daemon_plugins_test.go:110:
12:38:14     c.Fatalf("Expected exit code '0', got %d err: %v output: %s ", ec, err, out)
12:38:14 ... Error: Expected exit code '0', got 1 err: exit status 1 output:  
12:38:14 
12:38:14 [d1398589fe039] waiting for daemon to start
12:38:14 [d1398589fe039] daemon started
12:38:14 [d1398589fe039] exiting daemon
12:38:23 time="2016-11-11T12:38:23Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.5.7-docker-4/modules.dep.bin'`, error: exit status 1" 
12:38:23 time="2016-11-11T12:38:23Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.5.7-docker-4/modules.dep.bin'`, error: exit status 1" 
12:38:28 
```

```
12:45:42 ----------------------------------------------------------------------
12:45:42 FAIL: docker_cli_daemon_plugins_test.go:116: DockerDaemonSuite.TestDaemonShutdownLiveRestoreWithPlugins
12:45:42 
12:45:42 [d09303a521ccd] waiting for daemon to start
12:45:42 [d09303a521ccd] daemon started
12:45:42 docker_cli_daemon_plugins_test.go:143:
12:45:42     c.Fatalf("Expected exit code '0', got %d err: %v output: %s ", ec, err, out)
12:45:42 ... Error: Expected exit code '0', got 1 err: exit status 1 output:  
12:45:42 
12:45:42 [d09303a521ccd] waiting for daemon to start
12:45:42 [d09303a521ccd] daemon started
12:45:42 [d09303a521ccd] exiting daemon
```

**Comment by thaJeztah** [comment]
And last one;

```
12:51:44 ----------------------------------------------------------------------
12:51:44 FAIL: docker_cli_daemon_plugins_test.go:187: DockerDaemonSuite.TestVolumePlugin
12:51:44 
12:51:44 [d34dab176df4a] waiting for daemon to start
12:51:44 [d34dab176df4a] daemon started
12:51:44 docker_cli_daemon_plugins_test.go:213:
12:51:44     c.Fatalf("Could not create volume: %v %s", err, out)
12:51:44 ... Error: Could not create volume: exit status 1 Error response from daemon: create plugin-volume: Post http://%2Frun%2Fdocker%2F2587d1f949eae7021b9e314846c67e5ec84353b6fa914a6a8d149a6f3ed57d52%2Fplugin.sock/VolumeDriver.Create: dial unix /run/docker/2587d1f949eae7021b9e314846c67e5ec84353b6fa914a6a8d149a6f3ed57d52/plugin.sock: connect: no such file or directory
12:51:44 
12:51:44 
12:51:44 docker_cli_daemon_plugins_test.go:213:
12:51:44     c.Fatalf("Could not create volume: %v %s", err, out)
12:51:44 docker_cli_daemon_plugins_test.go:207:
12:51:44     c.Fatalf("Could not remove plugin: %v %s", err, out)
12:51:44 ... Error: Could not remove plugin: exit status 1 Error response from daemon: plugin tiborvass/no-remove:latest is in use
12:51:44 
```

**Comment by mavenugo** [comment]
@thaJeztah @vieux I see an open issue : https://github.com/docker/docker/issues/28305. Just adding the link here just to tag these related issues together.

**Comment by tonistiigi** [comment]
Will merge this as fixes swarm tests. Plugin tests can be fixed with a separate pr.

**Pull request merged**
