### PR TITLE
Add build constraint for windows

### PR DESCRIPTION
**Pull request by jessfraz**
Docker-DCO-1.1-Signed-off-by: Jessica Frazelle jess@docker.com (github: jfrazelle)

### CODE REVIEW

**Comment by jfrazelle** [comment]
yayyyy its fixed: https://jenkins.dockerproject.com/job/Windows%20PRs/label=windows/1/console

**Comment by jfrazelle** [comment]
ping @icecrime

**Comment by icecrime** [comment]
:+1:

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
