### PR TITLE
Cherry-picks and Changelog 1.12.2-rc2

### PR DESCRIPTION
**Pull request by vieux**
- [#27049](https://github.com/docker/docker/pull/27049)
  - 6c3b44f755cbf2564171a012fc55942862f3ede9 Use ListOpt for build labels
- [#27094](https://github.com/docker/docker/pull/27094)
  - 278273bc1699873304240a6eca342b54051e2f23 add lock in libcontainerd client AddProcess
- [#26960](https://github.com/docker/docker/pull/26960)
  - ea07ef7a7c3a221d6167cc2e36806ed9615ac973 make remove cloudprovider network return 204
- [#27085](https://github.com/docker/docker/pull/27085)
  - 4c74469d30a71c53cc6b309a3c0048191b1ac008 add check flag for CONFIG_NETFILTER_XT_MATCH_IPVS CONFIG_IP_VS_NFCT CONFIG_IP_VS_RR in contrib/check-config.sh
- [#27126](https://github.com/docker/docker/pull/27126)
  - 61335bcb03ac60385bc19b6e1346b34cd168f7de Remove amd64 assumption in release.sh, cross and tgz scripts

### CODE REVIEW

**Comment by thaJeztah** [comment]
moved back to "code review" so that we don't accidentally merge before all cherries are picked

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
@vieux looks like we may have to cherry pick one small fix in API response codes (if I interpreted correctly); see https://github.com/docker/docker/pull/27041#issuecomment-250888853

**Comment by mlaventure** [comment]
Could we also cherry-pick #27094 ?

**Comment by vieux** [comment]
@mlaventure done

**Comment by vieux** [comment]
@thaJeztah done

**Comment by thaJeztah** [comment]
This one can be cherry picked https://github.com/docker/docker/pull/27085

**Comment by vieux** [comment]
@thaJeztah added

**Comment by vieux** [comment]
failure unrelated: hub is down

**Comment by mrjana** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
