### PR TITLE
[17.05.x] Cherry-pick: Fix a rare segfault that can occur in service logs

### PR DESCRIPTION
**Pull request by dperny**
Revendors swarmkit with a change that fixes a rare segfault that can occur when following logs on a brand new service with bad bind mount options.

Fixes docker/swarmkit#2147

### CODE REVIEW

**Comment by dperny** [comment]
Not sure why vendor is failing, the logs don't seem to indicate that it's anything I did, but I may be misinterpreting them.

**Comment by dperny** [comment]
@thaJeztah PTAL

**Comment by thaJeztah** [comment]
ping @vieux :)

**Comment by dperny** [comment]
`vndr` is giving me trouble. i think i have upgraded to a newer version that swarmkit uses, but moby does not. i may be mistaken though.

**Comment by dperny** [comment]
Rerolling to hopefully match the CI's behavior on `vndr`. The tool has been updated but not in CI and on Moby.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
