### PR TITLE
Add integration test for history option

### LINKED ISSUE #12578: create integration cli test for -H|--human in docker history
see PR https://github.com/docker/docker/pull/12430

### PR DESCRIPTION
**Pull request by ankushagarwal**
Parse the history output to locate the size fields and check
whether they are integers or not. Use Column name SIZE
to mark start and end indices of the size fields

Signed-off-by: Ankush Agarwal ankushagarwal11@gmail.com

closes #12578

### CODE REVIEW

**Comment by jfrazelle** [comment]
can you update with with the changes from the gocheck addition see https://github.com/docker/docker/pull/12511

sorry about that

**Comment by ankushagarwal** [comment]
Updated. How can I run these individual tests? Are they documented somewhere

These instructions do not work anymore : http://docs.master.dockerproject.com/project/test-and-docs/#running-individual-or-multiple-named-tests (`$ TESTFLAGS='-test.run ^TestHistoryHumanOptionFalse$' make test`)

**Comment by ankushagarwal** [comment]
Nevermind, this worked

```
TESTFLAGS='-check.f DockerSuite.TestHistoryHumanOptionFalse' make test-integration-cli
```

**Comment by jfrazelle** [comment]
ya i have a pr to fix the instructions it just got merged sorry

**Comment by jfrazelle** [comment]
I believe this closes a specific issue too

**Comment by jfrazelle** [comment]
I added "closes #12578" to your original comment so it closes the issue as well

**Comment by jfrazelle** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
