### PR TITLE
Pass KEEPBUNDLE in Docker build environment.

### PR DESCRIPTION
**Pull request by boucher**
This is an alternate solution to the problem described in #19969.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM   thanks!

**Comment by vdemeester** [comment]
LGTM 🐶

**Comment by duglin** [comment]
ping @tianon

**Comment by jfrazelle** [comment]
oh nice LGTM

**Comment by jfrazelle** [comment]
@boucher can we close the other one now

**Comment by jfrazelle** [comment]
nevermind it looks like it was closed

**Pull request merged**
