### PR TITLE
Remove 'docker-' prefix for containerd and runc binaries

### PR DESCRIPTION
**Pull request by tiborvass**
This allows to run the daemon in environments that have upstream containerd installed.

Signed-off-by: Tibor Vass <tibor@docker.com>

### CODE REVIEW

**Review by seemethere — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :angel:

**Review by yongtang — APPROVED** [review]
LGTM

**Review by seemethere — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
I'm wondering this might cause packaging issues.
e.g. apt/dnf-installing both `docker-ce` and `runc` is no longer possible?

**Comment by thaJeztah** [comment]
ping @seemethere ^^

**Comment by seemethere** [comment]
`docker-ce` doesn't install runc anymore our containerd package does. But yeah our containerd package would essentially overwrite the runc binary installed with the runc distro provided package. Original intention was to have a docker distributed runc package as well but that probably won't happen until late Q4 for us.

**Comment by cyphar** [comment]
This is a very bad idea -- Docker has always been stuck on an older version of `runc` and now we have to do workarounds in order to be able to split the two in the distribution (because, for instance, cri-o uses a newer version).

Speaking on the openSUSE side of things, we will carry a revert of this patch.

**Pull request merged**
