### PR TITLE
hack: Have TIMEOUT take -test.count into account when testing for flakiness

### PR DESCRIPTION
**Pull request by tiborvass**
Follow up to https://github.com/moby/moby/pull/38523/files#r254905817

Ping @olljanat @thaJeztah @tianon @vdemeester

### CODE REVIEW

**Comment by tiborvass** [comment]
This fixes a failure when TESTARRAY in hack/make/test-integration-flaky includes `TestBuildWithHugeFile` which takes between 100s and 150s each run. Which means that with `-test.count=5` it goes beyond the 5m timeout set with `-test.timeout=5m`.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks for the added comment

**Comment by olljanat** [comment]
@tiborvass this is why I like open source so much. I can introduce idea and then someone else will improve it. Awesome and thanks :grinning:

**Comment by tiborvass** [comment]
@olljanat thanks :) feel free to approve and merge!

**Comment by olljanat** [comment]
> @olljanat thanks :) feel free to approve and merge!

I would but only maintainers can do so...
maybe @cpuguy83 ?

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
