### PR TITLE
add selinux policy for centos-7

### LINKED ISSUE #28406: Installation fails on RedHat 7.3
@andrewhsu asked me to file this on the Docker Slack Community.

When I use `get.docker.com` to install Docker Engine on RedHat 7.3, I receive the following errors.

```
warning: /var/cache/yum/x86_64/7Server/docker-main-repo/packages/docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at /etc/selinux/targeted/tmp/modules/100/virt/cil:159
/usr/sbin/semodule:  Failed!
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 100 with module at priority 400.
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.12.3-1.el7.centos.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.12.3-1.el7.centos.noarch

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ec2-user

Remember that you will have to log out and back in for this to take effect!
```

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Added selinux policy for centos-7. Fixes issue #28406.

**- How I did it**

Sync with latest selinux policy for RHEL7 which is in RHEL RPM `docker-selinux-1.10.3-57.el7.x86_64` because that policy works on RHEL7.3.

I downloaded the SRPM on an Amazon EC2 instance of RHEL7:
```
$ sudo yumdownloader --enablerepo='*' --source docker-1.10.3-57.el7
```

And then cracked it open to get to the `docker.spec` file:
```
$ rpm2cpio docker-1.10.3-57.el7.src.rpm | cpio -idmv
```

Found the selinux policy is using lsm5/container-selinux@583a67ffdf9eef9afc233ace0f841d5eeef28fb3.

I use PR #25334 for reference in constructing this PR.

**- How to verify it**

Build a docker-engine-selinux centos-7 RPM package and install on RHEL7.3 with selinux enabled:
```
$ make DOCKER_BUILD_PKGS=centos-7 rpm
```

Should also make sure this works on CentOS7.2 with selinux enabled because CentOS7.3 is not released yet.

**- Description for the changelog**

Update selinux policy for distros based on RHEL7.3.

**- A picture of a cute animal (not mandatory but encouraged)**

🐰 

Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
is this also needed for the fedora packages?

**Comment by andrewhsu** [comment]
@thaJeztah yes, i think we may need to look into updating the fedora 25 selinux policies. Right now the fedora 25 docker-engine rpms are able to install (but show warnings #28099). The fedora 25 selinux policy update should be a separate PR.

**Comment by andrewhsu** [comment]
Stuff works. Success in build and install on RHEL7.3 with selinux enabled:
```
$ sudo yum install *.rpm
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Examining docker-engine-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.x86_64.rpm: docker-engine-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.x86_64
Marking docker-engine-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.x86_64.rpm to be installed
Examining docker-engine-selinux-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.noarch.rpm: docker-engine-selinux-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.noarch
Marking docker-engine-selinux-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package docker-engine.x86_64 0:1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos will be installed
---> Package docker-engine-selinux.noarch 0:1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================================================================================================================================================
 Package                              Arch                  Version                                                          Repository                                                                                     Size
=================================================================================================================================================================================================================================
Installing:
 docker-engine                        x86_64                1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos                 /docker-engine-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.x86_64                         64 M
 docker-engine-selinux                noarch                1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos                 /docker-engine-selinux-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.noarch                 45 k

Transaction Summary
=================================================================================================================================================================================================================================
Install  2 Packages

Total size: 64 M
Installed size: 64 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : docker-engine-selinux-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.noarch                                                                                                                                 1/2 
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 200 with module at priority 400.
  Installing : docker-engine-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.x86_64                                                                                                                                         2/2 
  Verifying  : docker-engine-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.x86_64                                                                                                                                         1/2 
  Verifying  : docker-engine-selinux-1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos.noarch                                                                                                                                 2/2 

Installed:
  docker-engine.x86_64 0:1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos                                     docker-engine-selinux.noarch 0:1.14.0-0.0.20161202.223924.gitbfe5cab.el7.centos                                    

Complete!
```

**Comment by andrewhsu** [comment]
/cc @crosbymichael 

Notice the `Dockerfile` has a test for `selinux-policy-devel` to get the latest. When centos7.3 is out, this line should be removed.

**Comment by crosbymichael** [comment]
LGTM

**Comment by runcom** [comment]
isn't it possible (somehow) to use the rhel packaged docker-selinux directly?

**Comment by thaJeztah** [comment]
@runcom see https://github.com/docker/docker/issues/29114 I guess

**Comment by cpuguy83** [comment]
Testing this out on centos7, just getting perm denied on basically anything in the container.
Busybox is the only container that seems to start for me.
Can't even get alpine going.

```
[root@localhost data]# docker run -it --rm alpine sh
Error relocating /lib/ld-musl-x86_64.so.1: RELRO protection failed: Permission denied
Error relocating /bin/sh: RELRO protection failed: Permission denied
```

**Comment by andrewhsu** [comment]
@cpuguy83 I tried to reproduce your issue on a clean [EC2 instance of CentOS7.2](https://aws.amazon.com/marketplace/pp/B00O7WM7QW), but stuff works for me:
```
bash# docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   bfe5cab
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   bfe5cab
 Built:        
 OS/Arch:      linux/amd64
 Experimental: false
bash# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)
bash# getenforce # check that selinux is enabled
Enforcing
bash# docker run -it --rm alpine sh
/ # 
```

Httpd works:
```
bash# docker run -d -p 80:80 httpd:2.4
e59392b44b78ab4ab3d5e8b1dbcee26e624e0b056d035a23c30ae7db7de4b77a
bash# curl localhost
<html><body><h1>It works!</h1></body></html>
```

Do the [selinux logs](https://wiki.gentoo.org/wiki/SELinux/Tutorials/Where_to_find_SELinux_permission_denial_details#SELinux_logging) say anything interesting?

**Comment by cpuguy83** [comment]
Running this in vagrant/vbox, with the same centos release, I'm getting the permissions issues.
Are you sure you have `selinux-enabled` set on the daemon?

<details>

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   2ef7294
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   2ef7294
 Built:
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.14.0-dev
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 489 MiB
Name: localhost.localdomain
ID: 3SQE:4BE2:5W3G:DDKW:3CNQ:OP6F:QZ6Z:LCL2:ICDY:MNZD:DWLD:AB5A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

</details>

**Comment by cpuguy83** [comment]
Ah, nevermind. Seems to be an issue with the vfs driver. Using overlay works ok.

LGTM.

**Comment by crosbymichael** [comment]
@runcom I would be up for just using the distro package for the selinux policies going forward.  The only reason I think we did this was because oracle did not package the selinux policies so we shipped them ourselves but for RH distros I think we can just use the system packages.

We are open to PRs if anyone has time to help test the change to put fedora, RH, and centos on the distro packages of selinux policies.  Right now @andrewhsu is pretty busy with RCs on the packaging side.

**Comment by runcom** [comment]
> @runcom I would be up for just using the distro package for the selinux policies going forward. The only reason I think we did this was because oracle did not package the selinux policies so we shipped them ourselves but for RH distros I think we can just use the system packages.
> 
> We are open to PRs if anyone has time to help test the change to put fedora, RH, and centos on the distro packages of selinux policies. Right now @andrewhsu is pretty busy with RCs on the packaging side.

@crosbymichael awesome, I'll take a look into that hopefully or point the relevant people to this, thanks!

**Comment by crosbymichael** [comment]
@runcom thanks, I think the change makes a lot more sense going forward.

**Pull request merged**
