### PR TITLE
[TP4] Windows: hacking around content addressable IDs for temporary fix.

### PR DESCRIPTION
**Pull request by swernli**
@jhowardmsft @tonistiigi @tiborvass @aaronlehmann 

This workaround is necessary for pulled images to correctly run on Windows.  It's a temporary workaround for TP4 until the right fix can be made to the Windows code.  This fixes the workflow issue mentioned in https://github.com/docker/docker/pull/17988.

Tibor, could we get this marked for TP4?

Signed-off-by: Stefan J. Wernli swernli@microsoft.com

### CODE REVIEW

**Comment by tiborvass** [comment]
i'm fine with this LGTM

**Comment by tonistiigi** [comment]
LGTM

This probably isn't the best place to add the exception, as essentially we just want to skip the validation and always use `compatibilityID`-s but I'm fine with it as we are already working on a big refactor that will remove all of this code.

**Comment by swernli** [comment]
@aaronlehmann Yes, this matches what I've observed.  If you try to pull the same image again without these changes, it will get re-downloaded with a new ID.  With this change, the second pull will fail a path not found error.  While not ideal, it at least allows the first pulled image to work. If you have any suggestions for other places to put this check further in the pull, then we can definitely add those as well.

**Comment by swernli** [comment]
Whoops... wrong button, accidental close!

**Comment by tonistiigi** [comment]
@swernli would it make more sense to change the `validateImageInGraph` itself. Just return out after you have detected the image is in graph. https://github.com/docker/docker/blob/ef424c108a90a04e9c5b0bd48b9047054a6a798b/graph/pull_v2.go#L660 Haven't tested of course.

**Comment by swernli** [comment]
@tonistiigi Good idea.  It turns out just changing validateImageInGraph wasn't enough, but if I combine an early exit in that method and the first workaround, the pull code uses the v1 ID for Windows images AND correctly recognizes when the image is already present and skips the extra pull.  I've tested the behavior with John and updated the PR.

**Comment by tonistiigi** [comment]
@swernli can you try this: https://github.com/docker/docker/compare/master...tonistiigi:18030_pull_id_hack

**Comment by swernli** [comment]
Yeah, that seems more direct, since our intent is to always use the compatibility ID on Windows.  Trying that now...

**Comment by swernli** [comment]
@tonistiigi Ok, I was finally able to verify the change you suggested, and confirm that it works as expected.  I've pushed up a new version, and hopefully Janky will be green so that we can get this reviewed and ready to go in.  Thanks for all the help!  I'll get back to the larger content-addressability changes now...

**Comment by crosbymichael** [comment]
LGTM

**Comment by aaronlehmann** [comment]
LGTM

**Comment by swernli** [comment]
Windows CI is angry again... I'm trying a rebuild, but given the reviews this has gotten so far, any chance we can merge this today?

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
