### PR TITLE
docker ps before and since filters documentation

### PR DESCRIPTION
**Pull request by tkopczynski**
When looking at PR #20135 I thought that these before and since filters lack some documentation. This is my proposition of what should be added, what do you think?

Signed-off-by: Tomasz Kopczynski tomek@kopczynski.net.pl

### CODE REVIEW

**Comment by thaJeztah** [comment]
Actually, we deprecated the `--before` and `--since` flags in favor of `--filter before...`, so removed some references from the docs (see https://github.com/docker/docker/pull/17718). However, perhaps you can rewrite this to provide better docs / example for the new `--filter` implementation?

TL;DR we only keep the "old" flags for backward compatibility for now, and don't want to point new users to the deprecated flags

**Comment by thaJeztah** [comment]
Lol, so never try to look at a diff in a hurry on my phone.. @vdemeester just pointed me that this is already describing the filters, haha

I'll have a proper look in a bit

**Comment by vdemeester** [comment]
@tkopczynski Looks good. I wonder if we should precise that as all filters it will not show non-running by default (but as I'm writing that I think we don't, it should be covered when explaining what is a filter).

LGTM 🐰

**Comment by tkopczynski** [comment]
@thaJeztah tricky phone :)
@vdemeester I was thinking about it myself but eventually decided not to mix different topics into one note and leave the rest to the filter definition

**Comment by thaJeztah** [comment]
yes, that was really embarrassing; just boarded my plane, so stay tuned :blush:

**Comment by thaJeztah** [comment]
Had a proper look this time :wink:

LGTM

Thanks for contributing, @tkopczynski!

**Pull request merged**
