### PR TITLE
Let's try fixing "netgo" again

### PR DESCRIPTION
**Pull request by tianon**
Since "go test" doesn't seem to support "-installsuffix" as quite the same perfect solution that "go build" is happy to let it be, let's just switch those crappy old "integration/" tests to use our separate static dockerinit binary so we don't have to worry about compiling the entire test harness statically. :+1:

### CODE REVIEW

**Comment by tianon** [comment]
(and this time, I tested `make all` on my local box before submitting :wink:)

(but @jfrazelle, that still doesn't mean you can trust me)

**Comment by tianon** [comment]
Just for future context, to chain this all together, see also https://github.com/docker/docker/pull/10087 and https://github.com/docker/docker/pull/10092

**Comment by jfrazelle** [comment]
running all the tests locally now

**Comment by jfrazelle** [comment]
Everything passes locally but I do seem some weird output in `test-unit` but if we think it is fine (because it still passes then ok :)):
```
---> Making bundle: test-unit (in bundles/1.4.1-dev/test-unit)
Mon Jan 19 17:50:25 UTC 2015
Precompiled: github.com/docker/docker/builder/parser
Precompiled: github.com/docker/docker/daemon/graphdriver/aufs
# testmain
/var/tmp/go-link-ENAVXw/000001.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/api
# testmain
/var/tmp/go-link-pHmSdC/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/daemon/graphdriver/btrfs
Precompiled: github.com/docker/docker/daemon/graphdriver/devmapper
Precompiled: github.com/docker/docker/daemon/graphdriver/overlay
Precompiled: github.com/docker/docker/daemon/execdriver/lxc
# testmain
/var/tmp/go-link-P73VLj/000002.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/daemon/networkdriver
# testmain
/var/tmp/go-link-3e3w2F/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/api/server
# testmain
/var/tmp/go-link-beHEiC/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/daemon/networkdriver/portallocator
# testmain
/var/tmp/go-link-Ul76Tb/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/daemon/graphdriver/vfs
Precompiled: github.com/docker/docker/daemon/networkdriver/ipallocator
# testmain
/var/tmp/go-link-DOGksg/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/daemon/networkdriver/portmapper
# testmain
/var/tmp/go-link-PaRHPI/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/daemon/networkdriver/bridge
# testmain
/var/tmp/go-link-ysj5DI/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/nat
# testmain
/var/tmp/go-link-Y7hRAq/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/events
# testmain
/var/tmp/go-link-5DgMXP/000001.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/broadcastwriter
Precompiled: github.com/docker/docker/engine
# testmain
/var/tmp/go-link-Qh6rP6/000001.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/links
# testmain
/var/tmp/go-link-KwYv1g/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/archive
Precompiled: github.com/docker/docker/daemon
# testmain
/var/tmp/go-link-advzB7/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/ioutils
Precompiled: github.com/docker/docker/opts
# testmain
/var/tmp/go-link-AbjPTX/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/chrootarchive
Precompiled: github.com/docker/docker/pkg/iptables
# testmain
/var/tmp/go-link-qKFyWk/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/jsonlog
Precompiled: github.com/docker/docker/pkg/mflag
Precompiled: github.com/docker/docker/pkg/graphdb
Precompiled: github.com/docker/docker/pkg/mount
Precompiled: github.com/docker/docker/graph
# testmain
/var/tmp/go-link-4UznMg/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/networkfs/etchosts
Precompiled: github.com/docker/docker/pkg/namesgenerator
Precompiled: github.com/docker/docker/pkg/parsers
Precompiled: github.com/docker/docker/pkg/parsers/filters
Precompiled: github.com/docker/docker/pkg/parsers/kernel
Precompiled: github.com/docker/docker/pkg/parsers/operatingsystem
Precompiled: github.com/docker/docker/pkg/symlink
Precompiled: github.com/docker/docker/pkg/stdcopy
Precompiled: github.com/docker/docker/pkg/tailfile
Precompiled: github.com/docker/docker/pkg/proxy
# testmain
/var/tmp/go-link-JWS0CE/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/system
Precompiled: github.com/docker/docker/pkg/networkfs/resolvconf
# testmain
/var/tmp/go-link-mjJHyK/000001.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/pkg/urlutil
Precompiled: github.com/docker/docker/pkg/tarsum
Precompiled: github.com/docker/docker/pkg/version
Precompiled: github.com/docker/docker/pkg/units
Precompiled: github.com/docker/docker/pkg/truncindex
# testmain
/var/tmp/go-link-viTIRG/000001.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/utils
# testmain
/var/tmp/go-link-aXgI4f/000001.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/runconfig
# testmain
/var/tmp/go-link-cpwtdq/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Precompiled: github.com/docker/docker/registry
# testmain
/var/tmp/go-link-bsJNWB/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/local/go/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

+ go test -test.timeout=30m github.com/docker/docker/api
PASS
coverage: 10.3% of statements

```

**Comment by LK4D4** [comment]
Hehe, looks really weird. I liked reinstalling stdlib more.

**Comment by tianon** [comment]
Ah, that's not good.  Those can actually break tests.  I don't think the
unit tests even need to be statically compiled, so give me a sec and I'll
work on that.

**Comment by erikh** [comment]
fwiw libpack has the same problem. /cc @shykes

**Comment by tianon** [comment]
Updated!

**Comment by jfrazelle** [comment]
```
---> Making bundle: dyntest-unit (in bundles/1.4.1-dev/dyntest-unit)
hack/make.sh: line 234: /go/src/github.com/docker/docker/hack/make/dyntest-unit: No such file or directory
```

**Comment by tianon** [comment]
Whoops, nice catch.  Updated again!

**Comment by jfrazelle** [comment]
LGTM

**Comment by crosbymichael** [comment]
only LGTM'ing for +46  −72

**Comment by tianon** [comment]
@crosbymichael :heart:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
