### PR TITLE
Concatenate image with registry if provided

### LINKED ISSUE #15085: Unable to specify registry in query string for image/create api endpoint
I'm trying to create using API:
```
$ curl -v -XPOST --unix-socket /var/run/docker.sock "http:/images/create?fromImage=bronislav/clsi-sharelatex:latest&registry=quay.io"
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> POST /images/create?fromImage=bronislav/clsi-sharelatex:latest&registry=quay.io HTTP/1.1
> Host: http
> User-Agent: curl/7.42.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 28 Jul 2015 14:22:51 GMT
< Transfer-Encoding: chunked
<
{"status":"Pulling repository bronislav/clsi-sharelatex"}
{"errorDetail":{"message":"Error: image bronislav/clsi-sharelatex:latest not found"},"error":"Error: image bronislav/clsi-sharelatex:latest not found"}
* Connection #0 to host http left intact
```
If I move registry parameter to the image path than docker started to pull image:
```
curl -v -XPOST --unix-socket /var/run/docker.sock "http:/images/create?fromImage=quay.io/bronislav/clsi-sharelatex:latest"
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> POST /images/create?fromImage=quay.io/bronislav/clsi-sharelatex:latest HTTP/1.1
> Host: http
> User-Agent: curl/7.42.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 28 Jul 2015 14:48:16 GMT
< Transfer-Encoding: chunked
<
{"status":"Pulling repository quay.io/bronislav/clsi-sharelatex"}
...
{"status":"Status: Image is up to date for quay.io/bronislav/clsi-sharelatex:latest"}
* Connection #0 to host http left intact
```
My environment:
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d-dirty
OS/Arch (server): linux/amd64
```
[Docs for API v1.19](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#create-an-image) states that it is possible to specify `registry` query parameter:

```
Query Parameters:
    ...
    registry – The registry to pull from.
    ...
```
But it seems that this parameter ignored in the request handler. It's only takes in account `fromImage`, `repo` and `tag` parameters: [api/server/server.go#L729-L733](https://github.com/docker/docker/blob/master/api/server/server.go#L729-L733).

### PR DESCRIPTION
**Pull request by bronislav**
Signed-off-by: Anton Ilin anton@ilin.dn.ua (github: bronislav)

Fixes #15085

### CODE REVIEW

**Comment by stevvooe** [comment]
@docker/distribution-maintainers 

In general, I would expect the "registry" should be specified in the `fromImage` parameter. Explicitly calling out the registry goes against the general theme of communicating with registry to use. I am not sure how this API parameter slipped through but it's not implemented. We should probably remove it from the documentation.

We are working on making this a little more flexible, but the approach is at the docker daemon level. Some work is going on in https://github.com/docker/distribution/pull/193, but this will likely end up looking a little different.

Does anyone else know the history of the "registry" parameter and why it was left unimplemented?

**Comment by thaJeztah** [comment]
@stevvooe the parameter itself was introduced with release 0.4 (which was just one release before I started playing around with Docker, LOL), added in https://github.com/docker/docker/pull/432 in this commit https://github.com/docker/docker/commit/10c0e990371e065d4fc1c9b680f03a46e5bacc5e

So @vieux or Solomon are the ones that should know

**Comment by bronislav** [comment]
Just removing this parameter from docs won't solve the whole problem. I know about at least one project that relaying on this parameter [https://github.com/fsouza/go-dockerclient/](fsouza/go-dockerclient).

**Comment by stevvooe** [comment]
@bronislav I am not sure how anyone is "relying" on an unimplemented API parameter. The correct fix is to remove the documentation.

This code was last modified by 714b63d1, in July 2014.

The correct API usage would be to prepend `fromImage` with the registry, as is done throughout docker's UI and API. Have you tried that?

**Comment by icecrime** [comment]
@stevvooe Is that a close?

**Comment by thaJeztah** [comment]
@icecrime if it's closed, we should put that parameter on the deprecation list

**Comment by stevvooe** [comment]
@icecrime I am voting for a close.

@thaJeztah I am not sure what the policy here would be. If we consider the API docs to be a specification, we need to deprecate with a note saying it was never implemented. If we consider the API docs to be docs, we should remove the mention of it.

**Comment by icecrime** [comment]
@thaJeztah Yes let's do that, it seems that thing should never have existed.

Closing this.

**Pull request closed without merging**
