### PR TITLE
Add Kir as maintainer

### PR DESCRIPTION
**Pull request by thaJeztah**
As voted per e-mail

Welcome @kolyshkin as a maintainer! (long overdue 😅 🤗)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@moby.maintainers

**Comment by thaJeztah** [comment]
@moby/moby-maintainers

**Review by AkihiroSuda — APPROVED** [review]
LGTM :+1:

**Review by vdemeester — APPROVED** [review]
LGTM :tada:

**Review by coolljt0725 — APPROVED** [review]
LGTM

**Comment by tianon** [comment]
LGTM!! 🌟

**Review by lowenna — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
All green; let's get this merged :+1:

**Comment by kolyshkin** [comment]
Ughm, I can't even add an animated gif to here; maybe this alone makes me non-qualified :) anyway, here's what I've been doing all day today: https://www.youtube.com/watch?v=gisZcyaVLM4

**Pull request merged**
