### PR TITLE
Vendoring libnetwork and netlink

### LINKED ISSUE #30321: Zero-downtime deployments with rolling upgrades
Hey all,

**Usecase**
I have a front-end proxy which listens on ports `80` and `443`. My applications are deployed as microservices behind this proxy, which acts as a layer-7 load balancer for those applications. These applications are, for example, `php:7-apache` containers which simply listen on port `80` for HTTP requests. The idea is to have at least 2 replicas for a service, so they can be upgraded incrementally using the *rolling upgrade* functionality that comes with Docker Swarm.

**Issue**
At this point, I'm not sure if zero-downtime deployments using the rolling update functionality of Docker Swarm are even possible, at least for my use case. There is one major issue for me here.

When containers are stopped during the rolling update, they are always stopped using the same signal (SIGTERM, or SIGKILL after a certain period). Many images, like the aforementioned apache-based image, won't gracefully shutdown with a SIGTERM, but need a different signal to be sent for the container to shutdown in a graceful way. I created an issue (#25696) for this as well, but this didn't make the 1.13 release. I don't see how the current rolling upgrade system can work in any use case, except for the cases where containers *actually* are designed specifically to shutdown gracefully when receiving a SIGTERM. In my situation, upgrading the service leads to intermittent HTTP-502 errors until the upgrade is complete. I can't imagine this not being a problem for anyone else, unless I'm missing something obvious.

**Possible workaround**
Wrap the main command of an image that needs to be able to shutdown gracefully in a wrapper script:

```bash
shut_down() {
  kill -SIGWINCH ${SCRIPT_PID}
}

trap 'shut_down' SIGTERM SIGINT

start_apache &

SCRIPT_PID = "$!"
wait ${SCRIPT_PID}
```

This would immediately fix the issue I'm having, since any `SIGINT` or `SIGTERM` that reaches the container would simply be relayed as a `SIGWINCH`. In this case, this would gracefully shutdown my apache container. However, this would mean that I would have to modify every image I'm using to use this script. It's also a non-standard and to be fair, a nasty solution.

What's the recommended course of action here? Am I missing a piece of the puzzle, or simply overseeing something? Also: even if *this* issue would be solved, would I get true **zero downtime** deployments with the rolling upgrade functionality of Docker Swarm Mode? In other words, are containers actually removed from the ingress load balancing pool prior to sending the `stop_signal` during the upgrade, or would I still get HTTP-502 errors from containers that are still being load-balanced *to*, but would be in the process of shutting down?

### PR DESCRIPTION
**Pull request by mavenugo**
libnetwork eb57059e91bc54c9da23c5a633b75b3faf910a68
netlink bd6d5de5ccef2d66b0a26177928d0d8895d7f969

Fixes https://github.com/moby/moby/issues/32195 via https://github.com/docker/libnetwork/pull/1792
Fixes #30321 via https://github.com/docker/libnetwork/pull/1792
Fixes https://github.com/moby/moby/issues/33346 via https://github.com/docker/libnetwork/pull/1775
Includes https://github.com/docker/libnetwork/pull/1786 , https://github.com/docker/libnetwork/pull/1787 , https://github.com/docker/libnetwork/pull/1789
 

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
vendor failing:
```
00:01:31.264 The result of vndr differs
00:01:31.265 
00:01:31.265  M vendor/github.com/docker/libnetwork/drivers/overlay/overlay.go
00:01:31.265  M vendor/github.com/docker/libnetwork/vendor.conf
00:01:31.265 ?? vendor/github.com/vishvananda/netlink/README.md
00:01:31.265 
00:01:31.265 Please vendor your package with github.com/LK4D4/vndr.
```

**Comment by sanimej** [comment]
Fixes #30321.

[libnetwork #1792](https://github.com/docker/libnetwork/pull/1792) addresses the 2nd issue [mentioned here](https://github.com/moby/moby/issues/30321#issuecomment-300948222)

**Comment by thaJeztah** [comment]
@mavenugo https://github.com/moby/moby/pull/33555 was already closed via https://github.com/moby/moby/pull/33463, or does this bring additional fixes?

**Comment by mavenugo** [comment]
@thaJeztah this brings additional patches.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
This was cherry-picked into 17.06 through https://github.com/docker/docker-ce/pull/55

**Pull request merged**
