### PR TITLE
only sign the files that were changed in the last 2 hours

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon

### CODE REVIEW

**Comment by tianon** [comment]
If I'm understanding right, the problem is that we're re-signing files unnecessarily, right?

Couldn't we take advantage of `mtime` to only re-sign when the file has changed more recently than the signature file?
```console
$ help test
test: test [expr]
...
      FILE1 -nt FILE2  True if file1 is newer than file2 (according to
                       modification date).
...
```

**Comment by jfrazelle** [comment]
ah cool ya, and i was just getting bored of signing em all, not that it matters but would be nice to be smart about it

**Comment by tianon** [comment]
Agree, might as well! :+1:

**Comment by tianon** [comment]
(less churn for the cache too)

**Comment by jfrazelle** [comment]
hmmm idk what to check against wrt to the yum repo... going to try a few
things

**Comment by jfrazelle** [comment]
wow disregard lol

**Comment by jfrazelle** [comment]
updated

**Comment by tianon** [comment]
LGTM :+1:

**Comment by calavera** [comment]
LGTM :tada:

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
