### PR TITLE
[20.10] vendor: github.com/docker/libnetwork 1f3b98be6833a93f254aa0f765ff55d407dfdd69

### PR DESCRIPTION
**Pull request by thaJeztah**
- backports https://github.com/moby/moby/pull/42545
- includes https://github.com/moby/moby/pull/42569

- fix linting issues
- update to go1.18.9, gofmt, and regenerate proto
- processEndpointCreate: Fix deadlock between getSvcRecords and processEndpointCreate

full diff: https://github.com/docker/libnetwork/compare/dcdf8f176d1e13ad719e913e796fb698d846de98...1f3b98be6833a93f254aa0f765ff55d407dfdd69

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Arf.. vanity URLs;

```
2022-12-22T00:01:12.571Z] 2022/12/22 00:01:12 unrecognized import path "code.cloudfoundry.org/clock" (https fetch: Get "https://code.cloudfoundry.org/clock?go-get=1": x509: certificate is valid for *.de.a9sapp.eu, de.a9sapp.eu, not code.cloudfoundry.org)
```

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
sigh, and back to "we messed up our vanity URL" 😞 

```
[2022-12-22T21:51:14.886Z] 2022/12/22 21:51:14 

unrecognized import path "code.cloudfoundry.org/clock" 
(https fetch: Get "https://code.cloudfoundry.org/clock?go-get=1": 
x509: certificate is valid for *.de.a9sapp.eu, de.a9sapp.eu, not code.cloudfoundry.org)
script returned exit code 1
```

I'll probably gonna have to point `vendor.conf` directly to their upstream GitHub repo

**Comment by thaJeztah** [comment]
Opened https://github.com/moby/moby/pull/44691 to fix it

**Comment by thaJeztah** [comment]
Rebased, as https://github.com/moby/moby/pull/44691 was merged

**Comment by thaJeztah** [comment]
All green now; bringing this in 👍

**Pull request merged**
