### PR TITLE
Fix the network inspect id

### LINKED ISSUE #22231: Network inspect Id vs ID
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-58-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: <removed>
ID: <removeD>
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create docker network
2. docker network inspect network
3. docker network inspect network -f {{.Id}}

**Describe the results you received:**

When running network inspect, the JSON output shows the "Id" field capitalised as such, however, running an inspect -f will fail if "{{.Id}}" is used, and instead is should be written "{{.ID}}

**Describe the results you expected:**

for inspect -f {{.Id}} to return the ID as the consistent name displayed in a bare network inspect.

**Additional information you deem important (e.g. issue happens only occasionally):**

TL;DR Network ID is named "Id" in network inspect, but network inspect -f expects "ID".

### PR DESCRIPTION
**Pull request by HackToday**
This fixes #22231

Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
ping @vdemeester

**Comment by thaJeztah** [comment]
Thanks @HackToday change LGTM, but can you add a very simple integration test that verifies that both `Id` and `ID` work and return the same result? e.g.

```
docker network create test-network
docker network inspect -f "{{.Id}}"  test-network
docker network inspect -f "{{.ID}}"  test-network
```
output of both inspects should return the same

**Comment by thaJeztah** [comment]
Also note that this will need a rebase if https://github.com/docker/docker/pull/23210 is merged

**Comment by HackToday** [comment]
@thaJeztah  rebased and test added

**Comment by thaJeztah** [comment]
awesome!

LGTM

ping @vdemeester for review/merge

**Comment by vdemeester** [comment]
LGTM 🐰

**Pull request merged**
