### PR TITLE
Bump Golang 1.13.4

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

**- What I did**

Update golang to 1.13.4.

The full diff https://github.com/golang/go/compare/go1.13.3...go1.13.4

go1.13.4 (released 2019/10/31) includes fixes to the <code>net/http</code> and
<code>syscall</code> packages. It also fixes an issue on macOS 10.15 Catalina
where the non-notarized installer and binaries were being
<a href="https://golang.org/issue/34986">rejected by Gatekeeper</a>.
See the <a href="https://github.com/golang/go/issues?q=milestone%3AGo1.13.4">Go 1.13.4 milestone</a> on our issue tracker for details.

PS: I did a quick check, the problems fixed in this version will not affect docker core.

### CODE REVIEW

**Comment by tao12345666333** [comment]
wait for https://github.com/docker-library/official-images/pull/6896

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
Rerun CI since it failed earlier because the golang image was not available at the time

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
