### PR TITLE
api/types/container,client: gofmt

### PR DESCRIPTION
**Pull request by unclejack**
**- What I did**
I've fixed three issues discovered by gofmt.

**- Description for the changelog**
api/types/container,client: gofmt

### CODE REVIEW

**Comment by vdemeester** [comment]
ping @dnephin as I think `api/types/container` is generated from `swagger`.

**Comment by dnephin** [comment]
Nope, these files are not generated (yet). All generated files have a comment at the top of the file about it.

**Comment by aaronlehmann** [comment]
LGTM

Did these slip in from PRs opened during the period where validation was not being properly enforced by CI?

**Comment by vdemeester** [comment]
Hum probably 😣
LGTM 😇🐳

**Pull request merged**
