### PR TITLE
vendor: github.com/armon/go-metrics: fix broken file permissions

### PR DESCRIPTION
**Pull request by metux**
Source files should never have execute permissions.

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
```

[2021-05-07T14:23:07.927Z] The result of vndr differs
[2021-05-07T14:23:07.927Z] 
[2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/metrics.go
[2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/sink.go
[2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/start.go
[2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/statsite.go
[2021-05-07T14:23:07.927Z] 
[2021-05-07T14:23:07.927Z] Please vendor your package with github.com/LK4D4/vndr.
```

Please fix the permission bits in the upstream repo, update vendor.conf, and then run hack/vndr.sh

**Comment by metux** [comment]
> ```
> 
> [2021-05-07T14:23:07.927Z] The result of vndr differs
> [2021-05-07T14:23:07.927Z] 
> [2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/metrics.go
> [2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/sink.go
> [2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/start.go
> [2021-05-07T14:23:07.927Z]  M vendor/github.com/armon/go-metrics/statsite.go
> [2021-05-07T14:23:07.927Z] 
> [2021-05-07T14:23:07.927Z] Please vendor your package with github.com/LK4D4/vndr.
> ```
> 
> Please fix the permission bits in the upstream repo, update vendor.conf, and then run hack/vndr.sh

Unfortunately, I'm not the upstream, so I can't do that.

**Comment by metux** [comment]
Just checked the upstream - they've fixed the issue about 4 years ago.

Is there any specific reason for keeping around such old vendor code ?

**Comment by thaJeztah** [comment]
> Is there any specific reason for keeping around such old vendor code ?

I believe this is an indirect dependency, coming in as dependency from https://github.com/docker/libnetwork. I recall I had a PR to update the dependency in https://github.com/moby/libnetwork/pull/2441 (just rebased it to see if CI passes)

**Comment by AkihiroSuda** [comment]
Covered by https://github.com/moby/libnetwork/pull/2441 , so closing

**Pull request closed without merging**
