### PR TITLE
Fix file mode for docker bash completion

### PR DESCRIPTION
**Pull request by DieterReuter**
A bash completion file shouldn't have a executable bit set.
Just change file mode to 644 (instead of 755)

Signed-off-by: Dieter Reuter dieter.reuter@me.com

### CODE REVIEW

**Comment by vdemeester** [comment]
@DieterReuter you need a rebase, you're branch is ~3400 commits below :sweat_smile:.

**Comment by DieterReuter** [comment]
Uups, will do!

**Comment by jfrazelle** [comment]
can you please squash your commits

**Comment by DieterReuter** [comment]
I just close it and create a new clean PR, that's easier for me right now.

**Pull request closed without merging**
