### PR TITLE
cherry-picks 1.12.3

### PR DESCRIPTION
**Pull request by vieux**
- [#27474](https://github.com/docker/docker/pull/27474)
  - 53ed17449e990f49e8eecdf71ec3704ce7118660 Update fluent-logger-golang to v1.2.1
- [#27421](https://github.com/docker/docker/pull/27421)
  - e0c7300e3b2abea3d32d591fb01ee798ff59e0d4 Add AppArmor to runc buildtags for armhf
- [#27387](https://github.com/docker/docker/pull/27387)
  - b8793cff48fc4c1b702917ebc528ca0c60fb3397 Reset health status to starting when a container is restarted
- [#27327](https://github.com/docker/docker/pull/27327)
  - 63515bc59e5be4cebaa475ec4c8fe992a6c1107d debian package: update buildtags for armhf ubuntu-trusty
- [#27136](https://github.com/docker/docker/pull/27136)
  - 5143be0ccf70c7cb2acc2aa39fd7ec47450e5daa add lock in libcontainerd client AddProcess of Windows
- [#27075](https://github.com/docker/docker/pull/27075)
  - 57e12037ac8f8eb48cc05979c3030853d011dfea Fix error reporting in `CopyFileWithTar` 
- [#27007](https://github.com/docker/docker/pull/27007)
  - ddec4c3ee4e51cb62060f752777bdd32e86607e3 add \n in engine labels display in docker node inspect xxx --pretty
- [#27062](https://github.com/docker/docker/pull/27062)
  - bc32fcabebb5f3a83d47c00d85317ce82c963edf Fix conversion of restart-policy from GRPC 
- [#27609](https://github.com/docker/docker/pull/27609)
  - 70dfea63ba2a8a6d8b367420039aeb6a1759c240 chroot: let root be cleaned up by kernel 
  - b511d1f0cabd32ca30c87fa1bbc7ecac283dab39 chroot: remount everything as private in new mntns

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by justincormack** [comment]
Can you add #27634 its just a test

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
@vieux we may want to add https://github.com/docker/docker/pull/27630 in this PR (or a separate one if you prefer that)

**Comment by thaJeztah** [comment]
Forget my last comment; looks like it's not in 1.12 https://github.com/docker/docker/pull/27630#issuecomment-255420962

**Comment by vieux** [comment]
ping @docker/core-engine-maintainers  it's ready for review.

**Comment by mlaventure** [comment]
LGTM.

**Comment by tonistiigi** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
