### PR TITLE
api/client - The code for all cli commands are in one file #11610

### LINKED ISSUE #11610: api/client - The code for all cli commands are in one file
**Problem**
 
api/client - Break down commands in multiple files
 
**Solution**
 
The `api/client/commands.go` file hold the code for every Docker client command, which makes up for 2700+ lines!
 
Break this down into one dedicated file per subcommand (e.g., `docker push` related code in `api/client/push.go`). Note that the m"main function" for each subcommand is easily found as it is always named `CmdName` (e.g., `CmdPush`) in this file.

### PR DESCRIPTION
**Pull request by joeygibson**
Closes #11610

Signed-off-by: Joey Gibson joey@joeygibson.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
should probably get this in fast to avoid rebase hell, looks like nothing changed, so just waiting on janky

**Comment by jfrazelle** [comment]
also since i'm a nice person I say we merge this and if heaven forbid we need a fix after that is going to cause cherry-pick problems into the release branch, i'll handle them :)

**Comment by joeygibson** [comment]
There was an error with the Windows build last night, but that one just now succeeded.

**Comment by duglin** [comment]
yep - Looking good!

**Comment by jfrazelle** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
