### PR TITLE
Added information about deactivating Hyper-V for windows installations

### PR DESCRIPTION
**Pull request by nwright-nz**
In the Windows installation section there is no mention of the particular scenario of Hyper-V being installed on the windows machine. As Hyper-V and VirtualBox cannot both be active, added instructions on disabling the Hyper-V services. If this isn't done, an error occurs during the pre-create checks.

Signed-off-by: Nigel Wright hertzz@gmail.com

### CODE REVIEW

**Comment by nwright-nz** [comment]
Apologies for the number of commits in this very basic PR - its my first one and I had a couple of minor issues with this.

**Comment by SvenDowideit** [comment]
personally, I add a bootup option to disable hyper-v - that makes it easy to switch between them - see http://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx

**Comment by MHBauer** [comment]
@nwright-nz Definitely need to squash the commits down into one. You can see our instructions in the docs [here](https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently).

I do like @SvenDowideit's link for the ability to switch on boot. 

I would hope that people who are using Hyper-V know that they need it or not. I don't want to have a blanket recommendation for removal. Is there a warning that we can insert that shows the failure of VirtualBox? Better to show a solution to a potential problem, and what the problem looks like.

**Comment by nwright-nz** [comment]
Thanks for the feedback @MHBauer - Will ensure that all commits are squashed into one. 
@SvenDowideit - nice, hadn't seen that before. I could certainly add the failure message from virtualbox when Hyper-V is enabled, and include the information provided in the link above as a workaround. Does that sound like a viable solution?

**Comment by calavera** [comment]
I have mixed feelings about this guide. Ping @jhowardmsft for MS awesomeness.

**Comment by jhowardmsft** [comment]
Hmmm. Me too, but I'm going to defer to our PMs. @taylorb-microsoft @scooley

**Comment by enderb-ms** [comment]
@theodthompson will be taking a look at this when he's back in the office later in the week.

**Comment by theodthompson** [comment]
I like what @MHBauer said about addressing the error message. Machine gives you an error during the pre-create check that Hyper-V is installed... We should point users in the right direction if they search for the error.

Overall though, it's a bit burdensome to uninstall all of hyper-v just to switch back and forth. Can we tell people to just disable the hypervisor component, and leave the rest of the tools in place? I can follow up with instructions on how to do that.

Ideally, Machine should check to see if a hypervisor is running. Right now it essentially checks if Hyper-V is installed, so this could be more precise. I can submit an issue to change this.

Thoughts?

**Comment by nwright-nz** [comment]
Should I close this PR with the assumption that an issue will be raised for Machine to provide a clearer error message about the running hypervisor (as mentioned above by @theodthompson )? Or is still of value to include the instructions on how to disable the hypervisor component of Hyper-V? Thanks all!

**Comment by theodthompson** [comment]
@nwright-nz I think it's still valuable to show people how to turn off the Hyper-V hypervisor when they search for the error. Maybe we should regroup if/when the error message is made more specific? I'll get the issue opened. Thanks!

**Comment by nwright-nz** [comment]
Thanks @theodthompson. Will hold fire for now. Cheers!

**Comment by justincormack** [comment]
We need to revise all these documents now there is Docker for Windows as well, which requires Hyper-V, so it would be better perhaps if the detailed docs about virtualbox went into the Machine docs.

**Comment by moxiegirl** [comment]
@londoncalling Are you aware of this?  WDYT?

**Comment by londoncalling** [comment]
@moxiegirl I'm aware of the issue re: Machine, Hyper-V and Virtual Box. I'll talk with @justincormack about how to manage this in docs across these products, since Docker for Windows uses Hyper-V ... it wasn't clear to me when I talked with Michael Friis whether there is any means of resolving the conflict. It seems problematic that one key product requires Hyper-V (Docker for Windows) and the other can't run with it on / installed (Docker Machine), especially when most customers will have both products. I'm wondering if there is any possibility of modifying Docker Machine to be compatible / leverage Hyper-V?

**Comment by theodthompson** [comment]
@londoncalling Machine can already use Hyper-v as a driver, but you have to look for the option. With Docker for Windows out now, maybe it makes sense to make Hyper-V the "default" driver for Machine on Windows? "default" meaning that Hyper-V would replace VB in the "getting started"/install guides. 
Just my .02 :)

**Comment by londoncalling** [comment]
@theodthompson that makes sense to me to make Hyper-V the "default" because I think it would make for a more seamless startup-and-run user experience. Do you think so?

**Comment by moxiegirl** [comment]
@nathanleclaire  Maybe has plans to do this.

**Comment by nathanleclaire** [comment]
Docker for Windows will be when the switchover to using Hyper-V by default will be.  Machine/Toolbox has no plans to do so.

**Comment by friism** [comment]
I think it's confusing if we add this because Docker for Windows actually requires Hyper-V. At a minimum, the docs should express that.

**Comment by londoncalling** [comment]
@friism @justincormack @nathanleclaire I'll update the Docker Machine and Toolbox docs, and ask you all to review the new info. I'll probably need a couple of review cycles to get this right across the different product docs.

**Comment by thaJeztah** [comment]
I'll close this PR, pending the docs changes that @londoncalling is making, thanks @nwright-nz !

**Pull request closed without merging**
