### PR TITLE
Move ErrorContains to an internal package

### PR DESCRIPTION
**Pull request by dnephin**
Part of #32989
Follow up to #34600

Remove the last of `pkg/testutil` and move it to an internal package so that any tests in this repo can use it, but we don't have to support it externally.

If https://github.com/stretchr/testify/pull/486 is ever accepted we can replace it with upstream.

### CODE REVIEW

**Comment by vieux** [comment]
@dnephin needs a rebase

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by vdemeester** [comment]
@dnephin needs a rebase 😛

**Comment by yongtang** [comment]
All tests passed. Merging.

**Pull request merged**
