### PR TITLE
docs/rootless.md: move to https://docs.docker.com/engine/security/rootless/

### PR DESCRIPTION
**Pull request by AkihiroSuda**
The doc was moved to https://docs.docker.com/engine/security/rootless/

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

wondering if we should remove the whole file, or do we know of links referring to this?

**Comment by AkihiroSuda** [comment]
There are links: https://www.google.com/search?q=%22https://github.com/moby/moby/blob/master/docs/rootless.md%22&filter=0

**Comment by thaJeztah** [comment]
Ah, yeah that's a bit too many links, thanks!

**Comment by AkihiroSuda** [comment]
@tonistiigi @tiborvass @tianon PTAL

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
