### PR TITLE
Proposal: add more options to docker version

### PR DESCRIPTION
**Pull request by aanm**
DO NOT MERGE.
Fixes issue #10934

``` bash
[aanm@localhost docker]$ sudo docker version 
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): db211f9
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): db211f9
OS/Arch (server): linux/amd64
[aanm@localhost docker]$ sudo docker version default
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): db211f9
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): db211f9
OS/Arch (server): linux/amd64
[aanm@localhost docker]$ sudo docker version prefix
Client version: 1.5.0-dev
Client API version: 1.18
Client go version: go1.4.2
Client Git commit version: db211f9
Client OS/Arch: linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Server Go version: go1.4.2
Server Git commit: db211f9
Server OS/Arch: linux/amd64
[aanm@localhost docker]$ sudo docker version suffix
Version (client): 1.5.0-dev
API version (client): 1.18
Go version (client): go1.4.2
Git commit (client): db211f9
OS/Arch (client): linux/amd64
Version (server): 1.5.0-dev
API version (server): 1.18
Go version (server): go1.4.2
Git commit (server): db211f9
OS/Arch (server): linux/amd64
[aanm@localhost docker]$ sudo docker version sectioned
Client
  Version: 1.5.0-dev
  API version: 1.18
  Go version: go1.4.2
  Git commit: db211f9
  OS/Arch: linux/amd64
Server
  Version: 1.5.0-dev
  API version: 1.18
  Go version: go1.4.2
  Git commit: db211f9
  OS/Arch: linux/amd64
[aanm@localhost docker]$ sudo docker version tabular
                Client          Server         
Version:        1.5.0-dev       1.5.0-dev      
API version:    1.18            1.18           
Go version:     go1.4.2         go1.4.2        
Git commit:     db211f9         db211f9        
OS/Arch:        linux/amd64     linux/amd64 
```

Missing:
- Tests
- Docs
  Signed-off-by: André Martins martins@noironetworks.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
wait before you put in all this work I think we should reach a design decision on https://github.com/docker/docker/issues/10934

**Comment by aanm** [comment]
Can't we have them all? :-)
That's why I didn't make tests nor change docs

**Comment by jfrazelle** [comment]
can you add #10934 to the original comment so people see it easily

**Comment by aanm** [comment]
It is already there ;-)

**Comment by jfrazelle** [comment]
sorry weird refresh issue :/

**Comment by albers** [comment]
For the formatting options I would prefer real options like `--tabular` instead of subcommands (`tabular`).

**Comment by duglin** [comment]
I must say... as much as I usually like to give people options, having this many for what should one of the most basic commands feels a little silly.  Unless you were just showing the various options and we're supposed to vote/pick one.

In which case, I'd vote for one that includes client or server on each line, then its easier to grep for just the info you're looking for.  So, no "sectioned" or "tabular".  I like "prefix", put the highest order bit first  :-)

**Comment by phemmer** [comment]
@duglin See discussion on #10934 

One of the ideas was that if we added a `--format` argument, grep would not be necessary. Then the output would be for human eyes only. Scripts would use `--format`.

**Comment by duglin** [comment]
just seems like a lot of work for "version".  :-)

**Comment by icecrime** [comment]
Sorry I'm -1 on design: I can understand the need for a programmatically parseable version output, but this is way to complicated (and only make it programmatically parseable by making the human output more systematic).

**Comment by icecrime** [comment]
I'm going to close this, but please feel free to resubmit a subset of that patch when an agreement is reached on #10934!

**Pull request closed without merging**
