### PR TITLE
Revert "Disable TestExecWindowsOpenHandles on RS5 temporarily"

### PR DESCRIPTION
**Pull request by olljanat**
**- What I did**
Based on https://github.com/moby/moby/issues/38114#issuecomment-452074320 it should be possible to restore these tests to use.

**- How to verify it**
Let's see if RS5 passes CI

### CODE REVIEW

**Comment by olljanat** [comment]
Hmm. RS1 (which this change should not affect) failed to:
```
10:19:35 FAIL: docker_cli_start_test.go:189: DockerSuite.TestStartReturnCorrectExitCode
10:19:35 
10:19:35 docker_cli_start_test.go:199:
10:19:35     c.Assert(exitCode, checker.Equals, 12, check.Commentf("out: %s", out))
10:19:35 ... obtained int = 125
10:19:35 ... expected int = 12
10:19:35 ... out: time="2019-01-11T10:19:34Z" level=error msg="error waiting for container: EOF" 
```
RS5 failed to:
```
08:05:43 FAIL: docker_cli_exec_test.go:544: DockerSuite.TestExecWindowsOpenHandles
08:05:43 
08:05:43 docker_cli_exec_test.go:575:
08:05:43     c.Fatal("too many retries")
08:05:43 ... Error: too many retries
08:05:43 
08:05:43 assertion failed: 
08:05:43 Command:  d:\CI\CI-2a454228e7\binary\docker.exe exec test cmd /c start sleep 10
08:05:43 ExitCode: 3221225473
08:05:43 Error:    exit status 3221225473
08:05:43 Stdout:   
08:05:43 Stderr:   
08:05:43 
08:05:43 Failures:
08:05:43 ExitCode was 3221225473 expected 0
08:05:43 Expected no error
```

Also some weird hiccups on janky and experimental. Let's try again...

**Comment by olljanat** [comment]
Derek add label: rebuild/*

**Comment by olljanat** [comment]
RS5 failed again to TestExecWindowsOpenHandles so probably we cannot enable those tests yet.

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by olljanat** [comment]
derek label remove status/failing-ci

**Comment by thaJeztah** [comment]
"validate" stage error can be ignored, it's because a "new" test was added to `integration-cli`;

```
[2020-02-27T20:31:19.178Z] +func (s *DockerSuite) TestExecWindowsOpenHandles(c *testing.T) {
[2020-02-27T20:31:19.178Z] 
[2020-02-27T20:31:19.178Z] integration-cli is deprecated. Please add an API integration test to
[2020-02-27T20:31:19.178Z] ./integration/COMPONENT/. See ./TESTING.md for more details.
```

**Comment by olljanat** [comment]
Still failing on nowadays but now error message starting make sense
```
[2020-09-17T18:26:58.248Z] === FAIL: github.com/docker/docker/integration-cli TestDockerSuite/TestExecWindowsOpenHandles (4.38s)
[2020-09-17T18:26:58.248Z]     --- FAIL: TestDockerSuite/TestExecWindowsOpenHandles (4.38s)
[2020-09-17T18:26:58.248Z]         docker_cli_exec_test.go:593: assertion failed: expression is false: strings.Count(out, "busybox.exe") == 1: busybox process didn't exited
```
probably need try with longer timeout value...

**Pull request closed without merging**
