### PR TITLE
Make devmapper use xfs by default.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Signed-off-by: Anusha Ragunathan anusha@docker.com

### CODE REVIEW

**Comment by tiborvass** [comment]
FYI to make it clear, I think we need a fallback from xfs to ext4. /cc @rhvgoyal

**Comment by calavera** [comment]
we can check if `mkfs.xfs` is installed and fallback to `ext4` if it's not.

**Comment by crosbymichael** [comment]
ya, like @calavera said, we don't need a fallback, just check if its installed and if not use ext

**Comment by tiborvass** [comment]
@crosbymichael that's precisely what a fallback is.

**Comment by tiborvass** [comment]
so yeah i agree with you guys, we're talking about the same thing, i just use different words ;)

**Comment by rhvgoyal** [comment]
@tiborvaas so who is modifying the patch to check for existence of mkfs.xfs? @anusha-ragunathan as you have generated this PR, I am assuming you are going to update your patch?

**Comment by anusha-ragunathan** [comment]
yes, using exec.LookPath of mkfs.xfs.

**Comment by tiborvass** [comment]
This has been superseeded by #17888

**Pull request closed without merging**
