### PR TITLE
New version of notary with pkcs11 client integration

### PR DESCRIPTION
**Pull request by diogomonica**
Vendoring in new notary version with client-side pkcs11 support.

@jfrazelle took care of all of the building bits that were necessary to have this successfully cross-compile. Thank you Jess!

### CODE REVIEW

**Comment by cpuguy83** [comment]
ouch -- 7,239 additions and 1,854 deletions.
Someone's been busy!

**Comment by jfrazelle** [comment]
the commits are separated to make it easier

**Comment by jfrazelle** [comment]
Ping @tianon there a various parts about this that I hate that I hope you have a better solution for but the 2 biggest ones: 1. How to have a dependency in the deb for only experimental, I kinda like how I did it w the rpm but unsure how to do something like that w a control file2. We need a latest clang version for compiling and avoiding [clang errors](http://fuckingclangwarnings.com/) but as you can see their packages don't alias clang-3.8 as /usr/bin/clang 😞Such struggles w this one I hate it all a bit myself

**Comment by cpuguy83** [comment]
```
FAIL: docker_cli_push_test.go:235: DockerTrustSuite.TestTrustedPushWithIncorrectDeprecatedPassphraseForNonRoot
```

**Comment by jfrazelle** [comment]
yes i know I have informed them

**Comment by tianon** [comment]
@jfrazelle does the software actually shell out to `yubico-piv-tool`?  I don't think our dependency on it is quite at the level of `Recommends`, since it's not actually required for _most_ users, but `Suggests` sounds pretty appropriate (https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps for reference).

Until it moves out of experimental, we could do something like we do with putting `apparmor` into `Recommends`; ie, https://github.com/docker/docker/blob/9c6e3396ef7ba44837ffaede0345ab3a105e8116/hack/make/.build-deb/rules#L6-L7, so something like:
```make
    echo 'yubico:Suggests=$(shell [ "$DOCKER_EXPERIMENTAL" ] && echo yubico-piv-tool)' >> debian/docker-engine.substvars
```
there in `override_dh_gencontrol` and `Suggests: ${yubico:Suggests}` over in `debian/control` like https://github.com/docker/docker/blob/9c6e3396ef7ba44837ffaede0345ab3a105e8116/hack/make/.build-deb/control#L15

Is this a tool users of a Yubi are likely to have installed for other Yubi things, or is it something more specific to the way we use the Yubi inside Notary?

**Comment by tianon** [comment]
Also, if the tool isn't installed and a user attempts to use it for something within Docker, does a nice error message bubble up to the level of the client?

**Comment by jfrazelle** [comment]
@diogomonica would know better than I but if they have a yubikey but no lib it will just not use the yubikey and create certs on the host






On Thu, Nov 12, 2015 at 6:40 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:












Also, if the tool isn't installed and a user attempts to use it for something within Docker, does a nice error message bubble up to the level of the client?

**Comment by jfrazelle** [comment]
It dlopens an so file or dylib depending on architecture so I think recommends? Or whatever you think is best






On Thu, Nov 12, 2015 at 6:40 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:












@jfrazelle does the software actually shell out to yubico-piv-tool?  I don't think our dependency on it is quite at the level of Recommends, since it's not actually required for most users, but Suggests sounds pretty appropriate (https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps for reference).



Until it moves out of experimental, we could do something like we do with putting apparmor into Recommends; ie, https://github.com/docker/docker/blob/9c6e3396ef7ba44837ffaede0345ab3a105e8116/hack/make/.build-deb/rules#L6-L7, so something like:

    echo 'yubico:Suggests=$(shell [ "$DOCKER_EXPERIMENTAL" ] && echo yubico-piv-tool)' >> debian/docker-engine.substvars



there in override_dh_gencontrol and Suggests: ${yubico:Suggests} over in debian/control like https://github.com/docker/docker/blob/9c6e3396ef7ba44837ffaede0345ab3a105e8116/hack/make/.build-deb/control#L15



Is this a tool users of a Yubi are likely to have installed for other Yubi things, or is it something more specific to the way we use the Yubi inside Notary?

**Comment by tianon** [comment]
Ok that makes sense, but the tool we're installing isn't the .so, so where
does it fit in?

**Comment by jfrazelle** [comment]
It includes the so






On Thu, Nov 12, 2015 at 7:44 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:










Ok that makes sense, but the tool we're installing isn't the .so, so where

does it fit in?

**Comment by tianon** [comment]
It does?  https://packages.debian.org/sid/amd64/yubico-piv-tool/filelist
:smile:

We probably want that lib package it depends on instead (and in that case
it's just a .so so totally agree that recommends makes more sense).

**Comment by jfrazelle** [comment]
Shit I think it's _their_ deb package that it's in... :( this could be a problem because we were going to have to build these and I wasn't planning on building that one






On Thu, Nov 12, 2015 at 8:04 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:










It does?  https://packages.debian.org/sid/amd64/yubico-piv-tool/filelist

:smile:



We probably want that lib package it depends on instead (and in that case

it's just a .so so totally agree that recommends makes more sense).

**Comment by jfrazelle** [comment]
Because we have to have version 1.1.0






On Thu, Nov 12, 2015 at 8:04 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:










It does?  https://packages.debian.org/sid/amd64/yubico-piv-tool/filelist

:smile:



We probably want that lib package it depends on instead (and in that case

it's just a .so so totally agree that recommends makes more sense).

**Comment by jfrazelle** [comment]
Let me look into the lib one making a patch for it so we can get 1.1.0 on like wheezy and jessie etc






On Thu, Nov 12, 2015 at 8:04 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:










It does?  https://packages.debian.org/sid/amd64/yubico-piv-tool/filelist

:smile:



We probably want that lib package it depends on instead (and in that case

it's just a .so so totally agree that recommends makes more sense).

**Comment by jfrazelle** [comment]
So close to flipping a table this entire PR is a gigantic nightmare






On Thu, Nov 12, 2015 at 8:04 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:










It does?  https://packages.debian.org/sid/amd64/yubico-piv-tool/filelist

:smile:



We probably want that lib package it depends on instead (and in that case

it's just a .so so totally agree that recommends makes more sense).

**Comment by jfrazelle** [comment]
FWIW the rpm installs the so :( so that ones correct






On Thu, Nov 12, 2015 at 8:04 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:










It does?  https://packages.debian.org/sid/amd64/yubico-piv-tool/filelist

:smile:



We probably want that lib package it depends on instead (and in that case

it's just a .so so totally agree that recommends makes more sense).

**Comment by jfrazelle** [comment]
This one is what I was going to package for our repo 

https://github.com/Yubico/yubico-piv-tool-dpkg
With https://github.com/jfrazelle/repo-pkg



On Thu, Nov 12, 2015 at 8:04 AM -0800, "Tianon Gravi" <notifications@github.com> wrote:










It does?  https://packages.debian.org/sid/amd64/yubico-piv-tool/filelist

:smile:



We probably want that lib package it depends on instead (and in that case

it's just a .so so totally agree that recommends makes more sense).

**Comment by diogomonica** [comment]
@tianon @jfrazelle the yubico-piv-tool is actually necessary for anyone that wishes to check the mode on their yubikey/operate on keys (list, delete, etc)/advanced use cases not covered by docker. I would say that Recommend seems appropriate in this case.

This is something that we can change in the future, as more functionality to manage yubikeys is added onto docker and notary, but for now this seems like the only way to have a decent experience with the yubikeys.

Also, the use of pkcs11 is best-effort, if no .so's are found notary silently ignores it.

**Comment by tianon** [comment]
Thanks for confirming, Diogo! :heart:

Sounds good enough for me, assuming @jfrazelle can get happy about version
numbers.  Do you want to add a note about version requirements of this to
PACKAGERS.md with this PR?  Our "Recommends" entry should probably encode
the required version too (ie something like "yubico-piv-tool (>= 1.1.0~)").

**Comment by jfrazelle** [comment]
ok updated w windows fix and also tianons suggestions :) way better than the gross thing i did w install.sh

**Comment by jfrazelle** [comment]
also updated packagers.md

**Comment by cpuguy83** [comment]
Very minimal changes to engine side +1
Reviewed vendored in changes, seems OK (nothing horrendous stands out) +1
Tested trusted push/pull functionality (minus yubikey) +1
Tested trusted push/pull going back to 1.9.0 client +1

Soft LGTM

**Comment by diogomonica** [comment]
@cpuguy83 I have one for you. You can test it in Barcelona :)

**Comment by cyli** [comment]
I've tested the following cases, both with a mac binary that I built on a mac using the same method as homebrew, and with a mac binary that @diogomonica built on linux using `make cross`.

- pull/push with yubikey and `DOCKER_CONTENT_TRUST=1`
- pull/push without yubikey and `DOCKER_CONTENT_TRUST=1`
- push/pull without `DOCKER_CONTENT_TRUST`

Have not tested on Linux.  LGTM as far as macs are concerned :)

**Comment by tonistiigi** [comment]
Tested pushing and key rotation with yubikey and all seemed to work. LGTM (no review of the packaging).

**Comment by diogomonica** [comment]
@tianon would love your explicit LGTM, since this involves building magic.

**Comment by jfrazelle** [comment]
You need mine too ;)

**Comment by diogomonica** [comment]
@jfrazelle would love your explicit LGTM, since this involves building magic.

**Comment by cpuguy83** [comment]
@diogomonica :metal: 

I won't say how long it took me to find that emoji keyword.

**Comment by jfrazelle** [comment]
LGTM

**Comment by tianon** [comment]
I really wish this PR could've been in smaller chunks -- it's very hard to review being so massive. :cry:

(I almost didn't even look at c86517e557c93c8cbb26305704d91409dd207e39 because it didn't sound related to building, but glad I did.)

**Comment by jfrazelle** [comment]
yeah sorry I specifically hated the sym,ink of clang in that one :(

**Comment by jfrazelle** [comment]
there are def aspects of this PR I hate, it blows

**Comment by tianon** [comment]
Ok, latest iteration LGTM

**Comment by icecrime** [comment]
No docs required as far as I can tell.

**Pull request merged**
