### PR TITLE
Migrate rm command to cobra

### PR DESCRIPTION
**Pull request by WeiZhang555**
part of #23211

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@WeiZhang555 need rebase :(

**Comment by WeiZhang555** [comment]
@LK4D4  Rebased :sunglasses:

**Comment by vdemeester** [comment]
LGTM 🐮
but needs a rebase 😝

**Comment by WeiZhang555** [comment]
Rebased, again.

**Comment by cpuguy83** [comment]
```
14:44:15 FAIL: docker_cli_rename_test.go:69: DockerSuite.TestRenameInvalidName
14:44:15 
14:44:15 docker_cli_rename_test.go:78:
14:44:15     c.Assert(out, checker.Contains, "\"docker rename\" requires exactly 2 argument(s).", check.Commentf("%v", err))
14:44:15 ... obtained string = "Error: Neither old nor new names may be empty\n"
14:44:15 ... substring string = "\"docker rename\" requires exactly 2 argument(s)."
14:44:15 ... exit status 1: Error: Neither old nor new names may be empty
14:44:15 
```

**Comment by thaJeztah** [comment]
The `TestRenameInvalidName` should be fixed now, so triggered a rebuild for gccgo and windowsTP5

**Comment by WeiZhang555** [comment]
gccgo still fails, I guess it's not related to this.

**Comment by thaJeztah** [comment]
darn; guess another job was running, but not visible here, and me triggering it cancelled that job :cry:

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
