### PR TITLE
Use stdlib TLS dialer

### PR DESCRIPTION
**Pull request by cpuguy83**
Since go1.8, the stdlib TLS net.Conn implementation implements the
`CloseWrite()` interface.

### CODE REVIEW

**Review by boaz0 — APPROVED** [review]
LGTM :+1:

**Comment by ripcurld** [comment]
Um. On `powerpc` the test failed:

```
19:48:00 --- FAIL: TestTLSCloseWriter (0.00s)
19:48:00 panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized. [recovered]
19:48:00 	panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized.
19:48:00 
19:48:00 goroutine 135 [running]:
19:48:00 testing.tRunner.func1(0xc042337860)
19:48:00 	C:/go/src/testing/testing.go:711 +0x2d9
19:48:00 panic(0x99e2a0, 0xc0424392d0)
19:48:00 	C:/go/src/runtime/panic.go:491 +0x291
19:48:00 net/http/httptest.newLocalListener(0x180000, 0x0)
19:48:00 	C:/go/src/net/http/httptest/server.go:66 +0x205
19:48:00 net/http/httptest.NewUnstartedServer(0xd8ac40, 0xc0424392a0, 0xc042336001)
19:48:00 	C:/go/src/net/http/httptest/server.go:94 +0x2d
19:48:00 net/http/httptest.NewTLSServer(0xd8ac40, 0xc0424392a0, 0xd8448f)
19:48:00 	C:/go/src/net/http/httptest/server.go:161 +0x3c
19:48:00 github.com/docker/docker/client.TestTLSCloseWriter(0xc042337860)
19:48:00 	C:/go/src/github.com/docker/docker/client/hijack_test.go:22 +0xbb
19:48:00 testing.tRunner(0xc042337860, 0xaac8a8)
19:48:00 	C:/go/src/testing/testing.go:746 +0xd7
19:48:00 created by testing.(*T).Run
19:48:00 	C:/go/src/testing/testing.go:789 +0x2e5
```

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Really strange powerpc failed like that now it's working but windows is failing the same way.

**Comment by cpuguy83** [comment]
I'm going to assume it's hitting nodes without ipv6 or something.
I'm going to update the test with a manually configured server I can force it to use ipv4.

**Comment by cpuguy83** [comment]
> hijack_test.go:27: assertion failed: error is not nil: listen tcp4 127.0.0.1:0: socket: The requested service provider could not be loaded or initialized.

😡

**Comment by ripcurld** [comment]
Super odd!

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @johnstep @salah-khan

**Comment by johnstep** [comment]
**TestTLSCloseWriter** fails on Windows when the following line is run first, which can happen even if **TestNegotiateAPIVersionEmpty** starts later because the failing test pauses and continues:
https://github.com/moby/moby/blob/7fb456cfa719c02b41926a29d9bc70b4a1e33abc/client/client_test.go#L197
```
$ go test .\client -v -run 'TLS'
=== RUN   TestTLSCloseWriter
=== PAUSE TestTLSCloseWriter
=== CONT  TestTLSCloseWriter
--- PASS: TestTLSCloseWriter (0.01s)
PASS
ok      github.com/docker/docker/client (cached)
$ go test .\client -v -run 'TLS|VersionEmpty'
=== RUN   TestNegotiateAPIVersionEmpty
--- PASS: TestNegotiateAPIVersionEmpty (0.00s)
=== RUN   TestTLSCloseWriter
=== PAUSE TestTLSCloseWriter
=== CONT  TestTLSCloseWriter
--- FAIL: TestTLSCloseWriter (2.17s)
        hijack_test.go:64: assertion failed: error is not nil: listen tcp4 127.0.0.1:9999: socket: The requested service provider could not be loaded or initialized.
FAIL
FAIL    github.com/docker/docker/client 2.236s
```
It also passes when all tests run except for TestNegotiateAPIVersionEmpty.
Perhaps TestNegotiateAPIVersionEmpty needs to clean up after itself.

**Comment by dnephin** [comment]
Yes, it looks like there is a problem with that line. It should be deferring the return value of `PatchAll`. There's a missing `()` at the end of the line. Right now it's doing nothing for the test, then setting the environment after the test is done.

Does `TestTLSCloseWriter` depend on the value of `DOCKER_API_VERSION` ? I guess it should patch as well if an unexpected value can break the test.

**Comment by johnstep** [comment]
Thanks, that makes sense.

`TestTLSCloseWriter` does not depend on the value of `DOCKER_API_VERSION` but does require that the standard `SystemRoot` environment variables is set. On Windows, clearing the entire environment is almost always a bad idea as program code and system libraries use some of them.

**Comment by johnstep** [comment]
This should pass on Windows once #37236 is merged.

**Pull request merged**
