### PR TITLE
Bump swarmkit to bd69f6e8e301645afd344913fa1ede53a0a111fb

### PR DESCRIPTION
**Pull request by anshulpundir**
Summary of changes https://github.com/docker/swarmkit/compare/33d06bf5189881b4d1e371b5571f4d3acf832816...bd69f6e8e301645afd344913fa1ede53a0a111fb

PRs:
https://github.com/docker/swarmkit/pull/2614
https://github.com/docker/swarmkit/pull/2562

### CODE REVIEW

**Comment by anshulpundir** [comment]
@thaJeztah

**Comment by thaJeztah** [comment]
sgtm, but a bit worried about the huge amount of logging being added (as it's already quite noisy in debug-mode).

/cc @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
Agree, most (or all) of these new debug messages look excessive.
It's already super noisy from other recent changes.

**Comment by anshulpundir** [comment]
Not sure I understand the concern. These are logs for failure scenarios. Why do you think is excessive ? @cpuguy83 @thaJeztah

**Review by nishanttotla — APPROVED** [review]

**Review by cyli — APPROVED** [review]

**Comment by anshulpundir** [comment]
As I explained on slack, the logs are in debug mode, most of these are rare, and the ones that aren’t e.g. “task was marked pending” is a task state transition, and we we absolutely want to log that. we already do it in the dispatcher for states > running. these are also addressing our lack of proper logs in swarmkit. 

Can we please get this in soon ? @thaJeztah @cpuguy83

**Review by cpuguy83 — APPROVED** [review]
Thanks for confirming.
Tested this out and it does indeed seem fine.

LGTM

**Pull request merged**
