### PR TITLE
Add health start interval support to swarm mode

### LINKED ISSUE #45897: Tracking issue for health start interval
### Description

The API was updated in https://github.com/moby/moby/pull/40894 but other changes are required:

- [x]  https://github.com/moby/swarmkit/pull/3142
- [x]  https://github.com/docker/cli/pull/4405
- [x] https://github.com/moby/buildkit/pull/3998
- [x]  https://github.com/compose-spec/compose-spec/pull/383
- [ ]  https://github.com/moby/moby/pull/45965
- [ ]  https://github.com/compose-spec/compose-go/pull/437
- [ ] Update docker/compose CLI after compose-go is merged
- [ ]  Update default start interval to be non-zero?

### PR DESCRIPTION
**Pull request by cpuguy83**
Related: #45897

### CODE REVIEW

**Review by corhere — APPROVED** [review]

**Comment by thaJeztah** [comment]
quick blurb; need to check if the API is affected and swagger + version-history needs an update

**Review by corhere — APPROVED** [review]

**Comment by cpuguy83** [comment]
@thaJeztah Yes API is affected but it was already updated in the original PR (b/c swarm is using the same struct in the swagger and in the actual API implementation).
I did need to update the swarm router to set the value to zero if the api version is older.

**Review by neersighted — APPROVED** [review]
Could you add the SwarmKit version to the commit message? e.g. make the first line `vendor: github.com/moby/swarmkit/v2 v2.0.0-20230713153928-bc71908479e5`?

Otherwise, LGTM

**Comment by cpuguy83** [comment]
Updated the commit message.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
