### PR TITLE
Cherry picks 1.12.2

### PR DESCRIPTION
**Pull request by vieux**
- [#26049](https://github.com/docker/docker/pull/26049)
  - a020ec4c8b476a814eb137e216fe9d723524fc3b Check for non-nil container after match
- [#24335](https://github.com/docker/docker/pull/24335)
  - d9e12cba5a9a2291f56eb3921b06ac1b5f85dfc7 ppc64le: remove go SHA check
- [#25869](https://github.com/docker/docker/pull/25869)
  - 11eda60848e476c3a1d84a035642edba74e94c8a debian sysvinitscript one missed DOCKER->DOCKERD change 
- [#26260](https://github.com/docker/docker/pull/26260)
  - 7b5c3d935a7a99b282f0f859101c887894a0b00e Clarify usage of --force when used on a swarm manager
- [#26313](https://github.com/docker/docker/pull/26313)
  - b9e46235fadc6b390e2c04c44b6a865e4ea97cb8 Fix incorrect help output in `docker network ls`
- [#26737](https://github.com/docker/docker/pull/26737)
  - 26b6b47420be3e0d932a5e128ac2304b9e93efc2 Modify the print and comment of setting host configuration options when the container starts 
- [#26607](https://github.com/docker/docker/pull/26607)
  - 5cfbdceafe87df8bab85c0561a1483d3191eb775 Vendoring boltdb @fff57c100
- [#26282](https://github.com/docker/docker/pull/26282)
  - 341489f1500873a6aa51998f49c1da7f7fd8eb5a `docker node inspect <node> --pretty` needs an extra newline at the end
- [#26669](https://github.com/docker/docker/pull/26669)
  - f528690674712b680caf2712092c7e2f8f236491 re-vendor syslog package
- [#26536](https://github.com/docker/docker/pull/26536)
  - 0e539fec331cb9dbc4ef784b55516570b11affe2 Add retry logic during aufs unmount
- [#25578](https://github.com/docker/docker/pull/25578)
  - 0fd4bbda2dfb9a1bfc6781f2a3dacedc62c7c11b Force input stream ANSI emulation for ConEmu
- [#26208](https://github.com/docker/docker/pull/26208)
  - e95b6b51daed868094c7b66113381d5088e831b4 Fix exec form of HEALTHCHECK CMD
- [#26740](https://github.com/docker/docker/pull/26740)
  - 87124b9d62bc71f7632126cf7f8d5eb805c4a7f1 Update fluent-logger-golang to v1.2.0
- [#25965](https://github.com/docker/docker/pull/25965)
  - 9cb8fb6ea03fcd78010ce7dd33585d96cd73e38c Fix AuthZ plugins headers change issue
- [#24740](https://github.com/docker/docker/pull/24740)
  - 5e505d101f0201a4d045510d0a9b0c66697dedfe devmapper: prevent libdevmapper from deleting /dev/mapper/docker-xxx symbolic links in RemoveDeviceDeferred
- [#26211](https://github.com/docker/docker/pull/26211)
  - b1d2b088533187954d3b98ed5951ec2dbbb422e9 cluster: Do not autodetect advertise address on join

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by tiborvass** [comment]
@vieux please make sure the cherrypicks are done with `-x` (and to prevent bad surprises sometimes `-s` is also welcome). Hopefully it's not too much to ask :S

**Comment by vieux** [comment]
@tiborvass repushed with -x and -s

@docker/core-engine-maintainers this is ready for review.

**Comment by cpuguy83** [comment]
```
07:03:49 FAIL: docker_cli_run_unix_test.go:1121: DockerSuite.TestRunSeccompDefaultProfileNS
07:03:49 
07:03:49 docker_cli_run_unix_test.go:1180:
07:03:49     c.Assert(err, checker.IsNil)
07:03:49 ... value *errors.errorString = &errors.errorString{s:"goroutine 4: expected No such file or directory, got: /go/src/github.com/docker/docker/bundles/1.12.1/test-integration-cli/../binary-client/docker: Error response from daemon: failed to create endpoint small_dijkstra on network bridge: failed to save bridge endpoint c887537 to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout.\n"} ("goroutine 4: expected No such file or directory, got: /go/src/github.com/docker/docker/bundles/1.12.1/test-integration-cli/../binary-client/docker: Error response from daemon: failed to create endpoint small_dijkstra on network bridge: failed to save bridge endpoint c887537 to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout.\n")
```

Looks like we hit a libnetwork bug.
ping @aboch

**Comment by aaronlehmann** [comment]
It looks like this is missing https://github.com/docker/docker/pull/26211. That's a pretty important one.

How did that fall through? Do we not cherry-pick all the PRs on the 1.12.2 milestone?

**Comment by icecrime** [comment]
@aaronlehmann I let @vieux examine this particular PR, but just to clarify: we don't directly cherry-pick all PR from the milestone (as described [here](https://github.com/docker/docker/blob/master/project/PATCH-RELEASES.md#deciding-on-the-content-of-a-patch-release)). It can be misleading, but the milestone is the pool of changes to evaluate, and then decision is taken for each based on priority, risk, and value to the user.

**Comment by vieux** [comment]
@aaronlehmann I look mostly at PRs with the `process/cherry-pick` label. After I look at the others in the milestone, I must have missed it. add it now

**Comment by vieux** [comment]
for some reason github shows [build 24374](https://jenkins.dockerproject.org/job/Docker-PRs-experimental/24374/console)(aborted) for experimental, but it should show [build 24375](https://jenkins.dockerproject.org/job/Docker-PRs-experimental/24375/console)(running)

**Review by mlaventure — APPROVED** [review]
LGTM

**Comment by vieux** [comment]
the experimental failure is a know flacky test (fixed in master) https://github.com/docker/docker/pull/25808

@LK4D4 @mlaventure @crosbymichael @anusha-ragunathan PTAL

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
