### PR TITLE
Setting the mirror with mirror address.

### PR DESCRIPTION
**Pull request by Hyzhou**
**- What I did**

We can use the mirror address to setting the mirror. Only comply with the rules of url.
Because some user initialize the machine in Aliyun VPC environment And he can use the intranet mirror `http://mirrors.aliyuncs.com/docker-engine`.
By the way, if we add the option AliyunMirror or AliyunVPCMirror. More and more option will be added. 

```
curl -sSL https://get.docker.com/ | sh -s -- --mirror http://mirrors.aliyun.com/docker-engine
curl -sSL https://get.docker.com/ | sh -s -- --mirror http://mirrors.aliyuncs.com/docker-engine
curl -sSL https://get.docker.com/ | sh -s -- --mirror https://mirror.azure.cn/docker-engine
```

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: hyzhou.zhy <hyzhou.zhy@alibaba-inc.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'm not sure we should change this to allow any arbitrary URL to be set; also this change would break https://github.com/Azure/azure-docker-extension/blob/0539b864cc6fd64ba1236a60443c006019eb7f10/op-enable.go#L49-L51

/cc @friism @dmp42

**Comment by ushuz** [comment]
Beside what @thaJeztah mentioned, I guess we shouldn't assume all mirrors are ending with `/apt` and `/yum`. Prefer #28858.

**Comment by tianon** [comment]
Agreed, I'm more partial to our script supporting an explicit set of "official" mirrors than simply allowing arbitrary mirrors. :+1:

**Comment by thaJeztah** [comment]
Let's close this PR in favor of https://github.com/docker/docker/issues/28858. We still have to discuss if we're ok with adding these mirrors, but we can do so on that PR

perhaps you can join the discussion there @Hyzhou?

**Pull request closed without merging**
