### PR TITLE
Docs cleanup - Contributor Guide

### PR DESCRIPTION
**Pull request by kostickm**
Minor updates to the Contributor Guide:

find-an-issue.md:
Find and claim an issue -> Sync your fork and create a new branch -> Step 4 - Added missing `push)`

work-issue.md:
Work on your issue -> Pull and rebase frequently -> Step 2 - `branch` should be `checkout`

Signed-off-by: Megan Kostick mkostick@us.ibm.com

### CODE REVIEW

**Comment by moxiegirl** [comment]
Nice catches! Thank you.  LGTM

**Comment by moxiegirl** [comment]
ping @jamtur01 @fredlf @SvenDowideit

**Comment by fredlf** [comment]
I realize this is a wholly uncontroversial (and useful!) PR, but why was it merged with only one LGTM?

**Comment by moxiegirl** [comment]
For the reasons you stated.

On Thu, Apr 9, 2015 at 5:57 PM, Fred Lifton <notifications@github.com>
wrote:

> I realize this is a wholly uncontroversial (and useful!) PR, but why was
> it merged with only one LGTM?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/12252#issuecomment-91391687>.
>



-- 
Mary

**Pull request merged**
