### PR TITLE
Use name instead of container in Commit

### PR DESCRIPTION
**Pull request by LK4D4**
It will make daemon interface separation easier later.

### CODE REVIEW

**Comment by MHBauer** [comment]
Not sure if related or not https://github.com/docker/docker/pull/17662#discussion_r43807719
Do you think doing all of the methods that take a container or just this one?

I have this exact same change in a repo somewhere as well, so I agree with it, unless @calavera has an objection.

**Comment by LK4D4** [comment]
@MHBauer Yeah, had plans for all, but decided to keep changes small, because they sort of different for different methods.

**Comment by MHBauer** [comment]
@LK4D4 Sounds good. If thereis something I can do to help, or a plan that I can be a part of, I am here to help. This particular situation is something I have had focus on.

**Comment by LK4D4** [comment]
@MHBauer yeah, you can start to post your work already, don't wait until you patch will be too big to proper review.

**Comment by calavera** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
