### PR TITLE
Revendor go-winio

### PR DESCRIPTION
**Pull request by kevpar**
This is needed to provide fixes for ETW on Windows on ARM. The updated ETW package will
no-op on ARM, rather than crashing. Further changes are needed to Go itself to
allow ETW on ARM to work properly.

Signed-off-by: Kevin Parsons <kevpar@microsoft.com>

Previously the ETW logging would cause docker to crash on Windows on ARM. Most of the interesting description of the problem is included in the commit messages to go-winio. I can include that here if desired.

Cute animal: Cute penguin

### CODE REVIEW

**Comment by kevpar** [comment]
@jhowardmsft FYI

**Comment by thaJeztah** [comment]
This will conflict with https://github.com/moby/moby/pull/39100, but I can rebase that one if this is merged

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
ping @jhowardmsft PTAL

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
