### PR TITLE
bump libnetwork and dependencies to 92d1fbe1eb0883cf11d283cea8e658275146411d

### LINKED ISSUE #2431: parseIP Error ip=[172 17 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
I am using libnetwork/ipvs to fetch the destinations for each ipvs service.

following is the code statement.

`		destinations, err := c.ipvsHandle.GetDestinations(service)
`

After latest commit I am getting error while fetching destinations of service.

parseIP Error ip=[172 17 0 2 0 0 0 0 0 0 0 0 0 0 0 0]

Please help me on this. I am not able to fetch the destinations of each ipvs service.

### PR DESCRIPTION
**Pull request by thaJeztah**
this update is needed for https://github.com/docker/engine/pull/330 (which currently has the regression introduced by docker/libnetwork#241)

### bump libnetwork to 92d1fbe1eb0883cf11d283cea8e658275146411d

full diff: https://github.com/docker/libnetwork/compare/09cdcc8c0eab3946c2d70e8f6225b05baf1e90d1...92d1fbe1eb0883cf11d283cea8e658275146411d

relevant changes included (omitting some changes that were added _and_ reverted in this bump):

- docker/libnetwork#2433 Fix parseIP error when parseIP before get AddressFamily
  - fixes docker/libnetwork#2431 parseIP Error ip=[172 17 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
  - https://github.com/docker/libnetwork/issues/2289
  - this was a regression introduced in docker/libnetwork#2416 Fix hardcoded AF_INET for IPv6 address handling
- docker/libnetwork#2440 Bump hashicorp go-sockaddr v1.0.2, go-multierror v1.0.0

### bump hashicorp/go-multierror v1.0.0, add errwrap v1.0.0

full diff: https://github.com/hashicorp/go-multierror/compare/fcdddc395df1ddf4247c69bd436e84cfa0733f7e...v1.0.0

### bump hashicorp/go-sockaddr v1.0.2

full diff: https://github.com/hashicorp/go-sockaddr/compare/6d291a969b86c4b633730bfc6b8b9d64c3aafed9...v1.0.2

Relevant changes:
- hashicorp/go-sockaddr#25 Add android os
- hashicorp/go-sockaddr#28 Add go.mod

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @arkodg @selansen ptal

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Windows RS1 failure looks like flaky (opened a ticket for that); https://github.com/moby/moby/issues/39857

https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39855/runs/1/nodes/39/log/?start=0

```
[2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=info msg="Trying to get region from EC2 Metadata"
[2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=info msg="Log stream already exists" errorCode=ResourceAlreadyExistsException logGroupName= logStreamName= message= origError="<nil>"
[2019-09-03T10:15:19.914Z] --- FAIL: TestLogBlocking (0.02s)
[2019-09-03T10:15:19.914Z]     cloudwatchlogs_test.go:313: Expected to be able to read from stream.messages but was unable to
[2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=error msg=Error
[2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=InvalidSequenceTokenException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
[2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
[2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=info msg="Data already accepted, ignoring error" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token"
[2019-09-03T10:15:19.914Z] FAIL
```

**Comment by selansen** [comment]
> Windows RS1 failure looks like flaky (opened a ticket for that); #39857
> 
> https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39855/runs/1/nodes/39/log/?start=0
> 
> ```
> [2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=info msg="Trying to get region from EC2 Metadata"
> [2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=info msg="Log stream already exists" errorCode=ResourceAlreadyExistsException logGroupName= logStreamName= message= origError="<nil>"
> [2019-09-03T10:15:19.914Z] --- FAIL: TestLogBlocking (0.02s)
> [2019-09-03T10:15:19.914Z]     cloudwatchlogs_test.go:313: Expected to be able to read from stream.messages but was unable to
> [2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=error msg=Error
> [2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=InvalidSequenceTokenException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
> [2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=error msg="Failed to put log events" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token" origError="<nil>"
> [2019-09-03T10:15:19.914Z] time="2019-09-03T10:15:19Z" level=info msg="Data already accepted, ignoring error" errorCode=DataAlreadyAcceptedException logGroupName=groupName logStreamName=streamName message="use token token"
> [2019-09-03T10:15:19.914Z] FAIL
> ```

Thanks for pointing it out. Looks like this is the only error.

**Review by selansen — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Thanks for reviewing; bringing this one in to fix that regression

**Pull request merged**
