### PR TITLE
always allow client to override builder version regardless the server setup

### PR DESCRIPTION
**Pull request by AntaresS**
**- What I did**
- Always horonor docker cli using `DOCKER_BUILDKIT` env var to choose which buildcer to use regardless server settings.
  - removed server side prevention when the default builder set to `v1`.

Signed-off-by: Anda Xu <anda.xu@docker.com>

### CODE REVIEW

**Comment by AntaresS** [comment]
After making this change, in `/etc/docker/daemon.json` the UX will become a bit misleading on `"features": {"buildkit": false}`. Before this change was made,  what the option indicates is clear - daemon prevents using `buildkit`. However, now we are always allowing cli to override it. Maybe we should consider change the config option to something like `"builder-version":1` to imply the default builder version?

**Comment by AntaresS** [comment]
cc @tiborvass @tonistiigi

**Comment by tiborvass** [comment]
@AntaresS After talking with @tonistiigi we would like to make sure the BuilderVersion in the Ping struct is also a tri-state. The following should work

```diff
--- a/api/types/types.go
+++ b/api/types/types.go
@@ -105,7 +105,7 @@ type Ping struct {
        APIVersion     string
        OSType         string
        Experimental   bool
-       BuilderVersion BuilderVersion
+       BuilderVersion *BuilderVersion `json:",omitempty"`
 }

--- a/client/ping.go
+++ b/client/ping.go
@@ -27,8 +27,8 @@ func (cli *Client) Ping(ctx context.Context) (types.Ping, error) {
                        ping.Experimental = true
                }
                ping.OSType = serverResp.header.Get("OSType")
-               if bv := serverResp.header.Get("Builder-Version"); bv != "" {
-                       ping.BuilderVersion = types.BuilderVersion(bv)
+               if bv := types.BuilderVersion(serverResp.header.Get("Builder-Version")); bv != "" {
+                       ping.BuilderVersion = &bv
                }
```

**Review by tiborvass — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]

**Comment by AntaresS** [comment]
Putting a reminder here, we'll need to update the `dockerd` docs in cli as well according to the changes.
cc @andrewhsu

**Pull request merged**
