### PR TITLE
Skip TestPullVerified because hello-world image cannot be verified

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass tibor@docker.com

Ping @dmp42 @dmcgowan @jfrazelle @icecrime @crosbymichael @duglin @estesp

### CODE REVIEW

**Comment by jfrazelle** [comment]
awesome thanks LGTM

**Comment by ahmetalpbalkan** [comment]
Why not just pull some other small image temporarily?

**Comment by jfrazelle** [comment]
I can't think of another tiny one and I don't know what official images
have been pushed to v2 :/

**Comment by duglin** [comment]
LGTM once janky is happy

**Pull request merged**
