### PR TITLE
awslogs: fix linting issues, and small refactoring

### PR DESCRIPTION
**Pull request by thaJeztah**
splitting this off from https://github.com/moby/moby/pull/39668

See individual commits for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
@samuelkarp @vdemeester ptal

**Review by samuelkarp — APPROVED** [review]
Thanks!

**Comment by thaJeztah** [comment]
Thanks for reviewing 🤗

**Comment by thaJeztah** [comment]
rebased to get rid of old CI results

ping @kolyshkin PTAL

**Review by tiborvass — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM

**Pull request merged**
