### PR TITLE
Fix compilation on Go 1.3.3

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by jfrazelle** [comment]
you can see it compilesd on 1.3.3 here https://jenkins.dockerproject.com/job/Docker-Go1.3.3/label=ubuntu-btrfs/120/console

**Comment by tianon** [comment]
:+1:

Looks like we should add a Go 1.3 builder to our PRs? :angel:

**Comment by jfrazelle** [comment]
well we have the checks on master unsure just how muchhhhhh infra we can
build out for the amount of prs we get a day

**Comment by tiborvass** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
