### PR TITLE
Bump api version to 1.21.

### PR DESCRIPTION
**Pull request by calavera**
In preparation for Docker 1.8.

/cc @icecrime

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by LK4D4** [comment]
`docs/reference/api/docker_remote_api.md` also need to be changed

**Comment by thaJeztah** [comment]
@calavera Could you check if there are already changes that went into the v1.20 docs that were meant for 1.8 (so the v1.21 API), and need to be reverted there? (thinking of the change for "Mounts", possibly others?

**Comment by calavera** [comment]
@thaJeztah v1.21 is for docker 1.9. Or I might be misunderstanding it.

**Comment by calavera** [comment]
@LK4D4 fixed.

**Comment by thaJeztah** [comment]
@calavera >facepalm< yup! 😇

**Pull request merged**
