### PR TITLE
Clean up the constants in 'libcontainerd' that are no longer in use

### PR DESCRIPTION
**Pull request by miaoyq**
**\- What I did**

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like it needs a gofmt;

```
04:56:48 ---> Making bundle: validate-gofmt (in bundles/1.13.0-dev/validate-gofmt)
04:56:48 These files are not properly gofmt'd:
04:56:48  - libcontainerd/types.go
04:56:48 
04:56:48 Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by miaoyq** [comment]
Thanks! @thaJeztah 
Updated!

**Comment by jhowardmsft** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
lol @cpuguy83 beat me to it

**Pull request merged**
