### PR TITLE
Set default credentials store in Windows.

### PR DESCRIPTION
**Pull request by calavera**
Use the Windows Credentials Manager when the helper
is installed in the path.

This is a follow up of #20107 because I forgot to set it
in that original PR.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hey! Was just about to comment, when you updated, haha

**Comment by jhowardmsft** [comment]
Picture is not cute enough. LGTM otherwise ;)

**Comment by vdemeester** [comment]
LGTM 🐼

**Comment by thaJeztah** [comment]
> Picture is not cute enough

@jhowardmsft there you go;

image

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Pull request merged**
