### PR TITLE
Forward-port patches of 20.10.20 to master

### PR DESCRIPTION
**Pull request by thaJeztah**
cherry-pick of https://github.com/moby/moby/compare/v20.10.19...v20.10.20 (except for BuildKit, which is done in https://github.com/moby/moby/pull/44320)

- conflicts in the first commit (in test files) due to `io/ioutil` -> `io` changes
- conflicts in the last commit, due to https://github.com/moby/moby/commit/9adad264d2bf17bee8ec7b8a29d7112b3f503771 (https://github.com/moby/moby/pull/43675), which is not in 20.10 <-- please double check the last commit 👍

### CODE REVIEW

**Comment by thaJeztah** [comment]
@corhere @tonistiigi @cpuguy83

**Comment by thaJeztah** [comment]
Okay; need to look into this; perhaps alternative patches (directly for master) are needed;

```
# github.com/docker/docker/integration/image [github.com/docker/docker/integration/image.test]
integration/image/pull_test.go:123:36: undefined: registry.WithStdout
integration/image/pull_test.go:123:68: undefined: registry.WithStderr
make: *** [Makefile:238: test-integration] Error 2
Error: Process completed with exit code 2.
```

**Comment by corhere** [comment]
Why not merge the original commits directly? It strikes me as odd to round-trip from master to 20.10 and back to master.

**Comment by thaJeztah** [comment]
Ah; easy fix; need to revert https://github.com/moby/moby/commit/1f21c4dd0512e899ecf4077a927d99debac28f6d, which removed those utilities

**Comment by thaJeztah** [comment]
> Why not merge the original commits directly? It strikes me as odd to round-trip from master to 20.10 and back to master.

oh! good one; there was a branch for master as well? 🤦 

yes, that'd work; could you open a PR for that?

**Comment by thaJeztah** [comment]
For Brian's changes, I'd have to check; perhaps take my branch from that repo (with the fixes).

**Comment by thaJeztah** [comment]
Closing in favor of:

- https://github.com/moby/moby/pull/44324
- https://github.com/moby/moby/pull/44327
- https://github.com/moby/moby/pull/44320

**Pull request closed without merging**
