### PR TITLE
1.13.0-rc3 cherry-picks

### PR DESCRIPTION
**Pull request by vieux**
- [#28743](https://github.com/docker/docker/pull/28743)
  - bb96e18b19f78af38a9fe088b2873988ba9a47b4 Move `docker stack` docs out of experimental
- [#28749](https://github.com/docker/docker/pull/28749)
  - 30b8712e93819b2da77e67e16f9c7b81fd3a0cb4 daemon: remove not needed unmarshal
- [#28753](https://github.com/docker/docker/pull/28753)
  - eb5fe064cfb8475e9f6fb9beac98ad6ce63be2a3 Fixes some integration-cli on userns
- [#28758](https://github.com/docker/docker/pull/28758)
  - 43297dd6f81d85d1ac3dc49d68684404be0f2d8e Update plugin enable cli reference documentation
- [#28765](https://github.com/docker/docker/pull/28765)
  - d28eaa11710f2aa0429ccdc3dc7fd83c67f2775c Update docker info cli reference documentation
- [#28514](https://github.com/docker/docker/pull/28514)
  - 286ab6d69bb999f5fcbdfdcac50bb8d65bb50c56 Refix COPY file . after WORKDIR (now always created)
- [#28602](https://github.com/docker/docker/pull/28602)
  - 16c9cdad6fd7c78600e795cad03ec8b34cba0371 28600: Docs: network connect for container in Created/Stopped state 
- [#28625](https://github.com/docker/docker/pull/28625)
  - ecb707cb0f0ebb50fb1b90f4ab3c4ae611925ed2 Add bash completion for plugin API
- [#28657](https://github.com/docker/docker/pull/28657)
  - c22821014a8d951d7028f9d2888072c4d9f7c593 fix doc about service create in docker_remote_api_v1.24.md
- [#28667](https://github.com/docker/docker/pull/28667)
  - b2049a84dee35308ca8c4837ccb9359f57808f45 Windows: Case insensitive env vars
- [#28675](https://github.com/docker/docker/pull/28675)
  - c72daf953aaa8c7c8cbe60a103700d3b1d56c50d Better error message on stack deploy when not a swarm manager
- [#28757](https://github.com/docker/docker/pull/28757)
  - 2ca39d27a689c709e3306df5a4eb255c81276574 Fix broken markdown in CHANGELOG.md
- [#28760](https://github.com/docker/docker/pull/28760)
  - d87c91e39ff0d3defb5b98fdc9275c8c0bfc987e Update Secret Command help (carry #28576)
- [#28771](https://github.com/docker/docker/pull/28771)
  - 1c65cb6657f1288d6a7e93e0015bba68e6d374cd Allow hostname to be updated on service
- [#28772](https://github.com/docker/docker/pull/28772)
  - c90ec0517544e7d054d79f71f4d24d9ebbad7408 Restrict checkpoint name to prevent directory traversal
- [#28773](https://github.com/docker/docker/pull/28773)
  - bb7601a3ffdc78bbe7efe7e77a196e09cf3607c7 exit with status 1 if help is called on an invalid command
- [#28780](https://github.com/docker/docker/pull/28780)
  - f70470b71e519012e91137a2512f40d5bb8d18af support src in --secret
- [#28794](https://github.com/docker/docker/pull/28794)
  - 2510f254eea58788c1a98987db35294beb839bb4 Update docs of `docker network ls --filter`
- [#28802](https://github.com/docker/docker/pull/28802)
  - 9e414bfa6b26bf919fc7ffbf0cf87814043b328b Add options for docker plugin enable and fix some typos
- [#28803](https://github.com/docker/docker/pull/28803)
  - 163db04452fe399fec940a926733915e7cf90062 check-config check for LEGACY_VSYSCALL_* options
- [#28804](https://github.com/docker/docker/pull/28804)
  - 70acb89fa2e889393d33664bc780cf116795f3e4 Improve error when connecting service to network
- [#28815](https://github.com/docker/docker/pull/28815)
  - f1dd721b6978f1c24bb2761b88c83d9e385bd781 Add a short flag for docker stack deploy 
- [#28818](https://github.com/docker/docker/pull/28818)
  - 18724726c24728c0dd2bdb4981254a100568185f Fix some typos
- [#28822](https://github.com/docker/docker/pull/28822)
  - c394034f5978862b75770a036364f806bbcd8920 Modify repoName to PLUGIN for docker plugin create
- [#28824](https://github.com/docker/docker/pull/28824)
  - fc7c235f84f76d5d64f25bc802486ecbe87f8b95 modify invalid url in plugins_network.md
- [#28833](https://github.com/docker/docker/pull/28833)
  - 9d98d6d8cb23a5078e2d81014620fdd390c32abf Add bash completion for `docker service update --hostname`
- [#28841](https://github.com/docker/docker/pull/28841)
  - cd5c8e9c2dc181cd624bdb10947a19197215d730 Fix grammar on error message
- [#28856](https://github.com/docker/docker/pull/28856)
  - b23fbc3fbd133c9463c73a66e09f1dfbff902ffb Add zsh completion for 'docker service update --hostname'
- [#28857](https://github.com/docker/docker/pull/28857)
  - 08ff4f427e5ab6b597348661e602cd2a335e0aa0 Fix description and link of 'docker run [-a]'
- [#28865](https://github.com/docker/docker/pull/28865)
  - 8260366dd2fae9ef15a8da52451757ef32e88aca Add aliases and options to `docker stack ls` docs
- [#28866](https://github.com/docker/docker/pull/28866)
  - f3b7f40aafb009a3779e94ec9b2a8de1e0ce96bc Add bash completion for `docker service {create,update}` host options
- [#28868](https://github.com/docker/docker/pull/28868)
  - 3abee1bf8aad5e24df635d70bceb39c69a1c2407 4a3207de5b96a875b97e02dde83c75b1beabf184 fix description of 'docker swarm init'
- [#28882](https://github.com/docker/docker/pull/28882)
  - 3f98871a19eafbfa8ec7da3640d7006d0ca458ef Remove docker stack config commandline reference doc
- [#28886](https://github.com/docker/docker/pull/28886)
  - a1f55dca21c4ee9f38ed2aeba535cdba3bb2f790 Fix some redirect loops and problems
- [#28890](https://github.com/docker/docker/pull/28890)
  - 2333657e1b20d6a482627b78c9333cdf34397ff5 Fix copypaste error 'is-automated'

- [#28717](https://github.com/docker/docker/pull/28717)
  - 662d456928e47162a3af5931356cb05b6a3f9918 Fix issue caused by duplicate `docker plugin create` with same names 
- [#28721](https://github.com/docker/docker/pull/28721)
  - abcb699ad175859ee192388c001f55df5f88e8cd Fix network attachable option
- [#28734](https://github.com/docker/docker/pull/28734)
  - 798c00a7eea731f7f70e7595c403db399d34924c Added and example of using --format with docker images
- [#28776](https://github.com/docker/docker/pull/28776)
  - dfeaf7a959cf619f5460c88e7bc1fe5ce40d50a7 Align output of docker version again
- [#28778](https://github.com/docker/docker/pull/28778)
  - b9e65f40cfce3eb1907ad9d8a358c6ae1ad64175 Windows: Note about volumes in run
- [#28819](https://github.com/docker/docker/pull/28819)
  - 4e970c1e5a2b16f9408f530037e65595810cc5d7 Modify the link about config.json for docker plugin create
- [#28893](https://github.com/docker/docker/pull/28893)
  - 9e4234261c3e4d13f98218a97d7cc6644723e310 On plugin pull errors, delete created dirs. 
- [#28897](https://github.com/docker/docker/pull/28897)
  - 890a98ceed982454515f5b089d9772fc1e4eb6e0 Fix issue with plugin exit.
- [#28898](https://github.com/docker/docker/pull/28898)
  - c6e31454ba2f053bc6831651663cf538d142afaa Fixes ImageList to be retro-compatible with older API
- [#28901](https://github.com/docker/docker/pull/28901)
  - d73f73b3654add36096def93f5736cc6a6686226 update plugin example
- [#28904](https://github.com/docker/docker/pull/28904)
  - 4013a7c6d897051bb79982230f31279ee0c9a026 Use namespace label on stack volumes
- [#28905](https://github.com/docker/docker/pull/28905)
  - eeac8719466dbc42de7a9919d4f549863944aa19 Reject unspecified advertise addr on swarm init
- [#28906](https://github.com/docker/docker/pull/28906)
  - 2178c840ba420d7d207aedae292e2e70d7198265 Document publishing a UDP port
- [#28909](https://github.com/docker/docker/pull/28909)
  - 1b97bb416b8e2d4cd77544a1d714026b25d73c2f WORKDIR set cmd
- [#28914](https://github.com/docker/docker/pull/28914)
  - 9dba9e3248f8476d15242ce3ec0bf6d6d50c1a76 cluster: Refuse swarm spec not named "default"
- [#28919](https://github.com/docker/docker/pull/28919)
  - 5b93e77138f19d30245a3e0f9f8f834aa67458ec change secret remove logic in cli
- [#28928](https://github.com/docker/docker/pull/28928)
  - 71f1205269494430116e7a564ee76bfa0bfccc63 Fix some format errors

### CODE REVIEW

**Comment by vieux** [comment]
ping @docker/core-engine-maintainers

**Review by mdlinville — APPROVED** [review]
Docs LGTM

**Comment by mlaventure** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
