### PR TITLE
[AUTOMATED] libnetwork Vendoring

### LINKED ISSUE #397: the --dns option is not working with windows container
### Expected behavior
calling docker run with the --dns <some dns server> should use that server as the sole, or at least as the first dns server in the list
### Actual behavior
The default gateway is listed as the first dns server in the list on my vm ware hosted windows 10 instance. On a windows 2016 instance, the hosts dns server is listed first. 
### Information
Windows 2016 version:
PS C:\Windows\system32> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Windows 10 version:
PS C:\Windows\system32> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
 
### Steps to reproduce the behavior

  1. docker run --it --rm --dns 8.8.8.8 microsoft/windowsservercore powershell
  2. nslookup
  3. observe the dns server ip address does not match the server passed with --dns
  4. ipconfig /all to see all the dns servers in the container

PS C:\> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : a40f78e2ee08
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : localdomain

Ethernet adapter vEthernet (Container NIC d5dcaef9):

   Connection-specific DNS Suffix  . : localdomain
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-2C-09-69
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::d1d2:9df9:c877:7721%18(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.17.60.44(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.17.48.1
   DNS Servers . . . . . . . . . . . : 172.17.48.1
                                       8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Disabled

### LINKED ISSUE #30260: the --dns option is not working with windows container
### Expected behavior
(I was asked to repost this issue from the original in docker/for-win)

calling docker run with the --dns <some dns server> should use that server as the sole, or at least as the first dns server in the list
### Actual behavior
The default gateway is listed as the first dns server in the list on my vm ware hosted windows 10 instance. On a windows 2016 instance, the hosts dns server is listed first. 
### Information
Windows 2016 version:
PS C:\Windows\system32> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Windows 10 version:
PS C:\Windows\system32> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
 
### Steps to reproduce the behavior

  1. docker run --it --rm --dns 8.8.8.8 microsoft/windowsservercore powershell
  2. nslookup
  3. observe the dns server ip address does not match the server passed with --dns
  4. ipconfig /all to see all the dns servers in the container

PS C:\> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : a40f78e2ee08
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : localdomain

Ethernet adapter vEthernet (Container NIC d5dcaef9):

   Connection-specific DNS Suffix  . : localdomain
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-2C-09-69
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::d1d2:9df9:c877:7721%18(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.17.60.44(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.17.48.1
   DNS Servers . . . . . . . . . . . : 172.17.48.1
                                       8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Disabled

### PR DESCRIPTION
**Pull request by corbin-coleman**
Comparison of changes: https://github.com/docker/libnetwork/compare/9bca9a4...26531e5

Run with command: `vndr github.com/docker/libnetwork`

Windows fixes:

- https://github.com/docker/libnetwork/pull/1916
- https://github.com/docker/libnetwork/pull/2014
- https://github.com/docker/libnetwork/pull/2021

Fix for veth leak on daemon crash
Cleanup networkDB logic for node management

fixes https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/issues/1569
fixes https://github.com/moby/moby/issues/30260
fixes https://github.com/docker/for-win/issues/397

### CODE REVIEW

**Comment by thaJeztah** [comment]
panic on Windows will hopefully be addressed by https://github.com/moby/moby/pull/35808

```
02:03:09 ----------------------------------------------------------------------
02:03:09 PANIC: docker_api_logs_test.go:152: DockerSuite.TestLogsAPIUntil
02:03:09 
02:03:09 ... Panic: runtime error: index out of range (PC=0x45AC01)
02:03:09 
02:03:09 d:/CI/CI-1f70d6dd5/go/src/runtime/asm_amd64.s:509
02:03:09   in call32
02:03:09 d:/CI/CI-1f70d6dd5/go/src/runtime/panic.go:491
02:03:09   in gopanic
02:03:09 d:/CI/CI-1f70d6dd5/go/src/runtime/panic.go:28
02:03:09   in panicindex
02:03:09 docker_api_logs_test.go:175
02:03:09   in DockerSuite.TestLogsAPIUntil
02:03:09 d:/CI/CI-1f70d6dd5/go/src/runtime/asm_amd64.s:509
02:03:09   in call32
02:03:09 d:/CI/CI-1f70d6dd5/go/src/reflect/value.go:434
02:03:09   in Value.call
02:03:09 d:/CI/CI-1f70d6dd5/go/src/reflect/value.go:302
02:03:09   in Value.Call
02:03:09 c:/gopath/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:816
02:03:09   in suiteRunner.forkTest.func1
02:03:09 c:/gopath/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:672
02:03:09   in suiteRunner.forkCall.func1
02:03:09 d:/CI/CI-1f70d6dd5/go/src/runtime/asm_amd64.s:2337
02:03:09   in goexit
02:03:15 
```

**Comment by thaJeztah** [comment]
Odd failure here as well https://jenkins.dockerproject.org/job/Docker-PRs-s390x/7363/console; similar to  https://github.com/moby/moby/pull/35844#issuecomment-353047294:

```
10:20:22 Removing intermediate container 9f2c600dcfc7
10:20:22 The command '/bin/sh -c ./contrib/download-frozen-image-v2.sh /docker-frozen-images 	s390x/buildpack-deps:jessie@sha256:552dec28146e4d2591fc0309aebdbac9e4fb1f335d90c70a14bbf72fb8bb1be5 	s390x/busybox:latest@sha256:e32f40c39ca596a4317392bd32809bb188c4ae5864ea827c3219c75c50069964 	s390x/debian:jessie@sha256:6994e3ffa5a1dabea09d536f350b3ed2715292cb469417c42a82b70fcbff7d32 	s390x/hello-world:latest@sha256:602db500fee63934292260e65c0c528128ad1c1c7c6497f95bbbac7d4d5312f1' returned a non-zero code: 4
10:20:22 Unable to find image 'docker-s390x:0c028b0' locally
10:20:22 docker: Error response from daemon: repository docker-s390x not found: does not exist or no pull access.
```

```
Unable to find image 'docker-s390x:0c028b0' locally
```

Where does that reference `docker-s390x:0c028b0` come from?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
