### PR TITLE
Handle IPv6 entries in discovery

### PR DESCRIPTION
**Pull request by dongluochen**
This is part of fix for [swarm issue #1906](https://github.com/docker/swarm/issues/1906). Current discovery doesn't handle IPv6 entry properly. Entry `[2001:db8:0:f101::2]:4444` submitted to discovery would be returned as `2001:db8:0:f101::2:4444`. This change uses `net.JoinHostPort` to deal with this format issue. Unit tests are updated. 

Signed-off-by: Dong Chen dongluo.chen@docker.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

**Comment by aaronlehmann** [comment]
I did a grep and noticed other places in Docker where IP addresses and ports may be joined improperly.

```
api/client/port.go:                             fmt.Fprintf(cli.out, "%s:%s\n", frontend.HostIP, frontend.HostPort)
api/client/port.go:                     fmt.Fprintf(cli.out, "%s -> %s:%s\n", from, frontend.HostIP, frontend.HostPort)
vendor/src/github.com/docker/libnetwork/network.go:                                     return types.BadRequestErrorf("non parsable secondary ip address (%s:%s) passed for network %s", k, v, n.Name())
vendor/src/github.com/docker/libnetwork/network.go:                                     return types.InternalErrorf("failed to allocate secondary ip address (%s:%s): %v", k, v, err)
pkg/discovery/backends.go:      addr = fmt.Sprintf("%s:%s", addr, port)
```

I'm not sure offhand whether most of these are problematic, but the last one on the list looks like something worth fixing in this PR.

**Comment by dongluochen** [comment]
Tahnks @aaronlehmann. Fix the last one in `pkg/discovery/backends.go`.

**Comment by aaronlehmann** [comment]
Re-affirming LGTM.

**Comment by icecrime** [comment]
Good catch, LGTM!

**Comment by shmcfarl** [comment]
Hey gang.  This certainly fixed the issue with a 'swarm join' but I seem to have an issue with 'swarm manage' and pointing to etcd. Was this fix supposed address all of the IPv6 address entry issues in Docker or should I file a issue specific to 'swarm manage'?

`docker run -p 4000:2375 swarm manage etcd://[2001:db8:cafe:14::a]:2379/swarm
ERRO[1306] Handler for POST /v1.23/containers/create returned error: No such image: swarm:latest
Unable to find image 'swarm:latest' locally
latest: Pulling from library/swarm

25da0aa87182: Pull complete
45707a9f4c2b: Pull complete
7f0c09406c8f: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:5f2b4066b2f7e97a326a8bfcfa623be26ce45c26ffa18ea63f01de045d2238f3
Status: Downloaded newer image for swarm:latest
time="2016-03-16T21:46:09Z" level=info msg="Initializing discovery without TLS"
time="2016-03-16T21:46:09Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
time="2016-03-16T21:46:09Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured"
time="2016-03-16T21:46:09Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured"
time="2016-03-16T21:46:09Z" level=error msg="Discovery error: Unexpected watch error"`

**Comment by dongluochen** [comment]
@shmcfarl Can you open an issue at https://github.com/docker/swarm/issues?

**Pull request merged**
