### PR TITLE
Remove the assumption that the first IP is the bridge IP

### PR DESCRIPTION
**Pull request by ghost**
The assumption is not true if user specifies an IP address by --bip other than
the first IP, in that case the first IP address is never allocated to
any container.

Signed-off-by: Hu Tao hutao@cn.fujitsu.com

### CODE REVIEW

**Comment by taohu** [comment]
The problem can be reproduced by starting docker daemon with `--bip "172.17.42.2/30"`, then start a new container. In this case there is one IP 172.17.42.1 available, but we will get an error message:
```
FATA[0000] Error response from daemon: Cannot start container e711f2411583036378cc9a35675e73cf729010b5cc0232726275cbe34ae13f73: no available ip addresses on network
```

**Comment by crosbymichael** [comment]
ping @MalteJ  

Can you take a look at this one?

**Comment by MalteJ** [comment]
The reason the allocation starts with `172.31.0.2` is, there was someone saying that a lot of people use `172.31.0.1` for something else in their network. So we should not use the first address.
I would prefer starting at `172.31.0.1`. So I am +1 for this PR.

What do you think, @LK4D4 ?

**Comment by estesp** [comment]
@LK4D4 and others--I think we need a decision as to whether this is a reasonable path; especially with the @MalteJ commit f4551b8a48bdc7a135466398eecfb103fcde25c6 now merged, the bridge IP removal from the pool is already handled, making the comment on the code this PR is removing incorrect, as if the bridge IP is the first in the subnet, it will be removed from the pool properly anyway.

The reason I'm interested is I was working on a fix for #10382 to resolve a poor network+subnet calculation (when the subnet and network have the same starting point, the check now fails because the network is, for example, starting at ".0.2" and the subnet is ".0.1").  However, if this PR is merged, I won't need to fix that issue with a separate fix to the calculation in `RegisterNetwork`.

**Comment by LK4D4** [comment]
Seems legit, I'll try now

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
@LK4D4 should this go in 1.5?

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
