### PR TITLE
Remove unmatched bracket from _docker for zsh

### PR DESCRIPTION
**Pull request by floatingLomas**
**\- What I did**
Fixed a dangling ')' in the zsh _docker completion script.

**\- How I did it**
...With my keyboard?

**\- How to verify it**
tab completion no longer explodes with a parse error in zsh.

**\- Description for the changelog**

Fixed a zsh tab completion issue.

**\- A picture of a cute animal (not mandatory but encouraged)**
Cutest animal EVAR

### CODE REVIEW

**Comment by runcom** [comment]
LGTM ping @sdurrheimer

**Comment by jfrazelle** [comment]
looks good to me, its just removing an extra ")"

**Comment by cpuguy83** [comment]
LGTM

**Comment by sdurrheimer** [comment]
@floatingLomas Thanks, I did notice a problem with completion, but haven't got the time to look at it.

**Pull request merged**
