### PR TITLE
add powerpc and z to rebuild labels

### PR DESCRIPTION
**Pull request by vieux**
ping @dmp42 @estesp @thaJeztah

### CODE REVIEW

**Comment by estesp** [comment]
Thanks @vieux! LGTM

**Comment by thaJeztah** [comment]
I'm not sure this works, because IIRC the `rebuild/*` labels only trigger a rebuild if that CI originally ran on the PR, but won't trigger a _new_ job if it wasn't there. It _is_ possible to do from the maintainers slack channel though. (so once triggered, this change _is_ useful)

**Review by thaJeztah — APPROVED** [review]
LGTM, but see my comment above

**Comment by vieux** [comment]
@thaJeztah I agree about `rebuild/*` but I think the new labels will work

**Comment by thaJeztah** [comment]
ok, let's merge this, and see how it goes 👍

**Comment by thaJeztah** [comment]
added the labels as well

**Pull request merged**
