### PR TITLE
Restore /etc/sysconfig/docker configuration for Oracle Linux 7

### PR DESCRIPTION
**Pull request by Djelibeybi**
This restores configuration via environment variables in `/etc/sysconfig/docker*` on Oracle Linux 7 to support customers who upgrade from the previous docker packages and to better align with daemon configuration on the platform, which hasn't fully migrated to systemd drop-in files yet.

The change to the spec file is self-contained and limited only to the RPM built for Oracle Linux 7.

Signed-off-by: Avi Miller avi.miller@oracle.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @tianon @jfrazelle

**Comment by jfrazelle** [comment]
We have discussed this time and time again..

**Comment by Djelibeybi** [comment]
Yes, which is why this is not global, it's just for Oracle Linux. Our customers expect to maintain configuration from previous versions and they expect to maintain configuration in the well-known `/etc/sysconfig/` location. Other distributions may be different, but our QA team will not pass the upgrade from 1.6 to 1.8 without this.

Obviously, if this is not accepted upstream, we'll just make the changes internally before shipping, but that means there will be a difference between the (unsupported/upstream) Docker RPM build for Oracle Linux and the (supported/distro) RPM build provided by Oracle.

**Comment by phemmer** [comment]
> there will be a difference between the (unsupported/upstream) Docker RPM build for Oracle Linux and the (supported/distro) RPM build provided by Oracle

I don't think this is really a bad thing. This isn't that uncommon a practice. Many distro maintainers provider their own stuff when it comes to the init & configuration.

Generally, the packages provided by the upstream project are considered bleeding edge. It's up to the distribution to maintain compatibility with their releases.

But this is just my personal commentary. I'm not associated with docker. I'm piping in because this is my experience working with numerous distributions and open source projects.

**Comment by Djelibeybi** [comment]
> I don't think this is really a bad thing. This isn't that uncommon a practice. Many distro maintainers 
> provider their own stuff when it comes to the init & configuration.

I don't think it's a bad thing either, but if Docker is going to provide distro-specific RPMs, then the RPMs should be properly distro-specific, i.e. conforming to the best practice of the distro in terms of init and configuration. For the more modern systemd-based distros, that's absolutely drop-in files, but for the EL-derived distros, that's still `/etc/sysconfig` with systemd.

At the end of the day, I expect upstream to reject this PR but I figured it was worth a shot anyway.

**Comment by jfrazelle** [comment]
im sorry i understand your point but i agree w @phemmer 

also i think it is easier re our docs etc, to have one explanation of where/how these configuration files live/work

**Pull request closed without merging**
