### PR TITLE
Remove layersize file in favor of image JSON.

### PR DESCRIPTION
**Pull request by swernli**
@jhowardmsft @jstarks @stevvooe 

Removing the use the layersize file in favor of the layer size in the image JSON metadata.  I couldn't find any reason why the layersize file needed to be used, but it's possible there is something else I'm missing... This does resolve an issue where the layersize would end up with "0" in it on Windows and override the size correctly recorded in the image JSON.

Signed-off-by: Stefan J. Wernli swernli@microsoft.com

### CODE REVIEW

**Comment by LK4D4** [comment]
Dunno, weird janky fail :/

**Comment by swernli** [comment]
Very interesting... I'll dig in and see what is going on there!

**Comment by jhowardmsft** [comment]
Suspect a flaky test. Kicked it off again.

**Comment by stevvooe** [comment]
@swernli The worst part about this is that I am not sure if `Size` on image configuration really means anything. It is set very inconsistently. The layer size file may be the only true source of information.

@vbatts @dmcgowan Any ideas on this?

**Comment by aaronlehmann** [comment]
@stevvooe: Correct, the layersize file is the source of truth because the `Size` field is set inconsistently and can't be trusted.

**Comment by jhowardmsft** [comment]
@aaronlehmann What makes that statement about `Size` being inconsistent true?

**Comment by tonistiigi** [comment]
We should never change config on disk after it has been created after `v1.8.3`. Config is considered immutable and the hash of the config has a meaning for ID. That is why separate file is used.

At least on aufs `ApplyDiff` and `DiffSize` are identical so I don't see what this patch changes.

@jhowardmsft I think the inconsistencies come from different graphdrivers or from different methods being used between aufs and `UnpackLayer`. I don't know the details but you can easily find images from the hub that have different `Size` key than the one that you can generate locally.

**Comment by swernli** [comment]
Interesting. I had mistakenly assumed that the size stored in the image JSON was trustworthy. Given the concerns about changing on disk configuration and the unreliable nature of the config metadata, the layersize file makes more sense. 

I'll close the PR and look for a different way to resolve the size reporting on Windows.

**Comment by thaJeztah** [comment]
@tonistiigi @stevvooe reading the discussion above; is there a reason to keep the Size field around if its not useful/trustworthy?

**Pull request closed without merging**
