### PR TITLE
fix comments for test certain tests

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by estesp** [comment]
both look like good/correct updates to me; moved to docs review

**Comment by moxiegirl** [comment]
@hqhq @estesp Educate me, why just the integration tests?  `make test` does them all which is why it seemed a better choice.

**Comment by estesp** [comment]
@moxiegirl since this doc was written, the framework for the integration-cli tests has changed, and the flag to run a single test is only valid for the `test-integration-cli` target.  The other change shows that you can use `-test.run` for the unit tests, so maybe best case is that we show both options depending on whether you want to run a single or subset of tests on integration-cli versus unit tests?

**Comment by crosbymichael** [comment]
@estesp is right

LGTM

**Comment by moxiegirl** [comment]
@estesp Thanks for the explanation.  

LGTM

**Pull request merged**
