### PR TITLE
[test-integration] Remove WindowsDaemonKV as TPx are not supported anymore

### PR DESCRIPTION
**Pull request by vdemeester**
@jhowardmsft Correct me if I'm wrong, but this shouldn't be needed anymore 👼

/cc @thaJeztah @jhowardmsft @johnstep 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by jhowardmsft** [comment]
Correct. It's not needed. But I'd rather update the comment than remove it - we will need it very shortly to differentiate between RS1 and RS2 in integration tests.

**Comment by vdemeester** [comment]
Ok so this is still needed and the need is almost the same as the new `daemonKernelVersion`. I did a small thing here : https://github.com/docker/docker/pull/29661/files#diff-a715d1887671bdf0072480ba7d9773d2R215.

**Pull request closed without merging**
