### PR TITLE
Capitalize 'either' first letter

### PR DESCRIPTION
**Pull request by Jin10Dong**
**\- What I did**
Capitalize 'either' first letter to 'Either'

### CODE REVIEW

**Comment by Jin10Dong** [comment]
Capitalize 'either' first letter to 'Either'

**Comment by thaJeztah** [comment]
@Jin10Dong can you squash your commits, and make sure the commit is signed-off properly?

**Comment by Jin10Dong** [comment]
@thaJeztah I have re-committed with signed-off property, please check again. Thanks a lot.

**Comment by thaJeztah** [comment]
@Jin10Dong looks like there's still three commits in this PR; can you try rebasing, and squashing your commits? See https://docs.docker.com/opensource/workflow/work-issue/#/pull-and-rebase-frequently for some hints on how to do that

**Comment by Jin10Dong** [comment]
@thaJeztah I have committed again yesterday, please check it. Thanks.

**Comment by thaJeztah** [comment]
@Jin10Dong there's still 4 commits in this PR, can you please check?

**Comment by thaJeztah** [comment]
Looks like something went wrong when rebasing. To make things easier it's best to create a branch for your PR instead of making changes directly on master; I suggest reading the contributors guide, which explains this in more detail.

I'll close this PR, because it's not in a mergeable state, and it's only a minor fix

**Pull request closed without merging**
