### PR TITLE
Update Documentation for Windows Installation

### PR DESCRIPTION
**Pull request by ahmetb**
Boot2Docker experience is updated now that we have a Docker
client on Windows. Instead of running `boot2docker ssh`, users
can also use boot2docker on Windows Command Prompt (`cmd.exe`)
and PowerShell.
- :white_check_mark: Updated documentation and screenshots
- :white_check_mark: added a few details,
- :white_check_mark: reorganized sections by importance
- :white_check_mark:  fixed a few errors.
-  :white_circle:  The video link in the Demonstration section needs
  to be updated once I shoot a new video. (will be another PR)

Signed-off-by: Ahmet Alp Balkan ahmetalpbalkan@gmail.com
cc: @SvenDowideit 

:exclamation: :exclamation: @crosbymichael @jfrazelle please add to `1.6.0` and cherry-pick once merged. :exclamation: :exclamation:

### CODE REVIEW

**Comment by jfrazelle** [comment]
nice!

**Comment by jfrazelle** [comment]
cool powershell, I hear that is all the rage by hipsters these days

image

**Comment by jasonwilliams200OK** [comment]
Hi, will the documentation change again for 1.6? I reckon we will be able to run `docker build` without requiring `boot2docker` and VirtualBox.

Please CMIIW, starting with v1.6 we will have:

* docker.exe and boot2docker retired.
* Hyper-V support without needing VirtualBox.
* Header-less Windows (shell-only, gui-less) container, which CIs and automation folks can use to build for Windows.

(or is it just me in a dream!)

**Comment by ahmetalpbalkan** [comment]
@jasonwilliams200OK nope we do not have any windows containers at the moment and probably won't have for a few more months neither. We still need VirtualBox as docker-machine is not 1.0 and Hyper-V driver is not rock solid yet. Boot2Docker for Windows is not getting retired for 1.6 and is going to be released.

And answer to your first question, yes, this very pull request is changing the documentation for 1.6.

**Comment by moxiegirl** [comment]
@ahmetalpbalkan I've got a pending update for the windows installation also.  I think we should parallel the Mac install and explain Boot2Docker a bit more.  I'll pull this in and then merge my changes with your updates.  It is faster than commenting against this; I'll ping you back to see the completed update.

LGTM

**Comment by ahmetalpbalkan** [comment]
@moxiegirl hmm what are you planning to add at a high level? B2D is going to probably  going to be retired soon, right? If that's the case we'll probably updaye the entire thing soon anyway.

**Comment by moxiegirl** [comment]
@ahmetalpbalkan B2B is going away but exactly when isn't clear.  We get 55K hits per month to this page so even it B2B disappears in a month we will reduce some pain for some folks.

**Pull request merged**
