### PR TITLE
Deprecated of docker ps since and before options for v1.12

### PR DESCRIPTION
**Pull request by wenchma**
Deprecated note https://github.com/docker/docker/blob/master/docs/deprecated.md#docker-ps-before-and-since-options

Signed-off-by: Wen Cheng Ma wenchma@cn.ibm.com

### CODE REVIEW

**Comment by wenchma** [comment]
@thaJeztah PTAL,  and can you re-trigger  the `winddowsTP5` check ? thanks!

**Comment by thaJeztah** [comment]
Nice! :heart: these cleanups

Perhaps we should change "Target For Removal In Release: v1.12" to "Removed in release v1.12" (I see we didn't update other deprecated options, but we can do those in a separate PR)

Otherwise looks good 👍

**Comment by wenchma** [comment]
@thaJeztah  deprecated document has been updated  ad you said,  thanks.

**Comment by thaJeztah** [comment]
great! LGTM

**Comment by wenchma** [comment]
@thaJeztah  looks `experimental` and `windowsTP5` check jobs failed unrelated reason.

**Comment by runcom** [comment]
LGTM (assuming grep doesn't fail :p)

**Comment by vdemeester** [comment]
LGTM 🐼

**Pull request merged**
