### PR TITLE
Add an option to specify log format for awslogs driver

### PR DESCRIPTION
**Pull request by sanjams2**
Added an option 'awslogs-format' to allow specifying
a log format for the logs sent CloudWatch from the aws log driver.
For now, only the 'json/emf' format is supported.
If no option is provided, the log format header in the
request to CloudWatch will be omitted as before.

Signed-off-by: James Sanders <james3sanders@gmail.com>

**- What I did**
- Added an option `awslogs-format` to allow specifying a log format for the logs sent CloudWatch from the aws log driver.
- For now, only the `json/emf` format is supported.
- If no option is provided, the log format header in the request to CloudWatch will be omitted as before.
- This addresses https://github.com/moby/moby/issues/42731
- Users cannot provide the `awslogs-datetime-format` or the `awslogs-multiline-pattern` options when they set the `awslogs-format` option cannot be set to `json/emf`. This is because both the `awslogs-datetime-format` and `awslogs-multiline-pattern` options modify the log line delimiter. Given for now `json/emf` format must be a valid json line, it does not make sense to allow for different line delimiters when using `json/emf`.

**- How I did it**
- Modified the `awslogs` log driver to add a new CloudWatch client "handler" (basically middleware) to add the `x-amzn-logs-format` header to the request when the log format option is given and is `json/emf`. 
  - Tried to follow convention at every step of the way. 
  - Based key name off of the key name used in the [fluentd plugin](https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch)

**- How to verify it**
- Unit Testing
- Manual integration testing:
  - Ran container with no format option provided and verified logs were still published (no regression)
  - Ran container in development environment with `--log-opt awslogs-format=json/emf` enabled and saw metrics posted to CloudWatch: 
    ```bash
    docker run --rm \
        --log-driver awslogs \
        --log-opt awslogs-region=us-west-2 \
        --log-opt awslogs-group=emf-logger-test-container \
        --log-opt awslogs-create-group=true \
        --log-opt awslogs-format=json/emf \
        emf-logger \
        run
    ```
  - Metrics in CloudWatch: image
 - Attempted to specify a "random" log format and saw an error was thrown
    ```bash
    # docker run --rm \
        --log-driver awslogs \
        --log-opt awslogs-region=us-west-2 \
        --log-opt awslogs-group=emf-logger-test-container \
        --log-opt awslogs-create-group=true \
        --log-opt awslogs-format=random \
        emf-logger \
        run
    docker: Error response from daemon: unsupported log format 'random'.
    ```
 - Attempted to set `awslogs-datetime-format` and saw an error was thrown
   ```bash
    docker run --rm \
        --log-driver awslogs \
        --log-opt awslogs-region=us-west-2 \
        --log-opt awslogs-group=emf-logger-test-container \
        --log-opt awslogs-create-group=true \
        --log-opt awslogs-format='json/emf' \
        --log-opt awslogs-datetime-format='YYYY-mm-dd' \
        emf-logger \
        serve
    docker: Error response from daemon: you cannot configure log opt 'awslogs-datetime-format' or 'awslogs-multiline-pattern' when log opt 'awslogs-format' is set to 'json/emf'.
   ```
 - Attempted to set `awslogs-multiline-pattern` and saw an error was thrown
   ```bash
    docker run --rm \
        --log-driver awslogs \
        --log-opt awslogs-region=us-west-2 \
        --log-opt awslogs-group=emf-logger-test-container \
        --log-opt awslogs-create-group=true \
        --log-opt awslogs-format='json/emf' \
        --log-opt awslogs-multiline-pattern='-------' \
        emf-logger \
        serve
    docker: Error response from daemon: you cannot configure log opt 'awslogs-datetime-format' or 'awslogs-multiline-pattern' when log opt 'awslogs-format' is set to 'json/emf'.
   ```

**- Description for the changelog**
Added a new option to `awslogs` log driver to specify the log format that is sent to CloudWatch.

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by sanjams2** [comment]
Will update https://github.com/docker/docker.github.io/blob/master/config/containers/logging/awslogs.md once this is pushed

**Comment by sanjams2** [comment]
@samuelkarp any chance you could take a look at this?

**Comment by PettitWesley** [comment]
@samuelkarp Please review 😬 

I have seen requests for this...

**Review by samuelkarp — CHANGES_REQUESTED** [review]
Thanks for putting this together!  I have a few small changes I'd like to see before this is ready to go.

**Comment by sanjams2** [comment]
I have included the changes requested by @samuelkarp. It seems moby is having trouble with jenkins builds across the board for a multitude of reasons. I dont know if this typically blocks merging but I figure the changes themselves can at least be reviewed while the build system is fixed. 

Also, apologies if squash and force push is not the correct way to update pull requests. Im new to contributing through github. Squash and force push also seemed to be the way that other pull requests had been updated and kept in line with a single commit per unit change as outlined in the [contributing guidelines](https://github.com/moby/moby/blob/master/CONTRIBUTING.md)

**Comment by sanjams2** [comment]
@samuelkarp Do you have any more comments on the most recent revision? Also, what is the guidance here now that moby seems to be failing all the jenkins building and testing for some time now?

**Review by samuelkarp — APPROVED** [review]
LGTM

The CI failures do not look related to your change.  This needs an LGTM from a second maintainer before it's ready to merge.

**Comment by sanjams2** [comment]
@samuelkarp thanks for the review! Any suggestion on a second maintainer I could bug :) ?

**Comment by tianon** [comment]
> For now, only the 'json/emf' format is supported.

I think this is the phrasing that threw me off -- to make sure I understand, there are technically two values supported, right?  Empty (for the current behavior) and the new `json/emf` value?

**Comment by sanjams2** [comment]
@tianon that is technically correct. Empty as a value would work. But is there a recommendation to use empty as opposed to omitting the value entirely? In the next line I state:
>  If no option is provided, the log format header in the request to CloudWatch will be omitted as before.
Would you prefer I explicitly call out that users can set the value to empty in addition to simply omitting it?

**Comment by tianon** [comment]
I don't think we need to call it out more here -- I think we just need to make it clear to users in the documentation PR what the difference is and when and why users might want to add this option. :+1:

This looks/sounds sane to me (although I'm not very familiar with most of this code and obviously not very familiar with the AWS details underneath :sweat_smile:).

**Comment by sanjams2** [comment]
@samuelkarp @tianon sorry to keep bothering, but is there anything left here to do to get this merged in? I see it was tagged for a certain milestone, does that mean it's good to go? All checks are passing now.

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
