### PR TITLE
Vendor swarmkit ae29cf2

### LINKED ISSUE #31249: Swarm mode with mode=host and port is already in use by service on another host.
Hi,

I am using docker swarm mode (1.13) and I have 2 services A and B.
Both services publish ports using exclusively `mode=host` and both services have placement constraint on a different server.

Now the issue is that both services listen of port 443. Once the first service starts, the second is failing to start with the following error:

`Error response from daemon: rpc error: code = 3 desc = port '443' is already in use by service 'A' (pjo2sx4wx3apaejqhgevpkvqs)`

I am guessing there is a check somewhere that does not take into account that service A is using `mode=host` and so it's not mutually exclusive to run services on the same port anymore as far as the services are not running on the same host.

docker version
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### PR DESCRIPTION
**Pull request by aaronlehmann**
Fixes #31249

https://github.com/docker/swarmkit/compare/f420c4b9e1535170fc229db97ee8ac32374020b1...ae29cf24355ef2106b63884d2f9b0a6406e5a144

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by aboch** [comment]
looks good to me

**Comment by aaronlehmann** [comment]
docker-py test failure is surely unrelated

**Comment by aaronlehmann** [comment]
Updated to ae29cf24355ef2106b63884d2f9b0a6406e5a144

cc @aluzzardi @rogaha

**Comment by rogaha** [comment]
Awesome! thanks @aaronlehmann!

**Comment by rogaha** [comment]
👍

**Comment by rogaha** [comment]
@aaronlehmann should we re-trigger the tests for `PowerPC & WindowsRS1`?

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by rogaha** [comment]
Thanks @vdemeester! All 💚, besides the `windowsRS1` tests that `timed out`:

```
09:20:45 INFO: Commit hash is 498699033
09:20:45 INFO: Nuke-Everything...
09:20:45 INFO: Container count on control daemon to delete is 0
12:40:41 Build timed out (after 200 minutes). Marking the build as failed.
12:40:41 Set build name.
12:40:41 New build name is '#33170'
12:40:41 Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '#33170', new value: '#33170'
```

**Comment by vdemeester** [comment]
@jhowardmsft ^^

**Comment by rogaha** [comment]
Thanks @thaJeztah! All green now!

**Comment by thaJeztah** [comment]
All green now 👍

**Pull request merged**
