### PR TITLE
fix default tmpfs size to prevent breakage

### LINKED ISSUE #23394: Tmpfs broken on master but not 1.11.1
I used git bisect and my broken builds of https://github.com/dcos/dcos-docker and it all traced back to this commit https://github.com/docker/docker/commit/397a6fefadf9ac91a5c9de2447f4dea607296470

It is working on the stable version. 

Here is the problem because obviously I am not expecting you to read 300+ lines of make that is in that repo. When its broken I get `no space left on device`. Otherwise it just works. Trying to make a small repro is kinda hard :(

### PR DESCRIPTION
**Pull request by jessfraz**
Fixes #23394

### CODE REVIEW

**Comment by runcom** [comment]
is there any way to test this? :angel: 

LGTM otherwise

**Comment by jfrazelle** [comment]
so the problem before was data quite literally equals `'""` which was why it was never hitting this line https://github.com/yongtang/docker/commit/14f936da0d5fe24b69b2a5fd10deac9c8574532d#diff-ea22bb26655e758dc94c291dbaee0e76L470, and It's pretty much being tested by fixing the tests but ill try to think of something else

**Comment by justincormack** [comment]
Yes, 64MB is tiny. This is limited by memory limits anyway.

**Comment by thaJeztah** [comment]
Do we know why the default was set in the first place? (so even before https://github.com/yongtang/docker/commit/14f936da0d5fe24b69b2a5fd10deac9c8574532d#diff-ea22bb26655e758dc94c291dbaee0e76L470)?

**Comment by justincormack** [comment]
The default for tmpfs is half physical memory per mount, and this is unaffected by eg setting a cgroup memory limit, so there might have been an idea that it might help you not DoS yourself by using all memory, but I don't think we can usefully set policy here and there are many more ways to use up memory.

LGTM. And its green.

**Comment by thaJeztah** [comment]
sgtm, let's do this

**Comment by jfrazelle** [comment]
That was so fast I've never woken up to my stuff being merged so fast :)

**Comment by tiborvass** [comment]
I removed changelog from this because @jfrazelle said in #23394 that it was only in master and not 1.11. Please ping me now if this isn't the case

**Pull request merged**
