### PR TITLE
Non blocking attach clients

### PR DESCRIPTION
**Pull request by cpuguy83**
Enables clients that may be slow or prefer not to block the container's stdio to opt for dropping data over blocking stdio of the container.

This is especially useful for remote clients that may have a connection interruptions or are otherwise too slow to consume all the data produced by the container before the stdio buffers are full.

Note that to keep my sanity while adding this I did some code cleanup for `AttachStreams`.
As such there are 3 commits:
1. Adds non-blocking mode to BytesPipe
2. Cleans up some of the attach code
3. Plumbs through non-blocking options from clients.

ping @aaronlehmann 
Related (in spirit) to #28762

### CODE REVIEW

**Comment by tonistiigi** [comment]
Why should we encourage dropping data? Isn't the need for this feature showing that user is doing something wrong and not understanding the client-server model. It may have very surprising results that user may not realize when turning it on. I think the method we should recommend is `docker run -d && docker logs`.

> useful for remote clients that may have a connection interruptions 

Not sure I understand this. If attach stream drops the container will continue on full speed.

**Comment by cpuguy83** [comment]
I don't think we are encouraging dropping data, rather we are giving the consumer a choice of whether or not the attached stream is important enough to block the container from doing it's work.

1. Network connections are unreliable (both in performance and stability)
2. Many applications spit out a lot of data (even if unexpectedly)
3. In many cases ensuring the task actually runs is way more important than consuming its output

Is there a really compelling reason to not let someone make this choice?

**Comment by tonistiigi** [comment]
@cpuguy83 I'm not aware of `ssh` having `--drop-data` flag while it is exactly the same problem. Stopping users from making bad decisions is a good thing to do. All of the points you listed can be handled atm without dropping data. If the client connection is much slower, `logs` command can be used, if data is not needed containers can be put to background, opened streams can be configured or detached.

**Comment by cpuguy83** [comment]
@tonistiigi SSH is a different use-case. This is more like exec where SSH is starting a new process in an existing environment.

Also, in terms of docker experience, only jsonfile and journald are support with `docker logs`.

**Comment by aaronlehmann** [comment]
I think I agree with Tonis on this one. It seems like the right workaround is to use `docker logs`. Dropping data has unclear ramifications that might not be noticed until it's too late. I think SSH is a good analogy.

**Comment by cpuguy83** [comment]
This is fundamentally a different problem than SSH would be dealing with.
Opening an SSH session is not going to block an important service from doing it's work.
To take that even a step further, people use things like screen or tmux to make sure their jobs aren't killed when ssh is disconnected.

In current situation, if an attached client for whatever reason can't consume the pipe everything comes to a halt. The container can't write to it's stdio and as such can't perform work, logs aren't written, etc.
Let's even say in a happy case where the container process does not let itself get blocked on stdio, logs are still dropped, data is still lost.

I'm not sure I understand the line in the sand here.

**Comment by tonistiigi** [comment]
@cpuguy83 Running a command through SSH blocks the process after a buffer is filled exactly the same way as Docker does it. The problem here is the behavior of user connecting to a processes stdio over a slow connection. I don't see a difference if it is a process in a host or a process inside a container or if you can detach and attach again.

**Comment by cpuguy83** [comment]
@tonistiigi The difference is ssh is starting a new process, not connecting to an existing one.

**Comment by aaronlehmann** [comment]
If I ssh in and run `screen -x`, I'd imagine that this can block the process running inside screen.

**Comment by thaJeztah** [comment]
Does `docker attach --noblock` compare to `docker attach` as https://mosh.org compares to ssh?

**Comment by cpuguy83** [comment]
Just going to go ahead and close since it seems like some are adamantly opposed to introducing this.

Carrying the attach refactors in another PR.

**Pull request closed without merging**
