### PR TITLE
user namespaces: duplicate dot in user namespaces error message

### PR DESCRIPTION
**Pull request by liron-l**
duplicate dot in user namespaces error message:

$ docker run -ti --net=host ubuntu /bin/bash
docker: Error response from daemon: Cannot share the host or a
container's network namespace when user namespaces are enabled**..**

Signed-off-by: Liron Levin liron@twistlock.com

### CODE REVIEW

**Comment by liron-l** [comment]
@estesp please review.

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by vdemeester** [comment]
LGTM 🐍

**Comment by estesp** [comment]
nice catch, thanks! LGTM

**Comment by estesp** [comment]
Merging with failed gccgo run - spurious network connectivity error caused a single test failure unrelated to whether certain error messages have periods :)

**Comment by estesp** [comment]
@thaJeztah any reason we want this cherry-picked for 1.10? Seems very minor, but will let you decide.

**Comment by thaJeztah** [comment]
don't think we really need this for 1.10, no problem adding it, but it's really minor

**Pull request merged**
