### PR TITLE
Jenkinsfile: windows 2022 LTSC mcr.microsoft.com/windows/servercore:ltsc2022

### PR DESCRIPTION
**Pull request by thaJeztah**
see https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info
see https://github.com/moby/moby/pull/42527#issuecomment-902420557

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by StefanScherer** [comment]
Haha, it also worked with the Insider 2022 Insider machine pulling and running the `:ltsc2022` image 😅 Sure, it has the same OS version.

@thaJeztah I've put the new machines in place, if you want to run re-run the Jenkins pipeline with the ltsc machine.

**Comment by thaJeztah** [comment]
OK, kicked CI again (hope it picks a new machine); thanks!

**Comment by StefanScherer** [comment]
Yes the 20.10.8 engine is installed, that‘s the latest machine. 👍

**Review by StefanScherer — APPROVED** [review]
LGTM

**Pull request merged**
