### PR TITLE
1.13.0-rc4 cherry-picks: part1

### LINKED ISSUE #29199: fail to attach a container if this container start failed and then start success next time
**Description**

If a start a container, and it fail due to some reason, and then it start success next time, you can't attach to this container.
**Steps to reproduce the issue:**
1.  create a container
```
$ docker create --name test -ti busybox
ac50d05c8b3c901a7af264c49ed1d95cbb09e5052e469d4c3bd0c6bc76ed9058
```
2. create another container link to this container
```
$ docker create --name foo -ti --link test:test busybox
dff0a8f9868e5f5da3edc9a7a5e89f02290ad66ed7c621403b8c6a83b6324d3f

```
3. start container `foo`, it will fail
```
$ docker start -ai foo
Error response from daemon: Cannot link to a non running container: /test AS /foo/test
```
4. start container `test` and then start container `foo`
```
[lei@centos docker]$ docker start test
test
[lei@centos docker]$ docker start -ai foo
/ #

```
the container `foo` is start, but you can't do anything 
```
[lei@centos docker]$ docker start -ai foo
/ #



ls
ls


```
you can see the container is running in the `docker ps`, but you can't attach to it `docker attach`, `attach`
will exit immediately if you type anything.

**Describe the results you received:**
you can't  attach to this container.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   9cd598f-unsupported
 Built:        Mon Dec  5 07:35:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   9cd598f-unsupported
 Built:        Mon Dec  5 07:35:59 2016
 OS/Arch:      linux/amd64
 Experimental: false

```

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by vieux**
Convert DanglingOnly to Filters for `docker image prune` #28535
Fix issue where secret ID is masked by name #28896
refactor plugin install #28963
improve TestServiceLogs for the goroutine issue #28915 #28974
refine api swagger.yaml towards image create status code #29062
Print checkpoint id when creating a checkpoint #29073
Add bash completion for secret management #29109
Fix bash completion for `docker service create|update` #29111
Add bash completion for `docker version --format` #29113
Handle logging in compose to swarm #29123
Windows: make.ps1 Throw exception on failure #29145
Windows: Dockerfile 2GB clarification Hyper-V #29149
add 403 for endpoint network create #29166
Add bash completion for `docker network create --attachable` #29182
Fix `docker inspect <unkown object>` issue on Windows #29186
fix #29199, reset container if container start failed #29200
modify URLs for bind docker in docs/api #29201
Add zsh completion for 'docker network create --attachable' #29202
hack/make.sh: fix BUILDTIME #29082
Optimize the log info for client test #29026
api/types/container,client: gofmt #29134 
Plugin repository pinning #28459
fix apparmor load profile #28924
Caution against the use of CONFIG_LEGACY_VSYSCALL_NATIVE #29124
Add headers when using exec #29139
Make v2/Plugin accesses safe. #29191
add SCOPE field content for docker network ls #29241
fix some version information #29245
plugins: container-rootfs-relative paths #26398
Fix race in setting plugin refcounts. #29281
Remove unsupported distros from install script #23480 
Windows: make.ps1 - remove bonus whitespace #29162
Windows: make.ps1 fix DCO check #29231 
Add registry-specific credential helper support, take 2 #25851
Fix processing of unset build-args during build #29104
Fix issue for `--hostname` when running in "--net=host" #29144
replace env description with args in extend config #29320
Add zsh completion for 'docker inspect --type=plugin' and other missing ones #29317
Fix link to volume label support issue in changelog #29311
Fix description of docker swarm command #29309
fix some broken contents links #29308
Add bash completion for `docker inspect --type plugin` #29305
Windows: Fix crash in docker system prune #29287
remove old media type compat for plugins #29230
service ps: Revert output to 1.12 behavior. #29196
Note about potential plugin issue when upgrading #29173
Fix missing IPAM options in swarm network mode #29074
daemon: switch to 'ensure' workflow for AppArmor profiles #29130
When plugin enable fails, unmount PropagatedMount. #29337
[integration-cli] skip plugin tests on non-x86 #29335
deprecate "top-level" network information in NetworkSettings #28437
add missing status code 403 for services/create in docs #29216
Update the option for docker build #29267
Windows: Prompt fix use regular stdin #29288
stack_config.md not exist and delete it in other files #29352
Fix the option name for network #29359
Update reference docs for service ps #29361
Fix issues with plugin and `--live-restore` #29283
Run overlay attachable test on a single daemon #28955
Refcount graphdriver plugins properly #29008

### CODE REVIEW

**Comment by vieux** [comment]
I kicked off ARM on this one /cc @anusha-ragunathan

**Comment by vieux** [comment]
@jhowardmsft looks like it doesn't compile on windows, am I missing something ?

**Comment by friism** [comment]
@vieux no, it's the build script that tallies some git stats: https://github.com/docker/docker/blob/master/hack/make.ps1#L192

**Comment by vieux** [comment]
@friism how come https://github.com/docker/docker/pull/29145 didn't error out ?

**Comment by jhowardmsft** [comment]
Looking

**Comment by jhowardmsft** [comment]
Yes, I see the problem. Working on a fix. PR shortly... (It's tripping on .png files which git diff is returning `-` for number of lines changed rather than a number).

**Comment by jhowardmsft** [comment]
#29231 fixes it.

**Comment by cyphar** [comment]
#29130 should also be included (but maintainers need to merge it first).

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
