### PR TITLE
Added optional flags to init gcp logger metadata

### PR DESCRIPTION
**Pull request by farcaller**
**\- What I did**

Added `gcp-meta-zone`, `gcp-meta-name` and `gcp-meta-id` to gcplogs driver. If at least one of them is specified, docker will provide `instance` dict to the GCP logs if metadata server is not available, thus allowing to provide metadata from instances that aren't running on GCE.

**\- How to verify it**

Run the docker off GCE, providing auth details via `GOOGLE_APPLICATION_CREDENTIALS` and passing any of the relevant gcp logging options.

**\- Description for the changelog**

Added optional flags to init gcp logger metadata

**\- A picture of a cute animal (not mandatory but encouraged)**

b4kr0

Signed-off-by: Vladimir Pouzanov farcaller@google.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
Don't forget to update the docs as well https://github.com/docker/docker/blob/master/docs/admin/logging/gcplogs.md

**Comment by farcaller** [comment]
Done.

**Comment by thaJeztah** [comment]
Design looks good to me, moving to code review

**Comment by thaJeztah** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Moved to docs review.

**Comment by vdemeester** [comment]
LGTM 🐸
/cc @sfsmithcha @SvenDowideit @thaJeztah

**Comment by SvenDowideit** [comment]
LGTM - I presume this is not a 1.2 change - feel free to change it if i'm wrong :)

**Pull request merged**
