### PR TITLE
improve TestServiceLogs for the goroutine issue #28915

### PR DESCRIPTION
**Pull request by AkihiroSuda**
This PR improves `TestServiceLogs` for the goroutine issue #28915

The test should fail, until https://github.com/docker/swarmkit/pull/1775 gets vendored.

```console
----------------------------------------------------------------------
FAIL: docker_cli_service_logs_experimental_test.go:21: DockerSwarmSuite.TestServiceLogs

[de7be60b081bd] waiting for daemon to start
[de7be60b081bd] daemon started
log for "TestServiceLogs1": "TestServiceLogs2.1.q5uzrup5n5uf@d860d4a1ee00    | hello2\n"
docker_cli_service_logs_experimental_test.go:46:
    c.Assert(out, checker.Contains, message)
... obtained string = "TestServiceLogs2.1.q5uzrup5n5uf@d860d4a1ee00    | hello2\n"
... substring string = "hello1"

[de7be60b081bd] exiting daemon

----------------------------------------------------------------------
```
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
For 1.13 docker/swarmkit#1775 is already merged via https://github.com/docker/docker/pull/29049, 
but not yet for master https://github.com/docker/docker/pull/29117

**Comment by cpuguy83** [comment]
In master now.

**Comment by AkihiroSuda** [comment]
janky failure is unrelated
```
00:59:54.903 ----------------------------------------------------------------------
00:59:54.903 FAIL: docker_cli_swarm_test.go:999: DockerSwarmSuite.TestSwarmJoinPromoteLocked
00:59:54.904 
00:59:54.904 [deb6a004516ed] waiting for daemon to start
00:59:54.904 [deb6a004516ed] daemon started
00:59:54.904 [d259b49051d62] waiting for daemon to start
00:59:54.904 [d259b49051d62] daemon started
00:59:54.904 [d259b49051d62] exiting daemon
00:59:54.905 [d259b49051d62] waiting for daemon to start
00:59:54.905 [d259b49051d62] daemon started
00:59:54.905 [d1135609432f1] waiting for daemon to start
00:59:54.905 [d1135609432f1] daemon started
00:59:54.905 [d259b49051d62] exiting daemon
00:59:54.905 [d259b49051d62] waiting for daemon to start
00:59:54.905 [d259b49051d62] daemon started
00:59:54.905 [d1135609432f1] exiting daemon
00:59:54.905 [d1135609432f1] waiting for daemon to start
00:59:54.906 [d1135609432f1] daemon started
00:59:54.906 [d1135609432f1] exiting daemon
00:59:54.906 [d1135609432f1] waiting for daemon to start
00:59:54.906 [d1135609432f1] daemon started
00:59:54.906 [d1135609432f1] exiting daemon
00:59:54.906 [d1135609432f1] waiting for daemon to start
00:59:54.906 [d1135609432f1] daemon started
00:59:54.907 docker_cli_swarm_test.go:1058:
00:59:54.907     checkSwarmLockedToUnlocked(c, d3, unlockKey)
00:59:54.907 docker_cli_swarm_test.go:821:
00:59:54.907     c.Assert(getNodeStatus(c, d), checker.Equals, swarm.LocalNodeStateActive)
00:59:54.908 ... obtained swarm.LocalNodeState = "locked"
00:59:54.908 ... expected swarm.LocalNodeState = "active"
00:59:54.908 
00:59:54.908 [deb6a004516ed] exiting daemon
00:59:54.908 [d259b49051d62] exiting daemon
00:59:54.908 [d1135609432f1] exiting daemon
00:59:57.732 
00:59:57.732 ----------------------------------------------------------------------
```

**Review by thaJeztah — APPROVED** [review]
LGTM

ping @vdemeester

**Review by vdemeester — APPROVED** [review]
LGTM :angel:

**Pull request merged**
