### PR TITLE
Adds support for setting cgroup CPU CFS period.

### PR DESCRIPTION
**Pull request by mrunalp**
This allows one to set the cpu period used in cpu quota calculation.

Signed-off-by: Mrunal Patel mrunalp@gmail.com

### CODE REVIEW

**Comment by rjnagal** [comment]
LGTM :+1: 

Setting quota is hard if the default cpu period varies or is changed at root.

Thanks @mrunalp

**Comment by coolljt0725** [comment]
This is a dup of #12180

**Comment by jfrazelle** [comment]
closing as dup sorry, but would love your feedback on #12180

**Comment by mrunalp** [comment]
@jfrazelle @coolljt0725 My bad! I should have looked before implementing. Thanks!

**Pull request closed without merging**
