### PR TITLE
Delete conflict error code

### PR DESCRIPTION
**Pull request by gregwebs**
Addresses #30159 

**- What I did**

	delete conflict status is now 409 instead of 400

**- How I did it**

in the PR

**- How to verify it**

Let me know how I can unit test this. Otherwise I can attempt manual testing.
I did run `make test` successfully already.

**- Description for the changelog**

	delete conflict status is now 409 instead of 400

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @stevvooe @justincormack PTAL

**Comment by stevvooe** [comment]
409 is a better error code, but this needs to be updated in the documentation.

**Comment by thaJeztah** [comment]
Looks like there's already a 409 status code documented, but i need to check the latest API docs / swagger

**Comment by gregwebs** [comment]
409 was present in the 1.24 docs.
If I look at the [new 1.2.5 docs](https://docs.docker.com/engine/api/v1.25/) it is not present

**Comment by thaJeztah** [comment]
ah, looks like that was addressed on master, but not published yet; https://github.com/docker/docker/commit/c0cf14a73c38bf573803be8bc50af95a411732ba

**Comment by gregwebs** [comment]
That error message text isn't correct for this case. For this case it should say "the container is already being removed".

The current text doesn't actually make any sense to me as a 409 because there are not any conflicting requests. 400 would make a lot more sense to me: essentially the `force` flag is missing given that the container state is running

Please advise how you want to resolve this.

**Comment by vdemeester** [comment]
ping @thaJeztah what is the status ? :angel:

**Comment by thaJeztah** [comment]
> The current text doesn't actually make any sense to me as a 409 because there are not any conflicting requests.

When using HTTP status codes for an API, there's unfortunately a lot of room for "interpretation". A different description of 409 is "The request could not be completed due to a conflict with the current state of the target resource.", which _does_ look appropriate for "You cannot remove a running container" (which could be due to a different request having introduced the conflict).

Feel free to open a separate PR for changing that to open a discussion if you feel strongly about that though.

> Please advise how you want to resolve this.

Ideally, we'd add a second example to the 409 response code, however, it looks like Swagger / Open-API 2.0 does not support that; https://github.com/OAI/OpenAPI-Specification/issues/270, but is proposed to be added in Open-API 3.0 (https://github.com/OAI/OpenAPI-Specification/pull/741)

Perhaps we should be creative and put both possible errors in the same "message"?

**Comment by gregwebs** [comment]
Hmm, in this case it would be peculiar for a different request to have introduced the conflict. But given there is some plausibility I wouldn't change it if that means a change in the API.

However you would like to resolve the swagger is fine with me.

**Comment by gregwebs** [comment]
I updated the PR for the merge conflict.

OpenAPI v3 is out but It doesn't look like it offers us any help.

Rather than returning a 4xx would it make sense to return a `200` or `202`? It isn't necessarily an error to request the removal of something that is in the process of being removed.

**Comment by gregwebs** [comment]
Actually, after reviewing my original bug report, a `200` or `202` could easily expose the original bug under a 200 error code instead of 400. Give this state, my preference would be to use a 409 or a 423.

@thaJeztah I am hoping we can get this merged soon.

**Review by vdemeester — COMMENTED** [review]
SGTM but might need to be versionned
/cc @thaJeztah

**Comment by justincormack** [comment]
I don't think 409 or 423 are appropriate. The spec says https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7/

> Methods can also have the property of "idempotence" in that (aside from error or expiration issues) the side-effects of N > 0 identical requests is the same as for a single request. The methods GET, HEAD, PUT and DELETE share this property. Also, the methods OPTIONS and TRACE SHOULD NOT have side effects, and so are inherently idempotent.

So an extra `DELETE` while in progress should behave just like the original delete, and return a success error code.

**Comment by stevvooe** [comment]
@justincormack [Google's API Style guide](https://cloud.google.com/apis/design/standard_methods#delete) provides some decent guidance:

> Calls to the Delete method should be idempotent in effect, but do not need to yield the same response. Any number of Delete requests should result in a resource being (eventually) deleted, but only the first request should result in a success code. Subsequent requests should result in a google.rpc.Code.NOT_FOUND.

Note that there is some GRPCisms in there, but this applies to HTTP behavior, as well.

In general, we should ask what we are trying to communicate to the client. Does the client care that there is an ongoing delete in progress? What actions would they take if we returned that instead of a 404 or 204?

**Comment by cpuguy83** [comment]
Closing since the error returned is a conflict type now.

**Comment by cpuguy83** [comment]
Thanks for looking into this and for your patience!

**Pull request closed without merging**
