### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by scjane**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@scjane could you sign off your commit, and change this PR to be against the "master" branch (you can do this using the "edit" button at the top right)?

Unfortunately we wont' be able to merge the PR if the sign-off is missing

**Comment by scjane** [comment]
@thaJeztah Is it OK now? Sorry for the inconvenience I brought.

**Comment by thaJeztah** [comment]
No worries, thanks for contributing! 

Let's see. Can you update your sign-off to use your real name? https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

After that, you should be able to change the "base" branch to "master" using the edit button;

screen shot 2017-02-24 at 13 38 57

screen shot 2017-02-24 at 13 39 07

**Comment by thaJeztah** [comment]
Thanks @scjane. Looks like that didn't work, and a rebase is needed 😅 

I'll carry this in https://github.com/docker/docker/issues/31480, so let me close this one

**Pull request closed without merging**
