### PR TITLE
rebased canonical/json off go 1.5.1

### PR DESCRIPTION
**Pull request by jessfraz**
ping @tianon @runcom @tonistiigi @tiborvass

### CODE REVIEW

**Comment by runcom** [comment]
:) LGTM

**Comment by tiborvass** [comment]
@jfrazelle did you have to change anything or it's a simple conflict-free rebase?

**Comment by jfrazelle** [comment]
conflict free!! :) it was so nice i had to do it twice to be sure hahaha

**Comment by tiborvass** [comment]
LGTM

**Comment by calavera** [comment]
LGTM. Test failing is unrelated to this change. Merging.

**Pull request merged**
