### PR TITLE
Add .git in .dockerignore

### PR DESCRIPTION
**Pull request by tobegit3hub**

### CODE REVIEW

**Comment by tobegit3hub** [comment]
Thanks for your detailed instruction @GordonTheTurtle :+1: 

I have updated the commit message and will pay attention to this when I try to contribute `docker` later.

**Comment by LK4D4** [comment]
@tobegit3hub I'm not sure that it'll work. We using git for pretty many things (build naming, validation).

**Comment by thaJeztah** [comment]
@tobegit3hub this won't work, as @LK4D4 mentioned; this was tried before but the build system requires this (see https://github.com/docker/docker/pull/12581#issuecomment-94630603)

I'm going to close this PR, because unfortunately we cannot implement this. Thanks for your contribution, though!

**Comment by tobegit3hub** [comment]
Reasonable :smiley:

**Pull request closed without merging**
