### PR TITLE
[WiP] Adds testing for bridge's IPv6 support

### PR DESCRIPTION
**Pull request by simonswine**
Here my first try to add some tests for the IPv6 bridge implementation (cf. #10001). Comments and help are warmly appreciated, since this is my first Docker / Golang contribution.

I implemented the following tests:
- test for global subnets <= 80
- test for global subnets > 80
- test link local generation
- test duplicated addresses
- tests regression from bug #11427

Cheers

### CODE REVIEW

**Comment by estesp** [comment]
Nice! These look like some great additions-- @MalteJ do you have time to review/provide feedback?

**Comment by LK4D4** [comment]
That's cool. Probably it's time to write integration-cli tests as well.

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by MalteJ** [comment]
great! Thanks for this PR!

**Pull request merged**
