### PR TITLE
Throw an error when daemon option (--storage-opt) is passed to anything other than devicemapper.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
Following up on this PR #19123.
We should throw an error if daemon option (--storage-opt) is passed to other storage drivers like overlay, aufs, btrfs. As `--storage-opt` is only applicable to `devicemapper`.

Currently, if you pass `--storage-opt` to other storage drivers, it is just silently ignored, and user has no idea what happened !

**Comment by shishir-a412ed** [comment]
ping @calavera @rhvgoyal @thaJeztah

**Comment by rhvgoyal** [comment]
I think we should throw an error from graphdriver. That way if some graph driver wants to implement their own storage opt down the line, they can easily do it.

**Comment by icecrime** [comment]
Why would `--storage-opt` be devicemapper specific???

**Comment by cpuguy83** [comment]
Yeah, graphdrivers should register a option validator or something to resolve this.

**Comment by icecrime** [comment]
```
$ docker daemon --help
[...]
--storage-opt=[]                         Set storage driver options
```

There's nothing devicemapper specific about that, and there's no reason we shouldn't have other graphdrivers support driver specific options in the future, especially with the experimental support for external graphdrivers.

Sorry, closing this.

**Comment by icecrime** [comment]
I think a "warning: trailing storage options" would be just fine.

**Comment by rhvgoyal** [comment]
@icecrime if somebody passes "--storage-opt dm.basesize=10G" to overlay, that should error out. This is the intent of this PR. If one passes a storage-opt which is not supported/recognized by graph driver, it should error out instead of simply ignoring it.

**Comment by shishir-a412ed** [comment]
@icecrime Can you please explain me, If I start my docker on overlay using this.
`docker daemon --storage-opt dm.basesize=30G`. Will I get a basedevice size of 30G on overlay ?

The command above will execute just fine. eventhough that storage option has no significance on overlay.

**Comment by shishir-a412ed** [comment]
@icecrime In future if other graph drivers support `--storage-opt`, that error message can be removed. Till then the user needs to know if the option passed was actually applicable to this storage driver.

**Pull request closed without merging**
