### PR TITLE
add defer layerReader.Close()

### PR DESCRIPTION
**Pull request by lixiaobing1**
add defer layerReader.Close()

### CODE REVIEW

**Comment by tonistiigi** [comment]
@lixiaobing10051267 Is this solving an issue? The rule is usually that if a function takes an `io.ReadCloser`, `NewCancelReadCloser` in this case, then this function should close it as well. If I look at a source then it seems to do it, so not sure where the problem is coming from.

**Comment by lixiaobing10051267** [comment]
@tonistiigi I think layerReader should close whenever the func exits especially the exception happends such as:
     	_, err = io.Copy(ld.tmpFile, reader)
 	if err != nil {
 		ld.Close()
 		return nil, 0, err
 	}

**Comment by cpuguy83** [comment]
I don't think this is neccessary and potentially dangerous.
Once a Closer is passed off to something else the close responsibility is delegated to something else. Using `defer` here means it'll have `Close` called twice since closing `reader` wil also close `layerReader`

**Comment by tonistiigi** [comment]
@lixiaobing10051267 Can you point me to a code path that exits this func without closing the `layerReader`. We definitely don't want to close twice, as @cpuguy83 already commented.

**Pull request closed without merging**
