### PR TITLE
Remove unnecessary line

### PR DESCRIPTION
**Pull request by daehyeok**
Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>

### CODE REVIEW

**Comment by daehyeok** [comment]
`name` is not used

**Comment by AkihiroSuda** [comment]
cc @tiborvass @anusha-ragunathan

**Comment by duglin** [comment]
LGTM
build issues seem unrelated

**Comment by duglin** [comment]
@daehyeok the build error looks real:
```
plugin/backend_linux.go:265: nameref declared and not used
```

**Comment by anusha-ragunathan** [comment]
`nameref` is unused. so `_,  err := reference.ParseNormalizedNamed(name)` will do.

**Comment by daehyeok** [comment]
@anusha-ragunathan @duglin  sorry, I modified code again. I belive CI fails on powerpc, windwosRS1, z are not related this patch anymore.

**Comment by anusha-ragunathan** [comment]
call to `reference.ParseNormalizedNamed` is still required to check for correctly formulated reference names.

**Comment by daehyeok** [comment]
@anusha-ragunathan rechanged

**Comment by duglin** [comment]
LGTM

**Comment by cpuguy83** [comment]
`Upgrade` is mostly copied from `Pull`. Seems like we're missing this from `Pull` somehow:

```
if err := pm.config.Store.validateName(name); err != nil {
```
Which is where `name` comes in.

However I think this is only being verified because in `Pull` we are creating a new plugin and as such injesting a new name.
Here there is no naming change.

So I think this is ok.

LGTM

**Review by cpuguy83 — APPROVED** [review]

**Review by anusha-ragunathan — APPROVED** [review]

**Pull request merged**
