### PR TITLE
Move engine-api to docker

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes https://github.com/docker/engine-api/issues/379

This moves the `engine-api` repo code into docker.

The client is under `github.com/docker/docker/client` because the cli is under `api/client` and a top level client package seems like a good idea.  The types were moved into `api/types` so nothing really changes there.  

I kept the vendored code because swarmkit uses the engine-api code and is a dependency of docker so we need this merged first before i update the dep in swarmkit.

### CODE REVIEW

**Comment by vieux** [comment]
LGTM, please rebase :)

**Comment by justincormack** [comment]
LGTM after rebase.

**Comment by vdemeester** [comment]
@crosbymichael @icecrime @thaJeztah we need to ping contributors on all `docker/engine-api` PRs to migrate their PR in `docker/docker` and/or rebase their `docker/docker` PR to take into account this changes 👼

**Comment by stevvooe** [comment]
Wish we could have let this bake a day or two.

We still have the following problems:

1. How does one vendor the docker client without pulling in the whole docker project?
2. How do we maintain the separation between API types and internal types? These converged before and was one of the reasons behind the splits. How can we ensure these don't re-converge?
3. How can we ensure that the level of review in the client package is sufficient to maintain careful control of API-level fields?
4. Looks like all the issues have been deleted. I had a few proposals for fixing up things like Pull progress. What happened to those? Just gone from the Internet?

I guess memories are short...

**Pull request merged**
