### PR TITLE
1.11 Bash and Zsh completion cherry picks

### PR DESCRIPTION
**Pull request by thaJeztah**
This includes all Bash and Zsh cherry-picks for 1.11-rc3;

https://github.com/docker/docker/pull/21516 (396ffa2faf4b16bf6d6dbd813e967038bb2b4034)
https://github.com/docker/docker/pull/21517 (f8009d10bba6bb179466456bf5564883d5b7deac)
https://github.com/docker/docker/pull/21520 (a2958aa18f148ce2672b2f0c237c288d3f200add)
https://github.com/docker/docker/pull/21527 (5bfd29b9fbc97392d540013a8225671e2f83c407)
https://github.com/docker/docker/pull/21542 (93ffc2d9544742f1c78043fd449fe7e7ef59bbf3)
https://github.com/docker/docker/pull/21543 (ca2cca025579c92aaab0a27b6740c72f88788b1d)
https://github.com/docker/docker/pull/21546 (f3a27a6fac8d32a2930821a83bcceb750ff8070a)
https://github.com/docker/docker/pull/21547 (ff31f166f205432f07059dbce2b07e25a10abf1f)
https://github.com/docker/docker/pull/21548 (ca3ff89e56026d31ec0fdd2bf59b0db3ca5be3c1)
https://github.com/docker/docker/pull/21549 (b0235ffdddede003b3e125ffdef796a185e8a43e)
https://github.com/docker/docker/pull/21573 (aeaba46c2c411523fc03ce5fcdf51f50e14b80ce)
https://github.com/docker/docker/pull/21575 (63b29eda68683bad2e375fee97b4d106a5ca5a77)
https://github.com/docker/docker/pull/21579 (62475684b9cb09ba5cc3f2dd3b3ad88031b391ba)
https://github.com/docker/docker/pull/21580 (39d7ff233bbc2f333cce30124bfd6f52bba1ae2a)
https://github.com/docker/docker/pull/21584 (020998e24cc9bdf16204f1db18cf4886897c1541)
https://github.com/docker/docker/pull/21610 (e96d086afdb111fc4b587d4e82c857dbfec4e87e)
https://github.com/docker/docker/pull/21623 (39b9b63e364dc5e2bbc3e73f29b75f9de5c5dbf0)
https://github.com/docker/docker/pull/21645 (a2dbf7626c9950aab5049f0e485e053232be1e5f)

### CODE REVIEW

**Comment by icecrime** [comment]
Nice! LGTM

**Comment by moxiegirl** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by albers** [comment]
@thaJeztah There are only 7 PRs of mine in the list, not sure if this is correct.
* I think #21577 is missing.
* Does the `status/6-cherry-picked` label mean that a PR is already pulled in (e.g. #21515, #21484)?
* The earlier ones, #21256 and lower, did they get merged before branching off the RC?

**Comment by thaJeztah** [comment]
I think many of your PRs were already included in the previous RC, so the low number could be right. Look like I missed one #21577 indeed :disappointed: Yes, we use the "Cherry-Picked" label after its Cherry-picked into the bump branch.

https://github.com/docker/docker/pull/21256 was merged before we released RC1, so should be in the bump branch, which is branched from master just before the first RC is created

**Comment by thaJeztah** [comment]
@albers oh, just realized what happened with https://github.com/docker/docker/pull/21577 - I had it in here first, but wanted to only include the completion script changes, and do a separate cherry-pick PR for  all docs changes; I removed both commits from that PR instead of just the completion scripts. We'll include it in another cherry-pick PR before RC3 is created

**Comment by albers** [comment]
@thaJeztah Thanks for looking into this. So (almost) everything is all right :grinning:.

**Comment by albers** [comment]
@thaJeztah I diffed bash completion from _master_ and _bump_v1.11.0_ and found that #21577 is indeed the only change that's missing.

**Comment by thaJeztah** [comment]
@albers awesome, thanks for checking!

**Pull request merged**
