### PR TITLE
[19.03 backport] Added garbage collector for image layers

### LINKED ISSUE #38488: Images are removed from database even if cannot be delete from disk
**Description**
I did troubleshooting for docker/for-win#745 issue and find out that it actually happens on Linux too if layers are protected on way that root cannot remove them

**Steps to reproduce the issue:**
1. Check that we have one image on disk:
```
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              3f53bb00af94        13 days ago         4.41MB
```
2. Check that we can see only it on overlay2 folder:
```
# ls -l /var/lib/docker/overlay2/
total 44
drwx------ 3 root root  4096 Jan  4 00:06 a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3
```
3. Mark folder as immutable:
```
chattr +i /var/lib/docker/overlay2/a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3/
```
4. Try remove image:
```
# docker rmi alpine
Error response from daemon: remove /var/lib/docker/overlay2/a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3/diff: operation not permitted
```
**Describe the results you received:**
Image is removed from database but still exists on disk:
```
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

# ls -l /var/lib/docker/overlay2/
total 44
drwx------ 3 root root  4096 Jan  4 00:06 a35faa4237b8ee1d5fda926505326ad77ae70e8b8e38b8b9d62d133fa80eecc3
```

**Describe the results you expected:**
Images should be either only removed from database when they are successfully removed from disk or they should be marked as waiting for removal and removed when *imageService.Cleanup()* is called.

**Additional information you deem important (e.g. issue happens only occasionally):**
Related to #38401

Error message found from event log on combination of Windows Server 2016 + Docker 18.09:
```
Handler for DELETE /v1.39/images/5d4d99af0cf4 returned error: GetComputeSystems: The requested compute system operation is not valid in the current state.
```
if those 500 retries is not enough this is what happens on:
https://github.com/moby/moby/blob/ea60a87fcfc8b4592a5d2dec60f021c44ebe6a05/daemon/graphdriver/windows/windows.go#L295-L309

### PR DESCRIPTION
**Pull request by thaJeztah**
moved from https://github.com/docker/engine/pull/268

backport of

- [x] https://github.com/moby/moby/pull/39193 Added garbage collector for image layers
- [x] https://github.com/moby/moby/pull/39862 Implement code review comments in 39748
  - replaces https://github.com/moby/moby/pull/39748 Avoid using invalid value of cacheID on fail path
- [x] https://github.com/moby/moby/pull/39591 Add extra permission check in removal test
- [x] https://github.com/moby/moby/pull/39715 Unit test for getOrphan

Minor conflict because https://github.com/moby/moby/commit/072400fc4b8d6a38a2007d41072b765666a4c288 (https://github.com/moby/moby/pull/38377) is not in the 19.03 branch;

```patch
diff --cc internal/test/daemon/daemon.go
index bb8451db8c,4705d2f4ee..0000000000
--- a/internal/test/daemon/daemon.go
+++ b/internal/test/daemon/daemon.go
@@@ -60,16 -61,18 +61,31 @@@ type Daemon struct
        UseDefaultHost    bool
        UseDefaultTLSHost bool

++<<<<<<< HEAD
 +      id            string
 +      logFile       *os.File
 +      cmd           *exec.Cmd
 +      storageDriver string
 +      userlandProxy bool
 +      execRoot      string
 +      experimental  bool
 +      init          bool
 +      dockerdBinary string
 +      log           logT
++=======
+       id                         string
+       logFile                    *os.File
+       cmd                        *exec.Cmd
+       storageDriver              string
+       userlandProxy              bool
+       defaultCgroupNamespaceMode string
+       execRoot                   string
+       experimental               bool
+       init                       bool
+       dockerdBinary              string
+       log                        logT
+       imageService               *images.ImageService
++>>>>>>> 213681b66a... First step to implement full garbage collector for image layers

        // swarm related field
        swarmListenAddr string
```

**- What I did**
Added garbage collector for image layers

Closes #38488 and most probably #39247 too.
and with #38401 also https://github.com/docker/for-win/issues/745

**- How I did it**
Added logic which marks layers to be under removal by renaming layer digest folder to contain **-\<int\>-removing** suffix. That way we are able keep track that which layers are not anymore complete (=> which need to be re-downloaded if needed) and we are also able run clean up routine for those. 

**- How to verify it**
Reproduce issue like it is described on #38488
also notice bug with missing content on comment https://github.com/moby/moby/issues/38488#issuecomment-492801678

Run daemon on debug mode and stop it.

You will see log like this and orphan layer will disappear from disk.
```
DEBU[2019-05-17T02:22:21.349871543+03:00] start clean shutdown of all containers with a 15 seconds timeout... 
DEBU[2019-05-17T02:22:21.350859348+03:00] found 2 orphan layers                        
DEBU[2019-05-17T02:22:21.350918187+03:00] removing orphan layer, chain ID: sha256:3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b , cache ID: 5ccabfe0f839144bcbb30b7eae3d65e89fd93e34b411a9ba37b753c6cadc939c 
DEBU[2019-05-17T02:22:21.352871349+03:00] Removing folder: /var/lib/docker/image/overlay2/layerdb/sha256/3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b-0-removing 
DEBU[2019-05-17T02:22:21.353409212+03:00] Removing folder: /var/lib/docker/image/overlay2/layerdb/sha256/3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b-1-removing 
DEBU[2019-05-17T02:22:21.353901755+03:00] removing orphan layer, chain ID: sha256:3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b , cache ID: 4594ad5ca4f2ae9046141506d857fe9e94d68727809813d653b98353a43dd5fc 
DEBU[2019-05-17T02:22:21.356055301+03:00] Unix socket /var/run/docker/libnetwork/60b87c485747cb08641761e12ba27e169f4a9430efd4748121f1ce4d0fd3d536.sock doesn't exist. cannot accept client connections 
DEBU[2019-05-17T02:22:21.356174192+03:00] Cleaning up old mountid : start.             
INFO[2019-05-17T02:22:21.356225827+03:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
DEBU[2019-05-17T02:22:21.356871850+03:00] Cleaning up old mountid : done.              
DEBU[2019-05-17T02:22:21.357264017+03:00] Clean shutdown succeeded 
```

and if you do same test on Windows this is what you will see:
```
time="2019-05-16T23:31:11.505667200Z" level=debug msg="start clean shutdown of all containers with a 35 seconds timeout..."
time="2019-05-16T23:31:11.510504700Z" level=debug msg="found 1 orphan layers"
time="2019-05-16T23:31:11.511193900Z" level=debug msg="removing orphan layer, chain ID: sha256:cc83dc73fcbf0e8b0ce6bce79e23643e9ffc7773af69f831e7d1f2f5764d44b2 , cache ID: bc365c16a135afa6ee813b7f550d7723d135157a0080dc1c25489314f938b656"
time="2019-05-16T23:31:11.511193900Z" level=debug msg="hcsshim::GetComputeSystems - Begin Operation"
time="2019-05-16T23:31:11.512310200Z" level=debug msg="HCS ComputeSystem Query" json="{}"
time="2019-05-16T23:31:11.513192900Z" level=debug msg="hcsshim::GetComputeSystems - End Operation - Success"
time="2019-05-16T23:31:11.514189800Z" level=debug msg="hcsshim::DestroyLayer" path="C:\\ProgramData\\docker\\windowsfilter\\bc365c16a135afa6ee813b7f550d7723d135157a0080dc1c25489314f938b656-removing"
time="2019-05-16T23:31:11.678774400Z" level=debug msg="hcsshim::DestroyLayer - succeeded" path="C:\\ProgramData\\docker\\windowsfilter\\bc365c16a135afa6ee813b7f550d7723d135157a0080dc1c25489314f938b656-removing"
time="2019-05-16T23:31:11.678774400Z" level=debug msg="Removing folder: C:\\ProgramData\\docker\\image\\windowsfilter\\layerdb\\sha256\\cc83dc73fcbf0e8b0ce6bce79e23643e9ffc7773af69f831e7d1f2f5764d44b2-0-removing"
time="2019-05-16T23:31:11.687751900Z" level=debug msg="Clean shutdown succeeded"
```

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by alexanderadam** [comment]
Is there any progress or at least plans how to proceed on this?
If this is the PR for the backport, the garbage collector is already implemented in some version, right? May I ask in which version?

And should the PR fix the issue of [the huge `/var/lib/docker/` directory (described in this comment)](https://github.com/docker/cli/issues/942#issuecomment-667059653)?

Or will it at least fix the incorrect reporting of `docker system df` (I doubt it but I want to be sure)?

**Comment by olljanat** [comment]
@alexanderadam decission was that this will not released as patch so it will be included to next major version (20.xx I assume).

What comes to your issue it is very hard to say if this would help as I'm not familiar with user spaces.

**Comment by Netlims** [comment]
was this merged? , if so from which version is it working the windowfilter folder thing getting huge which is now solved suppousedly?

**Comment by olljanat** [comment]
@Netlims no and Docker 19.03.x versions are not supported anymore. Please update to Docker 20.10.x. All those contains this one.

**Comment by Netlims** [comment]
Hey @olljanat 
We are running 
Docker version 20.10.6, build b3766ff
and still encountering this issue, can you please maybe shed some light on this ?
or maybe direct me to a release note version page of this so i can research some my self

help is appreciated , thanks in advance! :)

**Comment by olljanat** [comment]
@Netlims this is just backport pull request. It is better to follow those links to original pull requests and issues linked to them. All those changes have been part of 20.10.0 and all versions after that.

When you say
> still encountering this issue,

you need to notice that there is multiple different issues on this area. The most critical one which these changes did solve 100% was this one https://github.com/moby/moby/issues/38488 because earlier we couldn't trust that same container image provides same result on all servers.

They partly solves also those disk usage challenges but now fully because there can be multiple different reasons why image/container layers removal fails in first place (e.g. anti-virus, Windows it selves, some 3rd party tool, etc locks those files). Also many of those does not release files before server reboot.

**Pull request closed without merging**
