### PR TITLE
Add TC to check dynamic subnet for ingress network

### PR DESCRIPTION
**Pull request by arkodg**
Needs to be rebased on top of https://github.com/moby/moby/pull/39953

### CODE REVIEW

**Comment by thaJeztah** [comment]
Rebased this one to see if https://github.com/moby/moby/pull/39953 and this one combined will make CI go green

**Comment by thaJeztah** [comment]
Not sure why x86 keeps failing; tests have completed successfully, but then it gets killed after 2 hours. Was thinking if this could be related to https://github.com/moby/moby/pull/39920, but not sure why it would fail only on this PR

https://ci.docker.com/public/job/moby/job/PR-39966/5/execution/node/187/log/

```
00:50:44.516  DONE 1223 tests, 43 skipped in 2257.616s
00:50:44.516  ---> Making bundle: .integration-daemon-stop (in bundles/test-integration)
00:50:44.516  ++++ cat bundles/test-integration/docker.pid
00:50:44.516  +++ kill 7271
00:50:51.057  umount: bundles/test-integration/root: mountpoint not found
00:50:51.057  +++ /etc/init.d/apparmor stop
00:50:51.057  Clearing AppArmor profiles cache:.
00:50:51.057  All profile caches have been cleared, but no profiles have been unloaded.
00:50:51.057  Unloading profiles will leave already running processes permanently
00:50:51.057  unconfined, which can lead to unexpected situations.
00:50:51.057  
00:50:51.057  To set a process to complain mode, use the command line tool
00:50:51.057  'aa-complain'. To really tear down all profiles, run the init script
00:50:51.057  with the 'teardown' option."
00:50:51.057  
02:00:06.451  Sending interrupt signal to process
02:00:06.481  Sending interrupt signal to process
```

**Comment by thaJeztah** [comment]
rebased https://github.com/moby/moby/pull/39953 and this one, in case there was a change/fix in master that wasn't yet in this branch

**Comment by thaJeztah** [comment]
Still failing; being killed after 2 hours. Could use some help on this one to figure out what's causing it; https://ci.docker.com/public/blue/organizations/jenkins/moby/detail/PR-39966/6/pipeline

**Comment by thaJeztah** [comment]
rebased; wondering if the failure was related to https://github.com/moby/moby/pull/40016

**Comment by thaJeztah** [comment]
still failing; something fishy going on 

@dperny @arkodg

**Comment by arkodg** [comment]
@thaJeztah I'm not a CI expert but putting the `make tests` is getting a `SIGTERM` after 1hr59min and the Jenkinsfile timeout is set to 2hrs https://github.com/moby/moby/blob/9732185e073789529ad285e7b97646b6ab840f8c/Jenkinsfile#L7, does that theory sound right @seemethere

**Comment by arkodg** [comment]
cc superadmin @tiborvass

**Comment by thaJeztah** [comment]
> I'm not a CI expert but putting the make tests is getting a SIGTERM after 1hr59min and the Jenkinsfile timeout is set to 2hrs

That's correct, but the test should take roughly 55 minutes to run, and on this PR it ends after 40 minutes;

```
00:40:43.713  DONE 1253 tests, 44 skipped, 2 failures in 2024.216s
```

And gets killed after 2 hours

**Comment by thaJeztah** [comment]
Actually, I see there's a NPE in a test; https://ci.docker.com/public/job/moby/job/PR-39966/9/execution/node/151/log/

```
00:37:28.660      --- FAIL: TestDockerSuite/TestEventsContainerEvents (1.19s)
00:37:28.660          suite.go:65: test suite panicked: runtime error: slice bounds out of range [:5] with capacity 4
00:37:28.660              goroutine 3978 [running]:
00:37:28.660              runtime/debug.Stack(0xc0026e3908, 0x1ad9bc0, 0xc0008100c0)
00:37:28.660              	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
00:37:28.660              github.com/docker/docker/internal/test/suite.failOnPanic(0xc00185e600)
00:37:28.660              	/go/src/github.com/docker/docker/internal/test/suite/suite.go:65 +0x57
00:37:28.660              panic(0x1ad9bc0, 0xc0008100c0)
00:37:28.660              	/usr/local/go/src/runtime/panic.go:679 +0x1b2
00:37:28.660              github.com/docker/docker/integration-cli.(*DockerSuite).TestEventsContainerEvents(0x2f7d7a8, 0xc00185e600)
00:37:28.660              	/go/src/github.com/docker/docker/integration-cli/docker_cli_events_test.go:89 +0x3c5
00:37:28.660              reflect.Value.call(0xc0000c4f00, 0xc0008036c0, 0x13, 0x1bfd18b, 0x4, 0xc000e8df30, 0x2, 0x2, 0xc00075c618, 0x40d903, ...)
00:37:28.660              	/usr/local/go/src/reflect/value.go:460 +0x5f6
00:37:28.660              reflect.Value.Call(0xc0000c4f00, 0xc0008036c0, 0x13, 0xc00075c730, 0x2, 0x2, 0xf, 0x0, 0x0)
00:37:28.660              	/usr/local/go/src/reflect/value.go:321 +0xb4
00:37:28.660              github.com/docker/docker/internal/test/suite.Run.func2(0xc00185e600)
00:37:28.660              	/go/src/github.com/docker/docker/internal/test/suite/suite.go:57 +0x2c2
00:37:28.660              testing.tRunner(0xc00185e600, 0xc0008dbea0)
00:37:28.660              	/usr/local/go/src/testing/testing.go:909 +0xc9
00:37:28.660              created by testing.(*T).Run
00:37:28.660              	/usr/local/go/src/testing/testing.go:960 +0x350
```

**Comment by thaJeztah** [comment]
hm... looks like there's a missing assert; https://github.com/moby/moby/blob/1fd0107d7f5402ae39781a03813265a103ab7ae2/integration-cli/docker_cli_events_test.go#L87-L89

(which doesn't explain the failure, but explains the panic)

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/40026 to prevent the panic

**Comment by thaJeztah** [comment]
Wait; why is this one now failing as well on vendor check?

```

[2019-10-03T15:13:59.478Z] The result of vndr differs
[2019-10-03T15:13:59.478Z] 
[2019-10-03T15:13:59.478Z]  D vendor/golang.org/x/sync/singleflight/singleflight.go
[2019-10-03T15:13:59.478Z] 
[2019-10-03T15:13:59.478Z] Please vendor your package with github.com/LK4D4/vndr.
```

**Comment by thaJeztah** [comment]
OK, looks like it's a problem on master; opened https://github.com/moby/moby/pull/40037 to fix it

**Comment by andrewhsu** [comment]
I kicked off a `Replay` on the last run, but with the jenkins timeout set to 3 hrs instead of 2 hrs: https://ci.docker.com/public/job/moby/job/PR-39966/15/

**Comment by thaJeztah** [comment]
> @thaJeztah I don't think its hanging but getting killed after the Jenkins Timeout of 2h, can we please extend it and retry

@arkodg see my earlier comment; it should _never reach the 2 hour limit_ https://github.com/moby/moby/pull/39966#issuecomment-537158754

**Comment by thaJeztah** [comment]
@andrewhsu download.docker.com is partially down, so we'll have to restart again after it's up again

**Comment by thaJeztah** [comment]
Kicked it again, as download.docker.com should be up again

**Comment by andrewhsu** [comment]
Hmm...looks like the [PR check hit the 2 hr timeout](https://ci.docker.com/public/job/moby/job/PR-39966/17/execution/node/149/log/):
```
00:42:24.678  === RUN   TestDockerSwarmSuite/TestSwarmVolumePlugin
00:43:11.289  === RUN   TestDockerSwarmSuite/TestUnlockEngineAndUnlockedSwarm
02:00:03.738  Sending interrupt signal to process
```

**Comment by arkodg** [comment]
@andrewhsu there is some issue with the latest `swarmkit` refpoint, that needs to be triaged,
just cherrypicking  the `ingress` network fix has no problems https://github.com/docker/engine/pull/402

**Comment by thaJeztah** [comment]
replaced by / included in https://github.com/moby/moby/pull/40309

**Pull request closed without merging**
