### PR TITLE
Add canonical import path

### PR DESCRIPTION
**Pull request by dnephin**
Internally all packages are imported as `github.com/docker/docker`, so the package statement should document this by using [canonical import paths](https://golang.org/doc/go1.4#canonicalimports).

`go build` will report an error when a package is used from a path that doesn't match the canonical path.

### CODE REVIEW

**Comment by tiborvass** [comment]
@dnephin need to change the swagger generator?

**Comment by cpuguy83** [comment]
ping @moby/moby-maintainers

**Comment by tianon** [comment]
It's really verbose to include it in every `.go` file, but IMO this is a good idea both now and if/when https://github.com/moby/moby/pull/35361 happens, and should help folks who put it at the wrong place figure out exactly what they need to change things to in order to fix their builds (and not end up with two copies of this repo cloned accidentally, for example).

So, TLDR; +1!

**Comment by thaJeztah** [comment]
Looks like the files generated by swagger need to be updated;

```
21:13:27 The result of hack/generate-swagger-api.sh differs
21:13:27 
21:13:27  M api/types/container/container_changes.go
21:13:27  M api/types/container/container_create.go
21:13:27  M api/types/container/container_top.go
21:13:27  M api/types/container/container_update.go
21:13:27  M api/types/container/container_wait.go
21:13:27  M api/types/error_response.go
21:13:27  M api/types/graph_driver_data.go
21:13:27  M api/types/id_response.go
21:13:27  M api/types/image/image_history.go
21:13:27  M api/types/image_delete_response_item.go
21:13:27  M api/types/image_summary.go
21:13:27  M api/types/plugin.go
21:13:27  M api/types/plugin_device.go
21:13:27  M api/types/plugin_env.go
21:13:27  M api/types/plugin_interface_type.go
21:13:27  M api/types/plugin_mount.go
21:13:27  M api/types/port.go
21:13:27  M api/types/service_update_response.go
21:13:27  M api/types/volume.go
21:13:27 
21:13:27 Please update api/swagger.yaml with any api changes, then 
21:13:27 run `hack/generate-swagger-api.sh`.
```

**Comment by thaJeztah** [comment]
Oh, never mind, I see @tiborvass already commented that :blush:

**Comment by AkihiroSuda** [comment]
We should not modify pb.go files

**Comment by tiborvass** [comment]
@dnephin I wonder if we really need to add the canonical import path on all files, or whether we could simply put it in the files at the root. Wouldn't that solve the issue of go-getting two copies?

**Comment by dnephin** [comment]
I don't think so. I think if you were to import any package outside the root you'd run into the same problem. I'm not sure if it needs to be in every file, or "at least one file per package", but it seems like it's more obvious if it's in every file. 

I'll test some things to confirm.

**Comment by dnephin** [comment]
Ok, I've reverted the change on generated files (swagger and `.pb.go`). Let's see if validation is happy now.

I looked at modifying the swagger-gen templates, the problem is getting the relative directory name to use in the canonical import path.

**Review by vdemeester — APPROVED** [review]
LGTM 🦁

**Review by cpuguy83 — APPROVED** [review]
LGTM

@tianon ?

**Comment by tianon** [comment]
LGTM :+1:

**Comment by thaJeztah** [comment]
Can we add a validation step in CI that checks if new files that were added have the canonical path set?

**Comment by dnephin** [comment]
yes, I'll look at adding that.

**Pull request merged**
