### PR TITLE
Update doc: "docker create" must specify a command

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by xuhdev** [comment]
OK signed. Thanks!

**Comment by estesp** [comment]
Actually, `[COMMAND]` is optional as the command-line reference docs show.  The image being created from may already have a command or entrypoint defined.  In this specific case, the command is already set up for you in the image: https://registry.hub.docker.com/u/training/postgres/dockerfile/

**Comment by xuhdev** [comment]
It's not critical, but it is just better to replace the command with a dummy one. The reason is that if someone accidentially start the data container, there will be no additional process to change the data in the container.

**Comment by SvenDowideit** [comment]
@xuhdev thats a really good explanation of why you've done it, and I think you're right, especially for something like `postgres` - where the default `COMMAND` / `ENTRYPOINT` would start a complete new postgres server!

Could you add that explanation to your change?

**Comment by estesp** [comment]
Ugh.. I looked more at your PR title than the context of where you are changing the code.  Just FYI--for busy people, a brief title that gives a closer representation of what you are doing is good, and an initial commit comment that explains can be helpful too! :) Other than my own personal problems, @SvenDowideit is exactly right.. for a data container it does make sense to replace the entrypoint!

The other thing I've seen in blogs documenting data volumes is that usually people don't understand why it's **not** recommended to use a "small" image like busybox but rather the same image as your runtime like this example is showing; don't know if this doc should be updated with the reasoning that I've seen elsewhere, but basically if your runtime container and data container are based from the same image, then all those layers are shared, but if the data container is "some other image", then you will actually waste more space for even the "small" content of your data volume image.

**Comment by xuhdev** [comment]
Sorry for the confusion, now updated :)

@estesp I agree that using the same image can save space, but I don't think a `busybox` image is really large for most cases... Besides, if the data container and the runtime container are built on the same image, some changes i.e. upgrading from runtime container from an old version to a new version without touching the data container actually leads to larger space usage.

**Comment by jfrazelle** [comment]
LGTM, I think there has been a lot of back and forth but someone else can feel free to make another patch explaining it will also use the entrypoint if otherwise, perhaps @SvenDowideit

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
