### PR TITLE
Pre bday updates

### PR DESCRIPTION
**Pull request by moxiegirl**
Pulling in several changes for the birthday. @tianon changes to hack and his eval hits.  Also finally, finally, @thaJeztah's css stylings go live.

Brining in the ubuntu updates and installation menu fixes.
Last second tweak to the Kitematic location in the file to clarify the choices.

### CODE REVIEW

**Comment by moxiegirl** [comment]
@jfrazelle this is failing DCO because of those same commits that keep causing problems on docs.  I think it will happen until we release.

Can you give me a LGTM anyway?

**Comment by spf13** [comment]
LGTM

**Comment by thaJeztah** [comment]
Yeaaah! Thanks, @moxiegirl and good luck with the party.

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
