### PR TITLE
Add Morgan Bauer to docker/docker/MAINTAINERS

### PR DESCRIPTION
**Pull request by duglin**
Per vote on maintainers mailing list

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by runcom** [comment]
LGTM :)

**Comment by icecrime** [comment]
LGTM :tada:

**Comment by MHBauer** [comment]
:astonished:

**Comment by tiborvass** [comment]
LGTM !

**Comment by vdemeester** [comment]
LGTM 🐳

**Comment by calavera** [comment]
:space_invader: LGTM :space_invader:

**Comment by duglin** [comment]
:santa:

**Comment by thaJeztah** [comment]
Oh! Missed it!

Congrats @MHBauer!! Welcome!

**Pull request merged**
