### PR TITLE
Fix failure to get containers when deleting a layer

### PR DESCRIPTION
**Pull request by darstahl**
**- What I did**

Fix errors like:
```
01:05:33 
01:05:33 Command: d:\CI\CI-78bcec9\binary\docker.exe rm -fv 7f7995ecef82 3550b04634cf
01:05:33 ExitCode: 1, Error: exit status 1
01:05:33 Stdout: 7f7995ecef82
01:05:33 
01:05:33 Stderr: Error response from daemon: Driver windowsfilter failed to remove root filesystem 3550b04634cf62135f44071b1a0cb727c406fd6557e76f38d27711cfed8a4e0f: unexpected value returned from hcs
01:05:33 
01:05:33 
01:05:33 Failures:
01:05:33 ExitCode was 1 expected 0
01:05:33 Expected no error
```
when deleting layers. Introduced in https://github.com/docker/docker/pull/28141

**- How I did it**

Keep retrying the GetContainers on the known error, just go ahead and delete if it happens more than 5 times though.

**- How to verify it**

Hope it doesn't show up in CI logs. Edit: Looks like it's fixed!

~~Needs a vendor.~~

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by darrenstahlmsft** [comment]
No issues seen in CI. Needs a vendor, but it's confirmed to fix the issue 👍

**Comment by darrenstahlmsft** [comment]
@jhowardmsft PTAL

**Comment by jhowardmsft** [comment]
Yup, looks good. LMK when you've got the revendor in and we can move it to design review.

**Comment by darrenstahlmsft** [comment]
@jhowardmsft vendor is in already 😄

**Comment by jhowardmsft** [comment]
I edited my comment ^^ 😇

**Comment by darrenstahlmsft** [comment]
Oops, I was too quick to see the edit 😇 

Fixed now

**Comment by jhowardmsft** [comment]
LGTM. Thanks @darrenstahlmsft

**Comment by jhowardmsft** [comment]
@thaJeztah FYI This is a critical 1.13 fix

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
