### PR TITLE
[17.04] Cherry-pick: Windows: Fix Docker hanging with named pipes and stdin

### LINKED ISSUE #31922: Docker hanging with named pipes and stdin
**Description**

When the CLI is connected to the daemon trough a named pipe (either directly or trough a proxy, like with Docker for Windows), and some content is sent trough stdin, on certain occasions, the container hangs trying to read data (this is a timing related issue).

This is the result of a bug in Microsoft/go-winio traced back by @dgageot and me from the Docker for Windows team. We fixed the issue, and a PR is currently pending there: https://github.com/Microsoft/go-winio/pull/43. This fix should be ported to docker as soon as possible, as it is the source of some tricky problems on Docker for Windows

**Steps to reproduce the issue:**
1. Install Docker for Windows
2. Run the following script: `for i in {0..100}; do echo $i;  dd if=/dev/zero bs=2 count=1 | docker run -i --rm dockerpinata/tini //sbin/tini -- timeout -t 10 sh -c "dd bs=2 of=/null" || break; echo; done`
3. If the scripts exit before its 100nth iteration, it means that the timing condition where the read hangs has occured

**Describe the results you received:**
The script hangs on reading stdin content

**Describe the results you expected:**
The script should run fine

**Additional information you deem important (e.g. issue happens only occasionally):**
This is a timing related issue, due to a bug in Microsoft/go-winio

**Output of `docker version`:**
```$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

(version mismatch does not mean anything, the problem happens with retail versions of Docker for Windows as well)

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: MJZ2:LTGZ:UAQQ:ONIY:EFWJ:2PW3:5KQ5:EKY2:624H:5QXP:SJ3P:7FVD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-03-17T16:28:31.009191Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Easy to exhibit with Docker for Windows, we expect the problem to also occur when connecting locally to a Windows server Docker engine using named pipes.

### PR DESCRIPTION
**Pull request by vdemeester**
Fixes #31922

cherry-pick of #31962

Vendor a fork of Microsoft/go-winio that has this PR (https://github.com/Microsoft/go-winio/pull/43)
merged

/cc @vieux @thaJeztah @dgageot 

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by vdemeester** [comment]
experimental timed out at the cross compilation phase 😱

**Comment by vieux** [comment]
@vdemeester let's try again

**Comment by vieux** [comment]
LGTM ping @tonistiigi

**Comment by dgageot** [comment]
\0/

**Review by thaJeztah — APPROVED** [review]
LGTM - this'll go into rc2

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
