### PR TITLE
Zombie package

### PR DESCRIPTION
**Pull request by siennathesane**
This PR is to address issue #11529. I'm not sure if it is core functionality that should be addressed within the daemon or as a package, so it's under `pkg/` for right now, as that seemed like an okay place to put it. I'm a new contributor, so I'm not sure how this should be implemented just yet.

It adds three functions:
Executor: arbitrary shell executor.
SignalHandler: this will handle all incoming signals and clean up things accordingly.
ChildReaper: will clean up every single process that is a child process.

Some things to note.
- It passes the unit tests when executed manually, however it has issues with the `hack/make.sh test-unit` functionality. I think this is due to the fact I have to send signals in order to test it's functionality, which interrupts the script. I didn't put a whole lot of effort into figuring out a workaround outside of just commenting them out. However, it's at the end of the package list, so in theory it shouldn't interfere with the results.
- `ChildReaper`, if utilised, will loop through every process that is running. It provides a custom `Exit` structure with the PID and its exit status, so if something isn't exited cleanly, it can be processed downstream.
- The `MonitoredPids` code is only a framework, based off the discussion in the issue. I'm not actively monitoring processes, but if there were processes to be monitored, the framework is there from the beginning.

I figured this is just a starting point to get the issue rolling to get this functionality implemented. I was going to write my own `init` when I stumbled across the issue, so I'm hoping by working with the Docker team, the issue can be resolved as part of the core functionality.

@tiborvass

### CODE REVIEW

**Comment by calavera** [comment]
I don't think we should merge a package that's not used. We should aim to have at least a usage case in this PR.

**Comment by mynameismevin** [comment]
I agree on that statement. As the purpose of the PR was to address proper signal handling and zombie processes, where should this be implemented?

**Comment by LK4D4** [comment]
@mynameismevin I agree that it's weird to merge unused `pkg`. I think you can post it as separate package in your own repo and then vendor it when you need it in docker. It'll be easier for everyone.

**Pull request closed without merging**
