### PR TITLE
Adding gccgo option to the build

### PR DESCRIPTION
**Pull request by brahmaroutu**
Addresses #9207

Signed-off-by: Srini Brahmaroutu srbrahma@us.ibm.com

### CODE REVIEW

**Comment by jfrazelle** [comment]
so what we should do is, and I hope @tianon agrees, much like we run make cross to cross compile and test that on all prs we should have a make gccgo so we are sure we never break this.

**Comment by brahmaroutu** [comment]
This change is tested on ppc64 for native compilation along with prereqs (gccgo compiled for go1.4 support, etc) and works well. This change does not impact todays build process.

**Comment by brahmaroutu** [comment]
@unclejack @duglin @vbatts @crosbymichael  Please refer to step-by-step changes we want for integrating ppc64 into CI pipeline #9207

**Comment by inatatsu** [comment]
@brahmaroutu Shouldn't we use `s/IAMSTATIC string/` instead of  `s/IAMSTATIC bool/` since PR #10154 has been merged into the master?

**Comment by brahmaroutu** [comment]
@inatatsu Thanks for the review. PR is updated.

**Comment by brahmaroutu** [comment]
@jfrazelle based on you comment I did a native build on X86 (I am not pursuing cross compilation) 
I have a experimental branch https://github.com/brahmaroutu/docker/compare/gccgo_x86 that builds docker binary along with gccgo and gccgo tools using project/gccgo-image/Dockerfile.
I have run tests and only few tests are failing because docker.io is unreachable for some reason, etc. I am looking into those failures.

**Comment by crosbymichael** [comment]
@tianon do you think this should be a separate build target like `dynbinary` ?

**Comment by tianon** [comment]
This still works in the same way that caused us to turn down the previous attempts. :disappointed:

See #8833, #8812, #8325.

We had quite a few issues with generated (or in this case, procedurally-modified) Go code.

**Comment by jfrazelle** [comment]
oh ya we had to revert some of those, who do we future proof/make it work

**Comment by brahmaroutu** [comment]
@tianon I am trying to make it such that the normal path that is used to build docker should not change. Only platforms where gccgo is necessary, will take the gccgo path.

**Comment by tianon** [comment]
I know, I can see that, and I don't disagree with that approach.  What I'm
wary of is the fact that it still requires changing/generating Go source
code from a shell script, which is what caused headaches previously.

**Comment by duglin** [comment]
@tianon if I understand your comment correctly, you're concerned about a script modifying go code, right?  And that can be worrisome.  But, as I understand it, the -X option isn't supported by gccgo so we need to find some other way to get these values into the code. 

One option, and at first this may seem weird, is to actually remove our use of the -X option from both go and gccgo build paths.  In other words, make it so that these modifications to the go code happens in all cases.  This has the benefit of either working or failing no matter how we choose to build the code. It, in a way, makes it a less brittle solution because it will be tested every single time we do a build.

If not that, then I'm wondering if you have any suggestions on how to make progress here?

**Comment by tianon** [comment]
That's exactly what that previous PR did that had to be reverted because it
caused problems with the build, specifically related to the fact that it
was modifying/creating ".go" files.  Even if we add them to ".gitignore" to
make sure they're not checked in, it's still dangerous because they're
still around and Go won't be ignoring them, so if we ever have to change
them (filename, structure, location), the migration becomes painful for
_every contributor_ instead of just fixing one script that's entirely
checked in.

**Comment by brahmaroutu** [comment]
@tianon @duglin  I have pushed out the code that will moves dockerversion to an autogenerated folder  and I added it to .gitignore  I have followed the code from #8325 by @mwhudson 
Please review.

**Comment by tianon** [comment]
I like the new approach (having a separate `autogenerated` folder that's gitignored completely and blown away for every single build).  That will help protect us from "moving" issues we might run into later (like we hit last time).

I'm not a fan of copying the part of #8325 where we have the exact same Go code copied in a ton of places with just a few values changed.  #8812 is where I cleaned that part up, but it didn't merge because we just backed out of the entire autogenerated code bits instead -- I'd much rather see us normalize those generated files in a single place than have the error-prone copy/pasta in multiple files with the same purpose.

It might also be helpful to have the `autogenerated`/"remove `-X`" changes in a separate PR so that they're not necessarily coupled to "support GCCGO" and I think we'll be able to merge them more quickly that way since that'll be a smaller change.

**Comment by brahmaroutu** [comment]
Thanks @tianon, I am working on it.

**Comment by brahmaroutu** [comment]
Please note that PR #10665 precedes this. I will rebase this PR once that other PR is approved and merged.

**Comment by vbatts** [comment]
it seems like there is a case for `go:generate` from go1.4, but that would be a version requirement. Are we completely opposed to generated source? What if there is a default source checked in, and the paths are added to `.gitignore`, then the autogenerated source would clobber, but not get checked in. 
This way, a simple `go build` code still reap results, but an official build would have the version, sha-sum, etc.

Thoughts?

**Comment by brahmaroutu** [comment]
@jfrazelle Can we please close this, I will have a different PR (for arch/distro support), as 10665 is now merged.

**Pull request closed without merging**
