### PR TITLE
Display `internal` flag on `network inspect`

### PR DESCRIPTION
**Pull request by chenchun**
Also adds internal network tests for bridge network
Depends on https://github.com/docker/engine-api/pull/47

Signed-off-by: ramichen ramichen@tencent.com

### CODE REVIEW

**Comment by vdemeester** [comment]
Make sense :stuck_out_tongue:.
Related to https://github.com/docker/engine-api/pull/47.

LGTM 🐵

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
@vdemeester wondering; should we change the vendor-check to a separate CI type? (Like the DCO) Then we can still check the results of the other builds before the vendor is updated

**Comment by vdemeester** [comment]
@thaJeztah yep, that's might be an idea :stuck_out_tongue:

**Comment by runcom** [comment]
need rebase :(

**Comment by chenchun** [comment]
Thanks for your reminder. Waiting for vendoring in https://github.com/docker/engine-api/pull/47. After that I'll do rebase.

**Comment by cpuguy83** [comment]
Heads up, you'll need to update the docs since this will go into API v1.23 now, I think.

**Comment by thaJeztah** [comment]
@cpuguy83 we could treat it as a bugfix, but I'm fine if it ends up in 1.11 as well. Not sure if it's needed for (e.g.) Swarm

**Comment by thaJeztah** [comment]
Alright, I checked, and it's not a requirement for Swarm, so should probably go into 1.11

**Comment by thaJeztah** [comment]
@chenchun is this currently a blocking issue for your use-case?

**Comment by chenchun** [comment]
No, it's not. I'm fine with 1.11.

**Comment by thaJeztah** [comment]
Cool, thanks!

**Comment by vdemeester** [comment]
@chenchun needs a rebase :sweat_smile:

**Comment by chenchun** [comment]
@vdemeester should I do vendoring latest docker-engine myself?

**Comment by vdemeester** [comment]
@chenchun ah you're right, we didn't create a new tag on `engine-api` yet. Let's wait for that before updating vendor then.

**Comment by icecrime** [comment]
@chenchun Still needs a rebase, sorry :crying_cat_face:

**Comment by vieux** [comment]
@chenchun this one will be very useful to us :)

**Comment by chenchun** [comment]
Sorry, I was on a train to go home to enjoy New Year Festival. Rebased now.

**Comment by cpuguy83** [comment]
:( needs another one.
I can carry if you like.

**Comment by thaJeztah** [comment]
Weird errors on WindowsTP4 https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/637/console

I'll restart

**Comment by cpuguy83** [comment]
LGTM moving to docs review.

**Comment by vdemeester** [comment]
LGTM 🐭

**Comment by thaJeztah** [comment]
LGTM! Thanks @chenchun :+1:

**Pull request merged**
