### PR TITLE
hack/make.ps1: don't rely on GO_VERSION

### PR DESCRIPTION
**Pull request by kolyshkin**
This removes the last use of `ENV GO_VERSION` which happened to be in `hack/make.ps`. Once this is merged, we can remove `ENV GO_VERSION` from the Dockerfile.

Apparently one can't modify both `Dockerfile` and `hack/make.ps1` in a single commit (although I fail to understand why), so Dockerfile remains intact for now.

### CODE REVIEW

**Comment by kolyshkin** [comment]
OK, looks like it didn't work only because this PR modified both `Dockerfile` and `hack/make.ps1` in a single commit, which created some sort of access problem for Dockerfile (don't ask why). Split into two commits to make Windows CI happy again.

**Comment by kolyshkin** [comment]
OK, it looks like one can not patch both `Dockerfile` and `hack/make.ps1` in a single PR. Removing the Dockerfile patch.

**Review by lowenna — APPROVED** [review]
LGTM

**Review by johnstep — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Pull request merged**
