### PR TITLE
Fatal info not identical with actual chmod intent

### PR DESCRIPTION
**Pull request by lixiaobing1**
modify Fatal info to be identical with actual chmod intent.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by lixiaobing10051267** [comment]
@thaJeztah @vdemeester Is there docker1.12 deb version to download? I can't download with apt-get, thanks.

**Comment by thaJeztah** [comment]
@lixiaobing10051267 the `.deb` can be found here; http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

You can also download just the binaries, but they are statically linked https://docs.docker.com/engine/installation/binaries/

**Comment by lixiaobing10051267** [comment]
@thaJeztah thanks very much

**Pull request merged**
