### PR TITLE
Add bash completion for `service {create,update} --group-{add,rm}`

### PR DESCRIPTION
**Pull request by albers**
Ref: #25317
ping @sdurrheimer for zsh completion

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by albers** [comment]
@cpuguy83 would you mind taking a look at this?

**Comment by cpuguy83** [comment]
LGTM

**Comment by albers** [comment]
@cpuguy83 Thanks Brian!

**Pull request merged**
