### PR TITLE
use t.Fatal() to output the err message and fix typo

### PR DESCRIPTION
**Pull request by fate-grand-order**
**- What I did**
1.use t.Fatal() to output the err message where the values used for formatting text does not appear to contain a placeholder
2.use errors.New() to return err message
3.fix misspell "semantically"
**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by cpuguy83** [comment]
```
09:08:09 These files are not properly gofmt'd:
09:08:09  - api/types/filters/parse_test.go
09:08:09  - builder/dockerfile/dispatchers_unix.go
09:08:09 
09:08:09 Please reformat the above files using "gofmt -s -w" and commit the result.
```

**Comment by thaJeztah** [comment]
Also, can you update the commit message and PR description to better describe the change (it's not really removing redundant code)

**Comment by fate-grand-order** [comment]
I have updated the PR, please review it again. Thinks! @thaJeztah @cpuguy83

**Review by thaJeztah — APPROVED** [review]
changes LGTM

can you update your sign-off to use your actual name? 
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by Helen-Xie** [comment]
oh, sorry. I will update it.

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Pull request merged**
