### PR TITLE
Windows [TP4] Trap Hyper-V exec failure

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

This traps a known issue in TP4 with Hyper-V containers and docker exec and don't end up logging an incomprehensible error message.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @jhowardmsft, I see there's a vendor update in there, could you move that to a separate commit? (i.e. one commit for the vendor-update and one for the other changes). Sorry for being a PITA there :relaxed:

**Comment by jhowardmsft** [comment]
@thaJeztah Ah, I can't.... This changes the return parameters of the function in HCSShim, so both need to go in at the same time. Sorry.

**Comment by thaJeztah** [comment]
@jhowardmsft it's okay to have them in the same PR, just in a separate commit

**Comment by jhowardmsft** [comment]
Right, sure, I can do that. (Just don't believe I've ever seen that before on the docker project).

**Comment by thaJeztah** [comment]
Vendor updates are normally split in to the vendor itself, and the code changes related to the vendor update, just picking a random one; https://github.com/docker/docker/pull/17056/commits

**Comment by jhowardmsft** [comment]
No prob. Will do this in the morning :) You should be asleep though!

**Comment by thaJeztah** [comment]
@jhowardmsft actually in SF for two weeks, almost over, I'll be heading home Saturday

**Comment by jhowardmsft** [comment]
@thaJeztah Split :)

**Comment by thaJeztah** [comment]
:scissors: :scissors: <3 thanks @jhowardmsft

**Comment by crosbymichael** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
\o/

**Pull request merged**
