### PR TITLE
11610 split up commands

### PR DESCRIPTION
**Pull request by joeygibson**
I split out all the commands and helper functions into appropriately-named files, and removed commands.go. All the existing tests pass, and all the commands I worked with still worked correctly. 

Several commits were made to commands.go in master since late on 03/22 when I started working on this. I took the updated functions in commands.go and moved those into their new homes, which, again, makes all the tests pass.

### CODE REVIEW

**Comment by duglin** [comment]
@joeygibson thanks a ton for this.  Can you do me a favor and squash you commits down to one?

The error in the testing doesn't seem related to your change.

**Comment by joeygibson** [comment]
I tried to squash them (`git rebase -i HEAD^2`, leave the first as pick, and the second as squash), but when I do, I get this:

error: could not apply 76bfa4f... First ten split out

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply 76bfa4fd4459c6db9bdb8700ce328d622b44ffe7... Split out commands.

**Comment by duglin** [comment]
I suspect its because there's a conflict.  This issue/PR is gonna be a real tricky one.  While the code change itself is fairly straight-forward, due to the number of code changes going in this week I bet there will be merge conflicts popping up a lot (as I was typing this another PR just came by with a change to this same file :-) ).  This is the kind of change that's best done during non-peak hours.

If you're game, we can try to get this change in quickly later tonight - I noticed you were working late eastern time last night so I thought perhaps we could try tonight?  You may need to redo some of it though given how things have changed.  You can ping one of us on docker-dev irc if/when you're ready as we'll probably need to ask maintainers to avoid merging in PRs that hit this code until we're done.  Make sense?

**Comment by joeygibson** [comment]
Yeah, we can try again tonight, probably after 10:00 PM EDT. When I saw 10 or so commits come in while I was working last night, I was a bit disheartened, but once I realized that all I had to do was, essentially, re-extract those functions that were changed by the commits, it was relatively painless.

**Comment by duglin** [comment]
ok cool - I should be on irc, id: duglin  just ping me when you're ready.  and thanks!

**Comment by cpuguy83** [comment]
Thanks @joeygibson 
I was looking at this earlier this morning and was lik `ugh... rough rebase`

**Comment by LK4D4** [comment]
@joeygibson There shouldn't be merge commits in your commit list.
@duglin @joeygibson Also pls note that client code is pretty sensible for windows, so look at windows check too.
Thanks a lot

**Comment by duglin** [comment]
@joeygibson I'm on docker-dev (duglin) when you're ready.

**Pull request closed without merging**
