### PR TITLE
docker restarts running OR stopped containers

### PR DESCRIPTION
**Pull request by sallyom**
Signed-off-by: Sally O'Malley somalley@redhat.com

### CODE REVIEW

**Comment by coolljt0725** [comment]
@sallyom  I think you also should change here
https://github.com/docker/docker/blob/master/api/client/restart.go#L16
<pre><code>$ docker restart --help

Usage:  docker restart [OPTIONS] CONTAINER [CONTAINER...]

Restart a running container

  --help=false       Print usage
  -t, --time=10      Seconds to wait for stop before killing the container</code></pre>

**Comment by runcom** [comment]
There are more to be changed also:
```
runcom @ fedora ~/koding/docker ‹master› ag -i "Restart a running container"

api/client/restart.go
16:	cmd := Cli.Subcmd("restart", []string{"CONTAINER [CONTAINER...]"}, "Restart a running container", true)

man/docker-restart.1.md
5:docker-restart - Restart a running container

man/docker.1.md
276:  Restart a running container

contrib/completion/fish/docker.fish
282:complete -c docker -f -n '__fish_docker_no_subcommand' -a restart -d 'Restart a running container'

docs/reference/commandline/restart.md
16:    Restart a running container

docker/flags.go
49:	{"restart", "Restart a running container"},
```

**Comment by sallyom** [comment]
@runcom @coolljt0725 ok, will do!

**Comment by runcom** [comment]
ping @thaJeztah what about just `Restart a container`? :smile:

**Comment by sallyom** [comment]
'Restart a container' makes sense to me, I'll wait for confirmation from @thaJeztah

**Comment by thaJeztah** [comment]
Yes, "restart a container" SGTM too, plain and simple :-)

**Comment by sallyom** [comment]
@runcom @thaJeztah @coolljt0725 happy to help!

**Comment by thaJeztah** [comment]
Thanks, and happy to have you helping! LGTM

**Comment by runcom** [comment]
@sallyom thank you! go files LGTM ping @thaJeztah

**Comment by thaJeztah** [comment]
ping @SvenDowideit @moxiegirl for the merge :+1:

**Comment by moxiegirl** [comment]
LGTM!

**Comment by calavera** [comment]
LGTM

**Pull request merged**
