### PR TITLE
Bump notary version to v0.3.0-RC1

### PR DESCRIPTION
**Pull request by cyli**
This PR mainly bumps the notary version up to v0.3.0-RC1.

There are 2 Notary API changes relevant to Docker in this change:
- `NotaryRepository.Update` now returns just an error
- `NewNotaryRepository` now takes a trust pinning configuration - we are just providing an empty one here, so that behavior does not change (TOFU is enabled), but a future PR should probably add trust pinning configuration to Docker itself (to only trust roots signed by a particular CA, or to otherwise disable TOFU)

This PR also removes the pkcs11 tag for Dockerfile.s390x as per #22007, since that depends upon GCCGo 5.3, which supports the Go 1.4 standard library.  Notary + pkcs11 (the yubikey support) requires an interface that was added in Go 1.5.

cute bunny

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

**Comment by cyli** [comment]
(just rebased - also bump :)  once this gets merged we have another RC we'd like to bump to, but would love to split this until multiple PRs because the dependency changes are fairly large)

**Comment by LK4D4** [comment]
LGTM

**Comment by cyli** [comment]
@LK4D4 Thank you!

**Pull request merged**
