### PR TITLE
ContainerCreate shouldn't return warnings=nil. Fix #38222

### LINKED ISSUE #38222: Response for container create has null value for non-nullable field
**Description**

Docker API returns null value for Warnings field.

According to a definition it probably should never be null. It has `x-nullable: false

https://github.com/moby/moby/blob/master/api/swagger.yaml#L4659-L4676

**Steps to reproduce the issue:**

1. Send correct, /containers/create request to API https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate
2. Check response

Example response's body:
```json
{
    "Id": "6ce9cb39c1d6a905c0fc7909235b74491d5a0f184ff097bb73ffe9a30cd7743a",
    "Warnings": null
}
```

instead of:
```json
{
    "Id": "6ce9cb39c1d6a905c0fc7909235b74491d5a0f184ff097bb73ffe9a30cd7743a",
    "Warnings": []
}
```

### PR DESCRIPTION
**Pull request by dsseng**
**- What I did**
I've fixed #38222.

**- How I did it**
If warnings == `nil`, create an empty slice to avoid bug.

**- How to verify it**
See #38222.

**- Description for the changelog**
Fix ContainerCreate output (fix #38222)

**- A picture of a cute animal (not mandatory but encouraged)**
default

### CODE REVIEW

**Comment by cpuguy83** [comment]
@sh7dm Thanks for the PR.

Note that all commits must have the DCO sign-off (`git commit -s` -- little `s`). Looks like these commits can all be squashed into one, though.

Until DCO is in order, we can't really review this.

**Comment by sh7dm** [comment]
@cpuguy83 how can I signoff an old commit?

**Comment by cpuguy83** [comment]
Probably you should squash commits:
```
git rebase -i HEAD~8
```

From there set all but the first commit to squash (assuming I got that number right... should just be your commits).

Then do the sign-off:

```
git commit --amend -s --no-edit
```

And force push:

```
git push -f origin fix/empty-warnings
```

**Comment by cpuguy83** [comment]
@sh7dm Are you still having an issue doing this?

**Comment by thaJeztah** [comment]
ping @sh7dm were you still working on this?

**Comment by sh7dm** [comment]
@thaJeztah no, I'm too busy now, but I will be able to continue later, but I need some help

**Comment by thaJeztah** [comment]
@sh7dm these are the steps to squash your commits, and fix your sign-off :

1. Make sure your remotes are up to date

    Assuming your remotes are named `upstream` (the remote pointing to this repository) and `origin` (the remote pointing to your own fork);


    ```
    git fetch upstream -v
    git fetch origin -v
    ```

2. Start an interactive rebase:

    ```
    git rebase -i upstream/master
    ```

    This should open your default editor and show all commits of your PR:

    ```
    pick 6cc56818b9 ContainerCreate shouldn't return warnings=nil. Fix #38222
    pick 3abc98c4a6 ContainerCreate shouldn't return warnings=nil. Fix #38222
    pick 1567ffcd02 Fix build error
    pick f7efa86e6d Fix build error

    # Rebase cbb885b07a..793267e9ca onto cbb885b07a (4 commands)
    ```

3. Mark commits to be squashed

    Change the `pick` on every line, except for the first one, to `s` (or `squash`, but `s` is less typing :joy:)

    ```
    pick 6cc56818b9 ContainerCreate shouldn't return warnings=nil. Fix #38222
    s 3abc98c4a6 ContainerCreate shouldn't return warnings=nil. Fix #38222
    s 1567ffcd02 Fix build error
    s f7efa86e6d Fix build error

    # Rebase cbb885b07a..793267e9ca onto cbb885b07a (4 commands)
    ```

4. Save the file and exit your editor

5. Cleanup the commit message, and fix sign-off

    After saving the file (in the step above), git will now open your editor _again_, this time to allow you to clean up the combined commit message a bit (lines starting with `#` are comments, so you can ignore those);

    ```
    # This is a combination of 4 commits.
    # This is the 1st commit message:

    ContainerCreate shouldn't return warnings=nil. Fix #38222

    Signed-off-by: sh7dm <d3dx12.xx@gmail.com>

    # This is the commit message #2:

    ContainerCreate shouldn't return warnings=nil. Fix #38222

    # This is the commit message #3:

    Fix build error

    Signed-off-by: sh7dm <d3dx12.xx@gmail.com>

    # This is the commit message #4:

    Fix build error

    Signed-off-by: sh7dm <d3dx12.xx@gmail.com>
    ```

    We probably only need the first commit-message (and sign-off);

    While you're editing; could you also change `sh7dm` to your _real name_ (Dmitry Sharshakov) in the sign-off? 

    ```
    ContainerCreate shouldn't return warnings=nil

    Fix #38222

    Signed-off-by: Dmitry Sharshakov <d3dx12.xx@gmail.com>
    ```

6. Save the file and exit your editor

7. _Force push_ your changes

    After a rebase, you need to _force_ push your changes. After pushing, this PR should automatically update:

    ```
    git push -f origin
    ```

8. You're done :)

**Comment by thaJeztah** [comment]
ping @sh7dm 🤗

**Comment by kolyshkin** [comment]
LGTM but needs to be squashed

**Comment by tiborvass** [comment]
Carried in https://github.com/moby/moby/pull/38924

**Pull request closed without merging**
