### PR TITLE
integration-cli: fixups

### PR DESCRIPTION
**Pull request by runcom**
- Fix those `autogenerated` lines because func was missing the pointer receiver

```
08:49:22 PASS: docker_cli_network_unix_test.go:1188: DockerNetworkSuite.TestDockerNetworkUnsupportedRequiredIP  1.567s
08:49:23 PASS: docker_cli_start_volume_driver_unix_test.go:386: DockerExternalVolumeSuite.TestExternalVolumeDriverBindExternalVolume    0.436s
08:49:25 PASS: <autogenerated>:50: DockerExternalVolumeSuite.TestExternalVolumeDriverDeleteContainer    1.412s
08:49:25 PASS: docker_cli_start_volume_driver_unix_test.go:415: DockerExternalVolumeSuite.TestExternalVolumeDriverGet   0.048s
08:49:26 PASS: docker_cli_start_volume_driver_unix_test.go:436: DockerExternalVolumeSuite.TestExternalVolumeDriverGetEmptyResponse  0.090s
08:49:26 PASS: docker_cli_start_volume_driver_unix_test.go:311: DockerExternalVolumeSuite.TestExternalVolumeDriverLookupNotBlocked  0.148s
08:49:28 PASS: docker_cli_start_volume_driver_unix_test.go:231: DockerExternalVolumeSuite.TestExternalVolumeDriverNamed 1.414s
08:49:32 PASS: docker_cli_start_volume_driver_unix_test.go:347: DockerExternalVolumeSuite.TestExternalVolumeDriverRetryNotImmediatelyExists 4.422s
08:49:34 PASS: docker_cli_start_volume_driver_unix_test.go:254: DockerExternalVolumeSuite.TestExternalVolumeDriverUnnamed   1.383s
08:49:36 PASS: <autogenerated>:49: DockerExternalVolumeSuite.TestExternalVolumeDriverVolumesFrom    2.077s
08:49:38 PASS: docker_cli_start_volume_driver_unix_test.go:422: DockerExternalVolumeSuite.TestExternalVolumeDriverWithDaemnRestart  1.111s
```
- Give different names to volumes (it's a hell debugging otherwise)
- Do not list _ninja_ volume or it could fail to be removed since `Get` returns an empty respose

ping @vdemeester @thaJeztah 

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐥

**Comment by thaJeztah** [comment]
LGTM (if tests are green)

**Comment by thaJeztah** [comment]
WindowsTP4 timed out: https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2028/console

```
13:03:28 SKIP: docker_cli_run_test.go:427: DockerSuite.TestRunVolumesFromInReadonlyModeFails (Test requires a Linux daemon)
13:04:12 panic: test timed out after 2h0m0s
13:04:12 
13:04:12 goroutine 6286 [running]:
13:04:12 panic(0xb89da0, 0xc0822b8030)
```

**Comment by runcom** [comment]
ping @cpuguy83 also, could you take a look at the volume drivers test fix?

**Comment by calavera** [comment]
LGTM

**Pull request merged**
