### PR TITLE
Add @aaronlehmann to maintainers

### PR DESCRIPTION
**Pull request by icecrime**
:tada:

### CODE REVIEW

**Comment by jfrazelle** [comment]
LGTM congrats!

**Comment by cpuguy83** [comment]
LGTM, ping @aaronlehmann

**Comment by MHBauer** [comment]
:up: :+1: 
19 thumbsup_960x663
LGTM

**Comment by vdemeester** [comment]
LGTM 🐹

**Comment by thaJeztah** [comment]
LGTM!

**Comment by coolljt0725** [comment]
LGTM :congratulations:

**Comment by aaronlehmann** [comment]
Thanks everyone!

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
