### PR TITLE
vendor: run go mod tidy and go mod vendor

### LINKED ISSUE #44614: [23.0.0-beta] go.sum and vendor/ tree currently mismatch go.mod
### Description

Running "go mod vendor" also fails due to a missing line in go.sum.

Errors when running "go build -mod=vendor" without running "go mod tidy":

go: inconsistent vendoring in docker-engine-:
  cloud.google.com/go@v0.102.1: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/compute@v1.7.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/logging@v1.4.2: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  code.cloudfoundry.org/clock@v1.0.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  [snip]

  To ignore the vendor directory, use -mod=readonly or -mod=mod.
  To sync the vendor directory, run:
  go mod vendor

### Reproduce

1. Run `go build -mod=vendor ./cmd/dockerd`

### Expected behavior

Previous releases build correctly without any changes using `go build -mod=vendor`.

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by paralin**
Run "go mod tidy" and "go mod vendor" to fix the (currently broken) go.sum file and the vendor/ tree.

Fixes errors when running `go build -mod=vendor`

```
go: inconsistent vendoring in docker-engine-:
  cloud.google.com/go@v0.102.1: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/compute@v1.7.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/logging@v1.4.2: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  code.cloudfoundry.org/clock@v1.0.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  [snip]

  To ignore the vendor directory, use -mod=readonly or -mod=mod.
  To sync the vendor directory, run:
  go mod vendor
```

Fixes #44614

### CODE REVIEW

**Comment by thaJeztah** [comment]
The reason you're running into this is that this repository is not yet a go module, as the versioning and package name are not compatible with Go's conventions; adding a `go.mod` would break the repository currently until we rename the project.

we use a `vendor.mod` file to specify the dependencies (which is a custom name for `go.mod`), which is used through the `hack/vendor.sh` script (which creates a temporary `go.mod` file to use during vendoring, but is not used after that); also see https://github.com/moby/moby/pull/44497

closing this because of that, but feel free to continue the conversation

**Comment by paralin** [comment]
@thaJeztah Previous releases build correctly with `go build -mod=vendor` but `master` and the latest beta release do not.

Please fix this so that we don't have to change our entire build tooling in Buildroot just for this package.

**Comment by thaJeztah** [comment]
Previous releases didn't use the `go mod` tool for performing the vendor, so didn't put a `modules.txt` inside the `vendor` directory, which is probably what trips up what you saw; you should be able to build this with `GO111MODULE=off` if the source is in GOPATH

**Comment by paralin** [comment]
@thaJeztah That causes a couple more issues:

 - We set `modcacherw` which causes a go tool error when GO111MODULE=off
 - We rely on the module path matching to find the path to cmd/docker as `github.com/docker/docker/cmd/docker`

... overall this causes a bit of a nightmare on our end.

**Comment by paralin** [comment]
@thaJeztah Seems like setting `GO111MODULE=off` also disables the vendor/ path lookup...

```
cmd/dockerd/daemon_unix.go:22:2: cannot find package "golang.org/x/sys/unix" in any of:
        /lib/go/src/golang.org/x/sys/unix (from $GOROOT)
        /host/share/go-path/src/golang.org/x/sys/unix (from $GOPATH)
```

Why can't it be the way it was before, which worked fine & played nice with the go mod infrastructure?

**Comment by thaJeztah** [comment]
Does it work if you remove the `modules.txt` before building?

**Comment by paralin** [comment]
@thaJeztah That works & is a reasonable workaround. Thanks.

**Pull request closed without merging**
