### PR TITLE
api/server/router/system: fix info versioning

### PR DESCRIPTION
**Pull request by runcom**
cc @cpuguy83 @vdemeester 

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
@thaJeztah should this go into 1.12.3?

**Review by vdemeester — APPROVED** [review]
ohhh :sweat_smile: I think we should set this to 1.12.3 
LGTM 🐸
/cc @cpuguy83

**Comment by thaJeztah** [comment]
Oh, yes, looks like it!

ping @vieux

**Comment by thaJeztah** [comment]
Actually, looks like it's not in 1.12? https://github.com/docker/docker/blob/1.12.x/api/server/router/system/system_routes.go#L31-L41

**Pull request merged**
