### PR TITLE
[1.13.x] Vendoring swarmkit @c7df892

### PR DESCRIPTION
**Pull request by aboch**
Brings the fixes for #28291, #25608 and #30938, #31100  to the 1.13.x branch

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
The Jenkins failure on windowsRS1 seems to be the same as #31011. Not sure about the reason of the Windows failure though I think it is unrelated to the update of this PR.

**Comment by LK4D4** [comment]
I think failure might be valid, but unrelated to change:
```
05:40:53 ----------------------------------------------------------------------
05:40:53 FAIL: docker_cli_logs_test.go:310: DockerSuite.TestLogsCLIContainerNotFound
05:40:53 
05:40:53 docker_cli_logs_test.go:314:
05:40:53     c.Assert(out, checker.Equals, message)
05:40:53 ... obtained string = "Error response from daemon: No such container: testlogsnocontainer\n"
05:40:53 ... expected string = "Error: No such container: testlogsnocontainer\n"
05:40:53 
05:40:57 
05:40:57 ----------------------------------------------------------------------
```
random ping of @vdemeester

**Review by LK4D4 — APPROVED** [review]
LGTM

**Pull request merged**
