### PR TITLE
client.StatusError don't be returned as a pointer

### LINKED ISSUE #12373: client.StatusError should not be returned as a pointer
Find all code like this:
https://github.com/docker/docker/blob/master/api/client/attach.go#L83
and remove the pointer notation because StatusError implements interface error and doesn't need pointer

### PR DESCRIPTION
**Pull request by xiaods**
closes #12373

Signed-off-by: Deshi Xiao xiaods@gmail.com

### CODE REVIEW

**Comment by LK4D4** [comment]
Seems like you created branch from old master.

**Comment by xiaods** [comment]
@LK4D4 update done.
could you tell more benefit on remove * from Error method?

**Comment by runcom** [comment]
@xiaods I'm not sure, I think is standard go way of implementing the error interface with a value pointer (even if example from https://blog.golang.org/error-handling-and-go use the pointer receiver and examples in the stdlib use the value receiver)

**Comment by LK4D4** [comment]
@xiaods Tests failing. Idea behind using values for small structs is to low pressure on GC which has more problems with collecting pointers, than values. Here it is just matter of style.
https://code.google.com/p/go-wiki/wiki/CodeReviewComments#Pass_Values

**Comment by xiaods** [comment]
@LK4D4 thanks for your comments. learned more. :+1: 

the failed report like -
-- FAIL: TestRunOOMExitCode (0.57s)
	docker_cli_run_test.go:3316: wrong exit code for OOM container: expected 137, got 1 (output: "WARNING: Your kernel does not support swap limit capabilities. Limitation discarded.\ntime=\"2015-04-15T09:14:31Z\" level=fatal msg=\"Status: , Code: 137\" \n")

it's not relative with daemon/daemon.go code base. so i need take some time on it. hold on.

**Comment by LK4D4** [comment]
@xiaods Sorry, `docker/docker.go`.

**Comment by xiaods** [comment]
@LK4D4 roger!

**Comment by vieux** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
