### PR TITLE
Builder/tarsum unit tests

### PR DESCRIPTION
**Pull request by tkopczynski**
Adding builder/tarsum tests.

Part of resolving #20784

Signed-off-by: Tomasz Kopczynski tomek@kopczynski.net.pl

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like there's genuine failures;

```
22:16:15 ---> Making bundle: validate-vet (in bundles/1.11.0-dev/validate-vet)
22:16:15 builder/tarsum_test.go:60: wrong number of args for format in Fatalf call: 1 needed but 2 args
22:16:15 builder/tarsum_test.go:121: wrong number of args for format in Fatalf call: 1 needed but 2 args
22:16:15 builder/tarsum_test.go:160: wrong number of args for format in Fatalf call: 1 needed but 2 args
22:16:15 builder/tarsum_test.go:261: wrong number of args for format in Fatalf call: 1 needed but 2 args
22:16:15 builder/tarsum_test.go:302: wrong number of args for format in Fatalf call: 1 needed but 2 args
22:16:15 exit status 1
```

**Comment by tkopczynski** [comment]
Hey @thaJeztah 
I've fixed those errors and it seems to be passing CI now

**Comment by calavera** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
damn, too slow.

**Pull request merged**
