### PR TITLE
Handle out-of-sync libcontainerd client on restore

### LINKED ISSUE #24971: ungraceful daemon restart retains a dead container in docker ps
When I kill the daemon ungracefully using 3 ^Cs on the daemond process, it results in a dead container showing up in docker ps. But when I killed the daemon using `kill -9 <dockerd-process>`, the containers are properly cleaned up. This is impacting the `docker service` as well.

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker run -d alpine top
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
e110a4a17941: Already exists
Digest: sha256:3dcdb92d7432d56604d4545cbd324b14e647b313626d99b889d0626de158f73a
Status: Downloaded newer image for alpine:latest
f877097a30237312db60970fb370e76b21ca5819b3caea43cf2f517fec7c6d19

$ docker run -d alpine top
5e0e50a636d2967bf0c41e1623053346dff7c0fa970f5a54d36644a63b952923

$ docker run -d alpine top
a179df0359e64f0390877af56d6d40679354ac0c60af852c39247e5676625676

$ docker exec -it 5e0e50a636d2 sh
/ # exit

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a179df0359e6        alpine              "top"               16 seconds ago      Up 16 seconds                           fervent_elion
5e0e50a636d2        alpine              "top"               22 seconds ago      Up 21 seconds                           elated_northcutt
f877097a3023        alpine              "top"               24 seconds ago      Up 23 seconds                           desperate_stallman
$
$ #### UNGRACEFUL DOCKER DAEMON RESTART ####

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
f877097a3023        alpine              "top"               48 seconds ago      Up 47 seconds                           desperate_stallman
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
f877097a3023        alpine              "top"               53 seconds ago      Up 52 seconds                           desperate_stallman
$ docker exec -it f877097a3023 sh
invalid container: f877097a30237312db60970fb370e76b21ca5819b3caea43cf2f517fec7c6d19
$
```

### LINKED ISSUE #25157: Can't kill container after restarting daemon with some stuck container
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   95ede36
 Built:        Thu Jul 28 03:19:42 2016
 OS/Arch:      linux/amd64
 Experimental: true
```
I run a container and it stuck on exiting, so I restart the daemon,
and `docker ps` show the container is still running. But run `ps aux | grep containerd`
I can't see these container is till running.
So I try to kill the container, but failed with
`container kill failed because of 'container not found' or 'no such process': Cannot kill container e1180c116260275f8bdfeb5599d2cc6b247800d75335585eeedccd864a4d4f02: rpc error: code = 2 desc = containerd: container not found`

I'm fully sure the container stuck on exiting, the daemon has receive the 
container event from containerd, but stuck on cleaning up container resource and 
restarting daemon make this container has a `Running=true` state but the container is
not running any more, so that we can see it in `docker ps`. I still can't figure out why
the container stuck and it's not easy to reproduce. But I think the daemon should handle
the case that the container has a `running=true` state but is not alive and has consumed all the
events from containerd. 
ping @mlaventure

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure mickael.laventure@gmail.com
## 

Fixes #24971
Fixes #25157

I couldn't find a way to fix it in docker proper without causing the triple `^C` to wait, so I had to do it in `libcontainerd` instead.

Since I still can't reproduce it locally, I've fake it by only allowing "exit" events to be processed if a restore is in progress in order to test it, which seemed to work.

ping @mavenugo 

~~edit: cherry-picked #25133 into this~~

### CODE REVIEW

**Comment by LK4D4** [comment]
@mlaventure is it for 1.12?

**Comment by mlaventure** [comment]
I think @mavenugo wants it for 1.12.

As far as the fix is concerned, I don't think it's critical. As long as you either kill the daemon straight away via kill -9 or wait for it finish its shutdown sequence, the issue shouldn't occur.

**Comment by mavenugo** [comment]
@mlaventure i dont think it is critical/blocker for 1.12.

**Comment by LK4D4** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by thaJeztah** [comment]
@mlaventure for 1.12.1?

**Comment by mlaventure** [comment]
it wouldn't hurt :angel:

**Comment by tonistiigi** [comment]
`TestApiSwarmRestartCluster` failure in experimental, ignoring.

**Pull request merged**
