### PR TITLE
add architecture_darwin.go in  package docker/pkg/platform to support darwin

### PR DESCRIPTION
**Pull request by allencloud**
make package docker/pkg/platform support darwin

This PR can finish a part of work described in #22470

### CODE REVIEW

**Comment by justincormack** [comment]
Could you just share the freebsd and darwin files, call them architecture_unix and and a no Linux build constraint as they are identical (and most other Unixes would be identical too)?

**Comment by allencloud** [comment]
update the PR, WDYT?
@justincormack

**Comment by LK4D4** [comment]
I don't know why, but windows tries to compile that file too. maybe @jhowardmsft knows.

**Comment by jhowardmsft** [comment]
Windows is `!linux` :smile:

**Comment by allencloud** [comment]
@LK4D4 @jhowardmsft 
I am confused. But I add `!windows` in *_unix.go.

**Comment by thaJeztah** [comment]
ping @jhowardmsft @LK4D4 ptal

**Comment by LK4D4** [comment]
@allencloud yeah, I'm confused as well. :) But at least it passed now.
LGTM

**Comment by jhowardmsft** [comment]
@thaJeztah - @allencloud updated it.

**Comment by LK4D4** [comment]
ping @docker/core-maintainers

**Comment by justincormack** [comment]
I think changing Linux from a syscall to an `exec` is strictly worse as exec is slow. You can use `syscall.Sysctl` on freebsd/darwin in order to avoid the exec there too.

**Comment by allencloud** [comment]
@justincormack 
Make linux to use syscall again.
While the integration test fails a lot. Confused.

**Comment by thaJeztah** [comment]
@allencloud looks like there's an issue with CI currently (running out of disk space for some reason) :cry:

**Comment by allencloud** [comment]
OK, Thx.
@thaJeztah 
If CI works, it would be great to info me.

**Comment by allencloud** [comment]
ping @LK4D4 @justincormack @jhowardmsft

**Comment by thaJeztah** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐯

**Pull request merged**
