### PR TITLE
Clarify binaries in changelog

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Clarify the platform difference with multiple binaries.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! LGTM

**Not sure we can merge already, with the dynamic packages being worked on at the moment**

**Comment by tonistiigi** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by thaJeztah** [comment]
merging, CI for code isn't needed

**Pull request merged**
