### PR TITLE
[17.03] Vendor swarmkit 2591ac3

### PR DESCRIPTION
**Pull request by aaronlehmann**
Includes https://github.com/docker/swarmkit/pull/2185

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by aluzzardi** [comment]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
hm; issues with Hub?

https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/14027/console

```
20:11:24 ----------------------------------------------------------------------
20:11:24 FAIL: docker_cli_pull_test.go:270: DockerSuite.TestPullLinuxImageFailsOnWindows
20:11:24 
20:11:24 docker_cli_pull_test.go:273:
20:11:24     c.Assert(err.Error(), checker.Contains, "cannot be used on this platform")
20:11:24 ... obtained string = "" +
20:11:24 ...     "\n" +
20:11:24 ...     "Command: d:\\CI\\CI-472485ea9\\binary\\docker.exe pull ubuntu\n" +
20:11:24 ...     "ExitCode: 1, Error: exit status 1\n" +
20:11:24 ...     "Stdout: Using default tag: latest\n" +
20:11:24 ...     "latest: Pulling from library/ubuntu\n" +
20:11:24 ...     "\n" +
20:11:24 ...     "Stderr: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/eb/ebcd9d4fca80e9e8afc525d8a38e7c56825dfb4a220ed77156f9fb13b14d4ab7/data?Expires=1494966673&Signature=iKISwDZskCD6DEY8lTJFU~7QqmipeL6cX~Pndqv-PSnscMGbrAtn3SiyCwtBgWlrmGc1W-Wg4DlzXiWmryGH5G09mh9TTGW6oQFfyN9xZ4GtL5laaEonHXgtzf5ZgeHeyeP7OuZGo9M8CT1b6~WMeNHjncHU~CrPtq~w9Tqxu2Y_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net: getaddrinfow: No such host is known.\n" +
20:11:24 ...     "\n" +
20:11:24 ...     "\n" +
20:11:24 ...     "Failures:\n" +
20:11:24 ...     "ExitCode was 1 expected 0\n" +
20:11:24 ...     "Expected no error\n"
20:11:24 ... substring string = "cannot be used on this platform"
20:11:24 
20:11:25 
20:11:25 ----------------------------------------------------------------------
```

**Comment by cpuguy83** [comment]
Opened #33238 to deal with flakey test
Merging.

**Pull request merged**
