### PR TITLE
Fix containers/create 404 response description

### PR DESCRIPTION
**Pull request by Emdot**
fix containers/create 404 response description

**- What I did** Fixed a minor documentation error

**- Description for the changelog**
Fixed containers/create 404 response description.

### CODE REVIEW

**Comment by jterry75** [comment]
@Emdot - Force push with `-s` to pass DCO

**Comment by Emdot** [comment]
Well, I fixed my DCO problem, but I haven't a clue why this is failing build. It really doesn't seem as though I could have caused that. Any ideas?

**Comment by jterry75** [comment]
@Emdot - Not related to your PR. But not sure who to get any feedback here either so I guess we wait :)

**Comment by Emdot** [comment]
It'd be pretty cool if someone would review this :)

**Review by thaJeztah — APPROVED** [review]
oh! I thought I already LGTM'd this one

let's get it merged, thank you!

**Pull request merged**
