### PR TITLE
Embed context.Context to routes with usage of CloseNotify

### PR DESCRIPTION
**Pull request by LK4D4**
ping @aaronlehmann @calavera

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Huge :+1: for this change. Thanks for working on it.

Just one question: is there a good reason to have a special `Cancellable` handler? I was thinking that `makeHTTPHandler` could do the `CloseNotifier` dance instead of just passing `context.Background()` to the handler. Are there any cases where we *don't* want a client disconnect to cancel the context?

**Comment by LK4D4** [comment]
@aaronlehmann I was scared away by comment https://golang.org/src/net/http/server.go?s=4307:5130#L135
And I know that docker-py definitely uses pipelining.

**Comment by LK4D4** [comment]
@aaronlehmann I think I can make it automatic for non-gets and make separate call for events. WDYT?

**Comment by aaronlehmann** [comment]
@LK4D4: That comment is strange :confused:.

Not sure if it should be automatic for POSTs or not.

**Comment by calavera** [comment]
LGTM

**Comment by coolljt0725** [comment]
LGTM

**Comment by aaronlehmann** [comment]
Can you please make push and pull `Cancellable` too? Right now they cancel their own context if writing to the `ResponseWriter` fails. It would be better if they were cancelled when the connection actually closes. I just saw a report that disconnecting the client didn't cancel a frozen download. I think adding `Cancellable` to those routes would fix this.

**Comment by LK4D4** [comment]
@aaronlehmann made those methods cancellable

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by aaronlehmann** [comment]
LGTM

**Comment by icecrime** [comment]
Interesting failure in windowsTP4 (cc @jhowardmsft):

```
09:53:29 FAIL: docker_cli_ps_test.go:761: DockerSuite.TestPsShowMounts
09:53:29 
09:53:29 docker_cli_ps_test.go:770:
09:53:29     runSleepingContainer(c, "--name=volume-test-2", "--volume", mp)
09:53:29 C:/gopath/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:42:
09:53:29     c.Assert(err, check.IsNil, check.Commentf(quote+"%v"+quote+" failed with errors: %s, %v", strings.Join(args, " "), out, err))
09:53:29 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc08239cf00), Stderr:[]uint8(nil)} ("exit status 125")
09:53:29 ... "run -d --name=volume-test-2 --volume c:\test busybox sleep 240" failed with errors: 586e66e5980d4158ebe6839e49c8c14e35865b48bd787f7d639e66a481f66e72
09:53:29 D:\CI\CI-c11d7aa\binary\docker.exe: Error response from daemon: HCSShim::CreateProcessInComputeSystem failed in Win32: The specified path is invalid. (0xa1) id=586e66e5980d4158ebe6839e49c8c14e35865b48bd787f7d639e66a481f66e72 params={ C:/busybox/busybox.exe sleep 240  map[] false [0 0]}.
09:53:29 , exit status 125
```

Merge anyway?

**Comment by LK4D4** [comment]
Looks pretty unrelated.

**Comment by calavera** [comment]
all :green_heart: merging

**Pull request merged**
