### PR TITLE
Switch to new versioning scheme

### PR DESCRIPTION
**Pull request by vieux**
This PR changes the versioning scheme of Docker. The next version of Docker will use a **YY.MM**_.rev_ versioning scheme. The next version to be released from the current *master* branch is expected in April, so the version used in this PR is `17.04.0`. We will also release `17.03.0` from the *17.03.x` branch, based on the *1.13.x* branch.

The new version scheme also includes `-ce` - short for “Community Edition”. “Community Edition” is one of a couple of changes to the way Docker is packaged that we’re preparing 

There are no functional changes that go along with the versioning change, and the API version stays the same in this release.

As part of the packaging changes, we’ll also work on consolidating package repos and other downloads on download.docker.com. This is part of our efforts to reduce the sprawl of download properties into a single secure location. get.docker.com and other release infrastructure will be maintained for backwards compatibility for now. Packaging code for distros and similar will still live in `/hack` and `/contrib`.

We will take care of updating all GitHub labels/milestones after this change is merged.

ping @docker/core-engine-maintainers

### CODE REVIEW

**Comment by albers** [comment]
Does this mean there will be no distinction between major and bugfix releases any more?
Furthermore, this sheme will only allow one release per month.
It's also not semantic, so it will make it much harder for admins to maintain a stable environment.

**Comment by vieux** [comment]
@albers the distinction still exists, as you can see in master, the new version is actually `17.04.0` you should see `17.04` as major and `.0` as minor. I updated the PR body to reflect it.

**Comment by albers** [comment]
> We will also release 17.03.0 from the *17.03.x` branch, based on the 1.13.x branch.

So `17.03.0` will actually be `1.13.2`? This is confusing because the number imples that it's a major update.
I'd prefer releases based on `1.13.x` branch to retain their old versioning scheme.

**Comment by friism** [comment]
> This is confusing because the number implies that it's a major update

I think your critique is correct when considering `docker/docker` in isolation. Docker is making packaging changes that go beyond the code in this repo, and we're using the change in versioning scheme to emphasize those changes.

**Comment by duglin** [comment]
Would it make sense to do another big change at the same time? In particular, the difference between docker's version # and the API version # is confusing to many people. It would be nice if those two were always the same and we just had one version # to deal with.  The original idea that the version #'s of the API and docker would be bumped at different times never really panned out.

**Comment by stevvooe** [comment]
Why are we switching away from semantic versioning? Also, what happens in the year 2100?

**Comment by friism** [comment]
> Why are we switching away from semantic versioning?

Going forward, we're going to stick a time-based release schedule and reflecting that directly in the versioning is a good way to emphasize that. Changing to a new versioning scheme is also a good way to emphasize the packaging updates we're introducing to make it clear what's pre-change and what's post-change.

**Comment by stevvooe** [comment]
@friism That still doesn't answer why we would move away from the best practices of semantic versioning. You can still do time-based releases and adhere to it.

Was there an announcement on the mailing list or a written document detailing this decision? I see an email in my inbox with a few hours notice for a meeting that happened this morning.

**Comment by tiborvass** [comment]
LGTM

**Comment by MHBauer** [comment]
Considering we cannot take any 1.X client and any other 1.Y server and have them work together, we are not fulfilling the requirements of semver as it is.

As commentary, I would suggest using the whole year vs the truncated version, to make it clear that it is indeed the year. It is the date, so use the date.

**Comment by thaJeztah** [comment]
> Considering we cannot take any 1.X client and any other 1.Y server and have them work together, we are not fulfilling the requirements of semver as it is.

With the API version negotiation added in docker 1.13, a docker 1.13 client is able to connect to older  1.12, or 1.13 daemons. Older clients are always able to talk to a newer daemon.

Basically, this doesn't change; e.g., a 17.10 client would be able to automatically negotiate API versions with 1.12, 1.13, and 17.03 .. 17.10 daemons, and can work with any daemon newer than that (17.11, 17.12, 18.01 etc)

**Comment by albers** [comment]
> So 17.03.0 will actually be 1.13.2? This is confusing because the number imples that it's a major update.

How about releasing `1.13.2` as `17.03.2`? This feels a bit strange, but we retain the information that it is a patch release.

I also like the idea of using the full year in the version as proposed by @MHBauer.

**Comment by justincormack** [comment]
@stevvooe we never supported semver, but our versioning scheme made people think we did, which there were many complaints about.

**Review by justincormack — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Comment by vieux** [comment]
@MHBauer let's take ubuntu as an example, I think it's clear enough when you get 16.04 that 16 is the year, no ?

**Comment by duglin** [comment]
I'd like to know about https://github.com/docker/docker/pull/31075#issuecomment-280430049  ? It would be really nice to remove the current inconsistency we have at the same time as we do this.

**Comment by cpuguy83** [comment]
@duglin Well, we just had to bump the API version on 1.13.1. So that would have thrown it off anyway.

**Comment by duglin** [comment]
@cpuguy83 I'm not following. If 1.13.1's version number was 170215 and the api's version number was the same, what's the issue?

**Comment by vieux** [comment]
@duglin I think it's a change too big to be done at the same time, i'm afraid it will break many people.

And I'm not even sure we should have the versions be the same.

1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6 are all using API 1.24
1.13.0 is using API 1.25
1.13.1, 17.03.0 are using API 1.26


for all the 1.12.x I think it's good that we have the same API version

**Comment by duglin** [comment]
@vieux why is it a good thing that 1.12.x's all have the same versions? People clearly can't count on that because as you've shown 1.13.x's vary.  So its random. And it does people a disservice for them to believe otherwise.  How is that better than to say "each version of Docker has its own version of the API".  And, people can then be explicitly clear about which version of the entire end-to-end docker they're using.  We're supposed to be backwards compatible so bumping the numbers more often shouldn't hurt anything - especially when we encourage people to not use "latest" as the version.

**Comment by unclejack** [comment]
It'd be nice to explain the benefits of this change in the documentation or somewhere. I'm sure the users would be happy to learn more about this.

Do you think we should have two sets of repositories? I expect some would like to upgrade only once in a while (to upgrade to bug fix releases and new longer term releases) and skip the intermediary releases.

LGTM

**Comment by duglin** [comment]
btw, I'm ok with resolving my questions around the API versioning scheme in a subsequent PR and letting this one be considered in isolation.

**Comment by mlaventure** [comment]
Need to update the references to `X.Y.Z` within `project/` too. I guess it should read `YY.MM.Z` now

**Review by thaJeztah — APPROVED** [review]
LGTM, but we may want to look at the changes that @mlaventure mentioned (can be a follow up)

**Comment by estesp** [comment]
LGTM 

Ok with subsequent PRs for the remaining questions

**Comment by stevvooe** [comment]
> Also, what happens in the year 2100?

Anyone on this? Or are we just going to repeat the mistakes of our ancestors?

__#Y2.1K__

Also, consider that once this is done, you can never go back.

**Comment by MHBauer** [comment]
I like having the whole year to be explicit. There's something in my mind that sees a version like that and goes 'wait a second, is that a date?'. Then I know it's from last month or last year, or that the project is hopelessly out of date if it's something else. v5.62 doesn't give me any of that.

**Comment by stevvooe** [comment]
> I like having the whole year to be explicit. There's something in my mind that sees a version like that and goes 'wait a second, is that a date?'. Then I know it's from last month or last year, or that the project is hopelessly out of date if it's something else. v5.62 doesn't give me any of that.

17.03.0: March 17, 2000

**Comment by dmp42** [comment]
@MHBauer @stevvooe the Ubuntu example is widely known, and it doesn't look like many people are confused by it. Adding the leading `20` feels like adding noise IMHO.

About the 2100 problem, I'm happy to be proven wrong :-) but I don't think docker will still be there in 80 years, or that it would still have that version scheme. Either way, at that time, we can just go from 99.12.0 to 100.03.0 right?

Then, maybe we have a problem in the year 3000 :)

**Review by icecrime — APPROVED** [review]

**Comment by vieux** [comment]
@mlaventure I'm going to address your changes in a following PR, merging..

**Comment by MHBauer** [comment]
> 17.03.0: March 17, 2000
What is your point?

**Comment by gesellix** [comment]
Maybe a bit late - but if semver wasn't actually applied and the `YY.MM.x` scheme isn't completely popular - why not using a counter? For each release just add `+1` to the previous release number. It's simple, you can compare version numbers, etc. Did I mention that it's simple?

**Comment by hairyhenderson** [comment]
> 17.03.0: March 17, 2000

Only in some countries... Plus, nobody would ever abbreviate "2000" to "0" 😉

**Comment by alexellis** [comment]
How soon will this change manifest in a release @vieux @friism ? It would be good to give a heads-up/briefing to the Docker Captains community so we can start thinking about how to explain this and answer questions.

**Comment by friism** [comment]
@alexellis we're planning a briefing next Thursday

**Comment by gesellix** [comment]
will the briefing be in public @friism ?

**Comment by friism** [comment]
> will the briefing be in public

@gesellix the briefing is for Docker Captains and is not public.

**Comment by dustinmoris** [comment]
Can someone elaborate on the rationale to do this? This is a very weird way of versioning.

Here is a list of weird things with this weird versioning scheme:

# 1: Versions have no meaning whatsoever anymore

Let's fast forward a few months and say we are on version 17.12.0. On the 5th of Dec you release a super small bug fix and the version will increment to 17.12.1. On the 29th of Dec you release a MAJOR BIG FEATURE/CHANGE and the version will only increment to **17.12.2**. That is super weird. Now let's say 5 days later in Jan you release another super mini bug fix and the version will become 18.01.0. This is just weird. The version will have absolutely no meaning or relation to the changes made whatsoever. Might as well abandon versions altogether then...

# 2: Gaps in the versioning

There will never be 18.0.0 or 19.0.0 or 20.0.0... It will always start with 18.01.0. WTF?

# 3: More gaps in versioning

If there is no release for a few months the version progression looks like this:
17.05.0
17.05.1
17.12.0
19.01.0
WTF???

# 4: Versioning without meaning is redundant

Most importantly if a version has absolute no meaning (or value in that respect) then it is just noise/trash and redundant. If a version says nothing but the year and month in which it has been released, then it adds 0 value or information to the release, because we know when it has been released through 100 other sources anyway. Why bothering with a version than at all?

**Comment by vdemeester** [comment]
> On the 29th of Dec you release a MAJOR BIG FEATURE/CHANGE and the version will only increment to 17.12.2.

This will never happen. It's released monthly, whatever major big change/feature is in december, it will be released next month. The release happen monthly, whatever the changes are in. Expect for bug fix (that increment the patch version (i.e. 17.03.1), a feature/change doesn't mean a release. 

> More gaps in versioning

Again, never gonna happen, there will be a release each month, whatever the change are in.

**Comment by dustinmoris** [comment]
> This will never happen. It's released monthly, whatever major big change/feature is in december, it will be released next month. The release happen monthly, whatever the changes are in. Expect for bug fix (that increment the patch version (i.e. 17.03.1), a feature/change doesn't mean a release.

Brilliant. So you crippled yourself to a stiff release cycle **FOREVER** only so you could justify some weird versioning decision that you had one day long time ago?

> Again, never gonna happen, there will be a release each month, whatever the change are in.

Brilliant again. You have just committed to release a new version EVERY BLOODY MONTH for the rest of your life no matter if there are actually changes that justify a new version just so you can stick with a crappy versioning scheme. Are you sure? I mean you can always make up changes just to release "something"...

**Comment by thaJeztah** [comment]
Yes, there will be a release every month; that's the major change, i.e., switching to a [time-based release cycle](https://wiki.ubuntu.com/TimeBasedReleases). Monthly releases can contain incremental changes, and allows users to have access to new features sooner, without having to wait for other features to be completed first.

For users that don't need the "bleeding edge" features, there's the quarterly releases. Quarterly releases receive bug- and security fixes for _four_ months, so have a one-month overlap with the next quarterly release.

Note that docker using a time-based release cycle is not new; in the past, a bi-monthly release cycle was used. The combination of a monthly release, and a quarterly release is a good middle-ground.

> If a developer in Australia releases a new Docker version on the first day of the month

Releases are always tagged and released by Docker; there is no requirement to do a release at the _first_ day of the month. Release-candidates will be released, and a GA release is done after that. The GA release can take place _during_ the month.

**Comment by dustinmoris** [comment]
> For users that don't need the "bleeding edge" features, there's the quarterly releases. Quarterly releases receive bug- and security fixes for four months, so have a one-month overlap with the next quarterly release.

This is another mistake. Security fixes are not "bleeding edge" and should be rolled out everywhere as soon as possible in a perfect world. Docker should never advertise to customers that they can choose to wait for a quarterly release to receive security fixes.

This is just another great example how SemVer would make much more sense and where time based releases come short. If you find a major security vulnerability in Docker that needs immediate attention, but requires potential big changes, would you delay the release only to not break weird versioning?

All I am saying is that I doubt that everyone has really thought this through properly and this change is will cause you a lot of trouble later down the road, I promise you this. You simply don't know what you will/want to do in 1 or 2 years time and your choices from today should not cripple you in the future. All your arguments are based on "this is how it is done today and it will not change" which should be a massive red flag to anyone who is involved in this.

**Comment by thaJeztah** [comment]
> This is another mistake. Security fixes are not "bleeding edge" and should be rolled out everywhere as soon as possible in a perfect world. Docker should never advertise to customers that they can choose to wait for a quarterly release to receive security fixes.

Please reed my comment above; 

> Quarterly releases receive bug- and security fixes for four months, so have a one-month overlap with the next quarterly release.

Bugfixes and security fixes are released for the monthly releases, and back-ported to the quarterly releases.

**Comment by dustinmoris** [comment]
> This will never happen. It's released monthly, whatever major big change/feature is in december, it will be released next month.

+

> If you find a major security vulnerability in Docker that needs immediate attention, but requires potential big changes, would you delay the release only to not break weird versioning?

What does this mean now? Big changes will always roll over to the next monthly release unless it is a big security fix? Confusing...

**Comment by cpuguy83** [comment]
@dustinmoris 

1. Many people have spent a lot of time on this. Please do not assume otherwise. That is not to say your input is not valued, but assumptions that nothing has been thought through and that this is done on a whim are unfounded.
2. Patches will continue to happen as always, except there will be two branches, an "LTS" branch which is supported for 3 months, and a monthly branch which is only supported until the next month's release. A security fix will be applied as we do today against all supported versions. This is opposed to the current situation where there a single branch based on a 2-3 month release cycle and only the current release is supported.
3. Just as this is changing the versioning to a different scheme, if it is decided later that this scheme is not working out it can be changed. Why would anyone stick to something that's not working... also the current scheme (before this change) is not working.

**Comment by dustinmoris** [comment]
@cpuguy83 Ok fine, but my initial question was:

> Can someone elaborate on the rationale behind this?

I would be still interested to hear what value of time based versioning is over semantic versioning. Because its not like SemVer hasn't been used and practiced by many people who also happened to spend a lot of time tinkering what versioning system makes the most sense and then came to the conclusion that SemVer was the best fit.

**Comment by cpuguy83** [comment]
@dustinmoris There will be an official announcement soon. Other than that I would request @friism to discuss details.

**Comment by gesellix** [comment]
It would've been nice to include the community in the discussion of changing the versioning scheme. That's certainly a bit risky, because more people slow down such a process, and bike shedding happens a lot. Apologising later sometimes feels a bit more efficient.

I don't prefer semver, since I'm part of the group saying that it doesn't really work. I don't prefer the new pattern encoding the release calendar into the version scheme. I don't really prefer any scheme at all.

I _wish_ that the versioning scheme is kept simple. I often pick the Git hash as version, maybe an ISO encoded timestamp. But that's not handy when one needs a "marketing version", or when just talking about different versions should be easy. Also, comparing version numbers with each other should be easy, e.g. to detect older clients talking to a more recent api. Yeah, semver and the new "Ubuntu style" pattern allows what you need.

They still feel like over-engineering to me when _a simple integer might suffice_. It would even allow to change the release frequency without further thinking about version numbers.

Now... thinking about LTS the integer based pattern might feel harder to implement. Maybe LTS was the reason to introduce the new versioning scheme? Ah, wait, how will LTS actually be implemented? Are you going to maintain a branch? That very branch would still work together with an integer style version number. You might even add a suffix like `42-LTS`, or you might rely a bit more on the git hash you already store along with the version number, so that everyone knows that you're talking about the LTS branch. I'm thinking out loud here, maybe there are reasons against such simple version numbers.

To close my little rant: I would be so very happy if the Captains briefing would happen in public. If not, could you please explain why that topic needs to be a multi step process? There are people out there with experience, maybe feedback, maybe even good ideas. Please don't ignore them. Getting to know more details or arguments about your decision towards the new pattern would be nice.

Like @cpuguy83 mentioned, you're at least open to change the versioning scheme if need be. Hopefully the community will be included in future discussions about similar topics.

**Comment by hairyhenderson** [comment]
> I would be still interested to hear what value time based versioning has over semantic versioning.

@dustinmoris - keep in mind that Docker has _never_ adhered to semantic versioning...

**Comment by friism** [comment]
@dustinmoris thanks for sharing your feedback.

> I would be still interested to hear what value time based versioning has over semantic versioning.

As several people have pointed out, Docker does not currently follow semantic versioning, so if you care about that, things are not worse after this change. 

@gesellix I agree there are lots of ways that the versioning could work. We hope that the versioning introduced in this PR will work for the Docker project, and we'll be rolling out the change in concert with other updates to Docker products.

**Comment by alexellis** [comment]
I think there are some very valid questions in the thread. Looking forward to hearing more - @friism do you think there will be an official blog posted about the change with some of the discussion/drivers mentioned by @cpuguy83 and others?

**Comment by dustinmoris** [comment]
@friism @hairyhenderson 

I understand that you say you never really followed SemVer, but that doesn't automatically imply a switch to a totally different versioning system. I guess I am just curious to learn more about why SemVer is not a good fit for Docker and time based versioning is better? e.g. what type of problems does it solve that is not possible or difficult with SemVer? What advantages does time based versioning have over SemVer at all? I cannot think of a single issue with SemVer, but can easily think of even more issues with time based versioning (as already mentioned above), so I'd be really curious to find out what the big? gains are from time based versioning.

So far from this thread the common answer is: "We didn't use SemVer so we are switching to time based, just because"

Obviously you don't have to justify your decision to me or anyone else, but I assume that you had more logical reasons behind this change and logical reasons to not use SemVer properly and just between technical guys I would be curious to find out what those "good" reasons are. Perhaps I'll learn something new...

**Comment by shawnbutts** [comment]
with the new versioning scheme, which version(s) do i pick for the 1-2 years of no breaking changes with security bug fixes?

**Comment by friism** [comment]
@shawnbutts with the upcoming releases, we're improving the maintainability of free Docker releases by adding a 1 month maintenance window overlap for quarterly releases. Since quarterly releases are supported for 4 months, there's a one-month window for upgrading where both the new and the old quarterly release is receiving security fixes. This is an improvement on the previous model where patches are not released for old versions at all.

For users interested in longer support windows, Docker maintains the [Docker CS engine](https://www.docker.com/pricing#/pricing_cs_engine). We're working on making that clearer too.

**Comment by ibuildthecloud** [comment]
Let me throw my hat into the ring and say this is a bad idea, like a really bad one.  The problem with switching to this scheme is it's extremely hard to switch to a different one.  My ADD prevents me from reading this whole thread but from what I've seen is the reason for this is "blah blah time-release, blah blah it's better, blah blah something about LTS."

The point being I don't really care a heck of a lot.  I ship software too for my day job.  I too have had way too many discussions about versions, release cycles, patching, etc.  Basically all ideas are terrible, and the one you pick probably won't work well.  It's an iterative thing to find what best matches your users.  It sounds like you guys are pitching some process change that somehow helps you internally and somehow feel like switching the versioning helps.  Well, it's doesn't, it's confusing....

The version is arbitrary nonsense, it's basically ${RANDOM CRAP}.${PATCH NUMBER}.  So if RANDOM_CRAP=1.13 or =17.04, doesn't really matter.  What I suggest you do is test out whatever new process you want, with the current version scheme.  Only then if the process works you switch the versioning.  All too often engineering gets great ideas like "We will just ship every month, the version number is useless, so we'll just say it's the month we released."  So then april comes around and your about to ship 17.04 and feature X isn't ready.

```
Sales Guy:     "I promised feature X would be in 17.04 to customer Big Important Inc." 
Rock Star Eng: "Well we release monthly and it's not ready so its not going in."
Sales Guy:     "Delay the release, I need the feature, it's big $$"
Rock Star Eng: "No, I can't delay, it's a monthly release. Then 17.04 would be 17.05"
Sales Guy:     "Fine release today, but then give me a release next week with feature X"
Rock Star Eng: "No, a release in a week would be 17.04.1 and can't have new features.  You have to wait until 17.05"
Sales Guy:     "Fine release, 17.05 in a week from now"
Rock Star Eng: "No, 17.05 has to be release in May."
Sales Guy:     "WTF!? So you are telling me I have to wait another month because your pretty version number will be wrong"
```

So.... switching to 17.04 isn't good unless you have REALLY, REALLY thought this through, then tried something, failed 4 times, and then decided on this.  Ubuntu's versioning is very clear, is 6 month release cycles, and a train of planning.  This change seems cosmetic...

**Comment by relistan** [comment]
With the amount of justification provided here, it's hard to understand why this is a good idea. It seems to me like it will cause some amount of chaos and misunderstanding on the part of existing users, and probably require some changes to tooling and config management (at a minimum) by production users. Not necessarily a huge deal, but it would be great if you folks could spend some time better explaining to us why this is going to help us and is worth the pain. @alexellis suggested a blog post. Yes, please.

A longer commentary period would also have been appreciated. I suspect the end solution would have benefited from the additional input that would have provided.

**Comment by shawnbutts** [comment]
@friism so the maximum amount of time i can safely have non-breaking changes is 4 month?

**Comment by cpuguy83** [comment]
@shawnbutts Docker never intentionally has a breaking change except through the [documented deprecation policy](https://docs.docker.com/engine/breaking_changes/) (which indeed needs updating for the new versioning/support scheme, on the todo list).

If you do run across a breaking change that was not communicated through the normal deprecation policy, please do file an issue so it can be addressed.

**Comment by shawnbutts** [comment]
I'm not worried about communication.  I'm worried about a "swarm" to "swarm mode" type change that will force a major production change.  With only a 4 month "guarantee", there is a potential for up to 4 unplanned (outside companies control) changes to the infrastructure of production environments.  Given the already tight schedules some of us work with, staying with docker may become a difficult sell to management.  

If this decision was made, in anyway, to push people desiring a reasonable LTS version into a non-“Community Edition” version, it may impact our own internal push for docker.

**Comment by cpuguy83** [comment]
@shawnbutts "swarm mode" is an enhancement to engine, "swarm" still works just fine with even the latest version of engine. It does not force any major production change unless it is something you want to take advantage of.

**Comment by Russell-IO** [comment]
LGTM

**Comment by benoahriz** [comment]
I along with many other people was hoping one day for semantic versioning to be adopted and being able to rely on a versioning scheme that actually means something.  Internal release processes come and go inside companies but versioning should be free of being affected by those.  Even though the existing versioning system is less than ideal at least the community has made some sense out of it and knows what to expect.  This changes those expectations and we will have to adapt.

**Comment by Russell-IO** [comment]
There's nothing stopping anyone from checking out the code, building it on your own CI & installing it

**Comment by cam-itv** [comment]
Can you please elaborate on the internal discussion to change it to the time based versioning format? It would be good for the community to understand the context of the decision. Currently it seems that if you're going to adopt an versioning method, a proper adoption of a widely adopted and understood system, semver, seems like the best fit.

**Comment by markriggins** [comment]
There is nothing to prevent you from doing monthly releases AND using semver.   Some of our projects release weekly.    Just do a minor release monthly, and patch it as needed.   But treating the year as an X release, and forcing a HUGE BREAKING X CHANGE on everyone is going to cause problems. 

1 -- what happens when you really DO need to make a breaking X change?  Are you planning adding extra "little" years between 2017 and 2018?

2 -- How can anyone tell how major and significant the differences are, or the likelihood of breakage when they pick up the latest patch 

3 -- What happens when you need to make a significant minor release in mid-month for a security fix? 

4 -- what if the change between 17.12.002 and 18.01.001 is a tiny safe change?  We take an X bump for no reason?

5 -- If other packages follow your pattern, then what happens  on Jan 1, 2018?   Is every other package using this ill-conceived scheme going to simultaneously release a new version at midnight?

If version numbers have no meaning, then I suppose they have no meaning.   But I've seen not ONE reason listed as to why semver can't work for docker.

**Comment by friism** [comment]
> what happens when you really DO need to make a breaking X change?

We take API compatibility very seriously, and there's a separate API version that's not changing with the upcoming release. 

Features are not usually removed, and if they are, they're deprecated well in advance. Details here: https://docs.docker.com/engine/#feature-deprecation-policy

>  How can anyone tell [..] the likelihood of breakage when they pick up the latest patch

As mentioned above, we take backwards compatibility seriously. If Docker breaks for you when moving from one version to the next, please open an issue so that the problem can be fixed.

> What happens when you need to make a significant minor release in mid-month for a security fix?

A patch release would be issued, eg. 17.03.1

> what if the change between 17.12.002 and 18.01.001 is a tiny safe change? We take an X bump for no reason

Under this scheme, "17" or "18" doesn't signify the magnitude of the change, it merely marks time.

**Comment by friism** [comment]
> Can you please elaborate on the internal discussion to change it to the time based versioning format?

To improve the predictability and cadence of Docker releases, we're adopting a monthly and quarterly release pattern. We hope this will benefit the project: Instead of waiting an indeterminate period of time after a PR is merged for a feature to be released, contributors will see improvements in the hands of users within a month.

A time-based version is a good way to underscore the change, and to signify the time-based release cadence.

Also: https://github.com/docker/docker/pull/31075#issuecomment-280475219

**Comment by shawnbutts** [comment]
Can someone clarify how a switching to a time based release schedule requires a time based versioning scheme?

Thank you.

**Comment by friism** [comment]
@shawnbutts you're correct that switching the versioning scheme is not a requirement, but since it's a good way to underscore the change, and to signify the time-based release cadence, we decided to introduce it.

**Comment by shawnbutts** [comment]
@friism, in my experience, opaque version schemes tend to create operational headaches. Judging by some of the comments here, I'm not alone.  

There's a lot of time investing in tooling, automation, etc around docker. I would like to have a good level of confidence that docker-compose, a custom shell script, or my automation management of choice isn't going to break with a "yum update".

Can you or someone else point to successful projects where date based version have made things better from an operational perspective?

**Comment by albers** [comment]
My concern about the new version scheme is that each time I will encounter a Docker version, I'll have to perform a mental modulo 4-operation in order to determine whether this is a monthly or a "LTS"/stable release.

**Comment by justincormack** [comment]
I have added a discussion issue for SemVer for the Docker API #31842

**Pull request merged**
