### PR TITLE
Compose file v3.2

### PR DESCRIPTION
**Pull request by dnephin**
Includes changes from #31112, and #30597

Revert the Compose file schema to the version that was released as v3.1
Add the new v3.2 schema with all the new changes

Compose PR for these schemas https://github.com/docker/compose/pull/4616

cc @vdemeester @shin-

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🦁
/cc @vieux @thaJeztah 
@dnephin targeting `17.04` right ?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
I see @cpuguy83 had a question on https://github.com/docker/docker/pull/30597#issuecomment-286262975 so let's wait merging to be sure

**Comment by dnephin** [comment]
That PR is now merged, so merging this as well

**Pull request merged**
