### PR TITLE
Fix image filter

### PR DESCRIPTION
**Pull request by HackToday**
This is related image fix for Propose #19153
for volume related change, would use another patch
to fix that.

Signed-off-by: Kai Qiang Wu(Kennan) wkqwu@cn.ibm.com

### CODE REVIEW

**Comment by HackToday** [comment]
Seems jenkins failed for

08:19:33 gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
08:19:33 ?: p80.pool.sks-keyservers.net: Host not found
08:19:33 gpgkeys: HTTP fetch error 7: couldn't connect: Succes

**Comment by thaJeztah** [comment]
yup, unfortunately the key servers are down (out of our control), causing CI to fail :cry:

**Comment by HackToday** [comment]
seems windows failed unrelated, not sure how to kick another build

**Comment by calavera** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
