### PR TITLE
Bump runc to 2f7393a47307a16f8cee44a37b262e8b81021e3e

### PR DESCRIPTION
**Pull request by crosbymichael**
This bumps master to runc 2f7393a47307a16f8cee44a37b262e8b81021e3e with
the ptrace patch and selinux fixes.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
@crosbymichael vendor check is failing

**Comment by crosbymichael** [comment]
@thaJeztah well i don't know what i'm doing wrong

**Comment by thaJeztah** [comment]
@crosbymichael was wondering it it could be the trailing `.git` in the URL, but that doesn't really make sense I guess

@LK4D4 any ideas?

**Comment by tonistiigi** [comment]
@crosbymichael 2f7393a4 is from v1.13 branch of docker/runc. Shouldn't we include something directly from opencontainers/runc. Master shouldn't need to depend on cherry-picked patches.

**Comment by crosbymichael** [comment]
@tonistiigi no, there is changes needed to make master work

**Comment by tonistiigi** [comment]
@crosbymichael Are these patches at least temporary?

The issue with vendoring seems to be that the included files are much newer than 2f7393a4

**Comment by crosbymichael** [comment]
idk, I told it which commit

**Pull request closed without merging**
