### PR TITLE
Plugin miscellaneous fixes

### PR DESCRIPTION
**Pull request by tiborvass**
This is to unblock #26398

In the plugin config, Capabilities has been moved to
Linux.Capabilities to avoid confusion with Interface.Types[i].Capability

Support for host networking.

Do not try to contact disabled plugin.

Fix various tests

Vendor docker/go-connections#25 to provide better error messages in case unix socket path is too long.

A DeviceCreation boolean has also been added to the config under the Linux field. This could
be changed in the future to be specific to a major number.

Support for devices

### CODE REVIEW

**Comment by vieux** [comment]
@tiborvass tests fail and seems related

**Comment by vieux** [comment]
LGTM when green,

**Comment by anusha-ragunathan** [comment]
Please take care of the following review comments:
1. https://github.com/docker/docker/pull/26398#discussion_r88549759
2. https://github.com/docker/docker/pull/26398#discussion_r88571481
3. https://github.com/docker/docker/pull/26398#discussion_r88569186

**Comment by anusha-ragunathan** [comment]
LGTM when green

**Pull request merged**
