### PR TITLE
Move userns cli test to a separate file, remove experimental flag

### PR DESCRIPTION
**Pull request by liron-l**
Signed-off-by: Liron Levin liron@twistlock.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

/cc @estesp

**Comment by jfrazelle** [comment]
LGTM as long as janky is happy

**Comment by estesp** [comment]
@liron-l this looks good, but one minor nit is that the filename is misspelled for the new file you created.  Right now it shows as: `integration-cli/docker_cli_usrens_test.go`

Maybe you can fix the name and also squash the 2 commits as it doesn't really need to be 2 different commits.

Thanks for this!

**Comment by jfrazelle** [comment]
damn good catch :)

On Mon, Feb 8, 2016 at 1:56 PM, Phil Estes <notifications@github.com> wrote:

> @liron-l <https://github.com/liron-l> this looks good, but one minor nit
> is that the filename is misspelled for the new file you created. Right now
> it shows as: integration-cli/docker_cli_usrens_test.go
>
> Maybe you can fix the name and also squash the 2 commits as it doesn't
> really need to be 2 different commits.
>
> Thanks for this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/pull/20117#issuecomment-181572838>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by liron-l** [comment]
Fixed. Thanks @estesp good catch :+1:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
