### PR TITLE
integration: drain node before stop in TestApiSwarmForceNewCluster

### PR DESCRIPTION
**Pull request by LK4D4**
It's too long to wait for reschedule.
This supposed to fix tests for upcoming 1.12.1 of swarmkit.
ping @aaronlehmann 
docker/swarmkit#1250

### CODE REVIEW

**Comment by aaronlehmann** [comment]
I'm okay with this as a short-term fix but combined with the swarmkit change it will make `TestForceNewCluster` take even longer. It already runs for a very long time. Is there a way we can redesign the test so it doesn't have to wait for the full node expiration timeout? Can we make that timeout configurable so the test can dial it down?

**Comment by LK4D4** [comment]
@aaronlehmann maybe it should be fixed on manager side :/ Like mark all nodes down on forcenewcluster. WDYT?

**Comment by aaronlehmann** [comment]
I don't think we should set all nodes down on "force new cluster", because they may not actually be down. Unknown seems like the right state.

Maybe this test should drain the other manager before reinitializing with `ForceNewCluster`, so it doesn't have to wait for that node to time out.

**Comment by LK4D4** [comment]
@aaronlehmann I used your suggestion. Looks like works.

**Comment by aaronlehmann** [comment]
Yay! Thanks! LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by aaronlehmann** [comment]
Is there a way to make sure this is cherry-picked to 1.12.1? If it isn't, the tests will fail when the swarmkit branch we're preparing for 1.12.1 is vendored.

**Comment by cpuguy83** [comment]
@aaronlehmann It's on the milestone, I think that'll be enough? ping @tiborvass

**Comment by tiborvass** [comment]
@cpuguy83 yeah should be fine

**Pull request merged**
