### PR TITLE
#11176: POST "images/create" will no longer silently fail if 'pull job fails.

### PR DESCRIPTION
**Pull request by dmitri-d**
also fixed similar issue in postImagesPush and postBuild

### CODE REVIEW

**Comment by icecrime** [comment]
@witlessbird I'm sorry, the PR already needs a rebase. Can you please take a look? Thanks!

**Comment by dmcgowan** [comment]
This PR is currently breaking streaming output and this error is received on the cli
~~~
FATA[0012] json: cannot unmarshal string into Go value of type utils.JSONMessage
~~~

**Comment by jfrazelle** [comment]
Seeing as this has been opened for almost 30days with no updates, I am going to close, we still would like to fix this issue, so please open a new PR if you come back and make edits. But I do not think this is the fix we want seeing as it is having a very bad effect on streaming output. Thanks.

**Comment by witlessbird** [comment]
Please see details in the issue that this PR attempts to address. I don't think it is possible to fix this problem without either disabling streaming of responses for POST operations or redesigning of how POSTs are handled (perhaps by using dedicated resources that track status of POSTs?). 

I was hoping that this PR might get the conversation started...

**Comment by dmcgowan** [comment]
Certainly willing to have that conversation since I am in the camp that thinks that interaction is broken as well. Not sure it was clear that was the intent of this PR though. I would suggest opening up the PR as a proposal so we can focus on the design review first, this appeared to be a bug fix.

**Comment by witlessbird** [comment]
@dmcgowan: I created a proposal PR at https://github.com/docker/docker/pull/12145

**Pull request closed without merging**
