### PR TITLE
Fixes 16556 CI failures

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

Sorry, I broke some CI tests from Windows to Linux in https://github.com/docker/docker/pull/16556 which got merged. This should fix Windows CI again.  @icecrime

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Close - still one test failing. Looking...

**Comment by jhowardmsft** [comment]
Fixed that one failure. Windows CI should be green now - waiting

**Comment by jhowardmsft** [comment]
Yup, Windows CI is green. Waiting on Janky and Experimental.

**Comment by calavera** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
