### PR TITLE
add unknown_binary

### LINKED ISSUE #18948: Docker exec fails with status 129 and no message
I'm trying to debug an issue where exec seems to be broken on the latest experimental build. The symptoms are any command seems to fail when exec'd in any container. This works under 1.9. 

I'm currently using devicemapper, but the same issue occurred under AUFS and overlayfs.

This is a clean install of Ubuntu 14.04.3 on AWS, with docker experimental freshly installed via `curl -sSL https://experimental.docker.com/ | sh`.

```bash
ubuntu@ip-10-0-0-54:~$ docker exec -it lox_s3ql_1 bash
DEBU[0019] Calling POST /v1.22/containers/lox_s3ql_1/exec 
DEBU[0019] POST /v1.22/containers/lox_s3ql_1/exec   
DEBU[0019] form data: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["bash"],"Container":"lox_s3ql_1","Detach":false,"Privileged":false,"Tty":true,"User":""} 
DEBU[0019] Calling POST /v1.22/exec/19d9a03caa657a5bce605323e3aed764b071023c2ce59f27e37ad4aa8d7f2c1a/start 
DEBU[0019] POST /v1.22/exec/19d9a03caa657a5bce605323e3aed764b071023c2ce59f27e37ad4aa8d7f2c1a/start 
DEBU[0019] form data: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["bash"],"Container":"lox_s3ql_1","Detach":false,"Privileged":false,"Tty":true,"User":""} 
DEBU[0019] starting exec command 19d9a03caa657a5bce605323e3aed764b071023c2ce59f27e37ad4aa8d7f2c1a in container 1de7586cbd51dd2b78120d6318eeba2e64852cdd8b658124789f62cef0723634 
DEBU[0019] attach: stdin: begin                         
DEBU[0019] attach: stdout: begin                        
DEBU[0019] Calling POST /v1.22/exec/19d9a03caa657a5bce605323e3aed764b071023c2ce59f27e37ad4aa8d7f2c1a/resize 
DEBU[0019] POST /v1.22/exec/19d9a03caa657a5bce605323e3aed764b071023c2ce59f27e37ad4aa8d7f2c1a/resize?h=57&w=206 
DEBU[0020] Exec task in container 1de7586cbd51dd2b78120d6318eeba2e64852cdd8b658124789f62cef0723634 exited with code 129 
DEBU[0020] attach: stdout: end                          
DEBU[0020] attach: stdin: end                           
DEBU[0020] Calling GET /v1.22/exec/19d9a03caa657a5bce605323e3aed764b071023c2ce59f27e37ad4aa8d7f2c1a/json 
DEBU[0020] GET /v1.22/exec/19d9a03caa657a5bce605323e3aed764b071023c2ce59f27e37ad4aa8d7f2c1a/json 
DEBU[0020] Closing buffered stdin pipe  
Exited with 129
```

```bash
ubuntu@ip-10-0-0-54:~$ uname -a
Linux ip-10-0-0-54 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

buntu@ip-10-0-0-54:~$ docker info
DEBU[0089] Calling GET /v1.22/info                      
DEBU[0089] GET /v1.22/info                              
Containers: 6
Images: 30
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-202:1-152966-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.52 GB
 Data Space Total: 107.4 GB
 Data Space Available: 1.827 GB
 Metadata Space Used: 6.308 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.827 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/0.0/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/0.0/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.661 GiB
Name: ip-10-0-0-54
ID: 5BJK:K5XT:TU3Z:SEYM:TLRT:7WV6:G3V4:P4Z7:GAOG:H4VK:SAP4:YEAI
Debug mode (server): true
 File Descriptors: 45
 Goroutines: 66
 System Time: 2015-12-29T04:18:26.982207505Z
 EventsListeners: 0
 Init SHA1: 63f95985c4c8aa697c678e4fcd7aba9a7c2de4de
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker/0.0
WARNING: No swap limit support
Experimental: true
ubuntu@ip-10-0-0-54:~$ uname -a
Linux ip-10-0-0-54 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by jessfraz**
fix #18948

### CODE REVIEW

**Comment by jfrazelle** [comment]
ping @ewindisch

**Comment by cpuguy83** [comment]
Didn't really fix it all the way for me, FYI.
Now I get different shared object denials.

**Comment by jfrazelle** [comment]
can you show me logs? it fixed it for me :(

**Comment by jfrazelle** [comment]
maybe we should not ship the profile... I am not exactly confident in it

**Comment by cpuguy83** [comment]
`/usr/bin/nodejs: error while loading shared libraries: libz.so.1: cannot open shared object file: 
Permission denied` -> hipache

`chown: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied` -> redis

`/bin/bash: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: Permission denied` -> custom go http server

`iptables: error while loading shared libraries: libip4tc.so.0: cannot open shared object file: Permission denied` -> openvpn

`stat: error while loading shared libraries: libselinux.so.1: cannot open shared object file: Permission denied` -> ZNC

```
[ 4467.683288] type=1400 audit(1453135237.971:24014): apparmor="ALLOWED" operation="open" profile="/usr/bin/docker//null-310" name="/etc/ld.so.cache" pid=23946 comm="znc-shim" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 4467.683371] type=1400 audit(1453135237.971:24015): apparmor="ALLOWED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/bin/docker//null-310" name="var/lib/docker/aufs/diff/0d52d6d11e71f65d0aff70efc10d9cbfe97479b15bd2d57357d68bfc17df8ee1/etc/ld.so.cache" pid=23946 comm="znc-shim" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 4467.684643] type=1400 audit(1453135237.975:24016): apparmor="ALLOWED" operation="open" profile="/usr/bin/docker//null-310" name="/lib/x86_64-linux-gnu/libncurses.so.5.9" pid=23946 comm="znc-shim" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 4467.684663] type=1400 audit(1453135237.975:24017): apparmor="ALLOWED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/bin/docker//null-310" name="var/lib/docker/aufs/diff/36fd425d7d8a26bb092cf3ca8c52eb8e47170363f40a3f4e37c9cad401f0e9fe/lib/x86_64-linux-gnu/libncurses.so.5.9" pid=23946 comm="znc-shim" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

With this change, some of my stuff works, some of it doesn't :(

**Comment by jfrazelle** [comment]
ugh ok i dont think we should ship the profile because honestly im in over
my apparmor knowledgee here

**Comment by jfrazelle** [comment]
ok i have added another commit which removes the `docker-engine` profile, i think we should do this for 1.10 because it should have been complain only and no enforced, but since that is not working i think we should wait til i can study TFM and get this working as intended :)

**Comment by jfrazelle** [comment]
this way i can have less anxiety for the release about the profile not working as intended

**Comment by cpuguy83** [comment]
SGTM, it was complain only anyway, so not losing much.

**Comment by cpuguy83** [comment]
Maybe we can do that 2nd commit as a separate PR so we can disable and discuss the first change separately?

**Comment by jfrazelle** [comment]
will do

**Comment by jfrazelle** [comment]
I do think this fixes it tho, and in the case where it didnt i think it just needed to be restarted, because i can nolonger repro with hipache or redis

**Comment by cpuguy83** [comment]
For me, it works on a full reboot... but if I restart docker it fails again.

**Comment by jfrazelle** [comment]
closing im going to redo various things make 1 PR

**Pull request closed without merging**
