### PR TITLE
Add vendor/pkg to .dockerignore

### PR DESCRIPTION
**Pull request by LK4D4**
It's in .gitignore too, so why not

### CODE REVIEW

**Comment by tianon** [comment]
Do you think it'd make sense to just change `.dockerignore` to be a symlink to `.gitignore` so we only have to maintain the list in one place?

**Comment by LK4D4** [comment]
@tianon Maybe, but I'm not sure if syntax is equivalent now. ping @duglin

**Comment by tianon** [comment]
I think all the syntax we're using is. :smile:

**Comment by LK4D4** [comment]
@tianon I tried and it seems like it's billion times slower :) Have no idea why.

**Comment by tianon** [comment]
Ok, that's really bizarre.  Thanks for trying anyhow :innocent: 

LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
