### PR TITLE
Make the RPM spec compatible with downstream packages

### PR DESCRIPTION
**Pull request by oszi**
**\- What I did**
I edited the RPM spec to provide `docker` so it's a drop-in replacement for downstream packages.
Related issue: docker#26059

**\- How I did it**
I used rpmrebuild to test the package as I got an unexpected error trying to do a full build:
`error: %changelog not in descending chronological order`

**\- How to verify it**
You should be able to do this on Fedora and CentOS without conflicts:
`dnf/yum install atomic kubernetes-node` 

**\- Description for the changelog**
Provide docker to be compatible with downstream packages

**\- A picture of a cute animal (not mandatory but encouraged)**
cat

Signed-off-by: David Osztertag

### CODE REVIEW

**Comment by oszi** [comment]
So it seems this could be inconvenient: The older versions conflict with `docker` so they would first have to be uninstalled to be able to install the new version. But I think it's worth it in the next major release otherwise the upstream package breaks the entire ecosystem.

Maybe there is an RPM work around that I don't know about. Any ideas?

**Comment by thaJeztah** [comment]
ping @mlaventure @tiborvass @kencochrane ptal

**Comment by mlaventure** [comment]
I don't know much about the RPM inner workings, maybe @tianon does?

Also, depending on when we switched to `docker-engine` for the package, it may not be a good idea to break the compatibility just yet.

**Comment by oszi** [comment]
@mlaventure, the name of the package will still be `docker-engine` but it will also provide `docker` so all the tools that depend on it can work with the upstream package too. This is a major reason to not use the upstream package as it is now. The thing that breaks is easy upgrade from 1.12 to 1.13.

**Comment by tianon** [comment]
The upgrade should be seamless, right?  The current package would have to be removed for this package to be installed, so `rpm` or `yum` or `dnf` or whatever should be able to figure out that this package replaces the existing one, right?

Regardless, it sounds like `Provides` implies `Conflicts`, so I'm +1 on this change. :+1:

**Comment by kencochrane** [comment]
I am also not an expert at the inner workings of RPM. I defer to @tianon, if he feels it is good. I trust him :)

**Comment by tianon** [comment]
I think GitHub needs to add :sweat_smile: to the list of available reactions for a comment. :sweat_smile: :innocent:

**Comment by oszi** [comment]
@tianon, that's the thing. You would have to do:
```
yum remove docker-engine && yum install docker-engine
```
Nothing is lost of course but a simple `yum upgrade` won't work unless there is a workaround.
Why did it have to conflict with `docker` in the first place?

**Comment by oszi** [comment]
I have in idea: In a minor release - say 1.12.2 - we remove the conflict.
Then the upgrade to 1.13 will be seamless. There is nothing I can think of for <1.12 to 1.13.

**Comment by tianon** [comment]
Ah, that's kind of frustrating.  IIRC, it had to conflict with `docker` originally to ensure that they couldn't be installed concurrently (since they do conflict both in installed binaries and in runtime functionality).

IMO your workaround to do the conflict removal in one release and add provides in a future release makes sense, although I'm not sure whether just adding it to a minor bump of 1.12 would be sufficient (or even acceptable this late in the RCs) -- we'd still need to document the workaround for users going from further back too.  I think we're probably back in @thaJeztah territory (or at least he'll likely know who to loop in for whether that's tenable). :smile:

**Comment by oszi** [comment]
Not as frustrating as not being able to use a lot of things requiring docker. :smile: 

With provides the upstream package would replace (upgrade) the downstream package.
Which is fine in my opinion, since the upstream repo is 3rd-party. Community repos do this too.

That brings up another small problem: The different systemd unit files...
This systemd drop-in makes the upstream and downstream packages interchangeable:
```
[Service]
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-network
EnvironmentFile=-/etc/sysconfig/docker-storage

ExecStart=
ExecStart=/usr/bin/docker daemon \
    $OPTIONS \
    $DOCKER_NETWORK_OPTIONS \
    $DOCKER_STORAGE_OPTIONS
```
But I don't think they have to be 100% compatible. This is just something to note.
Frustrating, indeed...

**Comment by thaJeztah** [comment]
It's too late for 1.12.2, work is in progress on building and testing the GA binaries, so unless there's a _major_ issue discovered before that, the 1.12.2 release will go out the door later today.

I _do_ like this though, so we should think of the most seamless approach possible (doing e.g. the 1.13.0 -> 1.13.1 trick could work)

w.r.t. the unit file, I don't think we should adopt that; we've recommend users to use drop-in files, instead of environment files (which was advised to us by (IIRC) the systemd maintainers as best-practice). Unfortunately, it looks like just about any distro now ignores those best-practices :smile:

**Comment by oszi** [comment]
Should I rebase the PR to only remove the conflict?

**Comment by thaJeztah** [comment]
@oszi yes please, it never hurts to have the PR in a mergeable state

**Comment by thaJeztah** [comment]
@oszi oh! I misunderstood, I thought you meant "merge conflict"

Let's wait for @andrewhsu to have a look as well, to see what he thinks

**Comment by andrewhsu** [comment]
i'll have a look

**Comment by oszi** [comment]
BTW I couldn't find the spec file for docker-engine-selinux, it may need similar changes.

**Comment by andrewhsu** [comment]
I have a concern...I'd like to make sure this scenario does not quietly succeed in installing `docker` as well as `docker-engine`:
```
$ dnf install -y atomic # installs docker-1.10 as a dependency
$ dnf install -y docker-engine-1.12.3
```
Because do not want two docker packages installed at the same time.

Can you test to make sure?

~~~

The selinux spec file is here:
https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine-selinux.spec

**Comment by oszi** [comment]
The situation got a bit more complicated...
On CentOS 7 and Fedora 25 there are multiple packages: docker-latest, docker, docker-common.
Obviously the stable and latest versions use different directories and binaries by default.
Also since F25 the docker package provides docker-engine for similar reasons.
Thus I had to edit and rebase the PR.

Here's how you can test it out, for instance in `oszi/toolbox:fc25`:

```
dnf install atomic skopeo rpmrebuild
# Install the upstream repo (which doesn't support releasever=25 yet so force 24)
dnf download docker-engine-1.12.3-1.fc24.x86_64
# Change the specs in an editor according to the updated changes
rpmrebuild -e -p -n docker-engine-1.12.3-1.fc24.x86_64.rpm
dnf install --allowerasing rpmbuild/RPMS/x86_64/docker-engine-1.12.3-1.fc24.x86_64.rpm
# Test with a dependent app
skopeo inspect docker://oszi/toolbox:fc25
```

Note that the seamless upgrade (without allowerasing) issue we discussed above remains.

**Comment by thaJeztah** [comment]
ping @oszi @andrewhsu what's the status on this one; is this still doable?

**Comment by oszi** [comment]
Well, it's as doable as before but backward compatibility still breaks and there are too many quirks.
It's better to run docker-engine in a system container if you want upstream...
So I think this should be closed. :crying_cat_face:

**Comment by thaJeztah** [comment]
Let me close this for now, but happy to reopen if we can come up with a solution!

**Pull request closed without merging**
