### PR TITLE
remove centos/rhel 6 from rpm builder

### PR DESCRIPTION
**Pull request by jessfraz**
since centos/rhel 6 will not be supported with 1.8.0 we should not build rpms for it

ping @icecrime @tianon

### CODE REVIEW

**Comment by icecrime** [comment]
Good one thanks! LGTM

Contributes to #14365.

**Comment by LK4D4** [comment]
Shouldn't we at least try to support? :)

**Comment by jfrazelle** [comment]
idk.... i mean we could offer the rpm but if it doesnt work idk

On Sun, Jul 19, 2015 at 8:42 PM, Alexander Morozov <notifications@github.com

**Comment by LK4D4** [comment]
dunno, too
maybe we can ask @vbatts too, how he feel about this

**Comment by calavera** [comment]
> Shouldn't we at least try to support? :)

no :smile_cat:

**Comment by vbatts** [comment]
hahaha. RHEL6 support is and will be "best effort". I didn't think pruning code would happen for 1.8, but so it goes.

**Comment by thaJeztah** [comment]
Does this make this redundant as well now; https://github.com/docker/docker/blob/master/contrib/builder/rpm/generate.sh#L83

**Comment by jfrazelle** [comment]
Oh damn that was a huge oversight on my part

**Comment by thaJeztah** [comment]
@jfrazelle sorry for commenting after the merge, I saw it during my commute, but had to run for a train and caught up in other things when I arrived home, lol.

**Comment by jfrazelle** [comment]
No I'm so glad thanks!!! I'll fix it later if no one does before me

**Comment by thaJeztah** [comment]
@jfrazelle created a PR; https://github.com/docker/docker/pull/14746

**Pull request merged**
