### PR TITLE
Fix 'make test-docker-py' error

### LINKED ISSUE #24261: The execution of "make test-docker-py" will fail，If you depend on the proxy to access the Internet.
When I run `make test-docker-py` in my development environment, found that most use cases do not pass,the results are as follows :
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.9 -- py-1.4.31 -- pytest-2.7.2
rootdir: /docker-py, inifile: pytest.ini
plugins: cov
collected 111 items

../../../../../docker-py/tests/integration/api_test.py EEEEEEEEEE
../../../../../docker-py/tests/integration/build_test.py EEEEE
../../../../../docker-py/tests/integration/container_test.py EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEs
../../../../../docker-py/tests/integration/exec_test.py EEEEEEE
../../../../../docker-py/tests/integration/image_test.py EEEEEEEEEs
../../../../../docker-py/tests/integration/network_test.py EEssssEEssEEE
../../../../../docker-py/tests/integration/regression_test.py EEEEEE
../../../../../docker-py/tests/integration/volume_test.py EEEEEEE

==================================== ERRORS ====================================
_________________ ERROR at setup of InformationTest.test_info __________________
/docker-py/tests/integration/conftest.py:30: in setup_test_session
    c.inspect_image(BUSYBOX)
/docker-py/docker/utils/decorators.py:21: in wrapped
    return f(self, resource_id, *args, **kwargs)
/docker-py/docker/api/image.py:143: in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
/docker-py/docker/client.py:150: in _result
    self._raise_for_status(response)
/docker-py/docker/client.py:145: in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
E   NotFound: 404 Client Error: Not Found ("No such image: busybox:buildroot-2014.02")
---------------------------- Captured stderr setup -----------------------------

pulling busybox:buildroot-2014.02
Pulling repository docker.io/library/busybox - None
None - None
   ... ...
```

After examination, I found that when the container is run need to set up a network proxy. Therefore, I modify `DOCKER_FLAGS` in the `Makefile` as follows：
```
DOCKER_FLAGS := docker run --rm -i --privileged $(DOCKER_USERDEF_ENVS) $(DOCKER_ENVS) $(DOCKER_MOUNT)
```
And set the appropriate environment variables in the host
```
export DOCKER_USERDEF_ENVS="-e http_proxy=http://10.10.10.10:80 -e https_proxy=http://10.10.10.10:80 -e no_proxy='127.0.0.1,localhost'"
```

Executed `make test-docker-py` command again, It works! The results are as follows:
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.9 -- py-1.4.31 -- pytest-2.7.2
rootdir: /docker-py, inifile: pytest.ini
plugins: cov
collected 111 items

../../../../../docker-py/tests/integration/api_test.py ..........
../../../../../docker-py/tests/integration/build_test.py .....
../../../../../docker-py/tests/integration/container_test.py ....................................................s
../../../../../docker-py/tests/integration/exec_test.py sssssss
../../../../../docker-py/tests/integration/image_test.py .........s
../../../../../docker-py/tests/integration/network_test.py ..ssss..ss...
../../../../../docker-py/tests/integration/regression_test.py ......
../../../../../docker-py/tests/integration/volume_test.py .......
=========================== short test summary info ============================
SKIP [1] /docker-py/tests/integration/exec_test.py:75: Exec driver not native
SKIP [1] tests/integration/network_test.py:165: API version is too low (< 1.22)
SKIP [1] /docker-py/tests/integration/exec_test.py:43: Exec driver not native
SKIP [1] /docker-py/tests/integration/exec_test.py:27: Exec driver not native
SKIP [1] tests/integration/network_test.py:262: API version is too low (< 1.22)
SKIP [1] tests/integration/network_test.py:238: API version is too low (< 1.22)
SKIP [1] /docker-py/tests/integration/exec_test.py:117: Exec driver not native
SKIP [1] tests/integration/container_test.py:1048: API version is too low (< 1.22)
SKIP [1] /docker-py/tests/integration/exec_test.py:59: Exec driver not native
SKIP [1] tests/integration/network_test.py:214: API version is too low (< 1.22)
SKIP [1] tests/integration/image_test.py:216: Doesn't work inside a container - FIXME
SKIP [1] /docker-py/tests/integration/exec_test.py:11: Exec driver not native
SKIP [1] tests/integration/network_test.py:189: API version is too low (< 1.22)
SKIP [1] tests/integration/network_test.py:129: API version is too low (< 1.22)
SKIP [1] /docker-py/tests/integration/exec_test.py:93: Exec driver not native

=================== 96 passed, 15 skipped in 157.64 seconds ====================
---> Making bundle: .integration-daemon-stop (in bundles/1.12.0-dev/test-docker-py)
++++ cat bundles/1.12.0-dev/test-docker-py/docker.pid
+++ kill 5880
+++ /etc/init.d/apparmor stop
Clearing AppArmor profiles cache:.
All profile caches have been cleared, but no profiles have been unloaded.
Unloading profiles will leave already running processes permanently
unconfined, which can lead to unexpected situations.

To set a process to complain mode, use the command line tool
'aa-complain'. To really tear down all profiles, run the init script
with the 'teardown' option."
```

### PR DESCRIPTION
**Pull request by miaoyq**
Fixes #24261 @thaJeztah 

Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon wdyt? Also have a look at the use-case in https://github.com/docker/docker/issues/24261

**Comment by jfrazelle** [comment]
this makes no sense...

**Comment by jfrazelle** [comment]
can we name it HTTP_PROXY and make it a real env var

**Comment by miaoyq** [comment]
@jfrazelle   :+1:  `HTTP_PROXY ` is more appropriate,  I will modify `DOCKER_USERDEF_ENVS` as `HTTP_PROXY`.  As follow: 

`DOCKER_FLAGS := docker run --rm -i --privileged  $(HTTP_PROXY) $(DOCKER_ENVS)  $(DOCKER_MOUNT)`

**Comment by jfrazelle** [comment]
Well shouldn't it be added to DOCKER_ENVS

On Wednesday, July 6, 2016, MiaoYanqiang <notifications@github.com> wrote:

> @jfrazelle <https://github.com/jfrazelle> 👍 HTTP_PROXY is more
> appropriate, I will modify DOCKER_USERDEF_ENVS as HTTP_PROXY. As follow:
>
> DOCKER_FLAGS := docker run --rm -i --privileged $(HTTP_PROXY)
> $(DOCKER_ENVS) $(DOCKER_MOUNT)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/pull/24280#issuecomment-230956054>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABYNbKwkfZDnt97p7gw7tBBLuTpWrS4fks5qTFjwgaJpZM4JD1RH>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by miaoyq** [comment]
@jfrazelle  Oh, I get it,  but the `HTTP_PROXY` need be modified to `http_proxy`,  As follow:

```
DOCKER_ENVS := \
        -e BUILDFLAGS \
        -e KEEPBUNDLE \
        -e DOCKER_BUILD_GOGC \
        -e DOCKER_BUILD_PKGS \
        -e DOCKER_DEBUG \
        -e DOCKER_EXPERIMENTAL \
        -e DOCKER_GITCOMMIT \
        -e DOCKER_GRAPHDRIVER=$(DOCKER_GRAPHDRIVER) \
        -e DOCKER_INCREMENTAL_BINARY \
        -e DOCKER_REMAP_ROOT \
        -e DOCKER_STORAGE_OPTS \
        -e DOCKER_USERLANDPROXY \
        -e TESTDIRS \
        -e TESTFLAGS \
        -e TIMEOUT \
        -e http_proxy \
        -e https_proxy \
        -e no_proxy
```

**Comment by jfrazelle** [comment]
seems ok to me

On Wed, Jul 6, 2016 at 8:21 PM, MiaoYanqiang <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> Oh, I get it, but the HTTP_PROXY
> need be modified to http_proxy, As follow:
>
> DOCKER_ENVS := \
>         -e BUILDFLAGS \
>         -e KEEPBUNDLE \
>         -e DOCKER_BUILD_GOGC \
>         -e DOCKER_BUILD_PKGS \
>         -e DOCKER_DEBUG \
>         -e DOCKER_EXPERIMENTAL \
>         -e DOCKER_GITCOMMIT \
>         -e DOCKER_GRAPHDRIVER=$(DOCKER_GRAPHDRIVER) \
>         -e DOCKER_INCREMENTAL_BINARY \
>         -e DOCKER_REMAP_ROOT \
>         -e DOCKER_STORAGE_OPTS \
>         -e DOCKER_USERLANDPROXY \
>         -e TESTDIRS \
>         -e TESTFLAGS \
>         -e TIMEOUT \
>         -e http_proxy \
>         -e https_proxy \
>         -e no_proxy
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/pull/24280#issuecomment-230968941>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABYNbGozmWQOlNXUoYrratJhGHL3AK6xks5qTHCzgaJpZM4JD1RH>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by tianon** [comment]
I believe both the lowercase and the all-caps versions are supported
differently depending on the tool used (some support one or the other, but
most support both, IIRC).

**Comment by thaJeztah** [comment]
Correct, I remember checking what the correct "case" is (upper/lowercase) for those env vars for the "build time args" PR, and apparently, there is no official standard; both can be used, but it depends on the software using it (some accept lower, other uppercase :disappointed:). So to be safe, we probably need to set all variants

**Comment by miaoyq** [comment]
I have set all variants of the network proxy.   PTAL  Thanks! @thaJeztah @tianon 
```
DOCKER_ENVS := \
        -e BUILDFLAGS \
        -e KEEPBUNDLE \
        -e DOCKER_BUILD_GOGC \
        -e DOCKER_BUILD_PKGS \
        -e DOCKER_DEBUG \
        -e DOCKER_EXPERIMENTAL \
        -e DOCKER_GITCOMMIT \
        -e DOCKER_GRAPHDRIVER=$(DOCKER_GRAPHDRIVER) \
        -e DOCKER_INCREMENTAL_BINARY \
        -e DOCKER_REMAP_ROOT \
        -e DOCKER_STORAGE_OPTS \
        -e DOCKER_USERLANDPROXY \
        -e TESTDIRS \
        -e TESTFLAGS \
        -e TIMEOUT \
        -e HTTP_PROXY \
        -e HTTPS_PROXY \
        -e NO_PROXY \
        -e http_proxy \
        -e https_proxy \
        -e no_proxy
```

**Comment by thaJeztah** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
