### PR TITLE
Fix: docker -d -h start daemon instead of showing help menu

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Pull request for Issue: https://github.com/docker/docker/issues/11120

Shishir

### CODE REVIEW

**Comment by tiborvass** [comment]
This fix is too specific.

IMHO you should just `flHelp` from `docker/flags.go`, which apparently is not used right now? So maybe this is just a regression.

**Comment by shishir-a412ed** [comment]
@tiborvass 
yeah that makes sense. Updated the code.

**Comment by ahmetalpbalkan** [comment]
what happens if we move the check outside and have it before the `if *flDaemon {..} ` block? would it show the usage string for docker even though we ask for `docker subcmd --help`?

**Comment by shishir-a412ed** [comment]
@ahmetalpbalkan I believe it would.
I think the CmdHelp() function handles the help menu for docker subcommands.

**Comment by ahmetalpbalkan** [comment]
LGTM (not a maintainer)

> Note: CI may take a bit longer, a PR queued things a bit.

**Comment by jfrazelle** [comment]
can you add fixes #9677 to your original comment

**Comment by tiborvass** [comment]
@jfrazelle unfortunately this does not fix #9677 :(

LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by tiborvass** [comment]
@shishir-a412ed next time please use "Fixes #11120" in the first description comment so that the issue gets automatically closed :)

**Pull request merged**
