### PR TITLE
Remove more registry v1 code (carry 39371)

### PR DESCRIPTION
**Pull request by thaJeztah**
closes https://github.com/moby/moby/pull/39371

rebase/carry of https://github.com/moby/moby/pull/39371, with an extra commit to check if preserving some of the fallback behavior fixes the failures on that PR

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tiborvass @tonistiigi @cpuguy83 ok, looks like it's green with the commit I added; kept it separate, but let me know if you want it squashed with one of the other ones (if the change in the last commit looks good)

**Comment by thaJeztah** [comment]
Rebased, to get a fresh run of CI

**Comment by thaJeztah** [comment]
Rebased (again)

**Review by tonistiigi — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
