### PR TITLE
devicemapper: set flags based on udev sync support

### PR DESCRIPTION
**Pull request by vbatts**
per #10195 this will disable fallback on devicemapper for device node creation when udev sync is supported. This eliminates the risk of udev vs. devicemapper race _only_ when sync is supported.

If sync is _not_ supported, then the race will likely be hit.

relates to #4036 

Ping @unclejack

### CODE REVIEW

**Comment by icecrime** [comment]
Naive question (I honestly don't know much about these changes): is it expected that functions that used to have a `flag` value of `0` now get `DmUdevDisableSubsystemRulesFlag | DmUdevDisableDiskRulesFlag | DmUdevDisableOtherRulesFlag`?

I'm just wondering because it contradicts the PR title in some way (udev sync is taken into account for flags **and** a new set of flags is used overall).

**Comment by vbatts** [comment]
@icecrime thanks. I copied from a commit where I was using the same flags from `CreatePool` on all flags that get set. I've just pushed an updated commit that is closer behavior to what has been, except that all flags will have "basic" flags which will be determined by the sync support. 
PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by rhvgoyal** [comment]
@vbatts 

If sync is supported, then there should not be any need to disable fallback. If udev is doing job right, then libdm will not create nodes. If udev is not doing job right, then libdm will create the nodes and things should work fine.

So to me in fact it looks like a good thing to keep fallback mode. This will make things work even if
udev is not working properly and flag warnings accordingly so that people have a chance to look udev issues.

So not sure what do we gain by removing fallback mode when udev sync is enabled.

**Comment by unclejack** [comment]
@rhvgoyal Is there any risk that devicemapper would fall back to creating the nodes even if it sees that udev is working properly?

**Comment by rhvgoyal** [comment]
@unclejack 

If libdm falls back to creating nodes even if udev is working properly, then it is a bug in libdm and should be fixed, AFAIK.

**Comment by rhvgoyal** [comment]
@unclejack 

Let me qualify previous statement. That would be the case when we know udev_sync is not zero and libdm expects udev to create nodes.

**Comment by vbatts** [comment]
@rhvgoyal from what peter said, if sync is working then using DM_UDEV_DISABLE_LIBRARY_FALLBACK will eliminate the chance of the race. 

> Now, why that happens? By default, libdevmapper (still) operates in
> "fallback mode" where it checks whether the node/symlink is created
> by udev and if not, libdevmapper creates the nodes/symlinks on his own
> ("fixing" possible udev failure). To disable this fallback in libdevmapper,
> you need to use DM_UDEV_DISABLE_LIBRARY_FALLBACK flag for dm_task_set_cookie
> call. If you use this flag, libdevmapper will completely rely on udev
> to create the nodes/symlinnks and it won't do any further checks if
> udev did that properly or not.
> 
> ( LVM already disables this fallback by default now, but it's not disabled
> by default in libdevmapper so any libdevmapper should still force it with
> that flag. Well, maybe it's time we should switch to using this flag by
> default in libdevmapper too!)

**Comment by vbatts** [comment]
in other words, when `dm_udev_get_sync_support != 0`, we should provide the flag `DM_UDEV_DISABLE_LIBRARY_FALLBACK`, which is what this PR does.

**Comment by unclejack** [comment]
@rhvgoyal @vbatts Thanks! I'll test this PR. While I'm doing that, the discussion can continue.

**Comment by rhvgoyal** [comment]
@vbatts 

Where did peter say above that there are races with udev_sync !=0 and DM_UDEV_DISABLE_LIBRARY_FALLBACK not set by caller?

He is just explaining that how fallback mode works and what's the current default. He is also suggesting that may be libdm default should be changed. 

If they change the default, then it is fine but I still don't understand that why we should have to force to disable fallback mode.

If we can prove that fallback mode with udev leads to races, then we should fix those races by fixing libdm.

But so far I don't think we have any data which proves this?

**Comment by rhvgoyal** [comment]
@vbatts 

I guess you are referring to "so any libdevmapper should still force it with
that flag".

I will check with Peter. If am not convinced. If this is libdm default, then why should a caller change it without a good reason.

If there are races with udev, then fallback as a default does not make any sense for libdm.

**Comment by rhvgoyal** [comment]
@vbatts 

In a follow up mail, peter also had said following. (When I explicitly asked that why should we disable fallback mode)

***************************************
> Ok, got it. So I don't have to specify DM_UDEV_DISABLE_LIBRARY_FALLBACK
> in docker code. Because if it is enabled by default, then it will kick
> in only if udev does not do its job. And I guess that's the behavior
> we want.
>

Yes, but then you need to be sure that whenever you (or your users)
hit a message like:

"... not set up by udev. Falling back to direct node creation"
"... not removed by udev. Falling back to direct node removal"
"... should have been renamed to ... by udev, but old node is still present.
Falling back to direct old node removal."

...and similar messages, there's something wrong going on with udev
and/or udev rules and/or udev synchronization and it needs fixing.

These are warning-level messages from libdevmapper,so they should be
always printed for users if this happens (so be sure to have the logging
enabled/registered in libdevmapper).
***************************************

So if we see warning messages then it is a problem with udev. In fact this sounds like a good thing to me as libdm is warning us about udev issues which might make it easier to identify problems and fix it.

So I still can't see what's the downside of keeping fallback mode with udev_sync != 0

**Comment by vbatts** [comment]
okay. I missed the expectation of no setting the flag, and only looking for those warnings. We will need #10193 then, to ensure we see those warnings. And in that case, perhaps we can just make this PR for  dbb642b and 4cfe9df, and drop 745b44c.

**Comment by vbatts** [comment]
closing for #10222

**Pull request closed without merging**
