### PR TITLE
[WIP] overlay2: fix for Linux 4.19 (metacopy=off)

### LINKED ISSUE #480: Unable to docker build on Linux kernel 4.19
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Build without error

### Actual behavior
When run `docker build -t testing .` this error appears on Linux kernel 4.19:
```
dpkg: error: error creating new backup file '/var/lib/dpkg/status-old': Invalid cross-device link
E: Sub-process /usr/bin/dpkg returned an error code (2)
The command '/bin/sh -c apt-get install -y locales &&     sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &&     locale-gen' returned a non-zero code: 100
```
On Linux kernel v4.18 it works. I have tested docker v18.06 and v18.09.

### Steps to reproduce the behavior
On a Linux kernel 4.19 use this Dockerfile:
```
FROM ubuntu:16.04

# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive

RUN echo "deb mirror://mirrors.ubuntu.com/mirrors.txt xenial main restricted universe multiverse" \
        > /etc/apt/sources.list && \
    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-updates main restricted universe multiverse" \
        >> /etc/apt/sources.list && \
    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-security main restricted universe multiverse" \
        >> /etc/apt/sources.list && \
    apt-get update

# Ensure UTF-8 lang and locale
RUN apt-get install -y locales && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
```
I run `docker build -t testing .`.

**Output of `docker version`:**
```
Client:
 Version:           18.09.0-ce
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        4d60db472b
 Built:             Fri Nov  9 00:05:34 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       4d60db472b
  Built:            Fri Nov  9 00:05:11 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 32
Server Version: 18.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b.m
runc version: 079817cc26ec5292ac375bb9f47f373d33574949
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.1-1-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.41GiB
Name: javier-homepc
ID: 6ULE:QTFG:T6YJ:QIRD:URUL:GEZR:ZWUK:R2J2:NAWY:ALEY:PSSJ:EW4P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Further information
It's a physical machine with Manjaro Linux based on Arch Linux OS (docker is from Arch Linux and Linux kernel from Manjaro)

### PR DESCRIPTION
**Pull request by kolyshkin**
Linux Kernel v.4.19 introduces a new overlay feature called metadata
copy up (or just metacopy). Quoting kernel docs:
    
> When metadata only copy up feature is enabled, overlayfs will only copy
> up metadata (as opposed to whole file), when a metadata specific operation
> like chown/chmod is performed. Full file will be copied up later when
> file is opened for WRITE operation.
    
Until the kernel commit d5791044d2e574 ("ovl: Provide a mount option
metacopy=on/off...") this feature was disabled by default.
    
Unfortunately for Docker, since the above commit the feature is on
by default in case `CONFIG_OVERLAY_FS_METACOPY=y` is set
(which is up to a distro vendor), and it is not working with the naive diff driver:
`docker build` leads to errors like this:
    
> dpkg: error: error creating new backup file '/var/lib/dpkg/status-old': Invalid cross-device link
    
To fix, use the same mechanism as in commit 8422d85087bfa
("overlay2: use index=off if possible"), i.e. check if the
kernel module parameter is present, and if it is, add
`metacopy=off` to mount options.

Should fix https://github.com/docker/for-linux/issues/480

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Do we want these for the `overlay` driver as well, or not worth bothering? (It would only be useful for people that are running overlay on a modern kernel (where they should really be running overlay2)

**Comment by kolyshkin** [comment]
I would reluctantly say no -- people who use newer kernels should use overlay2, people who use older kernels should not have this problem.

**Comment by thaJeztah** [comment]
- Failure on janky is `DockerSwarmSuite.TestAPISwarmLeaderElection`, which is a known flaky test
- PowerPC failed on the same, but also on another flaky; `DockerSwarmSuite.TestAPISwarmLeaderElection`

Windows is probably a flaky as well, but I'll restart

```
23:00:46 FAIL: docker_cli_start_test.go:189: DockerSuite.TestStartReturnCorrectExitCode
23:00:46 
23:00:46 docker_cli_start_test.go:199:
23:00:46     c.Assert(exitCode, checker.Equals, 12, check.Commentf("out: %s", out))
23:00:46 ... obtained int = 125
23:00:46 ... expected int = 12
23:00:46 ... out: time="2018-11-29T23:00:39Z" level=error msg="error waiting for container: EOF" 
23:00:46 
```

**Comment by kolyshkin** [comment]
> Windows is probably a flaky as well, but I'll restart

Nope, it seems that Windows environment has changed to look like Linux. If you look inside the test case you'll see there's a special case for Windows (different expectations), and now it seems like the special case is not needed, i.e. Windows returns what Linux does. I have found it elsewhere yesterday, but don't feel comfortable enough to do windows changes.

Maybe Windows was upgraded on CI?

**Comment by kolyshkin** [comment]
> don't feel comfortable enough to do windows changes.

Well it's bad excuse in fact; let me prepare a PR

**Comment by thaJeztah** [comment]
Perhaps related to https://github.com/moby/moby/pull/38278, but I think it was green. Could be another PR that was merged out of order, and had outdated test results. suspecting https://github.com/moby/moby/pull/37982 and/or https://github.com/moby/moby/pull/37638

**Comment by kolyshkin** [comment]
Yes, it might very well be a busybox update! Others look unrelated.

**Review by tonistiigi — APPROVED** [review]

**Comment by tonistiigi** [comment]
What about the `overlay` ("1") driver. Is that affected too?

**Comment by cpuguy83** [comment]
This may not be neccessary. Kernel fix is here: https://www.spinics.net/lists/linux-unionfs/msg06316.html

**Comment by thaJeztah** [comment]
Marked this "WIP" for the meantime. Thanks!

**Comment by kolyshkin** [comment]
It [appears](https://github.com/docker/for-linux/issues/480#issuecomment-448899590) that the abovementioned patch is merged into Linux 4.19.11 and so it fixes the issue meaning we probably don't need this kludge.

Let's wait for some more time to see the "it's fixed" from users as that kernel was just released and haven't made its way to distros yet.

**Comment by kolyshkin** [comment]
This is a kernel bug that is fixed in kernel >= 4.19.11

**Pull request closed without merging**
