### PR TITLE
Add DOCKER_OPTIONS

### PR DESCRIPTION
**Pull request by ghost**
This makes it possible to build docker with different docker options.

Signed-off-by: Hu Tao hutao@cn.fujitsu.com

### CODE REVIEW

**Comment by tianon** [comment]
What options did you have in mind?  I'm having a little trouble seeing a use-case here that's common enough to warrant Yet-Another-Flag for our `Makefile` (we already get complaints that there are too many / our `Makefile` is too complex).

**Comment by taohu** [comment]
I'm now using -H tcp://xxx because my docker has trouble connecting to /var/run/docker.sock.

**Comment by tianon** [comment]
Why not set DOCKER_HOST=tcp://xxx in the shell so it works outside of the
Makefile too?

**Comment by taohu** [comment]
I'm just unaware of it  :(

Not sure whether other options are useful or not, so closing it.

**Pull request closed without merging**
