### PR TITLE
Fix integration test case for `docker service`

### PR DESCRIPTION
**Pull request by WeiZhang555**
Test `docker service` command with more suitable func, and make some
cleanings after test.

Signed-off-by: Zhang Wei zhangwei555@huawei.com

### CODE REVIEW

**Comment by mavenugo** [comment]
@WeiZhang555 `docker service` ux is undergoing some basic changes as part of the network ux changes. lets wait for it to see if how it impacts this PR.

**Comment by tiborvass** [comment]
@mavenugo are you suggesting we close this PR for now?

**Comment by tiborvass** [comment]
@WeiZhang555 thank you very much for your contribution! Unfortunately @mavenugo is currently working on completely redoing the whole UX for `docker service` and as a result, the entire code related to docker service, will be changed. Therefore it doesn't make sense for us to merge this PR only to remove the lines shortly after. Sorry about that.

As soon as madhu's PR is open, I'll reference it here so you can also provide your input.

Thanks again for your work and please keep contributing :)

**Comment by WeiZhang555** [comment]
@tiborvass Fine, I'll keep watching :)

**Pull request closed without merging**
