### PR TITLE
Fix --ipc=host dependency on /dev/mqueue existing

### PR DESCRIPTION
**Pull request by burke**
Since #15862, containers fail to start when started with `--ipc=host` if `/dev/mqueue` is not present. This change causes docker to create container-local mounts for `--ipc=host` containers as well as in the default case.

Three other options (which I consider undesirable for various reasons):
1. Warn the user more explicitly if `/dev/shm` or `/dev/mqueue` is not mounted, with instructions on mounting it;
2. Mount `/dev/shm` and/or `/dev/mqueue` for the user, if necessary; or
3. Check for presence of `/dev/{shm,mqueue}` when `--ipc=host` is specified, preferring to use the global mounts, but falling back to creating container-root mounts if they are not found.

Option 3 sounds fine from a behaviour perspective, but it adds nontrivial complexity.

cc @calavera @mrunalp

### CODE REVIEW

**Comment by mrunalp** [comment]
I would say 1 is a good option here. I don't like 3 as we are creating container ipc mounts when user has explicitly asked us not to.

**Comment by burke** [comment]
Ok, I revised the PR to just print a more obvious error:

> Error response from daemon: Cannot start container ce7df2ee53ac29590df2cb6572f57c790bcc7ce061900842543c566902df364d: /dev/mqueue is not mounted, but must be for --host=ipc

Part of me feels like it's not really appropriate to ask users to mount devices for docker to work properly, especially since it appears to be default on ubuntu (14.04 at least) to not mount `/dev/mqueue` -- but then, `--ipc=host` is a pretty niche use-case, so it's probably not an issue.

**Comment by calavera** [comment]
I'm okay with setting a better error message for this. I think those need to go into the errors package though:

https://github.com/docker/docker/tree/master/errors

**Comment by tiborvass** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
