### PR TITLE
Proposal: Add volume ls/inspect/rm/create commands

### PR DESCRIPTION
**Pull request by cpuguy83**
`docker volumes ls` - list all volumes
Can be used with --filter dangling=true to list volumes not in use

`docker volumes create` - create volumes
Can set, `--name`, `--path`, `--mode`.  Can also be used with no
arguments to have everything auto generated

`docker volumes rm <volume name>` - Remove a volume
Volumes in use by containers cannot be removed.
Bind-mounts cannot be removed. (May want to have a way to remove just
the bind-mount config. Else this does seem to cause issues with tests)

`docker volumes inspect <volume name>` - Inspect a volume/get its config
Supports `--format` just like container inspect.

`docker run` can be used to either call a volume by name as `docker run
-v <volume name>:<mount point>` or with `docker run --volumes-from
<volume alias>:<mount point>[:<mode>]`
`docker run -v <path>` will create a volume with a generated name, just
as `docker volumes create` with no args.

All existing APIs/UI will work as normal.
There is no breakage in these changes.

Implements Proposal https://github.com/docker/docker/issues/8363

### CODE REVIEW

**Comment by asiragusa** [comment]
@cpuguy83 An use case not listed here is mounting a subset of the volume into the container. This can be useful when mounting large DFS which contains files from different users.

This can be achieved maybe with a -v <volume alias>:<source path>:<mount point>[:<mode>] argument or something similar.

Actually I think that it may be possible to create a data container that mount-binds the needed subpath, then to share this with the container, but this seems to me quite more complicated than the latter proposal and more expensive in terms of resources, as we have to instantiate a container just for a mount-bind.

Any thoughts?

**Comment by cpuguy83** [comment]
@asiragusa Hmm... I'm not sure. That you may just want to bind-mount from the host, or create a separate volume for.

**Comment by cpuguy83** [comment]
@shykes What i'm thinking in terms of names at the moment is that naming would be optional and would not use a name generator.
The idea here is really more the name is more of a label than anything else so someone can come back to it and know what it was, but with a generated name this doesn't work since the generated name means nothing, it might as well be an ID number.

What is important, however, is the containers that are using and that have used that volume, and probably the name of the container that created it (if it was created with docker run). So we can track the history of the volume instead of a specific name.

And of course, someone can name a volume if they like (if created through `docker volume create`).

**Comment by asiragusa** [comment]
@cpuguy83 The problem is more complicated than that. I need Docker-backed data volumes to be able to use Docker's CoW features.

The workaround I found to achieve this is the following:

```
DATA_ID=$(docker run -d --name my-data-volume base-data-image sh -c 'while true; do sleep 1; done')
ROOTFS=/var/lib/docker/btrfs/subvolumes/$DATA_ID
docker run -d -v $ROOTFS/data:/data worker-image
```

This way I will be able to snapshot the data image with:

```
docker commit $DATA_ID snapshotted-data-img
docker push snapshotted-data-img
```

This means incremental backups of my stateful website datas, wow :)

It would really nice to achieve this directly with Docker's cli instead of using this "hack".

Is it possible to start multiple Docker daemons with its storage driver backed in a DFS that supports CoW like Ceph + Btrfs or I will encounter many race conditions doing that?

If it's actually possible, it would be nice to start the daemon with multiple storage drivers and doing the following: 

```
docker run -s distributed-storage-driver-id --name my-data-volume base-data-img
docker run -d --volumes-from my-data-volume:/data:/data worker-image
```

Without the -s docker would use the default (local) storage driver.

Btw I can still achieve this with a single docker daemon that acts as a master node, thus I may actually do:

```
$IMG_ID=$(docker run -h master --name data data-img)
ROOTFS=/dfs/var/lib/docker/btrfs/subvolumes/$IMG_ID
docker run -d -v $ROOTFS:/data:/data worker-img
```

But I'll have a single point of failure and I may overload the node that runs the master, slowing down all my infrastructure.

**Comment by binocarlos** [comment]
@asiragusa I have a suggestion to make to you but its off-topic and I don't want to hijack this thread with it.  Can you reach out on freenode #clusterhq or email me directly (from profile) - thanks!

**Comment by pmoust** [comment]
Is there an ETA on getting this upstream?

**Comment by dreamcat4** [comment]
Also: Can we make sure that the output of `docker volume ls` is fully `grep`-able? So that it can be piped on to other unix commands. E.g. that nothing is being ommitted (for human readability). Or else an optional `--no-trunc` flag. Many thanks.

Previously raised issues talking about this elsewhere. On @cpuguy83's  `docker-volumes` repo. And also the `talk2docker` 3rd party tool:

https://github.com/ailispaw/talk2docker/issues/9

https://github.com/cpuguy83/docker-volumes/issues/20

**Comment by rhvgoyal** [comment]
@cpuguy83 

I am wondering why volumes have to be backed by vfs dir only. Like images, can't we create volumes from graphdriver. Say, I might want to carve out a space from thin pool and then give it to a container for storage?

The use case I am interested in solving is how to mount images/rootfs of a container so that some external tools can examine it.

 I was thinking of that can we convert images into volumes. That is just take a snapshot of image and now we have a read/write volume. And this volume can be bind mounted inside a container which can examine the contents of an image.

Don't want to use "docker save" because it will create copy of image and I wanted a fast operation where image can be snapshotted instead of creating a copy.

**Comment by yasker** [comment]
@rhvgoyal 

That's exactly what we're planning to do. Without upstream docker support, we currently only able to write a tool of our own, using device mapper and thin-pool, and use host bind mount to mount the volume to docker. By this way, we can create a volume using device mapper, and able to snapshot and back it up. That's a work at very early stage at: https://github.com/yasker/volmgr

And I've also tried to use device mapper as volume driver, as in https://github.com/docker/docker/compare/master...yasker:volumedriver

But I didn't submit the PR for it since we're expecting the new docker plugin mechanism can be used in this case, as in: https://github.com/cpuguy83/docker/pull/3/files

**Comment by dreamcat4** [comment]
@yasker So how does your tool, ***volmgr*** compare to using the `duplicity` program for incremental backups? With the `duplicity` tool I could back up my docker volumes to many possible target URL destinations (including FTP, amazon s3 etc). And the backups can be encrypted too.

What are the pros / cons ?

**Comment by dreamcat4** [comment]
@yasker So how does your tool, ***volmgr*** compare to using the `duplicity` program for incremental backups? With the `duplicity` tool I could back up my docker volumes to many possible target URL destinations (including FTP, amazon s3 etc). And the backups can be encrypted too.

What are the pros / cons ?

**Comment by dreamcat4** [comment]
@yasker So how does your tool, ***volmgr*** compare to using the `duplicity` program for incremental backups? With the `duplicity` tool I could back up my docker volumes to many possible target URL destinations (including FTP, amazon s3 etc). And the backups can be encrypted too.

What are the pros / cons ?

**Comment by dreamcat4** [comment]
@yasker So how does your tool, ***volmgr*** compare to using the `duplicity` program for incremental backups? With the `duplicity` tool I could back up my docker volumes to many possible target URL destinations (including FTP, amazon s3 etc). And the backups can be encrypted too.

What are the pros / cons ?

**Comment by dreamcat4** [comment]
Excuse me. Sorry about the duplicate postings.

**Comment by yasker** [comment]
@dreamcat4 volmgr would provide snapshot on block device level, rather than filesystem level.

And you would able to have the whole history of snapshots, and easily rollback to any of them.

The backup of snapshots would be delta, so only changed blocks would be backed up for the new snapshots, however you would always reconstruct the whole volume from any of snapshots

**Comment by rhvgoyal** [comment]
@yasker

Conceptually using a volumedriver  as backend for managing volumes makes sense to me. In fact this would just be a graph driver used for managing volumes (In the same way as images and containers have graph driver in the backend for storage). So in similar way, I would imaging that we should have volumes using a graph driver in the backend for creating/deleting/mounting volumes.

**Comment by yasker** [comment]
@rhvgoyal 

Agreed. In fact current device mapper graph driver works pretty well in my limited test, so it really make sense to me to just use graph driver for volume management.

And that's my original patch did, as in https://github.com/docker/docker/compare/master...yasker:volumedriver . It just substituted vfs driver to any driver specified by user, and create separate directory for it, in order to not confused with graphdriver root managed images.

And by using things other than vfs driver, it would enable many other things we can do with volume, like snapshot.

**Comment by rhvgoyal** [comment]
@yasker

So why not use graphdriver to manage volumes too. For example, if storage driver is device mapper, it will manage images, containers as well as volumes. 

Driver does not care whether a thin device is image, container, or volume. It is just an hash id and associated thin device.

**Comment by rhvgoyal** [comment]
@yasker

May be that's what you are doing. I will have to spend some time on your code.

**Comment by cpuguy83** [comment]
@rhvgoyal Indeed there is work going on to be able to use different drivers for volumes (as was requested by @shykes in the design review above), as well as a plugin loading mechanism that can hook into (and short-circuit) the current volume behavior.

**Comment by asiragusa** [comment]
@rhvgoyal look at my comment, I did exactly what you say, but it's kind-of tricky, because you have to find out the path of the root filesystem, and it depends on the storage driver you use.

Btw it would be a nice feature to have in Docker's cli. It would be even better if it could be used with a DFS and multiple Docker daemons, one for each mountpoint...

**Comment by yasker** [comment]
@rhvgoyal 

We'd love to see graphdriver for volume in upstream, but we're afraid it probably would not be a quick process. So currently we're building around docker, using our *volmgr* to create device mapper backed volume, and mount it to docker container through host bind mount. In this way we can control the volume and would able to do snapshot and other things to it, to compensate the lacking of using device mapper as volume driver in docker.

**Comment by rhvgoyal** [comment]
@yasker 

I understand that you are doing it outside the docker. But in the long term, I think it is a good idea to make docker volume management more powerful where it allows for volumes being backed by graphdriver (apart from volume better volume management as this pull request inteneded to).

@cpuguy83 

What's your thoughts on volumes being managed by graphdriver? Is this something you would like to see in docker?

**Comment by cpuguy83** [comment]
@rhvgoyal They are managed by a graphdriver today, just that it's hardcoded to the vfs graphdriver. :)

I think I would prefer the complexity introduced by providing support for more advanced drivers (dm, btrfs, zfs) be handled via extensions and not from the main volume API.
Volumes would be specifically a path on the host, and how the path gets there is determined by the loaded extensions and whatever metadata is attached.

**Comment by rhvgoyal** [comment]
@cpuguy83 

Will this extension based volume management allow me to hook into same thin pool as being used for images and containers. Reason being that I am looking to be able to snapshot an image and create a volume. So that I can mount that volume into another container and look at the image contents. Taking a snapshot of image will be possible only when volumes are being managed in the same thin pool as images.

**Comment by cpuguy83** [comment]
@rhvgoyal I'm not sure I have enough knowledge on the dm graphdriver to answer that.
If you can spin up a separate process that manages the same pool, then definitely yes.

**Comment by rhvgoyal** [comment]
@cpuguy83 

Only one process can manage the pool. This process knows the transaction Id and manages pool transaction Id. Two processes can't do it.

**Comment by dreamcat4** [comment]
Would such improvement be able to solve the other problem: that docker is not able to bind mount volumes into the container as a different `UID` and `GID`?

**Comment by rhvgoyal** [comment]
@cpuguy83 

W.r.t complexity of dm, btrfs etc, it is already managed by graphdriver and image and container objects already use it. So we probably will not be dealing with new complexity if we extend volumes to make use of graph drivers other then VFS.

If extensions can't work on same pool where images and containers are stored, then it will not serve the use case I have been thinking of.

Also I am wondering why volume has to be a path. Why could it not be an object with a unique hash ID (like images) and then various metadata attached to it. And path will be just one of the metadata. If user specifies the path, then user is sort of responsible to making sure that volume is up before it is used by docker. Otherwise, it could be a docker managed volume and path will be automatically determined by docker (/var/lib/docker/volumes/mnt/<id>). 

Are there some patches somewhere for this extension based volume management. I want to play with it a bit and see what it will offer.

**Comment by yasker** [comment]
@rhvgoyal @cpuguy83 

The previous patch for docker volume driver I mentioned separates pool/working directory for image and volume management, since I found it caused conflict on e.g. devId allocation which is per DeviceSet in device mapper(which I allocated another DeviceSet for the volume in the patch). If we want to use the same pool, I guess there would be a little more work need to be done.

However, the major problem still is, volume is assumed to be a directory currently, rather than an object. I don't think that assumption can hold in the future. We can keep path(as source and use vfs) for backward compatibility, but ultimately I think volume should be defined as: *an object can be mounted to a path of guest container*. Then we can do various things to the object.

Since we're already planning to have separate volume commands for docker, it would be so natural to have the volume as an object rather than merely a path. I think it would be necessary for the new volume driver able to use graphdriver as volume driver, rather than only vfs and host mount in the future.

**Comment by thaJeztah** [comment]
>I think volume should be defined as: an object can be mounted to a path of guest container. Then we can do various things to the object.

+1 Absolutely. IMO (and I think I mentioned that on other issues) a volume is storage *where* and *how* that storage is manager should be of no concern for the container. In a simple configuration, a volume could be stored on the host, in a directory. On a more advanced setup, this could be a remote volume or "you name it".

My ideal steps would be to (1) create/define a volume ("storage") using the desired driver. (2) connect the volume to the container.

It should be possible to manage the volume separately, for example to migrate or snapshot a volume, but all these could be dependent on the driver and (again) transparent to the container.

**Comment by rhvgoyal** [comment]
@yasker @thaJeztah 

+1 to some of your ideas. 

Few thoughts.

- I think we need a summary document which explains how this new volume architecture is going to look like. There seem to be information scattered in various threads and git trees but no single place
explains it. 

- In new scheme of things, are we targeting one global volume driver which will drive all volumes for
  that docker intance or there can be multiple volume drivers and it will become a per volume property. That means there might be some volumes backed by in-built graph driver, other volumes backed by plugin/extension volume driver. I feel making volumedriver a per volume property is much more flexible. 

- Volume driver Plugin/extension seems to be just another way to plug in a volumedriver dynamically, but I guess core volume API will have to be defined by docker core and all plugin/extension will simply
implement that API. I think this API should be pretty close to what graph driver is currently offering.

- I like the idea of treating volumes as object (like images) and then maintain metadata around it to differentiate between different kind of volumes. (Instead of just treating volume like a path). A call
into volumedriver (volume.volumeDriver.Mount()) should just make volume available at certain mount point.

- Once should be able to use existing graphdrivers (btrfs, devicemapper etc) as volumedrivers.

- In fact I think if we allow per volume volume drivers, then one can have two different instances of
  devicemapper graph drivers. One plugged in one which is operating on its own separate thin pool
and another one which is in-built and operating on pool where existing images are.

Those are some of the ideas. I think if we maintain a summary document which describes new volume architecture, it will help a lot. 
API will have to be d

**Comment by cpuguy83** [comment]
Since this isn't really mergable today, it doesn't really make sense to keep it open, so I'm going to go ahead and close.

So a lot of this discussion is really great, but is probably better suited for docker-dev ML at this point, so it would be really great to continue there, or even on IRC for specific questions.

Thanks.

**Comment by KodyKantor** [comment]
I like this.
Are there any plans to merge the above functionality? Is there any other active discussion somewhere on docker volume proposals?

**Comment by cpuguy83** [comment]
@KodyKantor Some other bits of the code-base need to be handled first so this can be implemented with the suggested API.

**Comment by jantonacci** [comment]
Is it possible/planned to use Dockerfile VOLUME for bind mounting from docker host? Example:
>VOLUME /mnt/nfs:/shared

Presently, mounting host volumes appears only available via docker run -v / --volume.  Example:
>docker run -it --volume /mnt/nfs:/shared ubuntu

**Comment by laktak** [comment]
This issue is referenced from https://docs.docker.com/userguide/dockervolumes/:

>    Note: Docker will not warn you when removing a container without providing the -v option to delete its volumes. If you remove containers without using the -v option, you may end up with “dangling” volumes; volumes that are no longer referenced by a container. Dangling volumes are difficult to get rid of and can take up a large amount of disk space. We’re working on improving volume management and you can check progress on this in pull request #8484

Since this is closed, where can I go to *check the progress on improving volume management*?

**Comment by thaJeztah** [comment]
@laktak thanks for reporting; https://github.com/docker/docker/issues/14214 is a "tracking" issue for issues related to volume management. Are you perhaps interested in creating a pull-request to update the link in the documentation? The Markdown file that is used to generate that page in the documentation can be found here [/docs/userguide/dockervolumes.md](https://github.com/docker/docker/blob/master/docs/userguide/dockervolumes.md)

**Comment by laktak** [comment]
> The Markdown file that is used to generate that page in the documentation can be found here /docs/userguide/dockervolumes.md

@thaJeztah The text has already been updated (not by me), it's just not live.

**Comment by ovidiub13** [comment]
I'm lost, was this functionality implemented or not?

**Comment by thaJeztah** [comment]
@ovidiub13 no, it's not implemented (yet); see https://github.com/docker/docker/issues/14214

**Comment by yasker** [comment]
@thaJeztah @ovidiub13 In fact the volume management has already been implemented by @cpuguy83 at https://github.com/docker/docker/pull/14242 . It's in review now and I suppose it would be merged in v1.9.

**Comment by thaJeztah** [comment]
@yasker yes, you're right; I intended to say "it's not merged yet"

**Comment by ovidiub13** [comment]
Thank you. I'm looking forward to that release.

**Comment by thaJeztah** [comment]
For those following this; this functionally is now implemented in https://github.com/docker/docker/pull/14242, which was just merged, and will be in **docker 1.9**

If you want to test it before that, nightly builds, build from master can be found at https://master.dockerproject.org

**Pull request closed without merging**
