### PR TITLE
Windows: Remove dead/unused code

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard jhoward@microsoft.com

No functional changes - just removing dead code.

### CODE REVIEW

**Comment by duglin** [comment]
If janky is happy then LGTM

**Comment by LK4D4** [comment]
@jhowardmsft I think pkg is supposed to be like "external" library. I think it makes sense to save this function for API consistency.

**Comment by jhowardmsft** [comment]
@lk4d4 - you mean just no-op it with just the declaration?

**Comment by jhowardmsft** [comment]
To clarify the above comment: It can't be used as a library in the way I think you mean. The actual console size setting on Windows is through the HCS interface. The code being removed is meaningless.

**Comment by LK4D4** [comment]
@jhowardmsft Oh, okay :) it was worth to mention

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
