### PR TITLE
server.go: format for

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
Signed-off-by: zhangxiaoyu-zidif <zhang.xiaoyu33@zte.com.cn>

**- What I did**
format for, make it look simple.
**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
I am a newbee in moby. someone couldhelp me solve the error of checks?

**Comment by AkihiroSuda** [comment]
Failure is under analysis https://github.com/moby/moby/issues/33194

**Comment by thaJeztah** [comment]
@AkihiroSuda this is green now 👍

**Review by AkihiroSuda — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM too :smile:

**Comment by zhangxiaoyu-zidif** [comment]
This is my first merged Moby PR. Thank you all！ Very glad to get together with you =）
@AkihiroSuda @thaJeztah @vdemeester

**Pull request merged**
