### PR TITLE
Add icecrime as api/ and daemon/ maintainer

### PR DESCRIPTION
**Pull request by icecrime**
I went with the two subsystems I know best, please let me know if that's ok and if there's a special ceremony about this I should know about.

On another note, I would really like to try free up some time to get up to speed on volumes management and help with that (if that's ok for you @cpuguy83).

### CODE REVIEW

**Comment by jfrazelle** [comment]
_song from the trophy ceremony of mario kart_
LGTM

**Comment by thaJeztah** [comment]
Yeah, the ceremony is what's keeping me from becoming a maintainer. I don't like having to run around naked wearing a giant Moby Dock, singing "Ahoy! Containers"

Glad to see there's still people that have the guts to do that. Kudos!

**Comment by vieux** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by tianon** [comment]
All jokes aside, LGTM too :+1:

**Comment by unclejack** [comment]
LGTM

ping @crosbymichael because he's also a maintainer of daemon and the chief maintainer

**Comment by crosbymichael** [comment]
Since we merged the new updated maintainer format I guess this should be moved to that super file ;)

**Comment by thaJeztah** [comment]
@icecrime I created a PR to add missing information to the MAINTAINERS document, but left this change out of that for now. I'm not sure if the information in that PR is correct, but if it is, I'm happy to add this change to that PR as well. You can find the PR here https://github.com/docker/docker/pull/10481

**Comment by icecrime** [comment]
Thanks, I saw it (twice actually :-) you pinged me and commented on it, so that sends emails remember).

I don't think it's necessary. Root MAINTAINERS should reflect current state of things: it lists me as a core maintainer, and I have no particular special role to play in api/ or daemon/ so that's fine to me as it is.

**Comment by thaJeztah** [comment]
Oh shucks, :blush: sorry for that noise. I wasn't sure if you would still have to be added to a specific subsystem as that was the intent of *this* PR. Thanks for confirming.

**Pull request closed without merging**
