### PR TITLE
Do not try to cleanupMounts if daemon.repository is empty

### PR DESCRIPTION
**Pull request by chenchun**
Signed-off-by: Chun Chen ramichen@tencent.com

Reopen https://github.com/docker/docker/pull/15808. I can not reopen https://github.com/docker/docker/pull/15808 due to force-pushed.

### CODE REVIEW

**Comment by chenchun** [comment]
Failed test `DockerSuite.TestExecStartFails` is not related.

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
