### PR TITLE
Update contrib/mkimage/debootstrap to include wheezy-lts

### PR DESCRIPTION
**Pull request by tianon**
See https://www.debian.org/News/2016/20160425 for more details.

### CODE REVIEW

**Comment by tianon** [comment]
Grrr:
```
W: Failed to fetch http://httpredir.debian.org/debian/dists/wheezy-lts/main/binary-amd64/Packages  404  Not Found
```

Need to investigate further what the status of this is upstream.

**Comment by tianon** [comment]
So, Wheezy LTS has officially started, but the suite isn't available for use yet, so I'll reopen when this is ready. :disappointed:

**Comment by tianon** [comment]
From https://wiki.debian.org/LTS/Using:
> For Debian 7 "Wheezy" LTS there will be no requirement to add a separate wheezy-lts suite to your sources.list any more. In fact you will not notice the switch to LTS because after the official security support by the Debian Security Team ends, security updates will be provided via security.debian.org 's wheezy/updates.

**Comment by thaJeztah** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM :dancer:

**Pull request merged**
