### PR TITLE
Update the llvm repo to use the debian jessie url

### PR DESCRIPTION
**Pull request by mlaventure**
bunnies

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by icecrime** [comment]
LGTM

**Comment by tiborvass** [comment]
@mlaventure this also needs an update everywhere where the word `trusty` is in the dockerfile. So `zfs` dependency and that comment on seccomp.

**Comment by tiborvass** [comment]
Let's merge this now, we can do a followup pr, as this is blocking everything.

**Comment by tiborvass** [comment]
LGTM

**Comment by tiborvass** [comment]
no need to cherrypick because it's already in https://github.com/docker/docker/pull/21659/commits

**Pull request merged**
