### PR TITLE
Return err if we got err on parseForm

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang h.huangqiang@huawei.com

### CODE REVIEW

**Comment by runcom** [comment]
were there any specific reasons why these parseForm calls were just returning `nil` instead of `err`? or were these just bugs? (stalkering you today @hqhq :smile: )

**Comment by hqhq** [comment]
I don't see any, it doesn't make any sense, does it? Seems we both active at a quiet time :)

**Comment by duglin** [comment]
I seem to recall that we had a discussion about this during the "remove engine" work, and while people thought returning errors due to bad input (parsing errors) was correct, it would break backwards compatibility, so the old behavior was left.  
Changing behavior for valid input would be bad, but becoming more correct by flagging bad input (while might break some people) is probably overall a good thing.
But @LK4D4 do you remember those discussions?  I might be misremembering....

**Comment by LK4D4** [comment]
Have no idea :/
+1 to change though

**Comment by LK4D4** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
