### PR TITLE
Status code 409 received when conflicting name when creating container

### PR DESCRIPTION
**Pull request by eskaaren**
- What I did
  Scripting creating a container with name.
- How I did it
  Created one container using the script, ran script again and it failed, inspected status codes and reason.
- How to verify it
  Create a container, then try to create another using the api with the same name. Inspect status code and reason.
- Description for the changelog

When creating a container by name using the remote API and the name already exists it returns 409 Conflict.

Signed-off-by: Eivin Giske Skaaren eivin@sysmystic.com

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks! Can you also update the older versions of the API? Looks like this was always like this, just not in the documentation

**Comment by eskaaren** [comment]
This also happens when deleting a container and it is currently running and the force parameter is not true. I am updating the docs now.

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Pull request merged**
