### PR TITLE
Fix GetStatus(), GetTable() to return multi-line tables

### LINKED ISSUE #39833: devicemapper: GetTable() and GetStatus return only first line of the DM table
**Description**

Device mapper target tables may have multiple lines. GetTable() and GetStatus should return the full results, they return only the first line.

The problem doesn't have any impact because only single line tables are created - but it is a bug in the DM API binding.

**Steps to reproduce the issue:**

1. Create a multi-line target with the following script:

```
#!/bin/bash
set -x
DATA_DEV=/dev/XXX # replace with scratch block device

dmsetup remove linear-dev

echo -e "0 1 error\n\n1 1 linear ${DATA_DEV} 1\\n2 7 error\\n9 1 linear ${DATA_DEV} 9\\n10 6 error" | dmsetup create linear-dev

```
2. Call GetTable() or GetStatus() functions

**Describe the results you received:**

Only the first line of the DM table is returned

**Describe the results you expected:**

The complete DM table is returned

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Sample output of dmsetup with a multi-line target:

```
# dmsetup status linear-dev
0 1 error
1 1 linear
2 7 error
9 1 linear
10 6 error

# dmsetup status -v linear-dev
Name:              linear-dev
State:             ACTIVE
Read Ahead:        256
Tables present:    LIVE
Open count:        0
Event number:      0
Major, minor:      253, 5
Number of targets: 5

0 1 error
1 1 linear
2 7 error
9 1 linear
10 6 error

# dmsetup table linear-dev
0 1 error
1 1 linear 8:32 1
2 7 error
9 1 linear 8:32 9
10 6 error
```

I'll open a PR with a proposed fix.

### PR DESCRIPTION
**Pull request by trgill**
fixes https://github.com/moby/moby/issues/39833

Device mapper target tables may have multiple lines. When the table has
multiple lines, it is required  that dm_get_next_target(ptr) be called
until the returned pointer is Nil.  Examples of using dm_get_next_target()
can be found in libdm/dm-tools/dmsetup.c

**- What I did**

Update GetStatus and GetTable to fetch and return more than just the first
line of the DM table.

**- How I did it**

Added TargetLine type to represent a single line of the DM table.  An
array of TargetLine is used to return the full table.

Update getThinPoolDataMetaMajMin() to hanle an array of TargetLine.

**- How to verify it**

Create a multi-line DM target
Call GetStatus() and GetTable() with/without the fix

**- Description for the changelog**
Fix GetStatus(), GetTable() to return multi-line tables

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @kolyshkin PTAL

**Comment by thaJeztah** [comment]
@trgill looks like build is failing;

```
# github.com/docker/docker/pkg/devicemapper
pkg/devicemapper/devmapper.go:558:29: syntax error: mixed named and unnamed function parameters
```

**Comment by kolyshkin** [comment]
@trgill this code is not compileable, please fix:

```
kir@kd:~/go/src/github.com/docker/docker$ ./hack/make.sh dynbinary

Removing bundles/

---> Making bundle: dynbinary (in bundles/dynbinary)
Building: bundles/dynbinary-daemon/dockerd-dev
GOOS="" GOARCH="" GOARM=""
# github.com/docker/docker/pkg/devicemapper
pkg/devicemapper/devmapper.go:562:3: too many arguments to return
	have (number, number, string, string, error)
	want ([]TargetLine, error)
pkg/devicemapper/devmapper.go:566:3: too many arguments to return
	have (number, number, string, string, error)
	want ([]TargetLine, error)
pkg/devicemapper/devmapper.go:572:3: too many arguments to return
	have (number, number, string, string, error)
	want ([]TargetLine, error)
pkg/devicemapper/devmapper.go:576:3: too many arguments to return
	have (number, number, string, string, error)
	want ([]TargetLine, error)
pkg/devicemapper/devmapper.go:618:10: tl.start undefined (type *TargetLine has no field or method start, but does have Start)
pkg/devicemapper/devmapper.go:618:20: tl.length undefined (type *TargetLine has no field or method length, but does have Length)
pkg/devicemapper/devmapper.go:618:31: tl.targetType undefined (type *TargetLine has no field or method targetType, but does have TargetType)
pkg/devicemapper/devmapper.go:618:46: tl.params undefined (type *TargetLine has no field or method params, but does have Params)
```

**Comment by trgill** [comment]
@kolyshkin fixed.

Looks like a couple unit tests TestDevmapperReduceLoopBackSize  and TestDevmapperIncreaseLoopBackSize are failing.  I'll have a look to see if I introduced the problem.

**Comment by trgill** [comment]
I don't think the test failures are related to this change.  The log entries after the failures indicate:

`[2019-09-30T21:38:12.450Z] time="2019-09-30T21:36:38Z" level=error msg="Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a more recent version of libdevmapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options" storage-driver=devicemapper`

**Pull request closed without merging**
