### PR TITLE
[17.03.x] Correct CPU usage calculation in presence of offline CPUs and newer Linux #31579

### PR DESCRIPTION
**Pull request by vieux**

### CODE REVIEW

**Review by justincormack — APPROVED** [review]

**Comment by tiborvass** [comment]
LGTM

**Review by tiborvass — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tiborvass — CHANGES_REQUESTED** [review]
```
# github.com/docker/docker/daemon
23:03:00 ..\..\daemon\stats_collector.go:118: s.getNumberOnlineCPUs undefined (type *statsCollector has no field or method getNumberOnlineCPUs)
23:03:00 ..\..\daemon\stats_collector_windows.go:17: undefined: Collector
```

**Comment by vieux** [comment]
@tiborvass PTAL

**Review by tiborvass — APPROVED** [review]

**Comment by vieux** [comment]
exp unrelated.

**Pull request merged**
