### PR TITLE
no limit on core size

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar lsm5@fedoraproject.org

### CODE REVIEW

**Comment by lsm5** [comment]
ping @jeremyeder @jfrazelle @philips @tianon

**Comment by jfrazelle** [comment]
what is the default, just curious, and i will try this out

**Comment by philips** [comment]
@lsm5 I would love to see something explaining why Infinity in your commit, just so we remember. I have no objections though.

**Comment by tianon** [comment]
Indeed, I think this PR is missing pretty much 100% of the rationale. :+1:

**Comment by tiborvass** [comment]
Ping @lsm5 can you please clarify your rationale?

**Comment by lsm5** [comment]
so the default core size on fedora/rhel systems is 0 and current rpm packages weren't generating any core dumps. Got this request via our support folks, and they'd like as much detail as possible in a core dump. 

Sorry about the rushed up PR, but that's all I have for now :| , I'll try and grab more info though. Perhaps @jeremyeder has more insight into this.

**Comment by jeremyeder** [comment]
Yes, this came from our support folks, but it benefits everyone.  We're aware of the shortcomings of go+gdb, but still, there _is_ some information that can be gleaned from a core file, which is a lot better than logs, debug logs or posthumously adding printk's and trying to reproduce.

So we'd like to suggest the docker unitfile be configured to write a core so we can perform root cause analysis in case any crashes occur in the field.  "infinity" is about ensuring we get a complete core.

**Comment by tianon** [comment]
Ok, thanks; seems reasonable to me! :+1:

**Comment by LK4D4** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Comment by jfrazelle** [comment]
ping @philips

**Comment by lsm5** [comment]
guess we also need a GOTRACEBACK=crash to enable core dumps, but that's probably set somewhere else, set via /etc/sysconfig/docker for fedora and its downstreams

also, I'll send a follow-up commit here with info from @jeremyeder in the commit message

**Comment by philips** [comment]
lgtm.

The side-effect is that all docker containers get this limit internally too, right?

**Comment by jeremyeder** [comment]
Thanks to everyone for looking at this.

Yes, @philips that's correct...softlimit=0 is overridden because RHEL has a core-catcher pipe-command called abrt.  We're taking care of disk space hogs there, plus a bunch of other tweaks.

**Pull request merged**
