### PR TITLE
Add bash completion for new `docker container` subcommands

### PR DESCRIPTION
**Pull request by albers**
Bash completion for the new `docker container` subcommand family introduced in #26025.
#26025 completely restructures the commands, So, to keep my changes reviewable, I chose to
- create one PR for each new subcommand. This one is just for `docker container`.
- create individual commits for each step

Notes for reviewers
- The first commit serves to illustrate the new flow of logic. The new commands still delegate to the old ones.
- The subsequent commits move the completion logic to their new homes, reversing the direction of delegation. These commits allow to see what really gets moved where. This is helpful because the overall result looks like a complete mess when diffed.
- The commit for `run` looks bungled because github displays it in a very technical way. This is because the moved code block is very large.
- The aliases `docker container list` and `docker container ps` need special treatment. To be consistent with the output of `docker container --help`, they are not included in the completion for `docker container <tab>`. But completion works after them.
- For one of the new subcommands (`prune`) there is no existing bash completion. I will add this in a subsequent PR. This PR just adds a stub for it.
- Please create a squashed merge commit with the commit message "Add bash completion for `docker container` subcommands" or give me a ping if and when I should squash the PR.

### CODE REVIEW

**Comment by albers** [comment]
ping @thaJeztah @mlaventure @tianon

**Comment by mlaventure** [comment]
@albers It needs a rebase

At a first glance, it looks good otherwise :+1:

**Comment by thaJeztah** [comment]
Wow, that's a huge amount of work :heart:

ping @tianon PTAL

**Comment by albers** [comment]
@mlaventure rebased.

**Comment by mlaventure** [comment]
Haven't tested all the combinations, but LGTM.

On another note, I'd actually prefer not to squash those commits, it would make reviewing the changes quite a pain afterwards.

**Comment by thaJeztah** [comment]
I agree, no need to squash this

**Review by tianon — APPROVED** [review]
LGTM :heart_eyes:

**Pull request merged**
