### PR TITLE
Remove incorrect duplicate phrase from build.md

### PR DESCRIPTION
**Pull request by pjaffe**
A phrase from the "Text files" section was incorrectly duplicated under the "Tarball contexts" section.

Signed-off-by: Peter Jaffe <pjaffe@nevo.com>

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
The change looks good to me, but can you change the PR to be against the master branch? We always merge to master first, and cherry-pick to release branches where needed.

You should be able to edit the PR using the edit button, then change the target branch

**Comment by pjaffe** [comment]
@thaJeztah - I tried changing the base branch to Master per http://stackoverflow.com/questions/24159036/how-to-modify-a-pull-request-on-github-to-change-target-branch-to-merge-into, but I think that has resulted in the system thinking I'm trying to bring in a whole bunch of other commits that were in my fork from the over version.

I was just trying to be helpful to correct one bit of documentation I was reviewing, and clearly I've caused more pain than harm :)  I'll close this pull request and create a new one off master.

**Comment by thaJeztah** [comment]
Hm, yes, you'd probably have to rebase on top of master,  it reopening a new one is fine; thanks!

**Comment by pjaffe** [comment]
I created #31398 as a new one, based on master.

**Pull request closed without merging**
