### PR TITLE
Deprecate 'docker images --tree' and 'docker images --viz'

### PR DESCRIPTION
**Pull request by shykes**
As discussed on #docker-dev, these flags can easily be implemented as external tools. We want to keep the Docker core as small as possible. Let's start cutting down the "nice-to-have" features.
- The commands are no longer listed or documented.
- The commands still work but print a deprecation warning.
- The commands should be removed in a future version.

### CODE REVIEW

**Comment by RoelVdP** [comment]
Would you please consider leaving --tree as-is for the docker command line (it still works as of latest 1.4.1) and instead remove the deprecated warning for --tee and -t. Many people (https://groups.google.com/forum/#!topic/docker-user/KJJkFU6eyGU) including myself clearly would like to keep it. Why make a lot of people in the community unhappy?

**Comment by bfirsh** [comment]
```
$ docker run --privileged image-tree
```
maybe?

**Comment by justone** [comment]
Does `--privileged` volume-mount the docker socket by default or does that need to be added?

**Comment by PHLAK** [comment]
I've also found '--tree' extremely useful in optimizing my Docker environments.  +1 for keeping this option in core.

**Comment by HuKeping** [comment]
is there anything supposed to replace it ?

**Comment by slmingol** [comment]
Looking for an alternative to this feature as well.

**Comment by ovidiuvisan** [comment]
i really think this should not be removed. It's useful to be in the core.

**Comment by RoelVdP** [comment]
++1 - Can this be closed?

**Comment by Karunamon** [comment]
Another +1,  at least let's not remove it until a suitable replacement exists. The view provided by --tree is unique and you can't really get that information in an accessible way in some other fashion.

**Comment by mikehaertl** [comment]
Please, please, don't remove this command. Or if you do, please provide a reasonable alternative, without awkward syntax (`docker run --privileged image-tree` seriously?) and without having to install other tools first.

While I really love docker, it's already creating a lot of mess on my hardrives (managing volumes? Anyone?). And `docker images --tree` was one of the easiest ways to learn about what's really going on behind the scenes with all those images.

So please, PLEASE - reconsider this!

**Comment by rhasselbaum** [comment]
I also think "--tree" should left in. It is _extremely_ useful and instructive.

**Comment by TimWSpence** [comment]
+1 leaving --tree in. It is exceptionally useful for managing images.

**Comment by RoelVdP** [comment]
I think 1) it is clear what the community wants & 2) the deprecate idea/this thread should be closed.

**Comment by aikomastboom** [comment]
+1 on keeping --tree

**Comment by bofm** [comment]
+1 to leave it

**Comment by johndistasio** [comment]
+1 keep it. Removing it would make image management even more annoying than it already is.

**Comment by cpuguy83** [comment]
It's gone folks.

**Comment by PHLAK** [comment]
@cpuguy83 It's still there for me.

    $ docker --version
    Docker version 1.6.2, build 7c8fca2\

---

    $ docker images --tree
    Warning: '--tree' is deprecated, it will be removed soon. See usage.
    └─511136ea3c5a Virtual Size: 0 B
      ├─f3c84ac3a053 Virtual Size: 188.1 MB
      │ └─a1a958a24818 Virtual Size: 188.3 MB
      │   └─9fec74352904 Virtual Size: 188.3 MB
      │     └─d0955f21bf24 Virtual Size: 188.3 MB Tags: ubuntu:14.04, ubuntu:14.04.2, ubuntu:latest, ubuntu:trusty, ubuntu:trusty-20150320
      ├─f0dde87450ec Virtual Size: 188.1 MB
      │ └─76b658ecb564 Virtual Size: 188.3 MB
      │   └─4faa69f72743 Virtual Size: 188.3 MB
      │     └─2103b00b3fdf Virtual Size: 188.3 MB
    ...

**Comment by cpuguy83** [comment]
On master it is gone (for a few weeks now).

**Comment by justone** [comment]
@aikomastboom, I just landed a branch to [dockviz](https://github.com/justone/dockviz) that enables it to connect directly to the docker daemon, just like the docker command line itself, including support for TLS (thanks to the excellent [go-dockerclient](https://github.com/fsouza/go-dockerclient)).

So now there's no need to mess with with curl or netcat.  Instead of `docker images -t`, you can run `dockviz images -t` from your local machine.

**Comment by thaJeztah** [comment]
@justone is there, or are there plans for a containerized version as well?

**Comment by mikehaertl** [comment]
> It's gone folks.

Does that mean, that the docker guys simply ignore the feedback they get from the community? Reading back this thread there's hardly anyone who is ok with this change. Still it's removed.

**Comment by thaJeztah** [comment]
@mikehaertl please have a look at https://github.com/docker/docker/issues/13140 as well. It's a proposal to add support for CLI plugins. This may make it possible to add this back in a seamless way, without it being part of the core.

**Comment by aikomastboom** [comment]
@justone thanks, looks like we are all forced into using your solution now.
I agree with @mikehaertl and it makes me sad.

**Comment by duglin** [comment]
If we can https://github.com/docker/docker/pull/13140 in then someone could write a 3rd party plugin for it.

**Comment by justone** [comment]
@thaJeztah Sure, I just pushed one up [over here](https://registry.hub.docker.com/u/nate/dockviz/).  An example:

```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t
```

**Comment by RoelVdP** [comment]
++1 on @mikehaertl . Comment by @thaJeztah makes no difference imho: the feature that the community requested to leave is gone.

**Comment by shykes** [comment]
Hi all. This command has had a deprecation warning for a very long time (at least 6 months?). I wasn't involved in the merge which removed it (I am happy about the fact that I am much less of a bottleneck than I used to be), but it makes sense to finally enforce the deprecation.

*THAT BEING SAID* if lots of people disagree with the plan, we can always consider changing it.

The reason we deprecated `--tree` is that Docker bundles a mission-critical daemon, and a lot of grumpy sysadmins (tm) are uncomfortable bundling too many features in the same binary as a mission-critical daemon. Since we have been historically attached to the idea of a single-binary-for-everything approach, our response was (and still is) to jettison features which can be re-implemented by a 3d-party client.

*HERE'S WHAT HAS CHANGED*: I now believe that we should spin out the Docker client into a separate command, which will simultaneously 1) make grumpy sysadmins less happy, and 2) allow us to continue carrying convenience features such as `--tree` indefinitely.

To be clear: I am opening the possibility of bringing back `--tree`, in exchange for spinning out the Docker client into its own repo and binary. How does everyone feel about that?

**Comment by shykes** [comment]
EDIT I meant "make grumpy sysadmins happy", or "make grumpy sysadmins less grumpy". I *DID NOT* mean "make grumpy sysadmins less happy" ;-)

**Comment by duglin** [comment]
@shykes does this mean you might be in favor of something like this?  https://github.com/docker/docker/pull/13140

**Comment by shykes** [comment]
Yes, with a proper standalone client I would be in favor of client-side plugins, absolutely.

**Comment by duglin** [comment]
Well, we could do it in stages. Splitting the CLI and daemon doesn't need to be tied to a CLI plug-in model.  They're pretty independent tasks.  But both worthy.

**Comment by RoelVdP** [comment]
I have no direct opinion on #13140, but if it may be a while before --tree would find it's way back into the feature list, why not simply revert the --tree removal for the time being? Most people in the community really seem to want/like it.

**Comment by shykes** [comment]
@duglin they are tied because the current cli is very deeply tied into the daemon, and before working on big new client features I would like to get a clean foundation to work on. If you want we can do a session on this during the next contributor summit.

@RoelVdP let's see how everyone feels about the long-term plan, then based on that we can decide of short-term steps (like a possible revert). No point in doing the latter before the former.

Thanks for the input, anyone else want to weigh in?

**Comment by duglin** [comment]
@shykes yes I'd like a session to discuss this at the summit.
I agree that right now the CLI and daemon are tied together, but my point was that a CLI plug-in model can be developed (e.g. #13140) that works with today's docker exe as well as a future docker cli exe.

**Comment by justone** [comment]
Separating out the binary is a great idea, and adding plugins makes it even better.  I like @duglin's plugin system, except I'd lean toward the git style of supporting anything in the path with the right binary name (e.g. `docker-viz` becomes `docker viz ...`).  It makes it super easy to add new commands in an adhoc manner.

@shykes Speaking of the summit, is there going to be a way for people to remotely participate or is it an in-person thing?

**Comment by justone** [comment]
Also, I like getting `--tree` back into the core as much as everyone else, but I think that if there was a decent plugin search/download capability, then it would be easy for the viz stuff to stay separate (and get individualized attention) while still being easy to obtain.  I think we can have the best of both worlds.

**Comment by johndistasio** [comment]
I would like to see the deprecation reverted. I can understand why this was done from a design standpoint, but as someone who has to manage systems where docker is installed I want it to be as simple as possible to see what my host is running and where it came from. I don't want to have to deal with third-party tooling for something as (in my opinion) elementary as that. I think --viz was overkill but --tree was/is the sweet spot. 

 That aside, I think splitting out the CLI into a client binary is the way to go long term.

**Comment by duglin** [comment]
@shykes w.r.t. the CLI/daemon exe split, do you have any more info on that?  We'd like to start to explore that piece of work but want to head in the same direction as what's been previously considered.

Some questions I have are....
- in the end, what are the exes you see us ending up with?  docker (cli) vs dockerd (daemon) ?
- right now you can build just the CLI exe via `make DOCKER_CLIENTONLY=1 binary`, but do you see the repo itself being split into two or us continuing to keep both cli and daemon code bases in one repo?  They're already kind of split nicely within the one repo via dirs. And there is some shared code between them.
- is there any relation between this exe split and the `docker -d` -> `docker daemon` work being done?

**Comment by mikehaertl** [comment]
@shykes Even though it's less convenient I'm not completely against a plugin architecture. The real problem is, that `--tree` was remove *before* a reasonable and easy to use workaround was provided. Right now I'm sitting here, frustrated that I can't check the mess of images I have on my disk. So I have to spend time to find a workaround (probably @justone's is the best so far? Who knows..?).

Proper image managment to me is docker's job! It should provide all the tools and utilities to make it easy to clean up the dirt it generates. Right now I have to use some 3rd party, to do the dirty work for me. Very annoying, to say the least.

**Comment by larrycai** [comment]
the `--tree` is finally removed for `docker image` command since docker version 1.7

@justone thank for the new docker tool (repeat it below for easy find)

     docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t

**Comment by SunWeicheng0001** [comment]
Sad to find that --tree has removed from master. It is a useful tool to manage the structure of an image.

**Comment by nigelpoulton** [comment]
Devastated that `--tree` has gone! 

From a day-to-day mgt perspective it was a life-saver.

I grok the whole thing about breaking out the CLI, 3rd-party plugins, trimming down the monolith etc.... but `--tree` was a godsend. On a day-to-day basis its small things like this that make a difference :-(

**Comment by RoelVdP** [comment]
@vieux @shykes can something not be done here? Clearly the community loved --tree.

**Comment by julian1** [comment]
Argh! --tree just disappeared from my distribution after an upgrade. 

As someone who recently picked up Docker, --tree is has become ingrained and a command that I probably run at least every day, to provide insight into disk use.

How do grumpy sys-admins feel about plugin architectures? 

Imho, plugin architectures ought to be avoided since they are vastly more complex - creating maintenance, security, versioning and distribution issues.

**Comment by thaJeztah** [comment]
@julian1 @RoelVdP @nigelpoulton try running

    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t

the "dockviz" image is developed  by the person that originally wrote the `--tree` option in Docker. Repository can be found here: https://github.com/justone/dockviz (the readme has more information and hints, e.g. setting up an alias)

**Comment by mikehaertl** [comment]
@thaJeztah 

Sarcasm mode on;

See, we now simplified `docker images --tree` to the much easier to remember `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t`.

Sarcasm mode off;

Sorry, but couldn't resist...

**Comment by nigelpoulton** [comment]
@mikehaertl LOL

In the IT Ops world I'd also say that most companies I've worked for will whitelist the core Docker Engine as trusted code to run in dev/test/prod etc.... Therefore `docker images --tree` is considered safe and easy to run.

`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t` **as good as it no doubt is**...... is an IT Ops can of worms.

IMHO pulling the `--tree` has made obtaining the info harder **and** the operational procedures harder :-(  

And in a lot of the big enterprises Ive worked at (esp. financial services)... it's a royal pain in the rear to get approval to run 3rd party code in production.

#SaveTheTree

**Comment by TomasTomecek** [comment]
Thanks @thaJeztah, I've just updated my dotfiles:
```diff
-alias dit="docker images --tree"
+alias dit="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t"
```

**Comment by RoelVdP** [comment]
@thaJeztah Thanks, but this was already discussed back in May (see above). Around the same time @shykes wrote:

*@RoelVdP let's see how everyone feels about the long-term plan, then based on that we can decide of short-term steps (like a possible revert). No point in doing the latter before the former. Thanks for the input, anyone else want to weigh in?*

It is clear that people want the --tree option. So will the revert happen now @shykes?

**Comment by sedwards** [comment]
Keep making decisions like this and eventually the user base will fork.

**Comment by remram44** [comment]
Ok, what the f***.

I didn't cry out when this was deprecated, as it was clearly stated that the goal was to be removed once it's "implemented as external tools". It is not implemented by external tools. This is not how deprecating features work.

This is not just called being awful to your community, you straight-out don't understand how versioning works.

**Comment by vinceyuan** [comment]
`--tree` is very useful. Please come back!

**Comment by markus512** [comment]
We are still using Docker version 1.6.2, build 7c8fca2. As we really want to keep our systems up to date, please bring back this feature. Our "grumpy sysadmins" do not allow any update of docker without this feature and they don't accept "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t"

**Comment by askb** [comment]
+1 to bring back the feature. When dealing with a large number of layers per image and large nums of images per host, using a "--tree" option was a great way we can view the layers associated image. Also companies have policies which don't easily approve using third party plugins / containers for security reasons. Though using `dockviz` does the trick, its best to bring the original feature back.

**Comment by magnayn** [comment]
+1 on what @mikehaertl said.

I don't understand the benefit of having removed such a useful option. It's a bit like if git removed all the user facing porcelain, and forced you to interact directly on the plumbing.

**Comment by ytwu** [comment]
+1 to bring back this feature! we need it!!! It's really inconvenient without it.

**Comment by jrjr89** [comment]
+1 bring it back

**Comment by FuzzySockets** [comment]
So it's unanimous.  +1 to add it back into the core.

**Comment by LordGaav** [comment]
I would also like this feature returned, or a proper alternative using the core docker tools. As layering images is a core feature of docker, this relation should be visible in the core tools.

**Comment by shaded-enmity** [comment]
https://github.com/shaded-enmity/docker-doug
```
doug-cli dependencies IMAGE_NAME
```

To list images depending on IMAGE_NAME

**Comment by adityamenon** [comment]
I'm less happy knowing that this existed (and seeing screenshots) and not having it now, than I would have been if it was never there at all :)

An error message giving step by step instructions on how to replicate that functionality would at least be a good redressal.

**Comment by TomasTomecek** [comment]
I have recently released a new version of sen (terminal user interface for docker engine) which contains interactive `docker images --tree`-like buffer:

https://github.com/TomasTomecek/sen/blob/master/docs/features.md#image-tree

**Comment by codeaholics** [comment]
That looks like an awesome project! Thank you for sharing.

**Comment by ytwu** [comment]
@TomasTomecek  very cool!

**Comment by meffect** [comment]
user@comp MINGW64 ~

`$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t
Error reading JSON: %!(EXTRA *json.SyntaxError=unexpected end of JSON input)`

anyone get this? windows 8.1

**Comment by justone** [comment]
Hey @meffect, just need to add `-it` to your docker run command.  This is required as of docker 1.11 (or maybe even 1.10).

And, for anyone that has issues with dockviz, please file an issue [over there](https://github.com/justone/dockviz/issues).  Thanks.

**Comment by meffect** [comment]
thanks it works

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t`

**Comment by pnkjtr** [comment]
when i run the above command , i see following o/p.. not sure, what <missing> means here. i am expecting proper ID here.  any idea, how to correct it ? 

pankaj@ubuntu14-04:~$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t
─<missing> Virtual Size: 967.0 B
│ └─sha256:94df4 Virtual Size: 967.0 B Tags: hello-world:latest
├─<missing> Virtual Size: 122.0 MB
│ └─<missing> Virtual Size: 122.0 MB
│   └─<missing> Virtual Size: 122.0 MB
│     └─<missing> Virtual Size: 122.0 MB
│       └─sha256:2fa92 Virtual Size: 122.0 MB Tags: ubuntu:latest

**Comment by pnkjtr** [comment]
re-submitting the exact o./p again.

I am getting <missing>  in output of 'dockviz images -t'  command. 

pankaj@ubuntu14-04:~$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t
├─<missing> Virtual Size: 967.0 B
│ └─sha256:94df4 Virtual Size: 967.0 B Tags: hello-world:latest
├─<missing> Virtual Size: 122.0 MB
│ └─<missing> Virtual Size: 122.0 MB
│   └─<missing> Virtual Size: 122.0 MB
│     └─<missing> Virtual Size: 122.0 MB
│       └─sha256:2fa92 Virtual Size: 122.0 MB Tags: ubuntu:latest
├─<missing> Virtual Size: 6.1 MB
│ └─<missing> Virtual Size: 6.1 MB
│   └─sha256:3ee5f Virtual Size: 6.1 MB Tags: nate/dockviz:latest

**Comment by thaJeztah** [comment]
@pnkjtr I edited your last comment to put the output in a code-block (otherwise the `<missing>` is hidden in HTML)

**Comment by pnkjtr** [comment]
resubmitting the o/p, since my earlier post made 'missing' hidden when coverted by HTML.

here you can see, i am getting missing tag in each line of 'dockviz images -t' o/p.

is there any thing i am missing ?

`pankaj@ubuntu14-04:~$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t
├─<missing> Virtual Size: 967.0 B
│ └─sha256:94df4 Virtual Size: 967.0 B Tags: hello-world:latest
├─<missing> Virtual Size: 122.0 MB
│ └─<missing> Virtual Size: 122.0 MB
│   └─<missing> Virtual Size: 122.0 MB
│     └─<missing> Virtual Size: 122.0 MB
│       └─sha256:2fa92 Virtual Size: 122.0 MB Tags: ubuntu:latest
├─<missing> Virtual Size: 6.1 MB
│ └─<missing> Virtual Size: 6.1 MB
│   └─sha256:3ee5f Virtual Size: 6.1 MB Tags: nate/dockviz:latest
└─<missing> Virtual Size: 0.0 B
  └─<missing> Virtual Size: 196.7 MB
    └─<missing> Virtual Size: 196.7 MB
      └─sha256:85961 Virtual Size: 196.7 MB Tags: centos:latest`

**Comment by mikehaertl** [comment]
@pnkjtr Since 1.10 the way layer IDs worked has changed fundamentally. For a lengthy explanation of this topic see #20399. There's also #20451 but I'm not sure, if this could be used by the `nate/dockviz` image.

Personally I find the way the new layers work very very confusing and much less transparent than before.   And it's not really well documented either - AFAIK @tonistiigi's comments in the issue above are the only public explanation available. I'd be more than happy to be corrected on this one.

**Comment by arcseldon** [comment]
Unnecessary mistake.

**Comment by thangbn** [comment]
this is a really useful feature. It a "core" feature for me. Love to see you guys bring it back.

**Comment by byronyi** [comment]
For every single complaint here there're ten times more unspoken ones. This is not how you work on OSS docker.

**Comment by cpuguy83** [comment]
Part of the reason for removal (beyond just being difficult to maintain) is it is tied to the (now old) method of image storage where images were all just a tree of layers and any layer is considered an image even if you can't actually run that layer.... in such a mess `--tree` (and external implementations of it) made sense to at least be able to make sense of it and know what can be cleaned and what cannot be.

Today images are flat. You have a proper thing that is an image and an image object is composed of layers (vs 1 layer = 1 image). Some images may share layers (so they only need to be downloaded/stored once) but there is no actual hierarchy.
Indeed you can have two images that are built from completely different sources (for instance, `centos` and `debian`) that can actually share layers based on the content of the layer rather than requiring the entire layer chain to be in common.

While you can build a tree view by comparing the layer chain in the image manifests, this would be an incomplete view of the relationship between images.

**Comment by abierbaum** [comment]
@cpuguy83 Is the newer way this works documented somewhere in the user docs?  I haven't seen a full description but I may have missed it in the updated documentation.

The reason I ask is that for my use case of --tree I used it to see the hierarchy of images and the size of these images so I could optimize the size of the builds.  We have multiple images used across multiple containers but we try to base them on common images during build so we can minimize the amount of data that has to be packaged and transferred.  The tree view helped dramatically with that because I would see what images were built on what other images and where the big image "deltas" where in the build.

Based upon what you said above about images being flat, maybe this isn't a concern anymore.  I haven't read anything that really describes this and I don't know of any tooling that allows me to view how the images are made up such that I can optimize for minimal packaging size of multiple related images.  Can you point me in a direction that would help with this?

**Comment by cpuguy83** [comment]
@abierbaum There's a fairly high-level doc here: https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/#content-addressable-storage

Note you can still get the size of images (in `docker images`), and even a summary view taking into account shared layers (`docker system df`).
Utilizing the content-hash with the image name can also improve your space requirements since you know that each build using a particular content hash are exactly the same.

**Comment by thaJeztah** [comment]
`docker history` gives an overview as well for an image you built

**Comment by aloneguid** [comment]
If you're on Windows, I wrote a simple tool for myself to do this https://github.com/aloneguid/docker-explorer-windows

**Pull request merged**
