### PR TITLE
Vendoring swarmkit @b74ec2b

### PR DESCRIPTION
**Pull request by aboch**
- Brings in a fix for a panic around the ingress network area. Details at docker/swarmkit/pull/2072
- Swarm allocator to respect IPAM driver contract for network gateway. Details at docker/libnetwork#1702
- Other swarmkit fixes/features/enhancements (please fill in)

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM if green

**Comment by aaronlehmann** [comment]
```
00:18:27 FAIL: check_test.go:353: DockerSwarmSuite.TearDownTest
00:18:27 
00:18:27 check_test.go:358:
00:18:27     d.Stop(c)
00:18:27 daemon/daemon.go:392:
00:18:27     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
00:18:27 ... Error: Error while stopping the daemon d89163aa99910 : exit status 2
00:18:27 
00:18:27 
00:18:27 ----------------------------------------------------------------------
00:18:27 PANIC: docker_cli_swarm_test.go:418: DockerSwarmSuite.TestSwarmIngressNetwork
00:18:27 
00:18:27 [d89163aa99910] waiting for daemon to start
00:18:27 [d89163aa99910] daemon started
00:18:27 
00:18:27 [d89163aa99910] exiting daemon
00:18:27 ... Panic: Fixture has panicked (see related PANIC)
00:18:27 
```

**Comment by aboch** [comment]
@aaronlehmann 
It is a known one and tracked by #32173 
Let me spin it again.

**Comment by aaronlehmann** [comment]
Is the failure understood yet? It to have only started recently. I'm concerned we introduced a regression.

**Comment by vdemeester** [comment]
arf if `TearDownTest` happened again, this mean it was not the only cause for it…
LGTM 🐸

**Pull request merged**
