### PR TITLE
Fix zsh-completion for containers in status 'created'

### PR DESCRIPTION
**Pull request by ngaro**
This patch makes sure that containers in the created-stated are
counted as stopped containers. Otherwise if you create a container,
don't run it and type: "docker rm ", followed by pressing tab in zsh, it won't show up.

Signed-off-by: Nikolas Garofil <nikolas.garofil@uantwerpen.be>

### CODE REVIEW

**Comment by ngaro** [comment]
This patch makes sure that containers in the created-stated are
counted as stopped containers. Otherwise if you create a container,
don't run it and type: "docker rm ", followed by pressing tab in zsh, it won't show up.

Signed-off-by: Nikolas Garofil nikolas.garofil@uantwerpen.be

**Comment by thaJeztah** [comment]
Oh, you don't have to close the PR; the problem was that you added multiple commits, and some of them aren't signed of properly.

To fix this (assuming your "upstream" docker repository is named `upstream`, and your fork's remote is named `origin`);

```
git fetch origin -v; git fetch upstream -v

git rebase upstream/master
```

That should probably make the "merge" commits go away. If not, you can then "squash" (see https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently)  

After you squashed your commits you can "amend" the last commit, and add a sign-off;

```
git commit -s --amend --no-edit
```

Then _force_ push to update this PR

```
git push -f origin
```

*Make sure to first reopen the PR, otherwise it won't update on GitHub*

**Comment by ngaro** [comment]
Something really strange is going on here...
I only did 1 commit, but github is showing 2 extra commits of 0 files.
I am just going to remove my whole fork, fork again, make my changes, commit them and create a new pull request...

**Comment by thaJeztah** [comment]
@ngaro the extra commits seem to be because you merged upstream into your master branch to bring it up to date. You can use _rebase_, but it's usually best as well to create a feature branch for a PR, which makes rebasing easier, and prevents unwanted changes to be inadvertently included.

**Pull request closed without merging**
