### PR TITLE
devmapper: ensure that UdevWait is called after calls to setCookie

### PR DESCRIPTION
**Pull request by nhorman**
Recent changes to devmapper broke the implicit requirement that UdevWait be
called after every call to task.setCookie.  Failure to do so results in leaks of
semaphores in the LVM code, eventually leading to semaphore exhaustion.
Previously this was handled by calling UdevWait in a ubiquitous defer function,
but that had its own problems with ordering between execution of the wait and
other uses of the semaphore.  So now we delay returning until after the UdevWait
completes, once we've set the cookie value.

Problem  can be observed by running moby with an lvm2 storage backend for extended periods of time.  When enough cookies have leaked, then they problem will present.
 
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

### CODE REVIEW

**Comment by nhorman** [comment]
@rhvgoyal as requested, tagging you to review this

**Comment by rhvgoyal** [comment]
cc @cpuguy83 @thaJeztah

**Comment by rhvgoyal** [comment]
LGTM

**Comment by rhvgoyal** [comment]
I did basic testing and it seems to fix cookies leaking issue when a busy device is being removed.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@rhvgoyal @nhorman IIUC, this is the PR that introduced this issue? https://github.com/moby/moby/pull/33119

**Comment by rhvgoyal** [comment]
@thaJeztah Right. Last patch in that patch series introduced the issue.

**Comment by fitz123** [comment]
Thank you! Finally it's released! Horaay

**Comment by leecade** [comment]
cool

**Pull request merged**
