### PR TITLE
Revert "Tidy config/hostconfig structures"

### PR DESCRIPTION
**Pull request by calavera**
Because it will cause a cache burst across all daemons :(

See https://github.com/docker/docker/pull/17579#issuecomment-155180770

This reverts commit ad5052df234e4f48a93e22694f91fda36bb9e95d.

### CODE REVIEW

**Comment by LK4D4** [comment]
@calavera no sign

**Comment by calavera** [comment]
signed :sob:

**Comment by tonistiigi** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by thaJeztah** [comment]
Do we need to add a comment somewhere to prevent this from accidentally happening again? https://github.com/docker/docker/pull/17579#issuecomment-155180770

**Comment by jhowardmsft** [comment]
LGTM

**Comment by aaronlehmann** [comment]
@thaJeztah: I'm actually about to remove this test and replace it with a new one, so I'll make sure that the new test has clear commentary about cache implications.

**Comment by thaJeztah** [comment]
Thanks @aaronlehmann, that would be great!

**Comment by calavera** [comment]
okay, thank you all for paying attention to this change. I'm going to merge it, so we can sleep tonight :smile_cat:

**Comment by jhowardmsft** [comment]
My apologies for the firestorm :(

**Comment by thaJeztah** [comment]
@jhowardmsft no prob, it would've been a nice cleanup, unfortunately with side effects :+1:

**Pull request merged**
