### PR TITLE
Introduce rate limiter to log reads.

### LINKED ISSUE #37471: Docker logs -f is inefficient (high CPU decoding json)
**Description**

`dockerd` consumes ~60% CPU when running `docker logs -f` for a container producing ~55k/sec of output to stdout (and the default JSON file logger driver is being used).

This, in turn, worsens the latency of the app by 5x.
 

**Steps to reproduce the issue:**

Dockerfile
```
FROM alpine:latest

COPY echo.sh echo.sh

CMD ["/echo.sh"]
```
echo.sh
```
#!/bin/sh

while true; do
  for i in $(seq 1 3); do
    rnd1=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 80 | head -n 1)
    rnd2=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 80 | head -n 1)
    echo '{"rnd1: "'"${rnd1}"', "rnd2": "'"${rnd2}"'"}'
  done
  sleep 0.01
done
```
To reproduce:
```
sudo docker build -t log-test .
docker run -d log-test
docker logs -f CONTAINER
```
Observe CPU usage of `dockerd`

**Describe the results you received:**

`dockerd` at 60% CPU usage

**Describe the results you expected:**

`dockerd` CPU usage to be in the single digits

**Additional information you deem important (e.g. issue happens only occasionally):**

bcc profile shows `dockerd` is spending most of its time in:

```
    runtime.mallocgc
    runtime.newobject
    runtime.makemap
    github.com/docker/docker/daemon/logger/jsonfilelog.decodeLogLine
    github.com/docker/docker/daemon/logger/jsonfilelog.decodeFunc.func1
    github.com/docker/docker/daemon/logger/loggerutils.followLogs
    github.com/docker/docker/daemon/logger/loggerutils.(*LogFile).ReadLogs
    github.com/docker/docker/daemon/logger/jsonfilelog.(*JSONFileLogger).readLogs
    runtime.goexit
    -                dockerd (3132)
```

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Thu May 24 22:21:27 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6/18.03.1-ce
  Built:        Thu May 24 22:22:43 2018
  OS/Arch:      linux/amd64
  Experimental: falsei
```

**Output of `docker info`:**

```
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 23
Server Version: 18.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 107.4GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 3.338GB
 Data Space Total: 12.72GB
 Data Space Available: 9.379GB
 Metadata Space Used: 1.286MB
 Metadata Space Total: 16.78MB
 Metadata Space Available: 15.49MB
 Thin Pool Minimum Free Space: 1.271GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.47-56.37.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.11GiB
Name: ip-172-31-7-98
ID: QJGC:PQQT:ST2F:EX6G:XOJU:YZ36:HLID:LBWS:PYUG:KDRX:4WDK:DHM5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS c5.2xlarge (8 vCPU)

### PR DESCRIPTION
**Pull request by cpuguy83**
This prevents log reads from consuming too much CPU which can degrade
actual container performance.

Closes #37471

### CODE REVIEW

**Comment by cpuguy83** [comment]
Oh this test...

**Comment by kolyshkin** [comment]
This looks like a workaround/bandaid rather than a solution to me. As the original bug report says, the problem is probably too much json decoding going on.

**Comment by cpuguy83** [comment]
@kolyshkin Not sure how we can reduce json decoding here outside of instructing the user to use the attach API, but that presents other issues which are often undesirable.

**Comment by olljanat** [comment]
@cpuguy83 this one needs to be rebased

**Comment by olljanat** [comment]
Derek add label: status/failing-ci

**Comment by cpuguy83** [comment]
Closing this since there doesn't seem to be any interest.

**Pull request closed without merging**
