### PR TITLE
[test] fix racy tests in pkg/archive

### PR DESCRIPTION
**Pull request by AkihiroSuda**
**\- What I did**
Fixed a race:

``` console
==================
WARNING: DATA RACE
Write at 0x00c420158540 by goroutine 21:
  os.(*file).close()
      /usr/local/go/src/os/file_unix.go:143 +0x124
  os.(*File).Close()
      /usr/local/go/src/os/file_unix.go:132 +0x55
  github.com/docker/docker/pkg/archive.TestDecompressStreamXz()
      /go/src/github.com/docker/docker/pkg/archive/archive_test.go:151 +0x22b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Previous read at 0x00c420158540 by goroutine 23:
  os.(*File).read()
      /usr/local/go/src/os/file_unix.go:228 +0x50
  os.(*File).Read()
      /usr/local/go/src/os/file.go:101 +0x6f
  bufio.(*Reader).fill()
      /usr/local/go/src/bufio/bufio.go:97 +0x196
  bufio.(*Reader).WriteTo()
      /usr/local/go/src/bufio/bufio.go:472 +0x499
  io.copyBuffer()
      /usr/local/go/src/io/io.go:380 +0x43f
  io.Copy()
      /usr/local/go/src/io/io.go:360 +0x7e
  os/exec.(*Cmd).stdin.func1()
      /usr/local/go/src/os/exec/exec.go:208 +0x88
  os/exec.(*Cmd).Start.func1()
      /usr/local/go/src/os/exec/exec.go:370 +0x38

Goroutine 21 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/go/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:743 +0x12f
  main.main()
      github.com/docker/docker/pkg/archive/_test/_testmain.go:300 +0x2f8

Goroutine 23 (finished) created at:
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:371 +0x87e
  github.com/docker/docker/pkg/archive.cmdStream()
      github.com/docker/docker/pkg/archive/_test/_obj_test/archive.go:1317 +0x296
  github.com/docker/docker/pkg/archive.xzDecompress()
      github.com/docker/docker/pkg/archive/_test/_obj_test/archive.go:178 +0xfa
  github.com/docker/docker/pkg/archive.DecompressStream()
      github.com/docker/docker/pkg/archive/_test/_obj_test/archive.go:217 +0x7f6
  github.com/docker/docker/pkg/archive.TestDecompressStreamXz()
      /go/src/github.com/docker/docker/pkg/archive/archive_test.go:147 +0x1dd
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================
```

**\- How I did it**

**\- How to verify it**
`TESTFLAGS=-race TESTDIRS=pkg/archive make test-unit`

**\- Description for the changelog**

**\- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Akihiro Suda suda.akihiro@lab.ntt.co.jp

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
CI didn't get executed..

**Comment by coolljt0725** [comment]
May be we could enable `-race` by default on running test-unit in https://github.com/docker/docker/blob/master/hack/make/test-unit#L11

**Comment by AkihiroSuda** [comment]
@coolljt0725 

+1 for `-race` by default, but it takes twice the time..

### `make test-unit`
executed [10 times](https://github.com/AkihiroSuda/ntimes) on GCE n1-highcpu-32.

```
average: 48.723439111s, max: 52.165949536s, min: 48.100313008s, std dev: 1.21406111s
99 percentile: 52.165949536s, 95 percentile: 52.165949536s, 50 percentile: 48.364515189s
```

### `TESTFLAGS=-race make test-unit`:
```
average: 1m37.952973705s, max: 1m38.793574353s, min: 1m37.311849775s, std dev: 471.814281ms
99 percentile: 1m38.793574353s, 95 percentile: 1m38.793574353s, 50 percentile: 1m37.560808264s
```

**Comment by aaronlehmann** [comment]
I'm wondering if this will work reliably. As I understand the code, calling `Close` on the stream returned by `DecompressStream` will wait until the command finishes. But in this case, we aren't reading from the stream, so the command may block forever trying to write to the pipe.

Maybe we should consider changing this so that `Close` kills the process. It's strange that calling `Close` on the stream it returns waits for the decompressor to finish before doing anything.

**Comment by AkihiroSuda** [comment]
@aaronlehmann Thank you for pointing out, added `ioutil.ReadAll` so that it won't block trying to write to the pipe.

**Comment by aaronlehmann** [comment]
LGTM

**Review by LK4D4 — APPROVED** [review]
LGTM

**Pull request merged**
