### PR TITLE
Update libcontainer to 2c3115481ee1782ad687a9e0b4834f89533c2acf

### PR DESCRIPTION
**Pull request by LK4D4**
It includes fix for parsing systemd cgroup names

Signed-off-by: Alexander Morozov lk4d4@docker.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by icecrime** [comment]
Following ARM CI here, but daemon seems to start properly: https://jenkins.dockerproject.org/job/Docker-PRs-arm/237/console

**Comment by icecrime** [comment]
ARM failure is known. Other failures are broken CI jobs.

Wonderful times.

**Pull request merged**
