### PR TITLE
API v1.22 is not going to be released until Engine v1.10

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit SvenDowideit@home.org.au

it seems it got in there by mistake - see the menu: http://docs.docker.com/engine/reference/api/docker_remote_api/

remote api-v1 22

@moxiegirl (this is a PR to the `docs` branch, as master is now all about 1.10 :)

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @moxiegirl, FYI

**Comment by moxiegirl** [comment]
@SvenDowideit thanks @thaJeztah  for those things that need a cherry pick please go ahead and assign to me and label cherry pick  --- I'm going to be testing some scripts Daniel is writing

**Comment by thaJeztah** [comment]
@moxiegirl cool, will do!

**Pull request merged**
