### PR TITLE
New features in mkimage-yum.sh script

### PR DESCRIPTION
**Pull request by FlorinAsavoaie**
Added -g and -p options for the contrib/mkimage-yum.sh script to allow generating images with the dependencies you want. I use this because I generate images where I only need "glibc" with its dependencies or "java-1.8.0-openjdk-headless" and so on. This makes sure that I don't get a lot of bogus packages from the Core group.

Possible usages now include sudo ./mkimage-yum.sh -y yum.conf -g '' -p java-1.8.0-openjdk-headless.

Also changed the "test" at the end to add --rm parameter to docker run so it doesn't leave a junk container and use bash to echo "success" in case you don't get coreutils in your dependencies tree.

Signed-off-by: Florin Asavoaie florin.asavoaie@gmail.com

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jfrazelle @tianon This replaces https://github.com/docker/docker/pull/17900

**Comment by thaJeztah** [comment]
@FlorinAsavoaie looks like this needs a rebase :cry:

**Comment by FlorinAsavoaie** [comment]
Done. There was a conflict on the exact script I modified, I merged it too.

**Comment by thaJeztah** [comment]
oh, can you use rebase and squash your commits, so that there's only a single commit in your PR? You can find some instructions in our contributors guide: https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently

**Comment by FlorinAsavoaie** [comment]
I hope I got it correctly but I need to confirm. I need to rebase to 7a050263e4581851b5ed20605d8d008464323216 using squash, merge again and commit?

**Comment by thaJeztah** [comment]
There's no need to "merge", rebasing should put your changes on top of the changes in master. "pick" and "squash" control the squashing. Here's also an article describing this https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by FlorinAsavoaie** [comment]
It messed up :( I'll try again

**Comment by thaJeztah** [comment]
ping @FlorinAsavoaie were you still trying?

**Comment by FlorinAsavoaie** [comment]
I didn't get to look again. I just completely rebased and forced pushed into my repo and commited my change again. I don't get why it has merge conflicts now.

**Comment by thaJeztah** [comment]
@FlorinAsavoaie no worries; if you're still interested, it's okay to open a new pull request if that's easier

**Comment by FlorinAsavoaie** [comment]
Ok, will do just that.

**Comment by FlorinAsavoaie** [comment]
I put it in https://github.com/docker/docker/pull/18807

**Comment by thaJeztah** [comment]
Thanks!

**Pull request closed without merging**
