### PR TITLE
context.Context should be the first parameter of a function

### PR DESCRIPTION
**Pull request by yu8833**
**- What I did**
Change the place of the  context.Context parameter.
**- How I did it**
Move the context.Context parameter to the first place.
**- How to verify it**
golint

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
LGTM (if CI green)

Can you open another PR for bumping up golint version defined in Dockerfiles?

**Comment by YuPengZTE** [comment]
@AkihiroSuda , you mean the 
“ENV GO_LINT_COMMIT 32a87160691b3c96046c0c678fe57c5bef761456”
of Dockerfiles is old?
image

**Comment by AkihiroSuda** [comment]
Yes, recently golint came able to check the position of context arg, so I suggest updating golint (https://github.com/golang/lint/commit/3390df4df2787994aea98de825b964ac7944b817)

Perhaps you should use hack/dockerfile/install-binaries.sh for managing the version of golint.

**Comment by YuPengZTE** [comment]
OK.
Thanks @AkihiroSuda .

**Review by vdemeester — APPROVED** [review]
LGTM 🐸

**Comment by thaJeztah** [comment]
@YuPengZTE will you be doing a follow-up for bumping golint, or want one of the maintainers to take care of that?

**Comment by YuPengZTE** [comment]
@thaJeztah
I use the https://github.com/golang/lint/commit/3390df4df2787994aea98de825b964ac7944b817 to check the commit https://github.com/docker/docker/commit/bd78374618dd4282445cd3b7230a22ba0b2b237d
, and found some mistake

[golint4docker.txt](https://github.com/docker/docker/files/584918/golint4docker.txt)
image

Some mistakes are Caused by docker, but some mistakes are Caused by golint, for example
image

So, in my opinion, the 
“ENV GO_LINT_COMMIT 32a87160691b3c96046c0c678fe57c5bef761456”
of Dockerfiles is no need to change now, I can fix the other typos, such as
 "context.Context should be the first parameter of a function"
and so on.

What do you think?

**Comment by AkihiroSuda** [comment]
OK, no need to change.
At least no need for 1.13.0.

**Pull request merged**
