### PR TITLE
vendor: github.com/containerd/containerd v1.5.2

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/containerd/containerd/compare/19ee068f93c91f7b9b2a858457f1af2cabc7bc06...v1.5.2
I'll be looking if other dependencies need to be updated for containerd, but these were the minimal changes

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
What's current status?

**Comment by thaJeztah** [comment]
Arf that ebpf rename of `readme.md  -> README.md` keeps following me :disappointed:


```
[2021-06-04T12:19:15.787Z] The result of vndr differs
[2021-06-04T12:19:15.787Z] 
[2021-06-04T12:19:15.787Z]  D vendor/github.com/cilium/ebpf/readme.md
[2021-06-04T12:19:15.787Z] 
[2021-06-04T12:19:15.787Z] Please vendor your package with github.com/LK4D4/vndr.
```

**Review by AkihiroSuda — APPROVED** [review]

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by samuelkarp — APPROVED** [review]
LGTM

**Pull request merged**
