### PR TITLE
bump api version to 1.20

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by estesp** [comment]
LGTM

**Comment by calavera** [comment]
LGTM

**Comment by estesp** [comment]
I don't think this needs docs review as the start of the API docs is just a copy of the prior (so 1.20 should be 1.19 copied, and any changes will now be made in 1.20)

**Comment by calavera** [comment]
I agree on that, but there is a markdown file with changes, therefore it needs docs review. Just following the rules :smile_cat:

**Comment by thaJeztah** [comment]
Da Rulez!

LGTM

Are docs for the release also cherry-picked? If not, then possibly the mkdocs.yml should not yet be updated.

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit

**Comment by LK4D4** [comment]
Thanks, LGTM

**Comment by moxiegirl** [comment]
@duglin @calavera I'm actually finding typos and stuff in the docs. So, I'd like a change. Unless this is generated from source -- my initial search seemed to indicate that was **not** the case.

**Comment by thaJeztah** [comment]
pay attention to https://github.com/docker/docker/pull/13446#issuecomment-106550415 before merging

**Comment by moxiegirl** [comment]
@thaJeztah idk, if I merge first shouldn't the other PR rebase and the change on their end?

**Comment by thaJeztah** [comment]
@moxiegirl not sure if a rebase works because it is a *copy* of the file. Therefore I added the note so that we can pay attention before merging :smiley:

**Comment by thaJeztah** [comment]
Oh, and it depends wether or not the other PR is included in 1.7

**Comment by moxiegirl** [comment]
Thanks @thaJeztah I read the other pr a couple of times...and was confuzzled.  (Could ya tell?) So, glad you are guiding...

**Comment by estesp** [comment]
The whole point of bumping the API is to recognize that master is now "beyond" 1.7.0 and will have a different version API, unless I'm missing the flow here.. if we want edits to make 1.7.0 then I would go look at editing the 1.19 file and getting that cherry picked into the bump branch.

**Comment by moxiegirl** [comment]
@estesp I'm making changes to the 1.20 version. Isn't that the current?

**Comment by estesp** [comment]
@moxiegirl: it will be when this PR is merged..it doesn't exist yet as this PR creates it :) It will most likely be the API version for the release after 1.7.0.  So, in terms of making sure this is "good" from a docs standpoint, it is very worthwhile to make edits; I just wanted to be clear this isn't part of the 1.7.0 release that is at rc1.

**Comment by thaJeztah** [comment]
1.7 == v1.19, 1.8 will be v1.20

remind me, we should really add a Docker version / API version matrix somewhere

**Comment by moxiegirl** [comment]
Ok. Let me see if I can sort this.  I'm almost done and quite frankly the file had a lot of cruft built up over time. I'm doing minimal rewrite -- mostly typos and crufty formatting for readability. I can branch from my change and make a another PR which might be easier -- can't hurt and readability is improved.

**Comment by jfrazelle** [comment]
what are we bikeshedding over right now

**Comment by thaJeztah** [comment]
@jfrazelle, @moxiegirl is making some copy edits to 1.19 and update 1.20 with that

**Comment by jfrazelle** [comment]
ah ok gotcha, i can wait :)

**Comment by moxiegirl** [comment]
@jfrazelle there is a lot of crap in this file; I noticed last release but didn't  have any scope to clean it up
since it is just a bump; eagle eye @thaJeztah and I can handle the docs review. I'm not changing any technical content. Just formatting.

**Comment by jfrazelle** [comment]
ok updated merge my PR!

**Comment by moxiegirl** [comment]
LGTM!!!! \O/\o/

**Pull request merged**
