### PR TITLE
Bump Golang 1.13.11

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/golang/go/compare/go1.13.10...go1.13.11

go1.13.11 (released 2020/05/14) includes fixes to the compiler. See the Go 1.13.11
milestone on the issue tracker for details:

https://github.com/golang/go/issues?q=milestone%3AGo1.13.11+label%3ACherryPickApproved

### CODE REVIEW

**Comment by thaJeztah** [comment]
Golang update looks to be fixing issues on s390x

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Wait; why are all builds failing?

```

[2020-05-16T13:13:07.334Z] #43 [gotestsum 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     ...
[2020-05-16T13:13:07.334Z] #43 107.2 + cd /tmp/tmp.AtFYNgLZrz/src/gotest.tools/gotestsum
[2020-05-16T13:13:07.334Z] #43 107.2 + git checkout -q v0.3.5
[2020-05-16T13:13:07.334Z] #43 107.3 + go build -buildmode=pie -o /build/gotestsum gotest.tools/gotestsum
[2020-05-16T13:13:07.334Z] #43 108.0 handler.go:8:2: cannot find package "github.com/sirupsen/logrus" in any of:
[2020-05-16T13:13:07.334Z] #43 108.0 	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
[2020-05-16T13:13:07.334Z] #43 108.0 	/tmp/tmp.AtFYNgLZrz/src/github.com/sirupsen/logrus (from $GOPATH)
[2020-05-16T13:13:07.334Z] #43 ERROR: executor failed running [/bin/sh -c PREFIX=/build /tmp/install/install.sh gotestsum]: runc did not terminate sucessfully



[2020-05-16T13:13:02.644Z] #39 [criu 2/2] RUN mkdir -p /usr/src/criu     && curl -sSL https://github.co...
[2020-05-16T13:13:02.644Z] #39 3.600 Note: Building without setproctitle() and strlcpy() support.
[2020-05-16T13:13:02.644Z] #39 3.600       To enable these features, please install libbsd-devel (RPM) / libbsd-dev (DEB).
[2020-05-16T13:13:02.644Z] #39 3.624 Note: Building without GnuTLS support
[2020-05-16T13:13:04.546Z] #39 5.382 fatal: not a git repository (or any of the parent directories): .git
[2020-05-16T13:13:04.546Z] #39 5.477   GEN      .gitid
[2020-05-16T13:13:04.546Z] #39 ...
[2020-05-16T13:13:04.546Z]
```

**Comment by thaJeztah** [comment]
Kicked CI to see if it was a temporary issue with GitHub

**Comment by thaJeztah** [comment]
Nope; looks like an actual regression?

Wondering if it's an issue in the image, or golang

**Comment by thaJeztah** [comment]
So... I just saw https://github.com/gotestyourself/gotestsum/pull/110

Is go modules somehow looking for the go modules from "master" instead of the version we checked out???

**Comment by thaJeztah** [comment]
OK, so this fails on Go 1.13.10 as well.

What happens is;

First, we `go get` the package;

```
GO111MODULE=off go get -d gotest.tools/gotestsum
```

Which gets the latest version from master, and fetches the _dependencies_ used on master

Then we checkout the `v0.3.5` version, and run `go build`

that fails, because master no longer depends on logrus (so the initial `go get` didn't fetch it), and `v0.3.5` _does_

**Comment by thaJeztah** [comment]
moved to draft, waiting for https://github.com/moby/moby/pull/40979 to be merged

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
Looks like ppc64le images are missing; build status: https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/golang/. Some previous builds failed because the node was out of disk space; perhaps that's the problem?

```
E: Failed to fetch http://deb.debian.org/debian/dists/buster/main/binary-ppc64el/Packages  Error writing to output file - write (28: No space left on device) [IP: 172.17.0.2 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

/cc @tianon ^^

**Comment by tianon** [comment]
Yeah sorry, the server filled up thanks to several base updates in a row and then took a long time to churn through the queue; it should be fixed/finished now!

**Comment by thaJeztah** [comment]
No worries! I don't think there was an urgency in this specific update of Go.

Kicking jenkins to see if it goes green; thanks!

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
