### PR TITLE
Deprecate 'docker run -c' option in zsh completion

### PR DESCRIPTION
**Pull request by sdurrheimer**
Ref. #16271

ping @albers for bash

Signed-off-by: Steve Durrheimer s.durrheimer@gmail.com

### CODE REVIEW

**Comment by vdemeester** [comment]
Added this to 1.9.0 milestone (as the command is in there).

**Comment by calavera** [comment]
LGTM. This flag was removed for 1.9 and it should not be in the completion list.

**Comment by vdemeester** [comment]
Ah lol, my comment is wrong, but my action right :sweat_smile:

**Comment by cpuguy83** [comment]
LGTM

**Comment by sdurrheimer** [comment]
In my opinion, `-c` should also be removed from `docker create` and `docker build`, for consistency.

**Comment by thaJeztah** [comment]
@sdurrheimer can you open a separate issue for that? /cc @tiborvass

**Comment by sdurrheimer** [comment]
Done #17117

**Pull request merged**
