### PR TITLE
Fix grammar for "does not exist"

### PR DESCRIPTION
**Pull request by frobnicaty**
as opposed to "does not exists"

### CODE REVIEW

**Comment by tianon** [comment]
Great catch!  I wish the DCO bot had some ability to determine when a patch is trivial (and thus doesn't need a DCO); any chance you can amend your commit message to add the sign off?

(If you're having trouble doing so, don't hesitate to ask for help -- I'd give some useful links right now, but I'm reviewing from my phone where they're a little harder to find 😅)

**Comment by thaJeztah** [comment]
@frobnicaty are you able to update this PR? (let us know if you need help doing so)

**Comment by frobnicaty** [comment]
@thaJeztah Done.

**Review by thaJeztah — APPROVED** [review]
Thank you!!

LGTM

**Review by tianon — APPROVED** [review]

**Pull request merged**
