### PR TITLE
Fixes hacks from progressreader refactor

### PR DESCRIPTION
**Pull request by robertabbott**
related to #10959

Signed-off-by: bobby abbott ttobbaybbob@gmail.com

### CODE REVIEW

**Comment by LK4D4** [comment]
@robertabbott Something wrong with your sing. Did you sign with `git commit -s`?

**Comment by robertabbott** [comment]
@LK4D4 Apparently not. I will fix the commit message this evening. Sorry about that.

**Comment by estesp** [comment]
Thanks for handling the cleanup! For reviewers that didn't see the prior PR (noted above), this resolves a hack that had to go in after only moving related content (the **progressreader** portion) from `docker/util` to `pkg`.

LGTM

**Comment by robertabbott** [comment]
fixed some merge conflicts. Can you guys check this out again @estesp @crosbymichael

**Comment by LK4D4** [comment]
@robertabbott Thank you! Very impressive work.

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
