### PR TITLE
Optimize slow bottleneck test of DockerSuite.TestRunUnshareProc.

### PR DESCRIPTION
**Pull request by yongtang**
This fix tries to improve the speed of TestRunUnshareProc in #19425.

In this fix goroutines are used to run test cases in parallel to prevent the test from taking a long time to run.

As the majority of the execution time in the tests is from multiple executions of 'docker run' and each of which takes several seconds, parallel executions improve the test time.

Since each 'docker run' is independent, the purpose of the test is not altered in this fix.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Can you please add a comment explaining that the test cases are being run in parallel to reduce execution time of the test?

I think having the channel have type `error` would be slightly better. That makes it clear that a `nil` error means no error, as opposed to an empty string which is not as obvious.

**Comment by yongtang** [comment]
@aaronlehmann Sure let me update the pull request.

**Comment by yongtang** [comment]
@aaronlehmann Just updated the pull request. Please let me know if there are any issues.

**Comment by aaronlehmann** [comment]
Thanks. The error channel looks good. Can you please add a comment explaining that the goroutines are used to run test cases in parallel to prevent the test from taking a long time to run?

**Comment by yongtang** [comment]
@aaronlehmann Sure just updated the comment. Let me know if there are any other issues.

**Comment by estesp** [comment]
@yongtang I don't see the comment in the code; did you update (push) the PR branch?

**Comment by yongtang** [comment]
@estesp Thanks I forgot the push -f. The PR push was updated a moment ago. Let me know if there are any other issues.

**Comment by aaronlehmann** [comment]
@yongtang: I still don't see the comment :(

**Comment by yongtang** [comment]
Hi @aaronlehmann I am still new to docker at github so might be referring to different places. I added
```
In this fix goroutines are used to run test cases in parallel to prevent the test from taking a long time to run.
``` 
in the commit message and the pull request message before. Is that what you want?

**Comment by yongtang** [comment]
@aaronlehmann Oh I think you are referring to the "comment" in the code section. Sorry I didn't realize that. Will update the pull request shortly.

**Comment by yongtang** [comment]
@aaronlehmann Just updated the pull request. The comment was added above the line of
```
	errChan := make(chan error)
```
Pardon my misunderstanding and let me know if there are any other issues.

**Comment by aaronlehmann** [comment]
No problem. Sorry for the confusion.

LGTM

**Comment by yongtang** [comment]
@estesp Any feedback or additional issues I need to address?

**Comment by estesp** [comment]
LGTM

**Pull request merged**
