### PR TITLE
Update doc docker_remote_api_v1.20.md

### PR DESCRIPTION
**Pull request by longliqiang88**
After test,using name in version 1.8 is OK,so I update the file  docker_remote_api_v1.20.md 
Thank you. @thaJeztah

### CODE REVIEW

**Comment by longliqiang88** [comment]
@HackToday

**Comment by longliqiang88** [comment]
Thank you for looking.@thaJeztah @HackToday  .I hope it can be merged. it's appreciated!

**Comment by thaJeztah** [comment]
LGTM, can you also do the other API versions?

ping @vdemeester

**Comment by vdemeester** [comment]
LGTM 🐶

**Pull request merged**
