### PR TITLE
Check for swarm-mode network conflict during create network

### LINKED ISSUE #23983: `docker network create -d bridge test` works if there is already an overlay network named test?
**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:02:41 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 380
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: active
 NodeID: 4b1et52uyr6nquyj7js30fgcu
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:9ebab8ad017aa10bd8eee00ba34f7e22932deeee38adf6e864786fb643668caf
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.`docker network create -d overlay test` to create an overlay network named test
2.`docker network create -d bridge test` to create a bridge network named test

Above steps can work. Actually they own the same name. It is a **CONFLICT** in the network naming.

While if I create bridge network named test, then create overlay network named test, daemon will report an error named:
```
Error response from daemon: network with name test already exists
```

In addition, This bug will result in `docker network inspect test` works if two networks with same name on a single daemon.

### PR DESCRIPTION
**Pull request by mavenugo**
Reverts https://github.com/docker/docker/pull/24158 which causes service create to fail if it is attached to multiple networks. We need to find another better way to handle the case of failing network connect/disconnect for managed containers.

Fixes #23983

### CODE REVIEW

**Comment by tiborvass** [comment]
@mavenugo can you clarify the situation? The issue this pr is supposed to fix, is already closed. Should we reopen it?

**Comment by mavenugo** [comment]
@tiborvass #24158 solves #23983. But along with the correct patch, I incorrectly added another fix which caused an issue wherein a service fails if it has multiple networks.

With this PR, am retaining just the fix that is required to solve #23983, but removing the incorrect patch that is causing the breakage.

**Comment by tiborvass** [comment]
LGTM

**Comment by thaJeztah** [comment]
Should we have a test?

**Comment by mavenugo** [comment]
@thaJeztah since this involves swarm-mode & there is a bigger effort on introducing proper IT for swarm-mode, I was hoping to add it as part of that.  Will that work ?
Yes. this particular case can be tested with a simple 1 node cluster. But so are many other swarm-mode tests.

**Comment by thaJeztah** [comment]
alright, as long as we don't forget

LGTM

**Comment by mavenugo** [comment]
@tiborvass just to confirm ... the Cherry-pick should only be done on the the commit : 6a4b21bd863f955d05e5df1e54be4dfcf6889870 . The other one is a revert and hence it can be safely ignored.

**Comment by tiborvass** [comment]
@mavenugo it's automated so it will cherrypick both.

**Pull request merged**
