### PR TITLE
[UX Proposal] service list: Display update status

### PR DESCRIPTION
**Pull request by aluzzardi**
This is a quick addition that lets users see at a glance how the rolling updates are going (today, the only way to figure that out is to `docker inspect`).

This PR adds a column that displays the status of the update in `service ls`.

I'm not 100% sure and this is definitely not for 1.12.

```
$ docker service create --name vote instavote/vote
5yoptbu7nuh52nwkeii19z9xx
$ docker service ls
ID            NAME  UPDATE STATUS  REPLICAS  IMAGE           COMMAND
5yoptbu7nuh5  vote                 1/1       instavote/vote
$ docker service update vote --image instavote/vote:indent
vote
$ docker service ls
ID            NAME  UPDATE STATUS                 REPLICAS  IMAGE                  COMMAND
5yoptbu7nuh5  vote  Updating since 2 seconds ago  0/1       instavote/vote:indent
$ docker service ls
ID            NAME  UPDATE STATUS            REPLICAS  IMAGE                  COMMAND
5yoptbu7nuh5  vote  Completed 5 seconds ago  1/1       instavote/vote:indent
```

/cc @aaronlehmann @vieux @dnephin 

[PS: @aaronlehmann I really believe we should have used `timestamp` rather than `started/created_at` after implementing this :)]

### CODE REVIEW

**Comment by dnephin** [comment]
Seems ok to me.

**Comment by vieux** [comment]
seems ok to me too, but it feels weird to have `UPDATE STATUS` set to `""` at first

**Comment by vdemeester** [comment]
/ping @aaronlehmann @stevvooe @tonistiigi for review 👼

**Comment by aaronlehmann** [comment]
I'm not sure about this one. I agree with the need to make this information more visible. But we're trying to cram a lot of information in a one-line summary view. It could be a bit intimidating.

My other thought is that if there has not been a recent update, this column won't be useful, and might even be confusing. Seeing "completed 5 days ago" might make it look like the service itself has completed, if someone talks that info out of context.

I wonder if we could only show this column if at least one service has an update in progress, but I'm not sure dynamically changing the set of columns we show is a good idea, or whether there's any precedent for that.

**Comment by dnephin** [comment]
That's a good point. "Completed" should probably say "Last updated" or even just "Updated". We could make the header just "STATUS", and show "Created x ago" if there hasn't been any updates yet.

**Comment by thaJeztah** [comment]
ping @aluzzardi @aaronlehmann where are we on this? Are you good with @dnephin's suggestion above?

**Comment by aaronlehmann** [comment]
Yeah, @dnephin's proposal sounds good.

Again, my main concern is trying to put too much information on every line. If it feels necessary, we should consider removing `IMAGE` and/or `COMMAND` to make space for this. Neither seems particularly useful for a summary view like this.

**Comment by thaJeztah** [comment]
Yes, we need docker-optimized monitors for various commands 😞 

docker-cli-optimized-monitor

**Comment by thaJeztah** [comment]
We're ok with adding this, and (if needed), drop the image column, because update status may be more useful than image

**Comment by stevvooe** [comment]
Why don't we abstract this based on our model? The question here is whether or not the service has converged. This is interesting if there is update or any other kind of failure.

**Comment by thaJeztah** [comment]
@stevvooe could you explain a bit more how you'd like this implemented?

**Comment by stevvooe** [comment]
@thaJeztah The question is whether or not the orchestrator has to perform work to get to the target state. This could be due to an update, but it could also be due to a change in the cluster topology or failures.

**Comment by aaronlehmann** [comment]
Can this make it into 1.13?

@aluzzardi: Needs a rebase.

**Comment by LK4D4** [comment]
ping @aluzzardi @stevvooe what's up here?

**Comment by vdemeester** [comment]
ping @aluzzardi

**Comment by LK4D4** [comment]
Ok, this was a long time without attention. So it's not so important and can be opened again as a carry.

**Pull request closed without merging**
