### PR TITLE
classify stdout and stderr when stack remove

### PR DESCRIPTION
**Pull request by allencloud**
**\- What I did**
1. make some normal things in stdout rather than stderr in command `docker stack rm ...`

**\- How I did it**

**\- How to verify it**

**\- Description for the changelog**

Signed-off-by: allencloud allen.sun@daocloud.io

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'm not sure, but I know sometimes such messages are *deliberately* sent to `stderr`, so that users can split the "informational" messages from the "result" (i.e. redirect stderr, and capture the `"success"` message in their scripts)

**Comment by dnephin** [comment]
Exactly. I think `stderr` is more correct. `stdout` is only for "normal program output". If the user runs a command to get the output of something, that would go to `stdout`. The ouput of ps, inspect, images, etc would all make sense on `stdout`.

Everything else (logs, information messages, warnings, errors, etc) should all go to `stderr`.  These are just log messages, not "normal program output". The user is running the command to remove the stack, not to display some information.

**Comment by thaJeztah** [comment]
I agree; I think the confusion is always that it's called `stderr`, even though we're not sending errors there (should've been called `stdinfo` :smile:)

I'll go ahead and close this, but thanks for contributing @allencloud!

**Pull request closed without merging**
