### PR TITLE
Fix Racy TestCleanup on container/image/volume/network removal

### PR DESCRIPTION
**Pull request by simonferquel**
As actual errors like "containerNotFound" are rehydrated from http
message body, they loose their typing and thus client.IsErrNotFound(err)
always returns false. This PR adds a test using a regexp that avoids CI
to fail on cleanups where a container is removed concurrently to the
Cleanup code.

As container operations are much slower on Windows that on Linux, we see this happen almost only on Windows (but quite frequently).

**- What I did**

Added some error checking on test cleanup to ignore concurrent resource removals

**- How I did it**

Added regexp / strings.Contains() calls

**- How to verify it**

Run CI. Windows failure rate should go down significantly

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by dnephin** [comment]
Thanks for looking into this. I noticed this failure in some builds and was going to start debugging this today.

I don't think I understand why `client.IsErrNotFound()` doesn't work. What do you mean by "are rehydrated from http message body". All the "remove" errors should be communicated with HTTP status codes, which should be converted into `notFound` errors by the `client` package.

If this isn't the case we should fix the client package instead of relying on regex. This is going to be a problem for all consumers of `client` not just the test suite.

**Review by dnephin — COMMENTED** [review]
So looking at the `client` I see that a lot of the Remove calls don't actually properly handle the 404 error.

I think we should fix the client to properly return the expected error.

**Comment by simonferquel** [comment]
Yes @dnephin I suspect the problem is there: the delete calls not found errors are not translated correctly to a typed notfound error and so client.IsErrNotFound() returns false.
I suppose we should add unit tests somewhere in client package for fixing the underlying issue.
I should probably be able to tackle this on Monday next week (if you can assign me an issue).

In the mean time, this PR should stabilize CI quite a lot.

**Comment by dnephin** [comment]
I've opened #34784 with the fix to the client/, so I don't think we need to add the string comparison workaround. The Volume and Network deleteAll could still use a `IsErrNotfound()` check.

**Comment by simonferquel** [comment]
Closed in favor of #34784

**Pull request closed without merging**
