### PR TITLE
Add location of daemon.json for mac

### PR DESCRIPTION
**Pull request by jmaitrehenry**
Fix documentation issue https://github.com/docker/docker.github.io/issues/2643

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by mstanleyjones** [comment]
Hey, please sign the commit. :) In your terminal, you can do `git commit --amend -s` and then `git push -f origin` (assuming your fork's remote is called `origin`).

**Comment by jmaitrehenry** [comment]
It was what I currently doing, I made the PR via github UI :)


On April 19, 2017 at 4:37:02 PM, Misty Stanley-Jones (notifications@github.com) wrote:

Hey, please sign the commit. :) In your terminal, you can do git commit --amend -s and then git push -f origin (assuming your fork's remote is called origin).

**Review by mdlinville — APPROVED** [review]

**Comment by mstanleyjones** [comment]
Approved after the commit is signed.

**Comment by mstanleyjones** [comment]
@thaJeztah or @vdemeester PTAL

**Comment by samoht** [comment]
What is the use-case? It is not recommend to edit the file manually (use the UI instead) but if you want to read it, it's probably simpler to use:

```
docker run -v /etc:/etc alpine cat /etc/docker/daemon.json
```
(if your docker app is working)

**Review by samoht — CHANGES_REQUESTED** [review]
This will not work in general (that path is a bare Git repository, by default the files will not show up). But depending on the use-case you have various other ways to do it.

**Comment by jmaitrehenry** [comment]
The use case was a user that doesn't have access to the UI could SSH in a mac box and made the change.
I take the use case from the document issue: https://github.com/docker/docker.github.io/issues/2643 where @mstanleyjones say the same thing:
> You shouldn't edit it directly. You should go to the whale in the taskbar > Preferences > Daemon > Advanced.

**Comment by jmaitrehenry** [comment]
I could add a note about the fact the file may not be present and a user can create it manually at is own risk and add a notice about not using this file but the UI ?

**Comment by samoht** [comment]
The UI is caching a version of that file as well, so it really not a good idea to edit it manually.

**Comment by mstanleyjones** [comment]
@samoht what is the alternative for users who do not use the OSX GUI? Why not tell them to restart Docker if they edit the `daemon.json`?

**Comment by jmaitrehenry** [comment]
I updated the note for adding more information about how to update the file and editing the mac file is a bad idea.

**Comment by jmaitrehenry** [comment]
@samoht is it resolve your issue about the modification?

**Comment by samoht** [comment]
@jmaitrehenry if you really want to update the file manually the correct sequence of operations is:

```
$ cd ~/Library/Containers/com.docker.docker/Data/database/
$ git reset --hard
$ emacs com.docker.driver.amd64-linux/etc/docker/daemon.json
$ git commit -a -m "Update the daemon config"
```
(e.g. `database` is a Git repository)

This is really not recommend to do that when the Docker application is running though, as the UI is caching the file in memory on startup so it could result in conflicts and the application unable to restart. We also do not commit to keep that location stable.

**Comment by mstanleyjones** [comment]
OK, so we have been told we shouldn't document this. Product management has been made aware of this use case and it would be great if a better solution is developed. Thanks for all your hard work on researching this!

**Comment by jmaitrehenry** [comment]
No problem, in case you need it, I just updated my PR for adding more information about that is not a good idea but how to do that.

**Pull request closed without merging**
