### PR TITLE
refactored network integration tests to make use of swarm.CreateService

### PR DESCRIPTION
**Pull request by adshmh**
Refactored the network integration tests to make use of `swarm.CreateService` utility function, to address the `//FIXME` item under `integration/network/inspect_test.go`

Signed-off-by: Arash Deshmeh <adeshmeh@ca.ibm.com>

**- What I did**
Refactored the network integration tests to make use of `swarm.CreateService` utility function.

**- How I did it**
Refactored tests under `integration/network`, and added the required functions under `integration/internal/swarm/service.go`

**- How to verify it**

**- Description for the changelog**
Network integration tests use swarm.CreateService for testing.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by thaJeztah** [comment]
Experimental is failing on a flaky test: https://jenkins.dockerproject.org/job/Docker-PRs-experimental/40151/console (tracked through https://github.com/moby/moby/issues/34051)

```
22:51:28 FAIL: docker_cli_swarm_test.go:1147: DockerSwarmSuite.TestSwarmLockUnlockCluster
22:51:28 
22:51:28 [d58391081e513] waiting for daemon to start
22:51:28 [d58391081e513] daemon started
22:51:28 
22:51:28 [da9a701b88656] waiting for daemon to start
22:51:28 [da9a701b88656] daemon started
22:51:28 
22:51:28 [d34e593e5acd2] waiting for daemon to start
22:51:28 [d34e593e5acd2] daemon started
22:51:28 
22:51:28 [da9a701b88656] exiting daemon
22:51:28 [da9a701b88656] waiting for daemon to start
22:51:28 [da9a701b88656] daemon started
22:51:28 
22:51:28 [da9a701b88656] exiting daemon
22:51:28 [d58391081e513] exiting daemon
22:51:28 [d58391081e513] waiting for daemon to start
22:51:28 [d58391081e513] daemon started
22:51:28 
22:51:28 [d34e593e5acd2] exiting daemon
22:51:28 [d34e593e5acd2] waiting for daemon to start
22:51:28 [d34e593e5acd2] daemon started
22:51:28 
22:51:28 [da9a701b88656] waiting for daemon to start
22:51:28 [da9a701b88656] daemon started
22:51:28 
22:51:28 [da9a701b88656] exiting daemon
22:51:28 [da9a701b88656] waiting for daemon to start
22:51:28 [da9a701b88656] daemon started
22:51:28 
22:51:28 [d58391081e513] exiting daemon
22:51:28 [d58391081e513] waiting for daemon to start
22:51:28 [d58391081e513] daemon started
22:51:28 
22:51:28 docker_cli_swarm_test.go:1201:
22:51:28     checkSwarmLockedToUnlocked(c, d, unlockKey)
22:51:28 docker_cli_swarm_test.go:1019:
22:51:28     c.Assert(getNodeStatus(c, d), checker.Equals, swarm.LocalNodeStateActive)
22:51:28 ... obtained swarm.LocalNodeState = "pending"
22:51:28 ... expected swarm.LocalNodeState = "active"
22:51:28 
22:51:28 [d58391081e513] exiting daemon
22:51:28 [da9a701b88656] exiting daemon
22:51:28 [d34e593e5acd2] exiting daemon
22:51:42 
```

restarting CI

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
Tried to restart the Jenkins build though the Jenkins is not picking up. Maybe some infrastructure issues?

**Comment by thaJeztah** [comment]
Triggering through slack seemed to work; perhaps the bot is having connection issues

**Comment by adshmh** [comment]
The 2 failures that I can get the logs for (`experimental` and `powerpc`) do not seem related to this PR:
`DockerSwarmSuite.TestAPISwarmLeaderElection` is failing.

**Pull request merged**
