### PR TITLE
[carry 28783] update plugin example

### PR DESCRIPTION
**Pull request by thaJeztah**
carries #28783 - fixed whitespace formatting of the JSON example
closes #28783

ping @vieux

### CODE REVIEW

**Comment by thaJeztah** [comment]
hold on, I can make it slightly less verbose

**Comment by thaJeztah** [comment]
done :)

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
ping @tiborvass

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
