### PR TITLE
Vendoring libnetwork & swarmkit to address #27147

### PR DESCRIPTION
**Pull request by aboch**
cherry-picking docker/swarmkit#1600 and docker/libnetwork#1489

Signed-off-by: Alessandro Boch aboch@docker.com

### CODE REVIEW

**Comment by aboch** [comment]
cc @mrjana @vieux

**Comment by vieux** [comment]
LGTM ping @crosbymichael @mlaventure

**Comment by mavenugo** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
@vieux added "impact/changelog" as this should probably be mentioned in the changelog (no longer allowed to attach a service to the ingress network)

**Pull request merged**
