### PR TITLE
[27.x backport] Create docker-proxy TCP/UDP listener sockets in the daemon

### PR DESCRIPTION
**Pull request by thaJeztah**
Backport:

- https://github.com/moby/moby/pull/48247
- (for clean cherry) https://github.com/moby/moby/pull/48248
- https://github.com/moby/moby/pull/48132
- https://github.com/moby/moby/pull/48318

-----

### Create docker-proxy TCP/UDP listener sockets in the daemon

**- What I did**

- Fix https://github.com/moby/moby/issues/47951
- Relates to https://github.com/moby/moby/pull/47871

Before commit 4f09af6267, when allocating host ports for a new port mapping iptables rules were set up, then docker-proxy was started. If the host port was already in-use, docker-proxy exited with an error, and the iptables rules were removed. That could potentially interfere with a non-docker service that was already using the host port for something unrelated.

Commit 4f09af6267 swapped that problem for a different one... in order to check that a port was available before creating iptables rules, it attempted to start docker-proxy first. If it failed, it could then try a different host port, without interfering with any other service. The problem with that is docker-proxy would start listening before the iptables rules were in place, so it could accept connections then become unusable because new NAT rules diverted packets directly to the container. This would leave the client with a broken connection, causing at-least a delay while it figured that out and reconnected.

**- How I did it**

This change creates and binds the socket in the daemon, before creating iptables rules. If the bind fails, it may try a different port. When or if the bind succeeds, iptables rules are created, then the daemon calls listen on the socket. If docker-proxy is needed, the socket is handed over to it at that point.

If docker-proxy is not needed (`--userland-proxy=false`), the daemon still listens on TCP sockets as the `dummyProxy` would have done. This makes the socket show up in `netstat` output.

The `dummyProxy` is no longer needed on Linux. Its job was to bind the host ports if docker-proxy was disabled, but that's now already handled by binding the sockets early.

This change doesn't affect SCTP, because it's not currently possible for docker-proxy to convert the file descriptor into an SCTPListener. So, docker-proxy is still started early, and the window for lost connections remains.

A new option has been added to `docker-proxy`, `-use-listen-fd` to tell it that fd 4 is a listener socket. It no longer needs to know the "frontend" address/port for TCP/UDP, but it's useful to see the options in the command line to work out which docker-proxy is which. (As a follow-up, it'd be possible to read the address/port from the fd and display it in the process title.)

If the user has an old docker-proxy in their path it'll fail for TCP/UDP, because it won't recognise the new command line option that says an listen-fd has been supplied as fd 4. In this case, the daemon's error message suggests checking $PATH.

RootlessKit used a proxy for `docker-proxy` called `rootlesskit-docker-proxy`. Its job was to make RootlessKit API calls to tell it about mapped host ports when necessary, before starting the usual `docker-proxy`, and then to remove that mapping when stopping the proxy. The `rootlesskit-docker-proxy` didn't know about new option `-use-listen-fd`, or the open sockets passed-in. Rather than update `rootlesskit-docker-proxy`, replace it by making the RootlessKit API calls directly from the daemon. That'll make it possible to continue to evolve `docker-proxy`, without having to keep `rootlesskit-docker-proxy` in-step (for example, we may go to a single `docker-proxy` per container rather than per port-mapping). It also makes it possible to set up those mappings in RootlessKit without running the proxy, when `--userland-proxy=false`. Because `rootlesskit-docker-proxy` is no longer used, it's no longer built.

**- How to verify it**

Updated tests.

The port mapping tests relied on `startProxy` being called to check that expected ports had been selected. That call is not made now, because`dummyProxy` isn't used. So, changed most of the tests to make them start the proxy.

For tests of behaviour where a host port is unexpectedly unavailable, a real `bind()` now needs to fail in the daemon code being tested (the test's mock proxy can't report that it would have failed, because it's called much later in the process). So, the tests now set up a dummy bridge in their n/w namespace, add any host addresses necessary to that bridge, and bind ports that need to be busy - before the test starts.

With an old `docker-proxy` in the path, the error looks like this ...

`docker: Error response from daemon: driver failed programming external connectivity on endpoint fervent_brattain (b4a9c5ebe14946f70c12c304da95abf41ed8b804903879c1163030ddbdbf1273): failed to start userland proxy for port mapping 0.0.0.0:8080:172.21.0.2:80/tcp: failed to start docker-proxy, check that the current version is in your $PATH.`

(I hacked a `NewSCTPListener(fd)` into the sctp package, and checked that it worked with the socket bound in the daemon. So we can propose a change like that, then align SCTP socket creation with TCP/UDP.)

**Rootless**

Mapping from unspecified host address ...

```
$ docker run --rm -ti --network n1 -p 8080:80 nginx
$ ps -ef | grep docker-proxy
robm       39815   39165  0 18:37 ?        00:00:00 /home/robm/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 8080 -container-ip 172.18.0.2 -container-port 80
robm       39822   39165  0 18:37 ?        00:00:00 /home/robm/bin/docker-proxy -proto tcp -host-ip ::1 -host-port 8080 -container-ip 172.18.0.2 -container-port 80

These work ...
curl http://192.168.175.43:8080 # host ip
curl http://127.0.0.1:8080
curl http://[::1]:8080
```

Mapping from a specific host address ...

```
$ docker run --rm -ti --network n1 -p 192.168.175.43:8080:80 nginx
$ ps -ef | grep docker-proxy
robm       39978   39165  0 18:39 ?        00:00:00 /home/robm/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 8080 -container-ip 172.18.0.2 -container-port 80
```

Mapping from two specific host addresses, before the change ...

```
$ docker run --rm -ti --network n1 -p 192.168.175.43:8080:80 -p 127.0.0.1:8080:80 nginx
<long delay, the 16s timeout on trying to start rootlesskit-docker-proxy>
docker: Error response from daemon: driver failed programming external connectivity on endpoint admiring_williamson (b3d757bf1d0832fcc85eccd9692c72fb24ba2ec817495e977824516cbfbdcda2): failed to bind port 192.168.175.43:8080/tcp: Timed out proxy starting the userland proxy.

<then subsequent valid requests for the same mapped port fail with an error from RootlessKit>
$ docker run --rm -ti --network n1 -p 192.168.175.43:8080:80 nginx
docker: Error response from daemon: driver failed programming external connectivity on endpoint xenodochial_taussig (24118b2865fa4fc3f314cf172c21d1118e3a28aa0cccce82d33ceff002eaf3a9): failed to bind port 192.168.175.43:8080/tcp: Error starting userland proxy: error while calling PortManager.AddPort(): conflict with ID 2.

<need to restart rootlesskit>
```

After the change - binding fails immediately, because both mappings end up trying to use the same child address ...

```
$ docker run --rm -ti --network n1 -p 192.168.175.43:8080:80 -p 127.0.0.1:8080:80 nginx
docker: Error response from daemon: driver failed programming external connectivity on endpoint charming_johnson (1d749d940f091a93108d8364ae658a9c8b44b57b362963cfc18f5e01cf904f25): failed to bind port 192.168.175.43:8080/tcp: Error starting userland proxy: failed to listen on 127.0.0.1:8080: listen tcp4 127.0.0.1:8080: bind: address already in use.
```

With `--userland-proxy=false` ...

```
$ docker run --rm -ti --network n1 -p 8080:80 nginx
-> no docker-proxy process
-> curl works for http://127.0.0.1:8080, http://192.168.175.43:8080 - but not http://[::1]:8080

$ docker run --rm -ti --network n1 -p 192.168.175.43:8080:80 nginx
-> no docker-proxy process
-> curl works for http://192.168.175.43:8080
```

**- Description for the changelog**
```markdown changelog
- Close a window in which `docker-proxy` could accept TCP connections, which would fail after NAT rules were set up. The `docker-proxy` binary has been updated, the old version will not work with the updated `dockerd`.
- The executable `rootlesskit-docker-proxy` is no longer used, it has been removed from the build.
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hmm.. looks like this is the one I needed;


- https://github.com/moby/moby/pull/48149

That one also is marked for 27.2, so let me first open a PR for that.

**Comment by AkihiroSuda** [comment]
Isn't this too big and risky for cherrypicking?

**Review by Roya001 — APPROVED** [review]

**Review by Roya001 — APPROVED** [review]

**Review by Roya001 — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
@thaJeztah @vvoland WDYT? At least this can't be cherrypicked in a patch release

**Comment by thaJeztah** [comment]
Oh, sorry didn't reply to you @AkihiroSuda - yes, this one was marked for cherry-picking, but I don't think we will. I had similar concerns and discussed with @akerouanton (Rob is on vacation) and I don't think this one was critical to have.

**Comment by akerouanton** [comment]
Nope, nothing critical. We intentionnally replaced a bug by another bug (with a smaller blast radius) in v27.0. This PR fixes the latter. I agree it's too big / risky to backport to a patch.

**Pull request closed without merging**
