### PR TITLE
integration: fix cleanup of raft data

### PR DESCRIPTION
**Pull request by thaJeztah**
The directory used for storage was either changed or new directories
were added.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Maybe don't cleanup if `t.Failed()`?

**Comment by thaJeztah** [comment]
Yes, I wanted to look at that as well (had a branch with some changes in that area); this also need changes to the CI script though, because it's only archiving specific files currently; https://github.com/moby/moby/blob/989d497d51fe678a02c5fcf8320c8008d9a3f868/Jenkinsfile#L103-L104

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
Fair enough, though could be helpful for local testing as well. But can easily be done separately.

**Comment by andrewhsu** [comment]
Looks like new type of [failure](https://jenkins.dockerproject.org/job/Docker-PRs/54812/console) to me in the janky PR check:
```
--- FAIL: Test (3896.19s)
panic: DockerSwarmSuite.TestSwarmJoinPromoteLocked test timed out after 5m0s [recovered]
	panic: DockerSwarmSuite.TestSwarmJoinPromoteLocked test timed out after 5m0s
```

**Comment by thaJeztah** [comment]
(rebased to get the latest fixes in)

**Comment by thaJeztah** [comment]
Looks like these docker-py tests are flaky; https://jenkins.dockerproject.org/job/Docker-PRs/54821/console

```
13:43:50 ______________ RestartContainerTest.test_restart_with_low_timeout ______________
13:43:50 /docker-py/tests/integration/api_container_test.py:1173: in test_restart_with_low_timeout
13:43:50     self.client.restart(container, timeout=3)
13:43:50 /docker-py/docker/utils/decorators.py:19: in wrapped
13:43:50     return f(self, resource_id, *args, **kwargs)
13:43:50 /docker-py/docker/api/container.py:1052: in restart
13:43:50     res = self._post(url, params=params, timeout=conn_timeout)
13:43:50 /docker-py/docker/utils/decorators.py:46: in inner
13:43:50     return f(self, *args, **kwargs)
13:43:50 /docker-py/docker/api/client.py:221: in _post
13:43:50     return self.post(url, **self._set_request_timeout(kwargs))
13:43:50 /usr/lib/python2.7/dist-packages/requests/sessions.py:535: in post
13:43:50     return self.request('POST', url, data=data, json=json, **kwargs)
13:43:50 /usr/lib/python2.7/dist-packages/requests/sessions.py:488: in request
13:43:50     resp = self.send(prep, **send_kwargs)
13:43:50 /usr/lib/python2.7/dist-packages/requests/sessions.py:609: in send
13:43:50     r = adapter.send(request, **kwargs)
13:43:50 /usr/lib/python2.7/dist-packages/requests/adapters.py:499: in send
13:43:50     raise ReadTimeout(e, request=request)
13:43:50 E   ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=4)
13:43:50 _______________________ ExecTest.test_exec_command_demux _______________________
13:43:50 /docker-py/tests/integration/api_exec_test.py:169: in test_exec_command_demux
13:43:50     assert next(exec_log) == b'hello out\r\n'
13:43:50 E   AssertionError: assert 'hello out\r\nhello err\r\n' == 'hello out\r\n'
13:43:50 E       hello out

13:43:50 E     - hello err
13:43:50 - generated xml file: /go/src/github.com/docker/docker/bundles/test-docker-py/results.xml -
```

**Comment by thaJeztah** [comment]
All green now! @yongtang @AkihiroSuda ptal 🤗

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
