### PR TITLE
Update centos.md

### PR DESCRIPTION
**Pull request by vegasbrianc**
Added instructions for the workaround for CentOS minimal installation where the Docker daemon cannot start due to a conflict with the CentOS firewall

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @vegasbrianc! I see some issues with the formatting, but I'm also not sure this is needed now that https://github.com/docker/docker/pull/15832 is merged, and will be in the 1.9 release. There probably won't be a update to docs.docker.com before the 1.9 release, in which case the extra instruction is obsolete at the time it's published on the website.

I hope you understand my reasoning here; please, don't be mad or disappointed if this doesn't get merged, you're contribution is appreciated, even if it doesn't find its way in :+1: 

/cc @moxiegirl @jfrazelle do you think it's worth adding this as a "note" for people using older releases?

**Comment by moxiegirl** [comment]
@vegasbrianc Thank you for the contribution. I agree with @thaJeztah tho, since the problem was fixed, I'm not sure we should document it.  The `selinux` package seems overkill too.  @thaJeztah do you have a pointer to the original issue that caused the problem? I'd like to see if maybe we need a firewall section or something.

**Comment by thaJeztah** [comment]
@moxiegirl it's this issue; https://github.com/docker/docker/issues/15498#issuecomment-130456902, basically, Docker fails to start via SystemD if selinux is enabled (https://github.com/docker/docker/issues/15498#issuecomment-134958488). The SELinux package is not overkill in this case, but a docker-provided alternative to that package  will be bundled with docker 1.9 (https://github.com/docker/docker/pull/15832)

So I don't think we have to add a Firewall section, more a troubleshooting with SELinux (to discover that it's SELinux blocking something)

**Comment by vegasbrianc** [comment]
@thaJeztah @moxiegirl thanks for the explanation.

**Comment by thaJeztah** [comment]
@vegasbrianc I'm going ahead and close this. Thanks again for your contribution!

**Pull request closed without merging**
