### PR TITLE
Fix an issue with service logs hanging

### PR DESCRIPTION
**Pull request by dperny**
This is another, more naive fix for #32826 which avoids any race conditions, big changes, task state checks, and whatever else. Problem changed.

/cc @stevvooe @aaronlehmann 

**- What I did**

Fixed an issue where logs calls were hanging if they included a task whose backing container was deleted (docker rm). This was the root cause of #31625, which this PR closes

**- How I did it**

Before this change, if the container backing a task was deleted and logs
were called, the waitReady function would wait forever for the container
to come online (which obviously will never happen) and the logs call
would hang. That behavior handles the case where a container has not YET
come up, but causes issues when a container is already dead and gone.

This skips the hanging `waitReady` if we're not doing follow. Without follow, we want whatever logs we can get RIGHT NOW, no waiting required. If the container doesn't exist, we're just going to return an error which gets logged and tossed. 

**- How to verify it**

Create service
find a container belonging to it container
stop and delete that container
call logs and note the hang is present before and absent after.

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

**Comment by aaronlehmann** [comment]
> Create service
find a container belonging to it container
stop and delete that container
call logs and note the hang is present before and absent after.

Sounds integration testable :)

**Comment by dperny** [comment]
@aaronlehmann added integration test.

**Comment by aaronlehmann** [comment]
LGTM on green

**Comment by dperny** [comment]
Might be worth mentioning that I checked and this test does in fact fail without this fix.

**Pull request merged**
