### PR TITLE
Fallback to pull from hub if mirrors unavailable.

### LINKED ISSUE #13571: docker 1.7.0-rc1 does not fall back to Docker Hub gracefully when mirror not available
Using docker 1.7.0-rc1, the docker engine will no longer fall back to using direct connection when a docker v1 mirror is not available:

```
Error response from daemon: invalid registry endpoint https://mirror.core.dckrindy.io:5000/v0/: unable to ping registry endpoint https://mirror.core.dckrindy.io:5000/v0/
v2 ping attempt failed with error: Get https://mirror.core.dckrindy.io:5000/v2/: dial tcp: lookup mirror.core.dckrindy.io on 10.0.2.3:53: server misbehaving
 v1 ping attempt failed with error: Get https://mirror.core.dckrindy.io:5000/v1/_ping: dial tcp: lookup mirror.core.dckrindy.io on 10.0.2.3:53: server misbehaving. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry mirror.core.dckrindy.io:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/mirror.core.dckrindy.io:5000/ca.crt
```

In this case, I am not in the same location as the mirror.  Previous behavior was that it would just bypass the mirror but it no longer falls back to direct connection as expected.

Docker daemon parameters:
`/usr/bin/docker -d -s overlay -H fd:// -H 0.0.0.0:2376 --tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem --tlskey=/etc/docker/server-key.pem --registry-mirror=http://mirror.core.dckrindy.io:5000`

I am running docker on debian sid using the .deb from test.docker.com.  I revered back to 1.6.2 and it works as expected.

Registry mirror is setup without anything custom: https://github.com/docker/docker/blob/master/docs/sources/articles/registry_mirror.md

Environment info:

```
mbentley@localdev ~$ docker version
Client version: 1.7.0-rc1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 395cced
OS/Arch (client): linux/amd64
Server version: 1.7.0-rc1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 395cced
OS/Arch (server): linux/amd64
mbentley@localdev ~$ docker info
Containers: 0
Images: 16
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
CPUs: 4
Total Memory: 1.959 GiB
Name: localdev
ID: ABO2:4REM:BS7R:OXYG:R7V6:UJGL:2YTX:CJ7H:UEYY:IK7O:JXYQ:YBYX
Username: mbentley
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
mbentley@localdev ~$ uname -a
Linux localdev 4.0.0-1-amd64 #1 SMP Debian 4.0.2-1 (2015-05-11) x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by RichardScothern**
If no endpoint could be established with the given mirror configuration,
fallback to pulling from the hub as per v1 behavior.

Signed-off-by: Richard Scothern richard.scothern@gmail.com

Closes #13571

### CODE REVIEW

**Comment by RichardScothern** [comment]
ping @tiborvass @dmcgowan @stevvooe

**Comment by tiborvass** [comment]
oops nice catch, LGTM

**Comment by dmcgowan** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM!

**Comment by tiborvass** [comment]
@jfrazelle needs cherrypick

**Comment by jfrazelle** [comment]
cherry-picked

**Pull request merged**
