### PR TITLE
Use spf13/cobra for docker images

### PR DESCRIPTION
**Pull request by yongtang**
This fix is part of the effort to convert commands to spf13/cobra #23211.

Thif fix coverted command `docker images` to use spf13/cobra

NOTE: As part of this fix, a new function `RequiresMaxArgs()`
has been defined in `cli/required.go`. This func returns an
error if there is not at most max args

Signed-off-by: Yong Tang yong.tang.github@outlook.com

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐮

**Comment by cpuguy83** [comment]
LGTM

**Comment by LK4D4** [comment]
@yongtang need rebase :/

**Comment by yongtang** [comment]
Thanks @vdemeester @cpuguy83 @LK4D4 for the review. The PR has been rebased and updated.

**Comment by thaJeztah** [comment]
test will be fixed by https://github.com/docker/docker/pull/23340

**Comment by thaJeztah** [comment]
Userns is green, but didn't notify GitHub;

```
15:35:57 Archiving artifacts
15:35:58 Notifying endpoint 'HTTP:https://leeroy.dockerproject.org/notification/jenkins'
15:35:58 Finished: SUCCESS
```

**Comment by thaJeztah** [comment]
LGTM

**Pull request merged**
