### PR TITLE
A fix for = in env values in linked containers

### LINKED ISSUE #12763: Environment variables with an equals sign are not available in linked containers
I'm trying to access an environment variable containing an equals sign in a linked container.

Example:
```
$ docker run -i -t --rm --name foo -e "FOO=BAR" -e "BAZ=QUX=QUUX" ubuntu /bin/bash 
root@073ecccb5a67:/# echo $FOO
BAR
root@073ecccb5a67:/# echo $BAZ
QUX=QUUX
```
Here is the result when I create a linked container in a separate terminal:
```
$ docker run -i -t --link foo:foo ubuntu /bin/bash
root@6f8edb5fbf66:/# echo $FOO_ENV_FOO
BAR
root@6f8edb5fbf66:/# echo $FOO_ENV_BAZ

root@6f8edb5fbf66:/# 
```
Am I missing some special handling for the equals sign?

### PR DESCRIPTION
**Pull request by duglin**
Closes: #12763

Signed-off-by: Doug Davis dug@us.ibm.com

### CODE REVIEW

**Comment by icecrime** [comment]
Good catch :-) LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
Needs rebase now.

**Comment by thaJeztah** [comment]
According to https://github.com/docker/docker/issues/12763#issuecomment-97465736 this PR is actually merged, but is shown as closed" due to a GitHub bug

**Pull request closed without merging**
