### PR TITLE
Revendor Microsoft/HCSShim v0.5.7

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

@cpuguy83 Revendors HCSShim to latest (v0.5.7)

cc @darrenstahlmsft @msabansal FYI.

### CODE REVIEW

**Comment by cpuguy83** [comment]
LGTM

**Comment by jhowardmsft** [comment]
Required for https://github.com/docker/docker/issues/28087 and other PRs in the pipeline.

**Comment by msabansal** [comment]
@jhowardmsft Can we please rebase hcsshim? I messed up the name it should be DisableICC not DisableICS?

**Review by thaJeztah — DISMISSED** [review]
LGTM

**Comment by jhowardmsft** [comment]
@msabansal Yup, updating now.

**Comment by jhowardmsft** [comment]
Updated to v0.5.7

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
LGTM

**Comment by jhowardmsft** [comment]
All green :)

**Comment by thaJeztah** [comment]
That means "merge" :)

**Pull request merged**
