### PR TITLE
vendor: github.com/moby/swarmkit/v2 v2.0.0-20230808164555-1983e41a9fff

### PR DESCRIPTION
**Pull request by thaJeztah**
### vendor: golang.org/x/crypto v0.3.0

full diff: https://github.com/golang/crypto/compare/v0.2.0...v0.3.0

### vendor: github.com/moby/swarmkit/v2 v2.0.0-20230808164555-1983e41a9fff

notable changes:

- Free unused volumes in more cases (https://github.com/moby/swarmkit/pull/3144)
    - addresses https://github.com/moby/moby/issues/45547
- Convert BasicKeyRequest to KeyRequest to use cloudflare/cfssl 1.x.x
- reduce direct imports of logrus

diffs:

- github.com/cloudflare/cfssl v1.6.4; full diff: https://github.com/cloudflare/cfssl/compare/5d63dbd981b5...v1.6.4
- github.com/moby/swarmkit/v2; full diff: https://github.com/moby/swarmkit/compare/bc71908479e5...60421a63a7f148ba1ec7d35c55e4cf9ac03d6b78

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
This may need follow-ups related to;

- https://github.com/moby/swarmkit/pull/3149
- https://github.com/moby/moby/issues/41371

May need:

- changes on the CLI side?
- entry in the API history (and swagger docs)
- documentation updates


/cc @dperny

**Comment by thaJeztah** [comment]
Ah, looks like we were using the deprecated bits in one of our tests as well;

```
integration-cli/benchmark_test.go:1: : # github.com/docker/docker/integration-cli [github.com/docker/docker/integration-cli.test]
integration-cli/docker_api_swarm_test.go:972:21: undefined: csr.NewBasicKeyRequest (typecheck)
```

**Comment by thaJeztah** [comment]
Interesting; getting the same error on this PR as well, @vvoland 

```
=== FAIL: github.com/docker/docker/integration/image TestSaveRepoWithMultipleImages (14.25s)
    save_test.go:110: assertion failed: error is not nil: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.44/commit?author=&comment=&container=59ea94e6e20ea01d137e306a2e89d42889a1f03f76972983f6e42f2bb3a6e253&pause=0&repo=foobar-save-multi-images-test&tag=foo": context deadline exceeded
```

**Comment by dperny** [comment]
@thaJeztah I was out sick yesterday, but I am confirming that `--security-opt` needs API, swagger, `daemon/cluster/convert`, executor, and all other manner of plumbing to make it go. However, this PR is good to merge as-is without those things. No harm in leaving it un-wired while the rest of it comes together.

**Comment by thaJeztah** [comment]
Ah, thanks! Hope you're feeling better Today!

> No harm in leaving it un-wired while the rest of it comes together.


Yup, no problem with that; we should look if we need to apply some restrictions as well if we wire-up the changes. I was thinking of some cases that are _slightly_ different in a "swarm" situation;

- custom apparmor-profiles (must be installed on the node where the task lands on)
- custom seccomp profiles (although it's possible we pass the actual profile in the API request, not the path of the profile)

We can look at / discuss those in the follow ups 👍

**Comment by dperny** [comment]
@thaJeztah We may want to merge moby/swarmkit#3150 and revendor because I used the wrong type for `SecurityOpt`, a mistake I just noticed. I can move forward with it represented as `map[string]string` in Swarmkit, but it will create the need for conversion logic, which gives everyone heartburn.

**Review by neersighted — APPROVED** [review]

**Pull request merged**
