### PR TITLE
Cherry pick docker #30145 and vendor corresponding swarmkit #1883

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
Verified that in swarmmode, plugin install (docker plugin install bboreham/weave2) and network creation (docker network create --driver=bboreham/weave2 foo works) using the plugin works.

### CODE REVIEW

**Review by mavenugo — APPROVED** [review]

**Comment by mavenugo** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by mavenugo** [comment]
@anusha-ragunathan IT failures on plugin-v1 never cease to amaze me :-(
The reason we are seeing this failure in 1.13.x branch is that, when we turned off the plugin support in 1.13.0, I added a test in this branch to make sure that swarmkit fails gracefully for plugin-v1. (It was not vendored into master due to cyclic-vendoring issues at that time).

Having said that, the test is infact correct and we must try and fail the plugin-v1 case since we are not supporting plugin-v1 with swarmkit (due to the constraints). With the new addition to support plugin-v2 in swarmkit, the `plugingetter.Get` call succeeds even for plugin-v1 and hence the network creation succeeds at the swarmkit level. But the test is expecting it to fail because we decided to gracefully fail this case during "network creation" time for plugin-v1 rather than silently fail to place the tasks when the service is created.
atm, I am not sure what is the best path forward wrt plugin-v1. do you have any suggestions ?

**Comment by mavenugo** [comment]
@anusha-ragunathan you can revert https://github.com/docker/docker/commit/c8083e873555b8265ff3965b33cce804656242b7 to get your PR moving. We can address the plugin-v1 graceful failure independently.

**Comment by anusha-ragunathan** [comment]
@mavenugo : In swarm mode, only network pluginv2 is supported; pluginv1 is not. When the plugin support was re-enabled in 1.13.x, it allowed both pluginv1 and pluginv2. We should only allow pluginv2.

I have a commit that disallows pluginv1 https://github.com/docker/docker/commit/26d54ec8ec4fa66814f295c78d0ab95c5ef6551b. Something like this will help.

**Comment by mavenugo** [comment]
@anusha-ragunathan i agree. can you pls push the PR in swarmkit ?

**Comment by anusha-ragunathan** [comment]
Waiting on https://github.com/docker/swarmkit/pull/1899 to be merged. After that, a corresponding swarmkit 1.13.x PR will be made and that will be vendored into docker/docker as part of this PR.

**Comment by mavenugo** [comment]
Thanks @anusha-ragunathan for addressing the v1 issue cleanly. 

LGTM (again)

**Comment by vieux** [comment]
LGTM (again)

**Comment by thaJeztah** [comment]
Do we have to merge this back to master as well, or will there be a separate PR @anusha-ragunathan ?

**Comment by thaJeztah** [comment]
oh, nevermind, this was a cherry pick of #30145 😊 :

**Pull request merged**
