### PR TITLE
Revert "dockerversion placeholder for library-import"

### PR DESCRIPTION
**Pull request by cpuguy83**
This reverts commit d5cd032a86617249eadd7142227c5355ba9164b4.

ping @jfrazelle @icecrime

### CODE REVIEW

**Comment by cpuguy83** [comment]
Patch of course still does not run on Windows because it's trying to merge it's local copy which is missing files due to case-sensitivity.

**Comment by jfrazelle** [comment]
lol so should we close our eyes and merge LGtM

**Comment by cpuguy83** [comment]
Really it's the same error as on @jhowardmsft's PR which would fix the issue as well.

**Comment by jfrazelle** [comment]
i feel like revert is safer for now

**Comment by jfrazelle** [comment]
yolo dont judge

**Comment by cpuguy83** [comment]
ping @vdemeester FYI

**Comment by vdemeester** [comment]
:scream: how did I not see that coming :sob: 
@jfrazelle @cpuguy83 @jhowardmsft so sorry :bow:

**Pull request merged**
