### PR TITLE
Correct username in [Org."Core Maintainers"]

### PR DESCRIPTION
**Pull request by ahmetb**
My OCD tells me to fix this.

cc: @tiborvass @shykes @vieux

### CODE REVIEW

**Comment by jfrazelle** [comment]
so at the bottom of the file tho it points to vish https://github.com/docker/docker/blob/master/MAINTAINERS#L587 so it  works

**Comment by ahmetalpbalkan** [comment]
Oh didnt notice that one. Should I fix that as well or close this PR?

**Comment by jfrazelle** [comment]
ya both would be good then they would match his GH username :)

**Comment by crosbymichael** [comment]
LGTM

**Comment by jfrazelle** [comment]
LGTM

**Pull request merged**
