### PR TITLE
Remove engine-api leftovers

### PR DESCRIPTION
**Pull request by thaJeztah**
f9vbu46g68hd5m3 medium

### CODE REVIEW

**Comment by vdemeester** [comment]
Lol the images :joy: 
LGTM 🐸

**Comment by duglin** [comment]
I dunno, still looks kind of hazy...
:-)

**Comment by justincormack** [comment]
LGTM

**Comment by darrenstahlmsft** [comment]
windowsRS1 CI failure was fixed by https://github.com/docker/docker/pull/26764

**Pull request merged**
