### PR TITLE
Use spf13/cobra for docker rmi

### PR DESCRIPTION
**Pull request by vdemeester**
Moves image command rmi to `api/client/image/remove.go` and use cobra  🐍.

/cc @dnephin @thaJeztah @LK4D4 

🐸

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by dnephin** [comment]
LGTMa

**Comment by cpuguy83** [comment]
LGTM

**Comment by cpuguy83** [comment]
This needs a rebase

**Comment by vdemeester** [comment]
Rebased :angel:

**Comment by vdemeester** [comment]
Ah userns is green, just didn't tell GitHub about it :sweat:

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
