### PR TITLE
update VPNKit

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Changes: (20190201-20200304): https://github.com/moby/vpnkit/compare/67041ad2655038c5462b3466f89a1853f2b894e5...v0.4.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
should a new version be tagged, @djs55 ?

**Comment by djs55** [comment]
I think it's a good time to tag a new vpnkit release. I've tagged the commit proposed here moby/vpnkit@6bc1679 as `v0.4.0` (previously we had `v0.3.0`). Let me know if you'd like another one!

**Comment by AkihiroSuda** [comment]
Thanks, could you also tag https://hub.docker.com/r/djs55/vpnkit/tags ?

**Comment by djs55** [comment]
Sure, I've pushed `djs55/vpnkit:0.4.0`:
```
$ docker push djs55/vpnkit:0.4.0
The push refers to repository [docker.io/djs55/vpnkit]
7f2198c7cea8: Layer already exists 
0.4.0: digest: sha256:e0e226d66cf3a7f2b4c3707aba207d4803be8a4f3a4e070a380de6d737a44669 size: 528
```

**Comment by thaJeztah** [comment]
Thanks @djs55 !

**Comment by AkihiroSuda** [comment]
Thanks, updated

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@cpuguy83 ptal (easy one)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
