### PR TITLE
Supplement the omission of pr#41145

### PR DESCRIPTION
**Pull request by wanghuaiqing2010**
Signed-off-by: wanghuaiqing <wanghuaiqing@loongson.cn>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by wanghuaiqing2010** [comment]
The problem is related to #41145

**Comment by wanghuaiqing2010** [comment]
@tianon ptal

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
Great catch, LGTM

**Pull request merged**
