### PR TITLE
integration-cli: use Devicemapper test requirement instead of checkin…

### PR DESCRIPTION
**Pull request by runcom**
…g strings

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
Looks like the lines above are now redundant as well?

**Comment by runcom** [comment]
Mm I thought they were needed because the tests later use them

**Comment by thaJeztah** [comment]
@runcom oh, could be, perhaps I overlooked, but didn't see them being used at a glance

**Pull request merged**
